### ISSUE TITLE
Issue with FSDP + HuggingFace generate

### ISSUE THREAD

**Issue by dakinggg** [pytorch/pytorch#100069]
### 🐛 Describe the bug

Calling `.generate` on a HuggingFace model that has been FSDP wrapped results in an error. I was able to work around this error by summoning full params without recurse, which just summons the LM head and avoids the issue.

Script with a minimal(ish) repro:
```python
import torch
import transformers

from composer.utils import dist

def _auto_wrap_policy(module: torch.nn.Module, recurse: bool, nonwrapped_numel: int) -> bool:
    if recurse:
        return True
    if hasattr(module, '_fsdp_wrap'):
        return bool(module._fsdp_wrap)
    return False

def main():
    # initialize dist
    dist.initialize_dist(None)

    # load base model and tokenizer from Hugging Face
    gpt = transformers.AutoModelForCausalLM.from_pretrained('EleutherAI/gpt-neo-125m')
    gptt = transformers.AutoTokenizer.from_pretrained('EleutherAI/gpt-neo-125m')

    from torch.distributed.fsdp.fully_sharded_data_parallel import FullyShardedDataParallel as FSDP

    # This seems to cause other problems...
    # for module in gpt.modules():
    #     module._fsdp_wrap = True

    gpt._fsdp_wrap = True
    
    # move model to gpu
    gpt.to(torch.cuda.current_device())
    # FSDP wrap
    fsdp_wrapped_gpt = FSDP(gpt, auto_wrap_policy=_auto_wrap_policy, use_orig_params=False)
    print(fsdp_wrapped_gpt)

    # create the input
    input_dict = gptt('hello', return_tensors='pt')
    input_dict['input_ids'] = input_dict['input_ids'].to(torch.cuda.current_device())
    input_dict['attention_mask'] = input_dict['attention_mask'].to(torch.cuda.current_device())

    # THIS CODE IS NECESSARY IN ORDER FOR .generate TO NOT ERROR BELOW (THIS WAS A PREVIOUS WORKAROUND FROM TORCH 1.13 THAT STILL SEEMS TO BE NECESSARY)
    with torch.no_grad():
        fsdp_wrapped_gpt.forward(input_ids=input_dict['input_ids'])

    # call generate
    generation = fsdp_wrapped_gpt.generate(input_ids=input_dict['input_ids'], attention_mask=input_dict['attention_mask'], max_new_tokens=5)
    print(generation)

if __name__ == '__main__':
    main()
```

resulting error:
```python
Traceback (most recent call last):
  File "/mnt/workdisk/danielking/github/composer/scripts/fsdp_gen_repro.py", line 49, in <module>
    main()
  File "/mnt/workdisk/danielking/github/composer/scripts/fsdp_gen_repro.py", line 45, in main
    generation = fsdp_wrapped_gpt.generate(input_ids=input_dict['input_ids'], attention_mask=input_dict['attention_mask'], max_new_tokens=5)
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 741, in forward
    transformer_outputs = self.transformer(
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 578, in forward
    inputs_embeds = self.wte(input_ids)
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/mnt/workdisk/danielking/miniconda3/envs/composer-dev-torch2/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'weight' must be 2-D
```

workaround is to wrap the `.generate` call with `with FSDP.summon_full_params(self.model, writeback=False, recurse=False):`

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 515.48.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7513 32-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1777.500
CPU max MHz:                     2600.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5200.14
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-7
NUMA node1 CPU(s):               8-15
NUMA node2 CPU(s):               16-23
NUMA node3 CPU(s):               24-31
NUMA node4 CPU(s):               32-39
NUMA node5 CPU(s):               40-47
NUMA node6 CPU(s):               48-55
NUMA node7 CPU(s):               56-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.0+cu117
[pip3] torch-optimizer==0.3.0
[pip3] torchdata==0.6.0
[pip3] torchmetrics==0.11.3
[pip3] torchtext==0.15.1+cpu
[pip3] torchvision==0.15.1+cu117
[pip3] triton==2.0.0
[pip3] vit-pytorch==0.35.8
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     2.0.0+cu117              pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchdata                 0.6.0                    pypi_0    pypi
[conda] torchmetrics              0.11.3                   pypi_0    pypi
[conda] torchtext                 0.15.1+cpu               pypi_0    pypi
[conda] torchvision               0.15.1+cu117             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
[conda] vit-pytorch               0.35.8                   pypi_0    pypi

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by chauhang** [comment]
cc: @awgu @rohan-varma

**Comment by awgu** [comment]
Without digging into it too deeply yet, I think the high level issue is one we have known about: For any computation that is not in `.forward()`, FSDP does not know to unshard (and later reshard) the parameters. Previously, users have worked around this (though I am not entirely clear on their solution).

Sorry for my lack of knowledge here, but does the `generate()` method need to be autograd tracked? In other words, is `generate()` only for inference, or will you later want to compute gradients based on the `generate()` output?

Your workaround of `summon_full_params(recurse=False)` is sufficient if you do not care about `generate()` being autograd tracked. Are you okay with this work around, or are you looking for something else?

**Comment by dakinggg** [comment]
`generate()` does not need to be autograd tracked (in face it is marked with a no grad decorator). The two workaround I am aware of are

1) The line in my script following `# THIS CODE IS NECESSARY`. I wasn't entirely clear on what this actually did, but it seemed like maybe it gathered the weights but then didn't unshard them because there was no backward pass after it? It was sufficient on torch 1.13, but no longer sufficient on 2.0 (and maybe not necessary anymore either?).
2) The summon params thing. I am fine with this workaround, with one caveat. I'm not entirely sure it works with all model architectures/model wrappings. For a relatively standard architecture (`model.transformer` and `model.lm_head`, where you individually wrap each block inside the `model.transformer`), it should work fine. Context is that I am working on upgrading [composer](https://github.com/mosaicml/composer) to torch 2.0, and we make heavy use of FSDP + models that genereate.

**Comment by awgu** [comment]
Before I give more thoughts, for `generate()`, which model parameters does it require? E.g., does it require all of the model parameters or just a subset? If just a subset, which modules / how are they wrapped with FSDP?

**Comment by dakinggg** [comment]
It requires all the parameters. Basically `generate` just does multiple sequential forward passes through the model. The general way that we have been wrapping LMs is to wrap the whole model, and then individual wrap each transformer block. To make things a little more complicated, there are (often) shared weights between the input embedding layer and the output unembedding layer.

**Comment by awgu** [comment]
In that case, I am not sure how either approaches 1 or 2 work.

For 1, the root FSDP instance does not free its parameters after forward, so you can technically still run forward computation with them. (This is not part of FSDP's specified behavior though.) However, for nested non-root FSDP instances, their parameters should be freed, which is why I am curious why `generate()` did not error then.

For 2, if you only call `summon_full_params(recurse=False)` on the root FSDP instance, then a similar situation applies.

**Comment by awgu** [comment]
I think your explanation is in line with my understanding too. For `use_orig_params=True`, after you run the dummy forward, we still expose the sharded parameters. For `use_orig_params=False`, we do not expose the unsharded parameters explicitly, but as mentioned above, we leverage the unspecified behavior that the unsharded parameters are kept intact for the root FSDP instance, which in your case I believe has the weight-tied parameter.

As you described, for `use_orig_params=True`, the `summon_full_params(recurse=False)` call will keep the root FSDP instance's parameters unsharded through the entire `generate()`, but that is also the behavior for a normal forward pass. As far as I see right now, that should not increase memory usage comparatively.

---

By the way, when you guys are upgrading composer to 2.0, is there a reason you guys want to use `use_orig_params=True`? Is that for `torch.compile()`?

We do want to push for that to be the default, but we have not been keeping in check with the release deadlines too closely. I think I landed a few PRs after the branch cut for 2.0 that reduced the CPU overhead for the `use_orig_params=True` path. (The added flexibility of `use_orig_params=True` comes at the cost of some extra state management that will inevitably incur CPU overhead not present in `use_orig_params=False`.) If your users' models are not usually CPU bound, then this should not make a difference.

**Comment by dakinggg** [comment]
Thanks, thats helpful! I think I fully understand.

And yes, we are setting `use_orig_params=True` for use with compile (it also makes a few other things easier I think, but `compile` is the main reason). We haven't gotten to thorough performance checks beyond running a couple models with `compile`, but appreciate the heads up about CPU overhead as we get into that.

**Comment by dakinggg** [comment]
I leave it up to you as to whether this issue should be closed, or there is something about it you would like to leave it open for  :)

**Comment by kushalj001** [comment]
Hi @dakinggg @awgu 
I am currently training a model where running `model.generate` on an FSDP-wrapped model is resulting in errors. A minimal example looks something like this (this is not to repro):
```
# a custom auto wrap policy for llama
auto_wrap_policy = fsdp_auto_wrap_policy 
model = LlamaForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf")
fsdp_wrapped_model = FSDP(model, auto_wrap_policy, sharding_strategy=FULL_SHARD)

# a simple forward pass
outputs = fsdp_wrapped_model(input_ids=batch["input_ids"], attention_mask=batch["attention_mask, labels=batch["input_ids"])
mle_loss = outputs.loss

# generate some samples
generated_idx = fsdp_wrapped_model.generate(input_ids=batch["input_ids"],attention_mask=batch["attention_mask"],max_new_tokens=128)

gen_attention_mask = get_gen_attention_mask()
model_out = fsdp_wrapped_model(input_ids=generated_idx, attention_mask=gen_attention_mask)

# some custom logic to calculate an auxiliary loss term
logits = model_out.logits
logprobs = torch.nn.functional.log_softmax(logits, dim=-1)
unsqueeze_sample_labels = generated_idx.unsqueeze(-1) 
gathered_logprobs = torch.gather(logprobs, dim=-1, index=unsqueeze_sample_labels).squeeze(-1)
....
other_loss = get_other_loss(gathered_logprobs, generated_idx)

total_loss = mle_loss + other_loss
total_loss.backward()
```

This code fails at `fsdp_wrapped_model.generate` with the following stack trace:

```

37   File "/fsx-checkpoints/shridhar743/anaconda3/envs/llama-rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
38     return self._call_impl(*args, **kwargs)
39   File "/fsx-checkpoints/shridhar743/anaconda3/envs/llama-rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
40     return forward_call(*args, **kwargs)
41   File "/fsx-checkpoints/shridhar743/anaconda3/envs/llama-rl/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
42     args, kwargs = _pre_forward(
43   File "/fsx-checkpoints/shridhar743/anaconda3/envs/llama-rl/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 425, in _pre_forward
44     state._exec_order_data.record_pre_forward(handle, module.training)
45   File "/fsx-checkpoints/shridhar743/anaconda3/envs/llama-rl/lib/python3.9/site-packages/torch/distributed/fsdp/_exec_order_utils.py", line 166, in record_pre_forward
46     self._check_order(handle, is_training)
47   File "/fsx-checkpoints/shridhar743/anaconda3/envs/llama-rl/lib/python3.9/site-packages/torch/distributed/fsdp/_exec_order_utils.py", line 267, in _check_order
48     raise RuntimeError(
49 RuntimeError: Forward order differs across ranks: rank 0 is all-gathering parameters for [['model.layers.0.self_attn.q_proj.weight', 'model.layers.0.self_attn.k_proj.weight', 'model.layers.0.self_attn.v_proj.weight', 'model.layers.0.self_attn.o_proj.weight', 'model.layers.0.mlp.gate_proj.weight', 'model.layers.0.mlp.up_proj.weight', 'model.layers.0.mlp.down_proj.weight', 'model.layers.0.input_layernorm.weight', 'model.layers.0.post_attention_layernorm.weight']] while rank 7 is all-gathering parameters for [['model.embed_tokens.weight', 'model.norm.weight', 'lm_head.weight']]
```
I wanted to know if this is a similar issue, caused by the custom logic (that needs to be tracked by autograd) not being wrapped by FSDP and hence leading to some synchronization issues within the processes. I'll try the things mentioned above (`summon_full_params`) but wanted to understand the root cause if possible. 
Thanks!

**Comment by awgu** [comment]
@kushalj001 I do not think that is an issue related to autograd. It might be worth checking if/how rank 0 differs rank other ranks in the execution.

**Comment by kushalj001** [comment]
Hi! Yeah, I tried `summon_full_params` and it didn't help. 
Can you elaborate on checking how rank 0 execution differs? What exactly can I do to investigate this? 
(I am not explicitly doing something differently on rank 0 compared to other ranks. It seems to me that rank 0 becomes the master process and some other process fails to synchronize with it.)
Thanks!

**Comment by awgu** [comment]
For my own tracking: module pre/post-forward hooks solves this particular case since `greedy_search()` in src/transformers/generation/utils.py runs `self(...)`, which will run the hooks.

https://github.com/huggingface/transformers/blob/fd6a0ade9b89c415ea213ef1aa07c9b2c32a4d75/src/transformers/generation/utils.py#L2048C27-L2048C31

**Comment by ringohoffman** [comment]
Related:

* https://github.com/huggingface/transformers/issues/30228#issuecomment-2350022762

> So after a lot longer than I would like to admit, I have uncovered all the gotchas of using `generate` with FSDP.
> 
> 1. As I mentioned above, `torch.distributed.fsdp.FullyShardedDataParallel(use_orig_params=True)` is required when instantiating your FSDP instance. Otherwise, you get the error `The tensor has a non-zero number of elements, but its data is not allocated yet`. It seems likely that `generate` is calling a `torch.compile`-wrapped function.
> 2. Calls to `generate` must be inside a `torch.distributed.fsdp.FullyShardedDataParallel.summon_full_params(fsdp_model)` context, otherwise you get the error `'weight' must be 2-D` from the input embeddings still being flattened by FSDP.
> 3. Lastly, and most trickily, you must use `generate(synced_gpus=True)` when using differently-sized data across ranks. Otherwise, the different ranks will pause on different synchronization points leading to a deadlock.
> 
> Here is a minimum reproducible example to show these off:
> 
> ```bash
> OMP_NUM_THREADS=2 \
> TOKENIZERS_PARALLELISM=false \
> CUDA_VISIBLE_DEVICES=6,7 \
> torchrun \
>     --rdzv-backend=c10d \
>     --rdzv-endpoint=localhost:0 \
>     --nnodes=1 \
>     --nproc-per-node=2 \
>     fsdp_generate.py
> ```
> 
> **fsdp_generate.py**
> ```python
> import functools
> 
> import torch
> import torch.distributed
> import torch.distributed.fsdp
> import torch.distributed.fsdp.wrap
> import transformers
> import transformers.models.gpt_neo.modeling_gpt_neo
> 
> 
> def main() -> None:
>     torch.distributed.init_process_group(world_size=2)
>     device = torch.device(torch.distributed.get_rank())
>     torch.cuda.set_device(device)
> 
>     pretrained_model_name_or_path = "EleutherAI/gpt-neo-125m"
>     model = transformers.AutoModelForCausalLM.from_pretrained(
>         pretrained_model_name_or_path,
>         device_map=device,
>     )
>     assert isinstance(model, transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoForCausalLM)
>     tokenizer = transformers.AutoTokenizer.from_pretrained(
>         pretrained_model_name_or_path
>     )
>     tokenizer.pad_token_id = tokenizer.eos_token_id
> 
>     fsdp_model = torch.distributed.fsdp.FullyShardedDataParallel(
>         model,
>         auto_wrap_policy=functools.partial(
>             torch.distributed.fsdp.wrap.transformer_auto_wrap_policy,
>             transformer_layer_cls={
>                 transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoBlock
>             },
>         ),
>         limit_all_gathers=True,
>         use_orig_params=True,  # required to overcome the error "The tensor has a non-zero number of elements, but its data is not allocated yet" ... PreTrainedModel.generate is probably using some torch.compile-wrapped function
>     )
> 
>     data_by_rank = {  # differently-sized causes FSDP to hang
>         0: "Hello world!",
>         1: "The quick brown fox jumps over the lazy dog."
>     }
> 
>     batch = tokenizer(
>         data_by_rank[torch.distributed.get_rank()],
>         return_tensors="pt",
>         return_attention_mask=True,
>     ).to(device)
> 
>     with torch.distributed.fsdp.FullyShardedDataParallel.summon_full_params(fsdp_model):  # required to overcome to the error "'weight' must be 2-D"
>         generated_text = fsdp_model.module.generate(
>             input_ids=batch["input_ids"],
>             attention_mask=batch["attention_mask"],
>             max_length=20,
>             synced_gpus=True,  # True is required to use differently sized data with FSDP + generate (current default is False)
>         )
> 
>     torch.distributed.barrier()
>     torch.distributed.destroy_process_group()
> 
> 
> if __name__ == "__main__":
>     main()
> 
> ```

**Comment by yundai424** [comment]
@awgu `module pre/post-forward hooks solves this particular case since greedy_search() in src/transformers/generation/utils.py runs self(...), which will run the hooks.` iiuc this might only work when all modules in the model is wrapped with FSDP, but most people only wrap the decoder layers, leaving embedding and the last vocab projection linear still throwing the error -- that's because inside of `GenerationMixIn` the `self` is unfortunately not FSDP-wrapped one but the original `AutoModelForCausalLM` 🤔

**Comment by awgu** [comment]
@yundai424 sorry I think I kind of lost track of some of the context here.

At least in FSDP2, you can do a few things to solve generation use cases (no backward):
1. Every `FSDPModule` (the ones 'wrapped') has an `unshard` method ([code](https://github.com/pytorch/pytorch/blob/65df26f61559ec580b8e455c8833b19358298cc2/torch/distributed/_composable/fsdp/fully_shard.py#L188)) that you can call to manually all-gather the parameters in case the pre-forward hook is not able to run for whatever reason.
2. We expose an API called `register_fsdp_forward_method()`, where you can tell the `FSDPModule` that it has some method, e.g. `generate`, that we should run the FSDP pre/post-forward hooks on ([code](https://github.com/pytorch/pytorch/blob/65df26f61559ec580b8e455c8833b19358298cc2/torch/distributed/_composable/fsdp/fully_shard.py#L426C5-L426C33)).

**Comment by mori360** [comment]
We are commited to support FSDP2. Here is the migration guide https://github.com/pytorch/torchtitan/blob/main/docs/fsdp.md
