### ISSUE TITLE
Issue of HistogramObserver to handle abnormal value

### ISSUE THREAD

**Issue by leslie-fang-intel** [pytorch/pytorch#100051]
### 🐛 Describe the bug

There is a issue in `HistogramObserver ` when the input has abnormal values. Here is the script to reproduce this issue 
```
import torch
from torch.ao.quantization.observer import HistogramObserver

def test():
    obser = HistogramObserver.with_args(reduce_range=False)()
    input1 = torch.tensor([-3.4028234663852886, -0.0])
    obser(input1)
    input2 = torch.tensor([-3.4028234663852886 * 10**38, -0.0])
    obser(input2)

if __name__ == "__main__":
    test()
```

and the corresponding error message is: 
```
Traceback (most recent call last):
  File "/home/lesliefang/pytorch_1_7_1/quantization/customer_issue/MLDL-883/test2.py", line 54, in <module>
    test()
  File "/home/lesliefang/pytorch_1_7_1/quantization/customer_issue/MLDL-883/test2.py", line 50, in test
    obser(input2)
  File "/home/lesliefang/pytorch_1_7_1/quantization/frameworks.ai.pytorch.private-cpu/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lesliefang/pytorch_1_7_1/quantization/frameworks.ai.pytorch.private-cpu/torch/ao/quantization/observer.py", line 1176, in forward
    ) = self._adjust_min_max(combined_min, combined_max, self.upsample_rate)
  File "/home/lesliefang/pytorch_1_7_1/quantization/frameworks.ai.pytorch.private-cpu/torch/ao/quantization/observer.py", line 1095, in _adjust_min_max
    downsample_rate = int(
OverflowError: cannot convert float infinity to integer
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gita15539d
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.9.10 (main, Mar  2 2022, 12:02:00)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.19.5-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    1
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Genuine CPU
Stepping:              10
CPU MHz:               1199.859
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27
NUMA node1 CPU(s):     28-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.0+git8e7c2b9
[pip3] numpy==1.22.3
[pip3] torch==2.1.0a0+git72daade
[pip3] torchvision==0.16.0a0+5579995
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0                  <pip>
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-service               2.4.0           py39h3605609_14    intel
[conda] mkl-static                2023.0.0                  <pip>
[conda] mkl_fft                   1.3.1           py39hcab1719_22    intel
[conda] mkl_random                1.2.2           py39hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py39hf66a691_32    intel
[conda] numpy                     1.22.3           py39hf0956d0_5    intel
[conda] numpy-base                1.22.3           py39h45c9ace_5    intel
[conda] torchvision               0.16.0a0+5579995           <pip>

**Comment by leslie-fang-intel** [comment]
Hi @jerryzh168, the issue happens in https://github.com/pytorch/pytorch/blob/488e0effe3e8eba27cb17c314a79b0f9b3531503/torch/ao/quantization/observer.py#L1095-L1099 when try to convert float infinity to integer. Do you think it's reasonable for us to add some protection here to skip the min max updating if the input is a float infinity?

**Comment by jianan-gu** [comment]
we meet such issue in use cases (shall be more):

- https://github.com/huggingface/transformers/blob/main/src/transformers/models/gptj/modeling_gptj.py#L173
- https://github.com/huggingface/transformers/blob/ef61b1ba1a8ee9fd354b640b059c3474b676c0c5/src/transformers/models/llama/modeling_llama.py#L249
- https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L550

where attention masks contain the finite value.

**Comment by HDCharles** [comment]
> Hi @jerryzh168, the issue happens in
> 
> https://github.com/pytorch/pytorch/blob/488e0effe3e8eba27cb17c314a79b0f9b3531503/torch/ao/quantization/observer.py#L1095-L1099
> 
> when try to convert float infinity to integer. Do you think it's reasonable for us to add some protection here to skip the min max updating if the input is a float infinity?

would you want to skip the update entirely or just clamp the value to the float min/max? I can make that update in either case
