### ISSUE TITLE
Master build / CUDA9.2 for Pascal - No kernel available

### ISSUE THREAD

**Issue by mfuntowicz** [pytorch/pytorch#10002]
Hi ! I'm experiencing an issue after building Pytorch from the master branch (commit 3609977) targetting P100 GPUs. Everything goes fine during the compilation, and I'm able to import/create tensors etc. Then, we I try to run the training script for my network, I got : 

```
Multi-GPU setup using devices: [0, 1, 2, 3]
  0%|                                                         | 0/100000 [00:00<?, ?it/s]THCudaCheck FAIL file=/home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu line=244 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    for epoch, batch in zip(trg, loader):
  File "/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/batch.py", line 27, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py", line 186, in process
    tensor = self.numericalize(padded, device=device)
  File "/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py", line 659, in numericalize
    padded_batch = torch.stack(numericalized)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu:244
```

**Build info:**
- OS : Centos 7
- gcc : 4.8.5
- cuda : 9.2
- cudnn 7.1.3
- nccl : 2.2.13
- magma : magma-cuda92
- target arch : 6.0 (auto detected)

**Comment by mfuntowicz** [comment]
My mistake, sorry.

Closing.
