### ISSUE TITLE
got device_ids [0], output_device 0, and module parameters {device(type='cpu')}.

### ISSUE THREAD

**Issue by alicera** [pytorch/pytorch#100243]
### 🐛 Describe the bug

```
LOCAL_RANK    0 cuda:0
Traceback (most recent call last):
  File "train_ddp.py", line 70, in <module>
    main(opt)    
  File "train_ddp.py", line 57, in main
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[LOCAL_RANK],output_device=LOCAL_RANK)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 508, in __init__
    self._log_and_throw(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 604, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cpu')}.
```
my machine is
LOCAL_RANK 0     , cuda:0
but get
 got device_ids [0], output_device 0, and module parameters {device(type='cpu')}

I try to inference ddp but meet the error. 
reference  this
https://github.com/pytorch/examples/tree/main/distributed/ddp#argument-passing-convention

command 
```
python -m torch.distributed.launch --nproc_per_node=4 train_ddp.py
```

### Versions

https://github.com/pytorch/examples/tree/main/distributed/ddp#argument-passing-convention

**Comment by lieyandadao** [comment]
How you fix this ? Thanks for your reply.

**Comment by lieyandadao** [comment]
> How you fix this ? Thanks for your reply.

Answer for other guys, model to cuda before use DDP(model)
