### ISSUE TITLE
Using ddp training with different machine

### ISSUE THREAD

**Issue by alicera** [pytorch/pytorch#100310]
### 🐛 Describe the bug

I train the project with different machine
https://github.com/ultralytics/yolov5

machine 1
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host nvcr.io/nvidia/pytorch:21.09-py3
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr="192.0.1.1" --master_port=1234 train.py --device 0,1 --workers 1
```

machine 2
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host nvcr.io/nvidia/pytorch:21.09-py3
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr="192.0.1.1" --master_port=1234 train.py --device 2,3 --workers 1
```

The machine 2  error then it hang
```
  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 449) of binary: /opt/conda/bin/python
```

I try to ping the master address, it is ok.

### Versions

using ngc docker 
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

If I use the command with the same machine, it will be training successfully.

machine 1  on  docker1 
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host nvcr.io/nvidia/pytorch:21.09-py3
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr="192.0.1.1" --master_port=1234 train.py --device 0,1 --workers 1
```

machine 1  on  docker2
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host nvcr.io/nvidia/pytorch:21.09-py3
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr="192.0.1.1" --master_port=1234 train.py --device 2,3 --workers 1
```

**Comment by alicera** [comment]
here is the mini reprodece code


```
import argparse
import os
import sys
import tempfile
from time import sleep
from urllib.parse import urlparse

import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import datetime


from torch.nn.parallel import DistributedDataParallel as DDP

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def train():
    local_rank = int(os.environ["LOCAL_RANK"])
    rank = int(os.environ["RANK"])
    while True:
        print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) training...")
        model = ToyModel().cuda(local_rank)
        ddp_model = DDP(model, [local_rank])

        loss_fn = nn.MSELoss()
        optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)
        optimizer.zero_grad()
        outputs = ddp_model(torch.randn(20, 10).to(local_rank))
        labels = torch.randn(20, 5).to(local_rank)
        loss = loss_fn(outputs, labels)
        loss.backward()
        print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) loss = {loss.item()}\n")
        optimizer.step()
        sleep(1)

def run():
    env_dict = {
        key: os.environ[key]
        for key in ("MASTER_ADDR", "MASTER_PORT", "WORLD_SIZE", "LOCAL_WORLD_SIZE")
    }
    print(f"[{os.getpid()}] Initializing process group with: {env_dict}")
    dist.init_process_group(backend="nccl", timeout=datetime.timedelta(seconds=30))
    #dist.init_process_group(backend="nccl")
    train()
    dist.destroy_process_group()


if __name__ == "__main__":
    run()

```



error

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[845] Initializing process group with: {'MASTER_ADDR': '10.0.10.36', 'MASTER_PORT': '1234', 'WORLD_SIZE': '3', 'LOCAL_WORLD_SIZE': '2'}
[846] Initializing process group with: {'MASTER_ADDR': '10.0.10.36', 'MASTER_PORT': '1234', 'WORLD_SIZE': '3', 'LOCAL_WORLD_SIZE': '2'}
[846] (rank = 2, local_rank = 1) training...
[845] (rank = 1, local_rank = 0) training...
Traceback (most recent call last):
  File "test_ddp.py", line 68, in <module>
    run()
  File "test_ddp.py", line 63, in run
    train()
  File "test_ddp.py", line 42, in train
    ddp_model = DDP(model, [local_rank])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 652, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1229, internal error, NCCL version 2.15.1
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 845 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 846) of binary: /opt/conda/bin/python
ERROR:torch.distributed.elastic.agent.server.api:Error waiting on exit barrier. Elapsed: 304.41858100891113 seconds
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 906, in _exit_barrier
    store_util.barrier(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 78, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 64, in synchronize
    agent_data = get_all(store, rank, key_prefix, world_size)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 34, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.0a0+d0d6b1f', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by alicera** [comment]
how to do that?
