### ISSUE TITLE
Cannot export ONNX model with ELU operations

### ISSUE THREAD

**Issue by tengyifei** [pytorch/pytorch#10050]
## Issue description

When I export a model to ONNX format using the tracer, the following error appears:

```
Traceback (most recent call last):
  File "export.py", line 64, in <module>
    torch.onnx.export(model, data, onnx_model_path)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 84, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 140, in _export
    trace.set_graph(_optimize_graph(trace.graph(), aten))
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 95, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 40, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 368, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
TypeError: elu() got an unexpected keyword argument 'scale' (occurred when translating elu)
```

ONNX version is 1.2.2

## Code example

```python3
import torch
import onnx
import onnx.utils
from torch import nn
import numpy as np


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()
        self.linear = nn.Linear(3, 1)
        self.elu = nn.ELU()

    def forward(self, inp):
        return self.elu(self.linear(inp))

model = TestModel()
inp = torch.from_numpy(np.array([1.0, 2.0, 3.0], dtype=np.float32))
torch.onnx.export(model, inp, "model.onnx")
```

If I examine the offending "scale" attribute passed to ELU, its value is 1, which is effectively not there.

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by tengyifei** [comment]
A workaround is to roll your own version of ELU when tracing for ONNX. Same goes for SELU.

**Comment by iNLyze** [comment]
@tengyifei , could you elaborate on how you roll your own version? I tried

```python
class ELU(nn.ELU):
    def __init__(self, alpha=1., inplace=False, scale=1.):
        super(nn.ELU, self).__init__()
        self.alpha=alpha
        self.inplace=inplace
        self.scale=scale
```
but it did not help.

**Comment by mkmkmk** [comment]
I had a similar problem with the "CeLU" class, I rolled it like this, and it helped

```python
class myCELU(nn.Module):
    def __init__(self, alpha=1.):
        super(myCELU, self).__init__()
        self.alpha = alpha

    def forward(self, input):
        # return F.celu(input, self.alpha, self.inplace)
        # max(0,x)+min(0,α∗(exp(x/α)−1))
        zeros = torch.zeros(input.shape)
        return torch.max(zeros, input) + torch.min(zeros, self.alpha * (torch.exp(input)/self.alpha - 1) ) 
```

**Comment by garymm** [comment]
Seems this is not reproducible in torch 1.9.0. Must have been fixed at some point. Please open another issue if this is still happening.
