### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by DaKeZhang7412** [pytorch/pytorch#100694]
### 🐛 Describe the bug

I am trying to run the following code in VS code:

```python
import torch
x = torch.rand(5, 3)
print(x)
```
Unfortunately, I'm getting the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\__init__.py", line 934, in <module>        
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage, _warn_typed_storage_removal
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\storage.py", line 12, in <module>
    import numpy as np
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\__init__.py", line 148, in <module>        
    from . import _distributor_init
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```

### Versions

get same error when trying to run

> python collect_env.py

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht

**Comment by malfet** [comment]
This does not sound like a PyTorch issue, as `import numpy` will fail the same way for you. Please file an issue against https://github.com/numpy/numpy
