### ISSUE TITLE
inductor cpp wrapper: crash when disable lowmem_dropout

### ISSUE THREAD

**Issue by blzheng** [pytorch/pytorch#100792]
### 🐛 Describe the bug

inductor cpp wrapper: crash when disable lowmem_dropout

Reproduce ut:
```
import torch
import torch._dynamo
import torch._inductor.config as config
dropout = torch.nn.Dropout(p=0.1, inplace=False)

@config.patch(cpp_wrapper=True, lowmem_dropout=False)
@torch._dynamo.optimize("inductor")
def fn(a):
    return dropout(a)

x = torch.rand([64, 4, 128, 128])
out = fn(x)
```

Error message:
```
Traceback (most recent call last):
  File "test_dropout_cpp.py", line 12, in <module>
    out = fn(x)
  File "/home/bzheng/anaconda3/envs/torchdynamo/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/eval_frame.py", line 282, in _fn
    return fn(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/eval_frame.py", line 435, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/convert_frame.py", line 519, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/convert_frame.py", line 122, in _fn
    return fn(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/convert_frame.py", line 355, in _convert_frame_assert
    return _compile(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/convert_frame.py", line 425, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/convert_frame.py", line 410, in transform
    tracer.run()
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2010, in run
    super().run()
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 703, in run
    and self.step()
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 663, in step
    getattr(self, inst.opname)(inst)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2098, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/output_graph.py", line 698, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/bzheng/anaconda3/envs/torchdynamo/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/output_graph.py", line 800, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/output_graph.py", line 859, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/output_graph.py", line 855, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 108, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/backends/inductor.py", line 9, in inductor
    return compile_fx(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 628, in compile_fx
    return compile_fx_with_cpp_wrapper(
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 533, in compile_fx_with_cpp_wrapper
    return compile_fx(
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 728, in compile_fx
    return aot_autograd(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/backends/common.py", line 56, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3334, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2975, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/bzheng/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1911, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/bzheng/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2082, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/bzheng/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1348, in aot_dispatch_base
    compiled_fw = compiler(fw_module, adjusted_flat_args)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 684, in fw_compiler_base
    return inner_compile(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
  File "/home/bzheng/anaconda3/envs/torchdynamo/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 211, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/bzheng/workspace/pytorch/torch/_inductor/graph.py", line 717, in compile_to_fn
    return self.compile_to_module().call
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/graph.py", line 695, in compile_to_module
    mod = PyCodeCache.load(code, linemap=linemap)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 706, in load
    return cls.load_by_key_path(key, path, linemap)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 721, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_bzheng/kc/ckckgql4t3stalfakr53hkwhau5nn4ee4m2aeh5arfaszir6iqud.py", line 60, in <module>
    module = load_inline(
  File "/home/bzheng/workspace/pytorch/torch/utils/cpp_extension.py", line 1433, in load_inline
    return _jit_compile(
  File "/home/bzheng/workspace/pytorch/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/bzheng/workspace/pytorch/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/bzheng/workspace/pytorch/torch/utils/cpp_extension.py", line 1910, in _run_ninja_build
    raise RuntimeError(message) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Error building extension 'inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll': [1/2] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -I/home/bzheng/workspace/tests/-I/home/bzheng/workspace/pytorch/torch/include -I/home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include -I/home/bzheng/workspace/pytorch/torch/include/TH -I/home/bzheng/workspace/pytorch/torch/include/THC -I/home/bzheng/anaconda3/envs/torchdynamo/include/python3.8 -isystem /home/bzheng/workspace/pytorch/torch/include -isystem /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include -isystem /home/bzheng/workspace/pytorch/torch/include/TH -isystem /home/bzheng/workspace/pytorch/torch/include/THC -isystem /home/bzheng/anaconda3/envs/torchdynamo/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -std=c++17 -Wno-unused-variable -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -Wall -DCPU_CAPABILITY_AVX512 -D C10_USING_CUSTOM_GENERATED_MACROS -c /home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp -o main.o 
FAILED: main.o 
c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -I/home/bzheng/workspace/tests/-I/home/bzheng/workspace/pytorch/torch/include -I/home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include -I/home/bzheng/workspace/pytorch/torch/include/TH -I/home/bzheng/workspace/pytorch/torch/include/THC -I/home/bzheng/anaconda3/envs/torchdynamo/include/python3.8 -isystem /home/bzheng/workspace/pytorch/torch/include -isystem /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include -isystem /home/bzheng/workspace/pytorch/torch/include/TH -isystem /home/bzheng/workspace/pytorch/torch/include/THC -isystem /home/bzheng/anaconda3/envs/torchdynamo/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -std=c++17 -Wno-unused-variable -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -Wall -DCPU_CAPABILITY_AVX512 -D C10_USING_CUSTOM_GENERATED_MACROS -c /home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp -o main.o 
In file included from /home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:4:
/tmp/torchinductor_bzheng/5b/c5bcubr6yrbvnx73gevjlm24khhax3e2tzjnnvb47oxio6qm462z.h:110: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  110 |   #pragma unroll
      | 
/tmp/torchinductor_bzheng/5b/c5bcubr6yrbvnx73gevjlm24khhax3e2tzjnnvb47oxio6qm462z.h:139: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  139 | #pragma unroll
      | 
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp: In function ‘std::vector<at::Tensor> inductor_entry_cpp(const std::vector<at::Tensor>&)’:
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:47:5: error: ‘aten’ was not declared in this scope
   47 |     aten.bernoulli_(buf1, 0.9)
      |     ^~~~
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:47:5: note: suggested alternatives:
In file included from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/ir/ir.h:18,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/function_impl.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/method.h:7,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/object.h:6,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/module.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/samplers/serialize.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/samplers.h:8,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/datasets/chunk.h:7,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/datasets.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/all.h:9,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/extension.h:4,
                 from /home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:1:
/home/bzheng/workspace/pytorch/torch/include/ATen/core/interned_strings.h:353:1: note:   ‘c10::aten’
  353 | FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
      | ^~~~~~~~~~~~~~~~~
/home/bzheng/workspace/pytorch/torch/include/ATen/core/interned_strings.h:353:1: note:   ‘c10::namespaces::aten’
  353 | FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
      | ^~~~~~~~~~~~~~~~~
In file included from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/function_impl.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/method.h:7,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/object.h:6,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/api/module.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/samplers/serialize.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/samplers.h:8,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/datasets/chunk.h:7,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data/datasets.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/data.h:4,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include/torch/all.h:9,
                 from /home/bzheng/workspace/pytorch/torch/include/torch/extension.h:4,
                 from /home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:1:
/home/bzheng/workspace/pytorch/torch/include/torch/csrc/jit/ir/ir.h:78:11: note:   ‘torch::jit::aten’
   78 | namespace aten {
      |           ^~~~
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:48:56: error: expected primary-expression before ‘,’ token
   48 |     auto buf3 = at::empty_strided({64L, 4L, 128L, 128L}, {65536L, 16384L, 128L, 1L}, at::device(at::kCPU).dtype(at::kFloat));
      |                                                        ^
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:48:58: error: expected primary-expression before ‘{’ token
   48 |     auto buf3 = at::empty_strided({64L, 4L, 128L, 128L}, {65536L, 16384L, 128L, 1L}, at::device(at::kCPU).dtype(at::kFloat));
      |                                                          ^
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:48:84: error: expected primary-expression before ‘,’ token
   48 |     auto buf3 = at::empty_strided({64L, 4L, 128L, 128L}, {65536L, 16384L, 128L, 1L}, at::device(at::kCPU).dtype(at::kFloat));
      |                                                                                    ^
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:49:83: error: ‘buf3’ was not declared in this scope; did you mean ‘buf1’?
   49 |     kernel_cpp_1((float*)(arg0_1.data_ptr()), (float*)(buf1.data_ptr()), (float*)(buf3.data_ptr()));
      |                                                                                   ^~~~
      |                                                                                   buf1
/home/bzheng/.cache/torch_extensions/py38_cpu/inline_extension_c5c7mli22y5hpvkheu57bx7ihqg2ps7kavapfifdyxr56lex4jll/main.cpp:51:17: error: could not convert ‘{buf3}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<at::Tensor>’
   51 |     return {buf3};
      |                 ^
      |                 |
      |                 <brace-enclosed initializer list>
ninja: build stopped: subcommand failed.



You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.1.0a0+git8e69879
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          160
On-line CPU(s) list:             0-159
Thread(s) per core:              2
Core(s) per socket:              40
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2300.000
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
L1d cache:                       3.8 MiB
L1i cache:                       2.5 MiB
L2 cache:                        100 MiB
L3 cache:                        120 MiB
NUMA node0 CPU(s):               0-39,80-119
NUMA node1 CPU(s):               40-79,120-159
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.6
[pip3] dalle2-pytorch==1.10.5
[pip3] ema-pytorch==0.1.1
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] intel-extension-for-pytorch==2.0.0+git42d5ba6
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] open-clip-torch==2.16.0
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.1.5
[pip3] torch==2.1.0a0+git675029a
[pip3] torch-fidelity==0.3.0
[pip3] torch-scatter==2.1.1+pt20cpu
[pip3] torch-sparse==0.6.17+pt20cpu
[pip3] torch-struct==0.5
[pip3] torchaudio==2.0.0a0+a8f4e97
[pip3] torchdata==0.7.0a0+f1283eb
[pip3] torchmetrics==0.11.0
[pip3] torchrec-nightly==2023.4.1
[pip3] torchtext==0.15.0a0+46e7eef
[pip3] torchvision==0.15.0a0+98c5815
[pip3] torchx==0.3.0
[pip3] vector-quantize-pytorch==0.10.14
[conda] bert-pytorch              0.0.1a4                   <pip>
[conda] clip-anytorch             2.5.2                     <pip>
[conda] CoCa-pytorch              0.0.6                     <pip>
[conda] dalle2-pytorch            1.10.5                    <pip>
[conda] ema-pytorch               0.1.1                     <pip>
[conda] functorch                 1.14.0a0+b71aa0b           <pip>
[conda] intel-extension-for-pytorch 2.0.0+git42d5ba6           <pip>
[conda] intel-extension-for-pytorch 2.1.0+git42d5ba6           <pip>
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-include               2022.2.1                  <pip>
[conda] mkl-service               2.4.0           py38h3605609_14    intel
[conda] mkl-static                2022.2.1                  <pip>
[conda] mkl_fft                   1.3.1           py38hcab1719_22    intel
[conda] mkl_random                1.2.2           py38hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py38hf66a691_32    intel
[conda] numpy                     1.22.3           py38hf0956d0_5    intel
[conda] numpy                     1.23.1                    <pip>
[conda] numpy-base                1.22.3           py38h45c9ace_5    intel
[conda] open-clip-torch           2.16.0                    <pip>
[conda] pytorch-transformers      1.2.0                     <pip>
[conda] pytorch-warmup            0.1.1                     <pip>
[conda] rotary-embedding-torch    0.1.5                     <pip>
[conda] torch                     2.1.0a0+git675029a           <pip>
[conda] torch-fidelity            0.3.0                     <pip>
[conda] torch-scatter             2.1.1+pt20cpu             <pip>
[conda] torch-sparse              0.6.17+pt20cpu            <pip>
[conda] torch-struct              0.5                       <pip>
[conda] torchaudio                2.0.0a0+a8f4e97           <pip>
[conda] torchdata                 0.7.0a0+f1283eb           <pip>
[conda] torchmetrics              0.11.0                    <pip>
[conda] torchrec-nightly          2023.4.1                  <pip>
[conda] torchtext                 0.15.0a0+46e7eef           <pip>
[conda] torchvision               0.15.0a0+98c5815           <pip>
[conda] torchx                    0.3.0                     <pip>
[conda] vector-quantize-pytorch   0.10.14                   <pip>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by chunyuan-w** [comment]
@blzheng it seems `lowmem_dropout` has been removed from the config.
I found a similar config `fallback_random` and tried to set it to both `True` and `False` and the UT could both run successfully using the latest main branch. Could you please help confirm if this issue still exists?
