### ISSUE TITLE
DISABLED test_profiler_experimental_tree (__main__.TestProfilerTree)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#100728]
Platforms: win, mac, rocm, linux

Caused by https://github.com/pytorch/pytorch/pull/97565

example links
https://hud.pytorch.org/pytorch/pytorch/commit/bf52d570d9be0167501cd6a206b7e262e6d3860c
https://ossci-raw-job-status.s3.amazonaws.com/log/13253665591
```
2023-05-05T06:52:04.6705425Z ================================== FAILURES ===================================
2023-05-05T06:52:04.6705697Z ______________ TestProfilerTree.test_profiler_experimental_tree _______________
2023-05-05T06:52:04.6705962Z Traceback (most recent call last):
2023-05-05T06:52:04.6706335Z   File "C:\actions-runner\_work\pytorch\pytorch\test\profiler\test_profiler_tree.py", line 254, in test_profiler_experimental_tree
2023-05-05T06:52:04.6706663Z     self.assertTreesMatch(
2023-05-05T06:52:04.6707007Z   File "C:\actions-runner\_work\pytorch\pytorch\test\profiler\test_profiler_tree.py", line 236, in assertTreesMatch
2023-05-05T06:52:04.6707384Z     self.assertExpectedInline(actual, expected, skip=1)
2023-05-05T06:52:04.6707764Z   File "C:\Jenkins\Miniconda3\lib\site-packages\expecttest\__init__.py", line 262, in assertExpectedInline
2023-05-05T06:52:04.6708199Z     self.assertMultiLineEqualMaybeCppStack(expect, actual, msg=help_text)
2023-05-05T06:52:04.6708687Z   File "C:\Jenkins\Miniconda3\lib\site-packages\expecttest\__init__.py", line 281, in assertMultiLineEqualMaybeCppStack
2023-05-05T06:52:04.6709109Z     self.assertMultiLineEqual(expect, actual[:len(expect)], *args, **kwargs)
2023-05-05T06:52:04.6709459Z   File "C:\Jenkins\Miniconda3\lib\unittest\case.py", line 1217, in assertMultiLineEqual
2023-05-05T06:52:04.6709778Z     self.fail(self._formatMessage(msg, standardMsg))
2023-05-05T06:52:04.6710076Z   File "C:\Jenkins\Miniconda3\lib\unittest\case.py", line 676, in fail
2023-05-05T06:52:04.6710351Z     raise self.failureException(msg)
2023-05-05T06:52:04.6710697Z AssertionError: '    [1397 chars]etach\n            cudaGetDeviceCount\n       [56 chars]ties' != '    [1397 chars]etach                                         [53 chars]    '
2023-05-05T06:52:04.6710992Z               aten::add
2023-05-05T06:52:04.6711167Z               aten::ones
2023-05-05T06:52:04.6711332Z                 aten::empty
2023-05-05T06:52:04.6711511Z                 aten::fill_
2023-05-05T06:52:04.6711685Z               aten::sub
2023-05-05T06:52:04.6711841Z               aten::pow
2023-05-05T06:52:04.6712023Z                 aten::result_type
2023-05-05T06:52:04.6712266Z                 aten::to
2023-05-05T06:52:04.6712428Z               aten::ones_like
2023-05-05T06:52:04.6712613Z                 aten::empty_like
2023-05-05T06:52:04.6712852Z                   aten::empty_strided
2023-05-05T06:52:04.6713030Z                 aten::fill_
2023-05-05T06:52:04.6713268Z               autograd::engine::evaluate_function: PowBackward0
2023-05-05T06:52:04.6713498Z                 PowBackward0
2023-05-05T06:52:04.6713679Z                   aten::pow
2023-05-05T06:52:04.6713892Z                     aten::result_type
2023-05-05T06:52:04.6714080Z                     aten::to
2023-05-05T06:52:04.6714258Z                     aten::copy_
2023-05-05T06:52:04.6714421Z                   aten::mul
2023-05-05T06:52:04.6714632Z                     aten::mul
2023-05-05T06:52:04.6714811Z                       aten::to
2023-05-05T06:52:04.6714981Z                         aten::_to_copy
2023-05-05T06:52:04.6715181Z                           aten::empty_strided
2023-05-05T06:52:04.6715379Z                           aten::copy_
2023-05-05T06:52:04.6715547Z                   aten::mul
2023-05-05T06:52:04.6715778Z               autograd::engine::evaluate_function: SubBackward0
2023-05-05T06:52:04.6716002Z                 SubBackward0
2023-05-05T06:52:04.6716167Z                   aten::neg
2023-05-05T06:52:04.6716397Z               autograd::engine::evaluate_function: AddBackward0
2023-05-05T06:52:04.6716615Z                 AddBackward0
2023-05-05T06:52:04.6716878Z               autograd::engine::evaluate_function: torch::autograd::AccumulateGrad
2023-05-05T06:52:04.6717144Z                 torch::autograd::AccumulateGrad
2023-05-05T06:52:04.6717363Z                   aten::new_empty_strided
2023-05-05T06:52:04.6717564Z                     aten::empty_strided
2023-05-05T06:52:04.6717742Z                   aten::copy_
2023-05-05T06:52:04.6718004Z               autograd::engine::evaluate_function: torch::autograd::AccumulateGrad
2023-05-05T06:52:04.6718286Z                 torch::autograd::AccumulateGrad
2023-05-05T06:52:04.6718478Z                   aten::detach
2023-05-05T06:52:04.6718723Z +                   detach                                                                                                  -                   detach
2023-05-05T06:52:04.6718956Z -             cudaGetDeviceCount
2023-05-05T06:52:04.6719158Z -             cudaGetDeviceCount
2023-05-05T06:52:04.6719548Z -             cudaGetDeviceProperties : To accept the new output, re-run test with envvar EXPECTTEST_ACCEPT=1 (we recommend staging/committing your changes before doing this)
2023-05-05T06:52:04.6720043Z ------------------------------ Captured log call ------------------------------
2023-05-05T06:52:04.6720451Z ERROR    numba.cuda.cudadrv.driver:driver.py:385 Call to cuInit results in CUDA_ERROR_UNKNOWN
```

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/profiler%5Ctest_profiler_tree.py%3A%3ATestProfilerTree%3A%3Atest_profiler_experimental_tree)).

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by clee2000** [comment]
dup of https://github.com/pytorch/pytorch/issues/82499 oops
