### ISSUE TITLE
MPS backend is not supported on MacOS 12.6.3

### ISSUE THREAD

**Issue by jiayisunx** [pytorch/pytorch#100879]
### 🐛 Describe the bug

ERROR: test_output_match_zero__cpu_uint8 (__main__.TestConsistencyCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    raise rte
  File "/Users/ec2-user/pytorch/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/Users/ec2-user/pytorch/torch/testing/_internal/common_device_type.py", line 846, in test_wrapper
    return test(*args, **kwargs)
  File "/Users/ec2-user/pytorch/test/test_mps.py", line 10350, in test_output_match
    mps_sample = cpu_sample.transform(
  File "/Users/ec2-user/pytorch/torch/testing/_internal/opinfo/core.py", line 264, in transform
    tt(self.input),
  File "/Users/ec2-user/pytorch/torch/testing/_internal/opinfo/core.py", line 251, in tt
    return _tt(t)
  File "/Users/ec2-user/pytorch/torch/testing/_internal/opinfo/core.py", line 248, in _tt
    return f(t)
  File "/Users/ec2-user/pytorch/test/test_mps.py", line 10351, in <lambda>
    lambda x: x.detach().to("mps").requires_grad_(x.requires_grad) if isinstance(x, torch.Tensor) else x)
RuntimeError: The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`

----------------------------------------------------------------------
Ran 4506 tests in 57.884s

FAILED (errors=2687, skipped=159, expected failures=1561)
(pt) ec2-user@ip-172-31-44-228 test %
(pt) ec2-user@ip-172-31-44-228 test % sw_vers
ProductName:    macOS
ProductVersion: 12.6.3
BuildVersion:   21G419

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gita3989b2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.16 (main, Mar  8 2023, 04:29:44)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.1.0a0+gita3989b2
[conda] mkl                       2023.1.0         h59209a4_43558
[conda] mkl-include               2023.1.0         hecd8cb5_43558
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.1.0a0+gita3989b2           dev_0    <develop>

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Looks like you've build PyTorch from source and very likely it was compiled without MPS support. Can you please post a build logs here as well? And would this one works if one to install latest nightly?
I.e. do you mind running something like:
```
python -c "import torch;print(torch.__version__, torch.backends.mps.is_available())"
```

**Comment by ZiruiYan** [comment]
@malfet, I have the same bug with latest macOS, PyTorch and Xcode version.

**Versions**
_macOS:_ Ventura 13.4
_Xcode:_ 14.3.1(14E300c)
_PyTorch:_ 2.1.0.dev20230613

**Output of the sample code**
```
python -c "import torch;print(torch.__version__, torch.backends.mps.is_available())"
2.1.0.dev20230613 False
```

**Comment by kulinseth** [comment]
> @malfet, I have the same bug with latest macOS, PyTorch (nightly) and Xcode version.
> 
> **Versions** MacBook Pro 13-inch, 2020 _Graphics:_ Intel Iris Plus Graphics 1536 MB _macOS:_ Ventura 13.4 _Xcode:_ 14.3.1(14E300c) _PyTorch:_ 2.1.0.dev20230613
> 
> **Install via conda**
> 
> ```
> conda install pytorch torchvision torchaudio -c pytorch-nightly
> ```
> 
> **Output of the sample code**
> 
> ```
> python -c "import torch;print(torch.__version__, torch.backends.mps.is_available())"
> 2.1.0.dev20230613 False
> ```

@ZiruiYan , we don't support Intel GPUs in MPS backend. This is expected behavior.

**Comment by patrice4github** [comment]
If it helps you @jiayisunx, I was able to get closer. (BTW, let me know of your creative way to print all of this environment info automatically.

OS: macOS 12.6.5 (x86_64)  (Not your 12.6.3 but close enough)
Python version: 3.11.4 (maybe you have the freedom to upgrade there).

`(brb) pg ~/mytorch [main] $python -c "import torch;print(torch.__version__, torch.backends.mps.is_available())"                       `
`2.1.0.dev20230706 True `

**Comment by skotapati** [comment]
Closing for now. @jiayisunx please reopen if the issue is still observed with current pytorch releases
