### ISSUE TITLE
Error when using custom decomposition with dynamo

### ISSUE THREAD

**Issue by jfix71** [pytorch/pytorch#101066]
### 🐛 Describe the bug

I'm trying to roll my own decomposition for `aten.add`, as I don't want to have type promotion, but I do want to decompose the `alpha` multiplication outside of the addition of the inputs:

```python
from torch._dynamo import export
import torch
import torch.nn as nn

torch._dynamo.reset()

class BasicModule(nn.Module):
    def forward(self, x, y):
        return x + y

mod, input = BasicModule(), torch.randn(2, 3).to(dtype=torch.float16)

import torch._prims as prims
aten = torch._ops.ops.aten

def my_add_decomp(a, b, alpha):
    return prims.add.default(a, aten.mul.Scalar(b, alpha))
gm, _ = export(mod, input, input, aten_graph=True, decomposition_table={torch.ops.aten.add.Tensor: my_add_decomp})
gm.print_readable()
```

However this results in an error about adding FakeTensors:
```
unsupported operand type(s) for +: 'FakeTensor' and 'FakeTensor'

While executing %add : [#users=1] = call_function[target=operator.add](args = (%l_x_, %l_y_), kwargs = {})
Original traceback:
  File "<ipython-input-27-9c568b87b1b5>", line 9, in forward
    return x + y
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-9c568b87b1b5> in <module>
     16 def my_add_decomp(a, b, alpha):
     17     return prims.add.default(a, aten.mul.Scalar(b, alpha))
---> 18 gm, _ = export(mod, input, input, aten_graph=True, decomposition_table={torch.ops.aten.add.Tensor: my_add_decomp})
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/_dynamo/eval_frame.py in export(f, aten_graph, pre_autograd, decomposition_table, tracing_mode, constraints, assume_static_by_default, functionalize, *args, **kwargs)
    981         with enable_python_dispatcher(), fake_mode:
    982             try:
--> 983                 graph = make_fx(
    984                     graph_with_interpreter,
    985                     decomposition_table=decomposition_table,
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/experimental/proxy_tensor.py in wrapped(*args)
    776         with decompose(decomposition_table), fake_tensor_mode, python_dispatcher_mode, \
    777              sym_mode, proxy_mode, disable_autocast_cache(), disable_proxy_modes_tracing(enable_current=True):
--> 778             t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_autograd), tracer=fx_tracer, concrete_args=tuple(phs))
    779 
    780         # TODO: kind of a bad way to do it, should maybe figure out a better way
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/_dynamo/eval_frame.py in _fn(*args, **kwargs)
    280             dynamic_ctx.__enter__()
    281             try:
--> 282                 return fn(*args, **kwargs)
    283             finally:
    284                 set_eval_frame(prior)
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/_dynamo/external_utils.py in inner(*args, **kwargs)
     15     @functools.wraps(fn)
     16     def inner(*args, **kwargs):
---> 17         return fn(*args, **kwargs)
     18 
     19     return inner
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/experimental/proxy_tensor.py in dispatch_trace(root, tracer, concrete_args)
    472         concrete_args: Optional[Tuple[Any, ...]] = None,
    473 ) -> GraphModule:
--> 474     graph = tracer.trace(root, concrete_args)
    475     name = root.__class__.__name__ if isinstance(root, torch.nn.Module) else root.__name__
    476     return GraphModule(tracer.root, graph, name)
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/_dynamo/eval_frame.py in _fn(*args, **kwargs)
    280             dynamic_ctx.__enter__()
    281             try:
--> 282                 return fn(*args, **kwargs)
    283             finally:
    284                 set_eval_frame(prior)
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/_dynamo/external_utils.py in inner(*args, **kwargs)
     15     @functools.wraps(fn)
     16     def inner(*args, **kwargs):
---> 17         return fn(*args, **kwargs)
     18 
     19     return inner
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/_symbolic_trace.py in trace(self, root, concrete_args)
    776                     "output",
    777                     "output",
--> 778                     (self.create_arg(fn(*args)),),
    779                     {},
    780                     type_expr=fn.__annotations__.get("return", None),
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/experimental/proxy_tensor.py in wrapped(*proxies)
    489             track_tensor_tree(flat_tensors, flat_proxies, constant=None, tracer=tracer)
    490 
--> 491         out = f(*tensors)
    492         out = pytree.tree_map_only(
    493             torch.Tensor,
<string> in <lambda>(arg0, arg1)
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/_dynamo/eval_frame.py in graph_with_interpreter(*args)
    977                         torch._disable_functionalization()
    978                 else:
--> 979                     return torch.fx.Interpreter(graph).run(*args)
    980 
    981         with enable_python_dispatcher(), fake_mode:
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/interpreter.py in run(self, initial_env, enable_io_processing, *args)
    136 
    137             try:
--> 138                 self.env[node] = self.run_node(node)
    139             except Exception as e:
    140                 if self.extra_traceback:
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/interpreter.py in run_node(self, n)
    193             assert isinstance(args, tuple)
    194             assert isinstance(kwargs, dict)
--> 195             return getattr(self, n.op)(n.target, args, kwargs)
    196 
    197     # Main Node running APIs
/mnt/xarfuse/uid-66150/feadae94-seed-nspid4026531836_cgpid45336301-ns-4026531840/torch/fx/interpreter.py in call_function(self, target, args, kwargs)
    265 
    266         # Execute the function and return the result
--> 267         return target(*args, **kwargs)
    268 
    269     @compatibility(is_backward_compatible=True)
TypeError: unsupported operand type(s) for +: 'FakeTensor' and 'FakeTensor'

While executing %add : [#users=1] = call_function[target=operator.add](args = (%l_x_, %l_y_), kwargs = {})
Original traceback:
  File "<ipython-input-27-9c568b87b1b5>", line 9, in forward
    return x + y
```

### Versions

Run via bento, N3584031
Version: 1849
Built: 5/9/2023 1:29:57 AM

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by voznesenskym** [comment]
I can take this

**Comment by voznesenskym** [comment]
```
from torch._dynamo import export
import torch
import torch.nn as nn

torch._dynamo.reset()

class BasicModule(nn.Module):
    def forward(self, x, y):
        return torch.add(x, y, alpha=1)

mod, input = BasicModule(), torch.randn(2, 3).to(dtype=torch.float16)

import torch._prims as prims
aten = torch._ops.ops.aten

def my_add_decomp(a, b, *, alpha=1):
    return prims.add(a, aten.mul.Scalar(b, alpha))
    
gm, _ = export(mod, input, input, aten_graph=True, decomposition_table={torch.ops.aten.add.Tensor: my_add_decomp})
gm.print_readable()
```

This passes - does this rewrite work for you? it should be the same.

**Comment by jfix71** [comment]
Yep, works for me, thanks @voznesenskym!
