### ISSUE TITLE
[torch.compile] Passing symbolic shapes to functions that normally take integers or tuples of integers fails

### ISSUE THREAD

**Issue by philgzl** [pytorch/pytorch#101014]
### 🐛 Describe the bug

Not sure if this is a bug or intended but reporting nonetheless.

Context: I am using a downsampling layer implemented as a convolution. I want the output to have length `n/2` if `n` is even and `(n+1)/2` is n is odd, where `n=x.shape[-1]` is the length of my input `x` which can be variable. To do so I calculate the right `padding` from the kernel size and the input length parity `x.shape[-1] % 2`.

When using `torch.compile` with `dynamic=True`, if input shapes are dynamic along the last axis then `x.shape[-1]` is a symbolic integer. The output from operations directly involving `x.shape[-1]` to calculate `padding` is also a symbolic integer. This can produce an error when passing to `F.conv1d`. The error is also raised with `F.conv2d` and if there is a symbolic integer in `padding`.

Code to reproduce:
```python
import math
import torch
import torch.nn.functional as F

kernel = torch.randn(1, 1, 4)

def func(x):
    padding = math.ceil((kernel.shape[-1] + x.shape[-1] % 2) / 2) - 1
    out = F.conv1d(x, kernel, padding=padding, stride=2)
    return out

opt_func = torch.compile(func, dynamic=True)

x = torch.randn(1, 1, 175)
opt_func(x)  # passes
x = torch.randn(1, 1, 249)
opt_func(x)  # crashes
```

Produces the following error:
```
Traceback (most recent call last):
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1308, in run_node
    return node.target(*args, **kwargs)
TypeError: conv1d() received an invalid combination of arguments - got (FakeTensor, FakeTensor, stride=int, padding=SymInt), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1256, in get_fake_value
    return wrap_fake_exception(
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 850, in wrap_fake_exception
    return fn()
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1257, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1320, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in method conv1d of type object at 0x7fe83337bec0>(*(FakeTensor(..., size=(1, 1, s0)), FakeTensor(..., size=(1, 1, 4))), **{'padding': ceiling((Mod(s0, 2))/2) + 1, 'stride': 2}):
conv1d() received an invalid combination of arguments - got (FakeTensor, FakeTensor, stride=int, padding=SymInt), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)

(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/d6/0/134239/brever/temp.py", line 21, in <module>
    opt_func(x)  # crashes
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 286, in _fn
    return fn(*args, **kwargs)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 439, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 519, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 122, in _fn
    return fn(*args, **kwargs)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 355, in _convert_frame_assert
    return _compile(
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 425, in _compile
    out_code = transform_code_object(code, transform)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 410, in transform
    tracer.run()
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2010, in run
    super().run()
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 703, in run
    and self.step()
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 663, in step
    getattr(self, inst.opname)(inst)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 385, in wrapper
    return inner_fn(self, inst)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1147, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 554, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 625, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 968, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1003, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/zhome/d6/0/134239/brever/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1287, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/zhome/d6/0/134239/brever/temp.py", line 12, in func
    out = F.conv1d(x, kernel, padding=padding, stride=2)

Set torch._dynamo.config.verbose=True or TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

As a workaround I can force `padding` to be an integer by adding an if/else statement even though it looks a bit silly. Using `int(x.shape[-1] % 2)` does not work.
```python
import math
import torch
import torch.nn.functional as F

kernel = torch.randn(1, 1, 4)


def func(x):
    parity = 0 if x.shape[-1] % 2 == 0 else 1  # new line
    padding = math.ceil((kernel.shape[-1] + parity) / 2) - 1
    out = F.conv1d(x, kernel, padding=padding, stride=2)
    return out


opt_func = torch.compile(func, dynamic=True)

x = torch.randn(1, 1, 175)
opt_func(x)  # passes
x = torch.randn(1, 1, 249)
opt_func(x)  # does not crash anymore
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230508+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Scientific Linux release 7.9 (Nitrogen) (x86_64)
GCC version: (GCC) 12.3.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.17

Python version: 3.10.11 (main, Apr 15 2023, 23:15:15) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB

Nvidia driver version: 530.41.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
Stepping:              7
CPU MHz:               2900.000
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_pkg_req pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230508+cu121
[pip3] torch-ema==0.3
[pip3] torchaudio==2.1.0.dev20230508+cu121
[pip3] torchvision==0.16.0.dev20230508+cu121
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ezyang** [comment]
This still reproduces as of 5/12 47ec9cc26dc0f46d9f7d029b8ebff29e64ac5cdf

**Comment by ezyang** [comment]
Looks simple to fix. Testing.

**Comment by ezyang** [comment]
not so simple, but I think I got it.
