### ISSUE TITLE
[Dynamo] UnspecializedNNModuleVariable side effect bug

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#101102]
### 🐛 Describe the bug

Repro:
```
import torch

class MyModel(torch.nn.Module):

    def __init__(self):
        super(MyModel, self).__init__()
        self.linear = torch.nn.Linear(5, 5)

    def forward(self, x):
        return torch.nn.Dropout(0.1)(self.linear(x))

x = torch.randn(5, 5)

m = MyModel()
print(m(x))

opt_m = torch.compile(backend="eager")(m)
print(opt_m(x))
```
Error:
```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1308, in run_node
    return node.target(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/functional.py", line 1269, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
TypeError: dropout(): argument 'train' (position 3) must be bool, not NoneType
```
The above error comes from ```Dropout``` object's ```training``` attribute is ```None```. Look at ```Dropout.__init__```:
https://github.com/pytorch/pytorch/blob/2dc93c20ac6b6cea68b09dfa78fd784dcc338d1d/torch/nn/modules/dropout.py#L13-L19

It seems we only initialized ```p``` and ```inplace``` which is ```Dropout``` module's attribute, ```training``` is ```nn.Module```'s attribute, we should handle it at here:
https://github.com/pytorch/pytorch/blob/c650b12e0bf8c183b27eda5cec44316921627951/torch/_dynamo/side_effects.py#L242

However, I did an experiment for the ```object_new``` function:
```
>>> import torch
>>> cls = torch.nn.Dropout
>>> obj = object.__new__(cls)
>>> torch.nn.Module.__init__(obj)
>>> obj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/module.py", line 2392, in __repr__
    extra_repr = self.extra_repr()
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/dropout.py", line 22, in extra_repr
    return 'p={}, inplace={}'.format(self.p, self.inplace)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/module.py", line 1630, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Dropout' object has no attribute 'p'
>>> obj.training
True
```
It seems we can't initialize class attribute using this way. I'm wondering if we can enhance ```object_new``` function to cover such cases, or maybe just graph break. This is a common pattern in PyTorch builtin modules.

### Versions

N/A

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment]
cc @jansel

**Comment by yanboliang** [comment]
Update: I figured out the root cause, will send a fix soon.
