### ISSUE TITLE
Error : "not enough memory: you tried to allocate 0BG"

### ISSUE THREAD

**Issue by umepy** [pytorch/pytorch#10115]
What is this error? this is very strange.
I have enough RAM(32GB) and checked that it did not use RAM more than 10GB.
When i add the code which makes my torch model to use .cpu() and .cuda() many times, this error happen.
What cause this error?

```
Traceback (most recent call last):
  File "/home/umeco/.pyenv/versions/anaconda2-4.1.1/envs/py36/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/umeco/.pyenv/versions/anaconda2-4.1.1/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/umeco/PycharmProjects/Apex/apex/main_learner.py", line 68, in main
    execute = learner.replay()
  File "/home/umeco/PycharmProjects/Apex/apex/learner.py", line 63, in replay
    self.main_net.to('cpu')
  File "/home/umeco/.pyenv/versions/anaconda2-4.1.1/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in to
    return self._apply(convert)
  File "/home/umeco/.pyenv/versions/anaconda2-4.1.1/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/umeco/.pyenv/versions/anaconda2-4.1.1/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/umeco/.pyenv/versions/anaconda2-4.1.1/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 377, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:204
```

##System info
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip
- OS: Ubuntu 16.04LTS
- PyTorch version: 0.4.1
- Python version: 3.6.1
- CUDA/cuDNN version: 9.1, None
- GPU models and configuration: GTX TITAN X(maxwell)

**Comment by ailzhang** [comment]
@umepy  Could you provide a simple repro script for this? Thanks!

**Comment by Ierezell** [comment]
Hello, 
I have the same problem, my laptop runs the program on Cpu with 16Gb of Ram...
Maybe it come from bad transform, format or require_grad somewhere but the error is still weird... 

I link the repo here : https://github.com/Ierezell/ProjetVision/blob/master/Ml/TestYolo2.py

Thanks in advance for your time !

**Comment by zou3519** [comment]
Closing this issue due to age (and because the problem may have been fixed already from all the changes we've made over the years). Please feel free to open a new issue if you see this again.
