### ISSUE TITLE
Type mismatch in AMP training

### ISSUE THREAD

**Issue by LuoXin-s** [pytorch/pytorch#101276]
### 🐛 Describe the bug

I run into following errors when I use amp training.

```text
Traceback (most recent call last):
  File "/home/sist/luoxin/projects/BasicSR/basicsr/train.py", line 308, in <module>
    train_pipeline(root_path)
  File "/home/sist/luoxin/projects/BasicSR/basicsr/train.py", line 252, in train_pipeline
    model.validation(val_loader, current_iter, tb_logger)
  File "/home/sist/luoxin/projects/BasicSR/basicsr/models/base_model.py", line 50, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger)
  File "/home/sist/luoxin/projects/BasicSR/basicsr/models/mae_model.py", line 487, in nondist_validation
    self.nondist_validation_perception_lin(dataloader, current_iter, tb_logger)
  File "/home/sist/luoxin/projects/BasicSR/basicsr/models/mae_model.py", line 358, in nondist_validation_perception_lin
    output = regressor(d0, d1)
  File "/home/sist/luoxin/.conda/envs/py3.10+pytorch2.0+cu118+dali+cu120/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sist/luoxin/projects/BasicSR/basicsr/archs/perceptual_similarity_arch.py", line 34, in forward
    return self.model.forward(torch.cat((d0, d1, d0 - d1, d0 / (d1 + eps), d1 / (d0 + eps)), dim=1))
  File "/home/sist/luoxin/.conda/envs/py3.10+pytorch2.0+cu118+dali+cu120/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/sist/luoxin/.conda/envs/py3.10+pytorch2.0+cu118+dali+cu120/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sist/luoxin/.conda/envs/py3.10+pytorch2.0+cu118+dali+cu120/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sist/luoxin/.conda/envs/py3.10+pytorch2.0+cu118+dali+cu120/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
```

The model is:
```python
class Dist2LogitLayer(nn.Module):
    ''' takes 2 distances, puts through fc layers, spits out value between [0,1] (if use_sigmoid is True) '''
    def __init__(self, chn_mid=32, use_sigmoid=True):
        super().__init__()

        layers = [nn.Conv2d(5, chn_mid, 1, stride=1, padding=0, bias=True)]
        layers += [nn.LeakyReLU(0.2, True)]
        layers += [nn.Conv2d(chn_mid, chn_mid, 1, stride=1, padding=0, bias=True)]
        layers += [nn.LeakyReLU(0.2, True)]
        layers += [nn.Conv2d(chn_mid, 1, 1, stride=1, padding=0, bias=True)]
        if(use_sigmoid):
            layers += [nn.Sigmoid()]
        self.model = nn.Sequential(*layers)

    def forward(self, d0, d1, eps=0.1):
        return self.model.forward(torch.cat((d0, d1, d0 - d1, d0 / (d1 + eps), d1 / (d0 + eps)), dim=1))
```
Training code
```python
        ############
        cri = torch.nn.BCEWithLogitsLoss()
        scaler = torch.cuda.amp.GradScaler(enabled=self.use_amp)

        regressor = Dist2LogitLayer(use_sigmoid=False)

        optim_params = []
        for k, v in self.perceptual_similarity.named_parameters():
            if v.requires_grad:
                optim_params.append(v)

        for k, v in regressor.named_parameters():
            if v.requires_grad:
                optim_params.append(v)

        optimizer = Adam(optim_params, lr=1e-4 * 2048 / 256, betas=[0.5, 0.999])

        num_iter_per_epoch = len(self.dataloader_bapps_train)
        scheduler = CosineLRScheduler(optimizer=optimizer, lr_min=1e-6, t_initial=12 * num_iter_per_epoch, warmup_t=3 * num_iter_per_epoch, warmup_lr_init=1e-6, warmup_prefix=True, t_in_epochs=False)

        for epoch in range(15):
            for idx, train_data in enumerate(self.dataloader_bapps_train):
                if isinstance(train_data, list):
                    train_data = train_data[0]
                p0 = train_data['p0'].to(self.device)
                p1 = train_data['p1'].to(self.device)
                ref = train_data['ref'].to(self.device)
                judge = train_data['judge'].to(self.device)

                with torch.cuda.amp.autocast(enabled=self.use_amp):
                    d0 = self.perceptual_similarity(p0, ref)
                    d1 = self.perceptual_similarity(p1, ref)

                    output = regressor(d0, d1)
                    # pixel loss
                    loss = cri(output, judge)

                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

                for name, module in self.perceptual_similarity.named_modules():
                    if 'lin' in name and 'conv1_1' in name:
                        module.weight.data = torch.clamp(module.weight.data, min=0)

                scheduler.step_update(epoch * num_iter_per_epoch + idx)
        ########
```
I use a ViT extracting features, and then use `Dist2LogitLayer`  fusing these features into a scale. Any advices for debugging?

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        6
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
L1d cache:                       3 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        80 MiB (64 instances)
L3 cache:                        96 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-31
NUMA node1 CPU(s):               32-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] DISTS-pytorch==0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] open-clip-torch==2.19.0
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[conda] dists-pytorch             0.1                      pypi_0    pypi
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] open-clip-torch           2.19.0                   pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi

**Comment by LuoXin-s** [comment]
Emm, I have figure out the problem. Actually, I forgot to load `regressor` into cuda. But when there is AMP context, the error information is misleading.
