### ISSUE TITLE
Pytorch 2.1.0.dev20230512 cuda not available

### ISSUE THREAD

**Issue by KeremTurgutlu** [pytorch/pytorch#101331]
### 🐛 Describe the bug

1) Created an Ubuntu 20.04 A100 machine
2) Installed CUDA as described [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network)
3) Created a new conda environment
4) Installed torch nightly

```
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch-nightly -c nvidia
```

Getting the following error:

```
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
/home/keremturgutlu/miniconda3/envs/myenv2/lib/python3.9/site-packages/torch/cuda/__init__.py:124: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at /opt/conda/conda-bld/pytorch_1683875589791/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
>>> torch.device()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Device() received an invalid combination of arguments - got (), but expected one of:
 * (torch.device device)
 * (str type, int index)

>>> torch.cud
torch.cuda                          torch.cudnn_convolution(            torch.cudnn_convolution_transpose(  
torch.cudnn_affine_grid_generator(  torch.cudnn_convolution_add_relu(   torch.cudnn_grid_sampler(           
torch.cudnn_batch_norm(             torch.cudnn_convolution_relu(       torch.cudnn_is_acceptable(          
>>> torch.cuda.device_count()
1
>>> torch.ones(1).cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/keremturgutlu/miniconda3/envs/myenv2/lib/python3.9/site-packages/torch/cuda/__init__.py", line 264, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.
>>> 
```

### Versions

Collecting environment information...
/home/keremturgutlu/miniconda3/envs/myenv2/lib/python3.9/site-packages/torch/cuda/__init__.py:124: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at /opt/conda/conda-bld/pytorch_1683875589791/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 2.1.0.dev20230512
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1030-gcp-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                        7
CPU MHz:                         2200.204
BogoMIPS:                        4400.40
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        6 MiB
L3 cache:                        38.5 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.1.0.dev20230512
[pip3] torchaudio==2.1.0.dev20230512
[pip3] torchvision==0.16.0.dev20230513
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.24.3           py39hf6e8229_1  
[conda] numpy-base                1.24.3           py39h060ed82_1  
[conda] pytorch                   2.1.0.dev20230512 py3.9_cuda12.1_cudnn8.8.1_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.1.0.dev20230512      py39_cu121    pytorch-nightly
[conda] torchtriton               2.1.0+7d1a95b046            py39    pytorch-nightly
[conda] torchvision               0.16.0.dev20230513      py39_cu121    pytorch-nightly

**Comment by Aidyn-A** [comment]
Does any of CUDA C/C++ codes (https://github.com/NVIDIA/cuda-samples) work on your machine?

**Comment by KeremTurgutlu** [comment]
> Does any of CUDA C/C++ codes (https://github.com/NVIDIA/cuda-samples) work on your machine?

It was a cloud rental, so I ended it up using nvidia NGC docker images.

**Comment by malfet** [comment]
@KeremTurgutlu what cloud provider have you used? Also, have you tried it with CUDA-11.8 (which I assume would be the cuda version in NCG container, wouldn't it?)

**Comment by KeremTurgutlu** [comment]
- Google Cloud
- I haven't tried 11.8 but directly moved to NGC container since it also had other dependency optimizations I needed
- Used this image `nvcr.io/nvidia/pytorch:23.04-py3` but I didn't specifically checked for the CUDA version

**Comment by Aidyn-A** [comment]
`nvcr.io/nvidia/pytorch:23.04-py3` comes with CUDA 12.1
