### ISSUE TITLE
The iter function cannot be used to manipulate the dataloader object

### ISSUE THREAD

**Issue by AugustueQin** [pytorch/pytorch#101327]
### 🐛 Describe the bug

The iter function cannot be used to manipulate the dataloader object

code：
import torch
from torch.utils.data import Dataset,DataLoader
import numpy as np

class WineDataset(Dataset):

    def __init__(self):
        xy = np.loadtxt('wine.csv',delimiter=",",dtype=np.float32,skiprows=1)  
        self.x = torch.from_numpy(xy[:,1:]) 
        self.y = torch.from_numpy(xy[:,[0]])  
        self.n_sample = xy.shape[0]  

    def __getitem__(self,index):
        return self.x[index],self.y[index]

    def __len__(self):  
        return self.n_sample
    
dataset = WineDataset()
# first_data = dataset[0]
# feature,labels = first_data
# print(feature,labels)

dataloader=DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=1)

print(dataloader)
datatiter = iter(dataloader)

error：Exception ignored in atexit callback: <function _exit_function at 0x10500dc60>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1842) is killed by signal: Terminated: 15. 

### Versions

？

**Comment by NivekT** [comment]
Please execute your code within a `if __name__ == '__main__':` block. Feel free to re-open if you are still experiencing issues.
