### ISSUE TITLE
functorch.compile minifier assert `assert len(ph_nodes) == len(cur_inps)` in remove_unused_inputs_unchecked

### ISSUE THREAD

**Issue by mgehre-amd** [pytorch/pytorch#101408]
### 🐛 Describe the bug

Using
```python
import torch
from torch.fx import symbolic_trace
from functorch.compile import minifier


class Model(torch.nn.Module):
    def forward(self, x):
        x = torch.ops.aten.div(x, x)
        x = torch.ops.aten.add(x, 3)
        x = torch.ops.aten.mul(x, x)
        return torch.ops.aten.sub(x, x)

model = Model()
inps = torch.randn(3)

my_module_traced = symbolic_trace(model)

def pass_checker(fx_g, inps):
    return (torch.ops.aten.mul in set([i.target for i in fx_g.graph.nodes]))

min_f, inps = minifier(my_module_traced, inps, pass_checker)
```
(a version of the code on https://pytorch.org/functorch/2.0/notebooks/minifier.html, but with a single argument to `forward`
I get
```
Started off with 6 nodes

# Working Repro with 6 nodes
inps = [(torch.Size([]), torch.float32, 'cpu'), (torch.Size([]), torch.float32, 'cpu'), (torch.Size([]), torch.float32, 'cpu')]
inps = [torch.zeros(())] + [torch.ones(shape, dtype=dtype, device=device) for (shape, dtype, device) in inps]



def forward(self, x):
    div = torch.ops.aten.div(x, x);  x = None
    add = torch.ops.aten.add(div, 3);  div = None
    mul = torch.ops.aten.mul(add, add);  add = None
    sub = torch.ops.aten.sub(mul, mul);  mul = None
    return sub
    

Trying granularity 4

Strategy: Eliminate dead code (G: 4) (6 nodes, 3 inputs)
FAIL: Eliminate dead code

Strategy: Remove unused inputs (G: 4) (6 nodes, 3 inputs)
Traceback (most recent call last):
  File "repro.py", line 21, in <module>
    min_f, inps = minifier(my_module_traced, inps, pass_checker)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 281, in minifier
    new_state = try_granularity(failing_state, granularity, use_non_granular=True)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 273, in try_granularity
    new_state = strategy(failing_state, granularity)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 110, in new_func
    new_state = strategy(deepcopy_fx_graph(old_state.graph), list(old_state.inps), granularity)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 207, in _remove_unused_wrapper
    return remove_unused_inputs_checked(ReproState(cur_graph, cur_inps))
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 201, in remove_unused_inputs_checked
    new_state = remove_unused_inputs_unchecked(cur_state)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 188, in remove_unused_inputs_unchecked
    assert len(ph_nodes) == len(cur_inps)
AssertionError
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230505+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.27

Python version: 3.8.0 (default, Dec  9 2021, 17:53:27)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-166-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True


Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.1.0.dev20230505+cpu
[pip3] torchvision==0.16.0.dev20230505+cpu
[conda] Could not collect
```

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ezyang** [comment]
You used minifier API wrong.

```
min_f, inps = minifier(my_module_traced, (inps,), pass_checker)
```

**Comment by mgehre-amd** [comment]
I see. Thanks for looking into it, and even more thanks for opening a PR to improve the usability!
