### ISSUE TITLE
"No module named 'tools.setup_helpers'" when use pip install caffe2

### ISSUE THREAD

**Issue by lcxywfe** [pytorch/pytorch#10155]
I want to use pip to install caffe, and i get "No module named 'tools.setup_helpers'"
```
$ pip install -i https://pypi.tuna.tsinghua.edu.cn/simple caffe2 --user                                                                
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, http://pypi.i.brainpp.cn/brain/dev/+simple
Collecting caffe2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0f/b5/b4824aeeef2fc0a54e6f9f090545a486c2e5db0e18faae011c16465ee917/caffe2-0.5.0a0.dev100.tar.gz (10.7MB)
    100% |████████████████████████████████| 10.7MB 2.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cv_wfeg6/caffe2/setup.py", line 108, in <module>
        from tools.setup_helpers.env import check_env_flag, check_negative_env_flag
    ImportError: No module named 'tools.setup_helpers'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cv_wfeg6/caffe2/
```

**Comment by 1f9763** [comment]
i met it too

**Comment by tastyminerals** [comment]
"We only support Anaconda packages at the moment. " is somewhat questionable considering that anaconda does not work reliably especially with local (in-house developed) pip packages.
`pip install caffe2` throws the same error for me unfortunately. Can someone please help us resolve this please?

**Comment by 5p6** [comment]
I met it too,how to solve this problem?

**Comment by mhtt66** [comment]
plugin an eye for further guideline
