### ISSUE TITLE
Inductor BatchNorm Eval Accuracy

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#101604]
### 🐛 Describe the bug

```
import torch

torch.manual_seed(0)

x = torch.rand([3, 32, 15, 15]).cuda()
mod = torch.nn.BatchNorm2d(32, eps=0.001).eval().cuda()

@torch.compile()
def foo(mod, x):
    return mod(x) + 10

out_eager = mod(x)
out_compiled = foo(mod, x)

torch.testing.assert_close(out_eager, out_compiled)
```

> Traceback (most recent call last):
  File "test/elias.py", line 15, in <module>
    torch.testing.assert_close(out_eager, out_compiled)
  File "/scratch/eellison/work/pytorch/torch/testing/_comparison.py", line 1511, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 21600 / 21600 (100.0%)
Greatest absolute difference: 10.000000953674316 at index (0, 0, 4, 12) (up to 1e-05 allowed)
Greatest relative difference: 0.9999979734420776 at index (2, 31, 2, 9) (up to 1.3e-06 allowed)

### Versions

master

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by eellison** [comment]
wow bad copy pasta. my bad!
