### ISSUE TITLE
torch.onnx.export ->couldn't export python method 

### ISSUE THREAD

**Issue by diplomatist** [pytorch/pytorch#101689]
## Issue description

When using torch. onnx. export, I get “RuntimeError:Couldn't export Python method”.
This error does not indicate which operators are incompatible that I cannot rule out the source of the error.

## Code example

```
Traceback (most recent call last):
  File "/home/hx/TensorRT/Palette-infer-demo/Palette-Image-to-Image-Diffusion-Models-main/pth2onnx.py", line 55, in <module>
    torch.onnx.export(unet_script, input, onnx_model, input_names=['unet_input', 'noise_level'], output_names=['output'], opset_version=16)
  File "/home/hx/anaconda3/envs/py38_TensorRT/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/hx/anaconda3/envs/py38_TensorRT/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/hx/anaconda3/envs/py38_TensorRT/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/hx/anaconda3/envs/py38_TensorRT/lib/python3.8/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/hx/anaconda3/envs/py38_TensorRT/lib/python3.8/site-packages/torch/onnx/utils.py", line 582, in _create_jit_graph
    module, params = _C._jit_onnx_list_model_parameters(freezed_m)
RuntimeError:
Couldn't export Python method.:
```

## System Info
```
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.13 (default, Oct 21 2022, 23:50:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：           x86_64
CPU 运行模式：   32-bit, 64-bit
字节序：         Little Endian
CPU:             24
在线 CPU 列表：  0-23
每个核的线程数： 2
每个座的核数：   12
座：             1
NUMA 节点：      1
厂商 ID：        GenuineIntel
CPU 系列：       6
型号：           85
型号名称：       Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
步进：           7
CPU MHz：        1200.078
CPU 最大 MHz：   4800.0000
CPU 最小 MHz：   1200.0000
BogoMIPS：       6999.82
虚拟化：         VT-x
L1d 缓存：       32K
L1i 缓存：       32K
L2 缓存：        1024K
L3 缓存：        19712K
NUMA 节点0 CPU： 0-23
标记：           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] numpy-quaternion==2022.4.2
[pip3] pytorch-ignite==0.4.11
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.13.0+cu116
[pip3] tritonclient==2.31.0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] numpy-quaternion          2022.4.2                 pypi_0    pypi
[conda] pytorch-ignite            0.4.11                   pypi_0    pypi
[conda] torch                     1.12.0+cu116             pypi_0    pypi
[conda] torchaudio                0.12.0+cu116             pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.13.0+cu116             pypi_0    pypi
[conda] tritonclient              2.31.0                   pypi_0    pypi
```

**Comment by diplomatist** [comment]
The problem has been resolved, Couldn’t export Python method 

The areas that indicate incompatibility do not belong to modules, but rather to Python methods. 

My model uses the ### **checkpoint** function in Python to save memory and accelerate, while onnx does not support checkpoint function acceleration.

I tested various modules of my network and found that one of the modules used the ### **checkpoint** function, which I removed and successfully exported the model in onnx format.
What I'm struggling with is that the error log doesn't yet output the exact part that creates the incompatibility, maybe torch.nn.onnx can't accommodate other python methods yet

**Comment by diplomatist** [comment]
The problem has been resolved, Couldn’t export Python method

The areas that indicate incompatibility do not belong to modules, but rather to Python methods.

My model uses the  **_checkpoint_** function in Python to save memory and accelerate, while onnx does not support checkpoint function acceleration.

I tested various modules of my network and found that one of the modules used the  **_checkpoint_** function, which I removed and successfully exported the model in onnx format.

What I'm struggling with is that the error log doesn't yet output the exact part that creates the incompatibility, maybe torch.nn.onnx can't accommodate other python methods yet

**Comment by diplomatist** [comment]
**_Checkpoint function_**  define：
```
def checkpoint(func, inputs, params, flag):
    """
    Evaluate a function without caching intermediate activations, allowing for
    reduced memory at the expense of extra compute in the backward pass.

    :param func: the function to evaluate.
    :param inputs: the argument sequence to pass to `func`.
    :param params: a sequence of parameters `func` depends on but does not
                   explicitly take as arguments.
    :param flag: if False, disable gradient checkpointing.
    """
    if flag:
        args = tuple(inputs) + tuple(params)
        return CheckpointFunction.apply(func, len(inputs), *args)
    else:
        return func(*inputs)


class CheckpointFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, run_function, length, *args):
        ctx.run_function = run_function
        ctx.input_tensors = list(args[:length])
        ctx.input_params = list(args[length:])
        with torch.no_grad():
            output_tensors = ctx.run_function(*ctx.input_tensors)
        return output_tensors

    @staticmethod
    def backward(ctx, *output_grads):
        ctx.input_tensors = [x.detach().requires_grad_(True) for x in ctx.input_tensors]
        with torch.enable_grad():
            # Fixes a bug where the first op in run_function modifies the
            # Tensor storage in place, which is not allowed for detach()'d
            # Tensors.
            shallow_copies = [x.view_as(x) for x in ctx.input_tensors]
            output_tensors = ctx.run_function(*shallow_copies)
        input_grads = torch.autograd.grad(
            output_tensors,
            ctx.input_tensors + ctx.input_params,
            output_grads,
            allow_unused=True,
        )
        del ctx.input_tensors
        del ctx.input_params
        del output_tensors
        return (None, None) + input_grads
```
