### ISSUE TITLE
  urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>  for  train_dataset = torchvision.datasets.CIFAR10(root=data_root, train=True, download=True, transform=transform_train) in one random process while rest of processes have no problem moving forward

### ISSUE THREAD

**Issue by monajalal** [pytorch/pytorch#101873]
### 🐛 Describe the bug

I get urllib and socket error for DistributedDataParallel in PyTorch when I use Azure Cluster of 4 nodes each with 4 K80 GPUs.
Please note this only happens in one out of the 16 GPUs (random process each time) and I do see that the line of code here is run with no problem in other nodes, data is being downloaded. So, I am unsure what's the cause or how to fix. Here's another of the 16 nodes showing progress:

![Screenshot from 2023-05-19 10-58-02](https://github.com/pytorch/pytorch/assets/1892917/31c9d24d-8b7d-47d9-95a0-d4bc1d1e1c30)

```
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO Bootstrap : Using eth0:10.0.0.4<0>
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO P2P plugin IBext
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NCCL_IB_PCI_RELAXED_ORDERING set by environment to 1.
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NET/IB : No device found.
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.4<0>
6fecdfc366984f4f805b5f36e562ccbc000000:42:42 [2] NCCL INFO Using network Socket
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_speed, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_width, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_speed, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_width, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_speed, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_width, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_speed, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_width, ignoring
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/0022484f-db6a-0022-484f-db6a0022484f is not a PCI device (vmbus). Attaching to first CPU
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Attribute coll of node net not found
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO === System : maxWidth 5.0 totalWidth 12.0 ===
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO CPU/0 (1/1/1)
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO + PCI[5000.0] - NIC/0
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO                 + NET[5.0] - NET/0 (0/0/5.000000)
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO + PCI[12.0] - GPU/100000 (0)
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO + PCI[12.0] - GPU/200000 (1)
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO + PCI[12.0] - GPU/300000 (2)
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO + PCI[12.0] - GPU/400000 (3)
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO ==========================================
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO GPU/200000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (0/5000.000000/LOC) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO GPU/300000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (0/5000.000000/LOC) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO GPU/400000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (0/5000.000000/LOC) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO NET/0 :GPU/100000 (3/5.000000/PHB) GPU/200000 (3/5.000000/PHB) GPU/300000 (3/5.000000/PHB) GPU/400000 (3/5.000000/PHB) CPU/0 (2/5.000000/PHB) NET/0 (0/5000.000000/LOC) 
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 5.000000/5.000000, type PHB/PHB, sameChannels 1
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Pattern 1, crossNic 0, nChannels 1, speed 6.000000/5.000000, type PHB/PHB, sameChannels 1
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type NVL/PIX, sameChannels 1
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Ring 00 : 1 -> 2 -> 3
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Ring 01 : 1 -> 2 -> 3
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Setting affinity for GPU 2 to 0fff
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Channel 00 : 2[300000] -> 3[400000] via direct shared memory
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Channel 01 : 2[300000] -> 3[400000] via direct shared memory
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Connected all rings
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Channel 00 : 2[300000] -> 1[200000] via direct shared memory
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Channel 01 : 2[300000] -> 1[200000] via direct shared memory
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO Connected all trees
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 8/8/512
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
6fecdfc366984f4f805b5f36e562ccbc000000:42:212 [2] NCCL INFO comm 0x14ae50001240 rank 2 nranks 16 cudaDev 2 busId 300000 - Init COMPLETE
NCCL version is:  (2, 10, 3)
MLflow version: 2.3.2
Tracking URI: azureml:URI
Artifact URI: URI
World size: 16
local rank is 2 and world rank is 2
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 85, in <module>
    train_dataset = torchvision.datasets.CIFAR10(root=data_root, train=True, download=True, transform=transform_train)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 141, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 430, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 131, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 79, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

`reuirements.txt`:
```
 # for local testing (cpu)
torchvision==0.12.0
torch==1.11.0
transformers==4.18.0

# for metrics reporting/plotting
# mlflow==1.25.1
# azureml-mlflow==1.41.0
mlflow==2.3.2
azureml-mlflow==1.50.0
matplotlib==3.5.2
tqdm==4.64.0
psutil==5.9.0

# for unit testing
pytest==7.1.2
```

`Dockerfile`:
```
# check release notes https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
FROM nvcr.io/nvidia/pytorch:22.04-py3

##############################################################################
# NCCL TESTS
##############################################################################
ENV NCCL_TESTS_TAG=v2.11.0

# NOTE: adding gencodes to support K80, M60, V100, A100
RUN mkdir /tmp/nccltests && \
    cd /tmp/nccltests && \
    git clone -b ${NCCL_TESTS_TAG} https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    make \
    MPI=1 MPI_HOME=/opt/hpcx/ompi \
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \
    CUDA_HOME=/usr/local/cuda && \
    cp ./build/* /usr/local/bin && \
    rm -rf /tmp/nccltests

# Install dependencies missing in this container
# NOTE: container already has matplotlib==3.5.1 tqdm==4.62.0
COPY requirements.txt ./
RUN pip install -r requirements.txt


# add ndv4-topo.xml
RUN mkdir /opt/microsoft/
ADD ./ndv4-topo.xml /opt/microsoft

# to use on A100, enable env var below in your job
# ENV NCCL_TOPO_FILE="/opt/microsoft/ndv4-topo.xml"

# adjusts the level of info from NCCL tests
ENV NCCL_DEBUG="INFO"
ENV NCCL_DEBUG_SUBSYS="GRAPH,INIT,ENV"

# Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
ENV NCCL_IB_PCI_RELAXED_ORDERING="1"
ENV CUDA_DEVICE_ORDER="PCI_BUS_ID"
ENV NCCL_SOCKET_IFNAME="eth0"
ENV NCCL_P2P_PXN_LEVEL="0"
# ENV NCCL_SOCKET_IFNAME='lo'
ENV NCCL_IB_DISABLE="1"
```

and `train-env.yaml`:
```
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: nvidia_pytorch
build:
  path: ../../../data-science/environment/
tags:
  os: ubuntu
  os_version: 20.04
  hpcx: 2.10
  mpi: openmpi
  mpi_version: 4.1.2rc4
  ucx: 1.12.0
  cuda: 11.6.2
  cudnn: 8.4.0.27
  # nccl: 2.12.10
  nccl: 2.17.1
  rdma_core: 36.0
  nsight_compute: 2022.1.1.2
  nsight_systems: "2022.2.1.31-5fe97ab"
  nccl_test: 2.11.0
  # azureml-defaults: 1.41.0
  # mlflow: 1.25.1
  azureml-defaults: 1.50.0
  mlflow: 2.3.2
  transformers: 4.18.0
```

Here's the training code:
```
import time
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
import mlflow
import os
import datetime

import configparser
import logging
import argparse

from PIL import Image

import ssl
ssl._create_default_https_context = ssl._create_unverified_context


start_time = time.time()

torch.backends.cudnn.benchmark=False
torch.backends.cudnn.deterministic=True


print("NCCL version is: ", torch.cuda.nccl.version())
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

# Set the seed for reproducibility
torch.manual_seed(42)

# Set up the data loading parameters
batch_size = 128
num_epochs = 10
num_workers = 4
pin_memory = True

# Get the world size and rank to determine the process group
world_size = int(os.environ['WORLD_SIZE'])
world_rank = int(os.environ['RANK'])
local_rank = int(os.environ['LOCAL_RANK'])

print("World size:", world_size)
print("local rank is {} and world rank is {}".format(local_rank, world_rank))

is_distributed = world_size > 1

if is_distributed:
    batch_size = batch_size // world_size
    batch_size = max(batch_size, 1)

# Set the backend to NCCL for distributed training
dist.init_process_group(backend="nccl",
                        init_method="env://",
                        world_size=world_size,
                        rank=world_rank)

# Set the device to the current local rank
torch.cuda.set_device(local_rank)
device = torch.device('cuda', local_rank)

dist.barrier()

# Define the transforms for the dataset
transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
])

# Load the CIFAR-10 dataset

data_root = './data_' + str(world_rank)
train_dataset = torchvision.datasets.CIFAR10(root=data_root, train=True, download=True, transform=transform_train)
train_sampler = torch.utils.data.distributed.DistributedSampler(dataset=train_dataset, num_replicas=world_size, rank=world_rank, shuffle=True) if is_distributed else None
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=(train_sampler is None), num_workers=num_workers, pin_memory=pin_memory, sampler=train_sampler)

test_dataset = torchvision.datasets.CIFAR10(root=data_root, train=False, download=True, transform=transform_test)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin_memory)

# Define the ResNet50 model
model = torchvision.models.resnet50(pretrained=True)
num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 10)

# Move the model to the GPU
model = model.to(device)

# Wrap the model with DistributedDataParallel
if is_distributed:
    model = nn.parallel.DistributedDataParallel(model, device_ids=[local_rank], output_device=local_rank)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train the model for the specified number of epochs
for epoch in range(num_epochs):
    running_loss = 0.0
    train_sampler.set_epoch(epoch) ### why is this line necessary??
    for batch_idx, (inputs, labels) in enumerate(train_loader):
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print('[Epoch %d] loss: %.3f' % (epoch + 1, running_loss))
    if world_rank == 0:
        # Log the loss and running loss as MLFlow metrics
        mlflow.log_metric("loss", loss.item())
        mlflow.log_metric("running loss", running_loss)

dist.barrier()
# Save the trained model
if world_rank == 0:
    checkpoints_path = "train_checkpoints"
    os.makedirs(checkpoints_path, exist_ok=True)
    torch.save(model.state_dict(), '{}/{}-{}.pth'.format(checkpoints_path, 'resnet50_cifar10', world_rank))
    mlflow.pytorch.log_model(model, "resnet50_cifar10_{}.pth".format(world_rank))
    # mlflow.log_artifact('{}/{}-{}.pth'.format(checkpoints_path, 'resnet50_cifar10', world_rank), artifact_path="model_state_dict")

# Evaluate the model on the test set and save inference on 6 random images
correct = 0
total = 0
with torch.no_grad():
    fig, axs = plt.subplots(2, 3, figsize=(8, 6), dpi=100)
    axs = axs.flatten()
    count = 0
    for data in test_loader:
        if count == 6:
            break
        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)

        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        # Save the inference on the 6 random images
        if count < 6:
            image = np.transpose(inputs[0].cpu().numpy(), (1, 2, 0))
            confidence = torch.softmax(outputs, dim=1)[0][predicted[0]].cpu().numpy()
            class_name = test_dataset.classes[predicted[0]]
            axs[count].imshow(image)
            axs[count].set_title(f'Class: {class_name}\nConfidence: {confidence:.2f}')
            axs[count].axis('off')
            count += 1

# Average the test accuracy across all processes

correct = torch.tensor(correct, dtype=torch.int8)
correct = correct.to(device)
torch.distributed.all_reduce(correct, op=torch.distributed.ReduceOp.SUM)
total = torch.tensor(total, dtype=torch.torch.int8)
total = total.to(device)
torch.distributed.all_reduce(total, op=torch.distributed.ReduceOp.SUM)
test_accuracy = 100 * correct / total
test_accuracy /= world_size

print('Test accuracy: %.2f %%' % test_accuracy)

# Save the plot with the 6 random images and their predicted classes and prediction confidence
test_img_file_name = 'test_images_' + str(world_rank) + '.png'
plt.savefig(test_img_file_name)

# Log the test accuracy and elapsed time to MLflow
if world_rank == 0:
    mlflow.log_metric("test accuracy", test_accuracy)

end_time = time.time()
elapsed_time = end_time - start_time
print('Elapsed time: ', elapsed_time)
if world_rank == 0:
    mlflow.log_metric("elapsed time", elapsed_time)

# Save the plot with the 6 random images and their predicted classes and prediction confidence as an artifact in MLflow
image = Image.open(test_img_file_name)
image = image.convert('RGBA')
image_buffer = np.array(image)
image_buffer = image_buffer[:, :, [2, 1, 0, 3]]
image_buffer = np.ascontiguousarray(image_buffer)
artifact_file_name = "inference_on_test_images_" + str(world_rank) + ".png"
mlflow.log_image(image_buffer, artifact_file=artifact_file_name)

# End the MLflow run
if mlflow.active_run():
    mlflow.end_run()

dist.destroy_process_group()
```
also:
```
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

Please let me know if further information is needed.
### Versions

I had to use special setup. Check above.

**Comment by monajalal** [comment]
It's extremely strange. Rerunning the code with no changes at all, resulted in no error. What do you think causes this?

![Screenshot from 2023-05-19 11-35-59](https://github.com/pytorch/pytorch/assets/1892917/3e806a8d-5a5c-40b5-9c28-b3782a3f2307)

**Comment by jbschlosser** [comment]
Sounds like an ephemeral connection issue with your environment. Closing for now as outside the scope of PyTorch proper issues, but please free to reopen if you identify information that leads you to believe otherwise.
