### ISSUE TITLE
Moco failure `TypeError: can't assign a SymInt to a torch.cuda.LongTensor`

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#101939]
### 🐛 Describe the bug

#101201 gets dynamic shapes accuracy passing, but perf fails with

```
2023-05-18T17:50:07.2455328Z cuda train moco                               
2023-05-18T17:50:07.8390605Z [2023-05-18 17:50:07,838] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
2023-05-18T18:08:52.6737825Z [2023-05-18 18:08:52,670] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (64)
2023-05-18T18:08:52.6739284Z    function: '<resume in _momentum_update_key_encoder>' (/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py:50)
2023-05-18T18:08:52.6741525Z to diagnose recompilation issues, set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.
2023-05-18T18:08:55.3922181Z [2023-05-18 18:08:55,391] torch._inductor.utils: [WARNING] DeviceCopy in input program
2023-05-18T18:09:36.3230570Z [2023-05-18 18:09:36,320] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 128*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:09:36.3232830Z [2023-05-18 18:09:36,322] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:09:41.2112859Z [2023-05-18 18:09:41,209] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 100352*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:09:41.2152362Z [2023-05-18 18:09:41,214] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 2048*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:09:41.2612828Z [2023-05-18 18:09:41,260] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 25088*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:09:53.2640328Z [2023-05-18 18:09:53,262] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 200704*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:09:53.3020118Z [2023-05-18 18:09:53,301] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 50176*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:10:03.1418081Z [2023-05-18 18:10:03,140] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 401408*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:10:03.5245757Z [2023-05-18 18:10:03,523] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 802816*s0 < 2147483648 == True, this could result in accuracy problems
2023-05-18T18:10:15.4633589Z ERROR:common:Backend dynamo failed in warmup()
2023-05-18T18:10:15.4634304Z Traceback (most recent call last):
2023-05-18T18:10:15.4634665Z   File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 1550, in warmup
2023-05-18T18:10:15.4637980Z     fn(model, example_inputs)
2023-05-18T18:10:15.4640652Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 286, in _fn
2023-05-18T18:10:15.4641258Z     return fn(*args, **kwargs)
2023-05-18T18:10:15.4641885Z   File "/var/lib/jenkins/workspace/benchmarks/dynamo/torchbench.py", line 411, in forward_and_backward_pass
2023-05-18T18:10:15.4642492Z     cloned_inputs = clone_inputs(inputs)
2023-05-18T18:10:15.4643165Z   File "/var/lib/jenkins/workspace/benchmarks/dynamo/torchbench.py", line 412, in <resume in forward_and_backward_pass>
2023-05-18T18:10:15.4643752Z     self.optimizer_zero_grad(mod)
2023-05-18T18:10:15.4644450Z   File "/var/lib/jenkins/workspace/benchmarks/dynamo/torchbench.py", line 414, in <resume in forward_and_backward_pass>
2023-05-18T18:10:15.4645098Z     pred = mod(*cloned_inputs)
2023-05-18T18:10:15.4646029Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
2023-05-18T18:10:15.4646675Z     return self._call_impl(*args, **kwargs)
2023-05-18T18:10:15.4647645Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
2023-05-18T18:10:15.4648132Z     return forward_call(*args, **kwargs)
2023-05-18T18:10:15.4648698Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1537, in forward
2023-05-18T18:10:15.4649071Z     else self._run_ddp_forward(*inputs, **kwargs)
2023-05-18T18:10:15.4649607Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1374, in _run_ddp_forward
2023-05-18T18:10:15.4650029Z     return self.module(*inputs, **kwargs)  # type: ignore[index]
2023-05-18T18:10:15.4651192Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
2023-05-18T18:10:15.4651571Z     return self._call_impl(*args, **kwargs)
2023-05-18T18:10:15.4652084Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
2023-05-18T18:10:15.4652436Z     return forward_call(*args, **kwargs)
2023-05-18T18:10:15.4652794Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 130, in forward
2023-05-18T18:10:15.4653195Z     self._momentum_update_key_encoder()  # update the key encoder
2023-05-18T18:10:15.4653617Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 133, in <resume in forward>
2023-05-18T18:10:15.4654221Z     im_k, idx_unshuffle = self._batch_shuffle_ddp(im_k)
2023-05-18T18:10:15.4654616Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 139, in <resume in forward>
2023-05-18T18:10:15.4655065Z     k = self._batch_unshuffle_ddp(k, idx_unshuffle)
2023-05-18T18:10:15.4655466Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 158, in <resume in forward>
2023-05-18T18:10:15.4655805Z     self._dequeue_and_enqueue(k)
2023-05-18T18:10:15.4656322Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-05-18T18:10:15.4656672Z     return func(*args, **kwargs)
2023-05-18T18:10:15.4657047Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 55, in _dequeue_and_enqueue
2023-05-18T18:10:15.4657397Z     keys = concat_all_gather(keys)
2023-05-18T18:10:15.4657792Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 59, in <resume in _dequeue_and_enqueue>
2023-05-18T18:10:15.4658170Z     ptr = int(self.queue_ptr)
2023-05-18T18:10:15.4658653Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 436, in catch_errors
2023-05-18T18:10:15.4659062Z     return hijacked_callback(frame, cache_size, hooks, frame_state)
2023-05-18T18:10:15.4659607Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 522, in _convert_frame
2023-05-18T18:10:15.4660009Z     result = inner_convert(frame, cache_size, hooks, frame_state)
2023-05-18T18:10:15.4678615Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 125, in _fn
2023-05-18T18:10:15.4679143Z     return fn(*args, **kwargs)
2023-05-18T18:10:15.4679808Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 358, in _convert_frame_assert
2023-05-18T18:10:15.4680201Z     return _compile(
2023-05-18T18:10:15.4680671Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 177, in time_wrapper
2023-05-18T18:10:15.4680984Z     r = func(*args, **kwargs)
2023-05-18T18:10:15.4681468Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 428, in _compile
2023-05-18T18:10:15.4681850Z     out_code = transform_code_object(code, transform)
2023-05-18T18:10:15.4682413Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
2023-05-18T18:10:15.4682829Z     transformations(instructions, code_options)
2023-05-18T18:10:15.4683350Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 413, in transform
2023-05-18T18:10:15.4683679Z     tracer.run()
2023-05-18T18:10:15.4684141Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2009, in run
2023-05-18T18:10:15.4684468Z     super().run()
2023-05-18T18:10:15.4684938Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 703, in run
2023-05-18T18:10:15.4685298Z     and self.step()
2023-05-18T18:10:15.4686052Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 663, in step
2023-05-18T18:10:15.4686415Z     getattr(self, inst.opname)(inst)
2023-05-18T18:10:15.4686926Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2097, in RETURN_VALUE
2023-05-18T18:10:15.4687289Z     self.output.compile_subgraph(
2023-05-18T18:10:15.4687801Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 752, in compile_subgraph
2023-05-18T18:10:15.4688220Z     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
2023-05-18T18:10:15.4688724Z   File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
2023-05-18T18:10:15.4689059Z     return func(*args, **kwds)
2023-05-18T18:10:15.4689585Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 829, in compile_and_call_fx_graph
2023-05-18T18:10:15.4689974Z     compiled_fn = self.call_user_compiler(gm)
2023-05-18T18:10:15.4690499Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 177, in time_wrapper
2023-05-18T18:10:15.4690829Z     r = func(*args, **kwargs)
2023-05-18T18:10:15.4691328Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 888, in call_user_compiler
2023-05-18T18:10:15.4691741Z     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
2023-05-18T18:10:15.4692314Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 884, in call_user_compiler
2023-05-18T18:10:15.4692720Z     compiled_fn = compiler_fn(gm, self.example_inputs())
2023-05-18T18:10:15.4693250Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/backends/distributed.py", line 206, in compile_fn
2023-05-18T18:10:15.4693644Z     return self.backend_compile_fn(gm, example_inputs)
2023-05-18T18:10:15.4694196Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
2023-05-18T18:10:15.4694576Z     compiled_gm = compiler_fn(gm, example_inputs)
2023-05-18T18:10:15.4695111Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/backends/inductor.py", line 9, in inductor
2023-05-18T18:10:15.4695469Z     return compile_fx(*args, **kwargs)
2023-05-18T18:10:15.4695970Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 720, in compile_fx
2023-05-18T18:10:15.4696290Z     return aot_autograd(
2023-05-18T18:10:15.4696781Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
2023-05-18T18:10:15.4697184Z     cg = aot_module_simplified(gm, example_inputs, **kwargs)
2023-05-18T18:10:15.4697745Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3686, in aot_module_simplified
2023-05-18T18:10:15.4698133Z     compiled_fn = create_aot_dispatcher_function(
2023-05-18T18:10:15.4698637Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 177, in time_wrapper
2023-05-18T18:10:15.4698971Z     r = func(*args, **kwargs)
2023-05-18T18:10:15.4699491Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3176, in create_aot_dispatcher_function
2023-05-18T18:10:15.4699909Z     fw_metadata = run_functionalized_fw_and_collect_metadata(
2023-05-18T18:10:15.4700452Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 722, in inner
2023-05-18T18:10:15.4700798Z     flat_f_outs = f(*flat_f_args)
2023-05-18T18:10:15.4701290Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3295, in functional_call
2023-05-18T18:10:15.4701691Z     out = Interpreter(mod).run(*args[params_len:], **kwargs)
2023-05-18T18:10:15.4702309Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/interpreter.py", line 138, in run
2023-05-18T18:10:15.4702661Z     self.env[node] = self.run_node(node)
2023-05-18T18:10:15.4703130Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/interpreter.py", line 195, in run_node
2023-05-18T18:10:15.4703492Z     return getattr(self, n.op)(n.target, args, kwargs)
2023-05-18T18:10:15.4703998Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/interpreter.py", line 267, in call_function
2023-05-18T18:10:15.4704329Z     return target(*args, **kwargs)
2023-05-18T18:10:15.4704831Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/overrides.py", line 22, in __torch_function__
2023-05-18T18:10:15.4705400Z     return replace_fn(func, is_cpu_device(args))(*args, **kwargs)
2023-05-18T18:10:15.4705857Z torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
2023-05-18T18:10:15.4706293Z TypeError: can't assign a SymInt to a torch.cuda.LongTensor
2023-05-18T18:10:15.4706495Z 
2023-05-18T18:10:15.4706740Z While executing %setitem_1 : [#users=0] = call_function[target=operator.setitem](args = (%l__self___queue_ptr, 0, %mod), kwargs = {})
2023-05-18T18:10:15.4707092Z Original traceback:
2023-05-18T18:10:15.4707460Z   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/moco/moco/builder.py", line 66, in <resume in _dequeue_and_enqueue>
2023-05-18T18:10:15.4707825Z     self.queue_ptr[0] = ptr
2023-05-18T18:10:15.4707969Z 
2023-05-18T18:10:15.4707975Z 
2023-05-18T18:10:15.4707981Z 
2023-05-18T18:10:15.4708144Z You can suppress this exception and fall back to eager by setting:
2023-05-18T18:10:15.4708437Z     import torch._dynamo
2023-05-18T18:10:15.4708701Z     torch._dynamo.config.suppress_errors = True
2023-05-18T18:10:15.4708880Z 
```

e.g., as seen in https://ossci-raw-job-status.s3.amazonaws.com/log/13573848761

Note that there are other failures in moco, see https://github.com/pytorch/pytorch/issues/98561

### Versions

master

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by ezyang** [comment]
cc @anijain2305 @eellison

**Comment by jansel** [comment]
I investigated this a bit.

```
./benchmarks/dynamo/torchbench.py --training --performance --no-skip --inductor --only moco
```
fails with:
```python
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
TypeError: can't assign a SymInt to a torch.cuda.LongTensor

While executing %setitem_1 : [num_users=0] = call_function[target=operator.setitem](args = (%l__self___queue_ptr, 0, %mod), kwargs = {})
Original traceback:
  File "/data/users/jansel/torchbenchmark/torchbenchmark/models/moco/moco/builder.py", line 66, in <resume in _dequeue_and_enqueue>
    self.queue_ptr[0] = ptr
```

The offending function is:
```python
@torch.no_grad()
def _dequeue_and_enqueue(self, keys):
    # gather keys before updating queue
    keys = concat_all_gather(keys)

    batch_size = keys.shape[0]

    ptr = int(self.queue_ptr)
    assert self.K % batch_size == 0  # for simplicity

    # replace the keys at ptr (dequeue and enqueue)
    self.queue[:, ptr:ptr + batch_size] = keys.T
    ptr = (ptr + batch_size) % self.K  # move pointer

    self.queue_ptr[0] = ptr
```

With a minimal repro of roughly:
```python
    ptr = int(self.queue_ptr)
    ptr = (ptr + batch_size) % self.K  # move pointer
    self.queue_ptr[0] = ptr
```

You can fix this error by changing the model:
```diff
diff --git a/torchbenchmark/models/moco/moco/builder.py b/torchbenchmark/models/moco/moco/builder.py
index 295e22a7..5460d195 100644
--- a/torchbenchmark/models/moco/moco/builder.py
+++ b/torchbenchmark/models/moco/moco/builder.py
@@ -61,7 +61,7 @@ class MoCo(nn.Module):
 
         # replace the keys at ptr (dequeue and enqueue)
         self.queue[:, ptr:ptr + batch_size] = keys.T
-        ptr = (ptr + batch_size) % self.K  # move pointer
+        ptr = (self.queue_ptr[0] + batch_size) % self.K  # move pointer
 
         self.queue_ptr[0] = ptr
 
```
So if the model did the pointer update with pytorch ops rather than python `int()` ops things would work.  Though this is just working around the issue not fixing it for real.


If I add `--dynamic` as a flag, it instead fails with:
```python
  File "/tmp/torchinductor_jansel/dd/cdd3xq74ulaveo5x7yion4c5db2hdp4ri3ivhi5typqx3gud4fge.py", line 599, in call
    assert_size_stride(primals_103, (s0, 512, 1 + (((-1) + s2) // 8), 1 + (((-1) + s2) // 8)), (512 + (512*((((-1) + s2) // 8)*(((-1) + s2) // 8))) + (1024*(((-1) + s2) // 8)), 1 + ((((-1) + s2) // 8)*(((-1) + s2) // 8)) + (2*(((-1) + s2) // 8)), 1 + (((-1) + s2) // 8), 1))
NameError: name 's2' is not define
```
which seems unrelated.

----

This seems fixable.  Possible ideas:
1) Fixing the current SymInt based handling to make this assignment work
2) Converting these ops into PyTorch ops to mimic my hand fix
3) Better graph breaking and fallbacks on this pointer update frame (I doubt inductor is helping much with this 1-element tensor)
