### ISSUE TITLE
[Inductor] convit_base accuracy failed on 2023-05-21 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#102065]
### 🐛 Describe the bug

Timm model **convit_base** accuracy failure tracked in https://github.com/pytorch/pytorch/issues/93531#issuecomment-1558372237

Error message:

```
loading model: 0it [00:02, ?it/s]cpu  eval  convit_base                         
WARNING:common:fp64 golden ref were not generated for convit_base. Setting accuracy check to cosine
[2023-05-22 11:37:39,433] torch._inductor.scheduler: [CRITICAL] Error in codegen for ComputedBuffer(name='buf21', layout=FixedLayout('cpu', torch.float32, size=[1, 196, 196, 3], stride=[115248, 588, 3, 1]), data=Pointwise(
  'cpu',
  torch.float32,
  def inner_fn(index):
      _, i1, i2, i3 = index
      tmp0 = ops.index_expr(i3, torch.int32)
      tmp1 = ops.index_expr(0, torch.int32)
      tmp2 = tmp0 == tmp1
      tmp3 = ops.index_expr(ModularIndexing(i2, 1, 14), dtype=torch.int64)
      tmp4 = ops.index_expr(ModularIndexing(i1, 1, 14), dtype=torch.int64)
      tmp5 = tmp3 - tmp4
      tmp6 = ops.to_dtype(tmp5, torch.float32)
      tmp7 = ops.index_expr(i3, torch.int32)
      tmp8 = ops.index_expr(1, torch.int32)
      tmp9 = tmp7 == tmp8
      tmp10 = ops.load(buf20, i2)
      tmp11 = ops.load(buf16, i1)
      tmp12 = ops.index_expr((tmp10), dtype=torch.int64)
      tmp13 = ops.index_expr((tmp11), dtype=torch.int64)
      tmp14 = tmp12 - tmp13
      tmp15 = ops.to_dtype(tmp14, torch.float32)
      tmp16 = ops.index_expr(i3, torch.int32)
      tmp17 = ops.index_expr(2, torch.int32)
      tmp18 = tmp16 == tmp17
      tmp19 = ops.index_expr(ModularIndexing(i2, 1, 14), dtype=torch.int64)
      tmp20 = ops.index_expr(ModularIndexing(i1, 1, 14), dtype=torch.int64)
      tmp21 = tmp19 - tmp20
      tmp22 = tmp21 * tmp21
      tmp23 = ops.load(buf20, i2)
      tmp24 = ops.load(buf16, i1)
      tmp25 = ops.index_expr((tmp23), dtype=torch.int64)
      tmp26 = ops.index_expr((tmp24), dtype=torch.int64)
      tmp27 = tmp25 - tmp26
      tmp28 = tmp27 * tmp27
      tmp29 = tmp22 + tmp28
      tmp30 = ops.to_dtype(tmp29, torch.float32)
      tmp31 = ops.constant(0, torch.float32)
      tmp32 = ops.where(tmp18, tmp30, tmp31)
      tmp33 = ops.where(tmp9, tmp15, tmp32)
      tmp34 = ops.where(tmp2, tmp6, tmp33)
      return tmp34
  ,
  ranges=[1, 196, 196, 3],
  origin_node=slice_scatter_8,
  origins={slice_30, select_scatter, slice_scatter_8, slice_sca...
))
ERROR:common:backend='inductor' raised:
TypeError: The computation had not completed because of the undecidable set membership is found in every candidates.


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1488, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 287, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1331, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 440, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 527, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2019, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 703, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 663, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2107, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 752, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 829, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 888, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 884, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/__init__.py", line 1542, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 720, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3700, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3226, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2090, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2270, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1532, in aot_dispatch_base
    compiled_fw = compiler(fw_module, adjusted_flat_args)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 676, in fw_compiler_base
    return inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 45, in newFunction
    return old_func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 280, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 709, in compile_to_fn
    return self.compile_to_module().call
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 683, in compile_to_module
    code, linemap = self.codegen()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 634, in codegen
    self.scheduler.codegen()
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 1238, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/workspace/pytorch/torch/_inductor/codegen/cpp.py", line 2460, in codegen_nodes
    cpp_kernel_proxy.codegen_nodes(nodes)
  File "/workspace/pytorch/torch/_inductor/codegen/cpp.py", line 2381, in codegen_nodes
    tiling_factors, tiling_indices = select_tiling()
  File "/workspace/pytorch/torch/_inductor/codegen/cpp.py", line 2368, in select_tiling
    run(vec_checker)
  File "/workspace/pytorch/torch/_inductor/codegen/cpp.py", line 2297, in run
    node.run(vars, reduction_vars)
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 415, in run
    self.codegen(index_vars)
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 437, in codegen
    self._body(*index_vars)
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4159, in __call__
    result = self.root_block()
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4268, in __call__
    return InterpreterShim(graph, submodules).run(V.get_ops_handler())
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4076, in run
    return super().run(*args, **kwargs)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4072, in run_node
    return super().run_node(n)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 289, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/workspace/pytorch/torch/_inductor/sizevars.py", line 564, in index_expr
    return self._inner.index_expr(self._simplify(index), dtype)
  File "/workspace/pytorch/torch/_inductor/codegen/cpp.py", line 1987, in index_expr
    max_expr = sympy.maximum(
  File "/opt/conda/lib/python3.8/site-packages/sympy-1.12-py3.8.egg/sympy/calculus/util.py", line 792, in maximum
    return function_range(f, symbol, domain).sup
  File "/opt/conda/lib/python3.8/site-packages/sympy-1.12-py3.8.egg/sympy/calculus/util.py", line 208, in function_range
    for critical_point in critical_points:
  File "/opt/conda/lib/python3.8/site-packages/sympy-1.12-py3.8.egg/sympy/sets/sets.py", line 1561, in __iter__
    raise TypeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
TypeError: The computation had not completed because of the undecidable set membership is found in every candidates.


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

TorchDynamo optimized model failed to run because of following error
fail_to_run



```

### Versions

```bash

python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/timm_models.py --accuracy --inference --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only convit_base  --cold_start_latency

```

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
@ESI-SYD, could you help break down which commit introduce this regression?
