### ISSUE TITLE
Test failures in dynamo/test_dynamic_shapes test_cuda_amp_autocast

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#102025]
### 🐛 Describe the bug

If I run `python test/run_test.py -i dynamo/test_dynamic_shapes -- -v -k cuda_amp`, the tests passed.
If I run `python test/run_test.py -i dynamo/test_dynamic_shapes -- -v -k cuda`, the tests failed.

Could there be any caching issue? 

_In case it's related, we have `PYTORCH_TEST_RUN_EVERYTHING_IN_SERIAL=1` and `PYTORCH_TEST_DO_NOT_USE_PYTEST=1` set._

```python
root@2a8fad187fdd:/opt/pytorch/pytorch# python test/run_test.py -i dynamo/test_dynamic_shapes -- -v -k cuda_amp
Ignoring disabled issues:  []
/opt/pytorch/pytorch/test/run_test.py:1331: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if torch.version.cuda is not None and LooseVersion(torch.version.cuda) >= "11.6":
::warning:: Gathered no stats from artifacts. Proceeding with default sharding plan.
No tests in group `Prioritized tests`
TEST GROUP: General tests
parallel (file granularity) tests :

serial (file granularity) tests:
 dynamo/test_dynamic_shapes 1/1
Ignoring disabled issues:  []
Ignoring disabled issues:  []
Running dynamo/test_dynamic_shapes 1/1 ... [2023-05-22 16:36:54.338634]
Executing ['/usr/local/bin/python', '-bb', 'dynamo/test_dynamic_shapes.py', '-v', '-k', 'cuda_amp'] ... [2023-05-22 16:36:54.339994]

Expand the folded group to see the log file of dynamo/test_dynamic_shapes 1/1
##[group]PRINTING LOG FILE of dynamo/test_dynamic_shapes 1/1 (/opt/pytorch/pytorch/test/test-reports/dynamo-test_dynamic_shapes_ssr_cu3f.log)
test_cuda_amp_autocast (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... ok
test_cuda_amp_autocast_dynamic_shapes (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... ok
test_cuda_amp_autocast (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... ok
test_cuda_amp_autocast_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.339s

OK
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 5), ('unique_graphs', 1)]

##[endgroup]
FINISHED PRINTING LOG FILE of dynamo/test_dynamic_shapes 1/1 (/opt/pytorch/pytorch/test/test-reports/dynamo-test_dynamic_shapes_ssr_cu3f.log)

root@2a8fad187fdd:/opt/pytorch/pytorch# python test/run_test.py -i dynamo/test_dynamic_shapes -- -v -k cuda
Ignoring disabled issues:  []
/opt/pytorch/pytorch/test/run_test.py:1331: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if torch.version.cuda is not None and LooseVersion(torch.version.cuda) >= "11.6":
::warning:: Gathered no stats from artifacts. Proceeding with default sharding plan.
No tests in group `Prioritized tests`
TEST GROUP: General tests
parallel (file granularity) tests :

serial (file granularity) tests:
 dynamo/test_dynamic_shapes 1/1
Ignoring disabled issues:  []
Ignoring disabled issues:  []
Running dynamo/test_dynamic_shapes 1/1 ... [2023-05-22 16:37:30.783354]
Executing ['/usr/local/bin/python', '-bb', 'dynamo/test_dynamic_shapes.py', '-v', '-k', 'cuda'] ... [2023-05-22 16:37:30.784764]

test_cuda_amp_autocast (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... ok
test_cuda_amp_autocast_dynamic_shapes (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... ok
test_cuda_stream_context_manager1 (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... [2023-05-22 16:37:33,978] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_stream_context_manager1_dynamic_shapes (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... [2023-05-22 16:37:33,992] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_stream_context_manager2 (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... [2023-05-22 16:37:34,010] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_stream_context_manager2_dynamic_shapes (torch._dynamo.testing.DynamicShapesCtxManagerTests) ... [2023-05-22 16:37:34,023] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_set_device (torch._dynamo.testing.DynamicShapesMiscTests) ... ok
test_cuda_set_device_dynamic_shapes (torch._dynamo.testing.DynamicShapesMiscTests) ... ok
test_torch_cuda_is_available (torch._dynamo.testing.DynamicShapesMiscTests) ... ok
test_torch_cuda_is_available_dynamic_shapes (torch._dynamo.testing.DynamicShapesMiscTests) ... ok
test_cuda_amp_autocast (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... FAIL
test_cuda_amp_autocast_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... FAIL
test_cuda_stream_context_manager1 (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... [2023-05-22 16:37:34,249] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_stream_context_manager1_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... [2023-05-22 16:37:34,260] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_stream_context_manager2 (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... [2023-05-22 16:37:34,271] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_stream_context_manager2_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests) ... [2023-05-22 16:37:34,282] torch._dynamo.variables.torch: [WARNING] torch.cuda.stream() not fully supported, streams may be ignored
ok
test_cuda_set_device (torch._dynamo.testing.StaticDefaultDynamicShapesMiscTests) ... ok
test_cuda_set_device_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesMiscTests) ... ok
test_torch_cuda_is_available (torch._dynamo.testing.StaticDefaultDynamicShapesMiscTests) ... ok
test_torch_cuda_is_available_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesMiscTests) ... ok

======================================================================
FAIL: test_cuda_amp_autocast (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/dynamo/test_ctx_manager.py", line 272, in test_cuda_amp_autocast
    self.assertEqual(exported.device.index, 0)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3060, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 0 but got 1.
Absolute difference: 1
Relative difference: inf

======================================================================
FAIL: test_cuda_amp_autocast_dynamic_shapes_static_default (torch._dynamo.testing.StaticDefaultDynamicShapesCtxManagerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/_dynamo/testing.py", line 307, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/dynamo/test_ctx_manager.py", line 272, in test_cuda_amp_autocast
    self.assertEqual(exported.device.index, 0)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3060, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 0 but got 1.
Absolute difference: 1
Relative difference: inf

----------------------------------------------------------------------
Ran 20 tests in 0.674s

FAILED (failures=2)
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 9), ('unique_graphs', 1)]
stats [('calls_captured', 9), ('unique_graphs', 1)]
stats [('calls_captured', 8), ('unique_graphs', 1)]
stats [('calls_captured', 8), ('unique_graphs', 1)]
frames [('total', 2), ('ok', 2)]
inline_call [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
unimplemented []
graph_break [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
stats [('calls_captured', 2), ('unique_graphs', 2)]
frames [('total', 2), ('ok', 2)]
inline_call [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
unimplemented []
graph_break [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
stats [('calls_captured', 2), ('unique_graphs', 2)]
stats [('calls_captured', 1), ('unique_graphs', 1)]
stats [('calls_captured', 1), ('unique_graphs', 1)]
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 5), ('unique_graphs', 1)]
stats [('calls_captured', 9), ('unique_graphs', 1)]
stats [('calls_captured', 9), ('unique_graphs', 1)]
stats [('calls_captured', 8), ('unique_graphs', 1)]
stats [('calls_captured', 8), ('unique_graphs', 1)]
frames [('total', 2), ('ok', 2)]
inline_call [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
unimplemented []
graph_break [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
stats [('calls_captured', 2), ('unique_graphs', 2)]
frames [('total', 2), ('ok', 2)]
inline_call [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
unimplemented []
graph_break [('inlining disallowed: <function set_device at 0x7fb1d97908b0>', 1)]
stats [('calls_captured', 2), ('unique_graphs', 2)]
stats [('calls_captured', 1), ('unique_graphs', 1)]
stats [('calls_captured', 1), ('unique_graphs', 1)]
FINISHED PRINTING LOG FILE of dynamo/test_dynamic_shapes 1/1 (/opt/pytorch/pytorch/test/test-reports/dynamo-test_dynamic_shapes_hcfe8f9o.log)

dynamo/test_dynamic_shapes 1/1 failed!
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/run_test.py", line 1615, in <module>
    main()
  File "/opt/pytorch/pytorch/test/run_test.py", line 1591, in main
    failure_messages += run_tests(
  File "/opt/pytorch/pytorch/test/run_test.py", line 1525, in run_tests
    raise RuntimeError(err_message)
RuntimeError: dynamo/test_dynamic_shapes 1/1 failed!
```

### Versions

torch_commit: https://github.com/pytorch/pytorch/commit/e9a7115605ee5b6ae38ea5716a4abea5aa415333

cuda 12.1

cc @ezyang @ptrblck @ngimel

**Comment by ezyang** [comment]
yes, could be caching issue

**Comment by ngimel** [comment]
`test_cuda_set_device` doesn't restore device, this is wrong, cc @yanboliang #101668
