### ISSUE TITLE
Many test_ops empty_strided_cuda test failures

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#102024]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/101782 is likely related

```python
root@9c1e25e21bfa:/opt/pytorch/pytorch# python test/test_ops.py -v -k TestCommonCUDA.test_multiple_devices_empty_strided_cuda_int64
test_multiple_devices_empty_strided_cuda_int64 (__main__.TestCommonCUDA) ... FAIL

======================================================================
FAIL: test_multiple_devices_empty_strided_cuda_int64 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2167, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 904, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1069, in only_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1093, in multi_fn
    return fn(slf, devices, *args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_ops.py", line 148, in test_multiple_devices
    self.assertTrue(result.device == cuda_device)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.090s

FAILED (failures=1)
```

```python
root@2a8fad187fdd:/opt/pytorch/pytorch# python test/test_ops.py -v -k TestCommonCUDA.test_multiple_devices_empty_strided_cuda_float32
test_multiple_devices_empty_strided_cuda_float32 (__main__.TestCommonCUDA) ... FAIL

======================================================================
FAIL: test_multiple_devices_empty_strided_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2167, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 904, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1069, in only_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1093, in multi_fn
    return fn(slf, devices, *args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_ops.py", line 148, in test_multiple_devices
    self.assertTrue(result.device == cuda_device)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.096s

FAILED (failures=1)
```

and below flaky test on H100/A100
```python
==================================== RERUNS ====================================
_______ TestCommonCUDA.test_compare_cpu__refs_empty_strided_cuda_float32 _______
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/test_ops.py", line 287, in test_compare_cpu
    self.assertEqual(cuda_results, cpu_results, atol=1e-3, rtol=1e-3)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3060, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not close!
Expected 2.3694278276172396e-38 but got -227244035276800.0.
Absolute difference: 227244035276800.0 (up to 0.001 allowed)
Relative difference: 9.590671326981195e+51 (up to 0.001 allowed)
_______ TestCommonCUDA.test_compare_cpu__refs_empty_strided_cuda_float32 _______
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/test_ops.py", line 287, in test_compare_cpu
    self.assertEqual(cuda_results, cpu_results, atol=1e-3, rtol=1e-3)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3060, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not close!
Expected 2.3694278276172396e-38 but got -227241887793152.0.
Absolute difference: 227241887793152.0 (up to 0.001 allowed)
Relative difference: 9.59058069397592e+51 (up to 0.001 allowed)
=================================== FAILURES ===================================
_______ TestCommonCUDA.test_compare_cpu__refs_empty_strided_cuda_float32 _______
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/test_ops.py", line 287, in test_compare_cpu
    self.assertEqual(cuda_results, cpu_results, atol=1e-3, rtol=1e-3)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3060, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not close!
Expected 0.0 but got 0.24308514595031738.
Absolute difference: 0.24308514595031738 (up to 0.001 allowed)
Relative difference: inf (up to 0.001 allowed)
```

### Versions

https://github.com/pytorch/pytorch/commit/e9a7115605ee5b6ae38ea5716a4abea5aa415333

cuda 12.1

V100, A100, H100

cc @ezyang @ptrblck @ngimel

**Comment by khushi-411** [comment]
Hi, @ngimel! Those tests weren't caught in my local system and CI, so we missed them. I'll send a new PR adding those skips. Thanks, and sorry about it :)
