### ISSUE TITLE
functorch/test_ops.py TestOperatorsCUDA.test_vjp_nn_functional_scaled_dot_product_attention_cuda_float32 fails with "unexpected success" on H100

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#102029]
### 🐛 Describe the bug

_functorch/test_ops.py_ `TestOperatorsCUDA.test_vjp_nn_functional_scaled_dot_product_attention_cuda_float32` fails with "unexpected success" on H100

```python
root@f0846c538c80:/opt/pytorch/pytorch# python test/functorch/test_ops.py -v -k TestOperatorsCUDA.test_vjp_nn_functional_scaled_dot_product_attention_cuda_float32
test_vjp_nn_functional_scaled_dot_product_attention_cuda_float32 (__main__.TestOperatorsCUDA) ... /opt/pytorch/pytorch/torch/_functorch/deprecated.py:73: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vjp is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.func.vjp instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vjp')
unexpected success

----------------------------------------------------------------------
Ran 1 test in 0.450s

FAILED (unexpected successes=1)
```

test passed on V100 and A100

### Versions

torch_commit: https://github.com/pytorch/pytorch/commit/e9a7115605ee5b6ae38ea5716a4abea5aa415333

fails on H100, passes on A100, V100
cuda 12.1

failure probably started on 5/19/23 nightly

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @zou3519 @Chillee @samdow @kshitij12345 @janeyx99 @ptrblck

**Comment by xwang233** [comment]
Another similar test fails on V100 and (seems like) passes on A100 and H100. It also started to fail since 5/19/23. I guess those failures are related.

```python
root@2a8fad187fdd:/opt/pytorch/pytorch# python test/test_schema_check.py -v -k TestSchemaCheckModeOpInfoCUDA.test_schema_correctness_nn_functional_scaled_dot_product_attention_cuda_bfloat16
test_schema_correctness_nn_functional_scaled_dot_product_attention_cuda_bfloat16 (__main__.TestSchemaCheckModeOpInfoCUDA) ... ERROR

======================================================================
ERROR: test_schema_correctness_nn_functional_scaled_dot_product_attention_cuda_bfloat16 (__main__.TestSchemaCheckModeOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2167, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 427, in instantiated_test
    raise rte
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 904, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_schema_check.py", line 502, in test_schema_correctness
    op(sample.input, *sample.args, **sample.kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/opinfo/core.py", line 1097, in __call__
    return self.op(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_methods_invocations.py", line 13069, in <lambda>
    wrapper_set_seed(torch.nn.functional.scaled_dot_product_attention, *args, **kwargs),
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_methods_invocations.py", line 8731, in wrapper_set_seed
    return op(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/schema_check_mode.py", line 112, in __torch_dispatch__
    out = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 398, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: cutlassF: no kernel found to launch!

----------------------------------------------------------------------
Ran 1 test in 0.657s

FAILED (errors=1)
```

**Comment by drisspg** [comment]
I can take a look

**Comment by Fuzzkatt** [comment]
For the original issue, I tested 5/19 nightly vs 5/18 nightly, it fails as expected in 5/18 but passes unexpectedly in 5/19. So it is one of the commits from 5/18, although none of them jump out to me in particular.

To fix the original issue, I just replaced https://github.com/pytorch/pytorch/blob/main/test/functorch/test_ops.py#L600 with
```
decorate('nn.functional.scaled_dot_product_attention', device_type="cuda", 
    decorator=expectedFailureIf(not (torch.cuda.is_available() and torch.cuda.get_device_capability() >= (9, 0)))),
```  
Basically just don't have an expected failure for sm90. Is that an acceptable solution?

**Comment by drisspg** [comment]
So this should make the tests work on h100: https://github.com/pytorch/pytorch/pull/101847/files#diff-5b0af800ae8069206a9d66d16db8aa2aab2b6451da4c419a034b39367d3d7dafR479

kind of flying bind since I don't have h100 to test.

I think this should be fine: `decorate('nn.functional.scaled_dot_product_attention', device_type="cuda", 
    decorator=expectedFailureIf(not (torch.cuda.is_available() and torch.cuda.get_device_capability() >= (9, 0)))),`

https://github.com/pytorch/pytorch/issues/102029#issuecomment-1558278905 this should fail with bfloat16 and a pr landed recently to make sure that failure is more explicit.
