### ISSUE TITLE
[cuda] Switching CI to CUDA 12.1 failures in linux-bionic-cuda12.1-py3.10-gcc7-sm86 tests

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#102287]
### 🐛 Describe the bug

Following  test failing: [linux-bionic-cuda12.1-py3.10-gcc7-sm86 / test (default, 2, 5, linux.g5.4xlarge.nvidia.gpu)](https://github.com/pytorch/pytorch/actions/runs/5071677184/jobs/9113241257#logs)

On following PR, switching CI from 11.8 to 12.1 CUDA : https://github.com/pytorch/pytorch/pull/102178

```
2023-05-24T22:13:17.9326495Z =================================== FAILURES ===================================
2023-05-24T22:13:17.9326660Z _____________________ TestNN.test_Conv2d_no_bias_cuda_tf32 _____________________
2023-05-24T22:13:17.9326770Z Traceback (most recent call last):
2023-05-24T22:13:17.9326933Z   File "/var/lib/jenkins/workspace/test/test_nn.py", line 7392, in with_tf32_on
2023-05-24T22:13:17.9327020Z     test.test_cuda(self, **kwargs)
2023-05-24T22:13:17.9327329Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_nn.py", line 4339, in test_cuda
2023-05-24T22:13:17.9327512Z     test_case.assertEqual(cpu_d_i, gpu_d_i, atol=self.precision, rtol=0, exact_dtype=False)
2023-05-24T22:13:17.9327809Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3070, in assertEqual
2023-05-24T22:13:17.9327915Z     raise error_metas[0].to_error(
2023-05-24T22:13:17.9328090Z AssertionError: Tensor-likes are not close!
2023-05-24T22:13:17.9328101Z 
2023-05-24T22:13:17.9328209Z Mismatched elements: 36 / 72 (50.0%)
2023-05-24T22:13:17.9328368Z Greatest absolute difference: 0.004107537847437115 at index (0, 2, 0, 0) (up to 0.001 allowed)
2023-05-24T22:13:17.9328509Z Greatest relative difference: 0.006442113260464176 at index (1, 0, 0, 1) (up to 0 allowed)
2023-05-24T22:13:17.9328813Z - generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/test_nn/test_nn-48d7b1a09e0b95f3.xml -
2023-05-24T22:13:17.9329009Z =========================== short test summary info ============================
2023-05-24T22:13:17.9341916Z FAILED [0.0051s] test_nn.py::TestNN::test_Conv2d_no_bias_cuda_tf32 - AssertionError: Tensor-likes are not close!
2023-05-24T22:13:17.9341925Z 
2023-05-24T22:13:17.9342047Z Mismatched elements: 36 / 72 (50.0%)
2023-05-24T22:13:17.9342200Z Greatest absolute difference: 0.004107537847437115 at index (0, 2, 0, 0) (up to 0.001 allowed)
2023-05-24T22:13:17.9342353Z Greatest relative difference: 0.006442113260464176 at index (1, 0, 0, 1) (up to 0 allowed)
2023-05-24T22:13:17.9342513Z = 1 failed, 1986 passed, 470 skipped, 4 xfailed, 2 rerun in 123.96s (0:02:03) ==
2023-05-24T22:13:17.9342625Z Got exit code 1, retrying (retries left=2)
2023-05-24T22:13:17.9342900Z Test results will be stored in test-reports/python-pytest/test_nn/test_nn-448dbb22c0c68cd0.xml
```

Following test are failing:
https://github.com/pytorch/pytorch/actions/runs/5071677184/jobs/9113241570

```
2023-05-24T22:25:47.7072380Z Greatest relative difference: 0.0087127685546875 at index (0, 0, 4, 4, 4) (up to 0.001 allowed)
2023-05-24T22:25:47.7072508Z =================================== FAILURES ===================================
2023-05-24T22:25:47.7072697Z _ TestInductorOpInfoCUDA.test_comprehensive_nn_functional_conv_transpose3d_cuda_float16 _
2023-05-24T22:25:47.7072802Z Traceback (most recent call last):
2023-05-24T22:25:47.7072999Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor_opinfo.py", line 658, in test_comprehensive
2023-05-24T22:25:47.7073076Z     raise e
2023-05-24T22:25:47.7073270Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor_opinfo.py", line 617, in test_comprehensive
2023-05-24T22:25:47.7073363Z     self.check_model_cuda(
2023-05-24T22:25:47.7073520Z   File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
2023-05-24T22:25:47.7073616Z     return func(*args, **kwds)
2023-05-24T22:25:47.7073870Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 409, in check_model_cuda
2023-05-24T22:25:47.7073957Z     check_model(
2023-05-24T22:25:47.7074132Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 314, in check_model
2023-05-24T22:25:47.7074223Z     self.assertEqual(
2023-05-24T22:25:47.7074560Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3070, in assertEqual
2023-05-24T22:25:47.7074663Z     raise error_metas[0].to_error(
2023-05-24T22:25:47.7074840Z AssertionError: Tensor-likes are not close!
2023-05-24T22:25:47.7074847Z 
2023-05-24T22:25:47.7074956Z Mismatched elements: 8 / 648 (1.2%)
2023-05-24T22:25:47.7075196Z Greatest absolute difference: 0.0625 at index (0, 2, 2, 2, 4) (up to 1e-05 allowed)
2023-05-24T22:25:47.7075359Z Greatest relative difference: 0.00390625 at index (0, 2, 2, 4, 3) (up to 0.001 allowed)
2023-05-24T22:25:47.7075814Z - generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/inductor.test_torchinductor_opinfo/inductor.test_torchinductor_opinfo-280295ec7824db3c.xml -
2023-05-24T22:25:47.7075956Z =========================== short test summary info ============================
2023-05-24T22:25:47.7076434Z FAILED [0.0644s] inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCUDA::test_comprehensive_nn_functional_conv_transpose3d_cuda_float16 - AssertionError: Tensor-likes are not close!
```

### Versions

2.1.0 nightly

cc @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra @ptrblck

**Comment by ngimel** [comment]
This looks like a tolerance issue, @Fuzzkatt can you please take a look?

**Comment by ptrblck** [comment]
CC @eqy

**Comment by Fuzzkatt** [comment]
Verified that tolerance issues are indeed happening on 3090. Made following PR to adjust tolerances: https://github.com/pytorch/pytorch/pull/102361.

**Comment by mikaylagawarecki** [comment]
@Fuzzkatt It seems like the first test in the description `test_Conv2d_no_bias_cuda_tf32` wasn't fixed by the above PR,  see https://github.com/pytorch/pytorch/issues/102291 could you verify whether this is also a tolerance issue?

**Comment by Fuzzkatt** [comment]
Hm, I just reran the test a couple of times on the latest nightly build on a 3080 (sm86), and it is passing. Could you verify that the test is still failing on your end?
