### ISSUE TITLE
after add /path_to_libtorch/libtorch/lib to LD_LIBRARY_PATH, I can't import torch_scatter.

### ISSUE THREAD

**Issue by jih189** [pytorch/pytorch#102272]
### 🐛 Describe the bug

To compile and use libtorch, I add libtorch/lib to $LD_LIBRARY_PATH. However, it causes error if I import torch_scatter. The following is the error:
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3.8/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

It looks like there is a conflict.
Once I remove the "/path_to_libtorch/libtorch/lib" from LD_LIBRARY_PATH, the problem will disappear. However, I will not be able to use libtorch anymore.

### Versions

To compile and use libtorch, I add libtorch/lib to $LD_LIBRARY_PATH. However, it causes error if I import torch_scatter. The following is the error:
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3.8/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

It looks like there is a conflict.
Once I remove the "/path_to_libtorch/libtorch/lib" from LD_LIBRARY_PATH, the problem will disappear. However, I will not be able to use libtorch anymore.

**Comment by ezyang** [comment]
One thing to try is build torch_scatter from source with your libtorch build.
