### ISSUE TITLE
Torch 2.0.1 + Python 3.11 + macOS 13.3.1 = `ImportError: dlopen(...) symbol not found in flat namespace '_PyFrame_GetLasti'`

### ISSUE THREAD

**Issue by vict0rsch** [pytorch/pytorch#102267]
### 🐛 Describe the bug

After installing `torch` to Python 3.11 with macOS 13.3.1 I get this error:

```
python -c "import torch"                                                  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/victor/.virtualenvs/gfn-11/lib/python3.11/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/victor/.virtualenvs/gfn-11/lib/python3.11/site-packages/torch/_C.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_PyFrame_GetLasti'
```

```
python --version
Python 3.11.0a6
```

```
pip install torch --force-reinstall --no-cache-dir                          
Collecting torch
  Downloading torch-2.0.1-cp311-none-macosx_10_9_x86_64.whl (143.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 MB 11.6 MB/s eta 0:00:00
Collecting filelock (from torch)
  Downloading filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting typing-extensions (from torch)
  Downloading typing_extensions-4.6.1-py3-none-any.whl (31 kB)
Collecting sympy (from torch)
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 11.6 MB/s eta 0:00:00
Collecting networkx (from torch)
  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 11.7 MB/s eta 0:00:00
Collecting jinja2 (from torch)
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 108.0 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading MarkupSafe-2.1.2-cp311-cp311-macosx_10_9_x86_64.whl (13 kB)
Collecting mpmath>=0.19 (from sympy->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 12.9 MB/s eta 0:00:00
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, jinja2, torch
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.1
    Uninstalling typing_extensions-4.6.1:
      Successfully uninstalled typing_extensions-4.6.1
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: networkx
    Found existing installation: networkx 3.1
    Uninstalling networkx-3.1:
      Successfully uninstalled networkx-3.1
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 2.1.2
    Uninstalling MarkupSafe-2.1.2:
      Successfully uninstalled MarkupSafe-2.1.2
  Attempting uninstall: filelock
    Found existing installation: filelock 3.12.0
    Uninstalling filelock-3.12.0:
      Successfully uninstalled filelock-3.12.0
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.2
    Uninstalling Jinja2-3.1.2:
      Successfully uninstalled Jinja2-3.1.2
Successfully installed MarkupSafe-2.1.2 filelock-3.12.0 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 sympy-1.12 torch-2.0.1 typing-extensions-4.6.1
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.0a6 (main, May 24 2023, 12:29:32) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-13.3.1-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchtyping==0.1.4
[conda] Could not collect

**Comment by Az0s** [comment]
@vict0rsch I've tried to replicate the issue on my machine (macOS 13, M1 Pro, Python 3.11.3, torch 2.0.1) but didn't encounter any ImportError. Without being able to reproduce the error, it's hard to pinpoint the exact cause.

If it turns out to be a compatibility issue with PyTorch, I'd be glad to lend a hand in resolving it though.

**Comment by vict0rsch** [comment]
I don't have an M1, could it be linked? How do I help you help me 😅 ?

**Comment by Az0s** [comment]
Hi @vict0rsch,

I've tried but couldn't reproduce the error, making it hard to identify the cause​. Your specific configuration could be a factor​. At this point, it might be best to wait for others who could reproduce this to chime in. Sorry for not having a clear solution yet.

**Comment by vict0rsch** [comment]
It's all good with `3.11.3`. So I guess its' fine. Thanks @Az0s
