### ISSUE TITLE
DDP multi node multi gpu inconsistent params

### ISSUE THREAD

**Issue by flckv** [pytorch/pytorch#102438]
### 🐛 Describe the bug

I pretrain on a multi node and multi gpu specified with SLURM.  It worked first time, but now it gives me error message : 

RuntimeError: DDP expects same model across all ranks, but **Rank 0** has `237 params`, while **rank 1** has inconsistent `0 params`.

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.204-ql-generic-12.0-19-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1498.421
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4500.08
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.24.3          py311h08b1b3b_1  
[conda] numpy-base                1.24.3          py311hf175353_1  
[conda] pytorch                   2.0.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py311_cu118    pytorch
[conda] torchtriton               2.0.0                     py311    pytorch
[conda] torchvision               0.15.2              py311_cu118    pytorch

**Comment by f2010126** [comment]
Hello, I am facing the same issue. Is there any solution/workaround?

**Comment by kk6398** [comment]
Hi, I am facing the same issue. Is there any solution/workaround?

**Comment by pvtien96** [comment]
Hi, I am facing the same issue. Is there any solution/workaround? My script is modified from torchvision [reference](https://github.com/pytorch/vision/blob/main/references/classification/train.py)
```bash
Creating data loaders
Creating model
Traceback (most recent call last):
  File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
Traceback (most recent call last):
  File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
    main(args)
  File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
    main(args)
  File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
Traceback (most recent call last):
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])  File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>

  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    main(args)
  File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
        _verify_param_shape_across_processes(self.process_group, parameters)_verify_param_shape_across_processes(self.process_group, parameters)

  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: DDP expects same model across all ranks, but Rank 0 has 161 params, while rank 1 has inconsistent 177 params.
RuntimeError:     DDP expects same model across all ranks, but Rank 2 has 177 params, while rank 0 has inconsistent 161 params.return dist._verify_params_across_processes(process_group, tensors, logger)

RuntimeError: DDP expects same model across all ranks, but Rank 1 has 177 params, while rank 0 has inconsistent 161 params.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19346) of binary: /home/van-tien.pham/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/van-tien.pham/anaconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch', 'console_scripts', 'torchrun')())
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-07_18:15:12
  host      : siim-3.lis-lab.fr
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 19347)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-02-07_18:15:12
  host      : siim-3.lis-lab.fr
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 19348)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-07_18:15:12
  host      : siim-3.lis-lab.fr
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 19346)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by pvtien96** [comment]
> Hi, I am facing the same issue. Is there any solution/workaround? My script is modified from torchvision [reference](https://github.com/pytorch/vision/blob/main/references/classification/train.py)
> 
> ```shell
> Creating data loaders
> Creating model
> Traceback (most recent call last):
>   File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> Traceback (most recent call last):
>   File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
>     main(args)
>   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
>     main(args)
>   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> Traceback (most recent call last):
>     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])  File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> 
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
>     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
>     main(args)
>   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
>     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
>         _verify_param_shape_across_processes(self.process_group, parameters)_verify_param_shape_across_processes(self.process_group, parameters)
> 
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
>     _verify_param_shape_across_processes(self.process_group, parameters)
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
>     return dist._verify_params_across_processes(process_group, tensors, logger)
>     return dist._verify_params_across_processes(process_group, tensors, logger)
> RuntimeError: DDP expects same model across all ranks, but Rank 0 has 161 params, while rank 1 has inconsistent 177 params.
> RuntimeError:     DDP expects same model across all ranks, but Rank 2 has 177 params, while rank 0 has inconsistent 161 params.return dist._verify_params_across_processes(process_group, tensors, logger)
> 
> RuntimeError: DDP expects same model across all ranks, but Rank 1 has 177 params, while rank 0 has inconsistent 161 params.
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19346) of binary: /home/van-tien.pham/anaconda3/bin/python
> Traceback (most recent call last):
>   File "/home/van-tien.pham/anaconda3/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch', 'console_scripts', 'torchrun')())
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> train.py FAILED
> ------------------------------------------------------------
> Failures:
> [1]:
>   time      : 2024-02-07_18:15:12
>   host      : siim-3.lis-lab.fr
>   rank      : 1 (local_rank: 1)
>   exitcode  : 1 (pid: 19347)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [2]:
>   time      : 2024-02-07_18:15:12
>   host      : siim-3.lis-lab.fr
>   rank      : 2 (local_rank: 2)
>   exitcode  : 1 (pid: 19348)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-02-07_18:15:12
>   host      : siim-3.lis-lab.fr
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 19346)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ```

I discovered that my argument includes a hyperparameter named 'rank', which was the root cause of the issue. Substituting it with a different name resolved the problem seamlessly.

**Comment by SimWangArizona** [comment]
> > Hi, I am facing the same issue. Is there any solution/workaround? My script is modified from torchvision [reference](https://github.com/pytorch/vision/blob/main/references/classification/train.py)
> > ```shell
> > Creating data loaders
> > Creating model
> > Traceback (most recent call last):
> >   File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> > Traceback (most recent call last):
> >   File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> >     main(args)
> >   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> >     main(args)
> >   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> > Traceback (most recent call last):
> >     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])  File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> > 
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
> >     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
> >     main(args)
> >   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> >     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
> >         _verify_param_shape_across_processes(self.process_group, parameters)_verify_param_shape_across_processes(self.process_group, parameters)
> > 
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
> >     _verify_param_shape_across_processes(self.process_group, parameters)
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
> >     return dist._verify_params_across_processes(process_group, tensors, logger)
> >     return dist._verify_params_across_processes(process_group, tensors, logger)
> > RuntimeError: DDP expects same model across all ranks, but Rank 0 has 161 params, while rank 1 has inconsistent 177 params.
> > RuntimeError:     DDP expects same model across all ranks, but Rank 2 has 177 params, while rank 0 has inconsistent 161 params.return dist._verify_params_across_processes(process_group, tensors, logger)
> > 
> > RuntimeError: DDP expects same model across all ranks, but Rank 1 has 177 params, while rank 0 has inconsistent 161 params.
> > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19346) of binary: /home/van-tien.pham/anaconda3/bin/python
> > Traceback (most recent call last):
> >   File "/home/van-tien.pham/anaconda3/bin/torchrun", line 33, in <module>
> >     sys.exit(load_entry_point('torch', 'console_scripts', 'torchrun')())
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
> >     return f(*args, **kwargs)
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
> >     run(args)
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
> >     elastic_launch(
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
> >     return launch_agent(self._config, self._entrypoint, list(args))
> >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> >     raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > ============================================================
> > train.py FAILED
> > ------------------------------------------------------------
> > Failures:
> > [1]:
> >   time      : 2024-02-07_18:15:12
> >   host      : siim-3.lis-lab.fr
> >   rank      : 1 (local_rank: 1)
> >   exitcode  : 1 (pid: 19347)
> >   error_file: <N/A>
> >   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> > [2]:
> >   time      : 2024-02-07_18:15:12
> >   host      : siim-3.lis-lab.fr
> >   rank      : 2 (local_rank: 2)
> >   exitcode  : 1 (pid: 19348)
> >   error_file: <N/A>
> >   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> > ------------------------------------------------------------
> > Root Cause (first observed failure):
> > [0]:
> >   time      : 2024-02-07_18:15:12
> >   host      : siim-3.lis-lab.fr
> >   rank      : 0 (local_rank: 0)
> >   exitcode  : 1 (pid: 19346)
> >   error_file: <N/A>
> >   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> > ```
> 
> I discovered that my argument includes a hyperparameter named 'rank', which was the root cause of the issue. Substituting it with a different name resolved the problem seamlessly.

Hi! What is the function of this hyperparameter?

**Comment by ari62** [comment]
@pvti argument to what? You said you had an argument named rank.

**Comment by pvti** [comment]
> > > Hi, I am facing the same issue. Is there any solution/workaround? My script is modified from torchvision [reference](https://github.com/pytorch/vision/blob/main/references/classification/train.py)
> > > ```shell
> > > Creating data loaders
> > > Creating model
> > > Traceback (most recent call last):
> > >   File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> > > Traceback (most recent call last):
> > >   File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> > >     main(args)
> > >   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> > >     main(args)
> > >   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> > > Traceback (most recent call last):
> > >     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])  File "/home/van-tien.pham/Imagenet/train.py", line 748, in <module>
> > > 
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
> > >     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
> > >     main(args)
> > >   File "/home/van-tien.pham/Imagenet/train.py", line 380, in main
> > >     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
> > >         _verify_param_shape_across_processes(self.process_group, parameters)_verify_param_shape_across_processes(self.process_group, parameters)
> > > 
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
> > >     _verify_param_shape_across_processes(self.process_group, parameters)
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
> > >     return dist._verify_params_across_processes(process_group, tensors, logger)
> > >     return dist._verify_params_across_processes(process_group, tensors, logger)
> > > RuntimeError: DDP expects same model across all ranks, but Rank 0 has 161 params, while rank 1 has inconsistent 177 params.
> > > RuntimeError:     DDP expects same model across all ranks, but Rank 2 has 177 params, while rank 0 has inconsistent 161 params.return dist._verify_params_across_processes(process_group, tensors, logger)
> > > 
> > > RuntimeError: DDP expects same model across all ranks, but Rank 1 has 177 params, while rank 0 has inconsistent 161 params.
> > > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19346) of binary: /home/van-tien.pham/anaconda3/bin/python
> > > Traceback (most recent call last):
> > >   File "/home/van-tien.pham/anaconda3/bin/torchrun", line 33, in <module>
> > >     sys.exit(load_entry_point('torch', 'console_scripts', 'torchrun')())
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
> > >     return f(*args, **kwargs)
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
> > >     run(args)
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
> > >     elastic_launch(
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
> > >     return launch_agent(self._config, self._entrypoint, list(args))
> > >   File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> > >     raise ChildFailedError(
> > > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > > ============================================================
> > > train.py FAILED
> > > ------------------------------------------------------------
> > > Failures:
> > > [1]:
> > >   time      : 2024-02-07_18:15:12
> > >   host      : siim-3.lis-lab.fr
> > >   rank      : 1 (local_rank: 1)
> > >   exitcode  : 1 (pid: 19347)
> > >   error_file: <N/A>
> > >   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> > > [2]:
> > >   time      : 2024-02-07_18:15:12
> > >   host      : siim-3.lis-lab.fr
> > >   rank      : 2 (local_rank: 2)
> > >   exitcode  : 1 (pid: 19348)
> > >   error_file: <N/A>
> > >   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> > > ------------------------------------------------------------
> > > Root Cause (first observed failure):
> > > [0]:
> > >   time      : 2024-02-07_18:15:12
> > >   host      : siim-3.lis-lab.fr
> > >   rank      : 0 (local_rank: 0)
> > >   exitcode  : 1 (pid: 19346)
> > >   error_file: <N/A>
> > >   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> > > ```
> > 
> > 
> > I discovered that my argument includes a hyperparameter named 'rank', which was the root cause of the issue. Substituting it with a different name resolved the problem seamlessly.
> 
> Hi! What is the function of this hyperparameter?

In my case, the `rank` hyperparameter was used because I was working on a tensor decomposition (where the rank is a common term) project. It turned out that this conflicted with the `rank` in PyTorch's DDP, which was the root of the problem.

**Comment by pvti** [comment]
> @pvti argument to what? You said you had an argument named rank.

Like this:
```
def parse_args():
    parser = argparse.ArgumentParser('arg parser')
    parser.add_argument('--rank', dest='rank', type=int, default=0,
                        help='use pre-specified rank for all layers') #YOUR custom argument, this caused the problem
```

For those who may need, do not use an argument with the name `rank`, this conflicts with the `rank` in PyTorch's DDP, and will cause problems. I remember that I read it [somewhere](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html?utm_source=distr_landing&utm_medium=intermediate_ddp_tutorial#) but now I can't find it.

TL;DR: do not use an argument with the name `rank`.

**Comment by Xnhyacinth** [comment]
the same error, how to solve it?
