### ISSUE TITLE
dynamic shape compile error

### ISSUE THREAD

**Issue by quancs** [pytorch/pytorch#102540]
### 🐛 Describe the bug

I tried to compile a module accepts dynamic time length, but failed.

```python
import torch
from torch import nn
import torch._dynamo.config

torch._dynamo.config.verbose = True


class MyModule(nn.Module):

    def __init__(self,) -> None:
        super().__init__()
        self.self_attn_t = nn.MultiheadAttention(128, num_heads=2, batch_first=True)
        self.self_attn_f = nn.MultiheadAttention(128, num_heads=2, batch_first=True)

    def forward(self, x: torch.Tensor):
        B, F, T, H = x.shape
        x = x.reshape(B * F, T, H)
        x, _ = self.self_attn_t(x, x, x)
        x = x.reshape(B, F, T, H)
        x = x.permute(0, 2, 1, 3)  # [B,T,F,H]
        x = x.reshape(B * T, F, H)
        x, _ = self.self_attn_f(x, x, x)
        x = x.reshape(B, T, F, H)
        x = x.permute(0, 2, 1, 3) # [B,F,T,H]
        return x


B, F, T, H = 2, 129, 100, 128
x = torch.randn((B, F, T, H)).cuda()
m = MyModule().cuda()
m = torch.compile(m, dynamic=True)
y = m(x)
```

the error:
```
Traceback (most recent call last):
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1199, in run_node
    return nnmodule(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 1205, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/nn/functional.py", line 5224, in multi_head_attention_forward
    q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/nn/functional.py", line 4767, in _in_projection_packed
    proj = proj.unflatten(-1, (3, E)).unsqueeze(0).transpose(0, -2).squeeze(-2).contiguous()
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_tensor.py", line 1189, in unflatten
    return super().unflatten(dim, sizes)
TypeError: unflatten(): argument 'sizes' (position 2) must be tuple of ints, but found element of type SymInt at pos 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1152, in get_fake_value
    return wrap_fake_exception(
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1153, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1206, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_module self_self_attn_t(*(FakeTensor(FakeTensor(..., device='meta', size=(s0*s1, s2, 128)), cuda:0), FakeTensor(FakeTensor(..., device='meta', size=(s0*s1, s2, 128)), cuda:0), FakeTensor(FakeTensor(..., device='meta', size=(s0*s1, s2, 128)), cuda:0)), **{}):
unflatten(): argument 'sizes' (position 2) must be tuple of ints, but found element of type SymInt at pos 1
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/quancs/projects/NBSS_pmt/x.py", line 32, in <module>
    y = m(x)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
    return inner_fn(self, inst)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/variables/nn_module.py", line 203, in call_function
    return wrap_fx_proxy(
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 789, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/quancs/miniconda3/envs/torch2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1173, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/home/quancs/projects/NBSS_pmt/x.py", line 18, in forward
    x, _ = self.self_attn_t(x, x, x)


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: CentOS Linux 8 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Clang version: Could not collect
CMake version: version 3.11.4
Libc version: glibc-2.28

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-193.el8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:            6
CPU MHz:             3300.112
CPU max MHz:         3400.0000
CPU min MHz:         800.0000
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31,64-95
NUMA node1 CPU(s):   32-63,96-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==1.1.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torcheval==0.0.6
[pip3] torchmetrics==1.0.0rc0
[pip3] torchtnt==0.0.7
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.5           py39h14f4228_0  
[conda] numpy-base                1.23.5           py39h31eccc5_0  
[conda] pytorch                   2.0.1           py3.9_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-lightning         2.0.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2                py39_cu117    pytorch
[conda] torcheval                 0.0.6                    pypi_0    pypi
[conda] torchmetrics              1.0.0rc0                 pypi_0    pypi
[conda] torchtnt                  0.0.7                    pypi_0    pypi
[conda] torchtriton               2.0.0                      py39    pytorch
[conda] torchvision               0.15.2               py39_cu117    pytorch

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ezyang** [comment]
The script does not fail on 956bd038088bd4e31f1adee99466f5674b51a87c try a nightly.

Reopen if still broken.
