### ISSUE TITLE
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised OSError: file too short 

### ISSUE THREAD

**Issue by franchesoni** [pytorch/pytorch#102539]
### 🐛 Describe the bug

`torch.compile` fails with custom dataset but works with CIFAR10

In the code below, using `CIFAR10` instead of my dataset results in a clean compilation and clear speedup, while using the dataset breaks the compilation raising the error given below. I would expect both compilations to work. Also, both cases work in eager mode. The error trace is obscure, I have no clue about what's happening.

```python
import torch
import torch._dynamo
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
import torchvision
from torchvision.datasets import CIFAR10
from PIL import Image
from pathlib import Path
from torch.utils.data import Dataset
from torchvision.transforms.functional import to_tensor

def norm_img(x):
    return (x - x.min()) / (x.max() - x.min())

class TrainMIT5KDataset(Dataset):
    def __init__(self, datadir):
        self.datadir = Path(datadir)
        image_paths = self.datadir / 'train_processed' / 'raw'
        target_paths = self.datadir / 'train_processed' / 'target'
        self.image_paths = sorted(image_paths.glob('*.jpg'))
        self.target_paths = sorted(target_paths.glob('*.jpg'))
        assert [ipath.name for ipath in self.image_paths] == [tpath.name for tpath in self.target_paths]

    def __getitem__(self, index):
        image_path = self.image_paths[index]
        target_path = self.target_paths[index]
        image = norm_img(to_tensor(Image.open(image_path)))
        target = to_tensor(Image.open(target_path)) 
        return image, target

    def __len__(self):
        return len(self.image_paths)




def fit(enhancer, dataloader, optimizer, scheduler, loss_fn, n_epochs=24, verbose=True, profiler=None):
    logger = SummaryWriter()

    for epoch_idx in range(n_epochs):
        for i, (raw_batch, target_batch) in enumerate(dataloader):
            print('epoch', epoch_idx, 'batch', i)
            out_batch = enhancer(raw_batch)
            target_batch = target_batch.float().reshape(target_batch.shape[0], -1).mean(dim=1, keepdim=True)
            loss = loss_fn(out_batch, target_batch)
            # loss = loss_fn(out_batch, target_batch[...,None].float())
            loss.backward()
            optimizer.step()
            scheduler.step(loss)

            logger.add_scalar("train/loss", loss, epoch_idx * len(dataloader) + i)

            if profiler:
                # save profiler stats
                profiler.disable()
                profiler.dump_stats(f"tests/profiler.prof")
                profiler.enable()
    return enhancer





if __name__ == '__main__':
    import cProfile
    # initialize profiler
    pr = cProfile.Profile()
    pr.enable()

    n_params = 1
    resnet = torchvision.models.resnet18(weights=torchvision.models.ResNet18_Weights.DEFAULT)
    resnet.fc = torch.nn.Linear(512, n_params)
    backbone = resnet
    enhancer = backbone

    torch._dynamo.config.verbose = True
    enhancer = torch.compile(enhancer, mode='reduce-overhead')
    print(enhancer(torch.zeros(1, 3, 448, 448)))

    lr=1e-3
    optimizer = torch.optim.Adam(enhancer.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, "min", factor=0.5, patience=50, verbose=True
    )

    dataset = TrainMIT5KDataset(datadir='dataset/C')
    # dataset = CIFAR10(root='dataset', train=True, download=True, transform=torchvision.transforms.ToTensor())
    dataloader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=4)

    loss_fn = torch.nn.MSELoss()
    enhancer = fit(enhancer, dataloader, optimizer, scheduler, loss_fn, n_epochs=24, verbose=True, profiler=pr)

    pr.disable()
    pr.dump_stats(f"tests/profiler.prof")
```
    
**OUTPUT**
```
tensor([[-0.0646]], grad_fn=<CompiledFunctionBackward>)
epoch 0 batch 0
Traceback (most recent call last):
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 401, in compile_fx
    return compile_fx(
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2805, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2498, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1713, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2133, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/graph.py", line 575, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 528, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_franchesoni/6v/c6vllgwmbm73o4mp5xussxmy3o3mlqd5qb7brz77pk4vvhj2b2py.py", line 4710, in <module>
    async_compile.wait(globals())
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 715, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 692, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 509, in load
    cls.cache[key] = cls._load_library(output_path)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 469, in _load_library
    return cdll.LoadLibrary(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/torchinductor_franchesoni/wg/cwgblozyk66h2rilkm4c4rw6syalfhi7iya2htlr7mt7ldyrukap.so: file too short

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/franchesoni/nsce/compiledebug.py", line 91, in <module>
    enhancer = fit(enhancer, dataloader, optimizer, scheduler, loss_fn, n_epochs=24, verbose=True, profiler=pr)
  File "/home/franchesoni/nsce/compiledebug.py", line 43, in fit
    out_batch = enhancer(raw_batch)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/franchesoni/env_sandbox/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised OSError: /tmp/torchinductor_franchesoni/wg/cwgblozyk66h2rilkm4c4rw6syalfhi7iya2htlr7mt7ldyrukap.so: file too short
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Pop!_OS 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
CPU family:                      6
Model:                           140
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     4200.0000
CPU min MHz:                     400.0000
BogoMIPS:                        2764.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        5 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.9.4
[pip3] pytorch-metric-learning==1.7.3
[pip3] segmentation-models-pytorch==0.3.2
[pip3] torch==2.0.0
[pip3] torchaudio==0.13.1+cpu
[pip3] torchmetrics==0.8.2
[pip3] torchsort==0.1.9
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect
```

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by jansel** [comment]
Possibly this is a corrupted file.  Does it work if you remove `/tmp/torchinductor_franchesoni/wg/cwgblozyk66h2rilkm4c4rw6syalfhi7iya2htlr7mt7ldyrukap.so` -- inductor should regenerate it automatically.

If that fixes it, then we may need to generate tmp.so then rename it to the file location only after it is generated fully.

**Comment by jgong5** [comment]
@franchesoni Does the problem happen randomly or stably?

**Comment by ZailiWang** [comment]
If the suggestion above does not fix the problem, would you provide your dataset so that I'll try to re-produce and root cause it.
If the dataset is too large to share, would you try if a small subset can re-produce the issue, then give the subset data to me.

**Comment by franchesoni** [comment]
I confirm that removing the file did help. After that I couldn't consistently replicate the issue anymore (and now I can't replicate it at all). 

thank you all for your help!
