### ISSUE TITLE
nanogpt_generate with dynamic shapes IMA

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#102616]
### 🐛 Describe the bug

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (956bd038)]$ pp python benchmarks/dynamo/torchbench.py --inductor --dynamic-shapes --inference --amp --devices cuda --accuracy --only nanogpt_generate
loading model: 0it [00:00, ?it/s]number of parameters: 123.69M
loading model: 0it [00:06, ?it/s]
cuda eval  nanogpt_generate
ERROR:common:CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 1481, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 287, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 1324, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 408, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 287, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 3714, in forward
    return compiled_fn(full_args)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 1438, in g
    return f(*args)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 2411, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 1463, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 1556, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py", line 409, in run
    return model(new_inputs)
  File "/tmp/torchinductor_ezyang/m5/cm5vewfai3h55s5ycob2sx2xmkhjl5z6r34ee4mtd332ievqyvfe.py", line 14082, in call
    buf284 = torch.ops.aten.multinomial.default(buf283, 1)
  File "/data/users/ezyang/a/pytorch/torch/_ops.py", line 398, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Versions

main

**Comment by ezyang** [comment]
cc @drisspg

**Comment by ezyang** [comment]
dupe of https://github.com/pytorch/pytorch/issues/102064
