### ISSUE TITLE
[dynamo.export] `AssertionError: whole graph export entails exactly one guard export` for Huggingface T5

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#102788]
### 🐛 Describe the bug

As title, it isn't immediately obvious what caused the break, or if there is any graph break at all. Any suggestions or hints to investigate this issue is greatly appreciated! Repro script below:

```python
import torch
import torch._dynamo
from transformers import AutoTokenizer, T5Model

tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = T5Model.from_pretrained("t5-small")

input_ids = tokenizer(
    "Studies have been shown that owning a dog is good for you", return_tensors="pt"
).input_ids  # Batch size 1
decoder_input_ids = tokenizer("Studies show that", return_tensors="pt").input_ids  # Batch size 1

# preprocess: Prepend decoder_input_ids with start token which is pad token for T5Model.
# This is not needed for torch's T5ForConditionalGeneration as it does this internally using labels arg.
decoder_input_ids = model._shift_right(decoder_input_ids)

# forward pass
outputs = model(input_ids=input_ids, decoder_input_ids=decoder_input_ids)
last_hidden_states = outputs.last_hidden_state

torch._dynamo.export(model, input_ids=input_ids, decoder_input_ids=decoder_input_ids)
```

Error logs:
```
Traceback (most recent call last):
  File "repro_dynamo_mutation_break.py", line 24, in <module>
    torch._dynamo.export(model, input_ids=input_ids, decoder_input_ids=decoder_input_ids)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/eval_frame.py", line 947, in export
    result_traced = opt_f(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/eval_frame.py", line 290, in _fn
    return fn(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bowbao/transformers/src/transformers/models/t5/modeling_t5.py", line 1350, in forward
    @add_start_docstrings_to_model_forward(T5_INPUTS_DOCSTRING)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/eval_frame.py", line 443, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/home/bowbao/pytorch_dev/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/convert_frame.py", line 500, in _compile
    hooks.guard_export_fn(output.guards)
  File "/home/bowbao/pytorch_dev/torch/_dynamo/eval_frame.py", line 896, in guard_export_print
    assert out_guards is None, "whole graph export entails exactly one guard export"
AssertionError: whole graph export entails exactly one guard export


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

From source b02f48b18152ddfcf5fcbefb68f6b66a6c44b37f
transformers                  4.25.1

**Comment by msaroufim** [comment]
Have you tried `torch._dynamo.explain()`? It's pretty great to debug this kind of issue

**Comment by BowenBao** [comment]
Hi @msaroufim , i did! Checking `explanation`, `break_reasons` and `explanation_verbose` from `explain` didn't raise anything alarming. The other three outputs `guards`, `graph` and `ops_per_graph` are pretty verbose, I'm not sure how to go about them. 
```
explanation, _, _, _, break_reason, ex_verbose = torch._dynamo.explain(model, input_ids=input_ids, decoder_input_ids=decoder_input_ids)
print(explanation)
print(break_reason)
print(ex_verbose)
```

```
Dynamo produced 1 graphs with 0 graph break and 307 ops
[]
Dynamo produced 1 graphs with 0 graph break and 307 ops
 Break reasons: 

TorchDynamo compilation metrics:
Function                        Runtimes (s)
------------------------------  ------------------------------
_compile                        2.3904, 0.0046, 0.0020, 0.0023
OutputGraph.call_user_compiler  0.0003
```

**Comment by BowenBao** [comment]
Closing as seems to be resolved. Can no longer repro.
