### ISSUE TITLE
nn.Parameter dispatch error in functionalization

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#102989]
## Issue description

The following code produces a dispatch error in functionalization:

```python
import torch

def fn(x):
    p = torch.nn.Parameter(x)
    return p[0]

if __name__ == '__main__':
    opt_fn = torch.compile(fn, backend="aot_eager")
    opt_fn(torch.rand(3))
```

```
Traceback (most recent call last):
  File "playground5.py", line 9, in <module>
    opt_fn(torch.rand(3))
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 289, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 442, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 527, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2020, in run
    super().run()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 704, in run
    and self.step()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 664, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2108, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 761, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/scratch/williamwen/work/py38-14k-env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 866, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 922, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 918, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/scratch/williamwen/work/pytorch/torch/__init__.py", line 1571, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3684, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3210, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2073, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2253, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1515, in aot_dispatch_base
    fw_module = aot_dispatch_base_graph(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1490, in aot_dispatch_base_graph
    fw_module = create_functionalized_graph(
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1377, in create_functionalized_graph
    fx_g = make_fx(helper, decomposition_table=aot_config.decompositions)(*args)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 788, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_autograd), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 289, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 484, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 289, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/_symbolic_trace.py", line 810, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 501, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1369, in fwd_helper
    return functionalized_f_helper(*args)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1319, in functionalized_f_helper
    f_outs = fn(*f_args)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1118, in inner_fn
    outs = fn(*args)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3293, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/scratch/williamwen/work/pytorch/torch/fx/interpreter.py", line 196, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/interpreter.py", line 268, in call_function
    return target(*args, **kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='aot_eager' raised:
TypeError: Multiple dispatch failed for 'torch._ops.aten.select.int'; all __torch_dispatch__ handlers returned NotImplemented:

  - mode object <torch.fx.experimental.proxy_tensor.ProxyTorchDispatchMode object at 0x7fbc76e33040>
  - tensor subclass <class 'torch._subclasses.fake_tensor.FakeTensor'>

For more information, try re-running with TORCH_LOGS=not_implemented

While executing %getitem : [#users=1] = call_function[target=operator.getitem](args = (%parameter, 0), kwargs = {})
Original traceback:
  File "playground5.py", line 5, in fn
    return p[0]



You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

This bug was revealed by `pytest ./generated/test_shinianzhihou_ChangeDetection.py -k test_027` in https://github.com/pytorch/pytorch/issues/92670.

cc @bdhirsh @ezyang

**Comment by ezyang** [comment]
Quoted code no longer fails on master, assuming fixed.
