### ISSUE TITLE
[onnx] aten::cumprod cannot be exported to ONNX

### ISSUE THREAD

**Issue by davisleelx** [pytorch/pytorch#102948]
### 🐛 Describe the bug

aten::cumprod fails to be exported to ONNX

```
import torch
from torch import nn

class Test(nn.Module):
    def forward(self, x):
        return torch.cumprod(x, dim=-1)

if __name__ == '__main__':

    model = Test()
    torch.onnx.export(model, torch.randn(1, 1, 1024, 65), "cumprod.onnx")
```

error message:
```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::cumprod' to ONNX opset version 14 is not supported.
```

### Versions

PyTorch version:  2.0.1+cu117
python : 3.9

**Comment by rahulhuddar** [comment]
I downgraded the pytorch version to 1.13.1 and it worked for me.

**Comment by shubhambhokare1** [comment]
Hi @davisleelx 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team

**Comment by XiaobingSuper** [comment]
@rahulhuddar I also meet this issue even use 1.13.1:
```
Traceback (most recent call last):
  File "/lpai/test.py", line 16, in <module>
    torch.onnx.export(model, torch.randn(1, 1, 1024, 65), "cumprod.onnx")
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1909, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::cumprod' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
```
the torch installed by 
```
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
```
```
python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.13.1+cu117'
```

**Comment by XiaobingSuper** [comment]
From onnx operators set, I can't find the ```cumprod``` operator, see https://github.com/onnx/onnx/blob/main/docs/Operators.md.

**Comment by jikcou** [comment]
cumsum is supported in onnx, so replace cumprod with exp(cumsum(log)).
`torch.exp(torch.cumsum(torch.log(x), dim=dim))`

**Comment by justinchuby** [comment]
https://onnx.ai/onnx/operators/onnx__CumProd.html has been added
