### ISSUE TITLE
[CI] Failure in linux-bionic-cuda12.1-py3.10-gcc9 / test (deploy, 1, 1, linux.4xlarge.nvidia.gpu) when migrating from gcc7 to gcc9

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#103087]
### 🐛 Describe the bug

When migrating above job from gcc7 to gcc9 I observe following error:

CI Run: https://github.com/pytorch/pytorch/actions/runs/5188383948/jobs/9352876946
Pull: https://github.com/pytorch/pytorch/pull/103075

```
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.SimpleModel (2183 ms)
[ RUN      ] TorchpyTest.ResNet
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.ResNet (2198 ms)
[ RUN      ] TorchpyTest.Movable
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:529: Exception Caught inside torch::deploy embedded library: 
Unable to cast Python instance of type <class 'NoneType'> to C++ type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>'" thrown in the test body.
[  FAILED  ] TorchpyTest.Movable (1137 ms)
[ RUN      ] TorchpyTest.MultiSerialSimpleModel
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.MultiSerialSimpleModel (3249 ms)
[ RUN      ] TorchpyTest.ThreadedSimpleModel
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.ThreadedSimpleModel (3288 ms)
[ RUN      ] TorchpyTest.ErrorsReplicatingObj
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.ErrorsReplicatingObj (4362 ms)
[ RUN      ] TorchpyTest.ThrowsSafely
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.ThrowsSafely (3330 ms)
[ RUN      ] TorchpyTest.AcquireMultipleSessionsInTheSamePackage
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.AcquireMultipleSessionsInTheSamePackage (1180 ms)
[ RUN      ] TorchpyTest.AcquireMultipleSessionsInDifferentPackages
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.AcquireMultipleSessionsInDifferentPackages (1177 ms)
[ RUN      ] TorchpyTest.TensorSharingNotAllowed
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
[       OK ] TorchpyTest.TensorSharingNotAllowed (2255 ms)
[ RUN      ] TorchpyTest.TaggingRace
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Traceback (most recent call last):
  File "<string>", line 49, in <module>
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/__init__.py", line 236, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: get_internals: could not successfully initialize the tstate TSS key!
unknown file: Failure
C++ exception with description "r == 0 INTERNAL ASSERT FAILED at "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp":690, please report a bug to PyTorch. 
Exception raised from newInterpreterImpl at /var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:690 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x68 (0x7f7d9292ae48 in /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x80 (0x7f7d928e2f34 in /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::detail::deprecated_AT_ASSERT() + 0 (0x7f7baa8f299f in /tmp/multipy_interpreterhBpPyz)
frame #3: newInterpreterImpl + 0x99 (0x7f7baa8f05f1 in /tmp/multipy_interpreterhBpPyz)
frame #4: torch::deploy::Interpreter::Interpreter(torch::deploy::InterpreterManager*, std::shared_ptr<torch::deploy::Environment>) + 0x335 (0x5591335f2661 in ./multipy/runtime/build/test_deploy)
frame #5: torch::deploy::Interpreter::Interpreter(std::shared_ptr<torch::deploy::Environment>) + 0x48 (0x5591335f41a6 in ./multipy/runtime/build/test_deploy)
frame #6: void __gnu_cxx::new_allocator<torch::deploy::Interpreter>::construct<torch::deploy::Interpreter, std::shared_ptr<torch::deploy::Environment>&>(torch::deploy::Interpreter*, std::shared_ptr<torch::deploy::Environment>&) + 0x69 (0x5591335f78fd in ./multipy/runtime/build/test_deploy)
frame #7: void std::allocator_traits<std::allocator<torch::deploy::Interpreter> >::construct<torch::deploy::Interpreter, std::shared_ptr<torch::deploy::Environment>&>(std::allocator<torch::deploy::Interpreter>&, torch::deploy::Interpreter*, std::shared_ptr<torch::deploy::Environment>&) + 0x36 (0x5591335f6432 in ./multipy/runtime/build/test_deploy)
frame #8: torch::deploy::Interpreter& std::vector<torch::deploy::Interpreter, std::allocator<torch::deploy::Interpreter> >::emplace_back<std::shared_ptr<torch::deploy::Environment>&>(std::shared_ptr<torch::deploy::Environment>&) + 0x4c (0x5591335f51cc in ./multipy/runtime/build/test_deploy)
frame #9: torch::deploy::InterpreterManager::InterpreterManager(unsigned long, std::shared_ptr<torch::deploy::Environment>) + 0x1d5 (0x5591335efe3b in ./multipy/runtime/build/test_deploy)
frame #10: TorchpyTest_TaggingRace_Test::TestBody() + 0x7a (0x559133578c02 in ./multipy/runtime/build/test_deploy)
frame #11: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x65 (0x5591335dec0e in ./multipy/runtime/build/test_deploy)
frame #12: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x5a (0x5591335d77f9 in ./multipy/runtime/build/test_deploy)
frame #13: testing::Test::Run() + 0xee (0x5591335b16dc in ./multipy/runtime/build/test_deploy)
frame #14: testing::TestInfo::Run() + 0x10f (0x5591335b2087 in ./multipy/runtime/build/test_deploy)
frame #15: testing::TestSuite::Run() + 0x12d (0x5591335b2935 in ./multipy/runtime/build/test_deploy)
frame #16: testing::internal::UnitTestImpl::RunAllTests() + 0x42d (0x5591335bf031 in ./multipy/runtime/build/test_deploy)
frame #17: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 0x65 (0x5591335dfbf7 in ./multipy/runtime/build/test_deploy)
frame #18: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 0x5a (0x5591335d89ab in ./multipy/runtime/build/test_deploy)
frame #19: testing::UnitTest::Run() + 0xc9 (0x5591335bd82b in ./multipy/runtime/build/test_deploy)
frame #20: RUN_ALL_TESTS() + 0x11 (0x559133582d7c in ./multipy/runtime/build/test_deploy)
frame #21: main + 0x99 (0x55913357d13f in ./multipy/runtime/build/test_deploy)
frame #22: __libc_start_main + 0xe7 (0x7f7d81b13c87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #23: _start + 0x2a (0x55913357285a in ./multipy/runtime/build/test_deploy)
" thrown in the test body.
[  FAILED  ] TorchpyTest.TaggingRace (15383 ms)
[ RUN      ] TorchpyTest.DisarmHook
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
[       OK ] TorchpyTest.DisarmHook (2489 ms)
[ RUN      ] TorchpyTest.RegisterModule
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
[       OK ] TorchpyTest.RegisterModule (2345 ms)
[ RUN      ] TorchpyTest.TensorSerializationSharing
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:529: Exception Caught inside torch::deploy embedded library: 
Unable to cast Python instance of type <class 'NoneType'> to C++ type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>'" thrown in the test body.
[  FAILED  ] TorchpyTest.TensorSerializationSharing (2390 ms)
[ RUN      ] TorchpyTest.UsesDistributed
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
unknown file: Failure
C++ exception with description "/var/lib/jenkins/multipy/multipy/runtime/interpreter/interpreter_impl.cpp:520: Exception Caught inside torch::deploy embedded library: 
Unable to convert call argument '0' of type 'std::shared_ptr<caffe2::serialize::PyTorchStreamReader>' to Python object" thrown in the test body.
[  FAILED  ] TorchpyTest.UsesDistributed (1263 ms)
[ RUN      ] TorchpyTest.Autograd
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
[       OK ] TorchpyTest.Autograd (2326 ms)
[ RUN      ] TorchpyTest.PrintInstruction
-0.6424  0.8229 -1.0796
 0.4211  1.5488 -1.4571
[ CPUFloatType{2,3} ]
Registering torch::deploy builtin library tensorrt (idx 0) with 0 builtin modules
torch::deploy builtin tensorrt contains 0 modules
Registering torch::deploy builtin library cpython_internal (idx 1) with 0 builtin modules
torch::deploy builtin cpython_internal contains 6 modules
-0.6424  0.8229 -1.0796
 0.4211  1.5488 -1.4571
[ CPUFloatType{2,3} ]
-0.6424  0.8229 -1.0796
 0.4211  1.5488 -1.4571
[ CPUFloatType{2,3} ]
[       OK ] TorchpyTest.PrintInstruction (1323 ms)
[----------] 20 tests from TorchpyTest (61310 ms total)

[----------] 2 tests from MultiPyException
[ RUN      ] MultiPyException.Assert
[       OK ] MultiPyException.Assert (0 ms)
[ RUN      ] MultiPyException.Check
[       OK ] MultiPyException.Check (0 ms)
[----------] 2 tests from MultiPyException (0 ms total)

[----------] Global test environment tear-down
[==========] 22 tests from 2 test suites ran. (61310 ms total)
[  PASSED  ] 10 tests.
[  FAILED  ] 12 tests, listed below:
[  FAILED  ] TorchpyTest.SimpleModel
[  FAILED  ] TorchpyTest.ResNet
[  FAILED  ] TorchpyTest.Movable
[  FAILED  ] TorchpyTest.MultiSerialSimpleModel
[  FAILED  ] TorchpyTest.ThreadedSimpleModel
[  FAILED  ] TorchpyTest.ErrorsReplicatingObj
[  FAILED  ] TorchpyTest.ThrowsSafely
[  FAILED  ] TorchpyTest.AcquireMultipleSessionsInTheSamePackage
[  FAILED  ] TorchpyTest.AcquireMultipleSessionsInDifferentPackages
[  FAILED  ] TorchpyTest.TaggingRace
[  FAILED  ] TorchpyTest.TensorSerializationSharing
[  FAILED  ] TorchpyTest.UsesDistributed

12 FAILED TESTS
Current working directory: /var/lib/jenkins/multipy
```

### Versions

nightly 2.1.0

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by atalman** [comment]
@malfet let me check

**Comment by Aidyn-A** [comment]
There are many `std::optional` in https://github.com/pytorch/pytorch/blob/main/torch/csrc/dynamo/guards.cpp
Were there any changes related to `std::optional` in gcc9 that would cause these failures?

**Comment by malfet** [comment]
Anyway, `multipy` hardcodes C++-7 ABI compatibility here
https://github.com/pytorch/multipy/blob/d60f34ad38c371e441fe7ffdb77a3c3dda5a5d19/multipy/runtime/CMakeLists.txt#L27

Changing it to 13 sovles the problem, but I guess it should query it from torch, rather than hardcode

**Comment by malfet** [comment]
> There are many `std::optional` in https://github.com/pytorch/pytorch/blob/main/torch/csrc/dynamo/guards.cpp Were there any changes related to `std::optional` in gcc9 that would cause these failures?

They are not API facing, so it should be ok, but in general, we should use g++9 or newer of all C++17 builds
