### ISSUE TITLE
FSDP saving with a partial `state_dict` triggers assertion

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#103136]
### 🐛 Describe the bug

I wrote a context manager that allows me to only save specific modules when `module.state_dict`:

```python
with partial_state_only(model):
    sd = model.state_dict()
```

However, this seems to violate an FSDP assumption:

```python
Traceback (most recent call last):
  File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/carmocca/git/lit-stablelm/kk.py", line 63, in work
    sd = model.state_dict()
  File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1835, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 661, in _post_state_dict_hook
    processed_state_dict = _post_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 325, in _full_post_state_dict_hook
    return _common_unshard_post_state_dict_hook(
  File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 209, in _common_unshard_post_state_dict_hook
    assert fqn in state_dict, (
AssertionError: FSDP assumes l2.weight is in the state_dict but the state_dict only has odict_keys(['l1.weight']). prefix=, module_name=l2., param_name=weight rank=0.
```

Repro code:
```python
import contextlib
import os
from functools import partial

import torch.cuda
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from torch.distributed.fsdp import FullyShardedDataParallel
from torch.distributed.fsdp.api import FullOptimStateDictConfig, FullStateDictConfig, StateDictType


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(100, 50, bias=False)
        self.l2 = nn.Linear(50, 1, bias=False)


@contextlib.contextmanager
def partial_state_only(module: nn.Module):
    originals = {}

    def save(name, destination, prefix, keep_vars):
        if "l1" in prefix:
            original_fn = originals[name]
            return original_fn(destination, prefix, keep_vars)

    for name, submodule in module.named_modules():
        originals[name] = submodule._save_to_state_dict
        submodule._save_to_state_dict = partial(save, name)
    yield
    for name, module in module.named_modules():
        module._save_to_state_dict = originals[name]


def work(rank):
    os.environ["MASTER_ADDR"] = "127.0.0.1"
    os.environ["MASTER_PORT"] = "1234"
    dist.init_process_group("nccl", world_size=1, rank=rank)

    torch.cuda.set_device(rank)
    device = torch.device("cuda", rank)

    model = MyModel().to(device)
    model = FullyShardedDataParallel(model)

    state_dict_config = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
    optim_state_dict_config = FullOptimStateDictConfig(offload_to_cpu=True, rank0_only=True)
    state_dict_type_context = FullyShardedDataParallel.state_dict_type(
        module=model,
        state_dict_type=StateDictType.FULL_STATE_DICT,
        state_dict_config=state_dict_config,
        optim_state_dict_config=optim_state_dict_config,
    )

    with partial_state_only(model), state_dict_type_context:
        sd = model.state_dict()
        print(sd)


def run():
    mp.spawn(work, nprocs=1)


if __name__ == "__main__":
    run()

```

I'd appreciate advice on either how to make the context manager work with FSDP or if FSDP could be updated to support this sort of behavior

Thank you!

### Versions

pytorch-triton          2.1.0+7d1a95b046
torch                   2.1.0.dev20230505+cu118

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by carmocca** [comment]
Saving seems to be working normally if I just skip the assertion

```diff
--- a/torch/distributed/fsdp/_state_dict_utils.py
+++ b/torch/distributed/fsdp/_state_dict_utils.py
@@ -215,16 +215,11 @@ def _common_unshard_post_state_dict_hook(
     # avoid processing buffers.
     for fqn, param_name, module_name in _param_name_infos(module, fsdp_state):
         fqn = f"{prefix}{fqn}"
+        if fqn not in state_dict:
+            continue
         if no_fsdp_return:
             state_dict.pop(fqn)
             continue
-        assert fqn in state_dict, (
-            f"FSDP assumes {fqn} is in the state_dict but the state_dict only "
-            f"has {state_dict.keys()}. "
-            f"prefix={prefix}, module_name={module_name}, "
-            f"param_name={param_name} rank={fsdp_state.rank}."
-        )
-
         param_hook(state_dict, prefix, fqn)
 
     if not (
```

**Comment by carmocca** [comment]
cc @fegin. Git blame tells me you added this check in https://github.com/pytorch/pytorch/pull/81253

**Comment by carmocca** [comment]
I resorted to this "hack" because I was using a framework that controls the `state_dict()` call and saves it.

I think this sort of behaviour would be useful. However, I opened the issue in case the suggested removal of the assertion was good enough. Since you say this is not actually supported, I'll close it. Thanks!
