### ISSUE TITLE
all warnings being treated as errors

### ISSUE THREAD

**Issue by ewof** [pytorch/pytorch#103204]
### 🐛 Describe the bug

all warnings being treated as errors even with CFLAGS/CXXFLAGS set to `-Wno-error`
i'm trying to build for rocm 5.5.1 i have 7900xtx i installed rocm with the opencl-amd and opencl-amd-dev packages in the AUR
should note i kept getting errors about librt not being found so i just made an empty .a file so it would stop complaining

### Error logs

[log1.txt](https://github.com/pytorch/pytorch/files/11682025/log1.txt)

### Minified repro

TORCHDYNAMO_REPRO_AFTER="dynamo"
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luis/pytorch/torch/__init__.py", line 29, in <module>
    from .torch_version import __version__ as __version__
  File "/home/luis/pytorch/torch/torch_version.py", line 2, in <module>
    from .version import __version__ as internal_version
ModuleNotFoundError: No module named 'torch.version'
>>>
```

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Artix Linux (x86_64)
GCC version: (GCC) 13.1.1 20230429
Clang version: 15.0.7
CMake version: version 3.26.4
Libc version: glibc-2.37

Python version: 3.11.3 (main, Apr  7 2023, 00:46:44) [GCC 12.2.1 20230201] (64-bit runtime)
Python platform: Linux-6.3.4-artix1-1-x86_64-with-glibc2.37
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 5 3600 6-Core Processor
CPU family:                      23
Model:                           113
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU(s) scaling MHz:              75%
CPU max MHz:                     4208.2031
CPU min MHz:                     2200.0000
BogoMIPS:                        7189.96
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        3 MiB (6 instances)
L3 cache:                        32 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[conda] Could not collect```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ewof** [comment]
i can keep running `python setup.py develop` even after it crashes and keep doing so over and over but eventually i will run into some dangling reference one that looks like `(*it).get()` and it wont let me skip it like all the other ones

**Comment by ewof** [comment]
same results if i use `rocm-hip-sdk roctracer` packages instead of `opencl-amd opencl-amd-dev`

**Comment by ewof** [comment]
sometimes i get a lot of `error: no member named 'runtime_error' in namespace 'std'`

**Comment by ewof** [comment]
nvm fixed by changing build flags
