### ISSUE TITLE
[dynamo] Python 3.11: AttributeError: 'torch._C.dynamo.eval_frame._PyInterpreterFrame' object has no attribute 'f_lineno'

### ISSUE THREAD

**Issue by zhxchen17** [pytorch/pytorch#103210]
### 🐛 Describe the bug

When dynamo throws error from 3.11 in _export(), instead of UserError we ran into another AttributeError instead:
```
2023-06-07T18:32:20.0477130Z 
2023-06-07T18:32:20.0477278Z During handling of the above exception, another exception occurred:
2023-06-07T18:32:20.0477455Z 
2023-06-07T18:32:20.0477551Z Traceback (most recent call last):
2023-06-07T18:32:20.0477842Z   File "/var/lib/jenkins/workspace/test/export/test_db.py", line 77, in test_exportdb_not_supported
2023-06-07T18:32:20.0478153Z     exported_model, _ = torchdynamo.export(
2023-06-07T18:32:20.0478383Z                         ^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0478757Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 949, in export
2023-06-07T18:32:20.0479063Z     result_traced = opt_f(*args, **kwargs)
2023-06-07T18:32:20.0479274Z                     ^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0479664Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
2023-06-07T18:32:20.0479985Z     return self._call_impl(*args, **kwargs)
2023-06-07T18:32:20.0480197Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0480582Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
2023-06-07T18:32:20.0480875Z     return forward_call(*args, **kwargs)
2023-06-07T18:32:20.0481090Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0481466Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 292, in _fn
2023-06-07T18:32:20.0481744Z     return fn(*args, **kwargs)
2023-06-07T18:32:20.0481932Z            ^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0482334Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
2023-06-07T18:32:20.0482656Z     return self._call_impl(*args, **kwargs)
2023-06-07T18:32:20.0482855Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0483242Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
2023-06-07T18:32:20.0483547Z     return forward_call(*args, **kwargs)
2023-06-07T18:32:20.0483739Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0484127Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 445, in catch_errors
2023-06-07T18:32:20.0484460Z     return callback(frame, cache_size, hooks, frame_state)
2023-06-07T18:32:20.0484744Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0485133Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 127, in _fn
2023-06-07T18:32:20.0485424Z     return fn(*args, **kwargs)
2023-06-07T18:32:20.0485613Z            ^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0486006Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
2023-06-07T18:32:20.0486304Z     return _compile(
2023-06-07T18:32:20.0486477Z            ^^^^^^^^^
2023-06-07T18:32:20.0486837Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 180, in time_wrapper
2023-06-07T18:32:20.0487120Z     r = func(*args, **kwargs)
2023-06-07T18:32:20.0487306Z         ^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0487678Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 511, in _compile
2023-06-07T18:32:20.0487987Z     exception_handler(e, code, frame)
2023-06-07T18:32:20.0488414Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 216, in exception_handler
2023-06-07T18:32:20.0488822Z     log.error(format_error_msg(e, code, record_filename, frame))
2023-06-07T18:32:20.0489061Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0489454Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 247, in format_error_msg
2023-06-07T18:32:20.0489816Z     stack_above_dynamo = filter_stack(extract_stack(frame))
2023-06-07T18:32:20.0490074Z                                       ^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0490344Z   File "/opt/conda/envs/py_3.11/lib/python3.11/traceback.py", line 231, in extract_stack
2023-06-07T18:32:20.0490658Z     stack = StackSummary.extract(walk_stack(f), limit=limit)
2023-06-07T18:32:20.0490907Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0491162Z   File "/opt/conda/envs/py_3.11/lib/python3.11/traceback.py", line 393, in extract
2023-06-07T18:32:20.0491449Z     return klass._extract_from_extended_frame_gen(
2023-06-07T18:32:20.0491676Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-07T18:32:20.0491960Z   File "/opt/conda/envs/py_3.11/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
2023-06-07T18:32:20.0492287Z     for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
2023-06-07T18:32:20.0492599Z   File "/opt/conda/envs/py_3.11/lib/python3.11/traceback.py", line 390, in extended_frame_gen
2023-06-07T18:32:20.0492854Z     for f, lineno in frame_gen:
2023-06-07T18:32:20.0493123Z   File "/opt/conda/envs/py_3.11/lib/python3.11/traceback.py", line 334, in walk_stack
2023-06-07T18:32:20.0493375Z     yield f, f.f_lineno
2023-06-07T18:32:20.0493549Z              ^^^^^^^^^^
2023-06-07T18:32:20.0493908Z AttributeError: 'torch._C.dynamo.eval_frame._PyInterpreterFrame' object has no attribute 'f_lineno'
```

This is observed from exportdb CI test: https://ossci-raw-job-status.s3.amazonaws.com/log/14083746115

### Versions

python 3.11 CI

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @aakhundov

**Comment by zhxchen17** [comment]
Assigned myself from pt2 hackday: https://github.com/pytorch/pytorch/issues/101011

**Comment by yanboliang** [comment]
cc our 3.11 expert @williamwen42

**Comment by williamwen42** [comment]
At the dynamo python level in 3.11, we don't actually have access to the internal CPython interpreter frame. Instead, we wrap the internal interpreter frame with a custom-defined CPython object struct and give that to the rest of dynamo. I think you can add `f_lineno` to this struct here: https://github.com/pytorch/pytorch/blob/95fced4483af07767114a7674d9a3e124cdd5eba/torch/csrc/dynamo/eval_frame.c#L63

**Comment by zhxchen17** [comment]
So after running `pytest test/export/test_db.py` locally with py3.11, there is no error reproed. By looking at the stacktrace the error tracks to https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/convert_frame.py#L216

why we are running with suppress_errors=True for CI tests but not for local tests??

**Comment by zhxchen17** [comment]
> At the dynamo-python level in 3.11, we don't actually have access to the internal CPython interpreter frame. Instead, we wrap the internal interpreter frame with a custom-defined CPython object struct and give that to the dynamo-python parts. I think you can add `f_lineno` to this struct here:
> 
> https://github.com/pytorch/pytorch/blob/95fced4483af07767114a7674d9a3e124cdd5eba/torch/csrc/dynamo/eval_frame.c#L63

yeah working on that.
