### ISSUE TITLE
Fallback/Tracing Exclusion for custom ops in `torch.compile`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#103340]
### 🐛 Describe the bug

Prior to #101131, custom operators could be placed in the FX graph and had fallback enabled. This enabled features including Torch-TensorRT's [module acceleration implementation](https://github.com/pytorch/TensorRT/pull/1979/files#diff-2e32e84ebfbf7ee98b1cf422843604d4c070ba26cd74110c05743a221072da93). This feature intercepts `call_module` nodes to `torch.nn.MaxPool1d` and replaces them with `call_function` nodes to `torch.ops.tensorrt.maxpool1d`, which has both a Torch generic implementation (for shape/dtype analyses) and an accelerated TensorRT converter. This feature works with the June 5 nightly, but not with the June 8 nightly.

Without fallback/Tracing Exclusion for custom ops, it is unclear how to specify custom operators which are exempted from tracing/decomposition in both Dynamo and AOT. Specifically, an FX node with `torch.ops.custom_ns.custom_op` was previously **exempted from tracing in both Dynamo and decomposition into `aten` ops in AOT**. Now, it seems there is no way to avoid AOT decomposition while keeping the node in the graph (since `torch._dynamo.allow_in_graph` doesn't apply for AOT).

Would a viable solution be to add the `"tensorrt"` namespace here? Are there any other workarounds for this issue?
https://github.com/pytorch/pytorch/blob/d1f24f73dac00f94d1dccf0650acff68b5890c07/torch/_subclasses/fake_tensor.py#L1391-L1399

### Error logs

**Error 1:**
```python
======================================================================
ERROR: test_pre_aot_lowering_maxpool1d (__main__.TestMaxPool1D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/TensorRT/py/torch_tensorrt/dynamo/backend/test/test_pre_aot_lowering.py", line 29, in test_pre_aot_lowering_maxpool1d
    _, expected_ops_unseen = lower_graph_testing(
  File "~/TensorRT/py/torch_tensorrt/dynamo/backend/test/utils.py", line 159, in lower_graph_testing
    compiled_graph(*inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 292, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 662, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 281, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 271, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 445, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 527, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 2024, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 707, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 667, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 2112, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 760, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 857, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 913, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 909, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 1571, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/backends/common.py", line 95, in wrapper
    return fn(model, inputs, **kwargs)
  File "~/TensorRT/py/torch_tensorrt/dynamo/backend/test/utils.py", line 40, in fx_dynamo_testing_backend
    return aot_module_simplified(
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 3707, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 3183, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 723, in inner
    flat_f_outs = f(*flat_f_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 3316, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 661, in __call__
    return self._op(*args, **kwargs or {})
  File "/usr/local/lib/python3.8/dist-packages/torch/_custom_op/autograd.py", line 42, in inner
    return autograd_fallback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_custom_op/autograd.py", line 55, in kernel
    return custom_op(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_custom_op/impl.py", line 253, in __call__
    result = _C._dispatch_call_boxed(self._ophandle, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_subclasses/fake_tensor.py", line 1161, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_subclasses/fake_tensor.py", line 1409, in dispatch
    raise UnsupportedOperatorException(func)
torch._dynamo.exc.BackendCompilerFailed: backend='functools.partial(<function fx_dynamo_testing_backend at 0x7f45765c6c10>, store_intermediate_graphs=[], min_block_size=1, torch_executed_ops=set())' raised:
UnsupportedOperatorException: tensorrt.maxpool1d.default

While executing %maxpool1d : [#users=1] = call_function[target=torch.ops.tensorrt.maxpool1d](args = (%l_x_,), kwargs = {kernel_size: 2, stride: 2, padding: 0, dilation: 1, ceil_mode: False})
Original traceback:
None
```

The above can be circumvented by replacing the custom op with a regular Python callable, but that callable will then be decomposed into `aten` ops by AOT.

### Minified repro

Output above is the result of running [this test](https://github.com/pytorch/TensorRT/pull/1979/files#diff-207829c9201988167322d91a237d86b549ffbf164925aff448b56bcefe253f20). No error appears when running the same test on the June 5 Torch nightly.

### Versions

```python
Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch_tensorrt==1.5.0.dev0+54843d39
[pip3] torch==2.1.0.dev20230608+cu118
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
You need to `impl_abstract` on your operator. In your case, you can use the same implementation you did for cpu/cuda. That should fix it.

@zou3519 is there a way to do the equivalent of a CompositeExplicitAutograd registration in the new custom_ops API?

**Comment by gs-olive** [comment]
Hi @ezyang and @zou3519 - thank you both for the comments. Adding `impl_abstract` did work! I'm wondering what `CompositeExplicitAutograd` registration is and how it might help in this case?

**Comment by zou3519** [comment]
Closing this issue as expected behavior (https://github.com/pytorch/pytorch/pull/101131 is indeed BC-breaking). But please don't hesitate to ask more questions or open a new issue if you have other problems, @gs-olive.
