### ISSUE TITLE
[dynamo] Lineinfo is wrong for Python-3.11

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#103355]
### 🐛 Describe the bug

Running test_boolean_shape_mismatch and test_bool_indicies_cpu results in spurious failure using Python-3.11:
```
$ PYTORCH_TEST_WITH_DYNAMO=1 python test_indexing.py  -v -k test_boolean_shape -k test_bool_indices_cpu
Fail to import hypothesis in common_utils, tests are not derandomized
test_boolean_shape_mismatch_cpu (__main__.NumpyTestsCPU.test_boolean_shape_mismatch_cpu) ... [2023-06-09 22:57:47,947] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT manual_seed /home/nshulga/miniconda3/envs/tmp-py311/lib/python3.11/site-packages/torch/random.py line 26 
due to: 
Traceback (most recent call last):
  File "/home/nshulga/miniconda3/envs/tmp-py311/lib/python3.11/site-packages/torch/fx/graph_module.py", line 75, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<eval_with_key>.0", line 5
    _lambda_ = torch.cuda.<lambda>()
                          ^
SyntaxError: invalid syntax

[2023-06-09 22:57:48,026] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT <lambda> /home/nshulga/git/pytorch/pytorch/test/test_indexing.py line 1471 
due to: 
Traceback (most recent call last):
  File "/home/nshulga/miniconda3/envs/tmp-py311/lib/python3.11/site-packages/torch/_prims_common/__init__.py", line 1667, in check
    raise exc_type(s())
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., size=(5, 4, 3)), FakeTensor(..., size=(4, 4), dtype=torch.uint8)), **{}):
tensors used as indices must be long, int, byte or bool tensors

from user code:
   File "/home/nshulga/git/pytorch/pytorch/test/test_indexing.py", line 1471, in <lambda>
    self.assertRaisesRegex(IndexError, 'mask', lambda: arr[index])

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


/home/nshulga/git/pytorch/pytorch/test/test_indexing.py:1471: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/IndexingUtils.h:27.)
  self.assertRaisesRegex(IndexError, 'mask', lambda: arr[index])
[2023-06-09 22:57:48,048] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT <lambda> /home/nshulga/git/pytorch/pytorch/test/test_indexing.py line 1472 
due to: 
Traceback (most recent call last):
  File "/home/nshulga/miniconda3/envs/tmp-py311/lib/python3.11/site-packages/torch/_prims_common/__init__.py", line 1667, in check
    raise exc_type(s())
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., size=(5, 4, 3)), (slice(None, None, None), FakeTensor(..., size=(4, 4), dtype=torch.uint8))), **{}):
tensors used as indices must be long, int, byte or bool tensors

from user code:
   File "/home/nshulga/git/pytorch/pytorch/test/test_indexing.py", line 1472, in <lambda>
    self.assertRaisesRegex(IndexError, 'mask', lambda: arr[(slice(None), index)])

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


/home/nshulga/git/pytorch/pytorch/test/test_indexing.py:1472: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/IndexingUtils.h:27.)
  self.assertRaisesRegex(IndexError, 'mask', lambda: arr[(slice(None), index)])
ok
test_bool_indices_cpu (__main__.TestIndexingCPU.test_bool_indices_cpu) ... FAIL

======================================================================
FAIL: test_bool_indices_cpu (__main__.TestIndexingCPU.test_bool_indices_cpu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nshulga/miniconda3/envs/tmp-py311/lib/python3.11/site-packages/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nshulga/git/pytorch/pytorch/test/test_indexing.py", line 696, in test_bool_indices
    self.assertEqual(v[boolIndices].shape, (3, 7, 3))
  File "/home/nshulga/git/pytorch/pytorch/test/test_indexing.py", line 696, in <resume in test_bool_indices>
    self.assertEqual(v[boolIndices].shape, (3, 7, 3))
  File "/home/nshulga/git/pytorch/pytorch/test/test_indexing.py", line 696, in <resume in test_bool_indices>
    self.assertEqual(v[boolIndices].shape, (3, 7, 3))
  File "/home/nshulga/git/pytorch/pytorch/test/test_indexing.py", line 696, in <resume in test_bool_indices>
    self.assertEqual(v[boolIndices].shape, (3, 7, 3))
  [Previous line repeated 1 more time]
  File "/home/nshulga/miniconda3/envs/tmp-py311/lib/python3.11/site-packages/torch/testing/_internal/common_utils.py", line 3096, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5

----------------------------------------------------------------------
Ran 2 tests in 0.333s

FAILED (failures=1)
```
Same works fine with any other version of Python

Discovered while working on https://github.com/pytorch/pytorch/pull/103279

Here is the minimal reproducer:
```python
import os
os.environ['PYTORCH_TEST_WITH_DYNAMO']='1'

import torch
from torch import tensor
from torch.testing._internal.common_utils import TestCase
import torch._dynamo
import unittest
import warnings

class TestFoo(TestCase):
    def test_boolean_shape_mismatch(self, device='cpu'):
        arr = torch.ones((5, 4, 3), device=device)

        index = tensor([True], device=device)
        self.assertRaisesRegex(IndexError, 'mask', lambda: arr[index])

        index = torch.ByteTensor(4, 4).to(device).zero_()
        self.assertRaisesRegex(IndexError, 'mask', lambda: arr[index])

    def test_bool_indices(self, device='cpu'):
        v = torch.randn(5, 7, 3, device=device)
        boolIndices = torch.tensor([True, False, True, True, False], dtype=torch.bool, device=device)
        self.assertEqual(v[boolIndices].shape, (3, 7, 3))
        self.assertEqual(v[boolIndices], torch.stack([v[0], v[2], v[3]]))

        v = torch.tensor([True, False, True], dtype=torch.bool, device=device)
        boolIndices = torch.tensor([True, False, False], dtype=torch.bool, device=device)
        uint8Indices = torch.tensor([1, 0, 0], dtype=torch.uint8, device=device)
        with warnings.catch_warnings(record=True) as w:
            self.assertEqual(v[boolIndices].shape, v[uint8Indices].shape)
            self.assertEqual(v[boolIndices], v[uint8Indices])
            self.assertEqual(v[boolIndices], tensor([True], dtype=torch.bool, device=device))
            print("\n\nw=",[f"{x.filename}:{x.lineno} {x.message}" for x in w],"\n\n")
            self.assertEqual(len(w), 2)

if __name__ == "__main__":
    unittest.defaultTestLoader.sortTestMethodsUsing = lambda *args: -1
    unittest.main()

```

### Versions

nightly

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by malfet** [comment]
Backtrace is wrong, assert that fails is
https://github.com/pytorch/pytorch/blob/2b3d955ffdcc79f8c30d9d457216c618775bbc1c/test/test_indexing.py#L706
and not (as backtrace claims)
https://github.com/pytorch/pytorch/blob/2b3d955ffdcc79f8c30d9d457216c618775bbc1c/test/test_indexing.py#L696

**Comment by malfet** [comment]
Backtrace aside, I think it can be an incorrect test, i.e. optimizing compiler should be free to execute subscript operation only once in the following code and cache its result, isn't it:
```python
import torch
x=torch.ones(3, 3)
assert x[1].shape == [3]
assert x[1].max().item() == 1
```

**Comment by malfet** [comment]
Tentatively grabbing for myself, sounds like a fun little problem.

**Comment by malfet** [comment]
Ok, I've found a problem:
https://github.com/pytorch/pytorch/blob/5f77be8bbef5b7e8f1a02525e93ac43e48884aa7/torch/_dynamo/resume_execution.py#L435
And fix:
```python
diff --git a/torch/_dynamo/resume_execution.py b/torch/_dynamo/resume_execution.py
index 60d28e3a6b2..ee47834b68e 100644
--- a/torch/_dynamo/resume_execution.py
+++ b/torch/_dynamo/resume_execution.py
@@ -432,9 +432,15 @@ class ContinueExecutionCache:
             # because the line number table monotonically increases from co_firstlineno
             # remove starts_line for any instructions before the graph break instruction
             # this will ensure the instructions after the break have the correct line numbers
-            target_ind = int(target.offset / 2)
-            for inst in instructions[0:target_ind]:
-                inst.starts_line = None
+            if sys.version_info < (3, 11):
+                target_ind = int(target.offset / 2)
+                for inst in instructions[0:target_ind]:
+                    inst.starts_line = None
+            else:
+                for inst in instructions:
+                    if inst.offset >= target.offset:
+                        break
+                    inst.starts_line = None
```
Time to figure out the test for it
