### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by Hzzhang-nlp** [pytorch/pytorch#103367]
### 🐛 Describe the bug

![image](https://github.com/pytorch/pytorch/assets/39661319/da0f9a22-de47-4942-8319-d279c6a682a6)

### Versions

RuntimeError: CUDA error: unknown error
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8193) of binary: /home/win10-ubuntu/anaconda3/envs/vicuna-7b/bin/python3.10
Traceback (most recent call last):
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
fastchat/train/train_mem.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-10_20:45:09
  host      : DESKTOP-LA7GLEG.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8193)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
![image](https://github.com/pytorch/pytorch/assets/39661319/ab44828a-414b-4fe6-99ca-28c0f0fa2253)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by mikaylagawarecki** [comment]
Hi @Hzzhang-nlp, could you provide a minimal repro of the script you ran that led to this error please?

**Comment by Hzzhang-nlp** [comment]
Hi，@mikaylagawarecki，I am very glad to hear from you. I got an error when I was fine-tuning the vicuna-7b-hf model. The address of this project is https://github.com/lm-sys/FastChat.[https://github.com/lm-sys/FastChat](url)：
torchrun --nproc_per_node=1 --master_port=20001 fastchat/train/train_mem.py     --model_name_or_path llama-7b-hf      --data_path playground/data/dummy.json     --fp16 True     --output_dir finetune_output     --num_train_epochs 3     --per_device_train_batch_size 1     --per_device_eval_batch_size 1     --gradient_accumulation_steps 16     --evaluation_strategy "no"     --save_strategy "steps"     --save_steps 1200     --save_total_limit 10     --learning_rate 2e-5     --weight_decay 0.     --warmup_ratio 0.03     --lr_scheduler_type "cosine"     --logging_steps 1     --fsdp "full_shard offload auto_wrap"     --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'     --tf32 True     --model_max_length 128    --gradient_checkpointing True     --lazy_preprocess True

**Comment by Hzzhang-nlp** [comment]
The specific error is：
/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py:295: UserWarning: FSDP is switching to use `NO_SHARD` instead of ShardingStrategy.FULL_SHARD since the world size is 1.
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/win10-ubuntu/FastChat/fastchat/train/train_mem.py:13 in <module>                           │
│                                                                                                  │
│   10 from fastchat.train.train import train                                                      │
│   11                                                                                             │
│   12 if __name__ == "__main__":                                                                  │
│ ❱ 13 │   train()                                                                                 │
│   14                                                                                             │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/fastchat/train/train.py │
│ :264 in train                                                                                    │
│                                                                                                  │
│   261 │   if list(pathlib.Path(training_args.output_dir).glob("checkpoint-*")):                  │
│   262 │   │   trainer.train(resume_from_checkpoint=True)                                         │
│   263 │   else:                                                                                  │
│ ❱ 264 │   │   trainer.train()                                                                    │
│   265 │   trainer.save_state()                                                                   │
│   266 │   safe_save_model_for_hf_trainer(trainer=trainer, output_dir=training_args.output_dir)   │
│   267                                                                                            │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/transformers/trainer.py │
│ :1662 in train                                                                                   │
│                                                                                                  │
│   1659 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1660 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1661 │   │   )                                                                                 │
│ ❱ 1662 │   │   return inner_training_loop(                                                       │
│   1663 │   │   │   args=args,                                                                    │
│   1664 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1665 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/transformers/trainer.py │
│ :1749 in _inner_training_loop                                                                    │
│                                                                                                  │
│   1746 │   │   if args.gradient_checkpointing:                                                   │
│   1747 │   │   │   self.model.gradient_checkpointing_enable()                                    │
│   1748 │   │                                                                                     │
│ ❱ 1749 │   │   model = self._wrap_model(self.model_wrapped)                                      │
│   1750 │   │                                                                                     │
│   1751 │   │   if is_sagemaker_mp_enabled() and resume_from_checkpoint is not None:              │
│   1752 │   │   │   self._load_from_checkpoint(resume_from_checkpoint, model)                     │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/transformers/trainer.py │
│ :1489 in _wrap_model                                                                             │
│                                                                                                  │
│   1486 │   │   │   │   │   for arg in ["limit_all_gathers", "forward_prefetch", "backward_prefe  │
│   1487 │   │   │   │   │   │   if arg in signature:                                              │
│   1488 │   │   │   │   │   │   │   kwargs[arg] = getattr(self, arg)                              │
│ ❱ 1489 │   │   │   │   │   self.model = model = FSDP(                                            │
│   1490 │   │   │   │   │   │   model,                                                            │
│   1491 │   │   │   │   │   │   sharding_strategy=self.fsdp,                                      │
│   1492 │   │   │   │   │   │   cpu_offload=cpu_offload,                                          │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ fully_sharded_data_parallel.py:391 in __init__                                                   │
│                                                                                                  │
│    388 │   │   │   │   # process groups.                                                         │
│    389 │   │   │   │   fsdp_kwargs["process_group"] = (self.process_group, self._inter_node_pg)  │
│    390 │   │   │                                                                                 │
│ ❱  391 │   │   │   _auto_wrap(auto_wrap_kwargs, fsdp_kwargs, FullyShardedDataParallel)           │
│    392 │   │                                                                                     │
│    393 │   │   backward_prefetch_limit = 1                                                       │
│    394 │   │   forward_prefetch_limit = 1                                                        │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ _wrap_utils.py:73 in _auto_wrap                                                                  │
│                                                                                                  │
│    70 │   │   │   "kernels do not support low precision."                                        │
│    71 │   │   )                                                                                  │
│    72 │   auto_wrap_kwargs["auto_wrap_policy"] = auto_wrap_policy                                │
│ ❱  73 │   _recursive_wrap(**auto_wrap_kwargs, **fsdp_kwargs)                                     │
│    74                                                                                            │
│    75                                                                                            │
│    76 def _get_fully_sharded_module_to_states(                                                   │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ wrap.py:370 in _recursive_wrap                                                                   │
│                                                                                                  │
│   367 │   │   for name, child in module.named_children():                                        │
│   368 │   │   │   if child in ignored_modules:                                                   │
│   369 │   │   │   │   continue                                                                   │
│ ❱ 370 │   │   │   wrapped_child, num_wrapped_params = _recursive_wrap(                           │
│   371 │   │   │   │   module=child,                                                              │
│   372 │   │   │   │   auto_wrap_policy=auto_wrap_policy,                                         │
│   373 │   │   │   │   wrapper_cls=wrapper_cls,                                                   │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ wrap.py:370 in _recursive_wrap                                                                   │
│                                                                                                  │
│   367 │   │   for name, child in module.named_children():                                        │
│   368 │   │   │   if child in ignored_modules:                                                   │
│   369 │   │   │   │   continue                                                                   │
│ ❱ 370 │   │   │   wrapped_child, num_wrapped_params = _recursive_wrap(                           │
│   371 │   │   │   │   module=child,                                                              │
│   372 │   │   │   │   auto_wrap_policy=auto_wrap_policy,                                         │
│   373 │   │   │   │   wrapper_cls=wrapper_cls,                                                   │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ wrap.py:370 in _recursive_wrap                                                                   │
│                                                                                                  │
│   367 │   │   for name, child in module.named_children():                                        │
│   368 │   │   │   if child in ignored_modules:                                                   │
│   369 │   │   │   │   continue                                                                   │
│ ❱ 370 │   │   │   wrapped_child, num_wrapped_params = _recursive_wrap(                           │
│   371 │   │   │   │   module=child,                                                              │
│   372 │   │   │   │   auto_wrap_policy=auto_wrap_policy,                                         │
│   373 │   │   │   │   wrapper_cls=wrapper_cls,                                                   │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ wrap.py:388 in _recursive_wrap                                                                   │
│                                                                                                  │
│   385 │   │   │   module=module, recurse=False, nonwrapped_numel=remainder                       │
│   386 │   │   ):                                                                                 │
│   387 │   │   │   # Leaf node or final wrapping of the remainder both happen here.               │
│ ❱ 388 │   │   │   return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel                  │
│   389 │   │   else:                                                                              │
│   390 │   │   │   return module, total_wrapped_numel                                             │
│   391 │   return module, 0                                                                       │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ wrap.py:317 in _wrap                                                                             │
│                                                                                                  │
│   314 │   │   overrides = {**kwargs, **module._wrap_overrides}  # type: ignore[arg-type]         │
│   315 │   │   return wrapper_cls(module, **overrides)                                            │
│   316 │                                                                                          │
│ ❱ 317 │   return wrapper_cls(module, **kwargs)                                                   │
│   318                                                                                            │
│   319                                                                                            │
│   320 def _recursive_wrap(                                                                       │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ fully_sharded_data_parallel.py:408 in __init__                                                   │
│                                                                                                  │
│    405 │   │   _init_runtime_state(self)                                                         │
│    406 │   │   _init_prefetching_state(self, backward_prefetch, forward_prefetch)                │
│    407 │   │   _init_buffer_state(self, module)                                                  │
│ ❱  408 │   │   _init_param_handle_from_module(                                                   │
│    409 │   │   │   self,                                                                         │
│    410 │   │   │   module,                                                                       │
│    411 │   │   │   device_id,                                                                    │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ _init_utils.py:429 in _init_param_handle_from_module                                             │
│                                                                                                  │
│    426 │   │   _sync_module_params_and_buffers(                                                  │
│    427 │   │   │   fully_sharded_module, managed_params, state.process_group                     │
│    428 │   │   )                                                                                 │
│ ❱  429 │   _init_param_handle_from_params(state, managed_params, fully_sharded_module)           │
│    430 │   return state                                                                          │
│    431                                                                                           │
│    432                                                                                           │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ _init_utils.py:525 in _init_param_handle_from_params                                             │
│                                                                                                  │
│    522 ):                                                                                        │
│    523 │   if len(params) == 0:                                                                  │
│    524 │   │   return                                                                            │
│ ❱  525 │   handle = FlatParamHandle(                                                             │
│    526 │   │   params,                                                                           │
│    527 │   │   fully_sharded_module,                                                             │
│    528 │   │   state.compute_device,                                                             │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ flat_param.py:366 in __init__                                                                    │
│                                                                                                  │
│    363 │   │   self._training_state = HandleTrainingState.IDLE                                   │
│    364 │   │   self._debug_level = dist.get_debug_level()                                        │
│    365 │   │   self._fully_sharded_module = fully_sharded_module                                 │
│ ❱  366 │   │   self._init_flat_param(params, fully_sharded_module, use_orig_params)              │
│    367 │   │   self._orig_param_dtype = self.flat_param.dtype                                    │
│    368 │   │   self._use_unsharded_views(as_params=False)                                        │
│    369 │   │   self._init_param_reduce_dtypes(mp_param_dtype, mp_reduce_dtype)                   │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ flat_param.py:462 in _init_flat_param                                                            │
│                                                                                                  │
│    459 │   │   │   "Passed-in `params` were not found in the module tree\n"                      │
│    460 │   │   │   f"params: {params}\nmodule: {module}"                                         │
│    461 │   │   )                                                                                 │
│ ❱  462 │   │   self.flat_param = FlatParamHandle.flatten_params(                                 │
│    463 │   │   │   params_to_flatten, requires_grad                                              │
│    464 │   │   )                                                                                 │
│    465 │   │   # For `use_orig_params=True`, ensure that the logical parameters are              │
│                                                                                                  │
│ /home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/fsdp/ │
│ flat_param.py:505 in flatten_params                                                              │
│                                                                                                  │
│    502 │   │   │   │   p.detach().reshape(-1) if isinstance(p, nn.Parameter) else p.reshape(-1)  │
│    503 │   │   │   │   for p in params                                                           │
│    504 │   │   │   ]                                                                             │
│ ❱  505 │   │   │   flat_param_data = torch.cat(flat_params, dim=0)                               │
│    506 │   │   flat_param = FlatParameter(flat_param_data, requires_grad=requires_grad)          │
│    507 │   │   return flat_param                                                                 │
│    508                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: unknown error
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7877) of binary: /home/win10-ubuntu/anaconda3/envs/vicuna-7b/bin/python3.10
Traceback (most recent call last):
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/win10-ubuntu/anaconda3/envs/vicuna-7b/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
fastchat/train/train_mem.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-14_10:01:50
  host      : DESKTOP-LA7GLEG.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 7877)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by rohan-varma** [comment]
@awgu Looks like the issue is ""Passed-in params were not found in the module tree\n""

**Comment by Hzzhang-nlp** [comment]
How to added module:fsdp....

**Comment by Hzzhang-nlp** [comment]
Your description is not clear. Could you elaborate on it?

**Comment by mori360** [comment]
We are committed to support FSDP2. Here is the migration guide https://github.com/pytorch/torchtitan/blob/main/docs/fsdp.md
If you encounter any similar issues with FSDP2, please open a new issue with updated information.
