### ISSUE TITLE
Disabling ALL TestOptim on the dynamo config

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#103322]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/102640 introduced flakiness into the dynamo optim tests.

There was a followup PR https://github.com/pytorch/pytorch/pull/103066 to try to disable the tests in attempt to restore health, but that did not sufficiently cover all forms of flakiness as there were further reports of flaky tests after. 

This issue tracks the fact that we currently disable ALL test_optim tests in the dynamo shard, which is probably undesirable, but is a necessary stopgap to restore CI health. The alternative is reverting https://github.com/pytorch/pytorch/pull/102640 and its forward fixes, like https://github.com/pytorch/pytorch/pull/103121. 

### Versions

main

cc @vincentqb @jbschlosser @albanD @crcrpar @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ezyang @gchanan @zou3519 @anijain2305 @Xia-Weiwen @ipiszy

**Comment by janeyx99** [comment]
Now that https://github.com/pytorch/pytorch/pull/103323 has landed, I am going to close all the DISABLE issues for test_optim.

**Comment by janeyx99** [comment]
cc @mlazos We should work towards restoring these tests.

**Comment by malfet** [comment]
@janeyx99 can you please clarify whether or not its specific to python version (there is a flakiness in 3.11 I'm aware of)

**Comment by janeyx99** [comment]
It is not 3.11 specific, the tests have also been flaky on 3.8
![image](https://github.com/pytorch/pytorch/assets/31798555/9d80dde2-0fc3-422b-81bb-2dfc814f13bd)

**Comment by janeyx99** [comment]
In the logs of https://github.com/pytorch/pytorch/runs/13983709678
```
==================================== RERUNS ====================================
2023-06-04T02:07:37.3786247Z ___________________________ TestOptim.test_adadelta ____________________________
2023-06-04T02:07:37.3786478Z Traceback (most recent call last):
2023-06-04T02:07:37.3786765Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 1079, in test_adadelta
2023-06-04T02:07:37.3787028Z     self._test_basic_cases(
2023-06-04T02:07:37.3787305Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 343, in _test_basic_cases
2023-06-04T02:07:37.3787564Z     self._test_state_dict(
2023-06-04T02:07:37.3787840Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 207, in _test_state_dict
2023-06-04T02:07:37.3788128Z     optimizer = constructor(weight, bias)
2023-06-04T02:07:37.3788430Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 208, in <resume in _test_state_dict>
2023-06-04T02:07:37.3788752Z     fn = functools.partial(fn_base, optimizer, weight, bias)
2023-06-04T02:07:37.3789082Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 232, in <resume in _test_state_dict>
2023-06-04T02:07:37.3789408Z     self.assertEqual(optimizer.state_dict(), optimizer_c.state_dict())
2023-06-04T02:07:37.3789875Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3088, in assertEqual
2023-06-04T02:07:37.3790182Z     raise error_metas[0].to_error(
2023-06-04T02:07:37.3790408Z AssertionError: Scalars are not close!
2023-06-04T02:07:37.3790538Z 
2023-06-04T02:07:37.3790617Z Expected 2 but got 1.
2023-06-04T02:07:37.3790832Z Absolute difference: 1 (up to 0.0 allowed)
2023-06-04T02:07:37.3791071Z Relative difference: 0.5 (up to 0.004 allowed)
2023-06-04T02:07:37.3791211Z 
2023-06-04T02:07:37.3791360Z The failure occurred for item ['state'][0]['step']
2023-06-04T02:07:37.3791631Z ___________________________ TestOptim.test_adadelta ____________________________
2023-06-04T02:07:37.3791875Z Traceback (most recent call last):
2023-06-04T02:07:37.3792160Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 1079, in test_adadelta
2023-06-04T02:07:37.3792409Z     self._test_basic_cases(
2023-06-04T02:07:37.3792684Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 343, in _test_basic_cases
2023-06-04T02:07:37.3792950Z     self._test_state_dict(
2023-06-04T02:07:37.3793208Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 207, in _test_state_dict
2023-06-04T02:07:37.3793505Z     optimizer = constructor(weight, bias)
2023-06-04T02:07:37.3793816Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 208, in <resume in _test_state_dict>
2023-06-04T02:07:37.3794130Z     fn = functools.partial(fn_base, optimizer, weight, bias)
2023-06-04T02:07:37.3794520Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 226, in <resume in _test_state_dict>
2023-06-04T02:07:37.3794799Z     optimizer_c.step(fn_c)
2023-06-04T02:07:37.3795187Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/optim/optimizer.py", line 34, in _use_grad
2023-06-04T02:07:37.3795471Z     ret = func(self, *args, **kwargs)
2023-06-04T02:07:37.3795852Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/optim/adadelta.py", line 88, in step
2023-06-04T02:07:37.3796124Z     loss = closure()
2023-06-04T02:07:37.3796499Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/optim/adadelta.py", line 105, in <resume in step>
2023-06-04T02:07:37.3796920Z     self._init_group(group, params_with_grad, grads, square_avgs, acc_deltas)
2023-06-04T02:07:37.3797357Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/optim/adadelta.py", line 60, in _init_group
2023-06-04T02:07:37.3797641Z     state = self.state[p]
2023-06-04T02:07:37.3797838Z KeyError: Parameter containing:
2023-06-04T02:07:37.3798122Z tensor([[-0.0450, -0.4299,  0.2298, -0.8150,  0.1206],
2023-06-04T02:07:37.3798393Z         [ 0.6125, -0.1155, -0.5234, -0.2711,  0.8281],
2023-06-04T02:07:37.3798646Z         [-0.6916, -0.3021, -0.2756, -1.3352,  0.3875],
2023-06-04T02:07:37.3798913Z         [-0.9587,  0.8620, -0.0291, -0.6418, -1.5392],
2023-06-04T02:07:37.3799176Z         [ 0.2359,  0.4367, -0.4385, -0.7652, -0.2238],
2023-06-04T02:07:37.3799421Z         [-1.3941,  0.2860,  0.3116, -1.2594,  0.7624],
2023-06-04T02:07:37.3799678Z         [-0.7266,  1.1522, -1.5585,  0.8174, -1.5906],
2023-06-04T02:07:37.3799936Z         [-1.9464, -1.4494,  0.4556, -1.1170,  0.7575],
2023-06-04T02:07:37.3800184Z         [-0.2177, -0.5003,  0.7464,  0.7900,  0.0980],
2023-06-04T02:07:37.3800488Z         [-1.5940, -1.8121,  0.8025,  0.4563,  0.5810]], requires_grad=True)
2023-06-04T02:07:37.3800751Z ____________________________ TestOptim.test_adamax _____________________________
2023-06-04T02:07:37.3800995Z Traceback (most recent call last):
2023-06-04T02:07:37.3801269Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 1254, in test_adamax
2023-06-04T02:07:37.3801533Z     self._test_basic_cases(
2023-06-04T02:07:37.3801812Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 343, in _test_basic_cases
2023-06-04T02:07:37.3802064Z     self._test_state_dict(
2023-06-04T02:07:37.3802336Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 232, in _test_state_dict
2023-06-04T02:07:37.3802667Z     self.assertEqual(optimizer.state_dict(), optimizer_c.state_dict())
2023-06-04T02:07:37.3803136Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3051, in assertEqual
2023-06-04T02:07:37.3803448Z     error_metas = not_close_error_metas(
2023-06-04T02:07:37.3803875Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1217, in not_close_error_metas
2023-06-04T02:07:37.3804190Z     raise error_meta.to_error() from None
2023-06-04T02:07:37.3804438Z AssertionError: The keys of the mappings do not match:
2023-06-04T02:07:37.3804697Z Missing keys in the actual mapping: [None]
2023-06-04T02:07:37.3804937Z Additional keys in the actual mapping: []
2023-06-04T02:07:37.3805080Z 
2023-06-04T02:07:37.3805207Z The failure occurred for item ['state']
2023-06-04T02:07:37.3805462Z ____________________________ TestOptim.test_rmsprop ____________________________
2023-06-04T02:07:37.3805707Z Traceback (most recent call last):
2023-06-04T02:07:37.3805991Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 1328, in test_rmsprop
2023-06-04T02:07:37.3806239Z     self._test_basic_cases(
2023-06-04T02:07:37.3806521Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 343, in _test_basic_cases
2023-06-04T02:07:37.3806782Z     self._test_state_dict(
2023-06-04T02:07:37.3807041Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 232, in _test_state_dict
2023-06-04T02:07:37.3807521Z     self.assertEqual(optimizer.state_dict(), optimizer_c.state_dict())
2023-06-04T02:07:37.3808002Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3088, in assertEqual
2023-06-04T02:07:37.3808313Z     raise error_metas[0].to_error(
2023-06-04T02:07:37.3808523Z AssertionError: Scalars are not equal!
2023-06-04T02:07:37.3808664Z 
2023-06-04T02:07:37.3808745Z Expected 2 but got 1.
2023-06-04T02:07:37.3808934Z Absolute difference: 1
2023-06-04T02:07:37.3809121Z Relative difference: 0.5
2023-06-04T02:07:37.3809244Z 
2023-06-04T02:07:37.3809405Z The failure occurred for item ['state'][0]['step']
2023-06-04T02:07:37.3809881Z ____________________________ TestOptim.test_rmsprop ____________________________
2023-06-04T02:07:37.3810126Z Traceback (most recent call last):
2023-06-04T02:07:37.3810409Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 1328, in test_rmsprop
2023-06-04T02:07:37.3810673Z     self._test_basic_cases(
2023-06-04T02:07:37.3810940Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 343, in _test_basic_cases
2023-06-04T02:07:37.3811207Z     self._test_state_dict(
2023-06-04T02:07:37.3811481Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 232, in _test_state_dict
2023-06-04T02:07:37.3811806Z     self.assertEqual(optimizer.state_dict(), optimizer_c.state_dict())
2023-06-04T02:07:37.3812267Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3088, in assertEqual
2023-06-04T02:07:37.3812573Z     raise error_metas[0].to_error(
2023-06-04T02:07:37.3812796Z AssertionError: Scalars are not equal!
2023-06-04T02:07:37.3812941Z 
2023-06-04T02:07:37.3813006Z Expected 2 but got 1.
2023-06-04T02:07:37.3813200Z Absolute difference: 1
2023-06-04T02:07:37.3813399Z Relative difference: 0.5
2023-06-04T02:07:37.3813520Z 
2023-06-04T02:07:37.3813670Z The failure occurred for item ['state'][0]['step']
2023-06-04T02:07:37.3813923Z =================================== FAILURES ===================================
2023-06-04T02:07:37.3814184Z ____________________________ TestOptim.test_rmsprop ____________________________
2023-06-04T02:07:37.3814427Z Traceback (most recent call last):
2023-06-04T02:07:37.3814699Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 1328, in test_rmsprop
2023-06-04T02:07:37.3814960Z     self._test_basic_cases(
2023-06-04T02:07:37.3815236Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 343, in _test_basic_cases
2023-06-04T02:07:37.3815486Z     self._test_state_dict(
2023-06-04T02:07:37.3815758Z   File "/var/lib/jenkins/workspace/test/optim/test_optim.py", line 232, in _test_state_dict
2023-06-04T02:07:37.3816094Z     self.assertEqual(optimizer.state_dict(), optimizer_c.state_dict())
2023-06-04T02:07:37.3816565Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3088, in assertEqual
2023-06-04T02:07:37.3816865Z     raise error_metas[0].to_error(
2023-06-04T02:07:37.3817089Z AssertionError: Scalars are not equal!
2023-06-04T02:07:37.3817228Z 
2023-06-04T02:07:37.3817307Z Expected 2 but got 1.
2023-06-04T02:07:37.3817487Z Absolute difference: 1
2023-06-04T02:07:37.3817685Z Relative difference: 0.5
2023-06-04T02:07:37.3817809Z 
2023-06-04T02:07:37.3817970Z The failure occurred for item ['state'][0]['step']
2023-06-04T02:07:37.3818414Z - generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/test_optim/test_optim-5e39935887bc7514.xml -
2023-06-04T02:07:37.3818770Z =========================== short test summary info ============================
2023-06-04T02:07:37.3819169Z FAILED [0.1300s] test_optim.py::TestOptim::test_rmsprop - AssertionError: Scalars are not equal!
2023-06-04T02:07:37.3819374Z 
2023-06-04T02:07:37.3819454Z Expected 2 but got 1.
2023-06-04T02:07:37.3819635Z Absolute difference: 1
2023-06-04T02:07:37.3819837Z Relative difference: 0.5
2023-06-04T02:07:37.3819960Z 
2023-06-04T02:07:37.3820119Z The failure occurred for item ['state'][0]['step']
2023-06-04T02:07:37.3820471Z !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-06-04T02:07:37.3820754Z ========= 1 failed, 18 passed, 9 skipped, 5 rerun in 67.65s (0:01:07) ==========
2023-06-04T02:07:37.3821011Z Got exit code 1, retrying (retries left=2)
2023-06-04T02:07:37.3821418Z Test results will be stored in test-reports/python-pytest/test_optim/test_optim-9174f99057d09940.xml
```

**Comment by janeyx99** [comment]
Deprioritized as status of dynamo'd tests seems uncertain and it's been so long.
