### ISSUE TITLE
[inductor] certain reductions cause triton compile error

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#103481]
The following code causes a triton compiler error (initially revealed by the failing test `pytest ./generated/test_clovaai_lffont.py -k test_008` in https://github.com/pytorch/pytorch/issues/92670):
```python
import torch
def fn(x, y):
    # NOTE: 6 dimensions is important! does not fail for 5 dimensions
    mean = torch.mean(x, [2, 3, 4, 5], keepdim=True)
    add = mean + y
    return add
if __name__ == '__main__':
    x = torch.rand(4, 4, 4, 4, 4, 4, device="cuda")
    y = torch.rand((), device="cuda")
    fn(x, y)
    opt_fn = torch.compile(fn)
    opt_fn(x, y)
```

```
Traceback (most recent call last):
  File "playground7.py", line 14, in <module>
    opt_fn(x, y)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 292, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 445, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 527, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2023, in run
    super().run()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 707, in run
    and self.step()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 667, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2111, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 760, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/scratch/williamwen/work/py38-14k-env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 857, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 913, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 909, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/scratch/williamwen/work/pytorch/torch/__init__.py", line 1536, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/compile_fx.py", line 815, in compile_fx
    return aot_autograd(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3707, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3233, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2073, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2253, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1527, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/compile_fx.py", line 770, in fw_compiler_base
    return inner_compile(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/py38-14k-env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/compile_fx.py", line 47, in newFunction
    return old_func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/compile_fx.py", line 317, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/scratch/williamwen/work/pytorch/torch/_inductor/graph.py", line 898, in compile_to_fn
    return self.compile_to_module().call
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/graph.py", line 873, in compile_to_module
    mod = PyCodeCache.load(code, linemap=linemap)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/codecache.py", line 741, in load
    return cls.load_by_key_path(key, path, linemap)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/codecache.py", line 756, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_williamwen/xy/cxyx2wh3juqgbugknmjhsokvme3yckrsxth2c7tlulvtf5oyqara.py", line 71, in <module>
    async_compile.wait(globals())
  File "/scratch/williamwen/work/pytorch/torch/_inductor/codecache.py", line 1027, in wait
    scope[key] = result.result()
  File "/scratch/williamwen/work/pytorch/torch/_inductor/codecache.py", line 886, in result
    self.future.result()
  File "/scratch/williamwen/work/py38-14k-env/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/scratch/williamwen/work/py38-14k-env/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CompilationError: at 21:39:    r1 = rindex
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (r1 + (256*x0)), rmask & xmask, other=0)
    tmp6 = tl.load(in_ptr1 + (0))
    tmp7 = tl.broadcast_to(tmp6, [1])
    tmp2 = tl.where(rmask & xmask, tmp0, 0)
    tmp3 = tl.sum(tmp2, 0)
    tmp4 = 256.0
    tmp5 = tmp3 / tmp4
    tmp8 = tmp5 + tmp7
    tl.debug_barrier()
    tl.store(in_out_ptr0 + (x0), tmp8, xmask)
                                       ^
ValueError('Value argument cannot be block type if pointer argument is not a block')


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

The cause of the bug appears to be from https://github.com/pytorch/pytorch/pull/102444, in particular, I think that the `self.no_x_dim` condition is too weak.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @aakhundov @chenyang78

**Comment by ngimel** [comment]
HOw does code for 5 dims look like? Seems like we shouldn't need `xmask` and broadcasting `tmp7` to [1], that ultimately causes value to be block type

**Comment by williamwen42** [comment]
Code for 6 dims:
```python
from ctypes import c_void_p, c_long
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile

from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


# kernel path: /tmp/torchinductor_williamwen/u4/cu4xzlc6kbejx4rhe672sn67oqpxv4y6kpni656nyvb7j72cw6in.py
# Original ATen: aten.add, aten.mean

# aten.add => add
# aten.mean => mean
triton_per_fused_add_mean_0 = async_compile.triton('triton_', '''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_heuristics import persistent_reduction
from torch._inductor.utils import instance_descriptor
from torch._inductor import triton_helpers

@persistent_reduction(
    size_hints=[16, 256],
    reduction_hint=ReductionHint.INNER,
    filename=__file__,
    meta={'signature': {0: '*fp32', 1: '*fp32', 2: '*fp32', 3: 'i32', 4: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': ['in_out_ptr0'], 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2, 3, 4), equal_to_1=())]}
)
@triton.jit
def triton_(in_out_ptr0, in_ptr0, in_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr):
    xnumel = 16
    rnumel = 256
    RBLOCK: tl.constexpr = 256
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset 
    xmask = xindex < xnumel
    rindex = tl.arange(0, RBLOCK)[:]
    rmask = rindex < rnumel
    r1 = rindex
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (r1 + (256*x0)), rmask & xmask, other=0)
    tmp6 = tl.load(in_ptr1 + (0))
    tmp7 = tl.broadcast_to(tmp6, [1])
    tmp2 = tl.where(rmask & xmask, tmp0, 0)
    tmp3 = tl.sum(tmp2, 0)
    tmp4 = 256.0
    tmp5 = tmp3 / tmp4
    tmp8 = tmp5 + tmp7
    tl.debug_barrier()
    tl.store(in_out_ptr0 + (x0), tmp8, xmask)
''')

import triton
import triton.language as tl
from torch._inductor.triton_heuristics import grid, start_graph, end_graph
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1 = args
    args.clear()
    assert_size_stride(arg0_1, (4, 4, 4, 4, 4, 4), (1024, 256, 64, 16, 4, 1))
    assert_size_stride(arg1_1, (1, ), (1, ))
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0) # no-op to ensure context
        buf0 = empty_strided((4, 4, 1, 1, 1, 1), (4, 1, 16, 16, 16, 16), device='cuda', dtype=torch.float32)
        buf1 = as_strided(buf0, (4, 4, 1, 1, 1, 1), (4, 1, 1, 1, 1, 1)); del buf0  # reuse
        stream0 = get_cuda_stream(0)
        triton_per_fused_add_mean_0.run(buf1, arg0_1, arg1_1, 16, 256, grid=grid(16), stream=stream0)
        del arg0_1
        del arg1_1
        return (buf1, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((4, 4, 4, 4, 4, 4), (1024, 256, 64, 16, 4, 1), device='cuda:0', dtype=torch.float32)
    arg1_1 = rand_strided((1, ), (1, ), device='cuda:0', dtype=torch.float32)
    return print_performance(lambda: call([arg0_1, arg1_1]), times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.utils import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)
```

Code for 5 dims (`4, 4, 4, 4, 4, 4 -> 4, 4, 4, 4, 4`, `[2, 3, 4, 5] -> [2, 3, 4]`):
```python
from ctypes import c_void_p, c_long
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile

from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


# kernel path: /tmp/torchinductor_williamwen/4r/c4r6zqm6wr4rbl6mbscyttzgu5tnf6d74vu3sgc7uku4o4ugmt3q.py
# Original ATen: aten.add, aten.mean

# aten.add => add
# aten.mean => mean
triton_per_fused_add_mean_0 = async_compile.triton('triton_', '''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_heuristics import persistent_reduction
from torch._inductor.utils import instance_descriptor
from torch._inductor import triton_helpers

@persistent_reduction(
    size_hints=[16, 64],
    reduction_hint=ReductionHint.INNER,
    filename=__file__,
    meta={'signature': {0: '*fp32', 1: '*fp32', 2: '*fp32', 3: 'i32', 4: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': ['in_out_ptr0'], 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2, 3, 4), equal_to_1=())]}
)
@triton.jit
def triton_(in_out_ptr0, in_ptr0, in_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr):
    xnumel = 16
    rnumel = 64
    RBLOCK: tl.constexpr = 64
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset  + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rindex = tl.arange(0, RBLOCK)[None, :]
    rmask = rindex < rnumel
    r1 = rindex
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (r1 + (64*x0)), rmask & xmask, other=0)
    tmp6 = tl.load(in_ptr1 + (0))
    tmp7 = tl.broadcast_to(tmp6, [XBLOCK, 1])
    tmp2 = tl.where(rmask & xmask, tmp0, 0)
    tmp3 = tl.sum(tmp2, 1)[:, None]
    tmp4 = 64.0
    tmp5 = tmp3 / tmp4
    tmp8 = tmp5 + tmp7
    tl.debug_barrier()
    tl.store(in_out_ptr0 + (x0), tmp8, xmask)
''')

import triton
import triton.language as tl
from torch._inductor.triton_heuristics import grid, start_graph, end_graph
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1 = args
    args.clear()
    assert_size_stride(arg0_1, (4, 4, 4, 4, 4), (256, 64, 16, 4, 1))
    assert_size_stride(arg1_1, (1, ), (1, ))
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0) # no-op to ensure context
        buf0 = empty_strided((4, 4, 1, 1, 1), (4, 1, 16, 16, 16), device='cuda', dtype=torch.float32)
        buf1 = as_strided(buf0, (4, 4, 1, 1, 1), (4, 1, 1, 1, 1)); del buf0  # reuse
        stream0 = get_cuda_stream(0)
        triton_per_fused_add_mean_0.run(buf1, arg0_1, arg1_1, 16, 64, grid=grid(16), stream=stream0)
        del arg0_1
        del arg1_1
        return (buf1, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((4, 4, 4, 4, 4), (256, 64, 16, 4, 1), device='cuda:0', dtype=torch.float32)
    arg1_1 = rand_strided((1, ), (1, ), device='cuda:0', dtype=torch.float32)
    return print_performance(lambda: call([arg0_1, arg1_1]), times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.utils import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)
```
