### ISSUE TITLE
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(all) [ListIteratorVariable()] {} in DynamicShapesReproTests.test_chunk_reformer_ff_dynamic_shapes

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#103620]
### 🐛 Describe the bug

```
_______________________________ DynamicShapesReproTests.test_chunk_reformer_ff_dynamic_shapes _______________________________
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/test/dynamo/test_repros.py", line 1068, in test_chunk_reformer_ff
    self.assertTrue(same(opt_model(input), correct))
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 2025, in run
    super().run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in wrapper
    return inner_fn(self, inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/functions.py", line 287, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/functions.py", line 120, in call_function
    return tx.inline_user_function_return(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 595, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 2130, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 2227, in inline_call_
    tracer.run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in wrapper
    return inner_fn(self, inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/builtin.py", line 604, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/base.py", line 230, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/exc.py", line 135, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(all) [ListIteratorVariable()] {}
from user code:
   File "/data/users/ezyang/b/pytorch/test/dynamo/test_repros.py", line 467, in forward
    return apply_chunking_to_forward(
  File "/data/users/ezyang/b/pytorch/test/dynamo/test_repros.py", line 482, in apply_chunking_to_forward
    assert all(input_tensor.shape[1] == tensor_shape for input_tensor in input_tensors)
Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

when run with `automatic_dynamic_shapes=True`

### Versions

main

**Comment by Pragyy-G** [comment]
Hello! I would like to solve the issue (I am beginner in open source), could anyone help me in understanding what exactly is the problem and how can I resolve it?

**Comment by jfischoff** [comment]
Is there a workaround for this?

**Comment by eellison** [comment]
We should have a way of registering dynamo decompositions for builtins as python syntax.  We support the following:
```
def all(iter):
      for elem in iter:
             if not bool(elem):
                   return False
      return True
```

but not `all`.

**Comment by jfischoff** [comment]
thanks for the explanation @eelison!

**Comment by Fidget-Spinner** [comment]
@jfischoff are you still working on this? If not, do you mind if I take over please?

**Comment by ezyang** [comment]
just go for it
