### ISSUE TITLE
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_method is_contiguous on DynamicShapesFunctionTests.test_is_contiguous_memory_format_dynamic_shapes

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#103618]
### 🐛 Describe the bug

```
________________________ DynamicShapesFunctionTests.test_is_contiguous_memory_format_dynamic_shapes _________________________
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/test/dynamo/test_functions.py", line 42, in test_fn
    return torch._dynamo.testing.standard_test(self, fn=fn, nargs=nargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/testing.py", line 220, in standard_test
    val1a = opt_fn(*args1)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 2025, in run
    super().run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in wrapper
    return inner_fn(self, inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1152, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/misc.py", line 586, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/tensor.py", line 558, in call_method
    return wrap_fx_proxy(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/builder.py", line 1063, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/builder.py", line 1239, in wrap_fx_proxy_cls
    unimplemented(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/exc.py", line 135, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_method is_contiguous
from user code:
   File "/data/users/ezyang/b/pytorch/test/dynamo/test_functions.py", line 962, in test_is_contiguous_memory_format
    elif tensor.is_contiguous(memory_format=torch.contiguous_format):
Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

Run the test with `automatic_dynamic_shapes=True`.

### Versions

main

**Comment by steegecs** [comment]
I am working on this!

**Comment by steegecs** [comment]
How can I reproduce? When I run the command it does not want to recognize the automatic_dynamic_shapes=True attribute. 

![Uploading Screenshot 2023-06-25 at 9.53.45 PM.png…]()

**Comment by ezyang** [comment]
You can patch in https://github.com/pytorch/pytorch/pull/103623 and then delete `expectedFailureDynamic` from the test

**Comment by vdesai2014** [comment]
@ezyang 

Ran this test with the 'expectedFailureDynamic' decorator removed, automatic_dynamic_shapes was already True in my config.py file on the latest repo pull I just did, everything seems to pass. Is this issue just outdated?

**Comment by ezyang** [comment]
Thanks for confirming it's fixed!
