### ISSUE TITLE
test_fstrings2 fails with dynamic

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#103602]
### 🐛 Describe the bug

```
    @make_test
    def test_fstrings2(x):
        tmp = f"{x.shape[0]} bar"
        if tmp.startswith("10"):
            return x + 1
```

fails with

```
stats [('calls_captured', 1), ('unique_graphs', 1)]
.[2023-06-14 10:10:13,223] torch._dynamo.utils: [ERROR] Accuracy failed (<class 'NoneType'>): None != tensor([[ 0.8883,  0.5034,  1.1631,  0.1183,  1.0539,  1.6684,  0.9403,  0.5325,
          0.7847,  1.8840],
        [ 0.2416,  0.6311,  0.6576, -0.4020,  1.3206, -0.0219,  1.7988,  0.9077,
          0.2951, -0.6024],
        [ 1.2891,  1.4899,  0.6147,  0.2880,  0.8294, -0.4594,  1.2207,  1.2463,
         -0.3248,  1.6970],
        [ 0.3369,  2.2158, -0.4949,  1.8810, -0.1786,  0.0660,  0.4325,  0.7228,
         -1.1834,  1.3668],
        [ 1.9380,  1.0078,  0.6861, -0.1567,  2.8409, -0.0174,  2.2192,  1.1601,
          2.5985,  0.9531],
        [-0.5270, -1.0143, -0.5173,  1.3877, -0.1849,  1.6897,  2.3232,  2.8169,
          1.6808,  1.7244],
        [ 1.0323, -0.6593, -0.8773,  1.7372,  1.9257,  1.9247,  1.1825,  0.9263,
          1.3147, -0.0369],
        [ 1.2100,  1.6144,  1.0628,  0.6703, -0.7970,  1.8728,  1.7670,  0.8862,
          0.0572,  1.7540],
        [ 1.1407,  0.3063,  0.3841,  0.2705,  2.3204,  2.5997, -0.0792,  0.6604,
         -0.4538, -1.6740],
        [ 2.5984,  1.8021,  1.5722,  1.0653,  0.9765,  1.8876,  2.4689,  2.2647,
          0.7247,  0.8675]])
stats [('calls_captured', 1), ('unique_graphs', 1)]
F
======================================================================
FAIL: test_fstrings2_dynamic_shapes (torch._dynamo.testing.DynamicShapesFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/testing.py", line 305, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/test/dynamo/test_functions.py", line 42, in test_fn
    return torch._dynamo.testing.standard_test(self, fn=fn, nargs=nargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/testing.py", line 225, in standard_test
    self.assertTrue(same(val1a, correct1))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 2.427s

```

My guess is that SymNodeVariable isn't implementing printing correctly.

The obvious thing to do is specialize and guard in this situation. However, it's a little subtle: if someone creates a string and then ends up not using it, we would prefer to NOT have specialized. This can matter for poorly written error checking code.

### Versions

main

cc @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @penguinwu

**Comment by fool1280** [comment]
Hi, I'd like to take on this issue. May I ask for some guidance? Thank you!

**Comment by Bhavya-official** [comment]
I wanna contribute to this issue. @ezyang would you please guide me for resolving that issue.

**Comment by davidradl** [comment]
@ezyang did the other fix not work? Or is this a slightly different scenario?

**Comment by ezyang** [comment]
The PR you linked didn't actually get merged!

**Comment by tfsingh** [comment]
cc @bobby-palmer

**Comment by bobby-palmer** [comment]
Am I missing something here? I just ran the test after building from source with:
```python test/dynamo/test_functions.py FunctionTests.test_fstrings2```
The result was :
```
stats [('calls_captured', 1), ('unique_graphs', 1)]
.
----------------------------------------------------------------------
Ran 1 test in 0.103s

OK
```
maybe the formatting was fixed in a recent PR?

**Comment by ezyang** [comment]
run `test_dynamic_shapes.py` version of it

**Comment by bobby-palmer** [comment]
after removing the dynamic failure expected decorator I ran it with 
```
python test/dynamo/test_dynamic_shapes.py test_functions.FunctionTests.test_fstrings2
```
and got :
```
stats [('calls_captured', 1), ('unique_graphs', 1)]
.
----------------------------------------------------------------------
Ran 1 test in 0.053s

OK
```
Am i running the test incorrectly?

**Comment by ezyang** [comment]
This is more pressing with https://github.com/pytorch/pytorch/pull/130935 because rank gets turned into a dynamic variable, and a common reason to f-string a rank is to construct something like `f"cuda:{rank}", which now is just completely broken
