### ISSUE TITLE
[FSDP] save model checkpoint with StateDictType.LOCAL_STATE_DICT and LocalStateDictConfig(offload_to_cpu=True) fail

### ISSUE THREAD

**Issue by nkflash** [pytorch/pytorch#103730]
### 🐛 Describe the bug

Enable cpu offload and save FSDP model dict with local state dictionary fail with below error:
```
Traceback (most recent call last):
  File "train_llama_fsdp_datasets.py", line 219, in <module>
    trainer.do_train(
  File "/home/elrond/code/flagai-internal/flagai/env_trainer_v1.py", line 783, in do_train
    save_checkpoint(self.iteration+1,
  File "/home/elrond/code/flagai-internal/flagai/utils.py", line 239, in save_checkpoint
    fsdp_sd = model.state_dict()
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1833, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1833, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1833, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1835, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 674, in _post_state_dict_hook
    processed_state_dict = _post_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 439, in _local_post_state_dict_hook
    sharded_tensor = sharded_tensor.cpu()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/_shard/sharded_tensor/api.py", line 503, in cpu
    st_cpu = ShardedTensor._init_from_local_shards_and_global_metadata(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/_shard/sharded_tensor/api.py", line 945, in _init_from_local_shards_and_global_metadata
    _raise_if_mismatch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/_shard/sharded_tensor/api.py", line 897, in _raise_if_mismatch
    raise ValueError(
ValueError: Local shards' tensor requires_grad property is incompatible with tensor property on rank 3: tensor property requires_grad=True, local shard tensor requires_grad=False.
```

Code like:
```python
            with FSDP.state_dict_type(
                    model, StateDictType.LOCAL_STATE_DICT, LocalStateDictConfig(offload_to_cpu=True)
            ):
                fsdp_sd = model.state_dict()

```

local state dictionary work well when disable cpu offload, like
```python
with FSDP.state_dict_type(
                    model, StateDictType.LOCAL_STATE_DICT, LocalStateDictConfig(offload_to_cpu=False)
            ):
                fsdp_sd = model.state_dict()
```

### Versions

PyTorch version: 2.1.0.dev20230522+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.31

Python version: 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.129.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
Address sizes: 43 bits physical, 48 bits virtual
CPU(s): 256
On-line CPU(s) list: 0-255
Thread(s) per core: 2
Core(s) per socket: 64
Socket(s): 2
NUMA node(s): 8
Vendor ID: AuthenticAMD
CPU family: 23
Model: 49
Model name: AMD EPYC 7742 64-Core Processor
Stepping: 0
Frequency boost: enabled
CPU MHz: 3346.395
CPU max MHz: 2250.0000
CPU min MHz: 1500.0000
BogoMIPS: 4491.12
Virtualization: AMD-V
L1d cache: 4 MiB
L1i cache: 4 MiB
L2 cache: 64 MiB
L3 cache: 512 MiB
NUMA node0 CPU(s): 0-15,128-143
NUMA node1 CPU(s): 16-31,144-159
NUMA node2 CPU(s): 32-47,160-175
NUMA node3 CPU(s): 48-63,176-191
NUMA node4 CPU(s): 64-79,192-207
NUMA node5 CPU(s): 80-95,208-223
NUMA node6 CPU(s): 96-111,224-239
NUMA node7 CPU(s): 112-127,240-255
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1: Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2: Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] flake8==3.7.9
[pip3] numpy==1.19.2
[pip3] nvidia-dlprof-pytorch-nvtx==1.0.0
[pip3] pytorch-lightning==1.6.5
[pip3] pytorch-quantization==2.1.0
[pip3] pytorch-transformers==1.1.0
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230522+cu117
[pip3] torchaudio==2.1.0.dev20230522+cu117
[pip3] torchdata==0.7.0.dev20230522
[pip3] torchmetrics==0.11.0
[pip3] torchtext==0.16.0.dev20230522+cpu
[pip3] torchvision==0.16.0.dev20230522+cu117
[conda] magma-cuda110 2.5.2 5 local
[conda] mkl 2019.4 243
[conda] mkl-include 2019.4 243
[conda] nomkl 3.0 0
[conda] numpy 1.19.2 py38h6163131_0
[conda] numpy-base 1.19.2 py38h75fe3a5_0
[conda] nvidia-dlprof-pytorch-nvtx 1.0.0 pypi_0 pypi
[conda] pytorch-lightning 1.6.5 pypi_0 pypi
[conda] pytorch-quantization 2.1.0 pypi_0 pypi
[conda] pytorch-transformers 1.1.0 pypi_0 pypi
[conda] pytorch-triton 2.1.0+7d1a95b046 pypi_0 pypi
[conda] torch 2.1.0.dev20230522+cu117 pypi_0 pypi
[conda] torchaudio 2.1.0.dev20230522+cu117 pypi_0 pypi
[conda] torchdata 0.7.0.dev20230522 pypi_0 pypi
[conda] torchmetrics 0.11.0 pypi_0 pypi
[conda] torchtext 0.16.0.dev20230522+cpu pypi_0 pypi
[conda] torchvision 0.16.0.dev20230522+cu117 pypi_0 pypi

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by fegin** [comment]
Thanks for reporting this issue. This looks like a bug to me and I will have a PR to fix this issue. I'm curious about what's the use case to make you enable cpu_offload + local_state_dict.

**Comment by nkflash** [comment]
> local_state_dict



> Thanks for reporting this issue. This looks like a bug to me and I will have a PR to fix this issue. I'm curious about what's the use case to make you enable cpu_offload + local_state_dict.

I am training llama 33B model, so try to use distributed checkpoint to save/load cp

**Comment by LLCF** [comment]
I meet the same issue, do we have any WAR for this issue?

**Comment by mori360** [comment]
We are committed to support FSDP2. Here is the migration guide https://github.com/pytorch/torchtitan/blob/main/docs/fsdp.md
If you encounter any similar issues with FSDP2, please open a new issue with updated information.
