### ISSUE TITLE
torch.multiprocsssing.Queue.get() blocks

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/pytorch#10375]
## Issue description

I can not get the tensor from queue.

## Code example

```
import torch


def _process(queue):
    input_ = queue.get()
    print('get')
    queue.put(input_)
    print('put')


if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
    input_ = torch.ones(1).cuda()
    queue = torch.multiprocessing.Queue()
    queue.put(input_)
    process = torch.multiprocessing.Process(target=_process, args=(queue,))
    process.start()
    process.join()
    result = queue.get()
    print('end')
    print(result)
```

I executed this code, and only get and put printed, no end. I use ctrl-c to interrupt it, I find it blocks in result = queue.get(). Any idea?

## System Info

Collecting environment information...
PyTorch version: 0.4.0a0+200fb22
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Arch Linux
GCC version: (GCC) 8.1.1 20180531
CMake version: version 3.11.4

Python version: 2.7
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 396.45
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] Could not collect

**Comment by zou3519** [comment]
I think you might need to launch the other process first, and then put the tensor into the queue. 

The current order is that you're making a queue, passing a tensor into the queue, and then creating a new process with the queue.

**Comment by acgtyrant** [comment]
I change the script as below:

```
import torch


def _process(queue):
    input_ = queue.get()
    print('get')
    queue.put(input_)
    print('put')


if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
    input_ = torch.ones(1).cuda()
    queue = torch.multiprocessing.Queue()
    process = torch.multiprocessing.Process(target=_process, args=(queue,))
    process.start()
    queue.put(input_)
    process.join()
    result = queue.get()
    print('end')
    print(result)
```

It still blocks after print the 'put'.

**Comment by ezyang** [comment]
When I run your script, I get:

```
Traceback (most recent call last):
  File "/home/ezyang/Dev/pytorch-tmp-env/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ezyang/Dev/pytorch-tmp-env/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/data/users/ezyang/pytorch-tmp/torch/multiprocessing/reductions.py", line 125, in reduce_tensor
    (device, handle, storage_size, storage_offset) = storage._share_cuda_()
RuntimeError: invalid device pointer: 0x2049e0000 at ../aten/src/THC/THCCachingAllocator.cpp:262
```

This is actually an unrelated bug, where if you send a CUDA tensor to another process, and then send that *same* CUDA tensor back, it does not work, @colesbury tells me. If I send something else back, nothing blocks.

```
import torch


def _process(queue):
    input_ = queue.get()
    print('get')
    queue.put(0)
    print('put')


if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
    input_ = torch.ones(1).cuda()
    queue = torch.multiprocessing.Queue()
    process = torch.multiprocessing.Process(target=_process, args=(queue,))
    process.start()
    queue.put(input_)
    process.join()
    result = queue.get()
    print('end')
    print(result)
```

**Comment by zou3519** [comment]
I have an old PR open that tries to solve that problem (passing the same CUDA tensors between processes). The design needs some reworking but I can rebase it and push and update if it would be useful: https://github.com/pytorch/pytorch/pull/7204

**Comment by acgtyrant** [comment]
@zou3519 Looking forward to your fix. Thank you!

**Comment by neerajprad** [comment]
@zou3519, @ezyang : I bumped into this issue, in a slightly different context - we have a pool of workers which put tensors into a shared queue that is read by the main process. 

It works great for CPU tensors, but with CUDA tensors it works only with a single worker, and fails when we have 2 workers with the same `invalid device pointer` exception. 

While the actual example is a bit more complicated, it is (modifying the example above) along the lines of:

```python
import torch

def _process1(queue):
    queue.put(torch.tensor(1).cuda())
    print('put1')

def _process2(queue):
    queue.put(torch.tensor(2).cuda())
    print('put2')

if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
    queue = torch.multiprocessing.Queue()
    process1 = torch.multiprocessing.Process(target=_process1, args=(queue,))
    process2 = torch.multiprocessing.Process(target=_process2, args=(queue,))
    process1.start()
    process2.start()
    r1 = queue.get()
    r2 = queue.get()
    process1.join()
    process2.join()    
    print(r1, r2)
    print('end')
```

which throws an exception:
```
put1
THCudaCheck FAIL file=/home/npradhan/workspace/pyro_dev/pytorch/torch/csrc/generic/StorageSharing.cpp line=276 error=30 : unknown error
Traceback (most recent call last):
  File "examples/ex1.py", line 19, in <module>
    r1 = queue.get()
  File "/home/npradhan/miniconda3/envs/pytorch-master/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/npradhan/miniconda3/envs/pytorch-master/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 93, in rebuild_cuda_tensor
    storage = storage_cls._new_shared_cuda(storage_device, storage_handle, storage_size)
RuntimeError: cuda runtime error (30) : unknown error at /home/npradhan/workspace/pyro_dev/pytorch/torch/csrc/generic/StorageSharing.cpp:276
put2
```

I think the underlying reason is probably the same as the more complicated [example](https://github.com/uber/pyro/blob/dev/pyro/infer/mcmc/mcmc.py#L89) that I am trying to get to work with CUDA. 

In such cases, what is the recommended way (currently) to read data from multiple workers:
 - Should each worker communicate with the main process via its own `mp.Queue` instance?
 - Can we use the lighter-weight `mp.Pipe` between each worker and the main process instead?

**Comment by ngimel** [comment]
Is it still an issue?

**Comment by zou3519** [comment]
Running the original example in the issue, I get the following:

```
get
put
Traceback (most recent call last):
  File "/raid/rzou/pt/1.7-env/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/raid/rzou/pt/1.7-env/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/raid/rzou/pt/1.7/torch/multiprocessing/reductions.py", line 240, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
RuntimeError: Attempted to send CUDA tensor received from another process; this is not currently supported. Consider cloning before sending.
```

This is still an issue (I never ended up implementing the design I had for this) but it looks like we give a much better error message for it now

**Comment by NaxAlpha** [comment]
Torch 1.8 and the issue is the same
```
  File "C:\Users\user\anaconda3\envs\main\lib\multiprocessing\queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\user\anaconda3\envs\main\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\user\anaconda3\envs\main\lib\site-packages\torch\multiprocessing\reductions.py", line 240, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:253
```

**Comment by kxhit** [comment]
> I have an old PR open that tries to solve that problem (passing the same CUDA tensors between processes). The design needs some reworking but I can rebase it and push and update if it would be useful: #7204

Hi, I wish to pass one shared CUDA tensor to different processes, hoping other processes only use this shared tensor without a copy to save GPU memory. But I couldn't find a way to do it? Is there any solution? Thanks a lot!
