### ISSUE TITLE
torchinductor does not handle well `Tensor.squeeze` with tuple dim argument

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#103875]
### 🐛 Describe the bug

Syntax as `x = x.squeeze(0, 1)` is not handled well by torchinductor, while `x = x.squeeze(1).squeeze(0)` runs fine. Using `backend="eager"`, there is no issue, so I assume it is a problem with torchinductor.

Given that `Tensor.squeeze` accepts a tuple argument from 2.0, I would expect this syntax to work as well with torchinductor: https://pytorch.org/docs/stable/generated/torch.squeeze.html#torch.squeeze

### Error logs

In the minimal reproduction:
```
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [32,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [33,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [34,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [35,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [36,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [37,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [38,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [39,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [40,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [41,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [42,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [43,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [44,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [45,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [46,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [47,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [48,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [49,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [50,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [51,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [52,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [53,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [54,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [55,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [56,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [57,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [58,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [59,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [60,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [61,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [62,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [51,0,0], thread: [63,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [96,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [97,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [98,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [99,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [100,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [101,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [102,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [103,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [104,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [105,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [106,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [107,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [108,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [109,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [110,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [111,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [112,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [113,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [114,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [115,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [116,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [117,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [118,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [119,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [120,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [121,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [122,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [123,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [124,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [125,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [126,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
<frozen importlib._bootstrap_external>:883: _call_with_frames_removed: block: [14,0,0], thread: [127,0,0] Assertion `index out of bounds: 0 <= tmp2 < 1` failed.
Traceback (most recent call last):
  File "/home/ubuntu/bug.py", line 33, in <module>
    pos_id = torch.Tensor([[300]]).to(torch.device("cuda"), torch.int64)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

In modeling_llama.py, replacing https://github.com/huggingface/transformers/blob/c5454eba9eac00a3e7d0a46a3d25aacd43187f1e/src/transformers/models/llama/modeling_llama.py#L133 by `cos = cos.squeeze(0, 1)`, I had a different error:

```
...
    self.env[node] = self.run_node(node)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1161, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1325, in dispatch
    return fast_impl(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 719, in fast_binary_impl
    final_shape = infer_size(final_shape, shape)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 676, in infer_size
    raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: The size of tensor a (32) must match the size of tensor b (s0) at non-singleton dimension 2)

While executing %mul_2 : [#users=1] = call_function[target=operator.mul](args = (%getitem_5, %unsqueeze), kwargs = {})
Original traceback:
  File "/home/ubuntu/accelerated-pytorch-transformers-generation/src/trfs_fast/llama.py", line 702, in forward
    outputs = self.model(
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/accelerated-pytorch-transformers-generation/src/trfs_fast/llama.py", line 572, in forward
    layer_outputs = decoder_layer(
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/accelerated-pytorch-transformers-generation/src/trfs_fast/llama.py", line 294, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/accelerated-pytorch-transformers-generation/src/trfs_fast/llama.py", line 218, in forward
    query_states = apply_rotary_pos_emb_opt(query_states, key_value_states[0], cos, sin, position_ids)
  File "/home/ubuntu/accelerated-pytorch-transformers-generation/src/trfs_fast/llama.py", line 138, in apply_rotary_pos_emb_opt
    q_embed = (q * cos) + (rotate_half(q) * sin)
```

### Minified repro

```python
import torch.nn as nn
import torch

import torch._inductor.config as iconfig

# iconfig.trace.enabled = True
# iconfig.trace.graph_diagram = True

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        # self.foo = nn.Parameter(torch.rand(32, 64))
    
    def forward(self, x, y, pos_id):
        x = x.squeeze(0, 1)  # this one fails with torch.compile
        #x = x.squeeze(1).squeeze(0)  # this one goes fine with torch.compile
        x = x[pos_id].unsqueeze(1)
        res = x * y
        
        return res

model = MyModel()
model = model.to("cuda")
x = torch.rand(1, 1, 1002, 128, device="cuda")
y = torch.rand(1, 32, 1, 128, device="cuda")
pos_id = torch.Tensor([[200]]).to(torch.device("cuda"), torch.int64)

model.forward = torch.compile(model.forward, backend="eager")

with torch.no_grad():
    res = model(x, y, pos_id)

    x = torch.rand(1, 1, 543, 128, device="cuda")
    pos_id = torch.Tensor([[300]]).to(torch.device("cuda"), torch.int64)

    res = model(x, y, pos_id)
```

### Versions

```
PyTorch version: 2.1.0.dev20230619+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-1026-aws-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.105.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7R32
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        5599.72
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        2 MiB (4 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230619+cu118
[pip3] torchaudio==2.1.0.dev20230619+cu118
[pip3] torchvision==0.16.0.dev20230619+cu118
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
[conda] torch                     2.1.0.dev20230619+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230619+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230619+cu118          pypi_0    pypi
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78

**Comment by mlazos** [comment]
assigning @Chillee arbitrarily

**Comment by peterbell10** [comment]
I guess this is a long-standing behavior:
https://github.com/pytorch/pytorch/blob/f73ff54f9ab67097c7d616336770cb0b9acf9466/torch/csrc/utils/python_arg_parser.cpp#L1356-L1358

So, should the fx graph be normalized so it matches the actual function signature?
