### ISSUE TITLE
Conversion from CSR to BSR without blocksize leads to misleading exception

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#103877]
## Issue description

As in the title.

As shown below, the raised exception does not indicate what is wrong with the user input.

## Code example

```python
>>> a = torch.tensor([[0, 1], [2, 3]]).to_sparse_csr()
>>> a.to_sparse(layout=torch.sparse_bsr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: ArrayRef: invalid slice, N = 1; M = 2; size = 1
>>> a.to_sparse(layout=torch.sparse_bsr, blocksize=(1, 1))
tensor(crow_indices=tensor([0, 1, 3]),
       col_indices=tensor([1, 0, 1]),
       values=tensor([[[1]],

                      [[2]],

                      [[3]]]), size=(2, 2), nnz=3, layout=torch.sparse_bsr)
```

The expected behavior is an exception indicating that blocksize must be specified, similar to
```python
>>> a.to_sparse_bsr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: to_sparse_bsr() missing 1 required positional arguments: "blocksize"
```

## System Info

- PyTorch version: main

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer

**Comment by alexsamardzic** [comment]
This will be fixed by [PR 92022](https://github.com/pytorch/pytorch/pull/92022):
```Python
>>> a = torch.tensor([[0, 1], [2, 3]]).to_sparse_csr()
<stdin>:1: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /home/asamardzic/scratch/git/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
>>> a.to_sparse(layout=torch.sparse_bsr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: sparse_compressed_to_sparse: conversion from SparseCsr to SparseBsr without blocksize argument given is not supported
```

**Comment by alexsamardzic** [comment]
[PR 92022](https://github.com/pytorch/pytorch/pull/92022) merged.
