### ISSUE TITLE
Get an error while convert fx model to onnx

### ISSUE THREAD

**Issue by lfgogogo** [pytorch/pytorch#103838]
### 🐛 Describe the bug

I firstly convert torch model to quantized model,then I want to export it to onnx,here is the code:

```
import copy
from torch.ao.quantization import get_default_qconfig
from torch.ao.quantization.quantize_fx import convert_fx, prepare_fx
import time
import torch
from  alphabets import plateName,plate_chr
#from plateNet import myNet_ocr
from easydict import EasyDict as edict
import yaml
from lib.dataset import get_dataset
from torch.utils.data import DataLoader
import lib.utils.utils as utils
from tqdm import tqdm
from torch.ao.quantization.fx.graph_module import ObservedGraphModule

plateName=r"#京沪津渝冀晋蒙辽吉黑苏浙皖闽赣鲁豫鄂湘粤桂琼川贵云藏陕甘青宁新学警港澳挂使领民航危0123456789ABCDEFGHJKLMNPQRSTUVWXYZ险品"
cfg =[8,8,16,16,'M',32,32,'M',48,48,'M',64,128]

import torch.nn as nn
import torch.nn.functional as F

class myNet_ocr(nn.Module):
    def __init__(self,cfg=None,num_classes=78,export=False):
        super(myNet_ocr, self).__init__()
        #if cfg is None:
            #cfg =[32,32,64,64,'M',128,128,'M',196,196,'M',256,256]
            # cfg =[32,32,'M',64,64,'M',128,128,'M',256,256]
        self.feature = self.make_layers(cfg, True)
        self.export = export
        # self.classifier = nn.Linear(cfg[-1], num_classes)
        # self.loc =  nn.MaxPool2d((2, 2), (5, 1), (0, 1),ceil_mode=True)
        # self.loc =  nn.AvgPool2d((2, 2), (5, 2), (0, 1),ceil_mode=False)
        self.loc =  nn.MaxPool2d((5, 2), (1, 1),(0,1),ceil_mode=False)
        self.newCnn=nn.Conv2d(cfg[-1],num_classes,1,1)
        # self.newBn=nn.BatchNorm2d(num_classes)
    def make_layers(self, cfg, batch_norm=False):
        layers = []
        in_channels = 3
        conv2d =nn.Conv2d(in_channels, cfg[0], kernel_size=5,stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[0]), nn.ReLU(inplace=True)]
        in_channels = cfg[0]

        conv2d = nn.Conv2d(in_channels, cfg[1], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[1]), nn.ReLU(inplace=True)]
        in_channels = cfg[1]

        conv2d = nn.Conv2d(in_channels, cfg[2], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[2]), nn.ReLU(inplace=True)]
        in_channels = cfg[2]

        conv2d = nn.Conv2d(in_channels, cfg[3], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[3]), nn.ReLU(inplace=True)]
        in_channels = cfg[3]

        layers += [nn.MaxPool2d(kernel_size=3, stride=2,ceil_mode=True)]

        conv2d = nn.Conv2d(in_channels, cfg[5], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[5]), nn.ReLU(inplace=True)]
        in_channels = cfg[5]

        conv2d = nn.Conv2d(in_channels, cfg[6], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[6]), nn.ReLU(inplace=True)]
        in_channels = cfg[6]

        layers += [nn.MaxPool2d(kernel_size=3, stride=2,ceil_mode=True)]

        conv2d = nn.Conv2d(in_channels, cfg[8], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[8]), nn.ReLU(inplace=True)]
        in_channels = cfg[8]

        conv2d = nn.Conv2d(in_channels, cfg[9], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[9]), nn.ReLU(inplace=True)]
        in_channels = cfg[9]

        layers += [nn.MaxPool2d(kernel_size=3, stride=2,ceil_mode=True)]

        conv2d = nn.Conv2d(in_channels, cfg[11], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[11]), nn.ReLU(inplace=True)]
        in_channels = cfg[11]

        conv2d = nn.Conv2d(in_channels, cfg[12], kernel_size=3, padding=(1,1),stride =1)
        layers += [conv2d, nn.BatchNorm2d(cfg[12]), nn.ReLU(inplace=True)]
        in_channels = cfg[12]

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.feature(x)
        x=self.loc(x)
        #print(x.shape)
        x=self.newCnn(x)
        # x=self.newBn(x)
        conv = x.squeeze(2) # b *512 * width
        conv = conv.transpose(2,1)  # [w, b, c]
        return conv

def calib_quant_model(model, calib_dataloader):
    assert isinstance(
        model, ObservedGraphModule
    ), "model must be a perpared fx ObservedGraphModule."
    model.eval()
    with torch.inference_mode():
        for inputs, labels in tqdm(calib_dataloader):
            model(inputs)
    print("calib done.")

if __name__=='__main__':
    import os
    with open('lib/config/360CC_config.yaml', 'r') as f:
            # config = yaml.load(f, Loader=yaml.FullLoader)
            config = yaml.safe_load(f)
            config = edict(config)
    config.DATASET.ALPHABETS = plateName
    config.MODEL.NUM_CLASSES = len(config.DATASET.ALPHABETS)
    config.HEIGHT=48
    config.WIDTH = 168

    val_dataset = get_dataset(config)(config,input_w=config.WIDTH,input_h=config.HEIGHT, is_train=False)
    val_loader = DataLoader(
        dataset=val_dataset,
        batch_size=config.TEST.BATCH_SIZE_PER_GPU,
        shuffle=config.TEST.SHUFFLE,
        num_workers=config.WORKERS,
        pin_memory=config.PIN_MEMORY,
    )

    criterion = torch.nn.CTCLoss()
    converter = utils.strLabelConverter(config.DATASET.ALPHABETS)

    fp32_model = myNet_ocr(num_classes=len(plate_chr),cfg=cfg,export=True).eval()
    checkpoint = torch.load('weights/plate_rec.pth', map_location='cpu')
    fp32_model.load_state_dict(checkpoint['state_dict'])

    model = copy.deepcopy(fp32_model)
    qconfig = get_default_qconfig("fbgemm")
    qconfig_dict = {"": qconfig}

    model_prepared = prepare_fx(model, qconfig_dict,example_inputs=None)
    calib_quant_model(model_prepared,val_loader)
    model_quantized = convert_fx(model_prepared)#,is_reference=True)
    model_quantized.eval()
    print(model_quantized)
    
    input = torch.randn(1,3,48,168)
    dynamic=False
    torch.onnx.export(model_quantized,input,'plate_rec_quant.onnx',
                    input_names=["images"],output_names=["output"],
                    verbose=True,
                    do_constant_folding=True,
                    opset_version=11,
                    dynamic_axes={'images': {0: 'batch'},
                                'output': {0: 'batch'}
                                } if dynamic else None)
    print(f"convert completed,save to {'plate_rec_quant.onnx'}")  
```           
And i get log below:
```
UserWarning: Passing a QConfig dictionary to prepare is deprecated and will not be supported in a future version. Please pass in a QConfigMapping instead.
  warnings.warn(
UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:03<00:00,  3.19s/it]
calib done.
    
The shape inference of prim::TupleConstruct type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ../torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1884.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
Torch IR graph at exception: graph(%x : Float(128, 3, 48, 168, strides=[24192, 8064, 168, 1], requires_grad=0, device=cpu),
      %feature_0_input_zero_point_0 : Long(requires_grad=0, device=cpu),
      %feature_0_input_scale_0 : Float(requires_grad=0, device=cpu),
      %feature.0._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.3._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.6._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.9._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.13._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.16._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.20._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.23._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.27._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %feature.30._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %newCnn._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase):
  %218 : Long(device=cpu) = prim::Constant[value={86}](), scope: torch.fx.graph_module.GraphModule::/torch.ao.nn.quantized.modules.conv.Conv2d::newCnn
  %219 : Double(device=cpu) = prim::Constant[value={1.68552}](), scope: torch.fx.graph_module.GraphModule::/torch.ao.nn.quantized.modules.conv.Conv2d::newCnn
  %220 : Bool(device=cpu) = prim::Constant[value={0}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::loc
  %18 : int[] = prim::Constant[value=[0, 1]]()
  %19 : int[] = prim::Constant[value=[5, 2]]()
  %221 : Double(device=cpu) = prim::Constant[value={0.117653}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::30
  %222 : Double(device=cpu) = prim::Constant[value={0.0380354}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::27
  %223 : Double(device=cpu) = prim::Constant[value={0.0414114}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::23
  %224 : Double(device=cpu) = prim::Constant[value={0.0411179}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::20
  %225 : Double(device=cpu) = prim::Constant[value={0.0516132}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::16
  %226 : Double(device=cpu) = prim::Constant[value={0.0390538}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::13
  %227 : Bool(device=cpu) = prim::Constant[value={1}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::12
  %27 : int[] = prim::Constant[value=[1, 1]]()
  %228 : Long(device=cpu) = prim::Constant[value={1}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::12
  %29 : int[] = prim::Constant[value=[0, 0]]()
  %30 : int[] = prim::Constant[value=[2, 2]]()
  %229 : Long(device=cpu) = prim::Constant[value={2}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::12
  %32 : int[] = prim::Constant[value=[3, 3]]()
  %230 : Double(device=cpu) = prim::Constant[value={0.0429376}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::9
  %231 : Double(device=cpu) = prim::Constant[value={0.0572507}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::6
  %232 : Double(device=cpu) = prim::Constant[value={0.0657352}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::3
  %233 : Long(device=cpu) = prim::Constant[value={0}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::0
  %234 : Double(device=cpu) = prim::Constant[value={0.07126}](), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::0
  %235 : Long(device=cpu) = prim::Constant[value={13}](), scope: torch.fx.graph_module.GraphModule::
  %input.1 : Tensor = aten::quantize_per_tensor(%x, %feature_0_input_scale_0, %feature_0_input_zero_point_0, %235), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:7:0
  %118 : Tensor = prim::Constant[value=<Tensor>]()
  %119 : Tensor = prim::Constant[value=0.001 *  0.7156  0.5953  6.8219  0.5890  0.6383  0.5060  3.6715  1.0147 [ CPUFloatType{8} ]]()
  %120 : Tensor = prim::Constant[value= 0  0  0  0  0  0  0  0 [ CPUIntType{8} ]]()
  %121 : Tensor = prim::Constant[value={0}]()
  %122 : Tensor = prim::TupleConstruct(%118, %119, %120, %121)
  %123 : Tensor = prim::Constant[value= 0.3125  0.2298  1.3906  0.3711  0.2986  0.5607 -0.1880 -0.7181 [ CPUFloatType{8} ]]()
  %124 : Tensor = onnx::Constant[value=[1, 1]]()
  %125 : Tensor = onnx::Constant[value=[0, 0]]()
  %126 : Tensor = onnx::Constant[value=[1, 1]]()
  %127 : Tensor = onnx::Constant[value=1]()
  %input.3 : Tensor = quantized::conv2d_relu(%input.1, %122, %123, %124, %125, %126, %127, %234, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::0 # 
  %128 : Tensor = prim::Constant[value=<Tensor>]()
  %129 : Tensor = prim::Constant[value=0.01 *  0.4054  0.3453  0.2708  0.1908  0.2522  0.1467  0.3418  1.0591 [ CPUFloatType{8} ]]()
  %130 : Tensor = prim::Constant[value= 0  0  0  0  0  0  0  0 [ CPUIntType{8} ]]()
  %131 : Tensor = prim::Constant[value={0}]()
  %132 : Tensor = prim::TupleConstruct(%128, %129, %130, %131)
  %133 : Tensor = prim::Constant[value= 0.7561  0.5473  0.1409  0.6760  0.2236 -0.5607  0.7260  1.2522 [ CPUFloatType{8} ]]()
  %134 : Tensor = onnx::Constant[value=[1, 1]]()
  %135 : Tensor = onnx::Constant[value=[1, 1]]()
  %136 : Tensor = onnx::Constant[value=[1, 1]]()
  %137 : Tensor = onnx::Constant[value=1]()
  %input.5 : Tensor = quantized::conv2d_relu(%input.3, %132, %133, %134, %135, %136, %137, %232, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::3 # 
  %138 : Tensor = prim::Constant[value=<Tensor>]()
  %139 : Tensor = prim::Constant[value=<Tensor>]()
  %140 : Tensor = prim::Constant[value=<Tensor>]()
  %141 : Tensor = prim::Constant[value={0}]()
  %142 : Tensor = prim::TupleConstruct(%138, %139, %140, %141)
  %143 : Tensor = prim::Constant[value=<Tensor>]()
  %144 : Tensor = onnx::Constant[value=[1, 1]]()
  %145 : Tensor = onnx::Constant[value=[1, 1]]()
  %146 : Tensor = onnx::Constant[value=[1, 1]]()
  %147 : Tensor = onnx::Constant[value=1]()
  %input.7 : Tensor = quantized::conv2d_relu(%input.5, %142, %143, %144, %145, %146, %147, %231, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::6 # 
  %148 : Tensor = prim::Constant[value=<Tensor>]()
  %149 : Tensor = prim::Constant[value=<Tensor>]()
  %150 : Tensor = prim::Constant[value=<Tensor>]()
  %151 : Tensor = prim::Constant[value={0}]()
  %152 : Tensor = prim::TupleConstruct(%148, %149, %150, %151)
  %153 : Tensor = prim::Constant[value=<Tensor>]()
  %154 : Tensor = onnx::Constant[value=[1, 1]]()
  %155 : Tensor = onnx::Constant[value=[1, 1]]()
  %156 : Tensor = onnx::Constant[value=[1, 1]]()
  %157 : Tensor = onnx::Constant[value=1]()
  %input.9 : Tensor = quantized::conv2d_relu(%input.7, %152, %153, %154, %155, %156, %157, %230, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::9 # 
  %input.11 : Tensor = aten::max_pool2d(%input.9, %32, %30, %29, %27, %227), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::12 # 
  %158 : Tensor = prim::Constant[value=<Tensor>]()
  %159 : Tensor = prim::Constant[value=<Tensor>]()
  %160 : Tensor = prim::Constant[value=<Tensor>]()
  %161 : Tensor = prim::Constant[value={0}]()
  %162 : Tensor = prim::TupleConstruct(%158, %159, %160, %161)
  %163 : Tensor = prim::Constant[value=<Tensor>]()
  %164 : Tensor = onnx::Constant[value=[1, 1]]()
  %165 : Tensor = onnx::Constant[value=[1, 1]]()
  %166 : Tensor = onnx::Constant[value=[1, 1]]()
  %167 : Tensor = onnx::Constant[value=1]()
  %input.13 : Tensor = quantized::conv2d_relu(%input.11, %162, %163, %164, %165, %166, %167, %226, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::13 # 
  %168 : Tensor = prim::Constant[value=<Tensor>]()
  %169 : Tensor = prim::Constant[value=<Tensor>]()
  %170 : Tensor = prim::Constant[value=<Tensor>]()
  %171 : Tensor = prim::Constant[value={0}]()
  %172 : Tensor = prim::TupleConstruct(%168, %169, %170, %171)
  %173 : Tensor = prim::Constant[value=<Tensor>]()
  %174 : Tensor = onnx::Constant[value=[1, 1]]()
  %175 : Tensor = onnx::Constant[value=[1, 1]]()
  %176 : Tensor = onnx::Constant[value=[1, 1]]()
  %177 : Tensor = onnx::Constant[value=1]()
  %input.15 : Tensor = quantized::conv2d_relu(%input.13, %172, %173, %174, %175, %176, %177, %225, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::16 # 
  %input.17 : Tensor = aten::max_pool2d(%input.15, %32, %30, %29, %27, %227), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::19 # 
  %178 : Tensor = prim::Constant[value=<Tensor>]()
  %179 : Tensor = prim::Constant[value=<Tensor>]()
  %180 : Tensor = prim::Constant[value=<Tensor>]()
  %181 : Tensor = prim::Constant[value={0}]()
  %182 : Tensor = prim::TupleConstruct(%178, %179, %180, %181)
  %183 : Tensor = prim::Constant[value=<Tensor>]()
  %184 : Tensor = onnx::Constant[value=[1, 1]]()
  %185 : Tensor = onnx::Constant[value=[1, 1]]()
  %186 : Tensor = onnx::Constant[value=[1, 1]]()
  %187 : Tensor = onnx::Constant[value=1]()
  %input.19 : Tensor = quantized::conv2d_relu(%input.17, %182, %183, %184, %185, %186, %187, %224, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::20 # 
  %188 : Tensor = prim::Constant[value=<Tensor>]()
  %189 : Tensor = prim::Constant[value=<Tensor>]()
  %190 : Tensor = prim::Constant[value=<Tensor>]()
  %191 : Tensor = prim::Constant[value={0}]()
  %192 : Tensor = prim::TupleConstruct(%188, %189, %190, %191)
  %193 : Tensor = prim::Constant[value=<Tensor>]()
  %194 : Tensor = onnx::Constant[value=[1, 1]]()
  %195 : Tensor = onnx::Constant[value=[1, 1]]()
  %196 : Tensor = onnx::Constant[value=[1, 1]]()
  %197 : Tensor = onnx::Constant[value=1]()
  %input.21 : Tensor = quantized::conv2d_relu(%input.19, %192, %193, %194, %195, %196, %197, %223, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::23 # 
  %input.23 : Tensor = aten::max_pool2d(%input.21, %32, %30, %29, %27, %227), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::26 # 
  %198 : Tensor = prim::Constant[value=<Tensor>]()
  %199 : Tensor = prim::Constant[value=<Tensor>]()
  %200 : Tensor = prim::Constant[value=<Tensor>]()
  %201 : Tensor = prim::Constant[value={0}]()
  %202 : Tensor = prim::TupleConstruct(%198, %199, %200, %201)
  %203 : Tensor = prim::Constant[value=<Tensor>]()
  %204 : Tensor = onnx::Constant[value=[1, 1]]()
  %205 : Tensor = onnx::Constant[value=[1, 1]]()
  %206 : Tensor = onnx::Constant[value=[1, 1]]()
  %207 : Tensor = onnx::Constant[value=1]()
  %input.25 : Tensor = quantized::conv2d_relu(%input.23, %202, %203, %204, %205, %206, %207, %222, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::27 # 
  %208 : Tensor = prim::Constant[value=<Tensor>]()
  %209 : Tensor = prim::Constant[value=<Tensor>]()
  %210 : Tensor = prim::Constant[value=<Tensor>]()
  %211 : Tensor = prim::Constant[value={0}]()
  %212 : Tensor = prim::TupleConstruct(%208, %209, %210, %211)
  %213 : Tensor = prim::Constant[value=<Tensor>]()
  %214 : Tensor = onnx::Constant[value=[1, 1]]()
  %215 : Tensor = onnx::Constant[value=[1, 1]]()
  %216 : Tensor = onnx::Constant[value=[1, 1]]()
  %217 : Tensor = onnx::Constant[value=1]()
  %input.27 : Tensor = quantized::conv2d_relu(%input.25, %212, %213, %214, %215, %216, %217, %221, %233), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::30 # 
  %input : Tensor = aten::max_pool2d(%input.27, %19, %27, %18, %27, %220), scope: torch.fx.graph_module.GraphModule::/torch.nn.modules.pooling.MaxPool2d::loc # 
  %108 : Tensor = prim::Constant[value=<Tensor>]()
  %109 : Tensor = prim::Constant[value=<Tensor>]()
  %110 : Tensor = prim::Constant[value=<Tensor>]()
  %111 : Tensor = prim::Constant[value={0}]()
  %112 : Tensor = prim::TupleConstruct(%108, %109, %110, %111)
  %113 : Tensor = prim::Constant[value=<Tensor>]()
  %114 : Tensor = onnx::Constant[value=[1, 1]]()
  %115 : Tensor = onnx::Constant[value=[0, 0]]()
  %116 : Tensor = onnx::Constant[value=[1, 1]]()
  %117 : Tensor = onnx::Constant[value=1]()
  %new_cnn : Tensor = quantized::conv2d(%input, %112, %113, %114, %115, %116, %117, %219, %218), scope: torch.fx.graph_module.GraphModule::/torch.ao.nn.quantized.modules.conv.Conv2d::newCnn # 
  %squeeze : Tensor = aten::squeeze(%new_cnn, %229), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:23:0
  %transpose : Tensor = aten::transpose(%squeeze, %229, %228), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:24:0
  %82 : Tensor = aten::dequantize(%transpose), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:25:0
  return (%82)

Traceback (most recent call last):
  File "quant2.py", line 261, in <module>
    torch.onnx.export(model_quantized,input,'plate_rec_quant.onnx',
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/utils.py", line 1867, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/symbolic_opset10.py", line 844, in quantized_conv2d_relu
    weight, weight_scale, _, _ = symbolic_helper.dequantize_helper(g, q_weight)
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 1550, in dequantize_helper
    _onnx_opset_unsupported_detailed(
  File "/home/lf/miniconda3/envs/yolov7plate/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 627, in _onnx_opset_unsupported_detailed
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of DequantizeLinear in opset 11. Attribute axis is not supported.. Please try opset version 13.  [Caused by the value '46 defined in (%46 : Tensor = prim::TupleConstruct(%42, %43, %44, %45)
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'prim::TupleConstruct'.] 

    Inputs:
        #0: 42 defined in (%42 : Char(8, 3, 5, 5, strides=[75, 25, 5, 1], device=cpu) = onnx::Constant[value=<Tensor>]()
    )  (type 'Tensor')
        #1: 43 defined in (%43 : Float(8, strides=[1], device=cpu) = onnx::Constant[value=0.001 *  0.7156  0.5953  6.8219  0.5890  0.6383  0.5060  3.6715  1.0147 [ CPUFloatType{8} ]]()
    )  (type 'Tensor')
        #2: 44 defined in (%44 : Int(8, strides=[1], device=cpu) = onnx::Constant[value= 0  0  0  0  0  0  0  0 [ CPUIntType{8} ]]()
    )  (type 'Tensor')
        #3: 45 defined in (%45 : Long(1, strides=[1], device=cpu) = onnx::Constant[value={0}]()
    )  (type 'Tensor')
    Outputs:
        #0: 46 defined in (%46 : Tensor = prim::TupleConstruct(%42, %43, %44, %45)
    )  (type 'Tensor')
```

### Versions

Package                  Version
------------------------ --------------------
absl-py                  1.4.0
cachetools               5.3.0
certifi                  2023.5.7
charset-normalizer       3.1.0
cmake                    3.26.3
coloredlogs              15.0.1
contourpy                1.0.7
cycler                   0.11.0
easydict                 1.10
filelock                 3.12.0
flatbuffers              23.5.9
fonttools                4.39.4
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.18.0
google-auth-oauthlib     1.0.0
grpcio                   1.54.2
humanfriendly            10.0
idna                     3.4
imageio                  2.28.1
importlib-metadata       6.6.0
importlib-resources      5.12.0
Jinja2                   3.1.2
json-tricks              3.15.6
kiwisolver               1.4.4
lit                      16.0.3
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
mdurl                    0.1.2
mpmath                   1.3.0
networkx                 3.1
numpy                    1.23.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
onnx                     1.14.0
onnx-simplifier          0.4.28
onnxruntime              1.14.1
onnxsim                  0.4.28
opencv-python            4.7.0.72
packaging                23.1
pandas                   2.0.1
Pillow                   9.5.0
pip                      23.0.1
protobuf                 3.20.3
psutil                   5.9.5
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycocotools              2.0.6
Pygments                 2.15.1
pyparsing                3.0.9
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
readablePTH              0.1.4
requests                 2.30.0
requests-oauthlib        1.3.1
rich                     13.3.5
rsa                      4.9
scipy                    1.10.1
seaborn                  0.12.2
setuptools               56.1.0
six                      1.16.0
smmap                    5.0.0
sympy                    1.12
tensorboard              2.13.0
tensorboard-data-server  0.7.0
tensorboardX             2.6
thop                     0.1.1.post2209072238
torch                    1.13.0
torchvision              0.14.0
tqdm                     4.65.0
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
ultralytics              8.0.114
urllib3                  1.26.15
Werkzeug                 2.3.4
wheel                    0.38.4
zipp                     3.15.0

**Comment by justinchuby** [comment]
As the error suggested, please use a newer opset version (>13). We recommend 17+

**Comment by omarelejla** [comment]
@justinchuby 
I was using onnx with torch 1.7 and opset 11 it works fine 
after I updated to torch 1.12, it works fine but with number of intermidiate layers less than expected 
also i tried to use opset 17 but it is not supoorted yet for this torch as error raised

**Comment by justinchuby** [comment]
Try torch 2.0? We cannot support an older version of torch.

**Comment by omarelejla** [comment]
what is the opset value should be with torch 2.0

**Comment by justinchuby** [comment]
I suggest opset17

**Comment by omarelejla** [comment]
i used torch 2.0.1 with opset17 and still getting 92 intermidiate layers however i was getting 104 intermidiate layer when i was using torch 1.7 with opset 11
what could be the probem
PS. I did not change the model or sample input

**Comment by justinchuby** [comment]
The exported model is not guaranteed to stay the same between torch versions. The only thing I would look for is whether the output matches

**Comment by steven-spec** [comment]
I encountered the same problem, have you solved it

**Comment by Redreadblack** [comment]
same to me 
Unsupported: ONNX export of DequantizeLinear in opset 11. Attribute axis is not supported
