### ISSUE TITLE
when train with multi GPUS

### ISSUE THREAD

**Issue by cqray1990** [pytorch/pytorch#103955]
### 🐛 Describe the bug

train command:
xport NGPUS=2
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=9531 ./train.py

but when traininf fow a while ,raise errors: what did it  means?

ARNING:torch.distributed.elastic.multiprocessing.api:Sending process 25236 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 25237) of binary: /anaconda3/envs/paddle_env/bin/python
Traceback (most recent call last):
  File "/anaconda3/envs/paddle_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda3/envs/paddle_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

### Versions

pytorch 13.1 cuda 116

**Comment by davidradl** [comment]
@cqray1990  is this a duplicate of https://github.com/pytorch/pytorch/issues/103954 ? If not, I suggest making the titles more descriptive to differentiate.

**Comment by wanchaol** [comment]
Hey @cqray1990, as @davidradl @janeyx99 suggested, please make the issue more descriptive and provide a repro for us to investigate what happened, thanks

**Comment by d4l3k** [comment]
**Category: Stale**

This issue has been automatically closed. Please reopen if this is still an active issue.
