### ISSUE TITLE
torch.save() fails if path contains multibyte characters

### ISSUE THREAD

**Issue by menou310** [pytorch/pytorch#103949]
### 🐛 Describe the bug

After upgrading PyTorch from 1.8.1 (LTS) to 2.0.1.
When saving a model using torch.save(), if the save destination path contains multi-byte characters, saving the model will fail.

Below is the sample code and error message.

Code to reproduce:
```python
import torch

model = torch.load("mnist_cnn.pt")
save_path = model_save.pt
torch.save(model, save_path) # OK

save_path_multibyte = "C:\\Users\\ユーザー名\\source\\model_save_multibyte.pt"        
torch.save(model, save_path_multibyte) # NG
```

The error message:
```
Traceback (most recent call last):
  File ".\sample.py", line 147, in <module>
    main()
  File ".\sample.py", line 142, in main
    torch.save(model, save_path_multibyte)
  File "C:\Users\ユーザー名\source\.venv\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "C:\Users\ユーザー名\source\.venv\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "C:\Users\ユーザー名\source\.venv\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory C:\Users\ユーザー名\source\ does not exist.
```

### Versions

PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: 11.0.1
CMake version: version 3.19.2
Libc version: N/A

Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.0.221
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060 with Max-Q Design
Nvidia driver version: 512.78
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3000
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3000
Name=AMD Ryzen 9 4900HS with Radeon Graphics
ProcessorType=3
Revision=24577

Versions of relevant libraries:
[pip3] numpy==1.19.3
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2+cu118
[conda] Could not collect

cc @mruberry @mikaylagawarecki

**Comment by taras-janea** [comment]
Closing this issue as it is no longer reproducible with the latest PyTorch version. If you continue to experience this problem or have related concerns, please feel free to open a new issue.
