### ISSUE TITLE
Warn/error if importing torch from source directory

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#10391]
We noticed Numpy did this recently:

```
Python 2.7.15 (default, Jun 17 2018, 12:46:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/__init__.py", line 131, in <module>
    raise ImportError(msg)
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

That's nice! We should do this too.

**Comment by ngimel** [comment]
Closing, `torch` can be successfully imported from source directory.
