### ISSUE TITLE
[torch.fx] Deserialization Error - TypeError: ones() received an invalid combination of arguments - got (tuple, device=Attribute) 

### ISSUE THREAD

**Issue by zjc664656505** [pytorch/pytorch#103947]
### 🐛 Describe the bug

Dear Pytorch Community,

Recently, I'm working on my research project and trying to serialize and deserialize the `torch.fx GraphModule object` of `bloom-560m `model.

I used pickle as the package for serialization and deserialization. Initially, I successfully serialized the GraphModule object using `pickle.dump()`.

However, when I try to deserialize the pickle object using `pickle.load`, it shows the error shown below:
```
Traceback (most recent call last):
  File "/Users/junchenzhao/Dist-CPU-Learn/test_inference.py", line 143, in <module>
    obj = pickle.load(file)
  File "/Users/junchenzhao/anaconda3/envs/onnx-training/lib/python3.10/site-packages/torch/fx/graph_module.py", line 109, in reduce_graph_module
    return _deserialize_graph_module(forward, body)
  File "/Users/junchenzhao/anaconda3/envs/onnx-training/lib/python3.10/site-packages/torch/fx/graph_module.py", line 168, in _deserialize_graph_module
    graph = KeepModules().trace(com, **tracer_extras)
  File "/Users/junchenzhao/anaconda3/envs/onnx-training/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "<eval_with_key>.0", line 18, in forward
TypeError: ones() received an invalid combination of arguments - got (tuple, device=Attribute), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

If it's possible, could anyone help me with this issue?

Thanks!

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.10.11 (main, Apr 20 2023, 13:59:00) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2023.1.0         h59209a4_43558  
[conda] mkl-service               2.4.0           py310h6c40b1e_1  
[conda] mkl_fft                   1.3.6           py310h3ea8b11_1  
[conda] mkl_random                1.2.2           py310h3ea8b11_1  
[conda] numpy                     1.24.3          py310h827a554_1  
[conda] numpy-base                1.24.3          py310ha186be2_1  
[conda] pytorch                   2.0.1                  py3.10_0    pytorch
[conda] torchaudio                2.0.2                 py310_cpu    pytorch
[conda] torchvision               0.15.2                py310_cpu    pytorch

**Comment by zjc664656505** [comment]
Is there any help regarding this issue?

**Comment by kurtamohler** [comment]
I briefly looked into fixing this, but I don't know enough about `torch.fx` yet to understand what needs to be done.

However, a temporary workaround could be to replace your function

```python
def test(input_ids):
    size = input_ids.size()
    getitem = size[0]
    getitem_1 = size[1];
    getattr_1 = input_ids.device
    ones = torch.ones((getitem, getitem_1), device=getattr_1)
    return ones
```

with this, or something similar:

```python
def test_workaround(x):
    return torch.ones_like(x.unsqueeze(-1).flatten(2)[:, :, 0])
```

This will return a tensor of ones on the same device as the input and with the shape `(x[0], x[1])`, and it does not raise an error when `symbolic_trace` is run on it. Of course it's not ideal since it creates a few intermediate tensors and is less readable

**Comment by nicolas-dufour** [comment]
Hi, is there any progress here? The propose workaround work only for certain setups
