### ISSUE TITLE
Some V100 inductor unit tests fail with message `Feature '.bf16' requires .target sm_80 or higher`

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#103993]
### 🐛 Describe the bug

Some V100 inductor unit tests fail because of `Feature '.bf16' requires .target sm_80 or higher`

Example stacktrace:
```python
root@5fd4d912c458:/opt/pytorch/pytorch# python test/inductor/test_torchinductor_opinfo.py -v -k TestInductorOpInfoCUDA.test_comprehensive_bfloat16_cuda_float32
test_comprehensive_bfloat16_cuda_float32 (__main__.TestInductorOpInfoCUDA) ... ERROR

======================================================================
ERROR: test_comprehensive_bfloat16_cuda_float32 (__main__.TestInductorOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2205, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 427, in instantiated_test
    raise rte
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 904, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1105, in only_fn
    return fn(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1457, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 941, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 941, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1061, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1026, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/unittest/mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_opinfo.py", line 656, in test_comprehensive
    raise e
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_opinfo.py", line 615, in test_comprehensive
    self.check_model_cuda(
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 410, in check_model_cuda
    check_model(
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 294, in check_model
    actual = run(*example_inputs, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/pytorch/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2027, in run
    super().run()
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2115, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 771, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 867, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 923, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 919, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 286, in compile_fx_wrapper
    return compile_fx(model_, example_inputs_)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 912, in compile_fx
    return aot_autograd(
  File "/opt/pytorch/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 3721, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 3260, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 2070, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 2250, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 2778, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 855, in fw_compiler_base
    return inner_compile(
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 46, in newFunction
    return old_func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 886, in compile_to_fn
    return self.compile_to_module().call
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 861, in compile_to_module
    mod = PyCodeCache.load(code, linemap=linemap)
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 742, in load
    return cls.load_by_key_path(key, path, linemap)
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 757, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/oo/coojmqshso3ewp7zeagxjn6kgcy3xoczrvuvkxske2zaczmcnh6l.py", line 53, in <module>
    async_compile.wait(globals())
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 1028, in wait
    scope[key] = result.result()
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 887, in result
    self.future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
RuntimeError: Internal Triton PTX codegen error:
ptxas /tmp/compile-ptx-src-dbbe2f, line 28; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-dbbe2f, line 28; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas fatal   : Ptx assembly aborted due to errors



You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


----------------------------------------------------------------------
Ran 1 test in 3.735s

FAILED (errors=1)
```

Some other similar failed jobs:

```bash
TestInductorOpInfoCUDA.test_comprehensive_bfloat16_cuda_{bool, float16, float32, float64, int32, int64}

python test/inductor/test_torchinductor_dynamic_shapes.py -v -k DynamicShapesCudaTests.test_remove_no_ops_dynamic_shapes_cuda

python test/inductor/test_torchinductor_codegen_dynamic_shapes.py -v -k DynamicShapesCodegenCudaTests.test_remove_no_ops_dynamic_shapes_cuda

python test/inductor/test_torchinductor.py -v -k CudaTests.test_remove_no_ops_cuda

```

### Versions

V100

cuda 12.1

triton https://github.com/openai/triton/commit/440fd1bf20697b0961ddb0822de86d151c58dd36
torch_commit: https://github.com/pytorch/pytorch/commit/d4b85f3031b81ea9f0e53502ad3b831fb91ec39b

cc @ptrblck @mruberry @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @malfet

**Comment by xwang233** [comment]
I think skipping those tests is a good idea. I'm not sure how similar tests were handled. If similar BF16 tests were skipped, we should skip those tests on sm_70 as well.

**Comment by malfet** [comment]
Looks like it's just a matter of adding `@unittest.skipIf(not SM80OrLater)` to the appropriate opinfo
cc: @ptrblck

**Comment by ptrblck** [comment]
CC @Fuzzkatt could you create a fix for it as it seems to be indeed a one-liner to disable these tests on pre-Ampere GPUs?

**Comment by Fuzzkatt** [comment]
Made fix PR here: https://github.com/pytorch/pytorch/pull/104436
