### ISSUE TITLE
[ppc64le pytorch] SIGSEGV  on test_matmul_4d_1d

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#10403]
PyTorch version   torch (0.5.0a0+e9ad743)

OMP_NUM_THREADS=4

test_matmul_4d_1d (__main__.TestAutograd) ... Traceback (most recent call last):
  File "run_test.py", line 368, in <module>
    main()
  File "run_test.py", line 360, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed! Received signal: SIGSEGV

here is the trace : 

Core was generated by `python test_autograd.py --verbose '.
Program terminated with signal 11, Segmentation fault.
#0  0x00003fff76411cf0 in dgemm_beta () from /usr/lib64/libopenblas.so.0
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.ppc64le elfutils-libelf-0.170-4.el7.ppc64le elfutils-libs-0.170-4.el7.ppc64le glibc-2.17-222.el7.ppc64le libattr-2.4.46-13.el7.ppc64le libcap-2.22-9.el7.ppc64le libgfortran-4.8.5-28.el7_5.1.ppc64le openblas-0.3.0-1.el7.ppc64le systemd-libs-219-57.el7.ppc64le
(gdb) bt
#0  0x00003fff76411cf0 in dgemm_beta () from /usr/lib64/libopenblas.so.0
(gdb) bt
#0  0x00003fff76411cf0 in dgemm_beta () from /usr/lib64/libopenblas.so.0

If I run the unittest by itself , it passes.
If I run the unittest in a for loop it passes mostly but randomly fails with SEGV 

I saw #9586,  but in my case this unittest seems to pass just fine , even in a for loop

I tried to use a couple of  libopenblas.so versions but same result
RH 7.5  
openblas-devel-0.3.0-1.el7.ppc64le
and 
libopenblas-0.2.20-2596.dd38835.ppc64le

I also tried setting :  OMP_NUM_THREADS=1  and still fails

**Comment by avmgithub** [comment]
I'm closing this.  It looks like this was a problem with the OpenMPI that I custom built.  I am now using OpenMPI  version 2.1.4  with the --enable-mpi-thread-multiple  flag.  And the problem seemed to have disappeared.   We'll try to re-test with versions 3.x to make sure they work.
