### ISSUE TITLE
[torch.compile] torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method normal of type object at ***: got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#104047]
### 🐛 Describe the bug

My repro

```
from torch import _dynamo as dyna

def func():
    return torch.normal(1, 1, (8,8))

op = dyna.optimize('eager')(func)
a = func() # this runs fine
a = op() # this fails
```

Stacktrace:
```
[2023-06-22 10:17:33,958] torch._subclasses.fake_tensor: [ERROR] fake tensor raised TypeError
Traceback (most recent call last):
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1161, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1381, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 392, in constructors
    r = func(*args, **new_kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_ops.py", line 429, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 227, in _fn
    result = fn(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 110, in _fn
    bound = sig.bind(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/inspect.py", line 3026, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'device'
Traceback (most recent call last):
  File "examples/wip.py", line 14, in <module>
    a = op()
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 526, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2026, in run
    super().run()
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 390, in wrapper
    return inner_fn(self, inst)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 610, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1115, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1151, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1313, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1281, in get_fake_value
    return wrap_fake_exception(
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 871, in wrap_fake_exception
    return fn()
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1282, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1347, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1334, in run_node
    return node.target(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1161, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1381, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 392, in constructors
    r = func(*args, **new_kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_ops.py", line 429, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 227, in _fn
    result = fn(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 110, in _fn
    bound = sig.bind(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/home/yshi/miniconda3/envs/dyn/lib/python3.8/inspect.py", line 3026, in _bind
    raise TypeError(
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method normal of type object at 0x7f4ea1a5a100>(*(1, 1, (8, 8)), **{}):
got an unexpected keyword argument 'device'
```

Looks like a fake tensor mode issue with this specific op that some keyword args are not recognized correctly.

### Versions

PyTorch version: 2.1.0.dev20230621+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 10.4.0-4ubuntu1~22.04) 10.4.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.16 (default, Jun 12 2023, 18:09:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-45-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     4950.1948
CPU min MHz:                     2200.0000
BogoMIPS:                        7399.95
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        6 MiB (12 instances)
L3 cache:                        64 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230621+cu118
[pip3] torchaudio==2.1.0.dev20230621+cu118
[pip3] torchvision==0.16.0.dev20230621+cu118
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
[conda] torch                     2.1.0.dev20230621+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230621+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230621+cu118          pypi_0    pypi

cc @pbelevich @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @SherlockNoMad @mruberry @Lezcano @peterbell10 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ipiszy

**Comment by jbschlosser** [comment]
Interesting, `torch.normal` is a factory function that doesn't accept the typical `device`, etc. args.

As a workaround, you can use `torch.randn(...) * sigma + mu` to generate normally-distributed samples beyond standard normal.

**Comment by mlazos** [comment]
This no longer fails
