### ISSUE TITLE
Several Torchbench models don't run with float16 or bfloat16 in the inference eager mode

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#104010]
Repro:
Apply the following patch,
```
diff --git a/benchmarks/dynamo/torchbench.py b/benchmarks/dynamo/torchbench.py
index 30406d5345d..6161f02690c 100755
--- a/benchmarks/dynamo/torchbench.py
+++ b/benchmarks/dynamo/torchbench.py
@@ -213,7 +213,7 @@ MAX_BATCH_SIZE_FOR_ACCURACY_CHECK = {
 FORCE_AMP_FOR_FP16_BF16_MODELS = {
     "doctr_det_predictor",
     "doctr_reco_predictor",
-    "Super_SloMo",
+    #"Super_SloMo",
     "tts_angular",
 }
```
and then run
```
benchmarks/dynamo/torchbench.py --inductor --bfloat16 --accuracy --inference --device cuda  --only Super_SloMo
```

Error:
```
Eager model failed to run
Traceback (most recent call last):
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/common.py", line 1320, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/torchbench.py", line 436, in forward_pass
    return mod(*inputs)
  File "/scratch/binbao/work/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/binbao/work/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/binbao/work/torchbench/torchbenchmark/models/Super_SloMo/model_wrapper.py", line 41, in forward
    g_I0_F_t_0 = self.trainFlowBackWarp(I0, F_t_0)
  File "/scratch/binbao/work/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/binbao/work/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/binbao/work/torchbench/torchbenchmark/models/Super_SloMo/slomo_model.py", line 286, in forward
    imgOut = torch.nn.functional.grid_sample(img, grid)
  File "/scratch/binbao/work/pytorch/torch/nn/functional.py", line 4295, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: "grid_sampler_2d_cuda" not implemented for 'BFloat16'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/common.py", line 2672, in run
    ) = runner.load_model(
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/torchbench.py", line 384, in load_model
    self.validate_model(model, example_inputs)
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/common.py", line 1322, in validate_model
    raise NotImplementedError("Eager model failed to run") from e
NotImplementedError: Eager model failed to run

WARNING:root:Super_SloMo failed to load
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
We need to make a policy decision here.

Some of these models simply never worked with bfloat16. In Super_SloMo's case, it is because it uses some operators that don't have bfloat16 implementations.

We could add bfloat16 implementations for these ops. But it's not clear to me that this is the right thing to do. If no one has ever done inference on this model in bfloat16, we shouldn't run our benchmark with it! Does that mean we should run the benchmark in float32? Or drop it entirely? Choices, choices...

**Comment by wconstab** [comment]
i don't think we should be trying to enable new ops support just to 'fill in the matrix' of dtype benchmarks.  We should probably come up with a flexible solution.  Maybe we need a csv that keeps ground truth of what dtype(s) we run each benchmark in, and maybe we can either (a) pick one dtype per model to keep it simple, or (b) do a scan of the models to see what they support and then lock those in

**Comment by desertfire** [comment]
Right now I group them as a list here https://github.com/pytorch/pytorch/blob/afc788a99c1853e815283854ef6f168b250eaf2c/benchmarks/dynamo/torchbench.py#L213C1-L213C1, and force them to fall back to AMP. Based on the discussions here, feel like it's sufficient for now.
