### ISSUE TITLE
Documentation building bug

### ISSUE THREAD

**Issue by osbm** [pytorch/pytorch#104113]
### 🐛 Describe the bug

I am trying to build the documentation locally, but i keep getting this error:
```
$ make html
```
output:
```
Traceback (most recent call last):
  File "/home/osman/Documents/temp/pytorch/docs/source/scripts/build_opsets.py", line 74, in <module>
    main()
  File "/home/osman/Documents/temp/pytorch/docs/source/scripts/build_opsets.py", line 57, in main
    aten_ops_list = get_aten()
  File "/home/osman/Documents/temp/pytorch/docs/source/scripts/build_opsets.py", line 19, in get_aten
    parsed_yaml = parse_native_yaml(NATIVE_FUNCTION_YAML_PATH, TAGS_YAML_PATH)
  File "/home/osman/Documents/temp/pytorch/docs/.venv/lib/python3.10/site-packages/torchgen/gen.py", line 235, in parse_native_yaml
    _GLOBAL_PARSE_NATIVE_YAML_CACHE[path] = parse_native_yaml_struct(
  File "/home/osman/Documents/temp/pytorch/docs/.venv/lib/python3.10/site-packages/torchgen/gen.py", line 167, in parse_native_yaml_struct
    error_check_native_functions(rs)
  File "/home/osman/Documents/temp/pytorch/docs/.venv/lib/python3.10/site-packages/torchgen/gen.py", line 277, in error_check_native_functions
    assert len(base_func_map[out_of_place_base_name]) > 0, (
AssertionError: resize_as_ is marked with tag: inplace_view. The codegen expects there to be a corresponding out-of-place view op with the name 'resize_as_' and matching schema, but it didn't find one. 
make: *** [Makefile:25: opset] Error 1
```

None of the `make` options I am interested in were compiling, it all gave the same error above.

I have installed the python requirements and katex inside a new virtual environment.

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 13.1.1 20230429
Clang version: 15.0.7
CMake version: version 3.26.4
Libc version: glibc-2.37

Python version: 3.10.11 (main, Jun 23 2023, 17:06:29) [GCC 13.1.1 20230429] (64-bit runtime)
Python platform: Linux-6.1.31-2-MANJARO-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce MX250
Nvidia driver version: 530.41.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
CPU family:                      6
Model:                           126
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        5
CPU(s) scaling MHz:              57%
CPU max MHz:                     3900,0000
CPU min MHz:                     400,0000
BogoMIPS:                        2996,00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        2 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.0.1
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by osbm** [comment]
It does work in the v2.0.1 branch.

```
git checkout v2.0.1
```

**Comment by davidradl** [comment]
I was looking at this in the duplicate issue i closed. I found that if the latest code for gen.py was picked up then the  "resize_as_" condition would prevent this issue. 

```
    if (
            "inplace_view" in f.tags
            and str(f.func.name) != "resize_"
            and str(f.func.name) != "resize_as_"
        ): 
```

In my case it was picking up older code from miniconda3 that did not have the "resize_as_" check. My guess is that this worked in the past because there was no mismatch between the older and newer code. The cause appears to be that the local (latest)  code is not being picked up for gen.py. 

How torch local code is picked up , is the egg_links which end up in the easy install path .
 
In my miniconda3 site-packages  I see:

```
	torch-2.0.1-py3.10.egg-info
	torch.egg-link
	torchgen
	torchvision
	torchvision-0.15.2-py3.10.egg-info 

```
I notice  torchgen does not have an egg-info.

My easy-install path has 
```
/easy-install.pth
/Users/davidradley/pytorch
/Users/davidradley/pytorch/docs/src/pytorch-sphinx-theme
```
I notice 
miniconda3/lib/python3.10/site-packages/torch-2.0.1-py3.10.egg-info/top_level.txt
```
contains
functorch
torch
torchgen
```

I hope this information is helpful.

**Comment by malfet** [comment]
@davidradl you can look at https://github.com/pytorch/pytorch/pull/104214 as an example I.e. probably in `gen.py` one should add something like `sys.path.insert(0, os.path.dirname(__file__))` to force all `import tools` to pick one installed locally.

**Comment by davidradl** [comment]
I have found a circumvention. I ran `pip install --editable .` in the root folder. `make html` does run successfully after a couple of fails.I am not happy to add this to the docs as-is as I am getting errors.

I am cleaning my environment and investigating @malfet. I think a line to say `if development then sys.path.insert(0, os.path.dirname(__file__))` could work. This should get it going but it would be better to drive the setup so it sets up the link properly for torchgen.

**Comment by davidradl** [comment]
Hi @malfet, I appreciate your feedback :-) .  I forced the local folder to be first in the path in the setup.py prior to the setup command being run; this had no effect. I do not think that updating gen.py helps, as it is running the wrong gen.py (i.e. not my local git pytorch fork) . 

I tried forcing my my local git pytorch fork to be first in the path prior to running the make, but the make does not honour this. pypath is not set to anything in my environment. 

I have started `https://github.com/pypa/setuptools/discussions/3968`; in case they give me any insights.

**Comment by gregsadetsky** [comment]
Hey, just curious if this was resolved? I'm still getting the same error when attempting to build the docs locally (this is happening on the latest commit, 8fb6416bfa403d25df1c32846e71b31b79fc88d5). Thanks!

**Comment by lferreiraMD** [comment]
I'm also getting the same error with the current PyTorch version. `torchgen` remains the culprit.
