### ISSUE TITLE
AttributeError: 'torch.Size' object has no attribute 'shape'

### ISSUE THREAD

**Issue by jatinS-dev** [pytorch/pytorch#104153]
### 🐛 Describe the bug

**Link**  -  [https://github.com/LCS2-IIITD/MAF/blob/main/Code/Trimodal-BART-driver.py](url)

**Description**  
While running the given file, it is giving the following error - 
``` Traceback (most recent call last):
  File "/mnt/Data/akashghosh/MDS/MDS_T.py", line 1122, in <module>
    train(model=MODEL,
  File "/mnt/Data/akashghosh/MDS/MDS_T.py", line 778, in train
    train_loss, train_acc = train_epoch(model,
  File "/mnt/Data/akashghosh/MDS/MDS_T.py", line 1012, in train_epoch
    outputs , logits = model(input_ids=input_ids,
  File "/mnt/Data/akashghosh/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/Data/akashghosh/MDS/MDS_T.py", line 274, in forward
    outputs = self.model(
  File "/mnt/Data/akashghosh/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/Data/akashghosh/MDS/MDS_T.py", line 446, in forward
    encoder_outputs = self.encoder(
  File "/mnt/Data/akashghosh/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/Data/akashghosh/MDS/MDS_T.py", line 601, in forward
    embed_pos = self.embed_positions(input_shape)
  File "/mnt/Data/akashghosh/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/Data/akashghosh/anaconda3/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 135, in forward
    bsz, seq_len = input_ids.shape[:2]

AttributeError: 'torch.Size' object has no attribute 'shape'

### Versions

**Versions -** 

(base) akashghosh@iit-p:~/MDS$ pip list | grep torch
torch             -->             2.0.1
torchmetrics        -->           0.11.4
torchvision       -->             0.15.2

**Comment by malfet** [comment]
Closing, as it does not sound like a PyTorch problem. Please feel free to use https://discuss.pytorch.org to ask generic question about how PyTorch should be used. 
If you believe that it is the problem of PyTorch, please spent some time to narrow it down small reproducible example that returns incorrect/unexpected value and than do not hesitate to submit a new issue.
