### ISSUE TITLE
Inductor dynamic shapes output: NameError: name 's2' is not defined

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#104102]
### 🐛 Describe the bug

Repro script:

```

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
import torch._inductor.inductor_prims

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config

torch._inductor.config.fallback_random = True
torch._inductor.config.generate_intermediate_hooks = True
torch._inductor.config.triton.cudagraphs = True



isolate_fails_code_str = None



# torch version: 2.1.0a0+git2232cce
# torch cuda version: 12.0
# torch git version: 2232cce69c450db3163751e9238e1f34a6a2477e


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2023 NVIDIA Corporation 
# Built on Fri_Jan__6_16:45:21_PST_2023 
# Cuda compilation tools, release 12.0, V12.0.140 
# Build cuda_12.0.r12.0/compiler.32267302_0 

# GPU Hardware Info: 
# NVIDIA PG509-210 : 8 


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, arg5_1):
        sym_size = torch.ops.aten.sym_size(arg5_1, 2);  arg5_1 = None
        mul_2 = 1024 * sym_size;  sym_size = None
        return (mul_2,)
        
def load_args(reader):
    buf0 = reader.storage('d5d3fbeeaccb2bf4d8e4ba44de52bd663bfe4e41', 1572864, device=device(type='cuda', index=0), dtype_hint=torch.float16)
    reader.tensor(buf0, (4, 256, 24, 32), dtype=torch.float16, is_leaf=True)  # arg5_1
load_args._version = 0
mod = Repro()
if __name__ == '__main__':
    from torch._dynamo.repro.after_aot import run_repro
    run_repro(mod, load_args, accuracy=False, command='run', save_dir='/data/users/ezyang/b/pytorch/torch_compile_debug/run_2023_06_23_06_17_09_326738-pid_4066193/minifier/checkpoints', tracing_mode='real')
```

Run with `python repro.py run --tracing-mode=symbolic`

Fails with

```
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/repro.py", line 58, in <module>
    run_repro(mod, load_args, accuracy=False, command='run', save_dir='/data/users/ezyang/b/pytorch/torch_compile_debug/run_2023_06_23_06_17_09_326738-pid_4066193/minifier/checkpoints', tracing_mode='real')
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/repro/after_aot.py", line 908, in run_repro
    COMMAND_FNS[options.command](options, mod, load_args)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/repro/after_aot.py", line 696, in repro_run
    ref = compiled(args)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codecache.py", line 313, in __call__
    return self.get_current_callable()(inputs)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/compile_fx.py", line 510, in run
    return old_compiled_artifact(new_inputs)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 359, in deferred_cudagraphify
    fn, out = cudagraphify(model, inputs, static_input_idxs, *args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 383, in cudagraphify
    return manager.add_function(
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 1853, in add_function
    return fn, fn(inputs)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 1673, in run
    out = self._run(new_inputs, function_id)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 1714, in _run
    return self.run_eager(new_inputs, function_id)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 1829, in run_eager
    return node.run(new_inputs)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/cudagraph_trees.py", line 571, in run
    out = self.wrapped_function.model(new_inputs)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codecache.py", line 340, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_ezyang/tz/ctzcpl3bpwtj5hhfuecve6mdgpbgkxmuazrhludfbutwb6oxbu6t.py", line 28, in call
    return (1024*s2, )
NameError: name 's2' is not defined
```

Generated code is

```

from ctypes import c_void_p, c_long
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile

from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (4, 256, 24, 32), (196608, 768, 32, 1))
    return (1024*s2, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((4, 256, 24, 32), (196608, 768, 32, 1), device='cuda:0', dtype=torch.float16)
    return print_performance(lambda: call([arg0_1]), times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.utils import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)
```

Repro was extracted from yolov3 although... it's not the actual bug I was trying to hit LOL.

### Versions

main

**Comment by lezcano** [comment]
go for it

**Comment by andvvo** [comment]
I'm working on this.

**Comment by ezyang** [comment]
It's possible some variation on https://github.com/pytorch/pytorch/pull/109893 or https://github.com/pytorch/pytorch/pull/110195 will be enough to fix it, although I think some adaptation will be neded

**Comment by andvvo** [comment]
@ezyang I really want to solve this issue and make my first contribution. I've looked through [#109893](https://github.com/pytorch/pytorch/pull/109893), [#110195](https://github.com/pytorch/pytorch/pull/110195), and the `_inductor` module, but I haven't been able to pin point where start. Some questions I have are:

- Where would I define `s2`
- What value should `s2` be

Any help would be appreciated!

**Comment by bmantoni** [comment]
I'm interested in working on this too. I see that the issue is that inductor generates Triton code that includes a reference to undefined s2. It must be tricked by the fact that sym_size is reassigned to None after the expression is declared.

I wrote a unit test based on one of those MRs to try to reproduce, but it works. Is this the right technique?

```
    @torch._dynamo.config.patch(capture_dynamic_output_shape_ops=True)
    def test_undefined_output_param(self, device):
        def f(arg5_1):
            sym_size = torch.ops.aten.sym_size(arg5_1, 2);  arg5_1 = None
            mul_2 = 1024 * sym_size;  sym_size = None
            return (mul_2,)

        opt_f = torch.compile(f, fullgraph=True)
        #x = torch.randn(5, device=device)
        x = torch.rand((4, 256, 24, 32))
        r = f(x)
        opt_r = opt_f(x)
        self.assertEqual(r, opt_r)
```

I am able to reproduce by running the repro script, so the issue is still present.
What is the expected behavior?

**Comment by bmantoni** [comment]
Still trying to figure this out. Pretty tough for a "good first issue"

I see that in interpreter.py:run(), it goes through 2 phases of calls: 4 for the CPU target generation and 4 for the CUDA generation.
In each, run() is invoked 4 times:
1. For arg0_1 (the input tensor)
2. For the `call_function` to `sym_size`, the result of which is 24 and gets put into `%sym_size`
3. For the `call_function` to `mul` 
4. For the output

In the CPU phase, call 3 sets self.env to `{sym_size: 24, mul: 24576}` and in the CUDA phase, call 3 sets self.env to `{sym_size: 24, mul: 1024 * s2}`

So that's where the problem seems to emerge. Rather than simply doing the multiplication (it seems to have the arguments to do so, since in `graph.py:run_node, args == (1024, 24)`), mul returns a result of `1024 * s2` but s2 is never given a value.

Before all that, there is a bunch of stuff happening in symbolic_shapes, under the call to _pytree.tree_map, where calls to `create_symintnode` take place. I *think* this is where the variable `s2` gets created.

At `graph.py:run_node():758`, `result = n.meta["val"].node.expr` assigns `1024*s2` to result. Is the problem before this assignment (where `result = n.meta["val"].node.expr` gets its value? I suspect the answer is No, because in the CPU run node.expr also has this same value.

Or is the problem earlier in that s2 should be added to env with value 24? Or is the problem after mul is run?

Or is the problem earlier still, under the call to tree_map where the SymInts are instantiated?

If anyone has a suggestion it'd be appreciated

**Comment by ezyang** [comment]
This is probably a problem in torch/_inductor/scheduler.py

**Comment by ezyang** [comment]
@bmantoni OK, so it turns out, this is operator error, but there IS still a bug to fix, just not where you expect.

The reason s2 doesn't exist in the generated Triton code, is we actually have an invariant that all SymInts must actually be arguments to what we pass to torch.compile. This is why your direct torch.compile example did not work; in that case, the invariant was upheld. But in the minified example, we've actually deleted the SymInt argument, so of course it's not going to work. There are two things to do here:

1. Beef up assertions in Inductor to verify that this invariant is upheld on input GraphModules that are passed in. Something like, iterate over all the inputs looking at free_symbols, and check those symbols are bound
2. Make the minimizer not remove symbolic int inputs when tracing. This is tricky, because this was only a problem because we were using tracing_mode symbolic. Not exactly sure how to do it.

**Comment by bmantoni** [comment]
Ahhh, thanks for the clues @ezyang ! I suspected that the MRs referenced above weren't actually relevant so this is great help to confirm where to look. 
This is making sense. I see the difference with the SymInt (`arg5_1`) argument in the original vs my test case vs the generated.  

So if I go with option 1, you'd expect this situation to throw an (earlier) error?
I'll start with 1 and see if I can figure out 2.

**Comment by ezyang** [comment]
yeah (1) sounds good

**Comment by bmantoni** [comment]
Hi @ezyang , I could use another hint or confirmation I'm on the right track.

I'm looking at `compile_fx_inner`, around where it sets up `cudagraph_tests` to add this check (is that the right timing? Or earlier, or later?)

If I assume `list(gm.graph.nodes)[0:len(example_inputs)]` gives me the input nodes (which is len==1 in the example), and [-1] is the output, then (between the two) I have the SymInts we're looking for. And assuming I use the sympy objects to get to `free_symbols`:

```
[x.meta["val"].node.expr.free_symbols for x in list(gm.graph.nodes)[len(example_inputs):-1] if type(x.meta["val"]) == torch.SymInt] 
```
Gives me `[{s2}, {s2}]`. `s2` being the free symbol causing the issue. 

Assuming that's on the right track, I cannot see how to "check those symbols are bound". I don't see anything in the sympy objects to indicate whether they're bound or not. I still can't quite tell how the input_examples are mapped into these symbols at execution time, other than positionally? 

So:
1. Is this a reasonable place to add the check?
2. Am I correctly getting to free_symbols?
3. How to tell whether s2 is bound?

Thanks!

**Comment by bmantoni** [comment]
OK @ezyang , this is probably way off but I'm throwing it against the wall:

```
def check_for_unbound_symints(
        gm: torch.fx.GraphModule,
        example_inputs: List[torch.Tensor]):
    fs = [x.meta["val"].node.expr.free_symbols for x in list(gm.graph.nodes)[len(example_inputs):-1] if "val" in x.meta and type(x.meta["val"]) == torch.SymInt]
    fs = {e for f in fs for e in f} # flatten/join sets
    fs = {e.name for e in fs}
    inputs = [i.name for i in list(gm.graph.nodes)[0:len(example_inputs)]]

    assert all(f in inputs for f in fs), "unbound free SymInt"
```

It is based on the assumptions above: (1) that I should identify free_symbols through the sympy objects accessed through gm.graph.nodes, and (2) that I should determine whether each is bound by checking if it is passed into the module as an input (by name). That does catch the problematic example, but it also fails many existing tests, such as this one: 

```
    def test_addr_alpha_beta_out(self):
        inp = torch.randn(2, 3)
        vec1 = torch.randn(2)
        vec2 = torch.randn(3)
        alpha = 2
        beta = 5

        out = torch.zeros(2, 3)
        compile_out = torch.zeros(2, 3)

        torch.addr(inp, vec1, vec2, alpha=alpha, beta=beta, out=out)
        compiled_fn = torch.compile(torch.addr, dynamic=True)
        compiled_fn(inp, vec1, vec2, alpha=alpha, beta=beta, out=compile_out)
        self.assertTrue(same(out, compile_out))
```

In this case, my free_symbols comes back as: `s0, s1`
And the inputs show as: `arg0_1, ..., arg7_1`

So that doesn't line up with the assumptions. Is this at all in the right ball park?

**Comment by ezyang** [comment]
Oh, this is probably pretty close. Instead of using the name of the input, you should read the symbol name directly off of meta.
