### ISSUE TITLE
NestedTensor cannot be pickled

### ISSUE THREAD

**Issue by vkovac2** [pytorch/pytorch#104198]
```python
import torch
import pickle

a, b = torch.arange(3), torch.arange(5) + 3
nt = torch.nested.nested_tensor([a, b])
with open('tensor.pkl', 'wb') as f:
    pickle.dump(nt, f)
```

<details>

<summary>
click to see original report
</summary>

### 🚀 The feature, motivation and pitch

Hello,

I am trying to make a custom dataset class of ZINC dataset on PyTorch geometric with nested tensors using "torch.nested.nested_tensor", and when executing I got the following error: 

"Internal error: NestedTensorImpl doesn't support sizes."

Is there a way to get the of the different tensors in the nested tensor? 

Thanks

</details>

cc @mruberry @mikaylagawarecki @cpuhrsch @jbschlosser @bhosmer @drisspg

**Comment by davidradl** [comment]
I suggest submitting a self contained minimal piece of code that can be used to recreate the issue.

**Comment by davidradl** [comment]
I am not sure what others think - should this issue be moved to https://github.com/pyg-team/pytorch_geometric/issues or maybe to the forum as question.

**Comment by soulitzer** [comment]
Does this work for you?
```
import torch
a = torch.tensor([1., 2., 3.])
b = torch.tensor([1., 2., 3., 4.])
c = torch.nested.nested_tensor([a, b])
print(c[0].size())  # 3
print(c[1].size())  # 4
```

**Comment by vkovac2** [comment]
Hello. I accidentally wrote the answer of this issue to another one #https://github.com/pytorch/pytorch/issues/104163#issuecomment-1611775696. 
I am copying and pasting it here so it is more relevant 



```py

import torch
from torch_geometric.data import Data
from torch_geometric.transforms import BaseTransform
from typing import Any
from torch_geometric.transforms import Compose
from torch_geometric.datasets import ZINC, QM9
from torch_geometric.loader import DataLoader

class customData(Data):

    @classmethod
    def take_feat(cls, data: Data):

        relations = {0:[2, 7, 6, 5, 4, 3], 1:[2, 5, 4, 3], 2:[2, 3, 4, 5, 1]}
        data["relations"] = torch.nested.nested_tensor(list(relations.values()))
        return data
    def __cat_dim__(self, key: str, value: Any, *args, **kwargs) -> Any:
        if 'edge_index' in key:
            return 1
        else:
            return 0
        
    def __inc__(self, key: str, value: Any, *args, **kwargs) -> Any:
        if 'edge_index' in key:
            return torch.tensor([[getattr(self, 'x').size(0)], [getattr(self, 'x').size(0)]])
        if 'relation' in key:
            return getattr(self, 'x').size(0)
        else:
            return super().__inc__(key, value, *args, **kwargs)

class customTransformations(BaseTransform):
    def __call__(self, data: Data):
        
        new_data = customData.take_feat(data)
        return new_data


data_train = ZINC("datasets/custom_zinc3", subset=True, split='train',
                    pre_transform=Compose([customTransformations()]), transform=Compose([]))  

train_loader = DataLoader(data_train, batch_size=128)
```


Error that I got: "Exception has occurred: RuntimeError
Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
  File "/Users/try_zinc.py", line 44, in <module>
    data_train = ZINC("datasets/custom_zinc3", subset=True, split='train',"
    

Any suggestions to overcome this issue? Thanks

**Comment by soulitzer** [comment]
@vkovac2 Could you run it again with `TORCH_SHOW_CPP_STACKTRACES=1` and paste that stack trace here? 
That would help us pinpoint where better nested tensor support is needed.

**Comment by vkovac2** [comment]
Hey @soulitzer. You can find the stack trace below. Hope it helps. Thanks a lot

```
Exception has occurred: RuntimeError
Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
Exception raised from sym_sizes_custom at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1682343686209/work/aten/src/ATen/NestedTensorImpl.cpp:285 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 81 (0x10a5603a1 in libc10.dylib)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 197 (0x10a55eb75 in libc10.dylib)
frame #2: at::native::NestedTensorImpl::sym_sizes_custom() const + 35 (0x130fbc393 in libtorch_cpu.dylib)
frame #3: THPSize_NewFromSymSizes(at::Tensor const&) + 673 (0x10f43e371 in libtorch_python.dylib)
frame #4: torch::autograd::THPVariable_size(_object*, _object*, _object*) + 472 (0x10efda3f8 in libtorch_python.dylib)
frame #5: cfunction_call + 52 (0x1006a40f4 in python3.9)
frame #6: _PyObject_MakeTpCall + 321 (0x100647721 in python3.9)
frame #7: trace_call_function + 564 (0x10077fdc4 in python3.9)
frame #8: _PyEval_EvalFrameDefault + 158629 (0x10077b1e5 in python3.9)
frame #9: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #10: _PyFunction_Vectorcall + 420 (0x1006491a4 in python3.9)
frame #11: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #12: _PyEval_EvalFrameDefault + 158629 (0x10077b1e5 in python3.9)
frame #13: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #14: _PyFunction_Vectorcall + 420 (0x1006491a4 in python3.9)
frame #15: method_vectorcall + 158 (0x10064e6fe in python3.9)
frame #16: _Pickle_FastCall + 97 (0x109c41cf1 in _pickle.cpython-39-darwin.so)
frame #17: save + 1945 (0x109c446d9 in _pickle.cpython-39-darwin.so)
frame #18: save + 6682 (0x109c4595a in _pickle.cpython-39-darwin.so)
frame #19: save + 6682 (0x109c4595a in _pickle.cpython-39-darwin.so)
frame #20: save_reduce + 879 (0x109c48cff in _pickle.cpython-39-darwin.so)
frame #21: save + 2005 (0x109c44715 in _pickle.cpython-39-darwin.so)
frame #22: save + 6682 (0x109c4595a in _pickle.cpython-39-darwin.so)
frame #23: save_reduce + 879 (0x109c48cff in _pickle.cpython-39-darwin.so)
frame #24: save + 2005 (0x109c44715 in _pickle.cpython-39-darwin.so)
frame #25: save + 1309 (0x109c4445d in _pickle.cpython-39-darwin.so)
frame #26: dump + 201 (0x109c43bc9 in _pickle.cpython-39-darwin.so)
frame #27: _pickle_Pickler_dump + 104 (0x109c43868 in _pickle.cpython-39-darwin.so)
frame #28: cfunction_vectorcall_O + 113 (0x1006a4b21 in python3.9)
frame #29: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #30: trace_call_function + 564 (0x10077fdc4 in python3.9)
frame #31: _PyEval_EvalFrameDefault + 158629 (0x10077b1e5 in python3.9)
frame #32: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #33: _PyFunction_Vectorcall + 1260 (0x1006494ec in python3.9)
frame #34: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #35: _PyEval_EvalFrameDefault + 156529 (0x10077a9b1 in python3.9)
frame #36: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #37: _PyFunction_Vectorcall + 1260 (0x1006494ec in python3.9)
frame #38: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #39: _PyEval_EvalFrameDefault + 163514 (0x10077c4fa in python3.9)
frame #40: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #41: _PyFunction_Vectorcall + 420 (0x1006491a4 in python3.9)
frame #42: method_vectorcall + 158 (0x10064e6fe in python3.9)
frame #43: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #44: _PyEval_EvalFrameDefault + 163514 (0x10077c4fa in python3.9)
frame #45: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #46: _PyFunction_Vectorcall + 420 (0x1006491a4 in python3.9)
frame #47: method_vectorcall + 158 (0x10064e6fe in python3.9)
frame #48: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #49: _PyEval_EvalFrameDefault + 163514 (0x10077c4fa in python3.9)
frame #50: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #51: _PyFunction_Vectorcall + 1260 (0x1006494ec in python3.9)
frame #52: method_vectorcall + 158 (0x10064e6fe in python3.9)
frame #53: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #54: _PyEval_EvalFrameDefault + 163514 (0x10077c4fa in python3.9)
frame #55: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #56: _PyFunction_Vectorcall + 1260 (0x1006494ec in python3.9)
frame #57: method_vectorcall + 158 (0x10064e6fe in python3.9)
frame #58: PyObject_Vectorcall.4404 + 71 (0x10077ff17 in python3.9)
frame #59: _PyEval_EvalFrameDefault + 163514 (0x10077c4fa in python3.9)
frame #60: __pyx_f_18_pydevd_frame_eval_22pydevd_frame_evaluator_get_bytecode_while_frame_eval_39 + 5212 (0x10a42133c in pydevd_frame_evaluator.cpython-39-d)
frame #61: _PyFunction_Vectorcall + 1260 (0x1006494ec in python3.9)
frame #62: slot_tp_init + 548 (0x1006cf9a4 in python3.9)
frame #63: type_call + 272 (0x1006d4e70 in python3.9)
  File "/Users/try_zinc.py", line 47, in <module>
    data_train = ZINC("datasets/custom_zinc3", subset=True, split='train',
```

**Comment by vkovac2** [comment]
Hello again @soulitzer . I am still having the same issue. Do you mind checking? Thanks a lot


```py

from typing import Any

import torch

from torch_geometric.data import Data
from torch_geometric.datasets import QM9, ZINC
from torch_geometric.loader import DataLoader
from torch_geometric.transforms import BaseTransform, Compose

import os
os.environ['TORCH_SHOW_CPP_STACKTRACES'] = '1'

class customData(Data):
    @classmethod
    def take_feat(cls, data: Data):

        relations = {
            0: [2, 7, 6, 5, 1, 3],
            1: [2, 5, 4, 3],
            2: [2, 3, 4, 5,2]
        }
        data["relations"] = torch.nested.nested_tensor(list(
            relations.values()))

        data = cls.from_dict(data.to_dict())
        return data

    def __cat_dim__(self, key: str, value: Any, *args, **kwargs) -> Any:
        if 'edge_index' in key:
            return 1
        else:
            return 0

    def __inc__(self, key: str, value: Any, *args, **kwargs) -> Any:
        if 'edge_index' in key:
            return torch.tensor([[getattr(self, 'x').size(0)],
                                 [getattr(self, 'x').size(0)]])
        if 'relation' in key:
            return getattr(self, 'x').size(0)
        else:
            return super().__inc__(key, value, *args, **kwargs)


class customTransformations(BaseTransform):
    def __call__(self, data: Data):

        new_data = customData.take_feat(data)
        return new_data

data_train = ZINC("/tmp/custom_zinc-trial", subset=True, split='train',
                  pre_transform=Compose([customTransformations()]))

train_loader = DataLoader(data_train, batch_size=128)
batch = next(iter(train_loader))
print(batch)


```

```
Traceback (most recent call last):
  File "/Users/veljko/Desktop/enmpcn/enmpcn/try_zinc.py", line 102, in <module>
    data_train = ZINC("/tmp/custom_zinc-trial", subset=True, split='train',
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric/datasets/zinc.py", line 100, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric/data/in_memory_dataset.py", line 74, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 102, in __init__
    self._process()
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 235, in _process
    self.process()
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric/datasets/zinc.py", line 169, in process
    torch.save(self.collate(data_list),
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/serialization.py", line 653, in _save
    pickler.dump(obj)
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/_tensor.py", line 212, in __reduce_ex__
    return self._reduce_ex_internal(proto)
  File "/Users/veljko/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/_tensor.py", line 390, in _reduce_ex_internal
    tuple(self.size()),
RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
Exception raised from sym_sizes_custom at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1682343686209/work/aten/src/ATen/NestedTensorImpl.cpp:285 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 81 (0x10be923a1 in libc10.dylib)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 197 (0x10be90b75 in libc10.dylib)
frame #2: at::native::NestedTensorImpl::sym_sizes_custom() const + 35 (0x1325bb393 in libtorch_cpu.dylib)
frame #3: THPSize_NewFromSymSizes(at::Tensor const&) + 673 (0x110a3d371 in libtorch_python.dylib)
frame #4: torch::autograd::THPVariable_size(_object*, _object*, _object*) + 472 (0x1105d93f8 in libtorch_python.dylib)
frame #5: method_vectorcall_VARARGS_KEYWORDS + 176 (0x1029949d0 in python3.9)
frame #6: _PyEval_EvalFrameDefault + 30778 (0x102a97e7a in python3.9)
frame #7: _PyFunction_Vectorcall + 420 (0x1029851a4 in python3.9)
frame #8: _PyEval_EvalFrameDefault + 30778 (0x102a97e7a in python3.9)
frame #9: _PyFunction_Vectorcall + 420 (0x1029851a4 in python3.9)
frame #10: method_vectorcall + 158 (0x10298a6fe in python3.9)
frame #11: _Pickle_FastCall + 97 (0x10c68ccf1 in _pickle.cpython-39-darwin.so)
frame #12: save + 1945 (0x10c68f6d9 in _pickle.cpython-39-darwin.so)
frame #13: save + 6682 (0x10c69095a in _pickle.cpython-39-darwin.so)
frame #14: save + 6682 (0x10c69095a in _pickle.cpython-39-darwin.so)
frame #15: save_reduce + 879 (0x10c693cff in _pickle.cpython-39-darwin.so)
frame #16: save + 2005 (0x10c68f715 in _pickle.cpython-39-darwin.so)
frame #17: save + 6682 (0x10c69095a in _pickle.cpython-39-darwin.so)
frame #18: save_reduce + 879 (0x10c693cff in _pickle.cpython-39-darwin.so)
frame #19: save + 2005 (0x10c68f715 in _pickle.cpython-39-darwin.so)
frame #20: save + 1309 (0x10c68f45d in _pickle.cpython-39-darwin.so)
frame #21: dump + 201 (0x10c68ebc9 in _pickle.cpython-39-darwin.so)
frame #22: _pickle_Pickler_dump + 104 (0x10c68e868 in _pickle.cpython-39-darwin.so)
frame #23: method_vectorcall_O + 121 (0x102994299 in python3.9)
frame #24: _PyEval_EvalFrameDefault + 30778 (0x102a97e7a in python3.9)
frame #25: _PyFunction_Vectorcall + 1260 (0x1029854ec in python3.9)
frame #26: _PyEval_EvalFrameDefault + 30283 (0x102a97c8b in python3.9)
frame #27: _PyFunction_Vectorcall + 1260 (0x1029854ec in python3.9)
frame #28: _PyEval_EvalFrameDefault + 37074 (0x102a99712 in python3.9)
frame #29: _PyFunction_Vectorcall + 420 (0x1029851a4 in python3.9)
frame #30: method_vectorcall + 158 (0x10298a6fe in python3.9)
frame #31: _PyEval_EvalFrameDefault + 37074 (0x102a99712 in python3.9)
frame #32: _PyFunction_Vectorcall + 420 (0x1029851a4 in python3.9)
frame #33: method_vectorcall + 158 (0x10298a6fe in python3.9)
frame #34: _PyEval_EvalFrameDefault + 37074 (0x102a99712 in python3.9)
frame #35: _PyFunction_Vectorcall + 1260 (0x1029854ec in python3.9)
frame #36: method_vectorcall + 158 (0x10298a6fe in python3.9)
frame #37: _PyEval_EvalFrameDefault + 37074 (0x102a99712 in python3.9)
frame #38: _PyFunction_Vectorcall + 1260 (0x1029854ec in python3.9)
frame #39: method_vectorcall + 158 (0x10298a6fe in python3.9)
frame #40: _PyEval_EvalFrameDefault + 37074 (0x102a99712 in python3.9)
frame #41: _PyFunction_Vectorcall + 1260 (0x1029854ec in python3.9)
frame #42: slot_tp_init + 548 (0x102a0b9a4 in python3.9)
frame #43: type_call + 272 (0x102a10e70 in python3.9)
frame #44: _PyEval_EvalFrameDefault + 39178 (0x102a99f4a in python3.9)
frame #45: _PyEval_EvalCode + 658 (0x102a8e922 in python3.9)
frame #46: run_mod + 196 (0x102b02d24 in python3.9)
frame #47: pyrun_file + 167 (0x102b01777 in python3.9)
frame #48: pyrun_simple_file + 460 (0x102b012ec in python3.9)
frame #49: PyRun_SimpleFileExFlags + 53 (0x102b010f5 in python3.9)
frame #50: pymain_run_file + 279 (0x102b24d67 in python3.9)
frame #51: pymain_run_python + 417 (0x102b24521 in python3.9)
frame #52: Py_RunMain + 37 (0x102b24335 in python3.9)
frame #53: main + 56 (0x102926c68 in python3.9)
frame #54: start + 462 (0x202efe4fe in dyld)
frame #55: dyld + 0 (0x202ef9000 in dyld)
frame #56: __dso_handle + 0 (0x102925000 in python3.9)

```

**Comment by soulitzer** [comment]
Hi @vkovac2, thanks for the stack trace, the error you are seeing is because NestedTensor currently does not support pickling. I've updated the issue description to reflect that.

Supporting this would involve adding a branch handling nested tensor in the `_reduce_ex_internal` function of `torch/_tensor.py`.
