### ISSUE TITLE
ProcessGroupGloo ->  bind: Address already in use

### ISSUE THREAD

**Issue by shileims** [pytorch/pytorch#104136]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "train_dreambooth_inpaint_unet_colossalaiv3.py", line 745, in <module>
    main()
  File "train_dreambooth_inpaint_unet_colossalaiv3.py", line 407, in main
    colossalai.launch_from_torch(config={})
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/initialize.py", line 227, in launch_from_torch
    verbose=verbose)
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/initialize.py", line 99, in launch
    gpc.init_global_dist(rank, world_size, backend, host, port)
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/context/parallel_context.py", line 378, in init_global_dist
    cpu_group = dist.new_group(ranks, backend='gloo') if dist.get_backend() != 'gloo' else None
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2905, in new_group
    timeout=timeout,
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 684, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1634272178570/work/third_party/gloo/gloo/transport/tcp/pair.cc:176] bind: Address already in use
Traceback (most recent call last):
  File "train_dreambooth_inpaint_unet_colossalaiv3.py", line 745, in <module>
    main()
  File "train_dreambooth_inpaint_unet_colossalaiv3.py", line 407, in main
    colossalai.launch_from_torch(config={})
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/initialize.py", line 227, in launch_from_torch
    verbose=verbose)
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/initialize.py", line 99, in launch
    gpc.init_global_dist(rank, world_size, backend, host, port)
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/context/parallel_context.py", line 378, in init_global_dist
    cpu_group = dist.new_group(ranks, backend='gloo') if dist.get_backend() != 'gloo' else None
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2905, in new_group
    timeout=timeout,
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 684, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1634272178570/work/third_party/gloo/gloo/transport/tcp/pair.cc:176] bind: Address already in use
Traceback (most recent call last):
  File "train_dreambooth_inpaint_unet_colossalaiv3.py", line 745, in <module>
    main()
  File "train_dreambooth_inpaint_unet_colossalaiv3.py", line 407, in main
    colossalai.launch_from_torch(config={})
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/initialize.py", line 227, in launch_from_torch
    verbose=verbose)
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/initialize.py", line 99, in launch
    gpc.init_global_dist(rank, world_size, backend, host, port)
  File "/tmp/py-userbase/lib/python3.7/site-packages/colossalai/context/parallel_context.py", line 378, in init_global_dist
    cpu_group = dist.new_group(ranks, backend='gloo') if dist.get_backend() != 'gloo' else None
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2905, in new_group
    timeout=timeout,
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 684, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1634272178570/work/third_party/gloo/gloo/transport/tcp/pair.cc:176] bind: Address already in use
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2647 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2654 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2659 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2667 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2675 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 5 (pid: 2694) of binary: /opt/conda/bin/python

### Versions

colossal ai == 0.2.7
torch == 1.10.0
cuda == 11.1

One month ago, everything is ok for me. But now, it doesn't work.

**Comment by shileims** [comment]
After retry torch 1.11, colossalai == 0.2.8, colossalai == 0.3.0 by using booster, the same error here.
