### ISSUE TITLE
PyTorch2.0 ROCM LayerNorm HIP error: invalid configuration

### ISSUE THREAD

**Issue by danny305** [pytorch/pytorch#104147]
### 🐛 Describe the bug

I am trying to  inference a protein structure graph transformer model using PyTorch2 with rocm-5.4.3/5.5.1 on MI210 GPUs. 

When I scale the batch size pass 250 per gpu I get the error below. The error does not exist when we use PyTorch 1.13 and we can scale to 1500 batch size per gpu on the MI210s. However, It works with PyTorch2 on our A100 GPUs. So it seems to be specific to PyTorch2.0 on ROCM. 

I have begun working with @srinivamd on the issue. He can discuss more about the current state of diagnosing and debugging the issue. 

```python
Original Traceback (most recent call last):
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/local/proteins/ml/Negatron/Negatron/models/torch/oracle/stability_oracle.py", line 334, in forward
    local_env_feats, aa_logits = self.backbone(
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/local/proteins/ml/Negatron/Negatron/models/torch/oracle/stability_oracle.py", line 220, in forward
    x = layer(
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/local/proteins/ml/Negatron/Negatron/models/torch/oracle/transformer.py", line 271, in forward
    attn_bias = self.distance_encoder(attn_bias_feat).permute(
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: HIP error: invalid configuration argument
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

### Versions

Collecting environment information...
/scratch/cluster/danny305/miniconda3/envs/amd/lib/python3.8/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
PyTorch version: 2.0.1+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI210
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22804
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7763 64-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1500.000
CPU max MHz:                     3529.0520
CPU min MHz:                     1500.0000
BogoMIPS:                        4899.83
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] pytorch-triton-rocm==2.0.1
[pip3] torch==2.0.1+rocm5.4.2
[pip3] torchaudio==2.0.2+rocm5.4.2
[pip3] torchvision==0.15.2+rocm5.4.2
[conda] nomkl                     3.0                           0    anaconda
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch-triton-rocm       2.0.1                    pypi_0    pypi
[conda] torch                     2.0.1+rocm5.4.2          pypi_0    pypi
[conda] torchaudio                2.0.2+rocm5.4.2          pypi_0    pypi
[conda] torchvision               0.15.2+rocm5.4.2          pypi_0    pypi

**Comment by srinivamd** [comment]
```
:3:hip_module.cpp           :469 : 3375414038276 us: 1238294: [tid:0x7f48e2ff2700]  hipLaunchKernel ( 0x7f48b98007d8, {208,2,1}, {512,1,1}, 0x7f48e2fee440, 0, stream:<null> ) 
:4:rocvirtual.cpp           :862 : 3375414038348 us: 1238294: [tid:0x7f48e2ff2700] HWq=0x7f493e81c000, Dispatch Header = 0xb02 (type=2, barrier=1, acquire=1, release=1), setup=3, grid=[106496, 2, 1], workgroup=[512, 1, 1], private_seg_size=0, group_seg_size=0, kernel_obj=0x7f491c460940, kernarg_address=0x7f4917208200, completion_signal=0x0
:3:hip_module.cpp           :470 : 3375414038355 us: 1238294: [tid:0x7f48e2ff2700] hipLaunchKernel: Returned hipSuccess : 
:3:hip_module.cpp           :469 : 3375414040859 us: 1238294: [tid:0x7f48e2ff2700]  hipLaunchKernel ( 0x7f48b9809870, {78950700,1,1}, {64,4,1}, 0x7f48e2fee4a0, 24, stream:<null> )
:3:hip_module.cpp           :470 : 3375414040880 us: 1238294: [tid:0x7f48e2ff2700] hipLaunchKernel: Returned hipErrorInvalidConfiguration : 
```
Verbose log showing the failing hipLaunchKernel call with hipErrorInvalidConfiguration

@jeffdaily @jithunnair-amd

**Comment by jeffdaily** [comment]
@danny305 would you be able to try our latest nightly wheel that has rocm 5.5?

`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5`

**Comment by danny305** [comment]
Just tried the nightly build. 
Same error:
```python
Original Traceback (most recent call last):
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/shared/prod/home/danny/ml/Negatron/Negatron/models/torch/oracle/stability_oracle.py", line 334, in forward
    local_env_feats, aa_logits = self.backbone(
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/shared/prod/home/danny/ml/Negatron/Negatron/models/torch/oracle/stability_oracle.py", line 220, in forward
    x = layer(
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/shared/prod/home/danny/ml/Negatron/Negatron/models/torch/oracle/transformer.py", line 271, in forward
    attn_bias = self.distance_encoder(attn_bias_feat).permute(
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/shared/prod/home/danny/.conda/envs/amd/lib/python3.10/site-packages/torch/nn/functional.py", line 2548, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: HIP error: invalid configuration argument
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

**Comment by srinivamd** [comment]
@jeffdaily  @jithunnair-amd 
Is there a fix available to try? Should we try the ROCm 5.6 pytorch 2.0 wheel from `https://repo.radeon.com/rocm/manylinux/rocm-rel-5.6/` here?
CC: @danny305

**Comment by jithunnair-amd** [comment]
Yes, please try the ROCm5.6 wheels, since this looks like something that could have regressed in HIP/ROCm, assuming the layernorm kernels are launched with the same config in PyTorch 1.13 vs 2.0.

@danny305 Would you be able to provide a simple reduced testcase which just calls the layernorm op with the same inputs that you provide in your app? I expect it should fail even in a standalone testcase with the same HIP configuration error. That would really help us dig into this faster.

**Comment by jeffdaily** [comment]
@danny305 are you able to create a smaller reproducer?  Or provide us with the input shapes that were used with layernorm so we can try to reproduce?
