### ISSUE TITLE
cudnn error

### ISSUE THREAD

**Issue by luoqiuluoqiu** [pytorch/pytorch#1042]
environment:Centos7.0   cuda8.0 cudnn5.1  

Error info:
Traceback (most recent call last):
  File "rnnTest.py", line 129, in <module>
    outputs = rnn(inputx)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "rnnTest.py", line 40, in forward
    out, _ = self.lstm1(x, (self.h0, self.c0))
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 327, in forward
    return func(input, *fargs, **fkwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 201, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 223, in forward
    result = self.forward_extended(*nested_tensors)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 269, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 239, in forward
    fn.hx_desc = cudnn.descriptor(hx)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/__init__.py", line 398, in descriptor
    descriptor.set(tensor)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/__init__.py", line 159, in set
    self, _typemap[tensor.type()], tensor.dim(),
KeyError: 'torch.FloatTensor'

could you tell me what to do now？
thankyou

**Comment by jekbradbury** [comment]
In the line `self.lstm1(x, (self.h0, self.c0))`, at least one of the inputs is on CPU while at least one other input is on GPU. They have to all be on one or the other; you can add a `print(x.is_cuda, self.h0.is_cuda, self.c0.is_cuda)` before that line to see which ones are where.
