### ISSUE TITLE
Attempt to use minifier on sam model fails

### ISSUE THREAD

**Issue by HDCharles** [pytorch/pytorch#104301]
### 🐛 Describe the bug

calling TORCHDYNAMO_REPRO_AFTER="dynamo" TORCHDYNAMO_REPRO_LEVEL=4 gpurun2 python experimental/segment_anything/accuracy_spot_check.py --quantized=0 --compiled=2 &>log.txt  results in an error. Whereas the model runs without issue when called normally but torch.compile returns a model with poor accuracy

### Error logs

Namespace(model_type='vit_h', checkpoint_path='/data/home/vasiliy/cluster/sam_dataset/sam_vit_h_4b8939.pth', run_shadow_sqnr=0, quantized=0, compiled=2, image_dir='/data/home/cdhernandez/cluster/saf/notebooks/images', run_name='test', save_model=0, generate_images=0)
fp32-dog.png
fp32-truck.png
fp32-groceries.png
AUTOTUNE mm(4900x1280, 1280x3840)
  triton_mm_8 0.2427 ms 100.0%
  mm 0.2468 ms 98.3%
  triton_mm_9 0.2478 ms 97.9%
  triton_mm_10 0.2990 ms 81.2%
  triton_mm_11 0.3000 ms 80.9%
  triton_mm_7 0.3308 ms 73.4%
  triton_mm_15 0.3502 ms 69.3%
  triton_mm_14 0.4321 ms 56.2%
  triton_mm_17 0.5437 ms 44.6%
  triton_mm_16 0.6636 ms 36.6%
SingleProcess AUTOTUNE takes 6.3883 seconds
AUTOTUNE mm(4900x1280, 1280x1280)
  mm 0.0788 ms 100.0%
  triton_mm_69 0.0942 ms 83.7%
  triton_mm_68 0.0952 ms 82.8%
  triton_mm_71 0.1137 ms 69.4%
  triton_mm_70 0.1147 ms 68.7%
  triton_mm_67 0.1270 ms 62.1%
  triton_mm_75 0.1280 ms 61.6%
  triton_mm_74 0.1526 ms 51.7%
  triton_mm_77 0.2017 ms 39.1%
  triton_mm_72 0.2304 ms 34.2%
SingleProcess AUTOTUNE takes 6.0125 seconds
AUTOTUNE mm(4096x1280, 1280x5120)
  mm 0.2222 ms 100.0%
  triton_mm_80 0.2703 ms 82.2%
  triton_mm_81 0.2724 ms 81.6%
  triton_mm_83 0.3267 ms 68.0%
  triton_mm_82 0.3277 ms 67.8%
  triton_mm_79 0.3799 ms 58.5%
  triton_mm_87 0.3871 ms 57.4%
  triton_mm_86 0.4833 ms 46.0%
  triton_mm_89 0.6031 ms 36.8%
  triton_mm_84 0.7322 ms 30.3%
SingleProcess AUTOTUNE takes 6.0187 seconds
AUTOTUNE mm(4096x5120, 5120x1280)
  mm 0.2038 ms 100.0%
  triton_mm_92 0.2652 ms 76.8%
  triton_mm_93 0.2652 ms 76.8%
  triton_mm_95 0.3082 ms 66.1%
  triton_mm_94 0.3092 ms 65.9%
  triton_mm_99 0.3686 ms 55.3%
  triton_mm_91 0.4045 ms 50.4%
  triton_mm_98 0.4680 ms 43.5%
  triton_mm_101 0.6605 ms 30.9%
  triton_mm_96 0.7014 ms 29.1%
SingleProcess AUTOTUNE takes 6.1106 seconds
AUTOTUNE mm(4096x1280, 1280x3840)
  mm 0.1638 ms 100.0%
  triton_mm_680 0.2038 ms 80.4%
  triton_mm_681 0.2048 ms 80.0%
  triton_mm_683 0.2468 ms 66.4%
  triton_mm_682 0.2478 ms 66.1%
  triton_mm_679 0.2785 ms 58.8%
  triton_mm_687 0.2918 ms 56.1%
  triton_mm_686 0.3574 ms 45.8%
  triton_mm_689 0.4618 ms 35.5%
  triton_mm_688 0.5550 ms 29.5%
SingleProcess AUTOTUNE takes 5.9864 seconds
AUTOTUNE mm(4096x1280, 1280x1280)
  mm 0.0625 ms 100.0%
  triton_mm_740 0.0768 ms 81.3%
  triton_mm_741 0.0768 ms 81.3%
  triton_mm_742 0.0901 ms 69.3%
  triton_mm_743 0.0901 ms 69.3%
  triton_mm_747 0.1055 ms 59.2%
  triton_mm_739 0.1106 ms 56.5%
  triton_mm_746 0.1219 ms 51.3%
  triton_mm_749 0.1731 ms 36.1%
  triton_mm_744 0.1925 ms 32.4%
SingleProcess AUTOTUNE takes 5.9320 seconds
reduction over non-contiguous dims
[2023-06-27 21:55:13,070] torch._dynamo.debug_utils: [ERROR] While minifying the program in accuracy minification mode, ran into a runtime exception which is likely an unrelated issue. Skipping this graph
Traceback (most recent call last):
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/debug_utils.py", line 453, in backend_accuracy_fails
    compiled_gm = compiler_fn(
  File "/fsx/users/cdhernandez/pytorch/torch/__init__.py", line 1530, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/fsx/users/cdhernandez/pytorch/torch/_inductor/compile_fx.py", line 730, in compile_fx
    return compile_fx(
  File "/fsx/users/cdhernandez/pytorch/torch/_inductor/compile_fx.py", line 912, in compile_fx
    return aot_autograd(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 3713, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 3202, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 715, in inner
    flat_f_outs = f(*flat_f_args)
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 3319, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/interpreter.py", line 312, in call_module
    return submod(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Cannot call numel() on tensor with symbolic sizes/strides

While executing %getattr_l__self___blocks_0___1___attn_qkv : [#users=1] = call_module[target=getattr_L__self___blocks_0___1___attn_qkv](args = (%view_1,), kwargs = {})
Original traceback:
  File "/fsx/users/cdhernandez/saf/segment_anything/modeling/image_encoder.py", line 111, in forward
    x = blk(x)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/saf/segment_anything/modeling/image_encoder.py", line 171, in forward
    x = self.attn(x)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/saf/segment_anything/modeling/image_encoder.py", line 223, in forward
    qkv = self.qkv(x).reshape(B, H * W, 3, self.num_heads, -1).permute(2, 0, 3, 1, 4)

[2023-06-27 21:55:13,190] torch.fx.experimental.symbolic_shapes: [WARNING] 0.0: Failing guard allocated at: 
  File "/fsx/users/cdhernandez/ao_benchmarks/experimental/segment_anything/accuracy_spot_check.py", line 336, in <module>
    run()
  File "/fsx/users/cdhernandez/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/fsx/users/cdhernandez/ao_benchmarks/experimental/segment_anything/accuracy_spot_check.py", line 309, in run
    act[args.run_name+"out"]["image-encoder"].append(sam.image_encoder(input).detach())
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 526, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/symbolic_convert.py", line 2026, in run
    super().run()
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/symbolic_convert.py", line 2114, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/output_graph.py", line 763, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/fsx/users/cdhernandez/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/output_graph.py", line 859, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/output_graph.py", line 911, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/repro/after_dynamo.py", line 81, in debug_wrapper
    if backend_accuracy_fails(gm, example_inputs, compiler_fn):
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/debug_utils.py", line 453, in backend_accuracy_fails
    compiled_gm = compiler_fn(
  File "/fsx/users/cdhernandez/pytorch/torch/__init__.py", line 1530, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/fsx/users/cdhernandez/pytorch/torch/_inductor/compile_fx.py", line 730, in compile_fx
    return compile_fx(
  File "/fsx/users/cdhernandez/pytorch/torch/_inductor/compile_fx.py", line 912, in compile_fx
    return aot_autograd(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 3713, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 3202, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 715, in inner
    flat_f_outs = f(*flat_f_args)
  File "/fsx/users/cdhernandez/pytorch/torch/_functorch/aot_autograd.py", line 3319, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/interpreter.py", line 312, in call_module
    return submod(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/fsx/users/cdhernandez/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_subclasses/fake_tensor.py", line 1161, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_subclasses/fake_tensor.py", line 1381, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_subclasses/fake_tensor.py", line 612, in conv
    conv_backend = torch._C._select_conv_backend(**kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/experimental/symbolic_shapes.py", line 852, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint)

Traceback (most recent call last):
  File "/fsx/users/cdhernandez/ao_benchmarks/experimental/segment_anything/accuracy_spot_check.py", line 336, in <module>
    run()
  File "/fsx/users/cdhernandez/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/fsx/users/cdhernandez/ao_benchmarks/experimental/segment_anything/accuracy_spot_check.py", line 309, in run
    act[args.run_name+"out"]["image-encoder"].append(sam.image_encoder(input).detach())
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 526, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/convert_frame.py", line 478, in _compile
    check_fn = CheckFunctionManager(
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/guards.py", line 863, in __init__
    guard.create(local_builder, global_builder)
  File "/fsx/users/cdhernandez/pytorch/torch/_guards.py", line 208, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/fsx/users/cdhernandez/pytorch/torch/_dynamo/guards.py", line 540, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/fsx/users/cdhernandez/pytorch/torch/fx/experimental/symbolic_shapes.py", line 2520, in produce_guards
    guard_expr = ShapeGuardPrinter(symbol_to_source, source_ref, self.var_to_sources).doprint(g)
  File "/fsx/users/cdhernandez/conda/lib/python3.9/site-packages/sympy-1.12rc1-py3.9.egg/sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/fsx/users/cdhernandez/conda/lib/python3.9/site-packages/sympy-1.12rc1-py3.9.egg/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/fsx/users/cdhernandez/conda/lib/python3.9/site-packages/sympy-1.12rc1-py3.9.egg/sympy/printing/str.py", line 778, in _print_Relational
    return '%s %s %s' % (self.parenthesize(expr.lhs, precedence(expr)),
  File "/fsx/users/cdhernandez/conda/lib/python3.9/site-packages/sympy-1.12rc1-py3.9.egg/sympy/printing/str.py", line 38, in parenthesize
    return self._print(item)
  File "/fsx/users/cdhernandez/conda/lib/python3.9/site-packages/sympy-1.12rc1-py3.9.egg/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/fsx/users/cdhernandez/pytorch/torch/fx/experimental/symbolic_shapes.py", line 1493, in _print_Symbol
    assert self.symbol_to_source.get(expr), (
AssertionError: s1 (could be from ['__meta_utils_unknown_tensor527.size()[2]', '__meta_utils_unknown_tensor527.size()[3]']) not in {s1: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

srun: error: a100-st-p4d24xlarge-49: task 0: Exited with exit code 1

### Minified repro

minifier itself errors, repro info above

### Versions

(base) cdhernandez@ip-10-200-79-136:/fsx/users/cdhernandez/ao_benchmarks$ gpurun2 python3 collect_env.py
Collecting environment information...
PyTorch version: 2.1.0a0+git1dba81f
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-1019-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         2999.998
BogoMIPS:                        5999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0a0+git1dba81f
[pip3] torchvision==0.16.0a0+e5bf7cf
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2023.0.0         h06a4308_25399  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
[conda] torch                     2.1.0a0+git1dba81f           dev_0    <develop>
[conda] torchvision               0.16.0a0+e5bf7cf           dev_0    <develop>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by HDCharles** [comment]
@ezyang

**Comment by HDCharles** [comment]
I think the accuracy bug i was trying to diagnose was due to https://github.com/pytorch/pytorch/issues/104435 but the minifier failure is due to something else.

note: there's also an issue with trying to export the graph of SAM where you run into a maximum recursion depth error due to calculation of dynamic shapes, not sure if thats causing the above minifier failure.

**Comment by ezyang** [comment]
The max recursion error usually can be suppressed without big problems, so it's probably unrelated

**Comment by bobrenjc93** [comment]
Closing out old issues that are likely resolved, as it’s not sustainable to verify each one individually. If the issue persists, feel free to reopen.
