### ISSUE TITLE
Local docs build is broken

### ISSUE THREAD

**Issue by davidradl** [pytorch/pytorch#104377]
### 🐛 Describe the bug

I followed the instructions to build the docs locally and the `make html` fails with 
```
Traceback (most recent call last):
  File "/Users/davidradley/pytorch/docs/source/scripts/build_opsets.py", line 74, in <module>
    main()
  File "/Users/davidradley/pytorch/docs/source/scripts/build_opsets.py", line 57, in main
    aten_ops_list = get_aten()
  File "/Users/davidradley/pytorch/docs/source/scripts/build_opsets.py", line 19, in get_aten
    parsed_yaml = parse_native_yaml(NATIVE_FUNCTION_YAML_PATH, TAGS_YAML_PATH)
  File "/Users/davidradley/miniconda3/lib/python3.10/site-packages/torchgen/gen.py", line 235, in parse_native_yaml
    _GLOBAL_PARSE_NATIVE_YAML_CACHE[path] = parse_native_yaml_struct(
  File "/Users/davidradley/miniconda3/lib/python3.10/site-packages/torchgen/gen.py", line 167, in parse_native_yaml_struct
    error_check_native_functions(rs)
  File "/Users/davidradley/miniconda3/lib/python3.10/site-packages/torchgen/gen.py", line 277, in error_check_native_functions
    assert len(base_func_map[out_of_place_base_name]) > 0, (
AssertionError: resize_as_ is marked with tag: inplace_view. The codegen expects there to be a corresponding out-of-place view op with the name 'resize_as_' and matching schema, but it didn't find one.
```
It appears to be picking up the gen.py from my miniconda3 not from my /Users/davidradley/pytorch. The version of gen.py in /Users/davidradley/pytorch would not cause this issue as there is an if condition to not process 'resize_as_'.

I notice there is no egg-info or egg-link for torchgen. 

I originally thought this was my setup but another user (who has had it working before) gets the same error.

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git6c1cccc
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-13.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.1.0a0+git6c1cccc
[conda] numpy                     1.25.0                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     2.1.0a0+git6c1cccc           dev_0    <develop>

**Comment by davidradl** [comment]
I think I understand the cause. torchgen package data does not account for gen.py because it is in the root folder.  
```
torchgen_package_data = [
        # Recursive glob doesn't work in setup.py,
        # https://github.com/pypa/setuptools/issues/1806
        # To make this robust we should replace it with some code that
        # returns a list of everything under packaged/
        'packaged/ATen/*',
        'packaged/ATen/native/*',
        'packaged/ATen/templates/*',
    ]
```

Testing and investigating, I hope that adding a line like  'packaged/*', or  'packaged/*.py' will correct this.

**Comment by davidradl** [comment]
closing duplicate of https://github.com/pytorch/pytorch/issues/104113
