### ISSUE TITLE
`test_storage_meta_errors_cpu` should fail but passes in CI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#104410]
### 🐛 Describe the bug

CI signal on  https://github.com/pytorch/pytorch/pull/104355 is green, but testing on https://github.com/pytorch/pytorch/actions/runs/5409497721/jobs/9829920184 is also green, which should not be possible.

And indeed local run of the test fails with `TypeError`:
```
test_storage_meta_errors_cpu_uint8 (__main__.TestTorchDeviceTypeCPU) ... /home/nshulga/git/pytorch/pytorch/test/test_torch.py:332: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  s0 = torch.TypedStorage([1, 2, 3, 4], device='meta', dtype=dtype)
ERROR

======================================================================
ERROR: test_storage_meta_errors_cpu_uint8 (__main__.TestTorchDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1074, in only_fn
    return fn(slf, *args, **kwargs)
  File "/home/nshulga/git/pytorch/pytorch/test/test_torch.py", line 351, in test_storage_meta_errors
    s0.pin_memory()
  File "/home/nshulga/git/pytorch/pytorch/torch/storage.py", line 842, in pin_memory
    return self._new_wrapped_storage(self._untyped_storage.pin_memory(device=device))
  File "/home/nshulga/git/pytorch/pytorch/torch/storage.py", line 223, in pin_memory
    raise TypeError(f"cannot pin '{self.type()}' only CPU memory can be pinned")
TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned

----------------------------------------------------------------------
Ran 1 test in 0.014s

FAILED (errors=1)
```

### Versions

CI

cc @ezyang @gchanan @zou3519 @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
An even more ridiculous example:
```
$ python test_segment_reductions.py -v -k test_multi_d_simple_cpu_float32_int32
test_multi_d_simple_cpu_float32_int32 (__main__.TestSegmentReductionsCPU) ... ERROR

======================================================================
ERROR: test_multi_d_simple_cpu_float32_int32 (__main__.TestSegmentReductionsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/nshulga/git/pytorch/pytorch/test/test_segment_reductions.py", line 357, in test_multi_d_simple
    expected_result,
UnboundLocalError: local variable 'expected_result' referenced before assignment

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```
