### ISSUE TITLE
cuda problem

### ISSUE THREAD

**Issue by mjiansun** [pytorch/pytorch#1044]
**cuda problem:**

CMake Warning:
  Manually-specified variables were not used by the project:
    NO_CUDA
    THCS_LIBRARIES
    THCUNN_SO_VERSION
    THC_LIBRARIES
    THD_SO_VERSION
    THNN_SO_VERSION
    THPP_LIBRARIES
    THS_LIBRARIES
    TH_SO_VERSION

**Comment by apaszke** [comment]
It's a harmless warning. You can ignore this.

**Comment by mjiansun** [comment]
**when i run my code, i have following problem:**
Traceback (most recent call last):
  File "/home/s/tool/pycharm/pycharm-2016.3/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/s/tool/pycharm/pycharm-2016.3/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/s/myproject/brats-master/src/main.py", line 232, in <module>
    main()
  File "/home/s/myproject/brats-master/src/main.py", line 116, in main
    train_loss = train(train_loader, model, criterion, optimizer, epoch)
  File "/home/s/myproject/brats-master/src/main.py", line 152, in train
    output = model((x1, x2)) # nx5x9x9x9
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/s/myproject/brats-master/src/model.py", line 41, in forward
    x1 = self.branch1(x1)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 330, in forward
    self.padding, self.dilation, self.groups)
  File "/home/s/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 88, in conv3d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_BAD_PARAM
