### ISSUE TITLE
[Quantization][Dispatch] Wrong dispatch when implementing quantized Conv2d for QuantizedPrivateUse1

### ISSUE THREAD

**Issue by fmo-mt** [pytorch/pytorch#104412]
### 🐛 Describe the bug

I implement the quantized convolution for `QuantizedPrivateUse1` backend as below:
```c++
TORCH_LIBRARY_IMPL(quantized, QuantizedPrivateUse1, m) {
   im.impl(
        TORCH_SELECTIVE_NAME("quantized::conv2d.new"), QConvUInt8<2, false>::run);
    im.impl(
       TORCH_SELECTIVE_NAME("quantized::conv2d_relu.new"),
      QConvUInt8<2, true>::run);
 }
```
which follows what pytorch does in [this](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/quantized/cpu/qconv.cpp#L1528), but pytorch throw an error of:
```txt
NotImplementedError: Could not run 'quantized::conv2d_relu.new' with arguments from the 'AutogradPrivateUse1' backend.
```
which confuses me a lot.

This `quantized::conv2d_relu` should be under `quantized` scope, and why pytorch dispatch it to `AutogradPrivateUse1` backend?

Full error info:
```txt
Traceback (most recent call last):
  File "test_int8.py", line 64, in <module>
    test_model()
  File "test_int8.py", line 12, in test_model
    out = net(inp)
  File "/workspace/pyenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pyenv/lib/python3.8/site-packages/torchvision/models/quantization/resnet.py", line 110, in forward
    x = self._forward_impl(x)
  File "/workspace/pyenv/lib/python3.8/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/workspace/pyenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pyenv/lib/python3.8/site-packages/torch/ao/nn/intrinsic/quantized/modules/conv_relu.py", line 98, in forward
    return torch.ops.quantized.conv2d_relu(
  File "/workspace/pyenv/lib/python3.8/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'quantized::conv2d_relu.new' with arguments from the 'Autogradmusa' backend. This could be because the operator doesn't exist for t
his backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit ht
tps://fburl.com/ptmfixes for possible resolutions. 'quantized::conv2d_relu.new' is only available for these backends: [QuantizedCPU, BackendSelect, Python, FuncTorchD
ynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, Autog
radXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, Pyth
onTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher]
```

### Versions

PyTorch version: 2.0.0a0+gitc263bd4
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 14.0.0 (git@github.mthreads.com:mthreads/mtcc.git 36f7f9d32ab6ba7d2f75c238fd422e9bc8e2defe)
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.0.0a0+git2445665
[pip3] torch-musa==2.0.0
[pip3] torchvision==0.15.2
[conda] No relevant packages

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by fmo-mt** [comment]
Update:

After register `quantized::conv2d_relu.new` to `AutogradPrivateUse1`, pytorch would call FBGEMM kernel instead of what I registered, here's gdb call stack:

```
(gdb) bt
#0  0x00007ffff7ddd767 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffe2b7eec4 in fbgemm::pack_a_with_im2col_opt<2, 512> (conv_p=..., block=..., sdata=0x80105e8000 <error: Cannot access memory at address 0x80105e8000>,
    out=0x7ffeb4005dc0 "", a_zero_pt=0, row_offset_buf=0x0, COL_SIZE=147, COL_P_SIZE=148, row_offset_acc=false)
    at /home/pytorch/third_party/fbgemm/src/PackAWithIm2Col.cc:182
#2  0x00007fffe2b7641d in fbgemm::PackAWithIm2Col<unsigned char, int, 2>::pack (this=0x7ffee6804bb0, block=...)
    at /home/pytorch/third_party/fbgemm/src/PackAWithIm2Col.cc:311
#3  0x00007fffe2b08779 in fbgemm::PackMatrix<fbgemm::PackAWithIm2Col<unsigned char, int, 2>, unsigned char, int>::pack (this=0x7ffee6804bb0, block=...)
    at /home/pytorch/third_party/fbgemm/include/fbgemm/Fbgemm.h:157
#4  0x00007fffe2ac3297 in fbgemm::fbgemmPacked<fbgemm::PackAWithIm2Col<unsigned char, int, 2>, fbgemm::PackBMatrix<signed char, int>, unsigned char, fbgemm::ReQuantizeOutput<true, (fbgemm::QuantizationGranularity)2, float, unsigned char, int, fbgemm::DoNothing<unsigned char, unsigned char> > > (packA=..., packB=...,
    C=0x22552280 "\260\250\377\377\377\177", C_buffer=0x239afe40, ldc=64, outProcess=..., thread_id=3, num_threads=56, blocking_params=0x0)
    at /home/pytorch/third_party/fbgemm/src/Fbgemm.cc:173
#5  0x00007fffe2b1b6a7 in fbgemm::fbgemmConv<fbgemm::ReQuantizeOutput<true, (fbgemm::QuantizationGranularity)2, float, unsigned char, int, fbgemm::DoNothing<unsigned char, unsigned char> >, 2, int> (conv_p=..., activations=0x80105e8000 <error: Cannot access memory at address 0x80105e8000>, packed_weights=...,
    out=0x22552280 "\260\250\377\377\377\177", outBuffer=0x239afe40, outProcess=..., thread_id=3, num_threads=56, blocking_params=0x0)
    at /home/pytorch/third_party/fbgemm/src/FbgemmConv.cc:402
#6  0x00007fffdab77c6a in PackedConvWeight<2>::apply_impl<true>(at::Tensor const&, double, long)::{lambda(long, long)#2}::operator()(long, long) const (this=
    0x56ea5f0, begin=3, end=4) at /home/pytorch/aten/src/ATen/native/quantized/cpu/qconv.cpp:562
#7  0x00007fffdaba5b56 in at::internal::_ZN2at8internal15invoke_parallelIZN16PackedConvWeightILi2EE10apply_implILb1EEENS_6TensorERKS5_dlEUlllE0_EEvlllRKT_._omp_fn.0(void) () at /home/pytorch/aten/src/ATen/ParallelOpenMP.h:42
#8  0x00007ffff04dd78e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#9  0x00007ffff7fa6609 in start_thread () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007ffff7d71133 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6
```

**Comment by jerryzh168** [comment]
could you show the full code/changes? Otherwise I don't know what is happening just by looking at error messages
