### ISSUE TITLE
Import torch will lead to crash on rocm 5.6 with RX7900 XTX GPU installed

### ISSUE THREAD

**Issue by nanamiwang** [pytorch/pytorch#104415]
### 🐛 Describe the bug

OS: UBUNTU server 22.04
GPU: RX7900 XTX
rocm version: 5.6
pytorch version: nightly build for rocm 5.5
Python program crashed in librocfft.so while importing torch.

```
nanami@nanami-ai:~$ python3
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
nanami@nanami-ai:~$ gdb python3
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) r
Starting program: /usr/bin/python3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352546112) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352546112) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737352546112) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737352546112, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fff72ea2bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fff72eae24c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fff72eae2b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fff72eae518 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fff72ea27cc in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7270b77 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /home/nanami/.local/lib/python3.10/site-packages/torch/lib/libtorch.so
#11 0x00007fff38df33fe in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_bracket_expression() () from /opt/rocm/lib/librocfft.so.0
#12 0x00007fff38defdee in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_atom() () from /opt/rocm/lib/librocfft.so.0
#13 0x00007fff38def2cd in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative() () from /opt/rocm/lib/librocfft.so.0
#14 0x00007fff38ded129 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_disjunction() () from /opt/rocm/lib/librocfft.so.0
#15 0x00007fff38decaa4 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type) ()
   from /opt/rocm/lib/librocfft.so.0
#16 0x00007fff38dec823 in std::enable_if<__is_contiguous_iter<char const*>::value, std::shared_ptr<std::__detail::_NFA<std::__cxx11::regex_traits<char> > const> >::type std::__detail::__compile_nfa<std::__cxx11::regex_traits<char>, char const*>(char const*, char const*, std::__cxx11::regex_traits<char>::locale_type const&, std::regex_constants::syntax_option_type) () from /opt/rocm/lib/librocfft.so.0
#17 0x00007fff38deabb8 in std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex(char const*, std::regex_constants::syntax_option_type) () from /opt/rocm/lib/librocfft.so.0
#18 0x00007fff38e0b86b in _GLOBAL__sub_I_solution_map.cpp () from /opt/rocm/lib/librocfft.so.0
#19 0x00007ffff7fc947e in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe438, env=env@entry=0x7fffffffe448) at ./elf/dl-init.c:70
#20 0x00007ffff7fc9568 in call_init (env=0x7fffffffe448, argv=0x7fffffffe438, argc=1, l=<optimized out>) at ./elf/dl-init.c:33
#21 _dl_init (main_map=0x555555d08680, argc=1, argv=0x7fffffffe438, env=0x7fffffffe448) at ./elf/dl-init.c:117
#22 0x00007ffff7d74c85 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:182
#23 0x00007ffff7fd0ff6 in dl_open_worker (a=0x7fffffffbcb0) at ./elf/dl-open.c:808
#24 dl_open_worker (a=a@entry=0x7fffffffbcb0) at ./elf/dl-open.c:771
#25 0x00007ffff7d74c28 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#26 0x00007ffff7fd134e in _dl_open (file=<optimized out>, mode=-2147483646, caller_dlopen=0x5555557b9f3f, nsid=-2, argc=1, argv=<optimized out>, env=0x7fffffffe448) at ./elf/dl-open.c:883
#27 0x00007ffff7c906bc in dlopen_doit (a=a@entry=0x7fffffffbf20) at ./dlfcn/dlopen.c:56
#28 0x00007ffff7d74c28 in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffbe80, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#29 0x00007ffff7d74cf3 in __GI__dl_catch_error (objname=0x7fffffffbed8, errstring=0x7fffffffbee0, mallocedp=0x7fffffffbed7, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:227
#30 0x00007ffff7c901ae in _dlerror_run (operate=operate@entry=0x7ffff7c90660 <dlopen_doit>, args=args@entry=0x7fffffffbf20) at ./dlfcn/dlerror.c:138
#31 0x00007ffff7c90748 in dlopen_implementation (dl_caller=<optimized out>, mode=<optimized out>, file=<optimized out>) at ./dlfcn/dlopen.c:71
#32 ___dlopen (file=<optimized out>, mode=<optimized out>) at ./dlfcn/dlopen.c:81
#33 0x00005555557b9f3f in ?? ()
#34 0x00005555557b8437 in ?? ()
#35 0x00005555556b1749 in ?? ()
#36 0x000055555569bd87 in _PyEval_EvalFrameDefault ()
#37 0x00005555556b14ec in _PyFunction_Vectorcall ()
#38 0x000055555569f75a in _PyEval_EvalFrameDefault ()
#39 0x00005555556b14ec in _PyFunction_Vectorcall ()
#40 0x0000555555699c14 in _PyEval_EvalFrameDefault ()
#41 0x00005555556b14ec in _PyFunction_Vectorcall ()
#42 0x0000555555699a1d in _PyEval_EvalFrameDefault ()
#43 0x00005555556b14ec in _PyFunction_Vectorcall ()
#44 0x0000555555699a1d in _PyEval_EvalFrameDefault ()
#45 0x00005555556b14ec in _PyFunction_Vectorcall ()
#46 0x0000555555699a1d in _PyEval_EvalFrameDefault ()
#47 0x00005555556b14ec in _PyFunction_Vectorcall ()
#48 0x00005555556b0914 in ?? ()
#49 0x00005555556c682f in _PyObject_CallMethodIdObjArgs ()
#50 0x00005555556c4a58 in PyImport_ImportModuleLevelObject ()
#51 0x000055555569c6b3 in _PyEval_EvalFrameDefault ()
#52 0x0000555555696176 in ?? ()
#53 0x000055555578bc56 in PyEval_EvalCode ()
--Type <RET> for more, q to quit, c to continue without paging--
#54 0x000055555579193d in ?? ()
#55 0x00005555556b1749 in ?? ()
#56 0x000055555569bd87 in _PyEval_EvalFrameDefault ()
#57 0x00005555556b14ec in _PyFunction_Vectorcall ()
#58 0x000055555569f75a in _PyEval_EvalFrameDefault ()
#59 0x00005555556b14ec in _PyFunction_Vectorcall ()
#60 0x0000555555699c14 in _PyEval_EvalFrameDefault ()
#61 0x00005555556b14ec in _PyFunction_Vectorcall ()
#62 0x0000555555699a1d in _PyEval_EvalFrameDefault ()
#63 0x00005555556b14ec in _PyFunction_Vectorcall ()
#64 0x0000555555699a1d in _PyEval_EvalFrameDefault ()
#65 0x00005555556b14ec in _PyFunction_Vectorcall ()
#66 0x00005555556b0914 in ?? ()
#67 0x00005555556c682f in _PyObject_CallMethodIdObjArgs ()
#68 0x00005555556c4a58 in PyImport_ImportModuleLevelObject ()
#69 0x000055555569c6b3 in _PyEval_EvalFrameDefault ()
#70 0x0000555555696176 in ?? ()
#71 0x000055555578bc56 in PyEval_EvalCode ()
#72 0x00005555557b8b18 in ?? ()
#73 0x00005555557b196b in ?? ()
#74 0x0000555555609b03 in ?? ()
#75 0x0000555555609790 in _PyRun_InteractiveLoopObject ()
#76 0x00005555557b7a68 in _PyRun_AnyFileObject ()
#77 0x00005555555f57e2 in PyRun_AnyFileExFlags ()
#78 0x00005555557a8e8f in Py_RunMain ()
#79 0x000055555577ebcd in Py_BytesMain ()
#80 0x00007ffff7c29d90 in __libc_start_call_main (main=main@entry=0x55555577eb90, argc=argc@entry=1, argv=argv@entry=0x7fffffffe438) at ../sysdeps/nptl/libc_start_call_main.h:58
#81 0x00007ffff7c29e40 in __libc_start_main_impl (main=0x55555577eb90, argc=1, argv=0x7fffffffe438, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe428)
    at ../csu/libc-start.c:392
#82 0x000055555577eac5 in _start ()

```

### Versions

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by nanamiwang** [comment]
Building pytorch from source under rcom 5.6 fixed this issue, we can close this now.
