### ISSUE TITLE
torch.compile failed when using dynamic input shapes on generation tasks.

### ISSUE THREAD

**Issue by jiqing-feng** [pytorch/pytorch#104515]
### 🐛 Describe the bug

torch.compile failed when using dynamic input shapes on generation tasks. It seems that related to this PR [103600](https://github.com/pytorch/pytorch/pull/103600) because the error disappear when I revert this change. 

Hi @eellison , would you please check it? Thanks!

BTW, the bug also exists when I use the newest version pytorch=2.1.0.dev20230702+cpu

Command: TORCHDYNAMO_REPORT_GUARD_FAILURES=1 TORCH_SHOW_CPP_STACKTRACES=1 OMP_NUM_THREADS=56 numactl -C 0-55 --membind 0 python3 xxx.py

Python script
```python
import argparse
import time
import torch
import torch._dynamo
torch._dynamo.config.dynamic_shapes = True
torch._dynamo.config.assume_static_by_default = False

from transformers import AutoModelForSeq2SeqLM, pipeline, AutoTokenizer

# torch._dynamo.config.log_level = logging.DEBUG
torch._dynamo.config.verbose = True

model_id = "google/flan-t5-base"

kwargs = dict(torch_dtype=torch.bfloat16, use_cache=True)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id, **kwargs)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = model.eval()

input_sentence = "It is done, and submitted. You can play 'Survival of the Tastiest' on Android, and on the web. Playing on the web works, but you have to simulate multiple touch for table moving and that can be a bit confusing. There is a lot I'd like to talk about. I will go through every topic, insted of making the typical what went right/wrong list. Concept Working over the theme was probably one of the hardest tasks which I had to face. Originally, I had an idea of what kind of game I wanted to develop, gameplay wise - something with a lot of enemies/actors, simple graphics, maybe set in space, controlled from a top-down view. I was confident that I could fit any theme around it. In the end, the problem with a theme like 'Evolution' in a game is that evolution is unassisted. It happens through several seemingly random mutations over time, with the most apt permutation surviving. This genetic car simulator is, in my opinion, a great example of actual evolution of a species facing a challenge. But is it a game? In a game, you need to control something to reach an objective. That control goes against what evolution is supposed to be like. If you allow the user to pick how to evolve something, it's not evolution anymore - it's the equivalent of intelligent design, the fable invented by creationists to combat the idea of evolution. Being agnostic and a Pastafarian, that's not something that rubbed me the right way. Hence, my biggest dillema when deciding what to create was not with what I wanted to create, but with what I did not. I didn't want to create an 'intelligent design' simulator and wrongly call it evolution. This is a problem, of course, every other contestant also had to face. And judging by the entries submitted, not many managed to work around it. I'd say the only real solution was through the use of artificial selection, somehow. So far, I haven't seen any entry using this at its core gameplay. Alas, this is just a fun competition and after a while I decided not to be as strict with the game idea, and"

generation_kwargs = dict(max_length=128, min_length=128, do_sample=False, num_beams=4, num_beam_groups=1, no_repeat_ngram_size=2)
print(input_sentence)
print(f"input tokens num is {len(tokenizer(input_sentence)['input_ids'])}")
inputs = tokenizer(input_sentence, return_tensors='pt')

with torch.no_grad():
    for i in range(8):
        pre = time.time()
        output = model.generate(**inputs, **generation_kwargs)
        print(f"eager eval time {i}: {time.time()-pre}")

print("Use torch compile model")
model.generate = torch.compile(model.generate, backend='inductor', dynamic=True)
with torch.no_grad():
    for i in range(8):
        pre = time.time()
        output_compile = model.generate(**inputs, **generation_kwargs)
        print(f"compile eval time {i}: {time.time()-pre}")
```

The bug is as follows
```
/home/jiqingfe/pytorch/torch/overrides.py:111: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/home/jiqingfe/pytorch/torch/overrides.py:112: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/home/jiqingfe/pytorch/torch/overrides.py:118: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/home/jiqingfe/pytorch/torch/overrides.py:119: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
[2023-07-02 18:14:59,638] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_11_1_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_11_0_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_10_1_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_10_0_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_9_1_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_9_0_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_8_1_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_8_0_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_7_1_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_7_0_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_6_1_
[2023-07-02 18:14:59,639] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_6_0_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_5_1_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_5_0_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_4_1_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_4_0_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_3_1_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_3_0_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_2_1_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_2_0_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_1_1_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_1_0_
[2023-07-02 18:14:59,640] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_0_1_
[2023-07-02 18:14:59,641] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_0_0_
[2023-07-02 18:14:59,641] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: ones_1
[2023-07-02 18:15:56,347] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_11_1_
[2023-07-02 18:15:56,347] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_11_0_
[2023-07-02 18:15:56,347] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_10_1_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_10_0_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_9_1_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_9_0_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_8_1_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_8_0_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_7_1_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_7_0_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_6_1_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_6_0_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_5_1_
[2023-07-02 18:15:56,348] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_5_0_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_4_1_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_4_0_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_3_1_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_3_0_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_2_1_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_2_0_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_1_1_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_1_0_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_0_1_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: l_past_key_values_0_0_
[2023-07-02 18:15:56,349] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: ones_1
[2023-07-02 18:16:50,222] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (64)
   function: '_get_generated_ngrams' (/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/logits_process.py:450)
   reasons:    reasons: set(L['banned_ngrams'].keys()) == {(51,), (118,), (31,), (2284,), (162,), (467,), (0,), (3,), (9,), (482,), (12,), (497,), (1095,), (24,), (27,), (179,)}

to diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
[2023-07-02 18:16:59,140] torch._inductor.scheduler: [CRITICAL] Error in codegen for ComputedBuffer(name='buf7', layout=MutationLayout('cpu', torch.bfloat16, size=[s12], stride=[1]), data=Scatter(device=dev
ice(type='cpu'), dtype=torch.bfloat16, inner_fn=<function BaseView.make_loader.<locals>.loader at 0x7f3006837790>, ranges=[2], output_indexer=<function index_put_impl_.<locals>.output_indexer at 0x7f3007aeb
310>, scatter_mode=None))
Traceback (most recent call last):
  File "/home/jiqingfe/optimum-script/test_hf_compile_jira.py", line 41, in <module>
    output_compile = model.generate(**inputs, **generation_kwargs)
  File "/home/jiqingfe/pytorch/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/utils.py", line 1246, in generate
    self._validate_model_class()
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/utils.py", line 1253, in <resume in generate>
    new_generation_config = GenerationConfig.from_model_config(self.config)
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/utils.py", line 1604, in <resume in generate>
    return self.beam_search(
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/utils.py", line 2837, in beam_search
    if len(stopping_criteria) == 0:
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/utils.py", line 2922, in <resume in beam_search>
    next_token_scores_processed = logits_processor(input_ids, next_token_scores)
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 492, in __call__
    banned_batch_tokens = _calc_banned_ngram_tokens(self.ngram_size, input_ids, num_batch_hypotheses, cur_len)
  File "/home/jiqingfe/pytorch/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/jiqingfe/pytorch/torch/_dynamo/convert_frame.py", line 526, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/jiqingfe/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/home/jiqingfe/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/jiqingfe/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jiqingfe/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/home/jiqingfe/pytorch/torch/_dynamo/symbolic_convert.py", line 2026, in run
    super().run()
  File "/home/jiqingfe/pytorch/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/home/jiqingfe/pytorch/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiqingfe/pytorch/torch/_dynamo/symbolic_convert.py", line 2114, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/jiqingfe/pytorch/torch/_dynamo/output_graph.py", line 763, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/jiqingfe/pytorch/torch/_dynamo/output_graph.py", line 859, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/jiqingfe/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_dynamo/output_graph.py", line 915, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/jiqingfe/pytorch/torch/_dynamo/output_graph.py", line 911, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/jiqingfe/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/jiqingfe/pytorch/torch/__init__.py", line 1530, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/jiqingfe/pytorch/torch/_inductor/compile_fx.py", line 912, in compile_fx
    return aot_autograd(
  File "/home/jiqingfe/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_functorch/aot_autograd.py", line 3713, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/jiqingfe/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_functorch/aot_autograd.py", line 3252, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/jiqingfe/pytorch/torch/_functorch/aot_autograd.py", line 2068, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/jiqingfe/pytorch/torch/_functorch/aot_autograd.py", line 2248, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/jiqingfe/pytorch/torch/_functorch/aot_autograd.py", line 1522, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/home/jiqingfe/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_inductor/compile_fx.py", line 855, in fw_compiler_base
    return inner_compile(
  File "/home/jiqingfe/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/jiqingfe/pytorch/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
  File "/home/jiqingfe/miniconda3/envs/trace/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/jiqingfe/pytorch/torch/_inductor/compile_fx.py", line 46, in newFunction
    return old_func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/jiqingfe/pytorch/torch/_inductor/graph.py", line 886, in compile_to_fn
    return self.compile_to_module().call
  File "/home/jiqingfe/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_inductor/graph.py", line 860, in compile_to_module
    code, linemap = self.codegen()
  File "/home/jiqingfe/pytorch/torch/_inductor/graph.py", line 811, in codegen
    self.scheduler.codegen()
  File "/home/jiqingfe/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_inductor/scheduler.py", line 1383, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/home/jiqingfe/pytorch/torch/_inductor/codegen/cpp.py", line 2566, in codegen_nodes
    cpp_kernel_proxy.codegen_nodes(nodes)
  File "/home/jiqingfe/pytorch/torch/_inductor/codegen/cpp.py", line 2481, in codegen_nodes
    codegen_kernel(
  File "/home/jiqingfe/pytorch/torch/_inductor/codegen/cpp.py", line 2373, in codegen_kernel
    run(kernel)
  File "/home/jiqingfe/pytorch/torch/_inductor/codegen/cpp.py", line 2390, in run
    node.run(vars, reduction_vars)
  File "/home/jiqingfe/pytorch/torch/_inductor/scheduler.py", line 443, in run
    self.codegen(index_vars)
  File "/home/jiqingfe/pytorch/torch/_inductor/scheduler.py", line 465, in codegen
    self._body(*index_vars)
  File "/home/jiqingfe/pytorch/torch/_inductor/ir.py", line 4511, in __call__
    result = self.root_block()
  File "/home/jiqingfe/pytorch/torch/_inductor/ir.py", line 4620, in __call__
    return InterpreterShim(graph, submodules).run(V.get_ops_handler())
  File "/home/jiqingfe/pytorch/torch/_inductor/ir.py", line 4413, in run
    return super().run(*args, **kwargs)
  File "/home/jiqingfe/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/home/jiqingfe/pytorch/torch/_inductor/ir.py", line 4409, in run_node
    return super().run_node(n)
  File "/home/jiqingfe/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/jiqingfe/pytorch/torch/fx/interpreter.py", line 289, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/home/jiqingfe/pytorch/torch/_inductor/sizevars.py", line 556, in store
    return self._inner.store(name, self._simplify(index), value, mode=mode)
  File "/home/jiqingfe/pytorch/torch/_inductor/codegen/common.py", line 824, in store
    return self.store(name, index, value, mode=mode)
  File "/home/jiqingfe/pytorch/torch/_inductor/codegen/cpp.py", line 1390, in store
    assert index.has(tiling_var)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError:


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

### Versions

Collecting environment information...                                                                                                                                                                         PyTorch version: 2.1.0a0+git1b16ac7                                                                                                                                                                           Is debug build: False                                                                                                                                                                                         CUDA used to build PyTorch: None                                                                                                                                                                              ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.28

Python version: 3.9.16 (main, May 15 2023, 23:46:34)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.16.0-rc8-intel-next-01534-g53cb5f883cf7-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              224
On-line CPU(s) list: 0-223
Thread(s) per core:  2
Core(s) per socket:  56
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               143
Model name:          Genuine Intel(R) CPU 0000%@
Stepping:            3
CPU MHz:             1900.000
CPU max MHz:         1900.0000
CPU min MHz:         800.0000
BogoMIPS:            3800.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
L3 cache:            107520K
NUMA node0 CPU(s):   0-55,112-167
NUMA node1 CPU(s):   56-111,168-223
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req hfi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm uintr avx512_vp2intersect md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.0+git1f1ee89
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] torch==2.1.0a0+git1b16ac7
[conda] intel-extension-for-pytorch 2.1.0+git1f1ee89          pypi_0    pypi
[conda] mkl                       2023.1.0         h6d00ec8_46342
[conda] mkl-include               2023.1.0                 pypi_0    pypi
[conda] mkl-static                2023.1.0                 pypi_0    pypi
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.1.0a0+git1b16ac7           dev_0    <develop>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by jiqing-feng** [comment]
Hi @ezyang . Thanks for your reply. I tried 
```
torch._dynamo.config.dynamic_shapes = True
torch._dynamo.config.assume_static_by_default = True
torch._dynamo.config.automatic_dynamic_shapes = True
```
, but the error still exists. I also tried to delete these configs and nothing changed, the error is still the same.

**Comment by XiaobingSuper** [comment]
it seems cpu backend issue.
