### ISSUE TITLE
Verbose exception on deleting multiprocessed `DataLoaderIter`

### ISSUE THREAD

**Issue by kl2792** [pytorch/pytorch#10450]
## Issue description

Ignored exception ConnectionResetError when deleting `DataLoaderIter` on every training epoch when using num_workers > 0.

## Code example

Reproduction: cannot create code for minimal reproduction at the moment. I get this error at the end of every epoch when using the torchbearer training package, and my model uses GPU.

Stack trace:
```
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x2aab643fe278>>
Traceback (most recent call last):
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/connection.py", line 737, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/rigel/katt/users/kl2792/.anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

## System Info
- PyTorch or Caffe2:  pytorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: linux 
- PyTorch version: 0.4.1
- Python version: 3.6
- CUDA/cuDNN version: 9.0
- GPU models and configuration: see code
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by SsnL** [comment]
This has been fixed by #10366 . Thanks for reporting.
