### ISSUE TITLE
Specifying kwargs for torch.pow causes graph break

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#104656]
### 🐛 Describe the bug

see title

### Error logs

```py
import torch

@torch.compile(backend='eager', fullgraph=True)
def fn(x, y):
    return torch.pow(self=x, exponent=y)

x = torch.tensor(2.)
y = torch.tensor(3.)
fn(x, y)
```
gives
```
Traceback (most recent call last):
  File "/raid/rzou/pt/debug-cpu2/torch/_dynamo/utils.py", line 1339, in run_node
    return node.target(*args, **kwargs)
  File "/raid/rzou/pt/debug-cpu2/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/raid/rzou/pt/debug-cpu2/torch/_subclasses/fake_tensor.py", line 1160, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/raid/rzou/pt/debug-cpu2/torch/_subclasses/fake_tensor.py", line 1380, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/raid/rzou/pt/debug-cpu2/torch/_subclasses/fake_tensor.py", line 469, in local_scalar_dense
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default
```

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by eellison** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/84597

**Comment by eellison** [comment]
@zou3519 can we close this as a dupe of https://github.com/pytorch/pytorch/issues/84597 ?

**Comment by zou3519** [comment]
Yup it's dupe
