### ISSUE TITLE
Failure in optimize_for_mobile when using conv1d(..., padding='same')

### ISSUE THREAD

**Issue by gtyukasz** [pytorch/pytorch#104606]
### 🐛 Describe the bug

If a module uses `torch.nn.functional.conv1d` with the argument `padding='same'`, `optimize_for_mobile` fails. If an integral padding argument is provided, it works as expected.

**Example:**
```python
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile


class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input: torch.Tensor, weight: torch.Tensor) -> torch.Tensor:
        return torch.nn.functional.conv1d(input, weight, padding='same')


module = TestModule()
module.eval()
scripted_module = torch.jit.script(module)
mobile_module = optimize_for_mobile(scripted_module)
```

**Output:**
```
Traceback (most recent call last):
  File "/Users/gtyukasz/TorchFail/torch_fail.py", line 16, in <module>
    mobile_module = optimize_for_mobile(scripted_module)
  File "/Users/gtyukasz/TorchFail/venv/lib/python3.10/site-packages/torch/utils/mobile_optimizer.py", line 62, in optimize_for_mobile
    optimized_cpp_module = torch._C._jit_pass_optimize_for_mobile(
RuntimeError: isList() INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/ivalue_inl.h":2034, please report a bug to PyTorch. Expected GenericList but got String
```

### Versions

```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] torch==2.0.1
[conda] Could not collect
```

**Comment by davidradl** [comment]
I can recreate. It also fails with the same error with padding='valid'. padding=1 works.

**Comment by digantdesai** [comment]
> padding controls the amount of padding applied to the input. It can be either a string {‘valid’, ‘same’} or an int / a tuple of ints giving the amount of implicit padding applied on both sides.

Right, internally for performance reasons, conv1d gets converted to a conv2d, and this arg gets updated as well. During that, as the error says only list of ints is supported ATM, not a string.
