### ISSUE TITLE
torch.jit.trace says "Arguments for call are invalid" on torch.ops.aten.sub(3, x, alpha=3)

### ISSUE THREAD

**Issue by mgehre-amd** [pytorch/pytorch#104732]
### 🐛 Describe the bug

The following model runs fine in pytorch but fails in `torch.jit.script`:
```python
import torch

class TestModule(torch.nn.Module):
    def forward(self, x):
        y = torch.ops.aten.sub(3, x, alpha=3)
        return y

args = torch.tensor([1, 0, -10, 255, 256], dtype=torch.int)
model = TestModule()

print("Running Torch via python")
model(args) # Fine
torch.jit.script(model) # Error
```
with 
```
Traceback (most recent call last):
  File "", line 32, in <module>
    torch.jit.script(model) # Error
  File "torch/jit/_script.py", line 1284, in script
    return torch.jit._recursive.create_script_module(
  File "torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::sub.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor:
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'int'.
  
  aten::sub.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> Tensor:
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'int'.
  
  aten::sub.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> Tensor(a!):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'int'.
  
  aten::sub.Scalar_out(Tensor self, Scalar other, Scalar alpha=1, *, Tensor(a!) out) -> Tensor(a!):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'int'.
  
  aten::sub.int(int a, int b) -> int:
  Keyword argument alpha unknown.
  
  aten::sub.complex(complex a, complex b) -> complex:
  Expected a value of type 'complex' for argument 'a' but instead found type 'int'.
  
  aten::sub.float(float a, float b) -> float:
  Expected a value of type 'float' for argument 'a' but instead found type 'int'.
  
  aten::sub.int_complex(int a, complex b) -> complex:
  Keyword argument alpha unknown.
  
  aten::sub.complex_int(complex a, int b) -> complex:
  Expected a value of type 'complex' for argument 'a' but instead found type 'int'.
  
  aten::sub.float_complex(float a, complex b) -> complex:
  Expected a value of type 'float' for argument 'a' but instead found type 'int'.
  
  aten::sub.complex_float(complex a, float b) -> complex:
  Expected a value of type 'complex' for argument 'a' but instead found type 'int'.
  
  aten::sub.int_float(int a, float b) -> float:
  Keyword argument alpha unknown.
  
  aten::sub.float_int(float a, int b) -> float:
  Expected a value of type 'float' for argument 'a' but instead found type 'int'.
  
  aten::sub(Scalar a, Scalar b) -> Scalar:
  Keyword argument alpha unknown.
  
  sub(float a, Tensor b) -> Tensor:
  Expected a value of type 'float' for argument 'a' but instead found type 'int'.
  
  sub(int a, Tensor b) -> Tensor:
  Keyword argument alpha unknown.
  
  sub(complex a, Tensor b) -> Tensor:
  Expected a value of type 'complex' for argument 'a' but instead found type 'int'.
```

This came up while we were ingesting torch decompositions (for `torch.ops.aten.rsub`) into `torch.jit.script`.

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230705+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 15.0.7
CMake version: version 3.26.3
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-166-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC Processor
CPU family:                      23
Model:                           1
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       2
Stepping:                        2
BogoMIPS:                        5988.74
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl xtopology cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       512 KiB (16 instances)
L1i cache:                       1 MiB (16 instances)
L2 cache:                        8 MiB (16 instances)
L3 cache:                        16 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] iree-torch==0.0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0.dev20230705+cpu
[pip3] torchvision==0.16.0.dev20230612+cpu
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
