### ISSUE TITLE
Error reporting uses formal parameter names of downstream C++ function

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#104739]
### 🐛 Describe the bug

When calling sdpa, I get the error message `RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 2` -- there are no parameters a and b in sdpa.  Likely it's the formal parameter names of a function called from inside sdpa, which does not relate to the visible Python call stack.  (Partial stack backtrace below.) 

Can we / Should we check parameters inside sdpa and use proper sdpa formal parameter names?  I think this behavior has shown for other functions, although getting the order of tensor dimensions right when updating arbitrary transformer code feels an order of magnitude harder.  No concern about having to do that per se, but it would be nice to have errors expressed in terms of sdpa to help debug.

```
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytorch/text/fb/nn/modules/transformer.py", line 69, in forward
    attention = self.attention(input, key_padding_mask)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytorch/text/fb/nn/modules/multihead_attention.py", line 320, in forward
    attn = F.scaled_dot_product_attention(q, k, v, key_padding_mask, self.dropout_p, False);
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 2
```

### Versions

fbcode trunk

**Comment by janeyx99** [comment]
cc @drisspg

**Comment by drisspg** [comment]
Depends on where the error is coming from, if it is coming the in the composite path then it would be pretty hard to pass the names down to one of the called functions.

setting `TORCH_SHOW_CPP_STACKTRACES=1` can help pinpoint the error

**Comment by mikekgfb** [comment]
Yes, I don't think we have a way to pass names that should be reported with formal parameters to give "python-level correct" error names.  The two options I see are either duplicating the check at the beginning of SDPA, or... just living with it
(There are also the TORCH_SHOW_CPP_STACKTRACES=1 which helps diagnose, but at the end of the day doesn't help debug of Python code)

```
hg up D47243587
export  TORCH_SHOW_CPP_STACKTRACES=1 
buck2 run '@fbcode//mode/dev' fbcode//careml/nlp/toolkit:tests -- --exact 'careml/nlp/toolkit:tests - test_XLMRoBERTaEncoderWithEmbedding (careml.nlp.toolkit.__tests__.test_xlmroberta_encoder.Test)'
# use buck2 run to get full output 
[...]
======================================================================
ERROR: test_XLMRoBERTaEncoderWithEmbedding (careml.nlp.toolkit.__tests__.test_xlmroberta_encoder.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/careml/nlp/toolkit/__tests__/test_xlmroberta_encoder.py", line 18, in test_XLMRoBERTaEncoderWithEmbedding
    encodings, sent_embs = model.encoder(sent_one_tensors)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/careml/nlp/toolkit/encoders/pretrained_xlmr_encoder.py", line 246, in forward
    embedding = self.encoder(tokens[0])
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytext/models/representations/transformer/sentence_encoder.py", line 43, in forward
    all_layers = self.extract_features(tokens)  # list of [T x B x C]
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytext/models/representations/transformer/sentence_encoder.py", line 52, in extract_features
    return self.transformer(tokens)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytorch/text/fb/nn/modules/transformer.py", line 153, in forward
    encoded = layer(encoded, padding_mask)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytorch/text/fb/nn/modules/transformer.py", line 69, in forward
    attention = self.attention(input, key_padding_mask)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/mikekg/fbsource/buck-out/v2/gen/fbcode/46d412658cf1d160/careml/nlp/toolkit/__tests__/tests#link-tree/pytorch/text/fb/nn/modules/multihead_attention.py", line 320, in forward
    attn = F.scaled_dot_product_attention(q, k, v, key_padding_mask, self.dropout_p, False);
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 2
Exception raised from infer_size_impl at fbcode/caffe2/aten/src/ATen/ExpandUtils.cpp:35 (most recent call first):
# 0  c10::get_backtrace[abi:cxx11](unsigned long, unsigned long, bool)
# 1  c10::(anonymous namespace)::GetFetchStackTrace[abi:cxx11]()::$_1::operator()[abi:cxx11]() const
# 2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::__invoke_impl<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::(anonymous namespace)::GetFetchStackTrace()::$_1&>(std::__invoke_other, c10::(anonymous namespace)::GetFetchStackTrace()::$_1&)
# 3  std::enable_if<is_invocable_r_v<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::(anonymous namespace)::GetFetchStackTrace()::$_1&>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type std::__invoke_r<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::(anonymous namespace)::GetFetchStackTrace()::$_1&>(c10::(anonymous namespace)::GetFetchStackTrace()::$_1&)
# 4  std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (), c10::(anonymous namespace)::GetFetchStackTrace()::$_1>::_M_invoke(std::_Any_data const&)
# 5  std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const
# 6  c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
# 7  c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 8  c10::SmallVector<long, 5u> at::(anonymous namespace)::infer_size_impl<c10::SmallVector<long, 5u>, c10::ArrayRef<long> >(c10::ArrayRef<long>, c10::ArrayRef<long>)
# 9  at::infer_size_dimvector(c10::ArrayRef<long>, c10::ArrayRef<long>)
# 10 at::TensorIteratorBase::compute_shape(at::TensorIteratorConfig const&)
# 11 at::TensorIteratorBase::build(at::TensorIteratorConfig&)
# 12 at::TensorIteratorBase::build_borrowing_binary_op(at::TensorBase const&, at::TensorBase const&, at::TensorBase const&)
# 13 at::meta::structured_add_Tensor::meta(at::Tensor const&, at::Tensor const&, c10::Scalar const&)
# 14 at::(anonymous namespace)::wrapper_CPU_add__Tensor(at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 15 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (at::Tensor&, at::Tensor const&, c10::Scalar const&), &at::(anonymous namespace)::wrapper_CPU_add__Tensor>, at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, at::Tensor const&, c10::Scalar const&> >, at::Tensor& (at::Tensor&, at::Tensor const&, c10::Scalar const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 16 at::Tensor& c10::callUnboxedKernelFunction<at::Tensor&, at::Tensor&, at::Tensor const&, c10::Scalar const&>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 17 at::Tensor& c10::Dispatcher::redispatch<at::Tensor&, at::Tensor&, at::Tensor const&, c10::Scalar const&>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, at::Tensor const&, c10::Scalar const&)> const&, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&) const
# 18 at::_ops::add__Tensor::redispatch(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 19 torch::ADInplaceOrView::(anonymous namespace)::add__Tensor(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 20 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&), &torch::ADInplaceOrView::(anonymous namespace)::add__Tensor>, at::Tensor&, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&> >, at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 21 at::Tensor& c10::callUnboxedKernelFunction<at::Tensor&, at::Tensor&, at::Tensor const&, c10::Scalar const&>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 22 at::Tensor& c10::Dispatcher::redispatch<at::Tensor&, at::Tensor&, at::Tensor const&, c10::Scalar const&>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, at::Tensor const&, c10::Scalar const&)> const&, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&) const
# 23 at::_ops::add__Tensor::redispatch(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 24 at::redispatch::add_(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 25 torch::autograd::VariableType::(anonymous namespace)::add__Tensor(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 26 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&), &torch::autograd::VariableType::(anonymous namespace)::add__Tensor>, at::Tensor&, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&> >, at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 27 at::Tensor& c10::callUnboxedKernelFunction<at::Tensor&, at::Tensor&, at::Tensor const&, c10::Scalar const&>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 28 at::_ops::add__Tensor::call(at::Tensor&, at::Tensor const&, c10::Scalar const&)
# 29 at::Tensor::add_(at::Tensor const&, c10::Scalar const&) const
# 30 at::native::_scaled_dot_product_attention_math(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>)
# 31 at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd___scaled_dot_product_attention_math(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>)
# 32 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<std::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd___scaled_dot_product_attention_math>, std::tuple<at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double> > >, std::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>)
# 33 std::tuple<at::Tensor, at::Tensor> c10::callUnboxedKernelFunction<std::tuple<at::Tensor, at::Tensor>, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double> >(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double&&, bool&&, c10::optional<at::Tensor> const&, c10::optional<double>&&)
# 34 at::_ops::_scaled_dot_product_attention_math::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>)
# 35 at::_scaled_dot_product_attention_math(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<at::Tensor> const&, c10::optional<double>)
# 36 at::native::scaled_dot_product_attention(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>)
# 37 at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__scaled_dot_product_attention(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>)
# 38 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__scaled_dot_product_attention>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double> > >, at::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>)
# 39 at::Tensor c10::callUnboxedKernelFunction<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double> >(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double&&, bool&&, c10::optional<double>&&)
# 40 at::_ops::scaled_dot_product_attention::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>)
# 41 at::scaled_dot_product_attention(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>)
# 42 torch::autograd::THPVariable_scaled_dot_product_attention(_object*, _object*, _object*)::$_124::operator()(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, double, bool, c10::optional<double>) const
# 43 torch::autograd::THPVariable_scaled_dot_product_attention(_object*, _object*, _object*)
# 44 cfunction_call(_object*, _object*, _object*) [clone .__uniq.281047882695835599676768160755749362799]
# 45 _PyObject_MakeTpCall
# 46 call_function(_ts*, PyTraceInfo*, _object***, long, _object*) [clone .__uniq.79849310599369217189729546442812793949]
# 47 _PyEval_EvalFrameDefault
# 48 _PyEval_Vector
# 49 method_vectorcall(_object*, _object* const*, unsigned long, _object*) [clone .__uniq.243338978568352371442406765225626566013] [clone .llvm.9727171595848872535]
# 50 _PyEval_EvalFrameDefault
# 51 _PyEval_Vector
# 52 method_vectorcall(_object*, _object* const*, unsigned long, _object*) [clone .__uniq.243338978568352371442406765225626566013] [clone .llvm.9727171595848872535]
# 53 _PyEval_EvalFrameDefault
# 54 _PyEval_Vector
# 55 _PyObject_Call_Prepend
# 56 slot_tp_call(_object*, _object*, _object*) [clone .__uniq.235726554139783955843240177532338160225]
# 57 _PyObject_MakeTpCall
# 58 call_function(_ts*, PyTraceInfo*, _object***, long, _object*) [clone .__uniq.79849310599369217189729546442812793949]
# 59 _PyEval_EvalFrameDefault
# 60 _PyEval_Vector
# 61 method_vectorcall(_object*, _object* const*, unsigned long, _object*) [clone .__uniq.243338978568352371442406765225626566013] [clone .llvm.9727171595848872535]
# 62 _PyEval_EvalFrameDefault
# 63 _PyEval_Vector
# 64 method_vectorcall(_object*, _object* const*, unsigned long, _object*) [clone .__uniq.243338978568352371442406765225626566013] [clone .llvm.9727171595848872535]
# 65 _PyEval_EvalFrameDefault
# 66 _PyEval_Vector
# 67 _PyObject_Call_Prepend
# 68 slot_tp_call(_object*, _object*, _object*) [clone .__uniq.235726554139783955843240177532338160225]
# 69 _PyObject_MakeTpCall
# 70 call_function(_ts*, PyTraceInfo*, _object***, long, _object*) [clone .__uniq.79849310599369217189729546442812793949]
# 71 _PyEval_EvalFrameDefault
```

**Comment by mikekgfb** [comment]
To add insult to injury we add up in `sdpa_math()`.   

Also, D47243587 needs some work to handle key padding mask correctly as NT.

**Comment by drisspg** [comment]
Yeah my reading of the tea leaves on this one is add_ only happends when a mask is present in the math path. I don't know if regular users would be able to get this though
