### ISSUE TITLE
[Caffe2] Multithreading in Caffe2

### ISSUE THREAD

**Issue by minthetkhine** [pytorch/pytorch#10471]
I am trying to implement a multithreading approach in Caffe2, but I got these errors:

```
E0809 13:54:40.390210 101295 net_async_scheduling.cc:213] Detected concurrent runs
E0809 13:54:40.390240 101295 net.h:57] Failed to execute async run
Exception in thread thread2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alfred/catkin_ws/src/live_pytorch/src/segmenter.py", line 119, in worker
    densepose(data)
  File "/home/alfred/catkin_ws/src/live_pytorch/src/segmenter.py", line 77, in densepose
    cls_boxes, cls_segms, cls_keyps, cls_bodys = infer_engine.im_detect_all(model, cv_image, None, timers=timers)
  File "/home/alfred/exp/DensePose/detectron/core/test.py", line 58, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/alfred/exp/DensePose/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1111] success. Error running net generalized_rcnn 
```

May I know why I get these errors?

**Comment by ilia-cher** [comment]
"Detected concurrent runs" means that you're launching net's run before the previous run is finished. Caffe2 does not support concurrent net's runs on the same net object. In case you need concurrent net's runs you need to maintain multiple net objects.

**Comment by minthetkhine** [comment]
Thank you. So may I know how I can make multiple net objects of the same net in each thread? I assume that right now, everything is happening in the "default" workspace, and so I think I might have to create multiple workspaces and assign each workspace a copy of the same net?

**Comment by ilia-cher** [comment]
That would be one of the ways to do this, yes.

**Comment by beichen2012** [comment]
> "Detected concurrent runs" means that you're launching net's run before the previous run is finished. Caffe2 does not support concurrent net's runs on the same net object. In case you need concurrent net's runs you need to maintain multiple net objects.

I have maintain multiple net ojbects and multiple workspace ojbects, but the single net forward (workspace.RunNet()) in multi-thread is much slower than single thread.
