### ISSUE TITLE
A problem during the model training process

### ISSUE THREAD

**Issue by PhyllisJi** [pytorch/pytorch#104862]
### 🐛 Describe the bug

There is such a model:
```
import torch
import torch.nn as nn


class TestNet(nn.Module):
    def __init__(self, num_classes: int = 1000, dropout: float = 0.5):
        super(TestNet, self).__init__()
        self.conv1 = torch.nn.Conv2d(in_channels=3, out_channels=64, kernel_size=8, stride=4, padding=2)
        self.relu1 = torch.nn.ReLU(inplace=True)
        self.pool1 = torch.nn.MaxPool2d(kernel_size=3, stride=2, dilation=6)
        self.conv2 = torch.nn.Conv2d(in_channels=64, out_channels=192, kernel_size=5, padding=2, bias=False)
        self.relu2 = torch.nn.ReLU(inplace=False)
        self.pool2 = torch.nn.MaxPool2d(kernel_size=3, stride=(2, 2))
        self.conv3 = torch.nn.Conv2d(in_channels=192, out_channels=384, kernel_size=3, padding=1, groups=3)
        self.relu3 = torch.nn.ReLU6()
        self.conv4 = torch.nn.LogSoftmax()
        self.relu4 = torch.nn.ReLU(inplace=True)
    def forward(self, x):
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.relu2(x)
        x = self.pool2(x)
        x = self.conv3(x)
        x = self.relu3(x)
        x = self.conv4(x)
        x = self.relu4(x)
        return x
```

Please ignore the peculiar structure and output performance of this model for now, as it is a test neural network constructed just for reproducing this problem. When I train it using the CIFAR-10 dataset, (including the input, output, loss computation, and backward), I encounter the following error. 

error info:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[6], line 1
----> 1 t.train(net, 'alexnet')

File D:\PythonProjects/pytorch_v2/algorithms\train.py:281, in Trainer.train(self, net_to_train, net_name)
    279 # loss calculation and backward:
    280 loss = criterion(outputs, labels)
--> 281 loss.backward()
    282 optimizer.step()
    283 running_loss += loss.item()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_tensor.py:487, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 384, 10, 10]], which is output 0 of LogSoftmaxBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
By the way, the shape of output tensor has been handled, so it's just okay to compute the loss with output and labels.

Then I execute ``torch.autograd.set_detect_anomaly(True)`` as this hint told me, and the error message changed as below.

error info:
```
C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\__init__.py:200: UserWarning: Error detected in LogSoftmaxBackward0. Traceback of forward call that caused the error:
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\Scripts\ipython.exe\__main__.py", line 7, in <module>
    sys.exit(start_ipython())
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\__init__.py", line 129, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\terminal\ipapp.py", line 318, in start
    self.shell.mainloop()
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\terminal\interactiveshell.py", line 888, in mainloop
    self.interact()
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\terminal\interactiveshell.py", line 881, in interact
    self.run_cell(code, store_history=True)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
    result = self._run_cell(
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
    result = runner(coro)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-7a054b904544>", line 1, in <module>
    t.train(net, 'alexnet')
  File "D:\PythonProjects/pytorch_v2/algorithms\train.py", line 266, in train
    outputs = net(inputs).to('cuda')
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\90768\Desktop\t.py", line 34, in forward
    x = self.conv4(x)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\activation.py", line 1553, in forward
    return F.log_softmax(input, self.dim, _stacklevel=5)
  File "C:\Users\90768\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py", line 1932, in log_softmax
    ret = input.log_softmax(dim)
 (Triggered internally at ..\torch\csrc\autograd\python_anomaly_mode.cpp:119.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 t.train(net, 'alexnet')

File D:\PythonProjects/pytorch_v2/algorithms\train.py:281, in Trainer.train(self, net_to_train, net_name)
    279 # loss calculation and backward:
    280 loss = criterion(outputs, labels)
--> 281 loss.backward()
    282 optimizer.step()
    283 running_loss += loss.item()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_tensor.py:487, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 384, 10, 10]], which is output 0 of LogSoftmaxBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

### Versions

PS D:\PythonProjects\venv\Lib\site-packages\torch\utils> python collect_env.py
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU
Nvidia driver version: 532.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2200
DeviceID=CPU0
Family=207
L2CacheSize=16384
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2200
Name=13th Gen Intel(R) Core(TM) i9-13900HX
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2+cu117
[conda] Could not collect

**Comment by ptrblck** [comment]
You are explicitly using `inplace=True` in a few layers and the error mentions that an inplace operation modified a variable needed for the gradient computation:
```python
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
Remove the `inplace=True` arguments and rerun your code.

The [discussion board](https://discuss.pytorch.org/) is also the proper place to ask about model errors.

**Comment by houman95** [comment]
I didn't set inplace = True and faced the same error.  @ptrblck 
I should mention that I only face such error when I use Threadpool instead of sequential learning in FL setting.

**Comment by FatemehTahavori** [comment]
Same here—I am not using inplace=True and encounter the same error when using the MPS device. Do you have any solutions for this?
