### ISSUE TITLE
Cannot use pytorch interpreter help function due to error

### ISSUE THREAD

**Issue by KennethAdamMiller** [pytorch/pytorch#10480]
## Issue description

I can't use the help due to an error, and I've reinstalled torch for both python 2 and 3 and with both anaconda and my host python.

## Code example

>>> import torch
>>> help(torch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1895, in __call__
    self.help(request)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1954, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1674, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1667, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 385, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1136, in docmodule
    for key, value in inspect.getmembers(object, inspect.isclass):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 325, in getmembers
    names = dir(object)
TypeError: descriptor '__dir__' of 'object' object needs an argument

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.11.4

Python version: 2.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] Could not collect

**Comment by soumith** [comment]
@KennethAdamMiller you report that your Python version is 2.7, but you are using Python 3.7 (as evidenced by the stack-trace).

We fixed this issue (which affects Python 3.7) in https://github.com/pytorch/pytorch/pull/10271

It was fixed after the 0.4.1 release and will be part of the next release.

**Comment by KennethAdamMiller** [comment]
"for both python 2 and 3"

**Comment by soumith** [comment]
@KennethAdamMiller sorry for missing that. Can I see a stack-trace for python2? (the python 3.7 issue has been fixed, maybe python 2 has a different issue in your case)

**Comment by KennethAdamMiller** [comment]
┌─(~/workspace/TAI/Code/Current)───────────────────────────────────────────────────────────────────────────(kamiller@HRLE03983:s011)─┐
└─(02:01:18)──> which python                                                                                           ──(Tue,Aug14)─┘
/usr/local/bin/python
┌─(~/workspace/TAI/Code/Current)───────────────────────────────────────────────────────────────────────────(kamiller@HRLE03983:s011)─┐
└─(02:01:21)──> python                                                                                                 ──(Tue,Aug14)─┘
Python 2.7.15 (default, Jun 17 2018, 13:05:56)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> help(torch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 446, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1795, in __call__
    self.help(request)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1842, in help
    else: doc(request, 'Help on %s:')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1579, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1574, in render_doc
    return title % desc + '\n\n' + text.document(object, name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 361, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1143, in docmodule
    result = result + self.section('CLASSES', join(contents, '\n'))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 320, in join
    return sep.join(words)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 33224: ordinal not in range(128)

Thanks for being attentive and helping me with it! :D

**Comment by soumith** [comment]
in your console,  before `help(torch)`, can you run these commands:

```
import sys  
reload(sys)  
sys.setdefaultencoding('utf8')
```

Does that fix the issue?

**Comment by KennethAdamMiller** [comment]
Yeah that did fix it!

**Comment by zou3519** [comment]
We should probably test and support `help(torch)` on Python 2

**Comment by mruberry** [comment]
Closing this issue because we no longer support Python 2. Please reopen if it's still relevant.
