### ISSUE TITLE
INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":644, please report a bug to PyTorch

### ISSUE THREAD

**Issue by devtronslab** [pytorch/pytorch#104801]
## Full error is:
```
Traceback (most recent call last):
  File "blahblahblah.py", line 249, in <module>
    trainer.fit(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 933, in _run
    self.strategy.setup_environment()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/ddp.py", line 144, in setup_environment
    super().setup_environment()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/strategy.py", line 128, in setup_environment
    self.accelerator.setup_device(self.root_device)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/accelerators/cuda.py", line 44, in setup_device
    _check_cuda_matmul_precision(device)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/accelerators/cuda.py", line 344, in _check_cuda_matmul_precision
    major, _ = torch.cuda.get_device_capability(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: config[i] == get()->name() INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":644, please report a bug to PyTorch. Allocator backend parsed at runtime != allocator backend parsed at load time
```

## Details:
- Singularity container (from `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04` docker image) running on single node in SLURM 
- Lightning 2.0.4 used to create a trainer with DistributedDataParallel strategy: 
```
trainer = pl.Trainer(
        accelerator='gpu',
        devices=NUM_GPUS,
        max_epochs=NUM_TRAIN_EPOCHS,
        strategy='ddp',
    )
```
- `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"`
- error occurs when calling `trainer.fit()`

## collect_env.py
```
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX A6000
GPU 5: NVIDIA RTX A6000
GPU 6: NVIDIA RTX A6000
GPU 7: NVIDIA RTX A6000

Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Address sizes:       48 bits physical, 48 bits virtual
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Vendor ID:           AuthenticAMD
Model name:          AMD EPYC 7513 32-Core Processor
CPU family:          25
Model:               1
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           2
Stepping:            1
Frequency boost:     disabled
CPU max MHz:         2600.0000
CPU min MHz:         1500.0000
BogoMIPS:            5199.85
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 invpcid_single hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq overflow_recov succor smca
Virtualization:      AMD-V
L1d cache:           2 MiB (64 instances)
L1i cache:           2 MiB (64 instances)
L2 cache:            32 MiB (64 instances)
L3 cache:            256 MiB (8 instances)
NUMA node(s):        2
NUMA node0 CPU(s):   0-31
NUMA node1 CPU(s):   32-63

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==2.0.4
[pip3] torch==2.0.1+cu118
[pip3] torchmetrics==1.0.0
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] No relevant packages
```

cc @ptrblck

**Comment by ptrblck** [comment]
You are most likely setting the config too late, i.e. after importing `torch` via:
```python
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"
```
This works:
```python
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"

import torch

x = torch.randn(1).cuda()
print(x)
```
This fails:
```python
import torch

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"

x = torch.randn(1).cuda()
print(x)
```
Output:
```
Traceback (most recent call last):
  File "/workspace/src/tmp.py", line 6, in <module>
    x = torch.randn(1).cuda()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: config[i] == get()->name() INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":644, please report a bug to PyTorch. Allocator backend parsed at runtime != allocator backend parsed at load time
```
Setting env variables via `os.environ` is often problematic and we thus always recommend exporting these into your current env/terminal, since we see similar issues when users try to set e.g. `CUDA_LAUNCH_BLOCKING=1` or want to mask a device via `CUDA_VISBLE_DEVICES`.
I also don't think the assert should claim it's an internal error.

@eqy do you think it makes sense to change the assert with a better error message and without pointing to an internal error?

**Comment by devtronslab** [comment]
Thank you, that suggestion appears to have solved the issue.

Another question that isn't directly related to the original issue but now crops up: is there a way I can disable the warnings of ```
[W CUDAMallocAsyncAllocator.cpp:590] Warning: Called record_stream on tensor whose original creation stream matches the recorded stream. This is unnecessary and has no effect. (function recordStream)
```
that now flood the terminal?

**Comment by eqy** [comment]
> You are most likely setting the config too late, i.e. after importing `torch` via:
> 
> ```python
> os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"
> ```
> 
> This works:
> 
> ```python
> import os
> os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"
> 
> import torch
> 
> x = torch.randn(1).cuda()
> print(x)
> ```
> 
> This fails:
> 
> ```python
> import torch
> 
> import os
> os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "backend:cudaMallocAsync"
> 
> x = torch.randn(1).cuda()
> print(x)
> ```
> 
> Output:
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/src/tmp.py", line 6, in <module>
>     x = torch.randn(1).cuda()
>   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: config[i] == get()->name() INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":644, please report a bug to PyTorch. Allocator backend parsed at runtime != allocator backend parsed at load time
> ```
> 
> Setting env variables via `os.environ` is often problematic and we thus always recommend exporting these into your current env/terminal, since we see similar issues when users try to set e.g. `CUDA_LAUNCH_BLOCKING=1` or want to mask a device via `CUDA_VISBLE_DEVICES`. I also don't think the assert should claim it's an internal error.
> 
> @eqy do you think it makes sense to change the assert with a better error message and without pointing to an internal error?

I agree, I think for user-config-facing errors we typically use `TORCH_CHECK`. I'll work on a PR for this.
