### ISSUE TITLE
Dynamic shapes tests fail when not simplifying `Mod` expressions.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#104826]
### 🐛 Describe the bug

Some tests in _test/dynamo/dynamic_shapes.py_ fail if SymPy stops simplifying `Mod` operations. The easiest way to reproduce this behavior is:

1. Modify SymPy `Mod` implementation at _sympy/core/mod.py_:

```python
class Mod(Function):
    @classmethod
    def eval(cls, p, q):
        # Never simplify Mod expressions.
        return None
```

2. Run: `DynamicShapesExportTests.test_capture_symbolic_tracing_dynamic_shapes`

```bash
$ python test/dynamo/test_dynamic_shapes.py -v -k test_capture_symbolic_tracing_dynamic_shapes
...
  File "/torch/fx/experimental/symbolic_shapes.py", line 2696, in produce_guards
    issue_guard(guard)
  File "/torch/fx/experimental/symbolic_shapes.py", line 2664, in issue_guard
    guard_expr = ShapeGuardPrinter(symbol_to_source, source_ref, self.var_to_sources).doprint(expr)
...
  File "/torch/fx/experimental/symbolic_shapes.py", line 1442, in _print_Symbol
    assert self.symbol_to_source.get(expr), (
AssertionError: s0 (could be from ['__meta_utils_unknown_tensor4.size()[0]']) not in {s0: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665
```

<details>
<summary>Raw Log</summary>

```python
test_capture_symbolic_tracing_dynamic_shapes (torch._dynamo.testing.DynamicShapesExportTests) ...
[2023-07-08 11:44:37,441] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(Mod(s0, s0*s1), 0) == True, this could result in accuracy problems
[2023-07-08 11:44:37,444] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(Mod(s0*s1, s0*s1), 0) == False, this could result in accuracy problems
[2023-07-08 11:44:37,457] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Eq(s1, 2) == True, this could result in accuracy problems
[2023-07-08 11:44:37,465] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(Mod(2*s0, s0), 0) == False, this could result in accuracy problems
[2023-07-08 11:44:37,472] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(Mod(s0, 2*s0), 0) == True, this could result in accuracy problems
[2023-07-08 11:44:37,473] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(Mod(2*s0, 2*s0), 0) == False, this could result in accuracy problems
[2023-07-08 11:44:37,482] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(Mod(2*s0, s0), 0) == False, this could result in accuracy problems
[2023-07-08 11:44:37,494] torch.fx.experimental.symbolic_shapes: [WARNING] 0.0: Failing guard allocated at:
  File "/test/dynamo/test_dynamic_shapes.py", line 78, in <module>
    run_tests()
  File "/torch/_dynamo/test_case.py", line 38, in run_tests
    run_tests()
  File "/torch/testing/_internal/common_utils.py", line 894, in run_tests
    unittest.main(argv=argv)
  File "/lib/python3.9/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/lib/python3.9/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/lib/python3.9/unittest/runner.py", line 184, in run
    test(result)
  File "/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/torch/testing/_internal/common_utils.py", line 2368, in run
    self._run_with_retry(
  File "/torch/testing/_internal/common_utils.py", line 2297, in _run_with_retry
    super_run(result=result)
  File "/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/torch/_dynamo/testing.py", line 312, in _fn
    return fn(*args, **kwargs)
  File "/test/dynamo/test_export.py", line 3036, in test_capture_symbolic_tracing
    graph_module, _ = torch._dynamo.export(
  File "/torch/_dynamo/eval_frame.py", line 1016, in export
    graph = make_fx(
  File "/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 468, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
  File "/torch/fx/experimental/proxy_tensor.py", line 485, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/torch/_dynamo/eval_frame.py", line 1012, in graph_with_interpreter
    return torch.fx.Interpreter(graph).run(*args)
  File "/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/torch/fx/interpreter.py", line 312, in call_module
    return submod(*args, **kwargs)
  File "/torch/fx/_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 425, in call_module
    return forward(*args, **kwargs)
  File "/torch/fx/_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 555, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 580, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 361, in proxy_call
    out = func(*args, **kwargs)
  File "/torch/_ops.py", line 429, in __call__
    return self._op(*args, **kwargs or {})
  File "/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/torch/_subclasses/fake_tensor.py", line 1160, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/torch/_subclasses/fake_tensor.py", line 1343, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "/torch/_refs/__init__.py", line 4138, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "/torch/_refs/__init__.py", line 3335, in _reshape_view_helper
    while accum % length != 0:
  File "/torch/__init__.py", line 353, in __bool__
    return self.node.bool_()
  File "/torch/fx/experimental/symbolic_shapes.py", line 873, in bool_
    return self.guard_bool("", 0)
  File "/torch/fx/experimental/symbolic_shapes.py", line 865, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)

stats [('calls_captured', 4), ('unique_graphs', 2)]
FAIL

======================================================================
FAIL: test_capture_symbolic_tracing_dynamic_shapes (torch._dynamo.testing.DynamicShapesExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/torch/_dynamo/testing.py", line 312, in _fn
    return fn(*args, **kwargs)
  File "/test/dynamo/test_export.py", line 3036, in test_capture_symbolic_tracing
    graph_module, _ = torch._dynamo.export(
  File "/torch/_dynamo/eval_frame.py", line 948, in export
    result_traced = opt_f(*args, **kwargs)
  File "/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/torch/_dynamo/eval_frame.py", line 447, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/torch/_dynamo/utils.py", line 179, in time_wrapper
    r = func(*args, **kwargs)
  File "/torch/_dynamo/convert_frame.py", line 478, in _compile
    check_fn = CheckFunctionManager(
  File "/torch/_dynamo/guards.py", line 871, in __init__
    guard.create(local_builder, global_builder)
  File "/torch/_guards.py", line 215, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/torch/_dynamo/guards.py", line 548, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/torch/fx/experimental/symbolic_shapes.py", line 2696, in produce_guards
    issue_guard(guard)
  File "/torch/fx/experimental/symbolic_shapes.py", line 2664, in issue_guard
    guard_expr = ShapeGuardPrinter(symbol_to_source, source_ref, self.var_to_sources).doprint(expr)
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/str.py", line 777, in _print_Relational
    return '%s(%s, %s)' % (charmap[expr.rel_op], self._print(expr.lhs),
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/str.py", line 160, in _print_Function
    return expr.func.__name__ + "(%s)" % self.stringify(expr.args, ", ")
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/str.py", line 40, in stringify
    return sep.join([self.parenthesize(item, level) for item in args])
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/str.py", line 40, in <listcomp>
    return sep.join([self.parenthesize(item, level) for item in args])
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/str.py", line 37, in parenthesize
    return self._print(item)
  File "/lib/python3.9/site-packages/sympy-1.11.1-py3.9.egg/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/torch/fx/experimental/symbolic_shapes.py", line 1442, in _print_Symbol
    assert self.symbol_to_source.get(expr), (
AssertionError: s0 (could be from ['__meta_utils_unknown_tensor4.size()[0]']) not in {s0: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665
```
</details>

**Note:** the error occurred when trying to print `Ne(Mod(s0, 2*s0), 0)`. Without the SymPy change (i.e. turning simplification of `Mod` expressions on), the expression is simplified to true.

**Expected:** the tests should pass regardless of SymPy simplification.

### Other Tests

There are a few other tests that fail, when I run _dynamo/test_dynamic_shapes.py_:

```python
FAILED [0.0093s] test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_numpy_ndarray_graph_break - AssertionError: Scalars are not equal!
FAILED [0.0160s] test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_numpy_ndarray_graph_break_dynamic_shapes - AssertionError: Scalars are not equal!
FAILED [0.0125s] test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_numpy_ndarray_graph_break_with_multiple_outputs - AssertionError: Scalars are not equal!
FAILED [0.0266s] test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_numpy_ndarray_graph_break_with_multiple_outputs_dynamic_shapes - AssertionError: Scalars are not equal!
FAILED [0.0160s] test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_tensor_interacts_with_numpy_ndarray - AssertionError: Scalars are not equal!
FAILED [0.0323s] test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_tensor_interacts_with_numpy_ndarray_dynamic_shapes - AssertionError: Scalars are not equal!
FAILED [0.0792s] test/dynamo/test_dynamic_shapes.py::DynamicShapesExportTests::test_capture_symbolic_tracing - AssertionError: s0 (could be from ['__meta_utils_unknown_tensor4.size()[0]']) not in {s0: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665
FAILED [0.0753s] test/dynamo/test_dynamic_shapes.py::DynamicShapesExportTests::test_capture_symbolic_tracing_dynamic_shapes - AssertionError: s0 (could be from ['__meta_utils_unknown_tensor4.size()[0]']) not in {s0: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665
====================================================================================== 8 failed, 1790 passed, 64 skipped, 28 xfailed in 85.92s (0:01:25) =======================================================================================
```

### Versions

On commit: `db1ac4e29b0f557711190c8d49d4afb5da1844e8` (July 6).

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ysiraichi** [comment]
cc @ezyang

**Comment by ezyang** [comment]
The first issue you quoted here is a one-off issue with the fake mode export interface I worked on with @thiagocrepaldi. The root cause of the problem is that when we fakeify the tensor manually here

```
        # Fakefy input+model before exporting it
        with fake_mode:
            x = torch.rand(5, 2, 2)
            model = Model()
```

we didn't assign sources to x or the model. This then bypasses the source assignment Dynamo would have done, and consequently guard creation doesn't know what to do. This is a separate bug that would need to be fixed but if @thiagocrepaldi isn't running into trouble with it I'm not in a rush to fix it.

The other issues seem to be dupes of this one, OR numpy ndarray related (cc @larryliu0820). Hard to say without the error message.

**Comment by ysiraichi** [comment]
They are all similar to each other.

<details>
<summary>DynamicShapesMiscTests.test_numpy_ndarray_graph_break</summary>

```python
Traceback (most recent call last):
  File "/test/dynamo/test_misc.py", line 1242, in test_numpy_ndarray_graph_break
    self.assertEqual(cnts.frame_count, 2)
  File "/torch/testing/_internal/common_utils.py", line 3119, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5
------------------------------------------------------------------------------------------------------------- Captured stdout call
-------------------------------------------------------------------------------------------------------------
frames [('total', 3), ('ok', 3)]
unimplemented []
graph_break [('call_function graph_break in skip_files /torch/_dynamo/__init__.py', 1), ('call_function args: NumpyVariable() ConstantVariable(float) ', 1)]
stats [('calls_captured', 2), ('unique_graphs', 1)]
```
</details>

<details>
<summary>DynamicShapesMiscTests.test_numpy_ndarray_graph_break_dynamic_shapes</summary>

```python
Traceback (most recent call last):
  File "/test/dynamo/test_misc.py", line 1242, in test_numpy_ndarray_graph_break
    self.assertEqual(cnts.frame_count, 2)
  File "/torch/testing/_internal/common_utils.py", line 3119, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5
------------------------------------------------------------------------------------------------------------- Captured stdout call
-------------------------------------------------------------------------------------------------------------
frames [('total', 3), ('ok', 3)]
unimplemented []
graph_break [('call_function graph_break in skip_files /torch/_dynamo/__init__.py', 1), ('call_function args: NumpyVariable() ConstantVariable(float) ', 1)]
stats [('calls_captured', 2), ('unique_graphs', 1)]
```
</details>

<details>
<summary>DynamicShapesMiscTests.test_numpy_ndarray_graph_break_with_multiple_outputs</summary>

```python
Traceback (most recent call last):
  File "/test/dynamo/test_misc.py", line 1260, in test_numpy_ndarray_graph_break_with_multiple_outputs
    self.assertEqual(cnts.frame_count, 2)
  File "/torch/testing/_internal/common_utils.py", line 3119, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5
------------------------------------------------------------------------------------------------------------- Captured stdout call
-------------------------------------------------------------------------------------------------------------
frames [('total', 4), ('ok', 4)]
unimplemented []
graph_break [('call_function args: NumpyVariable() ConstantVariable(int) ', 2), ('call_function graph_break in skip_files /torch/_dynamo/__init__.py', 1)]
stats [('calls_captured', 2), ('unique_graphs', 1)]
```
</details>

<details>
<summary>DynamicShapesMiscTests.test_numpy_ndarray_graph_break_with_multiple_outputs_dynamic_shapes</summary>

```python
Traceback (most recent call last):
  File "/test/dynamo/test_misc.py", line 1260, in test_numpy_ndarray_graph_break_with_multiple_outputs
    self.assertEqual(cnts.frame_count, 2)
  File "/torch/testing/_internal/common_utils.py", line 3119, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5
------------------------------------------------------------------------------------------------------------- Captured stdout call
-------------------------------------------------------------------------------------------------------------
frames [('total', 4), ('ok', 4)]
unimplemented []
graph_break [('call_function args: NumpyVariable() ConstantVariable(int) ', 2), ('call_function graph_break in skip_files /torch/_dynamo/__init__.py', 1)]
stats [('calls_captured', 2), ('unique_graphs', 1)]
```
</details>

<details>
<summary>DynamicShapesMiscTests.test_tensor_interacts_with_numpy_ndarray</summary>

```python
Traceback (most recent call last):
  File "/test/dynamo/test_misc.py", line 1280, in test_tensor_interacts_with_numpy_ndarray
    self.assertEqual(cnts.frame_count, 2)
  File "/torch/testing/_internal/common_utils.py", line 3119, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5
------------------------------------------------------------------------------------------------------------- Captured stdout call
-------------------------------------------------------------------------------------------------------------
frames [('total', 4), ('ok', 4)]
unimplemented []
graph_break [('call_function args: NumpyVariable() NumpyVariable() ', 2), ('call_function graph_break in skip_files /torch/_dynamo/__init__.py', 1)]
stats [('calls_captured', 4), ('unique_graphs', 1)]
```
</details>

<details>
<summary>DynamicShapesMiscTests.test_tensor_interacts_with_numpy_ndarray_dynamic_shapes</summary>

```python
Traceback (most recent call last):
  File "/test/dynamo/test_misc.py", line 1280, in test_tensor_interacts_with_numpy_ndarray
    self.assertEqual(cnts.frame_count, 2)
  File "/torch/testing/_internal/common_utils.py", line 3119, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Scalars are not equal!

Expected 2 but got 1.
Absolute difference: 1
Relative difference: 0.5
------------------------------------------------------------------------------------------------------------- Captured stdout call
-------------------------------------------------------------------------------------------------------------
frames [('total', 4), ('ok', 4)]
unimplemented []
graph_break [('call_function args: NumpyVariable() NumpyVariable() ', 2), ('call_function graph_break in skip_files /torch/_dynamo/__init__.py', 1)]
stats [('calls_captured', 4), ('unique_graphs', 1)]
```
</details>

**Comment by ezyang** [comment]
The numpy frame count change is pretty strange, will need to run with some logs and see what's going on.

**Comment by ysiraichi** [comment]
Yes. Even weirder: this error only occurs when I execute all of _test_dynamic_shapes.py_ tests. Whenever I filter so as to run only, for example, `test_numpy_ndarray_graph_break`, they pass.

**Comment by ysiraichi** [comment]
Ok. This is super strange. I will rebase and re-run the tests.

**Comment by ezyang** [comment]
The hysteresis problem could be due to not clearing cache

**Comment by ysiraichi** [comment]
Turns out `test_capture_symbolic_tracing_dynamic_shapes` was really relying on `Mod` (@ezyang already commented on that). The others were unrelated.
