### ISSUE TITLE
Graph break in len(numpy_array) in compiled NumPy

### ISSUE THREAD

**Issue by ev-br** [pytorch/pytorch#105054]
### 🐛 Describe the bug

```
$ cat sum.py 
import numpy as np

import torch
torch.set_default_device("cpu")

import torch._dynamo.config as cfg
cfg.numpy_ndarray_as_tensor = True

y_glob = np.array([[1, 2, 3], [4, 5, 6]])

@torch.compile
def av(x):
    v = x.sum() / len(x)
    return v

print(av(y_glob))
```

graph breaks on `len(x)`:

```
$ time TORCH_LOGS="+dynamo" python sum.py 
[2023-07-12 14:55:50,771] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:50,771] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:50,771] torch._dynamo.eval_frame: [DEBUG] skipping helper /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:50,771] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:50,771] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:50,771] torch._dynamo.eval_frame: [DEBUG] skipping enable_dynamic /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py
[2023-07-12 14:55:50,771] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing av sum.py:11
[2023-07-12 14:55:50,831] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['x'] (2, 3) [<DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>] [None, None]
[2023-07-12 14:55:50,833] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line sum.py:13
[2023-07-12 14:55:50,833] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x []
[2023-07-12 14:55:50,833] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR sum [NumpyNdarrayVariable()]
[2023-07-12 14:55:50,833] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 0 [GetAttrVariable(NumpyNdarrayVariable(), sum)]
[2023-07-12 14:55:50,835] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL len [NumpyNdarrayVariable()]
[2023-07-12 14:55:50,835] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x [NumpyNdarrayVariable(), BuiltinVariable(len)]
[2023-07-12 14:55:50,836] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 1 [NumpyNdarrayVariable(), BuiltinVariable(len), NumpyNdarrayVariable()]
[2023-07-12 14:55:50,836] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 391, in wrapper
    return inner_fn(self, inst)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 598, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 891, in call_len
    return args[0].call_method(tx, "__len__", args[1:], kwargs)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/tensor.py", line 882, in call_method
    result = wrap_fx_proxy_cls(
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1291, in wrap_fx_proxy_cls
    unimplemented(
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 141, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function <Wrapped method <original __len__>>
[2023-07-12 14:55:50,837] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG] Graph break: torch.* op returned non-Tensor int call_function <Wrapped method <original __len__>> from user code at   File "sum.py", line 13, in av
    v = x.sum() / len(x)

[2023-07-12 14:55:50,837] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 1 nodes
[2023-07-12 14:55:50,837] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='torch.* op returned non-Tensor int call_function <Wrapped method <original __len__>>', user_stack=[<FrameSummary file sum.py, line 13 in av>], graph_break=True)
[2023-07-12 14:55:50,838] torch._dynamo.output_graph.__graph_code: [DEBUG] TRACED GRAPH
 ===== __compiled_fn_0 =====
 <eval_with_key>.0 class GraphModule(torch.nn.Module):
    def forward(self, L_x_ : torch.Tensor):
        l_x_ = L_x_
        
        # File: sum.py:13, code: v = x.sum() / len(x)
        wrapped_sum = torch__dynamo_utils_wrapped_sum(l_x_);  l_x_ = None
        return (wrapped_sum,)
        

[2023-07-12 14:55:50,839] torch._dynamo.output_graph.__graph: [DEBUG] TRACED GRAPH
 __compiled_fn_0 <eval_with_key>.0 opcode         name         target                           args               kwargs
-------------  -----------  -------------------------------  -----------------  --------
placeholder    l_x_         L_x_                             ()                 {}
call_function  wrapped_sum  <Wrapped method <original sum>>  (l_x_,)            {}
output         output       output                           ((wrapped_sum,),)  {}

[2023-07-12 14:55:50,844] torch._dynamo.output_graph: [INFO] Step 2: calling compiler function inductor
[2023-07-12 14:55:56,738] torch._dynamo.output_graph: [INFO] Step 2: done compiler function inductor
[2023-07-12 14:55:56,768] torch._dynamo.convert_frame.__guards: [DEBUG] GUARDS:
  ___is_grad_enabled()
  not ___are_deterministic_algorithms_enabled()
  utils_device.CURRENT_DEVICE == device(type='cpu')
[2023-07-12 14:55:56,769] torch._dynamo.eval_frame: [DEBUG] skipping __torch_function__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/utils/_device.py
[2023-07-12 14:55:56,769] torch._dynamo.eval_frame: [DEBUG] skipping _fn /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py
[2023-07-12 14:55:56,769] torch._dynamo.eval_frame: [DEBUG] skipping nothing /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py
[2023-07-12 14:55:56,769] torch._dynamo.eval_frame: [DEBUG] skipping __exit__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:56,769] torch._dynamo.eval_frame: [DEBUG] skipping __exit__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 14:55:56,769] torch._dynamo.eval_frame: [DEBUG] skipping to_numpy_helper /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/utils.py
[2023-07-12 14:55:56,769] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* <resume in av>             sum.py 13
10.5
[2023-07-12 14:55:56,784] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
Function                                Runtimes (s)
------------------------------------  --------------
_compile                                      5.9971
OutputGraph.call_user_compiler                5.8937
create_aot_dispatcher_function                6.7486
compile_fx.<locals>.fw_compiler_base          5.6155
GraphLowering.run                             0.0304
GraphLowering.compile_to_module               3.8729
Scheduler.__init__                            3.8646
Scheduler.codegen                             0.0038
WrapperCodeGen.generate                       0.0005
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @lezcano

### Versions

same as https://github.com/pytorch/pytorch/issues/105052

**Comment by ezyang** [comment]
cc @larryliu0820

**Comment by ev-br** [comment]
Compiling `abs(x)` produces a similar graph break, while `np.abs(x)` works and transpiles to `std::abs(x)`.

**Comment by kshitij12345** [comment]
I'd like to pick this up.

**Comment by kshitij12345** [comment]
Builtin `abs` is not supported on `tensor` as well, so deferring to fixing it for now.

```python
import numpy as np

import torch
torch.set_default_device("cpu")

import torch._dynamo.config as cfg
cfg.numpy_ndarray_as_tensor = True

y_glob = np.array([[1, 2, 3], [4, 5, 6]])

@torch.compile(backend='eager', fullgraph=True)
def av(x):
    return abs(x)

print(av(torch.randn(2, 2)))
# print(av(y_glob))
```

Error
```
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(abs) [TensorVariable()] {}
```

**Comment by lezcano** [comment]
I reckon that fixing this one for tensor (in general, adding all the necessary dunder methods) should be reasonably simple.

**Comment by larryliu0820** [comment]
@kshitij12345 Are you still working on this? I don't want to duplicate the effort

**Comment by kshitij12345** [comment]
@larryliu0820 , thanks for reaching out, I think it will take me some time before I get back to this, so please feel free to pick this one up.
