### ISSUE TITLE
Minifier fails when storage size is not divisible by 2

### ISSUE THREAD

**Issue by ar0ck** [pytorch/pytorch#105035]
### 🐛 Describe the bug

With `TORCHDYNAMO_REPRO_AFTER="aot"` + `TORCHDYNAMO_REPRO_LEVEL=4`, the following snippet:

```python
import torch

def f(x):
    return (x + x).to(torch.int16)

x = torch.tensor(128, dtype=torch.uint8)
torch._dynamo.utils.same(f(x), torch.compile(f)(x))
```

, yields the following error:

```python
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    assert torch._dynamo.utils.same(f(x), torch.compile(f)(x))
  File "/.../lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "bug.py", line 3, in f
    def f(x):
  File "/.../lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/.../lib/python3.9/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/.../lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 3725, in forward
    return compiled_fn(full_args)
  File "/.../lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1433, in g
    return f(*args)
  File "/.../lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2391, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/.../lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1457, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/.../lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1545, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/.../lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 109, in deferred_for_real_inputs
    return inner_debug_fn(real_inputs)
  File "/.../lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 142, in inner_debug_fn
    dump_compiler_graph_state(
  File "/.../lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 289, in dump_compiler_graph_state
    save_graph_repro(
  File "/.../lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 258, in save_graph_repro
    generate_compiler_repro_string(
  File "/.../lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 234, in generate_compiler_repro_string
    writer.tensor(placeholder, arg)
  File "/.../lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 660, in tensor
    storage = self.storage(
  File "/.../lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 652, in storage
    storage_hash = self.store.write_storage(untyped_storage)
  File "/.../lib/python3.9/site-packages/torch/utils/_content_store.py", line 147, in write_storage
    h = hash_storage(storage, stable_hash=self.stable_hash)
  File "/.../lib/python3.9/site-packages/torch/utils/_content_store.py", line 123, in hash_storage
    x = x.view(torch.int32)
RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Int (different element sizes), but got 2
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230711+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         3302.232
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       768 KiB
L1i cache:                       512 KiB
L2 cache:                        20 MiB
L3 cache:                        24 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] torch==2.1.0.dev20230711+cpu
[conda] No relevant packages
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ar0ck** [comment]
This is an easy fix - the [padding calculation](https://github.com/pytorch/pytorch/blob/c03558fa8dea6cb75e2507ed2f600d5363c12d6f/torch/utils/_content_store.py#L120-L122) used in `hash_storage` is incorrect. I will put up a PR to fix it shortly.
