### ISSUE TITLE
Graph break in compiled NumPy `.astype(int)`

### ISSUE THREAD

**Issue by ev-br** [pytorch/pytorch#105052]
### 🐛 Describe the bug

Need to install https://github.com/Quansight-Labs/numpy_pytorch_interop/

Using built-in python types for casting, as in `x.astype(int)` generates a graph break.

```
import numpy as np
import torch
torch.set_default_device("cpu")
import torch._dynamo.config as cfg
cfg.numpy_ndarray_as_tensor = True

@torch.compile
def f(x):
    y = x.astype(int)
    return y
x = np.ones(3, dtype='float64')
print(f(x))
```

Produces

```
$ TORCH_LOGS="+dynamo" python astype.py 
[2023-07-12 13:58:35,321] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 13:58:35,321] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 13:58:35,321] torch._dynamo.eval_frame: [DEBUG] skipping helper /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 13:58:35,321] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 13:58:35,321] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-12 13:58:35,321] torch._dynamo.eval_frame: [DEBUG] skipping enable_dynamic /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py
[2023-07-12 13:58:35,322] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing f astype.py:8
[2023-07-12 13:58:35,379] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['x'] (3,) [<DimDynamic.STATIC: 2>] [None]
[2023-07-12 13:58:35,381] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line astype.py:10
[2023-07-12 13:58:35,381] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x []
[2023-07-12 13:58:35,381] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR astype [NumpyNdarrayVariable()]
[2023-07-12 13:58:35,381] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL int [GetAttrVariable(NumpyNdarrayVariable(), astype)]
[2023-07-12 13:58:35,382] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 1 [GetAttrVariable(NumpyNdarrayVariable(), astype), BuiltinVariable(int)]
[2023-07-12 13:58:35,382] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 480, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 480, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 282, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: BuiltinVariable(int)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 391, in wrapper
    return inner_fn(self, inst)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 598, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/tensor.py", line 888, in call_method
    *proxy_args_kwargs([self] + list(args), kwargs),
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 487, in proxy_args_kwargs
    raise unimplemented(
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 141, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function args: NumpyNdarrayVariable() BuiltinVariable(int) 
[2023-07-12 13:58:35,383] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG] Graph break: call_function args: NumpyNdarrayVariable() BuiltinVariable(int)  from user code at   File "astype.py", line 10, in f
    y = x.astype(int)

[2023-07-12 13:58:35,383] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-07-12 13:58:35,383] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='call_function args: NumpyNdarrayVariable() BuiltinVariable(int) ', user_stack=[<FrameSummary file astype.py, line 10 in f>], graph_break=True)
[2023-07-12 13:58:35,402] torch._dynamo.convert_frame.__guards: [DEBUG] GUARDS:
  ___is_grad_enabled()
  not ___are_deterministic_algorithms_enabled()
  utils_device.CURRENT_DEVICE == device(type='cpu')
[2023-07-12 13:58:35,402] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* <resume in f>             astype.py 10
[1 1 1]
[2023-07-12 13:58:35,407] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
Function      Runtimes (s)
----------  --------------
_compile            0.0801
```

Using a string, `x.astype('int')` works fine.

cc @mruberry @rgommers @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @lezcano 

### Versions

PyTorch version: 2.1.0.dev20230706+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00)  [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Stepping:                        12
CPU MHz:                         1800.000
CPU max MHz:                     3900,0000
CPU min MHz:                     400,0000
BogoMIPS:                        3600.00
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0.dev20230706+cpu
[conda] numpy                     1.24.4           py38h59b608b_0    conda-forge
[conda] torch                     2.1.0.dev20230706+cpu          pypi_0    pypi

**Comment by ezyang** [comment]
cc @larryliu0820

**Comment by ysiraichi** [comment]
Same behavior without numpy:

```python
@torch.compile
def f(x):
    y = x.to(int)
    return y
x = torch.rand((5,))
print(f(x))
```

```bash
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x []
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR to [TensorVariable()]
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL int [GetAttrVariable(TensorVariable(), to)]
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 1 
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG] Graph break: call_function args: TensorVariable() BuiltinVariable(int)
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]     y = x.to(int)
[2023-07-18 17:49:18,161] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]
[2023-07-18 17:49:18,161] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
```

Is this expected behavior?

**Comment by lezcano** [comment]
It looks like eager does support `to(int)`, but PyTorch doesn't (this is a weird pattern in PyTorch). 
Probably we can fix this one in the compat layer, but you can have a go at fixing this one in TorchDynamo if you feel like @ysiraichi.
