### ISSUE TITLE
graph break in compiling `np.linalg.norm` and other np.linalg functions

### ISSUE THREAD

**Issue by ev-br** [pytorch/pytorch#105269]
### 🐛 Describe the bug

```
$ cat compile_norm.py 
import numpy as np
import matplotlib.pyplot as plt

import torch
torch.set_default_device("cpu")
import torch._dynamo.config as cfg
cfg.numpy_ndarray_as_tensor = True

@torch.compile
def func(x):
    return np.linalg.norm(x)

print(func([1, 2, 3]))
```

Running  `$ TORCH_LOGS="+dynamo" python compile_norm.py`

produces

```
[2023-07-15 15:10:04,923] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-15 15:10:04,923] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-15 15:10:04,923] torch._dynamo.eval_frame: [DEBUG] skipping helper /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-15 15:10:04,923] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-15 15:10:04,923] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-07-15 15:10:04,923] torch._dynamo.eval_frame: [DEBUG] skipping enable_dynamic /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py
[2023-07-15 15:10:04,923] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing func compile_norm.py:10
[2023-07-15 15:10:04,925] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line compile_norm.py:12
[2023-07-15 15:10:04,925] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL np []
[2023-07-15 15:10:04,925] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR linalg [PythonModuleVariable()]
[2023-07-15 15:10:04,926] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR norm [PythonModuleVariable()]
[2023-07-15 15:10:04,926] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x [SkipFilesVariable()]
[2023-07-15 15:10:04,926] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 1 [SkipFilesVariable(), ListVariable()]
[2023-07-15 15:10:04,927] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 391, in wrapper
    return inner_fn(self, inst)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 765, in call_function
    unimplemented(
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 141, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function norm in skip_files <__array_function__ internals>
[2023-07-15 15:10:04,927] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG] Graph break: call_function norm in skip_files <__array_function__ internals> from user code at   File "compile_norm.py", line 12, in func
    return np.linalg.norm(x)

[2023-07-15 15:10:04,927] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-07-15 15:10:04,927] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='call_function norm in skip_files <__array_function__ internals>', user_stack=[<FrameSummary file compile_norm.py, line 12 in func>], graph_break=True)
[2023-07-15 15:10:04,943] torch._dynamo.convert_frame.__guards: [DEBUG] GUARDS:
  ___check_type_id(L['x'], 94580818297504)
  len(L['x']) == 3
  ___check_type_id(L['x'][0], 94580818295744)
  L['x'][0] == 1
  ___check_type_id(L['x'][1], 94580818295744)
  L['x'][1] == 2
  ___check_type_id(L['x'][2], 94580818295744)
  L['x'][2] == 3
  ___is_grad_enabled()
  not ___are_deterministic_algorithms_enabled()
  utils_device.CURRENT_DEVICE == device(type='cpu')
[2023-07-15 15:10:04,943] torch._dynamo.eval_frame: [DEBUG] skipping norm <__array_function__ internals>
[2023-07-15 15:10:04,943] torch._dynamo.eval_frame: [DEBUG] skipping _norm_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/linalg/linalg.py
[2023-07-15 15:10:04,943] torch._dynamo.eval_frame: [DEBUG] skipping norm /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/linalg/linalg.py
[2023-07-15 15:10:04,944] torch._dynamo.eval_frame: [DEBUG] skipping isComplexType /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/linalg/linalg.py
3.7416573867739413
[2023-07-15 15:10:04,948] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
Function      Runtimes (s)
----------  --------------
_compile            0.0197
```

Same error for other functions from `numpy.linalg` namespace (solve etc).

### Versions

same as https://github.com/pytorch/pytorch/issues/105052

cc @mruberry @rgommers @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by lezcano** [comment]
cc @larryliu0820 @ysiraichi
