### ISSUE TITLE
[ONNX] Decomp Pass behaves differently w/ '_dynamo.export(aten_graph=True)' under dynamic shapes and pre-defined fake mode

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#105467]
https://github.com/pytorch/pytorch/pull/105246 requires `torch._dynamo.export(aten_graph=True)`. The reason is an issue with dynamic shape and fake tensor mode, as shown below.

The error below was first reported at https://github.com/pytorch/pytorch/issues/99774, but never really addressed. Instead, we adopted a workaround that now is failing with fake tensor.

The fix is probably "dynamizing" the input before calling the exporter, which might be done on a separate task

```bash
# pytest -sv test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_False::test_large_scale_exporter_with_tiny_gpt2

____________________________ TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_False.test_large_scale_exporter_with_tiny_gpt2 _____________________________
Traceback (most recent call last):
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/decorator.py", line 127, in wrapper
    return_values = fn(*args, **kwargs)
  File "/opt/pytorch/torch/onnx/_internal/fx/_pass.py", line 192, in run
    module = self._run(*args, **kwargs)
  File "<@beartype(torch.onnx._internal.fx.passes.decomp.Decompose._run) at 0x7ff60cd8cdc0>", line 11, in _run
  File "/opt/pytorch/torch/onnx/_internal/fx/passes/decomp.py", line 54, in _run
    decomposed_module = proxy_tensor.make_fx(
  File "/opt/pytorch/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/opt/pytorch/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/fx/experimental/proxy_tensor.py", line 468, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/pytorch/torch/fx/experimental/proxy_tensor.py", line 485, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/opt/pytorch/torch/onnx/_internal/fx/passes/_utils.py", line 30, in wrapped
    return torch.fx.Interpreter(graph_module).run(*args)
  File "/opt/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/opt/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides

While executing %matmul : [num_users=1] = call_function[target=torch.matmul](args = (%permute, %transpose), kwargs = {})
Original traceback:
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 903, in forward
    outputs = block(
  File "/opt/pytorch/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 391, in forward
    attn_outputs = self.attn(
  File "/opt/pytorch/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 332, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 184, in _attn
    attn_weights = torch.matmul(query, key.transpose(-1, -2))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 831, in dynamo_export
    return Exporter(
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 649, in export
    graph_module = pre_export_passes(
  File "<@beartype(torch.onnx._internal.exporter.pre_export_passes) at 0x7ff6a5c73d30>", line 97, in pre_export_passes
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 864, in pre_export_passes
    module = passes.Decompose(
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/decorator.py", line 142, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/context.py", line 265, in log_and_raise_if_error
    raise RuntimeErrorWithDiagnostic(
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Running Decompose pass. Raised from:
    RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides

While executing %matmul : [num_users=1] = call_function[target=torch.matmul](args = (%permute, %transpose), kwargs = {})
Original traceback:
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 903, in forward
    outputs = block(
  File "/opt/pytorch/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 391, in forward
    attn_outputs = self.attn(
  File "/opt/pytorch/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 332, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 184, in _attn
    attn_weights = torch.matmul(query, key.transpose(-1, -2))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/opt/conda/envs/ptca/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/conda/envs/ptca/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/opt/pytorch/torch/testing/_internal/common_utils.py", line 2354, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/test/onnx/pytorch_test_common.py", line 231, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/pytorch/test/onnx/test_fx_to_onnx_with_onnxruntime.py", line 965, in test_large_scale_exporter_with_tiny_gpt2
    self._test_fake_tensor_mode_exporter(
  File "<@beartype(test_fx_to_onnx_with_onnxruntime.TestFxToOnnxWithOnnxRuntime._test_fake_tensor_mode_exporter) at 0x7ff6077ba040>", line 108, in _test_fake_tensor_mode_exporter
  File "/opt/pytorch/test/onnx/test_fx_to_onnx_with_onnxruntime.py", line 883, in _test_fake_tensor_mode_exporter
    export_output = torch.onnx.dynamo_export(
  File "<@beartype(torch.onnx._internal.exporter.dynamo_export) at 0x7ff6a5c73c10>", line 53, in dynamo_export
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 846, in dynamo_export
    raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at report_dynamo_export.sarif. Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues

To execute this test, run the following from the base repo dir:
     python test/onnx/test_fx_to_onnx_with_onnxruntime.py -k test_large_scale_exporter_with_tiny_gpt2

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
======================================================================== short test summary info ========================================================================
FAILED [107.9249s] test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_False::test_large_scale_exporter_with_tiny_gpt2 - torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at report_dynamo_export.sarif. Please report a bug on PyTorch Github: http...
===================================================================== 1 failed in 114.03s (0:01:54) =====================================================================
```

**Comment by BowenBao** [comment]
I updated the title to reduce the scope. @titaiwangms was observing another issue regarding dynamic shapes and pre-defined fake mode, that is slightly related but not the same as this issue. Will track that separately.

**Comment by thiagocrepaldi** [comment]
> I updated the title to reduce the scope. @titaiwangms was observing another issue regarding dynamic shapes and pre-defined fake mode, that is slightly related but not the same as this issue. Will track that separately.

I have a task for that at https://github.com/pytorch/pytorch/issues/105464. Will work on it soon
