### ISSUE TITLE
C++ API `torch::nn:functional::batch_norm`: Buffer-overflow caused by unsigned integer underflow

### ISSUE THREAD

**Issue by Sehun0819** [pytorch/pytorch#105458]
### 🐛 Describe the bug

Input tensor with rank 1 and `training=true` triggers buffer-overflow.

Test code:
```c++
#include <stdint.h>
#include <stddef.h>
#include <c10/util/irange.h>
#include <cassert>
#include <torch/torch.h>

namespace F = torch::nn::functional;
using namespace torch::nn;

int main() {
  torch::TensorOptions toptions =
    torch::TensorOptions()
      .dtype(torch::kFloat32)
      .requires_grad(true);

  auto x = torch::randn({2}, toptions);
  auto y = torch::randn({2}, toptions);
  auto z = torch::randn({2}, toptions);

  auto foptions =
    torch::nn::functional::BatchNormFuncOptions()
      .training(true);

  try {
    auto result = F::batch_norm(x, y, z, foptions);
  } catch (::c10::Error& e) {
    std::cout << "PyTorch Exception: " << e.what();
  } catch (std::runtime_error& e) {
    std::cout << "Runtime Exception: " << e.what();
  }

  return 0;
}

```
Error log:
```bash
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==2467691==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x00000594d000 (pc 0x000000435b78 bp 0x7fff60c68700 sp 0x7fff60c685a0 T2467691)
==2467691==The signal is caused by a READ memory access.
    #0 0x435b78 in torch::nn::functional::detail::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor, at::Tensor, bool, c10::optional<double>, double) /home/sehoon/pytorch/torch/csrc/api/include/torch/nn/functional/batchnorm.h:26:21
    #1 0x42fe43 in torch::nn::functional::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, torch::nn::functional::BatchNormFuncOptions const&) /home/sehoon/pytorch/torch/csrc/api/include/torch/nn/functional/batchnorm.h:66:10
    #2 0x42f378 in main /home/sehoon/pytorch/test/cpp/fuzzing/reproduce/batch_norm_bo.cpp:25:19
    #3 0x7fe2c181ed8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x7fe2c181ee3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #5 0x407644 in _start (/home/sehoon/pytorch/build/bin/reproduce_batch_norm_bo+0x407644)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV /home/sehoon/pytorch/torch/csrc/api/include/torch/nn/functional/batchnorm.h:26:21 in torch::nn::functional::detail::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor, at::Tensor, bool, c10::optional<double>, double)
==2467691==ABORTING

```
[Error location](https://github.com/pytorch/pytorch/blob/38c1e86ee289e0b5fdd3f3375dfe78764765be7f/torch/csrc/api/include/torch/nn/functional/batchnorm.h#L25C3-L27):
```c++
for (const auto i : c10::irange(size.size() - 2)) {
  size_prods *= size[i + 2];
}
```
This loop body shouldn't have been executed when input tensor rank is one. But because `size.size() - 2` (which is equivalent to `1 - 2`) is evaluated to `size_t max` (by unsigned-integer-underflow) the loop body is reached and `size[i + 2]` is executed whose offset is over the valid range(`i + 2` would be evaluated to `1` by overflow, which is out of bound).

### Versions

```
PyTorch version: 2.1.0a0+git38c1e86
Is debug build: True
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 12.0.1 (git@github.com:starlab-unist/llvm-project.git 5dbd431010299dcab8b35db1727895253fe7e8d9)
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
Stepping:                        7
CPU max MHz:                     4000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1.5 MiB (48 instances)
L1i cache:                       1.5 MiB (48 instances)
L2 cache:                        48 MiB (48 instances)
L3 cache:                        71.5 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] torch==2.1.0a0+git38c1e86
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-include               2023.1.0         h06a4308_46342  
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] torch                     2.1.0a0+git38c1e86           dev_0    <develop>
```

cc @jbschlosser @albanD @mruberry @walterddr @mikaylagawarecki

**Comment by albanD** [comment]
Ho, I would expect `c10::irange` to handle this case properly? Or the overflow is before we get there?

**Comment by Sehun0819** [comment]
I think it's not strange that `c10::irange` can't handle this because `size_t max` is normal value for it. How about to check whether `size.size() >= 2` before the loop?

**Comment by ezyang** [comment]
@Sehun0819 is right. When we subtract two from the unsigned int we've already lost. There's nothing irange can do

**Comment by albanD** [comment]
Sounds good!
Would you be able to send a PR to add this check?
