### ISSUE TITLE
out-of-place foreach functions don't set `is_output` to `true` when creating a list of SavedVariable from their outputs

### ISSUE THREAD

**Issue by crcrpar** [pytorch/pytorch#105502]
### 🐛 Describe the bug

Currently out-of-place foreach functions whose backward depends on forward's `result` register the output to `grad_fn`. The output tensors requiring grads share the same `grad_fn` and this `grad_fn` stores `result`. See the example of `_foreach_exp` in `torch/csrc/autograd/generated/VariableType`:

```c++
::std::vector<at::Tensor> _foreach_exp(c10::DispatchKeySet ks, at::TensorList self) {
  auto self_ = unpack(self, "self", 0);
  [[maybe_unused]] auto _any_requires_grad = compute_requires_grad( self );

  std::vector<bool> _any_has_forward_grad_result(self.size());
  for (const auto& i : c10::irange(self.size())) {
    _any_has_forward_grad_result[i] = isFwGradDefined(self[i]);
  }
  std::shared_ptr<ForeachExpBackward0> grad_fn;
  if (_any_requires_grad) {
    grad_fn = std::shared_ptr<ForeachExpBackward0>(new ForeachExpBackward0(), deleteNode);
    grad_fn->set_next_edges(collect_next_edges( self ));
    grad_fn->self_size_ = self.size();
  }
  #ifndef NDEBUG
  std::vector<c10::optional<Storage>> self__storage_saved(self_.size());
  for (const Tensor& tensor : self_)
    self__storage_saved.push_back(
      tensor.has_storage() ? c10::optional<Storage>(tensor.storage()) : c10::nullopt);
  std::vector<c10::intrusive_ptr<TensorImpl>> self__impl_saved(self_.size());
  for (size_t i=0; i<self_.size(); i++)
    if (self_[i].defined()) self__impl_saved[i] = self_[i].getIntrusivePtr();
  #endif
  auto _tmp = ([&]() {
    at::AutoDispatchBelowADInplaceOrView guard;
    return at::redispatch::_foreach_exp(ks & c10::after_autograd_keyset, self_);
  })();
  auto result = std::move(_tmp);
  #ifndef NDEBUG
  for (size_t i=0; i<self_.size() && !at::impl::dispatch_mode_enabled(); i++) {
    if (self__storage_saved[i].has_value() && !at::impl::tensorlist_has_dispatch(self_))
      TORCH_INTERNAL_ASSERT(self__storage_saved[i].value().is_alias_of(self_[i].storage()));
  }
  for (size_t i=0; i<self_.size() && !at::impl::dispatch_mode_enabled(); i++) {
    if (self__impl_saved[i] && !at::impl::tensorlist_has_dispatch(self_))
      TORCH_INTERNAL_ASSERT(self__impl_saved[i] == self_[i].getIntrusivePtr());
  }
  #endif
  if (grad_fn) {
      set_history(flatten_tensor_args( result ), grad_fn);
  }
  std::vector<c10::optional<at::Tensor>> result_new_fw_grad_opts(self.size(), c10::nullopt);
  for (const auto& i : c10::irange(result_new_fw_grad_opts.size())) {
    if (_any_has_forward_grad_result[i]) {
        auto self_t_raw = toNonOptFwGrad(self[i]);
        auto self_tensor = toNonOptTensor(self[i]);
        auto self_t = (self_t_raw.defined() || !self_tensor.defined())
          ? self_t_raw : at::_efficientzerotensor(self_tensor.sizes(), self_tensor.options());
        result_new_fw_grad_opts[i] = (self_t.conj() * result[i].conj()).conj();
    }
  }
  for (const auto& i : c10::irange(result_new_fw_grad_opts.size())) {
    auto& result_new_fw_grad_opt = result_new_fw_grad_opts[i];
    if (result_new_fw_grad_opt.has_value() && result_new_fw_grad_opt.value().defined() && result[i].defined()) {
      // The hardcoded 0 here will need to be updated once we support multiple levels.
      result[i]._set_fw_grad(result_new_fw_grad_opt.value(), /* level */ 0, /* is_inplace_op */ false);
    }
  }
  if (grad_fn) {
    grad_fn->result_ = make_saved_variable_list(result);
  }
  return result;
}
```

The creation of `vector<SavedVariable>` is delegated to this pass https://github.com/pytorch/pytorch/blob/3721fa5612e72de6ebe1cc0db4c246be07f17def/tools/autograd/gen_variable_type.py#L1457-L1463 but all of `make_saved_variable_list` does not set `is_output` to `true`:
https://github.com/pytorch/pytorch/blob/3721fa5612e72de6ebe1cc0db4c246be07f17def/torch/csrc/autograd/VariableTypeUtils.h#L426-L445.

This is exposed by https://github.com/pytorch/pytorch/pull/102409#issuecomment-1615254393. I checked the memory leak in the linked comment is resolved if `SavedVariable`s are correctly constructed with a tensor and `is_output=true`. It however seems to expose another problem as you can see in https://hud.pytorch.org/pr/pytorch/pytorch/105368#15142012171:

```console
2023-07-18T17:54:09.5810555Z =================================== FAILURES ===================================
2023-07-18T17:54:09.5810775Z __ TestForeachCUDA.test_outplace_with_invalid_grads__foreach_exp_cuda_float32 __
2023-07-18T17:54:09.5810917Z Traceback (most recent call last):
2023-07-18T17:54:09.5811179Z   File "/var/lib/jenkins/workspace/test/test_foreach.py", line 912, in test_outplace_with_invalid_grads
2023-07-18T17:54:09.5811325Z     out1.backward(torch.ones_like(out1))
2023-07-18T17:54:09.5811754Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_tensor.py", line 491, in backward
2023-07-18T17:54:09.5811896Z     torch.autograd.backward(
2023-07-18T17:54:09.5812249Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/__init__.py", line 204, in backward
2023-07-18T17:54:09.5812483Z     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
2023-07-18T17:54:09.5812947Z RuntimeError: Trying to use a saved tensor that has been detached in-place, i.e. with .detach_().This is not supported, please use out-of-place `.detach()` instead
```

I speculate this could be because every `release_variables` is called per input tensor.

```c++
struct TORCH_API ForeachExpBackward0 : public TraceableFunction {
  using TraceableFunction::TraceableFunction;
  variable_list apply(variable_list&& grads) override;
  std::string name() const override { return "ForeachExpBackward0"; }
  void release_variables() override {
    std::lock_guard<std::mutex> lock(mutex_);
    result_.clear();
    result_released_ = true;
  }

  std::vector<SavedVariable> result_;
  bool result_released_ = false;
  size_t self_size_;
};
```

### repro

`caching_allocator_mem_allocated` > `init_cached_memory` with the snippet below

```python
import gc
import torch

func = torch._foreach_exp

gc.collect()
torch.cuda.empty_cache()
torch._C._cuda_clearCublasWorkspaces()

primals = [torch.randn(3, device="cuda", requires_grad=True)]

init_cached_memory = torch.cuda.memory_allocated()
bytes_free, bytes_total = torch.cuda.mem_get_info(0)
init_driver_mem_allocated = bytes_total - bytes_free
print(f"# {init_cached_memory = }, {init_driver_mem_allocated = }")


def call(primals):
    func(primals)


call(primals)
torch._C._cuda_clearCublasWorkspaces()
caching_allocator_mem_allocated = torch.cuda.memory_allocated()
bytes_free, bytes_total = torch.cuda.mem_get_info(0)
driver_mem_allocated = bytes_total - bytes_free
print(f"# {caching_allocator_mem_allocated = }, {driver_mem_allocated = }")
```

---

rel:
- https://github.com/pytorch/pytorch/pull/105368#issuecomment-1640820699
- https://github.com/pytorch/pytorch/issues/95431

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
> I speculate this could be because every release_variables is called per input tensor

The engine actually calls this only a single time after the grad_fn finishes running

https://github.com/pytorch/pytorch/blob/04da0c76a0ebc4780c92aeea32dab60fb950e727/torch/csrc/autograd/engine.cpp#L985-L992

**Comment by soulitzer** [comment]
@crcrpar the issue with `"Trying to use a saved tensor that has been detached in-place, i.e. with .detach_()` should be that you also need to modify codegen to pass in grad_fn to unpack. 
By specifying is_output=True when you construct the SavedVariable, it no longer stores grad_fn onto itself to avoid the reference cycle, but this means that it also expects you to provide that grad_fn yourself when you go to use it later.
