### ISSUE TITLE
[Compile][Triton] Internal Triton PTX: Kernel parameter size too large

### ISSUE THREAD

**Issue by bohnstingl** [pytorch/pytorch#105522]
### 🐛 Describe the bug

I am facing issues when using `torch.compile(...)` during the training process of my network. In particular, during the backward path I get the error:
`error   : Feature 'Kernel parameter size larger than 4352 bytes' requires PTX ISA .version 8.1 or later`
This is independent of whether I use the default mode, or whether I use the mode of reduce-overhead.

I observe this error if the length of the sequence that I use as an input to the compiled function exceeds a certain limit.
For example, if the input shape is 120x64x140, the function compiles correctly and the forward as well as the backward path are accelerated. However, if the shape is 200x64x140, then the backward path fails with the mentioned error.

### Error logs

```
[2023-07-19 03:59:43,404] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_env
/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py:129: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-07-19 04:00:14,499] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: produce_guards
Traceback (most recent call last):
  File "/u/gsaboh/RNN-T_git/model/../pylib/PT2_function_test_minified.py", line 176, in <module>
    loss.backward()
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 3092, in backward
    out = call_compiled_backward()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 3062, in call_compiled_backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 33, in _wrapped_bw_compiler
    return disable(disable(bw_compiler)(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 260, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 179, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1024, in bw_compiler
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 48, in newFunction
    return old_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 303, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 516, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/graph.py", line 925, in compile_to_fn
    return self.compile_to_module().call
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 179, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/graph.py", line 897, in compile_to_module
    mod = PyCodeCache.load_by_key_path(key, path, linemap=linemap)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 964, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_gsaboh/kb/ckbdukshckdd3pv4gzjikragzerd6bwwvwmki7cu3eyjs7tixhyc.py", line 135, in <module>
    triton_poi_fused_add_mul_select_backward_sigmoid_backward_2 = async_compile.triton('triton_', '''
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1213, in triton
    return _load_kernel(kernel_name, source_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1083, in _load_kernel
    kernel.precompile()
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/triton_heuristics.py", line 160, in precompile
    self.launchers = [
                     ^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/triton_heuristics.py", line 161, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/triton_heuristics.py", line 190, in _precompile_config
    binary = triton.compile(
             ^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/triton/compiler/compiler.py", line 494, in compile
    next_module = compile_kernel(module)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/triton/compiler/compiler.py", line 369, in <lambda>
    lambda src: ptx_to_cubin(src, arch))
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/triton/compiler/compiler.py", line 168, in ptx_to_cubin
    return compile_ptx_to_cubin(ptx, ptxas, arch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/compile-ptx-src-2384e2, line 25018; error   : Entry function 'triton__0d1d2d3d4d5d6d7d8d9d10d11d12d13d14d15d16d17d18d19d20d21d22d23d24d25d26d27d28d29d30d31d32d33d34d35d36d37d38d39d40d41d42d43d44d45d46d47d48d49d50d51d52d53d54d55d56d57d58d59d60d61d62d63d64d65d66d67d68d69d70d71d72d73d74d75d76d77d78d79d80d81d82d83d84d85d86d87d88d89d90d91d92d93d94d95d96d97d98d99d100d101d102d103d104d105d106d107d108d109d110d111d112d113d114d115d116d117d118d119d120d121d122d123d124d125d126d127d128d129d130d131d132d133d134d135d136d137d138d139d140d141d142d143d144d145d146d147d148d149d150d151d152d153d154d155d156d157d158d159d160d161d162d163d164d165d166d167d168d169d170d171d172d173d174d175d176d177d178d179d180d181d182d183d184d185d186d187d188d189d190d191d192d193d194d195d196d197d198d199d200d201d202d203d204d205d206d207d208d209d210d211d212d213d214d215d216d217d218d219d220d221d222d223d224d225d226d227d228d229d230d231d232d233d234d235d236d237d238d239d240d241d242d243d244d245d246d247d248d249d250d251d252d253d254d255d256d257d258d259d260d261d262d263d264d265d266d267d268d269d270d271d272d273d274d275d276d277d278d279d280d281d282d283d284d285d286d287d288d289d290d291d292d293d294d295d296d297d298d299d300d301d302d303d304d305d306d307d308d309d310d311d312d313d314d315d316d317d318d319d320d321d322d323d324d325d326d327d328d329d330d331d332d333d334d335d336d337d338d339d340d341d342d343d344d345d346d347d348d349d350d351d352d353d354d355d356d357d358d359d360d361d362d363d364d365d366d367d368d369d370d371d372d373d374d375d376d377d378d379d380d381d382d383d384d385d386d387d388d389d390d391d392d393d394d395d396d397d398d399d400d401d402d403d404d405d406d407d408d409d410d411d412d413d414d415d416d417d418d419d420d421d422d423d424d425d426d427d428d429d430d431d432d433d434d435d436d437d438d439d440d441d442d443d444d445d446d447d448d449d450d451d452d453d454d455d456d457d458d459d460d461d462d463d464d465d466d467d468d469d470d471d472d473d474d475d476d477d478d479d480d481d482d483d484d485d486d487d488d489d490d491d492d493d494d495d496d497d498d499d500d501d502d503d504d505d506d507d508d509d510d511d512d513d514d515d516d517d518d519d520d521d522d523d524d525d526d527d528d529d530d531d532d533d534d535d536d537d538d539d540d541d542d543d544d545d546d547d548d549d550d551d552d553d554d555d556d557d558d559d560d561d562d563d564d565d566d567d568d569d570d571d572d573d574d575d576d577d' uses too much parameter space (0x120c bytes, 0x1100 max).
ptxas /tmp/compile-ptx-src-2384e2, line 25018; error   : Feature 'Kernel parameter size larger than 4352 bytes' requires PTX ISA .version 8.1 or later
ptxas fatal   : Ptx assembly aborted due to errors
```

### Minified repro

```
from typing import List, Tuple, Optional, overload, Union, cast
import torch
import numpy as np
import time
import torch.optim as optim
from torch.nn.parameter import Parameter

class RNNTest():

    def __init__(self, device) -> None:
        w_ih = torch.empty((input_size, hidden_size), device=device)
        w_io = torch.empty((input_size, hidden_size), device=device)
        self.param1 = torch.cat([w_ih,w_io],1)
        self.param1.requires_grad_(True)

        w_hh = torch.empty((hidden_size, hidden_size), device=device)
        w_ho = torch.empty((hidden_size, hidden_size), device=device)
        self.param2 = torch.cat([w_hh,w_ho],1)
        self.param2.requires_grad_(True)
    
    def RNNScript(self,
        input,
        ):

        state1 = torch.zeros(64, 340, dtype=input.dtype, device=input.device)
        
        outs = []

        Wx = input @ self.param1
        Wx_inp, Wx_rec = torch.tensor_split(Wx, 2, 2)
        for wt_inp, wt_rec in zip(Wx_inp, Wx_rec):
            rec_mul_inp, rec_mul_rec = torch.tensor_split(state1 @ self.param2, 2, 1)
            input_prev = (wt_inp + rec_mul_inp)
            output_gate = (wt_rec + rec_mul_rec)

            state1 = 1. + input_prev * torch.sigmoid(output_gate)
            outs.append(state1)
        
        outs = torch.stack(outs)

        return outs, None

if __name__ == "__main__":

    input_size = 140
    hidden_size = 340
    batch_size = 64
    use_gpu = True

    forward_times = []
    backward_times = []

    if use_gpu:
        device = torch.device('cuda:0')
    else:
        device = None

    rnn_test = RNNTest(device)
    
    def count_kernels(guard):
        print("[pt2_compile] guard failed: ", guard)

    #rnnscript = torch.compile(rnn_test.RNNScript, mode='reduce-overhead', dynamic=False, fullgraph=True)
    rnnscript = torch.compile(rnn_test.RNNScript, dynamic=False, fullgraph=True)
    
    optimizer = optim.SGD([rnn_test.param1, rnn_test.param2], 0.1)

    optimizer.zero_grad()
    for execution in range(20):
        start_forward = time.time_ns()
        t_rnd = 200
        inp = torch.rand((t_rnd, batch_size, input_size))
        print(inp.shape)
        if use_gpu:
            inp = inp.cuda()
        
        out, state = rnnscript(inp)

        if use_gpu:
            torch.cuda.synchronize()
        stop_forward = time.time_ns()
        forward_times.append((stop_forward - start_forward) / (10 ** 9))
        
        loss = 1. - torch.sum(out)

        start_time_backward = time.time_ns()
        loss.backward()
        if use_gpu:
            torch.cuda.synchronize()
        stop_time_backward = time.time_ns()
        backward_times.append((stop_time_backward - start_time_backward) / (10 ** 9))
```
        

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitfb376f8
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.7 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.28

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.10.1.el8_7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 128
On-line CPU(s) list: 0-127
Thread(s) per core: 1
Core(s) per socket: 64
Socket(s): 2
NUMA node(s): 2
Vendor ID: AuthenticAMD
CPU family: 23
Model: 49
Model name: AMD EPYC 7742 64-Core Processor
Stepping: 0
CPU MHz: 3361.974
CPU max MHz: 2250.0000
CPU min MHz: 1500.0000
BogoMIPS: 4499.91
Virtualization: AMD-V
L1d cache: 32K
L1i cache: 32K
L2 cache: 512K
L3 cache: 16384K
NUMA node0 CPU(s): 0-63
NUMA node1 CPU(s): 64-127
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+3c400e7818
[pip3] torch==2.1.0a0+gitfb376f8
[pip3] torchaudio==2.1.0a0+cf53a48
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.8.0 h6a678d5_0
[conda] magma-cuda118 2.6.1 1 pytorch
[conda] mkl 2023.1.0 h6d00ec8_46342
[conda] mkl-include 2023.1.0 h06a4308_46342
[conda] mkl-service 2.4.0 py311h5eee18b_1
[conda] mkl_fft 1.3.6 py311ha02d727_1
[conda] mkl_random 1.2.2 py311ha02d727_1
[conda] numpy 1.24.3 py311h08b1b3b_1
[conda] numpy-base 1.24.3 py311hf175353_1
[conda] pytorch-triton 2.1.0+3c400e7818 pypi_0 pypi
[conda] torch 2.1.0a0+gitfb376f8 pypi_0 pypi
[conda] torchaudio 2.1.0a0+cf53a48 dev_0 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
upgrade cuda to 12.1

**Comment by bohnstingl** [comment]
@ezyang I created a new environment with CUDA12.1 and installed the nightly build of PyTorch with cu121, but the error still persists. I have copied the new environment data below.

Can you reproduce this error? In a sense this is a somewhat critical error since torch.compile(...) cannot be used for training if the input to the function becomes larger.

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230720+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.8 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  1
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7763 64-Core Processor
Stepping:            1
CPU MHz:             2450.000
CPU max MHz:         3529.0520
CPU min MHz:         1500.0000
BogoMIPS:            4890.93
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-63
NUMA node1 CPU(s):   64-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] torch==2.1.0.dev20230720+cu121
[pip3] torchaudio==2.1.0.dev20230720+cu121
[pip3] torchvision==0.16.0.dev20230720+cu121
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-include               2023.1.0         h06a4308_46342  
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] torch                     2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230720+cu121          pypi_0    pypi
```

**Comment by bohnstingl** [comment]
@ezyang I could dive one step deeper on this and wrote a little code snippet:
```
import torch
print(torch.cuda.current_device())
from torch._inductor.cuda_properties import *
print('Torch reports the following properties about the GPU')
print(get_device_properties(0)) #Uses _get_device_properties(device), which in turn uses torch._C._cuda_init()

import triton
from triton.compiler.compiler import *
print('Triton reports the following properties about the GPU')
device = get_current_device()
print(device)
capability = get_device_capability(device)   #Internally refers back to torch.cuda.get_device_capability()
print(capability)

print('Architecture PT was compiled for')
print('PT supported architectures: ' + str(torch._C._cuda_getArchFlags()))
print('PT compiled version ' + str(torch._C._cuda_getCompiledVersion()))


print('Highest supported version of PTX for the GPU as reported from installed triton')
_, cuda_version = path_to_ptxas()
ptx_version = ptx_get_version(cuda_version)
print(ptx_version)
```

Yielding the output:
```
0
Torch reports the following properties about the GPU
_CudaDeviceProperties(name='NVIDIA A100-SXM4-40GB', major=8, minor=0, total_memory=40339MB, multi_processor_count=108)
Triton reports the following properties about the GPU
0
(8, 0)
Architecture PT was compiled for
PT supported architectures: sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90
PT compiled version 12010
Highest supported version of PTX for the GPU as reported from installed triton
81
```

As far as I can see, the installed triton version would be capable of using PTX ISA 8.1 and also reports it for the GPU in question. However, PyTorch reports just 8.0. Also the architecture that PyTorch was compiled for is correct.
Is there a way to determine the CUDA library path that torch picks up? Maybe it points unintentionally to the wrong directory?

**Comment by ezyang** [comment]
I think you're mixing up SM version (with an A100, you're sm_80 no matter what) and PTX ISA version. Unfortunately, I'm not sure if sm_80 supports PTX ISA 8.1 or not...

**Comment by bohnstingl** [comment]
Oh, my apologies for that. So at least from the scrip above triton reports that 8.1 would be supported. According to this [this table](https://docs.nvidia.com/cuda/parallel-thread-execution/#release-notes), it should be supported. 
I used a sample script from NVIDIA PTX and compiled it with PTX ISA 8.1 without any problems

```
#include <stdio.h>
#include <string.h>
#include "cuda.h"
#include "nvPTXCompiler.h"

#define NUM_THREADS 128
#define NUM_BLOCKS 32
#define SIZE NUM_THREADS * NUM_BLOCKS

#define CUDA_SAFE_CALL(x)                                               \
    do {                                                                \
        CUresult result = x;                                            \
        if (result != CUDA_SUCCESS) {                                   \
            const char *msg;                                            \
            cuGetErrorName(result, &msg);                               \
            printf("error: %s failed with error %s\n", #x, msg);        \
            exit(1);                                                    \
        }                                                               \
    } while(0)

#define NVPTXCOMPILER_SAFE_CALL(x)                                       \
    do {                                                                 \
        nvPTXCompileResult result = x;                                   \
        if (result != NVPTXCOMPILE_SUCCESS) {                            \
            printf("error: %s failed with error code %d\n", #x, result); \
            exit(1);                                                     \
        }                                                                \
    } while(0)


const char *ptxCode = "                                      \
   .version 8.1                                           \n \
   .target sm_80                                          \n \
   .address_size 64                                       \n \
   .visible .entry simpleVectorAdd(                       \n \
        .param .u64 simpleVectorAdd_param_0,              \n \
        .param .u64 simpleVectorAdd_param_1,              \n \
        .param .u64 simpleVectorAdd_param_2               \n \
   ) {                                                    \n \
        .reg .f32   %f<4>;                                \n \
        .reg .b32   %r<5>;                                \n \
        .reg .b64   %rd<11>;                              \n \
        ld.param.u64    %rd1, [simpleVectorAdd_param_0];  \n \
        ld.param.u64    %rd2, [simpleVectorAdd_param_1];  \n \
        ld.param.u64    %rd3, [simpleVectorAdd_param_2];  \n \
        cvta.to.global.u64      %rd4, %rd3;               \n \
        cvta.to.global.u64      %rd5, %rd2;               \n \
        cvta.to.global.u64      %rd6, %rd1;               \n \
        mov.u32         %r1, %ctaid.x;                    \n \
        mov.u32         %r2, %ntid.x;                     \n \
        mov.u32         %r3, %tid.x;                      \n \
        mad.lo.s32      %r4, %r2, %r1, %r3;               \n \
        mul.wide.u32    %rd7, %r4, 4;                     \n \
        add.s64         %rd8, %rd6, %rd7;                 \n \
        ld.global.f32   %f1, [%rd8];                      \n \
        add.s64         %rd9, %rd5, %rd7;                 \n \
        ld.global.f32   %f2, [%rd9];                      \n \
        add.f32         %f3, %f1, %f2;                    \n \
        add.s64         %rd10, %rd4, %rd7;                \n \
        st.global.f32   [%rd10], %f3;                     \n \
        ret;                                              \n \
   } ";

int elfLoadAndKernelLaunch(void* elf, size_t elfSize)
{
    CUdevice cuDevice;
    CUcontext context;
    CUmodule module;
    CUfunction kernel;
    CUdeviceptr dX, dY, dOut;
    size_t i;
    size_t bufferSize = SIZE * sizeof(float);
    float a;
    float hX[SIZE], hY[SIZE], hOut[SIZE];
    void* args[3];

    CUDA_SAFE_CALL(cuInit(0));
    CUDA_SAFE_CALL(cuDeviceGet(&cuDevice, 0));

    CUDA_SAFE_CALL(cuCtxCreate(&context, 0, cuDevice));
    CUDA_SAFE_CALL(cuModuleLoadDataEx(&module, elf, 0, 0, 0));
    CUDA_SAFE_CALL(cuModuleGetFunction(&kernel, module, "simpleVectorAdd"));

    // Generate input for execution, and create output buffers.
    for (i = 0; i < SIZE; ++i) {
        hX[i] = (float)i;
        hY[i] = (float)i * 2;
    }
    CUDA_SAFE_CALL(cuMemAlloc(&dX,   bufferSize));
    CUDA_SAFE_CALL(cuMemAlloc(&dY,   bufferSize));
    CUDA_SAFE_CALL(cuMemAlloc(&dOut, bufferSize));

    CUDA_SAFE_CALL(cuMemcpyHtoD(dX, hX, bufferSize));
    CUDA_SAFE_CALL(cuMemcpyHtoD(dY, hY, bufferSize));

    args[0] = &dX;
    args[1] = &dY;
    args[2] = &dOut;

    CUDA_SAFE_CALL( cuLaunchKernel(kernel,
                                   args, 0)); // arguments
    CUDA_SAFE_CALL(cuCtxSynchronize()); // Retrieve and print output.

    CUDA_SAFE_CALL(cuMemcpyDtoH(hOut, dOut, bufferSize));
    for (i = 0; i < SIZE; ++i) {
        printf("Result:[%ld]:%f\n", i, hOut[i]);
    }

    // Release resources.
    CUDA_SAFE_CALL(cuMemFree(dX));
    CUDA_SAFE_CALL(cuMemFree(dY));
    CUDA_SAFE_CALL(cuMemFree(dOut));
    CUDA_SAFE_CALL(cuModuleUnload(module));
    CUDA_SAFE_CALL(cuCtxDestroy(context));
    return 0;
}

int main(int _argc, char *_argv[])
{
    nvPTXCompilerHandle compiler = NULL;
    nvPTXCompileResult status;

    size_t elfSize, infoSize, errorSize;
    char *elf, *infoLog, *errorLog;
    unsigned int minorVer, majorVer;

    const char* compile_options[] = { "--gpu-name=sm_70",
                                      "--verbose"
                                    };

    NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetVersion(&majorVer, &minorVer));
    printf("Current PTX Compiler API Version : %d.%d\n", majorVer, minorVer);

    NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerCreate(&compiler,
                                                (size_t)strlen(ptxCode),  /* ptxCodeLen */
                                                ptxCode)                  /* ptxCode */
                            );

    status = nvPTXCompilerCompile(compiler,
                                  2,                 /* numCompileOptions */
                                  compile_options);  /* compileOptions */

    if (status != NVPTXCOMPILE_SUCCESS) {
        NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetErrorLogSize(compiler, &errorSize));

        if (errorSize != 0) {
            errorLog = (char*)malloc(errorSize+1);
            NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetErrorLog(compiler, errorLog));
            printf("Error log: %s\n", errorLog);
            free(errorLog);
        }
        exit(1);
    }

    NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetCompiledProgramSize(compiler, &elfSize));

    elf = (char*) malloc(elfSize);
    NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetCompiledProgram(compiler, (void*)elf));

    NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetInfoLogSize(compiler, &infoSize));

    if (infoSize != 0) {
        infoLog = (char*)malloc(infoSize+1);
        NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerGetInfoLog(compiler, infoLog));
        printf("Info log: %s\n", infoLog);
        free(infoLog);
    }

    NVPTXCOMPILER_SAFE_CALL(nvPTXCompilerDestroy(&compiler));

    // Load the compiled GPU assembly code 'elf'
    elfLoadAndKernelLaunch(elf, elfSize);

    free(elf);
    return 0;
}
```

The PTX code has 
```
.version x.x                                           \n \
.target sm_xx                                          \n \
```
in its first rows, right? Is there a way to tell which version triton uses there from the PyTorch side?

**Comment by bohnstingl** [comment]
I could identify the issue with the PTX ISA version and I raised an issue with triton

**Comment by bohnstingl** [comment]
The folks from Triton have increase the highest PTX ISA version to 8.2 and this will be effective in the newest builds of triton. PyTorch just needs to ensure that the latest build of triton is used. I see that the [file](https://github.com/pytorch/pytorch/blob/main/.ci/docker/triton_version.txt) uses triton fixed to 2.1.0, this needs to be monitored I guess?

**Comment by ezyang** [comment]
we just need to do another triton pin update

**Comment by ezyang** [comment]
send us a PR like this https://github.com/pytorch/pytorch/pull/105463
