### ISSUE TITLE
caffe.proto missing

### ISSUE THREAD

**Issue by louisabraham** [pytorch/pytorch#10558]
I installed the CPU only version on Ubuntu with `conda install -c caffe2 caffe2`.

`caffe_translator.py` is broken because [caffe.proto](https://github.com/caffe2/caffe2/tree/master/caffe/proto) is missing.

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/root/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/root/miniconda3/lib/python3.6/site-packages/caffe2/python/caffe_translator.py", line 12, in <module>
        from caffe.proto import caffe_pb2
    ModuleNotFoundError: No module named 'caffe'

**Comment by louisabraham** [comment]
Related issues:

- https://github.com/caffe2/caffe2/issues/342
- https://github.com/caffe2/caffe2/issues/2469

**Comment by louisabraham** [comment]
Using previous builds of caffe2 worked (py36_2018.07.20).

**Comment by hongsoog** [comment]
I got same problem and install caffe in caffe2 channel with following command
````
conda install -c caffe2 caffe1
````
Then, it goes well
Hope it would be help to you.

**Comment by louisabraham** [comment]
Thanks!
It seems logical, but I get

```
mbpla:~ louisabraham$ conda install -c caffe2 caffe1
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - caffe1
```

I suppose it doesn't work on macOS?

**Comment by louisabraham** [comment]
I think I tried it too. It just tried again to be sure:

```
mbpla:src louisabraham$ conda install -c caffe2 caffe
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - caffe
```

Do you know which one it is on [this page](https://anaconda.org/search?q=caffe)?

**Comment by jaewoosong** [comment]
I typed the exactly same command and my anaconda found the environment... for your reference:

```
jaewoo@jaewoo-pc:~/Repositories/github/pytorch$ conda install -c caffe2 caffe
Solving environment: done

## Package Plan ##

  environment location: /home/jaewoo/Programs/anaconda3

  added / updated specs: 
    - caffe


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    caffe-1.0                  |   py36h0c9280d_3         2.4 MB

The following NEW packages will be INSTALLED:

    caffe:          1.0-py36h0c9280d_3   
    leveldb:        1.20-hf484d3e_1      
    lmdb:           0.9.22-hf484d3e_1    
    python-gflags:  3.1.2-py36_0         
    python-leveldb: 0.20-py36hf484d3e_1  

The following packages will be DOWNGRADED:

    boost:          1.67.0-py36_4         --> 1.65.1-py36_4        
    libboost:       1.67.0-h46d08c1_4     --> 1.65.1-habcd387_4    
    py-boost:       1.67.0-py36h04863e7_4 --> 1.65.1-py36hf484d3e_4

Proceed ([y]/n)?
```

**Comment by louisabraham** [comment]
I have no idea why…

**Comment by mrgloom** [comment]
Get same error when installed from wheel on Mac OS:

 `pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

```
git clone https://github.com/pytorch/pytorch.git
python pytorch/caffe2/python/caffe_translator.py PCN/model/PCN-1.prototxt PCN/model/PCN.caffemodel --init_net init_net.pb --predict_net predict_net.pb
Traceback (most recent call last):
  File "pytorch/caffe2/python/caffe_translator.py", line 12, in <module>
    from caffe.proto import caffe_pb2
ModuleNotFoundError: No module named 'caffe.proto'
```

```
python -m caffe2.python.caffe_translator PCN/model/PCN-1.prototxt PCN/model/PCN.caffemodel
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/caffe2/python/caffe_translator.py", line 12, in <module>
    from caffe.proto import caffe_pb2
ModuleNotFoundError: No module named 'caffe.proto'
```

**Comment by mrgloom** [comment]
Using miniconda:
```
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

```
conda install pytorch-nightly-cpu -c pytorch

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-nightly-cpu

Current channels:

  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mrgloom** [comment]
Actually looks like problem was that Ihave clone caffe repo in the same dir from where I run the script and python was thinking that it's a `caffe` package, running from other dir gives me 

Running on pytorch cloned dir:
```
python pytorch_git/caffe2/python/caffe_translator.py
Traceback (most recent call last):
  File "pytorch_git/caffe2/python/caffe_translator.py", line 12, in <module>
    from caffe.proto import caffe_pb2
ModuleNotFoundError: No module named 'caffe'
```


python -m caffe2.python.caffe_translator
```
Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/user/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user/miniconda3/lib/python3.6/site-packages/caffe2/python/caffe_translator.py", line 12, in <module>
    from caffe.proto import caffe_pb2
ModuleNotFoundError: No module named 'caffe'
```

So should I point to caffe repo?

I have set `CAFFE_ROOT` like here but doesn't help
https://github.com/caffe2/tutorials/blob/master/Getting_Caffe1_Models_for_Translation.ipynb

**Comment by soumith** [comment]
`import caffe` should be available (caffe with python bindings should be correctly installed). That's the problem.
