### ISSUE TITLE
[Compile] Backward path using torch.compile(..., dynamic=True) is raising Exception

### ISSUE THREAD

**Issue by bohnstingl** [pytorch/pytorch#105524]
### 🐛 Describe the bug

When using a torch.compile(..., dynamic=True) during training, an exception is raised. The very same code compiles and runs fine when using torch.compile(..., dynamic=False).

This error is independent whether mode=default or mode=reduce-overhead. Furthermore, it is also independent whether fullgraph=True, or fullgraph=False

### Error logs

```
[2023-07-19 04:14:11,688] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_env
[2023-07-19 04:14:11,726] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_symbol s0 = 120 for L['input'].size()[0]
[2023-07-19 04:14:11,753] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_symbol s1 = 64 for L['input'].size()[1]
[2023-07-19 04:14:11,755] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_symbol s2 = 140 for L['input'].size()[2]
[2023-07-19 04:14:11,772] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_symbol s3 = 680 for L['self'].param1.size()[1]
[2023-07-19 04:14:11,818] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Mod(s3, 2) <= 0 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_dynamo/utils.py:1353 in run_node)
[2023-07-19 04:14:11,827] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval (s3//2) < s3 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_decomp/decompositions.py:693 in slice_forward)
[2023-07-19 04:14:11,850] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne((s3//2), 1) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,859] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval (s3//2) >= 2 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,873] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Mod(s3, 2) <= 1 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_dynamo/utils.py:1353 in run_node)
[2023-07-19 04:14:11,879] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval 2*((s3//2)) >= s3 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_decomp/decompositions.py:693 in slice_forward)
[2023-07-19 04:14:11,896] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s0*s1*s3 - s0*s1*(s3//2), 0) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,901] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s3 - (s3//2), 1) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,902] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s3, s3 - (s3//2)) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,905] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval s3 - (s3//2) >= 2 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,906] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s3, s3 - (s3//2)) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:30 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:11,911] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq(s0, 120) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:31 in RNNScript (_dynamo/variables/tensor.py:651 in evaluate_expr)
[2023-07-19 04:14:12,151] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s1*s3 - s1*(s3//2), 0) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:31 in RNNScript (_meta_registrations.py:4179 in meta_select)
[2023-07-19 04:14:12,335] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_symbol s4 = 340 for L['self'].param2.size()[0]
[2023-07-19 04:14:12,348] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq(s4, 340) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:32 in RNNScript (_meta_registrations.py:1650 in meta_mm)
[2023-07-19 04:14:12,364] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(64*s3 - 64*(s3//2), 0) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:32 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:12,377] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq(s1, 64) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:33 in RNNScript (_subclasses/fake_tensor.py:674 in infer_size)
[2023-07-19 04:14:12,386] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s3 - (s3//2), 1) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:34 in RNNScript (_subclasses/fake_tensor.py:680 in infer_size)
[2023-07-19 04:14:12,390] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval s3 - (s3//2) >= 0 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:34 in RNNScript (_refs/__init__.py:362 in _broadcast_shapes)
[2023-07-19 04:14:12,392] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval s3 - (s3//2) >= 0 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:34 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:12,395] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval s3 - (s3//2) >= 1 [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:34 in RNNScript (_ops.py:437 in __call__)
[2023-07-19 04:14:12,407] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(s3 - (s3//2), -1) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:36 in RNNScript (_prims_common/__init__.py:799 in infer_size)
[2023-07-19 04:14:12,420] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq((s3//2), s3 - (s3//2)) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:36 in RNNScript (_subclasses/fake_tensor.py:674 in infer_size)
[2023-07-19 04:14:12,431] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq((s3//2), 340) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:32 in RNNScript (_meta_registrations.py:1650 in meta_mm)
[2023-07-19 04:14:15,686] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Ne(7680*s3 - 7680*(s3//2), 0) [guard added] (_ops.py:437 in __call__)
/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/overrides.py:111: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/overrides.py:112: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/overrides.py:118: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/overrides.py:119: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
[2023-07-19 04:14:24,588] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq(340, (s3//2)) [guard added] (autograd/__init__.py:319 in grad)
[2023-07-19 04:14:31,249] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval 7680*s3 - 7680*(s3//2) >= 0 [guard added] (_prims/__init__.py:643 in _clone_meta)
/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py:129: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-07-19 04:14:48,731] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval (s3//2) < s3 [guard added] (_inductor/ir.py:1607 in create)
[2023-07-19 04:14:48,740] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq(2*((s3//2)), s3) [guard added] (_inductor/ir.py:1607 in create)
[2023-07-19 04:14:48,743] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval (s3//2) < 2*((s3//2)) [guard added] (_inductor/ir.py:1608 in create)
[2023-07-19 04:14:48,899] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval 64*s3 - 64*(s3//2) >= 2 [guard added] (_prims_common/__init__.py:205 in is_contiguous)
[2023-07-19 04:14:48,903] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq((s3//2), 340) [guard added] (_inductor/kernel/mm_common.py:129 in mm_args)
[2023-07-19 04:14:51,787] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval 64*((s3//2)) < 2147483648 [guard added] (_inductor/codegen/triton.py:2177 in can_use_32bit_indexing)
[2023-07-19 04:14:51,794] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval 64*s3 < 2147483648 [guard added] (_inductor/codegen/triton.py:2179 in can_use_32bit_indexing)
[2023-07-19 04:14:51,800] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval 7680*s3 < 2147483648 [guard added] (_inductor/codegen/triton.py:2179 in can_use_32bit_indexing)
[2023-07-19 04:14:54,677] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: produce_guards
[2023-07-19 04:15:00,230] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Eq((s3//2), s3 - (s3//2)) == True, this could result in accuracy problems
[2023-07-19 04:15:00,232] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: eval Eq((s3//2), s3 - (s3//2)) [guard added] at u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py:41 in RNNScript (_inductor/lowering.py:326 in broadcast_symbolic_shapes)
Traceback (most recent call last):
  File "/u/gsaboh/RNN-T_git/model/../pylib/PT2_testfile.py", line 89, in <module>
    loss.backward()
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 3092, in backward
    out = call_compiled_backward()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 3062, in call_compiled_backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 33, in _wrapped_bw_compiler
    return disable(disable(bw_compiler)(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 260, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 179, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1024, in bw_compiler
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 48, in newFunction
    return old_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 303, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 502, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 179, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/graph.py", line 418, in run
    return super().run(*args)
           ^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/graph.py", line 674, in run_node
    result = super().run_node(n)
             ^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/graph.py", line 565, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/graph.py", line 562, in call_function
    out = lowerings[target](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/lowering.py", line 281, in wrapped
    out = decomp_fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/torch/_inductor/lowering.py", line 1900, in slice_scatter
    if start is not None and start < 0:
                             ^^^^^^^^^
  File "/dccstor/datasets_nic/conda_boh/envs/rnnt_pytorch_git/lib/python3.11/site-packages/sympy/core/relational.py", line 510, in __bool__
    raise TypeError("cannot determine truth value of Relational")
torch._inductor.exc.LoweringException: TypeError: cannot determine truth value of Relational
  target: aten.slice_scatter.default
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float32,
      def inner_fn(index):
          i0, i1 = index
          tmp0 = ops.constant(0, torch.float32)
          return tmp0
      ,
      ranges=[64, s3],
      origin_node=full_1,
      origins={full_1}
    )
  ))
  args[1]: TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float32,
      def inner_fn(index):
          i0, i1 = index
          tmp0 = ops.load(tangents_1, i1 + 7616 * FloorDiv(s3, 2) + i0 * FloorDiv(s3, 2))
          tmp1 = ops.load(add_720, i1 + i0 * FloorDiv(s3, 2))
          tmp2 = tmp0 * tmp1
          tmp3 = ops.load(sigmoid_119, i1 + i0 * s3 + -1 * FloorDiv(s3, 2))
          tmp4 = ops.constant(1, torch.float32)
          tmp5 = ops.load(sigmoid_119, i1 + i0 * s3 + -1 * FloorDiv(s3, 2))
          tmp6 = tmp4 - tmp5
          tmp7 = tmp3 * tmp6
          tmp8 = tmp2 * tmp7
          return tmp8
      ,
      ranges=[64, (s3//2)],
      origin_node=mul_124,
      origins={mul_124, sub, mul_123, mul_121}
    )
  ))
  args[2]: 1
  args[3]: (s3//2)
  args[4]: 2*((s3//2))
```

### Minified repro

```
from typing import List, Tuple, Optional, overload, Union, cast
import torch
import numpy as np
import time
import torch.optim as optim
from torch.nn.parameter import Parameter

class RNNTest():

    def __init__(self, device) -> None:
        w_ih = torch.empty((input_size, hidden_size), device=device)
        w_io = torch.empty((input_size, hidden_size), device=device)
        self.param1 = torch.cat([w_ih,w_io],1)
        self.param1.requires_grad_(True)

        w_hh = torch.empty((hidden_size, hidden_size), device=device)
        w_ho = torch.empty((hidden_size, hidden_size), device=device)
        self.param2 = torch.cat([w_hh,w_ho],1)
        self.param2.requires_grad_(True)
    
    def RNNScript(self,
        input,
        ):

        state1 = torch.zeros(64, 340, dtype=input.dtype, device=input.device)
        
        outs = []

        Wx = input @ self.param1
        Wx_inp, Wx_rec = torch.tensor_split(Wx, 2, 2)
        for wt_inp, wt_rec in zip(Wx_inp, Wx_rec):
            rec_mul_inp, rec_mul_rec = torch.tensor_split(state1 @ self.param2, 2, 1)
            input_prev = (wt_inp + rec_mul_inp)
            output_gate = (wt_rec + rec_mul_rec)

            state1 = 1. + input_prev * torch.sigmoid(output_gate)
            outs.append(state1)
        
        outs = torch.stack(outs)

        return outs, None

if __name__ == "__main__":

    input_size = 140
    hidden_size = 340
    batch_size = 64
    use_gpu = True

    forward_times = []
    backward_times = []

    if use_gpu:
        device = torch.device('cuda:0')
    else:
        device = None

    rnn_test = RNNTest(device)
    
    def count_kernels(guard):
        print("[pt2_compile] guard failed: ", guard)

    #rnnscript = torch.compile(rnn_test.RNNScript, mode='reduce-overhead', dynamic=False, fullgraph=True)
    rnnscript = torch.compile(rnn_test.RNNScript, mode='reduce-overhead', dynamic=True, fullgraph=False)
    #rnnscript = torch.compile(rnn_test.RNNScript, dynamic=True, fullgraph=True)
    
    optimizer = optim.SGD([rnn_test.param1, rnn_test.param2], 0.1)

    optimizer.zero_grad()
    for execution in range(20):
        start_forward = time.time_ns()
        t_rnd = 120
        inp = torch.rand((t_rnd, batch_size, input_size))
        print(inp.shape)
        if use_gpu:
            inp = inp.cuda()
        
        out, state = rnnscript(inp)

        if use_gpu:
            torch.cuda.synchronize()
        stop_forward = time.time_ns()
        forward_times.append((stop_forward - start_forward) / (10 ** 9))
        
        loss = 1. - torch.sum(out)

        start_time_backward = time.time_ns()
        loss.backward()
        if use_gpu:
            torch.cuda.synchronize()
        stop_time_backward = time.time_ns()
        backward_times.append((stop_time_backward - start_time_backward) / (10 ** 9))
```
        

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitfb376f8
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.7 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.28

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.10.1.el8_7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 128
On-line CPU(s) list: 0-127
Thread(s) per core: 1
Core(s) per socket: 64
Socket(s): 2
NUMA node(s): 2
Vendor ID: AuthenticAMD
CPU family: 23
Model: 49
Model name: AMD EPYC 7742 64-Core Processor
Stepping: 0
CPU MHz: 3361.974
CPU max MHz: 2250.0000
CPU min MHz: 1500.0000
BogoMIPS: 4499.91
Virtualization: AMD-V
L1d cache: 32K
L1i cache: 32K
L2 cache: 512K
L3 cache: 16384K
NUMA node0 CPU(s): 0-63
NUMA node1 CPU(s): 64-127
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+3c400e7818
[pip3] torch==2.1.0a0+gitfb376f8
[pip3] torchaudio==2.1.0a0+cf53a48
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.8.0 h6a678d5_0
[conda] magma-cuda118 2.6.1 1 pytorch
[conda] mkl 2023.1.0 h6d00ec8_46342
[conda] mkl-include 2023.1.0 h06a4308_46342
[conda] mkl-service 2.4.0 py311h5eee18b_1
[conda] mkl_fft 1.3.6 py311ha02d727_1
[conda] mkl_random 1.2.2 py311ha02d727_1
[conda] numpy 1.24.3 py311h08b1b3b_1
[conda] numpy-base 1.24.3 py311hf175353_1
[conda] pytorch-triton 2.1.0+3c400e7818 pypi_0 pypi
[conda] torch 2.1.0a0+gitfb376f8 pypi_0 pypi
[conda] torchaudio 2.1.0a0+cf53a48 dev_0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
Confirmed reproduces

**Comment by ezyang** [comment]
```
diff --git a/torch/_inductor/lowering.py b/torch/_inductor/lowering.py
index 517e329ce84..1cb6bc12b7b 100644
--- a/torch/_inductor/lowering.py
+++ b/torch/_inductor/lowering.py
@@ -1897,9 +1897,9 @@ def slice_scatter(x, src, dim=0, start=None, end=None, step=1):
     x_loader = x.make_loader()
     dim = _validate_dim(x, dim, 0)
     dim_size = x.get_size()[dim]
-    if start is not None and start < 0:
+    if start is not None and V.graph.sizevars.guard_static_bool(start < 0):
         start = start + dim_size
-    if end is not None and end < 0:
+    if end is not None and V.graph.sizevars.guard_static_bool(end < 0):
         end = end + dim_size
     if start is None:
         start = 0
diff --git a/torch/_inductor/sizevars.py b/torch/_inductor/sizevars.py
index 021f5ef6790..1e33ccacd9f 100644
--- a/torch/_inductor/sizevars.py
+++ b/torch/_inductor/sizevars.py
@@ -339,6 +339,11 @@ class SizeVarAllocator:
         self.guard_equals(left, sympy.Integer(right))
         return int(right)
 
+    def guard_static_bool(self, left: Expr) -> bool:
+        right = self.shape_env.evaluate_expr(left)
+        self.guard_equals(left, sympy.sympify(right))
+        return bool(right)
+
     def guard_static_shapes(self, left: List[Expr]) -> List[int]:
         return [self.guard_static_shape(x) for x in left]
 ```

This patch fixes it, I'm going to prepare a more comprehensive version of it with some refactors.

**Comment by ezyang** [comment]
Note that the produced Triton kernel takes a veeeery long time to compile lol
