### ISSUE TITLE
[dynamo] Some issue with assert and context manager 

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#105513]
### 🐛 Describe the bug

```
import torch

def fn(x):
    with torch.no_grad():
        assert x.max() < 5, f"invalid max {x.max()}"
        x = torch.sin(x)
    return x

x = torch.randn(4)
ref = fn(x)

opt_fn = torch.compile(fn, backend="aot_eager")
res = opt_fn(x)

```

Error

```
Traceback (most recent call last):
  File "/data/users/anijain/pytorch/examples/ctx_assert.py", line 20, in <module>
    res = opt_fn(x, y)
  File "/data/users/anijain/pytorch/torch/_dynamo/eval_frame.py", line 294, in _fn
    return fn(*args, **kwargs)
  File "/data/users/anijain/pytorch/examples/ctx_assert.py", line 5, in fn
    def fn(x, y):
  File "/data/users/anijain/pytorch/examples/ctx_assert.py", line 6, in <resume in fn>
    with record_function("## test ##"):
TypeError: 'str' object is not callable
```

### Versions

N/A

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by anijain2305** [comment]
cc @yanboliang
