### ISSUE TITLE
torch.nn.MultiheadAttention lacks parameter validation check

### ISSUE THREAD

**Issue by PhyllisJi** [pytorch/pytorch#105630]
### Description:
torch.nn.MultiheadAttention lacks parameter validation check, and when invalid values are given, they are used in subsequent computations, leading to errors such as division by zero.

### Examples:
input:
```
p = torch.nn.MultiheadAttention(embed_dim=0, num_heads=100)
```
error_message:
```
D:\PythonProjects\venv\lib\site-packages\torch\nn\init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Traceback (most recent call last):
  File "D:\PythonProjects\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-beae84d8539c>", line 1, in <module>
    p = torch.nn.MultiheadAttention(embed_dim=0, num_heads=100)
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\modules\activation.py", line 996, in __init__
    self._reset_parameters()
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\modules\activation.py", line 1000, in _reset_parameters
    xavier_uniform_(self.in_proj_weight)
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\init.py", line 324, in xavier_uniform_
    std = gain * math.sqrt(2.0 / float(fan_in + fan_out))
ZeroDivisionError: float division by zero
```

input:
```
p = torch.nn.MultiheadAttention(embed_dim=100, num_heads=0)
```
error_message:
```
Traceback (most recent call last):
  File "D:\PythonProjects\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-e98ed2bc208f>", line 1, in <module>
    p = torch.nn.MultiheadAttention(embed_dim=100, num_heads=0)
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\modules\activation.py", line 968, in __init__
    self.head_dim = embed_dim // num_heads
ZeroDivisionError: integer division or modulo by zero
```

input:
```
p = torch.nn.MultiheadAttention(embed_dim=-1, num_heads=1)
```
error_message:
```
Traceback (most recent call last):
  File "D:\PythonProjects\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-c05504f1df61>", line 1, in <module>
    p = torch.nn.MultiheadAttention(embed_dim=-1, num_heads=1)
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\modules\activation.py", line 977, in __init__
    self.in_proj_weight = Parameter(torch.empty((3 * embed_dim, embed_dim), **factory_kwargs))
RuntimeError: Trying to create tensor with negative dimension -3: [-3, -1]
```

### Versions

PS D:\PythonProjects\venv\Lib\site-packages\torch\utils> python collect_env.py
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU
Nvidia driver version: 532.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2200
DeviceID=CPU0
Family=207
L2CacheSize=16384
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2200
Name=13th Gen Intel(R) Core(TM) i9-13900HX
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2+cu117
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by jbschlosser** [comment]
We'd accept a PR with the proper checks for nicer error messages.
