### ISSUE TITLE
torch.nn.TransformerDecoderLayer lacks parameter validation check

### ISSUE THREAD

**Issue by PhyllisJi** [pytorch/pytorch#105632]
### Description:
torch.nn.TransformerDecoderLayer lacks parameter validation check, and when invalid values are given, they are used in subsequent computations, leading to errors such as division by zero.

### Examples:
input:
```
p = torch.nn.TransformerDecoderLayer(d_model=10, nhead=0)
```
error_message:
```
Traceback (most recent call last):
  File "D:\PythonProjects\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-6f43c243aac4>", line 1, in <module>
    p = torch.nn.TransformerDecoderLayer(d_model=10, nhead=0)
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\modules\transformer.py", line 653, in __init__
    self.self_attn = MultiheadAttention(d_model, nhead, dropout=dropout, batch_first=batch_first,
  File "D:\PythonProjects\venv\lib\site-packages\torch\nn\modules\activation.py", line 968, in __init__
    self.head_dim = embed_dim // num_heads
ZeroDivisionError: integer division or modulo by zero

```

### Versions

PS D:\PythonProjects\venv\Lib\site-packages\torch\utils> python collect_env.py
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU
Nvidia driver version: 532.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2200
DeviceID=CPU0
Family=207
L2CacheSize=16384
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2200
Name=13th Gen Intel(R) Core(TM) i9-13900HX
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2+cu117
[conda] Could not collect

**Comment by franklinscudder** [comment]
Would the solution here be to add an 'if num_heads < 1: raise ValueError("...")' in the MultiHeadAttention class? Would we want a type check here too?

**Comment by PhyllisJi** [comment]
> Would the solution here be to add an 'if num_heads < 1: raise ValueError("...")' in the MultiHeadAttention class? Would we want a type check here too?

Sounds like a good solution

**Comment by taras-janea** [comment]
The issue is not reproducible on the latest PyTorch version, the parameter validation is in place, and reported in the described scenario:
```
ValueError: embed_dim and num_heads must be greater than 0, got embed_dim=10 and num_heads=0 instead
```
@PhyllisJi, please let me know if anything remains to be resolved within the scope of this issue.

**Comment by taras-janea** [comment]
Closing this issue due to inactivity. If you continue to experience this problem or have any related concerns, please don't hesitate to open a new issue.
