### ISSUE TITLE
[BUG]: unstable happend in saving model.

### ISSUE THREAD

**Issue by zyoohv** [pytorch/pytorch#10577]
## Issue description

When I save my model, I met the errors.

My environment:

system: debian 8   
python: python3   
pytorch: 0.4.1

## Code 

```python
    def save_model(self, epoch):
        # for example: save_path = '~/Documents/my_model_1.pth'.
        save_path = self.model_prefix + '_' + str(epoch) + '.pth'
        # note that my net: set.net is trained on GPU.
        torch.save(self.net.state_dict(), save_path)
        self.logging.info('Saved model in {}'.format(save_path))
```

## Error

```
Traceback (most recent call last):
  File "train_network.py", line 64, in <module>
    main()
  File "train_network.py", line 60, in main
    netutil.save_model(epoch)
  File "/opt/tiger/reid/attribute_net/network.py", line 169, in save_model
    torch.save(self.net.state_dict(), save_path)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 134, in _with_file_like
    return body(f)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 209, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 288, in _save
    serialized_storages[key]._write_file(f, _should_read_directly(f))
RuntimeError: Unknown error -1
```

**Comment by zou3519** [comment]
Could you provide a minimal reproducible script?

**Comment by noahcao** [comment]
same error occurs for me, under both 0.4.1 and 0.3.1 version of pytorch.

It's strange that, this program saves .pth after each epoch, and it can save successfully sometimes (for instance, for the first 3 epoches but fails for the 4th). I checked disk storage and memory, both are sufficient.

> Traceback (most recent call last):
  File "main-train.py", line 250, in <module> main()
  File "main-train.py", line 232, in main
 m.state_dict(), '../exp/{}/{}/model_{}.pth'.format(opt.dataset, opt.expID, opt.epoch))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 117, in _with_file_like
    return body(f)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 135, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 204, in _save
    serialized_storages[key]._write_file(f)
RuntimeError: Unknown error -1

    start_point = opt.epoch + 1
    for i in range(start_point, start_point + opt.nEpochs):
        opt.epoch = i

        print('############# Starting Epoch {} #############'.format(opt.epoch))
        loss, acc = train(train_loader, m, criterion, optimizer, writer)

        print('Train-{idx:d} epoch | loss:{loss:.8f} | acc:{acc:.4f}'.format(
            idx=opt.epoch,
            loss=loss,
            acc=acc
        ))

        opt.acc = acc
        opt.loss = loss
        m = m.module
        if (i - start_point) % opt.snapshot == 0:
            torch.save(
                **m.state_dict(), '../exp/{}/{}/model_{}.pth'.format(opt.dataset, opt.expID, opt.epoch))**
            torch.save(
                opt, '../exp/{}/{}/option.pth'.format(opt.dataset, opt.expID, opt.epoch))
            torch.save(
                optimizer, '../exp/{}/{}/optimizer.pth'.format(opt.dataset, opt.expID))

        m = torch.nn.DataParallel(m).cuda()
        loss, acc = valid(val_loader, m, criterion, optimizer, writer)

        print('Valid-{idx:d} epoch | loss:{loss:.8f} | acc:{acc:.4f}'.format(
            idx=i,
            loss=loss,
            acc=acc
        ))
    writer.close()

**Comment by noahcao** [comment]
Similar issue mentioned in https://github.com/pytorch/pytorch/issues/8477#issue-332298760 (issue 8477)

And I avoid the error mentioned above through simply add before torch.save:

> time.sleep(10)

But I think such issue should be fixed for further update or at least give more frinedly error message? thx a lot for all contributors for Pytorch

**Comment by henrylee2570** [comment]
Hi @noahcao, any hint why adding the `time.sleep()` avoid the error? Thanks

**Comment by noahcao** [comment]
@henrylee2570 Just like described in [#8477](https://github.com/pytorch/pytorch/issues/8477#issue-332298760), I believe this error occurs for a process killed by mistake due to a SIGCHLD signal. To add time.sleep(), I guess, make this signal handled already, then it would not call a terminal of a useful process.

**Comment by zyoohv** [comment]
And if I change the code 

```
torch.save(self.net.state_dict(), save_path)
```

to 

```
torch.save(self.net.cpu().state_dict(), save_path)
```

it works.

Until now, there are some method to overcome it, but I really hope pytorch can fix it.

**Comment by ezyang** [comment]
This really sounds like we're failing to synchronize before saving out a CUDA model.

**Comment by henrylee2570** [comment]
neither `time.sleep()` nor save 'model.cpu()' helps me out, I still have the issue...

**Comment by noahcao** [comment]
> neither `time.sleep()` nor save `model.cpu()` helps me out, I still have the issue...

@henrylee2570 sure that enough disk space for path to save model?

**Comment by henrylee2570** [comment]
@noahcao turns out `time.sleep()` was skipped sometimes in the main process, no idea why it happens... it does help if time.sleep operates properly, I'm ok now, thanks!

**Comment by sbelharbi** [comment]
Pytorch: 1.0.1
Python: 3.7.0

Make sure you have enough space on disc.
My code was working fine, then suddenly this error (related to saving the model) starts to show:
```sh
Traceback (most recent call last):
  File "train.py", line 250, in <module>
    torch.save(best_model.state_dict(), join(OUTD, "best_model.pt"))
  File "/home/usern290/Venvs/pytorch.1.0.1/lib/python3.7/site-packages/torch/serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/user290/Venvs/pytorch.1.0.1/lib/python3.7/site-packages/torch/serialization.py", line 143, in _with_file_like
    return body(f)
  File "/home/user290/Venvs/pytorch.1.0.1/lib/python3.7/site-packages/torch/serialization.py", line 218, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/user290/Venvs/pytorch.1.0.1/lib/python3.7/site-packages/torch/serialization.py", line 297, in _save
    serialized_storages[key]._write_file(f, _should_read_directly(f))
RuntimeError: write(): fd 29 failed with Input/output error
```
The server's disc was saturated....
After making some space, the code turns to work fine.

I think that the error message can be improved to be more clear!!!
