### ISSUE TITLE
Aten device operator triggers internal assert

### ISSUE THREAD

**Issue by anwang2009** [pytorch/pytorch#105766]
### 🐛 Describe the bug

```
import torch
torch.ops.aten.device.with_index('cuda', 0)
```

triggers an internal assert 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anwang/anaconda3/envs/dynamite/lib/python3.9/site-packages/torch/_ops.py", line 437, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: isString() INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue_inl.h":2308, please report a bug to PyTorch. Expected String but got Int
```

I expected no failure, since I supplied what looked like legitimate schema to the `with_index` operator according to this api:
```
Declaration: aten::device(str a) -> Device
Declaration: aten::device.with_index(str type, int index) -> Device
```

### Versions

```
PyTorch version: 2.1.0.dev20230720+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Pop!_OS 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.34

Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.11-76051511-generic-x86_64-with-glibc2.34
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           33
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     4950.1948
CPU min MHz:                     2200.0000
BogoMIPS:                        7400.51
Virtualization:                  AMD-V
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        6 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.12.4
[pip3] ema-pytorch==0.2.3
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.2
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.3
[pip3] torch==2.1.0.dev20230720+cu121
[pip3] torch-fidelity==0.3.0
[pip3] torchaudio==2.1.0.dev20230720+cu121
[pip3] torchdata==0.7.0.dev20230720
[pip3] torchmetrics==0.11.4
[pip3] torchrec-nightly==2023.6.22
[pip3] torchtext==0.16.0.dev20230720+rocm5.5
[pip3] torchvision==0.16.0.dev20230720+cu121
[pip3] triton==2.0.0
[pip3] vector-quantize-pytorch==1.6.24
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.12.4                   pypi_0    pypi
[conda] ema-pytorch               0.2.3                    pypi_0    pypi
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.3                    pypi_0    pypi
[conda] torch                     2.1.0a0+git25ed757           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torchdata                 0.7.0.dev20230720          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchrec-nightly          2023.6.22                pypi_0    pypi
[conda] torchtext                 0.16.0.dev20230720+rocm5.5          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230720+cu121          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
[conda] vector-quantize-pytorch   1.6.24                   pypi_0    pypi
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by janeyx99** [comment]
cc @thiagocrepaldi as the person who introduced this change. https://github.com/pytorch/pytorch/pull/97023

I don't think this is meant to be used as a userfacing API. https://pytorch.org/docs/stable/generated/torch.cuda.device.html should suffice.

**Comment by anwang2009** [comment]
I needed a lower-level api to dynamically get and apply the device info within a functionalized graph. This approach ended up working for me:

```
torch.ops.prim.device -> torch.ops.aten.to.dtype_layout
```

Thanks for taking a look!
