### ISSUE TITLE
DDP , error . [c10d] The client socket has timed out after 900s while trying to connect to (XX.XX.XX.XX, 8514). 

### ISSUE THREAD

**Issue by skyantao** [pytorch/pytorch#105782]
### 🐛 Describe the bug

code:
python -m torch.distributed.launch --use_env --nproc_per_node=${GPUS_PER_NODE} --nnodes=${WORKER_CNT} --node_rank=${RANK} \
          --master_addr="172.22.48.199" --master_port=${MASTER_PORT} cn_clip/training/main.py \

error:
[W socket.cpp:601] [c10d] The IPv6 network addresses of (XX.XX.XX.XX, 8514) cannot be retrieved (gai error: -2 - Name or service not known).
[E socket.cpp:860] [c10d] The client socket has timed out after 900s while trying to connect to (XX.XX.XX.XX, 8514).
Traceback (most recent call last):
  File "/mnt/e/wsldata/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/e/wsldata/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/mnt/e/wsldata/conda/envs/cnclip/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.27.0
Libc version: glibc-2.35

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 516.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          56
On-line CPU(s) list:             0-55
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              28
Socket(s):                       1
Stepping:                        4
BogoMIPS:                        5187.81
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       896 KiB (28 instances)
L1i cache:                       896 KiB (28 instances)
L2 cache:                        28 MiB (28 instances)
L3 cache:                        19.3 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] torch==2.0.0+cu117
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.0.0+cu117              pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by Mr-lonely0** [comment]
I have encountered the same issue.
Could you kindly advise on how to extend the timeout by configuring certain environment variables?

**Comment by c-p-i-o** [comment]
> PyTorch version: 2.0.0+cu117

Are you able to try with a newer PyTorch version (2.5)? We've addressed quite a few issues over the past year w.r.t. socket conns/tcpstore conns.

**Comment by Mr-lonely0** [comment]
> > PyTorch version: 2.0.0+cu117
> 
> Are you able to try with a newer PyTorch version (2.5)? We've addressed quite a few issues over the past year w.r.t. socket conns/tcpstore conns.
> 
> > @Mr-lonely0
> 
> Could you post the exact pytorch version + errors that you're seeing. In the past, these errors were a result of IP conflicts and/or inconsistencies in `/etc/hosts` file.

I appreciate your prompt response!
I am currently utilizing PyTorch version 2.4.0+cu121, and I am encountering the following error:

```text
[E108 20:04:34.467642512 socket.cpp:957] [c10d] The client socket has timed out after 900s while trying to connect to (33.145.124.128, 29500).
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 680, in run
    result = self._invoke_run(role)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 66, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
torch.distributed.DistNetworkError: The client socket has timed out after 900s while trying to connect to (33.145.124.128, 29500).
```

This error arises from the inconsistency in the speed of environment initialization across multiple machines. As a result, some workers commence distributed training and await communication, while others are still in the process of installing Python packages.
Therefore, I am seeking to set the timeout longer to wait for the slower workers.
Ideally, I would prefer to achieve this by setting specific environment variables rather than modifying the source code.

Looking forward to your early reply! :)

**Comment by Mr-lonely0** [comment]
Aha! I got it.
I can set `--rdzv_config rdzv_timeout=3600` in torchrun to increase the timeout!

**Comment by c-p-i-o** [comment]
> rdzv_timeout is an old deprecated way of setting the timeout.

You probably want just timeout:
```
         `rdzv_timeout` is a legacy argument that will be removed in future.
           Set the timeout via `rdzv_configs['timeout']`
   ```
But 900 is far too long waiting for a machine too connect to port `29500`. So I think we probably need to see if that port on target host is not open or there is a conflicting service running on that port.

**Comment by d4l3k** [comment]
**Category: Likely Fixed / Unreproducible**

This issue has been automatically closed. Please reopen if this is still an active issue.
