### ISSUE TITLE
Errors while trying to finetune compiled transformers model

### ISSUE THREAD

**Issue by eawer** [pytorch/pytorch#105802]
### 🐛 Describe the bug

I'm switching to Pytorch 2.0.1 and want to compile the model for training times improvement. I'm trying to compile the model according to the [docs](https://pytorch.org/blog/Accelerating-Hugging-Face-and-TIMM-models/#hugging-face-models), but it does not work and throws an error. 

The code looks this:

```python
model = AutoModelForSequenceClassification.from_pretrained(
    model_id, num_labels=num_labels, label2id=label2id, id2label=id2label
).to(device="cuda:0")
model = torch.compile(model, dynamic=True, fullgraph=True)

training_args = TrainingArguments(
    output_dir="./temp",
    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,
    learning_rate=5e-5,
    num_train_epochs=3,
    optim="adamw_torch_fused",
    logging_steps=1,
    logging_strategy="steps",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()
```

Here is the [link](https://colab.research.google.com/drive/1VnPcPyQ0Jg55Zn0x8pNJq-tQRX2IwIYR?authuser=2#scrollTo=DVrNg-2xmY7v) to colab version ("Pytorch API" section)

### Error logs

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-25-4dd917c6010c>](https://localhost:8080/#) in <cell line: 31>()
     29 )
     30 
---> 31 trainer.train()

2 frames
[/usr/local/lib/python3.10/dist-packages/transformers/trainer_pt_utils.py](https://localhost:8080/#) in get_model_param_count(model, trainable_only)
   1051             return p.numel()
   1052 
-> 1053     return sum(numel(p) for p in model.parameters() if not trainable_only or p.requires_grad)
   1054 
   1055 

AttributeError: 'function' object has no attribute 'parameters'
```

### Versions

PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.25.2
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        45 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by shunting314** [comment]
The colab link seems to be broken.

Can you provide a standalone script for repro?

**Comment by eawer** [comment]
@shunting314 hm, that's weird, for me it opens even in incognito mode. But here is the standalone script:

```python
import torch
import evaluate
import numpy as np
from datasets import load_dataset, DatasetDict
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments

def preprocess_function(examples):
  return tokenizer(examples["text"], truncation=True, padding=True, return_tensors='pt').to(device="cuda:0")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return metric.compute(predictions=predictions, references=labels, average="weighted")
  
model_id = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True, model_max_length=512)

dataset = load_dataset('banking77', split=['train[:2048]', 'test[:512]'])
dataset = DatasetDict({'train': dataset[0], 'test': dataset[1]})
dataset = dataset.map(preprocess_function, batched=True)

labels = dataset["train"].features["label"].names
num_labels = len(labels)
label2id, id2label = dict(), dict()
for i, label in enumerate(labels):
    label2id[label] = str(i)
    id2label[str(i)] = label

metric = evaluate.load("f1")

model = AutoModelForSequenceClassification.from_pretrained(
    model_id, num_labels=num_labels, label2id=label2id, id2label=id2label
).to(device="cuda:0")
model = torch.compile(model, dynamic=True, fullgraph=True)

training_args = TrainingArguments(
    output_dir="./temp",
    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,
    learning_rate=5e-5,
    num_train_epochs=3,
    optim="adamw_torch_fused",
    logging_steps=1,
    logging_strategy="steps",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()

```

**Comment by shunting314** [comment]
Hmm, I'm getting this error instead:
```
You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Traceback (most recent call last):
  File "/home/shunting/t.py", line 61, in <module>
    trainer.train()
  File "/home/shunting/ws/transformers/src/transformers/trainer.py", line 1526, in train
    return inner_training_loop(
  File "/home/shunting/ws/transformers/src/transformers/trainer.py", line 1774, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/shunting/.conda/envs/pytorch/lib/python3.10/site-packages/accelerate/data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/shunting/ws/pytorch/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/shunting/ws/pytorch/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/shunting/ws/pytorch/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/shunting/ws/transformers/src/transformers/data/data_collator.py", line 249, in __call__
    batch = self.tokenizer.pad(
  File "/home/shunting/ws/transformers/src/transformers/tokenization_utils_base.py", line 2993, in pad
    raise ValueError(
ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided ['label']
```

**Comment by eawer** [comment]
Indeed, you are right. The error I pasted appears if I run all the cells one by one in [this](https://colab.research.google.com/drive/1VnPcPyQ0Jg55Zn0x8pNJq-tQRX2IwIYR?usp=sharing) colab, even the model and the arguments are recreated, and that's pretty weird.

Regarding the error you are facing ([another colab](https://colab.research.google.com/drive/15C7AaubVJ7TT7Ck3gb2Mtdmujc3Elqmq?usp=sharing)) it goes away if I comment the line with `torch.compile` call, so the compilation still does not work as expected and as stated in the docs

**Comment by shunting314** [comment]
I tried this a bit. Without torch.compile on the model, a row of training data looks like
```
{'label': 11, 'input_ids': [101, 1045, 2572, 2145, 3403, 2006, 2026, 4003, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
```

but after applying torch.compile on the model, a row of training data looks like
```
{'label': 11}
```
Keys other than label are all get lost. This smells like relevant to dynamo. cc @voznesenskym  any ideas?

**Comment by msaroufim** [comment]
@shunting314 thanks for the nice summary, this now reminds me a lot of this issue https://github.com/pytorch/pytorch/issues/103099

**Comment by voznesenskym** [comment]
Help me debug this :) I get

`ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided ['label']`

Is there a smaller repro I can look at?

**Comment by eugene-kostrov** [comment]
@voznesenskym the smallest one is [this](https://colab.research.google.com/drive/15C7AaubVJ7TT7Ck3gb2Mtdmujc3Elqmq?usp=sharing) one

**Comment by eawer** [comment]
@voznesenskym the smallest one is [this](https://colab.research.google.com/drive/15C7AaubVJ7TT7Ck3gb2Mtdmujc3Elqmq?usp=sharing) one

**Comment by Crazy-LittleBoy** [comment]
same issue, any solution here?

**Comment by anijain2305** [comment]
@Crazy-LittleBoy Do you have a repro that I can try on my end?

**Comment by eawer** [comment]
@anijain2305 is https://github.com/pytorch/pytorch/issues/105802#issuecomment-1650216293 working for you?
