### ISSUE TITLE
"derivative for aten::linear_backward is not implemented" on mps (Apple Silicon) when using create_graph=True on autogrid

### ISSUE THREAD

**Issue by aa502aa** [pytorch/pytorch#105834]
### 🐛 Describe the bug

I have a NN model (see my code below) which uses the `create_graph = True` property on autogrid.grad, and this throws the error in the title. The full error is:

```/Users/B/Library/Python/3.9/lib/python/site-packages/torch/autograd/__init__.py:200: UserWarning: The operator 'aten::sgn.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/B/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/B/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/B/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/B/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/B/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/B/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/B/Desktop/d.py", line 190, in <module>
    main()
  File "/Users/B/Desktop/d.py", line 186, in main
    runmodel(epochs, lr1, lr2, gamma1, gamma2, step_size1, step_size2, N_interior, N_boundary)
  File "/Users/B/Desktop/d.py", line 152, in runmodel
    loss1.backward()
  File "/Users/B/Library/Python/3.9/lib/python/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/Users/B/Library/Python/3.9/lib/python/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: derivative for aten::linear_backward is not implemented
```

The code works fine on CPU and on CUDA. It's just MPS that has a problem, but when I set `create_graph = False`, it works on MPS too, however I don't want to do that. 

I thought this had been fixed in a previous bug report, so I am not sure what's going on. I'm on a 16GB Apple M1 Pro, macOS 13.2.

I'm on Python 3.9.6 and pytorch 2.0.1.  Here is my code:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim, autograd
import time
from math import pi
import numpy as np
import sobol_seq as sobol
 
class Block(nn.Module):
 

    def __init__(self, in_N, width, out_N):
        super(Block, self).__init__()
        self.L1 = nn.Linear(in_N, width)
        self.L2 = nn.Linear(width, out_N)
        self.phi = nn.Tanh()

    def forward(self, x):
        return self.phi(self.L2(self.phi(self.L1(x)))) + x


class drrnn(nn.Module):
 
    def __init__(self, in_N, m, out_N, depth=4):
        super(drrnn, self).__init__()
        self.in_N = in_N
        self.m = m
        self.out_N = out_N
        self.depth = depth
        self.phi = torch.nn.Tanh()
        self.stack = torch.nn.ModuleList()
        self.stack.append(torch.nn.Linear(in_N,m))

        for i in range(depth):
            self.stack.append(Block(m,m, m))
        # last layer
        self.stack.append(torch.nn.Linear(m, out_N))

    def forward(self, x):
        # first layer
        for i in range(len(self.stack)):
            x = self.stack[i](x)
        return x


def get_interior_points(N=128):
 
    x1 = sobol.i4_sobol_generate(2, N)  
    return torch.from_numpy(x1).float() 


def get_boundary_points(N=33):
    index = sobol.i4_sobol_generate(1, N)
    xb1 = np.concatenate((index, np.zeros_like(index)), 1)
    xb2 = np.concatenate((index, np.ones_like(index)), 1)
    xb4 = np.concatenate((np.zeros_like(index), index), 1)
    xb6 = np.concatenate((np.ones_like(index), index), 1)
    xb = torch.from_numpy(np.concatenate((xb1, xb2, xb4, xb6), 0)).float()

    return xb


def weights_init(m):
    if isinstance(m, (nn.Conv2d, nn.Linear)):
        nn.init.xavier_normal_(m.weight)
        nn.init.constant_(m.bias, 0.0)


def exact_sol(x):
    value = torch.where(x[:, 0: 1] > 0.5, (1 - x[:, 0: 1]) ** 2, x[:, 0: 1] ** 2)  
    return value


def function_l_exact(x):
    return x[:, 0: 1] * x[:, 1: 2] * (1 - x[:, 0: 1]) * (1 - x[:, 1: 2])


def function_f():
    return -2


def gradients(input, output):
    return autograd.grad(outputs=output, inputs=input,
                                grad_outputs=torch.ones_like(output),
                                create_graph=True, retain_graph=True, only_inputs=True)[0]

def error_l2(x, y):
 
    return torch.norm(x - y) / torch.norm(y)


def runmodel(epochs: int,
             lr1, lr2,
             gamma1, gamma2,
             step_size1, step_size2, N_interior, N_boundary):

    seed = 123
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

    in_N = 2
    m = 40
    out_N = 1

    device = torch.device("mps")
    soln_nn = drrnn(in_N, m, out_N).to(device) # solution
    soln_nn.apply(weights_init)
    test_function_nn = drrnn(in_N, m, out_N).to(device) # the test function
    test_function_nn.apply(weights_init)
    optimizer_solution = optim.Adam(soln_nn.parameters(), lr=lr1)
    optimizer_test_function = optim.Adam(test_function_nn.parameters(), lr=lr2)


    StepLR1 = torch.optim.lr_scheduler.StepLR(optimizer_solution, step_size=step_size1, gamma=gamma1)
    StepLR2 = torch.optim.lr_scheduler.StepLR(optimizer_test_function, step_size=step_size2, gamma=gamma2)
    tt = time.time()
    f_value = function_f()
    xr = get_interior_points(N_interior)
    xb = get_boundary_points(N_boundary)
    xr = xr.to(device)
    xb = xb.to(device)
    for epoch in range(epochs+1):

        xr.requires_grad_()
        output_r = soln_nn(xr)
        output_b = soln_nn(xb)
        output_phi_r = test_function_nn(xr) * function_l_exact(xr)
        exact_b = exact_sol(xb)
        grads_u = gradients(xr, output_r)
        grads_phi = gradients(xr, output_phi_r)

        loss_r = torch.square(torch.mean(torch.sum(grads_u * grads_phi, dim=1) - f_value * output_phi_r)) / torch.mean(torch.square(output_phi_r))
        loss_b = 10 * torch.mean(torch.abs(output_b - exact_b))
        
        loss1 = loss_r + loss_b
        loss2 = - loss_r + torch.square(torch.mean(torch.square(output_phi_r)) - 1)

        if epoch % 3 == 2:
            optimizer_test_function.zero_grad()
            loss2.backward()
            optimizer_test_function.step()
            StepLR2.step()
        else:
            optimizer_solution.zero_grad()
            loss1.backward()
            optimizer_solution.step()
            StepLR1.step()

        if epoch % 100 == 0:
            err = error_l2(soln_nn(xr), exact_sol(xr))
            print('epoch:', epoch, 'loss1:', loss1.item(), 'loss2:', loss2.item(), 'error', err.item())
            tt = time.time()

    with torch.no_grad():
        N0 = 1000
        x1 = np.linspace(0, 1, N0 + 1)

        xs1, ys1 = np.meshgrid(x1, x1)
        Z1 = torch.from_numpy(np.concatenate((xs1.flatten()[:, None], ys1.flatten()[:, None]), 1)).float()
        pred = torch.reshape(soln_nn(Z1), [N0 + 1, N0 + 1]).cpu().numpy()
        exact = torch.reshape(exact_sol(Z1), [N0 + 1, N0 + 1]).cpu().numpy()

    err = np.sqrt(np.sum(np.square(exact - pred)) / np.sum(np.square(exact)))
    print("Error:", err)

def main():
    epochs = 2000

    N_interior = 1000
    N_boundary = 200


    lr1 = 1e-2
    lr2 = 1e-2
    gamma1= 0.5
    gamma2 =0.5
    step_size1 = 1000
    step_size2 = 1000
    runmodel(epochs, lr1, lr2, gamma1, gamma2, step_size1, step_size2, N_interior, N_boundary)


if __name__ == '__main__':
    main()
```

### Versions

2023-07-24 10:30:38 (19,0 MB/s) - ‘collect_env.py’ saved [21653/21653]

B@B-MBP ~ % python3 collect_env.py 
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==2.0.0
[pip3] torch==2.0.1
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
I'm closing this as it has been implemented by https://github.com/pytorch/pytorch/pull/97151. Let me know if you have any issues.
