### ISSUE TITLE
PyTorch 2.0.x `CUDA error: operation not supported` when `Tensor.to` a different device

### ISSUE THREAD

**Issue by es94129** [pytorch/pytorch#105872]
### 🐛 Describe the bug

I've created an Azure VM with 2 A10 GPUs (`standard_nv72ads_a10_v5`). When running Hugging Face code to use both the GPUs, I've accounted `CUDA error: operation not supported`, and turns out it is reproducible with this PyTorch snippet.

```python
import torch

a = torch.Tensor(torch.randn(5,5,5))
a = a.to("cuda:0")

# Move a to another device
b = a.to("cuda:1")
```

It shows Segmentation Fault, and with [faulthandler](https://docs.python.org/3/library/faulthandler.html) enabled, it shows the error:
```
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Notably when I downgrade PyTorch from 2.0.1 to 1.13.1, the same snippet works.

As PyTorch 2.0 should be backward compatible, I hope to understand how this could happen, since there are some new features of PyTorch 2.0 that I need.

### Versions

Output of `collect_env.py`
```
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1040-azure-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A10-24Q
GPU 1: NVIDIA A10-24Q

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          72
On-line CPU(s) list:             0-71
Thread(s) per core:              2
Core(s) per socket:              18
Socket(s):                       2
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 74F3 24-Core Processor
Stepping:                        1
CPU MHz:                         3194.042
BogoMIPS:                        6388.08
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       1.1 MiB
L1i cache:                       1.1 MiB
L2 cache:                        18 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-17
NUMA node1 CPU(s):               18-35
NUMA node2 CPU(s):               36-53
NUMA node3 CPU(s):               54-71
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext invpcid_single vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr rdpru arat umip vaes vpclmulqdq rdpid

Versions of relevant libraries:
[pip3] torch==2.0.1
[pip3] triton==2.0.0
[conda] Could not collect
```

Output of NVIDIA's `deviceQuery`:
```
Detected 2 CUDA Capable device(s)

Device 0: "NVIDIA A10-24Q"
  CUDA Driver Version / Runtime Version          12.0 / 9.2
  CUDA Capability Major/Minor version number:    8.6
  Total amount of global memory:                 24298 MBytes (25478168576 bytes)
MapSMtoCores for SM 8.6 is undefined.  Default to use 64 Cores/SM
MapSMtoCores for SM 8.6 is undefined.  Default to use 64 Cores/SM
  (72) Multiprocessors, ( 64) CUDA Cores/MP:     4608 CUDA Cores
  GPU Max Clock rate:                            1695 MHz (1.70 GHz)
  Memory Clock rate:                             6251 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 6291456 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   2 / 0 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "NVIDIA A10-24Q"
  CUDA Driver Version / Runtime Version          12.0 / 9.2
  CUDA Capability Major/Minor version number:    8.6
  Total amount of global memory:                 24298 MBytes (25478168576 bytes)
MapSMtoCores for SM 8.6 is undefined.  Default to use 64 Cores/SM
MapSMtoCores for SM 8.6 is undefined.  Default to use 64 Cores/SM
  (72) Multiprocessors, ( 64) CUDA Cores/MP:     4608 CUDA Cores
  GPU Max Clock rate:                            1695 MHz (1.70 GHz)
  Memory Clock rate:                             6251 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 6291456 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   3 / 0 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from NVIDIA A10-24Q (GPU0) -> NVIDIA A10-24Q (GPU1) : Yes
> Peer access from NVIDIA A10-24Q (GPU1) -> NVIDIA A10-24Q (GPU0) : Yes

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 12.0, CUDA Runtime Version = 9.2, NumDevs = 2
Result = PASS
```

**Comment by janeyx99** [comment]
I could not repro on my A100 Linux--there is no segfault nor error on my end. Maybe this is Windows specific?

**Comment by es94129** [comment]
Hi @janeyx99, thanks for taking a look and tagging the relevant people.

It was on Ubuntu and a specific NVIDIA driver was installed: https://learn.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup#install-grid-drivers-on-nv-or-nvv3-series-vms

**Comment by ptrblck** [comment]
The issue sounds specific to your Azure VM setup. Try to run other multi-GPU applications and check if these would be working.

**Comment by cristianPanaite** [comment]
Considering that this is an issue that occurred on Ubuntu, I think we can remove the `module:windows` label.

**Comment by es94129** [comment]
I also followed [Getting Started with Distributed Data Parallel](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html), and it failed for the same reason with PyTorch 2.0.1 -- when moving tensor to another device -- and worked with PyTorch 1.13.1 as well.

The 3 functions in the tutorial:
- `demo_basic` (passed): no multi-GPU communication
- `demo_checkpoint` (passed): involves `torch.load(CHECKPOINT_PATH, map_location={'cuda:0': 'cuda:1'})` but works
- `demo_model_parallel` (failed): involves `torch.Tensor.to` another device

I have no idea why the `to` function particularly failed, and where the unsupported CUDA operation comes from.

```
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
Running DDP checkpoint example on rank 1.
Running DDP checkpoint example on rank 0.
Running DDP with model parallel example on rank 0.
Traceback (most recent call last):
  File "ddp_example.py", line 156, in <module>
    run_demo(demo_model_parallel, world_size)
  File "ddp_example.py", line 144, in run_demo
    mp.spawn(demo_fn,
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/azureuser/ddp_example.py", line 136, in demo_model_parallel
    outputs = ddp_mp_model(torch.randn(20, 10))
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1113, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/azureuser/ddp_example.py", line 118, in forward
    x = x.to(self.dev1)
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by ptrblck** [comment]
Have you had a chance to run any other multi-GPU (non-PyTorch) application as I doubt the issue is related to PyTorch itself and might be a setup issue?
