### ISSUE TITLE
Flatbuffer torchscipt files don't load in PyTorch Android Lite 1.13.1

### ISSUE THREAD

**Issue by Kautenja** [pytorch/pytorch#105997]
### 🐛 Describe the bug

When attempting to load a flatbuffer traced pytorch file, I get the following exception:

```
Caused by: com.facebook.jni.CppException: Flatbuffer input file but the build hasn't enabled flatbuffer
Exception raised from _load_mobile_from_bytes at /home/agunapal/pytorch/torch/csrc/jit/mobile/import.cpp:638 (most recent call first):
(no backtrace available)
    at org.pytorch.LiteNativePeer.initHybrid(Native Method)
    at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:28)
    at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:30)
    at ai.sensory.face.model.ImageProcessingModel.<init>(ImageProcessingModel.java:49)
    at ai.sensory.face.model.FaceLivenessModel.<init>(FaceLivenessModel.java:42)
    at ai.sensory.face.CaptureActivity.onCreate(CaptureActivity.java:195)
    at android.app.Activity.performCreate(Activity.java:7327)
    at android.app.Activity.performCreate(Activity.java:7318)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
    ... 11 more
```

### Versions

[1.13.1](https://mvnrepository.com/artifact/org.pytorch/pytorch_android_lite/1.13.1)

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
