### ISSUE TITLE
ReplayRecordTests.test_fn_call_args and others fail on my local devserver

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#105944]
### 🐛 Describe the bug

The failures look like this

```
__________________________________________________ ReplayRecordTests.test_fn_call_args ___________________________________________________
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/test/dynamo/test_replay_record.py", line 186, in test_fn_call_args
    self.check_replay(
  File "/data/users/ezyang/c/pytorch/test/dynamo/test_replay_record.py", line 50, in check_replay
    with self.assertLogs(logger="torch._dynamo", level=logging.ERROR) as log_orig:
  File "/home/ezyang/local/c/pytorch-env/lib/python3.10/unittest/_log.py", line 84, in __exit__
    self._raiseFailure(
  File "/home/ezyang/local/c/pytorch-env/lib/python3.10/unittest/case.py", line 163, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: no logs of level ERROR or higher triggered on torch._dynamo

To execute this test, run the following from the base repo dir:
     python test/dynamo/test_replay_record.py -k test_fn_call_args

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

I have checked and confirmed that an exception is being raised, there just is no ERROR log. It's not obvious to me why I would necessarily expect the exception to show up in logs. Oddly, these seem to pass in CI

I'm running on Python 3.10.11. Please reach out if you need help reproducing.

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @wconstab @Xia-Weiwen @ipiszy

**Comment by anijain2305** [comment]
@mlazos Should we remove the replay record tests?

**Comment by mlazos** [comment]
We've removed these
