### ISSUE TITLE
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default

### ISSUE THREAD

**Issue by weberxie** [pytorch/pytorch#106130]
Hi team, I'm trying to grab a computational graph using FakeTensor, but encountered DynamicOutputShapeException exception.

PyTorch Version: 2.0.1+cu118

```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
import traceback
from torch.fx.experimental.symbolic_shapes import ShapeEnv
from torch._dynamo.output_graph import config

a = torch.ones([1, 0])
mode = FakeTensorMode()

a = mode.from_tensor(a)
try:
    with mode:
        b = torch.nonzero(a)
except Exception as e:
    traceback.print_exc() 
```

The stacktrace is:

```
Traceback (most recent call last):
  File "<ipython-input-15-5efd30f1231c>", line 13, in <cell line: 11>
    b = torch.nonzero(a)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 987, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 1162, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 403, in dyn_shape
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default
```

So, anyone can help me to bypass this exception with nonzero operator?

Any response will be appreciated, thanks.

**Comment by samodi-nv** [comment]
Any update on this? I am running into the same error. Is the nonzero operator not supported in fake tensor mode because it introduces a data dependency?
