### ISSUE TITLE
llama model failed for dynamic shape path

### ISSUE THREAD

**Issue by XiaobingSuper** [pytorch/pytorch#106110]
### 🐛 Describe the bug

When running the dynamic shape path for the Llama model, there report an assert error:

```
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/home/xiaobing/pytorch-offical/benchmarks/dynamo/common.py", line 2226, in warmup
    fn(model, example_inputs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/eval_frame.py", line 310, in _fn
    return fn(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/eval_frame.py", line 470, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 559, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 130, in _fn
    return fn(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 378, in _convert_frame_assert
    return _compile(
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 506, in _compile
    check_fn = CheckFunctionManager(
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/guards.py", line 887, in __init__
    guard.create(local_builder, global_builder)
  File "/home/xiaobing/pytorch-offical/torch/_guards.py", line 216, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/guards.py", line 564, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/home/xiaobing/pytorch-offical/torch/fx/experimental/symbolic_shapes.py", line 2809, in produce_guards
    raise ConstraintViolationError(f"Constraints violated!\n{err}")
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated!
  1. Could not validate constraint RelaxedUnspecConstraint(L['inputs'][0].size()[0]) as L['inputs'][0].size()[0] was inferred to be constant (32).  For more information about why it is constant, run with TORCH_LOGS=dynamic

```

### Minified repro

```
python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu --inference -n5 --inductor --timeout 9000 --dynamic-shapes --dynamic-batch-only --only llama

```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitdcacff5
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.12.4
[pip3] ema-pytorch==0.2.2
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] intel-extension-for-pytorch==2.1.0+git785443c
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.1
[pip3] torch==2.1.0a0+git0391d8d
[pip3] torch-fidelity==0.3.0
[pip3] torch-scatter==2.1.1+pt20cpu
[pip3] torch-sparse==0.6.17+pt20cpu
[pip3] torch-struct==0.5
[pip3] torchaudio==2.1.0a0+d5b2996
[pip3] torchdata==0.7.0a0+f2bfd3d
[pip3] torchmetrics==0.11.4
[pip3] torchrec-nightly==2023.3.23
[pip3] torchtext==0.16.0a0+60bea66
[pip3] torchvision==0.16.0a0+d24db8c
[pip3] vector-quantize-pytorch==1.1.2
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.12.4                   pypi_0    pypi
[conda] ema-pytorch               0.2.2                    pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] intel-extension-for-pytorch 2.1.0+git785443c          pypi_0    pypi
[conda] mkl                       2023.0.0         h6d00ec8_25399
[conda] mkl-include               2023.1.0                 pypi_0    pypi
[conda] mkl-static                2023.1.0                 pypi_0    pypi
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.1                    pypi_0    pypi
[conda] torch                     2.1.0a0+git0391d8d           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-scatter             2.1.1+pt20cpu            pypi_0    pypi
[conda] torch-sparse              0.6.17+pt20cpu           pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.1.0a0+d5b2996          pypi_0    pypi
[conda] torchdata                 0.7.0a0+f2bfd3d          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchrec-nightly          2023.3.23                pypi_0    pypi
[conda] torchtext                 0.16.0a0+60bea66          pypi_0    pypi
[conda] torchvision               0.16.0a0+d24db8c          pypi_0    pypi
[conda] vector-quantize-pytorch   1.1.2                    pypi_0    pypi

**Comment by ESI-SYD** [comment]
`hf_T5_generate` accuracy check in Multi-Threads also observed.
 ```python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --accuracy --float32 -dcpu --inference -n5 --inductor --timeout 9000 --dynamic-shapes --dynamic-batch-only --only hf_T5_generate```
`

**Comment by ezyang** [comment]
I can't easily run the command, it fails for me with

```
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/torchbench.py", line 460, in <module>
    torchbench_main()
  File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/torchbench.py", line 456, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/common.py", line 2892, in main
    return maybe_fresh_cache(
  File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/common.py", line 1640, in inner
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/common.py", line 3286, in run
    ) = runner.load_model(
  File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/torchbench.py", line 351, in load_model
    benchmark = benchmark_cls(
  File "/data/users/ezyang/b/torchbenchmark/torchbenchmark/util/model.py", line 25, in __call__
    obj = type.__call__(cls, *args, **kwargs)
TypeError: Model.__init__() got an unexpected keyword argument 'jit'
[2023-07-27 19:35:10,851] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3248389) of binary: numactl
```

can someone run the model with `TORCH_LOGS=dynamic` as the error message suggests and post the logs?

**Comment by XiaobingSuper** [comment]
running ```TORCH_LOGS=dynamic python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu --inference -n5 --inductor --timeout 9000 --dynamic-shapes --dynamic-batch-only --only llama``` and get the following log:
```
[2023-07-27 22:16:11,506] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_env
[2023-07-27 22:16:11,650] torch.fx.experimental.symbolic_shapes: [INFO] 0.0: create_symbol s0 = 32 for L['inputs'][0].size()[0]
[2023-07-27 22:16:11,700] torch.fx.experimental.symbolic_shapes: [INFO] 0.1: create_env
[2023-07-27 22:16:11,701] torch.fx.experimental.symbolic_shapes: [INFO] 0.1: create_symbol s0 = 32 for L['inputs'][0].size()[0]
[2023-07-27 22:16:11,834] torch.fx.experimental.symbolic_shapes: [INFO] 0.2: create_env
[2023-07-27 22:16:11,835] torch.fx.experimental.symbolic_shapes: [INFO] 0.2: create_symbol s0 = 32 for L['inputs'][0].size()[0]
[2023-07-27 22:16:12,052] torch.fx.experimental.symbolic_shapes: [INFO] 0.2: eval Eq(32, s0) [guard added] at benchmark/torchbenchmark/models/llama/model.py:126 in forward (utils/_device.py:76 in __torch_function__)
skipping cudagraphs for unknown reason
[2023-07-27 22:16:20,305] torch.fx.experimental.symbolic_shapes: [INFO] 0.2: produce_guards
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/home/xiaobing/pytorch-offical/benchmarks/dynamo/common.py", line 2226, in warmup
    fn(model, example_inputs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/eval_frame.py", line 310, in _fn
    return fn(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/eval_frame.py", line 470, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 559, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 130, in _fn
    return fn(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 378, in _convert_frame_assert
    return _compile(
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/convert_frame.py", line 506, in _compile
    check_fn = CheckFunctionManager(
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/guards.py", line 887, in __init__
    guard.create(local_builder, global_builder)
  File "/home/xiaobing/pytorch-offical/torch/_guards.py", line 216, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/home/xiaobing/pytorch-offical/torch/_dynamo/guards.py", line 564, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/home/xiaobing/pytorch-offical/torch/fx/experimental/symbolic_shapes.py", line 2809, in produce_guards
    raise ConstraintViolationError(f"Constraints violated!\n{err}")
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated!
  1. Could not validate constraint RelaxedUnspecConstraint(L['inputs'][0].size()[0]) as L['inputs'][0].size()[0] was inferred to be constant (32).  For more information about why it is constant, run with TORCH_LOGS=dynamic


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = Tru
```

**Comment by XiaobingSuper** [comment]
> I can't easily run the command, it fails for me with
> 
> ```
> Traceback (most recent call last):
>   File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/torchbench.py", line 460, in <module>
>     torchbench_main()
>   File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/torchbench.py", line 456, in torchbench_main
>     main(TorchBenchmarkRunner(), original_dir)
>   File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/common.py", line 2892, in main
>     return maybe_fresh_cache(
>   File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/common.py", line 1640, in inner
>     return fn(*args, **kwargs)
>   File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/common.py", line 3286, in run
>     ) = runner.load_model(
>   File "/data/users/ezyang/b/pytorch/benchmarks/dynamo/torchbench.py", line 351, in load_model
>     benchmark = benchmark_cls(
>   File "/data/users/ezyang/b/torchbenchmark/torchbenchmark/util/model.py", line 25, in __call__
>     obj = type.__call__(cls, *args, **kwargs)
> TypeError: Model.__init__() got an unexpected keyword argument 'jit'
> [2023-07-27 19:35:10,851] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3248389) of binary: numactl
> ```
> 
> can someone run the model with `TORCH_LOGS=dynamic` as the error message suggests and post the logs?

It seems torchbenchmark issue, torchbenchmark used by us is ```770d5cf```.

**Comment by ezyang** [comment]
The key line is `[2023-07-27 22:16:12,052] torch.fx.experimental.symbolic_shapes: [INFO] 0.2: eval Eq(32, s0) [guard added] at benchmark/torchbenchmark/models/llama/model.py:126 in forward (utils/_device.py:76 in __torch_function__)`. But even checking out your commit hash I'm in the middle of nowhere for this line:

```
            # the updates and leads to "RuntimeError: Trying to backward through
```

The framework stack kind of messed up and dropped us in a useless frame. Try cranking this up to give a full stack trace by editing the relevant log line in symbolic_shapes.py

**Comment by anijain2305** [comment]
@XiaobingSuper Is it still relevant? If not, can you please close the issue?

**Comment by XiaobingSuper** [comment]
@leslie-fang-intel, please help double-check it.

**Comment by leslie-fang-intel** [comment]
Sure, I will double confirm whether it's still a issue or not

**Comment by leslie-fang-intel** [comment]
I can reproduce this issue with latest PyTorch(1e60174891c21e8de9a813eb2a454ac9819b4a50) and TorchBench(fa41cb26a39c112f72f55b3ccacc2bbc502e2649)

- Reproduce CMD is: `python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu --inference -n5 --inductor --timeout 9000 --dynamic-shapes --dynamic-batch-only --only llama`

- Detail error msg is:

```
  File "/home/jianan/leslie/torch_inductor_lz/pytorch/torch/_dynamo/convert_frame.py", line 575, in compile_inner
    check_fn = CheckFunctionManager(
  File "/home/jianan/leslie/torch_inductor_lz/pytorch/torch/_dynamo/guards.py", line 987, in __init__
    guard.create(builder)
  File "/home/jianan/leslie/torch_inductor_lz/pytorch/torch/_guards.py", line 245, in create
    return self.create_fn(builder, self)
  File "/home/jianan/leslie/torch_inductor_lz/pytorch/torch/_dynamo/guards.py", line 646, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/home/jianan/leslie/torch_inductor_lz/pytorch/torch/fx/experimental/symbolic_shapes.py", line 2769, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['inputs'][0].size()[0])! For more information, run with TORCH_LOGS=dynamic.
  - Not all values of RelaxedUnspecConstraint(L['inputs'][0].size()[0]) are valid because L['inputs'][0].size()[0] was inferred to be a constant (32).


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

**Comment by ezyang** [comment]
If you run with TORCH_LOGS=dynamic it will tell you why the specialization occurred

**Comment by leslie-fang-intel** [comment]
Hi @ezyang, update some progress for this issue, especially for why `[2023-07-27 22:16:12,052] torch.fx.experimental.symbolic_shapes: [INFO] 0.2: eval Eq(32, s0) [guard added] at benchmark/torchbenchmark/models/llama/model.py:126 in forward (utils/_device.py:76 in __torch_function__)`

- This guard is generated by [model script](https://github.com/pytorch/benchmark/blob/49c4a5fbbd62a50a003fd125d70ba68de3470040/torchbenchmark/models/llama/model.py#L132) at `keys = self.cache_k[:bsz, : start_pos + seqlen]` 
  - The hint of [input bs](https://github.com/pytorch/benchmark/blob/49c4a5fbbd62a50a003fd125d70ba68de3470040/torchbenchmark/models/llama/__init__.py#L14) is `32`: `DEFAULT_EVAL_BSIZE = 32`
  - The [max bs](https://github.com/pytorch/benchmark/blob/49c4a5fbbd62a50a003fd125d70ba68de3470040/torchbenchmark/models/llama/model.py#L22) to generate `self.cache_k` is also `32`: `max_batch_size: int = 32 # From the paper they use a batch size of 4M for training`
    - If we change the [max bs](https://github.com/pytorch/benchmark/blob/49c4a5fbbd62a50a003fd125d70ba68de3470040/torchbenchmark/models/llama/model.py#L22) to generate `self.cache_k` from `32` to `33`. The issue **disappears**. Looks like we try to specialize the variable `set_replacement s0 = 32` when equal at priority instead of generate the guard as `Ne(32, s0)`

- Simplify this issue into a small test case which can reproduce this issue: https://gist.github.com/leslie-fang-intel/657e13fbd90941a1972c43ed6d11e25e

**Comment by ezyang** [comment]
This is the thing where slicing into a tensor behaves inconsistently if you slice to the very end, versus slicing before the end. Is a bit of a pain to fix. Current approach would be to make the quantity in question unbacked, but will need some work. A repro would let me take a look directly.

**Comment by leslie-fang-intel** [comment]
> * https://gist.github.com/leslie-fang-intel/657e13fbd90941a1972c43ed6d11e25e

Thanks for the comment @ezyang. Here are the repo: https://gist.github.com/leslie-fang-intel/657e13fbd90941a1972c43ed6d11e25e

**Comment by ezyang** [comment]
So, if you don't mind having a specialized kernel for 32, you can work around this using `maybe_mark_dynamic`, which won't hard error when we do the bs=32 specialization, but will give you a generic kernel for everything else

**Comment by ezyang** [comment]
I fiddled around with the unbacked variant and we seem to be missing juice for it. I'll file some issues.

**Comment by leslie-fang-intel** [comment]
> So, if you don't mind having a specialized kernel for 32, you can work around this using `maybe_mark_dynamic`, which won't hard error when we do the bs=32 specialization, but will give you a generic kernel for everything else

Thanks for the suggestion.

- Since the issue happens when running llama in `torchbench` which hardcode to use [`mark_dynamic`](https://github.com/pytorch/pytorch/blob/a1fc29cd7887e5809255e89300d3744a26416067/benchmarks/dynamo/common.py#L3867) instead of `maybe_mark_dynamic`, do you think if we can change it in `torchbench`?
- Another workaround comes to my mind is maybe we can do some llama specific workaround as changing the [max bs for `cache_k`](https://github.com/pytorch/benchmark/blob/49c4a5fbbd62a50a003fd125d70ba68de3470040/torchbenchmark/models/llama/model.py#L22) from 32 to larger values like 64?

Any preference for the workaround?

**Comment by ezyang** [comment]
I think the latter gives us more insight into the true performance characteristics of the model.

**Comment by leslie-fang-intel** [comment]
PR: https://github.com/pytorch/benchmark/pull/2283 to fix this issue in torchbench.

**Comment by leslie-fang-intel** [comment]
Close as https://github.com/pytorch/benchmark/pull/2283 landed
