### ISSUE TITLE
Make EMFORMER_RNNT torch.compilable

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#106101]
## Repro

```python
import torch
import torchaudio
from torchaudio.io import StreamReader
import executorch.exir as exir

bundle = torchaudio.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH

feature_extractor = bundle.get_streaming_feature_extractor()
decoder = bundle.get_decoder()
token_processor = bundle.get_token_processor()

# random values
# This works
decoder(torch.randn(80, 80), length=torch.tensor([1.0]), beam_width=10)

decoder = torch.compile(decoder)

# This does not work
decoder(torch.randn(80, 80), length=torch.tensor([1.0]), beam_width=10)
```

## Error

```
(nightly) marksaroufim@marksaroufim-mbp zzz % ls
add.ff                          model.ff                        test.py                         test4.py
buck2-aarch64-apple-darwin.zst  tes2.py                         test3.py
(nightly) marksaroufim@marksaroufim-mbp zzz % 
(nightly) marksaroufim@marksaroufim-mbp zzz % python test4.py
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
/Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/executorch/extension/pytree/__init__.py:25: UserWarning: Unable to import executorch.extension.pytree, using native torch pytree instead.
  warnings.warn(
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT forward /Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/torchaudio/models/rnnt_decoder.py line 267 
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] due to: 
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING]   File "/Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/torch/_inductor/fx_passes/split_cat.py", line 125, in normalize_cat_default
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING]     assert all(ndim == x.meta["example_value"].dim() for x in tensors)
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] AssertionError: 
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] 
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] 
[2023-07-26 18:57:18,049] torch._dynamo.convert_frame: [WARNING] converting frame raised error, suppressing error
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT transcribe /Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/torchaudio/models/rnnt.py line 580 
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] due to: 
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING]   File "/Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/torch/_inductor/fx_passes/split_cat.py", line 125, in normalize_cat_default
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING]     assert all(ndim == x.meta["example_value"].dim() for x in tensors)
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] AssertionError: 
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] 
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] 
[2023-07-26 18:57:21,172] torch._dynamo.convert_frame: [WARNING] converting frame raised error, suppressing error
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT forward /Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/torchaudio/models/rnnt.py line 220 
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] due to: 
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING]   File "/Users/marksaroufim/opt/anaconda3/envs/nightly/lib/python3.10/site-packages/torch/_inductor/fx_passes/split_cat.py", line 125, in normalize_cat_default
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING]     assert all(ndim == x.meta["example_value"].dim() for x in tensors)
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] AssertionError: 
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] 
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] 
[2023-07-26 18:57:24,048] torch._dynamo.convert_frame: [WARNING] converting frame raised error, suppressing error
```

### Motivation, pitch

It's a popular model folks have been asking me about and I'd like get it deployed to a mobile device, starting with the decoder

Here's my progress so far
* torch.compile was graph breaking on jit annotate

```
@@ -236,7 +236,7 @@ class RNNTBeamSearch(torch.nn.Module):
         b_hypos = self._init_b_hypos(device) if hypo is None else hypo
         for t in range(n_time_steps):
             a_hypos = b_hypos
-            b_hypos = torch.jit.annotate(List[Hypothesis], [])
+            b_hypos = []
             key_to_b_hypo: Dict[str, Hypothesis] = {}
             symbols_current_t = 0
 
@@ -292,7 +292,7 @@ class RNNTBeamSearch(torch.nn.Module):
         enc_out, _ = self.model.transcribe(input, length)
         return self._search(enc_out, None, beam_width)
 
-    @torch.jit.export
+    # @torch.jit.export
     def infer(
         self,
         input: torch.Tensor,
``

### Alternatives

_No response_

### Additional context

_No response_

**Comment by msaroufim** [comment]
cc @mthrok as well

**Comment by msaroufim** [comment]
OK I think it should be possible to progress here by setting the split cat config to False https://github.com/pytorch/pytorch/blob/main/torch/_inductor/config.py#L49

**Comment by mthrok** [comment]
cc @hwangjeff

**Comment by ezyang** [comment]
@msaroufim if it's a dynamic shapes problem I'd like to take a closer look, but I need cleaner repro instructions. Any chance you've got them?

**Comment by msaroufim** [comment]
@ezyang you produced a nice repro already for the remaining problem lol https://github.com/pytorch/pytorch/issues/107188#issuecomment-1680550137

I'm less worried about the specific changes I needed to make right now to go through some errors

**Comment by anijain2305** [comment]
cc @yanboliang

**Comment by msaroufim** [comment]
cc @gmagogsfm

**Comment by ezyang** [comment]
This is now on 

```
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/lists.py", line 121, in call_method
    unimplemented("__getitem__ with non-constant tensor")
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: __getitem__ with non-constant tensor

from user code:
   File "/data/users/ezyang/a/torchaudio/src/torchaudio/models/rnnt_decoder.py", line 293, in forward
    return self._search(enc_out, None, beam_width)
  File "/data/users/ezyang/a/torchaudio/src/torchaudio/models/rnnt_decoder.py", line 246, in _search
    b_hypos = self._gen_b_hypos(b_hypos, a_hypos, next_token_probs, key_to_b_hypo)
  File "/data/users/ezyang/a/torchaudio/src/torchaudio/models/rnnt_decoder.py", line 165, in _gen_b_hypos
    return [b_hypos[idx] for idx in sorted_idx]
  File "/data/users/ezyang/a/torchaudio/src/torchaudio/models/rnnt_decoder.py", line 165, in <listcomp>
    return [b_hypos[idx] for idx in sorted_idx]
```

which cannot be supported without model rewrite.

Need

```
torch._dynamo.config.capture_scalar_outputs = True
torch._dynamo.config.capture_dynamic_output_shape_ops = True
```
