### ISSUE TITLE
DISABLED test_get_classifications_pending_unstable (__main__.TestBypassFailures)

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/pytorch#106204]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](https://github.com/pytorch/pytorch/actions/runs/5690543018/job/15424383198).

```
======================================================================
ERROR: test_get_classifications_pending_unstable (test_trymerge.TestBypassFailures)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.9/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/work/.github/scripts/test_trymerge.py", line 719, in test_get_classifications_pending_unstable
    pending, failed = categorize_checks(
ValueError: too many values to unpack (expected 2)

----------------------------------------------------------------------
```

**Comment by DanilBaibak** [comment]
Forward fix - #106203.

**Comment by malfet** [comment]
Please note, that disabling linter tests by issue does not work (and I guess it shouldn't)
