### ISSUE TITLE
[JIT][script] dtype argument on tensor constructors doesn't work

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#10632]
If I try to do this:

```
import torch

@torch.jit.script
def create_zeros():
    return torch.zeros(1, 2, 3, dtype=torch.long)
```

It fails like this:

```
﻿﻿Traceback (most recent call last):
  File "dtype.py", line 3, in <module>
    @torch.jit.script
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/jit/__init__.py", line 351, in script
    graph = _jit_script_compile(ast, rcb)
RuntimeError: 
arguments for call are not valid:
  
  for operator aten::zeros(int[] size, *, int dtype=<default>, int layout=<default>, int[] device=<default>) -> Tensor:
  argument dtype specified twice 
  @torch.jit.script
  def create_zeros():
      return torch.zeros(1, 2, 3, dtype=torch.long)
                                        ~~~~~~~~~~ <--- HERE
for call at:
@torch.jit.script
def create_zeros():
    return torch.zeros(1, 2, 3, dtype=torch.long)
           ~~~~~~~~~~~ <--- HERE


```

**Comment by jamesr66a** [comment]
Note this works:

```
import torch

@torch.jit.script
def create_zeros():
    return torch.zeros([1, 2, 3], dtype=torch.long)
```

Though requiring to wrap that stuff in an array is pretty cumbersome. We should probably make this behave more like with the python arg parser
