### ISSUE TITLE
torch._export.dynamic_dim raises when called within FakeTensorMode

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#106412]
### 🐛 Describe the bug

After #100017 `torch._dynamo.export` can be called within `FakeTensorMode` with inputs already fakefied by the user
When we try to use the `dynamic_dim` in such scenario, `torch._dynamo.exc.InternalTorchDynamoError: not enough values to unpack (expected at least 1, got 0)` is raised when `torch/_dynamo/guards.py::get_sources(constraint.t_id, constraint.dim)` is called.

```python
import torch
from torch._subclasses import fake_tensor
from torch.fx.experimental.symbolic_shapes import ShapeEnv
from torch._export import dynamic_dim

fake_mode = fake_tensor.FakeTensorMode(
    shape_env=ShapeEnv(  # all default values
        allow_scalar_outputs=True,
        allow_dynamic_output_shape_ops=True,
        assume_static_by_default=False,
    ),
)

class DynamicShapeSimpleModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a, b, c) -> torch.Tensor:
        d = (torch.matmul(a, b) + c) / 2
        d_s0 = d.shape[0]
        d_s1 = d.shape[1]
        d_s3 = d_s0 * d_s1
        e = d.view(d_s3)
        return torch.cat([e, e])


with fake_mode:
    model = DynamicShapeSimpleModel()
    inputs = (torch.randn(2, 4), torch.randn(4, 7), torch.randn(2, 7))
    constraints = [
        dynamic_dim(inputs[0], 0),
        dynamic_dim(inputs[2], 0),
        dynamic_dim(inputs[2], 0) == dynamic_dim(inputs[0], 0),
    ]
    torch._dynamo.export(
        model,
        constraints=constraints,
        aten_graph=True,
    )(*inputs)
```

raises

```bash
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT forward repro_dynamic_dim.py line 21 
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING] due to: 
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING]   File "/opt/pytorch/torch/_dynamo/guards.py", line 542, in SHAPE_ENV
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING]     source, *other_sources = get_sources(constraint.t_id, constraint.dim)
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING] ValueError: not enough values to unpack (expected at least 1, got 0)
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING] 
[2023-08-01 21:28:56,760] torch._dynamo.convert_frame: [WARNING] 
Traceback (most recent call last):
  File "repro_dynamic_dim.py", line 38, in <module>
    gm, _ = torch._dynamo.export(
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 1022, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 481, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 130, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 378, in _convert_frame_assert
    return _compile(
  File "/opt/pytorch/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 547, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(e.__traceback__) from None
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 506, in _compile
    check_fn = CheckFunctionManager(
  File "/opt/pytorch/torch/_dynamo/guards.py", line 887, in __init__
    guard.create(local_builder, global_builder)
  File "/opt/pytorch/torch/_guards.py", line 216, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/opt/pytorch/torch/_dynamo/guards.py", line 542, in SHAPE_ENV
    source, *other_sources = get_sources(constraint.t_id, constraint.dim)
torch._dynamo.exc.InternalTorchDynamoError: not enough values to unpack (expected at least 1, got 0)
```

### Versions

latest pytorch main branch

**Comment by ezyang** [comment]
The problem is that you're triggering the logic we added previously to make export use the ambient fake tensor mode. What needs to actually happen is we need to make an internal fresh mode. At the very least this line needs to go https://github.com/pytorch/pytorch/pull/106345/files#diff-c663df72d7a648204ff256e604fe3c9b393e7e2d58204e3bc818d90a99712911R921 but it seems there's more that needs to go too.

**Comment by ezyang** [comment]
I found some other spots. patch coming
