### ISSUE TITLE
[JIT] dict comprehension causes `RuntimeError: Cannot create dict for key type 'Scalar', only int, float, complex, Tensor, device and string keys are supported`

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#106435]
### 🐛 Describe the bug

**Tasks**:
* [ ] (maybe) fix this - seems hard because torchscript doesn't know whether a tensor is a FloatTensor or an IntTensor
* [ ] Improve source attribution: maybe this error should be a FrontendError(? is that what it's called?) that traces back to the source that had this issue.

Repro:

```python
import torch
from typing import List, Tuple, Dict

def fn(x: List[torch.Tensor]):
    return {x[i].item(): i for i in range(len(x))}

torch.jit.script(fn)
```

Error:
```
Traceback (most recent call last):
  File "/data/users/dberard/scripts/dict_comprehension.py", line 7, in <module>
    torch.jit.script(fn)
  File "/data/users/dberard/pytorch/torch/jit/_script.py", line 1377, in script
    fn = torch._C._jit_script_compile(
RuntimeError: Cannot create dict for key type 'Scalar', only int, float, complex, Tensor, device and string keys are supported
```

### Versions

main branch as of aug 1, 2023

**Comment by davidberard98** [comment]
Workaround: you can wrap the `x[i].item()` with a `float()` or `int()` so torchscript knows what type it is

```python
import torch
from typing import List, Tuple, Dict

def fn(x: List[torch.Tensor]):
    return {float(x[i].item()): i for i in range(len(x))}

torch.jit.script(fn)
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
