### ISSUE TITLE
PyTorchMPS not showing up in Instruments for `torch.mps.profiler`

### ISSUE THREAD

**Issue by ZachNagengast** [pytorch/pytorch#106408]
### 🐛 Describe the bug

Following these instructions: https://developer.apple.com/videos/play/wwdc2023/10050/?time=355, I'm not seeing the `PyTorchMPS` intervals showing up when trying to profile SDXL. I can see `events` in the `com.apple.Metal.AGXSignposts` but  I would expect to see PyTorchMPS here, with intervals breaking down each layer's latency.

<img width="618" alt="image" src="https://github.com/pytorch/pytorch/assets/1981179/6de491b4-5cbb-46eb-b614-96a7419cc85f">

Here's the code I'm using to profile:

```
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0")
pipe.to("mps")

prompt = "test prompt"
negative_prompt = "test negative prompt"

torch.mps.profiler.start(mode='interval', wait_until_completed=True)
print(os.getpid())
image = pipe(prompt, negative_prompt=negative_prompt, num_inference_steps=1).images[0]
torch.mps.profiler.stop()

```

This may be related to macOS 14 beta? I'm calling this from a notebook being run via VSCode, but I tested just running it from a standalone python file via iTerm2 and similar issue.

### Versions

PyTorch version: 2.1.0.dev20230801
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-lightning==1.7.7
[pip3] torch==2.1.0.dev20230801
[pip3] torchaudio==2.1.0.dev20230801
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.4
[pip3] torchsde==0.2.5
[pip3] torchvision==0.16.0.dev20230801
[conda] numpy                     1.24.3          py311hd0e4f0d_0
[conda] numpy-base                1.24.3          py311h947b413_0
[conda] numpydoc                  1.5.0           py311hecd8cb5_0

**Comment by kulinseth** [comment]
Cc @razarmehr

**Comment by kulinseth** [comment]
Thanks @ZachNagengast for filing the issue . The signpost support should exist on macOS 13 as well . I will let @razarmehr comment on it . While capturing the signpost did you follow the capture sequence from inside Instruments or only from the profiler ?

**Comment by ZachNagengast** [comment]
@kulinseth I'm not sure exactly the capture sequence you're referring to, but the steps I took to capture were this:

1. Start profiler in python and print process id
2. Find the process id in Instruments and begin capturing
3. Run inference fully, and stop the profiler
4. Stop capturing in Instruments and observe the trace

**Comment by razarmehr** [comment]
Thanks @ZachNagengast. I could reproduce this issue on MacOS 14. I'll investigate further to find a fix.

**Comment by ZachNagengast** [comment]
@razarmehr Amazing, thank you. Available to test as needed.

**Comment by DenisVieriu97** [comment]
@ZachNagengast could you please make sure Instruments is tracing the inference loop?
E.g can you capture the pid, add a small delay while opening Metal System Trace from Instruments and start tracing then?
```
import time
from diffusers import DiffusionPipeline
import torch
import os

print(os.getpid())
time.sleep(5)

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0")
pipe.to("mps")

prompt = "test prompt"
negative_prompt = "test negative prompt"

torch.mps.profiler.start(mode='interval', wait_until_completed=True)
image = pipe(prompt, negative_prompt=negative_prompt, num_inference_steps=1).images[0]
torch.mps.profiler.stop()
```

**Comment by ZachNagengast** [comment]
@DenisVieriu97 Just tested with your script, still no luck - only `com.apple.Metal.AGXSignposts` shows up under the `os_signpost` section

Side note: the nightly for today `2.1.0.dev20230804` threw this error, had to roll back to `2.1.0.dev20230801` to run that code.

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/zachnagengast/Downloads/modelviz-profile.py", line 1354, in <module>
    image = pipe(prompt, negative_prompt=negative_prompt, num_inference_steps=1).images[0]
  File "/opt/homebrew/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 810, in __call__
    latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)
  File "/opt/homebrew/lib/python3.10/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 203, in scale_model_input
    step_index = (self.timesteps == timestep).nonzero().item()
RuntimeError: Expected dst.dim() >= src.dim() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

**Comment by ZachNagengast** [comment]
@DenisVieriu97 @razarmehr @kulinseth Checking in on this, were you able to find out anything?

**Comment by igm503** [comment]
I had this issue in mac os 14.2.1, but the issue has gone away in 14.3.1

However, although there's now os_signpost data for PyTorchMPS, all of the intervals are just called "<private>", and so I can't see which ops each one represents. Anyone know what might be causing this?
