### ISSUE TITLE
remove_from_cache doesn't work on nn.Module

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#106547]
### 🐛 Describe the bug

Repro:

```
import torch
from torch.nn import Linear

m = Linear(2, 2)
torch._dynamo.export(m)(torch.randn(2, 2))
torch._dynamo.export(m)(torch.randn(2, 2))
```

Expected result: it works

Actual result:

```
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/a.py", line 6, in <module>
    torch._dynamo.export(m)(torch.randn(2, 2))
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/eval_frame.py", line 1059, in inner
    graph is not None
AssertionError: Failed to produce a graph during tracing. Tracing through 'f' must produce a single graph.
```

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym 

### Versions

main

**Comment by ezyang** [comment]
cc @anijain2305

**Comment by ezyang** [comment]
cc @tugsbayasgalan

**Comment by voznesenskym** [comment]
@ydwu4 @zou3519 - this is related to our caching discussion w/r/t export and cond

**Comment by anijain2305** [comment]
This does not repro. Is this still a problem?
