### ISSUE TITLE
Failed when converting MobileNetV2 to NNAPI following the tutorial

### ISSUE THREAD

**Issue by greyovo** [pytorch/pytorch#106522]
### 🐛 Describe the bug

I followed [this official tutorial](https://pytorch.org/tutorials/prototype/nnapi_mobilenetv2.html) on converting MobileNetV2 to NNAPI. But in quantizing steps, I copied the code and ran and stopped at error:

```
Traceback (most recent call last):
  File "D:/Develop/Playground/pytorch-nnapi-test/main.py", line 106, in <module>
    make_mobilenetv2_nnapi(Path(os.path.curdir) / "mobilenetv2-nnapi", quantize_mode)
  File "D:/Develop/Playground/pytorch-nnapi-test/main.py", line 34, in make_mobilenetv2_nnapi
    model = torchvision.models.quantization.mobilenet.mobilenet_v2(pretrained=True, quantize=quantize_core)
  File "D:\Develop\Playground\pytorch-nnapi-test\venv\lib\site-packages\torchvision\models\quantization\mobilenetv2.py", line 91, in mobilenet_v2
    quantize_model(model, backend)
  File "D:\Develop\Playground\pytorch-nnapi-test\venv\lib\site-packages\torchvision\models\quantization\utils.py", line 22, in quantize_model
    raise RuntimeError("Quantized backend not supported ")
RuntimeError: Quantized backend not supported 
```

It seems that `qnnpack` is not supported on my computer? When I run 
```python
print(torch.backends.quantized.supported_engines)  # outputs: ['none', 'fbgemm']
```

How can I fix it? Do I miss something?

The full code:

```python
#!/usr/bin/env python
import sys
import os
import torch
import torch.utils.bundled_inputs
import torch.utils.mobile_optimizer
import torch.backends._nnapi.prepare
import torchvision.models.quantization.mobilenet
from pathlib import Path

def make_mobilenetv2_nnapi(output_dir_path, quantize_mode):
    quantize_core, quantize_iface = {
        "none": (False, False),
        "core": (True, False),
        "full": (True, True),
    }[quantize_mode]

    model = torchvision.models.quantization.mobilenet.mobilenet_v2(pretrained=True, quantize=quantize_core)
    model.eval()

    if not quantize_core:
        model.fuse_model()
    assert type(model.classifier[0]) == torch.nn.Dropout
    model.classifier[0] = torch.nn.Identity()

    input_float = torch.zeros(1, 3, 224, 224)
    input_tensor = input_float

    if quantize_core:
        quantizer = model.quant
        dequantizer = model.dequant
        model.quant = torch.nn.Identity()
        model.dequant = torch.nn.Identity()
        input_tensor = quantizer(input_float)

    input_tensor = input_tensor.contiguous(memory_format=torch.channels_last)
    input_tensor.nnapi_nhwc = True

    with torch.no_grad():
        traced = torch.jit.trace(model, input_tensor)
    nnapi_model = torch.backends._nnapi.prepare.convert_model_to_nnapi(traced, input_tensor)

    if quantize_core and not quantize_iface:
        nnapi_model = torch.nn.Sequential(quantizer, nnapi_model, dequantizer)
        model.quant = quantizer
        model.dequant = dequantizer
        # Switch back to float input for benchmarking.
        input_tensor = input_float.contiguous(memory_format=torch.channels_last)

    model = torch.utils.mobile_optimizer.optimize_for_mobile(torch.jit.script(model))

    class BundleWrapper(torch.nn.Module):
        def __init__(self, mod):
            super().__init__()
            self.mod = mod

        def forward(self, arg):
            return self.mod(arg)

    nnapi_model = torch.jit.script(BundleWrapper(nnapi_model))
    torch.utils.bundled_inputs.augment_model_with_bundled_inputs(
        model, [(torch.utils.bundled_inputs.bundle_large_tensor(input_tensor),)])
    torch.utils.bundled_inputs.augment_model_with_bundled_inputs(
        nnapi_model, [(torch.utils.bundled_inputs.bundle_large_tensor(input_tensor),)])

    # Save both models.
    model._save_for_lite_interpreter(str(output_dir_path / ("mobilenetv2-quant_{}-cpu.pt".format(quantize_mode))))
    nnapi_model._save_for_lite_interpreter(
        str(output_dir_path / ("mobilenetv2-quant_{}-nnapi.pt".format(quantize_mode))))


if __name__ == "__main__":
    for quantize_mode in ["none", "core", "full"]:
        make_mobilenetv2_nnapi(Path(os.path.curdir) / "mobilenetv2-nnapi", quantize_mode)
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home China
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: 12.1.66

CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 531.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9

CurrentClockSpeed=3201

DeviceID=CPU0

Family=107

L2CacheSize=4096

L2CacheSpeed=

Manufacturer=AuthenticAMD

MaxClockSpeed=3201

Name=AMD Ryzen 7 6800H with Radeon Graphics         

ProcessorType=3

Revision=17409

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.10.0
[pip3] torchvision==0.11.1
[conda] Could not collect

**Comment by greyovo** [comment]
I successfully ran it on Linux (Ubuntu 20.06 WSL). Is qnnpack not supported on Windows? Then we should demonstrate it clearly in the toturial....

**Comment by mcr229** [comment]
yea unfortunately qnnpack is not supported on windows, we will update the docs to reflect this.

you can also try setting the qengine to another engine like so:

`torch.backends.quantized.engine = `
