### ISSUE TITLE
Confusing error message for DataLoader with num_workers=0 and non-zero timeout

### ISSUE THREAD

**Issue by adscib** [pytorch/pytorch#106634]
### 🐛 Describe the bug

It looks like setting a timeout on the DataLoader is illegal with num_workers=0, but the documentation doesn't mention it and the error message is very confusing. I would expect the timeout to be ignored under those circumstances, but at the very least this deserves a clear error message, since the current one reads as if a timeout occurred, rather than an illegal value for it was passed.

Minimal reproducing example
```python
from torch.utils.data import DataLoader
train_dataloader_full_tracks = DataLoader(
    [], num_workers=0, timeout=1
)
iter(train_dataloader_full_tracks)
```

Output
```
Traceback (most recent call last):
  File "dataloader_problem.py", line 6, in <module>
    iter(train_dataloader_full_tracks)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 385, in _get_iterator
    return _SingleProcessDataLoaderIter(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 664, in __init__
    assert self._timeout == 0
AssertionError
```

### Versions

I use 2.0.0, but I see that the main branch has the same issue as of today.

**Comment by mk12002** [comment]
I am getting the same issue. are u able to solve this?

**Comment by dqj5182** [comment]
change num_workers to value other than 0.
