### ISSUE TITLE
torch.jit.script: undefined value torch with imported decorator

### ISSUE THREAD

**Issue by andreasfloros** [pytorch/pytorch#106699]
### 🐛 Describe the bug

Say we have a decorator that does some kind of preprocessing (maybe some checks on the arguments, maybe some kind of normalization etc). A general form for this decorator would look something like this:

```python
# decorator_file.py

import functools
import typing


TCallable = typing.TypeVar("TCallable", bound=typing.Callable)


def decorator(obj: TCallable) -> TCallable:
    @functools.wraps(obj)
    def wrapper(*args, **kwargs):
        # Do something here
        return obj(*args, **kwargs)
    return typing.cast(TCallable, wrapper)

```
Now we want to decorate our function and later we decide to script it:

```python
# script_file.py

import torch
from decorator_file import decorator


@decorator
def func(inpt: torch.Tensor) -> torch.Tensor:
    return torch.sigmoid(inpt)


script_func = torch.jit.script(func)  # RuntimeError: undefined value torch

```
Running `python script_file.py` gives:

```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\test-env\script_file.py", line 10, in <module>
    script_func = torch.jit.script(func)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\test-env\env\Lib\site-packages\torch\jit\_script.py", line 1341, in script
    fn = torch._C._jit_script_compile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError:
undefined value torch:
  File "C:\Users\user\Desktop\test-env\decorator_file.py", line 7
@decorator
def func(inpt: torch.Tensor) -> torch.Tensor:
    return torch.sigmoid(inpt)
           ~~~~~ <--- HERE

```

Work arounds:

1. If the decorator is defined in the same file everything works as expected.
2. `import torch` in `decorator_file.py` or using the `torch.Tensor` methods like `inpt.sigmoid()` both work.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2592
DeviceID=CPU0
Family=198
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2592
Name=Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] torch==2.0.1
[conda] Could not collect

```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
