### ISSUE TITLE
'CUDA out of memory' when using a GPU services for reinforcement learning in Torch rpc tutorial

### ISSUE THREAD

**Issue by lpf6** [pytorch/pytorch#106711]
### 🐛 Describe the bug

I followed this [tutorial](https://pytorch.org/tutorials/intermediate/rpc_tutorial.html) to implement reinforcement learning with RPC on Torch. And I can run  the original tutorial well.

After adding the specified **GPU** device for the model as shown in the original tutorial, I encountered a "cuda out of memory" issue. 

Currently, I use one trainer process and one observer process. 

The trainer process creating the model, and the observer process calls the model forward using **RPC**. 

To simplify reproduction, I removed some of the original code from the tutorial.
https://gist.github.com/lpf6/9cd5bf55489758defc6b9fdbc2dcee62

The modifications compared to the tutorial are `select_action` and `Agent.__init__` function add `to(self.device_id)`. For example, the `select_action` function:
``` python
    def select_action(self, ob_id, state):
        state: torch.Tensor = torch.from_numpy(state).float().unsqueeze(0).to(self.device_id)
        probs = self.policy(state)
        m = Categorical(probs)
        action = m.sample()
        self.saved_log_probs[ob_id].append(m.log_prob(action))
        result = action.item()

        del action, m, state, probs
        return result
```

And I got result
```
/home/lu/PycharmProjects/tetris/venv/bin/python /home/lu/PycharmProjects/tetris/test_error.py 
obs_0_for_0 started
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230807 23:22:56.714407 262881 ProcessGroupNCCL.cpp:665] [Rank 0] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_DESYNC_DEBUG: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
I20230807 23:22:56.714471 262980 ProcessGroupNCCL.cpp:842] [Rank 0] NCCL watchdog thread started!
agent_0 started
/home/lu/PycharmProjects/tetris/venv/lib/python3.11/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
episode : 1, mem_used: 146.25Mb
episode : 2, mem_used: 251.88Mb
episode : 3, mem_used: 438.75Mb
episode : 4, mem_used: 682.50Mb
.....

episode : 44, mem_used: 4834.38Mb

At:
  /usr/lib/python3.11/site-packages/torch/distributed/rpc/internal.py(234): _handle_exception
')
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/internal.py", line 207, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/rref_proxy.py", line 42, in _invoke_rpc
    return _rref_type_cont(rref_fut)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/rref_proxy.py", line 31, in _rref_type_cont
    return rpc_api(
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/api.py", line 82, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/api.py", line 809, in rpc_sync
    return fut.wait()
           ^^^^^^^^^^
RuntimeError: RuntimeError: On WorkerInfo(id=1, name=obs_0_for_0):
RuntimeError('OutOfMemoryError: On WorkerInfo(id=0, name=agent_0):
OutOfMemoryError('CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.75 GiB total capacity; 4.73 GiB already allocated; 10.88 MiB free; 5.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/internal.py", line 207, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/distributed/rpc/rref_proxy.py", line 11, in _local_invoke
    return getattr(rref.local_value(), func_name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lu/PycharmProjects/tetris/test_error.py", line 71, in select_action
    probs = self.policy(state)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lu/PycharmProjects/tetris/test_error.py", line 25, in forward
    x = self.affine1(x)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.75 GiB total capacity; 4.73 GiB already allocated; 10.88 MiB free; 5.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF



Process finished with exit code 1
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 13.1.1 20230714
Clang version: 15.0.7
CMake version: Could not collect
Libc version: glibc-2.37

Python version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] (64-bit runtime)
Python platform: Linux-6.4.6-1-MANJARO-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 535.86.05
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.9.2
/usr/lib/libcudnn_adv_infer.so.8.9.2
/usr/lib/libcudnn_adv_train.so.8.9.2
/usr/lib/libcudnn_cnn_infer.so.8.9.2
/usr/lib/libcudnn_cnn_train.so.8.9.2
/usr/lib/libcudnn_ops_infer.so.8.9.2
/usr/lib/libcudnn_ops_train.so.8.9.2
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
字节序：                         Little Endian
CPU:                             48
在线 CPU 列表：                  0-47
厂商 ID：                        GenuineIntel
型号名称：                       Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
CPU 系列：                       6
型号：                           63
每个核的线程数：                 2
每个座的核数：                   12
座：                             2
步进：                           2
CPU(s) scaling MHz:              47%
CPU 最大 MHz：                   3300.0000
CPU 最小 MHz：                   1200.0000
BogoMIPS：                       5001.30
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perf pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts vnmi md_clear flush_l1d
虚拟化：                         VT-x
L1d 缓存：                       768 KiB (24 instances)
L1i 缓存：                       768 KiB (24 instances)
L2 缓存：                        6 MiB (24 instances)
L3 缓存：                        60 MiB (2 instances)
NUMA 节点：                      2
NUMA 节点0 CPU：                 0-11,24-35
NUMA 节点1 CPU：                 12-23,36-47
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] torch==2.0.1
[pip3] torchsummary==1.5.1
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0           py310h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0    defaults
[conda] mkl_random                1.2.2           py310h00e6091_0    defaults
[conda] numpy                     1.23.5          py310hd5efca6_0    defaults
[conda] numpy-base                1.23.5          py310h8e6c178_0    defaults
[conda] numpydoc                  1.5.0           py310h06a4308_0    defaults
[conda] pytorch                   1.12.1          cpu_py310hb1f1ab4_1    defaults

**Comment by drisspg** [comment]
Have you tried narrowing down the cause of the OOM with: https://zdevito.github.io/2022/08/16/memory-snapshots.html

**Comment by lpf6** [comment]
And I simple the demo: remove array append and simple model to one linear layer.

```
import gc
import os.path
from itertools import count

import gym
import numpy as np
import torch
import torch.distributed.rpc as rpc
import torch.multiprocessing as mp
import torch.nn as nn
import torch.nn.functional as F
from torch.distributed.rpc import RRef, rpc_async, remote
from torch.distributions import Categorical
from torch.nn.parallel import DistributedDataParallel as DDP
import torch.distributed as dist

AGENT_NAME = "agent_{}"
OBSERVER_NAME = "obs_{}_for_{}"
torch.cuda.memory._record_memory_history(True)

def release_memory(rank):
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    from pickle import dump
    snapshot = torch.cuda.memory._snapshot()
    if os.path.exists("snapshot.pickle"):
        if os.path.exists("snapshot.pickle.0"):
            os.remove("snapshot.pickle.0")
        os.rename("snapshot.pickle", "snapshot.pickle.0")
    dump(snapshot, open('snapshot.pickle', 'wb'))


class Policy(nn.Module):
    def __init__(self):
        super(Policy, self).__init__()
        self.affine1 = nn.Linear(4, 2)
        # self.dropout = nn.Dropout(p=0.6)
        # self.affine2 = nn.Linear(128, 2)

    def forward(self, x):
        x1 = self.affine1(x)
        # x2 = self.dropout(x1)
        # x3 = F.relu(x2)
        # action_scores = self.affine2(x3)
        # result = F.softmax(action_scores, dim=1)
        # del action_scores, x1, x2, x3
        # return result
        result = F.softmax(x1, dim=1)
        del x1
        return result


class Observer:

    def __init__(self):
        self.id = rpc.get_worker_info().id

    def run_episode(self, agent_rref):
        state = np.random.random((4,))
        agent_rref.rpc_sync().select_action(self.id, state)


class Agent:
    def __init__(self, rank, observer_size_pre_trainer, infos):
        ob_info = rpc.get_worker_info(OBSERVER_NAME.format(0, rank))
        self.ob_rref = remote(ob_info, Observer)
        self.agent_rref = RRef(self)
        self.device_id = rank % torch.cuda.device_count()
        self.policy = Policy().to(self.device_id)
        self.rank = rank

    def select_action(self, ob_id, state):
        release_memory(self.rank)
        s: torch.Tensor = torch.from_numpy(state).float().unsqueeze(0).to(self.device_id)
        with torch.no_grad():
            probs = self.policy(s)
        # m = Categorical(probs)
        # action = m.sample()
        # log_prob = m.log_prob(action)
        # self.saved_log_probs[ob_id].append(log_prob.item())
        # result = action.item()
        #
        # del action, m, state, probs, log_prob
        del probs
        release_memory(self.device_id)
        return 1

    def run_episode(self):
        rpc_async(
            self.ob_rref.owner(),
            self.ob_rref.rpc_sync().run_episode,
            args=(self.agent_rref,)
        ).wait()


def run_worker(rank, world_size):
    rpc_backend_options = rpc.TensorPipeRpcBackendOptions(
        init_method='tcp://localhost:29500',
        num_worker_threads=1024,
    )
    if rank == 0:
        name = AGENT_NAME.format(rank)
        print(f"{name} started")
        rpc.init_rpc(name, rank=rank, world_size=world_size,
                     rpc_backend_options=rpc_backend_options)

        agent = Agent(rank, 1, {})

        for i_episode in range(100):
            agent.run_episode()
            print(f"episode : {i_episode}, mem_used: {torch.cuda.memory_allocated(agent.device_id) / 1024 / 1024:.2f}Mb")

    else:
        observer = OBSERVER_NAME.format(0, 0)
        print(f"{observer} started")
        rpc.init_rpc(observer, rank=rank, world_size=world_size,
                     rpc_backend_options=rpc_backend_options)

    rpc.shutdown()


def main():
    mp.spawn(run_worker, args=(2,), nprocs=2, join=True)


if __name__ == "__main__":
    torch.multiprocessing.set_start_method('spawn')
    main()


```

However, the issue still persists.
```
obs_0_for_0 started
agent_0 started
episode : 0, mem_used: 8.13Mb
episode : 1, mem_used: 16.25Mb
episode : 2, mem_used: 24.38Mb
episode : 3, mem_used: 32.50Mb
episode : 4, mem_used: 40.63Mb
episode : 5, mem_used: 48.75Mb
episode : 6, mem_used: 56.88Mb
episode : 7, mem_used: 65.00Mb
episode : 8, mem_used: 73.13Mb
episode : 9, mem_used: 81.25Mb
episode : 10, mem_used: 89.38Mb
episode : 11, mem_used: 97.50Mb
episode : 12, mem_used: 105.63Mb
episode : 13, mem_used: 113.75Mb
episode : 14, mem_used: 121.88Mb
episode : 15, mem_used: 130.00Mb
episode : 16, mem_used: 138.13Mb
episode : 17, mem_used: 146.25Mb
episode : 18, mem_used: 154.38Mb
episode : 19, mem_used: 162.50Mb
episode : 20, mem_used: 170.63Mb
episode : 21, mem_used: 178.75Mb
episode : 22, mem_used: 186.88Mb
episode : 23, mem_used: 195.00Mb
episode : 24, mem_used: 203.13Mb
episode : 25, mem_used: 211.25Mb
episode : 26, mem_used: 219.38Mb
episode : 27, mem_used: 227.50Mb
episode : 28, mem_used: 235.63Mb
episode : 29, mem_used: 243.75Mb
episode : 30, mem_used: 251.88Mb
episode : 31, mem_used: 260.00Mb
episode : 32, mem_used: 268.13Mb
episode : 33, mem_used: 276.25Mb
episode : 34, mem_used: 284.38Mb
episode : 35, mem_used: 292.50Mb
episode : 36, mem_used: 300.63Mb
episode : 37, mem_used: 308.75Mb
episode : 38, mem_used: 316.88Mb
episode : 39, mem_used: 325.00Mb
episode : 40, mem_used: 333.13Mb
episode : 41, mem_used: 341.25Mb
episode : 42, mem_used: 349.38Mb
episode : 43, mem_used: 357.50Mb
episode : 44, mem_used: 365.63Mb
episode : 45, mem_used: 373.75Mb
episode : 46, mem_used: 381.88Mb
episode : 47, mem_used: 390.00Mb
episode : 48, mem_used: 398.13Mb
episode : 49, mem_used: 406.25Mb
episode : 50, mem_used: 414.38Mb
episode : 51, mem_used: 422.50Mb
episode : 52, mem_used: 430.63Mb
episode : 53, mem_used: 438.75Mb
episode : 54, mem_used: 446.88Mb
episode : 55, mem_used: 455.00Mb
episode : 56, mem_used: 463.13Mb
episode : 57, mem_used: 471.25Mb
episode : 58, mem_used: 479.38Mb
episode : 59, mem_used: 487.50Mb
episode : 60, mem_used: 495.63Mb
episode : 61, mem_used: 503.75Mb
episode : 62, mem_used: 511.88Mb
episode : 63, mem_used: 520.00Mb
episode : 64, mem_used: 528.13Mb
episode : 65, mem_used: 536.25Mb
episode : 66, mem_used: 544.38Mb
episode : 67, mem_used: 552.50Mb
episode : 68, mem_used: 560.63Mb
episode : 69, mem_used: 568.75Mb
episode : 70, mem_used: 576.88Mb
episode : 71, mem_used: 585.00Mb
episode : 72, mem_used: 593.13Mb
episode : 73, mem_used: 601.25Mb
episode : 74, mem_used: 609.38Mb
episode : 75, mem_used: 617.50Mb
episode : 76, mem_used: 625.63Mb
episode : 77, mem_used: 633.75Mb
episode : 78, mem_used: 641.88Mb
episode : 79, mem_used: 650.00Mb
episode : 80, mem_used: 658.13Mb
episode : 81, mem_used: 666.25Mb
episode : 82, mem_used: 674.38Mb
episode : 83, mem_used: 682.50Mb
episode : 84, mem_used: 690.63Mb
episode : 85, mem_used: 698.75Mb
episode : 86, mem_used: 706.88Mb
episode : 87, mem_used: 715.00Mb
episode : 88, mem_used: 723.13Mb
episode : 89, mem_used: 731.25Mb
episode : 90, mem_used: 739.38Mb
episode : 91, mem_used: 747.50Mb
episode : 92, mem_used: 755.63Mb
episode : 93, mem_used: 763.75Mb
episode : 94, mem_used: 771.88Mb
episode : 95, mem_used: 780.00Mb
episode : 96, mem_used: 788.13Mb
episode : 97, mem_used: 796.25Mb
episode : 98, mem_used: 804.38Mb
episode : 99, mem_used: 812.50Mb
```

**Comment by H-Huang** [comment]
Hi, CUDA tensors and CUDA RPC is not currently supported with [`RRef`](https://pytorch.org/docs/main/rpc.html#rref). It could be the case that RRef is holding a reference to the policy which resides on CUDA memory and doesn't get freed (if you comment out the forward pass then there is no memory leak). I am not entirely sure as I haven't dug into the RRef code.

You can implement RL use case with just regular `rpc_async` or `rpc_sync` calls without using RRef. As an example, in this repository I implemented and benchmarked the a3c algorithm on top of cuda rpc https://github.com/H-Huang/rpc-rl-experiments/tree/main/a3c
