### ISSUE TITLE
[Inductor][amp] clip: expected scalar type BFloat16 but found Float

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#106751]
### 🐛 Describe the bug

As the title, for reproduce:

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance torchbench clip amp

Error message:
```
loading model: 0it [00:00, ?it/s]
loading model: 0it [00:01, ?it/s]cpu  eval  clip                               

ERROR:common:expected scalar type BFloat16 but found Float
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1997, in check_accuracy
    correct_result = self.run_n_iterations(
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1882, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "benchmarks/dynamo/torchbench.py", line 437, in forward_pass
    return mod(*inputs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchmultimodal/models/clip/model.py", line 72, in forward
    embeddings_a = self.encoder_a(features_a)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchmultimodal/models/clip/image_encoder.py", line 109, in forward
    x = self.encoder(x)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/transformer.py", line 361, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/transformer.py", line 678, in forward
    x = x + self._sa_block(self.norm1(x), src_mask, src_key_padding_mask, is_causal=is_causal)
  File "/workspace/pytorch/torch/nn/modules/transformer.py", line 689, in _sa_block
    x = self.self_attn(x, x, x,
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/activation.py", line 1182, in forward
    return torch._native_multi_head_attention(
RuntimeError: expected scalar type BFloat16 but found Float
eager_1st_run_fail

```

### Versions

torchbench : 770d5cf7
torch :  2.1.0a0+git4734e4d
torchvision :  0.16.0a0+58366ab
torchtext :  0.16.0a0+c11d758
torchaudio :  2.1.0a0+dc83b38
torchdata :  0.7.0a0+1d231d1
dynamo_benchmarks :  f228c8b

**Comment by Valentine233** [comment]
The error occurs when calling `torch._native_multi_head_attention`. It exists not only with `inductor` but also with `eager`. It is found that the datatype would change after doing `at::native::matmul`: `input (Float), weight (Float) -> output (BFloat16)`.

**Comment by Valentine233** [comment]
Try to add "_native_multi_head_attention" in white list of amp, but got the error message as follow.

```
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2255, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 481, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 542, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 129, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 361, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 431, in _compile
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 416, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2071, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2159, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 837, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 937, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 993, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 989, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/__init__.py", line 1547, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1094, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3795, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3333, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2120, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2300, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1574, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 870, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 224, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 52, in newFunction
    return old_func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 312, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 498, in fx_codegen_and_compile
    fake_mode = fake_tensor_prop(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 268, in fake_tensor_prop
    FakeTensorProp(gm, mode=fake_mode).propagate_dont_convert_inputs(
  File "/workspace/pytorch/torch/fx/passes/fake_tensor_prop.py", line 61, in propagate_dont_convert_inputs
    return super().run(*args)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/workspace/pytorch/torch/fx/passes/fake_tensor_prop.py", line 33, in run_node
    result = super().run_node(n)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
  File "/workspace/pytorch/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/workspace/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 1222, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 1512, in dispatch
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/workspace/pytorch/torch/_prims_common/wrappers.py", line 229, in _fn
    result = fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_prims_common/wrappers.py", line 132, in _fn
    result = fn(**bound.arguments)
  File "/workspace/pytorch/torch/_refs/__init__.py", line 990, in add
    a, b = _maybe_broadcast(a, b)
  File "/workspace/pytorch/torch/_refs/__init__.py", line 380, in _maybe_broadcast
    common_shape = _broadcast_shapes(
  File "/workspace/pytorch/torch/_refs/__init__.py", line 369, in _broadcast_shapes
    raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Attempting to broadcast a dimension of length 8 at -2! Mismatching argument at index 1 had torch.Size([77, 32, 8, 512]); but expected shape should be broadcastable to [1, 77, 32, 512]

While executing %add_80 : [num_users=2] = call_function[target=torch.ops.aten.add.Tensor](args = (%permute_25, %_linear_pointwise_default_120), kwargs = {})
Original traceback:
  File "benchmarks/dynamo/torchbench.py", line 442, in forward_pass
    return mod(*inputs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchmultimodal/models/clip/model.py", line 73, in forward
    embeddings_b = self.encoder_b(features_b)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchmultimodal/models/clip/text_encoder.py", line 119, in forward
    embeddings = self.encoder(embeddings, mask=self.mask, is_causal=True)
```

**Comment by Valentine233** [comment]
The broadcast error above is solved by https://github.com/pytorch/pytorch/pull/107123.
