### ISSUE TITLE
Readily available python wheels for windows ARM

### ISSUE THREAD

**Issue by mwangistan** [pytorch/pytorch#106956]
### 🚀 The feature, motivation and pitch

Currently, [PyPI](https://pypi.org/project/torch/#files) does not support arm64 wheels for windows

### Alternatives

Building from source

cc @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by Blackhex** [comment]
Hello @mwangistan. The implementation of PyTorch on Window on Arm64 is an ongoing effort. We are trying to optimize the work and the list of required dependencies that needs to be enabled according to the most demanded users' use cases. It would help us if you can describe your intended use case more regarding the target hardware and the required features, please.

**Comment by mwangistan** [comment]
Hello @Blackhex , we're intending to use pytorch to run ML Benchmarks on windows ARM. We'll use pytorch functions to resize and normalize images that we can then target the CPU to run inferencing. Thanks

**Comment by Aloereed** [comment]
Are there any notable advancements regarding Pytorch on Windows ARM64 at present?

**Comment by alinpahontu2912** [comment]
Hey @Aloereed, @mwangistan, there is now a PR for windows on arm enablement currently awaiting reviews: https://github.com/pytorch/pytorch/pull/133088

**Comment by capiman** [comment]
MMhh, I am currently not sure, if I make an error. I tried again

python -m pip install torch

on Snapdragon ARM64 PC and it succeeded...? But PR is still in review?

(I have meanwhile also installed an old version of python 3.8.x, which is also behind in path variable, could it matter?)

I tried a small python example program, which used "import torch" and it tells me:

```
C:\python\python-test-export>python test-export.py
Traceback (most recent call last):
  File "C:\python\python-test-export\test-export.py", line 1, in <module>
    import torch
  File "c:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "c:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
 
C:\python\python-test-export>
```

Googling I found a program which could help to explorer the problem:

https://github.com/lucasg/Dependencies

![libomp_not_found_1](https://github.com/user-attachments/assets/99a3c5e9-822c-4095-8a3f-e9bafc2cd60a)
![libomp_not_found_2](https://github.com/user-attachments/assets/82231fe9-f1e6-494c-b434-e67e1cb7a27c)

Is this additional problem here in this entry the right place? Or shall I create a separate issue? Or just wait, because PR is not yet finished/available?

**Comment by alinpahontu2912** [comment]
Hello everyone, we are working on bringing a nightly arm64 release wheel, but in the meantime, you can build pytorch for Windows on ARM64 yourself following these instructions: https://github.com/pytorch/pytorch/wiki/Build-PyTorch-and-LibTorch-on-Windows-ARM64

**Comment by alinpahontu2912** [comment]
Hey @capiman, @mwangistan and everyone interested, there is now an official nightly release for pytorch for windows arm64. You can get it with this command: **pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu**
