### ISSUE TITLE
TIMM model tf_mobilenetv3_large_075 with torch.compile fails with `TypeError: 'Tensor' object is not callable`

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#106993]
### 🐛 Describe the bug

TIMM model tf_mobilenetv3_large_075 with torch.compile fails with `TypeError: 'Tensor' object is not callable`

Reproduce:
```python
root@48784a41d2f1:/workspace/timm-models/pytorch-image-models# python -u benchmark.py --bench train --model tf_mobilenetv3_large_075 --img-size 224 -b 128 --amp --channels-last --torchcompile
WARNING: Overriding precision to 'amp' since --amp flag set.
Benchmarking in amp precision. NHWC layout. torchscript disabled
Model tf_mobilenetv3_large_075 created, param count: 3993528
Running train benchmark on tf_mobilenetv3_large_075 for 40 steps w/ input size (3, 224, 224) and batch size 128.
Traceback (most recent call last):
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 766, in <module>
    main()
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 740, in main
    results = benchmark(args)
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 672, in benchmark
    run_results = _try_run(
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 619, in _try_run
    results = bench.run()
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 496, in run
    _step()
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 461, in _step
    self.loss(output, target).backward()
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/opt/pytorch/pytorch/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/pytorch/pytorch/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 3136, in backward
    out = call_compiled_backward()
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 3108, in call_compiled_backward
    out = call_func_with_args(
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 1507, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 333, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 373, in __call__
    return self.get_current_callable()(inputs)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 607, in run
    return model(new_inputs)
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 400, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_root/uj/cujv2yxgtagalyeunvdoybfiqkyyynscau3zfg7yg7ir4ymbrwpd.py", line 8219, in call
    extern_kernels.mm(as_strided(tangents_139, (1000, 128), (1, 1000)), view_1, out=buf1)
TypeError: 'Tensor' object is not callable
```

### Error logs

see above

### Minified repro

python -u benchmark.py --bench train --model tf_mobilenetv3_large_075 --img-size 224 -b 128 --amp --channels-last --torchcompile

### Versions

timm_commit: https://github.com/rwightman/pytorch-image-models/commit/c692715388d96cff20657e7374cde0b44ddfaa47
torch_commit: https://github.com/pytorch/pytorch/commit/2b560d3c3a9b34cd11fc9ff9e3a0be6a81d47968
triton @ git+https://github.com/openai/triton@e6216047b8b0aef1fe8da6ca8667a3ad0a016411#subdirectory=python

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by xwang233** [comment]
It still fails with the latest pytorch main today.

Is this a real issue in pytorch or should something be changed in the TIMM script?

**Comment by ezyang** [comment]
this is definitely a PyTorch bug

**Comment by Chillee** [comment]
This seems to run for me, do you still see it @xwang233 ?

**Comment by xwang233** [comment]
Yeah, I think it works with the latest pytorch nightly. Thanks for the fix! Though the compile overhead is a bit large ...

```python
root@99c6e33a5adb:/workspace/timm-models/pytorch-image-models# python -u benchmark.py --bench train --model tf_mobilenetv3_large_075 --img-size 224 -b 128 --amp --channels-last --torchcompile |& ts
Sep 01 14:23:54 WARNING: Overriding precision to 'amp' since --amp flag set.
Sep 01 14:23:54 Benchmarking in amp precision. NHWC layout. torchscript disabled
Sep 01 14:23:54 Model tf_mobilenetv3_large_075 created, param count: 3993528
Sep 01 14:23:55 Running train benchmark on tf_mobilenetv3_large_075 for 40 steps w/ input size (3, 224, 224) and batch size 128.
Sep 01 14:24:44 Train [8/40]. 2602.24 samples/sec. 49.188 ms/step.
Sep 01 14:24:44 Train [16/40]. 2586.66 samples/sec. 49.485 ms/step.
Sep 01 14:24:44 Train [24/40]. 2607.05 samples/sec. 49.098 ms/step.
Sep 01 14:24:45 Train [32/40]. 2598.58 samples/sec. 49.258 ms/step.
Sep 01 14:24:45 Train [40/40]. 2594.03 samples/sec. 49.344 ms/step.
Sep 01 14:24:45 Train benchmark of tf_mobilenetv3_large_075 done. 2564.88 samples/sec, 49.34 ms/sample
Sep 01 14:24:45 --result
Sep 01 14:24:45 {
Sep 01 14:24:45     "model": "tf_mobilenetv3_large_075",
Sep 01 14:24:45     "train_samples_per_sec": 2564.88,
Sep 01 14:24:45     "train_step_time": 49.344,
Sep 01 14:24:45     "train_batch_size": 128,
Sep 01 14:24:45     "train_img_size": 224,
Sep 01 14:24:45     "param_count": 3.99
Sep 01 14:24:45 }
```
