### ISSUE TITLE
RuntimeError: derivative for aten::_coalesced_ is not implemented

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#107097]
## Issue description

As in the title.

Calling the `_coalesced_` method to set a sparse tensor flag within a differentiable function ought to be ignored by autograd.

## Code example

```python
>>> a = torch.tensor([[0, 1], [2, 3]], dtype=torch.float64).to_sparse_coo()
>>> def func(indices, values, shape): return torch.sparse_coo_tensor(indices, values, shape)._coalesced_(True).sum()
... 
>>> torch.autograd.gradcheck(func, (a.indices(), a.values().requires_grad_(), a.shape))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torch/autograd/gradcheck.py", line 2051, in gradcheck
    return _gradcheck_helper(**args)
  File "torch/autograd/gradcheck.py", line 2080, in _gradcheck_helper
    _gradcheck_real_imag(
  File "torch/autograd/gradcheck.py", line 1482, in _gradcheck_real_imag
    gradcheck_fn(
  File "torch/autograd/gradcheck.py", line 1617, in _slow_gradcheck
    analytical = _check_analytical_jacobian_attributes(
  File "torch/autograd/gradcheck.py", line 768, in _check_analytical_jacobian_attributes
    vjps1 = _compute_analytical_jacobian_rows(vjp_fn, output.clone())
  File "torch/autograd/gradcheck.py", line 884, in _compute_analytical_jacobian_rows
    grad_inputs = vjp_fn(grad_out_base)
  File "torch/autograd/gradcheck.py", line 759, in vjp_fn
    return torch.autograd.grad(
  File "torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: derivative for aten::_coalesced_ is not implemented
```

The expected result is the same as in
```python
>>> def func(indices, values, shape): return torch.sparse_coo_tensor(indices, values, shape).coalesce().sum()
... 
>>> torch.autograd.gradcheck(func, (a.indices(), a.values().requires_grad_(), a.shape))
True
```

## System Info

- PyTorch version: main

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer @ezyang @albanD @zou3519 @gqchen @soulitzer @Lezcano @Varal7

**Comment by pearu** [comment]
A possible workaround is to add `assume_coalesced=False` argument to `sparse_coo_tensor` constructor function.

**Comment by pearu** [comment]
#107638 implements `is_coalesced` argument support for `torch.sparse_coo_tensor` that will avoid the need to use `_uncoalsced_` method for explicitly initializing the coalesce flag value.
