### ISSUE TITLE
Unit test failure: TestDistBackendWithSpawn.test_backend_group and test_backend_full_group

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#107078]
### 🐛 Describe the bug

Unit test failure: TestDistBackendWithSpawn.test_backend_group and test_backend_full_group

Reproduce:
<details><summary>very long stacktrace</summary>
<p>

```python
root@70c0b2031cc4:/opt/pytorch/pytorch# python test/run_test.py -v -i distributed/test_distributed_spawn -- -v -k test_backend_full_group
Ignoring disabled issues:  ['']
/opt/pytorch/pytorch/test/run_test.py:1369: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if torch.version.cuda is not None and LooseVersion(torch.version.cuda) >= "11.6":
Found test time stats from artifacts
Prioritized parallel tests:
 
Prioritized serial tests:
 
General parallel tests:
 
General serial tests:
 distributed/test_distributed_spawn 1/1
Ignoring disabled issues:  ['']
Ignoring disabled issues:  ['']
Running distributed/test_distributed_spawn 1/1 ... [2023-08-11 22:18:49.151994]
/usr/local/mpi/bin/mpiexec
MPI not available -- MPI backend tests will be skipped
Running distributed tests for the test backend with env init_method
Executing ['/usr/local/bin/python', '-bb', 'distributed/test_distributed_spawn.py', '-v', '-k', 'test_backend_full_group', '--shard-id=0', '--num-shards=1', '-v', '--subprocess', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest'] ... [2023-08-11 22:18:49.154615]

Expand the folded group to see the log file of distributed/test_distributed_spawn 1/1
##[group]PRINTING LOG FILE of distributed/test_distributed_spawn 1/1 (/opt/pytorch/pytorch/test/test-reports/distributed-test_distributed_spawn_b5zq10br.log)
Invalid backend test. Tests will not be run!
============================= test session starts ==============================
platform linux -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: /opt/pytorch/pytorch
configfile: pytest.ini
plugins: hypothesis-5.35.1, flakefinder-1.1.0, rerunfailures-12.0, shard-0.1.2, xdist-3.3.1, xdoctest-1.1.0
collected 0 items
Running 0 items in this shard

========================= no tests collected in 0.01s ==========================

##[endgroup]
FINISHED PRINTING LOG FILE of distributed/test_distributed_spawn 1/1 (/opt/pytorch/pytorch/test/test-reports/distributed-test_distributed_spawn_b5zq10br.log)

Running distributed tests for the test backend with file init_method
Executing ['/usr/local/bin/python', '-bb', 'distributed/test_distributed_spawn.py', '-v', '-k', 'test_backend_full_group', '--shard-id=0', '--num-shards=1', '-v', '--subprocess', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest'] ... [2023-08-11 22:18:52.704847]

Expand the folded group to see the log file of distributed/test_distributed_spawn 1/1
##[group]PRINTING LOG FILE of distributed/test_distributed_spawn 1/1 (/opt/pytorch/pytorch/test/test-reports/distributed-test_distributed_spawn_3f0yi8ee.log)
Invalid backend test. Tests will not be run!
============================= test session starts ==============================
platform linux -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: /opt/pytorch/pytorch
configfile: pytest.ini
plugins: hypothesis-5.35.1, flakefinder-1.1.0, rerunfailures-12.0, shard-0.1.2, xdist-3.3.1, xdoctest-1.1.0
collected 0 items
Running 0 items in this shard

========================= no tests collected in 0.01s ==========================

##[endgroup]
FINISHED PRINTING LOG FILE of distributed/test_distributed_spawn 1/1 (/opt/pytorch/pytorch/test/test-reports/distributed-test_distributed_spawn_3f0yi8ee.log)

Running distributed tests for the nccl backend with env init_method
Executing ['/usr/local/bin/python', '-bb', 'distributed/test_distributed_spawn.py', '-v', '-k', 'test_backend_full_group', '--shard-id=0', '--num-shards=1', '-v', '--subprocess', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest'] ... [2023-08-11 22:18:56.095219]

Expand the folded group to see the beginning of the log file of distributed/test_distributed_spawn 1/1
##[group]PRINTING BEGINNING OF LOG FILE of distributed/test_distributed_spawn 1/1 (/opt/pytorch/pytorch/test/test-reports/distributed-test_distributed_spawn_kdt1k4l3.log)
============================= test session starts ==============================
platform linux -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: /opt/pytorch/pytorch
configfile: pytest.ini
plugins: hypothesis-5.35.1, flakefinder-1.1.0, rerunfailures-12.0, shard-0.1.2, xdist-3.3.1, xdoctest-1.1.0
collected 283 items / 282 deselected / 1 selected
Running 1 items in this shard

<Module test/distributed/test_distributed_spawn.py>
  <UnitTestCase TestDistBackendWithSpawn>
    <TestCaseFunction test_backend_full_group>

=============== 1/283 tests collected (282 deselected) in 0.03s ================
============================= test session starts ==============================
platform linux -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0 -- /usr/local/bin/python
cachedir: .pytest_cache
hypothesis profile 'dev' -> database=None, max_examples=10, suppress_health_check=[HealthCheck.too_slow]
rootdir: /opt/pytorch/pytorch
configfile: pytest.ini
plugins: hypothesis-5.35.1, flakefinder-1.1.0, rerunfailures-12.0, shard-0.1.2, xdist-3.3.1, xdoctest-1.1.0
collecting ... collected 1 item
Running 1 items in this shard: test/distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_backend_full_group

distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_backend_full_group <- torch/testing/_internal/distributed/distributed_test.py INFO:numba.cuda.cudadrv.driver:init
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR] Caught exception:
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR] Traceback (most recent call last):
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 657, in run_test
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     getattr(self, test_name)()
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 543, in wrapper
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     fn()
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2376, in wrapper
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     method(*args, **kwargs)
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 174, in wrapper
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     return func(*args, **kwargs)
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 878, in test_backend_full_group
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     self._test_group_override_backend(self._init_full_group_test)
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 852, in _test_group_override_backend
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     self.assertTrue(isinstance(group_id, dist.ProcessGroupGloo))
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]   File "/usr/local/lib/python3.10/unittest/case.py", line 687, in assertTrue
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]     raise self.failureException(msg)
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR] AssertionError: False is not true
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR] To execute this test, run the following from the base repo dir:
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]      python test/distributed/test_distributed_spawn.py -k test_backend_full_group
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
[rank0]:[2023-08-11 22:19:06,572] torch.testing._internal.common_distributed: [ERROR]  exiting process 0 with exit code: 10
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] Caught exception:
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] Traceback (most recent call last):
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 657, in run_test
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     getattr(self, test_name)()
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 543, in wrapper
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     fn()
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2376, in wrapper
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     method(*args, **kwargs)
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 174, in wrapper
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     return func(*args, **kwargs)
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 878, in test_backend_full_group
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     self._test_group_override_backend(self._init_full_group_test)
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 852, in _test_group_override_backend
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     self.assertTrue(isinstance(group_id, dist.ProcessGroupGloo))
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/usr/local/lib/python3.10/unittest/case.py", line 687, in assertTrue
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     raise self.failureException(msg)
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] AssertionError: False is not true
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] To execute this test, run the following from the base repo dir:
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]      python test/distributed/test_distributed_spawn.py -k test_backend_full_group
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
[rank2]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]  exiting process 2 with exit code: 10
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] Caught exception:
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] Traceback (most recent call last):
##[endgroup]
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 657, in run_test
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     getattr(self, test_name)()
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 543, in wrapper
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     fn()
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2376, in wrapper
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     method(*args, **kwargs)
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 174, in wrapper
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     return func(*args, **kwargs)
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 878, in test_backend_full_group
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     self._test_group_override_backend(self._init_full_group_test)
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 852, in _test_group_override_backend
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     self.assertTrue(isinstance(group_id, dist.ProcessGroupGloo))
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]   File "/usr/local/lib/python3.10/unittest/case.py", line 687, in assertTrue
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]     raise self.failureException(msg)
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] AssertionError: False is not true
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] To execute this test, run the following from the base repo dir:
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]      python test/distributed/test_distributed_spawn.py -k test_backend_full_group
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
[rank1]:[2023-08-11 22:19:06,573] torch.testing._internal.common_distributed: [ERROR]  exiting process 1 with exit code: 10
FAILED [4.7563s] [100%]

=================================== FAILURES ===================================
_______________ TestDistBackendWithSpawn.test_backend_full_group _______________
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 541, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 760, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 810, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 1 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 657, in run_test
    getattr(self, test_name)()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 543, in wrapper
    fn()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2376, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 878, in test_backend_full_group
    self._test_group_override_backend(self._init_full_group_test)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 852, in _test_group_override_backend
    self.assertTrue(isinstance(group_id, dist.ProcessGroupGloo))
  File "/usr/local/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

To execute this test, run the following from the base repo dir:
     python test/distributed/test_distributed_spawn.py -k test_backend_full_group

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

Process 2 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 657, in run_test
    getattr(self, test_name)()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 543, in wrapper
    fn()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2376, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 878, in test_backend_full_group
    self._test_group_override_backend(self._init_full_group_test)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 852, in _test_group_override_backend
    self.assertTrue(isinstance(group_id, dist.ProcessGroupGloo))
  File "/usr/local/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

To execute this test, run the following from the base repo dir:
     python test/distributed/test_distributed_spawn.py -k test_backend_full_group

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0


----------------------------- Captured stdout call -----------------------------
Process 1 terminated with exit code 10, terminating remaining processes.
------------------------------ Captured log call -------------------------------
INFO     numba.cuda.cudadrv.driver:driver.py:257 init
=========================== short test summary info ============================
FAILED [4.7563s] distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_backend_full_group
============================== 1 failed in 4.78s ===============================
Test exited with non-zero exitcode 1. Command to reproduce: BACKEND=nccl WORLD_SIZE=3 /usr/local/bin/python distributed/test_distributed_spawn.py --use-pytest -v -k test_backend_full_group --shard-id=0 --num-shards=1 -v -vv -rfEX -p no:xdist --pytest-single-test distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_backend_full_group
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/distributed/test_distributed_spawn.py", line 45, in <module>
    run_tests()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 906, in run_tests
    assert len(failed_tests) == 0, "{} unit test(s) failed:\n\t{}".format(
AssertionError: 1 unit test(s) failed:
        distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_backend_full_group
FINISHED PRINTING LOG FILE of distributed/test_distributed_spawn 1/1 (/opt/pytorch/pytorch/test/test-reports/distributed-test_distributed_spawn_kdt1k4l3.log)

distributed/test_distributed_spawn 1/1 failed!
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/run_test.py", line 1709, in <module>
    main()
  File "/opt/pytorch/pytorch/test/run_test.py", line 1678, in main
    run_tests(general_tests, test_directory, options, general_failures)
  File "/opt/pytorch/pytorch/test/run_test.py", line 1585, in run_tests
    raise RuntimeError(failure.message)
RuntimeError: distributed/test_distributed_spawn 1/1 failed!
```

</p>
</details> 

Alternative reproduce (iiuc):
```python
import torch
import torch.distributed as dist

import argparse
import os

def main(rank):
    dist.init_process_group(backend='nccl')
    torch.cuda.set_device(rank)

    g = dist.new_group(backend='gloo')
    print(dist.get_backend(g), type(g), isinstance(g, dist.ProcessGroupGloo), isinstance(g, dist.ProcessGroupNCCL))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--local_rank', default=os.getenv('LOCAL_RANK', '0'))
    args = parser.parse_args()

    # print(args)
    rank = int(args.local_rank)

    main(rank)
```

run:
```python
root@70c0b2031cc4:/opt/pytorch/pytorch# torchrun --nproc_per_node=4 a.py 
[2023-08-11 22:21:30,792] torch.distributed.run: [WARNING] 
[2023-08-11 22:21:30,792] torch.distributed.run: [WARNING] *****************************************
[2023-08-11 22:21:30,792] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-08-11 22:21:30,792] torch.distributed.run: [WARNING] *****************************************
gloo <class 'torch.distributed.distributed_c10d.ProcessGroup'> False False
gloo <class 'torch.distributed.distributed_c10d.ProcessGroup'> False False
gloo <class 'torch.distributed.distributed_c10d.ProcessGroup'> False False
gloo <class 'torch.distributed.distributed_c10d.ProcessGroup'> False False
```

### Versions

pytorch: https://github.com/pytorch/pytorch/commit/03414081ff7ee011e17ee10f9ddb2584811bf965

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @ptrblck @eqy @malfet

**Comment by xwang233** [comment]
Test started failing 5/19/23. Guessing https://github.com/pytorch/pytorch/pull/101704 or similar is related. cc @H-Huang

**Comment by H-Huang** [comment]
The tests were reenabled as part of #101704, but looks like they were broken to begin with. Will send out a fix
