### ISSUE TITLE
[JIT] Making JIT work with Pyro's VAE example

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#10715]
## Issue description

Currently most Pyro [examples](https://github.com/uber/pyro/tree/dev/examples) fail when run with JIT, and one of the common errors is the following:

```
RuntimeError: nDim <= uncompressedDim ASSERT FAILED at /Users/npradhan/workspace/pyro_dev/pytorch/pytorch/torch/csrc/jit/fusion_compiler.cpp:724, please report a bug to PyTorch. (operator() at /Users/npradhan/workspace/pyro_dev/pytorch/pytorch/torch/csrc/jit/fusion_compiler.cpp:724)
```

## Code example
You can run the VAE example in Pyro as follows:

```sh
$ git checkout pytorch-0.4.1
$ python examples/vae/vae.py --num-epochs 1 --jit
```
, which throws the following error on PyTorch master.
<details><Summary> Error Trace </Summary>

```
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
warning: pytorch jit fuser failed to compile with openmp, trying without it...
Traceback (most recent call last):
  File "examples/vae/vae.py", line 212, in <module>
    model = main(args)
  File "examples/vae/vae.py", line 154, in main
    epoch_loss += svi.step(x)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/svi.py", line 96, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/trace_elbo.py", line 202, in loss_and_grads
    loss, surrogate_loss = self._loss_and_surrogate_loss(*args)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/ops/jit.py", line 59, in __call__
    ret = self.compiled[argc](*params_and_args)
  File "/Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages/torch/jit/__init__.py", line 736, in forward
    return self._get_method('forward')(*args, **kwargs)
RuntimeError: nDim <= uncompressedDim ASSERT FAILED at /Users/npradhan/workspace/pyro_dev/pytorch/pytorch/torch/csrc/jit/fusion_compiler.cpp:724, please report a bug to PyTorch. (operator() at /Users/npradhan/workspace/pyro_dev/pytorch/pytorch/torch/csrc/jit/fusion_compiler.cpp:724)
frame #0: torch::jit::CompiledFusionFunction::launch_with_tensors(at::ArrayRef<at::Tensor>, at::ArrayRef<at::Tensor>) + 1980 (0x113bcc8dc in libtorch.dylib)
frame #1: torch::jit::CompiledFusionFunction::launch(at::ArrayRef<at::Tensor>, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&) + 525 (0x113bce4dd in libtorch.dylib)
frame #2: std::__1::__function::__func<torch::jit::(anonymous namespace)::$_0::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&), std::__1::allocator<torch::jit::(anonymous namespace)::$_0::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&)>, int (std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&)>::operator()(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 379 (0x113d3c67b in libtorch.dylib)
frame #3: torch::jit::InterpreterStateImpl::runOneStage(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 139 (0x113ce933b in libtorch.dylib)
frame #4: torch::jit::GraphExecutorImpl::run(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 5756 (0x113cc456c in libtorch.dylib)
frame #5: std::__1::__function::__func<torch::jit::CodeImpl::getInterpreterOperation(torch::jit::Node*)::'lambda'(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&), std::__1::allocator<torch::jit::CodeImpl::getInterpreterOperation(torch::jit::Node*)::'lambda'(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&)>, int (std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&)>::operator()(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 45 (0x113cf143d in libtorch.dylib)
frame #6: torch::jit::InterpreterStateImpl::runOneStage(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 139 (0x113ce933b in libtorch.dylib)
frame #7: torch::jit::GraphExecutorImpl::run(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 187 (0x113cc2fab in libtorch.dylib)
frame #8: torch::jit::script::Method::run(std::__1::vector<torch::jit::IValue, std::__1::allocator<torch::jit::IValue> >&) + 346 (0x10e2ad5da in _C.cpython-36m-darwin.so)
frame #9: torch::jit::invokeScriptMethodFromPython(torch::jit::script::Method&, pybind11::args) + 279 (0x10e2a4ec7 in _C.cpython-36m-darwin.so)
frame #10: pybind11::object pybind11::detail::argument_loader<torch::jit::script::Method&, pybind11::args>::call_impl<pybind11::object, pybind11::object (*&)(torch::jit::script::Method&, pybind11::args), 0ul, 1ul, pybind11::detail::void_type>(pybind11::object (*&&&)(torch::jit::script::Method&, pybind11::args), pybind11::detail::index_sequence<0ul, 1ul>, pybind11::detail::void_type&&) + 54 (0x10e2bf5c6 in _C.cpython-36m-darwin.so)
frame #11: void pybind11::cpp_function::initialize<pybind11::object (*&)(torch::jit::script::Method&, pybind11::args), pybind11::object, torch::jit::script::Method&, pybind11::args, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::object (*&&&)(torch::jit::script::Method&, pybind11::args), pybind11::object (*)(torch::jit::script::Method&, pybind11::args), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 212 (0x10e2bf4c4 in _C.cpython-36m-darwin.so)
frame #12: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3392 (0x10df06ce0 in _C.cpython-36m-darwin.so)
<omitting python frames>
frame #60: start + 1 (0x7fff53648115 in libdyld.dylib)
```

</details>

\
To run all Pyro examples and record the output / error traces, you could also simply run:

```
$ make test-jit
```
Notice from the output of `jit.log` that most of our unit tests pass with JIT, but the bigger examples are all failing except for the simpler `bayesian_regression.py` example. I am not entirely sure under what conditions this error is triggered, but I am happy to debug more if you provide me with some pointers.

## System Info

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 0.5.0a0+e449a27
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.0)
[pip] pyro-ppl (0.2.1+a547dcbc, /Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages)
[pip] torch (0.5.0a0+e449a27)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] torch                     0.5.0a0+e449a27           <pip>
[conda] torch                     0.5.0a0+64a6003           <pip>
[conda] torch                     0.5.0a0+6456b94           <pip>
[conda] torch                     0.5.0a0+cd53b78           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

cc. @fritzo, @apaszke, @soumith

**Comment by zou3519** [comment]
Oh, this might be the same thing as https://github.com/pytorch/pytorch/issues/8560 (I was seeing the same error message)

**Comment by zou3519** [comment]
I usually just gdb. If nDim = 1 and uncompressedDim = 0 then it is probably the same issue as #8560

**Comment by neerajprad** [comment]
@zou3519 - I checked, and in all cases where this error is thrown, nDim = 1 and uncompressedDim = 0, so it's the same as #8560. Is there a resolution in the works for #8560, or do you think it might be worth exploring work arounds (I haven't yet figured out where these scalar operations are coming from)?

**Comment by zou3519** [comment]
No one's looked at it yet. Since it is blocking you I can try to take a look sometime. I'm not sure if it is worth exploring work-arounds; the graph fuser will try to fuse as many scalar tensor ops as it can, triggering the assert when the graph is interpreted in at runtime.

**Comment by neerajprad** [comment]
> I think I have a fix coming, will update you @neerajprad.

That's great to know! Thanks, @zou3519. I will re-run our jit test suite once you have a PR out.

**Comment by neerajprad** [comment]
Thanks for fixing this, @zou3519.
