### ISSUE TITLE
torch.inverse throws error when DP but not in DDP or single GPU

### ISSUE THREAD

**Issue by YuhsiHu** [pytorch/pytorch#107133]
## Description
When I use `torch.inverse` function, it throws an error when I train the model in DataParallel mode, but it will not appear if I use only a single GPU or in DDP mode. I use two RTX4090 on one machine and the OS is Ubuntu 22.04.1 LTS.

## Code
```
proj = torch.matmul(src_proj, torch.inverse(ref_proj))
```

## Error
```
Traceback (most recent call last):
  File "train.py", line 345, in <module>
    train(model, model_loss, optimizer, TrainImgLoader, TestImgLoader, start_epoch, args)
  File "train.py", line 49, in train
    loss, scalar_outputs, image_outputs = train_sample(model, model_loss, optimizer, sample, args)
  File "train.py", line 119, in train_sample
    outputs = model(
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
torch._C._LinAlgError: Caught _LinAlgError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/models/mymvsnet.py", line 101, in forward
    outputs_stage = self.StageNet(
  File "/Anaconda3/envs/mymvsnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/models/mymvsnet.py", line 151, in forward
    warped_src = homo_warping(src_fea, src_proj_new, ref_proj_new, depth_hypo)  # B C D H W
  File "/models/submodules.py", line 133, in homo_warping
    proj = torch.matmul(src_proj, torch.inverse(ref_proj))
torch._C._LinAlgError: torch.linalg.inv: (Batch element 0): The diagonal element 1 is zero, the inversion could not be completed because the input matrix is singular.
```

## Pytorch Version
```
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
```

**Comment by colesbury** [comment]
Would you please provide a self contained reproduction?

The error message is "...the input matrix is singular". DataParallel splits the input on batch size. If that results in a non-invertible matrix, you will get an error.

**Comment by lezcano** [comment]
Can you try whether this still happens in master? What's going on here is that you had something that was pretty close to singular, and it worked by chance when executed in one GPU, but it fails when run on multiple GPUs because of the reason Sam describes.

This is expected as per https://pytorch.org/docs/stable/notes/numerical_accuracy.html#extremal-values-in-linalg

As a side note, if you want to invert a matrix and then call a matmul, it's much more numerically stable to simply call `linalg.solve` rather than inverting the matrix explicitly. That being said, you still need all your matrices to be invertible.
