### ISSUE TITLE
[Inductor] Lowering for Concat op fails when performing concat with empty tensor

### ISSUE THREAD

**Issue by parthmannan** [pytorch/pytorch#107118]
### 🐛 Describe the bug

Concat of a tensor with an empty tensor fails when lowering to Inductor IR node.
The specific check failing is `assert len(input_size) == len(new_size)`

In eager mode, concat with empty tensor simply returns the regular tensor and does not fail.
Error log
```
Traceback (most recent call last):
  File "/scratch/mojitos/debug_scripts/repro_concat.py", line 24, in <module>
    compiled = compile_fx_inner(mod, args)
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/torch/_inductor/debug.py", line 220, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 52, in newFunction
    return old_func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 306, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 505, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 194, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 421, in run
    return super().run(*args)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 677, in run_node
    result = super().run_node(n)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 199, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 568, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 565, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/lowering.py", line 275, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/lowering.py", line 949, in cat
    return TensorBox(ir.ConcatKernel.create(inputs, dim))
  File "/opt/pytorch/pytorch/torch/_inductor/ir.py", line 2522, in create
    assert len(input_size) == len(new_size)
torch._inductor.exc.LoweringException: AssertionError: 
  target: aten.cat.default
  args[0]: [TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[1, 4, 32, 32], stride=[4096, 1, 128, 4]))
  )), TensorBox(StorageBox(
    InputBuffer(name='arg1_1', layout=FixedLayout('cuda', torch.float32, size=[0], stride=[1]))
  ))]
  args[1]: 1
```

To reproduce please run the following repro script
```
import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, arg0_1, convert_element_type):
        cat = torch.ops.aten.cat.default([arg0_1, convert_element_type], 1);  arg0_1 = convert_element_type = None
        return (cat,)
        
args = [((1, 4, 32, 32), (4096, 1, 128, 4), torch.float32, 'cuda'), ((0,), (1,), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro(), tracing_mode='real')(*args)

from torch._inductor.compile_fx import compile_fx_inner
from torch._dynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
ref = compiled(args)
torch.cuda.synchronize() # Ensures that segfaults are surfaced
```

### Versions

PyTorch version: 2.1.0a0+git487a33e

**Comment by wconstab** [comment]
confirmed repro and behavior diff between eager/pytorch, looks like inductor cat is incomplete and assumes only same-sized tensors can be cat'd together.
