### ISSUE TITLE
torch multiprocessing, ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

### ISSUE THREAD

**Issue by zencyyoung** [pytorch/pytorch#1071]
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vis/yangmin07/python27_tf0.12.1_gpu/lib/python2.7/site-packages/torch/__init__.py", line 335, in <module>
    import torch.multiprocessing
  File "/home/vis/yangmin07/python27_tf0.12.1_gpu/lib/python2.7/site-packages/torch/multiprocessing/__init__.py", line 33, in <module>
    from .queue import Queue, SimpleQueue
  File "/home/vis/yangmin07/python27_tf0.12.1_gpu/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 3, in <module>
    import multiprocessing.queues
  File "/home/vis/yangmin07/python27_tf0.12.1_gpu/lib/python2.7/multiprocessing/queues.py", line 48, in <module>
    from multiprocessing.synchronize import Lock, BoundedSemaphore, Semaphore, Condition
  File "/home/vis/yangmin07/python27_tf0.12.1_gpu/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

I've done http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied 

but not work

the system is centOS

**Comment by apaszke** [comment]
It's either because it's really not implemented in your system, or you have some permission issues. Maybe this thread can help you: http://stackoverflow.com/questions/270113/how-do-i-stop-sem-open-failing-with-enosys

Nevertheless, it's a Python problem with your system configuration, not a PyTorch bug. If you won't be able to resolve it, you can try asking [on our forums](discuss.pytorch.org).
