### ISSUE TITLE
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#107300]
### 🐛 Describe the bug

I'm running into some weird problem with our benchmark script, with apparently no change that caused it to stop working overnight on my machine.

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu005.nha1 ~/local/a/pytorch (pt2-torchrec)]$ python benchmarks/dynamo/torchbench.py --devices cuda --inductor --accuracy --inference --only pytorch_BERT
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 311, in _lazy_init
    queued_call()
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 180, in _check_capability
    capability = get_device_capability(d)
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 435, in get_device_capability
    prop = get_device_properties(device)
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 453, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/data/users/ezyang/a/pytorch/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=1 compare 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 481, in <module>
    torchbench_main()
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 477, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 3018, in main
    process_entry(0, runner, original_dir, args)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 2978, in process_entry
    return maybe_fresh_cache(
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 1655, in inner
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 3156, in run
    and torch.cuda.get_device_properties(0).total_memory < 25 * 2**30
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 449, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 317, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/data/users/ezyang/a/pytorch/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=1 compare 1

CUDA call was originally invoked at:

  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 11, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/users/ezyang/a/pytorch/torch/__init__.py", line 1311, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 244, in <module>
    _lazy_call(_check_capability)
  File "/data/users/ezyang/a/pytorch/torch/cuda/__init__.py", line 241, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
```

There seems to be something reducing the number of available cuda devices between the start of the script and when we initialize CUDA. If I force cuda initialization right at torchbench.py main the script successfully runs all the way through.

### Versions

main

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

**Comment by ezyang** [comment]
Minimal reproducer:

```
import torch
import os
torch.cuda.device_count()
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
torch.empty(2, device='cuda')
```

**Comment by ezyang** [comment]
This is broken again

**Comment by jramapuram** [comment]
+1: will this be fixed in torch 2.3.1? 

We use environ gating to prevent accidental memory leaks between GPUs (c.f. https://discuss.pytorch.org/t/is-it-expected-for-distributeddataparallel-to-use-more-memory-on-1-gpu-in-a-1gpu-1process-setup/77748/9)

**Comment by ezyang** [comment]
I fixed this once and for all in https://github.com/pytorch/pytorch/pull/122815 . I guess this missed the boat for 2.3.0.

**Comment by jramapuram** [comment]
Appreciate it @ezyang !  🙏

**Comment by TrappettML** [comment]
I am experiencing this error and am not sure how to go about fixing it. I have the equal version of CUDA and PyTorch, 12.1. I have updated PyTorch to 2.3.1. I get the error when I running the minimal reproducer as well as when I run torch.cuda.get_device_name(1), ( there are 3 gpus). 

`(data-science) MTrappett@saturn:~/mtrl/BranchGatingProject$ python
Python 3.9.12 (main, Jun  1 2022, 11:38:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
3
>>> torch.cuda.current_device()
Traceback (most recent call last):
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 306, in _lazy_init
    queued_call()
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 174, in _check_capability
    capability = get_device_capability(d)
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 448, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1716905969824/work/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 312, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1716905969824/work/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/__init__.py", line 1480, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 238, in <module>
    _lazy_call(_check_capability)
  File "/home/users/MTrappett/conda_voltar/envs/data-science/lib/python3.9/site-packages/torch/cuda/__init__.py", line 235, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))`

**Comment by jramapuram** [comment]
@ezyang : I can also confirm this error is not resolved with torch 2.3.1


```bash
Traceback (most recent call last):
  File "/miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 306, in _lazy_init
    queued_call()
  File "/miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 174, in _check_capability
    capability = get_device_capability(d)
  File "/miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
  File "/miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 448, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/tmp/tmp.BZwsfiNe0B/pytorch/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=
```

**Comment by ezyang** [comment]
These two reports don't involve the envvar so they are likely separate issues. To check if you have an environment misconfiguration check if nvidia-smi works

**Comment by TrappettML** [comment]
I can confirm that nvidia-smi works, however, it may be a systems issue. On a different ssh machine, using the same conda env, and loading cuda/12.1 via module, it does work.

**Comment by jramapuram** [comment]
Nope. It definately is the environ var.

```bash
> python -c "import torch; print(torch.cuda.is_available()); print(torch.__version__)"
True
2.3.1+cu121

> nvidia-smi
nvidia-smi
Fri Jun  7 18:08:52 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 12.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:00:05.0 Off |                    0 |
| N/A   36C    P0    63W / 400W |      0MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:00:06.0 Off |                    0 |
| N/A   34C    P0    67W / 400W |      0MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```bash
> ipython

In [1]: import torch
   ...: import os
   ...: torch.cuda.device_count()
   ...: os.environ["CUDA_VISIBLE_DEVICES"] = "0"
   ...: torch.empty(2, device='cuda')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:306, in _lazy_init()
    305 try:
--> 306     queued_call()
    307 except Exception as e:

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:174, in _check_capability()
    173 for d in range(device_count()):
--> 174     capability = get_device_capability(d)
    175     major = capability[0]

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:430, in get_device_capability(device)
    418 r"""Get the cuda capability of a device.
    419 
    420 Args:
   (...)
    428     tuple(int, int): the major and minor cuda capability of the device
    429 """
--> 430 prop = get_device_properties(device)
    431 return prop.major, prop.minor

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:448, in get_device_properties(device)
    447     raise AssertionError("Invalid device id")
--> 448 return _get_device_properties(device)

RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

DeferredCudaCallError                     Traceback (most recent call last)
Cell In[1], line 5
      3 torch.cuda.device_count()
      4 os.environ["CUDA_VISIBLE_DEVICES"] = "0"
----> 5 torch.empty(2, device='cuda')

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:312, in _lazy_init()
    307         except Exception as e:
    308             msg = (
    309                 f"CUDA call failed lazily at initialization with error: {str(e)}\n\n"
    310                 f"CUDA call was originally invoked at:\n\n{''.join(orig_traceback)}"
    311             )
--> 312             raise DeferredCudaCallError(msg) from e
    313 finally:
    314     delattr(_tls, "is_initializing")

DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

...
```

**Comment by BenjaminHerrera** [comment]
Issue doesn't appear to be fixed yet. This is with `2.4.0.dev20240611+cu124` and `2.4.0.dev20240610+cu124`

# Test Script:

```python
import torch

print(f"Pytorch version: {torch.__version__}")
print(f"Is CUDA available?: {torch.cuda.is_available()}")
print(f"Number of CUDA devices: {torch.cuda.device_count()}")
device = torch.device('cuda')
print(f"A torch tensor: {torch.rand(5).cuda(0)}")
print(f"A torch tensor: {torch.rand(5).cuda(1)}")
```

# Test Script Output

```bash
Pytorch version: 2.4.0.dev20240610+cu124
Is CUDA available?: True
Number of CUDA devices: 2
Traceback (most recent call last):
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 324, in _lazy_init
    queued_call()
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 192, in _check_capability
    capability = get_device_capability(d)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 448, in get_device_capability
    prop = get_device_properties(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 466, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":49, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anonuser/Projects/liyue/playground/gpu.py", line 7, in <module>
    print(f"A torch tensor: {torch.rand(5).cuda(0)}")
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 330, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":49, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

  File "/home/anonuser/Projects/liyue/playground/gpu.py", line 1, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/__init__.py", line 1694, in <module>
    _C._initExtension(_manager_path())
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 256, in <module>
    _lazy_call(_check_capability)
  File "/home/anonuser/.conda/envs/testenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 253, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))

```

# Nvidia-smi output

```
**+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:01:00.0 Off |                   On |
| N/A   44C    P0            174W /  500W |   10129MiB /  81920MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          Off |   00000000:41:00.0 Off |                   On |
| N/A   27C    P0             65W /  500W |   18051MiB /  81920MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          Off |   00000000:81:00.0 Off |                   On |
| N/A   32C    P0             65W /  500W |   53979MiB /  81920MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          Off |   00000000:C1:00.0 Off |                   On |
| N/A   26C    P0             50W /  500W |      87MiB /  81920MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| MIG devices:                                                                            |
+------------------+----------------------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |                     Memory-Usage |        Vol|      Shared           |
|      ID  ID  Dev |                       BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |
|                  |                                  |        ECC|                       |
|==================+==================================+===========+=======================|
|  1    3   0   0  |              25MiB / 19968MiB    | 28      0 |  2   0    1    0    0 |
|                  |                 0MiB / 32767MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
|  1    5   0   1  |              25MiB / 19968MiB    | 28      0 |  2   0    1    0    0 |
|                  |                 0MiB / 32767MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0    4    0    3853045      C   python                                       5666MiB |
|    0    3    0    3982710      C   python                                       4360MiB |
|    2    5    0    3982310      C   python                                      17956MiB |
|    2    3    0    3982311      C   python                                      17956MiB |
|    2    4    0    3982312      C   python                                      17956MiB |
+-----------------------------------------------------------------------------------------+**
```

**Comment by BenjaminHerrera** [comment]
I've pinned it down to the MIG being enabled. Got it to work when I run the script on a machine where MIG hasn't been enabled.

**Comment by ezyang** [comment]
Oh yeah there is some sort of problem with PyTorch and MIG that we haven't figured out yet hah

**Comment by jramapuram** [comment]
Not sure I understand the fix @BenjaminHerrera. Everything was working fine with 2.2.1 with exactly the same base nvidia container.

**Comment by darshjain** [comment]
I think I am able to reproduce this error when trying to run with Gemma3 27B IT model - 

```
# pip install git+https://github.com/huggingface/transformers@v4.49.0-Gemma-3

from transformers import pipeline
import torch

pipe = pipeline(
    "image-text-to-text",
    model="google/gemma-3-27b-it",
    device="cuda",
    torch_dtype=torch.bfloat16
)
messages = [
    {
        "role": "system",
        "content": [{"type": "text", "text": "You are a helpful assistant."}]
    },
    {
        "role": "user",
        "content": [
            {"type": "image", "url": "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/p-blog/candy.JPG"},
            {"type": "text", "text": "What animal is on the candy?"}
        ]
    }
]

output = pipe(text=messages, max_new_tokens=200)
print(output[0][0]["generated_text"][-1]["content"])


```

Versions -

```
absl-py==2.1.0
accelerate==1.5.2
archspec @ file:///home/conda/feedstock_root/build_artifacts/archspec_1708969572489/work
astunparse==1.6.3
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1721988618346/work
boltons @ file:///home/conda/feedstock_root/build_artifacts/boltons_1711936407380/work
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1687884021435/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1720457958366/work/certifi
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1723018375617/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1698833585322/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1692311806742/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1697464713350/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
conda @ file:///home/conda/feedstock_root/build_artifacts/conda_1694556032382/work
conda-libmamba-solver @ file:///home/conda/feedstock_root/build_artifacts/conda-libmamba-solver_1690880668143/work/src
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1691048088238/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1691009212940/work
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1712429897138/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1706658592802/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1696677705766/work
cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1706897031595/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1686329713262/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1686332905840/work
distro @ file:///home/conda/feedstock_root/build_artifacts/distro_1704321475663/work
filelock==3.18.0
flatbuffers==25.2.10
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1720359030008/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1719514913127/work
gast==0.6.0
google-pasta==0.2.0
graphviz==0.20.3
grpcio==1.71.0
h5py==3.13.0
huggingface==0.0.1
huggingface-hub==0.29.3
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1701026962277/work
imagecodecs @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs_1692293702904/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1719234999090/work
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1721856510709/work
inquirerpy==0.3.4
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1715127149914/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1714665484399/work
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1695536281965/work
jsonpointer @ file:///home/conda/feedstock_root/build_artifacts/jsonpointer_1718283368205/work
keras==3.9.0
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1695379920604/work
lazy_loader @ file:///home/conda/feedstock_root/build_artifacts/lazy_loader_1712342969017/work
libclang==18.1.1
libmambapy @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1689261252588/work/libmambapy
llvmlite==0.40.1
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
lz4 @ file:///home/conda/feedstock_root/build_artifacts/lz4_1704831090180/work
mamba @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1689261252588/work/mamba
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1706899926732/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1678135549780/work
mdurl==0.1.2
menuinst @ file:///home/conda/feedstock_root/build_artifacts/menuinst_1723301928768/work
ml_dtypes==0.5.1
mpmath==1.3.0
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1715670639536/work
munkres==1.1.4
namex==0.0.8
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1712540363324/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1686793481355/work
numpy==1.25.0
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-cusparselt-cu12==0.6.2
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
opt_einsum==3.4.0
optree==0.14.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1710075952259/work
pandas==1.5.3
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1715026491486/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1704469236901/work
pfzy==0.3.4
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1678273413266/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1706713388748/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1706116770704/work
ply @ file:///home/conda/feedstock_root/build_artifacts/ply_1712242996588/work
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1717777836653/work
prompt_toolkit==3.0.50
protobuf==5.29.4
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1719274586160/work
pyarrow==12.0.1
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1696355758146/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1711811537435/work
pydot==3.0.4
Pygments==2.19.1
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1722587090966/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1709721012883/work
PyQt5==5.15.9
PyQt5-sip==12.12.2
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1706886791323/work
PyWavelets==1.7.0
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1723018206044/work
regex==2024.11.6
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
rich==13.9.4
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1698138626992/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1707314491256/work
safetensors==0.5.3
scikit-image @ file:///home/conda/feedstock_root/build_artifacts/scikit-image_1681313148549/work/dist/scikit_image-0.20.0-cp311-cp311-linux_x86_64.whl
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1685023688504/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1683900207230/work/base/dist/scipy-1.10.1-cp311-cp311-linux_x86_64.whl#sha256=1bd338ba7dac51d895d5361cf982b7b10c354ea9572174207163f0bd84b8d9bb
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1672497695270/work
sip @ file:///home/conda/feedstock_root/build_artifacts/sip_1697300428897/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1715941217475/work
sympy==1.13.1
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1702066284995/work
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorflow==2.19.0
tensorflow-io-gcs-filesystem==0.37.1
termcolor==2.5.0
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1714400101435/work
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1723458355548/work
tokenizers==0.21.1
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1706112571092/work
torch==2.6.0
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1717722848697/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1707598593068/work
transformers @ git+https://github.com/huggingface/transformers@0ebd6651acd32c982fee265b23243b89bdb89577
triton==3.2.0
truststore @ file:///home/conda/feedstock_root/build_artifacts/truststore_1694154605758/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1717802530399/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1708239446578/work
wcwidth==0.2.13
Werkzeug==3.1.3
wrapt==1.17.2
xyzservices @ file:///home/conda/feedstock_root/build_artifacts/xyzservices_1717752109663/work
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1681770155528/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1723591248676/work
zstandard==0.23.0
```
