### ISSUE TITLE
MacOS self-hosted runners outage (2023-08-16)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#107347]
## Current Status
Ongoing

## Error looks like
A long queue waiting for MacOS self-hosted runners

## Incident timeline (all times pacific)
About 1700 according to the dashboard

## User impact
MacOS jobs are all blocked

## Root cause
An auto update brought down all runners, the instances are still up

```
[2023-08-16 23:34:37Z INFO SelfUpdater] DownloadUrl: https://github.com/actions/runner/releases/download/v2.308.0/actions-runner-osx-arm64-2.308.0.tar.gz
[2023-08-16 23:34:37Z INFO SelfUpdater] RuntimeTrimmed: False
[2023-08-16 23:34:37Z INFO SelfUpdater] ExternalsTrimmed: False
[2023-08-16 23:34:37Z INFO SelfUpdater] PackageDownloadTime: 315ms
[2023-08-16 23:34:37Z INFO SelfUpdater] Attempts: 1
[2023-08-16 23:34:37Z INFO SelfUpdater] PackageSize: 97MB
[2023-08-16 23:34:37Z INFO SelfUpdater] ValidateHashTime: 89ms
[2023-08-16 23:34:37Z INFO SelfUpdater] PackageExtractTime: 4034ms
[2023-08-16 23:34:37Z INFO SelfUpdater] CopyRunnerToRootTime: 2904ms
[2023-08-16 23:34:37Z INFO JobDispatcher] Waiting WorkerDispather for job 84d5ee0e-2da6-5a51-255f-96f8d2de3751 run to finish.
[2023-08-16 23:34:37Z INFO JobDispatcher] Job request 84d5ee0e-2da6-5a51-255f-96f8d2de3751 processed succeed.
[2023-08-16 23:34:37Z INFO SelfUpdater] All running job has exited.
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO SelfUpdater] Delete runner bin folder's backup at /Users/ec2-user/runner/bin.2.302.1.
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:37Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:37Z INFO SelfUpdater] Delete runner externals folder's backup at /Users/ec2-user/runner/externals.2.302.1.
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:38Z INFO SelfUpdater] Delete old version runner backup.
[2023-08-16 23:34:38Z INFO Terminal] WRITE LINE: Generate and execute update script.
[2023-08-16 23:34:38Z INFO SelfUpdater] DeleteRunnerBackupTime: 492ms
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Diag': '/Users/ec2-user/runner/_diag'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/runner/bin.2.307.1'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/runner'
[2023-08-16 23:34:38Z INFO HostContext] Well known directory 'Work': '/Users/ec2-user/runner/_work'
[2023-08-16 23:34:38Z INFO SelfUpdater] Generate update script into: /Users/ec2-user/runner/_work/_update.sh
[2023-08-16 23:34:38Z INFO SelfUpdater] Which: 'bash'
[2023-08-16 23:34:38Z INFO SelfUpdater] Location: '/bin/bash'
[2023-08-16 23:34:38Z INFO SelfUpdater] Update script start running
[2023-08-16 23:34:38Z INFO Terminal] WRITE LINE: Runner will exit shortly for update, should be back online within 10 seconds.
[2023-08-16 23:34:38Z INFO SelfUpdater] TotalUpdateTime: 10707ms
[2023-08-16 23:34:38Z INFO Terminal] WRITE LINE: Runner update process finished.
[2023-08-16 23:34:38Z INFO Runner] Auto update task finished at backend, an runner update is ready to apply exit the current runner instance.
[2023-08-16 23:34:38Z INFO Runner] Stop message queue looping.
[2023-08-16 23:34:38Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/YzkrBWJhMekfOBW8h1eJ4Q4Bjydmuc7cAAQAADuvLTTa8wncxa/_apis/distributedtask/pools/1/messages?sessionId=040c5e25-69d3-4a91-b216-5413c051a359&lastMessageId=515&status=Online&runnerVersion=2.307.1 has been cancelled.
[2023-08-16 23:34:38Z INFO MessageListener] Get next message has been cancelled.
[2023-08-16 23:34:38Z INFO Runner] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
[2023-08-16 23:34:38Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2023-08-16 23:34:38Z INFO Listener] Runner execution has finished with return code 3
```

## Mitigation
* I followed the runner and ran `make provision-mac2-nodes ` to re-provision the runners but it didn't fix the issue as I don't have permission to add org-level runners I think
* Disable MacOS job https://github.com/pytorch/pytorch/issues/98468 for now

## Prevention/followups
TBD

**Comment by huydhn** [comment]
Thank @atalman for restoring these runners. We are back in business.

**Comment by huydhn** [comment]
Auto update downloaded a newer version of the runner which was broken, and the runner failed to start up again. We need to follow up with disable auto update.
