### ISSUE TITLE
[regression] Not getting `CUDA error: device-side assert triggered` on main for CUDA_KERNEL_ASSERT2

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#107396]
### 🐛 Describe the bug

Motivated by the discussion here https://github.com/pytorch/pytorch/issues/106467#issuecomment-1677712857

Considering the following script,

```python
import torch
print(torch.__version__)
import torch.nn as nn

torch.manual_seed(0)

x = torch.randn(10, 10, requires_grad=True, device="cuda")
y = torch.randint(0, 10, (10,), device="cuda")
criterion = nn.CrossEntropyLoss()

loss = criterion(x, y)
print(loss)
# tensor(2.8109, device='cuda:0', grad_fn=<NllLossBackward0>)

y[0] = 10
loss = criterion(x, y)
print(loss)
```

Setting `y[0] = 10` should trigger https://github.com/pytorch/pytorch/blob/4bfc55ba8b0a96a1c62069b703318a729f0cc9a9/aten/src/ATen/native/cuda/Loss.cu#L254

which is defined as such

https://github.com/pytorch/pytorch/blob/4bfc55ba8b0a96a1c62069b703318a729f0cc9a9/aten/src/ATen/native/cuda/Loss.cu#L165-L170

On 2.0.1 I accurately get 

```
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

On `main` this error is not raised and I get

```
2.1.0a0+git2da735c
tensor(2.8778, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor(-2., device='cuda:0', grad_fn=<NllLossBackward0>)
```

### Versions

main

cc @ezyang @gchanan @zou3519 @ptrblck @ngimel @r-barnes

**Comment by ptrblck** [comment]
Same issue using the current nightly binary (`2.1.0.dev20230817+cu121`):
```python
python cross_entropy_loss_assert.py 
tensor(2.7439, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor(-2., device='cuda:0', grad_fn=<NllLossBackward0>)
```
As described in the linked issue, we've hit the same missing asserts before and added a unit test, which still works:
```python
python test_cuda.py -v -k test_fixed_cuda_assert_async 
test_fixed_cuda_assert_async (__main__.TestCuda) ... ../aten/src/ATen/native/cuda/TensorCompare.cu:106: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `input[0] != 0` failed.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/pbialecki/miniforge3/envs/nightly_pip_cu121/lib/python3.10/site-packages/torch/cuda/__init__.py", line 783, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/TensorCompare.cu:106: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `input[0] != 0` failed.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/pbialecki/miniforge3/envs/nightly_pip_cu121/lib/python3.10/site-packages/torch/cuda/__init__.py", line 783, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/TensorCompare.cu:106: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `input[0] != 0` failed.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/pbialecki/miniforge3/envs/nightly_pip_cu121/lib/python3.10/site-packages/torch/cuda/__init__.py", line 783, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `input[0] != c10::complex<float>(0, 0)` failed.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/pbialecki/miniforge3/envs/nightly_pip_cu121/lib/python3.10/site-packages/torch/cuda/__init__.py", line 783, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ok

----------------------------------------------------------------------
Ran 1 test in 4.327s

OK
```
I'll try to start bisecting the nightly releases to check when we started to ignore the invalid target index.

**Comment by mikaylagawarecki** [comment]
@ptrblck I suspect it might be the migration from CUDA_KERNEL_ASSERT --> CUDA_KERNEL_ASSERT2 which was committed on June 13th https://github.com/pytorch/pytorch/pull/95300

**Comment by ptrblck** [comment]
Yes, it seems you are right @mikaylagawarecki! 
```
pip install --no-deps ./torch-2.1.0.dev20230613+cu121-cp310-cp310-linux_x86_64.whl 
Processing ./torch-2.1.0.dev20230613+cu121-cp310-cp310-linux_x86_64.whl
Installing collected packages: torch
Successfully installed torch-2.1.0.dev20230613+cu121
...
python cross_entropy_loss_assert.py 
/home/pbialecki/debug/cross_entropy_loss_assert.py:14: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  x = torch.randn(10, 10, requires_grad=True, device="cuda")
tensor(2.7141, device='cuda:0', grad_fn=<NllLossBackward0>)
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/home/pbialecki/debug/cross_entropy_loss_assert.py", line 23, in <module>
    print(loss)
  File "/home/pbialecki/miniforge3/envs/tmp/lib/python3.10/site-packages/torch/_tensor.py", line 430, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/pbialecki/miniforge3/envs/tmp/lib/python3.10/site-packages/torch/_tensor_str.py", line 669, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/pbialecki/miniforge3/envs/tmp/lib/python3.10/site-packages/torch/_tensor_str.py", line 600, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/pbialecki/miniforge3/envs/tmp/lib/python3.10/site-packages/torch/_tensor_str.py", line 352, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/pbialecki/miniforge3/envs/tmp/lib/python3.10/site-packages/torch/_tensor_str.py", line 137, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
```
pip install --no-deps ./torch-2.1.0.dev20230614+cu121-cp310-cp310-linux_x86_64.whl 
Processing ./torch-2.1.0.dev20230614+cu121-cp310-cp310-linux_x86_64.whl
Installing collected packages: torch
Successfully installed torch-2.1.0.dev20230614+cu121
...
python cross_entropy_loss_assert.py 
/home/pbialecki/debug/cross_entropy_loss_assert.py:14: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  x = torch.randn(10, 10, requires_grad=True, device="cuda")
tensor(2.8818, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor(2., device='cuda:0', grad_fn=<NllLossBackward0>)
```

**Comment by mikaylagawarecki** [comment]
@ptrblck @r-barnes 

It seems like that PR might have introduced the regression. Feel free to investigate the root cause if you do have the interest/bandwidth!

In the interest of the branch cut being on the 8/25, if we do not have a fix by 8/23, the best solution here would probably be to revert the migration from `CUDA_KERNEL_ASSERT` --> `CUDA_KERNEL_ASSERT2` and defer it to a later release when there is engineering bandwidth to look into this

**Comment by malfet** [comment]
@r-barnes this goes back to https://github.com/pytorch/pytorch/pull/104054, which was landed and then quickly reverted, because device-side asserts aren't really triggered(but luckily we have CI test for index, as it caused a lot of pain in the past)

Can you please explain, how DSA is supposed to be used (with minimal example of some sort)
And +1 on reverting https://github.com/pytorch/pytorch/pull/95300

**Comment by ngimel** [comment]
+1 on reverting #95300 and in future not landing changes to error handling without extensive testing. Device assert tests are pretty expensive to run, and that infra doesn't change often,  so we try to be mindful with them, but when device assert infra changes our routine test coverage is just not enough.

**Comment by ezyang** [comment]
For anything that is more than just reverting old diffs, I would prefer the time instead be spent fixing CUDA_KERNEL_ASSERT2

**Comment by albanD** [comment]
This has been mitigated so removing highpri/milestone.
