### ISSUE TITLE
`RuntimeError: expected scalar type BFloat16 but found Float` with `torch.nn.TransformerEncoder` when `enable_nested_tensor` is `False`

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#107663]
### 🐛 Describe the bug

Runtime error occurred when running `torch.nn.TransformerEncoder` with `enable_nested_tensor = False` in AMP scope.

```python
import torch
encoder_layer = torch.nn.TransformerEncoderLayer(d_model=512, nhead=8, batch_first = True)
model = torch.nn.TransformerEncoder(encoder_layer, num_layers=6, enable_nested_tensor=False)
model.eval()
src = torch.rand(16, 41, 512)
mask = torch.rand(16, 41)
with torch.no_grad(), torch.cpu.amp.autocast():
  out = model(torch.FloatTensor(src), src_key_padding_mask = mask, is_causal = True)
  print(out[0])
```

Error message:
```
Traceback (most recent call last):
  File "/workspace/test/test1.py", line 13, in <module>
    out = model(torch.FloatTensor(src), src_key_padding_mask = mask, is_causal = True)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 387, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 678, in forward
    return torch._transformer_encoder_layer_fwd(
RuntimeError: expected scalar type BFloat16 but found Float
```

### Versions

```
Collecting environment information...                                                                                                                                                       PyTorch version: 2.1.0.dev20230820+cpu                                                                                                                                                      Is debug build: False                                                                                                                                                                       CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA                                                                                                                                                               CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA                                                                                                                                                       Nvidia driver version: No CUDA                                                                                                                                                              cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6346 CPU @ 3.10GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
Stepping:                        6
CPU max MHz:                     3600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1.5 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        40 MiB (32 instances)
L3 cache:                        72 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.0.dev20230820+cpu
[pip3] torchaudio==2.1.0.dev20230821+cpu
[pip3] torchvision==0.16.0.dev20230821+cpu
[conda] mkl-include               2023.2.0                 pypi_0    pypi
[conda] mkl-static                2023.2.0                 pypi_0    pypi
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] torch                     2.1.0.dev20230820+cpu          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230821+cpu          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230821+cpu          pypi_0    pypi
```

**Comment by jingxu10** [comment]
FYI.
another issue (shown below) will most likely occur once this issue gets fixed, under the same environment.
```
Traceback (most recent call last):
  File "/workspace/test/test2.py", line 15, in <module>
    out = transformer_encoder(src_rand, src_key_padding_mask = mask_rand)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 387, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 678, in forward
    return torch._transformer_encoder_layer_fwd(
NotImplementedError: Could not run 'aten::cat' with arguments from the 'NestedTensorCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::cat' is only available for these backends: [CPU, CUDA, HIP, MPS, IPU, XPU, HPU, VE, MTIA, PrivateUse1, PrivateUse2, PrivateUse3, Meta, FPGA, ORT, Vulkan, Metal, QuantizedCPU, QuantizedCUDA, QuantizedHIP, QuantizedMPS, QuantizedIPU, QuantizedXPU, QuantizedHPU, QuantizedVE, QuantizedMTIA, QuantizedPrivateUse1, QuantizedPrivateUse2, QuantizedPrivateUse3, QuantizedMeta, CustomRNGKeyId, MkldnnCPU, SparseCPU, SparseCsrCPU, SparseCsrCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
```

**Comment by mikaylagawarecki** [comment]
The issue here is that the `TransformerEncoder` fast path should be disabled when autocast is enabled. See here

https://github.com/pytorch/pytorch/blob/78810d78e82f8e18dbc1c049a2b92e559ab567b2/torch/nn/modules/transformer.py#L350-L351

However, `torch.is_autocast_enabled()` doesn't work on CPU, 

```
>>> with torch.autocast(device_type='cpu', dtype=torch.bfloat16):
>>>    print(torch.is_autocast_enabled())   # False
>>>    print(torch.is_autocast_cpu_enabled())  # True
```

so this is not being properly checked on CPU. If this code sample is changed to 

```
elif torch.is_autocast_enabled() or (src.is_cpu and torch.is_autocast_cpu_enabled()):
            why_not_fast_path = "autocast is enabled"
```
your script should run without error. I will send a PR to fix this.

I haven't looked into the issue in the second comment yet.

**Comment by EdwardJRoss** [comment]
It looks like the PR #108178 was closed as stale without any comment from the maintainers.

What can we do to help get this reviewed and merged?

**Comment by ElliottDyson** [comment]
> It looks like the PR #108178 was closed as stale without any comment from the maintainers.
> 
> What can we do to help get this reviewed and merged?

I was getting a similar issue with not being able to use Autocast on a transformerEncoderLayer when using both nested tensors (batched) and src_key_padding_mask together. I'm temporarily having to use fully Stochastic gradient decent (no batch dimension) to get around this. Ideally, there'd be support for both of these with autocast. Just for clarity, having those two in place without autocast also works. tests have been done with both CPU and Nvidia GPUs.
