### ISSUE TITLE
torch._dynamo.exc.InternalTorchDynamoError: 'NoneType' object has no attribute 'guards'

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#107630]
### 🐛 Describe the bug

Steps to reproduce:

pytorch version: 796ce672296c9ae8d7387b18403810aa2f1048a1
torchrec version: 005727ef06cdc808aa7d263ab4f2837938a77ed2

1. Get working torchrec install (you need fbgemm-gpu and torchrec, install by source; explicitly uninstall fbgemm-gpu-nightly and torchrec-nightly if they exist)
2. Patch torchrec with

```
diff --git a/examples/golden_training/train_dlrm.py b/examples/golden_training/train_dlrm.py
index 4004fbc..e22677d 100644
--- a/examples/golden_training/train_dlrm.py
+++ b/examples/golden_training/train_dlrm.py
@@ -151,8 +151,13 @@ def train(
             num_embeddings=num_embeddings,
         )
     )
-    for _ in tqdm(range(int(num_iterations)), mininterval=5.0):
-        train_pipeline.progress(train_iterator)
+
+    @torch.compile()
+    def f():
+        for _ in tqdm(range(int(num_iterations)), mininterval=5.0):
+            train_pipeline.progress(train_iterator)
+
+    f()
 
 
 if __name__ == "__main__":
```

3. In torchrec/examples/golden_training/ run `TORCH_LOGS=dynamo MASTER_ADDR=127.0.0.1 MASTER_PORT=29501 RANK=0 LOCAL_RANK=0 WORLD_SIZE=1 python train_dlrm.py`

Backtrace

```
Traceback (most recent call last):
  File "/data/users/ezyang/a/torchrec/examples/golden_training/train_dlrm.py", line 164, in <module>
    main()
  File "/data/users/ezyang/a/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/users/ezyang/a/torchrec/examples/golden_training/train_dlrm.py", line 52, in main
    train()
  File "/data/users/ezyang/a/torchrec/examples/golden_training/train_dlrm.py", line 160, in train
    f()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 333, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/torchrec/examples/golden_training/train_dlrm.py", line 157, in f
    for _ in tqdm(range(int(num_iterations)), mininterval=5.0):
  File "/data/users/ezyang/a/torchrec/examples/golden_training/train_dlrm.py", line 158, in <resume in f>
    train_pipeline.progress(train_iterator)
  File "/data/users/ezyang/a/torchrec/torchrec/distributed/train_pipeline.py", line 987, in progress
    self._fill_pipeline(dataloader_iter)
  File "/data/users/ezyang/a/torchrec/torchrec/distributed/train_pipeline.py", line 979, in _fill_pipeline
    self._init_pipelined_modules(self._batch_i)
  File "/data/users/ezyang/a/torchrec/torchrec/distributed/train_pipeline.py", line 1028, in _init_pipelined_modules
    self._pipelined_modules, self._model = _rewrite_model(
  File "/data/users/ezyang/a/torchrec/torchrec/distributed/train_pipeline.py", line 860, in _rewrite_model
    arg_info_list, num_found = _get_node_args(node, feature_processor_nodes)
  File "/data/users/ezyang/a/torchrec/torchrec/distributed/train_pipeline.py", line 707, in _get_node_args
    pos_arg_info_list, num_found = _get_node_args_helper(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 493, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 626, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 379, in _convert_frame_assert
    return _compile(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 571, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 554, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 181, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 476, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 443, in transform
    tracer.run()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 246, in inner
    self.output.guards.update(value.guards)
torch._dynamo.exc.InternalTorchDynamoError: 'NoneType' object has no attribute 'guards'
from user code:
   File "/data/users/ezyang/a/torchrec/torchrec/distributed/train_pipeline.py", line 656, in _get_node_args_helper
    and child_node in feature_processor_arguments
Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

Full dynamo debug log: https://gist.github.com/ezyang/deae63fd778eb63265111a3190561562

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @wconstab @Xia-Weiwen

**Comment by voznesenskym** [comment]
I am on:

torchrec 005727ef06cdc808aa7d263ab4f2837938a77ed2
pytorch 796ce672296c9ae8d7387b18403810aa2f1048a1
fbgemm ddbfa97199bd7eb0f6c6691cd3239455cb8f394e

Without Pt2:

```
File "/data/users/voz/pytorch/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: apply_with_saved not implemented: torch::autograd::CppNode<SplitLookupFunction_rowwise_adagrad_Op>
```

With eager:

```
  File "/data/users/voz/pytorch/torch/_subclasses/fake_tensor.py", line 1470, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/data/users/voz/pytorch/torch/_subclasses/fake_tensor.py", line 635, in nyi
    assert func not in _device_not_kwarg_ops, f"NYI: {func}"
torch._dynamo.exc.TorchRuntimeError: Failed running call_method pin_memory(*(FakeTensor(..., size=(26,), dtype=torch.int64),), **{}):
NYI: aten.is_pinned.default
```

With inductor:

```
  File "/tmp/torchinductor_voz/xk/cxkmydkhwrygmhto5d3ytukp33piy6hskonj7ogjvvoiivb2e7mm.py", line 126, in <module>
    async_compile.wait(globals())
  File "/data/users/voz/pytorch/torch/_inductor/codecache.py", line 1344, in wait
    scope[key] = result.result()
  File "/data/users/voz/pytorch/torch/_inductor/codecache.py", line 1203, in result
    self.future.result()
  File "/home/voz/local/miniconda3/envs/torchdynamo/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/voz/local/miniconda3/envs/torchdynamo/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AttributeError: 'instance_descriptor' object has no attribute 'ids_of_folded_args'
```

Will clean and rebuild, something is up on my end, I think.

**Comment by voznesenskym** [comment]
Perhaps a bad triton version, lets see...

**Comment by voznesenskym** [comment]
Yeah, okay, revving triton gets me identical errors w/ it.

Ed, does the non PT2 version of this file run fine for you?

**Comment by yuefengz** [comment]
> AttributeError: 'instance_descriptor' object has no attribute 'ids_of_folded_args'

I ran into the same error when I tried to wrap the Megatron-LM's model with torch.compile. Any suggestions on how to debug this?

**Comment by ezyang** [comment]
@yuefengz can you post a separate issue for your problem, with an updated repro. The repro here has gone stale.
