### ISSUE TITLE
index.Tensor_out & index_put.out errors or segfaults with indices list containing only null tensors 

### ISSUE THREAD

**Issue by manuelcandales** [pytorch/pytorch#107699]
### 🐛 Describe the bug

Indicies with **only** null tensors causes an error or segfault.
This doesn't happen if `indices` contains other tensors that aren't null

```python
import torch

input = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
indices = [None]
values = torch.tensor([10, 20], dtype=torch.float)
out = torch.tensor([[0, 0], [0, 0]], dtype=torch.float)

# Run any of the following two lines
torch.ops.aten.index.Tensor_out(input, indices, out=out)
torch.ops.aten.index_put.out(input, indices, values, False, out=out)
```

sometimes it segfaults:
```
zsh: segmentation fault
```
sometimes it throws this error:
```
RuntimeError: ntensor >= 3 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/cpu/IndexKernelUtils.h":10, please report a bug to PyTorch.
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim

**Comment by cpuhrsch** [comment]
Not sure what the right label is again

**Comment by malfet** [comment]
Actually, it no longer reproduces is it:
```
>>> import torch
... 
... input = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
... indices = [None]
... values = torch.tensor([10, 20], dtype=torch.float)
... out = torch.tensor([[0, 0], [0, 0]], dtype=torch.float)
... 
... # Run any of the following two lines
... torch.ops.aten.index.Tensor_out(input, indices, out=out)
... torch.ops.aten.index_put.out(input, indices, values, False, out=out)
... 
Traceback (most recent call last):
  File "<python-input-0>", line 9, in <module>
    torch.ops.aten.index.Tensor_out(input, indices, out=out)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/malfet/git/pytorch/pytorch-tmp/torch/_ops.py", line 916, in __call__
    return self._op(*args, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^
RuntimeError: ntensor >= 3 INTERNAL ASSERT FAILED at "/Users/malfet/git/pytorch/pytorch-tmp/aten/src/ATen/native/cpu/IndexKernelUtils.h":8, please report a bug to PyTorch. 
```
