### ISSUE TITLE
Exporting the operator 'aten::linalg_inv' to ONNX opset version 18 is not supported.

### ISSUE THREAD

**Issue by harsh-amenity** [pytorch/pytorch#107948]
While executing below code to export the model to onnx,
```
crops_flat = torch.rand([2, 3, 256, 256])
        new_intrinsic_matrix_flat = torch.rand([2, 3, 3])
        print(crops_flat.shape, type(crops_flat))
        print(new_intrinsic_matrix_flat.shape, type(new_intrinsic_matrix_flat))
        torch.onnx.export(model,
                          (([crops_flat, new_intrinsic_matrix_flat])),
                          "model.onnx",
                          input_names=['crops_flat', 'new_intrinsic_matrix_flat'],
                          output_names=['output'],
                          dynamic_axes={'crops_flat': {0: 'batch_size'},
                                        'new_intrinsic_matrix_flat': {0: 'batch_size'}},
                          opset_version=18,
                          verbose=True
                          )
```

I got this error. 
```

============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::linalg_inv' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "D:\amnt\Quidich_pose_estimation_poc\runbox\release\runbox\standalone_metrabs_torch.py", line 106, in <module>
    multiperson_model_pt = load_multiperson_model().cuda()
  File "D:\amnt\Quidich_pose_estimation_poc\runbox\release\runbox\standalone_metrabs_torch.py", line 52, in load_multiperson_model
    model_pytorch = load_crop_model()
  File "D:\amnt\Quidich_pose_estimation_poc\runbox\release\runbox\standalone_metrabs_torch.py", line 82, in load_crop_model
    torch.onnx.export(model,
  File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\torch\onnx\utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::linalg_inv' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

Process finished with exit code 1

```

Can anyone help me with this?

### Versions

Here the env

```
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 536.25
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2400
DeviceID=CPU0
Family=205
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2400
Name=Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.8
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.7
[pip3] pytorch3d==0.7.4
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2+cu117
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.0.7                    pypi_0    pypi
[conda] pytorch3d                 0.7.4                    pypi_0    pypi
[conda] torch                     2.0.1+cu117              pypi_0    pypi
[conda] torchaudio                2.0.2+cu117              pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.15.2+cu117             pypi_0    pypi
```

**Comment by justinchuby** [comment]
Matrix inverse is not currently supported by ONNX. Tracked by https://github.com/onnx/onnx/issues/3300

**Comment by harsh-amenity** [comment]
@justinchuby what are your suggestions then?

**Comment by justinchuby** [comment]
I would suggest vocalizing your needs in https://github.com/onnx/onnx/issues/3300 to help the proposal move faster. Once the operator is in the ONNX specification we will be able to support it in the exporter. 

At the same time, I think the onnx runtime has a custom op that does this: https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Inverse you may register it with 

```python
def aten_linalg_inv(g, arg):
    return g.op("com.Microsoft::Inverse", arg)


# Register custom symbolic function
torch.onnx.register_custom_op_symbolic("aten::linalg_inv", aten_linalg_inv, 17)

```

be sure to use opset 17 or lower as opset 18 is not yet fully supported by the exporter.

**Comment by justinchuby** [comment]
You may try to approximate it by implementing it as g.op(“MatMul”, g.op(“Inverse”, a), b) and register the function similarly as above. 

ONNX doesn’t come with native solvers. Feel free to open a request in the ONNX repository

**Comment by harsh-amenity** [comment]
@justinchuby I am working on increasing the inference speed of the pose estimation model and it's kind of urgent I can't wait for onnx team's update. 

Should I show you the code and model? is there any other place we can discuss this?

**Comment by justinchuby** [comment]
Try this:

```python
def aten_linalg_lstsq(g, a, b, **_):
    return g.op("MatMul", g.op("com.microsoft::Inverse", a), b)

torch.onnx.register_custom_op_symbolic("aten::linalg_lstsq", aten_linalg_lstsq, 17)
```

Inverse implemented at https://github.com/microsoft/onnxruntime/pull/3485.

If you would like to implement your own kernel for a more stable `lstsq`, it is possible to do that (https://onnxruntime.ai/docs/reference/operators/add-custom-op.html), in which case you will only need to do 

```python
def aten_linalg_lstsq(g, a, b, **_):
    return g.op("MatMul", g.op("your.domain::Lstsq", a), b)

torch.onnx.register_custom_op_symbolic("aten::linalg_lstsq", aten_linalg_lstsq, 17)
```

Assuming you implemented a custom operator `Lstsq` in ONNX Runtime. This is arguably more involved.

**Comment by harsh-amenity** [comment]
@justinchuby I have Tried:
```
def aten_linalg_lstsq(g, a, b, **_):
    return g.op("MatMul", g.op("com.microsoft::Inverse", a), b)

torch.onnx.register_custom_op_symbolic("aten::linalg_lstsq", aten_linalg_lstsq, 17)
```
and got this error,
```
TypeError: aten_linalg_lstsq() takes 3 positional arguments but 5 were given 
(Occurred when translating linalg_lstsq).
```
So I have tried this,
```
def aten_linalg_lstsq(g, a, b, *args):
    return g.op("MatMul", g.op("com.microsoft::Inverse", a), b)

torch.onnx.register_custom_op_symbolic("aten::linalg_lstsq", aten_linalg_lstsq, 17)
```
for that, I got this error.
```
File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
RuntimeError: symbolic for linalg_lstsq produced an incorrect number of outputs (expected 4, but got 1)
```

**Comment by justinchuby** [comment]
I see. So 

```
linalg_lstsq(Tensor self, Tensor b, float? rcond=None, *, str? driver=None) -> (Tensor solution, Tensor residuals, Tensor rank, Tensor singular_values)
```

(https://github.com/pytorch/pytorch/blob/6a448816f5e39f45dac7e77fcf879b256f4aa83d/aten/src/ATen/native/native_functions.yaml#L13495C9-L13495C160)

We need to figure out how to compute residuals, rank and singular_values.

**Comment by justinchuby** [comment]
Are they used in the graph? If not maybe just create `g.op("Constant", value_t=torch.tensor(0))` for them

**Comment by harsh-amenity** [comment]
let me check, I don't think they are used.

**Comment by harsh-amenity** [comment]
No others are not used, just the Tensor solution is used.

https://github.com/isarandi/metrabs/blob/8b2b116dd27372e7dbd8207809f868df4e3f852e/metrabs_pytorch/ptu3d.py#L100

**Comment by harsh-amenity** [comment]
I have tried to build by,
```
def aten_linalg_lstsq(g, a, b, *args):
    return g.op("MatMul", g.op("com.microsoft::Inverse", a), b), g.op("Constant", value_t=torch.tensor(0)), g.op("Constant", value_t=torch.tensor(0)), g.op("Constant", value_t=torch.tensor(0))
```
onnx model is successfully built.

but at the inference I got this error.
```
File "D:\amnt\Quidich_pose_estimation_poc\runbox\release\runbox\metrabs_pytorch\multiperson\multiperson_model.py", line 251, in _predict_single_batch
    pred_onx = self.sess.run([label_name], {input_name1: crops_flat.cpu().numpy(),
  File "C:\Users\harsh\anaconda3\envs\runbox\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Inverse node. Name:'/Inverse_1' Status Message: D:\a\_work\1\s\onnxruntime\contrib_ops\cuda\inverse.cc:148 onnxruntime::contrib::cuda::Inverse::ComputeInternal rows == cols was false. Expecting square matrices
```

**Comment by justinchuby** [comment]
https://pytorch.org/docs/stable/generated/torch.linalg.inv.html#torch.linalg.inv Requires a square matrix too. What’s the shape?

**Comment by harsh-amenity** [comment]
these are inputs,
```
crops_flat = torch.rand([2, 3, 256, 256])
new_intrinsic_matrix_flat = torch.rand([2, 3, 3])
```

**Comment by justinchuby** [comment]
Which one is the input to inv?

**Comment by harsh-amenity** [comment]
@justinchuby I've successfully inferred using onnx but the accuracy is very low compared to the normal model.

For inverse I have used,
```
torch.onnx.register_custom_op_symbolic("aten::linalg_inv", aten_linalg_inv, 17)
inv_intrinsics = torch.linalg.inv(intrinsics.to(coords2d.dtype))  # in the model file
```
and for lstsq instead of adding custom ops because by adding custom ops it was giving errors of shapes but the shapes were right,
```
ref_list, residuals_list, rank_list, singular_values_list = [], [], [], []
for idx in range(len(A)):
  ref, residuals, rank, singular_values = np.linalg.lstsq(
      A_regul.detach().cpu().numpy()[idx] * weights_regul.detach().cpu().numpy()[idx],
      b_regul.detach().cpu().numpy()[idx] * weights_regul.detach().cpu().numpy()[idx], rcond=None)
  ref_list.append(ref)
  residuals_list.append(residuals)
  rank_list.append(rank)
  singular_values_list.append(singular_values)
ref = torch.from_numpy(np.asarray(ref_list)).to(device)
residuals = torch.from_numpy(np.asarray(residuals_list)).to(device)
rank = torch.from_numpy(np.asarray(rank_list)).to(device)
singular_values = torch.from_numpy(np.asarray(singular_values_list)).to(device)
```

let me know your thoughts.

and also I request that, if you can add linalg support into onnx 1.16 it would be great.

**Comment by justinchuby** [comment]
The first thing I would do is to create a simple model that contains only these operators, feed inputs to them and compare if they behave the same way as PyTorch. This way we know which part of the model is in accurate.

**Comment by harsh-amenity** [comment]
I have already tested that way. The replaced functions' outputs are the same as the originals.

**Comment by shubhambhokare1** [comment]
Hi @harsh-amenity 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
