### ISSUE TITLE
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of convolution for kernel of unknown shape.

### ISSUE THREAD

**Issue by pzy2000** [pytorch/pytorch#107952]
### 🐛 Describe the bug

I met this error when converting a torch model to onnx.
I narrowed down the piece of code creating the problem shown below.

```python
import torch
from torch import nn
from torch.nn import functional as F
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class Buggy(nn.Module):
    def __init__(self):
        super(Buggy, self).__init__()

    def forward(self, x):
        dtype = x.dtype
        x = x.to(torch.float32)
        out = x
        out = F.pad(out, (1, 1, 1, 1), "constant", 0)
        out = F.conv2d(out, weight=torch.randn(out.shape[0], out.shape[1], 1, 1).float().to(device))
        out = out.to(dtype)
        return out


if __name__ == '__main__':
    net = Buggy().to(device)
    inpu = torch.ones([1, 3, 224, 224]).to(device)
    torch.onnx.export(net, inpu, "demo.onnx", verbose=True)
```

you can reproduce the error by running the above codes, error info is as follows:
/usr/local/bin/python /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py 
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/_internal/jit_utils.py:258: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
Torch IR graph at exception: graph(%0 : Float(1, 3, 224, 224, strides=[150528, 50176, 224, 1], requires_grad=0, device=cuda:0)):
  %179 : Long(device=cpu) = prim::Constant[value={6}](), scope: __main__.Buggy::
  %180 : Bool(device=cpu) = prim::Constant[value={0}](), scope: __main__.Buggy::
  %92 : NoneType = prim::Constant(), scope: __main__.Buggy::
  %93 : Float(1, 3, 224, 224, strides=[150528, 50176, 224, 1], requires_grad=0, device=cuda:0) = aten::to(%0, %179, %180, %180, %92), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:13:0
  %174 : int[] = prim::Constant[value=[1, 1, 1, 1]]()
  %99 : str = prim::Constant[value="constant"](), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:15:0
  %181 : Double(device=cpu) = prim::Constant[value={0}](), scope: __main__.Buggy::
  %101 : Float(1, 3, 226, 226, strides=[153228, 51076, 226, 1], requires_grad=0, device=cuda:0) = aten::pad(%93, %174, %99, %181), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:15:0
  %182 : Long(device=cpu) = prim::Constant[value={0}](), scope: __main__.Buggy::
  %103 : Long(device=cpu) = aten::size(%101, %182), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %183 : Long(device=cpu) = prim::Constant[value={1}](), scope: __main__.Buggy::
  %119 : Long(device=cpu) = aten::size(%101, %183), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %130 : int[] = prim::ListConstruct(%103, %119, %183, %183), scope: __main__.Buggy::
  %133 : Device = prim::Constant[value="cpu"](), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %135 : Float(1, 3, 1, 1, strides=[3, 1, 1, 1], requires_grad=0, device=cpu) = aten::randn(%130, %92, %92, %133, %180), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %140 : Float(1, 3, 1, 1, strides=[3, 1, 1, 1], requires_grad=0, device=cpu) = aten::to(%135, %179, %180, %180, %92), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %143 : Device = prim::Constant[value="cuda"](), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %148 : Float(1, 3, 1, 1, strides=[3, 1, 1, 1], requires_grad=0, device=cuda:0) = aten::to(%140, %179, %182, %143, %92, %180, %180, %92), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %175 : int[] = prim::Constant[value=[1, 1]]()
  %176 : int[] = prim::Constant[value=[0, 0]]()
  %184 : Bool(device=cpu) = prim::Constant[value={1}](), scope: __main__.Buggy::
  %168 : Float(1, 1, 226, 226, strides=[51076, 51076, 226, 1], requires_grad=0, device=cuda:0) = aten::_convolution(%101, %148, %92, %175, %176, %175, %180, %176, %183, %180, %180, %184, %184), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:16:0
  %173 : Float(1, 1, 226, 226, strides=[51076, 51076, 226, 1], requires_grad=0, device=cuda:0) = aten::to(%168, %179, %180, %180, %92), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:17:0
  return (%173)

Traceback (most recent call last):
  File "/data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py", line 24, in <module>
    torch.onnx.export(net, inpu, "demo.onnx", verbose=True, opset_version=16)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py", line 519, in export
    export_modules_as_functions=export_modules_as_functions,
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py", line 1539, in _export
    dynamic_axes=dynamic_axes,
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py", line 1123, in _model_to_graph
    module=module,
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py", line 1899, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 303, in wrapper
    return fn(g, *args, **kwargs)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 2376, in _convolution
    input,
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of convolution for kernel of unknown shape.  [Caused by the value '33 defined in (%33 : Float(*, *, *, *, strides=[153228, 51076, 226, 1], requires_grad=0, device=cuda:0) = onnx::Pad[mode="constant"](%4, %31, %32), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:15:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Pad'.] 
    (node defined in /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py(15): forward
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py(1194): _call_impl
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/jit/_trace.py(118): wrapper
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/jit/_trace.py(132): forward
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py(1194): _call_impl
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/jit/_trace.py(1184): _get_trace_graph
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py(896): _trace_and_get_graph_from_model
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py(987): _create_jit_graph
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py(1111): _model_to_graph
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py(1539): _export
/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/onnx/utils.py(519): export
/data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py(24): <module>
)

    Inputs:
        #0: 4 defined in (%4 : Float(1, 3, 224, 224, strides=[150528, 50176, 224, 1], requires_grad=0, device=cuda:0) = onnx::Cast[to=1](%0), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:13:0
    )  (type 'Tensor')
        #1: 31 defined in (%31 : Long(8, strides=[1], device=cpu) = onnx::Cast[to=7](%30), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:15:0
    )  (type 'Tensor')
        #2: 32 defined in (%32 : Float(device=cpu) = onnx::Constant[value={0}](), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:15:0
    )  (type 'Tensor')
    Outputs:
        #0: 33 defined in (%33 : Float(*, *, *, *, strides=[153228, 51076, 226, 1], requires_grad=0, device=cuda:0) = onnx::Pad[mode="constant"](%4, %31, %32), scope: __main__.Buggy:: # /data/MR/issue/issue_torch2onnx_1/test_torch2onnx.py:15:0
    )  (type 'Tensor')

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.27.1
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 21:04:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.86
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  2
Core(s) per socket:  12
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz
Stepping:            6
CPU MHz:             800.000
CPU max MHz:         3300.0000
CPU min MHz:         800.0000
BogoMIPS:            4200.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            18432K
NUMA node0 CPU(s):   0-11,24-35
NUMA node1 CPU(s):   12-23,36-47
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch2keras==0.2.4
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch2keras             0.2.4                    pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by pzy2000** [comment]
thanks for your help!
