### ISSUE TITLE
Undefined Symobl: pybind11::detail::type_caster<at::Tensor, void>::load(pybind11::handle, bool)

### ISSUE THREAD

**Issue by haopan27** [pytorch/pytorch#108041]
### 🐛 Describe the bug

This bug report is a derivation of what was reported on the pybind/pybind11 GitHub repo:
[pybind issue #4696](https://github.com/pybind/pybind11/issues/4696)

The traceback I got was:
Traceback (most recent call last):
File "run.py", line 25, in 
import cfvpy.tasks
File "/home/usrname/rebel-main/cfvpy/tasks.py", line 15, in 
import cfvpy.selfplay
File "/home/usrname/rebel-main/cfvpy/selfplay.py", line 27, in 
import cfvpy.rela
ImportError: /home/usrname/rebel-main/cfvpy/rela.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8pybind116detail11type_casterIN2at6TensorEvE4loadENS_6handleEb

To reproduce, please follow the steps as outlined by me in a comment of the pybind issue above:
[reproduction procedure](https://github.com/pybind/pybind11/issues/4696#issuecomment-1678574353)

And one of pybind's contributors, rwgk, suggested that this might be a bug/issue of PyTorch,
[rwgk's comment](https://github.com/pybind/pybind11/issues/4696#issuecomment-1679013574)

### Versions

PyTorch: 1.4.1
pybind: [a1b71df](https://github.com/pybind/pybind11/tree/a1b71df137e015d44f7e31f7b6d4807253fb7871)

**Comment by jbschlosser** [comment]
Hey @haopan27, it looks like you're dealing with a very old version of PyTorch. Do you still have issues with a PyTorch nightly build?

**Comment by Chrisgant** [comment]
In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`.
And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES). 

```
find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
```

I assume that they are separate because most C++ applications don't need the python functionalities.

**Comment by TarlanBakirli** [comment]
> In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`. And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES).
> 
> ```
> find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
> target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
> ```
> 
> I assume that they are separate because most C++ applications don't need the python functionalities.

Worked for me as well, thank you!

**Comment by hurd-git** [comment]
> In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`. And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES).
> 
> ```
> find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
> target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
> ```
> 
> I assume that they are separate because most C++ applications don't need the python functionalities.

牛逼

**Comment by ErvinXie** [comment]
This works for me! Thanks so much!

**Comment by WANGHanshuo1220** [comment]
> In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`. And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES).
> 
> ```
> find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
> target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
> ```
> 
> I assume that they are separate because most C++ applications don't need the python functionalities.

Thanks!! You are my hero :)

**Comment by yoshino-polyu** [comment]
> In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`. And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES).
> 
> ```
> find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
> target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
> ```
> 
> I assume that they are separate because most C++ applications don't need the python functionalities.

牛逼

**Comment by selmiss** [comment]
> In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`. And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES).
> 
> ```
> find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
> target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
> ```
> 
> I assume that they are separate because most C++ applications don't need the python functionalities.

It really works! You are my hero.

**Comment by sambaPython24** [comment]
Hey, thank you for providing the solution. Since I am not very experienced with pybind, could you describe 
where to put these two lines
```
find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
```
in the code?

**Comment by ankarako** [comment]
> In `site-packages/torch/lib` you will find not only `libtorch.so`, but also `libtorch_python.so`. And in our case the error was fixed by linking torch_python explicitly (I don't know what's included in TORCH_LIBRARIES).
> 
> ```
> find_library(TORCH_PYTHON_LIBRARY torch_python PATH "${TORCH_INSTALL_PREFIX}/lib")
> target_link_libraries(OurLib PRIVATE ${TORCH_LIBRARIES} ${TORCH_PYTHON_LIBRARY})
> ```
> 
> I assume that they are separate because most C++ applications don't need the python functionalities.

You just turned my frustrating afternoon to a very nice evening! :)
