### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by horizonfly99** [pytorch/pytorch#108209]
### 🐛 Describe the bug

```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/hhw/.conda/envs/geo/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    setup(
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
    self.run_command('build_ext')
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

### Versions

```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/hhw/.conda/envs/geo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/hhw/.conda/envs/geo/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

The above exception was the direct cause of the following exception:
[vision3d-main.zip](https://github.com/pytorch/pytorch/files/12471232/vision3d-main.zip)

cc @malfet @zou3519

**Comment by malfet** [comment]
Please run `python3 -mtorch.utils.collect_env` and share the output here

**Comment by fenglui** [comment]
pr 110431

**Comment by ezyang** [comment]
You didn't include the most important lines, which would be above the ninja -v line above

**Comment by sandeep-chaturvedi** [comment]
Today I had an error like this, in Android Studio, and I found no solution over internet, While looking for solution I saw a inconsistency in the project

Go **android/app/.cxx** folder, 

```
Note - for checking .cxx as it's a hidden folder.
For window users -  In file explorer, make show hidden files and deleted that folder (**.cxx**), 
For mac users - (cmd + shift + .) Now you can see the hidden files/folders and deleted that folder (**.cxx**), 
```

Then clean the project and that was the solution LOL!

**Comment by msaroufim** [comment]
No reproduction for 2 years so closing

**Comment by zqx1473** [comment]
[3/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output D:\code\jupyter\PointCloud\z_03_OtherNet\b_2021_PoinTr-master\extensions\griddi
ng\build\temp.win-amd64-cpython-39\Release\gridding.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /w
d4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_in
terface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IF:\Anaconda3\envs\py39\lib\site-packages\torch\include -IF:\Anaconda3\e
nvs\py39\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda3\envs\py39\lib\site-packages\torch\include\TH -IF:\Anaconda3\envs\py39\lib\site-packages\torch\include\THC "-IC:\Program Files\NVI
DIA GPU Computing Toolkit\CUDA\v11.8\include" -IF:\Anaconda3\envs\py39\include -IF:\Anaconda3\envs\py39\Include "-IF:\Microsoft\Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IF:\
Microsoft\Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IF:\Windows Kits\10\include\10.0.22621.0\ucrt" "-IF:\Windows Kits
\10\include\10.0.22621.0\shared" "-IF:\Windows Kits\10\include\10.0.22621.0\um" "-IF:\Windows Kits\10\include\10.0.22621.0\winrt" "-IF:\Windows Kits\10\include\10.0.22621.0\cppwinrt" -c D:\code\jupyter\PointC
loud\z_03_OtherNet\b_2021_PoinTr-master\extensions\gridding\gridding.cu -o D:\code\jupyter\PointCloud\z_03_OtherNet\b_2021_PoinTr-master\extensions\gridding\build\temp.win-amd64-cpython-39\Release\gridding.ob
j -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=gridding -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
gridding.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "F:\Anaconda3\envs\py39\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "F:\Anaconda3\envs\py39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\jupyter\PointCloud\z_03_OtherNet\b_2021_PoinTr-master\extensions\gridding\setup.py", line 11, in <module>
    setup(name='gridding',
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "F:\Anaconda3\envs\py39\lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "F:\Anaconda3\envs\py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "F:\Anaconda3\envs\py39\lib\site-packages\torch\utils\cpp_extension.py", line 842, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "F:\Anaconda3\envs\py39\lib\site-packages\torch\utils\cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "F:\Anaconda3\envs\py39\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
