### ISSUE TITLE
AttributeError: module 'sympy' has no attribute 'Expr'

### ISSUE THREAD

**Issue by ezra-ch** [pytorch/pytorch#108357]
### 🐛 Describe the bug

Traceback (most recent call last):
File "G:\anaconda3\lib\runpy.py", line 196, in run_module_as_main
return run_code(code, main_globals, None,
File "G:\anaconda3\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "G:\anaconda3\Scripts\accelerate.exe_main.py", line 4, in
File "G:\anaconda3\lib\site-packages\accelerate_init.py", line 3, in
from .accelerator import Accelerator
File "G:\anaconda3\lib\site-packages\accelerate\accelerator.py", line 32, in
import torch
File "G:\anaconda3\lib\site-packages\torch_init.py", line 1465, in
from . import _meta_registrations
File "G:\anaconda3\lib\site-packages\torch_meta_registrations.py", line 7, in
from torch._decomp import add_op_to_registry, global_decomposition_table, meta_table
File "G:\anaconda3\lib\site-packages\torch_decomp_init.py", line 169, in
import torch._decomp.decompositions
File "G:\anaconda3\lib\site-packages\torch_decomp\decompositions.py", line 10, in
import torch.prims as prims
File "G:\anaconda3\lib\site-packages\torch_prims_init.py", line 33, in
from torch.subclasses.fake_tensor import FakeTensor, FakeTensorMode
File "G:\anaconda3\lib\site-packages\torch_subclasses_init.py", line 3, in
from torch._subclasses.fake_tensor import (
File "G:\anaconda3\lib\site-packages\torch_subclasses\fake_tensor.py", line 13, in
from torch._guards import Source
File "G:\anaconda3\lib\site-packages\torch_guards.py", line 78, in
class ShapeGuard(NamedTuple):
File "G:\anaconda3\lib\site-packages\torch_guards.py", line 79, in ShapeGuard
expr: sympy.Expr
AttributeError: module 'sympy' has no attribute 'Expr'

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
wget : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:1
+ wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/uti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

**Comment by ezra-ch** [comment]
Name: torch
Version: 2.0.1+cu118
Name: accelerate
Version: 0.22.0

**Comment by fdfdfdfdhwhw** [comment]
Hello, I also encountered this problem, how did you solve it?please tell me ,thank you very much 5555

**Comment by ezra-ch** [comment]
i reinstalled anaconda
