### ISSUE TITLE
Segment_reduce can't be compiled

### ISSUE THREAD

**Issue by fishmingyu** [pytorch/pytorch#108530]
### 🐛 Describe the bug

I attempted to compile a model that includes the 'segment_reduce' function, but encountered some errors during the process. The model runs fine when not compiled with 'torch.compile'. Does anyone have suggestions on how to resolve this issue?

### Error logs

[2023-09-04 11:55:43,297] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing simple_model /home/leosys/Documents/Gencom/benchmark/segment_reduce.py:8
[2023-09-04 11:55:43,298] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line simple_model /home/leosys/Documents/Gencom/benchmark/segment_reduce.py:8
[2023-09-04 11:55:43,298] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]     def simple_model(data, lengths):
[2023-09-04 11:55:43,307] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['data'] (8,) [<DimDynamic.STATIC: 2>] [None]
[2023-09-04 11:55:43,308] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['lengths'] (3,) [<DimDynamic.STATIC: 2>] [None]
[2023-09-04 11:55:43,309] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line simple_model /home/leosys/Documents/Gencom/benchmark/segment_reduce.py:9
[2023-09-04 11:55:43,309] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]         torch.segment_reduce(data, reduce="max", lengths=lengths)
[2023-09-04 11:55:43,309] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL torch []
[2023-09-04 11:55:43,309] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR segment_reduce [TorchVariable(<module 'torch' from '/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/__init__.py'>)]
[2023-09-04 11:55:43,310] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST data [TorchVariable(<built-in method segment_reduce of type object at 0x7f77a586f860>)]
[2023-09-04 11:55:43,310] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST max [TorchVariable(<built-in method segment_reduce of type object at 0x7f77a586f860>), TensorVariable()]
[2023-09-04 11:55:43,310] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST lengths [TorchVariable(<built-in method segment_reduce of type object at 0x7f77a586f860>), TensorVariable(), ConstantVariable(str)]
[2023-09-04 11:55:43,310] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST ('reduce', 'lengths') [TorchVariable(<built-in method segment_reduce of type object at 0x7f77a586f860>), TensorVariable(), ConstantVariable(str), TensorVariable()]
[2023-09-04 11:55:43,310] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION_KW 3 [TorchVariable(<built-in method segment_reduce of type object at 0x7f77a586f860>), TensorVariable(), ConstantVariable(str), TensorVariable(), ConstantVariable(tuple)]
Traceback (most recent call last):
  File "/home/leosys/Documents/Gencom/benchmark/segment_reduce.py", line 13, in <module>
    compiled_model(data, lengths)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 333, in _fn
    return fn(*args, **kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 493, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 637, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 371, in _convert_frame_assert
    return _compile(
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 567, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 181, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 466, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 433, in transform
    tracer.run()
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2071, in run
    super().run()
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1167, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/variables/torch.py", line 716, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1180, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1254, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1352, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1320, in get_fake_value
    return wrap_fake_exception(
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 899, in wrap_fake_exception
    return fn()
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1321, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1386, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1373, in run_node
    return node.target(*args, **kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1233, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1516, in dispatch
    return maybe_run_unsafe_fallback()
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1509, in maybe_run_unsafe_fallback
    return run_fallback_kernel(self, func, args, kwargs, error)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1741, in run_fallback_kernel
    r = func(*args, **kwargs)
  File "/home/leosys/.conda/envs/gencom/lib/python3.9/site-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method segment_reduce of type object at 0x7f77a586f860>(*(FakeTensor(..., size=(8,)),), **{'reduce': 'max', 'lengths': FakeTensor(..., size=(3,), dtype=torch.int64)}):
segment_reduce(): Expected all rows of lengths along axis to sum to data.size(lengths.dim()-1) when !unsafe.

### Minified repro

TORCH_COMPILE_DEBUG=1 python segment_reduce.py 
``` python
import torch

data = torch.tensor([8, 7, 3, 4, 5, 1, 7, 2], dtype=torch.float32)
lengths = torch.tensor([2, 3, 3], dtype=torch.int64)

def simple_model(data, lengths):
    return torch.segment_reduce(data, reduce="max", lengths=lengths)


compiled_model = torch.compile(simple_model, backend="inductor")
compiled_model(data, lengths)
```

### Versions

PyTorch version: 2.1.0.dev20230821
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 525.125.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 5800X 8-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        2
Frequency boost:                 enabled
CPU max MHz:                     4850.1948
CPU min MHz:                     2200.0000
BogoMIPS:                        7586.06
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        32 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230820+cu118
[pip3] torch-geometric==2.3.1
[pip3] torchaudio==2.1.0.dev20230821+cu118
[pip3] torchvision==0.16.0.dev20230821+cu118
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch-nightly
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] numpy-base                1.25.2           py39hb5e798b_0  
[conda] pytorch                   2.1.0.dev20230821 py3.9_cuda11.8_cudnn8.7.0_0    pytorch-nightly
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230820+cu118          pypi_0    pypi
[conda] torch-geometric           2.3.1                    pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230821+cu118          pypi_0    pypi
[conda] torchtriton               2.1.0+e6216047b8            py39    pytorch-nightly
[conda] torchvision               0.16.0.dev20230821+cu118          pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by fishmingyu** [comment]
It seemed that I needed to add unsafe=True to the arg.
