### ISSUE TITLE
[dynamo] scalar <comp op> tensor not supported

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#108582]
Min repro code by @lezcano :

```python
import torch

@torch.compile(fullgraph=True)
def fn(x):
    return 0 <= x

x = torch.randn(512, device="cuda")
fn(x)
```

Here are tracing logs:
```
Step 1: torchdynamo start tracing fn check_compile_le_torch_op.py:4
TRACE starts_line fn check_compile_le_torch_op.py:4
    @torch.compile()
wrap_to_fake L['x'] (512,) [<DimDynamic.STATIC: 2>] [None]
TRACE starts_line fn check_compile_le_torch_op.py:6
        return 0 <= x
TRACE LOAD_CONST 0 []
TRACE LOAD_FAST x [ConstantVariable(int)]
TRACE COMPARE_OP <= [ConstantVariable(int), TensorVariable()]
step triggered compile
Traceback (most recent call last):
  File "/pytorch/torch/_dynamo/symbolic_convert.py", line 691, in step
    getattr(self, inst.opname)(inst)
  File "/pytorch/torch/_dynamo/symbolic_convert.py", line 1107, in COMPARE_OP
    BuiltinVariable(supported_any[op], **options).call_function(
  File "/pytorch/torch/_dynamo/variables/builtin.py", line 618, in call_function
    result = handler(tx, *args, **kwargs)
  File "/pytorch/torch/_dynamo/variables/builtin.py", line 1412, in _comparison
    _unimplemented()
  File "/pytorch/torch/_dynamo/variables/builtin.py", line 1321, in _unimplemented
    unimplemented(f"comparison {typestr(left)} {op} {typestr(right)}")
  File "/pytorch/torch/_dynamo/exc.py", line 176, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: comparison ConstantVariable(int) <built-in function le> TensorVariable()
restore_graphstate: removed 0 nodes
COMPILING GRAPH due to GraphCompileReason(reason='step_unsupported', user_stack=[<FrameSummary file check_compile_le_torch_op.py, line 6 in fn>], graph_break=True)
GUARDS:
hasattr(L['x'], '_dynamo_dynamic_indices') == False           # _dynamo/variables/builder.py:1252 in wrap_fx_proxy_cls
___is_grad_enabled()                                          # _dynamo/output_graph.py:345 in init_ambient_guards
not ___are_deterministic_algorithms_enabled()                 # _dynamo/output_graph.py:341 in init_ambient_guards
___is_torch_function_enabled()                                # _dynamo/output_graph.py:349 in init_ambient_guards
utils_device.CURRENT_DEVICE == None                           # _dynamo/output_graph.py:347 in init_ambient_guards
check_tensor(L['x'], Tensor, DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA), torch.float32, device=0, requires_grad=False, size=[512], stride=[1])  # _dynamo/variables/builder.py:1252 in wrap_fx_proxy_cls
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ysiraichi

**Comment by lezcano** [comment]
cc @ysiraichi

**Comment by OrenLeung** [comment]
can this issue be assigned to me

**Comment by ysiraichi** [comment]
Sure.
