### ISSUE TITLE
Cuda runtime error : the launch timed out and was terminated

### ISSUE THREAD

**Issue by saddy001** [pytorch/pytorch#10853]
I'm getting a cuda runtime error for various deep learning applications. Here is a minimal example

```
$ <fresh conda install>
$ conda update conda
$ conda update python
$ conda install pytorch torchvision cuda92 -c pytorch
$ git clone https://github.com/pytorch/examples
$ cd examples/mnist
$ python main.py

Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Processing...
Done!
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.373651
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/generic/THCTensorCopy.cpp line=21 error=6 : the launch timed out and was terminated
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 104, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "main.py", line 30, in train
    data, target = data.to(device), target.to(device)
RuntimeError: cuda runtime error (6) : the launch timed out and was terminated at /opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/generic/THCTensorCopy.cpp:21
```
At the same time, I get a Xid in dmesg:
```
$ dmesg|grep -i xid
[  347.164529] NVRM: Xid (PCI:0000:65:00): 8, Channel 00000010
```
I'm also seeing this error for training on https://github.com/ikostrikov/pytorch-a2c-ppo-acktr

Nvidia's [Xid error page](https://docs.nvidia.com/deploy/xid-errors/) states, that Xid 8 means "GPU stopped processing" with the following possible causes:
* Driver Error
I tested different driver versions from 387 to 396.51 and cuda versions from 8.0 to 9.2, same error

* Thermal Issue
The error appears shortly after starting the training, at 60 degrees celsius GPU temp

* Bus Error
I made different stability tests from gpu_burn to unigine heaven. All stable. I even sent my graphics card to MSI that found no device failure

* User App Error
That's why I'm here

I'm a little lost right now, hope you can help me spotting the cause of this issue.

## System Info
```
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 396.51
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a

# At the moment, /usr/local/cuda points at /usr/local/cuda-9.2, which is my current version.
# $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch
```

**Comment by saddy001** [comment]
I did some more tests. If I repeat several runs, some are getting further than 0% and the exception is different:
```
...
Train Epoch: 1 [59520/60000 (99%)]	Loss: 0.583770
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/generic/THCStorage.cpp line=36 error=6 : the launch timed out and was terminated
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 105, in main
    test(args, model, device, test_loader)
  File "main.py", line 49, in test
    test_loss += F.nll_loss(output, target, reduction='sum').item() # sum up batch loss
RuntimeError: cuda runtime error (6) : the launch timed out and was terminated at /opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/generic/THCStorage.cpp:36
```
I also tested cuda-memcheck. It reports some errors, but I don't know if it's related:
```
$ cuda-memcheck --tool racecheck python main.py
========= CUDA-MEMCHECK
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT_vec
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT_vec [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT_vec [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT_vec
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT_vec [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT_vec [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [32 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [4064 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [32 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [4064 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT [4064 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT [32 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT [4064 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT [32 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [40640 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [320 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [40640 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [320 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [352 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [40624 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [352 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [40624 hazards]
=========
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.373651
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT_vec
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT_vec [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT_vec [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT_vec
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT_vec [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT_vec [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [4064 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [32 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [4064 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [32 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [64 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [8128 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT [32 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT [4064 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NT
=========     and Read access at 0x00000078 in sgemm_32x32x32_NT [32 hazards]
=========     and Write access at 0x00000068 in sgemm_32x32x32_NT [4064 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [40640 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [320 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_NN
=========     and Write access at 0x00000068 in sgemm_32x32x32_NN [40640 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_NN [320 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [40640 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [320 hazards]
=========
========= ERROR: Race reported between Write access at 0x00000068 in sgemm_32x32x32_TN
=========     and Write access at 0x00000068 in sgemm_32x32x32_TN [40640 hazards]
=========     and Read access at 0x00000078 in sgemm_32x32x32_TN [320 hazards]
=========
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 104, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "main.py", line 34, in train
    loss.backward()
  File "/home/saddy/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/saddy/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED
========= RACECHECK SUMMARY: 24 hazards displayed (24 errors, 0 warnings) 
```

**Comment by zou3519** [comment]
cc @csarofeen

**Comment by saddy001** [comment]
Problem cause: https://devtalk.nvidia.com/default/topic/1043126/linux/xid-8-in-various-cuda-deep-learning-applications-for-nvidia-gtx-1080-ti/
