### ISSUE TITLE
Conv2d Cannot be Initialized with a Bias Tensor with Multiple Elements

### ISSUE THREAD

**Issue by Sanghyun-Hong** [pytorch/pytorch#10869]
When you do initialize a Conv2d with:

```
layer = torch.nn.Conv2d(2, 3, 4, 1, 1, bias=torch.tensor([1, 4]))
```

You may face this error message. Can you check this issue?

```
Traceback (most recent call last):
  File "pruner.py", line 236, in <module>
    model = prune_conv_layer(model, 28, 10)
  File "pruner.py", line 135, in prune_conv_layer
    bias = torch.Tensor([1, 5]))#conv.bias)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 297, in __init__
    False, _pair(0), groups, bias)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 34, in __init__
    if bias:
RuntimeError: bool value of Tensor with more than one value is ambiguous
```

**Comment by ngimel** [comment]
Bias is a boolean keyword argument https://pytorch.org/docs/stable/nn.html?highlight=conv2d#torch.nn.Conv2d, and not the initial bias value. This is not a bug.

**Comment by Sanghyun-Hong** [comment]
@ngimel Ah! my bad. Please kill me.
