### ISSUE TITLE
Fail to create new_group with backend gloo

### ISSUE THREAD

**Issue by YangFei1990** [pytorch/pytorch#108732]
### Description
I'm trying to create a new group with gloo, the script is very simple:
```
# test_gloo.py
import torch
import torch.distributed as dist
dist.init_process_group(backend="gloo")
groups = [[0, 4, 8, 12, 16, 20, 24, 28], [1, 5, 9, 13, 17, 21, 25, 29], [2, 6, 10, 14, 18, 22, 26, 30], [3, 7, 11, 15, 19, 23, 27, 31]]
rank = dist.get_rank()

self_group = None

for item in groups:
    if rank in item:
        self_group = item

gloo_group = dist.new_group(ranks=self_group, backend="gloo")
print(f"[{rank}]gloo_group finished.. rank {dist.get_rank(group=gloo_group)} size {dist.get_world_size(group=gloo_group)}")
```
I ran `torchrun --nproc-per-node 32 test_gloo.py` however I'm getting error
```
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:13195: Connection refused
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:4022: Connection refused
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:4022: Connection refused
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:50613: Connection refused
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:12710: Connection refused
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:4022: Connection refused
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:39301: Connection refused
Traceback (most recent call last):
  File "/fsx/magnus-pipe/scripts/test_gloo_simple.py", line 14, in <module>
    gloo_group = dist.new_group(ranks=self_group, backend="gloo")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
    pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/opt/conda/conda-bld/pytorch_1682343967769/work/third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [172.31.71.170]:23456: Connection refused
```

### Versions
I tried both 1.13 and 2.0.1, neither works. For my 2.0.1 env:
```
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1040-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
Stepping:                        6
CPU MHz:                         2899.982
BogoMIPS:                        5799.96
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd ida arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchdata==0.6.1
[pip3] torchelastic==0.2.2
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342
[conda] mkl-service               2.4.0           py310h5eee18b_1
[conda] mkl_fft                   1.3.6           py310h1128e8f_1
[conda] mkl_random                1.2.2           py310h1128e8f_1
[conda] numpy                     1.24.3          py310h5f9d8c6_1
[conda] numpy-base                1.24.3          py310hb5e798b_1
[conda] pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py310_cu117    pytorch
[conda] torchdata                 0.6.1                     py310    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtext                 0.15.2                    py310    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu117    pytorch
```

**Comment by YangFei1990** [comment]
Actually just figured it out need to call `new_group` for every rank. The right script should be 
```
for item in groups:
    gloo_group = dist.new_group(ranks=item, backend="gloo")
    if rank in item:
        self_group = gloo_group
```
The error message needs to improve, but I will close this issue for now.
