### ISSUE TITLE
Dynamo Swallowing Exception In Lambda

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#108798]
### 🐛 Describe the bug

Steps to reproduce:

- remove `@skipIfTorchInductor("AssertionError: RuntimeError not raised by <lambda>")` from `test_index_add_correctness` in `test_torch.py`
- run PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k test_index_add_correctness, will get error:

```
FAIL: test_index_add_correctness (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_torch.py", line 6046, in test_index_add_correctness
    self.assertRaises(RuntimeError, lambda: result.index_add_(dim, index, source))
  File "/scratch/eellison/work/pytorch/torch/testing/_internal/common_utils.py", line 3321, in assertRaises
    return super().assertRaises(expected_exception, *args, **kwargs)
AssertionError: RuntimeError not raised by <lambda>
```

Now, if you rewrite the test to just invoke the code which is supposed to throw:

```
diff --git a/test/test_torch.py b/test/test_torch.py 
index ffcf3bfcf07..de340b1500d 100644
--- a/test/test_torch.py
+++ b/test/test_torch.py
@@ -6044,9 +6044,7 @@ class TestTorch(TestCase):
                 result = torch.zeros(1, 512, 256, dtype=dtype)
                 source = torch.ones(1, 512, 256, dtype=dtype)
                 index = torch.ones(257).to(dtype=torch.long)
-                self.assertRaises(RuntimeError, lambda: result.index_add_(dim, index, source))
-                index = (torch.ones(256) * 257).to(dtype=torch.long)
-                self.assertRaises(RuntimeError, lambda: result.index_add_(dim, index, source))
+                result.index_add_(dim, index, source)
```

And re-run the test and an exception is thrown:
> RuntimeError: index_add_(): Number of indices (257) should be equal to source.size(dim): (256), for dim: 2

I think somehow the exception in the lambda is being swallowed within dynamo. I'm not sure of root cause. You can verify that this code snippet throws in a stand alone script:

```
import torch

@torch.compile()
def foo():
    dtype = torch.float
    dim = -1
    result = torch.zeros(1, 512, 256, dtype=dtype)
    source = torch.ones(1, 512, 256, dtype=dtype)
    index = torch.ones(257).to(dtype=torch.long)
    result.index_add_(dim, index, source)
    return result

foo()
```

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by williamwen42** [comment]
@eellison in what way are the tests similar?

**Comment by eellison** [comment]
I thought that one was failing because exception was not-propagating out of dynamo. But I tried the test and it passes locally so I'm probably wrong.

**Comment by williamwen42** [comment]
It seems to be failing because another exception is being raised that we're not looking for. I'm disabling the test for now (https://github.com/pytorch/pytorch/pull/108906).

**Comment by eellison** [comment]
hey @yanboliang, any chance you'd be able to work on this or know someone else who'd be able to take a look ?

**Comment by eellison** [comment]
Hm, I just ran `PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k test_index_add_correctness` and I got the following, where an error is correctly raised in the decomp, but somehow ends up not erroring in dynamo. 
 
 
 WON'T CONVERT <lambda> /home/eellison/pytorch/test/test_torch.py line 6059 
 due to: 
 Traceback (most recent call last):
   File "/home/eellison/pytorch/torch/_dynamo/convert_frame.py", line 632, in _convert_frame
     result = inner_convert(frame, cache_entry, hooks, frame_state)
   File "/home/eellison/pytorch/torch/_dynamo/convert_frame.py", line 140, in _fn
     return fn(*args, **kwargs)
   File "/home/eellison/pytorch/torch/_dynamo/convert_frame.py", line 380, in _convert_frame_assert
     return _compile(
   File "/home/eellison/pytorch/torch/_dynamo/convert_frame.py", line 559, in _compile
     guarded_code = compile_inner(code, one_graph, hooks, transform)
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 190, in time_wrapper
     r = func(*args, **kwargs)
   File "/home/eellison/pytorch/torch/_dynamo/convert_frame.py", line 481, in compile_inner
     out_code = transform_code_object(code, transform)
   File "/home/eellison/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
     transformations(instructions, code_options)
   File "/home/eellison/pytorch/torch/_dynamo/convert_frame.py", line 451, in transform
     tracer.run()
   File "/home/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 2103, in run
     super().run()
   File "/home/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in run
     and self.step()
   File "/home/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 706, in step
     getattr(self, inst.opname)(inst)
   File "/home/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 403, in wrapper
     return inner_fn(self, inst)
   File "/home/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 1139, in CALL_FUNCTION
     self.call_function(fn, args, {})
   File "/home/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 580, in call_function
     self.push(fn.call_function(self, args, kwargs))
   File "/home/eellison/pytorch/torch/_dynamo/variables/misc.py", line 619, in call_function
     return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
   File "/home/eellison/pytorch/torch/_dynamo/variables/tensor.py", line 699, in call_method
     return wrap_fx_proxy(
   File "/home/eellison/pytorch/torch/_dynamo/variables/builder.py", line 1302, in wrap_fx_proxy
     return wrap_fx_proxy_cls(
   File "/home/eellison/pytorch/torch/_dynamo/variables/builder.py", line 1389, in wrap_fx_proxy_cls
     example_value = get_fake_value(proxy.node, tx)
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 1391, in get_fake_value
     raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 1352, in get_fake_value
     return wrap_fake_exception(
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 921, in wrap_fake_exception
     return fn()
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 1353, in <lambda>
     lambda: run_node(tx.output, node, args, kwargs, nnmodule)
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 1452, in run_node
     raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
   File "/home/eellison/pytorch/torch/_dynamo/utils.py", line 1433, in run_node
     return getattr(args[0], node.target)(*args[1:], **kwargs)
   File "/home/eellison/pytorch/torch/utils/_stats.py", line 20, in wrapper
     return fn(*args, **kwargs)
   File "/home/eellison/pytorch/torch/_subclasses/fake_tensor.py", line 1323, in __torch_dispatch__
     return self.dispatch(func, types, args, kwargs)
   File "/home/eellison/pytorch/torch/_subclasses/fake_tensor.py", line 1529, in dispatch
     return decomposition_table[func](*args, **kwargs)
   File "/home/eellison/pytorch/torch/_decomp/decompositions.py", line 2223, in index_add_
     return _index_add(x, dim, index, tensor, inplace=True, alpha=alpha)
   File "/home/eellison/pytorch/torch/_decomp/decompositions.py", line 2255, in _index_add
     torch._check(
   File "/home/eellison/pytorch/torch/__init__.py", line 1028, in _check
     _check_with(RuntimeError, cond, message)
   File "/home/eellison/pytorch/torch/__init__.py", line 1011, in _check_with
     raise error_type(message_evaluated)
 torch._dynamo.exc.TorchRuntimeError: Failed running call_method index_add_(*(FakeTensor(..., size=(1, 512, 256), dtype=torch.float32), -1, FakeTensor(..., size=(257,), dtype=torch.int64), FakeTensor(..., size=(1, 512, 256), dtype=torch.float32)), **{}):
 Number of indices (257) should be equal to tensor.size(dim) (256), for dim=2
 
 from user code:
    File "/home/eellison/pytorch/test/test_torch.py", line 6059, in <lambda>
     self.assertRaises(RuntimeError, lambda: result.index_add_(dim, index, source))
 
 Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
 
 
F
======================================================================
FAIL: test_index_add_correctness (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eellison/pytorch/torch/testing/_internal/common_utils.py", line 2406, in wrapper
    method(*args, **kwargs)
  File "/home/eellison/local/miniconda3/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/eellison/pytorch/test/test_torch.py", line 6061, in test_index_add_correctness
    self.assertRaises(RuntimeError, lambda: result.index_add_(dim, index, source))
  File "/home/eellison/pytorch/torch/testing/_internal/common_utils.py", line 3345, in assertRaises
    return super().assertRaises(expected_exception, *args, **kwargs)
AssertionError: RuntimeError not raised by <lambda>

**Comment by yanboliang** [comment]
Identified the root cause, which is we set ```torch._dynamo.config.suppress_errors = True``` when testing with ```PYTORCH_TEST_WITH_INDUCTOR=1```, so the errors got suppressed.

**Comment by eellison** [comment]
I dont think this is intended behavior even with suppress_errors - that is meant for compile time errors, but it shouldn't suppress runtime ones.

**Comment by anijain2305** [comment]
@eellison I think this is related to meta kernels not raising assertion. This is the repro

```
import torch

@torch.compile()
def foo():
    g()


@torch._dynamo.disable(recursive=False)
def g():
    dtype = torch.float
    dim = -1
    result = torch.zeros(1, 512, 256, dtype=dtype, device="cuda")
    source = torch.ones(1, 512, 256, dtype=dtype, device="cuda")
    index = (torch.ones(256) * 257).to(dtype=torch.long, device="cuda")
    l = lambda: result.index_add_(dim, index, source)
    l()


def fn():
    try:
        foo()
    except RuntimeError as e:
        print(e)
        return "foo"

print(fn())
```

`suppress_errors` being True or False is a distraction here. Here, meta kernels do not raise RuntimeError and then we go all the way to Inductor, which raises a different exception here.
