### ISSUE TITLE
[Inductor][cpu][amp] model YituTechConvBert MemoryError: std::bad_alloc 

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#108761]
### 🐛 Describe the bug

bash [inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) single inference performance **huggingface YituTechConvBert** amp first static default 0

```bash
loading model: 0it [00:00, ?it/s]
loading model: 0it [00:01, ?it/s]cpu  eval  YituTechConvBert                   

[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_11
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_10
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_9
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_8
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_7
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_6
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_5
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_4
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_3
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_2
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_1
[2023-09-02 05:41:24,195] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat
skipping cudagraphs for unknown reason
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2226, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/huggingface.py", line 542, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3905, in forward
    return compiled_fn(full_args)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1482, in g
    return f(*args)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2533, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1506, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1594, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 948, in wrapper
    return optimized_function(args_new)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 384, in __call__
    return self.get_current_callable()(inputs)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 411, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/tmp0ifpl3g1/mq/cmqe2sm7fcfnwaakvotjv34ugewunddbt4tpfzfa7v5b5xac2sen.py", line 5713, in call
    buf29 = torch.ops.mkldnn._linear_pointwise(reinterpret_tensor(buf28, (1, 512, 768), (393216, 768, 1), 0), constant15, constant14, 'none', [-1], '')
  File "/workspace/pytorch/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
MemoryError: std::bad_alloc
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>73c794d</td>
      <td>4a9c6f1</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td>66f661d</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td>60bea66</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td>a6dea86</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>1d231d1</td>
      <td>757c032</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>f228c8b</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by leslie-fang-intel** [comment]
Hi @ESI-SYD, May I know the difference of `Nightly Commit` and `Main commit`? Which one should I use to reproduce this issue?

**Comment by leslie-fang-intel** [comment]
I have tested with above commits and can't reproduce this error.
Here is my env
```
Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.12
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.2.3
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.7
[pip3] torch==2.1.0a0+git4a9c6f1
[pip3] torch-fidelity==0.3.0
[pip3] torchaudio==2.1.0a0+66f661d
[pip3] torchdata==0.7.0a0+757c032
[pip3] torchmetrics==1.1.1
[pip3] torchtext==0.16.0a0+60bea66
[pip3] torchvision==0.16.0a0+a6dea86
[pip3] vector-quantize-pytorch==1.7.1
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.12                   pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.2.3                    pypi_0    pypi
[conda] mkl                       2023.2.0            intel_49495    intel
[conda] mkl-include               2023.2.0            intel_49495    intel
[conda] mkl-service               2.4.0           py310hae59892_35    intel
[conda] mkl_fft                   1.3.6           py310h173b8ae_56    intel
[conda] mkl_random                1.2.2           py310h1595b48_76    intel
[conda] mkl_umath                 0.1.1           py310hd987cd3_86    intel
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.7                    pypi_0    pypi
[conda] torch                     2.1.0a0+git4a9c6f1           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torchaudio                2.1.0a0+66f661d          pypi_0    pypi
[conda] torchdata                 0.6.1                    pypi_0    pypi
[conda] torchmetrics              1.1.1                    pypi_0    pypi
[conda] torchtext                 0.16.0a0+60bea66          pypi_0    pypi
[conda] torchvision               0.16.0a0+a6dea86          pypi_0    pypi
[conda] vector-quantize-pytorch   1.7.1                    pypi_0    pypi

```

and the test log
```
Testing with freezing on.
single-thread testing....
loading model: 0it [00:03, ?it/s]
cpu  eval  YituTechConvBert
[2023-09-08 19:35:44,398] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_11
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_10
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_9
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_8
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_7
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_6
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_5
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_4
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_3
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_2
[2023-09-08 19:35:44,399] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat_1
[2023-09-08 19:35:44,400] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat
skipping cudagraphs for unknown reason
running benchmark: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [01:21<00:00,  1.63s/it]
1.426x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,YituTechConvBert,1,1.425961,668.817389,70.912055,0.874167,160.638157,183.761306,636,1,0,0
```

**Comment by ESI-SYD** [comment]
try on SPR ? Also you can access docker env via `docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_09_02_static_default_local`

**Comment by leslie-fang-intel** [comment]
It looks like a functional issue that the system failed to allocate a memory block. I don't think it will relate to SPR or CPX. 

- Can this issue be reliably reproduced when running the above command you provided?  
- May it relate to some software version? Such as Jemalloc version and configuration parameters.
