### ISSUE TITLE
[ONNX] cache_size_limit reached when batch exporting

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#108938]
### 🐛 Describe the bug

I am exporting ~20000 single op models sequentially (https://github.com/justinchuby/torch-onnx-op-matrix/blob/66929e0cc12526acb428667c80897ba3a441ffb2/op_matrix/onnx_dynamo_op_survey.py). After some number of exports I get the `cache_size_limit reached when batch exporting` error for the rest:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1145, in dynamo_export
    ).export()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 931, in export
    graph_module = self.options.fx_tracer.generate_fx(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 199, in generate_fx
    graph_module, graph_guard = torch._dynamo.export(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1150, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 338, in _fn
    return fn(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 154, in wrapped
    return output_adapter.apply(model_func(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 500, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 347, in _convert_frame_assert
    unimplemented("cache_size_limit reached")
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 187, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: cache_size_limit reached

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/torch-onnx-op-matrix/torch-onnx-op-matrix/op_matrix/onnx_dynamo_op_survey.py", line 33, in check_single_op
    output = torch.onnx.dynamo_export(
  File "<@beartype(torch.onnx._internal.exporter.dynamo_export) at 0x7fbd55cefe20>", line 51, in dynamo_export
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1156, in dynamo_export
    raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
```

### Versions

PyTorch 2.2.0.dev20230908+cpu

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

cc @BowenBao

**Comment by BowenBao** [comment]
I wonder if it is because we missed a few `dynamo.reset()` here and there.

**Comment by justinchuby** [comment]
Let me try adding dynamo.reset(). Thanks!

**Comment by BowenBao** [comment]
Does it repro when running only that single op test?

**Comment by justinchuby** [comment]
Looks like it works now
