### ISSUE TITLE
Unsupported: call_function BuiltinVariable(all) [ListIteratorVariable()] {}

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109057]
### 🐛 Describe the bug

```
    File "/data/users/ezyang/b/torchrec/torchrec/sparse/jagged_tensor.py", line 1446, in dist_init
      if all(bs == batch_size_per_rank[0] for bs in batch_size_per_rank):
```

raises

```
    File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 565, in call_function
      self.push(fn.call_function(self, args, kwargs))
    File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/builtin.py", line 645, in call_function
      return super().call_function(tx, args, kwargs)
    File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/base.py", line 306, in call_function
      unimplemented(f"call_function {self} {args} {kwargs}")
    File "/data/users/ezyang/b/pytorch/torch/_dynamo/exc.py", line 176, in unimplemented
      raise Unsupported(msg)
  torch._dynamo.exc.Unsupported: call_function BuiltinVariable(all) [ListIteratorVariable()] {}
```

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by Deusy94** [comment]
Can't replicate the specific error, but I still got this:

```
import torch

@torch.compile(backend="eager", fullgraph=True)
def f(t):
    batch_size_per_rank = [2, 2, 2, 2, 2, 2]
    if all(bs == batch_size_per_rank[0] for bs in batch_size_per_rank):
        return t
    else:
        return 1 - t
        
if __name__ == "__main__":
    torch.manual_seed(42)
    print(f(torch.randn(1)))
```
raise:
```
Traceback (most recent call last):
  File "/home/andrea/PycharmProjects/pytorch/bug_2.py", line 25, in <module>
    print(f(torch.randn(1)))
  File "/home/andrea/PycharmProjects/pytorch/torch/_dynamo/eval_frame.py", line 337, in _fn
    return fn(*args, **kwargs)
  File "/home/andrea/PycharmProjects/pytorch/bug_2.py", line 9, in f
    if all(bs == batch_size_per_rank[0] for bs in batch_size_per_rank):
  File "/home/andrea/PycharmProjects/pytorch/torch/_dynamo/eval_frame.py", line 499, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/andrea/PycharmProjects/pytorch/torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "/home/andrea/PycharmProjects/pytorch/torch/_dynamo/convert_frame.py", line 315, in _convert_frame_assert
    unimplemented("generator")
  File "/home/andrea/PycharmProjects/pytorch/torch/_dynamo/exc.py", line 176, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: generator
```
