### ISSUE TITLE
Failure using compile for HF transformers `google/flan-ul2` and `google/flan-t5-xl` when batch size is not a power of 2

### ISSUE THREAD

**Issue by tdoublep** [pytorch/pytorch#109196]
### 🐛 Describe the bug

The error is reproduced with the following snippet:

```python
from transformers import AutoModelForSeq2SeqLM
import torch
import torch._dynamo
from torch._inductor.compile_fx import compile_fx

torch.backends.cuda.matmul.allow_tf32 = True

device = torch.device('cuda:0')

with device:
    model = AutoModelForSeq2SeqLM.from_pretrained(
        "google/flan-t5-xl", torch_dtype=torch.float16
    ).eval()
    model.to(device)

compiled_forward = torch._dynamo.optimize(
    compile_fx,
    dynamic=True,
)(model.forward)

with torch.no_grad():
    toks = torch.ones(size=(12,1), dtype=int, device=device)
    compiled_forward(
        input_ids=toks,
        attention_mask=toks,
        decoder_input_ids=toks,
    )
```
When the batch size (first dim of `toks`) is a power of 2, everything works. However if it is not (as in the above example), we get the error below. 

### Error logs

```python
$ python /tmp/test.py 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.52s/it]
/opt/miniconda/lib/python3.9/site-packages/torch/overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/opt/miniconda/lib/python3.9/site-packages/torch/overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/opt/miniconda/lib/python3.9/site-packages/torch/overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/opt/miniconda/lib/python3.9/site-packages/torch/overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
Traceback (most recent call last):
  File "/tmp/test.py", line 25, in <module>
    compiled_forward(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 338, in _fn
    return fn(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 500, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 634, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 382, in _convert_frame_assert
    return _compile(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 562, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 484, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 451, in transform
    tracer.run()
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2078, in run
    super().run()
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 728, in run
    and self.step()
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 691, in step
    getattr(self, inst.opname)(inst)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2166, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 905, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/miniconda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 1008, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 1075, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 1060, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1164, in compile_fx
    return aot_autograd(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 3891, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 3429, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2212, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2392, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1573, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1106, in fw_compiler_base
    return inner_compile(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/debug.py", line 228, in inner
    return fn(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 55, in newFunction
    return old_func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 348, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 574, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/graph.py", line 991, in compile_to_fn
    return self.compile_to_module().call
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/graph.py", line 946, in compile_to_module
    mod = PyCodeCache.load_by_key_path(key, path, linemap=linemap)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 1156, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_1000790000/e6/ce6z47qglnn53vil2auo2wljkqq6g5ttulum3pbujkkqzkthpnhd.py", line 2136, in <module>
    async_compile.wait(globals())
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 1435, in wait
    scope[key] = result.result()
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 1294, in result
    self.future.result()
  File "/opt/miniconda/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/opt/miniconda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx' raised:
CompilationError: at 35:48:        tmp9 = tl.where(tmp2, tmp8, 0)
        tmp10 = tl.broadcast_to(tmp9, [XBLOCK, RBLOCK])
        tmp12 = _tmp11 | tmp10
        _tmp11 = tl.where(rmask & xmask, tmp12, _tmp11)
        tl.device_assert(((0 <= tmp4) & (tmp4 < 32128)) | ~(xmask & rmask & tmp2), "index out of bounds: 0 <= tmp4 < 32128")
        tmp13 = tl.load(in_ptr3 + ((r1 + (x0*((2 + (2048*ks0)) // 3))) % (2048*ks0)), rmask & tmp2 & xmask, other=0).to(tl.float32)
        tmp14 = tmp5 + tmp13
        tmp15 = tl.math.isinf(tmp14).to(tl.int1)
        tmp16 = tl.where(tmp2, tmp15, 0)
        tmp17 = tl.broadcast_to(tmp16, [XBLOCK, RBLOCK])
        tmp19 = _tmp18 | tmp17
        _tmp18 = tl.where(rmask & xmask, tmp19, _tmp18)
                                                ^
AssertionError('Loop-carried variable _tmp11 has initial type <[1, 2048], int1> but is re-assigned to <[1, 2048], int32> in loop! Please make sure that the type stays consistent.')

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo

```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230904+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux 9.2 (Plow) (x86_64)
GCC version: (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.34

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.43.1.el8_6.x86_64-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Vendor ID:                       GenuineIntel
Model name:                      Intel Xeon Processor (Cascadelake)
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
Stepping:                        5
BogoMIPS:                        4799.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat pku ospke avx512_vnni md_clear arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.5 MiB (80 instances)
L1i cache:                       2.5 MiB (80 instances)
L2 cache:                        160 MiB (40 instances)
L3 cache:                        32 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-39
NUMA node1 CPU(s):               40-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-protobuf==3.4.0
[pip3] numpy==1.25.2
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230904+cu118
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230904+cu118          pypi_0    pypi
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by tdoublep** [comment]
One additional info: this error is not observed using nightly `2.1.0.dev20230730+cu118`, so it is something that crept in fairly recently.

**Comment by voznesenskym** [comment]
Does this work without compile?

**Comment by peterbell10** [comment]
@tdoublep can you post the contents of 
`/tmp/torchinductor_1000790000/e6/ce6z47qglnn53vil2auo2wljkqq6g5ttulum3pbujkkqzkthpnhd.py`

**Comment by tdoublep** [comment]
Sorry for late reply, haven't had much time last few weeks. Thank you for looking into this. 

> Does this work without compile?

@voznesenskym -- yes I just double-checked

> can you post the contents of
/tmp/torchinductor_1000790000/e6/ce6z47qglnn53vil2auo2wljkqq6g5ttulum3pbujkkqzkthpnhd.py


@peterbell10 it's rather huge so I attached it: 
[cbn6nqtdevf2ioumzjuajl3nj7m4f2lyqicavemkesd4ol5alpqg.py.zip](https://github.com/pytorch/pytorch/files/12718983/cbn6nqtdevf2ioumzjuajl3nj7m4f2lyqicavemkesd4ol5alpqg.py.zip)
