### ISSUE TITLE
torch.isclose() breaks for integral scalar type inputs

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#10916]
```
import torch
import torch.testing

torch.testing.assert_allclose(torch.LongTensor([1, 2, 3]), torch.LongTensor([1, 2, 3]))
```

gives

```
Traceback (most recent call last):
  File "allclose.py", line 4, in <module>
    torch.testing.assert_allclose(torch.LongTensor([1, 2, 3]), torch.LongTensor([1, 2, 3]))
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/testing/__init__.py", line 28, in assert_allclose
    close = torch.isclose(actual, expected, rtol, atol, equal_nan)
RuntimeError: value cannot be converted to type int64_t without overflow: inf
```

It seems the underlying issue is here, where we are specially handling INF values: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorCompare.cpp#L48

The INFINITY to compare to cannot be cast to a LongType to match the lhs operand of the `==` operators

**Comment by jamesr66a** [comment]
This seems to be fixed
