### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cqdaxue** [pytorch/pytorch#10938]
Recently,the model is training and the following error occurred 
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    train(opt, data_loader, model, visualizer)
  File "train.py", line 16, in train
    for i, data in enumerate(dataset):
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/home/cui/anaconda3/lib/python3.6/site-packages/PIL/ImageFile.py", line 212, in load
    s = read(self.decodermaxblock)
  File "/home/cui/anaconda3/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 592, in load_read
    cid, pos, length = self.png.read()
  File "/home/cui/anaconda3/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 113, in read
    length = i32(s)
  File "/home/cui/anaconda3/lib/python3.6/site-packages/PIL/_binary.py", line 76, in i32be
    return unpack(">I", c[o:o+4])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mywork/experiment_sn_2000_1/data/aligned_dataset.py", line 28, in __getitem__
    AB = Image.open(AB_path).convert('RGB')
  File "/home/cui/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 860, in convert
    self.load()
  File "/home/cui/anaconda3/lib/python3.6/site-packages/PIL/ImageFile.py", line 217, in load
    raise IOError("image file is truncated")
OSError: image file is truncated

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa236f953c8>>
Traceback (most recent call last):
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/cui/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/cui/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/cui/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/cui/anaconda3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/cui/anaconda3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by SsnL** [comment]
Your image is broken.
