### ISSUE TITLE
[PT2.1/ PT2.2(Nightly)][torch.compile][dynamic shape enabled]: TorchDynamo failed with Dynamic shape gives runtime error in 'pow' operation.

### ISSUE THREAD

**Issue by vikram2112** [pytorch/pytorch#109365]
### 🐛 Describe the bug

When dynamic flag enabled in torch.compile and the 'pow' operation is executed on the CPU, it is observed that TorchDynamo encounters a runtime error. However, the same operation, when executed with dynamic flag disabled in torch.compile, results in the proper generation and execution of the FX graph on the CPU.

Tried latest Nightly version(2.2.0.dev20230914+cpu).
Code Block:
```
import torch
import torch.nn as nn
import os
from typing import List
def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print(gm.code)
    print(gm.graph)
    gm.graph.print_tabular()
    return gm.forward

class OpWrapperModule(torch.nn.Module):
    def __init__(self, op):
        super().__init__()
        self.op = op

    def forward(self, inputs):
        result = self.op(**inputs)
        return result

def test_dynamic_shape_pow(is_dyn):
    print("Starting the test.................")
    sizes = [[340695, 80],
             [340658, 80],
             [340688, 80],
             [340658, 80],
             [340663, 80]]

    exponent = 2
    dev = torch.device("cpu")
    dtype = torch.float32
    op = torch.pow
    input_tensors = []
    for s in sizes:
        input_tensors.append(torch.rand(s, dtype=dtype))

    model = OpWrapperModule(op)
    model = torch.compile(model, backend=my_compiler, dynamic=is_dyn)
    model.to(dev)
    for s in input_tensors:
        s = s.to(dev)
        inputs = {"input":s, "exponent": exponent}
        result = model(inputs)

dyn_shape = os.getenv("DYNAMIC_SHAPE")
if dyn_shape is not None and dyn_shape == "0":
    test_dynamic_shape_pow(False)
else:
    test_dynamic_shape_pow(True)
```

**To Execute:**

- Add Above code into a file test_pow.py

- To Execute in Dynamic shape
$ DYNAMIC_SHAPE=1 python test_pow.py
- To check same in static shape 
$ DYNAMIC_SHAPE=0 python test_pow.py

**Traceback for the issue:**
```
Traceback (most recent call last):
  File "test_pow.py", line 48, in <module>
    test_dynamic_shape_pow(True)
  File "test_pow.py", line 42, in test_dynamic_shape_pow
    result = model(inputs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 347, in _fn
    return fn(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 509, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 633, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 380, in _convert_frame_assert
    return _compile(
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 561, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 197, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 483, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 449, in transform
    tracer.run()
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2089, in run
    super().run()
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 739, in run
    and self.step()
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 702, in step
    getattr(self, inst.opname)(inst)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 403, in wrapper
    return inner_fn(self, inst)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1170, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 731, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1224, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1311, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1395, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1356, in get_fake_value
    return wrap_fake_exception(
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 931, in wrap_fake_exception
    return fn()
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1357, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1436, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1417, in run_node
    return node.target(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1299, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1505, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 229, in _fn
    result = fn(*args, **kwargs)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 132, in _fn
    result = fn(**bound.arguments)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_refs/__init__.py", line 1029, in _ref
    output = prim(a, b)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/_refs/__init__.py", line 1194, in pow
    elif b == 2.0:
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/__init__.py", line 352, in __bool__
    return self.node.bool_()
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1003, in bool_
    return self.guard_bool("", 0)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 985, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/home/vshekhawat/venv_Exp/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 3554, in evaluate_expr
    assert orig_expr == hint, f"{orig_expr} != {hint}"
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method pow of type object at 0x7f1c76ede6a0>(*(), **{'input': FakeTensor(..., size=(s0, s1)), 'exponent': s2}):
False != True
```

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20230914+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.21.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       12
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
Stepping:                        0
CPU MHz:                         2194.843
BogoMIPS:                        4389.68
Virtualization:                  VT-x
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        12 MiB
L3 cache:                        429 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX flush not necessary, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.2.0.dev20230914+cpu
[pip3] torchaudio==2.2.0.dev20230914+cpu
[pip3] torchvision==0.17.0.dev20230914+cpu
[conda] Could not collect

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by ZhaoqiongZ** [comment]
I found it is a regression issue only appears in recently nightly wheels.

**Comment by jon-chuang** [comment]
Hmm, I see, it seems we will fallback on python `pow` when we're not able to generate the right code.

Python `pow` requires kwargs base and exp, not input and exponent. It may suffice to simply map the kwargs during tracing.

**Comment by jon-chuang** [comment]
Hmm actually I think this is about converting the exponent to a symint/symfloat, and for some reason, the hint on whether the the exponent is 2 differs upon different evaluations of the symbool.

**Comment by isuruf** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/113683
