### ISSUE TITLE
Gradcheck errors when handling size-0 tensors as input for functions with inplace

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#109418]
### 🐛 Describe the bug

I was recently modifying the foreach tests to accept empty-tensors (tensors with size 0). `gradcheck` worked when none of the tensors were empty, but when I added in size-0 tensors as inputs to `_foreach_abs_`, I ran into the following stacktrace.

Code:
```
import torch
from torch import tensor

def fn(*x):
    torch._foreach_abs_(tuple(t.clone() for t in x))
    return x

x = (tensor([[ 6.3624, -3.1650]], device='cuda:0',
       dtype=torch.float64, requires_grad=True), tensor([], device='cuda:0', dtype=torch.float64), tensor([], device='cuda:0', dtype=torch.float64), tensor([[-6.9790, -1.8816],
        [ 8.3326, -7.5439]], device='cuda:0', dtype=torch.float64,
       requires_grad=True), tensor([], device='cuda:0', dtype=torch.float64))

torch.autograd.gradcheck(fn, x, fast_mode=True)
```

Output:
```
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/playground.py", line 13, in <module>
    torch.autograd.gradcheck(fn, x, fast_mode=True)
  File "/data/users/janeyx/pytorch/torch/autograd/gradcheck.py", line 2051, in gradcheck
    return _gradcheck_helper(**args)
  File "/data/users/janeyx/pytorch/torch/autograd/gradcheck.py", line 2080, in _gradcheck_helper
    _gradcheck_real_imag(
  File "/data/users/janeyx/pytorch/torch/autograd/gradcheck.py", line 1482, in _gradcheck_real_imag
    gradcheck_fn(
  File "/data/users/janeyx/pytorch/torch/autograd/gradcheck.py", line 1871, in _fast_gradcheck
    numerical_vJu = _get_numerical_vJu(
  File "/data/users/janeyx/pytorch/torch/autograd/gradcheck.py", line 687, in _get_numerical_vJu
    jacobian_scalars.append(_dot_with_type_promotion(v, Ju))
  File "/data/users/janeyx/pytorch/torch/autograd/gradcheck.py", line 1632, in _dot_with_type_promotion
    return (u * v).sum()
RuntimeError: The size of tensor a (4) must match the size of tensor b (0) at non-singleton dimension 0
```

### Versions

main

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @crcrpar @mcarilli

**Comment by soulitzer** [comment]
Looks like it is actually this issue https://github.com/pytorch/pytorch/issues/77230

**Comment by janeyx99** [comment]
Ah yea I forgot about the requires_grad--closing issue
