### ISSUE TITLE
[JIT] test_jit test_literal failure

### ISSUE THREAD

**Issue by csarofeen** [pytorch/pytorch#10958]
I'm getting the following error in test_jit on current master. Any recommended paths to debug?

```
======================================================================
ERROR: test_literal (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 2341, in test_literal
    self.checkScript(func3, (a.item(), b.item()), optimize=True)
  File "test_jit.py", line 2019, in checkScript
    self.checkScript(source, inputs, optimize, outputs, script.__name__, capture_output, frames_up=2)
  File "test_jit.py", line 2029, in checkScript
    outputs_ge = ge(*inputs)
RuntimeError: Unsupported value kind: Tuple

----------------------------------------------------------------------
Ran 1153 tests in 24.551s

FAILED (errors=1, skipped=34, expected failures=4)
Traceback (most recent call last):
  File "run_test.py", line 363, in <module>
    main()
  File "run_test.py", line 355, in main
    raise RuntimeError(message)
RuntimeError: test_jit failed!
```

**Comment by zou3519** [comment]
How recent is your master? I just pulled, built, and ran that test and it runs okay.

**Comment by csarofeen** [comment]
Yeah, sorry Richard, trying again. Seems I may have still ended up with a slightly older build when I rebuilt. Trying again and will close if it doesn't repro again.

**Comment by zou3519** [comment]
I think you might have hit this bug: https://github.com/pytorch/pytorch/pull/10923 but I'm not sure because I wasn't around to see its symptoms

**Comment by csarofeen** [comment]
Yeah, looks like I could have gotten hung up on that one. Building now, will likely close soon.

**Comment by csarofeen** [comment]
Yes, that was it. Not sure how I got hung up on it. Sorry. Closing.
