### ISSUE TITLE
Mismatch between PyTorch and onnxruntime when converting TransformerEncoder to onnx

### ISSUE THREAD

**Issue by mohamedhassanmus** [pytorch/pytorch#109532]
### 🐛 Describe the bug

When I convert a model containing TransformerEncoder, I notice that the outputs I get in PyTorch and onnxruntimes are different.

```
import numpy as np
import torch
import torch.nn as nn
import onnxruntime as ort


def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        trans_enc_layer = nn.TransformerEncoderLayer(d_model=32,
                                                     nhead=4,
                                                     dim_feedforward=64)

        self.seqTransEncoder = nn.TransformerEncoder(trans_enc_layer,
                                                     num_layers=1)

    def forward(self, x):
        return self.seqTransEncoder(x)


model = Model()
x = torch.randn(1, 10, 32)
y = model(x)

output_file_name = 'transformer.onnx'
torch.onnx.export(
    model,
    x,
    output_file_name,
    training=torch.onnx.TrainingMode.EVAL,
    input_names=["x"]
)

ort_session = ort.InferenceSession(output_file_name)
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)
np.testing.assert_allclose(to_numpy(y), ort_outs[0], rtol=1e-03, atol=1e-05)

print("Exported model has been tested with ONNXRuntime, and the result looks good!")
```

```
Traceback (most recent call last):
  File "bug_report.py", line 42, in <module>
    np.testing.assert_allclose(to_numpy(y), ort_outs[0], rtol=1e-03, atol=1e-05)
  File "~\envs\env\lib\site-packages\numpy\testing\_private\utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "~\envs\env\lib\site-packages\numpy\testing\_private\utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 319 / 320 (99.7%)
Max absolute difference: 1.1437721
Max relative difference: 45.76775
 x: array([[[ 0.227045,  0.300791,  0.722459, -0.345092,  0.106575,
         -0.08109 , -0.068145,  0.055995,  0.719644,  0.447079,
          0.53789 ,  0.811626, -0.761432, -1.300061,  0.911857,...
 y: array([[[ 6.036972e-01,  4.368772e-01,  8.908376e-01, -4.936648e-01,
         -2.970741e-01, -1.328418e-01,  1.244037e-01, -1.749761e-01,
          5.460253e-01,  5.468819e-01,  1.692071e-01,  7.558677e-01,...
```

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Mar  1 2023, 18:30:21) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
Nvidia driver version: 532.09
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.9.4
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchmetrics==0.11.3
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.8.0              h09e9e62_11    conda-forge
[conda] mkl                       2021.4.0           haa95532_640  
[conda] mkl-service               2.4.0            py39h2bbff1b_0  
[conda] mkl_fft                   1.3.1            py39h277e83a_0  
[conda] mkl_random                1.2.2            py39hf11a4ad_0  
[conda] numpy                     1.23.5           py39h3b20f71_0  
[conda] numpy-base                1.23.5           py39h4da318b_0  
[conda] pytorch                   1.13.1          py3.9_cuda11.6_cudnn8_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-lightning         1.9.4              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.1                   pypi_0    pypi
[conda] torchmetrics              0.11.3             pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by mohamedhassanmus** [comment]
I was missing `model.eval()`
