### ISSUE TITLE
AsyncCompile loses useful exception backtrace in __get_result

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109610]
### 🐛 Describe the bug

Steps to reproduce:

1. Inject a synthetic failure in some code that is invoked solely from the generated wrapper py file. E.g.,

```
diff --git a/torch/_inductor/triton_heuristics.py b/torch/_inductor/triton_heuristics.py
index badacf0d2a4..7364a5b8909 100644
--- a/torch/_inductor/triton_heuristics.py
+++ b/torch/_inductor/triton_heuristics.py
@@ -961,6 +961,7 @@ def pointwise(size_hints, meta, tile_hint=None, filename=None):
 def reduction(size_hints, reduction_hint=False, meta=None, filename=None):
     """args to @triton.heuristics()"""
     assert meta is not None
+    assert False
     rnumel = size_hints[-1]
     if len(size_hints) == 2:
         contiguous_config = triton_config_reduction(
```

2. Trigger this codepath in a test program

```
import torch

@torch.compile(dynamic=True)
def f(x):
    return (x + 1).sum()

f(torch.randn(20000, device='cuda'))
```

Here's the backtrace you get:

```
  File "/tmp/torchinductor_ezyang/ww/cwwnfs543wa53bsz7p6na72nsllphuso5hdekryzodahas6hcwlu.py", line 112, in <module>
    async_compile.wait(globals())
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codecache.py", line 1858, in wait
    scope[key] = result.result()
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codecache.py", line 1705, in result
    self.future.result()
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: 
```

This is useless, we lost the stack trace associated with the exception in the other process.

In small scale cases, you can recover useful information with `TORCHINDUCTOR_COMPILE_THREADS=1 python n.py`

```
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codecache.py", line 1415, in load
    mod = PyCodeCache.load(source_code)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codecache.py", line 1281, in load
    return cls.load_by_key_path(key, path, linemap)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codecache.py", line 1303, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_ezyang/i3/ci3j5qcext3jp3rjk5l45e5smehavbnh4cs36yj7zxe5th7tg2gx.py", line 10, in <module>
    @reduction(
  File "/data/users/ezyang/a/pytorch/torch/_inductor/triton_heuristics.py", line 964, in reduction
    assert False
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: 
```

which is a nice workaround, but we should just fix this properly.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by ezyang** [comment]
cc @zdevito @bertmaher

**Comment by ezyang** [comment]
maybe @eellison too?

**Comment by zdevito** [comment]
Multiprocessing normally reports exceptions like this when you run a simple example separately:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/scratch/zdevito/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/raid/zdevito/pytorch/ptest.py", line 4, in f
    assert False
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid/zdevito/pytorch/ptest.py", line 9, in <module>
    print(p.apply(f, (3,)))
  File "/scratch/zdevito/miniconda3/lib/python3.9/multiprocessing/pool.py", line 357, in apply
    return self.apply_async(func, args, kwds).get()
  File "/scratch/zdevito/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AssertionError
```

I think the exception handling logic related to raising `torch._dynamo.exc.BackendCompilerFailed` must be dropping the `The above exception was the direct cause of the following exception:` part.

**Comment by ezyang** [comment]
I confirmed that printing the exception right when it is raised gives the correct result, so it's getting munged somewhere along the way.

**Comment by ezyang** [comment]
Looks like augment_exc_message is clobbering the original trace. You have a concurrent.futures.process._RemoteTraceback so we probably just have to add special handling for it.

**Comment by ezyang** [comment]
As well as the BackendCompilerFailed wrapping

**Comment by ezyang** [comment]
This patch is enough to get the original stack trace preserved all the way through https://gist.github.com/ezyang/a0b5368bbbf03b64c9afee1ff8c94482

but it's very delicate, somehow it's very easy to accidentally decay the rpc failure into a plain AssertionError which is puzzling to me.

**Comment by ryp1992** [comment]
@ezyang I would like to work on this issue.

**Comment by ezyang** [comment]
Ok, please finish root causing, and then open a PR with a proposed fix

**Comment by ezyang** [comment]
This is still a problem.

Updated error injection patch

```
diff --git a/torch/_inductor/triton_heuristics.py b/torch/_inductor/triton_heuristics.py
index 35e3ac1e313..8f4a2fb4a15 100644
--- a/torch/_inductor/triton_heuristics.py
+++ b/torch/_inductor/triton_heuristics.py
@@ -1320,6 +1320,7 @@ def reduction(
         size_hints = [1, *size_hints[1:]]
 
     assert triton_meta is not None
+    assert False
     rnumel = size_hints[-1]
     if len(size_hints) != 2:
         raise NotImplementedError(f"size_hints: {size_hints}")
```

gives

```
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codecache.py", line 2188, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_ezyang/ep/cepfrhajld33uhlge64pfj2pu5pwu4luh2zs2tpsczloafsmznge.py", line 126, in <module>
    async_compile.wait(globals())
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codecache.py", line 2743, in wait
    scope[key] = result.result()
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codecache.py", line 2550, in result
    self.future.result()
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: 

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

**Comment by masnesral** [comment]
I'll look into making this work with the new subprocess pool implementation

**Comment by masnesral** [comment]
https://github.com/pytorch/pytorch/pull/128775

**Comment by zhxchen17** [comment]
Closing this since https://github.com/pytorch/pytorch/pull/128775 seems to be landed already. Feel free to re-open if we need more work here.
