### ISSUE TITLE
Tensor indexing error when using 'mps'

### ISSUE THREAD

**Issue by plannaAlain** [pytorch/pytorch#109716]
We are training a DETR model using transformers and it works well on any machine with a GPU+CUDA. Running it on a Mac only works if we use the "cpu" accelerator. With 'mps' it throws an error (see full stack below):
ValueError: boxes1 must be in [x0, y0, x1, y1] (corner) format, but got tensor([], device='mps:0', size=(0, 4))

Using Lightning v2.0.9 on a MacBook Pro M2 Max 64GB - Bug was first report to PyTorch Lightning but the team suggested that it was a PyTorch issue.

```python
trainer = Trainer(gradient_clip_val=0.1, max_epochs=300, callbacks=[early_stop_callback],accelerator="mps")
  trainer.fit(model)
```

```
Traceback (most recent call last):
  File "/Users/user/dev/project/company/server/ai/od_detr/training/train.py", line 235, in <module>
    trainer.fit(model)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 376, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 393, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/Users/user/dev/project/company/server/ai/od_detr/training/train.py", line 131, in validation_step
    loss, loss_dict = self.common_step(batch, batch_idx)
  File "/Users/user/dev/project/company/server/ai/od_detr/training/train.py", line 113, in common_step
    outputs = self.model(pixel_values=pixel_values, pixel_mask=pixel_mask, labels=labels)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/transformers/models/detr/modeling_detr.py", line 1625, in forward
    loss_dict = criterion(outputs_loss, labels)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/transformers/models/detr/modeling_detr.py", line 2238, in forward
    losses.update(self.get_loss(loss, outputs, targets, indices, num_boxes))
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/transformers/models/detr/modeling_detr.py", line 2208, in get_loss
    return loss_map[loss](outputs, targets, indices, num_boxes)
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/transformers/models/detr/modeling_detr.py", line 2149, in loss_boxes
    generalized_box_iou(center_to_corners_format(source_boxes), center_to_corners_format(target_boxes))
  File "/Users/user/dev/miniconda3/envs/pytorch2/lib/python3.10/site-packages/transformers/models/detr/modeling_detr.py", line 2410, in generalized_box_iou
    raise ValueError(f"boxes1 must be in [x0, y0, x1, y1] (corner) format, but got {boxes1}")
ValueError: boxes1 must be in [x0, y0, x1, y1] (corner) format, but got tensor([], device='mps:0', size=(0, 4))
```

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.5.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] pytorch-lightning==2.0.9
[pip3] torch==2.0.1
[pip3] torchmetrics==1.1.2
[pip3] torchvision==0.15.2
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] pytorch-lightning         2.0.9                    pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchmetrics              1.1.2                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Can you please try latest torch nightly? Also, it would really help if you(or someone else) can provide a smaller repro example, where MPS backend does not return what is expected

**Comment by plannaAlain** [comment]
Installing torch-2.2.0.dev20230920 torchaudio-2.2.0.dev20230920 torchvision-0.17.0.dev20230920 seems to have fixed the issue. Thank you @malfet
