### ISSUE TITLE
Error occurs when using focal loss in DaFormer

### ISSUE THREAD

**Issue by zszBZ** [pytorch/pytorch#109867]
### 🐛 Describe the bug

Error encountered when replacing the cross-entropy loss function with focal loss in DaFormer.
Traceback (most recent call last):
  File "run_experiments.py", line 106, in <module>
    train.main([config_files[i]])
  File "D:\code\DAFormer-master\tools\train.py", line 166, in main
    train_segmentor(
  File "D:\code\DAFormer-master\mmseg\apis\train.py", line 131, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "D:\Anaconda3\envs\test\lib\site-packages\mmcv\runner\iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\Anaconda3\envs\test\lib\site-packages\mmcv\runner\iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "D:\Anaconda3\envs\test\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "D:\code\DAFormer-master\mmseg\models\uda\dacs.py", line 145, in train_step
    log_vars = self(**data_batch)
  File "D:\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\test\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "D:\code\DAFormer-master\mmseg\models\segmentors\base.py", line 109, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "D:\code\DAFormer-master\mmseg\models\uda\dacs.py", line 306, in forward_train
    mix_losses = self.get_model().forward_train(
  File "D:\code\DAFormer-master\mmseg\models\segmentors\encoder_decoder.py", line 160, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "D:\code\DAFormer-master\mmseg\models\segmentors\encoder_decoder.py", line 92, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "D:\code\DAFormer-master\mmseg\models\decode_heads\decode_head.py", line 194, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg, seg_weight)
  File "D:\Anaconda3\envs\test\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "D:\code\DAFormer-master\mmseg\models\decode_heads\decode_head.py", line 233, in losses
    loss['loss_seg'] = self.loss_decode(
  File "D:\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\code\DAFormer-master\mmseg\models\losses\focal_loss.py", line 299, in forward
    loss_cls = self.loss_weight * calculate_loss_func(
  File "D:\code\DAFormer-master\mmseg\models\losses\focal_loss.py", line 126, in sigmoid_focal_loss
    assert weight.dim() == loss.dim()
AssertionError

### Versions

mmcv1.4.0
cuda1.11.0

**Comment by cpuhrsch** [comment]
Thank you for opening this issue @zszBZ - please kindly redirect this to the authors of DAFormer. Thank you.
