### ISSUE TITLE
basic_gnn_gcn: ERROR:common:TypeError: object of type 'GreaterThan' has no len()

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#109884]
Repro:
```
python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda  --export-aot-inductor  --only basic_gnn_gcn
```
Error:
```
ERROR:common:TypeError: object of type 'GreaterThan' has no len()
  target: aten.scalar_tensor.default
  args[0]: i18 >= 0
Traceback (most recent call last):
  File "/home/binbao/pytorch/benchmarks/dynamo/common.py", line 2107, in check_accuracy
    optimized_model_iter_fn = optimize_ctx(self.run_n_iterations)
  File "/home/binbao/pytorch/benchmarks/dynamo/common.py", line 1159, in export_aot_inductor
    module, exported, output_spec = AOTInductorModelCache.load(
  File "/home/binbao/pytorch/benchmarks/dynamo/common.py", line 1132, in load
    so_path, exported = torch._export.aot_compile(
  File "/home/binbao/pytorch/torch/_export/__init__.py", line 775, in aot_compile
    so_path = torch._inductor.aot_compile(unlifted_module, flat_example_inputs, options)  # type: ignore[arg-type]
  File "/home/binbao/pytorch/torch/_inductor/__init__.py", line 48, in aot_compile
    result = compile_fx_aot(
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 850, in compile_fx_aot
    return compile_fx(
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 951, in compile_fx
    return compile_fx(
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 980, in compile_fx
    return compile_fx(
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 1154, in compile_fx
    return inference_compiler(model_, example_inputs_)
  File "/home/binbao/pytorch/torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 1096, in fw_compiler_base
    return inner_compile(
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 211, in wrapper
    compiled = inner_compile(
  File "/home/binbao/local/miniconda3/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/binbao/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/binbao/pytorch/torch/_inductor/debug.py", line 297, in inner
    return fn(*args, **kwargs)
  File "/home/binbao/local/miniconda3/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 340, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "/home/binbao/pytorch/torch/_inductor/compile_fx.py", line 535, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/home/binbao/pytorch/torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 464, in run
    return super().run(*args)
  File "/home/binbao/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 735, in run_node
    result = super().run_node(n)
  File "/home/binbao/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 625, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 622, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/binbao/pytorch/torch/_inductor/lowering.py", line 278, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/home/binbao/pytorch/torch/_inductor/lowering.py", line 2219, in tensor
    elif len(data) == 0 or isinstance(data[0], (float, int)) and len(data) <= 8:
torch._inductor.exc.LoweringException: TypeError: object of type 'GreaterThan' has no len()
  target: aten.scalar_tensor.default
  args[0]: i18 >= 0
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @tugsbayasgalan

**Comment by ezyang** [comment]
@jansel There is a philosophical question we need to answer here. In https://docs.google.com/document/d/1INSCdYu1PxXcr43HrD82OudeEuS-qxQe1yZmLg2wy6A/edit#heading=h.aytveihghlgn we resolved that we wouldn't teach inductor how to codegen float intermediates.

Here, the problem is codegen bool intermediates. This seems... reasonable for Inductor to do. Do we agree it's fine to build this support?

**Comment by jansel** [comment]
How are the bools being used in this use case?  What is the consumer in the graph?  Do we have a usecase where the bools are being used in indexing?

**Comment by ezyang** [comment]
They're being sent to a runtime assert, nothing fancy otherwise.

**Comment by jansel** [comment]
I see, seems fine then.

**Comment by zhxchen17** [comment]
Hi @ezyang I'm cleaning up the old issues and wondering if this issue has been addressed?

**Comment by ezyang** [comment]
The repro still fails, but differently

```
  File "/data/users/ezyang/b/pytorch/torch/fx/interpreter.py", line 146, in run                                                    
    self.env[node] = self.run_node(node)           
  File "/data/users/ezyang/b/pytorch/torch/_inductor/ir.py", line 6538, in run_node                                                
    return super().run_node(n)                                                                                                     
  File "/data/users/ezyang/b/pytorch/torch/fx/interpreter.py", line 203, in run_node                                               
    return getattr(self, n.op)(n.target, args, kwargs)                                                                             
  File "/data/users/ezyang/b/pytorch/torch/fx/interpreter.py", line 297, in call_method                                            
    return getattr(self_obj, target)(*args_tail, **kwargs)                                                                         
  File "/data/users/ezyang/b/pytorch/torch/_inductor/sizevars.py", line 840, in load       
    return self._inner.load(name, self._simplify(index))         
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/common.py", line 1875, in load                                        
    out = self.load(name, index)                                 
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/triton.py", line 1672, in load                                        
    indexing = self.indexing(index, block_ptr=True)              
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/triton.py", line 1255, in indexing                                    
    index = self.prepare_indexing(index)                                                                                           
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/simd.py", line 670, in prepare_indexing
    index = self.simplify_indexing(index)                                                                                          
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/simd.py", line 344, in simplify_indexing     
    index = self.combine_contiguous_dims(index, tree)                                                                              
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/simd.py", line 460, in combine_contiguous_dims                        
    return self._combine_contiguous_dims(index, tree)                                                                              
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/simd.py", line 468, in _combine_contiguous_dims
    index_vars, sizes = tree.vars_and_sizes(index)                                                                                 
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/simd.py", line 203, in vars_and_sizes
    nodes.sort(key=lambda x: V.graph.sizevars.size_hint(x.divisor))                                                                
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/simd.py", line 203, in <lambda>       
    nodes.sort(key=lambda x: V.graph.sizevars.size_hint(x.divisor))                                                                
  File "/data/users/ezyang/b/pytorch/torch/_inductor/sizevars.py", line 501, in size_hint                        
    return int(out)                                                                                                                
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/site-packages/sympy/core/expr.py", line 320, in __int__
    raise TypeError("Cannot convert symbols to int")                                                                               
TypeError: Cannot convert symbols to int                                                                                           
TorchDynamo optimized model failed to run because of following error                                                               
fail_to_run                                                      
```
