### ISSUE TITLE
Simple script segfaulting when grad is enabled

### ISSUE THREAD

**Issue by tringwald** [pytorch/pytorch#109948]
### 🐛 Describe the bug

I was just toying around a bit with `torch` and came across this strange bug:

```python
import torch
print(torch.__version__)

FEATURE_SIZE = 768
BATCH_SIZE = 512
NUM_ITERS = 171
has_grad = True

with torch.set_grad_enabled(has_grad):
    torch.random.manual_seed(0)
    linear_layer = torch.nn.Linear(FEATURE_SIZE, FEATURE_SIZE, bias=True)
    input_tensor = torch.randn(BATCH_SIZE, FEATURE_SIZE)
    output = torch.zeros_like(input_tensor)

    for iter_num in range(NUM_ITERS):
        print(f"\rForward pass {iter_num}", end='')
        for batch_idx in range(BATCH_SIZE):
            output[batch_idx] = linear_layer(input_tensor[batch_idx])
```

This results in the following output on `torch==2.0.1`:
```
2.0.1
Forward pass 170[1]    59045 segmentation fault (core dumped)  python3 test.py
```
and also on recent nightly builds
```
2.2.0.dev20230912+cu121
Forward pass 170[1]    59424 segmentation fault (core dumped)  python3 test.py
```

In both cases, the script runs until after the last forward pass and then segfaults. On my setup, this happens for `NUM_ITERS>=171`. With `NUM_ITERS=170`, everything works fine. Similarly, setting `has_grad=False` also prevents the segfault.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2

**Comment by albanD** [comment]
Ho this is very weird, my best guess is that you create an autograd graph so big that our smart way to destroy Nodes to avoid stackoverlow gets tripped. Here is the stack trace:

```c++
#0  0x00007ffff7d7f53c in _int_free () from /lib64/libc.so.6
#1  0x00007ffff7d82393 in free () from /lib64/libc.so.6
#2  0x00007fffe517c2c7 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#3  0x00007fffe51834c4 in torch::autograd::generated::SelectBackward0::~SelectBackward0() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#4  0x00007fffe5ba3f04 in torch::autograd::deleteNode(torch::autograd::Node*) ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#5  0x00007fffe54a2cce in std::_Sp_counted_deleter<torch::autograd::generated::SelectBackward0*, void (*)(torch::autograd::Node*), std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#6  0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#7  0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#8  0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#9  0x00007fffe5bb49de in torch::autograd::CopySlices::~CopySlices() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#10 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#11 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#12 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#13 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#14 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#15 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#16 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#17 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#18 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#19 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#20 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#21 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#22 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#23 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#24 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#25 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#26 0x00007fffe2be998a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() ()
   from /home/albandes/local/pytorch/3.11_debug_source/torch/lib/libtorch_cpu.so
#27 0x00007fffe517c2a6 in torch::autograd::Node::~Node() ()
```

**Comment by soulitzer** [comment]
With the repro script as-is, it's happening during Python finalization before program exists, but you can also trigger it to happen manually by deleting the output keeping the graph alive. 

Was able to repro on x86 dev server, but not M1 mac.
