### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by grpinto** [pytorch/pytorch#110074]
### 🐛 Describe the bug

For you to have the full scope of the bug :

reipig1@varntvar:~/Documents/binedge$ python mmdeploy/tools/deploy.py     mmdeploy/configs/mmpose/pose-detection_onnxruntime_static.py     mmpose/configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/cspnext-m_udp_8xb64-210e_coco-wholebody-256x192.py     cspnext-m_udp-coco-wholebody_pt-in1k_210e-256x192-320fa258_20230123.pth    mmpose/tests/data/coco/000000000785.jpg    --work-dir mmdeploy_model/cpsnext_optimized     --device cpu     --dump-info
Traceback (most recent call last):
  File "/m/home/home3/34/reipig1/data/Documents/binedge/mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "/m/home/home3/34/reipig1/data/Documents/binedge/mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/backend/sdk/export_info.py", line 267, in get_deploy
    _, customs = get_model_name_customs(
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/codebase/__init__.py", line 37, in import_codebase
    codebase.register_all_modules()
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 133, in register_all_modules
    cls.register_deploy_modules()
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 123, in register_deploy_modules
    import mmdeploy.codebase.mmdet.models
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/codebase/mmdet/models/__init__.py", line 3, in <module>
    from . import dense_heads  # noqa: F401,F403
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/codebase/mmdet/models/dense_heads/__init__.py", line 2, in <module>
    from . import base_dense_head  # noqa: F401,F403
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py", line 5, in <module>
    from mmdet.models.dense_heads import PAAHead
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..layers import CSPLayer
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdet/models/layers/__init__.py", line 3, in <module>
    from .bbox_nms import fast_nms, multiclass_nms
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/site-packages/mmdet/models/layers/bbox_nms.py", line 5, in <module>
    from mmcv.ops.nms import batched_nms
  File "/u/34/reipig1/unix/.local/lib/python3.10/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/u/34/reipig1/unix/.local/lib/python3.10/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/u/34/reipig1/unix/.local/lib/python3.10/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/u/34/reipig1/unix/.conda/envs/mmdeploy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

### Versions

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21709  100 21709    0     0  67116      0 --:--:-- --:--:-- --:--:-- 67003

mmdeploy) reipig1@varntvar:~/Documents/binedge$ python3 collect_env.py
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 9.0.176
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        4
CPU max MHz:                     3900.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        6 MiB (6 instances)
L3 cache:                        8.3 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.25.2          py310hb5e798b_0  
[conda] pytorch                   2.0.0              py3.10_cpu_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                2.0.0                 py310_cpu    pytorch
[conda] torchvision               0.15.0                py310_cpu    pytorch

**Comment by tringwald** [comment]
```
CUDA used to build PyTorch: Could not collect
Is CUDA available: False
CUDA runtime version: 9.0.176
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
```

Given these lines in the `collect_env` output, there is probably an error in your CUDA and/or GPU setup. Can you try reinstalling a CUDA-enabled `torch` version?

**Comment by Geremia** [comment]
I got this issue, too, after building PyTorch 2.3.1 with GCC 13.2 for nvcc, GCC 14.1.0 for everything else, CUDA 12.4.0, and applying [this `boxing.h` patch](https://github.com/pytorch/pytorch/issues/122169#issuecomment-2146155541):
```
$ python
Python 3.11.9 (main, Apr  2 2024, 13:43:44) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/torch/__init__.py", line 239, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libc10.so: cannot open shared object file: No such file or directory
```
