### ISSUE TITLE
ValueError: args contained 2 None's after flattening. When exporting a ScriptModule or ScriptFunction, no args may be None because that breaks type propagation.

### ISSUE THREAD

**Issue by onefish51** [pytorch/pytorch#110154]
### 🐛 Describe the bug

when I export model to ONNX I found the error `RuntimeError: ScalarType UNKNOWN_SCALAR is an unexpected tensor scalar type`.
then I debug 1 line to 1 line , I found `torch.nn.MultiheadAttention` thrown it !

I pick a small unit to debug it 
```python
import torch
from torch import Tensor, nn
d_model = 256
dropout = 0.0
n_heads = 8
model = nn.MultiheadAttention(d_model, n_heads, dropout=dropout) 

tgt = torch.randn(6, 1, 256, dtype=torch.float32)
q = torch.randn(6, 1, 256, dtype=torch.float32)
k = torch.randn(6, 1, 256, dtype=torch.float32)

args = (
    tgt, q, k
)

scripted_model = torch.jit.script(model)
scripted_model.save("model.pt")
torch.onnx.export(model=scripted_model, args=args, f="model.onnx", verbose=True,opset_version=17)
```
then an error thrown 
```sh
=========== Diagnostic Run torch.onnx.export version 2.1.0a0+b5021ba ===========
verbose: False, log level: 40
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "script_save_export_onnx.py", line 331, in <module>
    torch.onnx.export(model=scripted_model, args=args, f="model.onnx", verbose=True,opset_version=17)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 507, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1567, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1124, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 968, in _create_jit_graph
    _check_flatten_did_not_remove(args, flattened_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 956, in _check_flatten_did_not_remove
    raise ValueError(
ValueError: args contained 2 None's after flattening. When exporting a ScriptModule or ScriptFunction, no args may be None because that breaks type propagation.
```

### Versions

docker pull nvcr.io/nvidia/pytorch:23.07-py3

**Comment by umair0606** [comment]
Facing the same issue. Any solution?
