### ISSUE TITLE
`torch.nested.nested_tensor` does not work within multiprocess `DataLoader`

### ISSUE THREAD

**Issue by rusty1s** [pytorch/pytorch#110161]
### 🐛 Describe the bug

`torch.nested.nested_tensor` does not work in combination with `DataLoader(num_workers > 0)`. Here is a minimal reproducible example:
```python
import torch

dataset = [torch.nested.nested_tensor([torch.randn(5)]) for _ in range(100)]

loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=1,
    num_workers=4,
    collate_fn=lambda x: x,
)

for data in loader:
    print(data)
```
Error message:
```
Traceback (most recent call last):
  File "/home/matthias/miniconda3/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/matthias/miniconda3/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/matthias/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 284, in reduce_tensor
    metadata = (tensor.storage_offset(), tensor.size(), tensor.stride(), tensor.requires_grad)
RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
```

### Versions

PyTorch 2.0

cc @ezyang @gchanan @zou3519 @kadeng @cpuhrsch @jbschlosser @bhosmer @drisspg

**Comment by cpuhrsch** [comment]
Hi @rusty1s, unfortunately this is currently not supported, but we are working on it in https://github.com/pytorch/pytorch/pull/102445 . We'll prioritize landing this sooner.
