### ISSUE TITLE
PyTorch with non-shared build (building a single shared lib) is unsupported

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#110238]
### 🐛 Describe the bug

Building with `BUILD_SHARED_LIBS=0` to produce a single `libtorch.so` appears to be broken when using Python/torch rather than C++/libtorch.

Full build command:
```
BUILD_SHARED_LIBS=0 TORCH_CUDA_ARCH_LIST="9.0" CUDA_HOME="/usr/local/cuda"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" USE_SYSTEM_NCCL=1 USE_MAGMA=1 USE_OPENCV=1 BUILD_CAFFE2=0 BUILD_CAFFE2_OPS=0 BUILD_TEST=0 USE_CUSPARSELT=1 USE_FBGEMM=0 USE_KINETO=0 USE_METAL=0 USE_NATIVE_ARCH=1 USE_NNPACK=0 USE_QNNPACK=0 USE_VALGRIND=0 USE_XNNPACK=0 USE_ITT=0 USE_C10D_UCC=0 USE_GLOO=0 USE_C10D_MPI=0 ONNX_ML=0 USE_TENSORPIPE=0 BUILD_NVFUSER=0 BUILD_FUNCTORCH=1 BUILD_SPLIT_CUDA=0 python3 setup.py develop
```

The following output is observed:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/pytorch/torch/__init__.py", line 235, in <module>
    _load_global_deps()
  File "/workspace/pytorch/torch/__init__.py", line 194, in _load_global_deps
    raise err
  File "/workspace/pytorch/torch/__init__.py", line 175, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /workspace/pytorch/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
```
Running with ` TORCH_USE_RTLD_GLOBAL=1` to bypass the above failure seems to indicate that something is being loaded twice:
```
>>> import torch
terminate called after throwing an instance of 'c10::Error'
  what():  Tried to register multiple backend fallbacks for the same dispatch key Conjugate; previous registration registered at /workspace/pytorch/aten/src/ATen/ConjugateFallback.cpp:17, new registration registered at /workspace/pytorch/aten/src/ATen/ConjugateFallback.cpp:17
Exception raised from registerFallback at /workspace/pytorch/aten/src/ATen/core/dispatch/Dispatcher.cpp:401 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0xfffe1caf24d8 in /workspace/pytorch/torch/lib/libshm.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf8 (0xfffe16cbdd28 in /workspace/pytorch/torch/lib/libshm.so)
frame #2: c10::Dispatcher::registerFallback(c10::DispatchKey, c10::KernelFunction, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x558 (0xfffe27e16a88 in /workspace/pytorch/torch/lib/libtorch_python.so)
frame #3: torch::Library::_fallback(torch::CppFunction&&) & + 0x1c4 (0xfffe27e53e54 in /workspace/pytorch/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x21b8790 (0xfffe27bd8790 in /workspace/pytorch/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x21bc00c (0xfffe27bdc00c in /workspace/pytorch/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x16824d4 (0xfffe270a24d4 in /workspace/pytorch/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x5624 (0xfffe37405624 in /lib/ld-linux-aarch64.so.1)
frame #8: <unknown function> + 0x572c (0xfffe3740572c in /lib/ld-linux-aarch64.so.1)
frame #9: _dl_catch_exception + 0xd0 (0xfffe3722d1f0 in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #10: <unknown function> + 0xbf5c (0xfffe3740bf5c in /lib/ld-linux-aarch64.so.1)
frame #11: _dl_catch_exception + 0x78 (0xfffe3722d198 in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #12: <unknown function> + 0xc2fc (0xfffe3740c2fc in /lib/ld-linux-aarch64.so.1)
frame #13: <unknown function> + 0x796e4 (0xfffe371796e4 in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #14: _dl_catch_exception + 0x78 (0xfffe3722d198 in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #15: _dl_catch_error + 0x40 (0xfffe3722d260 in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #16: <unknown function> + 0x791c0 (0xfffe371791c0 in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #17: dlopen + 0x54 (0xfffe37179784 in /usr/lib/aarch64-linux-gnu/libc.so.6)
<omitting python frames>

Aborted (core dumped)
```

### Versions

(upstream source build)
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.5
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.2.0-1008-nvidia-64k-aarch64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA Graphics Device
Nvidia driver version: 535.115
```

**Comment by malfet** [comment]
I've noticed that torch_python started to depend on cublas, which it shouldn't.
I suspect some of @cyyever build simplification changes sneaked it
in, and we've disabled CI for it a while back because statistically linked cudnn is 50% slower than dynamic one...

**Comment by cyyever** [comment]
Let me check the dependency of libtorch.so

**Comment by cyyever** [comment]
I wouldn't recommend building static libraries since the library dependency graph is so complicated that a static library may be linked twice at some point.

**Comment by cyyever** [comment]
@eqy @malfet 
The reason is that in static building torch_cpu.a is linked twice to torch_python.so, via a direct link and an indirect linking from shm.a.  
I tried to change 
```
add_library(shm SHARED core.cpp)
```
to 
```
add_library(shm OBJECT core.cpp)
```
in torch/lib/libshm/CMakeLists.txt in my host and it seemed work.
@eqy can you verify this solution on your env?

**Comment by cyyever** [comment]
@albanD pin

**Comment by cyyever** [comment]
A simple grep gave me other SHARED libraries:
```
~/pytorch ❯ grep add_library -r caffe2/ torch | grep SHA | grep -v Targets | uniq
caffe2/CMakeLists.txt:  add_library(caffe2_nvrtc SHARED ${ATen_NVRTC_STUB_SRCS})
caffe2/CMakeLists.txt:  add_library(torch_global_deps SHARED ${TORCH_SRC_DIR}/csrc/empty.c)
torch/lib/libshm_windows/CMakeLists.txt:add_library(shm SHARED core.cpp)
torch/CMakeLists.txt:add_library(torch_python SHARED ${TORCH_PYTHON_SRCS})
torch/CMakeLists.txt:  add_library(nnapi_backend SHARED
```

**Comment by eqy** [comment]
@cyyever I'm now seeing a segmentation fault when I build with the shm change.
```
Thread 1: status = VgTs_Runnable syscall 222 (lwpid 73604)
==73604==    at 0x401D78C: __mmap64 (mmap64.c:58)
==73604==    by 0x401D78C: mmap (mmap64.c:46)
==73604==    by 0x40079CB: _dl_map_segments (dl-map-segments.h:140)
==73604==    by 0x40079CB: _dl_map_object_from_fd (dl-load.c:1258)
==73604==    by 0x4008ACF: _dl_map_object (dl-load.c:2327)
==73604==    by 0x4002E6F: openaux (dl-deps.c:64)
==73604==    by 0x4ADD167: _dl_catch_exception (dl-error-skeleton.c:208)
==73604==    by 0x40033C3: _dl_map_object_deps (dl-deps.c:248)
==73604==    by 0x400C77B: dl_open_worker_begin (dl-open.c:592)
==73604==    by 0x4ADD167: _dl_catch_exception (dl-error-skeleton.c:208)
==73604==    by 0x400BEF7: dl_open_worker (dl-open.c:782)
==73604==    by 0x4ADD167: _dl_catch_exception (dl-error-skeleton.c:208)
==73604==    by 0x400C2FB: _dl_open (dl-open.c:883)
==73604==    by 0x4A296E3: dlopen_doit (dlopen.c:56)
==73604==    by 0x4ADD167: _dl_catch_exception (dl-error-skeleton.c:208)
==73604==    by 0x4ADD22F: _dl_catch_error (dl-error-skeleton.c:227)
==73604==    by 0x4A291BF: _dlerror_run (dlerror.c:138)
==73604==    by 0x4A29783: dlopen_implementation (dlopen.c:71)
==73604==    by 0x4A29783: dlopen@@GLIBC_2.34 (dlopen.c:81)
```
I'm also interested in whether the omission of `libc10.so` would fundamentally break cpp/CUDA extensions, as naively modifying my build to do that also seemed to have that effect.

**Comment by cyyever** [comment]
@eqy Did the segmentation fault happen in linking? Or which pytorch command you used to trigger segmentation fault?
