### ISSUE TITLE
ONNX export: TransformerEncoder is exported with fixed input dims

### ISSUE THREAD

**Issue by mush42** [pytorch/pytorch#110347]
## Issue description

When exporting to ONNX a module that contains `torch.nn.TransformerEncoder`, the time dimention is fixed to the one used during export, and the model fails to deal with arbitrary  sequence lengths.

## Code example

Given the following module:

```python
from torch import nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(15, 96)
        enc_layer = nn.TransformerEncoderLayer (
            96,
            nhead=12,
            dim_feedforward=96,
            dropout=0.2,
            batch_first=True
        )
        self.attn_layers = nn.TransformerEncoder(
            enc_layer,
            num_layers=10,
            enable_nested_tensor=True
        )

    def forward(self, x):
        x = self.emb(x)
        return self.attn_layers(x)
```

Exported as follows:

```python
import torch

model = Model()
torch.onnx.export(
    model,
    args=(torch.randint(0, 15, (1, 20))),
    f="model.onnx",
    opset_version=16,
    export_params=True,
    do_constant_folding=True,
    input_names=["input"],
    output_names=["output"],
    dynamic_axes={
        "input": {0: "batch_size", 1: "time"},
        "output": {0: "batch_size", 1: "time"},
    }
)
```

and ran using `onnxruntime` as follows:

```python
import numpy as np
import onnxruntime

sess = onnxruntime.InferenceSession("model.onnx")
input = np.expand_dims(
    np.array([1, 2, 3], dtype=np.int64),
    0
)
output = sess.run(None, {"input": input})
```

I get the following error:

```python
Traceback (most recent call last):
  File "D:\lab\issue_with_enc.py", line 49, in <module>
    output = sess.run(None, {"input": input})
  File "D:\lab\.env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/attn_layers/layers.0/self_attn/Reshape_4' Status Message: C:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{3,1,96}, requested shape:{20,12,8}
```

## System Info

PyTorch version: 2.2.0.dev20230930+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: 15.0.2
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce MX350
Nvidia driver version: 528.49
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2918
DeviceID=CPU0
Family=198
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2918
Name=11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-lightning==2.0.6
[pip3] torch==2.2.0.dev20230930+cpu
[pip3] torchmetrics==1.0.1
[conda] Could not collect

**Comment by justinchuby** [comment]
You may consider leveraging the new `torch.onnx.dynamo_export` API:

```python
from torch import nn
import torch

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(15, 96)
        enc_layer = nn.TransformerEncoderLayer(
            96,
            nhead=12,
            dim_feedforward=96,
            dropout=0.2,
            batch_first=True
        )
        self.attn_layers = nn.TransformerEncoder(
            enc_layer,
            num_layers=10,
            enable_nested_tensor=True
        )

    def forward(self, x):
        x = self.emb(x)
        return self.attn_layers(x)


model = Model()
exported = torch.onnx.dynamo_export(
    model,
    torch.randint(0, 15, (1, 20)),
    export_options=torch.onnx.ExportOptions(dynamic_shapes=True)
)

exported.save("model.onnx")

import numpy as np
import onnxruntime

session = onnxruntime.InferenceSession("model.onnx", providers=["CPUExecutionProvider"])
input = np.expand_dims(
    np.array([1, 2, 3], dtype=np.int64),
    0
)
output = session.run(None, {"arg0": input})
print(output)
```

yields

```
[array([[[ 1.21399295e+00,  1.38444471e+00, -5.43636143e-01,
         -1.77991104e+00, -1.95356593e-01, -9.76335853e-02,
         -4.22550678e-01,  7.16868877e-01,  2.84270346e-01,
          1.08840632e+00, -1.55732214e-01, -6.72121823e-01,
          3.64055812e-01, -4.92070049e-01,  7.84370840e-01,
         -2.28362661e-02, -1.40640736e+00,  2.74028730e+00,
         -5.18808961e-01,  1.07162334e-01, -1.31390595e+00,
         -9.94497478e-01,  2.10741878e-01,  1.30186176e+00,
         -2.74887115e-01, -2.27699232e+00, -1.17701781e+00,
         -1.38323558e-02,  4.56916720e-01, -4.08307105e-01,
         -2.11757272e-01, -7.31187463e-01,  2.46623591e-01,
          8.37743938e-01, -1.21710455e+00,  1.67774403e+00,
         -5.49871504e-01,  8.49874839e-02, -2.86200374e-01,
          1.84620547e+00, -2.27751803e+00,  1.09612644e-01,
          6.99855328e-01, -8.10806096e-01,  5.30902267e-01,
          4.00176555e-01, -2.44432974e+00, -1.31730959e-01,
         -3.27658564e-01,  1.16707122e+00, -8.46142411e-01,
          2.38981351e-01,  3.55096877e-01, -2.66753048e-01,
         -1.10646880e+00,  3.59914601e-01,  7.20209256e-02,
          4.22494739e-01, -5.33577919e-01, -2.43368149e+00,
         -1.74961179e-01,  4.15422857e-01, -2.24171877e+00,
          8.48777950e-01, -8.01087916e-01,  2.46128067e-01,
         -6.90762639e-01, -7.26504743e-01, -2.79240403e-02,
          1.37044716e+00,  1.31956649e+00,  9.33497921e-02,
         -1.05725539e+00, -4.81045485e-01,  1.05426109e+00,
          1.43116200e+00, -9.38845932e-01,  5.89742005e-01,
          2.52852857e-01,  8.25470626e-01, -9.17140186e-01,
         -2.18587413e-01,  2.06853271e+00, -5.00198662e-01,
          1.83234677e-01,  5.92714190e-01,  4.86470848e-01,
          9.62449685e-02,  3.15268546e-01,  9.13173795e-01,
          3.88722241e-01, -2.39324182e-01,  6.21587038e-01,
          1.54352856e+00,  1.73383653e+00, -1.13665652e+00],
        [ 5.37538052e-01,  6.21939540e-01, -3.74748200e-01,
         -1.62497187e+00, -1.38422239e+00, -3.13426584e-01,
          3.90530191e-02,  8.71694744e-01,  6.63171113e-01,
          8.26186359e-01,  1.84087306e-01, -1.02917790e+00,
         -1.70292258e-01,  7.29982704e-02,  7.51832843e-01,
          2.45825127e-01, -1.27195120e+00,  1.81108880e+00,
         -4.05169815e-01,  1.90837428e-01, -8.74544621e-01,
         -1.30086160e+00,  7.14660466e-01,  1.36543763e+00,
         -3.57697129e-01, -2.64727402e+00, -1.97560143e+00,
          2.85583705e-01,  1.22730052e+00, -5.83188057e-01,
         -1.91003889e-01,  2.08237931e-01, -6.10164523e-01,
          1.17310989e+00, -7.74519920e-01,  8.55120480e-01,
          2.60225475e-01,  5.24421036e-02, -9.33709741e-01,
          1.19138575e+00, -2.44111538e+00, -4.90838662e-02,
          1.87743902e-01, -6.72854185e-01,  1.09299719e+00,
          5.39477229e-01, -2.08721924e+00, -3.68605435e-01,
          1.23319656e-01,  1.92491770e+00, -1.20323825e+00,
          7.12585449e-01,  8.02384317e-01, -8.85081440e-02,
         -5.26021063e-01,  8.82159233e-01,  6.68144345e-01,
          1.25643814e+00,  3.52132410e-01, -1.93366671e+00,
          1.15693939e+00,  2.03483608e-02, -1.94552362e+00,
          8.07096660e-01, -4.08759892e-01, -1.36498347e-01,
         -8.13018918e-01, -1.21343446e+00,  2.79102862e-01,
          1.39726245e+00,  1.50838315e+00, -6.42502367e-01,
         -1.27554846e+00, -3.70866843e-02,  8.18291903e-01,
          1.45844960e+00, -5.30216098e-01,  1.15806186e+00,
         -4.29916471e-01,  1.35635778e-01, -3.96855921e-01,
         -1.00689018e+00,  2.46376872e+00, -2.01198548e-01,
         -1.23990603e-01,  5.66283822e-01, -3.05030048e-01,
         -2.71534085e-01, -2.81496078e-01,  6.72097921e-01,
         -2.19918758e-01,  4.09893990e-01,  9.11343217e-01,
         -7.91448280e-02,  1.50138867e+00, -1.44500458e+00],
        [ 6.44359708e-01,  4.17712778e-01, -2.75455773e-01,
         -1.64159298e+00, -1.25587392e+00, -6.88541904e-02,
         -5.37634850e-01,  3.21217120e-01,  7.68356085e-01,
          1.98523378e+00,  7.77917579e-02, -1.18563640e+00,
          3.13762933e-01, -5.71584642e-01,  1.29473424e+00,
         -1.81329511e-02, -9.13557649e-01,  7.89486110e-01,
          7.24622756e-02,  3.39565158e-01, -1.34012997e+00,
         -1.25555491e+00,  3.67542744e-01,  1.36888790e+00,
          1.39704511e-01, -2.43474007e+00, -2.11890984e+00,
          1.77325442e-01,  9.93192196e-01, -1.44155040e-01,
          1.99857607e-01, -4.92409877e-02, -1.17370009e+00,
          1.37646508e+00, -7.16143072e-01,  1.17239869e+00,
          1.52755871e-01, -7.21229315e-02, -1.39862046e-01,
          1.13472104e+00, -1.28332663e+00,  7.89487362e-01,
          5.57411790e-01, -6.76244348e-02,  2.15822235e-01,
          2.00726807e-01, -1.66515040e+00, -5.36117077e-01,
         -4.79210347e-01,  1.58349228e+00, -9.22065318e-01,
          9.89134014e-02,  3.99586618e-01, -4.07810956e-01,
          1.17471360e-01,  6.62163913e-01,  6.46903276e-01,
          1.59147871e+00, -6.57372534e-01, -3.09822822e+00,
          7.44529247e-01,  1.99384496e-01, -1.99612141e+00,
          1.60897386e+00, -3.07751536e-01,  7.79964477e-02,
         -5.66066623e-01, -1.71201849e+00,  4.75844383e-01,
          1.21306205e+00,  9.15312588e-01,  1.71443857e-02,
         -1.95723450e+00, -9.38703492e-02,  6.23189926e-01,
          1.06538832e+00, -9.30453479e-01,  1.64066446e+00,
          3.75522822e-01,  1.18385756e+00, -6.44321620e-01,
         -1.03307664e+00,  2.10218072e+00, -2.90619135e-01,
         -1.07988380e-01,  8.03580523e-01,  3.20163369e-01,
         -4.87183392e-01,  1.69888616e-03,  8.98579001e-01,
         -3.95092405e-02, -6.41770661e-02,  2.53530145e-01,
         -6.74743354e-02,  1.17472172e+00, -1.33866239e+00]]],
      dtype=float32)]
```

**Comment by justinchuby** [comment]
You may consider using the new `torch.onnx.dynamo_export` api:

```python
from torch import nn
import torch

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(15, 96)
        enc_layer = nn.TransformerEncoderLayer(
            96,
            nhead=12,
            dim_feedforward=96,
            dropout=0.2,
            batch_first=True
        )
        self.attn_layers = nn.TransformerEncoder(
            enc_layer,
            num_layers=10,
            enable_nested_tensor=True
        )

    def forward(self, x):
        x = self.emb(x)
        return self.attn_layers(x)


model = Model().eval()
# sample_input = torch.randint(0, 15, (1, 20))
sample_input = torch.tensor([[1, 2, 3]])
exported = torch.onnx.dynamo_export(
    model,
    sample_input,
    export_options=torch.onnx.ExportOptions(dynamic_shapes=True)
)

exported.save("model.onnx")
print("Exported")

import numpy as np
import onnxruntime

session = onnxruntime.InferenceSession("model.onnx", providers=["CPUExecutionProvider"])
input = np.array([[1, 2, 3]], dtype=np.int64)
# input = sample_input.numpy()
output = session.run(None, {"arg0": input})
torch_input = torch.tensor(input)
torch_output = model(torch_input)
torch.testing.assert_close(torch.tensor(output[0]), torch_output)
print(output)
```

**Comment by shubhambhokare1** [comment]
Hi @mush42 

We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
