### ISSUE TITLE
`torch.func.functionalize(f)(x) != f(x)`

### ISSUE THREAD

**Issue by samuela** [pytorch/pytorch#110337]
### 🐛 Describe the bug

`torch.func.functionalize(f)` silently returns incorrect results:
```py
def f(x):
  x.add_(1)
  x.mul_(2)
  return x

x = torch.Tensor([3])
print(f(x)) # => tensor([8.])
print(torch.func.functionalize(f)(x)) # => tensor([18.])
```

### Versions

```
❯ python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "/Users/sam.ainsworth/external-dev/torch2jax/collect_env.py", line 611, in <module>
    main()
  File "/Users/sam.ainsworth/external-dev/torch2jax/collect_env.py", line 594, in main
    output = get_pretty_env_info()
  File "/Users/sam.ainsworth/external-dev/torch2jax/collect_env.py", line 589, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/Users/sam.ainsworth/external-dev/torch2jax/collect_env.py", line 427, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/Users/sam.ainsworth/external-dev/torch2jax/collect_env.py", line 399, in get_pip_packages
    out = run_with_pip([sys.executable, '-mpip'])
  File "/Users/sam.ainsworth/external-dev/torch2jax/collect_env.py", line 384, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

I'm running pytorch 2.0.1 on aarch64-darwin

**Comment by samuela** [comment]
oops i'm a silly, `x` is mutated in the first call.
