### ISSUE TITLE
Using `torch.onnx.export` from file named `onnx.py` results in cryptic error message

### ISSUE THREAD

**Issue by tringwald** [pytorch/pytorch#110447]
### 🐛 Describe the bug

Right now, there's a massive footgun when using `torch.onnx.export()` from a file named `onnx.py`.

```python3
# File contents of onnx.py
import torch
import torch.nn as nn
torch.onnx.export(nn.Linear(10, 10), args=torch.ones(10), f='output.onnx')
```
This results in a few dozen lines of rather cryptic error messages:
```
Traceback (most recent call last):
  File "/path/to/project/onnx.py", line 3, in <module>
    torch.onnx.export(nn.Linear(10, 10), args=torch.ones(10), f='output.onnx')
  File "/path/to/python3.9/site-packages/torch/__init__.py", line 1868, in __getattr__
    return importlib.import_module(f".{name}", __name__)
  File "/path/to/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/path/to/python3.9/site-packages/torch/onnx/__init__.py", line 57, in <module>
    from ._internal.onnxruntime import (
  File "/path/to/python3.9/site-packages/torch/onnx/_internal/onnxruntime.py", line 38, in <module>
    import onnx
  File "/path/to/project/onnx.py", line 3, in <module>
    torch.onnx.export(nn.Linear(10, 10), args=torch.ones(10), f='output.onnx')
  File "/path/to/python3.9/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/path/to/python3.9/site-packages/torch/onnx/utils.py", line 1590, in _export
    with exporter_context(model, training, verbose):
  File "/path/to/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/path/to/python3.9/site-packages/torch/onnx/utils.py", line 179, in exporter_context
    with select_model_mode_for_export(
  File "/path/to/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/path/to/python3.9/site-packages/torch/onnx/utils.py", line 166, in setup_onnx_logging
    is_originally_enabled = torch.onnx.is_onnx_log_enabled()
AttributeError: partially initialized module 'torch.onnx' has no attribute 'is_onnx_log_enabled' (most likely due to a circular import)
```

When `torch` imports `onnx` [here](https://github.com/pytorch/pytorch/blob/main/torch/onnx/_internal/onnxruntime.py#L34), the local file seems to be preferred over the pip installed `onnx`. According to #98271, I'm not the first one to encounter this issue, so we should probably throw a more descriptive error.

### Versions

torch==2.2.0.dev20231002+cu118

**Comment by tringwald** [comment]
The problem is actually even worse when calling it from another file:

File `test_onnx.py`:
```python3
import torch
import torch.nn as nn
torch.onnx.export(nn.Linear(10, 10), args=torch.ones(10), f='output.onnx')
```
File `onnx.py`:
```python3
print("Hello World")
```

```
Hello World
Traceback (most recent call last):
  File "/path/to/project/test_onnx.py", line 3, in <module>
    torch.onnx.export(nn.Linear(10, 10), args=torch.ones(10), f='output.onnx')
  File "/path/to/python3.9/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/path/to/python3.9/site-packages/torch/onnx/utils.py", line 1687, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "/path/to/python3.9/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 230, in _add_onnxscript_fn
    model_proto = onnx.load_model_from_string(model_bytes)  # type: ignore[attr-defined]
AttributeError: module 'onnx' has no attribute 'load_model_from_string'
```

In this case, a user wouldn't even get the circular import clue  and probably has no idea what just happened.

**Comment by thiagocrepaldi** [comment]
This is how Python handles namespace during execution. There isn't much we can do to fix this
