### ISSUE TITLE
ValueError issued instead of TypeError when used with math.isfinite

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#110605]
### 🐛 Describe the bug

When using `math.isfinite` with a tensor a wrong `ValueError` is issued instead of a `TypeError`. This creates bugs (see #109819). Fixing this issue will fix the other one as well.

```python
>>> import math, torch
>>> a = torch.randn(5)
>>> math.isfinite(a)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 math.isfinite(a)

ValueError: only one element tensors can be converted to Python scalars

>>> math.isfinite(a.numpy())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 math.isfinite(a.numpy())

TypeError: only size-1 arrays can be converted to Python scalars
```

### Versions

`PyTorch version: 2.0.1`

**Comment by malfet** [comment]
Hmm, this is indeed weird:
```python
>>> x = torch.rand(2)
>>> float(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: only one element tensors can be converted to Python scalars
>>> x.item()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: a Tensor with 2 elements cannot be converted to Scalar
```

**Comment by malfet** [comment]
@rgommers do you know if numpy will keep raising TypeError in similar cases?

**Comment by rgommers** [comment]
The behavior for `numpy` hasn't changed for a long time, and I don't expect it to.

This is the state with some older versions:
```python
>>> import torch
>>> import numpy as np
>>> torch.__version__
'1.9.0'
>>> np.__version__
'1.24.3'
>>> x = np.ones(2)
>>> t = torch.ones(2)
>>> float(x)
TypeError: only size-1 arrays can be converted to Python scalars
>>> x.item()
ValueError: can only convert an array of size 1 to a Python scalar

>>> t = torch.ones(2)
>>> float(t)
ValueError: only one element tensors can be converted to Python scalars
>>> t.item()
ValueError: only one element tensors can be converted to Python scalars
```

`float(not_a_scalar)` should perhaps raise `TypeError`, but it's not 100% clear cut I'd say, given that the `Tensor` type does work - if it has exactly one element.

I'd suggest that in general it's best to pick a reasonable exception kind when you first implement it, and then not change it unless it's very clearly incorrect - because any change is likely to break as much as it fixes.

**Comment by Atcold** [comment]
Thanks, @malfet, for looking into this.
Although @rgommers suggests giving PyTorch some slack, it's indeed a bug.
