### ISSUE TITLE
[index_select] expand: attempting to expand a dimension of length 10!

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#110699]
### 🐛 Describe the bug

torch.compile fails when "out" tensor is provided for index_select operator, even though the shape of output tensor is correct.
Please use below piece of code to reproduce the issue:
```
import torch

def dummy_fn(op_inputs_dict):
    return torch.index_select(**op_inputs_dict)

if __name__ == "__main__":
    torch.manual_seed(10)
    op_inputs_dict = {
        "input": torch.randn([8, 16]),
        "dim": 0,
        "index": torch.tensor([2, 1, 6, 7, 3, 1, 7, 5, 6, 7]),
        "out": torch.empty([10,16]),
    }
    model = torch.compile(dummy_fn, backend="eager")
    res = model(op_inputs_dict)
    print(res)
```

### Error logs

```
/tmp/lib/python3.8/site-packages/torch/_meta_registrations.py:352: UserWarning: An output with one or more elements was resized since it had shape [10, 16], which does not match the required output shape [8, 16]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /npu-stack/pytorch-fork/aten/src/ATen/native/Resize.cpp:28.)
  torch._resize_output_(out, self.size(), self.device)
Traceback (most recent call last):
  File "index_selct.py", line 15, in <module>
    res = model(op_inputs_dict)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 729, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1274, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1376, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1541, in dispatch
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
  File "/tmp/lib/python3.8/site-packages/torch/_meta_registrations.py", line 353, in meta_index_select_out
    return out.copy_(torch.index_select(self, dim, index))
  File "/tmp/lib/python3.8/site-packages/torch/_meta_registrations.py", line 294, in meta_copy_
    aten.expand_copy.default(intermediate, self.size())
  File "/tmp/lib/python3.8/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
  File "/tmp/lib/python3.8/site-packages/torch/_refs/__init__.py", line 2847, in expand
    torch._check(
  File "/tmp/lib/python3.8/site-packages/torch/__init__.py", line 1007, in _check
    _check_with(RuntimeError, cond, message)
  File "/tmp/lib/python3.8/site-packages/torch/__init__.py", line 990, in _check_with
    raise error_type(message_evaluated)
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method index_select of type object at 0x7f5771d79220>(*(), **{'input': FakeTensor(..., size=(8, 16)), 'dim': 0, 'index': FakeTensor(..., size=(10,), dtype=torch.int64), 'out': FakeTensor(..., size=(8, 16))}):
expand: attempting to expand a dimension of length 10!

from user code:
   File "index_selct.py", line 4, in dummy_fn
    return torch.index_select(**op_inputs_dict)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.15.2a0
[pip3] torchvision==0.15.1a0

**Comment by jon-chuang** [comment]
> even though the shape of output tensor is correct.

This is incorrect. The shape of out ought to be (8, 16). It was resized for you by eager.

**Comment by jay746** [comment]
@jon-chuang , Why do you think that out shape will be [8,16] in above example?
Let's take the example of below eager code:
```
import torch

def dummy_fn(op_inputs_dict):
    return torch.index_select(**op_inputs_dict)

if __name__ == "__main__":
    torch.manual_seed(10)
    op_inputs_dict = {
        "input": torch.randn([8, 16]),
        "dim": 0,
        "index": torch.tensor([2, 1, 6, 7, 3, 1, 7, 5, 6, 7]),
    }
    res = dummy_fn(op_inputs_dict)
    print(res.shape)

```
The result of above code is **torch.Size([10, 16])**
This is what we are passing when running with out parameter.

Also as per doc https://pytorch.org/docs/stable/generated/torch.index_select.html 
<img width="470" alt="image" src="https://github.com/pytorch/pytorch/assets/66110943/9ac27d98-abba-4e65-b0c4-250ff322e6b7">

In above example given we are trying take the torch.index at 0th dim and here len(index) = 10 and input tensor is (8, 16), hence the out will be (len(index), input_shape[1]) =  [10,16]

**Comment by jon-chuang** [comment]
Oh, you're absolutely right. I misread the error message as coming from eager.

Seems like yet another bug with `out=`... I wonder if there are so many bugs because its not really on the testing / usage path...

**Comment by bdhirsh** [comment]
our meta fn for index_select.out was wrong - fixed here: https://github.com/pytorch/pytorch/pull/111364.

Our meta tensor testing for ops is based off of opinfos, and I'm not sure what the state of out= coverage is for opinfos..
