### ISSUE TITLE
Error with monai SwinUNETR and checkpointing

### ISSUE THREAD

**Issue by john-zielke-snkeos** [pytorch/pytorch#110701]
### 🐛 Describe the bug

When running SwinUnetr from monai , I get the following error during execution:

```
/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/utils/checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Traceback (most recent call last):
  File "/home/joz/projects/pytorch_switch/swin_unetr.py", line 14, in <module>
    output = model(input_tensor).cpu()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 301, in forward
    hidden_states_out = self.swinViT(x_in, self.normalize)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 1043, in forward
    x1 = self.layers1[0](x0.contiguous())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 879, in forward
    x = blk(x, attn_mask)
        ^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 672, in forward
    x = checkpoint.checkpoint(self.forward_part1, x, mask_matrix)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 450, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 230, in forward
    outputs = run_function(*args)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 612, in forward_part1
    attn_windows = self.attn(x_windows, mask=attn_mask)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 501, in forward
    attn = attn + relative_position_bias.unsqueeze(0)
           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.
```
I am using the following code:
```python
import torch
from monai.networks.nets.swin_unetr import SwinUNETR

input_shape = (1, 1, 576, 256, 256)
input_tensor = torch.randn(input_shape).to("cuda")
model = SwinUNETR(
    spatial_dims=3,
    in_channels=1,
    out_channels=13,
    use_checkpoint=True,
    img_size=input_shape[2:],
).to("cuda")
output = model(input_tensor).cpu()

```
This error only seems to happen with larger input sizes, and smaller ones seem to run fine. But since the error message suggests to file an issue, this is what I am doing if the error message can be improved with this.

### Versions

My monai version is 1.2.0

PyTorch version: 2.1.0.dev20230731+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro RTX 5000
Nvidia driver version: 536.25
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Stepping:                        13
CPU MHz:                         3600.011
BogoMIPS:                        7200.02
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] onnx==1.14.1
[pip3] onnxruntime-gpu==1.15.1
[pip3] pytorch-lightning==2.0.5
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] snketorch==0.0.0
[pip3] torch==2.1.0.dev20230731+cu118
[pip3] torchaudio==2.1.0.dev20230731+cu118
[pip3] torchmetrics==1.0.1
[pip3] torchvision==0.16.0.dev20230731+cu118
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.25.0          py311h08b1b3b_0  
[conda] numpy-base                1.25.0          py311hf175353_0  
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-lightning         2.0.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230731+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230731+cu118          pypi_0    pypi
[conda] torchmetrics              1.0.1                    pypi_0    pypi
[conda] torchtriton               2.0.0                     py311    pytorch
[conda] torchvision               0.16.0.dev20230731+cu118          pypi_0    pypi

**Comment by ezyang** [comment]
can you run with CUDA_LAUNCH_BLOCKING=1 and post the updated stack trace

**Comment by john-zielke-snkeos** [comment]
When running it with `CUDA_LAUNCH_BLOCKING=1 python swin_unetr.py` I get the same output.
For completeness:
```
Traceback (most recent call last):
  File "/home/joz/projects/pytorch_switch/swin_unetr.py", line 14, in <module>
    output = model(input_tensor).cpu()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 301, in forward
    hidden_states_out = self.swinViT(x_in, self.normalize)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 1043, in forward
    x1 = self.layers1[0](x0.contiguous())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 879, in forward
    x = blk(x, attn_mask)
        ^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 672, in forward
    x = checkpoint.checkpoint(self.forward_part1, x, mask_matrix, use_reentrant=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 457, in checkpoint
    ret = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 612, in forward_part1
    attn_windows = self.attn(x_windows, mask=attn_mask)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joz/.conda/envs/mlpytorch/lib/python3.11/site-packages/monai/networks/nets/swin_unetr.py", line 501, in forward
    attn = attn + relative_position_bias.unsqueeze(0)
           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.
```

**Comment by ezyang** [comment]
I ran this on a source build 261cae793a19d91fda0d44d2c2bd8cd7e9a0b93f with monai 1.2.0 and it did not fail in this way.

```
PyTorch version: 2.2.0a0+gitf68500b 
Is debug build: False              
CUDA used to build PyTorch: 12.0        
ROCM used to build PyTorch: N/A           
                                                         
OS: CentOS Stream 9 (x86_64)            
GCC version: (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)                                                                                                                                                                                  
Clang version: 16.0.6 (Red Hat 16.0.6-1.el9)                                                                                                                                                                                           
CMake version: version 3.27.2                                                                                                                                                                                                          
Libc version: glibc-2.34                                                                                                                                                                                                               
                                                         
Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Is CUDA available: True                                                                                            
CUDA runtime version: 12.0.140                                                                                     
CUDA_MODULE_LOADING set to: LAZY                                                                                   
GPU models and configuration:                                                                                      
GPU 0: NVIDIA PG509-210                                                                                            
GPU 1: NVIDIA PG509-210                                                                                            
GPU 2: NVIDIA PG509-210                                                                                            
GPU 3: NVIDIA PG509-210                                                                                            
GPU 4: NVIDIA PG509-210                                                                                            
GPU 5: NVIDIA PG509-210                                                                                            
GPU 6: NVIDIA PG509-210                                                                                            
GPU 7: NVIDIA PG509-210                                                                                            
                                                                                                                   
Nvidia driver version: 525.105.17                                                                                  
cuDNN version: Probably one of the following:                                                                      
/usr/lib64/libcudnn.so.8.8.0                                                                                       
/usr/lib64/libcudnn_adv_infer.so.8.8.0                                                                             
/usr/lib64/libcudnn_adv_train.so.8.8.0                                                                             
/usr/lib64/libcudnn_cnn_infer.so.8.8.0                                                                             
/usr/lib64/libcudnn_cnn_train.so.8.8.0                                                                             
/usr/lib64/libcudnn_ops_infer.so.8.8.0                                                                             
/usr/lib64/libcudnn_ops_train.so.8.8.0                                                                             
HIP runtime version: N/A                                                                                           
MIOpen runtime version: N/A                                                                                        
Is XNNPACK available: Tru
```

maybe upgrading CUDA version will help.

**Comment by YichengDWu** [comment]
I'm getting the same error when trying to run the scripy in [modulus](https://github.com/NVIDIA/modulus-launch/tree/main/examples/cfd/darcy_fno).

<details>

<summary>Error msg</summary>

```python
ethan@NV-1282ML3:~/modulus-launch/examples/cfd/darcy_fno$ python train_fno_darcy.py
Warp 0.10.1 initialized:
   CUDA Toolkit: 11.5, Driver: 12.1
   Devices:
     "cpu"    | x86_64
     "cuda:0" | NVIDIA RTX A3000 Laptop GPU (sm_86)
   Kernel cache: /home/ethan/.cache/warp/0.10.1
/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
[11:57:29 - mlflow - WARNING] Checking MLFlow logging location is working (if this hangs its not)
[11:57:29 - mlflow - INFO] MLFlow logging location is working
[11:57:29 - mlflow - INFO] Existing Darcy_FNO experiment found
[11:57:31 - checkpoint - WARNING] Provided checkpoint directory ./checkpoints does not exist, skipping load
[11:57:31 - darcy_fno - WARNING] Model FourierNeuralOperator does not support AMP on GPUs, turning off
[11:57:31 - darcy_fno - WARNING] Model FourierNeuralOperator does not support AMP on GPUs, turning off
[11:57:31 - darcy_fno - INFO] Training started...
Module modulus.datapipes.benchmarks.kernels.initialization load on device 'cuda:0' took 1.24 ms
Module modulus.datapipes.benchmarks.kernels.utils load on device 'cuda:0' took 4.50 ms
Module modulus.datapipes.benchmarks.kernels.finite_difference load on device 'cuda:0' took 5.88 ms
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ethan/modulus-launch/examples/cfd/darcy_fno/train_fno_darcy.py", line 178, in <module>
    darcy_trainer()
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/modulus-launch/examples/cfd/darcy_fno/train_fno_darcy.py", line 147, in darcy_trainer
    loss = forward_train(batch["permeability"], batch["darcy"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/modulus/utils/capture.py", line 162, in decorated
    self.output = self._amp_forward(*args, **kwds)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/modulus/utils/capture.py", line 247, in _amp_forward
    output = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/modulus-launch/examples/cfd/darcy_fno/train_fno_darcy.py", line 126, in forward_train
    pred = model(invars)
           ^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/modulus/models/fno/fno.py", line 772, in forward
    y_latent = self.spec_encoder(x)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/modulus/models/fno/fno.py", line 250, in forward
    x = self.activation_fn(conv(x) + w(x))
                                     ^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/.pyenv/versions/3.11.6/lib/python3.11/site-packages/modulus/models/layers/spectral_layers.py", line 180, in forward
    x = torch.fft.irfft2(out_ft, s=(x.size(-2), x.size(-1)))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.
```
</details>

version info:
```
PyTorch version: 2.2.0a0+gitf68500b
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)
Clang version: 16.0.6 (Red Hat 16.0.6-1.el9)
CMake version: version 3.27.2
Libc version: glibc-2.34

Python version: 3.10.12 (main, Jul 5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA PG509-210
GPU 1: NVIDIA PG509-210
GPU 2: NVIDIA PG509-210
GPU 3: NVIDIA PG509-210
GPU 4: NVIDIA PG509-210
GPU 5: NVIDIA PG509-210
GPU 6: NVIDIA PG509-210
GPU 7: NVIDIA PG509-210

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.8.0
/usr/lib64/libcudnn_adv_infer.so.8.8.0
/usr/lib64/libcudnn_adv_train.so.8.8.0
/usr/lib64/libcudnn_cnn_infer.so.8.8.0
/usr/lib64/libcudnn_cnn_train.so.8.8.0
/usr/lib64/libcudnn_ops_infer.so.8.8.0
/usr/lib64/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```

**Comment by john-zielke-snkeos** [comment]
> I ran this on a source build [261cae7](https://github.com/pytorch/pytorch/commit/261cae793a19d91fda0d44d2c2bd8cd7e9a0b93f) with monai 1.2.0 and it did not fail in this way.
> 
> ```
> PyTorch version: 2.2.0a0+gitf68500b 
> Is debug build: False              
> CUDA used to build PyTorch: 12.0        
> ROCM used to build PyTorch: N/A           
>                                                          
> OS: CentOS Stream 9 (x86_64)            
> GCC version: (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)                                                                                                                                                                                  
> Clang version: 16.0.6 (Red Hat 16.0.6-1.el9)                                                                                                                                                                                           
> CMake version: version 3.27.2                                                                                                                                                                                                          
> Libc version: glibc-2.34                                                                                                                                                                                                               
>                                                          
> Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
> Is CUDA available: True                                                                                            
> CUDA runtime version: 12.0.140                                                                                     
> CUDA_MODULE_LOADING set to: LAZY                                                                                   
> GPU models and configuration:                                                                                      
> GPU 0: NVIDIA PG509-210                                                                                            
> GPU 1: NVIDIA PG509-210                                                                                            
> GPU 2: NVIDIA PG509-210                                                                                            
> GPU 3: NVIDIA PG509-210                                                                                            
> GPU 4: NVIDIA PG509-210                                                                                            
> GPU 5: NVIDIA PG509-210                                                                                            
> GPU 6: NVIDIA PG509-210                                                                                            
> GPU 7: NVIDIA PG509-210                                                                                            
>                                                                                                                    
> Nvidia driver version: 525.105.17                                                                                  
> cuDNN version: Probably one of the following:                                                                      
> /usr/lib64/libcudnn.so.8.8.0                                                                                       
> /usr/lib64/libcudnn_adv_infer.so.8.8.0                                                                             
> /usr/lib64/libcudnn_adv_train.so.8.8.0                                                                             
> /usr/lib64/libcudnn_cnn_infer.so.8.8.0                                                                             
> /usr/lib64/libcudnn_cnn_train.so.8.8.0                                                                             
> /usr/lib64/libcudnn_ops_infer.so.8.8.0                                                                             
> /usr/lib64/libcudnn_ops_train.so.8.8.0                                                                             
> HIP runtime version: N/A                                                                                           
> MIOpen runtime version: N/A                                                                                        
> Is XNNPACK available: Tru
> ```
> 
> maybe upgrading CUDA version will help.

I see you are running a A100 ? As mentioned previously I think this is related to a GPU OOM error, as the error does not occur with smaller input tensors. So if you run a A100, you would need to increase the input size accordingly until you get a OOM.

I would have to see whether I can retest with an upgraded CUDA version, but as mentioned in the previous comment this seems to occur with newer CUDA versions as well

**Comment by ptrblck** [comment]
@john-zielke-snkeos The stacktrace seems to point to a failure in `dlopen`ing `libcuda.so` and/or `libnvidia-ml.so.1`.
Could you rerun the code via `LD_DEBUG=libs` and check if the log shows an issue in finding one of the libs?
Also, it seems you are using WSL? Do you have a linux system available and can reproduce it there?

**Comment by john-zielke-snkeos** [comment]
@ptrblck Not that I can see. But it should also be unlikely to have an issue with finding a library, since it works if running smaller inputs.
Regarding WSL: Yes I am. Unfortunately I don't have access to a Linux system atm, but maybe @YichengDWu does?

**Comment by YichengDWu** [comment]
Unforunately no. But I managed to get round this bug by running in a docker container built with Python 3.10.
