### ISSUE TITLE
[__or__] aten::bitwise_or() Expected a value of type 'Tensor' for argument 'other' but instead found type 'int'

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#110880]
### 🐛 Describe the bug

In eager scalar is passed to __or__ operation then works fine, even documentation says that is supports scalar value.
<img width="206" alt="image" src="https://github.com/pytorch/pytorch/assets/66110943/58360282-8882-4357-8384-aef8e5c6ef98">
Ref: https://pytorch.org/docs/stable/jit_builtin_functions.html
but when it is executed with torch.compile, we get the cast error. 
Please use below code to reproduce the issue:

```
import torch

def impl_or(ifm):
    res = getattr(ifm, '__or__')(other=78)
    return res

if __name__ == "__main__":
    x = torch.rand([10]).to(dtype=torch.uint8)
    coml_fn = torch.compile(impl_or)
    res = coml_fn(x)
    print(res)

```

### Error logs

Traceback (most recent call last):
  File "bitwise_or.py", line 10, in <module>
    res = coml_fn(x)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1167, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 594, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/variables/tensor.py", line 655, in call_method
    return wrap_fx_proxy(
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1274, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1376, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/tmp//lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1399, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1541, in dispatch
    r = func(*args, **kwargs)
  File "/tmp//lib/python3.8/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.TorchRuntimeError: Failed running call_method __or__(*(FakeTensor(..., size=(10,), dtype=torch.uint8),), **{'other': 78}):
aten::bitwise_or() Expected a value of type 'Tensor' for argument 'other' but instead found type 'int'.
Position: 1
Value: 78
Declaration: aten::bitwise_or.Tensor(Tensor self, Tensor other) -> Tensor
Cast error details: Unable to cast 78 to Tensor

from user code:
   File "bitwise_or.py", line 4, in impl_or
    res = getattr(ifm, '__or__')(other=78)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Versions

Versions
Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.15.2a0
[pip3] torchvision==0.15.1a0

cc @ezyang @msaroufim @albanD @wconstab @bdhirsh @anijain2305

**Comment by eellison** [comment]
cc @albanD @ezyang the following repros, looks like dispatcher issue where we are dispatching to the wrong signature.

```
x = torch.rand([10]).to(dtype=torch.uint8)
with torch._subclasses.fake_tensor.FakeTensorMode(allow_non_fake_inputs=True):
    x | 78
```

> RuntimeError: aten::bitwise_or() Expected a value of type 'Tensor' for argument 'other' but instead found type 'int'.

**Comment by ezyang** [comment]
this no longer repros on main

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu005.nha1 ~/local/a/pytorch (61357c11)]$ cat > af.py
import torch

def impl_or(ifm):
    res = getattr(ifm, '__or__')(other=78)
    return res

if __name__ == "__main__":
    x = torch.rand([10]).to(dtype=torch.uint8)
    coml_fn = torch.compile(impl_or)
    res = coml_fn(x)
    print(res)
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu005.nha1 ~/local/a/pytorch (61357c11)]$ python af.py
tensor([78, 78, 78, 78, 78, 78, 78, 78, 78, 78], dtype=torch.uint8)
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu005.nha1 ~/local/a/pytorch (61357c11)]$ git rev-parse HEAD
61357c11d45a64357932667464b7a77f36f25af5
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu005.nha1 ~/local/a/pytorch (61357c11)]$ git rev-parse HEAD~
619ae87a1d1ae086f59a64d3b71dbfe4af8b804a
```
