### ISSUE TITLE
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::lift_fresh' to ONNX opset version 13 is not supported.

### ISSUE THREAD

**Issue by jacker-whh** [pytorch/pytorch#110859]
### 🐛 Describe the bug

```
 TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if img.dim() == 5 and img.size(0) == 1:
/mnt/coding/singularity/multi_view_3d/models/detectors/bevformer_onnx.py:95: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_feat.view(B, int(BN / B), C, H, W))
/mnt/coding/singularity/multi_view_3d/models/modules/transformer_onnx.py:467: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  spatial_shapes = torch.as_tensor(
/mnt/coding/singularity/multi_view_3d/models/modules/encoder_onnx.py:503: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ref_3d.detach().cpu().numpy()
/mnt/coding/singularity/multi_view_3d/models/modules/encoder_onnx.py:514: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ref_2d.detach().cpu().numpy()
/mnt/coding/singularity/multi_view_3d/models/modules/encoder_onnx.py:637: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  ref_2d = torch.from_numpy(ref_2d).to(bev_query.device)
/mnt/coding/singularity/multi_view_3d/models/modules/encoder_onnx.py:640: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  ref_3d = torch.from_numpy(ref_3d).to(bev_query.device)
/mnt/coding/singularity/multi_view_3d/models/modules/encoder_onnx.py:401: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  spatial_shapes=torch.tensor([[bev_h, bev_w]],
/mnt/coding/singularity/multi_view_3d/models/modules/encoder_onnx.py:403: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  level_start_index=torch.tensor([0], device=query.device),
/mnt/coding/singularity/multi_view_3d/models/modules/temporal_self_attention.py:443: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (spatial_shapes[:, 0] * spatial_shapes[:, 1]).sum() == num_value
/mnt/coding/singularity/multi_view_3d/models/modules/temporal_self_attention.py:475: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:524: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for i, reference_points_per_img in enumerate(reference_points_cam):
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:527: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  queries_rebatch[j, i, :len(index_query_per_img)] = query[j, index_query_per_img]
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:528: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  reference_points_rebatch[j, i, :len(index_query_per_img)] = reference_points_per_img[j, index_query_per_img]
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:339: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (spatial_shapes[:, 0] * spatial_shapes[:, 1]).sum() == num_value
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:357: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:378: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert num_all_points == num_points * num_Z_anchors
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:546: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for i, index_query_per_img in enumerate(indexes):
/mnt/coding/singularity/multi_view_3d/models/modules/spatial_cross_attention_onnx.py:548: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  j, i, :len(index_query_per_img)]
/usr/local/lib/python3.8/dist-packages/mmcv_full-1.6.1-py3.8-linux-x86_64.egg/mmcv/cnn/bricks/wrappers.py:170: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 5)):
/mnt/coding/singularity/multi_view_3d/models/modules/transformer_onnx.py:577: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  spatial_shapes=torch.tensor([[bev_h, bev_w]], device=query.device),
/mnt/coding/singularity/multi_view_3d/models/modules/transformer_onnx.py:578: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  level_start_index=torch.tensor([0], device=query.device),
/usr/local/lib/python3.8/dist-packages/flash_attn-2.2.3.post2-py3.8-linux-x86_64.egg/flash_attn/flash_attn_interface.py:47: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
/mnt/coding/singularity/multi_view_3d/models/modules/decoder.py:642: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (spatial_shapes[:, 0] * spatial_shapes[:, 1]).sum() == num_value
/mnt/coding/singularity/multi_view_3d/models/modules/decoder.py:659: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
/mnt/coding/singularity/multi_view_3d/models/dense_heads/bevformer_head_onnx.py:683: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert reference.shape[-1] == 3
----------------------------------------1112
----------------------------------------1112
----------------------------------------1112
----------------------------------------1112
----------------------------------------1112
----------------------------------------1112
----------------------------------------1112
/home/jidudev/.local/lib/python3.8/site-packages/torch/onnx/utils.py:617: UserWarning: ONNX Preprocess - Removing mutation from node aten::squeeze_ on block input: 'img'. This changes graph semantics. (Triggered internally at ../torch/csrc/jit/passes/onnx/remove_inplace_ops_for_onnx.cpp:335.)
  _C._jit_pass_onnx_remove_inplace_ops_for_onnx(graph, module)
Traceback (most recent call last):
  File "/mnt/coding/singularity/multi_view_3d/tools/test2onnx_nopre.py", line 460, in <module>
    main()
  File "/mnt/coding/singularity/multi_view_3d/tools/test2onnx_nopre.py", line 420, in main
    torch.onnx.export(
  File "/home/jidudev/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/jidudev/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/jidudev/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/home/jidudev/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/jidudev/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1909, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::lift_fresh' to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
```

### Versions

torch 13.1
cuda 11.6

**Comment by justinchuby** [comment]
Please report the error on the latest PyTorch (2.1). Thanks!

For the error, I suspect you can register a custom symbolic function that will simply return the input. lift_fresh seems to be just an no-op for ONNX.

**Comment by justinchuby** [comment]
So use 

```python
torch.onnx.register_custom_op_symbolic("aten::lift_fresh', lambda x: x, 13)
```

before calling `torch.onnx.export`.
