### ISSUE TITLE
Segmentation fault on aarch64 (Rpi4) using Pytorch 2.1.0 & torchaudio 

### ISSUE THREAD

**Issue by Topper69** [pytorch/pytorch#110819]
### 🐛 Describe the bug

On my raspberry pi 4 (aarch64 arch) with pytorch 2.1.0 & torchaudio i have a segmentation fault using microsoft [unilm/beats](https://github.com/microsoft/unilm/blob/master/beats/README.md) model. Same code run fine on my macos 11 (x86_64 arch) with same package version and code.

On the pi:
Rapsbian OS version : 11.8 bullseye (uptodate)
packaged installed:
python392 and python311 (same seg fault)
numpy              1.26.0
pandas             2.1.1
Pillow             10.0.1
torch              2.1.0
torchaudio         2.1.0
torchvision        0.16.0

```python
$python3 -m venv "testenv"
$source testenv/bin/activate
$pip3 install torch torchaudio
$python3

import torch
from BEATs import BEATs, BEATsConfig

# load the fine-tuned checkpoints
checkpoint = torch.load('/path/to/model.pt')

cfg = BEATsConfig(checkpoint['cfg'])
BEATs_model = BEATs(cfg)
BEATs_model.load_state_dict(checkpoint['model'])
BEATs_model.eval()

# predict the classification probability of each class
audio_input_16khz = torch.randn(3, 10000)
padding_mask = torch.zeros(3, 10000).bool()

probs = BEATs_model.extract_features(audio_input_16khz, padding_mask=padding_mask)[0]

for i, (top5_label_prob, top5_label_idx) in enumerate(zip(*probs.topk(k=5))):
    top5_label = [checkpoint['label_dict'][label_idx.item()] for label_idx in top5_label_idx]
    print(f'Top 5 predicted labels of the {i}th audio are {top5_label} with probability of {top5_label_prob}')


Output:
python3.11/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Segmentation fault
```

The sample code is working fine on aarch64 with pytorch 1.13.1 version (no seg fault), detail installed package:
numpy              1.24.1
pandas             1.1.5
Pillow             8.1.2
torch              1.13.1
torchaudio         0.13.1
torchvision        0.14.1

Many thanks for the help.

### Versions

PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (aarch64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.6 (main, Oct  8 2023, 12:45:00) [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     2000.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
L1d cache:                       128 KiB
L1i cache:                       192 KiB
L2 cache:                        1 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[conda] Could not collect

**Comment by liwii** [comment]
We faced the same issue when using `transformers` in a VSCode dev container (`5.15.49-linuxkit, Debian GNU/Linux 11 (bullseye)`) on M2 MacBook Pro.

I ran the code below with `transformers==4.22.1` and `torch==2.1.0`.
```python
from transformers import AutoModelForSequenceClassification, AutoTokenizer

sentiment_model_path = "cardiffnlp/twitter-roberta-base-sentiment-latest"

sentiment_tokenizer = AutoTokenizer.from_pretrained(
    sentiment_model_path)
sentiment_model = (AutoModelForSequenceClassification.
                    from_pretrained(sentiment_model_path))

input_tokens = sentiment_tokenizer(["I'm sad"],
                                    return_tensors='pt',
                                    padding=True)


output = sentiment_model(**input_tokens)
```
The caused SIGSEV, and from the gdb backtrace it seems to be coming from `libtorch_cpu`.

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x0000ffff834b6280 in __aarch64_cas4_acq () from /lib/aarch64-linux-gnu/libc.so.6
(gdb) bt
#0  0x0000ffff834b6280 in __aarch64_cas4_acq () from /lib/aarch64-linux-gnu/libc.so.6
]#1  0x0000ffff834473c0 in __GI___readdir64 (dirp=0x0) at ../sysdeps/posix/readdir.c:44
#2  0x0000ffff7eaeabc4 in Xbyak_aarch64::util::Cpu::getFilePathMaxTailNumPlus1(char const*) () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#3  0x0000ffff7eaead5c in Xbyak_aarch64::util::Cpu::Cpu() () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#4  0x0000ffff7ea88e80 in dnnl::impl::cpu::aarch64::cpu() () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#5  0x0000ffff7f07ed04 in dnnl::impl::cpu::aarch64::jit_uni_eltwise_fwd_t<(dnnl::impl::cpu::aarch64::cpu_isa_t)31, (dnnl_data_type_t)3>::pd_t::init(dnnl_engine*) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#6  0x0000ffff7ee7c6dc in dnnl_status_t dnnl::impl::primitive_desc_t::create<dnnl::impl::cpu::aarch64::jit_uni_eltwise_fwd_t<(dnnl::impl::cpu::aarch64::cpu_isa_t)31, (dnnl_data_type_t)3>::pd_t>(dnnl::impl::primitive_desc_t**, dnnl::impl::op_desc_t const*, dnnl_primitive_attr const*, dnnl_engine*, dnnl::impl::primitive_desc_t const*) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#7  0x0000ffff7e28ae5c in dnnl::impl::primitive_desc_iterator_t::operator++() [clone .isra.0] () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#8  0x0000ffff7e28b75c in dnnl_primitive_desc::init() () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#9  0x0000ffff7e28c518 in dnnl::impl::primitive_desc_create(dnnl_primitive_desc**, dnnl_engine*, dnnl::impl::op_desc_t const*, dnnl_primitive_desc const*, dnnl_primitive_attr const*) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#10 0x0000ffff7e264464 in dnnl_eltwise_forward_primitive_desc_create () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#11 0x0000ffff7aadba50 in ideep::eltwise_forward::compute(ideep::tensor const&, ideep::tensor&, dnnl::algorithm, dnnl::prop_kind, float, float, ideep::engine const&) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#12 0x0000ffff7aad2420 in at::native::structured_gelu_out_cpu::impl(at::Tensor const&, c10::basic_string_view<char>, at::Tensor const&) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#13 0x0000ffff7b8b9fd8 in at::(anonymous namespace)::wrapper_CPU_gelu(at::Tensor const&, c10::basic_string_view<char>) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#14 0x0000ffff7b8ba070 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, c10::basic_string_view<char>), &at::(anonymous namespace)::wrapper_CPU_gelu>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, c10::basic_string_view<char> > >, at::Tensor (at::Tensor const&, c10::basic_string_view<char>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char>) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#15 0x0000ffff7b3d79d0 in at::_ops::gelu::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char>) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#16 0x0000ffff7cbec354 in torch::autograd::VariableType::(anonymous namespace)::gelu(c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char>) ()
   from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
--Type <RET> for more, q to quit, c to continue without paging--RET
#17 0x0000ffff7cbec944 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char>), &torch::autograd::VariableType::(anonymous namespace)::gelu>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char> > >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, c10::basic_string_view<char>) () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#18 0x0000ffff7b421448 in at::_ops::gelu::call(at::Tensor const&, c10::basic_string_view<char>) () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#19 0x0000ffff81d4af20 in torch::autograd::THPVariable_gelu(_object*, _object*, _object*) () from /home/vscode/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#20 0x0000ffff83638240 in cfunction_call_varargs (func=<built-in method gelu of module object at remote 0xffff5b938770>, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:743
#21 0x0000ffff83636ea0 in _PyObject_MakeTpCall (callable=callable@entry=<built-in method gelu of module object at remote 0xffff5b938770>, args=<optimized out>, nargs=1, 
    keywords=keywords@entry=0x0) at Objects/call.c:159
#22 0x0000ffff83670de8 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=<built-in method gelu of module object at remote 0xffff5b938770>)
    at ./Include/cpython/abstract.h:125
#23 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=<built-in method gelu of module object at remote 0xffff5b938770>)
    at ./Include/cpython/abstract.h:115
#24 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0xaaaad5f933b0) at Python/ceval.c:4963
#25 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3469
#26 0x0000ffff836379ac in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at Objects/call.c:284
#27 0x0000ffff83638c88 in _PyObject_Vectorcall (kwnames=0x0, nargsf=2, args=0xffffd40d6380, callable=<function at remote 0xffff560bc550>) at ./Include/cpython/abstract.h:127
#28 method_vectorcall (method=method@entry=<method at remote 0xffff59cf3640>, args=<optimized out>, nargsf=nargsf@entry=1, kwnames=0x0) at Objects/classobject.c:89
#29 0x0000ffff8369e060 in PyVectorcall_Call (callable=callable@entry=<method at remote 0xffff59cf3640>, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:200
#30 0x0000ffff83638118 in PyObject_Call (callable=callable@entry=<method at remote 0xffff59cf3640>, args=args@entry=(<Tensor at remote 0xffff55526270>,), kwargs=kwargs@entry={})
    at Objects/call.c:228
#31 0x0000ffff83671108 in do_call_core (kwdict={}, callargs=(<Tensor at remote 0xffff55526270>,), func=<method at remote 0xffff59cf3640>, tstate=<optimized out>) at Python/ceval.c:5010
#32 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3559
#33 0x0000ffff8366c620 in _PyEval_EvalCodeWithName (_co=<code at remote 0xffff5b6557c0>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, 
    kwnames=kwnames@entry=0x0, kwargs=0xffffd40d66f0, kwcount=<optimized out>, kwcount@entry=0, kwstep=kwstep@entry=1, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=0x0, closure=0x0, 
    name='_call_impl', qualname='Module._call_impl') at Python/ceval.c:4298
#34 0x0000ffff83637780 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:436
#35 0x0000ffff83638c88 in _PyObject_Vectorcall (kwnames=0x0, nargsf=2, args=0xffffd40d66e0, callable=<function at remote 0xffff5b5af820>) at ./Include/cpython/abstract.h:127
#36 method_vectorcall (method=method@entry=<method at remote 0xffff59377d00>, args=<optimized out>, nargsf=nargsf@entry=1, kwnames=0x0) at Objects/classobject.c:89
--Type <RET> for more, q to quit, c to continue without paging--RET
#37 0x0000ffff8369e060 in PyVectorcall_Call (callable=callable@entry=<method at remote 0xffff59377d00>, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:200
#38 0x0000ffff83638118 in PyObject_Call (callable=callable@entry=<method at remote 0xffff59377d00>, args=args@entry=(<Tensor at remote 0xffff55526270>,), kwargs=kwargs@entry={})
    at Objects/call.c:228
#39 0x0000ffff83671108 in do_call_core (kwdict={}, callargs=(<Tensor at remote 0xffff55526270>,), func=<method at remote 0xffff59377d00>, tstate=<optimized out>) at Python/ceval.c:5010
#40 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3559
#41 0x0000ffff8366c620 in _PyEval_EvalCodeWithName (_co=<code at remote 0xffff5b6555b0>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0xffffd40d6a80, 
    argcount=argcount@entry=2, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0xffffd40d6a90, kwcount=<optimized out>, kwcount@entry=0, kwstep=kwstep@entry=1, defs=defs@entry=0x0, 
    defcount=defcount@entry=0, kwdefs=0x0, closure=0x0, name='_wrapped_call_impl', qualname='Module._wrapped_call_impl') at Python/ceval.c:4298
#42 0x0000ffff83637780 in _PyFunction_Vectorcall (func=func@entry=<function at remote 0xffff5b5af790>, stack=stack@entry=0xffffd40d6a80, nargsf=nargsf@entry=2, kwnames=kwnames@entry=0x0)
    at Objects/call.c:436
#43 0x0000ffff83636ad4 in _PyObject_FastCallDict (callable=callable@entry=<function at remote 0xffff5b5af790>, args=args@entry=0xffffd40d6a80, nargsf=nargsf@entry=2, kwargs=kwargs@entry=0x0)
    at Objects/call.c:96
#44 0x0000ffff83637d58 in _PyObject_Call_Prepend (callable=callable@entry=<function at remote 0xffff5b5af790>, 
    obj=obj@entry=<GELUActivation(training=False, _parameters={}, _buffers={}, _non_persistent_buffers_set=set(), _backward_pre_hooks={}, _backward_hooks={}, _is_full_backward_hook=None, _forward_hooks={}, _forward_hooks_with_kwargs={}, _forward_hooks_always_called={}, _forward_pre_hooks={}, _forward_pre_hooks_with_kwargs={}, _state_dict_hooks={}, _state_dict_pre_hooks={}, _load_state_dict_pre_hooks={}, _load_state_dict_post_hooks={}, _modules={}, act=<built-in method gelu of module object at remote 0xffff5b938770>) at remote 0xffff560ba460>, 
    args=args@entry=(<Tensor at remote 0xffff55526270>,), kwargs=kwargs@entry=0x0) at Objects/call.c:888
#45 0x0000ffff836b919c in slot_tp_call (
    self=self@entry=<GELUActivation(training=False, _parameters={}, _buffers={}, _non_persistent_buffers_set=set(), _backward_pre_hooks={}, _backward_hooks={}, _is_full_backward_hook=None, _forward_hooks={}, _forward_hooks_with_kwargs={}, _forward_hooks_always_called={}, _forward_pre_hooks={}, _forward_pre_hooks_with_kwargs={}, _state_dict_hooks={}, _state_dict_pre_hooks={}, _load_state_dict_pre_hooks={}, _load_state_dict_post_hooks={}, _modules={}, act=<built-in method gelu of module object at remote 0xffff5b938770>) at remote 0xffff560ba460>, 
    args=args@entry=(<Tensor at remote 0xffff55526270>,), kwds=kwds@entry=0x0) at Objects/typeobject.c:6556
#46 0x0000ffff83636ea0 in _PyObject_MakeTpCall (
    callable=callable@entry=<GELUActivation(training=False, _parameters={}, _buffers={}, _non_persistent_buffers_set=set(), _backward_pre_hooks={}, _backward_hooks={}, _is_full_backward_hook=None, _forward_hooks={}, _forward_hooks_with_kwargs={}, _forward_hooks_always_called={}, _forward_pre_hooks={}, _forward_pre_hooks_with_kwargs={}, _state_dict_hooks={}, _state_dict_pre_hooks={}, _load_state_dict_pre_hooks={}, _load_state_dict_post_hooks={}, _modules={}, act=<built-in method gelu of module object at remote 0xffff5b938770>) at remote 0xffff560ba460>, args=<optimized out>, 
    nargs=1, keywords=keywords@entry=0x0) at Objects/call.c:159
#47 0x0000ffff83670de8 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, 
    callable=<GELUActivation(training=False, _parameters={}, _buffers={}, _non_persistent_buffers_set=set(), _backward_pre_hooks={}, _backward_hooks={}, _is_full_backward_hook=None, _forward_hoo--Type <RET> for more, q to quit, c to continue without paging--Quit
```

**Comment by andrewaggb** [comment]
Just to add a little more context.

I also ran into this as did various others running yolov8 or yolo-nas on raspberry pi 3/4 in ubuntu 22.04, fyi. see https://github.com/ultralytics/ultralytics/issues/5274

Same resolution, downgrading torch to torch==2.0.1 and torchaudio==2.0.2 resolves the issue on those models as well.

I have not encountered issues with torch 2.1.0 on my windows 11 or ubuntu 22.04 x64 environments.  Just arm/aarch64 as far as I know.

**Comment by xushangning** [comment]
I encoutered the same issue on my aarch64 board (Orange Pi 5B) and after some troubleshooting I have a hypthoesis for the cause:

The segfault likely comes from a null pointer being passed to the `readdir` call. The backtraces posted by @liwii and @Topper69 also confirm this: Frame <span>#</span>1 in their backtraces both show the `dirp` parameter of `readdir` being null.

`readdir` is passed a null pointer by its caller `Xbyak_aarch64::util::Cpu::getFilePathMaxTailNumPlus1`, which is *only* called by `Cpu::setNumCores`:

https://github.com/fujitsu/xbyak_aarch64/blob/ac83636e44bbaba0b6941fedc1339e85061ab915/src/util_impl.cpp#L212-L247

`Cpu::setNumCores` calls `getFilePathMaxTailNumPlus1` twice and passes the paths `XBYAK_AARCH64_PATH_NODES` (/sys/devices/system/node/node) and `XBYAK_AARCH64_PATH_CORES` (/sys/devices/system/node/node0/cpu). These paths don't exist on my board probably due to lack of `CONFIG_NUMA` in the kernel, and `getFilePathMaxTailNumPlus1` attempts to open these paths without properly checking the return value of its `opendir` call, naively passing the returned null pointer to `readdir`, leading to the segfault:

https://github.com/fujitsu/xbyak_aarch64/blob/ac83636e44bbaba0b6941fedc1339e85061ab915/src/util_impl.cpp#L293-L326

**Comment by liwii** [comment]
The bug seems to be already fixed here on Xbyak side
https://github.com/fujitsu/xbyak_aarch64/pull/95
