### ISSUE TITLE
DDP Not able to stablish communication across nodes

### ISSUE THREAD

**Issue by TJ-Solergibert** [pytorch/pytorch#111090]
### 🐛 Describe the bug

When I work with DDP in 1 node, it works well. When I try to scale to 2 nodes, it fails. It looks like the worker node can't communicate with the master node. I've tried a variety of ports and also all the available network interfaces. Thanks in advanced.

The python script:
```python
import inspect
import os
import sys
import unittest

import torch

import accelerate
from accelerate import Accelerator
from accelerate.test_utils import execute_subprocess_async, require_multi_gpu


class MultiGPUTester(unittest.TestCase):
    def setUp(self):
        mod_file = inspect.getfile(accelerate.test_utils)
        self.test_file_path = os.path.sep.join(mod_file.split(os.path.sep)[:-1] + ["test_script.py"])

    @require_multi_gpu
    def test_multi_gpu(self):
        print(f"Found {torch.cuda.device_count()} devices.")
        distributed_args = f"""
            -m torch.distributed.launch
            --nproc_per_node={torch.cuda.device_count()}
            --use_env
            {self.test_file_path}
        """.split()
        cmd = [sys.executable] + distributed_args
        execute_subprocess_async(cmd, env=os.environ.copy())

    @require_multi_gpu
    def test_pad_across_processes(self):
        distributed_args = f"""
            -m torch.distributed.launch
            --nproc_per_node={torch.cuda.device_count()}
            --use_env
            {inspect.getfile(self.__class__)}
        """.split()
        cmd = [sys.executable] + distributed_args
        execute_subprocess_async(cmd, env=os.environ.copy())


if __name__ == "__main__":
    accelerator = Accelerator()
    shape = (accelerator.state.process_index + 2, 10)
    tensor = torch.randint(0, 10, shape).to(accelerator.device)

    error_msg = ""

    tensor1 = accelerator.pad_across_processes(tensor)
    if tensor1.shape[0] != accelerator.state.num_processes + 1:
        error_msg += f"Found shape {tensor1.shape} but should have {accelerator.state.num_processes + 1} at dim 0."
    if not torch.equal(tensor1[: accelerator.state.process_index + 2], tensor):
        error_msg += "Tensors have different values."
    if not torch.all(tensor1[accelerator.state.process_index + 2 :] == 0):
        error_msg += "Padding was not done with the right value (0)."
    
    tensor2 = accelerator.pad_across_processes(tensor, pad_first=True)
    if tensor2.shape[0] != accelerator.state.num_processes + 1:
        error_msg += f"Found shape {tensor2.shape} but should have {accelerator.state.num_processes + 1} at dim 0."
    index = accelerator.state.num_processes - accelerator.state.process_index - 1
    if not torch.equal(tensor2[index:], tensor):
        error_msg += "Tensors have different values."
    if not torch.all(tensor2[:index] == 0):
        error_msg += "Padding was not done with the right value (0)."

    # Raise error at the end to make sure we don't stop at the first failure.
    if len(error_msg) > 0:
        raise ValueError(error_msg)

```

My Slurm script:

```sh
#!/bin/bash
#SBATCH --job-name=tr
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1                  # number of MP tasks
#SBATCH --gres=gpu:4                # number of GPUs per node
#SBATCH --cpus-per-task=160            # number of cores per tasks
#SBATCH --time=01:00:00              # maximum execution time (HH:MM:SS)
#SBATCH --output=tr%j.out               # output file name
#SBATCH --error=tr%j.err                # error file name (same to watch just one file)
#SBATCH --qos=debug

module purge; module load gcc/8.3.0 cuda/10.2 cudnn/7.6.4 nccl/2.4.8 tensorrt/6.0.1 openmpi/4.0.1 atlas scalapack/2.0.2 fftw/3.3.8 szip/2.1.1 ffmpeg/4.2.1 opencv/4.1.1 python/3.7.4_ML arrow/3.0.0 torch/1.7.1 text-mining/2.1.0

module unload nccl/2.4.8

module load nccl/2.9.9

export NCCL_DEBUG=INFO
export LOGLEVEL=INFO

GPUS_PER_NODE=4
NNODES=$SLURM_JOB_NUM_NODES
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))

MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
MASTER_PORT=16817
HOSTNAMES=$(scontrol show hostnames $SLURM_JOB_NODELIST)
COUNT_NODE=$(scontrol show hostnames $SLURM_JOB_NODELIST | wc -l)

echo "Hostnames: $HOSTNAMES . MasterAddres: $MASTER_ADDR. MasterPort: $MASTER_PORT. CountNode: $COUNT_NODE"

cd /home/nct01/nct01328/accelerate

export LAUNCHER=" \
    python -m torch.distributed.launch \
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT \
"

export CMD="$LAUNCHER --node_rank $SLURM_PROCID /home/nct01/nct01328/accelerate/tests/test_multigpu.py"
echo $CMD
srun --jobid $SLURM_JOBID bash -c "$CMD"
```

The output file I get:
```
Hostnames: p9r1n16
p9r3n15 . MasterAddres: p9r1n16. MasterPort: 16817. CountNode: 2
NCCL: INFO . LOGLEVEL: INFO . NCCL_SOCKET: 
python -m torch.distributed.launch --nproc_per_node 4 --nnodes 2 --master_addr p9r1n16 --master_port 16817 --node_rank 0 /home/nct01/nct01328/accelerate/tests/test_multigpu.py
p9r3n15:119869:119869 [0] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.51<0>
p9r3n15:119869:119869 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r3n15:119869:119869 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.51<0>
p9r3n15:119869:119869 [0] NCCL INFO Using network IB
NCCL version 2.7.8+cuda10.2
p9r1n16:48205:48205 [3] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.16<0>
p9r1n16:48205:48205 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r3n15:119872:119872 [3] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.51<0>
p9r3n15:119871:119871 [2] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.51<0>
p9r3n15:119872:119872 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r3n15:119871:119871 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r3n15:119870:119870 [1] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.51<0>
p9r3n15:119870:119870 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r3n15:119872:119872 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.51<0>
p9r3n15:119872:119872 [3] NCCL INFO Using network IB
p9r3n15:119870:119870 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.51<0>
p9r3n15:119870:119870 [1] NCCL INFO Using network IB
p9r3n15:119871:119871 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.51<0>
p9r3n15:119871:119871 [2] NCCL INFO Using network IB
p9r1n16:48205:48205 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.16<0>
p9r1n16:48205:48205 [3] NCCL INFO Using network IB

p9r3n15:119869:119917 [0] bootstrap.cc:195 NCCL WARN Bootstrap Root : rank 3 of 8 ranks has already checked in
p9r1n16:48203:48203 [1] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.16<0>
p9r1n16:48203:48203 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r1n16:48202:48202 [0] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.16<0>
p9r1n16:48202:48202 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r1n16:48203:48203 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.16<0>
p9r1n16:48203:48203 [1] NCCL INFO Using network IB
p9r1n16:48202:48202 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.16<0>
p9r1n16:48202:48202 [0] NCCL INFO Using network IB
NCCL version 2.7.8+cuda10.2
p9r1n16:48204:48204 [2] NCCL INFO Bootstrap : Using [0]ib0:10.1.1.16<0>
p9r1n16:48204:48204 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
p9r1n16:48204:48204 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.1.1.16<0>
p9r1n16:48204:48204 [2] NCCL INFO Using network IB
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying
p9r1n16:48203:48251 [1] NCCL INFO Call to connect returned Connection refused, retrying

p9r1n16:48203:48251 [1] include/socket.h:403 NCCL WARN Connect to 10.1.1.51<42303> failed : Connection refused
p9r1n16:48203:48251 [1] NCCL INFO bootstrap.cc:95 -> 2
p9r1n16:48203:48251 [1] NCCL INFO bootstrap.cc:309 -> 2
p9r1n16:48203:48251 [1] NCCL INFO init.cc:555 -> 2
p9r1n16:48203:48251 [1] NCCL INFO init.cc:840 -> 2
p9r1n16:48203:48251 [1] NCCL INFO group.cc:73 -> 2 [Async thread]

```
The error file I get:
```
Traceback (most recent call last):
  File "/home/nct01/nct01328/accelerate/tests/test_multigpu.py", line 58, in <module>
    accelerator = Accelerator()
  File "/apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/accelerate/accelerator.py", line 164, in __init__
    **kwargs,
  File "/apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/accelerate/state.py", line 199, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
  File "/apps/TORCH/1.7.1/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/apps/TORCH/1.7.1/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /gpfs/apps/POWER9/PYTHON/SRC/ML/3.7.4/modules/pytorch_1.7.1/pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
```

### Versions

PyTorch version: 1.9.0a0+git3d70ab0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.5 (Maipo) (ppc64le)
GCC version: (GCC) 8.3.0
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: glibc-2.17

Python version: 3.7.4 (v3.7.4-dirty:e093591, Oct 14 2019, 12:33:22)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-4.14.0-115.el7a.ppc64le-ppc64le-with-redhat-7.5-Maipo
Is CUDA available: True
CUDA runtime version: 10.2.89
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-9.2/targets/ppc64le-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                160
On-line CPU(s) list:   0-159
Thread(s) per core:    4
Core(s) per socket:    20
Socket(s):             2
NUMA node(s):          6
Model:                 2.1 (pvr 004e 1201)
Model name:            POWER9, altivec supported
CPU max MHz:           3800,0000
CPU min MHz:           2300,0000
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              10240K
NUMA node0 CPU(s):     0-79
NUMA node8 CPU(s):     80-159
NUMA node252 CPU(s):   
NUMA node253 CPU(s):   
NUMA node254 CPU(s):   
NUMA node255 CPU(s):

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.2
[pip3] flake8==3.5.0
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.3
[pip3] onnx==1.7.0
[pip3] pytorch-lightning==1.5.8
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.9.0a0+git3d70ab0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.3
[pip3] torch-scatter==2.0.7
[pip3] torch-sparse==0.6.10
[pip3] torch-spline-conv==1.2.1
[pip3] torch-stft==0.1.4
[pip3] torchmetrics==0.7.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.6.0
[pip3] torchvision==0.4.0a0
[pip3] triton==0.3.0

**Comment by always-H** [comment]
hi, I have same problem with the error message "nccl error in: /pytorch/torch/lib/c10d/processgroupnccl.cpp:784, unhandled system error", some say it the nccl's problem, not pytorch. How do you solve this problem?
