### ISSUE TITLE
[Regression][PT2.1][Dynamic] torch.add torch._dynamo.exc.TorchRuntimeError: Failed running call_function

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#111199]
### 🐛 Describe the bug

torch.add with out tensor has been regressed in PT2,1 upgrade. Same test used to work in PT2.1
Please use below code to reproduce the issue.
```
import torch


def fn(inputs, other, alpha, out):
    res = torch.add(inputs, other, alpha=alpha, out=out)
    return res


if __name__ == "__main__":
    inputs = torch.randn(2, 3, 4)
    other = 1
    alpha = 2
    out = torch.empty(2, 3, 4)
    compl_fn = torch.compile(fn, dynamic=True)
    res = compl_fn(inputs, other, alpha, out)
    print(res)

```

### Error logs

Traceback (most recent call last):
  File "debug_abs.py", line 15, in <module>
    res = compl_fn(inputs, other, alpha, out)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1167, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 729, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1274, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1376, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1450, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 229, in _fn
    result = fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 132, in _fn
    result = fn(**bound.arguments)
  File "/tmp/lib/python3.8/site-packages/torch/_refs/__init__.py", line 1021, in add
    if python_type != bool and not utils.is_weakly_lesser_type(
  File "/tmp/lib/python3.8/site-packages/torch/_prims_common/__init__.py", line 1073, in is_weakly_lesser_type
    assert a in ordered_types
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method add of type object at 0x7fda7a411220>(*(FakeTensor(..., size=(s0, s1, s2)), 1), **{'alpha': s3, 'out': FakeTensor(..., size=(s0, s1, s2))}):

from user code:
   File "debug_abs.py", line 5, in fn
    res = torch.add(inputs, other, alpha=alpha, out=out)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Versions

[pip3] numpy==1.24.4
[pip3] torch==2.1.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.1

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
Well this is embarrassing. As a workaround you can use torch._dynamo.mark_dynamic to manually mark the dimensions you want dynamic and remove dynamic=False. In this case the problem is we improved dynamism in PT2 so that alpha is dynamic too now, which add never supported.

**Comment by jay746** [comment]
@ezyang, I see the similar issue in **addr** operator as well. Do you want me raise another issue for it or this is enough?

**Comment by jon-chuang** [comment]
Hmm, interestingly it works without the out. I guess it does not go onto the lowering path... :thinking:

**Comment by ezyang** [comment]
I see you filed a bunch of issues. I think the root causes are the same, so maybe you can just add the other instances as comments. Are you running a fuzzer right now?

**Comment by jon-chuang** [comment]
@ezyang I have a fix incoming

**Comment by desertfire** [comment]
I am linking all similar issues here for reference:
https://github.com/pytorch/pytorch/issues/111188
https://github.com/pytorch/pytorch/issues/111197
https://github.com/pytorch/pytorch/issues/111198
https://github.com/pytorch/pytorch/issues/111200
https://github.com/pytorch/pytorch/issues/111201
https://github.com/pytorch/pytorch/issues/111202
https://github.com/pytorch/pytorch/issues/111203
https://github.com/pytorch/pytorch/issues/111203

**Comment by ezyang** [comment]
@jay746 would you at all be willing to help us add those tests to the test suite in PT?
