### ISSUE TITLE
[amp][cpu] `multi_head_attention_forward` raise mismatch in the dtype when using `torch.cpu.amp.autocast`

### ISSUE THREAD

**Issue by yiliu30** [pytorch/pytorch#111276]
### Description
While running the model including `TransformerEncoder` module with [AMP](https://pytorch.org/docs/stable/amp.html#autocasting), a RuntimeError occurs due to a mismatch in the dtype of the attn_mask and query tensors. 

### Code
The code to reproduce this bug:
```python
from torch.nn import TransformerEncoderLayer, Linear
import torch
from torch import nn

class DemoModel(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        
        encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8, batch_first = True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=6)
        self.dense = Linear(512, 10)
    
    def forward(self, x):
        src_query_mask = torch.rand(1, 41)
        src_query_emb_VT = torch.rand(1, 41, 512)
        out1 = self.transformer_encoder(src_query_emb_VT , src_key_padding_mask = src_query_mask)
        res = self.dense(out1)
        return res

src = torch.rand(2, 32, 512)
print(src.shape) # torch.Size([2, 32, 512])
demo_model = DemoModel()
with torch.autocast(device_type="cpu", dtype=torch.bfloat16):
    out = demo_model(src)
    print("Out shape", out.shape)
```

### Log
```shell
Traceback (most recent call last):
  File "auto_cast_demo.py", line 41, in <module>
    out = demo_model(src)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "auto_cast_demo.py", line 21, in forward
    out1 = self.transformer_encoder(src_query_emb_VT , src_key_padding_mask = src_query_mask)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 387, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 707, in forward
    x = self.norm1(x + self._sa_block(x, src_mask, src_key_padding_mask, is_causal=is_causal))
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 715, in _sa_block
    x = self.self_attn(x, x, x,
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/nodename/.conda/envs/tmp_envs/lib/python3.8/site-packages/torch/nn/functional.py", line 5442, in multi_head_attention_forward
    print(f"q dtype: {q.dtype}")
RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but got attn_mask.dtype: float and  query.dtype: c10::BFloat16 instead.

```

### Versions

```shell
Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.16.0-rc8-intel-next-01534-g53cb5f883cf7-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
CPU(s):              224
Model name:          Intel(R) Xeon(R) Platinum 8480+
...
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm uintr md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.100
[pip3] numpy==1.24.4
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.16.1
[pip3] torch==2.1.0
[pip3] triton==2.1.0
[conda] intel-extension-for-pytorch 2.0.100                  pypi_0    pypi
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @Valentine233

**Comment by jon-chuang** [comment]
I think attention mask dtype is hard-coded to float. Let me try to make it autocast-able

**Comment by leslie-fang-intel** [comment]
Hi @jon-chuang, will you take a look of this issue? Otherwise, I think @Valentine233 may help to look into it.

**Comment by jon-chuang** [comment]
Sure, @Valentine233 can take over if they want :) just ping me for reviewing the PR.

**Comment by Valentine233** [comment]
I'm wondering if this issue also exists in CUDA, because it looks like a common issue. @jon-chuang @yiliu30

**Comment by yiliu30** [comment]
> I'm wondering if this issue also exists in CUDA, because it looks like a common issue. @jon-chuang @yiliu30

Hi @Valentine233 , I have tested it on the GPU and it worked for me.

```python
from torch.nn import Linear
import torch
from torch import nn

class DemoModel(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        
        encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8, batch_first = True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=6)
        self.dense = Linear(512, 10)
    
    def forward(self, x):
        src_query_mask = torch.rand(1, 41)
        src_query_emb_VT = torch.rand(1, 41, 512)
        out1 = self.transformer_encoder(src_query_emb_VT , src_key_padding_mask = src_query_mask)
        res = self.dense(out1)
        return res

src = torch.rand((2, 32, 512), device="cuda")
print(src.shape) # torch.Size([2, 32, 512])
demo_model = DemoModel()
demo_model.eval()
with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
    print("src device: {}".format(src.get_device())) # 0, gpu
    out = demo_model(src)
    print("Out shape", out.shape)
    print("out device: ", out.get_device()) # -1, cpu

```
