### ISSUE TITLE
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false. (Using Google Colab)

### ISSUE THREAD

**Issue by maheshmouli** [pytorch/pytorch#111210]
### 🐛 Describe the bug

I'm running StableDiffusionv1.5 to pretrian on my own dataset. 
I'm using Google Colab Free GPUs. But when running the below command it throwing me this error

Using torchversion '2.1.0'
""
!accelerate launch diffusers/examples/text_to_image/train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=100 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=100 \
  --mixed_precision='fp16' \
  --learning_rate=1e-5 \
  --max_grad_norm=1 \
  --num_train_epochs=100 \
  --checkpointing_steps=100000 \
  --lr_scheduler="constant" \
  --lr_warmup_step=0 \
  --output_dir=$OUTPUT_DIR
""

Below is the GPU Version
 CUDA Version: 12.0  

Below is the entire Error:

2023-10-13 16:26:38.246709: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
10/13/2023 16:26:44 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'prediction_type', 'variance_type', 'sample_max_value', 'timestep_spacing', 'clip_sample_range', 'thresholding', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
{'force_upcast', 'scaling_factor'} was not found in config. Values will be initialized to default values.
{'resnet_skip_time_act', 'time_cond_proj_dim', 'encoder_hid_dim', 'attention_type', 'resnet_out_scale_factor', 'upcast_attention', 'addition_embed_type_num_heads', 'num_class_embeds', 'timestep_post_act', 'mid_block_only_cross_attention', 'cross_attention_norm', 'dropout', 'only_cross_attention', 'resnet_time_scale_shift', 'conv_in_kernel', 'transformer_layers_per_block', 'num_attention_heads', 'conv_out_kernel', 'addition_time_embed_dim', 'dual_cross_attention', 'time_embedding_type', 'class_embed_type', 'use_linear_projection', 'time_embedding_act_fn', 'time_embedding_dim', 'projection_class_embeddings_input_dim', 'encoder_hid_dim_type', 'class_embeddings_concat', 'mid_block_type', 'addition_embed_type'} was not found in config. Values will be initialized to default values.
{'resnet_skip_time_act', 'time_cond_proj_dim', 'encoder_hid_dim', 'attention_type', 'resnet_out_scale_factor', 'upcast_attention', 'addition_embed_type_num_heads', 'num_class_embeds', 'timestep_post_act', 'mid_block_only_cross_attention', 'cross_attention_norm', 'dropout', 'only_cross_attention', 'resnet_time_scale_shift', 'conv_in_kernel', 'transformer_layers_per_block', 'num_attention_heads', 'conv_out_kernel', 'addition_time_embed_dim', 'dual_cross_attention', 'time_embedding_type', 'class_embed_type', 'use_linear_projection', 'time_embedding_act_fn', 'time_embedding_dim', 'projection_class_embeddings_input_dim', 'encoder_hid_dim_type', 'class_embeddings_concat', 'mid_block_type', 'addition_embed_type'} was not found in config. Values will be initialized to default values.
10/13/2023 16:27:24 - INFO - __main__ - ***** Running training *****
10/13/2023 16:27:24 - INFO - __main__ -   Num examples = 65418
10/13/2023 16:27:24 - INFO - __main__ -   Num Epochs = 1
10/13/2023 16:27:24 - INFO - __main__ -   Instantaneous batch size per device = 2
10/13/2023 16:27:24 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 8
10/13/2023 16:27:24 - INFO - __main__ -   Gradient Accumulation steps = 4
10/13/2023 16:27:24 - INFO - __main__ -   Total optimization steps = 100
Steps:   0% 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/drive/MyDrive/StableDiffusion/diffusers/examples/text_to_image/train_text_to_image.py", line 1066, in <module>
    main()
  File "/content/drive/MyDrive/StableDiffusion/diffusers/examples/text_to_image/train_text_to_image.py", line 948, in main
    accelerator.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1983, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
Steps:   0% 0/100 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command 

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.120+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by maheshmouli** [comment]
![GPU](https://github.com/pytorch/pytorch/assets/22795383/4a8e182b-e53f-49c3-b702-d5a11b1cc56c)

Here is the image.

**Comment by janeyx99** [comment]
ah yea, Tesla T4 is a part of the Turing series, and based on https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/, has sm75.

This means that torch was built for a different architecture. A glance shows that your torch was built with cuda12.1 but the cuda in colab is 12.0.

**Comment by maheshmouli** [comment]
Ok, So until the cuda version is upgrade I cannot run in google colab, right ?

**Comment by janeyx99** [comment]
You can rebuild your torch for the architecture in colab. That should work too
