### ISSUE TITLE
pytorch-0.4.1 build fails on autograd test

### ISSUE THREAD

**Issue by akamaus** [pytorch/pytorch#11133]
I'm working on packaging pytorch-0.4.1 for NixOS and I stumbled upon the following test error.

```
Running test_autograd ...
............................................................................................s.........s............................................................................................................................s............................................EEEEF.s........................................................s................................................................................................................................................................ss..................................................s.E........................................................................................s...........................s......................................................................................................................................s......................s.....
======================================================================
ERROR: test_gesv (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 104, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 3475, in do_test
    check(name)
  File "test_autograd.py", line 3409, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 3332, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 214, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[-0.3519,  0.7853,  0.1334, -0.8869, -0.4107, -0.1127,  0.2516,  0.0427,
         -0.2841, -0.1315,  0.0555, -0.1238, -0.0210,  0.1398,  0.0648, -0.1272,
          0.2838,  0.0482, -0.3205, -0.1484,  0.1304, -0.2910, -0.0494,  0.3286,
          0.1522],
        [-0.1972,  0.0193,  0.3803,  0.0496, -0.6060, -0.0632,  0.0062,  0.1218,
          0.0159, -0.1941,  0.0311, -0.0030, -0.0600, -0.0078,  0.0956, -0.0713,
          0.0070,  0.1374,  0.0179, -0.2190,  0.0731, -0.0072, -0.1409, -0.0184,
          0.2245],
        [-0.1190,  0.8624,  0.3051, -0.2650, -0.4737, -0.0381,  0.2763,  0.0977,
         -0.0849, -0.1517,  0.0188, -0.1360, -0.0481,  0.0418,  0.0747, -0.0430,
          0.3117,  0.1102, -0.0958, -0.1712,  0.0441, -0.3195, -0.1130,  0.0982,
          0.1755],
        [ 0.3640, -0.1793, -0.4726, -0.1183,  0.7092,  0.1166, -0.0574, -0.1514,
         -0.0379,  0.2272, -0.0574,  0.0283,  0.0745,  0.0186, -0.1118,  0.1315,
         -0.0648, -0.1708, -0.0427,  0.2563, -0.1349,  0.0664,  0.1751,  0.0438,
         -0.2628],
        [ 0.0017, -0.3339,  0.0982,  0.6557, -0.1890,  0.0005, -0.1070,  0.0314,
          0.2100, -0.0605, -0.0003,  0.0526, -0.0155, -0.1034,  0.0298,  0.0006,
         -0.1207,  0.0355,  0.2370, -0.0683, -0.0006,  0.1237, -0.0364, -0.2429,
          0.0700],
        [ 0.0955, -0.2132, -0.0362,  0.2407,  0.1115, -0.0274,  0.0612,  0.0104,
         -0.0691, -0.0320,  0.0300, -0.0670, -0.0114,  0.0757,  0.0350, -0.0648,
          0.1446,  0.0246, -0.1633, -0.0756,  0.1864, -0.4161, -0.0707,  0.4698,
          0.2176],
        [ 0.0535, -0.0053, -0.1032, -0.0135,  0.1645, -0.0154,  0.0015,  0.0296,
          0.0039, -0.0472,  0.0168, -0.0017, -0.0324, -0.0042,  0.0517, -0.0363,
          0.0036,  0.0700,  0.0091, -0.1116,  0.1045, -0.0102, -0.2015, -0.0263,
          0.3211],
        [ 0.0323, -0.2341, -0.0828,  0.0719,  0.1286, -0.0093,  0.0672,  0.0238,
         -0.0206, -0.0369,  0.0101, -0.0736, -0.0260,  0.0226,  0.0404, -0.0219,
          0.1588,  0.0562, -0.0488, -0.0872,  0.0630, -0.4569, -0.1616,  0.1404,
          0.2509],
        [-0.0988,  0.0487,  0.1283,  0.0321, -0.1925,  0.0284, -0.0140, -0.0368,
         -0.0092,  0.0552, -0.0311,  0.0153,  0.0403,  0.0101, -0.0605,  0.0670,
         -0.0330, -0.0870, -0.0218,  0.1306, -0.1928,  0.0950,  0.2504,  0.0627,
         -0.3757],
        [-0.0005,  0.0906, -0.0266, -0.1780,  0.0513,  0.0001, -0.0260,  0.0076,
          0.0511, -0.0147, -0.0001,  0.0285, -0.0084, -0.0559,  0.0161,  0.0003,
         -0.0615,  0.0181,  0.1207, -0.0348, -0.0009,  0.1769, -0.0520, -0.3474,
          0.1001],
        [ 0.2218, -0.4949, -0.0841,  0.5589,  0.2588,  0.3033, -0.6769, -0.1150,
          0.7644,  0.3540,  0.2494, -0.5565, -0.0945,  0.6284,  0.2910, -0.3366,
          0.7513,  0.1276, -0.8484, -0.3928,  0.0710, -0.1584, -0.0269,  0.1789,
          0.0829],
        [ 0.1243, -0.0122, -0.2397, -0.0313,  0.3819,  0.1700, -0.0167, -0.3278,
         -0.0428,  0.5223,  0.1397, -0.0137, -0.2695, -0.0352,  0.4294, -0.1887,
          0.0185,  0.3638,  0.0475, -0.5797,  0.0398, -0.0039, -0.0767, -0.0100,
          0.1223],
        [ 0.0750, -0.5435, -0.1923,  0.1670,  0.2985,  0.1025, -0.7433, -0.2630,
          0.2284,  0.4083,  0.0843, -0.6111, -0.2162,  0.1877,  0.3356, -0.1138,
          0.8250,  0.2918, -0.2535, -0.4531,  0.0240, -0.1740, -0.0615,  0.0535,
          0.0956],
        [-0.2294,  0.1130,  0.2979,  0.0745, -0.4469, -0.3137,  0.1546,  0.4074,
          0.1020, -0.6113, -0.2579,  0.1271,  0.3349,  0.0838, -0.5025,  0.3482,
         -0.1716, -0.4521, -0.1131,  0.6784, -0.0734,  0.0362,  0.0954,  0.0239,
         -0.1431],
        [-0.0011,  0.2104, -0.0619, -0.4132,  0.1191, -0.0015,  0.2878, -0.0846,
         -0.5652,  0.1629, -0.0012,  0.2366, -0.0696, -0.4646,  0.1339,  0.0016,
         -0.3194,  0.0939,  0.6272, -0.1808, -0.0003,  0.0674, -0.0198, -0.1323,
          0.0381],
        [-0.7464,  1.6657,  0.2829, -1.8810, -0.8710,  0.0600, -0.1339, -0.0227,
          0.1512,  0.0700, -0.5586,  1.2466,  0.2117, -1.4077, -0.6518,  0.0677,
         -0.1510, -0.0256,  0.1705,  0.0790,  0.3959, -0.8835, -0.1501,  0.9977,
          0.4620],
        [-0.4183,  0.0410,  0.8067,  0.1053, -1.2853,  0.0336, -0.0033, -0.0648,
         -0.0085,  0.1033, -0.3130,  0.0307,  0.6037,  0.0788, -0.9619,  0.0379,
         -0.0037, -0.0731, -0.0095,  0.1165,  0.2219, -0.0218, -0.4279, -0.0558,
          0.6818],
        [-0.2523,  1.8291,  0.6471, -0.5620, -1.0046,  0.0203, -0.1470, -0.0520,
          0.0452,  0.0807, -0.1888,  1.3689,  0.4842, -0.4206, -0.7518,  0.0229,
         -0.1658, -0.0587,  0.0509,  0.0911,  0.1338, -0.9702, -0.3432,  0.2981,
          0.5329],
        [ 0.7720, -0.3804, -1.0024, -0.2509,  1.5041, -0.0620,  0.0306,  0.0806,
          0.0202, -0.1209,  0.5778, -0.2847, -0.7502, -0.1877,  1.1256, -0.0700,
          0.0345,  0.0909,  0.0227, -0.1363, -0.4095,  0.2018,  0.5317,  0.1331,
         -0.7978],
        [ 0.0036, -0.7082,  0.2082,  1.3907, -0.4008, -0.0003,  0.0569, -0.0167,
         -0.1118,  0.0322,  0.0027, -0.5300,  0.1558,  1.0408, -0.3000, -0.0003,
          0.0642, -0.0189, -0.1261,  0.0363, -0.0019,  0.3756, -0.1104, -0.7377,
          0.2126],
        [-0.4169,  0.9304,  0.1580, -1.0507, -0.4865, -0.1176,  0.2625,  0.0446,
         -0.2964, -0.1373, -0.0849,  0.1895,  0.0322, -0.2140, -0.0991,  0.2586,
         -0.5772, -0.0980,  0.6518,  0.3018,  0.2081, -0.4645, -0.0789,  0.5245,
          0.2429],
        [-0.2336,  0.0229,  0.4506,  0.0588, -0.7180, -0.0659,  0.0065,  0.1271,
          0.0166, -0.2026, -0.0476,  0.0047,  0.0918,  0.0120, -0.1462,  0.1449,
         -0.0142, -0.2795, -0.0365,  0.4454,  0.1166, -0.0114, -0.2249, -0.0294,
          0.3584],
        [-0.1409,  1.0217,  0.3614, -0.3139, -0.5611, -0.0398,  0.2883,  0.1020,
         -0.0886, -0.1583, -0.0287,  0.2081,  0.0736, -0.0639, -0.1143,  0.0874,
         -0.6338, -0.2242,  0.1947,  0.3481,  0.0704, -0.5101, -0.1804,  0.1567,
          0.2801],
        [ 0.4312, -0.2125, -0.5599, -0.1401,  0.8402,  0.1217, -0.0599, -0.1580,
         -0.0395,  0.2371,  0.0878, -0.0433, -0.1140, -0.0285,  0.1711, -0.2675,
          0.1318,  0.3474,  0.0869, -0.5212, -0.2153,  0.1061,  0.2795,  0.0700,
         -0.4194],
        [ 0.0020, -0.3956,  0.1163,  0.7768, -0.2239,  0.0006, -0.1116,  0.0328,
          0.2192, -0.0632,  0.0004, -0.0806,  0.0237,  0.1582, -0.0456, -0.0013,
          0.2454, -0.0721, -0.4819,  0.1389, -0.0010,  0.1975, -0.0581, -0.3878,
          0.1118]])
analytical:tensor([[-0.3519,  0.7853,  0.1334, -0.8869, -0.4107, -0.1127,  0.2516,  0.0427,
         -0.2841, -0.1315,  0.0555, -0.1238, -0.0210,  0.1398,  0.0648, -0.1272,
          0.2838,  0.0482, -0.3205, -0.1484,  0.1304, -0.2910, -0.0494,  0.3286,
         -0.1436],
        [-0.1972,  0.0193,  0.3803,  0.0496, -0.6060, -0.0632,  0.0062,  0.1218,
          0.0159, -0.1941,  0.0311, -0.0030, -0.0600, -0.0078,  0.0956, -0.0713,
          0.0070,  0.1374,  0.0179, -0.2190,  0.0731, -0.0072, -0.1409, -0.0184,
         -0.3407],
        [-0.1190,  0.8624,  0.3051, -0.2650, -0.4737, -0.0381,  0.2763,  0.0977,
         -0.0849, -0.1517,  0.0188, -0.1360, -0.0481,  0.0418,  0.0747, -0.0430,
          0.3117,  0.1102, -0.0958, -0.1712,  0.0441, -0.3195, -0.1130,  0.0982,
         -0.2718],
        [ 0.3640, -0.1793, -0.4726, -0.1183,  0.7092,  0.1166, -0.0574, -0.1514,
         -0.0379,  0.2272, -0.0574,  0.0283,  0.0745,  0.0186, -0.1118,  0.1315,
         -0.0648, -0.1708, -0.0427,  0.2563, -0.1349,  0.0664,  0.1751,  0.0438,
          0.4181],
        [ 0.0017, -0.3339,  0.0982,  0.6557, -0.1890,  0.0005, -0.1070,  0.0314,
          0.2100, -0.0605, -0.0003,  0.0526, -0.0155, -0.1034,  0.0298,  0.0006,
         -0.1207,  0.0355,  0.2370, -0.0683, -0.0006,  0.1237, -0.0364, -0.2429,
         -0.0919],
        [ 0.0955, -0.2132, -0.0362,  0.2407,  0.1115, -0.0274,  0.0612,  0.0104,
         -0.0691, -0.0320,  0.0300, -0.0670, -0.0114,  0.0757,  0.0350, -0.0648,
          0.1446,  0.0246, -0.1633, -0.0756,  0.1864, -0.4161, -0.0707,  0.4698,
          0.2978],
        [ 0.0535, -0.0053, -0.1032, -0.0135,  0.1645, -0.0154,  0.0015,  0.0296,
          0.0039, -0.0472,  0.0168, -0.0017, -0.0324, -0.0042,  0.0517, -0.0363,
          0.0036,  0.0700,  0.0091, -0.1116,  0.1045, -0.0102, -0.2015, -0.0263,
          0.4745],
        [ 0.0323, -0.2341, -0.0828,  0.0719,  0.1286, -0.0093,  0.0672,  0.0238,
         -0.0206, -0.0369,  0.0101, -0.0736, -0.0260,  0.0226,  0.0404, -0.0219,
          0.1588,  0.0562, -0.0488, -0.0872,  0.0630, -0.4569, -0.1616,  0.1404,
          0.3724],
        [-0.0988,  0.0487,  0.1283,  0.0321, -0.1925,  0.0284, -0.0140, -0.0368,
         -0.0092,  0.0552, -0.0311,  0.0153,  0.0403,  0.0101, -0.0605,  0.0670,
         -0.0330, -0.0870, -0.0218,  0.1306, -0.1928,  0.0950,  0.2504,  0.0627,
         -0.5605],
        [-0.0005,  0.0906, -0.0266, -0.1780,  0.0513,  0.0001, -0.0260,  0.0076,
          0.0511, -0.0147, -0.0001,  0.0285, -0.0084, -0.0559,  0.0161,  0.0003,
         -0.0615,  0.0181,  0.1207, -0.0348, -0.0009,  0.1769, -0.0520, -0.3474,
          0.1441],
        [ 0.2218, -0.4949, -0.0841,  0.5589,  0.2588,  0.3033, -0.6769, -0.1150,
          0.7644,  0.3540,  0.2494, -0.5565, -0.0945,  0.6284,  0.2910, -0.3366,
          0.7513,  0.1276, -0.8484, -0.3928,  0.0710, -0.1584, -0.0269,  0.1789,
          0.2692],
        [ 0.1243, -0.0122, -0.2397, -0.0313,  0.3819,  0.1700, -0.0167, -0.3278,
         -0.0428,  0.5223,  0.1397, -0.0137, -0.2695, -0.0352,  0.4294, -0.1887,
          0.0185,  0.3638,  0.0475, -0.5797,  0.0398, -0.0039, -0.0767, -0.0100,
          0.4785],
        [ 0.0750, -0.5435, -0.1923,  0.1670,  0.2985,  0.1025, -0.7433, -0.2630,
          0.2284,  0.4083,  0.0843, -0.6111, -0.2162,  0.1877,  0.3356, -0.1138,
          0.8250,  0.2918, -0.2535, -0.4531,  0.0240, -0.1740, -0.0615,  0.0535,
          0.3774],
        [-0.2294,  0.1130,  0.2979,  0.0745, -0.4469, -0.3137,  0.1546,  0.4074,
          0.1020, -0.6113, -0.2579,  0.1271,  0.3349,  0.0838, -0.5025,  0.3482,
         -0.1716, -0.4521, -0.1131,  0.6784, -0.0734,  0.0362,  0.0954,  0.0239,
         -0.5721],
        [-0.0011,  0.2104, -0.0619, -0.4132,  0.1191, -0.0015,  0.2878, -0.0846,
         -0.5652,  0.1629, -0.0012,  0.2366, -0.0696, -0.4646,  0.1339,  0.0016,
         -0.3194,  0.0939,  0.6272, -0.1808, -0.0003,  0.0674, -0.0198, -0.1323,
          0.1402],
        [-0.7464,  1.6657,  0.2829, -1.8810, -0.8710,  0.0600, -0.1339, -0.0227,
          0.1512,  0.0700, -0.5586,  1.2466,  0.2117, -1.4077, -0.6518,  0.0677,
         -0.1510, -0.0256,  0.1705,  0.0790,  0.3959, -0.8835, -0.1501,  0.9977,
         -0.1653],
        [-0.4183,  0.0410,  0.8067,  0.1053, -1.2853,  0.0336, -0.0033, -0.0648,
         -0.0085,  0.1033, -0.3130,  0.0307,  0.6037,  0.0788, -0.9619,  0.0379,
         -0.0037, -0.0731, -0.0095,  0.1165,  0.2219, -0.0218, -0.4279, -0.0558,
         -0.5171],
        [-0.2523,  1.8291,  0.6471, -0.5620, -1.0046,  0.0203, -0.1470, -0.0520,
          0.0452,  0.0807, -0.1888,  1.3689,  0.4842, -0.4206, -0.7518,  0.0229,
         -0.1658, -0.0587,  0.0509,  0.0911,  0.1338, -0.9702, -0.3432,  0.2981,
         -0.4158],
        [ 0.7720, -0.3804, -1.0024, -0.2509,  1.5041, -0.0620,  0.0306,  0.0806,
          0.0202, -0.1209,  0.5778, -0.2847, -0.7502, -0.1877,  1.1256, -0.0700,
          0.0345,  0.0909,  0.0227, -0.1363, -0.4095,  0.2018,  0.5317,  0.1331,
          0.6462],
        [ 0.0036, -0.7082,  0.2082,  1.3907, -0.4008, -0.0003,  0.0569, -0.0167,
         -0.1118,  0.0322,  0.0027, -0.5300,  0.1558,  1.0408, -0.3000, -0.0003,
          0.0642, -0.0189, -0.1261,  0.0363, -0.0019,  0.3756, -0.1104, -0.7377,
         -0.1308],
        [-0.4169,  0.9304,  0.1580, -1.0507, -0.4865, -0.1176,  0.2625,  0.0446,
         -0.2964, -0.1373, -0.0849,  0.1895,  0.0322, -0.2140, -0.0991,  0.2586,
         -0.5772, -0.0980,  0.6518,  0.3018,  0.2081, -0.4645, -0.0789,  0.5245,
         -0.1075],
        [-0.2336,  0.0229,  0.4506,  0.0588, -0.7180, -0.0659,  0.0065,  0.1271,
          0.0166, -0.2026, -0.0476,  0.0047,  0.0918,  0.0120, -0.1462,  0.1449,
         -0.0142, -0.2795, -0.0365,  0.4454,  0.1166, -0.0114, -0.2249, -0.0294,
         -0.3113],
        [-0.1409,  1.0217,  0.3614, -0.3139, -0.5611, -0.0398,  0.2883,  0.1020,
         -0.0886, -0.1583, -0.0287,  0.2081,  0.0736, -0.0639, -0.1143,  0.0874,
         -0.6338, -0.2242,  0.1947,  0.3481,  0.0704, -0.5101, -0.1804,  0.1567,
         -0.2498],
        [ 0.4312, -0.2125, -0.5599, -0.1401,  0.8402,  0.1217, -0.0599, -0.1580,
         -0.0395,  0.2371,  0.0878, -0.0433, -0.1140, -0.0285,  0.1711, -0.2675,
          0.1318,  0.3474,  0.0869, -0.5212, -0.2153,  0.1061,  0.2795,  0.0700,
          0.3872],
        [ 0.0020, -0.3956,  0.1163,  0.7768, -0.2239,  0.0006, -0.1116,  0.0328,
          0.2192, -0.0632,  0.0004, -0.0806,  0.0237,  0.1582, -0.0456, -0.0013,
          0.2454, -0.0721, -0.4819,  0.1389, -0.0010,  0.1975, -0.0581, -0.3878,
         -0.0801]])


======================================================================
ERROR: test_gesv_batched (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 104, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 3475, in do_test
    check(name)
  File "test_autograd.py", line 3409, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 3332, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 214, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-5.2063e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -5.2063e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -5.2063e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.0869e-01,
          0.0000e+00,  4.1437e+05],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -3.0869e-01,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00, -3.0869e-01]])
analytical:tensor([[-5.2063,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -5.2063,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -5.2063,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [-0.0000, -0.0000, -0.0000,  ..., -0.3087, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.3087, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.3087]])


======================================================================
ERROR: test_gesv_batched_broadcast_A (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 104, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 3475, in do_test
    check(name)
  File "test_autograd.py", line 3409, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 3332, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 214, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-0.0583,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0583,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0583,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.3674,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.3674,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.3674]])
analytical:tensor([[-0.0583,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0583,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0583,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [-0.0000, -0.0000, -0.0000,  ...,  0.3674, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000,  0.3674, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000,  0.3674]])


======================================================================
ERROR: test_gesv_batched_broadcast_b (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 104, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 3475, in do_test
    check(name)
  File "test_autograd.py", line 3409, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 3332, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 214, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-0.2197,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.2197,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.2197,  ...,  0.4906,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.5873,  ..., -0.1934,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.1934,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.1934]])
analytical:tensor([[-0.2197,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.2197,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.2197,  ...,  0.4906,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.5873,  ..., -0.1934,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.1934,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.1934]])


======================================================================
ERROR: test_potrf (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 104, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 1914, in test_potrf
    run_test(upper=True)
  File "test_autograd.py", line 1911, in run_test
    gradcheck(func, [root])
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 217, in gradcheck
    return fail_test('Backward is not reentrant, i.e., running backward with same '
  File "/nix/store/l8kg9xdmyc51qji5ywh5ad9hakmlc9fn-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
    raise RuntimeError(msg)
RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient

======================================================================
FAIL: test_gesv_batched_dims (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 104, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 3475, in do_test
    check(name)
  File "test_autograd.py", line 3400, in check
    self.assertEqual(unpack_variables(output_variable), output_tensor)
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 352, in assertEqual
    self.assertEqual(x_, y_, prec, message)
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 344, in assertEqual
    assertTensorsEqual(x, y)
  File "/tmp/nix-build-python3.6-pytorch-0.4.1.drv-0/source/test/common.py", line 336, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(0.7946, grad_fn=<MaxBackward1>) not less than or equal to 1e-05 :

----------------------------------------------------------------------
Ran 831 tests in 69.093s

FAILED (failures=1, errors=5, skipped=12)
Traceback (most recent call last):
  File "test/run_test.py", line 345, in <module>
    main()
  File "test/run_test.py", line 337, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed!
```

- OS: nixos-unstable
- PyTorch version: 0.4.1 (rev a24163a95edb)
- Python version: 3.6
- CUDA/cuDNN version: CPU-only
- GCC version (if compiling from source): 7.3.0
- CMake version: 3.11.2

Any ideas what might went wrong?

**Comment by vishwakftw** [comment]
If you have NumPy installed, could you please show the output for `numpy.__config__.show()`?

**Comment by vishwakftw** [comment]
Irrespective of that, the values displayed for the `analytic` and `numerical` Jacobians seem to be close.

**Comment by akamaus** [comment]
```
>>> import numpy
>>> numpy.__config__.show()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/nix/store/ngsyhj7zy7g2ndsww6sq6m5h625m01az-openblas-0.3.1/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/nix/store/ngsyhj7zy7g2ndsww6sq6m5h625m01az-openblas-0.3.1/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/nix/store/ngsyhj7zy7g2ndsww6sq6m5h625m01az-openblas-0.3.1/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/nix/store/ngsyhj7zy7g2ndsww6sq6m5h625m01az-openblas-0.3.1/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by vishwakftw** [comment]
I think this is an OpenBLAS issue, and I believe OpenBLAS does fail some LAPACK tests.

**Comment by akamaus** [comment]
I updated openblas to 0.3.3, error is gone.
