### ISSUE TITLE
Custom torch.utils.data.Dataset causes DataLoader crash on Windows Machine

### ISSUE THREAD

**Issue by liona24** [pytorch/pytorch#11139]
When I try to use a custom dataset in conjunction with a dataloader and multiple workers an error occurs.

It only happens on my Windows 10 64 bit machine. 

Minimal working example:

```python
import torch
import torch.utils.data as data

class CDataset(data.Dataset):
    def __init__(self):
        data.Dataset.__init__(self)

    def __len__(self):
        return 4

    def __getitem__(self, i):
        return torch.randn(2, 3)

dataset = CDataset()

# num_workers > 1
loader = data.DataLoader(dataset, num_workers=2)

next(iter(loader))  # <-- error here
```

It produces a rather lengthy error message, depending on the number of workers specified it repeats itself:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lion\test.py", line 17, in <module>
    next(iter(loader))
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "E:\Users\Lion\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

## System Info
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Education
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.13.3)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.1)
[conda] pytorch                   0.3.0                py36_0.3.0    peterjc123
[conda] pytorch-cpu               0.4.1           py36_cpuhe774522_1    pytorch

**Comment by fmassa** [comment]
I believe this is a Windows-specific problem, and I think the solution is to wrap your code in `if __name__ == '__main__':`, as mentioned in the error message that you showed us.
More info in this thread https://stackoverflow.com/questions/33038209/python-multiprocessing-fails-for-example-code

I'm closing the issue, feel free to comment if this doesn't solve the problem for you

**Comment by liona24** [comment]
Thank you, I guess I have to work around it for now. 

Though I wonder why it only occurs in custom `Datasets` and not when using let's say a `torch.utils.data.TensorDataset`?

**Comment by fmassa** [comment]
I have no idea, but I'd say that the fact that it works with `TensorDataset` might be the exception, rather than the norm. But I don't have experience working on Windows, so I can't say much
