### ISSUE TITLE
Insufficient hasattr guards on user defined objects

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#111522]
### 🐛 Describe the bug

```
import torch
import torch._dynamo

@torch.compile(backend="eager", fullgraph=True)
def f(x, y):
    return x + y.a

class A:
    a = 2

print(f(torch.zeros(2), A()))

del A.a

print(f(torch.zeros(2), A()))
```

produces

```
ERROR RUNNING GUARDS f /data/users/ezyang/a/pytorch/a.py:4
lambda L, **___kwargs_ignored:
  ___guarded_code.valid and
  ___check_global_state() and
  hasattr(L['x'], '_dynamo_dynamic_indices') == False and
  ___check_type_id(L['y'], 102721216) and
  ___check_type_id(L['y'].a, 7640416) and
  L['y'].a == 2 and
  utils_device.CURRENT_DEVICE == None and
  ___skip_backend_check() or ___current_backend() == ___lookup_backend(140059152699776) and
  ___check_tensors(L['x'], tensor_check_names=tensor_check_names)
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/a.py", line 15, in <module>
    print(f(torch.zeros(2), A()))
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "<string>", line 13, in guard
AttributeError: 'A' object has no attribute 'a'
```

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @wconstab @aakhundov

**Comment by voznesenskym** [comment]
We know this - we actually lack hasattrs all over the place. We should check if the eager guarding work will fix this.

**Comment by mlazos** [comment]
assigning @jansel arbitrarily

**Comment by jon-chuang** [comment]
I also have a failure to guard for attribute identity.

```python
class MyCallable:
    def __call__(self, x):
        return x + 1

def fn(x):
    return MyCallable()(x)

fn_opt = torch.compile(fn, backend="eager")
print(fn_opt(torch.zeros(1)))

def patch__call__(obj, x):
    return x + 2

MyCallable.__call__ = patch__call__
print(fn_opt(torch.zeros(1)))  # Incorrectly 1, should be 2
```

**Comment by ezyang** [comment]
still fails as of 0a1b3be2163ea99633f95c4927bd816eb713e9bd
