### ISSUE TITLE
Building docs fails

### ISSUE THREAD

**Issue by 45mm** [pytorch/pytorch#111560]
### 🐛 Describe the bug

Error:
```
Traceback (most recent call last):
  File "/home/45mm/src/view/pytorch/docs/source/scripts/exportdb/generate_example_rst.py", line 182, in <module>
    generate_rst()
  File "/home/45mm/src/view/pytorch/docs/source/scripts/exportdb/generate_example_rst.py", line 168, in generate_rst
    doc_contents = generate_example_rst(example_case)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/45mm/src/view/pytorch/docs/source/scripts/exportdb/generate_example_rst.py", line 76, in generate_example_rst
    dynamic_shapes=example_case.dynamic_shapes,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExportCase' object has no attribute 'dynamic_shapes'
make: *** [Makefile:28: exportdb] Error 1
(pytorch-docs) [Done in 8.941540002822876s;  Exit Status: 2]
```

Steps followed to build:
```bash
conda create --name pytorch-docs pip
conda activate pytorch-docs
cd docs && pip install -r requirements.txt
pip install torch
sudo pacman -Sl npm
sudo npm -g install katex
make html
```

The error is obviously related to the `exportdb` target; if I comment it out:
```diff
diff --git a/docs/Makefile b/docs/Makefile
index c6df057d8a6..8e647a273df 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -45,7 +45,7 @@ html-stable:
 
 # Catch-all target: route all unknown targets to Sphinx using the new
 # "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
-%: Makefile figures onnx opset exportdb
+%: Makefile figures onnx opset # exportdb
 	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
 
 clean:
```
...then the build completes (albeit with many warnings/errors; I have attached the full output below)
[html.log](https://github.com/pytorch/pytorch/files/13040244/html.log)

Additionally, the `man ` target fails even after doing this. I have attached the full output:
[man.log](https://github.com/pytorch/pytorch/files/13040202/man.log)
And the Sphinx log -
[sphinx-err-sggaea8k.log](https://github.com/pytorch/pytorch/files/13040191/sphinx-err-sggaea8k.log)

Note that I did not do a full build of Pytorch; only the docs.

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 13.2.1 20230801
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.38

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.5.7-arch1-1-x86_64-with-glibc2.38
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.1.0
[pip3] triton==2.1.0
[conda] numpy                     1.26.1                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by kit1980** [comment]
This PR is related https://github.com/pytorch/pytorch/pull/110143

**Comment by angelayi** [comment]
I think it's because you're on torch version 2.1.0 but you're building docs on main. https://github.com/pytorch/pytorch/pull/110143 adds `ExportCase.dynamic_shapes`.

**Comment by kit1980** [comment]
I'm going to close this as updating PyTorch resolves the problem.
