### ISSUE TITLE
Sparse Tensor Sum Still Does Not Work for PyTorch Geometric

### ISSUE THREAD

**Issue by puririshi98** [pytorch/pytorch#111509]
### 🐛 Describe the bug

original issue: https://github.com/pytorch/pytorch/issues/98796
There was a PR to fix it: https://github.com/pytorch/pytorch/commit/a54043516fad1a37134f280f3e75f85a5b2daa13

However the issue still persists for this example: https://github.com/pyg-team/pytorch_geometric/blob/master/examples/correct_and_smooth.py
```
python3 example/correct_and_smooth.py
...
Epoch: 300, Loss: 0.9754, Train: 0.7694, Val: 0.7390, Test: 0.5940
Traceback (most recent call last):
  File "/workspace/examples/correct_and_smooth.py", line 72, in <module>
    deg = adj_t.sum(dim=1).to(torch.float)
RuntimeError: reduction operations on CSR tensors with keepdim=False is unsupported
```

### Versions

```
python collect_env.py
Collecting environment information...
PyTorch version: 2.1.0a0+32f93b1
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000

Nvidia driver version: 530.41.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        4
CPU max MHz:                     4500.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7599.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        8 MiB (8 instances)
L3 cache:                        16.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.2
[pip3] onnx==1.14.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0a0+32f93b1
[pip3] torch_geometric==2.4.0
[pip3] torch-tensorrt==0.0.0
[pip3] torchdata==0.6.0+5bbcd77
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0a0
[pip3] triton==2.1.0+e621604
[pip3] tritonclient==2.38.0.69485441
[conda] Could not collect
```

**Comment by amjames** [comment]
The sum is over one of the sparse dims, keep dims is required right now because we can't eliminate a sparse dim with CSR layout it requires two sparse dims. 

So, in order to support `keep_dims=False` the return becomes COO. I don't see any problem with that out of hand except that we usually preserve layout except for the obvious cases like `to_dense` etc. 

The alternative would be to first see if another dimension exists to use to maintain CSR, and then only going to COO if the result is 1 dimensional.

**Comment by puririshi98** [comment]
cc @rusty1s do you think any of these solutions be viable

**Comment by rusty1s** [comment]
Oh, I thought `torch.sparse.tensor.sum()` would return a dense tensor, but I guess it makes also sense to try to preserve the layout. We can fix the example on our end by just running with `keep_dims=True`.

**Comment by puririshi98** [comment]
if i do:
```
adj_t = data.adj_t.to(device)
deg = adj_t.sum(dim=1, keepdim=True).to(torch.float)
deg_inv_sqrt = deg.pow_(-0.5)
deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
DAD = deg_inv_sqrt.view(-1, 1) * adj_t * deg_inv_sqrt.view(1, -1)
DA = deg_inv_sqrt.view(-1, 1) * deg_inv_sqrt.view(-1, 1) * adj_t
```

```
then   File "/workspace/examples/correct_and_smooth.py", line 73, in <module>
    deg_inv_sqrt = deg.pow_(-0.5)
RuntimeError: unsupported tensor layout: SparseCsr
```

**Comment by rusty1s** [comment]
You need to make `deg` a dense tensor after the `sum` call.

**Comment by puririshi98** [comment]
thanks,
```
adj_t = data.adj_t.to(device)
deg = adj_t.sum(dim=1, keepdim=True).to(torch.float).to_dense()
deg_inv_sqrt = deg.pow_(-0.5)
deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
DAD = deg_inv_sqrt.view(-1, 1) * adj_t * deg_inv_sqrt.view(1, -1)
DA = deg_inv_sqrt.view(-1, 1) * deg_inv_sqrt.view(-1, 1) * adj_t
```
->
```
Traceback (most recent call last):
  File "/workspace/examples/correct_and_smooth.py", line 75, in <module>
    DAD = deg_inv_sqrt.view(-1, 1) * adj_t * deg_inv_sqrt.view(1, -1)
RuntimeError: sparse_mask(): operands have incompatible sizes; self has size [2449029, 1] but mask has size [2449029, 2449029]
```

i can remove the views and still same:
```
  File "/workspace/examples/correct_and_smooth.py", line 75, in <module>
    DAD = deg_inv_sqrt * adj_t * deg_inv_sqrt
RuntimeError: sparse_mask(): operands have incompatible sizes; self has size [2449029, 1] but mask has size [2449029, 2449029]
```

**Comment by amjames** [comment]
Actually dense would be another option here. Probably the best default behavior. 

Really we need some way to configure/deduce what the "correct" choice is here because if you have very localized values in a very sparse very large tensor you could have a sparse result. 


And yes the short-term work around here would be keep_dims=True and `to_dense()`.

**Comment by puririshi98** [comment]
i tried keepdim=True and to_dense but still error
`deg = adj_t.sum(dim=1, keepdim=True).to(torch.float).to_dense()`
->
`RuntimeError: sparse_mask(): operands have incompatible sizes; self has size [2449029, 1] but mask has size [2449029, 2449029]
`

**Comment by amjames** [comment]
@puririshi98 I'm looking into that latest problem right now, but the dataset used by this example is quite large and it is taking a while to pull it down. If you could provide a smaller reproduction it would help me move a bit faster.

**Comment by puririshi98** [comment]
```
import torch
from torch_geometric.datasets import FakeDataset
import torch_geometric.transforms as T
device='cuda'
data = FakeDataset(transform=T.ToSparseTensor())[0]
print(data)
adj_t = data.adj_t.to(device)
deg = adj_t.sum(dim=1).to(torch.float)
deg_inv_sqrt = deg.pow_(-0.5)
deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
DAD = deg_inv_sqrt.view(-1, 1) * adj_t * deg_inv_sqrt.view(1, -1)
DA = deg_inv_sqrt.view(-1, 1) * deg_inv_sqrt.view(-1, 1) * adj_t
```

->
```
root@riship-dt:/workspace# vim x; mv x x.py; python3 x.py
/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/sparse.py:264: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  adj = torch.sparse_csr_tensor(
Data(y=[1168], x=[1168, 64], adj_t=[1168, 1168])
Traceback (most recent call last):
  File "/workspace/x.py", line 8, in <module>
    deg = adj_t.sum(dim=1).to(torch.float)
RuntimeError: reduction operations on CSR tensors with keepdim=False is unsupported
```

**Comment by amjames** [comment]
We are lacking support for broadcasting in some ops including `sparse_mask` (used to implement pointwise `mul`) 

A work around here would be to manually broadcast the dense multipliers.
 
```python
left_deg_inv_sqrt = torch.broadcast_to(deg_inv_sqrt.view(-1, 1), adj_t.shape)
right_deg_inv_sqrt = torch.broadcast_to(dev_inv_sqrt.view(1, -1), adj_t.shape)

DAD = left_deg_inv_sqrt * adj_t * right_deg_inv_sqrt
DA = left_deg_inv_sqrt * left_deg_inv_sqrt * adj_t

```

**Comment by puririshi98** [comment]
```
root@riship-dt:/workspace# python3 examples/correct_and_smooth.py 
/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/sparse.py:264: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  adj = torch.sparse_csr_tensor(
Epoch: 001, Loss: 4.0874, Train: 0.3783, Val: 0.3772, Test: 0.3172
Epoch: 002, Loss: 3.4114, Train: 0.4685, Val: 0.4676, Test: 0.3805
Traceback (most recent call last):
  File "/workspace/examples/correct_and_smooth.py", line 79, in <module>
    DA = left_deg_inv_sqrt * left_deg_inv_sqrt * adj_t
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22343.33 GiB. GPU 0 has a total capacty of 23.68 GiB of which 16.81 GiB is free. Process 10073 has 6.87 GiB memory in use. Of the allocated memory 4.71 GiB is allocated by PyTorch, and 1.91 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
this causes way too much memory to be used and is not a viable option it seems. what is the timeline for supporting the original usage which for https://github.com/rusty1s/pytorch_sparse is much more memory efficient

**Comment by puririshi98** [comment]
@amjames following up on this

**Comment by puririshi98** [comment]
@amjames checking in if this is something we can get fixed sometime early next year

**Comment by cpuhrsch** [comment]
@amjames - Can you look into adding support for this to sparse_mask please?

@puririshi98 - Does the workaround help you migrate the issue?

**Comment by puririshi98** [comment]
the work around doesn't work as explained above
