### ISSUE TITLE
[JIT] torch.einsum not supported by JIT tracer

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#11157]
## Issue description

We are using the `torch.einsum` operation in many Pyro models (e.g. `HMM`), and it appears that the JIT tracer does not currently support the `einsum` operation. cc. @t-vi, @apaszke, @fritzo.

## Code example

The following example:

```python
@torch.jit.trace(torch.ones(2, 3), torch.ones(2, 3))
def fn(x, y):
    return torch.einsum('ab,ab->b', [x, y])


fn(torch.ones(2, 3), torch.ones(2, 3))
```

throws an error on a recent PyTorch commit:

```
Traceback (most recent call last):
  File "examples/ein.py", line 4, in <module>
    @torch.jit.trace(torch.ones(2, 3), torch.ones(2, 3))
  File "/Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages/torch/jit/__init__.py", line 290, in wrapper
    module._create_method_from_trace('forward', func, tuple(args))
  File "examples/ein.py", line 6, in fn
    return torch.einsum('ab,ab->b', [x, y])
  File "/Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages/torch/functional.py", line 239, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: Found an unsupported argument type in the JIT tracer. File a bug report.
```

## System Info

```
  $ python collect_env.py
Collecting environment information...
PyTorch version: 0.5.0a0+72f91b1
Is debug build: Yes
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.0)
[pip] torch (0.5.0a0+e449a27)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] torch                     0.5.0a0+e449a27           <pip>
[conda] torch                     0.5.0a0+cb32e38           <pip>
[conda] torch                     0.5.0a0+c98d748           <pip>
[conda] torch                     0.5.0a0+64a6003           <pip>
[conda] torch                     0.5.0a0+72f91b1           <pip>
[conda] torch                     0.5.0a0+6456b94           <pip>
[conda] torch                     0.5.0a0+cd53b78           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

**Comment by fritzo** [comment]
:+1: We just switched to using `einsum` for much of Pyro's linear algebra. We'd love JIT support!

**Comment by zou3519** [comment]
The tracer doesn't support strings right now.

And here's the script-mode error: (it looks like we're not registering the einsum op despite it being a native function, probably because it has a string arg):
```
In [1]: import torch
   ...: @torch.jit.script
   ...: def fn(x, y):
   ...:     return torch.einsum('i,j->ij', x, y)
   ...:
   ...:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-9e23e805a0d0> in <module>()
      1 import torch
----> 2 @torch.jit.script
      3 def fn(x, y):
      4     return torch.einsum('i,j->ij', x, y)

~/pt/scratch/torch/jit/__init__.py in script(fn, optimize, _frames_up)
    349     rcb = createResolutionCallback(_frames_up + 1)
    350     ast = get_jit_ast(fn, is_method=False)
--> 351     graph = _jit_script_compile(ast, rcb)
    352     mod = ScriptModule()
    353     mod._create_method_from_graph('forward', graph)

RuntimeError:
unknown builtin op:
@torch.jit.script
def fn(x, y):
    return torch.einsum('i,j->ij', x, y)
           ~~~~~~~~~~~~ <--- HERE
```

**Comment by neerajprad** [comment]
Thanks for explaining, @zou3519.

**Comment by fritzo** [comment]
@zou3519 would it be possible to pass the string as a `ByteTensor`? I guess we could register two variants of `einsum`: one with string and one with `ByteTensor`, and only support one in the jit?

**Comment by apaszke** [comment]
Actually it should be a trivial patch to support this (need to change `addInputs` in `torch/csrc/jit/tracer.cpp`). We do have strings as first class values in the JIT right now, and they can be embedded as constants in the graphs.

**Comment by apaszke** [comment]
@fritzo we can try to squeeze that in before the release. Can you try adding `check_trace=False` to `torch.jit.trace`?

**Comment by fritzo** [comment]
@apaszke after setting `check_trace=False1` the jitted function dies with a schema error
```py
    def forward(self, *args, **kwargs):
>       return self._get_method('forward')(*args, **kwargs)
E       RuntimeError:
E
E       Schema not found for node. File a bug report.
E       Node: %4 : Dynamic = aten::einsum(%2, %3)
E
E       Input types:string, Dynamic[]
E       candidates were:
E       :
E       /Users/fritzobermeyer/pytorch-dev/torch/functional.py(240): einsum
E       /Users/fritzobermeyer/pytorch-dev/test/test_jit_einsum.py(9): fn
```
Here is my my code and test: https://github.com/probtorch/pytorch/pull/151/files
Here is the full error:
<details>
```
$ pytest -v test/test_jit_einsum.py
======================================================= test session starts ========================================================
platform darwin -- Python 2.7.14, pytest-3.7.1, py-1.5.2, pluggy-0.7.1 -- /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/bin/python
cachedir: .pytest_cache
benchmark: 3.1.1 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/fritzobermeyer/pytorch-dev, inifile:
plugins: xdist-1.20.1, forked-0.2, benchmark-3.1.1, nbval-0.7
collected 1 item

test/test_jit_einsum.py::TestEinsum::test_jit FAILED                                                                         [100%]

============================================================= FAILURES =============================================================
_______________________________________________________ TestEinsum.test_jit ________________________________________________________

self = <test_jit_einsum.TestEinsum testMethod=test_jit>

    def test_jit(self):

        def fn(x, y):
            return torch.einsum('i,j->ij', x, y)

        jit_fn = torch.jit.trace(fn, (torch.ones(2), torch.ones(3)), check_trace=False)

        x = torch.randn(2)
        y = torch.randn(3)
        expected = fn(x, y)
>       actual = jit_fn(x, y)

test/test_jit_einsum.py:16:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
torch/nn/modules/module.py:477: in __call__
    result = self.forward(*input, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = fn(), args = (tensor([0.0461, 0.4024]), tensor([-1.0115,  0.2167, -0.6123])), kwargs = {}

    def forward(self, *args, **kwargs):
>       return self._get_method('forward')(*args, **kwargs)
E       RuntimeError:
E
E       Schema not found for node. File a bug report.
E       Node: %4 : Dynamic = aten::einsum(%2, %3)
E
E       Input types:string, Dynamic[]
E       candidates were:
E       :
E       /Users/fritzobermeyer/pytorch-dev/torch/functional.py(240): einsum
E       /Users/fritzobermeyer/pytorch-dev/test/test_jit_einsum.py(9): fn
E       /Users/fritzobermeyer/pytorch-dev/torch/jit/__init__.py(501): trace
E       /Users/fritzobermeyer/pytorch-dev/test/test_jit_einsum.py(11): test_jit
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/unittest/case.py(329): run
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/unittest/case.py(393): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/unittest.py(184): runtest
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(111): pytest_runtest_call
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(183): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(201): __init__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(185): call_runtest_hook
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(161): call_and_report
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(81): runtestprotocol
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(66): pytest_runtest_protocol
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(236): pytest_runtestloop
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(215): _main
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(178): wrap_session
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(208): pytest_cmdline_main
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/config/__init__.py(64): main
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/bin/pytest(11): <module>
E       :
E       operation failed shape propagation:
E       /Users/fritzobermeyer/pytorch-dev/torch/functional.py(240): einsum
E       /Users/fritzobermeyer/pytorch-dev/test/test_jit_einsum.py(9): fn
E       /Users/fritzobermeyer/pytorch-dev/torch/jit/__init__.py(501): trace
E       /Users/fritzobermeyer/pytorch-dev/test/test_jit_einsum.py(11): test_jit
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/unittest/case.py(329): run
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/unittest/case.py(393): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/unittest.py(184): runtest
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(111): pytest_runtest_call
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(183): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(201): __init__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(185): call_runtest_hook
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(161): call_and_report
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(81): runtestprotocol
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/runner.py(66): pytest_runtest_protocol
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(236): pytest_runtestloop
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(215): _main
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(178): wrap_session
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/main.py(208): pytest_cmdline_main
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/callers.py(180): _multicall
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(61): <lambda>
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/manager.py(67): _hookexec
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/pluggy/hooks.py(258): __call__
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/lib/python2.7/site-packages/_pytest/config/__init__.py(64): main
E       /Users/fritzobermeyer/miniconda2/envs/pytorch-dev/bin/pytest(11): <module>

torch/jit/__init__.py:1074: RuntimeError
===================================================== 1 failed in 0.55 seconds =====================================================
```
</details>
