### ISSUE TITLE
[inline_inbuilt_nn_modules] Custom `ModuleDict.__getitem__(key: tuple)` produces a graph break

### ISSUE THREAD

**Issue by akihironitta** [pytorch/pytorch#111551]
### 🐛 Describe the bug

#97932 enabled TorchDynamo to support modules with custom `__getitem__`. However, if the key is a tuple, it produces a graph break due to this assertion https://github.com/pytorch/pytorch/blob/v2.1.0/torch/_dynamo/variables/nn_module.py#L545.

```python
import torch
from torch_geometric.nn.module_dict import ModuleDict

class SomeModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.module_dict = ModuleDict({
            ("author", "writes", "paper"): torch.nn.Linear(1, 1),
        })

    def forward(self, x):
        x = self.module_dict[("author", "writes", "paper")](x)
        return x

model = torch.compile(SomeModel())
model(torch.randn(100, 1))
```

`torch_geometric.nn.module_dict.ModuleDict` is defined at https://github.com/pyg-team/pytorch_geometric/blob/2.4.0/torch_geometric/nn/module_dict.py

### Error logs

```
Traceback (most recent call last):
  File "/home/akihiro/work/github.com/pyg-team/pytorch_geometric/test/nn/test_compile_hetero.py", line 16, in <module>
    model(torch.randn(100, 1))
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 168, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 618, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 950, in call_getitem
    return args[0].call_method(tx, "__getitem__", args[1:], kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 545, in call_method
    assert isinstance(key, (str, int))
AssertionError: 

from user code:
   File "/home/akihiro/work/github.com/pyg-team/pytorch_geometric/test/nn/test_compile_hetero.py", line 12, in forward
    x = self.module_dict[("author", "writes", "paper")](x)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.998
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        4 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.16.0
[pip3] pytorch-lightning==2.0.9.post0
[pip3] pytorch-memlab==0.3.0
[pip3] torch==2.1.0+cu118
[pip3] torch_frame==0.1.0
[pip3] torch_geometric==2.4.0
[pip3] torchmetrics==1.2.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-lightning         2.0.9.post0              pypi_0    pypi
[conda] pytorch-memlab            0.3.0                    pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-frame               0.1.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchmetrics              1.2.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by akihironitta** [comment]
Just for anyone seeing this issue, a workaround is to convert `tuple` key to `str` in advance to passing it to `module_dict`:
```diff
    def forward(self, x):
-       x = self.module_dict[("author", "writes", "paper")](x)
+       key = ModuleDict.to_internal_key(("author", "writes", "paper"))
+       x = self.module_dict[key](x)
        return x
```

**Comment by yf225** [comment]
Animesh: try the `inlining_inbuilt_nn_modules` flag first

**Comment by yf225** [comment]
As Animesh suggested, using `inline_inbuilt_nn_modules` flag solves this issue. Two ways to enable it:
- Set `TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1` environment variable before running the script, or
- Set `torch._dynamo.config.inline_inbuilt_nn_modules = True` in the code, before calling torch.compile.

**Comment by anijain2305** [comment]
Will, just keeping it open. I will close when the flag is on by default.
