### ISSUE TITLE
`allow_non_fake_inputs=True` of `make_fx()` is not effective in fake tracing mode

### ISSUE THREAD

**Issue by ileixe** [pytorch/pytorch#111759]
### 🐛 Describe the bug

```
    gm = make_fx(
        gm,
        tracing_mode="fake",
        _allow_non_fake_inputs=True,
    )(*inputs)
```

In this code above, we specify allow non fake input tensors to allow, but unexpected exception happens like below

```
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.eq.Scalar(Parameter containing:
```

We're using custom backend and same code had worked well in 2.0, but 2.1 (and master) have regression now. 

After some investigation, I found the FakeTensorMode is not created using the `_allow_non_fake_inputs` options at all because `make_fx()` will use existed one from context manager: https://github.com/pytorch/pytorch/blob/main/torch/fx/experimental/proxy_tensor.py#L776  

The TracingContext from context manager seems to be added in: https://github.com/pytorch/pytorch/pull/100043, https://github.com/pytorch/pytorch/pull/96054

### Error logs

(pytorch) npu-tools$ python main.py
Traceback (most recent call last):
  File "/home/ys/Source/Furiosa/compiler/npu-tools/main.py", line 105, in <module>
    model(x)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/eval_frame.py", line 549, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/convert_frame.py", line 683, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/convert_frame.py", line 148, in _fn
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/convert_frame.py", line 402, in _convert_frame_assert
    return _compile(
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/convert_frame.py", line 610, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/convert_frame.py", line 527, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/convert_frame.py", line 497, in transform
    tracer.run()
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/symbolic_convert.py", line 2102, in run
    super().run()
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/symbolic_convert.py", line 742, in run
    and self.step()
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/symbolic_convert.py", line 705, in step
    getattr(self, inst.opname)(inst)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/symbolic_convert.py", line 2212, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/output_graph.py", line 858, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/ys/.miniconda3/envs/pytorch/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/output_graph.py", line 986, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/output_graph.py", line 1057, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/output_graph.py", line 1038, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/__init__.py", line 1643, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
  File "/home/ys/Source/Furiosa/compiler/npu-tools/main.py", line 97, in backend
    gm = make_fx(
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 867, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 478, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 514, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/graph_module.py", line 728, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/graph_module.py", line 307, in __call__
    raise e
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/graph_module.py", line 294, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 435, in call_module
    return forward(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.0", line 7, in forward
  File "/home/ys/Source/Projects/cpp/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 591, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 626, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/fx/experimental/proxy_tensor.py", line 371, in proxy_call
    out = func(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_ops.py", line 516, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/ys/Source/Projects/cpp/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_subclasses/fake_tensor.py", line 1324, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_subclasses/fake_tensor.py", line 1456, in dispatch
    ) = self.validate_and_convert_non_fake_tensors(func, converter, args, kwargs)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_subclasses/fake_tensor.py", line 1678, in validate_and_convert_non_fake_tensors
    args, kwargs = tree_map_only(
  File "/home/ys/Source/Projects/cpp/pytorch/torch/utils/_pytree.py", line 388, in tree_map_only
    return tree_map(map_only(ty)(fn), pytree)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/utils/_pytree.py", line 314, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/utils/_pytree.py", line 314, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/utils/_pytree.py", line 369, in inner
    return f(x)
  File "/home/ys/Source/Projects/cpp/pytorch/torch/_subclasses/fake_tensor.py", line 1668, in validate
    raise Exception(
torch._dynamo.exc.BackendCompilerFailed: backend='backend' raised:
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.eq.Scalar(Parameter containing:
tensor([...], size=(32, 6), dtype=torch.int8), 1)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Minified repro

```
import torch
import torch.nn as nn
from torch.fx.experimental.proxy_tensor import make_fx



model = nn.Linear(20, 30)
x = torch.randn(128, 20)


def backend(gm, inputs):
    gm = make_fx(
        gm,
        tracing_mode="fake",
        _allow_non_fake_inputs=True,
    )(*inputs)
    return gm

model = torch.compile(model, backend=backend)
model(x)

```

### Versions

Collecting environment information...
PyTorch version: 2.2.0a0+gite6d9350
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.4
Libc version: glibc-2.35

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
CPU family:                      6
Model:                           165
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     5000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5199.98
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        12 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] onnx==1.12.0
[pip3] onnx-simplifier==0.4.8
[pip3] onnxoptimizer==0.3.1
[pip3] onnxruntime==1.12.1
[pip3] torch==2.2.0a0+gite6d9350
[pip3] torch-xla==1.0
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] mkl                       2022.0.1           h06a4308_117
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     2.2.0a0+gite6d9350           dev_0    <develop>
[conda] torch-xla                 1.0                      pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
You could work around this by disabling the ambient tracing context using `TracingContext.patch(fake_mode=None)`. But in general, you should be using AOTAutograd wrapped around your backend, which will take care of fakeifying Parameters for you, so this error would not happen at all.

**Comment by mlazos** [comment]
@ileixe did Ed's suggestion solve your issue?

**Comment by ileixe** [comment]
Ok, it makes sense. Thanks for answer.

**Comment by yw-furiosa** [comment]
Hi @ezyang , I'm trying your suggestion, but AOTAutograd doesn't seem to work. I followed the very simple example in the [tutorial](https://pytorch.org/functorch/nightly/notebooks/aot_autograd_optimizations.html), but I still get the same error.
```python
import torch
from functorch.compile import aot_function

model = torch.nn.Linear(20, 30)
x = torch.randn(128, 20)

def backend(gm, inputs):
    return gm

model = aot_function(model, fw_compiler=backend, bw_compiler=backend)
model(x)
```
```bash
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.t.default(Parameter containing:
tensor([...], size=(30, 20), requires_grad=True))
```
Is there a reason for the default value of `allow_non_fake_inputs` is `False` in FakeTensorMode? And why `allow_non_fake_inputs` is `True` only in export?

**Comment by ileixe** [comment]
Similar issue: https://discuss.pytorch.org/t/view-operator-is-not-compiled-when-receiving-dtensor-faketensor-as-an-input/190613/1

**Comment by ezyang** [comment]
You're a custom backend because you want to integrate with torch.compile, right?

Use the `aot_autograd` combinator from torch._dynamo.backends.common to turn your backend into an aotautograd enabled one. You don't need to manually call the APIs.

**Comment by yw-furiosa** [comment]
It works well for me. Thanks!

**Comment by ileixe** [comment]
Thanks, it's all cleared.
