### ISSUE TITLE
[pytorch0.4.1]Segmentation fault occurred when using NCCL as backend for distribution training.

### ISSUE THREAD

**Issue by DonYum** [pytorch/pytorch#11170]
## Issue description

When I use pytorch to train on distributed cluster, I select NCCL as the backend. However, I got a annoying Segmentation fault as below.

### About running env

code: <https://github.com/pytorch/examples/tree/master/imagenet>

Modifications:

```diff
diff --git a/imagenet/main.py b/imagenet/main.py
index 7a60cd2..4d6c736 100644
--- a/imagenet/main.py
+++ b/imagenet/main.py
@@ -51,12 +51,13 @@ parser.add_argument('-e', '--evaluate', dest='evaluate', action='store_true',
                     help='evaluate model on validation set')
 parser.add_argument('--pretrained', dest='pretrained', action='store_true',
                     help='use pre-trained model')
-parser.add_argument('--world-size', default=1, type=int,
+parser.add_argument('--world-size', default=2, type=int,
                     help='number of distributed processes')
-parser.add_argument('--dist-url', default='tcp://224.66.41.62:23456', type=str,
+parser.add_argument('--dist-url', default='tcp://192.168.10.50:2345', type=str,
                     help='url used to set up distributed training')
-parser.add_argument('--dist-backend', default='gloo', type=str,
+parser.add_argument('--dist-backend', default='nccl', type=str,
                     help='distributed backend')
+parser.add_argument('--dist-rank', default=0, type=int, help='rank of distributed processes')
 parser.add_argument('--seed', default=None, type=int,
                     help='seed for initializing training. ')
 parser.add_argument('--gpu', default=None, type=int,
@@ -87,7 +88,7 @@ def main():
 
     if args.distributed:
         dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
-                                world_size=args.world_size)
+                                world_size=args.world_size, rank=args.dist_rank)
 
     # create model
     if args.pretrained:
```

CMD:

`python main.py /data/rjz/data/imagenet/raw --epochs 1 -b 512 -j 24 --arch resnet50 --dist-rank` *`[0/1]`*

### Error Info & My endeavor

And then I got a segment Fault:

```
......
Epoch: [0][1170/1252]   Time 1.270 (1.278)      Data 0.001 (0.066)      Loss 4.9393 (5.8856)    Prec@1 9.375 (3.959)    Prec@5 23.242 (11.597)
Epoch: [0][1180/1252]   Time 1.229 (1.278)      Data 0.001 (0.065)      Loss 4.8963 (5.8769)    Prec@1 8.984 (4.017)    Prec@5 23.633 (11.723)
Epoch: [0][1190/1252]   Time 1.225 (1.277)      Data 0.000 (0.065)      Loss 4.7729 (5.8676)    Prec@1 13.086 (4.078)   Prec@5 29.883 (11.857)
Epoch: [0][1200/1252]   Time 1.221 (1.277)      Data 0.000 (0.065)      Loss 4.7830 (5.8589)    Prec@1 8.398 (4.130)    Prec@5 26.172 (11.978)
[717623.493819] python[18028]: segfault at 7fff8cea7fe8 ip 00007f415cc749df sp 00007fff8cea7ff0 error 6 in _C.cpython-36m-x86_64-linux-gnu.so[7f415c8d7000+40de000]
```

**I ran it sevral times, and it always crashed on `Epoch: [0][1200/1252]`.**

So I do sth. below to try to handle it:

- Using `gloo` to replace `NCCL`, everything is OK.
- I open NCCL debug info, there is no more info print. It's not NCCL's business, I thick.
- Using `gdb -ex r --args [cmd]` to get more debug info. I got:

    **rank 0**

    ```
    Thread 1 "python" received signal SIGSEGV, Segmentation fault.
    lookdict_unicode (mp=0x7ffff62b76c0, key=0x7ffff3e60068, hash=-2694725939860369776, value_addr=0x7fffff7ff070, hashpos=0x0) at Objects/dictobject.c:804
    804     Objects/dictobject.c: No such file or directory.
    (gdb) bt
    #0  lookdict_unicode (mp=0x7ffff62b76c0, key=0x7ffff3e60068, hash=-2694725939860369776, value_addr=0x7fffff7ff070, hashpos=0x0) at Objects/dictobject.c:804
    #1  0x00007ffff7959316 in PyDict_GetItem (op=op@entry=0x7ffff62b76c0, key=key@entry=0x7ffff3e60068) at Objects/dictobject.c:1439
    #2  0x00007ffff796ae5c in _PyObject_GenericGetAttrWithDict (obj=obj@entry=0x7ffff4b786d8, name=name@entry=0x7ffff3e60068, dict=0x7ffff62b76c0, dict@entry=0x0) at Objects/object.c:1089
    #3  0x00007ffff796aff7 in PyObject_GenericGetAttr (obj=obj@entry=0x7ffff4b786d8, name=name@entry=0x7ffff3e60068) at Objects/object.c:1121
    #4  0x00007ffff79684f5 in module_getattro (m=0x7ffff4b786d8, name=0x7ffff3e60068) at Objects/moduleobject.c:663
    #5  0x00007ffff7a0487c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2859
    #6  0x00007ffff7a002d0 in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Python/ceval.c:4906
    #7  0x00007ffff7a099e6 in _PyFunction_FastCallDict (func=func@entry=0x7fffe926e1e0, args=args@entry=0x7fffff7ff420, nargs=1, kwargs=kwargs@entry=0x0) at Python/ceval.c:5008
    #8  0x00007ffff790e9be in _PyObject_FastCallDict (func=func@entry=0x7fffe926e1e0, args=args@entry=0x7fffff7ff420, nargs=nargs@entry=1, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2310
    #9  0x00007ffff790eaae in _PyObject_Call_Prepend (func=0x7fffe926e1e0, obj=0x7ffd800c22b0, args=0x7ffff7e09048, kwargs=0x0) at Objects/abstract.c:2373
    #10 0x00007ffff790e8cb in _PyObject_FastCallDict (func=0x7ffdd2fd1cc8, args=<optimized out>, nargs=<optimized out>, kwargs=0x0) at Objects/abstract.c:2331
    #11 0x00007ffff79874d3 in slot_tp_finalize (self=0x7ffd800c22b0) at Objects/typeobject.c:6450
    #12 0x00007ffff7969d94 in PyObject_CallFinalizer (self=self@entry=0x7ffd800c22b0) at Objects/object.c:297
    #13 0x00007ffff7969dc9 in PyObject_CallFinalizerFromDealloc (self=self@entry=0x7ffd800c22b0) at Objects/object.c:314
    #14 0x00007ffff797b9b4 in subtype_dealloc (self=0x7ffd800c22b0) at Objects/typeobject.c:1151
    #15 0x00007fff88345f62 in THPPointer<_object>::operator= (new_ptr=0x0, this=0x7ffd98059dc8) at /pytorch/torch/csrc/utils/object_ptr.h:17
    #16 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffd98059dc0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:26
    #17 0x00007fff88346084 in torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffd98059dc0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #18 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffd98059dc0) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #19 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffd98059df0, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #20 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffd98059de0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #21 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffd98059de0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #22 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffd98059de0) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #23 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffd98059df0, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #24 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffd98059e00, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #25 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffd98059e00, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #26 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffd98059e00) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #27 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffd98059df0, __in_chrg=<optimized out>)
    ```

    **rank 1**

    ```
    Thread 1 "python" received signal SIGSEGV, Segmentation fault.
    0x0000555555673175 in lookdict_unicode ()
    (gdb) bt
    #0  0x0000555555673175 in lookdict_unicode ()
    #1  0x0000555555655700 in PyDict_GetItem ()
    #2  0x000055555565fe21 in _PyObject_GenericGetAttrWithDict ()
    #3  0x00005555556ad360 in module_getattro ()
    #4  0x000055555571449a in _PyEval_EvalFrameDefault ()
    #5  0x00005555556ea51b in _PyFunction_FastCallDict ()
    #6  0x0000555555662b8f in _PyObject_FastCallDict ()
    #7  0x0000555555667773 in _PyObject_Call_Prepend ()
    #8  0x00005555556629ab in _PyObject_FastCallDict ()
    #9  0x00005555556bfb32 in slot_tp_finalize ()
    #10 0x00005555556f0b85 in PyObject_CallFinalizer ()
    #11 0x00005555556f0c7b in PyObject_CallFinalizerFromDealloc ()
    #12 0x00005555556f131c in subtype_dealloc ()
    #13 0x00007fff88aa6f62 in THPPointer<_object>::operator= (new_ptr=0x0, this=0x7ffee80698c8) at /pytorch/torch/csrc/utils/object_ptr.h:17
    #14 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee80698c0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:26
    #15 0x00007fff88aa7084 in torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee80698c0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #16 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffee80698c0) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #17 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffee80698f0, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #18 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee80698e0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #19 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee80698e0, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #20 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffee80698e0) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #21 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffee80698f0, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #22 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069900, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #23 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069900, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #24 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffee8069900) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #25 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffee80698f0, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #26 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069920, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #27 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069920, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #28 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffee8069920) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #29 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffee80698f0, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #30 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069940, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #31 0x00007fff88aa7084 in torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069940, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #32 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffee8069940) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #33 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffee8069970, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #34 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069960, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    #35 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069960, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:27
    #36 std::default_delete<THFinalizer>::operator() (this=<optimized out>, __ptr=0x7ffee8069960) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
    #37 std::unique_ptr<THFinalizer, std::default_delete<THFinalizer> >::~unique_ptr (this=0x7ffee8069970, __in_chrg=<optimized out>)
        at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
    #38 torch::PyObjectFinalizer::~PyObjectFinalizer (this=0x7ffee8069980, __in_chrg=<optimized out>) at /pytorch/torch/csrc/finalizer.h:22
    .......
    ```

    It crashed in lookdict_unicode()@python, so I google it. Then I found some clue from <https://discuss.pytorch.org/t/segmentation-fault/23489>. 

    Maybe sth. wrong with sampler of Dataloader, so I try to install torchvision0.2.0 instead 0.2.1

- Using torchvision0.2.0 instead 0.2.1

    Fail.

- Using torchvision0.4.0 instead 0.4.1

    It's OK.

### My conclusion

I think it may be a little flaw of pytorch 0.4.1. And please pay attention about it. 

Thanks for your attention.

## System Info

```
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 375.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.1                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

**Comment by cchen01** [comment]
Is the problem resolved?  I got the same error...in pytirch imagenet

**Comment by teng-li** [comment]
@cchen01 which version of PyTorch are you using. We don't plan on continuing supporting the old distributed library since the 1.0 release will have a new backend. Please give it a try and let us know.

**Comment by cchen01** [comment]
hi, the version is 0.4.1.  DistributedDataParallel has some issues especially in official imagenet examples.  After some modification, I can successfully run imagenet cross-node.  However it shows segmentation fault after the 1sy epoch.  Hopefully 1.0 will not have this issue.  Let me try it out.

**Comment by teng-li** [comment]
@cchen01  Great, let me know how it goes

**Comment by mrshenli** [comment]
Closing due to lack of activity. Please feel free to open a new issue if the problem persists with latest release.
