### ISSUE TITLE
torch.utils.flop_counter modifies model signatures when it shouldn't 

### ISSUE THREAD

**Issue by gabrielilharco** [pytorch/pytorch#111809]
### 🐛 Describe the bug

`torch.utils.flop_counter` has hooks that can undesirably change some model signatures, which in turn can lead to errors. This happens when a call returns a tuple with only one element. When using the flop counter, the call instead starts to return the element itself instead of a tuple, which can cause downstream errors.

A simple example is shown below (need to `pip install open_clip_torch` to run it). The code below (without the flop counter) works fine.

```python
import open_clip
import torch
model = open_clip.create_model('xlm-roberta-base-ViT-B-32', force_custom_text=True, pretrained_hf=False).text
example_input = torch.ones((1, 514), dtype=torch.int64)
model(example_input)
```

When adding the flop counter, the code now fails.

```python
import open_clip
import torch
from torch.utils.flop_counter import FlopCounterMode

model = open_clip.create_model('xlm-roberta-base-ViT-B-32', force_custom_text=True, pretrained_hf=False).text
example_input = torch.ones((1, 514), dtype=torch.int64)
flop_counter = FlopCounterMode(model)
with flop_counter:
    model(example_input)
```

Error:

```
Module                           FLOP    % Total
--------------------------  ---------  ---------
HFTextEncoder               8087.679M    100.00%
 - aten.addmm               7276.069M     89.96%
 - aten.bmm                  811.610M     10.04%
 HFTextEncoder.transformer  8087.679M    100.00%
  - aten.addmm              7276.069M     89.96%
  - aten.bmm                 811.610M     10.04%
Traceback (most recent call last):
  File "/home/open_clip/test.py", line 17, in <module>
    model(example_input)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/open_clip/src/open_clip/hf_model.py", line 156, in forward
    out = self.transformer(input_ids=x, attention_mask=attn_mask)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 850, in forward
    encoder_outputs = self.encoder(
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 534, in forward
    layer_outputs = layer_module(
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/oc/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 463, in forward
    outputs = (layer_output,) + outputs
TypeError: can only concatenate tuple (not "Tensor") to tuple
```

I believe this is because of how the code currently normalizes outputs to tuples, and then attempts to reverse this at https://github.com/pytorch/pytorch/blob/f7401de1bbf29ac488aac6a2c472c79353a7533d/torch/utils/flop_counter.py#L334. However, we should only reverse this if the original signature wasn't a tuple with one element.  

### Versions

```
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov  4 2022, 13:48:29) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1037-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          36
On-line CPU(s) list:             0-35
Thread(s) per core:              2
Core(s) per socket:              18
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
Stepping:                        4
CPU MHz:                         3241.206
BogoMIPS:                        6000.01
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       576 KiB
L1i cache:                       576 KiB
L2 cache:                        18 MiB
L3 cache:                        24.8 MiB
NUMA node0 CPU(s):               0-35
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] open-clip-torch==2.22.0
[pip3] torch==2.1.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] open-clip-torch           2.22.0                    dev_0    <develop>
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by awgu** [comment]
cc: @Chillee

**Comment by Chillee** [comment]
Hmm... I think I'm gonna take another look at how to do hierarchical flop counting.

Btw, to be clear, you can also use it *without* wrapping a module if you don't need the hierarchical aspect.

**Comment by gabrielilharco** [comment]
Thanks @Chillee! It does work without the hierarchical counting

**Comment by Chillee** [comment]
This should resolve the issues with the tuples + also any issues with any other pytree-able data structures (i.e. tuples, lists, sets, dicts, etc.): https://github.com/pytorch/pytorch/pull/111990

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/111990

**Comment by gabrielilharco** [comment]
Thanks @Chillee!
