### ISSUE TITLE
torchscript file can not be loaded if its saved form the export model produced by torch.export.export

### ISSUE THREAD

**Issue by TingfengTang** [pytorch/pytorch#111902]
### 🐛 Describe the bug

Hi, torchscript team guys,

 I tried the newest quantization tool pt2e and get the  final QAT model. But when I load the model after serializing,some error happens.

code snippet:
```
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
    XNNPACKQuantizer,
    get_symmetric_quantization_config,
)

from torch._export import dynamic_dim
from torch._export import capture_pre_autograd_graph
from torch.ao.quantization.quantize_pt2e import (
    prepare_qat_pt2e,
    convert_pt2e,
)

from torch.export import dynamic_dim
import torch
from torch._export import capture_pre_autograd_graph
from torch.export import export, ExportedProgram

class Debug(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_debug=torch.nn.Conv2d(in_channels=3, out_channels=5, kernel_size=(3,3), padding=0, stride=1, groups=1,bias=True)
        self.relu=torch.nn.ReLU()
    def forward(self,x):
        x=self.conv_debug(x)
        return self.relu(x)

if __name__=='__main__':
    print('The default quantized engine is {}'.format(torch.backends.quantized.engine))
    quantizer = XNNPACKQuantizer()
    qconfig=get_symmetric_quantization_config(is_qat=True)
    quantizer.set_global(qconfig)
    model=Debug()
    input=torch.rand(1,3,10,10)
    model_aot_graph= capture_pre_autograd_graph(model,(input,))
    model_qat = prepare_qat_pt2e(model_aot_graph, quantizer)
    model_qat_convert = convert_pt2e(model_qat)
    model_qat_ep=torch.export.export(model_qat_convert,(input,))


    model_jit=torch.jit.trace(model_qat_ep.module(),input)
    torch.jit.save(model_jit,'xnnpack_pt2e.pth')
```
if I load the model in terminal，error happens:
```
>>> import torch
>>> model_jit_load=torch.jit.load('xnnpack_pt2e.pth')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sfadmin/anaconda3/envs/torch2.1/lib/python3.9/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: 
Unknown builtin op: quantized_decomposed::quantize_per_tensor.
Could not find any similar ops to quantized_decomposed::quantize_per_tensor. This op may not exist or may not be currently supported in TorchScript.
:
  File "code/__torch__/torch/fx/graph_module.py", line 12
    _param_constant1 = self._param_constant1
    _param_constant0 = self._param_constant0
    _0 = ops.quantized_decomposed.quantize_per_tensor(arg_0, 1., 0, -128, 127, 1)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _1 = ops.quantized_decomposed.dequantize_per_tensor(_0, 1., 0, -128, 127, 1)
    _2 = ops.quantized_decomposed.quantize_per_tensor(_param_constant0, 1., 0, -127, 127, 1)
```
It seems that torchscript does not support those new ops produced during using pt2e.
Is there some plan to support those operators , I hear that torchscript is in maintain mode and will not add new features.
thanks.

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.58
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB

Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-89
Off-line CPU(s) list:            90-95
Thread(s) per core:              1
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3600.003
CPU max MHz:                     4000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6000.00
Virtualization:                  VT-x
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        24 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==2.1.0+cu118
[pip3] torch-pruning==1.0.0
[pip3] torch-scatter==2.1.0+pt112cu113
[pip3] torch-tb-profiler==0.4.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.2
[pip3] torchviz==0.0.2
[pip3] triton==2.1.0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-pruning             1.0.0                    pypi_0    pypi
[conda] torch-scatter             2.1.0+pt112cu113          pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by jerryzh168** [comment]
yeah `torch.ops.quantized_decomposed.quantize_per_tensor` etc. is custom ops added in python (https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/fx/_decomposed.py#L32), that's probably not supported by TorchScript. cc @zou3519 

wondering why do you need to Torchscript the model?

**Comment by TingfengTang** [comment]
windows is not supported by executorch now,  so i use  torchcript as a workaround to verify my model. for non-quantized model, torchscript works well.

**Comment by andrewor14** [comment]
This doesn't seem like something we plan to support any time soon. PT2E quantization <-> torchscript is not actively maintained. @jerryzh168 do you think we will get to this one day or it's something we simply don't plan to support?

**Comment by jerryzh168** [comment]
we don't have any users using this path currently, so I'm not sure about the timeline. also this is not a quantization problem, this should be reviewed at Export meetings, I'll assign to Tugsuu instead
