### ISSUE TITLE
_functional_collectives.all_gather_into_tensor cannot compile in aot_module_simplified

### ISSUE THREAD

**Issue by yangxiaorun** [pytorch/pytorch#112009]
### 🐛 Describe the bug

torch.distributed._functional_collectives.all_gather_tensor can work great in make_fx，but it cannot work in aot_module_simplified.
It doesn't work because assert self.is_contiguous() exists in _functional_collectives.all_gather_into_tensor api.
The script I'm running is：
```
import torch
import os
from torch.fx.experimental.proxy_tensor import make_fx
import torch.distributed as dist
import torch.distributed._functional_collectives as funcol
import torch.multiprocessing as mp
from torch._functorch.aot_autograd import aot_module_simplified
from typing import Any, Dict, Iterator, List, Optional, Tuple, Union

def toy_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print(gm.graph)
    return gm

def toy_backend(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    return aot_module_simplified(gm, example_inputs,fw_compiler=toy_compiler)

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x = funcol.all_gather_tensor(x, 0, group=[0,1],tag='test1')
        return x

def example(rank, world_size):
    dist.init_process_group("gloo", rank=rank, world_size=world_size)
    mod = MyModule()
    opt_mod = torch.compile(mod, dynamic=True, fullgraph=True, backend=toy_backend)
    x = torch.randn(10, 100)
    out = opt_mod(x)
    print(out)


def main():
    world_size = 2
    mp.spawn(example,
             args=(world_size, ),
             nprocs=world_size,
             join=True)


if __name__ == "__main__":
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29516"
    main()
```

### Error logs

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/opt/npu/y00569965/pytorch_master/tp_test/demo_all_gather_tensor_error.py", line 32, in example
    out = opt_mod(x)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1167, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1115, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 594, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/variables/tensor.py", line 655, in call_method
    return wrap_fx_proxy(
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1416, in wrap_fx_proxy_cls
    unimplemented(
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_method is_contiguous

from user code:
   File "/opt/npu/y00569965/pytorch_master/tp_test/demo_all_gather_tensor_error.py", line 24, in forward
    x = funcol.all_gather_tensor(x, 0, group=[0,1],tag='test1')
  File "/root/archiconda3/envs/yxr_py38/lib/python3.8/site-packages/torch/distributed/_functional_collectives.py", line 169, in all_gather_tensor
    assert self.is_contiguous()

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0
[pip3] torch-npu==2.1.0+git8824338
[pip3] torchair==0.1
[pip3] torchvision==0.15.1
[conda] numpy                     1.24.4                    <pip>
[conda] numpy                     1.24.2                    <pip>
[conda] numpy                     1.23.5                    <pip>
[conda] torch                     2.1.0                     <pip>
[conda] torch-npu                 2.1.0+git8824338           <pip>
[conda] torchair                  0.1                       <pip>
[conda] torchvision               0.15.1                    <pip>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by yangxiaorun** [comment]
And here I have two related questions: https://discuss.pytorch.org/t/functional-collectives-used-in-torch-compile/190627

**Comment by wconstab** [comment]
> And here I have two related questions: https://discuss.pytorch.org/t/functional-collectives-used-in-torch-compile/190627

Those other questions seem simpler, i created a separate task.

> torch.distributed._functional_collectives.all_gather_tensor can work great in make_fx，but it cannot work in aot_module_simplified.

For this one i wonder if @bdhirsh could take a quick look and diagnose- it seems like a straight-forward issue that we're calling `is_contiguous()` from inside functional collectives, and maybe that is not supported in aot_module_simplified? (For reasons that aren't clear to me)

**Comment by ezyang** [comment]
The backtrace is in Dynamo. IDK, this seems pretty straightforward to me, the main question is why isn't more stuff broken

**Comment by williamwen42** [comment]
The issue is that calling `all_gather_tensor` calls `is_contiguous`, which causes a graph break. If you set `fullgraph=False`, the script seems to run fine. @wconstab should there be a graph break here?

**Comment by yangxiaorun** [comment]
I found that this issue has been fixed in the latest version, so I closed the issue.
