### ISSUE TITLE
[ONNX] In-place additon not being functionalized by torch.onnx.dynamo_export

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#112256]
### 🐛 Describe the bug

```python
import torch
from torch import nn as nn

class CustomModule(nn.Module):
    def __init__(self):
        super(CustomModule, self).__init__()
        # Define a buffer
        self.register_buffer('my_buffer', torch.tensor(4.0))

    def forward(self, x1, x2):
        # Mutate the buffer
        self.my_buffer.add_(1.0) # In-place addition

        return torch.nn.functional.relu(x1 + x2)

inputs = (torch.randn(3), torch.randn(3))

export_output = torch.onnx.dynamo_export(CustomModule(), *inputs)
```

The error is as follows:

```bash
[2023-10-27 16:33:09,545] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/opt/pytorch/torch/onnx/_internal/exporter.py:135: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1232, in dynamo_export
    return Exporter(
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 979, in export
    graph_module = self.options.fx_tracer.generate_fx(
  File "/opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 216, in generate_fx
    return self.pre_export_passes(options, model, graph_module, updated_model_args)  # type: ignore[return-value]
  File "<@beartype(torch.onnx._internal.fx.dynamo_graph_extractor.DynamoExport.pre_export_passes) at 0x7f887973d0d0>", line 93, in pre_export_passes
  File "/opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 226, in pre_export_passes
    return exporter.common_pre_export_passes(
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1291, in common_pre_export_passes
    analysis.UnsupportedFxNodesAnalysis(
  File "/opt/pytorch/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 74, in analyze
    self._lint(analysis_result, diagnostic_level)
  File "/opt/pytorch/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 38, in _lint
    self.diagnostic_context.log_and_raise_if_error(diagnostic)
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/context.py", line 367, in log_and_raise_if_error
    raise RuntimeErrorWithDiagnostic(diagnostic)
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten.add_.Tensor']}. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "my_custom_module_to_onnx.py", line 26, in <module>
    export_output = torch.onnx.dynamo_export(CustomModule(), *inputs)
  File "<@beartype(torch.onnx._internal.exporter.dynamo_export) at 0x7f88290a09d0>", line 51, in dynamo_export
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1248, in dynamo_export
    raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
(ptca) root@88c3e49b4bcf:/opt/pytorch# 
```

### Versions

pytorch main branch from 10/27/2023

**Comment by BowenBao** [comment]
Same as #103857
