### ISSUE TITLE
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1695392020201/work/c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.

### ISSUE THREAD

**Issue by zyh3826** [pytorch/pytorch#112377]
### 🐛 Describe the bug

RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1695392020201/work/c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.

```python
from transformers import LlamaForCausalLM, LlamaConfig, LlamaTokenizer
p = 'path/to/llama_2_models/13B'
model = LlamaForCausalLM.from_pretrained(p)
model.to('cuda:0')
```
errors below:
![image](https://github.com/pytorch/pytorch/assets/31238754/60ce8cae-bfa0-4762-a954-c9c05baa95fd)

### Versions

```
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-156-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A800 80GB PCIe
  MIG 3g.40gb     Device  0:

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         906.909
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       2.3 MiB
L1i cache:                       1.5 MiB
L2 cache:                        60 MiB
L3 cache:                        72 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46343
[conda] mkl-service               2.4.0           py310h5eee18b_1
[conda] mkl_fft                   1.3.8           py310h5eee18b_0
[conda] mkl_random                1.2.4           py310hdb19cb5_0
[conda] numpy                     1.26.0          py310h5f9d8c6_0
[conda] numpy-base                1.26.0          py310hb5e798b_0
[conda] pytorch                   2.1.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.0               py310_cu118    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtriton               2.1.0                     py310    pytorch
[conda] torchvision               0.16.0              py310_cu118    pytorch
```

**Comment by zyh3826** [comment]
I use `pytorch` in this docker container, `pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel`

**Comment by chand1012** [comment]
I am getting the same error when running [this script](https://gist.github.com/chand1012/ed0a2bee8d1826704fe9f602490c3125) on [Modal AI](https://modal.com). Here is the full stack trace.

```
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 365, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 474, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/sdapi.py", line 82, in inference
    image = self.refiner(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1017, in __call__
    image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False)[0]
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 288, in decode
    decoded = self._decode(z).sample
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 275, in _decode
    dec = self.decoder(z)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/vae.py", line 272, in forward
    sample = up_block(sample, latent_embeds)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 2375, in forward
    hidden_states = upsampler(hidden_states)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/resnet.py", line 170, in forward
    hidden_states = self.conv(hidden_states, scale)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/lora.py", line 163, in forward
    return F.conv2d(
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch. 
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<FastAPI.__call__() done, defined at /usr/local/lib/python3.10/site-packages/fastapi/applications.py:267> exception=RuntimeError('NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch. ')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
Request finished with status 500. (execution time: 53023.9 ms, first-byte latency: 55345.7 ms)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/sdapi.py", line 132, in generate_image
    image_bytes = Model().inference.remote(
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
  File "/pkg/synchronicity/combined_types.py", line 26, in __call__
    raise uc_exc.exc from None
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/root/sdapi.py", line 82, in inference
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1017, in __call__
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 288, in decode
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 275, in _decode
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/models/vae.py", line 272, in forward
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 2375, in forward
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/models/resnet.py", line 170, in forward
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  File "<ta-VAuPWfjtnV8hRv1ZO69nRO>:/usr/local/lib/python3.10/site-packages/diffusers/models/lora.py", line 163, in forward
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.
```

**Comment by chand1012** [comment]
After some quick testing, I cannot say for anyone else's setup, but this issue only occurs when using the T4 GPU on Modal's platform, and doesn't occur with any other GPU.

**Comment by imangohari1** [comment]
Running to the same issue with `tiiuae/falcon-40b`. 
Any ideas how to get around this?

**Comment by zyh3826** [comment]
My GPU is A800 80G

**Comment by gongy** [comment]
Hi from Modal, our users have been facing this PyTorch error instead of the regular CUDA OOM message.

@chand1012 for you specifically, Stable Diffusion XL needs more memory than is available on T4s, so you may be running out of memory (and it should work with A10Gs).

**Comment by chand1012** [comment]
> Stable Diffusion XL needs more memory than is available on T4s, so you may be running out of memory (and it should work with A10Gs).

I ended up going with A10G GPUs, thanks for the insight!

**Comment by harsanyidani** [comment]
I get the same error.

GPU: A100 10GB
pytorch: [this nvidia pytorch container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-11.html](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-11.html)) ([commit](https://github.com/pytorch/pytorch/commit/6a974bec))

I'm testing the memory consumption of a function so I'm trying to catch a `torch.cuda.OutOfMemoryError`. 
It worked with V100 GPU with [this nvidia pytorch container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-04.html) ([commit](https://github.com/pytorch/pytorch/commit/fe05266f))

But now it throws this weird error when OOM happens, which is harder to catch and not so intuitive.

**Comment by nashjojo** [comment]
I got this error and I fixed it by reinstalling an earlier version of the transformers package.

**Comment by caroljoyv** [comment]
> I got this error and I fixed it by reinstalling an earlier version of the transformers package.

which version of transformers?

**Comment by NikhilMank** [comment]
I got a similar error while running my training code. Weird thing is it is happening everytime after running for 18853 iterations at same point in the code.
Memory: DDR4 32GB
CPU: AMD EPYC 7713 64-Core Processor
Storage: 1.92TB NVMe SSD +240GB 6Gbps SATA 2.5" SSD (for OS)
GPU: NVIDIA A100 80GB

![image](https://github.com/pytorch/pytorch/assets/41358516/1f53b1ea-9d05-4601-8ac4-29e8ba53053c)

**Comment by gSayak** [comment]
> Seems like I got the point, My GPU is MIG(I don't know this arch), and loading Llama2-13B on it will cause OOM, even if the memory is almost 80Gb, don't know why. I tested smaller model like Bert, everything was fine

Hey @zyh3826, I am facing the same issue while finetuning a gemma2-2b and I think it is due to the GPU I am using : 
`'NVIDIA H100 80GB HBM3 MIG 2g.20gb'`

Did you find any work around to fix this? Is this a memory issue?

**Comment by NikhilMank** [comment]
@gSayak In my experience, this error is thrown when the GPU used is not enough to run the training run, and instead of saying that it ran out of memory, it throws this error.

**Comment by gSayak** [comment]
@NikhilMank So, like I was trying to use PEFT for finetuning a gemma2-2b model, and even if I try it with 10 training data points, it is throwing this error. I have 20GB VRAM of a h100 GPU, should I be using a GPU with more vram? or as stated earlier this might be the issue with MIG?

Am really new in this space so sorry if I asked something silly.

**Comment by NikhilMank** [comment]
@gSayak I don't know much about gemma-2b model but check the size of the model (no of parameters) that will give you rough idea about how much size the model occupies. You can verify the memory issue by running with a single data point as batch size and observing the GPU memory in real-time (run ~watch -n 0.1 nvidia-smi~ in a new terminal before running the training script), if it occurs even when GPU is not full then the problem is different.

**Comment by riccardoratta** [comment]
> Seems like I got the point, My GPU is MIG(I don't know this arch), and loading Llama2-13B on it will cause OOM, even if the memory is almost 80Gb, don't know why. I tested smaller model like Bert, everything was fine
> 
> >>> import torch
> >>> torch.cuda.get_device_name(0)
> 'NVIDIA A800 80GB PCIe MIG 3g.40gb'
> ![image](https://github.com/pytorch/pytorch/assets/31238754/bafd71a6-d4bd-4a94-b8ea-ad463fb12f65)

Note that in your MIG configuration `3g.40gb` you have only 40 gb of available memory and 3 compute units.

**Comment by codingJang** [comment]
I have the same issue while using MIG, it's an A100 40GB gpu with 1/2 the resource.
HARDWARE: NVIDIA DGX A100 40GB - Dual AMD Rome 7742 (128 cores total, 3.4 GHz max boost), 1TiB System memory, 1.92TB SSD (RAID1, OS), 15TB SSD (RAID0, Internal Storage), 8x NVIDIA A100 40GB Tensor Core GPUs
Cuda version: 12.4
PyTorch version: 2.3.1+cu121

**Comment by okaris** [comment]
Thanks @NikhilMank 

That is exactly my point. This is effectively an OOM, but it surfaces as a different error.

I am unsure whether CUDA should report this as OOM or whether PyTorch should catch it and raise a clearer error.
