### ISSUE TITLE
[pytree] cleanup pytree custom node lifetimes

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112342]
### 🚀 The feature, motivation and pitch

_register_pytree_node is a global op. It should not be called anywhere outside of the pytree until

other consumers of pytree ought to only register pytree nodes locally. They should either be tied to a file or require a decorator over the function bodies where they are required.

### Alternatives

1. Duplicate definitions of pytree, unclear whether they diverge or which takes precedence.

fx https://github.com/pytorch/pytorch/blob/f5088d2e45787094e201fe82677c399ce456ef71/torch/fx/immutable_collections.py#L4

Aot autograd

https://github.com/pytorch/pytorch/blob/f5088d2e45787094e201fe82677c399ce456ef71/torch/_functorch/aot_autograd.py#L96

2. Aberrant behaviour of pytree nodes bleeding into implicit uses and calcifying due to hyrum’s law

Tackled by: https://github.com/pytorch/pytorch/pull/111993

### Additional context

NIL

**Comment by jon-chuang** [comment]
The two above are the only offending, further, `immutable_collections` registers the datatype where it is defined, so it is probably fine.

So the biggest offending is probably `torch.Size`, but for future's sake, I think we should enforce allowing global registration only if the object's defining module is identical to the current module.

**Comment by jon-chuang** [comment]
Proposed API:

I think we will move https://github.com/pytorch/pytorch/blob/740d636165676d4a7286f05043e47db86efdeee1/torch/onnx/_internal/fx/dynamo_graph_extractor.py#L31
into utils.pytree, and then we provide a default `torch.Size` extension.

```python

class use_pytree_extension:
  # If cls has a default extension (e.g. torch.Size), we do not need to provide (un)flatten_fn
  def __init__(self, cls):
    ..

```

```python
from utils.pytree import use_pytree_extension

@use_pytree_extension(torch.Size)
def fn():
  pytree.tree_map_only(SymInt, ..)
```

For non-default extensions:
```python
@dataclass
class myDataclass:
  t: torch.Tensor
  ..

register_pytree_extension(myDataclass, myDataclass.flatten_fn, myDataclass.unflatten_fn)

@use_pytree_extension(myDataclass)  # uses the existing registered (un)flatten_fn
def fn():
  pytree.tree_map_only(torch.Tensor, ..)
```

**Comment by jon-chuang** [comment]
Mechanism for defining module registration (except for pytree

```python
current_module = inspect.getmodule(inspect.currentframe())  # utils.pytree

def my_function(c):
    class_def_module = inspect.getmodule(c)
    registration_module = inspect.getmodule(inspect.currentframe())

    # Compare the modules
    if registration_module in [current_module, class_def_module]:
        print("my_function is being called from the same module where it is defined.")
    else:
        print("my_function is being called from a different module.")
```

**Comment by jon-chuang** [comment]
cc: @XuehaiPan @peterbell10

**Comment by XuehaiPan** [comment]
IMO, we should not delete/update the pytree node registry. Once a type is added to the registry, the flatten/unflatten behavior for this type should be immutable.

In the context manager or the function decorator example, if the treespec object is returned out of the scope, it can lead to potential bugs:

```python
@use_pytree_extension(MyType)
def some_func(*args, **kwargs):
    leaves, treespec = tree_flatten(...)
    return treespec
```

We should only allow users and developers to unregister types if they only use `tree_leaves` and `tree_map` functions, which do not access the `treespec` object.

------

See also my comment:

- https://github.com/pytorch/pytorch/pull/109684#discussion_r1371188379

> If we update the `transformers` pin, I think we can remove the flag. But this is a design problem. Could we delete/update the node flatten behavior in the pytree registry? Any thoughts? cc @zou3519
> 
> See my comment:
> 
> - https://github.com/huggingface/transformers/pull/26618#issuecomment-1759973274
> - https://github.com/huggingface/transformers/pull/26618#issuecomment-1761604123
> - https://github.com/huggingface/transformers/pull/26618#issuecomment-1773839144
> 
> I think deleting or updating the pytree node registry is dangerous. It could lead to potential bugs when the developer passes the treespec object out of the scope of the context manager.
> 
> > Here is a self-contained snippet with `torch==2.1.0` and `transformers==4.34.1`.
> > 
> > ```python
> > import torch
> > import transformers
> > import torch.utils._pytree as pytree
> > from torch.onnx._internal.fx.dynamo_graph_extractor import _PyTreeExtensionContext as PyTreeExtensionContext
> > from transformers.modeling_utils import ModelOutput
> > 
> > print('===== before entering context =====')
> > leaves, treespec = pytree.tree_flatten(ModelOutput(a=1, b=2))  # ModelOutput is a leaf
> > print('leaves:', leaves)
> > print('treespec:', treespec)
> > print('reconstructed:', pytree.tree_unflatten(leaves, treespec))
> > 
> > with PyTreeExtensionContext():
> >     print('===== entered context =====')
> >     leaves, treespec = pytree.tree_flatten(ModelOutput(a=1, b=2))  # ModelOutput is a node
> >     print('leaves:', leaves)
> >     print('treespec:', treespec)
> >     print('reconstructed:', pytree.tree_unflatten(leaves, treespec))
> > 
> > print('===== exited context =====')
> > print('leaves:', leaves)
> > print('treespec:', treespec)
> > print('reconstructed:', pytree.tree_unflatten(leaves, treespec))
> > ```
> > 
> > Output:
> > 
> > ```
> > $ python3 test.py             
> > ===== before entering context =====
> > leaves: [ModelOutput([('a', 1), ('b', 2)])]
> > treespec: *
> > reconstructed: ModelOutput([('a', 1), ('b', 2)])
> > ===== entered context =====
> > leaves: [1, 2]
> > treespec: TreeSpec(ModelOutput, (<class 'transformers.utils.generic.ModelOutput'>, ['a', 'b']), [*,
> >   *])
> > reconstructed: ModelOutput([('a', 1), ('b', 2)])
> > ===== exited context =====
> > leaves: [1, 2]
> > treespec: TreeSpec(ModelOutput, (<class 'transformers.utils.generic.ModelOutput'>, ['a', 'b']), [*,
> >   *])
> > Traceback (most recent call last):
> >   File ".../test.py", line 23, in <module>
> >     print('reconstructed:', pytree.tree_unflatten(leaves, treespec))
> >                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File ".../venv/lib/python3.11/site-packages/torch/utils/_pytree.py", line 268, in tree_unflatten
> >     unflatten_fn = SUPPORTED_NODES[spec.type].unflatten_fn
> >                    ~~~~~~~~~~~~~~~^^^^^^^^^^^
> > KeyError: <class 'transformers.utils.generic.ModelOutput'>
> > ```

**Comment by jon-chuang** [comment]
> We should only allow users and developers to unregister types if they only use tree_leaves and tree_map functions, which do not access the treespec object.

Unfortunately, things like `torch.functional.vmap` use tree spec.

Isn't there another way to enforce the lifetime of the created TreeSpec? I.e. each `TreeSpec` created while under a custom registration has a `enable_ctx_id`, and we have to check if this ctx is still active when we use the `TreeSpec` :thinking:

**Comment by XuehaiPan** [comment]
Currently, optree uses a string identifier `namespace` to specify the registry.

```python
optree.register_pytree_node(MyClass, flatten_fn, unflatten_fn, namespace='torch')
optree.register_pytree_node(MyOtherClass, flatten_fn, unflatten_fn, namespace='torch.vmap')
```

We could add a mechanism to synchronize the subnamespace to inherence registrations in the parent namespace.

Then we can have a context manager to switch the default namespace for the pytree utility.

```python
class PyTreeContextManager:
    def __new__(cls, namespace):  # should be singleton to ensure the types are registered only once
        if hasattr(cls. '_instance'):
            return cls._instance
        cls._instance = super().__new__()
        cls._instance.namespace = namespace
        for typ in some_types:
            pytree.register_pytree_node(typ, flatten_fn, unflatten_fn, namespace=namespace)

    def __enter__(self):
        pytree.set_default_namespace(self.namespace)

    def __exit__(self):
        pytree.set_default_namespace('torch')


with PyTreeContextManager('torch.vmap'):
    leaves, treespec = pytree.tree_flatten(...)
    # treespec refers to `namespace='torch.vmap'`

# treespec still refers to `namespace='torch.vmap'`
pytree.tree_unflatten(leaves, treespec)  # works without errors
```

**Comment by jon-chuang** [comment]
@XuehaiPan that makes sense to me.

The treespec is created under a user-defined context and namespace. Hence, they can check what the namespace is when consuming the treespec.

We do not pollute the global namespace with custom registrations.

It's not perfect (it is still possible to have errors) but not terrible (errors should be localized and debuggable).

**Comment by XuehaiPan** [comment]
> It's not perfect (it is still possible to have errors - i.e. unflattening incompatible with the custom treespec) but not terrible (errors should be localized and debuggable).

We set the registration immutable. During unflattening, once the provided `leaves` match the number of leaves in the `treespec`, it will not cause any error. The problem with the current implementation is we can remove the registration when we go out of the context manager. Missing flatten/unflatten definition will lead to `KeyError` when the user tries to unflatten the `treespec` back.

> Am I right to say that `torch.vmap` will inherit from the registrations of `torch` namespace?

I think we should make the subnamespace inherit the global namespace. This is easy to implement in the `register_pytree_node` API.

**Comment by zou3519** [comment]
> Unfortunately, things like torch.functional.vmap use tree spec.
> (It depends on custom behaviour for torch.Size, that ought to be localized to vmap's usage.)

I haven't had time to look into this. But it sounds like a vmap bug -- vmap shouldn't rely on custom behavior for torch.Size. If the change is not too BC-breaking, then we should fix it.

**Comment by jon-chuang** [comment]
@zou3519 vmap just wants to check if the in_dims are mapped correctly to torch.Size. I don't think it's a bug per se - but the behaviour should simply not be the default global behaviour, and enabled only for vmap.
