### ISSUE TITLE
torch.export does not work with input mutation

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#112429]
### 🐛 Describe the bug

```python
import torch

class MutationModel(torch.nn.Module):
    def forward(self, x):
        x.view(3, 2, -1).add_(2.0)
        return x
input = (torch.randn(12),)

ep = torch.export.export(MutationModel(), args=input)
```

The backtrace is

```bash
[2023-10-30 19:13:09,023] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "test_log_sigmoid.py", line 10, in <module>
    ep = torch.export.export(MutationModel(), args=input)
  File "/opt/pytorch/torch/export/__init__.py", line 440, in export
    return export__RC__(f, args, kwargs, dynamic_shapes=dynamic_shapes)
  File "/opt/pytorch/torch/_export/__init__.py", line 252, in export__RC__
    return _export(f, args, kwargs, constraints=constraints)
  File "/opt/pytorch/torch/_export/__init__.py", line 596, in _export
    gm_torch_level = _export_to_torch_ir(
  File "/opt/pytorch/torch/_export/__init__.py", line 517, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 1226, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 558, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 148, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 402, in _convert_frame_assert
    return _compile(
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 610, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 527, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 497, in transform
    tracer.run()
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 2127, in run
    super().run()
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 751, in run
    and self.step()
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 714, in step
    getattr(self, inst.opname)(inst)
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 405, in wrapper
    return inner_fn(self, inst)
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 1147, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 586, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/opt/pytorch/torch/_dynamo/variables/misc.py", line 613, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/opt/pytorch/torch/_dynamo/variables/lists.py", line 502, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/opt/pytorch/torch/_dynamo/variables/lists.py", line 183, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/opt/pytorch/torch/_dynamo/variables/base.py", line 336, in call_method
    raise unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/opt/pytorch/torch/_dynamo/exc.py", line 184, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method TupleVariable() view [ConstantVariable(int), ConstantVariable(int), ConstantVariable(int)] {}

from user code:
   File "test_log_sigmoid.py", line 6, in forward
    x.view(3, 2, -1).add_(2.0)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

(ptca) root@88c3e49b4bcf:/opt/pytorch# python test_log_sigmoid.py 
[2023-10-30 19:13:37,587] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "test_log_sigmoid.py", line 11, in <module>
    ep = torch.export.export(MutationModel(), args=input)
  File "/opt/pytorch/torch/export/__init__.py", line 440, in export
    return export__RC__(f, args, kwargs, dynamic_shapes=dynamic_shapes)
  File "/opt/pytorch/torch/_export/__init__.py", line 252, in export__RC__
    return _export(f, args, kwargs, constraints=constraints)
  File "/opt/pytorch/torch/_export/__init__.py", line 696, in _export
    gm, graph_signature = aot_export_module(
  File "/opt/pytorch/torch/_functorch/aot_autograd.py", line 4934, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/opt/pytorch/torch/_functorch/aot_autograd.py", line 5116, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/opt/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/torch/_functorch/aot_autograd.py", line 4345, in create_aot_dispatcher_function
    raise RuntimeError(f"""
RuntimeError: 
Found following user inputs located at [0] are mutated. This is currently banned in the aot_export workflow.
If you need this functionality, please file a github issue.

fw_metadata=ViewAndMutationMeta(input_info=[InputAliasInfo(is_leaf=True, mutates_data=True, mutates_metadata=False, mutations_hidden_from_autograd=False, requires_grad=False)], output_info=[OutputAliasInfo(output_type=<OutputType.is_input: 3>, raw_type=<class 'torch._subclasses.functional_tensor.FunctionalTensor'>, base_idx=0, dynamic_dims=set(), requires_grad=False)], num_intermediate_bases=0, keep_input_mutations=False, traced_tangents=[], subclass_inp_meta=[0], subclass_fw_graph_out_meta=[0, 1], subclass_tangent_meta=[], is_train=False, num_symints_saved_for_bw=None)
```

### Versions

pytorch main branch

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by thiagocrepaldi** [comment]
Another repro

```python
class Model(torch.nn.Module):
    def forward(self, x):
        x[:, x.size(0) :] = 0
        return x
input = (torch.ones(2, 5),)

ep = torch.export.export(Model(), args=input)
```

```bash
[2023-10-30 19:20:05,753] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "test_log_sigmoid.py", line 14, in <module>
    ep = torch.export.export(Model(), args=input)
  File "/opt/pytorch/torch/export/__init__.py", line 440, in export
    return export__RC__(f, args, kwargs, dynamic_shapes=dynamic_shapes)
  File "/opt/pytorch/torch/_export/__init__.py", line 252, in export__RC__
    return _export(f, args, kwargs, constraints=constraints)
  File "/opt/pytorch/torch/_export/__init__.py", line 696, in _export
    gm, graph_signature = aot_export_module(
  File "/opt/pytorch/torch/_functorch/aot_autograd.py", line 4934, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/opt/pytorch/torch/_functorch/aot_autograd.py", line 5116, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/opt/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/torch/_functorch/aot_autograd.py", line 4345, in create_aot_dispatcher_function
    raise RuntimeError(f"""
RuntimeError: 
Found following user inputs located at [0] are mutated. This is currently banned in the aot_export workflow.
If you need this functionality, please file a github issue.

fw_metadata=ViewAndMutationMeta(input_info=[InputAliasInfo(is_leaf=True, mutates_data=True, mutates_metadata=False, mutations_hidden_from_autograd=False, requires_grad=False)], output_info=[OutputAliasInfo(output_type=<OutputType.is_input: 3>, raw_type=<class 'torch._subclasses.functional_tensor.FunctionalTensor'>, base_idx=0, dynamic_dims=set(), requires_grad=False)], num_intermediate_bases=0, keep_input_mutations=False, traced_tangents=[], subclass_inp_meta=[0], subclass_fw_graph_out_meta=[0, 1], subclass_tangent_meta=[], is_train=False, num_symints_saved_for_bw=None)
```

**Comment by tugsbayasgalan** [comment]
We intentionally disallowed any input mutations in the forward due to added complexity. I wonder why we can't use buffer? We support buffer mutation.

**Comment by thiagocrepaldi** [comment]
> We intentionally disallowed any input mutations in the forward due to added complexity. I wonder why we can't use buffer? We support buffer mutation. But I do think the error message should be improved tho

Supporting input mutation would decrease the surface in which the user had to do code-changes on their own to use `torch.export`.

Having said that, an error message with an actionable workaround would improve the user experience too

**Comment by thiagocrepaldi** [comment]
this works now
