### ISSUE TITLE
[torch.compile] Unit test failures after we always trace all module.forward method

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#112424]
After #112233, we always trace all builtin ```module.forward``` method. I'll use this issue to track the latent bugs exposed from this change.

## 1/ AttributeError: '_SpectralNorm' object has no attribute '_u'
Run ```PYTORCH_TEST_WITH_DYNAMO=1 python test/nn/test_parametrization.py -k test_new_spectral_norm```:
```
Traceback (most recent call last):
  File "/home/ybliang/local/pytorch/torch/testing/_internal/common_utils.py", line 2524, in wrapper
    method(*args, **kwargs)
  File "/data/users/ybliang/pytorch/test/nn/test_parametrization.py", line 1102, in test_new_spectral_norm
    with set_default_dtype(torch.double):
  File "/data/users/ybliang/pytorch/test/nn/test_parametrization.py", line 1139, in resume_in_test_new_spectral_norm
    m = torch.nn.utils.parametrizations.spectral_norm(m, 'bias')
  File "/home/ybliang/local/pytorch/torch/nn/utils/parametrizations.py", line 569, in spectral_norm
    parametrize.register_parametrization(module, name, _SpectralNorm(weight, n_power_iterations, dim, eps))
  File "/home/ybliang/local/pytorch/torch/nn/utils/parametrize.py", line 563, in register_parametrization
    parametrizations = ParametrizationList([parametrization], original, unsafe=unsafe)
  File "/home/ybliang/local/pytorch/torch/nn/utils/parametrize.py", line 182, in __init__
    Z = self()
  File "/home/ybliang/local/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ybliang/local/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ybliang/local/pytorch/torch/nn/utils/parametrize.py", line 266, in forward
    x = self[0](self.original)
  File "/home/ybliang/local/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ybliang/local/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "<string>", line 13, in guard
  File "/home/ybliang/local/pytorch/torch/nn/modules/module.py", line 1696, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: '_SpectralNorm' object has no attribute '_u'
```

The failure came from the following lines:
https://github.com/pytorch/pytorch/blob/21330e5ba19b4f22afbd26168eb72bcd8586071d/test/nn/test_parametrization.py#L1137-L1139

## 2/ torch.compile + test_modules.py::test_grad + float64
Example command:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_modules.py -k test_grad_nn_AdaptiveAvgPool1d_cuda_float64
```
Error stack:
```
2023-11-01T21:47:09.9214763Z __________ TestModuleCUDA.test_grad_nn_AdaptiveAvgPool1d_cuda_float64 __________
2023-11-01T21:47:09.9214923Z Traceback (most recent call last):
2023-11-01T21:47:09.9215596Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1144, in _test_batched_grad
2023-11-01T21:47:09.9215789Z     result = vmap(vjp)(torch.stack(grad_outputs))
2023-11-01T21:47:09.9216423Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_vmap_internals.py", line 223, in wrapped
2023-11-01T21:47:09.9216612Z     batched_outputs = func(*batched_inputs)
2023-11-01T21:47:09.9217186Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1124, in vjp
2023-11-01T21:47:09.9217338Z     results = grad(v)
2023-11-01T21:47:09.9217905Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/__init__.py", line 399, in grad
2023-11-01T21:47:09.9218346Z     result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
2023-11-01T21:47:09.9218920Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/function.py", line 289, in apply
2023-11-01T21:47:09.9219063Z     return user_fn(self, *args)
2023-11-01T21:47:09.9219688Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 4085, in backward
2023-11-01T21:47:09.9219842Z     out = call_compiled_backward()
2023-11-01T21:47:09.9220548Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 4051, in call_compiled_backward
2023-11-01T21:47:09.9220687Z     out = call_func_with_args(
2023-11-01T21:47:09.9221379Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1952, in call_func_with_args
2023-11-01T21:47:09.9221523Z     out = normalize_as_list(f(args))
2023-11-01T21:47:09.9222089Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 410, in _fn
2023-11-01T21:47:09.9222223Z     return fn(*args, **kwargs)
2023-11-01T21:47:09.9222811Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
2023-11-01T21:47:09.9222950Z     return fn(*args, **kwargs)
2023-11-01T21:47:09.9223541Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 869, in __call__
2023-11-01T21:47:09.9223730Z     return self.get_current_callable()(inputs)
2023-11-01T21:47:09.9224301Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 672, in run
2023-11-01T21:47:09.9224513Z     copy_misaligned_inputs(new_inputs, inputs_to_check)
2023-11-01T21:47:09.9225201Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 640, in copy_misaligned_inputs
2023-11-01T21:47:09.9225369Z     if new_inputs[i].data_ptr() % ALIGNMENT:
2023-11-01T21:47:09.9225761Z RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
2023-11-01T21:47:09.9225799Z 
2023-11-01T21:47:09.9226092Z The above exception was the direct cause of the following exception:
2023-11-01T21:47:09.9226098Z 
2023-11-01T21:47:09.9226252Z Traceback (most recent call last):
2023-11-01T21:47:09.9226603Z   File "/var/lib/jenkins/workspace/test/test_modules.py", line 503, in test_grad
2023-11-01T21:47:09.9226943Z     self._test_gradients_helper(device, dtype, module_info, training, gradcheck)
2023-11-01T21:47:09.9227373Z   File "/var/lib/jenkins/workspace/test/test_modules.py", line 427, in _test_gradients_helper
2023-11-01T21:47:09.9227740Z     module_inputs = module_info.module_inputs_func(module_info, device=device, dtype=dtype,
2023-11-01T21:47:09.9228221Z   File "/var/lib/jenkins/workspace/test/test_modules.py", line 476, in resume_in__test_gradients_helper
2023-11-01T21:47:09.9228579Z     self.assertTrue(check(fn_to_gradcheck, flat_input, nondet_tol=gradcheck_nondet_tol))
2023-11-01T21:47:09.9229312Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4273, in gradcheck
2023-11-01T21:47:09.9229553Z     return torch.autograd.gradcheck(fn, inputs, **kwargs)
2023-11-01T21:47:09.9230165Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 2051, in gradcheck
2023-11-01T21:47:09.9230314Z     return _gradcheck_helper(**args)
2023-11-01T21:47:09.9231007Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 2105, in _gradcheck_helper
2023-11-01T21:47:09.9231173Z     _test_batched_grad(tupled_inputs, o, i)
2023-11-01T21:47:09.9231892Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1150, in _test_batched_grad
2023-11-01T21:47:09.9232025Z     raise GradcheckError(
2023-11-01T21:47:09.9232815Z torch.autograd.gradcheck.GradcheckError: While computing batched gradients, got: Cannot access data pointer of Tensor that doesn't have storage
```
## 3/ torch.compile + test_modules.py::test_gradgrad + float64
* ```torch.compile with aot_autograd does not currently support double backward```
## 4/ Other module test failures
* torch.nn.functional.triplet_margin_with_distance_loss
  * ```test_modules.py::TestModuleCUDA::test_cpu_gpu_parity_nn_CrossEntropyLoss_cuda_float32 - torch._inductor.exc.CppCompileError: C++ compile error``` 
* torch.nn.CrossEntropyLoss
* torch.nn.Hardswish
* torch.nn.SiLU
* torch.nn.Mish
* torch.nn.InstanceNorm1d
  * ```RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.DoubleTensor [3]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).```
* torch.nn.LPPool2d

Example command:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_modules.py -k test_cpu_gpu_parity_nn_CrossEntropyLoss_cpu_float64
```

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by anijain2305** [comment]
@yanboliang Are we considering the task of tracing through `forward`? Or is it low prio?

**Comment by yanboliang** [comment]
@anijain2305 I think it's low pri until we get more similar requirements.
