### ISSUE TITLE
[torch.jit.script] Expected a value of type 'Tensor' for argument 'b' but instead found type 'bool'.

### ISSUE THREAD

**Issue by sachinkademane** [pytorch/pytorch#112402]
### 🐛 Describe the bug

torch.jit.script fails when trying to utilize mul operator as mul(ones/zeros , True/False), please use below piece of code for repro:

```
import torch

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x1, x2):
        return torch.ops.aten.mul(x1, True)

def main():
    mod = MyModule()
    f = torch.jit.script(mod)
    print(f.graph)

if __name__ == "__main__":
    main()
```

### Error logs

```
Traceback (most recent call last):
  File "mul_repro.py", line 19, in <module>
    main()
  File "mul_repro.py", line 14, in main
    f = torch.jit.script(mod)
  File "/tmp/lib/python3.8/site-packages/torch/jit/_script.py", line 1324, in script
    return torch.jit._recursive.create_script_module(
  File "/tmp/lib/python3.8/site-packages/torch/jit/_recursive.py", line 559, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/tmp/lib/python3.8/site-packages/torch/jit/_recursive.py", line 636, in create_script_module_impl
    create_methods_and_properties_from_stubs(
  File "/tmp/lib/python3.8/site-packages/torch/jit/_recursive.py", line 469, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::mul.Tensor(Tensor self, Tensor other) -> Tensor:
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'bool'.
  
  aten::mul.Scalar(Tensor self, Scalar other) -> Tensor:
  Expected a value of type 'number' for argument 'other' but instead found type 'bool'.
  
  aten::mul.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'bool'.
  
  aten::mul.Scalar_out(Tensor self, Scalar other, *, Tensor(a!) out) -> Tensor(a!):
  Expected a value of type 'number' for argument 'other' but instead found type 'bool'.
  
  aten::mul.left_t(t[] l, int n) -> t[]:
  Could not match type Tensor (inferred) to List[t] in argument 'l': Cannot match List[t] to Tensor (inferred).
  
  aten::mul.right_(int n, t[] l) -> t[]:
  Could not match type bool to List[t] in argument 'l': Cannot match List[t] to bool.
  
  aten::mul.int(int a, int b) -> int:
  Expected a value of type 'int' for argument 'b' but instead found type 'bool'.
  
  aten::mul.complex(complex a, complex b) -> complex:
  Expected a value of type 'complex' for argument 'b' but instead found type 'bool'.
  
  aten::mul.float(float a, float b) -> float:
  Expected a value of type 'float' for argument 'b' but instead found type 'bool'.
  
  aten::mul.int_complex(int a, complex b) -> complex:
  Expected a value of type 'complex' for argument 'b' but instead found type 'bool'.
  
  aten::mul.complex_int(complex a, int b) -> complex:
  Expected a value of type 'int' for argument 'b' but instead found type 'bool'.
  
  aten::mul.float_complex(float a, complex b) -> complex:
  Expected a value of type 'complex' for argument 'b' but instead found type 'bool'.
  
  aten::mul.complex_float(complex a, float b) -> complex:
  Expected a value of type 'float' for argument 'b' but instead found type 'bool'.
  
  aten::mul.int_float(int a, float b) -> float:
  Expected a value of type 'float' for argument 'b' but instead found type 'bool'.
  
  aten::mul.float_int(float a, int b) -> float:
  Expected a value of type 'int' for argument 'b' but instead found type 'bool'.
  
  aten::mul(Scalar a, Scalar b) -> Scalar:
  Expected a value of type 'number' for argument 'b' but instead found type 'bool'.
  
  mul(float a, Tensor b) -> Tensor:
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'bool'.
  
  mul(int a, Tensor b) -> Tensor:
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'bool'.
  
  mul(complex a, Tensor b) -> Tensor:
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'bool'.

The original call is:
  File "mul_repro.py", line 9
    def forward(self, x1, x2):
        return torch.ops.aten.mul(x1, True)
               ~~~~~~~~~~~~~~~~~~ <--- HERE
```

### Versions

Versions of relevant libraries:
```
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0
[pip3] torchaudio==2.1.0
[pip3] torchdata==0.7.0
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by williamwen42** [comment]
cc @davidberard98

**Comment by davidberard98** [comment]
Torchscript doesn't understand that a boolean is a type of scalar. Replace `True/False` with `1/0` to work around the issue, or wrap the True/False in a tensor (`torch.tensor(True)`)
