### ISSUE TITLE
[torch.compile] Expected a value of type 'Tensor' for argument 'other' but instead found type 'bool'.

### ISSUE THREAD

**Issue by sachinkademane** [pytorch/pytorch#112503]
### 🐛 Describe the bug

torch.compile fails while running bitwise_and inplace operation with boolean value

```
import torch

def fn(input1, input2):
    res = input1.bitwise_and_(input2)
    return res

if __name__ == "__main__":
    input1 = torch.randint(1, 10, (2, 3))
    input2 = True
    f = torch.compile(fn)
    f(input1, input2)
```
If I replace "True" to torch.tensor([True]) or 1 as workaround, this case passes without issues

### Error logs

```
tensor([[6, 7, 5],
        [4, 9, 4]])
Traceback (most recent call last):
  File "open_source.py", line 13, in <module>
    f(input1)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "open_source.py", line 5, in fn
    print(input1)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1115, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 594, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/tensor.py", line 655, in call_method
    return wrap_fx_proxy(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1274, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1376, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1399, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1541, in dispatch
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.TorchRuntimeError: Failed running call_method bitwise_and_(*(FakeTensor(..., size=(2, 3), dtype=torch.int64), True), **{}):
aten::bitwise_and_() Expected a value of type 'Tensor' for argument 'other' but instead found type 'bool'.
Position: 1
Value: True
Declaration: aten::bitwise_and_.Tensor(Tensor(a!) self, Tensor other) -> Tensor(a!)
Cast error details: Unable to cast True to Tensor

from user code:
   File "open_source.py", line 6, in <resume in fn>
    input1.bitwise_and_(True)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

Versions of relevant libraries:
```
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0
[pip3] torchaudio==2.1.0
[pip3] torchdata==0.7.0
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by Chillee** [comment]
This runs correctly for me on nightly.
