### ISSUE TITLE
[Breaking change 2.1] Passing non-contiguous inputs to SDPA on CUDA device with the mem-efficient attention backend returns garbage

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#112577]
### 🐛 Describe the bug

Hi @drisspg, after more hours of debugging than I am comfortable to admit, I noticed the following breaking change between PyTorch 2.0.1 and PyTorch 2.1.

The issue can be reproduced both with `torch-2.1.0+cu118` & `2.2.0.dev20231030+cu118`. There is no issue on 2.0.1

For fp32 inputs to SDPA on CUDA device & passing a custom `attn_mask`, we have the following:
* PyTorch 2.0.1: dispatches to math (`RuntimeError: No available kernel. Aborting execution.` for other backends)
* PyTorch 2.1: dispatches to mem-efficient attention (likely following https://github.com/pytorch/pytorch/issues/96099). And it appears that **the mem-efficient attention backend outputs wrong results when passing non-contigous key/value, while the math backend goes just fine**.

Reproduction:

```python
import torch
import copy

num_heads = 16
head_dim = 128
torch.set_printoptions(threshold=1000000, sci_mode=True)

def _attn_sdpa(query, key, value, attention_mask=None, contiguify=False, enable_mem_efficient=False):
    query_shape = query.shape
    batch_size = query_shape[0]
    kv_seq_len = key.shape[-2]

    query_length = query_shape[1]

    # NOTE: Maybe there is better than this?
    query = query.view(batch_size, query_length, num_heads, head_dim).transpose(1, 2)

    # Without these unsqueeze, SDPA complains as the query and key/value have a different number of dimensions.
    key = key.unsqueeze(1)
    value = value.unsqueeze(1)

    # Although these expand are not numerically useful, PyTorch 2.1 can not dispatch to mem-efficient attention
    # and flash attention (No available kernel.  Aborting execution.) from the shapes
    # query = [batch_size, num_heads, query_length, head_dim]
    # key = [batch_size, 1, kv_length, head_dim]
    # value = [batch_size, 1, kv_length, head_dim]
    # which is unfortunate. Hopefully can be improved in the future. These expand should not be too expansive as they do not do memory copy.
    key = key.expand(-1, num_heads, -1, -1)
    value = value.expand(-1, num_heads, -1, -1)


    if contiguify:
        key = key.contiguous()
        value = value.contiguous()

    print("query contiguous", query.is_contiguous())
    print("key contiguous", key.is_contiguous())
    print("value contiguous", value.is_contiguous())

    if enable_mem_efficient:
        enable_math = False
    else:
        enable_math = True

    with torch.backends.cuda.sdp_kernel(enable_flash=False, enable_math=enable_math, enable_mem_efficient=enable_mem_efficient):
        sdpa_result = torch.nn.functional.scaled_dot_product_attention(
            query,
            key,
            value,
            attn_mask=attention_mask,
            dropout_p=0.0,
            is_causal=False,
        )

    return sdpa_result

device = "cpu"

query_sdpa = torch.load("query_sdpa.pt").to(device)
key_sdpa = torch.load("key_sdpa.pt").to(device)
value_sdpa = torch.load("value_sdpa.pt").to(device)
attention_mask_sdpa = torch.load("attention_mask_sdpa.pt").to(device)

print("query_sdpa", query_sdpa.shape)
print("key_sdpa", key_sdpa.shape)
print("value_sdpa", value_sdpa.shape)
print("attention_mask_sdpa", attention_mask_sdpa.shape)
print("attention_mask_sdpa", attention_mask_sdpa)

print("---- non_contig_cpu_math")
res_non_contig_cpu = _attn_sdpa(query_sdpa, key_sdpa, value_sdpa, attention_mask_sdpa, contiguify=False)
print("---- contig_cpu_math")
res_contig_cpu = _attn_sdpa(query_sdpa, key_sdpa, value_sdpa, attention_mask_sdpa, contiguify=True)

device = "cuda"

query_sdpa = torch.load("query_sdpa.pt").to(device)
key_sdpa = torch.load("key_sdpa.pt").to(device)
value_sdpa = torch.load("value_sdpa.pt").to(device)
attention_mask_sdpa = torch.load("attention_mask_sdpa.pt").to(device)

print("---- non_contig_cuda_math")
res_non_contig_cuda_math = _attn_sdpa(query_sdpa, key_sdpa, value_sdpa, attention_mask_sdpa, contiguify=False)
print("---- contig_cuda_math")
res_contig_cuda_math = _attn_sdpa(query_sdpa, key_sdpa, value_sdpa, attention_mask_sdpa, contiguify=True)

print("---- non_contig_cuda_memeff")
res_non_contig_cuda_memeff = _attn_sdpa(query_sdpa, key_sdpa, value_sdpa, attention_mask_sdpa, contiguify=False, enable_mem_efficient=True)
print("---- contig_cuda_memeff")
res_contig_cuda_memeff = _attn_sdpa(query_sdpa, key_sdpa, value_sdpa, attention_mask_sdpa, contiguify=True, enable_mem_efficient=True)

def print_diff(text, tensor1, tensor2):
    print(f"{text}: mean abs-diff", (tensor1 - tensor2).abs().mean())
    print(f"{text}: mean rel-diff", ((tensor1 - tensor2).abs() / (tensor1.abs() + 1e-12)).mean())

print("\n")
print_diff("cpu non-contig/contig", res_non_contig_cpu, res_contig_cpu)
print_diff("cuda non-contig/contig math", res_non_contig_cuda_math, res_contig_cuda_math)
print_diff("cuda non-contig/contig memeff", res_non_contig_cuda_memeff, res_contig_cuda_memeff)

print("\nAllclose CPU non-contig/contig:", torch.allclose(res_non_contig_cpu, res_contig_cpu))
print("Allclose CUDA math non-contig/contig:", torch.allclose(res_non_contig_cuda_math, res_contig_cuda_math))
print("Allclose CUDA memeff non-contig/contig:", torch.allclose(res_non_contig_cuda_memeff, res_contig_cuda_memeff))
```

The result is:
```
query_sdpa torch.Size([1, 1, 2048])
key_sdpa torch.Size([1, 16, 128])
value_sdpa torch.Size([1, 16, 128])
attention_mask_sdpa torch.Size([1, 1, 1, 16])
attention_mask_sdpa tensor([[[[True, True, True, True, True, True, True, True, True, True, True,
           True, True, True, True, True]]]])
---- non_contig_cpu_math
query contiguous True
key contiguous False
value contiguous False
---- contig_cpu_math
query contiguous True
key contiguous True
value contiguous True
---- non_contig_cuda_math
query contiguous True
key contiguous False
value contiguous False
---- contig_cuda_math
query contiguous True
key contiguous True
value contiguous True
---- non_contig_cuda_memeff
query contiguous True
key contiguous False
value contiguous False
---- contig_cuda_memeff
query contiguous True
key contiguous True
value contiguous True


cpu non-contig/contig: mean abs-diff tensor(0.)
cpu non-contig/contig: mean rel-diff tensor(0.)
cuda non-contig/contig math: mean abs-diff tensor(0., device='cuda:0')
cuda non-contig/contig math: mean rel-diff tensor(0., device='cuda:0')
cuda non-contig/contig memeff: mean abs-diff tensor(1.4653e-03, device='cuda:0')
cuda non-contig/contig memeff: mean rel-diff tensor(5.8919e-01, device='cuda:0')

Allclose CPU non-contig/contig: True
Allclose CUDA math non-contig/contig: True
Allclose CUDA memeff non-contig/contig: False
```

Note that these metrics are not super representative of how the drift is bad locally:
![image](https://github.com/pytorch/pytorch/assets/9808326/e912d390-ceda-4f85-a915-d27833caa15c)

[debug_sdpa.zip](https://github.com/pytorch/pytorch/files/13226139/debug_sdpa.zip)

The relevant tensors are attached in a zip here.

Thank you!

### Versions

```
Collecting environment information...
PyTorch version: 2.2.0.dev20231030+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.9.16 (main, May 15 2023, 23:46:34)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 510.73.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3000.006
BogoMIPS:                        6000.01
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] mypy-protobuf==3.4.0
[pip3] numpy==1.24.3
[pip3] onnx==1.13.1
[pip3] onnxruntime-gpu==1.15.1
[pip3] onnxruntime-training==1.15.1
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231030+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by drisspg** [comment]
So for this case the mask passed in is all Trues which will get converted to a "zeros" additive attention_bias mask.. in theory a no-op.

When I run the same q,k,v input with no mask I get 
``` Shell
******************************Mem-eff mask compare******************************
With Mask Contiguity | Without Mask Contiguity
non-contig  |  contig: mean abs-diff tensor(1.4653e-03, device='cuda:0')
non-contig  |  contig: mean rel-diff tensor(6.0943e-01, device='cuda:0')
contig      |  contig: mean abs-diff tensor(0., device='cuda:0')
contig      |  contig: mean rel-diff tensor(0., device='cuda:0')
non-contig  |  non-contig: mean abs-diff tensor(1.4653e-03, device='cuda:0')
non-contig  |  non-contig: mean rel-diff tensor(6.0943e-01, device='cuda:0')
contig      |  non-contig: mean abs-diff tensor(0., device='cuda:0')
contig      |  non-contig: mean rel-diff tensor(0., device='cuda:0')
********************************************************************************
```

**Comment by drisspg** [comment]
If I update the script to only call contiguous on either key or value but not both I still see the same results

**Comment by drisspg** [comment]
Okayy I got it, so this happens when bias_mask is not contiguous

**Comment by fxmarty** [comment]
Weird - so `attention_mask_sdpa` not being contiguous was responsible of the issue?

**Comment by fxmarty** [comment]
@drisspg I can confirm this issue is fixed on `2.2.0.dev20231102+cu118`

**Comment by drisspg** [comment]
Unfortunately

**Comment by drisspg** [comment]
@fxmarty I was acting somewhat rash with the impeding 2.1.1 deadline and I am unhappy with my solution, and I didn't fully think through its ramifications.  For a very hot path I.e. a mask of (1, 1, seq_len_q, seq_len_kv) this causes a substantial memory regression. 

I am having a hard time figure out whats goin on with the repro mentioned here: https://github.com/pytorch/pytorch/pull/114173

The results of the repo appear to be dependent on order in which the ops are ran, which makes me thing there is some IMA happening, but alas I haven't found it.

**Comment by fxmarty** [comment]
Thanks a lot for looking into it @drisspg, sorry for having been a bit pushy about having this in the patch!

I appear not to be able to reproduce the logits difference in https://github.com/pytorch/pytorch/pull/114173 using `2.1.1+cu118` and A100-SXM4-80GB,  is the output difference appearing using the memory patch https://github.com/pytorch/pytorch/pull/114173?

**Comment by bdhirsh** [comment]
Tentatively marking hi-pri for the regression

**Comment by huydhn** [comment]
@drisspg Could you help double check if the memory issue is fixed in 2.1.2?  Here are the results @atalman and myself gets using the reproduction example in the issue:

```
pip3 install torch==2.1.2 --index-url https://download.pytorch.org/whl/test/cu121

...
cpu non-contig/contig: mean abs-diff tensor(0.)
cpu non-contig/contig: mean rel-diff tensor(0.)
cuda non-contig/contig math: mean abs-diff tensor(0., device='cuda:0')
cuda non-contig/contig math: mean rel-diff tensor(0., device='cuda:0')
cuda non-contig/contig memeff: mean abs-diff tensor(1.4653e-03, device='cuda:0')
cuda non-contig/contig memeff: mean rel-diff tensor(5.8919e-01, device='cuda:0')

Allclose CPU non-contig/contig: True
Allclose CUDA math non-contig/contig: True
Allclose CUDA memeff non-contig/contig: False
```

This is the same as what we get from 2.1.0

**Comment by drisspg** [comment]
@huydhn 
So the memory issue was "fixed" in 2.1.1 via this PR: https://github.com/andreigh/pytorch/commit/f00fb17dfe3956f269c053c7c27da8e741d5e5ce

While this did change the result of the repro, it caused a memory usage "regression" for a very common hot path for SDPA. 

This PR: https://github.com/pytorch/pytorch/pull/114837 Was used to fix the memory regression. I did further analysis on the initial correctness report. I determined that the repro wasn't behaving as I expected.. e.g the order with which aten ops were called impacted. 

I am also not entirely sure that a contiguous vs non contiguous input should produce identical results (it likely should but I need to reason if there is some potential float addmulitple ops that get reordered cc @danthe3rd )

I was leaving this open in case we need to revisit this but the the memory reduction should be visible via usual memory profiling techniques

**Comment by fxmarty** [comment]
@drisspg I can also confirm that this issue is reintroduced in the 2.1.2 release, while it was fixed in 2.1.1.

This is a bit bad for us as following 2.1.1 we added SDPA by default in Transformers and a very common execution path has non-contiguous inputs: https://github.com/huggingface/transformers/blob/4b759da8be71ac025610d91881a18b592adf701c/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L553. We'll likely have to do a patch and manually call `.contiguous()`, I guess.

Here, silently SDPA starts outputting different results when inputs are not contiguous, which I think is not wishable. If the kernel requires contiguous inputs, why not check it on the C++ side and call `contiguous()` if needed (maybe with a warning)?

**Comment by drisspg** [comment]
@fxmarty do you have a repro for the illegal memory access? I wasn't able to re-repro this with the existing one in this issue.

**Comment by fxmarty** [comment]
I don't have a minimal reproduction unfortunately, but you can try:

```bash
pip uninstall torch torchaudio torchvision
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/test/cu118
git clone https://github.com/huggingface/transformers.git
cd transformers
git checkout 5e4ef0a0f6eaf0b80eb951a674939d68ab30f6e5
pip install -e .
```

and run `CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python test_bigcode.py` with the following script:

```python
from transformers import GPTBigCodeForCausalLM, AutoTokenizer
import torch

with torch.device("cuda"):
    model = GPTBigCodeForCausalLM.from_pretrained("bigcode/starcoderbase-1b")
tokenizer = AutoTokenizer.from_pretrained("bigcode/starcoderbase-1b")
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side = "left"

model = model.eval()
inp = tokenizer(["def quick_sort(", "a =", "print('I"], padding=True, return_tensors="pt").to("cuda")

# This one works.
with torch.backends.cuda.sdp_kernel(enable_flash=False, enable_math=True, enable_mem_efficient=False):
    res = model.generate(**inp, num_beams=1, do_sample=False, min_new_tokens=60, max_new_tokens=60)

for dec in tokenizer.batch_decode(res):
    print("---- math")
    print(dec)

# This one errors out.
with torch.backends.cuda.sdp_kernel(enable_flash=False, enable_math=False, enable_mem_efficient=True):
    res = model.generate(**inp, num_beams=1, do_sample=False, min_new_tokens=60, max_new_tokens=60)

for dec in tokenizer.batch_decode(res):
    print("---- mem-efficient")
    print(dec)
```

which errors at:
```
  File "/fsx/felix/condaenvs/fx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/felix/transformers/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 621, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/fsx/felix/transformers/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 553, in _attn
    sdpa_result = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This corresponds to this code: https://github.com/huggingface/transformers/blob/5e4ef0a0f6eaf0b80eb951a674939d68ab30f6e5/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L515-L562

Note that on `main` of Transformers you will not be able to reproduce as for now I just disabled the mem-efficient path for GPT BigCode due to this issue (fix at https://github.com/huggingface/transformers/pull/27973, removing the expand).

**Comment by atalman** [comment]
@fxmarty Is it possible to have minimal repro for this ? Running using your instructions I get following:
```
Traceback (most recent call last):
  File "/data/home/atalman/temp33/transformers/test_big.py", line 5, in <module>
    model = GPTBigCodeForCausalLM.from_pretrained("bigcode/starcoderbase-1b")
  File "/data/home/atalman/temp33/transformers/src/transformers/modeling_utils.py", line 2789, in from_pretrained
    resolved_config_file = cached_file(
  File "/data/home/atalman/temp33/transformers/src/transformers/utils/hub.py", line 404, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to request access at https://huggingface.co/bigcode/starcoderbase-1b and pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`.
```

**Comment by fxmarty** [comment]
Oh sorry. You can try with `TabbyML/SantaCoder-1B` instead that is non-gated. I'll try to come up with a minimal repro ASAP. I edited my message above.

**Comment by drisspg** [comment]
Running above command produced for me:


Notable Environment differences:
CUDA-12.1
PyTorch: Main
GPU: H100


``` Python
❯ CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python scripts/sdpa/hugging_face_bug.py
/home/drisspg/meta/transformers/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/drisspg/meta/transformers/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Setting `pad_token_id` to `eos_token_id`:49152 for open-end generation.
---- math
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        left = []
        right = []
        for i in arr:
            if i < pivot:
                left.append(i)
            else:
                right.append(
---- math
<|endoftext|><|endoftext|><|endoftext|>a = 0; a < 10; a++) {
            for (int b = 0; b < 10; b++) {
                for (int c = 0; c < 10; c++) {
                    for (int d = 0; d < 
---- math
<|endoftext|><|endoftext|>print('I am a child of'+ parent.name)

class Parent(Person):
    def __init__(self, name):
        super().__init__(name)
        self.children = []

    def add_child(self, child):
        self.children.append(child)
        child
Setting `pad_token_id` to `eos_token_id`:49152 for open-end generation.
---- mem-efficient
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        left = arr[i for i in arr[1:] if i < pivot]
        right = arr[i for i in arr[!!!!!!
---- mem-efficient
<|endoftext|><|endoftext|><|endoftext|>a = 
package com.google.api.ads.dfp.jaxws.v201502.video;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.api.bind.annotation.XmlAccessorType;
!!!!!!
---- mem-efficient
<|endoftext|><|endoftext|>print('I am a program to find the sum of all the numbers in a given range.

# import the random module
import random

# create a function to generate a random number
def random_number():
    return random.

# a function to generate!!!!!!
````

**Comment by drisspg** [comment]
While the repro isn't throwing a IMA compute-sanitizer is reporting errors:
https://gist.github.com/drisspg/a9269f422d13a67ee94610f8246951a8

**Comment by drisspg** [comment]
Current gists with compute-sanitizer outputs: https://gist.github.com/drisspg/a9269f422d13a67ee94610f8246951a8

**Comment by drisspg** [comment]
I have a fix: https://github.com/pytorch/pytorch/pull/116234 🤞

**Comment by huydhn** [comment]
I rerun the script to confirm that this is fixed in 2.2.0

```
query_sdpa torch.Size([1, 1, 2048])
key_sdpa torch.Size([1, 16, 128])
value_sdpa torch.Size([1, 16, 128])
attention_mask_sdpa torch.Size([1, 1, 1, 16])
attention_mask_sdpa tensor([[[[True, True, True, True, True, True, True, True, True, True, True,
           True, True, True, True, True]]]])
---- non_contig_cpu_math
query contiguous True
key contiguous False
value contiguous False
---- contig_cpu_math
query contiguous True
key contiguous True
value contiguous True
---- non_contig_cuda_math
query contiguous True
key contiguous False
value contiguous False
---- contig_cuda_math
query contiguous True
key contiguous True
value contiguous True
---- non_contig_cuda_memeff
query contiguous True
key contiguous False
value contiguous False
---- contig_cuda_memeff
query contiguous True
key contiguous True
value contiguous True


cpu non-contig/contig: mean abs-diff tensor(0.)
cpu non-contig/contig: mean rel-diff tensor(0.)
cuda non-contig/contig math: mean abs-diff tensor(0., device='cuda:0')
cuda non-contig/contig math: mean rel-diff tensor(0., device='cuda:0')
cuda non-contig/contig memeff: mean abs-diff tensor(0., device='cuda:0')
cuda non-contig/contig memeff: mean rel-diff tensor(0., device='cuda:0')

Allclose CPU non-contig/contig: True
Allclose CUDA math non-contig/contig: True
Allclose CUDA memeff non-contig/contig: True
```

**Comment by drisspg** [comment]
Okay I am going to close this issue for now
