### ISSUE TITLE
torch.compile a for loop that reduces with mul, sub, div

### ISSUE THREAD

**Issue by ydwu4** [pytorch/pytorch#112656]
### 🐛 Describe the bug

```python 
import torch

a = torch.randn(3, 3)
b = torch.randn(3, 3)
c = torch.randn(3, 3)
flat_inp = (a, b, c)

def reduce_sub(flattened):
    init = 1
    for val in flattened:
        init -= val
    return init

def reduce_mul(flattened):
    init = 1
    for val in flattened:
        init *= val
    return init

def reduce_div(flattened):
    init = 1
    for val in flattened:
        init /= val
    return init

def test_func(reduce_func, inp):
    torch._dynamo.reset()
    return torch.compile(reduce_func, backend="eager")(inp)

# Ok
reduce_div(flat_inp)
# Ok
reduce_mul(flat_inp)
# Ok
reduce_sub(flat_inp)
# Error
test_func(reduce_sub, flat_inp)
# Error
test_func(reduce_mul, flat_inp)
# Error
test_func(reduce_div, flat_inp)
```

### Error logs

```
Traceback (most recent call last):
  File "/home/yidi/local/pytorch/repro.py", line 37, in <module>
    test_func(reduce_sub, flat_inp)
  File "/home/yidi/local/pytorch/repro.py", line 31, in test_func
    return torch.compile(reduce_func, backend="eager")(inp)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 558, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 687, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 148, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 406, in _convert_frame_assert
    return _compile(
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 633, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 614, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 531, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 501, in transform
    tracer.run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2119, in run
    super().run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 752, in run
    and self.step()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 715, in step
    getattr(self, inst.opname)(inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2230, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/yidi/local/pytorch/torch/_dynamo/output_graph.py", line 870, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/yidi/local/miniconda3/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/yidi/local/pytorch/torch/_dynamo/output_graph.py", line 986, in compile_and_call_fx_graph
    gm = fx.GraphModule(root, self.graph)
  File "/home/yidi/local/pytorch/torch/fx/graph_module.py", line 426, in __init__
    self.graph = graph
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1755, in __setattr__
    super().__setattr__(name, value)
  File "/home/yidi/local/pytorch/torch/fx/graph_module.py", line 470, in graph
    self.recompile()
  File "/home/yidi/local/pytorch/torch/fx/graph_module.py", line 722, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals, co_fields)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 120, in fx_forward_from_src_skip_result
    result: types.FunctionType = original_forward_from_src(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/fx/graph_module.py", line 88, in _forward_from_src
    return _method_from_src(
  File "/home/yidi/local/pytorch/torch/fx/graph_module.py", line 98, in _method_from_src
    _exec_with_source(src, globals_copy, co_fields)
  File "/home/yidi/local/pytorch/torch/fx/graph_module.py", line 84, in _exec_with_source
    exec(compile(src, key, "exec"), globals)
torch._dynamo.exc.InternalTorchDynamoError: 'literal' is an illegal expression for augmented assignment (<eval_with_key>.0, line 8)
```

### Versions

devgpu on master branch

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by davidberard98** [comment]
more minimal repro @stroxler :
```python
import torch

def fn(x):
    y = 1
    y -= x
    return y

x = torch.rand((4, 4))

fn(x)
torch.compile(fn, backend="eager")(x)
```
