### ISSUE TITLE
AssertionError: Global state changed while dynamo tracing, please report a bug

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#112787]
### 🐛 Describe the bug

In my code, I have a context manager class that modifies the default dtype:

```python
import torch

class DtypeContextManager:
    def __init__(self, dtype):
        self._previous_dtype = torch.get_default_dtype()
        self._new_dtype = dtype
    def __enter__(self) -> None: torch.set_default_dtype(self._new_dtype)
    def __exit__(self, exc_type, exc_value, traceback): torch.set_default_dtype(self._previous_dtype)

def fn():
    t = torch.tensor(0)
    for i in range(10):
        ctx = DtypeContextManager(torch.bfloat16)
        with ctx:
            t = t.add(i)
    return t

fn = torch.compile(fn)
print(fn())
```

This raises the error listed below.

Interestingly, if the dtype is hard-coded, then the code runs normally

```python
import torch

class DtypeContextManager:
    def __enter__(self) -> None: torch.set_default_dtype(torch.bfloat16)
    def __exit__(self, exc_type, exc_value, traceback): torch.set_default_dtype(torch.float32)

def fn():
    t = torch.tensor(0)
    for i in range(10):
        ctx = DtypeContextManager()
        with ctx:
            t = t.add(i)
    return t

fn = torch.compile(fn)
print(fn())
```

### Error logs

```python
Traceback (most recent call last):
  File "/home/carlos/kk.py", line 20, in <module>
    print(fn())
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 411, in _fn
    return fn(*args, **kwargs)
  File "/home/carlos/kk.py", line 14, in fn
    with ctx:
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 559, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 683, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 160, in _fn
    assert (
AssertionError: Global state changed while dynamo tracing, please report a bug
```

### Versions

`torch==2.2.0.dev20231030+cu121`

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by jon-chuang** [comment]
Let me take a look. It should be possible to restore the initial values. It's probably an issue with `get_default_dtype` being constant folded.

**Comment by jon-chuang** [comment]
I am unable to reproduce your results on latest main. Could you try installing a newer version of pytorch or installing main from source?

**Comment by carmocca** [comment]
Oh you are right! I thought 20231030 was recent enough :P

Thank you

**Comment by carmocca** [comment]
Hi @jon-chuang, this seems to have regressed because the repro snippet in the top post is failing again.

I have `torch==2.3.0.dev20240301+cu121` installed. I haven't bisected which commit broke this again.

Reopening the issue
