### ISSUE TITLE
 Error loading "AppData\Local\Temp\_MEI136882\torch\lib\cufft64_10.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by mendickxiao** [pytorch/pytorch#112955]
### 🐛 Describe the bug

My python project can run successfully in pycharm in the debug and run mode. But when I build an exe by the auto-py-to-exe, and run it, throw an error. 

PS C:\Users\flydog\Work\code\DosePrediction_1\output> .\dose_prediction.exe
Traceback (most recent call last):
  File "src\predict.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "src\model\network_trainer.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "torch\__init__.py", line 122, in <module>
OSError: [WinError 998] 内存位置访问无效。 Error loading "C:\Users\flydog\AppData\Local\Temp\_MEI136882\torch\lib\cufft64_10.dll" or one of its dependencies.
[21416] Failed to execute script 'predict' due to unhandled exception!

My python requirements:
altgraph==0.17.4
auto-py-to-exe==2.41.0
bottle-websocket==0.2.9
bottle==0.12.25
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.0
click==8.1.7
colorama==0.4.6
contourpy==1.1.1
cycler==0.12.1
Eel==0.16.0
filelock==3.12.4
filetype==1.2.0
fonttools==4.43.1
fsspec==2023.9.2
future==0.18.3
gevent-websocket==0.10.1
gevent==23.9.1
greenlet==3.0.0
idna==3.4
imageio==2.31.5
Jinja2==3.1.2
kiwisolver==1.4.5
lazy-loader==0.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.2
numpy==1.26.1
opencv-python==4.8.1.78
packaging==23.2
pandas==2.1.1
pefile==2023.2.7
Pillow==10.1.0
pip==22.3.1
psutil==5.9.6
pycparser==2.21
pydicom==2.4.3
pyinstaller-hooks-contrib==2023.10
pyinstaller==6.1.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32-ctypes==0.2.2
PyYAML==6.0.1
qci-worker==23.7.11
qciplugin==0.4.1
requests==2.31.0
scikit-image==0.22.0
scipy==1.11.3
setuptools==65.5.1
SimpleITK==2.3.0
six==1.16.0
soundfile==0.12.1
sqlmap==1.7.8
sympy==1.12
threadpool==1.3.2
tifffile==2023.9.26
torch==2.0.0+cu118
torchaudio==2.0.1+cu118
torchvision==0.15.1+cu118
tqdm==4.66.1
typing-extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
websocket-client==1.2.1
wheel==0.38.4
whichcraft==0.6.1
zope.event==5.0
zope.interface==6.1

I tested the same environment in the python 3.6 with lower torch version, there is no error. The exe can run successfully.
The python 3.6 requirements:
altgraph==0.17.3
auto-py-to-exe==2.29.0
bottle-websocket==0.2.9
bottle==0.12.25
cffi==1.15.1
cloudpickle==2.2.1
cycler==0.11.0
dask==2021.3.0
dataclasses==0.8
decorator==4.4.2
Eel==0.14.0
future==0.18.3
gevent-websocket==0.10.1
gevent==22.10.2
greenlet==2.0.2
importlib-metadata==4.8.3
kiwisolver==1.3.1
matplotlib==3.0.2
networkx==2.5.1
numpy==1.19.5
opencv-python==4.4.0.46
pandas==0.23.4
pefile==2023.2.7
Pillow==8.4.0
pip==21.3.1
pycparser==2.21
pydicom==2.3.1
pyinstaller-hooks-contrib==2022.0
pyinstaller==4.10
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyWavelets==1.1.1
pywin32-ctypes==0.2.0
PyYAML==6.0
scikit-image==0.14.2
scipy==1.1.0
setuptools==59.6.0
SimpleITK==1.2.2
six==1.16.0
toolz==0.12.0
torch==1.10.2+cu113
torchaudio==0.10.2+cu113
torchvision==0.11.3+cu113
tqdm==4.26.0
typing-extensions==4.1.1
wheel==0.37.1
whichcraft==0.6.1
zipp==3.6.0
zope.event==4.6
zope.interface==5.5.2

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[conda] _anaconda_depends         2023.09             py311_mkl_1
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h6b88ed4_46357
[conda] mkl-service               2.4.0           py311h2bbff1b_1
[conda] mkl_fft                   1.3.8           py311h2bbff1b_0
[conda] mkl_random                1.2.4           py311h59b6b97_0
[conda] numpy                     1.24.3          py311hdab7c0b_1
[conda] numpy-base                1.24.3          py311hd01c5d8_1
[conda] numpydoc                  1.5.0           py311haa95532_0
[conda] pytorch                   2.1.0           py3.11_cuda12.1_cudnn8_0    pytorch
[conda] pytorch-cuda              12.1                 hde6ce7c_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by mendickxiao** [comment]
The log in auto-py-to-exe:
Running auto-py-to-exe v2.41.0
Building directory: C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf
Provided command: pyinstaller --noconfirm --onefile --console --name "dose_prediction" --hidden-import "pydicom.encoders.pylibjpeg" --hidden-import "pydicom.encoders.gdcm"  "C:/Users/flydog/Work/code/DosePrediction_1/src/predict.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --name dose_prediction --hidden-import pydicom.encoders.pylibjpeg --hidden-import pydicom.encoders.gdcm C:/Users/flydog/Work/code/DosePrediction_1/src/predict.py --distpath C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\application --workpath C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\build --specpath C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf

890681 INFO: PyInstaller: 6.1.0
890694 INFO: Python: 3.11.6
890735 INFO: Platform: Windows-10-10.0.22621-SP0
890743 INFO: wrote C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\dose_prediction.spec
890871 INFO: UPX is available and will be used if enabled on build targets.
890890 INFO: Extending PYTHONPATH with paths
['C:\\Users\\flydog\\Work\\code\\DosePrediction_1']
893001 INFO: checking Analysis
893009 INFO: Building Analysis because Analysis-00.toc is non existent
893025 INFO: Initializing module dependency graph...
893053 INFO: Caching module graph hooks...
893083 INFO: Analyzing base_library.zip ...
894845 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
894932 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
896349 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
898413 INFO: Caching module dependency graph...
898514 INFO: Running Analysis Analysis-00.toc
898527 INFO: Looking for Python shared library...
898530 INFO: Using Python shared library: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\python311.dll
898543 INFO: Analyzing C:\Users\flydog\Work\code\DosePrediction_1\src\predict.py
899303 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\_pyinstaller'...
900255 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
900525 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
900735 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
901568 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
901600 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
902172 INFO: Loading module hook 'hook-psutil.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
904577 INFO: Loading module hook 'hook-torch.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
905433 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
905533 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
908266 INFO: Loading module hook 'hook-sympy.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
909613 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
910342 INFO: Processing pre-safe import module hook gi from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
910710 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
910807 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
911329 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
911818 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
914281 INFO: Processing pre-safe import module hook distutils from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
914293 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
914842 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
914961 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
916921 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
917687 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
920223 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
921625 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
921871 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
931971 INFO: Loading module hook 'hook-scipy.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
932569 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
932747 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
935944 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
942369 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
943983 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
945171 INFO: Loading module hook 'hook-pandas.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
948241 INFO: Loading module hook 'hook-pytz.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
949893 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
953314 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
955843 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
967951 INFO: Loading module hook 'hook-charset_normalizer.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
969949 INFO: Loading module hook 'hook-scipy.io.matlab.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
972320 INFO: Loading module hook 'hook-torchvision.ops.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
975440 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
980373 INFO: Loading module hook 'hook-cv2.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
981056 INFO: Analyzing hidden import 'pydicom.encoders.pylibjpeg'
981071 INFO: Analyzing hidden import 'pydicom.encoders.gdcm'
981090 INFO: Processing module hooks...
981171 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
981187 INFO: Matplotlib backend selection method: automatic discovery of used backends
981254 INFO: Discovered Matplotlib backend(s) via `matplotlib.use()` call in module 'sympy.testing.runtests': ['Agg', 'Agg']
981279 INFO: The following Matplotlib backends were discovered by scanning for `matplotlib.use()` calls: ['Agg', 'Agg']. If your backend of choice is not in this list, either add a `matplotlib.use()` call to your code, or configure the backend collection via hook options (see: https://pyinstaller.org/en/stable/hooks-config.html#matplotlib-hooks).
981297 INFO: Selected matplotlib backends: ['Agg', 'Agg']
981975 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
982618 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
982645 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
982667 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
982717 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks'...
1031674 INFO: Looking for ctypes DLLs
1032056 WARNING: Ignoring /usr/lib64/libgomp.so.1 imported from C:\Users\flydog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\_inductor\codecache.py - only basenames are supported with ctypes imports!
1032140 INFO: Analyzing run-time hooks ...
1032176 INFO: Including run-time hook 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
1032198 INFO: Including run-time hook 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
1032228 INFO: Including run-time hook 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
1032249 INFO: Including run-time hook 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
1032286 INFO: Including run-time hook 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
1032297 INFO: Including run-time hook 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
1032322 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
1032790 INFO: Looking for dynamic libraries
1049650 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy.libs', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pandas.libs', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\matplotlib.libs', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\matplotlib.libs', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\scipy.libs', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\torch\\lib', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\torchvision', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\torchvision', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\torchvision', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\torchvision', 'C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\cv2\\../../x64/vc14/bin']
1049654 INFO: Extra DLL search directories (PATH): ['C:\\Users\\flydog\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\cv2\\../../x64/vc14/bin']
1055181 INFO: Warnings written to C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\build\dose_prediction\warn-dose_prediction.txt
1055578 INFO: Graph cross-reference written to C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\build\dose_prediction\xref-dose_prediction.html
1056027 INFO: checking PYZ
1056042 INFO: Building PYZ because PYZ-00.toc is non existent
1056056 INFO: Building PYZ (ZlibArchive) C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\build\dose_prediction\PYZ-00.pyz
1060352 INFO: Building PYZ (ZlibArchive) C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\build\dose_prediction\PYZ-00.pyz completed successfully.
1060702 INFO: checking PKG
1060709 INFO: Building PKG because PKG-00.toc is non existent
1060720 INFO: Building PKG (CArchive) dose_prediction.pkg
1068901 INFO: Disabling UPX for C:\Windows\system32\VCOMP140.DLL due to CFG!
1397490 INFO: Building PKG (CArchive) dose_prediction.pkg completed successfully.
1397826 INFO: Bootloader C:\Users\flydog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
1397829 INFO: checking EXE
1397849 INFO: Building EXE because EXE-00.toc is non existent
1397865 INFO: Building EXE from EXE-00.toc
1397882 INFO: Copying bootloader EXE to C:\Users\flydog\AppData\Local\Temp\tmppa5ubxnf\application\dose_prediction.exe
1397995 INFO: Copying icon to EXE
1398074 INFO: Copying 0 resources to EXE
1398087 INFO: Embedding manifest in EXE
1398165 INFO: Appending PKG archive to EXE
1401993 INFO: Fixing EXE headers
1415256 INFO: Building EXE from EXE-00.toc completed successfully.

Moving project to: C:\Users\flydog\Work\code\DosePrediction_1\output
Complete.

**Comment by malfet** [comment]
Thank you for filing the issue, but it does not look like a PyTorch problem, but more like a `py-to-exe`  one (or may be it just needs to be configured differently, but it clearly indicates that some of the dependencies has not been packaged correctly)

Please use https://discuss.pytorch.org/ to ask question on how PyTorch can be used in a specific environments. (My

**Comment by alinpahontu2912** [comment]
Hey @mendickxiao, are you still dealing with this issue? Did you build pytorch yourself or installed it via pip/conda ? Have you tried using the latest release, does that help?

**Comment by alinpahontu2912** [comment]
Closing this issue due to inactivity, but feel free to open a new one if needed
