### ISSUE TITLE
Unsupported unwinding pattern error in aarch64 platform

### ISSUE THREAD

**Issue by coyotelll** [pytorch/pytorch#113208]
### 🐛 Describe the bug

Command:
`python test/test_cuda.py -k test_memory_snapshot_with_cpp`

Stacktrace:
```
[W unwind.cpp:222] Warning: Did not find a PT_GNU_EH_FRAME segment for linux-vdso.so.1 (function libraryFor)
[W unwind.cpp:222] Warning: Did not find a PT_GNU_EH_FRAME segment for linux-vdso.so.1 (function libraryFor)
[W unwind.cpp:195] Warning: Unsupported unwinding pattern: addr not in range of known libraries (function unwinderFor)
/opt/pytorch/pytorch/test/test_cuda.py:3443: UserWarning: Unsupported unwinding pattern: addr not in range of known libraries (Triggered internally at /opt/pytorch/pytorch/torch/csrc/profiler/unwind/unwind.cpp:195.)
  x = torch.rand(311, 411, device='cuda')
F
======================================================================
FAIL: test_memory_snapshot_with_cpp (__main__.TestCudaMallocAsync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2410, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_cuda.py", line 3450, in test_memory_snapshot_with_cpp
    self.assertTrue('::rand' in str(b['frames']))
AssertionError: False is not true

To execute this test, run the following from the base repo dir:
     python test/test_cuda.py -k test_memory_snapshot_with_cpp

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 0.015s

FAILED (failures=1) 
```

Relevant PR:
https://github.com/pytorch/pytorch/pull/104707 which enables aarch64 in https://github.com/pytorch/pytorch/blob/8cee0a25bd5444d633347beab61473db3ae3f25a/torch/csrc/profiler/unwind/unwind.cpp#L4. 
We are thus seeing error from https://github.com/pytorch/pytorch/blob/8cee0a25bd5444d633347beab61473db3ae3f25a/torch/csrc/profiler/unwind/unwind.cpp#L195. 
Which kind of ARM arch were we expecting to support here, ARM server or APPLE-ARM? Please let me know if more info is needed to reproduce the issue. Thanks.

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98 @malfet @snadampal @Aidyn-A @ptrblck 

### Versions

```
Collecting environment information...
PyTorch version: 2.2.0a0+6a974be
Is debug build: False
CUDA used to build PyTorch: 12.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.7
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-72-generic-aarch64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Vendor ID:                       ARM
Model name:                      Neoverse-N1
Model:                           1
Thread(s) per core:              1
Core(s) per cluster:             80
Socket(s):                       -
Cluster(s):                      1
Stepping:                        r3p1
Frequency boost:                 disabled
CPU max MHz:                     2800.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        50.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
L1d cache:                       5 MiB (80 instances)
L1i cache:                       5 MiB (80 instances)
L2 cache:                        80 MiB (80 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; CSV2, BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.14.1
[pip3] optree==0.9.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.2.0a0+6a974be
[pip3] torch-tensorrt==2.2.0a0
[pip3] torchdata==0.7.0a0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.17.0a0
[conda] Could not collect```

**Comment by davidberard98** [comment]
cc @zdevito @andrewjcg

**Comment by zdevito** [comment]
I don't think the unwinder code really supports any arm architecture. @andrewjcg added some code to invoke the `unwind_c` function in arm assembly, but there is more of the unwinder code that is specialized to capture registers RBP, and RSP which I think will be different numbers on arm, and the kinds of unwinding patterns that typical arm compilers emit might be different than the ones this x86-specific unwinder supports. The path to fix this is to either complete the support for arm in the unwinder, or to back out the pathway that makes it think it can use the unwinder on arm.

**Comment by coyotelll** [comment]
@zdevito Thanks for reviewing the issue and for the comment!

> The path to fix this is to either complete the support for arm in the unwinder, or to back out the pathway that makes it think it can use the unwinder on arm.

Would this next action depend on @andrewjcg or is there anything we could assist on our end? As far as I am concerned, the support for arm may take a while to process.

**Comment by zdevito** [comment]
x86 needs a complicated unwinding machine because we need to look at dwarf information since there are not frame pointers in most x86 code. aarch64 does have a frame pointer register, so unwinding is actually quite simple: the frame pointers basically form a linked list with frame pointer register (29) can be treated as a `Entry*`:
```
struct Entry {
   Entry* next_fp;
   uint64_t addr;
}
```
So we can just bypass the unwinder library logic and do a simple walk of this structure to get the pointers. The problem is that I do not have a aarch64 linux machine to try it on.

**Comment by snadampal** [comment]
Hi @zdevito, did you check if you could use AWS t4g instances, they have free trail.
https://aws.amazon.com/ec2/instance-types/t4/

**Comment by malfet** [comment]
Let me see if I can get a reproducer on my end
