### ISSUE TITLE
code crashes on CI when using keep-going flag on PR

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#113419]
### 🐛 Describe the bug

I'm looking into https://github.com/pytorch/pytorch/pull/113061 where there are some weird failed tests showing up, i.e https://hud.pytorch.org/pr/pytorch/pytorch/113061#18505218585

```
/tmp/torchinductor_jenkins/cmcsowevfiurv7watfhwx2lot2pmcirzder7raxbz3ceuxtxucc5/c7kslyvrtkpc7ozemrz4chqgxbsskg3wswoxgktrzzz3f3ngpyly.cpp:327:115: error: cannot convert ‘AtenTensorOpaque**’ to ‘double’
```

Taking a closer look, this is not a failed tests at all, but just a debug message for an XFAIL test case.  The failure I think is actually at the bottom:

```
Running test_show_pickle 1/1 ... [2023-11-09 01:54:47.274095]
Executing ['/opt/conda/envs/py_3.10/bin/python', '-bb', 'test_show_pickle.py', '--shard-id=0', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '--reruns=2', '--import-slow-tests', '--import-disabled-tests'] ... [2023-11-09 01:54:47.274320]

test_show_pickle 1/1 was successful, full logs can be found in artifacts with path test/test-reports/test_show_pickle_1.1_db31c64655854f9c_.log
Running 1 items in this shard: test/test_show_pickle.py::TestShowPickle::test_scripted_model

Starting test batch 'unlikely_relevance' 5252.8884534835815 seconds after initiating testing
With sharding, this batch will run 0 tests
Starting test batch 'none_relevance' 5252.8884818553925 seconds after initiating testing
With sharding, this batch will run 0 tests
/var/lib/jenkins/workspace/tools/stats/upload_metrics.py:164: UserWarning: Error uploading metric td_experiment_1 to DynamoDB: Unsupported type "<class 'tools.testing.test_run.TestRun'>" for value "dynamo/test_activation_checkpointing"
  warn(f"Error uploading metric {metric_name} to DynamoDB: {e}")
holup, retry
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1832, in <module>
    main()
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1806, in main
    test_stats = aggregated_heuristics.get_test_stats(test)
  File "/var/lib/jenkins/workspace/tools/testing/target_determination/heuristics/interface.py", line 391, in get_test_stats
    metrics = heuristic_results.get_priority_info_for_test(test)
  File "/var/lib/jenkins/workspace/tools/testing/target_determination/heuristics/interface.py", line 307, in get_priority_info_for_test
    relevance = self._get_test_relevance_group(test_run)
  File "/var/lib/jenkins/workspace/tools/testing/target_determination/heuristics/interface.py", line 278, in _get_test_relevance_group
    raise ValueError(f"Test {test_run} not found in any relevance group")
ValueError: Test inductor/test_aot_inductor not found in any relevance group

real	87m36.722s
user	131m37.048s
sys	8m2.312s
```

The PR uses `keep-going` and this is the second times I see a PR using `keep-going` failing with lots of unrelated failures.  So, something weird is going on here

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @ZainRizvi @kit1980 @clee2000

**Comment by huydhn** [comment]
May be another way to frame the issue here is that if `keep-going` is used, the test jobs would be super flaky as I see from another example here https://hud.pytorch.org/pr/111129

**Comment by malfet** [comment]
It started to affect ROCm CI and it kind of breaks the first principle of any speculative heuristics: it should never abandon tests...

Also, this message is not super useful:
```
% grep 'raise ValueError(f"Test {test_run} not found in any relevance group")' target_determination/heuristics/interface.py 
            raise ValueError(f"Test {test_run} not found in any relevance group")
        raise ValueError(f"Test {test_run} not found in any relevance group")
        raise ValueError(f"Test {test_run} not found in any relevance group")
        raise ValueError(f"Test {test_run} not found in any relevance group")

```

**Comment by malfet** [comment]
Ok, removing hi-pri as errors are usually red herring for the real failures

**Comment by clee2000** [comment]
I'm currently working on improving the keep-going flag

That TD code only gets run if a test fails.  Even though it doesnt really affect CI results, I disabled what I think is the cause https://github.com/pytorch/pytorch/pull/113497 and @ZainRizvi is currently looking at it

I have a issue for test_aot_inductor specifically since I also see it without the keep-going flag on main branch https://github.com/pytorch/pytorch/issues/113691

**Comment by clee2000** [comment]
keep-going label should be fixed in https://github.com/pytorch/pytorch/pull/112098
