### ISSUE TITLE
Better user experience for using Generator object

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#11340]
Not a comprehensive list, but we should:

1. Document `torch.Generator` better, e.g., it's only CPU RNG, examples, ctor, etc.
2. Provide CUDA equivalent of `torch.Generator`.
3. Provide better transformation between `Generator` and `rng_state`.
3. Document that `torch.manual_seed` seeds **all** CUDA devices.
4. Support `generator=` keyword argument in `torch.nn.init.*` (at least the stochastic ones).
5. Support `generator=` keyword argument for distributions classes (?)

**Comment by vishwakftw** [comment]
https://github.com/pytorch/pytorch/issues/1614 covers the first point on the list.

**Comment by syed-ahmed** [comment]
I will be submitting a PR end of this week which will be addressing some parts of this issue.

**Comment by syed-ahmed** [comment]
I'll be able to share a more up to date diff tomorrow but here's a gist of what's coming:

1. I'm modifying the `GeneratorDerived` template to have a `RNGState` struct definition. (The struct definition will replace `THGenerator` as well, but for now I'm focusing on the cuda part and just passing `'th_generator': 'CUDARNGState* generator',` from `gen.py` for the `CUDAGenerator`.
```
#pragma once

// ${generated_comment}

#include <$header>

#include "ATen/core/Generator.h"

struct ${name}RNGState {$name}RNGState;

namespace at {

class Context;
struct ${name}Generator : public Generator {
  ${name}Generator(Context * context);
  virtual ~${name}Generator();

  virtual ${name}Generator& copy(const Generator& from) override;
  virtual ${name}Generator& free() override;

  virtual uint64_t seed() override;
  virtual uint64_t seedAll() override;
  virtual uint64_t initialSeed() override;
  virtual ${name}Generator& manualSeed(uint64_t seed) override;
  virtual ${name}Generator& manualSeedAll(uint64_t seed) override;
  virtual void * unsafeGetTH() override;

//TODO(zach): figure out friends later
public:
  Context * context;
  ${th_generator}
};
```
2. The CUDARNGState is then being defined in `CUDAGenerator.cpp` and looks like this. Note: I might change this slightly to have Philox related state variables. Also might add getters and setters through `CUDAContext` for the RNGState:
```
struct CUDARNGState {
  std::mutex mutex; /* mutex for using this generator */
  int initf;
  uint64_t initial_seed;
  std::atomic<int64_t> philox_seed_offset;
  int64_t device = -1;
};
```
3. The rest of the PR then modifies the `CUDAGenerator.cpp` to port the `THCRandom_*` related code, initializing the device states only once (like it's done in @mruberry 's Port Stream PR), and adding Runtian's Philox Generator (from fusion_compiler) as the default generator for CUDA in a `Random.h` module (like how the mersenne twister is the default for `TH_random`.  Note: this PR also aims to remove curand usages. Hence, there will be implementations of `rand_uniform, rand_normal, rand_lognormal, rand_poisson` in the Random.h module.

Another additional proposal for the CPU side I had was to use std::random with the mersenne_twister_engine from std, but I haven't got to that part.  Please let me know how this sounds.

**Comment by ezyang** [comment]
I'm not terribly familiar with how the current Generator setup is, but some thoughts.

* Consolidating Generator, CPUGenerator, CUDAGenerator, THGenerator and THCGenerator is good news. Obviously we should still have a CPU generator and a CUDA generator, but no need for TH.
* Your plan talks about CUDA only. Are you also planning to adjust the CPU situation?
* Your proposed new CUDARNGState struct has less fields than `THCGeneratorState`  (e.g., it no longer stores `gen_states`). Is this because it doesn't need it anymore?

**Comment by syed-ahmed** [comment]
Thanks for the feedback! 

Yes, I do plan to adjust the CPU situation. How I'm looking at it is, the current notion of `Generator` is confusing in the framework. That is, generator is referred to as the **state** of a generator in pytorch, whereas I would refer a generator to be the **engine** used to generate pseduo random numbers. Since there is this confusion, you will see that the `THCState` has `THCRNGState`, whereas the CPU doesn't have any notion of RNGState but a `THGenerator`. In other words, `THCRNGState` and `THGenerator` are really the same - a container for the states of the generator. The only difference is `THCRNGState` has one state container (`THCGenerator`) per device. Hence, if we are to make a unified state container for both CPU and GPU, we can have the same struct, but the CPU side will only have one container. That is my rationale behind consolidating those structs. 

The proposed CUDARNGState lacks the states for Runtian's Philox generator (`uint4 counter; uint4 output; uint2 key; unsigned int STATE;`) as I'm still deciding if it's really needed/how to expose them. Otherwise, we don't need the gen_states, since I'm making the `deafult_generator` for the CUDA to use Runtian's Philox implementation from `fusion_compiler` whereas the CPU side currently uses custom Mersenne Twister implementation. My proposal for the `default_generator` on the CPU side is to use the `std::mersenne_twister_engine` and get rid of the custom implementation we have in `THRandom.cpp` unless there is a good reason why we needed the custom implementation (I'm assuming we needed those because of C FFI reasons and now we can fallback to using `std` because of ATen).

**Comment by syed-ahmed** [comment]
@gchanan @ezyang @SsnL I'm not done with the PR yet but here is a diff showing what I'm thinking: https://github.com/syed-ahmed/pytorch/commit/36278a00db089104bccac89d14ed3db8b6ba1237

In summary, Generators will have a struct/state called CPUGenerator/CUDAGenerator. Each of these structs will have PRNG engines (for instance, for CPU you can have `std::mt19937` and for CUDA, I'm defining Runtian's philox as `at::Philox4_32_10`). They will have an API exposed through Context.h that would enable the user to modify the state of the generators and their engines.

**Comment by syed-ahmed** [comment]
I have couple of questions:
1. Regarding generator UX: when we set the seed of the generator engine (for instance: philox), do we reset its state, i.e. for instance philox needs an `offset`, do we set the offset to zero when we set the seed everytime? For the CPU side, if we were to use `std:mt19937` and called `seed(123)` on it, `std` does a re-init before seeding the engine. 
```
g = torch.Generator()
g.seed(123)
```
2. The default engines for CPU and CUDA will diverge with this PR, i.e. CPU will use mersenne twister (as it does now, except use it from `std`) and CUDA will use Philox. This means that `torch.Generator()` and `torch.cuda.Generator()` will produce different sequences of random numbers if given the same seed. How concerning is it? If it's a problem, do we need a CPU version of Philox engine?

**Comment by apaszke** [comment]
1. Yes. Two generators (of the same type) that received the same seed should always produce the same random sequence. If we didn't reset the offset, then they might produce different results if they were used a different number of times.
2. That doesn't concern me. We don't guarantee that our operations return the same results across devices. If you want to reproduce someone else's results, you should use the same configuration. It would be great if we could preserve the same sequences across GPU architectures, but not necessarily with CPU. They are devices with completely different performance characteristics, and locking ourselves to a particular PRNG implementation would be too limiting.

**Comment by ezyang** [comment]
It might be nice if we optionally had a CPU RNG implementation that was bit-for-bit compatible with the CUDA one, though :) But that's a separate matter.

**Comment by apaszke** [comment]
Oh, for sure. It would be awesome if we could implement a CPU-side Philox that would match/improve the perf of our mersene twister, and give us the same results as we get in CUDA land. I'm not sure if that's possible though, since the way we partition the workload on CPU and GPU are quite different.

**Comment by syed-ahmed** [comment]
@apaszke Thanks for the comments. Could you please elaborate a little bit on what you mean by preserving same sequences across GPU architectures? I am a bit confused.

Also, does anyone know what should be the resolution for this comment in `THRandom.cpp`?

```
// TODO: this only returns 32-bits of randomness but as a uint64_t. This is
// weird and should be fixed. We should also fix the state to be uint32_t
// instead of uint64_t. (Or switch to a 64-bit random number generator).
```

**Comment by kittipatv** [comment]
6. would be great for reproducibility.

**Comment by syed-ahmed** [comment]
Update:
~1. Document torch.Generator better, e.g., it's only CPU RNG, examples, ctor, etc.~
    - documentation added in https://pytorch.org/docs/master/torch.html#generators
~2. Provide CUDA equivalent of torch.Generator.~
    - cuda generators can now be created with `torch.Generator(device='cuda')`
~3. Provide better transformation between Generator and rng_state.~
    - `torch.Generator` is now analogous to `numpy.random.RandomState`. The CPU side holds `at::mt19937` as its rng state and the CUDA side has two uint64_ts (seed, offset) as its rng state.
~6. Support generator= keyword argument for distributions classes (?)~
    - distributions should now be able to handle generator objects properly. e.g.:
```
>>> import torch
>>> a = torch.Generator(device='cuda')
>>> b = torch.FloatTensor(10).cuda().uniform_(generator=a)
>>> b
tensor([0.3931, 0.5116, 0.8851, 0.4404, 0.8998, 0.1218, 0.5304, 0.3333, 0.2389,
        0.5041], device='cuda:0')
>>> a = torch.Generator()
>>> b = torch.FloatTensor(10).cuda().uniform_(generator=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

>>> a = torch.Generator(device='cuda')
>>> torch.normal(torch.Tensor([0.5]).cuda(), 0.5, generator=a)
tensor([-0.3292], device='cuda:0')

>>> a = torch.Generator()
>>> torch.normal(torch.Tensor([0.5]).cuda(), 0.5, generator=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

```
TODO:
4. **Document that torch.manual_seed seeds all CUDA devices.** - We are also discussing whether torch.manual_seed returning generator is the right thing to do: https://github.com/pytorch/pytorch/issues/15867
5. **Support generator= keyword argument in torch.nn.init.\* (at least the stochastic ones).** - Not sure what is meant by this @SsnL . Is it about the functions in torch/nn/init.py?

**Comment by SsnL** [comment]
@syed-ahmed Thanks so much for working on this. 

> 5. Support generator= keyword argument in torch.nn.init.* (at least the stochastic ones).
Yes, I meant those functions. Most of them sample from gaussian or uniform.

> 6. Support generator= keyword argument for distributions classes (?)
This is true for the random sampling **functions**, but not the `torch.distributions.*` classes.  cc @fritzo on this.

**Comment by SsnL** [comment]
@syed-ahmed I've changed the description of this issue into a checklist to track your progress! Thanks again!

**Comment by ringohoffman** [comment]
What about being able to use a `Generator` as a context manager like [`fork_rng`](https://pytorch.org/docs/stable/random.html#torch.random.fork_rng) that temporarily replaces the global state with the `Generator`'s state.

It's not always possible or practical to use generators instead of the global state. Modules like [`Dropout`](https://pytorch.org/docs/stable/generated/torch.nn.Dropout.html) advance the global RNG state without even a way to specify a generator to use. Also, if you are consuming a model, it isn't practical to modify the model's definition to pass in the generator everywhere it *is* possible.

@ezyang any thoughts on this?

**Comment by ringohoffman** [comment]
Also it would be cool if you could pickle `Generator`s.

```python
>>> import torch
>>> torch.save(torch.Generator(), "generator")
TypeError: cannot pickle 'torch._C.Generator' object
```

**Comment by ezyang** [comment]
We can probably do the same playbook as torch.device context manager with a torch function mode. Seems reasonable to me.

The pickling also seems doable!
