### ISSUE TITLE
[ONNX] STFT ExportProgram error

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#113504]
Running `torch.export.export` on an STFT model is successful but ONNX export fails with errors.

```python
import onnx
import torch
import numpy as np
import onnxruntime as ort

import onnx.inliner
import onnx.reference


class STFTModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self._window = torch.hann_window(window_length=320)

    def forward(self, signals: torch.Tensor) -> torch.Tensor:
        x = signals.stft(
            n_fft=512,
            hop_length=160,
            win_length=320,
            return_complex=True,
            window=self._window,
            pad_mode="constant",
        )
        return x


m = STFTModel()
m.eval()

batch_size = 2
signal_length = 16000

# Export
# Shape [B, T] audio signals
input_signals = torch.randn([batch_size, signal_length])
args = (input_signals,)
# Note: static dims
exported_program = torch.export.export(m, args)
print(exported_program)
exported_model = torch.onnx.dynamo_export(
    # m,
    exported_program,
    *args,
)

print("output shape", m(input_signals).shape)

# Load and attempt to run
# NOTE: Start from here to load the model and reproduce error
onnx_model = exported_model.model_proto
print("ONNX check ok")
# onnx_model = onnx.inliner.inline_local_functions(onnx_model)
# onnx.shape_inference.infer_shapes(onnx_model, check_type=True, strict_mode=True, data_prop=True)
onnx.save_model(onnx_model, f"stft_inlined_batch_{batch_size}.onnx")
print("Instantiate session")
session: ort.InferenceSession = ort.InferenceSession(
    onnx_model.SerializeToString(), providers=["CPUExecutionProvider"]
)
# Need static shape... use same as exported
np_signals = input_signals.numpy()
print(f"Run ONNX graph with signals of shape {np_signals.shape}")
# Exporter also gives parameter a weird name: signals -> l_signals_
outputs = session.run(None, {"arg0": np_signals})
expected = torch.view_as_real(m(input_signals)).numpy()

np.testing.assert_allclose(outputs[0], expected)
```

### Exported program

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, arg0_1: f32[320], arg1_1: f32[2, 16000]):
            # File: /home/justinchu/dev/onnx-script/test.py:16, code: x = signals.stft(
            view: f32[1, 2, 16000] = torch.ops.aten.view.default(arg1_1, [1, 2, 16000]);  arg1_1 = None
            constant_pad_nd: f32[1, 2, 16512] = torch.ops.aten.constant_pad_nd.default(view, [256, 256], 0.0);  view = None
            view_1: f32[2, 16512] = torch.ops.aten.view.default(constant_pad_nd, [2, 16512]);  constant_pad_nd = None
            constant_pad_nd_1: f32[512] = torch.ops.aten.constant_pad_nd.default(arg0_1, [96, 96]);  arg0_1 = None
            unfold: f32[2, 101, 512] = torch.ops.aten.unfold.default(view_1, -1, 512, 160);  view_1 = None
            mul: f32[2, 101, 512] = torch.ops.aten.mul.Tensor(unfold, constant_pad_nd_1);  unfold = constant_pad_nd_1 = None
            _fft_r2c: c64[2, 101, 257] = torch.ops.aten._fft_r2c.default(mul, [2], 0, True);  mul = None
            permute: c64[2, 257, 101] = torch.ops.aten.permute.default(_fft_r2c, [0, 2, 1]);  _fft_r2c = None
            return (permute,)
            
Graph signature: ExportGraphSignature(parameters=[], buffers=['L__self____window'], user_inputs=['arg1_1'], user_outputs=['permute'], inputs_to_parameters={}, inputs_to_buffers={'arg0_1': 'L__self____window'}, buffers_to_mutate={}, backward_signature=None, assertion_dep_token=None)
Range constraints: {}
Equality constraints: []
```

### Trace back

```
/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py:130: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(
Traceback (most recent call last):
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1196, in dynamo_export
    ).export()
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 941, in export
    graph_module = self.options.fx_tracer.generate_fx(
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 199, in generate_fx
    graph_module, graph_guard = torch._dynamo.export(
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1213, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 154, in wrapped
    return output_adapter.apply(model_func(*args, **kwargs))
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/export/exported_program.py", line 369, in __call__
    self._check_input_constraints(*ordered_params, *ordered_buffers, *args)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/export/exported_program.py", line 664, in _check_input_constraints
    _assertion_graph(*args)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/fx/graph_module.py", line 726, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/fx/graph_module.py", line 305, in __call__
    raise e
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/fx/graph_module.py", line 292, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 549, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 142, in _fn
    return fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 575, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 497, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 467, in transform
    tracer.run()
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2107, in run
    super().run()
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 747, in run
    and self.step()
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 710, in step
    getattr(self, inst.opname)(inst)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 405, in wrapper
    return inner_fn(self, inst)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1143, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 654, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1304, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1533, in wrap_fx_proxy_cls
    unimplemented(
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 184, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.sym_size.int

from user code:
   File "<eval_with_key>.14", line 5, in forward
    sym_size = torch.ops.aten.sym_size.int(arg0_1, 0);  arg0_1 = None

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justinchu/dev/onnx-script/test.py", line 40, in <module>
    exported_model = torch.onnx.dynamo_export(
  File "<@beartype(torch.onnx._internal.exporter.dynamo_export) at 0x7f83d18b72e0>", line 53, in dynamo_export
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1207, in dynamo_export
    raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
```

### SARIF

```json
{
 "runs":[
  {
   "tool":{
    "driver":{
     "name":"torch.onnx.dynamo_export",
     "contents":[
      "localizedData",
      "nonLocalizedData"
     ],
     "language":"en-US",
     "rules":[],
     "version":"2.2.0.dev20231011+cpu"
    }
   },
   "language":"en-US",
   "newlineSequences":[
    "\r\n",
    "\n"
   ],
   "results":[]
  }
 ],
 "version":"2.1.0",
 "schemaUri":"https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/schemas/sarif-schema-2.1.0.json"
}
```

**Comment by justinchuby** [comment]
cc @thiagocrepaldi @BowenBao

**Comment by vadimkantorov** [comment]
Also, I wonder, if it's always better to lower STFT to a Conv1d with a FFT basis? This way should be more amenable to fusions (which might outweight the benefit of using more an actual FFT impls)

**Comment by vadimkantorov** [comment]
At least, it might be useful to support some argument to torch.stft indicating that it needs to run with a `mode = "conv"` backend and lower to conv1d or a separate stft_conv function. It's also useful to support publicly-available helper methods: for constructing DFT-basis, for needing paddings etc.

**Comment by vadimkantorov** [comment]
Also, might be related for efficient FFT: https://twitter.com/realDanFu/status/1724127071902011611

**Comment by thiagocrepaldi** [comment]
Changing the repro to

```python
import onnx
import torch
import numpy as np
import onnxruntime as ort

import onnx.inliner
import onnx.reference


class STFTModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self._window = torch.hann_window(window_length=320)

    def forward(self, signals: torch.Tensor) -> torch.Tensor:
        x = signals.stft(
            n_fft=512,
            hop_length=160,
            win_length=320,
            return_complex=True,
            window=self._window,
            pad_mode="constant",
        )
        return x


m = STFTModel()
m.eval()

batch_size = 2
signal_length = 16000

# Export
# Shape [B, T] audio signals
input_signals = torch.randn([batch_size, signal_length])
args = (input_signals,)
# Note: static dims
exported_program = torch.export.export(m, args)
print(exported_program)
exported_model = torch.onnx.dynamo_export(
    # m,
    exported_program,
    *args,
)

outputs = exported_model(*args)
expected = torch.view_as_real(m(input_signals)).numpy()

np.testing.assert_allclose(outputs[0], expected, atol=1e-4, rtol=1e-4)
```

The model exports and passes (with accuracy of 1e-4) for both model `torch.nn.Module` and `torch.export.ExportedProgram`.

Is that enough?

**Comment by justinchuby** [comment]
> Is that enough?

I think so!

> Also, might be related for efficient FFT: [twitter.com/realDanFu/status/1724127071902011611](https://twitter.com/realDanFu/status/1724127071902011611)

This is an interesting read

**Comment by vadimkantorov** [comment]
> Also, I wonder, if it's always better to lower STFT to a Conv1d with a FFT basis?

For this question - conv1d can be considerably slower, but sometimes it's an acceptable slowdown. I'd suggest that there should be a helper method producing conv1d weight tensor, accepting the same arguments as torch.stft
