### ISSUE TITLE
[PT2.1][torch.compile][out variant] normal_operator - AssertionError: len(constraint) == t.dim()

### ISSUE THREAD

**Issue by sachinkademane** [pytorch/pytorch#113554]
### 🐛 Describe the bug

torch.compile is causing assertion error while running normal operator with out variant

please use below sample code to reproduce

```
import torch

def fn(mean, std, tout):
    torch.normal(mean, std, out=tout)
    return tout

if __name__ == "__main__":
    tout = torch.empty([10]).to(torch.float)
    fn = torch.compile(fn)
    print(
        fn(
            torch.tensor(1).to(torch.float),
            torch.tensor(5).to(torch.float),
            tout,
        )
    )
```

### Error logs

```
Traceback (most recent call last):
  File "xyz.py", line 16, in <module>
    fn(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 549, in compile_inner
    check_fn = CheckFunctionManager(
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 929, in __init__
    guard.create(local_builder, global_builder)
  File "/tmp/lib/python3.8/site-packages/torch/_guards.py", line 243, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/tmp/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 599, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/tmp/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 2633, in produce_guards
    assert len(constraint) == t.dim()
AssertionError: 


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

torch                   2.1.0a0
torch-tb-profiler       0.4.0             
torchaudio              2.1.0     
torchdata               0.7.0    
torchmetrics            1.2.0             
torchtext               0.16.0a0 
torchvision             0.16.0 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by wconstab** [comment]
This bug may have been fixed already. Can you rerun on latest nightly and confirm (@sachinkademane)? 

I get the following output from your repro script:

```
/data/users/whc/pytorch/torch/_prims_common/wrappers.py:168: UserWarning: An output with one or more elements was resized since it had shape torch.Size([10]) which does not match the required output shape {str(shape)}. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0).
  warnings.warn(msg)
/data/users/whc/pytorch/out.py:3: UserWarning: An output with one or more elements was resized since it had shape [10], which does not match the required output shape []. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /data/users/whc/pytorch/aten/src/ATen/native/Resize.cpp:35.)
  def fn(mean, std, tout):
tensor(-5.1928)
```

**Comment by sachinkademane** [comment]
@wconstab Yes, on latest nightly I can get correct output, looks like it has been fixed with PT2.2

```
/tmp/.venv_PT_Nightly/lib/python3.8/site-packages/torch/_prims_common/wrappers.py:168: UserWarning: An output with one or more elements was resized since it had shape torch.Size([10]) which does not match the required output shape {str(shape)}. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0).
  warnings.warn(msg)
opensource.py:4: UserWarning: An output with one or more elements was resized since it had shape [10], which does not match the required output shape []. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.normal(mean, std, out=tout)
tensor(2.7800)
```
