### ISSUE TITLE
test_get_rank_size_group is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#11364]
The error complains of broken pipe:

```
02:21:52 test_get_rank_size_full_group (__main__.TestDistBackend) ... ok
02:21:53 test_get_rank_size_group (__main__.TestDistBackend) ... Process process 1:
02:21:53 Traceback (most recent call last):
02:21:53   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
02:21:53     self.run()
02:21:53   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
02:21:53     self._target(*self._args, **self._kwargs)
02:21:53   File "test_distributed.py", line 1274, in _run
02:21:53     getattr(self, self.id().split(".")[2])()
02:21:53   File "test_distributed.py", line 1216, in wrapper
02:21:53     fn(self)
02:21:53   File "test_distributed.py", line 252, in test_get_rank_size_group
02:21:53     group_id = dist.new_group(group)
02:21:53   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/c10d/distributed_c10d.py", line 1075, in new_group
02:21:53     input_ranks)
02:21:53   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/c10d/distributed_c10d.py", line 275, in _new_process_group_helper
02:21:53     pg = ProcessGroupGloo(store, rank, world_size)
02:21:53 RuntimeError: Broken pipe
02:21:53 Process process 2:
02:21:53 Traceback (most recent call last):
02:21:53   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
02:21:53     self.run()
02:21:53   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
02:21:53     self._target(*self._args, **self._kwargs)
02:21:53   File "test_distributed.py", line 1274, in _run
02:21:53     getattr(self, self.id().split(".")[2])()
02:21:53   File "test_distributed.py", line 1216, in wrapper
02:21:53     fn(self)
02:21:53   File "test_distributed.py", line 252, in test_get_rank_size_group
02:21:53     group_id = dist.new_group(group)
02:21:53   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/c10d/distributed_c10d.py", line 1075, in new_group
02:21:53     input_ranks)
02:21:53   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/c10d/distributed_c10d.py", line 275, in _new_process_group_helper
02:21:53     pg = ProcessGroupGloo(store, rank, world_size)
02:21:53 RuntimeError: Broken pipe
02:21:53 FAIL
02:21:53 test_irecv (__main__.TestDistBackend) ... skipped 'Gloo does not support irecv'
02:21:53 test_isend (__main__.TestDistBackend) ... skipped 'Gloo does not support isend'
02:21:53 test_reduce_full_group_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_full_group_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_full_group_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_full_group_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_group_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_group_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_group_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_group_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_multigpu (__main__.TestDistBackend) ... skipped 'Only Nccl backend supports reduce multigpu'
02:21:53 test_reduce_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
02:21:53 test_reduce_sum_cuda (__main__.TestDistBackend) ... skipped 'Only Nccl supports CUDA reduce'
02:21:53 test_scatter (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
02:21:53 test_scatter_full_group (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
02:21:53 test_scatter_group (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
02:21:53 test_send_recv (__main__.TestDistBackend) ... skipped 'Gloo does not support send/recv'
02:21:53 test_send_recv_any_source (__main__.TestDistBackend) ... skipped 'Gloo does not support send/recv from any source'
02:21:53 
02:21:53 ======================================================================
02:21:53 FAIL: test_get_rank_size_group (__main__.TestDistBackend)
02:21:53 ----------------------------------------------------------------------
02:21:53 Traceback (most recent call last):
02:21:53   File "test_distributed.py", line 1214, in wrapper
02:21:53     self._join_and_reduce(fn)
02:21:53   File "test_distributed.py", line 1290, in _join_and_reduce
02:21:53     self.assertEqual(p.exitcode, first_process.exitcode)
02:21:53   File "/var/lib/jenkins/workspace/test/common.py", line 370, in assertEqual
02:21:53     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
02:21:53 AssertionError: 1 not less than or equal to 1e-05 : 
02:21:53 
```

Sample log: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda8-cudnn6-py3-multigpu-test/12694//console

CC @teng-li @pietern

**Comment by pietern** [comment]
What's happening is that process with rank 0 exits earlier than the other processes and takes down the TCP k/v store that it is hosting with it. This explains the "broken pipe" error. Adding a barrier to test teardown to fix this (and hopefully some other) flaky tests.

**Comment by pietern** [comment]
This is odd. The first process (rank 0) exits with code 0 (success) and the other two (ranks 1 and 2) exit with code 1 (presumably caused by the broken pipe error). BUT, there is a barrier call in `TestDistBackend._run` prior to exiting. Only explanation for this error so far is that the first process is falling through the barrier without actually waiting on the other processes to reach it.

**Comment by pietern** [comment]
Did some static analysis but no luck so far. With a single driver process for these tests that ends up spawning one sub process per rank, all tests are fully serialized, so there can't be any interference between tests on the barrier. The barrier code itself also looks sane and is completely reset between tests.

@teng-li Any takes on this?

**Comment by teng-li** [comment]
@ezyang Is this still happening?

**Comment by ezyang** [comment]
I haven't seen it recently.
