### ISSUE TITLE
[ONNX] ONNX export fails when combining tracing and scripting in the presence of symbolic functions

### ISSUE THREAD

**Issue by ekaden** [pytorch/pytorch#113652]
### 🐛 Describe the bug

Exporting to ONNX fails when combining tracing and scripting in the presence of symbolic functions. The following code has been non-functional since Commit #94746 (in particular PyTorch v2.0, v2.1 and latest nightly builds), but runs as expected in PyTorch v1.13.1:

```python
import torch


class SubModelImpl(torch.autograd.Function):
  @staticmethod
  def symbolic(g, x):
    return g.op('custom::Identity', x).setType(x.type())

  @staticmethod
  def forward(ctx, x):
    return x


class SubModel(torch.nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return SubModelImpl.apply(x)


class Model(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.submodel_trace = torch.jit.trace(SubModel(), torch.randn((5, ), dtype=torch.float32))

  def forward(self, x: torch.Tensor, n: int) -> torch.Tensor:
    for _ in range(n):
      x = self.submodel_trace(x)
    return x


model_script = torch.jit.script(Model())
x = torch.randn((5, ), dtype=torch.float32)
n = 3

torch.onnx.export(
  model_script,
  (x, n),
  '/tmp/test.onnx',
  verbose=True)
```

The error message reads (here shown for nvcr.io/nvidia/pytorch:23.10-py3):
```
Torch IR graph at exception: graph(%x.1 : Float(5, strides=[1], requires_grad=0, device=cpu),
      %n.1 : Long(device=cpu)):
  %10 : Bool(device=cpu) = prim::Constant[value={1}](), scope: Model::
  %x.2 : Tensor = prim::Loop(%n.1, %10, %x.1), scope: Model:: # /workspace/test_export.py:33:4
    block0(%5 : Long(device=cpu), %x.11 : Float(5, strides=[1], requires_grad=0, device=cpu)):
      %x.5 : Tensor = ^SubModelImpl[inplace=0, module="__main__"]()(%x.11), scope: Model::/SubModel::submodel_trace # /usr/local/lib/python3.10/dist-packages/torch/autograd/function.py:539:0
        block0(%x : Float(5, strides=[1], requires_grad=0, device=cpu)):
          %9 : Float(5, strides=[1], requires_grad=0, device=cpu) = aten::view_as(%x, %x) # /usr/local/lib/python3.10/dist-packages/torch/autograd/function.py:539:0
          -> (%9)
      -> (%10, %x.5)
  return (%x.2)

Traceback (most recent call last):
  File "/workspace/test_export.py", line 42, in <module>
    torch.onnx.export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1582, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 679, in _optimize_graph
    _C._jit_pass_lint(graph)
RuntimeError: 0 INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/ir/ir.cpp":589, please report a bug to PyTorch. 6 not in scope
```

### Versions

```
PyTorch version: 2.1.0a0+32f93b1
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 537.13
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        7
BogoMIPS:                        4389.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_vnni flush_l1d arch_capabilities
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        12 MiB (12 instances)
L3 cache:                        16.5 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] onnx==1.14.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0a0+32f93b1
[pip3] torch-tensorrt==0.0.0
[pip3] torchdata==0.7.0a0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0a0
[pip3] triton==2.1.0+e621604
[conda] Could not collect
```

**Comment by janeyx99** [comment]
@justinchuby is this expected behavior after your change?

**Comment by justinchuby** [comment]
The error is unexpected. I believe we fixed some errors for autograd functions in a later commit, but this needs to be better examined

**Comment by MaanavD** [comment]
Hi @ekaden,

Please try this with pytorch 2.1 and the `torch.onnx.dynamo_export` api - closing this issue in the meantime, but please reopen if it's relevant and that doesn't work.
