### ISSUE TITLE
torch.profiler Trace view in Tensorboard is displayed as empty on RoCm version of PyTorch

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#113760]
### 🐛 Describe the bug

Hi, using the following script:

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from torch.profiler import ProfilerActivity, profile, tensorboard_trace_handler
import torch

with torch.device("cuda"):
    model = AutoModelForCausalLM.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")

inp = tokenizer("Today I am in Paris and", return_tensors="pt").to("cuda")

with profile(
    activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA],
    record_shapes=True,
    profile_memory=True,
    with_stack=True,
    on_trace_ready=tensorboard_trace_handler(dir_name=f"./tb_logs/mylog"),
):
    res = model.generate(**inp, num_beams=1, max_new_tokens=1)
```

produces a nice trace (through tensorboard) with `torch==2.1.0+cu118`:

![image](https://github.com/pytorch/pytorch/assets/9808326/cb4ae777-d955-403b-ac76-2cfce92d7621)

But when the trace is captured with `2.1.0+rocm5.6` (same issue as well with `torch==2.2.0.dev20231106+rocm5.7)`, the trace can't load:

![image](https://github.com/pytorch/pytorch/assets/9808326/3d654e05-11e5-4a6f-ba39-67df9c7e6fb3)

Other features of the profiler ("GPU Kernel", "Operator" tabs) are fine.

A few logs are printed when loading into tensorboard in the RoCm case, as e.g. `W1115 14:49:31.006731 140355848750912 gpu_metrics_parser.py:180] pid '2' is not equal to args.device 'None' on event with ts '1700055803985211'`.

I am thus wondering if torch.profiler supports RoCm.

Thank you!

### Versions

On torch 2.1 + RoCm, this script gives:

```
Collecting environment information...
Traceback (most recent call last):
  File "//collect_env.py", line 612, in <module>
    main()
  File "//collect_env.py", line 595, in main
    output = get_pretty_env_info()
  File "//collect_env.py", line 590, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "//collect_env.py", line 462, in get_env_info
    nvidia_gpu_models=get_gpu_info(run_lambda),
  File "//collect_env.py", line 141, in get_gpu_info
    (" ({})".format(torch.cuda.get_device_properties(0).gcnArchName) if torch.version.hip is not None else "")
AttributeError: 'torch._C._CudaDeviceProperties' object has no attribute 'gcnArchName'
```

On torch nightly + RoCm:
```
PyTorch version: 2.2.0.dev20231106+rocm5.7
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.7.31921-d1770ee1b

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI210 (gfx90a:sramecc+:xnack-)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.7.31921
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      48 bits physical, 48 bits virtual
CPU(s):                             96
On-line CPU(s) list:                0-95
Thread(s) per core:                 1
Core(s) per socket:                 48
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          AuthenticAMD
CPU family:                         25
Model:                              1
Model name:                         AMD EPYC 7643 48-Core Processor
Stepping:                           1
Frequency boost:                    enabled
CPU MHz:                            1500.000
CPU max MHz:                        3640.9170
CPU min MHz:                        1500.0000
BogoMIPS:                           4600.20
Virtualization:                     AMD-V
L1d cache:                          3 MiB
L1i cache:                          3 MiB
L2 cache:                           48 MiB
L3 cache:                           512 MiB
NUMA node0 CPU(s):                  0-47
NUMA node1 CPU(s):                  48-95
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-protobuf==3.4.0
[pip3] numpy==1.26.0
[pip3] pytorch-triton-rocm==2.1.0+34f8189eae
[pip3] torch==2.2.0.dev20231106+rocm5.7
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] pytorch-triton-rocm       2.1.0+34f8189eae          pypi_0    pypi
[conda] torch                     2.2.0.dev20231106+rocm5.7          pypi_0    pypi
(base) root@hf-amd-mi210-dev:/# [conda] torch                     2.2.0.dev20231106+rocm5.7          pypi_0    pypi
bash: [conda]: command not found
```

On torch 2.1 + CUDA 11.8:
```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA DGX Display
GPU 4: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             128
On-line CPU(s) list:                0-127
Thread(s) per core:                 2
Core(s) per socket:                 64
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              49
Model name:                         AMD EPYC 7742 64-Core Processor
Stepping:                           0
Frequency boost:                    enabled
CPU MHz:                            3241.892
CPU max MHz:                        2250,0000
CPU min MHz:                        1500,0000
BogoMIPS:                           4491.76
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          2 MiB
L2 cache:                           32 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.4
[pip3] onnx==1.13.1
[pip3] onnxruntime==1.15.1
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.1.0+cu118
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.1.0
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
(fx) felix@hf-dgx-01:~/text-generation-inference$ [conda] triton                    2.1.0                    pypi_0    pypi
[conda]: command not found
```

cc @ezyang @gchanan @zou3519 @kadeng @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by malfet** [comment]
@fxmarty do you mind sharing a tracefile generated? I wonder if this is caused by https://github.com/pytorch/pytorch/issues/113756

**Comment by fxmarty** [comment]
[tb_logs.zip](https://github.com/pytorch/pytorch/files/13365979/tb_logs.zip)

Yes my bad, here it is!

**Comment by malfet** [comment]
@fxmarty what's your version of Chrome? As "it works on my machine"™ :)
<img width="850" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/927178fa-af8a-42f2-8610-736d95502e66">

**Comment by fxmarty** [comment]
I am using `119.0.6045.123`, & on Firefox (with tensorboard) I use `119.0.1`. Maybe that's too old, I'll try to upgrade.

**Comment by fxmarty** [comment]
Oh, it works on chromium actually. The issue is only on Firefox + tensorboard.

**Comment by hongxiayang** [comment]
Since the work-aground works , mark this as low priority to identify the root cause.

**Comment by hongxiayang** [comment]
This is what I saw on the backend when I click "Trace" on the frontend when running `tensorboard --logdir=./log`.
```
W1116 21:55:32.118967 140639922665216 security_validator.py:60] In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
```
@fxmarty Did you see this on your end too? Wondering whether this is related to my environment or it is the cause of the empty screen on Trace.

**Comment by fxmarty** [comment]
@hongxiayang Yes I am also seeing these logs - however I am seeing them as well for the json trace generated using an nvidia version of pytorch.

Can you reproduce the issue with tensorboard (using 2.15.1)?

**Comment by hongxiayang** [comment]
We will close this issue since the workaround works and the issue related to tensorboard is not ROCm related.
