### ISSUE TITLE
[Dynamo] [Python3.10] Missing support for strict=True kwargs in zip()

### ISSUE THREAD

**Issue by ezhang887** [pytorch/pytorch#113894]
### 🐛 Describe the bug

Python3.10 added a `strict=True` kwarg to `zip()`: https://peps.python.org/pep-0618/#specification.

Currently it seems like Dynamo is missing support for that, see example below.

### Error logs

```
2.1.0a0+git7bcf7da
[2023-11-16 13:01:18,525] [0/0] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_zip of BuiltinVariable(zip)> got an unexpected keyword argument 'strict' and no constant handler
Traceback (most recent call last):
  File "repro.py", line 21, in <module>
    out = net(torch.Tensor([1, 2, 3, 4]))
  File "/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1167, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 645, in call_function
    return super().call_function(tx, args, kwargs)
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 306, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "/conda/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(zip) [NNModuleVariable(), NNModuleVariable()] {'strict': ConstantVariable(bool)}

from user code:
   File "/repro.py", line 14, in forward
    for mod1, mod2 in zip(self.modules_1, self.modules_2, strict=True):

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

```
import torch
import torch.nn as nn

print(torch.__version__)

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.modules_1 = nn.ModuleList([nn.Identity()])
        self.modules_2 = nn.ModuleList([nn.Identity()])

    def forward(self, x):
        rv = []
        for mod1, mod2 in zip(self.modules_1, self.modules_2, strict=True):
            rv.append((mod1(x), mod2(x)))
        return rv

net = Net()
net = net.cuda()
net = torch.compile(net, backend="eager", fullgraph=True)
out = net(torch.Tensor([1, 2, 3, 4]))
print(out)
```

If I remove `strict=True` it works. If I remove the `net = torch.compile(net, ...)` line it also works.

### Versions

PyTorch Version == `2.1.0a0+git7bcf7da` (right off of the 2.1 release branch)

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by ezhang887** [comment]
From a quick scan through the code seems like the fix might just need to add a check for this kwarg here and pass it down to the `zip` call in here?

https://github.com/pytorch/pytorch/blob/bbd73c746e4d652b3aadaf3c5a0ea59b9b03cb4c/torch/_dynamo/variables/builtin.py#L911-L917

**Comment by ezyang** [comment]
Yeah, should be relatively simple
