### ISSUE TITLE
deep copy 'HigherOrderOperator' bug

### ISSUE THREAD

**Issue by liufengwei0103** [pytorch/pytorch#113938]
### 🐛 Describe the bug

'HigherOrderOperator'  op can't be deeply copied.

```
import torch
import copy

copy.deepcopy(torch._prims.rng_prims.run_and_save_rng_state)
```
err msg as belows:

Traceback (most recent call last):
  File "test_pickle_dispatch.py", line 6, in <module>
    copy.deepcopy(torch._prims.rng_prims.run_and_save_rng_state)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 269, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'torch._C.DispatchKeySet' object

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.2.0a0+gitd64bc8f
[pip3] torchvision==0.15.2
[pip3] triton==2.1.0

cc @zou3519 @ydwu4

**Comment by liufengwei0103** [comment]
@janeyx99  Could you help to review this pr? My code about custom compiler in dynamo stack needs this feature.

**Comment by janeyx99** [comment]
cc @zou3519 @Chillee who may know the right owners for this part of the codebase

**Comment by aorenste** [comment]
This issue was fixed in PyTorch 2.8 by #169704.

(Analysis done by Claude.)
