### ISSUE TITLE
Sympy reasoning with true division is broken

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#113905]
### 🐛 Describe the bug

Put this test in `test/test_dynamic_shapes.py`

```
    def test_sym_div_mul(self):
        shape_env = ShapeEnv()
        s0 = create_symint(shape_env, 10)
        r = (s0 ** 2) / 2 * 2
        self.assertTrue(bool(r == 100.0))
```

It fails

```
======================================================================
FAIL: test_sym_div_mul (__main__.TestPySymInt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/torch/testing/_internal/common_utils.py", line 2536, in wrapper
    method(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/test/test_dynamic_shapes.py", line 409, in test_sym_div_mul
    self.assertTrue(bool(r == 100.0))
  File "/data/users/ezyang/a/pytorch/torch/__init__.py", line 361, in __bool__
    return self.node.bool_()
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/sym_node.py", line 384, in bool_
    return self.guard_bool("", 0)
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/sym_node.py", line 340, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/recording.py", line 226, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3350, in evaluate_expr
    assert static_expr == hint, f"{static_expr} != {hint}"
AssertionError: False != True
```

The proximal cause of the problem is 

```
>>> x = sympy.Symbol('x', positive=True, integer=True)
>>> sympy.Eq(((x ** 2) / 2) * 2, 100.0)
False
```

Probably fixed by https://github.com/sympy/sympy/pull/25875

### Versions

main

**Comment by ezyang** [comment]
c.f. https://github.com/pytorch/pytorch/pull/113878

**Comment by ezyang** [comment]
The plan is to do nothing about this, and it will get fixed when we upgrade to latest sympy

**Comment by asmeurer** [comment]
Yes, this will also be fixed in the next version of SymPy. The problem is that in SymPy 1.12, we have

```py
>>> Float(1.0).is_integer
False
```

and Eq is smart enough to know that the lhs is an integer so it thinks it cannot be equal to the rhs and evaluates to False. If you need a workaround, you'd need to use a custom Eq class that doesn't do this.

**Comment by isuruf** [comment]
I feel like a solution similar to https://github.com/pytorch/pytorch/pull/113683 would work here. i.e. for methods in `always_float_magic_methods`, we should call `sym_float` on it.

**Comment by isuruf** [comment]
Yep. #113683 along with the diff
```
diff --git a/torch/fx/experimental/sym_node.py b/torch/fx/experimental/sym_node.py
index 1705a636e5a..26a260952b9 100644
--- a/torch/fx/experimental/sym_node.py
+++ b/torch/fx/experimental/sym_node.py
@@ -835,6 +835,8 @@ def _make_node_magic(method, func):
         # evaluation.
         if method in always_float_magic_methods:
             pytype = float
+            if self.pytype == int and other.pytype == int:
+                out = magic_methods["sym_float"](out)
         elif method in always_bool_magic_methods:
             pytype = bool
         elif self.pytype is float or other.pytype is float:
```

does fix this issue.

**Comment by ezyang** [comment]
Send us a patch for this one too?
