### ISSUE TITLE
`torch.compile()` makes loss `nan`

### ISSUE THREAD

**Issue by akihironitta** [pytorch/pytorch#114109]
### 🐛 Describe the bug

`torch.compile()` causes instability issue during training in my use case. Specifically, I observed that the loss goes `nan` with `torch.compile()` enabled.

To reproduce, I first tried below, but the minifier gave me `RuntimeError: Input graph did not fail the tester`:
```console
$ TORCHDYNAMO_REPRO_AFTER="aot" TORCHDYNAMO_REPRO_LEVEL=4 python my_script.py
...
torch._dynamo.debug_utils.AccuracyError: Bad accuracy detected
$ python torch_compile_debug/run_2023_11_20_08_23_04_362462-pid_45740/minifier/minifier_launcher.py
Loading inputs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 95/95 [00:02<00:00, 45.68it/s]

>>  Loading inputs: 100%|██████████| 53/53 [00:01<00:00, 26.81it/s]
>>  [2023-11-20 08:23:46,301] torch._dynamo.debug_utils: [ERROR] While minifying the program in accuracy minification mode, ran into a runtime exception which is likely an unrelated issue. Skipping this graph

Traceback (most recent call last):
  File "/home/akihiro/work/github.com/kumo-ai/some-repo/torch_compile_debug/run_2023_11_20_08_23_04_362462-pid_45740/minifier/minifier_launcher.py", line 540, in <module>
    run_repro(mod, load_args, accuracy=True, command='minify', save_dir='/home/akihiro/work/github.com/kumo-ai/some-repo/torch_compile_debug/run_2023_11_20_08_23_04_362462-pid_45740/minifier/checkpoints', tracing_mode='real', check_str=None)
  File "/home/akihiro/.conda/envs/kumo310/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 927, in run_repro
    COMMAND_FNS[options.command](options, mod, load_args)
  File "/home/akihiro/.conda/envs/kumo310/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 530, in repro_minify
    minifier(
  File "/home/akihiro/.conda/envs/kumo310/lib/python3.10/site-packages/torch/_functorch/fx_minifier.py", line 189, in minifier
    raise RuntimeError("Input graph did not fail the tester")
RuntimeError: Input graph did not fail the tester
```
and then, I tried below instead:
```console
$ TORCHDYNAMO_REPRO_AFTER="dynamo" TORCHDYNAMO_REPRO_LEVEL=4 python my_script.py
...
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
E                   AccuracyError: Bad accuracy detected.
$  python torch_compile_debug/run_2023_11_20_08_45_58_834796-pid_52789/minifier/minifier_launcher.py
...
Wrote minimal repro out to repro.py
```

### Error logs

```console
$ python repro.py
Loading inputs: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.04s/it]
[2023-11-20 08:54:20,386] torch._dynamo.debug_utils: [WARNING] Could not generate fp64 outputs
[2023-11-20 08:54:20,388] torch._dynamo.debug_utils: [WARNING] Could not generate fp64 outputs
[2023-11-20 08:54:24,498] torch._dynamo.utils: [ERROR] Accuracy failed: allclose not within tol=0.001
Traceback (most recent call last):
  File "/home/akihiro/work/github.com/kumo-ai/some-repo/repro.py", line 44, in <module>
    run_repro(mod, load_args, accuracy=True, command='run',
  File "/home/akihiro/.conda/envs/kumo310/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 566, in run_repro
    COMMAND_FNS[options.command](options, mod, load_args)
  File "/home/akihiro/.conda/envs/kumo310/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 428, in repro_run
    raise AccuracyError("Dynamo failed")
torch._dynamo.debug_utils.AccuracyError: Dynamo failed
```

### Minified repro

This is the minified `repro.py`:

```python
from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import torch._dynamo
from torch._dynamo.testing import rand_strided
from torch._dynamo.debug_utils import run_fwd_maybe_bwd
import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config
torch._dynamo.config.assume_static_by_default = False
from torch.nn import *

class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, view_22, getitem_51):
        expand_as_16 = view_22.expand_as(getitem_51);  view_22 = getitem_51 = None
        return (expand_as_16,)

mod = Repro()

def load_args(reader):
    buf0 = reader.storage('d4bfc3c81078c64c193b38e7b2189c50a5687e7a', 16, device=device(type='cuda', index=0), dtype_hint=torch.int64)
    reader.tensor(buf0, (1, 1), dtype=torch.int64, storage_offset=1, is_leaf=True)  # view_22
    buf1 = reader.storage('549a91c2aa84c73c8e9be35307048f20aeb4fd99', 128, device=device(type='cuda', index=0))
    reader.tensor(buf1, (1, 32), requires_grad=True)  # getitem_51
load_args._version = 0

if __name__ == '__main__':
    from torch._dynamo.repro.after_dynamo import run_repro
    run_repro(mod, load_args, accuracy=True, command='run',
        save_dir='/home/akihiro/work/github.com/kumo-ai/some-repo/checkpoints', autocast=False, backend='inductor')
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.996
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-boto3-s3==1.26.62
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.1.0
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.1.0+cu118
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.2+pt21cu118
[pip3] torchdata==0.7.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.1.0                    pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-scatter             2.1.2+pt21cu118          pypi_0    pypi
[conda] torchdata                 0.7.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtext                 0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @wconstab

**Comment by ezyang** [comment]
First do an ablation on backend. Try eager/aot_eager/aot_eager_decomp_partition to localize the problem to a particular component. Once you've found this, a full debug `TORCH_LOGS=+dynamo,+aot,+inductor` may help us do some initial investigation. You can also bisect the problem by intentionally disabling segments of your model from torch.compile. I also recommend trying to have a test that can identify the numeric divergence in a single iteration.

**Comment by akihironitta** [comment]
Thank you for your suggestions. Here're some findings:

- Tried `eager`, `aot_eager`, `aot_eager_decomp_partition` and `inductor` and I see this issue only with `inductor` backend.
- By compiling only certain segments of my model by hand, I've found out that compiling `torch_geometric.utils.scatter` causes this issue. In particular, compiling [this code block](https://github.com/pyg-team/pytorch_geometric/blob/ed490ecedeb63974def564395d3f5a8f7675305d/torch_geometric/utils/scatter.py#L94-L95) in the `scatter` causes this issue:

  ```python
                return src.new_zeros(size).scatter_reduce_(
                    dim, index, src, reduce=f'a{reduce}', include_self=False)
  ```
  I confirmed it by wrapping this code with `torch._dynamo.optimize()` in https://github.com/pyg-team/pytorch_geometric/pull/8443/.

<details><summary>logs with TORCH_LOGS=+dynamo,+aot,+inductor (~1500 lines)</summary>

https://gist.github.com/akihironitta/6aeeda8db708d06cc8e29544ab14ea97

</details>

<details><summary>python collect_env.py</summary>

```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.998
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-boto3-s3==1.26.62
[pip3] numpy==1.23.5
[pip3] pytorch_frame==0.1.0
[pip3] pytorch-lightning==2.1.0
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.1.0+cu118
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.2+pt21cu118
[pip3] torchdata==0.7.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-frame             0.1.0                    pypi_0    pypi
[conda] pytorch-lightning         2.1.0                    pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-scatter             2.1.2+pt21cu118          pypi_0    pypi
[conda] torchdata                 0.7.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtext                 0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

</details>

**Comment by akihironitta** [comment]
In addition, I reran the minifier with only the above code snippet compiled as in https://github.com/pyg-team/pytorch_geometric/pull/8443:

```console
$ TORCHDYNAMO_REPRO_LEVEL=4 TORCHDYNAMO_REPRO_AFTER=aot python my_script.py
```

and I got this `repro.py`:

```python
import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
import torch._inductor.inductor_prims
import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config
torch._inductor.config.generate_intermediate_hooks = True
isolate_fails_code_str = None

# torch version: 2.1.0+cu118
# torch cuda version: 11.8
# torch git version: 7bcf7da3a268b435777fe87c7794c382f444e86d

# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2021 NVIDIA Corporation 
# Built on Thu_Nov_18_09:45:30_PST_2021 
# Cuda compilation tools, release 11.5, V11.5.119 
# Build cuda_11.5.r11.5/compiler.30672275_0 

# GPU Hardware Info: 
# Tesla T4 : 1 

from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, arg0_1, arg3_1, convert_element_type, convert_element_type_1):
        scatter_add = torch.ops.aten.scatter_add.default(convert_element_type, 0, arg0_1, convert_element_type_1);  convert_element_type = arg0_1 = convert_element_type_1 = None
        div = torch.ops.aten.div.Tensor(arg3_1, scatter_add);  arg3_1 = scatter_add = None
        return (div,)
        
def load_args(reader):
    buf0 = reader.storage('6de79f4d451761873a72c46a249b835d43d5f5e8', 8, device=device(type='cuda', index=0), dtype_hint=torch.int64)
    reader.tensor(buf0, (1, 32), (1, 0), dtype=torch.int64, is_leaf=True)  # arg0_1
    buf1 = reader.storage('9489f89ab0bd1a88139da1c856558f8fb29dadea', 384, device=device(type='cuda', index=0))
    reader.tensor(buf1, (1, 32), (96, 1), storage_offset=64, is_leaf=True)  # arg3_1
    buf2 = reader.storage('da7a883c0f27c7ea8bc5974535fd0a6690fcf06c', 128, device=device(type='cuda', index=0))
    reader.tensor(buf2, (1, 32), is_leaf=True)  # convert_element_type
    buf3 = reader.storage('26fa883ccca7c7eae74597450dfd0a66187cf06c', 128, device=device(type='cuda', index=0))
    reader.tensor(buf3, (1, 32), is_leaf=True)  # convert_element_type_1
load_args._version = 0
mod = Repro()
if __name__ == '__main__':
    from torch._dynamo.repro.after_aot import run_repro
    run_repro(mod, load_args, accuracy=True, command='run', save_dir='/home/akihiro/work/github.com/kumo-ai/kumo/torch_compile_debug/run_2023_11_26_23_49_34_096419-pid_692919/minifier/checkpoints', tracing_mode='real', check_str=None)
```

**Comment by akihironitta** [comment]
> I also recommend trying to have a test that can identify the numeric divergence in a single iteration.

I'm aware that the divergence can vary depending on operations (and data, too?), but do you have any general insight into how large diff should be treated as a "bug"? For example in https://github.com/pyg-team/pytorch_geometric/pull/8433/, I'm adding a test case where I had to set `atol=1e-6`.

**Comment by ezyang** [comment]
Sorry about the delay, I was on recharge for Dec. Bumping this to get some more eyeballs

**Comment by akihironitta** [comment]
Thank you, @ezyang. If I can provide any further information, please let me know. I'm still very interested in investigating the cause of this issue for our GNN use case so that we can levarage the performance gains offered by the recent improvements with `torch.compile`.

**Comment by markrmiller** [comment]
Seeing the same thing, though just ran into it so I have not had a chance to track down what part is causing it. Same problem high level though - model trains fine without compile, with compile, first loss print out is nan.

**Comment by ezyang** [comment]
@markrmiller We're always looking for reproductions on this sort of thing, so if your code is all OSS, an end to end repro, even if it is very large, is quite helpful for us.

**Comment by markrmiller** [comment]
It looks like it was just a misunderstanding on my part. I had read that cudagraphs was not supported on multiple GPU's (I'm using two), but I thought that, and the logging messages related that you get, just meant you would not get cudagraphs when you compiled and trained on more than one GPU, no real action to take. Mostly because there is no big scary warning or hard error, I figured that's just how it works. In the past, I had not seen max-autotune-no-cudagraphs. Spotted it though and gave it a try and no more nan issue.

**Comment by ezyang** [comment]
We are not supposed to ever silently give you incorrect results. So your bug report is still appreciated!

**Comment by c0nn3r** [comment]
I'm also seeing this issue when using scatters with torch inductor.

**Comment by Chillee** [comment]
@c0nn3r Do you have some kind of repro?

**Comment by drhead** [comment]
I seem to be having a similar and possibly related issue.

Unfortunately, the minifier script produced does not seem to be helpful as it generates with syntax errors and when corrected the accuracy issue is not reproducible.  So here's my entire fork of LPIPS, thankfully it isn't *too* large:

https://github.com/drhead/PerceptualSimilarity/tree/0dc17b9cbcb81646057c08f30e82b99e60cf3efe

After installing requirements and downloading the datasets, you can cause the issue to happen by running:

`source scripts/train_test_metric_tune.sh srgb convnext_tiny`

It seems that the first and second step returns a loss that is in range, but the third step returns nan.  Accuracy issues are detectable from the very first iteration.  Commenting out the torch.compile partial decorator at lpips/trainer.py:132 and letting the code run normally in eager mode gives normal, correct results, as does using the backends `eager`, `aot_eager`, and `aot_eager_decomp_partition`, only `inductor` causes the issue which is another common pattern.

Interestingly, I only seem to have this issue on convnext, so it's almost certainly related to an operation that exists in convnext but not in other archs I've tested.  You can try vgg16, for example, and it will compile and run fine.

`source scripts/train_test_metric_tune.sh srgb vgg16`

**Comment by Chillee** [comment]
Thanks @drhead, I will take a look at this.

**Comment by Chillee** [comment]
Unfortunately, I'm unable to repro it on my machine. Out of curiosity, does it also nan if you run without max-autotune?

<img width="1489" alt="image" src="https://github.com/pytorch/pytorch/assets/6355099/0543b1ae-df94-4dfc-8c6b-386e167491c9">


cc: @drhead

**Comment by drhead** [comment]
I had also tried max-autotune off, same results.  If it works fine on your fresh environment, then it may be down to a mismatch in CUDA versions, I will try checking that and see what I can come up with.

**Comment by drhead** [comment]
> @drhead Another question - does it repro without `torch.set_deterministic_algorithms(True)`?

It actually doesn't repro without that.  Interesting.

I did do a fresh setup of the conda environment and verified that it is not loading any different CUDA libraries -- it was loading nvrtc 12.3, corrected that, but that didn't solve it, so CUDA versions are definitely not an issue.

Finally, wrapping the network in torch.compile instead of the whole loss function also does not cause the issue to happen.  That leaves out the BCELoss function entirely of course, but other network archs do not cause the issue so I don't think that's the culprit, or if it is it is related to a combination of that with other things.

**Comment by shunting314** [comment]
From triage review: we need a minimal repro

**Comment by akihironitta** [comment]
We tried the same script with 2.3.0, and we no longer see this issue. Feel free to close this issue as there's no repro provided yet.
