### ISSUE TITLE
boolean masking creates a graph break due to aten.nonzero

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#114220]
### 🐛 Describe the bug

```python
@torch.compile(fullgraph=True)
def f(t):
    return t[t > 0.5]


f(torch.rand(3, 16, 16))
```

```
torch._dynamo.exc.Unsupported: dynamic shape operator: aten.nonzero.default
```

<details><summary>Full traceback</summary>
<p>

```
Traceback (most recent call last):
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1570, in run_node
    return node.target(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1385, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1642, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 670, in index_tensor
    out = meta_index_Tensor(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_meta_registrations.py", line 2819, in meta_index_Tensor
    nonzero = index.nonzero()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1385, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1642, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 560, in nonzero
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1485, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1026, in wrap_fake_exception
    return fn()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1486, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1591, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1570, in run_node
    return node.target(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1385, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1642, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 670, in index_tensor
    out = meta_index_Tensor(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_meta_registrations.py", line 2819, in meta_index_Tensor
    nonzero = index.nonzero()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1385, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1642, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 560, in nonzero
    raise DynamicOutputShapeException(func)
RuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., size=(3, 16, 16)), FakeTensor(..., size=(3, 16, 16), dtype=torch.bool)), **{}):
aten.nonzero.default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philip/git/pytorch/vision/main_dynamo.py", line 34, in <module>
    f(torch.rand(3, 16, 16))
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 482, in _fn
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 646, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 249, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 579, in call_function
    return wrap_fx_proxy(tx, proxy)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1280, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1365, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1502, in get_fake_value
    unimplemented(f"dynamic shape operator: {cause.func}")
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: dynamic shape operator: aten.nonzero.default

from user code:
   File "/home/philip/git/pytorch/vision/main_dynamo.py", line 31, in f
    return t[t > 0.5]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

</p>
</details> 

Although the error indicates this an issue with dynamic shapes, I'm getting the same error when setting `torch.compile(..., dynamic=False)`.

### Versions

2.2.0.dev20231120+cpu

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
You need to set `capture_dynamic_output_shape_ops = True` to capture this. We should probably suggest this in the error message lol
