### ISSUE TITLE
math.radians with integer input creates a graph break for dynamic shapes

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#114218]
### 🐛 Describe the bug

```python
import itertools
import math

import torch


input = 90
expected = math.pi / 2


for type, dynamic in itertools.product([float, int], [False, True]):
    torch._dynamo.reset()
    cfn = torch.compile(fullgraph=True, dynamic=dynamic)(math.radians)

    try:
        torch.testing.assert_close(cfn(type(input)), expected)
        result = "PASS"
    except:
        result = "FAIL"
    print(f"{result} {type=}, {dynamic=}")
```

```
PASS type=<class 'float'>, dynamic=False
PASS type=<class 'float'>, dynamic=True
PASS type=<class 'int'>, dynamic=False
FAIL type=<class 'int'>, dynamic=True
```

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "/home/philip/git/pytorch/vision/main_dynamo.py", line 15, in <module>
    torch.testing.assert_close(cfn(type(input)), expected)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 482, in _fn
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 646, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1252, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/lazy.py", line 90, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 599, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1280, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1539, in wrap_fx_proxy_cls
    unimplemented(
  File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor float call_function <built-in function radians>

from user code:
   File "/home/philip/.conda/envs/pytorch-vision-dev/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

</p>
</details> 

### Versions

2.2.0.dev20231120+cpu

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
Should be relatively easy to fix

**Comment by isuruf** [comment]
`math.sqrt` works because of the code at https://github.com/pytorch/pytorch/blob/9d68cfee0dec46be44732667466303a36155f144/torch/_dynamo/variables/torch.py#L567-L570
It seems weird that `math.sqrt` is specialized like that. Should there be something like that for `math.radians, math.tan, math.sin` etc?

**Comment by ezyang** [comment]
It's specialized like that because we have a sympy expression for it. But to be honest, it is kind of suspicious. https://docs.google.com/document/d/1INSCdYu1PxXcr43HrD82OudeEuS-qxQe1yZmLg2wy6A/edit#heading=h.aytveihghlgn and https://github.com/pytorch/pytorch/issues/107277

**Comment by lamroger** [comment]
Interested in figuring out a fix - spent some time looking at the stack trace but didn't get very far. Down to go over someone's PR too if you're already on it @isuruf

**Comment by ezyang** [comment]
Sorry, to be clear, the easy fix is to force a guard when you want to compute radians. If you want to keep the input integer symbolic, that will be more difficult (needs https://github.com/pytorch/pytorch/issues/107277)

**Comment by pmeier** [comment]
Not sure if I'm ignorant of the terminology here so this might be pedantic. We want the compiled version `math.radians` to behave just like the eager counterpart, i.e. 

```python
assert isinstance(math.radians(90), float)
```

meaning a sym int can turn into a sym float if that is possible. But that seems to be the case because with static shapes it seems to work without graph break.

**Comment by vfdev-5** [comment]
> the easy fix is to force a guard when you want to compute radians.

@ezyang we would like to enter into this condition: https://github.com/pytorch/pytorch/blob/9d68cfee0dec46be44732667466303a36155f144/torch/_dynamo/variables/torch.py#L293-L300 as `can_constant_fold_through` checks `getattr(self.value, "__module__", None) == "math"`
and do something like this:
```python
        elif self.can_constant_fold_through() and (
            constant_args
            or unspec_python_args
            or any(isinstance(x, SymNodeVariable) for x in args)
        ):
            # constant fold
            return ConstantVariable.create(
                self.as_python_constant()(
                    *[
                        x.as_python_constant()
                        if not isinstance(x, SymNodeVariable)
                        else x.evaluate_expr()
                        for x in args
                    ],
                    **{
                        k: v.as_python_constant()
                        if not isinstance(v, SymNodeVariable)
                        else v.evaluate_expr()
                        for k, v in kwargs.items()
                    },
                ),
            )
```

**Comment by pmeier** [comment]
@lamroger there is already #114507 that potentially fixes this issue. Please have a look there.
