### ISSUE TITLE
torch.compile support for SeamlessExpressivity/SeamlessM4T in fairseq2

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#114373]
### 🐛 Describe the bug

Internal notes:
* https://fb.workplace.com/notes/389433230075029/?comment_id=362284632838743&reply_comment_id=332571542802227&notif_id=1699490653585208&notif_t=comment_mention&ref=notif
* https://docs.google.com/document/d/1PVy4KibfljirQDoijOwyHCV97B67r_iElWqFh7h1Acc/edit#heading=h.r8e5eoeu8v9e

Setup notes:

* It does NOT work in conda, you must do a venv
* Despite the instructions, you can build it against CUDA 12
* fmt is incompatible with PyTorch main, see https://github.com/facebookresearch/fairseq2/issues/170 for WAR

With the stock repo `python scripts/m4t/benchmark/benchmark.py  --apply_compile --dynamic` errors. https://github.com/pytorch/pytorch/pull/114362 solves the immediate problem but we end up with no generations after we slowly hit cache limit everywhere:

```
[2023-11-22 08:45:41,648] [23/47] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 447
[[]]
Traceback (most recent call last):
  File "/data/users/ezyang/seamless_communication/scripts/m4t/benchmark/benchmark.py", line 457, in <module>
    main(args)
  File "/data/users/ezyang/seamless_communication/scripts/m4t/benchmark/benchmark.py", line 362, in main
    res = run_inference(example)
  File "/data/users/ezyang/pytorch-venv/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/ezyang/seamless_communication/scripts/m4t/benchmark/benchmark.py", line 281, in apply_model
    return translator.predict(
  File "/data/users/ezyang/pytorch-venv/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/ezyang/seamless_communication/seamless_communication/models/inference/translator.py", line 256, in predict
    text_output, unit_output = self.get_prediction(
  File "/data/users/ezyang/seamless_communication/seamless_communication/models/inference/translator.py", line 162, in get_prediction
    return generator(
  File "/data/users/ezyang/pytorch-venv/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/ezyang/seamless_communication/seamless_communication/models/unity/generator.py", line 178, in __call__
    text_output = self.s2t_generator.generate_ex(
  File "/data/users/ezyang/fairseq2/src/fairseq2/generation/text.py", line 152, in generate_ex
    return self._do_generate(source_seqs, source_padding_mask)
  File "/data/users/ezyang/pytorch-venv/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/ezyang/fairseq2/src/fairseq2/generation/text.py", line 83, in _do_generate
    sentences = [self.token_decoder(b[0].seq) for b in gen_output.results]
  File "/data/users/ezyang/fairseq2/src/fairseq2/generation/text.py", line 83, in <listcomp>
    sentences = [self.token_decoder(b[0].seq) for b in gen_output.results]
IndexError: list index out of range
```

So there's an accuracy problem, and there's also a recompilation problem.

### Versions

main

**Comment by StrongerXi** [comment]
The `index out of range` error still repros on PT 2.5.1, with Python 3.12. I'm investigating.

**Comment by StrongerXi** [comment]
Okay, I've narrowed down the `index out of range` issue to this -- under `--apply_compile --dynamic`, compilation of `speech_encoder`, which resulted in a single graph but produced a result of all `nan`s (eager backend and inductor backends without `--dynamic` produced similar normal results). TLparses here:
- `--apply_compile --dynamic` with inductor backend: https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmp5w7GBa/dedicated_log_torch_trace_u6oy9zl7.log/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100
- `--apply_compile --dynamic` with inductor backend: https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpMfu5H8/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100
- `--apply_compile` with inductor backend: https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpmTKlqQ/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100

The Dynamo captured graphs all look the same, so this might be a dynamic shape + inductor issue? In that case can we remove the `Dynamo` tag? @ezyang

**Comment by ezyang** [comment]
How did you conclude the graphs are the same? They are definitely not the same lol

**Comment by StrongerXi** [comment]
> How did you conclude the graphs are the same? They are definitely not the same lol

I wasn't precise. `--apply_compile --dynamic` have the same dynamo graph for [inductor](https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmp5w7GBa/dedicated_log_torch_trace_u6oy9zl7.log/0_0_0/dynamo_output_graph_0.txt?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100) v.s. [eager](https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpMfu5H8/0_0_0/dynamo_output_graph_0.txt?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100), yet inductor produced `nan`s, so I concluded it's an inductor issue.

For `--apply_compile` v.s. `--apply_compile --dynamic` on inductor backend, I could be wrong, as I just eye-balled the beginning and end while ignoring symint v.s. int differences.

**Comment by StrongerXi** [comment]
Unassigning  myself as this no longer seems Dynamo related -- it's inductor for accuracy issue, and dynamic shapes for recompilation issue.
