### ISSUE TITLE
Simple use of torch.distributions Categorical causes malformed graph when optimizing logits

### ISSUE THREAD

**Issue by kylesayrs** [pytorch/pytorch#114417]
### 🐛 Describe the bug

It should be possible to optimize the parameters of torch.distributions Categorical, however trying to do so throws a Runtime Error.

```python3
import torch
from torch.distributions import Categorical


if __name__ == "__main__":
    # create data
    data = torch.tensor(1, requires_grad=False)

    # set up model
    logits = torch.nn.Parameter(torch.zeros(2, ), requires_grad=True)
    categorical = Categorical(logits=logits)

    # optimize
    optimizer = torch.optim.Adam([logits], lr=10)

    for iteration_i in range(2):
        print(f"iteration {iteration_i}")

        # optimize
        optimizer.zero_grad()
        loss = -1 * categorical.log_prob(data)
        loss.backward()  # throws error on second optimization
        optimizer.step()

        # debugging prints
        print(logits)
        print(categorical.logits)
        print(loss.item())
```

```
iteration 0
Parameter containing:
tensor([-10.0000,  10.0000], requires_grad=True)
tensor([-0.6931, -0.6931], grad_fn=<SubBackward0>)
0.6931471824645996
iteration 1
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    loss.backward()  # throws error on second optimization
  File "/opt/homebrew/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/homebrew/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

The issue seems to arise on [categorical.py:line 62](https://pytorch.org/docs/stable/_modules/torch/distributions/categorical.html#Categorical) due to how the class attempts to normalize the logits before using them
```python3
self.logits = logits - logits.logsumexp(dim=-1, keepdim=True)
```

This can be worked around by accessing and modifying the `categorical.logits` member directly
```python3
categorical.logits.requires_grad = True
optimizer = torch.optim.Adam([categorical.logits], lr=10)
```

However, I think pytorch should support passing a parameter directly, since this matches the usage of other distribution classes
```python3
class GaussianMixtureModel(torch.nn.Module):
    def __init__(self, num_mixtures: int, num_dims: int):
        super().__init__()
        self.logits = torch.nn.Parameter(torch.rand(num_mixtures, ), requires_grad=True)
        self.mus = torch.nn.Parameter(torch.rand(num_mixtures, num_dims))
        self.sigmas_diag = torch.nn.Parameter(torch.rand(num_mixtures, num_dims))

        self.mixture = Categorical(logits=self.logits)  # wouldn't it be nice
        self.components = Independent(Normal(self.mus, self.sigmas_diag), 1)
        self.mixture_model = MixtureSameFamily(self.mixture, self.components)
```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.25.2
Libc version: N/A

Python version: 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] mypy==1.5.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] onnx==1.14.0
[pip3] torch==1.13.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchvision==0.14.1
[conda] Could not collect
```

**Comment by kylesayrs** [comment]
It's become apparent to me that the classes in `torch.distributions` are not implemented with mutation in mind. Perhaps there should be more documentation noting this fact.
