### ISSUE TITLE
ImportError: cannot import name 'caffe2_pb2' (Ubuntu 18.04)

### ISSUE THREAD

**Issue by nicksterlingtek** [pytorch/pytorch#11445]
Hello, I have been trying for a couple of weeks to get pytorch and caffe2 to build and install on my system. I am running Ubuntu 18.04 with anaconda environment setup with python 3.5, CUDA 9.2, and cuDNN 7. For some reason, I keep running into the same python error (cannot import name 'caffe2_pb2'). I have gone through the Caffe2 FAQ docs for import errors, but still no luck. I would be so appreciative if someone might be able to help me figure this out :) 

$ git clone --recursive https://github.com/pytorch/pytorch
$ conda create -n some_env python=3
$ conda activate some_env
$ export CMAKE_PREFIX_PATH=/home/nick/anaconda3/envs/some_env/
$ conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
$ conda install -c mingfeima mkldnn
$ conda install -c pytorch magma-cuda92
$ cd pytorch/
$ git submodule update --init --recursive
$ python setup.py install

...

Installing convert-caffe2-to-onnx script to /home/nick/anaconda3/envs/some_env/bin
Installing convert-onnx-to-caffe2 script to /home/nick/anaconda3/envs/some_env/bin

...

(some_env) nick@nick-HP-ENVY-Notebook:~/pytorch$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
...
>>> from caffe2.python import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nick/pytorch/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: cannot import name 'caffe2_pb2'

**Comment by nicksterlingtek** [comment]
Thank you for your help, @ezyang. In this particular instance, I forgot to change directories, but the error is present even when I am not in the pytorch directory. I ran cd ~ but same message about caffe2_pb2. Thanks again :)

**Comment by lburzawa** [comment]
I have the same problem.

**Comment by nicksterlingtek** [comment]
Do you have any other suggestions @ezyang? I really appreciate your help!

**Comment by forestriveral** [comment]
@ezyang When I got this error (I didn't start python from inside the pytorch directory): 

`Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.`
`>>> from caffe2.python import core`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forestriveral/anaconda3/envs/mrcnn/lib/python2.7/site-packages/caffe2/python/__init__.py", line 2, in <module>   from caffe2.proto import caffe2_pb2
ImportError: cannot import name caffe2_pb2`

In `/home/forestriveral/anaconda3/envs/mrcnn/`, I run `find -name caffe2_pb2*` and it says nothing. Then I find that there was empty in `/home/forestriveral/anaconda3/envs/mrcnn/lib/python2.7/site-packages/caffe2/proto/`. But I run this command inside the pytorch directory, it says:

`forestriveral@HanazawaKana:~/DeepLearning/object-detection/pytorch$ find -name caffe2_pb2* `
`./build/caffe2/proto/caffe2_pb2.py `
`./torch/lib/tmp_install/lib/python2.7/site-packages/caffe2/proto/caffe2_pb2.py`
`./torch/lib/python2.7/site-packages/caffe2/proto/caffe2_pb2.py`

Does this mean that I need to rebuild caffe2 ? Or any other solutions?

**Comment by nicksterlingtek** [comment]
Thank you so much, @ezyang, for your prompt response. Running `find /home/nick/anaconda3/envs/some_env/ -name caffe2_pb2*` returns no files. 

Running `find /home/nick -name caffe2_pb2*` returns the following...

```
/home/nick/pytorch/torch/lib/tmp_install/lib/python3.5/site-packages/caffe2/proto/caffe2_pb2.py
/home/nick/pytorch/torch/lib/python3.5/site-packages/caffe2/proto/caffe2_pb2.py
/home/nick/pytorch/build/caffe2/proto/caffe2_pb2.py
```
It seems like maybe caffe2_pb2 is within the tmp_install directory, but never seems to make it into the anaconda environment. When I look at the "SUMMARY" section running `FULL_CAFFE2=1 python setup.py install`, I notice that CMAKE_PREFIX_PATH is different than what I had intended to set on the command line, even though I run `export CMAKE_PREFIX_PATH=/home/nick/anaconda3/envs/some_env/`.

```
-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.12.2
--   CMake command         : /home/nick/anaconda3/envs/some_env/bin/cmake
--   Git version           : v0.1.11-10342-g87b2f05a9
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 7.3.0
--   BLAS                  : MKL
--   CXX flags             : -msse3 -msse4.1 -msse4.2   --std=c++11  -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-stringop-overflow
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx_torch;MAGMA_V2;USE_C11_ATOMICS=1;TH_BLAS_MKL;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /home/nick/anaconda3/envs/some_env/lib/python3.5/site-packages
--   CMAKE_INSTALL_PREFIX  : /home/nick/pytorch/torch/lib/tmp_install
-- 
--   BUILD_ATEN_MOBILE     : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 3.5.6
--     Python executable   : /home/nick/anaconda3/envs/some_env/bin/python
--     Pythonlibs version  : 3.5.6
--     Python library      : /home/nick/anaconda3/envs/some_env/lib/python3.5
--     Python includes     : /home/nick/anaconda3/envs/some_env/include/python3.5m
--     Python site-packages: lib/python3.5/site-packages
--   BUILD_SHARED_LIBS     : ON

```

**Comment by soumith** [comment]
@nicksterlingtek a fix for this issue was landed on master today. Can you pull and rebuild?

**Comment by soumith** [comment]
@nicksterlingtek more specifically, this is the fix https://github.com/pytorch/pytorch/pull/11517

**Comment by nicksterlingtek** [comment]
Thank you @soumith. I pulled the latest version and followed the commands above, but I received this error...

[ 83%] Linking CXX shared module python/caffe2_pybind11_state_gpu.cpython-35m-x86_64-linux-gnu.so
[ 83%] Built target caffe2_pybind11_state_gpu
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 libshm gloo c10d THD'

**Comment by nicksterlingtek** [comment]
@ezyang, since the error that we are experiencing seems to be a separate issue (`make: *** [all] Error 2... Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 libshm gloo c10d THD'`), should I open a new issue or will it be best to continue along this issue thread? Thank you again.
