### ISSUE TITLE
[inductor][cpu]detectron2_fcos_r_50_fpn accuracy and performance failure

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114466]
### 🐛 Describe the bug

detectron2_fcos_r_50_fpn fails in 2023-11-15
```
`loading model: 0it [00:05, ?it/s]cpu  eval  detectron2_fcos_r_50_fpn           

[2023-11-16 00:57:00,234] [3/0_1] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: stack
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2580, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 408, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/torchbench.py", line 508, in forward_pass
    return mod(*inputs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/detectron2/modeling/meta_arch/dense_detector.py", line 95, in forward
    images = self.preprocess_image(batched_inputs)
  File "/opt/conda/lib/python3.8/site-packages/detectron2/modeling/meta_arch/dense_detector.py", line 96, in resume_in_forward
    features = self.backbone(images.tensor)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/detectron2/modeling/backbone/fpn.py", line 139, in forward
    bottom_up_features = self.bottom_up(x)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 569, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 671, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 377, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 595, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 245, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 512, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 150, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 477, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2101, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 815, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 778, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2216, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 905, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1024, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 245, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1096, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1077, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/__init__.py", line 1616, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1235, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 4938, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 245, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 4478, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2797, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2983, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2120, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 981, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 303, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 393, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 604, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 245, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 446, in run
    return super().run(*args)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 750, in run_node
    result = super().run_node(n)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 619, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/workspace/pytorch/torch/_inductor/graph.py", line 616, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 288, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 1268, in convolution_unary
    ir.ConvolutionUnary.create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4968, in create
    (inputs, constant_args, kernel_layout, _) = _prepare_convolution_fusion_create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4788, in _prepare_convolution_fusion_create
    assert 0 < len(padding) <= dims
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: 
  target: mkldnn._convolution_pointwise.default
  args[0]: TensorBox(StorageBox(
    ConvolutionBinaryInplace(
      kernel='torch.ops.mkldnn._convolution_pointwise_.binary',
      name=buf4,
      layout=<torch._inductor.ir.NoneLayout object at 0x7fbbc5cd5b80>,
      inputs=[ComputedBuffer(name='buf3', layout=FixedLayout('cpu', torch.float32, size=[1, 256, 4*s2, 4*s3], stride=[4096*s2*s3, 1, 1024*s3, 256]), data=Pointwise(
        'cpu',
        torch.float32,
        def inner_fn(index):
            _, i1, i2, i3 = index
            tmp0 = ops.index_expr(i2, dtype=torch.int64)
            tmp1 = ops.to_dtype(tmp0, torch.float64, src_dtype=torch.int64)
            tmp2 = ops.constant(1, torch.float64)
            tmp3 = tmp1 * tmp2
            tmp4 = ops.constant(0, torch.float64)
            tmp5 = tmp3 + tmp4
            tmp6 = ops.to_dtype(tmp5, torch.float32, src_dtype=torch.float64)
            tmp7 = ops.index_expr(1/2, torch.float32)
            tmp8 = tmp6 * tmp7
            tmp9 = ops.to_dtype(tmp8, torch.int64, src_dtype=torch.float32)
            tmp10 = ops.index_expr(i3, dtype=torch.int64)
            tmp11 = ops.to_dtype(tmp10, torch.float64, src_dtype=torch.int64)
            tmp12 = ops.constant(1, torch.float64)
            tmp13 = tmp11 * tmp12
            tmp14 = ops.constant(0, torch.float64)
            tmp15 = tmp13 + tmp14
            tmp16 = ops.to_dtype(tmp15, torch.float32, src_dtype=torch.float64)
            tmp17 = ops.index_expr(1/2, torch.float32)
            tmp18 = tmp16 * tmp17
            tmp19 = ops.to_dtype(tmp18, torch.int64, src_dtype=torch.float32)
            tmp20 = ops.load(buf2, i1 + 256 * (tmp19) + 512 * (tmp9) * s3)
            return tmp20
        ,
        ranges=[1, 256, 4*s2, 4*s3],
        origin_node=clone_1,
        origins={_unsafe_index_1, clone_1}
      )), InputBuffer(name='arg16_1', layout=FixedLayout('cpu', torch.float32, size=[1, 512, 4*s2, 4*s3], stride=[8192*s2*s3, 1, 2048*s3, 512])), ConstantBuffer(name='_frozen_param8', layout=FixedLayout('cpu', torch.float32, size=[256, 512, 1, 1], stride=[512, 1, 1, 1])), ConstantBuffer(name='_frozen_param1', layout=FixedLayout('cpu', torch.float32, size=[256], stride=[1]))],
      constant_args=[[0, 0], [1, 1], [1, 1], 1, 'add', 1.0, None, [], None],
      kwargs={},
      output_view=None,
      ordered_kwargs_for_cpp_kernel=(),
      origin_node=fn,
      origins={_unsafe_index_1, clone_1, fn}
    )
  ))
  args[1]: TensorBox(StorageBox(
    ConstantBuffer(name='_frozen_param18', layout=FixedLayout('cpu', torch.float32, size=[256, 256, 3, 3], stride=[2304, 1, 768, 256]))
  ))
  args[2]: TensorBox(StorageBox(
    ConstantBuffer(name='_frozen_param1', layout=FixedLayout('cpu', torch.float32, size=[256], stride=[1]))
  ))
  args[3]: [1, 1]
  args[4]: [1, 1]
  args[5]: [1, 1]
  args[6]: 1
  args[7]: none
  args[8]: []
  args[9]: 

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
`
```

### Versions

SW information:

<body link="#0563C1" vlink="#954F72" lang=EN-US style='tab-interval:.5in;
word-wrap:break-word'>

SW | Nightly   commit | Main   commit
-- | -- | --
Pytorch | a5a4048 | 6f44090
Torchbench | / | 7617d3f5
torchaudio | 475b6ae | ede4309
torchtext | 142d029 | 45e4b8c
torchvision | 8636bf3 | 4ac707a
torchdata | eb9bf61 | d76d92c
dynamo_benchmarks | e6efc29 | /

</body>

</html>

Repro:

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh multiple/single inference accuracy/performance torchbench detectron2_fcos_r_50_fpn float32 first static/dynamic default

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/6ae4e3a8d249a96d9a8bbfba389d0509783e11e1

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment]
cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by zxd1997066** [comment]
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment]
Hi @zou3519  we found commit https://github.com/pytorch/pytorch/commit/6ae4e3a8d249a96d9a8bbfba389d0509783e11e1 cause the performance failure issue. Could you please help to take a look?

**Comment by leslie-fang-intel** [comment]
Hi @zou3519, could you kindly help to take a look?

**Comment by leslie-fang-intel** [comment]
`detectron2_fcos_r_50_fpn` passes based on latest test report https://github.com/pytorch/pytorch/issues/93531#issuecomment-2058060401
