### ISSUE TITLE
Compiling variant of UNet fails

### ISSUE THREAD

**Issue by usamec** [pytorch/pytorch#114751]
### 🐛 Describe the bug

Following code crashes:
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import typing as t

class UNet(nn.Module):
    def __init__(self, out_size: int = 32):
        super().__init__()

        self.c2 = nn.Conv2d(out_size, 4 * out_size, 4, stride=4)
        self.u2 = nn.ConvTranspose2d(4 * out_size, out_size, 4, stride=4)

        self.merge = nn.Conv2d(2 * out_size, out_size, 1)

    def forward(self, X):
        Z = self.u2(self.c2(X))
        return self.merge(torch.cat([X, Z], dim=1))

model = UNet(out_size=32)
model.cuda()

model = torch.compile(model, backend="inductor")

out = model(torch.randn(192,32,256,256).cuda())
out.sum().backward()
print("done1", out.shape)

model.zero_grad()

out = model(torch.randn(99,32,256,256).cuda())
out.sum().backward()
print("done2", out.shape)
```

This is minimal example I am able to generate, removing anything causes code to magically work.
Works with cudagraphs, eager and aot_eager, does not work with inductor.

### Error logs

done1 torch.Size([192, 32, 256, 256])
Traceback (most recent call last):
  File "/home/usama/bad.py", line 31, in <module>
    out.sum().backward()
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 3232, in backward
    out = call_compiled_backward()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 3204, in call_compiled_backward
    out = call_func_with_args(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1506, in call_func_with_args
    out = normalize_as_list(f(args))
                            ^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 374, in __call__
    return self.get_current_callable()(inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 628, in run
    return model(new_inputs)
           ^^^^^^^^^^^^^^^^^
  File "/home/usama/miniconda3/envs/block_prune/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 401, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/torchinductor_usama/3w/c3w3ke7cwxjmhkvjvhjcdkaioig37qv7d4lyshvrm7ep3ndicou7.py", line 270, in call
    assert_size_stride(buf3, (s0, 64, 256, 256), (4194304, 1, 16384, 64))

### Minified repro

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
import torch._inductor.inductor_prims

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config

isolate_fails_code_str = None

# torch version: 2.1.1+cu121
# torch cuda version: 12.1
# torch git version: 4c55dc50355d5e923642c59ad2a23d6ad54711e7

# CUDA Info: 
# nvcc not found
# GPU Hardware Info: 
# Tesla T4 : 1 

from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, primals_7, primals_1, primals_3, primals_5, primals_8, convolution, cat, tangents_1):
        sum_1 = torch.ops.aten.sum.dim_IntList(tangents_1, [0, 2, 3])
        convolution_backward = torch.ops.aten.convolution_backward.default(tangents_1, cat, primals_5, [32], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [True, True, False]);  tangents_1 = cat = primals_5 = None
        getitem = convolution_backward[0]
        getitem_1 = convolution_backward[1];  convolution_backward = None
        slice_2 = torch.ops.aten.slice.Tensor(getitem, 1, 32, 64);  getitem = None
        sum_2 = torch.ops.aten.sum.dim_IntList(slice_2, [0, 2, 3])
        convolution_backward_1 = torch.ops.aten.convolution_backward.default(slice_2, convolution, primals_3, [32], [4, 4], [0, 0], [1, 1], True, [0, 0], 1, [True, True, False]);  slice_2 = convolution = primals_3 = None
        getitem_3 = convolution_backward_1[0]
        getitem_4 = convolution_backward_1[1];  convolution_backward_1 = None
        sum_3 = torch.ops.aten.sum.dim_IntList(getitem_3, [0, 2, 3])
        convolution_backward_2 = torch.ops.aten.convolution_backward.default(getitem_3, primals_8, primals_1, [128], [4, 4], [0, 0], [1, 1], False, [0, 0], 1, [False, True, False]);  getitem_3 = primals_8 = primals_1 = None
        getitem_7 = convolution_backward_2[1];  convolution_backward_2 = None
        return [getitem_7, sum_3, getitem_4, sum_2, getitem_1, sum_1, None, None]
        
def load_args(reader):
    reader.symint(99)  # primals_7
    buf0 = reader.storage(None, 262144, device=device(type='cuda', index=0))
    reader.tensor(buf0, (128, 32, 4, 4), requires_grad=True, is_leaf=True)  # primals_1
    buf1 = reader.storage(None, 262144, device=device(type='cuda', index=0))
    reader.tensor(buf1, (128, 32, 4, 4), requires_grad=True, is_leaf=True)  # primals_3
    buf2 = reader.storage(None, 8192, device=device(type='cuda', index=0))
    reader.tensor(buf2, (32, 64, 1, 1), (64, 1, 64, 64), requires_grad=True, is_leaf=True)  # primals_5
    buf3 = reader.storage(None, 830472192, device=device(type='cuda', index=0))
    reader.tensor(buf3, (99, 32, 256, 256), is_leaf=True)  # primals_8
    buf4 = reader.storage(None, 207618048, device=device(type='cuda', index=0))
    reader.tensor(buf4, (99, 128, 64, 64), is_leaf=True)  # convolution
    buf5 = reader.storage(None, 1660944384, device=device(type='cuda', index=0))
    reader.tensor(buf5, (99, 64, 256, 256), is_leaf=True)  # cat
    buf6 = reader.storage(None, 830472192, device=device(type='cuda', index=0))
    reader.tensor(buf6, (99, 32, 256, 256), is_leaf=True)  # tangents_1
load_args._version = 0
mod = Repro()
if __name__ == '__main__':
    from torch._dynamo.repro.after_aot import run_repro
    run_repro(mod, load_args, accuracy=False, command='minify', save_dir='/home/vboza/dev-ai/torch_compile_debug/run_2023_11_29_12_29_17_578281-pid_3430/minifier/checkpoints', tracing_mode='real', check_str=None)

### Versions

Collecting environment information...
PyTorch version: 2.1.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-17)
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.26

Python version: 3.11.6 (main, Nov 15 2023, 12:42:11) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)] (64-bit runtime)
Python platform: Linux-5.10.178-162.673.amzn2.x86_64-x86_64-with-glibc2.26
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3092.280
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] mypy==1.7.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] pytorch-msssim==1.0.0
[pip3] torch==2.1.1
[pip3] triton==2.1.0
[conda] No relevant packages

**Comment by shunting314** [comment]
I'm not able to repro:

```
$ python ~/x.py
done1 torch.Size([192, 32, 256, 256])
done2 torch.Size([99, 32, 256, 256])
```

Can you try latest pytorch?

**Comment by usamec** [comment]
Tried nightly, it seems to be fixed there.
