### ISSUE TITLE
torch.compile x autograd.Function x enum inputs graph breaks

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#114777]
See following repro:
```py
import torch
from enum import Enum
from typing import *

class SomeEnum(Enum):
    A = 0
    B = 1
    C = 2
    D = 3


class DoNothing(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, e):
        return x

    @staticmethod
    def backward(ctx, g):
        return g

@torch.compile(backend="eager", fullgraph=True)
def f(x):
    output = DoNothing.apply(
        input,
        SomeEnum.A,
    )
    return output

input = torch.tensor([[1., 2, 3], [4, 5, 6]], requires_grad=True)
y = f(input)
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
The error is 

```
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [WARNING] speculate_subgraph: while introspecting the user-defined autograd.Function, we were unable to trace function `trampoline_autograd_fwd` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown.
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR] HigherOrderOperator with body that accepts non-Tensors as input. Got: <enum 'SomeEnum'>
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR] Traceback (most recent call last):
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 224, in speculate_subgraph
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     args = validate_args_and_maybe_create_graph_inputs(
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 160, in validate_args_and_maybe_create_graph_inputs
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     raise unimplemented(
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     raise Unsupported(msg)
[2023-11-29 22:36:59,251] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR] torch._dynamo.exc.Unsupported: HigherOrderOperator with body that accepts non-Tensors as input. Got: <enum 'SomeEnum'>
Traceback (most recent call last):
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 224, in speculate_subgraph
    args = validate_args_and_maybe_create_graph_inputs(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 160, in validate_args_and_maybe_create_graph_inputs
    raise unimplemented(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: HigherOrderOperator with body that accepts non-Tensors as input. Got: <enum 'SomeEnum'>

```
