### ISSUE TITLE
aot_module fails to trace modules whose parameters are tied (models with shared params)

### ISSUE THREAD

**Issue by xuzijian629** [pytorch/pytorch#114743]
### 🐛 Describe the bug

When a model has multiple parameters whose corresponding parameter tensors are identical, torch's trace cannot the model. Please refer to the minimal repro.

Parameter sharing is a common technique, and we hope that pytorch chould support this kind of cases.

### Error logs

```
Traceback (most recent call last):
  File "/XXXXXXXXXXXXXXXXXXXXXX/hoge.py", line 20, in <module>
    aot_model(torch.rand(10))
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3781, in forward
    return compiled_f(
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3725, in returned_function
    compiled_fn = create_aot_dispatcher_function(
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3429, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2212, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2392, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2804, in aot_dispatch_autograd
    fx_g = aot_dispatch_autograd_graph(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2781, in aot_dispatch_autograd_graph
    fx_g = create_functionalized_graph(
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1420, in create_functionalized_graph
    fx_g = make_fx(helper, decomposition_table=aot_config.decompositions)(*args)
  File "/usr/local/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/usr/local/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 468, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/usr/local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
  File "/usr/local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 684, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/usr/local/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 485, in wrapped
    out = f(*tensors)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1409, in joint_helper
    return functionalized_f_helper(primals, tangents)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1363, in functionalized_f_helper
    f_outs = fn(*f_args)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1334, in inner_fn_with_anomaly
    return inner_fn(*args)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1271, in inner_fn
    outs, tangent_mask = fn(*primals)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1201, in inner_fn
    outs = fn(*args_maybe_cloned)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3525, in flat_fn
    tree_out = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3766, in functional_call
    return torch.func.functional_call(mod, params_and_buffers, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_functorch/functional_call.py", line 143, in functional_call
    return nn.utils.stateless._functional_call(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/utils/stateless.py", line 261, in _functional_call
    with _reparametrize_module(
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/utils/stateless.py", line 98, in _reparametrize_module
    untied_parameters_and_buffers = _untie_named_tensors_map(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/utils/stateless.py", line 73, in _untie_named_tensors_map
    raise ValueError(
ValueError: functional_call got multiple values for keys ['weight1', 'weight2'], which are tied. Consider using tie_weights=False
```

### Minified repro

```python
import torch
import torch._functorch.aot_autograd

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        weight = torch.nn.Parameter(torch.randn(10, 10, requires_grad=True))
        self.register_parameter("weight1", weight)
        self.weight2 = self.weight1

    def forward(self, x):
        t = torch.matmul(self.weight1, x) + torch.matmul(self.weight2, x)
        return t.sum()

def nop(*args):
    pass

model = Model()
aot_model = torch._functorch.aot_autograd.aot_module(model, fw_compiler=nop, bw_compiler=nop)
aot_model(torch.rand(10))
```

### Versions

Version info details. Lastest torch 2.1.0 will reproduce the issue too.

<details>

```
python3 collect_env.py 
Collecting environment information...
PyTorch version: 2.1.0+gcc10cuda12.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 10.5.0-1ubuntu1~22.04) 10.5.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 535.104.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             36
On-line CPU(s) list:                0-35
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz
CPU family:                         6
Model:                              85
Thread(s) per core:                 1
Core(s) per socket:                 18
Socket(s):                          2
Stepping:                           7
CPU max MHz:                        4000.0000
CPU min MHz:                        1200.0000
BogoMIPS:                           6200.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          1.1 MiB (36 instances)
L1i cache:                          1.1 MiB (36 instances)
L2 cache:                           36 MiB (36 instances)
L3 cache:                           49.5 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-17
NUMA node1 CPU(s):                  18-35
Vulnerability Gather data sampling: Vulnerable: No microcode
Vulnerability Itlb multihit:        KVM: Mitigation: VMX disabled
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] flake8-bugbear==22.4.25
[pip3] mypy==0.790
[pip3] mypy-extensions==0.4.4
[pip3] numpy==1.23.1
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.16.3
[pip3] pytorch-pfn-extras==0.7.2
[pip3] pytorch3d==0.7.5
[pip3] torch==2.1.0+gcc10cuda12.1
[pip3] torch-dftd==0.3.0
[pip3] torchrecomp==0.1.0
[pip3] torchvision==0.16.0+gcc10cuda12.1
[pip3] triton==2.1.0
[conda] Could not collect
```

</details>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by shunting314** [comment]
@bdhirsh do you want to take this one?

**Comment by bdhirsh** [comment]
I think we'd accept a patch fixing this. To be fair though, `torch.export` is mostly meant as the user-facing API on top of `aot_export_module`. So if you're using aot_export_module to get out graph, I would try export instead.

**Comment by xuzijian629** [comment]
Thanks for the comments! Unfortunately, the problem still reproduces with the nightly build.

```
$ pip show torch
Name: torch
Version: 2.3.0.dev20240111+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/joe/hogeenv/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, pytorch-triton, sympy, typing-extensions
Required-by: pytorch-lightning, torchmetrics, torchvision
```

**Comment by zou3519** [comment]
The recommendation here is to use torch.export.export instead of aot_module directly. Using torch.export.export this works:
```py
import torch
import torch._functorch.aot_autograd

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        weight = torch.nn.Parameter(torch.randn(10, 10, requires_grad=True))
        self.register_parameter("weight1", weight)
        self.weight2 = self.weight1

    def forward(self, x):
        t = torch.matmul(self.weight1, x) + torch.matmul(self.weight2, x)
        return t.sum()

def nop(*args):
    pass

model = Model()
ep = torch.export.export(model, (torch.rand(10),))
print(ep.module().code)
```
