### ISSUE TITLE
[Add][compile] Tensor with dtype torch.int64 is not the expected dtype of torch.int32!

### ISSUE THREAD

**Issue by imrkbhandari** [pytorch/pytorch#114742]
### 🐛 Describe the bug

Other parameter is not properly handled when it is Number for add op.

### Please use the below code to reproduce the issue:
import torch

def model_add(params):
    result = torch.add(**params)
    return result

ifm = torch.randint(low=-50,high=50,size=(8, 24, 24, 3),dtype = torch.int32)
other = int(0.9)
alpha = int(0.4)

out = torch.empty([1],dtype=torch.float32)

params = {"other": other, "alpha":alpha, "input": ifm}
foo = torch.compile(model_add, backend="eager")
output = foo(params)
print(output)

**Error logs**
Traceback (most recent call last):
  File "add_compile.py", line 17, in <module>
    output = foo(params)
  File "/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 729, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1274, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1376, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1541, in dispatch
    r = func(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
  File "/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 229, in _fn
    result = fn(*args, **kwargs)
  File "/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 132, in _fn
    result = fn(**bound.arguments)
  File "/lib/python3.8/site-packages/torch/_refs/__init__.py", line 1028, in add
    output = prims.add(a, b)
  File "/lib/python3.8/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
  File "/lib/python3.8/site-packages/torch/_prims/__init__.py", line 345, in _elementwise_meta
    utils.check_same_dtype(*args)
  File "/lib/python3.8/site-packages/torch/_prims_common/__init__.py", line 1139, in check_same_dtype
    raise RuntimeError(msg)
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method add of type object at 0x7f96e3dc2220>(*(), **{'other': 0, 'alpha': 0, 'input': FakeTensor(..., size=(8, 24, 24, 3), dtype=torch.int32)}):
Tensor with dtype torch.int64 is not the expected dtype of torch.int32!

from user code:
   File "/UT/add_compile.py", line 5, in model_add
    result = torch.add(**params)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Versions

[pip3] numpy==1.24.4
[pip3] torch==2.1.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.1

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by shunting314** [comment]
Do you mind provide a repro with proper indent?

**Comment by shunting314** [comment]
The repro
```
import torch

def model_add(params):
    result = torch.add(**params)

    return result

ifm = torch.randint(low=-50,high=50,size=(8, 24, 24, 3),dtype = torch.int32)
other = int(0.9)
alpha = int(0.4)

out = torch.empty([1],dtype=torch.float32)

params = {"other": other, "alpha":alpha, "input": ifm}
foo = torch.compile(model_add, backend="eager")
output = foo(params)
print(output)
```
works for me. The issue may have already been fixed. Please try the latest pytorch nightly build or build from source.
