### ISSUE TITLE
 'torch.onnx' has no attribute 'dynamo_export'

### ISSUE THREAD

**Issue by ShuoerWang** [pytorch/pytorch#114763]
### 🐛 Describe the bug

code: https://pytorch.org/docs/stable/onnx_dynamo.html#a-simple-example
          (need to add 'import torch.nn as nn')
python: 3.11
torch: 2.1
cuda: 12.1
onnx: 1.15.0 
onnxscript: 0.1.0
error:
```
Traceback (most recent call last):
  File "/xxx/onnx0.py", line 24, in <module>
    export_output = torch.onnx.dynamo_export(model, tensor_x)
                    ^^^^^^^^^^
  File "/xxx/miniconda/envs/onnx/lib/python3.11/site-packages/torch/__init__.py", line 1831, in __getattr__
    return importlib.import_module(f".{name}", __name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/miniconda/envs/onnx/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/xxx/miniconda/envs/onnx/lib/python3.11/site-packages/torch/onnx/__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "/xxx/miniconda/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter.py", line 65, in <module>
    from torch.onnx._internal.fx import diagnostics
  File "/xxx/miniconda/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/fx/diagnostics.py", line 10, in <module>
    import onnxscript  # type: ignore[import]
    ^^^^^^^^^^^^^^^^^
  File "/xxx/miniconda/envs/onnx/lib/python3.11/site-packages/onnxscript/__init__.py", line 7, in <module>
    from .backend.onnx_export import export2python as proto2python
  File "/xxx/miniconda/envs/onnx/lib/python3.11/site-packages/onnxscript/backend/onnx_export.py", line 10, in <module>
    import onnx
  File "/xxx/repo/stable-diffusion-pytorch/onnx.py", line 8, in <module>
    onnx_program = torch.onnx.dynamo_export(clip, rand_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torch.onnx' has no attribute 'dynamo_export' (most likely due to a circular import)
```

### Versions

```
PyTorch version: 2.1.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-70-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla P100-PCIE-12GB

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          22
On-line CPU(s) list:             0-21
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E7-8890 v4 @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       22
Stepping:                        1
BogoMIPS:                        4389.42
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       352 KiB (11 instances)
L1i cache:                       352 KiB (11 instances)
L2 cache:                        2.8 MiB (11 instances)
L3 cache:                        60 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-21
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] onnx==1.15.0
[pip3] onnxscript==0.1.0.dev20231129
[pip3] torch==2.1.1+cu121
[pip3] torchaudio==2.1.1+cu121
[pip3] torchvision==0.16.1+cu121
[pip3] triton==2.1.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.1.1+cu121              pypi_0    pypi
[conda] torchaudio                2.1.1+cu121              pypi_0    pypi
[conda] torchvision               0.16.1+cu121             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

**Comment by ShuoerWang** [comment]
Problem solved. Local module conflict issue. My mistake.

**Comment by lhcezx** [comment]
> Problem solved. Local module conflict issue. My mistake.

Hi, I am currently facing the same problem and would like to ask you which conflicts led to this problem?

**Comment by bigmover** [comment]
> > Problem solved. Local module conflict issue. My mistake.
> 
> Hi, I am currently facing the same problem and would like to ask you which conflicts led to this problem?

Same error with pytorch! Wether to have some solution to it?

**Comment by YourSaDady** [comment]
Same error. Could you please share your solution? Thanks!
