### ISSUE TITLE
MacOS tests randomly fail after https://github.com/pytorch/pytorch/commit/165f4f6ccf7522d75df99c30821d583dfc58ad62

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#114840]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/commit/165f4f6ccf7522d75df99c30821d583dfc58ad62 introduces build time incompatible changes, which on the other hand passed CI on PR

From the failures, it looks like lots of tests are using torchvision, which somehow magically appears on the system, so the failures would look something like:
```
Traceback (most recent call last):
  File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_proxy_tensor.py", line 85, in <module>
    import torchvision
  File "/Users/ec2-user/.local/lib/python3.9/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Users/ec2-user/.local/lib/python3.9/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_7041360280/lib/python3.9/site-packages/torch/library.py", line 440, in inner
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_7041360280/lib/python3.9/site-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
```

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @pytorch/pytorch-dev-infra @albanD

**Comment by malfet** [comment]
On the nodes that work, `torchvision` is not installed, but on the offending ones it is installed into `.local/lib/python3.9` folder
