### ISSUE TITLE
Nvidia P100, where to disable upcasting? Plus kernel image missing.

### ISSUE THREAD

**Issue by Ph0rk0z** [pytorch/pytorch#114949]
### 🐛 Describe the bug

P100 upcasts all FP16 to FP32. I would like to disable this and try out the FP16 support despite any numerical instability. Can anyone point me at the correct file to comment this behavior out? If the below is true, I probably have to recompile pytorch anyways.

Also, is SM6.0 fully supported by the binaries? When using fairseq and hubert it is complaining of a missing kernel image when doing the forward pass. I had tried to recompile fairseq so it seems like a pytorch problem? It works fine on SM6.1 and nothing except pytorch and fairseq is imported.

```
Traceback (most recent call last):
  File "/home/supermicro/ai/TavernAI-extras/modules/voice_conversion/rvc/rvc.py", line 233, in vc_single
    audio_opt = vc.pipeline(
  File "/home/supermicro/ai/TavernAI-extras/modules/voice_conversion/rvc/vc_infer_pipeline.py", line 355, in pipeline
    self.vc(
  File "/home/supermicro/ai/TavernAI-extras/modules/voice_conversion/rvc/vc_infer_pipeline.py", line 154, in vc
    logits = model.extract_features(**inputs)
  File "/home/supermicro/ai/TavernAI-extras/modules/voice_conversion/fairseq/models/hubert/hubert.py", line 535, in extract_features
    res = self.forward(
  File "/home/supermicro/ai/TavernAI-extras/modules/voice_conversion/fairseq/models/hubert/hubert.py", line 445, in forward
    unmasked_features = features.clone()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Versions

Torch 2.1.1 CUDA 11.8

**Comment by GuWei007** [comment]
I didn't understand your question. Can you provide a reproducible example of why P100 triggers the FP16 to FP32 upcast?
