### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by timotheecour** [pytorch/pytorch#115138]
### 🐛 Describe the bug

cross-posting from https://github.com/VKCOM/YouTokenToMe/issues/113 (since I'm not sure if it belongs in pytorch or YouTokenToMe):

reduced from a more complex example:

```
conda create -n tmp2 python=3.10
conda activate tmp2
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install youtokentome
```
then:

`python -c 'import youtokentome; import torch'`
works

`python -c 'import torch; import youtokentome'`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/timothee/.conda/envs/tmp1/lib/python3.10/site-packages/youtokentome/__init__.py", line 1, in <module>
    from .youtokentome import BPE
  File "/home/timothee/.conda/envs/tmp1/lib/python3.10/site-packages/youtokentome/youtokentome.py", line 4, in <module>
    import _youtokentome_cython
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/timothee/.conda/envs/tmp1/lib/python3.10/site-packages/_youtokentome_cython.cpython-310-x86_64-linux-gnu.so)
```

environment note:
```
grep -E '^(VERSION|NAME)=' /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
```

## workaround 1
`import torch` before `import youtokentome` or to add:

## workaround 2
as mentioned in https://github.com/BVLC/caffe/issues/4953#issuecomment-782131028
```
conda install libgcc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.conda/envs/tmp1/lib
```

neither workaround is great and shouldn't be needed

### Versions

Collecting environment information...
PyTorch version: 2.1.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Oracle Linux Server 7.9 (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

[...]

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.1+cu118
[pip3] torchaudio==2.1.1+cu118
[pip3] torchvision==0.16.1+cu118
[pip3] triton==2.1.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.1.1+cu118              pypi_0    pypi
[conda] torchaudio                2.1.1+cu118              pypi_0    pypi
[conda] torchvision               0.16.1+cu118             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by shink** [comment]
I installed pytorch from source, and had a same error:

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pytorch/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /root/anaconda3/envs/ai/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/pytorch/torch/lib/libtorch_python.so)
```

fixed by:

```shell
ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /root/anaconda3/envs/ai/bin/../lib/libstdc++.so.6
```
