### ISSUE TITLE
Compiling SDPA with TensorSubclass Mask fails with FullGraph=True

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#115363]
# Summary
I recently added the CausalBias tensor subclass that is used in conjunction with scaled_dot_product_attention. I also created a test that exercises this new code path:
https://github.com/pytorch/pytorch/blob/686a3e0bf08af50a3b83532058fc5a6667365e51/test/test_transformers.py#L3073

Trying to run this test with torch compile with backend = dynamo fails with: 
``` Shell
________________________________ TestAttnMasksCUDA.test_causal_variants_compile_causal_variant_2_shape1_cuda _________________________________
Traceback (most recent call last):
  File "/home/drisspg/meta/pytorch/torch/_dynamo/utils.py", line 556, in proxy_args_kwargs
    proxy_kwargs = {key: arg.as_proxy() for key, arg in kwargs.items()}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/utils.py", line 556, in <dictcomp>
    proxy_kwargs = {key: arg.as_proxy() for key, arg in kwargs.items()}
                         ^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/variables/lazy.py", line 90, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/variables/base.py", line 274, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(CausalBias)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/drisspg/miniconda3/envs/dev/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/home/drisspg/miniconda3/envs/dev/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/home/drisspg/miniconda3/envs/dev/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/testing/_internal/common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "/home/drisspg/meta/pytorch/torch/testing/_internal/common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "/home/drisspg/meta/pytorch/torch/testing/_internal/common_device_type.py", line 429, in instantiated_test
    raise rte
  File "/home/drisspg/meta/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/test/test_transformers.py", line 3093, in test_causal_variants_compile
    self.run_test(device, True, make_q_tensor, make_kv_tensor, attn_bias, forw_tol, grad_tol)
  File "/home/drisspg/meta/pytorch/test/test_transformers.py", line 3014, in run_test
    sdpa_output = sdpa_op(
                  ^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
                       ^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/drisspg/meta/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/drisspg/meta/pytorch/torch/_dynamo/symbolic_convert.py", line 2144, in run
    super().run()
  File "/home/drisspg/meta/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/drisspg/meta/pytorch/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/symbolic_convert.py", line 1252, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/drisspg/meta/pytorch/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/variables/lazy.py", line 90, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/variables/torch.py", line 690, in call_function
    *proxy_args_kwargs(args, kwargs),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/utils.py", line 562, in proxy_args_kwargs
    raise unimplemented(
          ^^^^^^^^^^^^^^
  File "/home/drisspg/meta/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function args: TensorVariable() TensorVariable() TensorVariable() UserDefinedObjectVariable() ConstantVariable() ConstantVariable() ConstantVariable()

from user code:
   File "/home/drisspg/meta/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


To execute this test, run the following from the base repo dir:
     python test/test_transformers.py -k test_causal_variants_compile_causal_variant_2_shape1_cuda

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

cc @hameerabbasi @rgommers @peterbell10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by Chillee** [comment]
cc: @mlazos 

I think we need to manually put this in the `__torch_function__` subclass config?

**Comment by drisspg** [comment]
Yeah you are right, @mlazos and I had a convo about this that I completely forgot. I have since inherited from torch.tensor and should add to the list

**Comment by mlazos** [comment]
@drisspg one tip just to double check that it's a tensor subclass issue is to try and compile your function standalone if possible, I think we discussed that you did this already and it traces correctly?

**Comment by drisspg** [comment]
Updating here with latest error message:

https://github.com/pytorch/pytorch/pull/116071#issuecomment-1885807887

**Comment by mlazos** [comment]
In this case the user defined class needs to be a callable, I don't think I handle this correctly in builder.py. Let me look into this.

**Comment by mlazos** [comment]
> In this case the user defined class needs to be a callable, I don't think I handle this correctly in builder.py. Let me look into this.

Since this is a C struct we'll need to add special handling in dynamo for this, see https://github.com/pytorch/pytorch/pull/117207
