### ISSUE TITLE
Export Transformer to ONNX results in SymIntArrayRef Error

### ISSUE THREAD

**Issue by mkueh** [pytorch/pytorch#115501]
I try to Export the PyTorch default Transformer (self._pytorch_nn_model) after i trained the model (with pytorch) with a really easy task to rotate a sequenze

Pytorch nightly
torch-2.2.0.dev20231208+cu121

        X_example = np.random.randint(5, 80, size=(2, 20))
        X_example = torch.LongTensor(X_example).to('cpu')
        y_example = np.random.randint(5, 80, size=(2, 12))
        y_example = torch.LongTensor(y_example).to('cpu')

        X_example_mask = self._triu_mask_generator.create_triu_mask(X_example.size(1), X_example.size(1),
                                                                   'cpu')
        y_example_mask = self._triu_mask_generator.create_triu_mask(y_example.size(1), y_example.size(1),
                                                                    'cpu')
        X_example_padding_mask = self._padding_mask_generator.create_padding_mask(X_example, 0, 'cpu')
        y_example_padding_mask = self._padding_mask_generator.create_padding_mask(y_example, 0, 'cpu')

        torch_input_args = ()
        torch_input_kwargs = {'X': X_example, 'y': y_example,
                              'X_mask': X_example_mask, 'y_mask': y_example_mask,
                              'X_padding_mask': X_example_padding_mask,
                              'y_padding_mask': y_example_padding_mask}

        self._pytorch_nn_model.to('cpu')
        export_options = torch.onnx.ExportOptions(dynamic_shapes=True)
        onnx_program = torch.onnx.dynamo_export(self._pytorch_nn_model, *torch_input_args,
                                                **torch_input_kwargs, export_options=export_options)
                                                
PyTorch gives me the following error

    /opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py:137: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
    warnings.warn(
    [2023-12-08 20:08:02,359] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Eq(s2, 155) == False, this could result in accuracy problems
    [2023-12-08 20:08:02,376] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Eq(s1, 155) == False, this could result in accuracy problems
    Traceback (most recent call last):
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1385, in dynamo_export
    ).export()
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1128, in export
    graph_module = self.options.fx_tracer.generate_fx(
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 223, in generate_fx
    return self.pre_export_passes(options, model, graph_module, updated_model_args)  # type: ignore[return-value]
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 233, in pre_export_passes
    return exporter.common_pre_export_passes(
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1424, in common_pre_export_passes
    module = passes.Functionalize(
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 151, in wrapper
    ctx.log_and_raise_if_error(diag)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 366, in log_and_raise_if_error
    raise diagnostic.source_exception
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 135, in wrapper
    return_values = fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/fx/_pass.py", line 275, in run
    module = self._run(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/fx/passes/functionalization.py", line 123, in _run
    graph_module = proxy_tensor.make_fx(
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 871, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 488, in _fn
    return fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 483, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 488, in _fn
    return fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 821, in trace
    (self.create_arg(fn(*args)),),
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 519, in wrapped
    out = f(*tensors)
    File "<string>", line 1, in <lambda>
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/fx/passes/functionalization.py", line 86, in wrapped
    out = function(*inputs_functional)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/fx/passes/_utils.py", line 30, in wrapped
    return torch.fx.Interpreter(graph_module).run(*args)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
    File "/opt/miniconda/lib/python3```
    .10/site-packages/torch/_ops.py", line 513, in __call__
    return self._op(*args, **(kwargs or {}))
    File "/opt/miniconda/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 596, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 631, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 376, in proxy_call
    out = func(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_ops.py", line 513, in __call__
    return self._op(*args, **(kwargs or {}))
    File "/opt/miniconda/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1392, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1708, in dispatch
    r = func(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_ops.py", line 513, in __call__
    return self._op(*args, **(kwargs or {}))
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 250, in _fn
    result = fn(*args, **kwargs)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/_meta_registrations.py", line 1905, in meta_baddbmm
    self = self.expand((dim1, dim2, dim3))
    RuntimeError: aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:2252: SymIntArrayRef expected to contain only concrete integers
    
    While executing %baddbmm : [num_users=1] = call_function[target=torch.ops.aten.baddbmm.default](args = (%add_3, %div, %transpose_5), kwargs = {})
    Original traceback:
    File "X/model/pytorchModels/models/transformer_model/structure/transformer_nn.py", line 35, in forward
    encoded_X = self.encoder(X, X_mask=X_mask, X_padding_mask=X_padding_mask)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
    File "X/models/transformer_model/structure/encoder.py", line 22, in forward
    X = mod(X=X, X_mask=X_mask, X_padding_mask=X_padding_mask)
    File "/opt/miniconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
    File "X/model/pytorchModels/models/transformer_model/Layer/encoder_layer.py", line 21, in forward
    X_new, _ = self.self_attn(X, X, X, attn_mask=X_mask, key_padding_mask=X_padding_mask)
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
    File "X/main_for_test.py", line 145, in <module>
    run_training_pytorchTransformer()
    File "X/main_for_test.py", line 102, in run_training_pytorchTransformer
    pytorch_Model.save_2_onnx_model('transformer.onnx')
    File "X/model/pytorchModels/pytorch_model.py", line 142, in save_2_onnx_model
    self._model.save_2_onnx_model(path)
    File "X/model/pytorchModels/models/transformer_model/transformer.py", line 116, in save_2_onnx_model
    onnx_program = torch.onnx.dynamo_export(self._pytorch_nn_model, *torch_input_args,
    File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1396, in dynamo_export
    raise OnnxExporterError(
    torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
    ```

_Originally posted by @mkueh in https://github.com/pytorch/pytorch/issues/110563#issuecomment-1847698173_
            

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by aviator19941** [comment]
Is there any solution/workaround for this error?

**Comment by mkueh** [comment]
I dont find any working workaround
 My current solution is a torchscript export, to get a easy to use model. ts not a really onnx workaround :/

**Comment by justinchuby** [comment]
Consider using the `torch.export.export` API to get an exported program; then feed that into `torch.onnx.dynamo_export`?

**Comment by mkueh** [comment]
okay, after Christmas, I try it out. Can you briefly explain why this should work? In other words, what is the difference?

**Comment by justinchuby** [comment]
torch.onnx.dynamo_export is a new model export api we are developing. you can read more about it on https://pytorch.org/docs/stable/onnx_dynamo.html

**Comment by ezyang** [comment]
Do you have a self contained repro script. The posted code is not runnable as is.

**Comment by mkueh** [comment]
No sry, but self._pytorch_nn_model is a standard pytorch transformer model. The Mask creater creating the masks.
I can reproduce the problem easy by try to Export the Pytorch transformer with onnx dynamo

**Comment by justinchuby** [comment]
Please share the error message. Standard transformer models should be exportable without errors.

**Comment by mkueh** [comment]
I try to export the transformer model with dynamic shapes.

The error message is:
```

RuntimeError: aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:2252: SymIntArrayRef expected to contain only concrete integers

File "/opt/miniconda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1396, in dynamo_export
raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues

```

**Comment by justinchuby** [comment]
Sorry I got distracted from the original recommendation. 

The recommendation is to use torch.export.export first, and then run onnx dynamo export. 

This way if the process fails in the first call (torch.export.export), we will have a better idea on what to fix. 

Please share the full error stack should you see any issues with torch.export.export

**Comment by thiagocrepaldi** [comment]
> No sry, but self._pytorch_nn_model is a standard pytorch transformer model. The Mask creater creating the masks. I can reproduce the problem easy by try to Export the Pytorch transformer with onnx dynamo

Please do repro and share the script

**Comment by titaiwangms** [comment]
Try export it to exportedprogram first with `torch.export.export`, and then feed it into `torch.onnx.export`. I found some transformers models would work in that way.
https://pytorch.org/docs/stable/export.html

```python
export_program = torch.export.export(self._pytorch_nn_model, args=torch_input_args, kwargs=torch_inputs_kwargs)
onnx_program = torch.onnx.dynamo_export(export_program , *torch_input_args,
                                          **torch_input_kwargs, export_options=export_options)
```

**Comment by MaanavD** [comment]
Hi @mkueh ,

Haven't heard back from you since December, closing the issue as stale. Feel free to reopen if you still need assistance with the issue :)
