### ISSUE TITLE
gradoutput shapes not being resized for some functions in backward

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1155]
As Timothee Lacroix reports:

```python
import torch
from torch import nn

dtype=torch.FloatTensor
class Test(nn.Module):
    def __init__(self, N, R, A, P, k):
        super(Test, self).__init__()

        self.k = k             # maximum subgraph size
        self.at = nn.Parameter(torch.randn(R, k, k).type(dtype), requires_grad=True)
        self.perm = nn.Parameter(torch.randn(N, k).type(dtype), requires_grad=True)

    def forward(self, (s, o, r)):
        res = self.perm[s, :].dot(self.at[r, :, :].mm(self.perm[o, :].view(self.k, 1)))
        return res


model = Test(5, 3, 1, 1, 3)

pred = model.forward((0,0,0))
pred.backward()
```

```
Traceback (most recent call last):
  File "a.py", line 21, in <module>
    pred.backward()
  File "/Users/chinso/anaconda/lib/python2.7/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/Users/chinso/anaconda/lib/python2.7/site-packages/torch/autograd/_functions/blas.py", line 40, in backward
    grad_matrix1 = torch.mm(grad_output, matrix2.t())
RuntimeError: matrices expected, got 1D, 2D tensors at /Users/soumith/miniconda2/conda-bld/pytorch_1490902430884/work/torch/lib/TH/generic/THTensorMath.c:1224
```

**Comment by apaszke** [comment]
It's because apparently `.dot` accepts 1xN inputs as valid vectors too... 
Here's a workaround for now:
```python
tmp = self.at[r, :, :].mm(self.perm[o, :].view(self.k, 1)).squeeze(0)
res = self.perm[s, :].dot(tmp)
```
