### ISSUE TITLE
torch.export.export fail to export OpenLLama model

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#115552]
### 🐛 Describe the bug

```python
import torch
import transformers


config = transformers.OpenLlamaConfig(
    vocab_size=8096, hidden_size=256, num_hidden_layers=2, num_attention_heads=2
)
batch, seq = 4, 256

def create_model() -> torch.nn.Module:
    return transformers.OpenLlamaModel(config).eval()

def create_args():
    return tuple()

def create_kwargs():
    input_ids = torch.randint(0, config.vocab_size, (batch, seq))
    attention_mask = torch.ones(batch, seq, dtype=torch.bool)
    position_ids = torch.arange(0, seq, dtype=torch.long)
    position_ids = position_ids.unsqueeze(0).view(-1, seq)
    return {"input_ids": input_ids,
            "attention_mask": attention_mask,
            "position_ids": position_ids}

model = create_model()
args = create_args()
kwargs = create_kwargs()

ep = torch.export.export(model, args=args, kwargs=kwargs)
```

error:

```bash
Traceback (most recent call last):
  File "/opt/pytorch/test_export_openllama.py", line 29, in <module>
    ep = torch.export.export(model, args=args, kwargs=kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/export/__init__.py", line 462, in export
    return export__RC__(
           ^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/__init__.py", line 259, in export__RC__
    return _export(
           ^^^^^^^^
  File "/opt/pytorch/torch/export/exported_program.py", line 77, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/__init__.py", line 810, in _export
    gm_torch_level = _export_to_torch_ir(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/__init__.py", line 516, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 1450, in inner
    graph = rewrite_signature(
            ^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 1073, in rewrite_signature
    matched_output_elements_positions = produce_matching(
                                        ^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 1058, in produce_matching
    raise AssertionError(
AssertionError: original output #1 is BaseModelOutputWithPast(last_hidden_state=FakeTensor(..., size=(4, 256, 256), grad_fn=<MulBackward0>), past_key_values=((FakeTensor(..., size=(4, 2, 256, 128), grad_fn=<AddBackward0>), FakeTensor(..., size=(4, 2, 256, 128), grad_fn=<TransposeBackward0>)), (FakeTensor(..., size=(4, 2, 256, 128), grad_fn=<AddBackward0>), FakeTensor(..., size=(4, 2, 256, 128), grad_fn=<TransposeBackward0>))), hidden_states=None, attentions=None), but only the following types are supported: (<class 'torch.Tensor'>, <class 'torch.SymInt'>, <class 'torch.SymFloat'>, <class 'torch.SymBool'>)
```

### Versions

pytorchmain
transformers==4.31.0

**Comment by angelayi** [comment]
I think `BaseModelOutputWithPast` needs to be registered as a pytree node. I thought [this](https://github.com/huggingface/transformers/blob/e5079b0b2abcef11ecbdae60ba4a6636c57b725d/src/transformers/utils/generic.py#L309-L313) was supposed to do it in the transformers codebase, but maybe you need to explicitly do this too?

**Comment by BowenBao** [comment]
Need to bump transformers version in onnx CI it appears @thiagocrepaldi

**Comment by thiagocrepaldi** [comment]
> Need to bump transformers version in onnx CI it appears @thiagocrepaldi

Indeed it fails with `transformers==4.36.0` while it works with `==4.32.1`.

**Comment by titaiwangms** [comment]
OpenLlama is deprecated. We should go with LlamaConfig/LlamaModeling

**Comment by titaiwangms** [comment]
https://huggingface.co/docs/transformers/main/model_doc/open-llama

**Comment by titaiwangms** [comment]
https://github.com/pytorch/pytorch/pull/117703
