### ISSUE TITLE
dynamo does not correctly handle future iterations if a specific iteration is frozen

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#115607]
### 🐛 Describe the bug

Optimizer and `step` no longer update correctly when grads are set to None for a given iteration (here iter 3). Usually, if all grads are None, the step becomes a no-op, which is correct. However, in this case, the no-op-ness should stop after the grads are populated again, which does not happen. Maybe dynamo is caching the no-op step?

This error persists across optimizers, across foreach vs single tensor, and across cpu and cuda.

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (f5f66188)]$ python playground.py 
expected in eager:
step tensor(1.)
step tensor(2.)
step tensor(3.)
step tensor(3.)
step tensor(4.)
step tensor(5.)
what actually happens after dynamo:
step tensor(1.)
step tensor(2.)
step tensor(3.)
step tensor(3.)
step tensor(3.)
step tensor(3.)
```

### Minified repro

```
import torch
def training_loop():
    input = torch.tensor(
        [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
    ).reshape(3, 2)

    model = torch.nn.Sequential(
        torch.nn.Linear(2, 3),
        torch.nn.Sigmoid(),
        torch.nn.Linear(3, 1),
        torch.nn.Sigmoid(),
    )

    params = list(model.parameters())
    optimizer = torch.optim.Adam(params)

    for i in range(6):
        optimizer.zero_grad()
        # Test that step behaves as expected (a no-op) when grads are set to None
        if i != 3:
            output = model(input)
            loss = output.sum()
            loss.backward()

        optimizer.step()
        print("step", optimizer.state[params[0]]["step"])

compiled_training_loop = torch._dynamo.optimize("eager", save_config=False)(training_loop)

print("expected in eager:")
training_loop()

print("what actually happens after dynamo:")
compiled_training_loop()
```

### Versions

main

cc @ezyang @gchanan @zou3519 @kadeng @vincentqb @jbschlosser @albanD @crcrpar @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @mlazos @wconstab @aakhundov

**Comment by janeyx99** [comment]
Continuing this thread with more observations. As a result of this bug, parameter updates after iteration 3 are all incorrect/frozen as expected. e.g., running the following code on almost every optimizer configuration (single tensor, multitensor, etc) will return differing parameters between eager and dynamo EXCEPT foreach ASGD. 

```
import torch
input = torch.tensor(
        [0.1, 0.2, 0.3, 0.4, 0.5, 0.6], device="cuda"
    ).reshape(3, 2)
params = [input]
input.grad = torch.ones_like(input)

def reset():
    global params, input
    input = torch.tensor(
        [0.1, 0.2, 0.3, 0.4, 0.5, 0.6], device="cuda"
    ).reshape(3, 2)
    params = [input]
    input.grad = torch.ones_like(input)


def training_loop():
    optimizer = torch.optim.ASGD(params, foreach=False)

    for i in range(6):
        optimizer.zero_grad()
        #  Test that step behaves as expected (a no-op) when grads are set to None
        if i != 3:
            input.grad = torch.ones_like(input)

        optimizer.step()

compiled_training_loop = torch._dynamo.optimize("eager")(training_loop)

print("expected in EAGER:")
print(f"BEFORE the loop {params=}")
training_loop()
print(f"AFTER the loop {params=}")
reset()
print("=======================================")

print("what actually happens after DYNAMO:")
print(f"BEFORE the loop {params=}")
compiled_training_loop()
print(f"AFTER the loop {params=}")
```

Printout: 
```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (f54bb1ed)]$ python playground.py 
expected in EAGER:
BEFORE the loop params=[tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [0.5000, 0.6000]], device='cuda:0')]
AFTER the loop params=[tensor([[0.0500, 0.1500],
        [0.2500, 0.3500],
        [0.4500, 0.5500]], device='cuda:0')]
=======================================
what actually happens after DYNAMO:
BEFORE the loop params=[tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [0.5000, 0.6000]], device='cuda:0')]
AFTER the loop params=[tensor([[0.0700, 0.1700],
        [0.2700, 0.3700],
        [0.4700, 0.5700]], device='cuda:0')]
```

Changing the code above to use ASGD foreach=True will somehow yield _correct_ results. I'm not sure why, but found it intriguing to point out.

**Comment by mlazos** [comment]
This will get resolved when we trace `_init_group`. Basically we aren't guarding on the grads being `None`.

**Comment by janeyx99** [comment]
Once resolved, it'd be good to check that the tests currently skipped in https://github.com/pytorch/pytorch/pull/115947 can be unskipped.

**Comment by janeyx99** [comment]
Would like to track/note that the freezing of parameters in the middle of the iterations cause Adamax & Adagrad to error (when otherwise they would fall back to eager smoothly) with:

```
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/playground.py", line 115, in <module>
    compiled_training_loop()
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 434, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/playground.py", line 87, in training_loop
    optimizer = torch.optim.Adagrad(params)
  File "/data/users/janeyx/pytorch/playground.py", line 88, in resume_in_training_loop_at_87
    optimizer.step()
  File "/data/users/janeyx/pytorch/playground.py", line 89, in resume_in_training_loop_at_88
    optimizer.zero_grad()
  File "/data/users/janeyx/pytorch/playground.py", line 90, in resume_in_training_loop_at_89
    optimizer.step()
  File "/data/users/janeyx/pytorch/playground.py", line 92, in resume_in_training_loop_at_90
    optimizer.step()
  File "/data/users/janeyx/pytorch/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/optim/adagrad.py", line 120, in step
    adagrad(
  File "/data/users/janeyx/pytorch/torch/optim/adagrad.py", line 221, in adagrad
    func(
  File "/data/users/janeyx/pytorch/torch/optim/adagrad.py", line 369, in _multi_tensor_adagrad
    minus_clr = [-lr / (1 + (_get_value(step) - 1) * lr_decay) for step in device_state_steps]
  File "/data/users/janeyx/pytorch/torch/optim/adagrad.py", line 369, in <listcomp>
    minus_clr = [-lr / (1 + (_get_value(step) - 1) * lr_decay) for step in device_state_steps]
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 597, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 736, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 381, in _convert_frame_assert
    return _compile(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 665, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 638, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 519, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 150, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 484, in transform
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2096, in run
    super().run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2214, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/data/users/janeyx/pytorch/torch/_dynamo/output_graph.py", line 906, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/janeyx/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/janeyx/pytorch/torch/_dynamo/output_graph.py", line 1050, in compile_and_call_fx_graph
    gm = fx.GraphModule(root, self.graph)
  File "/data/users/janeyx/pytorch/torch/fx/graph_module.py", line 401, in __init__
    _copy_attr(root, self, node.target)
  File "/data/users/janeyx/pytorch/torch/fx/graph_module.py", line 230, in _copy_attr
    orig = getattr(from_module, field)
  File "/data/users/janeyx/pytorch/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
torch._dynamo.exc.InternalTorchDynamoError: 'FakeRootModule' object has no attribute 'x'
```

I'm supposing this should also get fixed by tracing `_init_group` and having proper guard handling.

**Comment by janeyx99** [comment]
Since there are still references to this issue on main, we should keep these issues open until those references are either removed or replaced. Do you plan on opening a PR to test those?

**Comment by Essoz** [comment]
Hi Jane,

Thank you for the detailed issue description and I enjoyed reading it. I am a student very interested in PyTorch, and I was curious if there are any real use cases where it would be beneficial to intentionally freeze a specific iteration during training? Or to put it another way, what might be the impact of this bug?

**Comment by janeyx99** [comment]
@Essoz One use case I can think of is in GANs, where you have two models that will run through each other, but only one of them should be training at a time. In those cases, you would freeze one model's parameters but have the values still pipe through it. https://discuss.pytorch.org/t/a-gan-model-in-pytorch-does-not-learn/72497

**Comment by Essoz** [comment]
@janeyx99 Thanks for sharing! Appreciate it!
