### ISSUE TITLE
`torch.jit.save` fails for static function from C++ TorchScript extension with "Failed to downcast a Function to a GraphFunction"

### ISSUE THREAD

**Issue by Luthaf** [pytorch/pytorch#115639]
### 🐛 Describe the bug

We have some code that relies heavily on custom TorchScript classes, and some of these classes also export static functions. The function are fully supported after running the code through `torch.jit.script` but fail when trying to save the scripted module. Here is a minimal reproduction:

```python
import torch
from torch.utils.cpp_extension import load_inline

source = """
struct SomeClass : torch::CustomClassHolder {
    static bool function() {
        return true;
    }
};

TORCH_LIBRARY(static_functions, m) {
  m.class_<SomeClass>("SomeClass")
    .def_static("function", &SomeClass::function);
}
"""

module = load_inline(
    name='static_functions',
    cpp_sources=[source],
    is_python_module=False,
)

def function() -> bool:
    return torch.classes.static_functions.SomeClass.function()


script = torch.jit.script(function)
print(script.code)
torch.jit.save(script, "saved.pt")
```

This outputs (on the `main` branch and with torch 2.1)

```
def function() -> bool:
  _0 = __torch__.torch.classes.static_functions.SomeClass.function
  return _0()

Traceback (most recent call last):
  File "~/code/pytorch/pytorch/tmp/static.py", line 32, in <module>
    torch.jit.save(script, "saved.pt")
  File "~/code/pytorch/pytorch/torch/jit/_serialization.py", line 80, in save
    m.save(f, _extra_files=_extra_files)
RuntimeError: false INTERNAL ASSERT FAILED at "~/code/pytorch/pytorch/torch/csrc/jit/api/function_impl.cpp":59, please report a bug to PyTorch. Failed to downcast a Function to a GraphFunction. This probably indicates that the JIT calling context needs a special case on tryToGraphFunction() instead.
```

### Versions

I just reproduced this with the latest commit on `main`.

```
Collecting environment information...
PyTorch version: 2.3.0a0+git794545c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.27.9
Libc version: N/A

Python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-14.1.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] optree==0.10.0
[pip3] torch==2.3.0a0+git794545c
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
