### ISSUE TITLE
calling nn.utils.parametrize inside torch.compile leads to error

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#115744]
I would expect it to graph break gracefully.
```
import torch.nn as nn
import torch.nn.utils.parametrize as parametrize
torch.manual_seed(0)

class Symmetric(nn.Module):
    def forward(self, X):
        return X.triu() + X.triu(1).transpose(-1, -2)

x = torch.randn(3)

def f(x):
    layer = nn.Linear(3, 3, bias=False)
    parametrize.register_parametrization(layer, "weight", Symmetric())
    y = layer(x)
    return y, layer.weight

f_compiled = torch.compile(f, backend="aot_eager")

out_compiled, weight = f_compiled(x)
out = torch.nn.functional.linear(x, weight)
assert torch.allclose(out_compiled, out)
```
gives
```
Traceback (most recent call last):
  File "/home/rzou/dev/nightly/baz.py", line 20, in <module>
    out_compiled, weight = f_compiled(x)
                           ^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 501, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/baz.py", line 12, in f
    def f(x):
  File "/home/rzou/dev/nightly/baz.py", line 13, in resume_in_f
    layer = nn.Linear(3, 3, bias=False)
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 667, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 730, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
                       ^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 665, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 626, in compile_inner
    check_fn = CheckFunctionManager(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 1004, in __init__
    self.check_fn = self.compile_check_fn(builder, guards, guard_fail_fn)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 1087, in compile_check_fn
    dynamic_dims_sizes = [
                         ^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 1088, in <listcomp>
    convert(self.output_graph.tensor_weakref_to_sizes_strides[t]["size"])
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/rzou/dev/nightly/env/lib/python3.11/site-packages/torch/utils/weak.py", line 170, in __getitem__
    return self.data[self.ref_type(key)]  # CHANGED
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.InternalTorchDynamoError: <weakref at 0x7f6963e11a20; to 'Tensor' at 0x7f6963e115b0>


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/116108

**Comment by spzala** [comment]
@zou3519 Seems like the issue has been fixed. I couldn't reproduce it with the main repo, torch version 2.4.0a0+gitbf834d3
We should close it if you agree. Thanks!

**Comment by zou3519** [comment]
I think @jbschlosser fixed this?

**Comment by jbschlosser** [comment]
#121041 for posterity
