### ISSUE TITLE
ExportedProgram.module(flat=False) doesn't work with torch.cond

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#115790]
### 🐛 Describe the bug

```python
class Bar(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(4, 4)

    def forward(self, x):
        def true_fn(x):
            return self.linear(x).cos()
        def false_fn(x):
            return self.linear(x).sin()
        return torch.cond(x.shape[0] > 4, true_fn, false_fn, [x])

class CondExport(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.bar = Bar()

    def forward(self, x):
        return x.cos() + self.bar(x)

inp = (torch.randn(4, 4),)
ep_strict = torch.export.export(CondExport(), inp)

gm_unflat_strict = ep_strict.module(flat=False)
```
Gives:
```
Traceback (most recent call last):
  File "/data/users/tmanlaibaatar/pytorch/test/export/test_export.py", line 1936, in test_cond_with_module_stack_export
    gm_unflat_strict = ep_strict.module(flat=False)
  File "/data/users/tmanlaibaatar/pytorch/torch/export/exported_program.py", line 359, in module
    return unflatten(self)
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 117, in unflatten
    module = _UnflattenedModule(module)
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 58, in __init__
    _outline_submodules(export_graph, self)
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 579, in _outline_submodules
    ).run_outer()
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 485, in run_outer
    self.run_from(node_idx)
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 551, in run_from
    ).run_from(node_idx)
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 528, in run_from
    self.finalize_outputs()
  File "/data/users/tmanlaibaatar/pytorch/torch/_export/unflatten.py", line 448, in finalize_outputs
    self.graph.lint()
  File "/data/users/tmanlaibaatar/pytorch/torch/fx/graph.py", line 1427, in lint
    raise RuntimeError(f'Node {node} target {node.target} references nonexistent attribute '
RuntimeError: Node true_graph_0 target true_graph_0 references nonexistent attribute true_graph_0 of
```

### Versions

main

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @angelayi @suo @ydwu4

**Comment by tugsbayasgalan** [comment]
cc: @zhxchen17

**Comment by zhxchen17** [comment]
I can take a look when I have time.

**Comment by ydwu4** [comment]
Closing as the repro no longer fails on master and produce the following graph, which seems reasonable..
```
GraphModule(
  (bar): Module(
    (linear): Module()
  )
  (true_graph_0): <lambda>()
  (false_graph_0): <lambda>()
)



def forward(self, x):
    x, = fx_pytree.tree_flatten_spec(([x], {}), self._in_spec)
    bar_linear_weight = self.bar.linear.weight
    bar_linear_bias = self.bar.linear.bias
    cos = torch.ops.aten.cos.default(x)
    sum_1 = torch.ops.aten.sum.default(x)
    gt = torch.ops.aten.gt.Scalar(sum_1, 0);  sum_1 = None
    true_graph_0 = self.true_graph_0
    false_graph_0 = self.false_graph_0
    cond = torch.ops.higher_order.cond(gt, true_graph_0, false_graph_0, [bar_linear_bias, bar_linear_weight, x]);  gt = true_graph_0 = false_graph_0 = bar_linear_bias = bar_linear_weight = x = None
    getitem = cond[0];  cond = None
    add = torch.ops.aten.add.Tensor(cos, getitem);  cos = getitem = None
    return pytree.tree_unflatten((add,), self._out_spec)
```
