### ISSUE TITLE
Some distributed tests are flaky

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#11582]
test_DistributedDataParallel:
```
15:44:47 MPI not available -- MPI backend tests will be skipped
15:44:47 Running distributed tests for the gloo backend
15:44:47 test_DistributedDataParallel (__main__.TestDistBackend) ... Process process 2:
15:44:47 Traceback (most recent call last):
15:44:47   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
15:44:47     self.run()
15:44:47   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
15:44:47     self._target(*self._args, **self._kwargs)
15:44:47   File "test_distributed.py", line 1268, in _run
15:44:47     rank=self.rank
15:44:47   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/distributed/distributed_c10d.py", line 224, in init_process_group
15:44:47     _default_pg = ProcessGroupGloo(store, rank, world_size)
15:44:47 RuntimeError: Connection reset by peer
15:44:47 FAIL

...


15:44:53 ======================================================================
15:44:53 FAIL: test_DistributedDataParallel (__main__.TestDistBackend)
15:44:53 ----------------------------------------------------------------------
15:44:53 Traceback (most recent call last):
15:44:53   File "test_distributed.py", line 1217, in wrapper
15:44:53     self._join_and_reduce(fn)
15:44:53   File "test_distributed.py", line 1294, in _join_and_reduce
15:44:53     self.assertEqual(p.exitcode, first_process.exitcode)
15:44:53   File "/var/lib/jenkins/workspace/test/common.py", line 390, in assertEqual
15:44:53     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
15:44:53 AssertionError: 74 not less than or equal to 1e-05
15:44:53 
```
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py2.7.9-test/17578/console

test_broadcast_cuda:
```
15:44:01 test_broadcast_cuda (__main__.TestDistBackend) ... Process process 2:
15:44:01 Traceback (most recent call last):
15:44:01   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
15:44:01     self.run()
15:44:01   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
15:44:01     self._target(*self._args, **self._kwargs)
15:44:01   File "test_distributed.py", line 1268, in _run
15:44:01     rank=self.rank
15:44:01   File "/opt/python/3.5/lib/python3.5/site-packages/torch/distributed/distributed_c10d.py", line 224, in init_process_group
15:44:01     _default_pg = ProcessGroupGloo(store, rank, world_size)
15:44:01 RuntimeError: Connection reset by peer
15:44:51 Process process 1:
15:44:51 Traceback (most recent call last):
15:44:51   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
15:44:51     self.run()
15:44:51   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
15:44:51     self._target(*self._args, **self._kwargs)
15:44:51   File "test_distributed.py", line 1268, in _run
15:44:51     rank=self.rank
15:44:51   File "/opt/python/3.5/lib/python3.5/site-packages/torch/distributed/distributed_c10d.py", line 224, in init_process_group
15:44:51     _default_pg = ProcessGroupGloo(store, rank, world_size)
15:44:51 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:834] Connect timeout [172.17.0.2]:55959
15:44:51 FAIL

...


15:44:53 ======================================================================
15:44:53 FAIL: test_broadcast_cuda (__main__.TestDistBackend)
15:44:53 ----------------------------------------------------------------------
15:44:53 Traceback (most recent call last):
15:44:53   File "test_distributed.py", line 1217, in wrapper
15:44:53     self._join_and_reduce(fn)
15:44:53   File "test_distributed.py", line 1294, in _join_and_reduce
15:44:53     self.assertEqual(p.exitcode, first_process.exitcode)
15:44:53   File "/var/lib/jenkins/workspace/test/common.py", line 390, in assertEqual
15:44:53     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
15:44:53 AssertionError: 74 not less than or equal to 1e-05 : 
15:44:53 
```
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.5-test/17631/console

test_broadcast_multigpu:
```
15:44:51 test_broadcast_multigpu (__main__.TestDistBackend) ... Process process 2:
15:44:51 Traceback (most recent call last):
15:44:51   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
15:44:51     self.run()
15:44:51   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
15:44:51     self._target(*self._args, **self._kwargs)
15:44:51   File "test_distributed.py", line 1268, in _run
15:44:51     rank=self.rank
15:44:51   File "/opt/python/3.5/lib/python3.5/site-packages/torch/distributed/distributed_c10d.py", line 224, in init_process_group
15:44:51     _default_pg = ProcessGroupGloo(store, rank, world_size)
15:44:51 RuntimeError: Connection reset by peer
15:44:51 FAIL

...

15:44:53 ======================================================================
15:44:53 FAIL: test_broadcast_multigpu (__main__.TestDistBackend)
15:44:53 ----------------------------------------------------------------------
15:44:53 Traceback (most recent call last):
15:44:53   File "test_distributed.py", line 1217, in wrapper
15:44:53     self._join_and_reduce(fn)
15:44:53   File "test_distributed.py", line 1294, in _join_and_reduce
15:44:53     self.assertEqual(p.exitcode, first_process.exitcode)
15:44:53   File "/var/lib/jenkins/workspace/test/common.py", line 390, in assertEqual
15:44:53     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
15:44:53 AssertionError: 74 not less than or equal to 1e-05 : 
15:44:53 
```
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.5-test/17631/console

test_all_reduce_sum_cuda:
```
17:05:23 ======================================================================
17:05:23 FAIL: test_all_reduce_sum_cuda (__main__.TestDistBackend)
17:05:23 ----------------------------------------------------------------------
17:05:23 Traceback (most recent call last):
17:05:23   File "test_distributed.py", line 1217, in wrapper
17:05:23     self._join_and_reduce(fn)
17:05:23   File "test_distributed.py", line 1294, in _join_and_reduce
17:05:23     self.assertEqual(p.exitcode, first_process.exitcode)
17:05:23   File "/var/lib/jenkins/workspace/test/common.py", line 390, in assertEqual
17:05:23     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
17:05:23 AssertionError: 74 not less than or equal to 1e-05 : 
17:05:23 
17:05:23 ----------------------------------------------------------------------
```
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc5.4-test/17697//console

**Comment by fmassa** [comment]
should we consider reverting (or not including) https://github.com/pytorch/pytorch/pull/11405 for the release?

**Comment by pietern** [comment]
@SsnL Do you have links to the CI output for those? There may be more going on.

@fmassa We should just fix the flakiness of the tests IMO. These have been passing reliably locally and on other CI environments so I think this is something environment specific.

**Comment by SsnL** [comment]
@pietern Thanks for looking into this. Here are the logs:

`test_DistributedDataParallel`
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py2.7.9-test/17578/console

`test_broadcast_cuda` & `test_broadcast_multigpu`
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.5-test/17631/console

**Comment by SsnL** [comment]
@pietern FWIW, the failures I've seen are only on CPU machines. These tests are only recently enabled in https://github.com/pytorch/pytorch/pull/11513

**Comment by pietern** [comment]
Some of these print a difference of 74 between the expected error code and the actual error code. This can be explained by `SKIP_IF_NO_CUDA_EXIT_CODE` equal to 75 and the other processes exiting with code 1. The process group is initialized before the skipped test is called and exits with 75.

I think what's happening is that not all connections are fully setup before the first process runs the test and calls `sys.exit`. If we throw in a barrier after `init_process_group` we should be good to go. Creating a PR.
