### ISSUE TITLE
[inductor][cpu] Some huggingface models cpp wrapper accuracy crash

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115829]
### 🐛 Describe the bug

Some huggingface models accuracy crash, such as CamemBert:
```
loading model: 0it [00:02, ?it/s]cpu  eval  CamemBert                          

ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2391, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 488, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 654, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 730, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2144, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2259, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 945, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/__init__.py", line 1672, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 986, in compile_fx
    return compile_fx(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 427, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 632, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 915, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 305, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1117, in compile_to_fn
    return self.compile_to_module().call
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1071, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1891, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/tmphupxb9or/ls/clsc756bmatylani42e6whkjtsf3fus6mwb5nbxi7yz6ur2agchj.py", line 5001, in <module>
    module = CppWrapperCodeCache.load(cpp_wrapper_src, 'inductor_entry_cpp', 'ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan', False)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1984, in load
    mod = torch.utils.cpp_extension.load_inline(
  File "/workspace/pytorch/torch/utils/cpp_extension.py", line 1635, in load_inline
    return _jit_compile(
  File "/workspace/pytorch/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/workspace/pytorch/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/workspace/pytorch/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Error building extension 'inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan': [1/2] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -I/workspace/pytorch/torch/include -I/workspace/pytorch/torch/include/torch/csrc/api/include -I/workspace/pytorch/torch/include/TH -I/workspace/pytorch/torch/include/THC -I/opt/conda/include/python3.8 -isystem /workspace/pytorch/torch/include -isystem /workspace/pytorch/torch/include/torch/csrc/api/include -isystem /workspace/pytorch/torch/include/TH -isystem /workspace/pytorch/torch/include/THC -isystem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -std=c++17 -Wno-unused-variable -Wno-unknown-pragmas -O3 -DNDEBUG -ffast-math -fno-finite-math-only -fno-unsafe-math-optimizations -march=native -fopenmp -Wall -mavx512f -mavx512dq -mavx512vl -mavx512bw -mfma -DCPU_CAPABILITY_AVX512                     -DTORCH_INDUCTOR_CPP_WRAPPER -D C10_USING_CUSTOM_GENERATED_MACROS -c /tmp/tmphupxb9or/py38_cpu/inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan/main.cpp -o main.o 
FAILED: main.o 
c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -I/workspace/pytorch/torch/include -I/workspace/pytorch/torch/include/torch/csrc/api/include -I/workspace/pytorch/torch/include/TH -I/workspace/pytorch/torch/include/THC -I/opt/conda/include/python3.8 -isystem /workspace/pytorch/torch/include -isystem /workspace/pytorch/torch/include/torch/csrc/api/include -isystem /workspace/pytorch/torch/include/TH -isystem /workspace/pytorch/torch/include/THC -isystem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -std=c++17 -Wno-unused-variable -Wno-unknown-pragmas -O3 -DNDEBUG -ffast-math -fno-finite-math-only -fno-unsafe-math-optimizations -march=native -fopenmp -Wall -mavx512f -mavx512dq -mavx512vl -mavx512bw -mfma -DCPU_CAPABILITY_AVX512                     -DTORCH_INDUCTOR_CPP_WRAPPER -D C10_USING_CUSTOM_GENERATED_MACROS -c /tmp/tmphupxb9or/py38_cpu/inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan/main.cpp -o main.o 
In file included from /tmp/tmphupxb9or/py38_cpu/inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan/main.cpp:76:
/tmp/tmphupxb9or/26/c26eqbkuxvn72gf7p2xujmqjcwf4bo6lxmp6rwborxnf4gldnimh.h: In function â€˜at::vec::CPU_CAPABILITY::Vectorized<float> to_float_mask(int)â€™:
/tmp/tmphupxb9or/26/c26eqbkuxvn72gf7p2xujmqjcwf4bo6lxmp6rwborxnf4gldnimh.h:407:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  407 |   *(uint32_t*)&mask = src ? 0xFFFFFFFF : 0;
      |    ^~~~~~~~~~~~~~~~
/tmp/tmphupxb9or/py38_cpu/inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan/main.cpp: In function â€˜std::vector<at::Tensor> inductor_entry_cpp(const std::vector<at::Tensor>&)â€™:
/tmp/tmphupxb9or/py38_cpu/inline_extension_ccpkzn34tumtqzmopi76jy3yulesqvrfwt3gq6kxtqg26ey64aan/main.cpp:4488:27: error: no matching function for call to â€˜cumsum(at::Tensor&, const std::nullopt_t&, const c10::ScalarType&)â€™
 4488 |     auto buf1 = at::cumsum(buf0, c10::nullopt, at::kLong);
      |                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /workspace/pytorch/torch/include/ATen/Functions.h:585,
                 from /workspace/pytorch/torch/include/ATen/ATen.h:13,
                 from /workspace/pytorch/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /workspace/pytorch/torch/include/torch/csrc/api/include/torch/detail/static.h:4,
                 from /workspace/pytorch/torch/include/torch/csrc/api/include/torch/python.h:3,
                 from /workspace/pytorch/torch/include/torch/extension.h:9:
/workspace/pytorch/torch/include/ATen/ops/cumsum.h:26:19: note: candidate: â€˜at::Tensor at::cumsum(const at::Tensor&, int64_t, std::optional<c10::ScalarType>)â€™
   26 | inline at::Tensor cumsum(const at::Tensor & self, int64_t dim, c10::optional<at::ScalarType> dtype=c10::nullopt) {
      |                   ^~~~~~
/workspace/pytorch/torch/include/ATen/ops/cumsum.h:26:59: note:   no known conversion for argument 2 from â€˜const std::nullopt_tâ€™ to â€˜int64_tâ€™ {aka â€˜long intâ€™}
   26 | inline at::Tensor cumsum(const at::Tensor & self, int64_t dim, c10::optional<at::ScalarType> dtype=c10::nullopt) {
      |                                                   ~~~~~~~~^~~
In file included from /workspace/pytorch/torch/include/ATen/Functions.h:585,
                 from /workspace/pytorch/torch/include/ATen/ATen.h:13,
                 from /workspace/pytorch/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /workspace/pytorch/torch/include/torch/csrc/api/include/torch/detail/static.h:4,
                 from /workspace/pytorch/torch/include/torch/csrc/api/include/torch/python.h:3,
                 from /workspace/pytorch/torch/include/torch/extension.h:9:
/workspace/pytorch/torch/include/ATen/ops/cumsum.h:40:19: note: candidate: â€˜at::Tensor at::cumsum(const at::Tensor&, at::Dimname, std::optional<c10::ScalarType>)â€™
   40 | inline at::Tensor cumsum(const at::Tensor & self, at::Dimname dim, c10::optional<at::ScalarType> dtype=c10::nullopt) {
      |                   ^~~~~~
/workspace/pytorch/torch/include/ATen/ops/cumsum.h:40:63: note:   no known conversion for argument 2 from â€˜const std::nullopt_tâ€™ to â€˜at::Dimnameâ€™
   40 | inline at::Tensor cumsum(const at::Tensor & self, at::Dimname dim, c10::optional<at::ScalarType> dtype=c10::nullopt) {
      |                                                   ~~~~~~~~~~~~^~~
ninja: build stopped: subcommand failed.


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>5da0a5d</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>6518fa9</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>e12d200</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git6fc9d89</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+c1e2095</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.1.1+db62484</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single/multiple inference performance huggingface model float32 first static/dynamic cpp 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/7aac689b199fb3fd557a4c3ddccc5c619eb6e273
[huggingface-CamemBert-inference-float32-static-cpp-accuracy-single-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/13674768/huggingface-CamemBert-inference-float32-static-cpp-accuracy-single-crash_guilty_commit.log)
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @WeizhuoZhang-intel @chuanqi129

**Comment by chunyuan-w** [comment]
@chuanqi129 @zxd1997066 the description mentioned `such as CamemBert`, may I know if there're other models that also have this issue or `CamemBert` is the only one that fails starting from this guilty commit?

**Comment by leslie-fang-intel** [comment]
@zxd1997066 please list out all the regression models.
