### ISSUE TITLE
DISABLED test_ldl_factor_cpu_complex128 (__main__.TestLinalgCPU)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#115953]
Platforms: dynamo

The earliest known bad was on https://hud.pytorch.org/pytorch/pytorch/commit/91f1324b13754ccf155cf4486ce62c8ae1ae0851 which is based on 478f0e96dc2593db401903ac2ae053f8cd1e29ea
```

2023-12-15T16:49:54.1701491Z _________________ TestLinalgCPU.test_ldl_factor_cpu_complex128 _________________
2023-12-15T16:49:54.1701634Z Traceback (most recent call last):
2023-12-15T16:49:54.1701827Z   File "test_linalg.py", line 7638, in test_ldl_factor
2023-12-15T16:49:54.1701961Z     run_test(shape, batch, hermitian)
2023-12-15T16:49:54.1702133Z   File "test_linalg.py", line 7591, in run_test
2023-12-15T16:49:54.1702296Z     self.assertTrue((actual_pivots > 0).all())
2023-12-15T16:49:54.1702552Z   File "test_linalg.py", line 7603, in resume_in_run_test_at_7591
2023-12-15T16:49:54.1702867Z     self.assertEqual(symmetric(A) if not hermitian else A, A_reconstructed)
2023-12-15T16:49:54.1703107Z   File "test_linalg.py", line 7615, in resume_in_run_test_at_7603
2023-12-15T16:49:54.1703254Z     expected = scipy_ldl_batched(A_np)
2023-12-15T16:49:54.1703877Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2163, in __call__
2023-12-15T16:49:54.1704070Z     return self._vectorize_call(func=func, args=vargs)
2023-12-15T16:49:54.1704744Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2237, in _vectorize_call
2023-12-15T16:49:54.1704947Z     res = self._vectorize_call_with_signature(func, args)
2023-12-15T16:49:54.1705701Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2277, in _vectorize_call_with_signature
2023-12-15T16:49:54.1705881Z     results = func(*(arg[index] for arg in args))
2023-12-15T16:49:54.1706047Z   File "test_linalg.py", line 7611, in <lambda>
2023-12-15T16:49:54.1706284Z     lambda x: scipy_ldl(x, hermitian=hermitian, lower=True),
2023-12-15T16:49:54.1706855Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py", line 121, in ldl
2023-12-15T16:49:54.1707106Z     a = atleast_2d(_asarray_validated(A, check_finite=check_finite))
2023-12-15T16:49:54.1707863Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py", line 129, in resume_in_ldl_at_121
2023-12-15T16:49:54.1708039Z     r_or_c = complex if iscomplexobj(a) else float
2023-12-15T16:49:54.1708765Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py", line 129, in resume_in_ldl_at_129
2023-12-15T16:49:54.1708955Z     r_or_c = complex if iscomplexobj(a) else float
2023-12-15T16:49:54.1709643Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py", line 135, in resume_in_ldl_at_134
2023-12-15T16:49:54.1710008Z     warn('scipy.linalg.ldl():\nThe imaginary parts of the diagonal'
2023-12-15T16:49:54.1710719Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py", line 141, in resume_in_ldl_at_135
2023-12-15T16:49:54.1710925Z     solver, solver_lwork = get_lapack_funcs((s, sl), (a,))
2023-12-15T16:49:54.1711561Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 597, in catch_errors
2023-12-15T16:49:54.1711775Z     return callback(frame, cache_entry, hooks, frame_state)
2023-12-15T16:49:54.1712433Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 701, in _convert_frame
2023-12-15T16:49:54.1712693Z     result = inner_convert(frame, cache_entry, hooks, frame_state)
2023-12-15T16:49:54.1713396Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 381, in _convert_frame_assert
2023-12-15T16:49:54.1713513Z     return _compile(
2023-12-15T16:49:54.1714136Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 630, in _compile
2023-12-15T16:49:54.1714395Z     raise InternalTorchDynamoError(str(e)).with_traceback(
2023-12-15T16:49:54.1715024Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 603, in _compile
2023-12-15T16:49:54.1715277Z     guarded_code = compile_inner(code, one_graph, hooks, transform)
2023-12-15T16:49:54.1715873Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
2023-12-15T16:49:54.1715999Z     r = func(*args, **kwargs)
2023-12-15T16:49:54.1716652Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 519, in compile_inner
2023-12-15T16:49:54.1716846Z     out_code = transform_code_object(code, transform)
2023-12-15T16:49:54.1717625Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
2023-12-15T16:49:54.1717802Z     transformations(instructions, code_options)
2023-12-15T16:49:54.1718405Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 150, in _fn
2023-12-15T16:49:54.1718520Z     return fn(*args, **kwargs)
2023-12-15T16:49:54.1719143Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 484, in transform
2023-12-15T16:49:54.1719259Z     tracer.run()
2023-12-15T16:49:54.1719869Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2096, in run
2023-12-15T16:49:54.1719970Z     super().run()
2023-12-15T16:49:54.1720592Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in run
2023-12-15T16:49:54.1720697Z     and self.step()
2023-12-15T16:49:54.1721313Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 744, in step
2023-12-15T16:49:54.1721446Z     getattr(self, inst.opname)(inst)
2023-12-15T16:49:54.1722144Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1476, in UNPACK_SEQUENCE
2023-12-15T16:49:54.1722294Z     if isinstance(seq, TensorVariable):
2023-12-15T16:49:54.1722978Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 133, in __instancecheck__
2023-12-15T16:49:54.1723108Z     instance = instance.realize()
2023-12-15T16:49:54.1723728Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/lazy.py", line 56, in realize
2023-12-15T16:49:54.1723890Z     self._cache.realize(self.parents_tracker)
2023-12-15T16:49:54.1724543Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/lazy.py", line 22, in realize
2023-12-15T16:49:54.1724759Z     self.vt = VariableBuilder(tx, self.source)(self.value)
2023-12-15T16:49:54.1725436Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 245, in __call__
2023-12-15T16:49:54.1725592Z     vt = self._wrap(value)
2023-12-15T16:49:54.1726217Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 387, in _wrap
2023-12-15T16:49:54.1726350Z     return type_dispatch(self, value)
2023-12-15T16:49:54.1727044Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 842, in wrap_listlike
2023-12-15T16:49:54.1727143Z     output = [
2023-12-15T16:49:54.1727805Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 843, in <listcomp>
2023-12-15T16:49:54.1728110Z     VariableBuilder(self.tx, GetItemSource(self.get_source(), i))(item)
2023-12-15T16:49:54.1728757Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 245, in __call__
2023-12-15T16:49:54.1728884Z     vt = self._wrap(value)
2023-12-15T16:49:54.1729514Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 396, in _wrap
2023-12-15T16:49:54.1729828Z     value = inspect.getattr_static(value, "_torchdynamo_inline", value)
2023-12-15T16:49:54.1730214Z   File "/opt/conda/envs/py_3.8/lib/python3.8/inspect.py", line 1593, in getattr_static
2023-12-15T16:49:54.1730345Z     dict_attr = _shadowed_dict(klass)
2023-12-15T16:49:54.1730712Z   File "/opt/conda/envs/py_3.8/lib/python3.8/inspect.py", line 1567, in _shadowed_dict
2023-12-15T16:49:54.1730857Z     for entry in _static_getmro(klass):
2023-12-15T16:49:54.1731280Z torch._dynamo.exc.InternalTorchDynamoError: 'NoneType' object is not iterable
2023-12-15T16:49:54.1731286Z 
2023-12-15T16:49:54.1731401Z from user code:
2023-12-15T16:49:54.1732092Z    File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py", line 141, in resume_in_ldl_at_141
2023-12-15T16:49:54.1732296Z     solver, solver_lwork = get_lapack_funcs((s, sl), (a,))
2023-12-15T16:49:54.1732302Z 
2023-12-15T16:49:54.1732607Z Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
2023-12-15T16:49:54.1732617Z 
2023-12-15T16:49:54.1732621Z 
2023-12-15T16:49:54.1732898Z You can suppress this exception and fall back to eager by setting:
2023-12-15T16:49:54.1733021Z     import torch._dynamo
2023-12-15T16:49:54.1733196Z     torch._dynamo.config.suppress_errors = True
2023-12-15T16:49:54.1733202Z 
2023-12-15T16:49:54.1733207Z 
2023-12-15T16:49:54.1733457Z To execute this test, run the following from the base repo dir:
2023-12-15T16:49:54.1733892Z     PYTORCH_TEST_WITH_DYNAMO=1 python test_linalg.py -k test_ldl_factor_cpu_complex128
2023-12-15T16:49:54.1733897Z 
2023-12-15T16:49:54.1734220Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2023-12-15T16:49:54.1734627Z ----------------------------- Captured stderr call -----------------------------
2023-12-15T16:49:54.1735342Z /opt/conda/envs/py_3.8/lib/python3.8/site-packages/scipy/linalg/_decomp_ldl.py:129: ComplexWarning: scipy.linalg.ldl():
2023-12-15T16:49:54.1735888Z The imaginary parts of the diagonalare ignored. Use "hermitian=False" for factorization ofcomplex symmetric arrays.
2023-12-15T16:49:54.1736077Z   r_or_c = complex if iscomplexobj(a) else float
```

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/test_linalg.py%3A%3ATestLinalgCPU%3A%3Atest_ldl_factor_cpu_complex128)).

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zou3519** [comment]
We already skip this in the code, so there's no need for this disabled test issue anymore.
