### ISSUE TITLE
MacOS x86 flaky failures on periodic job, macos-12-py3-x86-64

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#115959]
## Current Status
mitigated

## Error looks like
```
2023-12-15T18:35:50.0530250Z ##[warning]Attempt 4 failed. Reason: Child_process exited with error code 1
2023-12-15T18:35:50.0583200Z + python3 -m pip install requests==2.26.0 pyyaml==6.0
2023-12-15T18:35:50.6356370Z Collecting requests==2.26.0
2023-12-15T18:35:50.6424470Z   Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
2023-12-15T18:35:50.6923760Z Collecting pyyaml==6.0
2023-12-15T18:35:50.6951890Z   Using cached PyYAML-6.0.tar.gz (124 kB)
2023-12-15T18:35:50.9087800Z   Installing build dependencies: started
2023-12-15T18:35:54.0693500Z   Installing build dependencies: finished with status 'done'
2023-12-15T18:35:54.0711090Z   Getting requirements to build wheel: started
2023-12-15T18:35:54.4535010Z   Getting requirements to build wheel: finished with status 'error'
2023-12-15T18:35:54.4710390Z   error: subprocess-exited-with-error
2023-12-15T18:35:54.4711280Z   
2023-12-15T18:35:54.4712650Z   × Getting requirements to build wheel did not run successfully.
2023-12-15T18:35:54.4713940Z   │ exit code: 1
2023-12-15T18:35:54.4714710Z   ╰─> [54 lines of output]
2023-12-15T18:35:54.4715530Z       running egg_info
2023-12-15T18:35:54.4716540Z       writing lib/PyYAML.egg-info/PKG-INFO
2023-12-15T18:35:54.4718180Z       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
2023-12-15T18:35:54.4720120Z       writing top-level names to lib/PyYAML.egg-info/top_level.txt
2023-12-15T18:35:54.4721500Z       Traceback (most recent call last):
2023-12-15T18:35:54.4724640Z         File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2023-12-15T18:35:54.4727390Z           main()
2023-12-15T18:35:54.4730140Z         File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2023-12-15T18:35:54.4734450Z           json_out['return_val'] = hook(**hook_input['kwargs'])
2023-12-15T18:35:54.4735640Z                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T18:35:54.4738530Z         File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
2023-12-15T18:35:54.4741150Z           return hook(config_settings)
2023-12-15T18:35:54.4741900Z                  ^^^^^^^^^^^^^^^^^^^^^
2023-12-15T18:35:54.4744950Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
2023-12-15T18:35:54.4748850Z           return self._get_build_requires(config_settings, requirements=['wheel'])
2023-12-15T18:35:54.4750040Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T18:35:54.4753470Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
2023-12-15T18:35:54.4756130Z           self.run_setup()
2023-12-15T18:35:54.4758700Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
2023-12-15T18:35:54.4761140Z           exec(code, locals())
2023-12-15T18:35:54.4761970Z         File "<string>", line 288, in <module>
2023-12-15T18:35:54.4764460Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
2023-12-15T18:35:54.4766820Z           return distutils.core.setup(**attrs)
2023-12-15T18:35:54.4767650Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T18:35:54.4770480Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
2023-12-15T18:35:54.4772950Z           return run_commands(dist)
2023-12-15T18:35:54.4773680Z                  ^^^^^^^^^^^^^^^^^^
2023-12-15T18:35:54.4776510Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
2023-12-15T18:35:54.4779070Z           dist.run_commands()
2023-12-15T18:35:54.4782080Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
2023-12-15T18:35:54.4783920Z           self.run_command(cmd)
2023-12-15T18:35:54.4785710Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
2023-12-15T18:35:54.4787390Z           super().run_command(command)
2023-12-15T18:35:54.4789260Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-12-15T18:35:54.4791040Z           cmd_obj.run()
2023-12-15T18:35:54.4792720Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
2023-12-15T18:35:54.4794400Z           self.find_sources()
2023-12-15T18:35:54.4796200Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
2023-12-15T18:35:54.4797950Z           mm.run()
2023-12-15T18:35:54.4800140Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 551, in run
2023-12-15T18:35:54.4801830Z           self.add_defaults()
2023-12-15T18:35:54.4803650Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
2023-12-15T18:35:54.4805400Z           sdist.add_defaults(self)
2023-12-15T18:35:54.4807220Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
2023-12-15T18:35:54.4809050Z           super().add_defaults()
2023-12-15T18:35:54.4811240Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
2023-12-15T18:35:54.4813060Z           self._add_defaults_ext()
2023-12-15T18:35:54.4815960Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
2023-12-15T18:35:54.4819500Z           self.filelist.extend(build_ext.get_source_files())
2023-12-15T18:35:54.4820170Z                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T18:35:54.4820770Z         File "<string>", line 204, in get_source_files
2023-12-15T18:35:54.4822840Z         File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pip-build-env-fn3vj1ze/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
2023-12-15T18:35:54.4824750Z           raise AttributeError(attr)
2023-12-15T18:35:54.4825280Z       AttributeError: cython_sources
2023-12-15T18:35:54.4825780Z       [end of output]
2023-12-15T18:35:54.4826140Z   
2023-12-15T18:35:54.4826910Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2023-12-15T18:35:54.4828600Z error: subprocess-exited-with-error
2023-12-15T18:35:54.4829140Z 
2023-12-15T18:35:54.4829750Z × Getting requirements to build wheel did not run successfully.
2023-12-15T18:35:54.4830820Z │ exit code: 1
2023-12-15T18:35:54.4831430Z ╰─> See above for output.
2023-12-15T18:35:54.4831860Z 
2023-12-15T18:35:54.4832580Z note: This error originates from a subprocess, and is likely not a problem with pip.
2023-12-15T18:36:25.0688740Z ##[error]Final attempt failed. Child_process exited with error code 1
```

## Incident timeline (all times pacific)
Tue Dec 12 5:02AM

## User impact
Periodic job `` periodic / macos-12-py3-x86-64 / build`` is failing 1 or more times a day

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
Closing, as fixed by https://github.com/pytorch/pytorch/pull/115956

**Comment by malfet** [comment]
And just curious: what are our SEV criterias?
