### ISSUE TITLE
dynamo does not work with varied devices across parameters in optimizer

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#116057]
### 🐛 Describe the bug

Parameters are allowed to be on different devices when input into optimizers. The optimizer will group parameters accordingly and do the update.

This does not work with dynamo for every foreach optimizer except SGD.

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (0407c8f1|REBASE-i|detached HEAD)]$ python playground2.py 
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/playground2.py", line 22, in <module>
    compiled_loop()
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 434, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/playground2.py", line 19, in loop
    optimizer.step()
  File "/data/users/janeyx/pytorch/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 597, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 736, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 381, in _convert_frame_assert
    return _compile(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 638, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 519, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 150, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 484, in transform
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2096, in run
    super().run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 463, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 1215, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 645, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 252, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 651, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2231, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2346, in inline_call_
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 463, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 1227, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 645, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 252, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 651, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2231, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2346, in inline_call_
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 463, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 1176, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 645, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/torch.py", line 554, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builder.py", line 1325, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builder.py", line 1410, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 1545, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 1506, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 1047, in wrap_fake_exception
    return fn()
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 1507, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 1612, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 1591, in run_node
    return node.target(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_subclasses/fake_tensor.py", line 1392, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_subclasses/fake_tensor.py", line 1712, in dispatch
    return self.wrap_meta_outputs_with_default_device_logic(
  File "/data/users/janeyx/pytorch/torch/_subclasses/fake_tensor.py", line 1815, in wrap_meta_outputs_with_default_device_logic
    return tree_map(wrap, r)
  File "/data/users/janeyx/pytorch/torch/utils/_pytree.py", line 732, in tree_map
    return treespec.unflatten(map(func, *flat_args))
  File "/data/users/janeyx/pytorch/torch/utils/_pytree.py", line 599, in unflatten
    leaves = list(leaves)
  File "/data/users/janeyx/pytorch/torch/_subclasses/fake_tensor.py", line 1790, in wrap
    ) = FakeTensor._find_common_device(func, flat_args)
  File "/data/users/janeyx/pytorch/torch/_subclasses/fake_tensor.py", line 1271, in _find_common_device
    merge_devices(arg)
  File "/data/users/janeyx/pytorch/torch/_subclasses/fake_tensor.py", line 1266, in merge_devices
    raise RuntimeError(
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method _foreach_pow of type object at 0x7fb86a3b84a0>(*(0.9, [FakeTensor(..., device='cuda:0', size=()), FakeTensor(..., device='cuda:0', size=()), FakeTensor(..., device='cuda:0', size=()), FakeTensor(..., device='cuda:0', size=()), FakeTensor(..., device='cuda:1', size=()), FakeTensor(..., device='cuda:1', size=()), FakeTensor(..., device='cuda:1', size=()), FakeTensor(..., device='cuda:1', size=())]), **{}):
Unhandled FakeTensor Device Propagation for aten._foreach_pow.ScalarAndTensor, found two different devices cuda:0, cuda:1

from user code:
   File "/data/users/janeyx/pytorch/torch/optim/adamw.py", line 187, in step
    adamw(
  File "/data/users/janeyx/pytorch/torch/optim/adamw.py", line 339, in adamw
    func(
  File "/data/users/janeyx/pytorch/torch/optim/adamw.py", line 558, in _multi_tensor_adamw
    bias_correction1 = torch._foreach_pow(beta1, device_state_steps)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

```
import torch

params = [
    torch.rand(2, 3, dtype=torch.float64, device='cuda:0', requires_grad=True),
    torch.rand(2, 3, dtype=torch.float32, device='cuda:0', requires_grad=True),
    torch.rand(2, 3, dtype=torch.float16, device='cuda:0', requires_grad=True),
    torch.rand(2, 3, dtype=torch.bfloat16, device='cuda:0', requires_grad=True),
    torch.rand(2, 3, dtype=torch.float64, device='cuda:1', requires_grad=True),
    torch.rand(2, 3, dtype=torch.float32, device='cuda:1', requires_grad=True),
    torch.rand(2, 3, dtype=torch.float16, device='cuda:1', requires_grad=True),
    torch.rand(2, 3, dtype=torch.bfloat16, device='cuda:1', requires_grad=True),
]

optimizer = torch.optim.AdamW(params)
for p in params:
    p.grad = torch.rand_like(p)

def loop():
    optimizer.step()

compiled_loop = torch._dynamo.optimize("eager")(loop)
compiled_loop()
```

### Versions

on main

cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by janeyx99** [comment]
Fixing this should enable the `test_foreach_mixed_device_dtype` test getting added in https://github.com/pytorch/pytorch/pull/115025/files

**Comment by mlazos** [comment]
closing as a dup of https://github.com/pytorch/pytorch/issues/102023
