### ISSUE TITLE
dynamo'ing SGD w/ momentum errors for CPU params with empty grads

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#116061]
### 🐛 Describe the bug

cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @mlazos 

When attempting to compile SGD with momentum on a param on CPU with empty grad, we run into a list index out of range internal dynamo error. This may also be fixed once `_init_group` tracing lands.

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (b26bf643|REBASE-i|detached HEAD)]$ python playground2.py 
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/playground2.py", line 15, in <module>
    compiled_loop()
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 434, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/playground2.py", line 12, in loop
    optimizer.step()
  File "/data/users/janeyx/pytorch/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 597, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 736, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 381, in _convert_frame_assert
    return _compile(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 665, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 638, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 519, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 150, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 484, in transform
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2096, in run
    super().run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 463, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 1227, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 645, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 252, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 651, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2231, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2346, in inline_call_
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 463, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 1227, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 645, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 252, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 651, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2231, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2346, in inline_call_
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 463, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 242, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builtin.py", line 648, in call_function
    result = handler(tx, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builtin.py", line 996, in call_getitem
    return args[0].call_method(tx, "__getitem__", args[1:], kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/lists.py", line 328, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/lists.py", line 291, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/lists.py", line 124, in call_method
    return self.getitem_const(value)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/lists.py", line 100, in getitem_const
    return self.items[index]
torch._dynamo.exc.InternalTorchDynamoError: list index out of range

from user code:
   File "/data/users/janeyx/pytorch/torch/optim/sgd.py", line 75, in step
    sgd(params_with_grad,
  File "/data/users/janeyx/pytorch/torch/optim/sgd.py", line 220, in sgd
    func(params,
  File "/data/users/janeyx/pytorch/torch/optim/sgd.py", line 250, in _single_tensor_sgd
    buf = momentum_buffer_list[i]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

```
import torch

params = [
    torch.rand(2, 3, dtype=torch.float64, device='cpu', requires_grad=True),
]

optimizer = torch.optim.SGD(params, lr=0.02, momentum=0.9)
for p in params:
    p.grad = torch.empty_like(p)

def loop():
    optimizer.step()

compiled_loop = torch._dynamo.optimize("eager")(loop)
compiled_loop()
```

### Versions

on main

**Comment by mlazos** [comment]
Closing as this no longer repros
