### ISSUE TITLE
torch.distributed.DistNetworkError: Unknown error on Windows using gloo on torch dev when training on multigpu.

### ISSUE THREAD

**Issue by Panchovix** [pytorch/pytorch#116056]
### 🐛 Describe the bug

Hi there, nice work as always! I'm trying to train a LoRA (low rank adapter) for Stable Diffusion architecture, using https://github.com/kohya-ss/sd-scripts/tree/main

Command ran on kohya was:

```
accelerate launch --multi_gpu --num_cpu_threads_per_process 16 train_network.py `
    --cache_latents `
    --enable_bucket `
    --bucket_no_upscale `
    --max_data_loader_n_workers=1 `
    --persistent_data_loader_workers `
    --shuffle_caption `
    --pretrained_model_name_or_path=$ckpt `
    --train_data_dir=$image_dir `
    --reg_data_dir=$reg_dir `
    --resolution=768,768 `
    --optimizer_type="AdamW" `
    --optimizer_args "weight_decay=0.01" "betas=0.9,0.999" `
    --output_dir=$output `
    --train_batch_size=$train_batch_size `
    --lr_scheduler=$scheduler `
    --lr_warmup_steps=$lr_warmup_steps `
    --max_train_steps=$mts `
    --flip_aug `
    --xformers `
    --mixed_precision=bf16 `
    --save_every_n_epochs=$save_every_n_epochs `
    --seed=1234 `
    --save_precision=bf16 `
    --logging_dir="" `
    --caption_extension=.txt `
    --save_model_as=safetensors `
    --network_module=lycoris.kohya `
    --text_encoder_lr=$text_encoder_lr `
    --unet_lr=$unet_lr `
    --clip_skip=2 `
```

I'm trying to use multigpu training with gloo (since nccl doesn't work on Windows), but when using torch 2.2/2.3 (dev), I get this issue.

```
Measuring folders:
        test: 5 repeats * 397 images = 1985
Total images with repeats: 1985
Max training steps 1985 / 4 * 10 = 4962
[2023-12-18 16:46:15,504] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[W socket.cpp:697] [c10d] The client socket has failed to connect to [ic.adobe.io]:29500 (system error: 10049 - La direcci≤n solicitada no es vßlida en este contexto.).
Traceback (most recent call last):
  File "C:\Users\Pancho\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pancho\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\acc\sd-scripts-cu118\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\accelerate\commands\launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\accelerate\commands\launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\run.py", line 803, in run
    elastic_launch(
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\launcher\api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    result = agent.run()
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 727, in run
    result = self._invoke_run(role)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 862, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 699, in _initialize_workers
    self._rendezvous(worker_group)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 542, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "G:\acc\sd-scripts-cu118\venv\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
torch.distributed.DistNetworkError: Unknown error
```

Accelerate was properly configured to just use 1 system (so no distributed training) with `accelerate config`

This issue happens with either torch with cuda 11.8 or cuda 12.1 (+cu118/+cu121)

Torch 2.1.x doesn't have this issue.

### Versions

I'm trying to run the command on Windows, but I get `C:\Users\Pancho\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'G:\\acc\\sd-scripts-cu118\\collect_env.py': [Errno 2] No such file or directory`

Running pip list, it shows this

```
Package                   Version                  Editable project location
------------------------- ------------------------ -------------------------
absl-py                   2.0.0
accelerate                0.23.0
aiohttp                   3.8.6
aiosignal                 1.3.1
altair                    4.2.2
async-timeout             4.0.3
attrs                     23.1.0
bitsandbytes              0.41.2.post2
cachetools                5.3.1
certifi                   2022.12.7
charset-normalizer        2.1.1
colorama                  0.4.6
diffusers                 0.21.2
easygui                   0.98.3
einops                    0.6.0
entrypoints               0.4
filelock                  3.9.0
frozenlist                1.4.0
fsspec                    2023.4.0
ftfy                      6.1.1
google-auth               2.23.3
google-auth-oauthlib      0.4.6
grpcio                    1.59.0
huggingface-hub           0.15.1
idna                      3.4
importlib-metadata        6.8.0
Jinja2                    3.1.2
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
library                   0.0.0                    G:\acc\sd-scripts-cu118
lightning-utilities       0.9.0
lycoris-lora              2.0.2
Markdown                  3.5
MarkupSafe                2.1.2
mpmath                    1.2.1
multidict                 6.0.4
networkx                  2.6.3
numpy                     1.24.1
oauthlib                  3.2.2
open-clip-torch           2.20.0
opencv-python             4.7.0.68
packaging                 23.2
pandas                    2.1.1
Pillow                    9.3.0
pip                       23.3
prodigyopt                1.0
protobuf                  3.19.6
psutil                    5.9.6
pyasn1                    0.5.0
pyasn1-modules            0.3.0
python-dateutil           2.8.2
pytorch-lightning         1.9.0
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.30.2
regex                     2023.10.3
requests                  2.28.1
requests-oauthlib         1.3.1
rpds-py                   0.10.6
rsa                       4.9
safetensors               0.3.1
scipy                     1.11.4
sentencepiece             0.1.99
setuptools                65.5.0
six                       1.16.0
sympy                     1.11.1
tensorboard               2.10.1
tensorboard-data-server   0.6.1
tensorboard-plugin-wit    1.8.1
timm                      0.9.7
tokenizers                0.13.3
toml                      0.10.2
toolz                     0.12.0
torch                     2.3.0.dev20231216+cu118
torchmetrics              1.2.0
torchvision               0.18.0.dev20231216+cu118
tqdm                      4.66.1
transformers              4.30.2
typing_extensions         4.8.0
tzdata                    2023.3
urllib3                   1.26.13
voluptuous                0.13.1
wcwidth                   0.2.8
Werkzeug                  3.0.0
wheel                     0.41.2
xformers                  0.0.24+042abc8.d20231217
yarl                      1.9.2
zipp                      3.17.0
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by Panchovix** [comment]
Closing it as torch 2.2.1 fixed it.
