### ISSUE TITLE
[inductor][cpu] RuntimeError: quantized_resize_cpu_ does not have a deterministic implementation

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#116240]
### 🐛 Describe the bug

some modes meet accuracy crash in 2023-12-17

```
cpu  eval  mobilenet_v2_quantized_qat         
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1940, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "benchmarks/dynamo/torchbench.py", line 532, in forward_pass
    return mod(*inputs)
  File "/workspace/pytorch/torch/fx/graph_module.py", line 738, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/workspace/pytorch/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/workspace/pytorch/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.6", line 128, in forward
    classifier_1 = getattr(self.classifier, "1")(classifier_0);  classifier_0 = None
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/ao/nn/quantized/modules/linear.py", line 168, in forward
    return torch.ops.quantized.linear(
  File "/workspace/pytorch/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: quantized_resize_cpu_ does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>a2940cd</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>6518fa9</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>e12d200</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info(nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.3.0a0+git5da0a5d</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+e12d200</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+6518fa9</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh multiple inference accuracy torchbench mobilenet_v2_quantized_qat float32 first static default

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/f71d931b32826cee2143f80a84135921696aa9f0

[torchbench-mobilenet_v2_quantized_qat-inference-float32-static-cpp-accuracy-multiple-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/13734640/torchbench-mobilenet_v2_quantized_qat-inference-float32-static-cpp-accuracy-multiple-crash_guilty_commit.log)
cc @WeizhuoZhang-intel @chuanqi129

**Comment by jgong5** [comment]
This is an expected error according to the current implementation of `quantized_resize_cpu_`. But we can perhaps make sure the new elements are initialized when the tensor is resized.
@Xia-Weiwen can you take a look?

**Comment by Xia-Weiwen** [comment]
Ok. I will take a look later.
