### ISSUE TITLE
ImportError: No module named 'google'

### ISSUE THREAD

**Issue by nicksterlingtek** [pytorch/pytorch#11632]
Hello. I think that I am getting closer to a successful install. After pulling the latest repo, I get the following message while trying to load up caffe2... `ImportError: No module named 'google'`. If anyone has ideas, I would sincerely appreciate any help. Thank you, in advance.

**Building from source...**
```
$ git clone --recursive https://github.com/pytorch/pytorch
$ conda create -n some_env python=3
$ conda activate some_env
(some_env) nick@host:~$ export CMAKE_PREFIX_PATH=/home/nick/anaconda3/envs/some_env/
(some_env) nick@host:~$ conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
(some_env) nick@host:~$ conda install -c mingfeima mkldnn
(some_env) nick@host:~$ conda install -c pytorch magma-cuda92
(some_env) nick@host:~$ cd pytorch/
(some_env) nick@host:~/pytorch$ git submodule update --init --recursive
(some_env) nick@host:~/pytorch$ NO_TEST=1 FULL_CAFFE2=1 python setup.py install
...
Copying torch.egg-info to /home/nick/anaconda3/envs/some_env/lib/python3.5/site-packages/torch-0.5.0a0+f0a2845-py3.5.egg-info
running install_scripts
Installing convert-onnx-to-caffe2 script to /home/nick/anaconda3/envs/some_env/bin
Installing convert-caffe2-to-onnx script to /home/nick/anaconda3/envs/some_env/bin
```

**Running python...**
```
(some_env) nick@host:~/pytorch$ cd ..
(some_env) nick@host:~$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nick/anaconda3/envs/some_env/lib/python3.5/site-packages/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "/home/nick/anaconda3/envs/some_env/lib/python3.5/site-packages/caffe2/proto/caffe2_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named 'google'
>>> ```

**Comment by nicksterlingtek** [comment]
Solved the problem. Had to do the following after I built...
```
conda install protobuf
conda install future
```
