### ISSUE TITLE
DataLoader: Could not wrapper a exception in threads

### ISSUE THREAD

**Issue by mapler** [pytorch/pytorch#11633]
## Issue description

It seems that the code in dataloader.py try to wrap exceptions in threads and re-raise it with traceback info witch formatted to string. 
https://github.com/pytorch/pytorch/blob/v0.4.0/torch/utils/data/dataloader.py#L22
https://github.com/pytorch/pytorch/blob/v0.4.0/torch/utils/data/dataloader.py#L303
(I paste links in v0.4.0 same to my environment, but it's not changed in master branch)

It did not work in some custom exception which not have a "good" `__init__` method. 
I have tried to fix it but failed. it is impossible to just re-raise a exception (`exc_type` in code) without knowing the detail of `__int__` method.

## Code example
```
class CustomException(BaseException):
    def __init__(self, **kwargs):
        pass

class SomeDataset(torch.utils.data.Dataset):
     def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        raise CustomException('test')

    def __len__(self):
        return len(self.data)

train_dataset = SomeDatset(train_data)
train_dataloder = torch.utils.data.DataLoader(train_dataset)

for data in train_loader:
    pass
```

Error Message:
```
Traceback (most recent call last):
  File "train.py", line 221, in <module>
    for data in train_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: __init__() takes 1 positional argument but 2 were given
```

## System Info
```
# python collect_env.py
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/lib/python3.6/dist-packages/cntk/libs/libcudnn.so.7

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by Xyand** [comment]
Another scenario is when the exception `__init__` requires more than one positional argument. Even if the first argument is a standard string/msg.

This also happens in v1.1+

**Comment by izdeby** [comment]
@SsnL, can you please take a look?
