### ISSUE TITLE
test_bc_for_state_dict_NAdam_cuda_float32 errors with PYTORCH_TEST_WITH_DYNAMO

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#116499]
### 🐛 Describe the bug

Out of all the optimizers run on this test, only NAdam errors with dynamo.

cc @mlazos 

### Error logs

```
======================================================================
ERROR: test_bc_for_state_dict_NAdam_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 429, in instantiated_test
    raise rte
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 178, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 456, in test_bc_for_state_dict
    all_optim_inputs = _get_optim_inputs_including_global_cliquey_kwargs(device, dtype, optim_info, skip=("differentiable",))
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 487, in resume_in_test_bc_for_state_dict_at_456
    optimizer.step()
  File "/data/users/janeyx/pytorch/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/optim/nadam.py", line 111, in step
    nadam(params_with_grad,
  File "/data/users/janeyx/pytorch/torch/optim/nadam.py", line 191, in nadam
    def nadam(params: List[Tensor],
  File "/data/users/janeyx/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/fx/graph_module.py", line 315, in __call__
    raise e.with_traceback(None)  # noqa: TRY200
RuntimeError: Expected scalars to be on CPU, got cuda:0 instead.

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_bc_for_state_dict_NAdam_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

### Minified repro

`PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_bc_for_state_dict_NAdam_cuda_float32` with my PR.

### Versions

on main

**Comment by janeyx99** [comment]
Ah, this will be fixed when `_process_value_according_to_param_policy` correctly handles ALL scalars, not just step. 
https://github.com/pytorch/pytorch/blob/main/torch/optim/optimizer.py#L638

**Comment by masnesral** [comment]
@janeyx99 I'm helping with old issue scrubbing. Looks like this might be fixed? (I _think_ it passes for me locally):

`PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_can_load_older_state_dict_NAdam_cuda_float32`
