### ISSUE TITLE
We don't have an op for aten::view but it isn't a special case.

### ISSUE THREAD

**Issue by Alaskra** [pytorch/pytorch#116443]
### 🐛 Describe the bug

The python file is:
```python
import torch
from torch import nn
class Foo(nn.Module):
    def forward(self, x, y):
        ori_dtype = y.dtype
        x = x.view(torch.int32)
        y = y.view(torch.int32)
        rst = (~x | y)
        rst = rst.view(ori_dtype)
        return rst

model = Foo()
data_in = (torch.randn(10), torch.randn(10))
torch.onnx.export(model, data_in, 'tmp.onnx')
```
After run it, the following error happen:
```
(py310) C:\Users\alaskra\torchfx-obfuscation>python tmp.py
Traceback (most recent call last):
  File "C:\Users\alaskra\torchfx-obfuscation\tmp.py", line 28, in <module>
    torch.onnx.export(model, data_in, 'tmp.onnx')
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\onnx\utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\onnx\utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\onnx\utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\onnx\utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\jit\_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\alaskra\miniconda3\envs\py310\lib\site-packages\torch\jit\_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
RuntimeError: 0 INTERNAL ASSERT FAILED at "C:\\cb\\pytorch_1000000000000\\work\\torch\\csrc\\jit\\ir\\alias_analysis.cpp":622, please report a bug to PyTorch. We don't have an op for aten::view but it isn't a special case.  Argument types: Tensor, int,

Candidates:
        aten::view(Tensor(a) self, SymInt[] size) -> Tensor(a)
        aten::view.dtype(Tensor(a) self, ScalarType dtype) -> Tensor(a)
```

### Versions

Collecting environment information...
PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti
Nvidia driver version: 546.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2201
DeviceID=CPU0
Family=198
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2201
Name=Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] onnx==1.13.1
[pip3] onnxoptimizer==0.3.13
[pip3] torch==2.1.1
[pip3] torchaudio==2.1.1
[pip3] torchstat==0.0.7
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.16.1
[pip3] vit-pytorch==1.6.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h6b88ed4_46358
[conda] mkl-service               2.4.0           py310h2bbff1b_1
[conda] mkl_fft                   1.3.8           py310h2bbff1b_0
[conda] mkl_random                1.2.4           py310h59b6b97_0
[conda] numpy                     1.26.0          py310h055cbcc_0
[conda] numpy-base                1.26.0          py310h65a83cf_0
[conda] pytorch                   2.1.1           py3.10_cuda12.1_cudnn8_0    pytorch
[conda] pytorch-cuda              12.1                 hde6ce7c_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.1                    pypi_0    pypi
[conda] torchstat                 0.0.7                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.16.1                   pypi_0    pypi
[conda] vit-pytorch               1.6.4                    pypi_0    pypi

**Comment by thiagocrepaldi** [comment]
Have you tried using `torch.onnx.dynamo_export` instead?

**Comment by thiagocrepaldi** [comment]
Although the new ONNX exporter does not work on Windows (dut to PyTorch Dynamo's limitation), on linux the model is exported. here it is what it looks like

<img width="239" alt="image" src="https://github.com/pytorch/pytorch/assets/5469809/a5e8f00e-cc98-4323-a565-a1de5efb76d6">

**Comment by thiagocrepaldi** [comment]
For the original model, it still fails, but for a different reason:

```python
import torch
from torch import nn
class Foo(nn.Module):
    def forward(self, x, y):
        ori_dtype = y.dtype
        x = x.view(torch.int32)
        y = y.view(torch.int32)
        rst = (~x | y)
        rst = rst.view(ori_dtype)
        return rst

model = Foo()
data_in = (torch.randn(10), torch.randn(10))
torch.onnx.dynamo_export(model, data_in, 'tmp.onnx')
```
which errors with

```bash
/opt/conda/envs/ptca/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
[2024-01-09 16:49:03,165] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/opt/conda/envs/ptca/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/conda/envs/ptca/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/pytorch/torch/onnx/_internal/exporter.py:137: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(
[2024-01-09 16:49:04,954] torch._dynamo.eval_frame: [DEBUG] skipping: helper (reason: in skipfiles, file: /opt/conda/envs/ptca/lib/python3.11/contextlib.py)
[2024-01-09 16:49:04,954] torch._dynamo.eval_frame: [DEBUG] skipping: __init__ (reason: in skipfiles, file: /opt/conda/envs/ptca/lib/python3.11/contextlib.py)
[2024-01-09 16:49:04,955] torch._dynamo.eval_frame: [DEBUG] skipping: backend_cache_wrapper (reason: in skipfiles, file: /opt/pytorch/torch/_dynamo/eval_frame.py)
[2024-01-09 16:49:04,955] torch._dynamo.eval_frame: [DEBUG] skipping: __enter__ (reason: in skipfiles, file: /opt/conda/envs/ptca/lib/python3.11/contextlib.py)
[2024-01-09 16:49:04,955] torch._dynamo.eval_frame: [DEBUG] skipping: _maybe_init_guarded_backend_cache (reason: in skipfiles, file: /opt/pytorch/torch/_dynamo/eval_frame.py)
[2024-01-09 16:49:04,955] torch._dynamo.eval_frame: [DEBUG] skipping: innermost_fn (reason: in skipfiles, file: /opt/pytorch/torch/_dynamo/eval_frame.py)
[2024-01-09 16:49:04,956] torch._dynamo.eval_frame: [DEBUG] skipping: _set_current_backend (reason: in skipfiles, file: /opt/pytorch/torch/_dynamo/eval_frame.py)
[2024-01-09 16:49:04,956] torch._dynamo.eval_frame: [DEBUG] skipping: __init__ (reason: in skipfiles, file: /opt/conda/envs/ptca/lib/python3.11/contextlib.py)
[2024-01-09 16:49:04,956] torch._dynamo.eval_frame: [DEBUG] skipping: __enter__ (reason: in skipfiles, file: /opt/conda/envs/ptca/lib/python3.11/contextlib.py)
[2024-01-09 16:49:04,956] torch._dynamo.eval_frame: [DEBUG] skipping: enable_dynamic (reason: in skipfiles, file: /opt/pytorch/torch/_dynamo/eval_frame.py)
[2024-01-09 16:49:04,956] torch._dynamo.eval_frame: [DEBUG] skipping: wrapped (reason: in skipfiles, file: /opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py)
[2024-01-09 16:49:05,223] [0/0] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing forward /opt/pytorch/test_gh116443.py:4
[2024-01-09 16:49:05,224] [0/0] torch.fx.experimental.symbolic_shapes: [INFO] create_env
[2024-01-09 16:49:05,228] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /opt/pytorch/test_gh116443.py:4 in forward (Foo.forward)
[2024-01-09 16:49:05,228] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]         def forward(self, x, y):
[2024-01-09 16:49:05,232] [0/0] torch._dynamo.output_graph: [DEBUG] create_graph_input L_x_0_ L['x'][0]
[2024-01-09 16:49:05,234] [0/0] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['x'][0] (10,) StatefulSymbolicContext(dynamic_sizes=[<DimDynamic.STATIC: 2>], constraint_sizes=[None], tensor_source=GetItemSource(base=LocalSource(local_name='x', cell_or_freevar=False), index=0, index_is_slice=False), shape_env_to_source_to_symbol_cache={})
[2024-01-09 16:49:05,237] [0/0] torch._dynamo.output_graph: [DEBUG] create_graph_input L_x_1_ L['x'][1]
[2024-01-09 16:49:05,237] [0/0] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['x'][1] (10,) StatefulSymbolicContext(dynamic_sizes=[<DimDynamic.STATIC: 2>], constraint_sizes=[None], tensor_source=GetItemSource(base=LocalSource(local_name='x', cell_or_freevar=False), index=1, index_is_slice=False), shape_env_to_source_to_symbol_cache={})
[2024-01-09 16:49:05,239] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE RESUME 0 []
[2024-01-09 16:49:05,239] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /opt/pytorch/test_gh116443.py:5 in forward (Foo.forward)
[2024-01-09 16:49:05,239] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]             ori_dtype = y.dtype
[2024-01-09 16:49:05,239] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST y []
[2024-01-09 16:49:05,240] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR dtype [ConstantVariable(str)]
Traceback (most recent call last):
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1432, in dynamo_export
    ).export()
      ^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1174, in export
    graph_module = self.options.fx_tracer.generate_fx(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 213, in generate_fx
    graph_module, graph_guard = torch._dynamo.export(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 1268, in inner
    result_traced = opt_f(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 168, in wrapped
    return output_adapter.apply(model_func(*args, **kwargs), model=model)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 670, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 2098, in run
    super().run()
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
        ^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/opt/pytorch/torch/_dynamo/symbolic_convert.py", line 1282, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/variables/builtin.py", line 650, in call_function
    result = handler(tx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/variables/builtin.py", line 1238, in call_getattr
    return obj.var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/variables/base.py", line 257, in var_getattr
    value = self.const_getattr(tx, name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_dynamo/variables/constant.py", line 128, in const_getattr
    member = getattr(self.value, name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.InternalTorchDynamoError: 'str' object has no attribute 'dtype'

from user code:
   File "/opt/pytorch/test_gh116443.py", line 5, in forward
    ori_dtype = y.dtype


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pytorch/test_gh116443.py", line 14, in <module>
    torch.onnx.dynamo_export(model, data_in, '/opt/dev/tmp.onnx')
  File "<@beartype(torch.onnx._internal.exporter.dynamo_export) at 0x7f56b00b67a0>", line 51, in dynamo_export
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1443, in dynamo_export
    raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
[2024-01-09 16:49:05,250] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2024-01-09 16:49:05,250] torch._dynamo.utils: [INFO] Function                           Runtimes (s)
[2024-01-09 16:49:05,250] torch._dynamo.utils: [INFO] -------------------------------  --------------
[2024-01-09 16:49:05,250] torch._dynamo.utils: [INFO] _compile.<locals>.compile_inner               0
```

**Comment by thiagocrepaldi** [comment]
WIndows is now supported by torch.onnx.dynamo_export

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
