### ISSUE TITLE
`test_autograd_dense_output_addmm` fails if matrix sizes are square

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#116565]
### 🐛 Describe the bug

For example, if one adds `((2, 2), (2, 2), (2, 2), False),` option to sample_inputs_addmm, test will start to fail with:
```
2023-12-30T01:10:54.4934201Z ________ TestSparseCSRCPU.test_autograd_dense_output_addmm_cpu_float64 _________
2023-12-30T01:10:54.4934895Z Traceback (most recent call last):
2023-12-30T01:10:54.4935452Z   File "test_sparse_csr.py", line 2827, in test_autograd_dense_output_addmm
2023-12-30T01:10:54.4936040Z     output.backward(covector)
2023-12-30T01:10:54.4936864Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_tensor.py", line 513, in backward
2023-12-30T01:10:54.4937720Z     return handle_torch_function(
2023-12-30T01:10:54.4938628Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/overrides.py", line 1606, in handle_torch_function
2023-12-30T01:10:54.4939602Z     result = mode.__torch_function__(public_api, types, args, kwargs)
2023-12-30T01:10:54.4940824Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1315, in __torch_function__
2023-12-30T01:10:54.4941746Z     r = func(*args, **kwargs)
2023-12-30T01:10:54.4942511Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_tensor.py", line 522, in backward
2023-12-30T01:10:54.4943252Z     torch.autograd.backward(
2023-12-30T01:10:54.4944074Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/__init__.py", line 267, in backward
2023-12-30T01:10:54.4944857Z     _engine_run_backward(
2023-12-30T01:10:54.4945743Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/graph.py", line 681, in _engine_run_backward
2023-12-30T01:10:54.4946915Z     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
2023-12-30T01:10:54.4948107Z RuntimeError: sparse_addmm_sparse_backward: unsupported combination of layouts, grad: Strided, mat1: Strided, mat2: SparseCsr
```

### Versions

Nigthly, 2.2

**Comment by cpuhrsch** [comment]
This isn't really a bug as much as a missing autograd feature. We don't support mixing of layouts for autograd.
