### ISSUE TITLE
ONNX export issue (To CoreML)

### ISSUE THREAD

**Issue by leonardoaraujosantos** [pytorch/pytorch#11670]
## Issue description
Use of ONNX models exported from Pytorch 0.4.1, causes issues when converting to coreML

Provide a short description.

## Code example
```python
import torch
import torch.nn as nn
import torch.onnx as torch_onnx
from onnx_coreml import convert

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3,3), stride=1, padding=0, bias=True)

    def forward(self, inputs):
        x = self.conv(inputs)
        # The view create the reshape/unsqueeze issue when exporting to coreml
        x = x.view(x.size()[0], -1)
        #x = x.view(1, 307328)
        print(x.size())
        return x

# Use this an input trace to serialize the model
input_shape = (3, 100, 100)
model_onnx_path = "torch_model.onnx"
model = Model()
model.train(False)

# Export the model to an ONNX file
dummy_input = torch.randn(1, *input_shape)
output = torch_onnx.export(model, 
                          dummy_input, 
                          model_onnx_path, 
                          export_params=True,
                          verbose=True)

# Export to coreml
coreml_model = convert('./torch_model.onnx')
coreml_model.save('./test.mlmodel')
```

## Results
```bash
torch.Size([1, 307328])
graph(%0 : Float(1, 3, 100, 100)
      %1 : Float(32, 3, 3, 3)
      %2 : Float(32)) {
  %3 : Float(1, 32, 98, 98) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[1, 1]](%0, %1, %2), scope: Model/Conv2d[conv]
  %4 : Dynamic = onnx::Shape(%3), scope: Model
  %5 : Dynamic = onnx::Slice[axes=[0], ends=[1], starts=[0]](%4), scope: Model
  %6 : Long() = onnx::Squeeze[axes=[0]](%5), scope: Model
  %7 : Long() = onnx::Constant[value={-1}](), scope: Model
  %8 : Dynamic = onnx::Unsqueeze[axes=[0]](%6), scope: Model
  %9 : Dynamic = onnx::Unsqueeze[axes=[0]](%7), scope: Model
  %10 : Dynamic = onnx::Concat[axis=0](%8, %9), scope: Model
  %11 : Float(1, 307328) = onnx::Reshape(%3, %10), scope: Model
  return (%11);
}

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-39-c67c0dcc89da> in <module>()
     33 
     34 # Export to coreml
---> 35 coreml_model = convert('./torch_model.onnx')
     36 coreml_model.save('./test.mlmodel')

/usr/local/lib/python3.5/dist-packages/onnx_coreml/converter.py in convert(model, mode, image_input_names, preprocessing_args, image_output_names, deprocessing_args, class_labels, predicted_feature_name, add_custom_layers, custom_conversion_functions)
    396     '''
    397     if not add_custom_layers:
--> 398         _check_unsupported_ops(graph.nodes)
    399 
    400     err = ErrorHandling(add_custom_layers,

/usr/local/lib/python3.5/dist-packages/onnx_coreml/converter.py in _check_unsupported_ops(nodes)
    102     if len(unsupported_op_types) > 0:
    103         raise NotImplementedError("Unsupported ONNX ops of type: %s" % (
--> 104             ','.join(unsupported_op_types)))
    105 
    106 

NotImplementedError: Unsupported ONNX ops of type: Shape,Squeeze,Unsqueeze
```

## System Info
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04 LTS
GCC version: (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TitanX

Nvidia driver version: 375.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by bddppq** [comment]
Shape, Squeezee and Unsqueeze are valid ONNX operators, please create a feature request for supporting these ops in the onnx-coreml repo.

**Comment by glenn-jocher** [comment]
Hello, I get the same error currently with **PyTorch 1.0.0 and ONNX 1.3.0:**
```
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 208, in <module>
    main()
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 32, in main
    yolov3_model = convert(model_proto, image_input_names=['0'], preprocessing_args={'image_scale': 1. / 255})
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 455, in convert
    _check_unsupported_ops(graph.nodes)
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 143, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported ONNX ops of type: Shape,Gather
```

**Comment by jasonlovescoding** [comment]
This is actually a weird problem. 

If you simply do x.view(x.size(0), -1), a bunch of constant/sqeeze/unsqueeze nodes along with a reshape node pop up which seems unnecessary to me. But if you do x.view(x.data.size(0), -1), this problem goes away with a clear reshape node itself. This only happend for versions equal to or higher than 0.4.1.

For some reason, x (type 'Tensor'), when calling x.size(0), returns an integer, but ONLY WHEN calling torch.onnx.export in its inner tracing, it returns a torch.Size object which contains the same integer. 
I guess this is reason why some additional nodes are traced as well. Is there a way to fix it?
