### ISSUE TITLE
test_serialization_offset may fail with small $TMP

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#116861]
### 🐛 Describe the bug

I'd like to suggest making the `test_serialization_offset` a bit more robust. Currently I see this sometimes:
```
________________________________________________________________________________ TestOldSerialization.test_serialization_offset ________________________________________________________________________________
Traceback (most recent call last):
  File "/dev/shm/pytorch-v2.1.2/test/test_serialization.py", line 869, in test_serialization_offset
    torch.save(b, f)
  File "/dev/shm/pytorch-v2.1.2/test/test_serialization.py", line 780, in wrapper
    return self.torch_save(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/serialization.py", line 623, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/python3.10/site-packages/torch/serialization.py", line 767, in _legacy_save
    storage._write_file(f, _should_read_directly(f), True, torch._utils._element_size(dtype))
RuntimeError: write(): fd 5 failed with No space left on device
```

Reason is that it writes a temporary file of more than 2 GB size which is rather large, especially for a test. Would you consider skipping the test if there is not enough space in the chosen tempdir and/or reducing the written file size?

### Versions

PyTorch 2.1.2

**Comment by albanD** [comment]
My expectation is that this test is ensuring that offset values larger than INT32_MAX are working fine. So reducing the size won't work.
I'm happy with adding a `@slowTest()` to it so that it doesn't run by default.

I'm not a fan of skipping if there is less than 2GB available on the drive as it can easily end up silently skipping this test forever in CI if for some reason the /tmp on our CI machines drops below that.
