### ISSUE TITLE
Nightly pip wheel+cu121 reports NCCL==2.18.1, but installs nvidia-nccl-cu12==2.19.3

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#116977]
Command to install the latest nightly binary:
```
pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu121
```
installs `nvidia-nccl-cu12==2.19.3`:
```
Looking in indexes: https://download.pytorch.org/whl/nightly/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cu121/torch-2.3.0.dev20240108%2Bcu121-cp310-cp310-linux_x86_64.whl (757.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.0/757.0 MB 36.2 MB/s eta 0:00:00
...
Collecting nvidia-nccl-cu12==2.19.3 (from torch)
  Downloading https://download.pytorch.org/whl/nightly/cu121/nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
...
```
However, PyTorch itself reports `2.18.1`:
```python
python -c "import torch; print(torch.__version__); print(torch.cuda.nccl.version())"
2.3.0.dev20240108+cu121
(2, 18, 1)
```
I guess this version tag might be defined during the build process from e.g. [here](https://github.com/pytorch/pytorch/blob/ad507789d12e3f757a43f35cd66e7aea6124140d/torch/csrc/cuda/nccl.cpp#L470) and then forwarded from [here](https://github.com/pytorch/pytorch/blob/ad507789d12e3f757a43f35cd66e7aea6124140d/torch/csrc/cuda/python_nccl.cpp#L26-L28), but also source builds should use `2.19.3` based on the `third_party/nccl` tag. 
Unsure, if this is just a reporting issue or if we are building the nightly binaries with `NCCL==2.18.1` and executing them with `2.19.3`, so creating this issue to dig a bit further into it.

CC @malfet @atalman  

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
@atalman can you please check that 2.2.0 reports (and is build) against the correct version of nccl library?

**Comment by atalman** [comment]
Confirmed for nightlies :
https://github.com/pytorch/builder/actions/runs/7450624690/job/20269994330
```
torchvision CUDA: 12010
torchaudio CUDA: 12010
torch cuda: 12.1
torch nccl version: (2, 18, 1)
torch cudnn: 8902
cuDNN enabled? True
```

**Comment by atalman** [comment]
Looking at the build log
```
2023-12-28T22:46:59.7652036Z -- Building version 2.2.0+cu121
2023-12-28T22:46:59.7785554Z cmake -GNinja -DBUILD_ENVIRONMENT=linux-binary-manywheel -DBUILD_JNI=OFF -DBUILD_LIBTORCH_CPU_WITH_DEBUG=0 -DBUILD_PYTHON=True -DBUILD_PYTHONLESS= -DBUILD_TEST=True -DCAFFE2_STATIC_LINK_CUDA=0 -DCMAKE_ARGS= -DCMAKE_BUILD_TYPE=Release -DCMAKE_INCLUDE_PATH=/opt/openssl/include:/opt/intel/include: -DCMAKE_INSTALL_PREFIX=/pytorch/torch -DCMAKE_LIBRARY_PATH=/opt/intel/lib:/lib: -DCMAKE_PREFIX_PATH=/opt/python/cp311-cp311/lib/python3.11/site-packages -DGLIBCXX_USE_CXX11_ABI=0 -DINSTALL_TEST=0 -DJAVA_HOME= -DNUMPY_INCLUDE_DIR=/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/core/include -DOPENSSL_ROOT_DIR=/opt/openssl -DPYTHON_EXECUTABLE=/opt/python/cp311-cp311/bin/python -DPYTHON_INCLUDE_DIR=/opt/python/cp311-cp311/include/python3.11 -DPYTHON_LIBRARY=/opt/_internal/cpython-3.11.0/lib/libpython3.11.so.1.0 -DTORCH_BUILD_VERSION=2.2.0+cu121 -DTORCH_CUDA_ARCH_LIST=5.0;6.0;7.0;7.5;8.0;8.6;9.0 -DUSE_CUPTI_SO=1 -DUSE_CUSPARSELT=1 -DUSE_FBGEMM=1 -DUSE_GLOO_WITH_OPENSSL=ON -DUSE_GOLD_LINKER=OFF -DUSE_KINETO=1 -DUSE_NCCL=1 -DUSE_NUMPY=True -DUSE_RCCL=1 -DUSE_STATIC_CUDNN=0 -DUSE_STATIC_NCCL=0 -DUSE_SYSTEM_NCCL=1 /pytorch
```

Looks like we are compiling with: USE_SYSTEM_NCCL

**Comment by atalman** [comment]
On Windows I see following exception:
```
Traceback (most recent call last):
  File "./test/smoke_test/smoke_test.py", line 317, in <module>
    main()
  File "./test/smoke_test/smoke_test.py", line 313, in main
    smoke_test_cuda(options.package, options.runtime_error_check)
  File "./test/smoke_test/smoke_test.py", line 166, in smoke_test_cuda
    print(f"torch nccl version: {torch.cuda.nccl.version()}" )
  File "C:\Jenkins\Miniconda3\envs\conda-env-7450624690\lib\site-packages\torch\cuda\nccl.py", line 35, in version
    ver = torch._C._nccl_version()
AttributeError: module 'torch._C' has no attribute '_nccl_version'
```
We compiling with ``USE_NCCL = FALSE`` should we return None rather then exception ?

**Comment by ptrblck** [comment]
> Looks like we are compiling with: USE_SYSTEM_NCCL

In this case we are indeed using 2.18.1:
https://github.com/pytorch/builder/blob/04ef1bf031cc8b75d5d7f8a5e7a0832d5a0a46da/common/install_cuda.sh#L68-L75

Do you know why we are using the system-wide NCCL installation instead of the `third_party` one?
Should we delete the system NCCL and use `third_party` by default?

**Comment by atalman** [comment]
Looks like its set here:

https://github.com/pytorch/builder/blob/main/manywheel/build_cuda.sh#L189-L190

**Comment by ptrblck** [comment]
I guess we are using the system NCCL installation to be able to `pip install nvidia-nccl-cu12` during the runtime. If we would use the `third_party/nccl` module I assume we would link NCCL into the PyTorch binaries.
If so, we should make sure to update the `install_cuda.sh` NCCL version whenever `third_party/nccl` is updated.

**Comment by atalman** [comment]
Yes. Also when we update this nccl here:
https://github.com/pytorch/pytorch/blob/main/.github/scripts/generate_binary_build_matrix.py#L58

**Comment by atalman** [comment]
@ptrblck We used following path 
``
https://developer.download.nvidia.com/compute/redist/nccl/v2.18.1/
``

What would be good path for nccl 2.19.3 and cuda 12.1 ?

**Comment by malfet** [comment]
Installing system NCCL into the nightly build docker container feels great, but we need to figure out, how to keep it in sync with PyTorch. I wonder if one can, for example, just check nccl version from this requirements file and build from source?

**Comment by atalman** [comment]
@malfet yes probably we should build and upload nccl for our supported cuda versions, same way as we build docker containers, by following details here: https://github.com/NVIDIA/nccl/blob/master/README.md
