### ISSUE TITLE
torch._dynamo.exc.InternalTorchDynamoError: DeviceMeshVariable() has no type

### ISSUE THREAD

**Issue by mathemakitten** [pytorch/pytorch#117042]
### 🐛 Describe the bug

Sharding and compiling a single Linear module works well, but trying to register an all-gather forward hook on it seems to break (edit: to be clear, I think the error is related to Dynamo trying to compile the collective for this device mesh, not the hook itself). ~~Is this an unexpected way of using `network.linear.register_forward_hook` or a bug?~~

Here's a toy repro and the log:

```
import torch
from torch.distributed._tensor import DeviceMesh
from torch.distributed.tensor.parallel import parallelize_module, ColwiseParallel
from torch.distributed._tensor import Shard, distribute_tensor, Replicate
from torch.distributed import _functional_collectives as funcol

mesh = DeviceMesh("cuda", torch.arange(2))

class Test(torch.nn.Module):
  def __init__(self):
    super(Test, self).__init__()
    self.weight1 = torch.nn.Linear(in_features=128, out_features=128)
  def forward(self, input):
    return self.weight1(input)


class Network(torch.nn.Module):
  def __init__(self, mesh):
    super(Network, self).__init__()
    self.linear = Test()

    self.linear_parallelized = parallelize_module(self.linear, mesh, {"weight1": ColwiseParallel()})
    self.linear_compiled = torch.compile(self.linear_parallelized)

  def forward(self, input):
    out = self.linear_compiled(input)
    return out


network = Network(mesh)
network.linear.register_forward_hook(lambda _module, _input, output: funcol.all_gather_tensor(output, -1, mesh))

input = torch.rand([128, 128], requires_grad=True)
input = distribute_tensor(input, mesh, [Replicate()])
output = network(input)

x = torch.unsqueeze(output, -1)
labels = torch.unsqueeze(torch.randint(0, 128, (128,)), -1).cuda()

loss_func = torch.nn.CrossEntropyLoss()
loss = loss_func(x, labels)
loss.backward()
```

Log:
```
Traceback (most recent call last):
  File ".../dtensor_backward_funcol.py", line 40, in <module>
    output = network(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/.../dtensor_backward_funcol.py", line 31, in forward
    out = self.linear_compiled(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1574, in _call_impl
    hook_result = hook(self, args, result)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 741, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 670, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2110, in run
    super().run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 1190, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 255, in call_function
    return super().call_function(tx, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 84, in call_function
    return tx.inline_user_function_return(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 650, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2245, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2360, in inline_call_
    tracer.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 1190, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 255, in call_function
    return super().call_function(tx, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 84, in call_function
    return tx.inline_user_function_return(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 650, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2245, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2360, in inline_call_
    tracer.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 1190, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/builtin.py", line 650, in call_function
    result = handler(tx, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/builtin.py", line 1002, in call_isinstance
    arg_type = arg.python_type()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/base.py", line 233, in python_type
    raise NotImplementedError(f"{self} has no type")
torch._dynamo.exc.InternalTorchDynamoError: DeviceMeshVariable() has no type

from user code:
   File ".../dtensor_backward_funcol.py", line 36, in <lambda>
    network.linear.register_forward_hook(lambda _module, _input, output: funcol.all_gather_tensor(output, -1, mesh))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/_functional_collectives.py", line 203, in all_gather_tensor
    tag, rankset, group_size = _expand_group(group, tag)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/_functional_collectives.py", line 548, in _expand_group
    if isinstance(group, list):

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

### Versions

PyTorch version: 2.3.0.dev20240105+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.104.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] onnx==1.14.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.3.0.dev20240105+cu121
[pip3] torch-tensorrt==0.0.0
[pip3] torchaudio==2.2.0.dev20240105+cu121
[pip3] torchdata==0.7.0a0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.18.0.dev20240105+cu121
[pip3] triton==2.1.0+e621604

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @ezyang @anijain2305 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @rohan-varma @msaroufim @bdhirsh @zou3519 @aakhundov

**Comment by mathemakitten** [comment]
Follow up: I can resolve this by adding a `python_type` method to the DeviceMeshVariable class [here](https://github.com/pytorch/pytorch/blob/e4e80dc9b3a3b09b3e514617c884ed1df2e4f4c1/torch/_dynamo/variables/distributed.py#L132), e.g. `def python_type(self):; return type(self.value)`, since otherwise it inherits the `NotImplementedError` from `VariableTracker`. Is this sufficient or is there more work needed on `DeviceMeshVariable` to make it compatible?

**Comment by ezyang** [comment]
cc @voznesenskym didn't you have a device mesh pr or something

**Comment by wanchaol** [comment]
@mathemakitten orthogonal to this torch.compile issue (I think we should fix this compile issue too).

I'm wondering if you tried using the `ColwiseParallel(input_layouts=Shard(shard_dim))` kwarg instead? This `input_layouts` kwarg would annotate the input sharding be sharded on the `shard_dim` and under the hood it will perform a allgather directly, and it should be torch.compile compatible.

**Comment by mathemakitten** [comment]
Thanks for the suggestion @wanchaol. 

To be specific, to trigger the all-gather you'd have to also set the `output_layouts` kwarg, right? e.g. `ColwiseParallel(input_layouts=Shard(-1), output_layouts=Replicate())`? Otherwise I think the output would still be sharded at the end, right?

**Comment by wanchaol** [comment]
> To be specific, to trigger the all-gather you'd have to also set the `output_layouts` kwarg, right? e.g. `ColwiseParallel(input_layouts=Shard(-1), output_layouts=Replicate())`? Otherwise I think the output would still be sharded at the end, right?

No, `output_layouts` mean the module output sharding layout, it's AFTER the execution of the module. `ColwiseParallel` desired input layout is Replicate() so you only need to specify `input_layouts` to trigger allgather on the inputs BEFORE the module execution.  The default output sharding layout of `ColwiseParallel` is shard on the last dimension, if you want to control the output sharding, you can specify it as replicate, where AFTER the nn.Linear/Embedding execution it would trigger another allgather

**Comment by wanchaol** [comment]
@mathemakitten sorry this is the new UX we introduced recently so the doc might not be documented enough about what happened under the hood, there is some [updated example of sequence parallelism with the swiglu MLP](https://github.com/pytorch/examples/blob/main/distributed/tensor_parallelism/sequence_parallel_example.py). This would trigger one allgather in the beginning of the first Colwise linear layer, and a reduce_scatter in the end after the second Rowwise linear layer, as the sharding layout conversion become: Shard(0) -> Replicate() means allgather and Partial() -> Shard(0) means reduce_scatter

**Comment by mathemakitten** [comment]
Thanks for the clarification! I think this is consistent — originally I wanted to all-gather after module execution, but I can do that with model shardings as opposed to a forward hook. The input_layouts makes sense with your example of sequence parallelism. 

When I remove the forward hook in favour of model shardings the DeviceMesh error goes away, so I think we're all good here unless someone _does_ actually want to use a forward hook.

**Comment by masnesral** [comment]
Scrubbing old issues. Per the last update, I'm assuming we can close this out but feel free to reopen if I've misread the conversation.
