### ISSUE TITLE
[inductor][cpu] some models meet AttributeError: 'View' object has no attribute 'layout'

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#117108]
### 🐛 Describe the bug

Some models meet AttributeError: 'View' object has no attribute 'layout', take twins_pcpvt_base as example:
```
loading model: 0it [00:00, ?it/s]cpu  eval  twins_pcpvt_base                   

ERROR:common:backend='inductor' raised:
AttributeError: 'View' object has no attribute 'layout'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2433, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2167, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 741, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2110, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2228, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 914, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1085, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1157, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1138, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/backends/inductor.py", line 9, in inductor
    return compile_fx(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1173, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 889, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 602, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 427, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 632, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 916, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 317, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 536, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 529, in run
    return super().run(*args)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 144, in run
    self.env[node] = self.run_node(node)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 837, in run_node
    result = super().run_node(n)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 201, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 673, in call_function
    return target(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/fx_passes/mkldnn_fusion.py", line 507, in fn
    or isinstance(other.get_layout(), (ir.MutationLayout, ir.AliasedLayout))
  File "/workspace/pytorch/torch/_inductor/ir.py", line 6322, in get_layout
    return self.layout
  File "/workspace/pytorch/torch/_inductor/ir.py", line 6306, in __getattr__
    fn = getattr(self.data, name)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AttributeError: 'View' object has no attribute 'layout'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

### Versions

</table><p>Reference SW info(nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.3.0a0+git7d163a9</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single/multiple inference accuracy timm_models twins_pcpvt_base amp first static default 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/4926146537df5a39846dae0e551d394001588b13

[timm_models-twins_pcpvt_base-inference-amp-static-default-accuracy-multiple-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/13888474/timm_models-twins_pcpvt_base-inference-amp-static-default-accuracy-multiple-crash_guilty_commit.log)

cc @WeizhuoZhang-intel @chuanqi129

**Comment by zxd1997066** [comment]
coat_lite_mini(timm_models), fp32 single/multiple default/cpp wrapper also meet the same error.

**Comment by leslie-fang-intel** [comment]
Expect fixing by https://github.com/pytorch/pytorch/pull/117330

**Comment by leslie-fang-intel** [comment]
The issue has been resolved by the test report of [[amp] Performance Dashboard for amp precision -- Single-core Single-thread (2024-01-13 nightly release)](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1892347165) and [[default] Performance Dashboard for float32 precision -- Single-core Single-thread (2024-01-14 nightly release)](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1892895578)
