### ISSUE TITLE
Dynamo'd tests that access optimizer param_groups errors for all optimizers

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#117165]
### 🐛 Describe the bug

Old guess: It looks like applying torch.compile() on optimizers changes the attributes of the optimizer object--it looks like param_groups get removed. Maybe this is expected behavior, though I am not convinced that's what it should be like.
New guess: it looks like self.value in dynamo is the test class instead of the test instance, so param_groups fails to be found on it.

Specifically, this issue is confronted by several tests, the first being `test_deepcopy_copies_all_public_attrs`--this test creates optimizers on 2 small parameters, runs 3 steps to create state, and then makes sure that the public attributes accessed in the optimizer instance and a deepcopy of that instance remain the same.

### Error logs

This test fails on all optimizers, but here are the logs for RAdam as an example:
```
======================================================================
ERROR: test_deepcopy_copies_all_public_attrs_RAdam_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 429, in instantiated_test
    raise rte
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 182, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 594, in test_deepcopy_copies_all_public_attrs
    all_optim_inputs = _get_optim_inputs_including_global_cliquey_kwargs(device, dtype, optim_info, skip=("differentiable",))
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 596, in resume_in_test_deepcopy_copies_all_public_attrs_at_594
    params = [Parameter(torch.randn(2, 3, device=device, dtype=dtype)) for _ in range(2)]
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 618, in resume_in_test_deepcopy_copies_all_public_attrs_at_596
    self.assertEqual(getPublicAttrs(optimizer), getPublicAttrs(deepcopy(optimizer)))
  File "/home/janeyx/.conda/envs/pytorch-3.10/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/janeyx/.conda/envs/pytorch-3.10/lib/python3.10/copy.py", line 273, in _reconstruct
    y.__setstate__(state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 741, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 670, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 2098, in run
    super().run()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 1190, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builtin.py", line 493, in call_function
    args = [v.realize() for v in args]
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builtin.py", line 493, in <listcomp>
    args = [v.realize() for v in args]
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/lazy.py", line 56, in realize
    self._cache.realize(self.parents_tracker)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/lazy.py", line 22, in realize
    self.vt = VariableBuilder(tx, self.source)(self.value)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builder.py", line 244, in __call__
    vt = self._wrap(value)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/builder.py", line 606, in _wrap
    return OptimizerVariable(value, source=self.source)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/base.py", line 121, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/variables/optimizer.py", line 38, in __init__
    for group in self.value.param_groups:
torch._dynamo.exc.InternalTorchDynamoError: 'RAdam' object has no attribute 'param_groups'

from user code:
   File "/data/users/janeyx/pytorch/torch/optim/radam.py", line 58, in __setstate__
    super().__setstate__(state)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_deepcopy_copies_all_public_attrs_RAdam_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

### Minified repro

`PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_deepcopy_copies_all_public_attrs_RAdam`

### Versions

on main

cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @mlazos

**Comment by janeyx99** [comment]
I'm running into the same issue with my added `test_init_state_per_param` test in https://github.com/pytorch/pytorch/pull/122242. Contrary to my prior guess, it looks like `self.value` in dynamo is the test class instead of the test instance, so param_groups fails to be found on it.

**Comment by mlazos** [comment]
This has been fixed with https://github.com/pytorch/pytorch/pull/123497
