### ISSUE TITLE
Dynamo'd test_state_dict_with_cuda_params_SGD fails state equality assert

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#117147]
### 🐛 Describe the bug

The source of this error may be the same as in https://github.com/pytorch/pytorch/issues/116061. Running `PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_state_dict_with_cuda_params_SGD` will miss the momentum buffer. 

The gist of this test is to start with an optimizer on CPU, move the params to CUDA, and verify that a new optimizer created on CUDA will compute similar results as the one that continues to run on CPU.

Adding this issue to track so that once `_init_group`, is traced, maybe this will go away.

I didn't combine this with the existing issue mentioned above in case it's actually a different error with state_dicts.

### Error logs

```
======================================================================
FAIL: test_state_dict_with_cuda_params_SGD_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 182, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 1110, in only_fn
    return fn(slf, *args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 533, in test_state_dict_with_cuda_params
    cpu_optim_inputs = _get_optim_inputs_including_global_cliquey_kwargs("cpu", dtype, optim_info, skip=("differentiable",))
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 584, in resume_in_test_state_dict_with_cuda_params_at_533
    self.assertEqual(optimizer.state_dict(), optimizer_cuda.state_dict())
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 3479, in assertEqual
    error_metas = not_close_error_metas(
  File "/data/users/janeyx/pytorch/torch/testing/_comparison.py", line 1217, in not_close_error_metas
    raise error_meta.to_error() from None
AssertionError: The keys of the mappings do not match:
Missing keys in the actual mapping: ['momentum_buffer']
Additional keys in the actual mapping: []

The failure occurred for item ['state'][0]

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_state_dict_with_cuda_params_SGD_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

### Minified repro

`PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_state_dict_with_cuda_params_SGD`

### Versions

on main

cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @mlazos @mruberry @ZainRizvi @aakhundov

**Comment by mlazos** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/123404, closing
