### ISSUE TITLE
Dynamo'd state_dict tests for NAdam error expecting scalars on CPU

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#117150]
### 🐛 Describe the bug

Tests using load_state_dict error for NAdam when run with dynamo. There seems to be something wrong with how we checkpoint between torch.compile()'d optimizers regarding scalars. 

The first is the same test as in #117147 (`test_state_dict_with_cuda_params`). The gist of the test is a common case where params start off optimizing on CPU and later get moved to CUDA. We want to ensure that the param updates and state are equal/allclose in both cases.

The other is `test_load_nontensor_step` which tests that a non-tensor `step` could be loaded and the optimizer could run with the Python step with no issues.

The tests pass in eager but errors in dynamo.

### Error logs

```
======================================================================
ERROR: test_state_dict_with_cuda_params_NAdam_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 429, in instantiated_test
    raise rte
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 182, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 1110, in only_fn
    return fn(slf, *args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 533, in test_state_dict_with_cuda_params
    cpu_optim_inputs = _get_optim_inputs_including_global_cliquey_kwargs("cpu", dtype, optim_info, skip=("differentiable",))
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 582, in resume_in_test_state_dict_with_cuda_params_at_533
    optimizer_cuda.step(closure)
  File "/data/users/janeyx/pytorch/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/optim/nadam.py", line 111, in step
    nadam(params_with_grad,
  File "/data/users/janeyx/pytorch/torch/optim/nadam.py", line 191, in nadam
    def nadam(params: List[Tensor],
  File "/data/users/janeyx/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/fx/graph_module.py", line 315, in __call__
    raise e.with_traceback(None)  # noqa: TRY200
RuntimeError: Expected scalars to be on CPU, got cuda:0 instead.

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_state_dict_with_cuda_params_NAdam_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

### Minified repro

`PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_state_dict_with_cuda_params_NAdam`

### Versions

on main

cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @mlazos @wconstab

**Comment by mlazos** [comment]
Closing, test is enabled now
