### ISSUE TITLE
`test_mixed_mm2_cuda` fails on V100

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#117144]
### 🐛 Describe the bug

Tested in a source build and the latest nightly+cu121.
Steps to reproduce the issue on a V100:
```python
python inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
test_mixed_mm2_cuda (__main__.CudaTests) ... FAIL

======================================================================
FAIL: test_mixed_mm2_cuda (__main__.CudaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/workspace/src/pytorch/test/inductor/test_torchinductor.py", line 8197, in new_test
    return value(self)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/src/pytorch/test/inductor/test_torchinductor.py", line 2136, in test_mixed_mm2
    self.common(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/src/pytorch/test/inductor/test_torchinductor.py", line 516, in check_model_cuda
    check_model(
  File "/workspace/src/pytorch/test/inductor/test_torchinductor.py", line 376, in check_model
    self.assertEqual(
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 3518, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 32 / 64 (50.0%)
Greatest absolute difference: 556.0 at index (4, 6) (up to 1e-05 allowed)
Greatest relative difference: 2.876953125 at index (2, 7) (up to 0.001 allowed)
```
I'm not sure if these Trriton kernels ever worked on Volta as it seems the tests were never executed before: https://github.com/pytorch/pytorch/pull/114504

Attaching the created code from `TORCH_LOGS=output_code python inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda` assuming it makes it easier to isolate the issue.
[mixed_mm2_code.txt](https://github.com/pytorch/pytorch/files/13893887/mixed_mm2_code.txt)

### Versions

`2.3.0.dev20240110+cu121`

CC @eqy 

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

**Comment by ptrblck** [comment]
@atalman Yes, the issue is in `2.2.0`:
```python
git status
HEAD detached at v2.2.0-rc8
...
pip list | grep torch
torch                     2.2.0+cu121
...
python inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
test_mixed_mm2_cuda (__main__.CudaTests) ... FAIL
...
Mismatched elements: 32 / 64 (50.0%)
Greatest absolute difference: 556.0 at index (4, 6) (up to 1e-05 allowed)
Greatest relative difference: 2.876953125 at index (2, 7) (up to 0.001 allowed)
```
However, unsure if this is a regression or a newly introduced method/failure. I'll test older releases.

**Comment by malfet** [comment]
Ok, I have a reproducer and a fix (as @jansel suggested, just skip templates on SM70), but I wonder if this condition also needs to be tweaked
https://github.com/pytorch/pytorch/blob/fc5cde7579a1221aa4fe1ecb586a0623f689fc76/torch/_inductor/utils.py#L847-L848

As at least V100 I'm testing on have 80 SMs:
```
>>> import torch
>>> torch.cuda.get_device_properties(0)
_CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16150MB, multi_processor_count=80)
```

**Comment by malfet** [comment]
So here is the fix:
```patch
diff --git a/torch/_inductor/kernel/mm.py b/torch/_inductor/kernel/mm.py
index 6479c2d83c7..f73ba2f9833 100644
--- a/torch/_inductor/kernel/mm.py
+++ b/torch/_inductor/kernel/mm.py
@@ -1,5 +1,6 @@
+import functools
 import logging
-from typing import Any, Dict, List
+from typing import Any, Dict, List, Optional
 
 import torch
 from torch._inductor.virtualized import V
@@ -259,10 +260,16 @@ def fallback_mixed_mm(mat1, mat2, *, out):
 aten_fallback_mixed_mm = ExternKernelChoice(fallback_mixed_mm, None)
 
 
+@functools.lru_cahce(0)
+def is_v100_gpu(index: Optional[int]) -> bool:
+   props = torch.cuda.get_device_properties(index or 0)
+   return props.major == 7
+
+
 def tuned_mixed_mm(mat1, mat2, mat2_dtype):
     m, n, k, layout, mat1, mat2 = mm_args(mat1, mat2, layout=None)
     choices = [aten_fallback_mixed_mm.bind((mat1, mat2), layout)]
-    if mat1.layout.dtype != torch.float32 and not mat2.layout.is_contiguous():
+    if (mat1.layout.dtype != torch.float32 and not mat2.layout.is_contiguous()) or is_v100_gpu(layout.device.index):
         # can't use triton kernel unless one of these is true
         return autotune_select_algorithm("mixed_mm", choices, [mat1, mat2], layout)
     if inductor_config.force_mixed_mm:
```

**Comment by atalman** [comment]
todo: check if its regresion against 2.1.0

**Comment by atalman** [comment]
This works for release 2.1.0:
```
python inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
test_mixed_mm2_cuda (__main__.CudaTests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK

python -c "import torch; import triton; print(torch.__version__); print(triton.__version__)"
2.1.0+cu121
2.1.0
```

**Comment by atalman** [comment]
The resolution is confirmed in RC: https://github.com/pytorch/pytorch/issues/119054#issuecomment-1949529494
