### ISSUE TITLE
split_with_sizes with unbacked SymInt fails under aot_eager

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117268]
### 🐛 Describe the bug

```
import torch
import torch._dynamo.config

torch._dynamo.config.capture_scalar_outputs = True

@torch.compile(backend="aot_eager", fullgraph=True)
def f(x, i):
    y, z = i.tolist()
    return torch.split(x, [y, z])

print(f(torch.randn(10, requires_grad=True), torch.tensor([7, 3])))
```

fails with

```
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/a.py", line 11, in <module>
    print(f(torch.randn(10, requires_grad=True), torch.tensor([7, 3])))
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/symbolic_convert.py", line 2098, in run
    super().run()
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/symbolic_convert.py", line 2216, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/output_graph.py", line 940, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/ezyang/local/c/pytorch-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/output_graph.py", line 1085, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/output_graph.py", line 1157, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/output_graph.py", line 1138, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/ezyang/c/pytorch/torch/__init__.py", line 1736, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_functorch/aot_autograd.py", line 889, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_functorch/aot_autograd.py", line 507, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/data/users/ezyang/c/pytorch/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 113, in inner
    flat_f_outs = f(*flat_f_args)
  File "/data/users/ezyang/c/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 604, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/fx/interpreter.py", line 144, in run
    self.env[node] = self.run_node(node)
  File "/data/users/ezyang/c/pytorch/torch/fx/interpreter.py", line 201, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/ezyang/c/pytorch/torch/fx/interpreter.py", line 273, in call_function
    return target(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/functional.py", line 190, in split
    return tensor.split(split_size_or_sections, dim)
  File "/data/users/ezyang/c/pytorch/torch/_tensor.py", line 888, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
  File "/data/users/ezyang/c/pytorch/torch/_subclasses/functional_tensor.py", line 380, in __torch_dispatch__
    outs_wrapped = pytree.tree_map_only(
  File "/data/users/ezyang/c/pytorch/torch/utils/_pytree.py", line 860, in tree_map_only
    return tree_map(map_only(__type_or_types)(func), tree)
  File "/data/users/ezyang/c/pytorch/torch/utils/_pytree.py", line 734, in tree_map
    return treespec.unflatten(map(func, *flat_args))
  File "/data/users/ezyang/c/pytorch/torch/utils/_pytree.py", line 599, in unflatten
    leaves = list(leaves)
  File "/data/users/ezyang/c/pytorch/torch/utils/_pytree.py", line 820, in wrapped
    return func(x)
  File "/data/users/ezyang/c/pytorch/torch/_subclasses/functional_tensor.py", line 309, in wrap
    return FunctionalTensor(x)
  File "/data/users/ezyang/c/pytorch/torch/_subclasses/functional_tensor.py", line 101, in __new__
    out = torch.Tensor._make_wrapper_subclass(  # type: ignore[arg-type, attr-defined]
  File "/data/users/ezyang/c/pytorch/torch/fx/experimental/sym_node.py", line 364, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/data/users/ezyang/c/pytorch/torch/fx/experimental/recording.py", line 250, in wrapper
    return event.run(self)
  File "/data/users/ezyang/c/pytorch/torch/fx/experimental/recording.py", line 151, in run
    return self.f(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3599, in evaluate_expr
    concrete_val = self.size_hint(orig_expr)
  File "/data/users/ezyang/c/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3339, in size_hint
    raise self._make_data_dependent_error(result_expr, expr)
torch._dynamo.exc.BackendCompilerFailed: backend='aot_eager' raised:
GuardOnDataDependentSymNode: It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is Eq(10 - i2, 0) (unhinted: Eq(10 - i2, 0)).  Scroll up to see where each of these data-dependent accesses originally occurred.

While executing %split : [num_users=2] = call_function[target=torch.functional.split](args = (%l_x_, [%item, %item_1]), kwargs = {})
Original traceback:
  File "/data/users/ezyang/c/pytorch/a.py", line 9, in f
    return torch.split(x, [y, z])


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

It works with backend="eager", it looks functionalization related.

This repro is a little different from the one I saw in prod:

```
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 113, in inner
[trainer0]:    flat_f_outs = f(*flat_f_args)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 604, in functional_call
[trainer0]:    out = Interpreter(mod).run(*args[params_len:], **kwargs)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/interpreter.py", line 144, in run
[trainer0]:    self.env[node] = self.run_node(node)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/interpreter.py", line 201, in run_node
[trainer0]:    return getattr(self, n.op)(n.target, args, kwargs)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/interpreter.py", line 273, in call_function
[trainer0]:    return target(*args, **kwargs)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/functional.py", line 190, in split
[trainer0]:    return tensor.split(split_size_or_sections, dim)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/_tensor.py", line 888, in split
[trainer0]:    return torch._VF.split_with_sizes(self, split_size, dim)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/_subclasses/functional_tensor.py", line 376, in __torch_dispatch__
[trainer0]:    return return_and_correct_aliasing(func, args, kwargs, outs_wrapped)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/utils/_python_dispatch.py", line 402, in return_and_correct_aliasing
[trainer0]:    _correct_storage_aliasing(func, schema_info, args, (out,) if not isinstance(out, tuple) else out)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/utils/_python_dispatch.py", line 289, in _correct_storage_aliasing
[trainer0]:    alias_non_inplace_storage(args[arg_idx], outs[return_idx])
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/utils/_python_dispatch.py", line 271, in alias_non_inplace_storage
[trainer0]:    torch.ops.aten.set_.source_Storage_storage_offset(r, arg.untyped_storage(), r.storage_offset(), r.shape)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/_ops.py", line 571, in __call__
[trainer0]:    return self_._op(*args, **(kwargs or {}))
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/experimental/sym_node.py", line 364, in guard_bool
[trainer0]:    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/experimental/recording.py", line 250, in wrapper
[trainer0]:    return event.run(self)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/experimental/recording.py", line 151, in run
[trainer0]:    return self.f(*args, **kwargs)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/experimental/symbolic_shapes.py", line 3582, in evaluate_expr
[trainer0]:    concrete_val = self.size_hint(orig_expr)
[trainer0]:  File "/mnt/xarfuse/uid-539346/8387ba76-seed-nspid4026531836_cgpid124304388-ns-4026531840/torch/fx/experimental/symbolic_shapes.py", line 3322, in size_hint
[trainer0]:    raise self._make_data_dependent_error(result_expr, expr)
[trainer0]:torch._dynamo.exc.BackendCompilerFailed: backend='aot_eager' raised:
[trainer0]:GuardOnDataDependentSymNode: It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is Ne(8889 - i6, 0) (unhinted: Ne(8889 - i6, 0)).  Scroll up to see where each of these data-dependent accesses originally occurred.
```

Here, it is stuck later at `alias_non_inplace_storage`. We will probably get there if we fix the initial problem.

This is extracted from @flaviotruzzi code: https://www.internalfb.com/intern/paste/P1007882414/ log: https://www.internalfb.com/intern/paste/P1007886044/ (Meta-only)

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

### Versions

main

**Comment by ezyang** [comment]
<img width="522" alt="image" src="https://github.com/pytorch/pytorch/assets/13564/b9bb35cd-286d-45d8-9e45-9ef54ba296dd">

**Comment by bdhirsh** [comment]
@flaviotruzzi let me know if you want any help!

**Comment by bdhirsh** [comment]
I printed the C++ backtrace from the repro (looks like `computeStorageNbytes` is very branchy):
```
  File "/data/users/hirsheybar/e/pytorch/torch/csrc/autograd/python_variable.cpp", line 740, in THPVariable_make_wrapper_subclass(_object*, _object*, _object*)
    size_bytes = at::detail::computeStorageNbytes(
  File "/data/users/hirsheybar/e/pytorch/aten/src/ATen/EmptyTensor.cpp", line 137, in at::detail::computeStorageNbytes(c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt const&, c10::SymInt const&)
    if (sizes[i] == 0) {
  File "/data/users/hirsheybar/e/pytorch/c10/core/SymInt.cpp", line 264, in c10::operator==(c10::SymInt const&, int)
    DEFINE_SYMINT_OP(int32_t, SymInt) // make sure constants work
  File "/data/users/hirsheybar/e/pytorch/c10/core/SymInt.h", line 198, in c10::SymInt::operator==(c10::SymInt const&) const
    return sym_eq(o).guard_bool(__FILE__, __LINE__);
  File "/data/users/hirsheybar/e/pytorch/c10/core/SymBool.cpp", line 64, in c10::SymBool::guard_bool(char const*, long) const
    return a->guard_bool(file, line);
```

**Comment by ezyang** [comment]
So this "fixes" it:

```
diff --git a/torch/fx/experimental/symbolic_shapes.py b/torch/fx/experimental/symbolic_shapes.py
index 5c02aa7cfa2..2564b801826 100644
--- a/torch/fx/experimental/symbolic_shapes.py
+++ b/torch/fx/experimental/symbolic_shapes.py
@@ -3456,7 +3456,7 @@ class ShapeEnv:
                         else:
                             # Never substitute backed with unbacked
                             ok = len(free_unbacked_symbols(new_var)) == 0
-                        if ok:
+                        if ok and False:
                             self._set_replacement(cast(sympy.Symbol, free[0]), new_var)
             except NotImplementedError:
                 pass
```

The problem is that when we see the runtime assert `i0 + i1 == 10`, we setup a replacement `i1 = 10 - i0`. But when we do this, we forget that `10 - i0` is size-like (and importantly, that it doesn't equal zero.) The size-likeness cannot be inferred from the fact that i0 is size like. Oops.

**Comment by ezyang** [comment]
cc @aakhundov

**Comment by ezyang** [comment]
@angelayi pointed out a similar version of this issue, though not replacement related.

```
import torch

class Basic(torch.nn.Module):
    def forward(self, x):
        y = x.item()
        return torch.zeros(y + 1)

ep = torch.export.export(Basic(), (torch.tensor(3),))
print(ep)
```

**Comment by flaviotruzzi** [comment]
> So this "fixes" it:
> 
> ```
> diff --git a/torch/fx/experimental/symbolic_shapes.py b/torch/fx/experimental/symbolic_shapes.py
> index 5c02aa7cfa2..2564b801826 100644
> --- a/torch/fx/experimental/symbolic_shapes.py
> +++ b/torch/fx/experimental/symbolic_shapes.py
> @@ -3456,7 +3456,7 @@ class ShapeEnv:
>                          else:
>                              # Never substitute backed with unbacked
>                              ok = len(free_unbacked_symbols(new_var)) == 0
> -                        if ok:
> +                        if ok and False:
>                              self._set_replacement(cast(sympy.Symbol, free[0]), new_var)
>              except NotImplementedError:
>                  pass
> ```
> 
> The problem is that when we see the runtime assert `i0 + i1 == 10`, we setup a replacement `i1 = 10 - i0`. But when we do this, we forget that `10 - i0` is size-like (and importantly, that it doesn't equal zero.) The size-likeness cannot be inferred from the fact that i0 is size like. Oops.

Would be enough to add some extra control when we are setting the replacement, so we don’t forget the size-likeness?

**Comment by ezyang** [comment]
I feel there are two possible ways we can resolve this.

The first is to stop doing as many replacements. We originally added the replacement logic with the following use cases in mind:

* https://github.com/pytorch/pytorch/pull/112156/ - goal was to reduce the number of variables when you have `i0 = s0`, `i0 = f(s0)` or `i0 = c` where c is some constant. These replacements are always profitable to do, as they reduce the number of unbacked symbols, and once we are able to get rid of an unbacked symint you can no longer run into guard on data dependent error
* https://github.com/pytorch/pytorch/pull/112653 - the goal was to allow `i0 = i1 * 12` replacement to happen. The particular version of replacing an unbacked SymInt with a scaled version of another unbacked SymInt is safe because it preserves sizeness: if `i1 != 0, 1`, then `c * i1 != 0, 1` for all `c >= 1`.

Notice that none of the motivating cases for replacement were for `i1 = 10 - i0`. So I think everything we got working for @aakhundov will still work even if we forbid this latter replacement case.

The second is to allow refined value ranges on expressions. So for example, we might know that `10 - i0 >= 2`. This seems a bit unwieldy to me, as there is no easy way to tell when we can actually substitute in the value range for 10 - i0; you need to do expression matching.
