### ISSUE TITLE
Logging when executing fx.Interpreter

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117351]
### 🐛 Describe the bug

Something like this:

```
diff --git a/torch/fx/interpreter.py b/torch/fx/interpreter.py
index c36c5c1004b..afc963ed545 100644
--- a/torch/fx/interpreter.py
+++ b/torch/fx/interpreter.py
@@ -7,10 +7,14 @@ from ._compatibility import compatibility
 from . import config
 import torch.fx.traceback as fx_traceback
 import torch
+from torch._logging import LazyString
 from typing import Any, Dict, Iterator, List, Optional, Tuple, Union
 import inspect
 from contextlib import contextmanager
 from torch.hub import tqdm
+import logging
+
+log = logging.getLogger(__name__)
 
 __all__ = ['Interpreter', 'Transformer']
 
@@ -194,6 +198,7 @@ class Interpreter:
         Returns:
             Any: The result of executing ``n``
         """
+        log.debug("run_node %s", LazyString(lambda: n.format_node()))
         with self._set_current_node(n):
             args, kwargs = self.fetch_args_kwargs_from_env(n)
             assert isinstance(args, tuple)
```

### Versions

main

**Comment by iantmn** [comment]
Do you want to log every function?

**Comment by ezyang** [comment]
Yes

**Comment by iantmn** [comment]
I'll see what I can do

**Comment by iantmn** [comment]
How detailed should the logging be? Just when every function is called with which parameters? Or should it include more than this?

**Comment by ezyang** [comment]
My ideal print is what you would be the line of code as if the function call was generated to Python.  So, e.g., show me something like

```
repeat_interleave = torch.ops.aten.repeat_interleave.Tensor(x_1, output_size = _local_scalar_dense)
```

It is probably unwise to actually print the contents of `x_1`, since it might be quite large.

**Comment by iantmn** [comment]
```python
    def call_function(self, target : 'Target', args : Tuple[Argument, ...], kwargs : Dict[str, Any]) -> Any:
        """
        Execute a ``call_function`` node and return the result.

        Args:
            target (Target): The call target for this node. See
                `Node <https://pytorch.org/docs/master/fx.html#torch.fx.Node>`__ for
                details on semantics
            args (Tuple): Tuple of positional args for this invocation
            kwargs (Dict): Dict of keyword arguments for this invocation

        Return
            Any: The value returned by the function invocation
        """
        log.debug(f"Execute call_function node {target} with {args} and {kwargs}")
        assert not isinstance(target, str)

        # Execute the function and return the result
        return target(*args, **kwargs)
```
Right now I have these log.debug statements like `log.debug(f"Execute call_function node {target} with {args} and {kwargs}")` just like above. Is this satisfactory?

p.s. It's my first time contributing to open source, hope I'm not misunderstanding or doing to really wrong lol

**Comment by ezyang** [comment]
Well, take a look at the output; does it look good?

**Comment by iantmn** [comment]
I tried testing it, but failed. Tried running the test_torch.py file but it just says it failed to import torch. I think this is because I have to build it first, however I tried but failed.  After running `python setup.py develop`, I get this error:
```
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2 (found version "11.2") 
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:529 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID)
  cmake/public/cuda.cmake:47 (enable_language)
  cmake/Dependencies.cmake:44 (include)
  CMakeLists.txt:749 (include)
```
Probably because I don't have cuda, however I cannot seem to disable this. I can see in the development tips that it should be possible to skip cuda, but I don't know how.

**Comment by ezyang** [comment]
For something like this, you don't need to build PyTorch from source, you can use tools/nightly.py to get working binaries for your dev copy.

**Comment by iantmn** [comment]
I can't seem to either pull or checkout, It gives me a FileNotFoundError.
```
Solving conda environment
ERROR:root:Fatal exception
Traceback (most recent call last):
  File "D:\Github desktop\pytorch\tools\nightly.py", line 179, in logging_manager
    yield root_logger
  File "D:\Github desktop\pytorch\tools\nightly.py", line 691, in main
    install(
  File "D:\Github desktop\pytorch\tools\nightly.py", line 592, in install
    deps, pytorch, platform, existing_env, env_opts = conda_solve(
                                                      ^^^^^^^^^^^^
  File "D:\Github desktop\pytorch\tools\nightly.py", line 252, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Github desktop\pytorch\tools\nightly.py", line 316, in conda_solve
    p = subprocess.run(cmd, capture_output=True, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden
log file: D:\Github desktop\pytorch\nightly\log\2024-01-30_13h48m40s_e4d22e74-bf6d-11ee-8ec2-546cebc7cadf\nightly.log
```
Conda is installed and in PATH, not sure how to fix it.

**Comment by stardust-lakshmidivyajk** [comment]
Hi! Is this issue still available?
I didn’t see an open PR linked—if no one else is actively working on it, I’d love to take a look.

**Comment by jansel** [comment]
My agent was unable to reproduce this on eb80dd583a7b531e3beef0af664b40416c98e325. Reopen if you see this on the latest PyTorch nightly
