### ISSUE TITLE
Failure to compile a function that takes a remainder of randint result

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#117435]
## Issue description

As in the title.

## Code example

```python
>>> import torch
>>> @torch.compile
... def fn(n):
...     return torch.randint(10, (n,), dtype=torch.int64) % 5
... 
>>> fn(10)
```

<details>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/convert_frame.py", line 741, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/symbolic_convert.py", line 2098, in run
    super().run()
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/symbolic_convert.py", line 2216, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/output_graph.py", line 914, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/output_graph.py", line 1085, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/output_graph.py", line 1157, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/output_graph.py", line 1138, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/__init__.py", line 1714, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/compile_fx.py", line 1177, in compile_fx
    return aot_autograd(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_functorch/aot_autograd.py", line 889, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_functorch/aot_autograd.py", line 602, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/compile_fx.py", line 1105, in fw_compiler_base
    return inner_compile(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/compile_fx.py", line 317, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/compile_fx.py", line 551, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/graph.py", line 1153, in compile_to_fn
    return self.compile_to_module().call
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/graph.py", line 1105, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/codecache.py", line 1874, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_pearu/z3/cz3wydts3yfstrmc67yotclav5b57l4aqpjjn5mwlyaxlfjx3xuq.py", line 47, in <module>
    async_compile.wait(globals())
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/codecache.py", line 2454, in wait
    scope[key] = result.result()
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/codecache.py", line 2425, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/codecache.py", line 1826, in load
    compile_file(input_path, output_path, cmd)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_inductor/codecache.py", line 1779, in compile_file
    raise exc.CppCompileError(cmd, output) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CppCompileError: C++ compile error

Command:
/home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/x86_64-conda-linux-gnu-c++ /tmp/torchinductor_pearu/q7/cq7v3kvgvj3lfliputnqep3zoxr7yjde6njkazetae47fgrknbkw.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -Wno-unknown-pragmas -D_GLIBCXX_USE_CXX11_ABI=1 -I/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/include -I/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/include/torch/csrc/api/include -I/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/include/TH -I/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/include/THC -I/home/pearu/miniconda3/envs/pytorch-cuda-dev/include/python3.9 -L/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/lib -L/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib -L/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/lib -ltorch -ltorch_cpu -lgomp -ltorch_python -lc10 -mavx512f -mavx512dq -mavx512vl -mavx512bw -mfma -DCPU_CAPABILITY_AVX512 -O3 -DNDEBUG -ffast-math -fno-finite-math-only -fno-unsafe-math-optimizations -march=native -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o /tmp/torchinductor_pearu/q7/cq7v3kvgvj3lfliputnqep3zoxr7yjde6njkazetae47fgrknbkw.so
```

</details>

```
Output:
In file included from /tmp/torchinductor_pearu/q7/cq7v3kvgvj3lfliputnqep3zoxr7yjde6njkazetae47fgrknbkw.cpp:2:
/tmp/torchinductor_pearu/2s/c2sj577gdsgvjjryokkxxttxnonx35diffsknzvdsmcs6deenmwx.h: In function 'at::vec::CPU_CAPABILITY::Vectorized<float> to_float_mask(int)':
/tmp/torchinductor_pearu/2s/c2sj577gdsgvjjryokkxxttxnonx35diffsknzvdsmcs6deenmwx.h:408:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  408 |   *(uint32_t*)&mask = src ? 0xFFFFFFFF : 0;
      |    ^~~~~~~~~~~~~~~~
/tmp/torchinductor_pearu/q7/cq7v3kvgvj3lfliputnqep3zoxr7yjde6njkazetae47fgrknbkw.cpp: In function 'void kernel(const long int*, long int*)':
/tmp/torchinductor_pearu/q7/cq7v3kvgvj3lfliputnqep3zoxr7yjde6njkazetae47fgrknbkw.cpp:13:28: error: no matching function for call to 'mod(long unsigned int&, long int&)'
   13 |             auto tmp4 = mod(tmp2, tmp3);
      |                         ~~~^~~~~~~~~~~~
/tmp/torchinductor_pearu/2s/c2sj577gdsgvjjryokkxxttxnonx35diffsknzvdsmcs6deenmwx.h:147:32: note: candidate: 'template<class T> T mod(T, T)'
  147 | template <typename T> inline T mod(T a, T b) { return a % b; }
      |                                ^~~
/tmp/torchinductor_pearu/2s/c2sj577gdsgvjjryokkxxttxnonx35diffsknzvdsmcs6deenmwx.h:147:32: note:   template argument deduction/substitution failed:
/tmp/torchinductor_pearu/q7/cq7v3kvgvj3lfliputnqep3zoxr7yjde6njkazetae47fgrknbkw.cpp:13:28: note:   deduced conflicting types for parameter 'T' ('long unsigned int' and 'long int')
   13 |             auto tmp4 = mod(tmp2, tmp3);
      |                         ~~~^~~~~~~~~~~~
<snip>
```

## Discussion

While the following patch fixes the issue
```
diff --git a/torch/_inductor/codegen/cpp_prefix.h b/torch/_inductor/codegen/cpp_prefix.h
index 98e3f58245d..76562e749ca 100644
--- a/torch/_inductor/codegen/cpp_prefix.h
+++ b/torch/_inductor/codegen/cpp_prefix.h
@@ -147,6 +147,7 @@ Welford<scalar_t> welford_vec_reduce_all(Welford<at::vec::Vectorized<scalar_t>>
 template <typename T> inline T mod(T a, T b) { return a % b; }
 template <> inline float mod(float a, float b) { return std::fmod(a, b); }
 template <> inline double mod(double a, double b) { return std::fmod(a, b); }
+template <typename T, typename U> inline U mod(T a, U b) { return a % b; }
 
 template <typename scalar_t>
 inline scalar_t max_propagate_nan(scalar_t a, scalar_t b) {
```
it does not answer the question of why the usage of `randint` generates code containing variables using `uint64_t` type. There may be a deeper problem that needs to be fixed. Therefore, applying the above patch is not recommended (nor likely needed) until the cause of the real problem is discovered.

## System Info

- PyTorch version: main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by tringwald** [comment]
> it does not answer the question of why the usage of randint generates code containing variables using uint64_t type. There may be a deeper problem that needs to be fixed. Therefore, applying the above patch is not recommended (nor likely needed) until the cause of the real problem is discovered.

Well, the return type for `randint` is defined as `uint64_t` here:

https://github.com/pytorch/pytorch/blob/fc044b5cdb9725cf8c6651ed011eaa4adb2604b3/torch/_inductor/codegen/cpp_prefix.h#L182-L188

Just naively changing everything to `int64_t` makes the Python snippet above work (not sure if mathematically correct though).

**Comment by pearu** [comment]
> Just naively changing everything to `int64_t` makes the Python snippet above work (not sure if mathematically correct though).

This sounds must better to me, especially when comparing with the previous situation where randint64 returns unsigned integers that value-wise contradicts with the cases when `low` is negative.
