### ISSUE TITLE
_functional_collectives.all_to_all_single stuck when use specials output_split_sizes and input_split_sizes

### ISSUE THREAD

**Issue by yangxiaorun** [pytorch/pytorch#117486]
### 🐛 Describe the bug

_functional_collectives.all_to_all_single will stuck when use specials output_split_sizes and input_split_sizes. But , if i change output_split_sizes value or use dist.all_to_all_single, is Ok.

### Error logs

-> python fx_new.py 
input:  tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]], device='cuda:0')
input:  tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]], device='cuda:1')
output:  AsyncCollectiveTensor(tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]], device='cuda:1'))
[rank0]:[E ProcessGroupNCCL.cpp:550] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLTOALL_BASE, NumelIn=32, NumelOut=32, Timeout(ms)=600000) ran for 600216 milliseconds before timing out.
[rank0]:[E ProcessGroupNCCL.cpp:564] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E ProcessGroupNCCL.cpp:570] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E ProcessGroupNCCL.cpp:1335] [PG 0 Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLTOALL_BASE, NumelIn=32, NumelOut=32, Timeout(ms)=600000) ran for 600216 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:552 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7faf32300ce7 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7faf33490682 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x223 (0x7faf334965c3 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x122 (0x7faf334977a2 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7faf81b72e95 in /home/root/mambaforge/envs/yxr/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7faf8313a609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7faf82efb353 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLTOALL_BASE, NumelIn=32, NumelOut=32, Timeout(ms)=600000) ran for 600216 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:552 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7faf32300ce7 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7faf33490682 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x223 (0x7faf334965c3 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x122 (0x7faf334977a2 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7faf81b72e95 in /home/root/mambaforge/envs/yxr/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7faf8313a609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7faf82efb353 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1339 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7faf32300ce7 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xdce0c1 (0x7faf331e70c1 in /home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd3e95 (0x7faf81b72e95 in /home/root/mambaforge/envs/yxr/bin/../lib/libstdc++.so.6)
frame #3: <unknown function> + 0x8609 (0x7faf8313a609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #4: clone + 0x43 (0x7faf82efb353 in /lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/home/yxr/fx_new.py", line 96, in <module>
    mp()
  File "/home/yxr/fx_new.py", line 89, in mp
    torch.multiprocessing.spawn(test_alltoall_single_no_split, args=(world_size, ), nprocs=world_size, join=True)
  File "/home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 281, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 237, in start_processes
    while not context.join():
  File "/home/root/mambaforge/envs/yxr/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 169, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGABRT

### Minified repro

```
import torch
import os
import torch.distributed._functional_collectives as funcol
from typing import Any, Dict, Iterator, List, Optional, Tuple, Union
import torch.distributed as dist
from torch.distributed import distributed_c10d


def test_alltoall_single_no_split(rank, world_size):
    torch.cuda.set_device(rank)
    dist.init_process_group(backend='nccl', rank=rank, world_size=world_size)
    input = torch.ones([4, 8]).cuda() + rank
    print("input: ", input)
    output = torch.zeros([4, 8]).cuda()
    # Didn't get stuck
    # dist.all_to_all_single(output, input, output_split_sizes=[3, 1], input_split_sizes=[1, 3])
    # Didn't get stuck
    # dist.all_to_all_single(output, input)
    # Didn't get stuck
    # output = funcol.all_to_all_single(input, output_split_sizes=[2, 2], input_split_sizes=[2, 2], group=distributed_c10d._get_default_group())
    # Stucking
    output = funcol.all_to_all_single(input, output_split_sizes=[1, 3], input_split_sizes=[1, 3], group=distributed_c10d._get_default_group())
    print("output: ", output)
    dist.destroy_process_group()

def mp():
    world_size = 2
    torch.multiprocessing.spawn(test_alltoall_single_no_split, args=(world_size, ), nprocs=world_size, join=True)

if __name__ == '__main__':
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29506"
    mp()
```

### Versions

Collecting environment information...
PyTorch version: 2.3.0.dev20240110+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         1199.998
CPU max MHz:                     4000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6000.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.3.0.dev20240110+cu118
[pip3] torchaudio==2.1.2
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.26.0          py310hb13e2d6_0    conda-forge
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            2.2.0+e28a256d71          pypi_0    pypi
[conda] torch                     2.3.0.dev20240110+cu118          pypi_0    pypi
[conda] torchaudio                2.1.2               py310_cu121    pytorch
[conda] torchtriton               2.1.0                     py310    pytorch
[conda] torchvision               0.16.2              py310_cu121    pytorch
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by ezyang** [comment]
FWIW, the non-functional collective version hangs too. So it's something to do with all2all itself.

**Comment by wconstab** [comment]
@H-Huang @kwen2501 you guys know if this is outside the spec for alltoall for some reason or is a bug?

**Comment by alanhe151220037** [comment]
@wconstab 
I think it is not a bug but a wrong usecase that split_sizes mismatch on different ranks.
https://github.com/pytorch/pytorch/blob/c3780010a58a84920335296ee5f091a0db18259f/torch/csrc/cuda/nccl.cpp#L852-L904
Since `all_to_all_single` invoke `ncclsend` and `ncclrecv` to do the job, I think the cause of the stuck here is the same as the following send-recv test that numel of output is larger than input.
```
import torch
import os
import torch.distributed as dist

def test_send_recv(rank, world_size):
    torch.cuda.set_device(rank)
    dist.init_process_group(backend='nccl', rank=rank, world_size=world_size)
    if rank == 0:
        input = torch.randn(1).cuda()
        print(input)
        dist.send(input, 1)
    elif rank == 1:
        # no stuck
        # output = (torch.zeros(2)+777).cuda()
        # stuck
        output = (torch.zeros(3)+777).cuda()
        dist.recv(output, 0)
        print(output)
    dist.destroy_process_group()

def mp():
    world_size = 2
    torch.multiprocessing.spawn(test_send_recv, args=(world_size, ), nprocs=world_size, join=True)

if __name__ == '__main__':
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29506"
    mp()
```
It's interesting that when I set the numel of output to 2, it won't stuck and output[1] will be covered by 0. It may have something to do with 8 bytes atomic read/write in nccl. Similarly, the following all_to_all_single test won't stuck as well.
```
import torch
import os
import torch.distributed as dist

def test_all_to_all_single(rank, world_size):
    torch.cuda.set_device(rank)
    dist.init_process_group(backend='nccl', rank=rank, world_size=world_size)
    x_in = 1
    input = torch.ones([x_in*world_size]).cuda() + rank
    print("input: ", input.numel())

    # no stuck
    x_out = 2
    # stuck
    # x_out = 3
    y_out = 2
    z_out = 2
    output = (torch.zeros([x_out + y_out + z_out]) + 777).cuda()
    dist.all_to_all_single(output, input, output_split_sizes=[x_out, y_out, z_out], input_split_sizes=[x_in, x_in, x_in])
    print("output: ", output)
    dist.destroy_process_group()

def mp():
    world_size = 3
    torch.multiprocessing.spawn(test_all_to_all_single, args=(world_size, ), nprocs=world_size, join=True)

if __name__ == '__main__':
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29506"
    mp()
```

**Comment by wconstab** [comment]
@kwen2501 firstly are there undocumented limitations of alltoall that we should document? https://papablic.com/products/papablic-2-in-1-kid-activity-table?fbclid=IwAR2qCWa01mCE6RQlNjtcHrrkv1gAIZZl8JtON6FKenVxkn3N5D8Dg9w7TlE  -- I can't really see anything wrong with the usage in this PR from reading that doc, but I could imagine that there are corner cases we can't support.  

If that's the case we may also ensure the necessary information about the alltoall (eg. its split sizes) can be recorded in the flight recorder so there is hope of diagnosing the cause of the hang based on flight dumps.

**Comment by d4l3k** [comment]
**Category: Likely Fixed / Unreproducible**

This issue has been automatically closed. Please reopen if this is still an active issue.
