### ISSUE TITLE
Simple use of unbacked SymInt fails in CPU inductor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117461]
### 🐛 Describe the bug

```
import torch
import torch._dynamo.config

torch._dynamo.config.capture_scalar_outputs = True

@torch.compile()
def f(x):
    y = x.item()
    return torch.ones(y).sum()

f(torch.tensor(5))
```

fails with

```
Error in codegen for ComputedBuffer(name='buf1', layout=FixedLayout('cpu', torch.float32, size=[], stride=[]), data=Reduction(
  'cpu',
  torch.float32,
  def inner_fn(index, rindex):
      r0 = rindex
      tmp0 = ops.constant(1, torch.float32)
      return tmp0
  ,
  ranges=[],
  reduction_ranges=[i2],
  reduction_type=sum,
  origin_node=sum_1,
  origins={sum_1, full}
))
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/a.py", line 11, in <module>
    f(torch.tensor(5))
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 741, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2098, in run
    super().run()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2216, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/output_graph.py", line 914, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/output_graph.py", line 1085, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/output_graph.py", line 1157, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/output_graph.py", line 1138, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/ezyang/a/pytorch/torch/__init__.py", line 1714, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py", line 1177, in compile_fx
    return aot_autograd(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 889, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 602, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py", line 1105, in fw_compiler_base
    return inner_compile(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py", line 317, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py", line 551, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 1153, in compile_to_fn
    return self.compile_to_module().call
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 1101, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 1078, in codegen
    self.scheduler.codegen()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/scheduler.py", line 2265, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codegen/cpp.py", line 3250, in codegen_nodes
    cpp_kernel_proxy.codegen_nodes(nodes)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codegen/cpp.py", line 3155, in codegen_nodes
    codegen_kernel(
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codegen/cpp.py", line 3042, in codegen_kernel
    run(kernel)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codegen/cpp.py", line 3059, in run
    node.run(vars, reduction_vars)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/scheduler.py", line 733, in run
    self.codegen(index_vars)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/scheduler.py", line 755, in codegen
    self._body(*index_vars)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/ir.py", line 6615, in __call__
    result = self.root_block()
  File "/data/users/ezyang/a/pytorch/torch/_inductor/ir.py", line 6758, in __call__
    return InterpreterShim(graph, submodules).run(V.get_ops_handler())
  File "/data/users/ezyang/a/pytorch/torch/_inductor/ir.py", line 6517, in run
    return super().run(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/fx/interpreter.py", line 144, in run
    self.env[node] = self.run_node(node)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/ir.py", line 6513, in run_node
    return super().run_node(n)
  File "/data/users/ezyang/a/pytorch/torch/fx/interpreter.py", line 201, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/ezyang/a/pytorch/torch/fx/interpreter.py", line 295, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codegen/common.py", line 1207, in reduction
    return self.reduction(dtype, src_dtype, reduction_type, value)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/codegen/cpp.py", line 1974, in reduction
    assert isinstance(value, CppCSEVariable) and value.is_vec, value
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: tmp0

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by ezyang** [comment]
Also fails on CUDA inductor. Might be related to https://github.com/pytorch/pytorch/issues/117315 or even the same issue

**Comment by ezyang** [comment]
After https://github.com/pytorch/pytorch/pull/117650 it once again only fails on CPU
