### ISSUE TITLE
assert == with clone segfaults

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#117597]
### 🐛 Describe the bug

Running a small snippet comparing  a tensor and its clone with == leads to a segfault. Comparing tensors with `==` is not common and shouldn't be done (torch.equal or torch.allclose are both better) but we shouldn't segfault.  For more context, we are happy when the == is replaced with either alternative.

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (4712c7da)]$ python playground2.py 
Segmentation fault (core dumped)
```

### Minified repro

```
import torch
x = torch.randn(2, device="cuda")
assert x == x.clone()
```

### Versions

on main (4712c7dac80)

**Comment by drisspg** [comment]
can't repro

**Comment by janeyx99** [comment]
hmmm maybe my env is very broken--removing hi pri

**Comment by ezyang** [comment]
So I noticed that my PyTorch env has recently started segfaulting whenever a C++ exception is raised. I am not sure what I have to rebuild to fix it.

**Comment by janeyx99** [comment]
Ah, the backtrace does show that gcc (?) is segfaulting at raising the exception:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
linear_search_fdes (ob=ob@entry=0x7fffffffb8e0, this_fde=0x0, pc=pc@entry=0x7ffff7d5ab12 <backtrace+98>) at ../../../libgcc/unwind-dw2-fde.c:969
969     ../../../libgcc/unwind-dw2-fde.c: No such file or directory.
(gdb) bt
#0  linear_search_fdes (ob=ob@entry=0x7fffffffb8e0, this_fde=0x0, 
    pc=pc@entry=0x7ffff7d5ab12 <backtrace+98>) at ../../../libgcc/unwind-dw2-fde.c:969
#1  0x00007ffff61fa08a in find_fde_tail (dbase=8, bases=0x7fffffffba58, 
    hdr=0x7ffff7dc37bc, pc=140737351363346) at ../../../libgcc/unwind-dw2-fde-dip.c:519
#2  _Unwind_Find_FDE (pc=<optimized out>, bases=bases@entry=0x7fffffffba58)
    at ../../../libgcc/unwind-dw2-fde-dip.c:573
#3  0x00007ffff61f6bcd in uw_frame_state_for (context=context@entry=0x7fffffffb9b0, 
    fs=fs@entry=0x7fffffffbaa0) at ../../../libgcc/unwind-dw2.c:1005
#4  0x00007ffff61f7f65 in _Unwind_Backtrace (trace=0x7ffff7d5aa10 <backtrace_helper>, 
    trace_argument=0x7fffffffbbe0) at ../../../libgcc/unwind.inc:303
#5  0x00007ffff7d5ab13 in backtrace () from /lib64/libc.so.6
#6  0x00007fffefd3e157 in c10::get_backtrace[abi:cxx11](unsigned long, unsigned long, bool) (frames_to_skip=2, maximum_number_of_frames=64, skip_python_frames=true)
    at /data/users/janeyx/pytorch/c10/util/Backtrace.cpp:253
#7  0x00007fffefd42cdd in operator() (
    __closure=0x7fffefdff640 <c10::(anonymous namespace)::GetFetchStackTrace()::func>)
    at /data/users/janeyx/pytorch/c10/util/Logging.cpp:25
#8  0x00007fffefd44b52 in std::__invoke_impl<std::__cxx11::basic_string<char>, c10::(anonymous namespace)::GetFetchStackTrace()::<lambda()>&>(std::__invoke_other, struct {...} &) (
    __f=...) at /usr/include/c++/11/bits/invoke.h:61
#9  0x00007fffefd4474c in std::__invoke_r<std::__cxx11::basic_string<char>, c10::(anonymous--Type <RET> for more, q to quit, c to continue without paging--
 namespace)::GetFetchStackTrace()::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/11/bits/invoke.h:116
#10 0x00007fffefd44412 in std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >(), c10::(anonymous namespace)::GetFetchStackTrace()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/11/bits/std_function.h:291
#11 0x00007fffefd458cb in std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const (
    this=0x7fffefdff640 <c10::(anonymous namespace)::GetFetchStackTrace()::func>)
    at /usr/include/c++/11/bits/std_function.h:590
#12 0x00007fffefd43126 in c10::Error::Error (this=0x68dda80, source_location=..., msg=...)
    at /data/users/janeyx/pytorch/c10/util/Logging.cpp:83
#13 0x00007fffefd4125c in c10::detail::torchCheckFail (func=0x7fffe90415b2 "is_nonzero", 
    file=0x7fffe9041568 "/data/users/janeyx/pytorch/aten/src/ATen/native/prim_native_functions.cpp", line=17, 
    msg=0x7fffe90415c0 "Boolean value of Tensor with more than one value is ambiguous")
    at /data/users/janeyx/pytorch/c10/util/Exception.cpp:92
#14 0x00007fffe075bd67 in at::native::is_nonzero (self=...)
    at /data/users/janeyx/pytorch/aten/src/ATen/native/prim_native_functions.cpp:17
#15 0x00007fffe1f04596 in at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__is_nonzero (self=...)
```

**Comment by janeyx99** [comment]
Closing as this is likely the same error as #117645

**Comment by malfet** [comment]
@ezyang CUPTI + gold linker strikes back :)
