### ISSUE TITLE
[dynamo] Bug in supporting ellipsis class

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#117563]
### 🐛 Describe the bug

~~~
import torch
import numpy as np


@torch.compile(backend="eager", fullgraph=True)
def fn(a, ind, val):
    a[ind] = val
    return a


a = np.zeros(5)
fn(a, np.s_[...], np.ones(5))
~~~

### Error logs

~~~
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR] Error while creating guard:
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR] Name: "L['ind']"
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR]     Source: local
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR]     Create Function: CONSTANT_MATCH
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR]     Guard Types: None
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR]     Code List: None
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR]     Object Weakref: None
[2024-01-16 10:47:43,983] [0/0] torch._guards: [ERROR]     Guarded Class Weakref: None
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR] Created at:
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]   File "/data/users/anijain/pytorch/torch/_dynamo/variables/lazy.py", line 22, in realize
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]     self.vt = VariableBuilder(tx, self.source)(self.value)
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]   File "/data/users/anijain/pytorch/torch/_dynamo/variables/builder.py", line 244, in __call__
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]     vt = self._wrap(value)
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]   File "/data/users/anijain/pytorch/torch/_dynamo/variables/builder.py", line 458, in _wrap
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]     return self.wrap_literal(value)
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]   File "/data/users/anijain/pytorch/torch/_dynamo/variables/builder.py", line 937, in wrap_literal
[2024-01-16 10:47:43,984] [0/0] torch._guards: [ERROR]     self.install_guards(GuardBuilder.CONSTANT_MATCH)
Traceback (most recent call last):
  File "/data/users/anijain/pytorch/examples/el.py", line 12, in <module>
    fn(a, np.s_[...], np.ones(5))
  File "/data/users/anijain/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/data/users/anijain/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/anijain/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 623, in compile_inner
    check_fn = CheckFunctionManager(
  File "/data/users/anijain/pytorch/torch/_dynamo/guards.py", line 996, in __init__
    guard.create(builder)
  File "/data/users/anijain/pytorch/torch/_guards.py", line 246, in create
    return self.create_fn(builder, self)
  File "/data/users/anijain/pytorch/torch/_dynamo/guards.py", line 444, in CONSTANT_MATCH
    self.EQUALS_MATCH(guard)
  File "/data/users/anijain/pytorch/torch/_dynamo/guards.py", line 401, in EQUALS_MATCH
    assert istype(
AssertionError: Unexpected type <class 'ellipsis'>, not in (<class 'float'>, <class 'bytes'>, <class 'list'>, <class 'numpy.uint64'>, <class 'set'>, <class 'numpy.int64'>, <class 'tuple'>, <class 'NoneType'>, <class 'torch.dtype'>, <class 'numpy.float16'>, <class 'numpy.uint8'>, <class 'numpy.int8'>, <class 'type'>, <class 'int'>, <class 'torch.memory_format'>, <class 'str'>, <class 'torch.Size'>, <class 'numpy.float64'>, <class 'numpy.uint32'>, <class 'numpy.int32'>, <class 'slice'>, <class 'range'>, <class 'torch.device'>, <class 'frozenset'>, <class 'bool'>, <class 'code'>, <class 'numpy.float32'>, <class 'numpy.uint16'>, <class 'numpy.int16'>, <class 'torch.layout'>)

~~~

### Minified repro

N/A

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by laithsakka** [comment]
this sounds also like something we shall enable after this
```
    @xfailIfTorchDynamo  # numpy ndarrays do not have `.tensor` attribute
    def test_ellipsis_index_2(self):
        a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        assert_(a[...] is not a)
        assert_equal(a[...], a)
        # `a[...]` was `a` in numpy <1.9.
        assert_(a[...].tensor._base is a.tensor)
```

**Comment by laithsakka** [comment]
this is working fine
```

OK
(base) [lsakka@devvm4561.ash0 /data/users/lsakka/pytorch (elipses)]$  TORCH_LOGS="graph, aot, output_code" python3 test/dynamo/test_functions.py  -k test_elipsis
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] TRACED GRAPH
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]  __compiled_fn_0 /data/users/lsakka/pytorch/torch/fx/_lazy_graph_module.py opcode         name                 target                                   args                      kwargs
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] -------------  -------------------  ---------------------------------------  ------------------------  --------
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] placeholder    l_a_                 L_a_                                     ()                        {}
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] placeholder    l_val_               L_val_                                   ()                        {}
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] call_function  wrapped___setitem__  <Wrapped method <original __setitem__>>  (l_a_, Ellipsis, l_val_)  {}
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] output         output               output                                   ((),)                     {}
[2024-01-30 18:19:55,804] [0/0] torch._dynamo.output_graph.__graph: [DEBUG] 
stats [('calls_captured', 1), ('unique_graphs', 1)]
.
----------------------------------------------------------------------
Ran 1 test in 2.945s

OK
```

**Comment by laithsakka** [comment]
re-opened to confirm first with @anijain2305 that its resolved.

**Comment by laithsakka** [comment]
created a diff that add an explicit test for the issue above.

**Comment by anijain2305** [comment]
Yes, https://github.com/pytorch/pytorch/pull/117819 fixed it.
