### ISSUE TITLE
[dynamo] Support `callable` builtin on callable classes

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#117556]
### 🐛 Describe the bug

~~~
import torch

# A callable class to have a callable UserDefinedObjectVariable
class Nothing:
    def __call__():
        pass

@torch.compile(backend="eager", fullgraph=True)
def fn(x, args):
    if callable(args[0]):
        return torch.sin(x)
    return torch.cos(x)

fn(torch.randn(4), [Nothing()])
~~~

### Error logs

~~~
Traceback (most recent call last):
  File "/data/users/anijain/pytorch/examples/callable.py", line 17, in <module>
    fn(torch.randn(4), [Nothing()])
  File "/data/users/anijain/pytorch/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/data/users/anijain/pytorch/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 384, in _convert_frame_assert
    return _compile(
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 643, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/anijain/pytorch/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 524, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/anijain/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/data/users/anijain/pytorch/torch/_dynamo/convert_frame.py", line 489, in transform
    tracer.run()
  File "/data/users/anijain/pytorch/torch/_dynamo/symbolic_convert.py", line 2098, in run
    super().run()
  File "/data/users/anijain/pytorch/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/data/users/anijain/pytorch/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/anijain/pytorch/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/data/users/anijain/pytorch/torch/_dynamo/symbolic_convert.py", line 1190, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/anijain/pytorch/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/anijain/pytorch/torch/_dynamo/variables/builtin.py", line 668, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/anijain/pytorch/torch/_dynamo/variables/base.py", line 321, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "/data/users/anijain/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(callable) [UserDefinedObjectVariable(Nothing)] {}
~~~

### Minified repro

N/A

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by laithsakka** [comment]
I will take this one
