### ISSUE TITLE
[ONNX] torch.onnx.dynamo_export raises "Unknown call_function target: cond"

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#117655]
### 🐛 Describe the bug

`functorch.experimental.control_flow.cond` is not yet supported by `torch.onnx.dynamo_export`

```python
import torch

from functorch.experimental.control_flow import cond


class MySubModule(torch.nn.Module):
    def foo(self, x):
        return x.cos()

    def forward(self, x):
        return self.foo(x)


class CondBranchClassMethod(torch.nn.Module):
    """
    The branch functions (`true_fn` and `false_fn`) passed to cond() must follow these rules:
      - both branches must take the same args, which must also match the branch args passed to cond.
      - both branches must return a single tensor
      - returned tensor must have the same tensor metadata, e.g. shape and dtype
      - branch function can be free function, nested function, lambda, class methods
      - branch function can not have closure variables
      - no inplace mutations on inputs or global variables


    This example demonstrates using class method in cond().

    NOTE: If the `pred` is test on a dim with batch size < 2, it will be specialized.
    """

    def __init__(self):
        super().__init__()
        self.subm = MySubModule()

    def bar(self, x):
        return x.sin()

    def forward(self, x):
        return cond(x.shape[0] <= 2, self.subm.forward, self.bar, [x])

model = CondBranchClassMethod()
input = torch.randn(5)

# exported_program = torch.export.export(model, args=(input,))(input)  # works
onnx_program = torch.onnx.dynamo_export(model, input)  # Unknown call_function target: cond
```

Error:

```bash
Traceback (most recent call last):
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1439, in dynamo_export
    ).export()
      ^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1182, in export
    graph_module = self.options.fx_tracer.generate_fx(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 232, in generate_fx
    return self.pre_export_passes(options, model, graph_module, updated_model_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(torch.onnx._internal.fx.dynamo_graph_extractor.DynamoExport.pre_export_passes) at 0x7fb951ae0fe0>", line 93, in pre_export_passes
  File "/opt/pytorch/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 242, in pre_export_passes
    return exporter.common_pre_export_passes(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/exporter.py", line 1495, in common_pre_export_passes
    ).analyze(infra.levels.ERROR)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 60, in analyze
    self.onnxfunction_dispatcher._get_aten_name(
  File "<@beartype(torch.onnx._internal.fx.onnxfunction_dispatcher.OnnxFunctionDispatcher._get_aten_name) at 0x7fb951cb0720>", line 54, in _get_aten_name
  File "/opt/pytorch/torch/onnx/_internal/fx/onnxfunction_dispatcher.py", line 352, in _get_aten_name
    raise diagnostics.RuntimeErrorWithDiagnostic(diagnostic)
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unknown call_function target: cond
```

### Versions

pytorch main branch

**Comment by PierreCarceller** [comment]
Currently facing the same error. Any Update ?

**Comment by hann-wang** [comment]
It seems that `torch.cond` is already supported by `torch.export.export` but not `torch.onnx.dynamo_export`

**Comment by justinchuby** [comment]
# PyTorch ONNX Conversion Error Report

```
✅ Obtain model graph with `torch.export.export`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

## Error message

```pytb
Traceback (most recent call last):

  File "/home/justinchu/dev/torch-onnx/src/torch_onnx/_core.py", line 512, in _add_nodes
    _handle_call_function_node_with_lowering(

  File "/home/justinchu/dev/torch-onnx/src/torch_onnx/_core.py", line 385, in _handle_call_function_node_with_lowering
    raise errors.DispatchError(

torch_onnx.errors.DispatchError: No ONNX function found for <torch._ops.HigherOrderOperator object at 0x738d17e1b290>. Failure message: No decompositions registered for the real-valued input


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/justinchu/dev/torch-onnx/src/torch_onnx/_core.py", line 1000, in export
    ir_model = exported_program_to_ir(program, registry=registry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/dev/torch-onnx/src/torch_onnx/_core.py", line 691, in exported_program_to_ir
    values = _add_nodes(exported_program, model, lower=lower, registry=registry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/dev/torch-onnx/src/torch_onnx/_core.py", line 524, in _add_nodes
    raise errors.OnnxConversionError(

torch_onnx.errors.OnnxConversionError: Error when translating node %conditional : [num_users=1] = call_function[target=torch.ops.higher_order.cond](args = (False, %true_graph_0, %false_graph_0, [%arg0_1]), kwargs = {}). See the stack trace for more information.
```

## Exported program

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, arg0_1: "f32[5]"):
            # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_higher_order_ops/cond.py:107 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
            true_graph_0 = self.true_graph_0
            false_graph_0 = self.false_graph_0
            conditional = torch.ops.higher_order.cond(False, true_graph_0, false_graph_0, [arg0_1]);  true_graph_0 = false_graph_0 = arg0_1 = None
            getitem: "f32[5]" = conditional[0];  conditional = None
            return (getitem,)
            
        class <lambda>(torch.nn.Module):
            def forward(self, arg0_1: "f32[5]"):
                # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_higher_order_ops/cond.py:107 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
                cos: "f32[5]" = torch.ops.aten.cos.default(arg0_1);  arg0_1 = None
                return (cos,)
                
        class <lambda>(torch.nn.Module):
            def forward(self, arg0_1: "f32[5]"):
                # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_higher_order_ops/cond.py:107 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
                sin: "f32[5]" = torch.ops.aten.sin.default(arg0_1);  arg0_1 = None
                return (sin,)
                
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg0_1'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='getitem'), target=None)])
Range constraints: {}

```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 0 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `arg0_1`: `TensorMetadata(shape=torch.Size([5]), dtype=torch.float32, requires_grad=False, stride=(1,), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `getitem`: `TensorMetadata(shape=torch.Size([5]), dtype=torch.float32, requires_grad=False, stride=(1,), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

The FX graph has 6 nodes in total. Number of FX nodes per op:
- `placeholder`: 1
- `get_attr`: 2
- `call_function`: 2
- `output`: 1


Of the call_function nodes, the counts of operators used are:

- `cond`: 1
- `<built-in function getitem>`: 1

## ONNX Conversion Information

The model contains operators the dispatcher could not find registered ONNX decompositions for. This may be due to missing implementations, decompositions not registered correctly, or a bug in the dispatcher.

Errors grouped by operator:

- `cond`:     No decompositions registered for the real-valued input. Example node: `%conditional : [num_users=1] = call_function[target=torch.ops.higher_order.cond](args = (False, %true_graph_0, %false_graph_0, [%arg0_1]), kwargs = {})`. All nodes: `[conditional]`

## Profiling result

```

  _     ._   __/__   _ _  _  _ _/_   Recorded: 00:11:34  Samples:  1200
 /_//_/// /_\ / //_// / //_'/ //     Duration: 1.564     CPU time: 1.557
/   _/                      v4.6.2

Program: /home/justinchu/dev/torch-onnx/tests/conditional.py

1.563 export  torch_onnx/_core.py:820
├─ 0.822 export  torch/export/__init__.py:73
│     [204 frames hidden]  torch, contextlib, importlib, concurr...
└─ 0.725 exported_program_to_ir  torch_onnx/_core.py:635
   ├─ 0.639 OnnxRegistry.from_torchlib  torch_onnx/_registration.py:133
   │  ├─ 0.366 TracedOnnxFunction.function_ir  ../../onnxscript/onnxscript/values.py:588
   │  │  ├─ 0.293 get_src_and_ast  ../../onnxscript/onnxscript/_internal/ast_utils.py:16
   │  │  │  ├─ 0.187 parse  ast.py:33
   │  │  │  │     [3 frames hidden]  ast, <built-in>
   │  │  │  └─ 0.103 getsource  inspect.py:1252
   │  │  │        [6 frames hidden]  inspect, tokenize, <built-in>
   │  │  └─ 0.065 Converter.translate_function_signature  ../../onnxscript/onnxscript/converter.py:1463
   │  │     └─ 0.065 Converter._translate_function_signature_common  ../../onnxscript/onnxscript/converter.py:1378
   │  │        └─ 0.028 is_valid_type  ../../onnxscript/onnxscript/type_annotation.py:172
   │  │           └─ 0.027 is_value_type  ../../onnxscript/onnxscript/type_annotation.py:131
   │  ├─ 0.164 _get_overload  torch_onnx/_registration.py:61
   │  │  └─ 0.157 <module>  torchvision/__init__.py:1
   │  │        [13 frames hidden]  torchvision, torch, inspect, <frozen ...
   │  └─ 0.099 OpSignature.from_function  torch_onnx/_schemas.py:431
   │     ├─ 0.032 get_type_hints  typing.py:2319
   │     └─ 0.032 _get_allowed_types_from_type_annotation  torch_onnx/_schemas.py:271
   │        └─ 0.023 _get_allowed_types_from_type_annotation  torch_onnx/_schemas.py:271
   │           └─ 0.017 _get_allowed_types_from_type_annotation  torch_onnx/_schemas.py:271
   ├─ 0.062 wrapper  torch/export/exported_program.py:80
   │     [64 frames hidden]  torch, <string>
   └─ 0.018 create_onnx_friendly_decomposition_table  torch_onnx/_decomp.py:39
      └─ 0.017 _get_registered_ops  torch_onnx/_decomp.py:12

```

**Comment by justinchuby** [comment]
I realized we can have nested subgraphs:


```
import torch

class Submodule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # Nested weight
        self.weight = torch.nn.Parameter(torch.tensor([100.0]))
    def forward(self, x):
        def true_fn(x):
            return x * self.weight

        def false_fn(x):
            return x / self.weight

        y = torch.cond(x.sum() <= 0, true_fn, false_fn, [x])
        return y

class CondModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.submodule = Submodule()
        self.weight = torch.nn.Parameter(torch.tensor([42.0]))

    def forward(self, x):
        def true_fn(x):
            return self.submodule(x)

        def false_fn(x):
            return x - self.weight

        y = torch.cond(x.sum() > 0, true_fn, false_fn, [x])
        return y

x = torch.tensor([1, 2])
model = CondModel()
ep = torch.export.export(model, (x,), strict=False)
print(ep)
```

This makes function managing harder. We need to create some sort of name scoping rules

**Comment by justinchuby** [comment]
```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, p_weight: "f32[1]", p_submodule_weight: "f32[1]", x: "i64[2]"):
             # File: /Users/justinc/Documents/GitHub/pytorch/test/onnx/exporter/cond.py:31 in forward, code: y = torch.cond(x.sum() > 0, true_fn, false_fn, [x])
            sum_1: "i64[]" = torch.ops.aten.sum.default(x)
            gt: "b8[]" = torch.ops.aten.gt.Scalar(sum_1, 0);  sum_1 = None
            
             # File: <eval_with_key>.53:11 in forward, code: cond = torch.ops.higher_order.cond(l_args_0_, cond_true_1, cond_false_1, [l_args_3_0_, l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight_, l_args_2_closure_0_cell_contents_get_base_parameters_weight_]);  l_args_0_ = cond_true_1 = cond_false_1 = l_args_3_0_ = l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight_ = l_args_2_closure_0_cell_contents_get_base_parameters_weight_ = None
            true_graph_0 = self.true_graph_0
            false_graph_0 = self.false_graph_0
            cond = torch.ops.higher_order.cond(gt, true_graph_0, false_graph_0, [x, p_submodule_weight, p_weight]);  gt = true_graph_0 = false_graph_0 = x = p_submodule_weight = p_weight = None
            getitem: "f32[2]" = cond[0];  cond = None
            return (getitem,)
            
        class true_graph_0(torch.nn.Module):
            def forward(self, x: "i64[2]", p_submodule_weight: "f32[1]", p_weight: "f32[1]"):
                 # File: <eval_with_key>.50:6 in forward, code: sum_1 = l_args_3_0__1.sum()
                sum_1: "i64[]" = torch.ops.aten.sum.default(x)
                
                 # File: <eval_with_key>.50:7 in forward, code: le = sum_1.le(0);  sum_1 = None
                le: "b8[]" = torch.ops.aten.le.Scalar(sum_1, 0);  sum_1 = None
                
                 # File: <eval_with_key>.50:10 in forward, code: cond = torch.ops.higher_order.cond(le, cond_true_0, cond_false_0, [l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight__true_branch, l_args_3_0__1]);  le = cond_true_0 = cond_false_0 = l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight__true_branch = l_args_3_0__1 = None
                true_graph_0 = self.true_graph_0
                false_graph_0 = self.false_graph_0
                cond = torch.ops.higher_order.cond(le, true_graph_0, false_graph_0, [p_submodule_weight, x]);  le = true_graph_0 = false_graph_0 = p_submodule_weight = x = None
                getitem: "f32[2]" = cond[0];  cond = None
                return (getitem,)
                
            class true_graph_0(torch.nn.Module):
                def forward(self, p_submodule_weight: "f32[1]", x: "i64[2]"):
                     # File: <eval_with_key>.48:7 in forward, code: mul = l_args_3_0__1.mul(l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight__1);  l_args_3_0__1 = l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight__1 = None
                    mul: "f32[2]" = torch.ops.aten.mul.Tensor(x, p_submodule_weight);  x = p_submodule_weight = None
                    return (mul,)
                    
            class false_graph_0(torch.nn.Module):
                def forward(self, p_submodule_weight: "f32[1]", x: "i64[2]"):
                     # File: <eval_with_key>.49:7 in forward, code: div = l_args_3_0__1.div(l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight__1);  l_args_3_0__1 = l_args_1_closure_0_cell_contents_get_base_modules_submodule_parameters_weight__1 = None
                    div: "f32[2]" = torch.ops.aten.div.Tensor(x, p_submodule_weight);  x = p_submodule_weight = None
                    return (div,)
                    
        class false_graph_0(torch.nn.Module):
            def forward(self, x: "i64[2]", p_submodule_weight: "f32[1]", p_weight: "f32[1]"):
                 # File: <eval_with_key>.51:6 in forward, code: sub = l_args_3_0__1.sub(l_args_2_closure_0_cell_contents_get_base_parameters_weight__false_branch);  l_args_3_0__1 = l_args_2_closure_0_cell_contents_get_base_parameters_weight__false_branch = None
                sub: "f32[2]" = torch.ops.aten.sub.Tensor(x, p_weight);  x = p_weight = None
                return (sub,)
                
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='p_weight'), target='weight', persistent=None), InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='p_submodule_weight'), target='submodule.weight', persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='getitem'), target=None)])
Range constraints: {}
```

**Comment by justinchuby** [comment]
```python
onnx_program = torch.onnx.export(model, (input,), dynamo=True)
```

```
ONNXProgram(
    model=
        <
            ir_version=10,
            opset_imports={'pkg.onnxscript.torch_lib.common': 1, '': 18},
            producer_name='pytorch',
            producer_version='2.6.0a0+gita847790',
            domain=None,
            model_version=None,
        >
        graph(
            name=main_graph,
            inputs=(
                %"x"<FLOAT,[5]>
            ),
            outputs=(
                %"sin"<FLOAT,[5]>
            ),
        ) {
            0 |  # node_Sin_0
                 %"sin"<FLOAT,[5]> ⬅️ ::Sin(%"x")
            return %"sin"<FLOAT,[5]>
        }

        <
            opset_imports={'': 18},
        >
        def pkg.onnxscript.torch_lib.common::Rank(
            inputs=(
                %"input"<?,?>
            ),
            outputs=(
                %"return_val"<?,?>
            ),
        ) {
            0 |  # n0
                 %"tmp"<?,?> ⬅️ ::Shape(%"input")
            1 |  # n1
                 %"return_val"<?,?> ⬅️ ::Size(%"tmp")
            return %"return_val"<?,?>
        }

        <
            opset_imports={'': 18},
        >
        def pkg.onnxscript.torch_lib.common::IsScalar(
            inputs=(
                %"input"<?,?>
            ),
            outputs=(
                %"return_val"<?,?>
            ),
        ) {
            0 |  # n0
                 %"tmp"<?,?> ⬅️ ::Shape(%"input")
            1 |  # n1
                 %"tmp_0"<?,?> ⬅️ ::Size(%"tmp")
            2 |  # n2
                 %"tmp_1"<?,?> ⬅️ ::Constant() {value_int=0}
            3 |  # n3
                 %"return_val"<?,?> ⬅️ ::Equal(%"tmp_0", %"tmp_1")
            return %"return_val"<?,?>
        }
    ,
    exported_program=
        ExportedProgram:
            class GraphModule(torch.nn.Module):
                def forward(self, x: "f32[5]"):
                     # File: /workspace/pytorch/cond.py:38 in forward, code: return cond(x.shape[0] <= 2, self.subm.forward, self.bar, [x])
                    sin: "f32[5]" = torch.ops.aten.sin.default(x);  x = None
                    return (sin,)
            
        Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='sin'), target=None)])
        Range constraints: {}

)
```
