### ISSUE TITLE
Supporting custom attributes with `__torch_function__` tensor subclasses

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#117806]
### 🚀 The feature, motivation and pitch

Currently we only support accessing attributes that are defined on the base `torch._tensor` implementation. Since some torch function subclasses define custom attributes it's a good idea to support accessing these as well. 

See https://github.com/pytorch/pytorch/blob/a468b9fbdf75b2da128e5fac4284ebbb981cd31a/torch/_dynamo/variables/torch_function.py#L180C1-L215C1 for the current implementation. 

Ideally we should support two cases 1) if a user defines a custom attribute that does *not* invoke `torch_function` on access (this is the default for an arbitrary attribute) and 2) if the user explicitly adds [this decorator](https://github.com/pytorch/pytorch/blob/a468b9fbdf75b2da128e5fac4284ebbb981cd31a/torch/_tensor.py#L31) to an attribute, we should support tracing through it and dispatching appropriately or shortcutting to the dynamo handling of it to be consistent. 

cc @hameerabbasi @rgommers @peterbell10 @ezyang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by Potato-Cracker** [comment]
Hi,
I would like to work on this issue. I want to become a long term PyTorch contributor, but I have been struggling to understand the code base. I would grateful if someone, patient enough to answer my trivial doubts, could assist me in the process of solving this issue and help me merge a PR.

**Comment by Potato-Cracker** [comment]
I've been trying to trigger these errors but have been unsuccessful so far. It would be helpful if I got some code to trigger these error messages-
```Accessing {name} on a tensor subclass with a __torch_function__ override is not supported"```
and
```Accessing overridden method/attribute {name} on a tensor subclass with a __torch_function__ override is not supported```
I hope I am going in the right direction. If not it will help to have the expected error message and some code that triggers it.

**Comment by mlazos** [comment]
Hi @Potato-Cracker, thanks for taking a look at this. We have a bunch of tests defined here: https://github.com/pytorch/pytorch/blob/a27a6e8cf123cf9517ccada63e249f73ab981845/test/dynamo/test_subclasses.py#L384

**Comment by Potato-Cracker** [comment]
I ran ```python test/dynamo/test_subclasses.py``` and 4 test cases related to attribute overriding failed. So, I should be good if I change ```var_getattr``` to make sure these test cases past? 

Also, I am not able to find the relevant test cases for this decorator:[_handle_torch_function_and_wrap_type_error_to_not_implemented](https://github.com/pytorch/pytorch/blob/a468b9fbdf75b2da128e5fac4284ebbb981cd31a/torch/_tensor.py#L31). 

I am also trying to find out which parts of dynamo deal with tracing/dispatching/shortcutting?
Thanks.

**Comment by mlazos** [comment]
Sorry I made a mistake with which decorator you should use, it should be this one: 
https://github.com/pytorch/pytorch/blob/f129e3fe034c0052d1d45856ac10fc4b3a1e9700/torch/overrides.py#L1463

At a high level, dynamo is performing the tracing. The var_getattr function you're looking at traces getattr calls on the python variable. I actually think we whould be able to trace that decorator like normal python code and not need to handle any shortcutting. It might be worth writing a test which uses that decorator and see if we can pass it right now as is after you remove the restrictions in var_getattr. Are you on slack btw? It might be easier to discuss this in person.

**Comment by Potato-Cracker** [comment]
I am ready to discuss this in person. I have an account in slack but I never used it though.

**Comment by mlazos** [comment]
> I am ready to discuss this in person. I have an account in slack but I never used it though.

Okay, can you message me in slack and I'll setup a meeting tomorrow

**Comment by Potato-Cracker** [comment]
I don't think I am on the PyTorch Slack channel. I am new to Slack so I don't know how to use it.

**Comment by mlazos** [comment]
If you'd like, can you send me your email on linkedin? I found you there, you can also post it here if you'd like and I can add you to the channel, wasn't sure if you want it in a public place.

**Comment by Potato-Cracker** [comment]
Hi, I sent my email to you on linkedin.

Regarding the issue-
I remove the restrictions by commenting these lines in var_getattr-
```   
 def var_getattr(self, tx, name):
        # [Note: __torch_function__] We currently only support attributes that are defined on
        # base tensors, custom attribute accesses will graph break.
        import torch
        from .builder import SourcelessBuilder

        # if name in banned_attrs or not hasattr(torch.Tensor, name):
        #     unimplemented(
        #         f"Accessing {name} on a tensor subclass with a __torch_function__ override is not supported"
        #     )

        # if _is_attr_overidden(tx, self, name):
        #     unimplemented(
        #         f"Accessing overridden method/attribute {name} on a tensor"
        #         " subclass with a __torch_function__ override is not supported"
        #     )

        if tx.output.torch_function_enabled:
            if self.source:
                install_guard(
                    AttrSource(AttrSource(self.source, "__class__"), name).make_guard(
                        GuardBuilder.FUNCTION_MATCH
                    )
                )
            get_fn = SourcelessBuilder()(tx, getattr(torch.Tensor, name).__get__)

            return self.call_torch_function(
                tx,
                get_fn,
                TupleVariable([self.class_type_var(tx)]),
                [self],
                {},
            )
        else:
            return super().var_getattr(tx, name)
```
Now I modified the ```test_user_overidden_attr_unsupported``` in  [pytorch/test/dynamo/test_subclasses.py](https://github.com/pytorch/pytorch/blob/a27a6e8cf123cf9517ccada63e249f73ab981845/test/dynamo/test_subclasses.py#L384) and made a test case like this-
```
import torch
import torch.overrides
import unittest

class LocalSubclass(torch.Tensor):
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        return super().__torch_function__(func, types, args, kwargs)

    @staticmethod
    def ndim_dispatcher(instance):
        return (instance,)

    @property
    @torch.overrides.wrap_torch_function(ndim_dispatcher)
    def ndim(self):
        return 10

@torch.compile(backend="eager", fullgraph=True)
def fn(x):
    return x.ndim

class TestOverrideAttrWithTorchFunction(unittest.TestCase):
    def test_override_attr_with_torch_function(self):
        x = torch.ones(2, 2).as_subclass(LocalSubclass)
        result = fn(x)
        self.assertEqual(result, 10, "The __torch_function__ dispatch did not work as expected for the custom attribute")

if __name__ == '__main__':
    unittest.main()

```
This test case does not work with the ```wrap_torch_function``` decorator and it gives me this error-

```
Traceback (most recent call last):
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/test4.py", line 28, in test_override_attr_with_torch_function
    result = fn(x)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/eval_frame.py", line 437, in _fn
    return fn(*args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/eval_frame.py", line 601, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 386, in _convert_frame_assert
    return _compile(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/utils.py", line 248, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 526, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 491, in transform
    tracer.run()
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2124, in run
    super().run()
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 787, in run
    and self.step()
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 750, in step
    getattr(self, inst.opname)(inst)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 1288, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/builtin.py", line 687, in call_function
    result = handler(tx, *args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/builtin.py", line 1280, in call_getattr
    return obj.var_getattr(tx, name)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/user_defined.py", line 722, in var_getattr
    ).call_function(tx, [], {})
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/functions.py", line 276, in call_function
    return super().call_function(tx, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/functions.py", line 84, in call_function
    return tx.inline_user_function_return(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 657, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2260, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2299, in inline_call_
    result = InliningInstructionTranslator.check_inlineable(func)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2278, in check_inlineable
    unimplemented(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/exc.py", line 190, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: 'inline in skipfiles: LocalSubclass.ndim | wrapped /media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/overrides.py, skipped according skipfiles.SKIP_DIRS'

from user code:
   File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/test4.py", line 23, in fn
    return x.ndim

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


----------------------------------------------------------------------
Ran 1 test in 0.090s

FAILED (errors=1)
```

However, I think I converted the attribute to a property here I think. If I am right the github issue just focuses on overriding attributes but not properties and method. I might have to make a test case that just deals with overriding the attribute.

**Comment by mlazos** [comment]
We discussed offline on the basic approach:

Currently with testing a custom attribute (the test looks at NDim) this will hit skipfiles because ndim is defined on the base tensor. We should try an attribute which is not defined on base tensor (ie try an attribute named "a" or something)

Once we can properly read/write these, the next steps are properties/methods with/without the [decorator](https://github.com/pytorch/pytorch/blob/f129e3fe034c0052d1d45856ac10fc4b3a1e9700/torch/overrides.py#L1463) to make sure dynamo can properly trace the decorator.

**Comment by Potato-Cracker** [comment]
Just changed ndim to 'a'-
```
import torch
import torch.overrides
import unittest

class LocalSubclass(torch.Tensor):
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        return super().__torch_function__(func, types, args, kwargs)

    @staticmethod
    def a_dispatcher(instance):
        return (instance,)

    @property
    @torch.overrides.wrap_torch_function(a_dispatcher)
    def a(self):
        return 10

@torch.compile(backend="eager", fullgraph=True)
def fn(x):
    return x.a

class TestOverrideAttrWithTorchFunction(unittest.TestCase):
    def test_override_attr_with_torch_function(self):
        x = torch.ones(2, 2).as_subclass(LocalSubclass)
        result = fn(x)
        self.assertEqual(result, 10, "The __torch_function__ dispatch did not work as expected for the custom attribute")

if __name__ == '__main__':
    unittest.main()

```
Not sure why I am still getting the skipfiles error-
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/test6.py", line 28, in test_override_attr_with_torch_function
    result = fn(x)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/eval_frame.py", line 437, in _fn
    return fn(*args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/eval_frame.py", line 601, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 386, in _convert_frame_assert
    return _compile(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/utils.py", line 248, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 526, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/convert_frame.py", line 491, in transform
    tracer.run()
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2124, in run
    super().run()
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 787, in run
    and self.step()
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 750, in step
    getattr(self, inst.opname)(inst)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 1288, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/builtin.py", line 687, in call_function
    result = handler(tx, *args, **kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/builtin.py", line 1280, in call_getattr
    return obj.var_getattr(tx, name)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/user_defined.py", line 722, in var_getattr
    ).call_function(tx, [], {})
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/functions.py", line 276, in call_function
    return super().call_function(tx, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/variables/functions.py", line 84, in call_function
    return tx.inline_user_function_return(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 657, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2260, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2299, in inline_call_
    result = InliningInstructionTranslator.check_inlineable(func)
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/symbolic_convert.py", line 2278, in check_inlineable
    unimplemented(
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/_dynamo/exc.py", line 190, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: 'inline in skipfiles: LocalSubclass.a | wrapped /media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/torch/overrides.py, skipped according skipfiles.SKIP_DIRS'

from user code:
   File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/Dev2/pytorch/test6.py", line 23, in fn
    return x.a

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


----------------------------------------------------------------------
Ran 1 test in 0.277s
```

**Comment by Potato-Cracker** [comment]
I also don't understand why I get the same message whether I set backend to "inductor" or "eager" 
```
You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by mlazos** [comment]
For properties it won't get invoked, we'll trace through the property accessor, you can add torch.overrides https://github.com/pytorch/pytorch/blob/278a0e1600cf8c5c49ef03fdda99e8dc4c42e16c/torch/_dynamo/trace_rules.py#L3157 to remove the skip error cc @yanboliang is this correct?

**Comment by Potato-Cracker** [comment]
I think adding torch.overrides helped bypass the skip files.
```
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/pytorch/torch/_dynamo/variables/base.py", line 371, in call_method
    raise unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/pytorch/torch/_dynamo/exc.py", line 190, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(staticmethod) __call__ [UserDefinedObjectVariable(LocalSubclass)] {}

from user code:
   File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/pytorch/test6.py", line 23, in fn
    return x.a
  File "/media/valgrant/Windows-SSD/Users/mahes/Desktop/Projects/Fun/pytorch/torch/overrides.py", line 1490, in wrapped
    relevant_args = dispatcher(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED (errors=1)
```
However, I don't quite understand what this error means.

**Comment by StrongerXi** [comment]
> 1) if a user defines a custom attribute that does not invoke torch_function on access (this is the default for an arbitrary attribute)

We support this to some extent for practical tracing: https://github.com/pytorch/pytorch/pull/149484/files#diff-b9390381059781e43ca874273a63ac3525d990c9c4d6bb048ef621bbf2a768a2R674-R690.

We can expand the types of supported attributes as needed. Eventually I'm _really_ hoping to unify this with all the logic in `UserDefinedObjectVariable.var_getattr`, because otherwise we'd just keep duplicating them for these tensor variables (and at more places).

 2) if the user explicitly adds [this decorator](https://github.com/pytorch/pytorch/blob/a468b9fbdf75b2da128e5fac4284ebbb981cd31a/torch/_tensor.py#L31) to an attribute, we should support tracing through it and dispatching appropriately or shortcutting to the dynamo handling of it to be consistent.

This one is a little tricky, I'll have to spend more time on it. What I've found is that we typically don't trace into `override.py` (e.g., we emulate the torch_function dispatch), but in this case we'd somehow force Dynamo to trace into `override.py`, which causes behavior divergence and things break...
