### ISSUE TITLE
torch.nn.functional.linear fails `test_conj_view`/`test_neg_view`

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#117854]
### 🐛 Describe the bug

If something like
```
input_tensor = create_tensor(2, 1, 2, 1, 2)
weight = create_tensor(4, 2)
yield SampleInput(input_tensor, weight)
yield SampleInput(input_tensor, weight, create_tensor(4))
```

added to 
https://github.com/pytorch/pytorch/blob/de257183007b218ce95aa6c9c084161f7d70bc77/torch/testing/_internal/common_methods_invocations.py#L4402

It will start failing with:
```
=================================== FAILURES ===================================
________ TestMathBitsCPU.test_neg_view_nn_functional_linear_cpu_float64 ________
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 918, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 1716, in test_neg_view
    self._test_math_view(
  File "test_ops.py", line 1672, in _test_math_view
    self.assertEqual(tensor.grad, cloned1_tensor.grad)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3564, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 8 / 8 (100.0%)
Greatest absolute difference: 2.368110593393027 at index (1, 0, 0, 0, 1) (up to 1e-07 allowed)
Greatest relative difference: 27.183659569540524 at index (1, 0, 1, 0, 0) (up to 1e-07 allowed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2687, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1364, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 924, in test_wrapper
    raise Exception(
Exception: Caused by sample input at index 17: SampleInput(input=Tensor[size=(2, 1, 2, 1, 2), device="cpu", dtype=torch.float64], args=TensorList[Tensor[size=(4, 2), device="cpu", dtype=torch.float64], Tensor[size=(4,), device="cpu", dtype=torch.float64]], kwargs={}, broadcasts_input=False, name='')
```

### Versions

2.2.0/nightly

cc @ezyang @gchanan @zou3519 @kadeng @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by mikaylagawarecki** [comment]
This wasn't a bug with neg_view!

The issue was that the same tensor was being passed in two sample inputs so in the test the .grad of that tensor was being accumulated twice which caused the discrepancies with the reference gradient
