### ISSUE TITLE
runtime error: unknown parameter

### ISSUE THREAD

**Issue by aravindravva** [pytorch/pytorch#117962]
### 🐛 Describe the bug

We are running an neural prophet model on the production server of 1.5G CPU and 1G memory and no GPU

Having this issue while running the model 

### Versions

```  
2024-01-21T15:11:45.258010227Z 21-01-2024:15:11:45,169 ERROR    [pod_usage_forecasting.py:140] unknown parameter type
2024-01-21T15:11:45.258038977Z Traceback (most recent call last):
2024-01-21T15:11:45.258044538Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
2024-01-21T15:11:45.258049228Z     self.fit_loop.run()
2024-01-21T15:11:45.258052947Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2024-01-21T15:11:45.258056598Z     self.advance(*args, **kwargs)
2024-01-21T15:11:45.258060268Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
2024-01-21T15:11:45.258063658Z     self._outputs = self.epoch_loop.run(self._data_fetcher)
2024-01-21T15:11:45.258066508Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2024-01-21T15:11:45.258069458Z     self.advance(*args, **kwargs)
2024-01-21T15:11:45.258073248Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
2024-01-21T15:11:45.258076058Z     batch_output = self.batch_loop.run(kwargs)
2024-01-21T15:11:45.258078979Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2024-01-21T15:11:45.258087509Z     self.advance(*args, **kwargs)
2024-01-21T15:11:45.258090529Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 90, in advance
2024-01-21T15:11:45.258093629Z     outputs = self.manual_loop.run(kwargs)
2024-01-21T15:11:45.258096458Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
2024-01-21T15:11:45.258099469Z     self.advance(*args, **kwargs)
2024-01-21T15:11:45.258102259Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 110, in advance
2024-01-21T15:11:45.258105109Z     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
2024-01-21T15:11:45.258108029Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
2024-01-21T15:11:45.258111229Z     output = fn(*args, **kwargs)
2024-01-21T15:11:45.258113999Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
2024-01-21T15:11:45.258116799Z     return self.model.training_step(*args, **kwargs)
2024-01-21T15:11:45.258119579Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/time_net.py", line 779, in training_step
2024-01-21T15:11:45.258123000Z     optimizer.step()
2024-01-21T15:11:45.258125889Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
2024-01-21T15:11:45.258128909Z     step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
2024-01-21T15:11:45.258131809Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
2024-01-21T15:11:45.258134800Z     return self.precision_plugin.optimizer_step(
2024-01-21T15:11:45.258138040Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 119, in optimizer_step
2024-01-21T15:11:45.258140929Z     return optimizer.step(closure=closure, **kwargs)
2024-01-21T15:11:45.258143720Z   File "/usr/local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
2024-01-21T15:11:45.258146530Z     return wrapped(*args, **kwargs)
2024-01-21T15:11:45.258149290Z   File "/usr/local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
2024-01-21T15:11:45.258152080Z     out = func(*args, **kwargs)
2024-01-21T15:11:45.258155041Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-01-21T15:11:45.258157910Z     return func(*args, **kwargs)
2024-01-21T15:11:45.258160900Z   File "/usr/local/lib/python3.10/site-packages/torch/optim/adamw.py", line 162, in step
2024-01-21T15:11:45.258163720Z     adamw(params_with_grad,
2024-01-21T15:11:45.258166651Z   File "/usr/local/lib/python3.10/site-packages/torch/optim/adamw.py", line 219, in adamw
2024-01-21T15:11:45.258169501Z     func(params,
2024-01-21T15:11:45.258172520Z   File "/usr/local/lib/python3.10/site-packages/torch/optim/adamw.py", line 273, in _single_tensor_adamw
2024-01-21T15:11:45.258175420Z     exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
2024-01-21T15:11:45.258178421Z RuntimeError: unknown parameter type
2024-01-21T15:11:45.258181001Z 
2024-01-21T15:11:45.258184351Z During handling of the above exception, another exception occurred:
2024-01-21T15:11:45.258187120Z 
2024-01-21T15:11:45.258189941Z Traceback (most recent call last):
2024-01-21T15:11:45.258192891Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
2024-01-21T15:11:45.258198881Z     return trainer_fn(*args, **kwargs)
2024-01-21T15:11:45.258203011Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
2024-01-21T15:11:45.258207031Z     self._run(model, ckpt_path=self.ckpt_path)
2024-01-21T15:11:45.258210821Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
2024-01-21T15:11:45.258214531Z     results = self._run_stage()
2024-01-21T15:11:45.258217981Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
2024-01-21T15:11:45.258221481Z     self._run_train()
2024-01-21T15:11:45.258231241Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1213, in _run_train
2024-01-21T15:11:45.258234822Z     with torch.autograd.set_detect_anomaly(self._detect_anomaly):
2024-01-21T15:11:45.258238982Z   File "/usr/local/lib/python3.10/site-packages/torch/autograd/anomaly_mode.py", line 115, in __exit__
2024-01-21T15:11:45.258244291Z     torch.set_anomaly_enabled(self.prev, self.prev_check_nan)
2024-01-21T15:11:45.258247902Z RuntimeError: unknown parameter type
2024-01-21T15:11:45.258251392Z 
2024-01-21T15:11:45.258254982Z During handling of the above exception, another exception occurred:
2024-01-21T15:11:45.258258843Z 
2024-01-21T15:11:45.258262392Z Traceback (most recent call last):
2024-01-21T15:11:45.258273133Z   File "/app/./ml/src/models/pod_usage_forecasting.py", line 75, in compute_forecasting
2024-01-21T15:11:45.258276732Z     model.fit(data)
2024-01-21T15:11:45.258280293Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 946, in fit
2024-01-21T15:11:45.258284113Z     metrics_df = self._train(
2024-01-21T15:11:45.258287103Z   File "/usr/local/lib/python3.10/site-packages/neuralprophet/forecaster.py", line 2642, in _train
2024-01-21T15:11:45.258289873Z     self.trainer.fit(
2024-01-21T15:11:45.258292653Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
2024-01-21T15:11:45.258295673Z     call._call_and_handle_interrupt(
2024-01-21T15:11:45.258298683Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 63, in _call_and_handle_interrupt
2024-01-21T15:11:45.258304363Z     trainer._teardown()
2024-01-21T15:11:45.258307703Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1175, in _teardown
2024-01-21T15:11:45.258310493Z     self.strategy.teardown()
2024-01-21T15:11:45.258313264Z   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 492, in teardown
2024-01-21T15:11:45.258316154Z     _optimizers_to_device(self.optimizers, torch.device("cpu"))
2024-01-21T15:11:45.258318973Z RuntimeError: unknown parameter type

```

**Comment by zou3519** [comment]
Do you have a self-contained script which we could use to reproduce the problem?

**Comment by aravindravva** [comment]
> Do you have a self-contained script which we could use to reproduce the problem?

No , if somw CPU crunch are these issues possible?
