### ISSUE TITLE
when load data  with Distributed Train, when the data is large, it will be raised errors

### ISSUE THREAD

**Issue by cqray1990** [pytorch/pytorch#117960]
### 🐛 Describe the bug

when load data  with Distributed Train,  the data is large, it will be raised errors,

my train data is  very large, it stored in json files, about 4.0G ,but when load json file with the function as follows:

        def _load_json( json_file):
        with open(json_file, 'r', encoding='utf-8') as load_f:
            ann = json.load(load_f, object_pairs_hook=collections.OrderedDict)
        return ann

unfortunately, i raised :

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1436 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 1435) of binary: anaconda3/envs/ocr_env/bin/python
Traceback (most recent call last):
File "anaconda3/envs/ocr_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "anaconda3/envs/ocr_env/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "anaconda3/envs/ocr_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in
main()
File "anaconda3/envs/ocr_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
launch(args)
File "anaconda3/envs/ocr_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
run(args)
File "anaconda3/envs/ocr_env/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
elastic_launch(
File "anaconda3/envs/ocr_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "anaconda3/envs/ocr_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

i am confused about this, why it is all right when i use only one card to train,but with two card not right, isn't it my cpu memory is not enough? but why one card is ok, when use two cards,the data will be loaded on each cards, and it results to this errors?

### Versions

pytorch 1.13.1

**Comment by wconstab** [comment]
Well, one theory is that you are loading your data into cpu memory (not GPU) so it doesn't matter how many GPUs you have, you're just limited by CPU memory and number of processes. (Assuming each process repeats the same loading step).

However, the stack trace does not show any complaint about OOM and I'd be surprised if 4 * 4GB is enough to oom your CPU.  Is there more information after the 'torch.distributed.elastic.multiprocessing.errors.ChildFailedError:' line in your logs?  The logs you did share unfortunately don't describe the source of the problem, so I can't diagnose.

You may also want to try a more recent PyTorch version.  (1.13 is old, we may have fixed issues in the mean time).

**Comment by d4l3k** [comment]
**Category: Stale**

This issue has been automatically closed. Please reopen if this is still an active issue.
