### ISSUE TITLE
"undefined Tensor" error in backward

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#11800]
Apparently some of our ops might return undefined tensors in backward.

[This script](https://gist.github.com/mttk/38f55a82605b2e25485484ad136eb231) fails with:

```
Traceback (most recent call last):                                                
  File "tmp.py", line 63, in <module>                                             
    loss.backward()                                                               
  File "/scratch/apaszke/pytorch/torch/tensor.py", line 96, in backward           
    torch.autograd.backward(self, gradient, retain_graph, create_graph)           
  File "/scratch/apaszke/pytorch/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag                             
RuntimeError: undefined Tensor                                                    
```

**Comment by t-vi** [comment]
I'd love to fix this.

**Comment by t-vi** [comment]
```
import torch
import torch.nn as nn
import torch.nn.functional as F

device = 'cuda:0'
embed_dim = 2
hidden_dim = 2
B = 4
T = 1

data = torch.randn(B,T,embed_dim, device=device)
h0 = torch.randn(B, embed_dim, device=device)
h0 = (h0, h0)

w_hh = torch.randn(4*hidden_dim, hidden_dim, device=device, requires_grad=True)
w_ih = torch.randn(4*embed_dim, hidden_dim, device=device, requires_grad=True)
b_hh = torch.randn(4*hidden_dim, device=device, requires_grad=True)
b_ih = torch.randn(4*embed_dim, device=device, requires_grad=True)

hiddens = h0
input = data
T = input.size(1) # check if time is actually the first dim
for t in range(T): 
    hiddens = torch.lstm_cell(input[:, t, :], hiddens, w_ih, w_hh, b_ih, b_hh)

h, c = hiddens
loss = c.sum() #+0*h.sum()
loss.backward()
```
`_thnn_fused_lstm_cell_cuda` doesn't deal well with undefined grad_hx, I'll send a PR.

**Comment by nbcmguarin0** [comment]
`Traceback (most recent call last):
  File "pytorch_run.py", line 165, in <module>
    train()
  File "pytorch_run.py", line 99, in train
    loss.backward()             # backprop
  File "/Users/mg/anaconda3/envs/docemb/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/mg/anaconda3/envs/docemb/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: undefined Tensor
` Hi I'm trying to upgrade [this project](https://github.com/hyqneuron/pytorch-avitm) to pytorch 1.2 and python 3.7 and getting the error above. Not sure if this is a related. Attached are files in case you would like to reproduce the error.
[avitm.zip](https://github.com/pytorch/pytorch/files/3726542/avitm.zip)

**Comment by MalaMahadevu** [comment]
@nbcmguarin0 : how did you resolve the issue in the attached file? im also trying to get the avitm model to run but falling into lot of engineering issues.
