### ISSUE TITLE
torch.export doesn't handle functools.partial correctly.

### ISSUE THREAD

**Issue by rvijayc** [pytorch/pytorch#118058]
### 🐛 Describe the bug

I would like to use `functools.partial` along with `torch.export` to simplify graph export, but torch.export doesn't seem to handle functools.partial as expected. A minimal reproducible example below:

```python
import torch
import functools

EXAMPLE_ARGS = (
        torch.randn(4, 4), torch.randn(4, 4), torch.randn(4)
        )

# some common function that can be parameterized.
def linear_common(x: torch.Tensor, w: torch.Tensor, b:torch.Tensor, relu_en):

    y = torch.ops.aten.linear(x, w, b)
    if relu_en:
        y = torch.ops.aten.relu(y)
    return y

# Case-A parameterize explicitly.
def linear_common_relu(x: torch.Tensor, w: torch.Tensor, b:torch.Tensor):
    return linear_common(x, w, b, relu_en=True)
m0 = torch.export.export(linear_common_relu, EXAMPLE_ARGS)
print('m0')
print('--')
print(m0.module().code)

# Case-B: Use functools.partial
print('m1')
print('--')
m1 = torch.export.export(functools.partial(linear_common, relu_en=True), EXAMPLE_ARGS)
print(m1.module().code)
```
In the above example Case-A works correctly, while Case-B produces the following error in my torch environment (Version: `2.2.0.dev20231010+cpu`).

```
[2024-01-22 18:17:43,850] torch._dynamo.eval_frame: [WARNING] could not determine __code__ for functools.partial(<function linear_common at 0x7fc04dc731f0>, relu_en=True)
[2024-01-22 18:17:43,871] torch._dynamo.eval_frame: [WARNING] could not determine __code__ for functools.partial(<function linear_common at 0x7fc04dc731f0>, relu_en=True)
Traceback (most recent call last):
  File "tests/repro/partial.py", line 26, in <module>
    m1 = torch.export.export(functools.partial(linear_common, relu_en=True), EXAMPLE_ARGS)
  File "/local/mnt/workspace/.executorch/lib/python3.8/site-packages/torch/export/__init__.py", line 586, in export
    return export__RC__(f, args, kwargs, dynamic_shapes=dynamic_shapes)
  File "/local/mnt/workspace/.executorch/lib/python3.8/site-packages/torch/_export/__init__.py", line 95, in export__RC__
    return export(f, args, kwargs)
  File "/local/mnt/workspace/.executorch/lib/python3.8/site-packages/torch/_export/__init__.py", line 470, in export
    return _export(
  File "/local/mnt/workspace/.executorch/lib/python3.8/site-packages/torch/_export/__init__.py", line 537, in _export
    gm_torch_level, _ = torch._dynamo.export(
  File "/local/mnt/workspace/.executorch/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 1221, in inner
    and not skipfiles.check(inspect.getsourcefile(call_to_inspect))
  File "/usr/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/local/mnt/workspace/.executorch/lib/python3.8/site-packages/torch/package/package_importer.py", line 696, in _patched_getfile
    return _orig_getfile(object)
  File "/usr/lib/python3.8/inspect.py", line 676, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got partial
```

# Expected Result

Both Case-A and Case-B works as expected. As our libraries get more complicated, having to define each specialization explicitly creates quite a bit of unnecessary repetition and verbosity. If `functools.partial` won't be supported, is there any other way to achieve the similar effect as Case-B?

### Versions

PyTorch version: 2.2.0.dev20231010+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-146-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: GRID A100D-10C
Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] executorch==0.1.0
[pip3] numpy==1.24.4
[pip3] torch==2.2.0.dev20231010+cpu
[pip3] torchaudio==2.2.0.dev20231010+cpu
[pip3] torchsr==1.0.4
[pip3] torchvision==0.17.0.dev20231010+cpu
[conda] Could not collect

**Comment by tringwald** [comment]
I can reproduce this on `2.1.2` but it seems to be already fixed on latest `main`.

**Comment by rvijayc** [comment]
Thanks - I'll update my checkout and validate this (need to run regression tests before I switch to latest). "Fixed" implies even the following warning is gone?

[2024-01-22 18:17:43,850] torch._dynamo.eval_frame: [WARNING] could not determine __code__ for functools.partial(<function linear_common at 0x7fc04dc731f0>, relu_en=True)
[2024-01-22 18:17:43,871] torch._dynamo.eval_frame: [WARNING] could not determine __code__ for functools.partial(<function linear_common at 0x7fc04dc731f0>, relu_en=True)

**Comment by tringwald** [comment]
This is the full output for your initial code snippet on my local `main` build:

```
m0
--
def forward(self, arg_0, arg_1, arg_2):
    l_x_, l_w_, l_b_, = fx_pytree.tree_flatten_spec(([arg_0, arg_1, arg_2], {}), self._in_spec)
    t = torch.ops.aten.t.default(l_w_);  l_w_ = None
    addmm = torch.ops.aten.addmm.default(l_b_, l_x_, t);  l_b_ = l_x_ = t = None
    relu = torch.ops.aten.relu.default(addmm);  addmm = None
    return pytree.tree_unflatten((relu,), self._out_spec)
    
m1
--
[2024-01-23 23:28:23,252] torch._dynamo.eval_frame: [WARNING] could not determine __code__ for functools.partial(<function linear_common at 0x7f48dba97d90>, relu_en=True)
[2024-01-23 23:28:23,264] torch._dynamo.eval_frame: [WARNING] could not determine __code__ for functools.partial(<function linear_common at 0x7f48dba97d90>, relu_en=True)
def forward(self, arg_0, arg_1, arg_2):
    l_args_0_, l_args_1_, l_args_2_, = fx_pytree.tree_flatten_spec(([arg_0, arg_1, arg_2], {}), self._in_spec)
    t = torch.ops.aten.t.default(l_args_1_);  l_args_1_ = None
    addmm = torch.ops.aten.addmm.default(l_args_2_, l_args_0_, t);  l_args_2_ = l_args_0_ = t = None
    relu = torch.ops.aten.relu.default(addmm);  addmm = None
    return pytree.tree_unflatten((relu,), self._out_spec)
    
```

The warning persists, but the generated code is the same, even with `partial`.

**Comment by rvijayc** [comment]
This is what I see as well when I backed up to `2.2.0a0+gitb4ce501` (i.e., an older) PyTorch version.

If `torch.export` is supposed to support `functools.partial`, then should the warning be removed? If not, is there possibility that this functionality would break in the future?

Thanks!

**Comment by zhxchen17** [comment]
@rvijayc hi thanks for raising this question. Right now function support (including exporting functions and partial functions) is not very high on the priority list for torch.export.

For now we support nn.Module better. If you want to partially apply some arguments, another pattern you can try is something like the following:
```
class Module(torch.nn.Module):
    def __init__(self, relu_en):
        self.relu_en = relu_en
    def forward(self, x, w, b):
        return ...
```

We understand this might not be equivalent to the original example you provided, but hopefully it is close and good enough.

**Comment by rvijayc** [comment]
Thanks @zhxchen17 for the hint. I'll give this a try. But, please do keep functools/partial functions support in the future roadmap as does provide more flexibility for torch.export.

**Comment by rvijayc** [comment]
To be more specific, I needed `functools.partial` support because I am using the function signatures to do subgraph match/replace ([SubgraphMatcher](https://github.com/pytorch/pytorch/blob/6e78592cbb81138ce13ad65a5f549d65b191526c/torch/csrc/jit/ir/subgraph_matcher.cpp#L14),  [replace_pattern](https://github.com/pytorch/pytorch/blob/6e78592cbb81138ce13ad65a5f549d65b191526c/torch/fx/subgraph_rewriter.py#L80)) . For example, in some cases I would like to match an argument pattern of `(arg1, arg2, arg3, arg4)` and in some other cases I would like match a specialized version of the function with argument list `(arg1, arg2)` with `arg3` and `arg4` fixed to constants. 

For example, one case I may have `linear_common(x, w, b, x_dtype, w_dtype, b_dtype)` and in other cases, I may have `linear_s8u8s8(x, w, b)` with `x_dtype` fixed at `torch.int8`, etc., `functools.partial` allows me to avoid spelling out `linear_s8u8s8` explicitly. 

I don't think using `nn.Module` would help with this unless I am missing something.

**Comment by zhxchen17** [comment]
> To be more specific, I needed `functools.partial` support because I am using the function signatures to do subgraph match/replace ([SubgraphMatcher](https://github.com/pytorch/pytorch/blob/6e78592cbb81138ce13ad65a5f549d65b191526c/torch/csrc/jit/ir/subgraph_matcher.cpp#L14), [replace_pattern](https://github.com/pytorch/pytorch/blob/6e78592cbb81138ce13ad65a5f549d65b191526c/torch/fx/subgraph_rewriter.py#L80)) . For example, in some cases I would like to match an argument pattern of `(arg1, arg2, arg3, arg4)` and in some other cases I would like match a specialized version of the function with argument list `(arg1, arg2)` with `arg3` and `arg4` fixed to constants.
> 
> For example, one case I may have `linear_common(x, w, b, x_dtype, w_dtype, b_dtype)` and in other cases, I may have `linear_s8u8s8(x, w, b)` with `x_dtype` fixed at `torch.int8`, etc., `functools.partial` allows me to avoid spelling out `linear_s8u8s8` explicitly.
> 
> I don't think using `nn.Module` would help with this unless I am missing something.

@rvijayc thanks for the context. IIUC, the code example I listed above doesn't work for your case because that actually changes the signature of the graph from 4 inputs to 3 inputs, but theoretically we want to have 4 inputs in the graph instead of 3, so there's a small difference by rewriting this to module. Is this accurate?

I just want to point out that in our current design, even we support functools.partial in torch.export.export, it would still produce 3 graph inputs, because torch.export doesn't build the graph based on the original callable signature, but rather the actual argument list users provide to the export() call (as the second argument), in your case, torch.export.export(partial(f, relu_en=x), (x, w, b)) will still ignore relu_en as the graph input. Why we're doing so? Because 1. we don't need to parse function signatures which adds a lot of complexity to the API and 2. it's a more consistent semantics across all sorts of objects that users pass into the API, and it'd be weird for other groups of users to understand the API behavior if we do some special handling for functions.

That being said, we can still support functions through a more explicit API, like torch.export.export_function() (which doesn't exist today), and it could do what you said to handle partially applied arguments as intended in your case.

**Comment by rvijayc** [comment]
> I just want to point out that in our current design, even we support functools.partial in torch.export.export, it would still produce 3 graph inputs, because torch.export doesn't build the graph based on the original callable signature, but rather the actual argument list users provide to the export() call (as the second argument), in your case, torch.export.export(partial(f, relu_en=x), (x, w, b)) will still ignore relu_en as the graph input.

Hi @zhxchen17, This is exactly what I want as well. I just would like to export both `f` and `functools.partial(f, ...)`. In my example, I would expect `functools.partial(linear_common, relu_en=True)` to produce the *exact same graph* as `linear_common_relu` when passing it through `torch.export`. I am fine as along as `functools.partial` support is planned at some point in the future. Right now, it does produce a warning.

Meanwhile, I've tried the `nn.Module` approach you recommended and it does save me quite a bit in reducing the verbosity of maintaining a pattern hierarchy (to use with `SubgraphMatcher`). So, I am good for now.
