### ISSUE TITLE
Failed to export onnx model with sparse_conv tensor

### ISSUE THREAD

**Issue by kellenf** [pytorch/pytorch#118170]
### 🐛 Describe the bug

I want to export onnx with sparse conv tensor. 
```python
import torch
import torch.nn as nn
import spconv.pytorch as spconv
from voydet.architect.cnn.layers import build_norm_layer

class MLPModel(nn.Module):
    def __init__(self, sparse_shape, 
                 norm_cfg=dict(type='BN1d', eps=1e-3, momentum=0.01)):
        super().__init__()
        self.sparse_shape = sparse_shape
        self.conv1 = spconv.SparseSequential(
            spconv.SubMConv3d(3,
                                16,
                                3,
                                padding=1,
                                bias=False,
                                indice_key='subm1'),
            build_norm_layer(norm_cfg, 16), 
            nn.ReLU())
        
        self.conv2 = spconv.SparseSequential(
            spconv.SubMConv3d(16,
                                16,
                                3,
                                padding=1,
                                bias=False,
                                indice_key='subm1'),
            build_norm_layer(norm_cfg, 16), 
            nn.ReLU())

    def forward(self, features, coords, batch_size=1):
        x = spconv.SparseConvTensor(
            features=features,
            indices=coords.int(),
            spatial_shape=self.sparse_shape,
            batch_size=batch_size)
        x = self.conv1(x)
        x = self.conv2(x)
        return x


sparse_shape = [40, 100, 100]
model = MLPModel(sparse_shape=sparse_shape).cuda()
features = torch.rand(200, 3).cuda()
coords = [(torch.rand(200) * 0).int(), (torch.rand(200) * 40).int(), (torch.rand(200) * 100).int(), (torch.rand(200) * 100).int()]
coords = torch.stack(coords, dim=1).cuda()
x = model(features, coords)
model.eval()
dummy_inputs = (features, coords)
name_inputs = ('features', 'coords')
with torch.no_grad():
    torch.onnx.export(model,
                        dummy_inputs,
                        'asdasd.onnx',
                        opset_version=11,
                        input_names=name_inputs,
                        output_names='output')
```
But errors:
```
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "export_test.py", line 52, in <module>
    torch.onnx.export(model,
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/luban/anaconda3/envs/voydet/lib/python3.8/site-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: SparseConvTensor
```
So How to export this model?

### Versions

torch: 2.0.1+cu118
spconv: 2.3.6

**Comment by thiagocrepaldi** [comment]
torch.onnx.export does not support non-tensor/scalar input types

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
