### ISSUE TITLE
ModuleNotFoundError: pynvml does not seem to be installed or it can't be imported.

### ISSUE THREAD

**Issue by developer0hye** [pytorch/pytorch#118173]
### 🐛 Describe the bug

# Code to reproduce bug

```python
import torch
print(torch.cuda.utilization(device=0))
```

# Error message

```
Traceback (most recent call last):
  File "C:\Users\yhkwon\.conda\envs\pytorch211\Lib\site-packages\torch\cuda\__init__.py", line 51, in <module>
    import pynvml  # type: ignore[import]
    ^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pynvml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yhkwon\Documents\Projects\2024\KISA\usage.py", line 3, in <module>
    print(torch.cuda.utilization(device=0))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhkwon\.conda\envs\pytorch211\Lib\site-packages\torch\cuda\__init__.py", line 925, in utilization
    handle = _get_pynvml_handler(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhkwon\.conda\envs\pytorch211\Lib\site-packages\torch\cuda\__init__.py", line 878, in _get_pynvml_handler
    raise ModuleNotFoundError(
ModuleNotFoundError: pynvml does not seem to be installed or it can't be imported.
```

### Versions

PyTorch version: 2.1.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: version 3.23.0-rc2
Libc version: N/A

Python version: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.3.58
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA TITAN RTX
Nvidia driver version: 536.40
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3300
DeviceID=CPU0
Family=205
L2CacheSize=7680
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3300
Name=12th Gen Intel(R) Core(TM) i5-12600
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] onnx==1.15.0
[pip3] onnxruntime-gpu==1.16.3
[pip3] torch==2.1.1+cu121
[pip3] torchaudio==2.1.1+cu121
[pip3] torchvision==0.16.1+cu121
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.1.1+cu121              pypi_0    pypi
[conda] torchaudio                2.1.1+cu121              pypi_0    pypi
[conda] torchvision               0.16.1+cu121             pypi_0    pypi

**Comment by malfet** [comment]
As far as I recall, pynvml is an optional dependency because it was not available for some versions of Python at the time it was added. As we are only using a small fraction of the API, I wonder if rewriting this code using types would be more efficient

**Comment by taras-janea** [comment]
@malfet if this issue is still relevant, could you please describe in more details the tasks remain to be completed to resolve it?
