### ISSUE TITLE
Using autograd.Functions defined in torch/ cause graph breaks

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#118334]
### 🐛 Describe the bug

If an autograd.Function is defined in torch/, it will cause a graph break due to skipfiles.

```python
import torch
from torch.nested._internal.nested_tensor import ViewNestedFromBuffer

def fn(values, offsets):
    return ViewNestedFromBuffer.apply(values.cos(), offsets).sin()

fn_c = torch.compile(fn, backend="aot_eager", dynamic=True)
values = torch.rand((12, 8), requires_grad=True)
offsets = torch.tensor([0, 1, 2, 5, 8, 9, 12])
lengths = torch.tensor([1, 1, 3, 3, 1, 3])

fn_c(values, offsets)
```

log:
```
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG] Traceback (most recent call last):
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/symbolic_convert.py", line 469, in wrapper
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     return inner_fn(self, inst)
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/symbolic_convert.py", line 1196, in CALL_FUNCTION
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     self.call_function(fn, args, {})
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/symbolic_convert.py", line 651, in call_function
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     self.push(fn.call_function(self, args, kwargs))
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/variables/misc.py", line 581, in call_function
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     return self.obj.call_method(tx, self.name, args, kwargs)
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/variables/misc.py", line 410, in call_method
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     return self.call_apply(tx, args, kwargs)
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/variables/misc.py", line 353, in call_apply
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     return AutogradFunctionApplyVariable(
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 1376, in call_function
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     (fwd_out, _), fwd_graph, fwd_freevars = speculate_subgraph(
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]   File "/data/users/dberard/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 451, in speculate_subgraph
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG]     raise Unsupported(
[2024-01-25 16:05:28,337] [0/0] torch._dynamo.symbolic_convert: [DEBUG] torch._dynamo.exc.Unsupported: speculate_subgraph: while introspecting autograd.Function, we were unable to trace function `forward` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown. Scroll up for the stack trace of the initial exception. The reason was: 'inline in skipfiles: ViewNestedFromBuffer.forward | forward /data/users/dberard/pytorch/torch/nested/_internal/nested_tensor.py, skipped according skipfiles.SKIP_DIRS'
```

note: ViewNestedFromBuffer may be patched; in which case, a different autograd.Function will probably need to be used to repro this behavior.

### Versions

main branch ~jan 24.

**Comment by anijain2305** [comment]
Cc @yanboliang for the new tracing rule system

**Comment by yanboliang** [comment]
I have talked with @davidberard98 about this, I think we should allow Dynamo trace for all ```autograd.Function``` since the trace is only to check if it's sound. I'll work on a PR to fix this.

**Comment by anijain2305** [comment]
Any update on this one?

**Comment by davidberard98** [comment]
I haven't done this, but I think it may have been fixed otherwise - maybe @yanboliang did this?

**Comment by zou3519** [comment]
I get the graph break, so this issue is still valid

**Comment by yanboliang** [comment]
Tentative solution: ignore trace rules for HOPs.
