### ISSUE TITLE
logging errors for toy model with TORCH_COMPILE_DEBUG

### ISSUE THREAD

**Issue by chauhang** [pytorch/pytorch#118476]
### 🐛 Describe the bug

Seeing many logging errors for a simple toy example with TORCH_COMPILE_DEBUG flag turned, reducing readability of the logs

```
import torch

@torch.compile(dynamic=True)
def toy_example(x):
    y = x.sin()
    z = y.cos()
    return y, z

toy_example(torch.randn([8192, 1024], device="cuda"))
```

Logs with errors - on running first time only. Subsequent requests are using inductor cache and do not contain these errors: 
```
TORCH_COMPILE_DEBUG=1 python inductor_demo.py

==== Errors in the logs===

[2024-01-27 22:03:32,821] torch._inductor.triton_heuristics: [DEBUG] Benchmark all input configs for triton_, get:
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/envs/nllm3/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/conda/envs/nllm3/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_logging/_internal.py", line 698, in format
    record.message = record.getMessage()
  File "/opt/conda/envs/nllm3/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "/home/ubuntu/compile/inductor_demo.py", line 9, in <module>
    toy_example(torch.randn([8192, 1024], device="cuda"))
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 443, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/compile/inductor_demo.py", line 3, in toy_example
    @torch.compile(dynamic=True)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 443, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 905, in forward
    return compiled_fn(full_args)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 79, in g
    return f(*args)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 95, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 103, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 118, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 824, in __call__
    return self.get_current_callable()(inputs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 648, in run
    return model(new_inputs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 852, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_ubuntu/nc/cncdhr4iiocgxpdvrkvwvf27wnz36h33n3ror2dz2eeut3abzhb3.py", line 84, in call
    triton_poi_fused_cos_sin_0.run(arg2_1, buf0, buf1, triton_poi_fused_cos_sin_0_xnumel, grid=grid(triton_poi_fused_cos_sin_0_xnumel), stream=stream0)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 604, in run
    self.autotune_to_one_config(*args, grid=grid, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 502, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 248, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 489, in benchmark_all_configs
    log.debug(
Message: '%s: %f, nreg %d, nspill %d, #shared-mem %d'
Arguments: (<triton.runtime.autotuner.Config object at 0x7fa33942ead0>, 0.2385919988155365, 31, 8, None)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/envs/nllm3/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/conda/envs/nllm3/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_logging/_internal.py", line 698, in format
    record.message = record.getMessage()
  File "/opt/conda/envs/nllm3/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "/home/ubuntu/compile/inductor_demo.py", line 9, in <module>
    toy_example(torch.randn([8192, 1024], device="cuda"))
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 443, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/compile/inductor_demo.py", line 3, in toy_example
    @torch.compile(dynamic=True)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 443, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 905, in forward
    return compiled_fn(full_args)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 79, in g
    return f(*args)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 95, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 103, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 118, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 824, in __call__
    return self.get_current_callable()(inputs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 648, in run
    return model(new_inputs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 852, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_ubuntu/nc/cncdhr4iiocgxpdvrkvwvf27wnz36h33n3ror2dz2eeut3abzhb3.py", line 84, in call
    triton_poi_fused_cos_sin_0.run(arg2_1, buf0, buf1, triton_poi_fused_cos_sin_0_xnumel, grid=grid(triton_poi_fused_cos_sin_0_xnumel), stream=stream0)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 604, in run
    self.autotune_to_one_config(*args, grid=grid, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 502, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 248, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/nllm3/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 489, in benchmark_all_configs
    log.debug(
Message: '%s: %f, nreg %d, nspill %d, #shared-mem %d'
Arguments: (<triton.runtime.autotuner.Config object at 0x7fa3372e9420>, 0.21094399690628052, 17, 8, None)
[2024-01-27 22:03:32,823] torch._inductor.triton_heuristics: [DEBUG] Save heuristic tuning result to /tmp/torchinductor_ubuntu/od/cod6gmt3ar2wbiz5vcueflt47acfjygzcpa24j67gndgktbdoeo4.best_config

```

### Versions

torch==2.3.0.dev20240127+cu118

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
Looks easy to fix

**Comment by cyrilgabriele** [comment]
Hi @mlazos !
Could I work on this bug? It would be my first ever contribution FYI.

**Comment by mlazos** [comment]
Yes please do, let me know if you have questions.

**Comment by cyrilgabriele** [comment]
Hi @mlazos 
I might fixed the issue. However, I'm not able to test it as I get dependency error while trying to run pytest test_torch.py. 
Furthermore, as this change is tiny I assume that the rather "big" unit tests won't cover this bug. There I'm wondering how I must use the "upadted" pytorch including my changed locally to check if the issue is fixed.
I asekd in the unofficial pytroch forum for help. I'm after it and  it will soon be done :)

**Comment by mlazos** [comment]
we have our log testing here (no log entry is too small to be tested :)) take a look at that file for test examples.

**Comment by cyrilgabriele** [comment]
Hi @mlazos 
Thank you for pointing to the right file. I will add a test tomorrow. I think I do not need to build pytroch from scratch as the bug only appears for the first time so I can see after what it should log and write tomorrow a corresponding test. 
I could successfully build pytroch from source after taking time do fully understand the doc. However, I need to figure out how to build only the needed parts. But I saw that this is also explained in the doc. 
Thanks for your help!

**Comment by cyrilgabriele** [comment]
As torch.compile is not supported for Windows yet, I can not see how the log should look like. Furthermore, I have some difficulties what I should test here, as we only need to test the logging, the shapes etc. does not interest us at all right?
Therefore, I implemented now a basic test just checking if an exception gets thrown. 
If I want to run the test locally I get some errors idk why... (see picture)
<img width="987" alt="2024-02-11 11_05_28-logging errors for toy model with TORCH_COMPILE_DEBUG · Issue #118476 · pytorch_" src="https://github.com/pytorch/pytorch/assets/100346759/bbbde602-d176-42fd-b556-ae68835e23e4">

**Comment by zou3519** [comment]
Seems to be fixed, I can't repro this anymore.
