### ISSUE TITLE
"Direct Graph Manipulation" example in torch.fx crashes

### ISSUE THREAD

**Issue by dsuess** [pytorch/pytorch#118626]
### 📚 The doc issue

The second example in the [direct graph manipulation](https://pytorch.org/docs/stable/fx.html#direct-graph-manipulation) section does not work. 

Running the following minimal example reflecting the example crashes:
```
import torch
print(torch.__version__)

class M(torch.nn.Module):
    def forward(self, x, y):
        return x + y

m = M()
traced = torch.fx.symbolic_trace(m)

_, _, add, _ = traced.graph.nodes
with traced.graph.inserting_after(add):
    relu = traced.graph.call_function(
        torch.relu, args=(add,))

    add.replace_all_uses_with(relu)

print(relu, relu.all_input_nodes)
traced.recompile()

traced(torch.ones(1), torch.ones(1))
```

with 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 274, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.4 from <ipython-input-4-fbbac1d8ccdb>:5 in forward", line 6, in forward
    relu = torch.relu(relu)
UnboundLocalError: local variable 'relu' referenced before assignment

Call using an FX-traced Module, line 6 of the traced Module's generated forward function:
    add = x + y;  x = y = None
    relu = torch.relu(relu)

~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

The reason being that the `replace_all_uses_with` call also replaces the use of the `add`-node as an input to `relu` with `relu`. Therefore, the resulting graph is not acyclic anymore because the input to `relu` is `relu` itself. 

### Suggest a potential alternative/fix

Add the `delete_user_cb` argument to the call to `replace_all_uses_with`:
```
    add.replace_all_uses_with(relu, delete_user_cb=lambda node: node is not relu)
```

**Comment by eellison** [comment]
This doesn't repro for me as of master.

```
import torch
print(torch.__version__)

class M(torch.nn.Module):
    def forward(self, x, y):
        return x + y

m = M()
traced = torch.fx.symbolic_trace(m)

_, _, add, _ = traced.graph.nodes
with traced.graph.inserting_after(add):
    relu = traced.graph.call_function(
        torch.relu, args=(add,))

    add.replace_all_uses_with(relu)

print(relu, relu.all_input_nodes)
traced.recompile()
print(traced)
```

Gives
```
2.2.0a0+git8c14779
relu [relu]
M()



def forward(self, x, y):
    add = x + y;  x = y = None
    relu = torch.relu(relu)
    return relu
```

Could you try using a more recent version ? if it still fails free feel to reopen.
