### ISSUE TITLE
CUDA 9.2 PyTorch on Mac gives "Found no NVIDIA driver" error

### ISSUE THREAD

**Issue by tesfaz1** [pytorch/pytorch#11870]
## Issue description
Installed pytorch from the source with cuda enabled, but having issue (see below) when I tried to use it. 
System: macOS Sierra (version 10.12.16) 
Graphics:  NVIDIA GeForce GT 750M 2048 MB Intel Iris Pro 1536 MB

## Code example
$ python
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
>>> x = torch.Tensor(5, 3)
>>>  x.cuda()
 >>> x.cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tesfaz1/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/Users/tesfaz1/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
>>> 

## System Info
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.0.0a0+e80d1d2
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Mac OSX 10.12.6
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.4.dylib
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn.dylib
/usr/local/cuda/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.5)
[pip3] numpydoc (0.8.0)
[pip3] torch (1.0.0a0+e80d1d2)
[pip3] torchfile (0.1.0)
[conda] torch                     1.0.0a0+e80d1d2           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchfile                 0.1.0                      py_0    conda-forge

**Comment by tesfaz1** [comment]
Upgrading the OS resolved the issue.
