### ISSUE TITLE
[inductor][cpu]yolov3 fp32 static shape cpp wrapper single thread accuracy crash

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#118751]
### 🐛 Describe the bug

```
loading model: 0it [00:01, ?it/s]cpu  eval  yolov3                             

[2024-01-30 08:13:43,620] [7/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: stack
[2024-01-30 08:13:53,898] [7/1] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: stack
ERROR:common:Failed running call_function <built-in function not_>(*(False,), **{}):
False != True

from user code:
   File "/workspace/benchmark/torchbenchmark/models/yolov3/yolo_models.py", line 187, in forward
    if (self.nx, self.ny) != (nx, ny):

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2441, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 443, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2175, in run_n_iterations
    return self.model_iter_fn(mod, inputs, collect_outputs=True)
  File "benchmarks/dynamo/torchbench.py", line 469, in forward_pass
    return mod(*inputs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/benchmark/torchbenchmark/models/yolov3/yolo_models.py", line 238, in forward
    return self.forward_once(x)
  File "/workspace/benchmark/torchbenchmark/models/yolov3/yolo_models.py", line 290, in forward_once
    yolo_out.append(module(x, out))
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 605, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 748, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 390, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 650, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 248, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 531, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 155, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 496, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2125, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 787, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 750, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1184, in COMPARE_OP
    BuiltinVariable(supported_any[op]).call_function(
  File "/workspace/pytorch/torch/_dynamo/variables/builtin.py", line 689, in call_function
    result = handler(tx, *args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/variables/builtin.py", line 1595, in _comparison
    return BaseListVariable.list_compare(tx, op, left, right)
  File "/workspace/pytorch/torch/_dynamo/variables/lists.py", line 148, in list_compare
    return BuiltinVariable(operator.not_).call_function(tx, [eq_result], {})
  File "/workspace/pytorch/torch/_dynamo/variables/builtin.py", line 689, in call_function
    result = handler(tx, *args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/variables/builtin.py", line 1713, in call_not_
    return SymNodeVariable.create(
  File "/workspace/pytorch/torch/_dynamo/variables/tensor.py", line 796, in create
    sym_num = get_fake_value(proxy.node, tx)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1653, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1599, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1140, in wrap_fake_exception
    return fn()
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1600, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1720, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1699, in run_node
    return node.target(*args, **kwargs)
  File "/workspace/pytorch/torch/__init__.py", line 369, in __bool__
    return self.node.bool_()
  File "/workspace/pytorch/torch/fx/experimental/sym_node.py", line 399, in bool_
    return self.guard_bool("", 0)
  File "/workspace/pytorch/torch/fx/experimental/sym_node.py", line 365, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/workspace/pytorch/torch/fx/experimental/recording.py", line 227, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3704, in evaluate_expr
    assert static_expr == hint, f"{static_expr} != {hint}"
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function not_>(*(False,), **{}):
False != True

from user code:
   File "/workspace/benchmark/torchbenchmark/models/yolov3/yolo_models.py", line 187, in forward
    if (self.nx, self.ny) != (nx, ny):

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>4749337</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>b2d9c3e</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>315f315</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0790338</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info(nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.3.0a0+git4f9be7c</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.18.0a0+a00a72b</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+b2d9c3e</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>
Repro:

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference accuracy torchbench yolov3 float32 first static cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/4e456fd95b7f88a40105e77dd1ded098d8f4c578
[torchbench-yolov3-inference-float32-static-cpp-accuracy-single-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/14114000/torchbench-yolov3-inference-float32-static-cpp-accuracy-single-crash_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @WeizhuoZhang-intel @chuanqi129

**Comment by chuanqi129** [comment]
Hi @desertfire , could you please help to double check this issue? According to the bisect search log, it probably caused by the PR #118024

**Comment by chunyuan-w** [comment]
Hi @desertfire this issue is a regression against the PyTorch 2.2 release. May I know if you get the time to check it?

**Comment by zxd1997066** [comment]
base on the latest results, this issue is fixed.
