### ISSUE TITLE
Torch crashes with "torch.distributed.DistNetworkError: Unknown error"

### ISSUE THREAD

**Issue by meryanh** [pytorch/pytorch#118868]
### 🐛 Describe the bug

I'm trying to run this on a single machine. Single GPU. No distributed anything. No k8s. Just a laptop with a fresh install of Win11.

It clearly recognizes my GPU since I can see `GPU NVIDIA GeForce GTX 1070 with Max-Q Design` in the output.

When I try to actually train something, I get the following error:
```
Traceback (most recent call last):
  File "C:\RVC_V2\runtime\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\RVC_V2\runtime\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\RVC_V2\infer\modules\train\train.py", line 129, in run
    dist.init_process_group(
  File "C:\RVC_V2\runtime\lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\RVC_V2\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 1177, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\RVC_V2\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "C:\RVC_V2\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: Unknown error
```

Rolling back to version 2.1.2+cu121 fixes the problem, so It's definitely not a hardware issue. The bug was introduced in version 2.2.0.

### Versions

PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070 with Max-Q Design
Nvidia driver version: 551.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2201
DeviceID=CPU0
Family=198
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2201
Name=Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] onnxruntime-gpu==1.17.0
[pip3] torch==2.2.0+cu121
[pip3] torchaudio==2.2.0+cu121
[pip3] torchcrepe==0.0.20
[pip3] torchfcpe==0.0.3
[pip3] torchvision==0.17.0+cu121
[conda] Could not collect

**Comment by awgu** [comment]
This looks like a duplicate of https://github.com/pytorch/pytorch/issues/118737 (where a PR for the fix is in https://github.com/pytorch/pytorch/pull/118860).

Let me know if this is not the same error.

**Comment by taras-janea** [comment]
Closing this issue due to inactivity. If you continue to experience this problem or have any related concerns, please don't hesitate to open a new issue.
