### ISSUE TITLE
DataParallel with Multi-GPU module (eg. 2 model replica on 4 GPU)

### ISSUE THREAD

**Issue by YHRen** [pytorch/pytorch#11881]
We are working on distributing a large model's weights on two GPUs and then use DataParallel to train the model. 
So, suppose we have 4 GPUs with `device_id = [0,1,2,3]`, there are two replicas of the model. One replica lives on device 0 and 1, and the other lives on 2 and 3.
During the training, we received the following error message:

> Traceback (most recent call last):
  File "dpmp_simple_cnn.py", line 93, in <module>
    loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 30, in backward
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 41, in forward
    return comm.reduce_add_coalesced(grads, destination)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 120, in reduce_add_coalesced
    flat_result = reduce_add(flat_tensors, destination)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 73, in reduce_add
    raise RuntimeError("reduce_add expects destination to be on the same GPU with one of the tensors")
RuntimeError: reduce_add expects destination to be on the same GPU with one of the tensors

We think the error traces back to the `reduce_add_coalesced()` function, where to improve the efficiency of the data transfer, all grads are flattened and packed into fix-sized (about 10MB by default) buffers. 
In our case, part of the grads is on the first device, and the other part on the second device, which leads to the above error.

If we reduce the number of parameters of the model within the buffer size, the error will not occur, and the model converges. 

System Info: pytorch 0.4.1, python 2.7, on 4 V100 (32GB version).

Here is a minimum code to reproduce the problem, where one can tune the size of the model via the variable `tmp` during the initialization. (tmp<=5 will be a small model, and tmp>=12 will be a large model).

`import torch
import torch.nn as nn
from collections import OrderedDict
from torchvision import datasets, transforms

batch_size = 128
train_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ])),
batch_size=batch_size, shuffle=True)

class ConvBlck(nn.Module):
    def __init__(self, in_channel, out_channel, kernel_size, stride=1):
        super(ConvBlck, self).__init__()
        self.blck = nn.Sequential( OrderedDict([
            ('conv', nn.Conv2d( in_channel, out_channel, kernel_size=kernel_size, stride=stride, padding=kernel_size//2)),
            ('relu', nn.ReLU() )]) )
    def forward(self, x):
        return self.blck(x)

class SixConv(nn.Module):
    def __init__(self):
        super(SixConv, self).__init__()
        self.conv1 = ConvBlck(1,16,5,2)
        self.conv2 = ConvBlck(16,32,5,2)
        self.conv3 = ConvBlck(32,16,5,2)
        self.conv4 = nn.Sequential( nn.AdaptiveAvgPool2d(1) , nn.Conv2d(16, 10, 1, 1) )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        next_index = x.device.index + 1
        x = x.cuda(next_index)
        tmp_conv3 = self.conv3.cuda(next_index)
        tmp_conv4 = self.conv4.cuda(next_index)
        x = tmp_conv3(x)
        x = tmp_conv4(x)
        x = x.cuda(next_index-1)
        return x

model = SixConv()
model = nn.DataParallel(model,device_ids=[0,2]);
crite = torch.nn.CrossEntropyLoss()
optim = torch.optim.Adam( model.parameters(), lr=0.001)
device = 'cuda:0' if torch.cuda.is_available() else 'cpu:0'
model.to( device )

losses = []
for x,y in train_loader:
    optim.zero_grad()
    x, y = x.to(device), y.to(device)
    pred = model(x)
    loss = crite(pred.squeeze(), y)
    loss.backward()
    optim.step()
    losses.append(loss.item())
print(losses)

`

I think, which might be wrong, the function `reduce_add_coalesced()` expects all the inputs are from the same device, which is not true in our case. 
Any suggestions to work around this are welcome.
Thank you in advance.

**Comment by YHRen** [comment]
I think I found the "right" way to do this. I will update the solution later. Thanks.

**Comment by YHRen** [comment]
The walk-around we found is to `DaraParallel` the head of the model and the tail of the model separately. 
And wrap the data transfer in the `forward` function.
Here is a working example. Hopefully, someone finds this useful. 
Thanks. This issue can be closed. 
```

class ConvBlck(nn.Module):
    def __init__(self, in_channel, out_channel, kernel_size, stride=1):
        super(ConvBlck, self).__init__()
        self.blck = nn.Sequential( OrderedDict([
            ('conv', nn.Conv2d( in_channel, out_channel, kernel_size=kernel_size, stride=stride, padding=kernel_size//2)),
            ('relu', nn.ReLU() )]) )
    def forward(self, x):
        return self.blck(x)

class SixConv(nn.Module):
    def __init__(self):
        super(SixConv, self).__init__()
        tmp = 5
        self.conv1 = nn.Sequential( ConvBlck(1,1<<tmp,5,2), ConvBlck(1<<tmp,1<<(tmp+1),5,2) )
        self.conv2 = nn.Sequential( ConvBlck(1<<(tmp+1),1<<tmp,5,2), nn.AdaptiveAvgPool2d(1) , nn.Conv2d(1<<tmp, 10, 1, 1) )

    def forward(self, x):
        x = self.conv1(x)
        next_index = x.device.index + 1
        x = x.cuda(next_index)
        x = self.conv2(x)
        return x
model = SixConv()
model.conv1 = nn.DataParallel(model.conv1,device_ids=[0,2]);
model.conv2 = nn.DataParallel(model.conv2,device_ids=[1,3]);
crite = torch.nn.CrossEntropyLoss()
optim = torch.optim.Adam( model.parameters() , lr=0.001)
model.conv1.to( 'cuda:0' )
model.conv2.to( 'cuda:1' )

```
