### ISSUE TITLE
BackendCompilerFailed: backend=‘inductor’ raised: RuntimeError: Triton Error [CUDA]: device kernel image is invalid

### ISSUE THREAD

**Issue by napsternxg** [pytorch/pytorch#119054]
### 🐛 Describe the bug

I am unable to use torch compile with pytorch using the inductor backend.

I am not sure how to interpret this error `BackendCompilerFailed: backend='inductor' raised: RuntimeError: Triton Error [CUDA]: device kernel image is invalid`

Code to reproduce the bug:

```python
# file: torch_compile_error.py
import torch

def add_tensors(a, b):
    c = a + b
    return c

a = torch.tensor([1, 2, 3]).to("cuda")
b = torch.tensor([1, 2, 3]).to("cuda")
c = add_tensors(a, b)

print(f"{a=}, {b=}, {c=}")

# Compile
add_tensors_compiled = torch.compile(add_tensors)

c_compiled = add_tensors_compiled(a, b)
print("{c_compiled=}")
```

Full output when running `python torch_compile_error.py`:

### Error logs
```
a=tensor([1, 2, 3], device='cuda:0'), b=tensor([1, 2, 3], device='cuda:0'), c=tensor([2, 4, 6], device='cuda:0')
/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_validation.py:114: UserWarning: WARNING: failed to get cudart_version from onnxruntime build info.
  warnings.warn("WARNING: failed to get cudart_version from onnxruntime build info.")
Traceback (most recent call last):
  File "/mnt/pv/notebooks/smishra/torch_compile_error.py", line 17, in <module>
    c_compiled = add_tensors_compiled(a, b)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
                       ^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 919, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/__init__.py", line 1662, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/debug.py", line 305, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
    return self.compile_to_module().call
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1070, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1892, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_ray/ou/cou5lpnmw3pu2wttvcehhpf7x4qtl47sgysbgnpxel3l6uecylhj.py", line 63, in <module>
    async_compile.wait(globals())
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2471, in wait
    scope[key] = result.result()
                 ^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2315, in result
    kernel = self.kernel = _load_kernel(self.kernel_name, self.source_code)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2291, in _load_kernel
    kernel.precompile()
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/triton_heuristics.py", line 188, in precompile
    compiled_binary, launcher = self._precompile_config(
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/torch/_inductor/triton_heuristics.py", line 308, in _precompile_config
    binary._init_handles()
  File "/home/ray/anaconda3/envs/pytorch-temp/lib/python3.11/site-packages/triton/compiler/compiler.py", line 683, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

Output of `TORCHDYNAMO_REPRO_AFTER="dynamo" python torch_compile_error.py`

```python
from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import torch._dynamo
from torch._dynamo.testing import rand_strided
from torch._dynamo.debug_utils import run_fwd_maybe_bwd

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config
import torch.fx.experimental._config









from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, L_a_ : torch.Tensor, L_b_ : torch.Tensor):
        l_a_ = L_a_
        l_b_ = L_b_
        c = l_a_ + l_b_;  l_a_ = l_b_ = None
        return (c,)


mod = Repro()

def load_args(reader):
    buf0 = reader.storage('e2d1839ed1706f7d470d87f8c48a5584cafa5a12', 24, device=device(type='cuda', index=0), dtype_hint=torch.int64)
    reader.tensor(buf0, (3,), dtype=torch.int64, is_leaf=True)  # L_a_
    buf1 = reader.storage('e2d1839ed1706f7d470d87f8c48a5584cafa5a12', 24, device=device(type='cuda', index=0), dtype_hint=torch.int64)
    reader.tensor(buf1, (3,), dtype=torch.int64, is_leaf=True)  # L_b_
load_args._version = 0

if __name__ == '__main__':
    from torch._dynamo.repro.after_dynamo import run_repro
    run_repro(mod, load_args, accuracy=False, command='minify',
        save_dir='/mnt/pv/notebooks/smishra/torch_compile_debug/run_2024_02_02_10_49_36_213095-pid_366606/minifier/checkpoints', autocast=False, backend='inductor')
```

### Versions

```
Collecting environment information...
PyTorch version: 2.2.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.254-170.358.amzn2.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             96
On-line CPU(s) list:                0-95
Thread(s) per core:                 2
Core(s) per socket:                 24
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                           7
CPU MHz:                            2962.577
BogoMIPS:                           5999.99
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          1.5 MiB
L1i cache:                          1.5 MiB
L2 cache:                           48 MiB
L3 cache:                           71.5 MiB
NUMA node0 CPU(s):                  0-23,48-71
NUMA node1 CPU(s):                  24-47,72-95
Vulnerability Gather data sampling: Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:        KVM: Vulnerable
Vulnerability L1tf:                 Mitigation; PTE Inversion
Vulnerability Mds:                  Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Vulnerable
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] onnx==1.15.0
[pip3] onnxruntime-training==1.16.3
[pip3] onnxscript==0.1.0.dev20240201
[pip3] torch==2.2.0+cu118
[pip3] triton==2.2.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.2.0+cu118              pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by eellison** [comment]
I think you have a bad triton build locally. This doesn't error for me. Try running examples from triton directly and making sure they work.  E.g. https://github.com/openai/triton/blob/main/python/tutorials/01-vector-add.py

**Comment by eellison** [comment]
cc @malfet in case theres something we can do here related to build

**Comment by malfet** [comment]
@eellison removed topic build, I think it have something to do with the driver version (740), which can not be used to kernel images generated by ptxas bundled with triton.

**Comment by napsternxg** [comment]
Thanks @eellison and @malfet 
Can you share how can I replace the`ptxas bundled into triton wheel with one from CUDA-11.8 toolkit`
I have never encoutered this error before or have used triton before.

**Comment by malfet** [comment]
@napsternxg just set `TRITON_PTXAS_PATH` to point to `/usr/local/cuda-11.8/bin/ptxas` (assuming you have CUDA-11.8 installed in that folder) or run `python3 -c "import triton;print(triton.common.backend.path_to_ptxas())"` and copy ptxas from 11.8 into the folder returned by the command

**Comment by napsternxg** [comment]
Thanks @malfet this worked for me. 

```python
TRITON_PTXAS_PATH="/usr/local/cuda-11.8/bin/ptxas" python torch_compile_error.py
a=tensor([1, 2, 3], device='cuda:0'), b=tensor([1, 2, 3], device='cuda:0'), c=tensor([2, 4, 6], device='cuda:0')
/mnt/pv/notebooks/smishra/envs/pytorch-biggraph/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_validation.py:114: UserWarning: WARNING: failed to get cudart_version from onnxruntime build info.
  warnings.warn("WARNING: failed to get cudart_version from onnxruntime build info.")
c_compiled=tensor([2, 4, 6], device='cuda:0')
```

I also tried using the path using the following command you suggested. 

```bash
python3 -c "import triton;print(triton.common.backend.path_to_ptxas())"
('/mnt/pv/notebooks/smishra/envs/pytorch-biggraph/lib/python3.11/site-packages/triton/common/../third_party/cuda/bin/ptxas', '12.3')
```

However the path returned by the above command leads to the error:

```bash
TRITON_PTXAS_PATH="envs/pytorch-biggraph/bin/ptxas" python torch_compile_error.py
```

**Comment by ptrblck** [comment]
I was able to reproduce the issue on an A100 node with an older driver (470).
If you don't have a locally installed CUDA toolkit, you could also install the needed `ptxas` from the `nvidia-cuda-nvcc-cu11` Python package and point towards it:
```python
python tmp.py 
a=tensor([1, 2, 3], device='cuda:0'), b=tensor([1, 2, 3], device='cuda:0'), c=tensor([2, 4, 6], device='cuda:0')
Traceback (most recent call last):
  File "/workspace/src/tmp.py", line 17, in <module>
...
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
```
```python
pip install nvidia-cuda-nvcc-cu11
TRITON_PTXAS_PATH=/usr/local/lib/python3.10/dist-packages/nvidia/cuda_nvcc/bin/ptxas python tmp.py
a=tensor([1, 2, 3], device='cuda:0'), b=tensor([1, 2, 3], device='cuda:0'), c=tensor([2, 4, 6], device='cuda:0')
{c_compiled=}
```

**Comment by malfet** [comment]
Looks like there are two things to do here:
 - [Easy] Package ptxas into cu-11.8 wheel/conda and define `TRITION_PTXAS_PATH` before invoking the compile
 - [Stretch] Provide a better error message on the triton end

**Comment by napsternxg** [comment]
Thanks @ptrblck your approach also worked for me.

**Comment by eellison** [comment]
Should we close this ?

**Comment by napsternxg** [comment]
Yes

**Comment by malfet** [comment]
@eellison actually, reopening it now, as we want PyTorch usable out-of-box on CUDA-11.8, therefore we need to make small changes to the packaging script.

**Comment by ptrblck** [comment]
https://github.com/pytorch/pytorch/pull/119750 seems to fix the issue in the final `2.2.1RC` and the code runs fine on a V100 using NVIDIA driver 470.

**Comment by zhangvia** [comment]
i'm using torch2.3.0+cu118, with rtx2080ti. driver version is 515.65.01,cuda toolkit version is 11.8. i still got this error with the torch_compile_error.py

**Comment by f-fuchs** [comment]
Also got this problem with following setup:
torch=2.4.0+cu118
Driver Version: 470.239.06
CUDA Version: 11.4 
NVIDIA TITAN V

**Comment by meoqi** [comment]
> I was able to reproduce the issue on an A100 node with an older driver (470). If you don't have a locally installed CUDA toolkit, you could also install the needed `ptxas` from the `nvidia-cuda-nvcc-cu11` Python package and point towards it:
> 
> ```python
> python tmp.py 
> a=tensor([1, 2, 3], device='cuda:0'), b=tensor([1, 2, 3], device='cuda:0'), c=tensor([2, 4, 6], device='cuda:0')
> Traceback (most recent call last):
>   File "/workspace/src/tmp.py", line 17, in <module>
> ...
> RuntimeError: Triton Error [CUDA]: device kernel image is invalid
> ```
> 
> ```python
> pip install nvidia-cuda-nvcc-cu11
> TRITON_PTXAS_PATH=/usr/local/lib/python3.10/dist-packages/nvidia/cuda_nvcc/bin/ptxas python tmp.py
> a=tensor([1, 2, 3], device='cuda:0'), b=tensor([1, 2, 3], device='cuda:0'), c=tensor([2, 4, 6], device='cuda:0')
> {c_compiled=}
> ```

very helpful, thank you so much!!

**Comment by ChengsongLu** [comment]
> ```python
> TRITON_PTXAS_PATH="/usr/local/cuda-11.8/bin/ptxas"
> ```

TRITON_PTXAS_PATH="/usr/local/cuda-11.8/bin/ptxas"

This setting also works for me, totally sovle my problem!
