### ISSUE TITLE
torch.full can't accept only SymInt as argument (without wrapping tuple)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119042]
### 🐛 Describe the bug

In test_proxy_tensor.py

```
    def test_full_symint_arg(self):
        def f(inp):
            return torch.full(inp.item(), 5)

        make_fx(f, tracing_mode="symbolic")(torch.tensor(12))
```

this test fails with

```
======================================================================
ERROR: test_full_symint_arg (__main__.TestSymbolicTracing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/torch/testing/_internal/common_utils.py", line 2698, in wrapper
    method(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/test/test_proxy_tensor.py", line 1730, in test_full_symint_arg
    make_fx(f, tracing_mode="symbolic")(torch.tensor(12))
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/proxy_tensor.py", line 1187, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/data/users/ezyang/a/pytorch/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 452, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/proxy_tensor.py", line 635, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/users/ezyang/a/pytorch/torch/fx/_symbolic_trace.py", line 793, in trace
    (self.create_arg(fn(*args)),),
  File "/data/users/ezyang/a/pytorch/torch/fx/experimental/proxy_tensor.py", line 665, in wrapped
    out = f(*tensors)
  File "/data/users/ezyang/a/pytorch/test/test_proxy_tensor.py", line 1728, in f
    return torch.full(inp.item(), 5)
TypeError: full(): argument 'size' (position 1) must be tuple of ints, not SymInt
```

Somewhat surprisingly, this ALSO happens when you do the equivalent program in Dynamo.

### Versions

main

**Comment by tringwald** [comment]
Isn't that the desired behavior? I guess it would be confusing to be able to write `torch.full(3, 3, 5)` instead of `torch.full((3, 3), 5)` (aka `torch.full(size=(3, 3), fill_value=5)`). It would probably work if `fill_value` was a keyword-only argument.

**Comment by ezyang** [comment]
Oh oops, I didn't even realize that the non-SymInt version didn't work. Carry on!
