### ISSUE TITLE
Dynamo displays errors when accessing `needs_input_grad` in custom function

### ISSUE THREAD

**Issue by tohtana** [pytorch/pytorch#119059]
### 🐛 Describe the bug

Dynamo displays error outputs when you access `needs_input_grad` in a custom function though it produces the correct result. Here is the repro.

```python
import torch

class UseNeedsInputGradFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        return x

    @staticmethod
    def backward(ctx, grad_output):
        if ctx.needs_input_grad[0]:
            return grad_output
        return None

def linear(x):
    return UseNeedsInputGradFunction.apply(x)

linear = torch.compile(linear)
x = torch.randn(4, 128, requires_grad=True)
y = linear(x)
```

The output is
```
[2024-02-02 11:31:02,500] [0/0] torch._dynamo.variables.higher_order_ops: [WARNING] speculate_subgraph: while introspecting autograd.Function, we were unable to trace function `backward` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown.
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR] call_method GetAttrVariable(AutogradFunctionContextVariable(Function), needs_input_grad) __getitem__ (ConstantVariable(int),) {}
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR] Traceback (most recent call last):
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 381, in speculate_subgraph
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     output = f.call_function(tx, args, sub_kwargs)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 279, in call_function
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return super().call_function(tx, args, kwargs)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 87, in call_function
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return tx.inline_user_function_return(
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 657, in inline_user_function_return
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2261, in inline_call
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return cls.inline_call_(parent, func, args, kwargs)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2370, in inline_call_
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     tracer.run()
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 787, in run
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     and self.step()
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 750, in step
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     getattr(self, inst.opname)(inst)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 469, in wrapper
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return inner_fn(self, inst)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 241, in impl
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     self.push(fn_var.call_function(self, self.popn(nargs), {}))
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/variables/builtin.py", line 694, in call_function
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     result = handler(tx, *args, **kwargs)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/variables/builtin.py", line 1062, in call_getitem
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return args[0].call_method(tx, "__getitem__", args[1:], kwargs)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 364, in call_method
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     raise unimplemented(f"call_method {self} {name} {args} {kwargs}")
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/aiscuser/.conda/envs/tcomp/lib/python3.9/site-packages/torch/_dynamo/exc.py", line 190, in unimplemented
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR]     raise Unsupported(msg)
[2024-02-02 11:31:02,501] [0/0] torch._dynamo.variables.higher_order_ops: [ERROR] torch._dynamo.exc.Unsupported: call_method GetAttrVariable(AutogradFunctionContextVariable(Function), needs_input_grad) __getitem__ (ConstantVariable(int),) {}
```

### Versions

```
PyTorch version: 2.3.0.dev20240202+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1045-azure-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.86.10
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      48 bits physical, 48 bits virtual
CPU(s):                             96
On-line CPU(s) list:                0-95
Thread(s) per core:                 1
Core(s) per socket:                 48
Socket(s):                          2
NUMA node(s):                       4
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              49
Model name:                         AMD EPYC 7V12 64-Core Processor
Stepping:                           0
CPU MHz:                            3254.227
BogoMIPS:                           4890.86
Hypervisor vendor:                  Microsoft
Virtualization type:                full
L1d cache:                          3 MiB
L1i cache:                          3 MiB
L2 cache:                           48 MiB
L3 cache:                           384 MiB
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Mitigation; untrained return thunk; SMT disabled
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru arat umip rdpid

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==3.0.0+901819d2b6
[pip3] torch==2.3.0.dev20240202+cu118
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.2.0.dev20240202+cu118
[pip3] torchvision==0.18.0.dev20240202+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            3.0.0+901819d2b6          pypi_0    pypi
[conda] torch                     2.3.0.dev20240202+cu118          pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchaudio                2.2.0.dev20240202+cu118          pypi_0    pypi
[conda] torchvision               0.18.0.dev20240202+cu118          pypi_0    pypi
```

cc @zou3519 @ydwu4

**Comment by zou3519** [comment]
We shouldn't actually be printing anything on a graph break like this

**Comment by zou3519** [comment]
Does torch.compile print these logs everywhere? Or is it just for HOPs?

**Comment by ydwu4** [comment]
> Does torch.compile print these logs everywhere? Or is it just for HOPs?

It's just these two lines, which corresponds to WARNING and Error https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/higher_order_ops.py#L451-L452

**Comment by zou3519** [comment]
Right, my question was: are there other places in torch.compile that we print logs during normal execution of code?

If not, then we probably want to hide the HOP logs behind TORCH_LOGS="dynamo" (I'm not sure how to do that)

**Comment by ydwu4** [comment]
yeah, I think we're doing in the correct way in HOO. Serious messages like warning or exception are logged even no TORCH_LOGS flags are on. TORCH_LOGS=dynamo is just INFO log, and +dynamo includes DEBUG log. Probabaly, we could change warn and exception to debug and info? So that it's hidden from users if it's a normal graph break.

**Comment by zou3519** [comment]
> Probabaly, we could change warn and exception to debug and info? So that it's hidden from users if it's a normal graph break.

Yeah that sounds good

**Comment by tohtana** [comment]
Thank you @zou3519 @ydwu4 for your fix! This will definitely resolve my issue.
