### ISSUE TITLE
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::tile' to ONNX opset version 17 is not supported.

### ISSUE THREAD

**Issue by duxuan11** [pytorch/pytorch#119155]
### 🐛 Describe the bug

torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::tile' to ONNX opset version 17 is not supported.

### Versions

my code as follow.
```python
def export_onnx(onnx_model, output, dynamic_axes, dummy_inputs, output_names):
    with open(output, "wb") as f:
        print(f"Exporting onnx model to {output}...")
        torch.onnx.export(
            onnx_model,
            tuple(dummy_inputs.values()),
            f,
            export_params=True,
            verbose=False,
            opset_version=17,
            do_constant_folding=True,
            input_names=list(dummy_inputs.keys()),
            output_names=output_names,
            dynamic_axes=dynamic_axes,
        )
```
![2024-02-05_101246](https://github.com/pytorch/pytorch/assets/64136561/e3df8eeb-e751-42ec-9204-d91025525084)

errors would be displayed after running
***raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::tile' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
![2024-02-05_101246](https://github.com/pytorch/pytorch/assets/64136561/f7c7c194-ceda-4390-af09-00e781691502)

**Comment by titaiwangms** [comment]
Hi @duxuan11 

We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team

**Comment by ZhangYuef** [comment]
> Hi @duxuan11
> 
> We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!
> 
> Thanks, ONNX Converter team

I met following error when using `torch.onnx.dynamo_export` API:
```
/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/exporter.py:136: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(
---------------------------------------------------------------------------
GuardOnDataDependentSymNode               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py](https://localhost:8080/#) in run_node(tracer, node, args, kwargs, nnmodule)
   1765             elif op == "call_method":
-> 1766                 return getattr(args[0], node.target)(*args[1:], **kwargs)
   1767             elif op == "call_module":

58 frames
GuardOnDataDependentSymNode: Could not guard on data-dependent expression u0 (unhinted: u0).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 1766, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/usr/local/lib/python3.10/dist-packages/compressai/models/google.py", line 537, in forward
    z_hat, z_likelihoods = self.entropy_bottleneck(z)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/compressai/entropy_models/entropy_models.py", line 482, in forward
    x = x.permute(*perm).contiguous()


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: Failed running call_method permute(*(FakeTensor(..., size=(1, 192, 8, 8), grad_fn=<ConvolutionBackward0>), FakeTensor(..., size=(), dtype=torch.int64), FakeTensor(..., size=(), dtype=torch.int64), FakeTensor(..., size=(), dtype=torch.int64), FakeTensor(..., size=(), dtype=torch.int64)), **{}):
Could not guard on data-dependent expression u0 (unhinted: u0).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 1766, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/usr/local/lib/python3.10/dist-packages/compressai/models/google.py", line 537, in forward
    z_hat, z_likelihoods = self.entropy_bottleneck(z)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/compressai/entropy_models/entropy_models.py", line 482, in forward
    x = x.permute(*perm).contiguous()


During handling of the above exception, another exception occurred:

UserError                                 Traceback (most recent call last)
UserError: Tried to use data-dependent value in the subsequent computation. This can happen when we encounter unbounded dynamic value that is unknown during tracing time.  You will need to explicitly give hint to the compiler. Please take a look at constrain_as_value OR constrain_as_size APIs.  Could not guard on data-dependent expression u0 (unhinted: u0).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 1766, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/usr/local/lib/python3.10/dist-packages/compressai/models/google.py", line 537, in forward
    z_hat, z_likelihoods = self.entropy_bottleneck(z)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/compressai/entropy_models/entropy_models.py", line 482, in forward
    x = x.permute(*perm).contiguous()

For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#constrain-as-size-example

from user code:
   File "/usr/local/lib/python3.10/dist-packages/compressai/models/google.py", line 537, in forward
    z_hat, z_likelihoods = self.entropy_bottleneck(z)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/compressai/entropy_models/entropy_models.py", line 482, in forward
    x = x.permute(*perm).contiguous()

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


The above exception was the direct cause of the following exception:

OnnxExporterError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/exporter.py](https://localhost:8080/#) in dynamo_export(model, export_options, *model_args, **model_kwargs)
   1437             f"Please report a bug on PyTorch Github: {_PYTORCH_GITHUB_ISSUES_URL}"
   1438         )
-> 1439         raise OnnxExporterError(
   1440             ONNXProgram._from_failure(e, resolved_export_options.diagnostic_context),
   1441             message,

OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
```

**Comment by ghazalb76** [comment]
@ZhangYuef 
Hello,

I have same issue as mentioned even with torch.onnx.dynamo_export API, I get error. Have you fixed your issue?
