### ISSUE TITLE
Incorrect Results from cdist_backward Operator with Input Dimensions Exceeding int32_max

### ISSUE THREAD

**Issue by mahxn0** [pytorch/pytorch#119147]
## Issue Description
I've encountered an issue where the `cdist_backward` operator produces incorrect results when either of its input dimensions `r1 * M` or `r2 * M` exceed the maximum value for `int32` (2,147,483,647). This seems to suggest that there might be an integer overflow happening internally when computing large tensors.

### To Reproduce
1. Use `cdist_backward` operator with inputs that result in dimensions `r1 * M` or `r2 * M` exceeding `int32_max`.
2. Observe incorrect computation results.

```python
# Sample code to reproduce the issue
import torch

# Example tensor dimensions that cause the issue
# Please replace this with the specific dimensions you used
tensor1 = torch.randn([1,1024,1024 * 2050])
tensor2 = torch.randn([1,1024,1024 * 2050])

# Code to demonstrate the issue
result = torch.cdist_backward(tensor1, tensor2, p=2)
print(result)
```
### Possible Cause and My Understanding
Based on my observations and tests, I suspect that the issue might be related to integer overflow within the `cdist_backward` operator's internal computation. This is because the problem occurs when the input dimensions, when multiplied (`r1 * M` or `r2 * M`), exceed the maximum value that an `int32` can represent (2,147,483,647). 
This overflow could potentially cause the internal index calculations or memory allocations to

located the overflow : https://github.com/pytorch/pytorch/blob/7bcf7da3a268b435777fe87c7794c382f444e86d/aten/src/ATen/native/cuda/DistanceKernel.cu#L133
```c++
const int l = y / r_size;
const int k = y % r_size;
const int stride = blockDim.x * gridDim.x;
const int l_size = r_size * m;
```

### Versions

 torch2.1/torch1.13/torch1.9

**Comment by zou3519** [comment]
I'm moderately concerned that torch.cdist_backward is exposed (it shouldn't be)

**Comment by zou3519** [comment]
@mahxn0 we can't reproduce this. torch.cdist_backward is not callable in PyTorch.

**Comment by mahxn0** [comment]
Hi @zou3519   You can use 
`
import torch
tensor1 = torch.randn([1,1024,2099200],requires_grad=True).cuda()
tensor2 = torch.randn([1,1,2099200]).cuda()
grad = torch.randn([1,1024,1]).cuda()

tensor1.retain_grad()
# Code to demonstrate the issue
dist = torch.cdist(tensor1, tensor2, p=1)
dist.backward(grad)
result = tensor1.grad
print(result.shape)
`
to reproduce it.  

The calculation results of the GPU differ from those of the CPU.

**Comment by mahxn0** [comment]
Also, The cdist_forward op has the same problem.  when output dim exceeding int32_max.
```
import torch

# Example tensor dimensions that cause the issue
# Please replace this with the specific dimensions you used
tensor1 = torch.randn([1,1024 * 2047,1]).cuda()
tensor2 = torch.randn([1,1024,1]).cuda()
result = torch.cdist(tensor1, tensor2, p=1)
print(result.shape)
```
the result shape is 
```
torch.Size([1, 2096128, 1024])
```

When the output exceed int_max(2^31)
```
import torch

# Example tensor dimensions that cause the issue
# Please replace this with the specific dimensions you used
tensor1 = torch.randn([1,1024 * 2050,1]).cuda()
tensor2 = torch.randn([1,1024,1]).cuda()

# Code to demonstrate the issue
result = torch.cdist(tensor1, tensor2, p=1)
print(result.shape)
```
It's caused the error
```
Traceback (most recent call last):
  File "/maxiangjun/cdist/cdist_forward.py", line 9, in <module>
    result = torch.cdist(tensor1, tensor2, p=1)
  File "/usr/local/lib/python3.10/dist-packages/torch/functional.py", line 1315, in cdist
    return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
