### ISSUE TITLE
Problem with CosineEmbeddingLoss()

### ISSUE THREAD

**Issue by linxd5** [pytorch/pytorch#1192]
The Following is the test code for CosineEmbeddingLoss()

```
import torch
from torch.autograd import Variable

cuda_num = 2
batch_size = 50

loss_fn = torch.nn.CosineEmbeddingLoss().cuda(cuda_num)


for i in range(500):
    sentences = Variable(torch.randn(batch_size, 300)).cuda(cuda_num)
    images = Variable(torch.randn(batch_size, 400)).cuda(cuda_num)
    flags = Variable(torch.ones(batch_size)).cuda(cuda_num)

    fc = torch.nn.Linear(400, 300).cuda(cuda_num)
    optimizer = torch.optim.SGD(fc.parameters(), lr=1e-4)
    img_emb = fc(images)
    sen_emb = sentences

    loss = loss_fn(img_emb, sen_emb, flags)
    print 'Batch_id %d \t  loss %.2f' %(i, loss.data.mean())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

```

In my compute, it raise the following traceback:
```
Traceback (most recent call last):
  File "test2.py", line 19, in <module>
    loss = loss_fn(img_emb, sen_emb, flags)
  File "/home/lindayong/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lindayong/anaconda2/lib/python2.7/site-packages/torch/nn/modules/loss.py", line 365, in forward
    self.size_average)(input1, input2, target)
  File "/home/lindayong/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/loss.py", line 47, in forward
    torch.eq(y, -1, out=_idx)
RuntimeError: arguments are located on different GPUs at /data/users/soumith/builder/wheel/pytorch-src/torch/lib/THC/generated/../generic/THCTensorMathCompare.cu:39
```

There are three GPUs in my computer, the bug arises when I set cuda_num to 1 or 2, but no bug when I set cuda_num to 0.

**Comment by soumith** [comment]
are you on an old version of torch? I am on `0.1.11` and this works fine for me.
You can check your torch version with `print(torch.__version__)`

**Comment by linxd5** [comment]
My torch version is 0.1.10，I solve this problem by two ways：
- Change cuda(cuda_num) to cuda()，this works fine but the program runs at GPU 0 by default。Run the code by `CUDA_VISIBLE_DEVICES=num python xx.py` to enforce it  run at GPU num. 
- Follow the solution by soumith，I upgrade my torch version to 0.1.11，and the code works fine simply by `python xx.py`

Thanks a lot !!!!
