### ISSUE TITLE
Cannot install or import PyTorch Nightly

### ISSUE THREAD

**Issue by iSach** [pytorch/pytorch#119447]
### 🐛 Describe the bug

I am unable to install PyTorch Nightly (`2.3.0.dev20240208`) using conda, on both Mac and Linux. 

On Mac:
```
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pytorch-nightly/noarch                                        No change
pytorch-nightly/linux-64                                      No change

Pinned packages:
  - python 3.9.*

error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ pin-1 is installable and it requires
    │  └─ python 3.9.* , which can be installed;
    ├─ pytorch is installable with the potential options
    │  ├─ pytorch [2.3.0.dev20240207|2.3.0.dev20240208] would require
    │  │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
    │  ├─ pytorch [2.3.0.dev20240207|2.3.0.dev20240208], which can be installed;
    │  ├─ pytorch [2.3.0.dev20240207|2.3.0.dev20240208] would require
    │  │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
    │  ├─ pytorch [2.3.0.dev20240207|2.3.0.dev20240208] would require
    │  │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
    │  ├─ pytorch [2.3.0.dev20240207|2.3.0.dev20240208] would require
    │  │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
    │  └─ pytorch 2.3.0.dev20240207 would require
    │     └─ pytorch-cuda >=12.1,<12.2 , which requires
    │        └─ libcublas >=12.1.0.26,<12.1.3.1 , which does not exist (perhaps a missing channel);
    └─ torchaudio is not installable because there are no viable options
       ├─ torchaudio 2.2.0.dev20240110 would require
       │  └─ pytorch 2.3.0.dev20240110 , which conflicts with any installable versions previously reported;
       ├─ torchaudio 2.1.0.dev20230523 would require
       │  └─ pytorch 2.1.0.dev20230523 , which does not exist (perhaps a missing channel);
       └─ torchaudio 2.2.0.dev20240206 would require
          └─ pytorch 2.3.0.dev20240206 , which does not exist (perhaps a missing channel).
critical libmamba Could not solve for environment specs
```

On Linux:
```
❯ conda install pytorch torchvision torchaudio cpuonly -c pytorch-nightly
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pytorch-nightly/noarch                                        No change
pytorch-nightly/linux-64                                      No change

Pinned packages:
  - python 3.12.*

error    libmamba Could not solve for environment specs
    The following packages are incompatible
    └─ torchaudio is not installable because there are no viable options
       ├─ torchaudio 2.1.0.dev20230523 would require
       │  └─ pytorch 2.1.0.dev20230523 , which does not exist (perhaps a missing channel);
       └─ torchaudio 2.2.0.dev20240206 would require
          └─ pytorch 2.3.0.dev20240206 , which does not exist (perhaps a missing channel).
critical libmamba Could not solve for environment specs
```

Using pip, it is installed, but it is impossible to import it on Mac. Both issues happen on **clean environments on Python 3.10, 11 or 12**.

```
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sach/micromamba/envs/dl/lib/python3.12/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/sach/micromamba/envs/dl/lib/python3.12/site-packages/torch/_C.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '__PyCode_GetExtra'
```

On Linux, the pip install works (`2.3.0.dev20240207`). But on Mac, it is impossible to use any nightly build.

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.3.0.dev20240207
[pip3] torchaudio==2.2.0.dev20240207
[pip3] torchvision==0.18.0.dev20240207
[conda] Could not collect
```

**Comment by lamroger** [comment]
Hey @iSach did you find a workaround / solution? I'm running into the same issue.

**Comment by lamroger** [comment]
Ah I figured it out - I had semi-old files in /build. Deleting the build folder and rebuilding fixed it for me...

**Comment by danni-cool** [comment]
same problem, what's the full path of /build ?
