### ISSUE TITLE
`hf_Longformer` fails on L4 GPU

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#119680]
### 🐛 Describe the bug

By default, `hf_Longformer` benchmark is flagged as "skip" for L4 GPU (24G) [due to OOM problem](https://github.com/pytorch/pytorch/blob/24bdd03d23d883e3eaa19b3002e62995987dfd0f/benchmarks/dynamo/common.py#L3530-L3537). However, trying to actually execute it yields an odd syntax error:

```
python benchmarks/dynamo/torchbench.py \
    --performance --cold-start-latency --inference --bfloat16 \
    --backend inductor --disable-cudagraphs --device cuda \
    --no-skip --filter hf_Longformer
```

```python
Traceback (most recent call last):
  File "benchmarks/dynamo/common.py", line 2626, in warmup
    fn(model, example_inputs)
  File "torch/_dynamo/eval_frame.py", line 454, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/torchbench.py", line 469, in forward_pass
    return mod(*inputs)
  File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/longformer/modeling_longformer.py", line 1835, in forward
    outputs = self.longformer(
  File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 904, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "torch/_dynamo/convert_frame.py", line 769, in _convert_frame
    result = inner_convert(
  File "torch/_dynamo/convert_frame.py", line 398, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/convert_frame.py", line 669, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/utils.py", line 249, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 542, in compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 507, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2130, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 793, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 756, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 465, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
  File "torch/_dynamo/symbolic_convert.py", line 529, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "torch/_dynamo/output_graph.py", line 957, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 1102, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 249, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1175, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1156, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/_dynamo/backends/inductor.py", line 16, in inductor
    return compile_fx(*args, **kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_inductor/compile_fx.py", line 1321, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 57, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 879, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "torch/_dynamo/utils.py", line 249, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 604, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "torch/_dynamo/utils.py", line 249, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 1249, in fw_compiler_base
    return inner_compile(
  File "torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_inductor/compile_fx.py", line 423, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "torch/_inductor/compile_fx.py", line 689, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "torch/_inductor/graph.py", line 1224, in compile_to_fn
    return self.compile_to_module().call
  File "torch/_dynamo/utils.py", line 249, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/graph.py", line 1176, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "torch/_inductor/codecache.py", line 2053, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/tmp5ls2v_my/io/ciolxyg77mheg573qaho5t32aqnprvya2w76vofp5suboejsq6hb.py", line 223, in <module>
    async_compile.wait(globals())
  File "torch/_inductor/codecache.py", line 2593, in wait
    scope[key] = result.result()
  File "torch/_inductor/codecache.py", line 2400, in result
    self.future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Failed to import /tmp/torchinductor/fs/cfsnwopnp6zcdyj27ovqkeiddku6uwipcqa56xnsa3uhn3xd6mrx.py
SyntaxError: invalid syntax (cfsnwopnp6zcdyj27ovqkeiddku6uwipcqa56xnsa3uhn3xd6mrx.py, line 43)
```

<details>
<summary>cfsnwopnp6zcdyj27ovqkeiddku6uwipcqa56xnsa3uhn3xd6mrx.py</summary>

```python
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_heuristics import AutotuneHint, reduction
from torch._inductor.utils import instance_descriptor
from torch._inductor import triton_helpers
from triton.compiler.compiler import AttrsDescriptor

@triton.jit
def _triton_helper_fn0(arg0, arg1):
    tmp0 = arg0 + arg1
    return tmp0

@reduction(
    size_hints=[1, 4096],
    reduction_hint=ReductionHint.INNER,
    filename=__file__,
    triton_meta={'signature': {0: '*i64', 1: '*i64', 2: 'i32', 3: 'i32'}, 'device': 0, 'device_type': 'cuda', 'constants': {}, 'configs': [AttrsDescriptor(divisible_by_16=(0, 1, 3), equal_to_1=(), ids_of_folded_args=(), divisible_by_8=(3,))]},
    inductor_meta={'autotune_hints': set(), 'kernel_name': 'triton_red_fused__to_copy_cumsum_ne_0', 'mutated_arg_names': [], 'no_x_dim': False}
)
@triton.jit
def triton_(in_ptr0, out_ptr0, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xnumel = 1
    rnumel = 4096
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rbase = tl.arange(0, RBLOCK)[None, :]
    tmp6 = tl.full([1, 1], 0, tl.int64)
    tmp7 = tl.full([XBLOCK, 1], 0, tl.int64)
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp0 = tl.load(in_ptr0 + (r0), None, eviction_policy='evict_last')
        tmp1 = tl.full([1, 1], 1, tl.int64)
        tmp2 = tmp0 != tmp1
        tmp3 = tmp2.to(tl.int32)
        tmp4 = tmp3.to(tl.int64)
        tmp5 = tl.broadcast_to(tmp4, [XBLOCK, RBLOCK])
        # ========================================================================
        tmp8 = tl.where(, tmp5, tmp6)  # <<========================== Syntax Error
        # ========================================================================
        tmp9 = tl.reduce(tmp5, 1, _triton_helper_fn0)[:, None]
        tmp10 = tmp7 + tmp9
        tmp11 = tl.associative_scan(tmp8, 1, _triton_helper_fn0)
        tmp12 = tmp7 + tmp11
        tmp7 = tmp10
        tl.store(out_ptr0 + (tl.broadcast_to(r0, [XBLOCK, RBLOCK])), tmp12, None)
```

</details>

### Versions

- PyTorch: 5d6e323549bd5d3997e8c344532e611078be7011
- PyTorch/benchmark: [62f4e9c6427b467ba77d06fc9952bf4a28204488](https://github.com/pytorch/benchmark/commit/62f4e9c6427b467ba77d06fc9952bf4a28204488)

cc @miladm @lezcano @peterbell10 @ezyang

**Comment by lezcano** [comment]
Can you copy the inputs of the output file? That looks like an issue with inductor's codegen.

**Comment by lezcano** [comment]
Ah, I see the file now. That was fixed in https://github.com/pytorch/pytorch/pull/119555
