### ISSUE TITLE
Jit cannot trace autograd for certain operator

### ISSUE THREAD

**Issue by ozzzp** [pytorch/pytorch#11967]
## Issue description

`torch.jit.trace` can not trace `torch.autograd.grad` for some cetrain operator(SliceBackward)

## Code example

code:
```python
import torch

def test(fun):
    x = torch.ones([1, 4], requires_grad=True)
    y = fun(x)

    @torch.jit.trace(torch.zeros([1, 4]))
    def difference_forward(z):
        return torch.autograd.grad(y, x, grad_outputs=z, retain_graph=True)

    print(difference_forward(torch.ones([1, 4])))

if __name__ == '__main__':
    test(lambda x: x * x)
    test(lambda x: x[0:1])
```

output:
```bash
tensor([[2., 2., 2., 2.]])
Traceback (most recent call last):
  File "playground.py", line 16, in <module>
    test(lambda x: x[0:1])
  File "playground.py", line 7, in test
    @torch.jit.trace(torch.zeros([1, 4]))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 310, in wrapper
    module._create_method_from_trace('forward', func, args)
  File "playground.py", line 9, in difference_forward
    return torch.autograd.grad(y, x, grad_outputs=z, retain_graph=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 145, in grad
    inputs, allow_unused)
RuntimeError: saved_variables() needed but not implemented in SliceBackward
```

## System Info
- PyTorch version: 0.5.0a0+4ad6e53
- Is debug build: No
- CUDA used to build PyTorch: 9.1.85

- OS: Ubuntu 16.04.5 LTS
- GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CMake version: version 3.5.1

- Python version: 3.6
- Is CUDA available: Yes
- CUDA runtime version: Could not collect
- GPU models and configuration: GPU 0: GeForce GTX 1080
- Nvidia driver version: 396.37
- cuDNN version: Probably one of the following:
- /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
- [pip] Could not collect
- [conda] Could not collect

**Comment by zou3519** [comment]
This needs mutability in the JIT, which is something we're working on. Stay tuned.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
