### ISSUE TITLE
[NestedSubTensor] add communication operators support

### ISSUE THREAD

**Issue by yaochengji** [pytorch/pytorch#119714]
### 🚀 The feature, motivation and pitch

I'm trying to combine DTensor and NestedTensor to support the sharding of variable length sequences. Therefore, it is essential to make NestedTensor support communication ops.

### Alternatives

I'd love to contribute. The straightforward way to support this seems to add code in the __torch_function__ of NestedTensor.

But when I `print(func)` in __torch_function__, I got `<method-wrapper '__get__' of getset_descriptor object at 0x7f76721e57c0>`, which makes it difficult to know whether it's a communication op or not.

Below is the code to test the case:
```
import torch
from torch.testing._internal.distributed.fake_pg import FakeStore
import torch.distributed as dist
from torch.nested import nested_tensor

hidden_size = 2
device = "cpu"
seq_lengths = [2, 3, 4, 5]
input_tensors = []
world_size = 2
for seqlen in seq_lengths:
    input_tensor = torch.randn(seqlen, hidden_size, device=device, requires_grad=False)
    input_tensor = input_tensor.detach().clone()
    input_tensors.append(input_tensor)


store = FakeStore()
dist.init_process_group(backend="fake", rank=0, world_size=world_size, store=store)

nested_input_tensor = nested_tensor(input_tensors, layout=torch.jagged)
nested_output_tensor = dist.scatter(nested_input_tensor, src=1)
```

**Comment by wconstab** [comment]
is your print(func) only firing once? i was looking at the code for 'scatter' in distributed_c10d.py and it does a few checks on dtype and other things before calling into c++ layer.  also the collective itself doesn't go through the dispatcher at first, it goes through pybind.  i think later on the c++ code calls into dispatcher. it's possible this is causing part of your problem, but i wonder if the __get__ is coming from unwrapping nestedtensor to get dtype or something like that. do you have a stacktrace for when print(func) got called?

cc @wanchaol @bdhirsh

**Comment by yaochengji** [comment]
@wconstab thanks for replying, here is the stacktrace. You will find the error comes from the dispatcher. And then I added a line ` print("func: ", func)` in the `\_\_torch_function\_\_` method of `torch/nested/_internal/nested_tensor.py`, I got `func:  <method-wrapper '__get__' of getset_descriptor object at 0x7fa4161fbe00>`. 

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data00/chengji.yao/docker/nested_scatter.py", line 21, in <module>
[rank0]:     nested_output_tensor = dist.scatter(nested_input_tensor, src=1)
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/nightly/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/nightly/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 3165, in scatter
[rank0]:     work = default_pg.scatter(output_tensors, input_tensors, opts)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: NotImplementedError: Could not run 'c10d::scatter_' with arguments from the 'AutogradNestedTensor' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'c10d::scatter_' is only available for these backends: [CPU, CUDA, PrivateUse1, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

[rank0]: CPU: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/torch/csrc/distributed/c10d/Ops.cpp:511 [kernel]
[rank0]: CUDA: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/torch/csrc/distributed/c10d/Ops.cpp:511 [kernel]
[rank0]: PrivateUse1: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/torch/csrc/distributed/c10d/Ops.cpp:511 [kernel]
[rank0]: Meta: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/MetaFallbackKernel.cpp:23 [backend fallback]
[rank0]: BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
[rank0]: Python: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/PythonFallbackKernel.cpp:154 [backend fallback]
[rank0]: FuncTorchDynamicLayerBackMode: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/functorch/DynamicLayer.cpp:498 [backend fallback]
[rank0]: Functionalize: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/FunctionalizeFallbackKernel.cpp:324 [backend fallback]
[rank0]: Named: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
[rank0]: Conjugate: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
[rank0]: Negative: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
[rank0]: ZeroTensor: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
[rank0]: ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
[rank0]: AutogradOther: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:53 [backend fallback]
[rank0]: AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:57 [backend fallback]
[rank0]: AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:65 [backend fallback]
[rank0]: AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:69 [backend fallback]
[rank0]: AutogradMPS: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:77 [backend fallback]
[rank0]: AutogradXPU: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:61 [backend fallback]
[rank0]: AutogradHPU: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:90 [backend fallback]
[rank0]: AutogradLazy: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:73 [backend fallback]
[rank0]: AutogradMeta: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/VariableFallbackKernel.cpp:81 [backend fallback]
[rank0]: Tracer: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/torch/csrc/autograd/TraceTypeManual.cpp:297 [backend fallback]
[rank0]: AutocastCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/autocast_mode.cpp:378 [backend fallback]
[rank0]: AutocastCUDA: fallthrough registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/autocast_mode.cpp:244 [backend fallback]
[rank0]: FuncTorchBatched: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:732 [backend fallback]
[rank0]: BatchedNestedTensor: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:759 [backend fallback]
[rank0]: FuncTorchVmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
[rank0]: Batched: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
[rank0]: VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
[rank0]: FuncTorchGradWrapper: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/functorch/TensorWrapper.cpp:203 [backend fallback]
[rank0]: PythonTLSSnapshot: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/PythonFallbackKernel.cpp:162 [backend fallback]
[rank0]: FuncTorchDynamicLayerFrontMode: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/functorch/DynamicLayer.cpp:494 [backend fallback]
[rank0]: PreDispatch: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/PythonFallbackKernel.cpp:166 [backend fallback]
[rank0]: PythonDispatcher: registered at /opt/conda/conda-bld/pytorch_1707982978259/work/aten/src/ATen/core/PythonFallbackKernel.cpp:158 [backend fallback]
```

**Comment by yaochengji** [comment]
The request for enhancing the Nested Tensor (NJT) originates from my consideration of how to enable expert parallelism of MoE model while accommodating unbalanced expert tokens. In this context, I envision the user code as follows:

```
import torch
import torch.distributed as dist
from torch.nested import nested_tensor
from torch import nn
import torch
from torch.distributed._tensor import (
    Shard,
    distribute_tensor,
    init_device_mesh,
)

device_mesh = init_device_mesh("cpu", (2,))
hidden_size = 2
device = "cpu"
seq_lengths = [2, 3, 4, 5]
input_tensors = []
world_size = 2
num_experts = 4


class Experts(nn.Module):
    def __init__(self):
        self.w0 = distribute_tensor(
            nn.Parameter(torch.Tensor(num_experts, hidden_size, hidden_size)),
            device_mesh,
            [Shard(0)],
        )
        self.act = torch.nn.GELU()
        self.w1 = distribute_tensor(
            nn.Parameter(torch.Tensor(num_experts, hidden_size, hidden_size)),
            device_mesh,
            [Shard(0)],
        )

    def forward(self, x):
        x = torch.bmm(x, self.w0)
        x = self.act(x)
        x = torch.bmm(x, self.w1)
        return x


if __name__ == "__main__":
    for seqlen in seq_lengths:
        input_tensor = torch.randn(seqlen, hidden_size, device=device, requires_grad=False)
        input_tensor = input_tensor.detach().clone()
        input_tensors.append(input_tensor)

    nested_input = nested_tensor(input_tensors, layout=torch.jagged)
    nested_dinput = distribute_tensor(nested_tensor, device_mesh, [Shard(0)])
    model = Experts()
    output = model(nested_dinput)
```

**Comment by wconstab** [comment]
Oh, I forgot how torch_function works but I wonder if you need a torch_dispatch subclass in order to intercept these collective calls, since they do not go through the usual torch operator flow in the python layer.

**Comment by wanchaol** [comment]
Thanks for capturing this issue @wconstab!

🤔 So looking at the code snippet, I think there're two separate things:
1. general subclass composability with DTensor: I was planning to write some summary about how to compose other subclass with DTensor as I am working on FP8 composability atm. But tldr is that the subclass need to implement necessary collectives, i.e. allgather/reduce_scatter/allreduce. In addition, to support sharding the large tensor to a Sharded DTensor or Replicated DTensor, subclass would need to implement scatter/broadcast too. However there's a gap on the DTensor side that we would need to use functional scatter/broadcast so that other subclass can overwrite these two collectives (not sure if `c10d::scatter_` can be override in python actually)
2. I think for the specific expert parallelism use case you mentioned, looks like NT need to compose with DTensor as module inputs, not module parameters (we usually use `distribute_tensor` api to shard module params, but not module inputs). For model inputs, usually dataloader should either give a "sharded" on batch or "replicated" torch.Tensor already in multiprocess training, so you can just create DTensor(NestedTensor) via `DTensor.from_local(NT, device_mesh, placement, run_check=False)`. Then in this case you wouldn't need `scatter/broadcast` to be supported in NestedTensor.

For this node snippet I wonder after switching to `DTensor.from_local`, it might just work

**Comment by yaochengji** [comment]
@wconstab @wanchaol thanks for the replying, I got the point. I'd better use functional communication operations, not the c10d ones. Then I can capture the communication ops and implement them for NestedTensor.

For the MoE EP demo user code, yeah it is more appropriate to use DTensor.from_local. However, to support EP with DTensor, other parts of the code, such as the routing part, need to be written using NestedTensor. This may require the insertion of an all-to-all communication operation with NestedTensor inputs or outputs. Therefore, supporting communication operations on NestedTensor is still essential. I believe I can manage this now.
