### ISSUE TITLE
Moving Complex data type tensors from CPU to GPU on M3

### ISSUE THREAD

**Issue by RushabhaB** [pytorch/pytorch#119709]
When I try to move tensors with complex data type from the CPU to the GPU on my M3 using the complex_tensor.to('mps') and try to perform simple arithmetic operations. I get the following. For example, I tried multiplying the complex-valued tensor which was moved to the gpu by 2 and I get the following

`inputs = inputs.to(device) % inputs is complex data type`
`x = 2*inputs`

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: c10::isComplexType(input.scalar_type()) && c10::isComplexType(other.scalar_type()) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/BinaryKernel.mm":340, please report a bug to PyTorch.`

### Versions

PyTorch version: 2.2.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 12:22:05) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.3
[pip3] torch==2.2.0
[pip3] torchmetrics==1.3.0.post0
[pip3] torchvision==0.17.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
[conda] torchmetrics              1.3.0.post0              pypi_0    pypi
[conda] torchvision               0.17.0                   pypi_0    pypi

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by alexicanesse** [comment]
I can reproduce the same error on my M3 Pro with torch version 2.3.0.dev20240124 too.

I am using the following code : 

```python
import torch

# Create a complex tensor with real and imaginary parts
real_part = torch.tensor([1.0, 2.0, 3.0])
imaginary_part = torch.tensor([4.0, 5.0, 6.0])
complex_tensor = torch.view_as_complex(torch.stack([real_part, imaginary_part], dim=-1)).to("mps")

# Perform an arithmetic operation 
x = 2 * complex_tensor
```

The error on my torch version 
```sh
Traceback (most recent call last):
  File "/Users/alexicanesse/Documents/test.py", line 9, in <module>
    x = 2 * complex_tensor
        ~~^~~~~~~~~~~~~~~~
RuntimeError: c10::isComplexType(input.scalar_type()) && c10::isComplexType(other.scalar_type()) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/BinaryKernel.mm":326, please report a bug to PyTorch. 
```

**Comment by alexicanesse** [comment]
The issue is solved on my side with the last nightly build (2.3.0.dev20240215).

**Comment by RushabhaB** [comment]
When you mean it is solved, are you able to execute the command 2*complex_tensor to get the correct output? or did the error message change to incompatible types. Because I am facing the latter with the latest build.

**Comment by alexicanesse** [comment]
I am saying that the line is executed and I get the right result without any error or warnings. 
If it is not your case, please make sure you're trying using the latest nightly build and give us the exact error message.

**Comment by jhavukainen** [comment]
Verified on `torch==2.5.1` that the above script no longer reproduces the error and the output of the computation `2*complex_tensor` is correct.
