### ISSUE TITLE
torch.nn.DataParallel not working

### ISSUE THREAD

**Issue by nkolot** [pytorch/pytorch#11979]
## Issue description

I tried to use torch.nn.DataParallel but apparently I can't get it working on my system. I tried to run it using the **pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime** docker image that you provide but the code crashes and outputs
```
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/4QRVRMEQI3QBEKYYH6Q7RBNTLM:/var/lib/docker/overlay2/l/4IZR47YTZ5HJWUNGSQMIL3GYOF:/var/lib/docker/overlay2/l/TDUFGMDQHXVXDCOZA23WRENEZ7:/var/lib/docker/overlay2/l/R6EAQ3YWCJDBGMF6FGUOLCXBYP:/var/lib/docker/overlay2/l/TZNAQRWOM5NWKXMA2AXYJ4RFJK:/var/lib/docker/overlay2/l/WOYGJ4J5NOOPQUV4VQQGAWIXSO:/var/lib/docker/overlay2/l/YKLJNXYBRFZM2C3NKCAD7DXATB:/var/lib/docker/overlay2/l/747UMECDYK5WGI2TEQ3Q2LBDEX:/var/lib/docker/overlay2/l/6TEFXVS427LG5
```
I also tried it with **pytorch/pytorch:latest** but I am getting the same errors.

When I try to run it using **pytorch/pytorch:0.4.1-cuda9-cudnn7-devel** O a, getting this error:
```
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/J2FT2HKPICOMEUKVP43METQYBR:/var/lib/docker/overlay2/l/EVILMLJWKK7BVPAC6G7LJLYNFO:/var/lib/docker/overlay2/l/XHZIT4K7AY6ZBHBXCRTLCHMIDI:/var/lib/docker/overlay2/l/4OL6DC7JI2REXSF7VHGMGYSI25:/var/lib/docker/overlay2/l/SUNFHBCJREK3HRGBT63IPMJWFS:/var/lib/docker/overlay2/l/HYEVHJ2PSTITOIOIY7PNSRDYHK:/var/lib/docker/overlay2/l/3UHI5T5AMDD7WF6HW7L7RZY3MW:/var/lib/docker/overlay2/l/SCN3CFIVYJIDUVQNNRXA7E6HG7:/var/lib/docker/overlay2/l/2V7SCPNEERUSU'
Unexpected end of /proc/mounts line `A2WTUG6MUW2EZ:/var/lib/docker/overlay2/l/R3ICXG7TJ5FBQAVBDX4O66HTYT:/var/lib/docker/overlay2/l/FCEZES76F7FZAUEZ4B5L3XBRLT:/var/lib/docker/overlay2/l/4NLWRVNBKOTNEPHTBTO74F7QK6:/var/lib/docker/overlay2/l/MCSIH24GTOAYTDCMLBX7ARR6QE:/var/lib/docker/overlay2/l/KDYCLWVCVOD7T4WNTT7YAH3OUF:/var/lib/docker/overlay2/l/P3XIA3QOGD56WY7LOLP2BOWBND:/var/lib/docker/overlay2/l/OKJBQ54KQBLC3T4FFCYCB5SFW2:/var/lib/docker/overlay2/l/6EOMY424KTNZWINHITSNJK3ZJG,upperdir=/var/lib/docker/overlay2/a30be0494ed731c466551e10696c10a'
```

Initially I tried to run it in a custom built docker image that we use (chaneyk/pytorch:0.4.1-py3) and I was getting the following error:
```
Traceback (most recent call last):
  File "dummy_module.py", line 18, in <module>
    y = dm(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 122, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 127, in replicate
    return replicate(module, device_ids)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/replicate.py", line 12, in replicate
    param_copies = Broadcast.apply(devices, *params)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/_functions.py", line 19, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/comm.py", line 40, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 1: unhandled cuda error
```
Note that I tried to run it using pairs of several different types of GPU: Titan Z, Titan X, 1080Ti and Tesla V100 (always of the same type in a pair), but I am always getting the same errors. `torch.cuda.device_count()` always shows 2 for my system, and I tried to explicitly pass `device_ids=[0,1]` in nn.DataParallel but nothing changes. I can successfully copy tensors to both gpus using cuda(0) or cuda(1) so I assume that PyTorch recognizes both GPUs properly. 

## Code example
```
import torch
import torch.nn as nn

class DummyModule(nn.Module):

    def __init__(self):
        super(DummyModule, self).__init__()
        self.m = nn.Linear(10,1)

    def forward(self, x):
        return self.m(x)

if __name__ == '__main__':
    print(torch.cuda.device_count())
    x = torch.ones(16,100,10).cuda()
    dm = nn.DataParallel(DummyModule())
    dm.cuda()
    y = dm(x)
```

## System Info
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX TITAN Z
GPU 1: GeForce GTX TITAN Z

Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.1           py36_cuda9.0.176_cudnn7.1.2_1    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by nkolot** [comment]
Thanks, I can confirm it's working. I am closing this issue.
