### ISSUE TITLE
_c10d_functional.all_reduce cannot be lowered in inductor

### ISSUE THREAD

**Issue by ani300** [pytorch/pytorch#119839]
### 🐛 Describe the bug

When running on the latest nightlies, the new native functional collectives do not work in inductor anymore, with the following traceback.

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/lustre/aviros/fms-oss/scripts/inference.py", line 227, in <module>
[rank0]:     infer(cache, sample)
[rank0]:   File "/lustre/aviros/fms-oss/scripts/inference.py", line 209, in infer
[rank0]:     result = generate(
[rank0]:              ^^^^^^^^^
[rank0]:   File "/lustre/aviros/fms-oss/fms/utils/generation.py", line 75, in generate
[rank0]:     output = model(input_ids, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 454, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 904, in catch_errors
[rank0]:     return callback(frame, cache_entry, hooks, frame_state, skip=1)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 769, in _convert_frame
[rank0]:     result = inner_convert(
[rank0]:              ^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 398, in _convert_frame_assert
[rank0]:     return _compile(
[rank0]:            ^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/contextlib.py", line 81, in inner
[rank0]:     return func(*args, **kwds)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 669, in _compile
[rank0]:     guarded_code = compile_inner(code, one_graph, hooks, transform)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 250, in time_wrapper
[rank0]:     r = func(*args, **kwargs)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 542, in compile_inner
[rank0]:     out_code = transform_code_object(code, transform)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[rank0]:     transformations(instructions, code_options)
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 163, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 507, in transform
[rank0]:     tracer.run()
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2130, in run
[rank0]:     super().run()
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 793, in run
[rank0]:     and self.step()
[rank0]:         ^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 756, in step
[rank0]:     getattr(self, inst.opname)(inst)
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2249, in RETURN_VALUE
[rank0]:     self.output.compile_subgraph(
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 957, in compile_subgraph
[rank0]:     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/contextlib.py", line 81, in inner
[rank0]:     return func(*args, **kwds)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1102, in compile_and_call_fx_graph
[rank0]:     compiled_fn = self.call_user_compiler(gm)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 250, in time_wrapper
[rank0]:     r = func(*args, **kwargs)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1175, in call_user_compiler
[rank0]:     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1156, in call_user_compiler
[rank0]:     compiled_fn = compiler_fn(gm, self.example_inputs())
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
[rank0]:     compiled_gm = compiler_fn(gm, example_inputs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/__init__.py", line 1730, in __call__
[rank0]:     return compile_fx(model_, inputs_, config_patches=self.config)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/contextlib.py", line 81, in inner
[rank0]:     return func(*args, **kwds)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1321, in compile_fx
[rank0]:     return aot_autograd(
[rank0]:            ^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 57, in compiler_fn
[rank0]:     cg = aot_module_simplified(gm, example_inputs, **kwargs)
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 879, in aot_module_simplified
[rank0]:     compiled_fn = create_aot_dispatcher_function(
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 250, in time_wrapper
[rank0]:     r = func(*args, **kwargs)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 604, in create_aot_dispatcher_function
[rank0]:     compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
[rank0]:     return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
[rank0]:     return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
[rank0]:     compiled_fw = compiler(fw_module, updated_flat_args)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 250, in time_wrapper
[rank0]:     r = func(*args, **kwargs)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1249, in fw_compiler_base
[rank0]:     return inner_compile(
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
[rank0]:     inner_compiled_fn = compiler_fn(gm, example_inputs)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/debug.py", line 304, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/contextlib.py", line 81, in inner
[rank0]:     return func(*args, **kwds)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/contextlib.py", line 81, in inner
[rank0]:     return func(*args, **kwds)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 423, in compile_fx_inner
[rank0]:     compiled_graph = fx_codegen_and_compile(
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 674, in fx_codegen_and_compile
[rank0]:     graph.run(*example_inputs)
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 250, in time_wrapper
[rank0]:     r = func(*args, **kwargs)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/graph.py", line 573, in run
[rank0]:     return super().run(*args)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/fx/interpreter.py", line 145, in run
[rank0]:     self.env[node] = self.run_node(node)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/graph.py", line 907, in run_node
[rank0]:     result = super().run_node(n)
[rank0]:              ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/fx/interpreter.py", line 202, in run_node
[rank0]:     return getattr(self, n.op)(n.target, args, kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/graph.py", line 772, in call_function
[rank0]:     raise LoweringException(e, target, args, kwargs).with_traceback(
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/graph.py", line 769, in call_function
[rank0]:     out = lowerings[target](*args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/lowering.py", line 295, in wrapped
[rank0]:     out = decomp_fn(*args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/lowering.py", line 5510, in _all_reduce_
[rank0]:     ir._CollectiveKernel.create_inplace(
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/ir.py", line 7500, in create_inplace
[rank0]:     packed = cls(
[rank0]:              ^^^^
[rank0]:   File "/lustre/aviros/conda_envs/fms-dev/lib/python3.11/site-packages/torch/_inductor/ir.py", line 4651, in __init__
[rank0]:     raise NotImplementedError(
[rank0]: torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[rank0]: LoweringException: NotImplementedError: NYI: Can't generate FallbackKernel for _c10d_functional.all_reduce_.default
[rank0]:   target: _c10d_functional.all_reduce_.default
[rank0]:   args[0]: TensorBox(
[rank0]:     ReinterpretView(
[rank0]:       StorageBox(
[rank0]:         ExternKernelOut(
[rank0]:           python_kernel_name='extern_kernels.mm',
[rank0]:           name=buf21,
[rank0]:           layout=FixedLayout('cuda', torch.float16, size=[44, 4096], stride=[4096, 1]),
[rank0]:           inputs=[ReinterpretView(
[rank0]:             StorageBox(
[rank0]:               ComputedBuffer(name='buf20', layout=FixedLayout('cuda', torch.float16, size=[1, 44, 16, 128], stride=[90112, 2048, 128, 1]), data=Pointwise(
[rank0]:                 'cuda',
[rank0]:                 torch.float16,
[rank0]:                 def inner_fn(index):
[rank0]:                     _, i1, i2, i3 = index
[rank0]:                     tmp0 = ops.load(buf15, i3 + 128 * i1 + 5632 * i2)
[rank0]:                     return tmp0
[rank0]:                 ,
[rank0]:                 ranges=[1, 44, 16, 128],
[rank0]:                 origin_node=clone_4,
[rank0]:                 origins={clone_4}
[rank0]:               ))
[rank0]:             ),
[rank0]:             FixedLayout('cuda', torch.float16, size=[44, 2048], stride=[2048, 1]),
[rank0]:             origins={mm_3}
[rank0]:           ), ReinterpretView(
[rank0]:             StorageBox(
[rank0]:               InputBuffer(name='arg166_1', layout=FixedLayout('cuda', torch.float16, size=[4096, 2048], stride=[2048, 1]))
[rank0]:             ),
[rank0]:             FixedLayout('cuda', torch.float16, size=[2048, 4096], stride=[1, 2048]),
[rank0]:             origins={mm_3}
[rank0]:           )],
[rank0]:           constant_args=(),
[rank0]:           kwargs={},
[rank0]:           output_view=None,
[rank0]:           python_kernel_name=extern_kernels.mm,
[rank0]:           cpp_kernel_name=at::mm_out,
[rank0]:           ordered_kwargs_for_cpp_kernel=(),
[rank0]:           origin_node=mm_3,
[rank0]:           origins={mm_3}
[rank0]:         )
[rank0]:       ),
[rank0]:       FixedLayout('cuda', torch.float16, size=[1, 44, 4096], stride=[180224, 4096, 1]),
[rank0]:       origins={view_17}
[rank0]:     )
[rank0]:   )
[rank0]:   args[1]: sum
[rank0]:   args[2]: default
```

From what I can tell, it's failing the following check in FallbackKernel:

```
if schema.is_mutable and not can_auto_functionalize(kernel):
    raise NotImplementedError(
        f"NYI: Can't generate FallbackKernel for {kernel}"
    )
```

This used to work a few weeks ago, the code calling it looks like this:

```
def _all_reduce_single(input: torch.Tensor, op: str):
    res = torch.ops._c10d_functional.all_reduce(input.contiguous(), op, "default")
    return torch.ops._c10d_functional.wait_tensor(res)
```

### Versions

Collecting environment information...
PyTorch version: 2.3.0.dev20240212
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1041-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3000.000
BogoMIPS:                        6000.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] mypy==1.7.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] torch==2.3.0.dev20240212
[pip3] torchaudio==2.2.0.dev20240212
[pip3] torchvision==0.18.0.dev20240212
[pip3] triton==3.0.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numexpr                   2.8.3           mkl_py311h0b1cd97_1    conda-forge
[conda] numpy                     1.26.2          py311h64a7726_0    conda-forge
[conda] pytorch                   2.3.0.dev20240212 py3.11_cuda12.1_cudnn8.9.2_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.2.0.dev20240212     py311_cu121    pytorch-nightly
[conda] torchtriton               3.0.0+901819d2b6           py311    pytorch-nightly
[conda] torchvision               0.18.0.dev20240212     py311_cu121    pytorch-nightly

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by yifuwang** [comment]
Hey @ani300, thanks for filing the issue. This is a recent regression which I believe is fixed in #119102. Can you give it a try when you get a chance?

**Comment by eellison** [comment]
cc @zou3519

**Comment by ani300** [comment]
@yifuwang I assume this didn't make it to yesterday's nightly, so I'll try with tomorrow's one and if that doesn't work I'll just compile from source. Thanks for the quick response!

**Comment by ani300** [comment]
It works! Thanks
