### ISSUE TITLE
Optional reader/loader for distributed checkpoint optimizer APIs 

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#119800]
### 🚀 The feature, motivation and pitch

`storage_reader` is optional for `torch.distributed.checkpoint.state_dict_loader.load`: https://github.com/pytorch/pytorch/blob/c0e5cca4f8be382bc30c5c5a8199ddc12fed85a3/torch/distributed/checkpoint/state_dict_loader.py#L49

But not for `torch.distributed.checkpoint.optimizer.load_sharded_optimizer_state_dict`: https://github.com/pytorch/pytorch/blob/c0e5cca4f8be382bc30c5c5a8199ddc12fed85a3/torch/distributed/checkpoint/optimizer.py#L209

This argument was made optional in https://github.com/pytorch/pytorch/pull/117772

Creating the reader object is straightforward and has no cost, but this is mildly inconvenient if https://github.com/pytorch/pytorch/issues/118036 lands.

cc @LucasLLC @fegin

**Comment by fegin** [comment]
We are deprecating `load_sharded_optimizer_state_dict`. The API is designed to handle the existing FSDP optimizer. So the API is not general. In PyTorch v.2.2, we have added an experimental API set, distributed_state_dict (torch.distributed.checkpoint.state_dict), which aim to unify all the PyTorch distributed parallelisms state_dict and optimizer state_dict. As a result, we are not going to change the API.

cc., @LucasLLC

**Comment by carmocca** [comment]
Thanks for the reply.

I can close this then.

Is there any resource/docs/rfc/issue/pr that describes the changes and maybe includes basic migration guidelines? Is this experimental API going to be released with 2.3?

We call these future-deprecated apis in PyTorch Lightning (https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/strategies/fsdp.py#L619-L629) so it would be useful to know what and how we need to update our internals. cc @awaelchli

**Comment by fegin** [comment]
Yes, this is still an experimental feature that was introduced in 2.2 and we should have a formal documentation in 2.3 to discuss the new interface and APIs.

But the code should be simple like
```
import torch.distributed.checkpoint.state_dict get_model_state_dict, get_optimizer_state_dict
import torch.distributed.checkpoint as DCP

msd = get_model_state_dict(model)
osd = get_optimizer_state_dict(model, optimizer
DCP.save(PATH, {"model": msd, "optimizer": osd})
sd = DCP.load(PATH)
```

**Comment by carmocca** [comment]
Thank you @fegin.

I tried out this API, but I'm falling into an internal `AssertionError` during loading:

```python
Traceback (most recent call last):
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/home/carlos/lightning/kk.py", line 31, in work
    set_model_state_dict(model, state["model"], options=options)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict.py", line 804, in set_model_state_dict
    return _load_model_state_dict(model, model_state_dict, info)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict.py", line 415, in _load_model_state_dict
    _state_dict_fn(model, "load_state_dict")(
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2194, in load_state_dict
    load(self, state_dict)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2176, in load
    module._load_from_state_dict(
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2033, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 71, in __call__
    return self.hook(module, *args, **kwargs)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 854, in _pre_load_state_dict_hook
    _pre_load_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 632, in _sharded_pre_load_state_dict_hook
    param, shards = _ext_pre_load_state_dict_transform(
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/fsdp/_fsdp_extensions.py", line 164, in _ext_pre_load_state_dict_transform
    assert type(tensor) is ShardedTensor
AssertionError
```

The code is:

```python
import os
import torch.cuda
import torch.nn as nn
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed.fsdp import FullyShardedDataParallel

def work(rank):
    os.environ["MASTER_ADDR"] = "127.0.0.1"
    os.environ["MASTER_PORT"] = "1234"
    dist.init_process_group("nccl", world_size=2, rank=rank)
    torch.cuda.set_device(rank)
    device = torch.device("cuda", rank)

    model = nn.Linear(100, 50).to(device)
    model = FullyShardedDataParallel(model)
    x = torch.rand(2, 100, device=device)
    _ = model(x)

    from torch.distributed.checkpoint.state_dict import get_model_state_dict, set_model_state_dict, StateDictOptions
    from torch.distributed.checkpoint import save, load

    options = StateDictOptions(full_state_dict=False)
    state = {"model": get_model_state_dict(model, options=options)}
    save(state, checkpoint_id="fsdp_model.pt")
    
    state = {"model": model.state_dict()}
    load(state, checkpoint_id="fsdp_model.pt")
    set_model_state_dict(model, state["model"], options=options)

def run():
    mp.spawn(work, nprocs=2)

if __name__ == "__main__":
    run()
```

Let me know if you prefer that I open a separate issue for this report.
