### ISSUE TITLE
FSDP + TP Initialization Error

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#119937]
### 🐛 Describe the bug

I have a custom implementation of TP which uses device mesh to lay out the tensors and then dtensors it. I then pass in the device mesh into FSDP for wrapping. Concretely, I am TPing my FFN and standard FSDPing everything else. 

For small GPU counts where tp world size = world size, eg I have 2 GPUs with 2-way TP, I get an error on initialization:
```
File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/wrap.py", line 63, in _post_order_apply_inner
    _post_order_apply_inner(child_module, child_module_name, module)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/wrap.py", line 63, in _post_order_apply_inner
    _post_order_apply_inner(child_module, child_module_name, module)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/wrap.py", line 64, in _post_order_apply_inner
    optional_module = fn(module)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/wrap.py", line 98, in fn
    return fsdp_fn(module, **kwargs)
  File "/usr/lib/python3/dist-packages/composer/trainer/mosaic_fsdp_utils.py", line 901, in init_fn_t2p3p0
    _init_param_handle_from_module(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_init_utils.py", line 545, in _init_param_handle_from_module
    _check_single_device_module(fully_sharded_module, state._ignored_params, device_id)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_init_utils.py", line 781, in _check_single_device_module
    raise RuntimeError(
RuntimeError: FSDP only supports single device modules but got params on {device(type='cuda', index=0), device(type='meta')}
```

I think this is because in this scenario, FSDP treats the TP as NO_SHARD so it is not flattened (whereas if I had 4 GPUs, it would shard and all-gather the TP weights). In this case, when recursively initializing, the TP weights are initialized. However, it is then not included in `ignored_params` for this check as `_is_fsdp_flattened(param)` is `False`.

Is there any recommended solution to address this?

### Versions

Torch nightly

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by awgu** [comment]
Maybe we just filter `torch.device("meta")` out from the check 🤔  

I can think about it more carefully later.

**Comment by mvpatel2000** [comment]
@awgu would there be any other ramifications to it not properly showing up inside ignored modules? I can try the suggested filter soon...

**Comment by awgu** [comment]
@mvpatel2000 Actually, hmm. The fact that they do not have `_is_fsdp_flattened` returning `True` is unexpected. 

`_set_fsdp_flattened` should be called regardless of `sharding_strategy`:
https://github.com/pytorch/pytorch/blob/daf1050ae5664cde6d28a040b2209c9ed7592c33/torch/distributed/fsdp/_flat_param.py#L433-L434

**Comment by mvpatel2000** [comment]
@awgu I've narrowed it down a bit more based on your comment -- it seems both correctly tag `_is_fsdp_flattened` to `True`. In the case where I encounter an error, `model.parameters()` yields a DTensor (not the underlying local tensor) which does not have this attribute:

```
[Flatcheck] param=DTensor(local_tensor=tensor([[-0.0239,  0.0052, -0.0401,  ...,]],
       device='cuda:1'), device_mesh=DeviceMesh([0, 1, 2, 3, 4, 5, 6, 7], mesh_dim_names=('tensor_parallel',)), placements=(Shard(dim=0),)), _is_fsdp_flattened(param)=False
```

In the working case, I instead see:
```
[Flatcheck] param=Parameter containing:
tensor([-0.0020,  0.0052,  0.0093,  ...,  0.0007, -0.0246,  0.0002],
       device='cuda:1', requires_grad=True), _is_fsdp_flattened(param)=True
```

I'm not really familiar with dtensor and `model.parameters()` interaction -- I can keep investigating if you have any guidance here

**Comment by awgu** [comment]
I think the issue is from here, where we special case `NO_SHARD`:
https://github.com/pytorch/pytorch/blob/e5bfdde7ba32fecb0364783115eda6e21fb3e400/torch/distributed/fsdp/_flat_param.py#L2059-L2062

I wonder, would you be able to avoid wrapping with FSDP on the module that has 1-way FSDP?

**Comment by mvpatel2000** [comment]
@awgu do you have recommendations on what the best way to do this would be? It's a nested module below something that is FSDP wrapped, and I also want things like sharded checkpointing to work, so I'm not sure if that's possible...

Alternatively, could we auto-forward attributes from dtensor onto the local tensor if it does not have that attribute?

Or can we tag the unsharded view in this case?

I will poke around the code more, thanks for the pointer.

**Comment by awgu** [comment]
We could also skip `DTensor`s in the single-device check 😢 

I am not sure how useful the single-device check is really in practice. I would doubt people would have a module on say `cuda:i` and `cuda:j`, which seems to be the main thing we are trying to check against.

**Comment by mvpatel2000** [comment]
I guess the question is does it matter if `get_orig_params` returns something "wrong" elsewhere? As best as I can tell, no, but that seems like a less than ideal solution...

What if in `get_orig_params` it "unwraps" the dtensor and checks on the local shard?

**Comment by awgu** [comment]
> What if in get_orig_params it "unwraps" the dtensor and checks on the local shard?

This seems possibly okay (need to check for sure). This is becoming hacky, but we already did something similar for `sync_module_states`.

**Comment by mvpatel2000** [comment]
Alternatively, what if `_use_unsharded_views` is run before tagging metadata? (still reading code, suggestion might not make sense...)

**Comment by mvpatel2000** [comment]
FYI if I skip the check, I hit:
```
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_init_utils.py", line 596, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_init_utils.py", line 608, in _init_param_handle_from_params
    handle = FlatParamHandle(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 585, in __init__
    self._init_flat_param_and_metadata(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 740, in _init_flat_param_and_metadata
    self.flat_param: FlatParameter = self.flatten_tensors_into_flat_param(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 853, in flatten_tensors_into_flat_param
    flat_param_data = self.flatten_tensors(tensors, aligned_numel)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 845, in flatten_tensors
    return torch.cat(flat_tensors, dim=0)
  File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/api.py", line 289, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
  File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/dispatch.py", line 111, in dispatch
    op_info = self.unwrap_to_op_info(op_call, args, kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/dispatch.py", line 317, in unwrap_to_op_info
    raise RuntimeError(
RuntimeError: aten.cat.default: got mixed torch.Tensor and DTensor, need to convert all torch.Tensor to DTensor before calling distributed operators!
```
from `_named_parameters_with_duplicates` so maybe this just doesn't work if it sets to use the non-shard?

**Comment by awgu** [comment]
@mvpatel2000 Wait, in your stacktrace, I wonder why it did not unwrap the `DTensor` before `torch.cat`. Would it be easier to construct a smaller repro so I can take a look too?

**Comment by mvpatel2000** [comment]
Ok, so if I disable this check:
```
    # We clamp the strategy to `NO_SHARD` for world size of 1 since they are
    # currently functionally equivalent. This may change if/when we integrate
    # FSDP with MoE.
    # if state.world_size == 1:
    #     if sharding_strategy != ShardingStrategy.NO_SHARD:
    #         warnings.warn(
    #             "FSDP is switching to use `NO_SHARD` instead of "
    #             f"{sharding_strategy or ShardingStrategy.FULL_SHARD} since "
    #             "the world size is 1."
    #         )
    #     sharding_strategy = ShardingStrategy.NO_SHARD
```
it seems to work. My understanding is this is not optimal as it stores both the sharded and the unsharded weights (so 2x memory). @awgu is that correct?

I'd love to have this work with NO_SHARD (especially since it works without DTensor), but it seems pretty messy. Let me try to get a minimal repro as suggested

**Comment by awgu** [comment]
@mvpatel2000 Good call. I do think it would use 2x memory since it would save both sharded and unsharded weights.

**Comment by mvpatel2000** [comment]
@awgu working on getting a minimal repro, will take me a bit of time to rip out a lot of our stack.

As a side note, I also see if I remove:
```
        if not self.uses_sharded_strategy:
            # For `NO_SHARD`, use the *unflattened* unsharded views since we
            # have the unsharded parameter
            self._use_unsharded_views(as_params=True)
            return
```
things seem to work. 

Why is this step needed? is it to avoid some kind of unshard call or something?

**Comment by awgu** [comment]
> Why is this step needed? is it to avoid some kind of unshard call or something?

It was mainly to make `NO_SHARD` more similar to DDP. In the 'sharded' state (i.e. outside forward/backward computation), since we have the unsharded data, we can use unsharded views and expose ND tensors instead of 1D tensors.

Whether we do this or not is not _critical_, but I am not sure how much of our stack (mainly checkpointing) assumes this behavior now :(

**Comment by mvpatel2000** [comment]
Minimal repro @awgu. It's not exact same error but I think hitting something similar with same root cause

Traceback:
```
Traceback (most recent call last):
  File "/workdisk/llm-foundry-private/scripts/train/checkpoint.py", line 133, in <module>
    run_fsdp_checkpoint_save_example(dist_cp.get_global_rank(), world_size, mesh_shape)
  File "/workdisk/llm-foundry-private/scripts/train/checkpoint.py", line 103, in run_fsdp_checkpoint_save_example
    model = FSDP(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 503, in __init__
    _init_param_handle_from_module(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_init_utils.py", line 596, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_init_utils.py", line 608, in _init_param_handle_from_params
    handle = FlatParamHandle(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 585, in __init__
    self._init_flat_param_and_metadata(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 740, in _init_flat_param_and_metadata
    self.flat_param: FlatParameter = self.flatten_tensors_into_flat_param(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 853, in flatten_tensors_into_flat_param
    flat_param_data = self.flatten_tensors(tensors, aligned_numel)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 845, in flatten_tensors
    return torch.cat(flat_tensors, dim=0)
  File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/api.py", line 289, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
  File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/dispatch.py", line 111, in dispatch
    op_info = self.unwrap_to_op_info(op_call, args, kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/dispatch.py", line 317, in unwrap_to_op_info
    raise RuntimeError(
RuntimeError: aten.cat.default: got mixed torch.Tensor and DTensor, need to convert all torch.Tensor to DTensor before calling distributed operators!
```

Code:
```
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from typing import Callable
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed._tensor.device_mesh import init_device_mesh
from torch.distributed.fsdp.wrap import CustomPolicy
from torch.distributed._tensor import DeviceMesh, Shard, DTensor, Placement
from torch.distributed.fsdp.api import ShardingStrategy

fs_dim = 8
tp_dim = 4
input_dim = 2

class TPModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.ffn1 = torch.nn.Parameter(torch.empty(
            fs_dim,
            tp_dim,
        ))
    def forward(self, x):
        return self.ffn1(x)
    def fsdp_wrap_fn(self, fsdp_mesh):
        return {'device_mesh': fsdp_mesh}

class FullShardModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = nn.Linear(input_dim, fs_dim, bias=False)
        self.net2 = nn.Linear(fs_dim, fs_dim, bias=False)
        self.ffn = TPModel()
    def forward(self, x):
        return self.ffn(self.net2(self.net1(x)))
    
    
def run_fsdp_checkpoint_save_example(rank, world_size, mesh_shape):
    ## INITIALIZE DIST
    # Running on one node so master_addr is just local host
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "28000"
    # All ranks simulataneously init the process group together.
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)

    ## SETUP MODEL
    mesh_2d = init_device_mesh(
        'cuda', mesh_shape, mesh_dim_names=("dp", "tp")
    )
    tp_mesh = mesh_2d["tp"]
    ffn_fsdp_mesh = mesh_2d["dp"]
    mesh_1d = init_device_mesh('cuda', (world_size,))
    model = FullShardModel().to(rank)
    def dtensorify_param(param: nn.Parameter, mesh: DeviceMesh, placements: list[Placement]):
        """Construct a DTensor from an already sharded local parameter."""
        param_dtensor = DTensor.from_local(
            param.data,
            device_mesh=mesh,
            placements=placements,
            run_check=False,
        )
        return nn.Parameter(param_dtensor)
    dtensorified_params = [
        (
            name,
            dtensorify_param(
                param=parameter,
                mesh=tp_mesh,
                placements=[Shard(0)],
            )
        )
        for name, parameter in model.ffn.named_parameters()
    ]
    for name, dtensorified_param in dtensorified_params:
        model.ffn.register_parameter(name, dtensorified_param)


    ## ADD DTENSOR HOOKS
    def tensor_to_dtensor_hook(mod, args):
        inp, = args
        return DTensor.from_local(inp, tp_mesh, [Shard(0)])
    model.ffn.register_forward_pre_hook(tensor_to_dtensor_hook)
    
    def dtensor_to_tensor_hook(mod, inp, outp):
        return outp.to_local()
    model.ffn.register_forward_hook(dtensor_to_tensor_hook)
    
    ## WRAP MODEL
    def lambda_fn(module: torch.nn.Module):
        ret = False
        if hasattr(module, '_fsdp_wrap'):
            ret = bool(module._fsdp_wrap)
        elif hasattr(module, 'fsdp_wrap_fn') and isinstance(module.fsdp_wrap_fn, Callable):
            ret = module.fsdp_wrap_fn(ffn_fsdp_mesh)
        return ret

    model = FSDP(
        model,
        sharding_strategy=ShardingStrategy.FULL_SHARD,
        device_mesh=mesh_1d,
        use_orig_params=True,
        auto_wrap_policy=CustomPolicy(lambda_fn),
    )
    print(model)

    ## RUN MODEL
    # loss_fn = nn.MSELoss()
    # optim = torch.optim.Adam(model.parameters(), lr=0.1)
    # optim.zero_grad()
    # outp = model(torch.rand(4,input_dim,device="cuda")).sum(dim=1)
    # loss = loss_fn(outp, torch.ones(4, device='cuda'))
    # loss.backward()
    # optim.step()

    dist.destroy_process_group()

if __name__ == "__main__":
    mesh_shape = (1, 2)
    world_size = mesh_shape[0] * mesh_shape[1]
    mp.spawn(
        run_fsdp_checkpoint_save_example,
        args = (world_size, mesh_shape),
        nprocs=world_size,
        join=True
    )
```

**Comment by mvpatel2000** [comment]
@awgu One additional note, in our setup we already have the sharded tensors and we want to create a dtensor from it, so we do:
```
    def dtensorify_param(param: nn.Parameter, mesh: DeviceMesh, placements: list[Placement]):
        """Construct a DTensor from an already sharded local parameter."""
        param_dtensor = DTensor.from_local(
            param.data,
            device_mesh=mesh,
            placements=placements,
            run_check=False,
        )
        return nn.Parameter(param_dtensor)
    dtensorified_params = [
        (
            name,
            dtensorify_param(
                param=parameter,
                mesh=tp_mesh,
                placements=[Shard(0)],
            )
        )
        for name, parameter in model.ffn.named_parameters()
    ]
    for name, dtensorified_param in dtensorified_params:
        model.ffn.register_parameter(name, dtensorified_param)
```

However, if I do:
```
    model.ffn.ffn1.weight = torch.nn.Parameter(distribute_tensor(model.ffn.ffn1, tp_mesh, [Shard(0)]))
```

then I do not get an error (even though it still switches to `NO_SHARD`). 🤔

**Comment by awgu** [comment]
Thanks for the repro! I will try to look at this soon. Debugging some other issues at the moment.

**Comment by mvpatel2000** [comment]
@awgu this solution looks good to me! I can test it out, but it seems like the right idea.

**Comment by mvpatel2000** [comment]
@awgu I've updated the repro to include a forward

Error:
```
Traceback (most recent call last):
  File "/mnt/workdisk/mihirp/llm-foundry-private/scripts/train/bcui_min_repro.py", line 131, in <module>
    run_fsdp_checkpoint_save_example(0, world_size, mesh_shape)
  File "/mnt/workdisk/mihirp/llm-foundry-private/scripts/train/bcui_min_repro.py", line 115, in run_fsdp_checkpoint_save_example
    outp = model(torch.rand(4,input_dim,device="cuda")).sum(dim=1)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 849, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workdisk/mihirp/llm-foundry-private/scripts/train/bcui_min_repro.py", line 36, in forward
    return self.ffn(self.net2(self.net1(x)))
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 835, in forward
    args, kwargs = _pre_forward(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 413, in _pre_forward
    unshard_fn(state, handle)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 448, in _pre_forward_unshard
    _unshard(state, handle, state._unshard_stream, state._pre_unshard_stream)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 321, in _unshard
    ran_pre_unshard = handle.pre_unshard()
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 1252, in pre_unshard
    ret = self._writeback_orig_params()
  File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 2254, in _writeback_orig_params
    self._writeback_tensor(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 2353, in _writeback_tensor
    raise RuntimeError(
RuntimeError: Cannot writeback when the parameter shape changes
Expects torch.Size([32]) but got torch.Size([16, 4])
```


Code:
```
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from typing import Callable
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed._tensor.device_mesh import init_device_mesh
from torch.distributed.fsdp.wrap import CustomPolicy
from torch.distributed._tensor import DeviceMesh, Shard, DTensor, Placement
from torch.distributed.fsdp.api import ShardingStrategy

fs_dim = 8
tp_dim = 4
input_dim = 2

class TPModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.ffn1 = torch.nn.Parameter(torch.empty(
            fs_dim,
            tp_dim,
        ))
    def forward(self, x):
        return self.ffn1(x)
    def fsdp_wrap_fn(self, fsdp_mesh):
        return {'device_mesh': fsdp_mesh}

class FullShardModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = nn.Linear(input_dim, fs_dim, bias=False)
        self.net2 = nn.Linear(fs_dim, fs_dim, bias=False)
        self.ffn = TPModel()
    def forward(self, x):
        return self.ffn(self.net2(self.net1(x)))
    
    
def run_fsdp_checkpoint_save_example(rank, world_size, mesh_shape):
    ## INITIALIZE DIST
    # Running on one node so master_addr is just local host
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "28000"
    # All ranks simulataneously init the process group together.
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)

    ## SETUP MODEL
    mesh_2d = init_device_mesh(
        'cuda', mesh_shape, mesh_dim_names=("dp", "tp")
    )
    tp_mesh = mesh_2d["tp"]
    ffn_fsdp_mesh = mesh_2d["dp"]
    mesh_1d = init_device_mesh('cuda', (world_size,))
    model = FullShardModel().to(rank)
    def dtensorify_param(param: nn.Parameter, mesh: DeviceMesh, placements: list[Placement]):
        """Construct a DTensor from an already sharded local parameter."""
        param_dtensor = DTensor.from_local(
            param.data,
            device_mesh=mesh,
            placements=placements,
            run_check=False,
        )
        return nn.Parameter(param_dtensor)
    dtensorified_params = [
        (
            name,
            dtensorify_param(
                param=parameter,
                mesh=tp_mesh,
                placements=[Shard(0)],
            )
        )
        for name, parameter in model.ffn.named_parameters()
    ]
    for name, dtensorified_param in dtensorified_params:
        model.ffn.register_parameter(name, dtensorified_param)


    ## ADD DTENSOR HOOKS
    def tensor_to_dtensor_hook(mod, args):
        inp, = args
        return DTensor.from_local(inp, tp_mesh, [Shard(0)])
    model.ffn.register_forward_pre_hook(tensor_to_dtensor_hook)
    
    def dtensor_to_tensor_hook(mod, inp, outp):
        return outp.to_local()
    model.ffn.register_forward_hook(dtensor_to_tensor_hook)
    
    ## WRAP MODEL
    def lambda_fn(module: torch.nn.Module):
        ret = False
        if hasattr(module, '_fsdp_wrap'):
            ret = bool(module._fsdp_wrap)
        elif hasattr(module, 'fsdp_wrap_fn') and isinstance(module.fsdp_wrap_fn, Callable):
            ret = module.fsdp_wrap_fn(ffn_fsdp_mesh)
        return ret

    model = FSDP(
        model,
        sharding_strategy=ShardingStrategy.FULL_SHARD,
        device_mesh=mesh_1d,
        use_orig_params=True,
        auto_wrap_policy=CustomPolicy(lambda_fn),
    )
    print(model)

    ## RUN MODEL
    # loss_fn = nn.MSELoss()
    # optim = torch.optim.Adam(model.parameters(), lr=0.1)
    # optim.zero_grad()
    outp = model(torch.rand(4,input_dim,device="cuda")).sum(dim=1)
    # loss = loss_fn(outp, torch.ones(4, device='cuda'))
    # loss.backward()
    # optim.step()

    dist.destroy_process_group()

if __name__ == "__main__":
    mesh_shape = (1, 2)
    world_size = mesh_shape[0] * mesh_shape[1]
    mp.spawn(
        run_fsdp_checkpoint_save_example,
        args = (world_size, mesh_shape),
        nprocs=world_size,
        join=True
    )
```

**Comment by awgu** [comment]
@mvpatel2000 I think that getting `NO_SHARD` to work with `DTensor` extensions is complicated because we always use unsharded views in `NO_SHARD`.

I think there are two options:
- Do not always use unsharded views in `NO_SHARD`
- Do not clamp world size 1 to `NO_SHARD` (https://github.com/pytorch/pytorch/pull/120334)

The former has a much higher blast radius, so I would prefer going with the latter in the short term. The downside is that the memory usage will be higher during forward/backward due to 2 copies of the parameters being in memory. However, I wonder if that is tolerable since 1-way FSDP is not a typical use case.

Otherwise, we will try to address this more fundamentally in the future, but making fixes to existing `NO_SHARD` might be hard.

**Comment by awgu** [comment]
The issue is that unsharded views include wrapping with `DTensor`, but there is logic that assumes operating on sharded views, which are guaranteed to be `torch.Tensor`. Without `DTensor`, this fine since sharded and unsharded views are effectively the same for `NO_SHARD`. However, with `DTensor`, calls to `.shape` or `.data_ptr()` on the `DTensor` give unexpected values and crash downstream.

**Comment by mvpatel2000** [comment]
> The former has a much higher blast radius, so I would prefer going with the latter in the short term. The downside is that the memory usage will be higher during forward/backward due to 2 copies of the parameters being in memory. However, I wonder if that is tolerable since 1-way FSDP is not a typical use case.

@awgu I think solution 2 is reasonable given the complexity of the code here, and it seems difficult to implement the full solution immediately. It would obviously be nice, but the increased memory usage seems like an acceptable short-term tradeoff. 

I don't think it should be too bad if the wrapping is granular enough and it's set to something like FULL_SHARD so each block is "gathered" aka duplicated but then freed immediately after....

In either case, this seems like an edge-case scenario that isn't really used for performant training but rather easier debugging and testing, so short-term performance compromises for a working solution seems like the right decision to me!

Really appreciate your help getting to the bottom of this.

**Comment by mvpatel2000** [comment]
@awgu Unfortunately I'm still seeing issues if I run with `SHARD_GRAD_OP` (`FULL_SHARD` works fine) in the backward pass. I've updated the repro to include this:
```
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from typing import Callable
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed._tensor.device_mesh import init_device_mesh
from torch.distributed.fsdp.wrap import CustomPolicy
from torch.distributed._tensor import DeviceMesh, Shard, DTensor, Placement
from torch.distributed.fsdp.api import ShardingStrategy

fs_dim = 8
tp_dim = 8
input_dim = 2

class TPModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.ffn1 = torch.nn.Parameter(torch.empty(
            fs_dim,
            tp_dim,
        ))
    def forward(self, x):
        return self.ffn1 @ x
    def fsdp_wrap_fn(self, fsdp_mesh):
        return {'device_mesh': fsdp_mesh}

class FullShardModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = nn.Linear(input_dim, fs_dim, bias=False)
        self.net2 = nn.Linear(fs_dim, fs_dim, bias=False)
        self.ffn = TPModel()
    def forward(self, x):
        return self.ffn(self.net2(self.net1(x)))
    
    
def run_fsdp_checkpoint_save_example(rank, world_size, mesh_shape):
    ## INITIALIZE DIST
    # Running on one node so master_addr is just local host
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "28000"
    # All ranks simulataneously init the process group together.
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)

    ## SETUP MODEL
    mesh_2d = init_device_mesh(
        'cuda', mesh_shape, mesh_dim_names=("dp", "tp")
    )
    tp_mesh = mesh_2d["tp"]
    ffn_fsdp_mesh = mesh_2d["dp"]
    mesh_1d = init_device_mesh('cuda', (world_size,))
    model = FullShardModel().to(rank)
    def dtensorify_param(param: nn.Parameter, mesh: DeviceMesh, placements: list[Placement]):
        """Construct a DTensor from an already sharded local parameter."""
        param_dtensor = DTensor.from_local(
            param.data,
            device_mesh=mesh,
            placements=placements,
            run_check=False,
        )
        return nn.Parameter(param_dtensor)
    dtensorified_params = [
        (
            name,
            dtensorify_param(
                param=parameter,
                mesh=tp_mesh,
                placements=[Shard(0)],
            )
        )
        for name, parameter in model.ffn.named_parameters()
    ]
    for name, dtensorified_param in dtensorified_params:
        model.ffn.register_parameter(name, dtensorified_param)


    ## ADD DTENSOR HOOKS
    def tensor_to_dtensor_hook(mod, args):
        inp, = args
        return DTensor.from_local(inp, tp_mesh, [Shard(0)])
    model.ffn.register_forward_pre_hook(tensor_to_dtensor_hook)
    
    def dtensor_to_tensor_hook(mod, inp, outp):
        return outp.to_local()
    model.ffn.register_forward_hook(dtensor_to_tensor_hook)
    
    ## WRAP MODEL
    def lambda_fn(module: torch.nn.Module):
        ret = False
        if hasattr(module, '_fsdp_wrap'):
            ret = bool(module._fsdp_wrap)
        elif hasattr(module, 'fsdp_wrap_fn') and isinstance(module.fsdp_wrap_fn, Callable):
            ret = module.fsdp_wrap_fn(ffn_fsdp_mesh)
        return ret

    model = FSDP(
        model,
        sharding_strategy=ShardingStrategy.SHARD_GRAD_OP,
        device_mesh=mesh_1d,
        use_orig_params=True,
        auto_wrap_policy=CustomPolicy(lambda_fn),
    )
    print(model)

    ## RUN MODEL
    loss_fn = nn.MSELoss()
    optim = torch.optim.Adam(model.parameters(), lr=0.1)
    optim.zero_grad()
    outp = model(torch.rand(4,input_dim,device="cuda")).sum(dim=1)
    loss = loss_fn(outp, torch.ones(8, device='cuda'))
    loss.backward()
    optim.step()

    dist.destroy_process_group()

if __name__ == "__main__":
    mesh_shape = (1, 2)
    world_size = mesh_shape[0] * mesh_shape[1]
    mp.spawn(
        run_fsdp_checkpoint_save_example,
        args = (world_size, mesh_shape),
        nprocs=world_size,
        join=True
    )
```
Error trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/mnt/workdisk/mihirp/llm-foundry-private/scripts/train/shared_min_repro.py", line 117, in run_fsdp_checkpoint_save_example
    loss.backward()
  File "/usr/lib/python3/dist-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/usr/lib/python3/dist-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/usr/lib/python3/dist-packages/torch/autograd/graph.py", line 690, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 693, in _pre_backward_hook
    _unshard(
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 321, in _unshard
    ran_pre_unshard = handle.pre_unshard()
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 1252, in pre_unshard
    ret = self._writeback_orig_params()
  File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 2236, in _writeback_orig_params
    or not _same_storage(param, flat_param_tensor)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_flat_param.py", line 2716, in _same_storage
    return a.untyped_storage().data_ptr() == b.untyped_storage().data_ptr()
RuntimeError: Attempted to access the data pointer on an invalid python storage.
```

**Comment by mvpatel2000** [comment]
@awgu any chance we could potentially land something in time for 2.2.2? Not sure what timeline you have in mind / how hard this is now

**Comment by mvpatel2000** [comment]
@awgu correct, it is blocked. We just require a user requires more GPUs so TP world size != world size.

**Comment by awgu** [comment]
@mihir-db I would not count on this being fixed. The problem seems pretty involved, and we do not have the bandwidth to try to fix it right now :(

**Comment by awgu** [comment]
We are mainly supporting FSDP2 now, so we are marking this as not planned :/
