### ISSUE TITLE
caffe2's installation is still problematic...

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#12007]
> WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
> CRITICAL:root:Cannot load caffe2.python. Error: ~/.local/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so: undefined symbol: mkldnn_primitive_destroy

**Comment by avijit9** [comment]
Any workaround?

**Comment by wfly1998** [comment]
I met similar problem, when import torch, it throws that

> Traceback (most recent call last):
>  File "tmp.py", line 5, in <module>
>    import torch
>  File "/home/me/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
>    from torch._C import *
>ImportError: /home/me/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2.so: undefined symbol: mkldnn_primitive_attr_destroy

Waiting for resolution.

**Comment by wfly1998** [comment]
I solve this problem! Just delete the environment variable!
If there are some environment variable whose name have `MKL`, then delete it.
And if there is `LD_LIBRARY_PATH`, delete it.

I removed such variable: `LD_LIBRARY_PATH`, `MKL_DOMAIN_NUM_THREADS`, `MKL_NUM_THREADS`, and my code can run now.
