### ISSUE TITLE
AOTAutograd does not fully decompose the `torch.cond` subgraphs

### ISSUE THREAD

**Issue by aakhundov** [pytorch/pytorch#120160]
### 🐛 Describe the bug

Seems that the nested `true_fn` and `false_fn` subgraphs of `torch.cond` are not fully decomposed under the hood of the following `aot_autograd` call in Inductor:

https://github.com/pytorch/pytorch/blob/2fea4752150d4e3c1d8c5ff3e5920a458dc1b499/torch/_inductor/compile_fx.py#L1329-L1339

As a result, we see ops like `torch.ops.aten.ones_like` reaching the Inductor lowering stage, whereas they should be decomposed into more primitive ops (in this case, `torch.ops.aten.full`) *before* Inductor lowering.

### Example

When running the following code that `torch.compile`s the model with `torch.cond`:

```python
class Module(torch.nn.Module):
    def forward(self, pred, a):
        def true_fn(x):
            return torch.zeros_like(x)

        def false_fn(x):
            return torch.ones_like(x)

        b = torch.ones_like(a)
        c = torch.cond(pred, true_fn, false_fn, [b])
        return c

torch.compile(Module())(
    torch.tensor(True),
    torch.rand(10, 20),
)
```

We get the following error:

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: both a fallback and a decomp for same op: aten.zeros_like.default
```

<details>
<summary>Full error with the stack trace:</summary>

```
Traceback (most recent call last):
  File "/data/users/aakhundov/pytorch/torch/testing/_internal/common_utils.py", line 2744, in wrapper
    method(*args, **kwargs)
  File "/data/users/aakhundov/pytorch/test/inductor/test_control_flow.py", line 326, in test_decomp
    torch.compile(Module())(
  File "/data/users/aakhundov/pytorch/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 912, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 777, in _convert_frame
    result = inner_convert(
             ^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 398, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/home/aakhundov/.conda/envs/pytorch/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 669, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 542, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/convert_frame.py", line 507, in transform
    tracer.run()
  File "/data/users/aakhundov/pytorch/torch/_dynamo/symbolic_convert.py", line 2130, in run
    super().run()
  File "/data/users/aakhundov/pytorch/torch/_dynamo/symbolic_convert.py", line 793, in run
    and self.step()
        ^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/symbolic_convert.py", line 756, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/aakhundov/pytorch/torch/_dynamo/symbolic_convert.py", line 2249, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/data/users/aakhundov/pytorch/torch/_dynamo/output_graph.py", line 931, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/aakhundov/.conda/envs/pytorch/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/output_graph.py", line 1102, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/output_graph.py", line 1175, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/aakhundov/pytorch/torch/_dynamo/output_graph.py", line 1156, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/__init__.py", line 1730, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aakhundov/.conda/envs/pytorch/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/compile_fx.py", line 1332, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/backends/common.py", line 57, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_functorch/aot_autograd.py", line 879, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_functorch/aot_autograd.py", line 604, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/compile_fx.py", line 1260, in fw_compiler_base
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/aakhundov/.conda/envs/pytorch/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/aakhundov/.conda/envs/pytorch/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/compile_fx.py", line 430, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/compile_fx.py", line 683, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 607, in run
    return super().run(*args)
           ^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 946, in run_node
    result = super().run_node(n)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 808, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 805, in call_function
    out = lowerings[target](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/lowering.py", line 294, in wrapped
    out = decomp_fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/lowering.py", line 5416, in cond
    result = ir.Conditional.create(pred, true_fn, false_fn, operands)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/ir.py", line 6761, in create
    subgraph.graph.run(*fake_operands)
  File "/data/users/aakhundov/pytorch/torch/_dynamo/utils.py", line 251, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 607, in run
    return super().run(*args)
           ^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 946, in run_node
    result = super().run_node(n)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/aakhundov/pytorch/torch/_inductor/graph.py", line 793, in call_function
    make_fallback(target, layout_constraint)
  File "/data/users/aakhundov/pytorch/torch/_inductor/lowering.py", line 1710, in make_fallback
    assert op not in decompositions, f"both a fallback and a decomp for same op: {op}"
           ^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: both a fallback and a decomp for same op: aten.zeros_like.default
  target: cond
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg1_1', layout=FixedLayout('cpu', torch.bool, size=[], stride=[]))
  ))
  args[1]: Subgraph(name='true_graph_0', graph_module=<lambda>(), graph=<torch._inductor.graph.GraphLowering object at 0x7f7fc7a0a2d0>)
  args[2]: Subgraph(name='false_graph_0', graph_module=<lambda>(), graph=None)
  args[3]: [TensorBox(StorageBox(
    ComputedBuffer(name='buf0', layout=FlexibleLayout('cpu', torch.float32, size=[10, 20], stride=[20, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          i0, i1 = index
          tmp0 = ops.constant(1, torch.float32)
          return tmp0
      ,
      ranges=[10, 20],
      origin_node=full_default,
      origins={full_default}
    ))
  ))]
```
</details>

### Analysis

If we take a look at the functionalized fx graph of the model right before inductor lowering (after `post_grad_passes`):

```python
def forward(self, arg0_1: "f32[10, 20]", arg1_1: "b8[]"):
    # File: /data/users/aakhundov/pytorch/torch/_higher_order_ops/cond.py:108 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
    true_graph_0 = self.true_graph_0
    false_graph_0 = self.false_graph_0
    
    # File: /data/users/aakhundov/pytorch/test/inductor/test_control_flow.py:322 in forward, code: b = torch.ones_like(a)
    full_default: "f32[10, 20]" = torch.ops.aten.full.default([10, 20], 1, dtype = torch.float32, layout = torch.strided, device = device(type='cpu'), pin_memory = False)
    
    # File: /data/users/aakhundov/pytorch/torch/_higher_order_ops/cond.py:108 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
    conditional = torch.ops.higher_order.cond(arg1_1, true_graph_0, false_graph_0, [full_default]);  arg1_1 = true_graph_0 = false_graph_0 = full_default = None
    getitem: "f32[10, 20]" = conditional[0];  conditional = None
    return (getitem,)
    
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: "f32[10, 20]"):
        # File: /data/users/aakhundov/pytorch/torch/_higher_order_ops/cond.py:108 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
        zeros_like: "f32[10, 20]" = torch.ops.aten.zeros_like.default(arg0_1, pin_memory = False);  arg0_1 = None
        return (zeros_like,)
        
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: "f32[10, 20]"):
        # File: /data/users/aakhundov/pytorch/torch/_higher_order_ops/cond.py:108 in cond, code: return cond_op(pred, true_fn, false_fn, operands)
        ones_like: "f32[10, 20]" = torch.ops.aten.ones_like.default(arg0_1, pin_memory = False);  arg0_1 = None
        return (ones_like,)
```

we can see that the `torch.ones_like` is the parent graph is decomposed down to `torch.ops.aten.full`, but the one in the `false_fn` subgraph stays `torch.ops.aten.ones_like`. This causes the error reported above here during Inductor lowering:

https://github.com/pytorch/pytorch/blob/2fea4752150d4e3c1d8c5ff3e5920a458dc1b499/torch/_inductor/lowering.py#L1710

as there is, indeed, a decomposition for `torch.ops.aten.ones_like`. Conclusion: AOTAutograd does not completely decompose the subgraphs before Inductor lowering.

### Versions

<details>
<summary>Versions:</summary>

```
PyTorch version: 2.3.0a0+git8818392
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: 17.0.6 (CentOS 17.0.6-4.el9)
CMake version: version 3.22.1
Libc version: glibc-2.34

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.12.0-0_fbk16_zion_7661_geb00762ce6d2-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA PG509-210
GPU 1: NVIDIA PG509-210
GPU 2: NVIDIA PG509-210
GPU 3: NVIDIA PG509-210
GPU 4: NVIDIA PG509-210
GPU 5: NVIDIA PG509-210
GPU 6: NVIDIA PG509-210
GPU 7: NVIDIA PG509-210

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn.so.8.9.2
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.2
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.2
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.2
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.2
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.2
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       4
Stepping:                        11
Frequency boost:                 enabled
CPU max MHz:                     1801.0000
CPU min MHz:                     800.0000
BogoMIPS:                        3600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        96 MiB (96 instances)
L3 cache:                        132 MiB (4 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-23,96-119
NUMA node1 CPU(s):               24-47,120-143
NUMA node2 CPU(s):               48-71,144-167
NUMA node3 CPU(s):               72-95,168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.2.3
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] onnx==1.14.0
[pip3] open-clip-torch==2.20.0
[pip3] optree==0.10.0
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.3
[pip3] torch==2.3.0a0+git88f3808
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torch-struct==0.5
[pip3] torchaudio==2.1.0a0+406e9c8
[pip3] torchdata==0.7.0a0+901b483
[pip3] torchdata==0.7.0a0+901b483
[pip3] torchmetrics==0.11.4
[pip3] torchrec-nightly==2023.6.14
[pip3] torchtext==0.16.0a0+60bea66
[pip3] torchvision==0.16.0a0+8324c48
[pip3] triton==2.2.0
[pip3] vector-quantize-pytorch==1.6.14
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.2.3                    pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-include               2023.1.0         h06a4308_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.3                    pypi_0    pypi
[conda] torch                     2.3.0a0+git88f3808           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.1.0a0+406e9c8           dev_0    <develop>
[conda] torchdata                 0.7.0a0+901b483          pypi_0    pypi
[conda] torchfix                  0.2.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchrec-nightly          2023.6.14                pypi_0    pypi
[conda] torchtext                 0.16.0a0+60bea66           dev_0    <develop>
[conda] torchvision               0.16.0a0+8324c48           dev_0    <develop>
[conda] triton                    2.2.0                    pypi_0    pypi
[conda] vector-quantize-pytorch   1.6.14                   pypi_0    pypi
```
</details>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames

**Comment by aakhundov** [comment]
@ydwu4 assigning to you, as we've discussed this offline. Thanks!
