### ISSUE TITLE
Cannot `torch.save` or pickle complex32 Tensor

### ISSUE THREAD

**Issue by Gwihwan-Go** [pytorch/pytorch#120290]
### 🐛 Describe the bug

I'm encountering issues when attempting to pickle a complex32 tensor. Saving the tensor using pickle fails

```python 

import torch, pickle

tensor = torch.rand([1,2,3],dtype=torch.float32).to(torch.complex32)
with open('test.pkl', 'wb') as f : pickle.dump(tensor, f)
```

error_logs :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/std/lib/python3.8/site-packages/torch/storage.py", line 951, in __reduce__
    torch.save(self, b, _use_new_zipfile_serialization=False)
  File "/opt/conda/envs/std/lib/python3.8/site-packages/torch/serialization.py", line 632, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/opt/conda/envs/std/lib/python3.8/site-packages/torch/serialization.py", line 769, in _legacy_save
    pickler.dump(obj)
  File "/opt/conda/envs/std/lib/python3.8/site-packages/torch/serialization.py", line 674, in persistent_id
    storage_type_str = obj._pickle_storage_type()
  File "/opt/conda/envs/std/lib/python3.8/site-packages/torch/storage.py", line 947, in _pickle_storage_type
    raise KeyError(f'dtype {self.dtype} is not recognized') from e
KeyError: 'dtype torch.complex32 is not recognized'
```

### Versions

2.3.0.dev20240220+cu118

cc @ezyang @gchanan @zou3519 @kadeng @mruberry @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Seems to be a real issue, 

```python
import torch
tensor = torch.rand([1,2,3],dtype=torch.float32).to(torch.complex32)
torch.save(tensor)
```

fails for me as well

Since [`dtype_to_storage_map`](https://github.com/pytorch/pytorch/blob/main/torch/storage.py?fbclid=IwAR2Sn44cDVWD345iUL-x7HzzBiMxleI6js-gRZfeSb9h3ky9CUwmjIa-k-I#L390-L414) says we should no longer add to the list, I think the correct fix is to handle this in `v3_dtypes` and `torch._utils._rebuild_tensor_v3` over here

https://github.com/pytorch/pytorch/blob/cfddfce0d378e335d2243563b2d84f923cbc790c/torch/_tensor.py#L397-L410

Marking actionable to send a fix

**Comment by mikaylagawarecki** [comment]
marking triage review to discuss whether this is high priority

**Comment by albanD** [comment]
Done!
