### ISSUE TITLE
Profiler with stack does not work for CPU when loading model

### ISSUE THREAD

**Issue by kleinicke** [pytorch/pytorch#120235]
### 🐛 Describe the bug

Running the profiler on the CPU with `with_stack` activated does not allow to call torch.load. 
```python
    import torch    
    from torch.profiler import profile, ProfilerActivity

    with profile(
        activities=[ProfilerActivity.CPU],
        with_stack=True,
    ):

        chckpt = torch.load(model_path)
```

The error message is
```
  File "main.py", line 10, in main
    with profile(
  File "/home/.../python3.12/site-packages/torch/profiler/profiler.py", line 624, in __exit__
    self.stop()
  File "/home/.../python3.12/site-packages/torch/profiler/profiler.py", line 638, in stop
    self._transit_action(self.current_action, None)
  File "/home/.../python3.12/site-packages/torch/profiler/profiler.py", line 666, in _transit_action
    action()
  File "/home/.../python3.12/site-packages/torch/profiler/profiler.py", line 163, in stop_trace
    self.profiler.__exit__(None, None, None)
  File "/home/.../python3.12/site-packages/torch/autograd/profiler.py", line 296, in __exit__
    self.kineto_results = _disable_profiler()
                          ^^^^^^^^^^^^^^^^^^^
RuntimeError: !stack.empty() INTERNAL ASSERT FAILED at "../torch/csrc/autograd/profiler_python.cpp":969, please report a bug to PyTorch. Python replay stack is empty.
```

Using ProfilerActivity.CUDA instead causes no error.
Activating all attributes except for `with_stack` also causes no error.

### Versions

Collecting environment information...
PyTorch version: 2.2.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 10.5.0-1ubuntu1~22.04) 10.5.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.12.1 | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000

Nvidia driver version: 515.105.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnxruntime==1.17.0
[pip3] torch==2.2.0+cu118
[pip3] torch-tb-profiler==0.4.3
[pip3] torchvision==0.17.0
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.0+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchvision               0.17.0                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by ApsarasX** [comment]
+1, same problem

**Comment by Tradunsky** [comment]
+1, The same problem.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask_pydantic/core.py", line 249, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/wsgi.py", line 66, in invocations
    with torch.inference_mode(), profile(activities=[ProfilerActivity.CPU], profile_memory=True, record_shapes=True, with_stack=True) as prof:
  File "/usr/local/lib/python3.11/dist-packages/torch/profiler/profiler.py", line 624, in __exit__
    self.stop()
  File "/usr/local/lib/python3.11/dist-packages/torch/profiler/profiler.py", line 638, in stop
    self._transit_action(self.current_action, None)
  File "/usr/local/lib/python3.11/dist-packages/torch/profiler/profiler.py", line 666, in _transit_action
    action()
  File "/usr/local/lib/python3.11/dist-packages/torch/profiler/profiler.py", line 163, in stop_trace
    self.profiler.__exit__(None, None, None)
  File "/usr/local/lib/python3.11/dist-packages/torch/autograd/profiler.py", line 296, in __exit__
    self.kineto_results = _disable_profiler()
                          ^^^^^^^^^^^^^^^^^^^
RuntimeError: !stack.empty() INTERNAL ASSERT FAILED at "../torch/csrc/autograd/profiler_python.cpp":969, please report a bug to PyTorch. Python replay stack is empty.

```


OS: ubuntu 22.04
Python: 3.11
numpy = "1.26.4"
torch = "2.2.1"
torchvision = "0.17.1"

**Comment by xqiangx1991** [comment]
+1

**Comment by ommmid** [comment]
+1

**Comment by MateiDumitrescu1** [comment]
+1

**Comment by kleinicke** [comment]
It was properly fixed by #143940
