### ISSUE TITLE
Dynamo (`openxla`) fails when returning bigger input view.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#120336]
### 🐛 Describe the bug

PyTorch XLA issue: https://github.com/pytorch/xla/issues/5837

In the following code, `foo` is a function that tries to expand the input tensor `x` [3] into a [2, 3] tensor. 

```python
import torch
import torch_xla.core.xla_model as xm

@torch.compile(backend="openxla")
def foo(x):
    return x.expand(2, *x.shape)

x = torch.arange(3, device=xm.xla_device())
print(foo(x))
```

```python
Traceback (most recent call last):
  File "examples/dyn-view.py", line 15, in <module>
    print(foo(x))
  File "torch/_tensor.py", line 983, in __format__
    return object.__format__(self, format_spec)
  File "torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 677, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 432, in _str_intern
    self = self.to("cpu")
RuntimeError: Error while lowering: [] aten::as_strided, xla_shape=s64[2,3]{1,0}, dynamic_dims: (), size=(2, 3), stride=(3, 1), storage_offset=0
Error: torch_xla/csrc/ops/as_strided.cpp:26 : Check failed: storage_offset + slice_size <= input_element_count (6 vs. 3)
```

PyTorch/XLA raises an error in the lowering phase, i.e. past the point where we call the bad `as_strided`. Modifying PyTorch/XLA code, I am able to pin-point exactly where the offending call is at:

<details>
<summary>PyTorch/XLA Diff</summary>

```
diff --git a/torch_xla/csrc/aten_xla_type.cpp b/torch_xla/csrc/aten_xla_type.cpp
index 3a2518233..177769050 100644
--- a/torch_xla/csrc/aten_xla_type.cpp
+++ b/torch_xla/csrc/aten_xla_type.cpp
@@ -702,6 +702,11 @@ at::Tensor XLANativeFunctions::as_strided_copy(
   XLATensorPtr self_tensor = bridge::GetXlaTensor(tensor);
   auto xsize = XlaHelpers::I64List(size);
   auto xstride = XlaHelpers::I64List(stride);
+
+  int64_t input_element_count = xla::ShapeUtil::ElementsIn(self_tensor->shape());
+  int64_t slice_size = torch_xla::runtime::util::Multiply<int64_t>(size);
+  XLA_CHECK_LE(storage_offset.value_or(0) + slice_size, input_element_count);
+
   if (!AsStrided::StrideIsSupported(self_tensor->shape(), xsize, xstride,
                                     storage_offset.value_or(0))) {
     return at::native::call_fallback_fn<
```

</details>

```python
Traceback (most recent call last):
  File "examples/dyn-view.py", line 14, in <module>
    out = foo(x)
  File "torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "examples/dyn-view.py", line 10, in foo
    @torch.compile(backend="openxla")
  File "torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 893, in forward
    return compiled_fn(full_args)
  File "torch/_functorch/_aot_autograd/utils.py", line 79, in g
    return f(*args)
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 230, in runtime_wrapper
    regenerated_out = gen_alias_from_base(
  File "torch/_functorch/_aot_autograd/functional_utils.py", line 240, in gen_alias_from_base
    aliased_out = aliased_base_tensor.as_strided(size, stride, storage_offset)
RuntimeError: torch_xla/csrc/aten_xla_type.cpp:708 : Check failed: storage_offset.value_or(0) + slice_size <= input_element_count (6 vs. 3)
```

### Versions

PyTorch version: 2.3.0a0+git73c01e3
Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] (64-bit runtime)

Versions of relevant libraries:
[pip3] torch-xla==2.2.0+git19362a9

cc @bdhirsh @miladm @JackCaoG @lezcano @ezyang

**Comment by ysiraichi** [comment]
The problem is due to the interaction of 2 factors:

1. AOTAutograd functionalization step marks the output as "alias_of_input"
2. After executing the function output by the forward compiler (`openxla`), we have an output whose strides correspond to a non-overlapped tensor

Because of (1), AOTAutograd tries to re-stride the aliased input with the output (2) strides, which causes the error.

**Comment by ysiraichi** [comment]
One way I can think of in order to fix this issue is by doing something similar to what `FunctionalTensorWrapper` does: instead of calling `as_strided`, AOTAutograd should re-apply all the view operations applied to the output, until it gets the  actual output. Specifically:

1. Save the `ViewMeta` sequence of the AOTAutograd functionalization output
2. Apply the `ViewMeta` sequence, using the concrete input as base tensor (something like `FunctionalTensorWrapper::regenerate_from_base`)

What do you think?

**Comment by lezcano** [comment]
The proposed solution sounds reasonable to me. @bdhirsh wdyt?

**Comment by ezyang** [comment]
sgtm

cc @jbschlosser
