### ISSUE TITLE
No grad generated when using amp and no_grad at same time when training process 

### ISSUE THREAD

**Issue by xin-w8023** [pytorch/pytorch#120483]
## Code
```python3
import torch


model = torch.nn.Linear(10, 20).cuda()
x = torch.randn(1, 10).cuda()

with torch.autocast(device_type="cuda"):
    with torch.no_grad():
        _ = model(x)
    
    out = model(x)
    loss = out.mean()
    loss.backward()
```

## Error
Traceback (most recent call last):
  File "/opt/tiger/samantha/x2.py", line 13, in <module>
    loss.backward()
  File "/usr/local/lib/python3.9/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### Versions

Collecting environment information...
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB

Nvidia driver version: 470.161.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         3000.000
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] byted-torch==2.1.0+u9
[pip3] flake8==4.0.1
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] onnx==1.13.1
[pip3] onnxruntime==1.7.0
[pip3] pytorch-lightning==2.0.0
[pip3] rotary-embedding-torch==0.5.3
[pip3] soft-moe-pytorch==0.1.5
[pip3] tf2onnx==1.9.3
[pip3] torch==2.1.0
[pip3] torch-complex==0.4.3
[pip3] torch-stft==0.1.4
[pip3] torchaudio==2.1.0+cu121
[pip3] torchaudio-augmentations==0.2.1
[pip3] torchlibrosa==0.1.0
[pip3] torchmetrics==1.3.0.post0
[pip3] torchvision==0.16.0+cu121
[pip3] triton==2.1.0
[pip3] vector_quantize_pytorch==1.12.16
[conda] Could not collect

**Comment by xin-w8023** [comment]
And it only affects `Linear` layer, I tried add `LayerNorm` before and post, they have grad generated but the grad of the layer before linear may not right.
```python3
import torch


model = torch.nn.ModuleList(
    [torch.nn.LayerNorm(10), torch.nn.Linear(10, 20), torch.nn.LayerNorm(20)]
).cuda()
x = torch.randn(1, 10).cuda()

with torch.autocast(device_type="cuda", enabled=True):
    with torch.no_grad():
        o = x
        for layer in model:
            o = layer(o)
    out = x
    for layer in model:
        out = layer(out)
    loss = out.mean()
    loss.backward()
    for layer in model:
        print(f"{layer=}, {layer.weight.grad=}")
```

## OUTPUT
layer=LayerNorm((10,), eps=1e-05, elementwise_affine=True), layer.weight.grad=tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
layer=Linear(in_features=10, out_features=20, bias=True), layer.weight.grad=None
layer=LayerNorm((20,), eps=1e-05, elementwise_affine=True), layer.weight.grad=tensor([ 0.0238,  0.0126,  0.0203, -0.0194,  0.1023,  0.0092,  0.0418, -0.0552,
         0.0195, -0.1057, -0.0881,  0.0290, -0.0904,  0.0060,  0.0034,  0.0022,
        -0.0055, -0.0031,  0.0466,  0.0506], device='cuda:0')

**Comment by albanD** [comment]
Closing as duplicate from https://github.com/pytorch/pytorch/issues/112583
There are more details and suggested PR there if you want to help fix this!
