### ISSUE TITLE
[Multiprocess Training & Datapipe] the message is sent "bind: Address already in use" after executing several epochs. 

### ISSUE THREAD

**Issue by sifengyang** [pytorch/pytorch#120401]
### 🐛 Describe the bug

There is a failure case：
```
import torch
import torch.distributed as dist
from torch.utils.data import DataLoader
import torch.utils.data.datapipes as dp

if __name__ == "__main__":
    batch_size = 4
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    rank = int(os.environ.get("RANK", 0))
    dist.init_process_group(backend='nccl', init_method='env://', world_size=world_size, rank=rank)
 
    idp = dp.iter.IterableWrapper(range(300)).map(lambda x: x + 1).shuffle()
    dataloader = DataLoader(idp, num_workers=2, shuffle=True, batch_size=4)
 
    for ite in range(200):
        for itd in dataloader:
            print(f"rank {rank}, epoch {ite}, {itd.shape}")
```

Run command,

```
python -m torch.distributed.run --nproc_per_node 16 --master_port 2326 test.py
```

Error Info,
```
rank 13, epoch 160, torch.Size([4])
rank 13, epoch 160, torch.Size([4])
rank 13, epoch 160, torch.Size([4])
rank 13, epoch 160, torch.Size([4])
rank 13, epoch 160, torch.Size([4])
Traceback (most recent call last):
  File "/workspace/dataloader.py", line 29, in <module>
    for itd in dataloader:
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 995, in __init__
    super(_MultiProcessingDataLoaderIter, self).__init__(loader)
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 567, in __init__
    self._pg = dist.new_group(backend="gloo")
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3335, in new_group
    pg = _new_process_group_helper(
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 862, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [/torch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:176] bind: Address already in use
```

My questions:
   1. The above code may be wrong. DataLoader does not have `world_size` and `rank` and cannot divide the data. If the above code is wrong, please tell me how to correct it.
   2. If the usage of DataPipe is correct, please tell me the reason for the error.
   3. why does _BaseDataLoaderIter need to [new process group](https://github.com/pytorch/pytorch/blob/faad8ecb26e710e883c3ae3d418ef7919f86ec37/torch/utils/data/dataloader.py#L571) for each batch  of DataLoader.
   
 

### Versions

I test the demo by torch1.13.1 and torch2.1.

**Comment by sifengyang** [comment]
Change codes:
```
import torch
import torch.distributed as dist
from torch.utils.data import DataLoader
import torch.utils.data.datapipes as dp

if __name__ == "__main__":
    batch_size = 4
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    rank = int(os.environ.get("RANK", 0))
    dist.init_process_group(backend='nccl', init_method='env://', world_size=world_size, rank=rank)
 
    idp = dp.iter.IterableWrapper(range(300)).map(lambda x: x + 1).shuffle()
    # look at the change
    dataloader = DataLoader(idp, num_workers=2, shuffle=True, batch_size=4, persistent_workers=True)
 
    for ite in range(200):
        for itd in dataloader:
            print(f"rank {rank}, epoch {ite}, {itd.shape}")
```
`DataLoader` get `persistent_workers=True`, The error message does not appear.

Description of parameter `persistent_workers`:
```
persistent_workers (bool, optional): If ``True``, the data loader will not shut down
            the worker processes after a dataset has been consumed once. This allows to
            maintain the workers `Dataset` instances alive. (default: ``False``)
```

add my question:
    4.   the data loader **will shut down** the worker processes after a dataset has been consumed once. What is the purpose of this design?

**Comment by XilunWu** [comment]
Not the designer of DDP but I think it's mainly to be compatible with legacy code because this feature was not added until PyTorch 1.8 (source: https://github.com/pytorch/pytorch/issues/15849). I do think we can discuss if we want to make `persistent=True` the default option.

cc @fegin @wanchaol @rohan-varma @wconstab

**Comment by wconstab** [comment]
@kwen2501 can you add some comments?

**Comment by XilunWu** [comment]
back to @sifengyang 's original question, when `persistent_workers=False`, each iteration will do the following:
0) initialize new workers
1) bind socket to the hardcoded default port because `init_method='env://'`
2) do the rendezvous process to coordinate workers
3) real data loading job

Step 1) introduces the issue. One way to tackle it is to keep incrementing the port number until an available one is found.

**Comment by kwen2501** [comment]
`bind: Address already in use` usually comes from that the same IP port is being used again and again. That might be linked to your observation that some code in DataLoader is creating ProcessGroups in each iter.

**Comment by d4l3k** [comment]
**Category: Stale**

This issue has been automatically closed. Please reopen if this is still an active issue.
