### ISSUE TITLE
Functionalization of `as_strided` disregards its base tensor storage.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#120585]
### 🐛 Describe the bug

In the program below, I try to **retrieve the original tensor** by calling `as_strided`, after creating a view with **different `storage_offset`**. In theory, it should work, given that `y` is a view of `x`.

```python
import torch
import torch._lazy.ts_backend

torch._lazy.ts_backend.init()

def foo(x):
    y = x[2:]
    return y.as_strided((10,), (1,), 0)

x = torch.arange(10)
print(foo(x))
# tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Lx = x.to("lazy")
print(foo(Lx))
# See error below.
```

```python
Traceback (most recent call last):
  File "examples/bug.py", line 14, in <module>
    print(foo(Lx))
  File "torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 677, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 432, in _str_intern
    self = self.to("cpu")
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: setStorage: sizes [10], strides [1], storage offset 0, and itemsize 8 requiring a storage size of 80 are out of bounds for storage of size 64
```

From the error above, we can clearly see that `as_strided` is only considering the storage of the input tensor. Since the lazy backend uses `FunctionalTensorWrapper`, the view aspects are controlled by it. The real tensor (wrapped one) is unaware of such a thing.

### Versions

PyTorch version: 2.3.0a0+gited6660e

**Comment by ysiraichi** [comment]
Given all this information, I thought that the functionalization kernel of `as_strided` should redispatch, passing the base tensor as first argument (check out this [draft PR](https://github.com/pytorch/pytorch/pull/120435)). However, that brings a new problem: we have no notion of the input tensor (the view) `storage_offset`.

That is because the input tensor (a view from `FunctionalTensorWrapper` perspective) is not actually a view from the backend perspective.

**Comment by ysiraichi** [comment]
One solution I can think of is to possibly re-dispatch `as_strided` twice: 

1. Using the view as first argument
2. If that fails, use the base tensor as first argument

This solution would work with the example in the OP. However, there's still a problem with this solution is if the function `foo` was the following:

```python
def foo(x):
    y = x[2:8]
    return y.as_strided((8,), (1,))
```

- (1) would fail because it doesn't have enough storage space (6 elements instead of 8)
- (2) would not fail, but return an incorrect result since the `storage_offset` of both the view and the base tensor is 0

That said, this solution would be an improvement over what we have now.
Let me know what you think.

**Comment by ezyang** [comment]
The ability for `as_strided` to look into the underlying storage and then make a disjoint view on it is kind of cursed and so I expect a solution to this to be kind of cursed too.

I think @bdhirsh really needs to chime in here, but I think the way I would go about doing this properly is ensuring that functionalization is keeping track of accurate "what the storage would have looked like in eager mode" (which I'm not sure we do right now, to some extent we try to preserve the striding of the functionalized tensors, maybe this works); then, when we call `as_strided`, we actually perform the operation on the storage "tensor" (which we have been faithfully keeping track of and has all the information we need.)

I don't like the hacky solution you proposed because it will generate silently incorrect results. In general, that's worse than just failing.

**Comment by ysiraichi** [comment]
> is keeping track of accurate "what the storage would have looked like in eager mode"

I thought we weren't, but after I took another look at it, I think we are doing that. That's probably what `set_sizes_strides_offset` in the functionalization backend does.

Given that, the question is: why isn't the storage offset preserved. I think the answer lies in the backend (TS and PyTorch/XLA). I will take another look at it.

**Comment by bdhirsh** [comment]
(belated reply) - talked to @ysiraichi offline. He pointed out that FunctionalTensorWrapper is already maintaining faithful eager info about sizes/strides during functionalization already, but it's failing to plumb that info to the inner tensor which is what we really want. He's going to try a PR and we can see if there's any CI fallout

**Comment by ysiraichi** [comment]
Said PR: #135237
