### ISSUE TITLE
`Tensor.new_tensor` fails with `jvp` (problem with duals?)

### ISSUE THREAD

**Issue by lkct** [pytorch/pytorch#120554]
### 🐛 Describe the bug

When using `Tensor.new_tensor` inside a function wrapped by `torch.func.jvp`, the tensor creation fails with wrong device. However, other `new_*` methods (zeros/ones/full/empty) can work as expected.

**To reproduce**
```python
import torch
from torch.func import jvp

def func(x):
    y = x.new_tensor(0.5)      # This fails
    # y = x.new_full((), 0.5)  # This works
    return x + y

x = torch.rand(10, 10)
tangents = torch.zeros_like(x)

jvp(func, (x,), (tangents,))
```

**Error log**
```log
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    jvp(func, (x,), (tangents,))
  File "/home/lkct/miniconda3/envs/torch38/lib/python3.8/site-packages/torch/_functorch/eager_transforms.py", line 927, in jvp
    return _jvp_with_argnums(func, primals, tangents, argnums=None, strict=strict, has_aux=has_aux)
  File "/home/lkct/miniconda3/envs/torch38/lib/python3.8/site-packages/torch/_functorch/vmap.py", line 44, in fn
    return f(*args, **kwargs)
  File "/home/lkct/miniconda3/envs/torch38/lib/python3.8/site-packages/torch/_functorch/eager_transforms.py", line 976, in _jvp_with_argnums
    result_duals = func(*duals)
  File "a.py", line 5, in func
    y = x.new_tensor(0.5)      # This fails
RuntimeError: DispatchKey FuncTorchGradWrapper doesn't correspond to a device
```

**Known workaround**
`y = torch.tensor(0.5).to(x)` works.

### Versions

I can reproduce on both 2.2.1 and nightly 20240222.

**Comment by guilhermeleobas** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/133018
