### ISSUE TITLE
`set_model_state_dict` fails with `AssertionError`

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#120609]
### 🐛 Describe the bug

I'm trying the new DCP APIs after this comment: https://github.com/pytorch/pytorch/issues/119800#issuecomment-1945241436

But failing into a `ShardedTensor` assertion

```python
import os
import torch.cuda
import torch.nn as nn
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed.fsdp import FullyShardedDataParallel

def work(rank):
    os.environ["MASTER_ADDR"] = "127.0.0.1"
    os.environ["MASTER_PORT"] = "1234"
    dist.init_process_group("nccl", world_size=2, rank=rank)
    torch.cuda.set_device(rank)
    device = torch.device("cuda", rank)

    model = nn.Linear(100, 50).to(device)
    model = FullyShardedDataParallel(model)
    x = torch.rand(2, 100, device=device)
    _ = model(x)

    from torch.distributed.checkpoint.state_dict import get_model_state_dict, set_model_state_dict, StateDictOptions
    from torch.distributed.checkpoint import save, load

    options = StateDictOptions(full_state_dict=False)
    state = {"model": get_model_state_dict(model, options=options)}
    save(state, checkpoint_id="fsdp_model.pt")
    
    state = {"model": model.state_dict()}
    load(state, checkpoint_id="fsdp_model.pt")
    set_model_state_dict(model, state["model"], options=options)

def run():
    mp.spawn(work, nprocs=2)

if __name__ == "__main__":
    run()
```

Error:

```python
Traceback (most recent call last):
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/home/carlos/lightning/kk.py", line 31, in work
    set_model_state_dict(model, state["model"], options=options)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict.py", line 804, in set_model_state_dict
    return _load_model_state_dict(model, model_state_dict, info)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict.py", line 415, in _load_model_state_dict
    _state_dict_fn(model, "load_state_dict")(
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2194, in load_state_dict
    load(self, state_dict)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2176, in load
    module._load_from_state_dict(
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2033, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 71, in __call__
    return self.hook(module, *args, **kwargs)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 854, in _pre_load_state_dict_hook
    _pre_load_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 632, in _sharded_pre_load_state_dict_hook
    param, shards = _ext_pre_load_state_dict_transform(
  File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/fsdp/_fsdp_extensions.py", line 164, in _ext_pre_load_state_dict_transform
    assert type(tensor) is ShardedTensor
AssertionError
```

### Versions

Current nightly

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by fegin** [comment]
```
state = {"model": model.state_dict()}
```
indicates that you ask DCP to load a full_state_dict but for `set_model_state_dict` you set the full_state_dict to False. You should use the same way, `get_state_dict` to get the state to load.

**Comment by carmocca** [comment]
I see. Thank you for the reply. Would you recommend that `get_model_state_dict` is always used regardless of full/sharded instead of `model.state_dict()`? Is there any drawback to loading a `full_state_dict` with it?

**Comment by wz337** [comment]
> I see. Thank you for the reply. Would you recommend that `get_model_state_dict` is always used regardless of full/sharded instead of `model.state_dict()`? Is there any drawback to loading a `full_state_dict` with it?

@carmocca The benefit of using get_model_state_dict is that you don't have to change the API if you change the parallelism solution. I am guessing you are sticking using FSDP to train at the time, so with that the benefit is instead of using FSDP specific APIs, `get_model_state_dict` is a more generic APIs. You don't have to use context manager or `set_state_dict_type` to toggle between full and sharded state_dict. Instead, you can just specify in the `StateDictOption` in `get_model_state_dict`.
