### ISSUE TITLE
[pytorch/ppc64le] c10d test_gloo_backend test fails / also outputs undefined symbol ...

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#12062]
torch version:  torch (1.0.0a0+dfa03e9)
RH 7.5 / CUDA 9.2  cuDNN 7.3

======================================================================
FAIL: test_gloo_backend (__main__.DistributedDataParallelTest)

Traceback (most recent call last):
  File "test_c10d.py", line 300, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 347, in _join_processes
    self._check_return_codes(elapsed_time)
  File "test_c10d.py", line 364, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/common.py", line 397, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 127 not less than or equal to 1e-05 :

I also get the following output when running the test:

test_gloo_backend (__main__.DistributedDataParallelTest) ... 
python: symbol lookup error: /home/freddie/miniconda/lib/python3.6/site-packages/torch/_C.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: _ZN4gloo24CudaAllreduceRingChunkedIdNS_17CudaHostWorkspaceIdEEEC1ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaISA_EEiRKS9_IP11CUstream_stSaISG_EE
python: symbol lookup error: /home/freddie/miniconda/lib/python3.6/site-packages/torch/_C.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: _ZN4gloo24CudaAllreduceRingChunkedIdNS_17CudaHostWorkspaceIdEEEC1ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaISA_EEiRKS9_IP11CUstream_stSaISG_EE
FAIL

**Comment by avmgithub** [comment]
Closing this for now.  It looks like it was a bad environment causing this.
