### ISSUE TITLE
[export] `nn.GRU` fails to `torch.export` due to unimplemented operator

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#120626]
### 🐛 Describe the bug

The following model, containing a single `nn.GRU` layer cannot be exported:
 
**Model:**
```python
import torch
from torch.export import export

class Sample(torch.nn.Module):
   def __init__(self, size, h_dim, **kwargs):
       super(Sample, self).__init__(**kwargs)
       self.rnn = torch.nn.GRU(size, h_dim, batch_first=True)
 
   def forward(self, x):
       _, states = self.rnn(x)
       return states

mod = Sample(size=19, h_dim=40)
mod.eval()
mod.cuda()
exported = export(mod, (torch.rand((1, 40, 19)).cuda(),))
```

**Error Log:**
```bash
  File "/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1713, in run_fallback_kernel
    return pytree.tree_map(map_out, r)
  File "/python3.10/site-packages/torch/utils/_pytree.py", line 898, in tree_map
    return treespec.unflatten(map(func, *flat_args))
  File "/python3.10/site-packages/torch/utils/_pytree.py", line 734, in unflatten
    leaves = list(leaves)
  File "/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1703, in map_out
    raise orig_not_implemented_exception
  File "/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1436, in _dispatch_impl
    r = func(*args, **kwargs)
  File "/python3.10/site-packages/torch/_ops.py", line 571, in __call__
    return self_._op(*args, **kwargs)
NotImplementedError: aten::_cudnn_rnn_flatten_weight: attempted to run this operator with Meta tensors, but there was no abstract impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add an abstract impl.Please see the following doc for next steps: https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit
```

### Versions

```
torch == 2.3.0.dev20240222+cu121
```

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by angelayi** [comment]
I just tried this locally, and it seems to work for me?
The exported program looks like this: https://gist.github.com/angelayi/c12aa58399b564006a1862c635753a99

**Comment by gs-olive** [comment]
Thanks for testing that out. I tried it again with both today's nightly (`2.3.0.dev20240308+cu121`) and the stable version, and seeing the `NotImplementedError` for both. Could you share the `torch` version, `nvidia-cudnn-cu12` version, and `torch.backends.cudnn.version()` - in case I have one of those incorrect?

**Comment by angelayi** [comment]
Oh looks like I don't have cudnn 😅

**Comment by vadimkantorov** [comment]
Related:
- https://github.com/pytorch/pytorch/issues/91439

**Comment by gs-olive** [comment]
Hello - as an update on this issue, on the older PyTorch nightly (`torch==2.3.0.dev20240222+cu121`), the error no longer appears when using the fix in #123138, and inference appears to be functional - thanks for the fix @angelayi!

Though, when I tried again with a more recent nightly (`torch==2.4.0.dev20240403+cu121`), the error is now:
<details>

<summary>
<b>Traceback</b>
</summary>

```python
Traceback (most recent call last):
  File "test_script.py", line 32, in <module>
    exported = export(mod, (torch.rand((1, 40, 19)).cuda(),))
  File "/usr/local/lib/python3.10/dist-packages/torch/export/__init__.py", line 174, in export
    return _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/export/_trace.py", line 705, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/export/_trace.py", line 688, in wrapper
    ep = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/export/exported_program.py", line 84, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/export/_trace.py", line 938, in _export
    gm_torch_level = _export_to_torch_ir(
  File "/usr/local/lib/python3.10/dist-packages/torch/export/_trace.py", line 373, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 1238, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "test_script.py", line 25, in forward
    def forward(self, x):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 1204, in result_capturing_wrapper
    graph_captured_result = torch.func.functional_call(
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/functional_call.py", line 143, in functional_call
    return nn.utils.stateless._functional_call(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/stateless.py", line 263, in _functional_call
    return module(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/_lazy_graph_module.py", line 123, in _lazy_forward
    return self(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.0", line 6, in forward
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 1086, in forward
    self._update_flat_weights()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 305, in _update_flat_weights
    self._init_flat_weights()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 158, in _init_flat_weights
    self.flatten_parameters()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 196, in flatten_parameters
    unique_data_ptrs = {p.data_ptr() for p in self._flat_weights}
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 196, in <setcomp>
    unique_data_ptrs = {p.data_ptr() for p in self._flat_weights}
RuntimeError: Cannot access data pointer of Tensor (e.g. FakeTensor, FunctionalTensor). If you're using torch.compile/export/fx, it is likely that we are erroneously tracing into a custom kernel. To fix this, please wrap the custom kernel into an opaque custom op. Please see the following for details: https://docs.google.com/document/d/1W--T6wz8IY8fOI0Vm8BF44PdBgs283QvpelJZWieQWQ
```

</details>

**Comment by vient** [comment]
Getting
```
...
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: SetComp aren't supported:
  File "/usr/twix/python3.11/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 195
        # alias would break the assumptions of the uniqueness check in
        # Module.named_parameters().
        unique_data_ptrs = {p.data_ptr() for p in self._flat_weights}
                           ~ <--- HERE
        if len(unique_data_ptrs) != len(self._flat_weights):
            return
```
using torch 2.3.1 from pypi (latest version at the moment)
The same problem, right?
Got this while trying to convert torch model to openvino using `torch.jit.script` following this guide https://docs.openvino.ai/2023.3/notebooks/102-pytorch-to-openvino-with-output.html#scripted-model

**Comment by justinchuby** [comment]
With torch 2.9:

```py
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, p_rnn_weight_ih_l0: "f32[120, 19]", p_rnn_weight_hh_l0: "f32[120, 40]", p_rnn_bias_ih_l0: "f32[120]", p_rnn_bias_hh_l0: "f32[120]", x: "f32[1, 40, 19]"):
             # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/rnn.py:1380 in forward, code: hx = torch.zeros(
            zeros: "f32[1, 1, 40]" = torch.ops.aten.zeros.default([1, 1, 40], dtype = torch.float32, device = device(type='cpu'), pin_memory = False)
            
             # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/rnn.py:1394 in forward, code: result = _VF.gru(
            gru = torch.ops.aten.gru.input(x, zeros, [p_rnn_weight_ih_l0, p_rnn_weight_hh_l0, p_rnn_bias_ih_l0, p_rnn_bias_hh_l0], True, 1, 0.0, False, False, True);  x = zeros = p_rnn_weight_ih_l0 = p_rnn_weight_hh_l0 = p_rnn_bias_ih_l0 = p_rnn_bias_hh_l0 = None
            getitem: "f32[1, 40, 40]" = gru[0];  getitem = None
            getitem_1: "f32[1, 1, 40]" = gru[1];  gru = None
            return (getitem_1,)
            
Graph signature: 
    # inputs
    p_rnn_weight_ih_l0: PARAMETER target='rnn.weight_ih_l0'
    p_rnn_weight_hh_l0: PARAMETER target='rnn.weight_hh_l0'
    p_rnn_bias_ih_l0: PARAMETER target='rnn.bias_ih_l0'
    p_rnn_bias_hh_l0: PARAMETER target='rnn.bias_hh_l0'
    x: USER_INPUT
    
    # outputs
    getitem_1: USER_OUTPUT
    
Range constraints: {}
```
