### ISSUE TITLE
Subclasses with `__torch_function__()` impls for composite ops don't work with dynamic shapes

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#120654]
Example trivial subclass implementing `__torch_function__()`. Note the composite op call of `unflatten()` in the compiled function.

In the torch_function impl: `with torch._C.DisableTorchFunctionSubclass()` for redispatch breaks `Proxy`.

```python
import torch
import torch.utils._pytree as pytree

class SubTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, t):
        return torch.Tensor._make_wrapper_subclass(
            cls, t.shape, t.stride(), t.storage_offset(), torch.contiguous_format, t.dtype,
            torch.strided, t.device, False, t.requires_grad, "sizes", False, False, None
        )

    def __init__(self, t):
        super().__init__()
        self._t = t

    def __tensor_flatten__(self):
        return ["_t"], {}

    @staticmethod
    def __tensor_unflatten__(inner_tensors, ctx, outer_size, outer_stride):
        t = inner_tensors["_t"]
        return SubTensor(t)

    def __repr__(self):
        return f"SubTensor({self._t})"

    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}

        with torch._C.DisableTorchFunctionSubclass():
            return func(*args, **kwargs)

    @classmethod
    def __torch_dispatch__(cls, func, types, args=(), kwargs=None):
        kwargs = {} if kwargs is None else kwargs
        new_args = pytree.tree_map_only(SubTensor, lambda s: s._t, args)
        output = func(*new_args, **kwargs)
        output = pytree.tree_map_only(torch.Tensor, lambda t: SubTensor(t), output)
        return output


@torch.compile(dynamic=True)
def f(x):
    return x.unflatten(-1, [2, 5])

s = SubTensor(torch.randn(3, 10))
output = f(s)
print(output)
```
```
Traceback (most recent call last):
  File "/home/jbschlosser/misc/repro.py", line 50, in <module>
    output = f(s)
             ^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 912, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 777, in _convert_frame
    result = inner_convert(
             ^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 398, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/home/jbschlosser/anaconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 669, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 542, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/convert_frame.py", line 507, in transform
    tracer.run()
  File "/home/jbschlosser/pytorch/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/home/jbschlosser/pytorch/torch/_dynamo/symbolic_convert.py", line 791, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in step
    getattr(self, inst.opname)(inst)
  File "/home/jbschlosser/pytorch/torch/_dynamo/symbolic_convert.py", line 2247, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/jbschlosser/pytorch/torch/_dynamo/output_graph.py", line 931, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/jbschlosser/anaconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/output_graph.py", line 1102, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/output_graph.py", line 1175, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/jbschlosser/pytorch/torch/_dynamo/output_graph.py", line 1156, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/__init__.py", line 1730, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/anaconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_inductor/compile_fx.py", line 1332, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/backends/common.py", line 57, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/aot_autograd.py", line 879, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/aot_autograd.py", line 604, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 72, in aot_dispatch_base
    fw_module, updated_flat_args, maybe_subclass_meta = aot_dispatch_base_graph(  # type: ignore[misc]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 90, in aot_dispatch_base_graph
    fw_module = _create_graph(
                ^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 40, in _create_graph
    fx_g = make_fx(
           ^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 1099, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 550, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/_symbolic_trace.py", line 793, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 577, in wrapped
    out = f(*tensors)
          ^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 540, in fw_fn
    return inner_fn(flat_fn_maybe_joint, primals, use_trace_joint=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 519, in inner_fn
    wrapped_outs = fn(*all_args)
                   ^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 357, in _functionalized_f_helper
    f_outs = fn(*f_args)
             ^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 68, in inner_fn
    outs = fn(*args)
           ^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 618, in functional_call
    out = PropagateUnbackedSymInts(mod).run(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 593, in run_node
    result = super().run_node(n)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/interpreter.py", line 296, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_tensor.py", line 1287, in unflatten
    return handle_torch_function(Tensor.unflatten, (self,), self, dim, sizes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/overrides.py", line 1636, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/misc/repro.py", line 34, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_tensor.py", line 1299, in unflatten
    return super().unflatten(dim, sizes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/misc/repro.py", line 40, in __torch_dispatch__
    output = func(*new_args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_ops.py", line 571, in __call__
    return self_._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_subclasses/functional_tensor.py", line 380, in __torch_dispatch__
    outs_unwrapped = func._op_dk(
                     ^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 656, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 691, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 364, in proxy_call
    proxy_args, proxy_kwargs = pytree.tree_map_only(
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/utils/_pytree.py", line 1037, in tree_map_only
    return tree_map(map_only(__type_or_types)(func), tree, is_leaf=is_leaf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/utils/_pytree.py", line 897, in tree_map
    return treespec.unflatten(map(func, *flat_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/utils/_pytree.py", line 735, in unflatten
    leaves = list(leaves)
             ^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/utils/_pytree.py", line 993, in wrapped
    return func(x)
           ^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 294, in inner
    return get_proxy_slot(e, tracer)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/fx/experimental/proxy_tensor.py", line 193, in <lambda>
    try_set_proxy_slot(s, lambda x, i: set_meta(torch.ops.aten.sym_size.int(proxy, i), x), i)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbschlosser/pytorch/torch/_ops.py", line 571, in __call__
    return self_._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: aten::sym_size() Expected a value of type 'Tensor' for argument 'self' but instead found type 'Proxy'.
Position: 0
Value: Proxy(arg0_1)
Declaration: aten::sym_size.int(Tensor self, int dim) -> SymInt
Cast error details: Unable to cast Proxy(arg0_1) to Tensor

While executing %unflatten : [num_users=1] = call_method[target=unflatten](args = (%l_x_, -1, [2, 5]), kwargs = {})
Original traceback:
  File "/home/jbschlosser/misc/repro.py", line 47, in f
    return x.unflatten(-1, [2, 5])


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

cc @hameerabbasi @rgommers @peterbell10 @ezyang @msaroufim @albanD @bdhirsh @anijain2305 @zou3519

**Comment by jbschlosser** [comment]
cc @mlazos any insight here?

**Comment by jbschlosser** [comment]
Related: #120124

**Comment by bdhirsh** [comment]
Hmm I think https://github.com/pytorch/pytorch/issues/120124#issuecomment-1965095721 will also fix this issue.

Today, we're probably **re-running** the torch_function code in this example while aot autograd is tracing, which will blindly disable torch_function and prevent torch.proxy from working.

**Comment by soulitzer** [comment]
To avoid https://github.com/pytorch/pytorch/issues/120654#issuecomment-1965346649, one "solution" is to split the subclass into two parts, one that handles torch dispatch, and one that handles the torch function.  

There seem to be some gaps that make this way difficult though: the only way I've gotten this to work so far is to have a non-subclass torch function class that implements torch function and wraps the inner tensor (make wrapper subclass only allows torch dispatch subclass today). This means we're required to implement all the methods (maybe there should exist an automated way, exactly for this usecase).

```python
import torch
import torch.utils._pytree as pytree

class SubTensorTF:
    def __init__(self, t):
        super().__init__()
        self._t = t

    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}

        new_args = pytree.tree_map_only(SubTensorTF, lambda s: s._t, args)
        output = func(*new_args, **kwargs)
        output = pytree.tree_map_only(torch.Tensor, lambda t: SubTensorTF(t), output)
        return output

class SubTensorTD(torch.Tensor):
    @staticmethod
    def __new__(cls, t):
        return torch.Tensor._make_wrapper_subclass(
            cls, t.shape, t.stride(), t.storage_offset(), torch.contiguous_format, t.dtype,
            torch.strided, t.device, False, t.requires_grad, "sizes", False, False, None
        )

    def __init__(self, t):
        super().__init__()
        self._t = t

    def __tensor_flatten__(self):
        return ["_t"], {}

    @staticmethod
    def __tensor_unflatten__(inner_tensors, ctx, outer_size, outer_stride):
        t = inner_tensors["_t"]
        return SubTensorTD(t)

    def __repr__(self):
        return f"SubTensor({self._t})"

    @classmethod
    def __torch_dispatch__(cls, func, types, args=(), kwargs=None):
        kwargs = {} if kwargs is None else kwargs
        new_args = pytree.tree_map_only(SubTensorTD, lambda s: s._t, args)
        output = func(*new_args, **kwargs)
        output = pytree.tree_map_only(torch.Tensor, lambda t: SubTensorTD(t), output)
        return output

@torch.compile(dynamic=True)
def f(x):
    return torch.unflatten(x, -1, [2, 5])

s = SubTensorTF(SubTensorTD(torch.randn(3, 10)))
output = f(s)
print(output)
```

**Comment by mlazos** [comment]
Sorry was on PTO last week. So I've been grappling with this in a few places, I feel like the long term solution is that once dynamo is done tracing the torch function bits in the graph, I think it should be safe to ignore it from then on. Not sure this is safe if there are other places that  the non-default/default `__torch_function__` is called elsewhere in the stack.
