### ISSUE TITLE
Latest Docker image build breaks PyTorch

### ISSUE THREAD

**Issue by SynchronicitydotAI** [pytorch/pytorch#12074]
After a pull today from the PyTorch repo, I generated a Docker build with:

$ docker build -t pytorch -f docker/pytorch/Dockerfile .

...

$ docker run -it --runtime=nvidia ...
root@802db82c54ad:/workspace# python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/torch/__init__.py", line 16, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'torch.version'
>>>

**Comment by SynchronicitydotAI** [comment]
Don't attempt to run PyTorch from a directory where another directory named pytorch exists.
