### ISSUE TITLE
Inductor triton_heuristics 'TypeError: %d format: a real number is required, not NoneType' Logging error

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#120770]
### 🐛 Describe the bug

Noticed this in a prod job:

```
[rank6]:V0227 20:20:57.082000 140088063297088 torch/_inductor/triton_heuristics.py:854] Save heuristic tuning result to /tmp/torchinductor_nobody/vu/cvurr4ua5kw5icag3uwzj3ak3cqnrmbhiikoleubekcu5phrxkmd.best_config #threadId="140088063297088" #callSite="torch/_inductor/triton_heuristics.py:854"
  File "/packages/training_platform/worker-inplace#link-tree/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/codecache.py", line 825, in __call__
    return self.get_current_callable()(inputs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/compile_fx.py", line 772, in run
    return model(new_inputs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/codecache.py", line 853, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_nobody/yk/cykbck7pwkmogpeuin5s2y7djkb5syz6up3qg2umzzihptdpb7jl.py", line 29096, in call
    triton_red_fused_sum_450.run(buf1393, buf1761, 6144, 128, grid=grid(6144), stream=stream7)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/triton_heuristics.py", line 621, in run
    self.autotune_to_one_config(*args, grid=grid, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/triton_heuristics.py", line 519, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/triton_heuristics.py", line 506, in benchmark_all_configs
    log.debug(
Message: '%s: %f, nreg %d, nspill %d, #shared-mem %d'
Arguments: (<triton.runtime.autotuner.Config object at 0x7fc4b9ff3e50>, 0.011776000261306763, 27, 0, None)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/fbcode/platform010/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/fbcode/platform010/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_logging/_internal.py", line 730, in format
    record.message = record.getMessage()
  File "/usr/local/fbcode/platform010/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "/packages/training_platform/worker-inplace#link-tree/torch/autograd/function.py", line 301, in apply
    return user_fn(self, *args)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 813, in backward
    out = call_compiled_backward()
  File "/packages/training_platform/worker-inplace#link-tree/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 762, in call_compiled_backward
    out = call_func_at_runtime_with_args(
  File "/packages/training_platform/worker-inplace#link-tree/torch/_functorch/_aot_autograd/utils.py", line 103, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/packages/training_platform/worker-inplace#link-tree/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/codecache.py", line 825, in __call__
    return self.get_current_callable()(inputs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/compile_fx.py", line 772, in run
    return model(new_inputs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/codecache.py", line 853, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_nobody/yk/cykbck7pwkmogpeuin5s2y7djkb5syz6up3qg2umzzihptdpb7jl.py", line 29096, in call
    triton_red_fused_sum_450.run(buf1393, buf1761, 6144, 128, grid=grid(6144), stream=stream7)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/triton_heuristics.py", line 621, in run
    self.autotune_to_one_config(*args, grid=grid, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/triton_heuristics.py", line 519, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/packages/training_platform/worker-inplace#link-tree/torch/_inductor/triton_heuristics.py", line 506, in benchmark_all_configs
    log.debug(
Message: '%s: %f, nreg %d, nspill %d, #shared-mem %d'
Arguments: (<triton.runtime.autotuner.Config object at 0x7fc4b9ff2e90>, 0.011296000331640244, 32, 0, None)
[rank7]:V0227 20:20:57.082000 140459712185920 torch/_inductor/triton_heuristics.py:854] Save heuristic tuning result to /tmp/torchinductor_nobody/z4/cz4whu5xebame7yt3gpnkhhi3qh5iuqxwo7tci3rzm2ezf5mw2ht.best_config #threadId="140459712185920" #callSite="torch/_inductor/triton_heuristics.py:854"
[rank4]:V0227 20:20:57.141000 140501349041728 torch/_inductor/triton_heuristics.py:504] Benchmark all input configs for triton_poi_fused_cat_452, get: #threadId="140501349041728" #callSite="torch/_inductor/triton_heuristics.py:504"
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @shunting314 as last blame for this log line

### Versions

main

**Comment by shunting314** [comment]
The root cause is triton moved the field for shared memory from one object to another. Our code handling BC uses something like 'getattr(old_object, attr, None)' and returns None.

Yang chen has a PR recently fixing it: https://github.com/pytorch/pytorch/pull/120666

**Comment by chenyang78** [comment]
> The root cause is triton moved the field for shared memory from one object to another. Our code handling BC uses something like 'getattr(old_object, attr, None)' and returns None.
> 
> Yang chen has a PR recently fixing it: #120666

Thanks, Shunting. Yeah, I think #120666 fixed the issue here.
