### ISSUE TITLE
[Inductor] RBLOCK not defined

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#120857]
Repro:
```
from typing import List

import torch


E4M3_MAX_POS = torch.finfo(torch.float8_e4m3fn).max
E5M2_MAX_POS = torch.finfo(torch.float8_e5m2).max
EPS = 1e-12

SIZES = [torch.Size([1152, 768]), torch.Size([384, 768])]


def to_fp8_saturated(x, float8_dtype: torch.dtype):
    if float8_dtype == torch.float8_e4m3fn:
        x = x.clamp(min=-1 * E4M3_MAX_POS, max=E4M3_MAX_POS)
    else:
        x = x.clamp(min=-1 * E5M2_MAX_POS, max=E5M2_MAX_POS)
    return x.to(float8_dtype)


def inner_fn(weights: List[torch.Tensor]):
    # All-reduce partial amaxes computed from sharded weights
    abs_weights = torch._foreach_abs(weights)
    partial_amax_tensor = abs_weights[0].new_empty(len(abs_weights))
    for i, abs_weight in enumerate(abs_weights):
        torch.max(abs_weight, out=partial_amax_tensor[i])
    # NOTE: The error reproduces without this all-reduce, so let us use a
    # single-GPU repro.
    # replicated_amax_tensor = torch.distributed._functional_collectives.all_reduce(
    #     partial_amax_tensor, "MAX", list(range(torch.distributed.get_world_size()))
    # )
    replicated_amax_tensor = partial_amax_tensor

    # Compute scales from replicated amaxes and the fp8 bit datas
    clamped_tensor = torch.clamp(replicated_amax_tensor, EPS)
    scales_tensor = E4M3_MAX_POS / clamped_tensor
    datas = []
    scales = []
    for i, weight in enumerate(weights):
        scale = scales_tensor[i]
        weight_scaled = weight * scale
        datas.append(to_fp8_saturated(weight_scaled, torch.float8_e4m3fn))
        scales.append(scale)
    return datas, scales


weights = [torch.randn(size, device="cuda") for size in SIZES]
torch.compile(inner_fn)(weights)
```

```
CompilationError: at 10:29:def triton_(in_ptr0, out_ptr1):
    xpid = tl.program_id(0)
    XBLOCK: tl.constexpr = 1024
    if xpid >= 0 and xpid < 1:
        xpid_offset = xpid - 0
        xnumel = 108
        xoffset = xpid_offset * XBLOCK
        xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
        xmask = xindex < xnumel
        rbase = tl.arange(0, RBLOCK)[None, :]

NameError('RBLOCK is not defined')
```

<details>
<summary> Full stack trace </summary>

```
Traceback (most recent call last):
  File "/data/users/andgu/float8_experimental/repro_inductor_error.py", line 74, in <module>
    torch.compile(inner_fn)(weights)
  File "/data/users/andgu/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 909, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 774, in _convert_frame
    result = inner_convert(
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 399, in _convert_frame_assert
    return _compile(
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 665, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/andgu/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 537, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/andgu/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 164, in _fn
    return fn(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_dynamo/convert_frame.py", line 502, in transform
    tracer.run()
  File "/data/users/andgu/pytorch/torch/_dynamo/symbolic_convert.py", line 2174, in run
    super().run()
  File "/data/users/andgu/pytorch/torch/_dynamo/symbolic_convert.py", line 831, in run
    and self.step()
  File "/data/users/andgu/pytorch/torch/_dynamo/symbolic_convert.py", line 794, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/andgu/pytorch/torch/_dynamo/symbolic_convert.py", line 2293, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/data/users/andgu/pytorch/torch/_dynamo/output_graph.py", line 957, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/andgu/pytorch/torch/_dynamo/output_graph.py", line 1102, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/andgu/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_dynamo/output_graph.py", line 1175, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/andgu/pytorch/torch/_dynamo/output_graph.py", line 1156, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/andgu/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/andgu/pytorch/torch/__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/andgu/pytorch/torch/_inductor/compile_fx.py", line 1333, in compile_fx
    return aot_autograd(
  File "/data/users/andgu/pytorch/torch/_dynamo/backends/common.py", line 57, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/data/users/andgu/pytorch/torch/_functorch/aot_autograd.py", line 878, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/data/users/andgu/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_functorch/aot_autograd.py", line 603, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/andgu/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/andgu/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/andgu/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 101, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/data/users/andgu/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_inductor/compile_fx.py", line 1260, in fw_compiler_base
    return inner_compile(
  File "/data/users/andgu/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/data/users/andgu/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/andgu/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_inductor/compile_fx.py", line 430, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/data/users/andgu/pytorch/torch/_inductor/compile_fx.py", line 698, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/data/users/andgu/pytorch/torch/_inductor/graph.py", line 1279, in compile_to_fn
    return self.compile_to_module().call
  File "/data/users/andgu/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/_inductor/graph.py", line 1231, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/data/users/andgu/pytorch/torch/_inductor/codecache.py", line 2103, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_andgu/fj/cfjt3dz3mu2u5apyg5xstqhvbovmasuzlzs67avpdswfwaitplsj.py", line 319, in <module>
    async_compile.wait(globals())
  File "/data/users/andgu/pytorch/torch/_inductor/codecache.py", line 2658, in wait
    scope[key] = result.result()
  File "/data/users/andgu/pytorch/torch/_inductor/codecache.py", line 2465, in result
    self.future.result()
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/andgu/.conda/envs/pytorch-3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CompilationError: at 10:29:def triton_(in_ptr0, out_ptr1):
    xpid = tl.program_id(0)
    XBLOCK: tl.constexpr = 1024
    if xpid >= 0 and xpid < 1:
        xpid_offset = xpid - 0
        xnumel = 108
        xoffset = xpid_offset * XBLOCK
        xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
        xmask = xindex < xnumel
        rbase = tl.arange(0, RBLOCK)[None, :]

NameError('RBLOCK is not defined')
```

</details>

On commit 9c597ff137ead9f7f7ec8fdcbf473de2d328e61b (`viable/strict` as of 2/28 morning)

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by desertfire** [comment]
cc @shunting314

**Comment by shunting314** [comment]
Here is a simpler repro
```
import torch
from torch._inductor import config

torch.set_default_device("cuda")

config.benchmark_kernel = True

@torch.compile
def f(a, b):
    a, b = torch._foreach_abs([a, b]) # fail
    # a, b = a.abs(), b.abs() # works
    return a.max(), b.max()

N = 64
f(torch.randn(N, N), torch.randn(N, N))
print("bye")
```

The issue is caused by running a foreach kernel followed by reduction. I'm not sure that's already supported.

@awgu  you could avoid using the foreach kernel by calling abs on each tensor separately to workaround.

cc @mlazos for the foreach kernel issue.

**Comment by mlazos** [comment]
This shouldn't error though,  we just shouldn't fuse into the foreach op. I can  take a look at this.
