### ISSUE TITLE
distributed: prefixstore doesn't recognize custom store

### ISSUE THREAD

**Issue by jglaser** [pytorch/pytorch#120843]
### 🐛 Describe the bug

I am using a custom python based store to address the issue of torch's `TCPStore` running out of file handle resources when running on a large number of GPUs. However, torch by default wraps the store into a `PrefixStore` which seems to disable the python API.

I am getting the following error
```
L ASSERT FAILED at "/gpfs/alpine2/bif143/proj-shared/summit_py310/conda-bld/pytorch-base_1708839867265/work/torch/csrc/distributed/c10d/init.cpp":151, please report a bug to PyTorch. Not implemented.
Exception raised from get at /gpfs/alpine2/bif143/proj-shared/summit_py310/conda-bld/pytorch-base_1708839867265/work/torch/csrc/distributed/c10d/init.cpp:151 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xfc (0x200072d39d3c in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x124 (0x200072cd1d04 in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, char const*) + 0x70 (0x200072d363e0 in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0xe74814 (0x2000429a4814 in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #4: c10d::PrefixStore::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6c (0x20004993f4bc in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::PrefixStore::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6c (0x20004993f4bc in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) + 0x234 (0x20004df5e7e4 in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #7: c10d::ProcessGroupNCCL::getNCCLComm(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d::OpType, int, bool) + 0x294 (0x20004df64a44 in /gpfs/alpine2/proj-shared/bif143/summit_py310/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
```

implying that the torch can't resolve the virtual overload of the `Store->get()` function, even though it is implemented in the custom store.

My store:
```
from mpi4py import MPI
import torch.distributed as dist

class MPIStore(dist.Store):
    def __init__(self, comm=None):
        super().__init__()
        self.comm = comm
        if self.comm is None:
            self.comm = MPI.COMM_WORLD

    # Function to get value associated with a key
    def get(self, key):
        return self.comm.bcast(None)

    # Function to put a key-value pair into the store
    def set(self, key, value):
        self.comm.bcast(value)

    def add(self, key, value):
        return self.comm.Get_size()

    def wait(self, keys, timeout):
        pass

if __name__ == '__main__':
    dist._test_python_store(MPIStore())
```

(i.e. just replace the complicated key/value store logic by a simple brodcast to set up NCCL)

Workaround:
```
torch.distributed.distributed_c10d.PrefixStore = lambda x, s: s
torch.distributed.init_process_group("nccl",
                                     store=MPIStore(),
                                     rank=comm.Get_rank(),
                                     world_size=comm.Get_size())
```

i.e. monkey patch the PrefixStore to be a no-op.

It would be nice if PrefixStore could be updated to accept custom Python stores.

To address the underlying issue of distributed setup, it should be possible to initialize NCCL using MPI communicators instead of using TCP. Perhaps revamping the logic behind the k/v stores and reducing them to a `bcast` call might help here, if it applies to all other back ends as well.

### Versions

tested with 2.0

**Comment by wconstab** [comment]
@fduwjj added an API recently to access the inner store from the PrefixStore.
_underlying_non_prefix_store

Not too sure if that's useful.  I'm not actually sure what you're trying to accomplish.  (or why you run out of file handles..)   Are you using TCPStore or FileStore in that case?

Agreed it'd be nice to support MPI rendezvous more natively.  @pavanbalaji has some ideas here.

cc @shuqiangzhang

**Comment by jglaser** [comment]
> @fduwjj added an API recently to access the inner store from the PrefixStore. _underlying_non_prefix_store
> 
> Not too sure if that's useful. I'm not actually sure what you're trying to accomplish. (or why you run out of file handles..) Are you using TCPStore or FileStore in that case?
> 
> Agreed it'd be nice to support MPI rendezvous more natively. @pavanbalaji has some ideas here.
> 
> cc @shuqiangzhang

Hi @wconstab  ... thanks!  Here's a short synopsis of what I am trying to accomplish.

I am running pytorch on >1000 nodes of Summit at ornl.gov, or >6000 GPUs. At that level, distributed's TCPStore creates resource contention, as every connection requires a file descriptor on the root node. We have a constant ulimit of 8192 files on every node, which we cross at a few hundred nodes, beyond which TCPStore will not scale.

To mitigate that, I wrote the above class. It isolates the required functionality from the bootstrap process, namely, a bcast, and uses MPI instead to perform this operation. MPI scales naturally on our machine, since it is designed to handle thousands of nodes.

Regarding the prefix store, that was my observation that it is not currently possible to directly pass the custom python store to `torch.distributed.init_process_group`, it fails because the PrefixStore somehow doesn't work with custom stores. Simply disabling it seems to be a solution. 

Let me change the code above to a reproducer that will "properly fail"

**Comment by wconstab** [comment]
btw there is another user who had similar issues with a wrapper store and resolved them
https://github.com/pytorch/pytorch/issues/115977

i am not sure if your case is the same.

cc @XilunWu for additional insight into the wrapping issue

cc @shuqiangzhang RE the TCPStore file handles issue

**Comment by XilunWu** [comment]
Hi @jglaser , I tried to reproduce the error using a non-MPI store implementation but couldn't. Here is the code snippet I used:

test_store_wrapper.py:
```
import os
import torch
import torch.distributed as dist
from datetime import timedelta
from typing import Optional, overload
from torch._C._distributed_c10d import Store, TCPStore, PrefixStore
from typing import List

class TcpStoreWrapper(Store):
    '''a wrapper of TCPStore, to trace the internal behavior'''

    def __init__(self, rank: int, world_size: int, port: Optional[int] = None, hostname: Optional[str] = None, timeout: Optional[timedelta] = None):
        super().__init__()
        self.rank = rank
        self.is_master = rank == 0
        self.real_store = TCPStore(
            host_name=hostname if hostname is not None else os.getenv("MASTER_ADDR"),
            port=port if port is not None else int(os.getenv("MASTER_PORT")) + 100,
            timeout=timeout,
            world_size=world_size,
            is_master=self.is_master,
            wait_for_workers=True,
        )

    def set(self, key: str, value: str):
        return self.real_store.set(key, value)

    def get(self, key: str) -> bytes:
        return self.real_store.get(key)

    def add(self, key: str, value: int) -> int:
        return self.real_store.add(key, value)

    def compare_set(self, key: str, expected_value: str, desired_value: str) -> bytes:
        return self.real_store.compare_set(key, expected_value, desired_value)

    def delete_key(self, key: str) -> bool:
        return self.real_store.delete_key(key)

    def num_keys(self) -> int:
        return self.real_store.num_keys()

    def set_timeout(self, timeout: timedelta):
        return self.real_store.set_timeout(timeout)

    @overload
    def wait(self, keys: List[str]):
        return self.real_store.wait(keys)

    @overload
    def wait(self, keys: List[str], timeout: timedelta):
        return self.real_store.wait(keys, timeout)

rank = int(os.environ['RANK'])
world_size = int(os.environ['WORLD_SIZE'])
port = int(os.environ['MASTER_PORT']) + 100
store = TcpStoreWrapper(
    hostname="localhost",
    port=port,
    world_size=world_size,
    rank=rank,
    timeout=timedelta(seconds=60),
)
dist._test_python_store(dist.PrefixStore('prefix', store))
print("test succeeds!")
```

Command to run:
`torchrun --nproc_per_node=1 --nnodes 1 --node_rank 0 --master_addr=localhost --master_port=4127 test_store_wrapper.py`

Output:
```
test succeeds!
```

So I wonder if this error is directly related to mpi4py.

**Comment by jglaser** [comment]
In your example, apply the following change
```
#store = TcpStoreWrapper(
#    hostname="localhost",
#    port=port,
#    world_size=world_size,
#    rank=rank,
#    timeout=timedelta(seconds=60),
#)
#dist._test_python_store(dist.PrefixStore('prefix', store))
dist._test_python_store(dist.PrefixStore('prefix', TcpStoreWrapper(
    hostname="localhost",
    port=port,
    world_size=world_size,
    rank=rank,
    timeout=timedelta(seconds=60),
)))
```

and run
```
$ torchrun --nproc_per_node=1 --nnodes 1 --node_rank 0 --master_addr=localhost --master_port=4127 test_store_wrapper.py
Traceback (most recent call last):
  File "/gpfs/alpine2/bif143/proj-shared/glaser/affinity_clip/train/test_store_wrapper.py", line 65, in <module>
    dist._test_python_store(dist.PrefixStore('prefix', TcpStoreWrapper(
RuntimeError: Tried to call pure virtual function "::c10d::Store::add"
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 111185) of binary: /sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/bin/python
Traceback (most recent call last):
  File "/sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sw/summit/ibmsw/minicondas/rocketce-1.10-py3.11-cuda11.8/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test_store_wrapper.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-20_00:01:27
  host      : login4.summit.olcf.ornl.gov
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 111185)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Weird, huh? This seems to apply some issue with garbage collection or reference counting...

**Comment by nicholasmalaya** [comment]
@jglaser interesting analysis. We should discuss options to apply a proposed patch and test it. As it is, we don't yet have a PR that could be reviewed or tested.

**Comment by jeffdaily** [comment]
@jglaser there was a suggestion on a related issue to set USE_LIBUV=1 for improved performance of TCPStore.  Does that work around your need for a custom store?

https://github.com/pytorch/pytorch/issues/115977#issuecomment-1973607134

**Comment by d4l3k** [comment]
**Category: Likely Fixed / Unreproducible**

This issue has been automatically closed. Please reopen if this is still an active issue.
