### ISSUE TITLE
TypeError: unhashable type 'dict'

### ISSUE THREAD

**Issue by Tomsen1410** [pytorch/pytorch#120932]
### 🐛 Describe the bug

I am using pytorch lightning and I was trying to compile my model in default mode. However this error message appeared (without actually throwing an error):

```
Traceback (most recent call last):
  File ".../.vscode-server/extensions/ms-python.python-2024.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 371, in __call__
    if frame_cache_key in cache_skips:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File ".../.vscode-server/extensions/ms-python.python-2024.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 371, in __call__
    if frame_cache_key in cache_skips:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR] Error while creating guard:
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR] Name: "L['self']"
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Source: local
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Create Function: NN_MODULE
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Guard Types: ['ID_MATCH']
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Code List: ["___check_obj_id(L['self'], 140614015217936)"]
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Object Weakref: <weakref at 0x7fe318512d40; to '_ResultMetric' at 0x7fe3406d7110>
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Guarded Class Weakref: <weakref at 0x7fe4a4d3ab10; to 'ABCMeta' at 0x8774df0 (_ResultMetric)>
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR] Created at:
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 245, in __call__
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     vt = self._wrap(value).clone(**self.options())
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 469, in _wrap
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     return self.wrap_module(value)
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 937, in wrap_module
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     return self.tx.output.register_attr_or_module(
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 736, in register_attr_or_module
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     install_guard(source.make_guard(GuardBuilder.NN_MODULE))
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR] Error while creating guard:
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR] Name: "L['self']"
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR]     Source: local
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR]     Create Function: NN_MODULE
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR]     Guard Types: ['ID_MATCH']
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR]     Code List: ["___check_obj_id(L['self'], 140614015217936)"]
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR]     Object Weakref: <weakref at 0x7fe318512d40; to '_ResultMetric' at 0x7fe3406d7110>
[2024-02-29 19:44:37,817] [44/0_1] torch._guards: [ERROR]     Guarded Class Weakref: <weakref at 0x7fe4a4d3ab10; to 'ABCMeta' at 0x8774df0 (_ResultMetric)>
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR] Created at:
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 245, in __call__
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]     vt = self._wrap(value).clone(**self.options())
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 469, in _wrap
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]     return self.wrap_module(value)
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 937, in wrap_module
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]     return self.tx.output.register_attr_or_module(
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 736, in register_attr_or_module
[2024-02-29 19:44:37,819] [44/0_1] torch._guards: [ERROR]     install_guard(source.make_guard(GuardBuilder.NN_MODULE))
```

Afterwards it showed this message:
```
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING]    function: 'resume_in_log' (.../lib/python3.11/site-packages/pytorch_lightning/core/module.py:416)
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING]    last reason: ___check_global_state()
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
[2024-02-29 19:49:40,358] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2024-02-29 19:49:40,358] torch._dynamo.convert_frame: [WARNING]    function: 'log' (.../lib/python3.11/site-packages/pytorch_lightning/core/module.py:358)
[2024-02-29 19:49:40,358] torch._dynamo.convert_frame: [WARNING]    last reason: ___check_global_state()
[2024-02-29 19:49:40,358] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[2024-02-29 19:49:40,358] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
```

It still ran the training eventually, however it showed the annoying unhashable type error during _each_ iteration:
```
Traceback (most recent call last):
  File ".../.vscode-server/extensions/ms-python.python-2024.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 371, in __call__
    if frame_cache_key in cache_skips:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File ".../.vscode-server/extensions/ms-python.python-2024.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 371, in __call__
    if frame_cache_key in cache_skips:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

When using enforce_graph=True it doesn't run at all and throws an error, even though the input shapes are the same for all calls. Both, training and validation.

I honestly have very little knowledge about the underlying workings of the torch.compile stack and do not really have time to dig deep into this. The above messages are quite cryptic to me. Do you know what might cause the error? 

### Versions

Collecting environment information...
PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-169-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB
GPU 4: NVIDIA A100-PCIE-40GB
GPU 5: NVIDIA A100-PCIE-40GB
GPU 6: NVIDIA A100-PCIE-40GB
GPU 7: NVIDIA A100-PCIE-40GB

Nvidia driver version: 535.146.02
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 1
Core(s) per socket:                 32
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              49
Model name:                         AMD EPYC 7452 32-Core Processor
Stepping:                           0
Frequency boost:                    enabled
CPU MHz:                            1823.217
CPU max MHz:                        2350.0000
CPU min MHz:                        1500.0000
BogoMIPS:                           4700.10
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          2 MiB
L2 cache:                           32 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-31
NUMA node1 CPU(s):                  32-63
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.1.3
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.1
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==1.2.1
[pip3] torchvision==0.17.1
[pip3] triton==2.2.0
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0           py311h5eee18b_1
[conda] mkl_fft                   1.3.8           py311h5eee18b_0
[conda] mkl_random                1.2.4           py311hdb19cb5_0
[conda] numpy                     1.26.4          py311h08b1b3b_0
[conda] numpy-base                1.26.4          py311hf175353_0
[conda] pytorch                   2.2.1           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-lightning         2.1.3              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.2.1               py311_cu121    pytorch
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              1.2.1              pyhd8ed1ab_0    conda-forge
[conda] torchtriton               2.2.0                     py311    pytorch
[conda] torchvision               0.17.1              py311_cu121    pytorch

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by anijain2305** [comment]
1) The error msg `Error while creating guard` - should be benign. Basically this one
~~~
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR] Error while creating guard:
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR] Name: "L['self']"
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Source: local
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Create Function: NN_MODULE
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Guard Types: ['ID_MATCH']
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Code List: ["___check_obj_id(L['self'], 140614015217936)"]
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Object Weakref: <weakref at 0x7fe318512d40; to '_ResultMetric' at 0x7fe3406d7110>
[2024-02-29 19:44:37,740] [43/0_1] torch._guards: [ERROR]     Guarded Class Weakref: <weakref at 0x7fe4a4d3ab10; to 'ABCMeta' at 0x8774df0 (_ResultMetric)>
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR] Created at:
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 245, in __call__
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     vt = self._wrap(value).clone(**self.options())
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 469, in _wrap
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     return self.wrap_module(value)
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 937, in wrap_module
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     return self.tx.output.register_attr_or_module(
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]   File ".../lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 736, in register_attr_or_module
[2024-02-29 19:44:37,743] [43/0_1] torch._guards: [ERROR]     install_guard(source.make_guard(GuardBuilder.NN_MODULE))
~~~
I will send a PR to not throw this on stderr.


2) There are recompilations because global_state is changing. 
~~~~
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING]    function: 'resume_in_log' (.../lib/python3.11/site-packages/pytorch_lightning/core/module.py:416)
[2024-02-29 19:49:40,215] torch._dynamo.convert_frame: [WARNING]    last reason: ___check_global_state()
~~~
This could happen if any of the following items change from run to run - https://github.com/pytorch/pytorch/blob/797d4fbdf423dd9320ebe383fb57ffb1135c4a99/torch/csrc/dynamo/guards.cpp#L472-L480

Maybe printing these at the beginning of this function would help - https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/core/module.py#L371


3) This error - `frame_cache_key in cache_skips`. This is weird. The message is saying that frame_cache_key is a dict. Is this a dict for eager. The error is coming from a weird source file - `debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py`. Not sure if this is intended. My bet is that this is not related to `torch.compile`.

**Comment by Tomsen1410** [comment]
Ok thank you!
1. Great!
2. Well, the grad mode is changing during pytorch lightning training, since there are validation epochs inbetween training epochs. Or rather pytorch lightning calls validation_step with gradient computation disabled and training_step with gradients enabled. Might that cause the error? Also, I am using the logging mechanism that you linked in each of the meintioned step functions. Might that be the problem? Can I disable torch compile for these sections?
3. Update: This does **not** happen when I am on another machine (with 80GB A100s instead of 40GB A100s)

**Comment by anijain2305** [comment]
Thanks for the update. Closing the issue. Please feel free to reopen if these issues still persist.
