### ISSUE TITLE
RuntimeError: xnnpack::convolution not available！

### ISSUE THREAD

**Issue by nzbanana** [pytorch/pytorch#120976]
### 🐛 Describe the bug

import torch
import os
os.environ['TORCH_XNNPACK_DISABLE'] = '1'

model=torch.jit.load(r"runs\train\20240227_person_v8n-asf-p2\weights\best1.torchscript", map_location=torch.device("cuda"))
print(model)

----------------------------------------------------------------------------------------------------------------------------
(yolo) D:\Vscode\workspace>python yolov8-hub\model_test.py
Traceback (most recent call last):
  File "D:\Vscode\workspace\yolov8-hub\model_test.py", line 6, in <module>
    model=torch.jit.load(r"runs\train\20240227_person_v8n-asf-p2\weights\best1.torchscript", map_location=torch.device("cuda"))
  File "C:\Users\Administrator\.conda\envs\yolo\lib\site-packages\torch\jit\_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: xnnpack::convolution not available! Reason: The provided (weight, bias, padding, stride, dilation, groups, transposed, output_min, output_max) parameters are either invalid individually or their combination is not supported by XNNPACK.

### Versions

PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: (Rev5, Built by MSYS2 project) 5.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 551.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=198
L2CacheSize=12288
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3600
Name=12th Gen Intel(R) Core(TM) i7-12700KF
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] efficientnet_pytorch==0.7.1
[pip3] numpy==1.23.2
[pip3] onnx==1.15.0
[pip3] onnxruntime-gpu==1.17.0
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.13.1+cu116
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] libblas                   3.9.0              20_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              20_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              20_win64_mkl    conda-forge
[conda] mkl                       2023.2.0         h6a75c08_50497    conda-forge
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

**Comment by digantdesai** [comment]
hmm, can you try with disabling XNNPACK via [USE_XNNPACK](https://github.com/pytorch/pytorch/blob/9cab5987bdeb66df8efbc581b3469bfe300e168c/CMakeLists.txt#L309) CMake variable?
