### ISSUE TITLE
Test failure in pytorch/test/onnx/test_models.py

### ISSUE THREAD

**Issue by spandantiwari** [pytorch/pytorch#12104]
## Issue description
I have built Pytorch from yesterday's (Sept 25th) master. It is a CPU-only release build on Ubuntu 16.04. More details are given below. 

I am trying to run the pytorch/test/onnx/test_models.py test, but it fails to export PixelShuffle op in the SuperResolution.py model.

## Code example
`cd pytorch/test/onnx`
`python test_models.py`

I see the following failure:

```
/home/spandantiwari/pytorch1/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator pixel_shuffle because torch.onnx.symbolic.pixel_shuffle does not exist
  .format(op_name, op_name))
E....
======================================================================
ERROR: test_super_resolution (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/spandantiwari/pytorch1/test/onnx/test_pytorch_common.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/home/spandantiwari/pytorch1/test/common.py", line 119, in wrapper
    fn(*args, **kwargs)
  File "test_models.py", line 86, in test_super_resolution
    self.exportTest(toC(SuperResolutionNet(upscale_factor=3)), toC(x), atol=1e-6)
  File "test_models.py", line 51, in exportTest
    verify(model, inputs, backend, rtol=rtol, atol=atol)
  File "/home/spandantiwari/pytorch1/test/onnx/verify.py", line 354, in verify
    torch_out = torch.onnx._export(model, args, proto_bytes, verbose=verbose)
  File "/home/spandantiwari/pytorch1/torch/onnx/__init__.py", line 22, in _export
    return utils._export(*args, **kwargs)
  File "/home/spandantiwari/pytorch1/torch/onnx/utils.py", line 286, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::pixel_shuffle

Defined at:
/home/spandantiwari/pytorch1/torch/nn/modules/pixelshuffle.py(40): forward
/home/spandantiwari/pytorch1/torch/nn/modules/module.py(465): _slow_forward
/home/spandantiwari/pytorch1/torch/nn/modules/module.py(475): __call__
/home/spandantiwari/pytorch1/test/onnx/model_defs/super_resolution.py(23): forward
/home/spandantiwari/pytorch1/torch/nn/modules/module.py(465): _slow_forward
/home/spandantiwari/pytorch1/torch/nn/modules/module.py(475): __call__
/home/spandantiwari/pytorch1/torch/jit/__init__.py(146): forward
/home/spandantiwari/pytorch1/torch/nn/modules/module.py(477): __call__
/home/spandantiwari/pytorch1/torch/jit/__init__.py(115): get_trace_graph
/home/spandantiwari/pytorch1/torch/onnx/utils.py(191): _trace_and_get_graph_from_model
/home/spandantiwari/pytorch1/torch/onnx/utils.py(223): _model_to_graph
/home/spandantiwari/pytorch1/torch/onnx/utils.py(280): _export
/home/spandantiwari/pytorch1/torch/onnx/__init__.py(22): _export
/home/spandantiwari/pytorch1/test/onnx/verify.py(354): verify
test_models.py(51): exportTest
test_models.py(86): test_super_resolution
/home/spandantiwari/pytorch1/test/common.py(119): wrapper
/home/spandantiwari/pytorch1/test/onnx/test_pytorch_common.py(27): wrapper
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/case.py(605): run
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/case.py(653): __call__
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/suite.py(122): run
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/suite.py(84): __call__
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/suite.py(122): run
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/suite.py(84): __call__
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/runner.py(176): run
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/main.py(256): runTests
/home/spandantiwari/anaconda3/envs/pytorch-py36/lib/python3.6/unittest/main.py(95): __init__
/home/spandantiwari/pytorch1/test/common.py(53): run_tests
test_models.py(164): <module>


Graph we tried to export:
graph(%0 : Float(2, 1, 224, 224)
      %1 : Float(64, 1, 5, 5)
      %2 : Float(64)
      %3 : Float(64, 64, 3, 3)
      %4 : Float(64)
      %5 : Float(32, 64, 3, 3)
      %6 : Float(32)
      %7 : Float(9, 32, 3, 3)
      %8 : Float(9)) {
  %9 : Float(2, 64, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%0, %1, %2), scope: SuperResolutionNet/Conv2d[conv1]
  %10 : Float(2, 64, 224, 224) = onnx::Relu(%9), scope: SuperResolutionNet/ReLU[relu]
  %11 : Float(2, 64, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%10, %3, %4), scope: SuperResolutionNet/Conv2d[conv2]
  %12 : Float(2, 64, 224, 224) = onnx::Relu(%11), scope: SuperResolutionNet/ReLU[relu]
  %13 : Float(2, 32, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%12, %5, %6), scope: SuperResolutionNet/Conv2d[conv3]
  %14 : Float(2, 32, 224, 224) = onnx::Relu(%13), scope: SuperResolutionNet/ReLU[relu]
  %15 : Float(2, 9, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%14, %7, %8), scope: SuperResolutionNet/Conv2d[conv4]
  %16 : Long() = onnx::Constant[value={3}]()
  %17 : Float(2, 1, 672, 672) = aten::pixel_shuffle(%15, %16), scope: SuperResolutionNet/PixelShuffle[pixel_shuffle]
  return (%17);
}

```

## System Info
Please note that I am working with a CPU-only release build.

Collecting environment information...
PyTorch version: 1.0.0a0+a6f1ae7
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 7.5.17
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch (1.0.0a0+a6f1ae7, /home/spandantiwari/pytorch1)
[pip] torchvision (0.2.1, /home/spandantiwari/torchvision1)
[conda] magma-cuda90              2.3.0                         1    pytorch
[conda] torch                     1.0.0a0+a6f1ae7           <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by spandantiwari** [comment]
This has been fixed. Thanks!
