### ISSUE TITLE
[FSDP][torch._dynamo.compiled_autograd] Final callbacks can only be installed during backward pass

### ISSUE THREAD

**Issue by zejun-chen** [pytorch/pytorch#121071]
### 🐛 Describe the bug

Hi,

When using `torch.compile` and `torch._dynamo.compiled_autograd` to trace the FSDP model with the backward gradient hooks, the following error happened. According to the following error log, the error message is thrown from the code here: https://github.com/pytorch/pytorch/blob/bab4b5a341609aec3edd6f5cd3918d08e0cfb36c/torch/distributed/fsdp/_runtime_utils.py#L1515-L1519

Here is the error log:
```
Traceback (most recent call last):
  File "/home/bduser/zejun/pytorch/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/home/bduser/zejun/test_1_jiong_fsdp.py", line 48, in fsdp_main
    train(input, target, model, rank, world_size, optimizer)
  File "/home/bduser/zejun/test_1_jiong_fsdp.py", line 30, in train
    loss.backward()
  File "/home/bduser/zejun/pytorch/torch/_tensor.py", line 524, in backward
    torch.autograd.backward(
  File "/home/bduser/zejun/pytorch/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/home/bduser/zejun/pytorch/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/bduser/zejun/pytorch/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bduser/zejun/pytorch/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bduser/zejun/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "/home/bduser/zejun/pytorch/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/bduser/zejun/pytorch/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/home/bduser/zejun/pytorch/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/bduser/zejun/pytorch/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bduser/zejun/pytorch/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.9", line 21, in forward
    call_hook = torch__dynamo_external_utils_call_hook(getitem_14, nll_loss_backward);  getitem_14 = nll_loss_backward = None
  File "/home/bduser/zejun/pytorch/torch/_dynamo/external_utils.py", line 34, in call_hook
    result = hook(*args)
  File "/home/bduser/zejun/pytorch/torch/distributed/fsdp/_runtime_utils.py", line 641, in _pre_backward_hook
    _register_post_backward_final_callback(state, module)
  File "/home/bduser/zejun/pytorch/torch/distributed/fsdp/_runtime_utils.py", line 1518, in _register_post_backward_final_callback
    Variable._execution_engine.queue_callback(
RuntimeError: Final callbacks can only be installed during backward pass.
```

I check the function https://github.com/pytorch/pytorch/blob/bab4b5a341609aec3edd6f5cd3918d08e0cfb36c/torch/distributed/fsdp/_runtime_utils.py#L1499 and find the `torch.distributed._functional_collectives.is_torchdynamo_compiling()` is wrongly **False** when running the reproducer. It should be True i guess because i am doing the trace with the context with `torch._dynamo.compiled_autograd.enable(torch.compile)`. When i manually set it to True, the expected graph with the backward gradient hook op i can get after the `torch.compile`.

Here is the reproducer script:
```
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 4, 3, 1)
        self.conv2 = nn.Conv2d(4, 4, 3, 1)
        self.fc1 = nn.Linear(576, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = F.max_pool2d(x, 2)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        output = F.log_softmax(x, dim=1)
        return output

def train(input, target, model, rank, world_size, optimizer):
    output = model(input)
    loss = F.nll_loss(output, target, reduction='sum')
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    return loss

def fsdp_main(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device("cuda:{}".format(rank))
    model = Net().to("cuda:{}".format(rank))
    model = FSDP(model, device_id="cuda:{}".format(rank), use_orig_params=True).train()
    optimizer = optim.Adadelta(model.parameters(), lr=0.1)
    model = torch.compile(model)

    input = torch.randn(4, 1, 28, 28).to("cuda:{}".format(rank))
    target = torch.randint(1, 10, (4,)).to("cuda:{}".format(rank))

    with torch._dynamo.compiled_autograd.enable(torch.compile):
        train(input, target, model, rank, world_size, optimizer)
    dist.destroy_process_group()

if __name__ == '__main__':
    WORLD_SIZE = 2
    mp.spawn(fsdp_main, args=(WORLD_SIZE,), nprocs=WORLD_SIZE, join=True)
```

Here is the simplified expected graph i can get when the `torch.distributed._functional_collectives.is_torchdynamo_compiling()` is manually set to True in pytorch source code:
```
def forward(self, arg0_1, arg1_1, arg2_1, arg3_1, arg4_1, arg5_1, arg6_1, arg7_1, arg8_1, arg9_1, arg10_1):
    alias = torch.ops.aten.alias.default(arg1_1);  arg1_1 = None
    alias_1 = torch.ops.aten.alias.default(alias);  alias = None
    alias_2 = torch.ops.aten.alias.default(alias_1);  alias_1 = None
    alias_3 = torch.ops.aten.alias.default(alias_2);  alias_2 = None
    exp = torch.ops.aten.exp.default(alias_3);  alias_3 = None
    sum_1 = torch.ops.aten.sum.dim_IntList(arg0_1, [1], True)
    mul = torch.ops.aten.mul.Tensor(exp, sum_1);  exp = sum_1 = None
    .........
    cat = torch.ops.aten.cat.default([view_7, view_6, view_5, view_4, view_3, view_2]);  view_7 = view_6 = view_5 = view_4 = view_3 = view_2 = None
    accumulate_grad_ = torch.ops.inductor.accumulate_grad_.default(arg10_1, cat);  arg10_1 = None
    return (cat,)
```

Thank you.

### Versions

PyTorch version: 2.3.0a0+git2de7468
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.31

Python version: 3.9.7 (default, Oct 27 2021, 01:23:21)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-149-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3396.848
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4491.63
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] flake8==3.8.2
[pip3] flake8-bugbear==20.1.4
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.3.0
[pip3] flake8-executable==2.0.4
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==20.5.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] optree==0.10.0
[pip3] pytorch-triton==3.0.0+901819d2b6
[pip3] torch==2.3.0a0+git2de7468
[pip3] torchaudio==2.1.2+cu118
[pip3] torchvision==0.16.2+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] pytorch-triton            3.0.0+901819d2b6          pypi_0    pypi
[conda] torch                     2.3.0a0+git2de7468           dev_0    <develop>
[conda] torchaudio                2.1.2+cu118              pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchvision               0.16.2+cu118             pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by zejun-chen** [comment]
CC: @ezyang @voznesenskym @albanD @wconstab @zou3519 @jansel 
CC: @jgong5 @gujinghui

**Comment by ezyang** [comment]
Cc @jansel

**Comment by jansel** [comment]
cc @yf225

**Comment by jansel** [comment]
The fix here would be to insert an op into the backwards graph that registers the final callback hook.

**Comment by zejun-chen** [comment]
@ezyang @jansel BTW, may i know why the ops registered by the `torch.Tensor.register_post_accumulate_grad_hook` are traced as `torch.ops.inductor.accumulate_grad_.default` onto the graph instead of the ops in the hook function, something like collective ops?

**Comment by yf225** [comment]
> @ezyang @jansel BTW may i know why the ops registered by the `torch.Tensor.register_post_accumulate_grad_hook` are traced uniformly as `torch.ops.inductor.accumulate_grad_.default` onto the compiled graph instead of the ops in the hook function, something like collective ops?

It's not traced as accumulate_grad_ - those ops come from the autograd engine itself.

We will see the ops including collectives in the hook function once the `torch.Tensor.register_post_accumulate_grad_hook` support is complete. It's still missing some pieces which you can find in my PR if you search for related strings: https://github.com/pytorch/pytorch/pull/120442.

I believe there are other things missing for compiling flat-parameter FSDP. Our focus is on compiling per-parameter FSDP now and it's being  tracked in my PR above, and we expect to post an update on this within the next few weeks.

**Comment by zejun-chen** [comment]
Thank you @yf225 
From above, the collective ops in the backward hook function will be traced onto the graph when your PR is merged.

BTW, i see stream methods(like `wait_stream`) in FSDP are bypass when doing tracing. I wonder why bypass stream in FSDP and if it is a short term plan.
https://github.com/pytorch/pytorch/pull/120442/files#diff-1db25273fb600ec451c57e5a26c98898152448157d593b7f5bc7a35b2bf1b22eR56-R57
https://github.com/pytorch/pytorch/pull/115497/files#diff-d927c975c46aa38a36dea309c29331545c50844e8e2671201a8c7eb8bac2017bR445-R446

**Comment by yf225** [comment]
@zejun-chen Wonder do you have a specific use case for tracing stream methods?

The current short-term plan for stream are to ignore those method usages on user code side, and rely on Inductor to insert the right ops to achieve multi-stream compute/comm overlaps

**Comment by zejun-chen** [comment]
> @zejun-chen Wonder do you have a specific use case for tracing stream methods?
> 
> The current short-term plan for stream are to ignore those method usages on user code side, and rely on Inductor to insert the right ops to achieve multi-stream compute/comm overlaps

Thank you for reply @yf225 
We accept Meta's design of relying on inductor to achieve the overlapping for computation ops and communication ops by doing some reorder passes. We have just a toy example for the risk when ignoring the stream:
```
stream1 = torch.cuda.Stream()
def async(x):
    with torch.cuda.stream(stream1):
        x = x + 1.0
    return x

@torch.compile(backend='inductor’)
def test(x):
    stream1.synchronize() # ignore sync maybe risky here because some computation on stream1 may not finish execution
    x = x + 2.0
    ....
test(async(x))
```

**Comment by zejun-chen** [comment]
BTW @yf225 , IIRC the inductor uses the greedy optimization policy to schedule the collective ops and `wait_tensor` ops. The collective ops are moved as early as possible and the `wait_tensor` ops are moved as late as possible according to the data dependency.

If the user code is like below, my intuitive is the collective ops(all reduce) will be moved after the op2 and the `wait_tensor` op will be moved before the op6, then the collective ops execution can be overlapped with the op3 and op5.
```
@torch.compile()
def train(x, y):
    x = x + 1.0 #op1
    y = y + 2.0 #op2
    x = x + 3.0 #op3
    dist.all_reduce(y, group=list(range(dist.get_world_size()))) #op4
    x = x + 4.0 #op5
    y = y + 5.0 #op6
    return x + y #op7
```

But the compiled graph is shown as below after the inductor transformation:
```
def forward(self, arg0_1: "f32[4]", arg1_1: "f32[4]"):
    # File: /home/bduser/zejun/collective_ops.py:18 in train, code: x = x + 1.0
    add: "f32[4]" = torch.ops.aten.add.Tensor(arg0_1, 1.0);  arg0_1 = None

    # File: /home/bduser/zejun/collective_ops.py:20 in train, code: x = x + 3.0
    add_2: "f32[4]" = torch.ops.aten.add.Tensor(add, 3.0);  add = None

    # File: /home/bduser/zejun/collective_ops.py:22 in train, code: x = x + 4.0
    add_3: "f32[4]" = torch.ops.aten.add.Tensor(add_2, 4.0);  add_2 = None

    # File: /home/bduser/zejun/collective_ops.py:19 in train, code: y = y + 2.0
    add_1: "f32[4]" = torch.ops.aten.add.Tensor(arg1_1, 2.0);  arg1_1 = None

    # File: /home/bduser/zejun/pytorch/torch/distributed/_functional_collectives.py:190 in all_reduce, code: tensor = torch.ops._c10d_functional.all_reduce(
    all_reduce: "f32[4]" = torch.ops._c10d_functional.all_reduce_.default(add_1, 'sum', '0');  add_1 = None

    # File: /home/bduser/zejun/pytorch/torch/distributed/_functional_collectives.py:146 in wait_tensor, code: return torch.ops._c10d_functional.wait_tensor(tensor)  # type: ignore[attr-defined]
    wait_tensor: "f32[4]" = torch.ops._c10d_functional.wait_tensor.default(all_reduce);  all_reduce = None

    # File: /home/bduser/zejun/collective_ops.py:23 in train, code: y = y + 5.0
    add_4: "f32[4]" = torch.ops.aten.add.Tensor(wait_tensor, 5.0);  wait_tensor = None

    # File: /home/bduser/zejun/collective_ops.py:24 in train, code: return x + y
    add_5: "f32[4]" = torch.ops.aten.add.Tensor(add_3, add_4);  add_3 = add_4 = None
    return (add_5,)
```
It looks like no overlapping because the transformation is like below.
```
@torch.compile()
def train(x, y):
    x = x + 1.0 #op1
    x = x + 3.0 #op3
    x = x + 4.0 #op5
    y = y + 2.0 #op2
    dist.all_reduce(y, group=list(range(dist.get_world_size()))) #op4
    y = y + 5.0 #op6
    return x + y #op7
```

**Comment by zejun-chen** [comment]
Hi, @yf225 

I choose a test case from the pytorch cases to check the reorder pass of inductor for sink waits and raise comms.
Here is the test case.
```
torch._inductor.config.reorder_for_compute_comm_overlap = True
torch._inductor.config.reorder_for_compute_comm_overlap_passes = ["sink_waits", "raise_comms"]
torch._inductor.config.allow_buffer_reuse = True
torch._inductor.config.compile_threads = 1

@torch.compile()
def train(a):
    c = torch.relu(a)
    d = torch.matmul(c, c)
    ar = _functional_collectives.all_reduce(a, "sum", [0, 1], "")
    e = d + ar
    return e
```

The output code is here. The allreduce should be scheduled above the relu, but it is behind the relu in the gen output code. And there are 2 allreduce ops: one is `triton_poi_fused_all_reduce_relu_0`, the other is `torch.ops._c10d_functional.all_reduce_.default`.
```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (4, 4), (4, 1))
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0)
        buf0 = empty_strided_cuda((4, 4), (4, 1), torch.float32)
        buf5 = empty_strided_cuda((4, 4), (4, 1), torch.float32)
        # Source Nodes: [c, tensor], Original ATen: [_c10d_functional.all_reduce, aten.relu]
        stream0 = get_raw_stream(0)
        triton_poi_fused_all_reduce_relu_0.run(arg0_1, buf0, buf5, 16, grid=grid(16), stream=stream0)
        del arg0_1
        # Source Nodes: [tensor], Original ATen: [_c10d_functional.all_reduce]
        buf1 = torch.ops._c10d_functional.all_reduce_.default(buf0, 'sum', '0')      ------------------------- is this op redundant or wrongly code gen?
        # Source Nodes: [ar], Original ATen: [_c10d_functional.wait_tensor]
        buf3 = torch.ops._c10d_functional.wait_tensor.default(buf0)
        buf6 = empty_strided_cuda((4, 4), (4, 1), torch.float32)
        # Source Nodes: [c], Original ATen: [aten.relu]
        extern_kernels.addmm(buf0, buf5, buf5, alpha=1, beta=1, out=buf6)
        del buf0
        del buf5
    return (buf6, )
```
It looks like the `buf1 = torch.ops._c10d_functional.all_reduce_.default(buf0, 'sum', '0')` is redundant. Does the `triton_poi_fused_all_reduce_relu_0.run(arg0_1, buf0, buf5, 16, grid=grid(16), stream=stream0)` contain the allreduce and relu ops.

Thank you.

**Comment by yf225** [comment]
@zejun-chen For the reordering issue, would you like to open a new Github issue to discuss? Also would recommend testing on latest nightly because @yifuwang's recent work on improving the Inductor comm reordering pass might've fixed this. Thanks!

**Comment by zejun-chen** [comment]
Hi, @yf225 @BoyuanFeng 

Thank you for help. We will test the latest nightly and give a update.

Thank you.

**Comment by zejun-chen** [comment]
Close the issue because we have verified the reorder pass of inductor for the computation and the communication overlapping, it works fine. Commit we are using: `2.6.0a0+gitd745b2b`
Thank you all!
