### ISSUE TITLE
UnsupportedOperatorError: Exporting the operator ::_transformer_encoder_layer_fwd to ONNX opset

### ISSUE THREAD

**Issue by Peterzzz-hub** [pytorch/pytorch#121109]
### 🐛 Describe the bug

when i try to export onnx model from fairseq, i encountered this error. plz help support this operator

```
Traceback (most recent call last):
  File "/home/workspace/terminal_launching/pt2onnx.py", line 92, in <module>
    torch.onnx.export(model.encoder, sample_input['net_input'], onnx_file_path, input_names=input_names, output_names=output_names, verbose=True, opset_version=14)
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/envs/train-test/lib/python3.8/site-packages/torch/onnx/utils.py", line 1421, in _run_symbolic_function
    raise symbolic_registry.UnsupportedOperatorError(
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::_transformer_encoder_layer_fwd to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

```

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 21:04:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.55

**Comment by thiagocrepaldi** [comment]
torch.onnx.export doens't support this operator and we don't have plans to support it.

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
