### ISSUE TITLE
NllLoss tracing fails with Cannot call numel() on tensor with symbolic sizes/strides 

### ISSUE THREAD

**Issue by jthakurH** [pytorch/pytorch#121218]
### 🐛 Describe the bug

Issue is with dynamic=auto/True, if we disable the dynamic shape then it works fine.

### Error logs

```
running iter: 0
running iter: 1
Traceback (most recent call last):
  File "/tmp/test/../nllLoss.py", line 29, in <module>
    result = compiled_model(ifm_param)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1523, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1523, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1252, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 301, in call_function
    return wrap_fx_proxy(
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1314, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1399, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1525, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1486, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1027, in wrap_fake_exception
    return fn()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1487, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1592, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1576, in run_node
    return nnmodule(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1523, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 216, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/tmp/lib/python3.10/site-packages/torch/nn/functional.py", line 2733, in nll_loss
    return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
torch._dynamo.exc.TorchRuntimeError: Failed running call_module L__self___op(*(), **{'input': FakeTensor(..., size=(16, s0, 8), requires_grad=True), 'target': FakeTensor(..., size=(16, 8), dtype=torch.int64)}):
Cannot call numel() on tensor with symbolic sizes/strides
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7f39b3b9a97e in /tmp/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::TensorImpl::throw_cannot_call_with_symbolic(char const*) const + 0xa2 (0x7f39b3b433d2 in /tmp/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x57a8f (0x7f39b3b74a8f in /tmp/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #3: at::native::nll_loss_nd_symint(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, long, c10::SymInt) + 0xd96 (0x7f39a42c85a6 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x293b432 (0x7f39a54e4432 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x704328 (0x7f39aea29328 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x7010a5 (0x7f39aea260a5 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x14312af (0x7f39a3fda2af in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x704328 (0x7f39aea29328 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x7010a5 (0x7f39aea260a5 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x20686af (0x7f39a4c116af in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #11: at::_ops::nll_loss_nd::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, long, c10::SymInt) + 0x453 (0x7f39a4bd16a3 in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x64918a (0x7f39ae96e18a in /tmp/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>


from user code:
   File "/tmp/test/../nllLoss.py", line 10, in forward
    result = self.op(**ifm_param)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

### Minified repro

```
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.op = torch.nn.NLLLoss()

    def forward(self, ifm_param):
        result = self.op(**ifm_param)
        return result


if __name__ == "__main__":
    torch.manual_seed(0)
    compiled_model = torch.compile(Model())
    ifm_params = [
        {
            "input": torch.randn([16, 24, 8], requires_grad=True),
            "target": torch.randint(low=0, high=10, size=[16, 8]),
        },
        {
            "input": torch.randn([16, 13068, 8], requires_grad=True),
            "target": torch.randint(low=0, high=50, size=[16, 8]),
        },
    ]
    for i, ifm_param in enumerate(ifm_params):
        print(f"running iter: {i}")
        result = compiled_model(ifm_param)
print("Successfully executed!")


```

### Versions

[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.0
[pip3] torchdata==0.7.1
[pip3] torchmetrics==1.2.1
[pip3] torchtext==0.17.0
[pip3] torchvision==0.17.0

**Comment by ezyang** [comment]
should be easy fix

**Comment by ezyang** [comment]
@eellison actually already fixed this
