### ISSUE TITLE
torch.Tensor.random_ causes invalid syntax in InternalTorchDynamoError

### ISSUE THREAD

**Issue by jthakurH** [pytorch/pytorch#121621]
### 🐛 Describe the bug

The op signature from https://pytorch.org/docs/stable/generated/torch.Tensor.random_.html#torch.Tensor.random_ 
is that first argument is from and second to, looks like this is causing trouble in tracing

### Error logs

```
Traceback (most recent call last):
  File "/tmp/add.py", line 13, in <module>
    res = random_op(tensor, params)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 665, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 919, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1063, in compile_and_call_fx_graph
    gm = fx.GraphModule(root, self.graph)
  File "/tmp/lib/python3.10/site-packages/torch/fx/graph_module.py", line 428, in __init__
    self.graph = graph
  File "/tmp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in __setattr__
    super().__setattr__(name, value)
  File "/tmp/lib/python3.10/site-packages/torch/fx/graph_module.py", line 472, in graph
    self.recompile()
  File "/tmp/lib/python3.10/site-packages/torch/fx/graph_module.py", line 724, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals, co_fields)
  File "/tmp/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 122, in fx_forward_from_src_skip_result
    result: types.FunctionType = original_forward_from_src(*args, **kwargs)
  File "/tmp/lib/python3.10/site-packages/torch/fx/graph_module.py", line 88, in _forward_from_src
    return _method_from_src(
  File "/tmp/lib/python3.10/site-packages/torch/fx/graph_module.py", line 98, in _method_from_src
    _exec_with_source(src, globals_copy, co_fields)
  File "/tmp/lib/python3.10/site-packages/torch/fx/graph_module.py", line 84, in _exec_with_source
    exec(compile(src, key, "exec"), globals)
torch._dynamo.exc.InternalTorchDynamoError: invalid syntax (<eval_with_key>.0, line 6)
```

### Minified repro

```
import torch


def random_op(tensor, params):
    res = tensor.random_(**params)
    return res


if __name__ == "__main__":
    random_op = torch.compile(random_op)
    params = {"from": -10, "to": 10}
    tensor = torch.randn([2, 3])
    res = random_op(tensor, params)
    print(res)
```

### Versions

[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.0
[pip3] torchdata==0.7.1
[pip3] torchmetrics==1.2.1
[pip3] torchtext==0.17.0
[pip3] torchvision==0.17.0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by LamForest** [comment]
I can reproduce in main. It is weired `res = tensor.random_()` and `res = tensor.random_(**{ "to":10})` okay, but `res = tensor.random_(**{ "from":10, "to":10})` failed.

Maybe because `from` is a python keyword, but it cannot explain why `res = tensor.uniform_(**{"from":-10, "to":10})` is okay...
