### ISSUE TITLE
Error building a custom PyTorch CUDA extension with 1.0 on macOS High Sierra

### ISSUE THREAD

**Issue by michhar** [pytorch/pytorch#12169]
## 🐛 Bug

I am getting an error during the build of a custom CUDA extension with PyTorch 1.0 on macOS High Sierra.  I built PyTorch from source with `clang version 3.9.1 (tags/RELEASE_391/final)`.   This build worked once with a `pip install` of PyTorch 0.4.1 and `gcc-7`, however I wanted to upgrade from 0.4.1 to 1.0 for these extensions.  I have CUDA and cuDNN, but no NVIDIA GPU.

Please see stack trace below and additional information for context.  And thank you, a ton, in advance for any help/guidance/direction/questions back/magic wand/bandaid.

## To Reproduce

1.  See environment below for setup
1. Check out this folder `https://github.com/michhar/pytorch-mask-rcnn-samples/tree/master/roialign`
1. Run this build command for the PyTorch extension (excuse the format as it was run from a Jupyter notebook sitting on top of the System 3.6 Python install as the kernel - but you get the idea):
```
! export PATH=/Developer/NVIDIA/CUDA-10.0/bin:$PATH &&\
    export LD_LIBRARY_PATH=//Developer/NVIDIA/CUDA-10.0/lib:$LD_LIBRARY_PATH &&\
    export CUDA_BIN_PATH=/Developer/NVIDIA/CUDA-10.0/bin &&\
    export CUDA_TOOLKIT_ROOT_DIR=/Developer/NVIDIA/CUDA-10.0 &&\
    export CUDNN_LIB_DIR=/Developer/NVIDIA/CUDA-10.0/lib &&\
    export USE_CUDA=1 &&\
    export CC=clang &&\
    export CXX=clang++ &&\
    cd roialign/roi_align/src/cuda/ &&\
    nvcc -c -o crop_and_resize_kernel.cu.o crop_and_resize_kernel.cu -x cu -Xcompiler -fPIC &&\
    cd ../../ &&\
    python3 build.py
```

(See below)

## Expected behavior

Compiled cuda extension:  `crop_and_resize_kernel.cu.o`

## Environment

Please copy and paste the output from our
[environment collection script]

**Some values could not be collected and are manually specified in bold**
```
PyTorch version: 1.0.0a0+c35f85a
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.9.0-rc5

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn.dylib
/usr/local/cuda/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.15.2)
[pip3] torch (1.0.0a0+c35f85a)
[pip3] torchvision (0.2.1)
[conda] Could not collect
```

**Nvidia driver version:  Not known**
**cuDNN version: 7.3.0**

I don't have an NVIDIA GPU

 - PyTorch Version (e.g., 1.0): 1.0.0a0+c35f85a
 - OS (e.g., Linux): macOS High Sierra
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source) (from Jupyter):
```
! export PATH=/usr/local/cuda/bin:$PATH &&\
    export LD_LIBRARY_PATH=/usr/local/cuda/lib:$LD_LIBRARY_PATH &&\
    export CUDA_BIN_PATH=/usr/local/cuda/bin &&\
    export CUDA_TOOLKIT_ROOT_DIR=/Developer/NVIDIA/CUDA-10.0 &&\
    export CUDNN_LIB_DIR=/usr/local/cuda/lib &&\
    export CUDA_HOST_COMPILER=/usr/bin/gcc &&\
    export USE_CUDA=1 &&\
    export CC=clang &&\
    export CXX=clang++ &&\
    git clone --recursive https://github.com/pytorch/pytorch &&\
    cd pytorch &&\
    pip3 uninstall torch --yes &&\
    python3 setup.py clean &&\
    python3 setup.py build &&\
    TORCH_CUDA_ARCH_LIST="3.7" python3 setup.py install
```
 - Python version: 3.6 (Python.org)
 - CUDA/cuDNN version: 10.0/7.3.0
 - GPU models and configuration: N/A
 - Any other relevant information:

### Stack trace snippet

```
In file included from /Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:1:
In file included from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:16:
In file included from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:14:
In file included from generic/THTensor.h:1:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:31: warning: 
      redefinition of typedef 'at_Tensor_Impl' is a C11 feature
      [-Wtypedef-redefinition]
typedef struct at_Tensor_Impl at_Tensor_Impl;
                              ^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:31: note: 
      previous definition is here
typedef struct at_Tensor_Impl at_Tensor_Impl;
                              ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:126:33: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int batch_size = image->size[0];
                           ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:127:28: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int depth = image->size[1];
                      ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:128:35: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int image_height = image->size[2];
                             ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:129:34: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int image_width = image->size[3];
                            ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:131:32: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int num_boxes = boxes->size[0];
                          ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:167:39: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int batch_size = grads_image->size[0];
                           ~~~~~~~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:168:34: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int depth = grads_image->size[1];
                      ~~~~~~~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:169:41: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int image_height = grads_image->size[2];
                             ~~~~~~~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:170:40: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int image_width = grads_image->size[3];
                            ~~~~~~~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:172:32: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int num_boxes = grads->size[0];
                          ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:173:34: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int crop_height = grads->size[2];
                            ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
/Users/micheleenharris/Documents/bin/github/pytorch-mask-rcnn-samples/roialign/roi_align/src/crop_and_resize.c:174:33: error: 
      incomplete definition of type 'struct at_Tensor_Impl'
    const int crop_width = grads->size[3];
                           ~~~~~^
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:14:16: note: 
      forward declaration of 'struct at_Tensor_Impl'
typedef struct at_Tensor_Impl at_Tensor_Impl;
               ^
14 warnings and 12 errors generated.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 40, in <module>
    ffi.build()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'clang' failed with exit status 1
```

**Comment by zou3519** [comment]
We deprecated and removed FFI two days ago. Please try to build our new C++ extension API: https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by soumith** [comment]
closed via @zou3519 's comment
