### ISSUE TITLE
Compiling SwinTransformer encoder fail with input size changes

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#121637]
### 🐛 Describe the bug

Compiling SwinTransformer forward at https://github.com/yoxu515/aot-benchmark/blob/paot/networks/encoders/swin/swin_transformer.py#L684

It is going to work correctly at training time when it works on a fixed input crop.

It is going to fail instead at inference when the input size change.

### Error logs

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/workspace/tools/eval.py", line 30, in main_worker
    evaluator.evaluating()
  File "/workspace/./networks/managers/evaluator.py", line 402, in evaluating
    engine.add_reference_frame(current_img,
  File "/workspace/./networks/engines/aotv3_engine.py", line 647, in add_reference_frame
    aot_engine.add_reference_frame(img,
  File "/workspace/./networks/engines/aotv3_engine.py", line 206, in add_reference_frame
    curr_enc_embs, curr_one_hot_mask = self.encode_one_img_mask(
  File "/workspace/./networks/engines/aotv3_engine.py", line 136, in encode_one_img_mask
    curr_enc_embs = self.AOT.encode_image(img)
  File "/workspace/./networks/models/aotv3.py", line 163, in encode_image
    xs = self.encoder(img)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/workspace/./networks/encoders/swin/swin_transformer.py", line 702, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 484, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 548, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 984, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1161, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1234, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1215, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 533, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 112, in inner
    flat_f_outs = f(*flat_f_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 676, in functional_call
    out = PropagateUnbackedSymInts(mod).run(
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 651, in run_node
    result = super().run_node(n)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 274, in call_function
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py", line 411, in __torch_dispatch__
    outs_unwrapped = func._op_dk(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 896, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1241, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 974, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1393, in _dispatch_impl
    return decomposition_table[func](*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 754, in slice_forward
    if end_val < start_val:
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 374, in __bool__
    return self.node.bool_()
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 432, in bool_
    return self.guard_bool("", 0)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 374, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 255, in wrapper
    return event.run(self)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 156, in run
    return self.f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4124, in evaluate_expr
    raise self._make_data_dependent_error(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
GuardOnDataDependentSymNode: Could not guard on data-dependent expression u2 - 7 < 0 (unhinted: u2 - 7 < 0).  (Size-like symbols: u2)

Potential framework code culprit (scroll up for full backtrace):
  File "/opt/conda/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 754, in slice_forward
    if end_val < start_val:

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u2"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing


While executing %setitem : [num_users=0] = call_function[target=operator.setitem](args = (%img_mask, (slice(None, None, None), slice(0, -7, None), slice(0, -7, None), slice(None, None, None)), 0), kwargs = {})
Original traceback:
  File "/workspace/./networks/encoders/swin/swin_transformer.py", line 449, in forward
    img_mask[:, h, w, :] = cnt


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

last `pytorch-nightly` official docker image.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by ezyang** [comment]
Thanks for the report @bhack. Did you try diagnosing with the doc linked in the error message?

At some point I can take a look, but the full model repro instructions would be useful.

**Comment by bhack** [comment]
If we follow the docs in the report and log is correct  we have
``` python
for h in h_slices:
    for w in w_slices:
        img_mask[:, h, w, :] = cnt
        cnt += 1
```

That  it seems to generate the `setitem`:
`While executing %setitem : [num_users=0] = call_function[target=operator.setitem](args = (%img_mask, (slice(None, None, None), slice(0, -7, None), slice(0, -7, None), slice(None, None, None)), 0), kwargs = {})`

`h` and `w` could be variable at inference and they are constant in training.

The docs is relative to `data-dependent control flow` but here there is not an explicit control flow in the user code but probably it is in the underline generated code.

> But the full model repro instructions would be useful.

As this model is a good source of many compiler errors I have already shared some instruction in other tickets to setup the environment with the hope you could adopt this model more in general to stress test the compiler:
https://github.com/pytorch/pytorch/issues/118865#issuecomment-1924745100

In this case we need to run the `eval.py` on different image sizes.

**Comment by ezyang** [comment]
I think it may work to explicitly test with `torch._check` that the h and w are in bounds for `img_mask` before doing the index. Your simplified code looks relatively simple and can take a look later.

**Comment by bhack** [comment]
/cc @williamwen42 is on another ticket for two other issue on the same model but for another sub-component at https://github.com/pytorch/pytorch/issues/121504.

Then we have also another open ticket same model at https://github.com/pytorch/pytorch/issues/118865

**Comment by bhack** [comment]
@ezyang Is it possible that something is missing cause how it handles slices?

> I think it may work to explicitly test with torch._check that the h and w are in bounds for img_mask before doing the index. Your simplified code looks relatively simple and can take a look later.

```python
        h_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        w_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        
        cnt = 0
        for h in h_slices:
            for w in w_slices:
                img_mask[:, h, w, :] = cnt
                cnt += 1
```

Cause manually adding `torch._check` in the loop for W and H and transforming slices in range it is working.

And then it is failing just few row later with the same bug for:
```python
        if self.downsample is not None:
            x_down = self.downsample(x, H, W)
            Wh, Ww = (H + 1) // 2, (W + 1) // 2
```

```python

While executing %setitem : [num_users=0] = call_function[target=operator.setitem](args = (%img_mask, (slice(None, None, None), slice(0, -7, None), slice(0, -7, None), slice(None, None, None)), 0), kwargs = {})
Original traceback:
  File "/workspace/./networks/encoders/swin/swin_transformer.py", line 466, in forward
    Wh, Ww = (H + 1) // 2, (W + 1) // 2
```

**Comment by ezyang** [comment]
Do the same trick but with the downsampled sizes.

We should do better for this case, but it is difficult because when you do a slice that is out of bounds, the semantics of PyTorch is to clamp to the max value, and this is painful to generate code for (we'd much rather know that the slice range is never out of bounds). Maybe we should introduce a variant of indexing which assumes everything is in range (this will also remove annoyances with negative indices).

I think I'd be happy to add this model to our overall suite. If you are interested in rolling up your sleeves to do it, open a PR to https://github.com/pytorch/benchmark and then once it's in (I can help), I can add it to our torchbenchmark benchmark runs.

**Comment by bhack** [comment]
In the meantime I have create a workaround to not use python slices (it would be nice if at least when we find slices we could emit a more comprehensible error).

But then later on a child function `x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)`
```pyhton
    @torch.compile
    def forward(self, x):
        """Forward function."""
        x = self.patch_embed(x)

        Wh, Ww = x.size(2), x.size(3)
        if self.ape:
            # interpolate the position embedding to the corresponding size
            absolute_pos_embed = F.interpolate(self.absolute_pos_embed,
                                               size=(Wh, Ww),
                                               mode='bicubic')
            x = (x + absolute_pos_embed).flatten(2).transpose(1,
                                                              2)  # B Wh*Ww C
        else:
            x = x.flatten(2).transpose(1, 2)
        x = self.pos_drop(x)

        outs = []
        for i in range(self.num_layers):
            layer = self.layers[i]
            x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)

            if i in self.out_indices:
                norm_layer = getattr(self, f'norm{i}')
                x_out = norm_layer(x_out)

                out = x_out.view(-1, H, W,
                                 self.num_features[i]).permute(0, 3, 1,
                                                               2).contiguous()
                outs.append(out)

        outs.append(outs[-1])

        return outs
```

```python
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
GuardOnDataDependentSymNode: Could not guard on data-dependent expression Ne(Max(1, u5), u5) (unhinted: Ne(Max(1, u5), u5)).  (Size-like symbols: u5)

ATTENTION: guard_size_oblivious would fix the error, evaluating expression to False.
Maybe you need to add guard_size_oblivious to framework code, see doc below for more guidance.

Potential framework code culprit (scroll up for full backtrace):
  File "/opt/conda/lib/python3.10/site-packages/torch/_prims_common/__init__.py", line 245, in is_contiguous
    if y != expected_stride:

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u5"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
 ```

**Comment by bhack** [comment]
> I think I'd be happy to add this model to our overall suite. If you are interested in rolling up your sleeves to do it, open a PR to https://github.com/pytorch/benchmark and then once it's in (I can help), I can add it to our torchbenchmark benchmark runs.

As @williamwen42 is trying to reproduce the same environment to check other compiler issues at https://github.com/pytorch/pytorch/issues/121504 I have asked if he he is already familiar with the benchmark repository. I could help for sure but I don't think I have the bandwidth to bootstrap the PR on my side as I need to find the time to check how the benchmark standard interface are organized in the repo. But I can support for everything related to the model for sure and compiler failures reproducibility with pytorch nightly versions.

**Comment by ezyang** [comment]
For this one, try patching the line in `torch/_prims_common/__init__.py` to `guard_size_oblivious(y != expected_stride)`

Also, https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit#heading=h.44gwi83jepaj may be of interest

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/122370 for the size oblivious here
