### ISSUE TITLE
[export] Casting `ExportedProgram` module to CUDA after `export` on CPU fails to run inference

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#121761]
### 🐛 Describe the bug

First, we `export` the model on CPU, then move to CUDA to perform inference. Once moved, the inference fails with the following message, even though casting the original model directly to CUDA works without issue.

```bash
Traceback (most recent call last):
  File "~/sample.py", line 487, in <module>
    gm(*inputs)
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1577, in _call_impl
    result = forward_call(*args, **kwargs)
  File "<eval_with_key>.9", line 66, in forward
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

**Sample Script:**
```python
import torch
from torch.export import export

class Sample(torch.nn.Module):
   def __init__(self, size, h_dim, **kwargs):
       super(Sample, self).__init__(**kwargs)
       self.rnn = torch.nn.GRU(size, h_dim, batch_first=True)
 
   def forward(self, x):
       _, states = self.rnn(x)
       return states

mod = Sample(size=19, h_dim=40)
mod.eval()

gm = export(mod, (torch.rand((1, 40, 19)),)).module()
gm=gm.to("cuda")

inputs = (torch.rand((1, 40, 19)).cuda(),)
gm(*inputs)
```

The above was proposed as a workaround to #120626.

### Versions

```bash
torch==2.3.0.dev20240312+cu121
```

**Comment by zhxchen17** [comment]
@gs-olive I can take a look at this. thanks for reporting this issue!

**Comment by angelayi** [comment]
Sorry, forgot to add my previous investigation, but this is because we burn in the "cpu" device into one of the ops in the exported program, so doing gm.to("cuda") doesn't exactly work.

**Comment by angelayi** [comment]
https://github.com/pytorch/pytorch/issues/104998 is related to this issue

**Comment by gs-olive** [comment]
As suggested, I tested out manually casting the `device: cpu` keyword to `cuda`, as below. I verified all of the weights were on CUDA as well. The sample script, output graph, and error message are shown below.

```python
import torch
from torch.export import export

class Sample(torch.nn.Module):
   def __init__(self, size, h_dim, **kwargs):
       super(Sample, self).__init__(**kwargs)
       self.rnn = torch.nn.GRU(size, h_dim, batch_first=True)
 
   def forward(self, x):
       _, states = self.rnn(x)
       return states

mod = Sample(size=19, h_dim=40)
mod.eval()

gm = export(mod, (torch.rand((1, 40, 19)),)).module()
gm=gm.to("cuda")

for node in gm.graph.nodes:
    if "device" in node.kwargs:
        kwargs = node.kwargs.copy()
        kwargs["device"] = "cuda"
        node.kwargs = kwargs

inputs = (torch.rand((1, 40, 19)).cuda(),)
exported = export(mod, (torch.rand((1, 40, 19)),))
```

**Refactored Graph**
```python
graph():
    %rnn_weight_ih_l0 : [num_users=1] = get_attr[target=rnn.weight_ih_l0]
    %rnn_weight_hh_l0 : [num_users=40] = get_attr[target=rnn.weight_hh_l0]
    %rnn_bias_ih_l0 : [num_users=1] = get_attr[target=rnn.bias_ih_l0]
    %rnn_bias_hh_l0 : [num_users=40] = get_attr[target=rnn.bias_hh_l0]
    %arg4_1 : [num_users=1] = placeholder[target=arg4_1]
    %zeros : [num_users=1] = call_function[target=torch.ops.aten.zeros.default](args = ([1, 1, 40],), kwargs = {dtype: torch.float32, device: cuda, pin_memory: False})
    ...
    return (stack,)
```


**Error Trace**
```python
  File "/usr/local/lib/python3.10/dist-packages/torch/_decomp/decompositions.py", line 1421, in addmm
    out = alpha * torch.mm(mat1, mat2)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 893, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 1238, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 963, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 1459, in _dispatch_impl
    return self.wrap_meta_outputs_with_default_device_logic(
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 1589, in wrap_meta_outputs_with_default_device_logic
    return tree_map(wrap, r)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py", line 900, in tree_map
    return treespec.unflatten(map(func, *flat_args))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py", line 736, in unflatten
    leaves = list(leaves)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 1564, in wrap
    ) = FakeTensor._find_common_device(func, flat_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 635, in _find_common_device
    merge_devices(arg)
  File "/usr/local/lib/python3.10/dist-packages/torch/_subclasses/fake_tensor.py", line 630, in merge_devices
    raise RuntimeError(
torch._dynamo.exc.TorchRuntimeError: Failed running call_module L__self___rnn(*(FakeTensor(..., size=(1, 40, 19)),), **{}):
Unhandled FakeTensor Device Propagation for aten.mm.default, found two different devices cpu, cuda:0

from user code:
   File "~/sample.py", line 384, in forward
    _, states = self.rnn(x)
```
