### ISSUE TITLE
Wrong libstdc++ version load in CI when pytorch is built in different kernel version (5.+)

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#121796]
### 🐛 Describe the bug

When migrating workflows to different runners, from our current infrastructure based on kernel 4+ to kernel 5+, Anaconda picks the wrong library to link or load in a few scenarios. The problem seems to have some stochasticity nature, what points to the fact that maybe LD have some non-deterministic behaviour when multiple options to load a library are all equally valid.

The seen error is:
```
+ echo 'We are not in debug mode: linux-jammy-py3.8-gcc11. Expect the assertion to pass'
We are not in debug mode: linux-jammy-py3.8-gcc11. Expect the assertion to pass
+ cd test
+ python -c 'import torch; torch._C._crash_if_debug_asserts_fail(424242)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: /opt/conda/envs/py_3.8/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
```

...or other variants of `GLIBCXX_3.4.30 not found`

to mitigate these issues, on affected environments we currently simply remove the bad library from the file system in multiple places ([example](https://github.com/pytorch/pytorch/pull/119544/commits/8826dd8f112e7b68e6559142d176d367de62800d)).

Other options might be define the library load priority with `LD_LIBRARY_PATH` or even `LD_PRELOAD`. But the ideal situation would be figure out why this is happening and how to properly allow the binary to identify and load the correct glibc.

Finally, there is a question on why glibc is shipped with anaconda, and if there are good reasons for it. And if so, can we always enforce for it to be used so all tests behave equally?

### Versions

main branch

**Comment by bhack** [comment]
Yes, also in my PR https://github.com/pytorch/pytorch/pull/121324
