### ISSUE TITLE
inline_container.cc:424

### ISSUE THREAD

**Issue by PtrMan** [pytorch/pytorch#121833]
### 🐛 Describe the bug

    store model
    store model (snapshot)
    Traceback (most recent call last):
      File "C:\Users\rober\anaconda3\Lib\site-packages\torch\serialization.py", line 619, in save
        _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
      File "C:\Users\rober\anaconda3\Lib\site-packages\torch\serialization.py", line 853, in _save
        zip_file.write_record(name, storage.data_ptr(), num_bytes)
    RuntimeError: [enforce fail at inline_container.cc:593] . PytorchStreamWriter failed writing file data/1: file write failed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\rober\fsRoot\coding\a19ChaosMlExperiments\mlCustom\entry0.py", line 1097, in <module>
        storeModel(netA, f'snapshot it{it} trainLoss{lossStr}')
      File "C:\Users\rober\fsRoot\coding\a19ChaosMlExperiments\mlCustom\entry0.py", line 690, in storeModel
        torch.save(model, f'hopfieldModelA0-last{extraName}.pth')
      File "C:\Users\rober\anaconda3\Lib\site-packages\torch\serialization.py", line 618, in save
        with _open_zipfile_writer(f) as opened_zipfile:
      File "C:\Users\rober\anaconda3\Lib\site-packages\torch\serialization.py", line 466, in __exit__
        self.file_like.write_end_of_file()
    RuntimeError: [enforce fail at inline_container.cc:424] . unexpected pos 1436928 vs 1436784

### Versions

Collecting environment information...
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
Nvidia driver version: 537.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3302
DeviceID=CPU0
Family=198
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3302
Name=11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] numpydoc==1.5.0
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.8.0               hd77b12b_0
[conda] mkl                       2023.1.0         h6b88ed4_46357
[conda] mkl-service               2.4.0           py311h2bbff1b_1
[conda] mkl_fft                   1.3.8           py311h2bbff1b_0
[conda] mkl_random                1.2.4           py311h59b6b97_0
[conda] numpy                     1.24.3          py311hdab7c0b_1
[conda] numpy-base                1.24.3          py311hd01c5d8_1
[conda] numpydoc                  1.5.0           py311haa95532_0
[conda] pytorch                   2.1.0           py3.11_cuda11.8_cudnn8_0    pytorch
[conda] pytorch-cuda              11.8                 h24eeafa_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi

**Comment by malfet** [comment]
Can you please explain in a bit more details how you get into this problem? (I vaguely remember seeing those types of errors frequently  in 1.13 release)

**Comment by PtrMan** [comment]
the program is just storing the model on disk

    def storeModel(model, extraName=''):
        torch.save(model, f'hopfieldModelA0-last{extraName}.pth')



the architecture itself is the following:


    
    # "Hopfield"
    class Hopfield(torch.nn.Module):
        def __init__(self, n, width, beta=0.1):
            super(Hopfield, self).__init__()
            self.beta = beta
    
            self.n = n # number of items
            self.width = width # width of a memory item
    
    
            self.Wk = torch.nn.Parameter(torch.rand(self.width, self.n)*(1.0 / (self.width*self.n))*1.0) # key
            self.Wv = torch.nn.Parameter(torch.rand(self.width, self.n)*(1.0 / (self.width*self.n))*0.1) # value
            self.Wq = torch.nn.Parameter(torch.rand(self.n, self.n)*(1.0 / (self.n*self.n))*0.1) # query (is always a square matrix)
    
        # /param R retrieval
        def forward(self, R, Y):
            z0 = self.beta * R
            z0 = z0 @ self.Wq
            z0 = z0 @ transpose2(self.Wk)
            z0 = z0 @ transpose2(Y)
            z0 = torch.nn.functional.softmax(z0, dim=-1)  # Apply softmax
    
            z0 = z0 @ Y
            z = z0 @ self.Wv
            return z

<br />

    import math
    
    # hopfield based LM NN
    class ModelA(torch.nn.Module):
        def __init__(self):
            super(ModelA, self).__init__()
    
            xWidth = tokenSliceGen.ctxLen*22
    
            
            self.nUnitsHopfield = 6
            self.widthHopfield = 9
            hopfieldBeta = 1.0/math.sqrt(self.nUnitsHopfield)
            self.hopfieldA = Hopfield(self.nUnitsHopfield, self.widthHopfield, hopfieldBeta)
    
    
            self.encoderForHopfieldAForR = LeakyReLUMlp(xWidth, 20, self.nUnitsHopfield*self.widthHopfield)
            self.encoderForHopfieldAForY = LeakyReLUMlp(xWidth, 20, self.nUnitsHopfield*self.widthHopfield)
    
    
            matrixWidth5 = xWidth + self.hopfieldA.n*self.hopfieldA.width
            self.outLinearTransformWeights = torch.nn.Parameter(torch.rand(matrixWidth5, xWidth)*(1.0 / (matrixWidth5*xWidth))*0.1)
    
            # TODO
            #midWidth = 140
            #self.outLinearTransformWeightsA = torch.nn.Parameter(torch.rand(matrixWidth5, midWidth)*(1.0 / (matrixWidth5*midWidth))*0.1)
            #self.outLinearTransformWeightsB = torch.nn.Parameter(torch.rand(midWidth, xWidth)*(1.0 / (midWidth*xWidth))*0.1)
    
            
    
            #matrixWidth5 = self.hopfieldA.n*self.hopfieldA.width
            matrixWidth5 = xWidth
            nUnits5 = 63000 # is the size of the output vector
            self.logitHeadWeights = torch.nn.Parameter(torch.rand(matrixWidth5, nUnits5)*(1.0 / (matrixWidth5*nUnits5))*0.1)
    
        def forward(self, x):#, R, Y):
    
            #print(x) # DBG
    
            R = self.encoderForHopfieldAForR.forward(x)
            #print(R)
            R = R.reshape(self.widthHopfield, self.nUnitsHopfield)
    
            Y = self.encoderForHopfieldAForR.forward(x)
            #print(R)
            Y = Y.reshape(self.hopfieldA.n, self.hopfieldA.width)
    
            hopfieldResA = self.hopfieldA.forward(R, Y)
    
            hopfieldResAFlattened = torch.flatten(hopfieldResA)
    
            # merge crossbar with output from NN of this layer
            z0 = torch.cat([x, hopfieldResAFlattened])
    
            # transform so that output of this module has dimensions like "x"
            z0 = z0 @ self.outLinearTransformWeights
    
            #z0 = z0 @ self.outLinearTransformWeightsA
            #z0 = z0 @ self.outLinearTransformWeightsB
            
    
    
    
    
            
    
            logithead2Matrix = self.logitHeadWeights # transpose2(self.logitHeadWeights)
    
            #print(hopfieldResAFlattened.size())
            #print(logithead2Matrix.size())
            
            #z0 = hopfieldResAFlattened @ logithead2Matrix
            z0 = z0 @ logithead2Matrix
    
            return z0
    
    
    
    
    
    
This is the first time I saw the error on my machine after storing a model with a different architecture which didn't have submodules nested 2 levels deep (or something like that).
    
 ex:


    class NetA(torch.nn.Module):
        def __init__(self):
            super(NetA, self).__init__()
            # define sub-modules
    
            self.hopfieldLayerN = 600 #100 # number of items in memory
            self.hopfieldLayerWidth = 50 # width of one vector in memory
    
            #beta = 12.0
            #beta = 0.1 # blur somewhat (?)
    
            betaA = 3.0
            betaB = 10.0
    
    
            # MLP to translate 1d matrix input to internal matrix
            self.mlp0_moduleA = LeakyReLUMlp(tokenSliceGen.ctxLen*22, 70, self.hopfieldLayerN*self.hopfieldLayerWidth, 0.05)        
            self.sub_module1A = HopfieldLayer(self.hopfieldLayerN, self.hopfieldLayerWidth, betaA)
    
            self.mlp0_moduleB = LeakyReLUMlp(tokenSliceGen.ctxLen*22, 70, self.hopfieldLayerN*self.hopfieldLayerWidth, 0.05)
            self.sub_module1B = HopfieldLayer(self.hopfieldLayerN, self.hopfieldLayerWidth, betaB)
    
            #self.output_module = LeakyReLUMlp(self.hopfieldLayerN*self.hopfieldLayerWidth * (2) + ( tokenSliceGen.ctxLen*22 ), 120, 63000, 0.05) # MLP to translate internal matrix to 1d matrix
            
            # linear should be easier and faster to train
            self.output_module = Linear2(self.hopfieldLayerN*self.hopfieldLayerWidth * (2) + ( tokenSliceGen.ctxLen*22 ), 120, 63000) # linear to translate internal matrix to 1d matrix
            
            #self.output_module = LinearLayer(50*32 * (2) + ( tokenSliceGen.ctxLen*22 ), 63000) # linear layer to translate internal vector to logits
    
        def forward(self, x):
            output0A = self.mlp0_moduleA(x)
            output0A = torch.nn.functional.layer_norm(output0A, output0A.size()) # layer normalization
    
            z0 = output0A.reshape(self.hopfieldLayerWidth, self.hopfieldLayerN)
            output1A = self.sub_module1A(z0)
            output1A = z0 + output1A # skip connection to make learning easier
            #output1A = torch.nn.functional.layer_norm(output1A, output1A.size()) # layer normalization
    
    
            output0B = self.mlp0_moduleB(x)
            output0B = torch.nn.functional.layer_norm(output0B, output0B.size()) # layer normalization
    
            z0 = output0B.reshape(self.hopfieldLayerWidth, self.hopfieldLayerN)
            output1B = self.sub_module1B(z0)
            output1B = z0 + output1B # skip connection to make learning easier
            #output1B = torch.nn.functional.layer_norm(output1B, output1B.size()) # layer normalization
    
    
            output1AFlattened = torch.flatten(output1A)
            output1BFlattened = torch.flatten(output1B)
    
            output1 = torch.cat([output1AFlattened, output1BFlattened,   x])
    
            output2 = self.output_module(output1)
            
            # Combine outputs as needed (e.g., concatenation, summation)
            #combined_output = torch.cat((output1, output2), dim=1)  # Concatenate outputs along dimension 1
            #return combined_output
    
            return output2
    
I never saw this crash with "NetA" after maybe 1000 stores of models ... I hope this helps narrowing down this bug.

**Comment by alinpahontu2912** [comment]
Hey @PtrMan, have you tried running with the latest stable release, is it still happening ?

**Comment by alinpahontu2912** [comment]
I am closing this issue due to lack of activity, feel free to open a new one if needed.
