### ISSUE TITLE
[Feature Request] Support Cythonized Classes (cython_function_or_method) for torch.export.export()

### ISSUE THREAD

**Issue by mtk-tl** [pytorch/pytorch#122078]
### 🚀 The feature, motivation and pitch

**Motivation**
Users might want to hide their torch model implementation from the public due to legal/proprietary reasons. Hence, it would be great if you could support cythonized functions/methods.

**Reproducible Example**

- **Environment**

```
python                    3.8x or 3.9x
executorch                0.1.0
torch                     2.3.0.dev20240229+cpu
torchaudio                2.2.0.dev20240229+cpu
torchsr                   1.0.4
torchvision               0.18.0.dev20240229+cpu

```

- **Scripts**

1. simple_model.py
```
import torch

class SimpleModel(torch.nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.linear = torch.nn.Linear(in_feat, out_feat)

    def forward(self, x):
        out = self.linear(x)
        return out
```
2. setup.py
```
from setuptools import setup
from Cython.Build import cythonize

setup(name='test', ext_modules=cythonize('simple_model.py'))
```
3. export_cython.py
```
from simple_model import SimpleModel
import torch
from torch.export import export

def main():

    model = SimpleModel(2, 4)
    example_inputs = (torch.rand(4,2),)
    export(model, example_inputs)

if __name__ == '__main__':
    main()
```

- **Commands**

```
python setup.py build_ext --inplace
python export_cython.py
```

**Full Error Stacktrace**
```
Traceback (most recent call last):
  File "export_cython.py", line 12, in <module>
    main()
  File "export_cython.py", line 9, in main
    export(model, example_inputs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/export/__init__.py", line 186, in export
    return _export(
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/export/_trace.py", line 599, in wrapper
    raise e
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/export/_trace.py", line 585, in wrapper
    ep = fn(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/export/exported_program.py", line 83, in wrapper
    return fn(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/export/_trace.py", line 845, in _export
    gm_torch_level = _export_to_torch_ir(
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/export/_trace.py", line 346, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 1296, in inner
    result_traced = opt_f(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 437, in _fn
    return fn(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 919, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File ".../anaconda3/envs/.../lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 675, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 534, in compile_inner
    out_code = transform_code_object(code, transform)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 499, in transform
    tracer.run()
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2175, in run
    super().run()
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 831, in run
    and self.step()
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 794, in step
    getattr(self, inst.opname)(inst)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1286, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 695, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/variables/nn_module.py", line 336, in call_function
    return tx.inline_user_function_return(
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 701, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2311, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2425, in inline_call_
    tracer.run()
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 831, in run
    and self.step()
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 794, in step
    getattr(self, inst.opname)(inst)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1337, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 697, in call_function
    result = handler(tx, *args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 1259, in call_getattr
    return obj.var_getattr(tx, name)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/variables/nn_module.py", line 240, in var_getattr
    unimplemented(f"class property {typestr(base)} {typestr(subobj)}")
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/exc.py", line 190, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: class property SimpleModel cython_function_or_method

from user code:
   File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File ".../anaconda3/envs/.../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1530, in _call_impl
    forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.forward)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ezyang** [comment]
We need access to the bytecode to be able to trace the model. Not gonna happen.
