### ISSUE TITLE
test_tp_random_state is broken (fails with IndexError or ValueError)

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#122184]
### 🐛 Describe the bug

The test test/distributed/tensor/parallel/test_tp_random_state.py always fails since at least #105614 (hence Ccing @wnchaol & @fduwjj) at https://github.com/pytorch/pytorch/blob/81683380633f3c79cbf0debc0d491612b152f202/test/distributed/tensor/parallel/test_tp_random_state.py#L101-L105

The reason is the `group=(_1d_mesh, 1)` argument where an index of "1" into a 1D-Mesh is seemingly invalid and leads to:
```

Traceback (most recent call last):
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/testing/_internal/common_distributed.py", line 649, in run_test
    getattr(self, test_name)()
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/testing/_internal/common_distributed.py", line 535, in wrapper
    fn()
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/testing/_internal/common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 153, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/testing/_internal/common_distributed.py", line 174, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/h3/s3248973/git/pytorch/test/distributed/tensor/parallel/test_tp_random_state.py", line 101, in test_model_init
    tensor_gather = funcol.all_gather_tensor(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/distributed/_functional_collectives.py", line 190, in all_gather_tensor
    tag, rankset, group_size = _expand_group(group, tag)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.11/site-packages/torch/distributed/_functional_collectives.py", line 507, in _expand_group
    tag, rankset = dmesh._dim_group_infos[dim]
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
```

The `dim` index that is causing the Error is the "1" from the `group` argument and `dmesh._dim_group_infos=[('ptd:2', [1, 3])]` or `[('ptd:1', [0, 2])]` (depending on the rank)

Furthermore after 08460f4baeb9257a466935f56362c6ebff8cbdd5 the `parallelize_module` call at https://github.com/pytorch/pytorch/blob/81683380633f3c79cbf0debc0d491612b152f202/test/distributed/tensor/parallel/test_tp_random_state.py#L50 will cause a `ValueError` being thrown at https://github.com/pytorch/pytorch/blob/81683380633f3c79cbf0debc0d491612b152f202/torch/distributed/tensor/parallel/_utils.py#L43-L45 because the device mesh has 2 dims, see https://github.com/pytorch/pytorch/blob/81683380633f3c79cbf0debc0d491612b152f202/test/distributed/tensor/parallel/test_tp_random_state.py#L41-L42

### Versions

It is broken since at least PyTorch 2.1.0 (see #105614) and still (and even more) in current main and latest release (2.3.0-rc2)

Any other version information is irrelevant.

The test is skipped if there are less than 4 GPUs, so the machine needs to have at least 4 GPUs (we have 8)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

**Comment by XilunWu** [comment]
@Flamefire thx for the error report!! #122248 is the fix PR. Comments are welcome.
