### ISSUE TITLE
Bug: `torch.compile` fails to trace jvp with raw python numbers.

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#122197]
### 🐛 Describe the bug

`torch.compile` fails to compile jvp transformation with native python numbers. Many tests ignored on `dynamo_expected_fail` fails for this same reason.

```python
import torch
torch._dynamo.config.capture_func_transforms = True
jvp = torch.func.jvp


def f(x, y, z):
    a, b = x
    return a + 2 * b + 3 * y + 4 * z

@torch.compile(backend='aot_eager', fullgraph=True)
def fn(x):
    return jvp(f, ((x, x,), x, x), ((x, x), x, x))


x = torch.tensor(1.,)
y = fn(x)
print(y)
```

```python
Traceback (most recent call last):
  File "/home/guilhermeleobas/git/pytorch/a.py", line 24, in <module>
    y = fn(x)
        ^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/eval_frame.py", line 450, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 923, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/home/guilhermeleobas/micromamba/envs/pytorch/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2150, in run
    super().run()
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 1802, in CALL
    self.call_function(fn, args, kwargs)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 674, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2400, in inline_call_
    tracer.run()
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 1802, in CALL
    self.call_function(fn, args, kwargs)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 674, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2400, in inline_call_
    tracer.run()
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 1260, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 674, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2400, in inline_call_
    tracer.run()
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 1260, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 674, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2400, in inline_call_
    tracer.run()
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 1764, in BINARY_OP
    return getattr(self, "BINARY_" + opname)(inst)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 242, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/builtin.py", line 641, in call_function
    return wrap_fx_proxy(tx, proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/builder.py", line 1338, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/variables/builder.py", line 1423, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 1732, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 1667, in get_fake_value
    ret_val = wrap_fake_exception(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 1198, in wrap_fake_exception
    return fn()
           ^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 1668, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 1800, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/utils.py", line 1782, in run_node
    return node.target(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_subclasses/fake_tensor.py", line 893, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_subclasses/fake_tensor.py", line 1238, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_subclasses/fake_tensor.py", line 963, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_subclasses/fake_tensor.py", line 1455, in _dispatch_impl
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/git/pytorch/torch/_ops.py", line 600, in __call__
    return self_._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function mul>(*(2, GradTrackingTensor(lvl=1, value=
    FakeTensor(..., size=())
)), **{}):
aten::alias() Expected a value of type 'Tensor' for argument 'self' but instead found type 'int'.
Position: 0
Value: 2
Declaration: aten::alias(Tensor(a) self) -> Tensor(a)
Cast error details: Unable to cast 2 to Tensor

from user code:
   File "/home/guilhermeleobas/git/pytorch/a.py", line 20, in fn
    return jvp(f, ((x, x,), x, x), ((x, x), x, x))
  File "/home/guilhermeleobas/git/pytorch/torch/_functorch/eager_transforms.py", line 985, in jvp
    return _jvp_with_argnums(func, primals, tangents, argnums=None, strict=strict, has_aux=has_aux)
  File "/home/guilhermeleobas/git/pytorch/torch/_functorch/vmap.py", line 47, in fn
    return f(*args, **kwargs)
  File "/home/guilhermeleobas/git/pytorch/torch/_functorch/eager_transforms.py", line 1031, in _jvp_with_argnums
    result_duals = func(*duals)
  File "/home/guilhermeleobas/git/pytorch/a.py", line 16, in f
    return a + 2 * b + 3 * y + 4 * z

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by guilhermeleobas** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/124774
