### ISSUE TITLE
[inductor][cpu] pyhpc_equation_of_state fp32 static shape default/cpp wrapper multiple thread performance  test crashed

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#122283]
### 🐛 Describe the bug

new_failures in 2024-03-11
| suite | name | accuracy | perf | reason(reference only)
-- | -- | -- | -- | --
torchbench | pyhpc_equation_of_state | √ | NaN | pyhpc_equation_of_state, torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised: AssertionError: ((41616, 26), (1082016,))

### Versions

SW info
| name | target_branch | target_commit | refer_branch | refer_commit
-- | -- | -- | -- | --
torchbench | main | d6015d42 | main | 1ef0a39e
torch | main | 9f235971f02e0d53038f5bcef9b7018be2ac8c6d | main | f11f2b0d55b1aa322f73f4bb521beaf9d4563603
torchvision | main | 0.18.0a0+2c127da | main | 0.18.0a0+2c127da
torchtext | main | 0.16.0a0+b0ebddc | main | 0.16.0a0+b0ebddc
torchaudio | main | 2.2.0a0+87aeb55 | main | 2.2.0a0+87aeb55
torchdata | main | 0.7.1a0+0790338 | main | 0.7.1a0+0790338
dynamo_benchmarks | main | nightly | main | nightly

Error:
```
loading model: 0it [00:00, ?it/s]cpu  eval  pyhpc_equation_of_state            

ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2634, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 437, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 964, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1161, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1234, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1215, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/backends/inductor.py", line 16, in inductor
    return compile_fx(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1373, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1108, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 463, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 738, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1296, in compile_to_fn
    return self.compile_to_module().call
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1239, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1196, in codegen
    self.scheduler = Scheduler(self.buffers)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 1309, in __init__
    self.fuse_nodes()
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 1683, in fuse_nodes
    self.fuse_nodes_once()
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 1822, in fuse_nodes_once
    node3 = self.get_backend(device).fuse(node1, node2)
  File "/workspace/pytorch/torch/_inductor/codegen/cpp.py", line 3531, in fuse
    assert vars1 == vars2, (vars1, vars2)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: ((41616, 26), (1082016,))

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

0
```

Repro:
[inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
```shell
bash inductor_single_test.sh single inference performance torchbench pyhpc_equation_of_state float32 first static default 0
```

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/49d1fd31cf5424899fdbb73654d95bf3478c0bae

log: 
[torchbench-pyhpc_equation_of_state-inference-float32-static-default-multiple-performance-crash_guilty_commit.log.txt](https://github.com/pytorch/pytorch/files/14663904/torchbench-pyhpc_equation_of_state-inference-float32-static-default-multiple-performance-crash_guilty_commit.log.txt)

cc @zxd1997066  @WeizhuoZhang-intel @chuanqi129 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by chuanqi129** [comment]
Hi @vfdev-5, by bisect search, seems the PR #120077 introduced this issue, could you please help to double check it?

**Comment by vfdev-5** [comment]
@chuanqi129 thanks for pinging! Could you please provide repro command from your scripts?
I could get the following command from your description:
```
python benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --no-skip --dashboard --batch-size 1 --threads 1 --only pyhpc_equation_of_state   --inference   --freezing  --timeout 9000 --backend=inductor  --output=/tmp/inductor_single_test_st.csv
```
and this does not fail with above message:
```
loading model: 0it [00:00, ?it/s]
cpu  eval  pyhpc_equation_of_state            
skipping cudagraphs due to skipping cudagraphs due to cpu device. Found from : 
   File "benchmarks/dynamo/torchbench.py", line 370, in forward_pass
    return mod(*inputs)
  File "/pytorch/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/pth/benchmark/torchbenchmark/models/pyhpc_equation_of_state/__init__.py", line 28, in forward
    return eos_pytorch.gsw_dHdT(s, t, p)
  File "/tmp/pth/benchmark/torchbenchmark/models/pyhpc_equation_of_state/eos_pytorch.py", line 72, in gsw_dHdT
    t3 = v46 * sa

running benchmark: 100%|███████████████████████████| 50/50 [00:00<00:00, 646.64it/s]
19.972x
```
Thanks

**Comment by chuanqi129** [comment]
Hi @vfdev-5 , I have double checked the repro cmd in the issue descripts, it's a multiple thread crash case, not single thread mode. So the right reproduce is:
`python benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --no-skip --dashboard  --only pyhpc_equation_of_state   --inference   --freezing  --timeout 9000 --backend=inductor  --output=/tmp/inductor_single_test_st.csv` 
or use [inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
`bash inductor_single_run.sh multiple inference performance torchbench pyhpc_equation_of_state float32 first static default 0`

**Comment by vfdev-5** [comment]
Thanks @chuanqi129 !
I could finally reproduce the bug as well just taking the model and running torch.compile on it. Your repro script also shows the error, thanks!
