### ISSUE TITLE
[Inductor][Triton] test_mixed_mm2_cuda fails on Hopper

### ISSUE THREAD

**Issue by Aidyn-A** [pytorch/pytorch#122227]
### 🐛 Describe the bug

We are seeing some segfault failures on Hopper GPUs on all Triton 3.0.0 versions:

`pytorch_triton-3.0.0+989adb9a29`:
```python
python test/inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
test_mixed_mm2_cuda (__main__.GPUTests) ... python: /source/llvm-project/mlir/lib/IR/TypeRange.cpp:20: mlir::TypeRange::TypeRange(ArrayRef<mlir::Type>): Assertion `llvm::all_of(types, [](Type t) { return t; }) && "attempting to construct a TypeRange with null types"' failed.
```

`pytorch_triton-3.0.0+a9bc1a3647`:
https://download.pytorch.org/whl/nightly/pytorch_triton-3.0.0%2Ba9bc1a3647-cp310-cp310-linux_x86_64.whl
```python
python test/inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
test_mixed_mm2_cuda (__main__.GPUTests) ... [d8aa2091f3fe:962  :0:962] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
```

`pytorch_triton-3.0.0+901819d2b6`
```python
python test/inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
test_mixed_mm2_cuda (__main__.GPUTests) ... [d8aa2091f3fe:1275 :0:1275] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7f745aeec067)
```

### Versions

PyTorch version: 2.4.0a0+git0d845f7
NVIDIA H100 80GB

**Comment by Aidyn-A** [comment]
Small repro:
```Python
import torch
import torch._inductor.config
torch._inductor.config.force_mixed_mm = True

def fn(a, b, scale, bias):
    return torch.mm(a, b.to(a.dtype)) * scale + bias

fnc = torch.compile(fn)
device=torch.device("cuda")
y = fnc(
        torch.randn(8, 8, device=device),
        torch.randint(-128, 127, (8, 8), dtype=torch.int8, device=device),
        torch.randn(8, device=device),
        torch.randn(8, device=device),
    )
```
It works fine if `torch._inductor.config.force_mixed_mm = False`.

**Comment by jansel** [comment]
@bertmaher @htyu @manman-ren this looks like it might be a Triton bug.  Would someone on your team want to take a look at this?

It seems H100 specific as it doesn't repro on a RTX 3090.

**Comment by htyu** [comment]
I can take a look.

**Comment by jansel** [comment]
Thanks!

**Comment by htyu** [comment]
I was unable to repro this with the following command on H100:

```
$ pip list | grep torch
torch                    2.4.0a0+git0d845f7 /home/hoy/pytorch
$ pip list | grep triton
triton                   3.0.0              /home/hoy/triton/python
$ python test/inductor/test_torchinductor.py -v -k test_mixed_mm2_cuda
OK

```
Triton was at 989adb9a29496c22a36ef82ca69cad5dad536b9c or latest. Running the small repo file didn't trigger the issue either.  Can you please check what I was missing?

BTW, the test is mm related, on if it only repros on H100, it's probably related to the use WGMMA instructions.

**Comment by Aidyn-A** [comment]
I re-ran it with the latest nightly and still getting a failure.
```
root@1997ebd64bf2:/workspace# python /tmp/torchinductor_root/vz/cvzt5xdurznoze3lbldx5jlh3ekub242yklwo5nn2qanxjph32oq.py
python: /source/llvm-project/mlir/lib/IR/TypeRange.cpp:20: mlir::TypeRange::TypeRange(ArrayRef<mlir::Type>): Assertion `llvm::all_of(types, [](Type t) { return t; }) && "attempting to construct a TypeRange with null types"' failed.
Traceback (most recent call last):
  File "/tmp/torchinductor_root/vz/cvzt5xdurznoze3lbldx5jlh3ekub242yklwo5nn2qanxjph32oq.py", line 132, in <module>
    async_compile.wait(globals())
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2757, in wait
    scope[key] = result.result()
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2564, in result
    self.future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
Here is the code that was generated by the Inductor:
- [cvzt5xdurznoze3lbldx5jlh3ekub242yklwo5nn2qanxjph32oq.py.txt](https://github.com/pytorch/pytorch/files/14746831/cvzt5xdurznoze3lbldx5jlh3ekub242yklwo5nn2qanxjph32oq.py.txt)

Hope it will make easier to reproduce.

**Comment by jansel** [comment]
@Aidyn-A are you running the correct version of triton?

You could try:
```
pip3 uninstall -y triton && pip install -U pytorch-triton==3.0.0+989adb9a29
```

**Comment by htyu** [comment]
> Here is the code that was generated by the Inductor:
> 
> * [cvzt5xdurznoze3lbldx5jlh3ekub242yklwo5nn2qanxjph32oq.py.txt](https://github.com/pytorch/pytorch/files/14746831/cvzt5xdurznoze3lbldx5jlh3ekub242yklwo5nn2qanxjph32oq.py.txt)

Thanks for the repro! I can repro the failure now.

**Comment by Aidyn-A** [comment]
@jansel, yep that is exactly what I was doing.
In addition to H100, I am seeing the same failure on 3080, while it is working fine on A100.

**Comment by htyu** [comment]
Same triton issue filed previously https://github.com/openai/triton/issues/2853 . I'm working on a fix.

**Comment by cpuhrsch** [comment]
cc @HDCharles @alexsamardzic FYI

**Comment by IvanKobzarev** [comment]
Hi @htyu , doing issue scrapping, is this issue still relevant, are you working on it?

**Comment by htyu** [comment]
> Hi @htyu , doing issue scrapping, is this issue still relevant, are you working on it?

Sorry, it's put on hold. I'm not on it now.

**Comment by jansel** [comment]
My agent was unable to reproduce this on da74fecc24c85f9694061e961858303c44be4338. Reopen if you see this on the latest PyTorch nightly
