### ISSUE TITLE
Batch size and sequence length can't be varied if you export a transformer to onnx

### ISSUE THREAD

**Issue by DavidMinorNV** [pytorch/pytorch#122321]
### 🐛 Describe the bug

I've been making a lot of tickets about differentiating through things lately, but here's a much more basic one: if I export a transformer to on onnx, without even running any backprop stuff, the onnx appears to be broken if I try to run it with different batch sizes and sequence lengths. Execute this code to reproduce the issue:

```
import torch
import onnxruntime as ort


class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.latent_dim = 256
        self.num_heads = 4
        self.ff_size=1024
        self.dropout=0.1
        self.activation="gelu"
        self.num_layers = 4

        root_seqTransEncoderLayer = torch.nn.TransformerEncoderLayer(d_model=self.latent_dim,
                                                               nhead=self.num_heads,
                                                               dim_feedforward=self.ff_size,
                                                               dropout=self.dropout,
                                                               activation=self.activation)

        self.root_seqTransEncoder = torch.nn.TransformerEncoder(root_seqTransEncoderLayer,
                                                          num_layers=self.num_layers)
        
    def forward(self, inputs):
        return self.root_seqTransEncoder(inputs[0])


batch_size=20
seq_len=2

mdl = Model()
for p in mdl.parameters():
    p.requires_grad_(False)


print("export model")
torch.onnx.export(
    Model(),
    [torch.randn([batch_size, seq_len, 256])],
    "modelthing.onnx",
    dynamic_axes={'xseq': {0: 'batch_size', 1:'seq_len'}},
    input_names=["xseq"],
    opset_version=17,
    output_names=["lossgrad"],
    verbose=True
)

# load and evaluate with a different shape:
ort_session = ort.InferenceSession("modelthing.onnx")

print("run onnx with export shape")
ort_session.run(None, { "xseq":torch.randn([batch_size, seq_len, 256]).numpy() })
print("success")

batch_size=10
seq_len=5
print("run onnx with different batch size")
ort_session.run(None, { "xseq":torch.randn([batch_size, seq_len, 256]).numpy() })
print("success")
```

Here's the error I get:

```
2024-03-20 09:27:48.2454180 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/root_seqTransEncoder/layers.0/self_attn/Reshape_4' Status Message: C:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{10,5,256}, requested shape:{20,20,64}

Traceback (most recent call last):
  File "C:\Git\physdiff\dynamicshapesbroken.py", line 63, in <module>
    ort_session.run(None, { "xseq":torch.randn([batch_size, seq_len, 256]).numpy() })
  File "C:\Users\dminor\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/root_seqTransEncoder/layers.0/self_attn/Reshape_4' Status Message: C:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{10,5,256}, requested shape:{20,20,64}
```

I don't know if this works better with the dynamo export, but that's not currently an option for me as I can mostly differentiate through things with torch.onnx.export() now and it's completely unsupported in dynamo.

### Versions

PyTorch version: 2.2.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 10.0.130
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090 Ti
Nvidia driver version: 536.23
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3501
DeviceID=CPU0
Family=107
L2CacheSize=16384
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3501
Name=AMD Ryzen Threadripper PRO 3975WX 32-Cores
ProcessorType=3
Revision=12544

Versions of relevant libraries:
[pip3] functorch==2.0.0
[pip3] lovely-numpy==0.2.8
[pip3] numpy==1.24.3
[pip3] onnx==1.14.1
[pip3] onnx-graphsurgeon==0.3.27
[pip3] onnxconverter-common==1.13.0
[pip3] onnxruntime==1.15.1
[pip3] optree==0.10.0
[pip3] pytorch-lightning==1.4.2
[pip3] tf2onnx==1.16.0
[pip3] torch==2.2.1+cu118
[pip3] torch-cluster==1.6.1
[pip3] torch-fidelity==0.3.0
[pip3] torch-geometric==2.3.0
[pip3] torch-scatter==2.1.1
[pip3] torch-sparse==0.6.17
[pip3] torch-spline-conv==1.2.2
[pip3] torchaudio==2.2.1+cu118
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.17.1+cu118
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.6.0 hc0ea762_10 conda-forge
[conda] libblas 3.9.0 16_win64_mkl conda-forge
[conda] libcblas 3.9.0 16_win64_mkl conda-forge
[conda] liblapack 3.9.0 16_win64_mkl conda-forge
[conda] mkl 2022.1.0 h6a75c08_874 conda-forge
[conda] mkl-include 2023.2.0 intel_49496 intel
[conda] mkl-static 2023.2.0 intel_49496 intel
[conda] numpy 1.24.2 py310hd02465a_0 conda-forge
[conda] pytorch 1.12.0 py3.10_cuda11.6_cudnn8_0 pytorch
[conda] pytorch-mutex 1.0 cuda pytorch

**Comment by DavidMinorNV** [comment]
Update: looks like it's just the batch size I can't vary. Seems to be related to the reshape operations on q, k and v in the multi_head_attention_forward function (torch/nn/functional.py) so I narrowed the test down a bit

**Comment by DavidMinorNV** [comment]
Actually I can juggle things around in torch/nn/functional.py and make this work - here are my diffs:

```
diff --git a/torch/nn/functional.py b/torch/nn/functional.py
index 707fc04f7e7..735a6ef16b4 100644
--- a/torch/nn/functional.py
+++ b/torch/nn/functional.py
@@ -5377,9 +5377,9 @@ def multi_head_attention_forward(
     #
     # reshape q, k, v for multihead attention and make em batch first
     #
-    q = q.view(tgt_len, bsz * num_heads, head_dim).transpose(0, 1)
+    q = q.view(q.shape[0], -1, head_dim).transpose(0, 1)
     if static_k is None:
-        k = k.view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
+        k = k.view(k.shape[0], -1, head_dim).transpose(0, 1)
     else:
         # TODO finish disentangling control flow so we don't do in-projections when statics are passed
         assert static_k.size(0) == bsz * num_heads, \
@@ -5388,7 +5388,7 @@ def multi_head_attention_forward(
             f"expecting static_k.size(2) of {head_dim}, but got {static_k.size(2)}"
         k = static_k
     if static_v is None:
-        v = v.view(v.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
+        v = v.view(v.shape[0], -1, head_dim).transpose(0, 1)
     else:
         # TODO finish disentangling control flow so we don't do in-projections when statics are passed
         assert static_v.size(0) == bsz * num_heads, \
@@ -5469,9 +5469,9 @@ def multi_head_attention_forward(
             else:
                 attn_mask = attn_mask.view(bsz, num_heads, -1, src_len)

-        q = q.view(bsz, num_heads, tgt_len, head_dim)
-        k = k.view(bsz, num_heads, src_len, head_dim)
-        v = v.view(bsz, num_heads, src_len, head_dim)
+        q = q.view(bsz, num_heads, -1, head_dim)
+        k = k.view(bsz, num_heads, -1, head_dim)
+        v = v.view(bsz, num_heads, -1, head_dim)

         attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
         attn_output = attn_output.permute(2, 0, 1, 3).contiguous().view(bsz * tgt_len, embed_dim)
```

**Comment by rchuzh99** [comment]
Hi maintainers,

I am encountering an issue while inferencing with the exported ONNX SegFormer model from MMSegmentation.

To export the model to ONNX, I used the `onnx_export` function from MMDeploy (`from mmdeploy.apis.onnx import export as onnx_export`). However, I am facing an error with the following layer: `backbone/layers.0.1.0/attn/attn/Reshape_4`, which uses `nn.MultiheadAttention` from PyTorch.

Here is the error log:

<details><summary>Error Log</summary>
<p>
<code>
Name: 'main//backbone/layers.0.1.0/attn/attn/Reshape_4'  
Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{187,1,32}, requested shape:{160,1,32}
</code>
</p>
</details> 

I have referred to the following code segment in PyTorch:

https://github.com/pytorch/pytorch/blob/54f27b886e9dccebb2ebd07300c309bba3b3b30c/torch/nn/functional.py#L6129-L6154

and I have added the revision as mentioned in https://github.com/pytorch/pytorch/issues/122321#issuecomment-2010340209 
```python
q = q.view(tgt_len, bsz * num_heads, head_dim).transpose(0, 1)

if static_k is None:
    - k = k.view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
    + k = k.view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
else:
    assert static_k.size(0) == bsz * num_heads, \
        f"expecting static_k.size(0) of {bsz * num_heads}, but got {static_k.size(0)}"
    assert static_k.size(2) == head_dim, \
        f"expecting static_k.size(2) of {head_dim}, but got {static_k.size(2)}"
    k = static_k
if static_v is None:
    - v = v.view(v.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
    + v = v.view(v.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
else:
    assert static_v.size(0) == bsz * num_heads, \
        f"expecting static_v.size(0) of {bsz * num_heads}, but got {static_v.size(0)}"
    assert static_v.size(2) == head_dim, \
        f"expecting static_v.size(2) of {head_dim}, but got {static_v.size(2)}"
    v = static_v
```

Prior to writing this issue, I have attempted several methods to resolve it, particularly focusing on exporting the `nn.MultiheadAttention` module:

1. **Scripting the module and then exporting to ONNX** (`torch.jit.script` -> `torch.onnx.export`):
    - Resulted in `RuntimeError: ScalarType UNKNOWN_SCALAR is an unexpected tensor scalar type`

2. **Torch Dynamo Export**:
    - Resulted in the error `Currently does not support non-function and super`

Could you please provide guidance on how to resolve this issue or suggest alternative methods for correctly exporting the model?

Thank you for your assistance.

cc @soumith @gchanan @dzhulgakov @ezyang @malfet
