### ISSUE TITLE
Segmentation fault about torch::nn::Conv2d in `libtorch2.0.1+cuda11.8`

### ISSUE THREAD

**Issue by meng152634** [pytorch/pytorch#122308]
### 🐛 Describe the bug

I got a segmentation fault when executing `Conv2d` using `Libtorch2.0.1+cuda11.8` version, but the version `Libtorch2.0.0+cuda11.8` is work. So, I think this may be a bug in `Libtorch2.0.1+cuda11.8`, or may be I have some errors when using Libtorch. The follow is the `C++` test code and `CMakeList.txt` file.

- C++ code:

```cpp
#include<torch/torch.h>
#include<iostream>
#include <opencv2/opencv.hpp>

struct TestCNN : torch::nn::Module {
    TestCNN() {
        conv1a = register_module("conv1a", torch::nn::Conv2d(torch::nn::Conv2dOptions(1, 64, 3).stride(1).padding(1)));
        conv1b = register_module("conv1b", torch::nn::Conv2d(torch::nn::Conv2dOptions(64, 128, 3).stride(1).padding(1)));
        out = register_module("out", torch::nn::Conv2d(torch::nn::Conv2dOptions(128, 1, 3).stride(1).padding(1)));
    }

    torch::Tensor forward(torch::Tensor x) {
        x = torch::relu(conv1a->forward(x));
        x = torch::relu(conv1b->forward(x));
        x = out->forward(x);
        return x;
    }

    torch::nn::Conv2d conv1a{nullptr};
    torch::nn::Conv2d conv1b{nullptr};
    torch::nn::Conv2d out{nullptr};
};

int main(){
    auto device_type = torch::kCUDA;
    auto device = torch::Device(device_type);

    std::string img_path  = "/path/to/image/";
    cv::Mat img = cv::imread(img_path, cv::IMREAD_UNCHANGED);
    cv::Mat gray;
    cv::cvtColor(img, gray, cv::COLOR_BGR2GRAY);

    torch::Tensor inp = torch::from_blob(gray.data, {gray.rows, gray.cols}, torch::kByte);
    inp = inp.unsqueeze(0).unsqueeze(1);
    inp = inp.to(torch::kFloat32);
    inp = inp.div(255.0);

    std::shared_ptr<TestCNN> model = std::make_shared<TestCNN>();
    model->eval();
    model->to(device);

    auto out = model->forward(inp.to(device));

    return 0;
}
```

- CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.10)
project(demo)

set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS}-O0 -Wall -g -ggdb")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")

set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "/path/to/libtorch2.0.1+cuda11.8/")
find_package(Torch REQUIRED)
find_package(OpenCV REQUIRED)

set(CMAKE_CXX_FLAGS "${CAMKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(demo demo.cpp)
target_link_libraries(demo ${TORCH_LIBRARIES} ${OpenCV_LIBS} -pthread)
set_property(TARGET demo PROPERTY CXX_STANDARD 14)
```

When executing `x = torch::relu(conv1a->forward(x));`, I got the following output without any other prompt information.
```shell
Signal: SIGSEGV (Segmentation fault)
```

When I change the `/path/to/libtorch/` into `libtorch2.0.0+cuda11.8` in CMakeLists.txt, it can work well. And more interesting, if I generate a random Tensor instead of reading a image, the same codes also can work well.

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.7
Libc version: glibc-2.31

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 525.116.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              1
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           183
Model name:                      13th Gen Intel(R) Core(TM) i7-13700KF
Stepping:                        1
CPU MHz:                         3400.000
CPU max MHz:                     5400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6835.20
Virtualization:                  VT-x
L1d cache:                       384 KiB
L1i cache:                       256 KiB
L2 cache:                        16 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.24.3          py310h5f9d8c6_1  
[conda] numpy-base                1.24.3          py310hb5e798b_1  
[conda] pytorch                   2.0.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu118    pytorch

**Comment by malfet** [comment]
@meng152634 can you please try running it with debugger attached and post a backtrace here?

And can you please try reproducing this problem using latest version of libtorch (2.2.1 at the time of this writing)

**Comment by meng152634** [comment]
@malfet Thanks for quick reply, and I am so sorry for late reply.

> can you please try running it with debugger attached and post a backtrace here?

I have already run it with debugger and the backtrace information is as follows:

```shell
Thread 1 "demo" received signal SIGSEGV, Segmentation fault.
0x00007ffedfb264a0 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
(gdb) bt
#0  0x00007ffedfb264a0 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007ffedf7a161c in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007ffedf97f04e in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007ffd9789a96b in  () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#4  0x00007ffd978f7cf6 in  () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#5  0x00007ffd953c5cab in  () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#6  0x00007ffd95075d93 in cudnn::cnn::ConvForward4dImplicitGemmEngine<cudnn::cnn::convolve_launch_4d_pf<float, float, float, float, kernel_conv_params>, 5, 2, 2, 2, 2>::execute_internal_impl(cudnn::backend::VariantPack const&, CUstream_st*) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#7  0x00007ffd94b7f545 in cudnn::cnn::EngineInterface::execute(cudnn::backend::VariantPack const&, CUstream_st*) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#8  0x00007ffd94bb7a10 in cudnn::cnn::EngineContainer<(cudnnBackendEngineName_t)28>::execute_internal_impl(cudnn::backend::VariantPack const&, CUstream_st*) ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#9  0x00007ffd94b7f545 in cudnn::cnn::EngineInterface::execute(cudnn::backend::VariantPack const&, CUstream_st*) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#10 0x00007ffd94cdc52e in cudnn::cnn::AutoTransformationExecutor::execute_pipeline(cudnn::cnn::EngineInterface&, cudnn::backend::VariantPack const&, CUstream_st*) const ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#11 0x00007ffd94cdc677 in cudnn::cnn::BatchPartitionExecutor::operator()(cudnn::cnn::EngineInterface&, cudnn::cnn::EngineInterface*, cudnn::backend::VariantPack const&, CUstream_st*) const ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#12 0x00007ffd94cfda5b in cudnn::cnn::GeneralizedConvolutionEngine<cudnn::cnn::EngineContainer<(cudnnBackendEngineName_t)28> >::execute_internal_impl(cudnn::backend::VariantPack const&, CUstream_st*) ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#13 0x00007ffd94b7f545 in cudnn::cnn::EngineInterface::execute(cudnn::backend::VariantPack const&, CUstream_st*) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#14 0x00007ffd94b91ec9 in cudnn::backend::execute(cudnnContext*, cudnn::backend::ExecutionPlan&, cudnn::backend::VariantPack&) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#15 0x00007ffd94b92271 in cudnnBackendExecute () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libcudnn_cnn_infer.so.8
#16 0x00007fff40a90956 in at::native::run_conv_plan(cudnnContext*, at::Tensor const&, at::Tensor const&, at::Tensor const&, cudnn_frontend::ExecutionPlan_v8 const&) ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#17 0x00007fff40a97da4 in at::native::try_configs(std::vector<std::shared_ptr<cudnn_frontend::OpaqueBackendPointer>, std::allocator<std::shared_ptr<cudnn_frontend::OpaqueBackendPointer> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, at::native::(anonymous namespace)::CacheKey const&, cudnnContext*, at::Tensor const&, at::Tensor const&, at::Tensor const&) ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#18 0x00007fff40a985a1 in at::native::run_single_conv(cudnnBackendDescriptorType_t, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#19 0x00007fff40a99795 in at::native::raw_cudnn_convolution_forward_out(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) ()
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#20 0x00007fff40a820ca in at::native::cudnn_convolution_forward(char const*, at::TensorArg const&, at::TensorArg const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) ()
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#21 0x00007fff40a825c5 in at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#22 0x00007fff4264af71 in at::(anonymous namespace)::(anonymous namespace)::wrapper_CUDA__cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#23 0x00007fff4264b00f in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CUDA__cudnn_convolution>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool> >, at::Tensor (at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cuda.so
#24 0x00007fff9851b3ff in at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#25 0x00007fff978265ed in at::native::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#26 0x00007fff988ac6bc in at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd___convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#27 0x00007fff988ac784 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd___convolution>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool> >, at::Tensor (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#28 0x00007fff980b93f5 in at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#29 0x00007fff9781d15f in at::native::convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#30 0x00007fff988ac2a2 in at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#31 0x00007fff988ac322 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__convolution>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long> >, at::Tensor (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#32 0x00007fff980875fe in at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#33 0x00007fff99b4b2ed in torch::autograd::VariableType::(anonymous namespace)::convolution(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#34 0x00007fff99b4bf66 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long), &torch::autograd::VariableType::(anonymous namespace)::convolution>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#35 0x00007fff980b883c in at::_ops::convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#36 0x00007fff978202e4 in at::native::conv2d(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#37 0x00007fff98a74bd2 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__conv2d>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long> >, at::Tensor (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#38 0x00007fff98636991 in at::_ops::conv2d::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#39 0x00007fff9b1cb4e2 in decltype(auto) c10::detail_::visitation::alt::visit_alt<c10::detail_::visitation::variant::value_visitor<torch::nn::functional::detail::conv2d(at::Tensor const&, at::Tensor const&, at::Tensor const&, torch::ExpandingArray<2ul, long>, c10::variant<torch::ExpandingArray<2ul, long>, torch::enumtype::kValid, torch::enumtype::kSame> const&, torch::ExpandingArray<2ul, long>, long)::{lambda(auto:1 const&)#1}>, c10::detail_::impl<torch::ExpandingArray<2ul, long>, torch::enumtype::kValid, torch::enumtype::kSame> const&>(c10::detail_::visitation::variant::value_visitor<torch::nn::functional::detail::conv2d(at::Tensor const&, at::Tensor const&, at::Tensor const&, torch::ExpandingArray<2ul, long>, c10::variant<torch::ExpandingArray<2ul, long>, torch::enumtype::kValid, torch::enumtype::kSame> const&, torch::ExpandingArray<2ul, long>, long)::{lambda(auto:1 const&)#1}>&&, c10::detail_::impl<torch::ExpandingArray<2ul, long>, torch::enumtype::kValid, torch::enumtype::kSame> const&) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#40 0x00007fff9b1c461d in torch::nn::Conv2dImpl::_conv_forward(at::Tensor const&, at::Tensor const&) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#41 0x00007fff9b1c4864 in torch::nn::Conv2dImpl::forward(at::Tensor const&) () at /home/mxb/3rdparty/libtorch201_cuda118/lib/libtorch_cpu.so
#42 0x0000555555561382 in TestCNN::forward(at::Tensor) (this=0x555558957b50, x=...) at /home/mxb/Projects/CLionProjects/test_libtorch/demo.cpp:13
#43 0x000055555555b090 in main() () at /home/mxb/Projects/CLionProjects/test_libtorch/demo.cpp:42

```

> And can you please try reproducing this problem using latest version of libtorch (2.2.1 at the time of this writing)

I tried to reproduce this problem using libtorch 2.2.1+cuda 11.8, but there were many errors during compilation which may be caused by version updates. Listing all the error messages is too long, so I have only listed a few that I believe are fatal errors.

```shell
/home/mxb/3rdparty/libtorch221_cuda118/include/torch/csrc/api/include/torch/nn/modules/conv.h:146:40: error: no matching function for call to ‘torch::nn::detail::ConvNdOptions<3>::padding_mode() const’
  146 |     if (!std::get_if<enumtype::kZeros>(&options.padding_mode())) {

/home/mxb/3rdparty/libtorch221_cuda118/include/torch/csrc/api/include/torch/nn/modules/conv.h:98:40: error: use of deleted function ‘at::Tensor::Tensor()’
   98 |       this->register_parameter("bias", Tensor(), /*requires_grad=*/false);
      |                                        ^~~~~~~~

/home/mxb/3rdparty/libtorch221_cuda118/include/torch/csrc/api/include/torch/nn/cloneable.h:78:60: error: invalid conversion from ‘c10::TensorOptions (*)(c10::Device)’ to ‘int’ [-fpermissive]
   78 |       copy->children_[child.key()]->clone_(*child.value(), device);
      |                                                            ^~~~~~
      |                                                            |
      |                                                            c10::TensorOptions (*)(c10::Device)

/home/mxb/3rdparty/libtorch221_cuda118/include/torch/csrc/api/include/torch/nn/modules/conv.h:315:39: error: no matching function for call to ‘torch::nn::detail::ConvNdOptions<1>::padding() const’
  315 |     return std::get<ExpandingArray<D>>(this->options.padding());
```

I found that these errors seem to be related to the following lines of code:

1. `register_module()`, 

```shell
In template: function 'padding' with deduced return type cannot be used before it is defined error occurred here in instantiation of member function 'torch::nn::ConvOptions<2>::padding' requested here 'padding' declared here
```

2. `inp = inp.to(torch::kFloat32)`, this may be due to changing `c10::ScalarType` to `caffe2::TypeMeta` in `to()` method

```shell
No matching member function for call to 'to' candidate function not viable: requires at least 2 arguments, but 1 was provided
```

3. `model->eval()`, 

```shell
Cannot initialize object parameter of type 'torch::nn::Module' with an expression of type 'std::__shared_ptr_access<TestCNN, __gnu_cxx::_S_atomic>::element_type' (aka 'TestCNN')
```

4. `model->to(device)`

```
No matching member function for call to 'to' candidate function not viable: requires at least 2 arguments, but 1 was provided
```

I do not know how to fix these errors to reproduce the original problem. it would be appreciated if you could provide some guidances about these errors.

**Comment by StefanVK** [comment]
You should probably switch to C++17. The newest versions of pytorch require C++17 support from the compiler.

For what it's worth, I tried reproducing it but I don't get a crash using this Dockerfile:

```
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

# Set non-interactive mode
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y \
    libopencv-dev ninja-build gcc-9 g++-9 wget unzip cmake

# Download and extract libtorch
# alternative: https://download.pytorch.org/libtorch/cu118/libtorch-shared-with-deps-2.2.2%2Bcu118.zip  builds with C++17 but not with C++14
RUN wget -O libtorch.zip https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcu118.zip \
    && unzip libtorch.zip -d /usr/local \
    && rm libtorch.zip

# Copy source code and build
COPY src /app
WORKDIR /app/build
RUN cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -G Ninja ..
RUN cmake --build .
CMD ["./demo"]
```

Adjust CMAKE_PREFIX_PATH in CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10)
project(demo)

set(CMAKE_BUILD_TYPE Debug)

set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "/usr/local/libtorch")
find_package(Torch REQUIRED)
find_package(OpenCV REQUIRED)

set(CMAKE_CXX_FLAGS "${CAMKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(demo demo.cpp)
target_link_libraries(demo ${TORCH_LIBRARIES} ${OpenCV_LIBS} -pthread)
set_property(TARGET demo PROPERTY CXX_STANDARD 14) # !!! Better change to 17 !!!
```

I constructed a cv::Mat instead of loading it
```  
auto device = torch::Device(device_type);

cv::Mat gray(256, 256, CV_8UC1, cv::Scalar(0));

torch::Tensor inp = torch::from_blob(gray.data, {gray.rows, gray.cols}, torch::kByte);
```

And built and ran it with: `docker build . -t tt && docker run --gpus=all -it tt`

**Comment by minostauros** [comment]
> And more interesting, if I generate a random Tensor instead of reading a image, the same codes also can work well.

In my case, not using opencv solves the problem.
