### ISSUE TITLE
torch.export: Unsupported: call_function args: UserDefinedObjectVariable(BatchEncoding) on Gemma

### ISSUE THREAD

**Issue by MaanavD** [pytorch/pytorch#122340]
### 🐛 Describe the bug

Google's Gemma cannot be exported using `torch.export.export` due to a user defined type.
Fake Tensor is used because the model is very big.
A context manager is also used to workaround a bug on safetensor under fake mode

## Script:

```python
import transformers
import safetensors
from typing import List, Union
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch


class WorkAroundSafetensorsBugWithFakeTensor:
   """Workaround safetensors checkpoint loading within fake export mode"""
    def __init__(self):
        def safetensors_load_file_wrapper(filename, device="cpu"):
            result = {}
            with safetensors.torch.safe_open(  # type: ignore[attr-defined]
                filename, framework="pt", device=device
            ) as f:
                for k in f.keys():
                    fake_mode = torch._guards.detect_fake_mode()
                    if not fake_mode:
                        result[k] = f.get_tensor(k)
                    else:
                        empty_tensor = f.get_slice(k)
                        result[k] = torch.empty(
                            tuple(empty_tensor.get_shape()),
                            dtype=safetensors.torch._getdtype(
                                empty_tensor.get_dtype()
                            ),
                        )
            return result

        self.safetensors_torch_load_file = safetensors.torch.load_file
        self.safetensors_torch_load_file_wrapper = safetensors_load_file_wrapper
        self.transformers_modeling_utils_safe_load_file = (
            transformers.modeling_utils.safe_load_file
        )

    def __enter__(self):

        safetensors.torch.load_file = self.safetensors_torch_load_file_wrapper
        transformers.modeling_utils.safe_load_file = (
            self.safetensors_torch_load_file_wrapper
        )

    def __exit__(self, exc_type, exc_value, traceback):
        safetensors.torch.load_file = self.safetensors_torch_load_file
        transformers.modeling_utils.safe_load_file = (
            self.transformers_modeling_utils_safe_load_file
        )

tokenizer = AutoTokenizer.from_pretrained("google/gemma-7b")

input_text = "Write me a poem about Machine Learning."
input_ids = tokenizer(input_text, return_tensors="pt")

with torch._subclasses.fake_tensor.FakeTensorMode(), WorkAroundSafetensorsBugWithFakeTensor():
    model = AutoModelForCausalLM.from_pretrained("google/gemma-7b")
    input = {
        "input_ids": input_ids
    }
    ep = torch.export.export(model, args=(), kwargs=input)
```
    
## Error is as follows:

```bash
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  9.66it/s]
Traceback (most recent call last):
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 572, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 572, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 273, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(BatchEncoding)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gemma.py", line 58, in <module>
    ep = torch.export.export(model, args=(), kwargs=input)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/export/__init__.py", line 193, in export
    return _export(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/export/exported_program.py", line 78, in wrapper
    return fn(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/export/_trace.py", line 600, in _export
    gm_torch_level = _export_to_torch_ir(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/export/_trace.py", line 270, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 1277, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 417, in _fn
    return fn(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 580, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 386, in _convert_frame_assert
    return _compile(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 247, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 526, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in transform
    tracer.run()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2097, in run
    super().run()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1242, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/variables/nn_module.py", line 332, in call_function
    return tx.inline_user_function_return(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 650, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2232, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2341, in inline_call_
    tracer.run()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1230, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 311, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 265, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 84, in call_function
    return tx.inline_user_function_return(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 650, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2232, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2341, in inline_call_
    tracer.run()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
    and self.step()
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
    getattr(self, inst.opname)(inst)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
    return inner_fn(self, inst)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1189, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/variables/nn_module.py", line 310, in call_function
    *proxy_args_kwargs(args, kwargs),
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 579, in proxy_args_kwargs
    raise unimplemented(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 194, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function args: UserDefinedObjectVariable(BatchEncoding)

from user code:
   File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/transformers/models/gemma/modeling_gemma.py", line 1073, in forward
    outputs = self.model(
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maanav/benchmark/.venv/lib/python3.8/site-packages/transformers/models/gemma/modeling_gemma.py", line 869, in forward
    inputs_embeds = self.embed_tokens(input_ids)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

Looking [HF code](https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_base.py#L177), `BatchEncoding` is a custom dict:

```python
from collections import UserDict
class BatchEncoding(UserDict):
```

### Versions

[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.12
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.2.3
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.15.0
[pip3] onnxconverter-common==1.14.0
[pip3] onnxmltools==1.10.0
[pip3] onnxruntime==1.15.1
[pip3] onnxscript==0.1.0.dev20240118
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.3.0
[pip3] skl2onnx==1.16.0
[pip3] torch==2.3.0.dev20240118+cpu
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torchaudio==2.2.0.dev20240118+cpu
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.1.2
[pip3] torchtext==0.15.2
[pip3] torchvision==0.18.0.dev20240118+cpu
[pip3] triton==2.0.0
[pip3] vector-quantize-pytorch==1.7.1
[conda] _anaconda_depends         2023.09             py311_mkl_1
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h213fc3f_46343
[conda] mkl-service               2.4.0           py311h5eee18b_1
[conda] mkl_fft                   1.3.8           py311h5eee18b_0
[conda] mkl_random                1.2.4           py311hdb19cb5_0
[conda] numpy                     1.24.3          py311h08b1b3b_1
[conda] numpy-base                1.24.3          py311hf175353_1
[conda] numpydoc                  1.5.0           py311h06a4308_0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @eellison

**Comment by anijain2305** [comment]
This is because the model is not called correctly. This works

~~~
with WorkAroundSafetensorsBugWithFakeTensor(): 
    model = AutoModelForCausalLM.from_pretrained("google/gemma-7b")
    
    Run eager
    input_ids = tokenizer(input_text, return_tensors="pt")
    print(model(**input_ids))

    Run torch.compile
    input_ids = tokenizer(input_text, return_tensors="pt")
    opt_mod = torch.compile(model, backend="eager", fullgraph=True)
    print(opt_mod(**input_ids))

    # Run torch.export
    input_ids = tokenizer(input_text, return_tensors="pt")
    ep = torch.export.export(model, args=(), kwargs=input_ids)
~~~

More specifically, look at the last line `kwargs=input_ids`. Earlier, it was `kwargs=input`.

With this, the compile works but export fails later at 

~~~
Traceback (most recent call last):
  File "/home/anijain/local/pytorch2/examples/gemma.py", line 66, in <module>
    ep = torch.export.export(model, args=(), kwargs=input_ids)
  File "/home/anijain/local/pytorch2/torch/export/__init__.py", line 174, in export
    return _export(
  File "/home/anijain/local/pytorch2/torch/export/_trace.py", line 1071, in wrapper
    raise e
  File "/home/anijain/local/pytorch2/torch/export/_trace.py", line 1043, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/anijain/local/pytorch2/torch/export/exported_program.py", line 100, in wrapper
    return fn(*args, **kwargs)
  File "/home/anijain/local/pytorch2/torch/export/_trace.py", line 2080, in _export
    exported_program = ExportedProgram(
  File "/home/anijain/local/pytorch2/torch/export/exported_program.py", line 683, in __init__
    self._validate()
  File "/home/anijain/local/pytorch2/torch/export/exported_program.py", line 1104, in _validate
    v().check(self)
  File "/home/anijain/local/pytorch2/torch/_export/verifier.py", line 155, in check
    self._check_graph_module(ep.graph_module)
  File "/home/anijain/local/pytorch2/torch/_export/verifier.py", line 222, in _check_graph_module
    _check_val(node)
  File "/home/anijain/local/pytorch2/torch/_export/verifier.py", line 64, in _check_val
    raise SpecViolationError(f"Node.meta {node.name} is missing val field.")
torch._export.verifier.SpecViolationError: Node.meta _enter_autocast is missing val field.
~~~

@angelayi for the export error, please take a look or assign someone else. Removing dynamo tags from here.

**Comment by angelayi** [comment]
@yushangdi is working on the autocast error, which is similar to https://github.com/pytorch/pytorch/issues/128394#issuecomment-2207303025

**Comment by yushangdi** [comment]
@anijain2305 I think this error should be handled after #131914 lands.
