### ISSUE TITLE
Deprecated gloo-based DDP modules are not pickleable: TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12261]
## To Reproduce

1. Apply this patch:

```
diff --git a/test/test_thd_distributed.py b/test/test_thd_distributed.py
index a104baeb3..032b2dd58 100644
--- a/test/test_thd_distributed.py
+++ b/test/test_thd_distributed.py
@@ -8,6 +8,7 @@ import time
 import unittest
 from contextlib import contextmanager
 from functools import reduce, wraps
+import tempfile
 
 import torch
 import torch.cuda
@@ -154,6 +155,22 @@ class Barrier(object):
             time.sleep(0.1)
 
 
+# The test network must live at top level so we can test pickling it.
+class Net(nn.Module):
+    def __init__(self):
+        super(Net, self).__init__()
+        self.fc1 = nn.Linear(2, 10, bias=False)
+        self.fc2 = nn.Linear(10, 50, bias=False)
+        self.fc3 = nn.Linear(50, 4, bias=False)
+        self.relu = nn.ReLU()
+
+    def forward(self, x):
+        x = self.relu(self.fc1(x))
+        x = self.relu(self.fc2(x))
+        x = self.fc3(x)
+        return F.softmax(x, dim=1)
+
+
 class _DistTestBase(object):
     def _barrier(self, *args, **kwargs):
         Barrier.sync(*args, **kwargs)
@@ -896,20 +913,6 @@ class _DistTestBase(object):
         self._test_all_gather_multigpu_helper(group, group_id, rank, rank_to_GPU)
 
     def _create_Net(self):
-        class Net(nn.Module):
-            def __init__(self):
-                super(Net, self).__init__()
-                self.fc1 = nn.Linear(2, 10, bias=False)
-                self.fc2 = nn.Linear(10, 50, bias=False)
-                self.fc3 = nn.Linear(50, 4, bias=False)
-                self.relu = nn.ReLU()
-
-            def forward(self, x):
-                x = self.relu(self.fc1(x))
-                x = self.relu(self.fc2(x))
-                x = self.fc3(x)
-                return F.softmax(x, dim=1)
-
         return Net()
 
     def _model_step(self, model):
@@ -962,6 +965,12 @@ class _DistTestBase(object):
             # Shuffle the input so that DDP input is different
             input = input[torch.randperm(batch_size)]
 
+        # Test that saving and loading works
+        tmp_file = tempfile.TemporaryFile()
+        torch.save(model_DDP, tmp_file)
+        tmp_file.seek(0)
+        saved_model_DDP = torch.load(tmp_file)
+
     @unittest.skipIf(
         BACKEND != "nccl" and BACKEND != "gloo",
         "Only Nccl & Gloo backend support DistributedDataParallel",
```

Run the thd_distributed tests for gloo backend. (I actually don't know how to do this locally; I can only do it on CI; see https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py2-test2/11715/console )

I get:

```
17:31:06 test_DistributedDataParallel (__main__.TestDistBackend) ... Process process 0:
17:31:09 Process process 1:
17:31:09 Traceback (most recent call last):
17:31:09 Traceback (most recent call last):
17:31:09   File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
17:31:09   File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
17:31:09     self.run()
17:31:09     self.run()
17:31:09   File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 114, in run
17:31:09   File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 114, in run
17:31:09     self._target(*self._args, **self._kwargs)
17:31:09     self._target(*self._args, **self._kwargs)
17:31:09   File "test_thd_distributed.py", line 1102, in _run
17:31:09   File "test_thd_distributed.py", line 1102, in _run
17:31:09     getattr(self, self.id().split(".")[2])()
17:31:09     getattr(self, self.id().split(".")[2])()
17:31:09   File "test_thd_distributed.py", line 1057, in wrapper
17:31:09   File "test_thd_distributed.py", line 1057, in wrapper
17:31:09     fn(self)
17:31:09   File "test_thd_distributed.py", line 59, in wrapper
17:31:09     fn(self)
17:31:09     return func(*args, **kwargs)
17:31:09   File "test_thd_distributed.py", line 59, in wrapper
17:31:09   File "test_thd_distributed.py", line 75, in wrapper
17:31:09     return func(*args, **kwargs)
17:31:09   File "test_thd_distributed.py", line 1014, in test_DistributedDataParallel
17:31:09     return func(*args, **kwargs)
17:31:09     global_bs,
17:31:09   File "test_thd_distributed.py", line 75, in wrapper
17:31:09   File "test_thd_distributed.py", line 970, in _test_DDP_2iter
17:31:09     torch.save(model_DDP, tmp_file)
17:31:09     return func(*args, **kwargs)
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 209, in save
17:31:09   File "test_thd_distributed.py", line 1014, in test_DistributedDataParallel
17:31:09     global_bs,
17:31:09   File "test_thd_distributed.py", line 970, in _test_DDP_2iter
17:31:09     torch.save(model_DDP, tmp_file)
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 209, in save
17:31:09     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 134, in _with_file_like
17:31:09     return body(f)
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 209, in <lambda>
17:31:09     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 282, in _save
17:31:09     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
17:31:09     pickler.dump(obj)
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 134, in _with_file_like
17:31:09 TypeError: can't pickle thread.lock objects
17:31:09     return body(f)
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 209, in <lambda>
17:31:09     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
17:31:09   File "/opt/conda/lib/python2.7/site-packages/torch/serialization.py", line 282, in _save
17:31:09     pickler.dump(obj)
17:31:09 TypeError: can't pickle thread.lock objects
```

I don't intend on fixing this unless someone shouts.

**Comment by teng-li** [comment]
Should be fixed in the PR.
