### ISSUE TITLE
Unable to call len on nested tensor 

### ISSUE THREAD

**Issue by VikaasVarma** [pytorch/pytorch#122701]
### 🐛 Describe the bug

```
import torch

t = torch.nested.nested_tensor([torch.zeros])
len(t)
```

produces error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/opt/anaconda3/envs/test/lib/python3.9/site-packages/torch/_tensor.py", line 904, in __len__
    return self.shape[0]
RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
```

New `nested_tensors` does not support the __len__ operation as it is implemented using `self.shape[0]`. Replacing this with `self.size(0)` should produce intended results.

### Versions

```
--2024-03-26 14:19:05--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22068 (22K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py           100%[==================================>]  21.55K  --.-KB/s    in 0.001s

2024-03-26 14:19:05 (19.0 MB/s) - ‘collect_env.py’ saved [22068/22068]

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (x86_64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:53:33)  [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.2.1-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.6
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h89fa619_689    conda-forge
[conda] mkl-service               2.4.0            py39hadd8af7_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpy-base                1.24.3           py39h9cd3388_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```

**Comment by fleonce** [comment]
I am getting the same error message using `pytorch==2.2.0` and would be willing to submit a PR to address this regression!

**Comment by soulitzer** [comment]
1. I'm not sure this is a regression, e.g. not sure creating a nested tensor using the `torch.nested.nested_tensor(..., layout=torch.strided)` (strided is the default layout) API has ever supported this?

2.  Strided layout nested tensors are not being actively developed, and you should prefer to use jagged-layout nested tensors instead, e.g. with `torch.nested.nested_tensor(..., layout=torch.jagged)` and that would already support `len` today.
