### ISSUE TITLE
Cannot access data pointer of Tensor that doesn't have storage when using torch.func.vmap with c++/cuda extension

### ISSUE THREAD

**Issue by 1996wu** [pytorch/pytorch#122706]
### 🐛 Describe the bug

torch.func.map reports error using cpp extension function, `constrain_make_charts` is a simple table lookup operation.
```
import torch

from torch.func import vmap
from C_extension import constrain_make_charts

cond_array = torch.tensor(
    [
        [1, 0, 1, 1],
        [1, 1, 0, 1],
        [1, 1, 1, 0],
    ],
    dtype=torch.int64,
).reshape(-1, 4)

cond_array = (cond_array * torch.tensor([1, 2, 4, 8])).sum(dim=1, keepdim=True)

func = vmap(constrain_make_charts, in_dims=0)

values = constrain_make_charts(cond_array)
print(values)
func(cond_array)
```

cpp code: **test.cpp**
```cpp
#include <torch/extension.h>
#include <torch/script.h>

#include <algorithm>
#include <unordered_map>
#include <vector>
using Tensor = at::Tensor;

Tensor constrain_make_charts(const Tensor &sym_index) {
  const int64_t nbatch = sym_index.size(0);
  const int64_t *sym_ptr = sym_index.data_ptr<int64_t>();
  auto result = std::vector<double>(nbatch * 4, 0.0);

  std::vector<int64_t> cond_array = {10, 6, 14, 9, 5, 13, 11, 7, 15};
  std::vector<std::vector<double>> merge_array = {
      {1, 0, 0, 0}, {0, 0, 1, 0}, {1, 0, 1, 0}, {0, 1, 0, 0}, {0, 0, 0, 1},
      {0, 1, 0, 1}, {1, 1, 0, 0}, {0, 0, 1, 1}, {1, 1, 1, 1}};
  std::unordered_map<int64_t, std::vector<double>> index_map;
  for (int64_t i = 0; i < 9; i++) {
    index_map[cond_array[i]] = merge_array[i];
  }

  for (int64_t i = 0; i < nbatch; i++) {
    int64_t offset = i * 4;
    std::copy_n(index_map[sym_ptr[i]].data(), 4, &result[offset]);
  }
  Tensor result_tensor =
      torch::from_blob(
          result.data(), nbatch * 4,
          torch::TensorOptions().dtype(torch::kDouble).requires_grad(false))
          .reshape({nbatch, 4});
  return std::move(result_tensor.clone());
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("constrain_make_charts", &constrain_make_charts);
}
```
complie file: **setup.py**
```python
import os.path as osp

from setuptools import setup
from torch.utils.cpp_extension import BuildExtension
from torch.utils.cpp_extension import CppExtension

ROOT_DIR = osp.dirname(osp.abspath(__file__))

s = "C_extension"
include_dirs = [osp.join(ROOT_DIR)]
sources = ["test.cpp"]
CPU_VERSION = CppExtension(
name=s,
sources=sources,
include_dirs=include_dirs,
extra_compile_args={"cxx": ["-O3", "-std=c++17"]}
)


setup(
    name=s,
    version='0.1',
    author='zbwu',
    author_email='zbwu1996@gmail.com',
    description=s,
    long_description=s,
    ext_modules=[
        CPU_VERSION
    ],
    cmdclass={
        'build_ext': BuildExtension.with_options(no_python_abi_suffix=True)
    }
)
```
Run the following code
```shell
python setup.py develop && python demo.py
```
> RuntimeError: Cannot access data pointer of Tensor that doesn't have storage

**Error logs**
```
tensor([[0., 1., 0., 1.],
        [1., 1., 0., 0.],
        [0., 0., 1., 1.]], dtype=torch.float64)
Traceback (most recent call last):
  File "/home/zbwu/Desktop/issue/demo.py", line 21, in <module>
    func(cond_array)
  File "/home/zbwu/soft/anaconda3/lib/python3.10/site-packages/torch/_functorch/apis.py", line 188, in wrapped
    return vmap_impl(func, in_dims, out_dims, randomness, chunk_size, *args, **kwargs)
  File "/home/zbwu/soft/anaconda3/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 278, in vmap_impl
    return _flat_vmap(
  File "/home/zbwu/soft/anaconda3/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 44, in fn
    return f(*args, **kwargs)
  File "/home/zbwu/soft/anaconda3/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 391, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

### Versions

```
Collecting environment information...
PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (Arch Linux 10.5.0-1) 10.5.0
Clang version: 17.0.6
CMake version: version 3.29.0
Libc version: glibc-2.39

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
```

cc @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by xkhainguyen** [comment]
I am encountering the same issue. Look forward to a fix soon.

**Comment by 1996wu** [comment]
> I am encountering the same issue. Look forward to a fix soon. Things I notice are:
> 
> * You have to make `constrain_make_charts` a PyToch `Function` class with `forward` and `vmap` static methods. Then it let you apply `vmap` over that function. However, I got the correct result for the first batch but garbage results from 2nd batch.
> * This is because `constrain_make_charts` itself cannot handle batch input, applying `vmap` will give undefined behaviors.
> * The only thing you can do is multi-thread CPU/CUDA programming, which I'm not familiar with.

I don't quite understand how to define `vmap staticmethod` using `torch.autograd.Function`. Could you provide an example for using this.

**Comment by xkhainguyen** [comment]
vmap will accept something like this but the operation is apparently wrong. The below code will blindly apply the whole batch input to the `cartpole2l_cpp.forward_dynamics` function, resulting in undefined behaviors. Probably I should use a `for loop` for correct results, but it is NOT what we want.
**We need to do CUDA programming for that function.**

Everyone: Please let me know if you have better ideas on this. Thanks.
```
class Cartpole2LFunction(Function):
    @staticmethod
    def forward(q_in, qdot_in, tau_in):
        qddot_out = cartpole2l_cpp.forward_dynamics(q_in, qdot_in, tau_in)
        return qddot_out
    
    @staticmethod
    # inputs is a Tuple of all of the inputs passed to forward.
    # output is the output of the forward().
    def setup_context(ctx, inputs, output):
        q_in, qdot_in, tau_in = inputs
        qddot_out = output
        ctx.save_for_backward(q_in, qdot_in, tau_in, qddot_out)
    
    @staticmethod
    def vmap(info, in_dims, q_in, qdot_in, tau_in):
        q_in_bdim, qdot_in_bdim, tau_in_bdim  = in_dims

        q_in = q_in.movedim(q_in_bdim, 0)
        qdot_in = qdot_in.movedim(qdot_in_bdim, 0)
        tau_in = tau_in.movedim(tau_in_bdim, 0)

        qddot_out = Cartpole2LFunction.apply(q_in, qdot_in, tau_in)

        return qddot_out, 0
```

**Comment by guilhermeleobas** [comment]
As @xkhainguyen said, you need to provide a `vmap` staticmethod ([ref](https://pytorch.org/docs/stable/notes/extending.func.html#torch-vmap-support)) or defining `generate_vmap_rule=True` to let PyTorch autogenerate it for you.

**Comment by lezcano** [comment]
Closing this as expected.
