### ISSUE TITLE
torch.func transforms don't yet support saved tensor hooks.

### ISSUE THREAD

**Issue by Jinghong-Zhang** [pytorch/pytorch#122729]
### 🚀 The feature, motivation and pitch

Hello pytorch develops, I encountered the following error when I am executing my code: `RuntimeError: torch.func transforms don't yet support saved tensor hooks. Please open an issue with your use case.` Basically I am trying to do gradient checkpointing of a function which contains vmap as one of its operations. The minimum code to reproduce this error is given as follows:
```python
import torch
from torch.utils.checkpoint import checkpoint
A = torch.randn((3, 8, 8), dtype=torch.float64, requires_grad=True)

def get_loss(A):
    ortho_A, _ = torch.func.vmap(torch.linalg.qr)(A)
    return torch.sum(ortho_A)

loss = checkpoint(get_loss, A, use_reentrant=False)
loss.backward()
print(A.grad)
```

The full error message is:
```
Traceback (most recent call last):
  File "/path/to/tests/vmapcheckpoint.py", line 9, in <module>
    loss = checkpoint(get_loss, A, use_reentrant=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 458, in checkpoint
    ret = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/tests/vmapcheckpoint.py", line 6, in get_loss
    ortho_A, _ = torch.func.vmap(torch.linalg.qr)(A)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/_functorch/apis.py", line 188, in wrapped
    return vmap_impl(func, in_dims, out_dims, randomness, chunk_size, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/_functorch/vmap.py", line 266, in vmap_impl
    return _flat_vmap(
           ^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/_functorch/vmap.py", line 37, in fn
    with torch.autograd.graph.disable_saved_tensors_hooks(message):
  File "/Applications/anaconda3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/torch/autograd/graph.py", line 322, in disable_saved_tensors_hooks
    torch._C._autograd._saved_tensors_hooks_disable(error_message)
RuntimeError: torch.func transforms don't yet support saved tensor hooks. Please open an issue with your use case.
```

I wonder if it is possible to make vmap compatible for gradient checkpointing, which is crucial for my code. Thanks!

**Comment by KinWaiCheuk** [comment]
I encounter the same problem in my project.
Here's the minimal code to reproduce it

```python
import torch
import torch.nn as nn
import torch.optim as optim
import random
from torch.func import vmap
from torch.utils.checkpoint import checkpoint

# Set a fixed seed for reproducibility
seed = 42
torch.manual_seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)  # For multi-GPU setups
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# Define a simple Transformer model
class SimpleTransformer(nn.Module):
    def __init__(self, input_dim, model_dim, num_heads, num_layers, output_dim):
        super(SimpleTransformer, self).__init__()
        self.embedding = nn.Embedding(input_dim, model_dim)
        self.transformer = nn.Transformer(d_model=model_dim, nhead=num_heads, num_encoder_layers=num_layers)
        self.fc_out = nn.Linear(model_dim, output_dim)
        
    def forward(self, src, tgt):
        src = self.embedding(src)
        tgt = self.embedding(tgt)
        # output = self.transformer(src, tgt)
        output = checkpoint(self.transformer, src, tgt, use_reentrant=False)
        return self.fc_out(output)
    
def compute_loss(model,
                 weights,
                 buffers,
                 src,
                 tgt,
                 ):

    # Forward pass
    output = torch.func.functional_call(
        model, (weights, buffers), args=(src.unsqueeze(1), tgt[:-1].unsqueeze(1))
        )

    # Reshape output and target for loss calculation
    output = output.view(-1, output_dim)
    tgt = tgt[1:].view(-1)  # Shift target sequence by one
    loss = criterion_mean(output, tgt)
    print(loss.shape)
    return loss

# Hyperparameters
input_dim = 1000  # Vocabulary size
model_dim = 512   # Embedding dimension
num_heads = 8     # Number of attention heads
num_layers = 6    # Number of transformer layers
output_dim = 1000 # Output vocabulary size
seq_length = 10   # Sequence length

# Initialize model, loss function, and optimizer
model = SimpleTransformer(input_dim, model_dim, num_heads, num_layers, output_dim)
criterion_mean = nn.CrossEntropyLoss()
criterion_raw = nn.CrossEntropyLoss(reduction='none')
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Dummy data (batch_size = 2, seq_length = 10)
src = torch.randint(0, input_dim, (seq_length, 2))  # Source sequence
tgt_raw = torch.randint(0, output_dim, (seq_length, 2)) # Target sequence

# Print src and tgt to verify they are the same each time
print("Source sequence (src):")
print("Target sequence (tgt):")

# Forward pass
output = model(src, tgt_raw[:-1, :])  # Exclude the last token in the target sequence

# Reshape output and target for loss calculation
output = output.view(-1, output_dim)
tgt = tgt_raw[1:, :].view(-1)  # Shift target sequence by one

weights = dict(model.named_parameters())
buffers = dict(model.named_buffers())
 
grads_fn = torch.func.grad(compute_loss, has_aux=False, argnums=1)
gs = vmap(grads_fn,
            in_dims=(None, None, None, 1, 1),
            randomness='different')(
                model,
                weights,
                buffers,
                src,
                tgt_raw
            )
```

At first, I got this error

> RuntimeError: You tried to vmap over _NoopSaveInputs, but it does not have vmap support. Please override and implement the vmap staticmethod or set generate_vmap_rule=True. For more details, please see https://pytorch.org/docs/master/notes/extending.func.html

Following the note given in the error, I added `generate_vmap_rule = True` under the `_NoopSaveInputs` class, and I ended up with the same problem as @Jinghong-Zhang.

May I know if there's any plan to make vmap compatible for gradient checkpointing?
