### ISSUE TITLE
[dynamo] Tracing triton kernel unexpectedly

### ISSUE THREAD

**Issue by oraluben** [pytorch/pytorch#122768]
### 🐛 Describe the bug

#110185 and following updates handle trivial triton kernels, however this is used in some packages, e.g. `flash_attn.layers.rotary`

A simple repro:
```
import torch
import triton

@triton.jit
def test_kernel(kernel):
    pass

@torch.compile(backend="eager")
def f(x):
    grid = (x.numel(),)
    # test_kernel[grid](kernel=x)
    with torch.cuda.device(x.device.index):
        test_kernel[grid](kernel=x)

t1 = torch.rand(5, device="cuda")
f(t1)
```

which gives:

```
Traceback (most recent call last):
  File "/home/yyc/repo/zero3-dynamo/test.py", line 16, in <module>
    f(t1)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 497, in _fn
    return fn(*args, **kwargs)
  File "/home/yyc/repo/zero3-dynamo/test.py", line 12, in f
    with torch.cuda.device(x.device.index):
  File "/home/yyc/repo/zero3-dynamo/test.py", line 13, in resume_in_f
    test_kernel[grid](kernel=x)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 413, in run
    grid = get_special_arg("grid")
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 426, in resume_in_run
    bound_args = self.signature.bind(*args, **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 427, in resume_in_run
    bound_args.apply_defaults()
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 429, in resume_in_run
    assert len(bound_args.arguments) == len(self.params)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 429, in resume_in_run
    assert len(bound_args.arguments) == len(self.params)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 430, in resume_in_run
    args = [KernelArg(arg_value, param) for (_, arg_value), param in zip(bound_args.arguments.items(), self.params)]
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 430, in resume_in_run
    args = [KernelArg(arg_value, param) for (_, arg_value), param in zip(bound_args.arguments.items(), self.params)]
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 453, in resume_in_run
    [self._pinned_memory_of(arg) for arg in non_constexpr_arg_values])
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 453, in <listcomp>
    [self._pinned_memory_of(arg) for arg in non_constexpr_arg_values])
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 681, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1213, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/variables/misc.py", line 660, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/variables/tensor.py", line 756, in call_method
    return wrap_fx_proxy(
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1314, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1399, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1525, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1486, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1027, in wrap_fake_exception
    return fn()
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1487, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1592, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1573, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1392, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1649, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 737, in nyi
    assert func not in _device_not_kwarg_ops, f"NYI: {func}"
torch._dynamo.exc.TorchRuntimeError: Failed running call_method is_pinned(*(FakeTensor(..., device='cuda:0', size=(5,)),), **{}):
NYI: aten.is_pinned.default

from user code:
   File "/home/yyc/.local/miniconda3/envs/test_env/lib/python3.10/site-packages/triton/runtime/jit.py", line 241, in _pinned_memory_of
    return arg.is_pinned()

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

### Versions

Collecting environment information...
PyTorch version: 2.2.0.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.134-16.1.al8.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.3.107
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A10
GPU 1: NVIDIA A10

Nvidia driver version: 535.146.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
Stepping:                        6
BogoMIPS:                        5800.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        40 MiB (32 instances)
L3 cache:                        48 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.15.0rc2
[pip3] optree==0.10.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.2.0+cu121
[pip3] torch-tensorrt==2.3.0a0
[pip3] torchaudio==2.2.0+cu121
[pip3] torchvision==0.17.0+cu121
[pip3] triton==2.2.0
[conda] Could not collect

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by oraluben** [comment]
As a workaround/fallback I think we can consider to add `triton` in `skipfiles.py::THIRDPARTY_SKIPLIST`

**Comment by yf225** [comment]
cc. @yanboliang

**Comment by thepowerfuldeez** [comment]
+1. Have the same problem here with flash-attn triton apply_rotary_emb func

**Comment by thepowerfuldeez** [comment]
I skipped the torch compile with torch.compiler.disable decorator and now it works

**Comment by oraluben** [comment]
handled correctly in 2.3.0
