### ISSUE TITLE
[Inductor] `test_mixed_mm_dynamic_shapes_cuda` is broken on multiple architectures

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#122747]
### 🐛 Describe the bug

observed
`python test/inductor/test_torchinductor_codegen_dynamic_shapes.py -k test_mixed_mm_dynamic_shapes_cuda` failing on A2 (sm86/GA107) and V100 (sm70/GV100), among others.

### Versions

Nightly build as of 3/26.

cc @ptrblck @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

**Comment by Aidyn-A** [comment]
Possibly related #122227

**Comment by tinglvv** [comment]
Seeing the failure on V100 and T4. 
```________ DynamicShapesCodegenGPUTests.test_mixed_mm_dynamic_shapes_cuda ________
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2697, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 8508, in new_test
    return value(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/testing.py", line 320, in _fn
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 2184, in test_mixed_mm
    self.common(
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py", line 335, in common
    return check_codegen(
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py", line 97, in check_codegen
    self.assertTrue(triton_kernel_found, f"Failed to find triton kernel\n{code}")
  File "/usr/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Failed to find triton kernel````

**Comment by cpuhrsch** [comment]
cc @HDCharles @alexsamardzic FYI

**Comment by eqy** [comment]
Note: is inductor meant to support codegen on Volta?

**Comment by cpuhrsch** [comment]
Is this related to https://github.com/openai/triton/issues/2853 ?

**Comment by cpuhrsch** [comment]
As a mitigation this should be resolvable with a guard. I want to differentiate between a Triton bug and a missing guard. @pearu maybe this could be a good task to get more familiar with the code? Do you easy access to a V100?

**Comment by alexsamardzic** [comment]
I was able to reproduce, and will check - on a second look, it may have to do with my changes when CUTLASS kernels added for auto-tuning for mixed MM...

**Comment by alexsamardzic** [comment]
Ok, after checking it: I think this issue, as is, has nothing to do with above mentioned Triton bug, or my CUTLASS-related changes.  The error is reported, in its current form, as far back as for 6c67f33. The idea of this change was to guard against auto-tuning mixed MM on 7.x and older archs, which makes sense.  For such archs, the compiler should just use the fallback.  However, `test_torchinductor_codegen_dynamic_shapes.py` would still check is Triton kernel generated, and would report failure.

So the fix would be to decorate `test_mixed_mm` in `test_torchinductor.py` with `@expectedFailureCodegenDynamic`, but somehow only if `SM80OrLater` is not true.

**Comment by eqy** [comment]
I went back to check A2 and it looks like the test is failing (on a nightly build from yesterday) but the failure mode appears different:
```
[eaf60699f6a8:163  :0:163] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xc)                                                 [188/1876]==== backtrace (tid:    163) ====                                                                                                                                        0 0x0000000000042520 __sigaction()  ???:0
 1 0x00000000015db7ea mlir::LLVM::InsertElementOp::inferReturnTypes()  ???:0
 2 0x00000000015db747 mlir::LLVM::InsertElementOp::build()  ???:0
 3 0x000000000101252b mlir::OpBuilder::create<mlir::LLVM::InsertElementOp, mlir::Value&, mlir::LLVM::ExtractElementOp, mlir::Value>()  /root/.triton/llvm/llvm-4017f04e-ubuntu-x64/include/mlir/IR/Builders.h:508
 4 0x000000000101252b MMA16816SmemLoader::loadX4()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp:418
 5 0x0000000001013681 getLoadMatrixFn(mlir::triton::MemDescType, mlir::LLVM::SharedMemoryObject const&, mlir::triton::gpu::NvidiaMmaEncodingAttr, int, unsigned int, int, llvm::SmallVector<int, 12u>, llvm::SmallVector<int, 12u>, llvm::SmallVector<mlir::Value, 6u>, mlir::Value, std::map<std::array<int, 3ul>, mlir::Value, std::less<std::array<int, 3ul> >, std::allocator<std::pair<std::array<int, 3ul> const, mlir::Value> > >&, bool, mlir::LLVMTypeConverter const*, mlir::ConversionPatternRewriter&, mlir::Location)::{lambda(int, int, int)#1}::operator()()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp:573
 6 0x0000000001010980 std::function<void (int, int, int)>::operator()()  /usr/include/c++/11/bits/std_function.h:590
 7 0x0000000001010f47 SharedToDotOperandMMAv2::convertLayout()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp:780
 8 0x000000000102dad9 (anonymous namespace)::LocalLoadOpConversion::matchAndRewrite()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp:74
 9 0x000000000102dad9 lowerSharedToDotOperand()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp:118
10 0x000000000102dad9 matchAndRewrite()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp:180
11 0x000000000102e2c0 mlir::ConvertOpToLLVMPattern<mlir::triton::gpu::LocalLoadOp>::matchAndRewrite()  /root/.triton/llvm/llvm-4017f04e-ubuntu-x64/include/mlir/Conversion/LLVMCommon/Pattern.h:161
12 0x0000000002c0d730 mlir::ConversionPattern::matchAndRewrite()  ???:0
13 0x0000000002c4bb64 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>)::$_2::operator()()  PatternApplicator.cpp:0
14 0x0000000002c4867f mlir::PatternApplicator::matchAndRewrite()  ???:0
15 0x0000000002c1cde5 (anonymous namespace)::OperationLegalizer::legalize()  DialectConversion.cpp:0
16 0x0000000002c11674 (anonymous namespace)::OperationConverter::convertOperations()  DialectConversion.cpp:0
17 0x0000000002c14910 mlir::applyPartialConversion()  ???:0
18 0x00000000010d455c (anonymous namespace)::ConvertTritonGPUToLLVM::runOnOperation()  /opt/openai/triton/third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp:271
19 0x00000000014d9db6 mlir::detail::OpToOpPassAdaptor::run()  ???:0
20 0x00000000014da701 mlir::detail::OpToOpPassAdaptor::runPipeline()  ???:0
21 0x00000000014dce0b mlir::PassManager::run()  ???:0
22 0x000000000120d40d init_triton_ir(pybind11::module_&&)::{lambda(mlir::PassManager&, mlir::ModuleOp&)#214}::operator()()  /opt/openai/triton/python/src/ir.cc:1558
23 0x000000000121c7d8 pybind11::cpp_function::initialize<init_triton_ir(pybind11::module_&&)::{lambda(mlir::PassManager&, mlir::ModuleOp&)#214}, void, mlir::PassManager&, mlir::ModuleOp&, pybind11::name, pybind11::is_method, pybind11::sibling>(init_triton_ir(pybind11::module_&&)::{lambda(mlir::PassManager&, mlir::ModuleOp&)#214}&&, void (*)(mlir::PassManager&, mlir::ModuleOp&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}:
:_FUN()  /root/.triton/pybind11/pybind11-2.11.1/include/pybind11/detail/../cast.h:1480
24 0x000000000121c7d8 _FUN()  /root/.triton/pybind11/pybind11-2.11.1/include/pybind11/pybind11.h:224                                                          [148/1876]25 0x000000000120212c pybind11::cpp_function::dispatcher()  /root/.triton/pybind11/pybind11-2.11.1/include/pybind11/pybind11.h:946
26 0x000000000015a10e PyObject_CallFunctionObjArgs()  ???:0
27 0x0000000000150a7b _PyObject_MakeTpCall()  ???:0
28 0x0000000000168acb PyMethod_New()  ???:0
29 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
30 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
31 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
32 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
33 0x000000000014326d _PyEval_EvalFrameDefault()  ???:0
34 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
35 0x0000000000169492 PyObject_Call()  ???:0
36 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
37 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
38 0x000000000014345c _PyEval_EvalFrameDefault()  ???:0
39 0x00000000001687f1 PyMethod_New()  ???:0
40 0x000000000014453c _PyEval_EvalFrameDefault()  ???:0
41 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
42 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
43 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
44 0x00000000001455d7 _PyEval_EvalFrameDefault()  ???:0
45 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
46 0x000000000014345c _PyEval_EvalFrameDefault()  ???:0
47 0x00000000001687f1 PyMethod_New()  ???:0
48 0x000000000014453c _PyEval_EvalFrameDefault()  ???:0
49 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
50 0x000000000014345c _PyEval_EvalFrameDefault()  ???:0
51 0x000000000014fc14 _PyObject_FastCallDictTstate()  ???:0
52 0x0000000000164a64 _PyStack_AsDict()  ???:0
53 0x0000000000150a1c _PyObject_MakeTpCall()  ???:0
54 0x0000000000149096 _PyEval_EvalFrameDefault()  ???:0
55 0x000000000015a9fc _PyFunction_Vectorcall()  ???:0
56 0x0000000000148cfa _PyEval_EvalFrameDefault()  ???:0
=================================
E
======================================================================                                                                                        [113/1876]ERROR: test_mixed_mm_dynamic_shapes_cuda (__main__.DynamicShapesCodegenGPUTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 9582, in new_test
    return value(self)
  File "/opt/pytorch/pytorch/torch/_dynamo/testing.py", line 300, in _fn
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 2428, in test_mixed_mm
    self.common(
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py", line 383, in common
    return check_codegen(
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py", line 91, in check_codegen
    code = run_and_get_triton_code(run, *example_inputs, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/utils.py", line 1116, in run_and_get_triton_code
    _, source_codes = run_and_get_code(fn, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/utils.py", line 1065, in run_and_get_code
    result = fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 978, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 411, in _convert_frame_assert
    return _compile(
  File "/opt/pytorch/pytorch/torch/_utils_internal.py", line 70, in wrapper_function
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 700, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 568, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/pytorch/pytorch/torch/_dynamo/bytecode_transformation.py", line 1113, in transform_code_object
    transformations(instructions, code_options)
      File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 173, in _fn                                                                                 [73/1876]    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 515, in transform
    tracer.run()
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2201, in run
    super().run()
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 857, in run
    while self.step():
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 767, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2337, in RETURN_VALUE
    self._return(inst)
  File "/opt/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2322, in _return
    self.output.compile_subgraph(
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1050, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1264, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1331, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1312, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_dynamo.py", line 127, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_dynamo.py", line 127, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py", line 80, in compile_fx_wrapper
    return compile_fx(model_, example_inputs_)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1398, in compile_fx
    return aot_autograd(
  File "/opt/pytorch/pytorch/torch/_dynamo/backends/common.py", line 65, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 951, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
      File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper                                                                                [33/1876]    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 678, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(
  File "/opt/pytorch/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 467, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/pytorch/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 669, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/pytorch/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 149, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1311, in fw_compiler_base
    return inner_compile(
  File "/opt/pytorch/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/pytorch/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 469, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 746, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 1448, in compile_to_fn
    return self.compile_to_module().call
  File "/opt/pytorch/pytorch/torch/_inductor/utils.py", line 1054, in patched_compile_to_module
    mod = compile_to_module(self)
  File "/opt/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_inductor/graph.py", line 1395, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 2310, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/ol/coljml5lyqoudnsjvwycn7nbrbpooaa26ktavhwevemifemk3i5b.py", line 128, in <module>
    async_compile.wait(globals())
      File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 2875, in wait
    scope[key] = result.result()
  File "/opt/pytorch/pytorch/torch/_inductor/codecache.py", line 2694, in result
    self.future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


To execute this test, run the following from the base repo dir:
     python test/inductor/test_torchinductor_codegen_dynamic_shapes.py -k test_mixed_mm_dynamic_shapes_cuda

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 502.120s

FAILED (errors=1)
inline_call []
stats [('calls_captured', 2)]
inductor [('pattern_matcher_nodes', 2), ('pattern_matcher_count', 1)]
aot_autograd [('total', 1), ('not_ok', 1)]
```

**Comment by alexsamardzic** [comment]
That seems to me as a different issue from failures on 7.x and lower archs.  Maybe it is related with the Trition issue that @cpuhrsch linked above?

**Comment by eellison** [comment]
mixed_mm deleted, closing.
