### ISSUE TITLE
TestJit.test_lstm_fusion_concat_cuda fails for some inputs

### ISSUE THREAD

**Issue by hartb** [pytorch/pytorch#12286]
Test `test_lstm_fusion_concat_cuda` in the `jit` test bucket fails for
certain inputs:

```
$ python run_test.py -i jit -- TestJit.test_lstm_fusion_concat_cuda
Running test_jit ...
F
======================================================================
FAIL: test_lstm_fusion_concat_cuda (__main__.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hartb/test2/common.py", line 275, in wrapper
    method(*args, **kwargs)
  File "/home/hartb/test2/common.py", line 109, in wrapper
    fn(*args, **kwargs)
  File "test_jit.py", line 691, in test_lstm_fusion_concat_cuda
    ge = self.checkTrace(LSTMCellC, inputs)
  File "test_jit.py", line 368, in checkTrace
    self.assertTrue(torch.allclose(g2, g2_ge, atol=7e-4, rtol=1e-4))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 5.639s

FAILED (failures=1)
```

The failure occurs in current `master` (through at least `v1.0rc1`).

The failure is seen on both:

- ppc64le / CUDA 10.0 / NVIDIA V100 GPU / RHEL 7.5
- x86 / CUDA 9.2 / NVIDIA K80 GPU / Ubuntu 16.04

The failure depends on the input data. The test will _usually_ pass,
depending on the state of the RNG when the test is reached.

A failure can be forced by seeding the RNG with specific values. For
example:

```
$ git diff -- test_jit.py
diff --git a/test/test_jit.py b/test/test_jit.py
index 24d8076..a9f6a83 100644
--- a/test/test_jit.py
+++ b/test/test_jit.py
@@ -686,6 +686,7 @@ class TestJit(JitTestCase):
     @unittest.skipIf(not RUN_CUDA, "fuser requires CUDA")
     @skipIfRocm
     def test_lstm_fusion_concat_cuda(self):
+        torch.manual_seed(122)
         inputs = get_lstm_inputs('cuda')
         ge = self.checkTrace(LSTMCellC, inputs)
         self.assertExpectedGraph(ge.graph_for(*inputs))
```

The cause of the failure is that the difference in two sets of
calculated gradients is out of tolerance (`7e-4`). Inspecting the
out-of-tolerance differences shows that both platforms calculate the
same gradient pairs, and that the differences between the gradients in
each pair is close but somewhat outside the tolerance of the test:

On ppc64le / CUDA 10 / V100 / RHEL 7.5:

```
Running test_jit ...
command run python test_jit.py TestJit.test_lstm_fusion_concat_cuda
ge[1][5] =  -2698.955078125, g2_ge[1][5] =  -2698.956298828, abs diff = 0.001220703125
ge[1][6] =     60.063949585, g2_ge[1][6] =     60.062801361, abs diff = 0.00114822387695
ge[1][7] =  -2317.295166016, g2_ge[1][7] =  -2317.296142578, abs diff = 0.0009765625
ge[2][0] =   1820.975341797, g2_ge[2][0] =   1820.976318359, abs diff = 0.0009765625
ge[2][3] =  -9474.621093750, g2_ge[2][3] =  -9474.622070312, abs diff = 0.0009765625
...
ge[71][6] =  -2849.033447266, g2_ge[71][6] =  -2849.034179688, abs diff = 0.000732421875
ge[73][0] =  -4872.507324219, g2_ge[73][0] =  -4872.508789062, abs diff = 0.00146484375
ge[73][4] =   1764.805541992, g2_ge[73][4] =   1764.806274414, abs diff = 0.000732421875
ge[73][6] =   2349.417968750, g2_ge[73][6] =   2349.418701172, abs diff = 0.000732421875
ge[73][8] =  -3767.620849609, g2_ge[73][8] =  -3767.622070312, abs diff = 0.001220703125
...
```

On x86 / CUDA 9.2 / K80 / Ubuntu 16.04:

```
Running test_jit ...
ge[1][5] =  -2698.955078125, g2_ge[1][5] =  -2698.956298828, abs diff = 0.001220703125
ge[1][6] =     60.063949585, g2_ge[1][6] =     60.062801361, abs diff = 0.00114822387695
ge[1][7] =  -2317.295166016, g2_ge[1][7] =  -2317.296142578, abs diff = 0.0009765625
ge[2][0] =   1820.975341797, g2_ge[2][0] =   1820.976318359, abs diff = 0.0009765625
ge[2][3] =  -9474.621093750, g2_ge[2][3] =  -9474.622070312, abs diff = 0.0009765625
...
ge[71][6] =  -2849.033447266, g2_ge[71][6] =  -2849.034179688, abs diff = 0.000732421875
ge[73][0] =  -4872.507324219, g2_ge[73][0] =  -4872.508789062, abs diff = 0.00146484375
ge[73][4] =   1764.805541992, g2_ge[73][4] =   1764.806274414, abs diff = 0.000732421875
ge[73][6] =   2349.417968750, g2_ge[73][6] =   2349.418701172, abs diff = 0.000732421875
ge[73][8] =  -3767.620849609, g2_ge[73][8] =  -3767.622070312, abs diff = 0.001220703125
```

Given the absolute values of the gradients (often falling in the `2^10`
to `2^16` range) and the data type (`float32`), the differences amount to
being off by a few units (~3-5) in the least significant bits.

So I think there's not a fundamental problem here, just rounding errors
for certain inputs that pushes the result outside the test's tolerance.

If so, then possible solutions for this would include, at least:

- relax the tolerance for this test
- seed the RNG with a value that will generate well-behaved inputs (any
  in the range 1 - 121 should pass)

**Comment by zou3519** [comment]
I haven't seen a failure for this before, but please let me know if it shows up again.

**Comment by hartb** [comment]
FWIW, I agree with the closure. We hadn't seen failure recur since the initial report. Thank you!
