### ISSUE TITLE
Incorrect model configuration (possible dynamic axes issue) after torch.onnx.export

### ISSUE THREAD

**Issue by FominArtmind** [pytorch/pytorch#122868]
### 🐛 Describe the bug

I have the following model:

```
import torch
import torchaudio

class ConformerSpeechRecognizer(torch.nn.Module):
    def __init__(self,
                 kernel_size,
                 ffn_dim: int,
                 feature_vector_size: int,
                 hidden_layer_size: int,
                 num_layers: int,
                 num_heads: int,
                 dropout: float,
                 depthwise_conv_kernel_size: int,
                 vocabulary_size: int):
        super().__init__()
        self.vocabulary_size = vocabulary_size
        self.cnn_ = torch.nn.Sequential(
            torch.nn.BatchNorm1d(num_features=feature_vector_size),
            torch.nn.Conv1d(
                in_channels=feature_vector_size,
                out_channels=hidden_layer_size,
                bias=False,
                kernel_size=(kernel_size,),
                padding='same'
            ),
            torch.nn.BatchNorm1d(num_features=hidden_layer_size)
        )
        self.conformer_ = torchaudio.models.Conformer(
            input_dim=hidden_layer_size,
            num_heads=num_heads,
            num_layers=num_layers,
            ffn_dim=ffn_dim,
            depthwise_conv_kernel_size=depthwise_conv_kernel_size,
            dropout=dropout
        )
        self.proba_appoximator_ = torch.nn.Linear(
            in_features=hidden_layer_size,
            out_features=vocabulary_size
        )
    def forward(self, inputs: torch.Tensor, input_lenghts: torch.Tensor) -> torch.Tensor:
        hidden_states = torch.nn.functional.gelu(self.cnn_(inputs.permute(0, 2, 1)))
        hidden_states, _ = self.conformer_(hidden_states.permute(0, 2, 1), input_lenghts)
        output_logits = self.proba_appoximator_(hidden_states)
        return output_logits
```

The model trained with the following parameters:
```
# my_module = ConformerSpeechRecognizer(
#                 hidden_layer_size=512,
#                 ffn_dim=64,
#                 num_heads=8,
#                 kernel_size=9,
#                 feature_vector_size=13,
#                 num_layers=6,
#                 dropout=0.41130458168952116,
#                 depthwise_conv_kernel_size=9
#                 vocabulary_size=37)
```

And properly works as Pytorch model. However, when I export it to onnx:

```
import torch
from conformer_model import ConformerSpeechRecognizer

model = torch.load("model.pt")
torch.onnx.export(model.cpu(),
                  f="../model.onnx",
                  input_names=["inputs", "input_lenghts"],
                  output_names=["logits"],
                  args=({ "inputs": torch.ones(1, 1, 13), "input_lenghts": torch.ones(1, dtype=torch.long) }),
                  dynamic_axes={
                    "inputs": { 0: "batch_count", 1: "batch_item_length" },
                    "input_lenghts": { 0: "batch_count" },
                    "logits": { 0: "batch_count", 1: "batch_item_length" }
                  },
                  verbose=True
                )
```

and try to check the model output:
```
import torch
import torchaudio
import conformer_model
from transformers import Wav2Vec2CTCTokenizer
import onnxruntime as ort
import numpy

testDir = "test conformer/";
testFiles = ["1_0.wav", "1_1.wav", "1_2.wav"];  

def loadTestFileFeatureMatrix(fileName):
  waveform, sample_rate = torchaudio.load(testDir + fileName, normalize=True)
  transform = torchaudio.transforms.MFCC(
    sample_rate=16000,
    n_mfcc=13,
    melkwargs={
      'n_mels': 64,
      'n_fft': 512,
      'win_length': 400,
      'hop_length': 320,
      'center': False,
      'power': 2,
      'f_min': 200,
      'f_max': 5000
    }
  )

  mfcc = transform(waveform)

  numpy_array = mfcc[0].numpy()
  numpy.savetxt(testDir + fileName.rsplit('.', 1)[0] + "_spectral_array.txt", numpy_array)

  return mfcc


tokenizer = Wav2Vec2CTCTokenizer.from_pretrained("conformer")

feature_lengths = []
features = []

for file in testFiles:
  with torch.no_grad():
    mfcc = loadTestFileFeatureMatrix(file)
    new_feature_matrix = mfcc
    new_feature_matrix = torch.moveaxis(mfcc, 1, 2)
  feature_lengths.append(new_feature_matrix.cpu().size()[1])
  features.append(new_feature_matrix[0])

features = torch.nn.utils.rnn.pad_sequence(features, batch_first=True, padding_value=0)
feature_lengths = torch.from_numpy(numpy.array(feature_lengths, dtype=numpy.int32)).to(torch.long)

print(features.shape)
print(feature_lengths.shape)

session = ort.InferenceSession("conformer-onnx/model.onnx")

ortvalue = ort.OrtValue.ortvalue_from_numpy(features.numpy())
ortvalue2 = ort.OrtValue.ortvalue_from_numpy(feature_lengths.numpy())

input_name = session.get_inputs()[0].name
input2_name = session.get_inputs()[1].name
label_name = session.get_outputs()[0].name

print(input_name)
print(input2_name)
print(label_name)

result = session.run([label_name], { input_name: ortvalue, input2_name: ortvalue2 })
```

here is the output I get:

> torch.Size([3, 222, 13])
> torch.Size([3])
> inputs
> input_lenghts
> logits
> 2024-03-28 10:26:00.4106034 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/conformer_/conformer_layers.0/self_attn/Reshape_4' Status Message: D:\bld\onnxruntime_1710148767998\work\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:45 onnxruntime::ReshapeHelper::ReshapeHelper input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{222,3,512}, requested shape:{1,24,64}
> 
> Traceback (most recent call last):
>   File "..\pt-conformer-onnx-test-output.py", line 68, in <module>
>     result = session.run([label_name], { input_name: ortvalue, input2_name: ortvalue2 })
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Conda\envs\torch\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
>     return self._sess.run(output_names, input_feed, run_options)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/conformer_/conformer_layers.0/self_attn/Reshape_4' Status Message: D:\bld\onnxruntime_1710148767998\work\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:45 onnxruntime::ReshapeHelper::ReshapeHelper input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{222,3,512}, requested shape:{1,24,64}
> 

I've checked the model configuration via https://netron.app/ and looks like that inputs and outputs of the model are formed properly. However, there is an issue in internal layers structure.

### Versions

> PyTorch version: 2.2.1
> Is debug build: False
> CUDA used to build PyTorch: 12.1
> ROCM used to build PyTorch: N/A
> 
> OS: Майкрософт Windows 10 Pro
> GCC version: Could not collect
> Clang version: Could not collect
> CMake version: version 3.28.3
> Libc version: N/A
> 
> Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)] (64-bit runtime)
> Python platform: Windows-10-10.0.19044-SP0
> Is CUDA available: True
> CUDA runtime version: Could not collect
> CUDA_MODULE_LOADING set to: LAZY
> GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
> Nvidia driver version: 551.61
> cuDNN version: Could not collect
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> CPU:
> Architecture=9
> CurrentClockSpeed=3593
> DeviceID=CPU0
> Family=107
> L2CacheSize=4096
> L2CacheSpeed=
> Manufacturer=AuthenticAMD
> MaxClockSpeed=3593
> Name=AMD Ryzen 7 3700X 8-Core Processor
> ProcessorType=3
> Revision=28928
> 
> Versions of relevant libraries:
> [pip3] numpy==1.26.4
> [pip3] onnx==1.15.0
> [pip3] onnxruntime==1.17.1
> [pip3] onnxscript==0.1.0.dev20240315
> [pip3] torch==2.2.1
> [pip3] torchaudio==2.2.1
> [pip3] torchvision==0.17.1
> [conda] blas                      1.0                         mkl
> [conda] mkl                       2023.1.0         h6b88ed4_46358
> [conda] mkl-service               2.4.0           py312h2bbff1b_1
> [conda] mkl_fft                   1.3.8           py312h2bbff1b_0
> [conda] mkl_random                1.2.4           py312h59b6b97_0
> [conda] numpy                     1.26.4          py312hfd52020_0
> [conda] numpy-base                1.26.4          py312h4dde369_0
> [conda] pytorch                   2.2.1           py3.12_cuda12.1_cudnn8_0    pytorch
> [conda] pytorch-cuda              12.1                 hde6ce7c_5    pytorch
> [conda] pytorch-mutex             1.0                        cuda    pytorch
> [conda] torchaudio                2.2.1                    pypi_0    pypi
> [conda] torchvision               0.17.1                   pypi_0    pypi

**Comment by FominArtmind** [comment]
Closing as #122956 desribing the same issue using just the library Conformer model
