### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by WangHHY19931001** [pytorch/pytorch#122864]
### 🐛 Describe the bug

import torch
import torchaudio
from torch import nn

class DataCov(nn.Module):
    def __init__(self):
        super(DataCov, self).__init__()

        self.transform = nn.Sequential(
            torchaudio.transforms.MelSpectrogram(sample_rate=48000, n_fft=1536, hop_length=768, f_min=20, f_max=20000)
        )

    def forward(self, x1):
        return self.transform(x1)

def export_datacov_onnx(path):
    model = DataCov()
    model.eval()
    model = torch.jit.script(model)
    x = torch.randn((1, 48000 * 12), requires_grad=True)
    args = (x,)
    torch.onnx.dynamo_export(model, args, path, export_params=True, opset_version=18)

if __name__ == '__main__':
    #export_datacov_script("DataCov.pt")
    #export_qanet_script("fun3.pth", "QANet.pt")
    export_datacov_onnx('DataCov.onnx')

### Versions

collect_env.py 
Collecting environment information...
PyTorch version: 2.4.0.dev20240326
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (Rev5, Built by MSYS2 project) 13.1.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] onnx==1.14.0
[pip3] onnxruntime==1.15.1
[pip3] onnxscript==0.1.0.dev20240328
[pip3] torch==2.1.0.dev20230810+cpu
[pip3] torchaudio==2.1.0.dev20230810+cpu
[pip3] torchvision==0.16.0.dev20230810+cpu
[conda] blas                      1.0                         mkl    defaults
[conda] cpuonly                   2.0                           0    pytorch-nightly
[conda] mkl                       2021.4.0           haa95532_640    defaults
[conda] mkl-service               2.4.0           py311h2bbff1b_0    defaults
[conda] mkl_fft                   1.3.1           py311h743a336_0    defaults
[conda] mkl_random                1.2.2           py311heda8569_0    defaults
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-base                1.24.3          py311h877bb12_0    defaults
[conda] pytorch                   2.4.0.dev20240326    py3.11_cpu_0    pytorch-nightly
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     2.1.0.dev20230810+cpu          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230810+cpu          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230810+cpu          pypi_0    pypi

**Comment by WangHHY19931001** [comment]
{
 "runs":[
  {
   "tool":{
    "driver":{
     "name":"torch.onnx.dynamo_export",
     "contents":[
      "localizedData",
      "nonLocalizedData"
     ],
     "language":"en-US",
     "rules":[],
     "version":"2.4.0.dev20240326"
    }
   },
   "language":"en-US",
   "newlineSequences":[
    "\r\n",
    "\n"
   ],
   "results":[]
  }
 ],
 "version":"2.1.0",
 "schemaUri":"https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/schemas/sarif-schema-2.1.0.json"
}

**Comment by WangHHY19931001** [comment]
C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\exporter.py:137: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\exporter.py", line 1457, in dynamo_export
    ).export()
      ^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\exporter.py", line 1200, in export
    graph_module = self.options.fx_tracer.generate_fx(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\fx\dynamo_graph_extractor.py", line 213, in generate_fx
    graph_module, graph_guard = torch._dynamo.export(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\_dynamo\eval_frame.py", line 1251, in inner
    result_traced = opt_f(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\_dynamo\eval_frame.py", line 409, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\_dynamo\external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\fx\dynamo_graph_extractor.py", line 168, in wrapped
    return output_adapter.apply(model_func(*args, **kwargs), model=model)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: forward() expected at most 2 argument(s) but received 5 argument(s). Declaration: forward(__torch__.module.DataCov self, Tensor x1) -> Tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\e\ai_mos_local\yy-aimos\本地化mos算分开发指引\模型转换工具\main.py", line 44, in <module>
    export_datacov_onnx('DataCov.onnx')
  File "E:\e\ai_mos_local\yy-aimos\本地化mos算分开发指引\模型转换工具\main.py", line 38, in export_datacov_onnx
    torch.onnx.dynamo_export(model, args, path, export_params=True, opset_version=18)
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\exporter.py", line 1468, in dynamo_export
    raise OnnxExporterError(
torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues
