### ISSUE TITLE
Tracker for Adagrad+SGD sparse tests failing with dynamo

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#123147]
### 🐛 Describe the bug

```
PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_rosenbrock_sparse_with_lrsched_False_SGD_cpu_float64
```

with_lrsched can be False or True, SGD or Adagrad, cpu or cuda

They all fail with something similar to:
```
======================================================================
FAIL: test_rosenbrock_sparse_with_lrsched_False_SGD_cpu_float64 (__main__.TestOptimRenewedCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 211, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 265, in test_rosenbrock_sparse
    all_optim_inputs = _get_optim_inputs_including_global_cliquey_kwargs(
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 368, in torch_dynamo_resume_in_test_rosenbrock_sparse_at_265
    self.assertEqual(params, params_c, atol=5e-6, rtol=5e-6)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 3624, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 2 (50.0%)
Greatest absolute difference: 0.6912000179290771 at index (1,) (up to 5e-06 allowed)
Greatest relative difference: 0.4521193206310272 at index (1,) (up to 5e-06 allowed)

The failure occurred for item [0]

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_rosenbrock_sparse_with_lrsched_False_SGD_cpu_float64

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

### Versions

on main, after I land #123146 haha

**Comment by IvanKobzarev** [comment]
Doing issue scrapping, test passes, closing
```
PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_rosenbrock_sparse_with_lrsched_False_SGD_cpu_float64
```
