### ISSUE TITLE
error LNK2019: unresolved external symbol "int const THP_PyOpcode_Caches_size"

### ISSUE THREAD

**Issue by ozanMSFT** [pytorch/pytorch#123190]
### 🐛 Describe the bug

**Describe the bug:**
Nightly builds for Windows are being failed. 
It looks like happening for both `Python 3.11` and `Python 3.12`

**Nightly builds:**
https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50

---

**Error message:**

**Short form:**
```
error LNK2019: unresolved external symbol "unsigned char const * const THP_PyOpcode_Caches"
```

**Long form:**
```
FAILED: bin/torch_python.dll lib/torch_python.lib 
cmd.exe /C "cd . && %BUILD_PREFIX%\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\torch\CMakeFiles\torch_python.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_python.rsp  /out:bin\torch_python.dll /implib:lib\torch_python.lib /pdb:bin\torch_python.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO  /NODEFAULTLIB:LIBCMT.LIB  -WHOLEARCHIVE:C:/cb/pytorch_1000000000000/work/build/lib/onnx.lib  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_python.rsp /out:bin\torch_python.dll /implib:lib\torch_python.lib /pdb:bin\torch_python.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT.LIB -WHOLEARCHIVE:C:/cb/pytorch_1000000000000/work/build/lib/onnx.lib /MANIFEST /MANIFESTFILE:bin\torch_python.dll.manifest" failed (exit code 1120) with the following output:
   Creating library lib\torch_python.lib and object lib\torch_python.exp
init.cpp.obj : error LNK2019: unresolved external symbol "unsigned char const * const THP_PyOpcode_Caches" (?THP_PyOpcode_Caches@@3PEBEEB) referenced in function "void __cdecl torch::dynamo::`dynamic initializer for '_PyOpcode_Caches_vec''(void)" (??__E_PyOpcode_Caches_vec@dynamo@torch@@YAXXZ)
  Hint on symbols that are defined and could potentially match:
    THP_PyOpcode_Caches
init.cpp.obj : error LNK2019: unresolved external symbol "int const THP_PyOpcode_Caches_size" (?THP_PyOpcode_Caches_size@@3HB) referenced in function "void __cdecl torch::dynamo::`dynamic initializer for '_PyOpcode_Caches_vec''(void)" (??__E_PyOpcode_Caches_vec@dynamo@torch@@YAXXZ)
  Hint on symbols that are defined and could potentially match:
    THP_PyOpcode_Caches_size
bin\torch_python.dll : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.
-- Building version 2.4.0.dev20240402
cmake -GNinja -D!EXITCODE=00000000 -DBUILD_ENVIRONMENT=windows-binary-conda -DBUILD_JNI=OFF -DBUILD_PLATFORM=win-64 -DBUILD_PREFIX=%BUILD_PREFIX% -DBUILD_PYTHON=True -DBUILD_PYTHONLESS= -DBUILD_TEST=True -DCMAKE_ARGS= -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR=Ninja -DCMAKE_INSTALL_PREFIX=C:\cb\PYTORC~1\work\torch -DCMAKE_PREFIX_PATH=C:\cb\PYTORC~1\_h_env\Lib\site-packages -DINSTALL_TEST=0 -DJAVA_HOME= -DNUMPY_INCLUDE_DIR=C:\cb\PYTORC~1\_h_env\Lib\site-packages\numpy\core\include -DPYTHON_EXECUTABLE=C:\cb\PYTORC~1\_h_env\python.exe -DPYTHON_INCLUDE_DIR=C:\cb\PYTORC~1\_h_env\Include -DPYTHON_LIBRARY=C:\cb\PYTORC~1\_h_env/libs/python311.lib -DTORCH_BUILD_VERSION=2.4.0.dev20240402 -DUSE_CUDA=0 -DUSE_FBGEMM=1 -DUSE_GLOO_WITH_OPENSSL=ON -DUSE_GOLD_LINKER=ON -DUSE_NUMPY=True -DUSE_SCCACHE=1 C:\cb\PYTORC~1\work
cmake --build . --target install --config Release -- -j 12
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\deprecations.py", line 70, in inner
    return func(*args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\cli\main_build.py", line 589, in main
    execute(sys.argv[1:])
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\cli\main_build.py", line 568, in execute
    outputs = api.build(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\api.py", line 253, in build
    return build_tree(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\build.py", line 3804, in build_tree
    packages_from_this = build(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\build.py", line 2629, in build
    windows.build(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\windows.py", line 341, in build
    check_call_env(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.11_075618\conda\lib\site-packages\conda_build\utils.py", line 427, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
```

### Versions

[failure] Binary Windows
The following jobs errored out:
[windows-binary-conda / conda-py3_11-cpu-build](https://github.com/pytorch/pytorch/actions/runs/8519099984/job/23332450646)
[windows-binary-conda / conda-py3_11-cuda11_8-build](https://github.com/pytorch/pytorch/actions/runs/8519099984/job/23332453272)
[windows-binary-conda / conda-py3_11-cuda12_1-build](https://github.com/pytorch/pytorch/actions/runs/8519099984/job/23332451527)
[windows-binary-conda / conda-py3_12-cpu-build](https://github.com/pytorch/pytorch/actions/runs/8519099984/job/23332453836)
[windows-binary-conda / conda-py3_12-cuda11_8-build](https://github.com/pytorch/pytorch/actions/runs/8519099984/job/23332452405)
[windows-binary-conda / conda-py3_12-cuda12_1-build](https://github.com/pytorch/pytorch/actions/runs/8519099984/job/23332453546)
[windows-binary-wheel / wheel-py3_11-cpu-build](https://github.com/pytorch/pytorch/actions/runs/8519099959/job/23332453573)
[windows-binary-wheel / wheel-py3_11-cuda11_8-build](https://github.com/pytorch/pytorch/actions/runs/8519099959/job/23332452635)
[windows-binary-wheel / wheel-py3_11-cuda12_1-build](https://github.com/pytorch/pytorch/actions/runs/8519099959/job/23332450031)
[windows-binary-wheel / wheel-py3_12-cpu-build](https://github.com/pytorch/pytorch/actions/runs/8519099959/job/23332451600)
[windows-binary-wheel / wheel-py3_12-cuda11_8-build](https://github.com/pytorch/pytorch/actions/runs/8519099959/job/23332454172)
[windows-binary-wheel / wheel-py3_12-cuda12_1-build](https://github.com/pytorch/pytorch/actions/runs/8519099959/job/23332450343)

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
@atalman can this be closed as fix just merged?
