### ISSUE TITLE
optim direction tests fail on dynamo due to it specializing on the init_value

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#123202]
### 🐛 Describe the bug

I spent quite a while trying to minimize the test to a repro but failed :/ The best repro is:

1. Remove the potential skip for test_param_group_with_lrscheduler_goes_right_direction in common_optimizers.py under SGD/Adam

2. Run the test:
```
PYTORCH_TEST_WITH_DYNAMO=1  python test/test_optim.py -k test_param_group_with_lrscheduler_goes_right_direction_SGD
```

The reason SGD and Adam fail (and not the others) is because they both run for more than one iteration within the test.

BTW I suspect this is why the other tests still fail even though the closure issue is complete cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @mlazos 

### Error logs

```
======================================================================
FAIL: test_param_group_with_lrscheduler_goes_right_direction_SGD_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 206, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 199, in test_param_group_with_lrscheduler_goes_right_direction
    self.assertLess(closure().item(), initial_value)
AssertionError: 10.20158863067627 not less than 10.20158863067627

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_param_group_with_lrscheduler_goes_right_direction_SGD_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 2 tests in 22.902s

FAILED (failures=2)
```

### Minified repro

The test looks like:
```
@optims(optim_db, dtypes=[torch.float32])
    def test_param_group_with_lrscheduler_goes_right_direction(self, device, dtype, optim_info):
        optim_cls = optim_info.optim_cls

        for schedulers_c in optim_info.scheduler_inputs:
            weight = Parameter(torch.randn((10, 5), device=device, dtype=dtype))
            bias = Parameter(torch.randn((10), device=device, dtype=dtype))
            inpt = torch.randn(5, device=device, dtype=dtype)

            optimizer = optim_cls([{"params": [weight]}, {"params": [bias], "lr": 0.01}])
            schedulers = [scheduler_c(optimizer) for scheduler_c in schedulers_c]

            def closure():
                optimizer.zero_grad()
                loss = (weight.mv(inpt) + bias).pow(2).sum()
                loss.backward()
                if optim_info.only_supports_sparse_grads:
                    # For this test, we naively convert the Tensor layout, which we know does
                    # NOT represent the expected use case for optims like SparseAdam!
                    weight.grad = weight.grad.to_sparse()
                    bias.grad = bias.grad.to_sparse()
                return loss

			>>> WHAT I THINK IS WRONG: every iteration after the first, initial_value is somehow the last iteration's final value
            initial_value = closure().item()    
            >>> end.

            for _ in range(20):
                loss = optimizer.step(closure)
                for scheduler in schedulers:
                    if isinstance(scheduler, ReduceLROnPlateau):
                        scheduler.step(loss)
                    else:
                        scheduler.step()

            self.assertLess(closure().item(), initial_value)
```

At the same time, I tried minimizing to something to that effect but the following script does not fail! Confused. 
```
import torch

@torch.compile(backend="eager")
def f():
    for _ in range(4):
        i = torch.randn(2, 3) # torch.tensor([[400], [500]], dtype=torch.float32)
        j = torch.randn(2, 3) # torch.tensor([[200], [300]], dtype=torch.float32)
        def c():
            print("graph break")
            loss = (i + j).sum()
            return loss
        init_val = c().item()
        def s():
            print("step")
            i.sub_(1)
            j.sub_(1)
        for _ in range(3):
            c()
            s()
        assert c().item() < init_val

    f()
```

### Versions

on main

**Comment by mlazos** [comment]
These are passing now
