### ISSUE TITLE
running Kornia.morphology.opening and trying to export onnx

### ISSUE THREAD

**Issue by leohafi** [pytorch/pytorch#123287]
### 🐛 Describe the bug

```
from pathlib import Path
import torch
from torch import nn
import kornia
import onnx
from onnxsim import simplify
import blobconverter

# Name of the model
name = 'threshold'

# Define the model class
class Model(nn.Module):

    def forward(self, image):
        kernel_size = (22, 22)
        kernel = torch.ones(kernel_size)
        blob = kornia.morphology.opening(image, kernel)
        return blob


# Define the expected input shape (dummy input)
shape = (1, 3, 300, 300)  # Example input shape
model = Model()
X = torch.ones(shape, dtype=torch.float32)

# Create output directory if it doesn't exist
path = Path("out/")
path.mkdir(parents=True, exist_ok=True)

# Export the model to ONNX format
onnx_path = str(path / (name + '.onnx'))
print(f"Exporting model to {onnx_path}")
torch.onnx.export(
    model,
    X,
    onnx_path,
    opset_version=12,
    do_constant_folding=True,
)

# Simplify the ONNX model
onnx_simplified_path = str(path / (name + '_simplified.onnx'))
print(f"Simplifying model to {onnx_simplified_path}")
onnx_model = onnx.load(onnx_path)
model_simp, check = simplify(onnx_model)
onnx.save(model_simp, onnx_simplified_path)

# Convert ONNX model to blob format
blobconverter.from_onnx(
    model=onnx_simplified_path,
    data_type="FP16",
    shaves=6,
    use_cache=False,
    output_dir="../models",
    optimizer_params=[]
)
```
Trouble exporting  onnx as the code throws following error :

```C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\_internal\jit_utils.py:307: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
Traceback (most recent call last):
  File "C:\Users\lh\Documents\DEV\OAK Projects\depthai-experiments\gen2-custom-models\generate_model\kornia_threashold.py", line 36, in <module>
    torch.onnx.export(
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py", line 1613, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py", line 1957, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\symbolic_opset12.py", line 331, in unfold
    return opset9.unfold(g, input, dimension, const_size, const_step)
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\symbolic_opset9.py", line 3149, in unfold
    return symbolic_helper._unimplemented(
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\symbolic_helper.py", line 612, in _unimplemented
    _onnx_unsupported(f"{op}, {msg}", value)
  File "C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\symbolic_helper.py", line 623, in _onnx_unsupported
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator Unfold, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues  [Caused by the value '31 defined in (%31 : Float(*, *, *, *, strides=[309123, 103041, 321, 1], requires_grad=0, device=cpu) = onnx::Pad[mode="constant"](%image, %29, %30), scope: __main__.Model:: # C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\functional.py:4495:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Pad'.] 
    (node defined in C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\functional.py(4495): pad
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\kornia\morphology\morphology.py(174): erosion
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\kornia\morphology\morphology.py(259): opening
C:\Users\lh\Documents\DEV\OAK Projects\depthai-experiments\gen2-custom-models\generate_model\kornia_threashold.py(20): forward
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\modules\module.py(1501): _slow_forward
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\modules\module.py(1520): _call_impl
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\modules\module.py(1511): _wrapped_call_impl
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\jit\_trace.py(129): wrapper
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\jit\_trace.py(138): forward
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\modules\module.py(1520): _call_impl
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\modules\module.py(1511): _wrapped_call_impl
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\jit\_trace.py(1296): _get_trace_graph
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py(915): _trace_and_get_graph_from_model
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py(1011): _create_jit_graph
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py(1135): _model_to_graph
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py(1613): _export
C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\onnx\utils.py(516): export
C:\Users\lh\Documents\DEV\OAK Projects\depthai-experiments\gen2-custom-models\generate_model\kornia_threashold.py(36): <module>
)

    Inputs:
        #0: image defined in (%image : Float(1, 3, 300, 300, strides=[270000, 90000, 300, 1], requires_grad=0, device=cpu) = prim::Param()
    )  (type 'Tensor')
        #1: 29 defined in (%29 : Long(8, strides=[1], device=cpu) = onnx::Cast[to=7](%28), scope: __main__.Model:: # C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\functional.py:4495:0
    )  (type 'Tensor')
        #2: 30 defined in (%30 : Float(device=cpu) = onnx::Constant[value={10000}](), scope: __main__.Model:: # C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\functional.py:4495:0
    )  (type 'Tensor')
    Outputs:
        #0: 31 defined in (%31 : Float(*, *, *, *, strides=[309123, 103041, 321, 1], requires_grad=0, device=cpu) = onnx::Pad[mode="constant"](%image, %29, %30), scope: __main__.Model:: # C:\Users\lh\anaconda3\envs\depthai-experiments\lib\site-packages\torch\nn\functional.py:4495:0
    )  (type 'Tensor')
```

How can i fix this?
Thanks for your help :)

### Versions
```

PyTorch version: 2.2.2+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro for Workstations
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Quadro RTX 5000 with Max-Q Design
Nvidia driver version: 551.61
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnx==1.16.0
[pip3] onnx-simplifier==0.4.36
[pip3] onnxruntime==1.17.1
[pip3] torch==2.2.2
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
```

**Comment by thiagocrepaldi** [comment]
torch.onn.export does not support unfold (aka im2col) and there is no plan to support it

try using `torch.onnx.dynamo_export` isntead and let us know if that doesnt work for you
