### ISSUE TITLE
Dynamo fails on `__setstate__` of optimizers

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#123400]
### 🐛 Describe the bug

Looks like dynamo fails when tracing `__setstate__` of optimizers. I've disabled dynamo on this for now, there isn't much to gain from tracing it since it doesn't appear in the middle of a model. Keeping this issue to track this.

### Error logs

======================================================================
ERROR: test_deepcopy_copies_all_public_attrs_SGD_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/mlazos/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/data/users/mlazos/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/data/users/mlazos/pytorch/torch/testing/_internal/common_device_type.py", line 432, in instantiated_test
    raise rte
  File "/data/users/mlazos/pytorch/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/mlazos/pytorch/torch/testing/_internal/common_optimizers.py", line 217, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/mlazos/pytorch/test/test_optim.py", line 1529, in test_deepcopy_copies_all_public_attrs
    all_optim_inputs = _get_optim_inputs_including_global_cliquey_kwargs(device, dtype, optim_info, skip=("differentiable",))
  File "/data/users/mlazos/pytorch/test/test_optim.py", line 1533, in torch_dynamo_resume_in_test_deepcopy_copies_all_public_attrs_at_1529
    p.grad = torch.rand_like(p)
  File "/data/users/mlazos/pytorch/test/test_optim.py", line 1553, in torch_dynamo_resume_in_test_deepcopy_copies_all_public_attrs_at_1533
    self.assertEqual(getPublicAttrs(optimizer), getPublicAttrs(deepcopy(optimizer)))
  File "/home/mlazos/.conda/envs/pytorch-3.10/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mlazos/.conda/envs/pytorch-3.10/lib/python3.10/copy.py", line 273, in _reconstruct
    y.__setstate__(state)
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 939, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 802, in _convert_frame
    result = inner_convert(
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/home/mlazos/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 713, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 686, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/mlazos/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 541, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/mlazos/pytorch/torch/_dynamo/bytecode_transformation.py", line 1078, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/data/users/mlazos/pytorch/torch/_dynamo/convert_frame.py", line 503, in transform
    tracer.run()
  File "/data/users/mlazos/pytorch/torch/_dynamo/symbolic_convert.py", line 2202, in run
    super().run()
  File "/data/users/mlazos/pytorch/torch/_dynamo/symbolic_convert.py", line 843, in run
    while self.step():
  File "/data/users/mlazos/pytorch/torch/_dynamo/symbolic_convert.py", line 757, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/mlazos/pytorch/torch/_dynamo/symbolic_convert.py", line 481, in wrapper
    return inner_fn(self, inst)
  File "/data/users/mlazos/pytorch/torch/_dynamo/symbolic_convert.py", line 1224, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/mlazos/pytorch/torch/_dynamo/symbolic_convert.py", line 697, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/builtin.py", line 939, in call_function
    return handler(tx, args, kwargs)
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/builtin.py", line 705, in <lambda>
    tx, [v.realize() for v in args], kwargs
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/builtin.py", line 705, in <listcomp>
    tx, [v.realize() for v in args], kwargs
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/lazy.py", line 57, in realize
    self._cache.realize()
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/lazy.py", line 24, in realize
    self.vt = VariableBuilder(tx, self.source)(self.value)
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/builder.py", line 275, in __call__
    vt = self._wrap(value)
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/builder.py", line 669, in _wrap
    return OptimizerVariable(value, source=self.source)
  File "/data/users/mlazos/pytorch/torch/_dynamo/variables/optimizer.py", line 74, in __init__
    for group in self.value.param_groups:
torch._dynamo.exc.InternalTorchDynamoError: 'SGD' object has no attribute 'param_groups'

from user code:
   File "/data/users/mlazos/pytorch/torch/optim/sgd.py", line 37, in __setstate__
    super().__setstate__(state)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_deepcopy_copies_all_public_attrs_SGD_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

### Minified repro

Remove one of the torch._disable decorators and run:

PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_deepcopy_copies_all_public_attrs

### Versions

nightly 1ea6d3a9b4e97f7278b47a3d27f4926774a14bfa

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by mlazos** [comment]
Fixed with https://github.com/pytorch/pytorch/pull/123406
