### ISSUE TITLE
Enable inlining nn modules for test/dynamo/test_modules.py 

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#123589]
TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1 pytest test/dynamo/test_modules.py 
```
=============================================================================== short test summary info ================================================================================
FAILED [0.4562s] test/dynamo/test_modules.py::NNModuleTests::test_call_fn_with_non_const_inputs_safe - AssertionError: Unexpectedly found a <class 'torch.nn.parameter.Parameter'> in the inputs.
FAILED [0.0078s] test/dynamo/test_modules.py::NNModuleTests::test_children - torch._dynamo.exc.Unsupported: call_method SetVariable() __setitem__ (UnspecializedNNModuleVariable(), ConstantVariable()) {}
FAILED [0.0129s] test/dynamo/test_modules.py::NNModuleTests::test_lazy_module_no_cls_to_become - torch._dynamo.exc.Unsupported: call_function args: TensorVariable() UnspecializedNNModuleVariable(Parameter) 
FAILED [0.0058s] test/dynamo/test_modules.py::NNModuleTests::test_module_class_method - torch._dynamo.exc.Unsupported: __self__ mismatch for bound method
FAILED [0.0060s] test/dynamo/test_modules.py::NNModuleTests::test_module_comparison - torch._dynamo.exc.Unsupported: call_method GetAttrVariable(UnspecializedNNModuleVariable(ModuleComparison), encoder_layers) __iter__ () {}
FAILED [0.1837s] test/dynamo/test_modules.py::NNModuleTests::test_modulelist - torch._dynamo.exc.Unsupported: call_method GetAttrVariable(UnspecializedNNModuleVariable(ModuleList), _modules) __len__ () {}
FAILED [0.0080s] test/dynamo/test_modules.py::NNModuleTests::test_named_children - torch._dynamo.exc.Unsupported: call_method SetVariable() __setitem__ (UnspecializedNNModuleVariable(), ConstantVariable()) {}
FAILED [0.0099s] test/dynamo/test_modules.py::NNModuleTests::test_parameters3 - torch._dynamo.exc.Unsupported: call_method SetVariable() __setitem__ (UnspecializedNNModuleVariable(), ConstantVariable()) {}
FAILED [0.0048s] test/dynamo/test_modules.py::NNModuleTests::test_super_class_method - torch._dynamo.exc.Unsupported: __self__ mismatch for bound method
FAILED [0.0964s] test/dynamo/test_modules.py::OptimizedModuleTest::test_cache_size_limit_on_guarded_nn_modules - AssertionError: Scalars are not equal!
FAILED [0.1500s] test/dynamo/test_modules.py::OptimizedModuleTest::test_hooks_skip_guards - AssertionError: AssertionError not raised
FAILED [0.0940s] test/dynamo/test_modules.py::OptimizedModuleTest::test_no_guard_on_torch_nn_modules - AssertionError: Scalars are not equal!
FAILED [0.0368s] test/dynamo/test_modules.py::OptimizedModuleTest::test_no_op_assignment - AssertionError: Scalars are not equal!
FAILED [0.0454s] test/dynamo/test_modules.py::OptimizedModuleTest::test_no_recompile_on_nn_guarded_modules - torch._dynamo.exc.RecompileError: Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_modules.py:1688
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by laithsakka** [comment]
I was looking at the first item in the issues. The problem happen whenever there is a member of the nn module class
that is tensor that is use in the forward function

ex:
```
 class FailingInlined(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.t = torch.randn([3, 10, 10])

            def forward(self, x):
                return x*self.t

        mod = FailingInlined()
        rx = torch.randn([3, 10, 10])
        real = mod(rx)
        graph, _ = torch._dynamo.export(mod)(rx)
```

In that case the function rewrite_signature throws complaining about that tensor (t is this code above)
```
Traceback (most recent call last):
  File "/data/users/lsakka/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2741, in wrapper
    method(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/test/dynamo/test_modules.py", line 1534, in test_call_fn_with_non_const_inputs_safe
    graph, _ = torch._dynamo.export(mod)(rx)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 1343, in inner
    graph = rewrite_signature(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 935, in rewrite_signature
    matched_input_elements_positions = produce_matching(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 926, in produce_matching
    raise AssertionError(
AssertionError: Unexpectedly found a <class 'torch.Tensor'> in the inputs.
Please file an issue along with a paste of the logs from TORCH_LOGS="+export"
```
I will investigate more tomorrow.

**Comment by anijain2305** [comment]
Dont use export for now. Export has other issues when it comes to inlining nn modules. Use torch.compile

**Comment by laithsakka** [comment]
> Dont use export for now. Export has other issues when it comes to inlining nn modules. Use torch.compile

I see the failing test used to use export, would it make sense to add @disableNNInline or something to tests that we know they would fail with nn module inline but we do not care much about them atm?

**Comment by laithsakka** [comment]
re-running after rebasing on @anijain2305 changes we have only one issue:
FAILED [0.6191s] test/dynamo/test_modules.py::NNModuleTests::test_call_fn_with_non_const_inputs_safe - AssertionError: Unexpectedly found a <class 'torch.nn.parameter.Parameter'> in the inputs.
Which is the one related to export.

**Comment by laithsakka** [comment]
Mitigated by disabling inlining nn modules for export
