### ISSUE TITLE
RuntimeError: Unrecognized CachingAllocator option: expandable_segments

### ISSUE THREAD

**Issue by await-you** [pytorch/pytorch#123505]
###The errors are as follows:  the code run very well previously,but it dose not work suddenly. i would appreciated if you could kindly give me some advice about it.

use cuda & cudnn for acceleration!
the gpu id is: [2, 3]
hr npy datas have already been prepared!, hr: 800
lr npy datas have already been prepared!, lr: 800
select , set5 for evaluation! 
compile cuda source of 'pair_wise_distance' function...
NOTE: if you avoid this process, you make .cu file and compile it following https://pytorch.org/tutorials/advanced/cpp_extension.html
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model = utils.import_module('models.{}'.format(args.model)).create_model(args)
  File "/home/ziwen/SR_code/SPIN-main/utils.py", line 69, in import_module
    return importlib.import_module(name)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ziwen/SR_code/SPIN-main/models/spin.py", line 7, in <module>
    from .pair_wise_distance import PairwiseDistFunction
  File "/home/ziwen/SR_code/SPIN-main/models/pair_wise_distance.py", line 12, in <module>
    "pair_wise_distance", cpp_sources="", cuda_sources=source
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1445, in load_inline
    keep_intermediates=keep_intermediates)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1518, in _jit_compile
    is_standalone=is_standalone)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1619, in _write_ninja_file_and_build_library
    is_standalone=is_standalone)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 2014, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1767, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability(i)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
    prop = get_device_properties(device)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: expandable_segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    raise ValueError('not supported model type! or something')
ValueError: not supported model type! or something
(test) ziwen@server103:~/SR_code/SPIN-main$ gpustat 
server103                   Sat Apr  6 23:07:13 2024  535.129.03
[0] NVIDIA GeForce RTX 4090 | 45'C, 100 % | 18821 / 24564 MB | lyx(18416M)
[1] NVIDIA GeForce RTX 4090 | 46'C, 100 % | 19399 / 24564 MB | lyx(18994M)
[2] NVIDIA GeForce RTX 4090 | 30'C,   0 % |   352 / 24564 MB |
[3] NVIDIA GeForce RTX 4090 | 30'C,   0 % |   352 / 24564 MB |
(test) ziwen@server103:~/SR_code/SPIN-main$ rm -rf ~/.config/Code/Cache/*
(test) ziwen@server103:~/SR_code/SPIN-main$ sh run_script.sh 
use cuda & cudnn for acceleration!
the gpu id is: [2, 3]
hr npy datas have already been prepared!, hr: 800
lr npy datas have already been prepared!, lr: 800
select , set5 for evaluation! 
compile cuda source of 'pair_wise_distance' function...
NOTE: if you avoid this process, you make .cu file and compile it following https://pytorch.org/tutorials/advanced/cpp_extension.html
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model = utils.import_module('models.{}'.format(args.model)).create_model(args)
  File "/home/ziwen/SR_code/SPIN-main/utils.py", line 69, in import_module
    return importlib.import_module(name)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ziwen/SR_code/SPIN-main/models/spin.py", line 7, in <module>
    from .pair_wise_distance import PairwiseDistFunction
  File "/home/ziwen/SR_code/SPIN-main/models/pair_wise_distance.py", line 12, in <module>
    "pair_wise_distance", cpp_sources="", cuda_sources=source
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1445, in load_inline
    keep_intermediates=keep_intermediates)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1518, in _jit_compile
    is_standalone=is_standalone)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1619, in _write_ninja_file_and_build_library
    is_standalone=is_standalone)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 2014, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1767, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability(i)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
    prop = get_device_properties(device)
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/ziwen/miniconda3/envs/test/lib/python3.7/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: expandable_segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    raise ValueError('not supported model type! or something')
ValueError: not supported model type! or something

**Comment by ptrblck** [comment]
Could you check if PyTorch was downgraded by mistake, as the code fails [here](https://github.com/pytorch/pytorch/blob/1ea2f1eaa19176b8b5b778bb317203dc7f4fd3dc/c10/cuda/CUDAAllocatorConfig.cpp#L311) while `expandable_segments` is supported as seen [here](https://github.com/pytorch/pytorch/blob/1ea2f1eaa19176b8b5b778bb317203dc7f4fd3dc/c10/cuda/CUDAAllocatorConfig.cpp#L269)?

**Comment by pyh-129** [comment]
> Could you check if PyTorch was downgraded by mistake, as the code fails [here](https://github.com/pytorch/pytorch/blob/1ea2f1eaa19176b8b5b778bb317203dc7f4fd3dc/c10/cuda/CUDAAllocatorConfig.cpp#L311) while `expandable_segments` is supported as seen [here](https://github.com/pytorch/pytorch/blob/1ea2f1eaa19176b8b5b778bb317203dc7f4fd3dc/c10/cuda/CUDAAllocatorConfig.cpp#L269)?

hi I meet the same error when I use Mini-GPT4:

```
    from peft import (
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/peft/tuners/__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/peft/tuners/lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 225, in <module>
    class MatmulLtState:
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 247, in MatmulLtState
    formatB = F.get_special_format_str()
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/bitsandbytes/functional.py", line 269, in get_special_format_str
    major, _minor = torch.cuda.get_device_capability()
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/usr/local/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: `expandable_segments`
```

**Comment by bczzzz** [comment]
@await-you  Hello! I meet the same issue. Have you solved it? If resolved, can you share how?

**Comment by huguensjean** [comment]
Hello, has anyone manage to solve this issue?
![5gckvznVHGZFwf6](https://github.com/user-attachments/assets/44efe9c9-ca52-4594-b862-9c6098bbe736)

**Comment by redizzy** [comment]
hi
I meet the same issue
<img width="629" alt="75c8b3cab9e5803b132266141fb804c" src="https://github.com/user-attachments/assets/3a5b5326-86aa-41d7-9aa5-3546bd89f141">

**Comment by cdalinghaus** [comment]
In my case this was resolved by upgrading from torch 2.0.1 triton-2.0.0 to torch-2.4.1 triton-3.0.0
