### ISSUE TITLE
BrokenPipeError on "DataLoading and PreProcessing" tutorial

### ISSUE THREAD

**Issue by david2588e** [pytorch/pytorch#12358]
## To Reproduce

1. BrokenPipeError: [Errno 32] Broken pipe 
1.
1.

## Expected behavior

  File "C:\Users\Liu\Anaconda2\envs\py3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "C:\Users\Liu\Anaconda2\envs\py3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\Liu\Anaconda2\envs\py3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\Liu\Anaconda2\envs\py3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\Liu\Anaconda2\envs\py3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
**Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 348, in <module>
    main()
  File "collect_env.py", line 343, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 338, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 232, in get_env_info
    cudnn_version=get_cudnn_version(run_lambda),
  File "collect_env.py", line 112, in get_cudnn_version
    rc, out, _ = run_lambda(cudnn_cmd)
  File "collect_env.py", line 43, in run
    err = err.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)**

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):  
conda install pytorch -c pytorch
pip3 install torchvision

 - Build command you used (if compiling from source):
 - Python version: Python 3.7
 - CUDA/cuDNN version: 
CUDA Version 9.1.85

CUDA Patch Version 9.1.85.3

 - GPU models and configuration:  GTX 1060 
 - Any other relevant information:

**Comment by caiyingchun** [comment]
I meet the same problems. Would you please have the solution? Thank you!

**Comment by SsnL** [comment]
The errors don't fail anything. They are already fixed on master.
