### ISSUE TITLE
[TorchAO] fail to do fake_tensor_prop with freezing pass

### ISSUE THREAD

**Issue by Valentine233** [pytorch/pytorch#123522]
### 🐛 Describe the bug

We fail to do fake tensor propagation when using TorchAO quant with freezing pass. Actually, the number of frozen parameters is not as expected. For example, we have two linears L1 and L2. The frozen  parameters are supposed to be weight of L1, scale of L1, weight of L2 and scale of L2. But in fact, we only get two frozen parameters --- two qtensors. The tensor subclass `Int8DynamicallyQuantizedLinearWeight` in TorchAO is a qtensor, possessing `int_data` and `q_scales` as attributes. It seems to be some bugs in parameter flattening, mistaking qtensor of L1 as weight of L1, and qtensor of L2 as scale of L1.

Reproduced code with flag `TORCHINDUCTOR_FREEZING=1`:
```python
import torch
from torchao.quantization import quant_api
 
class M(torch.nn.Module):
    def __init__(
        self,
        use_bias,
        post_op_algo,
    ):
        super().__init__()
        self.linear1 = torch.nn.Linear(16, 16, use_bias)
        self.linear2 = torch.nn.Linear(16, 16, use_bias)
 
    def forward(self, x):
        temp = self.linear1(x)
        temp = self.linear2(temp)
 
        return temp
 
 
if __name__ == "__main__":
    bias = False
    mod = M(bias, "none").eval()
 
    v = torch.randn((3, 16))
    inputs = (v,)
 
    quant_api.change_linear_weights_to_int8_woqtensors(mod)
 
    ref_res = mod(*inputs)
 
    with torch.no_grad(), torch.cpu.amp.autocast():
        compiler_mode = torch.compile(mod)
        _ = compiler_mode(*inputs)
        output = compiler_mode(*inputs)
 
        print(torch.allclose(ref_res, output), flush=True)

```

Full traceback:
```
Traceback (most recent call last):
  File "/home/liaoxuan/pytorch_ao/test_ao.py", line 39, in <module>
    _ = compiler_mode(*inputs)
  File "/home/liaoxuan/pytorch_ao/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 942, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 805, in _convert_frame
    result = inner_convert(
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 402, in _convert_frame_assert
    return _compile(
  File "/home/liaoxuan/pytorch_ao/torch/_utils_internal.py", line 70, in wrapper_function
    return function(*args, **kwargs)
  File "/home/liaoxuan/anaconda3/envs/torchao/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 689, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 544, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/bytecode_transformation.py", line 1103, in transform_code_object
    transformations(instructions, code_options)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/convert_frame.py", line 506, in transform
    tracer.run()
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/symbolic_convert.py", line 2197, in run
    super().run()
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/symbolic_convert.py", line 847, in run
    while self.step():
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/symbolic_convert.py", line 757, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/symbolic_convert.py", line 2333, in RETURN_VALUE
    self._return(inst)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/symbolic_convert.py", line 2318, in _return
    self.output.compile_subgraph(
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/output_graph.py", line 961, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/liaoxuan/anaconda3/envs/torchao/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/output_graph.py", line 1175, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/output_graph.py", line 1248, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/output_graph.py", line 1229, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/liaoxuan/pytorch_ao/torch/__init__.py", line 1739, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/liaoxuan/anaconda3/envs/torchao/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/liaoxuan/pytorch_ao/torch/_inductor/compile_fx.py", line 1384, in compile_fx
    return aot_autograd(
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/backends/common.py", line 65, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/liaoxuan/pytorch_ao/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/liaoxuan/pytorch_ao/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 444, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/liaoxuan/pytorch_ao/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 649, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/liaoxuan/pytorch_ao/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 148, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/home/liaoxuan/pytorch_ao/torch/_inductor/compile_fx.py", line 1095, in fw_compiler_freezing
    opt_model, preserved_arg_indices = freeze(
  File "/home/liaoxuan/pytorch_ao/torch/_inductor/freezing.py", line 113, in freeze
    freezing_passes(aot_autograd_gm, aot_example_inputs)
  File "/home/liaoxuan/pytorch_ao/torch/_inductor/fx_passes/freezing_patterns.py", line 47, in freezing_passes
    fake_tensor_prop(gm, aot_example_inputs, True)
  File "/home/liaoxuan/pytorch_ao/torch/_inductor/compile_fx.py", line 363, in fake_tensor_prop
    FakeTensorProp(gm, mode=fake_mode).propagate_dont_convert_inputs(
  File "/home/liaoxuan/pytorch_ao/torch/fx/passes/fake_tensor_prop.py", line 73, in propagate_dont_convert_inputs
    return super().run(*args)
  File "/home/liaoxuan/pytorch_ao/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
  File "/home/liaoxuan/pytorch_ao/torch/fx/passes/fake_tensor_prop.py", line 36, in run_node
    result = super().run_node(n)
  File "/home/liaoxuan/pytorch_ao/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/fx/interpreter.py", line 274, in call_function
    return target(*args, **kwargs)
  File "/home/liaoxuan/pytorch_ao/torch/_ops.py", line 610, in __call__
    return self_._op(*args, **kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #1 'mat2'

While executing %mm : [num_users=1] = call_function[target=torch.ops.aten.mm.default](args = (%convert_element_type_2, %convert_element_type_default_1), kwargs = {})
Original traceback:
  File "/home/liaoxuan/pytorch_ao/test_ao.py", line 17, in forward
    temp = self.linear1(x)
```

Graph before replacing params:
```
def forward(self, arg0_1, arg1_1, arg2_1, arg3_1, arg4_1):
    view = torch.ops.aten.view.default(arg4_1, [-1, 16]);  arg4_1 = None
    convert_element_type_default_1 = torch.ops.prims.convert_element_type.default(arg0_1, torch.bfloat16);  arg0_1 = None
    convert_element_type_2 = torch.ops.prims.convert_element_type.default(view, torch.bfloat16);  view = None
    mm = torch.ops.aten.mm.default(convert_element_type_2, convert_element_type_default_1);  convert_element_type_2 = convert_element_type_default_1 = None
    mul = torch.ops.aten.mul.Tensor(mm, arg1_1);  mm = arg1_1 = None
    view_2 = torch.ops.aten.view.default(mul, [-1, 16]);  mul = None
    convert_element_type_default = torch.ops.prims.convert_element_type.default(arg2_1, torch.bfloat16);  arg2_1 = None
    convert_element_type_7 = torch.ops.prims.convert_element_type.default(view_2, torch.bfloat16);  view_2 = None
    mm_1 = torch.ops.aten.mm.default(convert_element_type_7, convert_element_type_default);  convert_element_type_7 = convert_element_type_default = None
    mul_1 = torch.ops.aten.mul.Tensor(mm_1, arg3_1);  mm_1 = arg3_1 = None
    return [mul_1]
```

Graph after replacing params:
-- Only replaced first two params here and expected to replace first four.
```
def forward(self, arg2_1, arg3_1, arg4_1):
    _frozen_param0 = self._frozen_param0
    _frozen_param1 = self._frozen_param1
    view = torch.ops.aten.reshape.default(arg4_1, [-1, 16]);  arg4_1 = None
    convert_element_type_default_1 = torch.ops.prims.convert_element_type.default(_frozen_param0, torch.bfloat16);  _frozen_param0 = None
    convert_element_type_2 = torch.ops.prims.convert_element_type.default(view, torch.bfloat16);  view = None
    mm = torch.ops.aten.mm.default(convert_element_type_2, convert_element_type_default_1);  convert_element_type_2 = convert_element_type_default_1 = None
    mul = torch.ops.aten.mul.Tensor(mm, _frozen_param1);  mm = _frozen_param1 = None
    view_2 = torch.ops.aten.reshape.default(mul, [-1, 16]);  mul = None
    convert_element_type_default = torch.ops.prims.convert_element_type.default(arg2_1, torch.bfloat16);  arg2_1 = None
    convert_element_type_7 = torch.ops.prims.convert_element_type.default(view_2, torch.bfloat16);  view_2 = None
    mm_1 = torch.ops.aten.mm.default(convert_element_type_7, convert_element_type_default);  convert_element_type_7 = convert_element_type_default = None
    mul_1 = torch.ops.aten.mul.Tensor(mm_1, arg3_1);  mm_1 = arg3_1 = None
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @leslie-fang-intel @jiong

### Versions

PyTorch: main 3beb9d85
TorchAO: main a7670be5

**Comment by Valentine233** [comment]
@eellison Hi, do you have any idea about the issue, and how could we fix it? Thanks!

**Comment by Valentine233** [comment]
@eellison hi, Ellison~ Have you got any update for this one?

**Comment by eellison** [comment]
I don't. @Valentine233 would you be able to take it?

**Comment by Valentine233** [comment]
> I don't. @Valentine233 would you be able to take it?

Sure. We will try to find a solution, and discuss with you later.

**Comment by Valentine233** [comment]
Fixed by the latest PyTorch and Torchao.
