### ISSUE TITLE
Better logs for improperly registered custom ops

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#123603]
Related to https://github.com/pytorch/pytorch/issues/95791, but with simpler examples.

Repro: https://github.com/pytorch/vision/compare/main...wwen/custom_ops_test

There are two issues:

The TORCH_LIBRARY registered custom op gives the following logs in the graph_breaks artifact:
```
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] Graph break: from user code at:
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/torchvision/playground.py", line 8, in fn2
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return torch.ops.torchvision.my_custom_op2(x)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] Traceback (most recent call last):
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1402, in _dispatch_impl
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     r = func(*args, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_ops.py", line 610, in __call__
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self_._op(*args, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] NotImplementedError: torchvision::my_custom_op2: attempted to run this operator with Meta tensors, but there was no abstract impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add an abstract impl.Please see the following doc for next steps: https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] 
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] During handling of the above exception, another exception occurred:
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] 
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] Traceback (most recent call last):
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1830, in run_node
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return node.target(*args, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_ops.py", line 870, in __call__
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self_._op(*args, **(kwargs or {}))
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/utils/_stats.py", line 20, in wrapper
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return fn(*args, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 840, in __torch_dispatch__
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self.dispatch(func, types, args, kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1185, in dispatch
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self._cached_dispatch_impl(func, types, args, kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 918, in _cached_dispatch_impl
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     output = self._dispatch_impl(func, types, args, kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1404, in _dispatch_impl
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return maybe_run_unsafe_fallback(not_implemented_error)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1387, in maybe_run_unsafe_fallback
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     raise UnsupportedOperatorException(func)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] torch._subclasses.fake_tensor.UnsupportedOperatorException: torchvision.my_custom_op2.default
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] 
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] The above exception was the direct cause of the following exception:
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] 
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] Traceback (most recent call last):
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1712, in get_fake_value
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     ret_val = wrap_fake_exception(
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1227, in wrap_fake_exception
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return fn()
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1713, in <lambda>
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     lambda: run_node(tx.output, node, args, kwargs, nnmodule)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1848, in run_node
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     raise RuntimeError(make_error_message(e)).with_traceback(
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1830, in run_node
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return node.target(*args, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_ops.py", line 870, in __call__
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self_._op(*args, **(kwargs or {}))
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/utils/_stats.py", line 20, in wrapper
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return fn(*args, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 840, in __torch_dispatch__
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self.dispatch(func, types, args, kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1185, in dispatch
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return self._cached_dispatch_impl(func, types, args, kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 918, in _cached_dispatch_impl
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     output = self._dispatch_impl(func, types, args, kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1404, in _dispatch_impl
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return maybe_run_unsafe_fallback(not_implemented_error)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_subclasses/fake_tensor.py", line 1387, in maybe_run_unsafe_fallback
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     raise UnsupportedOperatorException(func)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] RuntimeError: Failed running call_function torchvision.my_custom_op2(*(FakeTensor(..., size=(3, 3)),), **{}):
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] torchvision.my_custom_op2.default
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] 
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] During handling of the above exception, another exception occurred:
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] 
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] Traceback (most recent call last):
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/symbolic_convert.py", line 481, in wrapper
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return inner_fn(self, inst)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/symbolic_convert.py", line 1224, in CALL_FUNCTION
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     self.call_function(fn, args, {})
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/symbolic_convert.py", line 697, in call_function
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     self.push(fn.call_function(self, args, kwargs))
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/variables/torch.py", line 745, in call_function
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     tensor_variable = wrap_fx_proxy(
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/variables/builder.py", line 1352, in wrap_fx_proxy
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/variables/builder.py", line 1437, in wrap_fx_proxy_cls
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/utils.py", line 1759, in get_fake_value
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     unimplemented(
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]   File "/data/users/williamwen/pytorch2/torch/_dynamo/exc.py", line 204, in unimplemented
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks]     raise Unsupported(msg)
V0408 16:53:17.749000 140101593147200 torch/_dynamo/symbolic_convert.py:516] [0/0] [__graph_breaks] torch._dynamo.exc.Unsupported: unsupported operator: torchvision.my_custom_op2.default (see https://docs.google.com/document/d/1GgvOe7C8_NVOMLOCwDaYV1mXXyHMXY7ExoewHqooxrs/edit#heading=h.64r4npvq0w0 for how to fix)
```

In particular, both the dynamic shapes manual and the C++ custom ops manual are linked.

The `torch::RegisterOperators()` registered custom op gives the opaque error seen in https://github.com/pytorch/pytorch/issues/95791

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @zou3519

**Comment by ezyang** [comment]
I'm not sure what the desired fixed behavior is?

**Comment by williamwen42** [comment]
We want to find instances where the opaque error is happening and point to the right information instead (the C++ custom ops manual likely). For the first error, we should only link 1 doc.

**Comment by bdhirsh** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/124240
