### ISSUE TITLE
[AOTI] Multiple arrayref_interface tests cause segfault on test runner exit

### ISSUE THREAD

**Issue by int3** [pytorch/pytorch#123691]
### 🐛 Describe the bug

How to repro:

comment out the lines below:

https://github.com/pytorch/pytorch/blob/57a9a64e10b84fa8d932482ae9417aa3fc3fbf44/test/inductor/test_aot_inductor.py#L2322-L2324

and run the following command:

```
$ python test/inductor/test_aot_inductor.py -k test_zero_grid_with_unbacked_symbols_abi_compatible_cpu_with_stack_allocation_and_minimal_arrayref_interface
```

While the test itself succeeds, the test runner segfaults before it exits.

Running it under gdb gives the following stack trace:

```
#0  0x00007fffb1caeb10 in ?? ()
#1  0x00007ffff68af896 in (anonymous namespace)::run (p=<optimized out>) at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/atexit_thread.cc:80
#2  (anonymous namespace)::run () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/atexit_thread.cc:105
```

In particular, we are segfaulting when trying to run the destructor here: https://github.com/gcc-mirror/gcc/blob/releases/gcc-11/libstdc%2B%2B-v3/libsupc%2B%2B/atexit_thread.cc#L80

The destructor's address originally points to `~RAIIAtenTensorHandle()` within model.so, but by the time we try to run it, model.so has already been unloaded; hence the segfault. Not sure why this is only being triggered by the minimal arrayref interface though.

### Versions

PyTorch version: 2.4.0a0+git6890333
gcc used to build PyTorch: 11.4.1

cc @desertfire @penguinwu @yushangdi @benjaminglass1 @jataylo @iupaikov-amd @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @chenyang78

**Comment by int3** [comment]
test_amp_fallback_random_abi_compatible_cpu_with_stack_allocation_and_minimal_arrayref_interface also succeeds + segfaults on exit with a similar stack trace

**Comment by int3** [comment]
So does test_index_put_with_none_index_abi_compatible_cpu_with_stack_allocation_and_minimal_arrayref_interface (after #122984 is fixed)

**Comment by int3** [comment]
After a bit more digging, I think the problem may be in conda's build of libstdc++. First, it's a known issue that DSO unloading can conflict with `__cxa_thread_atexit`. See https://cxx-abi-dev.codesourcery.narkive.com/sHOvbaPX/adding-cxa-thread-atexit-to-the-c-abi and http://sourceware.org/glibc/wiki/Destructor%20support%20for%20thread_local%20variables
 for some relevant discussion.

Ultimately the problem should have been solved in glibc long ago. However, libstdc++ will only call the implementation in glibc if it is compiled with the right ifdefs: https://github.com/gcc-mirror/gcc/blob/releases/gcc-11/libstdc%2B%2B-v3/libsupc%2B%2B/atexit_thread.cc#L38-L52. That does not seem to be happening here, since our stack trace shows that we end up on line 155, which is within libstdc++'s own fallback implementation of `__cxa_thread_atexit`. This implementation does not seem to use the `dso_handle` argument at all, so I guess it's not surprising that we run into conflicts with `dlclose`.

I guess I could confirm the hypothesis by building pytorch outside of conda, but that's a bit of a pain...

**Comment by chenyang78** [comment]
> After a bit more digging, I think the problem may be in conda's build of libstdc++. First, it's a known issue that DSO unloading can conflict with `__cxa_thread_atexit`. See https://cxx-abi-dev.codesourcery.narkive.com/sHOvbaPX/adding-cxa-thread-atexit-to-the-c-abi and http://sourceware.org/glibc/wiki/Destructor%20support%20for%20thread_local%20variables for some relevant discussion.
> 
> Ultimately the problem should have been solved in glibc long ago. However, libstdc++ will only call the implementation in glibc if it is compiled with the right ifdefs: https://github.com/gcc-mirror/gcc/blob/releases/gcc-11/libstdc%2B%2B-v3/libsupc%2B%2B/atexit_thread.cc#L38-L52. That does not seem to be happening here, since our stack trace shows that we end up on line 155, which is within libstdc++'s own fallback implementation of `__cxa_thread_atexit`. This implementation does not seem to use the `dso_handle` argument at all, so I guess it's not surprising that we run into conflicts with `dlclose`.
> 
> I guess I could confirm the hypothesis by building pytorch outside of conda, but that's a bit of a pain...

Thanks for sharing. Very interesting findings!

**Comment by desertfire** [comment]
> 
> I guess I could confirm the hypothesis by building pytorch outside of conda, but that's a bit of a pain...

Very nice finding!

Why do you suspect it is a conda build issue? I don't think the program will use libstdc++.so from the conda directory without explicitly specifying LD_LIBRARY_PATH. FWIW, I tried with my local MacOS build, which is built with clang++ instead of g++, the problem does get resolved. So I think we are on the right track here.

**Comment by int3** [comment]
> I don't think the program will use libstdc++.so from the conda directory without explicitly specifying LD_LIBRARY_PATH

This surprised me too, but `info proc mappings` in gdb shows that it's definitely getting libstdc++ from conda. This is despite me having an empty `LD_LIBRARY_PATH`. I did try setting `LD_LIBRARY_PATH` explicitly so that the `/lib64` system libstdc++ would take priority, but that gave me some other symbol resolution errors...

**Comment by int3** [comment]
Ah, with `LD_DEBUG=libs`, we get

```
    579883:	find library=libstdc++.so.6 [0]; searching
    579883:	 search path=/data/users/jezng/pytorch/torch/lib		(RPATH from file /data/users/jezng/pytorch/torch/lib/libtorch_global_deps.so)
    579883:	  trying file=/data/users/jezng/pytorch/torch/lib/libstdc++.so.6
    579883:	 search path=/usr/local/cuda-12.1/lib64		(LD_LIBRARY_PATH)
    579883:	  trying file=/usr/local/cuda-12.1/lib64/libstdc++.so.6
    579883:	 search path=/home/jezng/.conda/envs/pytorch/bin/../lib		(RPATH from file python)
    579883:	  trying file=/home/jezng/.conda/envs/pytorch/bin/../lib/libstdc++.so.6
```

RPATH takes precedence over `LD_LIBRARY_PATH`, and the python provided by conda has an rpath set to `$ORIGIN/../lib`; that's why we are looking up the conda version of the library. (In general, that does seem to be the right thing to do, since conda packages are getting built against that library too...)

Modifying the RPATH causes the segfault to go away:
```
patchelf --set-rpath "/lib64:\$ORIGIN/../lib" `which python`
```

I wonder if we can get conda to use the system libstdc++, or if we need to host our own conda channel with a fixed version of the library...

**Comment by desertfire** [comment]
Adding @malfet to the discussion, I think for the short term we can at least fix this on CI by seeting RPATH so that we are not skipping those tests. For long term, if we want AOTI to generate code with `thread_local`, we will have to fix this conda issue.

**Comment by ezyang** [comment]
Why not just use C-style thread local `__thread`.

**Comment by int3** [comment]
AFAIK `__thread` does not support non-trivial destructors, so an instance of `RAIIAtenTensorHandle` needs `thread_local`.

**Comment by int3** [comment]
hm well I think the thread local stuff was set up by @swolchok

**Comment by swolchok** [comment]
> not sure if he intended RAII handles to end up there

This was clearly intentional in https://github.com/pytorch/pytorch/pull/112800 . Here is the relevant background:
- the AOTI minimal arrayref interface returns an `ArrayRefTensor` (non-owning) referring to a thread_local buffer. This allows the caller to avoid repeated memory allocation/deallocation costs for outputs.
- There is a complication: the output might just so happen to be an actual `RAIIAtenTensorHandle` or `AtenTensorHandle`, either always or in some internal branch of the model. To provide the same interface contract in this case, we stash said handle into a `thread_local` and will end up destroying it at either the next iteration that also returns one of these handles, dlclose time, or thread termination time. Note that *this behavior is not ideal* -- for maximum performance, we should be avoiding fallback kernels, including by generating calls to a lower-overhead matmul API, possibly using a stack allocated buffer if we know the relevant size.

> This is especially true for AOTInductor where we control codegen over everything; if you need something "thread local" just pass it as an argument.

I don't think this argument holds water; we don't control the calling program, and the calling program doesn't necessarily know how much memory to allocate for this particular model's output on this particular run.

> Ultimately the problem should have been solved in glibc long ago. However, libstdc++ will only call the implementation in glibc if it is compiled with the right ifdefs

My reading of the discussion surrounding this point is "some aspect of the conda environment someone (users? unit tests? both?) is using is resulting in a broken libstdc++". The right fix is for that environment to have a non-broken libstdc++; `thread_local` is a C++11 feature, we require C++17, and the year is 2024. As further evidence, I present both the reported success on macOS and the test evidently having passed in fbcode when the PR was imported and nobody complaining about it in that environmment. However, I recognize that I might be missing something and would be interested to hear what that might be.

**Comment by malfet** [comment]
> Adding @malfet to the discussion, I think for the short term we can at least fix this on CI by seeting RPATH so that we are not skipping those tests. For long term, if we want AOTI to generate code with `thread_local`, we will have to fix this conda issue.

There shouldn't be any libstdc++ library in conda, ~~we delete it in CI~~ sigh, we install it from conda-forge see https://github.com/pytorch/pytorch/pull/121556 updating to the one that works sounds good to me (and reporting the issue back to conda)

But I guess what we should avoid doing is relying on some libstdc++ version that would not be available in ubuntu-20.04 by default

**Comment by swolchok** [comment]
> updating to the one that works sounds good to me 

did anybody try this?
