### ISSUE TITLE
torch.explain gives non-deterministic results on the same model with the same input

### ISSUE THREAD

**Issue by kilianyp** [pytorch/pytorch#123636]
### 🐛 Describe the bug

When running `torch._dynamo.explain` multiple times on the same model with the same input, different number of graphs and graph ops are returned.

I would expect this to be the same in every run, but maybe I overlooked something in the docs.

If this is expected behaviour, this non-determinism is causing issues for the custom backend I am working on.
A flag to keep it consistent would be great to have. 

There's also other warnings in the error log, that I so far ignored, but maybe are the reason for the non-determinism.

### Error logs

```
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:694: UserWarning: explain(f, *args, **kwargs) is deprecated, use explain(f)(*args, **kwargs) instead.  If you don't migrate, we may break your explain call in the future if your user defined kwargs conflict with future kwargs added to explain(f).
  warnings.warn(                                                                                                                                                                     
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py:1397: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)                                                                                                                                                
<eval_with_key>.3:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(l_stack0_, device = device(type='cuda', index=0), dtype = torch.bool);  l_stack0_ = None         
[2024-04-09 12:08:41,762] [8/0] torch._dynamo.output_graph: [WARNING] nn.Module state_dict and backward hooks are not yet supported by torch.compile, but were detected in your model and will be silently ignored. See https://pytorch.org/docs/master/compile/nn-module.html for more information and limitations.
0: graph_count: 16, op_count: 179                                                                                                                                                    
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:694: UserWarning: explain(f, *args, **kwargs) is deprecated, use explain(f)(*args, **kwargs) instead.  If you don't migrate, we may break your explain call in the future if your user defined kwargs conflict with future kwargs added to explain(f).
  warnings.warn(                                                                                                                                                                     
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py:1397: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)                                                                                                                                                
<eval_with_key>.19:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(l_stack0_, device = device(type='cuda', index=0), dtype = torch.bool);  l_stack0_ = None         
1: graph_count: 14, op_count: 149                         
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:694: UserWarning: explain(f, *args, **kwargs) is deprecated, use explain(f)(*args, **kwargs) instead.  If you don't migrate, we may break your explain call in the future if your user defined kwargs conflict with future kwargs added to explain(f).
  warnings.warn(
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py:1397: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)
<eval_with_key>.33:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(l_stack0_, device = device(type='cuda', index=0), dtype = torch.bool);  l_stack0_ = None
2: graph_count: 17, op_count: 194
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:694: UserWarning: explain(f, *args, **kwargs) is deprecated, use explain(f)(*args, **kwargs) instead.  If you don't migrate, we may break your explain call in the future if your user defined kwargs conflict with future kwargs added to explain(f).
  warnings.warn(
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py:1397: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)
<eval_with_key>.50:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(l_stack0_, device = device(type='cuda', index=0), dtype = torch.bool);  l_stack0_ = None
3: graph_count: 18, op_count: 209
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:694: UserWarning: explain(f, *args, **kwargs) is deprecated, use explain(f)(*args, **kwargs) instead.  If you don't migrate, we may break your explain call in the future if your user defined kwargs conflict with future kwargs added to explain(f).
  warnings.warn(
/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py:1397: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)
<eval_with_key>.68:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(l_stack0_, device = device(type='cuda', index=0), dtype = torch.bool);  l_stack0_ = None
4: graph_count: 15, op_count: 164
Exception ignored in: <function ExactWeakKeyDictionary.__setitem__.<locals>.<lambda> at 0x7efb8a48e3b0>
Traceback (most recent call last):
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 386, in <lambda>
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 541, in _remove_id
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 525, in __call__
AttributeError: 'NoneType' object has no attribute 'count'
Exception ignored in: <function ExactWeakKeyDictionary.__setitem__.<locals>.<lambda> at 0x7efb8ad53880>
Traceback (most recent call last):
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 386, in <lambda>
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 541, in _remove_id
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 525, in __call__
AttributeError: 'NoneType' object has no attribute 'count'
Exception ignored in: <function ExactWeakKeyDictionary.__setitem__.<locals>.<lambda> at 0x7efb8b7476d0>
Traceback (most recent call last):
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 386, in <lambda>
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 541, in _remove_id
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 525, in __call__
AttributeError: 'NoneType' object has no attribute 'count'
Exception ignored in: <function ExactWeakKeyDictionary.__setitem__.<locals>.<lambda> at 0x7efb8a963130>
Traceback (most recent call last):
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 386, in <lambda>
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 541, in _remove_id
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 525, in __call__
AttributeError: 'NoneType' object has no attribute 'count'
Exception ignored in: <function ExactWeakKeyDictionary.__setitem__.<locals>.<lambda> at 0x7efb8b07b400>
Traceback (most recent call last):
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 386, in <lambda>
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 541, in _remove_id
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 525, in __call__
AttributeError: 'NoneType' object has no attribute 'count'
```

I pasted the complete log:
There are ignored exceptions, I haven't digged yet into where they are coming from.

```
Exception ignored in: <function ExactWeakKeyDictionary.__setitem__.<locals>.<lambda> at 0x7efb8b07b400>
Traceback (most recent call last):
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 386, in <lambda>
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 541, in _remove_id
  File "/home/kilian/.pyenv/versions/torch2.1/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 525, in __call__
AttributeError: 'NoneType' object has no attribute 'count'
```

The issue that I am focused on:
```
0: graph_count: 16, op_count: 179  
1: graph_count: 14, op_count: 149  
2: graph_count: 17, op_count: 194
3: graph_count: 18, op_count: 209
4: graph_count: 15, op_count: 164
```

### Minified repro

```python
import torch
from transformers import WavLMForCTC, WavLMConfig

import torch._dynamo as dynamo

device = "cuda"
model = WavLMForCTC(config=WavLMConfig()).to(device)
x = torch.rand((2, 24_000)).to(device)

for i in range(5):
    out =  dynamo.explain(model, x)
    print(f"{i}: graph_count: {out.graph_count}, op_count: {out.op_count}"))
```

### Versions
```
Collecting environment information...
PyTorch version: 2.1.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-1030-gcp-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 550.54.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        1 MiB (4 instances)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] fast-pytorch-kmeans==0.2.0.1
[pip3] flytekitplugins-kfpytorch==1.10.7
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.14.1
[pip3] onnx-tool==0.7.0+90a844dfa9c9011be8257e6c02e9e7e281314bdf
[pip3] onnx2torch==1.5.6+29b1c71c8581e4e0bf8c76d9589d47886dd83f69
[pip3] onnxruntime==1.15.1
[pip3] onnxsim==0.4.36
[pip3] pytorch-ignite==0.4.13
[pip3] torch==2.1.1+cu118
[pip3] torchaudio==2.1.1+cu118
[pip3] torchmetrics==1.3.2
[pip3] torchvision==0.16.1+cu118
[pip3] triton==2.1.0
[conda] Could not collect


Also reproduced on the same machine in a different venv on 2.2:

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.16.0
[pip3] onnxruntime==1.17.1
[pip3] torch==2.2.1+cu118
[pip3] triton==2.2.0
[conda] Could not collect


transformers == 4.38.2
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by kilianyp** [comment]
After some more debugging to check if maybe the model isn't deterministic:

When using `model.eval()`, `torch._dynamo.explain` always gives the same result. I misinterpreted `torch.inference_mode` to also do `eval`, but apparently it doesn't.

Not sure if this is then still a bug then.

**Comment by TXacs** [comment]
Hi, I'm has the same problem when I use `dynamo.explain` to get `GraphModule`. Do you have some idea to solve the AttributeError?
