### ISSUE TITLE
[RFC] PyTorch next wheel build platform: manylinux-2.28

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#123649]
### 🚀 The feature, motivation and pitch

CentOS EOL is scheduled for the summer: https://www.redhat.com/en/blog/fastest-road-centos-linux-red-hat-enterprise-linux

With official manylinux has moved to almalinux: https://github.com/pypa/manylinux/blob/main/docker/Dockerfile#L2

manylinux_2_28 (AlmaLinux 8 based)
Toolchain: GCC 12
x86_64 image: quay.io/pypa/manylinux_2_28_x86_64
aarch64 image: quay.io/pypa/manylinux_2_28_aarch64
ppc64le image: quay.io/pypa/manylinux_2_28_ppc64le
s390x image: quay.io/pypa/manylinux_2_28_s390x

Almalinux:
https://almalinux.org/

Opening this issue to gather feedback, decide on the timeline for migration of the wheel build images

Work Completed:

- [x] Create Docker Manylinx 2.28 builds
- [x] PyTorch Wheel Switch to Manylinux 2.28 https://github.com/pytorch/pytorch/pull/138732
- [x] Test-Infra Nova Workflows Switch to Manylinx 2.28 https://github.com/pytorch/test-infra/pull/5909
- [x] Triton Update https://github.com/pytorch/pytorch/pull/141704
- [x] Use Manylinux 2.28 on pytorch pytorch for all the architectures https://github.com/pytorch/pytorch/pull/143423

RFC: Discussion issue https://github.com/pytorch/pytorch/issues/126551

cc @seemethere @malfet @osalpekar @pytorch/pytorch-dev-infra @ptrblck

**Comment by huydhn** [comment]
@AlekseiNikiforovIBM recently adds the docker build image for s390x with the RedHat 9 base image from https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?architecture=amd64&image=65e093e60a21b531a96f93ca.  

But going with the official manylinux suggestion sounds like a good choice too as long as they have all the different flavors that we need and compatible with RedHat.

**Comment by seemethere** [comment]
I don't think we should base on RHEL considering getting access to RHEL images is based on if you have a subscription or not (or at least that's been my experience, happy to be wrong here).

I'd say we should go with whatever the official upstream `manylinux` distribution is utilizing. If that's almalinux then we go with that, if it's something else then we should go with what they're going with.

**Comment by malfet** [comment]
manylinux-2.28 is the next standard we should be moving to. And perhaps it's also time to kill PRE_CXX11 ABI (which were necessary for all manylinux standards prior to 2.28)

**Comment by seemethere** [comment]
> manylinux-2.28 is the next standard we should be moving to. And perhaps it's also time to kill PRE_CXX11 ABI (which were necessary for all manylinux standards prior to 2.28)

I'd agree here, no need to keep dinosaurs around if we're moving to the future!

**Comment by zeroepoch** [comment]
TensorRT is moving back to manylinux_2_17 after some push back from customers. Although this shouldn't create issues for projects like PyTorch consuming TRT using manylinux_2_28 due to glibc backward compatibility. The CXX ABI change is also being discussed (slaying dinosaurs)

**Comment by ZolotukhinM** [comment]
> manylinux-2.28 is the next standard we should be moving to. And perhaps it's also time to kill PRE_CXX11 ABI (which were necessary for all manylinux standards prior to 2.28)

Are there any estimate timelines on when this can happen? IIUC most of current builds are still targeting CXX03 ABI (from looking at https://download.pytorch.org/whl/torch/)

**Comment by snadampal** [comment]
I have the PRs for aarch64-linux platform CD migration to manylinux 2_28. 
https://github.com/pytorch/builder/pull/1784
https://github.com/pytorch/builder/pull/1781

but I see few OS distros (for example Amazon Linux2) is with glibc2_26 and switching to manylinux2_28 will break compatibility with it. I would suggest we first make the announcement about the timeline for this switch to avoid surprises and disappointments for customers.

**Comment by atalman** [comment]
@snadampal @malfet @seemethere 
I suggest following option, still use old wheels for 2.4. But announce the deprecation of old wheels. For Release 2.5 - Use only new wheels. This will give Amazon Linux 2 users time to prepare.

**Comment by huydhn** [comment]
Our CI are still on Amazon Linux 2, so I guess we need to migrate it to use Amazon Linux 2023 before the the new wheel could even pass validation.

**Comment by atalman** [comment]
@snadampal You are correct wheel generated with manylinux2_28 is not compatible with Amazon Linux 2. Here is the test:

```
(py38) [ec2-user@ip-10-0-9-21 temp]$ pip install torch-2.4.0.dev20240513%2Bcpu-cp38-cp38-linux_x86_64.whl
Processing ./torch-2.4.0.dev20240513%2Bcpu-cp38-cp38-linux_x86_64.whl
Collecting filelock (from torch==2.4.0.dev20240513+cpu)
  Downloading filelock-3.14.0-py3-none-any.whl.metadata (2.8 kB)
Collecting typing-extensions>=4.8.0 (from torch==2.4.0.dev20240513+cpu)
  Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.4.0.dev20240513+cpu)
  Downloading sympy-1.12-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.4.0.dev20240513+cpu)
  Downloading networkx-3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting jinja2 (from torch==2.4.0.dev20240513+cpu)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.4.0.dev20240513+cpu)
  Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.4.0.dev20240513+cpu)
  Downloading MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting mpmath>=0.19 (from sympy->torch==2.4.0.dev20240513+cpu)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Downloading filelock-3.14.0-py3-none-any.whl (12 kB)
Downloading fsspec-2024.3.1-py3-none-any.whl (171 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 23.3 MB/s eta 0:00:00
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 18.4 MB/s eta 0:00:00
Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 90.7 MB/s eta 0:00:00
Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 112.1 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 50.5 MB/s eta 0:00:00
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.5 filelock-3.14.0 fsspec-2024.3.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.1 sympy-1.12 torch-2.4.0.dev20240513+cpu typing-extensions-4.11.0
(py38) [ec2-user@ip-10-0-9-21 temp]$ conda list
# packages in environment at /home/ec2-user/miniconda3/envs/py38:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ca-certificates           2024.3.11            h06a4308_0  
filelock                  3.14.0                   pypi_0    pypi
fsspec                    2024.3.1                 pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
markupsafe                2.1.5                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
openssl                   3.0.13               h7f8727e_1  
pip                       24.0             py38h06a4308_0  
python                    3.8.19               h955ad1f_0  
readline                  8.2                  h5eee18b_0  
setuptools                69.5.1           py38h06a4308_0  
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.12                     pypi_0    pypi
tk                        8.6.14               h39e8969_0  
torch                     2.4.0.dev20240513+cpu          pypi_0    pypi
typing-extensions         4.11.0                   pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0  
xz                        5.4.6                h5eee18b_1  
zlib                      1.2.13               h5eee18b_1  

...
(py38) [ec2-user@ip-10-0-9-21 test]$ python smoke_test/smoke_test.py 
Traceback (most recent call last):
  File "smoke_test/smoke_test.py", line 5, in <module>
    import torch
  File "/home/ec2-user/miniconda3/envs/py38/lib/python3.8/site-packages/torch/__init__.py", line 240, in <module>
    from torch._C import *  # noqa: F403
ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/ec2-user/miniconda3/envs/py38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
```

**Comment by chuanqi129** [comment]
Hi @atalman, we're working on XPU nightly manylinux wheel build enabling, and for XPU we also need to use manylinux_2_28 environment. But I found that the official quay.io/pypa/manylinux_2_28_x86_64 docker image don't provide shared library libpython*.so for each python version under /opt/python (refer https://github.com/pypa/manylinux/issues/255), so we can't use it to build pytorch python wheel directly, we may still need rebuild the python by ourselves. How do you think about it?

**Comment by EikanWang** [comment]
For Intel GPU, we will submit a PR to support ABI=0 if PT2.5 cannot switch to ABI=1 mode. Due to the ABI change for Intel GPU software breaking the backward compatibility, we will refine the cmake a little bit - https://github.com/pytorch/pytorch/pull/130110 FYI

**Comment by jithunnair-amd** [comment]
Actually, do we need to support the _GLIBCXX_USE_CXX11_ABI=0 case for PyTorch wheels, or can we sunset that requirement?

**Comment by malfet** [comment]
@jithunnair-amd that depends on who your customers. If you believe that this is fine for ROCm, please do not hesitate to propose a patch

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd that depends on who your customers. If you believe that this is fine for ROCm, please do not hesitate to propose a patch

Okay, I think we can start with setting `DESIRED_DEVTOOLSET: cxx11-abi` in https://github.com/pytorch/pytorch/blob/ad9826208c4d8e171d0c0d57a14818ede4babad4/.github/workflows/generated-linux-binary-manywheel-nightly.yml#L548 and see if there's any community motivation to stay on pre-cxx11-abi symbols. I'll check internally regarding customers as well.

**Comment by atalman** [comment]
Reopening this task to followup on this migration.

**Comment by HDCharles** [comment]
are there remediation steps if we run into the issues mentioned above in pytorch/ao we're seeing the gclib error in our wheel builds

https://github.com/pytorch/ao/actions/runs/11714251538/job/32628593881

ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__w/_temp/conda_environment_11714251538/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

**Comment by atalman** [comment]
Reopening to track

**Comment by ramanishsingh** [comment]
@HDCharles were you able to fix this?
I am getting a similar error  `ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/conda/envs/conda-env-11898957414/lib/python3.9/site-packages/torch/lib/libtorch_python.so)`
 https://github.com/pytorch/data/actions/runs/11898957414/job/33157180200
and I tried the fix that was suggested
But when I use that and point to `pytorch/test-infra/.github/workflows/linux_job_v2.yml@main`
I get this error `The workflow is not valid. .github/workflows/build_wheels_linux.yml (Line: 48, Col: 21): Invalid input, build-matrix is not defined in the referenced workflow. .github/workflows/build_wheels_linux.yml (Line: 49, Col: 19): Invalid input, pre-script is not defined in the referenced workflow.` https://github.com/pytorch/data/actions/runs/11899232882

**Comment by atalman** [comment]
For Release 2.6 we will be releasing Manylinux 2014 wheels for CPU, CUDA 12.4, CUDA 11.8 builds. And Manylinux 2.28 wheels for CUDA 12.6 : https://github.com/pytorch/pytorch/pull/141565

**Comment by njzjz** [comment]
I want to ask a question: for CUDA 12.6, will `_GLIBCXX_USE_CXX11_ABI` be `0` or `1`?

**Comment by malfet** [comment]
> I want to ask a question: for CUDA 12.6, will `_GLIBCXX_USE_CXX11_ABI` be `0` or `1`?

I would vote for `1`, or release it with both ABIs

**Comment by jithunnair-amd** [comment]
ROCm PRs to move to manylinux2_28:
* update GCC_ABI check to expect 1 for ROCm manylinux2_28 wheels: [2043](https://github.com/pytorch/builder/pull/2043)
* ROCm manylinux2_28 manylinux images: [140681](https://github.com/pytorch/pytorch/pull/140681)
* upgrade to gcc11 for manylinux2_28 images: [141609](https://github.com/pytorch/pytorch/pull/141609)
* ROCm manylinux2_28 PyTorch binaries - [141423](https://github.com/pytorch/pytorch/pull/141423)
* ROCm manylinux2_28 PyTorch ecosystem binaries - [6016](https://github.com/pytorch/test-infra/pull/6016)

**Comment by atalman** [comment]
Switching PyTorch nightlies to Manylinux 2.28 builds and cxx11-abi by default: https://github.com/pytorch/pytorch/pull/143423

**Comment by atalman** [comment]
Closing this as completed
