### ISSUE TITLE
DISABLED test_hsdp_save_load_state_dict (__main__.TestFSDPHybridShard)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#123749]
Platforms: linux

Ex https://ossci-raw-job-status.s3.amazonaws.com/log/23584654524
Tentatively blaming #123230 @xunnanxu

```

2024-04-08T22:28:05.4610276Z ______________ TestFSDPHybridShard.test_hsdp_save_load_state_dict ______________
2024-04-08T22:28:05.4610984Z Traceback (most recent call last):
2024-04-08T22:28:05.4612153Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 541, in wrapper
2024-04-08T22:28:05.4613223Z     self._join_processes(fn)
2024-04-08T22:28:05.4614355Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 760, in _join_processes
2024-04-08T22:28:05.4616353Z     self._check_return_codes(elapsed_time)
2024-04-08T22:28:05.4617595Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 810, in _check_return_codes
2024-04-08T22:28:05.4618817Z     raise RuntimeError(error)
2024-04-08T22:28:05.4619407Z RuntimeError: Process 2 exited with error code 10 and exception:
2024-04-08T22:28:05.4620048Z Traceback (most recent call last):
2024-04-08T22:28:05.4621168Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 657, in run_test
2024-04-08T22:28:05.4622259Z     getattr(self, test_name)()
2024-04-08T22:28:05.4623343Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 543, in wrapper
2024-04-08T22:28:05.4624366Z     fn()
2024-04-08T22:28:05.4625310Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2741, in wrapper
2024-04-08T22:28:05.4626304Z     method(*args, **kwargs)
2024-04-08T22:28:05.4627373Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 182, in wrapper
2024-04-08T22:28:05.4628422Z     return func(*args, **kwargs)
2024-04-08T22:28:05.4629468Z   File "/var/lib/jenkins/workspace/test/distributed/fsdp/test_fsdp_hybrid_shard.py", line 160, in test_hsdp_save_load_state_dict
2024-04-08T22:28:05.4630554Z     msd = model.state_dict()
2024-04-08T22:28:05.4631555Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1918, in state_dict
2024-04-08T22:28:05.4632686Z     hook_result = hook(self, destination, prefix, local_metadata)
2024-04-08T22:28:05.4633897Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-04-08T22:28:05.4634964Z     return func(*args, **kwargs)
2024-04-08T22:28:05.4636161Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 728, in _post_state_dict_hook
2024-04-08T22:28:05.4637490Z     processed_state_dict = _post_state_dict_hook_fn[fsdp_state._state_dict_type](
2024-04-08T22:28:05.4639057Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 573, in _sharded_post_state_dict_hook
2024-04-08T22:28:05.4640282Z     return _common_unshard_post_state_dict_hook(
2024-04-08T22:28:05.4641756Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 242, in _common_unshard_post_state_dict_hook
2024-04-08T22:28:05.4642985Z     param_hook(state_dict, prefix, fqn)
2024-04-08T22:28:05.4644150Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 554, in param_hook
2024-04-08T22:28:05.4645225Z     sharded_tensor = _ext_chunk_tensor(
2024-04-08T22:28:05.4646405Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/_fsdp_extensions.py", line 130, in _ext_chunk_tensor
2024-04-08T22:28:05.4647505Z     return chunk_tensor_fn(
2024-04-08T22:28:05.4648671Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/_shard_utils.py", line 79, in _create_chunk_sharded_tensor
2024-04-08T22:28:05.4649978Z     return ShardedTensor._init_from_local_shards_and_global_metadata(
2024-04-08T22:28:05.4651521Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/_shard/sharded_tensor/api.py", line 863, in _init_from_local_shards_and_global_metadata
2024-04-08T22:28:05.4653122Z     rank, local_device = _parse_and_validate_remote_device(process_group, shard_metadata.placement)
2024-04-08T22:28:05.4654788Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/_shard/sharded_tensor/utils.py", line 29, in _parse_and_validate_remote_device
2024-04-08T22:28:05.4655999Z     raise ValueError(
2024-04-08T22:28:05.4656585Z ValueError: Global rank 0 does not exist in input process group: [2, 3]
2024-04-08T22:28:05.4657128Z 
2024-04-08T22:28:05.4657423Z To execute this test, run the following from the base repo dir:
2024-04-08T22:28:05.4658545Z      python test/distributed/fsdp/test_fsdp_hybrid_shard.py -k test_hsdp_save_load_state_dict
2024-04-08T22:28:05.4659194Z 
2024-04-08T22:28:05.4659564Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-04-08T22:28:05.4660139Z 
2024-04-08T22:28:05.4660144Z 
2024-04-08T22:28:05.4660474Z ----------------------------- Captured stdout call -----------------------------
2024-04-08T22:28:05.4661325Z Process 2 terminated with exit code 10, terminating remaining processes.
```
This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22distributed%2Ffsdp%2Ftest_fsdp_hybrid_shard.py%3A%3ATestFSDPHybridShard%3A%3Atest_hsdp_save_load_state_dict%22%5D)).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @ezyang @msaroufim @bdhirsh @anijain2305

**Comment by xunnanxu** [comment]
Should have been fixed by https://github.com/pytorch/pytorch/pull/123778
