### ISSUE TITLE
my_role_info = role_infos group_rank index error

### ISSUE THREAD

**Issue by hjc3613** [pytorch/pytorch#123815]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 737, in run
    result = self._invoke_run(role)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 872, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 706, in _initialize_workers
    self._rendezvous(worker_group)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 549, in _rendezvous
    workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 639, in _assign_worker_ranks
    my_role_info = role_infos[group_rank]
IndexError: list index out of range

### Versions

During the training process of the code, I encountered the above exception
my training script is:
```bash
torchrun --nnodes 2 --nproc_per_node 8 --rdzv-id=7788 --rdzv-backend=c10d --rdzv-endpoint=10.233.126.118 \
    finetuning_dpo.py \
    --model_name ${model_name} \
    --dataset ${dataset} \
    --low_cpu_fsdp \
    --enable_fsdp \
    --batch_size_training 1 \
    --dist_checkpoint_root_folder ${dist_checkpoint_root_folder} \
    --dist_checkpoint_folder ${dist_checkpoint_folder} \
    --num_epochs 5 \
    --gradient_accumulation_steps 4 \
    --fsdp_config.pure_bf16 \
    --lr 5e-6 \
    --seed 0 \
    --gradient_clipping \
    --gradient_clipping_threshold 5 \
```
it seems that when assign rank number to the process failed in the process of torchrun using backend rdzv , so the role_infos has not enough number, and cause the index error, but I do not know what cause the problem? network? or others?

**Comment by 0uterspaceguy** [comment]
any progress?
faced same, idk how to solve...

**Comment by hjc3613** [comment]
> any progress? faced same, idk how to solve...

It's a hardware communication issue for my case. Uncertain whether other reasons might also cause this

**Comment by dzang** [comment]
> > any progress? faced same, idk how to solve...
> 
> It's a hardware communication issue for my case. Uncertain whether other reasons might also cause this

how did you find and fix it?

**Comment by 0uterspaceguy** [comment]
> > > any progress? faced same, idk how to solve...
> > 
> > 
> > It's a hardware communication issue for my case. Uncertain whether other reasons might also cause this
> 
> how did you find and fix it?

Hi!
I solved it. For me it was nccl communication problem between my laptops. I am starting the training in docker container, so i needed to open ports range in ubuntu:

ufw allow 50000:51000/tcp

And then set ports range for nccl backend in docker container like this:

echo 50000 51000 > /proc/sys/net/ipv4/ip_local_port_range

(You need to do this two steps on every machine)

You can check my repository

https://github.com/0uterspaceguy/Multinode_template/tree/main

Also check this:

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#ip-ports

**Comment by archrock** [comment]
If NTP is not in use, verify the system time on all servers. Any discrepancies of 2-30 seconds or more can lead to issues.

**Comment by kwen2501** [comment]
cc @d4l3k
