### ISSUE TITLE
RuntimeError: _weight_int4pack_mm_cpu : expect A to be float16 or bfloat16 tensor.

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#123997]
### 🐛 Describe the bug

RuntimeError: _weight_int4pack_mm_cpu : expect A to be float16 or bfloat16 tensor.

https://github.com/pytorch/torchat/actions/runs/8670488663/job/23778546397?pr=162

[W413 02:40:40.489921000 MPSFallback.mm:13] Warning: The operator 'aten::_convert_weight_to_int4pack' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (function operator())
  Traceback (most recent call last):
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 642, in <module>
      cli()
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 638, in cli
      main(args)
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 611, in main
      _main(
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 562, in _main
      y, metrics = generate(
                   ^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 231, in generate
      next_token = prefill(model, prompt.view(1, -1), input_pos, **sampling_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 78, in prefill
      logits = model(x_sliced, ip_sliced)  # (x[:, i], input_pos[i])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line 211, in forward
      x = layer(x, input_pos, freqs_cis, mask)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line 237, in forward
      h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line [299](https://github.com/pytorch/torchat/actions/runs/8670488663/job/23778546397?pr=162#step:9:303), in forward
      q = self.wq(x)
          ^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/quantize.py", line 769, in forward
      return linear_forward_int4(
             ^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/quantize.py", line 650, in linear_forward_int4
      c = torch.ops.aten._weight_int4pack_mm(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/_ops.py", line 870, in __call__
      return self_._op(*args, **(kwargs or {}))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  RuntimeError: _weight_int4pack_mm_cpu : expect A to be float16 or bfloat16 tensor.
  Error: Process completed with exit code 1.
  
  cc: @malfet @jgong5 

### Versions

pytorch CI

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by mikekgfb** [comment]
Interestingly after some hackery shenanigans, I get:
```
  RuntimeError: _weight_int4pack_mm_cpu : expect A to be bfloat16 tensor.
 ```
 
Now I'm totally confused because I thought floa16 had been added?
 
https://github.com/pytorch/torchat/actions/runs/8670556388/job/23778711258?pr=162

[W413 02:56:47.567290000 MPSFallback.mm:13] Warning: The operator 'aten::_convert_weight_to_int4pack' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (function operator())
  Traceback (most recent call last):
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 642, in <module>
      cli()
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 638, in cli
      main(args)
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 611, in main
      _main(
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 562, in _main
      y, metrics = generate(
                   ^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 231, in generate
      next_token = prefill(model, prompt.view(1, -1), input_pos, **sampling_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/generate.py", line 78, in prefill
      logits = model(x_sliced, ip_sliced)  # (x[:, i], input_pos[i])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line 211, in forward
      x = layer(x, input_pos, freqs_cis, mask)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      run_cmd_or_die(f"bash { os.environ.get('RUNNER_TEMP', '') }/exec_script")
    File "/Users/ec2-user/runner/_work/torchat/torchat/test-infra/.github/scripts/run_with_env_secrets.py", line 38, in run_cmd_or_die
      raise RuntimeError(f"Command {cmd} failed with exit code {exit_code}")
  RuntimeError: Command bash /Users/ec2-user/runner/_work/_temp/exec_script failed with exit code 1
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line [237](https://github.com/pytorch/torchat/actions/runs/8670549561/job/23778695074?pr=162#step:9:241), in forward
      h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line 299, in forward
      q = self.wq(x)
          ^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/quantize.py", line 778, in forward
      return linear_forward_int4(
             ^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/quantize.py", line 652, in linear_forward_int4
      c = torch.ops.aten._weight_int4pack_mm(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/_ops.py", line 870, in __call__
      return self_._op(*args, **(kwargs or {}))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  RuntimeError: _weight_int4pack_mm_cpu : expect A to be bfloat16 tensor.
  Error: Process completed with exit code 1.

**Comment by mingfeima** [comment]
@mikekgfb I can not access to those torchat CI links, like this one: https://github.com/pytorch/torchat/actions/runs/8670488663/job/23778546397?pr=162

Is there any minimal examples that we can reproduce this issue?

**Comment by yanbing-j** [comment]
@mikekgfb we cannot access torchat CI links. Could you please provide a minimal example, or some error logs? Thanks!

**Comment by malfet** [comment]
I've added a fix for it while back in https://github.com/pytorch/pytorch/pull/124287
