### ISSUE TITLE
JIT reports RuntimeError when decorating forward with torch.jit.script

### ISSUE THREAD

**Issue by hguandl** [pytorch/pytorch#123961]
### 🐛 Describe the bug

Hi there, I have accidentally put `@torch.jit.script` above the `forward` method and it produces a strange error.
I guess the decorator should be ignored or report a clearer message if this is not an expected case.
Thank you!

```python
import torch
from torch import nn

class Model(nn.Module):
    def __init__(self, h: int = 16) -> None:
        super().__init__()
        self.fc1 = nn.Linear(h, h)

    @torch.jit.script
    def forward(self, x: torch.Tensor):
        return torch.tanh(self.fc1(x))
    
m = Model(42)
y = m(torch.randn(42, 42))
```

```
Traceback (most recent call last):
  File "/path/to/test.py", line 4, in <module>
    class Model(nn.Module):
  File "/path/to/test.py", line 9, in Model
    @torch.jit.script
     ^^^^^^^^^^^^^^^^
  File "/path/to/site-packages/torch/jit/_script.py", line 1395, in script
    fn = torch._C._jit_script_compile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError:
'Tensor (inferred)' object has no attribute or method 'fc1'.:
  File "/path/to/test.py", line 11
    @torch.jit.script
    def forward(self, x: torch.Tensor):
        return torch.tanh(self.fc1(x))
                          ~~~~~~~~ <--- HERE
```

### Versions

PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.2
Libc version: N/A

Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[pip3] torchvision==0.17.1
[conda] Could not collect

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
