### ISSUE TITLE
AttributeError: Method VideoInput is not a registered operator

### ISSUE THREAD

**Issue by kateiyas** [pytorch/pytorch#12401]
## 🐛 Bug

I want to use models from [R2Plus1D](https://github.com/facebookresearch/R2Plus1D) for extracting action recognition features. However, when running their `extract_features.py` it will immediately throw the following error message:

`AttributeError: Method VideoInput is not a registered operator. Did you mean: []`

## To Reproduce

1. Install pytorch and caffe2 via `conda install pytorch-nightly torchvision -c pytorch`.
1. Download e.g. the C3D-16 model from [here](https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/models.md). 
1. Follow the [R2Plus1D feature extraction tutorial](https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/feature_extraction.md).
1. The error will occur with the command related to `extract_features.py`. My command:
```
python extract_features.py --test_data=data/lmdb_data --model_name=c3d --model_depth=34 --clip_length_rgb=32 --gpus=1 --batch_size=4 --load_model_path=/c3d/c3d_l16.pkl --output_path=testvideo_features.pkl --features=conv1a,conv2a,fc6 --sanity_check=1 --get_video_id=1 --use_local_file=1
```

Stack trace: 
```
Traceback (most recent call last):
  File "lib/extract_features.py", line 333, in <module>
    main()
  File "lib/extract_features.py", line 328, in main
    ExtractFeatures(args)
  File "lib/extract_features.py", line 131, in ExtractFeatures
    devices=gpus,
  File "/anaconda2/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 34, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/anaconda2/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 219, in Parallelize
    input_builder_fun(model_helper_obj)
  File "lib/extract_features.py", line 106, in input_fn
    use_local_file=args.use_local_file,
  File "/models/c3d/R2Plus1D/lib/utils/model_helper.py", line 120, in AddVideoInput
    data, label, video_id = model.net.VideoInput(
  File "/anaconda2/lib/python2.7/site-packages/caffe2/python/core.py", line 2171, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method VideoInput is not a registered operator. Did you mean: []
```

## Expected behavior

Getting action recognition features from `extract_features.py` .

## Environment

```
PyTorch version: 1.0.0.dev20181004
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.1

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0.dev20181004)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.1           py27__9.0.176_7.1.2_2    pytorch
[conda] pytorch-nightly           1.0.0.dev20181004 py2.7_cuda9.0.176_cudnn7.1.2_0    pytorch
[conda] torchvision               0.2.1                    py27_1    pytorch
```

**Comment by orionr** [comment]
Hi @kateiyas - I think I know what's going on here. The default binary builds are generated *without* OpenCV and ffmpeg dependency, which means that these operators (all of those under caffe2/video/) aren't built. You'll need to build from source to have these operators available.

We should update the R2Plus1 tutorial to make a note of this.

cc @pjh5 @Yangqing @soumith  on whether we want to provide a CV version of these with the above enabled.

**Comment by kateiyas** [comment]
I'm likely not the only one who would really appreciate a precompiled binary that works with [R2Plus1D](url
https://github.com/facebookresearch/R2Plus1D) (i.e. having USE_FFMPEG, USE_OPENCV and (optimally) GPU support enabled). Caffe still has several useful pretrained models for feature extraction.

**Comment by kateiyas** [comment]
The new master provided by @orionr seems to compile the video operators too. 
Compiling via `NP_GPU=1 NO_TEST=1 USE_FFMPEG=1 USE_OPENCV=1 USE_LEVELDB=0 USE_LMDB=1 python setup.py install` seems to work for me.

**Comment by yimikai** [comment]
> Hi @kateiyas - I think I know what's going on here. The default binary builds are generated _without_ OpenCV and ffmpeg dependency, which means that these operators (all of those under caffe2/video/) aren't built. You'll need to build from source to have these operators available.
> 
> We should update the R2Plus1 tutorial to make a note of this.
> 
> cc @pjh5 @Yangqing @soumith on whether we want to provide a CV version of these with the above enabled.

Please, how to get the new master for R2plus1D ?
