### ISSUE TITLE
[torch.compile][FlopCounter] AssertionError: Global is not OptimizedModule._orig_mod

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#124196]
### 🐛 Describe the bug

The error is coming from the `FlopCounterMode`. This seems like a tensor subclass. So, opening an issue.

The resulting flops probably needs to be cleaned up as well.

cc @Chillee @ezyang @zou3519 @albanD @samdow @msaroufim @bdhirsh @chauhang 

~~~
import torch
from torch.utils.flop_counter import FlopCounterMode


class SimpleMod(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 3)

    def forward(self, x):
        return torch.sin(self.linear(x))

inp = torch.randn(3, 3, device='cuda', requires_grad=True)
# mod = torch.nn.Linear(3, 3).to(device="cuda")
mod = SimpleMod().to(device="cuda")

mod = torch.compile(mod, backend="eager")

flop_counter = FlopCounterMode(mod)

with flop_counter:
    for i in range(20):
        mod(inp).sum().backward()
~~~

### Error logs

~~~
Module                         FLOP    % Total
---------------------------  ------  ---------
Global                          216    100.00%
 - aten.addmm                   108     50.00%
 - aten.mm                      108     50.00%
 OptimizedModule                162     75.00%
  - aten.addmm                   54     25.00%
  - aten.mm                     108     50.00%
  OptimizedModule._orig_mod     162     75.00%
   - aten.addmm                  54     25.00%
   - aten.mm                    108     50.00%
Traceback (most recent call last):
  File "/data/users/anijain/pytorch2/examples/valerie.py", line 23, in <module>
    mod(inp).sum().backward()
    ^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/_dynamo/eval_frame.py", line 387, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/nn/modules/module.py", line 1595, in _call_impl
    hook_result = hook(self, args, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/utils/flop_counter.py", line 412, in f
    outputs = _pytreeify_preserve_structure(self._create_post_module(name))(outputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/utils/flop_counter.py", line 330, in nf
    out = f(*flat_args)
          ^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/autograd/function.py", line 571, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/anijain/pytorch2/torch/utils/flop_counter.py", line 420, in forward
    assert self.parents[-1] == name, f"{self.parents[-1]} is not {name}"
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Global is not OptimizedModule._orig_mod
~~~

### Versions

N/A

cc @ezyang @msaroufim @bdhirsh @chauhang

**Comment by jbschlosser** [comment]
Note: `FlopCounterMode` is a `TorchDispatchMode`. Feels to me like a bug in `FlopCounterMode` making assumptions that don't hold under `torch.compile`.

**Comment by zou3519** [comment]
cc @Chillee, people seem to use FlopCounterMode under torch.compile a lot. Maybe we should just error out if we say we don't want to support it?

**Comment by Chillee** [comment]
@zou3519 yeah I think that's reasonable. Another option is to disable torch.compile automatically under FlopCounterMode

**Comment by IvanKobzarev** [comment]
Doing issue scrapping, closing as original repro does not fail.
