### ISSUE TITLE
[Affine grid][channels_last_3d] view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by jthakurH** [pytorch/pytorch#124154]
### 🐛 Describe the bug

```
import torch

def affine_grid_cl():
    torch.manual_seed(123)
    theta = torch.rand([6, 3, 4], requires_grad=True)
    grid = torch.nn.functional.affine_grid(theta, [6, 1, 3, 5, 5], align_corners=False)
    grad_tensor = torch.rand(grid.shape)
    grad_tensor = grad_tensor.contiguous(memory_format=torch.channels_last_3d)
    grid.backward(grad_tensor)
    return grid, theta.grad

if __name__ == "__main__":
    fwd, bwd_grad = affine_grid_cl()
    print("Test Passed!")

```

Please use above code to reproduce the issue. Here if the grad tensor is moved to channels_last it creates an issue.
Error:
```
Traceback (most recent call last):
  File "/tmp/view_issue.py", line 13, in <module>
    fwd, bwd_grad = affine_grid_cl()
  File "/tmp/view_issue.py", line 9, in affine_grid_cl
    grid.backward(grad_tensor)
  File "/tmp/lib/python3.10/site-packages/torch/_tensor.py", line 532, in backward
    torch.autograd.backward(
  File "/tmp/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.15.2a0
[pip3] torchvision==0.15.1a0

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by soulitzer** [comment]
We should update the view to become reshape, backward should work regardless of stride

**Comment by lezcano** [comment]
cc @vfdev-5
