### ISSUE TITLE
SDPA + torch.compile: (*bias): last dimension must be contiguous

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#124289]
### 🐛 Describe the bug

Hi,

I noticed a bug with SDPA when using torch.compile, both on 2.2.2 and 2.3 RC.

Reproduction:
```
git clone https://github.com/huggingface/transformers.git
cd transformers
git checkout 40eb6d6c5fcdaf99b499c249640d41f28659565b (main branch)
```
and
```python
from transformers import LlamaForCausalLM
import torch

llm_name = "meta-llama/Llama-2-7b-hf"
llm = LlamaForCausalLM.from_pretrained(llm_name).cuda()

llm.forward = torch.compile(llm.forward, fullgraph=True)

attn_mask = torch.ones(1, 450, dtype = torch.long).cuda()
outputs = llm(torch.ones(1, 450, dtype = torch.long).cuda(), attention_mask=attn_mask)

print("------")

attn_mask = torch.ones(1, 1, dtype = torch.long).cuda()
outputs = llm(torch.ones(1, 1, dtype = torch.long).cuda(), attention_mask=attn_mask)
```

Interestingly, adding
```
query_states = query_states.contiguous()
key_states = key_states.contiguous()
value_states = value_states.contiguous()
causal_mask = causal_mask.contiguous()
```
before SDPA call does not help. So the error below is not very helpful.

We always have:
```
Traceback (most recent call last):
  File "/home/felix/test_compile.py", line 16, in <module>
    outputs = llm(torch.ones(1, 1, dtype = torch.long).cuda(), attention_mask=attn_mask)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/felix/transformers/src/transformers/models/llama/modeling_llama.py", line 1144, in forward
    @add_start_docstrings_to_model_forward(LLAMA_INPUTS_DOCSTRING)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 917, in forward
    return compiled_fn(full_args)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 88, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 505, in forward
    fw_outs = call_func_at_runtime_with_args(
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 906, in __call__
    return self.get_current_callable()(inputs)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 784, in run
    return model(new_inputs)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 934, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_felix/ea/ceaid5aqesabg6e5wow7dfa7mruu6carauiqwmtu6mwv6thztgup.py", line 1105, in call
    buf13 = aten._scaled_dot_product_efficient_attention.default(buf10, buf11, reinterpret_tensor(buf6, (1, 32, 1, 128), (4096, 128, 4096, 1), 0), reinterpret_tensor(buf12, (1, 32, 1, 1), (0, 0, 0, 0), 0), True)
  File "/home/felix/miniconda3/envs/fx/lib/python3.9/site-packages/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
RuntimeError: (*bias): last dimension must be contiguous
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @drisspg @ArthurZucker this seem to impact a relatively hot SDPA path

### Versions

```
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA DGX Display
GPU 4: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             128
On-line CPU(s) list:                0-127
Thread(s) per core:                 2
Core(s) per socket:                 64
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              49
Model name:                         AMD EPYC 7742 64-Core Processor
Stepping:                           0
Frequency boost:                    enabled
CPU MHz:                            1879.127
CPU max MHz:                        2250,0000
CPU min MHz:                        1500,0000
BogoMIPS:                           4491.21
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          2 MiB
L2 cache:                           32 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.4
[pip3] onnx==1.16.0
[pip3] onnx-graphsurgeon==0.3.27
[pip3] onnx-tool==0.9.0
[pip3] onnxruntime==1.17.3
[pip3] torch==2.3.0+cu121
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==2.3.0+cu121
[pip3] torchvision==0.18.0+cu121
[pip3] triton==2.3.0
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     2.3.0+cu121              pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                2.3.0+cu121              pypi_0    pypi
[conda] torchvision               0.18.0+cu121             pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
```

**Comment by fxmarty** [comment]
@eellison It appears https://github.com/pytorch/pytorch/pull/111721 did not fix everything

**Comment by ex3ndr** [comment]
I am getting similar problems with non-compiled one

**Comment by andersonbcdefg** [comment]
Same problem here

**Comment by eellison** [comment]
@mostafaelhoushi do you have a repro / tlparse ?

**Comment by mostafaelhoushi** [comment]
@eellison Here is the code snippet. Note that the error doesn't happen with `facebook/opt-125m` but happens with Llama:

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# model_name="facebook/opt-125m"
model_name="meta-llama/Llama-3.2-1B"
bs=1
seqlen=1
dtype=torch.bfloat16
device = "cuda"

model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=dtype, device_map=device)
input_ids = torch.randint(0, model.config.vocab_size, (bs, seqlen), device=device)
attention_mask = torch.ones((bs, seqlen), dtype=torch.long, device=device)

model = torch.compile(model, mode="max-autotune", fullgraph=True)

_ = model(input_ids=input_ids, attention_mask=attention_mask)
```

and here is the error log:
```
Traceback (most recent call last):
  File "/home/melhoushi/ao/examples/huggingface/dummy.py", line 16, in <module>
    _ = model(input_ids=input_ids, attention_mask=attention_mask)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1135, in forward
    @add_start_docstrings_to_model_forward(LLAMA_INPUTS_DOCSTRING)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 917, in forward
    return compiled_fn(full_args)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 88, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 505, in forward
    fw_outs = call_func_at_runtime_with_args(
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 906, in __call__
    return self.get_current_callable()(inputs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 838, in run
    return compiled_fn(new_inputs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 383, in deferred_cudagraphify
    fn, out = cudagraphify(model, inputs, new_static_input_idxs, *args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 411, in cudagraphify
    return manager.add_function(
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1943, in add_function
    return fn, fn(inputs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1757, in run
    out = self._run(new_inputs, function_id)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1798, in _run
    return self.run_eager(new_inputs, function_id)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1913, in run_eager
    return node.run(new_inputs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 616, in run
    out = self.wrapped_function.model(new_inputs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 934, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_melhoushi/tu/ctuaj6pwczywskrmrkiydobtpk4t427jr5oh63penyd43cknyozi.py", line 1274, in call
    buf16 = aten._scaled_dot_product_efficient_attention.default(buf11, reinterpret_tensor(buf13, (1, 32, 1, 64), (0, 64, 0, 1), 0), reinterpret_tensor(buf14, (1, 32, 1, 64), (0, 64, 0, 1), 0), reinterpret_tensor(buf15, (1, 32, 1, 1), (0, 0, 0, 0), 0), True)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/utils/_device.py", line 78, in __torch_function__
    return func(*args, **kwargs)
  File "/data/home/melhoushi/miniconda3/envs/any4/lib/python3.10/site-packages/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
RuntimeError: (*bias): last dimension must be contiguous
```

**Comment by eellison** [comment]
@mostafaelhoushi are you on nightly ?

**Comment by mostafaelhoushi** [comment]
Thanks @eellison . I tried nightly and the error is away, although the model is significantly slower than baseline, but I can create a new issue for that.

**Comment by abdulfatir** [comment]
@eellison oddly, #149857 may be somehow related. Do you have any thoughts?

@mostafaelhoushi Does #149857 sound familiar to you? Would be able to provide additional information on how your model was slower?

**Comment by eellison** [comment]
@abdulfatir there was a slowdown but it was later fixed with https://github.com/pytorch/pytorch/pull/146054.
