### ISSUE TITLE
Dynamo Export: Support for PixelShuffle

### ISSUE THREAD

**Issue by asfiyab-nvidia** [pytorch/pytorch#124338]
### 🐛 Describe the bug

I want to export a module containing [PixelShuffle](https://pytorch.org/docs/stable/generated/torch.nn.PixelShuffle.html) to ONNX. However, it looks like the Pixel Shuffle layer is unsupported. cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @moraxu

Here is a simple repro script with just the PixelShuffle layer:

```
import torch

class PixelShuffle_module(torch.nn.Module):
    def __init__(self):
        super(PixelShuffle_module, self).__init__()
        self.pixel_shuffle = torch.nn.PixelShuffle(3)

    def forward(self, data):
        return self.pixel_shuffle(data)

device = 'cuda'
model = PixelShuffle_module().to(device)
data = torch.randn(1, 9, 4, 4).to(device)
export_output = torch.onnx.dynamo_export(model, data)
``` 

The error during export is attached below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/exporter.py", line 1490, in dynamo_export
    ).export()
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/exporter.py", line 1223, in export
    graph_module = self.options.fx_tracer.generate_fx(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/torch_export_graph_extractor.py", line 96, in generate_fx
    return self.pre_export_passes(options, model, model.graph_module, updated_model_args)  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/torch_export_graph_extractor.py", line 117, in pre_export_passes
    ).analyze(infra.levels.ERROR)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 85, in analyze
    self._lint(analysis_result, diagnostic_level)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 37, in _lint
    self.diagnostic_context.log_and_raise_if_error(diagnostic)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 367, in log_and_raise_if_error
    raise RuntimeErrorWithDiagnostic(diagnostic)
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten.pixel_shuffle.default']}.
```

Note that the model only fails during dynamo export. Running `torch.export.export(model, args=(data,))` is error-free. 

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.16.0
[pip3] onnxscript==0.1.0.dev20240417
[pip3] optree==0.10.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a29
[pip3] torch==2.4.0.dev20240417+cu121
[pip3] torch-tensorrt==2.3.0a0
[pip3] torchaudio==2.2.0.dev20240417+cu121
[pip3] torchdata==0.7.1a0
[pip3] torchtext==0.17.0a0
[pip3] torchvision==0.19.0.dev20240417+cu121
[pip3] triton==2.2.0+e28a256

**Comment by asfiyab-nvidia** [comment]
cc @thiagocrepaldi

**Comment by asfiyab-nvidia** [comment]
Thanks for the contribution @MaanavD. The export is successful with the nightly version of ONNXScript. Closing
