### ISSUE TITLE
compiling profiler with ExecutionTraceObserver breaks

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#124500]
### 🐛 Describe the bug

Repro:
```python
import torch
import tempfile
import json
from torch.profiler import ExecutionTraceObserver

def fn():
  fp = tempfile.NamedTemporaryFile("w+t", suffix=".et.json", delete=False)
  fp.close()

  et = ExecutionTraceObserver()
  observer = et.register_callback(fp.name)

  with torch.profiler.profile(execution_trace_observer=observer) as prof:
    # OK if we graph break here
    torch.tensor([0, 2, 4, 6, 8])

  with open(fp.name) as f:
    et_graph = json.load(f)

out = torch.compile(fn, backend="eager")()
```

Error:
```
Exception ignored in: <function ExecutionTraceObserver.__del__ at 0x111004550>
Traceback (most recent call last):
  File "/Users/jw3468/local/pytorch1/torch/profiler/profiler.py", line 772, in __del__
    self.unregister_callback()
  File "/Users/jw3468/local/pytorch1/torch/profiler/profiler.py", line 812, in unregister_callback
    if self._registered:
AttributeError: 'ExecutionTraceObserver' object has no attribute '_registered'
W0419 10:45:10.610069 8385510080 torch/_logging/_internal.py:1016] [4/0] Profiler function <class 'torch.profiler.profiler.profile'> will be ignored
Traceback (most recent call last):
  File "/Users/jw3468/local/.tests/tst1.py", line 4029, in <module>
    out = torch.compile(fn, backend="eager")()
  File "/Users/jw3468/local/pytorch1/torch/_dynamo/eval_frame.py", line 403, in _fn
    return fn(*args, **kwargs)
  File "/Users/jw3468/local/.tests/tst1.py", line 4017, in fn
    fp = tempfile.NamedTemporaryFile("w+t", suffix=".et.json", delete=False)
  File "/Users/jw3468/local/.tests/tst1.py", line 4018, in torch_dynamo_resume_in_fn_at_4017
    fp.close()
  File "/Users/jw3468/local/.tests/tst1.py", line 4020, in torch_dynamo_resume_in_fn_at_4018
    et = ExecutionTraceObserver()
  File "/Users/jw3468/local/.tests/tst1.py", line 4021, in torch_dynamo_resume_in_fn_at_4020
    observer = et.register_callback(fp.name)
  File "/Users/jw3468/local/.tests/tst1.py", line 4026, in torch_dynamo_resume_in_fn_at_4021
    with open(fp.name) as f:
  File "/Users/jw3468/local/.tests/tst1.py", line 4027, in torch_dynamo_resume_in_fn_at_4026
    et_graph = json.load(f)
  File "/Users/jw3468/opt/miniconda3/envs/pytorch1/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/jw3468/opt/miniconda3/envs/pytorch1/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/jw3468/opt/miniconda3/envs/pytorch1/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jw3468/opt/miniconda3/envs/pytorch1/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by anijain2305** [comment]
@soulitzer Can we close the bug?  I am adding low priority just to reflect David's point.
