### ISSUE TITLE
ERROR: No matching distribution found for torchvision==0.6.0+cu121

### ISSUE THREAD

**Issue by linkpharm** [pytorch/pytorch#124587]
### 🐛 Describe the bug

Torchvision isn't available for CUDA toolkit 12.1 and torchvision 0.6.0. Here's the bug, I am trying to run https://github.com/Fanghua-Yu/SUPIR. Thanks in advance.

```
C:\Users\Luke\Supir_Install\SUPIR>pip install torch==2.2.2+cu121 torchvision==0.6.0+cu121 torchaudio==0.6.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==2.2.2+cu121
  Using cached https://download.pytorch.org/whl/cu121/torch-2.2.2%2Bcu121-cp310-cp310-win_amd64.whl (2454.8 MB)
ERROR: Ignored the following yanked versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.15.0
ERROR: Could not find a version that satisfies the requirement torchvision==0.6.0+cu121 (from versions: 0.1.6, 0.2.0, 0.12.0, 0.12.0+cpu, 0.12.0+cu113, 0.12.0+cu115, 0.13.0, 0.13.0+cpu, 0.13.0+cu113, 0.13.0+cu116, 0.13.1, 0.13.1+cpu, 0.13.1+cu113, 0.13.1+cu116, 0.14.0, 0.14.0+cpu, 0.14.0+cu116, 0.14.0+cu117, 0.14.1, 0.14.1+cpu, 0.14.1+cu116, 0.14.1+cu117, 0.15.0+cpu, 0.15.0+cu117, 0.15.0+cu118, 0.15.1, 0.15.1+cpu, 0.15.1+cu117, 0.15.1+cu118, 0.15.2, 0.15.2+cpu, 0.15.2+cu117, 0.15.2+cu118, 0.16.0, 0.16.0+cpu, 0.16.0+cu118, 0.16.0+cu121, 0.16.1, 0.16.1+cpu, 0.16.1+cu118, 0.16.1+cu121, 0.16.2, 0.16.2+cpu, 0.16.2+cu118, 0.16.2+cu121, 0.17.0, 0.17.0+cpu, 0.17.0+cu118, 0.17.0+cu121, 0.17.1, 0.17.1+cpu, 0.17.1+cu118, 0.17.1+cu121, 0.17.2, 0.17.2+cpu, 0.17.2+cu118, 0.17.2+cu121)
ERROR: No matching distribution found for torchvision==0.6.0+cu121
```

Here's the error for SUPIR, which explains why I'm attempting to install this version.

```
C:\Users\Luke\Supir_Install\SUPIR>python gradio_demo.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.2+cu118 with CUDA 1108 (you have 2.2.2+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "C:\Users\Luke\Supir_Install\SUPIR\gradio_demo.py", line 11, in <module>
    from llava.llava_agent import LLavaAgent
  File "C:\Users\Luke\Supir_Install\SUPIR\llava\__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "C:\Users\Luke\Supir_Install\SUPIR\llava\model\__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "C:\Users\Luke\Supir_Install\SUPIR\llava\model\language_model\llava_llama.py", line 139, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "C:\Python310\lib\site-packages\transformers\models\auto\configuration_auto.py", line 981, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "C:\Python310\lib\site-packages\transformers\models\auto\configuration_auto.py", line 680, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.
```

```
C:\Users\Luke\Supir_Install\SUPIR>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

### Versions

Sorry, but this doesn't seem to work either. 

```
C:\Users\Luke>wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
'wget' is not recognized as an internal or external command,
operable program or batch file.
```

cc @seemethere @malfet @osalpekar @atalman

**Comment by colesbury** [comment]
There's no `torchvision` **0.6.0** package for CUDA 12.1. You need to use a newer torchvision package. 0.6.0 is pretty old.
