### ISSUE TITLE
Unable to use `torch.compile()` with triton's `TensorWrapper` in custom triton kernel

### ISSUE THREAD

**Issue by snarayan21** [pytorch/pytorch#124601]
### 🐛 Describe the bug

I have a custom kernel in triton for a matrix multiplication in fp8. To use torch fp8 dtypes with triton, triton's `reinterpret` function is necessary, which wraps the tensor in a `TensorWrapper` ([link](https://github.com/openai/triton/blob/35d6df1da41ab6c84c6cda22522afd4cc51f11d9/python/triton/runtime/jit.py#L757)). The kernel runs fine without `torch.compile`, but with it, I get the error in the logs below. 

Here's a small example that uses triton's own `matmul` kernel, but the example errors out with a different error. I suspect the two may be linked though?

### Error logs

Error logs with accessing `data_ptr` of `TensorWrapper` -- I looked at the doc that was linked in the error message, but it just said that custom triton kernels should be supported.
```
[rank0]: ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                                                                         │
[rank0]: │                                                                                                  │
[rank0]: │ /llm-foundry-private/llmfoundry/models/utils/triton_matmul_kernel_orig.py:397 in simpler_matmul  │
[rank0]: │                                                                                                  │
[rank0]: │   394 │   return c                                                                               │
[rank0]: │   395                                                                                            │
[rank0]: │   396 def simpler_matmul(afp8, bfp8, out_scale=1.0, acc_dtype=None, allow_tf32=None, fp8_fast_   │
[rank0]: │ ❱ 397 │   return _simpler_matmul_call(afp8, bfp8, out_scale, acc_dtype, allow_tf32, fp8_fast_a   │
[rank0]: │   398                                                                                            │
[rank0]: │                                                                                                  │
[rank0]: │ /llm-foundry-private/llmfoundry/models/utils/triton_matmul_kernel_orig.py:384 in                 │
[rank0]: │ _simpler_matmul_call                                                                             │
[rank0]: │                                                                                                  │
[rank0]: │   381 │   │   │   fp8_fast_accum=fp8_fast_accum,  #                                              │
[rank0]: │   382 │   │   │   GROUP_M=8, AB_DTYPE=ab_dtype)                                                  │
[rank0]: │   383 │   else:                                                                                  │
[rank0]: │ ❱ 384 │   │   _scaled_kernel[grid](                                                              │
[rank0]: │   385 │   │   │   a, b, c, M, N, K,  #                                                           │
[rank0]: │   386 │   │   │   a.stride(0), a.stride(1),  #                                                   │
[rank0]: │   387 │   │   │   b.stride(0), b.stride(1),  #                                                   │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/jit.py:180 in <lambda>                             │
[rank0]: │                                                                                                  │
[rank0]: │   177 │   │   Hence JITFunction.__getitem__ returns a callable proxy that                        │
[rank0]: │   178 │   │   memorizes the grid.                                                                │
[rank0]: │   179 │   │   """                                                                                │
[rank0]: │ ❱ 180 │   │   return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs   │
[rank0]: │   181 │   │   # return cast(T, functools.partial(cast(Callable, self.run), grid=grid))           │
[rank0]: │   182                                                                                            │
[rank0]: │   183                                                                                            │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/autotuner.py:141 in run                            │
[rank0]: │                                                                                                  │
[rank0]: │   138 │   │   │   │   # prune configs                                                            │
[rank0]: │   139 │   │   │   │   pruned_configs = self.prune_configs(kwargs)                                │
[rank0]: │   140 │   │   │   │   bench_start = time.time()                                                  │
[rank0]: │ ❱ 141 │   │   │   │   timings = {config: self._bench(*args, config=config, **kwargs) for confi   │
[rank0]: │   142 │   │   │   │   bench_end = time.time()                                                    │
[rank0]: │   143 │   │   │   │   self.bench_time = bench_end - bench_start                                  │
[rank0]: │   144 │   │   │   │   self.cache[key] = builtins.min(timings, key=timings.get)                   │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/autotuner.py:141 in <dictcomp>                     │
[rank0]: │                                                                                                  │
[rank0]: │   138 │   │   │   │   # prune configs                                                            │
[rank0]: │   139 │   │   │   │   pruned_configs = self.prune_configs(kwargs)                                │
[rank0]: │   140 │   │   │   │   bench_start = time.time()                                                  │
[rank0]: │ ❱ 141 │   │   │   │   timings = {config: self._bench(*args, config=config, **kwargs) for confi   │
[rank0]: │   142 │   │   │   │   bench_end = time.time()                                                    │
[rank0]: │   143 │   │   │   │   self.bench_time = bench_end - bench_start                                  │
[rank0]: │   144 │   │   │   │   self.cache[key] = builtins.min(timings, key=timings.get)                   │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/autotuner.py:120 in _bench                         │
[rank0]: │                                                                                                  │
[rank0]: │   117 │   │   │   self.post_hook(args)                                                           │
[rank0]: │   118 │   │                                                                                      │
[rank0]: │   119 │   │   try:                                                                               │
[rank0]: │ ❱ 120 │   │   │   return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, qua   │
[rank0]: │   121 │   │   except OutOfResources:                                                             │
[rank0]: │   122 │   │   │   return [float("inf"), float("inf"), float("inf")]                              │
[rank0]: │   123                                                                                            │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/testing.py:100 in do_bench                                 │
[rank0]: │                                                                                                  │
[rank0]: │    97 │   :type fast_flush: bool                                                                 │
[rank0]: │    98 │   """                                                                                    │
[rank0]: │    99 │                                                                                          │
[rank0]: │ ❱ 100 │   fn()                                                                                   │
[rank0]: │   101 │   torch.cuda.synchronize()                                                               │
[rank0]: │   102 │                                                                                          │
[rank0]: │   103 │   # We maintain a buffer of 256 MB that we clear                                         │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/autotuner.py:110 in kernel_call                    │
[rank0]: │                                                                                                  │
[rank0]: │   107 │   │   │   if config.pre_hook:                                                            │
[rank0]: │   108 │   │   │   │   config.pre_hook(full_nargs)                                                │
[rank0]: │   109 │   │   │   self.pre_hook(args)                                                            │
[rank0]: │ ❱ 110 │   │   │   self.fn.run(                                                                   │
[rank0]: │   111 │   │   │   │   *args,                                                                     │
[rank0]: │   112 │   │   │   │   num_warps=config.num_warps,                                                │
[rank0]: │   113 │   │   │   │   num_stages=config.num_stages,                                              │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/autotuner.py:296 in run                            │
[rank0]: │                                                                                                  │
[rank0]: │   293 │   def run(self, *args, **kwargs):                                                        │
[rank0]: │   294 │   │   for v, heur in self.values.items():                                                │
[rank0]: │   295 │   │   │   kwargs[v] = heur({**dict(zip(self.arg_names, args)), **kwargs})                │
[rank0]: │ ❱ 296 │   │   return self.fn.run(*args, **kwargs)                                                │
[rank0]: │   297                                                                                            │
[rank0]: │   298                                                                                            │
[rank0]: │   299 def heuristics(values):                                                                    │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/jit.py:374 in run                                  │
[rank0]: │                                                                                                  │
[rank0]: │   371 │   │   # compute cache key                                                                │
[rank0]: │   372 │   │   args = [KernelArg(arg_value, param) for (_, arg_value), param in zip(bound_args.   │
[rank0]: │   373 │   │   sig_key = tuple(arg.signature_key() for arg in args if not arg.param.is_constexp   │
[rank0]: │ ❱ 374 │   │   spec_key = tuple(arg.specialization_key() for arg in args if not arg.param.do_no   │
[rank0]: │   375 │   │   constexpr_key = tuple(arg.value for arg in args if arg.param.is_constexpr)         │
[rank0]: │   376 │   │   key = (sig_key, constexpr_key, spec_key, options)                                  │
[rank0]: │   377 │   │   key = str(key)                                                                     │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/jit.py:374 in <genexpr>                            │
[rank0]: │                                                                                                  │
[rank0]: │   371 │   │   # compute cache key                                                                │
[rank0]: │   372 │   │   args = [KernelArg(arg_value, param) for (_, arg_value), param in zip(bound_args.   │
[rank0]: │   373 │   │   sig_key = tuple(arg.signature_key() for arg in args if not arg.param.is_constexp   │
[rank0]: │ ❱ 374 │   │   spec_key = tuple(arg.specialization_key() for arg in args if not arg.param.do_no   │
[rank0]: │   375 │   │   constexpr_key = tuple(arg.value for arg in args if arg.param.is_constexpr)         │
[rank0]: │   376 │   │   key = (sig_key, constexpr_key, spec_key, options)                                  │
[rank0]: │   377 │   │   key = str(key)                                                                     │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/jit.py:159 in specialization_key                   │
[rank0]: │                                                                                                  │
[rank0]: │   156 │   │   assert not self.param.do_not_specialize                                            │
[rank0]: │   157 │   │                                                                                      │
[rank0]: │   158 │   │   if hasattr(self.value, "data_ptr"):                                                │
[rank0]: │ ❱ 159 │   │   │   return (self.value.data_ptr() % JITFunction.divisibility == 0, )               │
[rank0]: │   160 │   │                                                                                      │
[rank0]: │   161 │   │   if isinstance(self.value, int):                                                    │
[rank0]: │   162 │   │   │   # bool is a subclass of int, so we don't check explicitly above.               │
[rank0]: │                                                                                                  │
[rank0]: │ /usr/lib/python3/dist-packages/triton/runtime/jit.py:616 in data_ptr                             │
[rank0]: │                                                                                                  │
[rank0]: │   613 │   │   self.shape = self.base.shape                                                       │
[rank0]: │   614 │                                                                                          │
[rank0]: │   615 │   def data_ptr(self):                                                                    │
[rank0]: │ ❱ 616 │   │   return self.base.data_ptr()                                                        │
[rank0]: │   617 │                                                                                          │
[rank0]: │   618 │   def stride(self, i):                                                                   │
[rank0]: │   619 │   │   return self.base.stride(i)                                                         │
[rank0]: ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[rank0]: TorchRuntimeError: Failed running call_function <function produce_trampoline_autograd_apply.<locals>.trampoline_autograd_apply at 0x7fd1aba3bf40>(*(FakeTensor(..., device='cuda:0',
[rank0]: size=(4, 4096, 5120), dtype=torch.bfloat16,
[rank0]:            grad_fn=<CloneBackward0>), FakeTensor(..., device='cuda:0', size=(15360, 5120), dtype=torch.bfloat16,
[rank0]:            grad_fn=<AsStridedBackward0>), 0.013975424859373685), **{}):
[rank0]: Cannot access data pointer of Tensor (e.g. FakeTensor, FunctionalTensor). If you're using torch.compile/export/fx, it is likely that we are erroneously tracing into a custom kernel. To
[rank0]: fix this, please wrap the custom kernel into an opaque custom op. Please see the following for details: https://docs.google.com/document/d/1W--T6wz8IY8fOI0Vm8BF44PdBgs283QvpelJZWieQWQ
```

Error logs from my small attempt at a repro:
```
Traceback (most recent call last):
  File "/llm-foundry-private/llmfoundry/models/utils/repro_compile.py", line 42, in <module>
    z = cast_fp8_mm_scale(x, y, out_scale)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/eval_frame.py", line 403, in _fn
    return fn(*args, **kwargs)
  File "/llm-foundry-private/llmfoundry/models/utils/repro_compile.py", line 34, in cast_fp8_mm_scale
    x_fp8 = convert_fp8_tensor(x)
  File "/llm-foundry-private/llmfoundry/models/utils/repro_compile.py", line 35, in torch_dynamo_resume_in_cast_fp8_mm_scale_at_34
    y_fp8 = convert_fp8_tensor(y)
  File "/llm-foundry-private/llmfoundry/models/utils/repro_compile.py", line 36, in torch_dynamo_resume_in_cast_fp8_mm_scale_at_35
    return mm_scale(x_fp8, y_fp8, out_scale)
  File "/llm-foundry-private/llmfoundry/models/utils/repro_compile.py", line 13, in mm_scale
    return (tt_ops.matmul(x, y) * out_scale).to(torch.bfloat16)
  File "/usr/lib/python3/dist-packages/torch/autograd/function.py", line 571, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/lib/python3/dist-packages/triton/ops/matmul.py", line 215, in forward
    return _matmul._call(a, b, acc_dtype=acc_dtype, allow_tf32=allow_tf32, fp8_fast_accum=fp8_fast_accum,
  File "/usr/lib/python3/dist-packages/triton/ops/matmul.py", line 202, in _call
    _kernel[grid](
  File "/usr/lib/python3/dist-packages/triton/runtime/jit.py", line 180, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/triton/runtime/autotuner.py", line 141, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/usr/lib/python3/dist-packages/triton/runtime/autotuner.py", line 141, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/usr/lib/python3/dist-packages/triton/runtime/autotuner.py", line 103, in _bench
    current = dict(meta, **config.kwargs)
  File "/usr/lib/python3/dist-packages/triton/runtime/autotuner.py", line 120, in torch_dynamo_resume_in__bench_at_103
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
  File "/usr/lib/python3/dist-packages/triton/testing.py", line 100, in do_bench
    fn()
  File "/usr/lib/python3/dist-packages/triton/runtime/autotuner.py", line 110, in kernel_call
    self.fn.run(
  File "/usr/lib/python3/dist-packages/triton/runtime/autotuner.py", line 296, in run
    return self.fn.run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/triton/runtime/jit.py", line 349, in run
    device = driver.active.get_current_device()
  File "/usr/lib/python3/dist-packages/triton/runtime/jit.py", line 350, in torch_dynamo_resume_in_run_at_349
    stream = driver.active.get_current_stream(device)
  File "/usr/lib/python3/dist-packages/triton/runtime/jit.py", line 351, in torch_dynamo_resume_in_run_at_350
    target = driver.active.get_current_target()
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 977, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 818, in _convert_frame
    result = inner_convert(
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 411, in _convert_frame_assert
    return _compile(
  File "/usr/lib/python3/dist-packages/torch/_utils_internal.py", line 70, in wrapper_function
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 729, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 700, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/utils.py", line 267, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 568, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1116, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 173, in _fn
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/convert_frame.py", line 515, in transform
    tracer.run()
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 2237, in run
    super().run()
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 875, in run
    while self.step():
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 790, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 492, in wrapper
    return inner_fn(self, inst)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 1260, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 730, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/lib/python3/dist-packages/torch/_dynamo/variables/functions.py", line 339, in call_function
    return super().call_function(tx, args, kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 736, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 2418, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 2534, in inline_call_
    tracer.run()
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 875, in run
    while self.step():
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 790, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 1010, in LOAD_GLOBAL
    source = self.get_global_source(name)
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 974, in get_global_source
    self.import_source(self.f_globals["__name__"]), name
  File "/usr/lib/python3/dist-packages/torch/_dynamo/symbolic_convert.py", line 1036, in import_source
    value = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
torch._dynamo.exc.InternalTorchDynamoError: No module named 'nvi'
```

### Versions

```
PyTorch version: 2.4.0.dev20240420+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.19.17-coreweave-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 535.161.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           143
Model name:                      Intel(R) Xeon(R) Platinum 8462Y+
Stepping:                        8
Frequency boost:                 enabled
CPU MHz:                         3561.306
CPU max MHz:                     2801.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        128 MiB
L3 cache:                        120 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hfi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr ibt amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] onnx==1.14.0
[pip3] onnxruntime==1.15.1
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-triton==3.0.0+989adb9a29
[pip3] torch==2.4.0.dev20240420+cu121
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==1.0.3
[pip3] torchvision==0.19.0.dev20240420+cu121
[pip3] triton-nightly==3.0.0.post20240421065522
[conda] Could not collect
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @oulgen @aakhundov

**Comment by masnesral** [comment]
@oulgen this is related to your work supporting user-defined triton kernels, correct? If so, how shall we label this for tracking purposes?

**Comment by snarayan21** [comment]
Hey, sorry for the delay. I won't be needing this anymore for now, so I'll close it.
