### ISSUE TITLE
test_sync_params_ in test_c10d.py is broken

### ISSUE THREAD

**Issue by ygfeng** [pytorch/pytorch#12463]
## 🐛 Bug
Running unittest for suite c10d, encountering failure on `test_sync_params_no_buffers` & `test_sync_params_with_buffers`

```
python test/run_test.py -i c10d -v
Selected tests: c10d
Running test_c10d ...
command run python test_c10d.py --verbose
test_dist_broadcast_coalesced (__main__.DistributedDataParallelTest) ... ok
test_fp16 (__main__.DistributedDataParallelTest) ... ok
test_gloo_backend (__main__.DistributedDataParallelTest) ... ok
test_nccl_backend (__main__.DistributedDataParallelTest) ... ok
test_sync_params_no_buffers (__main__.DistributedDataParallelTest) ... Process process 1:
Traceback (most recent call last):
  File "/home/builder/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/builder/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "test_c10d.py", line 338, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_c10d.py", line 302, in wrapper
    fn(self)
  File "test_c10d.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "test_c10d.py", line 756, in test_sync_params_no_buffers
    broadcast_buffers=False)
RuntimeError: all tensors must be on devices[0]
FAIL
test_sync_params_with_buffers (__main__.DistributedDataParallelTest) ... Process process 1:
Traceback (most recent call last):
  File "/home/builder/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/builder/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "test_c10d.py", line 338, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_c10d.py", line 302, in wrapper
    fn(self)
  File "test_c10d.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "test_c10d.py", line 790, in test_sync_params_with_buffers
    broadcast_buffers=True)
RuntimeError: all tensors must be on devices[0]

```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 2.7
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 4 Tesla v100

## Additional context

```
def test_sync_params_no_buffers(self):
...
parameter_data += [torch.zeros(10, device=torch.device('cuda', d)).chunk(5) for d in devices[1:]]
...
        c10d._sync_params(
            process_group,
            parameter_data=parameter_data,
            buffer_data=buffer_data,
            devices=devices,
            broadcast_bucket_size=10,
            broadcast_buffers=True)
```

Testcase is assigning tensors to all cuda devices in the  parameter_data, it seems the c code is expecting the list of tensors to all reside on gpu0.

```
 pytorch/torch/csrc/cuda/comm.cpp
tensor_list2d broadcast_coalesced(TensorList tensors, IntList devices, size_t buffer_size) {
  if (!std::all_of(tensors.begin(), tensors.end(),
                   [&](const at::Tensor& t) { return t.get_device() == devices[0]; })) {
    throw std::runtime_error("all tensors must be on devices[0]");
}
```

**Comment by ngimel** [comment]
Closing due to age
