### ISSUE TITLE
TestAOTAutograd.test_mem_leak_from_save_for_bw fails locally but not on CI when run with dynamo

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#124747]
I was trying to repro the recent flaky tests that CI was reported, when CI runs AOTAutograd tets on the dynamo shard.

However I noticed that this test would reliably fail in isolation for me locally:
```
PYTORCH_TEST_WITH_DYNAMO=1 python test/functorch/test_aotdispatch.py TestAOTAutograd.test_mem_leak_from_save_for_bw
```

@zou3519 pointed out that due to the fact that dynamo.reset doesn't reset **all** global state, it is technically possible that this test might not be failing in CI when run with the rest of the test suite.

**Comment by jbschlosser** [comment]
I can repro this consistently locally too.

**Comment by williamwen42** [comment]
I'm getting a compiled autograd error:
```
======================================================================
ERROR: test_mem_leak_from_save_for_bw (__main__.TestAOTAutograd.test_mem_leak_from_save_for_bw)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch3/torch/testing/_internal/common_utils.py", line 3223, in wrapper
    method(*args, **kwargs)
  File "/data/users/williamwen/pytorch3/test/functorch/test_aotdispatch.py", line 2944, in test_mem_leak_from_save_for_bw
    f_compiled = aot_function(f, nop)
  File "/data/users/williamwen/pytorch3/test/functorch/test_aotdispatch.py", line 2946, in torch_dynamo_resume_in_test_mem_leak_from_save_for_bw_at_2944
    torch.ones(8, 8, device="cuda", requires_grad=True),
  File "/data/users/williamwen/pytorch3/test/functorch/test_aotdispatch.py", line 2947, in torch_dynamo_resume_in_test_mem_leak_from_save_for_bw_at_2946
    torch.ones(1, 4, 1, device="cuda", requires_grad=True),
  File "/data/users/williamwen/pytorch3/test/functorch/test_aotdispatch.py", line 2949, in torch_dynamo_resume_in_test_mem_leak_from_save_for_bw_at_2947
    mem_before = torch.cuda.memory_allocated()
  File "/data/users/williamwen/pytorch3/test/functorch/test_aotdispatch.py", line 2950, in torch_dynamo_resume_in_test_mem_leak_from_save_for_bw_at_2949
    f_compiled(*inps)
  File "/data/users/williamwen/pytorch3/torch/_functorch/aot_autograd.py", line 820, in returned_function
    aot_graph_capture = aot_stage1_graph_capture(aot_state, flat_fn)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_compile.py", line 161, in aot_stage1_graph_capture
    aot_dispatch_autograd_graph(
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture.py", line 436, in aot_dispatch_autograd_graph
    fx_g = _create_graph(
           ^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture.py", line 82, in _create_graph
    fx_g = make_fx(
           ^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/experimental/proxy_tensor.py", line 2351, in wrapped
    return make_fx_tracer.trace(f, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/experimental/proxy_tensor.py", line 2283, in trace
    return self._trace_inner(f, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/experimental/proxy_tensor.py", line 2254, in _trace_inner
    t = dispatch_trace(
        ^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_compile.py", line 53, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_dynamo/eval_frame.py", line 1005, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/experimental/proxy_tensor.py", line 1283, in dispatch_trace
    graph = tracer.trace(root, concrete_args)  # type: ignore[arg-type]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_dynamo/eval_frame.py", line 1005, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/_symbolic_trace.py", line 850, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/_symbolic_trace.py", line 703, in flatten_fn
    tree_out = root_fn(*tree_args)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/experimental/proxy_tensor.py", line 1341, in wrapped
    out = f(*tensors)  # type:ignore[call-arg]
          ^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture.py", line 70, in inner_f
    out, out_descs = call_and_expect_output_descs(f, args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/utils.py", line 549, in call_and_expect_output_descs
    outs_pair = fn(*args)
                ^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture_wrappers.py", line 1094, in inner_fn
    outs, outs_descs = call_and_expect_output_descs(fn, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/utils.py", line 549, in call_and_expect_output_descs
    outs_pair = fn(*args)
                ^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture_wrappers.py", line 1042, in joint_helper
    return _functionalized_f_helper(primals, tangents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture_wrappers.py", line 800, in _functionalized_f_helper
    f_outs, f_outs_descs = call_and_expect_output_descs(fn, f_args)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/utils.py", line 549, in call_and_expect_output_descs
    outs_pair = fn(*args)
                ^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture_wrappers.py", line 430, in inner_fn_with_anomaly
    return inner_fn(primals, tangents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_functorch/_aot_autograd/graph_capture_wrappers.py", line 396, in inner_fn
    backward_out = torch.autograd.grad(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/autograd/__init__.py", line 452, in grad
    return handle_torch_function(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/overrides.py", line 1727, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/fx/experimental/proxy_tensor.py", line 1389, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/autograd/__init__.py", line 503, in grad
    result = _engine_run_backward(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/autograd/graph.py", line 829, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/williamwen/pytorch3/torch/_dynamo/compiled_autograd.py", line 1017, in end_capture
    self.reorder_pre_hook_nodes_to_mimic_eager()
  File "/data/users/williamwen/pytorch3/torch/_dynamo/compiled_autograd.py", line 1228, in reorder_pre_hook_nodes_to_mimic_eager
    registered_node = next(iter(users[0].users.keys()))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

cc @xmfan
