### ISSUE TITLE
torch.nn.init.orthogonal fails with LAPACK error

### ISSUE THREAD

**Issue by Maratyszcza** [pytorch/pytorch#1247]
Reproducer:
```
>>> import torch.nn as nn
>>> import torch.nn.init as init
>>> layer = nn.Conv2d(3, 64, kernel_size=(3, 3))
>>> init.orthogonal(layer.weight.data)

Intel MKL ERROR: Parameter 6 was incorrect on entry to SGESVD.

Intel MKL ERROR: Parameter 3 was incorrect on entry to SGESVD.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/init.py", line 216, in orthogonal
    u, s, v = torch.svd(flattened, some=True)
RuntimeError: Lapack Error in gesvd : Illegal Argument 3 at /home/marat/tools/pytorch/pytorch/torch/lib/TH/generic/THTensorLapack.c:461
```

**Comment by szagoruyko** [comment]
this should be solved by https://github.com/torch/torch7/pull/1002 - the Windows PR was breaking MKL

**Comment by soumith** [comment]
i just merged that into pytorch less than 1 hour ago. so check against master and see if master works.

**Comment by Maratyszcza** [comment]
@soumith It seems that something else broke now. After re-building `torch` I get the error:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: No module named _C
```

**Comment by Maratyszcza** [comment]
Note that `_C.so` exists in `/usr/local/lib/python2.7/dist-packages/torch` (where, according to logs, is was copied), `pip list` includes `torch (0.1.11+d122b4e)`

**Comment by Maratyszcza** [comment]
@soumith Thanks, orthogonal init works now!
