### ISSUE TITLE
`RuntimeError: invalid dtype for bias` when use compile + autocast

### ISSUE THREAD

**Issue by yiliu30** [pytorch/pytorch#124901]
### 🐛 Describe the bug

When I tried using `torch.compile` along with `autocast` to infereance a llama's decoder block, I encountered `RuntimeError: invalid dtype for bias - should match query's dtype`.

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from torch.amp import autocast
model_name = "/models/Llama-2-7b-chat-hf/"
#model_name = "meta-llama/Llama-2-7b-hf"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
device = "cuda"
amp_dtype = torch.float16
block = model.model.layers[0]
block = block.to(device).to(amp_dtype)

input_ids = torch.randn(8, 2048, 4096).to(amp_dtype).to(device)
input_others = {
    "attention_mask": torch.randn(8, 1, 2048, 2048).to(amp_dtype).to(device),
    "position_ids": torch.arange(2048).unsqueeze(0).to(torch.int64).to(device),
    "cache_position": torch.arange(2048).to(torch.int64).to(device),
}

opt_block = torch.compile(block)
#opt_block     = block
out_without_amp = opt_block.forward(input_ids, **input_others)
print(f"out_without_amp[0].shape: {out_without_amp[0].shape}")

with autocast(device_type=device, dtype=amp_dtype):
    out = opt_block.forward(input_ids, **input_others)
    print(f"out[0].shape: {out[0].shape}")

```

### Versions

```bash
$ python collect_env.py 
Collecting environment information...
PyTorch version: 2.4.0.dev20240318+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
Clang version: Could not collect
CMake version: version 3.29.0
Libc version: glibc-2.31

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-169-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

...
Versions of relevant libraries:
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] pytorch-triton==3.0.0+989adb9a29
[pip3] torch==2.4.0.dev20240318+cu121
[pip3] torchaudio==2.2.1
[pip3] torchvision==0.18.0.dev20240318+cu121
[pip3] triton==2.2.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.8            py39h5eee18b_0  
[conda] mkl_random                1.2.4            py39hdb19cb5_0  
[conda] numpy                     1.26.4           py39h5f9d8c6_0  
[conda] numpy-base                1.26.4           py39hb5e798b_0  
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            3.0.0+989adb9a29          pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] torchaudio                2.2.1                py39_cu121    pytorch
[conda] torchtriton               2.2.0                      py39    pytorch
[conda] torchvision               0.18.0.dev20240318+cu121          pypi_0    pypi
```

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by marcociccone** [comment]
is there any fix for this issue? I have the same exact issue when combining autocast and compile. Thanks.

**Comment by AleenahK** [comment]
I am having this issue. Is there a fix please??

**Comment by bdhirsh** [comment]
hmm... running the repro above on a nightly, even when I turn off torch.compile I get a shape mismatch:
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from torch.amp import autocast

model_name = "meta-llama/Llama-2-7b-hf"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
device = "cuda"
amp_dtype = torch.float16
block = model.model.layers[0]
block = block.to(device).to(amp_dtype)

input_ids = torch.randn(8, 2048, 4096).to(amp_dtype).to(device)
input_others = {
    "attention_mask": torch.randn(8, 1, 4096, 4096).to(amp_dtype).to(device),
    "position_ids": torch.arange(2048).unsqueeze(0).to(torch.int64).to(device),
    "cache_position": torch.arange(2048).to(torch.int64).to(device),
}

# skip compile
# opt_block = torch.compile(block)
opt_block = block
out_without_amp = opt_block.forward(input_ids, **input_others)
print(f"out_without_amp[0].shape: {out_without_amp[0].shape}")

with autocast(device_type=device, dtype=amp_dtype):
    out = opt_block.forward(input_ids, **input_others)
    print(f"out[0].shape: {out[0].shape}")
```

gives:
```
Traceback (most recent call last):
  File "/home/hirsheybar/local/a/pytorch/tmp3.py", line 22, in <module>
    out_without_amp = opt_block.forward(input_ids, **input_others)
  File "/home/hirsheybar/local/a/pytorch-env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 713, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/hirsheybar/local/a/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hirsheybar/local/a/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hirsheybar/local/a/pytorch-env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 649, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: The expanded size of the tensor (2048) must match the existing size (4096) at non-singleton dimension 2.  Target sizes: [8, 32, 2048, 2048].  Tensor sizes: [8, 1, 4096, 2048]
```

**Comment by yiliu30** [comment]
> hmm... running the repro above on a nightly, even when I turn off torch.compile I get a shape mismatch:
> 
> ```
> import torch
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from torch.amp import autocast
> 
> model_name = "meta-llama/Llama-2-7b-hf"
> model = AutoModelForCausalLM.from_pretrained(model_name)
> tokenizer = AutoTokenizer.from_pretrained(model_name)
> device = "cuda"
> amp_dtype = torch.float16
> block = model.model.layers[0]
> block = block.to(device).to(amp_dtype)
> 
> input_ids = torch.randn(8, 2048, 4096).to(amp_dtype).to(device)
> input_others = {
>     "attention_mask": torch.randn(8, 1, 4096, 4096).to(amp_dtype).to(device),
>     "position_ids": torch.arange(2048).unsqueeze(0).to(torch.int64).to(device),
>     "cache_position": torch.arange(2048).to(torch.int64).to(device),
> }
> 
> # skip compile
> # opt_block = torch.compile(block)
> opt_block = block
> out_without_amp = opt_block.forward(input_ids, **input_others)
> print(f"out_without_amp[0].shape: {out_without_amp[0].shape}")
> 
> with autocast(device_type=device, dtype=amp_dtype):
>     out = opt_block.forward(input_ids, **input_others)
>     print(f"out[0].shape: {out[0].shape}")
> ```
> 
> gives:
> 
> ```
> Traceback (most recent call last):
>   File "/home/hirsheybar/local/a/pytorch/tmp3.py", line 22, in <module>
>     out_without_amp = opt_block.forward(input_ids, **input_others)
>   File "/home/hirsheybar/local/a/pytorch-env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 713, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/home/hirsheybar/local/a/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/hirsheybar/local/a/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/hirsheybar/local/a/pytorch-env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 649, in forward
>     attn_output = torch.nn.functional.scaled_dot_product_attention(
> RuntimeError: The expanded size of the tensor (2048) must match the existing size (4096) at non-singleton dimension 2.  Target sizes: [8, 32, 2048, 2048].  Tensor sizes: [8, 1, 4096, 2048]
> ```

Sorry, the `att_mask` should be `8, 1, 2048, 2048`. I updated the repro code.

**Comment by yiliu30** [comment]
It works well with torch `2.5.0.dev20240812` !!!
