### ISSUE TITLE
RuntimeError: MPS: Unsupported Border padding mode

### ISSUE THREAD

**Issue by bukhalmae145** [pytorch/pytorch#125098]
### 🐛 Describe the bug

`python interpolate_video_forward_anyfps.py -i /Users/workstation/Movies/AFI-ForwardDeduplicate/input.mov -o /Users/workstation/Movies/AFI-ForwardDeduplicate/frames -nf 2 -fps 60 -m gmfss -s -st 12 -scale 1.0 -stf -c
Loaded model
  0%|                                                | 0/1108.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/interpolate_video_forward_anyfps.py", line 278, in <module>
    output0, count = decrease_inference(queue_input.copy())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/interpolate_video_forward_anyfps.py", line 207, in decrease_inference
    to_numpy(make_inf(inp0, inp1, scale, 0.5))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/interpolate_video_forward_anyfps.py", line 190, in make_inf
    return model.inference(x, y, model.reuse(x, y, _scale), timestep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/models/model_pg104/GMFSS.py", line 107, in inference
    rife = self.ifnet(imgs, timestep, scale_list=[8, 4, 2, 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/Deduplication/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/Deduplication/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/models/model_pg104/IFNet_HDv3.py", line 93, in forward
    warped_img0 = warp(img0, flow[:, :2])
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/models/model_pg104/warplayer.py", line 22, in warp
    return torch.nn.functional.grid_sample(input=tenInput, grid=g, mode='bilinear', padding_mode='border', align_corners=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/workstation/Movies/AFI-ForwardDeduplicate/Deduplication/lib/python3.11/site-packages/torch/nn/functional.py", line 4351, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS: Unsupported Border padding mode`

Source Code: https://www.dropbox.com/s/dfqbbuffjmo9f32/AFI-ForwardDeduplicate.zip?dl=0

I use M1 Mac.

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
--2024-04-27 16:21:23--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22068 (22K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  21.55K  --.-KB/s    in 0.02s

2024-04-27 16:21:24 (1005 KB/s) - ‘collect_env.py’ saved [22068/22068]

Collecting environment information...
PyTorch version: 2.3.0a0+git07330ff
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.28.3
Libc version: N/A

Python version: 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0.dev20240426
[pip3] torchvision==0.18.0
[conda] Could not collect

**Comment by jonahclarsen** [comment]
I'm getting the same error when running https://github.com/google-research/frame-interpolation on my M2 MBA with torch 2.1.2:
```
  File "\torch\nn\functional.py", line 4244, in grid_sample
        align_corners = False

    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
           ~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: MPS: Unsupported Border padding mode
```

**Comment by jonahclarsen** [comment]
I figured it out. The solution was, before exporting the torchscript model, change the padding mode from 'border' to 'zeros'. Haven't yet seen how this affects the model outputs however.

**Comment by bukhalmae145** [comment]
> I figured it out. The solution was, before exporting the torchscript model, change the padding mode from 'border' to 'zeros'. Haven't yet seen how this affects the model outputs however.

get this error if I change to 'zeros'

`File "/Users/workstation/Movies/AFI-ForwardDeduplicate/models/model_pg104/forward_warp2.py", line 173, in sample_one
    img_warp.put_(ids_mask, torch.masked_select(flat_img*flat_weight, mask), accumulate=True)
IndexError: out of range: tried to access index 33423360 on a tensor of 33423360 elements.`

**Comment by xcomart** [comment]
In the PyTorch documentation,

"If grid has values outside the range of [-1, 1], the corresponding outputs are handled as defined by padding_mode..."

So you can clamp grid values to [-1, 1] and use 'zero' padding mode, then the output would be same as 'border' padding mode.

below is sample code:

padding_mode = 'border'
if x.device.type == "mps":
    padding_mode = 'zeros'
    grid = grid.clamp(-1, 1)
output = F.grid_sample(input, grid, mode='bilinear', padding_mode=padding_mode, align_corners=False)

**Comment by malfet** [comment]
The `grid_sample` part of this is fixed: on torch 2.13.0 ...
