### ISSUE TITLE
clang-tidy still spuriously triggering for some files which include onnx_pb.h

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12512]
```
/usr/bin/clang-tidy-6.0 -p build -config {"Checks": " -* ,modernize-deprecated-headers ", "WarningsAsErrors": "*", "HeaderFilterRegex": "torch/csrc/.*", "AnalyzeTemporaryDtors": false, "CheckOptions": null} -line-filter [{"name": "torch/csrc/jit/graph_executor.cpp", "lines": [[13, 14], [448, 449]]}, {"name": "torch/csrc/jit/import.cpp", "lines": [[24, 31], [87, 88], [107, 110], [191, 191]]}, {"name": "torch/csrc/jit/init.cpp", "lines": [[18, 19], [92, 93]]}, {"name": "torch/csrc/jit/node_hashing.cpp", "lines": [[1, 114]]}, {"name": "torch/csrc/jit/passes/common_subexpression_elimination.cpp", "lines": [[9, 10], [14, 14]]}, {"name": "torch/csrc/jit/passes/constant_pooling.cpp", "lines": [[1, 54]]}, {"name": "torch/csrc/jit/script/compiler.cpp", "lines": [[4, 5], [907, 908]]}] torch/csrc/jit/graph_executor.cpp torch/csrc/jit/import.cpp torch/csrc/jit/init.cpp torch/csrc/jit/node_hashing.cpp torch/csrc/jit/passes/common_subexpression_elimination.cpp torch/csrc/jit/passes/constant_pooling.cpp torch/csrc/jit/script/compiler.cpp
Traceback (most recent call last):
  File "tools/clang_tidy.py", line 219, in <module>
    main()
  File "tools/clang_tidy.py", line 215, in main
    print(run_clang_tidy(options, line_filters, files))
  File "tools/clang_tidy.py", line 121, in run_clang_tidy
    raise RuntimeError(message.format(output))
RuntimeError: Found clang-diagnostic-errors in clang-tidy output: /home/travis/build/pytorch/pytorch/third_party/onnx/onnx/onnx_pb.h:52:10: error: 'onnx/onnx.pb.h' file not found [clang-diagnostic-error]
#include "onnx/onnx.pb.h"
```

from https://travis-ci.org/pytorch/pytorch/jobs/439274208

cc @goldsborough

**Comment by goldsborough** [comment]
I think this was before the fix. When I search for `onnx_pb.h` under `torch/csrc` I find

<img width="407" alt="screen shot 2018-10-17 at 11 53 51" src="https://user-images.githubusercontent.com/6429851/47074666-8c935200-d203-11e8-879d-e5b4e4de8e6f.png">

All of which are [blacklisted](https://github.com/pytorch/pytorch/blob/master/tools/run-clang-tidy-in-ci.sh#L45).
