### ISSUE TITLE
Investigate "Expected a value of type 'List[int]' for argument 'stride' but instead found type 'tuple' " when nn module inlining is enabled.

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#125638]
repo:
 TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1  python test/inductor/test_cuda_cpp_wrapper.py -k test_batch_norm_2d_2_cuda_dynamic_shapes_cuda_wrapper

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by laithsakka** [comment]
Looking at the code i see two places that have comments with same error 
    xfail('max_pool2d_with_indices_backward', ''),  # Expected a value of type 'List[int]' for argument 'kernel_size' but...

and
common_methods_invocations.py have it in multiple places, 

ex
```
OpInfo('nn.functional.adaptive_max_pool2d',
           dtypes=floating_types_and(torch.half, torch.bfloat16),
           decorators=(
               # RuntimeError:
               # adaptive_max_pool2d(Tensor input, int[2] output_size) -> (Tensor):
               # Expected a value of type 'List[int]' for argument 'output_size' but
               # instead found type 'Tuple[NoneType, int]'. :
               #   File "<string>", line 3
               # def the_method(i0):
               #     return torch.nn.functional.adaptive_max_pool2d(i0, (None, 7))
               #            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
               DecorateInfo(unittest.expectedFailure, 'TestJit', 'test_variant_consistency_jit'),
           ),
           ```

**Comment by laithsakka** [comment]
I tracked down the issue to the following, I feel that this is the issue:
we call
```
def convolution(
    x: TensorBox,
    weight: TensorBox,
    bias: TensorBox,
    stride: List[int],
    padding: List[int],
    dilation: List[int],
    transposed: bool,
    output_padding: List[int],
    groups: int,
):
``` 
but 
type(stride) is tuple and not List[int], same for padding and dilation

**Comment by laithsakka** [comment]
We ends up calling  torch.ops.aten.convolution with symbols, this happen because when we generate concrete args we actually do not generate values for non tensor inputs. 
I wonder if shall return the hint for symints
            args, kwargs = self.fetch_args_kwargs_from_env(n)

**Comment by ezyang** [comment]
Without backtrace, I can't be 100% sure, but it's probably a problem with this code

```
        is_arg_tensor = []
        tensor_args = []
        non_tensor_args: List[Any] = []
        for arg in args_flat:
            is_arg_tensor.append(isinstance(arg, IRNode))
            if is_arg_tensor[-1]:
                tensor_args.append(arg)
            else:
                if isinstance(arg, sympy.Expr):
                    arg = V.graph.sizevars.shape_env.create_symintnode(arg, hint=None)
                non_tensor_args.append(arg)
```

when we repropagate fake tensors through kernels, we need to convert Inductor representations back to regular PyTorch reps. The code here converts sympy.Expr back into SymInt so you can prop through them.

I'm guessing, for some reason, some of the sympy exprs are not getting converted in this way

**Comment by laithsakka** [comment]
full stack trace:
```
======================================================================
ERROR: test_batch_norm_2d_2_cuda_dynamic_shapes_cuda_wrapper (__main__.DynamicShapesCudaWrapperCudaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/lsakka/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2763, in wrapper
    method(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/test/inductor/test_torchinductor.py", line 9838, in new_test
    return value(self)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/testing.py", line 309, in _fn
    return fn(*args, **kwargs)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/test/inductor/test_cuda_cpp_wrapper.py", line 152, in fn
    _, code = test_torchinductor.run_and_get_cpp_code(
  File "/data/users/lsakka/pytorch/pytorch/test/inductor/test_torchinductor.py", line 355, in run_and_get_cpp_code
    result = fn(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/test/inductor/test_torchinductor.py", line 9838, in new_test
    return value(self)
  File "/data/users/lsakka/pytorch/pytorch/torch/testing/_internal/common_cuda.py", line 198, in wrapped
    return f(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/test/inductor/test_torchinductor.py", line 4100, in test_batch_norm_2d_2
    o2 = torch.compile(mod)(inp)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 416, in _fn
    return fn(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 981, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 822, in _convert_frame
    result = inner_convert(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 410, in _convert_frame_assert
    return _compile(
  File "/data/users/lsakka/pytorch/pytorch/torch/_utils_internal.py", line 70, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 703, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 570, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/bytecode_transformation.py", line 1167, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 172, in _fn
    return fn(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 517, in transform
    tracer.run()
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2234, in run
    super().run()
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 884, in run
    while self.step():
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 799, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2424, in RETURN_VALUE
    self._return(inst)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 2409, in _return
    self.output.compile_subgraph(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1104, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1296, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1387, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/output_graph.py", line 1368, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/repro/after_dynamo.py", line 127, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/lsakka/pytorch/pytorch/torch/__init__.py", line 1745, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1265, in compile_fx
    return compile_fx(
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1475, in compile_fx
    return aot_autograd(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/backends/common.py", line 65, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 958, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 685, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(
  File "/data/users/lsakka/pytorch/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 470, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/lsakka/pytorch/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 672, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/lsakka/pytorch/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 447, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1379, in fw_compiler_base
    return inner_compile(
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/compile_fx.py", line 495, in compile_fx_inner
    compiled_graph = FxGraphCache.load(
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/codecache.py", line 978, in load
    compiled_graph = compile_fx_fn(gm, example_inputs, **fx_kwargs)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/compile_fx.py", line 781, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/graph.py", line 728, in run
    return super().run(*args)
  File "/data/users/lsakka/pytorch/pytorch/torch/fx/interpreter.py", line 147, in run
    self.env[node] = self.run_node(node)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/graph.py", line 1187, in run_node
    result = self.call_function(n.target, args, kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/graph.py", line 975, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/graph.py", line 972, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/lowering.py", line 304, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/kernel/conv.py", line 390, in convolution
    layout = conv_layout(x, weight, None, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_inductor/kernel/conv.py", line 244, in conv_layout
    output = torch.ops.aten.convolution(
  File "/data/users/lsakka/pytorch/pytorch/torch/_ops.py", line 1024, in __call__
    return self_._op(*args, **(kwargs or {}))
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: RuntimeError: Overloaded torch operator invoked from Python failed to match any schema:
aten::convolution() Expected a value of type 'List[int]' for argument 'stride' but instead found type 'tuple'.
Position: 3
Value: (s4, s5)
Declaration: aten::convolution(Tensor input, Tensor weight, Tensor? bias, SymInt[] stride, SymInt[] padding, SymInt[] dilation, bool transposed, SymInt[] output_padding, SymInt groups) -> Tensor
Cast error details: Unable to cast Python instance of type <class 'sympy.core.symbol.Symbol'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)

aten::convolution() Expected a value of type 'List[int]' for argument 'stride' but instead found type 'tuple'.
Position: 3
Value: (s4, s5)
Declaration: aten::convolution.out(Tensor input, Tensor weight, Tensor? bias, SymInt[] stride, SymInt[] padding, SymInt[] dilation, bool transposed, SymInt[] output_padding, SymInt groups, *, Tensor(a!) out) -> Tensor(a!)
Cast error details: Unable to cast Python instance of type <class 'sympy.core.symbol.Symbol'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)


  target: aten.convolution.default
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='primals_5', layout=FixedLayout('cuda', torch.float32, size=[s0, 64, s2, s3], stride=[64*s2*s3, s2*s3, s3, 1]))
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='primals_1', layout=FixedLayout('cuda', torch.float32, size=[128, 64, 3, 3], stride=[576, 9, 3, 1]))
  ))
  args[2]: None
  args[3]: [s4, s5]
  args[4]: [1, 1]
  args[5]: [1, 1]
  args[6]: False
  args[7]: [0, 0]
  args[8]: 1

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


To execute this test, run the following from the base repo dir:
     python test/inductor/test_cuda_cpp_wrapper.py -k DynamicShapesCudaWrapperCudaTests.test_batch_norm_2d_2_cuda_dynamic_shapes_cuda_wrapper

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

**Comment by ezyang** [comment]
```
def conv_layout(
    x: TensorBox,
    weight: TensorBox,
    bias: Optional[TensorBox],
    stride: Sequence[int],
    padding: tuple[int, ...],
    dilation: tuple[int, ...],
    transposed: bool,
    output_padding: tuple[int, ...],
    groups: int,
) -> ir.Layout:
    """Determine output layout for a convolution"""
    with V.graph.fake_mode:
        output = torch.ops.aten.convolution(
            ir.ir_node_to_tensor(x, guard_shape=True),
            ir.ir_node_to_tensor(weight, guard_shape=True),
            ir.ir_node_to_tensor(bias, guard_shape=True),
            stride, 
            tuple(V.graph.sizevars.size_hint(p) for p in padding),  # type: ignore[arg-type]
            dilation,
            transposed,
            tuple(V.graph.sizevars.size_hint(p) for p in output_padding),  # type: ignore[arg-type]
            groups,
        )   

```

you need to size_hint the stride like the others here.

**Comment by laithsakka** [comment]
that fix it

**Comment by laithsakka** [comment]
I wonder if in general before calling any functions we shall go through all args and if any symbol is not substituted with a value we do that as a general aproach ?
