### ISSUE TITLE
Support dynamo tracing weakref obj

### ISSUE THREAD

**Issue by ydwu4** [pytorch/pytorch#125720]
### 🚀 The feature, motivation and pitch

For below code, we have a graph break right now:
```python
import torch
import weakref

class UserDefined:
    def __init__(self, x):
        self.x = x

    def __call__(self):
        return self.x.sin()

def f(obj):
    return ref()

obj = UserDefined(torch.randn(3))

ref = weakref.ref(obj)
ret = torch.compile(f, backend="eager", fullgraph=True)(ref)
```

```
(pytorch-3.10) ~/local/pytorch$ TORCH_LOGS="+dynamo" python test_dynamo.py 
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0] torchdynamo start compiling f /home/yidi/local/pytorch/test_dynamo.py:11, stack (elided 4 frames):
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0]   File "/home/yidi/local/pytorch/test_dynamo.py", line 17, in <module>
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0]     ret = torch.compile(f, backend="eager", fullgraph=True)(ref)
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0]   File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 416, in _fn
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0]     return fn(*args, **kwargs)
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 981, in catch_errors
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0]     return callback(frame, cache_entry, hooks, frame_state, skip=1)
V0507 15:55:27.189000 140217027146752 torch/_dynamo/convert_frame.py:678] [0/0] 
I0507 15:55:30.713000 140217027146752 torch/_dynamo/logging.py:55] [0/0] Step 1: torchdynamo start tracing f /home/yidi/local/pytorch/test_dynamo.py:11
V0507 15:55:30.714000 140217027146752 torch/fx/experimental/symbolic_shapes.py:2268] [0/0] create_env
V0507 15:55:30.716000 140217027146752 torch/_dynamo/symbolic_convert.py:769] [0/0] [__trace_source] TRACE starts_line /home/yidi/local/pytorch/test_dynamo.py:12 in f (f)
V0507 15:55:30.716000 140217027146752 torch/_dynamo/symbolic_convert.py:769] [0/0] [__trace_source]         return ref()
V0507 15:55:30.717000 140217027146752 torch/_dynamo/symbolic_convert.py:792] [0/0] [__trace_bytecode] TRACE LOAD_GLOBAL ref []
V0507 15:55:30.720000 140217027146752 torch/_dynamo/symbolic_convert.py:792] [0/0] [__trace_bytecode] TRACE CALL_FUNCTION 0 [UserDefinedObjectVariable()]
V0507 15:55:30.720000 140217027146752 torch/_dynamo/symbolic_convert.py:805] [0/0] empty checkpoint
Traceback (most recent call last):
  File "/home/yidi/local/pytorch/test_dynamo.py", line 17, in <module>
    ret = torch.compile(f, backend="eager", fullgraph=True)(ref)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 416, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 981, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 410, in _convert_frame_assert
    return _compile(
  File "/home/yidi/local/pytorch/torch/_utils_internal.py", line 70, in wrapper_function
    return function(*args, **kwargs)
  File "/home/yidi/local/miniconda3/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 703, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 570, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1167, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 172, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 517, in transform
    tracer.run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2234, in run
    super().run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 884, in run
    while self.step():
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 799, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 494, in wrapper
    return inner_fn(self, inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1253, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 737, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/user_defined.py", line 786, in call_function
    return self.call_method(tx, "__call__", args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/user_defined.py", line 646, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/base.py", line 313, in call_method
    unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/home/yidi/local/pytorch/torch/_dynamo/exc.py", line 212, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(ReferenceType) __call__ [] {}

from user code:
   File "/home/yidi/local/pytorch/test_dynamo.py", line 12, in f
    return ref()

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78

**Comment by mlazos** [comment]
Looks like there is an internal use case for this as well, not sure if graph break is unacceptable here though. https://fb.workplace.com/groups/1075192433118967/permalink/7310803355714170/

**Comment by galv** [comment]
Notably, I suspect that enabling this would allow tracing RNNs to work. The call to ref() [here](https://github.com/pytorch/pytorch/blob/a0604193a2353aa7f5a4bd0c7115e2cefa90e08a/torch/nn/modules/rnn.py#L274C59-L274C64) currently crashes dynamo with the following in a model using an LSTM:

```
msg = 'call_method UserDefinedObjectVariable(ReferenceType) __call__ [] {}'

    def unimplemented(msg: str, *, from_exc: Any = _NOTHING) -> NoReturn:
        assert msg != os.environ.get("BREAK", False)
        if from_exc is not _NOTHING:
            raise Unsupported(msg) from from_exc
>       raise Unsupported(msg)
E       torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(ReferenceType) __call__ [] {}

../../pytorch/torch/_dynamo/exc.py:216: Unsupported
```
