### ISSUE TITLE
`torch.export` code that includes `torch.autograd.grad`

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [pytorch/pytorch#125984]
### 🐛 Describe the bug

The following minimal example (based on a large real-world model which fails the same way) fails with errors in `torch.export`:
```python
import torch

class F(torch.nn.Module):
    def forward(self, x):
        y = x.square()
        return torch.autograd.grad(y.sum(), x)

f = F()
x = torch.ones(3)
x.requires_grad_(True)
print(f(x))

f = F()
x = torch.ones(3)
x.requires_grad_(True)
print(torch.export.export(f, args=(x,), strict=False))
```
printing (omitting backtraces):
```
(tensor([2., 2., 2.]),)
[...]
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
With `strict=True`, it errors as
```
Unsupported: 'skip function grad in file site-packages/torch/autograd/__init__.py'
```

Is exporting through a module that includes internal calls to the autograd engine a supported usecase for `torch.export` (and other related APIs, like `torch._export.aot_compile`)?

### Versions

PyTorch 2.3.0

**Comment by Linux-cpp-lisp** [comment]
@bdhirsh does that mean that code containing auto-differentiation is not supported for `torch.export`?  (Is this in the roadmap, or not intended to work?)

**Comment by tugsbayasgalan** [comment]
cc: @JackCaoG for the dynamo tracing through autograd.

**Comment by thisisd3** [comment]
Same issue when replacing last line by 
`torch.onnx.dynamo_export(f, x)`

**Comment by thisisd3** [comment]
A question - is this meant to be supported with dynamo export at some point? Or will this never be supported? An application that I'm building needs to get model Jacobian of output w.r.t. input in addition to regular output, and this would solve it out of the box. @bdhirsh @tugsbayasgalan @JackCaoG

**Comment by ezyang** [comment]
You can use non-strict export for this. When @JackCaoG finishes his stuff this will also work in dynamo, but that's a whiles away.

**Comment by thisisd3** [comment]
@ezyang thank you very much for your reply. 

Are you able to modify above example provided by @Linux-cpp-lisp in first message, such that it works with torch.onnx.export?
I dont see strict mode in torch.onnx.export and generally can't seem to get it to export.

`torch.onnx.export(
    model: 'Union[torch.nn.Module, torch.jit.ScriptModule, torch.jit.ScriptFunction]',
    args: 'Union[Tuple[Any, ...], torch.Tensor]',
    f: 'Union[str, io.BytesIO]',
    export_params: 'bool' = True,
    verbose: 'bool' = False,
    training: '_C_onnx.TrainingMode' = <TrainingMode.EVAL: 0>,
    input_names: 'Optional[Sequence[str]]' = None,
    output_names: 'Optional[Sequence[str]]' = None,
    operator_export_type: '_C_onnx.OperatorExportTypes' = <OperatorExportTypes.ONNX: 0>,
    opset_version: 'Optional[int]' = None,
    do_constant_folding: 'bool' = True,
    dynamic_axes: 'Optional[Union[Mapping[str, Mapping[int, str]], Mapping[str, Sequence[int]]]]' = None,
    keep_initializers_as_inputs: 'Optional[bool]' = None,
    custom_opsets: 'Optional[Mapping[str, int]]' = None,
    export_modules_as_functions: 'Union[bool, Collection[Type[torch.nn.Module]]]' = False,
    autograd_inlining: 'Optional[bool]' = True,
) -> 'None'
`

I am using torch version `2.3.1+cu12'
`

**Comment by ezyang** [comment]
Hmm, I'm not familiar with the ONNX frontend and unfortunately two of the main members of the ONNX team left Microsoft. You could try using non-strict export, and then torch.onnx.export on the resulting GM from non-strict export.

**Comment by thisisd3** [comment]
@ezyang  thank you very much. I've actually written the specific issue I'm facing here that's a bit more comprehensive:

https://github.com/pytorch/pytorch/issues/128325

hopefully we'll figure out a way to export these things.

**Comment by justinchuby** [comment]
@ezyang the top post shows usage of `strict=False` and mentions that both non-strict mode and strict mode failed. Do you have a suggestion? Thanks!

**Comment by ezyang** [comment]
In this case, it is likely export is incorrectly stripping the requires-grad'ness of the input variables to your model. You can fix the problem by instead appropriately creating a requires_grad=True variable inside the model to be exported (NB: don't mutate an input, that won't work) and then ensuring that the IO convention is still plain, does not require grad variables

**Comment by mitkotak** [comment]
@ezyang I tried this

```python
import torch

class F(torch.nn.Module):
    def forward(self, x):
        x_clone = x.detach().clone().requires_grad_(True)
        y = x_clone.square()
        grad = torch.autograd.grad(y.sum(), x_clone)
        return x

f = F()
x = torch.ones(3)
x.requires_grad_(True)
print(f(x))

f = F()
x = torch.ones(3)
print(torch.export.export(f, args=(x,), strict=True))
```

but got hit by
```
torch._dynamo.exc.Unsupported: Tensor.requires_grad_

from user code:
   File "/home/mkotak/tmp/export_debug.py", line 5, in forward
    x_clone = x.detach().clone().requires_grad_(True)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

How do I stop it from mutating x ?

**Comment by ezyang** [comment]
Maybe try something jank like

```
x_clone = torch.empty(..., requires_grad=True)
with torch.no_grad():
  x_clone.copy_(x)
```

lol

**Comment by Dasyud** [comment]
Hi @ezyang ,
I am running into errors with a non-strict export as well.

`class QFGrad(nn.Module):
    def __init__(self, policy, qf, beta=0):
        super().__init__()
        self.policy = policy
        self.qf = qf
        self.beta = beta

    def forward(self, state, hidden_state, cell_state):
        # state.squeeze_(1)
        state = state.squeeze(1)
        if not state.requires_grad:
            state = state.detach().requires_grad_(True)
        action, std_dev = self.policy.act(state, enable_grad=True)        
        updated_action = action + self.beta * self.calc_q_grad(state, action)
        return updated_action, hidden_state, cell_state

    def calc_q_grad(self, state, action):
        qf_output = self.qf(state, action)
        # return torch.autograd.functional.jacobian(self.qf, (state, action), create_graph=False)[1]
        return torch.autograd.grad(qf_output, action, create_graph=True, retain_graph=True)[0]`

torch Version: 2.5.0.dev20240906+cu121

This is the error I am getting in non-strict export.
`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

Dynamo gives a skip function grad error as stated above.

qf and policy are neural networks, and I am trying to get the derivative of qf wrt policy's output. I can share the entire file if needed.

**Comment by ezyang** [comment]
Sure, if you can post a self contained file that would let someone play around with it until it works

**Comment by Dasyud** [comment]
Sure! Does this attachment work?

[grad_to_onnx.txt](https://github.com/user-attachments/files/16989581/grad_to_onnx.txt)

**Comment by Dasyud** [comment]
Hi @ezyang ,
Should I open a separate issue for this? Also, whom can I connect with to discuss this issue?

**Comment by justinchuby** [comment]
Just listing what doesn't work here:

```python
import torch


class Model(torch.nn.Module):
    def forward(self, x):
        x_clone = torch.empty_like(x, requires_grad=True)
        with torch.no_grad():
            x_clone.copy_(x)
            loss = torch.sqrt(x_clone).sum()
            return torch.autograd.grad([loss], [x_clone], create_graph=True, retain_graph=True)[0]


torch.export.export(Model(), (torch.FloatTensor(2, 3, 4),), strict=False)
```

**Comment by Dasyud** [comment]
Assuming torch is failing to trace autograd, is there any other workaround for exporting this part of the model?

**Comment by angelayi** [comment]
It seems like this issue no longer repros? For the initial code posted, running with `torch.export.export(..., strict=False)` results in the following graph:
```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, x: "f32[3]"):
             # File: /data/users/angelayi/pytorch/moo.py:145 in forward, code: y = x.square()
            square: "f32[3]" = torch.ops.aten.square.default(x)
            
             # File: /data/users/angelayi/pytorch/moo.py:146 in forward, code: return torch.autograd.grad(y.sum(), x)
            sum_1: "f32[]" = torch.ops.aten.sum.default(square);  square = None
            ones_like: "f32[]" = torch.ops.aten.ones_like.default(sum_1, pin_memory = False, memory_format = torch.preserve_format);  sum_1 = None
            expand: "f32[3]" = torch.ops.aten.expand.default(ones_like, [3]);  ones_like = None
            pow_1: "f32[3]" = torch.ops.aten.pow.Tensor_Scalar(x, 1.0);  x = None
            mul: "f32[3]" = torch.ops.aten.mul.Scalar(pow_1, 2.0);  pow_1 = None
            mul_1: "f32[3]" = torch.ops.aten.mul.Tensor(expand, mul);  expand = mul = None
            return (mul_1,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='mul_1'), target=None)])
Range constraints: {}
```

@Dasyud 's [example](https://github.com/pytorch/pytorch/issues/125984#issuecomment-2348152846) produces the following graph: https://gist.github.com/angelayi/4795c358871f0af32aab991d87d2c0f2

**Comment by Dasyud** [comment]
Hi @angelayi ,

Are you referring to the `grad_to_onnx.txt` file? I tried running it again but the error hasn't changed. I even upgraded torch to the latest version (2.6.0).

`in forward
    updated_action = action + self.beta * self.calc_q_grad(state, action)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
0.001 *
-2.1699
[ torch.cuda.FloatTensor{1,1} ]`

I commented out the `onnx` line with `torch.export.export(meta_model, (input_tensor, dummy_hidden, dummy_cell), strict=False)` but it isn't working either.

`W0131 10:43:31.231000 177593 torch/fx/experimental/symbolic_shapes.py:6307] failed during evaluate_expr(Eq(u0, 1), hint=None, size_oblivious=False, forcing_spec=False
E0131 10:43:31.233000 177593 torch/fx/experimental/recording.py:299] failed while running evaluate_expr(*(Eq(u0, 1), None), **{'fx_node': False})
W0131 10:43:31.420000 177593 torch/fx/experimental/symbolic_shapes.py:6830] Unable to find user code corresponding to {u0}
Traceback (most recent call last):
...
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(u0, 1) (unhinted: Eq(u0, 1)).  (Size-like symbols: none)

Caused by: (_export/non_strict_utils.py:557 in __torch_function__)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

The following call raised this error:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/t-asonigpu2/code/Users/t-asoni/BWE/run_jobs/iql_training/github_issue_test.py", line 67, in forward
    return MultivariateNormal(mean, scale_tril=scale_tril)`


Could you please share the torch version you used? Also, could you try the onnx export, that was in my original code?

**Comment by angelayi** [comment]
@Dasyud I'm using the code you inlined in [this comment](https://github.com/pytorch/pytorch/issues/125984#issuecomment-2348152846), not the grad_to_onnx.txt file, which I believe just directly calls torch.export.export. I realized I forgot to include that I removed [this check](https://github.com/pytorch/pytorch/blob/68a363548409a3ff17965770304ee5e12fe718d9/torch/distributions/distribution.py#L71-L77), and then it exported successfully. 

cc @justinchuby on the onnx failure above

**Comment by justinchuby** [comment]
Hmm I got

```pytb
Traceback (most recent call last):
  File "/home/justinchu/dev/onnxscript/testtest.py", line 175, in <module>
    main()
    ~~~~^^
  File "/home/justinchu/dev/onnxscript/testtest.py", line 165, in main
    ep = torch.export.export(meta_model, (input_tensor, dummy_hidden, dummy_cell), strict=True)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/__init__.py", line 368, in export
    return _export(
        mod,
    ...<5 lines>...
        pre_dispatch=True,
    )
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 1044, in wrapper
    raise e
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 1017, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/exported_program.py", line 117, in wrapper
    return fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 2063, in _export
    return _export_for_training(
        mod,
    ...<4 lines>...
        preserve_module_call_signature=preserve_module_call_signature,
    )
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 1044, in wrapper
    raise e
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 1017, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/exported_program.py", line 117, in wrapper
    return fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 1928, in _export_for_training
    export_artifact = export_func(  # type: ignore[operator]
        mod=mod,
    ...<8 lines>...
        _is_torch_jit_trace=False,
    )
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 1296, in _strict_export_lower_to_aten_ir
    gm_torch_level = _export_to_torch_ir(
        mod,
    ...<6 lines>...
        _log_export_usage=False,
    )
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/export/_trace.py", line 693, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
                        ~~~~~~~~~~~~~~~~~~~~~
    ...<10 lines>...
        same_signature=same_signature,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    )(
    ~^
        *args,
        ^^^^^^
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/eval_frame.py", line 1575, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/eval_frame.py", line 566, in _fn
    return fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 1400, in __call__
    return self._torchdynamo_orig_callable(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        frame, cache_entry, self.hooks, frame_state, skip=1
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 565, in __call__
    return _compile(
        frame.f_code,
    ...<14 lines>...
        skip=skip + 1,
    )
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 997, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 726, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 760, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/bytecode_transformation.py", line 1404, in transform_code_object
    transformations(instructions, code_options)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 236, in _fn
    return fn(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 680, in transform
    tracer.run()
    ~~~~~~~~~~^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 2914, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 1084, in run
    while self.step():
          ~~~~~~~~~^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 994, in step
    self.dispatch_table[inst.opcode](self, inst)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 691, in wrapper
    return inner_fn(self, inst)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 2384, in CALL
    self._call(inst)
    ~~~~~~~~~~^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 2378, in _call
    self.call_function(fn, args, kwargs)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 929, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/variables/functions.py", line 438, in call_function
    return super().call_function(tx, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/variables/functions.py", line 320, in call_function
    return super().call_function(tx, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/variables/functions.py", line 121, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 935, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 3120, in inline_call
    return tracer.inline_call_()
           ~~~~~~~~~~~~~~~~~~~^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 3257, in inline_call_
    self.run()
    ~~~~~~~~^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 1084, in run
    while self.step():
          ~~~~~~~~~^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 994, in step
    self.dispatch_table[inst.opcode](self, inst)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 691, in wrapper
    return inner_fn(self, inst)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 2528, in CALL_KW
    self._call(inst, call_kw=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 2378, in _call
    self.call_function(fn, args, kwargs)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 929, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/variables/functions.py", line 747, in call_function
    unimplemented(msg)
    ~~~~~~~~~~~~~^^^^^
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/_dynamo/exc.py", line 361, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: 'skip function grad in file /home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/autograd/__init__.py'

from user code:
   File "/home/justinchu/dev/onnxscript/testtest.py", line 137, in forward
    updated_action = action + self.beta * self.calc_q_grad(state, action)
  File "/home/justinchu/dev/onnxscript/testtest.py", line 143, in calc_q_grad
    return torch.autograd.grad(qf_output, action, create_graph=True, retain_graph=True)[0]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

with 

```py
import torch
import torch.nn as nn
import numpy as np
from torch.distributions import MultivariateNormal

LOG_STD_MIN = -5.0
LOG_STD_MAX = 2.0

DEFAULT_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# DEFAULT_DEVICE = torch.device('cpu')


def torchify(x):
    x = torch.from_numpy(x)
    if x.dtype is torch.float64:
        x = x.float()
    x = x.to(device=DEFAULT_DEVICE)
    return x


class Squeeze(nn.Module):
    def __init__(self, dim=None):
        super().__init__()
        self.dim = dim

    def forward(self, x):
        return x.squeeze(dim=self.dim)


def mlp(dims, activation=nn.ReLU, output_activation=None, squeeze_output=False):
    n_dims = len(dims)
    assert n_dims >= 2, "MLP requires at least two dims (input and output)"

    layers = []
    for i in range(n_dims - 2):
        layers.append(nn.Linear(dims[i], dims[i + 1]))
        layers.append(activation())
    layers.append(nn.Linear(dims[-2], dims[-1]))
    if output_activation is not None:
        layers.append(output_activation())
    if squeeze_output:
        assert dims[-1] == 1
        layers.append(Squeeze(-1))
    net = nn.Sequential(*layers)
    net.to(dtype=torch.float32)
    return net


# had to define this because torch.diag_embed was not being onnx exported
def custom_diag_embed(diagonal):
    batch_size, dim = diagonal.shape
    return torch.eye(dim).unsqueeze(0).repeat(batch_size, 1, 1).to(
        diagonal.device
    ) * diagonal.unsqueeze(-1)


class GaussianPolicy(nn.Module):
    def __init__(
        self,
        obs_dim,
        act_dim,
        hidden_dim=256,
        n_hidden=2,
        state_min=None,
        state_max=None,
        state_mean=None,
        state_std=None,
    ):
        super().__init__()
        self.net = mlp(
            [obs_dim, *([hidden_dim] * n_hidden), act_dim], output_activation=nn.Tanh
        )
        self.state_min = state_min
        self.state_max = state_max
        self.state_mean = state_mean
        self.state_std = state_std

    def forward(self, obs):
        if self.state_mean is not None:
            obs = (obs - self.state_mean) / self.state_std
        mean, log_std = torch.chunk(self.net(obs), 2, dim=-1)
        std = torch.exp(log_std.clamp(LOG_STD_MIN, LOG_STD_MAX))
        # scale_tril = torch.diag(std)
        # scale_tril = torch.diag_embed(std)
        scale_tril = custom_diag_embed(std)
        return MultivariateNormal(mean, scale_tril=scale_tril)

    def act(self, obs, deterministic=True, enable_grad=False):  # only called during evaluation
        with torch.set_grad_enabled(enable_grad):
            dist = self(obs)  # dist is a MultivariateNormal object, calls forward
            return dist.mean, dist.stddev if deterministic else dist.sample()


class TwinQ(nn.Module):
    def __init__(
        self,
        state_dim,
        action_dim,
        hidden_dim=256,
        n_hidden=2,
        state_min=None,
        state_max=None,
        state_mean=None,
        state_std=None,
    ):
        super().__init__()
        dims = [state_dim + action_dim, *([hidden_dim] * n_hidden), 1]
        self.q1 = mlp(dims, activation=nn.Tanh, squeeze_output=True)
        self.q2 = mlp(dims, activation=nn.Tanh, squeeze_output=True)
        self.state_min = state_min
        self.state_max = state_max
        self.state_mean = state_mean
        self.state_std = state_std

    def both(self, state, action):
        sa = torch.cat([state, action], 1)
        # sa = sa.float() # added this line
        return self.q1(sa), self.q2(sa)

    def forward(self, state, action, enable_grad=False):
        with torch.set_grad_enabled(enable_grad):
            if self.state_mean is not None:
                state = (state - self.state_mean) / self.state_std
            return torch.min(*self.both(state, action))


class QFGrad(nn.Module):
    def __init__(self, policy, qf, beta=0):
        super().__init__()
        self.policy = policy
        self.qf = qf
        self.beta = torch.tensor(beta)

    def forward(self, state, hidden_state, cell_state):
        state = state.squeeze(1)
        action, _ = self.policy.act(state, enable_grad=True)
        updated_action = action + self.beta * self.calc_q_grad(state, action)
        return updated_action, hidden_state, cell_state

    def calc_q_grad(self, state, action):
        qf_output = self.qf(state, action, enable_grad=True)
        # return torch.autograd.functional.jacobian(self.qf, (state, action), create_graph=False)[1]
        return torch.autograd.grad(qf_output, action, create_graph=True, retain_graph=True)[0]


def main():
    obs_dim = 150
    act_dim = 1

    policy = GaussianPolicy(obs_dim, act_dim * 2, hidden_dim=128, n_hidden=2)
    qf = TwinQ(obs_dim, act_dim, hidden_dim=128, n_hidden=2)

    policy.to(DEFAULT_DEVICE)
    qf.to(DEFAULT_DEVICE)

    # create a meta model with policy and qf, that follows the equation: output = policy(input) + grad_a * qf(input, policy(input))
    meta_model = QFGrad(policy, qf, beta=0.05)

    # Example usage
    input_tensor = torchify(np.random.rand(1, 1, 150))
    dummy_hidden = torch.zeros(1, 1)
    dummy_cell = torch.zeros(1, 1)

    # Export to ONNX with additional inputs and outputs
    ep = torch.export.export(meta_model, (input_tensor, dummy_hidden, dummy_cell), strict=True)
    onnx_program = torch.onnx.export(
        ep,
        dynamo=True,
        # report=True,
    )
    print(onnx_program)


if __name__ == "__main__":
    main()
```

**Comment by justinchuby** [comment]
torch 2.7.0.dev20250124+cu124

**Comment by angelayi** [comment]
Oh you need to set export(strict=False)

**Comment by justinchuby** [comment]
Yeah I did that too

**Comment by angelayi** [comment]
If you set strict=False then you shouldn't run into a torch._dynamo.exc.Unsupported error..

**Comment by justinchuby** [comment]
Thanks just tried again and it works by commenting the check https://github.com/pytorch/pytorch/blob/68a363548409a3ff17965770304ee5e12fe718d9/torch/distributions/distribution.py#L71-L77. 

Should the check be improved or removed?

**Comment by Dasyud** [comment]
@angelayi @justinchuby Thanks for looking into the issue! It seems that disabling the check only resolves some specific issue relating to `distributions` and `torch.export`. @justinchuby 's [code in this comment](https://github.com/pytorch/pytorch/issues/125984#issuecomment-2356374801) is still throwing an error for me. As for my code, the ONNX related errors haven't changed, although I am seeing a different ONNX error if I use `torch.export.export` before calling `torch.onnx.export`.

**Comment by justinchuby** [comment]
Did you set strict=False? What is the onnx error now?

**Comment by Dasyud** [comment]
Yes, I set `strict=False` in all the runs. Which code are you referring to?

For your short example snippet: 
`RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.`

For the `grad_to_onnx` code with torch.export (that you shared):
```
## Exception summary

<class 'TypeError'>: aten_ones_like() got an unexpected keyword argument 'memory_format'
⬆️
<class 'torch.onnx._internal.exporter._errors.GraphConstructionError'>: Error when calling function 'TracedOnnxFunction(<function aten_ones_like at 0x7f8bdbee8280>)' with args '[SymbolicTensor('min_3', type=Tensor(FLOAT), shape=[1], producer=node_aten_minimum_26, index=0)]' and kwargs '{'pin_memory': False, 'memory_format': 'torch.preserve_format'}'
⬆️
<class 'torch.onnx._internal.exporter._errors.ConversionError'>: Error when translating node %ones_like : [num_users=4] = call_function[target=torch.ops.aten.ones_like.default](args = (%min_3,), kwargs = {pin_memory: False, memory_format: torch.preserve_format}). See the stack trace for more information. 
```

My original `grad_to_onnx` code (direct torch.onnx.export):
`RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient`

**Comment by justinchuby** [comment]
aten_ones_like... is an easy one to fix. We will just update the onnx implementation

**Comment by angelayi** [comment]
> @justinchuby 's code in this comment is still throwing an error for me

I believe running that [code](https://github.com/pytorch/pytorch/issues/125984#issuecomment-2356374801) eagerly (without torch.export) doesn't work, so I wouldn't expect running torch.export to work either.

**Comment by albanD** [comment]
@angelayi yes that is expected. Running under no_grad() mode means that autograd doesn't track things so we cannot compute gradients for it.
