### ISSUE TITLE
No Module Named 'torch._prims_common' When Importing nn in New Version.

### ISSUE THREAD

**Issue by Zoeeeeey** [pytorch/pytorch#125987]
### 🐛 Describe the bug

Hello,

While using `nn` to build a model, there seems to be an error occurring at the `from torch import nn` statement. 

This issue arises in torch version `2.3`, whereas there was no error in torch version `2.2`.

The following code snippet can reproduce the aforementioned problem.

```python
import torch
from torch import nn


class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out


input_size = 10
hidden_size = 5
num_classes = 2

net = SimpleNet(input_size, hidden_size, num_classes)

input_data = torch.randn(1, input_size)

output = net(input_data)
print(output)
```

Out ( in 2.3):
```
Traceback (most recent call last):
  File "/root/.../check/test_import.py", line 2, in <module>
    from torch import nn
  File "/root/miniconda3/envs/torch23py39/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/root/miniconda3/envs/torch23py39/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 1, in <module>
    from .module import Module
  File "/root/miniconda3/envs/torch23py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 8, in <module>
    from torch._prims_common import DeviceLikeType
ModuleNotFoundError: No module named 'torch._prims_common'
```

Out (in 2.1):
```
tensor([[-0.4151, -1.0369]], grad_fn=<AddmmBackward0>)
```

### Versions

 Similarly, under the new version, it appears that the `collect_env.py` script is no longer functional.

(torch23py39) root@autodl-container-e39d46b8d3-26a04d33:~/zzy# python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "/root/zzy/collect_env.py", line 624, in <module>
    main()
  File "/root/zzy/collect_env.py", line 607, in main
    output = get_pretty_env_info()
  File "/root/zzy/collect_env.py", line 602, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/root/zzy/collect_env.py", line 441, in get_env_info
    version_str = torch.__version__
AttributeError: module 'torch' has no attribute '__version__'

**Comment by Zoeeeeey** [comment]
In 2.2, got:
```
tensor([[0.0653, 0.1539]], grad_fn=<AddmmBackward0>)
```

**Comment by Zoeeeeey** [comment]
`ModuleNotFoundError: No module named 'torch._custom_ops'`

```python
import torch
import torchvision
print(torchvision.__version__)
```

version: torch 2.3.0, torchvision 0.17.2
