### ISSUE TITLE
torch._dynamo.export segfaults when calling nn.Parameter

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#126109]
### 🐛 Describe the bug

`torch._dynamo.export` seems to segfault on this piece of code which creates an `nn.Parameter` in the forwards function. I'm not sure how common this code is though -- I just noticed it when I was playing around with some things.

```python
import torch
import torch._dynamo

class M(torch.nn.Module):
    def forward(self, x):
        return x + torch.nn.Parameter(torch.ones(3, 3))

inps = (torch.ones(3, 3),)
torch._dynamo.export(M())(*inps)
```

The following cases work:
* `torch.compile(M(), fullgraph=True)(*inps)`
* `make_fx(M())(*inps)`
* `torch.export.export(M(), inps, strict=False)`

Here are the logs: https://gist.github.com/angelayi/9c57c175ee8f54cd5a51cf864dc11def

### Versions

main

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78

**Comment by ezyang** [comment]
```
#0  0x00007fffe8440a50 in void c10::function_ref<void (char**, long const*, long, long)>::callback_fn<at::native::AVX2::VectorizedLoop2d<at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::{lambda()#4}::operator()() const::{lambda()#14}::operator()() const::{lambda(float)#1}, at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&)::{lambda()#4}::operator()() const::{lambda()#4}::operator()() const::{lambda(at::vec::AVX2::Vectorized<float>)#2}> >(long, char**, long const*, long, long)
    () from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#1  0x00007fffe3d944b8 in at::TensorIteratorBase::serial_for_each(c10::function_ref<void (char**, long const*, long, long)>, at::Range) const () from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#2  0x00007fffe3d949f7 in at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#3  0x00007fffe852108b in at::native::AVX2::direct_copy_kernel(at::TensorIteratorBase&) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#4  0x00007fffe410deee in at::native::copy_impl(at::Tensor&, at::Tensor const&, bool) [clone .isra.0] ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#5  0x00007fffe410f84c in at::native::copy_(at::Tensor&, at::Tensor const&, bool) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#6  0x00007fffe4da20c6 in at::_ops::copy_::call(at::Tensor&, at::Tensor const&, bool) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#7  0x00007fffe4411f67 in at::native::clone(at::Tensor const&, std::optional<c10::MemoryFormat>) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#8  0x00007fffe50fe9b0 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, std::optional<c10::MemoryFormat>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__clone>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, std::optional<c10::MemoryFormat> > >, at::Tensor (at::Tensor const&, std::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat>) () from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#9  0x00007fffe4a2b60a in at::_ops::clone::redispatch(c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat>) () from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#10 0x00007fffe6763df2 in torch::autograd::VariableType::(anonymous namespace)::clone(c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat>) () from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#11 0x00007fffe6764213 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat>), &torch::autograd::VariableType::(anonymous namespace)::clone>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat> > >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, std::optional<c10::MemoryFormat>) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#12 0x00007fffe4abaefb in at::_ops::clone::call(at::Tensor const&, std::optional<c10::MemoryFormat>) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_cpu.so
#13 0x00007fffee8cad06 in torch::autograd::THPVariable_clone(_object*, _object*, _object*) ()
   from /data/users/ezyang/a/pytorch/torch/lib/libtorch_python.so
```

It's probably accidentally running real kernels on a fake tensor.

**Comment by ezyang** [comment]
```
Current thread 0x00007f4983a45400 (most recent call first):
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 826 in clone_input
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 1799 in _clone_input
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 1819 in wrap_fx_proxy_cls
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 1722 in wrap_fx_proxy
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 1283 in wrap_tensor
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 446 in _wrap
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 304 in __call__
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/output_graph.py", line 484 in synthetic_graph_input
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/torch.py", line 878 in call_nn_parameter
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/torch.py", line 511 in handle_parameter
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/torch.py", line 716 in call_function
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 737 in call_function
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1253 in CALL_FUNCTION
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 494 in wrapper
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 799 in step
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 884 in run
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2234 in run
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 490 in transform
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 172 in _fn
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1167 in transform_code_object
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 543 in compile_inner
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 273 in time_wrapper
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 708 in _compile
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/contextlib.py", line 79 in inner
  File "/data/users/ezyang/a/pytorch/torch/_utils_internal.py", line 70 in wrapper_function
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 381 in _convert_frame_assert
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 986 in catch_errors
  File "/data/users/ezyang/a/pytorch/torch/nn/modules/module.py", line 1541 in _call_impl
  File "/data/users/ezyang/a/pytorch/torch/nn/modules/module.py", line 1532 in _wrapped_call_impl
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 414 in _fn
  File "/data/users/ezyang/a/pytorch/torch/nn/modules/module.py", line 1541 in _call_impl
  File "/data/users/ezyang/a/pytorch/torch/nn/modules/module.py", line 1532 in _wrapped_call_impl
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 1306 in inner
  File "/data/users/ezyang/a/pytorch/w.py", line 12 in <module>
```

**Comment by anijain2305** [comment]
For nn.Parameter construction, there is pre-graph bytecode. This does not apply to export. This is possibly why it segfaults. I am in favor of just graph breaking. @angelayi will that work? It doesnt really move the needle for export, but better than segfault.

**Comment by anijain2305** [comment]
Related https://github.com/pytorch/pytorch/pull/128935

**Comment by angelayi** [comment]
@anijain2305 I'm fine with that for now! thanks!
