### ISSUE TITLE
When testing the scalar version, test_open_device_registration will fail

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#126372]
### 🐛 Describe the bug

When test the scalar version, loadu is not found  in test_open_device_registration https://github.com/pytorch/pytorch/actions/runs/9104932189/job/25030244654.

### Error logs

```
======================================================================
ERROR: test_open_device_registration (__main__.ExtensionBackendTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sdp/ecao/pytorchs/stock_pytorch/torch/testing/_internal/common_utils.py", line 2756, in wrapper
    method(*args, **kwargs)
  File "test/inductor/test_extension_backend.py", line 160, in test_open_device_registration
    FileCheck().check("void").check(load_expr).check(
RuntimeError: Expected to find "loadu" but did not find it
Searched string:

#include "/tmp/tmpeg2jo8om/sy/csy5ilkd74mvjhibm2eq3jumg6sfu3fbjexi7alnojcpzzghbzhg.h"
extern "C" void cpp_fused_add_mul_0(const float* in_ptr0,
                       const float* in_ptr1,
                       const float* in_ptr2,
                       float* out_ptr0)
{
    {
        #pragma GCC ivdep
        for(long x0=static_cast<long>(0L); x0<static_cast<long>(32L); x0+=static_cast<long>(1L))
        {
            auto tmp0 = in_ptr0[static_cast<long>(x0)];
            auto tmp1 = in_ptr1[static_cast<long>(x0)];
            auto tmp3 = in_ptr2[static_cast<long>(x0)];
            auto tmp2 = decltype(tmp0)(tmp0 * tmp1);
            auto tmp4 = decltype(tmp2)(tmp2 + tmp3);
            out_ptr0[static_cast<long>(x0)] = tmp4;
        }
    }
}

void inductor_entry_impl(
    AtenTensorHandle*
        input_handles, // array of input AtenTensorHandle; handles
                        // are stolen; the array itself is borrowed
    AtenTensorHandle*
        output_handles  // array for writing output AtenTensorHandle; handles
                        // will be stolen by the caller; the array itself is
                        // borrowed)
) {
    py::gil_scoped_release release;

    auto inputs = alloc_tensors_by_stealing_from_handles(input_handles, 3);
    auto arg0_1 = std::move(inputs[0]);
    auto arg1_1 = std::move(inputs[1]);
    auto arg2_1 = std::move(inputs[2]);
    auto buf0 = at::empty_strided({2L, 16L}, {16L, 1L}, at::TensorOptions(c10::Device(at::kPrivateUse1, 0)).dtype(at::kFloat));
    cpp_fused_add_mul_0((float*)(arg0_1.data_ptr()), (float*)(arg1_1.data_ptr()), (float*)(arg2_1.data_ptr()), (float*)(buf0.data_ptr()));
    arg0_1.reset();
    arg1_1.reset();
    arg2_1.reset();
    output_handles[0] = reinterpret_cast<AtenTensorHandle>(new at::Tensor(buf0));
} // inductor_entry_impl
'''
)

inductor_entry = CppWrapperCodeCache.load_pybinding(
    ["std::vector<AtenTensorHandle>"], cpp_wrapper_src, False, 1)

def _wrap_func(f):
    def g(args):
        input_tensors = [arg if isinstance(arg, torch.Tensor) else torch.tensor(arg) for arg in args]
        input_handles = torch._C._aoti.unsafe_alloc_void_ptrs_from_tensors(input_tensors)

        output_handles = f(input_handles)
        output_tensors = torch._C._aoti.alloc_tensors_by_stealing_from_void_ptrs(output_handles)
        return output_tensors

    return g

call = _wrap_func(inductor_entry)


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((2, 16), (16, 1), device='extension_device:0', dtype=torch.float32)
    arg1_1 = rand_strided((2, 16), (16, 1), device='extension_device:0', dtype=torch.float32)
    arg2_1 = rand_strided((2, 16), (16, 1), device='extension_device:0', dtype=torch.float32)
    fn = lambda: call([arg0_1, arg1_1, arg2_1])
    return print_performance(fn, times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.wrapper_benchmark import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)

Output code written to: /tmp/tmpeg2jo8om/f4/cf4q5c2vaaqxldgtsonrqhrf2m4jty6ycbpqf7kpbp546zfho36r.py
From CHECK: loadu


To execute this test, run the following from the base repo dir:
     python test/inductor/test_extension_backend.py -k ExtensionBackendTests.test_open_device_registration

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

```

### Minified repro

Run `python test/inductor/test_extension_backend.py -k ExtensionBackendTests.test_open_device_registration` with `torch._inductor.config.cpp.simdlen=0`.

### Versions

pytorch nighly 0512.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by CaoE** [comment]
Close as scalar version will not generated vectorized code.
