### ISSUE TITLE
Runtime error while running an Inductor inference benchmark for llama_v2_7b_16h

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/pytorch#126335]
### 🐛 Describe the bug

Hi,

With the PyTorch main branch, I tried to run an Inductor benchmark with llama_v2_7b_16h. The python version used was 3.10.2.
The workload failed with a strange error when it tried to run in eager mode.
I also created a new python virtual environment at my end to confirm that it's a legit issue.
While I used CPU, even with CUDA, I'd expect it to fail.

I'm guessing CI jobs are not covering this workload (at least with the arguments I used in the command below)
I searched the logs of trunk CI jobs pertaining to benchmarks, but couldn't find it.
If the CI jobs don't cover it, then it's very likely a legit issue.

#### Command

```
python benchmarks/dynamo/torchbench.py --performance --inference --inductor -dcpu --only llama_v2_7b_16h --freezing
```

### Error
```
loading model: 0it [00:37, ?it/s]
cpu  eval  llama_v2_7b_16h                    
Traceback (most recent call last):
  File "pytorch/benchmarks/dynamo/common.py", line 2262, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_pass
    return mod(*inputs)
  File "pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1211, in forward
    outputs = self.model(
  File "pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 974, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "pytorch/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "pytorch/torch/nn/functional.py", line 2266, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File pytorch/benchmarks/dynamo/common.py", line 4091, in run
    ) = runner.load_model(
  File pytorch/benchmarks/dynamo/torchbench.py", line 362, in load_model
    self.validate_model(model, example_inputs)
  File pytorch/benchmarks/dynamo/common.py", line 2264, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

```

### Cause

While running the benchmark, [here](https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/torchbench.py#L426), `benchmarks/dynamo/torchbench.py` is unpacking a dict `inputs`, which has a key `input_ids`, whose corresponding value is a tensor. 

![image](https://github.com/pytorch/pytorch/assets/90872293/1014d022-3b6d-4be5-a430-5001df3d33ea)

Because of the aforementioned unpacking, what actually got passed is the string `input_ids` (name of the key)!

![image](https://github.com/pytorch/pytorch/assets/90872293/dd125b5e-0892-4063-912f-8e485cea4a4b)

### Versions

```
PyTorch version: 2.4.0a0+git288fdfa
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          208
On-line CPU(s) list:             0-207
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8371HC CPU @ 3.30GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              26
Socket(s):                       4
Stepping:                        11
CPU max MHz:                     4200.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3.3 MiB (104 instances)
L1i cache:                       3.3 MiB (104 instances)
L2 cache:                        104 MiB (104 instances)
L3 cache:                        143 MiB (4 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-25,104-129
NUMA node1 CPU(s):               26-51,130-155
NUMA node2 CPU(s):               52-77,156-181
NUMA node3 CPU(s):               78-103,182-207
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.6.0
[pip3] CoCa-pytorch==0.1.0
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.4.8
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.16.0
[pip3] open-clip-torch==2.24.0
[pip3] pytorch-labs-segment-anything-fast==0.2
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.3.3
[pip3] torch==2.4.0a0+gitd2b2727
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torchao==0.1
[pip3] torchaudio==2.2.0a0+1980f8a
[pip3] torchmetrics==1.4.0.post0
[pip3] torchmultimodal==0.1.0b0
[pip3] torchtext==0.17.0a0+09e2690
[pip3] torchvision==0.19.0a0+947ae1d
[pip3] vector-quantize-pytorch==1.14.23
[conda] No relevant packages
```

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by sanchitintel** [comment]
Will fix it. Thanks!

**Comment by xmfan** [comment]
Thanks for reporting, this is indeed a model that we run only on CUDA in our CI and dashboards due to its size. The dashboard runs for this model still pass: https://tinyurl.com/54d2eb56

I would recommend double-checking your installed `transformers` version, our benchmark repo specifies 4.38.1.

**Comment by sanchitintel** [comment]
Sorry for the false alarm! On another machine with python 3.9, everything works well. I'm not sure about the root-cause, but I'm closing this issue.
