### ISSUE TITLE
RNN/GRU/LSTM fail to export()/dynamo_export

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#126339]
### 🐛 Describe the bug

nn.RNNBase.flatten_parameters function should be a no-op for export. 
Otherwise, export()/dynamo_export fail inside it with this error:
```
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 196, in <setcomp>
    unique_data_ptrs = {p.data_ptr() for p in self._flat_weights}
RuntimeError: Cannot access data pointer of Tensor (e.g. FakeTensor, FunctionalTensor). If you're using torch.compile/export/fx, it is li\
kely that we are erroneously tracing into a custom kernel. To fix this, please wrap the custom kernel into an opaque custom op. Please se\
e the following for details: https://docs.google.com/document/d/1W--T6wz8IY8fOI0Vm8BF44PdBgs283QvpelJZWieQWQ
```
Here is a short repro. Monkey-patching nn.RNNBase.flatten_parameters fixes the issue. Real fix should be a conditional inside  flatten_parameters. 
```
import numpy as np
import torch
import torch.nn as nn

def noop(self):
    pass

# That fixes the issue                                                                                                                    
# nn.RNNBase.flatten_parameters = noop                                                                                                    

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        # same for LSTM, GRU                                                                                                              
        self.rnn = nn.RNN(16, 16, batch_first=True)

    def forward(self, x):
        return self.rnn(x)

device = torch.device('cuda')
model = Model().to(device)
x = torch.rand(1024, 20, 16).to(device)
# This does not help - fails same way in export()                                                                                         
# model = torch.export.export(model, (x,)).run_decompositions()                                                                           
onnx_program = torch.onnx.dynamo_export(model, x).save('model.onnx')
```

### Versions

PyTorch nightly 05/14

**Comment by angelayi** [comment]
Similar issue to https://github.com/pytorch/pytorch/issues/120626

**Comment by egaznep** [comment]
Hello @angelayi,

I noticed that while the static (over temporal/spatial) export works, if I try to export a dynamic export, it fails with the following error:

(MWE):
```python
import torch

class MWE(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = torch.nn.GRU(39, 256, 2, batch_first=True)
    def forward(self, x, y):
        return self.lstm(x)[0], y

batch_dim = torch.export.Dim('batch', max=1024)
time_dim = torch.export.Dim('time', min=2, max=3000)

model = MWE()
torch.export.export(
    mod=model,
    args=(torch.randn(2, 110, 39), torch.tensor([95, 100])),
    dynamic_shapes=({0: batch_dim, 1: time_dim},{0: batch_dim}),
)
```

```bash
(openspeech_env) egaznep@rockmore:~/.$ python openspeech_cli/mwe.py 
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0] Error while creating guard:
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0] Name: ''
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     Source: shape_env
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     Create Function: SHAPE_ENV
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     Guard Types: None
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     Code List: None
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     Object Weakref: None
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     Guarded Class Weakref: None
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0] Traceback (most recent call last):
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]   File "./venv/lib/python3.10/site-packages/torch/_guards.py", line 280, in create
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     return self.create_fn(builder, self)
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]   File "./venv/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 1856, in SHAPE_ENV
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     guards = output_graph.shape_env.produce_guards(
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]   File "./venv/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4287, in produce_guards
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]     raise ConstraintViolationError(
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0] torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (time)! For more information, run with TORCH_LOGS="+dynamic".
E0924 14:39:35.032000 821769 site-packages/torch/_guards.py:282] [0/0]   - Not all values of time = L['x'].size()[1] in the specified range time <= 3000 are valid because time was inferred to be a constant (110).
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0] Created at:
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]   File "./venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 623, in transform
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]     tracer = InstructionTranslator(
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]   File "./venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2670, in __init__
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]     output=OutputGraph(
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]   File "./venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 317, in __init__
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]     self.init_ambient_guards()
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]   File "./venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 463, in init_ambient_guards
E0924 14:39:35.033000 821769 site-packages/torch/_guards.py:284] [0/0]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
Traceback (most recent call last):
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 560, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1477, in inner
    raise constraint_violation_error
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1432, in inner
    result_traced = opt_f(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1298, in __call__
    return self._torchdynamo_orig_callable(
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 530, in __call__
    return _compile(
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 933, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 675, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "./venv/lib/python3.10/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 805, in _compile_inner
    check_fn = CheckFunctionManager(
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 2283, in __init__
    guard.create(builder)
  File "./venv/lib/python3.10/site-packages/torch/_guards.py", line 280, in create
    return self.create_fn(builder, self)
  File "./venv/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 1856, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "./venv/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4287, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (time)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of time = L['x'].size()[1] in the specified range time <= 3000 are valid because time was inferred to be a constant (110).

Suggested fixes:
  time = 110

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./openspeech_cli/mwe.py", line 14, in <module>
    torch.export.export(
  File "./venv/lib/python3.10/site-packages/torch/export/__init__.py", line 366, in export
    return _export(
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 1017, in wrapper
    raise e
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 990, in wrapper
    ep = fn(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/export/exported_program.py", line 114, in wrapper
    return fn(*args, **kwargs)
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 1880, in _export
    export_artifact = export_func(  # type: ignore[operator]
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 1224, in _strict_export
    return _strict_export_lower_to_aten_ir(
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 1252, in _strict_export_lower_to_aten_ir
    gm_torch_level = _export_to_torch_ir(
  File "./venv/lib/python3.10/site-packages/torch/export/_trace.py", line 576, in _export_to_torch_ir
    raise UserError(UserErrorType.CONSTRAINT_VIOLATION, str(e))  # noqa: B904
torch._dynamo.exc.UserError: Constraints violated (time)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of time = L['x'].size()[1] in the specified range time <= 3000 are valid because time was inferred to be a constant (110).

Suggested fixes:
  time = 110
```

Should I create a new issue?

**Comment by angelayi** [comment]
@egaznep I think your issue is similar to https://github.com/pytorch/pytorch/issues/115092

**Comment by egaznep** [comment]
> @egaznep I think your issue is similar to #115092

Thanks for the link, somehow I did not come across that one.

**Comment by bo-nemk** [comment]
I ran into a similar problem when exporting to ONNX in the following way, copying the style of the original poster:
```python
import numpy as np
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.rnn = nn.GRU(16, 16, batch_first=True)

    def forward(self, x):
        return self.rnn(x)

device = torch.device('cpu')
model = Model().to(device)
x = torch.rand(1024, 20, 16).to(device)
onnx_program = torch.onnx.export(model, x, dynamo=True).save('model.onnx')
```

Yields a slightly different error. The hack provided by original poster does not work for me.

```
W1026 20:14:25.888000 37229 .venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_registration.py:107] torchvision is not installed. Skipping torchvision::nms
[torch.onnx] Obtain model graph for `Model([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `Model([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decomposition...
[torch.onnx] Run decomposition... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ❌
Traceback (most recent call last):
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 591, in _handle_call_function_node_with_lowering
    outputs = onnx_function(*onnx_args, **onnx_kwargs)
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/onnxscript/values.py", line 625, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/onnxscript/function_libs/torch_lib/ops/core.py", line 8551, in aten_unbind
    return [op.Squeeze(out, [dim]) for out in outputs]
                                              ^^^^^^^
TypeError: 'SymbolicTensor' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 796, in _translate_fx_graph
    _handle_call_function_node_with_lowering(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        model,
        ^^^^^^
    ...<6 lines>...
        node_name_to_local_functions=node_name_to_local_functions,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 593, in _handle_call_function_node_with_lowering
    raise _errors.GraphConstructionError(
        f"Error when calling function '{onnx_function}' with args '{onnx_args}' and kwargs '{onnx_kwargs}'"
    ) from e
torch.onnx._internal.exporter._errors.GraphConstructionError: Error when calling function 'TracedOnnxFunction(<function aten_unbind at 0x7fb4c729b6a0>)' with args '[SymbolicTensor(name='zeros', type=Tensor(FLOAT), shape=Shape([1, 1024, 16]), producer='node_zeros', index=0)]' and kwargs '{}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 1465, in export
    onnx_program = _exported_program_to_onnx_program(
        decomposed_program, registry=registry
    )
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 1096, in _exported_program_to_onnx_program
    values = _translate_fx_graph(
        fx_graph,
    ...<4 lines>...
        registry=registry,
    )
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 822, in _translate_fx_graph
    raise _errors.ConversionError(
        f"Error when translating node {node.format_node()}. See the stack trace for more information."
    ) from e
torch.onnx._internal.exporter._errors.ConversionError: Error when translating node %unbind : [num_users=1] = call_function[target=torch.ops.aten.unbind.int](args = (%zeros,), kwargs = {}). See the stack trace for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/niels/repositories/work/asdf/main.py", line 16, in <module>
    onnx_program = torch.onnx.export(model, x, dynamo=True).save('model.onnx')
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/__init__.py", line 296, in export
    return _compat.export_compat(
           ~~~~~~~~~~~~~~~~~~~~~^
        model,
        ^^^^^^
    ...<20 lines>...
        legacy_export_kwargs=legacy_export_kwargs,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_compat.py", line 143, in export_compat
    onnx_program = _core.export(
        model,
    ...<11 lines>...
        verbose=verbose,
    )
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_flags.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/home/niels/repositories/work/asdf/.venv/lib/python3.13/site-packages/torch/onnx/_internal/exporter/_core.py", line 1511, in export
    raise _errors.ConversionError(
    ...<3 lines>...
    ) from e
torch.onnx._internal.exporter._errors.ConversionError: Failed to convert the exported program to an ONNX model. [96mThis is step 3/3[0m of exporting the model to ONNX. Next steps:
- If there is a missing ONNX function, implement it and register it to the registry.
- If there is an internal error during ONNX conversion, debug the error and summit a PR to PyTorch.
- Create an error report with `torch.onnx.export(..., report=True)`, and save the ExportedProgram as a pt2 file. Create an issue in the PyTorch GitHub repository against the [96m*onnx*[0m component. Attach the error report and the pt2 model.

## Exception summary

<class 'TypeError'>: 'SymbolicTensor' object is not iterable
⬆️
<class 'torch.onnx._internal.exporter._errors.GraphConstructionError'>: Error when calling function 'TracedOnnxFunction(<function aten_unbind at 0x7fb4c729b6a0>)' with args '[SymbolicTensor(name='zeros', type=Tensor(FLOAT), shape=Shape([1, 1024, 16]), producer='node_zeros', index=0)]' and kwargs '{}'
⬆️
<class 'torch.onnx._internal.exporter._errors.ConversionError'>: Error when translating node %unbind : [num_users=1] = call_function[target=torch.ops.aten.unbind.int](args = (%zeros,), kwargs = {}). See the stack trace for more information.

(Refer to the full stack trace above for more information.)

```
