### ISSUE TITLE
What type of file the method torch.save() create? Binary or Tar

### ISSUE THREAD

**Issue by mohammad-py** [pytorch/pytorch#1263]
I have reinstalled **pytorch** on my PC. Before reinstallation, the output file of torch.save method was `tar` , but after reinstallation, it has changed to binary file. I would like to know is it typical or not?

**Comment by apaszke** [comment]
Yes, it's expected. We've changed the data format because it makes data loading several times faster and slightly more space efficient.

**Comment by apaszke** [comment]
Note that new versions can still read the old files, but the old ones obviously don't support the new format

**Comment by mohammad-py** [comment]
@apaszke Thanks man, but with this change I can load my pretrained network! I upgarde my pytorch version with conda! But the error still exists!

**Comment by apaszke** [comment]
What's `torch.__version__` and what error do you get?

**Comment by mohammad-py** [comment]
pytorch version is 0.1.8 and the error is
Traceback (most recent call last):
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 185, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ons\nOrde'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 2287, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 1086, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 1028, in frombuf
    chksum = nti(buf[148:156])
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 187, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "YOLO_demo_v3_offline.py", line 357, in <module>
    net.load_state_dict(torch.load('./final.pth'))
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 248, in load
    return _load(f, map_location, pickle_module)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 314, in _load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 1582, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 1612, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 1475, in __init__
    self.firstmember = self.next()
  File "/home/mohammad/anaconda3/lib/python3.6/tarfile.py", line 2299, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

**Comment by apaszke** [comment]
0.1.8 is an old version... (0.1.11 is the current one). You didn't upgrade PyTorch properly. The file should load once you fix it.

**Comment by mohammad-py** [comment]
For Upgrading, I did this command:

> conda config --add channels soumith
> conda update pytorch torchvision

But I think something went wrong with conda! 
Sorry.
