### ISSUE TITLE
fail to visualize caffe2 model

### ISSUE THREAD

**Issue by XiongChengxin** [pytorch/pytorch#12642]
Refer to caffe2 official website, I tried to visualize caffe2 model by these code:

from caffe2.python import net_drawer
from IPython import display
graph=net_drawer.GetPydotGraph(train_model.net.Proto().op,"train_model",rankdir="LR")
display.Image(graph.create_png(),width=800) 

I've also tried:
graph = net_drawer.GetPydotGraph(train_model.net.Proto().op, "train_model", rankdir="LR")
graph.write_png('graph.png')

I've installed graphviz by command:
sudo apt-get install graphviz
pip install pydot

But I will meet error as follows:
Traceback (most recent call last):
  File "/mnt/xiongcx/R2Plus1D-master/tools/train_net.py", line 535, in <module>
    main()
  File "/mnt/xiongcx/R2Plus1D-master/tools/train_net.py", line 530, in main
    Train(args)
  File "/mnt/xiongcx/R2Plus1D-master/tools/train_net.py", line 418, in Train
    explog
  File "/mnt/xiongcx/R2Plus1D-master/tools/train_net.py", line 144, in RunEpoch
    graph = net_drawer.GetPydotGraph(train_model.net.Proto().op, "train", rankdir="TB")
  File "/home/xiongcx/anaconda2/envs/r21d/lib/python2.7/site-packages/pydot.py", line 1673, in new_method
    encoding=encoding)
  File "/home/xiongcx/anaconda2/envs/r21d/lib/python2.7/site-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/xiongcx/anaconda2/envs/r21d/lib/python2.7/site-packages/pydot.py", line 1884, in create
    assert p.returncode == 0, p.returncode
AssertionError: -11

Do you have ideas to solve it? Or do you have any other ideas to visualize caffe2 model? Thanks in advance.

**Comment by mhubii** [comment]
Are you on windows?

**Comment by XiongChengxin** [comment]
@mhubii No, My device is ubuntu16.04, cuda8.0, cudnn6.0, glibc 2.23.

**Comment by mhubii** [comment]
Hm maybe try `conda install -c anaconda pydot`

**Comment by XiongChengxin** [comment]
@mhubii Thanks. My device is shut down now, once it reopen, I will try.
