### ISSUE TITLE
Tutorials: downloadable Python examples don't work from-the-box...

### ISSUE THREAD

**Issue by Felix-neko** [pytorch/pytorch#12645]
Hi all! And thank you for the tutorials!

I've just tried to download the Python examples from the PyTorch tutorials and simply run them on my machine (Windows 7x64, Python 3.6, fresh version of PyTorch).

https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html
https://pytorch.org/tutorials/_downloads/cifar10_tutorial.py --- this is the one I've just tried to run.

Alas, they don't run correctly (while the IPython notebooks still do). Maybe they lack `if __name__ == "__main__"`, maybe something else.

Can you correct the Python examples?

cc @peterjc123

**Comment by mhubii** [comment]
The __name__ variable is automatically defined in your executed python file. It is only to prevent the execution of code that is not part of your executable, like imported files. It has nothing to with your problem. Can you please provide the error?

**Comment by Felix-neko** [comment]
Here's it:

```
C:\Python36\python.exe D:/DOWN/cifar10_tutorial.py
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\DOWN\cifar10_tutorial.py", line 99, in <module>
    dataiter = iter(trainloader)
  File "C:\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "C:\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "D:/DOWN/cifar10_tutorial.py", line 99, in <module>
    dataiter = iter(trainloader)
  File "C:\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "C:\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by mhubii** [comment]
Hm you might be right. It really seems like you need to wrap the code with `if __name__ == "__main__":` on Windows machines. Maybe checkout this issue #2341

**Comment by Felix-neko** [comment]
AFAIK it is because DataLoader uses multiprocessing...

**Comment by peterjc123** [comment]
@Felix-neko There is already a PR for this: https://github.com/pytorch/tutorials/pull/265. And maybe we should add `examples` and `tutorial` to build tests to ensure that they are working. The test might run in CI or in releases only. What do you think, @soumith?

**Comment by ezyang** [comment]
I filed an issue for peterjc123's suggestion at https://github.com/pytorch/pytorch/issues/32004

**Comment by iremyux** [comment]
Closing this issue since the PR with a fix, https://github.com/pytorch/tutorials/pull/2132, is also closed. 
It looks like for some tutorials, `if __name__ == '__main__':` clause should be added manually when working on Windows.
