### ISSUE TITLE
install pytorch in developer mode

### ISSUE THREAD

**Issue by wddabc** [pytorch/pytorch#1265]
Hi, I'm trying to do some hack on the pytorch which might require a developer install. However, when I run `python setup.py develop` I got something like:

> In file included from torch/csrc/utils/tuple_parser.cpp:1:0:
> torch/csrc/utils/tuple_parser.h:6:23: fatal error: THPP/THPP.h: No such file or directory
>  #include <THPP/THPP.h>
>                        ^
The normal installation with `python setup.py install` works fine.

**Comment by albanD** [comment]
Hi, you can check the [contributing](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md) guidelines.
You should do `python setup.py build develop`

**Comment by wddabc** [comment]
Thanks!

**Comment by accelsao** [comment]
error what I get , help
```
(devtorch) C:\Users\owner\pytorch>python setup.py develop
Building wheel torch-1.1.0a0+7e73783
-- Building version 1.1.0a0+7e73783
['cmake',
 '-GNinja',
 '-DMSVC_Z7_OVERRIDE=ON',
 '-DBUILDING_WITH_TORCH_LIBS=ON',
 '-DBUILD_BINARY=False',
 '-DBUILD_CAFFE2_OPS=True',
 '-DBUILD_PYTHON=True',
 '-DBUILD_SHARED_LIBS=ON',
 '-DBUILD_TEST=True',
 '-DBUILD_TORCH=ON',
 '-DCAFFE2_STATIC_LINK_CUDA=False',
 '-DCMAKE_BUILD_TYPE=Release',
 '-DCMAKE_CXX_FLAGS=  /EHa',
 '-DCMAKE_C_FLAGS=  /EHa',
 '-DCMAKE_EXE_LINKER_FLAGS=',
 '-DCMAKE_INSTALL_PREFIX=C:\\Users\\owner\\pytorch/torch',
 '-DCMAKE_PREFIX_PATH=C:\\Users\\owner\\Anaconda3\\envs\\devtorch\\Lib\\site-pac
kages',
 '-DCMAKE_SHARED_LINKER_FLAGS=',
 '-DINSTALL_TEST=True',
 '-DNCCL_EXTERNAL=False',
 '-DNUMPY_INCLUDE_DIR=C:/Users/owner/Anaconda3/envs/devtorch/lib/site-packages/n
umpy/core/include',
 '-DONNX_ML=False',
 '-DONNX_NAMESPACE=onnx_torch',
 '-DPYTHON_EXECUTABLE=C:/Users/owner/Anaconda3/envs/devtorch/python.exe',
 '-DPYTHON_INCLUDE_DIR=C:/Users/owner/Anaconda3/envs/devtorch/include',
 '-DPYTHON_LIBRARY=C:/Users/owner/Anaconda3/envs/devtorch/libs/python37.lib',
 '-DTHD_SO_VERSION=1',
 '-DTORCH_BUILD_VERSION=1.1.0a0+7e73783',
 '-DUSE_CUDA=False',
 '-DUSE_DISTRIBUTED=False',
 '-DUSE_FBGEMM=True',
 '-DUSE_FFMPEG=False',
 '-DUSE_LEVELDB=False',
 '-DUSE_LMDB=False',
 '-DUSE_MKLDNN=True',
 '-DUSE_NCCL=False',
 '-DUSE_NNPACK=True',
 '-DUSE_NUMPY=True',
 '-DUSE_OPENCV=False',
 '-DUSE_QNNPACK=True',
 '-DUSE_ROCM=False',
 '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
 '-DUSE_SYSTEM_NCCL=False',
 '-DUSE_TENSORRT=False',
 '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON',
 'C:\\Users\\owner\\pytorch']
-- The CXX compiler identification is MSVC 19.14.26433.3
-- The C compiler identification is MSVC 19.14.26433.3
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe -- broken
CMake Error at C:/Users/owner/Anaconda3/envs/devtorch/Library/share/cmake-3.14/M
odules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC
/14.14.26428/bin/HostX64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/owner/pytorch/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~2/MICROS~3/2017/COMMUN~1/Common7/IDE/COMMON~1
/MICROS~1/CMake/Ninja/ninja.exe cmTC_ed507
    [1/2] Building CXX object CMakeFiles\cmTC_ed507.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_ed507.exe
    FAILED: cmTC_ed507.exe
    cmd.exe /C "cd . && C:\Users\owner\Anaconda3\envs\devtorch\Library\bin\cmake
.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_ed507.dir --rc=rc --mt=CMAKE_MT-NOT
FOUND --manifests  -- C:\PROGRA~2\MICROS~3\2017\COMMUN~1\VC\Tools\MSVC\1414~1.26
4\bin\HostX64\x64\link.exe /nologo CMakeFiles\cmTC_ed507.dir\testCXXCompiler.cxx
.obj  /out:cmTC_ed507.exe /implib:cmTC_ed507.lib /pdb:cmTC_ed507.pdb /version:0.
0  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib win
spool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
&& cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_ed507.dir/manifest.res CMakeFiles\
cmTC_ed507.dir/manifest.rc" failed (exit code 0) with the following output:
    系統找不到指定的檔案。
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/owner/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/owner/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 719, in <module>
    build_deps()
  File "setup.py", line 285, in build_deps
    build_dir='build')
  File "C:\Users\owner\pytorch\tools\build_pytorch_libs.py", line 259, in build_
caffe2
    my_env)
  File "C:\Users\owner\pytorch\tools\build_pytorch_libs.py", line 239, in run_cm
ake
    check_call(cmake_args, cwd=build_dir, env=my_env)
  File "C:\Users\owner\Anaconda3\envs\devtorch\lib\subprocess.py", line 347, in
check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DMSVC_Z7_OVERRIDE
=ON', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_O
PS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True',
'-DBUILD_TORCH=ON', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Relea
se', '-DCMAKE_CXX_FLAGS=  /EHa', '-DCMAKE_C_FLAGS=  /EHa', '-DCMAKE_EXE_LINKER_F
LAGS=', '-DCMAKE_INSTALL_PREFIX=C:\\Users\\owner\\pytorch/torch', '-DCMAKE_PREFI
X_PATH=C:\\Users\\owner\\Anaconda3\\envs\\devtorch\\Lib\\site-packages', '-DCMAK
E_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNCCL_EXTERNAL=False', '-DNUMP
Y_INCLUDE_DIR=C:/Users/owner/Anaconda3/envs/devtorch/lib/site-packages/numpy/cor
e/include', '-DONNX_ML=False', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTAB
LE=C:/Users/owner/Anaconda3/envs/devtorch/python.exe', '-DPYTHON_INCLUDE_DIR=C:/
Users/owner/Anaconda3/envs/devtorch/include', '-DPYTHON_LIBRARY=C:/Users/owner/A
naconda3/envs/devtorch/libs/python37.lib', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_
VERSION=1.1.0a0+7e73783', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=False', '-DUSE_
FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '
-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True',
 '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_E
IGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_
ENABLE_CONCURRENT_EXEC=ON', 'C:\\Users\\owner\\pytorch']' returned non-zero exit
 status 1.
```
