### ISSUE TITLE
Error on import PyTorch >= 2.1 on OS X 10.11 with Python 3.10

### ISSUE THREAD

**Issue by BLKSerene** [pytorch/pytorch#126679]
### 🐛 Describe the bug

Hi, when import `PyTorch` >= 2.1 on OS X 10.11 with Python 3.10 there is an error:

```
Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so, 2): Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/libc10.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libc++.1.dylib
 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/libc10.dylib
```

The latest version of `PyTorch` that works on OS X 10.11 with Python 3.10 seems to be 2.0.1

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 10.11.6 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-10.11.6-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.2.2
[conda] Could not collect
```

cc @seemethere @malfet @osalpekar @atalman @svekars @brycebortree @albanD

**Comment by malfet** [comment]
Thank you for reporting the issue, but this behavior is expected(Last El Capitan's update was in 2018), but we should do a better job at documenting it (and perhaps changing pypi signature to highlight that only MacOS 12 or above is supported by the latest release )

**Comment by albanD** [comment]
Nikita will organize publishing macos support matrix to release.md similar to the cuda/cpython ones to increase visibility.
