### ISSUE TITLE
[dynamo] Check for invalid random_ arguments while tracing

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#126834]
Discovered with https://github.com/pytorch/pytorch/pull/126341.

Original repro command: `PYTORCH_TEST_WITH_DYNAMO=1 python -m pytest test/test_tensor_creation_ops.py::TestTensorCreationCPU::test_random_from_to_bool_cpu`

Repro:
```python
import torch

def f():
    try:
        x = torch.empty((3, 3), dtype=torch.bool)
        x.random_(-1, 1)
    except:
        x = x + 1
    return x

opt_f = torch.compile(f, backend="eager")
opt_f()
```

Output:
```
$ TORCH_LOGS="graph_code" python playground3.py 
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] TRACED GRAPH
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  ===== __compiled_fn_1 =====
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  /data/users/williamwen/pytorch2/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]     def forward(self):
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         # File: /data/users/williamwen/pytorch2/playground3.py:5 in f, code: x = torch.empty((3, 3), dtype=torch.bool)
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         x: "b8[3, 3]" = torch.empty((3, 3), dtype = torch.bool)
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         # File: /data/users/williamwen/pytorch2/playground3.py:6 in f, code: x.random_(-1, 1)
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         random_: "b8[3, 3]" = x.random_(-1, 1)
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         return (x,)
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0521 17:33:16.624000 139979020912448 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] 
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch2/playground3.py", line 12, in <module>
    opt_f()
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 414, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/pytorch2/playground3.py", line 3, in f
    def f():
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 548, in _fn
    return fn(*args, **kwargs)
  File "<eval_with_key>.1", line 6, in forward
RuntimeError: from is out of bounds for bool
```

Also happens with `uniform_`.

**Comment by ezyang** [comment]
Not enough error checking in the random error functions

**Comment by williamwen42** [comment]
Update: repro now graph breaks (skips) with message `torch._dynamo.exc.Unsupported: Tensor.random_ op`.

If we replace `random_` with `uniform_`, we get `NotImplementedError: "check_uniform_bounds" not implemented for 'Bool'`.
