### ISSUE TITLE
[ONNX] view(dtype=dtype) is not supported by both onnx.export and onnx.dynamo_export

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#126921]
### 🐛 Describe the bug

Here, ONNX exporter should be smart enough to reinterpret constant as different type, but it's not : 

```
import torch

class TData(torch.nn.Module):
    def __init__(
            self,
            path_cg_values: torch.Tensor,
    ):
        super().__init__()
        buf = path_cg_values.view(dtype=torch.int32)
        self.register_buffer(
            "path_cg_values", buf, persistent=False
        )

    def forward(self, x):
        return x+self.path_cg_values.view(dtype=torch.float32)

sample_input = torch.randn(8, 4)

model = TData(sample_input).eval()

# Fails with : RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":615, please report a bug to PyTorch.                                
# We don't have an op for aten::view but it isn't a special case.  Argument types: Tensor, int,                                                                        
# Candidates:                                                                                                                                                          
#         aten::view(Tensor(a) self, SymInt[] size) -> Tensor(a)                                                                                                       
#                 aten::view.dtype(Tensor(a) self, ScalarType dtype) -> Tensor(a)                                                                                      
torch.onnx.export(model, sample_input, "tdata_legacy.onnx")

# Fails with: RuntimeError: Unhandled FakeTensor Device Propagation for aten.add.Tensor, found two different devices cpu, meta                                         
#While executing %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%l_x_, %detach), kwargs = {})                                          
# Original traceback:                                                                                                                                                  
#  File "/git/models/view_repro.py", line 15, in forward                                                                                                               
#      return x+self.path_cg_values.view(dtype=torch.float32)                                                                                                          
out = torch.onnx.dynamo_export(model, sample_input,)


### Versions

Pytorch nighty 20/05

**Comment by justinchuby** [comment]
cc @shubhambhokare1 @titaiwangms fake tensor

**Comment by borisfom** [comment]
Note both legacy ONNX export and dynamo_export fail - though with different diagnostic. 
Alos, here are results of trying to do export.export() first : 
```
import torch

class TData(torch.nn.Module):
    def __init__(
            self,
            path_cg_values: torch.Tensor,
    ):
        super().__init__()
        buf = path_cg_values.view(dtype=torch.int32)
        self.register_buffer(
            "path_cg_values", buf, persistent=False
        )
  
    def forward(self, x):
        return x+self.path_cg_values.view(torch.float32)

sample_input = torch.randn(8, 4)

model = TData(sample_input).eval()

options = torch.onnx.ExportOptions(dynamic_shapes=True)
out = torch.export.export(model, (sample_input,))
# This passes, but fails on ONNXRT executon:                                                                                                                           
# onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /git/models/view.onnx failed:Type Error: Type (tensor(float)) of o\
utput arg (view) of node (aten_view_2_n1) does not match expected type (tensor(int32)).                                                                                
out = torch.onnx.dynamo_export(out, sample_input,export_options=options)
out.save("view_ex.onnx")

# This fails with :                                                                                                                                                    
#   File "/usr/local/lib/python3.10/dist-packages/onnx/reference/ops/op_reshape.py", line 19, in reshape_reference_implementation                                      
#     new_shape[zeros_index] = np.array(data.shape)[zeros_index]                                                                                                       
#     IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed                                                                               
m = out.module()
out = torch.onnx.dynamo_export(m, sample_input,export_options=options)
out.save("view.onnx")

**Comment by titaiwangms** [comment]
nn.Module + onnx.dynamo_export has error in Functionalization, while ExportedProgram + onnx.dynamo_export passes. I think for this issue, we should look into: 

```python
import torch

class TData(torch.nn.Module):
    def __init__(
            self,
            path_cg_values: torch.Tensor,
    ):
        super().__init__()
        buf = path_cg_values.view(dtype=torch.int32)
        self.register_buffer(
            "path_cg_values", buf, persistent=False
        )
  
    def forward(self, x):
        return x+self.path_cg_values.view(torch.float32)

sample_input = torch.randn(8, 4)

model = TData(sample_input).eval()

options = torch.onnx.ExportOptions(dynamic_shapes=True)
out = torch.export.export(model, (sample_input,))
# This passes, but fails on ONNXRT executon:                                                                                                                           
# onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /git/models/view.onnx failed:Type Error: Type (tensor(float)) of o\
# utput arg (view) of node (aten_view_2_n1) does not match expected type (tensor(int32)).                                                                                
out = torch.onnx.dynamo_export(out, sample_input,export_options=options)
out.save("view_ex.onnx")
```

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /git/models/view.onnx failed:Type Error: Type (tensor(float)) of output arg (view) of node (aten_view_2_n1) does not match expected type (tensor(int32)).      
```

**Comment by justinchuby** [comment]
# PyTorch ONNX Conversion Report

```
✅ Obtain model graph with `torch.export.export`
⚪ Obtain model graph with `torch.export.export(..., strict=False)`
⚪ Obtain model graph with `torch.jit.trace`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

## Error messages

```pytb


Traceback (most recent call last):

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_core.py", line 553, in _add_nodes
    _handle_call_function_node_with_lowering(

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_core.py", line 444, in _handle_call_function_node_with_lowering
    raise _errors.DispatchError(

torch.onnx._internal.exporter._errors.DispatchError: No ONNX function found for <OpOverload(op='aten.view', overload='dtype')>. Failure message: No decompositions registered for the real-valued input


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_core.py", line 1134, in export
    onnx_program = _exported_program_to_onnx_program(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_core.py", line 791, in _exported_program_to_onnx_program
    values = _add_nodes(exported_program, model, lower=lower, registry=registry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_core.py", line 565, in _add_nodes
    raise _errors.ConversionError(

torch.onnx._internal.exporter._errors.ConversionError: Error when translating node %view : [num_users=1] = call_function[target=torch.ops.aten.view.dtype](args = (%b_path_cg_values, torch.float32), kwargs = {}). See the stack trace for more information.

```

## Exported program

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, b_path_cg_values: "i32[8, 4]", x: "f32[8, 4]"):
             # File: /workspace/ONNXConverter/testtest.py:15 in forward, code: return x+self.path_cg_values.view(dtype=torch.float32)
            view: "f32[8, 4]" = torch.ops.aten.view.dtype(b_path_cg_values, torch.float32);  b_path_cg_values = None
            add: "f32[8, 4]" = torch.ops.aten.add.Tensor(x, view);  x = view = None
            return (add,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='b_path_cg_values'), target='path_cg_values', persistent=False), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='add'), target=None)])
Range constraints: {}

```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 0 parameters and 32 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {torch.int32: 32})
```

Inputs:
- `x`: `TensorMetadata(shape=torch.Size([8, 4]), dtype=torch.float32, requires_grad=False, stride=(4, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `add`: `TensorMetadata(shape=torch.Size([8, 4]), dtype=torch.float32, requires_grad=False, stride=(4, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

The FX graph has 5 nodes in total. Number of FX nodes per op:
- `placeholder`: 2
- `call_function`: 2
- `output`: 1


Of the call_function nodes, the counts of operators used are:

- `aten.view.dtype`: 1
- `aten.add.Tensor`: 1

## ONNX Conversion Information

The model contains operators the dispatcher could not find registered ONNX decompositions for. This may be due to missing implementations, decompositions not registered correctly, or a bug in the dispatcher.

Errors grouped by operator:

- `aten.view.dtype`:     No decompositions registered for the real-valued input. Example node: `%view : [num_users=1] = call_function[target=torch.ops.aten.view.dtype](args = (%b_path_cg_values, torch.float32), kwargs = {})`. All nodes: `[view]`

## Decomposition comparison

Ops exist only in the ExportedProgram before decomposition: `[]`

Ops exist only in the ExportedProgram after decomposition: `['aten.detach.default']`

**Comment by justinchuby** [comment]
Will just need to implement `torch.ops.aten.view.dtype` in torchlib

**Comment by borisfom** [comment]
@justinchuby : any estimate on when this can be fixed ?

**Comment by justinchuby** [comment]
I just realized onnx does not have reinterpret cast, so this is not always possible. Right now it is only possible to support a special case where the input is a constant, which we can eagerly evaluate. This will require an edge case handling in the exporter. 

@gramalingam do you have comments on ONNX support for reinterpret cast?

@borisfom where/which model is this operation needed? Is this a general usage pattern?

**Comment by gramalingam** [comment]
If there is sufficient demand, we can add reinterpret-cast to ONNX. I am guessing it should be relatively easy for backends to implement it .... So, seems like a good candidate for adding it to standard. Is the behavior going to be the same in all machines (eg., big-endian and small-endian)? I suppose so, just wondering if there are special cases.

**Comment by borisfom** [comment]
@justinchuby : Yes it would be very nice to have reinterpret_cast in ONNX!
Our general pattern of using those: some modules need to keep float constant Tensors (registered as buffers) unaffected by .to(dtype=float16, etc) operations. Currently, the only consistent way to keep those constants to be flipped on module type conversion is to declare those Tensors as matching length integers (int32 for float32 etc.) and use cast.
As we are on that - probably, better and easier way to fix that particular case would be to add a flag to register_buffer that would mark it as guarded from type conversion. I will create a separate issue for that.

**Comment by borisfom** [comment]
@justinchuby : Here, with the same library we have similar use case - and I noticed it fails not only for ONNX, but for jit.script() as well - it can't find implementation for view(dtype) either : 
https://github.com/NVIDIA/cuEquivariance/blob/3557c31426d8579b81e761b2f7c8f39ea54351b2/cuequivariance_torch/cuequivariance_torch/primitives/tensor_product.py#L217

This may be easier to fix as it does not require any extension  of ONNX opset.
