### ISSUE TITLE
[dynamo] Trace through invalid bool tensor operations properly

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#127003]
Discovered with `https://github.com/pytorch/pytorch/pull/126341`.

Original repro command: `PYTORCH_TEST_WITH_DYNAMO=1 pytest test/test_binary_ufuncs.py::TestBinaryUfuncsCPU::test_sub_typing_cpu`

Repro:
```python
import torch

def f(x, y):

    try:
        x = x - y
    except:
        return x
    return y

opt_f = torch.compile(f, backend="eager")
inp_x = torch.tensor([1, 0, 1, 0], dtype=torch.bool)
inp_y = torch.tensor([1, 1, 0, 0], dtype=torch.bool)
opt_f(inp_x, inp_y)
```

Output:
```
$ TORCH_LOGS="graph_code" python playground3.py 
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] TRACED GRAPH
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  ===== __compiled_fn_1 =====
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  /data/users/williamwen/pytorch2/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]     def forward(self, L_x_: "b8[4]", L_y_: "b8[4]"):
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         l_x_ = L_x_
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         l_y_ = L_y_
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         # File: /data/users/williamwen/pytorch2/playground3.py:6 in f, code: x = x - y
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         x: "b8[4]" = l_x_ - l_y_;  l_x_ = None
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         return (l_y_,)
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 13:16:09.159000 140482399983424 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] 
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch2/playground3.py", line 14, in <module>
    opt_f(inp_x, inp_y)
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 414, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/pytorch2/playground3.py", line 3, in f
    def f(x, y):
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 548, in _fn
    return fn(*args, **kwargs)
  File "<eval_with_key>.1", line 7, in forward
RuntimeError: Subtraction, the `-` operator, with two bool tensors is not supported. Use the `^` or `logical_xor()` operator instead.
```

**Comment by williamwen42** [comment]
Probably just need to update the meta/fake tensor implementation.

**Comment by zeb209** [comment]
What is the expected behavior here? The traced graph says that "Subtraction, the `-` operator, with two bool tensors is not supported."

**Comment by williamwen42** [comment]
Dynamo should detect the subtraction error when tracing the function and skip the frame. The output shows that dynamo is instead not detecting the error and tracing the incorrect codepath as a result.

**Comment by NevroHelios** [comment]
Hi everyone,

If no one is currently working on this issue, I would like to take it up as my first contribution.

Thank you!

**Comment by williamwen42** [comment]
Issue is still open - just submit a PR.
