### ISSUE TITLE
[dynamo] Fake tensor impl for torch.addr not checking for errors

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#127043]
Discovered with https://github.com/pytorch/pytorch/pull/126341.

Original repro: `PYTORCH_TEST_WITH_DYNAMO=1 pytest test/test_linalg.py::TestLinalgCPU::test_addr_float_and_complex_cpu_float16`

Minimal repro:
```python
import torch

def f(m, a, b):
    try:
        res = torch.addr(m, a, b, beta=True, alpha=2)
    except:
        return m + 1
    return res

opt_f = torch.compile(f, backend="eager")
m = torch.randn(8, 8)
a = torch.rand(8)
b = torch.rand(8)
opt_f(m, a, b)
```

Output:
```
$ TORCH_LOGS="graph_code" python playground3.py 
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] TRACED GRAPH
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  ===== __compiled_fn_1 =====
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  /data/users/williamwen/pytorch2/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]     def forward(self, L_m_: "f32[8, 8]", L_a_: "f32[8]", L_b_: "f32[8]"):
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         l_m_ = L_m_
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         l_a_ = L_a_
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         l_b_ = L_b_
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         # File: /data/users/williamwen/pytorch2/playground3.py:5 in f, code: res = torch.addr(m, a, b, beta=True, alpha=2)
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         res: "f32[8, 8]" = torch.addr(l_m_, l_a_, l_b_, beta = True, alpha = 2);  l_m_ = l_a_ = l_b_ = None
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         return (res,)
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 17:08:10.586000 139803696768832 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] 
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch2/playground3.py", line 14, in <module>
    opt_f(m, a, b)
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 414, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/pytorch2/playground3.py", line 3, in f
    def f(m, a, b):
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 548, in _fn
    return fn(*args, **kwargs)
  File "<eval_with_key>.1", line 8, in forward
RuntimeError: Boolean beta only supported for Boolean results.
```

It looks like this error occurs because the fake tensor implementation for torch.addr isn't performing all the necessary error checks.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by fabricerenard12** [comment]
If no one is currently working on this issue I would like to take it as a first contribution

**Comment by williamwen42** [comment]
Relevant file should be here: https://github.com/pytorch/pytorch/blob/main/torch/_refs/__init__.py

**Comment by dimichoueiry** [comment]
Hey! I don't see anyone assigned to this issue so I would like to try and solve the issue if possible :)
