### ISSUE TITLE
[dynamo] Fake tensor impl for Tensor.add_ not checking for errors

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#127049]
Similar issue to https://github.com/pytorch/pytorch/issues/127043.

Repro: `PYTORCH_TEST_WITH_DYNAMO=1 pytest test/test_type_promotion.py::TestTypePromotionCPU::test_inplace_cpu` - problematic op is `Tensor.add_`.

Repro:
```python
import torch

def f(x):
    try:
        x.add_(1.5)
    except:
        return x + 1
    return x + 2

opt_f = torch.compile(f, backend="eager")
inp = torch.ones(3, dtype=torch.int64)
opt_f(inp)
```

Output:
```
$ TORCH_LOGS="graph_code" python playground3.py 
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] TRACED GRAPH
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  ===== __compiled_fn_1 =====
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]  /data/users/williamwen/pytorch2/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]     def forward(self, L_x_: "i64[3]"):
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         l_x_ = L_x_
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         # File: /data/users/williamwen/pytorch2/playground3.py:5 in f, code: x.add_(1.5)
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         add_: "i64[3]" = l_x_.add_(1.5)
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         # File: /data/users/williamwen/pytorch2/playground3.py:8 in f, code: return x + 2
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         add: "i64[3]" = l_x_ + 2;  l_x_ = None
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         return (add,)
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code]         
V0523 18:37:46.490000 140151595521856 torch/_dynamo/output_graph.py:1277] [0/0] [__graph_code] 
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch2/playground3.py", line 12, in <module>
    opt_f(inp)
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 414, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/pytorch2/playground3.py", line 3, in f
    def f(x):
  File "/data/users/williamwen/pytorch2/torch/_dynamo/eval_frame.py", line 548, in _fn
    return fn(*args, **kwargs)
  File "<eval_with_key>.1", line 6, in forward
RuntimeError: result type Float can't be cast to the desired output type Long
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by Etelis** [comment]
I will work on this one as well :)

**Comment by arnav177** [comment]
Title: Fix Data Type Casting Issue in Function f
Issue Reference
Resolves issue #127042.

Description
This pull request addresses a data type casting issue in the function f. The function is intended to perform in-place addition on a tensor, but it encounters errors when the input tensor is not of type Float. The fix explicitly casts the input tensor to Float type before performing the addition.

Code Explanation
The function f is modified to include an explicit cast to Float type for the input tensor x. This ensures that the in-place addition operation does not raise an error for integer input tensors. Here’s the updated function:

import torch

def f(x):
    try:
        x = x.float()  # Explicitly cast x to Float type
        x.add_(1.5)
    except:
        return x + 1
    return x + 2

opt_f = torch.compile(f, backend="eager")
inp = torch.ones(3, dtype=torch.int64)
opt_f(inp)


![open source](https://github.com/pytorch/pytorch/assets/134754217/ffb52d2e-53a2-496c-9d96-a449e904637f)

**Comment by yashvsrathore** [comment]
if this issue is open I would like to take it up.

**Comment by aniketinamdar** [comment]
`import torch

def f(x):
    try:
        x = x.to(torch.float)
        x.add_(1.5)
    except:
        return x + 1
    return x + 2

opt_f = torch.compile(f, backend="eager")
inp = torch.ones(3, dtype=torch.int64)
result = opt_f(inp)
print(result)
`

The above code is giving me the following output

![image](https://github.com/pytorch/pytorch/assets/79044809/c45a3327-3f83-47e9-9db4-3f82195d4427)

Changes are made in the following line
` x = x.to(torch.float)`

**Comment by aniketinamdar** [comment]
If no one is currently working on this issue I would like to work on it.

**Comment by gagan-bhullar-tech** [comment]
can i look into this

**Comment by williamwen42** [comment]
Just submit a PR!

**Comment by awayzjj** [comment]
@williamwen42 Hi, I am currently working on the issue. 

But I fould unlike the `torch.addr` in https://github.com/pytorch/pytorch/blob/main/torch/_refs/__init__.py which you mentioned in the https://github.com/pytorch/pytorch/issues/127043. 
I made some changes to the `add_` function in the same file, 
https://github.com/pytorch/pytorch/blob/8a5fda0377274f88ab255f1ba05bdc3ed0e99c43/torch/_refs/__init__.py#L1070-L1078
but the repro script you provided did not step into it, is this the correct file to modify?
Thank you very much!

**Comment by maushumee** [comment]
> @williamwen42 Hi, I am currently working on the issue.
> 
> But I found unlike the `torch.addr` in https://github.com/pytorch/pytorch/blob/main/torch/_refs/__init__.py which you mentioned in the #127043. I made some changes to the `add` function in the same file,
> 
> https://github.com/pytorch/pytorch/blob/8a5fda0377274f88ab255f1ba05bdc3ed0e99c43/torch/_refs/__init__.py#L1070-L1078
> 
> 
> but the repro script you provided did not step into it, is this the correct file to modify?
> Thank you very much!

Hi, I am a new contributor and I have this same question. It looks like Tensor.add_ function mentioned in the description of this issue comes from torch/_C/__init__.pyi. I could not find the func definition of Tensor.add_ anywhere just the type information in the .pyi file mentioned above. @williamwen42 , could you please give any pointers in the right direction? Would much appreciate the help. Thank you!

**Comment by williamwen42** [comment]
Sorry for the late response! You can try looking in https://github.com/pytorch/pytorch/blob/main/torch/_prims/__init__.py or https://github.com/pytorch/pytorch/blob/main/torch/_meta_registrations.py

**Comment by DuyguA** [comment]
Heys @williamwen42  , I made a quick PR please have a look :blush: 

I added the error checks so, output of your original code now looks like:

```
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0] failed while attempting to run meta for aten.add_.Tensor
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0] Traceback (most recent call last):
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0]   File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_subclasses/fake_tensor.py", line 2013, in _dispatch_impl
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0]     r = func(*args, **kwargs)
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0]   File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_ops.py", line 716, in __call__
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0]     return self._op(*args, **kwargs)
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0]   File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_meta_registrations.py", line 3593, in meta_binop_inplace_promote
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0]     raise RuntimeError("Promotion of int.add/sub_(float) in in-place ops are not possible due to element size change.")
E0912 14:09:33.353081 4733 pytorch/torch/_subclasses/fake_tensor.py:2017] [0/0] RuntimeError: Promotion of int.add/sub_(float) in in-place ops are not possible due to element size change.
Traceback (most recent call last):
  File "/mnt/disks/newd/contrib/torch_code/orig.py", line 12, in <module>
    opt_f(inp)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 1274, in __call__
    return self._torchdynamo_orig_callable(
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 1069, in __call__
    result = self._inner_convert(
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 929, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 671, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 704, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/convert_frame.py", line 639, in transform
    tracer.run()
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/symbolic_convert.py", line 2766, in run
    super().run()
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/symbolic_convert.py", line 973, in run
    while self.step():
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/symbolic_convert.py", line 885, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/symbolic_convert.py", line 570, in wrapper
    return inner_fn(self, inst)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/symbolic_convert.py", line 1592, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/symbolic_convert.py", line 820, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/variables/misc.py", line 1024, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/variables/tensor.py", line 535, in call_method
    return wrap_fx_proxy(
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/variables/builder.py", line 2040, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/variables/builder.py", line 2127, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/utils.py", line 2079, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/utils.py", line 2014, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/utils.py", line 1573, in wrap_fake_exception
    return fn()
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/utils.py", line 2015, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/utils.py", line 2147, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_dynamo/utils.py", line 2131, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_subclasses/fake_tensor.py", line 1238, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_subclasses/fake_tensor.py", line 1692, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_subclasses/fake_tensor.py", line 1339, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_subclasses/fake_tensor.py", line 2013, in _dispatch_impl
    r = func(*args, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_ops.py", line 716, in __call__
    return self._op(*args, **kwargs)
  File "/mnt/disks/newd/contrib/torch_code/pytorch/torch/_meta_registrations.py", line 3593, in meta_binop_inplace_promote
    raise RuntimeError("Promotion of int.add/sub_(float) in in-place ops are not possible due to element size change.")
torch._dynamo.exc.TorchRuntimeError: Failed running call_method add_(*(FakeTensor(..., size=(3,), dtype=torch.int64), 1.5), **{}):
Promotion of int.add/sub_(float) in in-place ops are not possible due to element size change.

from user code:
   File "/mnt/disks/newd/contrib/torch_code/orig.py", line 5, in f
    x.add_(1.5)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```
