### ISSUE TITLE
[feature request]: Update max onnx opset to 21 for onnxruntime==1.18 compatability

### ISSUE THREAD

**Issue by MengLinMaker** [pytorch/pytorch#127167]
## Description
[Onnxruntime==1.18 supports onnx opset 21](https://onnxruntime.ai/docs/reference/compatibility.html).

Pytorch currently does not support conversion to onnx opset 21.

## Proposed implementation
The change seems simple:
Just update the `ONNX_MAX_OPSET` constant from [/torch/onnx/_constants.py](https://github.com/pytorch/pytorch/blob/ba3b05fdf37ddbc3c301294d6a560a816335e717/torch/onnx/_constants.py#L7).

```
"""Constant values used in ONNX."""

ONNX_ARCHIVE_MODEL_PROTO_NAME = "__MODEL_PROTO"

ONNX_BASE_OPSET = 9
ONNX_MIN_OPSET = 7
ONNX_MAX_OPSET = 21
```

**Limitations:**
Using constants shifts the responsibility of updating constants to `pytorch`. Is there an alternative way of detecting that an `OPSET` is not supported without maintenance?

## Workarounds
Currently, the way to workaround this issue is to use some additional code after exporting an onnx file from pytorch:

```
import onnx

opset=21
upgradedModel = onnx.version_converter.convert_version(modelFromTorch, opset)
onnx.save(upgradedModel, modelPath)
```

**Comment by justinchuby** [comment]
We will add opset21 support in the coming months. Thanks!

**Comment by jeffreywolberg** [comment]
Following up on the progress of exporting opset21 in torch?

**Comment by justinchuby** [comment]
Could you create a pull request, simply bumping the constant will do for now.

**Comment by jeffreywolberg** [comment]
Not sure why bumping the version number is helpful -- we would need to actually implement everything in torch required to use opset 21. Even with bumping the version 21, you still run into the following errors:

Error when using `torch.onnx.dynamo_export` with opset 21:
```
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1509, in dynamo_export
    ).export()
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1236, in export
    graph_module = self.options.fx_tracer.generate_fx(
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 214, in generate_fx
    graph_module, graph_guard = torch._dynamo.export(
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1379, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 169, in wrapped
    return output_adapter.apply(model_func(*args, **kwargs), model=model)
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/jit/_trace.py", line 1404, in forward
    raise RuntimeError("Trace submodules cannot be called.")
RuntimeError: Trace submodules cannot be called.
```

And when using `torch.onnx.export`:
```
/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py:884: UserWarning: no signature found for <torch.ScriptMethod object at 0x7bf31d93a520>, skipping _decide_input_format
  warnings.warn(f"{e}, skipping _decide_input_format")
Traceback (most recent call last):
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jwolberg/bee/s3vp/scripts/model/torch_to_onnx.py", line 117, in <module>
    torch.onnx.export(model, 
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1174, in _model_to_graph
    graph = _optimize_graph(
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 714, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1997, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/symbolic_opset9.py", line 6936, in prim_constant
    return g.op("Constant", value_t=symbolic_helper._node_get(node, "value"))
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py", line 93, in op
    return _add_op(self, opname, *raw_args, outputs=outputs, **kwargs)
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py", line 252, in _add_op
    node = _create_node(
  File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py", line 314, in _create_node
    _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
RuntimeError: Unsupported onnx_opset_version: 21
```

**Comment by MengLinMaker** [comment]
> Not sure why bumping the version number is helpful -- we would need to actually implement everything in torch required to use opset 21. Even with bumping the version to 21, you still run into the following errors:
> 
> Error when using `torch.onnx.dynamo_export` with opset 21:
> 
> ```
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1509, in dynamo_export
>     ).export()
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 1236, in export
>     graph_module = self.options.fx_tracer.generate_fx(
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 214, in generate_fx
>     graph_module, graph_guard = torch._dynamo.export(
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1379, in inner
>     result_traced = opt_f(*args, **kwargs)
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
>     return fn(*args, **kwargs)
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 169, in wrapped
>     return output_adapter.apply(model_func(*args, **kwargs), model=model)
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/jit/_trace.py", line 1404, in forward
>     raise RuntimeError("Trace submodules cannot be called.")
> RuntimeError: Trace submodules cannot be called.
> ```
> 
> And when using `torch.onnx.export`:
> 
> ```
> /home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py:884: UserWarning: no signature found for <torch.ScriptMethod object at 0x7bf31d93a520>, skipping _decide_input_format
>   warnings.warn(f"{e}, skipping _decide_input_format")
> Traceback (most recent call last):
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/jwolberg/bee/s3vp/scripts/model/torch_to_onnx.py", line 117, in <module>
>     torch.onnx.export(model, 
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 551, in export
>     _export(
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
>     graph, params_dict, torch_out = _model_to_graph(
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1174, in _model_to_graph
>     graph = _optimize_graph(
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 714, in _optimize_graph
>     graph = _C._jit_pass_onnx(graph, operator_export_type)
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1997, in _run_symbolic_function
>     return symbolic_fn(graph_context, *inputs, **attrs)
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/symbolic_opset9.py", line 6936, in prim_constant
>     return g.op("Constant", value_t=symbolic_helper._node_get(node, "value"))
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py", line 93, in op
>     return _add_op(self, opname, *raw_args, outputs=outputs, **kwargs)
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py", line 252, in _add_op
>     node = _create_node(
>   File "/home/jeffrey/miniforge3/envs/torch_venv/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py", line 314, in _create_node
>     _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
> RuntimeError: Unsupported onnx_opset_version: 21
> ```

My understanding is that these constants are used in guard clauses to prevent conversion to unsupported opset versions.
See [torch/onnx/_globals.py#L56](https://github.com/pytorch/pytorch/blob/ba3b05fdf37ddbc3c301294d6a560a816335e717/torch/onnx/_globals.py#L56).
This is the definitely the first step towards supporting opset 21.

Looking through [torch/onnx/__init__.py#L353](https://github.com/pytorch/pytorch/blob/bb22132c8dd4647f6b75481dabfbe5d2717e7b4d/torch/onnx/__init__.py#L353), `dynamo=True` should use `onnx.version_converter.convert_version` for conversion internally.

For `dynamo=False`, maybe `torch.onnx.symbolic_opset21` will need to be implemented according to [opset v21](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#version-21-of-the-default-onnx-operator-set).
We can use PR #118828 as an example of how to support opset 21.

To make matters more confusing, it's possible that we're using an older version of `torch` and not the latest. Our findings may not apply to this codebase anymore.
How are you installing pytorch? - `conda install` judging by your file paths?

**Comment by MengLinMaker** [comment]
Oh, I did not consider that Pytorch python part binds to C++.

**Comment by e-said** [comment]
Hello , I wanted to check if there are any updates on adding support for ONNX opset 21 in PyTorch. This feature would be really beneficial for many users, so any information would be greatly appreciated! Thanks

**Comment by MengLinMaker** [comment]
> Hello , I wanted to check if there are any updates on adding support for ONNX opset 21 in PyTorch. This feature would be really beneficial for many users, so any information would be greatly appreciated! Thanks

I was working on a PR.

Right now a test is failing. Difference between test and expected tensor values are too big:
[`test/onnx/test_pytorch_onnx_onnxruntime.py TestONNXRuntime_opset_version_21_is_script_True_keep_initializers_as_inputs_True.test_avgpool_3d_ceil`](https://github.com/pytorch/pytorch/blob/2c9e194e23b02f0ed51b3d6bc0d9cf30924ba49a/test/onnx/test_pytorch_onnx_onnxruntime.py#L1611)

I think maybe `torch.onnx.symbolic_opset21` needs to be  implemented?

**Comment by justinchuby** [comment]
Feel free to skip the failing test for now. Thanks

**Comment by justinchuby** [comment]
> How does dynamo setting impact how onnx is exported?

Dynamo opset support is separate. For now you may ignore

> How to write a test that exports to opset 21?

You may skip the tests for now

> What is the purpose of this if it's not implemented in torch.onnx.export?

We will refactor later

**Comment by e-said** [comment]
Hello @MengLinMaker,

> I think maybe torch.onnx.symbolic_opset21 needs to be implemented?

In opset 21, the operator [QuantizeLinear-21](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#QuantizeLinear-21) introduces new attributes (output_dtype and block_size). These additions may probably require implementing torch.onnx.symbolic_opset21, as you've mentioned, to handle the export correctly.

Opset 21 is important for exporting PyTorch models with mixed precision quantization. Currently, only 8-bit (bw=8) quantization is supported in PyTorch’s ONNX export, so expanding this to include mixed precision could involve supporting QuantizeLinear/DequantizeLinear-21.

@justinchuby, could you share your thoughts on whether implementing symbolic_opset21 would be enough/necessary ?

Thanks

**Comment by e-said** [comment]
Hello @justinchuby @MengLinMaker 

I just wanted to kindly ask if there are any updates or feedback on this issue.

Thanks

**Comment by MengLinMaker** [comment]
> Hello @justinchuby @MengLinMaker
> 
> I just wanted to kindly ask if there are any updates or feedback on this issue.
> 
> Thanks

Try this for now if you need a working solution - at least worked for me:
```
import onnx

opset=21
upgradedModel = onnx.version_converter.convert_version(modelFromTorch, opset)
onnx.save(upgradedModel, modelPath)
```

The situation is more complicated than I though.
Apparently part of the opset21 is incorrect, not sure if this is fixed.

@e-said If you know how to fix the issue, feel free to git it a go.

**Comment by justinchuby** [comment]
Using the version converter is a reasonable thing to do for now.

**Comment by e-said** [comment]
Hello @MengLinMaker @justinchuby 

Thank you for the proposed workaround. Unfortunately, this won't resolve the issue, as I am aiming to export a PyTorch model with mixed precision nodes (INT8/INT16) to ONNX. Currently, only a direct conversion to ONNX opset 21 can support the mixed precision requirements, particularly for handling  Q/DQ ([QuantizeLinear](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#QuantizeLinear-21)) effectively.

BTW thanks to @adrianlizarraga 16-bit support to Q/DQ ops was added in ONNX (cf. https://github.com/onnx/onnx/pull/5737)

**Comment by e-said** [comment]
Hi @justinchuby,

I wanted to follow up on this issue to check if there have been any updates. If this particular concern is not within the current scope, would you recommend raising a separate ticket to address it?

Thanks

**Comment by justinchuby** [comment]
We are adding opset 21 support to the dynamo=True API. @shubhambhokare1 can share more

Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

**Comment by e-said** [comment]
Hello @justinchuby 

I tested the export with torch.onnx.export(..., dynamo=True) using the latest torch-nightly (2.5.1+cu121). However, I wasn't able to observe the QuantizeLinear ops in the exported ONNX graph.

It seems that when dynamo=True, TorchDynamo traces the computation graph differently. Instead of directly preserving the QuantizeLinear operation, it decomposes it into its underlying arithmetic steps, such as Mul, Round, and Add. This decomposition reflects the mathematical steps of quantization (scaling, rounding, offsetting), but it loses the high-level abstraction of QuantizeLinear.

Here’s an example to illustrate:

With dynamo=False and opset=20 (to be able to do the export as opset 21 is not supported without dynamo), the graph includes the QuantizeLinear op:
![Image](https://github.com/user-attachments/assets/8341dee9-6cd7-47be-ad26-c0ac39c65a24)

With dynamo=True, the graph instead shows the decomposed arithmetic operations

![Image](https://github.com/user-attachments/assets/71f8c863-d4ba-4595-9c32-6f227ab68e07)

I’ve attached the following for your reference:

The generated report: [onnx_export_2025-01-23_18-19-11-035579_strategies.md](https://github.com/user-attachments/files/18526365/onnx_export_2025-01-23_18-19-11-035579_strategies.md)
The notebook I used for testing: [QDQ_onnx_export.zip](https://github.com/user-attachments/files/18526384/QDQ_onnx_export.zip)

Let me know if you need further details. Thanks

**Comment by justinchuby** [comment]
You may need to refer to https://pytorch.org/tutorials/prototype/pt2e_quant_ptq.html and https://pytorch.org/tutorials/prototype/pt2e_quant_qat.html for pt2 quantization support when dynamo is true.

**Comment by hitbuyi** [comment]
> We will add opset21 support in the coming months. Thanks!

pytorch2.2.2 still doesn't support opset 21 yet

**Comment by justinchuby** [comment]
The latest version is PyTorch 2.7 (2.8 to be released soon). Please use these new versions.
