### ISSUE TITLE
Tensor Parallel cannot work when tp mesh size is 1

### ISSUE THREAD

**Issue by Fanoid** [pytorch/pytorch#127213]
### 🐛 Describe the bug

By using tensor parallel API, I expect we can disable TP by setting its mesh size to 1. But this does not work. Here is a reproduction case:

```
import torch
from torch.distributed.tensor.parallel import ColwiseParallel, parallelize_module
from torch.testing._internal.common_utils import run_tests
from torch.testing._internal.distributed._tensor.common_dtensor import DTensorTestBase, with_comms


class MyModule(torch.nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.linear = torch.nn.Linear(10, 10)

    def forward(self, x):
        x = self.linear(x)
        return x


class TensorParallelSize1Test(DTensorTestBase):

    @property
    def world_size(self) -> int:
        return 1

    @with_comms
    def test_auto_tp_plan(self):
        mesh = self.build_device_mesh()
        plan = {
            'linear': ColwiseParallel(),
        }
        module = MyModule()
        module = parallelize_module(module, mesh, plan)
        module = module.to(torch.cuda.current_device())
        x = torch.randn(10, 10)
        x = x.cuda()
        out = module(x)
        print(f'{out = }')


if __name__ == '__main__':
    run_tests()
```

The error message is:
```
Traceback (most recent call last):
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 656, in run_test
    getattr(self, test_name)()
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 542, in wrapper
    fn()
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 281, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
  File "/home/hongfan.hf/Code/AutoParallel/tests/zoos/tp_size_1_bug.py", line 34, in test_auto_tp_plan
    out = module(x)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hongfan.hf/Code/AutoParallel/tests/zoos/tp_size_1_bug.py", line 13, in forward
    x = self.linear(x)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/api.py", line 279, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/dispatch.py", line 113, in dispatch
    self.sharding_propagator.propagate(op_info)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/sharding_prop.py", line 165, in propagate
    output_sharding = self.propagate_op_sharding(op_info.schema)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/sharding_prop.py", line 213, in propagate_op_sharding_non_cached
    op_strategy = self.op_strategy_funcs[op_schema.op](mesh, strategy_schema)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/ops/matrix_ops.py", line 133, in addmm_strategy
    return _addmm_like_strategy("mk,kn->mn", mesh, op_schema)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/ops/matrix_ops.py", line 87, in _addmm_like_strategy
    mm_strategy = gen_einsum_strategies(mm_equation, mesh)
  File "/home/hongfan.hf/miniconda3/envs/torch23/lib/python3.10/site-packages/torch/distributed/_tensor/ops/basic_strategy.py", line 181, in gen_einsum_strategies
    strat = PlacementStrategy(output_specs=spec_list[0], input_specs=spec_list[1:])
IndexError: list index out of range
```

**Comment by awgu** [comment]
I think we just need to fix this (I filed an issue like this before in https://github.com/pytorch/pytorch/issues/113761).

**Comment by Fanoid** [comment]
Thx. I think they are same issue, I'll close this one.
