### ISSUE TITLE
RuntimeError: grid_sampler_2d_cpu not implemented for Half

### ISSUE THREAD

**Issue by asusdisciple** [pytorch/pytorch#127224]
### 🐛 Describe the bug

I use a variety of transforms for my training, however the `grid_sampler` seems to be not implemented for cpu when using mixed training on fp16? Is there any solution to use all image `transforms in torchvision` with mixed training? Is it maybe possible to move them to the gpu, if this method is implemented there? Did not find a lot of documentation on that issue, maybe you guys can help me.

```
RuntimeError:
Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/raid/.../projects/script-classifier/dataset.py", line 68, in __getitem__
    image = self.transform(image)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torchvision/transforms/v2/_container.py", line 51, in forward
    outputs = transform(*inputs)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torchvision/transforms/v2/_auto_augment.py", line 495, in forward
    image_or_video = self._apply_image_or_video_transform(
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torchvision/transforms/v2/_auto_augment.py", line 121, in _apply_image_or_video_transform
    return F.affine(
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torchvision/transforms/v2/functional/_geometry.py", line 401, in affine
    return kernel(
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torchvision/transforms/v2/functional/_geometry.py", line 730, in affine_image
    return _apply_grid_transform(image, grid, interpolation.value, fill=fill)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torchvision/transforms/v2/functional/_geometry.py", line 619, in _apply_grid_transform
    float_img = grid_sample(float_img, grid, mode=mode, padding_mode="zeros", align_corners=False)
  File "/raid/.../projects/script-classifier/venv2/lib/python3.10/site-packages/torch/nn/functional.py", line 4351, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler_2d_cpu not implemented for Half
```

### Versions

Torch Master
Python 3.12 

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by Skylion007** [comment]
Someone just needs to change the dispatch macros for the fwd and bwd to support float16/bfloat16 for the CPU kernels too: https://github.com/pytorch/pytorch/blob/0ff2f8b52248323bbe25108b64e706c43390cb72/aten/src/ATen/native/cpu/GridSamplerKernel.cpp#L1275C3-L1275C29 Would be a good first issue. They'll also need to make sure optest in the test suite has the tests for those dtypes enabeld.

**Comment by mingfeima** [comment]
@jiayisunx please fix this one!

**Comment by asusdisciple** [comment]
May I ask if there is a solution to do this on the gpu meanhile? or some other kind of "hack"? I tried bringing my transforms to the gpu with `transform.to(device)` but this did not really work out :)

**Comment by Skylion007** [comment]
@asusdisciple dispatch is registered for CUDA on float16 and bfloat16 types so that should work.

**Comment by asusdisciple** [comment]
@Skylion007 I can not confirm this or I do not really understand what you mean. I use `torch.float16` as input datatype for my transforms.
