### ISSUE TITLE
[BUG][JIT] `torch.jit.script` is not compatible with `DeprecationWarning` and `FutureWarning`

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#127283]
### 🐛 Describe the bug

`torch.jit.script` is not compatible with `warnings.warn` when the warning category is specified.

Reference: 

- #126898
- Commit c2a843d21850552d07012e07b276490a4d1db52c

```python
In [1]: import warnings

In [2]: import torch

In [3]: def func0(x):
   ...:     warnings.warn("func0 is deprecated")  # UserWarning is the default category
   ...:     return x
   ...:

In [4]: torch.jit.script(func0)  # OK
Out[4]: <torch.jit.ScriptFunction object at 0x7f0f9a1dccb0>

In [5]: def func1(x):
   ...:     warnings.warn("func1 is deprecated", UserWarning)
   ...:     return x
   ...:

In [6]: torch.jit.script(func1)
╭───────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────╮
│ <ipython-input-6-501924eff1a7>:1 in <module>                                                                                 │
│                                                                                                                              │
│ /home/PanXuehai/Projects/pytorch/torch/jit/_script.py:1429 in script                                                         │
│                                                                                                                              │
│   1426 │   _TOPLEVEL = False                                                                                                 │
│   1427 │                                                                                                                     │
│   1428 │   try:                                                                                                              │
│ ❱ 1429 │   │   return _script_impl(                                                                                          │
│   1430 │   │   │   obj=obj,                                                                                                  │
│   1431 │   │   │   optimize=optimize,                                                                                        │
│   1432 │   │   │   _frames_up=_frames_up + 1,                                                                                │
│                                                                                                                              │
│ /home/PanXuehai/Projects/pytorch/torch/jit/_script.py:1201 in _script_impl                                                   │
│                                                                                                                              │
│   1198 │   │   ast = get_jit_def(obj, obj.__name__)                                                                          │
│   1199 │   │   if _rcb is None:                                                                                              │
│   1200 │   │   │   _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)                                             │
│ ❱ 1201 │   │   fn = torch._C._jit_script_compile(                                                                            │
│   1202 │   │   │   qualified_name, ast, _rcb, get_default_args(obj)                                                          │
│   1203 │   │   )                                                                                                             │
│   1204 │   │   # Forward docstrings                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError:
Python exception cannot be used as a value:
  File "<ipython-input-5-c4f0f2070b6c>", line 2
def func1(x):
    warnings.warn("func1 is deprecated", UserWarning)
                                         ~~~~~~~~~~~ <--- HERE
    return x


In [7]: def func2(x):
   ...:     warnings.warn("func2 is deprecated", DeprecationWarning)
   ...:     return x
   ...:

In [8]: torch.jit.script(func2)
╭───────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────╮
│ <ipython-input-8-9c358e7e7293>:1 in <module>                                                                                 │
│                                                                                                                              │
│ /home/PanXuehai/Projects/pytorch/torch/jit/_script.py:1429 in script                                                         │
│                                                                                                                              │
│   1426 │   _TOPLEVEL = False                                                                                                 │
│   1427 │                                                                                                                     │
│   1428 │   try:                                                                                                              │
│ ❱ 1429 │   │   return _script_impl(                                                                                          │
│   1430 │   │   │   obj=obj,                                                                                                  │
│   1431 │   │   │   optimize=optimize,                                                                                        │
│   1432 │   │   │   _frames_up=_frames_up + 1,                                                                                │
│                                                                                                                              │
│ /home/PanXuehai/Projects/pytorch/torch/jit/_script.py:1201 in _script_impl                                                   │
│                                                                                                                              │
│   1198 │   │   ast = get_jit_def(obj, obj.__name__)                                                                          │
│   1199 │   │   if _rcb is None:                                                                                              │
│   1200 │   │   │   _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)                                             │
│ ❱ 1201 │   │   fn = torch._C._jit_script_compile(                                                                            │
│   1202 │   │   │   qualified_name, ast, _rcb, get_default_args(obj)                                                          │
│   1203 │   │   )                                                                                                             │
│   1204 │   │   # Forward docstrings                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError:
Python exception cannot be used as a value:
  File "<ipython-input-7-b51cafdeee6e>", line 2
def func2(x):
    warnings.warn("func2 is deprecated", DeprecationWarning)
                                         ~~~~~~~~~~~~~~~~~~ <--- HERE
    return x


In [9]: def func3(x):
   ...:     warnings.warn("func3 is deprecated", FutureWarning)
   ...:     return x
   ...:

In [10]: torch.jit.script(func3)
╭───────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────╮
│ <ipython-input-10-dd37498f163c>:1 in <module>                                                                                │
│                                                                                                                              │
│ /home/PanXuehai/Projects/pytorch/torch/jit/_script.py:1429 in script                                                         │
│                                                                                                                              │
│   1426 │   _TOPLEVEL = False                                                                                                 │
│   1427 │                                                                                                                     │
│   1428 │   try:                                                                                                              │
│ ❱ 1429 │   │   return _script_impl(                                                                                          │
│   1430 │   │   │   obj=obj,                                                                                                  │
│   1431 │   │   │   optimize=optimize,                                                                                        │
│   1432 │   │   │   _frames_up=_frames_up + 1,                                                                                │
│                                                                                                                              │
│ /home/PanXuehai/Projects/pytorch/torch/jit/_script.py:1201 in _script_impl                                                   │
│                                                                                                                              │
│   1198 │   │   ast = get_jit_def(obj, obj.__name__)                                                                          │
│   1199 │   │   if _rcb is None:                                                                                              │
│   1200 │   │   │   _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)                                             │
│ ❱ 1201 │   │   fn = torch._C._jit_script_compile(                                                                            │
│   1202 │   │   │   qualified_name, ast, _rcb, get_default_args(obj)                                                          │
│   1203 │   │   )                                                                                                             │
│   1204 │   │   # Forward docstrings                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError:
Python exception cannot be used as a value:
  File "<ipython-input-9-4b6a0e0081f1>", line 2
def func3(x):
    warnings.warn("func3 is deprecated", FutureWarning)
                                         ~~~~~~~~~~~~~ <--- HERE
    return x
```

### Versions

nightly

**Comment by EikanWang** [comment]
@XuehaiPan , have you tried to `torch.jit.trace`?

**Comment by EikanWang** [comment]
Currently, it should be a limitation of `torch.jit.script`.

**Comment by XuehaiPan** [comment]
> @XuehaiPan , have you tried to `torch.jit.trace`?

`torch.jit.trace` works as expected.

> Currently, it should be a limitation of `torch.jit.script`.

In CI tests for `torch.jit.script`, we cannot add the warning category in `warnings.warn`.

**Comment by EikanWang** [comment]
May I know if you are trying to submit PR to refine the deprecated `nn.module`?

**Comment by XuehaiPan** [comment]
> May I know if you are trying to submit PR to refine the deprecated `nn.module`?

I'm trying to add `FutureWarning`s to functions in `torch.nn.functional`.

- Commit: Remove `FutureWarning` for JIT compatibility c2a843d21850552d07012e07b276490a4d1db52c

**Comment by EikanWang** [comment]
@XuehaiPan , according to your commit, `torch.jit.script` can work now, right?

**Comment by XuehaiPan** [comment]
> @XuehaiPan , according to the commit, `FutureWarning` was removed. So, `torch.jit.script` can work now, right?

Yes.

The problem is we cannot raise `FutureWarning`s in deprecated APIs in `torch.nn`. We can only use the default `UserWarning` category.

**Comment by EikanWang** [comment]
@ezyang , I'm not sure if we need to invest more effort in `torch.jit.script` to support `FutureWarning`. Personally, I prefer to leave the limitation as it is, as I think it is a nice-to-have feature. Any comments?

**Comment by ezyang** [comment]
While we're not maintaining TS, we're also not breaking TS tests (yet, anyway). So if it's a small patch to add FutureWarning support, I'd accept it, purely on work minimization reasons

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
