### ISSUE TITLE
investigate :torch._dynamo.exc.Unsupported: cache_size_limit reached  when inlining nn module for test_do_not_skip_side_effects

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#127483]
repo:
 TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1  TORCH_LOGS="+dynamo, bytecode, graph" python test/dynamo/test_skip_non_tensor.py -k test_do_not_skip_side_effects
 
 ```
 unimplemented [('cache_size_limit reached', 1)]
E
======================================================================
ERROR: test_do_not_skip_side_effects (__main__.SkipNonTensorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/lsakka/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2756, in wrapper
    method(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py", line 181, in test_do_not_skip_side_effects
    model(torch.tensor([1]))
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 414, in _fn
    return fn(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 1085, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 464, in _convert_frame_assert
    return _compile(
  File "/data/users/lsakka/pytorch/pytorch/torch/_utils_internal.py", line 74, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/lsakka/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/convert_frame.py", line 764, in _compile
    unimplemented(f"{limit_type} reached")
  File "/data/users/lsakka/pytorch/pytorch/torch/_dynamo/exc.py", line 216, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: cache_size_limit reached

```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by laithsakka** [comment]
running with  TORCH_LOGS="recompiles" with out inlining:

```
[lsakka@devvm4561.ash0 /data/users/lsakka/pytorch/pytorch (fix_op_count)]$ TORCH_LOGS="recompiles" python test/dynamo/test_skip_non_tensor.py -k test_do_not_skip_side_effects
V0529 16:36:59.419000 140372644329280 torch/_dynamo/guards.py:2598] [1/1] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:59.419000 140372644329280 torch/_dynamo/guards.py:2598] [1/1] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:59.419000 140372644329280 torch/_dynamo/guards.py:2598] [1/1] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.438000 140372644329280 torch/_dynamo/guards.py:2598] [1/3] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:59.438000 140372644329280 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:59.438000 140372644329280 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.438000 140372644329280 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     - ___check_obj_id(L['self'], 140369290455472)                 
V0529 16:36:59.438000 140372644329280 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - ___check_obj_id(L['self'], 140369275927328)                 
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - ___check_obj_id(L['self'], 140369290455472)                 
V0529 16:36:59.456000 140372644329280 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - ___check_obj_id(L['self'], 140369272172752)                 
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - ___check_obj_id(L['self'], 140369275927328)                 
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - ___check_obj_id(L['self'], 140369290455472)                 
V0529 16:36:59.476000 140372644329280 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                          
```

with inlining :
```
[lsakka@devvm4561.ash0 /data/users/lsakka/pytorch/pytorch (fix_op_count)]$ TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1 TORCH_LOGS="recompiles" python test/dynamo/tes
t_skip_non_tensor.py -k test_do_not_skip_side_effects
V0529 16:36:30.551000 139731447994176 torch/_dynamo/guards.py:2598] [1/1] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.551000 139731447994176 torch/_dynamo/guards.py:2598] [1/1] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.551000 139731447994176 torch/_dynamo/guards.py:2598] [1/1] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.561000 139731447994176 torch/_dynamo/guards.py:2598] [1/2] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.561000 139731447994176 torch/_dynamo/guards.py:2598] [1/2] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.561000 139731447994176 torch/_dynamo/guards.py:2598] [1/2] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.561000 139731447994176 torch/_dynamo/guards.py:2598] [1/2] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.572000 139731447994176 torch/_dynamo/guards.py:2598] [1/3] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.572000 139731447994176 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.572000 139731447994176 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.572000 139731447994176 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.572000 139731447994176 torch/_dynamo/guards.py:2598] [1/3] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.582000 139731447994176 torch/_dynamo/guards.py:2598] [1/4] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.582000 139731447994176 torch/_dynamo/guards.py:2598] [1/4] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.582000 139731447994176 torch/_dynamo/guards.py:2598] [1/4] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.582000 139731447994176 torch/_dynamo/guards.py:2598] [1/4] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.582000 139731447994176 torch/_dynamo/guards.py:2598] [1/4] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.582000 139731447994176 torch/_dynamo/guards.py:2598] [1/4] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.656000 139731447994176 torch/_dynamo/guards.py:2598] [1/5] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     - G['_variable'] == 1                                         
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     - L['self'].mode == 3                                           # _dynamo/output_graph.py:448 in init_ambient_guards
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.677000 139731447994176 torch/_dynamo/guards.py:2598] [1/6] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - L['self'].mode == 3                                           # _dynamo/output_graph.py:448 in init_ambient_guards
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.701000 139731447994176 torch/_dynamo/guards.py:2598] [1/7] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles] Recompiling function forward in /data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     triggered by the following guard failure(s):
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - L['self'].mode == 4                                           # _dynamo/output_graph.py:448 in init_ambient_guards
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - L['self'].mode == 3                                           # _dynamo/output_graph.py:448 in init_ambient_guards
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - L['self'].mode == 2                                         
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - G['_variable'] == 0                                         
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - L['self'].mode == 1                                         
V0529 16:36:30.730000 139731447994176 torch/_dynamo/guards.py:2598] [1/8] [__recompiles]     - G['_variable'] == 0                                         
W0529 16:36:30.730000 139731447994176 torch/_dynamo/convert_frame.py:752] [1/8] torch._dynamo hit config.cache_size_limit (8)
W0529 16:36:30.730000 139731447994176 torch/_dynamo/convert_frame.py:752] [1/8]    function: 'forward' (/data/users/lsakka/pytorch/pytorch/test/dynamo/test_skip_non_tensor.py:37)
W0529 16:36:30.730000 139731447994176 torch/_dynamo/convert_frame.py:752] [1/8]    last reason: G['_variable'] == 0                                         
W0529 16:36:30.730000 139731447994176 torch/_dynamo/convert_frame.py:752] [1/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0529 16:36:30.730000 139731447994176 torch/_dynamo/convert_frame.py:752] [1/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
```

**Comment by laithsakka** [comment]
the unit test code is :
```
        for mode in range(1, 6):
            _variable = 0
            _variable_2 = 0

            mod = MyModule(mode=mode)
            model = torch._dynamo.optimize(backend="eager", nopython=mode != 6)(mod)
            assert _variable == 0
            assert _variable_2 == 0

            model(torch.tensor([1]))
            assert _variable == 1
            assert _variable_2 == 0

            model(torch.tensor([1]))
            assert _variable == 2
            assert _variable_2 == 0
```

**Comment by laithsakka** [comment]
each loop iteration in the code above calls model twice, but since with inlining we actually guard on  - L['self'].mode == 1   which we did guard on without inlining, the second call compiles again, which sounds legitimate since we do need to guard on mode!

since the test is not really about the cache size I will just increase the limit for this test

**Comment by laithsakka** [comment]
here is what is interesting, i do understand why when nn module is enabled then each time we see the module we do recompile

but when inlining not enabled, what happen is that
(1) each time we create the module for the first time we do not consider that 
recompilation, but a new frame (function that we see for the first time) then next time we hit it its a recompilation. 
(2)for some reason iterations 5 and see we do not consider the second hit recompilations
