### ISSUE TITLE
RuntimeError: derivative for aten::_spdiags is not implemented

### ISSUE THREAD

**Issue by npistenon** [pytorch/pytorch#127541]
### 🚀 The feature, motivation and pitch

The backward for the torch.sparse.spdiags method does not seem to be implemented.
Do you have a fix that I can use in my networks?
Below is a typical sparse matrix that I am trying to use with the backward error. 

``
import torch
from torch import nn

class Test(nn.Module):
    def __init__(self) -> None:
        super(Test,self).__init__()

        self.x_E_i = nn.Parameter(torch.Tensor(1,))
        self.N_time = 10
        self.init_parameters()

    def init_parameters(self):
        x_E_i_ini = torch.rand(self.x_E_i.shape)

    def forward(self,x):
        """"x shape : (btc)"""
        diags = torch.exp(-x/self.x_E_i)
        D1 = torch.sparse.spdiags(diags,offsets=torch.tensor([0]),shape=(diags.shape[0],diags.shape[0]))
        return D1.to_dense()

if __name__ == "__main__":
    x = torch.rand((10),requires_grad=True)
    tt = Test()

    y = tt(x)
    print(y.shape)
    check = torch.autograd.gradcheck(tt,x.double())
    print(check)
`` 

``
torch.Size([10, 10])
Traceback (most recent call last):
  File "TestPytorch.py", line 27, in <module>
    check = torch.autograd.gradcheck(tt,x.double())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 2051, in gradcheck
    return _gradcheck_helper(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 2080, in _gradcheck_helper
    _gradcheck_real_imag(
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 1482, in _gradcheck_real_imag
    gradcheck_fn(
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 1617, in _slow_gradcheck
    analytical = _check_analytical_jacobian_attributes(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 768, in _check_analytical_jacobian_attributes
    vjps1 = _compute_analytical_jacobian_rows(vjp_fn, output.clone())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 884, in _compute_analytical_jacobian_rows
    grad_inputs = vjp_fn(grad_out_base)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/gradcheck.py", line 759, in vjp_fn
    return torch.autograd.grad(
           ^^^^^^^^^^^^^^^^^^^^
  File "anaconda3/envs/reinf/lib/python3.11/site-packages/torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: derivative for aten::_spdiags is not implemented
``

**Comment by lezcano** [comment]
cc @amjames

**Comment by amjames** [comment]
@npistenon I was working on backwards for `spdiags` (and the GPU kernels) a while ago ( #78965 ). I never got back to it, but I think it was mostly good to go, just missing some things to test it more thoroughly.

[Here](https://gist.github.com/amjames/9bab8c5581c5b551d23d356fe8daaa2e) is an implementation using a `torch.autograd.Function` which I had from when I was working on that PR. If I get some free time I might re-open that to try and land it.

**Comment by npistenon** [comment]
> @npistenon I was working on backwards for `spdiags` (and the GPU kernels) a while ago ( #78965 ). I never got back to it, but I think it was mostly good to go, just missing some things to test it more thoroughly.
> 
> [Here](https://gist.github.com/amjames/9bab8c5581c5b551d23d356fe8daaa2e) is an implementation using a `torch.autograd.Function` which I had from when I was working on that PR. If I get some free time I might re-open that to try and land it.

Thanks for sharing your class.
