### ISSUE TITLE
AOTAutograd: the partitioner should not move mutations from the backward into the forward.

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#127561]
After patching in https://github.com/pytorch/pytorch/pull/127551, and running this repro:
```
import torch
@torch.library.custom_op("mylib::clone", mutates_args={})
def f(x: torch.Tensor) -> torch.Tensor:
    return x.clone()
def f_fake(x):
    return torch.empty_like(x)
def backward(ctx, grad):
    with torch.no_grad():
        ctx.x.zero_()
        return grad
def setup_context(ctx, inputs, output):
    x, = inputs
    ctx.x = x
f.register_fake(f_fake)
f.register_autograd(backward, setup_context=setup_context)
x = torch.randn(3, requires_grad=True)
y = f(x)
y.sum().backward()
def fn(x: torch.Tensor) -> torch.Tensor:
    return torch.ops.mylib.clone(x)
print(x.grad)  # ones
print(x)  # zeros
torch.compile(fn, backend="aot_eager", fullgraph=True)(x)
```

We get these fw and bw graphs:
```
 ===== Forward graph 0 =====
 /home/hirsheybar/local/b/pytorch/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
    def forward(self, primals_1: "f32[3]"):
        # File: /home/hirsheybar/local/b/pytorch/tmp9.py:27 in fn, code: return torch.ops.mylib.clone(x)
        clone: "f32[3]" = torch.ops.mylib.clone.default(primals_1)
        zero: "f32[3]" = torch.ops.aten.zero.default(primals_1)

        # No stacktrace found for following nodes
        copy_: "f32[3]" = torch.ops.aten.copy_.default(primals_1, zero);  primals_1 = zero = None
        return [clone]


INFO: TRACED GRAPH
 ===== Backward graph 0 =====
 <eval_with_key>.1 class GraphModule(torch.nn.Module):
    def forward(self, tangents_1: "f32[3]"):
        return [tangents_1]
```

As @zou3519 pointed out, this is a problem: there was an input mutation in the user code that happened during the backward, but from the two graphs above, we've put the input mutation (the `copy_()` node) inside of the forward graph. This is a problem, since if the user uses the input after executing the forward but before running the backward, they will incorrectly see the mutated value.

The partitioner is in charge of deciding which graph each node should go in. Generally, nodes go in the backward graph if they depend on tangents (inputs to the bw), or if they involve compute on saved activations that were saved for backward.

We can tell from inside of AOTAutograd if our input mutation is supposed to happen the backward ([here](https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/traced_function_transforms.py#L432)), so we should require the partitioner to keep these special `copy_()` in the backward graph.

cc @ezyang @msaroufim @anijain2305 @chauhang @zou3519

**Comment by ezyang** [comment]
cc @Chillee

**Comment by StrongerXi** [comment]
Doing old issue scrubbing, on main d0f08dc3ebc the original repro fails with an error:

```
Traceback (most recent call last):
  File "/home/ryanguo99/scratch/repro.py", line 23, in <module>
    torch.compile(fn, backend="aot_eager", fullgraph=True)(x)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/eval_frame.py", line 589, in _fn
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/output_graph.py", line 1515, in _call_user_compiler
    raise BackendCompilerFailed(
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/output_graph.py", line 1490, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/repro/after_dynamo.py", line 150, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/repro/after_dynamo.py", line 150, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/__init__.py", line 2384, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/backends/debugging.py", line 182, in aot_eager
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/backends/common.py", line 101, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/aot_autograd.py", line 1170, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/aot_autograd.py", line 1143, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/aot_autograd.py", line 570, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/aot_autograd.py", line 820, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 398, in aot_dispatch_autograd
    fx_g, joint_inputs, maybe_subclass_meta = aot_dispatch_autograd_graph(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 318, in aot_dispatch_autograd_graph
    fx_g = _create_graph(joint_fn_to_trace, updated_joint_inputs, aot_config=aot_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 55, in _create_graph
    fx_g = make_fx(
           ^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/experimental/proxy_tensor.py", line 2194, in wrapped
    return make_fx_tracer.trace(f, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/experimental/proxy_tensor.py", line 2132, in trace
    return self._trace_inner(f, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/experimental/proxy_tensor.py", line 2103, in _trace_inner
    t = dispatch_trace(
        ^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/eval_frame.py", line 764, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/experimental/proxy_tensor.py", line 1136, in dispatch_trace
    graph = tracer.trace(root, concrete_args)  # type: ignore[arg-type]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/eval_frame.py", line 764, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/_symbolic_trace.py", line 836, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/_symbolic_trace.py", line 690, in flatten_fn
    tree_out = root_fn(*tree_args)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/fx/experimental/proxy_tensor.py", line 1191, in wrapped
    out = f(*tensors)  # type:ignore[call-arg]
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 717, in inner_fn
    outs = fn(*args)
           ^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 668, in joint_helper
    return _functionalized_f_helper(primals, tangents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 471, in _functionalized_f_helper
    before.copy_(after)
  File "/home/ryanguo99/repos/pytorch/torch/fx/experimental/proxy_tensor.py", line 1239, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='aot_eager' raised:
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

**Comment by StrongerXi** [comment]
@IvanKobzarev was #129130 supposed to fix this? And is the existing behavior above expected?

**Comment by IvanKobzarev** [comment]
Yes, this was fixed, closing.
