### ISSUE TITLE
TestNestedTensorSubclassCPU::test_chunk_cpu fails in debug mode

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#127546]
Some view issue?
```
============================= test session starts ==============================
platform linux -- Python 3.12.2, pytest-7.4.0, pluggy-1.0.0 -- /home/rzou/dev/opt-cuda3/env/bin/python
cachedir: .pytest_cache
rootdir: /home/rzou/dev/opt-cuda3/pt-opt-cuda3
configfile: pytest.ini
plugins: xdist-3.6.1
collecting ... collected 889 items / 887 deselected / 2 selected
Running 2 items in this shard
test/test_nestedtensor.py::TestNestedTensorSubclassCPU::test_chunk_cpu FAILED [0.1070s] [ 50%]
test/test_nestedtensor.py::TestNestedTensorSubclassCUDA::test_chunk_cuda FAILED [11.1668s] [100%]
=================================== FAILURES ===================================
__________________ TestNestedTensorSubclassCPU.test_chunk_cpu __________________
Traceback (most recent call last):
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_utils.py", line 2715, in wrapper
    method(*args, **kwargs)
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_device_type.py", line 432, in instantiated_test
    raise rte
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/test/test_nestedtensor.py", line 3340, in test_chunk
    chunks = nt.chunk(NUM_CHUNKS, dim=-1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/nested/_internal/nested_tensor.py", line 241, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: aliased_input.storage().is_alias_of(aliased_output.storage()) INTERNAL ASSERT FAILED at "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/csrc/autograd/autograd_not_implemented_fallback.cpp":422, please report a bug to PyTorch. aten::chunk
To execute this test, run the following from the base repo dir:
     python test/test_nestedtensor.py -k TestNestedTensorSubclassCPU.test_chunk_cpu
This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
_________________ TestNestedTensorSubclassCUDA.test_chunk_cuda _________________
Traceback (most recent call last):
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_utils.py", line 2715, in wrapper
    method(*args, **kwargs)
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_utils.py", line 2715, in wrapper
    method(*args, **kwargs)
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_device_type.py", line 432, in instantiated_test
    raise rte
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/test/test_nestedtensor.py", line 3340, in test_chunk
    chunks = nt.chunk(NUM_CHUNKS, dim=-1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/nested/_internal/nested_tensor.py", line 241, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: aliased_input.storage().is_alias_of(aliased_output.storage()) INTERNAL ASSERT FAILED at "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/csrc/autograd/autograd_not_implemented_fallback.cpp":422, please report a bug to PyTorch. aten::chunk
To execute this test, run the following from the base repo dir:
     python test/test_nestedtensor.py -k TestNestedTensorSubclassCUDA.test_chunk_cuda
This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
=========================== short test summary info ============================
FAILED [0.1070s] test/test_nestedtensor.py::TestNestedTensorSubclassCPU::test_chunk_cpu
FAILED [11.1668s] test/test_nestedtensor.py::TestNestedTensorSubclassCUDA::test_chunk_cuda
====================== 2 failed, 887 deselected in 21.06s ======================
```

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer

**Comment by soulitzer** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/125503
