### ISSUE TITLE
Installation not possible on Ubuntu 18.04

### ISSUE THREAD

**Issue by ZeJackOfSpades** [pytorch/pytorch#12758]
## To Reproduce

1.run the command `conda install -c pytorch pytorch-cpu`

conda install pytorch-cpu torchvision-cpu -c pytorch
Solving environment: done

## Package Plan ##

  environment location: /home/user/anaconda3

  added / updated specs: 
    - pytorch-cpu
    - torchvision-cpu

The following NEW packages will be INSTALLED:

    ninja:           1.8.2-py37h6bb024c_1        
    pytorch-cpu:     0.4.1-py37_cpu_1     pytorch
    torchvision-cpu: 0.2.1-py37_1         pytorch

Proceed ([y]/n)? y

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 282, in handle_txn
        unlink_link_transaction.execute()
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 223, in execute
        self.verify()
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
        return f(*args, **kwds)
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 200, in verify
        self.prepare()
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 192, in prepare
        stp.remove_specs, stp.update_specs)
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 282, in _prepare
        mkdir_p(transaction_context['temp_dir'])
      File "/home/user/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
        makedirs(path)
      File "/home/user/anaconda3/lib/python3.7/os.py", line 221, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/home/user/anaconda3/.condatmp'

`$ /home/user/anaconda3/bin/conda install pytorch-cpu torchvision-cpu -c pytorch`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/user/anaconda3/bin/conda
             CONDA_PREFIX=/home/user/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/user/anaconda3/bin/python
               CONDA_ROOT=/home/user/anaconda3
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/user/anaconda3/bin:/home/user/.local/bin:/usr/local/sbin:/usr/lo
                          cal/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sna
                          p/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
     TERMINATOR_DBUS_PATH=/net/tenshu/Terminator2
               WINDOWPATH=2

     active environment : base
    active env location : /home/user/anaconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/user/anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/.conda/envs
                          /home/user/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (Ubuntu 18.04):
 - How you installed PyTorch (`conda`):
 - Build command you used (if compiling from source):
 - Python version: 3.7.0
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zou3519** [comment]
Do you have a user named anaconda3? This seems like a permissions error on your machine.

**Comment by JisongXie** [comment]
I meet the same problem as you today. It is the problem of access. Finally I change the permission of the documents, and install the package, then modify it back.
For example, I see your install path may be "/home/user/anaconda3", so it might be helpful for you like this：
`sudo chmod -R o+w /home/user/anaconda3`
Then you can install the package successfully. And after finishing installation, I modify it back, like this:
`sudo chmod -R o-w /home/user/anaconda3` 
I don't know if this way is good, but it works for me.
