### ISSUE TITLE
The data was supposed to be on the GPU, but was mistakenly placed on the CPU.

### ISSUE THREAD

**Issue by balabooooo** [pytorch/pytorch#127603]
### 🐛 Describe the bug

During training, I keep encountering errors with data on both the CPU and GPU.
This doesn't seem to be an issue with my code, as I've never encountered this problem on another computer with nearly the same configuration.

Here are the specifications of the server where I encountered the problem:
Ubuntu 20.04.6 LTS
GPU 2x4090
pytorch 1.8.1+cu111
GPU Driver Version: 535.113.01

The error issues I've encountered (using the same code) are numerous and include, but are not limited to:

This is the most frequently encountered issue.
```
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 350, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.dataset_file, args.clip_max_norm, writer, args.print_freq,)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/engine.py", line 48, in train_one_epoch_mot
    outputs = model(data_dict)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/motr.py", line 740, in forward
    frame_res = self._forward_single_image(frame, track_instances, num_proposals, gtboxes)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/motr.py", line 555, in _forward_single_image
    self.transformer(srcs, masks, pos, num_proposals, query_embed, ref_pts=ref_pts, attn_mask=attn_mask)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/deformable_transformer_plus.py", line 186, in forward
    num_proposals, mask_flatten,mem_bank, mem_bank_pad_mask, attn_mask)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/deformable_transformer_plus.py", line 445, in forward
    num_proposals, src_level_start_index, src_padding_mask, mem_bank, mem_bank_pad_mask, attn_mask)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/deformable_transformer_plus.py", line 400, in forward
    level_start_index, num_proposals, src_padding_mask, attn_mask)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/deformable_transformer_plus.py", line 390, in _forward_cross_self
    pp_weights_cos, pp_weights_mm = self._forward_weight_attn(proposals, p_query_pos, proposals, p_query_pos)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/deformable_transformer_plus.py", line 357, in _forward_weight_attn
    weight_cos, weight_mm = self.weight_attn(q, k)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run5/models/attention.py", line 41, in forward
    weight_cos = F.cosine_similarity(k.unsqueeze(2), q.unsqueeze(3), dim=-1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu:0 and cuda:0!
```

```
Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 350, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.dataset_file, args.clip_max_norm, writer, args.print_freq,)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run4/engine.py", line 71, in train_one_epoch_mot
    losses.backward()
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: d.type() == DeviceType::CUDA INTERNAL ASSERT FAILED at "/pytorch/c10/cuda/impl/CUDAGuardImpl.h":28, please report a bug to PyTorch. 
```

```
Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 350, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.dataset_file, args.clip_max_norm, writer, args.print_freq,)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run3/engine.py", line 71, in train_one_epoch_mot
    losses.backward()
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu:0 and cuda:0!
```

```
Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 350, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.dataset_file, args.clip_max_norm, writer, args.print_freq,)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run2/engine.py", line 48, in train_one_epoch_mot
    outputs = model(data_dict)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run2/models/motr.py", line 740, in forward
    frame_res = self._forward_single_image(frame, track_instances, num_proposals, gtboxes)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run2/models/motr.py", line 515, in _forward_single_image
    features, pos = self.backbone(samples)  # extract features and create position embeddings
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run2/models/backbone.py", line 119, in forward
    xs = self[0](tensor_list)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run2/models/backbone.py", line 86, in forward
    xs = self.body(tensor_list.tensors)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torchvision/models/_utils.py", line 63, in forward
    x = module(x)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torchvision/models/resnet.py", line 129, in forward
    out = self.bn2(out)
  File "/home/fzm_2022/miniconda3/envs/motrv2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fzm_2022/projects/track_anything/my_code/2024_3_7/exps/mot17/run2/models/backbone.py", line 63, in forward
    bias = b - rm * scale
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu:0 and cuda:0!
```

Can anyone help me with this?
Thank u in advance.

### Versions

PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.16 (default, Jan 17 2023, 22:20:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-182-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090

Nvidia driver version: 535.113.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      39 bits physical, 48 bits virtual
CPU(s):                             32
On-line CPU(s) list:                0-31
Thread(s) per core:                 1
Core(s) per socket:                 24
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              183
Model name:                         13th Gen Intel(R) Core(TM) i9-13900KF
Stepping:                           1
CPU MHz:                            5360.972
CPU max MHz:                        7400.0000
CPU min MHz:                        800.0000
BogoMIPS:                           5990.40
Virtualization:                     VT-x
L1d cache:                          576 KiB
L1i cache:                          384 KiB
L2 cache:                           24 MiB
NUMA node0 CPU(s):                  0-31
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.8.1+cu111
[pip3] torchvision==0.9.1+cu111
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.8.1+cu111              pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi

**Comment by sanchitintel** [comment]
Can you please try using PyTorch 2.3?

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

PyTorch never moves code between devices automatically, so your code has to be doing something it shouldn't.
I would share a working code sample there so that people can more effectively help you figure out what is wrong with your code.
