### ISSUE TITLE
"unhashable type: non-nested SymInt" error when using DTensor and Compiled Autograd together

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#127797]
### 🐛 Describe the bug

Repro:

If I make the following change to enable Compiled Autograd for compile+DTensor E2E test `test_tp_compile_fullgraph`:

```
diff --git a/test/distributed/_tensor/test_dtensor_compile.py b/test/distributed/_tensor/test_dtensor_compile.py
index 325d18be79f..f142314c660 100644
--- a/test/distributed/_tensor/test_dtensor_compile.py
+++ b/test/distributed/_tensor/test_dtensor_compile.py
@@ -661,9 +661,13 @@ class TestDTensorCompileE2E(DTensorTestBase):
         inp = torch.rand(20, 10, device=self.device_type)
         out = model(inp)
         cnt = torch._dynamo.testing.CompileCounterWithBackend("aot_eager")
-        compiled_mod = torch.compile(model, backend=cnt, fullgraph=True)
-        compiled_out = compiled_mod(inp)
-        compiled_out.sum().backward()
+        compiled_mod = torch.compile(model, backend="aot_eager", fullgraph=True)
+        def compiler_fn(gm):
+            return torch.compile(gm, backend="aot_eager", fullgraph=True)
+        ctx = torch._dynamo.compiled_autograd.enable(compiler_fn)
+        with ctx:
+            compiled_out = compiled_mod(inp)
+            compiled_out.sum().backward()
         self.assertEqual(compiled_out, out)
         self.assertEqual(cnt.frame_count, 1)
```
and run `pytest -rA test/distributed/_tensor/test_dtensor_compile.py::TestDTensorCompileE2E::test_tp_compile_fullgraph_is_seq_parallel_False`, I get this error:
```
Traceback (most recent call last):
  File "/data/users/willfeng/pytorch/torch/testing/_internal/common_distributed.py", line 653, in run_test
    getattr(self, test_name)()
  File "/data/users/willfeng/pytorch/torch/testing/_internal/common_distributed.py", line 539, in wrapper
    fn()
  File "/data/users/willfeng/pytorch/torch/testing/_internal/common_utils.py", line 2715, in wrapper
    method(*args, **kwargs)
  File "/data/users/willfeng/pytorch/torch/testing/_internal/common_utils.py", line 446, in instantiated_test
    test(self, **param_kwargs)
  File "/data/users/willfeng/pytorch/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 369, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/test/distributed/_tensor/test_dtensor_compile.py", line 670, in test_tp_compile_fullgraph
    compiled_out.sum().backward()
  File "/data/users/willfeng/pytorch/torch/_tensor.py", line 520, in backward
    torch.autograd.backward(
  File "/data/users/willfeng/pytorch/torch/autograd/__init__.py", line 284, in backward
    _engine_run_backward(
  File "/data/users/willfeng/pytorch/torch/autograd/graph.py", line 767, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/_dynamo/compiled_autograd.py", line 88, in begin_capture
    self.bind_tensors_to_proxies(inputs, proxies)
  File "/data/users/willfeng/pytorch/torch/_dynamo/compiled_autograd.py", line 258, in bind_tensors_to_proxies
    track_tensor_tree(tensors, proxies, constant=None, tracer=self.fx_tracer)
  File "/data/users/willfeng/pytorch/torch/fx/experimental/proxy_tensor.py", line 267, in track_tensor_tree
    wrap_with_proxy(inner_res, proxy_res, constant)
  File "/data/users/willfeng/pytorch/torch/fx/experimental/proxy_tensor.py", line 238, in wrap_with_proxy
    wrap_with_proxy(ee, proxy[idx], get_constant(idx))
  File "/data/users/willfeng/pytorch/torch/fx/experimental/proxy_tensor.py", line 224, in wrap_with_proxy
    set_meta(proxy, e)
  File "/data/users/willfeng/pytorch/torch/fx/experimental/proxy_tensor.py", line 178, in set_meta
    proxy.node.meta['val'] = extract_val(val)
                             ^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/fx/experimental/proxy_tensor.py", line 146, in extract_val
    return snapshot_fake(val)
           ^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/fx/experimental/proxy_tensor.py", line 142, in snapshot_fake
    return val.detach()
           ^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/_compile.py", line 30, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/_dynamo/eval_frame.py", line 574, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/api.py", line 296, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/_dispatch.py", line 117, in dispatch
    self.sharding_propagator.propagate(op_info)
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/_sharding_prop.py", line 182, in propagate
    output_sharding = self.propagate_op_sharding_non_cached(op_info.schema)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/_sharding_prop.py", line 196, in propagate_op_sharding_non_cached
    out_tensor_meta = self._propagate_tensor_meta(op_schema)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/_op_schema.py", line 333, in __hash__
    return hash((self.op, args_to_hash))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/placement_types.py", line 527, in __hash__
    self._hash = self._hash_impl()
                 ^^^^^^^^^^^^^^^^^
  File "/data/users/willfeng/pytorch/torch/distributed/_tensor/placement_types.py", line 510, in _hash_impl
    return hash(
           ^^^^^
  File "/data/users/willfeng/pytorch/torch/__init__.py", line 356, in __hash__
    raise TypeError("unhashable type: non-nested SymInt")
TypeError: unhashable type: non-nested SymInt
```

Not sure whether we must have this SymInt, or if we need a way to hash this SymInt.

### Versions

nightly

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @kwen2501 @chauhang @ezyang @anijain2305 @penguinwu @wanchaol @XilunWu @d4l3k @msaroufim @bdhirsh @tianyu-l

**Comment by xmfan** [comment]
single gpu repro:

[ca_inputs.txt](https://github.com/user-attachments/files/15540462/ca_inputs.txt) (actually ca_inputs.pickle)

```python
import torch
from torch._dynamo.source import GetItemSource, LocalSource
from torch._subclasses import FakeTensorMode
from torch.fx.experimental.proxy_tensor import (
    PythonKeyTracer,
    track_tensor_tree,
)
from torch.fx.experimental.symbolic_shapes import ShapeEnv
import pickle
class Foo:
    def wrap_fake(self, x, source):
        assert isinstance(x, torch.Tensor)
        return self.fake_tensor_mode.from_tensor(x, source=source)
    @staticmethod
    def source(name, idx) -> GetItemSource:
        return GetItemSource(LocalSource(name), idx)
    def bind_tensors_to_proxies(self, tensors, proxies):
        if isinstance(proxies, torch.fx.Proxy):
            proxies = [proxies[i] for i in range(len(tensors))]
        assert len(tensors) == len(proxies)
        track_tensor_tree(tensors, proxies, constant=None, tracer=self.fx_tracer)
    def __init__(self):
        self.shape_env = ShapeEnv()
        self.fake_tensor_mode = FakeTensorMode(
            allow_fallback_kernels=True,
            allow_non_fake_inputs=True,
            shape_env=self.shape_env,
        )
        self.fx_tracer = PythonKeyTracer()
        self.fx_tracer.root = torch.nn.Module()
        self.fx_tracer.graph = torch.fx.Graph(tracer_cls=PythonKeyTracer)
        self.fx_tracer.tensor_attrs = {}
        args_proxy = self.fx_tracer.create_proxy("placeholder", "inputs", (), {})
        with open('ca_inputs.pickle', 'rb') as f:
            inputs = pickle.load(f)
        inputs = [
            self.wrap_fake(x, self.source("inputs", idx))
            for idx, x in enumerate(inputs)
        ]

        proxies = [args_proxy[i] for i in range(len(inputs))]
        self.bind_tensors_to_proxies(inputs, proxies)
Foo()
```

**Comment by bdhirsh** [comment]
Two distinct issues:

(1) DTensor + torch.compile is still not happy with dynamic shapes. I believe https://github.com/pytorch/pytorch/pull/123349 fixes the issue above, although the PR is a bit stalled (DTensor has a bunch of caches, that we need to turn off if there any any SymInt inputs to the cache. Ideally, we should have a version of lru_cache that says "always cache-miss when we see a SymInt", and use that in DTensor instead). cc @wanchaol, @LucasLLC.

(2) When compiled autograd is enabled, dynamic shapes are showing up during tracing, even though the test itself has no dynamism.

It looks like:

(2a) normally, when we fakeify tensors in dynamo we pass a symbolic context (which assumes static-shapes-by-default), that tells our fakeify logic to produce FakeTensors with static shapes ([code](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/builder.py#L2279))

(2b) compiled autograd does not pass in a symbolic context ([code](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/compiled_autograd.py#L67))

(2c) the default behavior when we have no symbolic context is to do duck-sizing, which will create SymInts ([code)](https://github.com/pytorch/pytorch/blob/main/torch/fx/experimental/symbolic_shapes.py#L3130)

After talking to @xmfan - it sounds liked compiled autograd already figures out which of its inputs are dynamic/static (which it needs to cache properly) - so we can use this info to construct a proper `SymbolicContext` to feed to `FakeTensorMode.from_tensor`.

**Comment by yf225** [comment]
This might be a similar issue:

`pytest -rA test/distributed/_composable/test_replicate_with_compiler.py::DDP_TP_Test::test_ddp_tp`

Error:
```
  File "/data/users/willfeng/pytorch_top/torch/_dynamo/variables/base.py", line 210, in as_python_constant
    raise NotImplementedError(f"{self} is not a constant")
torch._dynamo.exc.InternalTorchDynamoError: SymNodeVariable() is not a constant

from user code:
   File "/data/users/willfeng/pytorch_top/torch/distributed/tensor/parallel/_data_parallel_utils.py", line 34, in _unflatten_tensor
    result = DTensor.from_local(
```

Full error log: https://gist.github.com/yf225/c3827ecdb2915c19f14ffa5be2ca9761

**Comment by ezyang** [comment]
That is kind of different. You need to decide if the prim supports dynamic shapes, and if it does, you need to feed these as real arguments, not fake arguments that you've closed over. cc @wanchaol

**Comment by bdhirsh** [comment]
> That is kind of different. You need to decide if the prim supports dynamic shapes, and if it does, you need to feed these as real arguments, not fake arguments that you've closed over.

@ezyang i don't follow - what does prim refer to here, and what are the "fake arguments that you've closed over"? (from my previous looking at this issue, I found the error coming from (1) compiled autograd was generating symints even though there was no dynamism in the graph, and (2) DTensor is not fully equipped to handle symints today)

**Comment by yf225** [comment]
@bdhirsh I am not 100% sure but Ed might be responding to this issue https://github.com/pytorch/pytorch/issues/130978 that I also posted here at one point (but since deleted because I feel that it might be a different issue)

**Comment by bdhirsh** [comment]
I think the plan-on-record here is still to get compiled autograd to pass a symbolic context into fakeification, so we properly generated static shapes in the backward instead of duck sizing if there is no dynamism? (someone can correct me if I'm wrong)

**Comment by bdhirsh** [comment]
Related: https://github.com/pytorch/pytorch/issues/133575

**Comment by bdhirsh** [comment]
With the dynamic shape / `accumulate_grad_/DTensor` changes in this stack https://github.com/pytorch/pytorch/pull/133581, I get further but now error in compiled autograd with this:
```
  File "/home/hirsheybar/local/b/pytorch/torch/_dynamo/variables/base.py", line 327, in call_method
    unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/home/hirsheybar/local/b/pytorch/torch/_dynamo/exc.py", line 289, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: call_method GetAttrVariable(TensorVariable(), grad) add_ [TensorVariable()] {}
```

it looks like we are incorrectly generating the proxy for the accumulate grad input while compiled autograd is running dynamo for some reason

**Comment by bdhirsh** [comment]
aha. Current theory:

(1) the parameter in question that we are doing accumulate_grad on here is a `DTensor`

(2) compiled autograd will see it (and its grad field) and mark them as graph inputs in the compiled autograd graph)

(3) compiled autograd uses default "proxy mode" tracing, here: https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/compiled_autograd.py#L73.

(4) default tracing is actually wrong here: compiled autograd explicitly wants to trace a "pre-subclass-desugaring graph", so it can let AOTDispatch do the subclass desugaring later. `ProxyTorchDispatchMode`, however, will by-default trace through `__torch_dispatch__`

I'm currently trying to force compiled autograd to use pre-dispatch tracing. This will also have the nice effect of (eventually) allowing us to better handle double-backwrd in compiled autograd ([see here](https://github.com/pytorch/pytorch/issues/91469)). Although I'm running into some issues...

**Comment by bdhirsh** [comment]
Hmm, `pre-dispatch` tracing alone isn't actually enough, because the `bw_module` that we end up tracing through in compiled autograd has **already** been desugared below pre-dispatch/subclasses.

So once we also trace the backward in pre-dispatch as part of https://github.com/pytorch/pytorch/issues/91469 then it should be enough. But until then, we're also going to need compiled autograd to trace through the "runtime wrap/unwrap subclasses" logic in the backward, so the inputs/outputs to the `CompiledFunctionBackward` node that compiled autograd sees are proper subclasses.

I guess alternatively, we could have compiled autograd just not operate pre-dispatch. That would require it to manually desugar all tensor subclasses inputs before dynamo though, and we would probably end up undoing all of that once we have pre-dispatch backward tracing in AOTDispatcher.

**Comment by StrongerXi** [comment]
@bdhirsh @xmfan should we keep this open?

**Comment by bdhirsh** [comment]
We can either keep this issue open, or file a new one to represent the latest DTensor + compiled autograd error that you repro'd.

@zou3519 / @xmfan 's compiled autograd changes fixed most problems between tensor subclasses and compiled autograd, but Richard pointed out that some DTensor-specific problems still remain (the one I remember is that some of the custom autograd.Functions that DTensor uses are not trace-friendly today, although this AccumulateGrad error looks like a different problem)

**Comment by xmfan** [comment]
https://github.com/pytorch/pytorch/pull/149014 should have fixed Ryan's latest error. I'll look into enabling the tests and close this issue
