### ISSUE TITLE
DISABLED test_cpp_extension_recommends_custom_ops (__main__.MiscTests)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#127848]
Platforms: mac, macos

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22FAILED%22%2C%22dynamo%2Ftest_misc.py%3A%3AMiscTests%3A%3Atest_cpp_extension_recommends_custom_ops%22%5D)).

This test starts to become flaky in trunk, maybe after the migration to MacOS 14 https://github.com/pytorch/pytorch/issues/127490.

cc @malfet @albanD @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by soulitzer** [comment]
@zou3519 Looks like this test was added in https://github.com/pytorch/pytorch/pull/127301

Error message:
```
2024-06-05T02:47:47.6591177Z =================================== FAILURES ===================================
2024-06-05T02:47:47.6591987Z ______________ MiscTests.test_cpp_extension_recommends_custom_ops ______________
2024-06-05T02:47:47.6592752Z Traceback (most recent call last):
2024-06-05T02:47:47.6593986Z   File "/var/lib/jenkins/workspace/test/dynamo/test_misc.py", line 251, in test_cpp_extension_recommends_custom_ops
2024-06-05T02:47:47.6595035Z     f(x)
2024-06-05T02:47:47.6595970Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 421, in _fn
2024-06-05T02:47:47.6596955Z     return fn(*args, **kwargs)
2024-06-05T02:47:47.6598128Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1078, in catch_errors
2024-06-05T02:47:47.6599378Z     return callback(frame, cache_entry, hooks, frame_state, skip=1)
2024-06-05T02:47:47.6600753Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 919, in _convert_frame
2024-06-05T02:47:47.6601814Z     result = inner_convert(
2024-06-05T02:47:47.6603013Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 456, in _convert_frame_assert
2024-06-05T02:47:47.6604142Z     return _compile(
2024-06-05T02:47:47.6605202Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_utils_internal.py", line 83, in wrapper_function
2024-06-05T02:47:47.6606423Z     return StrobelightCompileTimeProfiler.profile_compile_time(
2024-06-05T02:47:47.6607962Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
2024-06-05T02:47:47.6609170Z     return func(*args, **kwargs)
2024-06-05T02:47:47.6609907Z   File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
2024-06-05T02:47:47.6610706Z     return func(*args, **kwds)
2024-06-05T02:47:47.6611805Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 828, in _compile
2024-06-05T02:47:47.6612950Z     raise InternalTorchDynamoError(str(e)).with_traceback(
2024-06-05T02:47:47.6614215Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 799, in _compile
2024-06-05T02:47:47.6615435Z     guarded_code = compile_inner(code, one_graph, hooks, transform)
2024-06-05T02:47:47.6616727Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 232, in time_wrapper
2024-06-05T02:47:47.6617721Z     r = func(*args, **kwargs)
2024-06-05T02:47:47.6618852Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 618, in compile_inner
2024-06-05T02:47:47.6620003Z     out_code = transform_code_object(code, transform)
2024-06-05T02:47:47.6621405Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1184, in transform_code_object
2024-06-05T02:47:47.6622932Z     transformations(instructions, code_options)
2024-06-05T02:47:47.6624110Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 177, in _fn
2024-06-05T02:47:47.6625092Z     return fn(*args, **kwargs)
2024-06-05T02:47:47.6626369Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 564, in transform
2024-06-05T02:47:47.6627379Z     tracer.run()
2024-06-05T02:47:47.6628381Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2450, in run
2024-06-05T02:47:47.6629361Z     super().run()
2024-06-05T02:47:47.6630351Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 892, in run
2024-06-05T02:47:47.6631351Z     while self.step():
2024-06-05T02:47:47.6632371Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 804, in step
2024-06-05T02:47:47.6633453Z     self.dispatch_table[inst.opcode](self, inst)
2024-06-05T02:47:47.6634686Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1560, in LOAD_ATTR
2024-06-05T02:47:47.6635716Z     self._load_attr(inst)
2024-06-05T02:47:47.6636940Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1550, in _load_attr
2024-06-05T02:47:47.6638135Z     result = BuiltinVariable(getattr).call_function(
2024-06-05T02:47:47.6639444Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 962, in call_function
2024-06-05T02:47:47.6640541Z     return handler(tx, args, kwargs)
2024-06-05T02:47:47.6641722Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 711, in <lambda>
2024-06-05T02:47:47.6642883Z     return lambda tx, args, kwargs: obj.call_function(
2024-06-05T02:47:47.6644177Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 962, in call_function
2024-06-05T02:47:47.6645288Z     return handler(tx, args, kwargs)
2024-06-05T02:47:47.6646525Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 846, in builtin_dipatch
2024-06-05T02:47:47.6647637Z     rv = fn(tx, args, kwargs)
2024-06-05T02:47:47.6648838Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 764, in call_self_handler
2024-06-05T02:47:47.6650017Z     result = self_handler(tx, *args, **kwargs)
2024-06-05T02:47:47.6651275Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 1611, in call_getattr
2024-06-05T02:47:47.6652362Z     member = getattr(obj.value, name)
2024-06-05T02:47:47.6653292Z torch._dynamo.exc.InternalTorchDynamoError: module 'mylib' has no attribute 'foobar'
2024-06-05T02:47:47.6653989Z 
2024-06-05T02:47:47.6654152Z from user code:
2024-06-05T02:47:47.6654801Z    File "/var/lib/jenkins/workspace/test/dynamo/test_misc.py", line 246, in f
2024-06-05T02:47:47.6655600Z     return module.foobar(x)
2024-06-05T02:47:47.6655899Z 
2024-06-05T02:47:47.6656292Z Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
2024-06-05T02:47:47.6656872Z 
2024-06-05T02:47:47.6656902Z 
2024-06-05T02:47:47.6657279Z You can suppress this exception and fall back to eager by setting:
2024-06-05T02:47:47.6657974Z     import torch._dynamo
2024-06-05T02:47:47.6658480Z     torch._dynamo.config.suppress_errors = True
2024-06-05T02:47:47.6658901Z 
2024-06-05T02:47:47.6658920Z 
2024-06-05T02:47:47.6659260Z To execute this test, run the following from the base repo dir:
2024-06-05T02:47:47.6660343Z      python test/dynamo/test_misc.py -k MiscTests.test_cpp_extension_recommends_custom_ops
```
