### ISSUE TITLE
[inductor] error in graph lowering and graph breaks

### ISSUE THREAD

**Issue by FindHao** [pytorch/pytorch#128095]
### 🐛 Describe the bug

Huggingface model: https://huggingface.co/CohereForAI/aya-23-8B
Reference code: https://huggingface.co/CohereForAI/aya-23-8B/blob/main/Aya_23_notebook.ipynb

## Error
```bash
  File "/home/yhao/p9/pytorch/torch/_inductor/lowering.py", line 2639, in inner
    return _full(fill_value, device, dtype, size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yhao/p9/pytorch/torch/_inductor/lowering.py", line 2597, in _full
    assert len(value.get_size()) == 0
               ^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AttributeError: 'GreaterThan' object has no attribute 'get_size'
  target: aten.full.default
  args[0]: [1]
  args[1]: s0 >= 1043
  kwargs: {'dtype': torch.bool, 'device': device(type='cuda', index=0), 'pin_memory': False}
```

## Graph breaks

There are two types of graph breaks. 
1.  UserWarning: Graph break due to unsupported builtin flash_attn_2_cuda.PyCapsule.fwd. 
2. Skipping frame because there is a graph break in a for/while loop

## To Reproduce

https://github.com/FindHao/ml_scripts/blob/main/inductor/cases/aya_full.py

You may need to add the following code and your own token for the first run to download weights etc.
```python
from huggingface_hub import login
login(token='your_hf_token')
```

### Versions

nightly

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by FindHao** [comment]
The bug is duplicated with #128161

**Comment by FindHao** [comment]
I'd like to reopen it because the graph breaks are still the issues.

**Comment by williamwen42** [comment]
Current graph breaks:

1.
```
NotImplementedError: UnspecializedNNModuleVariable(CohereForCausalLM) is not a constant
```
caused by 
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/transformers/generation/utils.py", line 1207, in _validate_model_kwargs
  model_args |= set(inspect.signature(self.forward).parameters)
```
(`self.forward` cannot be converted to a Python constant since it is a `functools.partial` object with a unspecialized nn.module argument)

2.
```
torch._dynamo.exc.Unsupported: 'inline in skipfiles: Signature.parameters | parameters /data/users/williamwen/py312-env/lib/python3.12/inspect.py, skipped according trace_rules.lookup SKIP_DIRS'
```
caused by
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/transformers/generation/utils.py", line 1207, in _validate_model_kwargs
  model_args |= set(inspect.signature(self.forward).parameters)
```
(previous graph break results in calling a user-defined method in a skipped file)

3.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/transformers/cache_utils.py", line 321, in __init__
  super().__init__()
```
caused by
```
torch._dynamo.exc.Unsupported: uninitialized nn.Module: DynamicCache
```

4.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/accelerate/utils/operations.py", line 156, in send_to_device
  return tensor.to(device, non_blocking=non_blocking)
File "/data/users/williamwen/pytorch/torch/nn/modules/module.py", line 1299, in to
  device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(
```
caused by
```
torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor device call_function <built-in function getitem>
```

5. 
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/transformers/models/cohere/modeling_cohere.py", line 920, in _update_causal_mask
  if attention_mask is not None and 0.0 in attention_mask:
```
caused by
```
torch._dynamo.exc.Unsupported: Tensor.item
```

6.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/bitsandbytes/nn/modules.py", line 477, in forward
  out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
```
caused by
```
torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(Params4bit) t [] {}
```

7.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/bitsandbytes/nn/modules.py", line 477, in torch_dynamo_resume_in_forward_at_477
  out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
...
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/bitsandbytes/functional.py", line 462, in pre_call
  prev_device = torch.cuda.current_device()
```
caused by
```
torch._dynamo.exc.Unsupported: 'skip function current_device in file /data/users/williamwen/pytorch/torch/cuda/__init__.py'
```

8.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/bitsandbytes/functional.py", line 463, in torch_dynamo_resume_in_pre_call_at_462
  torch.cuda.set_device(device)
```
caused by
```
torch._dynamo.exc.Unsupported: 'skip function set_device in file /data/users/williamwen/pytorch/torch/cuda/__init__.py'
```

9.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/bitsandbytes/functional.py", line 977, in torch_dynamo_resume_in_dequantize_blockwise_at_969
  lib.cdequantize_blockwise_fp32(
...
File "/data/users/williamwen/pytorch/torch/_dynamo/polyfills/__init__.py", line 144, in instantiate_user_defined_class_object
  obj = cls.__new__(cls, *args, **kwargs)
```
caused by
```
torch._dynamo.exc.Unsupported: Graph break due to unsupported builtin None.CFuncPtr.__new__...
```

10.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/bitsandbytes/functional.py", line 458, in get_ptr
  return ct.c_void_p(A.data.data_ptr())
```
caused by
```
torch._dynamo.exc.Unsupported: Tensor.data_ptr
```

11.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/transformers/models/cohere/modeling_cohere.py", line 447, in torch_dynamo_resume_in_forward_at_392
  attn_output = _flash_attention_forward(
...
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 43, in _is_package_available
  package_exists = importlib.util.find_spec(pkg_name) is not None
```
caused by
```
torch._dynamo.exc.Unsupported: 'skip function find_spec in file <frozen importlib.util>'
```

12.
```
File "/data/users/williamwen/py312-env/lib/python3.12/site-packages/flash_attn/flash_attn_interface.py", line 52, in _flash_attn_forward
  out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
```
caused by
```
torch._dynamo.exc.Unsupported: Graph break due to unsupported builtin flash_attn_2_cuda.PyCapsule.fwd...
```

**Comment by williamwen42** [comment]
Current status: fixed a crash, but perf is still bad - will need to investigate which graph breaks/recompiles are contributing to bad perf.

**Comment by umarbutler** [comment]
I'm getting this on PyTorch 2.4.1 while trying to train a model using flash attention 2.6.3 for self-attention and torch compile.

**Comment by anijain2305** [comment]
```
torch._dynamo.exc.Unsupported: Graph break due to unsupported builtin flash_attn_2_cuda.PyCapsule.fwd...
```

This should be fixed on flash_attention main repo, where the ops have been made pt2 compatible.

**Comment by umarbutler** [comment]
@anijain2305 I just built the flash-attention main branch from source and sadly I'm getting the same error message during training with the Hugging Face Trainer with `torch_compile=True`:
```
.venv/lib/python3.12/site-packages/torch/_dynamo/variables/functions.py:663: UserWarning: Graph break due to unsupported builtin flash_attn_2_cuda.PyCapsule.fwd. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
```

See also https://github.com/Dao-AILab/flash-attention/pull/1139

**Comment by umarbutler** [comment]
It looks like I somehow ran `python setup.py bdist_wheel` and forgot I was creating a wheel (which I also ended up mistakenly deleting moments ago) 😅 hopefully second time's the charm

**Comment by umarbutler** [comment]
I can confirm that it works!

**Comment by ArthurZucker** [comment]
cc @gante as well, something we need to check in generate

**Comment by StrongerXi** [comment]
Doing old issue scrubbing, on d0f08dc3ebc, full log at P1739636194.

4 out of 12 graph breaks remain from @williamwen42's notes above: (4), (5), (6), (11).

Then I also saw 4 new graph breaks:

1. 
```
[40/0] [__graph_breaks] Graph break in user code at /home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py:201
[40/0] [__graph_breaks] Graph Break Reason: Attempted to inline function marked as skipped
[40/0] [__graph_breaks]   Explanation: Dynamo developers have intentionally marked that the function `device_of.__init__` should not be traced.
[40/0] [__graph_breaks]   Hint: Avoid calling the function `device_of.__init__`.
[40/0] [__graph_breaks]   Hint: Remove the function `device_of.__init__` or the file `/home/ryanguo99/repos/pytorch/torch/cuda/__init__.py` from torch/_dynamo/trace_rules.py. More graph breaks may occur as a result of attempting to trace into the function.
[40/0] [__graph_breaks]   Hint: Please file an issue to PyTorch.
[40/0] [__graph_breaks] 
[40/0] [__graph_breaks]   Developer debug context: qualname: device_of.__init__, name: __init__, filename: `/home/ryanguo99/repos/pytorch/torch/cuda/__init__.py`, skip reason: skipped according trace_rules.lookup MOD_SKIPLIST
[40/0] [__graph_breaks] 
[40/0] [__graph_breaks] User code traceback:
[40/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 484, in torch_dynamo_resume_in_forward_at_484
[40/0] [__graph_breaks]     return bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state).to(inp_dtype)
[40/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py", line 533, in matmul_4bit
[40/0] [__graph_breaks]     return MatMul4Bit.apply(A, B, out, bias, quant_state)
[40/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py", line 462, in forward
[40/0] [__graph_breaks]     output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
[40/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1352, in dequantize_4bit
[40/0] [__graph_breaks]     absmax = dequantize_blockwise(quant_state.absmax, quant_state.state2)
[40/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1027, in dequantize_blockwise
[40/0] [__graph_breaks]     with _cuda_device_of(A):
[40/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 201, in _cuda_device_of
[40/0] [__graph_breaks]     return torch.cuda.device_of(a)
```

2. 
```
[46/0] [__graph_breaks] Graph break: skip: from user code at:
[46/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1027, in torch_dynamo_resume_in_dequantize_blockwise_at_1027
[46/0] [__graph_breaks]     with _cuda_device_of(A):
[46/0] [__graph_breaks] Traceback (most recent call last):
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 1173, in __call__
[46/0] [__graph_breaks]     result = self._inner_convert(
[46/0] [__graph_breaks]              ^^^^^^^^^^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 585, in __call__
[46/0] [__graph_breaks]     return _compile(
[46/0] [__graph_breaks]            ^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 1023, in _compile
[46/0] [__graph_breaks]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[46/0] [__graph_breaks]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_utils_internal.py", line 97, in wrapper_function
[46/0] [__graph_breaks]     return function(*args, **kwargs)
[46/0] [__graph_breaks]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 746, in compile_inner
[46/0] [__graph_breaks]     return _compile_inner(code, one_graph, hooks, transform)
[46/0] [__graph_breaks]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 782, in _compile_inner
[46/0] [__graph_breaks]     out_code = transform_code_object(code, transform)
[46/0] [__graph_breaks]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 1418, in transform_code_object
[46/0] [__graph_breaks]     transformations(instructions, code_options)
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 256, in _fn
[46/0] [__graph_breaks]     return fn(*args, **kwargs)
[46/0] [__graph_breaks]            ^^^^^^^^^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 700, in transform
[46/0] [__graph_breaks]     tracer.run()
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3065, in run
[46/0] [__graph_breaks]     super().run()
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
[46/0] [__graph_breaks]     while self.step():
[46/0] [__graph_breaks]           ^^^^^^^^^^^
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
[46/0] [__graph_breaks]     self.dispatch_table[inst.opcode](self, inst)
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2548, in BEFORE_WITH
[46/0] [__graph_breaks]     self.setup_or_before_with(inst)
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2555, in setup_or_before_with
[46/0] [__graph_breaks]     unimplemented_v2(
[46/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/exc.py", line 504, in unimplemented_v2
[46/0] [__graph_breaks]     raise Unsupported(msg)
[46/0] [__graph_breaks] torch._dynamo.exc.Unsupported: Unsupported context manager
[46/0] [__graph_breaks]   Explanation: Dynamo does not know how to enter a `device_of` context manager.
[46/0] [__graph_breaks]   Hint: Avoid using the unsupported context manager.
[46/0] [__graph_breaks]   Hint: File an issue to PyTorch. Simple context managers can potentially be supported, but note that context managers can't be supported in general
[46/0] [__graph_breaks] 
[46/0] [__graph_breaks]   Developer debug context: Attempted SETUP_WITH/BEFORE_WITH on UserDefinedObjectVariable(device_of)
[46/0] [__graph_breaks] 
[46/0] [__graph_breaks] 
[46/0] [__graph_breaks] from user code:
[46/0] [__graph_breaks]    File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1027, in torch_dynamo_resume_in_dequantize_blockwise_at_1027
[46/0] [__graph_breaks]     with _cuda_device_of(A):
```

3. 
```
[47/0] [__graph_breaks] Graph break in user code at /home/ryanguo99/repos/pytorch/torch/_dynamo/polyfills/__init__.py:146
[47/0] [__graph_breaks] Graph Break Reason: Attempted to call function marked as skipped
[47/0] [__graph_breaks]   Explanation: Dynamo does not know how to trace the builtin `None._SimpleCData.__new__.` This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind).
[47/0] [__graph_breaks]   Hint: If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround.
[47/0] [__graph_breaks]   Hint: If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html for more details) or, if it is traceable, use `torch.compiler.allow_in_graph`.
[47/0] [__graph_breaks] 
[47/0] [__graph_breaks]   Developer debug context: module: None, qualname: _SimpleCData.__new__, skip reason: <missing reason>
[47/0] [__graph_breaks] 
[47/0] [__graph_breaks] User code traceback:
[47/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 497, in get_ptr
[47/0] [__graph_breaks]     return ct.c_void_p(A.data_ptr())
[47/0] [__graph_breaks]   File "/home/ryanguo99/repos/pytorch/torch/_dynamo/polyfills/__init__.py", line 146, in instantiate_user_defined_class_object
[47/0] [__graph_breaks]     obj = cls.__new__(cls, *args, **kwargs)
[47/0] [__graph_breaks] 
```

4. 
```
[48/0] [__graph_breaks] Graph break in user code at /home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py:482
[48/0] [__graph_breaks] Graph Break Reason: torch.* op returned non-Tensor int call_function <built-in function _cuda_getCurrentRawStream>
[48/0] [__graph_breaks] User code traceback:
[48/0] [__graph_breaks]   File "/home/ryanguo99/.conda/envs/pt311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 482, in _get_tensor_stream
[48/0] [__graph_breaks]     return ct.c_void_p(torch._C._cuda_getCurrentRawStream(tensor.device.index))
```

**Comment by StrongerXi** [comment]
@williamwen42 do we leave this open?

**Comment by williamwen42** [comment]
All the graph breaks seem to be related to `bitsandbytes`. Would skipping this module improve perf?

Also double check if there's a perf hit still - if there isn't one anymore, we can probably close this.
