### ISSUE TITLE
Initialization error when moving data to the GPU

### ISSUE THREAD

**Issue by stephane-archer** [pytorch/pytorch#12819]
I want to move my data to the GPU in **collate_fn**
because it will be done in parallel and **moving the data to the GPU** is my main **bottleneck**.

But I have the following error message.

How to make it possible?

I search a way to transfer my data in parallel so **I don't have to wait every mini batch**

`RuntimeError: Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "<ipython-input-18-8366151b8664>", line 17, in collate_fn
    data= data.to(torch.device('cuda'))
RuntimeError: cuda runtime error (3) : initialization error at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.c:60
`

**Comment by SsnL** [comment]
> moving the data to the GPU is my main bottleneck.

Are you certain? Naive moving is a synchronization point, so unless you synchronize before time measurements, you will see a lot of time in moving. Instead, you can try, `data.to(device, non_blocking=True)`.

**Comment by SsnL** [comment]
> To(device) take 75% of my program time in 0.4.0

are you sure that it's not synchronization reason?

**Comment by SsnL** [comment]
CUDA synchronization is normally needed when you transfer things between CPU and GPU.

**Comment by nabsabraham** [comment]
has this been solved? I get a `RuntimeError: CUDA error: initialization error` when trying to move something to gpu. I only have one GPU

**Comment by rajasrijan** [comment]
Is there any workaround, I'm having same problem?

**Comment by ndrizza** [comment]
Same problem. Do you have any solution?
