### ISSUE TITLE
A trivial but annoying “bug” in random_split

### ISSUE THREAD

**Issue by X-Engineer-001** [pytorch/pytorch#128116]
### 🐛 Describe the bug

```
import torch
import torchvision
from torch.utils.data import random_split
whole_trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)
trainsets = random_split(whole_trainset, [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
```
```
Files already downloaded and verified
Traceback (most recent call last):
  File "D:\碩論\test\test.py", line 5, in <module>
    trainsets = random_split(whole_trainset, [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\utils\data\dataset.py", line 454, in random_split
    raise ValueError("Sum of input lengths does not equal the length of the input dataset!")
ValueError: Sum of input lengths does not equal the length of the input dataset!
```
Speculated cause:
print(0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05+0.05) gives "1.0000000000000002" by plain Python in the first place.

### Versions

Collecting environment information...
PyTorch version: 2.2.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 546.80
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2500
DeviceID=CPU0
Family=207
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2500
Name=12th Gen Intel(R) Core(TM) i9-12900H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] torch==2.2.1+cu118
[pip3] torchaudio==2.2.1+cu118
[pip3] torchvision==0.17.1+cu118
[conda] Could not collect

**Comment by ajbrent** [comment]
Tried to reproduce with PyTorch from source (2.4.0a0+git662a78f), Python 3.12.3, and Cuda 12.5 resulting in:
```
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 10 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 11 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 12 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 13 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 14 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 15 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 16 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 17 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 18 is 0. This might result in an empty dataset.
  warnings.warn(
/home/ajbrent/pytorch_contrib/pytorch/torch/utils/data/dataset.py:472: UserWarning: Length of split at index 19 is 0. This might result in an empty dataset.
  warnings.warn(
```
(the same result occurred using PyTorch 2.2.1, Python 3.12.3, and pytorch-cuda==12.1)

I was able to reproduce this issue with Pytorch 2.2.1, Python 3.11.9, and pytorch-cuda==12.1: 
```
Traceback (most recent call last):
  File "/home/ajbrent/pytorch_contrib/issue_128116/response_one.py", line 3, in <module>
    trainsets = random_split(range(10), [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajbrent/anaconda3/envs/pytorch-repro/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 454, in random_split
    raise ValueError("Sum of input lengths does not equal the length of the input dataset!")
ValueError: Sum of input lengths does not equal the length of the input dataset!
```

**Comment by andrewkho** [comment]
It looks like th second half of this check is the cause: https://github.com/pytorch/pytorch/blob/11f2d8e823efa8508d1f2198429b95b1e9007222/torch/utils/data/dataset.py#L455

**Comment by ajbrent** [comment]
Seems like this is not a problem in Python 3.12 because the algorithm that 'sum()' uses has been changed [see here](https://docs.python.org/3/whatsnew/3.12.html). (The warning for empty datasets is expected since you would be splitting 10 items into 20 sets.)

As far as fixing for earlier versions of Python:
In the discussion referenced by @andrewkho, it is mentioned that there should be no error if the list of fractions sums to less than 1, but there is a test that fails in the case that the list sums to less than 1: 
https://github.com/pytorch/pytorch/blob/main/test/test_dataloader.py#L266
This test was added as a part of the pull request that resolved the aforementioned [#78510](https://github.com/pytorch/pytorch/issues/78510).

Either way the problem is solved by altering https://github.com/pytorch/pytorch/blob/11f2d8e823efa8508d1f2198429b95b1e9007222/torch/utils/data/dataset.py#L455

Two options:
1. Removing the 'and' clause above (enforcing the equality constraint since math.isclose() should solve the issues that come from using floating point numbers in Python).
2. Replacing 'and' with an 'or': `if math.isclose(sum(lengths), 1) or sum(lengths) < 1:`, and removing the above test case.

**Comment by X-Engineer-001** [comment]
Oh. I did speculate that it's a problem related to Python, but I didn't realize that I should also describe my python version then. Thank you all for helping.

**Comment by taras-janea** [comment]
Closing this issue as it is no longer reproducible with the latest PyTorch version. If you continue to experience this problem or have related concerns, please feel free to open a new issue.
