### ISSUE TITLE
`swap_tensors` fail when calling `nn.Module.to` on XLA `DDP` wrapped models.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#128165]
### 🐛 Describe the bug

```python
torch.distributed.init_process_group(
    backend="xla",
    init_method="xla://",
)

m = torch.nn.Linear(10, 10).to(xla)
m = torch.nn.parallel.DistributedDataParallel(m, device_ids=[0])

# Error happens here!
m.half()
```

```python
[rank0]: Traceback (most recent call last):
[rank0]:   File "torch/nn/modules/module.py", line 824, in _apply
[rank0]:     torch.utils.swap_tensors(param, param_applied)
[rank0]:   File "torch/utils/__init__.py", line 72, in swap_tensors
[rank0]:     check_use_count(t1, 't1')
[rank0]:   File "torch/utils/__init__.py", line 70, in check_use_count
[rank0]:     raise RuntimeError(error_str)
[rank0]: RuntimeError: Expected use_count of t1 to be 1 or 2 with an AccumulateGrad node but got 4 make sure you are not holding references to the tensor in other places.

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "examples/scratch.py", line 58, in <module>
[rank0]:     m.half()
[rank0]:   File "torch/nn/modules/module.py", line 1017, in half
[rank0]:     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
[rank0]:   File "torch/nn/modules/module.py", line 779, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "torch/nn/modules/module.py", line 828, in _apply
[rank0]:     raise RuntimeError(f"_apply(): Couldn't swap {self._get_name()}.{key}") from e
[rank0]: RuntimeError: _apply(): Couldn't swap Linear.weight
```

### Versions

- PyTorch version: f5328542b5365741176e71dd8a2954e0f350b9bc
- PyTorch/XLA version: [aec273056a95d8119279c15d36c0f48f739fb810](https://github.com/pytorch/xla/commit/aec273056a95d8119279c15d36c0f48f739fb810)

**Comment by ysiraichi** [comment]
This started failing after making `swap_tensors` the default for XLA (#126814)

**Comment by JackCaoG** [comment]
Ah... i totally forgot about the ddp wrapper. I guess similar thing will happen with the FSDP wrapper.

**Comment by mikaylagawarecki** [comment]
@JackCaoG let me know if we should revert or whether you have a workaround for this

**Comment by JackCaoG** [comment]
@mikaylagawarecki let's revert, sorry for all the troubles. I am curious is we first wrap the `ddp` and then move to another data type, is this a supported use case? Will swap_tensor work in this case?

**Comment by mikaylagawarecki** [comment]
could you clarify what you mean by this please

> we first wrap the ddp and then move to another data type, is this a supported use case?

**Comment by JackCaoG** [comment]
pretty much is
```
m = torch.nn.Linear(10, 10).to(xm.xla_device())
m = torch.nn.parallel.DistributedDataParallel(m, device_ids=[0])

# Error happens here!
m.half()
```
a valid use case for pytorch? I think it is. If that's the case I am wondering if `swap_tensor` can handle this case.

**Comment by mikaylagawarecki** [comment]
Do you happen to know why there are multiple references in this case? I would have to investigate more to understand

**Comment by JackCaoG** [comment]
My best case is that DDP wrapper adds some kind of reference to all the module's parameter, but I am not the DDP expert 😢 .

**Comment by mikaylagawarecki** [comment]
fyi @ysiraichi the offending PR was reverted, but keeping this issue open to track the problem with swap_tensors and DDP

**Comment by mikaylagawarecki** [comment]
@albanD 

I managed to reproduce this with CUDA and looked into where the 4 references were coming from:
(1) One reference seemed to occur when going from the python to C++ constructor. In particular, before the python `dist.Reducer` call, every param has `use_count == 1`, but after being passed to the C++ constructor [here](https://github.com/pytorch/pytorch/blob/2e5366fbc04f819c62612e8c56fb786b43c1c67d/torch/csrc/distributed/c10d/reducer.cpp#L125) has `use_count == 2`. I was unable to distill from t[he pybind logic](https://github.com/pytorch/pytorch/blob/2e5366fbc04f819c62612e8c56fb786b43c1c67d/torch/csrc/distributed/c10d/init.cpp#L508-L531) why this would be the case  
(2) In `Reducer::initialize_buckets` [this line](https://github.com/pytorch/pytorch/blob/56a3d276fefa256ec354a1b94d756161605535e2/torch/csrc/distributed/c10d/reducer.cpp#L1154)
(3) In `Reducer` constructor [getting the gradient accumulator](https://github.com/pytorch/pytorch/blob/56a3d276fefa256ec354a1b94d756161605535e2/torch/csrc/distributed/c10d/reducer.cpp#L180): I think this reference is okay and would work with swap_tensors

<details closed>
<summary><b>Script</b></summary>
<br>

```python
'''
torchrun --standalone --nproc-per-node 2 test_ddp.py
'''
import torch
from torch.distributed.device_mesh import init_device_mesh

device_mesh = init_device_mesh("cuda", (min(2, torch.cuda.device_count()),))

torch.__future__.set_swap_module_params_on_conversion(True)
m = torch.nn.Linear(10, 10, device="cuda")
m = torch.nn.parallel.DistributedDataParallel(m, device_ids=[0])

# Error happens here!
m.half()
```

</details>

Not sure whether we can solve this with careful handling in DDP, or whether we can modify `swap_tensors` to accomodate this.
