### ISSUE TITLE
put profiling results from different ranks into one webpage

### ISSUE THREAD

**Issue by guoyejun** [pytorch/pytorch#128292]
### 🚀 The feature, motivation and pitch

there's always device imbalance when we run the workload on more than one devices with TP and DP.  We can get to know what happened in each GPU with torch.profiler and prof.export_chrome_trace in chrome://tracing. But we are unable to put all the ranks profiling results together in a single webpage, the one webpage can give us a big picture of the device imbalance.

the feature might contain two things.
1) to align timeline among all the ranks, and so there's only one timeline for all the ranks.
2) a script to combine all the profiling result files into one file and so we can display it in one webpage.

thanks.

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by sraikund16** [comment]
We have a tool for this known as Holistic Trace Analysis: https://pytorch.org/tutorials/beginner/hta_intro_tutorial.html

**Comment by guoyejun** [comment]
thanks, I tried this tool with gpt-fast, but looks that something is wrong.

Here is what I changed in the gpt-fast code, according to hta doc.
```
$ git diff
diff --git a/generate.py b/generate.py
index c58a224..f1f84e5 100644
--- a/generate.py
+++ b/generate.py
@@ -288,6 +288,10 @@ def main(
             # only print on rank 0
             print = lambda *args, **kwargs: None

+    from hta.trace_analysis import TraceAnalysis
+    trace_dir = "./hta_traces"
+    analyzer = TraceAnalysis(trace_dir=trace_dir)
+
     print(f"Using device={device}")
     precision = torch.bfloat16
     is_speculative = draft_checkpoint_path is not None
```

and got errors with below commands. Looks that something is missed for the ranks.
```
$ ENABLE_INTRA_NODE_COMM=1 torchrun --standalone --nproc_per_node=2 generate.py --checkpoint_path checkpoints/meta-llama/Llama-2-7b-chat-hf/model.pth --prompt "Hello, my name is" --compile
W0624 23:13:19.742873 140327988369216 torch/distributed/run.py:778]
W0624 23:13:19.742873 140327988369216 torch/distributed/run.py:778] *****************************************
W0624 23:13:19.742873 140327988369216 torch/distributed/run.py:778] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0624 23:13:19.742873 140327988369216 torch/distributed/run.py:778] *****************************************
2024-06-24 23:13:25,062 - hta - trace.py:L389 - INFO - /tmp/gpt-fast/hta_traces
2024-06-24 23:13:25,062 - hta - trace_file.py:L36 - WARNING - No trace file is found in /tmp/gpt-fast/hta_traces
2024-06-24 23:13:25,062 - hta - trace_file.py:L88 - WARNING - failed to create rank to trace map
2024-06-24 23:13:25,062 - hta - trace.py:L535 - INFO - ranks=[]
2024-06-24 23:13:25,063 - hta - trace.py:L541 - ERROR - The list of ranks to be parsed is empty.
2024-06-24 23:13:25,063 - hta - trace.py:L389 - INFO - /tmp/gpt-fast/hta_traces
2024-06-24 23:13:25,063 - hta - trace_file.py:L36 - WARNING - No trace file is found in /tmp/gpt-fast/hta_traces
2024-06-24 23:13:25,063 - hta - trace_file.py:L88 - WARNING - failed to create rank to trace map
2024-06-24 23:13:25,063 - hta - trace.py:L535 - INFO - ranks=[]
2024-06-24 23:13:25,063 - hta - trace.py:L541 - ERROR - The list of ranks to be parsed is empty.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/tmp/gpt-fast/generate.py", line 436, in <module>
[rank1]:     main(
[rank1]:   File "/tmp/gpt-fast/generate.py", line 293, in main
[rank1]:     analyzer = TraceAnalysis(trace_dir=trace_dir)
...
```

**Comment by sraikund16** [comment]
It looks like the directory you posted is empty
`No trace file is found in /tmp/gpt-fast/hta_traces`

**Comment by guoyejun** [comment]
should I prepare something ahead in this directory? thanks.

This directory is passed to TraceAnalysis at the beginning, the expectation is HTA will record something into this directory, instead of that user need to prepare something ahead within the directory.

**Comment by sraikund16** [comment]
@guoyejun HTA does post processing on the traces once you've collected them. You need to first get the traces from the profiler and then use HTA on them afterwards.

**Comment by guoyejun** [comment]
thanks @sraikund16 , I'm able to run HTA, but looks that it does not provide insights of the imbalance.

In my try on gpt-fast with TP=2, I got the below result. In rough summary, rank 0 uses 53k us (84474.444-31072.147) more time on allreduce than rank1, and host_wait time on rank1 is 45k us (81150.84-35828.71) more than rank0. But it still could not explain why it happens (for example, one rank is waiting on another rank, and why?).

And my idea is to combine kineto profiling result files from different ranks into one file and display it within one webpage with chrome://tracing (looks that HTA does not provide this feature). We may get some insights visually from the timeline.

```
   rank  idle_time(us)  compute_time(us)  non_compute_time(us)  kernel_time(us)  idle_time_pctg  compute_time_pctg  non_compute_time_pctg
0     0   42514.871305        154671.134               446.143    197632.148305           21.51              78.26                   0.23
1     1   85520.319399        102648.532               451.959    188620.810398           45.34              54.42                   0.24

(   rank stream idle_category  idle_time  idle_time_ratio
0     0      7     host_wait   35828.71             0.84
1     0      7   kernel_wait    6581.45             0.15
2     0      7         other     104.70             0.00
0     1      7     host_wait   81150.84             0.95
1     1      7   kernel_wait    4316.00             0.05
2     1      7         other      53.47             0.00, None)

                                                 name   sum (us)   max (us)   min (us)      stddev     mean (us)  kernel_type  rank
0   ampere_bf16_s16816gemm_bf16_64x64_sliced1x2_ld...   4440.189   4440.189   4440.189    0.000000   4440.189000  COMPUTATION     0
1   ampere_bf16_s16816gemm_bf16_64x64_sliced1x2_ld...   4434.663   4434.663   4434.663    0.000000   4434.663000  COMPUTATION     1
2                                              others  14381.285   1582.836      1.856  315.735459    235.758770  COMPUTATION     0
3                                              others  14849.728   1580.470      1.888  328.370394    243.438164  COMPUTATION     1
4                              triton_red_fused_bmm_6   4410.430   4410.430   4410.430    0.000000   4410.430000  COMPUTATION     0
5                              triton_red_fused_bmm_6   4618.213   4618.213   4618.213    0.000000   4618.213000  COMPUTATION     1
6                          triton_red_fused_div_mm_19   1865.936   1865.936   1865.936    0.000000   1865.936000  COMPUTATION     0
7                          triton_red_fused_div_mm_19   2027.889   2027.889   2027.889    0.000000   2027.889000  COMPUTATION     1
8                              triton_red_fused_mm_11   5392.112   5392.112   5392.112    0.000000   5392.112000  COMPUTATION     0
9                              triton_red_fused_mm_11   6086.484   6086.484   6086.484    0.000000   6086.484000  COMPUTATION     1
10                             triton_red_fused_mm_13   9875.939   9875.939   9875.939    0.000000   9875.939000  COMPUTATION     0
11                             triton_red_fused_mm_13  10023.643  10023.643  10023.643    0.000000  10023.643000  COMPUTATION     1
12                             triton_red_fused_mm_15   5990.062   5990.062   5990.062    0.000000   5990.062000  COMPUTATION     0
13                             triton_red_fused_mm_15   6637.723   6637.723   6637.723    0.000000   6637.723000  COMPUTATION     1
14                              triton_red_fused_mm_8   9964.264   9964.264   9964.264    0.000000   9964.264000  COMPUTATION     0
15                              triton_red_fused_mm_8   9125.989   9125.989   9125.989    0.000000   9125.989000  COMPUTATION     1
16                              triton_red_fused_mm_9  12275.725  12275.725  12275.725    0.000000  12275.725000  COMPUTATION     0
17                              triton_red_fused_mm_9  12146.742  12146.742  12146.742    0.000000  12146.742000  COMPUTATION     1
18  void at::native::elementwise_kernel<128, 4, at...   1600.748   1600.748   1600.748    0.000000   1600.748000  COMPUTATION     0
19  void at::native::elementwise_kernel<128, 4, at...   1625.311   1625.311   1625.311    0.000000   1625.311000  COMPUTATION     1
20  void c10d::intra_node_comm::oneShotAllReduceKe...  84474.444  84474.444  84474.444    0.000000  84474.444000  COMPUTATION     0
21  void c10d::intra_node_comm::oneShotAllReduceKe...  31072.147  31072.147  31072.147    0.000000  31072.147000  COMPUTATION     1
22                     Memcpy DtoD (Device -> Device)    409.022      3.104      1.472    0.349313      2.726813       MEMORY     0
23                     Memcpy DtoD (Device -> Device)    409.784      3.072      1.760    0.275828      2.731893       MEMORY     1
24                   Memcpy HtoD (Pageable -> Device)      1.472      1.472      1.472    0.000000      1.472000       MEMORY     0
25                   Memcpy HtoD (Pageable -> Device)      1.440      1.440      1.440    0.000000      1.440000       MEMORY     1
26                                    Memset (Device)     35.649      2.880      1.056    0.674586      1.782450       MEMORY     0
27                                    Memset (Device)     40.735      2.432      1.312    0.482839      2.036750       MEMORY     1

```

**Comment by sraikund16** [comment]
@guoyejun please try using the Timeline class found here https://github.com/facebookresearch/HolisticTraceAnalysis/blob/main/hta/common/timeline.py#L520

**Comment by guoyejun** [comment]
@sraikund16  do you mean that there will be new changes to support preprocess in HTA?  And at that time, I can combine kineto profiling result files from different ranks into one file and display it in one webpage with chrome://tracing?

**Comment by sraikund16** [comment]
@guoyejun sorry I lost track of this. Yes, HTA is currently working on supporting this for OSS. However, it won't be on a webpage. It will output the plot using the python library

**Comment by guoyejun** [comment]
@sraikund16 thanks, not sure if the plot will include the things that can be displayed in the webpage. With chrome://tracing, we can easily enlarge/shrink the timeline to get detail info.

**Comment by sraikund16** [comment]
I don't think we have plans on doing this internally so I will mark this with OSS contribution wanted

**Comment by guoyejun** [comment]
@sraikund16  with current implementation, for the trace files (one file for one rank) from kineto profiler, are the timelines in these files already aligned? Or we need to do something to align them, for example:
1) call one sync function at the beginning of the process to make sure all the timelines are aligned among all the ranks.
2) do some smart analysis on the trace files to offset some timelines in different ranks.

**Comment by sraikund16** [comment]
@guoyejun We align the traces by subtracting the unix timestamp from the timestamp from the beginning of the current three month period. 

https://github.com/pytorch/kineto/blob/main/libkineto/src/output_json.cpp#L53-L70

**Comment by guoyejun** [comment]
thanks, not sure if I understand correctly.  Does it cover the following two cases:
1) more than one node is involved, the host times on each node are not exactly same, for worst case, maybe with seconds difference.
2) the ranks in the same node do not start at the exact same time, maybe rank0 starts at time t0, and rank1 starts at time t0+100ms.

so, for the RelativeTime "t1" in rank0.log and "t1" in rank1.log and "t1" in rank20.log (different node), are they the same time?

**Comment by sraikund16** [comment]
@guoyejun the profiler on its own does not do any alignment of this sort. It just outputs the operations it sees while active
