### ISSUE TITLE
 python test/inductor/test_torchinductor.py -k GPUTests.test_slice_scatter_reinplace_cuda failure

### ISSUE THREAD

**Issue by nWEIdia** [pytorch/pytorch#128277]
### 🐛 Describe the bug

The inductor test fails on A100 with the following error

`Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2715, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 10385, in new_test
    return value(self)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 6806, in test_slice_scatter_reinplace
    self.common(kv_cache_module, (inp, 1), check_lowp=False)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 582, in check_model_gpu
    check_model(
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 470, in check_model
    self.assertEqual(
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 3607, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 8075 / 8448 (95.6%)
Greatest absolute difference: 0.008390426635742188 at index (0, 1, 26, 27) (up to 1e-05 allowed)
Greatest relative difference: 0.5796821713447571 at index (0, 5, 0, 29) (up to 1.3e-06 allowed)

To execute this test, run the following from the base repo dir:
     python test/inductor/test_torchinductor.py -k GPUTests.test_slice_scatter_reinplace_cuda

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0`

### Versions

Tested with https://github.com/pytorch/pytorch/commit/3bcc3cddb580bf0f0f1958cfe27001f236eac2c1

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by eellison** [comment]
I could not repro this on master (940db13f8ad36c9beedb12308aad01ef95e44883). please rebase to master, if it still repros re-open.

**Comment by soulitzer** [comment]
Doesn't repro for me on https://github.com/pytorch/pytorch/commit/2176ef7dfaf02dd6dbb8484a50c99d5fadf3ea0b, is anyone else able to repro this?
