### ISSUE TITLE
Cannot export onnx model with autograd.functional.jacobian

### ISSUE THREAD

**Issue by thisisd3** [pytorch/pytorch#128325]
### 🐛 Describe the bug

Good morning,

I have the following simple model:

```
import torch

class Model1(torch.nn.Module):
    def __init__(self):
         super(Model1, self).__init__()

    def forward(self, X):
        return X[:,0] ** 2 + X[:, 1]
        
class F(torch.nn.Module):
    def __init__(self, model: torch.nn.Module):
        super(F, self).__init__()
        self.model = model

    def forward(self, X):
        out = self.model(X)
        grad = torch.autograd.functional.jacobian(self.model, X)
        return out, torch.flatten(grad, 1)
    
f = F(Model1())
X = torch.arange(6).reshape(3, 2).to(torch.float32)
out, grad = f(X)
print("input:\n", X)
print("output:\n", out)
print("gradient:\n", grad[1])
``` 

I am trying to export it to onnx. 

When I use old-school export

```
torch.onnx.export(f, X, 'test.onnx')
```

i get the following error
``` 
UnsupportedOperatorError: Exporting the operator 'aten::select_backward' to ONNX opset version 17 is not supported
```

when i try to use dynamo export as following:

```
dynamo_model = torch.onnx.dynamo_export(f, X)
``` 
i get the following error

``` 
NotImplementedError                       Traceback (most recent call last)
File [<redacted>/torch/_dynamo/utils.py:621](<redacted>/torch/_dynamo/utils.py#line=620), in proxy_args_kwargs(args, kwargs)
    620 try:
--> 621     proxy_args = tuple(arg.as_proxy() for arg in args)
    622     proxy_kwargs = {key: arg.as_proxy() for key, arg in kwargs.items()}

File [<redacted>/torch/_dynamo/utils.py:621](<redacted>/torch/_dynamo/utils.py#line=620), in <genexpr>(.0)
    620 try:
--> 621     proxy_args = tuple(arg.as_proxy() for arg in args)
    622     proxy_kwargs = {key: arg.as_proxy() for key, arg in kwargs.items()}

File [<redacted>/torch/_dynamo/variables/base.py:301](<redacted>/torch/_dynamo/variables/base.py#line=300), in VariableTracker.as_proxy(self)
    300 def as_proxy(self):
--> 301     raise NotImplementedError(str(self))

NotImplementedError: NNModuleVariable()

``` 

please advise on how to export this model to onnx. Any help would be greatly appreciated. 

### Versions

```
[pip3] onnx==1.16.0
[pip3] torch==2.3.1
```

**Comment by ezyang** [comment]
> UnsupportedOperatorError: Exporting the operator 'aten::select_backward' to ONNX opset version 17 is not supported

I mean, sounds like you're gonna have a bad time, because ONNX's operator set is insufficient for backwards/training

**Comment by thisisd3** [comment]
That's quite strange because this self contained example
```
import torch
import onnxruntime as ort
import numpy as np

class F(torch.nn.Module):
    def forward(self, X):
        y = X.square().sum()
        return torch.autograd.grad(y, X, create_graph=True, retain_graph=True)

f = F()
X = torch.arange(3).to(torch.float32)
X.requires_grad_(True)
test_out = f(X)
print(test_out)

X2 = torch.arange(3).to(torch.float32)
X2.requires_grad_(True)
torch.onnx.export(f, X2,'test.onnx', input_names=['X'],
            output_names=['out'])

inArray = np.arange(3).astype(np.float32)
ort_sess = ort.InferenceSession('test.onnx')
outputs = ort_sess.run(None, {'X': inArray})

print("input:", inArray)
print("output:", outputs[0])
```

also uses autograd and tracks the gradient, and runs absolutely fine. I'm not sure I understand why it works fine tracking a scalar with autograd.grad, but fails when it comes to the multivariate jacobian.

**Comment by ezyang** [comment]
I mean, how complicated your backward graph is depends on your model. If you're lucky you'll hit everything in the onnx opset. But we have some pretty strange backward ops and onnx doesn't always have full coverage.

**Comment by justinchuby** [comment]
This is exported as the following:

## Code

```python
import torch

class Model1(torch.nn.Module):
    def __init__(self):
         super(Model1, self).__init__()

    def forward(self, X):
        return X[:,0] ** 2 + X[:, 1]

class F(torch.nn.Module):
    def __init__(self, model: torch.nn.Module):
        super(F, self).__init__()
        self.model = model

    def forward(self, X):
        out = self.model(X)
        grad = torch.autograd.functional.jacobian(self.model, X)
        return out, torch.flatten(grad, 1)

f = F(Model1())
X = torch.arange(6).reshape(3, 2).to(torch.float32)
out, grad = f(X)
onnx_program = torch.onnx.export(f, (X,), report=True, dynamo=True, verify=True)
print(onnx_program)

```

## Report

# PyTorch ONNX Conversion Report

```
❌ Obtain model graph with `torch.export.export`
✅ Obtain model graph with `torch.export.export(..., strict=False)`
⚪ Obtain model graph with `torch.jit.trace`
✅ Translate the graph into ONNX
✅ Run `onnx.checker` on the ONNX model
✅ Execute the model with ONNX Runtime
✅ Validate model output accuracy
```

## Error messages

```pytb
# ⚠️ Errors from strategy 'TorchExportStrategy': -----------------------

Traceback (most recent call last):

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 737, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 737, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
                       ^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/variables/base.py", line 257, in as_proxy
    raise NotImplementedError(str(self))

NotImplementedError: NNModuleVariable()


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_capture_strategies.py", line 90, in __call__
    exported_program = self._capture(model, args, kwargs, dynamic_shapes)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/onnx/_internal/exporter/_capture_strategies.py", line 123, in _capture
    return torch.export.export(
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/__init__.py", line 258, in export
    return _export(
           ^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/_trace.py", line 1007, in wrapper
    raise e

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/_trace.py", line 980, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/exported_program.py", line 105, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/_trace.py", line 1915, in _export
    export_artifact = export_func(  # type: ignore[operator]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/_trace.py", line 1214, in _strict_export
    return _strict_export_lower_to_aten_ir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/_trace.py", line 1242, in _strict_export_lower_to_aten_ir
    gm_torch_level = _export_to_torch_ir(
                     ^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/export/_trace.py", line 550, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
                        ^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 1432, in inner
    result_traced = opt_f(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1251, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 523, in __call__
    return _compile(
           ^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 915, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 663, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 696, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 216, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 631, in transform
    tracer.run()

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
    super().run()

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2279, in CALL
    self._call(inst)

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2273, in _call
    self.call_function(fn, args, kwargs)

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/variables/torch.py", line 892, in call_function
    *proxy_args_kwargs(args, kwargs),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 744, in proxy_args_kwargs
    unimplemented(

  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 288, in unimplemented
    raise Unsupported(msg, case_name=case_name) from from_exc

torch._dynamo.exc.Unsupported: call_function args: NNModuleVariable() TensorVariable() 

from user code:
   File "/workspace/torch-onnx/tests/test5.py", line 18, in forward
    grad = torch.autograd.functional.jacobian(self.model, X)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information



```

## Exported program

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, x: "f32[3, 2]"):
             # File: /workspace/torch-onnx/tests/test5.py:9 in forward, code: return X[:,0] ** 2 + X[:, 1]
            slice_1: "f32[3, 2]" = torch.ops.aten.slice.Tensor(x, 0, 0, 9223372036854775807)
            select: "f32[3]" = torch.ops.aten.select.int(slice_1, 1, 0);  slice_1 = None
            scalar_tensor_default: "f32[]" = torch.ops.aten.scalar_tensor.default(2, dtype = torch.float32)
            pow_1: "f32[3]" = torch.ops.aten.pow.Tensor_Tensor(select, scalar_tensor_default);  select = scalar_tensor_default = None
            slice_2: "f32[3, 2]" = torch.ops.aten.slice.Tensor(x, 0, 0, 9223372036854775807)
            select_1: "f32[3]" = torch.ops.aten.select.int(slice_2, 1, 1);  slice_2 = None
            add: "f32[3]" = torch.ops.aten.add.Tensor(pow_1, select_1);  pow_1 = select_1 = None
            
             # File: /workspace/torch-onnx/tests/test5.py:18 in forward, code: grad = torch.autograd.functional.jacobian(self.model, X)
            detach: "f32[3, 2]" = torch.ops.aten.detach.default(x);  x = None
            detach_1: "f32[3, 2]" = torch.ops.aten.detach.default(detach);  detach = None
            detach_2: "f32[3, 2]" = torch.ops.aten.detach.default(detach_1);  detach_1 = None
            zeros_like: "f32[3, 2]" = torch.ops.aten.zeros_like.default(detach_2, pin_memory = False)
            zeros_like_1: "f32[3, 2]" = torch.ops.aten.zeros_like.default(detach_2, pin_memory = False)
            zeros_like_2: "f32[3, 2]" = torch.ops.aten.zeros_like.default(detach_2, pin_memory = False);  detach_2 = None
            stack: "f32[3, 3, 2]" = torch.ops.aten.stack.default([zeros_like, zeros_like_1, zeros_like_2]);  zeros_like = zeros_like_1 = zeros_like_2 = None
            view: "f32[3, 3, 2]" = torch.ops.aten.view.default(stack, [3, 3, 2]);  stack = None
            detach_3: "f32[3, 3, 2]" = torch.ops.aten.detach.default(view);  view = None
            detach_4: "f32[3, 3, 2]" = torch.ops.aten.detach.default(detach_3);  detach_3 = None
            detach_5: "f32[3, 3, 2]" = torch.ops.aten.detach.default(detach_4);  detach_4 = None
            
             # File: /workspace/torch-onnx/tests/test5.py:19 in forward, code: return out, torch.flatten(grad, 1)
            view_1: "f32[3, 6]" = torch.ops.aten.view.default(detach_5, [3, 6]);  detach_5 = None
            return (add, view_1)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='add'), target=None), OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='view_1'), target=None)])
Range constraints: {}

```

## ONNX model

```python
<
    ir_version=9,
    opset_imports={'': 18, 'pkg.onnxscript.torch_lib': 1, 'pkg.onnxscript.torch_lib.common': 1},
    producer_name='torch',
    producer_version='2.5.0.dev20240904+cpu',
    domain=None,
    model_version=None,
>
graph(
    name=main_graph,
    inputs=(
        %"x"<FLOAT,[3,2]>
    ),
    outputs=(
        %"add"<FLOAT,[3]>,
        %"view_1"<FLOAT,[3,6]>
    ),
) {
     0 |  # node_Constant_0
          %"val_0"<?,?> ⬅️ ::Constant() {value=Tensor<INT64,[]>(array(0), name=None)}
     1 |  # node_Cast_1
          %"val_1"<?,?> ⬅️ ::Cast(%"val_0") {to=7}
     2 |  # node_Constant_2
          %"val_2"<?,?> ⬅️ ::Constant() {value_ints=[-1]}
     3 |  # node_Reshape_3
          %"val_3"<?,?> ⬅️ ::Reshape(%"val_1", %"val_2") {allowzero=0}
     4 |  # node_Constant_4
          %"val_4"<?,?> ⬅️ ::Constant() {value=Tensor<INT64,[]>(array(9223372036854775807), name=None)}
     5 |  # node_Cast_5
          %"val_5"<?,?> ⬅️ ::Cast(%"val_4") {to=7}
     6 |  # node_Constant_6
          %"val_6"<?,?> ⬅️ ::Constant() {value_ints=[-1]}
     7 |  # node_Reshape_7
          %"val_7"<?,?> ⬅️ ::Reshape(%"val_5", %"val_6") {allowzero=0}
     8 |  # node_Cast_8
          %"val_8"<?,?> ⬅️ ::Cast(%"val_0") {to=7}
     9 |  # node_Constant_9
          %"val_9"<?,?> ⬅️ ::Constant() {value_ints=[-1]}
    10 |  # node_Reshape_10
          %"val_10"<?,?> ⬅️ ::Reshape(%"val_8", %"val_9") {allowzero=0}
    11 |  # node_Constant_11
          %"val_11"<?,?> ⬅️ ::Constant() {value_ints=[1]}
    12 |  # node_Slice_12
          %"slice_1"<FLOAT,[3,2]> ⬅️ ::Slice(%"x", %"val_3", %"val_7", %"val_10", %"val_11")
    13 |  # node_Gather_13
          %"select"<FLOAT,[3]> ⬅️ ::Gather(%"slice_1", %"val_0") {axis=1}
    14 |  # node_Constant_14
          %"val_12"<?,?> ⬅️ ::Constant() {value=Tensor<INT64,[]>(array(2), name=None)}
    15 |  # node_Cast_15
          %"scalar_tensor_default"<FLOAT,[]> ⬅️ ::Cast(%"val_12") {to=FLOAT}
    16 |  # node_aten_pow_16
          %"pow_1"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_pow(%"select", %"scalar_tensor_default")
    17 |  # node_Cast_17
          %"val_13"<?,?> ⬅️ ::Cast(%"val_0") {to=7}
    18 |  # node_Constant_18
          %"val_14"<?,?> ⬅️ ::Constant() {value_ints=[-1]}
    19 |  # node_Reshape_19
          %"val_15"<?,?> ⬅️ ::Reshape(%"val_13", %"val_14") {allowzero=0}
    20 |  # node_Cast_20
          %"val_16"<?,?> ⬅️ ::Cast(%"val_4") {to=7}
    21 |  # node_Constant_21
          %"val_17"<?,?> ⬅️ ::Constant() {value_ints=[-1]}
    22 |  # node_Reshape_22
          %"val_18"<?,?> ⬅️ ::Reshape(%"val_16", %"val_17") {allowzero=0}
    23 |  # node_Cast_23
          %"val_19"<?,?> ⬅️ ::Cast(%"val_0") {to=7}
    24 |  # node_Constant_24
          %"val_20"<?,?> ⬅️ ::Constant() {value_ints=[-1]}
    25 |  # node_Reshape_25
          %"val_21"<?,?> ⬅️ ::Reshape(%"val_19", %"val_20") {allowzero=0}
    26 |  # node_Constant_26
          %"val_22"<?,?> ⬅️ ::Constant() {value_ints=[1]}
    27 |  # node_Slice_27
          %"slice_2"<FLOAT,[3,2]> ⬅️ ::Slice(%"x", %"val_15", %"val_18", %"val_21", %"val_22")
    28 |  # node_Constant_28
          %"val_23"<?,?> ⬅️ ::Constant() {value=Tensor<INT64,[]>(array(1), name=None)}
    29 |  # node_Gather_29
          %"select_1"<FLOAT,[3]> ⬅️ ::Gather(%"slice_2", %"val_23") {axis=1}
    30 |  # node_Add_30
          %"add"<FLOAT,[3]> ⬅️ ::Add(%"pow_1", %"select_1")
    31 |  # node_Identity_31
          %"detach"<FLOAT,[3,2]> ⬅️ ::Identity(%"x")
    32 |  # node_Identity_32
          %"detach_1"<FLOAT,[3,2]> ⬅️ ::Identity(%"detach")
    33 |  # node_Identity_33
          %"detach_2"<FLOAT,[3,2]> ⬅️ ::Identity(%"detach_1")
    34 |  # node_CastLike_34
          %"val_24"<?,?> ⬅️ ::CastLike(%"val_0", %"detach_2")
    35 |  # node_Shape_35
          %"val_25"<?,?> ⬅️ ::Shape(%"detach_2") {start=0}
    36 |  # node_Expand_36
          %"zeros_like"<FLOAT,[3,2]> ⬅️ ::Expand(%"val_24", %"val_25")
    37 |  # node_CastLike_37
          %"val_26"<?,?> ⬅️ ::CastLike(%"val_0", %"detach_2")
    38 |  # node_Shape_38
          %"val_27"<?,?> ⬅️ ::Shape(%"detach_2") {start=0}
    39 |  # node_Expand_39
          %"zeros_like_1"<FLOAT,[3,2]> ⬅️ ::Expand(%"val_26", %"val_27")
    40 |  # node_CastLike_40
          %"val_28"<?,?> ⬅️ ::CastLike(%"val_0", %"detach_2")
    41 |  # node_Shape_41
          %"val_29"<?,?> ⬅️ ::Shape(%"detach_2") {start=0}
    42 |  # node_Expand_42
          %"zeros_like_2"<FLOAT,[3,2]> ⬅️ ::Expand(%"val_28", %"val_29")
    43 |  # node_Constant_43
          %"val_30"<?,?> ⬅️ ::Constant() {value_ints=[0]}
    44 |  # node_Unsqueeze_44
          %"val_31"<?,?> ⬅️ ::Unsqueeze(%"zeros_like", %"val_30")
    45 |  # node_Constant_45
          %"val_32"<?,?> ⬅️ ::Constant() {value_ints=[0]}
    46 |  # node_Unsqueeze_46
          %"val_33"<?,?> ⬅️ ::Unsqueeze(%"zeros_like_1", %"val_32")
    47 |  # node_Constant_47
          %"val_34"<?,?> ⬅️ ::Constant() {value_ints=[0]}
    48 |  # node_Unsqueeze_48
          %"val_35"<?,?> ⬅️ ::Unsqueeze(%"zeros_like_2", %"val_34")
    49 |  # node_Concat_49
          %"stack"<FLOAT,[3,3,2]> ⬅️ ::Concat(%"val_31", %"val_33", %"val_35") {axis=0}
    50 |  # node_Constant_50
          %"val_36"<?,?> ⬅️ ::Constant() {value=Tensor<INT64,[3]>(array([3, 3, 2]), name=None)}
    51 |  # node_Cast_51
          %"val_37"<?,?> ⬅️ ::Cast(%"val_36") {to=7}
    52 |  # node_Reshape_52
          %"view"<FLOAT,[3,3,2]> ⬅️ ::Reshape(%"stack", %"val_37") {allowzero=0}
    53 |  # node_Identity_53
          %"detach_3"<FLOAT,[3,3,2]> ⬅️ ::Identity(%"view")
    54 |  # node_Identity_54
          %"detach_4"<FLOAT,[3,3,2]> ⬅️ ::Identity(%"detach_3")
    55 |  # node_Identity_55
          %"detach_5"<FLOAT,[3,3,2]> ⬅️ ::Identity(%"detach_4")
    56 |  # node_Constant_56
          %"val_38"<?,?> ⬅️ ::Constant() {value=Tensor<INT64,[2]>(array([3, 6]), name=None)}
    57 |  # node_Cast_57
          %"val_39"<?,?> ⬅️ ::Cast(%"val_38") {to=7}
    58 |  # node_Reshape_58
          %"view_1"<FLOAT,[3,6]> ⬅️ ::Reshape(%"detach_5", %"val_39") {allowzero=0}
    return %"add"<FLOAT,[3]>, %"view_1"<FLOAT,[3,6]>
}

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib::aten_pow(
    inputs=(
        %"self"<?,?>,
        %"exponent"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"return_val"<?,?> ⬅️ ::Pow(%"self", %"exponent")
    return %"return_val"<?,?>
},

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib.common::Rank(
    inputs=(
        %"input"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"tmp"<?,?> ⬅️ ::Shape(%"input")
    1 |  # n1
         %"return_val"<?,?> ⬅️ ::Size(%"tmp")
    return %"return_val"<?,?>
},

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib.common::IsScalar(
    inputs=(
        %"input"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"tmp"<?,?> ⬅️ ::Shape(%"input")
    1 |  # n1
         %"tmp_0"<?,?> ⬅️ ::Size(%"tmp")
    2 |  # n2
         %"tmp_1"<?,?> ⬅️ ::Constant() {value_int=0}
    3 |  # n3
         %"return_val"<?,?> ⬅️ ::Equal(%"tmp_0", %"tmp_1")
    return %"return_val"<?,?>
}

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib::aten_pow(
    inputs=(
        %"self"<?,?>,
        %"exponent"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"return_val"<?,?> ⬅️ ::Pow(%"self", %"exponent")
    return %"return_val"<?,?>
},

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib.common::Rank(
    inputs=(
        %"input"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"tmp"<?,?> ⬅️ ::Shape(%"input")
    1 |  # n1
         %"return_val"<?,?> ⬅️ ::Size(%"tmp")
    return %"return_val"<?,?>
},

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib.common::IsScalar(
    inputs=(
        %"input"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"tmp"<?,?> ⬅️ ::Shape(%"input")
    1 |  # n1
         %"tmp_0"<?,?> ⬅️ ::Size(%"tmp")
    2 |  # n2
         %"tmp_1"<?,?> ⬅️ ::Constant() {value_int=0}
    3 |  # n3
         %"return_val"<?,?> ⬅️ ::Equal(%"tmp_0", %"tmp_1")
    return %"return_val"<?,?>
}

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib::aten_pow(
    inputs=(
        %"self"<?,?>,
        %"exponent"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"return_val"<?,?> ⬅️ ::Pow(%"self", %"exponent")
    return %"return_val"<?,?>
},

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib.common::Rank(
    inputs=(
        %"input"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"tmp"<?,?> ⬅️ ::Shape(%"input")
    1 |  # n1
         %"return_val"<?,?> ⬅️ ::Size(%"tmp")
    return %"return_val"<?,?>
},

<
    opset_imports={'': 18},
>
def pkg.onnxscript.torch_lib.common::IsScalar(
    inputs=(
        %"input"<?,?>
    ),
    outputs=(
        %"return_val"<?,?>
    ),
) {
    0 |  # n0
         %"tmp"<?,?> ⬅️ ::Shape(%"input")
    1 |  # n1
         %"tmp_0"<?,?> ⬅️ ::Size(%"tmp")
    2 |  # n2
         %"tmp_1"<?,?> ⬅️ ::Constant() {value_int=0}
    3 |  # n3
         %"return_val"<?,?> ⬅️ ::Equal(%"tmp_0", %"tmp_1")
    return %"return_val"<?,?>
}
```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 0 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `x`: `TensorMetadata(shape=torch.Size([3, 2]), dtype=torch.float32, requires_grad=False, stride=(2, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `add`: `TensorMetadata(shape=torch.Size([3]), dtype=torch.float32, requires_grad=False, stride=(1,), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `view_1`: `TensorMetadata(shape=torch.Size([3, 6]), dtype=torch.float32, requires_grad=False, stride=(6, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

The FX graph has 21 nodes in total. Number of FX nodes per op:
- `placeholder`: 1
- `call_function`: 19
- `output`: 1


Of the call_function nodes, the counts of operators used are:

- `aten.detach.default`: 6
- `aten.zeros_like.default`: 3
- `aten.slice.Tensor`: 2
- `aten.select.int`: 2
- `aten.view.default`: 2
- `aten.scalar_tensor.default`: 1
- `aten.pow.Tensor_Tensor`: 1
- `aten.add.Tensor`: 1
- `aten.stack.default`: 1

## ONNX Conversion Information

All operators in the model have registered ONNX decompositions.

## Decomposition comparison

Ops exist only in the ExportedProgram before decomposition: `['aten.pow.Tensor_Scalar']`

Ops exist only in the ExportedProgram after decomposition: `['aten.pow.Tensor_Tensor', 'aten.scalar_tensor.default']`


## Verification results

`add`: `max_abs_diff=0.000000e+00`, `max_rel_diff=0.000000e+00`, `abs_diff_hist=torch.return_types.histogram(
hist=tensor([3., 0., 0., 0., 0., 0., 0., 0.]),
bin_edges=tensor([0.0000e+00, 1.0000e-06, 1.0000e-05, 1.0000e-04, 1.0000e-03, 1.0000e-02,
        1.0000e-01, 1.0000e+00, 1.0000e+01]))`, `rel_diff_hist=torch.return_types.histogram(
hist=tensor([3., 0., 0., 0., 0., 0., 0., 0.]),
bin_edges=tensor([0.0000e+00, 1.0000e-06, 1.0000e-05, 1.0000e-04, 1.0000e-03, 1.0000e-02,
        1.0000e-01, 1.0000e+00, 1.0000e+01]))`
`view_1`: `max_abs_diff=0.000000e+00`, `max_rel_diff=0.000000e+00`, `abs_diff_hist=torch.return_types.histogram(
hist=tensor([18.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
bin_edges=tensor([0.0000e+00, 1.0000e-06, 1.0000e-05, 1.0000e-04, 1.0000e-03, 1.0000e-02,
        1.0000e-01, 1.0000e+00, 1.0000e+01]))`, `rel_diff_hist=torch.return_types.histogram(
hist=tensor([18.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
bin_edges=tensor([0.0000e+00, 1.0000e-06, 1.0000e-05, 1.0000e-04, 1.0000e-03, 1.0000e-02,
        1.0000e-01, 1.0000e+00, 1.0000e+01]))`

**Comment by justinchuby** [comment]
Like @ezyang suggested there may be some backward operations ONNX does not support yet. Please feel free to open issues on those.
