### ISSUE TITLE
[export] Failed to trace HF Llama2 model

### ISSUE THREAD

**Issue by kwen2501** [pytorch/pytorch#128394]
### 🐛 Describe the bug

The following Llama2 program used to work, but failed recently.

### Error logs

```
Traceback (most recent call last):
  File "/data/users/kw2501/pytorch/torch/distributed/pipelining/_IR.py", line 1005, in _trace_with_export
    ep = torch.export.export(
         ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/export/__init__.py", line 174, in export
    return _export(
           ^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/export/_trace.py", line 944, in wrapper
    raise e
  File "/data/users/kw2501/pytorch/torch/export/_trace.py", line 927, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/export/exported_program.py", line 88, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/export/_trace.py", line 1532, in _export
    exported_program = ExportedProgram(
                       ^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/export/exported_program.py", line 245, in __init__
    self.verifier().check(self)
  File "/data/users/kw2501/pytorch/torch/_export/verifier.py", line 153, in check
    self._check_graph_module(ep.graph_module)
  File "/data/users/kw2501/pytorch/torch/_export/verifier.py", line 218, in _check_graph_module
    _check_val(node)
  File "/data/users/kw2501/pytorch/torch/_export/verifier.py", line 61, in _check_val
    raise SpecViolationError(f"Node.meta {node.name} is missing val field.")
torch._export.verifier.SpecViolationError: Node.meta _enter_autocast is missing val field.
```

### Minified repro

```
import argparse
import torch
from torch.export._trace import _export
from transformers import AutoModelForCausalLM, AutoTokenizer

parser = argparse.ArgumentParser()
parser.add_argument('--strict', action=argparse.BooleanOptionalAction)
parser.add_argument('--pre', action=argparse.BooleanOptionalAction)
args = parser.parse_args()
print(f"Strict mode: {args.strict}")
print(f"Pre-dispatch mode: {args.pre}")

# Grab the model
with torch.device("meta"):
    llama = AutoModelForCausalLM.from_pretrained(
        "meta-llama/Llama-2-7b-chat-hf"
    )
    llama.eval()

    tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
    tokenizer.pad_token = tokenizer.eos_token

    prompts = (
        "How do you", "I like to",
    )

    inputs = tokenizer(prompts, return_tensors="pt", padding=True)

if args.pre:
    ep = torch.export.export(
        llama,
        (inputs["input_ids"],),
        strict=args.strict,
    )
else:
    _export(
        llama,
        (inputs["input_ids"],),
        pre_dispatch=args.pre,
        strict=args.strict,
    )

```

$ python ep_llama.py --strict --pre
[Error log](https://gist.github.com/kwen2501/17ce9905b7a9541e8ebd79ed9bce8095)

$ python ep_llama.py --no-strict --pre
[Error log](https://gist.github.com/kwen2501/cf5a64ae05cb19e1a5e4f3c1675f76a6)

### Versions

pytorch nightly as of issue open time.

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @bdhirsh

**Comment by angelayi** [comment]
@tugsbayasgalan seems like a predispatch issue?

**Comment by tugsbayasgalan** [comment]
To unblock, you can try torch.export._trace._export(pre_dispatch=False).

**Comment by kwen2501** [comment]
Thanks @tugsbayasgalan . 
Tried pre_dispatch=False, but seems to hit the same error.
(You can use the repro above, but set flag `--no-pre`).

For example:
```
$ python ep_llama.py --no-pre --no-strict
Strict mode: False
Pre-dispatch mode: False
...
  File "/data/users/kw2501/transformers/src/transformers/models/llama/modeling_llama.py", line 644, in forward
    cos, sin = self.rotary_emb(value_states, position_ids)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/nn/modules/module.py", line 1552, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/nn/modules/module.py", line 1561, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/transformers/src/transformers/models/llama/modeling_llama.py", line 140, in forward
    with torch.autocast(device_type=device_type, enabled=False):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/kw2501/pytorch/torch/amp/autocast_mode.py", line 228, in __init__
    dtype = torch.get_autocast_dtype(device_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unsupported scalarType
```

**Comment by lessw2020** [comment]
Hit the same issue (627 nightlies) and talked with @kwen2501 about it.
This is becoming more urgent. 
This issue has been open for 3 weeks...would anyone be able to address this soon?
cc @tugsbayasgalan @avikchaudhuri

**Comment by lessw2020** [comment]
updating - the same error blocks tracing of Llama3-8B, so it's continuing to block on more models. 
```
[rank0]:[rank0]: Traceback (most recent call last):
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/distributed/pipelining/_IR.py", line 1007, in _trace_with_export
[rank0]:[rank0]:     ep = torch.export.export(
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/export/__init__.py", line 173, in export
[rank0]:[rank0]:     return _export(
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/export/_trace.py", line 1000, in wrapper
[rank0]:[rank0]:     raise e
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/export/_trace.py", line 983, in wrapper
[rank0]:[rank0]:     ep = fn(*args, **kwargs)
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/export/exported_program.py", line 98, in wrapper
[rank0]:[rank0]:     return fn(*args, **kwargs)
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/export/_trace.py", line 1949, in _export
[rank0]:[rank0]:     exported_program = ExportedProgram(
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/export/exported_program.py", line 662, in __init__
[rank0]:[rank0]:     self.verifier().check(self)
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/_export/verifier.py", line 154, in check
[rank0]:[rank0]:     self._check_graph_module(ep.graph_module)
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/_export/verifier.py", line 221, in _check_graph_module
[rank0]:[rank0]:     _check_val(node)
[rank0]:[rank0]:   File "/home/less/local/miniconda3/envs/inference/lib/python3.10/site-packages/torch/_export/verifier.py", line 62, in _check_val
[rank0]:[rank0]:     raise SpecViolationError(f"Node.meta {node.name} is missing val field.")
[rank0]:[rank0]: torch._export.verifier.SpecViolationError: Node.meta _enter_autocast is missing val field.
```

**Comment by angelayi** [comment]
Some investigations.. 

Loading and running with the `with torch.device(‘meta’)` does not work for me, it always runs into `RuntimeError: unsupported scalarType error`. Running the loaded model eagerly runs into the same issue `(llama(inputs[“input_ids”]))`, even if I tried not loading the inputs on meta device.

So removing that context, for the following code:
```
with torch.no_grad():
    ep = torch.export._trace._export(
        llama,
        (inputs["input_ids"],),
        pre_dispatch=pre_dispatch,
        strict=strict,
    )
```

The following combinations of flags worked for me: `(pre_dispatch=False, strict=False), (pre_dispatch=False, strict=False)`

On a [small test case](https://github.com/pytorch/pytorch/blob/a21d4363d2ef325c0808ed6a03f8def15c0abd7e/test/dynamo/test_ctx_manager.py#L464), I get the following graph:
```
class <lambda>(torch.nn.Module):
    def forward(self, x: "f32[1]"):
        rand: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        rand_1: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        rand_2: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)

        _to_copy: "bf16[8, 8]" = torch.ops.aten._to_copy.default(rand_1, dtype = torch.bfloat16);  rand_1 = None
        _to_copy_1: "bf16[8, 8]" = torch.ops.aten._to_copy.default(rand, dtype = torch.bfloat16);  rand = None
        mm: "bf16[8, 8]" = torch.ops.aten.mm.default(_to_copy_1, _to_copy);  _to_copy_1 = _to_copy = None
        _to_copy_2: "bf16[8, 8]" = torch.ops.aten._to_copy.default(rand_2, dtype = torch.bfloat16);  rand_2 = None
        mm_1: "bf16[8, 8]" = torch.ops.aten.mm.default(_to_copy_2, mm);  _to_copy_2 = mm = None
        return (mm_1,)
```

`(pre_dispatch=True, strict=True)` results in the SpecViolationError, and produces following graph:
```
class <lambda>(torch.nn.Module):
    def forward(self, x: "f32[1]"):
        rand: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        rand_1: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        rand_2: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        
        _enter_autocast = torch.amp.autocast_mode._enter_autocast('cuda', torch.bfloat16, True, None)
        
        mm: "f32[8, 8]" = torch.ops.aten.mm.default(rand, rand_1);  rand = rand_1 = None
        mm_1: "f32[8, 8]" = torch.ops.aten.mm.default(rand_2, mm);  rand_2 = mm = None
        
        _exit_autocast = torch.amp.autocast_mode._exit_autocast(_enter_autocast);  _enter_autocast = None
        return (mm_1,)
```

`(pre_dispatch=True, strict=False)` passes, resulting in the following graph, but this seems to be an incorrect behavior:
```
class <lambda>(torch.nn.Module):
    def forward(self, x: "f32[1]"):
        rand: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        rand_1: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        rand_2: "f32[8, 8]" = torch.ops.aten.rand.default([8, 8], device = device(type='cuda'), pin_memory = False)
        
        mm: "bf16[8, 8]" = torch.ops.aten.mm.default(rand, rand_1);  rand = rand_1 = None
        mm_1: "bf16[8, 8]" = torch.ops.aten.mm.default(rand_2, mm);  rand_2 = mm = None
        return (mm_1,)
```

Chatted with @bdhirsh and we feel that the best solution is to turn the autocast context manager into a HOP, like what we do for `no_grad`. cc @ydwu4 @zou3519

**Comment by zou3519** [comment]
> Chatted with @bdhirsh and we feel that the best solution is to turn the autocast context manager into a HOP, like what we do for no_grad. cc @ydwu4 @zou3519

What exactly is the problem here?

**Comment by angelayi** [comment]
> What exactly is the problem here?

If there's an autocast context manager, the predispatch (strict) graph looks something like:
```
class <lambda>(torch.nn.Module):
    def forward(self, x: "f32[1]"):
        ...
        _enter_autocast = torch.amp.autocast_mode._enter_autocast('cuda', torch.bfloat16, True, None)
        mm: "f32[8, 8]" = torch.ops.aten.mm.default(rand, rand_1);  rand = rand_1 = None
        _exit_autocast = torch.amp.autocast_mode._exit_autocast(_enter_autocast);  _enter_autocast = None
        return (mm_1,)
```

But the operator `torch.amp.autocast_mode._enter_autocast` is not a valid ATen op. And we were thinking that the way we handle the autocast context manager should be the same way which we handle the no_grad HOP.

Separately, the non-strict predispatch graph seems to be incorrect, since it's missing the `_to_copy(dtype=torch.bfloat16)`, but maybe the context manager above will fix this.

**Comment by angelayi** [comment]
For note keeping, the regression is due to https://github.com/huggingface/transformers/pull/29285/ which added the autocast context in [transformers/modeling_llama.py](https://github.com/huggingface/transformers/blob/080e14b24c8923e4bc18fcd54010fc7396c67bc0/src/transformers/models/llama/modeling_llama.py#L115).

**Comment by zou3519** [comment]
Do we have a problem with the predispatch=False case? I agree in the predispatch=True case we can use a HOP to represent the context manager

**Comment by angelayi** [comment]
No, predispatch=False seems fine to me

**Comment by kwen2501** [comment]
Thanks @albanD for suggesting fake tensor mode in https://github.com/pytorch/pytorch/issues/130067.

The following script seems to work for me for export the current Llama2 model (with `autocast`).

```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
from transformers import AutoModelForCausalLM, AutoTokenizer

# Grab the model
with torch.device("meta"):
    llama = AutoModelForCausalLM.from_pretrained(
        "meta-llama/Llama-2-7b-chat-hf"
    )
    llama.eval()

fake_mode = FakeTensorMode(allow_non_fake_inputs=True)
with fake_mode:
    llama.to_empty(device="cpu")

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
tokenizer.pad_token = tokenizer.eos_token
prompts = (
    "How do you", "I like to",
)

inputs = tokenizer(prompts, return_tensors="pt", padding=True)
real_ids = inputs["input_ids"]
fake_ids = fake_mode.from_tensor(real_ids)

print(fake_ids.device)
print(llama)

ep = torch.export.export(
    llama,
    (fake_ids,),
)

ep.module().print_readable()
```

**Comment by yushangdi** [comment]
With the changes in #131914, the code below can be exported (we convert autocast to HOO as discussed above). `with torch.device("meta")` still doesn't work (see #130067).

```python
import torch
from torch.export._trace import _export
from transformers import AutoModelForCausalLM, AutoTokenizer


# Grab the model
# with torch.device("meta"):
llama = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Llama-2-7b-chat-hf"
)
llama.eval()

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
tokenizer.pad_token = tokenizer.eos_token

prompts = (
    "How do you", "I like to",
)

inputs = tokenizer(prompts, return_tensors="pt", padding=True)


ep = torch.export.export(
    llama,
    (inputs["input_ids"],),
    strict=True,
)

```

cc @angelayi
