### ISSUE TITLE
torch.compile() AssertionError: target must be of GPUTarget type

### ISSUE THREAD

**Issue by wookjeHan** [pytorch/pytorch#128357]
### 🐛 Describe the bug

When I tried to use `torch.compile` for a forward function of the module,
```
@torch.compile(mode="reduce-overhead")
def forward(
    self,
    x: torch.Tensor,
    ....
)
```
Following error occurred.

 0%|                                                                                                                                                           | 0/1082 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py:623: UserWarning: Traceback (most recent call last):
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 595, in identify_mutated_tensors
    ttir_module, ordered_tensor_names = generate_ttir(kernel, kwargs)
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 154, in generate_ttir
    backend = get_backend()
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 148, in get_backend
    from triton.compiler.backends.cuda import CUDABackend
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/backends/cuda.py", line 3, in <module>
    from ..._C.libtriton.triton import ClusterInfo, get_num_warps, TMAInfos, translate_triton_gpu_to_llvmir, get_shared_memory_size, translate_llvmir_to_ptx, compile_ptx_to_cubin, add_external_libs
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
ModuleNotFoundError: No module named 'triton._C.libtriton.triton'; 'triton._C.libtriton' is not a package

  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py:623: UserWarning: Traceback (most recent call last):
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 595, in identify_mutated_tensors
    ttir_module, ordered_tensor_names = generate_ttir(kernel, kwargs)
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 154, in generate_ttir
    backend = get_backend()
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 148, in get_backend
    from triton.compiler.backends.cuda import CUDABackend
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/backends/cuda.py", line 3, in <module>
    from ..._C.libtriton.triton import ClusterInfo, get_num_warps, TMAInfos, translate_triton_gpu_to_llvmir, get_shared_memory_size, translate_llvmir_to_ptx, compile_ptx_to_cubin, add_external_libs
Encountered an exception in identify_mutated_tensors, assuming every input is mutated:
ModuleNotFoundError: No module named 'triton._C.libtriton.triton'; 'triton._C.libtriton' is not a package

  warnings.warn(
  0%|                                                                                                                                                           | 0/1082 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/gr-optimizations/train.py", line 573, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/gr-optimizations/train.py", line 571, in main
    mp_train_fn(0, world_size, FLAGS.master_port, FLAGS.gin_config_file)
  File "/home/gr-optimizations/train.py", line 559, in mp_train_fn
    train_fn(rank, world_size, master_port)
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.10/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/gr-optimizations/train.py", line 504, in train_fn
    eval_dict, infer_time = eval_metrics_v2_from_tensors(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/gr-optimizations/data/eval.py", line 105, in eval_metrics_v2_from_tensors
    shared_input_embeddings = model.encode(
  File "/home/gr-optimizations/modeling/sequential/hstu_custom.py", line 801, in encode
    return self._encode(
  File "/home/gr-optimizations/modeling/sequential/hstu_custom.py", line 764, in _encode
    encoded_seq_embeddings, cache_states = self.generate_user_embeddings(
  File "/home/gr-optimizations/modeling/sequential/hstu_custom.py", line 699, in generate_user_embeddings
    user_embeddings, cached_states = self._hstu(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gr-optimizations/modeling/sequential/hstu_custom.py", line 545, in forward
    jagged_x, cache_states = self.jagged_forward(
  File "/home/gr-optimizations/modeling/sequential/hstu_custom.py", line 508, in jagged_forward
    x, cache_states_i = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 991, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1168, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1241, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1222, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1102, in compile_fx
    return compile_fx(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1257, in fw_compiler_base
    return inner_compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 438, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 714, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1307, in compile_to_fn
    return self.compile_to_module().call
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1254, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2160, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/6d/c6daho7sz2aa5cupjy6ka4l4vdswynqhfi4g6wjnipmorwblzsjk.py", line 766, in <module>
    async_compile.wait(globals())
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2715, in wait
    scope[key] = result.result()
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2522, in result
    self.future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: target must be of GPUTarget type

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

  In call to configurable 'train_fn' (<function train_fn at 0x7fa756fab010>)

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.16.0
[pip3] optree==0.11.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a2
[pip3] torch==2.3.0+cu121
[pip3] torch-tensorrt==2.4.0a0
[pip3] torchaudio==2.3.0+cu121
[pip3] torchvision==0.18.0+cu121
[pip3] triton==2.3.0
[pip3] triton-nightly==3.0.0.post20240424212437

cc @ezyang @bdhirsh @anijain2305 @chauhang

**Comment by eellison** [comment]
cc @oulgen, related to custom triton kernels.

**Comment by oulgen** [comment]
@wookjeHan please provide a repro

**Comment by oulgen** [comment]
Looking at your packages you have 3 different triton versions, triton, triton-nightly and pytorch-triton. Please remove all except for `pytorch-triton` and try again

**Comment by eellison** [comment]
Yea, you might have a local build issue. Try creating a new conda env and installing nightly ? 


Apparently `Encountered an exception in identify_mutated_tensors, assuming every input is mutated` is benign, unrelated to custom triton kernels.

**Comment by wookjeHan** [comment]
Thanks for your kind comments @oulgen , @eellison 
Could you guys please let me know which version should I keep for triton?
Should I leave `pytorch-triton` or should I leave `triton-nightly`?

Best,

**Comment by oulgen** [comment]
Only keep `pytorch-triton`

**Comment by wookjeHan** [comment]
Thanks for your kind comment!

After removing all except `pytorch-triton`,

`ModuleNotFoundError 'triton.language.extra.cuda' ` occurred.
```
Traceback (most recent call last):
  File "/home/gr-optimizations/ops/triton/triton_ragged_hstu_attention.py", line 32, in <module>
    from triton.language.extra.cuda.libdevice import fast_dividef
ModuleNotFoundError: No module named 'triton.language.extra.cuda'

```
I think this is somewhat weird as `pytorch-triton` is installed as below.

```
Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.16.0
[pip3] optree==0.11.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a2
[pip3] torch==2.3.0+cu121
[pip3] torch-tensorrt==2.4.0a0
[pip3] torchaudio==2.3.0+cu121
[pip3] torchvision==0.18.0+cu121
[conda] Could not collect
```
Do you have any idea?

Best,

**Comment by oulgen** [comment]
I am assuming you're a Meta employee since you are accessing `triton_ragged_hstu_attention.py`. There is a try-catch around that code, did you remove that?

**Comment by wookjeHan** [comment]
Thanks for your help oulgen,
No, I am not a Meta employee, I was just exploring this [code base](https://github.com/facebookresearch/generative-recommenders).

After adding try-catch clause, I am still having ModuleNotFoundError: `No module named 'triton.language.math'` issue.

Will making a new environment from the scratch be a better way to start?

**Comment by oulgen** [comment]
Ah I did not realize this code was open source, my bad. I suspect the problem is the version of triton that generative-recommenders repo requires is not compatible with the one that ships with pytorch.

**Comment by wookjeHan** [comment]
Thanks for your kind help oulgen!
I will reach out the author of generative-recommenders for more detail.

By the way, could you please let me know what would be the best practice to compile the `torch.nn.Module` (A) whose `forward` call another module (B)'s `forward`?

It seems to me that torch.compile(A) does not work so I was wondering whether I should wrap B itself with torch.compile or B's forward function with torch.compile

Best,
