### ISSUE TITLE
[inductor][cpu] AMP models static/dynamic default/CPP wrapper accuracy/performance crash in 2024-06-08 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#128507]
### 🐛 Describe the bug

<p> AMP models static/dynamic default/CPP wrapper accuracy/performance crash</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_sage</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>basic_gnn_sage, AssertionError:</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>deit_base_distilled_patch16_224</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>deit_base_distilled_patch16_224, AssertionError:</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>levit_128</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>levit_128, AssertionError:</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>volo_d1_224</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>volo_d1_224, AssertionError:</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_sage</td>
      <td>single</td>
      <td>X</td>
      <td>N/A</td>
      <td>basic_gnn_sage, AssertionError:</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>deit_base_distilled_patch16_224</td>
      <td>single</td>
      <td>X</td>
      <td>N/A</td>
      <td>deit_base_distilled_patch16_224, AssertionError:</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>levit_128</td>
      <td>single</td>
      <td>X</td>
      <td>N/A</td>
      <td>levit_128, AssertionError:</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>volo_d1_224</td>
      <td>single</td>
      <td>X</td>
      <td>N/A</td>
      <td>volo_d1_224, AssertionError:</td>
    </tr>
  </tbody>

</table>

```
loading model: 0it [00:01, ?it/s]cpu  eval  basic_gnn_sage                     

ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2742, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 948, in __call__
    result = self._inner_convert(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/workspace/pytorch/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/workspace/pytorch/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 230, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2451, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2642, in RETURN_VALUE
    self._return(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2627, in _return
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1098, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1318, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 230, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1409, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1390, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/__init__.py", line 1803, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1504, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 69, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 954, in aot_module_simplified
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 230, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 687, in create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 168, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1190, in fw_compiler_freezing
    opt_model, preserved_arg_indices = freeze(
  File "/workspace/pytorch/torch/_inductor/freezing.py", line 110, in freeze
    freezing_passes(aot_autograd_gm, aot_example_inputs)
  File "/workspace/pytorch/torch/_inductor/fx_passes/freezing_patterns.py", line 67, in freezing_passes
    pattern.apply(gm.graph)  # type: ignore[arg-type]
  File "/workspace/pytorch/torch/_inductor/pattern_matcher.py", line 1698, in apply
    if is_match(m) and entry.extra_check(m):
  File "/workspace/pytorch/torch/_inductor/fx_passes/mkldnn_fusion.py", line 793, in is_linear_add_bias
    assert packed_weight_node.name == "_reorder_linear_weight"
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: 
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>d6015d42</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>f681e3689b857b8811f19d60d439bfb3fb2dd2d3</td>
      <td>main</td>
      <td>c19ad112f65ab88af3eeb319dda0675c076b0b67</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+1980f8a</td>
      <td>main</td>
      <td>2.2.0a0+1980f8a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple/single inference accuracy/performance **suite** **name** amp first dynamic/static default/cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/dbf39a6e6323419c95d989949cefc82b5c2e027c
[torchbench-basic_gnn_sage-inference-amp-static-default-multiple-accuracy-crash_guilty_commit.log](https://github.com/user-attachments/files/15806477/torchbench-basic_gnn_sage-inference-amp-static-default-multiple-accuracy-crash_guilty_commit.log)
cc @ezyang @anijain2305 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
Should be same as https://github.com/pytorch/pytorch/issues/128287

**Comment by leslie-fang-intel** [comment]
The fix: https://github.com/pytorch/pytorch/pull/128473 should already landed, @zxd1997066 please help to check.

**Comment by zxd1997066** [comment]
This issue is fixed in the latest report.
