### ISSUE TITLE
Dynamo graph breaks when passing a constant value to a nn module initialized within a function

### ISSUE THREAD

**Issue by jamesjwu** [pytorch/pytorch#128556]
### 🐛 Describe the bug

```
import torch
class MyMod(torch.nn.Module):
    def __init__(self, constant):
        super().__init__()
        self.register_buffer("buf", torch.randn([2,2]))
        self.param = torch.nn.Parameter(torch.randn([2,2]))
        self.constant = constant

    def forward(self, x):
        return self.param + self.constant + self.buf


def fn(x):
	return MyMod(torch.ones((2, 2)))(x)

f = torch.compile(backend="eager", fullgraph=True)(fn)
print(f(torch.randn([2,2])))
```

Fails with Unsupported. If you remove the buffer:
```
import torch
class MyMod(torch.nn.Module):
    def __init__(self, constant):
        super().__init__()
        self.param = torch.nn.Parameter(torch.randn([2,2]))
        self.constant = constant

    def forward(self, x):
        return self.param + self.constant


def fn(x):
	return MyMod(torch.ones((2, 2)))(x)

f = torch.compile(backend="eager", fullgraph=True)(fn)
print(f(torch.randn([2,2])))
```
It also fails with a different message. Both error messages are listed below,

### Error logs

```
Traceback (most recent call last):
  File "/home/jjwu/test.py", line 17, in <module>
    print(f(torch.randn([2,2])))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/data/users/jjwu/a/pytorch/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/data/users/jjwu/a/pytorch/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/utils.py", line 230, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2462, in run
    super().run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1470, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/user_defined.py", line 380, in call_function
    var.call_method(tx, "__init__", args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/nn_module.py", line 960, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/user_defined.py", line 630, in call_method
    return UserMethodVariable(method, self, source=source).call_function(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 345, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 294, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 91, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 760, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2677, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2793, in inline_call_
    tracer.run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1470, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 345, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 294, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 91, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 760, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2677, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2793, in inline_call_
    tracer.run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1470, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/misc.py", line 698, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/dicts.py", line 453, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/dicts.py", line 312, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/base.py", line 320, in call_method
    unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/exc.py", line 221, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method SetVariable() discard [ConstantVariable()] {}
```

Without the buffer:
```
Traceback (most recent call last):
  File "/home/jjwu/test.py", line 16, in <module>
    print(f(torch.randn([2,2])))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/data/users/jjwu/a/pytorch/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/data/users/jjwu/a/pytorch/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/utils.py", line 230, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2462, in run
    super().run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1470, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/user_defined.py", line 380, in call_function
    var.call_method(tx, "__init__", args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/nn_module.py", line 960, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/user_defined.py", line 630, in call_method
    return UserMethodVariable(method, self, source=source).call_function(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 345, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 294, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/functions.py", line 91, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 760, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2677, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2793, in inline_call_
    tracer.run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1470, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/torch.py", line 723, in call_function
    result = special_handler(self, tx, *args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/torch.py", line 518, in handle_parameter
    return self.call_nn_parameter(tx, *args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/variables/torch.py", line 879, in call_nn_parameter
    unimplemented("Workaround for issues with nn_parameter construction")
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/exc.py", line 221, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: Workaround for issues with nn_parameter construction
```

### Versions

```
PyTorch version: 2.4.0a0+git0fbff48
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.34

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk12_zion_rc2_11583_g0bef9520ca2b-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100
GPU 4: NVIDIA H100
GPU 5: NVIDIA H100
GPU 6: NVIDIA H100
GPU 7: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.9.2
/usr/lib64/libcudnn_adv_infer.so.8.9.2
/usr/lib64/libcudnn_adv_train.so.8.9.2
/usr/lib64/libcudnn_cnn_infer.so.8.9.2
/usr/lib64/libcudnn_cnn_train.so.8.9.2
/usr/lib64/libcudnn_ops_infer.so.8.9.2
/usr/lib64/libcudnn_ops_train.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          384
On-line CPU(s) list:             0-383
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              2
Core(s) per socket:              96
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU(s) scaling MHz:              100%
CPU max MHz:                     2400.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4792.72
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                  AMD-V
L1d cache:                       6 MiB (192 instances)
L1i cache:                       6 MiB (192 instances)
L2 cache:                        192 MiB (192 instances)
L3 cache:                        768 MiB (24 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-95,192-287
NUMA node1 CPU(s):               96-191,288-383
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable, IBPB: conditional, IBRS_FW, STIBP: always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.6.0
[pip3] CoCa-pytorch==0.1.0
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.4.2
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.9.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] onnx==1.15.0
[pip3] open-clip-torch==2.24.0
[pip3] optree==0.11.0
[pip3] pytorch-labs-segment-anything-fast==0.2
[pip3] pytorch-triton==3.0.0+45fff310c8
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.3.3
[pip3] torch==2.4.0a0+git0fbff48
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torchao==0.0.3
[pip3] torchdata==0.7.1a0+473588c
[pip3] torchmetrics==1.0.3
[pip3] torchmultimodal==0.1.0b0
[pip3] torchrec==0.7.0a0+001fa62
[pip3] torchtext==0.17.0a0+656a3b4
[pip3] vector_quantize_pytorch==1.14.1
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl
[conda] clip-anytorch             2.6.0                    pypi_0    pypi
[conda] coca-pytorch              0.1.0                    pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.4.2                    pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-include               2023.1.0         h06a4308_46344
[conda] mkl-service               2.4.0           py310h5eee18b_1
[conda] mkl_fft                   1.3.8           py310h5eee18b_0
[conda] mkl_random                1.2.4           py310hdb19cb5_0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] open-clip-torch           2.24.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch-labs-segment-anything-fast 0.2                      pypi_0    pypi
[conda] pytorch-triton            3.0.0+45fff310c8          pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.3.3                    pypi_0    pypi
[conda] torch                     2.4.0a0+git0fbff48           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchao                   0.0.3                    pypi_0    pypi
[conda] torchdata                 0.7.1a0+473588c          pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchmetrics              1.0.3                    pypi_0    pypi
[conda] torchmultimodal           0.1.0b0                  pypi_0    pypi
[conda] torchrec                  0.7.0a0+001fa62           dev_0    <develop>
[conda] torchtext                 0.17.0a0+656a3b4           dev_0    <develop>
[conda] vector-quantize-pytorch   1.14.1                   pypi_0    pypi
```

**Comment by ezyang** [comment]
This is also affecting `pytest torchrec/distributed/tests/test_pt2_multiprocess.py::TestPt2Train::test_compile_multiprocess`

**Comment by StrongerXi** [comment]
Doing old issue scrubbing; this still repros on main 0c8028e; @anijain2305 is this still on your plate?
