### ISSUE TITLE
TestAdadelta.test_adadelta flaky on CI

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12851]
```
Oct 18 11:00:36 =================================== FAILURES ===================================
Oct 18 11:00:36 __________________________ TestAdadelta.test_adadelta __________________________
Oct 18 11:00:36 
Oct 18 11:00:36 self = <caffe2.python.operator_test.adadelta_test.TestAdadelta testMethod=test_adadelta>
Oct 18 11:00:36 args = (), kwargs = {}
Oct 18 11:00:36 
Oct 18 11:00:36     def func(self, *args, **kwargs):
Oct 18 11:00:36         self.should_serialize = True
Oct 18 11:00:36         fixed_seed_func(self, *args, **kwargs)
Oct 18 11:00:36         self.should_serialize = False
Oct 18 11:00:36 >       hyp_func(self, *args, **kwargs)
Oct 18 11:00:36 
Oct 18 11:00:36 /usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/serialized_test/serialized_test_util.py:37: 
Oct 18 11:00:36 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Oct 18 11:00:36 
Oct 18 11:00:36 self = <caffe2.python.operator_test.adadelta_test.TestAdadelta testMethod=test_adadelta>
Oct 18 11:00:36 
Oct 18 11:00:36     @serial.given(inputs=hu.tensors(n=4),
Oct 18 11:00:36 >          lr=st.floats(min_value=0.01, max_value=0.99,
Oct 18 11:00:36                         allow_nan=False, allow_infinity=False),
Oct 18 11:00:36            epsilon=st.floats(min_value=0.01, max_value=0.99,
Oct 18 11:00:36                              allow_nan=False, allow_infinity=False),
Oct 18 11:00:36            decay=st.floats(min_value=0.01, max_value=0.99,
Oct 18 11:00:36                              allow_nan=False, allow_infinity=False),
Oct 18 11:00:36            **hu.gcs)
Oct 18 11:00:36     def test_adadelta(self, inputs, lr, epsilon, decay, gc, dc):
Oct 18 11:00:36 E   MultipleFailures: Hypothesis found 2 distinct failures.
Oct 18 11:00:36 
Oct 18 11:00:36 /usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/adadelta_test.py:49: MultipleFailures
```

Example failure:

```

Oct 18 11:00:36 Trying example: test_adadelta(self=<caffe2.python.operator_test.adadelta_test.TestAdadelta testMethod=test_adadelta>, inputs=[array([[[[-0.974813, -0.151351]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.402256,  0.939587]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.974813, -0.974813]]],
Oct 18 11:00:36  
Oct 18 11:00:36  
Oct 18 11:00:36         [[[-0.974813, -0.974813]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.279054, -0.974813]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.974813, -0.974813]]]], dtype=float32),
Oct 18 11:00:36  array([[[[ 0.543178,  0.543178]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.707815,  0.543178]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.684333, -0.488988]]],
Oct 18 11:00:36  
Oct 18 11:00:36  
Oct 18 11:00:36         [[[ 0.543178, -0.314111]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.543178, -0.308272]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.543178,  0.543178]]]], dtype=float32),
Oct 18 11:00:36  array([[[[-0.3243  , -0.3243  ]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.3243  , -0.3243  ]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.3243  ,  0.592383]]],
Oct 18 11:00:36  
Oct 18 11:00:36  
Oct 18 11:00:36         [[[ 0.739015, -0.29517 ]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.3243  , -0.3243  ]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.3243  , -0.3243  ]]]], dtype=float32),
Oct 18 11:00:36  array([[[[ 0.561077,  0.561077]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.561077,  0.561077]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.561077, -0.528247]]],
Oct 18 11:00:36  
Oct 18 11:00:36  
Oct 18 11:00:36         [[[ 0.561077,  0.561077]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[-0.841942,  0.561077]],
Oct 18 11:00:36  
Oct 18 11:00:36          [[ 0.561077,  0.561077]]]], dtype=float32)], lr=0.32685703182675524, epsilon=0.3714145407871429, decay=0.686572461743667, gc=, dc=[])
Oct 18 11:00:36 Traceback (most recent call last):
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 558, in evaluate_test_data
Oct 18 11:00:36     result = self.execute(data)
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 525, in execute
Oct 18 11:00:36     result = self.test_runner(data, run)
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/hypothesis/executors.py", line 58, in default_new_style_executor
Oct 18 11:00:36     return function(data)
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 523, in run
Oct 18 11:00:36     return test(*args, **kwargs)
Oct 18 11:00:36   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/adadelta_test.py", line 49, in test_adadelta
Oct 18 11:00:36     lr=st.floats(min_value=0.01, max_value=0.99,
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 470, in test
Oct 18 11:00:36     result = self.test(*args, **kwargs)
Oct 18 11:00:36   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/adadelta_test.py", line 72, in test_adadelta
Oct 18 11:00:36     functools.partial(self.ref_adadelta, epsilon=epsilon, decay=decay))
Oct 18 11:00:36   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/serialized_test/serialized_test_util.py", line 224, in assertReferenceChecks
Oct 18 11:00:36     outputs_to_check,
Oct 18 11:00:36   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py", line 612, in assertReferenceChecks
Oct 18 11:00:36     output_blob_name,
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/numpy/testing/_private/utils.py", line 1452, in assert_allclose
Oct 18 11:00:36     verbose=verbose, header=header, equal_nan=equal_nan)
Oct 18 11:00:36   File "/usr/local/lib/python2.7/dist-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
Oct 18 11:00:36     raise AssertionError(msg)
Oct 18 11:00:36 AssertionError: 
Oct 18 11:00:36 Not equal to tolerance rtol=0.0001, atol=0.0001
Oct 18 11:00:36 Output moment_delta is not matching the reference
Oct 18 11:00:36 (mismatch 8.33333333333%)
Oct 18 11:00:36  x: array([-0.217141, -0.217141, -0.217793, -0.217141, 19.181126,  1.091199,
Oct 18 11:00:36         0.637355, -0.173087, -0.211825, -0.204667, -0.217141, -0.217141],
Oct 18 11:00:36       dtype=float32)
Oct 18 11:00:36  y: array([-0.217141, -0.217141, -0.217793, -0.217141, 19.18354 ,  1.091199,
Oct 18 11:00:36         0.637355, -0.173087, -0.211825, -0.204667, -0.217141, -0.217141],
Oct 18 11:00:36       dtype=float32)
Oct 18 11:00:36 
```

Full log https://circleci.com/gh/pytorch/pytorch/80749?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mrshenli** [comment]
Hit test failure on `test_adadelta` too, but seems to be a different error.

```
17:59:34 ======================================================================
17:59:34 FAIL: test_adadelta (test_optim.TestOptim)
17:59:34 ----------------------------------------------------------------------
17:59:34 Traceback (most recent call last):
17:59:34   File "/var/lib/jenkins/workspace/test/test_optim.py", line 330, in test_adadelta
17:59:34     lambda weight, bias: optim.Adadelta([weight, bias])
17:59:34   File "/var/lib/jenkins/workspace/test/test_optim.py", line 225, in _test_basic_cases
17:59:34     scheduler_constructors
17:59:34   File "/var/lib/jenkins/workspace/test/test_optim.py", line 120, in _test_basic_cases_template
17:59:34     self.assertLess(fn().item(), initial_value)
17:59:34 AssertionError: nan not less than nan
17:59:34 
17:59:34 ----------------------------------------------------------------------
17:59:34 Ran 48 tests in 168.944s
17:59:34 
17:59:34 FAILED (failures=1)
17:59:34 Traceback (most recent call last):
17:59:34   File "test/run_test.py", line 458, in <module>
17:59:34     main()
17:59:34   File "test/run_test.py", line 450, in main
17:59:34     raise RuntimeError(message)
17:59:34 RuntimeError: test_optim failed!
17:59:35 =================== sccache compilation log ===================
```

**Comment by Micket** [comment]
Is this test still known to be flaky? I'm getting currently getting bit by
```
======================================================================
FAIL: test_adadelta (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/tmp.93265/eb-m5y07fe9/tmpqhvzjk9z/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 439, in wrapper
    fn(*args, **kwargs)
  File "test_optim.py", line 465, in test_adadelta
    self._test_basic_cases(
  File "test_optim.py", line 204, in _test_basic_cases
    self._test_state_dict(
  File "test_optim.py", line 192, in _test_state_dict
    self.assertEqual(weight, weight_cuda)
  File "/local/tmp.93265/eb-m5y07fe9/tmpqhvzjk9z/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1355, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 2 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.2218952178955078e-05 (-0.7925083041191101 vs. -0.7924960851669312), which occurred at index (9, 1).
```
So, a bit over the tolerances.
