### ISSUE TITLE
DISABLED test_segfault (__main__.TestDataLoader)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#128551]
Platforms: linux

Failing flakily 
ex https://hud.pytorch.org/pytorch/pytorch/commit/9e39c62908de4831439397e30e9102f63c338682
https://github.com/pytorch/pytorch/actions/runs/9486063148/job/26141144791

First bad I can find is 2e065f2486e92d8b89b058f1d561bb801f226179
```

2024-06-12T17:42:24.9678385Z   class TestProperExitIterableDataset(IterableDataset):
2024-06-12T17:42:24.9679987Z /var/lib/jenkins/workspace/test/test_dataloader.py:1010: PytestCollectionWarning: cannot collect test class 'TestWorkerInfoDataset' because it has a __init__ constructor (from: test/test_dataloader.py)
2024-06-12T17:42:24.9681391Z   class TestWorkerInfoDataset(SynchronizedDataset):
2024-06-12T17:42:24.9682971Z /var/lib/jenkins/workspace/test/test_dataloader.py:1122: PytestCollectionWarning: cannot collect test class 'TestMultiEpochDataset' because it has a __init__ constructor (from: test/test_dataloader.py)
2024-06-12T17:42:24.9684336Z   class TestMultiEpochDataset(IterableDataset):
2024-06-12T17:42:24.9685900Z /var/lib/jenkins/workspace/test/test_dataloader.py:3374: PytestCollectionWarning: cannot collect test class 'TestWorkerQueueDataset' because it has a __init__ constructor (from: test/test_dataloader.py)
2024-06-12T17:42:24.9687262Z   class TestWorkerQueueDataset(Dataset):
2024-06-12T17:42:24.9687744Z collected 178 items / 75 deselected / 103 selected
2024-06-12T17:42:24.9688249Z stepcurrent: skipping 75 already run items.
2024-06-12T17:42:24.9688694Z Running 103 items in this shard
2024-06-12T17:42:24.9688944Z 
2024-06-12T17:42:24.9690136Z test_dataloader.py::TestDataLoader::test_segfault /opt/conda/envs/py_3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 42 leaked semaphore objects to clean up at shutdown
2024-06-12T17:42:24.9691762Z   warnings.warn('resource_tracker: There appear to be %d '
2024-06-12T17:42:24.9692352Z ('RERUN', {'yellow': True}) [62.8826s] [  0%]
2024-06-12T17:42:24.9693160Z test_dataloader.py::TestDataLoader::test_segfault ('RERUN', {'yellow': True}) [61.5954s] [  0%]
2024-06-12T17:42:24.9694124Z test_dataloader.py::TestDataLoader::test_segfault FAILED [62.0443s]      [  0%]
2024-06-12T17:42:24.9694632Z 
2024-06-12T17:42:24.9694814Z ==================================== RERUNS ====================================
2024-06-12T17:42:24.9695479Z _________________________ TestDataLoader.test_segfault _________________________
2024-06-12T17:42:24.9696049Z Traceback (most recent call last):
2024-06-12T17:42:24.9696707Z   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 1380, in test_segfault
2024-06-12T17:42:24.9697405Z     self.assertFalse(p.is_alive())
2024-06-12T17:42:24.9698066Z   File "/opt/conda/envs/py_3.11/lib/python3.11/unittest/case.py", line 709, in assertFalse
2024-06-12T17:42:24.9698753Z     raise self.failureException(msg)
2024-06-12T17:42:24.9699170Z AssertionError: True is not false
2024-06-12T17:42:24.9699429Z 
2024-06-12T17:42:24.9699696Z To execute this test, run the following from the base repo dir:
2024-06-12T17:42:24.9700636Z     PYTORCH_TEST_WITH_DYNAMO=1 python test/test_dataloader.py -k TestDataLoader.test_segfault
2024-06-12T17:42:24.9701259Z 
2024-06-12T17:42:24.9701608Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-06-12T17:42:24.9702361Z _________________________ TestDataLoader.test_segfault _________________________
2024-06-12T17:42:24.9702931Z Traceback (most recent call last):
2024-06-12T17:42:24.9703586Z   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 1380, in test_segfault
2024-06-12T17:42:24.9704284Z     self.assertFalse(p.is_alive())
2024-06-12T17:42:24.9704947Z   File "/opt/conda/envs/py_3.11/lib/python3.11/unittest/case.py", line 709, in assertFalse
2024-06-12T17:42:24.9705634Z     raise self.failureException(msg)
2024-06-12T17:42:24.9706051Z AssertionError: True is not false
2024-06-12T17:42:24.9706312Z 
2024-06-12T17:42:24.9706576Z To execute this test, run the following from the base repo dir:
2024-06-12T17:42:24.9707484Z     PYTORCH_TEST_WITH_DYNAMO=1 python test/test_dataloader.py -k TestDataLoader.test_segfault
2024-06-12T17:42:24.9708065Z 
2024-06-12T17:42:24.9708385Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-06-12T17:42:24.9709057Z =================================== FAILURES ===================================
2024-06-12T17:42:24.9709659Z _________________________ TestDataLoader.test_segfault _________________________
2024-06-12T17:42:24.9710227Z Traceback (most recent call last):
2024-06-12T17:42:24.9710892Z   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 1380, in test_segfault
2024-06-12T17:42:24.9711589Z     self.assertFalse(p.is_alive())
2024-06-12T17:42:24.9712235Z   File "/opt/conda/envs/py_3.11/lib/python3.11/unittest/case.py", line 709, in assertFalse
2024-06-12T17:42:24.9712979Z     raise self.failureException(msg)
2024-06-12T17:42:24.9713424Z AssertionError: True is not false
2024-06-12T17:42:24.9713787Z 
2024-06-12T17:42:24.9714042Z To execute this test, run the following from the base repo dir:
2024-06-12T17:42:24.9715029Z     PYTORCH_TEST_WITH_DYNAMO=1 python test/test_dataloader.py -k TestDataLoader.test_segfault
2024-06-12T17:42:24.9715591Z 
2024-06-12T17:42:24.9715924Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-06-12T17:42:24.9717227Z - generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/test_dataloader/test_dataloader-97c30c281c6a51f3.xml -
2024-06-12T17:42:24.9718309Z =========================== short test summary info ============================
2024-06-12T17:42:24.9719261Z FAILED [62.0443s] test_dataloader.py::TestDataLoader::test_segfault - AssertionError: True is not false
2024-06-12T17:42:24.9719880Z 
2024-06-12T17:42:24.9720147Z To execute this test, run the following from the base repo dir:
2024-06-12T17:42:24.9721038Z     PYTORCH_TEST_WITH_DYNAMO=1 python test/test_dataloader.py -k TestDataLoader.test_segfault
2024-06-12T17:42:24.9721609Z 
2024-06-12T17:42:24.9721926Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

```
This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_dataloader.py%3A%3ATestDataLoader%3A%3Atest_segfault%22%5D)).

cc @andrewkho @gokulavasan @SsnL @VitalyFedyunin @dzhulgakov @ezyang @anijain2305 @chauhang @penguinwu

**Comment by clee2000** [comment]
I think this is still flaky 
https://hud.pytorch.org/hud/pytorch/pytorch/68ad3eb722a429db738f93c73af82f700bc89ef5/1?per_page=100
The PR it starts on is inconsistent

Ex https://github.com/pytorch/pytorch/actions/runs/9893599157/job/27329920726

**Comment by ZainRizvi** [comment]
This has been failing for months without anyone looking at it. How about we disable this test permanently if the dataloader team isn't interested in fixing it?

**Comment by huydhn** [comment]
> This has been failing for months without anyone looking at it. How about we disable this test permanently if the dataloader team isn't interested in fixing it?

Let's do that. This test just keeps failing in trunk whenever it's re-enable again

**Comment by Flamefire** [comment]
Hasn't this test passed on Sep 17, 2024? That would indicate it is flaky and not failing consistently.

I'm asking because this test (unexpectedly) succeeds for me on RHEL with AMD EPYC CPUs.

**Comment by ZainRizvi** [comment]
Hi @Flamefire, that isn't a configuration we test on. Are you asking because the unexpected successes are resulting in test failures in your environment?

Given that there is no party interested in fixing this PR, I don't think there's any value in having a test that is _expected_ to segfault.  We could just remove the test instead

**Comment by Flamefire** [comment]
Yes we use AMD EPYC CPUs with NVIDIA H100 and the unexpected success is treated as a test failure.

>  I don't think there's any value in having a test that is expected to segfault

The test is actually about **handling** the segfault. I.e. what PyTorch does when a dataloader code happens to run into a serious issue (like an access violation). So it does make sense, doesn't it?
And in our environment is is correctly handled, i.e. we get a non-zero exit code from the dataloader process with the appropriate runtime error.

Unfortunately the logs seem to have expired so it isn't clear to me how this test failed on CI
