### ISSUE TITLE
NotImplementedError: Operator aten.native_layer_norm_backward.default does not have a sharding strategy registered.

### ISSUE THREAD

**Issue by Xingzhi107** [pytorch/pytorch#128699]
### 🐛 Describe the bug

I tried to use ParallelStyle for a layer_norm type module. I followed ColwiseParallel, but got the following error: 
```Traceback (most recent call last):
  File "train_gpt2.py", line 255, in <module>
    output_sharding = self.propagate_op_sharding(op_info.schema)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/sharding_prop.py", line 369, in propagate_op_sharding_non_cached
        torch.autograd.backward(raise NotImplementedError(

  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 266, in backward
NotImplementedError: Operator aten.native_layer_norm_backward.default does not have a sharding strategy registered.
    loss.backward()
      File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 522, in backward
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/api.py", line 280, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/dispatch.py", line 106, in dispatch
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 266, in backward
    self.sharding_propagator.propagate(op_info)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/sharding_prop.py", line 163, in propagate
        output_sharding = self.propagate_op_sharding(op_info.schema)
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/sharding_prop.py", line 369, in propagate_op_sharding_non_cached
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/api.py", line 280, in __torch_dispatch__
        return DTensor._op_dispatcher.dispatch(raise NotImplementedError(

  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_tensor/dispatch.py", line 106, in dispatch
NotImplementedError: Operator aten.native_layer_norm_backward.default does not have a sharding strategy registered.```

I want to know if this ParallelStyle is only valid for linear and embedding. Will other types of modules also produce this error when doing backward? Or is there something wrong with my usage?


### Versions

I use the pytorch==2.2.1

**Comment by weifengpy** [comment]
Hi @XilunWu , this looks like a DTensor + TP issue. Does it look familar to you? 

@Xingzhi107 , do you mind share more about `train_gpt2.py` ? we want to understand more about the layer norm module (how it is defined), and how it is annotated (ParallelStyle)

**Comment by Xingzhi107** [comment]
> Hi @XilunWu , this looks like a DTensor + TP issue. Does it look familar to you?
> 
> @Xingzhi107 , do you mind share more about `train_gpt2.py` ? we want to understand more about the layer norm module (how it is defined), and how it is annotated (ParallelStyle)

Thanks for your reply，
I defined a class
```
class ShardParallel(ParallelStyle):
    def __init__(
        self,
        *,
        input_layouts: Optional[Placement] = None,
        output_layouts: Optional[Placement] = None,
        use_local_output: bool = True,
        param_layouts:Dict[str,Optional[Placement]] = None,
    ):
        super().__init__()
        self.input_layouts = input_layouts
        self.output_layouts = output_layouts
        self.use_local_output = use_local_output
        self.param_layouts = param_layouts


    @staticmethod
    def _prepare_input_fn(input_layouts, inputs, device_mesh):
        input_tensor = inputs[0]
        if not isinstance(input_tensor, DTensor):
            input_tensor = DTensor.from_local(input_tensor, device_mesh, [input_layouts], run_check=False)
        return input_tensor

    def _partition_fn(self, name, module, device_mesh):
        for name, param in module.named_parameters():
            dist_param = nn.Parameter(
                distribute_tensor(param, device_mesh, [self.param_layouts[name]])
            )
            module.register_parameter(name, dist_param)
...

    def _apply(self, module: nn.Module, device_mesh: DeviceMesh) -> nn.Module:
        return distribute_module(
            module,
            device_mesh,
            self._partition_fn,
            partial(self._prepare_input_fn, self.input_layouts),
            partial(self._prepare_output_fn, self.output_layouts, self.use_local_output),
        )
```
and use parallelize_plan={'ln_1':ShardParallel(input_layouts=[Replicate()],input_layouts=[output_layouts],param_layouts={'weight':[Replicate()]})},if _partition_fn only used on nn.Linear and nn.Embedding
