### ISSUE TITLE
Improving expand w/ unbacked symints

### ISSUE THREAD

**Issue by ColinPeppler** [pytorch/pytorch#128645]
### 🐛 Describe the bug

```
  @skipCUDAIf(not HAS_CUDA, "requires cuda")
  @dynamo_config.patch({"capture_scalar_outputs": True})
  def test_expand(self, device):
      mm_fn = torch.bmm
      def fn(x, w, repeats):
          u0 = repeats.item()
          torch._check_is_size(u0)
          x_unbacked = x.expand(-1, u0)    # [16, u0]
          # But x.unsqueeze(1).expand(-1, u0) works
      
      example_inputs = (
          torch.randn(16).cuda(),
          torch.tensor(100).cuda(),
      )
      actual = torch.compile(fn, fullgraph=True)(*example_inputs)

```

We hit this code during `expand`.
https://github.com/pytorch/pytorch/blob/c0b40ab42e38a208351911496b7153511304f8da/torch/_refs/__init__.py#L2939-L2944

In this scenario, we have `requested_length = u0` and `x = 16`. All three of these checks will resolve to false or fail. 

However we know that `x.unsqueeze(1).expand(-1, u0)` works, so why can't `x.expand(-1, u0)` work? This has me wondering, if we can somehow tell Dynamo that this is fine without a `torch._check`.

### Error logs

```
======================================================================
ERROR: test_bmm_cuda (__main__.TestUnbackedSymintsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/colinpeppler/pytorch/torch/_dynamo/utils.py", line 1905, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/data/users/colinpeppler/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/colinpeppler/pytorch/torch/_subclasses/fake_tensor.py", line 1061, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/data/users/colinpeppler/pytorch/torch/_subclasses/fake_tensor.py", line 1450, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/data/users/colinpeppler/pytorch/torch/_subclasses/fake_tensor.py", line 1153, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/data/users/colinpeppler/pytorch/torch/_subclasses/fake_tensor.py", line 1690, in _dispatch_impl
    return decomposition_table[func](*args, **kwargs)
  File "/data/users/colinpeppler/pytorch/torch/_refs/__init__.py", line 2937, in expand
    guard_size_oblivious(requested_length == x)
  File "/data/users/colinpeppler/pytorch/torch/fx/experimental/symbolic_shapes.py", line 248, in guard_size_oblivious
    return expr.node.guard_size_oblivious("", 0)
  File "/data/users/colinpeppler/pytorch/torch/fx/experimental/sym_node.py", line 466, in guard_size_oblivious
    r = self.shape_env.evaluate_expr(
  File "/data/users/colinpeppler/pytorch/torch/fx/experimental/recording.py", line 245, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/colinpeppler/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5197, in evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(u0, 1) (unhinted: Eq(u0, 1)).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/data/users/colinpeppler/pytorch/torch/_refs/__init__.py", line 2937, in expand
    guard_size_oblivious(requested_length == x)
```

### Versions

N/A

**Comment by ezyang** [comment]
The test here technically could be a runtime assert, but currently isn't because the "or" forces the value to be evaluated immediately. So rewriting this with some sym_or is potentially one way to solve, though there are probably others.

**Comment by StrongerXi** [comment]
Doing old issue scrubbing; this still repros on main 0c8028e8772; @bobrenjc93 should we keep it open?

**Comment by bobrenjc93** [comment]
Yes let's keep this open

**Comment by laithsakka** [comment]
yeh lets keep 
added data dependent error tag

**Comment by laithsakka** [comment]
i think in the example above the expand itself is not valid anyway let me change the example slightly so it will compile with the new update but will fail with runtime erro .
i.e.
torch.randn(16).expand(10, 100) fails

RuntimeError: The expanded size of the tensor (100) must match the existing size (16) at non-singleton dimension 1.  Target sizes: [10, 100].  Tensor sizes: [16]

**Comment by laithsakka** [comment]
here is a better example were we fail but we dont have to 
torch.rand(3,3).expand(3,3) should work 

```
    @torch._dynamo.config.patch(capture_scalar_outputs=True)
    def test_expand_unbacked(self):
        def fn(x, repeats):
            u0 = repeats.item()
            torch._check_is_size(u0)
            x_unbacked = x.expand(u0, u0)  
            return x_unbacked
        
        example_inputs = (
            torch.rand(3,3),
            torch.tensor(3),
        )
        torch.compile(fn, fullgraph=True)(*example_inputs)
```
we do not have to fail for this. 
sym_or fix it
