### ISSUE TITLE
Expected grad_output types don't match available grad_output types when using tensor parallelism with DTensors

### ISSUE THREAD

**Issue by schinmayee** [pytorch/pytorch#128636]
### 🐛 Describe the bug

I was trying to distribute some model using tensor parallelization, but I ran into a grad output type mismatch when I enabled compile. Note, I was not using loss parallel here, and using use_local_output for the final lm head. I was able to run this successfully without compile.

I was able to reproduce a similar error with a small example, but with loss parallel enabled. Adding the simplified example below. I am able to run this if I comment out the compile call.

This simplified example works if we only return the loss instead of the output and the loss from the forward function.

### Error logs

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "example1.py", line 69, in <module>
[rank1]:     loss.backward()
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/_tensor.py", line 512, in backward
[rank1]:     return handle_torch_function(
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/overrides.py", line 1630, in handle_torch_function
[rank1]:     result = mode.__torch_function__(public_api, types, args, kwargs)
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/utils/_device.py", line 79, in __torch_function__
[rank1]:     return func(*args, **kwargs)
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
[rank1]:     torch.autograd.backward(
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/autograd/function.py", line 306, in apply
[rank1]:     return user_fn(self, *args)
[rank1]:   File ".conda/envs/ptnightly/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1726, in backward
[rank1]:     assert (
[rank1]: AssertionError:     We incorrectly attempted to compile the backward with incorrect subclass metadata.
[rank1]:     If you run into this error, please file an issue.
[rank1]:     Expected grad_output types: [<class 'torch.distributed._tensor.api.DTensor'>, <class 'torch.distributed._tensor.api.DTensor'>]
[rank1]:     Got grad_output types: [<class 'torch.Tensor'>, <class 'torch.distributed._tensor.api.DTensor'>]
```

### Minified repro

```
import os
os.environ["TORCH_COMPILE_DEBUG"] = "1"
os.environ["TORCHDYNAMO_VERBOSE"] = "1"
os.environ["TORCH_LOGS"] = "+dynamo"

import torch
import torch.nn as nn
import torch.distributed as dist 
from torch.distributed.tensor.parallel import *
from torch.distributed._tensor import DTensor, Shard, Replicate, distribute_tensor, distribute_module, init_device_mesh

dist.init_process_group()
global_rank = dist.get_rank()
device = global_rank % torch.cuda.device_count()
torch.set_default_device(device)
world_size = dist.get_world_size()

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(50, 80)
        self.fc2 = nn.Linear(80, 50)
        self.fc3 = nn.Linear(50, 32)
        self.fc4 = nn.Linear(32, 10)
        self.loss_fn = nn.CrossEntropyLoss()

    def forward(self, x, target=None):
        h1 = nn.ReLU()(self.fc1(x))
        h2 = nn.ReLU()(self.fc2(h1))
        h3 = nn.ReLU()(self.fc3(h2))
        out = self.fc4(h3)
        if target is not None:
            loss = self.loss_fn(out, target)
        return (out, loss)

device_mesh = init_device_mesh("cuda", (world_size,))
plan = {
    "fc1": ColwiseParallel(output_layouts=Shard(1)),
    "fc2": ColwiseParallel(input_layouts=Shard(1), output_layouts=Shard(1)),
    "fc3": RowwiseParallel(input_layouts=Shard(1), output_layouts=Replicate()),
    "fc4": ColwiseParallel(input_layouts=Replicate(), output_layouts=Shard(1), use_local_output=False)
}

net = Net()
net = parallelize_module(net, device_mesh, plan)
net = torch.compile(net)

net.train()
for i in range(5):
    print(f"[rank{global_rank}] Running iteration {i}")
    x = torch.rand(4, 50)
    target = torch.empty(4, dtype=torch.long).random_(10)
    x = x.to(global_rank)
    target = target.to(global_rank)
    x = distribute_tensor(x, device_mesh=device_mesh, placements=[Replicate()])
    target = distribute_tensor(target, device_mesh=device_mesh, placements=[Replicate()])
    with loss_parallel():
        (_, loss) = net(x, target=target)
        loss.backward()


print("[rank{global_rank}] ]Completed!")
```

Command used:
```
torchrun --standalone --nnodes=1 --nproc-per-node=2 example1.py
```

### Versions

Collecting environment information...
PyTorch version: 2.4.0.dev20240611
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-17)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.26

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.216-204.855.amzn2.x86_64-x86_64-with-glibc2.26
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 535.161.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:            7
CPU MHz:             3600.063
BogoMIPS:            5999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0.dev20240611
[pip3] torchaudio==2.4.0.dev20240611
[pip3] torchvision==0.19.0.dev20240611
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl  
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch-nightly
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.4          py310h5f9d8c6_0  
[conda] numpy-base                1.26.4          py310hb5e798b_0  
[conda] pytorch                   2.4.0.dev20240611 py3.10_cuda12.1_cudnn9.1.0_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_6    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.4.0.dev20240611     py310_cu121    pytorch-nightly
[conda] torchtriton               3.0.0+45fff310c8           py310    pytorch-nightly
[conda] torchvision               0.19.0.dev20240611     py310_cu121    pytorch-nightly

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @ezyang @albanD @chauhang @penguinwu @anijain2305 @zou3519 @bdhirsh

**Comment by awgu** [comment]
cc: @bdhirsh

**Comment by bdhirsh** [comment]
I can repro.

FWIW, this is a legitimate error (the output of the forward graph was a DTensor, but the gradient that flowed in was a plain tensor). Two things:

(1) we do want to allow this situation to work in the long term, although it is quite difficult to fix (hopefully we can work on it later this year)

(2) it might be possible to work around this error. i'm going to dig in a bit more and see why it's happening in this pretty vanilla-looking code

**Comment by schinmayee** [comment]
Thanks for the update. What's the suggested work-around for this issue?

Is there a way for me to examine the forward and backward graph: where this issue is coming from, which ops/nodes?

**Comment by bdhirsh** [comment]
Hey @schinmayee, sorry for the late reply.

I stared at your repro some more - changing the output of your example `Net.forward()` to the below fixes it for me:
```
        if target is not None:
            loss = self.loss_fn(out, target)
        return (out.detach(), loss)
```

In particular:

(1) your net returns **both** the output, and the loss as outputs

(2) but when you do training, you effectively discard the output tensor, and only backpropagate through the `loss()` tensor.

(3) the autograd engine will handle this by plumbing a tensor full of zeros as the gradient for your first output. This will show up as a plain tensor though, which is what causes the error: the first output to your model was a DTensor, but its corresponding gradient is a plain tensor (a tensor of zeros, since the autograd engine realized you did not actually need to propagate gradients through the first output).

the `detach()` fixes this problem because you are properly telling the autograd engine that you only plan on `.backward`-ing through the second output of your net (the `loss` tensor), and not the first output.

Let me know if you have any questions!

**Comment by schinmayee** [comment]
Thanks!

**Comment by bdhirsh** [comment]
Closing this one since this is the workaround that we will generally advertise for this situation
