### ISSUE TITLE
heartbeatMonitor error after run script multiple times

### ISSUE THREAD

**Issue by garfield1997** [pytorch/pytorch#128680]
### 🐛 Describe the bug

heartbeatMonitor error after run script multiple times, the python script is as following:
```python
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
class TwoLinLayerNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.nn.Linear(10, 10, bias=False)
        self.b = torch.nn.Linear(10, 1, bias=False)
 
    def forward(self, x):
        a = self.a(x)
        b = self.b(x)
        return (a, b)
 
def worker(rank):
    dist.init_process_group("nccl", rank=rank, world_size=int(os.environ.get('WORLD_SIZE')))
    torch.cuda.set_device(rank)
    print("init model")
    model = TwoLinLayerNet().cuda()
    print("init ddp")
    ddp_model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[rank])
 
    inp = torch.randn(10, 10).cuda()
    print("train")
 
    for _ in range(20):
        output = ddp_model(inp)
        loss = output[0] + output[1]
        loss.sum().backward()
 
if __name__ == "__main__":
    mp.spawn(worker, nprocs=int(os.environ.get('WORLD_SIZE')), args=())
```
and the shell script to run this python script multiple times is as following:
```shell
#!/bin/bash
export MASTER_ADDR=localhost
export MASTER_PORT=12345
export WORLD_SIZE=4
export TORCH_NCCL_BLOCKING_WAIT=1
export TORCH_CPP_LOG_LEVEL=INFO
export TORCH_DISTRIBUTED_DEBUG=DETAIL

export FAIL_LOG=$PWD/op_repeat_fail_log
COUNT=1000

repeat_test() {
  ITER=1
  RET=0
  while [ ${RET} -eq 0 ] && [ ${ITER} -lt ${COUNT} ]; do
    python reduce_timer.py > log 2>&1
    RET=$?
    if [ $RET == 0 ]; then
      echo "run ${1} iter ${ITER} success!"
    else
      echo "run ${1} iter ${ITER} failed!"
      cat log
    fi
    let ITER=$ITER+1
  done
  if [ ${RET} != 0 ]; then
    echo "run ${1} failed in iter ${ITER}" >> ${FAIL_LOG}
  fi
}

repeat_test
```
after repeat some times, the following errors may be produced(without normal log info):
```
[rank1]:[E614 11:14:03.086670611 ProcessGroupNCCL.cpp:1319] [PG 0 Rank 1] Failed to get exception dump flag from the global store.Connection reset by peer
Exception raised from recvBytes at /projs/framework/xushuo/pytorch_gar/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: <unknown function> + 0x121eb6 (0x7f1d54e02eb6 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1240a2 (0x7f1d54e050a2 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x12052f (0x7f1d54e0152f in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x123113 (0x7f1d54e04113 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x122fda (0x7f1d54e03fda in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #5: <unknown function> + 0x122e32 (0x7f1d54e03e32 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0x122b82 (0x7f1d54e03b82 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x122a34 (0x7f1d54e03a34 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #8: <unknown function> + 0x1227cb (0x7f1d54e037cb in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x1221af (0x7f1d54e031af in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #10: <unknown function> + 0x121a20 (0x7f1d54e02a20 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #11: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x34 (0x7f1d54e0167c in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #12: <unknown function> + 0xa13c6ce (0x7f1d6f7316ce in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0xa21bcfc (0x7f1d6f810cfc in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0xa221186 (0x7f1d6f816186 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0xa21f194 (0x7f1d6f814194 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0xa21dba5 (0x7f1d6f812ba5 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #17: c10d::TCPStore::check(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) + 0x1ed (0x7f1d6f80e7c1 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #18: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x44a (0x7f1d588e61f8 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #19: void std::__invoke_impl<void, void (c10d::ProcessGroupNCCL::*)(), c10d::ProcessGroupNCCL*>(std::__invoke_memfun_deref, void (c10d::ProcessGroupNCCL::*&&)(), c10d::ProcessGroupNCCL*&&) + 0x6a (0x7f1d589a9b1d in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #20: std::__invoke_result<void (c10d::ProcessGroupNCCL::*)(), c10d::ProcessGroupNCCL*>::type std::__invoke<void (c10d::ProcessGroupNCCL::*)(), c10d::ProcessGroupNCCL*>(void (c10d::ProcessGroupNCCL::*&&)(), c10d::ProcessGroupNCCL*&&) + 0x3b (0x7f1d589a99d5 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #21: void std::thread::_Invoker<std::tuple<void (c10d::ProcessGroupNCCL::*)(), c10d::ProcessGroupNCCL*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) + 0x47 (0x7f1d589a9895 in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #22: std::thread::_Invoker<std::tuple<void (c10d::ProcessGroupNCCL::*)(), c10d::ProcessGroupNCCL*> >::operator()() + 0x1c (0x7f1d589a96cc in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #23: std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (c10d::ProcessGroupNCCL::*)(), c10d::ProcessGroupNCCL*> > >::_M_run() + 0x20 (0x7f1d589a934e in /projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #24: <unknown function> + 0xdbbf4 (0x7f1d82a54bf4 in /home/xushuo/miniconda3/bin/../lib/libstdc++.so.6)
frame #25: <unknown function> + 0x8609 (0x7f1d843ca609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #26: clone + 0x43 (0x7f1d84195353 in /lib/x86_64-linux-gnu/libc.so.6)

[rank1]:[E614 11:14:03.108204079 ProcessGroupNCCL.cpp:1418] 
[rank1]:[I614 11:14:03.121301828 ProcessGroupNCCL.cpp:1450] Could acquire GIL on exit
[rank1]:[F614 11:14:03.121327945 ProcessGroupNCCL.cpp:1227] [PG 0 Rank 1] [PG 0 Rank 1] 
Traceback (most recent call last):
  File "/projs/framework/xushuo/backup/workspace/reduce_timer.py", line 38, in <module>
    mp.spawn(worker, nprocs=int(os.environ.get('WORLD_SIZE')), args=())
  File "/projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 282, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
    while not context.join():
  File "/projs/framework/xushuo/pytorch_gar/venv/maingpu/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 170, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT

```

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+git7d3bfe4
Is debug build: True
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 535.104.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
Stepping:                        4
CPU MHz:                         1000.000
CPU max MHz:                     3700.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        32 MiB
L3 cache:                        44 MiB
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.10.0
[pip3] torch==2.3.0a0+git2d7a360
[conda] No relevant packages

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by garfield1997** [comment]
Maybe relates to  [#123969](https://github.com/pytorch/pytorch/issues/123969)

**Comment by garfield1997** [comment]
https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1323
```cpp
        try {
          checkExceptionDump =
              globalStore_->check({std::string(EXCEPTION_DUMP)});
        } catch (const std::exception& e) {
          LOG(ERROR)
              << logPrefix()
              << "Failed to get exception dump flag from the global store."
              << e.what();
          break;
        }

```
It appears that after breaking out of the loop here, [the thread was aborted](https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1489).  If this is indeed the case, I would like to know if this behavior is expected, as the script above seems to be legitimate.

**Comment by weifengpy** [comment]
> It appears that after breaking out of the loop here

cc @c-p-i-o who just made the change to break out at https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1323

**Comment by wconstab** [comment]
@kurman has an ENV you can set that will keep tcpstore alive past trainer exit. It should help avoid this crash.

**Comment by garfield1997** [comment]
After removing this break statement, this test case does not report an error and exit when run repeatedly. Would it be more reasonable to delete this break here?

**Comment by weifengpy** [comment]
> After removing this break statement, this test case does not report an error and exit when run repeatedly. Would it be more reasonable to delete this break here?

Hi @garfield1997 , thanks for stepping up and root cause it. Are you interested in sending us a PR so we can address the issue through PR review? It might speed up the landing

**Comment by c-p-i-o** [comment]
> > It appears that after breaking out of the loop here
> 
> cc @c-p-i-o who just made the change to break out at https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1323

Hello @weifengpy /  @garfield1997 - the `break` was added to catch the case where the `globalStore` isn't available and/or it throws an exception. Not having the `try/catch` + `break` there causes the program to crash.
But, another option could be to do a `continue` here to see if it resolves the issue.
The change would be at the `break` we instead put:
```
try {
          checkExceptionDump =
              globalStore_->check({std::string(EXCEPTION_DUMP)});
        } catch (const std::exception& e) {
          LOG(ERROR)
              << logPrefix()
              << "Failed to get exception dump flag from the global store."
              << e.what();
          checkDumpSignal = false;
          continue;
        }

**Comment by c-p-i-o** [comment]
FWIW, I tried the attached repro on my machine and haven't hit the repro so far:
Do you know how long it takes?
I have run ~100 iterations so far.

**Comment by kurman** [comment]
> ENV you can set that will keep tcpstore alive past trainer exit. It should help avoid this crash.

This is enabled by default now after https://github.com/pytorch/pytorch/pull/128096 landed about 5 days ago.

**Comment by garfield1997** [comment]
After I updated my local repository, this problem still occurs. @kurman 
```
Collecting environment information...
PyTorch version: 2.4.0a0+git7d3bfe4
Is debug build: True
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 535.104.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
Stepping:                        4
CPU MHz:                         1000.000
CPU max MHz:                     3700.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        32 MiB
L3 cache:                        44 MiB
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.10.0
[pip3] torch==2.3.0a0+git2d7a360
[conda] No relevant packages

```

**Comment by garfield1997** [comment]
After I updated my local repository, this problem no longer occurs. @c-p-i-o  @kurman @weifengpy Thank you for taking the time to look into this issue.
My current environment is as follows:
```
Collecting environment information...
PyTorch version: 2.5.0a0+gitc35ffaf
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 535.104.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
Stepping:                        4
CPU MHz:                         1000.000
CPU max MHz:                     3700.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        32 MiB
L3 cache:                        44 MiB
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.10.0
[pip3] torch==2.5.0a0+gitc35ffaf
[conda] No relevant packages

```

**Comment by garfield1997** [comment]
If there are no further questions from everyone, this issue can be closed.
