### ISSUE TITLE
AssertionError: <class 'torch._dynamo.variables.torch.TorchInGraphFunctionVariable'> when compiling `torch.nn.functional.layer_norm`

### ISSUE THREAD

**Issue by ByronHsu** [pytorch/pytorch#128797]
### 🐛 Describe the bug

```python
import torch

ln = torch.compile(torch.nn.functional.layer_norm)
x = torch.randn(16, 8, 4)
ln(x, (8, 4))
```

```
Traceback (most recent call last):
  File "/home/jobuser/resources/layernorm.py", line 3, in <module>
    ln = torch.compile(torch.nn.functional.layer_norm)
  File "/home/jobuser/.local/lib/python3.10/site-packages/torch/__init__.py", line 2351, in compile
    return torch._dynamo.optimize(
  File "/home/jobuser/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 378, in __call__
    (filename is None or trace_rules.check(fn))
  File "/home/jobuser/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 3435, in check
    return check_verbose(obj, is_inlined_call).skipped
  File "/home/jobuser/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 3427, in check_verbose
    assert rule == SkipFunctionVariable, rule
AssertionError: <class 'torch._dynamo.variables.torch.TorchInGraphFunctionVariable'>
```

The same issue also happens for silu

```python
import torch
x = torch.randn(16, 8, 4)
sl = torch.compile(torch.nn.functional.silu)
sl(x)
```

### Versions

```
[pip3] numpy==1.24.3
[pip3] pytorch-triton==3.0.0+45fff310c8
[pip3] torch==2.5.0.dev20240614+cu118
[pip3] torch-tb-profiler==0.4.1
[pip3] triton==2.3.0
```

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by HDCharles** [comment]
you need to run compile on the module, not the module constructor

in your example if you try to test the pre compiled model it doesn't work
```
ln = torch.compile(torch.nn.functional.layer_norm)
torch.nn.functional.layer_norm(x, (8,4)) # this won't run
x = torch.randn(16, 8, 4)
ln(x, (8, 4))
```

```
import torch
model = torch.nn.functional.layer_norm(8, 4)
x = torch.randn(16, 8, 4)
model(x) # since you can run the model before compile, you'd expect to be able to run it afterwards
ln = torch.compile(model)
ln(x)
```

**Comment by ByronHsu** [comment]
I see. Thanks for the explanation!
