### ISSUE TITLE
ImportError: cannot import name 'OrderedDict' from partially initialized module 'collections'

### ISSUE THREAD

**Issue by pickle-dev-fr** [pytorch/pytorch#128838]
### 🐛 Describe the bug

```import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
import torchaudio
import pandas as pd
import os
Traceback (most recent call last):
  File "C:\workspace\sandra\models\definition\keyword.py", line 1, in <module>
    import torch
  File "C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\__init__.py", line 15, in <module>
    import platform
  File "C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\platform.py", line 115, in <module>
    import collections
  File "C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py", line 35, in <module>
    from keyword import iskeyword as _iskeyword
  File "C:\workspace\sandra\models\definition\keyword.py", line 2, in <module>
    from torch import nn, optim
  File "C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\__init__.py", line 1, in <module>
    from .module import Module
  File "C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name 'OrderedDict' from partially initialized module 'collections' (most likely due to a circular import) (C:\Users\Julien MTN\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)

### Versions

PyTorch version: 2.3.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 555.85
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3000
DeviceID=CPU0
Family=107
L2CacheSize=3072
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3000
Name=AMD Ryzen 5 4600H with Radeon Graphics
ProcessorType=3
Revision=24577

Versions of relevant libraries:
[pip3] numpy==2.0.0
[pip3] torch==2.3.1
[pip3] torchaudio==2.3.1
[conda] Could not collect

**Comment by pickle-dev-fr** [comment]
I shouldn't have called my file keyword.py that's what caused the issue
