### ISSUE TITLE
Environment gating of CUDA_VISIBLE_DEVICES returns a CUDA initialization error.

### ISSUE THREAD

**Issue by jramapuram** [pytorch/pytorch#128819]
### 🐛 Describe the bug

- Exact code worked fine on <= pytorch 2.2.1
- Breaks on pytorch > 2.2.1 (includes 2.3.0, 2.3.1)
- Deployment is with a docker container: nothing besides pytorch has changed (same CUDA version, etc). 
- `nvidia-smi` works fine.
- Without enviroment gating this works fine. 

Why is it necessary? As per [this thread](https://discuss.pytorch.org/t/is-it-expected-for-distributeddataparallel-to-use-more-memory-on-1-gpu-in-a-1gpu-1process-setup/77748/9) there is the possibility for memory leakage. This is more pronounced when using external libraries. Thus the cleanest way is to environment gate with `CUDA_VISIBLE_DEVICES`

Example: 
```bash
> python -c "import torch; print(torch.cuda.is_available()); print(torch.__version__)"
True
2.3.1+cu121

> nvidia-smi
nvidia-smi
Fri Jun  7 18:08:52 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 12.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:00:05.0 Off |                    0 |
| N/A   36C    P0    63W / 400W |      0MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:00:06.0 Off |                    0 |
| N/A   34C    P0    67W / 400W |      0MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```bash
> ipython

In [1]: import torch
   ...: import os
   ...: torch.cuda.device_count()
   ...: os.environ["CUDA_VISIBLE_DEVICES"] = "0"
   ...: torch.empty(2, device='cuda')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:306, in _lazy_init()
    305 try:
--> 306     queued_call()
    307 except Exception as e:

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:174, in _check_capability()
    173 for d in range(device_count()):
--> 174     capability = get_device_capability(d)
    175     major = capability[0]

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:430, in get_device_capability(device)
    418 r"""Get the cuda capability of a device.
    419 
    420 Args:
   (...)
    428     tuple(int, int): the major and minor cuda capability of the device
    429 """
--> 430 prop = get_device_properties(device)
    431 return prop.major, prop.minor

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:448, in get_device_properties(device)
    447     raise AssertionError("Invalid device id")
--> 448 return _get_device_properties(device)

RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

DeferredCudaCallError                     Traceback (most recent call last)
Cell In[1], line 5
      3 torch.cuda.device_count()
      4 os.environ["CUDA_VISIBLE_DEVICES"] = "0"
----> 5 torch.empty(2, device='cuda')

File /miniconda/lib/python3.10/site-packages/torch/cuda/__init__.py:312, in _lazy_init()
    307         except Exception as e:
    308             msg = (
    309                 f"CUDA call failed lazily at initialization with error: {str(e)}\n\n"
    310                 f"CUDA call was originally invoked at:\n\n{''.join(orig_traceback)}"
    311             )
--> 312             raise DeferredCudaCallError(msg) from e
    313 finally:
    314     delattr(_tls, "is_initializing")

DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

...
```

Without environment gating this works fine:
```bash
In [1]: import torch
   ...: import os
   ...: torch.cuda.device_count()
   ...: torch.empty(2, device='cuda')

Out[1]: tensor([0., 0.], device='cuda:0')
```

Related PR: https://github.com/pytorch/pytorch/issues/107300

### Versions

- Exact code worked fine on <= pytorch 2.2.1
- Breaks on pytorch > 2.2.1 (includes 2.3.0, 2.3.1)

**Comment by malfet** [comment]
Ok, I can repro it inside the docker container, but not with the local build outside of it

**Comment by malfet** [comment]
@atalman can you please take an AI of finding an offending commit as well as adding this one to the pre-release regression testing?

**Comment by jramapuram** [comment]
Appreciate the quick turn-around 🙏 

I'll also try with 2.4.0rc1

**Comment by jramapuram** [comment]
Can confirm that 2.4.0rc1 resolves this issue, but will be great to prevent this from arising in the future!

**Comment by atalman** [comment]
This is the fix: https://github.com/pytorch/pytorch/pull/122815 that resolved this error.

**Comment by atalman** [comment]
This also breaks on 2.2.0 
```
python3 -c "import torch;import os;print(torch.cuda.device_count(), torch.__version__);os.environ['CUDA_VISIBLE_DEVICES']='0';print(torch.empty(2, device='cuda'))"
8 2.2.0+cu121
Traceback (most recent call last):
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 315, in _lazy_init
    queued_call()
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 183, in _check_capability
    capability = get_device_capability(d)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 439, in get_device_capability
    prop = get_device_properties(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 457, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 321, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

CUDA call was originally invoked at:

  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/__init__.py", line 1421, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in <module>
    _lazy_call(_check_capability)
  File "/home/atalman/miniconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 244, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
```

**Comment by vananh0905** [comment]
Hi @atalman,
I installed Pytorch 2.4.0 and am facing the same issue.
few days ago, it worked on my site, but today, when I re-ran my code and didnt change anything, it raised this error. 

<img width="726" alt="Image" src="https://github.com/user-attachments/assets/97e0adc0-a2d4-4f57-a292-2953177196eb" />
