### ISSUE TITLE
Update PyTorch CI to numpy 2.0 

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#128860]
https://pypi.org/project/numpy/2.0.0/ is officially out on June 16th 2024, so we need to update PyTorch CI to use this new version.  @albanD and @malfet have done the work to make core to work with numpy 2.0.  Note that numpy 2.0 requires python >= 3.9.  So, while we are still having python 3.8 in our CI/CD, 3.8 would probably need a different numpy pinned version.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by adamtheturtle** [comment]
Right now I'm hitting issues on Windows CI, e.g. at https://productionresultssa14.blob.core.windows.net/actions-results/59670409-dd33-4d54-a862-279f3277e74f/workflow-job-run-0e5a36d3-4b3d-53bb-c9e4-da62bd545c22/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-06-17T22%3A16%3A53Z&sig=z8Z13uW47AbPjAgEkL6CTw7ONOSdxlh%2BZx0J34xzhxY%3D&ske=2024-06-18T07%3A08%3A05Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-06-17T19%3A08%3A05Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-06-17T22%3A06%3A48Z&sv=2023-11-03:

```
2024-06-17T21:58:47.1938064Z [36;1mpython -m pytest -s -vvv --cov-fail-under 100 --cov=src/ --cov=tests . --cov-report=xml[0m
2024-06-17T21:58:47.1971748Z shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
2024-06-17T21:58:47.1972264Z env:
2024-06-17T21:58:47.1972584Z   pythonLocation: C:\hostedtoolcache\windows\Python\3.12.3\x64
2024-06-17T21:58:47.1973208Z   PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.12.3\x64/lib/pkgconfig
2024-06-17T21:58:47.1973815Z   Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.3\x64
2024-06-17T21:58:47.1974348Z   Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.3\x64
2024-06-17T21:58:47.1974923Z   Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.3\x64
2024-06-17T21:58:47.1975350Z ##[endgroup]
2024-06-17T21:59:04.8125867Z 
2024-06-17T21:59:04.8126515Z A module that was compiled using NumPy 1.x cannot be run in
2024-06-17T21:59:04.8127420Z NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
2024-06-17T21:59:04.8128217Z versions of NumPy, modules must be compiled with NumPy 2.0.
2024-06-17T21:59:04.8129383Z Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
2024-06-17T21:59:04.8130056Z 
2024-06-17T21:59:04.8130423Z If you are a user of the module, the easiest solution will be to
2024-06-17T21:59:04.8131477Z downgrade to 'numpy<2' or try to upgrade the affected module.
2024-06-17T21:59:04.8132585Z We expect that some modules will need time to support NumPy 2.
2024-06-17T21:59:04.8133098Z 
2024-06-17T21:59:04.8133558Z Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-17T21:59:04.8138741Z   File "<frozen runpy>", line 88, in _run_code
2024-06-17T21:59:04.8139707Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pytest\__main__.py", line 7, in <module>
2024-06-17T21:59:04.8140489Z     raise SystemExit(pytest.console_main())
2024-06-17T21:59:04.8141395Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 206, in console_main
2024-06-17T21:59:04.8142109Z     code = main()
2024-06-17T21:59:04.8142806Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 159, in main
2024-06-17T21:59:04.8143502Z     config = _prepareconfig(args, plugins)
2024-06-17T21:59:04.8144375Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 346, in _prepareconfig
2024-06-17T21:59:04.8145170Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-06-17T21:59:04.8145990Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
2024-06-17T21:59:04.8146850Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-06-17T21:59:04.8147838Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
2024-06-17T21:59:04.8148687Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-06-17T21:59:04.8149636Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
2024-06-17T21:59:04.8150344Z     res = hook_impl.function(*args)
2024-06-17T21:59:04.8151260Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 1152, in pytest_cmdline_parse
2024-06-17T21:59:04.8152056Z     self.parse(args)
2024-06-17T21:59:04.8152805Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 1501, in parse
2024-06-17T21:59:04.8153545Z     self._preparse(args, addopts=addopts)
2024-06-17T21:59:04.8156770Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 1405, in _preparse
2024-06-17T21:59:04.8157649Z     self.hook.pytest_load_initial_conftests(
2024-06-17T21:59:04.8158540Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
2024-06-17T21:59:04.8159390Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-06-17T21:59:04.8160364Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
2024-06-17T21:59:04.8161177Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-06-17T21:59:04.8162112Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
2024-06-17T21:59:04.8162798Z     res = hook_impl.function(*args)
2024-06-17T21:59:04.8163717Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 1230, in pytest_load_initial_conftests
2024-06-17T21:59:04.8164533Z     self.pluginmanager._set_initial_conftests(
2024-06-17T21:59:04.8165439Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 588, in _set_initial_conftests
2024-06-17T21:59:04.8166193Z     self._try_load_conftest(
2024-06-17T21:59:04.8167026Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 636, in _try_load_conftest
2024-06-17T21:59:04.8167789Z     self._loadconftestmodules(
2024-06-17T21:59:04.8168705Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 666, in _loadconftestmodules
2024-06-17T21:59:04.8170166Z     mod = self._importconftest(
2024-06-17T21:59:04.8171041Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\config\__init__.py", line 717, in _importconftest
2024-06-17T21:59:04.8171789Z     mod = import_path(
2024-06-17T21:59:04.8172547Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\pathlib.py", line 591, in import_path
2024-06-17T21:59:04.8173291Z     importlib.import_module(module_name)
2024-06-17T21:59:04.8173982Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\importlib\__init__.py", line 90, in import_module
2024-06-17T21:59:04.8174727Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-17T21:59:04.8175692Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\_pytest\assertion\rewrite.py", line 178, in exec_module
2024-06-17T21:59:04.8176445Z     exec(co, module.__dict__)
2024-06-17T21:59:04.8176999Z   File "D:\a\vws-python\vws-python\tests\conftest.py", line 11, in <module>
2024-06-17T21:59:04.8177512Z     from mock_vws import MockVWS
2024-06-17T21:59:04.8178274Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\mock_vws\__init__.py", line 5, in <module>
2024-06-17T21:59:04.8179081Z     from mock_vws._requests_mock_server.decorators import MockVWS
2024-06-17T21:59:04.8180112Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\mock_vws\_requests_mock_server\decorators.py", line 15, in <module>
2024-06-17T21:59:04.8180936Z     from mock_vws.image_matchers import (
2024-06-17T21:59:04.8181774Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\mock_vws\image_matchers.py", line 6, in <module>
2024-06-17T21:59:04.8182593Z     import piq  # type: ignore[import-untyped]
2024-06-17T21:59:04.8183426Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\piq\__init__.py", line 5, in <module>
2024-06-17T21:59:04.8184100Z     from .msid import MSID
2024-06-17T21:59:04.8184789Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\piq\msid.py", line 10, in <module>
2024-06-17T21:59:04.8185480Z     from piq.base import BaseFeatureMetric
2024-06-17T21:59:04.8186642Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\piq\base.py", line 3, in <module>
2024-06-17T21:59:04.8187370Z     from piq.feature_extractors import InceptionV3
2024-06-17T21:59:04.8188296Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\piq\feature_extractors\__init__.py", line 1, in <module>
2024-06-17T21:59:04.8189172Z     from piq.feature_extractors.fid_inception import InceptionV3
2024-06-17T21:59:04.8190190Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\piq\feature_extractors\fid_inception.py", line 13, in <module>
2024-06-17T21:59:04.8190993Z     from torchvision import models
2024-06-17T21:59:04.8191774Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
2024-06-17T21:59:04.8192719Z     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
2024-06-17T21:59:04.8193793Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
2024-06-17T21:59:04.8194533Z     from .convnext import *
2024-06-17T21:59:04.8195367Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
2024-06-17T21:59:04.8196189Z     from ..ops.misc import Conv2dNormActivation, Permute
2024-06-17T21:59:04.8197084Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
2024-06-17T21:59:04.8197844Z     from .poolers import MultiScaleRoIAlign
2024-06-17T21:59:04.8198692Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
2024-06-17T21:59:04.8199520Z     from .roi_align import roi_align
2024-06-17T21:59:04.8200344Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torchvision\ops\roi_align.py", line 4, in <module>
2024-06-17T21:59:04.8201074Z     import torch._dynamo
2024-06-17T21:59:04.8201838Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\__init__.py", line 64, in <module>
2024-06-17T21:59:04.8202600Z     torch.manual_seed = disable(torch.manual_seed)
2024-06-17T21:59:04.8203482Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\decorators.py", line 50, in disable
2024-06-17T21:59:04.8204210Z     return DisableContext()(fn)
2024-06-17T21:59:04.8205015Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\eval_frame.py", line 410, in __call__
2024-06-17T21:59:04.8205780Z     (filename is None or trace_rules.check(fn))
2024-06-17T21:59:04.8206629Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3378, in check
2024-06-17T21:59:04.8207422Z     return check_verbose(obj, is_inlined_call).skipped
2024-06-17T21:59:04.8208350Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3361, in check_verbose
2024-06-17T21:59:04.8209155Z     rule = torch._dynamo.trace_rules.lookup_inner(
2024-06-17T21:59:04.8210068Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3442, in lookup_inner
2024-06-17T21:59:04.8210868Z     rule = get_torch_obj_rule_map().get(obj, None)
2024-06-17T21:59:04.8211831Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 2782, in get_torch_obj_rule_map
2024-06-17T21:59:04.8212628Z     obj = load_object(k)
2024-06-17T21:59:04.8213424Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 2811, in load_object
2024-06-17T21:59:04.8214190Z     val = _load_obj_from_str(x[0])
2024-06-17T21:59:04.8215063Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 2795, in _load_obj_from_str
2024-06-17T21:59:04.8215949Z     return getattr(importlib.import_module(module), obj_name)
2024-06-17T21:59:04.8216783Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\importlib\__init__.py", line 90, in import_module
2024-06-17T21:59:04.8217540Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-17T21:59:04.8218533Z   File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\torch\nested\_internal\nested_tensor.py", line 417, in <module>
2024-06-17T21:59:04.8219354Z     values=torch.randn(3, 3, device="meta"),
```

**Comment by mscheltienne** [comment]
I also have windows CI failings on a downstream repository with `pytorch` 2.3.1 and `numpy` 2.0: https://github.com/mne-tools/mne-icalabel/pull/188
Looks like the 2.3.1 windows wheel was not compiled with `numpy` 2.0?

**Comment by BenjaminBossan** [comment]
I tested on [GitHub CI runners](https://github.com/BenjaminBossan/mops/pull/12) and can confirm that I also get the

> RuntimeError: Numpy is not available

error on `windows-latest`. On top of that, I also get it on `macos-13` and lower (Intel) but not `macos-latest` (arm).

Finally, `macos-latest` and `ubuntu-latest` are also affected for torch v2.2.2 (and presumably every version below). Downgrading to numpy v1.2.6 resolves the issue in all cases.

**Comment by albanD** [comment]
@huydhn I though we did that in https://github.com/pytorch/pytorch/issues/107302 already?
From the comment here I guess the windows side might not have been covered properly? Anything else missing?

Older releases not supporting NumPy 2.0 is expected and will not be fixed as per the usual policy we have on old releases patching.

**Comment by malfet** [comment]
PyTorch builds are now compatible with Numpy-2.0 and we are running some tests using Python-3.12
