### ISSUE TITLE
RelaxedOneHotCategorical not implementing entropy (and other abstract methods)

### ISSUE THREAD

**Issue by rmst** [pytorch/pytorch#12895]
## To Reproduce

```python
from torch.distributions import RelaxedOneHotCategorical
d = RelaxedOneHotCategorical(0.1, torch.tensor((0.1, 0.9)))
d.entropy()
```

throws a NotImplementedError

The methods `mean`, `variance` and `enumerate_support` don't seem to be implemented either.

## Expected behavior

One simple solution would be to implement the methods as follows

```python
  def entropy(self):
    return self.base_dist._categorical.entropy()
```

 - PyTorch Version: 0.4.1.post2 (I briefly checked the code in master and the methods don't seem to be implemented there either)
 - OS: Linux
 - How you installed PyTorch: conda
 - Python version: 3.6

**Comment by ezyang** [comment]
This is still valid:

```
>>> import torch
>>> from torch.distributions import RelaxedOneHotCategorical
>>> d = RelaxedOneHotCategorical(0.1, torch.tensor((0.1, 0.9)))
>>> d.entropy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/ezyang/pytorch-tmp2/torch/distributions/distribution.py", line 215, in entropy
    raise NotImplementedError
NotImplementedError
>>> print(torch.__version__)
1.9.0a0+gitc41083f
```
