### ISSUE TITLE
[PT2E Quantization] Graph with concatenation of the same node will raise RecursionError when prepare_pt2e

### ISSUE THREAD

**Issue by siahuat0727** [pytorch/pytorch#129038]
### 🐛 Describe the bug

Graph with **concatenation of the same node** will raise RecursionError when prepare_pt2e.

```python
import torch
import torch.export._trace
from torch import nn
from torch.ao.quantization.quantize_pt2e import prepare_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
    XNNPACKQuantizer,
    get_symmetric_quantization_config,
)

class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 3, 3)

    def forward(self, x):
        x = self.conv(x)  # not neccesary to have a conv to reproduce the bug
        x = torch.cat([x, x])
        return x

model = Net()
quantizer = XNNPACKQuantizer().set_global(get_symmetric_quantization_config())
model = torch.export._trace._export(
    model, (torch.rand(1, 3, 32, 32),), pre_dispatch=True
).module()
model = prepare_pt2e(model, quantizer)
```

Output
```
Traceback (most recent call last):
  File "reproduce_cat_recursion_error_bug.py", line 28, in <module>
    model = prepare_pt2e(model, quantizer)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/quantize_pt2e.py", line 109, in prepare_pt2e
    model = prepare(model, node_name_to_scope, is_qat=False)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 470, in prepare
    edge_or_node_to_group_id = _get_edge_or_node_to_group_id(edge_or_node_to_qspec)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 196, in _get_edge_or_node_to_group_id
    input_edge_root_qspec = _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 83, in _unwrap_shared_qspec
    return _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 83, in _unwrap_shared_qspec
    return _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 83, in _unwrap_shared_qspec
    return _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  [Previous line repeated 991 more times]
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 81, in _unwrap_shared_qspec
    root = _find_root_edge_or_node(sharing_with, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 42, in _find_root_edge_or_node
    parent = shared_with_map[edge_or_node]
RecursionError: maximum recursion depth exceeded in comparison
```

Note that `edge_or_node` is `(conv2d, cat)` when fails.

### Versions

`torch==2.3.1`

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @msaroufim @ezyang @anijain2305 @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by siahuat0727** [comment]
Maybe add a check before L992:
```python
        if input_act not in input_qspec_map:
```
https://github.com/pytorch/pytorch/blob/a584b2a389b9fcaa1cd4d92dcc6914f9cf92491b/torch/ao/quantization/quantizer/xnnpack_quantizer_utils.py#L985-L992

**Comment by masnesral** [comment]
cc current oncall @jcaip (I think). Not sure if adding the "oncall: quantization" tag is already enough to put on your radar?

**Comment by jcaip** [comment]
@siahuat0727 Thanks for flagging this, that fix looks fine to me. Can you create a PR and add @jerryzh168 to review?

**Comment by siahuat0727** [comment]
> @siahuat0727 Thanks for flagging this, that fix looks fine to me. Can you create a PR and add @jerryzh168 to review?

Sure

**Comment by dgcnz** [comment]
Had the same error and https://github.com/pytorch/pytorch/pull/129567 worked like a charm, thanks @siahuat0727 !
