### ISSUE TITLE
Torch Inductor uses CUDA memory even compiling CPU functions

### ISSUE THREAD

**Issue by hct-synth** [pytorch/pytorch#129131]
### 🐛 Describe the bug

When trying to compile even a simple function that uses CPU tensors, torch inductor allocates memory on cuda:0. If uses in a multiprocessing context (E.G.) a torch dataloader, this quickly results in OOM (simple repro example allocates 500MB of VRAM per process). 

`CUDA_VISIBLE_DEVICES=""` works as a workaround, however disables all use of CUDA in that process, which is undesirable.

This issue appears to stem from torch inductor not respecting the default device when allocating fake tensors:
https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/pad_mm.py#L636

(Logic refers to issue https://github.com/pytorch/pytorch/issues/97894)

### Error logs

Traceback (most recent call last):
  File "/home/hugh/synth/rnd-video-diffusion/src/videodiffusion/eg.py", line 11, in <module>
    some_fn(x)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/.../lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/.../lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/.../lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/.../lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/.../lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 971, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/.../lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1168, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1241, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/.../lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1222, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/.../lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/.../lib/python3.10/site-packages/torch/__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/.../lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/.../lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "/.../lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/.../lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/.../lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/.../lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/.../lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/.../lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1199, in fw_compiler_base
    _recursive_joint_graph_passes(model)
  File "/.../lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 207, in _recursive_joint_graph_passes
    joint_graph_passes(gm)
  File "/.../lib/python3.10/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 285, in joint_graph_passes
    lazy_init()
  File "/.../lib/python3.10/site-packages/torch/_inductor/pattern_matcher.py", line 1463, in lazy_init
    result = fn()
  File "/.../lib/python3.10/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 33, in lazy_init
    _pad_mm_init()
  File "/.../lib/python3.10/site-packages/torch/_inductor/fx_passes/pad_mm.py", line 530, in _pad_mm_init
    [dim2a(), dim2b()],
  File "/.../lib/python3.10/site-packages/torch/utils/_device.py", line 78, in __torch_function__
    return func(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 896, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1241, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 966, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1431, in _dispatch_impl
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_impls.py", line 180, in constructors
    return FakeTensor(fake_mode, r, out_device)
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 487, in __new__
    init_cuda_context()
  File "/.../lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 364, in init_cuda_context
    torch.empty(1, device="cuda") if torch.version.hip is None else torch.zeros(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Minified repro

import torch
# Force error if CUDA memory is used for debugging - this example normally allocates ~500MB of VRAM
torch.cuda.set_per_process_memory_fraction(0.0000001)

@torch.compile
def some_fn(x):
    return torch.pow(x, 0.1) / 2

with torch.device("cpu"):
    x = torch.ones([3, 1920, 1080], device="cpu")
    some_fn(x)

### Versions

torch==2.3.0
triton==2.3.0

**Comment by lezcano** [comment]
There's this abandoned PR: https://github.com/pytorch/pytorch/pull/124722
The current approach in the PR is too intrusive. It'd be better to just check whether there's any global dtype on, and if so, then use that. In the general case, you don't want to be passing around the `input_dtype`, but simply take the logic in
```
    inputs_devices = list(
        {i.device for i in pytree.tree_flatten(aot_example_inputs)[0]}
    ) + [None]
    assert len(inputs_devices) > 0
    lazy_init(input_device=next(iter(inputs_devices)))
```
and wrap the `lazy_init` into a `with torch.dtype...` construct.

Would you like to send a fix?

**Comment by lezcano** [comment]
Also, dupe of https://github.com/pytorch/pytorch/pull/124722

**Comment by lee-bin** [comment]
@hct-synth Where do you set `CUDA_VISIBLE_DEVICES=""` for the dataloader processes?

**Comment by StrongerXi** [comment]
Doing old issue scrubbing; I think this still repros, @eellison should we leave it open?

```python
import torch

@torch.compile
def some_fn(x):
    return torch.pow(x, 0.1) / 2

print(torch.cuda._initialized) # False
with torch.device("cpu"):
    x = torch.ones([3, 1920, 1080], device="cpu")
    print(torch.cuda._initialized) # False
    some_fn(x)
    print(torch.cuda._initialized) # True

print(torch.cuda._initialized) # True
# At a breakpoint here 400MB+ of VRAM will be in use due to initialisation of a CUDA context
```

**Comment by eellison** [comment]
Yes. repros with aot_eager.
