### ISSUE TITLE
Support for torch.Generator with JIT

### ISSUE THREAD

**Issue by bridgesign** [pytorch/pytorch#129282]
### 🚀 The feature, motivation and pitch

I am trying to sample random values in a jitted module and want to sample from different random sources a.k.a generators with different seeds. However, I get an error when I try to JIT  `torch.Generator`. As I did not find any documentation on support of Generators with `torch.jit`, I think it is not implemented but I am not sure. (That's why a feature request).

Below is a simple test and error associated with it.

```python
>>> import torch
>>> g_cpu = torch.Generator()
>>> g_cpu = torch.jit.script(g_cpu)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/_sources.py", line 23, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "/usr/lib/python3.10/inspect.py", line 1121, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.10/inspect.py", line 950, in findsource
    raise OSError('source code not available')
OSError: source code not available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 1405, in script
    return torch.jit._recursive.create_script_class(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 525, in create_script_class
    _compile_and_register_class(type(obj), rcb, qualified_class_name)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 59, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/frontend.py", line 266, in get_jit_class_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(
  File "/usr/local/lib/python3.10/dist-packages/torch/_sources.py", line 32, in get_source_lines_and_file
    raise OSError(msg) from e
OSError: Can't get source for <class 'torch._C.Generator'>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
```

This seems to be a different problem from the following issue as it is about typing support:
[[JIT] allow Optional[torch.Generator] be tracable in Python](https://github.com/pytorch/pytorch/issues/69006)

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by malfet** [comment]
Thank you for creating the issue. Although JIT project is in the maintenance mode right now, i.e. no new features/enhancements are planned for it

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
