### ISSUE TITLE
Does it still make sense to prevent saving multiple tensors that have a shared storage but different dtypes?

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#129356]
Here we raise an exception if multiple tensors with a common storage have different dtypes:

https://github.com/pytorch/pytorch/blob/d21f311af880c736b18b5a588583f6162e9abcfa/torch/serialization.py#L808-L816

However in the related issue, @kurtamohler indicates that the fact that we're switching to untyped storages may resolve this issue

https://github.com/pytorch/pytorch/issues/58970#issuecomment-848444799

## Context
 
In tensordict, we are building a method to consolidate a series of arbitrary tensors on a common device into a single storage
https://github.com/pytorch/tensordict/pull/814

The storage and metadata are written in the `tensordict._consolidated` dictionary. It's easy to serialize / deserialize this but if one makes a view of the tensordict, eg
```python
data = td.consolidate()
data = data[0]
```
then the view lacks the `_consolidated` attribute. In that case we can't really tell pickle what to do and fall back on regular serialization methods. Saving such an object will fail because of the common storage check. 
Note that we can pass that data through a `mp.Pipe`, only `torch.save` currently fails.

**Comment by mikaylagawarecki** [comment]
I don't particularly understand why this check is needed, @kurtamohler could you share more details here please

**Comment by kurtamohler** [comment]
It should in principle be possible to save tensors of different dtypes that view the same data.

However, in https://github.com/pytorch/pytorch/issues/58970#issuecomment-848435011, @ezyang suggested that we shouldn't make this change because it would not be forward compatible. I don't really understand/remember how it breaks FC though. Sure, if a user saves a set of tensors that view the same data with different dtypes, the save file cannot be loaded by older versions of pytorch. But to give another situation that I think is analogous, if we add a new kind of `nn.Module` and a user saves an instance of it, that file cannot be loaded by older versions of pytorch either. But we wouldn't consider that FC-breaking because the new module is simply a new feature that didn't exist in older versions.

I think a change only breaks serialization FC if a save file generated by the new version only relies on features that the old version supports, and yet the save file cannot be loaded by the old version. I can't think of a reason why that would happen if we enable saving tensors that view the same data with different dtypes. If the change really wouldn't break FC, then I'm happy to do it

**Comment by ezyang** [comment]
We should eventually support this. The reason I told Kurt not to support it is because the "obvious" way to implement it isn't FC. So for FC reasons we need to do something different but ONLY when you have a mixed dtype situation.

**Comment by mikaylagawarecki** [comment]
fwiw this error if we remove this check seems to be around resizing of storages, will investigate further

```python
>>> import torch
# float32 and chalf for both v2 and v3 dtypes
>>> sd = {'t': torch.randn(2, 3), 'b': torch.randn(2, 3).to(torch.chalf)}
<stdin>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /data/users/mg1998/pytorch/aten/src/ATen/EmptyTensor.cpp:44.)
>>> sd['t1'] = sd['t'].view(torch.float16)
>>> sd['b1'] = sd['b'].view(torch.float32)
>>> torch.save(sd, "bla.pt")
>>> torch.load("bla.pt")
<stdin>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/mg1998/pytorch/torch/serialization.py", line 1226, in load
    return _load(
  File "/data/users/mg1998/pytorch/torch/serialization.py", line 1713, in _load
    result = unpickler.load()
  File "/data/users/mg1998/pytorch/torch/_utils.py", line 206, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/data/users/mg1998/pytorch/torch/_utils.py", line 179, in _rebuild_tensor
    return t.set_(storage._untyped_storage, storage_offset, size, stride)
RuntimeError: Trying to resize storage that is not resizable
```

**Comment by vmoens** [comment]
We're still investigating the error with @mikaylagawarecki to see how that could be enabled.

Regarding the FC compatibility issue: @albanD was proposing the following scheme, where we 
- establish a window for FC to be safe
- at `t=0` within that window, we upgrade `torch.load` to make it compatible with that feature
- at `t=T` within that window we update `torch.save` and enable the feature to be used.

That way, any PT build that is of `-T` time in the past will be able to read saved tensors if these point to the same storage even when they have different dtypes.

Would that be a suitable solution? What would be the appropriate window for this?

@ezyang @kurtamohler @mikaylagawarecki

**Comment by ezyang** [comment]
So, if we don't mind the format being more complicated, I'd just suggest we detect if we are the same dtype situation and do the old format, and only if we detect multi-dtype do we switch to the new format...

**Comment by vmoens** [comment]
Got it!
Recap: 
- we can patch the `load` to allow for untyped storage used with multiple tensors with different dtypes, and patch `save` subsequently. The complexity of doing so would need to be investigated as currently `save` and `load` rely on typed storages.
- we could have an if/else within save and a corresponding adaptive behaviour on the `load` side to account for this use case. Long term, this behaviour could be the default for load/save (since it's more generic and doesn't rely on typed storages),  and since we'll have both options available we will be able to finely select in which case the previous or new serialization logic should be used.
