### ISSUE TITLE
Flaky Test Bot isn't considering a distributed test failure to be a test failure

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#129382]
The test `distributed/_tensor/test_convolution_ops.py::DistConvolutionOpsTest::test_depthwise_convolution` has been regularly failing on distributed builds, but out CI tools don't realize that this was a test failure that should be retried, disabled, or even highlighted in the log classifier

**Goal: Root cause and fix why this test failure isn't being noticed**

Repro cases (filter to the `pull / linux-jammy-py3.8-gcc11 / test (distributed` jobs):

https://hud.pytorch.org/failure?name=pull%20%2F%20linux-jammy-py3.8-gcc11%20%2F%20test%20(distributed%2C%201%2C%202%2C%20linux.2xlarge)&jobName=linux-jammy-py3.8-gcc11%20%2F%20test%20(distributed%2C%201%2C%202%2C%20linux.2xlarge)&failureCaptures=%5B%22Process%20completed%20with%20exit%20code%201.%22%5D

Relevant logs:

```
2024-06-21T22:20:53.1812605Z Running 2 items in this shard: test/distributed/_tensor/test_convolution_ops.py::DistConvolutionOpsTest::test_depthwise_convolution, test/distributed/_tensor/test_convolution_ops.py::DistConvolutionOpsTest::test_downsampling_convolution
2024-06-21T22:20:53.1814973Z 
2024-06-21T22:20:53.1817911Z distributed/_tensor/test_convolution_ops.py::DistConvolutionOpsTest::test_depthwise_convolution /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/_tensor/random.py:37: UserWarning: DTensor random operators may not have complete support on cpu device mesh
2024-06-21T22:20:53.1821073Z   warnings.warn(
2024-06-21T22:20:53.1822268Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] Caught exception: 
2024-06-21T22:20:53.1824451Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] Traceback (most recent call last):
2024-06-21T22:20:53.1827658Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 657, in run_test
2024-06-21T22:20:53.1829495Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     getattr(self, test_name)()
2024-06-21T22:20:53.1831494Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 539, in wrapper
2024-06-21T22:20:53.1833182Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     fn()
2024-06-21T22:20:53.1834997Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2739, in wrapper
2024-06-21T22:20:53.1836928Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     method(*args, **kwargs)
2024-06-21T22:20:53.1838976Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 369, in wrapper
2024-06-21T22:20:53.1841118Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     func(self, *args, **kwargs)  # type: ignore[misc]
2024-06-21T22:20:53.1843048Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/var/lib/jenkins/workspace/test/distributed/_tensor/test_convolution_ops.py", line 128, in test_depthwise_convolution
2024-06-21T22:20:53.1844857Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     model = distribute_module(
2024-06-21T22:20:53.1846919Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/_tensor/api.py", line 790, in distribute_module
2024-06-21T22:20:53.1848783Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     partition_fn(name, submod, device_mesh)
2024-06-21T22:20:53.1850566Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/var/lib/jenkins/workspace/test/distributed/_tensor/test_convolution_ops.py", line 33, in _conv_fn
2024-06-21T22:20:53.1852364Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     distribute_tensor(param, device_mesh, dist_spec)
2024-06-21T22:20:53.1854550Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/_tensor/api.py", line 679, in distribute_tensor
2024-06-21T22:20:53.1858093Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     local_tensor = placement._replicate_tensor(local_tensor, device_mesh, idx)
2024-06-21T22:20:53.1862237Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/_tensor/placement_types.py", line 386, in _replicate_tensor
2024-06-21T22:20:53.1865753Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     mesh_broadcast(tensor, mesh, mesh_dim=mesh_dim)
2024-06-21T22:20:53.1869471Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/_tensor/_collective_utils.py", line 160, in mesh_broadcast
2024-06-21T22:20:53.1873400Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     return broadcast(tensor, src=src_for_dim, group=dim_group, async_op=async_op)
2024-06-21T22:20:53.1877189Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
2024-06-21T22:20:53.1880250Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     return func(*args, **kwargs)
2024-06-21T22:20:53.1883751Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
2024-06-21T22:20:53.1886885Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]     work.wait()
2024-06-21T22:20:53.1890154Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [172.17.0.2]:15764: Connection reset by peer
2024-06-21T22:20:53.1893260Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] 
2024-06-21T22:20:53.1895530Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] To execute this test, run the following from the base repo dir:
2024-06-21T22:20:53.1899690Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]      python test/distributed/_tensor/test_convolution_ops.py -k DistConvolutionOpsTest.test_depthwise_convolution
2024-06-21T22:20:53.1902456Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] 
2024-06-21T22:20:53.1904889Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-06-21T22:20:53.1907657Z [rank1]:E0621 22:20:51.207085 140200183793472 torch/testing/_internal/common_distributed.py:664]  exiting process 1 with exit code: 10
2024-06-21T22:20:53.1909356Z ('RERUN', {'yellow': True}) [15.3025s] [ 50%]
2024-06-21T22:20:53.1910688Z distributed/_tensor/test_convolution_ops.py::DistConvolutionOpsTest::test_depthwise_convolution 
```

cc @kit1980 @huydhn @clee2000

**Comment by ZainRizvi** [comment]
Oddly enough, this test was auto-disabled by our tooling a month and a half ago, and was then also automatically re-enabled a few days later

**Comment by clee2000** [comment]
I can't find the logs for this job anymore and the link provided doesn't give info about runs at the time that it failed
