### ISSUE TITLE
A process got stuck in TCPStore::get

### ISSUE THREAD

**Issue by ChuBoning** [pytorch/pytorch#129367]
### 🐛 Describe the bug

I tried to use 8 ranks to run a model. However I entered a port that was occupied.Rank 0 report the error:
![image](https://github.com/pytorch/pytorch/assets/102216855/5b05b904-da0b-4ab5-82c2-43e881dd6002)
And 1-7 ranks (except rank 3) report:
![image](https://github.com/pytorch/pytorch/assets/102216855/8bd80122-da30-4dcc-a025-891f8e04af78)
rank 3 got stuck,and the stack is:
(gdb) bt
#0  __libc_recv (flags=<optimized out>, len=1303328157216, buf=0x7e4687969059, fd=98) at ../sysdeps/unix/sysv/linux/recv.c:28
#1  __libc_recv (fd=98, buf=0x7e4687969059, len=1303328157216, flags=0) at ../sysdeps/unix/sysv/linux/recv.c:23
#2  0x00007f778b8ae63f in void c10d::tcputil::recvBytes<unsigned char>(int, unsigned char*, unsigned long) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#3  0x00007f778b8ae77d in std::vector<unsigned char, std::allocator<unsigned char> > c10d::tcputil::recvVector<unsigned char>(int) ()
   from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#4  0x00007f778b8aca2b in c10d::TCPStore::doGet(std::string const&) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#5  0x00007f778b8acd55 in c10d::TCPStore::get(std::string const&) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#6  0x00007f778b864561 in c10d::PrefixStore::get(std::string const&) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#7  0x00007f778b864561 in c10d::PrefixStore::get(std::string const&) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#8  0x00007f778b864561 in c10d::PrefixStore::get(std::string const&) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#9  0x00007f7743c90b79 in c10d_npu::ProcessGroupHCCL::broadcastMasterID(HcclRootInfoDef*) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch_npu/lib/libtorch_npu.so
#10 0x00007f7743c97afb in c10d_npu::ProcessGroupHCCL::getHCCLComm(std::string const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d_npu::HcclCommType) ()
   from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch_npu/lib/libtorch_npu.so
#11 0x00007f7743c98cd8 in c10d_npu::ProcessGroupHCCL::getHcclCommName(int) () from /home/anaconda3/envs/wyt_all_21/lib/python3.8/site-packages/torch_npu/lib/libtorch_npu.so
#12 0x00007f7743c813bf in pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<std::string, c10d_npu::ProcessGroupHCCL, int, pybind11::name, pybind11::is_method, pybind11::sibling>(std::string (c10d_npu::ProcessGroupHCCL::*)(int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(c10d_npu::ProcessGroupHCCL*, int)#1}, std::string, c10d_npu::ProcessGroupHCCL*, int, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<std::string, c10d_npu::ProcessGroupHCCL, int, pybind11::name, pybind11::is_method, pybind11::sibling>(std::string (c10d_npu::ProcessGroupHCCL::*)(int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(c10d_npu::ProcessGroupHCCL*, int)#1}&&, std::string (*)(c10d_npu::ProcessGroupHCCL*, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) ()

The errors reported are normal, but it's strange to get stuck in rank 3.
Here is the source code:
![image](https://github.com/pytorch/pytorch/assets/102216855/48b7023e-dc16-4657-b595-697260391c6f)
It seemed that doWait is ok but got stuck in receiveBits.Under what circumstances does this problem occur？

### Versions

PyTorch version: 2.1.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          192
On-line CPU(s) list:             0-191
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           143
Model name:                      Intel(R) Xeon(R) Platinum 8468V
Stepping:                        8
CPU MHz:                         2900.000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       4.5 MiB
L1i cache:                       3 MiB
L2 cache:                        192 MiB
L3 cache:                        195 MiB
NUMA node0 CPU(s):               0-47,96-143
NUMA node1 CPU(s):               48-95,144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid cldemote movdiri movdir64b md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0+cpu
[pip3] torch-npu==2.1.0.post3-20240620
[pip3] torchmetrics==1.3.0.post0
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by wz337** [comment]
@ChuBoning Does changing the port to be a non-occupied one fixing the issue? 
Or is it the concern that rank 3 is not providing the correct error?

**Comment by ChuBoning** [comment]
> @ChuBoning Does changing the port to be a non-occupied one fixing the issue? Or is it the concern that rank 3 is not providing the correct error?

A non-occupied port can fix the issue,but it is the concern that rank 3 is not providing the correct error.It shouldn't be stuck

**Comment by XilunWu** [comment]
The reason of the error output on non-0 ranks is, they do not know what root cause leads to the connection failure. Yes rank 0 knows it's an occupied port, but the other ranks do not. They only see that a connection timeout happens.
