### ISSUE TITLE
Upgrade dependencies MKL and Intel OpenMP to 2024.2.0

### ISSUE THREAD

**Issue by WhiteByeBye** [pytorch/pytorch#129310]
### 🚀 The feature, motivation and pitch

The latest build (version 2.3.1) seems to rely on `MKL & Intel OpenMP = 2021.4.0`, while their most recent versions are now 2024.2.0. 

When I habitually updated all my Python packages, these two dependencies were also upgraded to their latest versions (2024.2.0), and I found that PyTorch lost its ability to use the GPU (obviously). I assume the latest versions of these dependencies might offer slight performance improvements (though I haven't fact-checked this, sorry). Is it possible to build PyTorch with the newest versions of MKL and Intel OpenMP?

I understand this may not be a priority for the community, and I don't want to add more noise either. However, perhaps this could be considered as an enhancement plan for future implementation.

**Comment by malfet** [comment]
@WhiteByeBye please run `python3 -mtorch.utils.collect_env` and post its output here (or append to the issue) Namely I'm curious about your host OS and whether PyTorch was installed from PyPI or Anaconda. I suspect you Windows and PyPI

cc: @jgong5 @atalman , do you know why we pin the mkl dependency to 2021.4.0 on Windows? (Linux ones are built against a more recent version if I'm not mistaken), see
```
$ curl https://pypi.org/pypi/torch/json|jq ".info.requires_dist"|grep mkl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  441k  100  441k    0     0  17.2M      0 --:--:-- --:--:-- --:--:-- 17.2M
  "mkl<=2021.4.0,>=2021.1.1; platform_system == \"Windows\"",
```
Also, perhaps todo for 2.5.0: why not link with MKL dynamically on both Linux and Windows?

**Comment by WhiteByeBye** [comment]
> Please run `python3 -mtorch.utils.collect_env` and post its output here (or append to the issue) Namely I'm curious about your host OS and whether PyTorch was installed from PyPI or Anaconda. I suspect you Windows and PyPI

You are correct! And the following is the output. There are some new warnings (science I move to preview version 2.5.0dev to check if the dependencies are latest (2024.2.0)).

```
User: System32 ❯ python -m torch.utils.collect_env

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Program Files\Python312\Lib\site-packages\torch\__init__.py", line 2318, in <module>
    from torch import export as export
  File "C:\Program Files\Python312\Lib\site-packages\torch\export\__init__.py", line 67, in <module>
    from .unflatten import FlatArgsAdapter, unflatten, UnflattenedModule
  File "C:\Program Files\Python312\Lib\site-packages\torch\export\unflatten.py", line 26, in <module>
    from ._remove_effect_tokens_pass import _remove_effect_tokens
  File "C:\Program Files\Python312\Lib\site-packages\torch\export\_remove_effect_tokens_pass.py", line 6, in <module>
    from torch._higher_order_ops.effects import _get_schema, with_effects
  File "C:\Program Files\Python312\Lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "C:\Program Files\Python312\Lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "C:\Program Files\Python312\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "C:\Program Files\Python312\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
C:\Program Files\Python312\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
<frozen runpy>:128: RuntimeWarning: 'torch.utils.collect_env' found in sys.modules after import of package 'torch.utils', but prior to execution of 'torch.utils.collect_env'; this may result in unpredictable behaviour
Collecting environment information...
PyTorch version: 2.5.0.dev20240620+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro for Workstations
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.29.6
Libc version: N/A

Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 555.99
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3000
DeviceID=CPU0
Family=207
L2CacheSize=32768
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3000
Name=13th Gen Intel(R) Core(TM) i9-13900KF
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==2.0.0
[pip3] optree==0.11.0
[pip3] torch==2.5.0.dev20240620+cu124
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.4.0.dev20240620+cu124
[pip3] torchvision==0.20.0.dev20240620+cu124
[conda] Could not collect
```

**Comment by yanbing-j** [comment]
Hi @malfet,

For your information, in linux platform, PyTorch conda wheel and pip wheel are using different MKL version, conda wheel will dynamic link MKL 2023 ([conda/pytorch-nightly/meta.yaml](https://github.com/pytorch/builder/blob/main/conda/pytorch-nightly/meta.yaml#L18-L45)), and pip wheel will static link MKL 2022 ([install_mkl.sh](https://github.com/pytorch/builder/blob/main/common/install_mkl.sh)).

**Comment by xuhancn** [comment]
> @WhiteByeBye please run `python3 -mtorch.utils.collect_env` and post its output here (or append to the issue) Namely I'm curious about your host OS and whether PyTorch was installed from PyPI or Anaconda. I suspect you Windows and PyPI
> 
> cc: @jgong5 @atalman , do you know why we pin the mkl dependency to 2021.4.0 on Windows? (Linux ones are built against a more recent version if I'm not mistaken), see
> 
> ```
> $ curl https://pypi.org/pypi/torch/json|jq ".info.requires_dist"|grep mkl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  441k  100  441k    0     0  17.2M      0 --:--:-- --:--:-- --:--:-- 17.2M
>   "mkl<=2021.4.0,>=2021.1.1; platform_system == \"Windows\"",
> ```
> 
> Also, perhaps todo for 2.5.0: why not link with MKL dynamically on both Linux and Windows?

Hi @malfet , we use latest mkl version in our builder system: https://github.com/pytorch/builder/blob/d032d62b5dd9251901bf4349d9cf4af45eae647a/windows/condaenv.bat#L12

Linux seems use mkl 2022.2.1: https://github.com/pytorch/builder/blob/d032d62b5dd9251901bf4349d9cf4af45eae647a/common/install_mkl.sh#L6 

CC: @jgong5

**Comment by atalman** [comment]
@malfet Looks like the pipy mkl update ``mkl<=2021.4.0,>=2021.1.1`` was done here: https://github.com/pytorch/pytorch/pull/102604/files#r1419944305

There is a followup PR to update pypi windows to: https://github.com/pytorch/pytorch/pull/118200 that was never landed. Perhaps we should look into reopening this

**Comment by xuhancn** [comment]
> @malfet Looks like the pipy mkl update `mkl<=2021.4.0,>=2021.1.1` was done here: https://github.com/pytorch/pytorch/pull/102604/files#r1419944305
> 
> There is a followup PR to update pypi windows to: #118200 that was never landed. Perhaps we should look into reopening this

Hi @atalman , @malfet , @jgong5 
Current Windows build is using static build, it removed mkl dependency. I think the remained question is if we need pin mkl version to 2022.2.1.

**Comment by xuhancn** [comment]
Link to my PR, which clean up pytorch Windows 2.4 mkl shared mkl dependency.
Link: https://github.com/pytorch/pytorch/pull/129493

**Comment by atalman** [comment]
hi @xuhancn thanks for https://github.com/pytorch/pytorch/pull/129493 lets see if the windows-binary-wheel workflow is successful: https://github.com/pytorch/pytorch/actions/runs/9704252023/job/26784121458?pr=129493 , will mere it then

**Comment by atalman** [comment]
Please note on conda we can only update to 2023.1. This is the latest on official conda releases: https://anaconda.org/anaconda/mkl/files?version=2023.1.0

**Comment by xuhancn** [comment]
> Please note on conda we can only update to 2023.1. This is the latest on official conda releases: https://anaconda.org/anaconda/mkl For conda builds we are still using dynamic mkl
> 
> However looks like Intel did released mkl-inlude and mkl-static on conda forge now 2 days ago: https://anaconda.org/conda-forge/mkl-static/files Should we try to update conda builds to static as well ?

I think we need update conda builds to mkl-static also, but how to do it? @atalman

**Comment by atalman** [comment]
hi @xuhancn Here is the conda meta.yaml : https://github.com/pytorch/builder/blob/main/conda/pytorch-nightly/meta.yaml the change will have to be made here, and possibly in some conda build scripts

**Comment by xuhancn** [comment]
> hi @xuhancn Here is the conda meta.yaml : https://github.com/pytorch/builder/blob/main/conda/pytorch-nightly/meta.yaml the change will have to be made here, and possibly in some conda build scripts

@atalman Tried to switch to mkl-static: https://github.com/pytorch/builder/pull/1914
