### ISSUE TITLE
The ProcessGroupNCCL is not being destructed

### ISSUE THREAD

**Issue by zhouzaida** [pytorch/pytorch#129477]
### 🐛 Describe the bug

When I use PyTorch's `multiprocessing` to launch a multi-GPU task, if I terminate the program with Ctrl-C, it might result in the child processes not being killed, which leads to the GPU memory not being released (**the ProcessGroupNCCL is not being destructed**). The error message is as follows:

```python
Traceback (most recent call last):
  File "~/miniconda3/envs/py310-cu118-pt230/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 237, in start_processes
    while not context.join():
  File "~/miniconda3/envs/pyt310-cu118-pt230/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 117, in join
    ready = multiprocessing.connection.wait(
  File "~/miniconda3/envs/py310-cu118-pt230/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "~/miniconda3/envs/py310-cu118-pt230/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
^CException ignored in atexit callback: <function _exit_function at
```

But sometimes the subprocesses can be killed and print the following information:

```python
[rank1]:[I ProcessGroupNCCL.cpp:1109] [PG 1 Rank 1] ProcessGroupNCCL destructor entered.
[rank1]:[I ProcessGroupNCCL.cpp:1094] [PG 1 Rank 1] Launching ProcessGroupNCCL abort asynchrounously.
[rank1]:[I ProcessGroupNCCL.cpp:999] [PG 1 Rank 1] future is successfully executed for: ProcessGroup abort
[rank1]:[I ProcessGroupNCCL.cpp:1100] [PG 1 Rank 1] ProcessGroupNCCL aborts successfully.
[rank1]:[I ProcessGroupNCCL.cpp:1132] [PG 1 Rank 1] ProcessGroupNCCL watchdog thread joined.
[rank1]:[I ProcessGroupNCCL.cpp:1136] [PG 1 Rank 1] ProcessGroupNCCL heart beat monitor thread joined.
[rank1]:[I ProcessGroupNCCL.cpp:1109] [PG 2 Rank 1] ProcessGroupNCCL destructor entered.
[rank1]:[I ProcessGroupNCCL.cpp:1094] [PG 2 Rank 1] Launching ProcessGroupNCCL abort asynchrounously.
[rank1]:[I ProcessGroupNCCL.cpp:999] [PG 2 Rank 1] future is successfully executed for: ProcessGroup abort
[rank1]:[I ProcessGroupNCCL.cpp:1100] [PG 2 Rank 1] ProcessGroupNCCL aborts successfully.
[rank1]:[I ProcessGroupNCCL.cpp:1132] [PG 2 Rank 1] ProcessGroupNCCL watchdog thread joined.
[rank1]:[I ProcessGroupNCCL.cpp:1136] [PG 2 Rank 1] ProcessGroupNCCL heart beat monitor thread joined.
[rank0]:[I ProcessGroupNCCL.cpp:1109] [PG 1 Rank 0] ProcessGroupNCCL destructor entered.
[rank0]:[I ProcessGroupNCCL.cpp:1094] [PG 1 Rank 0] Launching ProcessGroupNCCL abort asynchrounously.
[rank0]:[I ProcessGroupNCCL.cpp:999] [PG 1 Rank 0] future is successfully executed for: ProcessGroup abort
[rank0]:[I ProcessGroupNCCL.cpp:1100] [PG 1 Rank 0] ProcessGroupNCCL aborts successfully.
[rank0]:[I ProcessGroupNCCL.cpp:1132] [PG 1 Rank 0] ProcessGroupNCCL watchdog thread joined.
```

### Versions

```python
Python 3.10
NCCL version: 2.20.5
torch                     2.3.0+cu118
```

**Comment by zhouzaida** [comment]
Hi @malfet ,is there any progress?

**Comment by zhouzaida** [comment]
Hi @awgu , could you take a look at this issue?

**Comment by awgu** [comment]
Hey @zhouzaida! Sorry, I am going to be out for the next week. Hopefully, my team's next oncall can get to this.

**Comment by zhouzaida** [comment]
Thanks for your reply.

**Comment by LucasLLC** [comment]
@zhouzaida , your sleep statement is making me think something in the forward code may be relevant. Could you please update the example w/ a filled out forward and except block instead of the placeholders?

**Comment by zhouzaida** [comment]
Hi @LucasLLC , thanks for your reply. The below is the full example (python ddp.py):

```python
import os

import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(1000, 1000)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(1000, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

def setup(rank, world_size):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12355 "

    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)


def cleanup():
    dist.destroy_process_group()


def ddp_example(rank, world_size):
    setup(rank, world_size)
    
    print(f"Start running basic DDP example on rank {rank}.")

    # create model and move it to GPU with id rank
    device_id = rank % torch.cuda.device_count()
    model = ToyModel().to(device_id)
    ddp_model = DDP(model, device_ids=[device_id])

    print(f"Starting forward pass on rank {rank}.")
    for _ in range(1000000):
        # if we remove the try except block here,
        # the program will not hang and the processgroupnccl will be destructed
        try:
            ddp_model(torch.rand(1000, 1000, device="cuda")).sum().backward()
        except:
            pass

    cleanup()


if __name__ == "__main__":
    world_size = torch.cuda.device_count()
    mp.spawn(
        ddp_example,
        args=(world_size,),
        nprocs=world_size,
        join=True,
    )

```

**Comment by zhouzaida** [comment]
Hi @LucasLLC , thanks for your reply. The below is the full example:

```python
import os

import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader


class Dataset(torch.utils.data.Dataset):
    def __init__(self):
        self.data = torch.randn(1000, 1000)

    def __len__(self):
        return 100000000

    def __getitem__(self, idx):
        return self.data


class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(1000, 1000)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(1000, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

def setup(rank, world_size):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12355 "

    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)


def cleanup():
    dist.destroy_process_group()


def ddp_example(rank, world_size):
    setup(rank, world_size)
    
    print(f"Start running basic DDP example on rank {rank}.")

    dataloader = DataLoader(Dataset(), batch_size=32, shuffle=True, num_workers=10, persistent_workers=True)

    # create model and move it to GPU with id rank
    device_id = rank % torch.cuda.device_count()
    model = ToyModel().to(device_id)
    ddp_model = DDP(model, device_ids=[device_id])

    print(f"Starting forward pass on rank {rank}.")
    try:
        for data in dataloader:
            ddp_model(data.to('cuda')).sum().backward()
    except:
        pass

    cleanup()


if __name__ == "__main__":
    world_size = torch.cuda.device_count()
    mp.spawn(
        ddp_example,
        args=(world_size,),
        nprocs=world_size,
        join=True,
    )
```

**Comment by ppwwyyxx** [comment]
Child processes created by `mp.spawn` are killed by SIGINT when parent dies: https://github.com/pytorch/pytorch/blob/da24823e067f5b9cbedd7d491c28e88c5d1b963a/torch/multiprocessing/spawn.py#L68-L73

This is not reliable: SIGINT is not able to terminate a Python process if the process is executing a blocking C-extension (e.g. a nccl collective). Such child processes will be left alive. 

Changing the above signal to SIGTERM seems to help. I tried the code from @zhouzaida , the orphan process cannot be killed by `kill -SIGINT` but can be killed by `kill -SIGTERM`.

**Comment by wconstab** [comment]
I wonder if you could use torchrun to launch your job? 

Also, you may want to look at our unit test helpers which launch and join processes inside the base class test case. Look at tests in test_c10d_nccl.py and find their base class in some utils file. It might point you to a more reliable way.

**Comment by ppwwyyxx** [comment]
torchrun don't have this issue but it's not a direct replacement. For example, one can have Python logic before `start_processes` to create data to be shared between processes - this is not easily doable with torchrun.

The test case call `process.terminate()`: https://github.com/pytorch/pytorch/blob/0fee7d028139149a3a9581d924975ea361abe7ae/torch/testing/_internal/common_distributed.py#L565-L573 which sends a SIGTERM. The point is that `torch.multiprocessing.start_processes` should provide a reliable way.

**Comment by LucasLLC** [comment]
I think likely the original motivation was that `SIGINT` is the correct error code for processes being terminated by the user. However, it makes sense to me that if the main process receives a SIGNINT, it can send a `SIGTERM` to child processes.

I think we'd accept a PR affecting this change, but likely would have to track down the right people to review.
