### ISSUE TITLE
torch 2.3 incomplete error message

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#129632]
### 🐛 Describe the bug

The following code:
```
import torch
x = torch.ones((int(90e9),), device='cuda', dtype=torch.uint8)
x.fill_(2.)
```
run under the environment variable `TORCH_SHOW_CPP_STACKTRACES=1`.

In torch 2.2, the error is:
```
Traceback (most recent call last):
  File "/home/XXX/a.py", line 2, in <module>
    x = torch.ones((int(90e9),), device='cuda', dtype=torch.uint8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 83.82 GiB. GPU 0 has a total capacity of 79.35 GiB of which 78.40 GiB is free. Process 3456282 has 969.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 b
ytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/c
uda.html#environment-variables)
Exception raised from malloc at ../c10/cuda/CUDACachingAllocator.cpp:1125 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f4ae499cd87 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x34e80 (0x7f4ae4a4fe80 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x35124 (0x7f4ae4a50124 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x354d6 (0x7f4ae4a504d6 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x17a3619 (0x7f4b1c59e619 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, std::optional<c10::MemoryFormat>) + 0x14 (0x7f4b1c5981d4 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_
cpu.so)
frame #6: at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, std::optional<c10::Device>, std::optional<c10::MemoryFormat>) + 0x111 (0x7f4ae5a2b711 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::detail::empty_cuda(c10::ArrayRef<long>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, std::optional<c10::MemoryFormat>) + 0x36 (0x7f4ae5a2b9e6 in /home/XXX/.pyenv/versions/torch
22/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #8: at::native::empty_cuda(c10::ArrayRef<long>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, std::optional<c10::MemoryFormat>) + 0x20 (0x7f4ae5b75400 in /home/XXX/.pyenv/versions/torch
22/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #9: <unknown function> + 0x3039db9 (0x7f4ae7ae1db9 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0x3039e9b (0x7f4ae7ae1e9b in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #11: at::_ops::empty_memory_format::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, std::optional<c10::MemoryFormat>) + 0xe7 (0x7
f4b1d563de7 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2b04faf (0x7f4b1d8fffaf in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #13: at::_ops::empty_memory_format::call(c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, std::optional<c10::MemoryFormat>) + 0x1a0 (0x7f4b1d5a9ce0 in /home/XXX
/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x195ef16 (0x7f4b1c759f16 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #15: at::native::full(c10::ArrayRef<long>, c10::Scalar const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>) + 0x100 (0x7f4b1cd09f70 in /home/XXX/.pyenv/versions/torch22/lib/python3.10/
site-packages/torch/lib/libtorch_cpu.so)
frame #16: at::native::ones(c10::ArrayRef<long>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>) + 0x4b (0x7f4b1cd0a05b in /home/XXX/.pyenv/versions/torch22/lib/python3.10/site-packages/torch/l
ib/libtorch_cpu.so)
```

In torch2.3, the error is:
```
Traceback (most recent call last):
  File "/home/yuxin/a.py", line 2, in <module>
    x = torch.ones((int(90e9),), device='cuda', dtype=torch.uint8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 83.82 GiB. GPU
```

1. The error message is truncated
2. cpp stack trace is not shown.

### Versions

```
 python -m torch.utils.collect_env
<frozen runpy>:128: RuntimeWarning: 'torch.utils.collect_env' found in sys.modules after import of package 'torch.utils', but prior to execution of 'torch.utils.collect_env'; this may result in unpredictable behaviour
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 14.1.1 20240522
Clang version: 17.0.6
CMake version: version 3.29.6
Libc version: glibc-2.39
```

**Comment by ppwwyyxx** [comment]
OK looks like it got fixed in https://github.com/pytorch/pytorch/pull/123984
