### ISSUE TITLE
Pytorch nightly aarch64 build is failing

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#129693]
### 🐛 Describe the bug

Following failure during build 
```
-- asimd/Neon found with compiler flag : -D__NEON__
CMake Error at cmake/Modules/FindBLAS.cmake:413 (check_function_exists):
  Unknown CMake command "check_function_exists".
Call Stack (most recent call first):
  cmake/Modules/FindLAPACK.cmake:22 (FIND_PACKAGE)
  cmake/Dependencies.cmake:1442 (find_package)
  CMakeLists.txt:853 (include)


-- Configuring incomplete, errors occurred!
ls: cannot access //pytorch//dist: No such file or directory
Traceback (most recent call last):
  File "/builder/aarch64_linux/aarch64_wheel_ci_build.py", line 217, in <module>
    pytorch_wheel_name = complete_wheel("/pytorch/")
  File "/builder/aarch64_linux/aarch64_wheel_ci_build.py", line 117, in complete_wheel
    wheel_name = list_dir(f"/{folder}/dist")[0]
  File "/builder/aarch64_linux/aarch64_wheel_ci_build.py", line 15, in list_dir
    return check_output(["ls", "-1", path]).decode().split("\n")
  File "/opt/conda/envs/aarch64_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/envs/aarch64_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ls', '-1', '//pytorch//dist']' returned non-zero exit status 2.
```

Workflow:
https://github.com/pytorch/pytorch/actions/runs/9692530872/job/26779703817

### Versions

2.5.0 nightly 

cc @seemethere @malfet @osalpekar

**Comment by malfet** [comment]
The source of the regression cmake version update from 3.29.3 to 3.29.6
