### ISSUE TITLE
`torch.nn.function.one_hot` and `torch.Tensor.as_subclass` API not available under `torch.compile`

### ISSUE THREAD

**Issue by Thinksky5124** [pytorch/pytorch#129651]
### 🐛 Describe the bug

Some of pytorch's apis are not available under `torch.compile`

## 1 - `torch.nn.function.one_hot`
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import numpy as np

def make(*args, **kwargs):
    @torch.compile(backend='inductor')
    def f():
        x, target = args
        target[target < 0] = 80 - 1
        one_hot = F.one_hot(target, 80)  # N x C+1
    return f

for i in range(32):
    shape = np.random.randint(10, 40)
    x = torch.randn(shape, 80, requires_grad=True).cuda()
    target = torch.randint(0, 80, (shape,)).cuda()
    make(x, target)()
```

Error

```txt
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function one_hot>(*(FakeTensor(..., device='cuda:0', size=(s1,), dtype=torch.int64), 80), **{}):
Cannot call sizes() on tensor with symbolic sizes/strides
```

## 2 - `torch.Tensor.as_subclass`
```python
import torch
import torch.nn as nn
import math
import numpy as np

def make(*args, **kwargs):
    @torch.compile(backend='inductor')
    def f():
        x = args
        x = [f.as_subclass(torch.Tensor) for f in x]
    return f

for i in range(32):
    shape = np.random.randint(10, 40)
    x = torch.randn(16, 3, shape, shape).cuda()
    make(x)()
```

Error
```torch._dynamo.exc.InternalTorchDynamoError: argument of type: <class 'torch._C._TensorMeta'>```

### Versions

| Env                     | Version                |
| -----------             | -----------            |
| Python                  | 3.8.18                 |
| CUDA                    | 12.2                   |
| Torch                   | 2.1.0+cu118            |
| Torchvision             | 0.16.0+cu118           |
| GPU                     | 2 * RTX4090            |
| CPU                     | Intel-i7-12700KF       |
| Ubuntu                  | 22.04                  |

cc @ezyang @albanD @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by bdhirsh** [comment]
FYI @Thinksky5124 I ran the first repro locally on my nightly and it doesn't repro - can you try a nightly?

For the second issue, we probably just graph break on `as_subclass()` calls in dynamo (cc @mlazos).

**Comment by Thinksky5124** [comment]
I run the first repro locally on pytorch version `https://download.pytorch.org/whl/nightly/cu121`, It seems to be solved. By the way in the pytorch version 2.2.0, the first issue remains, not sure if 2.3.0 exists.

But the second problem remains. 

```txt
Traceback (most recent call last):
  File "/home/thinksky/AIHPC-Larning/test.py", line 16, in <module>
    make(x)()
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 434, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1121, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 948, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 846, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 233, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1270, in transform_code_object
    transformations(instructions, code_options)
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2476, in run
    super().run()
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2083, in CALL
    self.call_function(fn, args, kwargs)
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 95, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 760, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2691, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2807, in inline_call_
    tracer.run()
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 904, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 816, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 510, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2083, in CALL
    self.call_function(fn, args, kwargs)
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 754, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/variables/misc.py", line 745, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/variables/tensor.py", line 477, in call_method
    tx.output.create_proxy(
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 540, in create_proxy
    return self.current_tracer.create_proxy(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1872, in create_proxy
    rv = super().create_proxy(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/fx/proxy.py", line 196, in create_proxy
    args_ = self.create_arg(args)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/fx/_symbolic_trace.py", line 424, in create_arg
    return super().create_arg(a)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/fx/proxy.py", line 263, in create_arg
    return type(a)(self.create_arg(elem) for elem in a)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/fx/proxy.py", line 263, in <genexpr>
    return type(a)(self.create_arg(elem) for elem in a)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/fx/_symbolic_trace.py", line 424, in create_arg
    return super().create_arg(a)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thinksky/miniconda3/envs/torch_nightly/lib/python3.11/site-packages/torch/fx/proxy.py", line 299, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
torch._dynamo.exc.InternalTorchDynamoError: argument of type: <class 'torch._C._TensorMeta'>

from user code:
   File "/home/thinksky/AIHPC-Larning/test.py", line 10, in f
    x = [f.as_subclass(torch.Tensor) for f in x]
  File "/home/thinksky/AIHPC-Larning/test.py", line 10, in <listcomp>
    x = [f.as_subclass(torch.Tensor) for f in x]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by mlazos** [comment]
Hi everyone, I think this can be fixed. I'm curious why you're calling as_subclass with a normal torch.Tensor arg? isn't that a no-op?

**Comment by StrongerXi** [comment]
Both examples have been fixed on main 8e987a14bee. I think we can close this? @mlazos @bdhirsh @IlyasMoutawwakil
