### ISSUE TITLE
CPU Fusion compiler fails on NVIDIA AGX Xavier

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#12978]
## 🐛 Bug

```
======================================================================
ERROR: test_ge_optimized (__main__.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 200, in wrapper
    fn(*args, **kwargs)
  File "test_jit.py", line 1423, in test_ge_optimized
    self.run_ge_tests(True, False)
  File "test_jit.py", line 1397, in run_ge_tests
    optimize=optimize)
  File "test_jit.py", line 297, in checkTrace
    ge = torch.jit.trace(func, input_tensors, optimize=optimize, check_tolerance=check_tolerance)
  File "/home/nvidia/code/pytorch/torch/jit/__init__.py", line 572, in trace
    _check_trace([example_inputs], func, executor_options, module, check_tolerance)
  File "/home/nvidia/code/pytorch/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/nvidia/code/pytorch/torch/jit/__init__.py", line 474, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(module, inputs, 'trace')
  File "/home/nvidia/code/pytorch/torch/jit/__init__.py", line 443, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
        Failed to compile a fused CPU kernel (runCompiler at /home/nvidia/code/pytorch/torch/csrc/jit/fusers/cpu/fused_kernel.cpp:56)
        frame #0: <unknown function> + 0x5dc044 (0x7f5fdde044 in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #1: torch::jit::cpufuser::CPUFusedKernel::CPUFusedKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, torch::jit::AnnotatedGraph&, torch::jit::cpufuser::CPUFusionCompilerConfig&)
+ 0xe2c (0x7f5fddf74c in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #2: torch::jit::FusionHandleImpl::compileSpec(torch::jit::FusionArgSpec const&, std::vector<long, std::allocator<long> > const&) + 0x8c4 (0x7f5fdcc6ec in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #3: torch::jit::FusionHandleImpl::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x2b8 (0x7f5fdcdd78 in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #4: <unknown function> + 0x532a3c (0x7f5fd34a3c in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #5: <unknown function> + 0x4b7fd0 (0x7f5fcb9fd0 in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #6: <unknown function> + 0x4a2e98 (0x7f5fca4e98 in /home/nvidia/code/pytorch/torch/lib/libtorch.so.1)
        frame #7: <unknown function> + 0x3defc4 (0x7f70f11fc4 in /home/nvidia/code/pytorch/torch/_C.so)
        frame #8: <unknown function> + 0x3c0cd4 (0x7f70ef3cd4 in /home/nvidia/code/pytorch/torch/_C.so)
        frame #9: <unknown function> + 0x11bed4 (0x7f70c4eed4 in /home/nvidia/code/pytorch/torch/_C.so)
        <omitting python frames>
```

## To Reproduce

1. Run `test_jit.py`

## Environment

- PyTorch version: 1.0.0a0+01227f3
- Is debug build: No
- CUDA used to build PyTorch: 10.0.117

- OS: Ubuntu 18.04 LTS
- GCC version: (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 7.3.0
- CMake version: version 3.10.2

- Python version: 2.7
- Is CUDA available: Yes
- CUDA runtime version: 10.0.117
- GPU models and configuration: Could not collect
- Nvidia driver version: Could not collect
- cuDNN version: Probably one of the following:
    - /usr/lib/aarch64-linux-gnu/libcudnn.so.7.3.0
    - /usr/lib/aarch64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
- [pip] Could not collect
- [conda] Could not collect

**Comment by zdevito** [comment]
This looks out of date so I am closing. Reopen if this is still broken.
