### ISSUE TITLE
[inductor][cpu]test_comprehensive_masked_logsumexp_cpu_int64 will fail on AVX2

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#129863]
### 🐛 Describe the bug

TestInductorOpInfoCPU.test_comprehensive_masked_logsumexp_cpu_int64 will fail on AVX2, other ISA is OK.

**Error logs**
```
This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
=================================== FAILURES ===================================
_____ TestInductorOpInfoCPU.test_comprehensive_masked_logsumexp_cpu_int64 ______
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 1121, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 1382, in only_fn
    return fn(self, *args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1940, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 1189, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 1189, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1363, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1312, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "inductor/test_torchinductor_opinfo.py", line 542, in inner
    raise e
  File "inductor/test_torchinductor_opinfo.py", line 534, in inner
    fn(self, device, dtype, op)
  File "inductor/test_torchinductor_opinfo.py", line 778, in test_comprehensive
    raise e
  File "inductor/test_torchinductor_opinfo.py", line 760, in test_comprehensive
    self.check_model(
  File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 487, in check_model
    self.assertEqual(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3631, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not equal!

Mismatched elements: 2 / 12 (16.7%)
Greatest absolute difference: 9223372034707292160 at index (0, 0, 0, 0)
Greatest relative difference: 0.0 at index (0, 0, 0, 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 446, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1363, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 1127, in test_wrapper
    raise Exception(  # noqa: TRY002
Exception: Caused by sample input at index 48: SampleInput(input=Tensor[size=(3, 2, 1, 2), device="cpu", dtype=torch.int64], args=(), kwargs={'mask': 'Tensor[size=(3, 2, 1, 2), device="cpu", dtype=torch.bool]', 'dim': '2', 'keepdim': 'True'}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
     python test/inductor/test_torchinductor_opinfo.py -k TestInductorOpInfoCPU.test_comprehensive_masked_logsumexp_cpu_int64
```

**Repro**
```python test/inductor/test_torchinductor_opinfo.py -k TestInductorOpInfoCPU.test_compd_logsumexp_cpu_int64```

### Versions

https://github.com/pytorch/pytorch/commit/eb1583dbc1a8c4a8f0d1525438f16350f11f1208

cc @ezyang @anijain2305 @chauhang @penguinwu @CaoE

**Comment by malfet** [comment]
Related to https://github.com/pytorch/pytorch/issues/123224

**Comment by jgong5** [comment]
> Related to #123224

This issue was discovered while we enable the AVX2 CI. See https://github.com/pytorch/pytorch/pull/128682
