### ISSUE TITLE
Signature change of optimizer step function results in omission of `_check_inf_per_device ` in GradScaler

### ISSUE THREAD

**Issue by syed-ahmed** [pytorch/pytorch#129922]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/123751 changed the signature of the optimizer step function (by removing `@wraps(func)`). `GradScaler` relies on the signature to push `grad_scaler` kwarg to the custom optimizer step: https://github.com/pytorch/pytorch/blob/600bf978ba1e3f4e5df9b4d51547cacded4514cc/torch/amp/grad_scaler.py#L411-L413. Since `grad_scaler` is not present in the kwargs, optimizer step in apex doesn't receive it: 

https://github.com/NVIDIA/apex/blob/f8e60c47c5c3034ddf8181e33910f3da5b289f25/apex/optimizers/fused_adam.py#L203-L206

and subsequently we end up with the following error, since `_check_inf_per_device` is not called:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/home/bug.py", line 72, in <module>
[rank0]:     main()
[rank0]:   File "/opt/home/bug.py", line 69, in main
[rank0]:     grad_scaler.update()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/amp/grad_scaler.py", line 512, in update
[rank0]:     assert len(found_infs) > 0, "No inf checks were recorded prior to update."
[rank0]: AssertionError: No inf checks were recorded prior to update.
```

There seems to be several ways this can be resolved. Which one is preferred? @janeyx99 @crcrpar @mlazos @eqy  @ptrblck 
1. Add back `@wraps(func)` to the wrapper function in lr_scheduler. Note that without this, the function signature is:
```
(Pdb) inspect.signature(optimizer.step)
<Signature (*args, **kwargs)>
(Pdb) inspect.signature(optimizer.step).parameters
mappingproxy(OrderedDict([('args', <Parameter "*args">), ('kwargs', <Parameter "**kwargs">)]))
```
vs with `@wraps(func)`:
```
(Pdb) inspect.signature(optimizer.step)
<Signature (self, closure: Optional[Callable] = None, *, grad_scaler: Optional[torch.cuda.amp.grad_scaler.GradScaler] = None)>
(Pdb) inspect.signature(optimizer.step).parameters
mappingproxy(OrderedDict([('self', <Parameter "self">), ('closure', <Parameter "closure: Optional[Callable] = None">), ('grad_scaler', <Parameter "grad_scaler: Optional[torch.cuda.amp.grad_scaler.GradScaler] = None">)]))
```
2. Revert https://github.com/pytorch/pytorch/pull/98620/ and recompute `found_inf`.
3. Make changes in apex. I read that grad_scaler kwarg is deprecated. May be we should remove that in apex step function and call `_check_inf_per_device` based on something else (is it "Tensor attributes of `grad_scale` and `found_inf`"?)

### Versions

Happens on main branch.
To reproduce:
```
import torch.distributed as dist
import torch
import torch.nn as nn
import os
import torch, torch.nn as nn, torch.optim as optim
from apex.contrib.optimizers.distributed_fused_adam import DistributedFusedAdam
import copy

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

def main():
    local_rank = int(os.environ['LOCAL_RANK'])
    global_rank = int(os.environ['RANK'])
    world_size = int(os.environ['WORLD_SIZE'])
    device = torch.device(f"cuda:{local_rank}")
    torch.cuda.set_device(device)
    torch.manual_seed(global_rank)
    learning_rate = 0.0001
    decay = 0
    num_iters = 30
    amp = True

    dist.init_process_group(backend='nccl', init_method='env://')
    world_group = torch.distributed.new_group(ranks=[i for i in range(world_size)])
    self_groups = [torch.distributed.new_group(ranks=[i]) for i in range(world_size)]

    model = ToyModel().to(device).half()
    loss_fn = nn.CrossEntropyLoss().to(device)
    

    optimizer = DistributedFusedAdam(
        model.parameters(),
        lr=learning_rate,
        weight_decay=decay,
        overlap_grad_sync=False,
        contiguous_param_buffer=True,
        contiguous_grad_buffer=True,
        distributed_process_group=self_groups[global_rank],
        redundant_process_group=world_group,
        grad_sync_dtype=torch.float16 if amp else torch.float32,
        param_sync_dtype=torch.float16 if amp else torch.float32
    )
  
    grad_scaler = torch.amp.GradScaler('cuda', init_scale=1024)
    
    sched = optim.lr_scheduler.StepLR(
        optimizer, 
        step_size=10)
    input = torch.randn(20, 10).to(device)
    input = input.half()
    labels = torch.ones(20, 5).to(device)

    for i in range(num_iters):
        optimizer.zero_grad()
        outputs = model(input)
        loss = loss_fn(outputs, labels)
        grad_scaler.scale(loss).backward()
        grad_scaler.step(optimizer)
        grad_scaler.update()

if __name__ == "__main__":
    main()

```
```[tasklist]
### Tasks
```

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by mlazos** [comment]
@syed-ahmed I think I'm okay with either 1 or 3, I'm happy to sign off on PRs for either, and could get to 1 myself next week if not.

**Comment by mlazos** [comment]
@syed-ahmed jk, just sent a PR adding wraps back, I don't think there was a specific issue that required its removal.
