### ISSUE TITLE
Error when exporting a module without input

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#129927]
### 🐛 Describe the bug

Might be related to Issue #118304. However, I'm seeing the error message below even with the fix in #129928

```python
class M(torch.nn.Module):
    def forward(self):
        full = torch.full((), 11)
        i0 = full.item()
        return (torch.full((i0,), 0), )

args = ()
gm = torch.export.export(M(), ())  # .module()
```

Error message:

```bash
Traceback (most recent call last):
  File "/Users/shangdiy/Desktop/pytorch/test.py", line 28, in <module>
    gm = torch.export.export(M(), ())  # .module()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/__init__.py", line 173, in export
    return _export(
           ^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/_trace.py", line 1000, in wrapper
    raise e
  File "/Users/shangdiy/Desktop/pytorch/torch/export/_trace.py", line 983, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/exported_program.py", line 98, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/_trace.py", line 1871, in _export
    export_artifact = export_func(
                      ^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/_trace.py", line 1116, in _strict_export
    return _strict_export_lower_to_aten_ir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/_trace.py", line 1245, in _strict_export_lower_to_aten_ir
    aten_export_artifact = lower_to_aten_callback(
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/export/_trace.py", line 630, in _export_to_aten_ir
    gm, graph_signature = transform(aot_export_module)(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_functorch/aot_autograd.py", line 1163, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_functorch/aot_autograd.py", line 1385, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_dynamo/utils.py", line 233, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_functorch/aot_autograd.py", line 584, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 163, in inner
    flat_f_outs = f(*flat_f_args)
                  ^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_functorch/_aot_autograd/utils.py", line 178, in flat_fn
    tree_out = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 760, in functional_call
    out = PropagateUnbackedSymInts(mod).run(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/fx/interpreter.py", line 146, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/shangdiy/Desktop/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5487, in run_node
    rebind_unbacked(detect_fake_mode().shape_env, n, result)
  File "/Users/shangdiy/Desktop/pytorch/torch/fx/experimental/symbolic_shapes.py", line 331, in rebind_unbacked
    assert raw_u0 != raw_u1, f"{raw_u0} possible memo disaster"
           ^^^^^^^^^^^^^^^^
AssertionError: u0 possible memo disaster

While executing %item : [num_users=4] = call_method[target=item](args = (%full,), kwargs = {})
Original traceback:
  File "/Users/shangdiy/Desktop/pytorch/test.py", line 23, in forward
    i0 = full.item()

```

### Versions

PyTorch version: 2.5.0a0+git62422e9
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Apple M2

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[pip3] torch==2.5.0a0+git62422e9
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.5.0a0+git62422e9           dev_0    <develop>
[conda] torchfix                  0.4.0                    pypi_0    pypi

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @penguinwu

**Comment by angelayi** [comment]
We probably need to fix [this code](https://github.com/pytorch/pytorch/blob/eebe7e1d37f1baa995c694d540cc2fc98884fa18/torch/_functorch/aot_autograd.py#L434-L439) to look at the metadata for the fake mode.
Or we could run a pass after exporting w/ dynamo to remove ["unbacked_bindings"](https://github.com/pytorch/pytorch/blob/39357ba06f48cda7d293a4995aa5eba2a46598b5/torch/fx/experimental/symbolic_shapes.py#L301) from node.meta.

**Comment by yushangdi** [comment]
> We could fix [this code](https://github.com/pytorch/pytorch/blob/eebe7e1d37f1baa995c694d540cc2fc98884fa18/torch/_functorch/aot_autograd.py#L434-L439) to look at the node.meta["val"] for the fake mode, instead of only looking at the input arguments. Or we could run a pass after exporting w/ dynamo to remove ["unbacked_bindings"](https://github.com/pytorch/pytorch/blob/39357ba06f48cda7d293a4995aa5eba2a46598b5/torch/fx/experimental/symbolic_shapes.py#L301) from node.meta:
> 
> ```
>     for node in gm_torch_level.graph.nodes:
>         if "unbacked_bindings" in node.meta:
>             del node.meta["unbacked_bindings"]
> ```

Do you mean something like this? https://github.com/pytorch/pytorch/pull/130007

I'm curious why it's save for us to remove those "unbacked_bindings"?
