### ISSUE TITLE
Meta device not supported with autocast

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#130067]
### 🐛 Describe the bug

While looking at https://github.com/pytorch/pytorch/issues/128394, we ran into the error that autocast does not support meta device being passed in.

This shows up in transformers's [modeling_llama.py](https://github.com/huggingface/transformers/blob/048f599f3506e57e0a595b455d9d2834c8d45023/src/transformers/models/llama/modeling_llama.py#L115)

A small repro is:
```
    def test_autocast(self):
        if not torch.cuda.is_bf16_supported():
            raise unittest.SkipTest("requires bf16")

        class MyModule(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.a_float32 = torch.rand((8, 8), device="cuda")
                self.b_float32 = torch.rand((8, 8), device="cuda")
                self.d_float32 = torch.rand((8, 8), device="cuda")

            def forward(self, x):
                device_type = x.device.type
                device_type = device_type if isinstance(device_type, str) else "cpu"
                with torch.autocast(device_type, enabled=False):
                    e_float16 = torch.mm(self.a_float32, self.b_float32)
                    f_float16 = torch.mm(self.d_float32, e_float16)
                return f_float16

        module = MyModule().to("meta")
        inp = (torch.tensor([0.5], device="meta"),)
        real = module(*inp)
```
With the error being:
```
Traceback (most recent call last):
  File "/data/users/angelayi/pytorch/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/data/users/angelayi/pytorch/test/export/test_export.py", line 5433, in test_autocast
    real = module(*inp)
  File "/data/users/angelayi/pytorch/torch/nn/modules/module.py", line 1714, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/nn/modules/module.py", line 1725, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/angelayi/pytorch/test/export/test_export.py", line 5426, in forward
    with torch.autocast(device_type, enabled=False):
  File "/data/users/angelayi/pytorch/torch/amp/autocast_mode.py", line 230, in __init__
    dtype = torch.get_autocast_dtype(device_type)
RuntimeError: unsupported scalarType
```

### Versions

main

**Comment by albanD** [comment]
While we could easily allow this, I'm not sure it will do what you want.
Autocast rules are device and dtype specific. So the trace will no match what would happen if you were to use whichever device you're looking for.

Maybe you want to use FakeTensor to have a proper device for which the rules exist?

**Comment by kwen2501** [comment]
Thanks @albanD. 
n00b question, what is the FakeTensor alternative to the following code?
```
with torch.device("meta"):
    llama = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
    inputs = tokenizer(prompts, return_tensors="pt", padding=True)
```
Thanks!

**Comment by albanD** [comment]
I would say 
```
with torch._subclasses.FakeTensorMode():
    ...
```

Not sure how well that works in the hf stack though.

**Comment by minbo-wang** [comment]
> > While we could easily allow this, I'm not sure it will do what you want.
> 
> I'm looking at results of jit-tracing (in cuda) which contain plain dtype conversions (and not autocast enter/exit calls) and I think that's exactly what I want - just trace a graph with meta-device, as if i traced real tensors.
> 
> [@albanD](https://github.com/albanD) if there is a way to specify this behavior on user end, I'd be happy to use it

@arogozhnikov  so, have you got the way?

**Comment by arogozhnikov** [comment]
> so, have you got the way?

nope, not using meta-device anymore.
