### ISSUE TITLE
Test failure when running pytorch without cuDNN

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#1301]
```
# compile pytorch without cudnn
$ python test_nn.py TestNN.test_variable_sequence_cuda
/data/users/alerer/pytorch/pytorch/torch/backends/cudnn/__init__.py:40: UserWarning: PyTorch was compiled without cuDNN support. To use cuDNN, rebuild PyTorch making sure the library is visible to the build system.
======================================================================
FAIL: test_variable_sequence_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 1501, in test_variable_sequence_cuda
    self._test_variable_sequence(True)
  File "test_nn.py", line 1492, in _test_variable_sequence
    self.assertEqual(x_leaf.grad.data, grad_x)
  File "/data/users/alerer/pytorch/pytorch/test/common.py", line 158, in assertEqual
    assertTensorsEqual(x, y)
  File "/data/users/alerer/pytorch/pytorch/test/common.py", line 150, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: 0.2056929971275647 not less than or equal to 1e-05 :
```

**Comment by apaszke** [comment]
It seems to be broken because of the fused RNN kernels commit. If I add `False and` to [this condition](https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/rnn.py#L23), then the test passes (with `torch.backends.cudnn.enabled = False` set before). @csarofeen

**Comment by csarofeen** [comment]
Working on this. I understand the problem, and am working on a fix.

**Comment by csarofeen** [comment]
@apaszke @adamlerer Thanks for finding this and bringing it to my attention.
