### ISSUE TITLE
[Inductor] Incorrect strides for function containing `torch.empty_strided`. Causes output to crash.

### ISSUE THREAD

**Issue by blaine-rister** [pytorch/pytorch#130394]
### 🐛 Describe the bug

Hi, I was hoping to get help using Inductor to compile programs with discontiguous outputs. This may seem like an obscure use case but it's important for certain hardware accelerators. 

Inductor seems to use the wrong strides when `torch.empty_strided` creates an output tensor. In the following program, I expect the output strides to be `(16,1)`, as in eager mode. Instead, Inductor uses contiguous strides of `(8,1)`:
```
import torch

device = torch.device("cuda")
full = torch.randn((16, 16)).to(device)
view = torch.as_strided(full, (16, 8), full.stride())

def foo(x):
    result = x + x
    result_strided = torch.empty_strided(x.size(), x.stride(), device=device)
    result_strided[:] = result
    return result_strided

eager_result = foo(view)

compiled_foo = torch.compile(foo, backend="inductor")
compiled_result = compiled_foo(view)

assert compiled_result.stride() == eager_result.stride()
```

The assertion fails:
```
Traceback (most recent call last):
  File "/home/brister/test_padding_wrong_strides.py", line 18, in <module>
    assert compiled_result.stride() == eager_result.stride()
AssertionError
```

This can lead to a correctness issue, as calling `torch.as_strided` on the output causes Inductor to return an invalid tensor:
```
import torch

device = torch.device("cuda")
full = torch.randn((16, 16)).to(device)
view = torch.as_strided(full, (16, 8), full.stride())

def foo(x):
    result = x + x
    result_strided = torch.empty_strided(x.size(), x.stride(), device=device)
    result_strided[:] = result
    return torch.as_strided(result_strided, result_strided.size(), x.stride())

eager_result = foo(view)
print('\n\nEager result:')
print(eager_result)

compiled_foo = torch.compile(foo, backend="inductor")
compiled_result = compiled_foo(view)
print('\n\nCompiled result:')
print(compiled_result)             
```

The output is:
```
Eager result:
tensor([[-1.9191e+00, -9.9364e-01,  2.7343e+00,  3.8158e-01,  2.6018e+00,
          7.2199e-04,  4.2154e-01, -3.6633e-01],
        [ 1.9658e+00,  1.4934e-03,  4.8586e-02, -1.0864e-01, -1.0975e+00,
         -1.2657e+00, -1.7973e+00,  2.1852e+00],
        [ 3.1229e-01,  2.0248e+00,  2.4957e+00,  1.2117e+00, -2.1294e+00,
         -1.5332e+00, -2.3192e+00, -1.1214e-01],
        [-2.2408e+00,  9.0849e-01, -2.0530e+00, -1.0669e+00,  1.1546e+00,
         -4.4620e+00, -1.5520e+00, -4.5037e-01],
        [-5.6579e-02,  1.6490e+00, -8.4768e-01, -3.3583e+00, -2.3183e+00,
          2.3846e+00,  2.1071e+00, -1.0147e+00],
        [ 1.4566e+00, -5.8106e-01,  1.2685e+00,  3.9002e+00, -2.3972e+00,
          1.9856e+00, -9.7874e-01, -1.9117e+00],
        [-9.2953e-02,  1.1793e+00,  9.8296e-01,  2.7822e+00,  1.2876e+00,
          1.4123e+00, -3.9539e-02, -1.9377e+00],
        [-8.1993e-01,  4.7476e+00, -1.8478e+00, -1.3737e+00, -3.3559e-01,
          1.0162e-01,  1.5843e+00,  1.2504e+00],
        [ 9.0944e-01,  7.3267e-01,  1.4168e+00, -2.5459e+00, -1.3898e+00,
          6.7621e-01, -1.3263e+00,  8.7106e-01],
        [ 1.1192e+00, -3.8516e+00, -3.4478e+00, -2.1786e+00, -9.5769e-01,
          4.1877e+00,  1.0502e+00,  1.3480e+00],
        [-3.0413e+00, -3.4837e+00, -8.3844e-01,  2.9216e-01, -3.9086e-01,
         -4.4565e-01,  4.1650e-01,  1.3133e+00],
        [ 2.2269e+00,  3.5410e-01,  2.9001e+00,  5.7174e-01,  3.0786e-01,
         -3.9775e+00, -1.1836e+00,  8.9351e-01],
        [ 1.5400e+00,  1.9593e+00,  1.5753e+00, -2.1872e+00,  2.5408e+00,
          3.7106e-01,  3.5535e+00,  6.1770e-01],
        [-4.8369e-01, -2.3293e+00,  1.8427e+00, -9.8587e-02,  1.2536e+00,
          2.8813e-01, -3.4177e-01, -1.2205e+00],
        [-1.0270e-01,  3.9507e-01,  8.7445e-01, -2.8494e+00, -2.2721e+00,
         -3.6759e+00,  7.6545e-01,  1.9305e+00],
        [-6.9283e-01,  7.5761e-01,  6.3600e-01, -1.6220e+00, -3.1843e-01,
         -1.2160e+00, -5.5611e-02,  3.0697e+00]], device='cuda:0')


Compiled result:
Traceback (most recent call last):
  File "/home/brister/test_padding_crash.py", line 20, in <module>
    print(compiled_result)
  File "/data/users/brister/pytorch/torch/_tensor.py", line 464, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/data/users/brister/pytorch/torch/_tensor_str.py", line 698, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/data/users/brister/pytorch/torch/_tensor_str.py", line 618, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/data/users/brister/pytorch/torch/_tensor_str.py", line 351, in _tensor_str
    return _tensor_str_with_formatter(self, indent, summarize, formatter)
  File "/data/users/brister/pytorch/torch/_tensor_str.py", line 292, in _tensor_str_with_formatter
    slices = [
  File "/data/users/brister/pytorch/torch/_tensor_str.py", line 294, in <listcomp>
    self[i], indent + 1, summarize, formatter1, formatter2
RuntimeError: setStorage: sizes [8], strides [1], storage offset 128, and itemsize 4 requiring a storage size of 544 are out of bounds for storage of size 512
```

Eager mode returned a valid tensor which could be printed, while Inductor seems to have used an invalid stride.

Any help would be greatly appreciated!

### Versions

```
Collecting environment information...
PyTorch version: 2.4.0a0+gitc4348f4
Is debug build: True
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.12.0-0_fbk14_zion_7533_g0df3a3e4e046-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA PG509-210
Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          22
On-line CPU(s) list:             0-21
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              1
Core(s) per socket:              22
Socket(s):                       1
Stepping:                        11
BogoMIPS:                        3591.75
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 arat umip pku ospke avx512_vnni md_clear arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       704 KiB (22 instances)
L1i cache:                       704 KiB (22 instances)
L2 cache:                        88 MiB (22 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-21
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[pip3] pytorch-triton==3.0.0+45fff310c8
[pip3] torch==2.5.0a0+gitaace8ff
[pip3] torchbenchmark==0.0.7
[conda] blas                      1.0                         mkl  
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch-triton            3.0.0+45fff310c8          pypi_0    pypi
[conda] torch                     2.5.0a0+gitaace8ff           dev_0    <develop>
[conda] torchbenchmark            0.0.7                    pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by ezyang** [comment]
This is intentional, but you have some outs (but maybe we don't have APIs for it).

We had a lot of debates about whether or not PT2 was required to produce exactly matching strides for outputs matching eager semantics. The overall conclusion we came to was (1) no, it doesn't have to, and (2) yes this can change behavior. Not having to preserve exact striding opens up optimization opportunities like changing up memory layout.

To force Inductor to produce exactly the same strides, we have a way to do this but only for custom op calls ala https://github.com/pytorch/pytorch/issues/130243  But I'm not sure we actually have an API for doing it on output. We should add one.

cc @zou3519 @oulgen

**Comment by Chillee** [comment]
@ezyang Wait... I thought we do exactly match strides for outputs?

**Comment by blaine-rister** [comment]
@ezyang @Chillee  thanks for the context. Forcing Inductor to follow the strides produced by eager mode does seem constraining. @eellison pointed out that `torch.as_strided` may not be always be safe e.g. #104505.

My use case is seems similar to #130243. I don't really have to use `torch.as_strided`. What I'm really trying to do is to force the generated triton kernels to use a specific memory layout, which might work better on certain hardware. So whatever approach is developed for user-defined kernels could also be helpful here.

**Comment by eellison** [comment]
@Chillee correct we only match dense strides currently. We do this as part of the other work to match triton kernel exact strides.

**Comment by ezyang** [comment]
It seems like it should be useful to match non-dense strides too?

**Comment by eellison** [comment]
Yes, we should, and I think @FindHao has it on his docket to do.
