### ISSUE TITLE
Cannot call numel() on tensor with symbolic sizes/strides 

### ISSUE THREAD

**Issue by yaxan** [pytorch/pytorch#130358]
### 🐛 Describe the bug

When attempting to save the inputs to a graph that supports dynamic shapes, torch.save throws a runtime error because it is attempting to call numel() on tensor with symbolic sizes/strides.

Example code to reproduce:
```
import torch
from typing import List

def bar(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

def custom_backend(gm: torch.fx.GraphModule,  example_inputs: List[torch.Tensor]):
    torch.save(example_inputs, "./example_inputs.zip", pickle_protocol=4)

    return gm.forward

compiled_bar = torch.compile(bar, backend=custom_backend)

compiled_bar(torch.randn(2), torch.randn(2))
compiled_bar(torch.randn(4), torch.randn(4))
```

Full trace:
```
Traceback (most recent call last):
  File "/home/ubuntu/code/dynamicshape.py", line 21, in <module>
    compiled_bar(torch.randn(4), torch.randn(4))
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 395, in inner
    self.output.compile_subgraph(
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 981, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1178, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1251, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1232, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/__init__.py", line 1770, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
  File "/home/ubuntu/code/dynamicshape.py", line 14, in custom_backend
    torch.save(example_inputs, "./example_inputs.zip", pickle_protocol=4)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/serialization.py", line 628, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/serialization.py", line 840, in _save
    pickler.dump(obj)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_tensor.py", line 219, in __reduce_ex__
    func, args = self._reduce_ex_internal(proto)
  File "/home/ubuntu/code/venv/lib/python3.10/site-packages/torch/_tensor.py", line 381, in _reduce_ex_internal
    self.data_ptr() == 0
torch._dynamo.exc.BackendCompilerFailed: backend='custom_backend' raised:
RuntimeError: Cannot call numel() on tensor with symbolic sizes/strides
Exception raised from throw_cannot_call_with_symbolic at ../c10/core/TensorImpl.cpp:298 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f49bc77a897 in /home/ubuntu/code/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::TensorImpl::throw_cannot_call_with_symbolic(char const*) const + 0x9c (0x7f49bc7291ec in /home/ubuntu/code/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x60f7f (0x7f49bc755f7f in /home/ubuntu/code/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x51684a (0x7f49bb11684a in /home/ubuntu/code/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
```

### Versions

[pip3] numpy==2.0.0
[pip3] torch==2.3.1
[pip3] triton==2.3.1

cc @ezyang @anijain2305 @chauhang @penguinwu

**Comment by ezyang** [comment]
I'm not sure what you're trying to do, but if you wanted to save the *real* tensors, this code doesn't do what you want; it's trying to save fake tensors that don't have data. I don't remember how to exactly spell it, but there's some relevant similar wibbling in torch/_dynamo/repro/after_aot.py

Or I could be wrong and example_inputs is actual real tensors and some much more obscure problem

**Comment by yaxan** [comment]
> I'm not sure what you're trying to do, but if you wanted to save the _real_ tensors, this code doesn't do what you want; it's trying to save fake tensors that don't have data. I don't remember how to exactly spell it, but there's some relevant similar wibbling in torch/_dynamo/repro/after_aot.py
> 
> Or I could be wrong and example_inputs is actual real tensors and some much more obscure problem

Throwing in a `print(example_inputs)` before the save yields:
```
[tensor([1.6226, 0.0726]), tensor([-0.5025, -0.0696])]
[tensor([-0.5025, -0.0696]), tensor([0.6187, 0.0677])]
[s0, tensor([-0.4205, -0.7103, -0.8642, -1.0742]), s1, tensor([ 0.1903, -0.7546,  0.4817, -1.1801])]
```

From what I can tell they are real tensors and the issue arises from the tensor containing the SymInts.
I do not know too much about how fake tensors work so perhaps I am misunderstanding the problem at hand.

**Comment by ezyang** [comment]
Oh lol, filter out the SymInts in that last list before serializing

**Comment by yaxan** [comment]
> Oh lol, filter out the SymInts in that last list before serializing

Any suggestions on if I wanted to retain the SymInts?

**Comment by anijain2305** [comment]
Can't really serialize the symint here. Filtering out tensors work. You might want some other mechanism to save the info that there is a symint

~~~
import torch
from typing import List

def bar(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

def custom_backend(gm: torch.fx.GraphModule,  example_inputs: List[torch.Tensor]):
    print(example_inputs)
    for idx, inp in enumerate(example_inputs):
        if isinstance(inp, torch.Tensor): 
            torch.save(inp, f"./example_inputs{idx}.zip", pickle_protocol=4)

    return gm.forward

compiled_bar = torch.compile(bar, backend=custom_backend)

compiled_bar(torch.randn(2), torch.randn(2))
compiled_bar(torch.randn(4), torch.randn(4))

~~~

**Comment by ezyang** [comment]
If you just want the ints you can ask for hints for the symints

**Comment by yaxan** [comment]
Understood, thank you all.
If it's entirely intentional that symints can't be saved then this issue can just be closed
