### ISSUE TITLE
Constructor for nested tensor doesn't correctly handle corner case of empty list

### ISSUE THREAD

**Issue by clessig** [pytorch/pytorch#130470]
### 🐛 Describe the bug

```
>>> a = torch.nested.nested_tensor( [], layout=torch.jagged)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/etc/ecmwf/nfs/dh2_perm_a/nacl/research/obs/lessig-dev-kas-cell-forecast/ai-obs-experimental-transformer/pyenv/lib/python3.10/site-packages/torch/nested/__init__.py", line 236, in nested_tensor
    nt, _ = jagged_from_list(list_of_tensors, offsets=None, device=device, dtype=dtype)
  File "/etc/ecmwf/nfs/dh2_perm_a/nacl/research/obs/lessig-dev-kas-cell-forecast/ai-obs-experimental-transformer/pyenv/lib/python3.10/site-packages/torch/nested/_internal/nested_tensor.py", line 373, in jagged_from_list
    raise RuntimeError(
RuntimeError: When constructing a nested tensor, all tensors in list must have the same dtype
```

The exception is triggered here: https://github.com/pytorch/pytorch/blob/cf090e222ead67e23e2af0721f1e92dcc1791482/torch/nested/_internal/nested_tensor.py#L372
```
 if not len(set(t.dtype for t in tensors)) == 1:  # noqa: C401
```
since  len(set(t.dtype for t in tensors)) = 0 in this case.

Suggested solution: insert in nested_tensor.py#l.371

```
if len(tensors) == 0:
    raise RuntimeError(
        "Cannot construct a nested tensor from an empty list."
    )
```

For me the issue was to understand that I was passing an empty list since tensor([]).unbind() returns []. It's probably best to disallow it rather than have to handle the special case of an empty nested tensor everywhere.

CC: @soulitzer @jbschlosser 

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240710+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.8 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: 15.0.7 (Red Hat 15.0.7-1.module+el8.8.0+17939+b58878af)
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.10.10 (main, Feb  9 2023, 14:42:48) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)] (64-bit runtime)
Python platform: Linux-4.18.0-477.43.1.el8_8.x86_64-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              256
On-line CPU(s) list: 0-255
Thread(s) per core:  2
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7H12 64-Core Processor
Stepping:            0
CPU MHz:             3299.911
CPU max MHz:         2600.0000
CPU min MHz:         1500.0000
BogoMIPS:            5200.23
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15,128-143
NUMA node1 CPU(s):   16-31,144-159
NUMA node2 CPU(s):   32-47,160-175
NUMA node3 CPU(s):   48-63,176-191
NUMA node4 CPU(s):   64-79,192-207
NUMA node5 CPU(s):   80-95,208-223
NUMA node6 CPU(s):   96-111,224-239
NUMA node7 CPU(s):   112-127,240-255
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] flake8==7.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] pytorch-triton==3.0.0+dedb7bdf33
[pip3] torch==2.5.0.dev20240710+cu124
[pip3] triton==2.3.1
[conda] Could not collect

**Comment by jbschlosser** [comment]
Thanks for the report! We should definitely provide a nicer error message.

**Comment by zeshengzong** [comment]
Hello, I think this issue resolved and can be closed. :D

```python
>>> import torch
>>> a = torch.nested.nested_tensor( [], layout=torch.jagged)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zong/code/pytorch/torch/nested/__init__.py", line 241, in nested_tensor
    nt, _ = jagged_from_list(list_of_tensors, offsets=None, device=device, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zong/code/pytorch/torch/nested/_internal/nested_tensor.py", line 423, in jagged_from_list
    raise RuntimeError("Cannot construct a nested tensor from an empty tensor list")
RuntimeError: Cannot construct a nested tensor from an empty tensor list
```

**Comment by cpuhrsch** [comment]
We could theoretically return an NT with 0 size from `torch.nested.nested_tensor( [], layout=torch.jagged)`, which is equivalent to a regular Tensor of with 0 size. So, we could return a 0-sized torch.Tensor here. Not sure how useful that is though. Other modes to explore here are lists of Tensors with 0 sizes and such.

**Comment by clessig** [comment]
NT with 0 size seems like a good solution to me.

**Comment by zeshengzong** [comment]
Looks like `layout=torch.jagged` and `layout=torch.strided` has different type of NT

for `layout=torch.jagged` has NT defined in here
https://github.com/pytorch/pytorch/blob/43a2a231d39b040055f8b6f2c83fb86c88186898/torch/nested/_internal/nested_tensor.py#L53-L55

for `layout=torch.strided` has NT defined in here

https://github.com/pytorch/pytorch/blob/43a2a231d39b040055f8b6f2c83fb86c88186898/aten/src/ATen/NestedTensorImpl.cpp#L213-L221

Seems there's no uniform type could be used to represent empty NT from `nested_tensor` API, or use just empty tensor `torch.empty(0)` ? 

For  `layout=torch.strided` currently is return empty NT

```python
>>> torch.nested.nested_tensor( [], layout=torch.strided)
nested_tensor([

])
>>> 

```
Thanks! @cpuhrsch

**Comment by cpuhrsch** [comment]
@zeshengzong - They are logically the same DataStructure but may use different memory layouts such as the layout strided or layout jagged. Indeed, making sure they stay in sync is useful to make decisions about the semantics of operations. The original nestedtensor prototype [has a lot of tests](https://github.com/pytorch/nestedtensor/blob/a97e1f6fc1650372bcb149d1fc243dde87514dcf/test/test_nested_tensor_class.py#L104) that we could also migrate to revisit this behavior. 

I'd say though in comparison to the items listed in https://github.com/pytorch/pytorch/issues/112398 we might not want to prioritize this right away, unless there's perhaps an application that's acutely blocked by this?
