### ISSUE TITLE
Illegal Memory Access in Custom CUDA Kernel Using Pybind11 with PyTorch

### ISSUE THREAD

**Issue by xTayEx** [pytorch/pytorch#130519]
### 🐛 Describe the bug

I am encountering an "illegal memory access" error when using a custom CUDA kernel with pybind11 and PyTorch. Specifically, I create a very simple CUDA kernel that only do some assignment. The CUDA code and its c++ interface are shown below
```cuda
__global__ void iterateMemorySpaceImpl(half* mem, half* out, std::size_t size) {
    std::size_t idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx < size) {
        *(out + idx) = *(mem + idx);
    }
}

extern "C" void iterateMemorySpace(half *mem, half* out, std::size_t size) {
    int block_size = 512;
    int grid_size = (size + block_size - 1) / block_size;
    iterateMemorySpaceImpl<<<grid_size, block_size>>>(mem, out, size);    
}
```

Then, I create a python binding using `pybind11` for the c++ interface:
```c++
m.def("debug_qkv_illegal_memory_access", [](at::Tensor& qkv) {
    TORCH_CHECK(qkv.device().is_cuda());

    const int64_t total_seqlen = qkv.size(0);
    const int64_t nheads = qkv.size(2);
    const int64_t head_size = qkv.size(3);
    auto out = torch::empty({total_seqlen, nheads, head_size}, at::TensorOptions().device(torch::kCUDA).dtype(torch::kF16));

    iterateMemorySpace(reinterpret_cast<half*>(qkv.data_ptr()), reinterpret_cast<half*>(out.data_ptr()), qkv.numel());
});
```

After that, the `debug_qkv_illegal_memory_access` interface created above is called in a python script:
```python
from binding import debug_qkv_illegal_memory_access
import torch
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--seqlen", type=int, required=True)
parser.add_argument("--batch_size", type=int, required=True)
parser.add_argument("--repeat", type=int, required=True)
args = parser.parse_args()

dim = 4096
nheads = 32
headdim = dim // nheads

for _ in range(args.repeat):
    qkv = torch.empty(
        (args.seqlen * args.batch_size, 3, nheads, headdim),
        device="cuda:0",
        dtype=torch.float16,
    )

    debug_qkv_illegal_memory_access(qkv)
    torch.cuda.synchronize()
```

The python scripts works fine for $\texttt{batch\\_size}\times \texttt{seqlen} \leq 512\times512$. However, If $\texttt{batch\\_size}\times \texttt{seqlen} \gt 512\times512$, for example, run the script using `CUDA_LAUNCH_BLOCKING=1 python3 debug_illegal_memory_access.py --seqlen 512 --batch_size 513 --repeat 50`, an "illegal memory access" will occur:
```bash
Traceback (most recent call last):
  File "/xxx/debug_illegal_memory_access.py", line 23, in <module>
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 803, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Versions

```
PyTorch version: 2.4.0a0+f70bd71a48.nv24.06
Is debug build: False
CUDA used to build PyTorch: 12.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.119-19.0009.28-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H800
GPU 1: NVIDIA H800
GPU 2: NVIDIA H800
GPU 3: NVIDIA H800
GPU 4: NVIDIA H800
GPU 5: NVIDIA H800
GPU 6: NVIDIA H800
GPU 7: NVIDIA H800

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          172
On-line CPU(s) list:             0-171
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8476C
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              43
Socket(s):                       2
Stepping:                        6
BogoMIPS:                        5199.73
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb ibrs_enhanced fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 wbnoinvd arat avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq movdiri movdir64b fsrm arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       4 MiB (86 instances)
L1i cache:                       2.7 MiB (86 instances)
L2 cache:                        172 MiB (86 instances)
L3 cache:                        195 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-85
NUMA node1 CPU(s):               86-171
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.16.0
[pip3] optree==0.11.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a2
[pip3] torch==2.4.0a0+f70bd71a48.nv24.6
[pip3] torch-tensorrt==2.4.0a0
[pip3] torchvision==0.19.0a0
[conda] Could not collect
```
Also, the `pybind11` version is 2.12.0. All the above code are compiled and run in the `nvcr.io/nvidia/pytorch:24.06-py3` docker container

**Comment by xTayEx** [comment]
I have found the reason, the shape of `out` should be `{total_seqlen, 3, nheads, head_size}`
