### ISSUE TITLE
dataloader hangs with fork and pin memory=True

### ISSUE THREAD

**Issue by accelerate321** [pytorch/pytorch#130610]
### 🚀 The feature, motivation and pitch

I train my model on DDP when num_workers>0, pin_memory=True and multiple dataloaders(train, valid, test). There is a small chance to hang that dataloader can not load data.  The reason is on Ubuntu，fork will be used to start num worker subprocess by default and it will cause potential deadlock with pin_memory_thread.

For pin_memory_thread, it will call torch.set_num_threads(1), it will acquire lock in __GI___cxa_atexit, if it locks and another dataloader fork num_worker process, it may cause potential deadlock. I set multiprocessing_context='spawn'
can solve the hang.

So can we change default value of multiprocessing_context to spawn? I think spawn is more safe.

```
(gdb) bt 
#0  __internal_atexit (listp=0x7fab466f6838 <__exit_funcs>, d=0x7fab43f9bf00, arg=0x7fab4430fd60 <caffe2::pthreadpool()::threadpool>, 
    func=0x7fab32724da0 <std::unique_ptr<caffe2::PThreadPool, std::default_delete<caffe2::PThreadPool> >::~unique_ptr()>) at ./stdlib/cxa_atexit.c:41
#1  __GI___cxa_atexit (func=0x7fab32724da0 <std::unique_ptr<caffe2::PThreadPool, std::default_delete<caffe2::PThreadPool> >::~unique_ptr()>, arg=0x7fab4430fd60 <caffe2::pthreadpool()::threadpool>, 
    d=0x7fab43f9bf00) at ./stdlib/cxa_atexit.c:70
#2  0x00007fab32724c6e in caffe2::pthreadpool() () from /tmp/cair_modelzoo_megatron_llama2_7b_pretrain_0_0/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so
#3  0x00007fab302757f7 in at::set_num_threads(int) () from /tmp/cair_modelzoo_megatron_llama2_7b_pretrain_0_0/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so
#4  0x00007fab44a40ada in THPModule_setNumThreads(_object*, _object*) () from /tmp/cair_modelzoo_megatron_llama2_7b_pretrain_0_0/lib/python3.10/site-packages/torch/lib/libtorch_python.so
```

**Comment by accelerate321** [comment]
@andrewkho @ssnl If you have time , could you please take a look at this issuse?
