### ISSUE TITLE
torch2.2.0+cuda12.1 image cant run on cuda12.2

### ISSUE THREAD

**Issue by northfun** [pytorch/pytorch#130802]
### 🐛 Describe the bug

We use official command to install torch2.2.0:
`conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia`

Then run the image on cuda12.2 enviroment, use `pip show torch` to see torch package info, and it looks fine.

```
$nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A800-SXM4-80GB          Off | 00000000:5E:00.0 Off |                    0 |
| N/A   29C    P0              61W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

```
$pip show torch
Name: torch
Version: 2.2.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /opt/conda/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision
```

But actually we can't use gpu.

```
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.2.0'
>>> print(torch.cuda.is_available())
False
>>> torch.zeros(1).cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
>>> 
```

The same issue exist at torch2.3.0, and torch2.3.1 works fine.

I tried add CUDA_HOME to PATH, but it didn't work.

### Versions

Collecting environment information...
PyTorch version: 2.2.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.0-1.0.0.9-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A800-SXM4-80GB
Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8350C CPU @ 2.60GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         3100.000
CPU max MHz:                     2601.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==7.0.0
[pip3] numpy==1.24.4
[pip3] optree==0.11.0
[pip3] torch==2.2.0
[pip3] torchaudio==2.2.0
[pip3] torchvision==0.17.0
[pip3] triton==2.2.0
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2020.2                      256    defaults
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch                   2.2.0           cpu_py310hab5cca8_0    defaults
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.2.0               py310_cu121    pytorch
[conda] torchtriton               2.2.0                     py310    pytorch
[conda] torchvision               0.17.0              py310_cu121    pytorch

cc @seemethere @malfet @osalpekar @atalman @ptrblck @msaroufim

**Comment by malfet** [comment]
As collect env shows, you somehow get CPU version of PyTorch installed, from [Anaconda channel](https://anaconda.org/anaconda/pytorch/files?channel=main&page=0&sort=basename&sort_order=desc&version=2.2.0) rather than PyTorch one
> [conda] pytorch 2.2.0 cpu_py310hab5cca8_0 defaults
> [conda] pytorch-cuda 12.1 ha16c6d3_5 pytorch


Please post full installation logs, there probably would be an explanation why the desired version could not be installed

**Comment by northfun** [comment]
> As collect env shows, you somehow get CPU version of PyTorch installed, from [Anaconda channel](https://anaconda.org/anaconda/pytorch/files?channel=main&page=0&sort=basename&sort_order=desc&version=2.2.0) rather than PyTorch one
> 
> > [conda] pytorch 2.2.0 cpu_py310hab5cca8_0 defaults
> > [conda] pytorch-cuda 12.1 ha16c6d3_5 pytorch
> 
> Please post full installation logs, there probably would be an explanation why the desired version could not be installed

What's the different between pytorch 2.2.0 cpu_pyxxx and pytorch-cuda 12.1 xxx?

**Comment by northfun** [comment]
> As collect env shows, you somehow get CPU version of PyTorch installed, from [Anaconda channel](https://anaconda.org/anaconda/pytorch/files?channel=main&page=0&sort=basename&sort_order=desc&version=2.2.0) rather than PyTorch one
> 
> > [conda] pytorch 2.2.0 cpu_py310hab5cca8_0 defaults
> > [conda] pytorch-cuda 12.1 ha16c6d3_5 pytorch
> 
> Please post full installation logs, there probably would be an explanation why the desired version could not be installed

```
bml@489600533f23:~$ conda install -y --solver=classic pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)
Collecting package metadata (current_repodata.json): \ WARNING conda.models.version:get_matcher(562): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(562): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(562): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(562): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - pytorch-cuda=12.1
    - pytorch==2.2.0
    - torchaudio==2.2.0
    - torchvision==0.17.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.1                   |         openblas           1 KB  defaults
    ca-certificates-2024.7.2   |       h06a4308_0         127 KB  defaults
    certifi-2024.7.4           |  py310h06a4308_0         158 KB  defaults
    conda-24.5.0               |  py310h06a4308_0         976 KB  defaults
    cuda-cudart-12.1.105       |                0         189 KB  nvidia
    cuda-cupti-12.1.105        |                0        15.4 MB  nvidia
    cuda-libraries-12.1.0      |                0           2 KB  nvidia
    cuda-nvrtc-12.1.105        |                0        19.7 MB  nvidia
    cuda-nvtx-12.1.105         |                0          57 KB  nvidia
    cuda-opencl-12.5.39        |                0          26 KB  nvidia
    cuda-runtime-12.1.0        |                0           1 KB  nvidia
    cuda-version-12.5          |                3          16 KB  nvidia
    ffmpeg-4.4.0               |       hca11adc_0        95.3 MB  defaults
    filelock-3.13.1            |  py310h06a4308_0          21 KB  defaults
    frozendict-2.4.2           |  py310h5eee18b_0          55 KB  defaults
    fsspec-2024.3.1            |  py310h06a4308_0         281 KB  defaults
    gmp-6.2.1                  |       h295c915_3         544 KB  defaults
    gmpy2-2.1.2                |  py310heeb90bb_0         517 KB  defaults
    gnutls-3.6.15              |       he1e5248_0         1.0 MB  defaults
    lame-3.100                 |       h7b6447c_0         323 KB  defaults
    lcms2-2.16                 |       hb7c19ff_0         239 KB  defaults
    libcublas-12.1.0.26        |                0       329.0 MB  nvidia
    libcufft-11.0.2.4          |                0       102.9 MB  nvidia
    libcufile-1.10.1.7         |                0         1.0 MB  nvidia
    libcurand-10.3.6.82        |                0        51.8 MB  nvidia
    libcusolver-11.4.4.55      |                0        98.3 MB  nvidia
    libcusparse-12.0.2.55      |                0       163.0 MB  nvidia
    libidn2-2.3.4              |       h5eee18b_0         146 KB  defaults
    libnpp-12.0.2.50           |                0       139.8 MB  nvidia
    libnvjitlink-12.1.105      |                0        16.9 MB  nvidia
    libnvjpeg-12.1.1.14        |                0         2.9 MB  nvidia
    libprotobuf-3.20.3         |       h3eb15da_0         2.2 MB  defaults
    libtasn1-4.19.0            |       h5eee18b_0          63 KB  defaults
    libunistring-0.9.10        |       h27cfd23_0         536 KB  defaults
    mpc-1.1.0                  |       h10f8cd9_1          90 KB  defaults
    mpfr-4.0.2                 |       hb69a4c5_1         487 KB  defaults
    mpmath-1.3.0               |  py310h06a4308_0         834 KB  defaults
    nettle-3.7.3               |       hbbd107a_1         809 KB  defaults
    networkx-3.3               |  py310h06a4308_0         2.5 MB  defaults
    ninja-1.10.2               |       h06a4308_5           8 KB  defaults
    ninja-base-1.10.2          |       hd09550d_5         109 KB  defaults
    numpy-1.26.4               |  py310heeff2f4_0          10 KB  defaults
    numpy-base-1.26.4          |  py310h8a23956_0         7.2 MB  defaults
    openblas-0.3.27            |pthreads_h7a3da1a_0         5.5 MB  defaults
    openh264-2.1.1             |       h4ff587b_0         711 KB  defaults
    openjpeg-2.5.2             |       h488ebb8_0         334 KB  defaults
    openssl-3.3.1              |       h4bc722e_2         2.8 MB  defaults
    pillow-10.4.0              |  py310hebfe307_0        40.6 MB  defaults
    pytorch-2.2.0              |cpu_py310hab5cca8_0        61.2 MB  defaults
    pytorch-cuda-12.1          |       ha16c6d3_5           3 KB  pytorch
    pytorch-mutex-1.0          |             cuda           3 KB  pytorch
    sympy-1.12                 |  py310h06a4308_0        10.5 MB  defaults
    torchaudio-2.2.0           |      py310_cu121         6.3 MB  pytorch
    torchvision-0.17.0         |      py310_cu121         8.2 MB  pytorch
    typing_extensions-4.11.0   |  py310h06a4308_0          59 KB  defaults
    x264-1!161.3030            |       h7f98852_1         2.5 MB  defaults
    ------------------------------------------------------------
                                           Total:        1.17 GB

The following NEW packages will be INSTALLED:

  blas               anaconda/cloud/conda-forge/linux-64::blas-1.1-openblas 
  cuda-cudart        nvidia/linux-64::cuda-cudart-12.1.105-0 
  cuda-cupti         nvidia/linux-64::cuda-cupti-12.1.105-0 
  cuda-libraries     nvidia/linux-64::cuda-libraries-12.1.0-0 
  cuda-nvrtc         nvidia/linux-64::cuda-nvrtc-12.1.105-0 
  cuda-nvtx          nvidia/linux-64::cuda-nvtx-12.1.105-0 
  cuda-opencl        nvidia/linux-64::cuda-opencl-12.5.39-0 
  cuda-runtime       nvidia/linux-64::cuda-runtime-12.1.0-0 
  cuda-version       nvidia/noarch::cuda-version-12.5-3 
  ffmpeg             anaconda/cloud/conda-forge/linux-64::ffmpeg-4.4.0-hca11adc_0 
  filelock           anaconda/pkgs/main/linux-64::filelock-3.13.1-py310h06a4308_0 
  frozendict         anaconda/pkgs/main/linux-64::frozendict-2.4.2-py310h5eee18b_0 
  fsspec             anaconda/pkgs/main/linux-64::fsspec-2024.3.1-py310h06a4308_0 
  gmp                anaconda/pkgs/main/linux-64::gmp-6.2.1-h295c915_3 
  gmpy2              anaconda/pkgs/main/linux-64::gmpy2-2.1.2-py310heeb90bb_0 
  gnutls             anaconda/pkgs/main/linux-64::gnutls-3.6.15-he1e5248_0 
  lame               anaconda/pkgs/main/linux-64::lame-3.100-h7b6447c_0 
  lcms2              anaconda/cloud/conda-forge/linux-64::lcms2-2.16-hb7c19ff_0 
  libcublas          nvidia/linux-64::libcublas-12.1.0.26-0 
  libcufft           nvidia/linux-64::libcufft-11.0.2.4-0 
  libcufile          nvidia/linux-64::libcufile-1.10.1.7-0 
  libcurand          nvidia/linux-64::libcurand-10.3.6.82-0 
  libcusolver        nvidia/linux-64::libcusolver-11.4.4.55-0 
  libcusparse        nvidia/linux-64::libcusparse-12.0.2.55-0 
  libidn2            anaconda/pkgs/main/linux-64::libidn2-2.3.4-h5eee18b_0 
  libnpp             nvidia/linux-64::libnpp-12.0.2.50-0 
  libnvjitlink       nvidia/linux-64::libnvjitlink-12.1.105-0 
  libnvjpeg          nvidia/linux-64::libnvjpeg-12.1.1.14-0 
  libprotobuf        anaconda/cloud/conda-forge/linux-64::libprotobuf-3.20.3-h3eb15da_0 
  libtasn1           anaconda/pkgs/main/linux-64::libtasn1-4.19.0-h5eee18b_0 
  libunistring       anaconda/pkgs/main/linux-64::libunistring-0.9.10-h27cfd23_0 
  mpc                anaconda/pkgs/main/linux-64::mpc-1.1.0-h10f8cd9_1 
  mpfr               anaconda/pkgs/main/linux-64::mpfr-4.0.2-hb69a4c5_1 
  mpmath             anaconda/pkgs/main/linux-64::mpmath-1.3.0-py310h06a4308_0 
  nettle             anaconda/pkgs/main/linux-64::nettle-3.7.3-hbbd107a_1 
  networkx           anaconda/pkgs/main/linux-64::networkx-3.3-py310h06a4308_0 
  ninja              anaconda/pkgs/main/linux-64::ninja-1.10.2-h06a4308_5 
  ninja-base         anaconda/pkgs/main/linux-64::ninja-base-1.10.2-hd09550d_5 
  numpy              anaconda/pkgs/main/linux-64::numpy-1.26.4-py310heeff2f4_0 
  numpy-base         anaconda/pkgs/main/linux-64::numpy-base-1.26.4-py310h8a23956_0 
  openblas           anaconda/cloud/conda-forge/linux-64::openblas-0.3.27-pthreads_h7a3da1a_0 
  openh264           anaconda/pkgs/main/linux-64::openh264-2.1.1-h4ff587b_0 
  openjpeg           anaconda/cloud/conda-forge/linux-64::openjpeg-2.5.2-h488ebb8_0 
  pillow             anaconda/cloud/conda-forge/linux-64::pillow-10.4.0-py310hebfe307_0 
  pytorch            anaconda/pkgs/main/linux-64::pytorch-2.2.0-cpu_py310hab5cca8_0 
  pytorch-cuda       pytorch/linux-64::pytorch-cuda-12.1-ha16c6d3_5 
  pytorch-mutex      pytorch/noarch::pytorch-mutex-1.0-cuda 
  sympy              anaconda/pkgs/main/linux-64::sympy-1.12-py310h06a4308_0 
  torchaudio         pytorch/linux-64::torchaudio-2.2.0-py310_cu121 
  torchvision        pytorch/linux-64::torchvision-0.17.0-py310_cu121 
  typing_extensions  anaconda/pkgs/main/linux-64::typing_extensions-4.11.0-py310h06a4308_0 
  x264               anaconda/cloud/conda-forge/linux-64::x264-1!161.3030-h7f98852_1 

The following packages will be UPDATED:

  ca-certificates    anaconda/cloud/conda-forge::ca-certif~ --> anaconda/pkgs/main::ca-certificates-2024.7.2-h06a4308_0 
  certifi            anaconda/cloud/conda-forge/noarch::ce~ --> anaconda/pkgs/main/linux-64::certifi-2024.7.4-py310h06a4308_0 
  conda              anaconda/cloud/conda-forge::conda-24.~ --> anaconda/pkgs/main::conda-24.5.0-py310h06a4308_0 
  openssl                                  3.3.1-h4ab18f5_0 --> 3.3.1-h4bc722e_2 



Downloading and Extracting Packages:
                                                                                                                          
Preparing transaction: done                                                                                               
Verifying transaction: done                                                                                               
Executing transaction: done              
```

Here is the installation log.
