### ISSUE TITLE
RuntimeError in _multi_tensor_adamw: Output Shape Mismatch During torch.foreach_lerp Operation

### ISSUE THREAD

**Issue by nbqu** [pytorch/pytorch#130810]
### 🐛 Describe the bug

Error traceback:
```
Traceback (most recent call last):
[rank1]:   File "/home/jh/my_lightning_project/main.py", line 9, in <module>
[rank1]:     cli_main()
[rank1]:   File "/home/jh/my_lightning_project/main.py", line 6, in cli_main
[rank1]:     cli = LightningCLI(MyLightningModule, MyDataModule, save_config_kwargs={"overwrite": True})
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 394, in __init__
[rank1]:     self._run_subcommand(self.subcommand)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 701, in _run_subcommand
[rank1]:     fn(**fn_kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
[rank1]:     call._call_and_handle_interrupt(
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
[rank1]:     return trainer_fn(*args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
[rank1]:     self._run(model, ckpt_path=ckpt_path)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
[rank1]:     results = self._run_stage()
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1030, in _run_stage
[rank1]:     self.fit_loop.run()
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
[rank1]:     self.advance()
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
[rank1]:     self.epoch_loop.run(self._data_fetcher)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
[rank1]:     self.advance(data_fetcher)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 250, in advance
[rank1]:     batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 190, in run
[rank1]:     self._optimizer_step(batch_idx, closure)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 268, in _optimizer_step
[rank1]:     call._call_lightning_module_hook(
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
[rank1]:     output = fn(*args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1308, in optimizer_step
[rank1]:     optimizer.step(closure=optimizer_closure)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py", line 153, in step
[rank1]:     step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 238, in optimizer_step
[rank1]:     return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/fsdp.py", line 163, in optimizer_step
[rank1]:     step_output = self.scaler.step(optimizer, **kwargs)  # type: ignore[arg-type]
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 453, in step
[rank1]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 351, in _maybe_opt_step
[rank1]:     retval = optimizer.step(*args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
[rank1]:     return wrapped(*args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/optim/optimizer.py", line 391, in wrapper
[rank1]:     out = func(*args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
[rank1]:     ret = func(self, *args, **kwargs)
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/optim/adamw.py", line 188, in step
[rank1]:     adamw(
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/optim/adamw.py", line 340, in adamw
[rank1]:     func(
[rank1]:   File "/home/jh/.cache/pypoetry/virtualenvs/my-project-2CIT3KWG-py3.10/lib/python3.10/site-packages/torch/optim/adamw.py", line 550, in _multi_tensor_adamw
[rank1]:     torch._foreach_lerp_(device_exp_avgs, device_grads, 1 - beta1)
[rank1]: RuntimeError: output with shape [] doesn't match the broadcast shape [1]
```

When I do FSDP training and save checkpoints, then resume, the AdamW optimizer raises error. Seems this error only raised from non-rank 0.

The one thing I've tried to fix is to unsqueeze dim == 0 tensors in `device_exp_avgs`, `device_grads`, and `device_exp_avg_sqs` with
```python
from itertools import zip_longest
for i, (exp_avg, grad, exp_avg_sq) in enumerate(zip_longest(device_exp_avgs, device_grads, device_exp_avg_sqs)):

    if exp_avg is not None and exp_avg.dim() == 0:
        device_exp_avgs[i] = exp_avg.unsqueeze(0)

    if grad is not None and grad.dim() == 0:
        device_grads[i] = grad.unsqueeze(0)

    if exp_avg_sq is not None and exp_avg_sq.dim() == 0:
        device_exp_avg_sqs[i] = exp_avg_sq.unsqueeze(0)
```
and it resolves the issue. (Copilot suggested it 😅)

But this cannot be the best solution, can anyone investigate on this issue? I'm not familiar on FSDP so I cannot even define what the problem is, and cannot point whether it is torch-related issue or lightning-related issue..

### Versions

environment information:
```
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul 31 2023, 19:12:41) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX A6000
GPU 5: NVIDIA RTX A6000
GPU 6: NVIDIA RTX A6000
GPU 7: NVIDIA RTX A6000

Nvidia driver version: 555.42.02
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.9.7
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.7
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.7
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.7
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.7
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.7
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.7
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_adv.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_cnn.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_engines_precompiled.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_engines_runtime_compiled.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_graph.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_heuristic.so.9.1.1
/usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudnn_ops.so.9.1.1

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.3.3
[pip3] torch==2.3.1
[pip3] torchmetrics==1.4.0.post0
[pip3] torchscale==0.3.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.18.1
[pip3] triton==2.3.1
```

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by awgu** [comment]
cc: @fegin @wz337 @LucasLLC if this is related to optimizer state dict handling of scalar tensors

**Comment by nbqu** [comment]
Hi, I'm leaving additional information of my setting that may affects:
```yaml
sharding_strategy: SHARD_GRAD_OP
state_dict_type: full
precision: 16-mixed
```

**Comment by wz337** [comment]
Looks like we are missing a unit test for FSDP1, in which we should set foreach=True for AdamW and see if we could repro the same error here.

**Comment by nbqu** [comment]
> cc: @fegin @wz337 @LucasLLC if this is related to optimizer state dict handling of scalar tensors

As @awgu pointed, a scalar parameter in my model caused error. I changed it into 1-d parameter and seems to work properly. But still this is an issue unless defining 0-d(scalar) tensor is legit. Any thoughts?

**Comment by fegin** [comment]
@nbqu Please check https://github.com/pytorch/pytorch/pull/132934.
