### ISSUE TITLE
float8 types cannot be used under deterministic mode

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#130968]
```
>>> import torch
>>> torch.__version__
'2.4.0a0'
>>> torch.use_deterministic_algorithms(True)
>>> torch.empty(1, dtype=torch.float8_e4m3fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "fill_empty_deterministic_" not implemented for 'Float8_e4m3fn'
>>> torch.empty(1, dtype=torch.float8_e5m2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "fill_empty_deterministic_" not implemented for 'Float8_e5m2'
```

We need `fill_empty_deterministic_` implementations.

**Comment by malfet** [comment]
I remember seeing a PR about this one recently (from @vkuzo ) What version of PyTorch are you using?

**Comment by awgu** [comment]
For the original repro, the torch version is listed as `'2.4.0a0'`.

I tried on my `main` branch setup:
```
>>> import torch
>>> torch.use_deterministic_algorithms(True)
>>> torch.empty(1, dtype=torch.float8_e4m3fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "fill_out" not implemented for 'Float8_e4m3fn'
>>> torch.__version__
'2.5.0a0+git7128504'
```
different error now with `fill_out`

**Comment by kwen2501** [comment]
Hitting same error when trying to write a value into a `float8_e4m3fn` tensor:
`tensor[0] = float(nan)`
(nightly as of sept 11)
Or is there a different recommended way?
