### ISSUE TITLE
torch.Tensor.uniform_ causes invalid syntax in InternalTorchDynamoError

### ISSUE THREAD

**Issue by Cztery** [pytorch/pytorch#131019]
### 🐛 Describe the bug

This issue is a follow-up to https://github.com/pytorch/pytorch/issues/121621 . Basically the same issue, different op.
The op signature from https://pytorch.org/docs/stable/generated/torch.Tensor.uniform_.html#torch.Tensor.uniform_
is that first argument is from and second to, looks like this is causing trouble in tracing.

### Error logs

Traceback (most recent call last):
  File "/root/pytorch-training-tests/tests/torch_feature_val/single_op/common_executor.py", line 132, in exec_test
    operator.run_habana()
  File "/root/pytorch-training-tests/tests/torch_feature_val/single_op/op_impl/op_base.py", line 180, in run_habana
    self.ref_fwd = self.executor.run_hpu(self.seeds[0])
  File "/root/pytorch-training-tests/tests/torch_feature_val/single_op/torch_executor.py", line 146, in run_hpu
    habana_result = self._run_on(HPU, seed)
  File "/root/pytorch-training-tests/tests/torch_feature_val/single_op/torch_executor.py", line 321, in _run_on
    result_fwd = self._eval_and_run(
  File "/root/pytorch-training-tests/tests/torch_feature_val/single_op/torch_executor.py", line 401, in _eval_and_run
    self.leaf_tensor, result = model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1521, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1530, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1521, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1530, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 586, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 2162, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 857, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 947, in compile_and_call_fx_graph
    gm = fx.GraphModule(root, self.graph)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 385, in __init__
    self.graph = graph
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1757, in __setattr__
    super().__setattr__(name, value)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 426, in graph
    self.recompile()
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 664, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals, co_fields)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 108, in fx_forward_from_src_skip_result
    result: types.FunctionType = original_forward_from_src(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 83, in _forward_from_src
    _exec_with_source(src, globals_copy, co_fields)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 77, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
torch._dynamo.exc.InternalTorchDynamoError: invalid syntax (<eval_with_key>.0, line 6) 
3955-2023-11-02 12:27:39:908  WARNING  [op_base.py:322] — data type is of <class 'NoneType'>, skipping dumping of data for ref_fwd
3955-2023-11-02 12:27:39:908  WARNING  [op_base.py:322] — data type is of <class 'NoneType'>, skipping dumping of data for hpu_fwd
3955-2023-11-02 12:27:41:197  INFO     [conftest.py:989] — bridge cleanup done!
3955-2023-11-02 12:27:41:198  INFO     [conftest.py:1059] — 

### Minified repro

import torch

def uniform_op(tensor, params):
    res = tensor.uniform(**params)
    return res

if __name__ == "__main__":
    random_op = torch.compile(random_op)
    params = {"from": -10, "to": 10}
    tensor = torch.randn([2, 3])
    res =  uniform_op(tensor, params)
    print(res)

### Versions

Versions of relevant libraries:
[pip3] flake8==7.0.0
[pip3] habana-torch-dataloader==1.18.0+git31ea075c1
[pip3] habana-torch-plugin==1.18.0+git31ea075c1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.2.5
[pip3] torch==2.4.0a0+gite602b87
[pip3] torch_tb_profiler==0.4.0
[pip3] torchaudio==2.3.0+952ea74
[pip3] torchdata==0.7.1+5e6f7b7
[pip3] torchmetrics==1.4.0.post0
[pip3] torchtext==0.18.0a0+9bed85d
[pip3] torchvision==0.18.1a0+fe70bc8
[conda] Could not collect

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by desertfire** [comment]
@anijain2305 , I saw you closed https://github.com/pytorch/pytorch/issues/121621. Does you fix cover this case as well?

**Comment by anijain2305** [comment]
I don't think my PR will fix it. But my PR can be easily extended.
