### ISSUE TITLE
Missing float8 storage

### ISSUE THREAD

**Issue by maruel** [pytorch/pytorch#131196]
### 🚀 The feature, motivation and pitch

I'm trying to use float8 to try mistral nemo which was trained in a quantization aware way, to do inference in FP8.
Ref:
- https://mistral.ai/news/mistral-nemo/
- https://huggingface.co/mistralai/Mistral-Nemo-Base-2407#transformers

### Additional context

Environment:
- macOS 14.5
- Python 3.12.4
- pytorch 2.3.1

Repo:

```
import torch                                                                    
import transformers
print(torch.__version__)                                                        
transformers.pipeline(                                                 
      "text-generation",                                                        
      model="mistralai/Mistral-Nemo-Instruct-2407",                             
      torch_dtype=torch.float8_e4m3fn)  
```

Failure:

```
2.3.1
Traceback (most recent call last):
  File ".../repro.py", line 3, in <module>
    transformers.pipeline(                                                 
    ^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/transformers/pipelines/__init__.py", line 895, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/transformers/pipelines/base.py", line 283, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maruel/src-my/sillybot/py/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3724, in from_pretrained
    dtype_orig = cls._set_default_torch_dtype(torch_dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 1572, in _set_default_torch_dtype
    torch.set_default_dtype(dtype)
  File ".../venv/lib/python3.12/site-packages/torch/__init__.py", line 796, in set_default_dtype
    _C._set_default_dtype(d)
TypeError: couldn't find storage object Float8_e4m3fnStorage
```

When I try with float8_e5m2, the exception is Float8_e5m2Storage

**Comment by mikaylagawarecki** [comment]
`torch.set_default_dtype` seems to be broken with Float8

```
>>> import torch
>>> torch.set_default_dtype(torch.float8_e4m3fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/mg1998/pytorch/torch/__init__.py", line 1100, in set_default_dtype
    _C._set_default_dtype(d)
TypeError: couldn't find storage object Float8_e4m3fnStorage
```

**Comment by notlober** [comment]
@mikaylagawarecki @maruel
I think issue is that its mentioned that environment is a macOS environment, but I think macOS systems dont support float8 natively, could this be the problem?

**Comment by Eyalm321** [comment]
any update on this guys?

**Comment by balala8** [comment]
I had the same problem on ubuntu 22, the graphics card is 2080ti

**Comment by Pedrexus** [comment]
I believe only Nvidia H100 and the like support fp8 right now, correct?

**Comment by remixer-dec** [comment]
same issue on torch 2.4 on 4090

**Comment by vkuzo** [comment]
Float8 support in PyTorch so far has focused on target hardware which supports the float8 gemm, such as NVIDIA machines with CUDA capability 8.9 and above.  We would welcome community contributions to make float8 work as a storage type on Mac OS!

**Comment by RobertCorwin-AustinAI** [comment]
same issue here, Ubuntu 22, 4090 GPUs, latest verison of most libraries

**Comment by lsb** [comment]
I'm finding this issue on a H200 with torch 2.7.1 stock installation
