### ISSUE TITLE
Pytorch Error: ImportError: /home/dp/anaconda3/envs/ComfyUI/lib/python3.11/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12

### ISSUE THREAD

**Issue by wenbindu** [pytorch/pytorch#131312]
### 🐛 Describe the bug

And, when I run the python3 -c "import torch;", I got this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dp/anaconda3/envs/ComfyUI/lib/python3.11/site-packages/torch/__init__.py", line 364, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/dp/anaconda3/envs/ComfyUI/lib/python3.11/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

### Versions

```
(ComfyUI) dp@dp-7920:/hw_data/ws/ComfyUI$ pip list |grep torch
pytorch-triton           3.0.0+dedb7bdf33
torch                    2.5.0.dev20240720+cu124
torchaudio               2.4.0.dev20240721+cu124
torchvision              0.20.0.dev20240721+cu124
(ComfyUI) dp@dp-7920:/hw_data/ws/ComfyUI$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  550.90.07  Fri May 31 09:35:42 UTC 2024
GCC version:  gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~22.04) 
```

**Comment by malfet** [comment]
@wenbindu can you please share the output of  full `pip list|grep nvidia-`? I'm curious about CUDA dependencies

**Comment by wenbindu** [comment]
Sorry, I'm late. As I changed the torch version, shown below:
<img width="418" alt="image" src="https://github.com/user-attachments/assets/05983101-9710-4bc3-97b2-a23633321d40">
it worked well. But the error is still existed. I create the env with the following commands to reproduce the problem:
```sh
conda create --name ComfyUI python==3.11
conda activate ComfyUI
nvidia-smi
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
ls
```
The output of the `pip list|grep nvidia-`:
```
nvidia-cublas-cu12       12.4.2.65
nvidia-cuda-cupti-cu12   12.4.99
nvidia-cuda-nvrtc-cu12   12.4.99
nvidia-cuda-runtime-cu12 12.4.99
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.0.44
nvidia-curand-cu12       10.3.5.119
nvidia-cusolver-cu12     11.6.0.99
nvidia-cusparse-cu12     12.3.0.142
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.99
nvidia-nvtx-cu12         12.4.99
```
And the output of `pip list |grep torch`:
```
pytorch-triton           3.0.0+dedb7bdf33
torch                    2.5.0.dev20240729+cu124
torchaudio               2.4.0.dev20240729+cu124
torchvision              0.20.0.dev20240729+cu124
```
Please let me know if you get any progress.

**Comment by yufeng1684** [comment]
May be linked to wrong so file. 
You can attempt to modify LD_LIBRARY_PATH:
export LD_LIBRARY_PATH=/path/to/venv/lib/python3.11/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH
