### ISSUE TITLE
Correctness test for compiled LBFGS optimizer fails on Darwin if `use_closure` is True

### ISSUE THREAD

**Issue by qqaatw** [pytorch/pytorch#131398]
### 🐛 Describe the bug

Found in PR #131065, where we enable tensor LR for all the optimizers.

After adding the tensor lr test sample to LBFGS sample inputs: 

```python
OptimizerInput(
        params=None, kwargs={"lr": torch.tensor(0.001)}, desc="Tensor lr"
),
```

The following test fails on Darwin:
`inductor/test_compiled_optimizers.py::CompiledOptimizerParityTestsCPU::test_correctness_LBFGS_use_closure_True_cpu_float32`

with the traceback here:

```
_ CompiledOptimizerParityTestsCPU.test_correctness_LBFGS_use_closure_True_cpu_float32 _
Traceback (most recent call last):
  File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/inductor/test_compiled_optimizers.py", line 535, in test_correctness
    opt_eager.step(closure_eager)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10002088921/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 602, in _fn
    return fn(*args, **kwargs)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10002088921/lib/python3.9/site-packages/torch/optim/optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10002088921/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10002088921/lib/python3.9/site-packages/torch/optim/lbfgs.py", line 442, in step
    loss, flat_grad, t, ls_func_evals = _strong_wolfe(
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10002088921/lib/python3.9/site-packages/torch/optim/lbfgs.py", line 175, in _strong_wolfe
    t = bracket[low_pos]  # type: ignore[possibly-undefined]
IndexError: list index out of range
```

### Versions

Collecting environment information...
PyTorch version: 2.5.0a0+gitada67f4
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.7.4 (arm64)
GCC version: Could not collect
Clang version: 18.1.5
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.7.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.2
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] onnx==1.13.1
[pip3] onnxruntime==1.14.1
[pip3] onnxruntime-tools==1.7.0
[pip3] optree==0.11.0
[pip3] torch==2.5.0a0+git1a8dfc1
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.0
[pip3] torchdiffeq==0.2.3
[pip3] torchsde==0.2.5
[pip3] torchtext==0.15.1
[pip3] torchvision==0.19.0a0+f1bcbd3
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.5.0a0+git1a8dfc1           dev_0    <develop>
[conda] torchaudio                2.0.1                    pypi_0    pypi
[conda] torchdata                 0.6.0                    pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchtext                 0.15.1                   pypi_0    pypi
[conda] torchvision               0.19.0a0+f1bcbd3           dev_0    <develop>

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @anijain2305 @chauhang @penguinwu

**Comment by desertfire** [comment]
@mlazos

**Comment by mlazos** [comment]
I don't think this is a bug with the compiled optimizer. The reason I think this is that we skip compilation on LBFGS via `torch._dynamo.disable`. (I added these tests for completeness though in order to verify the disabled optimizers E2E as well). I think this is an issue with the eager optimizer, and the error message is identical to what we see here: https://github.com/pytorch/pytorch/issues/117094 perhaps it's the same issue?
Strange that it only happens on macos as well. FWIW I think it's okay that we skip LBFGS with tensor LR, I'm not sure if it even supports cudagraphs.

**Comment by masnesral** [comment]
@mlazos I'm helping scrub old issues. Given your last comment, is it ok to just close this? Sounds like you don't think there's a compiler issue here.

**Comment by janeyx99** [comment]
Yea this can be folded into the issue Lazos linked

**Comment by masnesral** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/117094
