### ISSUE TITLE
Edits to torch/lib/c10d/ProcessGroupGloo.cpp (and possibly other files) do not successfully recompile

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#13176]
## To Reproduce

1. Fresh checkout of PyTorch on c95fa4b9046085aefa91e76845f20918bd1054ef
2. Do a build `python setup.py build_deps develop`
3. Apply this patch:

```
diff --git a/torch/lib/c10d/ProcessGroupGloo.cpp b/torch/lib/c10d/ProcessGroupGloo.cpp
index 513cc0c7b..ed633da19 100644
--- a/torch/lib/c10d/ProcessGroupGloo.cpp
+++ b/torch/lib/c10d/ProcessGroupGloo.cpp
@@ -499,6 +499,7 @@ void ProcessGroupGloo::createBroadcast(AlgorithmEntry& entry) {
 // failure must be signaled through the Work future.
 //
 EntryType ProcessGroupGloo::construct(const AlgorithmKey& key) {
+  AT_ERROR("arglebargle");
   at::DeviceGuard deviceGuard;
   auto entry = std::unique_ptr<AlgorithmEntry>(new AlgorithmEntry);
   entry->key = key;
```

4. Do a build `python setup.py build_deps develop`
5. Run `python test/test_c10d.py DistributedDataParallelTest.test_dist_broadcast_coalesced`

Test doesn't fail.

You can induce a correct recompilation by deleting the `so` file in build:

```
$ rm build/lib.*/torch/_C*
$ python setup.py build_deps develop
$ python test/test_c10d.py DistributedDataParallelTest.test_dist_broadcast_coalesced
Process process 1:
Process process 0:
Traceback (most recent call last):
  File "/home/ezyang/Dev/pytorch-repro-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ezyang/Dev/pytorch-repro-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "test/test_c10d.py", line 354, in _run
    getattr(self, self.id().split(".")[2])()
  File "test/test_c10d.py", line 319, in wrapper
    fn(self)
  File "test/test_c10d.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "test/test_c10d.py", line 763, in test_dist_broadcast_coalesced
    buffer_size=10)
RuntimeError: arglebargle (construct at ../torch/lib/c10d/ProcessGroupGloo.cpp:502)
```

## Expected behavior

Test fails with arglebargle.

## Environment

On a devgpu005.ash6

```
(/home/ezyang/Dev/pytorch-repro-env) [ezyang@devgpu005.ash6 ~/Dev/pytorch-repro] cmake --version
cmake version 3.12.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(/home/ezyang/Dev/pytorch-repro-env) [ezyang@devgpu005.ash6 ~/Dev/pytorch-repro] cmake3 --version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(/home/ezyang/Dev/pytorch-repro-env) [ezyang@devgpu005.ash6 ~/Dev/pytorch-repro] ninja --version
1.8.2.git.kitware.dyndep-1.jobserver-1
```

**Comment by zou3519** [comment]
@ezyang is this still a problem?

**Comment by ezyang** [comment]
Let's guess it's not.
