### ISSUE TITLE
Different Cholesky results between Windows & Linux

### ISSUE THREAD

**Issue by grimulkan** [pytorch/pytorch#131774]
### 🐛 Describe the bug

Computing Cholesky on a large matrix fails on Windows. To reproduce:
```
import torch
chol = torch.linalg.cholesky(torch.eye(53248, 53248, dtype=torch.float32, device='cuda:0'))
```
On Windows with torch==2.3.0 and numpy==1.26.4 with CUDA 12.1, the result is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 40961 is not positive-definite).
```
This answer should be the identity matrix (and the input identity clearly is positive definite).

The result is the same even if I vary the torch and numpy versions up/down a few notches from the above versions (including testing the latest of each), as well as varying the Python versions (3.10 to 3.12). I am not sure if torch==2.4.0 compiles all kernels against numpy 2.x on Windows though, so I may not have fully validated numpy==2.0 in combination with torch.

The result is the same on a 24GB as well as a 48GB GPU (both should have enough VRAM to perform the operation). The result is also unchanged between a TCC mode GPU or WDDM.

In WSL, on the same hardware, the correct result is obtained. Another user independently confirmed it works in native Linux as well. In Windows, the correct result is obtained when computing on the cpu instead of GPU.

If the dimensions of the matrix are reduced to, egs., 47500 (found by randomly trying):
```
import torch
chol = torch.linalg.cholesky(torch.eye(47500, 47500, dtype=torch.float32, device='cuda:0'))
```
the result is correct on both a 24GB and 48GB GPU in Windows. But a dimension of around 48000x48000 or above produces the above error message (while not doing so in WSL/Linux).

Unsure if the issue originates with Pytorch or Numpy. This may affect more than just `torch.linalg.cholesky`, I haven't tested.

### Versions

PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.25.0-rc4
Libc version: N/A

Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA RTX 6000 Ada Generation
GPU 2: NVIDIA RTX 6000 Ada Generation
GPU 3: NVIDIA RTX 6000 Ada Generation
GPU 4: NVIDIA RTX 6000 Ada Generation
GPU 5: NVIDIA RTX 6000 Ada Generation
GPU 6: NVIDIA RTX 6000 Ada Generation
GPU 7: NVIDIA RTX 6000 Ada Generation
GPU 8: NVIDIA RTX 6000 Ada Generation
GPU 9: NVIDIA RTX 6000 Ada Generation

Nvidia driver version: 560.70
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2701
DeviceID=CPU0
Family=107
L2CacheSize=32768
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=2701
Name=AMD Ryzen Threadripper PRO 5995WX 64-Cores
ProcessorType=3
Revision=2050

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.26.4
[pip3] onnx==1.13.0
[pip3] onnx-graphsurgeon==0.3.12
[pip3] torch==2.3.1+cu121
[pip3] torchaudio==2.3.1+cu121
[pip3] torchvision==0.18.1+cu121
[conda] No relevant packages

**Comment by taras-janea** [comment]
@grimulkan could you please provide the script output when using the latest PyTorch version, and setting the following flags before the function call:
```
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["TORCH_SHOW_CPP_STACKTRACES"] = "1"
os.environ["TORCH_CPP_LOG_LEVEL"] = "INFO"
```

**Comment by lezcano** [comment]
Removing edge cases, as the cholesky decomposition of the identity is just the identity, and the Cholesky decomposition algorithms do not depend on the inverse of the eigengap or anything like that.

**Comment by grimulkan** [comment]
With pytorch 2.7.1, numpy 2.1.2, CUDA 12.6, error still remains on Windows.

```python
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["TORCH_SHOW_CPP_STACKTRACES"] = "1"
os.environ["TORCH_CPP_LOG_LEVEL"] = "INFO"

import torch

chol = torch.linalg.cholesky(torch.eye(53248, 53248, dtype=torch.float32, device='cuda:0'))
print(chol)
```

Output:

```
[W610 14:00:47.000000000 Module.cpp:185] symbolizing C++ stack trace for exception; if this hangs, rerun with TORCH_DISABLE_ADDR2LINE=1...

D:\pytest\test_chol.py:8: UserWarning: record_context_cpp is not support on non-linux non-x86_64 platforms (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\profiler\unwind\unwind.cpp:11.)
  chol = torch.linalg.cholesky(torch.eye(53248, 53248, dtype=torch.float32, device='cuda:0'))
Traceback (most recent call last):
  File "D:\pytest\test_chol.py", line 8, in <module>
    chol = torch.linalg.cholesky(torch.eye(53248, 53248, dtype=torch.float32, device='cuda:0'))
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 40961 is not positive-definite).
Exception raised from _linalg_check_errors at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\BatchLinearAlgebra.cpp:1617 (most recent call first):
C++ CapturedTraceback:
```

**Comment by lezcano** [comment]
btw, the issue here is that the backend uses int32 arithmetic, and the number of elements is larger than 2**31. Alas, not much to do here.

I wonder why does the linux path work tho.

**Comment by grimulkan** [comment]
Here's the output for the same package versions, same code as above, but on WSL instead (same machine):

```
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], device='cuda:0')
```

Basically, it works. I also did test dual booting into native Linux and that also works.

2^31 is not actually that big a size, it's kind of sad that we can't make it work. Egs., the largest Llama 3 model has matrices that can get that big in the MLP layer (when doing A*A'). Maybe the linux path uses a 64-bit backend?

**Comment by grimulkan** [comment]
48000*48000 is less than 2^31 though, wonder why that also fails on Windows native. That's what made me think it wasn't the 32-bit boundary initially.

**Comment by lezcano** [comment]
Some buffers may be slightly larger than the matrix size as they it may need some extra workspace, probably from there.

Regarding this issue, there are other issues open discussing this. It's not an intrinsic limitation of the library as blas offers a 64bit API. It's just that no one in the core team has the time to integrate it

**Comment by taras-janea** [comment]
@lezcano would you mind sharing the links to the other issues you mentioned that discuss this topic? It would be helpful to read through them for more context. Appreciate your time!

**Comment by lezcano** [comment]
e.g. https://github.com/pytorch/pytorch/issues/92141

**Comment by taras-janea** [comment]
@lezcano Thank you for quick reply. Is my understanding correct that if https://github.com/pytorch/pytorch/issues/51720 is resolved, then the issue reported in this ticket would be resolved as well?

**Comment by lezcano** [comment]
on CPU yes. On GPU the same would be needed using cublas/cusolver.
