### ISSUE TITLE
xpu: NotImplementedError: elapsed_time is not supported by XPUEvent

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#131840]
With https://github.com/pytorch/pytorch/commit/f063027d5424c6b90588ef0e84e9c21be4ce68ae I am trying to follow https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html#demonstrating-speedups to check that `torch.compile` works for XPU backend. I eventually change `s/cuda/xpu/` in the example - see overall code below. Running example give the following error:
```
Traceback (most recent call last):
  File "/home/dvrogozh/examples/torch/tutorials/ex4.py", line 39, in <module>
    print("eager:", timed(lambda: model(inp))[1])
  File "/home/dvrogozh/examples/torch/tutorials/ex4.py", line 13, in timed
    return result, start.elapsed_time(end) / 1000
  File "/home/dvrogozh/git/pytorch/pytorch/torch/xpu/streams.py", line 153, in elapsed_time
    return super().elapsed_time(end_event)
NotImplementedError: elapsed_time is not supported by XPUEvent.
```
Example script below (aka `ex4.py`):
```
import torch

# Returns the result of running `fn()` and the time it took for `fn()` to run,
# in seconds. We use CUDA events and synchronization for the most accurate
# measurements.
def timed(fn):
    start = torch.xpu.Event(enable_timing=True)
    end = torch.xpu.Event(enable_timing=True)
    start.record()
    result = fn()
    end.record()
    torch.xpu.synchronize()
    return result, start.elapsed_time(end) / 1000

# Generates random input and targets data for the model, where `b` is
# batch size.
def generate_data(b):
    return (
        torch.randn(b, 3, 128, 128).to(torch.float32).xpu(),
        torch.randint(1000, (b,)).xpu(),
    )

N_ITERS = 10

from torchvision.models import densenet121
def init_model():
    return densenet121().to(torch.float32).xpu()

model = init_model()

# Reset since we are using a different mode.
import torch._dynamo
torch._dynamo.reset()

model_opt = torch.compile(model, mode="reduce-overhead")

inp = generate_data(16)[0]
with torch.no_grad():
    print("eager:", timed(lambda: model(inp))[1])
    print("compile:", timed(lambda: model_opt(inp))[1])
```

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5 @vlad-penkin

**Comment by guangyey** [comment]
This is a known issue, which depends on compiler 2025.0

**Comment by dvrogozh** [comment]
> This is a known issue, which depends on compiler 2025.0

`elapsed_time()` in XPUEvent depends on _compiler_? This sounds strange. Can you, please, provide details - which APIs are features are missing? Please, point to filed issues requesting these features.

Also, this blocks basic `torch.compile()` example from PyTorch tutorial. Can you suggest some workaround to achieve the same - get elapsed timings for eager and graph modes to see benefits of `torch.compile()`?

**Comment by gujinghui** [comment]
> > This is a known issue, which depends on compiler 2025.0
> 
> `elapsed_time()` in XPUEvent depends on _compiler_? This sounds strange. Can you, please, provide details - which APIs are features are missing? Please, point to filed issues requesting these features.
> 
> Also, this blocks basic `torch.compile()` example from PyTorch tutorial. Can you suggest some workaround to achieve the same - get elapsed timings for eager and graph modes to see benefits of `torch.compile()`?

It depends on SYCL runtime in SYCL compiler package, to provide event-wise timestamp.
Can you temporarily use E2E time in the case?

**Comment by dvrogozh** [comment]
> Can you temporarily use E2E time in the case?

I can though this will come with lower precision measurements. The problem is that significant amount of people will simply stop trying once this issue will be met. To have code handy, here is a function modified for e2e time measurement:
```
def timed(fn):
    start =  time.time_ns()
    result = fn()
    torch.xpu.synchronize()
    return result, (time.time_ns() - start) / 1000000000
```

**Comment by dvrogozh** [comment]
> It depends on SYCL runtime in SYCL compiler package, to provide event-wise timestamp.

@gujinghui : if I understand correctly, the following 2 PRs have added the required sycl extension to implement elapsed_time for XPUEvent. They have been merged already.
* https://github.com/intel/llvm/pull/12194
* https://github.com/intel/llvm/pull/12838

It seems that @alexbaden have updated the https://github.com/pytorch/pytorch/pull/126456 to use the new extension. Given right dpc++ version (maybe built from main) it can be tried.

**Comment by EikanWang** [comment]
@guangyey , I remembered that the feature depends on the oneAPI uplift. Correct?

**Comment by guangyey** [comment]
This feature is already implemented in PyTorch, but some corner cases need to be fixed depending on the oneAPI uplift.

**Comment by dvrogozh** [comment]
@chuanqi129 : it would be nice to point to the specific PR or changes which addressed the issue.

**Comment by dvrogozh** [comment]
> @chuanqi129 : it would be nice to point to the specific PR or changes which addressed the issue.

Answering myself. Done in https://github.com/pytorch/pytorch/commit/a8482ab3a82b5d83d66184f6c25124334af6d218 (https://github.com/pytorch/pytorch/pull/140873), available in PT2.7.
