### ISSUE TITLE
TORCH_COMPILE_CPROFILE=1 broken (strobelight might always be on internally?)

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#131953]
Repro: `TORCH_COMPILE_CPROFILE=1 python foo.py`
on
```py
import torch

@torch.compile
def f(x):
    return x.sin()

x = torch.randn(3, device="cuda")
f(x)
```
gives the following stack trace:
```
Traceback (most recent call last):
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/foo.py", line 8, in <module>
    f(x)
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/eval_frame.py", line 448, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/convert_frame.py", line 1171, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/convert_frame.py", line 980, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/convert_frame.py", line 500, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/convert_frame.py", line 878, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/convert_frame.py", line 851, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/utils.py", line 272, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/pt-opt-cuda3/torch/_dynamo/convert_frame.py", line 334, in profile_wrapper
    retval = prof.runcall(func, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzou/dev/opt-cuda3/env/lib/python3.12/cProfile.py", line 109, in runcall
    self.enable()
torch._dynamo.exc.InternalTorchDynamoError: Another profiling tool is already active
```

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @oulgen @jamesjwu @aorenste @anijain2305 @laithsakka

**Comment by yf225** [comment]
I tried on a RunPod gpu machine, it still repros. Seems not specific to internal machines. cc. @laithsakka

**Comment by jamesjwu** [comment]
cc @laithsakka

**Comment by laithsakka** [comment]
is the issue with TORCH_COMPILE_CPROFILE or TORCH_COMPILE_STROBELIGHT?
those two are orthogonal, CPROFILE does not care if STROBELIGHT is already running and the vice versa.

int the stack above, strobelight is not enabled since it goes to line 129.  
```
 def profile_compile_time(
        cls, func: Any, phase_name: str, *args: Any, **kwargs: Any
    ) -> Any:
        if not cls.enabled:
            return func(*args, **kwargs)
```
the error seems to be from cProfile.

if you want to try strobelight you can pass TORCH_COMPILE_STROBELIGHT=1. 
for the cProfile you might want to ask Daohang Shi (not sure whats his github).

**Comment by oulgen** [comment]
@laithsakka the confusion about whether strobelight is running or not have showed up multiple times, can you change the code so that when strobelight is not running, there's no mention of strobelight in the stack trace?

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/blob/6cf493158ef1f427e04f43d5b0ba1d702718af09/torch/_dynamo/convert_frame.py#L647

It's not clear to me what the above line is doing. Is this unconditionally enabling strobelight? Because it reads like it (internal: https://www.internalfb.com/code/fbsource/[93215e474c7915b93bed42622c4a8503c809f515]/fbcode/caffe2/fb/_utils_internal.py?lines=321-322)

**Comment by laithsakka** [comment]
I can rename it to maybe_compile_time_strobelight_meta.
this guy here is like maybe_cprofile and dynamo_time, it will trigger the profiling only if 
 TORCH_COMPILE_STROBELIGHT=1 else it does nothing.

**Comment by laithsakka** [comment]
I think i move  
  if not cls.enabled:
            return func(*args, **kwargs) 
        outside  to the wrapper we wont see this in the call stack. I will put PR

**Comment by ezyang** [comment]
Yes, please do, a lot of people use call stack to understand what is being done and so if they see "strobelight" in stack they get very nervous

**Comment by masnesral** [comment]
@laithsakka I'm helping with the old issue scrubbing. Did you make the change you mention above or should this stay open?

**Comment by laithsakka** [comment]
fixed
