### ISSUE TITLE
Pytorch conversion to ONNX inserts ScatterNDUpdate Layers

### ISSUE THREAD

**Issue by IkrameBeggar** [pytorch/pytorch#132002]
### 🐛 Describe the bug

Hello everyone, I have a pose estimation model(SPNv2). I converted the model from Pytorch FP32 to OpenVINO FP16 IR representation (passing by onnx).

I converted a PyTorch model to ONNX to run inferences on it using OpenVINO on NCS2 (VPU). The converted model comprises scatterNDupdate layers which are not supported by the VPU. Is there any specific reason for the creation of those layers? and a way to avoid them?

When I tried to run the model on NCS2 I had this error:

Traceback (most recent call last):
File "test_spnv2_myriad.py", line 49, in
compiled_model = ie_core.compile_model(model=model, device_name="MYRIAD")
File "/opt/intel/openvino_2022.3.1/python/python3.8/openvino/runtime/ie_api.py", line 399, in compile_model
super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: [ GENERAL_ERROR ]
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:596 Failed to compile layer "ScatterND_8672": unsupported layer type "ScatterNDUpdate"

Can anyone help me with this please?

### Versions

PyTorch version: 1.13.0+cu117
OS: Ubuntu 20.04.4 LTS (x86_64)
Python:  3.8.10
OpenVINO version: 2022.3.1

GPU models and configuration: GPU 0: NVIDIA GeForce RTX4060

Versions of relevant libraries:
yacs==0.1.8
albumentations==1.1.0
matplotlib==3.4.2
tqdm==4.62.2
plyfile==0.7.4
scipy==1.7.1
pandas==1.3.1
numpy==1.21.2
Pillow==9.0.0

**Comment by justinchuby** [comment]
Can you share a script that will export the model?

**Comment by IkrameBeggar** [comment]
> Can you share a script that will export the model?

You can find it [here](https://drive.google.com/file/d/1otbHnGpJcoxgpjWUIt3bY8IiLuQinhY3/view?usp=drivesdk)

**Comment by justinchuby** [comment]
It would be helpful to provide a script that’s directly reproducible.

**Comment by IkrameBeggar** [comment]
> It would be helpful to provide a script that’s directly reproducible.
> 
> The torch->onnx part is what we need here. The open vino part is not needed since we only need to investigate what produced the operators.

Sorry, here it is:

# Load the model
print("Load the model architecture")
model = build_spnv2(cfg)
model.to(device)


# Save the model.
weights_path = "weights/model_final.pth.tar"
if Path(weights_path).exists():
    model.load_state_dict(torch.load(weights_path))

model_path.parent.mkdir(exist_ok=True)
torch.save(model, str(model_path))
print(f"Model saved at {model_path}")

# ONNX model conversion
if not onnx_path.exists():
# Create the dummy input tensor on the CPU
    dummy_input = torch.randn(1, 3, IMAGE_HEIGHT, IMAGE_WIDTH)

    # Move the input tensor to the device if GPU is used
    if device.type == 'cuda':
        dummy_input = dummy_input.to(device)
    

    # For the Fastseg model, setting do_constant_folding to False is required
    # for PyTorch > 1.5.1
    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        opset_version=11,
        do_constant_folding=False,
    )
    print(f"ONNX model exported to {onnx_path}.")
else:
    print(f"ONNX model {onnx_path} already exists.")

**Comment by justinchuby** [comment]
It is unclear what build_spnv2 or cfg is. Please provide a script that can run on its own.

**Comment by IkrameBeggar** [comment]
> It is unclear what build_spnv2 or cfg is. Please provide a script that can run on its own.

build_spnv2 is the model architecture 
Cfg is the configuration file

**Comment by titaiwangms** [comment]
Please feel free to test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!
