### ISSUE TITLE
Nightly Windows conda and wheel CUDA 12.1 and 12.4 are broken, oom

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#132042]
### 🐛 Describe the bug

Failure:
https://github.com/pytorch/pytorch/actions/runs/10140052044/job/28034482560

Error observed:
```
tmpxft_00001418_00000000-7_attention_backward.compute_90.cudafe1.cpp
[7845/8497] Building CXX object caffe2\CMakeFiles\torch_cuda.dir\__\aten\src\ATen\cuda\CUDASparseBlas.cpp.obj
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\deprecations.py", line 70, in inner
    return func(*args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\cli\main_build.py", line 589, in main
    execute(sys.argv[1:])
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\cli\main_build.py", line 568, in execute
    outputs = api.build(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\api.py", line 253, in build
    return build_tree(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\build.py", line 3804, in build_tree
    packages_from_this = build(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\build.py", line 2629, in build
    windows.build(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\windows.py", line 341, in build
    check_call_env(
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\utils.py", line 422, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\utils.py", line 292, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\utils.py", line 366, in _execute
    self.disk = max(directory_size(disk_usage_dir), self.disk)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\site-packages\conda_build\utils.py", line 192, in directory_size
    out = subprocess.check_output(command.format(path), shell=True)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.9_074920\conda\lib\subprocess.py", line 1141, in communicate
    stdout = self.stdout.read()
MemoryError
```

Most likely cause: https://github.com/pytorch/pytorch/pull/131906

### Versions

2.5.0

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @osalpekar @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by lw** [comment]
According to @albanD, FlashAttention can take up to 30GB of memory to compile. However, we somehow manage to build FlashAttention in the CI of [xFormers](https://github.com/facebookresearch/xformers), hence I'm surprised that we cannot build it in PyTorch.

Note that in https://github.com/pytorch/pytorch/pull/131875 (my first attempt at that PR) I had added the trunk and periodic tags in order to issue some Windows build jobs and they all passed. Why are the jobs for conda and pip any different?

**Comment by albanD** [comment]
Two things that might influence this:
- Do we use the same windows build machines for xFormers and core? Are we building the same version of FA there?
- There might be a lot more compilation parallelism in core than xFormers?

Reducing compilation parallelism is tricky as it can make the build take a LOT more time (And timeout).

**Comment by atalman** [comment]
@lw we would also need to add ciflow/binaries label to the PR

**Comment by lw** [comment]
Ok to revert for now, but I'd appreciate some guidance on how to land this properly.

**Comment by malfet** [comment]
Removing high priority as PR causing OOMS has been reverted

**Comment by atalman** [comment]
Closing this issue for now. Reverted the culprit PR.
