### ISSUE TITLE
Caffe2: Causes error when using flag remove_legacy_pad while converting from caffe to caffe2

### ISSUE THREAD

**Issue by parth1595** [pytorch/pytorch#13224]
I was converting basic cat dog model from caffe to caffe2 framework using caffe_translator.py but in conversion it shows a legacy_padding in max pool operation argument which I don't want so i try to remove it using the caffe_translator script in which remove_legacy_pad flag is there which can be enable when we give it in argument while running the script. But it throws some error which I don't know what it is. 

**Error Log**
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1028 15:43:38.935531   680 init.h:99] Caffe2 GlobalInit should be run before any other API calls.
Traceback (most recent call last):
  File "/home/parthr/project/pytorch/caffe2/python/caffe_translator.py", line 927, in <module>
    input_dims=input_dims,
  File "/home/parthr/project/pytorch/caffe2/python/caffe_translator.py", line 285, in TranslateModel
    return TranslatorRegistry.TranslateModel(*args, **kwargs)
  File "/home/parthr/project/pytorch/caffe2/python/caffe_translator.py", line 280, in TranslateModel
    net = _RemoveLegacyPad(net, net_params, input_dims)
  File "/home/parthr/project/pytorch/caffe2/python/caffe_translator.py", line 131, in _RemoveLegacyPad
    ws.create_blob(external_input).feed_blob(dummy_input)
AttributeError: 'caffe2.python.caffe2_pybind11_state.Blob' object has no attribute 'feed_blob'

**Comment by farhan333** [comment]
I'm getting the same error. Any Luck ?

**Comment by hankchuan** [comment]
try to change "'feed_blob'" to "feed" methods like this:
ws.create_blob(external_input).feed(dummy_input)
