### ISSUE TITLE
MultiProcTest Exception "None is not -6"

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#132428]
https://github.com/pytorch/pytorch/actions/runs/10117704483/job/28178859665
<img width="960" alt="image" src="https://github.com/user-attachments/assets/61dcdaa8-5d7a-4810-9f7d-719b50204a83">

A few tests related to the Flight Recorder have begun failing recently.
 * first reported by @ZainRizvi as part of a new AMI upgrade (not on trunk)
 * noticed by @wconstab on trunk as flaky test as of 8/1, not sure how long it's been happening

After debugging via SSH on the new AMI via this PR (#131946), I confirmed that the Flight Recorder functionality seems fine, and the test code and pytorch code seems to behave as expected.  Namely, the test intentionally hangs a collective.  One rank first notices this and sets a global flag in TCPStore. The other rank notices this flag.  Both flags raise a timeout error, dump their flight logs, and then raise a SIGABRT with an exception about the timeout.

But after raising the SIGABRT, the pytorch processes (rank0, rank1) do not exit.  The parent (test launcher) waits on .join() call until the join timeout, and then finds a None exitcode.

Attaching GDB to the rank0 or rank1 process can sometimes cause the process to exit immediately, and the test to pass.

cc @zdevito @c-p-i-o @fduwjj @ZainRizvi @malfet

**Comment by ZainRizvi** [comment]
As discussed offline, the job linked above that failed on trunk was running on the new Amazon 2023 AMI.  Distributed jobs on trunk were reverted back to using the old AMI last Friday

**Comment by ZainRizvi** [comment]
More details on the failures I observed:


Examples of the failures:
Failure 1: https://github.com/pytorch/pytorch/actions/runs/10047579686/job/27770963175
```
FAILED [90.0880s] distributed/test_c10d_nccl.py::NCCLTraceTestDumpOnTimeout::test_timeout_dumps_timing_enabled_False - AssertionError: None mismatch: None is not -6
```

Failure 2: https://github.com/pytorch/pytorch/actions/runs/10047579686/job/27770963494
```
____ NCCLTraceTestTimeoutDumpOnStuckRanks.test_timeout_dumps_on_stuck_ranks ____
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/distributed/test_c10d_nccl.py", line 4214, in test_timeout_dumps_on_stuck_ranks
    self.assertEqual(self._wait_process(0, timeout=90), -6)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3721, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: None mismatch: None is not -6
```

Failing tests are now being skipped as of https://github.com/pytorch/pytorch/pull/133355

**Comment by ZainRizvi** [comment]
@wconstab @c-p-i-o @fduwjj  Continuing the conversation from https://github.com/pytorch/pytorch/pull/133355

Any idea what level of the stack this test failure is occurring at? Is Nccl actually timing out and returning the same error code as before? Or has the python code perhaps changed how it catches these failures?

**Comment by c-p-i-o** [comment]
> @wconstab @c-p-i-o @fduwjj Continuing the conversation from #133355
> 
> Any idea what level of the stack this test failure is occurring at? Is Nccl actually timing out and returning the same error code as before? Or has the python code perhaps changed how it catches these failures?

The code is as follows:
```
self.assertEqual(self.processes[0].exitcode, -6)
```

So in cases, the self.processs[0].exitcode no longer contains the expected value after the process exits.

Similarly the following code;
```
    def _wait_process(self, rank, timeout):
        try:
            self.processes[rank].join(timeout)
            return self.processes[rank].exitcode
        except TimeoutError:
            return None
    ```
    It used to return `exitcode` but that's not happening anymore.

**Comment by fduwjj** [comment]
@ZainRizvi I think what @wconstab wrote here means that the code is working (the actual NCCL timeout is working as expected). It's this test code itself has problems.

**Comment by c-p-i-o** [comment]
> @ZainRizvi I think what @wconstab wrote here means that the code is working (the actual NCCL timeout is working as expected). It's this test code itself has problems.

That is my understanding too. With the new AMI, somehow timings have changed and/or `exitcode` propagation in Python isn't happening as before for whatever reason.
