### ISSUE TITLE
dynamo IndexError: list index out of range on Windows UT

### ISSUE THREAD

**Issue by xuhancn** [pytorch/pytorch#132569]
### 🐛 Describe the bug

reproduce:
Setup env: https://github.com/pytorch/pytorch/issues/124245#issuecomment-2254993625
```cmd
pytest test\inductor\test_cpu_cpp_wrapper.py -v -k test_qlinear_gelu_cpu_dynamic_shapes_cpp_wrapper
```
err msg:
```cmd
Traceback (most recent call last):
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\testing\_internal\common_utils.py", line 2918, in wrapper
    method(*args, **kwargs)
  File "D:\xu_git\dnnl_cb\pytorch\test\inductor\test_torchinductor.py", line 11208, in new_test
    return value(self)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\_dynamo\testing.py", line 312, in _fn
    return fn(*args, **kwargs)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\xu_git\dnnl_cb\pytorch\test\inductor\test_cpu_cpp_wrapper.py", line 156, in fn
    _, code = test_torchinductor.run_and_get_cpp_code(
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\_inductor\utils.py", line 1862, in run_and_get_cpp_code
    result = fn(*args, **kwargs)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\testing\_internal\common_quantization.py", line 415, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\testing\_internal\common_quantization.py", line 367, in wrapper
    fn(*args, **kwargs)
  File "D:\xu_git\dnnl_cb\pytorch\test\inductor\test_mkldnn_pattern_matcher.py", line 1668, in test_qlinear_gelu_cpu
    self._qlinear_unary_cpu_test_helper((torch.randn((2, 4)),), gelu)
  File "D:\xu_git\dnnl_cb\pytorch\test\inductor\test_mkldnn_pattern_matcher.py", line 1615, in _qlinear_unary_cpu_test_helper
    self._test_common(
  File "D:\xu_git\dnnl_cb\pytorch\test\inductor\test_mkldnn_pattern_matcher.py", line 165, in _test_common
    convert_model = _generate_qdq_quantized_model(
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\testing\_internal\common_quantization.py", line 2962, in _generate_qdq_quantized_model
    torch.ao.quantization.move_exported_model_to_eval(prepare_model)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\ao\quantization\pt2e\export_utils.py", line 181, in _move_exported_model_to_eval
    _replace_dropout(model, train_to_eval=True)
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\ao\quantization\pt2e\export_utils.py", line 66, in _replace_dropout
    match_pattern = _get_aten_graph_module_for_pattern(
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\ao\quantization\pt2e\utils.py", line 355, in _get_aten_graph_module_for_pattern
    aten_pattern = capture_pre_autograd_graph(
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\_export\__init__.py", line 143, in capture_pre_autograd_graph
    m = torch._dynamo.export(
  File "C:\Users\Xuhan\.conda\envs\win_mkl_static\lib\site-packages\torch\_dynamo\eval_frame.py", line 1481, in inner
    if torch.is_tensor(flat_args[i]):
IndexError: list index out of range

To execute this test, run the following from the base repo dir:
    python test\inductor\test_cpu_cpp_wrapper.py -k DynamicShapesCppWrapperCpuTests.test_qlinear_gelu_cpu_dynamic_shapes_cpp_wrapper

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
--------------------------------------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------------------------------------
stats [('calls_captured', 4), ('unique_graphs', 1)]
--------------------------------------------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------------------------------------------
W0803 12:31:56.970000 35176 torch\_export\__init__.py:64] +============================+
W0803 12:31:56.970000 35176 torch\_export\__init__.py:65] |     !!!   WARNING   !!!    |
W0803 12:31:56.970000 35176 torch\_export\__init__.py:66] +============================+
W0803 12:31:56.970000 35176 torch\_export\__init__.py:67] capture_pre_autograd_graph() is deprecated and doesn't provide any function guarantee moving forward.
W0803 12:31:56.970000 35176 torch\_export\__init__.py:68] Please switch to use torch.export instead.
========================================================================================================================== short test summary info ==========================================================================================================================
FAILED [0.2835s] test/inductor/test_cpu_cpp_wrapper.py::DynamicShapesCppWrapperCpuTests::test_qlinear_gelu_cpu_dynamic_shapes_cpp_wrapper - IndexError: list index out of range
```

### Versions

Latest main branch code can reproduce the issue.
I'm working on enable `torch.compile` on Windows, and occured this issue, but I'm not a dynamo expert. So, I have to open this issue and ask help from community.

```
Collecting environment information...
PyTorch version: 2.5.0a0+giteb5883f
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Ti
Nvidia driver version: 472.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3303
DeviceID=CPU0
Family=207
L2CacheSize=10240
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3303
Name=11th Gen Intel(R) Core(TM) i9-11900KB @ 3.30GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==2.0.0
[pip3] torch==2.5.0a0+git0738916
[pip3] torchvision==0.19.0a0+06ad737
[conda] mkl-include               2024.2.0                 pypi_0    pypi
[conda] mkl-static                2024.2.0                 pypi_0    pypi
[conda] numpy                     2.0.0                    pypi_0    pypi
[conda] torch                     2.5.0a0+gitff2008f          pypi_0    pypi
[conda] torchvision               0.19.0a0+06ad737          pypi_0    pypi
```

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @msaroufim @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by xuhancn** [comment]
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/aa255ff5-b42e-4345-8db5-0337d84e1862">

Please priority to fix this PR, it is failed many UTs.

**Comment by Guobing-Chen** [comment]
@malfet, to be aware on this issue also as blocking the Inductor Windows enabling.

**Comment by xuhancn** [comment]
@BoyuanFeng who will be assigned as the issue owner?

**Comment by malfet** [comment]
@Guobing-Chen so what's the ask here? Easiest short term solution (if it's isolated) seems like excluding export tests from running on Windows for now

**Comment by xuhancn** [comment]
> @Guobing-Chen so what's the ask here? Easiest short term solution (if it's isolated) seems like excluding export tests from running on Windows for now

@malfet we want to ask help to fix the issue as long term solution.

**Comment by malfet** [comment]
@Guobing-Chen do you have a local reproducer? (Or even better a work-in-progress PR that exposes this problem?)

**Comment by xuhancn** [comment]
> @Guobing-Chen do you have a local reproducer? (Or even better a work-in-progress PR that exposes this problem?)

@malfet I will try to provide it. Thanks.

**Comment by xuhancn** [comment]
> @xuhancn, are there any updates? Could you please provide a WIP PR that enables the issue on the latest `viable/strict`? Thanks!

How to do it? checkout a new branch from `viable/strict`, and then apply issue enabling code? @taras-janea

**Comment by taras-janea** [comment]
> > @xuhancn, are there any updates? Could you please provide a WIP PR that enables the issue on the latest `viable/strict`? Thanks!
> 
> How to do it? checkout a new branch from `viable/strict`, and then apply issue enabling code? @taras-janea

Yes, to apply a commit based on `viable/strict` that enables the reported issue.

**Comment by xuhancn** [comment]
Hi @taras-janea, I tried to repo this issue via easier way, that is re-enable `test_x86inductor_quantizer.py`. But, due to the main branch is move farward, the issue seems gone, please check: https://github.com/pytorch/pytorch/pull/138937.

Currently, the `torch inductor` on Windows UTs are not enabled, due to it always timeout: https://github.com/pytorch/pytorch/issues/135927. So, a lot of related UT are unknown status. I have other more priority work to do, so I will re-calibrating these UTs after some time. Please wait for a while.
