### ISSUE TITLE
Dynamic rendezvous with etcd-v2 fails with "etcd.EtcdKeyNotFound: Key not found : /torch/elastic/store"

### ISSUE THREAD

**Issue by alenawang** [pytorch/pytorch#132950]
### 🐛 Describe the bug

**Environment**

- PyTorch 2.4.0
- Kubernetes, launching distributed PyTorchJob (1 master and 1 worker replica) with KubeFlow Training Operator
- Launching with `torchrun`
- Using `etcd-v2` as the rendezvous backend

**Error**

The training run fails immediately on startup with the error `etcd.EtcdKeyNotFound: Key not found : /torch/elastic/store` on the worker pod. The master pod errors out with `torch.distributed.elastic.rendezvous.api.RendezvousClosedError`. Subsequent restarts fail also due to the rendezvous being closed.

From the debug logs, it seems like when the master joins the rendezvous first it needs to wait for all participants so is stuck waiting [here](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py#L937). When the worker joins, all participants are ready so it completes the `_RendezvousJoinOp` first and calls `RendezvousStoreInfo.build` [here](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py#L1150) first. Because the worker reaches this method first, the master has not yet written the master address info to `/torch/elastic/store` [here](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/api.py#L78-L79) yet, so the worker's call to retrieve this info [here](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/api.py#L81) fails and the worker closes the rendezvous.

Reversing this order by adding a brief sleep to the master pod (so the worker is the one waiting and the master completes the rendezvous first) seems to resolve this issue. Adding a sleep right before the [store.get call](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/api.py#L81) if rank != 0 so that the master has time to write the keys also seems to work. I assume adding retry logic to the store.get call should also work.

**Master pod logs**

```
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189] Starting elastic_operator with launch configs:
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   entrypoint       : /tmp/tmp.eQ7OYvCMN8
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   min_nodes        : 2
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   max_nodes        : 2
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   nproc_per_node   : 1
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   run_id           : foo
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   rdzv_backend     : etcd-v2
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   rdzv_endpoint    : foo-etcd:2379
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   rdzv_configs     : {'timeout': 900}
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   max_restarts     : 10000
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   monitor_interval : 0.1
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   log_dir          : /tmp/torchelastic_bx1mdg4b
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189]   metrics_cfg      : {}
I0807 20:59:57.533000 139762139563840 torch/distributed/launcher/api.py:189] 
I0807 20:59:57.622000 139762139563840 torch/distributed/elastic/agent/server/api.py:825] [default] starting workers for entrypoint: python
I0807 20:59:57.622000 139762139563840 torch/distributed/elastic/agent/server/api.py:646] [default] Rendezvous'ing worker group
I0807 20:59:57.630000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1109] The node 'foo-master-0_8_0' attempts to join the next round of the rendezvous 'foo'.
V0807 20:59:57.631000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:718] The node 'foo-master-0_8_0' added itself to the participants of round 0 of the rendezvous 'foo'. Pending sync.
V0807 20:59:57.632000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:708] The node 'foo-master-0_8_0' updated its keep-alive heartbeat time for the rendezvous 'foo'. Pending sync.
V0807 20:59:57.635000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:653] The node 'foo-master-0_8_0' has successfully synced its local changes with other nodes in the rendezvous 'foo'.
V0807 20:59:57.636000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:938] The node 'foo-master-0_8_0' can't complete rendezvous: not enough participants
V0807 20:59:58.638000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:938] The node 'foo-master-0_8_0' can't complete rendezvous: not enough participants
V0807 20:59:59.640000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:938] The node 'foo-master-0_8_0' can't complete rendezvous: not enough participants
V0807 21:00:00.643000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:938] The node 'foo-master-0_8_0' can't complete rendezvous: not enough participants
V0807 21:00:01.645000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:938] The node 'foo-master-0_8_0' can't complete rendezvous: not enough participants
I0807 21:00:02.649000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1237] The node 'foo-master-0_8_0' has closed the rendezvous 'foo'.
I0807 21:00:02.650000 139762139563840 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1237] The node 'foo-master-0_8_0' has closed the rendezvous 'foo'.
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 680, in run
    result = self._invoke_run(role)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1125, in next_rendezvous
    self._op_executor.run(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 667, in run
    raise RendezvousClosedError
torch.distributed.elastic.rendezvous.api.RendezvousClosedError
```

**Worker pod logs**

```
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189] Starting elastic_operator with launch configs:
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   entrypoint       : /tmp/tmp.LVBo1dpr8Y
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   min_nodes        : 2
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   max_nodes        : 2
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   nproc_per_node   : 1
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   run_id           : foo
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   rdzv_backend     : etcd-v2
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   rdzv_endpoint    : foo-etcd:2379
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   rdzv_configs     : {'timeout': 900}
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   max_restarts     : 10000
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   monitor_interval : 0.1
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   log_dir          : /tmp/torchelastic_txbbvdn4
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189]   metrics_cfg      : {}
I0807 21:00:02.487000 139857836099392 torch/distributed/launcher/api.py:189] 
I0807 21:00:02.575000 139857836099392 torch/distributed/elastic/agent/server/api.py:825] [default] starting workers for entrypoint: python
I0807 21:00:02.575000 139857836099392 torch/distributed/elastic/agent/server/api.py:646] [default] Rendezvous'ing worker group
I0807 21:00:02.583000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1109] The node 'foo-worker-0_8_0' attempts to join the next round of the rendezvous 'foo'.
V0807 21:00:02.629000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:718] The node 'foo-worker-0_8_0' added itself to the participants of round 0 of the rendezvous 'foo'. Pending sync.
V0807 21:00:02.630000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:708] The node 'foo-worker-0_8_0' updated its keep-alive heartbeat time for the rendezvous 'foo'. Pending sync.
V0807 21:00:02.631000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:813] The node 'foo-worker-0_8_0' marked round 0 of the rendezvous 'foo' as complete. Pending sync.
V0807 21:00:02.637000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:653] The node 'foo-worker-0_8_0' has successfully synced its local changes with other nodes in the rendezvous 'foo'.
I0807 21:00:02.638000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1148] The node 'foo-worker-0_8_0' has joined round 0 of the rendezvous 'foo' as rank 1 in a world of size 2.
V0807 21:00:02.640000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:830] The node 'foo-worker-0_8_0' marked the rendezvous 'foo' as closed. Pending sync.
V0807 21:00:02.644000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:653] The node 'foo-worker-0_8_0' has successfully synced its local changes with other nodes in the rendezvous 'foo'.
I0807 21:00:02.644000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1237] The node 'foo-worker-0_8_0' has closed the rendezvous 'foo'.
I0807 21:00:02.645000 139857836099392 torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1237] The node 'foo-worker-0_8_0' has closed the rendezvous 'foo'.
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 680, in run
    result = self._invoke_run(role)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1150, in next_rendezvous
    bootstrap_store_info = RendezvousStoreInfo.build(rank, store)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/api.py", line 81, in build
    addr = store.get(RendezvousStoreInfo.MASTER_ADDR_KEY).decode(encoding="UTF-8")
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/etcd_store.py", line 75, in get
    kvs = self._try_wait_get([b64_key])
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/etcd_store.py", line 179, in _try_wait_get
    all_nodes = self.client.get(key=self.prefix)
  File "/opt/conda/lib/python3.10/site-packages/etcd/client.py", line 740, in get
    return self.read(key)
  File "/opt/conda/lib/python3.10/site-packages/etcd/client.py", line 595, in read
    response = self.api_execute(
  File "/opt/conda/lib/python3.10/site-packages/etcd/client.py", line 907, in wrapper
    return self._handle_server_response(response)
  File "/opt/conda/lib/python3.10/site-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/opt/conda/lib/python3.10/site-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
etcd.EtcdKeyNotFound: Key not found : /torch/elastic/store
```

### Versions

PyTorch version: 2.4.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.219-208.866.amzn2.x86_64-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flake8==7.0.0
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.3.3
[pip3] torch==2.4.0+cpu
[pip3] torchaudio==2.4.0+cpu
[pip3] torchmetrics==1.4.1
[pip3] torchvision==0.19.0+cpu
[conda] numpy                     1.26.4          py310heeff2f4_0  
[conda] numpy-base                1.26.4          py310h8a23956_0  
[conda] pytorch-lightning         2.3.3                    pypi_0    pypi
[conda] torch                     2.4.0+cpu                pypi_0    pypi
[conda] torchaudio                2.4.0+cpu                pypi_0    pypi
[conda] torchmetrics              1.4.1                    pypi_0    pypi
[conda] torchvision               0.19.0+cpu               pypi_0    pypi

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @dzhulgakov

**Comment by alenawang** [comment]
After further investigation, we decided the best solution was to resolve this at the etcd_store `get` level - the [get method](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/etcd_store.py#L60) is supposed to optionally do a blocking wait, but if `get` is called before the first key is ever written (so that a key with the store prefix doesn't exist yet), this [etcd client get](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/distributed/elastic/rendezvous/etcd_store.py#L179) call fails with the `EtcdKeyNotFound` error, so it never gets to the watch part. We patched this by adding a try/except, which resolves the issue:

```
try:
    all_nodes = self.client.get(key=self.prefix)
    req_nodes = {
        node.key: node.value for node in all_nodes.children if node.key in b64_keys
    }

    if len(req_nodes) == len(b64_keys):
        # All keys are available
        return req_nodes
except etcd.EtcdKeyNotFound:
    continue
```

Is this a reasonable fix, and if so is this something we could contribute?
