### ISSUE TITLE
Leaky ReLU of empty tensor doesn't work on MPS

### ISSUE THREAD

**Issue by JohnGoldenGardiner** [pytorch/pytorch#133179]
### 🐛 Describe the bug

```
import torch
import torch.nn.functional as F

x = torch.tensor([], device=torch.device('mps')).view((0, 4))
print(F.relu(x)) # Works as expected
print(F.leaky_relu(x, negative_slope=0.0)) # Breaks
```

The above code results in the following:

```
tensor([], device='mps:0', size=(0, 4))
Traceback (most recent call last):
  File "/Users/username/leaky_relu_bug.py", line 6, in <module>
    print(F.leaky_relu(x, negative_slope=0.0))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/anaconda3/envs/my_env/lib/python3.11/site-packages/torch/nn/functional.py", line 1675, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_e2rjusv8ek/croot/pytorch-select_1717607459930/work/aten/src/ATen/native/mps/OperationUtils.mm":383, please report a bug to PyTorch. Placeholder tensor is empty!
```

This fails similarly for x of any size (0, n) and for any other value of negative_slope.

### Versions

```
Collecting environment information...
PyTorch version:2.3.0.post100
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version 3.11.9 (main, Apr 19 2024, 11:43:37) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.0.post100
[conda] numpy                     1.26.4          py311he598dae_0
[conda] numpy-base                1.26.4          py311hfbfe69c_0
[conda] pytorch                   2.3.0           gpu_mps_py311hc07fac7_100
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by qqaatw** [comment]
Interestingly enough, I'm hitting this assert when `relu` is called:

RuntimeError: result.storage().use_count() == 1 INTERNAL ASSERT FAILED at "/torch/csrc/autograd/generated/VariableType_4.cpp":14862, please report a bug to PyTorch. function: relu.

Repro:

```
import torch
import torch.nn.functional as F

x = torch.tensor([], device="mps")
print(F.relu(x))
```

Env:

```
PyTorch version: 2.5.0a0+git79ca596
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.7.4 (arm64)
GCC version: Could not collect
Clang version: 18.1.5
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.7.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False
```

**Comment by jhavukainen** [comment]
This issue is fixed by now by the addition of return when numel() of input is zero. Verified on the 2.5.1 release.
