### ISSUE TITLE
Triton tl.reinterpret is not Dynamo traceable

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#133253]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/1075192433118967/posts/1480219992616207/

Repro: 

```
import torch

from triton.runtime.jit import reinterpret as tl_reinterpret
import triton.language as tl

@torch.compile(backend="eager", fullgraph=True)
def fn(x):
    return tl_reinterpret(x, dtype=tl.float8e4nv)


fn(torch.randn(3, device='cuda'))
```

Fails with

```
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 870, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 558, in wrapper
    return inner_fn(self, inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1655, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 805, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 811, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 2946, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 3062, in inline_call_
    tracer.run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 958, in run
    while self.step():
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 873, in step
    self.exception_handler(e)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1459, in exception_handler
    raise raised_exception
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 870, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1360, in RAISE_VARARGS
    raise exc.ObservedException(f"raised exception {val}")
torch._dynamo.exc.ObservedException: raised exception ExceptionVariable()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/a.py", line 11, in <module>
    fn(torch.randn(3, device='cuda'))
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 1238, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 514, in __call__
    return _compile(
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 902, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 653, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/b/pytorch/torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/data/users/ezyang/b/pytorch/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 686, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 208, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/convert_frame.py", line 622, in transform
    tracer.run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 2731, in run
    super().run()
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 958, in run
    while self.step():
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 873, in step
    self.exception_handler(e)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1458, in exception_handler
    raise Unsupported("Observed exception")
torch._dynamo.exc.Unsupported: Observed exception

from user code:
   File "/data/users/ezyang/b/pytorch/a.py", line 8, in fn
    return tl_reinterpret(x, dtype=tl.float8e4nv)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

I think the problem is when we trace the hasattr call on data_ptr. Debug logs here: https://gist.github.com/ezyang/2eb8f879a49bf5bd607dad3e8e50133b

### Versions

main

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @bertmaher @int3 @davidberard98 @nmacchioni @embg @peterbell10

**Comment by Lazarus42** [comment]
I think I tracked this down to triton/.venv/lib/python3.11/site-packages/torch/_dynamo/variables/base.py where a call_hasattr function is called but is not implemented. This method belongs to the VariableTracker class which has many unimplemented methods.

Does closing this issue mean implementing the relevant methods?

**Comment by ezyang** [comment]
yes. Also, we should be graph breaking, not incorrectly returning False which is what seems to be happening

**Comment by Nikhil172913832** [comment]
Hey, could you elaborate more on this issue? I’d love to contribute.

**Comment by Lazarus42** [comment]
Sure. The issue seemed to stem from a call to call_hasattr on a TensorVariable object. This class did not have an implementation of call_hasattr hence the error. 

I initially wrote code that checked if the class of the object contained the attribute which works in some cases but doesn't cover the case where the instance has an attribute that doesn't belong to the class. This can occur because pytorch allows dynamically adding attributes to tensors, i.e. if we do my_tensor.foo = 1 then after calling hasattr(my_tensor, "foo") should return True, which would not happen if you just check hasattr(torch.Tensor, "foo").

I think I fixed this with the latest patch but feel free to add stuff in and/or provide commentary.

**Comment by torotoki** [comment]
I think this issue was resolved should be closed?

**Comment by henrylhtsang** [comment]
> I think this issue was resolved should be closed?

This issue doesn't seem resolved?

**Comment by henrylhtsang** [comment]
Refined the repro a bit:
```
import os

os.environ["TORCH_LOGS"] = "+dynamo"
os.environ["TORCHDYNAMO_VERBOSE"] = "1"

import torch

@torch.compile(backend="eager", fullgraph=True)
def fn(x):
    if not hasattr(x, "data_ptr"):
        assert False

fn(torch.randn(3, device="cuda"))
```

Logs:
```
V0911 17:54:36.342889 4059785 torch/_dynamo/convert_frame.py:855] [21/0]   File "/mnt/xarfuse/uid-556211/42e562f7-seed-nspid4026531836_cgpid11447487-ns-4026531841/IPython/core/interactiveshell.py", line 3508, in run_code
V0911 17:54:36.342889 4059785 torch/_dynamo/convert_frame.py:855] [21/0]     exec(code_obj, self.user_global_ns, self.user_ns)
V0911 17:54:36.342889 4059785 torch/_dynamo/convert_frame.py:855] [21/0]   File "/tmp/ipykernel_4059785/425438394.py", line 15, in <module>
V0911 17:54:36.342889 4059785 torch/_dynamo/convert_frame.py:855] [21/0]     fn(torch.randn(3, device="cuda"))
V0911 17:54:36.342889 4059785 torch/_dynamo/convert_frame.py:855] [21/0] 
I0911 17:54:36.346274 4059785 torch/_dynamo/logging.py:57] [21/0] Step 1: torchdynamo start tracing fn /tmp/ipykernel_4059785/425438394.py:9
V0911 17:54:36.346814 4059785 torch/fx/experimental/symbolic_shapes.py:2500] [21/0] create_env
V0911 17:54:36.348746 4059785 torch/_dynamo/symbolic_convert.py:865] [21/0] [__trace_source] TRACE starts_line /tmp/ipykernel_4059785/425438394.py:11 in fn
V0911 17:54:36.348746 4059785 torch/_dynamo/symbolic_convert.py:865] [21/0] [__trace_source]         if not hasattr(x, "data_ptr"):
V0911 17:54:36.349120 4059785 torch/_dynamo/symbolic_convert.py:888] [21/0] [__trace_bytecode] TRACE LOAD_GLOBAL hasattr []
V0911 17:54:36.350234 4059785 torch/_dynamo/symbolic_convert.py:888] [21/0] [__trace_bytecode] TRACE LOAD_FAST x [BuiltinVariable()]
V0911 17:54:36.350766 4059785 torch/_dynamo/symbolic_convert.py:888] [21/0] [__trace_bytecode] TRACE LOAD_CONST data_ptr [BuiltinVariable(), LazyVariableTracker()]
V0911 17:54:36.351422 4059785 torch/_dynamo/symbolic_convert.py:888] [21/0] [__trace_bytecode] TRACE CALL_FUNCTION 2 [BuiltinVariable(), LazyVariableTracker(), ConstantVariable()]
V0911 17:54:36.351930 4059785 torch/_dynamo/output_graph.py:2076] [21/0] create_graph_input L_x_ L['x']
V0911 17:54:36.353569 4059785 torch/_dynamo/variables/builder.py:2661] [21/0] wrap_to_fake L['x'] (3,) StatefulSymbolicContext(dynamic_sizes=[<DimDynamic.STATIC: 2>], dynamic_strides=[<DimDynamic.INFER_STRIDE: 4>], constraint_sizes=[None], constraint_strides=[None], view_base_context=None, tensor_source=LocalSource(local_name='x', cell_or_freevar=False), shape_env_to_source_to_symbol_cache={}) <class 'torch.Tensor'>
V0911 17:54:36.355455 4059785 torch/_dynamo/symbolic_convert.py:888] [21/0] [__trace_bytecode] TRACE POP_JUMP_IF_TRUE 14 [ConstantVariable()]
V0911 17:54:36.355884 4059785 torch/_dynamo/symbolic_convert.py:904] [21/0] empty checkpoint
```

**Comment by Xynonners** [comment]
> EDIT: deleted, my bad

it is resolved?

**Comment by yushangdi** [comment]
@henrylhtsang  Is this issue still open?

I get a different error when running the repro now:

```
Traceback (most recent call last):
  File "/data/users/shangdiy/pytorch/test.py", line 11, in <module>
    fn(torch.randn(3, device='cuda'))
  File "/data/users/shangdiy/pytorch/torch/_dynamo/eval_frame.py", line 659, in _fn
    raise e.with_traceback(None) from None
torch._dynamo.exc.Unsupported: Observed exception
  Explanation: Dynamo found no exception handler at the top-level compiled function when encountering an exception. Exception will propagate outside the compiled region.
  Hint: Dynamo has detected that tracing the code will result in an error when running in eager. Please double check that your code doesn't contain a similar error when actually running eager/uncompiled.
  Hint: It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.

  Developer debug context: raised exception ExceptionVariable(<class 'TypeError'>)


from user code:
   File "/data/users/shangdiy/pytorch/test.py", line 8, in fn
    return tl_reinterpret(x, dtype=tl.float8e4nv)

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
```

but eager runs fine:

```
def fn(x):
    return tl_reinterpret(x, dtype=tl.float8e4nv)


x = torch.randn(3, device='cuda')
fn(x)
```

`fullgraph=False` also runs fine

**Comment by henrylhtsang** [comment]
@yushangdi There is a chance this is irrelevant already.

I think the back story is we tried to trace directly into a triton kernel. So we have dynamo directly handle triton logic, which didn't work too well.

But I think nowadays the preferred solution is to wrap it with `@torch._library.triton_op` (we can't use custom_op if we want to use it in C++). So we won't need to trace inside.

cc @zou3519
