### ISSUE TITLE
Exporting ResNet-50 with dynamic batch dimension results in violated constraints

### ISSUE THREAD

**Issue by JackWolfard** [pytorch/pytorch#133653]
### 🐛 Describe the bug

My expectation is to be able to export ResNet-50 from Torchvision using `torch.export` with a dynamic batch dimension where the first dimension of my example argument can be any value in the dynamic dimension's domain.. However, with my example argument having a batch dimension of 1, I hit an error. If this example argument is any other value between `[2,10]`, then I do not hit an error. The documentation for [Dim](https://pytorch.org/docs/main/export.html#torch.export.dynamic_shapes.Dim) indicates the minimum and maximum values should be inclusive. Additionally when logging details with `TORCH_LOGS="+dynamic"`, `track_symint L['x'].size()[0] 1 StrictMinMaxConstraint(warn_only=False, vr=VR[1, 10])` looks valid.

```python
# example.py
import torch
from torch.export import Dim, export
from torchvision.models import resnet50


def main():
    model = resnet50()
    example_args = (torch.randn(1, 3, 224, 224),)
    batch = Dim("batch", min=1, max=10)
    dynamic_shapes = {
        "x": {0: batch}
    }
    export(model, example_args, dynamic_shapes=dynamic_shapes)


if __name__ == "__main__":
    main()
```

```sh
$ python example.py
V0815 19:38:36.676000 8614645568 torch/fx/experimental/symbolic_shapes.py:2529] [0/0] create_env
I0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3639] [0/0] produce_guards
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].size()[0] 1 StrictMinMaxConstraint(warn_only=False, vr=VR[1, 10])
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].size()[1] 3 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].size()[2] 224 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].size()[3] 224 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].stride()[0] 150528 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].stride()[1] 50176 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].stride()[2] 224 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].stride()[3] 1 None
V0815 19:38:37.051000 8614645568 torch/fx/experimental/symbolic_shapes.py:3821] [0/0] track_symint L['x'].storage_offset() 0 None
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0] Error while creating guard:
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0] Name: ''
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     Source: shape_env
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     Create Function: SHAPE_ENV
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     Guard Types: None
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     Code List: None
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     Object Weakref: None
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     Guarded Class Weakref: None
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0] Traceback (most recent call last):
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_guards.py", line 260, in create
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     return self.create_fn(builder, self)
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/guards.py", line 1717, in SHAPE_ENV
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     guards = output_graph.shape_env.produce_guards(
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4163, in produce_guards
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]     raise ConstraintViolationError(
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0] torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (batch)! For more information, run with TORCH_LOGS="+dynamic".
E0815 19:38:37.052000 8614645568 torch/_guards.py:262] [0/0]   - Not all values of batch = L['x'].size()[0] in the specified range batch <= 10 are valid because batch was inferred to be a constant (1).
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0] Created at:
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 564, in transform
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]     tracer = InstructionTranslator(
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/symbolic_convert.py", line 2360, in __init__
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]     output=OutputGraph(
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 313, in __init__
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]     self.init_ambient_guards()
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]   File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 452, in init_ambient_guards
E0815 19:38:37.053000 8614645568 torch/_guards.py:264] [0/0]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
Traceback (most recent call last):
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/_trace.py", line 512, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1425, in inner
    raise constraint_violation_error
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1379, in inner
    result_traced = opt_f(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
           ^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 726, in compile_inner
    check_fn = CheckFunctionManager(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/guards.py", line 2130, in __init__
    guard.create(builder)
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_guards.py", line 260, in create
    return self.create_fn(builder, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/_dynamo/guards.py", line 1717, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4163, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (batch)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of batch = L['x'].size()[0] in the specified range batch <= 10 are valid because batch was inferred to be a constant (1).

Suggested fixes:
  batch = 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/resnet50.py", line 17, in <module>
    main()
  File "/private/tmp/resnet50.py", line 13, in main
    export(model, example_args, dynamic_shapes=dynamic_shapes)
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/__init__.py", line 174, in export
    return _export(
           ^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/_trace.py", line 945, in wrapper
    raise e
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/_trace.py", line 928, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/exported_program.py", line 89, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/_trace.py", line 1455, in _export
    aten_export_artifact = export_func(
                           ^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/_trace.py", line 1060, in _strict_export
    gm_torch_level = _export_to_torch_ir(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/torch/export/_trace.py", line 529, in _export_to_torch_ir
    raise UserError(UserErrorType.CONSTRAINT_VIOLATION, str(e))  # noqa: B904
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.UserError: Constraints violated (batch)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of batch = L['x'].size()[0] in the specified range batch <= 10 are valid because batch was inferred to be a constant (1).

Suggested fixes:
  batch = 1
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats constrain_symbol_range: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats evaluate_expr: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats _simplify_floor_div: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats _maybe_guard_rel: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats _find: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats has_hint: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats size_hint: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats simplify: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats _update_divisible: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats replace: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats _maybe_evaluate_static: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats get_implications: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats get_axioms: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats safe_expand: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V0815 19:38:37.056000 8614645568 torch/fx/experimental/symbolic_shapes.py:116] lru_cache_stats uninteresting_files: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
```

### Versions

```shell
$ python collect_env.py
Collecting environment information...
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 18.1.8
CMake version: version 3.30.1
Libc version: N/A

Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[conda] Could not collect
```

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @penguinwu

**Comment by pianpwk** [comment]
@JackWolfard Sorry for just getting to this, export does 0/1 specialization which means we'll specialize to dims that are 0/1 in the sample inputs, even if the min/max range provided is different, for example in this case. You'll want to export with a different batch size sample input. Locally I tried batch size = 2 and it manages to export successfully.

**Comment by JackWolfard** [comment]
Thanks. I might've missed the docs which mentioned 0/1 specialization.
