### ISSUE TITLE
cannot run mobilenet_v2_quantized on pytorch/caffe2

### ISSUE THREAD

**Issue by pcub** [pytorch/pytorch#13373]
## ❓ Questions and Help
I am trying to run mobilenet_v2_quantized on pytorch/caffe2 repo which supports int8 .

after compiling pytorch on tx2 and run the model, I meet the following error:

> Original python traceback for operator `-2134827016` in network `mobilenet_v2_quant` in exception above (most recent call last):
> Traceback (most recent call last):
>   File "test_caffe2.py", line 467, in <module>
>     net_def = createNet(pred_net)
>   File "test_caffe2.py", line 406, in createNet
>     workspace.CreateNet(net_def, overwrite=True)
>   File "/home/gg/pytorch/build/caffe2/python/workspace.py", line 154, in CreateNet
>     StringifyProto(net), overwrite,
>   File "/home/gg/pytorch/build/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
>     return func(*args, **kwargs)
> RuntimeError: [enforce fail at operator.cc:46] blob != nullptr. op NCHW2NHWC: Encountered a non-existing input blob: data
> frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x7c (0x7f48beaed4 in /home/gg/pytorch/build/lib/libc10.so)
> frame #1: caffe2::OperatorBase::OperatorBase(caffe2::OperatorDef const&, caffe2::Workspace*) + 0x560 (0x7f5a508a18 in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #2: <unknown function> + 0x13e5efc (0x7f5a931efc in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #3: std::_Function_handler<std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (caffe2::OperatorDef const&, caffe2::Workspace*), std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (*)(caffe2::OperatorDef const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, caffe2::OperatorDef const&, caffe2::Workspace*&&) + 0x34 (0x7f5b40f4d4 in /home/gg/pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-aarch64-linux-gnu.so)
> frame #4: <unknown function> + 0xfbacfc (0x7f5a506cfc in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #5: <unknown function> + 0xfbcd0c (0x7f5a508d0c in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #6: caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int) + 0x430 (0x7f5a509898 in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #7: caffe2::SimpleNet::SimpleNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x3dc (0x7f5a56916c in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #8: <unknown function> + 0x101eb3c (0x7f5a56ab3c in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #9: <unknown function> + 0xfa5904 (0x7f5a4f1904 in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #10: caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x90c (0x7f5a541f94 in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #11: caffe2::Workspace::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, bool) + 0x1e4 (0x7f5a554824 in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #12: caffe2::Workspace::CreateNet(caffe2::NetDef const&, bool) + 0xa4 (0x7f5a555a7c in /home/gg/pytorch/build/lib/libcaffe2.so)
> frame #13: <unknown function> + 0x59798 (0x7f5b406798 in /home/gg/pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-aarch64-linux-gnu.so)
> frame #14: <unknown function> + 0x59a08 (0x7f5b406a08 in /home/gg/pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-aarch64-linux-gnu.so)
> frame #15: <unknown function> + 0x99534 (0x7f5b446534 in /home/gg/pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-aarch64-linux-gnu.so)
> <omitting python frames>

what is the problem?

**Comment by jjoss** [comment]
try download the model via
 python -m caffe2.python.models.download -i mobilenet_v2

**Comment by pcub** [comment]
solved by https://github.com/caffe2/caffe2/issues/372#issuecomment-329720954
