### ISSUE TITLE
[dynamo] missing opcode `LOAD_BUILD_CLASS`

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#133806]
### 🐛 Describe the bug

Missing opcode [LOAD_BUILD_CLASS](https://docs.python.org/3/library/dis.html#opcode-LOAD_BUILD_CLASS).

Required by PR: #133805

- #133805

```python
# Copied from functools.py in the standard library
@substitute_in_graph(functools.cmp_to_key)
def cmp_to_key(mycmp):
    class K:  # <--- RAISED HERE
        __slots__ = ("obj",)

        def __init__(self, obj):
            self.obj = obj

        def __lt__(self, other):
            return mycmp(self.obj, other.obj) < 0

        def __gt__(self, other):
            return mycmp(self.obj, other.obj) > 0

        def __eq__(self, other):
            return mycmp(self.obj, other.obj) == 0

        def __le__(self, other):
            return mycmp(self.obj, other.obj) <= 0

        def __ge__(self, other):
            return mycmp(self.obj, other.obj) >= 0

        __hash__ = None

    return K
```

### Error logs

```console
$ python3 test/dynamo/test_functions.py -k cmp_to_key
Einductor []
inline_call [('missing: LOAD_BUILD_CLASS', 1)]

======================================================================
ERROR: test_functools_cmp_to_key (__main__.FunctionTests.test_functools_cmp_to_key)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/testing/_internal/common_utils.py", line 2918, in wrapper
    method(*args, **kwargs)
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/test/dynamo/test_functions.py", line 79, in test_fn
    return torch._dynamo.testing.standard_test(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/testing.py", line 251, in standard_test
    val1a = opt_fn(*args1)
            ^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/eval_frame.py", line 469, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 1238, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 514, in __call__
    return _compile(
           ^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 902, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 653, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 686, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 208, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/convert_frame.py", line 622, in transform
    tracer.run()
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 2731, in run
    super().run()
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 958, in run
    while self.step():
          ^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 870, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 558, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 2242, in CALL
    self._call(inst)
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 2236, in _call
    self.call_function(fn, args, kwargs)
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 805, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/variables/functions.py", line 966, in call_function
    return SourcelessBuilder.create(tx, handler).call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 811, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 2946, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 3062, in inline_call_
    tracer.run()
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 958, in run
    while self.step():
          ^^^^^^^^^^^
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 870, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/symbolic_convert.py", line 692, in _missing
    unimplemented(f"missing: {opname}")
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/exc.py", line 289, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: missing: LOAD_BUILD_CLASS

from user code:
   File "/mnt/moonfs/users/panxuehai/Projects/pytorch/test/dynamo/test_functions.py", line 167, in test_functools_cmp_to_key
    key=functools.cmp_to_key(lambda x, y: (x.mean() - y.mean()).item()),
  File "/mnt/moonfs/users/panxuehai/Projects/pytorch/torch/_dynamo/polyfills/functools.py", line 49, in cmp_to_key
    class K:

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


To execute this test, run the following from the base repo dir:
    python test/dynamo/test_functions.py FunctionTests.test_functools_cmp_to_key

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 0.080s

FAILED (errors=1)
```

### Minified repro

```bash
ghstack checkout https://github.com/pytorch/pytorch/pull/133805
python3 test/dynamo/test_functions.py -k cmp_to_key
```

### Versions

nightly

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by jerrychenhf** [comment]
Possible the same issue as https://github.com/pytorch/pytorch/issues/128942

**Comment by XuehaiPan** [comment]
Dup of #128942

- #128942

Move the discussion there.
