### ISSUE TITLE
_jit_differentiate can not process aten::cat

### ISSUE THREAD

**Issue by ozzzp** [pytorch/pytorch#13390]
## code:

```python
import torch

def main():
    def fun(x, y):
        return torch.cat([x, y], dim=0)

    fun = torch.jit.trace(fun, (torch.ones([4, 4], requires_grad=True),
                                torch.zeros([4, 4], requires_grad=True)))
    out = torch._C._jit_differentiate(fun.graph)
    return out


if __name__ == '__main__':
    main()
```
## output:
```python
Traceback (most recent call last):
  File "playground.py", line 14, in <module>
    main()
  File "playground.py", line 9, in main
    out = torch._C._jit_differentiate(fun.graph)
RuntimeError: differentiation of aten::cat is not supported, or it is missing necessary type information
```

## Environment
```bash
Collecting environment information...
PyTorch version: 1.0.0.dev20181029
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.3)
[pip] pytorchviz (0.0.1)
[pip] torch (1.0.0.dev20181029)
[pip] torchvision (0.2.1)
[conda] pytorch-nightly           1.0.0.dev20181029         py3.6_0    
[conda] pytorchviz                0.0.1                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

It can be located in `pytorch/torch/csrc/jit/autodiff.cpp` line 357-361
```C++
if (!isDifferentiable(node)) {
    throw std::runtime_error(std::string("differentiation of ") + node->kind().toDisplayString() + " "
                             "is not supported, or it is missing necessary type information");
  }
  auto sym_grads = build_sym_grad(fmap<SymbolicVariable>(grad_values));
``` 
but curiously, from my perspective, it seems that it has the ability to process `"aten::cat(Tensor[] tensors, int dim) -> Tensor"` but simply blocked by `isDifferentiable`.

Any Idea?

**Comment by zou3519** [comment]
I think the reason why we didn't implement this in autodiff is because aten::cat is also used for list concatenation and we have not made that differentiable yet

**Comment by ozzzp** [comment]
Thanks for response, @zou3519. But if `isDifferentiable` blocked cause fo no implement, then the code in line 325-340 
```C++
} else if (node->matches("aten::cat(Tensor[] tensors, int dim) -> Tensor", /*const_inputs=*/attr::dim)) {
...
```
will never run and seems it is exactly the difference of `aten::cat`.

For now I can not sure wether it could work (In re-compiling), or you can just tell me line 325-340 are still in building so that I can save the time. 😉

**Comment by zou3519** [comment]
Yes, that line doesn't do anything right now because we've turned off autodiff support for cat.

**Comment by zdevito** [comment]
The autodiff for jit works in a different way now, so torch._C._jit_differentiate is obsolete. Please reopen if there is still an issue here.

**Comment by mzmssg** [comment]
@zdevito 
Is there some doc about the new way
