### ISSUE TITLE
Nighties now need a newer typing-extension version than in requirements.txt

### ISSUE THREAD

**Issue by Vargol** [pytorch/pytorch#134097]
### 🐛 Describe the bug

I tried to run a diffusers script using the latest PyTorch nightly.
The script failed to to the version of typing-extensions, the version I had installed was 4.8.0
the requirements.txt file for torch has 
```
typing-extensions>=4.8.0
```
which indicates it should work, updated to latest typing-extensions and the script worked. The requirements.txt file need updating to reflect a newer version is needed.

```
(Diffusers) M3iMac:Diffusers $ python flux.py 
Traceback (most recent call last):
  File "/Volumes/SSD2TB/AI/Diffusers/flux.py", line 1, in <module>
    import torch
  File "/Volumes/SSD2TB/AI/Diffusers/lib/python3.10/site-packages/torch/__init__.py", line 37, in <module>
    from typing_extensions import ParamSpec as _ParamSpec, TypeIs as _TypeIs
ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/Volumes/SSD2TB/AI/Diffusers/lib/python3.10/site-packages/typing_extensions.py)


(Diffusers) M3iMac:Diffusers $ pip install typing-extensions
Requirement already satisfied: typing-extensions in ./lib/python3.10/site-packages (4.8.0)


(Diffusers) M3iMac:Diffusers $ pip install -U typing-extensions
Requirement already satisfied: typing-extensions in ./lib/python3.10/site-packages (4.8.0)
Collecting typing-extensions
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.8.0
    Uninstalling typing_extensions-4.8.0:
      Successfully uninstalled typing_extensions-4.8.0
Successfully installed typing-extensions-4.12.2


(Diffusers) M3iMac:Diffusers $ python flux.py 
/Volumes/SSD2TB/AI/Diffusers/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. 
  ...
```

### Versions

```
Collecting environment information...
PyTorch version: 2.5.0.dev20240820
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.24.4
Libc version: N/A

Python version: 3.10.13 (main, Nov  9 2023, 13:59:31) [Clang 15.0.0 (clang-1500.0.40.1)] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] torch==2.5.0.dev20240820
[pip3] torchaudio==2.4.0.dev20240820
[pip3] torchvision==0.20.0.dev20240820
[conda] Could not collect
```

**Comment by Skylion007** [comment]
Fixed in #133814
