### ISSUE TITLE
Unexpected behavior (times out) of all_gather_into_tensor with subgroups

### ISSUE THREAD

**Issue by edouardoyallon** [pytorch/pytorch#134006]
### 🐛 Describe the bug

I'm currently developing a script that uses subgroups of torch.distributed and the procedure all_gather_into_tensor. Unfortunately, for some reasons and on different clusters, one of the worker - often the master - times out. All the ports are open and I introduced a parameter **n** which quantifies the number of groups I'm subdividing my workers with (here, 8 workers for simplicity, see the slurm script). I think I'm observing some inconsistent results, which suggest a bug

### Issue Summary:

**Problem:** Unexpected behavior of all_gather_into_tensor when running distributed PyTorch training using SLURM with NCCL backend.

**Environment:**
- **Python Script, minimalbug.py**
```python
import torch.distributed as dist
from datetime import timedelta
import os
import time
import torch 

# Enviromnent variables
rank = int(os.environ["RANK"])
world_size = int(os.environ["WORLD_SIZE"])
local_rank = int(os.environ["LOCAL_RANK"])

dist.init_process_group(backend='nccl', timeout=timedelta(seconds=10))

n=4 #Try: 1, 2, 4, 8

# Create subgroups
ranks_subgroups = [[r for r in range(world_size) if r%n==rank%n] for rank in range(n)]
if rank==0:
    print(ranks_subgroups)

group_DDP_torch, subgroups  = dist.new_subgroups_by_enumeration(ranks_subgroups)
device = f'cuda:{local_rank}'

print('Worker '+str(rank)+' enters here.')
input_slice = torch.zeros(1).cuda(device)
output = torch.zeros(world_size//n).cuda(device)

dist.barrier(group=group_DDP_torch)
dist.all_gather_into_tensor(output, input_slice, group=group_DDP_torch)
print('Worker '+str(rank)+' was able to gather.')
dist.barrier(group=group_DDP_torch)

dist.destroy_process_group()
```
- **SLURM Batch Script:**
```bash
#!/usr/bin/bash -l
#SBATCH --partition=gpu
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:4
#SBATCH --constraint 'a100 with infiniband'
#SBATCH --time 00:10:00

export HOSTNAMES=`scontrol show hostnames "$SLURM_JOB_NODELIST"`
export MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_PORT=50001
export COUNT_NODE=`scontrol show hostnames "$SLURM_JOB_NODELIST" | wc -l`

#export TORCH_DISTRIBUTED_DEBUG=INFO
#export NCCL_DEBUG=INFO
#export TORCH_NCCL_BLOCKING_WAIT=1
#export CUDA_LAUNCH_BLOCKING=1
#export TORCH_USE_CUDA_DSA=1

echo $COUNT_NODE
srun torchrun  --nnodes=$COUNT_NODE --nproc_per_node=4 --rdzv_backend=c10d \
   --master_port $MASTER_PORT --rdzv_id=$SLURM_JOB_ID --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
      miminalbug.py
```

Then, n=4 leads to:

```bash
W0820 11:37:09.500566 140737353983488 torch/distributed/run.py:779] 
W0820 11:37:09.500566 140737353983488 torch/distributed/run.py:779] *****************************************
W0820 11:37:09.500566 140737353983488 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0820 11:37:09.500566 140737353983488 torch/distributed/run.py:779] *****************************************
W0820 11:37:09.536371 140737353983488 torch/distributed/run.py:779] 
W0820 11:37:09.536371 140737353983488 torch/distributed/run.py:779] *****************************************
W0820 11:37:09.536371 140737353983488 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0820 11:37:09.536371 140737353983488 torch/distributed/run.py:779] *****************************************
Worker 6 enters here.
Worker 7 enters here.
Worker 4 enters here.
Worker 3 enters here.
Worker 5 enters here.
[[0, 4], [1, 5], [2, 6], [3, 7]]
Worker 0 enters here.
Worker 1 enters here.
Worker 2 enters here.
Worker 0 was able to gather.
Worker 5 was able to gather.
Worker 6 was able to gather.
Worker 7 was able to gather.
Worker 3 was able to gather.
Worker 2 was able to gather.
[rank4]:[W820 11:37:34.810863480 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 2 - No such file or directory).
[rank4]: Traceback (most recent call last):
[rank4]:   File "/mnt/home/miminalbug.py", line 28, in <module>
[rank4]:     dist.all_gather_into_tensor(output, input_slice, group=group_DDP_torch)
[rank4]:   File "/mnt/home/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/mnt/home/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3200, in all_gather_into_tensor
[rank4]:     work = group._allgather_base(output_tensor, input_tensor, opts)
[rank4]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '1', but store->get('1') got error: Socket Timeout
[rank4]: Exception raised from doWait at /opt/conda/conda-bld/pytorch_1720538616722/work/torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):
[rank4]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fff9e05df86 in /mnt/home/lib/python3.9/site-packages/torch/lib/libc10.so)
[rank4]: frame #1: <unknown function> + 0x12e6fab (0x7fffe1b04fab in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7fffe61b55a2 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7fffe61b6791 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fffe616b1e1 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fffe616b1e1 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fffe616b1e1 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fffe616b1e1 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7fff9f3400df in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
[rank4]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7fff9f34bebc in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
[rank4]: frame #10: c10d::ProcessGroupNCCL::_allgather_base(at::Tensor&, at::Tensor&, c10d::AllgatherOptions const&) + 0x6e5 (0x7fff9f36fcd5 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
[rank4]: frame #11: <unknown function> + 0x593ffd8 (0x7fffe615dfd8 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #12: <unknown function> + 0x5949bec (0x7fffe6167bec in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #13: <unknown function> + 0x4f6c42b (0x7fffe578a42b in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #14: <unknown function> + 0x4f69ca4 (0x7fffe5787ca4 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #15: <unknown function> + 0x176bcd8 (0x7fffe1f89cd8 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #16: <unknown function> + 0x595133e (0x7fffe616f33e in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #17: <unknown function> + 0x595d6f8 (0x7fffe617b6f8 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
[rank4]: frame #18: <unknown function> + 0xdb195e (0x7fffee84895e in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
[rank4]: frame #19: <unknown function> + 0x4b146f (0x7fffedf4846f in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
[rank4]: frame #20: /mnt/home/bin/python() [0x507397]
[rank4]: frame #21: _PyObject_MakeTpCall + 0x2ec (0x4f065c in /mnt/home/bin/python)
[rank4]: frame #22: /mnt/home/bin/python() [0x5052b0]
[rank4]: frame #23: _PyEval_EvalFrameDefault + 0x4cef (0x4ec5cf in /mnt/home/bin/python)
[rank4]: frame #24: /mnt/home/bin/python() [0x4e69da]
[rank4]: frame #25: _PyFunction_Vectorcall + 0xd4 (0x4f7de4 in /mnt/home/bin/python)
[rank4]: frame #26: PyObject_Call + 0xb4 (0x5057e4 in /mnt/home/bin/python)
[rank4]: frame #27: _PyEval_EvalFrameDefault + 0x4172 (0x4eba52 in /mnt/home/bin/python)
[rank4]: frame #28: /mnt/home/bin/python() [0x4e69da]
[rank4]: frame #29: _PyFunction_Vectorcall + 0xd4 (0x4f7de4 in /mnt/home/bin/python)
[rank4]: frame #30: _PyEval_EvalFrameDefault + 0x1235 (0x4e8b15 in /mnt/home/bin/python)
[rank4]: frame #31: /mnt/home/bin/python() [0x4e69da]
[rank4]: frame #32: _PyEval_EvalCodeWithName + 0x47 (0x4e6667 in /mnt/home/bin/python)
[rank4]: frame #33: PyEval_EvalCodeEx + 0x39 (0x4e6619 in /mnt/home/bin/python)
[rank4]: frame #34: PyEval_EvalCode + 0x1b (0x5938eb in /mnt/home/bin/python)
[rank4]: frame #35: /mnt/home/bin/python() [0x5c1157]
[rank4]: frame #36: /mnt/home/bin/python() [0x5bd170]
[rank4]: frame #37: /mnt/home/bin/python() [0x456423]
[rank4]: frame #38: PyRun_SimpleFileExFlags + 0x1a2 (0x5b6e52 in /mnt/home/bin/python)
[rank4]: frame #39: Py_RunMain + 0x37e (0x5b43ce in /mnt/home/bin/python)
[rank4]: frame #40: Py_BytesMain + 0x39 (0x587999 in /mnt/home/bin/python)
[rank4]: frame #41: __libc_start_main + 0xe5 (0x7ffff70877e5 in /lib64/libc.so.6)
[rank4]: frame #42: /mnt/home/bin/python() [0x58784e]
[rank4]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank4]:[W820 11:37:34.922821366 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0820 11:37:36.306975 140737353983488 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 793062) of binary: /mnt/home/bin/python
Traceback (most recent call last):
  File "/mnt/home/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.0', 'console_scripts', 'torchrun')())
  File "/mnt/home/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/mnt/home/lib/python3.9/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/mnt/home/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/mnt/home/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/home/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
miminalbug.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-20_11:37:36
  host      : workergpu008.cm.cluster
  rank      : 4 (local_rank: 0)
  exitcode  : 1 (pid: 793062)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: workergpu008: task 1: Exited with exit code 1
[rank0]:[E820 11:47:24.069865760 ProcessGroupNCCL.cpp:607] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=_ALLGATHER_BASE, NumelIn=1, NumelOut=2, Timeout(ms)=600000) ran for 600001 milliseconds before timing out.
[rank0]:[E820 11:47:24.070046070 ProcessGroupNCCL.cpp:1664] [PG 1 Rank 0] Exception (either an error or timeout) detected by watchdog at work: 2, last enqueued NCCL work: 3, last completed NCCL work: 1.
[rank1]:[E820 11:47:24.169946254 ProcessGroupNCCL.cpp:607] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600057 milliseconds before timing out.
[rank1]:[E820 11:47:24.170143100 ProcessGroupNCCL.cpp:1664] [PG 2 Rank 0] Exception (either an error or timeout) detected by watchdog at work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
[rank1]:[E820 11:47:25.664335426 ProcessGroupNCCL.cpp:1709] [PG 2 Rank 0] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
[rank1]:[E820 11:47:25.664482151 ProcessGroupNCCL.cpp:621] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E820 11:47:25.664511544 ProcessGroupNCCL.cpp:627] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E820 11:47:25.665769911 ProcessGroupNCCL.cpp:1515] [PG 2 Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600057 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1720538616722/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fff9e05df86 in /mnt/home/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7fff9f3410b2 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7fff9f347af3 in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7fff9f349edc in /mnt/home/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7fffeee67bf4 in /mnt/home/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x81ca (0x7ffff7bb51ca in /lib64/libpthread.so.0)
frame #6: clone + 0x43 (0x7ffff70868d3 in /lib64/libc.so.6)

W0820 11:47:26.246769 140737353983488 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 959249 closing signal SIGTERM
slurmstepd: error: *** JOB 3729272 ON workergpu007 CANCELLED AT 2024-08-20T11:47:26 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 3729272.0 ON workergpu007 CANCELLED AT 2024-08-20T11:47:26 DUE TO TIME LIMIT ***
W0820 11:47:26.674544 140737353983488 torch/distributed/elastic/agent/server/api.py:688] Received Signals.SIGTERM death signal, shutting down workers
W0820 11:47:26.674945 140737353983488 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 959249 closing signal SIGTERM
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
W0820 11:47:26.675554 140737353983488 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 959249 closing signal SIGTERM
```

while n=1 works like a charm and has a the expected behavior:
``` bash
W0820 11:35:10.150496 140737353983488 torch/distributed/run.py:779] 
W0820 11:35:10.150496 140737353983488 torch/distributed/run.py:779] *****************************************
W0820 11:35:10.150496 140737353983488 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0820 11:35:10.150496 140737353983488 torch/distributed/run.py:779] *****************************************
W0820 11:35:10.158800 140737353983488 torch/distributed/run.py:779] 
W0820 11:35:10.158800 140737353983488 torch/distributed/run.py:779] *****************************************
W0820 11:35:10.158800 140737353983488 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0820 11:35:10.158800 140737353983488 torch/distributed/run.py:779] *****************************************
Worker 6 enters here.
Worker 5 enters here.
Worker 7 enters here.
Worker 1 enters here.
Worker 3 enters here.
Worker 2 enters here.
[[0, 1, 2, 3, 4, 5, 6, 7]]
Worker 0 enters here.
Worker 4 enters here.
Worker 6 was able to gather.
Worker 3 was able to gather.
Worker 5 was able to gather.
Worker 1 was able to gather.
Worker 7 was able to gather.
Worker 2 was able to gather.
Worker 4 was able to gather.
Worker 0 was able to gather.
```

I'd be happy to incorporate more details and any help is more than welcome.

### Versions

- **Version: (doesn't really make sens as I'm on a cluster)**
```bash
Collecting environment information...
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.10 (Green Obsidian) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.28

Python version: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-553.8.1.el8_10.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A6000
Nvidia driver version: 550.107.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True


Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.8.0               h6a678d5_0  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] magma                     2.7.1                h2c23e93_0  
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.8            py39h5eee18b_0  
[conda] mkl_random                1.2.4            py39hdb19cb5_0  
[conda] numpy                     1.26.4           py39h5f9d8c6_0  
[conda] numpy-base                1.26.4           py39hb5e798b_0  
[conda] pytorch                   2.4.0           py3.9_cuda12.4_cudnn9.1.0_0    pytorch
[conda] pytorch-cuda              12.4                 hc786d27_6    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.4.0                py39_cu124    pytorch
[conda] torchtriton               3.0.0                      py39    pytorch
[conda] torchvision               0.19.0               py39_cu124    pytorch
```

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by yifuwang** [comment]
Ah this is nasty. My guess is that this is caused by the wonky device guessing logic of `ProcessGroupNCCL::barrier()`. `ProcessGroupNCCL` collectives rely on input tensors to determine the rank's device. However, since `barrier()` doesn't take input tensors, `ProcessGroupNCCL::barrier()` guesses the device for the rank. It typically works for the global process group but is likely incorrect for subgroups.

We need to fix the issue. In the meanwhile, you can workaround it by replacing the first ever barrier issued by a subgroup with a single-element all-reduce.

```python
import torch.distributed as dist
from datetime import timedelta
import os
import time
import torch

# Enviromnent variables
rank = int(os.environ["RANK"])
world_size = int(os.environ["WORLD_SIZE"])
local_rank = int(os.environ["LOCAL_RANK"])

dist.init_process_group(backend='nccl', timeout=timedelta(seconds=10))

n=4 #Try: 1, 2, 4, 8

# Create subgroups
ranks_subgroups = [[r for r in range(world_size) if r%n==rank%n] for rank in range(n)]
if rank==0:
    print(ranks_subgroups)

group_DDP_torch, subgroups  = dist.new_subgroups_by_enumeration(ranks_subgroups)
device = f'cuda:{local_rank}'
torch.cuda.set_device(device)

print('Worker '+str(rank)+' enters here.')
input_slice = torch.zeros(1).cuda(device)
output = torch.zeros(world_size//n).cuda(device)

# Replace the first ever barrier with a single-element all-reduce.
# This is basically what ProcessGroupNCCL::barrier() does but without the guessing.
barrier_tensor = torch.zeros(1).cuda(device)
dist.all_reduce(barrier_tensor, group=group_DDP_torch)

dist.all_gather_into_tensor(output, input_slice, group=group_DDP_torch)
torch.cuda.synchronize()
print('Worker '+str(rank)+' was able to gather.')

# Subsequent barrier should work
dist.barrier(group=group_DDP_torch)

dist.destroy_process_group()
```

**Comment by yifuwang** [comment]
cc: @wconstab in case you've seen this or are aware of any previous discussions.

**Comment by edouardoyallon** [comment]
Thanks a lot @yifuwang, I really appreciate your help! Unfortunately, the fix you propose doesn't work.. there are still 2 workers hanging. I've the impression the issue might be related to all_gather_into_tensor, not the barrier, but I could be wrong. Thanks in advance for any further insights..

**Comment by zhenyuhe00** [comment]
Same issue.

**Comment by edouardoyallon** [comment]
After some further examinations, it's indeed working correctly: I was missing the torch.cuda.synchronize()
Thanks much!
