### ISSUE TITLE
[XPU] Can't install Triton with `python build_triton_wheel.py --device xpu`

### ISSUE THREAD

**Issue by Stonepia** [pytorch/pytorch#134199]
### 🐛 Describe the bug

# Issue Message

```Bash
$python build_triton_wheel.py --device xpu 

HEAD is now at c451d567 Update bfloat16 conversion property (#1945)
Traceback (most recent call last):
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 219, in <module>
    main()
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 206, in main
    build_triton(
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 108, in build_triton
    patch_setup_py(triton_pythondir / "setup.py")
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 57, in patch_setup_py
    orig = check_and_replace(
           ^^^^^^^^^^^^^^^^^^
  File "/pytorch/.github/scripts/build_triton_wheel.py", line 34, in check_and_replace
    raise RuntimeError(f"Can't find ${src} in the input")
RuntimeError: Can't find $https://tritonlang.blob.core.windows.net/llvm-builds/ in the input
```

# Root Cause

The PR #133694 does a workaround to replace the str `"https://tritonlang.blob.core.windows.net/llvm-builds/"` with  `"https://oaitriton.blob.core.windows.net/public/llvm-builds/"` in `triton/python/setup.py`.

Thus, the URL in the below code will be replaced to newer `oaitriton.blob.core` one.
```Python
# triton-lang/triton/python/setup.py
# Commit : dedb7bdf339a3546896d4820366ca562c586bfa0

    name = f"llvm-{rev}-{system_suffix}"
    url = f"https://tritonlang.blob.core.windows.net/llvm-builds/{name}.tar.gz"  # This will be replaced
    return Package("llvm", name, url, "LLVM_INCLUDE_DIRS", "LLVM_LIBRARY_DIR", "LLVM_SYSPATH")
```

For the default `triton-lang/triton`, because the pinned commit is not the newest, it has the above code, and could be replaced. 

However, for xpu, the link has already be changed to `https://oaitriton.blob.core.windows.net/public/llvm-builds/` in [setup.py](https://github.com/intel/intel-xpu-backend-for-triton/blob/c451d56744e72e9659f07b1acd9286087bd58078/python/setup.py#L205). Thus, it would complain about the above error.

# Affected files

## 1.  `.github/scripts/build_triton_wheel.py`
This file has the `patch_setup_py`, which would cause this error. See detail in #133694 

## 2. `.ci/docker/common/install_triton.sh`
This file explicitly change does the str replacement. See detail in #133878 at [line 56](https://github.com/pytorch/pytorch/pull/133878/files#diff-43af2599ef1e1e8753ec618dd805e28c0d7443cb5ff924c3fbddd93fad78c4d5R56)

# Env
### Versions

PyTorch version: 2.5.0a0+git25d5a81
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-118-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert_pytorch==0.0.1a4
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] onnx==1.16.1
[pip3] optree==0.12.1
[pip3] pytorch-triton-xpu==3.0.0+1b2f15840e
[pip3] torch==2.5.0a0+git25d5a81
[pip3] torch_geometric==2.4.0
[pip3] torchaudio==2.4.0a0+69b2a0a
[pip3] torchbench==0.1
[pip3] torchdata==0.7.0a0+11bb5b8
[pip3] torchmetrics==1.0.3
[pip3] torchrec==0.7.0
[pip3] torchtext==0.16.0a0+b0ebddc
[pip3] torchvision==0.18.0a0+6043bc2
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] mkl-include               2024.2.0              intel_663    intel
[conda] mkl-static                2024.2.0              intel_663    intel
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] pytorch-triton-xpu        3.0.0+1b2f15840e          pypi_0    pypi
[conda] torch                     2.5.0a0+gite8fc1e0          pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchaudio                2.4.0a0+69b2a0a          pypi_0    pypi
[conda] torchbench                0.1                       dev_0    <develop>
[conda] torchdata                 0.7.0a0+11bb5b8          pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchmetrics              1.0.3                    pypi_0    pypi
[conda] torchrec                  0.7.0                    pypi_0    pypi
[conda] torchtext                 0.16.0a0+b0ebddc          pypi_0    pypi
[conda] torchvision               0.18.0a0+6043bc2          pypi_0    pypi

**Comment by Stonepia** [comment]
@chuanqi129 FYI
