### ISSUE TITLE
[c10d][MPI] Attempting to create a new group after MPI causes "RuntimeError: Underlying Non-PrefixStore shouldn't be null"

### ISSUE THREAD

**Issue by Aidyn-A** [pytorch/pytorch#134700]
### 🐛 Describe the bug

```python
import torch

torch.distributed.init_process_group(backend="mpi")
nccl_group = torch.distributed.new_group(backend="nccl")
```

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/pytorch/pytorch/repro.py", line 4, in <module>
[rank0]:     nccl_group = torch.distributed.new_group(backend="nccl")
[rank0]:   File "/opt/pytorch/pytorch/torch/distributed/c10d_logger.py", line 97, in wrapper
[rank0]:     func_return = func(*args, **kwargs)
[rank0]:   File "/opt/pytorch/pytorch/torch/distributed/distributed_c10d.py", line 4577, in new_group
[rank0]:     return _new_group_with_tag(
[rank0]:   File "/opt/pytorch/pytorch/torch/distributed/distributed_c10d.py", line 4660, in _new_group_with_tag
[rank0]:     pg, pg_store = _new_process_group_helper(
[rank0]:   File "/opt/pytorch/pytorch/torch/distributed/distributed_c10d.py", line 1783, in _new_process_group_helper
[rank0]:     backend_class = ProcessGroupNCCL(
[rank0]: RuntimeError: Underlying Non-PrefixStore shouldn't be null.
```

### Versions

main

**Comment by tianyu-l** [comment]
@wconstab @kwen2501 @H-Huang

**Comment by H-Huang** [comment]
Is the use case here you want to use MPI for cpu and NCCL for cuda? Does the following work as a workaround?

```python
torch.distributed.init_process_group(backend="cpu:mpi,cuda:nccl")
nccl_group = torch.distributed.new_group(backend="nccl")
```

**Comment by Aidyn-A** [comment]
> Is the use case here you want to use MPI for cpu and NCCL for cuda? Does the following work as a workaround?
> 
> ```python
> torch.distributed.init_process_group(backend="cpu:mpi,cuda:nccl")
> nccl_group = torch.distributed.new_group(backend="nccl")
> ```

This will not work in the case of hybrid network, where NCCL cannot cover all the ranks. The workaround for such network would be having MPI as a global process group over Ethernet and NCCL for sub-network interconnected via IB:
```Python
torch.distributed.init_process_group(backend="mpi")
world_size = torch.distributed.get_world_size()
g0 = torch.distributed.new_group(backend="nccl", list(range(0, world_size // 2))) 
g1 = torch.distributed.new_group(backend="nccl", list(range(world_size // 2, world_size)))
```

**Comment by kwen2501** [comment]
The error seems to occur when trying to fetch a global store to coordinate dumps.
https://github.com/pytorch/pytorch/blob/951c21d6790334d57862e94a3f582ac724147a53/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L851-L857

cc: @fduwjj @c-p-i-o

**Comment by Aidyn-A** [comment]
> The error seems to occur when trying to fetch a global store to coordinate dumps.
> 
> https://github.com/pytorch/pytorch/blob/951c21d6790334d57862e94a3f582ac724147a53/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L851-L857
> 
> cc: @fduwjj @c-p-i-o

Correct, because the `underlying_store` was never set, nor it was ever created. In the PR #134710 I am creating a new store if it is required.
