### ISSUE TITLE
[Dynamo] propagate required_grad info while applying autograd function

### ISSUE THREAD

**Issue by xinyu-intel** [pytorch/pytorch#134820]
### 🐛 Describe the bug

Hi, we found the required_grad function won't be propagated while applying autograd function. Is it expected?

### Error logs

```
Traceback (most recent call last):
  File "/home/xichen/workspace/benchmark/python/ds_exp_grad.py", line 20, in <module>
    compile_repro(input)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2451, in run
    super().run()
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/misc.py", line 680, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/misc.py", line 484, in call_method
    return self.call_apply(tx, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/misc.py", line 409, in call_apply
    ).call_function(tx, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 1705, in call_function
    (fwd_out, _), fwd_graph, fwd_freevars = speculate_subgraph(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 420, in speculate_subgraph
    output = f.call_function(tx, args, sub_kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1512, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 758, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1713, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1798, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1853, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1785, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1300, in wrap_fake_exception
    return fn()
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1786, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1921, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/home/xichen/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1903, in run_node
    return node.target(*args, **kwargs)
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method exp of type object at 0x7f32ea695d20>(*(FakeTensor(..., size=(128, 1), requires_grad=True),), **{'out': FakeTensor(..., size=(128, 1), requires_grad=True)}):
exp(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.

from user code:
   File "/home/xichen/workspace/benchmark/python/ds_exp_grad.py", line 15, in compile_repro
    l = toy_fn.apply(inputs)
  File "/home/xichen/workspace/benchmark/python/ds_exp_grad.py", line 6, in forward
    torch.exp(inputs, out=inputs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
```

### Minified repro

```python
import torch 

class toy_fn(torch.autograd.Function):
  @staticmethod
  def forward(ctx,inputs):
    torch.exp(inputs, out=inputs)
    return inputs

  @staticmethod
  def backward(ctx, grad_output):
    return None, None

@torch.compile(fullgraph=True)
def compile_repro(inputs):
    l = toy_fn.apply(inputs)
    return l

input = torch.randn(128,1, requires_grad=True)

compile_repro(input)

```

### Versions

```
PyTorch version: 2.5.0.dev20240729
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.0
Libc version: N/A

Python version: 3.8.18 (default, Sep 11 2023, 08:17:16)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] onnx==1.16.1
[pip3] onnx2torch==1.5.14
[pip3] optree==0.11.0
[pip3] pytorch-lightning==1.7.7
[pip3] torch==2.5.0a0+git1f961ad
[pip3] torchaudio==2.4.0.dev20240729
[pip3] torchmetrics==0.10.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] numpy-base                1.24.3           py38h90707a3_0
[conda] onnx2torch                1.5.14                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] torch                     1.12.0.dev20220518          pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240729          pypi_0    pypi
[conda] torchmetrics              0.10.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
```

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by xinyu-intel** [comment]
@zou3519 Hi, may I have your inputs?

**Comment by zou3519** [comment]
cc @yanboliang 

The problem is probably that speculate_subgraph isn't speculating the forward under no_grad

**Comment by xinyu-intel** [comment]
@zou3519 Thank you for the quick fix:)
