### ISSUE TITLE
register_after_fork fails on python built without multiprocessing support

### ISSUE THREAD

**Issue by djphoenix** [pytorch/pytorch#134926]
### 🐛 Describe the bug

An embeddable python without multiprocessing support (built without fork/exec symbols) cannot import torch:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../torch/__init__.py", line 1862, in <module>
    register_after_fork(torch.get_num_threads)
  File ".../torch/multiprocessing/_atfork.py", line 35, in register_after_fork
    _register(func)
  File ".../torch/multiprocessing/_atfork.py", line 20, in _register
    os.register_at_fork(after_in_child=func)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'register_at_fork'
```

But it works well after a simple patch:
```diff
diff --git a/torch/multiprocessing/_atfork.py b/torch/multiprocessing/_atfork.py
--- torch/multiprocessing/_atfork.py
+++ torch/multiprocessing/_atfork.py
@@ -16,9 +16,10 @@
 else:
     import os
 
     def _register(func):
-        os.register_at_fork(after_in_child=func)
+        if hasattr(os, "register_at_fork"):
+            os.register_at_fork(after_in_child=func)
 
 
 def register_after_fork(func):
     """Register a callable to be executed in the child process after a fork.
```

### Versions

```
Collecting environment information...
...
OSError: [Errno 45] xxx does not support processes.
```

**Comment by albanD** [comment]
Thanks for the report. Can you give more details for the usecase you have where multiprocessing is not available?

**Comment by djphoenix** [comment]
It is about my experimental (but well working) build for iOS/iPadOS. For Apple mobile systems, multiprocessing is prohibited at build level, so `fork`/`exec` is not even detected in python configuration, so `register_at_fork` excluded from `os` module.
