### ISSUE TITLE
NumPy 2.1.0 Compatibility Issue with PyTorch 2.4.0: Importing PyTorch with NumPy 2.1.0 Causes _ARRAY_API not found Error

### ISSUE THREAD

**Issue by sascharo** [pytorch/pytorch#135013]
### 🐛 Describe the bug

Attempting to import PyTorch (torch) in a Python script results in a compatibility error related to NumPy. The error indicates that a module compiled using NumPy 1.x cannot be run with NumPy 2.1.0 due to potential crashes. It suggests that modules must be compiled with NumPy 2.0 or newer to support both versions.

Minimal reproducing example:
```
import torch

# Example usage that triggers the error
t = torch.rand(5, 10)
```

Error message:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "F:\source\repos\python-projects\rotating\main.py", line 6, in <module>
    import torch
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\__init__.py", line 2120, in <module>
    from torch._higher_order_ops import cond
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
```

I expect the torch module to import successfully without errors.

### Versions

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "F:\source\repos\python-projects\rotating\collect_env.py", line 16, in <module>
    import torch
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\__init__.py", line 2120, in <module>
    from torch._higher_order_ops import cond
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
F:\__HOME__\anaconda3\envs\rotating-on-pytorch\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
Collecting environment information...
PyTorch version: 2.4.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Education
GCC version: (Rev1, Built by MSYS2 project) 14.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 560.70
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3500
DeviceID=CPU0
Family=107
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3500
Name=AMD Ryzen Threadripper 2950X 16-Core Processor
ProcessorType=3
Revision=2050

Versions of relevant libraries:
[pip3] numpy==2.1.0
[pip3] pytorch-lightning==2.4.0
[pip3] torch==2.4.0+cu124
[pip3] torchaudio==2.4.0+cu124
[pip3] torchmetrics==1.4.1
[pip3] torchvision==0.19.0+cu124
[conda] numpy                     2.1.0                    pypi_0    pypi
[conda] pytorch-lightning         2.4.0                    pypi_0    pypi
[conda] torch                     2.4.0+cu124              pypi_0    pypi
[conda] torchaudio                2.4.0+cu124              pypi_0    pypi
[conda] torchmetrics              1.4.1                    pypi_0    pypi
[conda] torchvision               0.19.0+cu124             pypi_0    pypi

**Comment by ValerianRey** [comment]
Same for me with torch 2.4.1 and numpy 2.1.1. I guess numpy 2.1.1 solved it. Thanks for the update!

**Comment by Jeremaiha** [comment]
This issue persists for other versions as well. Is there any legit solution for the manner?
