### ISSUE TITLE
[export] non-strict export error on torch.distributions.Normal

### ISSUE THREAD

**Issue by yiming0416** [pytorch/pytorch#135061]
### 🐛 Describe the bug

The following issues showed up when I ran **non-strict** export on models `soft_actor_critic` and `drq` in `torchbench`. There is a data-dependent expression when calling `torch.distributions.Normal`. However, running strict mode doesn't have such issues

**Repro**
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import distributions as pyd

class SquashedNormal(pyd.transformed_distribution.TransformedDistribution):
    def __init__(self, loc, scale, tanh_transform_clamp=(-0.99, 0.99)):
        self.loc = loc
        self.scale = scale
        self.tanh_transform_clamp = tanh_transform_clamp
        self.base_dist = pyd.Normal(loc, scale)
        super().__init__(self.base_dist, [])

    @property
    def mean(self):
        mu = self.loc
        for tr in self.transforms:
            mu = tr(mu)
        return mu


def _squashed_normal_flatten(t: SquashedNormal):
    return [t.loc, t.scale], t.tanh_transform_clamp


def _squashed_normal_unflatten(values, context):
    return SquashedNormal(*values, context)


torch.utils._pytree.register_pytree_node(
    SquashedNormal,
    _squashed_normal_flatten,
    _squashed_normal_unflatten,
    serialized_type_name=f"{SquashedNormal.__module__}.{SquashedNormal.__name__}",
)

class StochasticActor(nn.Module):
    def __init__(
        self,
        state_space_size=4,
        act_space_size=2,
    ):
        super().__init__()
        self.fc = nn.Linear(state_space_size, act_space_size)

    def forward(self, state):
        out = F.relu(self.fc(state))
        mu, log_std = out.chunk(2, dim=1)
        log_std = torch.tanh(log_std)
        std = (-10 + 6*(log_std+1)).exp()
        dist = SquashedNormal(mu, std)
        return dist


model = StochasticActor()
ep = torch.export.export(model, (torch.randn(1,4),), strict=False)
print (ep)

```
**Error Msg**
```
W0903 15:10:15.901000 2821440 torch/fx/experimental/symbolic_shapes.py:5128] failed during evaluate_expr(Eq(u0, 1), hint=None, expect_rational=True, size_oblivious=False, forcing_spec=False
E0903 15:10:15.901000 2821440 torch/fx/experimental/recording.py:298] failed while running evaluate_expr(*(Eq(u0, 1), None), **{'fx_node': False})
Traceback (most recent call last):
  File "/home/yimingzhou/pytorch/torch/_export/non_strict_utils.py", line 513, in __torch_function__
    return func(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/fx/experimental/sym_node.py", line 451, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/home/yimingzhou/pytorch/torch/fx/experimental/recording.py", line 262, in wrapper
    return retlog(fn(*args, **kwargs))
  File "/home/yimingzhou/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5126, in evaluate_expr
    return self._evaluate_expr(orig_expr, hint, fx_node, expect_rational, size_oblivious, forcing_spec=forcing_spec)
  File "/home/yimingzhou/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5244, in _evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(u0, 1) (unhinted: Eq(u0, 1)).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/home/yimingzhou/pytorch/torch/_export/non_strict_utils.py", line 513, in __torch_function__
    return func(*args, **kwargs)

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

The following call raised this error:
  File "/home/yimingzhou/pytorch/pyd_normal_repro.py", line 11, in __init__
    self.base_dist = pyd.Normal(loc, scale)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yimingzhou/pytorch/pyd_normal_repro.py", line 57, in <module>
    ep = torch.export.export(model, (torch.randn(1,4),), strict=False)
  File "/home/yimingzhou/pytorch/torch/export/__init__.py", line 258, in export
    return _export(
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 1007, in wrapper
    raise e
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 980, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/export/exported_program.py", line 105, in wrapper
    return fn(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 1915, in _export
    export_artifact = export_func(  # type: ignore[operator]
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 1719, in _non_strict_export
    aten_export_artifact = _to_aten_func(  # type: ignore[operator]
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 626, in _export_to_aten_ir
    gm, graph_signature = transform(aot_export_module)(
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 1648, in _aot_export_non_strict
    gm, sig = aot_export(wrapped_mod, args, kwargs=kwargs, **flags)
  File "/home/yimingzhou/pytorch/torch/_functorch/aot_autograd.py", line 1246, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/home/yimingzhou/pytorch/torch/_functorch/aot_autograd.py", line 1480, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/home/yimingzhou/pytorch/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/home/yimingzhou/pytorch/torch/_functorch/aot_autograd.py", line 623, in _create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/home/yimingzhou/pytorch/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 168, in inner
    flat_f_outs = f(*flat_f_args)
  File "/home/yimingzhou/pytorch/torch/_functorch/_aot_autograd/utils.py", line 182, in flat_fn
    tree_out = fn(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 863, in functional_call
    out = mod(*args[params_len:], **kwargs)
  File "/home/yimingzhou/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/export/_trace.py", line 1635, in forward
    tree_out = self._export_root(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yimingzhou/pytorch/pyd_normal_repro.py", line 52, in forward
    dist = SquashedNormal(mu, std)
  File "/home/yimingzhou/pytorch/pyd_normal_repro.py", line 11, in __init__
    self.base_dist = pyd.Normal(loc, scale)
  File "/home/yimingzhou/pytorch/torch/distributions/normal.py", line 59, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/yimingzhou/pytorch/torch/distributions/distribution.py", line 70, in __init__
    if not valid.all():
  File "/home/yimingzhou/pytorch/torch/_export/non_strict_utils.py", line 515, in __torch_function__
    _suggest_fixes_for_data_dependent_error_non_strict(e)
  File "/home/yimingzhou/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5598, in _suggest_fixes_for_data_dependent_error_non_strict
    for path, leaf in pytree.tree_leaves_with_path(val):
  File "/home/yimingzhou/pytorch/torch/utils/_pytree.py", line 1544, in tree_leaves_with_path
    return list(_generate_key_paths((), tree, is_leaf))
  File "/home/yimingzhou/pytorch/torch/utils/_pytree.py", line 1570, in _generate_key_paths
    raise ValueError(
ValueError: Did not find a flatten_with_keys_fn for type: <class '__main__.SquashedNormal'>. Please pass a flatten_with_keys_fn argument to register_pytree_node.
```

### Versions

main

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ezyang** [comment]
@avikchaudhuri another bug in suggest_fixes_for_...

**Comment by pianpwk** [comment]
Hmm it seems to come from torch.distributions here, where element-wise checks are run on the distribution parameters. In this case it's checking for real number on the mean, and >= 0 for std. But then the `not valid.all()` call to verify this is triggering the Eq(u0, 1) error. 

@ezyang could we just guard this check with `torch.compiler.is_compiling()` to avoid? Or maybe assert_async in that case..

https://github.com/pytorch/pytorch/blob/8520ce5f78227a81fa1a0b37dd73f9a43bf31fc2/torch/distributions/distribution.py#L68-L77

**Comment by ezyang** [comment]
So where I got stuck is there seems to be some indirection via the constraints mechanism. You need to find the /real/ place that actually is generating this constraint.

**Comment by avikchaudhuri** [comment]
@yiming0416 This doesn't repro for me, I'm on fbcode trunk. Can you check?

**Comment by avikchaudhuri** [comment]
@ezyang Independent of the repro, ack that there is a bug to fix in data-dependent error handling. Will put up a PR.

**Comment by avikchaudhuri** [comment]
> @ezyang Independent of the repro, ack that there is a bug to fix in data-dependent error handling. Will put up a PR.

https://github.com/pytorch/pytorch/pull/135518

**Comment by yushangdi** [comment]
@avikchaudhuri I can still repro running on main:

```
W0325 18:00:19.308000 2531609 torch/fx/experimental/symbolic_shapes.py:6679] failed during evaluate_expr(Eq(u0, 1), hint=None, size_oblivious=False, forcing_spec=False
E0325 18:00:19.309000 2531609 torch/fx/experimental/recording.py:299] failed while running evaluate_expr(*(Eq(u0, 1), None, False, False), **{})
W0325 18:00:19.309000 2531609 torch/fx/experimental/symbolic_shapes.py:7276] pytree.tree_leaves_with_path failed for value of type {<class '__main__.SquashedNormal'>} in local variable {self}
W0325 18:00:19.309000 2531609 torch/fx/experimental/symbolic_shapes.py:7234] Unable to find user code corresponding to {u0}




def forward(self, arg0_1: "f32[2, 4]", arg1_1: "f32[2]", arg2_1: "f32[1, 4]"):
     # File: /data/users/shangdiy/pytorch/torch/nn/modules/linear.py:125 in forward, code: return F.linear(input, self.weight, self.bias)
    linear: "f32[1, 2]" = torch.ops.aten.linear.default(arg2_1, arg0_1, arg1_1);  arg2_1 = arg0_1 = arg1_1 = None
    
     # File: /data/users/shangdiy/pytorch/test.py:47 in forward, code: out = F.relu(self.fc(state))
    relu: "f32[1, 2]" = torch.ops.aten.relu.default(linear);  linear = None
    
     # File: /data/users/shangdiy/pytorch/test.py:48 in forward, code: mu, log_std = out.chunk(2, dim=1)
    chunk = torch.ops.aten.chunk.default(relu, 2, 1);  relu = None
    getitem: "f32[1, 1]" = chunk[0]
    getitem_1: "f32[1, 1]" = chunk[1];  chunk = None
    
     # File: /data/users/shangdiy/pytorch/test.py:49 in forward, code: log_std = torch.tanh(log_std)
    tanh: "f32[1, 1]" = torch.ops.aten.tanh.default(getitem_1);  getitem_1 = None
    
     # File: /data/users/shangdiy/pytorch/test.py:50 in forward, code: std = (-10 + 6*(log_std+1)).exp()
    add: "f32[1, 1]" = torch.ops.aten.add.Tensor(tanh, 1);  tanh = None
    mul: "f32[1, 1]" = torch.ops.aten.mul.Tensor(add, 6);  add = None
    add_1: "f32[1, 1]" = torch.ops.aten.add.Tensor(mul, -10);  mul = None
    exp: "f32[1, 1]" = torch.ops.aten.exp.default(add_1);  add_1 = None
    
     # File: /data/users/shangdiy/pytorch/test.py:51 in forward, code: dist = SquashedNormal(mu, std)
    broadcast_tensors = torch.ops.aten.broadcast_tensors.default([getitem, exp]);  getitem = exp = None
    getitem_2: "f32[1, 1]" = broadcast_tensors[0]
    getitem_3: "f32[1, 1]" = broadcast_tensors[1];  broadcast_tensors = getitem_3 = None
    eq: "b8[1, 1]" = torch.ops.aten.eq.Tensor(getitem_2, getitem_2);  getitem_2 = None
    _is_all_true: "b8[]" = torch.ops.aten._is_all_true.default(eq);  eq = None
    ne: "b8[]" = torch.ops.aten.ne.Scalar(_is_all_true, 0);  _is_all_true = None
    item: "Sym(Eq(u0, 1))" = torch.ops.aten.item.default(ne);  ne = item = None
    
/data/users/shangdiy/pytorch/torch/backends/mkldnn/__init__.py:78: UserWarning: TF32 acceleration on top of oneDNN is available for Intel GPUs. The current Torch version does not have Intel GPU Support. (Triggered internally at /data/users/shangdiy/pytorch/aten/src/ATen/Context.cpp:148.)
  torch._C._set_onednn_allow_tf32(_allow_tf32)
Traceback (most recent call last):
  File "/data/users/shangdiy/pytorch/test.py", line 56, in <module>
    ep = torch.export.export(model, (torch.randn(1,4),), strict=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/__init__.py", line 360, in export
    return _export(
           ^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1092, in wrapper
    raise e
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1065, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/exported_program.py", line 121, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 2112, in _export
    ep = _export_for_training(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1092, in wrapper
    raise e
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1065, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/exported_program.py", line 121, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1975, in _export_for_training
    export_artifact = export_func(  # type: ignore[operator]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1910, in _non_strict_export
    aten_export_artifact = _to_aten_func(  # type: ignore[operator]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1696, in _export_to_aten_ir_make_fx
    gm, graph_signature = transform(_make_fx_helper)(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1840, in _aot_export_non_strict
    gm, sig = aot_export(wrapped_mod, args, kwargs=kwargs, **flags)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1616, in _make_fx_helper
    gm = make_fx(
         ^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 2240, in wrapped
    return make_fx_tracer.trace(f, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 2178, in trace
    return self._trace_inner(f, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 2149, in _trace_inner
    t = dispatch_trace(
        ^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/_dynamo/eval_frame.py", line 838, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1174, in dispatch_trace
    graph = tracer.trace(root, concrete_args)  # type: ignore[arg-type]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1738, in trace
    res = super().trace(root, concrete_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 838, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1229, in wrapped
    out = f(*tensors)  # type:ignore[call-arg]
          ^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1520, in wrapped_fn
    return tuple(flat_fn(*args))
                 ^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/_functorch/_aot_autograd/utils.py", line 184, in flat_fn
    tree_out = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 903, in functional_call
    out = mod(*args[params_len:], **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 813, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1808, in call_module
    return Tracer.call_module(self, m, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 531, in call_module
    ret_val = forward(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 806, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/export/_trace.py", line 1824, in forward
    tree_out = mod(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 813, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1808, in call_module
    return Tracer.call_module(self, m, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 531, in call_module
    ret_val = forward(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/_symbolic_trace.py", line 806, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/test.py", line 51, in forward
    dist = SquashedNormal(mu, std)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/test.py", line 11, in __init__
    self.base_dist = pyd.Normal(loc, scale)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/distributions/normal.py", line 60, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/data/users/shangdiy/pytorch/torch/distributions/distribution.py", line 71, in __init__
    if not torch._is_all_true(valid):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1277, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/proxy_tensor.py", line 1324, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/_export/non_strict_utils.py", line 683, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/sym_node.py", line 536, in guard_bool
    r = self.evaluate()
        ^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/sym_node.py", line 510, in evaluate
    return self.shape_env.evaluate_sym_node(self, size_oblivious)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6655, in evaluate_sym_node
    return self.evaluate_expr(
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/recording.py", line 263, in wrapper
    return retlog(fn(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6671, in evaluate_expr
    return self._evaluate_expr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/shangdiy/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6894, in _evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(u0, 1) (unhinted: Eq(u0, 1)).  (Size-like symbols: none)

Caused by: (_export/non_strict_utils.py:683 in __torch_function__)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

The following call raised this error:
  File "/data/users/shangdiy/pytorch/test.py", line 11, in __init__
    self.base_dist = pyd.Normal(loc, scale)
```

**Comment by laithsakka** [comment]
I guess we need to make 
```
bool is_nonzero(const Tensor& self) {
  auto n = self.numel();
  TORCH_CHECK(n != 0, "Boolean value of Tensor with no values is ambiguous");
  TORCH_CHECK(
      n < 2, "Boolean value of Tensor with more than one value is ambiguous");

  Scalar localScalar = self.item();
  if (localScalar.isFloatingPoint()) {
    return localScalar.to<double>() != 0;
  } else if (localScalar.isComplex()) {
    return localScalar.to<c10::complex<double>>() !=
        c10::complex<double>(0.0, 0.0);
  } else if (localScalar.isIntegral(false)) {
    return localScalar.to<int64_t>() != 0;
  } else if (localScalar.isBoolean()) {
    return localScalar.to<bool>();
  }
  TORCH_INTERNAL_ASSERT(false, "Expected non-Tensor backend scalar");
}
```
DDE friendly.
