### ISSUE TITLE
MacOS runner fails at `Complete runner step` 

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#135362]
### 🐛 Describe the bug

List of jobs (all of them MPS ones for some reason):
- https://github.com/pytorch/pytorch/actions/runs/10738683344/job/29783923957
- https://github.com/pytorch/pytorch/actions/runs/10739166790/job/29784739940
- https://github.com/pytorch/pytorch/actions/runs/10739832388/job/29787068694
- https://github.com/pytorch/pytorch/actions/runs/10740092184/job/29787906784
- https://github.com/pytorch/pytorch/actions/runs/10740449433/job/29789033721

### Versions

CI

**Comment by malfet** [comment]
From the logs on the runner:
```
2024-09-06 16:08:18Z INFO StepsRunner] Processing step: DisplayName='Complete runner'
[2024-09-06 16:08:18Z INFO StepsRunner] Evaluating: always()
[2024-09-06 16:08:18Z INFO StepsRunner] Result: true
[2024-09-06 16:08:18Z INFO StepsRunner] Starting the step.
[2024-09-06 16:08:18Z ERR  StepsRunner] Caught exception from step: System.IO.FileNotFoundException: File doesn't exist
   at GitHub.Runner.Worker.JobHookProvider.RunHook(IExecutionContext executionContext, Object data)
   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[2024-09-06 16:08:18Z INFO StepsRunner] Step result: Failed
[2024-09-06 16:08:18Z INFO StepsRunner] Update job result with current step result 'Failed'.
[2024-09-06 16:08:18Z INFO StepsRunner] Current state: job state = 'Failed'
[2024-09-06 16:08:18Z INFO JobRunner] Finalize job.
```

**Comment by malfet** [comment]
And for some reason this runner is missing `/opt/runner_scripts/post_job.sh`
