### ISSUE TITLE
torchrun nccl Multi machine and multi card training error: ss1.ss_family == ss2.ss_family. 2 vs 10

### ISSUE THREAD

**Issue by sph116** [pytorch/pytorch#135355]
### 🐛 Describe the bug

torchrun Multi machine and multi card training error.
Both Rank1 and Rank2 can be trained normally.
The error occurs after the successful establishment of nccl communication

#### rank0 log
```
[2024-09-06 13:49:48,898] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-09-06 13:49:48,898] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
fedora:2414:2414 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to enp4s0
fedora:2414:2414 [0] NCCL INFO Bootstrap : Using enp4s0:172.18.12.59<0>
fedora:2414:2414 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
fedora:2414:2414 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.20.5+cuda12.4
fedora:2414:2469 [0] NCCL INFO Failed to open libibverbs.so[.1]
fedora:2414:2469 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to enp4s0
fedora:2414:2469 [0] NCCL INFO NET/Socket : Using [0]enp4s0:172.18.12.59<0>
fedora:2414:2469 [0] NCCL INFO Using non-device net plugin version 0
fedora:2414:2469 [0] NCCL INFO Using network Socket
fedora:2414:2469 [0] NCCL INFO comm 0xc31a680 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0xd987dbe723df81a4 - Init START
fedora:2414:2469 [0] NCCL INFO comm 0xc31a680 rank 0 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
fedora:2414:2469 [0] NCCL INFO Channel 00/02 :    0   1
fedora:2414:2469 [0] NCCL INFO Channel 01/02 :    0   1
fedora:2414:2469 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
fedora:2414:2469 [0] NCCL INFO P2P Chunksize set to 131072
fedora:2414:2469 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [receive] via NET/Socket/0
fedora:2414:2469 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [receive] via NET/Socket/0
fedora:2414:2469 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [send] via NET/Socket/0
fedora:2414:2469 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [send] via NET/Socket/0
fedora:2414:2469 [0] NCCL INFO Connected all rings
fedora:2414:2469 [0] NCCL INFO Connected all trees
fedora:2414:2469 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
fedora:2414:2469 [0] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
fedora:2414:2469 [0] NCCL INFO comm 0xc31a680 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0xd987dbe723df81a4 - Init COMPLETE

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 360, in <module>
[rank0]:     main()
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 356, in main
[rank0]:     runner.train()
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1160, in train
[rank0]:     self._train_loop = self.build_train_loop(
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 958, in build_train_loop
[rank0]:     loop = LOOPS.build(
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank0]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank0]:     obj = obj_cls(**args)  # type: ignore
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/engine/runner/loops.py", line 32, in __init__
[rank0]:     dataloader = runner.build_dataloader(
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 824, in build_dataloader
[rank0]:     dataset = DATASETS.build(dataset_cfg)
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank0]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank0]:     obj = obj_cls(**args)  # type: ignore
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/dataset/huggingface.py", line 305, in process_hf_dataset
[rank0]:     group_gloo = dist.new_group(backend='gloo', timeout=xtuner_dataset_timeout)
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
[rank0]:     func_return = func(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4125, in new_group
[rank0]:     return _new_group_with_tag(
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4205, in _new_group_with_tag
[rank0]:     pg, pg_store = _new_process_group_helper(
[rank0]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1569, in _new_process_group_helper
[rank0]:     backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
[rank0]: **RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:276] ss1.ss_family == ss2.ss_family. 2 vs 10**
[rank0]:[W906 13:49:53.865609084 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
fedora:2414:2470 [0] NCCL INFO [Service thread] Connection closed by localRank 0
fedora:2414:2481 [0] NCCL INFO comm 0xc31a680 rank 0 nranks 2 cudaDev 0 busId 1000 - Abort COMPLETE
```
#### rank1 log
```
localhost:5644:5644 [0] NCCL INFO cudaDriverVersion 12040
localhost:5644:5644 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eno1
localhost:5644:5644 [0] NCCL INFO Bootstrap : Using eno1:172.18.12.43<0>
localhost:5644:5644 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
localhost:5644:5708 [0] NCCL INFO Failed to open libibverbs.so[.1]
localhost:5644:5708 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eno1
localhost:5644:5708 [0] NCCL INFO NET/Socket : Using [0]eno1:172.18.12.43<0>
localhost:5644:5708 [0] NCCL INFO Using non-device net plugin version 0
localhost:5644:5708 [0] NCCL INFO Using network Socket
localhost:5644:5708 [0] NCCL INFO comm 0xb0fc580 rank 1 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0x9598bc84e3a9edb4 - Init START
localhost:5644:5708 [0] NCCL INFO comm 0xb0fc580 rank 1 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
localhost:5644:5708 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
localhost:5644:5708 [0] NCCL INFO P2P Chunksize set to 131072
localhost:5644:5708 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [receive] via NET/Socket/0
localhost:5644:5708 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [receive] via NET/Socket/0
localhost:5644:5708 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [send] via NET/Socket/0
localhost:5644:5708 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [send] via NET/Socket/0
localhost:5644:5708 [0] NCCL INFO Connected all rings
localhost:5644:5708 [0] NCCL INFO Connected all trees
localhost:5644:5708 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
localhost:5644:5708 [0] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
localhost:5644:5708 [0] NCCL INFO comm 0xb0fc580 rank 1 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0x9598bc84e3a9edb4 - Init COMPLETE
[rank1]: Traceback (most recent call last):
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 360, in <module>
[rank1]:     main()
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 356, in main
[rank1]:     runner.train()
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1160, in train
[rank1]:     self._train_loop = self.build_train_loop(
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 958, in build_train_loop
[rank1]:     loop = LOOPS.build(
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank1]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank1]:     obj = obj_cls(**args)  # type: ignore
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/engine/runner/loops.py", line 32, in __init__
[rank1]:     dataloader = runner.build_dataloader(
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 824, in build_dataloader
[rank1]:     dataset = DATASETS.build(dataset_cfg)
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank1]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank1]:     obj = obj_cls(**args)  # type: ignore
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/dataset/huggingface.py", line 305, in process_hf_dataset
[rank1]:     group_gloo = dist.new_group(backend='gloo', timeout=xtuner_dataset_timeout)
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
[rank1]:     func_return = func(*args, **kwargs)
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4125, in new_group
[rank1]:     return _new_group_with_tag(
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4205, in _new_group_with_tag
[rank1]:     pg, pg_store = _new_process_group_helper(
[rank1]:   File "/root/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1569, in _new_process_group_helper
[rank1]:     backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
[rank1]: **RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:276] ss1.ss_family == ss2.ss_family. 10 vs 2**
localhost:5644:5709 [0] NCCL INFO [Service thread] Connection closed by localRank 0
localhost:5644:5719 [0] NCCL INFO comm 0xb0fc580 rank 1 nranks 2 cudaDev 0 busId 1000 - Abort COMPLETE
```

### Versions

Rank1 and Rank2 have the same Docker container deployment environment
Rank1 and Rank2 both use 0 card 4090

#### rank0:
```
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.6 (Green Obsidian) (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.9-200.fc36.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 4090 D
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 550.54.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Stepping:            13
CPU MHz:             3252.407
CPU max MHz:         5000.0000
CPU min MHz:         800.0000
BogoMIPS:            7200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
```
#### rank1:
```PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.6 (Green Obsidian) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1062.el7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Stepping:            13
CPU MHz:             4700.170
CPU max MHz:         5000.0000
CPU min MHz:         800.0000
BogoMIPS:            7200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch intel_pt ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
```

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @ptrblck @msaroufim

**Comment by sph116** [comment]
This is my startup parameter
`NPROC_PER_NODE=1 NNODES=2 PORT=29600 ADDR=0.0.0.0 NODE_RANK=0`
`NPROC_PER_NODE=1 NNODES=2 PORT=29600 ADDR=172.18.12.59 NODE_RANK=1`
please check

**Comment by c-p-i-o** [comment]
It looks like rank0 is using IPV4 and rank1 is using IPV6. ss_family `2` == IPV4 and ss_family `10` == IPV6.
```
[rank0]: **RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:276] ss1.ss_family == ss2.ss_family. 2 vs 10**
```
[rank1]: **RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:276] ss1.ss_family == ss2.ss_family. 10 vs 2**
```
Can you verify @sph116 that you are not mixing the 2 IP versions.
That said, I believe mixed networks should work and maybe we remove the assert [here](https://github.com/facebookincubator/gloo/blob/main/gloo/transport/tcp/device.cc#L276)

cc @d4l3k

**Comment by d4l3k** [comment]
@c-p-i-o yeah that's interesting -- I think we bind by default to ipv6 so likely there's a conflict. I'm not quite sure why Gloo has that check

@sph116 you could try removing that check and building pytorch from source, if it works fine we can likely relax that constraint

The other thing is if you're using NCCL there's not much reason to also be using Gloo. If you just use nccl it should avoid this issue

What does `ADDR=0.0.0.0` do in this case? Should that instead be the main host ip address? 0.0.0.0 can act strangely and may be binding an ipv6 address and causing this issue

**Comment by c-p-i-o** [comment]
> What does ADDR=0.0.0.0 do in this case? 

Thanks @d4l3k. From my understanding, `ADDR=0.0.0.0` will create listeners on ALL available ports and IPs and in this case, it appears that `rank0` machine decided to bind the port to the IPv6 address. At least that's what I'm able to see from the provided logs.

**Comment by c-p-i-o** [comment]
@sph116 were you able to get over this issue?

Alternatively, we can try a patch that allows IPV4 and IPV6 mixing?

**Comment by c-p-i-o** [comment]
Closing this issue out for now. @sph116, please re-open the issue if this issue still exists.
