### ISSUE TITLE
Distributed `Segmentation fault` in basic operation

### ISSUE THREAD

**Issue by etiennemlb** [pytorch/pytorch#135486]
### 🐛 Describe the bug

```python
import torch
import torch.distributed.elastic.multiprocessing


@torch.distributed.elastic.multiprocessing.errors.record
def Main():
    torch.distributed.init_process_group("nccl")
    the_main_process_group = torch.distributed.new_group(ranks=None, backend=None)
    torch.distributed.barrier(group=the_main_process_group)


if __name__ == "__main__":
    assert torch.distributed.is_available()
    assert torch.distributed.is_torchelastic_launched()

    Main()
```
Note that if I use the default process group, the error is the same.

Launched like so:
```shell
srun --label --nodes="1" --ntasks-per-node="1" \
    -- torchrun --nnodes="1" --nproc_per_node="1" --rdzv-backend=c10d \
    --rdzv-endpoint="$(scontrol show hostname ${SLURM_NODELIST} | head -n 1):29400" \
    -- ./1.basic.py
```

Traceback:
```
0: g1002:2128869:2128869 [0] NCCL INFO Bootstrap : Using bond0:10.64.0.51<0>
0: g1002:2128869:2128869 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
0: g1002:2128869:2128869 [0] NCCL INFO NET/Plugin: Loaded net plugin AWS Libfabric (v5)
0: g1002:2128869:2128869 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
0: g1002:2128869:2128869 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
0: g1002:2128869:2128869 [0] NCCL INFO Kernel version: 4.18.0-477.10.1.el8_8.x86_64
0: g1002:2128869:2128869 NCCL CALL ncclGetUniqueId(0xc310145dea15d940)
0: g1002:2128869:2128869 [0] NCCL INFO ROCr version 1.13
0: g1002:2128869:2128869 [0] NCCL INFO Dmabuf feature disabled without NCCL_ENABLE_DMABUF_SUPPORT=1
0: RCCL version 2.18.6+hip6.1 HEAD:164c955+
0: g1002:2128869:2128869 [0] NCCL INFO /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/rccl/build/hipify/src/init.cc:1946 Cuda Host Alloc Size 4 pointer 0x148252c91000
0: g1002:2128869:2128880 [0] NCCL INFO NET/OFI Using aws-ofi-rccl 1.4.0
0: g1002:2128869:2128880 [0] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1
0: g1002:2128869:2128880 [0] 57.030301 filter_cxi_info_list:426 NCCL TRACE NET/OFI Removing multiple CXI info for same domain
0: g1002:2128869:2128880 [0] NCCL INFO NET/OFI Selected Provider is cxi
0: g1002:2128869:2128880 [0] 57.040240 ofi_init:1202 NCCL TRACE NET/OFI Provider cxi does not require registration of local memory buffers
0: g1002:2128869:2128880 [0] 57.042294 ofi_init:1212 NCCL TRACE NET/OFI Provider cxi does not require registration of device buffers
0: g1002:2128869:2128880 [0] NCCL INFO Using network AWS Libfabric
0: g1002:2128869:2128880 [0] NCCL INFO /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/rccl/build/hipify/src/init.cc:527 Cuda Host Alloc Size 262144 pointer 0x148252580000
0: g1002:2128869:2128880 [0] NCCL INFO /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/rccl/build/hipify/src/init.cc:528 Cuda Host Alloc Size 16777216 pointer 0x147a30200000
0: g1002:2128869:2128880 [0] NCCL INFO comm 0x893f350 rank 0 nranks 1 cudaDev 0 busId c1000 commId 0xc310145dea15d940 - Init START
0: g1002:2128869:2128880 [0] NCCL INFO rocm_smi_lib: version 7.0.0.0
0: g1002:2128869:2128880 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 0 'cxi0'
0: g1002:2128869:2128880 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 1 'cxi1'
0: g1002:2128869:2128880 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 2 'cxi2'
0: g1002:2128869:2128880 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 3 'cxi3'
0: g1002:2128869:2128880 [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
0: g1002:2128869:2128880 [0] NCCL INFO GPU Direct RDMA Enabled for GPU c1000 / HCA 0 (distance 6 <= 6), read 0
0: g1002:2128869:2128880 [0] NCCL INFO GPU Direct RDMA Disabled for GPU c1000 / HCA 1 (distance 7 > 6)
0: g1002:2128869:2128880 [0] NCCL INFO GPU Direct RDMA Disabled for GPU c1000 / HCA 2 (distance 7 > 6)
0: g1002:2128869:2128880 [0] NCCL INFO GPU Direct RDMA Disabled for GPU c1000 / HCA 3 (distance 7 > 6)
0: g1002:2128869:2128880 [0] NCCL INFO GPU Direct RDMA Enabled for GPU c1000 / HCA 0 (distance 6 <= 6), read 1
0: g1002:2128869:2128880 [0] NCCL INFO === System : maxBw 5000.0 totalBw 0.0 ===
0: g1002:2128869:2128880 [0] NCCL INFO CPU/3 (1/2/4)
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/1
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/0
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/2
0: g1002:2128869:2128880 [0] NCCL INFO + PCI[24.0] - GPU/C1000 (0)
0: g1002:2128869:2128880 [0] NCCL INFO + PCI[24.0] - NIC/C5000
0: g1002:2128869:2128880 [0] NCCL INFO CPU/1 (1/2/4)
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/3
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/0
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/2
0: g1002:2128869:2128880 [0] NCCL INFO + PCI[24.0] - NIC/CD000
0: g1002:2128869:2128880 [0] NCCL INFO CPU/0 (1/2/4)
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/3
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/1
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/2
0: g1002:2128869:2128880 [0] NCCL INFO + PCI[24.0] - NIC/D5000
0: g1002:2128869:2128880 [0] NCCL INFO CPU/2 (1/2/4)
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/3
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/1
0: g1002:2128869:2128880 [0] NCCL INFO + SYS[5000.0] - CPU/0
0: g1002:2128869:2128880 [0] NCCL INFO + PCI[24.0] - NIC/DD000
0: g1002:2128869:2128880 [0] NCCL INFO ==========================================
0: g1002:2128869:2128880 [0] NCCL INFO GPU/C1000 :GPU/C1000 (0/5000.000000/LOC) CPU/3 (1/24.000000/PHB) CPU/1 (2/24.000000/SYS) CPU/0 (2/24.000000/SYS) CPU/2 (2/24.000000/SYS) 
0: g1002:2128869:2128880 [0] NCCL INFO Setting affinity for GPU 0 to ffff0000,00000000,ffff0000,00000000
0: Fatal Python error: Segmentation fault
0: 
0: Thread 0x000014844b65d740 (most recent call first):
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3938 in barrier
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 79 in wrapper
0:   File "<deracted for brevity>torch.mi250/test/./1.basic.py", line 11 in Main
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348 in wrapper
0:   File "<deracted for brevity>torch.mi250/test/./1.basic.py", line 18 in <module>
0: 
0: Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special (total: 9)
0: E0909 14:03:50.013000 22579342468928 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -11) local_rank: 0 (pid: 2128869) of binary: <deracted for brevity>torch.mi250/python_environment/bin/python
0: Traceback (most recent call last):
0:   File "<deracted for brevity>torch.mi250/python_environment/bin/torchrun", line 10, in <module>
0:     sys.exit(main())
0:              ^^^^^^
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
0:     return f(*args, **kwargs)
0:            ^^^^^^^^^^^^^^^^^^
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
0:     run(args)
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
0:     elastic_launch(
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
0:     return launch_agent(self._config, self._entrypoint, list(args))
0:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "<deracted for brevity>torch.mi250/python_environment/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
0:     raise ChildFailedError(
0: torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
0: =========================================================
0: ./1.basic.py FAILED
0: ---------------------------------------------------------
0: Failures:
0:   <NO_OTHER_FAILURES>
0: ---------------------------------------------------------
0: Root Cause (first observed failure):
0: [0]:
0:   time      : 2024-09-09_14:03:50
0:   host      : g1002.hostmgmt2000
0:   rank      : 0 (local_rank: 0)
0:   exitcode  : -11 (pid: 2128869)
0:   error_file: <N/A>
0:   traceback : Signal 11 (SIGSEGV) received by PID 2128869
0: =========================================================
```

### Versions

```
Collecting environment information...
PyTorch version: 2.4.1+rocm6.1
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 6.1.40091-a8dbc0c19

OS: Red Hat Enterprise Linux release 8.8 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.28

Python version: 3.11.5 (main, Nov 29 2023, 20:14:26) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] (64-bit runtime)
Python platform: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X (gfx90a:sramecc+:xnack-)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 6.1.40091
MIOpen runtime version: 3.1.0
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  64
Socket(s):           1
NUMA node(s):        4
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               48
Model name:          AMD EPYC 7A53 64-Core Processor
Stepping:            1
CPU MHz:             2000.000
CPU max MHz:         3541.0149
CPU min MHz:         1500.0000
BogoMIPS:            3992.31
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-15,64-79
NUMA node1 CPU(s):   16-31,80-95
NUMA node2 CPU(s):   32-47,96-111
NUMA node3 CPU(s):   48-63,112-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==2.1.1
[pip3] pytorch-triton-rocm==3.0.0
[pip3] torch==2.4.1+rocm6.1
[pip3] torchaudio==2.4.1+rocm6.1
[pip3] torchvision==0.19.1+rocm6.1
[conda] Could not collect
```

**Comment by hongxiayang** [comment]
@etiennemlb: Do you have a reproducer script/command without relying on the slurm environment?

**Comment by wconstab** [comment]
if possible could you attach a gdb stacktrace? i am also wondering if this is related to not setting the default cuda device before calling the barrier.  You could try setting the device as a workaround, if so.

**Comment by hongxiayang** [comment]
Since I don't have slurm, I ran the below command in various rocm/pytorch versions (inlcuding the stable `pip3 install torch --index-url https://download.pytorch.org/whl/rocm6.1`),  and I could not reproduce the problem.
```
torchrun --nnodes=1 --nproc_per_node=1 --rdzv-backend=c10d     --rdzv-endpoint="localhost:29400"  ./basic.py
```

**Comment by etiennemlb** [comment]
I did the following:
```
export NCCL_DEBUG="TRACE"
export NCCL_DEBUG_SUBSYS="ALL"

source ./python_environment/bin/activate

pip3 freeze

torchrun --nnodes=1 --nproc_per_node=1 --rdzv-backend=c10d --rdzv-endpoint="localhost:29400" ./basic.py
```

Which printed:
```
filelock==3.13.1
fsspec==2024.2.0
Jinja2==3.1.3
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
pillow==10.2.0
pytorch-triton-rocm==3.0.0
sympy==1.12
torch==2.4.1+rocm6.1
torchaudio==2.4.1+rocm6.1
torchvision==0.19.1+rocm6.1
typing_extensions==4.9.0
g1255:1752304:1752304 [0] NCCL INFO Bootstrap : Using bond0:10.64.12.61<0>
g1255:1752304:1752304 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
g1255:1752304:1752304 [0] NCCL INFO NET/Plugin: Loaded net plugin AWS Libfabric (v5)
g1255:1752304:1752304 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
g1255:1752304:1752304 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
g1255:1752304:1752304 [0] NCCL INFO Kernel version: 4.18.0-477.10.1.el8_8.x86_64
g1255:1752304:1752304 NCCL CALL ncclGetUniqueId(0x1010293603fbc5f1)
g1255:1752304:1752304 [0] NCCL INFO ROCr version 1.13
g1255:1752304:1752304 [0] NCCL INFO Dmabuf feature disabled without NCCL_ENABLE_DMABUF_SUPPORT=1
RCCL version 2.18.6+hip6.1 HEAD:164c955+
g1255:1752304:1752304 [0] NCCL INFO /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/rccl/build/hipify/src/init.cc:1946 Cuda Host Alloc Size 4 pointer 0x14a8fb36f000
g1255:1752304:1752378 [0] NCCL INFO NET/OFI Using aws-ofi-rccl 1.4.0
g1255:1752304:1752378 [0] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1
g1255:1752304:1752378 [0] 158.694653 filter_cxi_info_list:426 NCCL TRACE NET/OFI Removing multiple CXI info for same domain
g1255:1752304:1752378 [0] NCCL INFO NET/OFI Selected Provider is cxi
g1255:1752304:1752378 [0] 158.727787 ofi_init:1202 NCCL TRACE NET/OFI Provider cxi does not require registration of local memory buffers
g1255:1752304:1752378 [0] 158.735271 ofi_init:1212 NCCL TRACE NET/OFI Provider cxi does not require registration of device buffers
g1255:1752304:1752378 [0] NCCL INFO Using network AWS Libfabric
g1255:1752304:1752378 [0] NCCL INFO /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/rccl/build/hipify/src/init.cc:527 Cuda Host Alloc Size 262144 pointer 0x14a8fb2c0000
g1255:1752304:1752378 [0] NCCL INFO /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/rccl/build/hipify/src/init.cc:528 Cuda Host Alloc Size 16777216 pointer 0x14a0d8600000
g1255:1752304:1752378 [0] NCCL INFO comm 0x95ae1a0 rank 0 nranks 1 cudaDev 0 busId c1000 commId 0x1010293603fbc5f1 - Init START
g1255:1752304:1752378 [0] NCCL INFO rocm_smi_lib: version 7.0.0.0
g1255:1752304:1752378 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 0 'cxi0'
g1255:1752304:1752378 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 1 'cxi1'
g1255:1752304:1752378 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 2 'cxi2'
g1255:1752304:1752378 [0] NCCL INFO NET/AWS Libfabric : GPU Direct RDMA Enabled for HCA 3 'cxi3'
g1255:1752304:1752378 [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
g1255:1752304:1752378 [0] NCCL INFO GPU Direct RDMA Enabled for GPU c1000 / HCA 0 (distance 6 <= 6), read 0
g1255:1752304:1752378 [0] NCCL INFO GPU Direct RDMA Disabled for GPU c1000 / HCA 1 (distance 7 > 6)
g1255:1752304:1752378 [0] NCCL INFO GPU Direct RDMA Disabled for GPU c1000 / HCA 2 (distance 7 > 6)
g1255:1752304:1752378 [0] NCCL INFO GPU Direct RDMA Disabled for GPU c1000 / HCA 3 (distance 7 > 6)
g1255:1752304:1752378 [0] NCCL INFO GPU Direct RDMA Enabled for GPU c1000 / HCA 0 (distance 6 <= 6), read 1
g1255:1752304:1752378 [0] NCCL INFO === System : maxBw 5000.0 totalBw 0.0 ===
g1255:1752304:1752378 [0] NCCL INFO CPU/3 (1/2/4)
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/1
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/0
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/2
g1255:1752304:1752378 [0] NCCL INFO + PCI[24.0] - GPU/C1000 (0)
g1255:1752304:1752378 [0] NCCL INFO + PCI[24.0] - NIC/C5000
g1255:1752304:1752378 [0] NCCL INFO CPU/1 (1/2/4)
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/3
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/0
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/2
g1255:1752304:1752378 [0] NCCL INFO + PCI[24.0] - NIC/CD000
g1255:1752304:1752378 [0] NCCL INFO CPU/0 (1/2/4)
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/3
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/1
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/2
g1255:1752304:1752378 [0] NCCL INFO + PCI[24.0] - NIC/D5000
g1255:1752304:1752378 [0] NCCL INFO CPU/2 (1/2/4)
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/3
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/1
g1255:1752304:1752378 [0] NCCL INFO + SYS[5000.0] - CPU/0
g1255:1752304:1752378 [0] NCCL INFO + PCI[24.0] - NIC/DD000
g1255:1752304:1752378 [0] NCCL INFO ==========================================
g1255:1752304:1752378 [0] NCCL INFO GPU/C1000 :GPU/C1000 (0/5000.000000/LOC) CPU/3 (1/24.000000/PHB) CPU/1 (2/24.000000/SYS) CPU/0 (2/24.000000/SYS) CPU/2 (2/24.000000/SYS) 
g1255:1752304:1752378 [0] NCCL INFO Setting affinity for GPU 0 to ffff0000,00000000,ffff0000,00000000
Fatal Python error: Segmentation fault

Thread 0x000014ab7a743740 (most recent call first):
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3938 in barrier
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 79 in wrapper
  File "<...>/./basic.py", line 11 in Main
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348 in wrapper
  File "<...>/./basic.py", line 18 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special (total: 20)
E0910 11:17:54.554000 22670447675200 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -11) local_rank: 0 (pid: 1752304) of binary: <...>/python_environment/bin/python
Traceback (most recent call last):
  File "<...>/python_environment/bin/torchrun", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>/python_environment/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=========================================================
./basic.py FAILED
---------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
---------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-10_11:17:54
  host      : g1255.hostmgmt2003
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 1752304)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1752304
=========================================================
```

**Comment by etiennemlb** [comment]
The node was also allocated using slurm but I did not use srun to dispatch the work.

**Comment by hongxiayang** [comment]
@etiennemlb If I understand correctly by reading above, the pytorch default librccl is fine, and you only have the crash issue if you used the librccl library from your own build of rccl of a lower version. 

What is the motivation not using the torch's own librccl?

**Comment by hongxiayang** [comment]
How you installed torch==2.4.1+rocm6.1 to your system? Any wheel you used?

**Comment by hongxiayang** [comment]
I still can not reproduce your issue by installing the `pip3 install torch==2.4.1+rocm6.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.1` in my environment (venv, or docker method). I did confirmed that the torch's librccl.so is 2.18 if installing torch using the above command. However, I did not experience the crash when running your script. 


What is your ROCm version? as in /opt/rocm* ?

**Comment by hongxiayang** [comment]
That might be true if you use the docker from rocm. For your case, you seem to use either venv or conda. In that case, it might points to /opt/rocm...
Can you go to your torch/lib (pip show torch) directory, and do 
```
ldd libamdhip64.so
ldd librccl.so
```

And what version is your /opt/rocm points, which rocm version is the version you have problem with?

**Comment by kwen2501** [comment]
@hongxiayang could this issue to be tied to a specific machine topology? bc the segfault seems to be from `ncclTopoCompute`.

In any case, if seems an upgrade of RCCL version would solve the problem. I personally hasn't done that before so digging to see how. If you know a shortcut, can you please let us know? Thank you!

**Comment by hongxiayang** [comment]
@kwen2501 Thanks for comments. I will double check with rccl team to see whether I can get some hints.

**Comment by hongxiayang** [comment]
@etiennemlb Can you try to install the wheel (

```pip3 install torch==2.5.0 --index-url https://download.pytorch.org/whl/test/rocm6.2/```

 to see whether it works for you since rocm6.2 has the newer rccl?  This is to confirm that the new wheel fixed the issue related to your use case.

**Comment by hongxiayang** [comment]
> With torch 2.5.0 and RCCL version 2.20.5+hip6.2 HEAD:45b618a+, the reproducer it worked fine to completion.

Thanks @etiennemlb  for your confirmation. Can we close this issue ?
