### ISSUE TITLE
Torch.tensor() throws "RuntimeError: Overflow when unpacking long" exception?!

### ISSUE THREAD

**Issue by rbelew** [pytorch/pytorch#135628]
### 🐛 Describe the bug

i see this exception mentioned in some older and more exotic contexts but this is as straight-forward as it gets:

```
    import torch

    for package in [torch]: 
        print(package.__name__, package.__version__)
    
    tstList = [10,20,30,40,50]
    tstTensor = torch.tensor(tstList)
    print('tst',type(tstTensor),tstTensor)
    
    tstLongTensor = torch.tensor(tstList,dtype=torch.int64)
    print('long',type(tstLongTensor),tstLongTensor)
    
    tstLng2Tensor = torch.tensor(tstList).type(torch.int64)
    print('long2',type(tstLng2Tensor),tstLng2Tensor) 

    indexedTst = [10239237003504588839, 9921686513378912864, 11901859001352538922, 4316640507316845735, 7162342725099726394, 17494803046312582752]
    idxTensor = torch.tensor(indexedTst)
    print('idx',type(idxTensor),idxTensor)
```
works fine until it's given long ints:

```
torch 2.3.0
tst <class 'torch.Tensor'> tensor([10, 20, 30, 40, 50])
long <class 'torch.Tensor'> tensor([10, 20, 30, 40, 50])
long2 <class 'torch.Tensor'> tensor([10, 20, 30, 40, 50])
Traceback (most recent call last):
  File ".../tstTensor.py", line 33, in <module>
    main()
  File ".../tstTensor.py", line 29, in main
    idxTensor = torch.tensor(indexedTst)
                ^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Overflow when unpacking long
```
version info:
- Python 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ] on darwin
- same exception using device=`cpu` or `mps`

### Versions

PyTorch version: 2.3.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.3.0
[pip3] torchdata==0.8.0
[pip3] torchtext==0.18.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] torchdata                 0.8.0                    pypi_0    pypi
[conda] torchtext                 0.18.0                   pypi_0    pypi

cc @albanD

**Comment by rbelew** [comment]
answered by @ptrblck  https://discuss.pytorch.org/t/torch-tensor-throws-runtimeerror-overflow-when-unpacking-long-exception/209386/2
I needed to use torch.uint64!
`idxTensor = torch.tensor(indexedTst, dtype=torch.uint64)
`
