### ISSUE TITLE
☂️ 40+ MacOS tests were marked flaky recently

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#135885]
### 🐛 Describe the bug

I don't think flaky detection bot is design to mass disable the test, we should try to rootcause what caused flakiness ASAP:
- https://github.com/pytorch/pytorch/issues/135856
- https://github.com/pytorch/pytorch/issues/135855
- https://github.com/pytorch/pytorch/issues/135854
- https://github.com/pytorch/pytorch/issues/135853
- https://github.com/pytorch/pytorch/issues/135852
- https://github.com/pytorch/pytorch/issues/135851
- https://github.com/pytorch/pytorch/issues/135850
- https://github.com/pytorch/pytorch/issues/135849
- https://github.com/pytorch/pytorch/issues/135848
- https://github.com/pytorch/pytorch/issues/135847
- https://github.com/pytorch/pytorch/issues/135846
- https://github.com/pytorch/pytorch/issues/135845
- https://github.com/pytorch/pytorch/issues/135844
- https://github.com/pytorch/pytorch/issues/135843
- https://github.com/pytorch/pytorch/issues/135842
- https://github.com/pytorch/pytorch/issues/135841
- https://github.com/pytorch/pytorch/issues/135840
- https://github.com/pytorch/pytorch/issues/135839
- https://github.com/pytorch/pytorch/issues/135838

### Versions

nightly

**Comment by malfet** [comment]
Failure logs are not really helpful, but looks like compiler simply failed to run, perhaps because machine run out of space, or somebody corrupted the runner:
```
Traceback (most recent call last):
2024-09-11T22:17:54.1822640Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1140, in test_wrapper
2024-09-11T22:17:54.1823360Z     return test(*args, **kwargs)
2024-09-11T22:17:54.1824120Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1409, in only_fn
2024-09-11T22:17:54.1824830Z     return fn(self, *args, **kwargs)
2024-09-11T22:17:54.1825570Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2133, in wrapper
2024-09-11T22:17:54.1826260Z     fn(*args, **kwargs)
2024-09-11T22:17:54.1826980Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1210, in dep_fn
2024-09-11T22:17:54.1827690Z     return fn(slf, *args, **kwargs)
2024-09-11T22:17:54.1828460Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1210, in dep_fn
2024-09-11T22:17:54.1829160Z     return fn(slf, *args, **kwargs)
2024-09-11T22:17:54.1829900Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1526, in wrapper
2024-09-11T22:17:54.1830580Z     fn(*args, **kwargs)
2024-09-11T22:17:54.1831270Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1466, in wrapper
2024-09-11T22:17:54.1831940Z     fn(*args, **kwargs)
2024-09-11T22:17:54.1832610Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/unittest/mock.py", line 1336, in patched
2024-09-11T22:17:54.1833180Z     return func(*newargs, **newkeywargs)
2024-09-11T22:17:54.1833780Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/contextlib.py", line 79, in inner
2024-09-11T22:17:54.1834310Z     return func(*args, **kwds)
2024-09-11T22:17:54.1834930Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/inductor/test_torchinductor_opinfo.py", line 554, in inner
2024-09-11T22:17:54.1835460Z     raise e
2024-09-11T22:17:54.1835970Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/inductor/test_torchinductor_opinfo.py", line 546, in inner
2024-09-11T22:17:54.1836520Z     fn(self, device, dtype, op)
2024-09-11T22:17:54.1837150Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/inductor/test_torchinductor_opinfo.py", line 790, in test_comprehensive
2024-09-11T22:17:54.1837720Z     raise e
2024-09-11T22:17:54.1838280Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/inductor/test_torchinductor_opinfo.py", line 772, in test_comprehensive
2024-09-11T22:17:54.1838860Z     self.check_model(
2024-09-11T22:17:54.1839390Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/inductor/test_torchinductor.py", line 430, in check_model
2024-09-11T22:17:54.1839950Z     actual = run(*example_inputs, **kwargs)
2024-09-11T22:17:54.1840650Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
2024-09-11T22:17:54.1841280Z     return fn(*args, **kwargs)
2024-09-11T22:17:54.1841970Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 1269, in __call__
2024-09-11T22:17:54.1842690Z     return self._torchdynamo_orig_callable(
2024-09-11T22:17:54.1843430Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
2024-09-11T22:17:54.1844120Z     return _compile(
2024-09-11T22:17:54.1844770Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
2024-09-11T22:17:54.1845510Z     guarded_code = compile_inner(code, one_graph, hooks, transform)
2024-09-11T22:17:54.1846340Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
2024-09-11T22:17:54.1847070Z     return _compile_inner(code, one_graph, hooks, transform)
2024-09-11T22:17:54.1847860Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
2024-09-11T22:17:54.1848530Z     return function(*args, **kwargs)
2024-09-11T22:17:54.1849260Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
2024-09-11T22:17:54.1849970Z     out_code = transform_code_object(code, transform)
2024-09-11T22:17:54.1850840Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_10819913966/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
2024-09-11T22:17:54.1851600Z     transformations(instructions, code_options)
```

**Comment by malfet** [comment]
Another failure, that looks like an infra issue:
```
_ TestInductorOpInfoCPU.test_comprehensive_nn_functional_upsample_nearest_cpu_float64 _
Traceback (most recent call last):
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/_inductor/cpp_builder.py", line 331, in _run_compile_cmd
    status = subprocess.check_output(args=cmd, cwd=cwd, stderr=subprocess.STDOUT)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['clang++', '/var/folders/bm/fnn3xd1d39lcpbxrgwys1c140000gn/T/tmp93vin8ix/gh/cghxi2wijpeluoppwmlknko2auexiu4jknwsknv42d3tgveguz3c.cpp', '-D', 'TORCH_INDUCTOR_CPP_WRAPPER', '-D', 'C10_USING_CUSTOM_GENERATED_MACROS', '-D', 'CPU_CAPABILITY_NEON', '-D', 'AT_BUILD_ARM_VEC256_WITH_SLEEF', '-shared', '-fPIC', '-undefined', 'dynamic_lookup', '-O3', '-DNDEBUG', '-ffast-math', '-fno-finite-math-only', '-fno-unsafe-math-optimizations', '-ffp-contract=off', '-Wall', '-std=c++17', '-Wno-unused-variable', '-Wno-unknown-pragmas', '-Werror=ignored-optimization-argument', '-Xclang', '-fopenmp', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/include/python3.9', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/include/python3.9', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include/torch/csrc/api/include', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include/TH', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include/THC', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/include', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include/torch/csrc/api/include', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include/TH', '-I/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/include/THC', '-D_GLIBCXX_USE_CXX11_ABI=0', '-lc10', '-lomp', '-L/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib', '-L/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/lib', '-L/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/lib', '-L/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib', '-L/Users/ec2-user/runner/_work/_temp/conda_environment_10822894530/lib/python3.9/site-packages/torch/lib', '-o', '/var/folders/bm/fnn3xd1d39lcpbxrgwys1c140000gn/T/tmp93vin8ix/gh/cghxi2wijpeluoppwmlknko2auexiu4jknwsknv42d3tgveguz3c.so']' died with <Signals.SIGABRT: 6>.
```

**Comment by malfet** [comment]
@izaitsevfb by the way, this is a perfect example where log detection/classifier misfires, i.e. the actual test that caused failure/resources exhaustion:
```
2024-09-12T17:29:55.9079010Z inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCPU::test_comprehensive_reciprocal_cpu_int32 OMP: Error #179: Function pthread_key_create failed:
2024-09-12T17:29:55.9079710Z OMP: System error #35: Resource temporarily unavailable
2024-09-12T17:29:55.9080030Z Fatal Python error: Aborted
2024-09-12T17:29:55.9080190Z 
2024-09-12T17:29:55.9080350Z Current thread 0x000000031cbc3000 (most recent call first):
```
Which causes number of tests to fail later on

**Comment by malfet** [comment]
I wonder if some changes in inductor/multiprocessing create a bunch of zombies, as MacOS has limit of 2666 processes per user by default:
```
 ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2666
-n: file descriptors                256
```

**Comment by hvaara** [comment]
> I wonder if some changes in inductor/multiprocessing create a bunch of zombies, as MacOS has limit of 2666 processes per user by default:
> 
> ```
>  ulimit -a
> -t: cpu time (seconds)              unlimited
> -f: file size (blocks)              unlimited
> -d: data seg size (kbytes)          unlimited
> -s: stack size (kbytes)             8176
> -c: core file size (blocks)         0
> -v: address space (kbytes)          unlimited
> -l: locked-in-memory size (kbytes)  unlimited
> -u: processes                       2666
> -n: file descriptors                256
> ```

Are these numbers from the test machine itself? `processes` at 2666 seems low. If running tests in parallel I can see this going over?

What's the output of `ulimit -Ha`?

**Comment by malfet** [comment]
> Are these numbers from the test machine itself? `processes` at 2666 seems low. If running tests in parallel I can see this going over?
Can you elaborate why do you it's the case? cpp_inductor has a worker pool, which is limited by number of CPU cores, so 3k processes might be low for generic use case, but for machine that only runs unit-tests this should be sufficient, unless there is a resource leak

> What's the output of `ulimit -Ha`?
Will try to get that one later, but unless someone is messing with those machines, I guess almost the hard limits should all be unlimited.

**Comment by malfet** [comment]
Ok, even after increasing number of open file handles, this still happens for one of the closed issues, see
https://hud.pytorch.org/flakytest?name=test_comprehensive_nn_functional_pixel_unshuffle_cpu_bool&suite=TestInductorOpInfoCPU&limit=100 / https://ossci-raw-job-status.s3.amazonaws.com/log/30279858465 
```
2024-09-17T23:55:19.9595800Z inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCPU::test_comprehensive_slice_scatter_cpu_float32 OMP: Error #179: Function pthread_key_create failed:
2024-09-17T23:55:19.9596600Z OMP: System error #35: Resource temporarily unavailable
2024-09-17T23:55:19.9596960Z Fatal Python error: Aborted
```

**Comment by hvaara** [comment]
> > Are these numbers from the test machine itself? `processes` at 2666 seems low. If running tests in parallel I can see this going over?
> 
> Can you elaborate why do you it's the case? cpp_inductor has a worker pool, which is limited by number of CPU cores, so 3k processes might be low for generic use case, but for machine that only runs unit-tests this should be sufficient, unless there is a resource leak

I was thinking maybe they we would go over the limit if tests are ran in parallel. I don't know how the thread pool is configured or how many jobs run simultaneously. Is it plausible we'd go over in this case?

Was there a lot of tests enabled recently? I vaguely remember reading something like this a while ago, but I don't know if it's relevant to MPS. Does PyTorch have something similar to testgrid (eg. https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit). It would help with exploring this hypothesis. What I'd like to check is if there was a bunch of tests added, did they start failing immediately or were they initially green and then started failing later on.

By the way, the defaults on my machine is

```bash
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       10666
-n: file descriptors                256

$ ulimit -Ha
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             65520
-c: core file size (blocks)         unlimited
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       10666
-n: file descriptors                unlimited
```

**Comment by hvaara** [comment]
Looks like this got resolved and the issues were closed automatically because the tests started passing again.

Just curious, do you know what was wrong or what changed? Great to see that it's now working again.

**Comment by malfet** [comment]
Closing (should have been done a while back)
