### ISSUE TITLE
[AOT Autograd][functionalization] mutations on input view of same dtype fail functionalization checks

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#136064]
### 🐛 Describe the bug

If you have some input to a function `inp`, and try to do `inp.view(inp.dtype).copy_(inp2)`, the functionalized graph generated in aot autograd isn't actually functionalized; and it fails some assertions.

repro:

```python
import torch

def fn(x, y):
    view = x.view(torch.float32)
    view.copy_(y)

def get_inp():
    x = torch.zeros(4, 4, device="cuda")
    y = torch.ones(4, 4, device="cuda")
    return x, y

xc, yc = get_inp()
xe, ye = get_inp()
fn(xe, ye)
torch.compile(fn)(xc, yc)
assert torch.all(xe == xc)
```

error:
```
Traceback (most recent call last):
  File "/home/dberard/local/scripts/horace_repro_isolate.py", line 15, in <module>
    torch.compile(fn)(xc, yc)
  File "/home/dberard/local/pytorch/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 1278, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 1073, in __call__
    result = self._inner_convert(
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/dberard/local/pytorch/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/dberard/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 634, in transform
    tracer.run()
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2796, in run
    super().run()
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
    self._return(inst)
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2972, in _return
    self.output.compile_subgraph(
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1142, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/dberard/local/pytorch/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/dberard/local/pytorch/torch/__init__.py", line 2235, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/dberard/local/pytorch/torch/_inductor/compile_fx.py", line 1525, in compile_fx
    return aot_autograd(
  File "/home/dberard/local/pytorch/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 1071, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 1056, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 759, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/home/dberard/local/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 140, in aot_dispatch_base
    fw_module, updated_flat_args, maybe_subclass_meta = aot_dispatch_base_graph(  # type: ignore[misc]
  File "/home/dberard/local/pytorch/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 186, in aot_dispatch_base_graph
    copy_count = assert_functional_graph(fw_module.graph)
  File "/home/dberard/local/pytorch/torch/_functorch/_aot_autograd/functional_utils.py", line 427, in assert_functional_graph
    n.args[0] in placeholders
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: n=copy_, n.args[0]=view_1, placeholders={arg0_1, arg1_1}, graph=graph():
    %arg0_1 : [num_users=1] = placeholder[target=arg0_1]
    %arg1_1 : [num_users=1] = placeholder[target=arg1_1]
    %view : [num_users=2] = call_function[target=torch.ops.aten.view.dtype](args = (%arg0_1, torch.float32), kwargs = {})
    %alias : [num_users=1] = call_function[target=torch.ops.aten.alias.default](args = (%view,), kwargs = {})
    %alias_1 : [num_users=1] = call_function[target=torch.ops.aten.alias.default](args = (%alias,), kwargs = {})
    %copy : [num_users=1] = call_function[target=torch.ops.aten.copy.default](args = (%alias_1, %arg1_1), kwargs = {})
    %view_1 : [num_users=1] = call_function[target=torch.ops.aten.view.dtype](args = (%view, torch.float32), kwargs = {})
    %view_2 : [num_users=1] = call_function[target=torch.ops.aten.view.dtype](args = (%copy, torch.float32), kwargs = {})
    %view_3 : [num_users=2] = call_function[target=torch.ops.aten.view.dtype](args = (%view_2, torch.float32), kwargs = {})
    %alias_2 : [num_users=0] = call_function[target=torch.ops.aten.alias.default](args = (%view_3,), kwargs = {})
    %copy_ : [num_users=0] = call_function[target=torch.ops.aten.copy_.default](args = (%view_1, %view_3), kwargs = {})
    return ()
```

### Versions

viable/strict ~sep 11, H100

cc @bdhirsh @ezyang @chauhang @penguinwu @zou3519 @Chillee

**Comment by bdhirsh** [comment]
interestingly this doesn't repro if I tweak the view in this repro script to **actually** be cross-dtype:
```
# inpts are 
def fn(x, y):
    view = x.view(torch.int32)
    view.copy_(y)
```

**Comment by bdhirsh** [comment]
The fix was kind of interesting - I added more details in the PR description here https://github.com/pytorch/pytorch/pull/136074
