### ISSUE TITLE
If mark_dynamic fails (Not all values of RelaxedUnspecConstraint are valid) due to specialization, error message should print where specialization came from

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#136002]
### 🐛 Describe the bug

Self explanatory

internal xref: https://fb.workplace.com/groups/1075192433118967/posts/1502206057084267

### Versions

main

**Comment by bdhirsh** [comment]
I guess one annoying thing is that there might not be a single "culprit" guard - there might have been a series of guards that cause a specialization when combined (e.g. `x > 5 and x <= 6`) - so for full generality we'd want to print every guard generated on the symbol and its stacktrace?

**Comment by ezyang** [comment]
Here's a minimal repro you can use to see if you fixed it:

```
import torch

@torch.compile()
def f(x):
    if x.size(0) == 5:  # REPORT ME
        return x * 2
    else:
        return x + 1

x = torch.randn(5)
torch._dynamo.mark_dynamic(x, 0)
f(x)
```

This currently errors like

```
E0913 08:34:30.532000 1447785 torch/_guards.py:285] [0/0]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/ca.py", line 12, in <module>
    f(x)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 1278, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 1073, in __call__
    result = self._inner_convert(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/c/pytorch/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/convert_frame.py", line 796, in _compile_inner
    check_fn = CheckFunctionManager(
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/guards.py", line 2269, in __init__
    guard.create(builder)
  File "/data/users/ezyang/c/pytorch/torch/_guards.py", line 281, in create
    return self.create_fn(builder, self)
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/guards.py", line 1844, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/data/users/ezyang/c/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4194, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['x'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of RelaxedUnspecConstraint(L['x'].size()[0]) are valid because L['x'].size()[0] was inferred to be a constant (5).


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

Declare victory when the exact line number "REPORT ME" shows up in the error message

**Comment by ezyang** [comment]
@bdhirsh Yeah, I think printing every guard that involved the symbol is a good compromise.

**Comment by kevomaco** [comment]
I'd like to take a stab at this.
