### ISSUE TITLE
test_dist_broadcast_coalesced_nccl timeout on CI

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#13618]
```
Nov 06 05:00:37 ======================================================================
Nov 06 05:00:37 ERROR: test_dist_broadcast_coalesced_nccl (__main__.DistributedDataParallelTest)
Nov 06 05:00:37 ----------------------------------------------------------------------
Nov 06 05:00:37 Traceback (most recent call last):
Nov 06 05:00:37   File "test_c10d.py", line 349, in wrapper
Nov 06 05:00:37     self._join_processes(fn)
Nov 06 05:00:37   File "test_c10d.py", line 395, in _join_processes
Nov 06 05:00:37     self._check_return_codes(elapsed_time)
Nov 06 05:00:37   File "test_c10d.py", line 405, in _check_return_codes
Nov 06 05:00:37     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Nov 06 05:00:37 RuntimeError: Process 0 terminated or timed out after 30.030466556549072 seconds
```

**Comment by mruberry** [comment]
Closing due to age
