### ISSUE TITLE
[Inductor][FP8] AOTInductor appears to ignore a transpose in `test_fp8_view_of_param_non_abi_compatible_cuda`

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#136209]
### 🐛 Describe the bug

`python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCuda.test_fp8_view_of_param_non_abi_compatible_cuda` fails with 
```
Error: mat1 and mat2 shapes cannot be multiplied (16x32 and 16x16)
Exception raised from _scaled_mm_out_cuda at /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Blas.cpp:1000 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xac (0x7f674d2b448c in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f674d258a79 in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #2: at::native::_scaled_mm_out_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<c10::ScalarType>, bool, at::Tensor&) + 0x932 (0x7f6750d29272 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #3: at::native::_scaled_mm_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<c10::ScalarType>, bool) + 0xe8 (0x7f6750d29fa8 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x36c44e6 (0x7f67509e94e6 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x385a905 (0x7f6750b7f905 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x4f9c935 (0x7f677e82d935 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #7: at::_ops::_scaled_mm::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<c10::ScalarType>, bool) + 0x431 (0x7f677bdb8671 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #8: torch::aot_inductor::AOTInductorModel::run_impl(AtenTensorOpaque**, AtenTensorOpaque**, CUstream_st*, AOTIProxyExecutorOpaque*) + 0x3c9 (0x7f63e9c46c39 in /tmp/tmpc6es9_y7/cc2ki73moqt2d3knlnvifbg4u2iray5kurdhfp43gahixqrsl2zk/cghubrklhhsaxpykzudjqjs5ooon6pi7h52k3egi3f5wxbndodti.so)
frame #9: torch::aot_inductor::AOTInductorModelContainer::run(AtenTensorOpaque**, AtenTensorOpaque**, CUstream_st*, AOTIProxyExecutorOpaque*) + 0xf8 (0x7f63e9c56c58 in /tmp/tmpc6es9_y7/cc2ki73moqt2d3knlnvifbg4u2iray5kurdhfp43gahixqrsl2zk/cghubrklhhsaxpykzudjqjs5ooon6pi7h52k3egi3f5wxbndodti.so)
frame #10: AOTInductorModelContainerRun + 0x85 (0x7f63e9c47be5 in /tmp/tmpc6es9_y7/cc2ki73moqt2d3knlnvifbg4u2iray5kurdhfp43gahixqrsl2zk/cghubrklhhsaxpykzudjqjs5ooon6pi7h52k3egi3f5wxbndodti.so)
frame #11: torch::inductor::AOTIModelContainerRunner::run(std::vector<at::Tensor, std::allocator<at::Tensor> >&, AOTInductorStreamOpaque*) + 0x114 (0x7f677e8a0d54 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #12: torch::inductor::AOTIModelContainerRunnerCuda::run(std::vector<at::Tensor, std::allocator<at::Tensor> >&) + 0x51 (0x7f6750dac1e1 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #13: <unknown function> + 0x927d8d (0x7f6787194d8d in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x4a473f (0x7f6786d1173f in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
<omitting python frames>

inductor [('extern_calls', 2)]
stats [('calls_captured', 2), ('unique_graphs', 1)]
E
======================================================================
ERROR: test_fp8_view_of_param_non_abi_compatible_cuda (__main__.AOTInductorTestNonABICompatibleCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2979, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/inductor/test_torchinductor.py", line 11492, in new_test
    return value(self)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1751, in wrapper
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/inductor/test_aot_inductor.py", line 807, in test_fp8_view_of_param
    self.check_model(
  File "/opt/pytorch/pytorch/test/inductor/test_aot_inductor.py", line 124, in check_model
    actual = AOTIRunnerUtil.run(
  File "/opt/pytorch/pytorch/test/inductor/test_aot_inductor_utils.py", line 131, in run
    return optimized(*example_inputs)
  File "/opt/pytorch/pytorch/torch/_export/__init__.py", line 314, in optimized
    flat_outputs = runner.run(flat_inputs)  # type: ignore[attr-defined]
RuntimeError: run_func_( container_handle_, input_handles.data(), input_handles.size(), output_handles.data(), output_handles.size(), cuda_stream_handle, proxy_executor_handle_) API call failed at /opt/pytorch/pytorch/torch/csrc/inductor/aoti_runner/model_container_runner.cpp, line 111

To execute this test, run the following from the base repo dir:
    python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCuda.test_fp8_view_of_param_non_abi_compatible_cuda

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 10.757s

FAILED (errors=1)
```
which seems to suggest that the `weight.T` which seems to happen in eager in the test model definition is ignored in the inductor codepath

### Versions

nightly build from last day or so

cc @ptrblck @msaroufim @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by avikchaudhuri** [comment]
@desertfire can you take a look?
