### ISSUE TITLE
pull ciflow failing - CI Internal Server Errror for Huggingface URL in linux-focal-py3.9-clang10-onnx / test

### ISSUE THREAD

**Issue by robert-hardwick** [pytorch/pytorch#136423]
## Current Status
ongoing

## Error looks like

[linux-focal-py3.9-clang10-onnx / test](https://github.com/pytorch/pytorch/actions/runs/10974413106/job/30473119223?pr=136315#logs)

```
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/YituTech/conv-bert-base/resolve/main/config.json
```

## Incident timeline (all times pacific)
Seen 21 Sep 2024

## User impact
Prevents PR merging into main due to failing test

## Root cause
Hugging face url appears to be returning 500 internal server error. 

## Mitigation
Unknown

## Prevention/followups
Don't rely on unreliable external services for merge blocking tests.

**Comment by robert-hardwick** [comment]
Looks like it might not be happening anymore. Will confirm by re-running pull tests and then close.

**Comment by robert-hardwick** [comment]
Closing issue as tests pass now.
