### ISSUE TITLE
[TorchScript] typing_extensions.deprecated doesn't work

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#136654]
### 🐛 Describe the bug

From S441024

repro

```python
import torch

from typing_extensions import deprecated

@deprecated("asdf")
def fn():
    return torch.compiler.is_compiling()

torch.jit.script(fn)
```

error:

```
Traceback (most recent call last):
  File "/data/users/dberard/scripts/torchscript_deprecated.py", line 9, in <module>
    torch.jit.script(fn)
  File "/data/users/dberard/pytorch/torch/jit/_script.py", line 1429, in script
    ret = _script_impl(
          ^^^^^^^^^^^^^
  File "/data/users/dberard/pytorch/torch/jit/_script.py", line 1205, in _script_impl
    fn = torch._C._jit_script_compile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError:
undefined value torch:
  File "/home/dberard/.conda/envs/pytorch311/lib/python3.11/site-packages/typing_extensions.py", line 7

@deprecated("asdf")
def fn():
    return torch.compiler.is_compiling()
           ~~~~~ <--- HERE
```

### Versions

viable/strict, CPU build

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
