### ISSUE TITLE
Onnx scaled_dot_product_attention does not allow to export model

### ISSUE THREAD

**Issue by doloresgarcia** [pytorch/pytorch#136756]
### 🐛 Describe the bug

The model is converted with dynamo and opset 18, torch nightly, and most recent onnx and onnxscript, 
# PyTorch ONNX Conversion Report

```
✅ Obtain model graph with `torch.export.export`
⚪ Obtain model graph with `torch.export.export(..., strict=False)`
⚪ Obtain model graph with `torch.jit.trace`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```
```
RuntimeError: Internal error: pybind11::error_already_set called while Python error indicator not set.

While executing %scaled_dot_product_attention : [num_users=2] = call_function[target=torch.ops.aten.scaled_dot_product_attention.default](args = (%expand, %expand_1, %expand_2), kwargs = {})
Original traceback:
  File "src/models/Gatr_pf_e_tau_onnx2.py", line 162, in forward
    embedded_outputs, _ = self.gatr(
  File "PID_GNN/src/gatr_v111/nets/gatr.py", line 158, in forward
    h_mv, h_s = block(
  File "PID_GNN/src/gatr_v111/layers/gatr_block.py", line 126, in forward
    h_mv, h_s = self.attention(
  File "/gatr_v111/layers/attention/self_attention.py", line 135, in forward
    h_mv, h_s = self.attention(q_mv, k_mv, v_mv, q_s, k_s, v_s, attention_mask=None)
  File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/gatr_v111/layers/attention/attention.py", line 83, in forward
    h_mv, h_s = self.geometric_attention(
  File "src/gatr_v111/primitives/attention.py", line 522, in forward
    v_out = scaled_dot_product_attention(q, k, v) # attn_mask=attn_mask)

```

the markdown is:
[onnx_export_2024-09-26_15-53-37-082571_conversion.md](https://github.com/user-attachments/files/17149851/onnx_export_2024-09-26_15-53-37-082571_conversion.md)

### Versions

onnxscript 0.1.0.dev20240925
torch-nigthly
onnx

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by justinchuby** [comment]
This is happening during the decomp step @angelayi @tugsbayasgalan 


```pytb


Traceback (most recent call last):

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/onnx/_internal/exporter/_core.py", line 1089, in export
decomposed_program = _prepare_exported_program_for_export(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/onnx/_internal/exporter/_core.py", line 727, in _prepare_exported_program_for_export
exported_program = _fx_passes.decompose_with_registry(exported_program, registry)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/onnx/_internal/exporter/_fx_passes.py", line 20, in decompose_with_registry
return exported_program.run_decompositions(decomp_table)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 114, in wrapper
return fn(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 1080, in run_decompositions
return _decompose_exported_program(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 628, in _decompose_exported_program
gm, new_graph_signature = _decompose_and_get_gm_with_new_signature_constants(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 421, in _decompose_and_get_gm_with_new_signature_constants
gm, graph_signature = aot_export_module(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1255, in aot_export_module
fx_g, metadata, in_spec, out_spec = _aot_export_function(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1489, in _aot_export_function
fx_g, meta = create_aot_dispatcher_function(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 524, in create_aot_dispatcher_function
return _create_aot_dispatcher_function(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 625, in _create_aot_dispatcher_function
fw_metadata = run_functionalized_fw_and_collect_metadata(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 173, in inner
flat_f_outs = f(*flat_f_args)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 182, in flat_fn
tree_out = fn(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 859, in functional_call
out = PropagateUnbackedSymInts(mod).run(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/fx/interpreter.py", line 146, in run
self.env[node] = self.run_node(node)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5631, in run_node
result = super().run_node(n)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/fx/interpreter.py", line 203, in run_node
return getattr(self, n.op)(n.target, args, kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/fx/interpreter.py", line 275, in call_function
return target(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_ops.py", line 720, in __call__
return self._op(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_higher_order_ops/utils.py", line 64, in inner
return autograd_not_implemented_inner(op, deferred_error, *args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_higher_order_ops/utils.py", line 37, in autograd_not_implemented_inner
result = operator(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_ops.py", line 720, in __call__
return self._op(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py", line 535, in __torch_dispatch__
outs_unwrapped = func._op_dk(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/utils/_stats.py", line 21, in wrapper
return fn(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1241, in __torch_dispatch__
return self.dispatch(func, types, args, kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1695, in dispatch
return self._cached_dispatch_impl(func, types, args, kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1351, in _cached_dispatch_impl
output = self._dispatch_impl(func, types, args, kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2042, in _dispatch_impl
r = func(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/_ops.py", line 720, in __call__
return self._op(*args, **kwargs)

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 152, in _register_cia_to_meta
return kernel._op_dk(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 152, in _register_cia_to_meta
return kernel._op_dk(

File "/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/torch/export/exported_program.py", line 152, in _register_cia_to_meta
return kernel._op_dk(

RuntimeError: Internal error: pybind11::error_already_set called while Python error indicator not set.

While executing %scaled_dot_product_attention : [num_users=2] = call_function[target=torch.ops.aten.scaled_dot_product_attention.default](args = (%expand, %expand_1, %expand_2), kwargs = {})
Original traceback:
File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/models/Gatr_pf_e_tau_onnx2.py", line 162, in forward
embedded_outputs, _ = self.gatr(
File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/gatr_v111/nets/gatr.py", line 158, in forward
h_mv, h_s = block(
File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/gatr_v111/layers/gatr_block.py", line 126, in forward
h_mv, h_s = self.attention(
File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/gatr_v111/layers/attention/self_attention.py", line 135, in forward
h_mv, h_s = self.attention(q_mv, k_mv, v_mv, q_s, k_s, v_s, attention_mask=None)
File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/gatr_v111/layers/attention/attention.py", line 83, in forward
h_mv, h_s = self.geometric_attention(
File "/afs/cern.ch/work/m/mgarciam/private/PID_GNN/src/gatr_v111/primitives/attention.py", line 522, in forward
v_out = scaled_dot_product_attention(q, k, v) # attn_mask=attn_mask)


```

**Comment by doloresgarcia** [comment]
as a note, this is with dynamic axis and the problem is not there if the input is fixed. I also tried with pytorch 2.4 which gives the warning:  `UserWarning: Specified dynamic axes is not supported for dynamo export at the moment.`

**Comment by tugsbayasgalan** [comment]
Yup! Sound like recent bug. Can I have repro instructions?

**Comment by tugsbayasgalan** [comment]
Actually can I try it on latest master, this might have been resolved?

**Comment by exclamaforte** [comment]
Closing, reopen with reproduction if necessary.
