### ISSUE TITLE
iter a dataloader and then finish, get this error

### ISSUE THREAD

**Issue by PathricLee** [pytorch/pytorch#13670]
when i iter a dataloader,  the code like this
`
self.iters[name] = iter(dataloader)
`
and then just finish the python program
`sys.exit()`
then i get the error

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fe763ece898>>
Traceback (most recent call last):
  File "/home/work/chenchaoxing/tools/python/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
  File "/home/work/chenchaoxing/tools/python/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
  File "/home/work/chenchaoxing/tools/python/python36/lib/python3.6/multiprocessing/queues.py", line 337, in get
AttributeError: Can't get attribute '_rebuild_tensor_v2' on None
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fe75885cef0>>
Traceback (most recent call last):
  File "/home/work/chenchaoxing/tools/python/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
  File "/home/work/chenchaoxing/tools/python/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
  File "/home/work/chenchaoxing/tools/python/python36/lib/python3.6/multiprocessing/queues.py", line 337, in get
AttributeError: Can't get attribute '_rebuild_tensor_v2' on None

**Comment by SsnL** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/12700. Please reopen if you can reproduce on a nightly.
