### ISSUE TITLE
[Dynamo] "fill_out" not implemented for 'Float8_e4m3fn'.  (unable to use torch.use_deterministic_algorithms(True)) with FP8 and compile

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#137160]
### 🐛 Describe the bug

In order to ensure deterministic runs, we want to set:
torch.use_deterministic_algorithms(True)

However, if this is used with torch.compile and while using FP8...then receive:
~~~
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
  RuntimeError: "fill_out" not implemented for 'Float8_e4m3fn'
~~~
This may be a torch.ao issue in terms of who should fix, but filing here for now. 

To reproduce:
Use torchtitan.
1 - Set torch.use_deterministic_algorithms(True) in utils.set_determinism or else at the start of main in train.py
2 - set compile=True, and enable FP8 in the toml:

[float8]
enable_float8_linear = true
Run and see the crash as below. 

Full stack trace:
~~~
traceback : Traceback (most recent call last):
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
      return f(*args, **kwargs)
    File "/data/users/less/local/torchtitan/train.py", line 300, in main
      pred = model(input_ids)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
      return inner()
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
      result = forward_call(*args, **kwargs)
    File "/data/users/less/local/torchtitan/torchtitan/models/llama/model.py", line 439, in forward
      h = layer(h, self.freqs_cis)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
      return inner()
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
      result = forward_call(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
      return fn(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1298, in __call__
      return self._torchdynamo_orig_callable(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 530, in __call__
      return _compile(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 933, in _compile
      guarded_code = compile_inner(code, one_graph, hooks, transform)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 675, in compile_inner
      return _compile_inner(code, one_graph, hooks, transform)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
      return function(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 708, in _compile_inner
      out_code = transform_code_object(code, transform)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
      transformations(instructions, code_options)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 220, in _fn
      return fn(*args, **kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 643, in transform
      tracer.run()
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2776, in run
      super().run()
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 979, in run
      while self.step():
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 891, in step
      self.dispatch_table[inst.opcode](self, inst)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2967, in RETURN_VALUE
      self._return(inst)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2952, in _return
      self.output.compile_subgraph(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1117, in compile_subgraph
      self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
      compiled_fn = self.call_user_compiler(gm)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
      return self._call_user_compiler(gm)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
      raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
      compiled_fn = compiler_fn(gm, self.example_inputs())
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
      compiled_gm = compiler_fn(gm, example_inputs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
      compiled_gm = compiler_fn(gm, example_inputs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/__init__.py", line 2235, in __call__
      return compile_fx(model_, inputs_, config_patches=self.config)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1545, in compile_fx
      return aot_autograd(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
      cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1080, in aot_module_simplified
      compiled_fn = dispatch_and_compile()
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1065, in dispatch_and_compile
      compiled_fn, _ = create_aot_dispatcher_function(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 524, in create_aot_dispatcher_function
      return _create_aot_dispatcher_function(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 761, in _create_aot_dispatcher_function
      compiled_fn, fw_metadata = compiler_fn(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 586, in aot_dispatch_autograd
      compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1371, in fw_compiler_base
      return _fw_compiler_base(model, example_inputs, is_inference)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1442, in _fw_compiler_base
      return inner_compile(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 460, in compile_fx_inner
      return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
      inner_compiled_fn = compiler_fn(gm, example_inputs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 646, in _compile_fx_inner
      compiled_graph = FxGraphCache.load(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1427, in load
      compiled_graph = compile_fx_fn(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 555, in codegen_and_compile
      compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 864, in fx_codegen_and_compile
      num_bytes, nodes_num_elem, node_runtimes = graph.count_bytes()
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1858, in count_bytes
      num_bytes = node.get_read_write_buffers_sizes()
    File "<string>", line 5, in get_read_write_buffers_sizes_cache_on_self
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 615, in get_read_write_buffers_sizes
      node_bytes += get_buf_bytes(buf)
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 611, in get_buf_bytes
      return get_dtype_size(buf.get_dtype()) * min(
    File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_inductor/utils.py", line 861, in get_dtype_size
      return torch.empty((), dtype=dtype).element_size()
  torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
  RuntimeError: "fill_out" not implemented for 'Float8_e4m3fn'
  
  Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
  
  
  You can suppress this exception and fall back to eager by setting:
      import torch._dynamo
      torch._dynamo.config.suppress_errors = True
~~~
  

### Versions

PyTorch version: 2.6.0.dev20240925+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.5.0 20240719 (Red Hat 11.5.0-2)
Clang version: 18.1.8 (CentOS 18.1.8-3.el9)
CMake version: version 3.30.2
Libc version: glibc-2.34

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk21_zion_12633_g4db063a1bcb5-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100
GPU 4: NVIDIA H100
GPU 5: NVIDIA H100
GPU 6: NVIDIA H100
GPU 7: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.9.2
/usr/lib64/libcudnn_adv_infer.so.8.9.2
/usr/lib64/libcudnn_adv_train.so.8.9.2
/usr/lib64/libcudnn_cnn_infer.so.8.9.2
/usr/lib64/libcudnn_cnn_train.so.8.9.2
/usr/lib64/libcudnn_ops_infer.so.8.9.2
/usr/lib64/libcudnn_ops_train.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.2
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          384
On-line CPU(s) list:             0-383
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              2
Core(s) per socket:              96
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU(s) scaling MHz:              100%
CPU max MHz:                     2400.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4792.76
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                  AMD-V
L1d cache:                       6 MiB (192 instances)
L1i cache:                       6 MiB (192 instances)
L2 cache:                        192 MiB (192 instances)
L3 cache:                        768 MiB (24 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-95,192-287
NUMA node1 CPU(s):               96-191,288-383
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable, IBPB: conditional, IBRS_FW, STIBP: always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-triton==3.1.0+5fe38ffd73
[pip3] torch==2.6.0.dev20240925+cu121
[pip3] torchao==0.5.0
[pip3] torchdata==0.8.0
[pip3] torchtune==0.0.0
[pip3] torchvision==0.20.0.dev20240925+cu121
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] pytorch-triton            3.1.0+5fe38ffd73          pypi_0    pypi
[conda] torch                     2.6.0.dev20240925+cu121          pypi_0    pypi
[conda] torchao                   0.5.0                    pypi_0    pypi
[conda] torchdata                 0.8.0                    pypi_0    pypi
[conda] torchtune                 0.0.0                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240925+cu121          pypi_0    pypi

cc @ezyang @chauhang @penguinwu

**Comment by eellison** [comment]
This is part of the same set of issues is fixing https://github.com/pytorch/pytorch/pull/128780

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/137341 fixes this on my local checkout of PyTorch + torchtitan

**Comment by weifengpy** [comment]
> #137341 fixes this on my local checkout of PyTorch + torchtitan

verified the fix indeed worked! closing the issue for now
