### ISSUE TITLE
torch-0.4.1-cp35-cp35m-linux_x86_64.whl bug in cuda.set_device()

### ISSUE THREAD

**Issue by davidnewman02** [pytorch/pytorch#13718]
## 🐛 Bug

I installed torch version: `torch-0.4.1-cp35-cp35m-linux_x86_64.whl` in a venv from http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl

I then tried to set my gpu device:
```
>>> import torch 
>>> torch.cuda.set_device(0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/vnx-home/dnewman/tmp/torch_bug/lib/python3.5/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```
I don't get this bug when I install the default pip package: torch-0.4.1-cp35-cp35m-manylinux1_x86_64.whl 

## To Reproduce
```
virtualenv -p python3 torch_bug
. torch_bug/bin/activate
pip install numpy>=1.9.0
pip install --upgrade http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl
python -c "import torch; torch.cuda.set_device(0)"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/vnx-home/dnewman/tmp/torch_bug/lib/python3.5/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```
## Expected behavior

`torch.cuda.set_device()` function can be found

## Environment

 - PyTorch Version: 0.4.1  (specifically: http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl)
 - OS: Ubuntu 16.04.5 LTS
- GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CMake version: version 3.11.0
 - Python version: 3.5.2

**Comment by davidnewman02** [comment]
I think I've been foolish and tried to detect a GPU device from a CPU build - oops!
