### ISSUE TITLE
pyTorch installation in conflict with libTorch

### ISSUE THREAD

**Issue by xkzl** [pytorch/pytorch#137247]
### 🐛 Describe the bug

I have setup a minimal environment running PyTorch
```
conda create -n pytorch-env python=3.10
conda activate pytorch-env
pip install torch torchvision torchaudio
```

On the other hand, I also compiled for different purpose libTorch 2.3.1 (without CUDA options) on my MacOS.
If I link my configuration `PATH` and `DYLD_LIBRARY_PATH` to the path `/path/to/libtorch/2.3.1`, I get an issue running PyTorch.

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcomeyer/.conda/envs/starformer/lib/python3.10/site-packages/torch/__init__.py", line 1694, in <module>
    _C._initExtension(_manager_path())
  File "/Users/marcomeyer/.conda/envs/starformer/lib/python3.10/site-packages/torch/cuda/__init__.py", line 267, in <module>
    OutOfMemoryError = torch._C.OutOfMemoryError
AttributeError: module 'torch._C' has no attribute 'OutOfMemoryError'
```

I believe this is due to the difference between PyTorch 2.4.1 and libTorch 2.3.1, but how to make sure PyTorch is not using my custom libTorch ? Thank you

### Versions

```
Collecting environment information...
PyTorch version: 2.4.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.0 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.22.7)
CMake version: version 3.30.4
Libc version: N/A

Python version: 3.10.15 | packaged by conda-forge | (main, Sep 30 2024, 17:48:38) [Clang 17.0.6 ] (64-bit runtime)
Python platform: macOS-15.0-arm64-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==7.1.1
[pip3] flake8-black==0.3.6
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.3.0
[pip3] torch==2.4.1
[pip3] torchaudio==2.4.1
[pip3] torchmetrics==1.4.0.post0
[pip3] torchvision==0.19.1
[conda] libtorch                  2.4.0           cpu_generic_h8523454_1    conda-forge
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.26.4          py310h3b2db8e_0  
[conda] numpy-base                1.26.4          py310ha9811e2_0  
[conda] pytorch-lightning         2.3.0           py310hca03da5_0  
[conda] torch                     2.4.1                    pypi_0    pypi
[conda] torchaudio                2.4.1                    pypi_0    pypi
[conda] torchmetrics              1.4.0.post0     py310hca03da5_0  
[conda] torchvision               0.19.1                   pypi_0    pypi
```

**Comment by bdhirsh** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions:[ https://discuss.pytorch.org/](https://discuss.pytorch.org/)

**Comment by xkzl** [comment]
It looks to me like a bug that PyTorch is not prioritizing its own implementations but link to any user-defined package available.
