### ISSUE TITLE
torch.compile graph break: torch._dynamo.exc.Unsupported: __self__ mismatch for bound method

### ISSUE THREAD

**Issue by yuwenzho** [pytorch/pytorch#137476]
### 🐛 Describe the bug

```python
import torch
import torch.nn as nn

def set_attrs_from_orig_model(cls_instance, mod, *func_names):
    cls_instance.__dict__.update(mod.__dict__)
    if func_names is not None:
        for func in func_names:
            setattr(cls_instance, func, getattr(mod, func))

class PatchedMyModule(nn.Module):
    def __init__(self, mod):
        super().__init__()
        set_attrs_from_orig_model(self, mod, "resolve_input")

    def forward(self, x):
        x = self.resolve_input(x)
        return x

class MyModule(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(in_features=input_dim, out_features=output_dim)

    def resolve_input(self, x):
        x = torch.nn.Dropout(0.1)(self.linear(x))
        return x

    def forward(self, x):
        x = self.linear(x)
        return x

module = MyModule(input_dim=1, output_dim=1)
patched_module = PatchedMyModule(module)
compiled_module = torch.compile(patched_module, fullgraph=True)

input_tensor = torch.tensor([1.], dtype=torch.float)
res = compiled_module(input_tensor)
```
fail with: `torch._dynamo.exc.Unsupported: __self__ mismatch for bound method`

### Versions

torch==2.5.0.dev20240909+cpu

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames @rec

**Comment by intellinjun** [comment]
cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec
```
if isinstance(subobj, types.MethodType):
    if dynamic_subobj.__self__ is not self.value:
        unimplemented("__self__ mismatch for bound method")
    func = subobj.__func__
```
https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/user_defined.py#L1134
Can anyone tell me why the code here is written this way? Such a rule would cause a class in torch.compile to fail when copying a method of another class, the same as described in the issue.

**Comment by ezyang** [comment]
We just didn't handle this case. Can remove the unimplemented and instead properly handle bound method getting moved to another class.

**Comment by markurcin** [comment]
Hi, I'd like to bump this as I've stumbled upon the same error after upgrading to PT2.5.

Here's a minified script to present my module and class relationship that worked seamlessly on PT2.4.:

```
import os
import torch

class MyOp(torch.autograd.Function):
    @staticmethod
    def forward(
        ctx,
        t1,
        t2
    ):
        res = torch.add(t1, t2)
        res = torch.mul(res, 5)
        return res

class OpWrapperModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.op = MyOp.apply

    def forward(self, op_inputs_dict):
        result = self.op(
            op_inputs_dict["t1"],
            op_inputs_dict["t2"]
        )
        return result

model = OpWrapperModule()
model = torch.compile(model, dynamic=False, fullgraph=True)
op_params = {
    "t1": torch.randn([32, 16, 8, 16], dtype=torch.float16, device=device),
    "t2": torch.tensor([3e-05], device=device)
}
result = model(op_params)
print(result)
```

**Comment by intellinjun** [comment]
@ezyang @markurcin @anijain2305
Dose  this pr fix  https://github.com/pytorch/pytorch/pull/139953 above issus? It looks like relevant to this issue.

**Comment by StrongerXi** [comment]
On main d0f08dc3ebc I get this:

```
Traceback (most recent call last):
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/user_defined.py", line 1119, in var_getattr
    subobj = self._getattr_static(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/user_defined.py", line 1046, in _getattr_static
    subobj = self.value.__getattribute__(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MyModule' object has no attribute 'linear'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryanguo99/scratch/repro.py", line 37, in <module>
    res = compiled_module(input_tensor)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/eval_frame.py", line 585, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 1393, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 585, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 1023, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_utils_internal.py", line 97, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 746, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 782, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 1418, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 256, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 700, in transform
    tracer.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3065, in run
    super().run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2528, in CALL
    self._call(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2522, in _call
    self.call_function(fn, args, kwargs)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 897, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 384, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 186, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1943, in LOAD_METHOD
    self._load_attr(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1967, in _load_attr
    result = BuiltinVariable(getattr).call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 1108, in call_function
    return handler(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 945, in builtin_dispatch
    rv = fn(tx, args, kwargs)
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 850, in call_self_handler
    result = self_handler(tx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 1864, in call_getattr
    return obj.var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 1103, in var_getattr
    return super().var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/user_defined.py", line 1135, in var_getattr
    out = self.manually_trace_nn_module_getattr(tx, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 1115, in manually_trace_nn_module_getattr
    out = self.getattr_helper(tx, "_modules", name_vt)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 1039, in getattr_helper
    dict_vt = self.var_getattr(tx, field)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 1103, in var_getattr
    return super().var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/user_defined.py", line 1301, in var_getattr
    return VariableTracker.build(tx, subobj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/base.py", line 527, in build
    return builder.SourcelessBuilder.create(tx, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builder.py", line 3040, in create
    return fast_handler(tx, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builder.py", line 3104, in <lambda>
    {create(tx, k): create(tx, v) for k, v in value.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builder.py", line 3104, in <dictcomp>
    {create(tx, k): create(tx, v) for k, v in value.items()},
                    ^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builder.py", line 3085, in create
    unimplemented(
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/exc.py", line 441, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: Unexpected type in sourceless builder torch.nn.modules.linear.Linear

from user code:
   File "/home/ryanguo99/scratch/repro.py", line 16, in forward
    x = self.resolve_input(x)
  File "/home/ryanguo99/scratch/repro.py", line 25, in resolve_input
    x = torch.nn.Dropout(0.1)(self.linear(x))
```
