### ISSUE TITLE
Dataset loader ToCuda() transform collate_fn fails

### ISSUE THREAD

**Issue by dizcza** [pytorch/pytorch#13775]
## 🐛 Bug

When moving `tensor = tensor.cuda()` in data preprocesing routine, loader `collate_fn` fails.
The reason why I've moved `.cuda()` to data-loader is that I need to `torch.matmul(input, matrix)` each input batch, and the matrix is large. Doing so in CPU is slow.

## To Reproduce

```python
import torch
import torch.utils.data
import torchvision

class ToCuda:

    def __init__(self):
        self.is_cuda = torch.cuda.is_available()

    def __call__(self, tensor):
        if self.is_cuda:
            tensor = tensor.cuda()
        return tensor

transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor(), ToCuda()])
dataset = torchvision.datasets.MNIST('../data', transform=transform)
loader = torch.utils.data.DataLoader(dataset, batch_size=256, num_workers=1)

model = torch.nn.Linear(784, 10)
model = model.cuda()

for images, labels in loader:
    print('it works')
```

## Expected behavior
It prints 'it works' a few times.

Traceback.

```
/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:116: UserWarning: 
    Found GPU0 GeForce GTX 760 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
THCudaCheck FAIL file=/tmp/pip-req-build-g4r2xzft/aten/src/THC/THCCachingAllocator.cpp line=508 error=3 : initialization error
Traceback (most recent call last):
  File "gpu_transform.py", line 25, in <module>
    for images, labels in loader:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 339, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 360, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 77, in __getitem__
    img = self.transform(img)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "gpu_transform.py", line 13, in __call__
    tensor = tensor.cuda()
RuntimeError: cuda runtime error (3) : initialization error at /tmp/pip-req-build-g4r2xzft/aten/src/THC/THCCachingAllocator.cpp:508
```

If I change `num_workers = 0`, everything works. If I don't use `ToCuda()` transform, it works fine as well.

## Environment

pytorch v0.4.1 built from source (tag 0.4.1) in Ubuntu 16.04 docker.
torchvision 0.2.1
python 3.6.6 (conda)
OS: Ubuntu 18.04

 - Build command you used (if compiling from source): default config

**Comment by SsnL** [comment]
See https://pytorch.org/docs/master/notes/multiprocessing.html#sharing-cuda-tensors

**Comment by dizcza** [comment]
I don't understand how it might help. I don't spawn and join processes, torchvision it does for me. I've tried `tensor.share_memory_()` before sending to cuda storage with no help.

**Comment by SsnL** [comment]
You used num_worker > 0, which are processes.

**Comment by dizcza** [comment]
I know. Are you implying I cannot send a tensor to cuda inside a process?

**Comment by soumith** [comment]
@dizcza as pointed in the link, you have to use `torch.multiprocessing.set_start_method('spawn')` to get CUDA + Multiprocessing working

**Comment by dizcza** [comment]
I don't find it in the link. Thanks for your help. I suppose I should add this line before I import torchvision, right? Because, if I import torchvision first and then include this line with the rest of the code under `if __name__ == "__main__"`, it gives
```
Traceback (most recent call last):
  File "gpu_transform.py", line 8, in <module>
    torch.multiprocessing.set_start_method('spawn')
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```
I've also tried setting `force=True` flag. But it leads to
```
/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```
after the program is quit.

**Comment by dizcza** [comment]
So it works fine only if I include both import torch and your line like so
```python
if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
    import torchvision
    #... rest of the code
```
But it's hard to stick to this method in a large project, where I have many .py files.
