### ISSUE TITLE
Torch Dynamo support for Flux Transformer model

### ISSUE THREAD

**Issue by asfiyab-nvidia** [pytorch/pytorch#138195]
### 🐛 Describe the bug

I'm using the script below to export the Flux Transformer model to ONNX using torch.onnx.dynamo_export(). However, I run into a TypeError relating to an attribute type. 

The script below can be used to reproduce the issue:

```
import torch
from diffusers.models import FluxTransformer2DModel

# Load Model
model_dir = "black-forest-labs/FLUX.1-dev"
device = "cuda"
model = FluxTransformer2DModel.from_pretrained(model_dir, subfolder="transformer", torch_dtype=torch.float16).to(device)

# Define Inputs
dtype = torch.float32
tensor_dtype = torch.float16
batch_size = 1
text_maxlen = 512
latent_height, latent_width = 1024 // 8, 1024 // 8
config = {
    'in_channels': 64,
    'joint_attention_dim': 4096,
    'pooled_projection_dim': 768
}
inputs = {
    'hidden_states': torch.randn(batch_size, (latent_height // 2) * (latent_width // 2), config['in_channels'], dtype=tensor_dtype, device=device),
    'encoder_hidden_states': torch.randn(batch_size, text_maxlen, config['joint_attention_dim'], dtype=tensor_dtype, device=device),
    'pooled_projections': torch.randn(batch_size, config['pooled_projection_dim'], dtype=tensor_dtype, device=device),
    'timestep': torch.tensor([1.]*batch_size, dtype=tensor_dtype, device=device),
    'img_ids': torch.randn((latent_height // 2) * (latent_width // 2), 3, dtype=dtype, device=device),
    'txt_ids': torch.randn(text_maxlen, 3, dtype=dtype, device=device),
    'guidance': torch.tensor([1.]*batch_size, dtype=dtype, device=device),
}

# Export to ONNX
out = torch.onnx.dynamo_export(model,
    **inputs,
)
out.save("transformer_dynamo.onnx")
```

The error is pasted below:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/_exporter_legacy.py", line 801, in dynamo_export
    ).export()
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/_exporter_legacy.py", line 570, in export
    onnxscript_graph = fx_interpreter.run(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 146, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 355, in log_and_raise_if_error
    raise diagnostic.source_exception
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 537, in run
    self.run_node(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 146, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 355, in log_and_raise_if_error
    raise diagnostic.source_exception
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 450, in run_node
    self.call_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 738, in call_module
    sub_onnxscript_graph = self.run(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 146, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 355, in log_and_raise_if_error
    raise diagnostic.source_exception
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 537, in run
    self.run_node(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 146, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 355, in log_and_raise_if_error
    raise diagnostic.source_exception
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 450, in run_node
    self.call_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 738, in call_module
    sub_onnxscript_graph = self.run(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 146, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 355, in log_and_raise_if_error
    raise diagnostic.source_exception
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 537, in run
    self.run_node(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 146, in wrapper
    ctx.log_and_raise_if_error(diag)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 355, in log_and_raise_if_error
    raise diagnostic.source_exception
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 440, in run_node
    self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 656, in call_function
    ) = symbolic_fn(*onnx_args, **onnx_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/values.py", line 583, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/ops/nn.py", line 1883, in aten__scaled_dot_product_flash_attention
    ) = _aten__scaled_dot_product_flash_attention_fillin_empty_outputs(query)
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/ops/nn.py", line 1842, in _aten__scaled_dot_product_flash_attention_fillin_empty_outputs
    op.Constant(value=onnx.helper.make_tensor("Empty_INTS", INT64.dtype, [0], []))
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/onnx_opset/_impl/opset13.py", line 453, in Constant
    return op(
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/values.py", line 301, in __call__
    return evaluator.default().eval(schema, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py", line 346, in eval
    return self._graph.add_op_call(schema, inputs, attributes)
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py", line 888, in add_op_call
    result = self._add_torchscript_op_call(
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py", line 768, in _add_torchscript_op_call
    result = _create_op_call_in_torch_graph(
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py", line 508, in _create_op_call_in_torch_graph
    _add_attribute_to_torchscript_node(node, key, value)
  File "/usr/local/lib/python3.10/dist-packages/onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py", line 470, in _add_attribute_to_torchscript_node
    raise TypeError(
TypeError: Unsupported attribute type '<class 'onnx.onnx_ml_pb2.TensorProto'>' for attribute 'value' in node=%146 : Tensor = onnx::Constant()
, value is dims: 0
data_type: 7
name: "Empty_INTS"
```

### Versions

transformers              4.42.2
torch                     2.6.0.dev20241016+cu124
diffusers                 0.31.0.dev0

**Comment by justinchuby** [comment]
Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

**Comment by yuanyao-nv** [comment]
@justinchuby Is fake mode exposed through this integrated API? I don't see a flag for it. If not what's the recommended way to use it now?

**Comment by justinchuby** [comment]
It should. You may refer to https://pytorch.org/docs/main/onnx_dynamo.html#torch.onnx.enable_fake_mode

**Comment by asfiyab-nvidia** [comment]
Thanks for the pointer @justinchuby . As per v2.4 docs, "A ONNXFakeContext object that must be passed to [dynamo_export()](https://pytorch.org/docs/2.4/onnx_dynamo.html#torch.onnx.dynamo_export) through the ExportOptions.fake_context argument."

This statement is missing in v2.5 docs. I'm guessing this means that using the context manager with `torch.onnx.export` is sufficient and the ONNXFakeContext need not be passed as an argument during export. Hope my understanding is accurate

**Comment by justinchuby** [comment]
That's right!

**Comment by justinchuby** [comment]
Sorry there may be a change to this. FakeMode is by default enabled for tensor propergation. Could you explain what your main goal is when using fake mode?

**Comment by asfiyab-nvidia** [comment]
The main goal is to reduce VRAM usage during ONNX export. How can I enable fake mode for this objective?

**Comment by justinchuby** [comment]
Does the VRAM usage happen during model initialization, or model export? We are going to create a tutorial on how to reduce memory usage when the model is being initialized so that the weights are not loaded; the export process itself is already running on fake tensors and requires minimal memory space.

**Comment by asfiyab-nvidia** [comment]
The Flux Transformer is 23GB but the peak usage during the export step is 46GB. I haven't captured the usage for model load and model export separately yet. 

> the export process itself is already running on fake tensors and requires minimal memory space.
Does this apply to the torch-script-based exporter by default, too, or is there an arg to enable this for TS-based export?

Looking forward to the docs for optimizing memory usage during model load as well. Please feel free to share snippets here for quicker turnaround

**Comment by justinchuby** [comment]
Only the torch.onnx.export(, dynamo=True) option will have an optimized memory usage for now. There is no plan to enable it for the torch script based export (the models are traced differently).

**Comment by asfiyab-nvidia** [comment]
Sounds good. Please share the usage for loading models without the weights even if the tutorial is not ready yet. We can try it and provide feedback

**Comment by fatcat-z** [comment]
> Sounds good. Please share the usage for loading models without the weights even if the tutorial is not ready yet. We can try it and provide feedback

Here is a simply example to help calling the latest dynamo enabled exporter to export your model. This latest exporter will leverage FakeTensorMode internally to reduce the memory usage.

```
import datetime
import gc
import torch

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float32

from monai.networks.nets import (
    HighResNet,
)

torch.cuda.memory._record_memory_history()

model = HighResNet(
    spatial_dims=3, in_channels=1, out_channels=3, norm_type="batch"
).eval()

model = model.to(device)
data = torch.randn(30, 1, 48, 48, 48, dtype=torch_dtype).to(device)

with torch.no_grad():
    onnx_program = torch.onnx.export(
                        model,
                        data,
                        "test_faketensor.onnx",
                        dynamo=True,
                        report=False)

snapshot_name = f"dynamo_exporter_{datetime.datetime.now().strftime('%m%d_%H%M%S')}.pickle"
print(f"generate {snapshot_name}")

del model
gc.collect()

torch.cuda.memory._dump_snapshot(snapshot_name)

print("----- Work is done. -----")

```

After execute above code, you will get a file like "dynamo_exporter_xxxx.pickle" which will save the cuda memory uage during the export process. Launch https://[pytorch.org/memory_viz](https://pytorch.org/memory_viz) page and drag and drop this .pickle file on this web page, you will see the details of memory usage.

**Comment by asfiyab-nvidia** [comment]
Thanks for the example @fatcat-z . Just to clarify, the model is still initialized with random weights. However, the weights aren't loaded from disk. 
Is this what you meant in https://github.com/pytorch/pytorch/issues/138195#issuecomment-2427244659 @justinchuby ? 
We still will have the weights in memory, but the randomly initialized ones?

**Comment by asfiyab-nvidia** [comment]
This may not impact my original use case of Flux transformer as `low_cpu_mem_usage` is True by default during
`model = FluxTransformer2DModel.from_pretrained(model_dir, subfolder="transformer", torch_dtype=torch.float16).to(device)` . This only loads the pretrained weights and does not initialize the weights
