### ISSUE TITLE
torch.cond with shape condition in predicate doesn't allow for assertions

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#138141]
### 🐛 Describe the bug

```
import torch
from torch.nn.attention.flex_attention import create_block_mask, flex_attention
torch.set_default_device("cuda")

@torch.compile(dynamic=True)
def f(x):
    def g(x):
        return x.view(x.shape[0] * x.shape[1])

    def h(x):
        assert x.shape[0] == 1
        return x.view(x.shape[1]) * 2

    return torch.cond(x.shape[0] > 1, g, h, (x,))

f(torch.randn(8, 12))
```

In this case, I would expect this to be able to run correctly. But it errors with
```
Traceback (most recent call last):
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 51, in graph_break_as_hard_error
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 756, in call_function
    ) = speculate_branch(False)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 730, in speculate_branch
    ) = speculate_subgraph(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 548, in speculate_subgraph
    raise ex
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 477, in speculate_subgraph
    output = f.call_function(tx, args, sub_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 3103, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 3231, in inline_call_
    tracer.run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 485, in inner
    unimplemented(
  File "/home/chilli/local/pytorch/torch/_dynamo/exc.py", line 304, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: Assertion failed on symbolic shapes. Did you make sure eager mode succeeds?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/chilli/t.py", line 16, in <module>
    f(torch.randn(8, 12))
  File "/home/chilli/local/pytorch/torch/_dynamo/eval_frame.py", line 487, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 1364, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 1155, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 544, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 964, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 695, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 728, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 229, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 657, in transform
    tracer.run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2888, in run
    super().run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2395, in CALL
    self._call(inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2389, in _call
    self.call_function(fn, args, kwargs)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 339, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 3103, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 3231, in inline_call_
    tracer.run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2395, in CALL
    self._call(inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2389, in _call
    self.call_function(fn, args, kwargs)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 54, in graph_break_as_hard_error
    raise UncapturedHigherOrderOpError(reason + msg) from e
torch._dynamo.exc.UncapturedHigherOrderOpError: Cond doesn't work unless it is captured completely with torch.compile. Scroll up to find out what causes the graph break.

from user code:
   File "/data/users/chilli/t.py", line 14, in f
    return torch.cond(x.shape[0] > 1, g, h, (x,))
  File "/home/chilli/local/pytorch/torch/_higher_order_ops/cond.py", line 131, in cond
    return cond_op(pred, true_fn, false_fn, operands)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

N/A

**Comment by ezyang** [comment]
This one is actually a bit subtle. When we speculate into the false branch, the assertion would naively force specialization (because that's what assertions like this do), however, this completely misses the point of the torch.cond, which is to allow for the case when the symbolic condition is > 1.

But you have an even bigger problem, which is that 0/1 specialization will force a bound that x.shape[1] >= 1, so we will in fact never compile the false branch. mark_unbacked() on the the input will help solve that problem. From there, you need to replace the assert with torch._check (but mostly for dumb reasons which is that we don't know how to deferred runtime assert via assert.)

Fixing these, and also cloning g so that it doesn't alias input, gets to Inductor:

```
import torch
from torch.nn.attention.flex_attention import create_block_mask, flex_attention
torch.set_default_device("cuda")

@torch.compile(dynamic=True, fullgraph=True)
def f(x):
    def g(x):
        return x.view(x.shape[0] * x.shape[1]).clone()

    def h(x):
        torch._check(x.shape[0] == 1)
        return x.view(x.shape[1]) * 2

    return torch.cond(x.shape[0] > 1, g, h, (x,))

x = torch.randn(8, 12)
torch._dynamo.decorators.mark_unbacked(x, 0)
f(x)
```

but now we have a new error:

```
  File "/data/users/ezyang/b/pytorch/torch/_inductor/lowering.py", line 6352, in cond
    result = ir.Conditional.create(pred, true_fn, false_fn, operands)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/ir.py", line 6611, in create
    assert to.get_size() == fo.get_size(), (i, to, fo)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: (0, StorageBox(
  ComputedBuffer(name='true_graph_0_buf0', layout=FixedLayout('cuda', torch.float32, size=[s0*u0], stride=[1]), data=Pointwise(
    'cuda',
    torch.float32,
    def inner_fn(index):
        i0 = index
        tmp0 = ops.load(true_graph_0_arg0_1, i0)
        return tmp0
    ,
    ranges=[s0*u0],
    origin_node=clone,
    origins=OrderedSet([cond, clone])
  ))
), StorageBox(
  ComputedBuffer(name='false_graph_0_buf0', layout=FixedLayout('cuda', torch.float32, size=[s0], stride=[1]), data=Pointwise(
    'cuda',
    torch.float32,
    def inner_fn(index):
        i0 = index
        tmp0 = ops.load(false_graph_0_arg0_1, i0)
        tmp1 = ops.constant(2, torch.float32)
        tmp2 = tmp0 * tmp1
        return tmp2
    ,
    ranges=[s0],
    origin_node=mul_3,
    origins=OrderedSet([cond, mul_3])
  ))
))
  target: cond
  args[0]: u0 > 1
  args[1]: Subgraph(name='true_graph_0', graph_module=<lambda>(), graph=<torch._inductor.graph.SubgraphLowering object at 0x7f4f99175450>)
  args[2]: Subgraph(name='false_graph_0', graph_module=<lambda>(), graph=<torch._inductor.graph.SubgraphLowering object at 0x7f4f991757e0>)
  args[3]: [TensorBox(StorageBox(
    InputBuffer(name='arg2_1', layout=FixedLayout('cuda', torch.float32, size=[u0, s0], stride=[s0, 1]))
  ))]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

and now life is kinda bad. Now, we *could* sledgehammer this with https://github.com/pytorch/pytorch/pull/137615 (cc @ydwu4) in which case the output here has an unbacked size and you could manually assert it so that's equal to x.shape[0]. But the true root cause of the problem is we don't know how to do temporary size refinements in branches of cond. Specifically, in the h(...) branch we should be allowed to refine x.shape[0] to 1, so that we can prove that x.shape[1] == x.shape[0] * x.shape[1], matching the type of the input branch.

This is a huge throwback to my Haskell days, because this local type refinement is precisely what GADTs do. And oh boy, Simon and friends wrote a lot of papers about type inference for this setting, e.g., https://www.microsoft.com/en-us/research/wp-content/uploads/2009/09/implication_constraints.pdf I don't know if we can get away with something simpler, but we may end up with something very GADT like here.

cc @StrongerXi

**Comment by avikchaudhuri** [comment]
The problem is not saving / restoring the shape env when speculating, but rather merging the shape envs from each branch at the end of the `cond`, right?

Maybe taking the maximum set of common guards in the two shape envs and asserting the remaining ones in each branch would work in principle?

**Comment by ezyang** [comment]
We have no way of merging the ShapeEnv because all changes are currently completely destructive. For example, if I set a replacement `u0 = s0`, that gets put in replacements, and I can't easily "back that out".

**Comment by avikchaudhuri** [comment]
Could there be a way of using the event recording system to recreate a merged shape env?

**Comment by StrongerXi** [comment]
Slightly tangential:

> But you have an even bigger problem, which is that 0/1 specialization will force a bound that x.shape[1] >= 1, so we will in fact never compile the false branch

This makes sense, but then shouldn't we have a better error log (if there should be an error at all)?
