### ISSUE TITLE
2.5.0 stable + cuda 12.4 broken; unable to to find cuda libs (works 2.4.1)

### ISSUE THREAD

**Issue by dcsouthwick** [pytorch/pytorch#138324]
### 🐛 Describe the bug

torch 2.5.0 stable from pip with cuda 12.4 results in a reproducible broken install when attempting to follow 'Getting Started' guide:

```sh
docker run -it --rm --gpus=all almalinux/9-base
[root@a8af28733c07 /]# python3 -V
Python 3.9.18
[root@a8af28733c07 /]# python3 -m pip install torch torchvision torchaudio
[root@a8af28733c07 /]# python3
>>> import torch
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 300, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 325, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 284, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcufile.so.*[0-9] not found in the system path ['', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

This works fine for the previous version; eg 2.4.1, 2.4.0, etc:
`python3 -m pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124`

I notice for previous versions when installing, resulting torch version is `2.4.1+cu124`, whereas current stable install instructions result in `2.5.0` without `+cu124` - is this a simple documentation issue?

### Versions

torch-2.5.0-cp39-cp39-manylinux1_x86_64.whl from pypi

Diagnostic script relies on broken distribution of torch:

```sh
[root@a8af28733c07 /]# wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
[root@a8af28733c07 /]# python3 collect_env.py
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 300, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//collect_env.py", line 17, in <module>
    import torch
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 325, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 284, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcufile.so.*[0-9] not found in the system path ['/', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @osalpekar @atalman @ptrblck

**Comment by malfet** [comment]
Hi-pri to get a reproducer...

**Comment by ptrblck** [comment]
Possibly related to https://github.com/pytorch/pytorch/commit/018e48c337094c8800483f1e577a1ec241982001 which added `libcufile` to `torch/__init__.py` while the actual usage and support of GDS is guarded by `USE_CUFILE=1` during the build.

**Comment by atalman** [comment]
Confirmed on Almalinux 9
```
Python 3.9.18 (main, Aug 23 2024, 00:00:00) 
[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 300, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 325, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 284, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcufile.so.*[0-9] not found in the system path ['', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

**Comment by malfet** [comment]
Ok, it fails the same way for me on amazonlinux2023:
```
docker run --rm amazonlinux:2023 bash -c "yum install -y python3-pip; python3 -mpip install torch; python3 -c 'import torch'"
....
Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.9.0 jinja2-3.1.4 mpmath-1.3.0 networkx-3.2.1 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 sympy-1.13.1 torch-2.5.0 triton-3.1.0 typing-extensions-4.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 300, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 325, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 284, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcufile.so.*[0-9] not found in the system path ['', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

**Comment by kit1980** [comment]
A release-only fix https://github.com/pytorch/pytorch/pull/138367

A possible workaround in the meantime is to install cuda-toolkit, but that may be tricky.

**Comment by malfet** [comment]
One can also create dummy `libcufile.so` or delete it from `torch/__init__.py`

**Comment by atalman** [comment]
Will be adding validation for this use case here: https://github.com/pytorch/pytorch/issues/138482
Since this is already second time we encounter this issue. First occurence was: https://github.com/pytorch/pytorch/issues/88869

**Comment by kit1980** [comment]
This is mitigated by https://github.com/pytorch/pytorch/pull/138501, which is cherry-picked for 2.5.1

**Comment by yurkoff-mv** [comment]
I'm trying to build a PyTorch docker image with **CUDA 12.4** and **PyTorch 2.4.1**. The image builds, but when I call it with the command 
```
sudo docker run --gpus all --rm -it yurkoff/pytorch:2.4.1-gpu  'python -c "import torch; print(torch.cuda.get_device_capability())"
```
I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 451, in get_device_capability
    prop = get_device_properties(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 465, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
```
