### ISSUE TITLE
[export] Torch custom class export issue

### ISSUE THREAD

**Issue by peri044** [pytorch/pytorch#138344]
### 🐛 Describe the bug

We are trying to implement the functionality to export custom classes within Torch-TensorRT. TensorRT engines are expressed as custom classes (https://github.com/pytorch/TensorRT/blob/re-export/core/runtime/register_jit_hooks.cpp#L77-L83)
Following https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA/edit
1) I implement the flatten call here : https://github.com/pytorch/TensorRT/blob/re-export/core/runtime/TRTEngine.cpp#L321-L336
2) I register a fake class with the unflatten call : https://github.com/pytorch/TensorRT/blob/re-export/py/torch_tensorrt/dynamo/runtime/register_fake_class.py#L16-L21

When I re-export the graph with these compiled TRT engines, I face an error as shown in this [reexport.log]
(https://github.com/user-attachments/files/17438975/reexport.log) 

Error msg: 
```py
Traceback (most recent call last):
  File "/home/dperi/Downloads/TensorRT/test.py", line 29, in <module>
    torch_tensorrt.save(trt_gm, "./trt.ep", inputs=inputs, retrace=True)
  File "/home/dperi/Downloads/TensorRT/py/torch_tensorrt/_compile.py", line 534, in save
    exp_program = torch.export.export(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/__init__.py", line 366, in export
    return _export(
           ^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 1013, in wrapper
    raise e
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 986, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/exported_program.py", line 116, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 1954, in _export
    export_artifact = export_func(  # type: ignore[operator]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 1744, in _non_strict_export
    aten_export_artifact = _to_aten_func(  # type: ignore[operator]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 642, in _export_to_aten_ir
    gm, graph_signature = transform(aot_export_module)(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 1674, in _aot_export_non_strict
    gm, sig = aot_export(wrapped_mod, args, kwargs=kwargs, **flags)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1262, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1497, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 524, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 625, in _create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 194, in inner
    flat_f_outs = f(*flat_f_args)
                  ^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 184, in flat_fn
    tree_out = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 863, in functional_call
    out = mod(*args[params_len:], **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/export/_trace.py", line 1657, in forward
    tree_out = torch.fx.Interpreter(self._export_root).run(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/fx/interpreter.py", line 146, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/fx/interpreter.py", line 203, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/fx/interpreter.py", line 320, in call_module
    return submod(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/Downloads/TensorRT/py/torch_tensorrt/_features.py", line 56, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dperi/Downloads/TensorRT/py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py", line 275, in forward
    outputs: List[torch.Tensor] = torch.ops.tensorrt.execute_engine(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_ops.py", line 1122, in __call__
    return _call_overload_packet_from_python(self, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_ops.py", line 1134, in _call_overload_packet_from_python
    torch_function_called, ret = torch._C._maybe_call_torch_function_for_op_packet(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_export/non_strict_utils.py", line 551, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_ops.py", line 1122, in __call__
    return _call_overload_packet_from_python(self, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_ops.py", line 1167, in _call_overload_packet_from_python
    raise RuntimeError(err_msg)
RuntimeError: Fail to match any TorchBindOverload of tensorrt.execute_engine with following exceptions:
Overload name default:
 tensorrt::execute_engine() Expected a value of type '__torch__.torch.classes.tensorrt.Engine (of Python compilation unit at: 0)' for argument '_1' but instead found type 'FakeScriptObject'.
Position: 1
Value: Torch-TensorRT TensorRT Engine:
  Name: _run_on_acc_0_engine
  Inputs: [
    id: 0
      name: x
      shape: [1, 10]
      dtype: Float
  ]
  Outputs: [
    id: 0
      name: output0
      shape: [1, 40]
      dtype: Float
  ]
  Device: Device(ID: 0, Name: NVIDIA GeForce RTX 3080 Ti, SM Capability: 8.6, Type: GPU)
  Hardware Compatibility: Disabled
  Target Platform: linux_x86_64

Declaration: tensorrt::execute_engine(Tensor[] _0, __torch__.torch.classes.tensorrt.Engine _1) -> Tensor[] _0
Cast error details: _1 is expected to be a FakeScriptObject of __torch__.torch.classes.tensorrt.Engine
```

During the re-export, this forward function gets called https://github.com/pytorch/TensorRT/blob/re-export/py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py#L275 and the self.engine object here is a FakeScriptObject 

```py
(Pdb) self.engine
<torch._library.fake_class_registry.FakeScriptObject object at 0x7557289bf010>
(Pdb) self.engine.real_obj
Torch-TensorRT TensorRT Engine:
  Name: _run_on_acc_0_engine
  Inputs: [
    id: 0
      name: x
      shape: [1, 10]
      dtype: Float
  ]
  Outputs: [
    id: 0
      name: output0
      shape: [1, 40]
      dtype: Float
  ]
  Device: Device(ID: 0, Name: NVIDIA GeForce RTX 3080 Ti, SM Capability: 8.6, Type: GPU)
  Hardware Compatibility: Disabled
  Target Platform: linux_x86_64

(Pdb) input_tensors
[FunctionalTensor(_to_functional_tensor(FakeTensor(..., device='cuda:0', size=(1, 10)),
       device='cuda:0'))]
```
Any suggestions on how to resolve the issue in the log ? 
cc: @angelayi 

### Versions

[pip3] pytorch-lightning==2.0.7
[pip3] pytorch_sphinx_theme==0.0.24
[pip3] pytorch-triton==3.1.0+cf34004b8a
[pip3] pytorch-triton-rocm==2.2.0
[pip3] pytorchvideo==0.1.5
[pip3] torch==2.6.0.dev20241011+cu124
[pip3] torch_tensorrt==2.6.0.dev0+cb03ca14a
[pip3] torchmetrics==1.4.0.post0
[pip3] torchprofile==0.0.4
[pip3] torchsurgeon==0.1.2
[pip3] torchvision==0.20.0.dev20241011+cu124
[pip3] triton==3.0.0

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by angelayi** [comment]
You have to implement a [meta kernel](https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit#heading=h.nt1pbojni4ow) for the tensorrt.execute_engine function, similar to [this example](https://github.com/pytorch/pytorch/blob/3c7d9d6c7fa565e811675be7dd84e5ef7c8ba7a0/torch/testing/_internal/torchbind_impls.py#L35-L74).

**Comment by peri044** [comment]
@angelayi Here's the PR: https://github.com/pytorch/TensorRT/pull/3262/files

We have our execute_engine op registered here and I register a fake version (in register_fake_class.py) as shown in the PR: https://github.com/pytorch/TensorRT/blob/main/core/runtime/register_jit_hooks.cpp#L127

Error: Seems like it is complaining double registration 
```py
RuntimeError: register_fake(...): the operator tensorrt::execute_engine already has an implementation for this device type via a pre-existing registration to DispatchKey::CompositeImplicitAutograd.CompositeImplicitAutograd operators do not need an fake impl; instead, the operator will decompose into its constituents and those can have fake impls defined on them.
```

**Comment by angelayi** [comment]
(From the error message) The operator is registered already to the CompositeImplicitAutograd key, so it does not need you to register a fake implementation since CompositeImplicitAutograd operators will be decomposed. I think you don't want this behavior though, so you should find where the execute_engine operators is being created and change the registration of the op to point to CompositeExplicitAutograd instead of CompositeImplicitAutograd.  

Here's an example: https://github.com/pytorch/pytorch/blob/8f62832189f82bc904302a172809436bc28a54b4/test/inductor/custom_ops.cpp#L347

**Comment by peri044** [comment]
With just 
```py
TORCH_LIBRARY_IMPL(tensorrt, CompositeExplicitAutograd, m) {
  m.impl("execute_engine", execute_engine);
}
```
I see the following. 
```py
File "/home/dperi/Downloads/TensorRT/py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py", line 275, in forward
    outputs: List[torch.Tensor] = torch.ops.tensorrt.execute_engine(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dperi/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/_ops.py", line 1232, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'tensorrt' object has no attribute 'execute_engine'
```

**Comment by peri044** [comment]
I've made progress and got some models working with this re-export. Here's my fake class/op implementation for reference : https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/dynamo/runtime/register_fake_class.py

However, for open_ai_clip model, I face a new error  when I export the compiled module
Code: 
```py
import torch
import torch_tensorrt
import open_clip
torch.set_float32_matmul_precision('high')

if __name__ == "__main__":
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model, _, preprocess = open_clip.create_model_and_transforms("convnext_xxlarge", 
                                           pretrained="laion2b_s34b_b82k_augreg_soup")

    model = model.visual.eval().to(device)
    image_size = model.image_size
    image = torch.randn((1, 3, *image_size)).to(device) # (1, 3, 256, 256)
    model = torch_tensorrt.compile(model, ir="dynamo", inputs=[image])

    trt_ep = torch.export.export(model, (image,))
    torch.export.save(trt_ep, "convnext_xxlarge_compiled.ep")
```
 Error: 
```py
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 744, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
    transformations(instructions, code_options)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 233, in _fn
    return fn(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 661, in transform
    tracer.run()
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2900, in run
    super().run()
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1120, in run
    while self.step():
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1032, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3091, in RETURN_VALUE
    self._return(inst)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3076, in _return
    self.output.compile_subgraph(
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1077, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1303, in compile_and_call_fx_graph
    self.remove_unused_graphargs()
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1596, in remove_unused_graphargs
    fake_attr_val = getattr(
torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'FakeTRTEngine' object has no attribute 'version'
```
Am I missing any attributes here ? @angelayi

**Comment by peri044** [comment]
@angelayi  
1) I added [all the attributes as you mentioned](https://github.com/pytorch/TensorRT/blob/mem_opt/py/torch_tensorrt/dynamo/runtime/register_fake_class.py#L82-L90) but now when I try to re-export using the code provided in the above comment, the export call runs indefinitely. It never gets completed. 

2) Previously, without having these attributes to the FakeTRTEngine class, all the test case models here: https://github.com/pytorch/TensorRT/blob/main/tests/py/dynamo/models/test_reexport.py pass. So this particular model (open_clip) exhibits different behavior.

Please let me know if you need any other info or have any debugging suggestions.

**Comment by angelayi** [comment]
> I added [all the attributes as you mentioned](https://github.com/pytorch/TensorRT/blob/mem_opt/py/torch_tensorrt/dynamo/runtime/register_fake_class.py#L82-L90) but now when I try to re-export using the code provided in the above comment, the export call runs indefinitely. It never gets completed.

Do you know when/where it gets stuck?

**Comment by masnesral** [comment]
[issue scrubbing] Looks like the convo petered out here. @peri044 is this still relevant? Any update from the last question?

**Comment by masnesral** [comment]
Gonna close this out from the perspective of issue hygiene. Feel free to reopen if there's still an issue and you have some additional details.
