### ISSUE TITLE
[ROCm] FlexAttention Sliding Window Attention Numeric Error

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#138300]
### 🐛 Describe the bug

Hi AMD Team,

I am currently trying to improve Mistral performance on MI300X by attempting to use FlexAttention Sliding Attention but unfortunately it is running into numeric errors. I have Verified that on H100 that this passes the correctness check

cc: @hliuca

## H100 Correctness Passing & Showing Massive Speedup
![image](https://github.com/user-attachments/assets/5cc0b2ca-3997-46e5-be69-34342d4dc3de)

## MI300X Error Msg
```bash
╔═════════════════════════════════════════════════════════════════════════════════════════╗
║                                   Sliding Window 1024                                   ║
╚═════════════════════════════════════════════════════════════════════════════════════════╝
Traceback (most recent call last):
  File "/workspace/llm-train-bench/attention-gym/./examples/benchmark.py", line 176, in <module>
    test_mask(mask_mod=generate_sliding_window(window_size=1024))
  File "/workspace/llm-train-bench/attention-gym/./examples/benchmark.py", line 132, in test_mask
    torch.testing.assert_close(flex, sdpa_mask, atol=1e-1, rtol=1e-2)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1530, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 116391936 / 134217728 (86.7%)
Greatest absolute difference: nan at index (0, 0, 1088, 0) (up to 0.1 allowed)
Greatest relative difference: nan at index (0, 0, 1088, 0) (up to 0.01 allowed)
```

## Reprod (Slightly Minified from https://github.com/pytorch-labs/attention-gym/blob/main/examples/benchmark.py)
```python
from functools import lru_cache
from typing import Optional

import torch
import torch.nn.functional as F

from tabulate import tabulate
from torch.nn.attention.flex_attention import (
    _DEFAULT_SPARSE_BLOCK_SIZE,
    create_block_mask,
    create_mask,
    flex_attention,
    _score_mod_signature,
    _mask_mod_signature,
)

from triton.testing import do_bench

from attn_gym.masks import generate_sliding_window

torch.set_default_device("cuda")
torch.manual_seed(0)

torch._dynamo.config.cache_size_limit = 1000

# Compile the flex_attention function
flex_attention = torch.compile(flex_attention, dynamic=False)

# For better performance, you can use:
# flex_attention = torch.compile(_flex_attention, dynamic=False, mode="max-autotune-no-cudagraphs")

data_type = torch.bfloat16

# The kernels will utilize block sparsity to increase performance
print(f"Using the default sparsity block size: {_DEFAULT_SPARSE_BLOCK_SIZE}")


@lru_cache
def create_block_mask_cached(score_mod, B, H, M, N, device="cuda"):
    block_mask = create_block_mask(score_mod, B, H, M, N, device=device)
    return block_mask


def calculate_tflops(flops: float, time_ms: float, multiplier: int) -> float:
    return multiplier * flops * (1e3 / time_ms) / 1e12


def print_header(text):
    width = 91
    print("╔" + "═" * (width - 2) + "╗")
    print(f"║ {text.center(width - 4)} ║")
    print("╚" + "═" * (width - 2) + "╝")


def test_mask(
    score_mod: Optional[_score_mod_signature] = None,
    mask_mod: Optional[_mask_mod_signature] = None,
    B: int = 16,
    H: int = 16,
    S: int = 8192,
    D: int = 64,
    skip_correctness: bool = False,
    print_mask: bool = True,
    device: str = "cuda",
):
    assert score_mod is not None or mask_mod is not None, "Must provide a score_mod or mask_mod"
    if mask_mod is not None:
        block_mask = create_block_mask_cached(mask_mod, 1, 1, S, S, device=device)
    else:
        block_mask = None
    sdpa_mask_fn = mask_mod if mask_mod is not None else score_mod
    mask = create_mask(sdpa_mask_fn, 1, 1, S, S, device=device)

    qkv = [
        torch.randn(B, H, S, D, device=device, dtype=data_type, requires_grad=True)
        for _ in range(3)
    ]
    gradOut = torch.randn(B, H, S, D, device=device, dtype=torch.float16)

    causal_fa2 = lambda: F.scaled_dot_product_attention(*qkv, is_causal=True)
    sdpa_mask = lambda: F.scaled_dot_product_attention(*qkv, attn_mask=mask)
    flex_attention_call = lambda: flex_attention(*qkv, score_mod=score_mod, block_mask=block_mask)

    results = []
    if block_mask is not None:
        density = (100 - block_mask.sparsity()) / 100
    else:
        density = 1.0
    causal_fav2_flops = 0.5 * B * H * D * S * S
    flops = density * B * H * D * S * S

    # Forward pass
    causal_fa2_time = do_bench(causal_fa2)
    sdpa_mask_time = do_bench(sdpa_mask)
    flex_ms = do_bench(flex_attention_call)

    # Backward pass
    causal_fa2_out = causal_fa2()
    sdpa_mask_out = sdpa_mask()
    flex_out = flex_attention_call()

    causal_fa2_bw_time = do_bench(lambda: causal_fa2_out.backward(gradOut, retain_graph=True))
    sdpa_mask_bw_time = do_bench(lambda: sdpa_mask_out.backward(gradOut, retain_graph=True))
    flex_bw_ms = do_bench(lambda: flex_out.backward(gradOut, retain_graph=True))

    print_header(
        f"{score_mod.__name__ if score_mod is not None else mask_mod.__name__}".replace(
            "_", " "
        ).title()
    )
    # Inline correctness check
    if not skip_correctness:
        sdpa_mask_outs = []
        flex_outs = []

        for tensor in qkv:
            tensor.grad = None

        out1 = sdpa_mask()
        sdpa_mask_outs.append(out1)
        out1.backward(gradOut)
        sdpa_mask_outs += [tensor.grad for tensor in qkv]

        for tensor in qkv:
            tensor.grad = None

        out2 = flex_attention_call()
        flex_outs.append(out2)
        out2.backward(gradOut)
        flex_outs += [tensor.grad for tensor in qkv]
        for flex, sdpa_mask in zip(flex_outs, sdpa_mask_outs):
            torch.testing.assert_close(flex, sdpa_mask, atol=1e-1, rtol=1e-2)

        print("Correctness check passed ✅")
    # Usage in your results formatting:
    results = [
        [
            "causal FA2",
            f"{causal_fa2_time:.4f}",
            f"{calculate_tflops(causal_fav2_flops, causal_fa2_time, 4):.2f}",
            f"{causal_fa2_bw_time:.4f}",
            f"{calculate_tflops(causal_fav2_flops, causal_fa2_bw_time, 10):.2f}",
        ],
        [
            "F.sdpa + mask",
            f"{sdpa_mask_time:.4f}",
            f"{calculate_tflops(flops, sdpa_mask_time, 4):.2f}",
            f"{sdpa_mask_bw_time:.4f}",
            f"{calculate_tflops(flops, sdpa_mask_bw_time, 10):.2f}",
        ],
        [
            "flexattention",
            f"{flex_ms:.4f}",
            f"{calculate_tflops(flops, flex_ms, 4):.2f}",
            f"{flex_bw_ms:.4f}",
            f"{calculate_tflops(flops, flex_bw_ms, 10):.2f}",
        ],
    ]
    print(
        tabulate(
            results,
            headers=[
                "Operation",
                "FW Time (ms)",
                "FW FLOPS (TF/s)",
                "BW Time (ms)",
                "BW FLOPS (TF/s)",
            ],
            tablefmt="grid",
        )
    )
    if print_mask:
        print(f"\nBlock Mask:\n{block_mask}")


test_mask(mask_mod=generate_sliding_window(window_size=1024))
```

## [Pytorch Labs Flex Attention Attention Gym Installation](https://github.com/pytorch-labs/attention-gym)
```bash
git clone https://github.com/pytorch-labs/attention-gym.git
cd attention-gym
pip install .
```
## Version
```bash
pip list | grep attention
attn_gym                0.0.3.dev1+gf7c93de       /workspace/llm-train-bench/attention-gym
```

## ROCm Pytorch Nightly

```bash
$ pip list | grep torch
pytorch-triton-rocm     3.1.0+cf34004b8a
torch                   2.6.0.dev20241017+rocm6.2
torchvision             0.18.0a0+68ba7ec
```

**Comment by OrenLeung** [comment]
This numeric error also affects "document" mask in the example as it is basically similar to SWA with max seq=32k and randomly generated window.

https://github.com/pytorch-labs/attention-gym/blob/f7c93ded4abf9fd8d7dc9d8bcbf57e420b891e2d/examples/benchmark.py#L218

```python
from functools import lru_cache
from typing import Optional

import torch
import torch.nn.functional as F

from tabulate import tabulate
from torch.nn.attention.flex_attention import (
    _DEFAULT_SPARSE_BLOCK_SIZE,
    create_block_mask,
    create_mask,
    flex_attention,
    _score_mod_signature,
    _mask_mod_signature,
)

from triton.testing import do_bench

from attn_gym.masks.document_mask import length_to_offsets
from attn_gym.masks import (
    causal_mask,
    generate_doc_mask_mod,
)



torch.set_default_device("cuda")
torch.manual_seed(0)

torch._dynamo.config.cache_size_limit = 1000

# Compile the flex_attention function
flex_attention = torch.compile(flex_attention, dynamic=False)

# For better performance, you can use:
# flex_attention = torch.compile(_flex_attention, dynamic=False, mode="max-autotune-no-cudagraphs")

data_type = torch.float16

# The kernels will utilize block sparsity to increase performance
print(f"Using the default sparsity block size: {_DEFAULT_SPARSE_BLOCK_SIZE}")


@lru_cache
def create_block_mask_cached(score_mod, B, H, M, N, device="cuda"):
    block_mask = create_block_mask(score_mod, B, H, M, N, device=device)
    return block_mask


def calculate_tflops(flops: float, time_ms: float, multiplier: int) -> float:
    return multiplier * flops * (1e3 / time_ms) / 1e12


def print_header(text):
    width = 91
    print("╔" + "═" * (width - 2) + "╗")
    print(f"║ {text.center(width - 4)} ║")
    print("╚" + "═" * (width - 2) + "╝")


def test_mask(
    score_mod: Optional[_score_mod_signature] = None,
    mask_mod: Optional[_mask_mod_signature] = None,
    B: int = 16,
    H: int = 16,
    S: int = 8192,
    D: int = 64,
    skip_correctness: bool = True,
    print_mask: bool = True,
    device: str = "cuda",
):
    assert score_mod is not None or mask_mod is not None, "Must provide a score_mod or mask_mod"
    if mask_mod is not None:
        block_mask = create_block_mask_cached(mask_mod, 1, 1, S, S, device=device)
    else:
        block_mask = None
    sdpa_mask_fn = mask_mod if mask_mod is not None else score_mod
    mask = create_mask(sdpa_mask_fn, 1, 1, S, S, device=device)

    qkv = [
        torch.randn(B, H, S, D, device=device, dtype=data_type, requires_grad=True)
        for _ in range(3)
    ]
    gradOut = torch.randn(B, H, S, D, device=device, dtype=torch.float16)

    causal_fa2 = lambda: F.scaled_dot_product_attention(*qkv, is_causal=True)
    sdpa_mask = lambda: F.scaled_dot_product_attention(*qkv, attn_mask=mask)
    flex_attention_call = lambda: flex_attention(*qkv, score_mod=score_mod, block_mask=block_mask)

    results = []
    if block_mask is not None:
        density = (100 - block_mask.sparsity()) / 100
    else:
        density = 1.0
    causal_fav2_flops = 0.5 * B * H * D * S * S
    flops = density * B * H * D * S * S

    # Forward pass
    causal_fa2_time = do_bench(causal_fa2)
    sdpa_mask_time = do_bench(sdpa_mask)
    flex_ms = do_bench(flex_attention_call)

    # Backward pass
    causal_fa2_out = causal_fa2()
    sdpa_mask_out = sdpa_mask()
    flex_out = flex_attention_call()

    causal_fa2_bw_time = do_bench(lambda: causal_fa2_out.backward(gradOut, retain_graph=True))
    sdpa_mask_bw_time = do_bench(lambda: sdpa_mask_out.backward(gradOut, retain_graph=True))
    flex_bw_ms = do_bench(lambda: flex_out.backward(gradOut, retain_graph=True))

    print_header(
        f"{score_mod.__name__ if score_mod is not None else mask_mod.__name__}".replace(
            "_", " "
        ).title()
    )
    # Inline correctness check
    if not skip_correctness:
        sdpa_mask_outs = []
        flex_outs = []

        for tensor in qkv:
            tensor.grad = None

        out1 = sdpa_mask()
        sdpa_mask_outs.append(out1)
        out1.backward(gradOut)
        sdpa_mask_outs += [tensor.grad for tensor in qkv]

        for tensor in qkv:
            tensor.grad = None

        out2 = flex_attention_call()
        flex_outs.append(out2)
        out2.backward(gradOut)
        flex_outs += [tensor.grad for tensor in qkv]
        for flex, sdpa_mask in zip(flex_outs, sdpa_mask_outs):
            torch.testing.assert_close(flex, sdpa_mask, atol=1e-1, rtol=1e-2)

        print("Correctness check passed ✅")
    # Usage in your results formatting:
    results = [
        [
            "causal FA2",
            f"{causal_fa2_time:.4f}",
            f"{calculate_tflops(causal_fav2_flops, causal_fa2_time, 4):.2f}",
            f"{causal_fa2_bw_time:.4f}",
            f"{calculate_tflops(causal_fav2_flops, causal_fa2_bw_time, 10):.2f}",
        ],
        [
            "F.sdpa + mask",
            f"{sdpa_mask_time:.4f}",
            f"{calculate_tflops(flops, sdpa_mask_time, 4):.2f}",
            f"{sdpa_mask_bw_time:.4f}",
            f"{calculate_tflops(flops, sdpa_mask_bw_time, 10):.2f}",
        ],
        [
            "flexattention",
            f"{flex_ms:.4f}",
            f"{calculate_tflops(flops, flex_ms, 4):.2f}",
            f"{flex_bw_ms:.4f}",
            f"{calculate_tflops(flops, flex_bw_ms, 10):.2f}",
        ],
    ]
    print(
        tabulate(
            results,
            headers=[
                "Operation",
                "FW Time (ms)",
                "FW FLOPS (TF/s)",
                "BW Time (ms)",
                "BW FLOPS (TF/s)",
            ],
            tablefmt="grid",
        )
    )
    if print_mask:
        print(f"\nBlock Mask:\n{block_mask}")


def run_document_masking(max_seq_len: int, num_docs: int):
    import random

    random.seed(0)

    def generate_random_lengths(total_length, num_documents):
        # Initialize all lengths to 1 to ensure each document has at least one token
        lengths = [1] * num_documents
        remaining_length = total_length - num_documents

        # Randomly distribute the remaining length
        for _ in range(remaining_length):
            index = random.randint(0, num_documents - 1)
            lengths[index] += 1

        return lengths

    lengths = generate_random_lengths(max_seq_len, num_docs)
    offsets = length_to_offsets(lengths, "cuda")
    document_causal_mask = generate_doc_mask_mod(causal_mask, offsets)
    test_mask(mask_mod=document_causal_mask, S=32768)

run_document_masking(max_seq_len=32768, num_docs=12)
```

**Comment by hliuca** [comment]
Hi @OrenLeung the issue has been assigned to developer. Thank you Oren.

**Comment by jataylo** [comment]
Anticipating that this will require a triton update to resolve.  Will track flexattention support as part of https://github.com/pytorch/pytorch/issues/139175

**Comment by jataylo** [comment]
This is still reproducible on the beta triton 3.2 testing, taking a look to see where the issue lies. Whether on triton kernel or the sdpa call.

Curiously with S<1024 correctness is fine

**Comment by jataylo** [comment]
I had to tune down some parameters for side-by-side comparison at the minute as I'm comparing with V100 instead of H100 for the time being 
```
  B: int = 1,
  H: int = 4,
  S: int = 2048,
  D: int = 16,
```


I compared MI300 vs V100 for the 3 output tensors (--atol 1e-1 --rtol 1e-2):
causal_fa2_out.pth:
- Tensors match within tolerance. Closeness: 100.00% of elements are close within tolerance.
    
flex_out.pth: 
- Tensors do not match within tolerance. Closeness: 90.01% of elements are close within tolerance.
- Max Difference: 2.562500, Mean Difference: 0.049805
    
sdpa_mask_out.pth: 
- Tensors do not match within tolerance. Closeness: 51.56% of elements are close within tolerance.
- Max Difference: nan, Mean Difference: nan

Looks like the main accuracy issue here is coming from the none-causal sdpa call:
```
sdpa_mask = lambda: F.scaled_dot_product_attention(*qkv, attn_mask=mask)
sdpa_mask_out = sdpa_mask()
```

When I have H100 access I will rerun with original reported configuration

**Comment by OrenLeung** [comment]
hi @jataylo ,

Thanks for confirming that these numeric errors are reproducible on your end too

**Comment by jataylo** [comment]
Compared original configuration outputs H100 vs MI300, flex attention and fa2 are within 90% of same result as H100 but sdpa_mask_out results are off 
```
flex_out.pth: Tensors do not match within tolerance.
    Closeness: 91.10% of elements are close within tolerance.
    Max Difference: 4.187500
    Mean Difference: 0.047852
Warning: 'q_grad.pth' does not contain a tensor in one of the directories.
causal_fa2_out.pth: Tensors do not match within tolerance.
    Closeness: 93.50% of elements are close within tolerance.
    Max Difference: 5.625000
    Mean Difference: 0.040283
sdpa_mask_out.pth: Tensors do not match within tolerance.
    Closeness: 8.49% of elements are close within tolerance.
    Max Difference: nan
    Mean Difference: nan
```

Moreover there is some NaN issue in sdpa_mask_out
```
(Pdb) print(out1)
tensor([[[[ 1.2578,  0.8633,  0.3301,  ..., -2.7344,  1.9766, -1.4766],
          [ 1.1328,  0.0549,  0.8125,  ..., -0.8906,  0.9414, -0.6484],
          [ 0.9453, -0.3750,  0.8789,  ...,  0.5078,  0.1182, -0.1748],
          ...,
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],
```

This reproducer seems to be catching some edge case for us, the flex and causal fa2 results seem okay but the causal sdpa path is behaving poorly.

**Comment by OrenLeung** [comment]
Hi! Thanks for taking the time to reprod this on your end too.

this is quite interesting. the atol is quite high on mi300x.

**Comment by jataylo** [comment]
The issue with NaNs is related to boolean attention mask, 0.8b AOTriton version will resolve this when merged upstream. Aiming for 2.6 release.

**Comment by jataylo** [comment]
@OrenLeung cc: @hliuca, @hongxiayang This is now resolved with the 0.8b AOTriton upgrade from https://github.com/pytorch/pytorch/pull/140172

This was specifically an issue for boolean attention masks, thank you for reporting this.

![image](https://github.com/user-attachments/assets/6e3727c4-f3da-469d-8f30-d317f12751ea)

**Comment by hliuca** [comment]
Thank you @jataylo

**Comment by drisspg** [comment]
@jataylo Thanks for burning this one down!
