### ISSUE TITLE
get_model_state_dict failed after FSDP_model.to(dtype)

### ISSUE THREAD

**Issue by ZiyueHuang** [pytorch/pytorch#138467]
### 🐛 Describe the bug

```python
# fsdp_model with mixed precision (fp32 parameters)
fsdp_model.to(torch.bfloat16)
save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
with FSDP.state_dict_type(model, StateDictType.FULL_STATE_DICT, save_policy):
    return fsdp_model.state_dict()
```

The above code fails with error:

```
[rank0]: Traceback (most recent call last):
......
[rank0]:   File "xxx", line 118, in xxx
[rank0]:     return model.state_dict()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2199, in state_dict
[rank0]:     hook(self, prefix, keep_vars)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_state_dict_utils.py", line 782, in _pre_state_dict_hook
[rank0]:     _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_state_dict_utils.py", line 303, in _full_pre_state_dict_hook
[rank0]:     _common_unshard_pre_state_dict_hook(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_state_dict_utils.py", line 170, in _common_unshard_pre_state_dict_hook
[rank0]:     _enter_unshard_params_ctx(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_state_dict_utils.py", line 134, in _enter_unshard_params_ctx
[rank0]:     fsdp_state._unshard_params_ctx[module].__enter__()
[rank0]:   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
[rank0]:     return next(self.gen)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 198, in _unshard_fsdp_state_params
[rank0]:     _unshard(state, handle, computation_stream, computation_stream)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 301, in _unshard
[rank0]:     handle.unshard()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_flat_param.py", line 1312, in unshard
[rank0]:     padded_unsharded_flat_param = self._all_gather_flat_param(unsharded_flat_param)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/fsdp/_flat_param.py", line 1403, in _all_gather_flat_param
[rank0]:     dist.all_gather_into_tensor(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3410, in all_gather_into_tensor
[rank0]:     work = group._allgather_base(output_tensor, input_tensor, opts)
[rank0]: TypeError: output tensor must have the same type as input tensor
```

### Versions

torch 2.4+

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @zhaojuanmao @mrshenli @rohan-varma @chauhang

**Comment by ZiyueHuang** [comment]
gently ping @awgu

**Comment by ZiyueHuang** [comment]
@awgu Thanks for your response.

`fsdp_model.to(torch.bfloat16)` is did before `state_dict` to reduce CPU memory cost, otherwise, for example, 100B model will cost 400GB memory (if fp32 state_dict).

```python
# init fsdp model with mixed presion
fsdp_model = FSDP(model)
# forward and backward for training
# ......
# change param dtype to bf16 to reduce CPU memory cost when materializing full_state_dict, otherwise will OOM
fsdp_model.to(torch.bfloat16)
# rank_0 = true, offload_cpu = true
fsdp_model.state_dict()

**Comment by awgu** [comment]
Do you intend to continue using the fp32 parameters after you save the full state dict (like for further training)?

**Comment by awgu** [comment]
Sorry, I had some idea in mind, but I realized that it is still hard to handle the conversion from FSDP's flat-parameter sharding.

Would it be possible for you to switch to FSDP2 😓 ? It would be easier to do this kind of transformations.

**Comment by ZiyueHuang** [comment]
@awgu I tried FSDP2 at first, but it comsumed much more GPU memory than FSDP1 (both with CPU_Offload = true).

Can I use the code below to save state_dict to reduce CPU memory?
```python
# rank_0 = true, cpu = true
with summon_full_parameters():
    for n, p in fsdp_model.named_parameters():
        # p.to(bfloat16) and save each param
```

**Comment by awgu** [comment]
FSDP2 using more GPU memory seems unexpected to me. Maybe we can investigate that separately.

I think your `summon_full_params` code snippet makes sense.

**Comment by ZiyueHuang** [comment]
@awgu I will do some profile for FSDP2 later.

Can I call `summon_full_params(recurse=True)` on the root fsdp module? Will it lead to OOM?

**Comment by ZiyueHuang** [comment]
@awgu One more question: I encountered the same issue as in https://github.com/pytorch/pytorch/issues/132366#issuecomment-2264642034. And I follow this suggestion, add device_mesh into FSDP args to emit DTensor **sharded** state_dict, and use dist_cp to save each shard. Then it consumed more memory even than when rank_0 allg_athers full_state_dict.

**Comment by awgu** [comment]
> Then it consumed more memory even than when rank_0 all_gathers full_state_dict.

CPU memory or GPU memory?

**Comment by awgu** [comment]
cc: @wz337 @fegin any ideas why sharded state dict with DCP would take more CPU memory than full state dict?

**Comment by ZiyueHuang** [comment]
@awgu How to get the full param for `lm_head` (for example, https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2/modeling_qwen2.py#L1110)? `summon_full_parameters(fsdp_model, recurse=False)` seems to gives sharded `_flat_param` (param_name), while others params look like `model.layers.0._fsdp_wrapped_module._checkpoint_wrapped_module._flat_param` (param_name).

**Comment by wz337** [comment]
> #132366 (comment)



> @awgu One more question: I encountered the same issue as in [#132366 (comment)](https://github.com/pytorch/pytorch/issues/132366#issuecomment-2264642034). And I follow this suggestion, add device_mesh into FSDP args to emit DTensor **sharded** state_dict, and use dist_cp to save each shard. Then it consumed more memory even than when rank_0 all_gathers full_state_dict.

@ ZiyueHuang When using FSDP1's sharded state dict, what happens behind the scenes is that there is all_gather and chunk to produce the correct sharded state dict, since the local state dict lives in each rank are the flat parameter. 

There are 3 state_dict type in FSDP1:
1) full_state_dict: all_gather
2) sharded_state_dict: all_gather and chunk the original parameters
3) local_state_dict: flat parameter

**Comment by ZiyueHuang** [comment]
@wz337 If the local_state_dict (flat parameter) is saved, how can we recover the original parameters after loading?

**Comment by wz337** [comment]
> @wz337 If the local_state_dict (flat parameter) is saved, how can we recover the original parameters after loading?

@ZiyueHuang Wondering what your use case is. If you are not going to change # of devices for training, you should be able to directly load the local_state_dict back.

**Comment by ZiyueHuang** [comment]
> @ZiyueHuang Wondering what your use case is. If you are not going to change # of devices for training, you should be able to directly load the local_state_dict back.

@wz337 The `local_state_dict` is saved to avoid errors, while `full_state_dict` lead to OOM and `sharded_state_dict` lead to the error described in https://github.com/pytorch/pytorch/issues/132366#issuecomment-2264642034).

> @ZiyueHuang Can you recognize which stage incur more CPU memory usage? For example, can you try only saving model state_dict without optimizer state_dict? This can isolate the problems.

Only model state_dict is saved.

**Comment by ZiyueHuang** [comment]
> @ZiyueHuang Wondering what your use case is. If you are not going to change # of devices for training, you should be able to directly load the local_state_dict back.

@wz337 I want to convert the saved `local_state_dict` to Huggingface repo format.

**Comment by wz337** [comment]
> > @ZiyueHuang Wondering what your use case is. If you are not going to change # of devices for training, you should be able to directly load the local_state_dict back.
> 
> @wz337 I want to convert the saved `local_state_dict` to Huggingface repo format.

You would need to load it back and then get the full_state_dict so that you can save it to Huggingface repo format. 
If you want to do the casting, you could do it after getting the full_state_dict so you won't run into the issue above.
