### ISSUE TITLE
dynamic control flow failed

### ISSUE THREAD

**Issue by keilsmart** [pytorch/pytorch#138689]
### 🐛 Describe the bug

```
import torch
import numpy as np

def test_controlflow():
    def is_scaled(val: np.ndarray) -> bool:
        return np.min(val) >= 0 and np.max(val) <= 1

    def process(val):
        # np.min(val) >= 0 and np.max(val) <= 1
        if is_scaled(val):
            val = val * 255
        val = val - np.mean(val, keepdims=True)
        return val

    val = np.random.rand(3, 224, 224)
    output = process(val)

    process_opt = torch.compile(process, dynamic=True)
    output_opt = process_opt(val)

    assert np.allclose(output, output_opt)

if __name__ == "__main__":
    test_controlflow()
```

When I ran the above code, torch compile reported an error that “Dynamic control flow is not supported at the moment”.  But if I call np.min and np.max directly in the process function instead of encapsulating them in the is_scaled function, every thing is ok。How can I resolve this problem? 

### Error logs

V1023 16:11:40.698000 139837258437760 torch/_dynamo/symbolic_convert.py:534] [0/0] [__graph_breaks] torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.e    xperimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands

### Versions

torch.2.4.1

cc @ezyang @chauhang @penguinwu

**Comment by desertfire** [comment]
I can not reproduce with 2.5 or nightly. Can you try with a later version?

**Comment by keilsmart** [comment]
> I can not reproduce with 2.5 or nightly. Can you try with a later version?

I tried both 2.5 and nightly, but the error still exists. I run the code with TORCH_LOGS="+dynamo" python ./test_cond.py.


Logs:


 FAILED INLINING <code object is_scaled at 0x7f82f927d580, file "/root/./test_cond.py", line 5>
[__graph_breaks] Graph break in user code at /root/./test_cond.py:6
[__graph_breaks] Reason: Unsupported: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more infor

[__graph_breaks] User code traceback:
[__graph_breaks]   File "/root/./test_cond.py", line 9, in process
[__graph_breaks]     if is_scaled(val):
[__graph_breaks]   File "/root/./test_cond.py", line 6, in is_scaled
[__graph_breaks]     return np.min(val) >= 0 and np.max(val) <= 1
[__graph_breaks] Traceback (most recent call last):
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
[__graph_breaks]     return inner_fn(self, inst)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1713, in CALL_FUNCTION
[__graph_breaks]     self.call_function(fn, args, {})
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 942, in call_function
[__graph_breaks]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/variables/lazy.py", line 170, in realize_and_forward
[__graph_breaks]     return getattr(self.realize(), name)(*args, **kwargs)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 345, in call_function
[__graph_breaks]     return super().call_function(tx, args, kwargs)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 124, in call_function
[__graph_breaks]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
[__graph_breaks]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3102, in inline_call
[__graph_breaks]     return cls.inline_call_(parent, func, args, kwargs)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3230, in inline_call_
[__graph_breaks]     tracer.run()
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1095, in run
[__graph_breaks]     while self.step():
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1007, in step
[__graph_breaks]     self.dispatch_table[inst.opcode](self, inst)
[__graph_breaks]   File "/mnt/xjl/venv/torch2.5.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 596, in inner
[__graph_breaks]     raise exc.UserError(
[__graph_breaks] torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow.
