### ISSUE TITLE
Error loading ".venv\Lib\site-packages\torch\lib\c10_xpu.dll" or one of its dependencies

### ISSUE THREAD

**Issue by Stanley5249** [pytorch/pytorch#138986]
### 🐛 Describe the bug

When attempting to import `torch` with version `2.5.1+xpu`, I encounter the following error:
```
Error loading ".venv\Lib\site-packages\torch\lib\c10_xpu.dll" or one of its dependencies
```

I've followed the instructions from:
- https://pytorch.org/docs/stable/notes/get_start_xpu.html
- https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html

Installed and set up the oneAPI environment:

```
:: initializing oneAPI environment...
   Initializing Visual Studio command-line environment...
   Visual Studio version 17.11.5 environment configured.
   "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\"
   Visual Studio command-line environment initialized for: 'x64'
:: compiler -- processing etc\compiler\vars.bat
:: debugger -- processing etc\debugger\vars.bat
:: dpl -- processing etc\dpl\vars.bat
:: mkl -- processing etc\mkl\vars.bat
:: tbb -- processing etc\tbb\vars.bat
:: oneAPI environment initialized ::
```

I have additional questions for the Intel Teams. What is the recommended way to use an Intel GPU on Windows 11?
   - IPEX `2.3.1+xpu` on WSL2
   - `torch.compile` with OpenVINO backend
   - `torch 2.5` for support xpu

Thank you for your assistance.

### Versions

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家用版 (10.0.22631 64 位元)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22631-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Name: Intel(R) Core(TM) Ultra 9 185H
Manufacturer: GenuineIntel
Family: 1
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 2300
MaxClockSpeed: 2300
L2CacheSize: 18432
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] onnx==1.17.0
[pip3] torch==2.5.1+xpu
[conda] Could not collect
```

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by imkow** [comment]
I got the same problem with 2.5.1 preview and 2.6.0 nightly. I guess that the Intel/Pytorch dev team didn't test on a clean system without dev libs installed.

**Comment by chuanqi129** [comment]
@ratnampa please help to check this issue

**Comment by EikanWang** [comment]
@Stanley5249 , May I know if you source Intel GPU bundle every time?

```bash
"C:\Program Files (x86)\Intel\oneAPI\pytorch-gpu-dev-0.5\oneapi-vars.bat"
"C:\Program Files (x86)\Intel\oneAPI\ocloc\2024.2\env\vars.bat"
```

**Comment by MEDMac29** [comment]
Hello
please i need help
**how  to  add navigationMenu in Toolbox here (Visual studio 2022)**
** How to add the Toolbox navigation menu here (Visual Studio 2022) ** Not showing up
<img width="312" alt="1" src="https://github.com/user-attachments/assets/54a337f1-f5d0-4355-9401-0a87d0af5731">

**Comment by Stanley5249** [comment]
> @Stanley5249 , May I know if you source Intel GPU bundle every time? Could you help run the command lines as follows and share the result with us?
> 
> ```shell
> "C:\Program Files (x86)\Intel\oneAPI\pytorch-gpu-dev-0.5\oneapi-vars.bat"
> "C:\Program Files (x86)\Intel\oneAPI\ocloc\2024.2\env\vars.bat"
> python -c "import torch"
> ```

Hi @EikanWang,

I found that the problem was with PowerShell. When I ran a script, I saw the message ":: oneAPI environment initialized ::," which made me think it had initialized correctly, but it hadn't. It started working after I switched to CMD.

The source script could be more user-friendly. It would be beneficial to have a warning for using the incorrect shell. An update to the documentation could also help prevent any confusion.

**Comment by lam-mini** [comment]
Hi @Stanley5249,
Could you please provide any other key steps of your solution? I've tried switching to CMD but couldn't solve the same problem.  environment:  torch 2.5.1+xpu, graphics driver31.0.101.5522

**Comment by lam-mini** [comment]
Hi @Stanley5249,
Could you please provide any other key steps of your solution? I've tried switching to CMD but couldn't solve the same problem.  environment:  torch 2.5.1+xpu, graphics driver31.0.101.5522

**Comment by Stanley5249** [comment]
@lam-mini,

did you install the Visual Studio or the Visual Studio Build Tools?

I wrote my steps [here](https://github.com/Stanley5249/torch-test-xpu).

**Comment by MEDMac29** [comment]
Hi sir
I did install visual studio 2022

**Comment by EikanWang** [comment]
@Stanley5249 , thanks for your input. And definitely, we should improve the sourcing step and your inputs are helpful.

> It would be beneficial to have a warning for using the incorrect shell. An update to the documentation could also help prevent any confusion.

@jingxu10 , @riverliuintel, let's add a test case to cover different cmd shells.

**Comment by EikanWang** [comment]
@imkow , do you mean it still does not work even though you have invoked the two scripts?

```shell
"C:\Program Files (x86)\Intel\oneAPI\pytorch-gpu-dev-0.5\oneapi-vars.bat"
"C:\Program Files (x86)\Intel\oneAPI\ocloc\2024.2\env\vars.bat" 
```

**Comment by EikanWang** [comment]
@Stanley5249 , @MEDMac29 , are you trying to build from source rather than installing intel gpu wheel directly?

**Comment by Stanley5249** [comment]
> @Stanley5249 , @MEDMac29 , are you trying to build from source rather than installing intel gpu wheel directly?

No, I installed it using the wheel.

**Comment by imkow** [comment]
> @imkow , do you mean it still does not work even though you have invoked the two scripts?
> 
> ```shell
> "C:\Program Files (x86)\Intel\oneAPI\pytorch-gpu-dev-0.5\oneapi-vars.bat"
> "C:\Program Files (x86)\Intel\oneAPI\ocloc\2024.2\env\vars.bat" 
> ```

@EikanWang Yes, that's what I meant. However, now, no error with latest nightly 2.6.0 update "torch-2.6.0.dev20241029%2Bxpu-cp312-cp312-win_amd64.whl" in CMD (PowerShell not tested). Yet, "torch.xpu.is_available()" is "False" on my Arc 140V on Ultra 9 288V (Lunar Lake). Is Arc 140V supported? or do I need a driver version newer than 32.0.101.6044?

**Comment by EikanWang** [comment]
@imkow , we are trying to remove the two additional steps.

**Comment by lam-mini** [comment]
@Stanley5249 ，@imkow，@EikanWang,Thanks for your reply. 
It finally works with torch-2.6.0.dev20241030%2Bxpu-cp310-cp310-win_amd64.whl .

**Comment by Stanley5249** [comment]
@imkow,

You can view my settings [here](https://github.com/Stanley5249/torch-test-xpu/blob/master/.vscode/settings.json).
This will automatically source oneAPI in the CMD within VSCode. However, I'm still uncertain about the optimal method to execute it in PowerShell.

Additionally, if you're utilizing a notebook, this approach will not function. You'll need to start the Jupyter server manually and establish a connection to it.

**Comment by GUZZ07** [comment]
Encounter the same error on lunar lake platform, I am using `torch-2.6.0.dev20241028+xpu-cp310-cp310-win_amd64.whl` , dependencyWalker says `c10_xpu.dll`'s dependency `sycl7.dll` is missing, I managed to fix this problem by installing a runtime of [oneAPI](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html)

**Comment by mengfei25** [comment]
@Stanley5249  @imkow  Looks like the following works in powershell
https://gist.github.com/scivision/196cfa0df761ad4fcace8ff269128f7b#file-oneapi-ps1
```
$Env:CC="icx"
$Env:FC="ifx"
$Env:CXX="icx"
& $Env:comspec /c '"%PROGRAMFILES(X86)%\Intel\oneAPI\2024.1\oneapi-vars.bat" && pwsh'
```
If no pwsh, you can change to `powershell`, or install latest release via `msi` installer in https://github.com/PowerShell/PowerShell/releases, it will add into `path` automatically

**Comment by GES233** [comment]
> Looks like the following works in powershell https://gist.github.com/scivision/196cfa0df761ad4fcace8ff269128f7b#file-oneapi-ps1
> 
> ```
> $Env:CC="icx"
> $Env:FC="ifx"
> $Env:CXX="icx"
> & $Env:comspec /c '"%PROGRAMFILES(X86)%\Intel\oneAPI\2024.1\oneapi-vars.bat" && pwsh'
> ```
> 
> If no pwsh, you can change to `powershell`, or install latest release via `msi` installer in https://github.com/PowerShell/PowerShell/releases, it will add into `path` automaticalITly

It works. Thank you.

Without commands:

```
> python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.version); print(ipex.version); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Conda\envs\IntelML38\lib\site-packages\torch\__init__.py", line 143, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\Conda\envs\IntelML38\lib\site-packages\torch\lib\c10_xpu.dll" or one of its dependencies.
```

With it:

```
> python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.version); print(ipex.version); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
D:\Conda\envs\IntelML38\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'D:\Conda\envs\IntelML38\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
D:\Conda\envs\IntelML38\lib\site-packages\intel_extension_for_pytorch\llm\__init__.py:9: UserWarning: failed to use huggingface generation fuctions due to: No module named 'transformers'.
  warnings.warn(f"failed to use huggingface generation fuctions due to: {e}.")
<module 'torch.version' from 'D:\\Conda\\envs\\IntelML38\\lib\\site-packages\\torch\\version.py'>
<function version at 0x000001AE6D983940>
[0]: _XpuDeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', type='gpu', driver_version='1.3.30714', total_memory=15930MB, max_compute_units=512, gpu_eu_count=512, gpu_subslice_count=64, max_work_group_size=1024, max_num_sub_groups=128, sub_group_sizes=[8 16 32], has_fp16=1, has_fp64=0, has_atomic64=1)
```

**Comment by AndrewRainfall** [comment]
Did you find a solution?

Not sure if my problem is related to this, but I got this error when tried to launch Stable Diffusion Next on Inter Arc A770 GPU:

OSError: [WinError 126] The specified module could not be found. Error loading
"D:\automatic\venv\lib\site-packages\torch\lib\c10_xpu.dll" or one of its dependencies.

**Comment by EikanWang** [comment]
@GES233 , are you using `intel_extension_for_pytorch` plus torch 2.5?

**Comment by EikanWang** [comment]
@AndrewRainfall , may I know if you have run the bat files as follows?
```
"C:\Program Files (x86)\Intel\oneAPI\pytorch-gpu-dev-0.5\oneapi-vars.bat"
"C:\Program Files (x86)\Intel\oneAPI\ocloc\2024.2\env\vars.bat" 
```

If yes, could you help run `echo %PATH%` and share the result here?

**Comment by GES233** [comment]
@EikanWang No, the version of PyTorch is `2.1.0.post2+cxx11.abi` , and IPEX is `2.1.30.post0` 。

I have other issue, but i prefer use chinese cause my bad english.

---
下午发现好像只能在 VSCode 的跑 AI 绘画的文件夹里激活环境然后成功 `import torch` 不出错，但是在别的文件夹就不好说了。

```text
> .\/activation.ps1  # 上面的脚本
> conda activate IntelML310  # 按照 https://community.intel.com/t5/AI-Tools-from-Intel/intel-extension-for-pytorch-OSError-WinError-126-The-specified/m-p/1610414 方式来安装环境
> python env_coll.py # 脚本来自 https://raw.githubusercontent.com/intel/intel-extension-for-pytorch/main/scripts/collect_env.py
D:\Conda\envs\IntelML310\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'D:\Conda\envs\IntelML310\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Collecting environment information...
=====================================
PyTorch version:   2.1.0.post2+cxx11.abi
PyTorch CXX11 ABI: No
IPEX version:      2.1.30.post0
IPEX commit:       97b37e23d
Build type:        Release

OS:                Microsoft Windows 11 专业版 (10.0.22631 64 位)
GCC version:       (GCC) 13.2.0
Clang version:     N/A
IGC version:       2024.2.1 (2024.2.1.20240711)
CMake version:     version 3.29.5-msvc4
Libc version:      N/A

Python version:    3.10.15 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:19) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform:   Windows-10-10.0.22631-SP0
Is XPU available:  True
DPCPP runtime:     N/A
MKL version:       N/A

GPU models and configuration onboard:
* Intel(R) Arc(TM) A770 Graphics

GPU models and configuration detected:
* [0] _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.30714', has_fp64=0, total_memory=15930MB, max_compute_units=512, gpu_eu_count=512)

Driver version:
* 32.0.101.6078 (20240913000000.******+***)

CPU:
Description: Intel64 Family 6 Model 151 Stepping 5
Manufacturer: GenuineIntel
Name: 12th Gen Intel(R) Core(TM) i5-12400
NumberOfCores: 6
NumberOfEnabledCore: 6
NumberOfLogicalProcessors: 12
ThreadCount: 12

Versions of relevant libraries:
[conda] dpcpp-cpp-rt              2024.1.0                 pypi_0    pypi
[conda] intel-cmplr-lib-rt        2024.1.0                 pypi_0    pypi
[conda] intel-cmplr-lic-rt        2024.1.0                 pypi_0    pypi
[conda] intel-extension-for-pytorch 2.1.30.post0             pypi_0    pypi
[conda] intel-opencl-rt           2024.1.0                 pypi_0    pypi
[conda] intel-openmp              2024.1.0                 pypi_0    pypi
[conda] mkl                       2024.1.0                 pypi_0    pypi
[conda] mkl-dpcpp                 2024.1.0                 pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] onemkl-sycl-blas          2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-datafitting   2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-dft           2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-lapack        2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-rng           2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-sparse        2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-stats         2024.1.0                 pypi_0    pypi
[conda] onemkl-sycl-vm            2024.1.0                 pypi_0    pypi
[conda] torch                     2.1.0.post2+cxx11.abi          pypi_0    pypi
[conda] torchaudio                2.1.0.post2+cxx11.abi          pypi_0    pypi
[conda] torchsde                  0.2.6                    pypi_0    pypi
[conda] torchvision               0.16.0.post2+cxx11.abi          pypi_0    pypi
[conda] transformers              4.46.1                   pypi_0    pypi
```

**Comment by EikanWang** [comment]
@GES233 , could you help migrate this issue to https://github.com/intel/intel-extension-for-pytorch ?

**Comment by AndrewRainfall** [comment]
@EikanWang yes, I found solution to my problem.

For some reason OneApi wasn't seeing VS2022.

I went Settings - System - About - Advanced System Settings - Environment Variables - System Variables - New if doesn't exist or Edit if it is wrong to "VS2022INSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" enter your path in "" - ok - ok - ok

CMD
d:
cd D:\automatic
D:\Intel\oneAPI\2024.2\oneapi-vars.bat
.\webui.bat --use-ipex --upgrade --autolaunch --debug

and it finally works

**Comment by EikanWang** [comment]
@AndrewRainfall , thanks for the information.

**Comment by mikewastedmoney** [comment]
Is there an established solution for this problem?

**Comment by Stonepia** [comment]
If you are using **powershell**, you need to do these things for full toolchain:

1. I recommend you open "Developer PowerShell for VS2022" directly. You could find it in Start Menu. It will automatically activate VS env. 

2. In this same PowerShell terminal, run the command to source oneAPI env. Note that this only works when you have one version of oneAPI installed. If there are multiple versions, please use the command mentioned earlier mentioned earlier.

```
cmd.exe "/K" '"C:\Program Files (x86)\Intel\oneAPI\setvars.bat" && powershell'
```

4. Activate conda env and run Python.


### Some issues mentioned in this issue:

If you didn't open the "Developer PowerShell for VS2022", you need to activate it manually:
```
cmd.exe "/K" "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
```

If it says you need to set VS2022INSTALLDIR, please set it accordingly. Normally this is not needed if you already activate the VS env.

```
# If you only install the build Tools:
$Env:VS2022INSTALLDIR="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"

# If you installed full Visual Studio
$Env:VS2022INSTALLDIR==C:\Program Files\Microsoft Visual Studio\2022\Community
```

**Comment by lyc280705** [comment]
I met the same problem when I use pytorch with xpu. I'm using intel extension for pytorch now and it works

**Comment by lyc280705** [comment]
What's the difference between intel extension for pytorch and pytorch+xpu. Is pytorch using gpu and npu to accelerate?

**Comment by Stonepia** [comment]
> I met the same problem when I use pytorch with xpu. I'm using [intel extension for pytorch](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.3.110%2bxpu&os=windows&package=pip) now and it works well. Will this issue be fixed in the next version of pytorch?

Yes, the issue should not exist in the next version of PyTorch. We are WIP to hide complexity for the user. You won't need to source oneAPI in future releases of PyTorch.

> What's the difference between intel extension for pytorch and pytorch+xpu. Is pytorch using gpu and npu to accelerate?

The differences between  intel-extension-for-pytorch (IPEX) and PyTorch + XPU is that:
1. prior to PyTorch 2.5, if you wish to use XPU, you must install PyTorch + IPEX.  IPEX offers Op support for XPU.
2. After PyTorch 2.5, you could use PyTorch without IPEX. IPEX offers some custom ops implemented for XPU, those ops are not upstreamed into PyTorch yet (and we are working on it)

**Comment by canbakiskan** [comment]
I have an ARC A770 and I ran into the same problem while following this guide: https://pytorch.org/docs/stable/notes/get_start_xpu.html which refers to this guide: https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html (which refers to another site if I wanted to build it for Ubuntu 24.04 or WSL running Ubuntu 24.04). I did everything on listed on those pages and yet I still get this error. Do you even test on a fresh installation of Windows before releasing? It has been how long since this card is released? 2 years? No matter what I do it doesn't seem to work. Following the same pages on WSL even BSOD's my computer, plain embarrassing...

**Comment by Stonepia** [comment]
Hi @canbakiskan , could you provide your system env info by running the following?

```Bash
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
In addition, could you try import torch on Windows after installing `libuv`?

```Bash
conda install libuv
```

**Comment by EikanWang** [comment]
As we have released PyTorch 2.6 and this case is for PT 2.5, I will close this issue. Pls. feel free reopen this issue if it is still there.
