### ISSUE TITLE
FP16 overflow sometimes results in "illegal memory access"

### ISSUE THREAD

**Issue by myleott** [pytorch/pytorch#13909]
## 🐛 Bug

FP16 overflow sometimes results in "illegal memory access". See example below.

## To Reproduce

```
>>> import torch
>>> weight = torch.nn.Parameter(torch.rand(512*3, 512).cuda()).half()
>>> bias = torch.nn.Parameter(torch.rand(512*3).cuda()).half()
>>> x = torch.nn.functional.linear(torch.rand(32, 512).cuda().half(), weight, bias)
>>> loss = x.sum()
>>> loss
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCTensorMathCompareT.cuh line=69 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/myleott/.conda/envs/fairseq-fp16-20181030/lib/python3.6/site-packages/torch/tensor.py", line 66, in __repr__
    return torch._tensor_str._str(self)
  File "/private/home/myleott/.conda/envs/fairseq-fp16-20181030/lib/python3.6/site-packages/torch/_tensor_str.py", line 275, in _str
    tensor_str = _tensor_str(self, indent)
  File "/private/home/myleott/.conda/envs/fairseq-fp16-20181030/lib/python3.6/site-packages/torch/_tensor_str.py", line 193, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/private/home/myleott/.conda/envs/fairseq-fp16-20181030/lib/python3.6/site-packages/torch/_tensor_str.py", line 84, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
  File "/private/home/myleott/.conda/envs/fairseq-fp16-20181030/lib/python3.6/site-packages/torch/functional.py", line 271, in isfinite
    return (tensor == tensor) & (tensor.abs() != inf)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generated/../THCTensorMathCompareT.cuh:69
```

## Expected behavior

In the past this would result in inf:

```
>>> import torch
>>> weight = torch.nn.Parameter(torch.rand(512*3, 512).cuda()).half()
>>> bias = torch.nn.Parameter(torch.rand(512*3).cuda()).half()
>>> x = torch.nn.functional.linear(torch.rand(32, 512).cuda().half(), weight, bias)
>>> loss = x.sum()
>>> loss
tensor(inf, device='cuda:0', dtype=torch.float16, grad_fn=<SumBackward0>)
```

## Environment

```
PyTorch version: 1.0.0.dev20181112
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 396.51
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch-nightly (1.0.0.dev20181112)
[pip] torchvision-nightly (0.2.1)
[conda] magma-cuda90              2.3.0                         1    pytorch
[conda] magma-cuda92              2.3.0                         1    pytorch
[conda] torch-nightly             1.0.0.dev20181112           <pip>
[conda] torchvision-nightly       0.2.1                     <pip>
```

**Comment by kevin-w-li** [comment]
I have encountered same error for std()
