### ISSUE TITLE
test/functorch/test_ops.py:test_extremal_numerics_l1_loss_cpu segfaults when wrapped with Dynamo

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#139103]
`PYTORCH_TEST_WITH_DYNAMO=1 pytest test/functorch/test_ops.py -k test_extremal_numerics_l1_loss_cpu` segfaults.

Unsure why it wasn't until https://github.com/pytorch/pytorch/pull/138233 that this test was segfaulted in CI, since it happens locally before the PR. The PR skips the test using `skipIfTorchDynamo` (since adding it to `test/dynamo_skips` still attempts to run the test).

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @Chillee @samdow @kshitij12345 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames @rec

**Comment by zou3519** [comment]
cc @guilhermeleobas 

hi-pri for segfault

**Comment by guilhermeleobas** [comment]
William, which version of Python are you using? The test works for me on Python 3.9:

```bash
$ PYTORCH_TEST_WITH_DYNAMO=1 python test/functorch/test_ops.py -k test_extremal_numerics_l1_loss_cpu
.
----------------------------------------------------------------------
Ran 1 test in 2.483s
```

**Comment by williamwen42** [comment]
I'm on 3.12.

**Comment by zou3519** [comment]
It also segfaulted for me on 3.10.15 on a mac

**Comment by guilhermeleobas** [comment]
Let me try on 3.12. On 3.10 and 3.11, the test fails, which I think is "expected":

```python
======================================================================
FAIL: test_extremal_numerics_l1_loss_cpu (__main__.TestOperatorsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ysiraichi/work/pytorch/0/torch/testing/_internal/common_utils.py", line 2996, in wrapper
    method(*args, **kwargs)
  File "/home/ysiraichi/work/pytorch/0/torch/testing/_internal/common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/ysiraichi/work/pytorch/0/test/functorch/test_ops.py", line 2197, in test_extremal_numerics_l1_loss
    self._compare_jacobians_of_vjp(
  File "/home/ysiraichi/work/pytorch/0/test/functorch/test_ops.py", line 1740, in _compare_jacobians_of_vjp
    jacobian_jvp = jacfwd(get_vjp, argnums)(*cotangents_and_primals)
  File "/home/ysiraichi/work/pytorch/0/test/functorch/test_ops.py", line 1741, in torch_dynamo_resume_in__compare_jacobians_of_vjp_at_1740
    jacobian_vjp = jacrev(get_vjp, argnums)(*cotangents_and_primals)
  File "/home/ysiraichi/work/pytorch/0/test/functorch/test_ops.py", line 1751, in torch_dynamo_resume_in__compare_jacobians_of_vjp_at_1741
    self.assertEqual(jacobian_jvp, jacobian_vjp)
  File "/home/ysiraichi/work/pytorch/0/torch/testing/_internal/common_utils.py", line 3904, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 60 / 60 (100.0%)
Greatest absolute difference: 0.01666666753590107 at index (0, 0, 0) (up to 1e-05 allowed)
Greatest relative difference: 1.0 at index (0, 0, 0) (up to 1.3e-06 allowed)

The failure occurred for item [0][0]
```

**Comment by williamwen42** [comment]
I can no longer repro locally haha - let's try re-enabling the test (adding it to dynamo xfails/skips) and see if CI is happy.

**Comment by guilhermeleobas** [comment]
Ok! I'll push a PR changing this in a bit.
