### ISSUE TITLE
`torch.compile` errors when inputs memory overlap. 

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#139111]
### 🐛 Describe the bug

Eager successfully executes the program below. However, when using `torch.compile` with dynamic shapes, it errors:

```python
@torch.compile(dynamic=True)
def f(a, b):
    a.add_(1)
    b.add_(1)
    return a

x = torch.ones(10)
f(x[:3], x[:3])
```

```python
Traceback (most recent call last):
  File "examples/repr.py", line 44, in <module>
    f(*args)
  File "torch/_dynamo/eval_frame.py", line 550, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 1364, in __call__
    return self._torchdynamo_orig_callable(
  File "torch/_dynamo/convert_frame.py", line 1155, in __call__
    result = self._inner_convert(
  File "torch/_dynamo/convert_frame.py", line 544, in __call__
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 964, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/convert_frame.py", line 695, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 728, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 229, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 657, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2887, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 3078, in RETURN_VALUE
    self._return(inst)
  File "torch/_dynamo/symbolic_convert.py", line 3063, in _return
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 1131, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "torch/_dynamo/output_graph.py", line 1400, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/output_graph.py", line 1447, in call_user_compiler
    return self._call_user_compiler(gm)
  File "torch/_dynamo/output_graph.py", line 1496, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1477, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 2249, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1605, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "torch/_functorch/aot_autograd.py", line 1087, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "torch/_functorch/aot_autograd.py", line 1063, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "torch/_functorch/aot_autograd.py", line 524, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "torch/_functorch/aot_autograd.py", line 762, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 142, in aot_dispatch_base
    flat_fn, flat_args, fw_metadata = pre_compile(
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2153, in pre_compile
    flat_fn, flat_args, fw_metadata = wrapper.pre_compile(
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1018, in pre_compile
    flat_args_with_synthetic_bases, synthetic_base_info = merge_view_inputs(
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1412, in merge_view_inputs
    arg_to_old_idx_map = {arg: i for (i, arg) in enumerate(fwd_inputs)}
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1412, in <dictcomp>
    arg_to_old_idx_map = {arg: i for (i, arg) in enumerate(fwd_inputs)}
  File "torch/__init__.py", line 537, in __hash__
    raise TypeError("unhashable type: non-nested SymInt")
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
TypeError: unhashable type: non-nested SymInt

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.6.0a0+git362ca54
Is debug build: True
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

cc @ezyang @chauhang @penguinwu @bobrenjc93

**Comment by ezyang** [comment]
Probably not too hard to fix, if the code snippet is OK to key on sympy expression structure then can just swap in the hashable symint wrapper

**Comment by ysiraichi** [comment]
@ezyang Do you mean that I should create a hashable SymInt wrapper (like the one below), or is there an existing one?

```python
class HashableSymIntWrapper:
    def __init__(self, value: SymInt):
        self.value  = value

    def __hash__(self):
        try:
            return hash(self.value)
        except Exception:
            return hash(self.value.node.expr)
```

**Comment by ezyang** [comment]
there's an existing one in torch.fx.experimental.symbolic_shapes
