### ISSUE TITLE
[Upstream Triton] attrs_description `KeyError: 'cls'`

### ISSUE THREAD

**Issue by jataylo** [pytorch/pytorch#139179]
### 🐛 Describe the bug

In preparation for release/2.6 (https://github.com/pytorch/pytorch/issues/139175)  I attempted some local runs with tip-of-tree triton main. The majority of the unit tests fail with these message due to a change in the dictionary format.

**Reproducer:**
`python test/inductor/test_torchinductor.py -k "test_avg_pool2d8_cuda" --verbose`

**Traceback:**
======================================================================
ERROR: test_avg_pool2d8_cuda (__main__.GPUTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2996, in wrapper
    method(*args, **kwargs)
  File "/workspace/pytorch/test/inductor/test_torchinductor.py", line 11635, in new_test
    return value(self)
  File "/workspace/pytorch/test/inductor/test_torchinductor.py", line 4819, in test_avg_pool2d8
    self.common(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/test/inductor/test_torchinductor.py", line 602, in check_model_gpu
    check_model(
  File "/workspace/pytorch/test/inductor/test_torchinductor.py", line 443, in check_model
    actual = run(*example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 554, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 1401, in __call__
    return self._torchdynamo_orig_callable(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 546, in __call__
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 979, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 705, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 740, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 659, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2909, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1115, in run
    while self.step():
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1027, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 3100, in RETURN_VALUE
    self._return(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 3085, in _return
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1131, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1401, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1448, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1497, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1478, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/test/inductor/test_torchinductor.py", line 435, in compile_fx_wrapper
    return compile_fx(model_, example_inputs_)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1686, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1105, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1081, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 528, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 780, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 196, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1506, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1575, in _fw_compiler_base
    return inner_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 578, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 100, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 735, in _compile_fx_inner
    compiled_graph = FxGraphCache.load(
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1460, in load
    compiled_graph = compile_fx_fn(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 642, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 953, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 2029, in compile_to_fn
    return self.compile_to_module().call
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1951, in compile_to_module
    return self._compile_to_module()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1957, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1896, in codegen
    self.scheduler.codegen()
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 3457, in codegen
    return self._codegen()
  File "/workspace/pytorch/torch/_inductor/scheduler.py", line 3536, in _codegen
    self.get_backend(device).codegen_node(node)
  File "/workspace/pytorch/torch/_inductor/codegen/cuda_combined_scheduling.py", line 80, in codegen_node
    return self._triton_scheduling.codegen_node(node)
  File "/workspace/pytorch/torch/_inductor/codegen/simd.py", line 1195, in codegen_node
    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
  File "/workspace/pytorch/torch/_inductor/codegen/simd.py", line 1384, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "/workspace/pytorch/torch/_inductor/codegen/triton.py", line 2850, in codegen_kernel
    triton_meta["configs"] = [config_of(signature)]
  File "/workspace/pytorch/torch/_inductor/codegen/triton_utils.py", line 176, in config_of
    return AttrsDescriptorWrapper(divisible_by_16, equal_to_1)
  File "/workspace/pytorch/torch/_inductor/runtime/hints.py", line 54, in AttrsDescriptorWrapper
    res = AttrsDescriptor.from_dict(kwargs)
  File "/root/triton/python/triton/backends/compiler.py", line 166, in from_dict
    attrs_descriptor = _descriptor_table[data["cls"]]()
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
KeyError: 'cls'

Seems that the dictionary was further updated since this change https://github.com/pytorch/pytorch/commit/487873f7cafeb0fd390eaefe40496b804bceabbd, this will require updating and requires an additional PR to upstream triton e.g. https://github.com/triton-lang/triton/pull/4888, but this PR also needs to be updated with the dictionary change.

### Versions

Triton commit: 3549db850c7daf86624a624378e12d2a5a2bd236
PyTorch commit: 4dd04db5d0962fb8a1925cee831b9eb4f41ca4fd

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov @bertmaher @int3 @davidberard98 @nmacchioni @embg @peterbell10

**Comment by jataylo** [comment]
cc: @alexbaden

**Comment by jataylo** [comment]
Something like this seems to work:
```
def AttrsDescriptorWrapper(
    divisible_by_16=None,
    equal_to_1=None,
    divisibility_value=16,
    equal_to_value=1,
):
    return AttrsDescriptor.from_dict({
        "cls": "AttrsDescriptor",
        "arg_properties": {
            "tt.divisibility": list(divisible_by_16 or []),
            "tt.equal_to": list(equal_to_1 or []),
        },
        "property_values": {
            "tt.divisibility": divisibility_value,
            "tt.equal_to": equal_to_value,
        }
    })
```

But needs a corresponding update to triton e.g. https://github.com/triton-lang/triton/pull/4888#issuecomment-2442878984
