### ISSUE TITLE
find_spec does something weird to Python Path when loading modules

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#139200]
### 🐛 Describe the bug

I tried adding a top level logging import to torch._dynamo module. When I did this, and then I attempt to TORCH_LOGS=dynamo, I end upw ith this error:

```
(/home/ezyang/local/b/pytorch-env) [ezyang@devgpu005.nha1 ~/local/b/pytorch (9b84074e)]$ TORCH_LOGS=dynamo,dynamic,+torch._dynamo.pgo python test/dynamo/test_pgo.py 
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/test/dynamo/test_pgo.py", line 5, in <module>
    import torch.compiler.config
  File "/data/users/ezyang/b/pytorch/torch/__init__.py", line 2666, in <module>
    _logging._init_logs()
  File "/data/users/ezyang/b/pytorch/torch/_logging/_internal.py", line 927, in _init_logs
    _update_log_state_from_env()
  File "/data/users/ezyang/b/pytorch/torch/_logging/_internal.py", line 737, in _update_log_state_from_env
    log_state = _parse_log_settings(log_setting)
  File "/data/users/ezyang/b/pytorch/torch/_logging/_internal.py", line 716, in _parse_log_settings
    elif _is_valid_module(name):
  File "/data/users/ezyang/b/pytorch/torch/_logging/_internal.py", line 729, in _is_valid_module
    spec = importlib.util.find_spec(qname)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/__init__.py", line 45, in <module>
    log = logging.getLogger(__name__)
AttributeError: module 'torch._dynamo.logging' has no attribute 'getLogger'. Did you mean: 'get_loggers'?
```

Somehow, the logging import got pointed to torch._dynamo.logging instead of top level logging module.

### Versions

main

**Comment by Skylion007** [comment]
`If name is for a submodule (contains a dot), the parent module is automatically imported.` from importlib doc.  Seems like the issue is importlib is overwriting the stdlib importer logger?

**Comment by ezyang** [comment]
Not sure how that follows: the parent of torch._dynamo is torch?

**Comment by Skylion007** [comment]
It's importing `torch.dynamo.logging as logging` likely

**Comment by malfet** [comment]
To much modules patching :) (`@exposed_in("foo")` decorator is scary :) )

**Comment by ezyang** [comment]
But why is it doing that LOL

**Comment by Skylion007** [comment]
@ezyang if you `import logging as std_logging` at the top of the `torch._dynamo.__init__` and use that, it might fix it. I think we are having some logging import shadowing shenanigans.

**Comment by ezyang** [comment]
I worked around it, but when you say "import logging" in a submodule that has a file named logging.py it shouldn't get picked up. It shouldn't be related to qname since it's the import statement that's gotten messed up. It feels like importlib improperly set torch/_dynamo as the base directory which it should not do
