### ISSUE TITLE
Plan to support “discrete” dynamic dimension on torch.export

### ISSUE THREAD

**Issue by swmoon00** [pytorch/pytorch#139307]
### 🚀 The feature, motivation and pitch

Is there any plan for the `torch.export` team to support the set-based dynamism in addition to range-based dynamism?

Below is a small repro code for discrete `Dim` failure mode. The `torch._check` is supposed to work within discrete sets, but it fails.

```python
import torch

class Model(torch.nn.Module):
    def forward(self, x):
        # torch._check(2 <= x.shape[0] <= 3)  # this works
        torch._check(x.shape[0] in {2, 3})
        return x

torch.export.export(
    Model(),
    (torch.zeros(2),),
    dynamic_shapes={
        "x": {
            0: torch.export.Dim("discrete", min=2, max=3)
        }
    }
)
```

### Additional context

The conventional use of the dynamic dimension on `torch.export` is to use the continuum of the variables like `Dim(min=3, max=12)`, which is suited for accepting dynamic batch size for example.

Our team is trying to support some level of “discrete” dynamism on the neural network, for providing “image” mode and “video” mode for the vision transformer.

To show some idea behind this, here is a pseudocode for doing the operation. The specifics are not same in detail.

```python
import torch

class ImgVideoModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.emb_dim = 8
        self.vid_len = 12
        self.img_pos_embed = torch.nn.Parameter(torch.zeros(1, 1, self.emb_dim))
        self.vis_pos_embed = torch.nn.Parameter(torch.zeros(1, self.vid_len, self.emb_dim))
        self.projector = TransformerWithLargeParameters(...)
    def forward(self, x):
        # x: [B, 1, C] or [B, 12, C]
        B, T, C = x.size()
        x = torch.cond(T == 1, lambda t: t + self.img_pos_embed, lambda t: t + self.vis_pos_embed, (x,))
        # This is the intended behavior of the model.
        # if T == 1:
        #     x = x + self.img_pos_embed
        # else:
        #     assert T == 12
        #     x = x + self.vis_pos_embed
        x = self.projector(x)
        return x

inp = torch.rand(2, 12, 8)
bs = torch.export.Dim("bs")
seq_len = torch.export.Dim("seq_len", min=1, max=12)
ep = torch.export.export(ImgVideoModel(), (inp,), dynamic_shapes={"x": {0: bs, 1: seq_len}})
print(ep)
```

The `torch.export` immediately fails, because the second `lambda` function inside `torch.cond` is not compatible with the length other than 12.

Since there is no way to enforce the model to accept the “set” based constraints other than the continuum of the shapes, our team has no way other than exporting two almost-identical models with sharing large sets of common transformer weights.

cc @ezyang @chauhang @penguinwu @bobrenjc93 @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by vadimkantorov** [comment]
I also wonder if it's possible to parse native Python `assert` statements (e.g. supporting constraints on shape elements and enforcing eq/lt relations between shapes of different tensors) and transform them into torch.compile constraints?
- https://github.com/pytorch/pytorch/issues/46948

**Comment by ydwu4** [comment]
Error message:
```
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0] Error while creating guard:
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0] Name: ''
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     Source: shape_env
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     Create Function: SHAPE_ENV
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     Guard Types: None
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     Code List: None
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     Object Weakref: None
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     Guarded Class Weakref: None
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0] Traceback (most recent call last):
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]   File "/data/users/yidi/pytorch/torch/_guards.py", line 298, in create
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     return self.create_fn(builder, self)
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]   File "/data/users/yidi/pytorch/torch/_dynamo/guards.py", line 1766, in SHAPE_ENV
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     code_parts, verbose_code_parts = output_graph.shape_env.produce_guards_verbose(
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]   File "/data/users/yidi/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5056, in produce_guards_verbose
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]     raise ConstraintViolationError(
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0] torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (seq_len)! For more information, run with TORCH_LOGS="+dynamic".
E1104 09:45:04.172000 3966607 torch/_guards.py:300] [0/0]   - Not all values of seq_len = L['x'].size()[1] in the specified range seq_len <= 12 are valid because seq_len was inferred to be a constant (12).
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0] Created at:
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]   File "/data/users/yidi/pytorch/torch/_dynamo/convert_frame.py", line 641, in transform
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]     tracer = InstructionTranslator(
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]   File "/data/users/yidi/pytorch/torch/_dynamo/symbolic_convert.py", line 2802, in __init__
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]     output=OutputGraph(
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]   File "/data/users/yidi/pytorch/torch/_dynamo/output_graph.py", line 321, in __init__
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]     self.init_ambient_guards()
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]   File "/data/users/yidi/pytorch/torch/_dynamo/output_graph.py", line 470, in init_ambient_guards
E1104 09:45:04.173000 3966607 torch/_guards.py:302] [0/0]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
Traceback (most recent call last):
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 658, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/data/users/yidi/pytorch/torch/_dynamo/eval_frame.py", line 1578, in inner
    raise constraint_violation_error
  File "/data/users/yidi/pytorch/torch/_dynamo/eval_frame.py", line 1533, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/_dynamo/eval_frame.py", line 554, in _fn
    return fn(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/_dynamo/convert_frame.py", line 1443, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/yidi/pytorch/torch/_dynamo/convert_frame.py", line 548, in __call__
    return _compile(
  File "/data/users/yidi/pytorch/torch/_dynamo/convert_frame.py", line 981, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/yidi/pytorch/torch/_dynamo/convert_frame.py", line 707, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/yidi/pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/_dynamo/convert_frame.py", line 839, in _compile_inner
    check_fn = CheckFunctionManager(
  File "/data/users/yidi/pytorch/torch/_dynamo/guards.py", line 2183, in __init__
    guard.create(builder)
  File "/data/users/yidi/pytorch/torch/_guards.py", line 298, in create
    return self.create_fn(builder, self)
  File "/data/users/yidi/pytorch/torch/_dynamo/guards.py", line 1766, in SHAPE_ENV
    code_parts, verbose_code_parts = output_graph.shape_env.produce_guards_verbose(
  File "/data/users/yidi/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5056, in produce_guards_verbose
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (seq_len)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of seq_len = L['x'].size()[1] in the specified range seq_len <= 12 are valid because seq_len was inferred to be a constant (12).

Suggested fixes:
  seq_len = 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/users/yidi/pytorch/output.py", line 35, in <module>
    ep = torch.export.export(
  File "/data/users/yidi/pytorch/torch/export/__init__.py", line 368, in export
    return _export(
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 1029, in wrapper
    raise e
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 1002, in wrapper
    ep = fn(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/export/exported_program.py", line 121, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 1942, in _export
    export_artifact = export_func(  # type: ignore[operator]
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 1249, in _strict_export
    return _strict_export_lower_to_aten_ir(
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 1277, in _strict_export_lower_to_aten_ir
    gm_torch_level = _export_to_torch_ir(
  File "/data/users/yidi/pytorch/torch/export/_trace.py", line 675, in _export_to_torch_ir
    raise UserError(UserErrorType.CONSTRAINT_VIOLATION, str(e))  # noqa: B904
torch._dynamo.exc.UserError: Constraints violated (seq_len)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of seq_len = L['x'].size()[1] in the specified range seq_len <= 12 are valid because seq_len was inferred to be a constant (12).

Suggested fixes:
  seq_len = 12
```

**Comment by ezyang** [comment]
If the graphs end up differing between the discrete values there's nothing you can do, you have to torch.cond your way to victory or export multiple graphs.

**Comment by swmoon00** [comment]
> If the graphs end up differing between the discrete values there's nothing you can do, you have to torch.cond your way to victory or export multiple graphs.

Understood. Currently the dynamic dimension is in the continuum of the shapes, so it is really challenging to capture this branch in a single graph.
For example one of the shapes can be 2 or 4 and not in between, there is no way to enforce this as a dynamic dimension and the graph capturing will not be run as intended.

Is there any plan to support this discrete dynamic dim in the future? Or is it not possible or appropriate thing to support because of the inherent design of dynamic graph capturing?

**Comment by ezyang** [comment]
The problem is specifically around capturing and preserving branching behavior in the set of computations you do at runtime. This is only supported through torch.cond. There may be some auxiliary problems where you are unable to refine shape symbols temporarily inside cond but those we should fix.

**Comment by paul-twelvelabs** [comment]
@ezyang Following this thread, can you add a bit more color to your response? In this modified toy example above, 

```python
import torch
from torch._dynamo import guards

class Model(torch.nn.Module):
    def forward(self, x):
        torch._check(x.shape[0] in {2, 3})
        return x

torch.export.export(
    Model(),
    (torch.zeros(3),),
    dynamic_shapes={
        "x": {
            0: torch.export.Dim("x", min=2, max=3)
        }
    }
)
```

the assert `torch._check(x.shape[0] in {2, 3})` forces `torch.export` to infer `x` has a constant shape of 3. That seems odd, especially given that shape guards can check for x in a range (e.g. `torch._check(2 <= x.shape[0] <= 3)` is completely fine). In principle, couldn't there be a `torch.export.Dim` object that took `values={...}` as a param and applied a disjunctive shape guard, e.g.

```python
torch.export.Dim("x", values={2, 3})
```

which would then pass
```python
torch._check(x.shape[0] == 2) or torch._check(x.shape[0] == 3)
```

**Comment by ezyang** [comment]
We technically support disjunction but it is not exposed in a user facing way because it's.... not very useful 🤣 . We don't currently do any reasoning based off of the information, so it would basically be equivalent to not having the check at all. I suppose that in principle discrete values could be used to statically reason about unbacked SymInts, as you could enumerate all disjunct values to see if a given expression is statically known in all situations... but that's pretty obscure.

When you write `x.shape[0] in {2, 3}`, there is an additional problem that we must recognize that this is something that we can generate a disjunction on, as opposed to guarding. Without Dynamo, this would be impossible to do as the only thing the reasoning system would see is the equality test on 2 and then the test on 3 (or, I suppose in this case, you would try to hash the SymInt, which doesn't work.) With Dynamo, in principle, we could write a special case for test of membership in a set which is known to be constant...... I guess I would accept a patch that does this, but it seems pretty niche.

**Comment by bhack** [comment]
Is this a dup of https://github.com/pytorch/pytorch/issues/136119

**Comment by masnesral** [comment]
> Is this a dup of https://github.com/pytorch/pytorch/issues/136119

Issue scrubbing. @pianpwk do you know if it's a dup?

**Comment by pianpwk** [comment]
Yep, closing as a duplicate, keeping the older issue
