### ISSUE TITLE
inspect.Signature with functools.partial partially applying tensors doesn't work

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#139374]
### 🐛 Describe the bug

```
import torch
from triton.testing import do_bench
from torch.nn.attention.flex_attention import create_block_mask, flex_attention, noop_mask, BlockMask
import torch.nn.functional as F
import functools

torch.manual_seed(0)

import torch
torch.set_default_device('cuda')

def sliding_window(b, h, q_idx, kv_idx, val):
    return (q_idx - kv_idx).abs() < val

sliding_window2 = functools.partial(sliding_window, val=torch.randn(()))
torch.compile(create_block_mask, fullgraph=True)(sliding_window2, None, None, 1024, 1024)
```

```
Traceback (most recent call last):
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/misc.py", line 383, in __init__
    self.fn = self.inspected.get_function()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 908, in get_function
    return self.as_python_constant()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 930, in as_python_constant
    **{k: v.as_python_constant() for k, v in self.keywords.items()},
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 930, in <dictcomp>
    **{k: v.as_python_constant() for k, v in self.keywords.items()},
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/base.py", line 219, in as_python_constant
    raise NotImplementedError(f"{self} is not a constant")
NotImplementedError: TensorVariable() is not a constant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/users/chilli/repro.py", line 196, in <module>
    block_mask = get_cp_flex_attn_bias("block_causal", tokens, eos_id=1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/chilli/repro.py", line 190, in get_cp_flex_attn_bias
    cp_flex_attn_bias.block_mask = torch.compile(create_block_mask, fullgraph=True)(**kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/eval_frame.py", line 554, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 1371, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 544, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 967, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 695, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 728, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 229, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/convert_frame.py", line 657, in transform
    tracer.run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2892, in run
    super().run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1100, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1012, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 620, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2399, in CALL
    self._call(inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2393, in _call
    self.call_function(fn, args, kwargs)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 947, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 345, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/functions.py", line 124, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 953, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 3107, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 3235, in inline_call_
    tracer.run()
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1100, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1012, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 620, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2399, in CALL
    self._call(inst)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2393, in _call
    self.call_function(fn, args, kwargs)
  File "/home/chilli/local/pytorch/torch/_dynamo/symbolic_convert.py", line 947, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/misc.py", line 963, in call_function
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/misc.py", line 373, in create
    return InspectSignatureVariable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chilli/local/pytorch/torch/_dynamo/variables/misc.py", line 389, in __init__
    unimplemented("inspect.signature with non-constant function")
  File "/home/chilli/local/pytorch/torch/_dynamo/exc.py", line 305, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: inspect.signature with non-constant function

```
cc: @williamwen42 @anijain2305 

### Versions

N/A

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames

**Comment by schmidt-jake** [comment]
I think I'm also hitting this issue.

**Comment by mirceamironenco** [comment]
Had the same issue while trying to compile with `fullgraph=True` with a document mask_mod, due to the `inspect.signature` in `_get_mod_type`. The following attempted fix will also fail:
```py
def _get_mod_type(fn: Callable) -> _ModificationType:
    num_defaults = 0 if fn.__defaults__ is None else len(fn.__defaults__)
    num_positional_args = fn.__code__.co_argcount - num_defaults
    ...
```
with `torch._dynamo.exc.Unsupported: call_method GetAttrVariable(NestedUserFunctionVariable(), __defaults__) __len__ () {}`.

**Comment by skrsna** [comment]
+1 still seeing the same issue on torch v2.6 when trying to compile with `fullgraph=True` on a module that uses flex attention and block mask 

```
Collecting environment information...
PyTorch version: 2.6.0+cu126
Is debug build: False
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.11.4 (main, Jan 23 2025, 00:15:14) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-122-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.6.77
```

**Comment by williamwen42** [comment]
@anijain2305 check if tracing through `inspect` resolves this issue?

**Comment by anijain2305** [comment]
Assigning to myself. I will debug this next week.

**Comment by anijain2305** [comment]
https://github.com/pytorch/pytorch/pull/146339 should fix this.

**Comment by StrongerXi** [comment]
Getting a different error on main d0f08dc3ebc now:

```
Traceback (most recent call last):
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2528, in CALL
    self._call(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2522, in _call
    self.call_function(fn, args, kwargs)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 384, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 186, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1658, in exception_handler
    raise raised_exception
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2528, in CALL
    self._call(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2522, in _call
    self.call_function(fn, args, kwargs)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 384, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 186, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1658, in exception_handler
    raise raised_exception
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2528, in CALL
    self._call(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2522, in _call
    self.call_function(fn, args, kwargs)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 897, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 384, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 186, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1658, in exception_handler
    raise raised_exception
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2528, in CALL
    self._call(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2522, in _call
    self.call_function(fn, args, kwargs)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 384, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 186, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1658, in exception_handler
    raise raised_exception
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2528, in CALL
    self._call(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2522, in _call
    self.call_function(fn, args, kwargs)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 384, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 186, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1658, in exception_handler
    raise raised_exception
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2339, in CONTAINS_OP
    self.push(right.call_method(self, "__contains__", [left], {}))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/lists.py", line 663, in call_method
    return super().call_method(tx, name, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/lists.py", line 146, in call_method
    return iter_contains(self.unpack_var_sequence(tx), args[0], tx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/utils.py", line 2502, in iter_contains
    check = BuiltinVariable(operator.eq).call_function(tx, [x, search], {})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 1108, in call_function
    return handler(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 945, in builtin_dispatch
    rv = fn(tx, args, kwargs)
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 834, in <lambda>
    handlers.append(lambda tx, args, _: binop_handler(tx, *args))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 567, in handler
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1009, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3286, in inline_call
    return tracer.inline_call_()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3444, in inline_call_
    self.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1658, in exception_handler
    raise raised_exception
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1068, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1943, in LOAD_METHOD
    self._load_attr(inst)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1967, in _load_attr
    result = BuiltinVariable(getattr).call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 1108, in call_function
    return handler(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 945, in builtin_dispatch
    rv = fn(tx, args, kwargs)
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 850, in call_self_handler
    result = self_handler(tx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/builtin.py", line 1894, in call_getattr
    return obj.var_getattr(tx, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/variables/functions.py", line 1493, in var_getattr
    raise_observed_exception(AttributeError, tx)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/exc.py", line 368, in raise_observed_exception
    raise observed_exception_map[exc_type]
torch._dynamo.exc.ObservedAttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryanguo99/scratch/repro.py", line 16, in <module>
    torch.compile(create_block_mask, fullgraph=True)(sliding_window2, None, None, 1024, 1024)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/eval_frame.py", line 585, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 1393, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 585, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 1023, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_utils_internal.py", line 97, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 746, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 782, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 1418, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 256, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/convert_frame.py", line 700, in transform
    tracer.run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 3065, in run
    super().run()
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1158, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1073, in step
    self.exception_handler(e)
  File "/home/ryanguo99/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1657, in exception_handler
    raise Unsupported("Observed exception")
torch._dynamo.exc.Unsupported: Observed exception

from user code:
   File "/home/ryanguo99/repos/pytorch/torch/nn/attention/flex_attention.py", line 864, in create_block_mask
    mod_type = _get_mod_type(mask_mod)

**Comment by williamwen42** [comment]
Can this code run in eager? The graph break suggests that an exception is attempting to escape the compiled region.

**Comment by StrongerXi** [comment]
Just checked, works in eager.

**Comment by anijain2305** [comment]
Will take a look this week.

**Comment by anijain2305** [comment]
https://github.com/pytorch/pytorch/pull/151168 should fix this.
