### ISSUE TITLE
inductor/test_move_constructors_to_cuda.py::TestMoveConstructorsToCuda::test_multi_gpu unit test failure

### ISSUE THREAD

**Issue by nWEIdia** [pytorch/pytorch#139520]
### 🐛 Describe the bug

inductor/test_move_constructors_to_cuda.py::TestMoveConstructorsToCuda::test_multi_gpu FAILED [1.4059s] [ 14%]
==================================== RERUNS ====================================
__________________ TestMoveConstructorsToCuda.test_multi_gpu ___________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 2983, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/inductor/test_move_constructors_to_cuda.py", line 103, in test_multi_gpu
    self._check_fn(foo, True, inp)
  File "/opt/pytorch/pytorch/test/inductor/test_move_constructors_to_cuda.py", line 31, in _check_fn
    FileCheck().check("cpp_fused").run(code[0])
RuntimeError: Expected to find "cpp_fused" but did not find it
Searched string:
# AOT ID: ['0_inference']
~~~~~~~~~ <--- HERE
from ctypes import c_void_p, c_long, c_int
import torch
From CHECK: cpp_fused
To execute this test, run the following from the base repo dir:
    python test/inductor/test_move_constructors_to_cuda.py TestMoveConstructorsToCuda.test_multi_gpu


tested on A100x2 systems 

### Versions

nightly versions

**Comment by nWEIdia** [comment]
Bisection points to: 

https://github.com/pytorch/pytorch/pull/134748 

cc @jansel

**Comment by nWEIdia** [comment]
Is the fix available soon? 
cc @eqy
