### ISSUE TITLE
Error when exporting the torchaudio Conformer model

### ISSUE THREAD

**Issue by neuropilot-captain** [pytorch/pytorch#139610]
### 🐛 Describe the bug

Code to reproduce the problem

```
import torch
import torchaudio.models as models

instance = models.Conformer(
    input_dim=80,
    num_heads=4,
    ffn_dim=128,
    num_layers=4,
    depthwise_conv_kernel_size=31,
)
lengths = torch.randint(1, 400, (10,))  # (batch,)
input_ = torch.rand(10, int(lengths.max()), 80)  # (batch, num_frames, input_dim)
inputs = (input_, lengths)

# Failed to export
exported_program = torch.export.export(instance.eval(), inputs)
# exported_program = torch.export.export(instance.eval(), inputs, strict=False)
# exported_program = torch.export.export_for_training(instance.eval(), inputs)
```

Error Logs
```
W1030 05:12:28.314000 28493 /home/neuropilot/.pyenv/versions/3.11.8/envs/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py:6067] [0/0] failed during evaluate_expr(Eq(u0, 399), hint=None, size_oblivious=False, forcing_spec=False
E1030 05:12:28.315000 28493 /home/neuropilot/.pyenv/versions/3.11.8/envs/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/recording.py:298] [0/0] failed while running evaluate_expr(*(Eq(u0, 399), None), **{'fx_node': False})
Traceback (most recent call last):
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 2175, in run_node
    return nnmodule(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/functional.py", line 6216, in multi_head_attention_forward
    assert key_padding_mask.shape == (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/__init__.py", line 685, in __bool__
    return self.node.bool_()
           ^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/sym_node.py", line 511, in bool_
    return self.guard_bool("", 0)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/sym_node.py", line 449, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
    return retlog(fn(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 6063, in evaluate_expr
    return self._evaluate_expr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 6212, in _evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(u0, 399) (unhinted: Eq(u0, 399)).  (Size-like symbols: u0)

Caused by: x, _ = self.self_attn(  # torchaudio/models/conformer.py:194 in forward (nn/functional.py:6216 in multi_head_attention_forward)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 292, in forward
    x = layer(x, encoder_padding_mask)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 194, in forward
    x, _ = self.self_attn(

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 2055, in get_fake_value
    ret_val = wrap_fake_exception(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 1612, in wrap_fake_exception
    return fn()
           ^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 2056, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 2188, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 2175, in run_node
    return nnmodule(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/functional.py", line 6216, in multi_head_attention_forward
    assert key_padding_mask.shape == (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/__init__.py", line 685, in __bool__
    return self.node.bool_()
           ^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/sym_node.py", line 511, in bool_
    return self.guard_bool("", 0)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/sym_node.py", line 449, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
    return retlog(fn(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 6063, in evaluate_expr
    return self._evaluate_expr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 6212, in _evaluate_expr
    raise self._make_data_dependent_error(
RuntimeError: Failed running call_module L__self___conformer_layers_0_self_attn(*(), **{'query': FakeTensor(..., size=(399, 10, 80), grad_fn=<NativeLayerNormBackward0>), 'key': FakeTensor(..., size=(399, 10, 80), grad_fn=<NativeLayerNormBackward0>), 'value': FakeTensor(..., size=(399, 10, 80), grad_fn=<NativeLayerNormBackward0>), 'key_padding_mask': FakeTensor(..., size=(10, u0), dtype=torch.bool), 'need_weights': False}):
Could not guard on data-dependent expression Eq(u0, 399) (unhinted: Eq(u0, 399)).  (Size-like symbols: u0)

Caused by: x, _ = self.self_attn(  # torchaudio/models/conformer.py:194 in forward (nn/functional.py:6216 in multi_head_attention_forward)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 292, in forward
    x = layer(x, encoder_padding_mask)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 194, in forward
    x, _ = self.self_attn(

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neuropilot/nrpmodel_converter/test_et/executorch/examples/mediatek/export_conformer.py", line 16, in <module>
    exported_program = torch.export.export(instance.eval(), inputs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/__init__.py", line 368, in export
    return _export(
           ^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/_trace.py", line 994, in wrapper
    raise e
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/_trace.py", line 967, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/exported_program.py", line 122, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/_trace.py", line 1938, in _export
    export_artifact = export_func(  # type: ignore[operator]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/_trace.py", line 1214, in _strict_export
    return _strict_export_lower_to_aten_ir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/_trace.py", line 1242, in _strict_export_lower_to_aten_ir
    gm_torch_level = _export_to_torch_ir(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/export/_trace.py", line 564, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 1523, in inner
    result_traced = opt_f(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 550, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1364, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 544, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 964, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 695, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 728, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 229, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 657, in transform
    tracer.run()
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2887, in run
    super().run()
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2394, in CALL
    self._call(inst)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2388, in _call
    self.call_function(fn, args, kwargs)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/nn_module.py", line 440, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3102, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3230, in inline_call_
    tracer.run()
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1791, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 406, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 345, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 124, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3102, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3230, in inline_call_
    tracer.run()
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2394, in CALL
    self._call(inst)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2388, in _call
    self.call_function(fn, args, kwargs)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/nn_module.py", line 412, in call_function
    return wrap_fx_proxy(
           ^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 2076, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 2163, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 2110, in get_fake_value
    raise UserError(  # noqa: B904
torch._dynamo.exc.UserError: Could not guard on data-dependent expression Eq(u0, 399) (unhinted: Eq(u0, 399)).  (Size-like symbols: u0)

Caused by: x, _ = self.self_attn(  # torchaudio/models/conformer.py:194 in forward (nn/functional.py:6216 in multi_head_attention_forward)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 292, in forward
    x = layer(x, encoder_padding_mask)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 194, in forward
    x, _ = self.self_attn(

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#constrain-as-size-example

from user code:
   File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 292, in forward
    x = layer(x, encoder_padding_mask)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/neuropilot/.pyenv/versions/torch_2_6_dev/lib/python3.11/site-packages/torchaudio/models/conformer.py", line 194, in forward
    x, _ = self.self_attn(

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

```

### Versions

```
Collecting environment information...
PyTorch version: 2.6.0.dev20241022+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1~18.04~1) 10.3.0
Clang version: Could not collect
CMake version: version 3.13.4
Libc version: glibc-2.27

Python version: 3.11.8 (main, Sep 10 2024, 06:54:51) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080
GPU 3: GeForce GTX 1080

Nvidia driver version: 460.27.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:            1
CPU MHz:             1443.815
CPU max MHz:         3100.0000
CPU min MHz:         1200.0000
BogoMIPS:            4397.14
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            25600K
NUMA node0 CPU(s):   0-19
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+f9ddcaf
[pip3] numpy==2.1.2
[pip3] onnx==1.13.0
[pip3] onnxruntime==1.17.0
[pip3] torch==2.6.0.dev20241022+cpu
[pip3] torchaudio==2.5.0.dev20241022+cpu
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20241022+cpu
[pip3] triton==2.1.0
[conda] Could not collect
```

cc @ezyang @chauhang @penguinwu @bobrenjc93 @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ezyang** [comment]
Try the playbook at https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?tab=t.0#heading=h.44gwi83jepaj
