### ISSUE TITLE
Exception in Thread: ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by chenchen2004025** [pytorch/pytorch#13966]
## ❓Exception in Thread: ValueError: signal number 32 out of range
The specific tutorial that raises an issue for me is the training a classifier (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html), the specific line is dataiter = iter(trainloader) and the error is:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/chenchen/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/chenchen/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chenchen/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
  File "/home/chenchen/anaconda3/lib/python3.6/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range

My operation system is Ubuntu 18.10 and my python env is Anaconda3 for python 3.6. I installed pytorch from the latest source. My cuda version is 10.0.

**Comment by mrluin** [comment]
Hi, have you solved the problem? I met the same problem.
It occurs when I use DataLoader with num_workers > 0.

**Comment by mrluin** [comment]
I have solved the problem by updating Python3.5 to Python3.7

**Comment by heitorschueroff** [comment]
Closing this issue as it seems to have been resolved.
