### ISSUE TITLE
Inductor CPU test case `test_codecache.py::TestFxGraphCache::test_freezing_device_cpu` failed when build with USE_MKLDNN=ON

### ISSUE THREAD

**Issue by etaf** [pytorch/pytorch#139783]
### 🐛 Describe the bug

On current main branch, the pure Inductor CPU test case `test_codecache.py::TestFxGraphCache::test_freezing_device_cpu` failed when build with USE_MKLDNN=ON. It can pass when build with USE_MKLDNN=OFF.

The case log( reproduceable on main branch):
[xpu / linux-jammy-xpu-py3.9 / test (default, 2, 4, linux.idc.xpu)](https://hud.pytorch.org/pr/pytorch/pytorch/139705#32522162371) ([gh](https://github.com/pytorch/pytorch/actions/runs/11679459270/job/32522162371))
inductor/test_codecache.py::TestFxGraphCache::test_freezing_device_cpu

```
2024-11-05T13:51:29.8358679Z =================================== FAILURES ===================================
2024-11-05T13:51:29.8359204Z __________________ TestFxGraphCache.test_freezing_device_cpu ___________________
2024-11-05T13:51:29.8359696Z Traceback (most recent call last):
2024-11-05T13:51:29.8360278Z   File "/var/lib/jenkins/pytorch/test/inductor/test_codecache.py", line 695, in test_freezing
2024-11-05T13:51:29.8360977Z     self.assertEqual(counters["inductor"]["fxgraph_cache_bypass"], 0)
2024-11-05T13:51:29.8361882Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 3960, in assertEqual
2024-11-05T13:51:29.8362589Z     raise error_metas.pop()[0].to_error(
2024-11-05T13:51:29.8362960Z AssertionError: Scalars are not equal!
2024-11-05T13:51:29.8363207Z 
2024-11-05T13:51:29.8363323Z Expected 0 but got 1.
2024-11-05T13:51:29.8363603Z Absolute difference: 1
2024-11-05T13:51:29.8363887Z Relative difference: inf
```

### Versions

Collecting environment information...
PyTorch version: 2.6.0a0+gitfc32e21
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.4
Libc version: glibc-2.35

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.47+prerelease23.5.18-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by etaf** [comment]
After double check, the failed case actually always failed on machines that `torch.ops.mkldnn._is_mkldnn_fp16_supported()`.
The root cause is: For mahcine that has mkldnn_fp16 support, the weight_pack in mkldnn_fusion.py wroks, which result in mkldnn format tensor, then the exception BypassFxGraphCache("mkldnn tensors unpickleable") is raised, and cause the fxgraph not cached.

Fixed in #39705
