### ISSUE TITLE
LoweringException: AssertionError: convert FlexibleLayout to FixedLayout first when using score_mod

### ISSUE THREAD

**Issue by cat-state** [pytorch/pytorch#139836]
### 🐛 Describe the bug

This doesn't work:
```python
import torch

means = torch.randn(64, 3).cuda()
length_scales = torch.logspace(0.001, 0.1, 8).cuda()

@torch.compile
def euclidean_dist_pos_embed(score, b, h, q_idx, k_idx):
    q_pos = means[q_idx]
    k_pos = means[k_idx]
    dist = (q_pos - k_pos).pow(2).sum(-1).sqrt()
    scale = length_scales[h]
    inv_dist = torch.exp(-dist / scale)
    return inv_dist * score

features = torch.randn(1, 8, 64, 64).cuda()
q = features
k = features
v = features

@torch.compile
def attn(q, k, v):
    return flex_attention(q, k, v, score_mod=euclidean_dist_pos_embed)

attn(q, k, v)
```
with the error:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: convert FlexibleLayout to FixedLayout first
```

however using 
```python
@torch.compile
def euclidean_dist_pos_embed(score, b, h, q_idx, k_idx):
    q_pos = means[q_idx]
    k_pos = means[k_idx]

    #dist = (q_pos - k_pos).pow(2).sum(-1).sqrt()
    diff = q_pos - k_pos
    dist = (diff[0] * diff[0] + diff[1] * diff[1] + diff[2] * diff[2]).sqrt()
    scale = length_scales[h]
    inv_dist = torch.exp(-dist / scale)
    return inv_dist * score
```
works fine

### Versions

it didnt work for me
```
Collecting environment information...
Traceback (most recent call last):
  File "/home/a/subjective/gausim/collect_env.py", line 693, in <module>
    main()
  File "/home/a/subjective/gausim/collect_env.py", line 676, in main
    output = get_pretty_env_info()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/subjective/gausim/collect_env.py", line 671, in get_pretty_env_info
    return pretty_str(get_env_info())
                      ^^^^^^^^^^^^^^
  File "/home/a/subjective/gausim/collect_env.py", line 496, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/subjective/gausim/collect_env.py", line 453, in get_pip_packages
    out = run_with_pip([sys.executable, '-mpip'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/subjective/gausim/collect_env.py", line 448, in run_with_pip
    for line in out.splitlines()
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'
```
however i am using `torch==2.5.1`

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov @zou3519 @ydwu4 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by bdhirsh** [comment]
cc @drisspg

**Comment by drisspg** [comment]
Will try and repro

**Comment by Chillee** [comment]
This will be fixed by https://github.com/pytorch/pytorch/pull/140331

**Comment by Chillee** [comment]
This is fixed on main now.
