### ISSUE TITLE
[triton 3.2] user-defined triton kernels mutation analysis failures

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#139835]
### 🐛 Describe the bug

From #139206.

Repro:
```
python test/inductor/test_triton_kernels.py -k test_add_for_loop
```

I removed some exception handling to get a stacktrace of what's failing:

```
ERROR: test_add_for_loop2 (__main__.MutationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dberard/local/triton-env2/pytorch/torch/testing/_internal/common_utils.py", line 3057, in wrapper
    method(*args, **kwargs)
  File "/home/dberard/local/triton-env2/pytorch/test/inductor/test_triton_kernels.py", line 2211, in test_fn
    identify_mutated_tensors(kernel, inputs),
  File "/home/dberard/local/triton-env2/pytorch/torch/_higher_order_ops/triton_kernel_wrap.py", line 573, in identify_mutated_tensors
    ttir_module, ordered_tensor_names = generate_ttir(kernel, kwargs)
  File "/home/dberard/local/triton-env2/pytorch/torch/_higher_order_ops/triton_kernel_wrap.py", line 262, in generate_ttir
    ttir_module = src.make_ir(options, codegen_fns, module_map, context)
  File "/home/dberard/local/triton-env2/triton/python/triton/compiler/compiler.py", line 85, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns,
  File "/home/dberard/local/triton-env2/triton/python/triton/compiler/code_generator.py", line 1295, in ast_to_ttir
    generator = CodeGenerator(context, prototype, gscope=gscope, constants=all_constants, function_name=function_name,
  File "/home/dberard/local/triton-env2/triton/python/triton/compiler/code_generator.py", line 221, in __init__
    self.gscope[k] = getattr(module_map[module_name], k)
AttributeError: module 'triton.language.extra.cuda.libdevice' has no attribute 'my_fast_dividef'

To execute this test, run the following from the base repo dir:
    python test/inductor/test_triton_kernels.py MutationTests.test_add_for_loop2

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0. Did you mean: 'fast_dividef'?
```

### Versions

main branch triton, viable/strict pytorch (nov 5), H100.

cc @ezyang @chauhang @penguinwu @bertmaher @int3 @nmacchioni @chenyang78 @embg @peterbell10 @aakhundov @oulgen

**Comment by oulgen** [comment]
@aakhundov can you take a look at this?

@davidberard98 this looks like a triton version mismatch, where the new triton deprecated some API

**Comment by davidberard98** [comment]
I think I have a fix on the triton side

**Comment by davidberard98** [comment]
https://github.com/triton-lang/triton/pull/5081
