### ISSUE TITLE
test_barrier_group: AssertionError: True is not false : Timeout waiting for rank 1 to terminate

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#13983]
```
Nov 14 18:00:25 test_barrier_group (__main__.TestDistBackend) ... Process process 2:
Nov 14 18:00:25 Traceback (most recent call last):
Nov 14 18:00:25   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Nov 14 18:00:25     self.run()
Nov 14 18:00:25   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Nov 14 18:00:25     self._target(*self._args, **self._kwargs)
Nov 14 18:00:25   File "test_distributed.py", line 1363, in _run
Nov 14 18:00:25     getattr(self, self.id().split(".")[2])()
Nov 14 18:00:25   File "test_distributed.py", line 1302, in wrapper
Nov 14 18:00:25     fn(self)
Nov 14 18:00:25   File "test_distributed.py", line 121, in wrapper
Nov 14 18:00:25     return func(*args, **kwargs)
Nov 14 18:00:25   File "test_distributed.py", line 990, in test_barrier_group
Nov 14 18:00:25     self._test_barrier_helper(group, group_id, rank)
Nov 14 18:00:25   File "test_distributed.py", line 977, in _test_barrier_helper
Nov 14 18:00:25     self.assertGreaterEqual(time.time(), expected_time[0])
Nov 14 18:00:25   File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 948, in assertGreaterEqual
Nov 14 18:00:25     self.fail(self._formatMessage(msg, standardMsg))
Nov 14 18:00:25   File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 410, in fail
Nov 14 18:00:25     raise self.failureException(msg)
Nov 14 18:00:25 AssertionError: 1542218425.578966 not greater than or equal to tensor(1.5422e+09)
Nov 14 18:00:30 Process process 0:
Nov 14 18:00:30 Traceback (most recent call last):
Nov 14 18:00:30   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Nov 14 18:00:30     self.run()
Nov 14 18:00:30   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Nov 14 18:00:30     self._target(*self._args, **self._kwargs)
Nov 14 18:00:30   File "test_distributed.py", line 1363, in _run
Nov 14 18:00:30     getattr(self, self.id().split(".")[2])()
Nov 14 18:00:30   File "test_distributed.py", line 1302, in wrapper
Nov 14 18:00:30     fn(self)
Nov 14 18:00:30   File "test_distributed.py", line 121, in wrapper
Nov 14 18:00:30     return func(*args, **kwargs)
Nov 14 18:00:30   File "test_distributed.py", line 990, in test_barrier_group
Nov 14 18:00:30     self._test_barrier_helper(group, group_id, rank)
Nov 14 18:00:30   File "test_distributed.py", line 979, in _test_barrier_helper
Nov 14 18:00:30     self._barrier()
Nov 14 18:00:30   File "test_distributed.py", line 193, in _barrier
Nov 14 18:00:30     Barrier.sync(*args, **kwargs)
Nov 14 18:00:30   File "test_distributed.py", line 187, in sync
Nov 14 18:00:30     raise RuntimeError("barrier timeout")
Nov 14 18:00:30 RuntimeError: barrier timeout

...


Nov 14 18:05:34 ======================================================================
Nov 14 18:05:34 FAIL: test_barrier_group (__main__.TestDistBackend)
Nov 14 18:05:34 ----------------------------------------------------------------------
Nov 14 18:05:34 Traceback (most recent call last):
Nov 14 18:05:34   File "test_distributed.py", line 1300, in wrapper
Nov 14 18:05:34     self._join_and_reduce(fn)
Nov 14 18:05:34   File "test_distributed.py", line 1379, in _join_and_reduce
Nov 14 18:05:34     "Timeout waiting for rank %d to terminate" % rank)
Nov 14 18:05:34 AssertionError: True is not false : Timeout waiting for rank 1 to terminate
```

Log https://circleci.com/gh/pytorch/pytorch/242602?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

CC @teng-li @pietern

**Comment by ezyang** [comment]
Another occurrence at https://circleci.com/gh/pytorch/pytorch/242602?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pietern** [comment]
The submodule bump happened in #14281 and any failing operation now throws with #14298.
