### ISSUE TITLE
Shorter logs for compile

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#140394]
### 🚀 The feature, motivation and pitch

When running a code with `TORCH_LOGS="+recompiles,graph_breaks" I'm getting some very long logs:

<details>
  <summary>Summary of the code</summary>

    ```
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks] Graph break: skip: from user code at:
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/Repos/rl/rl/torchrl/modules/tensordict_module/common.py", line 85, in _forward_hook_safe_action
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     if not _spec.is_in(item):
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/Repos/rl/rl/torchrl/data/tensor_specs.py", line 2263, in is_in
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     within_bounds = (val >= self.space.low.to(val.device)).all() and (
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks] Traceback (most recent call last):
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1232, in __call__
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     result = self._inner_convert(
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 550, in __call__
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return _compile(
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 979, in _compile
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     guarded_code = compile_inner(code, one_graph, hooks, transform)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 709, in compile_inner
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return _compile_inner(code, one_graph, hooks, transform)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return function(*args, **kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 744, in _compile_inner
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     out_code = transform_code_object(code, transform)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     transformations(instructions, code_options)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 234, in _fn
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return fn(*args, **kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 663, in transform
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     tracer.run()
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2912, in run
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     super().run()
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1120, in run
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     while self.step():
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1032, in step
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     self.dispatch_table[inst.opcode](self, inst)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 640, in wrapper
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return inner_fn(self, inst)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1738, in CALL_FUNCTION
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     self.call_function(fn, args, {})
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 967, in call_function
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 401, in call_function
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return super().call_function(tx, args, kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 340, in call_function
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return super().call_function(tx, args, kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 125, in call_function
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 973, in inline_user_function_return
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3127, in inline_call
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     return cls.inline_call_(parent, func, args, kwargs)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3255, in inline_call_
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     tracer.run()
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1120, in run
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     while self.step():
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1032, in step
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     self.dispatch_table[inst.opcode](self, inst)
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 621, in inner
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     raise exc.UserError(
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks] torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands
    ```

</details>

What most users would like instead is a more descriptive stack from their code and a very short stack from compile:

<details>
  <summary>Summary of the code</summary>

    ```
    # this is from my code: must be longer!
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks] Graph break: skip: from user code at:
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/Repos/rl/rl/torchrl/modules/tensordict_module/common.py", line 85, in _forward_hook_safe_action
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     if not _spec.is_in(item):
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]   File "/Users/vmoens/Repos/rl/rl/torchrl/data/tensor_specs.py", line 2263, in is_in
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks]     within_bounds = (val >= self.space.low.to(val.device)).all() and (
    # whatever comes next must be as short as possible (unless we have a specific TORCH_LOGS flag to ask for more info)!
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks] Traceback (most recent call last):
    V1112 13:10:18.379000 52923 torch/_dynamo/convert_frame.py:1282] [5/0] [__graph_breaks] torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands
    ```

</details>

### Alternatives

As described in the second block, one alternative would be to have
```
TORCH_LOGS="+recompiles,graph_breaks,verbose" python myscript.py
```
to ask for long stacks from compile, and the default without `verbose` would be a short stack with heavy focus on the user's code.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by ezyang** [comment]
I used to complain that as a dev I really need the full stack but if we shove it in tlparse I'm ok dropping it from recompiles log.

**Comment by vmoens** [comment]
Exactly, I think there is some overlap between what users (who want to get the most of compile) and developers (who want to work on compile) want to see - with more weight given to the latter in terms of stack length.

**Comment by ezyang** [comment]
so yes, I am happy to approve PRs on this vein
