### ISSUE TITLE
The test case test/export/test_export.py::TestExport.test_slice_with_floordiv failed but not exposed in trunk CI.

### ISSUE THREAD

**Issue by etaf** [pytorch/pytorch#140678]
### 🐛 Describe the bug

I found the test case `TestExport.test_slice_with_floordiv` in `test/export/test_export.py` failed but not exposed in trunk CI.

To reproduce: python test/export/test_export.py TestExport.test_slice_with_floordiv

Error message:
```
======================================================================
FAIL: test_slice_with_floordiv (__main__.TestExport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/xinanlin/pytorch/torch/testing/_internal/common_utils.py", line 3057, in wrapper
    method(*args, **kwargs)
  File "/data/xinanlin/pytorch/test/export/test_export.py", line 8570, in test_slice_with_floordiv
    ep.module()(torch.ones(10), torch.ones(4))
AssertionError: RuntimeError not raised

To execute this test, run the following from the base repo dir:
    python test/export/test_export.py TestExport.test_slice_with_floordiv

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------

```

### Versions

Collecting environment information...
PyTorch version: 2.6.0a0+git62eea62
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: glibc-2.35

Python version: 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10)  [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-125-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 550.120
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by etaf** [comment]
The test case has been set expected failure.
