### ISSUE TITLE
[aoti] C++ compiler redefinition error on XlmRoberta

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#140606]
Internal link: https://docs.google.com/document/d/1VwApEwh37eURfCQVMWR6p4QgRsBIAqpHUsvAsFvzH_g/edit?usp=sharing

Example error:
```
/tmp/torchinductor_williamwen/czzxfezqogcw2lqab2nhb2hhnkqxnoswdukzwpcofexqaphgfely/cu3d4wlyj2eb5zbgojmii2oxd4titxlttt2cv74wgatgmodmhsr2.cpp: In member function ‘void torch::aot_inductor::AOTInductorModel::run_impl(AtenTensorOpaque**, AtenTensorOpaque**, torch::aot_inductor::DeviceStreamType, AOTIProxyExecutorHandle)’:
...
/tmp/torchinductor_williamwen/czzxfezqogcw2lqab2nhb2hhnkqxnoswdukzwpcofexqaphgfely/c5zdkk6ugqujjkoaxc3zxvvvr42nsb3it64piuu3e4oanp4s7pzm.cpp:18808:10: error: redeclaration of ‘bool buf6_scalar’
18808 |     bool buf6_scalar;
      |          ^~~~~~~~~~~
/tmp/torchinductor_williamwen/czzxfezqogcw2lqab2nhb2hhnkqxnoswdukzwpcofexqaphgfely/c5zdkk6ugqujjkoaxc3zxvvvr42nsb3it64piuu3e4oanp4s7pzm.cpp:4890:10: note: ‘bool buf6_scalar’ previously declared here
 4890 |     bool buf6_scalar;
      |          ^~~~~~~~~~~
...
Traceback (most recent call last):
  File "/data/users/williamwen/fairseq-env/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1714, in run_command_and_check
    subprocess.check_call(cmd)
  File "/data/users/williamwen/fairseq-env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
```

More details including repro are in the internal link.

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by tugsbayasgalan** [comment]
cc: @desertfire

**Comment by desertfire** [comment]
@yushangdi , this is a good example to apply the AOTI minifier to create a minimal reproduce.

**Comment by yushangdi** [comment]
@williamwen42 
I tried to reproduce this, but for an error when running the eager model.

Wondering why I got "aten._scaled_dot_product_flash_attention_for_cpu.default" op?  I followed the save repro step as in the doc (has all the .cuda() calls). Thanks!

```
Traceback (most recent call last):
  File "/data/users/shangdiy/fairseq/example.py", line 25, in <module>
    last_layer_features, time = timed(lambda: xlmr.extract_features(en_tokens.cuda()))
  File "/data/users/shangdiy/fairseq/example.py", line 13, in timed
    result = fn()
  File "/data/users/shangdiy/fairseq/example.py", line 25, in <lambda>
    last_layer_features, time = timed(lambda: xlmr.extract_features(en_tokens.cuda()))
  File "/data/users/shangdiy/fairseq/fairseq/models/roberta/hub_interface.py", line 93, in extract_features
    features, extra = self.model(
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/shangdiy/fairseq/fairseq/models/roberta/model.py", line 255, in forward
    x, extra = self.encoder(src_tokens, features_only, return_all_hiddens, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/shangdiy/fairseq/fairseq/models/roberta/model.py", line 601, in forward
    x, extra = self.extract_features(
  File "/data/users/shangdiy/fairseq/fairseq/models/roberta/model.py", line 609, in extract_features
    encoder_out = self.sentence_encoder(
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/shangdiy/fairseq/fairseq/models/transformer/transformer_encoder.py", line 165, in forward
    return self.forward_scriptable(
  File "/data/users/shangdiy/fairseq/fairseq/models/transformer/transformer_encoder.py", line 239, in forward_scriptable
    lr = torch.cond(
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_higher_order_ops/cond.py", line 175, in cond
    return torch.compile(_cond_op_wrapper, backend="eager", fullgraph=True)(
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_higher_order_ops/cond.py", line 169, in _cond_op_wrapper
    def _cond_op_wrapper(*args, **kwargs):
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "<eval_with_key>.3", line 26, in forward
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_higher_order_ops/cond.py", line 55, in __call__
    return super().__call__(pred, true_fn, false_fn, operands)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_ops.py", line 433, in __call__
    return wrapper()
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_ops.py", line 429, in wrapper
    return self.dispatch(
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_ops.py", line 412, in dispatch
    return kernel(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_higher_order_ops/cond.py", line 402, in cond_autograd
    ) = create_fw_bw_graph_branches(true_fn, false_fn, *operands)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/_higher_order_ops/cond.py", line 187, in create_fw_bw_graph_branches
    fw_outputs_true = pytree.tree_map(_from_fun, true_fn(*fw_inputs))
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/fx/graph_module.py", line 784, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/fx/graph_module.py", line 361, in __call__
    raise e
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/fx/graph_module.py", line 348, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.0", line 25, in forward
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/functional.py", line 6278, in multi_head_attention_forward
    attn_output = scaled_dot_product_attention(
NotImplementedError: Could not run 'aten::_scaled_dot_product_flash_attention_for_cpu' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_scaled_dot_product_flash_attention_for_cpu' is only available for these backends: [CPU, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastMPS, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
```

Similarly, got an error for export:

```
RuntimeError: Unhandled FakeTensor Device Propagation for aten._scaled_dot_product_flash_attention_for_cpu.default, found two different devices cpu, cuda:0
```

**Comment by yushangdi** [comment]
@desertfire The minifier successfully reduced the number of nodes from 517 to 43. (need https://github.com/pytorch/pytorch/pull/141156)

The resulting repro.py is here: https://gist.github.com/yushangdi/cea2d213ad011ded7735f340b7c55c4e

**Comment by yushangdi** [comment]
@desertfire It's going to be non-trivial if we want the minifier to minify the submodules as well, since then we'll need to modify inputs to the submodule calls, but I think it can be done. Maybe ~2 weeks of work (very rough estimate, could be less, could be more). Do you think it's worth adding this feature?

**Comment by yushangdi** [comment]
With the fix in https://github.com/pytorch/pytorch/pull/141528, I exported the model successfully.

time to encode 0.0003277440071105957
time to decode 0.00028700798749923704
time to extract features 8.446578125
time to extract features (exported) 5.5172177734375
time to extract features (aoti) 1.589226806640625

**Comment by desertfire** [comment]
> @desertfire It's going to be non-trivial if we want the minifier to minify the submodules as well, since then we'll need to modify inputs to the submodule calls, but I think it can be done. Maybe ~2 weeks of work, including testing(very rough estimate, could be less, could be more). Do you think it's worth adding this feature?

Good catch! torch.cond isn't a common use case now, so it's not urgent to add this feature, but it can be a good extension for next half.
