### ISSUE TITLE
the device of tensor can not be change

### ISSUE THREAD

**Issue by szupzp** [pytorch/pytorch#14072]
I got an error while training my model.
`def train(args):

    # Setup Dataloader
    train_set = Loader(root_path='/home/zhanpengpan/zhanpengpan/train_test_data/',
                                                        sub_path=['clean_trainset_56spk_32k_wav_lp07/', 'clean_trainset_56spk_32k_wav_lp14/'],
                                                         win_type='hanning', win_len=256, hop_len=128, sr=32000, model_type= args.arch
                                                         )
    vali_set = Loader(root_path='/home/zhanpengpan/zhanpengpan/train_test_data/',
                                                        sub_path=['clean_testset_32k_wav_lp07/', 'clean_testset_32k_wav_lp14/'],
                                                         win_type='hanning', win_len=256, hop_len=128, sr=32000, model_type= args.arch

                                                  )
    train_loader = data.DataLoader(train_set, batch_size=args.batch_size, num_workers=8)
    val_loader = data.DataLoader(vali_set, batch_size=args.batch_size, num_workers=8)
    # setup model
    if(args.arch=='dnn'):
        model = models.DNN()
    elif(args.arch=='cnn'):
        model = models.CNN()
    if torch.cuda.is_available():
        device = torch.device("cuda")
        model.to(device)

    # optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=args.l_rate, weight_decay=5e-4)

    # loss function
    loss_f = nn.MSELoss()

    # Setup device
    device = torch.device("cuda:0")
    print(device)
    # train
    min_loss = 100000.0
    for epoch in range(args.n_epoch):
        model.train()
        for i, (lp07, lp14) in enumerate(train_loader):
            if args.arch == 'cnn':
                lp07 = lp07.permute(1,0,2)
                lp07 = lp07.view(-1, 1, 64)
            else:
                lp07 = lp07.view(-1,64)
            lp14 = lp14.view(-1,64)
            if lp07.shape != lp14.shape:
                print(lp07.shape)
                print(lp14.shape)
            lp07.to(device)
            lp14.to(device)
            optimizer.zero_grad()
            outputs = model(lp07)
            loss = loss_f(outputs, lp14)
            optimizer.step()

            if (i + 1) % 50 == 0:
                print("Epoch [%d/%d] Loss: %.4f" % (epoch + 1, args.n_epoch, loss.data[0]))

        model.eval()
        sum_loss = 0.0
        for i_val, (lp07_val, lp14_val) in tqdm(enumerate(val_loader)):
            if args.arch == 'cnn':
                lp07_val = lp07_val.permute(1,0,2)
                lp07_val = lp07_val.view(-1, 1, 64)
            else:
                lp07_val = lp07_val.view(-1,64)
            lp14_val = lp14_val.view(-1,64)
            val_outputs = model(lp07_val)
            val_loss = loss_f(val_outputs, lp14_val)
            sum_loss += val_loss
        print('val_loss = %f',sum_loss/vali_set.__len__())`

the error is:
Traceback (most recent call last):
  File "/home/zhanpengpan/zhanpengpan/PycharmProjects/blind_bwe/train.py", line 114, in <module>
    train(args)
  File "/home/zhanpengpan/zhanpengpan/PycharmProjects/blind_bwe/train.py", line 69, in train
    outputs = model(lp07)
  File "/home/zhanpengpan/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/datas/zhanpengpan/PycharmProjects/blind_bwe/models/DNN.py", line 27, in forward
    output = self.fc1(input)
  File "/home/zhanpengpan/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanpengpan/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/zhanpengpan/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanpengpan/.local/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zhanpengpan/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #4 'mat1'

It means that my model's device is GPU but the input tensor is CPU. How can i do ?

**Comment by szupzp** [comment]
> As I said in your previous issue `.to` returns new tensors, so you need to re-assign results of these two lines
> 
> ```
>         lp07.to(device)
>         lp14.to(device)
> ```
thanks for answering my question. i figure out it by modify my code:
`
            lp07 = lp07.to(device)
            lp14 = lp14.to(device)
`
but i don't know why should i do this. In pytorch 0.3.0, the tensor just use:
`tensor.cuda()`
