### ISSUE TITLE
No fake impl or Meta kernel for Communication Operator 

### ISSUE THREAD

**Issue by jo-pillar** [pytorch/pytorch#140712]
### 🐛 Describe the bug

There is no fake implementation or meta kernel for the Communication Operator. If I want to contribute to this feature, what can I do? Are there any examples that I can reference?
```python
import torch
import torch.nn as nn
import torch.optim as optim
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP
import os
import argparse

# 简单的神经网络模型
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = nn.Linear(10, 10)
    
    def forward(self, x):
        return self.fc(x)

def setup(rank, world_size):
    # 设置分布式通信的初始化方法
    os.environ['MASTER_ADDR'] = 'localhost'  # 主节点地址
    os.environ['MASTER_PORT'] = '12355'  # 通信端口
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

def main(rank, world_size):
    setup(rank, world_size)

    # 设置设备
    device = torch.device(f'cuda:{rank}')
    
    # 创建模型并迁移到对应设备
    model = SimpleModel().to(device)
    
    # 包装成 DDP 模型
    model = DDP(model, device_ids=[rank])
    
    # 简单的损失函数和优化器
    criterion = nn.MSELoss()
    optimizer = optim.SGD(model.parameters(), lr=0.01)

    # 模拟数据
    input_data = torch.randn(20, 10).to(device)
    target_data = torch.randn(20, 10).to(device)

    # 训练循环
    for epoch in range(10):
        optimizer.zero_grad()
        output = model(input_data)
        loss = criterion(output, target_data)
        loss.backward()
        optimizer.step()
        
        print(f"Rank {rank}, Epoch {epoch}, Loss: {loss.item()}")
    
    cleanup()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--rank", type=int, help="Rank of the process")
    parser.add_argument("--world_size", type=int, help="Total number of processes")
    args = parser.parse_args()

    main(args.rank, args.world_size)

```

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/pc06/wyl/Torch-sim/ddp_tutorial/ddp_meta.py", line 89, in <module>
[rank1]:     main(device, args.total_epochs, args.batch_size)
[rank1]:   File "/home/pc06/wyl/Torch-sim/ddp_tutorial/ddp_meta.py", line 77, in main
[rank1]:     trainer = Trainer(model, train_data, optimizer, device)
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/pc06/wyl/Torch-sim/ddp_tutorial/ddp_meta.py", line 33, in __init__
[rank1]:     self.model = DDP(self.model)
[rank1]:                  ^^^^^^^^^^^^^^^
[rank1]:   File "/home/pc06/anaconda3/envs/torch25/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank1]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank1]:   File "/home/pc06/anaconda3/envs/torch25/lib/python3.12/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank1]:     return dist._verify_params_across_processes(process_group, tensors, logger)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: NotImplementedError: c10d::allgather_: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl. Please see the following for next steps:  https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html
E1114 23:05:38.298000 195576 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 195676) of binary: /home/pc06/anaconda3/envs/torch25/bin/python
```

### Versions

PyTorch version: 2.5.0a0
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:27:36) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 550.78
cuDNN version: Probably one of the following:
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       GenuineIntel
Model name:                      13th Gen Intel(R) Core(TM) i9-13900K
CPU family:                      6
Model:                           183
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     4300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5990.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       896 KiB (24 instances)
L1i cache:                       1.3 MiB (24 instances)
L2 cache:                        32 MiB (12 instances)
L3 cache:                        36 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] bert_pytorch==0.0.1a4
[pip3] bert_pytorch==0.0.1a4
[pip3] bert_pytorch==0.0.1a4
[pip3] numpy==1.26.4
[pip3] optree==0.13.0
[pip3] torch==2.5.0a0+gitunknown
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2023.1.0         h213fc3f_46344    defaults
[conda] mkl-include               2025.0.0                 pypi_0    pypi
[conda] mkl-service               2.4.0           py312h5eee18b_1    defaults
[conda] mkl-static                2025.0.0                 pypi_0    pypi
[conda] mkl_fft                   1.3.10          py312h5eee18b_0    defaults
[conda] mkl_random                1.2.7           py312h526ad5a_0    defaults
[conda] numpy                     2.1.2                    pypi_0    pypi
[conda] numpy-base                1.26.4          py312h0da6c21_0    defaults
[conda] optree                    0.13.0                   pypi_0    pypi
[conda] torch                     2.5.0a0+gitunknown          pypi_0    pypi

**Comment by tianyu-l** [comment]
cc: @yifuwang

**Comment by tianyu-l** [comment]
Sorry this might be directly answering your question, but I didn't understand why running DDP on cuda would incur "attempted to run this operator with Meta tensors"?
cc: @fegin

**Comment by yifuwang** [comment]
@jo-pillar Your repro doesn't seem to use fake tensor/meta device. Can you update your repro? I can check what needs to be implemented to support this.

**Comment by jo-pillar** [comment]
> @jo-pillar Your repro doesn't seem to use fake tensor/meta device. Can you update your repro? I can check what needs to be implemented to support this.  

Sorry, I mistakenly deleted the sentence`device = torch.device ('meta') `when editing, and now it has been added in the original comment.

**Comment by jo-pillar** [comment]
> Sorry, I mistakenly deleted the sentence`device = torch.device ('meta') `when editing, and now it has been added in the original comment.

Sorry, I mistakenly deleted the sentencedevice = torch.device ('meta') when editing, and now it has been added in the original comment.

**Comment by fegin** [comment]
DDP currently doesn't support Meta device. We have an alternative implementation `replicate` that support Meta device. The implementation lazily initializes DDP instance so that all the communications happen lazily. Simply supporting Meta device of some communicator API won't complete resolve the DDP issue because DDP require the communication results to verify the parameters correctness which contradict to Meta device use case.

What's the motivation of using Meta device with DDP? DDP should only be used GPU memory is enough to fit the entire model, in which case Meta initialization seems to be redundant?

**Comment by jo-pillar** [comment]
I want use meta tensor or FakeTensor to capture the workload of communication with different parallel strategy

 @fegin

**Comment by jo-pillar** [comment]
I'm not quite clear about the meta initialization. Could you provide me with more details regarding it?
