### ISSUE TITLE
[MPS] Add support for output_channels > 2**16 in `F.conv1d`

### ISSUE THREAD

**Issue by hvaara** [pytorch/pytorch#140722]
### 🚀 The feature, motivation and pitch

#129207 discovered a silent correctness issue in conv1d with output channels > 65536. A guard with an error message was added in #129484.

On macOS 15.1 it looks like this has been fixed based on testing with the repro case from #129207.

Consider adding support for output channels > 2**16 again. Discover which macOS versions are supported and keep the guard for the macOS versions where it's not supported. Add unit tests with xfails for the versions where it is still failing.

xref #134416 https://github.com/huggingface/parler-tts/issues/148

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by hvaara** [comment]
Fix incoming.

@pytorchbot label 'module: mps'

**Comment by malfet** [comment]
Thank you for reporting and volunteering to fix @hvaara . Tentatively assigning it to you.

**Comment by hvaara** [comment]
The issue is visible downstream in for example parler-tts (ref https://github.com/huggingface/parler-tts/issues/148).

I included the changes from #140726 and compiled PyTorch with `USE_DISTRIBUTED=1 python setup.py develop` to enable `torch.distributed`. This is because a dep in parler-tts (descript-audiotools) needs types from `torch.distributed` (ref https://github.com/descriptinc/audiotools/blob/348ebf2034ce24e2a91a553e3171cb00c0c71678/audiotools/ml/decorators.py#L288). `torch.distributed` is disabled by default in the macOS version of PyTorch.

With the approach above I got a good output using the script from https://github.com/pytorch/pytorch/issues/134416#issuecomment-2476447401. I uploaded an [example output](https://github.com/hvaara/files/blob/refs/heads/main/parler-tts/parler_tts_out_mps-2024-11-14.wav) file.

**Comment by hvaara** [comment]
@chigkim I found a `hertz-dev` tts model. Is this the one you meant in https://github.com/pytorch/pytorch/issues/134416#issuecomment-2476887100? it seems it doesn't support macOS (ref https://github.com/Standard-Intelligence/hertz-dev/issues/5). Is this different from what you expected, or is it the wrong model?

Currently investigating if coqui-ai-tts will be fixed as well.

**Comment by hvaara** [comment]
For coqui-ai-tts I created a new mamba env with Python 3.11 and tried to install with `pip install TTS`. Unfortunately it failed while installing a dep called `spacy` with

```
      Compiling spacy/symbols.pyx because it changed.
      Compiling spacy/vectors.pyx because it changed.
      [ 1/41] Cythonizing spacy/attrs.pyx
      [ 2/41] Cythonizing spacy/kb.pyx
      Traceback (most recent call last):
        File "/Users/hvaara/miniforge3/envs/coqui-ai-tts/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/hvaara/miniforge3/envs/coqui-ai-tts/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/hvaara/miniforge3/envs/coqui-ai-tts/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4j/b1p5403s5slcxvg1t7wk8ngr0000gp/T/pip-build-env-d8zao3t5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4j/b1p5403s5slcxvg1t7wk8ngr0000gp/T/pip-build-env-d8zao3t5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4j/b1p5403s5slcxvg1t7wk8ngr0000gp/T/pip-build-env-d8zao3t5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "/private/var/folders/4j/b1p5403s5slcxvg1t7wk8ngr0000gp/T/pip-build-env-d8zao3t5/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/4j/b1p5403s5slcxvg1t7wk8ngr0000gp/T/pip-build-env-d8zao3t5/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]
```

**Comment by chigkim** [comment]
I believe the original repo for coqui-ai-TTS is discontinued. Clone and `pip install -e .` using:
https://github.com/idiap/coqui-ai-TTS

**Comment by hvaara** [comment]
@chigkim you seem to be very familiar with this topic. Would you be interested in testing it out with https://github.com/idiap/coqui-ai-TTS on torch-2.6.0.dev20241115 and tell us how it went? I'm happy to take another look in case it's still not working.

**Comment by chigkim** [comment]
I tested idiap/coqui-ai-TTS, and it works with the latest the Torch nightly build!!! :)
I also got Standard-Intelligence/hertz-dev to work on my Mac with the Torch nightly build. It's a totally different issue, but m3 Max 65GB seems too slow for it. I get very choppy audio output. :(

**Comment by hvaara** [comment]
Awesome! Thank you for testing and happy to see the great results.

**Comment by chigkim** [comment]
Thank you for fixing it!

**Comment by AimoneAndex** [comment]
> I tested idiap/coqui-ai-TTS, and it works with the latest the Torch nightly build!!! :) I also got Standard-Intelligence/hertz-dev to work on my Mac with the Torch nightly build. It's a totally different issue, but m3 Max 65GB seems too slow for it. I get very choppy audio output. :(

What your macOS version is?Is it higher than 15.1 or lower?
