### ISSUE TITLE
[ROCm] Incorrect number of arguments passed to kernel

### ISSUE THREAD

**Issue by jataylo** [pytorch/pytorch#140800]
### 🐛 Describe the bug

When using ROCm specific tuning parameters for custom triton kernels we run into an exception.

It seems related to this PR https://github.com/pytorch/pytorch/pull/137236 but simply adding matrix_instr_nonkdim, waves_per_eu and kpack to "SPECIAL_CONFIG_NAMES" does not seem to be enough to fix this as kwargs is empty at this point.

```
import torch
import triton
from triton import language as tl

@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 4, "matrix_instr_nonkdim": 32}, num_stages=3, num_warps=8),
    ],
    key=[],
)
@triton.jit
def add_kernel_autotuned(
    in_ptr0,
    in_ptr1,
    out_ptr,
    n_elements,
    BLOCK_SIZE: "tl.constexpr",
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(in_ptr0 + offsets, mask=mask)
    y = tl.load(in_ptr1 + offsets, mask=mask)
    output = x + y
    tl.store(out_ptr + offsets, output, mask=mask)

@torch.compile(fullgraph=True)
def add_fn(x, y):
    output = torch.zeros_like(x)
    n_elements = output.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    add_kernel_autotuned[grid](x, y, output, n_elements)
    return output

x = torch.randn(4, device="cuda")
y = torch.randn(4, device="cuda")
out = add_fn(x, y)
print(f"Vector addition of\nX:\t{x}\nY:\t{y}\nis equal to\n{out}")
```

Traceback:
```
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0] Encountered an exception in identify_mutated_tensors, assuming every input is mutated
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0] Traceback (most recent call last):
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 574, in identify_mutated_tensors
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]     ttir_module, ordered_tensor_names = generate_ttir(kernel, kwargs)
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 202, in generate_ttir
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]     raise ValueError("Incorrect number of arguments passed to kernel")
W1115 11:37:10.193439 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0] ValueError: Incorrect number of arguments passed to kernel
{'in_ptr0': FakeTensor(..., device='cuda:0', size=(4,)), 'in_ptr1': FakeTensor(..., device='cuda:0', size=(4,)), 'out_ptr': FakeTensor(..., device='cuda:0', size=(4,)), 'n_elements': 4, 'BLOCK_SIZE': 4, 'matrix_instr_nonkdim': 32}
['in_ptr0', 'in_ptr1', 'out_ptr', 'n_elements', 'BLOCK_SIZE']
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0] Encountered an exception in identify_mutated_tensors, assuming every input is mutated
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0] Traceback (most recent call last):
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 574, in identify_mutated_tensors
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]     ttir_module, ordered_tensor_names = generate_ttir(kernel, kwargs)
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_higher_order_ops/triton_kernel_wrap.py", line 202, in generate_ttir
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0]     raise ValueError("Incorrect number of arguments passed to kernel")
W1115 11:37:10.193879 313 site-packages/torch/_higher_order_ops/triton_kernel_wrap.py:595] [0/0] ValueError: Incorrect number of arguments passed to kernel
```

### Versions

Tip of tree

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang @naromero77amd

**Comment by jataylo** [comment]
ccing @aakhundov incase anything jumps to your mind on this one.

**Comment by jataylo** [comment]
Correct we pass the AMD specific args via kwargs, either as implemented in this reproducer or through kwargs of the kernel args e.g.

```
extra_kargs = {"waves_per_eu": 4, "matrix_instr_nonkdim": 16, "kpack": 2}
 
_fwd_kernel[grid](
    q_extend,
    k_extend,
    ...,
    ...,
    **extra_kargs,
)
```

Both cases run into this issue, I couldn't see a solid way to resolve this in the code without challenging this assumption:
```
if len(kwargs) != len(kernel.arg_names):
    raise ValueError("Incorrect number of arguments passed to kernel")
```

**Comment by aakhundov** [comment]
@jataylo https://github.com/pytorch/pytorch/pull/141062 should fix the error showing up here.
