### ISSUE TITLE
Benchmark result upgrade script is broken

### ISSUE THREAD

**Issue by bobrenjc93** [pytorch/pytorch#141095]
### 🐛 Describe the bug

```CH_KEY_ID=abc CH_KEY_SECRET=def python benchmarks/dynamo/ci_expected_accuracy/update_expected.py b43688515a50aba071aef22329de565566d91e19```

(removed the secret keys for obvious reasons)

results in

```
inductor_huggingface 1, 1: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_huggingface-1-1-linux.g5.4xlarge.nvidia.gpu_33104789789.zip
inductor_timm 1, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_timm-1-2-linux.g5.4xlarge.nvidia.gpu_33104789865.zip
inductor_timm 2, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_timm-2-2-linux.g5.4xlarge.nvidia.gpu_33104789924.zip
inductor_torchbench 1, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_torchbench-1-2-linux.g5.4xlarge.nvidia.gpu_33104790005.zip
inductor_torchbench 2, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_torchbench-2-2-linux.g5.4xlarge.nvidia.gpu_33104790091.zip
inductor_timm 1, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_timm-1-2-linux.g5.4xlarge.nvidia.gpu_33104793832.zip
inductor_timm 2, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-inductor_timm-2-2-linux.g5.4xlarge.nvidia.gpu_33104793920.zip
cpu_inductor_torchbench 1, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-cpu_inductor_torchbench-1-2-linux.8xlarge.amx_33104456757.zip
cpu_inductor_torchbench 2, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-cpu_inductor_torchbench-2-2-linux.8xlarge.amx_33104456805.zip
dynamic_cpu_inductor_huggingface 1, 1: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-dynamic_cpu_inductor_huggingface-1-1-linux.8xlarge.amx_33104456837.zip
dynamic_cpu_inductor_timm 1, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-dynamic_cpu_inductor_timm-1-2-linux.8xlarge.amx_33104456880.zip
dynamic_cpu_inductor_timm 2, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-dynamic_cpu_inductor_timm-2-2-linux.8xlarge.amx_33104456933.zip
dynamic_cpu_inductor_torchbench 1, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-dynamic_cpu_inductor_torchbench-1-2-linux.8xlarge.amx_33104456986.zip
dynamic_cpu_inductor_torchbench 2, 2: https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/11880698620/1/artifact/test-reports-test-dynamic_cpu_inductor_torchbench-2-2-linux.8xlarge.amx_33104457050.zip
Traceback (most recent call last):
  File "/data/users/bobren/pytorch/benchmarks/dynamo/ci_expected_accuracy/update_expected.py", line 219, in <module>
    urls = get_artifacts_urls(results, suites)
  File "/data/users/bobren/pytorch/benchmarks/dynamo/ci_expected_accuracy/update_expected.py", line 115, in get_artifacts_urls
    config_str, test_str = parse_job_name(r["jobName"])
ValueError: too many values to unpack (expected 2)
```

### Versions

(pytorch) [18:53] devgpu006:/data/users/bobren/pytorch python collect_env.py
Collecting environment information...
PyTorch version: 2.6.0a0+gitc3fbec7
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.5.0 20240719 (Red Hat 11.5.0-2)
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: glibc-2.34

Python version: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.4.3-0_fbk14_zion_2601_gcd42476b84e9-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100
GPU 4: NVIDIA H100
GPU 5: NVIDIA H100
GPU 6: NVIDIA H100
GPU 7: NVIDIA H100

Nvidia driver version: 535.154.05
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.8.0
/usr/lib64/libcudnn_adv_infer.so.8.8.0
/usr/lib64/libcudnn_adv_train.so.8.8.0
/usr/lib64/libcudnn_cnn_infer.so.8.8.0
/usr/lib64/libcudnn_cnn_train.so.8.8.0
/usr/lib64/libcudnn_ops_infer.so.8.8.0
/usr/lib64/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             384
On-line CPU(s) list:                0-383
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 9654 96-Core Processor
CPU family:                         25
Model:                              17
Thread(s) per core:                 2
Core(s) per socket:                 96
Socket(s):                          2
Stepping:                           1
Frequency boost:                    enabled
CPU(s) scaling MHz:                 71%
CPU max MHz:                        3707.8120
CPU min MHz:                        1500.0000
BogoMIPS:                           4792.82
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                     AMD-V
L1d cache:                          6 MiB (192 instances)
L1i cache:                          6 MiB (192 instances)
L2 cache:                           192 MiB (192 instances)
L3 cache:                           768 MiB (24 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-95,192-287
NUMA node1 CPU(s):                  96-191,288-383
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Vulnerable: eIBRS with unprivileged eBPF
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] bert_pytorch==0.0.1a4
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.15.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.11.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] onnx==1.17.0
[pip3] onnxscript==0.1.0.dev20241101
[pip3] optree==0.13.0
[pip3] pytorch-labs-segment-anything-fast==0.2
[pip3] torch==2.6.0a0+gitc3fbec7
[pip3] torch_geometric==2.4.0
[pip3] torchao==0.6.1
[pip3] torchaudio==2.5.0a0+ba696ea
[pip3] torchbench==0.1
[pip3] torchdata==0.10.0a0+ef62e00
[pip3] torchmetrics==1.0.3
[pip3] torchmultimodal==0.1.0b0
[pip3] torchrec==1.1.0a0+d2ed744
[pip3] torchtext==0.17.0a0+1d4ce73
[pip3] torchvision==0.20.0a0+e9a3213
[pip3] torchviz==0.0.2
[pip3] triton==3.1.0
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2025.0.1                 pypi_0    pypi
[conda] mkl-include               2025.0.0                 pypi_0    pypi
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl-static                2025.0.0                 pypi_0    pypi
[conda] mkl_fft                   1.3.11          py310h5eee18b_0  
[conda] mkl_random                1.2.8           py310h1128e8f_0  
[conda] numpy                     1.26.4          py310h5f9d8c6_0  
[conda] numpy-base                1.26.4          py310hb5e798b_0  
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] optree                    0.13.0                   pypi_0    pypi
[conda] pytorch-labs-segment-anything-fast 0.2                      pypi_0    pypi
[conda] torch                     2.6.0a0+gitc3fbec7           dev_0    <develop>
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchao                   0.6.1                    pypi_0    pypi
[conda] torchaudio                2.5.0a0+ba696ea           dev_0    <develop>
[conda] torchbench                0.1                       dev_0    <develop>
[conda] torchdata                 0.10.0a0+ef62e00          pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchmetrics              1.0.3                    pypi_0    pypi
[conda] torchmultimodal           0.1.0b0                  pypi_0    pypi
[conda] torchrec                  1.1.0a0+d2ed744          pypi_0    pypi
[conda] torchtext                 0.17.0a0+1d4ce73           dev_0    <develop>
[conda] torchvision               0.20.0a0+e9a3213           dev_0    <develop>
[conda] torchviz                  0.0.2                    pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi

cc @seemethere @malfet @pytorch/pytorch-dev-infra @chauhang @penguinwu

**Comment by clee2000** [comment]
The query is fine, the script makes incorrect assumptions when parsing the job name.  You also get this error prior to the query migration to ClickHouse

**Comment by clee2000** [comment]
Fixed by @huydhn in #144523
