### ISSUE TITLE
RelaxedUnspecConstraint infers constant shape when i am marking as dynamic

### ISSUE THREAD

**Issue by felipemello1** [pytorch/pytorch#141034]
### 🐛 Describe the bug

possible related issue: https://github.com/pytorch/pytorch/issues/139936

In torchtune we chunk the logits/labels in order to compute [ChunkedCrossEntropy](https://github.com/pytorch/torchtune/blob/main/torchtune/modules/loss/ce_chunked_output_loss.py) 

I am trying to avoid graph breaks by marking the labels as dynamic.

Marking the labels_chunks as dynamic raises the error below. My n00b guess is that this happens because we have 8 chunks for each batch, so we call the function 8 times with the same shape before it finally changes in the next batch.

To reproduce
```
import torch
import torch.nn.functional as F

def compute_cross_entropy(
    logits_test: torch.Tensor, labels_test: torch.Tensor
) -> torch.Tensor:
    return F.cross_entropy(
        logits_test.float(),
        labels_test,
        ignore_index=-100,
        reduction="sum",
    )


# Create dummy data
batch_size = 2
num_tokens = 16
vocab_size = 10
num_chunks = 8

logits = torch.randn(batch_size, num_tokens, vocab_size)
labels = torch.randint(0, vocab_size, (batch_size, num_tokens))

# Chunk and reshape logits
logits_chunks = [
    chunk.reshape(-1, chunk.size(-1)) for chunk in logits.chunk(num_chunks, dim=1)
]

# Chunk and reshape labels
labels_chunks = [chunk.reshape(-1) for chunk in labels.chunk(num_chunks, dim=1)]

# Avoid graph breaks
for l in labels_chunks:
    torch._dynamo.mark_dynamic(l, 0)

# Compile the compute_cross_entropy function
compiled_compute_cross_entropy = torch.compile(
    compute_cross_entropy, backend="inductor"
)

# Compute cross entropy for each chunk
total_loss = 0.0
for logits_chunk, labels_chunk in zip(logits_chunks, labels_chunks):
    total_loss += compiled_compute_cross_entropy(logits_chunk, labels_chunk)

print(total_loss)
```

### Error logs

```
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0] Error while creating guard:
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0] Name: ''
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     Source: shape_env
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     Create Function: SHAPE_ENV
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     Guard Types: None
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     Code List: None
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     Object Weakref: None
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     Guarded Class Weakref: None
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0] Traceback (most recent call last):
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_guards.py", line 293, in create
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     return self.create_fn(builder, self)
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 1787, in SHAPE_ENV
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     code_parts, verbose_code_parts = output_graph.shape_env.produce_guards_verbose(
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5090, in produce_guards_verbose
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]     raise ConstraintViolationError(
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0] torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['labels_test'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
E1119 07:45:17.426000 2050788 site-packages/torch/_guards.py:295] [1/0]   - Not all values of RelaxedUnspecConstraint(L['labels_test'].size()[0]) are valid because L['labels_test'].size()[0] was inferred to be a constant (216).
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0] Created at:
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 644, in transform
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]     tracer = InstructionTranslator(
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2681, in __init__
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]     output=OutputGraph(
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 319, in __init__
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]     self.init_ambient_guards()
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]   File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 468, in init_ambient_guards
E1119 07:45:17.427000 2050788 site-packages/torch/_guards.py:297] [1/0]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
Traceback (most recent call last):
  File "/home/felipemello/.conda/envs/torchtune/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/users/felipemello/torchtune/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/data/users/felipemello/torchtune/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/data/users/felipemello/torchtune/torchtune/_cli/run.py", line 208, in _run_cmd
    self._run_single_device(args, is_builtin=is_builtin)
  File "/data/users/felipemello/torchtune/torchtune/_cli/run.py", line 102, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/data/users/felipemello/torchtune/recipes/lora_finetune_single_device.py", line 807, in <module>
    sys.exit(recipe_main())
             ^^^^^^^^^^^^^
  File "/data/users/felipemello/torchtune/torchtune/config/_parse.py", line 99, in wrapper
    sys.exit(recipe_main(conf))
             ^^^^^^^^^^^^^^^^^
  File "/data/users/felipemello/torchtune/recipes/lora_finetune_single_device.py", line 802, in recipe_main
    recipe.train()
  File "/data/users/felipemello/torchtune/recipes/lora_finetune_single_device.py", line 709, in train
    current_loss = self._loss_step(batch) * current_num_tokens
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/felipemello/torchtune/recipes/lora_finetune_single_device.py", line 652, in _loss_step
    loss = self._loss_fn(logits, labels)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/felipemello/torchtune/torchtune/modules/loss/ce_chunked_output_loss.py", line 92, in forward
    total_loss += self.compute_cross_entropy(logits_chunk, labels_chunk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 556, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1403, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1187, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 549, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 984, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 712, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 844, in _compile_inner
    check_fn = CheckFunctionManager(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 2199, in __init__
    guard.create(builder)
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_guards.py", line 293, in create
    return self.create_fn(builder, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 1787, in SHAPE_ENV
    code_parts, verbose_code_parts = output_graph.shape_env.produce_guards_verbose(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5090, in produce_guards_verbose
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['labels_test'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of RelaxedUnspecConstraint(L['labels_test'].size()[0]) are valid because L['labels_test'].size()[0] was inferred to be a constant (216).
```

### Versions

Tried it with both:  2.5.1 and 2.6.0.dev20241119+cu124

cc @chauhang @penguinwu

**Comment by bdhirsh** [comment]
This fixes it for me:
```
# Avoid graph breaks
for l, logit in zip(labels_chunks, logits_chunks):
    torch._dynamo.mark_dynamic(l, 0)
    torch._dynamo.mark_dynamic(logit, 0)
```

Since the logits need to have the same shape as the labels, we were specializing since compile thought that logits were static

**Comment by felipemello1** [comment]
Thanks!
