### ISSUE TITLE
[User Empathy Day] Watermark-Anything AOTAutograd crash

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#141187]
Getting an internal assert failure:
```
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1] failed while attempting to run meta for aten._upsample_bilinear2d_aa_backward.default
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1] Traceback (most recent call last):
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1]   File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2297, in _dispatch_impl
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1]     r = func(*args, **kwargs)
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1]   File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_ops.py", line 723, in __call__
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1]     return self._op(*args, **kwargs)
E1120 16:27:42.446000 166428 site-packages/torch/_subclasses/fake_tensor.py:2301] [0/1_1] RuntimeError: isIntList() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/core/ivalue_inl.h":1979, please report a bug to PyTorch. Expected IntList but got GenericList
/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/autograd/graph.py:825: UserWarning: Error detected in UpsampleBilinear2DAaBackward0. Traceback of forward call that caused the error:
  File "/data/users/williamwen/watermark-anything/watermark_anything/models/wam.py", line 211, in embed
    preds_w = inverse_resize(preds_w)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 354, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 479, in resize
    return F_t.resize(img, size=output_size, interpolation=interpolation.value, antialias=antialias)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torchvision/transforms/_functional_tensor.py", line 467, in resize
    img = interpolate(img, size=size, mode=interpolation, align_corners=align_corners, antialias=antialias)
 (Triggered internally at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:122.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/data/users/williamwen/watermark-anything/playground.py", line 70, in <module>
    outputs_c, embed_t_c = timed(lambda: wam_embed_compiled(img_pt, wm_msg))
  File "/data/users/williamwen/watermark-anything/playground.py", line 26, in timed
    result = fn()
  File "/data/users/williamwen/watermark-anything/playground.py", line 70, in <lambda>
    outputs_c, embed_t_c = timed(lambda: wam_embed_compiled(img_pt, wm_msg))
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 556, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1404, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1188, in __call__
    result = self._inner_convert(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 549, in __call__
    return _compile(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 985, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 712, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 747, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 233, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 664, in transform
    tracer.run()
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2841, in run
    super().run()
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1032, in run
    while self.step():
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 944, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 639, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 680, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1110, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1349, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1399, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1448, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1429, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/__init__.py", line 2301, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1733, in compile_fx
    return aot_autograd(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1103, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1079, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 527, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 778, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 373, in aot_dispatch_autograd
    fx_g, joint_inputs, maybe_subclass_meta = aot_dispatch_autograd_graph(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 318, in aot_dispatch_autograd_graph
    fx_g = _create_graph(joint_fn_to_trace, updated_joint_inputs, aot_config=aot_config)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 55, in _create_graph
    fx_g = make_fx(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 2188, in wrapped
    return make_fx_tracer.trace(f, *args)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 2126, in trace
    return self._trace_inner(f, *args)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 2097, in _trace_inner
    t = dispatch_trace(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 721, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 1137, in dispatch_trace
    graph = tracer.trace(root, concrete_args)  # type: ignore[arg-type]
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 721, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 843, in trace
    (self.create_arg(fn(*args)),),
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 700, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 1192, in wrapped
    out = f(*tensors)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 693, in inner_fn
    outs = fn(*args)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 644, in joint_helper
    return _functionalized_f_helper(primals, tangents)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 413, in _functionalized_f_helper
    f_outs = fn(*f_args)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 280, in inner_fn_with_anomaly
    return inner_fn(*args)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 265, in inner_fn
    backward_out = torch.autograd.grad(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 445, in grad
    return handle_torch_function(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/overrides.py", line 1719, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 1240, in __torch_function__
    return func(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 496, in grad
    result = _engine_run_backward(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py", line 545, in __torch_dispatch__
    outs_unwrapped = func._op_dk(
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 1342, in __torch_dispatch__
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 911, in proxy_call
    out = func(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1271, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1813, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1381, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2297, in _dispatch_impl
    r = func(*args, **kwargs)
  File "/data/users/williamwen/watermark-anything-env/lib/python3.10/site-packages/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: isIntList() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/core/ivalue_inl.h":1979, please report a bug to PyTorch. Expected IntList but got GenericList
```
in various functions in Watermark-Anything, for example,
```python
        resize = transforms.Resize(
            (h, w), interpolation=transforms.InterpolationMode.BILINEAR
        )

        inverse_resize = transforms.Resize(
            (imgs.shape[-2:]),
            interpolation=transforms.InterpolationMode.BILINEAR,
            antialias=True,
        )
```
The crash only happens on aot_eager backend and lower.

Checkout https://github.com/williamwen42/watermark-anything/tree/compile to repro - run `python playground.py`. Remove the `torch.compiler.disable` calls in https://github.com/williamwen42/watermark-anything/blob/compile/watermark_anything/models/wam.py to repro the crash.

cc @chauhang @penguinwu @eellison @ezyang @bobrenjc93 @zou3519 @bdhirsh @yf225

**Comment by bdhirsh** [comment]
We're missing a (dynamic shape friendly) fake tensor rule for `aten._upsample_bilinear2d_aa_backward`. Looks like we have one for the forward [here](https://github.com/pytorch/pytorch/blob/main/torch/_meta_registrations.py#L6212) but not the backward op

Minimal repro:
```
import torch

@torch.compile(backend="aot_eager", dynamic=True)
def f(x):
    return torch.nn.functional.interpolate(x, size = [256, 256], mode = 'bilinear', align_corners = False, antialias = True)

x = torch.randn(1, 3, 2005, 1920, device='cuda', requires_grad=True)
out = f(x)
```

**Comment by bdhirsh** [comment]
side note: it would be great if we could make this error message better in the spirit of user empathy
