### ISSUE TITLE
[user empathy day] AOTDispatcher fails when calling copy_(int)

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#141149]
### 🐛 Describe the bug

```python
    def test_copy_int(self): 
        class M(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.b = torch.ones(3)
        
            def forward(self, x):
                seq_len = 2
                self.b.copy_(seq_len)
                return x + self.b
        
        M()(torch.ones(3))
        torch.compile(M())(torch.ones(3))
```

fails with:
```
======================================================================
ERROR: test_copy_int (__main__.TestMoo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/angelayi/pytorch/torch/testing/_internal/common_utils.py", line 3069, in wrapper
    method(*args, **kwargs)
  File "/data/users/angelayi/pytorch/moo.py", line 46, in test_copy_int
    torch.compile(M())(torch.ones(3))
  File "/data/users/angelayi/pytorch/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_dynamo/eval_frame.py", line 556, in _fn
    return fn(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 1401, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 1185, in __call__
    result = self._inner_convert(
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 549, in __call__
    return _compile(
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 982, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 712, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/angelayi/pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 747, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/angelayi/pytorch/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 233, in _fn
    return fn(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_dynamo/convert_frame.py", line 664, in transform
    tracer.run()
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 2841, in run
    super().run()
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 1032, in run
    while self.step():
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 944, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 3021, in RETURN_VALUE
    self._return(inst)
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 3006, in _return
    self.output.compile_subgraph(
  File "/data/users/angelayi/pytorch/torch/_dynamo/output_graph.py", line 1077, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/data/users/angelayi/pytorch/torch/_dynamo/output_graph.py", line 1349, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/angelayi/pytorch/torch/_dynamo/output_graph.py", line 1399, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/data/users/angelayi/pytorch/torch/_dynamo/output_graph.py", line 1448, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/angelayi/pytorch/torch/_dynamo/output_graph.py", line 1429, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/angelayi/pytorch/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/angelayi/pytorch/torch/__init__.py", line 2301, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/data/users/angelayi/pytorch/torch/_inductor/compile_fx.py", line 1733, in compile_fx
    return aot_autograd(
  File "/data/users/angelayi/pytorch/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/data/users/angelayi/pytorch/torch/_functorch/aot_autograd.py", line 1103, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/data/users/angelayi/pytorch/torch/_functorch/aot_autograd.py", line 1079, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/data/users/angelayi/pytorch/torch/_functorch/aot_autograd.py", line 527, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/data/users/angelayi/pytorch/torch/_functorch/aot_autograd.py", line 635, in _create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/data/users/angelayi/pytorch/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 197, in inner
    flat_f_outs = f(*flat_f_args)
  File "/data/users/angelayi/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 875, in functional_call
    out = PropagateUnbackedSymInts(mod).run(
  File "/data/users/angelayi/pytorch/torch/fx/interpreter.py", line 167, in run
    self.env[node] = self.run_node(node)
  File "/data/users/angelayi/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6584, in run_node
    result = super().run_node(n)
  File "/data/users/angelayi/pytorch/torch/fx/interpreter.py", line 228, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/angelayi/pytorch/torch/fx/interpreter.py", line 332, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/functional_tensor.py", line 545, in __torch_dispatch__
    outs_unwrapped = func._op_dk(
  File "/data/users/angelayi/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_tensor.py", line 1271, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_tensor.py", line 1813, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_tensor.py", line 1372, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_tensor.py", line 2267, in _dispatch_impl
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_impls.py", line 147, in dispatch_to_op_implementations_dict
    return op_implementations_dict[func](fake_mode, func, *args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_impls.py", line 641, in multi_device_op_default
    return run_and_return_new_tensor_of_input_device(fake_mode, func, args, kwargs)
  File "/data/users/angelayi/pytorch/torch/_subclasses/fake_impls.py", line 551, in run_and_return_new_tensor_of_input_device
    out = func(*args, **kwargs)
  File "/data/users/angelayi/pytorch/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: aten::copy() Expected a value of type 'Tensor' for argument 'src' but instead found type 'int'.
Position: 1
Value: 2
Declaration: aten::copy(Tensor self, Tensor src, bool non_blocking=False) -> Tensor
Cast error details: Unable to cast 2 to Tensor

While executing %copy_ : [num_users=0] = call_method[target=copy_](args = (%l_self_b, 2), kwargs = {})
Original traceback:
  File "/data/users/angelayi/pytorch/moo.py", line 42, in forward
    self.b.copy_(seq_len)
```

### Versions

main

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @bdhirsh @yf225

**Comment by bdhirsh** [comment]
Looks like `aten.copy_()` supports scalar overloads, but `aten.copy` does not:
```
>>> x = torch.ones(2)
>>> torch.ops.aten.copy_(x, 2)
tensor([2., 2.])
>>> torch.ops.aten.copy(x, 2)
```

**Comment by anijain2305** [comment]
Turning high-priority due to user-empathy day.

**Comment by bdhirsh** [comment]
I have a PR that's been languishing - let me try to land this week
