### ISSUE TITLE
Not all values of RelaxedUnspecConstraint(L['old_my_residual_1'].size()[0]) are valid because L['old_my_residual_1'].size()[0] was inferred to be a constant (256).

### ISSUE THREAD

**Issue by bnellnm** [pytorch/pytorch#141251]
### 🐛 Describe the bug

Running the following script results in the above error (full stack trace included below).  The script works fine if @torch.compile is removed or if `old_my_residual` is not marked as dynamic.  The script is whittled down from a larger example so doesn't do anything meaningful.

The error seems similar to https://github.com/pytorch/pytorch/issues/106110

```
import torch
from typing import Tuple


@torch.library.custom_op("vllm::gemm_rs_4096_float16_4096_tp_0", mutates_args=[])
def gemm_rs_4096_float16_4096_tp_0(getitem: torch.Tensor,
                                   gemm_1_activations_1: torch.Tensor,
                                   gemm_1_weights_1: torch.Tensor) -> torch.Tensor:
    return torch.ops.aten.mm.default(gemm_1_activations_1,
                                     gemm_1_weights_1.transpose(1, 0))


@torch.library.register_fake("vllm::gemm_rs_4096_float16_4096_tp_0")
def gemm_rs_4096_float16_4096_tp_0_fake(res: torch.Tensor, act: torch.Tensor, wt: torch.Tensor) -> torch.Tensor:
    return torch.ops.aten.mm.default(act, wt.transpose(1, 0))


@torch.library.custom_op("vllm::ag_gemm_4096_float16_14336_4096_tp_0", mutates_args=[])
def ag_gemm_4096_float16_14336_4096_tp_0(getitem: torch.Tensor,
                                         gemm_2_activations_1: torch.Tensor,
                                         gemm_2_weights_1: torch.Tensor) -> torch.Tensor:
    return torch.ops.aten.mm.default(gemm_2_activations_1,
                                     gemm_2_weights_1.transpose(1, 0))


@torch.library.register_fake("vllm::ag_gemm_4096_float16_14336_4096_tp_0")
def ag_gemm_4096_float16_14336_4096_tp_0_fake(getitem: torch.Tensor,
                                              gemm_2_activations_1: torch.Tensor,
                                              gemm_2_weights_1: torch.Tensor) -> torch.Tensor:
    return torch.ops.aten.mm.default(gemm_2_activations_1,
                                     gemm_2_weights_1.transpose(1, 0))


@torch.library.custom_op("vllm::fused_add_rms_norm", mutates_args=["input", "residual"])
def fused_add_rms_norm(input: torch.Tensor,
                       residual: torch.Tensor,
                       weight: torch.Tensor,
                       epsilon: float) -> None:
    orig_dtype = input.dtype
    input = input.to(torch.float32)
    if residual is not None:
        input = input + residual.to(torch.float32)
        residual = input.to(orig_dtype)

    hidden_size = input.shape[-1]
    x_var = input
    variance = x_var.pow(2).mean(dim=-1, keepdim=True)

    input = input * torch.rsqrt(variance + epsilon)
    input = input.to(orig_dtype) * weight


class gemm_rs_ag_gemm(torch.nn.Module):
    @torch.compile(fullgraph=True)
    def forward(self, residual_1: torch.Tensor,
                old_my_residual_1: torch.Tensor,
                gemm_1_weights_1: torch.Tensor,
                gemm_1_activations_1: torch.Tensor,
                rms_norm_weight_1: torch.Tensor,
                gemm_2_weights_1: torch.Tensor,
                first_layer_1: bool) -> Tuple[torch.Tensor,torch.Tensor,torch.Tensor]:
        split_size = 256

        split = torch.ops.aten.split.Tensor(old_my_residual_1, split_size)
        getitem = split[0]
        split = None

        gemm_rs_4096_float16_4096_tp_0 = \
            torch.ops.vllm.gemm_rs_4096_float16_4096_tp_0.default(getitem,
                                                                  gemm_1_activations_1,
                                                                  gemm_1_weights_1)
        gemm_1_activations_1 = gemm_1_weights_1 = None

        fused_add_rms_norm(
            input = gemm_rs_4096_float16_4096_tp_0,
            residual = getitem,
            weight = rms_norm_weight_1,
            epsilon = 1e-05)
        getitem_3 = gemm_rs_4096_float16_4096_tp_0
        getitem_4 = getitem

        slice_scatter = torch.ops.aten.slice_scatter.default(old_my_residual_1,
                                                                              getitem_4,
                                                                              0,
                                                                              0,
                                                                              split_size)
        getitem_4 = None
        split_1 = torch.ops.aten.split.Tensor(slice_scatter, split_size)
        getitem_5 = split_1[0];  split_1 = None

        ag_gemm_4096_float16_14336_4096_tp_0 = \
            torch.ops.vllm.ag_gemm_4096_float16_14336_4096_tp_0.default(old_my_residual_1,
                                                                        getitem_3,
                                                                        gemm_2_weights_1)
        old_my_residual_1 = getitem_3 = gemm_2_weights_1 = None

        return (ag_gemm_4096_float16_14336_4096_tp_0, getitem_5, slice_scatter)


def empty(a, b):
    return torch.empty((a,b), device="cuda", dtype=torch.float16)


M = 256
residual_1: "f16[s0, 4096]" = empty(M, 4096)
old_my_residual_1: "f16[s0, 4096]" = empty(M, 4096)
gemm_1_weights_1: "f16[4096, 2048]" = empty(4096, 2048)
gemm_1_activations_1: "f16[s0, 2048]" = empty(M, 2048)
rms_norm_weight_1: "f16[4096]" = empty(M,1)
gemm_2_weights_1: "f16[14336, 4096]" = empty(14336, 4096)
first_layer_1 = False

obj = gemm_rs_ag_gemm()
torch._dynamo.mark_dynamic(residual_1, 0)

# comment out the next line and the program will run.
torch._dynamo.mark_dynamic(old_my_residual_1, 0)

torch._dynamo.mark_dynamic(gemm_1_activations_1, 0)
a, b, c = obj.forward(residual_1,
                      old_my_residual_1,
                      gemm_1_weights_1,
                      gemm_1_activations_1,
                      rms_norm_weight_1,
                      gemm_2_weights_1,
                      first_layer_1)

print(a)
print(b)
print(c)
```

Full stack trace:
```
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0] Error while creating guard:
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0] Name: ''
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     Source: shape_env
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     Create Function: SHAPE_ENV
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     Guard Types: None
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     Code List: None
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     Object Weakref: None
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     Guarded Class Weakref: None
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0] Traceback (most recent call last):
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/_guards.py", line 281, in create
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     return self.create_fn(builder, self)
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 1836, in SHAPE_ENV
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     guards = output_graph.shape_env.produce_guards(
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4178, in produce_guards
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]     raise ConstraintViolationError(
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0] torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['old_my_residual_1'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
E1121 16:47:58.615000 2714600 torch/_guards.py:283] [0/0]   - Not all values of RelaxedUnspecConstraint(L['old_my_residual_1'].size()[0]) are valid because L['old_my_residual_1'].size()[0] was inferred to be a constant (256).
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0] Created at:
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 615, in transform
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]     tracer = InstructionTranslator(
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2670, in __init__
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]     output=OutputGraph(
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 317, in __init__
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]     self.init_ambient_guards()
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]   File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 463, in init_ambient_guards
E1121 16:47:58.616000 2714600 torch/_guards.py:285] [0/0]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
Traceback (most recent call last):
  File "/home/bnell/nm-vllm-newer/replace.py", line 120, in <module>
    a, b, c = obj.forward(residual_1,
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1269, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 796, in _compile_inner
    check_fn = CheckFunctionManager(
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 2261, in __init__
    guard.create(builder)
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_guards.py", line 281, in create
    return self.create_fn(builder, self)
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 1836, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/home/bnell/.local/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4178, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['old_my_residual_1'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of RelaxedUnspecConstraint(L['old_my_residual_1'].size()[0]) are valid because L['old_my_residual_1'].size()[0] was inferred to be a constant (256).


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

This is blocking some work for vLLM.

cc @ezyang , @Chillee , @zou3519 

### Versions

[python-env.txt](https://github.com/user-attachments/files/17849370/python-env.txt)

**Comment by zou3519** [comment]
Workaround in this case seems like changing the split to take in a dynamic shape:
```py
split_size = old_my_residual_1.size(0)
split = torch.ops.aten.split.Tensor(old_my_residual_1, split_size)
```
I'm not sure if we can do anything from the framework side (thoughts @ezyang @bobrenjc93?)

**Comment by ezyang** [comment]
Did https://github.com/pytorch/pytorch/pull/141077 fix this?

**Comment by ezyang** [comment]
cc @ysiraichi

**Comment by ysiraichi** [comment]
Not really.
The issue here is that `L['old_my_residual_1'].size()[0]` (i.e. `s0`) is getting specialized because of the value range analysis:

- **Upper bound:** `torch.split(old_my_residual_1, split_size)`: asserts that `Eq(((s0 + 255)//256), 1)` (number of chunks), which refines its range to `[2, 256]`
- **Lower bound:** `torch.slice_scatter(old_my_residual_1, getitem_4, 0, 0, split_size)`: asserts that `256 <= s0` (wrap end of the slice), which refines its range to `[256, 256]`

Replacing 256 by a size variable works because both upper and lower bounds become statically known. Which means, it doesn't get specialized.

**Comment by ysiraichi** [comment]
One possible solution would be to change the condition below (inside `slice` decomposition) to:

https://github.com/pytorch/pytorch/blob/09a3eddc071f21acd525b6e7074476bede126325/torch/_decomp/decompositions.py#L781-L784

```python

 elif statically_known_true(end_val == sys.maxsize) or guard_size_oblivious( 
     end_val >= sizes[dim]  # Instead of '>' 
 ): 
     end_val = sizes[dim] 
```

Which would generate the true expression: `256 >= s0`, an upper bound! Which means that we would not generate a lower bound, i.e. no specialization.

That said, I do think this is a little too brittle.
Let me know what you think.

**Comment by ysiraichi** [comment]
I do wonder, however, whether we really need to guard on the number of chunks (upper bound), though. For example, we could return a custom list of length `((s0 + 255)//256)`. Then, when getting an item from it (e.g. `split[0]`), we could issue a guard `((s0 + 255)//256) >= 1`, since, otherwise, `split[0]` would error.

**Comment by ezyang** [comment]
I have definitely done the `>` to `>=` replacement before, try sending in a patch for it.

We don't really have any provision for returning variadic lists. Maybe you could talk me into supporting it, but probably not lol
