### ISSUE TITLE
Compiled `nn.Module` with tensor subclass can't be moved to another device

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/pytorch#141548]
### 🐛 Describe the bug

```python
import torch

aten = torch.ops.aten

class Subclass(torch.Tensor):
    def __new__(cls, data):
        return torch.Tensor._make_wrapper_subclass(cls, data.shape, dtype=data.dtype, device=data.device)

    def __init__(self, data):
        self._data = data

    def __repr__(self):
        return f"{self.__class__.__name__}(data={self._data})"

    def __tensor_flatten__(self):
        return ["_data"], []

    @classmethod
    def __tensor_unflatten__(cls, inner_tensors, ctx, outer_size, outer_stride):
        return cls(inner_tensors["_data"])

    def __torch_function__(self, func, types, args, kwargs=None):
        if func == torch.nn.functional.linear:
            return func(args[0], args[1]._data, *args[2:])

        with torch._C.DisableTorchFunctionSubclass():
            return func(*args, **(kwargs or dict()))

    def __torch_dispatch__(self, func, types, args, kwargs):
        if func in (aten._to_copy.default, aten.detach.default):
            args = [x._data if isinstance(x, Subclass) else x for x in args]
            out = func(*args, **kwargs)
            return Subclass(out)

        raise NotImplementedError(f"{func=}")


linear = torch.nn.Linear(2, 2)
linear.weight = torch.nn.Parameter(Subclass(linear.weight.detach()))
linear.compile()
linear(torch.randn(1, 2))
linear.cpu()  # doesn't work even for the same device
```
```
RuntimeError                              Traceback (most recent call last)
File ~/xxx/python3.10/site-packages/torch/nn/modules/module.py:948, in Module._apply(self, fn, recurse)
    945     param_applied = torch.nn.Parameter(
    946         param_applied, requires_grad=param.requires_grad
    947     )
--> 948     torch.utils.swap_tensors(param, param_applied)
    949 except Exception as e:

File ~/xxx/python3.10/site-packages/torch/utils/__init__.py:51, in swap_tensors(t1, t2)
     50 if weakref.getweakrefs(t1):
---> 51     raise RuntimeError("Cannot swap t1 because it has weakref associated with it")
     52 if weakref.getweakrefs(t2):

RuntimeError: Cannot swap t1 because it has weakref associated with it

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[1], line 42
     40 linear.compile()
     41 linear(torch.randn(1, 2))
---> 42 linear.cpu()

File ~/xxx/python3.10/site-packages/torch/nn/modules/module.py:1121, in Module.cpu(self)
   1112 def cpu(self: T) -> T:
   1113     r"""Move all model parameters and buffers to the CPU.
   1114 
   1115     .. note::
   (...)
   1119         Module: self
   1120     """
-> 1121     return self._apply(lambda t: t.cpu())

File ~/xxx/python3.10/site-packages/torch/nn/modules/module.py:952, in Module._apply(self, fn, recurse)
    950         if param_grad is not None:
    951             param.grad = param_grad
--> 952         raise RuntimeError(
    953             f"_apply(): Couldn't swap {self._get_name()}.{key}"
    954         ) from e
    955     out_param = param
    956 elif p_should_use_set_data:

RuntimeError: _apply(): Couldn't swap Linear.weight
```

Per title. A compiled module with tensor subclass can't be moved to another device. cc: pytorch/ao#1309

### Versions

torch==2.6.0.dev20241125+cu124

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @albanD @chauhang @penguinwu @bdhirsh @yf225

**Comment by Chillee** [comment]
cc: @bdhirsh

**Comment by bdhirsh** [comment]
The repro errors in `swap_tensors()` [here](https://github.com/pytorch/pytorch/blob/main/torch/utils/__init__.py#L51), because there outstanding weakrefs taken out on the subclass:

It looks like:

(1) there are a few places throughout compile where we take out weakrefs to the params in some form (at a first glance, there are several that come from guards, and one from the dict around `SubclassSymbolicContext`)

(2) `swap_tensors()` isn't ok with having any outstanding weakrefs on any parameters you want to swap


One high level question is: it looks like in order to support this, we're going to need to make sure that compile doesn't store any weakrefs to subclass params/tensors. Does this seem like a reasonable invariant to try to uphold? (cc @ezyang in case you have any thoughts).

**Comment by bdhirsh** [comment]
One example is that the `MetaConverter` on `FakeTensorMode` has a `tensor_meta` dict of tensor weakrefs [here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L676). And it looks like there are several places where we keep the `FakeTensorMode` alive after we are done compiling. One example:

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/48eacf4c-46db-465a-ba58-d390f4f6f78a">


So it might be a bit of whack-a-mole to stamp out all of the places where we stash weakrefs to tensors after compilation is finished

**Comment by ezyang** [comment]
@bdhirsh How many more are there? Because we can totally dump MetaConverter's weakrefs at the end of compilation. In fact, when I wrote MetaConverter I did have to break some refcycles at end of compile, so we can break some more.

**Comment by bdhirsh** [comment]
I'll dig some more and try to get a complete list

**Comment by ezyang** [comment]
Why would the guards weakref on tensors though? That seems unlikely :)

**Comment by bdhirsh** [comment]
Oh the guard-related weakref looks more incidental than fundamental - we take out a weakref [here](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/builder.py#L1691) and then generate a strong reference inside the `TENSOR_MATCH` code [here](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/guards.py#L1928). When I remove that weakref I see the number of outstanding weakrefs drop from 3 to 2 after we're done running the compiled model.

@zou3519 also pointed me to https://github.com/pytorch/pytorch/issues/141452, where it sounds like "dynamo using sources to grab inputs to the compiled region at runtime" is slow, and one of the suggested alternatives is to stash weakrefs to graph args so dynamo can pass them to compile more efficiently.

So if we want the invariant that there are no weakrefs to any graph inputs after compilation is done, we'll have to take that design off the table

**Comment by bghira** [comment]
this is still an issue for torchao or quanto for sure.. some kind of 'decompile' wrapper would be nice.

**Comment by drisspg** [comment]
Curious if there is any update here?

**Comment by ezyang** [comment]
I don't remember us actually fixing this

**Comment by drisspg** [comment]
Yeah, sayak is running into this w/ 

```Py
import torch
from diffusers import AutoModel, TorchAoConfig

def get_input_dict(**device_dtype_kwargs):
    # resolution: 1024x1024
    # maximum sequence length 512
    hidden_states = torch.randn(1, 4096, 64, **device_dtype_kwargs)
    encoder_hidden_states = torch.randn(1, 512, 4096, **device_dtype_kwargs)
    pooled_prompt_embeds = torch.randn(1, 768, **device_dtype_kwargs)
    image_ids = torch.ones(512, 3, **device_dtype_kwargs)
    text_ids = torch.ones(4096, 3, **device_dtype_kwargs)
    timestep = torch.tensor([1.0], **device_dtype_kwargs)
    guidance = torch.tensor([1.0], **device_dtype_kwargs)

    return {
        "hidden_states": hidden_states,
        "encoder_hidden_states": encoder_hidden_states,
        "img_ids": image_ids,
        "txt_ids": text_ids,
        "pooled_projections": pooled_prompt_embeds,
        "timestep": timestep,
        "guidance": guidance,
    }

dtype = torch.bfloat16
model_id = "black-forest-labs/FLUX.1-dev"
quant_config = TorchAoConfig("int8wo")
transformer = AutoModel.from_pretrained(
    model_id, 
    subfolder="transformer", 
    quantization_config=quant_config, 
    torch_dtype=dtype
).to("cuda")
transformer.compile() # this is beneficial from the subsequent pipeline calls.

inputs = get_input_dict(dtype=dtype, device="cuda")
with torch.no_grad():
    for _ in range(4):
        _ = transformer(**inputs)

transformer.cpu() # error
```
Where: "offloading which is a very crucial use case in the diffusion community."

**Comment by bdhirsh** [comment]
No bandwidth to work on this currently but I can shop to see if anyone else has bandwidth

**Comment by sayakpaul** [comment]
Just chiming in here to say that if it's supported, it will be incredibly useful. 

The use case is the following.

* We quantize with `torchao`. 
* We offload some parts of a given model to save on memory (for diffusion, it's almost a default setup). Offloading can be done on the entire model-level, too (meaning a model is completely offloaded to CPU when it's not needed).
* We compile to benefit from latency improvements. 

The above workflow gives a very reasonable speed-memory trade-off on consumer cards and its effects become particularly pronounced when using compute-heavy models like Wan2.1-14B.

**Comment by bdhirsh** [comment]
@IvanKobzarev is going to take a look

**Comment by azahed98** [comment]
I monkey patched `weakref` to track tracebacks when weakrefs are created. For the original example, I found the following 4 creation sites (click in to see since they're a bit long)

<details>
<summary>Weakref 1: HASATTR Guard</summary>

```
   File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 691, in __call__
    result = _compile(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1569, in _compile
    guarded_code, tracer_output = compile_inner(code, one_graph, hooks)
  File "/data/users/arshzahed/pytorch/torch/_utils_internal.py", line 92, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1251, in compile_inner
    return _compile_inner(code, one_graph, hooks)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1385, in _compile_inner
    check_fn = dynamo_output.build_guards(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 860, in build_guards
    return CheckFunctionManager(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 3472, in __init__
    builder, guard_manager = self.build_guards(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 3763, in build_guards
    guard.create(builder)
  File "/data/users/arshzahed/pytorch/torch/_guards.py", line 364, in create
    return self.create_fn(builder, self)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 1836, in HASATTR
    self._set_guard_export_info(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 2925, in _set_guard_export_info
    obj_ref = weakref.ref(guarded_object)
  File "/data/users/arshzahed/pytorch/test_move_subclass.py", line 11, in __new__
    self._creation_stack = traceback.format_stack(limit=12)
```

</details>

<details>
<summary>Weakref 2: TENSOR_MATCH Guard</summary>

```
   File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 691, in __call__
    result = _compile(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1569, in _compile
    guarded_code, tracer_output = compile_inner(code, one_graph, hooks)
  File "/data/users/arshzahed/pytorch/torch/_utils_internal.py", line 92, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1251, in compile_inner
    return _compile_inner(code, one_graph, hooks)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1385, in _compile_inner
    check_fn = dynamo_output.build_guards(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 860, in build_guards
    return CheckFunctionManager(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 3472, in __init__
    builder, guard_manager = self.build_guards(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 3763, in build_guards
    guard.create(builder)
  File "/data/users/arshzahed/pytorch/torch/_guards.py", line 364, in create
    return self.create_fn(builder, self)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 2880, in TENSOR_MATCH
    self._set_guard_export_info(guard, code)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 2925, in _set_guard_export_info
    obj_ref = weakref.ref(guarded_object)
  File "/data/users/arshzahed/pytorch/test_move_subclass.py", line 11, in __new__
    self._creation_stack = traceback.format_stack(limit=12)
```

</details>

<details>
<summary>Weakref 3: TYPE_MATCH Guard</summary>

```
   File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 691, in __call__
    result = _compile(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1569, in _compile
    guarded_code, tracer_output = compile_inner(code, one_graph, hooks)
  File "/data/users/arshzahed/pytorch/torch/_utils_internal.py", line 92, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1251, in compile_inner
    return _compile_inner(code, one_graph, hooks)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 1385, in _compile_inner
    check_fn = dynamo_output.build_guards(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/convert_frame.py", line 860, in build_guards
    return CheckFunctionManager(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 3472, in __init__
    builder, guard_manager = self.build_guards(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 3763, in build_guards
    guard.create(builder)
  File "/data/users/arshzahed/pytorch/torch/_guards.py", line 364, in create
    return self.create_fn(builder, self)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 1910, in TYPE_MATCH
    self._set_guard_export_info(guard, [code])
  File "/data/users/arshzahed/pytorch/torch/_dynamo/guards.py", line 2925, in _set_guard_export_info
    obj_ref = weakref.ref(guarded_object)
  File "/data/users/arshzahed/pytorch/test_move_subclass.py", line 11, in __new__
    self._creation_stack = traceback.format_stack(limit=12)
```

</details>

<details>
<summary>Weakref 4: VariableBuilder.wrap_tensor installs TENSOR_MATCH guard</summary>

````
   File "/data/users/arshzahed/pytorch/torch/_dynamo/symbolic_convert.py", line 1345, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/symbolic_convert.py", line 2434, in LOAD_ATTR
    self._load_attr(inst)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/symbolic_convert.py", line 2422, in _load_attr
    result = BuiltinVariable(getattr).call_function(
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/builtin.py", line 1346, in call_function
    return handler(tx, args, kwargs)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/builtin.py", line 966, in <lambda>
    tx, [v.realize() for v in args], kwargs
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/lazy.py", line 72, in realize
    self._cache.realize()
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/lazy.py", line 33, in realize
    self.vt = builder.VariableBuilder(tx, self.source)(self.value)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/builder.py", line 451, in __call__
    vt = self._wrap(value)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/builder.py", line 704, in _wrap
    return self.wrap_tensor(value)
  File "/data/users/arshzahed/pytorch/torch/_dynamo/variables/builder.py", line 2209, in wrap_tensor
    else TensorWeakRef(value)
  File "/data/users/arshzahed/pytorch/torch/utils/weak.py", line 354, in __init__
    self.ref = weakref.ref(tensor)
  File "/data/users/arshzahed/pytorch/test_move_subclass.py", line 11, in __new__
    self._creation_stack = traceback.format_stack(limit=12)
```

</details>

I also generated this objgraph - I don't know what most of it on the right is and if its relevant, but on the left you can see the 4 weakrefs.

Based off this, it seems the MetaConverter no longer an issue, and all remaining weakrefs are guard related

cc @bdhirsh

**Comment by azahed98** [comment]
Shouldn't be closed - one source was fixed but there are still remaining weakrefs. I accidentally marked the other PR as resolving this issue.

Instead #171209 should resolve the issue (currently WIP)
