### ISSUE TITLE
RuntimeError: cuda runtime error (30) unknown error

### ISSUE THREAD

**Issue by sbhakat** [pytorch/pytorch#14169]
I was trying to run the script submission.sh inside generative_model folder from the attached .gz file and getting the following error

```
processing batches ...
THCudaCheck FAIL file=/scratch/zao/eb/PyTorch/0.3.1/goolfc-2017.02-Python-3.5.2/pytorch-0.3.1/torch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
Traceback (most recent call last):
  File "generator_training.py", line 50, in <module>
    train_batches,val_batches = process_data_to_batches(data,batch_size,vocabs,cuda)
  File "/pfs/nobackup/home/s/sbhakat/Generate-novel-molecules-with-LSTM-master/generative_model/data_loading.py", line 53, in process_data_to_batches
    train,val = process_batch(hash_length_data[length],batch_size,vocabs,cuda)
  File "/pfs/nobackup/home/s/sbhakat/Generate-novel-molecules-with-LSTM-master/generative_model/data_loading.py", line 34, in process_batch
    inp = inp.cuda()
  File "/hpc2n/eb/software/MPI/GCC-CUDA/5.4.0-2.26-8.0.61_375.26/OpenMPI/2.1.1/PyTorch/0.3.1-Python-3.5.2/lib/python3.5/site-packages/torch/autograd/variable.py", line 298, in cuda
    return CudaTransfer.apply(self, device, async)
  File "/hpc2n/eb/software/MPI/GCC-CUDA/5.4.0-2.26-8.0.61_375.26/OpenMPI/2.1.1/PyTorch/0.3.1-Python-3.5.2/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 201, in forward
    return i.cuda(async=async)
  File "/hpc2n/eb/software/MPI/GCC-CUDA/5.4.0-2.26-8.0.61_375.26/OpenMPI/2.1.1/PyTorch/0.3.1-Python-3.5.2/lib/python3.5/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/hpc2n/eb/software/MPI/GCC-CUDA/5.4.0-2.26-8.0.61_375.26/OpenMPI/2.1.1/PyTorch/0.3.1-Python-3.5.2/lib/python3.5/site-packages/torch/cuda/__init__.py", line 384, in _lazy_new
    _lazy_init()
  File "/hpc2n/eb/software/MPI/GCC-CUDA/5.4.0-2.26-8.0.61_375.26/OpenMPI/2.1.1/PyTorch/0.3.1-Python-3.5.2/lib/python3.5/site-packages/torch/cuda/__init__.py", line 142, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /scratch/zao/eb/PyTorch/0.3.1/goolfc-2017.02-Python-3.5.2/pytorch-0.3.1/torch/lib/THC/THCGeneral.c:70
```

my submission.sh file looks like

```
module load GCC/5.4.0-2.26
module load CUDA/8.0.61_375.26
module load OpenMPI/2.1.1
module load PyTorch/0.3.1-Python-3.5.2
python generator_training.py
```

Not sure what causes this error? Is this error reproducible?

https://www.dropbox.com/s/ri0zdvhhpasibl1/Generate-novel-mol.tar.gz?dl=0

 or is it something to do with my system?

**Comment by soumith** [comment]
"unknown error" usually is a lower level CUDA error that can happen for multiple reasons.
Can you maybe try updating PyTorch to the latest version instead of using 0.3.1?

**Comment by yaysummeriscoming** [comment]
Have you tried lowering your batch size?  This fixed a similar error I was getting recently.

**Comment by zou3519** [comment]
Closing due to age and lack of repro, please feel free to file us a new issue if you're still experiencing this problem.
