### ISSUE TITLE
While use torch.onnx.export to export an mode to onnx, there is an error

### ISSUE THREAD

**Issue by tombang** [pytorch/pytorch#141814]
### 🐛 Describe the bug

import whisper
import torch
import tensorflow as tf
import onnx
import numpy as np
import argparse
import os
import warnings
import tqdm
from onnx_tf.backend import prepare
from whisper.audio import load_audio, log_mel_spectrogram,pad_or_trim,N_FRAMES, SAMPLE_RATE
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

#load openai->whisper(pytorch)->tiny model
tiny_model = whisper.load_model("tiny")

#Export to onnx format
torch.onnx.export(tiny_model.encoder,torch.randn(1,80,3000).to(device), "./whisper_encoder.onnx",opset_version=14,verbose=True)

the error is below:

Traceback (most recent call last):
  File "/home/tangben/LLM/whisper/qidk-master/Solutions/NLPSolution3-AutomaticSpeechRecognition-Whisper/Generate_Assets/export_onnx.py", line 19, in <module>
    torch.onnx.export(tiny_model.encoder,torch.randn(1,80,3000).to(device), "./whisper_encoder.onnx",opset_version=14,verbose=True)
  File "/home/tangben/LLM/whisper/venv_qidk/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/tangben/LLM/whisper/venv_qidk/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/tangben/LLM/whisper/venv_qidk/lib/python3.10/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/home/tangben/LLM/whisper/venv_qidk/lib/python3.10/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/tangben/LLM/whisper/venv_qidk/lib/python3.10/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### Versions

Name: torch
Version: 2.0.1

Name: onnx
Version: 1.17.0

**Comment by titaiwangms** [comment]
Please use torch-nightly
