### ISSUE TITLE
AOTAutogradCache doesn't support view_replay

### ISSUE THREAD

**Issue by jamesjwu** [pytorch/pytorch#141974]
### 🐛 Describe the bug

When we first implemented AOTAutogradCache, we decided to punt this, but now that we're trying to release this to OSS, I think it's good to get more eyes on it, since it looks like a simple fix. 

Consider this simple test:
```
import torch
import torch._functorch.config

torch._functorch.config.view_replay_for_aliased_outputs = True
torch._functorch.config.strict_autograd_cache = True

def f(a):
    tmp = a.detach()
    a.mul_(2)
    return a, tmp

with torch.autograd._force_original_view_tracking(True):
    fn = torch.compile(f)
    out = fn(torch.rand(2,3))

print(out)
```

This fails when AOTAutogradCache attempts to serialize the ViewAndMutationMeta associated with the function. This is because view_replay logic stores a FunctionalTensor in it that represents an alias, with no underlying storage. When we try to serialize it, we try to access the underlying storage, but it doesn't exist, so we fail. This leads to more cache misses than necessary when running AOTAutogradCache, making it so that if there's ever a alias mutation on the output with view_replay turned on, AOTAutogradCache cannot serialize/save the cached object.

Stack trace:
```
W1203 08:57:32.604000 1374434 torch/_functorch/_aot_autograd/autograd_cache.py:837] [0/0] AOTAutograd cache unable to serialize compiled graph: Attempted to access the data pointer on an invalid python storage.
Traceback (most recent call last):
  File "/home/jjwu/test.py", line 14, in <module>
    out = fn(torch.rand(2,3))
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/eval_frame.py", line 573, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 1379, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 1163, in __call__
    result = self._inner_convert(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 547, in __call__
    return _compile(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 986, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 715, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/jjwu/a/pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 750, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1361, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/convert_frame.py", line 662, in transform
    tracer.run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2864, in run
    super().run()
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1053, in run
    while self.step():
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 963, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 3044, in RETURN_VALUE
    self._return(inst)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/symbolic_convert.py", line 3029, in _return
    self.output.compile_subgraph(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/output_graph.py", line 1118, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/output_graph.py", line 1359, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/output_graph.py", line 1409, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/output_graph.py", line 1460, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/output_graph.py", line 1439, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/jjwu/a/pytorch/torch/__init__.py", line 2308, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/data/users/jjwu/a/pytorch/torch/_inductor/compile_fx.py", line 1812, in compile_fx
    return aot_autograd(
  File "/data/users/jjwu/a/pytorch/torch/_dynamo/backends/common.py", line 73, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/data/users/jjwu/a/pytorch/torch/_functorch/aot_autograd.py", line 1092, in aot_module_simplified
    compiled_fn = AOTAutogradCache.load(
  File "/data/users/jjwu/a/pytorch/torch/_functorch/_aot_autograd/autograd_cache.py", line 744, in load
    compiled_fn = dispatch_and_compile()
  File "/data/users/jjwu/a/pytorch/torch/_functorch/aot_autograd.py", line 1078, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/data/users/jjwu/a/pytorch/torch/_functorch/aot_autograd.py", line 527, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/data/users/jjwu/a/pytorch/torch/_functorch/aot_autograd.py", line 777, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/data/users/jjwu/a/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 238, in aot_dispatch_base
    AOTAutogradCache.save(
  File "/data/users/jjwu/a/pytorch/torch/_functorch/_aot_autograd/autograd_cache.py", line 839, in save
    raise e
  File "/data/users/jjwu/a/pytorch/torch/_functorch/_aot_autograd/autograd_cache.py", line 835, in save
    content = pickle.dumps(entry)
  File "/data/users/jjwu/a/pytorch/torch/storage.py", line 1237, in __reduce__
    torch.save(self, b, _use_new_zipfile_serialization=False)
  File "/data/users/jjwu/a/pytorch/torch/serialization.py", line 944, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/data/users/jjwu/a/pytorch/torch/serialization.py", line 1093, in _legacy_save
    pickler.dump(obj)
  File "/data/users/jjwu/a/pytorch/torch/serialization.py", line 1090, in persistent_id
    return persistent_id(obj)
  File "/data/users/jjwu/a/pytorch/torch/serialization.py", line 1008, in persistent_id
    if storage.data_ptr() != 0:
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Attempted to access the data pointer on an invalid python storage.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

This is the object we store: 

https://github.com/pytorch/pytorch/blob/ed4831b93cadaf76d851aaf7ce234f1a356024fe/torch/_functorch/_aot_autograd/functional_utils.py#L365-L381

Unfortunately, even though we only need the metadata, we store the whole functional tensor. Since the tensor has no data_ptr() as it represents an alias, we fail to serialize it. 

There are a few simple enough fixes to this problem:

- We could adjust the serialization to handle FunctionalTensors with no underlying storage. This seems good overall, since there may be other cases that need to be able to save functional tensors. 
- We could also just change how `view_replay` uses functional tensors. It doesn't actually specifically need the functional tensor to begin with, it only uses the `view_metas` field: 
https://github.com/pytorch/pytorch/blob/ed4831b93cadaf76d851aaf7ce234f1a356024fe/torch/csrc/autograd/python_torch_functions_manual.cpp#L643

So we could just store the view metas and apply them, instead of taking in a whole tensor. 

### Versions

nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @bdhirsh @oulgen @masnesral @yf225

**Comment by bdhirsh** [comment]
> We could also just change how view_replay uses functional tensors. It doesn't actually specifically need the functional tensor to begin with, it only uses the view_metas field:

This feels pretty reasonable (the view-replay is done with a bunch of C++ lambdas, so we don't actually need the python `FunctionalTensor` at all to run it).

Although I think the next problem you'll run into is that it's not clear to me that pickle will do something reasonable when it tries to serialize the corresponding C++ view replay information:

- the vector of `ViewMetas`: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/FunctionalTensorWrapper.h#L276

- the C++ lambda that each `ViewMeta` stores: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/FunctionalStorageImpl.h#L47

**Comment by jamesjwu** [comment]
FWIW this doesn't block the launch, it just will make it so AOTAutogradCache will bypass any cases where view replay is turned on and the functional tensor for an output alias is not None. It's a bit annoying, though, that we can't know until *after* we've done AOTAutograd, though, so I can't check and bypass it in the same spot. But it should be okay to get around this for now as well by checking during the cache's save step if the object is in fact serializable.

**Comment by ysiraichi** [comment]
Yeah. I will take a look at this.

**Comment by jamesjwu** [comment]
To run with autograd cache, you can run the example with:

```
TORCHINDUCTOR_AUTOGRAD_CACHE=1 TORCHINDUCTOR_FX_GRAPH_CACHE=1 TORCH_LOGS=aot python ~/test.py
```
Or change the example to enable them all manually:

```
import torch
import torch._functorch.config

torch._functorch.config.view_replay_for_aliased_outputs = True
torch._functorch.config.enable_autograd_cache = True
torch._inductor.config.fx_graph_cache = True
torch._functorch.config.strict_autograd_cache = True

def f(a):
    tmp = a.detach()
    a.mul_(2)
    return a, tmp

with torch.autograd._force_original_view_tracking(True):
    fn = torch.compile(f)
    out = fn(torch.rand(2,3))

print(out)
```

**Comment by ysiraichi** [comment]
I don't think we can pickle `ViewMeta` function attributes. So, in order to solve that, I think we need to **make `ViewMeta` an abstract class.**

- Each operation inherits from it, implementing their `forward_fn` and `reverse_fn`
- Constructors have to store a copy of the operation's arguments (which have to be pickle-able)

This should also help to make view-replay work with dynamic shapes, too.
@bdhirsh What do you think?

**Comment by ezyang** [comment]
cc @aorenste, this is related to MetaTensorDesc serialization

**Comment by ysiraichi** [comment]
In an external discussion, we decided it would be better to make `ViewMeta` an abstract class, specializing it for each view operation. Also making them pickle-able, so that backends such, as PyTorch/XLA, can make use of the cache while skipping the view-replay.

**Comment by zou3519** [comment]
- We're running into this for some llama4 configuration in vLLM. I suspect the subgraph returns a view of one of the inputs.
- vLLM with standalone_compile is raising an assert saying that no AOTAutogradCache artifact was saved.
- vLLM with VLLM_USE_STANDALONE_COMPILE=0 is succeeding
- @jamesjwu and I debugged this down to AOTAutogradCache raising a bypass for the view replay logic
- The reason why VLLM_USE_STANDALONE_COMPILE=0 works is that it needs to recompile on warm start (it cannot just re-use the cache artifact).

edit: TL;DR: I think this is important for precompile, we need some way of serializing the AOTAutograd runtime wrappers.

**Comment by zou3519** [comment]
I don't think we are going to put cherry-pick into 2.9. This is a bit risky. We should still fix it soon though. Brian has a PR out for it.

**Comment by miladm** [comment]
Thanks - shall we pull this PR out of 2.9 milestone? @bdhirsh @zou3519
