### ISSUE TITLE
Compute output strides logic is incompatible with unbacked symints

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#142024]
### 🐛 Describe the bug

Internal ref: https://fb.workplace.com/groups/1075192433118967/posts/1538522730119266/?comment_id=1547734489198090&reply_comment_id=1553642601940612

<details>
  <summary>Full error logs</summary>

```python
WARNING:torch.fx.experimental.symbolic_shapes:failed during evaluate_expr(u0 > 2, hint=None, size_oblivious=True, forcing_spec=False
ERROR:torch.fx.experimental.recording:failed while running evaluate_expr(*(u0 > 2, None), **{'fx_node': False, 'size_oblivious': True})
Traceback (most recent call last):
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 2527, in run_node
    return node.target(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1270, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1810, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1380, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 2264, in _dispatch_impl
    return maybe_propagate_real_tensors(fast_impl(self, *args, **kwargs))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_impls.py", line 991, in fast_binary_impl
    return slow("no contiguity match")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_impls.py", line 862, in slow
    return slow_ref(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/wrappers.py", line 291, in _fn
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/wrappers.py", line 143, in _fn
    result = fn(**bound.arguments)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_refs/__init__.py", line 1096, in _ref
    output = prim(a, b)
             ^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_refs/__init__.py", line 1703, in mul
    return prims.mul(a, b)
           ^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1270, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1810, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1380, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 2306, in _dispatch_impl
    func.prim_meta_impl(*args, **kwargs)
  File "/data/users/xmfan/a/pytorch/torch/_prims/__init__.py", line 406, in _prim_elementwise_meta
    l2p_perm = utils.compute_elementwise_output_logical_to_physical_perm(*args_)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/__init__.py", line 527, in compute_elementwise_output_logical_to_physical_perm
    comparison = should_swap(perm[dim0], perm[dim1])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/__init__.py", line 509, in should_swap
    if guard_size_oblivious(shape[idx_a] > shape[idx_b]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 382, in guard_size_oblivious
    return expr.node.guard_size_oblivious("", 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/sym_node.py", line 564, in guard_size_oblivious
    r = self.shape_env.evaluate_expr(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/recording.py", line 263, in wrapper
    return retlog(fn(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6186, in evaluate_expr
    return self._evaluate_expr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6344, in _evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression u0 > 2 (unhinted: u0 > 2).  (Size-like symbols: u0)

Caused by: return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)  # unbacked.py:6 in fn (_prims_common/__init__.py:509 in should_swap)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/data/users/xmfan/a/pytorch/unbacked.py", line 6, in fn
    return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 2412, in get_fake_value
    ret_val = wrap_fake_exception(
              ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 1957, in wrap_fake_exception
    return fn()
           ^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 2413, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 2545, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 2527, in run_node
    return node.target(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1270, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1810, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1380, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 2264, in _dispatch_impl
    return maybe_propagate_real_tensors(fast_impl(self, *args, **kwargs))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_impls.py", line 991, in fast_binary_impl
    return slow("no contiguity match")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_impls.py", line 862, in slow
    return slow_ref(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/wrappers.py", line 291, in _fn
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/wrappers.py", line 143, in _fn
    result = fn(**bound.arguments)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_refs/__init__.py", line 1096, in _ref
    output = prim(a, b)
             ^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_refs/__init__.py", line 1703, in mul
    return prims.mul(a, b)
           ^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_ops.py", line 723, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1270, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1810, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 1380, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_subclasses/fake_tensor.py", line 2306, in _dispatch_impl
    func.prim_meta_impl(*args, **kwargs)
  File "/data/users/xmfan/a/pytorch/torch/_prims/__init__.py", line 406, in _prim_elementwise_meta
    l2p_perm = utils.compute_elementwise_output_logical_to_physical_perm(*args_)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/__init__.py", line 527, in compute_elementwise_output_logical_to_physical_perm
    comparison = should_swap(perm[dim0], perm[dim1])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_prims_common/__init__.py", line 509, in should_swap
    if guard_size_oblivious(shape[idx_a] > shape[idx_b]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 382, in guard_size_oblivious
    return expr.node.guard_size_oblivious("", 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/sym_node.py", line 564, in guard_size_oblivious
    r = self.shape_env.evaluate_expr(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/recording.py", line 263, in wrapper
    return retlog(fn(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6186, in evaluate_expr
    return self._evaluate_expr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/fx/experimental/symbolic_shapes.py", line 6344, in _evaluate_expr
    raise self._make_data_dependent_error(
RuntimeError: Failed running call_function aten.mul.Tensor(*(FakeTensor(..., size=(2, u0)), FakeTensor(..., size=(2, 1))), **{}):
Could not guard on data-dependent expression u0 > 2 (unhinted: u0 > 2).  (Size-like symbols: u0)

Caused by: return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)  # unbacked.py:6 in fn (_prims_common/__init__.py:509 in should_swap)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/data/users/xmfan/a/pytorch/unbacked.py", line 6, in fn
    return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/users/xmfan/a/pytorch/unbacked.py", line 12, in <module>
    fn(aot6_sub_58, aot6_mul_170)
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/eval_frame.py", line 573, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 1379, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 547, in __call__
    return _compile(
           ^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 986, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 715, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 750, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 1349, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/convert_frame.py", line 662, in transform
    tracer.run()
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2865, in run
    super().run()
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1054, in run
    while self.step():
          ^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 964, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 661, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2338, in CALL
    self._call(inst)
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 2332, in _call
    self.call_function(fn, args, kwargs)
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/symbolic_convert.py", line 899, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/variables/torch.py", line 953, in call_function
    tensor_variable = wrap_fx_proxy(
                      ^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/variables/builder.py", line 2123, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/variables/builder.py", line 2189, in wrap_fx_proxy_cls
    return _wrap_fx_proxy(
           ^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/variables/builder.py", line 2285, in _wrap_fx_proxy
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/xmfan/a/pytorch/torch/_dynamo/utils.py", line 2467, in get_fake_value
    raise UserError(  # noqa: B904
torch._dynamo.exc.UserError: Could not guard on data-dependent expression u0 > 2 (unhinted: u0 > 2).  (Size-like symbols: u0)

Caused by: return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)  # unbacked.py:6 in fn (_prims_common/__init__.py:509 in should_swap)
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/data/users/xmfan/a/pytorch/unbacked.py", line 6, in fn
    return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)

For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#constrain-as-size-example

from user code:
   File "/data/users/xmfan/a/pytorch/unbacked.py", line 6, in fn
    return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

  </summary>
</details>

`Could not guard on data-dependent expression u0 > 2 (unhinted: u0 > 2).  (Size-like symbols: u0)`. This error happens when fullgraph=True during dynamo tracing: we call `compute_elementwise_output_logical_to_physical_perm` to determine output strides of the matmul, which can swap dimensions for reasons I didn't really understand: https://github.com/pytorch/pytorch/blob/d6481333ad3371825be3fd5fda6d7eae1fad7345/torch/_prims_common/__init__.py#L491-L513

Any of these checks could error with unbacked symints, and in the repro below, we mark certain shapes as unbacked in order to avoid zero-one specialization, so we error when performing the last shape check: https://github.com/pytorch/pytorch/blob/d6481333ad3371825be3fd5fda6d7eae1fad7345/torch/_prims_common/__init__.py#L507-L509

Repro:
```python
import torch

@torch.compile(backend="eager", fullgraph=True)
def fn(aot6_sub_58, aot6_mul_170):
    aot6_unsqueeze_14 = torch.ops.aten.unsqueeze.default(aot6_mul_170, 1)
    return torch.ops.aten.mul.Tensor(aot6_sub_58, aot6_unsqueeze_14)

aot6_sub_58 = torch.randn(2, 1)
torch._dynamo.decorators.mark_unbacked(aot6_sub_58, 1)
aot6_mul_170 = torch.randn(2)

fn(aot6_sub_58, aot6_mul_170)
```
### Versions

main

cc @chauhang @penguinwu @ezyang @bobrenjc93 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by ezyang** [comment]
This feels like it should be overcomeable with size oblivious style. In the multiply, we are combining

```
FakeTensor(..., size=(2, u0))                                                                                                                                        
FakeTensor(..., size=(2, 1))
```

Clearly, a broadcasting should occur into u0. As both inputs are contiguous, the output should be contiguous too.

We are a bit in the weeds though so I'm not sure what the right fix is.

**Comment by ezyang** [comment]
It may be related to the fact that the unsqueeze means we no longer can take the contiguous fast path:

```
    # Short-circuits if contiguous or channels last, following the fake fast path.
    # This reduces the number of guards we end up making
    is_contiguous = True
    is_channels_last = True
    for t in tensors:
        is_contiguous = is_contiguous and t.is_contiguous(
            memory_format=torch.contiguous_format
        )   
        is_channels_last = is_channels_last and t.is_contiguous(
            memory_format=torch.channels_last
        )   
        
    if is_contiguous and not is_channels_last:
        return list(range(ndim))
        
    if is_channels_last and not is_contiguous:
        return [0, *list(range(2, ndim)), 1]
```

**Comment by ezyang** [comment]
Oh, actually, this is really interesting! There is actually not any problem with `compute_elementwise_output_logical_to_physical_perm`. Let us look at the size and stride of the input that was marked unbacked: size=[2, u0], stride=[**1**, 1] (emphasis mine). This is bad; the desired stride is stride=[u0, 1] (which is the stride that will keep the tensor contiguous when u0 != 1). When the stride is specialized to 1 nothing good will happen.

Now, there is a little bit of ambiguity here, unfortunately. Specifically, if you pass in a tensor size=[2, 1], stride=[1, 1], it is ambiguous if you intended for this tensor to be row major or column major. This is the classic stride does not uniquely determine memory layout problem. Fortunately, the `mark_unbacked` is from explicit user annotation so we can potentially simply ask the user to disambiguate (assuming that the input is contiguous is also reasonable). I think a good intuitive default is that when we mark a size 0/1 dimension as unbacked, we should attempt to treat left dimensions as contiguous relative to it so long as there isn't anything that explicitly contradicts it. But it also may be necessary for the user to explicitly specify what the layout permutation is, assuming it is contiguous.

@bobrenjc93 this is fully loaded, if you are interested.

**Comment by ezyang** [comment]
Another thought is that it is unpredictable what sizes you are going to get as inputs, so forcing users to upfront specify the contiguity (we can assume contiguous by default and error immediately if it is inconsistent) might be a way to detect problems faster.
