### ISSUE TITLE
Distributed FileSystem sync check

### ISSUE THREAD

**Issue by lshamis** [pytorch/pytorch#142396]
In `distributed/checkpoint/filesystem.py`, `write_data` / `_write_files_from_queue`, it tries to sync the stream, and catches `AttributeError` if the `FileSystem`'s stream does not provide such an operator.

The s3 plugin to Fsspec provides a stream that has the `fileno` attribute, but access raises `io.UnsupportedOperation`.
I think this can easily be solved by catching `io.UnsupportedOperation` along side `AttributeError` here:
https://github.com/pytorch/pytorch/blob/5e8e1d725aba3fa1010c59a0dc74670ece7f24bc/torch/distributed/checkpoint/filesystem.py#L333

Note that I cannot easily set `use_fsync` to bypass the check.
The Fsspec `FileSystem` is automatically applied by `_storage_setup` if the path begins with `s3://`, but `_storage_setup` does not provide a way to forward `sync_files=False`.

cc @LucasLLC @pradeepfn @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by SumanthRH** [comment]
Hit the same `io.UnsupportedOperation` error when I tried to upload files to S3/GCS storage. Looks like torch DCP breaks with remote paths right now? 


To Repro: 

```
import torch 
import torch.nn as nn 
import torch.distributed.checkpoint as dcp 

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(16, 16)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(16, 8)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

model = ToyModel()

state_dict = {"model": model.state_dict()}

path = "s3://<path to folder>" # or GCS path

dcp.save(state_dict, checkpoint_id=path)
```

Error: 

```
CheckpointException                       Traceback (most recent call last)
/home/ray/default/torch_dcp.ipynb Cell 6 line 7
      5 storage_writer = FsspecWriter(path)
----> 7 dcp.save(state_dict, checkpoint_id=path, storage_writer=storage_writer)

File ~/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/logger.py:83, in _dcp_method_logger.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
     81 # exceptions
     82 try:
---> 83     result = func(*args, **kwargs)
     84 except BaseException as error:
     85     if log_exceptions:

File ~/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/utils.py:429, in _api_bc_check.<locals>.inner_func(*args, **kwargs)
    427     return func(args[0], **kwargs)
    428 else:
--> 429     return func(*args, **kwargs)

File ~/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/state_dict_saver.py:152, in save(state_dict, checkpoint_id, storage_writer, planner, process_group)
    147 with _profile():
    148     storage_writer = cast(
    149         StorageWriter, _storage_setup(storage_writer, checkpoint_id, reader=False)
    150     )
--> 152     return _save_state_dict(
    153         state_dict=_stateful_to_state_dict(state_dict),
    154         storage_writer=storage_writer,
    155         process_group=process_group,
    156         no_dist=no_dist,
    157         planner=planner,
    158     )

File ~/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/state_dict_saver.py:333, in _save_state_dict(state_dict, storage_writer, process_group, coordinator_rank, no_dist, planner)
    330     storage_writer.finish(metadata=global_metadata, results=all_results)
    331     return global_metadata
--> 333 return distW.all_reduce("write", write_data, finish_checkpoint)

File ~/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/utils.py:231, in _DistWrapper.all_reduce(self, step, map_fun, reduce_fun)
    229 final_result = self.broadcast_object(result)
    230 if isinstance(final_result, CheckpointException):
--> 231     raise final_result
    232 return cast(R, final_result)

CheckpointException: CheckpointException ranks:dict_keys([0])
Traceback (most recent call last): (RANK 0)
  File "/home/ray/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/utils.py", line 211, in all_reduce
    local_data = map_fun()
                 ^^^^^^^^^
  File "/home/ray/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/logger.py", line 83, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 322, in write_data
    all_writes = storage_writer.write_data(final_local_plan, planner)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/filesystem.py", line 552, in write_data
    _write_files_from_queue(
  File "/home/ray/anaconda3/lib/python3.11/site-packages/torch/distributed/checkpoint/filesystem.py", line 333, in _write_files_from_queue
    os.fsync(stream.fileno())
             ^^^^^^^^^^^^^^^
io.UnsupportedOperation: fileno
```

**Comment by saumishr** [comment]
Thanks @lshamis for reporting the issue. https://github.com/pytorch/pytorch/pull/143046 should get this fixed.
