### ISSUE TITLE
[FlexAttention] Using FlexAttention with compiled_autograd complains "Cannot reenter make_fx"

### ISSUE THREAD

**Issue by YouJiacheng** [pytorch/pytorch#142313]
### 🐛 Describe the bug

The purpose is to use FlexAttention with Compiled DDP
https://github.com/pytorch/pytorch/issues/109774

```python
import torch
from torch.nn.attention.flex_attention import flex_attention


@torch.compile(backend="aot_eager")
def fwd_bwd(x: torch.Tensor):
    flex_attention(x, x, x).sum().backward()


v = torch.zeros(1, 1, 768, 64, dtype=torch.bfloat16, device="cuda", requires_grad=True)
with torch._dynamo.compiled_autograd._enable(torch.compile(backend="aot_eager")):
    fwd_bwd(v)
```

traceback
```
Traceback (most recent call last):
  File "/root/modded-nanogpt/flex_compiled_autograd.py", line 12, in <module>
    fwd_bwd(v)
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 573, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/flex_compiled_autograd.py", line 5, in fwd_bwd
    @torch.compile(backend="aot_eager")
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/autograd/function.py", line 307, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1708, in backward
    return impl_fn()
           ^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1698, in impl_fn
    out = CompiledFunction._backward_impl(ctx, all_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1986, in _backward_impl
    return normalize_as_list(bw_module(*all_args))
                             ^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/fx/graph_module.py", line 822, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/fx/graph_module.py", line 400, in __call__
    raise e
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/fx/graph_module.py", line 387, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<eval_with_key>.6", line 10, in forward
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/flex_attention.py", line 130, in __call__
    return super().__call__(
           ^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_ops.py", line 440, in __call__
    return wrapper()
           ^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 744, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_ops.py", line 436, in wrapper
    return self.dispatch(
           ^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_ops.py", line 302, in dispatch
    return kernel(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/utils.py", line 64, in inner
    return autograd_not_implemented_inner(op, deferred_error, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/utils.py", line 37, in autograd_not_implemented_inner
    result = operator(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/flex_attention.py", line 130, in __call__
    return super().__call__(
           ^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_ops.py", line 440, in __call__
    return wrapper()
           ^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 744, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_ops.py", line 436, in wrapper
    return self.dispatch(
           ^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_ops.py", line 339, in dispatch
    result = handler(mode, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/flex_attention.py", line 1010, in flex_attention_backward_proxy_torch_dispatch_mode
    return trace_flex_attention_backward(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/flex_attention.py", line 943, in trace_flex_attention_backward
    fw_graph = reenter_make_fx(fw_graph)(*fw_example_vals, *score_mod_other_buffers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modded-nanogpt/.venv/lib/python3.12/site-packages/torch/_higher_order_ops/utils.py", line 87, in wrapped
    _CURRENT_MAKE_FX_TRACER is not None
AssertionError: Cannot reenter make_fx when we're not under a make_fx tracing session
```

### Versions

PyTorch version: 2.6.0.dev20241203+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.4
Libc version: glibc-2.35

Python version: 3.12.7 (main, Oct 16 2024, 04:37:19) [Clang 18.1.8 ] (64-bit runtime)
Python platform: Linux-5.4.250-2-velinux1u1-amd64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.6.77
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          168
On-line CPU(s) list:             0-161
Off-line CPU(s) list:            162-167
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8457C
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              42
Socket(s):                       2
Stepping:                        8
BogoMIPS:                        5199.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid cldemote movdiri movdir64b md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3.9 MiB (84 instances)
L1i cache:                       2.6 MiB (84 instances)
L2 cache:                        168 MiB (84 instances)
L3 cache:                        195 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-83
NUMA node1 CPU(s):               84-167
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==2.1.3
[pip3] torch==2.6.0.dev20241203+cu124
[pip3] triton==3.1.0
[conda] Could not collect

cc @chauhang @penguinwu @zou3519 @ydwu4 @xmfan @yf225 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng @fegin

**Comment by xmfan** [comment]
@Chillee torch.ops.higher_order.flex_attention_backward errors if it is run in eager

Compiled autograd is trying to inline the AOT backward by running it in eager with proxied fake tensors (compiled autograd's variant of make_fx)

**Comment by drisspg** [comment]
@xmfan whats the error?

**Comment by xmfan** [comment]
You shouldn't see the error anymore, but there's a graph break happening and flex attention is running in eager under compiled autograd at the moment

**Comment by YouJiacheng** [comment]
"flex attention is running in eager under compiled autograd" does this mean its performance is bad?
