### ISSUE TITLE
[jit] graph differentiation segfaults on a particular graph

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#14255]
## To Reproduce

Short repro code
https://gist.github.com/soumith/68e55c24845ca16770f55409c0230776

Segmentation fault stack-trace:

```
Thread 1 "test_jit" received signal SIGSEGV, Segmentation fault.
0x00007ffff6be10f4 in torch::jit::Node::inBlockList (this=0x0) at ../torch/csrc/jit/ir.h:600
600         if(next() == nullptr) {
(gdb) bt
#0  0x00007ffff6be10f4 in torch::jit::Node::inBlockList (this=0x0) at ../torch/csrc/jit/ir.h:600
#1  0x00007ffff71b5494 in torch::jit::Node::insertAfter (this=0xbcbb60, n=0x0) at ../torch/csrc/jit/ir.cpp:905
#2  0x00007ffff71b668b in torch::jit::Node::moveAfter (this=0xbcbb60, n=0x0) at ../torch/csrc/jit/ir.cpp:1125
#3  0x00007ffff6e89b09 in torch::jit::lambdaLiftReverse (grad_desc=..., rev_info=...) at ../torch/csrc/jit/autodiff.cpp:724
#4  0x00007ffff6e8a113 in torch::jit::differentiate (graph=...) at ../torch/csrc/jit/autodiff.cpp:773
#5  0x0000000000527a41 in torch::jit::(anonymous namespace)::testTHNNConv () at ../test/cpp/jit/tests.h:563
#6  0x000000000054d4fd in JitTest_THNNConv_Test::TestBody (this=0xb47900) at ../test/cpp/jit/gtest.cpp:31
#7  0x0000000000602fe5 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0xb47900, method=&virtual testing::Test::TestBody(), location=0x6232eb "the test body")
    at ../third_party/googletest/googletest/src/gtest.cc:2443
#8  0x00000000005fd889 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0xb47900, method=&virtual testing::Test::TestBody(), location=0x6232eb "the test body")
    at ../third_party/googletest/googletest/src/gtest.cc:2479
#9  0x00000000005dd166 in testing::Test::Run (this=0xb47900) at ../third_party/googletest/googletest/src/gtest.cc:2518
#10 0x00000000005ddaa7 in testing::TestInfo::Run (this=0xb54ff0) at ../third_party/googletest/googletest/src/gtest.cc:2693
#11 0x00000000005de111 in testing::TestCase::Run (this=0xb338f0) at ../third_party/googletest/googletest/src/gtest.cc:2811
#12 0x00000000005e9110 in testing::internal::UnitTestImpl::RunAllTests (this=0xb56d30) at ../third_party/googletest/googletest/src/gtest.cc:5177
#13 0x0000000000603f1b in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xb56d30,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x5e8e70 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x623ca0 "auxiliary test code (environments or event listeners)")
    at ../third_party/googletest/googletest/src/gtest.cc:2443
#14 0x00000000005fe63b in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xb56d30,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x5e8e70 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x623ca0 "auxiliary test code (environments or event listeners)")
    at ../third_party/googletest/googletest/src/gtest.cc:2479
#15 0x00000000005e7b98 in testing::UnitTest::Run (this=0x89b880 <testing::UnitTest::GetInstance()::instance>) at ../third_party/googletest/googletest/src/gtest.cc:4786
#16 0x000000000051b59a in RUN_ALL_TESTS () at ../cmake/../third_party/googletest/googletest/include/gtest/gtest.h:2341
#17 0x000000000051b496 in main (argc=1, argv=0x7fffffffda78) at ../test/cpp/common/main.cpp:31
```

**Comment by driazati** [comment]
Closing since this works on master
