### ISSUE TITLE
[jit trace] CUDA fusion unknown error

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#14263]
```
Traceback (most recent call last):
  File ".../miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 468, in run_mod_and_filter_tens
or_outputs
    outs = wrap_retval(mod(*_clone_inputs(inputs)))
  File ".../miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File ".../miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1270, in forward
    return self._get_method('forward')(*args, **kwargs)
RuntimeError: ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:137: unknown error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 478, in <module>
    main()
  ...
  ... = torch.jit.trace(traced, sample_inp)
  File ".../miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 604, in trace
    _check_trace([example_inputs], func, executor_options, module, check_tolerance)
  File ".../miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File ".../miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 505, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(module, inputs, 'trace')
  File ".../miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 474, in run_mod_and_filter_tens
or_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
        ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:137: unknown error
```

Model: LeNet from torch/example with dropout removed
GPU: Titan Xp
CUDA: 9.1.85

**Comment by gottbrath** [comment]
we think this is likely not to be an issue any more. SsnL or other folks reading this. If you can still reproduce this with a recent version of PyTorch please let us know.
