### ISSUE TITLE
test_custom_scan_op regression

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#143053]
### 🐛 Describe the bug

We are skipping scan_op_compiled ever since https://github.com/pytorch/pytorch/pull/138363 because of dynamic shapes. Even with `@torch._dynamo.config.patch({"dynamic_shapes": False, "assume_static_by_default": False})` patched, the test fails.

```
ERROR: test_custom_scan_op_cuda (__main__.GPUTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/eellison/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 55, in graph_break_as_hard_error
    return fn(*args, **kwargs)
  File "/data/users/eellison/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 1234, in call_function
    unimplemented(
  File "/data/users/eellison/pytorch/torch/_dynamo/exc.py", line 317, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: Combine fn had unexpected freevars: {Proxy(s1): Proxy(s1)}
...
  File "/data/users/eellison/pytorch/torch/_dynamo/symbolic_convert.py", line 898, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/data/users/eellison/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 58, in graph_break_as_hard_error
    raise UncapturedHigherOrderOpError(reason + msg) from e
torch._dynamo.exc.UncapturedHigherOrderOpError: associative_scan must be captured completely with torch.compile. Scroll up to find out what causes the graph break.
```

If we have to force static shapes, we can do that, but the test should not break.

cc @chauhang @penguinwu @ezyang @bobrenjc93 @zou3519 @ydwu4 @bdhirsh @yf225 @gchanan @kadeng @msaroufim 

### Versions

master

**Comment by zou3519** [comment]
cc @ydwu4

**Comment by eellison** [comment]
@ezyang it fails even without dynamic shapes.

**Comment by ydwu4** [comment]
> it fails even without dynamic shapes.

hm... this is weird, there shouldn't be dynamic symbols if we're not running with dynamic. The following doesn't repro for me (I copied from the test case):
```python
import torch

def sum_combine(a, b):
    return a + b

from torch._higher_order_ops.associative_scan import associative_scan

a = torch.randn(100, 100, device=torch.device("cuda"))
expect = torch.cumsum(a, 0)
actual = associative_scan(sum_combine, a, 0)

def logcumsum_combine(a, b):
    min_v = torch.minimum(a, b)
    max_v = torch.maximum(a, b)
    mask = (min_v != max_v) | ~min_v.isinf()
    return torch.where(mask, max_v + (min_v - max_v).exp().log1p(), a)

expect = torch.logcumsumexp(a, 0)
actual = associative_scan(logcumsum_combine, a, 0)
print(expect, actual)
```
How can i repro this?

**Comment by eellison** [comment]
Okay, sorry, nevermind it is in fact the dynamic shapes that cause this to fail. 
```
    @skipCUDAIf(TEST_WITH_ROCM, "associative_scan is not supported on ROCm")
    @skip_if_halide  # scan ops
    @torch._dynamo.config.patch({"dynamic_shapes": False, "assume_static_by_default": False})
    def test_custom_scan_op(self):
```
fails while

```
    @skip_if_halide  # scan ops
    @torch._dynamo.config.patch({"dynamic_shapes": False, "assume_static_by_default": True})
    def test_custom_scan_op(self):
```

succeeds. could we add back at least the static variant in the CI, because right now it is always being skipped.

**Comment by ydwu4** [comment]
Sure! here: https://github.com/pytorch/pytorch/pull/143161
