### ISSUE TITLE
Thread deadlock problem on Dataloader

### ISSUE THREAD

**Issue by LoganZhou** [pytorch/pytorch#14307]
## Thread deadlock problem on Dataloader

Hey guys! 

Currently, I try to train distributed model, but the dataloader seems to have a thread deadlock problem on master process while other slave processes reading data well. `TripletPDRDataset` tries to return 3 images in the function `__getitem()__`, including an anchor, a positive sample and a negative sample. I found that it can work well if don't use distributed sampler.

Best, 

Heng Zhou

## To Reproduce

1. Run the following command on master node:
```shell
python -u test_dataset.py --world-size=2 --dist-url=tcp://10.10.10.1:23456 --dist-backend=nccl --global-rank=0
```
2. Run the following command on slave node:
```shell
python -u test_dataset.py --world-size=2 --dist-url=tcp://10.10.10.1:23456 --dist-backend=nccl --global-rank=1
```

### Code sample
**PDR_Dataset .py**

```python
import os
import numpy as np
from torch.utils import data
from torch.utils.data.sampler import BatchSampler
from PIL import Image
import torchvision.transforms as transforms
import json

class TripletPDRDataset(data.Dataset):
    def __init__(self, images_dir, labels_path, transforms, train):
        self.train = train
        with open(labels_path, 'r') as f:
            examples = json.loads(f.read())
        self.images_dir = images_dir
        self.transforms = transforms
        self.labels = []
        self.image_ids = []
        for example in examples:
            self.image_ids.append(example["image_id"])
            self.labels.append(example["disease_class"])
        self.labels_set = set(self.labels)

        self.label_to_indices = {
            label: np.where(np.array(self.labels) == label)[0] for label in self.labels_set
        }

        if not self.train:
            # generate fixed triplets for testing
            random_state = np.random.RandomState(29)

            triplets = [[i,
                         random_state.choice(self.label_to_indices[self.labels[i]]),
                         random_state.choice(self.label_to_indices[
                                                 np.random.choice(
                                                     list(self.labels_set - {self.labels[i]})
                                                 )
                                             ])
                         ]
                        for i in range(len(self.image_ids))]
            self.test_triplets = triplets

    def __getitem__(self, index):
        if self.train:
            img1_id, label1 = self.image_ids[index], self.labels[index]
            positive_index = index
            while positive_index == index:
                positive_index = np.random.choice(self.label_to_indices[label1])
            negative_label = np.random.choice(list(self.labels_set - {label1}))
            negative_index = np.random.choice(self.label_to_indices[negative_label])
            img2_id = self.image_ids[positive_index]
            img3_id = self.image_ids[negative_index]
        else:
            img1_id = self.image_ids[self.test_triplets[index][0]]
            img2_id = self.image_ids[self.test_triplets[index][1]]
            img3_id = self.image_ids[self.test_triplets[index][2]]

        img1 = Image.open(os.path.join(self.images_dir, img1_id))
        img2 = Image.open(os.path.join(self.images_dir, img2_id))
        img3 = Image.open(os.path.join(self.images_dir, img3_id))
        if self.transforms is not None:
            img1 = self.transforms(img1)
            img2 = self.transforms(img2)
            img3 = self.transforms(img3)
        return (img1, img2, img3), []

    def __len__(self):
        return len(self.image_ids)
```

**test_dataset.py**

```python
# coding:utf-8
import torch
import argparse
import torchvision.transforms as transforms
import torch.utils.data.distributed
import torch.distributed as dist
import torch.utils.data
from PDR_Dataset import *

parser = argparse.ArgumentParser(description='PyTorch DataLoader Test')
parser.add_argument('--world-size', default=1, type=int,
                    help='number of distributed processes')
parser.add_argument('--dist-url', default='env://', type=str,
                    help='url used to set up distributed training')
parser.add_argument('--global-rank', default=0, type=int,
                    help='process rank of global process group')
parser.add_argument('--dist-backend', default='nccl', type=str,
                    help='distributed backend')

args = parser.parse_args()

dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
                        world_size=args.world_size, rank=args.global_rank)
print("=> Distributed: success (%d/%d)!" % (dist.get_rank() + 1, dist.get_world_size()))


traindir = os.path.join(r"/home/asc001/AI_Challenger/PDR2018/data/trainingset/images")
trainlabel = os.path.join(r"/home/asc001/AI_Challenger/PDR2018/data/trainingset/AgriculturalDisease_train_annotations.json")


train_dataset = TripletPDRDataset(
        traindir, trainlabel, transforms.Compose([
            transforms.RandomResizedCrop(331, scale=(0.5, 1.0)),
            transforms.RandomRotation(degrees=(0, 360)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225]), ]), train=True)

train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)

triplet_train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=4, shuffle=(train_sampler is None),
        num_workers=2, pin_memory=True, sampler=train_sampler)

for batch_idx, (data, target) in enumerate(triplet_train_loader):
    message = 'Train: [{}/{} ({:.0f}%)]'.format(
        batch_idx * len(data[0]), len(triplet_train_loader),
        100. * batch_idx / len(triplet_train_loader))
    print(message)
```

### stack traces

```shell
Traceback (most recent call last):
  File "test_dataset.py", line 49, in <module>
    for batch_idx, (data, target) in enumerate(triplet_train_loader):
  File "/home/asc001/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/home/asc001/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 601, in _get_batch
    return self.data_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/asc001/anaconda3/envs/pytorch/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/asc001/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

## Expected behavior

The progress of distributed process outputs may look like the same, but the master process stuck while running. 

```
master
...
Train: [1180/3965 (7%)]
Train: [1184/3965 (7%)]
Train: [1188/3965 (7%)]
Train: [1192/3965 (8%)]
Train: [1196/3965 (8%)]    <== stuck here
```

```
slave
...
Train: [6248/3965 (39%)]
Train: [6252/3965 (39%)]
Train: [6256/3965 (39%)]
Train: [6260/3965 (39%)] 
```

## Environment

PyTorch version: 1.0.0a0+86e1009
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: CentOS Linux release 7.3.1611 (Core) 
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 396.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.0.0a0+86e1009           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

## Additional context
[Here is the validation dataset](https://drive.google.com/file/d/1rzJ3Qt_y_VNSLWH5U8R6Et1OJ5_IEgUS/view?usp=sharing), you can download it for testing.

**Comment by LoganZhou** [comment]
I have found that the data lenght of specific label may be just one which would cause an endless loop in `TripletPDRDataset` . So I added the following statements:
```python
while positive_index == index:
    if len(self.label_to_indices[label1]) <= 1:
        break
    positive_index = np.random.choice(self.label_to_indices[label1])
```
