### ISSUE TITLE
RuntimeError: 2D or 4D weight tensor expected,

### ISSUE THREAD

**Issue by youssefoumate** [pytorch/pytorch#1431]
Hello Sir,
In my project I'm trying to use 3D convloutional networks 
on some video frames, but when I perform a forward propagation, the program 
shows this error:
```
Traceback (most recent call last):
  File "C3D_training.py", line 309, in <module>
    main()
  File "C3D_training.py", line 152, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "C3D_training.py", line 187, in train
    output = model.forward(input_var)
  File "C3D_training.py", line 41, in forward
    x = F.relu(self.conv1a(x))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 330, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 88, in conv3d
    return f(input, weight, bias)
RuntimeError: 2D or 4D weight tensor expected, but got: [64 x 3 x 3 x 3 x 3] at /py/conda-bld/pytorch_1490903321756/work/torch/lib/THNN/generic/SpatialConvolutionMM.c:15

```
I don't know exactly what is the origin of this error,
and what it means ?
any help will be appreciated.
Thank you,

**Comment by soumith** [comment]
https://discuss.pytorch.org
