### ISSUE TITLE
Recently enabled to ARM CI test_mkldnn_pattern_matcher.py fails on Graviton3

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#143146]
### 🐛 Describe the bug

When running bf16 convs or linear using channel last test_mkldnn_pattern_matcher.py (that was enabled by  https://github.com/pytorch/pytorch/pull/141921 ) fails numerous expected vs traced mismatches.
Namely:
 - TestPatternMatcher.test_conv2d_binary
```
$ python inductor/test_mkldnn_pattern_matcher.py TestPatternMatcher.test_conv2d_binary

Running tests...
----------------------------------------------------------------------
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:157: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=torch.bfloat16)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_config_module.py:342: UserWarning: Skipping serialization of skipfiles_inline_module_allowlist value {}
  warnings.warn(
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:106: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=dtype)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_config_module.py:342: UserWarning: Skipping serialization of skipfiles_inline_module_allowlist value {}
  warnings.warn(
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:157: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=torch.bfloat16)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_config_module.py:342: UserWarning: Skipping serialization of skipfiles_inline_module_allowlist value {}
  warnings.warn(
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:106: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=dtype)
frames [('total', 1), ('ok', 1)]
inline_call []
stats [('calls_captured', 4), ('unique_graphs', 1)]
aot_autograd [('total', 1), ('autograd_cache_bypass', 1), ('ok', 1)]
inductor [('extern_calls', 4), ('mkldnn_conv_weight_pack_matcher_count', 2), ('mkldnn_conv_weight_pack_matcher_nodes', 2), ('pattern_matcher_count', 2), ('pattern_matcher_nodes', 2), ('fxgraph_cache_bypass', 1)]
F
======================================================================
FAIL [11.465s]: test_conv2d_binary (__main__.TestPatternMatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3108, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_quantization.py", line 417, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_quantization.py", line 369, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1846, in wrapper
    return fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py", line 671, in test_conv2d_binary
    self._test_conv_binary_base(dim=4)
  File "/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py", line 665, in _test_conv_binary_base
    self.assertEqual(metrics.generated_kernel_count, generated_kernel_count)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4016, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Scalars are not equal!

Expected 1 but got 2.
Absolute difference: 1
Relative difference: 1.0

To execute this test, run the following from the base repo dir:
    python test/inductor/test_mkldnn_pattern_matcher.py TestPatternMatcher.test_conv2d_binary

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 11.465s

FAILED (failures=1)

Generating XML reports...

```

- TestPatternMatcher.test_conv3d_unary_cpu
```
$ python test_mkldnn_pattern_matcher.py TestPatternMatcher.test_conv3d_unary_cpu

Running tests...
----------------------------------------------------------------------
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:157: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=torch.bfloat16)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_config_module.py:342: UserWarning: Skipping serialization of skipfiles_inline_module_allowlist value {}
  warnings.warn(
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:106: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=dtype)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_config_module.py:342: UserWarning: Skipping serialization of skipfiles_inline_module_allowlist value {}
  warnings.warn(
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:157: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=torch.bfloat16)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_config_module.py:342: UserWarning: Skipping serialization of skipfiles_inline_module_allowlist value {}
  warnings.warn(
/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py:106: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  maybe_autocast = torch.cpu.amp.autocast(dtype=dtype)
frames [('total', 1), ('ok', 1)]
inline_call []
stats [('calls_captured', 2), ('unique_graphs', 1)]
aot_autograd [('total', 1), ('autograd_cache_bypass', 1), ('ok', 1)]
inductor [('extern_calls', 2), ('mkldnn_conv_weight_pack_matcher_count', 1), ('mkldnn_conv_weight_pack_matcher_nodes', 1), ('pattern_matcher_count', 1), ('pattern_matcher_nodes', 1), ('fxgraph_cache_bypass', 1)]
F
======================================================================
FAIL [10.837s]: test_conv3d_unary_cpu (__main__.TestPatternMatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3108, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_quantization.py", line 417, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_quantization.py", line 369, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1846, in wrapper
    return fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py", line 313, in test_conv3d_unary_cpu
    self._test_conv_unary_cpu_base(dim=5)
  File "/var/lib/jenkins/workspace/test/inductor/test_mkldnn_pattern_matcher.py", line 301, in _test_conv_unary_cpu_base
    self.assertEqual(metrics.generated_kernel_count, generated_kernel_count)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4016, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Scalars are not equal!

Expected 1 but got 2.
Absolute difference: 1
Relative difference: 1.0

To execute this test, run the following from the base repo dir:
    python test/inductor/test_mkldnn_pattern_matcher.py TestPatternMatcher.test_conv3d_unary_cpu

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 10.837s

FAILED (failures=1)
```
- TestPatternMatcher.test_linear_add_bias
- TestPatternMatcher.test_linear_unary

### Versions

CI

cc @mruberry @ZainRizvi @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @milpuz01

**Comment by malfet** [comment]
@Mousius do you mind having a look at it?
