### ISSUE TITLE
Race condition in FileTimerServerTest in test/distributed/elastic/timer/file_based_local_timer_test.py

### ISSUE THREAD

**Issue by cdzhan** [pytorch/pytorch#143188]
### 🐛 Describe the bug

Possible root cause: The watchdog in server might open the named pipe later than the client opens the pipe in non-blocking mode.

```bash

[2024-12-10T17:32:15.692Z] =================================== FAILURES ===================================

[2024-12-10T17:32:15.692Z] _________________ FileTimerServerTest.test_watchdog_call_count _________________

[2024-12-10T17:32:15.692Z] Traceback (most recent call last):

[2024-12-10T17:32:15.692Z]   File "/opt/py3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor

[2024-12-10T17:32:15.692Z]     yield

[2024-12-10T17:32:15.692Z]   File "/opt/py3.10/lib/python3.10/unittest/case.py", line 591, in run

[2024-12-10T17:32:15.692Z]     self._callTestMethod(testMethod)

[2024-12-10T17:32:15.692Z]   File "/opt/py3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod

[2024-12-10T17:32:15.692Z]     method()

[2024-12-10T17:32:15.692Z]   File "/home/jenkins/agent/workspace/Pytorch/Gitlab_trigger_torch_mlu/venv/pytorch/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3099, in wrapper

[2024-12-10T17:32:15.692Z]     method(*args, **kwargs)

[2024-12-10T17:32:15.692Z]   File "/home/jenkins/agent/workspace/Pytorch/Gitlab_trigger_torch_mlu/pytorch/test/distributed/elastic/timer/file_based_local_timer_test.py", line 227, in test_watchdog_call_count

[2024-12-10T17:32:15.692Z]     client._send_request(self._valid_timer(pid=test_pid, scope="test0"))

[2024-12-10T17:32:15.692Z]   File "/home/jenkins/agent/workspace/Pytorch/Gitlab_trigger_torch_mlu/venv/pytorch/lib/python3.10/site-packages/torch/distributed/elastic/timer/file_based_local_timer.py", line 116, in _send_request

[2024-12-10T17:32:15.692Z]     raise BrokenPipeError(

[2024-12-10T17:32:15.692Z] BrokenPipeError: Could not send the FileTimerRequest because FileTimerServer is not available.

[2024-12-10T17:32:15.692Z] 

[2024-12-10T17:32:15.692Z] To execute this test, run the following from the base repo dir:

[2024-12-10T17:32:15.692Z]     python test/distributed/elastic/timer/file_based_local_timer_test.py FileTimerServerTest.test_watchdog_call_count
```
### Versions

main

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @mruberry @ZainRizvi

**Comment by d4l3k** [comment]
I'm looking into it

**Comment by d4l3k** [comment]
Managed to repro the issue

```sh
pytest --minutes 10 test/distributed/elastic/timer/file_based_local_timer_test.py -k test_watchdog_call_count -s -x
```
