### ISSUE TITLE
Error in DTensor uneven shard view op

### ISSUE THREAD

**Issue by guo-ran** [pytorch/pytorch#143372]
### 🐛 Describe the bug

**Description**: 
There seems to be an issue when reshaping/viewing an unevenly sharded DTensor.

**Code to Reproduce:**
torchrun --nproc_per_node=4 test.py
In this test case has 512 elements on ranks 0-2 and 0 elements on rank 3. The error occurs during the view operation.
```
import torch
from torch.distributed._tensor import Replicate, Shard, distribute_tensor, DTensor
from torch.distributed.device_mesh import init_device_mesh
from datetime import timedelta
import torch.nn as nn

new_mesh = init_device_mesh("cuda", [4], mesh_dim_names=["tp"])
x=torch.randn((6,256),dtype=torch.float32,device="cuda")

def a(x):
    d_x = DTensor.from_local(x, device_mesh=new_mesh, placements=[Replicate()])
    d_x = d_x.redistribute(device_mesh=new_mesh, placements=[Shard(dim=0)]) 
    d_x = d_x.view(-1)
    return d_x

out=a(x)
```

**Error log:**
For ranks 0-2:
```
[rank0]:   File "/opt/tiger/test.py", line 13, in a
[rank0]:     d_x = d_x.view(-1)
[rank0]:           ^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.11/dist-packages/torch/_compile.py", line 31, in inner
[rank0]:     return disable_fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.11/dist-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.11/dist-packages/torch/distributed/_tensor/api.py", line 309, in __torch_dispatch__
[rank0]:     return DTensor._op_dispatcher.dispatch(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.11/dist-packages/torch/distributed/_tensor/_dispatch.py", line 205, in dispatch
[rank0]:     local_results = op_call(*local_tensor_args, **op_info.local_kwargs)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.11/dist-packages/torch/_ops.py", line 667, in __call__
[rank0]:     return self_._op(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: shape '[384]' is invalid for input of size 512
```
For rank 3:
```
RuntimeError: shape '[384]' is invalid for input of size 0
```

### Versions

🐛 Describe the bug
Please provide a clear and concise description of what the bug is.

If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:

# All necessary imports at the beginning
import torch

# A succinct reproducing example trimmed down to the essential parts:
t = torch.rand(5, 10)  # Note: the bug is here, we should pass requires_grad=True
t.sum().backward()
If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com/.

Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the full traceback of the exception. It may be relevant to wrap error messages in ```triple quotes blocks```.

```python
# Sample code to reproduce the problem
```

```
The error message you got, with the full traceback.
```
Versions
Please run the following and paste the output below.

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by fegin** [comment]
cc., @XilunWu

**Comment by XilunWu** [comment]
The problem is DTensor assumes the sharding will be even on the result DTensor. So far I don't have a clear picture of how to fix but let me think...

**Comment by awgu** [comment]
@XilunWu It seems to me that for uneven sharding for `d_x: (Shard(0),)`, we have to redistribute to replicated before sharding again on dim-0. Otherwise, the sharding placement is not well-formed.

**Comment by wconstab** [comment]
1. I confirmed that @awgu's suggestion literally works today, as a starting point: 
```
    d_x = DTensor.from_local(x, device_mesh=new_mesh, placements=[Replicate()])  # shape is (6, 256)
    d_x = d_x.view(-1)  # shape is (1536,)
    d_x = d_x.redistribute(device_mesh=new_mesh, placements=[Shard(dim=0)])  # shape is (384, )
```

2. In the OP example, should we expect the view() operator to perform a redistribution automatically?
Pro: it works as expected (semantically)
Con: view ops are normally 'lightweight' in pytorch, e.g. they try to avoid even making a local memory copy.  Redistribute, otoh, is very expensive in comparison.

3. Or, should we define the view() op such that it cheaply manipulates metadata but leaves the tensor data where it is?  This means that at least we defer the actual redistribute call until some later time when an op needs to access the data locally.

It feels like we need to answer (2) and (3) in the broader context of "defining the behavior / semantics of DTensor view ops".  I'm not inclined to make a behavior change on this issue until I have a more clear sense of the design for DTensor views.

**Comment by XilunWu** [comment]
@wconstab I agree that we should try avoiding redistribution in `view()`. The root cause is the `size` argument passed to `view()` was computed without considering uneven sharding. One way is we manually fix the `size` in DTensor dispatch.

**Comment by wconstab** [comment]
I don't think we fully discussed this version though?

> (3) Or, should we define the view() op such that it cheaply manipulates metadata but leaves the tensor data where it is? This means that at least we defer the actual redistribute call until some later time when an op needs to access the data locally.

We could define dist_y as always being a lightweight metadata change with no change to underlying local_shard data.  Some implications of this would be:
- if we compute on a view (or print a view), it might force a just-in-time redistribute
- creating a view never modifies the original tensor (dist_x would always behave as usual)

We could take inspiration from memory contiguity/stride behavior in single-gpu torch.  Example:

```
>>> x = torch.arange(10).reshape(2,5)
>>> x.stride()
(5, 1)

# transpose is a fast view op, but returns a non-contiguous tensor. 
>>> y = x.t()
>>> y.stride()
(1, 5)

# you aren't allowed to take a view of a non-contiguous tensor
>>> y.view(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

# demanding a contiguous tensor requires making a copy, but never changes the original tensor
>>> z = y.contiguous()
>>> z.stride()
(2, 1)
>>> x.stride()
(5, 1)

# and you're free to take a view on z since its explicitly a contiguous copy
>>> z.view(-1)
tensor([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])
```

**Comment by wconstab** [comment]
> dist_y = dist_x.view(-1)  # now it would fail. Fixing sharding prop should enable this.

i'll be happy to take a look at this part. Can you give me some code pointers?

**Comment by tianyu-l** [comment]
@wconstab 
IMO we should never allow redistribute on `view`. We should just error out in such cases.

> for pointwise ops, we could probably compute on the view by modifying the ._local_shard and preserving the metadata.

For pointwise ops, do users have to do `view` before performing the pointwise ops anyway?

**Comment by wconstab** [comment]
Pardon the long form post, but @XilunWu and I did some offline discussion and it's worth capturing the discussion points here.

1) Legal sharding rule

We discussed at length a question about which DTensor sharding specs were 'legal' and what implications that has for the stack.  A conclusion that I'm not sure is well documented but seems to be a design assumption is this:

"Uneven sharding of a DTensor is only legal if the global shape + sharding requires it".  

Reasons for this rule:
- distributed checkpointing makes assumptions based on global shape/sharding following this rule, impacting where it looks for data in shard files
- dtensor dispatch ignores the complexity that would be necessary if we supported operations on 'illegal views'

Example of difficulty with illegal sharding:
```
x=torch.randn((6,256),dtype=torch.float32,device="cuda")
d_x = DTensor.from_local(x, device_mesh=new_mesh, placements=[Replicate()])
d_x_shard = d_x.redistribute(device_mesh=new_mesh, placements=[Shard(dim=0)])
d_x_shard_view = d_x_shard.view(-1)

# now, logically d_x_shard_view should have shape (1536,) and per-rank local shapes (512,) (512,) (512,) (0,)
# but what if we want to use this view? 

# this line is ambiguous currently. Dispatcher would assume that becuase both tensors have the same 'sharding' and global shape, its safe to just add the local tensors.  But you'd be adding tensors of wrong shapes.  This operation would require a redistribution, _and_ this is not clearly captured in the sharding metadata. 
y = d_x_shard_view +  DTensor.from_local(torch.randn(384,), placements=[Shard(dim=0)])
```

So as it stands today, the view(-1) op in this PR is "illegal".

2) Banning illegal views

Assuming we agree with point (1) and we want to make some changes to make this case clearer for users, what options do we have?

A) illegal views cannot be created- you get an explicit error saying why they are illegal and pointing to the docs with the rules spelled out
B) illegal views can be created, but you can do almost nothing with them- most operations on them explicitly error out.  Perhaps this is more useful than (A) if folks want to print them or poke at them in some way, but I think its more likely just worse than (A)
C) we perform redistribute() silently when creating such a view, so the resulting view is legally sharded.  This has several downsides, first being an unexpected performance hit, second being a deviation from torch's view operator semantics of never making a copy.

**Comment by wanchaol** [comment]
As @tianyu-l suggested, we should never allow redistribute on `view` related operation, or inplace operations. We should just error out in such cases. If it currently does not error out today in any of these cases, it is a bug we should fix.
