### ISSUE TITLE
CUDA OOM error when inferencing with SwinTransformer ExportedProgram

### ISSUE THREAD

**Issue by rbavery** [pytorch/pytorch#143346]
### 🐛 Describe the bug

I have a SWIN Transformer model that I was successfully exporting and inferencing with torch 2.3.0 using `torch._export.aot_compile` but that is now failing to inference with torch 2.5.1.  With torch `2.3.0` and the `aot_compile` method I was able to inference with a batch size of 10. When I try to upgrade from torch 2.3.0 to torch 2.5 and use the new `torch.export.export` and `torch.export.load`, I run into at least two, possibly related issues.

There's no error during torch.export. Both strict and non strict work. I've attached a trace from TORCH_TRACE for the export/compile step.

[dedicated_log_torch_trace_6zqra37l.log](https://github.com/user-attachments/files/18158386/dedicated_log_torch_trace_6zqra37l.log)

The first issue is an error when logging in a `deserialiaze_sym_int` method, when I load the model that successfully exported with `torch.export.load`. There's also a lot of warnings about:

```
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph.py:1586: UserWarning: Node backbone_backbone_backbone_features_1_1_attn_lifted_tensor_4 target backbone.backbone.backbone.features.1.1.attn.lifted_tensor_4 lifted_tensor_4 of backbone.backbone.backbone.features.1.1.attn does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(f'Node {node} target {node.target} {atom} of {seen_qualname} does '
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph.py:1593: UserWarning: Additional 428 warnings suppressed about get_attr references
  warnings.warn(

```

The next is that when inference runs on a tensor with size `[1, 36, 1024, 0124]`, I get a CUDA OOM. This is surprising since when I previously exported the model with `torch._export.aot_compile`, I could run inference on a tensor with size `[10, 36, 1024, 1024]`.

Here is how I used to export the model as a CUDA shared lib with .cubin and .so files

```python
import json
import numpy as np
import torch
import tqdm
import sys
import os

sys.path.append("./satlas")
import satlas.model.evaluate
import satlas.model.model
import os

torch.set_float32_matmul_precision("high")
# os.environ["TORCH_LOGS"] = "+dynamic"
weights_path = "/home/finetuned_satlas_explorer_sentinel2_solar_farm.pth"
config_path = "./satlas/configs/satlas_explorer_solar_farm.txt"
# the result path must be unique to disambiguate between different aot_compile models
output_directory = "aot_inductor_model"
size = 1024

with open(config_path, "r") as f:
    config = json.load(f)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
for spec in config["Tasks"]:
    if "Task" not in spec:
        spec["Task"] = satlas.model.dataset.tasks[spec["Name"]]
model = satlas.model.model.Model(
    {
        "config": config["Model"],
        "channels": config["Channels"],
        "tasks": config["Tasks"],
    }
)

device = "cuda"
state_dict = torch.load(weights_path, map_location=device)
model.load_state_dict(state_dict)
model.to(device)
model.eval()
bs_min = 2
with torch.no_grad():
    test_im_ts = torch.randn((9 * 4, size, size)).to(device)
    x = torch.stack([test_im_ts] * bs_min, dim=0)
    outputs, _ = model(x)

os.makedirs(output_directory, exist_ok=True)
model_path = os.path.join(
    os.getcwd(), output_directory, "solar_satlas_sentinel2_model_pt2.so"
)
# model should be 4 image time series 9 bands each
batch_dim = torch.export.Dim("batch", min=bs_min, max=13)
channel_dim = torch.export.Dim("channel")
height_dim = torch.export.Dim("height")
width_dim = torch.export.Dim("width")

if not os.path.exists(model_path):
    so_path = torch._export.aot_compile(
        f=model,
        args=(x,),
        # Specify the first dimension of the input x as dynamic
        dynamic_shapes={"batch_tensor": {0: batch_dim}},
        # Specify the generated shared library path
        options={
            "aot_inductor.output_path": model_path,
            "max_autotune": True,
        },
    )
```

And here is how I now export the model

```python
import json
import torch
from torch.export import Dim
import os
from huggingface_hub import hf_hub_download

import satlas.model.evaluate
import satlas.model.model
torch._logging.set_logs(all=0)

full_path = os.path.dirname(os.path.abspath(__file__))

torch.set_float32_matmul_precision("high")
# os.environ["TORCH_LOGS"] = "+dynamic"
config_path = f"{full_path}/src/configs/satlas_explorer_solar_farm.txt"
size = 1024

with open(config_path, "r") as f:
    config = json.load(f)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
for spec in config["Tasks"]:
    if "Task" not in spec:
        spec["Task"] = satlas.model.dataset.tasks[spec["Name"]]
model = satlas.model.model.Model(
    {
        "config": config["Model"],
        "channels": config["Channels"],
        "tasks": config["Tasks"],
    }
)


def export_to_torchep(model, name, img_size=1024, save_dir='./compiled'):
    "Save the model to pytorch ExportedProgram format."
    bs_min = 2
    dummy_batch =  torch.randn(bs_min, 9*4, img_size, img_size).to("cuda")

    # dynamic shapes for model export
    batch_size = Dim("batch", min=2, max=20)
    #height = Dim("height", min=2, max=2048)
    #width = Dim("width", min=2, max=2048)
    dynamic_shapes = {
        "batch_tensor": {0: batch_size},
    }

    # Export the model to pytorch ExportedProgram format
    with torch.no_grad():
        ep = torch.export.export(
            model.eval(),
            (dummy_batch,),
            dynamic_shapes=dynamic_shapes,
            strict=True,
        )
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    # Save the exported model
    torch.export.save(ep, f"./{save_dir}/{name}")
    print(
        f"Model exported to pytorch ExportedProgram format: {os.path.abspath(save_dir)}/{name}"  # noqa: E501
    )

    return ep

device = "cuda"

print(f"Downloading from Hugging Face Hub or loading from local dir...")
try:
    # Provide the repository ID and filename on the Hub
    weights_path = hf_hub_download(
        repo_id="allenai/satlas-pretrain",
        subfolder="finetuned_satlas_explorer_models_2023-07-24",
        filename="finetuned_satlas_explorer_sentinel2_solar_farm.pth",
        local_dir=full_path,
        revision='5f6eff89d0675b7601bbe8c8d68956163ae07dd0'
    )
    print(f"Weights downloaded to: {weights_path}")
except Exception as e:  # Catch potential download errors
    print(f"Error downloading weights: {e}")

state_dict = torch.load(weights_path, map_location=device, weights_only=True)
model.load_state_dict(state_dict)
model.to(device)
print("Exporting model")
export_to_torchep(model, "satlas_solar_1024_exported.pt2")

```

Here is how I used to run inference

```python
def load_and_test_model():
    import torch

    model_path = "aot_inductor_model/satlas_pt2.so"
    pt2_model = torch._export.aot_load(model_path, "cuda")
    if torch.cuda.is_available() and torch.cuda.current_device() is not None:
        device = torch.device("cuda" + ":" + str(torch.cuda.current_device()))
        torch.cuda.set_device(device)
    else:
        raise Exception("needs to have cuda available")
    test_im_ts = torch.randn((9 * 4, 256, 256)).to(device)
    x = torch.stack(6 * [test_im_ts], dim=0)
    outputs_aot, _ = pt2_model(x)
    assert outputs_aot.shape == (1, 1, 256, 256)
```

and how I now run inference. I had to add `.module()` which I didn't used to have to do but I got an error when it was not present.

```
RuntimeError: Unable to call ExportedProgram directly. You should use `exported_program.module()` instead.
```

```python
def test_inference():
    import torch
    import os
    full_path = os.path.dirname(os.path.abspath(__file__))
    model_path = f"{full_path}/../../../compiled/satlas_solar_1024_exported.pt2"
    pt2_model = torch.export.load(model_path).module()
    test_img_ts = torch.randn((1, 9 * 4, 1024, 1024)).to(device)
    outputs, _ = pt2_model(test_img_ts)
    assert outputs.shape == (1, 1, 1024, 1024)
```

### Error logs

Full Traceback for the 1st issue with loading the model

```
→ uv run --group torchgpu --group satlas-solar python model-forge/satlas/solar/test.py
V1216 15:56:12.588000 222606 torch/fx/experimental/symbolic_shapes.py:2498] create_env
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588] add_var_to_val s0 2
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588] Stack (most recent call last):
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/model-forge/satlas/solar/test.py", line 16, in <module>
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     test_inference()
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/model-forge/satlas/solar/test.py", line 6, in test_inference
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     pt2_model = torch.export.load(model_path).module()
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/export/__init__.py", line 473, in load
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     ep = deserialize(artifact, expected_opset_version)
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 2437, in deserialize
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     .deserialize(
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 2316, in deserialize
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     .deserialize(
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 1906, in deserialize
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     self.deserialize_graph(serialized_graph_module.graph)
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 1612, in deserialize_graph
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     meta_val = self.deserialize_tensor_meta(tensor_value)
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 1580, in deserialize_tensor_meta
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     tuple(self.deserialize_sym_int(val) for val in tensor_meta.sizes),  # type: ignore[misc]
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 1580, in <genexpr>
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     tuple(self.deserialize_sym_int(val) for val in tensor_meta.sizes),  # type: ignore[misc]
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 1517, in deserialize_sym_int
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     self.shape_env.add_var_to_val(sym, hint)
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]   File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 3588, in add_var_to_val
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:3588]     log.debug("add_var_to_val %s %s", expr, val, stack_info=True)
V1216 15:56:13.479000 222606 torch/fx/experimental/symbolic_shapes.py:4727] _update_var_to_range s0 = VR[2, 20] (new)
I1216 15:56:13.480000 222606 torch/fx/experimental/symbolic_shapes.py:5481] constrain_symbol_range s0 [2, 20]
V1216 15:56:13.502000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval s0 >= 0 == True [statically known]
V1216 15:56:13.504000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval Eq(s0, 0) == False [statically known]
V1216 15:56:13.527000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 1024*s0 >= 0 == True [statically known]
V1216 15:56:13.528000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval Eq(1024*s0, 0) == False [statically known]
V1216 15:56:13.538000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 25165824*s0 > 1 == True [statically known]
V1216 15:56:13.654000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 256*s0 >= 0 == True [statically known]
V1216 15:56:13.655000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval Eq(256*s0, 0) == False [statically known]
V1216 15:56:13.664000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 12582912*s0 > 1 == True [statically known]
V1216 15:56:13.779000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 64*s0 >= 0 == True [statically known]
V1216 15:56:13.779000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval Eq(64*s0, 0) == False [statically known]
V1216 15:56:13.788000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 6291456*s0 > 1 == True [statically known]
V1216 15:56:14.495000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 16*s0 >= 0 == True [statically known]
V1216 15:56:14.496000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval Eq(16*s0, 0) == False [statically known]
V1216 15:56:14.505000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 3145728*s0 > 1 == True [statically known]
V1216 15:56:17.410000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 8388608*s0 > 128 == True [statically known]
V1216 15:56:17.418000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 4194304*s0 > 256 == True [statically known]
V1216 15:56:17.426000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 2097152*s0 > 512 == True [statically known]
V1216 15:56:17.434000 222606 torch/fx/experimental/symbolic_shapes.py:5201] eval 1048576*s0 > 1024 == True [statically known]
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/export/_unlift.py:60: UserWarning: Attempted to insert a get_attr Node with no underlying reference in the owning GraphModule! Call GraphModule.add_submodule to add the necessary submodule, GraphModule.add_parameter to add the necessary Parameter, or nn.Module.register_buffer to add the necessary buffer
  getattr_node = gm.graph.get_attr(lifted_node)
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph.py:1586: UserWarning: Node backbone_backbone_backbone_features_1_1_attn_lifted_tensor_0 target backbone.backbone.backbone.features.1.1.attn.lifted_tensor_0 lifted_tensor_0 of backbone.backbone.backbone.features.1.1.attn does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(f'Node {node} target {node.target} {atom} of {seen_qualname} does '
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph.py:1586: UserWarning: Node backbone_backbone_backbone_features_1_1_attn_lifted_tensor_1 target backbone.backbone.backbone.features.1.1.attn.lifted_tensor_1 lifted_tensor_1 of backbone.backbone.backbone.features.1.1.attn does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target

```

Full traceback for the second issue, when running that loaded model, CUDA OOM

```
  warnings.warn(f'Node {node} target {node.target} {atom} of {seen_qualname} does '
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph.py:1586: UserWarning: Node backbone_backbone_backbone_features_1_1_attn_lifted_tensor_4 target backbone.backbone.backbone.features.1.1.attn.lifted_tensor_4 lifted_tensor_4 of backbone.backbone.backbone.features.1.1.attn does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(f'Node {node} target {node.target} {atom} of {seen_qualname} does '
/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph.py:1593: UserWarning: Additional 428 warnings suppressed about get_attr references
  warnings.warn(
Traceback (most recent call last):
  File "/home/rave/work/modelhub/model-forge/satlas/solar/test.py", line 16, in <module>
    test_inference()
  File "/home/rave/work/modelhub/model-forge/satlas/solar/test.py", line 13, in test_inference
    outputs, _ = pt2_model(test_img_ts)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph_module.py", line 784, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph_module.py", line 361, in __call__
    raise e
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/fx/graph_module.py", line 348, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
    return inner()
           ^^^^^^^
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<eval_with_key>.4", line 10099, in forward
  File "/home/rave/work/modelhub/.venv/lib/python3.11/site-packages/torch/_ops.py", line 716, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 48.44 MiB is free. Including non-PyTorch memory, this process has 22.91 GiB memory in use. Of the allocated memory 22.01 GiB is allocated by PyTorch, and 613.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
V1216 15:56:21.849000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats constrain_symbol_range: CacheInfo(hits=8, misses=1, maxsize=None, currsize=1)
V1216 15:56:21.849000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats evaluate_expr: CacheInfo(hits=10074, misses=18, maxsize=256, currsize=18)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _simplify_floor_div: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _maybe_guard_rel: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _find: CacheInfo(hits=240, misses=1, maxsize=None, currsize=1)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats has_hint: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats size_hint: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats simplify: CacheInfo(hits=0, misses=18, maxsize=None, currsize=18)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _update_divisible: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats replace: CacheInfo(hits=281362, misses=353, maxsize=None, currsize=353)
V1216 15:56:21.850000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _maybe_evaluate_static: CacheInfo(hits=0, misses=18, maxsize=None, currsize=18)
V1216 15:56:21.851000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats get_implications: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1216 15:56:21.851000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats get_axioms: CacheInfo(hits=17, misses=1, maxsize=None, currsize=1)
V1216 15:56:21.851000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats safe_expand: CacheInfo(hits=51249, misses=422, maxsize=256, currsize=256)
V1216 15:56:21.851000 222606 torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats uninteresting_files: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)

```

### Versions

unfortunately this doesn't work with uv/my env in uv. 

```
Collecting environment information...
Traceback (most recent call last):
  File "/home/rave/work/modelhub/collect_env.py", line 692, in <module>
    main()
  File "/home/rave/work/modelhub/collect_env.py", line 675, in main
    output = get_pretty_env_info()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/collect_env.py", line 670, in get_pretty_env_info
    return pretty_str(get_env_info())
                      ^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/collect_env.py", line 495, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/work/modelhub/collect_env.py", line 450, in get_pip_packages
    for line in out.splitlines()
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

Here are my torch related requirements

```
torch==2.5.1 ; platform_system == 'Darwin'
torch==2.5.1+cu121 ; platform_system != 'Darwin'
torchvision==0.20.1 ; platform_system == 'Darwin'
torchvision==0.20.1+cu121 ; platform_system != 'Darwin'
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
triton==3.1.0 ; python_full_version < '3.13' and platform_machine == 'x86_64' and platform_system == 'Linux'
```

cc @chauhang @penguinwu

**Comment by rbavery** [comment]
I had the wrong impression that torch.export.export is the public api to using torch._export.aot_compile. It seems that they are complementary. Not sure why I'm OOMing but closing since I'm not doing what I thought I was doing.

From the pytorch slack
    - multi model archive example that requires aot + torch.export.export https://github.com/pytorch/pytorch/blob/efab8c433f257a4ab01fd07ca4b4a6aaf6ddc632/test/inductor/test_aot_inductor_package.py#L200-L252
 
    - deprecation warning for aot_compile with instructions https://github.com/pytorch/pytorch/blob/efab8c433f257a4ab01fd07ca4b4a6aaf6ddc632/torch/_export/__init__.py#L271-L282
