### ISSUE TITLE
torch.compile - Simplify error when triton package is  not found 

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#143406]
### 🐛 Describe the bug

Initial title:  titon: python 3.13 torch.compile smoke test is failing in CI/CD

I observe following failure running smoke_test for python 3.13, cuda 11.8, cuda 12.4, cuda 12.6: https://github.com/pytorch/pytorch/blob/main/.ci/pytorch/smoke_test/smoke_test.py

Detected during validation testing. Please see: https://github.com/pytorch/test-infra/issues/6077#issue-2745142173

Worklfow: https://github.com/pytorch/pytorch/actions/runs/12378525708/job/34555282656?pr=143397#step:15:1434

Full log:
```
++ python3 ./smoke_test/smoke_test.py --package torchonly
torch: 2.6.0+cu118
ATen/Parallel:
	at::get_num_threads() : 8
	at::get_num_interop_threads() : 16
OpenMP 201511 (a.k.a. OpenMP 4.5)
	omp_get_max_threads() : 8
Intel(R) oneAPI Math Kernel Library Version 2024.2-Product Build 20240605 for Intel(R) 64 architecture applications
	mkl_get_max_threads() : 8
Intel(R) MKL-DNN v3.5.3 (Git Hash 66f0cb9eb66affd2da3bf5f8d897376f04aae6af)
std::thread::hardware_concurrency() : 16
Environment variables:
	OMP_NUM_THREADS : [not set]
	MKL_NUM_THREADS : [not set]
ATen parallel backend: OpenMP

Testing smoke_test_conv2d
Testing smoke_test_conv2d with cuda
/pytorch/pytorch/.ci/pytorch/./smoke_test/smoke_test.py:232: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():
Testing smoke_test_conv2d with cuda for torch.float16
Testing smoke_test_conv2d with cuda for torch.float32
Testing smoke_test_conv2d with cuda for torch.float64
Testing smoke_test_linalg on cpu
Testing smoke_test_linalg on cuda
Testing smoke_test_linalg with cuda for torch.float32
Testing smoke_test_linalg with cuda for torch.float64
Testing smoke_test_compile for cuda and torch.float16
Traceback (most recent call last):
  File "/pytorch/pytorch/.ci/pytorch/./smoke_test/smoke_test.py", line 385, in <module>
    main()
    ~~~~^^
  File "/pytorch/pytorch/.ci/pytorch/./smoke_test/smoke_test.py", line 379, in main
    smoke_test_cuda(
    ~~~~~~~~~~~~~~~^
        options.package, options.runtime_error_check, options.torch_compile_check
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/pytorch/pytorch/.ci/pytorch/./smoke_test/smoke_test.py", line 186, in smoke_test_cuda
    smoke_test_compile("cuda" if torch.cuda.is_available() else "cpu")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pytorch/pytorch/.ci/pytorch/./smoke_test/smoke_test.py", line 286, in smoke_test_compile
    x_pt2 = torch.compile(foo)(x)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/eval_frame.py", line 573, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 1380, in __call__
    return self._torchdynamo_orig_callable(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        frame, cache_entry, self.hooks, frame_state, skip=1
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 1164, in __call__
    result = self._inner_convert(
        frame, cache_entry, hooks, frame_state, skip=skip + 1
    )
  File "/opt/conda/envs/conda-env-12[3750](https://github.com/pytorch/test-infra/actions/runs/12375056109/job/34539025723#step:14:3751)56109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 547, in __call__
    return _compile(
        frame.f_code,
    ...<14 lines>...
        skip=skip + 1,
    )
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 986, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 715, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 750, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/bytecode_transformation.py", line 1361, in transform_code_object
    transformations(instructions, code_options)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/convert_frame.py", line 662, in transform
    tracer.run()
    ~~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 2868, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 1052, in run
    while self.step():
          ~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 962, in step
    self.dispatch_table[inst.opcode](self, inst)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 3048, in RETURN_VALUE
    self._return(inst)
    ~~~~~~~~~~~~^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/symbolic_convert.py", line 3033, in _return
    self.output.compile_subgraph(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<2 lines>...
        ),
        ^^
    )
    ^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/output_graph.py", line 1101, in compile_subgraph
    self.compile_and_call_fx_graph(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        tx, list(reversed(stack_values)), root, output_replacements
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/output_graph.py", line 1382, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/output_graph.py", line 1432, in call_user_compiler
    return self._call_user_compiler(gm)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/output_graph.py", line 1483, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
        e.__traceback__
    ) from None
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/output_graph.py", line 1462, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/__init__.py", line 2314, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 1863, in compile_fx
    return aot_autograd(
           ~~~~~~~~~~~~~
    ...<6 lines>...
        cudagraphs=cudagraphs,
        ~~~~~~~~~~~~~~~~~~~~~~
    )(model_, example_inputs_)
    ~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/backends/common.py", line 83, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_functorch/aot_autograd.py", line 1155, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_functorch/aot_autograd.py", line 1131, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        functional_call,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        shape_env,
        ^^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_functorch/aot_autograd.py", line 580, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
        flat_fn, fake_flat_args, aot_config, fake_mode, shape_env
    )
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_functorch/aot_autograd.py", line 830, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ~~~~~~~~~~~^
        flat_fn,
        ^^^^^^^^
    ...<2 lines>...
        fw_metadata=fw_metadata,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 203, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_functorch/aot_autograd.py", line 489, in __call__
    return self.compiler_fn(gm, example_inputs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 1741, in fw_compiler_base
    return inner_compile(
        gm,
    ...<5 lines>...
        boxed_forward_device_index=forward_device,
    )
Traceback (most recent call last):
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 569, in compile_fx_inner
  File "/home/ec2-user/actions-runner/_work/test-infra/test-infra/test-infra/.github/scripts/run_with_env_secrets.py", line 102, in <module>
    main()
  File "/home/ec2-user/actions-runner/_work/test-infra/test-infra/test-infra/.github/scripts/run_with_env_secrets.py", line 98, in main
    run_cmd_or_die(f"docker exec -t {container_name} /exec")
  File "/home/ec2-user/actions-runner/_work/test-infra/test-infra/test-infra/.github/scripts/run_with_env_secrets.py", line 39, in run_cmd_or_die
    raise RuntimeError(f"Command {cmd} failed with exit code {exit_code}")
RuntimeError: Command docker exec -t 9918c06ce07754c73f8d05922651f9952bdb247939406ec9e910b63df29bad02 /exec failed with exit code 1
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        gm,
        ^^^
        example_inputs,
        ^^^^^^^^^^^^^^^
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_dynamo/repro/after_aot.py", line 102, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 685, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm, example_inputs, inputs_to_check, **graph_kwargs
    )
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 1129, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 1044, in codegen_and_compile
    compiled_fn = graph.compile_to_module().call
                  ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/graph.py", line 2027, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/graph.py", line 2033, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
                                                             ~~~~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/graph.py", line 1964, in codegen
    self.scheduler = Scheduler(self.operations)
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 1798, in __init__
    self._init(nodes)
    ~~~~~~~~~~^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 1816, in _init
    self.nodes = [self.create_scheduler_node(n) for n in nodes]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 1947, in create_scheduler_node
    return SchedulerNode(self, node)
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 893, in __init__
    self._compute_attrs()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 907, in _compute_attrs
    group_fn = self.scheduler.get_backend(device).group_fn
               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 3441, in get_backend
    self.backends[device] = self.create_backend(device)
                            ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/conda/envs/conda-env-12375056109/lib/python3.13/site-packages/torch/_inductor/scheduler.py", line 3432, in create_backend
    raise RuntimeError(
        "Cannot find a working triton installation. Either the package is not installed or it is too old. More information on installing Triton can be found at https://github.com/openai/triton"  # noqa: B950
    )
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Cannot find a working triton installation. Either the package is not installed or it is too old. More information on installing Triton can be found at https://github.com/openai/triton

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

++ handle_error
Please note: We are currently migrating Linux Wheel builds to Manywheel 2.28
++ echo 'Please note: We are currently migrating Linux Wheel builds to Manywheel 2.28'
++ echo 'If you see error like: ImportError: /lib64/libc.so.6: version GLIBC_2.28 not found'
++ echo 'Please migrate to: https://github.com/pytorch/test-infra/blob/main/.github/workflows/linux_job_v2.yml'
++ echo 'Issue: https://github.com/pytorch/pytorch/issues/123649'
If you see error like: ImportError: /lib64/libc.so.6: version GLIBC_2.28 not found
Please migrate to: https://github.com/pytorch/test-infra/blob/main/.github/workflows/linux_job_v2.yml
Issue: https://github.com/pytorch/pytorch/issues/123649
Error: Process completed with exit code 1.```

### Versions

2.6.0

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov @ezyang @gchanan @zou3519 @msaroufim

**Comment by atalman** [comment]
Posted enabling smoke_testing with compile on nightly build: https://github.com/pytorch/pytorch/pull/143397

**Comment by malfet** [comment]
This looks very similar to https://github.com/pytorch/pytorch/issues/143288

**Comment by atalman** [comment]
Here is the error: https://github.com/pytorch/test-infra/actions/runs/12375056109/job/34539025723
Not an issue, triton is missing from the installation, will be fixed when we rebuild the rc : 
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Cannot find a working triton installation. Either the package is not installed or it is too old. More information on installing Triton can be found at https://github.com/openai/triton
```

**Comment by atalman** [comment]
Reopening to simplify the error, we should probably have simple: ```RuntimeError: Cannot find a working triton installation.``` rather then having whole stack trace.
