### ISSUE TITLE
[Break XPU] The device-bias hard code in `is_big_gpu` cause case failures on XPU.

### ISSUE THREAD

**Issue by etaf** [pytorch/pytorch#143472]
### 🐛 Describe the bug

We found the recent XPU CI failure https://hud.pytorch.org/pr/pytorch/pytorch/142322#34573031104 which is caused by #143339 

```
Z _______________ AOTInductorTestABICompatibleGpu.test_conv3d_xpu ________________
2024-12-18T04:17:23.7324890Z Traceback (most recent call last):
2024-12-18T04:17:23.7325205Z   File "/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py", line 11965, in new_test
2024-12-18T04:17:23.7325511Z     return value(self)
2024-12-18T04:17:23.7325794Z   File "/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py", line 4116, in test_conv3d
2024-12-18T04:17:23.7326123Z     if self.device != GPU_TYPE or not is_big_gpu():
2024-12-18T04:17:23.7326472Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py", line 1134, in is_big_gpu
2024-12-18T04:17:23.7326825Z     prop = DeviceProperties.create(device)
2024-12-18T04:17:23.7327170Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/runtime/hints.py", line 139, in create
2024-12-18T04:17:23.7327539Z     props = device_interface.get_device_properties(device)
2024-12-18T04:17:23.7327919Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/cuda/__init__.py", line 524, in get_device_properties
2024-12-18T04:17:23.7328298Z     _lazy_init()  # will define _get_device_properties
2024-12-18T04:17:23.7328643Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/cuda/__init__.py", line 311, in _lazy_init
2024-12-18T04:17:23.7329071Z     raise AssertionError("Torch not compiled with CUDA enabled")
2024-12-18T04:17:23.7329345Z AssertionError: Torch not compiled with CUDA enabled
2024-12-18T04:17:23.7329493Z 
2024-12-18T04:17:23.7329613Z To execute this test, run the following from the base repo dir:
2024-12-18T04:17:23.7330007Z     python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleGpu.test_conv3d_xpu
```

The root cause is the "cuda" hard code in `is_big_gpu`.

### Versions

PyTorch version: 2.6.0a0+gite6c7400
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.2
Libc version: glibc-2.35

Python version: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.47+prerelease24.6.13-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by EikanWang** [comment]
Let's return `False` for other devices except `CUDA` to fix the issue.
