### ISSUE TITLE
AssertionError: not bool like VR[1.00000000000000, 1.00000000000000]

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#143502]
### 🐛 Describe the bug

I triggered this bug while bisecting, it is not blocking me.

Backtrace:

```
Traceback (most recent call last):
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/convert_frame.py", line 979, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/convert_frame.py", line 709, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_utils_internal.py", line 306, in wrapper_function
    result = StrobelightCompileTimeProfiler.profile_compile_time(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/caffe2/fb/strobelight/compile_time_profiler.py", line 162, in profile_compile_time
    return func(*args, **kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/convert_frame.py", line 744, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/convert_frame.py", line 233, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/convert_frame.py", line 661, in transform
    tracer.run()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/symbolic_convert.py", line 2900, in run
    super().run()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/symbolic_convert.py", line 1120, in run
    while self.step():
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/symbolic_convert.py", line 1032, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/symbolic_convert.py", line 3091, in RETURN_VALUE
    self._return(inst)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/symbolic_convert.py", line 3076, in _return
    self.output.compile_subgraph(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/output_graph.py", line 1110, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/output_graph.py", line 1349, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/output_graph.py", line 1399, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/output_graph.py", line 1448, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/output_graph.py", line 1429, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/__init__.py", line 2301, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 1449, in compile_fx
    return compile_fx(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 1733, in compile_fx
    return aot_autograd(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_functorch/aot_autograd.py", line 1103, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_functorch/aot_autograd.py", line 1079, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_functorch/aot_autograd.py", line 527, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_functorch/aot_autograd.py", line 778, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 655, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 1546, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 1615, in _fw_compiler_base
    return inner_compile(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/runtime/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 599, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_dynamo/repro/after_aot.py", line 102, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/fb/utils.py", line 167, in newFunction
    return old_func(*args, **kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 756, in _compile_fx_inner
    compiled_graph = FxGraphCache.load(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/codecache.py", line 1515, in load
    compiled_graph = compile_fx_fn(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 663, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/compile_fx.py", line 974, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/graph.py", line 2043, in compile_to_fn
    return self.compile_to_module().call
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/graph.py", line 1954, in compile_to_module
    return self._compile_to_module()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/graph.py", line 1960, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/graph.py", line 1896, in codegen
    self.scheduler.codegen()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/scheduler.py", line 3489, in codegen
    return self._codegen()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/scheduler.py", line 3568, in _codegen
    self.get_backend(device).codegen_node(node)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/codegen/cuda_combined_scheduling.py", line 80, in codegen_node
    return self._triton_scheduling.codegen_node(node)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/codegen/simd.py", line 1195, in codegen_node
    return self.codegen_node_schedule(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/codegen/simd.py", line 1263, in codegen_node_schedule
    self.codegen_node_schedule_with_kernel(node_schedule, kernel)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/codegen/simd.py", line 1353, in codegen_node_schedule_with_kernel
    node.codegen(index_vars)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/scheduler.py", line 1020, in codegen
    with V.set_ops_handler(
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/runtime/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/codegen/common.py", line 2071, in set_current_node
    self.node_to_bounds = node._body.bounds().get_bounds()
  File "<string>", line 5, in get_bounds_cache_on_self
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/bounds.py", line 74, in get_bounds
    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/loop_body.py", line 60, in run
    return super().run(*args, **kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/fx/interpreter.py", line 167, in run
    self.env[node] = self.run_node(node)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/_inductor/loop_body.py", line 56, in run_node
    return super().run_node(n)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/fx/interpreter.py", line 228, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/fx/interpreter.py", line 332, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/utils/_sympy/value_ranges.py", line 853, in where
    a = a.boolify()
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/1b080a82294b728e/bento_kernels/pytorch/__bento_kernel_pytorch_binary__/bento_kernel_pytorch_binary#link-tree/torch/utils/_sympy/value_ranges.py", line 223, in boolify
    raise AssertionError(f"not bool like {self}")
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: not bool like VR[1.00000000000000, 1.00000000000000]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

This tlparse isn't great, I need to make a cleaner one.
tlparse: https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpOsBxLd/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100#[7/0]

I think https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpOsBxLd/7_0_0/inductor_post_grad_graph_900.txt?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100 is what induces the problem though.

I'm working on the internal repro instructions.

### Versions

main

cc @chauhang @penguinwu @bobrenjc93 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by eellison** [comment]
Note - this was only an error with a debugging config on..
