### ISSUE TITLE
[Inductor][CPU] C++ compile error: no known conversion from `VecMask` to `VectorizedN`

### ISSUE THREAD

**Issue by guangyey** [pytorch/pytorch#143568]
### 🐛 Describe the bug

It will raise a C++ compile error when run the following reproducer.

```python
import torch

def demo():
    # Input tensors that are generated randomly
    torch.manual_seed(777)
    in_self_ln39273 = (
        torch.randn(size=[128, 2501], device="cpu").ge(0)
    )

    def fwd_subgraph():
        # pytorch op calls encoded from aten functions
        res_ln39273_0, res_ln39273_1 = torch.max(
            in_self_ln39273, 1, False
        )  # traced line: 39273
        return res_ln39273_0, res_ln39273_1

    sg_callable = torch.compile(fwd_subgraph)
    with torch.amp.autocast('cpu', enabled=True, dtype=torch.bfloat16):
        res_ln39273_0, res_ln39273_1 = sg_callable()
    return {"res_ln39273_0": res_ln39273_0, "res_ln39273_1": res_ln39273_1}

print(demo())
```
The output is 
```bash
E1219 03:07:31.455000 3547855 stock-pytorch/torch/_dynamo/repro/after_aot.py:119] [0/0] CompilerError
Traceback (most recent call last):
  File "/home/pt-gpu/4T-4652/guangyey/test1.py", line 23, in <module>
    print(dlrminfer_compile_bf16_step_1_fwd_max_rfid_39273())
  File "/home/pt-gpu/4T-4652/guangyey/test1.py", line 20, in dlrminfer_compile_bf16_step_1_fwd_max_rfid_39273
    res_ln39273_0, res_ln39273_1 = sg_callable()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/eval_frame.py", line 576, in _fn
    return fn(*args, **kwargs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 1387, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 1171, in __call__
    result = self._inner_convert(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 548, in __call__
    return _compile(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 988, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 716, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 751, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/bytecode_transformation.py", line 1361, in transform_code_object
    transformations(instructions, code_options)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 232, in _fn
    return fn(*args, **kwargs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/convert_frame.py", line 663, in transform
    tracer.run()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/symbolic_convert.py", line 2870, in run
    super().run()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/symbolic_convert.py", line 1053, in run
    while self.step():
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/symbolic_convert.py", line 963, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/symbolic_convert.py", line 3050, in RETURN_VALUE
    self._return(inst)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/symbolic_convert.py", line 3035, in _return
    self.output.compile_subgraph(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/output_graph.py", line 1136, in compile_subgraph
    self.compile_and_call_fx_graph(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/output_graph.py", line 1382, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/output_graph.py", line 1432, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/output_graph.py", line 1483, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/output_graph.py", line 1462, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/__init__.py", line 2314, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/compile_fx.py", line 1880, in compile_fx
    return aot_autograd(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/backends/common.py", line 83, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/aot_autograd.py", line 1145, in aot_module_simplified
    compiled_fn = AOTAutogradCache.load(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/_aot_autograd/autograd_cache.py", line 754, in load
    compiled_fn = dispatch_and_compile()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/aot_autograd.py", line 1131, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/aot_autograd.py", line 580, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/aot_autograd.py", line 830, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 201, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_functorch/aot_autograd.py", line 489, in __call__
    return self.compiler_fn(gm, example_inputs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/compile_fx.py", line 1758, in fw_compiler_base
    return inner_compile(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/compile_fx.py", line 572, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_dynamo/repro/after_aot.py", line 102, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/compile_fx.py", line 686, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/compile_fx.py", line 1129, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/compile_fx.py", line 1044, in codegen_and_compile
    compiled_fn = graph.compile_to_module().call
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/graph.py", line 1978, in compile_to_module
    return self._compile_to_module()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/graph.py", line 2019, in _compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/codecache.py", line 2756, in load_by_key_path
    mod = _reload_python_module(key, path)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/runtime/compile_tasks.py", line 45, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_pt-gpu/ya/cyarcc2jewtxa72ffr36zkk7ofyedvzpifamfhkv4rbglo3ros5w.py", line 76, in <module>
    async_compile.wait(globals())
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/async_compile.py", line 306, in wait
    scope[key] = result.result()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/codecache.py", line 3250, in result
    return self.result_fn()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/codecache.py", line 2250, in future
    result = get_result()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/codecache.py", line 2040, in load_fn
    future.result()
  File "/home/pt-gpu/4T-4652/envs/ygy_stock/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/pt-gpu/4T-4652/envs/ygy_stock/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/pt-gpu/4T-4652/envs/ygy_stock/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/codecache.py", line 2081, in _worker_compile_cpp
    cpp_builder.build()
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/cpp_builder.py", line 1544, in build
    status = run_compile_cmd(build_cmd, cwd=_build_tmp_dir)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/cpp_builder.py", line 345, in run_compile_cmd
    return _run_compile_cmd(cmd_line, cwd)
  File "/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/_inductor/cpp_builder.py", line 339, in _run_compile_cmd
    raise exc.CppCompileError(cmd, output) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.cpp -D TORCH_INDUCTOR_CPP_WRAPPER -D STANDALONE_TORCH_HEADER -D C10_USING_CUSTOM_GENERATED_MACROS -D CPU_CAPABILITY_AVX512 -shared -fPIC -O3 -DNDEBUG -fno-trapping-math -funsafe-math-optimizations -ffinite-math-only -fno-signed-zeros -fno-math-errno -fexcess-precision=fast -fno-finite-math-only -fno-unsafe-math-optimizations -ffp-contract=off -fno-tree-loop-vectorize -march=native -Wall -std=c++17 -Wno-unused-variable -Wno-unknown-pragmas -fopenmp -I/home/pt-gpu/4T-4652/envs/ygy_stock/include/python3.10 -I/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/include -I/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/include/torch/csrc/api/include -I/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/include/TH -I/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/include/THC -mavx512f -mavx512dq -mavx512vl -mavx512bw -mfma -mamx-tile -mamx-bf16 -mamx-int8 -D_GLIBCXX_USE_CXX11_ABI=1 -ltorch -ltorch_cpu -ltorch_python -lgomp -L/home/pt-gpu/4T-4652/envs/ygy_stock/lib -L/home/pt-gpu/4T-4652/guangyey/stock-pytorch/torch/lib -o /tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.so

Output:
/tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.cpp: In function ‘void kernel(const bool*, bool*, int64_t*)’:
/tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.cpp:23:80: error: no matching function for call to ‘argmax_combine_vec<bool, 1, 2, true>(IndexValueVec<bool, 1, 2>&, at::vec::CPU_CAPABILITY::VecMask<float, 1>&, int64_t&)’
   23 |                             tmp_acc1_vec = argmax_combine_vec<bool, 1, 2, true>(tmp_acc1_vec, tmp0, x1);
      |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.cpp:2:
/tmp/torchinductor_pt-gpu/2r/c2rnilspx43ivnzu4uieul65kx65dfhfbptbh5og4wk6rqebuxoo.h:396:34: note: candidate: ‘IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>&, at::vec::CPU_CAPABILITY::VectorizedN<T, N>, int64_t, std::optional<long int>) [with T = bool; int NV = 1; int NI = 2; bool horizontal = true; int64_t = long int]’
  396 | inline IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>& a, at::vec::VectorizedN<T, NV> next_value, int64_t next_index, std::optional<int64_t> tail_size = std::nullopt){
      |                                  ^~~~~~~~~~~~~~~~~~
/tmp/torchinductor_pt-gpu/2r/c2rnilspx43ivnzu4uieul65kx65dfhfbptbh5og4wk6rqebuxoo.h:396:110: note:   no known conversion for argument 2 from ‘at::vec::CPU_CAPABILITY::VecMask<float, 1>’ to ‘at::vec::CPU_CAPABILITY::VectorizedN<bool, 1>’
  396 | inline IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>& a, at::vec::VectorizedN<T, NV> next_value, int64_t next_index, std::optional<int64_t> tail_size = std::nullopt){
      |                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/tmp/torchinductor_pt-gpu/2r/c2rnilspx43ivnzu4uieul65kx65dfhfbptbh5og4wk6rqebuxoo.h:435:34: note: candidate: ‘template<class T, int NV, int NI> IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>&, const IndexValueVec<T, NV, NI>&, std::optional<long int>)’
  435 | inline IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>& vec_a, const IndexValueVec<T, NV, NI>& vec_b, std::optional<int64_t> tail_size = std::nullopt){
      |                                  ^~~~~~~~~~~~~~~~~~
/tmp/torchinductor_pt-gpu/2r/c2rnilspx43ivnzu4uieul65kx65dfhfbptbh5og4wk6rqebuxoo.h:435:34: note:   template argument deduction/substitution failed:
/tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.cpp:23:80: error: wrong number of template arguments (4, should be 3)
   23 |                             tmp_acc1_vec = argmax_combine_vec<bool, 1, 2, true>(tmp_acc1_vec, tmp0, x1);
      |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/torchinductor_pt-gpu/hj/chjaf7w6mzln3blgtjqbhumxw3gvjxyspdn5nfsz663nfp5rxqvv.cpp:2:
/tmp/torchinductor_pt-gpu/2r/c2rnilspx43ivnzu4uieul65kx65dfhfbptbh5og4wk6rqebuxoo.h:435:34: note: provided for ‘template<class T, int NV, int NI> IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>&, const IndexValueVec<T, NV, NI>&, std::optional<long int>)’
  435 | inline IndexValueVec<T, NV, NI>& argmax_combine_vec(IndexValueVec<T, NV, NI>& vec_a, const IndexValueVec<T, NV, NI>& vec_b, std::optional<int64_t> tail_size = std::nullopt){
      |                                  ^~~~~~~~~~~~~~~~~~


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

Collecting environment information...
PyTorch version: 2.6.0a0+git2d0d447
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.1
Libc version: glibc-2.35

Python version: 3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:16:10) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          224
On-line CPU(s) list:             0-223
Vendor ID:                       GenuineIntel
Model name:                      Genuine Intel(R) CPU 0000%@
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              56
Socket(s):                       2
Stepping:                        5
CPU max MHz:                     4000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        3600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       5.3 MiB (112 instances)
L1i cache:                       3.5 MiB (112 instances)
L2 cache:                        224 MiB (112 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-55,112-167
NUMA node1 CPU(s):               56-111,168-223
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==2.2.0
[pip3] optree==0.13.1
[pip3] pytorch-triton-xpu==3.2.0+gite98b6fcb
[pip3] torch==2.6.0a0+git2d0d447
[conda] numpy                     2.2.0                    pypi_0    pypi
[conda] optree                    0.13.1                   pypi_0    pypi
[conda] pytorch-triton-xpu        3.2.0+gite98b6fcb          pypi_0    pypi
[conda] torch                     2.6.0a0+git2d0d447           dev_0    <develop>

cc @jgong5 @EikanWang

**Comment by leslie-fang-intel** [comment]
cc @blzheng to take a look.
