### ISSUE TITLE
FSDP learning hangs when program tries to save the model

### ISSUE THREAD

**Issue by phos-phophy** [pytorch/pytorch#143536]
## TL;DR

I have strange intermittent error which I can fix in my own (just by adding one line), but I don't know how to fix it properly in general

## What's the problem?

Recently I have tried to fine-tune some LLMs using [Accelerate](https://github.com/huggingface/accelerate) from HuggingFace. I have used FSDP distributed learning + LoRA adapter to fine-tune 2 models from Qwen series:  [Qwen2.5-7B-Instruct](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct) and [Qwen2.5-1.5B-Instruct](https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct). And when there are no problems with the latter model, I have got a strange intermittent error when trying to save the former after training (It may not happen right away, but it will happen for sure)

```bash
/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
  warnings.warn(
[rank0]:[E1219 03:01:55.989449808 ProcessGroupNCCL.cpp:616] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=600, OpType=_ALLGATHER_BASE, NumelIn=58309504, NumelOut=233238016, Timeout(ms)=1800000) ran for 1800068 milliseconds before timing out.
[rank0]:[E1219 03:01:55.990175767 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 600, last enqueued NCCL work: 600, last completed NCCL work: 599.
[rank0]:[E1219 03:01:56.095109308 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 0] Timeout at NCCL work: 600, last enqueued NCCL work: 600, last completed NCCL work: 599.
[rank0]:[E1219 03:01:56.095141631 ProcessGroupNCCL.cpp:630] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E1219 03:01:56.095151475 ProcessGroupNCCL.cpp:636] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E1219 03:01:56.096419462 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=600, OpType=_ALLGATHER_BASE, NumelIn=58309504, NumelOut=233238016, Timeout(ms)=1800000) ran for 1800068 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fc856081446 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7fc857394772 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7fc85739bbb3 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7fc85739d61d in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x7fc89fd2a5c0 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x8609 (0x7fc8a24df609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7fc8a2619133 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=600, OpType=_ALLGATHER_BASE, NumelIn=58309504, NumelOut=233238016, Timeout(ms)=1800000) ran for 1800068 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fc856081446 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7fc857394772 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7fc85739bbb3 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7fc85739d61d in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x7fc89fd2a5c0 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x8609 (0x7fc8a24df609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7fc8a2619133 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fc856081446 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe4271b (0x7fc85700a71b in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7fc89fd2a5c0 in /mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x8609 (0x7fc8a24df609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #4: clone + 0x43 (0x7fc8a2619133 in /lib/x86_64-linux-gnu/libc.so.6)

E1219 03:01:57.498000 786687 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -6) local_rank: 0 (pid: 786758) of binary: /mnt/data/a.kudisov/transformers/.venv/bin/python
Traceback (most recent call last):
  File "/mnt/data/a.kudisov/transformers/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/a.kudisov/transformers/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-19_03:01:57
  host      : ...
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 786758)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 786758
=======================================================
```

This error occurs when the program tries to save the model and hangs while collecting model.state_dict()
I did a little investigation and found out that the main process (it is distributed learning with 4 processes) successfully collects all model's layers on cpu, except the last one. When it starts processing the last layer, the whole process hangs and crashes on timeout.

If I change model from Qwen2.5-7B-Instruct to Qwen2.5-1.5B-Instruct (from a big one to a small one) this error will disappear (there is still one more [problem](https://github.com/huggingface/transformers/pull/35234) that will not allow you to save the model after training but it's related to transformers from HuggingFace, not pytorch)

I believe this error has something to do with communication between processes.

## How to reproduce?

```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch --config_file=config.yaml --main_process_port=12355 train.py --output_dir=./save
```

Accelerate config:
```yaml
# accelerate.yaml
compute_environment: LOCAL_MACHINE
debug: true
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: NO_PREFETCH
  fsdp_forward_prefetch: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Training script:
```python
# train.py
import argparse
from functools import partial

import torch
from datasets import Dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments


def get_data(tokenizer):

    data = [{
        'user_message': "Hi, how are you?",
        'model_message': "I'm good, thanks. How about you?"
    }] * 20

    data = Dataset.from_list(data)
    data = data.train_test_split(train_size=0.7, shuffle=True, seed=42)
    tmp = data['test'].train_test_split(test_size=0.6, shuffle=True, seed=143)
    data['validation'] = tmp['train']
    data['test'] = tmp['test']

    def tokenize(x):
        messages = [
            {'role': 'user', "content": x['user_message']},
            {'role': 'assistant', "content": x['model_message']},
        ]

        text = tokenizer.decode(tokenizer.apply_chat_template(messages))
        result = tokenizer(text, return_tensors='pt')

        sep = '<|im_start|>assistant\n'
        input_text = text.split(sep)[0] + sep
        input_len = len(tokenizer(input_text)['input_ids'])

        result['labels'] = result['input_ids'].clone().detach()
        result['labels'][:, :input_len] = -100

        return {k: v.tolist()[0] for k, v in result.items()}

    tokenized_datasets = data.map(
        tokenize,
        remove_columns=['user_message', 'model_message'],
    )
    tokenized_datasets.set_format('torch')

    return tokenized_datasets

def collate_fn(data, pad_token_id):
    input_ids, labels = tuple([x[key] for x in data] for key in ('input_ids', 'labels'))
    input_ids = torch.nn.utils.rnn.pad_sequence(input_ids, batch_first=True, padding_value=pad_token_id)
    labels = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value=-100)
    return {
        'input_ids': input_ids,
        'labels': labels,
        'attention_mask': input_ids.ne(pad_token_id) * 1
    }

def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(f'trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param:.2f}')

def training_function(args):
    model_name = 'Qwen/Qwen2.5-7B-Instruct'

    training_args = TrainingArguments(
        output_dir=args.output_dir,
        gradient_checkpointing=True,
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        num_train_epochs=1,
        save_strategy='no',
        seed=42,
        data_seed=42,
        optim='adamw_8bit'
    )

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    data = get_data(tokenizer)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        return_dict=True,
    )

    model.add_adapter(LoraConfig(
        r=16,
        lora_alpha=16,
        lora_dropout=0.1,
        target_modules=['q_proj', 'k_proj']
    ))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=data['train'],
        eval_dataset=data['validation'],
        data_collator=partial(collate_fn, pad_token_id=tokenizer.pad_token_id),
    )

    if trainer.accelerator.is_main_process:
        print_trainable_parameters(model)

    trainer.train()

    if trainer.is_fsdp_enabled:
        trainer.accelerator.state.fsdp_plugin.set_state_dict_type("FULL_STATE_DICT")
    trainer.save_model()

def main():
    parser = argparse.ArgumentParser(description='Main training script.')
    parser.add_argument(
        '--output_dir',
        type=str,
        default='.',
        help='Optional save directory where all checkpoint folders will be stored. Default is the current working directory.'
    )
    args = parser.parse_args()

    training_function(args)


if __name__ == '__main__':
    main()
```

Environment:
```bash
accelerate==1.1.1
torch==2.5.1+cu124
pandas==2.2.3
peft==0.13.2
datasets==3.1.0
transformers==4.46.3
tqdm==4.67.1
```

## How to fix?

I found that just adding `dist.barrier()` in  `_pre_state_dict_hook` function (from torch/distributed/fsdp/_state_dict_utils.py)  helps me overcome the problem. But I don't have enough expertise to be sure that this is the correct error correction.

```python
# torch/distributed/fsdp/_state_dict_utils.py
@no_type_check
@torch.no_grad()
def _pre_state_dict_hook(
    module: nn.Module,
    *args,
    **kwargs,
) -> None:
    """
    This is called before the core state dict saving logic of ``module``.
    ``fsdp_state._state_dict_type`` is used to decide what postprocessing will
    be done.
    """
    fsdp_state = _get_module_fsdp_state_if_fully_sharded_module(module)
    if fsdp_state.sharding_strategy == ShardingStrategy.NO_SHARD:
        context = _replace_with_full_state_dict_type(fsdp_state)
        warnings.warn(
            "When using ``NO_SHARD`` for ``ShardingStrategy``, full_state_dict will"
            "be returned."
        )
    else:
        _set_use_dtensor(fsdp_state)
        context = contextlib.nullcontext()

    with context:
        _pre_state_dict_hook_fn = {
            StateDictType.FULL_STATE_DICT: _full_pre_state_dict_hook,
            StateDictType.LOCAL_STATE_DICT: _local_pre_state_dict_hook,
            StateDictType.SHARDED_STATE_DICT: _sharded_pre_state_dict_hook,
        }

        ##############################################
        dist.barrier()  # I add this
        ##############################################

        _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
            fsdp_state,
            module,
            *args,
            **kwargs,
        )
```

### Versions

```
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-165-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      52 bits physical, 57 bits virtual
CPU(s):                             112
On-line CPU(s) list:                0-111
Thread(s) per core:                 2
Core(s) per socket:                 28
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              106
Model name:                         Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
Stepping:                           6
Frequency boost:                    enabled
CPU MHz:                            2527.355
CPU max MHz:                        2001.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4000.00
Virtualization:                     VT-x
L1d cache:                          2.6 MiB
L1i cache:                          1.8 MiB
L2 cache:                           70 MiB
L3 cache:                           84 MiB
NUMA node0 CPU(s):                  0-27,56-83
NUMA node1 CPU(s):                  28-55,84-111
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Vulnerable
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==2.1.3
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] torch==2.5.1+cu124
[pip3] triton==3.1.0
[conda] Could not collect
```

**Comment by fegin** [comment]
@phos-phophy Can you have a mini repro without accelerator? I couldn't reproduce the same issue.

**Comment by zwimpee2** [comment]
Hi all – just wanted to confirm that this FSDP-checkpoint hang is still reproducible on the latest PyTorch/Accelerate stack.

---

### TL;DR

* Job **finishes the final training step but freezes when it tries to gather & save the full state-dict.**
* After the 30-minute NCCL watchdog window the process group is torn down with an  
  `_ALLGATHER_BASE` timeout in `ProcessGroupNCCL.cpp`.

---

### Reproduction recipe (no private code)

Below is a fully-self-contained script that triggers the same failure on two GPUs (I can't share the actual code I am running unfortunately as it is internal)

<details>
<summary><code>fsdp_hang_minimal.py</code></summary>

```python
#!/usr/bin/env python
# torch==2.1.2, transformers==4.39.1, accelerate==0.27.2

import os, torch, numpy as np
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    set_seed,
)
set_seed(42)

# ----- tiny dummy dataset ----------------------------------------------------
TEXTS  = [f"example {i}" for i in range(128)]
LABELS = np.random.randint(0, 2, size=len(TEXTS))
ds = Dataset.from_dict({"text": TEXTS, "label": LABELS})
tokenizer = AutoTokenizer.from_pretrained("meta-llama/llama-3.1-8b-instruct")
ds = ds.map(lambda x: tokenizer(x["text"], truncation=True), batched=True)
# --------------------------------------------------------------------------- #

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2,
    attn_implementation="eager",  # same result with flash_attn_2
    torch_dtype=torch.bfloat16,
)

args = TrainingArguments(
    output_dir="out",
    max_steps=3,                               # minimal work
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=1,
    learning_rate=1e-4,
    bf16=True,
    logging_steps=1,
    eval_strategy="steps",
    save_strategy="steps",
)

Trainer(model=model, args=args, train_dataset=ds).train()
print("✅ reached end of script")  # never printed – hangs first
```
</details>

Run with:

```bash
accelerate launch \
  --config_file accelerate_fsdp.yaml \
  fsdp_hang_minimal.py
```

and an `accelerate_fsdp.yaml` like:

```yaml
compute_environment: LOCAL_MACHINE
debug: true
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false 
```

Environment summary  
• PyTorch 2.1.2 + CUDA 12.1 • Accelerate 0.27.2 • Transformers 4.39.1  
• 2 × H100 80 GB • Driver 535.xx / NCCL 2.18 • Ubuntu 22.04

---

### Error Trace
```shell
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:43<00:00, 14.22s/it]in oss file
[rank1]:[E616 13:41:10.909476913 ProcessGroupNCCL.cpp:565] [Rank 1] Watchdog caught collective operatMERS_CACHE` is deprecated and will be removed in v5 of Transformion timeout: WorkNCCL(SeqNum=2109, OpType=_ALLGATHER_BASE, NumelIn=262711296, NumelOut=525422592, Timeout(ms)=1800000) ran for 1800007 milliseconds before timing out.
[rank1]:[E616 13:41:10.911168570 ProcessGroupNCCL.cpp:628] [Rank 1] Work WorkNCCL(SeqNum=2109, OpTypeMERS_CACHE` is deprecated and will be removed in v5 of Transform=_ALLGATHER_BASE, NumelIn=262711296, NumelOut=525422592, Timeout(ms)=1800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank0]:[E616 13:41:10.040935704 ProcessGroupNCCL.cpp:565] [Rank 0] Watchdog caught collective operatMERS_CACHE` is deprecated and will be removed in v5 of Transformion timeout: WorkNCCL(SeqNum=2109, OpType=_ALLGATHER_BASE, NumelIn=40960, NumelOut=81920, Timeout(ms)=1800000) ran for 1800000 milliseconds before timing out.
[rank0]:[E616 13:41:10.043090898 ProcessGroupNCCL.cpp:628] [Rank 0] Work WorkNCCL(SeqNum=2109, OpType=_ALLGATHER_BASE, NumelIn=40960, NumelOut=81920, Timeout(ms)=1800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).                                                                                                                                            
[rank0]:[E616 13:41:11.524624994 ProcessGroupNCCL.cpp:579] [Rank 0] Some NCCL operations have failed                                                                 or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on                                                                 corrupted/incomplete data.                                                                           ██████████████████████████████████| 3/3 [00:43<00:00, 14.22s/it]
[rank0]:[E616 13:41:11.524652414 ProcessGroupNCCL.cpp:585] [Rank 0] To avoid data inconsistency, we are taking the entire process down.                                                                   ion timeout: WorkNCCL(SeqNum=2109, OpType=_ALLGATHER_BASE, Numel
[rank0]:[E616 13:41:11.526315737 ProcessGroupNCCL.cpp:1606] [PG 0 Rank 0] Timeout at NCCL work: 2109,. last enqueued NCCL work: 2109, last completed NCCL work: 2108.                                      =_ALLGATHER_BASE, NumelIn=262711296, NumelOut=525422592, Timeout
[rank0]:[E616 13:41:11.526355337 ProcessGroupNCCL.cpp:579] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on ion timeout: WorkNCCL(SeqNum=2109, OpType=_ALLGATHER_BASE, Numelcorrupted/incomplete data.
ERROR:root:Command failed: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=210=_ALLGATHER_BASE, NumelIn=40960, NumelOut=81920, Timeout(ms)=1809, OpType=_ALLGATHER_BASE, NumelIn=40960, NumelOut=81920, Timeout(ms)=1800000) ran for 1800000 milliseconds before timing out.                                                                            or timed out. Due to the asynchronous nature of CUDA kernels, su
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [30:51<00:00, 617.30s/it]                                     re taking the entire process down.
[rank1]:[E616 13:41:13.484234334 ProcessGroupNCCL.cpp:579] [Rank 1] Some NCCL operations have failed  last enqueued NCCL work: 2109, last completed NCCL work: 2108.or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on or timed out. Due to the asynchronous nature of CUDA kernels, sucorrupted/incomplete data.
[rank1]:[E616 13:41:13.484263574 ProcessGroupNCCL.cpp:585] [Rank 1] To avoid data inconsistency, we a9, OpType=_ALLGATHER_BASE, NumelIn=40960, NumelOut=81920, Timeoure taking the entire process down.
[rank1]:[E616 13:41:13.486090785 ProcessGroupNCCL.cpp:1606] [PG 0 Rank 1] Timeout at NCCL work: 2109,█████████████████████████████████| 3/3 [30:51<00:00, 617.30s/it] last enqueued NCCL work: 2109, last completed NCCL work: 2108.                                      or timed out. Due to the asynchronous nature of CUDA kernels, su
[rank1]:[E616 13:41:13.486126575 ProcessGroupNCCL.cpp:579] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on re taking the entire process down.corrupted/incomplete data.                                                                            last enqueued NCCL work: 2109, last completed NCCL work: 2108.
ERROR:root:Command failed: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=210or timed out. Due to the asynchronous nature of CUDA kernels, su9, OpType=_ALLGATHER_BASE, NumelIn=262711296, NumelOut=525422592, Timeout(ms)=1800000) ran for 1800007 milliseconds before timing out.   
```

### Expected

Ranks consolidate and write the checkpoint without timing out.

### Actual

Process blocks during state-dict consolidation, then watchdog kills the PG.

Any pointers or diagnostics I could run to help nail this down would be hugely appreciated!

Thanks 🙏

**Comment by sasakiyori** [comment]
I met the same issue when finetuning `Qwen2.5-7B-Instruct` with `SFTTrainer` and `LoRA` (Accelerate + FSDP), but `Qwen2.5-0.5B-Instruct` works well. And worked around by the closed pr https://github.com/pytorch/pytorch/pull/143540. 
Sadly I have no enough knowledge to figure out the root cause.
