### ISSUE TITLE
[inductor][cpu]text-classification+albert-base-v1 failure in prepare_pt2e

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#143621]
### 🐛 Describe the bug

After changing to torch.export.export_for_training from capture_pre_autograd_graph, the following failure occurs.
```
Traceback (most recent call last):
  File "/workspace/pytorch/./transformers/examples/pytorch/text-classification/run_glue.py", line 652, in <module>
    main()
  File "/workspace/pytorch/./transformers/examples/pytorch/text-classification/run_glue.py", line 590, in main
    metrics = trainer.evaluate(eval_dataset=eval_dataset)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3109, in evaluate
    output = eval_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3237, in evaluation_loop
    else self.accelerator.prepare_model(model, evaluation_mode=True)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1457, in prepare_model
    prepared_model = prepare_pt2e(exported_model, quantizer)
  File "/workspace/pytorch/torch/ao/quantization/quantize_pt2e.py", line 97, in prepare_pt2e
    quantizer.annotate(model)
  File "/workspace/pytorch/torch/ao/quantization/quantizer/x86_inductor_quantizer.py", line 705, in annotate
    self._annotate_with_config(
  File "/workspace/pytorch/torch/ao/quantization/quantizer/x86_inductor_quantizer.py", line 738, in _annotate_with_config
    self._annotate_linear_fusion_pattern(model, quantization_config, filter_fn)
  File "/workspace/pytorch/torch/ao/quantization/quantizer/x86_inductor_quantizer.py", line 1022, in _annotate_linear_fusion_pattern
    self._annotate_linear_binary_unary(model, quantization_config, filter_fn)
  File "/workspace/pytorch/torch/ao/quantization/quantizer/x86_inductor_quantizer.py", line 1527, in _annotate_linear_binary_unary
    linear_node, binary_node = self._get_output_nodes_of_partitions(
  File "/workspace/pytorch/torch/ao/quantization/quantizer/x86_inductor_quantizer.py", line 646, in _get_output_nodes_of_partitions
    raise ValueError("Input partition has more than one output node")
ValueError: Input partition has more than one output node
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/pytorch/numa_launcher.py", line 805, in <module>
    main()
  File "/workspace/pytorch/numa_launcher.py", line 800, in main
    launcher.launch(args)
  File "/workspace/pytorch/numa_launcher.py", line 481, in launch
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd_s)
subprocess.CalledProcessError: Command 'numactl -C 0-31 -m 0 /opt/conda/bin/python -u ./transformers/examples/pytorch/text-classification/run_glue.py --model_name_or_path albert-base-v1 --task_name MRPC --do_eval --max_seq_length 16 --learning_rate 2e-5 --overwrite_output_dir --output_dir /tmp/tmp_huggingface/ --torch_compile --torch_compile_quant ptq_dynamic --report_to=none --per_device_eval_batch_size 64' returned non-zero exit status 1.
```
this error can be reproduced with following cmd after install pytorch:
```
git clone -b test https://github.com/zxd1997066/transformers --depth=1 && cd transformers && \
    python setup.py bdist_wheel && pip install --force-reinstall dist/*.whl && cd ..
git clone -b test https://github.com/zxd1997066/accelerate.git && cd accelerate && \
    python setup.py bdist_wheel && pip install --no-deps --force-reinstall dist/*.whl && cd ..
pip install -r transformers/examples/pytorch/text-classification/requirements.txt
wget https://github.com/chuanqi129/inductor-tools/raw/xiangdong/accuracy/scripts/modelbench/quant/numa_launcher.py
wget https://github.com/chuanqi129/inductor-tools/raw/xiangdong/accuracy/scripts/modelbench/quant/hf_quant_test.sh
bash hf_quant_test.sh key torch_compile_quant
```
torch.export.export_for_training is using here https://github.com/zxd1997066/accelerate/blob/test/src/accelerate/accelerator.py#L1450

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Branch</th>
      <th>Target commit</th>
      <th>Refer commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>nightly</td>
      <td>a5fc054</td>
      <td>aa019ef</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>nightly</td>
      <td>a6b0a14</td>
      <td>332760d</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>nightly</td>
      <td>b0ebddc</td>
      <td>b0ebddc</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>nightly</td>
      <td>d23a6e1</td>
      <td>d23a6e1</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>nightly</td>
      <td>11bb5b8</td>
      <td>11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>fea73cb</td>
      <td>fea73cb</td>
    </tr>
  </tbody>
</table>

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @msaroufim @chuanqi129

**Comment by Xia-Weiwen** [comment]
This problem is caused by the inconsistent behavior of `capture_pre_autograd_graph` and `torch.export.export_for_training(...).module()`.
The 12 layers of Albert model share the same weight and bias, i.e., layer 1, 2, ..., 11 all use the weights and biases of layer 0.
With `capture_pre_autograd_graph`, the exported graph will have patterns like:
```
    _param_constant19_11 = self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight
    _param_constant20_11 = self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias
    linear_72 = torch.ops.aten.linear.default(gelu_11, _param_constant19_11, _param_constant20_11);  gelu_11 = _param_constant19_11 = _param_constant20_11 = None
```
The shared weight and bias are used via their aliases so this pattern (partition) has only one output, which is the linear node.
But with `torch.export.export_for_training(...).module()`, the pattern is:
```
    linear_72 = torch.ops.aten.linear.default(gelu_11, albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight, albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias);  gelu_11 = albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight = albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias = None
```
It uses the shared weight and bias directly without aliasing. Therefore, the pattern has three outputs, which are linear, the shared weight and bias.
When annotating the graph for quantization, we assert a matched partition has only one output, otherwise we don't know which one is what we want. So, the failure occurs with the `torch.export.export_for_training(...).module()`.

We need `torch.export.export_for_training(...).module()` to behave the same as `capture_pre_autograd_graph`.

@yushangdi @gmagogsfm Since your PR https://github.com/pytorch/pytorch/pull/143426 removed `capture_pre_autograd_graph`, could you please take a look and fix the issue with `export_for_training`? Thanks.

**Comment by yushangdi** [comment]
https://github.com/pytorch/pytorch/pull/142446 should probably solve this, but I need more testing. Taking a look.

**Comment by Xia-Weiwen** [comment]
@yushangdi Sounds good. Thanks. BTW, I was talking about aliasing, not making copies of parameters. Anyway, if parameters are excluded from outputs, the issue should be solved.

**Comment by yushangdi** [comment]
> @yushangdi Sounds good. Thanks. BTW, I was talking about aliasing, not making copies of parameters. Anyway, if parameters are excluded from outputs, the issue should be solved.

@Xia-Weiwen  Thanks! I'll probably land this after the code freeze period ends (about next week). 

Just want to double-check, what do you mean by "aliasing, not making copies of parameters"? If we are not making copies of parameters (which is the expected behavior), we'll have to alias the parameter when using it?

**Comment by Xia-Weiwen** [comment]
> Just want to double-check, what do you mean by "aliasing, not making copies of parameters"? If we are not making copies of parameters (which is the expected behavior), we'll have to alias the parameter when using it?

Yes. If I understand it correctly, the old way (`capture_pre_autograd_graph`) uses aliases of shared parameters for each call to `linear`. The pattern I saw is like below with `capture_pre_autograd_graph`:
```
    _param_constant19_11 = self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight
    _param_constant20_11 = self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias
    linear_72 = torch.ops.aten.linear.default(gelu_11, _param_constant19_11, _param_constant20_11);  gelu_11 = _param_constant19_11 = _param_constant20_11 = None
```
`self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight` and `self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias` are parameters, and `_param_constant19_11` and `_param_constant20_11` are aliases. When calling `linear`, aliases are used.

**Comment by yushangdi** [comment]
> Yes. If I understand it correctly, the old way (`capture_pre_autograd_graph`) uses aliases of shared parameters for each call to `linear`. The pattern I saw is like below with `capture_pre_autograd_graph`:
> 
> ```
>     _param_constant19_11 = self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight
>     _param_constant20_11 = self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias
>     linear_72 = torch.ops.aten.linear.default(gelu_11, _param_constant19_11, _param_constant20_11);  gelu_11 = _param_constant19_11 = _param_constant20_11 = None
> ```
> 
> `self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight` and `self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_bias` are parameters, and `_param_constant19_11` and `_param_constant20_11` are aliases. When calling `linear`, aliases are used.

@Xia-Weiwen oh, I would argue that the new export_for_training is also using aliasing. We just changed the names. 

The node `self.albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight` in the old graph is exactly the same as the `self.albert_encoder_albert_layer.groups_0.albert_layers.0.ffn.output.weight` node (or something similar) in the new graph. We just named the state_dict entries differently. 

Before, the state_dict entry's name is `albert_encoder_albert_layer_groups_0_albert_layers_0_ffn_output_weight`, now we changed it to `albert_encoder_albert_layer.groups_0.albert_layers.0.ffn.output.weight` to match the eager behavior.

**Comment by Xia-Weiwen** [comment]
I see. Thanks. So, the difference is that `capture_pre_autograd_graph` creates an alias of parameter for every call of `linear` while `export_for_training` uses the same alias for all calls.

**Comment by yushangdi** [comment]
@Xia-Weiwen  fyi the fix https://github.com/pytorch/pytorch/pull/142446 has landed. Please let me know if it doesn't fix your issue.

**Comment by Xia-Weiwen** [comment]
> @Xia-Weiwen fyi the fix #142446 has landed. Please let me know if it doesn't fix your issue.

Thanks

**Comment by Xia-Weiwen** [comment]
Hi @zxd1997066 could you please verify the fix? Thanks.

**Comment by zxd1997066** [comment]
The issue is fixed.
