### ISSUE TITLE
[ROCm] [APU] ClipVision stuck with MIOpen ‘‘internal’’ bugs somewhy

### ISSUE THREAD

**Issue by KISSEsWHISPERsFEEtBACKHUGs** [pytorch/pytorch#143734]
```
CLIPVisionEncode
miopenStatusInternalError
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/MLOpen/src/gemm_v2.cpp:920: rocBlas error encountered
!!! Exception during processing !!! miopenStatusInternalError
Traceback (most recent call last):
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/nodes.py", line 985, in encode
    output = clip_vision.encode_image(image, crop=crop_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_vision.py", line 62, in encode_image
    out = self.model(pixel_values=pixel_values, intermediate_output=-2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_model.py", line 216, in forward
    x = self.vision_model(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_model.py", line 195, in forward
    x = self.embeddings(pixel_values)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_model.py", line 168, in forward
    embeds = self.patch_embedding(pixel_values).flatten(2).transpose(1, 2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/ops.py", line 96, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/ops.py", line 92, in forward_comfy_cast_weights
    return self._conv_forward(input, weight, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: miopenStatusInternalError

fatal: No names found, cannot describe anything.
```
### Reproductions,
(1) Download & run this workflow for Comfy on your AMD APU HW system. https://pastebin.com/qfKUrJc9, with downloading Shutt1eMix and Shutt1e3D Official SFT ckpt model images (CivitAI) onto `$COMFY_ROOT/models/unet`, and Comfy’s ClipVisionG (HF) onto `$COMFY_ROOT/models/clip_vision`,
(2) Look at ClipVision portrait wallpaper encode phase if MIOpen bugs are,
(3) Workflow previews and demonstraitions of errors in pink,
![spectac1e 110301 122324](https://github.com/user-attachments/assets/51755c3c-5e5e-46fd-9c83-e2ce890c8c3b)
### HW
AMD Zen2 R4750G APU (HSA 9.0.0) × 14.9GiB UniVRAM’s with OpenCL-ROCm 6.3.0

_Originally posted by @KISSEsWHISPERsFEEtBACKHUGs in https://github.com/pytorch/pytorch/issues/60477#issuecomment-2558822920_

**Comment by naromero77amd** [comment]
Do you still get this error when you omit all these additional AMD/HIP environment variables?
```
        PYTORCH_HIP_MEM_ALLOC=strict PYTORCH_NO_HIP_MEMORY_CACHING=1 AMD_SERIALIZE_KERNEL=3 TORCH_USE_HIP_DSA=1 \
        HSA_ENABLE_SDMA=0 HSA_ENABLE_INTERRUPT=0 AMD_LOG_LEVEL=1 AMD_LOG_MASK=0x1 HIP_LAUNCH_BLOCKING=0 GPU_DUMP_CODE_OBJECT=0 AMD_SERIALIZE_COPY=3 AMD_KERNEL_DISPATCH=1 GPU_MAX_HW_QUEUES=0 \
        HIP_HIDDEN_FREE_MEM=16384
```

**Comment by naromero77amd** [comment]
Just checking in to see if you had a chance to try the last suggestion.

**Comment by naromero77amd** [comment]
@AI-JUNAITa
