### ISSUE TITLE
[distributed] parallelize_module error with `SequenceParallel`

### ISSUE THREAD

**Issue by gameofdimension** [pytorch/pytorch#143969]
### 🐛 Describe the bug

repro code:

run with `torchrun --nproc-per-node=8 --local-ranks-filter=1 -m t2i.bad_match`

```python
import os
from typing import Optional, Tuple

import torch
import torch.distributed as dist
from torch import nn
from torch.distributed.device_mesh import init_device_mesh
from torch.distributed.tensor.parallel import (SequenceParallel,
                                               parallelize_module)


def cleanup():
    dist.destroy_process_group()


def init_distributed():

    # Initializes the distributed backend
    # which will take care of sychronizing nodes/GPUs
    dist_url = "env://"  # default

    # only works with torch.distributed.launch // torch.run
    rank = int(os.environ["RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    local_rank = int(os.environ["LOCAL_RANK"])

    # this will make all .cuda() calls work properly
    torch.cuda.set_device(local_rank)

    dist.init_process_group(
        backend="nccl", init_method=dist_url, world_size=world_size, rank=rank,
        device_id=torch.device(f"cuda:{torch.cuda.current_device()}"),
    )

    # synchronizes all the threads to reach this point before moving on
    dist.barrier()
    return world_size, rank, local_rank


class AdaLayerNormZeroSingle(nn.Module):
    def __init__(self, embedding_dim: int, norm_type="layer_norm", bias=True):
        super().__init__()
        self.linear = nn.Linear(embedding_dim, 3 * embedding_dim, bias=bias)
        self.norm = nn.LayerNorm(embedding_dim, elementwise_affine=False, eps=1e-6)

    def forward(
        self,
        x: torch.Tensor,
        emb: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        pass


class FluxSingleTransformerBlock(nn.Module):
    def __init__(self, dim, mlp_ratio=4.0):
        super().__init__()
        self.mlp_hidden_dim = int(dim * mlp_ratio)
        self.norm = AdaLayerNormZeroSingle(dim)

    def forward(
        self,
        hidden_states: torch.FloatTensor,
    ):
        pass


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.block = FluxSingleTransformerBlock(
            dim=3072,
        )

    def forward(
        self,
        hidden_states: torch.FloatTensor,
    ):
        return self.block(hidden_states)


def main():
    init_distributed()
    mesh = init_device_mesh(
        "cuda", (dist.get_world_size(), ))
    model = Model()
    parallelize_module(
        model.block, mesh, parallelize_plan={
            "norm.norm": SequenceParallel(
                use_local_output=True,
            ),
        }
    )
    cleanup()


if __name__ == "__main__":
    main()
```

error

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/home/pagoda/t2i/bad_match.py", line 70, in <module>
[rank1]:     main()
[rank1]:   File "/home/pagoda/t2i/bad_match.py", line 59, in main
[rank1]:     parallelize_module(
[rank1]:   File "/home/pagoda/venv/lib/python3.11/site-packages/torch/distributed/tensor/parallel/api.py", line 112, in parallelize_module
[rank1]:     parallelize_module(submodule, device_mesh, parallelize_style)
[rank1]:   File "/home/pagoda/venv/lib/python3.11/site-packages/torch/distributed/tensor/parallel/api.py", line 85, in parallelize_module
[rank1]:     return parallelize_plan._apply(module, device_mesh)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/pagoda/venv/lib/python3.11/site-packages/torch/distributed/tensor/parallel/style.py", line 368, in _apply
[rank1]:     return distribute_module(
[rank1]:            ^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/pagoda/venv/lib/python3.11/site-packages/torch/distributed/tensor/_api.py", line 852, in distribute_module
[rank1]:     partition_fn(name, submod, device_mesh)
[rank1]:   File "/home/pagoda/venv/lib/python3.11/site-packages/torch/distributed/tensor/parallel/style.py", line 341, in _replicate_module_fn
[rank1]:     module.register_parameter(p_name, replicated_param)
[rank1]:   File "/home/pagoda/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 604, in register_parameter
[rank1]:     raise KeyError('parameter name can\'t contain "."')
[rank1]: KeyError: 'parameter name can\'t contain "."'
```

### Versions

```
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.9 (main, May 14 2024, 09:36:59) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.0-136.36.0.112.4.oe2203sp1.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 535.161.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz
Stepping:                        6
CPU MHz:                         2800.001
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4400.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[pip3] triton==3.1.0
[conda] Could not collect
```

**Comment by gameofdimension** [comment]
if we just change the name as below, it will ok. so it seems that matched the wrong module

```diff
diff --git a/t2i/bad_match.py b/t2i/bad_match.py
index 189eaac..80f051e 100644
--- a/t2i/bad_match.py
+++ b/t2i/bad_match.py
@@ -55,7 +55,7 @@ class FluxSingleTransformerBlock(nn.Module):
     def __init__(self, dim, mlp_ratio=4.0):
         super().__init__()
         self.mlp_hidden_dim = int(dim * mlp_ratio)
-        self.norm = AdaLayerNormZeroSingle(dim)
+        self.norm1 = AdaLayerNormZeroSingle(dim)
 
     def forward(
         self,
@@ -85,7 +85,7 @@ def main():
     model = Model()
     parallelize_module(
         model.block, mesh, parallelize_plan={
-            "norm.norm": SequenceParallel(
+            "norm1.norm": SequenceParallel(
                 use_local_output=True,
             ),
         }
```

**Comment by awgu** [comment]
I think @kwen2501 was the one who most recently changed this logic in https://github.com/pytorch/pytorch/pull/122968.

It looks like the logic does not support the `norm.norm` matching correctly:
https://github.com/pytorch/pytorch/blob/dca443835e574e02ffdfda5b5c5e9bdcc9c9bcad/torch/distributed/tensor/parallel/api.py#L81-L106

- `path_splits` starts as `["norm", "norm"]`.
- On the second `"norm"` in the list (first `"norm"` has been popped and processed already), `matched_children` matches against `norm: AdaLayerNormZeroSingle` _again_. Then, since `path_splits` is now empty, the code falls into the `else` base-case branch that calls `parallelize_module(submodule, ddevice_mesh, parallelize_style)` directly on `norm: AdaLayerNormZeroSingle`.

Since @kwen2501 will be out for a few weeks, @tianyu-l or @wanchaol do you want to take a closer look and see what the preferred solution is?

**Comment by gameofdimension** [comment]
i don't understand why we need while loop (line 87) here, shouldn't we consume one segment of the path, just go one level deeper of the module hierarchy by the recursive calling?

**Comment by asahni04** [comment]
hi so what's the solution for this? other than renaming?

**Comment by a-r-r-o-w** [comment]
Gentle bump (facing the same error as well with a different diffusers model implementation containing `norm.norm`)

**Comment by tianyu-l** [comment]
@kwen2501 do you mind taking a look?
