### ISSUE TITLE
[DCP] dcp.load leads to param type mismatch.

### ISSUE THREAD

**Issue by nanlliu** [pytorch/pytorch#143972]
### 🐛 Describe the bug

I tried to load a dcp saved checkpoint on a single GPU.

However, when I loaded optimizer state using  `set_optimizer_state_dict` and it led to following error:

I'd expect `BytesStorageMetadata` is the same as`torch.distributed.checkpoint.metadata.BytesStorageMetadata`?

```
CheckpointException: CheckpointException ranks:dict_keys([0])
Traceback (most recent call last): (RANK 0)
  File "/mnt/filestore/users/nan/.venv/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 164, in reduce_scatter
    local_data = map_fun()
  File "/mnt/filestore/users/nan/.venv/lib/python3.10/site-packages/torch/distributed/checkpoint/logger.py", line 83, in wrapper
    result = func(*args, **kwargs)
  File "/mnt/filestore/users/nan/.venv/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_loader.py", line 211, in local_step
    local_plan = planner.create_local_plan()
  File "/mnt/filestore/users/nan/.venv/lib/python3.10/site-packages/torch/distributed/checkpoint/default_planner.py", line 233, in create_local_plan
    return create_default_local_load_plan(
  File "/mnt/filestore/users/nan/.venv/lib/python3.10/site-packages/torch/distributed/checkpoint/default_planner.py", line 365, in create_default_local_load_plan
    requests += _create_read_items(fqn, md, obj)
  File "/mnt/filestore/users/nan/.venv/lib/python3.10/site-packages/torch/distributed/checkpoint/planner_helpers.py", line 269, in _create_read_items
    raise ValueError(
ValueError: Invalid checkpoint metadata for opt_state.param_groups.0.weight_decay, expected BytesStorageMetadata but found <class 'torch.distributed.checkpoint.metadata.BytesStorageMetadata'>
...
[rank0]: ValueError: Invalid checkpoint metadata for opt_state.param_groups.0.lr, expected BytesStorageMetadata but found <class 'torch.distributed.checkpoint.metadata.TensorStorageMetadata'>
```

### Versions

[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] open_clip_torch==2.28.0
[pip3] optree==0.13.1
[pip3] pytorch-labs-segment-anything-fast==0.2
[pip3] torch==2.5.0
[pip3] torch_scatter==2.1.2.dev4
[pip3] torch-tb-profiler==0.4.3
[pip3] torchao==0.6.1
[pip3] torchaudio==2.5.0
[pip3] torchinfo==1.8.0
[pip3] torchmetrics==1.6.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.20.0
[pip3] triton==3.1.0

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC @pradeepfn

**Comment by nanlliu** [comment]
https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/planner_helpers.py#L266-L274
```python
def _create_read_items(fqn: str, md: STORAGE_TYPES, obj: Any) -> List[ReadItem]:
    if not isinstance(md, BytesStorageMetadata):
        try:
            local_chunks = _create_chunk_list(obj)
        except ValueError as ex:
            raise ValueError(
                f"Invalid checkpoint metadata for {fqn}, "
                + f"expected BytesStorageMetadata but found {type(md)}",
            ) from ex
```

if statement already checks the `md` isn't `BytesStorageMetadata` but then why does exception expects `BytesStorageMetadata`.

**Comment by nanlliu** [comment]
The issue is that
`metadata` for `lr` is tensor while `lr` is a float value. hope this can help you guys fix this minor issue.

**Comment by wanchaol** [comment]
Thanks for the issue @nanlliu! So it has already been fixed on your side?

**Comment by nanlliu** [comment]
> Thanks for the issue @nanlliu! So it has already been fixed on your side?

yes its fixed on my end!
