### ISSUE TITLE
pytorch with xpu support fails to eval pre trained models

### ISSUE THREAD

**Issue by farooqkz** [pytorch/pytorch#143996]
### 🐛 Describe the bug

I have installed pytorch as written here(the preview build): https://pytorch.org/docs/main/notes/get_start_xpu.html

Then I'm trying the first example code from the same page:

```
import torch
import torchvision.models as models

model = models.resnet50(weights="ResNet50_Weights.DEFAULT")
model.eval()
data = torch.rand(1, 3, 224, 224)

model = model.to("xpu")
data = data.to("xpu")

with torch.no_grad():
    model(data)

print("Execution finished")
```

It fails:

```
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: libze_tracing_layer.so.1
Traceback (most recent call last):
  File "/home/farooqkz/py/intel_xpu_test.py", line 12, in <module>
    model(data)
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
        ^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farooqkz/.local/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: could not create an engine
```

### Versions

```
Collecting environment information...
PyTorch version: 2.5.1+xpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux trixie/sid (x86_64)
GCC version: (Debian 14.2.0-8) 14.2.0
Clang version: 19.1.5 (1)
CMake version: version 3.31.2
Libc version: glibc-2.40

Python version: 3.12.8 (main, Dec 13 2024, 13:19:48) [GCC 14.2.0] (64-bit runtime)
Python platform: Linux-6.10.9-amd64-x86_64-with-glibc2.40
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               24
On-line CPU(s) list:                  0-23
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen 9 3900X 12-Core Processor
CPU family:                           23
Model:                                113
Thread(s) per core:                   2
Core(s) per socket:                   12
Socket(s):                            1
Stepping:                             0
Frequency boost:                      enabled
CPU(s) scaling MHz:                   85%
CPU max MHz:                          4919.0000
CPU min MHz:                          550.0000
BogoMIPS:                             8000.30
[DELETED]

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnxruntime==1.20.0
[pip3] optree==0.13.1
[pip3] pytorch-triton-xpu==3.1.0+91b14bf559
[pip3] torch==2.5.1+xpu
[pip3] torch-geometric==2.6.1
[pip3] torchaudio==2.5.1+xpu
[pip3] torchvision==0.20.1+xpu
[conda] Could not collect
```

Also:

```
farooqkz@darthryzen:~/py$ uname -a
Linux darthryzen 6.10.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.9-1 (2024-09-08) x86_64 GNU/Linux
```

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by huiyan2021** [comment]
The OS version is Debian 6.10.9-1, I am not sure whether you are able to install the driver accordingly from here: [PyTorch Installation Prerequisites for Intel GPUs](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpus.html?__hstc=132719121.49f9942070b4b0aeddca536d5118605c.1725591756297.1735550388091.1735606420721.106&__hssc=132719121.2.1735606420721&__hsfp=3810185348), and did you check the availability for Intel GPU after installation?
![image](https://github.com/user-attachments/assets/5cbe8c62-7f1f-40f3-92db-74d7a438106d)

**Comment by EikanWang** [comment]
@farooqkz , May I know your GPU type? Is it iGPU?

**Comment by EikanWang** [comment]
Meanwhile, @farooqkz , could you help run the code as follows and paste the output here?

```python
import torch
cur_xpu_device = torch.device("xpu")
torch.xpu.get_device_properties(cur_xpu_device)
```

**Comment by farooqkz** [comment]
> Hi @farooqkz , seems there is a link issue on https://pytorch.org/docs/main/notes/get_start_xpu.html. `PyTorch Installation Prerequisites for Intel GPUs` links to the prerequisites for 2.6, we are working on fixing it.
> 
> If you have installed the prerequisites for 2.6, please try nightly wheels and see if the issue still exists. Thanks!
> 
> ```
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/xpu
> ```

It is still there.

@EikanWang 

```
_XpuDeviceProperties(name='Intel(R) Arc(TM) A380 Graphics', platform_name='Intel(R) oneAPI Unified Runtime over Level-Zero', type='gpu', driver_version='1.5.30872', total_memory=5783MB, max_compute_units=128, gpu_eu_count=128, gpu_subslice_count=8, max_work_group_size=1024, max_num_sub_groups=128, sub_group_sizes=[8 16 32], has_fp16=1, has_fp64=0, has_atomic64=1)
```

**Comment by ekaakurniawan** [comment]
@farooqkz, Debian OS may not be supported. Could you share the clinfo result?
```
$ sudo apt-get install clinfo
$ clinfo
```

Please also try the following package.
```
$ pip install torch==2.6 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/xpu
```

And the following command.
```
import torch
from torch.nn import functional as F, init
data = torch.rand(1, 3, 224, 224)
print(F.conv2d(data, data).to("xpu"))
```

The expected result.
```
tensor([[[[50140.6562]]]], device='xpu:0')
```

**Comment by farooqkz** [comment]
> @farooqkz, Debian OS may not be supported. Could you share the clinfo result?
> 
> ```
> $ sudo apt-get install clinfo
> $ clinfo
> ```


```
Number of platforms                               2
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 24.2.8-1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   rusticl
  Platform Vendor                                 Mesa/X.org
  Platform Version                                OpenCL 3.0 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_byte_addressable_store cl_khr_create_command_queue cl_khr_expect_assume cl_khr_extended_versioning cl_khr_icd cl_khr_il_program cl_khr_spirv_no_integer_wrap_decoration cl_khr_suggested_local_work_size
  Platform Extensions with Version                cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_create_command_queue                                      0x400000 (1.0.0)
                                                  cl_khr_expect_assume                                             0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)
                                                  cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_khr_il_program                                                0x400000 (1.0.0)
                                                  cl_khr_spirv_no_integer_wrap_decoration                          0x400000 (1.0.0)
                                                  cl_khr_suggested_local_work_size                                 0x400000 (1.0.0)
  Platform Numeric Version                        0xc00000 (3.0.0)
  Platform Extensions function suffix             MESA
  Platform Host timer resolution                  1ns

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD CEDAR (DRM 2.50.0 / 6.10.9-amd64, LLVM 19.1.4)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 24.2.8-1
  Device Numeric Version                          0x401000 (1.1.0)
  Driver Version                                  24.2.8-1
  Device OpenCL C Version                         OpenCL C 1.1 
  Device OpenCL C Numeric Version                 0x401000 (1.1.0)
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Max compute units                               2
  Max clock frequency                             650MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple (kernel)     32
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 0        (n/a)
    float                                                4 / 4       
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           536870912 (512MiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     15
  Max constant buffer size                        536870912 (512MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    ILs with version                              (n/a)
  Built-in kernels with version                   (n/a)
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_extended_versioning
  Device Extensions with Version                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)

  Platform Name                                   rusticl
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContext(NULL, ...) [other]              <error: no devices in non-default plaforms>
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CEDAR (DRM 2.50.0 / 6.10.9-amd64, LLVM 19.1.4)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CEDAR (DRM 2.50.0 / 6.10.9-amd64, LLVM 19.1.4)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CEDAR (DRM 2.50.0 / 6.10.9-amd64, LLVM 19.1.4)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.3.2
  ICD loader Profile                              OpenCL 3.0
```

> Please also try the following package.
> 
> ```
> $ pip install torch==2.6 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/xpu
> ```
> 
> And the following command.
> 
> ```
> import torch
> from torch.nn import functional as F, init
> data = torch.rand(1, 3, 224, 224)
> print(F.conv2d(data, data).to("xpu"))
> ```
> 
> The expected result.
> 
> ```
> tensor([[[[50140.6562]]]], device='xpu:0')
> ```

```
RuntimeError: The program was built for 1 devices
Build program log for 'Intel(R) Arc(TM) A380 Graphics':
warning: module got recompiled from IR because provided native binary is incompatible with underlying device and/or driver [-Wrecompiled-from-ir]
```

By the way, I have 2 GPUs here. Does that have something to do with anything?

**Comment by ekaakurniawan** [comment]
@farooqkz , clinfo does not detect the Arc A380. Before this, the GPU driver has to be installed properly. Please help to check if the following driver status is active.

```
$ hwinfo --display
...
Driver Info #1
  Driver Status: i915 is active
...
```

If not, you may need to install the GPU driver. Since the official [PyTorch* Prerequisites for Intel® GPUs](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-6.html) is for Windows and Ubuntu only, you may want to start from the required Linux Kernel from the following link. It is version 6.2 for A380.

[Intel dGPU Docs - Supported Hardware](https://dgpu-docs.intel.com/devices/hardware-table.html)

I found the following as well. Hope it helps.

https://www.reddit.com/r/jellyfin/comments/10m17vs/intel_arc_a380_on_debiansid_linux_62/

**Comment by farooqkz** [comment]
> @farooqkz , clinfo does not detect the Arc A380. Before this, the GPU driver has to be installed properly. Please help to check if the following driver status is active.
> 
> ```
> $ hwinfo --display
> ...
> Driver Info #1
>   Driver Status: i915 is active
> ...
> ```
> 
> If not, you may need to install the GPU driver. Since the official [PyTorch* Prerequisites for Intel® GPUs](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-6.html) is for Windows and Ubuntu only, you may want to start from the required Linux Kernel from the following link. It is version 6.2 for A380.
> 
> [Intel dGPU Docs - Supported Hardware](https://dgpu-docs.intel.com/devices/hardware-table.html)
> 
> I found the following as well. Hope it helps.
> 
> https://www.reddit.com/r/jellyfin/comments/10m17vs/intel_arc_a380_on_debiansid_linux_62/

right. I will try to ask for help on some Linux forum and get back here when I have got the drivers installed.

**Comment by EikanWang** [comment]
Thanks @ekaakurniawan for the detailed explanation.

@farooqkz , by the way, do you mind share the device counter with us?

```python
import torch
print(torch.xpu.device_count())
```

If the device count is >1, could you share the device properties of each device?

```python
import torch
cur_xpu_device = torch.device("xpu:0")
torch.xpu.get_device_properties(cur_xpu_device)
```

```python
import torch
cur_xpu_device = torch.device("xpu:1")
torch.xpu.get_device_properties(cur_xpu_device)
```

**Comment by farooqkz** [comment]
Hello. Sorry for the late reply. I finally got it working on Debian. Will write a guide on this later.

**Comment by farooqkz** [comment]
Here:

https://forums.debian.net/viewtopic.php?p=815269#p815269

Closing as complete.
