### ISSUE TITLE
Missing error message related to malformed model parameters

### ISSUE THREAD

**Issue by justinkterry** [pytorch/pytorch#14396]
## 🐛 Bug

The attached code (if I didn't make a mistake) would implement a simple fully connected network to classify MNIST. Due to the mistake, I had an architecture that couldn't be run; nothing terribly interesting. However, when I ran it, the error went all the way to a relatively cryptic and unhelpful cuBLAS error. This error should've been handled internally in PyTorch with a useful error message that clearly says what's wrong instead.

justinkterry@Station:~/Dropbox/mnist/current/plain$ python3 adam.py
Traceback (most recent call last):
  File "adam.py", line 107, in <module>
    main()
  File "adam.py", line 98, in main
    train(model, device, train_loader, optimizer, epoch, log_interval)
  File "adam.py", line 33, in train
    output = model(data)
  File "/home/justinkterry/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "adam.py", line 22, in forward
    out = F.sigmoid(self.fc1(out))
  File "/home/justinkterry/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/justinkterry/miniconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 62, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/justinkterry/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1065, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [784 x 6000], m2: [784 x 1000] at /home/justinkterry/Documents/pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:271

[code.zip](https://github.com/pytorch/pytorch/files/2618093/code.zip)

 - PyTorch Version (e.g., 1.0): '0.5.0a0+c8b246a'
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): Source
 - Build command you used (if compiling from source): Default one in documentation, built into conda environment
 - Python version: 3.6
 - CUDA/cuDNN version: CUDA 9.2
 - GPU models and configuration: GTX 1080
 - Any other relevant information:

**Comment by ngimel** [comment]
Closing due to age
