### ISSUE TITLE
torch.multiprocessing.spawn should support spawning up processes 

### ISSUE THREAD

**Issue by teng-li** [pytorch/pytorch#14390]
When we have more than 1 dataloader workers, multiprocessing won't work

```
Traceback (most recent call last):
  File "/private/home/tengli/pytorch_fork_example/examples/imagenet/main.py", line 472, in <module>
    main()
  File "/private/home/tengli/pytorch_fork_example/examples/imagenet/main.py", line 133, in main
    args=(ngpus_per_node, args)
  File "/private/home/tengli/pytorch/torch/multiprocessing/spawn.py", line 154, in spawn
    while not spawn_context.join():
  File "/private/home/tengli/pytorch/torch/multiprocessing/spawn.py", line 103, in join
    raise Exception(msg)
Exception:

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/private/home/tengli/pytorch/torch/multiprocessing/spawn.py", line 11, in _wrap
    fn(i, *args)
  File "/private/home/tengli/pytorch_fork_example/examples/imagenet/main.py", line 273, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "/private/home/tengli/pytorch_fork_example/examples/imagenet/main.py", line 301, in train
    for i, (input, target) in enumerate(train_loader):
  File "/private/home/tengli/pytorch/torch/utils/data/dataloader.py", line 827, in __iter__
    return _DataLoaderIter(self)
  File "/private/home/tengli/pytorch/torch/utils/data/dataloader.py", line 561, in __init__
    w.start()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

**Comment by teng-li** [comment]
Good to close after the diff is landed

**Comment by teng-li** [comment]
We should also find a way to clean up the orphaned processes
