### ISSUE TITLE
Transfer Tutorial fails -- WARNING:root:Your model ir_version is higher than the checker's,...

### ISSUE THREAD

**Issue by tlc** [pytorch/pytorch#14493]
## 🐛 Bug
I followed the tutorial "Transfering a Model from PyTorch to Caffe2 and Mobile using ONNX" 
(https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html),
including building pytorch from source, and it failed with

```
$ python3 super_resolution_with_caffe2.py
WARNING:root:Your model ir_version is higher than the checker's, so it might not interpret the higher version correctly.
Input size 2 not in range [min=1, max=1].Traceback (most recent call last):
  File "super_resolution_with_caffe2.py", line 139, in <module>
    prepared_backend = onnx_caffe2.backend.prepare(model)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 439, in prepare
    super(Caffe2Backend, cls).prepare(model, device, **kwargs)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 154, in check_model
    check_graph(model.graph)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 127, in check_graph
    check_node(node)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 40, in check_node
    'NodeProto of type {} did not pass defs schema check.'.format(str(node.op_type)))
ValueError: NodeProto of type Reshape did not pass defs schema check.
```

## To Reproduce

1. Follow the tutorial.
2. Download the source file.
2. Run the program, `python3 super_resolution_with_caffe2.py`

```
$ python3 super_resolution_with_caffe2.py
WARNING:root:Your model ir_version is higher than the checker's, so it might not interpret the higher version correctly.
Input size 2 not in range [min=1, max=1].Traceback (most recent call last):
  File "super_resolution_with_caffe2.py", line 139, in <module>
    prepared_backend = onnx_caffe2.backend.prepare(model)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 439, in prepare
    super(Caffe2Backend, cls).prepare(model, device, **kwargs)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 154, in check_model
    check_graph(model.graph)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 127, in check_graph
    check_node(node)
  File "/home/tlc/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 40, in check_node
    'NodeProto of type {} did not pass defs schema check.'.format(str(node.op_type)))
ValueError: NodeProto of type Reshape did not pass defs schema check.
```

## Expected behavior

Functioning program.

## Environment

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.0.0a0+c32debb
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 980
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn_static_v6.a
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.13.1)
[pip3] torch (0.4.1)
[pip3] torchaudio (0.1)
[pip3] torchfile (0.1.0)
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] torch                     1.0.0a0+c32debb           <pip>
```

## Additional context

I got the same results with `CUDA_VISIBLE_DEVICES='' python super_resolution_with_caffe2.py`.

**Comment by tlc** [comment]
This was a problem with the tutorial and the tutorial has now been updated to 1.0.0.dev20181128 !  (Right after I figured it out.)

Now I'm hitting this issue:  https://github.com/pytorch/pytorch/issues/13836

**Comment by flankechen** [comment]
I have the same error, how did you fixed this? update to date web and code comes with the same error. [#13836](https://github.com/pytorch/pytorch/issues/13836) points out that some operations might be different from torch and caffe?
