### ISSUE TITLE
ROCm test intermittently fails with: libcaffe2_hip.so: undefined symbol: THCudaByteTensor_mode / THCudaTensor_indexSelect

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14495]
This failure occurs when compilation OOMs, but the OOM exit code is not propagated. "Resume build" will not fix errors like this, as resume build will reuse the (corrupted) build product.

----

I got this durably on a PR of mine (https://github.com/pytorch/pytorch/pull/14247 commit a643548); this test doesn't seem to fail on master all the time, but I did find the failure on one other PR: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/3885/console for https://github.com/pytorch/pytorch/pull/14482 (most other failures are the known SIGIOT problem)

Full error:

```
19:08:19 test_ByteTensor_mode (__main__.TestCuda) ... /usr/bin/python: symbol lookup error: /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libcaffe2_hip.so: undefined symbol: THCudaByteTensor_mode
19:08:19 Traceback (most recent call last):
19:08:19   File "test/run_test.py", line 431, in <module>
19:08:19     main()
19:08:19   File "test/run_test.py", line 423, in main
19:08:19     raise RuntimeError(message)
19:08:19 RuntimeError: test_cuda failed!
```

log: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/3874/console

**Comment by ezyang** [comment]
Another occurrence https://github.com/pytorch/pytorch/pull/14425 https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/3782/console

**Comment by ezyang** [comment]
It turns out, when this occurs,  it is because LLVM ran out of memory, but hcc failed to report the exit code correctly:

```
17:22:05   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:05                                                                       ^
17:22:05 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:05   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:05                                                                       ^~~~~
17:22:05                                                                       std::abs
17:22:05 1 warning generated.
17:22:05 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathPointwiseLong.cu.o
17:22:11 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMaskedInt.cu:1:
17:22:11 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCTensorMasked.cuh:7:
17:22:11 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCReduce.cuh:14:
17:22:11 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:11   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:11                                                                       ^
17:22:11 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:11   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:11                                                                       ^~~~~
17:22:11                                                                       std::abs
17:22:11 1 warning generated.
17:22:11 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathCompareLong.cu.o
17:22:13 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCTensorCopy.cu:3:
17:22:13 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:13   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:13                                                                       ^
17:22:13 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:13   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:13                                                                       ^~~~~
17:22:13                                                                       std::abs
17:22:13 1 warning generated.
17:22:13 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathReduceLong.cu.o
17:22:16 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathCompareInt.cu:1:
17:22:16 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathCompare.cuh:8:
17:22:16 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:16   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:16                                                                       ^
17:22:16 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:16   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:16                                                                       ^~~~~
17:22:16                                                                       std::abs
17:22:16 1 warning generated.
17:22:16 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMaskedLong.cu.o
17:22:22 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathPointwiseByte.cu:1:
17:22:22 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathPointwise.cuh:10:
17:22:22 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:22   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:22                                                                       ^
17:22:22 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:22   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:22                                                                       ^~~~~
17:22:22                                                                       std::abs
17:22:22 1 warning generated.
17:22:22 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorSortHalf.cu.o
17:22:29 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorSortInt.cu:1:
17:22:29 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorSort.cuh:8:
17:22:29 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCSortUtils.cuh:7:
17:22:29 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:29   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:29                                                                       ^
17:22:29 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:29   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:29                                                                       ^~~~~
17:22:29                                                                       std::abs
17:22:29 1 warning generated.
17:22:29 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathCompareTHalf.cu.o
17:22:30 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathReduceInt.cu:1:
17:22:30 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathReduce.cuh:7:
17:22:30 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:30   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:30                                                                       ^
17:22:30 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:30   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:30                                                                       ^~~~~
17:22:30                                                                       std::abs
17:22:30 1 warning generated.
17:22:30 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathPointwiseHalf.cu.o
17:22:47 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathCompareTInt.cu:1:
17:22:47 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathCompareT.cuh:8:
17:22:47 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:47   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:47                                                                       ^
17:22:47 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:47   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:47                                                                       ^~~~~
17:22:47                                                                       std::abs
17:22:47 1 warning generated.
17:22:47 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathCompareHalf.cu.o
17:22:55 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMaskedLong.cu:1:
17:22:55 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCTensorMasked.cuh:7:
17:22:55 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCReduce.cuh:14:
17:22:55 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:55   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:55                                                                       ^
17:22:55 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:55   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:55                                                                       ^~~~~
17:22:55                                                                       std::abs
17:22:55 1 warning generated.
17:22:55 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathReduceHalf.cu.o
17:22:57 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathPointwiseChar.cu:1:
17:22:57 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathPointwise.cuh:10:
17:22:57 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:57   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:57                                                                       ^
17:22:57 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:57   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:57                                                                       ^~~~~
17:22:57                                                                       std::abs
17:22:57 1 warning generated.
17:22:57 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMaskedHalf.cu.o
17:22:58 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathCompareLong.cu:1:
17:22:58 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathCompare.cuh:8:
17:22:58 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:22:58   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:58                                                                       ^
17:22:58 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:22:58   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:22:58                                                                       ^~~~~
17:22:58                                                                       std::abs
17:22:58 1 warning generated.
17:22:58 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorSortFloat.cu.o
17:23:12 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorMathReduceLong.cu:1:
17:23:12 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorMathReduce.cuh:7:
17:23:12 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:23:12   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:23:12                                                                       ^
17:23:12 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:23:12   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:23:12                                                                       ^~~~~
17:23:12                                                                       std::abs
17:23:12 1 warning generated.
17:23:12 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathCompareTFloat.cu.o
17:23:16 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/THCTensorSortLong.cu:1:
17:23:16 In file included from /var/lib/jenkins/workspace/aten/src/THC/generated/../THCTensorSort.cuh:8:
17:23:16 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCSortUtils.cuh:7:
17:23:16 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:23:16   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:23:16                                                                       ^
17:23:16 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:23:16   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:23:16                                                                       ^~~~~
17:23:16                                                                       std::abs
17:23:16 1 warning generated.
17:23:16 [ 62%] Building HIPCC object caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/generated/caffe2_hip_generated_THCTensorMathPointwiseFloat.cu.o
17:23:30 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCTensorMode.cu:15:
17:23:30 In file included from /var/lib/jenkins/workspace/aten/src/THC/THCTensorMode.cuh:5:
17:23:30 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
17:23:30   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:23:30                                                                       ^
17:23:30 /var/lib/jenkins/workspace/aten/src/THC/THCNumerics.cuh:208:71: note: use function 'std::abs' instead
17:23:30   static inline __host__ __device__ at::Half abs(at::Half a) { return ::abs(a); }
17:23:30                                                                       ^~~~~
17:23:30                                                                       std::abs
17:23:30 LLVM ERROR: out of memory
17:23:30 Stack dump:
17:23:30 0.Program arguments: /opt/rocm/hcc/bin/clang-7.0_original -cc1 -D__KALMAR_HC__=1 -D__HCC_HC__=1 -triple x86_64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -main-file-name THCTensorMode.cu -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/./caffe2_hip_generated_THCTensorMode.cu.gcno -resource-dir /opt/rocm/hcc/lib/clang/7.0.0 -I/opt/rocm/hcc/bin/../include -I/opt/rocm/hcc/bin/../hcc/include -D __HIPCC__ -I /opt/rocm/hcc/include -I /opt/rocm/hip/include/hip/hcc_detail/cuda -I /opt/rocm/hsa/include -I /opt/rocm/profiler/CXLActivityLogger/include -I /opt/rocm/hip/include -D HIP_VERSION_MAJOR=1 -D HIP_VERSION_MINOR=5 -D HIP_VERSION_PATCH=18435 -I /usr/include/x86_64-linux-gnu -I /usr/include/x86_64-linux-gnu/c++/4.2.1 -I /usr/include/c++/4.2.1 -D __HIP_PLATFORM_HCC__=1 -D CUDA_HAS_FP16=1 -D __HIP_NO_HALF_OPERATORS__=1 -D __HIP_NO_HALF_CONVERSIONS__=1 -D HIP_VERSION=1 -D CAFFE2_USE_MIOPEN -D ROCBLAS_FP16=0 -D NDEBUG -D ONNX_NAMESPACE=onnx_torch -D USE_GCC_ATOMICS=1 -D HAVE_MMAP=1 -D _FILE_OFFSET_BITS=64 -D HAVE_SHM_OPEN=1 -D HAVE_SHM_UNLINK=1 -D HAVE_MALLOC_USABLE_SIZE=1 -I /opt/rocm/hcc/include -I /opt/rocm/hsa/include -I /opt/rocm/rocrand/include -I /opt/rocm/hiprand/include -I /opt/rocm/rocblas/include -I /opt/rocm/miopen/include -I /opt/rocm/include -I /opt/rocm/include/thrust/system/cuda/detail/cub-hip -I /opt/rocm/hcc/include -I /opt/rocm/hsa/include -I /opt/rocm/rocrand/include -I /opt/rocm/hiprand/include -I /opt/rocm/rocblas/include -I /opt/rocm/miopen/include -I /opt/rocm/include -I /opt/rocm/include/thrust/system/cuda/detail/cub-hip -I /var/lib/jenkins/workspace/build/caffe2/aten/src/TH -I /var/lib/jenkins/workspace/aten/src/TH -I /var/lib/jenkins/workspace/aten/src/THC -I /var/lib/jenkins/workspace/build/caffe2/aten/src/THC -I /var/lib/jenkins/workspace/build/caffe2/aten/src/THC -I /var/lib/jenkins/workspace/aten/src/THC -I /var/lib/jenkins/workspace/aten/src/THCUNN -I /var/lib/jenkins/workspace/aten/src/ATen/cuda -I /var/lib/jenkins/workspace/build/caffe2/aten/src/TH -I /var/lib/jenkins/workspace/aten/src/TH -I /var/lib/jenkins/workspace/aten/src/TH -I /var/lib/jenkins/workspace/build/caffe2/aten/src/TH -I /var/lib/jenkins/workspace/aten/src -I /var/lib/jenkins/workspace/build/caffe2/aten/src -I /var/lib/jenkins/workspace/build/aten/src -I /var/lib/jenkins/workspace/aten/src/THNN -I /var/lib/jenkins/workspace/aten/src/THCUNN -I /var/lib/jenkins/workspace/aten/src -I /var/lib/jenkins/workspace/aten/../third_party/catch/single_include -I /var/lib/jenkins/workspace/build/caffe2/aten/src/ATen -I /var/lib/jenkins/workspace/aten/src/ATen/.. -I /var/lib/jenkins/workspace/build/caffe2/aten/src/ATen -I /var/lib/jenkins/workspace/aten/src -I /var/lib/jenkins/workspace/build -I /var/lib/jenkins/workspace -I /opt/rocm/miopen/include -I /var/lib/jenkins/workspace/third_party/protobuf/src -I /var/lib/jenkins/workspace/third_party/gemmlowp -I /var/lib/jenkins/workspace/third_party/neon2sse -I /var/lib/jenkins/workspace/cmake/../third_party/googletest/googletest/include -I /var/lib/jenkins/workspace/cmake/../third_party/benchmark/include -I /usr/include -I /usr/include/opencv -I /var/lib/jenkins/workspace/cmake/../third_party/eigen -I /usr/include/python2.7 -I /usr/local/lib/python2.7/dist-packages/numpy/core/include -I /var/lib/jenkins/workspace/cmake/../third_party/pybind11/include -I /opt/rocm/hip/include -I /opt/rocm/rocblas/include -I /opt/rocm/rocfft/include -I /opt/rocm/hipsparse/include -I /opt/rocm/hiprand/include -I /opt/rocm/rocrand/include -I /opt/rocm/include -I /var/lib/jenkins/workspace/build/caffe2/contrib/aten -I /var/lib/jenkins/workspace/third_party/onnx -I /var/lib/jenkins/workspace/build/third_party/onnx -I /var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/include -I /var/lib/jenkins/workspace/third_party/ideep/include -I /var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/external/mklml_lnx_2018.0.3.20180406/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/hcc/lib/clang/7.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wno-deprecated-register -Wno-macro-redefined -Wno-inconsistent-missing-override -Wno-exceptions -Wno-shift-count-negative -Wno-shift-count-overflow -Wno-unused-command-line-argument -Wno-duplicate-decl-specifier -std=c++amp -fdeprecated-macro -fdebug-compilation-dir /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -famp -fhsa-ext -o /tmp/THCTensorMode-be107e.s -x hc-host /var/lib/jenkins/workspace/aten/src/THC/THCTensorMode.cu -emit-llvm-bc 
17:23:30 1.<eof> parser at end of file
17:23:30 2.Per-module optimization passes
17:23:30 3.Running pass 'CallGraph Pass Manager' on module '/var/lib/jenkins/workspace/aten/src/THC/THCTensorMode.cu'.
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x1767d3a]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm3sys17RunSignalHandlersEv+0x4c)[0x176606c]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original[0x17661d7]
17:23:30 /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f93c4c0c390]
17:23:30 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f93c397e428]
17:23:30 /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f93c398002a]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm22report_bad_alloc_errorEPKcb+0x154)[0x1714714]
17:23:30 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x2c)[0x7f93c42bfe8c]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original[0x12748e8]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm11Instruction11setMetadataEjPNS_6MDNodeE+0x23a)[0x127543a]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm11Instruction12copyMetadataERKS0_NS_8ArrayRefIjEE+0x58f)[0x12396df]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZNK4llvm11Instruction5cloneEv+0x5a)[0x1239a0a]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original[0x179b3b0]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm25CloneAndPruneIntoFromInstEPNS_8FunctionEPKS0_PKNS_11InstructionERNS_8ValueMapIPKNS_5ValueENS_14WeakTrackingVHENS_14ValueMapConfigISA_NS_3sys10SmartMutexILb0EEEEEEEbRNS_15SmallVectorImplIPNS_10ReturnInstEEEPKcPNS_14ClonedCodeInfoE+0x107)[0x179fae7]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm14InlineFunctionENS_8CallSiteERNS_18InlineFunctionInfoEPNS_9AAResultsEbPNS_8FunctionE+0xe91)[0x17c8e41]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm17LegacyInlinerBase11inlineCallsERNS_12CallGraphSCCE+0xf5c)[0x130071c]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original[0xd46651]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x32c)[0x125d38c]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsERKN4llvm10DataLayoutEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISM_EEb+0xc47)[0x195cff7]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original[0x2088342]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN5clang8ParseASTERNS_4SemaEbb+0x370)[0x2814050]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN5clang13CodeGenAction13ExecuteActionEv+0x37)[0x20878e7]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN5clang14FrontendAction7ExecuteEv+0x126)[0x1d5e506]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x146)[0x1d27f06]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x96c)[0x1df994c]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0xa18)[0x8f9158]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(main+0x17e3)[0x8973d3]
17:23:30 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f93c3969830]
17:23:30 /opt/rocm/hcc/bin/clang-7.0_original(_start+0x29)[0x8f6929]
17:23:30 clang-7.0_original: error: unable to execute command: Aborted (core dumped)
17:23:30 clang-7.0_original: error: clang frontend command failed due to signal (use -v to see invocation)
17:23:30 HCC clang version 7.0.0 (git@github.com:scchan/hcc-clang-upgrade.git 4ed1d60af7c26e833d6d4452ba526d2daaa6ed35) (https://github.com/scchan/llvm.git c57b310200941724972aa5c5c90cbc151d1978f4) (based on HCC 1.2.18445-b03a17a-4ed1d60-c57b310 )
17:23:30 Target: x86_64-unknown-linux-gnu
17:23:30 Thread model: posix
17:23:30 InstalledDir: /opt/rocm/hcc/bin
17:23:30 clang-7.0_original: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
17:23:30 clang-7.0_original: note: diagnostic msg: 
17:23:30 ********************
17:23:30 
17:23:30 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
17:23:30 Preprocessed source(s) and associated run script(s) are located at:
17:23:30 clang-7.0_original: note: diagnostic msg: /tmp/THCTensorMode-07dfc2.cpp
17:23:30 clang-7.0_original: note: diagnostic msg: /tmp/THCTensorMode-604533.cpp
17:23:30 clang-7.0_original: note: diagnostic msg: /tmp/THCTensorMode-07dfc2.sh
17:23:30 clang-7.0_original: note: diagnostic msg: 
17:23:30 
17:23:30 ********************
```

**Comment by ezyang** [comment]
Another occurrence: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/4018/console

```
17:44:36 test_Embedding (__main__.TestNN) ... /usr/bin/python: symbol lookup error: /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libcaffe2_hip.so: undefined symbol: THCudaTensor_indexSelect
```
