### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by NomiMalik0207** [pytorch/pytorch#14519]
## 🐛 Bug

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    message = initrun(dataloader, netD, netG, args)
  File "/home/naveed/myDRGAN-master/run/run.py", line 9, in initrun
    mes = train_single_DRGAN(dataloader, netD, netG, args)
  File "/home/naveed/myDRGAN-master/run/train_single_DRGAN.py", line 179, in train_single_DRGAN
    L_d_gan   = BCE_Loss(real_output[:, Nd].sigmoid(), batch_real_label) + BCE_Loss(syn_output[:, Nd].sigmoid(), batch_sys_label)
  File "/home/naveed/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/naveed/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 433, in forward
    reduce=self.reduce)
  File "/home/naveed/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1483, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, size_average, reduce)
RuntimeError: reduce failed to synchronize: device-side assert triggered
 i have tried every solution, but didnt solve this problem.

**Comment by soumith** [comment]
`target` here has out of bounds indices.
Your inputs to the loss function are invalid.
