### ISSUE TITLE
test_barrier_full_group is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14554]
```
Nov 29 17:41:15 test_barrier_full_group (__main__.TestDistBackend) ... Process process 1:
Nov 29 17:41:15 Traceback (most recent call last):
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Nov 29 17:41:15     self.run()
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Nov 29 17:41:15     self._target(*self._args, **self._kwargs)
Nov 29 17:41:15   File "test_distributed.py", line 1389, in _run
Nov 29 17:41:15     getattr(self, self.id().split(".")[2])()
Nov 29 17:41:15   File "test_distributed.py", line 1328, in wrapper
Nov 29 17:41:15     fn(self)
Nov 29 17:41:15   File "test_distributed.py", line 1021, in test_barrier_full_group
Nov 29 17:41:15     self._test_barrier_helper(group, group_id, rank)
Nov 29 17:41:15   File "test_distributed.py", line 980, in _test_barrier_helper
Nov 29 17:41:15     self.assertGreaterEqual(time.time(), expected_time[0])
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 1227, in assertGreaterEqual
Nov 29 17:41:15     self.fail(self._formatMessage(msg, standardMsg))
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Nov 29 17:41:15     raise self.failureException(msg)
Nov 29 17:41:15 AssertionError: 1543513275.6613793 not greater than or equal to tensor(1.5435e+09)
Nov 29 17:41:15 Process process 0:
Nov 29 17:41:15 Traceback (most recent call last):
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Nov 29 17:41:15     self.run()
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Nov 29 17:41:15     self._target(*self._args, **self._kwargs)
Nov 29 17:41:15   File "test_distributed.py", line 1389, in _run
Nov 29 17:41:15     getattr(self, self.id().split(".")[2])()
Nov 29 17:41:15   File "test_distributed.py", line 1328, in wrapper
Nov 29 17:41:15     fn(self)
Nov 29 17:41:15   File "test_distributed.py", line 1021, in test_barrier_full_group
Nov 29 17:41:15     self._test_barrier_helper(group, group_id, rank)
Nov 29 17:41:15   File "test_distributed.py", line 980, in _test_barrier_helper
Nov 29 17:41:15     self.assertGreaterEqual(time.time(), expected_time[0])
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 1227, in assertGreaterEqual
Nov 29 17:41:15     self.fail(self._formatMessage(msg, standardMsg))
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Nov 29 17:41:15     raise self.failureException(msg)
Nov 29 17:41:15 AssertionError: 1543513275.6613927 not greater than or equal to tensor(1.5435e+09)
Nov 29 17:41:20 Process process 2:
Nov 29 17:41:20 Traceback (most recent call last):
Nov 29 17:41:20   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Nov 29 17:41:20     self.run()
Nov 29 17:41:20   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Nov 29 17:41:20     self._target(*self._args, **self._kwargs)
Nov 29 17:41:20   File "test_distributed.py", line 1389, in _run
Nov 29 17:41:20     getattr(self, self.id().split(".")[2])()
Nov 29 17:41:20   File "test_distributed.py", line 1328, in wrapper
Nov 29 17:41:20     fn(self)
Nov 29 17:41:20   File "test_distributed.py", line 1021, in test_barrier_full_group
Nov 29 17:41:20     self._test_barrier_helper(group, group_id, rank)
Nov 29 17:41:20   File "test_distributed.py", line 982, in _test_barrier_helper
Nov 29 17:41:20     self._barrier()
Nov 29 17:41:20   File "test_distributed.py", line 193, in _barrier
Nov 29 17:41:20     Barrier.sync(*args, **kwargs)
Nov 29 17:41:20   File "test_distributed.py", line 187, in sync
Nov 29 17:41:20     raise RuntimeError("barrier timeout")
Nov 29 17:41:20 RuntimeError: barrier timeout
Nov 29 17:41:20 FAIL
Nov 29 17:41:20 test_barrier_full_group_cuda (__main__.TestDistBackend) ... skipped 'cuda is not available'
Nov 29 17:41:21 test_barrier_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:21 test_barrier_group_cuda (__main__.TestDistBackend) ... skipped 'cuda is not available'
Nov 29 17:41:22 test_broadcast (__main__.TestDistBackend) ... ok
Nov 29 17:41:22 test_broadcast_cuda (__main__.TestDistBackend) ... skipped 'cuda is not available'
Nov 29 17:41:22 test_broadcast_full_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:22 test_broadcast_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:22 test_broadcast_multigpu (__main__.TestDistBackend) ... skipped 'cuda is not available'
Nov 29 17:41:23 test_destroy_full_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:23 test_destroy_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:23 test_gather (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
Nov 29 17:41:23 test_gather_full_group (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
Nov 29 17:41:23 test_gather_group (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
Nov 29 17:41:23 test_get_backend (__main__.TestDistBackend) ... ok
Nov 29 17:41:23 test_get_default_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:24 test_get_rank (__main__.TestDistBackend) ... ok
Nov 29 17:41:25 test_get_rank_size_full_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:25 test_get_rank_size_group (__main__.TestDistBackend) ... ok
Nov 29 17:41:25 test_irecv (__main__.TestDistBackend) ... ok
Nov 29 17:41:26 test_isend (__main__.TestDistBackend) ... ok
Nov 29 17:41:26 test_reduce_full_group_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_full_group_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_full_group_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_full_group_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_group_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_group_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_group_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_group_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_multigpu (__main__.TestDistBackend) ... skipped 'Only Nccl backend supports reduce multigpu'
Nov 29 17:41:26 test_reduce_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
Nov 29 17:41:26 test_reduce_sum_cuda (__main__.TestDistBackend) ... skipped 'Only Nccl supports CUDA reduce'
Nov 29 17:41:26 test_scatter (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
Nov 29 17:41:26 test_scatter_full_group (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
Nov 29 17:41:26 test_scatter_group (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
Nov 29 17:41:27 test_send_recv (__main__.TestDistBackend) ... ok
Nov 29 17:41:27 test_send_recv_any_source (__main__.TestDistBackend) ... ok
Nov 29 17:41:27 test_send_recv_with_tag (__main__.TestDistBackend) ... ok
Nov 29 17:41:27 
Nov 29 17:41:27 ======================================================================
Nov 29 17:41:27 FAIL: test_barrier_full_group (__main__.TestDistBackend)
Nov 29 17:41:27 ----------------------------------------------------------------------
Nov 29 17:41:27 Traceback (most recent call last):
Nov 29 17:41:27   File "test_distributed.py", line 1326, in wrapper
Nov 29 17:41:27     self._join_and_reduce(fn)
Nov 29 17:41:27   File "test_distributed.py", line 1433, in _join_and_reduce
Nov 29 17:41:27     self.assertEqual(first_process.exitcode, 0)
Nov 29 17:41:27   File "/var/lib/jenkins/workspace/test/common_utils.py", line 439, in assertEqual
Nov 29 17:41:27     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Nov 29 17:41:27 AssertionError: 1 not less than or equal to 1e-05 : 
Nov 29 17:41:27 
Nov 29 17:41:27 ----------------------------------------------------------------------
Nov 29 17:41:27 Ran 65 tests in 18.317s
Nov 29 17:41:27 
Nov 29 17:41:27 FAILED (failures=1, skipped=33)
Nov 29 17:41:27 Traceback (most recent call last):
Nov 29 17:41:27   File "test/run_test.py", line 431, in <module>
Nov 29 17:41:27     main()
Nov 29 17:41:27   File "test/run_test.py", line 423, in main
Nov 29 17:41:27     raise RuntimeError(message)
Nov 29 17:41:27 RuntimeError: test_distributed failed!
```

log: https://circleci.com/gh/pytorch/pytorch/325347?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @pietern @teng-li

**Comment by pietern** [comment]
Assertion error at the core of this failure:

```

Nov 29 17:41:15   File "test_distributed.py", line 1021, in test_barrier_full_group
Nov 29 17:41:15     self._test_barrier_helper(group, group_id, rank)
Nov 29 17:41:15   File "test_distributed.py", line 980, in _test_barrier_helper
Nov 29 17:41:15     self.assertGreaterEqual(time.time(), expected_time[0])
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 1227, in assertGreaterEqual
Nov 29 17:41:15     self.fail(self._formatMessage(msg, standardMsg))
Nov 29 17:41:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Nov 29 17:41:15     raise self.failureException(msg)
Nov 29 17:41:15 AssertionError: 1543513275.6613793 not greater than or equal to tensor(1.5435e+09)
```

**Comment by ezyang** [comment]
Happened again at https://circleci.com/gh/pytorch/pytorch/1791246?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SciPioneer** [comment]
Verified that it's already fixed:
https://github.com/pytorch/pytorch/pull/56418
