### ISSUE TITLE
[JIT] Error reporting on imported modules highlights serialization code

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#14653]
Repro:

```
import torch

def baz(x):
    return torch.neg(x) + 3.14159

baz_traced = torch.jit.trace(baz, (torch.rand(5, 4, 3),))

@torch.jit.script
def foo(x):
    bar = torch.neg(torch.mm(x, torch.zeros(3, 4, 5)))
    return baz_traced(bar)

foo.save('test.out')

imported = torch.jit.load('test.out')
imported(torch.rand(3, 4))
```

Output:

```
Traceback (most recent call last):
  File "error_report.py", line 16, in <module>
    imported(torch.rand(3, 4))
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError:
matrices expected, got 2D, 3D tensors at ../aten/src/TH/generic/THTensorMath.cpp:935:
operation failed in interpreter:
op_version_set = 0
def forward(self,
    x: Tensor) -> Tensor:
  _0 = torch.zeros([3, 4, 5], dtype=6, layout=0, device=[0, -1])
  bar = torch.neg(torch.mm(x, _0))
                  ~~~~~~~~ <--- HERE
  _1 = torch.add(torch.neg(bar), CONSTANTS.c0, alpha=1)
  return _1
```

This has the potential to be super confusing to end users. We should probably preserve the original source for highlighting

**Comment by driazati** [comment]
This is fixed on master
