### ISSUE TITLE
test_distributed - failed gloo test_all_reduce_multigpu and  test_barrier_group_cuda on 8-GPU machines

### ISSUE THREAD

**Issue by teng-li** [pytorch/pytorch#14676]
```
tengli@learnfair062:~/pytorch/test$ python run_test.py -i distributed --verbose
Test executor: ['/private/home/tengli/miniconda3/bin/python']
Selected tests: distributed
Running test_distributed ... [2018-12-02 01:47:46.729903]
/public/apps/openmpi/2.1.1/gcc.5.4.0/bin/mpiexec
Running distributed tests for the gloo backend
test_Backend_enum_class (__main__.TestDistBackend) ... ok
test_DistributedDataParallel (__main__.TestDistBackend) ... ok
test_DistributedDataParallelCPU (__main__.TestDistBackend) ... ok
test_all_gather (__main__.TestDistBackend) ... skipped 'Only MPI supports CPU all gather'
test_all_gather_cuda (__main__.TestDistBackend) ... skipped 'Only Nccl supports CUDA all gather'
test_all_gather_full_group (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
test_all_gather_group (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
test_all_gather_multigpu (__main__.TestDistBackend) ... skipped 'Only Nccl backend supports allgather multigpu'
test_all_reduce_full_group_max (__main__.TestDistBackend) ... ok
test_all_reduce_full_group_min (__main__.TestDistBackend) ... ok
test_all_reduce_full_group_product (__main__.TestDistBackend) ... ok
test_all_reduce_full_group_sum (__main__.TestDistBackend) ... ok
test_all_reduce_group_max (__main__.TestDistBackend) ... ok
test_all_reduce_group_min (__main__.TestDistBackend) ... ok
test_all_reduce_group_product (__main__.TestDistBackend) ... ok
test_all_reduce_group_sum (__main__.TestDistBackend) ... ok
test_all_reduce_max (__main__.TestDistBackend) ... ok
test_all_reduce_min (__main__.TestDistBackend) ... ok
test_all_reduce_multigpu (__main__.TestDistBackend) ... Process process 0:
Traceback (most recent call last):
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 1446, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_distributed.py", line 1385, in wrapper
    fn(self)
  File "test_distributed.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 1146, in test_all_reduce_multigpu
    (2 + 10 * (len(group) - 1)) * len(rank_to_GPU[0]),
  File "test_distributed.py", line 1128, in _test_all_reduce_multigpu_helper
    self.assertEqual(tensor, expected_tensor)
  File "/private/home/tengli/pytorch/test/common_utils.py", line 414, in assertEqual
    assertTensorsEqual(x, y)
  File "/private/home/tengli/pytorch/test/common_utils.py", line 406, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
  File "/private/home/tengli/miniconda3/lib/python3.6/unittest/case.py", line 1215, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/private/home/tengli/miniconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: tensor(42., device='cuda:1', dtype=torch.float32) not less than or equal to 1e-05 :
Process process 2:
Traceback (most recent call last):
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 1446, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_distributed.py", line 1385, in wrapper
    fn(self)
  File "test_distributed.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 1146, in test_all_reduce_multigpu
    (2 + 10 * (len(group) - 1)) * len(rank_to_GPU[0]),
  File "test_distributed.py", line 1128, in _test_all_reduce_multigpu_helper
    self.assertEqual(tensor, expected_tensor)
  File "/private/home/tengli/pytorch/test/common_utils.py", line 414, in assertEqual
    assertTensorsEqual(x, y)
  File "/private/home/tengli/pytorch/test/common_utils.py", line 406, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
  File "/private/home/tengli/miniconda3/lib/python3.6/unittest/case.py", line 1215, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/private/home/tengli/miniconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: tensor(34., device='cuda:5', dtype=torch.float32) not less than or equal to 1e-05 :
Process process 1:
Traceback (most recent call last):
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 1446, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_distributed.py", line 1385, in wrapper
    fn(self)
  File "test_distributed.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 1146, in test_all_reduce_multigpu
    (2 + 10 * (len(group) - 1)) * len(rank_to_GPU[0]),
  File "test_distributed.py", line 1128, in _test_all_reduce_multigpu_helper
    self.assertEqual(tensor, expected_tensor)
  File "/private/home/tengli/pytorch/test/common_utils.py", line 414, in assertEqual
    assertTensorsEqual(x, y)
  File "/private/home/tengli/pytorch/test/common_utils.py", line 406, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
  File "/private/home/tengli/miniconda3/lib/python3.6/unittest/case.py", line 1215, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/private/home/tengli/miniconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: tensor(34., device='cuda:3', dtype=torch.float32) not less than or equal to 1e-05 :
FAIL
test_all_reduce_product (__main__.TestDistBackend) ... ok
test_all_reduce_sum (__main__.TestDistBackend) ... ok
test_all_reduce_sum_cuda (__main__.TestDistBackend) ... ok
test_barrier (__main__.TestDistBackend) ... ok
test_barrier_cuda (__main__.TestDistBackend) ... ok
test_barrier_full_group (__main__.TestDistBackend) ... ok
test_barrier_full_group_cuda (__main__.TestDistBackend) ... ok
test_barrier_group (__main__.TestDistBackend) ... ok
test_barrier_group_cuda (__main__.TestDistBackend) ... Process process 0:
Traceback (most recent call last):
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 1446, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_distributed.py", line 1385, in wrapper
    fn(self)
  File "test_distributed.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 1054, in test_barrier_group_cuda
    self._test_barrier_helper(group, group_id, rank, True, rank_to_GPU)
  File "test_distributed.py", line 1039, in _test_barrier_helper
    self._barrier()
  File "test_distributed.py", line 198, in _barrier
    Barrier.sync(*args, **kwargs)
  File "test_distributed.py", line 192, in sync
    raise RuntimeError("barrier timeout")
RuntimeError: barrier timeout
Process process 1:
Traceback (most recent call last):
 10 import subprocess
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 1447, in _run
    self._barrier()
  File "test_distributed.py", line 198, in _barrier
    Barrier.sync(*args, **kwargs)
  File "test_distributed.py", line 192, in sync
    raise RuntimeError("barrier timeout")
RuntimeError: barrier timeout
Process process 2:
Traceback (most recent call last):
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/tengli/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 1447, in _run
    self._barrier()
  File "test_distributed.py", line 198, in _barrier
    Barrier.sync(*args, **kwargs)
  File "test_distributed.py", line 192, in sync
    raise RuntimeError("barrier timeout")
RuntimeError: barrier timeout
FAIL
test_barrier_timeout_full_group (__main__.TestDistBackend) ... ok
test_barrier_timeout_global (__main__.TestDistBackend) ... skipped 'Requires file:// initialization method. Both tcp:// and env:// rely on the TCP store for which reinitialization has proven racy.'
test_barrier_timeout_group (__main__.TestDistBackend) ... ok
test_broadcast (__main__.TestDistBackend) ... ok
test_broadcast_cuda (__main__.TestDistBackend) ... ok
test_broadcast_full_group (__main__.TestDistBackend) ... ok
test_broadcast_group (__main__.TestDistBackend) ... ok
test_broadcast_multigpu (__main__.TestDistBackend) ... ok
test_destroy_full_group (__main__.TestDistBackend) ... ok
test_destroy_group (__main__.TestDistBackend) ... ok
test_gather (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
test_gather_full_group (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
test_gather_group (__main__.TestDistBackend) ... skipped 'Gloo does not support gather'
test_get_backend (__main__.TestDistBackend) ... ok
test_get_default_group (__main__.TestDistBackend) ... ok
test_get_rank (__main__.TestDistBackend) ... ok
test_get_rank_size_full_group (__main__.TestDistBackend) ... ok
test_get_rank_size_group (__main__.TestDistBackend) ... ok
test_irecv (__main__.TestDistBackend) ... ok
test_isend (__main__.TestDistBackend) ... ok
test_reduce_full_group_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_full_group_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_full_group_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_full_group_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_group_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_group_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_group_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_group_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_max (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_min (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_multigpu (__main__.TestDistBackend) ... skipped 'Only Nccl backend supports reduce multigpu'
test_reduce_product (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_sum (__main__.TestDistBackend) ... skipped 'Gloo does not support reduce'
test_reduce_sum_cuda (__main__.TestDistBackend) ... skipped 'Only Nccl supports CUDA reduce'
test_scatter (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
test_scatter_full_group (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
test_scatter_group (__main__.TestDistBackend) ... skipped 'Gloo does not support scatter'
test_send_recv (__main__.TestDistBackend) ... ok
test_send_recv_any_source (__main__.TestDistBackend) ... ok
test_send_recv_with_tag (__main__.TestDistBackend) ... ok

======================================================================
FAIL: test_all_reduce_multigpu (__main__.TestDistBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_distributed.py", line 1383, in wrapper
    self._join_and_reduce(fn)
  File "test_distributed.py", line 1478, in _join_and_reduce
    first_process.exitcode == SKIP_IF_SMALL_WORLDSIZE_EXIT_CODE
AssertionError

======================================================================
FAIL: test_barrier_group_cuda (__main__.TestDistBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_distributed.py", line 1383, in wrapper
    self._join_and_reduce(fn)
  File "test_distributed.py", line 1478, in _join_and_reduce
    first_process.exitcode == SKIP_IF_SMALL_WORLDSIZE_EXIT_CODE
AssertionError

----------------------------------------------------------------------
Ran 68 tests in 83.104s

FAILED (failures=2, skipped=26)
Traceback (most recent call last):
  File "run_test.py", line 431, in <module>
    main()
  File "run_test.py", line 423, in main
    raise RuntimeError(message)
RuntimeError: test_distributed failed!
```

**Comment by pietern** [comment]
The barrier one is likely because of excessive initialization time when using CUDA, triggering the native timeout. Bumping that a bit should solve it. Looking into the allreduce multi GPU one.
