### ISSUE TITLE
Missing args in constructor of torch.multiprocessing.pool.Pool

### ISSUE THREAD

**Issue by phohenecker** [pytorch/pytorch#14888]
## 🐛 Bug

In the constructor of `torch.multiprocessing.pool.Pool` (lines 23 and 24), two `torch.multiprocessing.queue.SimpleQueue`s are created with no args. The constructor of `SimpleQueue` requires one key-word arg, `ctx`, though. Therefore, initializing a `Pool` results in a `TypeError`.

## To Reproduce

```python
>>> from torch.multiprocessing import pool
>>> p = pool.Pool()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/anaconda3/envs/dummy/lib/python3.6/multiprocessing/pool.py", line 157, in __init__
    self._setup_queues()
  File "/home/patrick/anaconda3/envs/dummy/lib/python3.6/site-packages/torch/multiprocessing/pool.py", line 23, in _setup_queues
    self._inqueue = SimpleQueue()
TypeError: __init__() missing 1 required keyword-only argument: 'ctx'
```

## Environment

 - PyTorch Version: 0.4.1
 - OS: Ubuntu 16.04.5 LTS
 - How you installed PyTorch: `conda`
 - Python version: 3.6
 - CUDA/cuDNN version: CPU-only (but happens with GPU as well)

**Comment by ailzhang** [comment]
Closing via https://github.com/pytorch/pytorch/pull/14949#issuecomment-447206640

**Comment by phohenecker** [comment]
I'm still getting exactly the same error for the current nightly build (1.0.0.dev20190228):
```python
>>> from torch.multiprocessing import pool
>>> p = pool.Pool()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/anaconda3/envs/ppt/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
    self._setup_queues()
  File "/home/patrick/anaconda3/envs/ppt/lib/python3.6/site-packages/torch/multiprocessing/pool.py", line 23, in _setup_queues
    self._inqueue = SimpleQueue()
TypeError: __init__() missing 1 required keyword-only argument: 'ctx'
```
