### ISSUE TITLE
Improper error msg when calling Variable.cuda() in forked subprocess

### ISSUE THREAD

**Issue by Jiaming-Liu** [pytorch/pytorch#1494]
In FloatTensorBase: 

RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

In Variable:
RuntimeError: cuda runtime error (3) : initialization error at /py/conda-bld/pytorch_$SOMENUMBER$/work/torch/lib/THC/generic/THCStorage.c:55

**Comment by apaszke** [comment]
Can you please show me the code that gives you that error message?

**Comment by AwokeKnowing** [comment]
I got this error just running through the cifar10 tutorial .   I added net.cuda() 

![image](https://cloud.githubusercontent.com/assets/2770322/26023039/c6320786-3768-11e7-8de5-7e778d2f72e2.png)

**Comment by AwokeKnowing** [comment]
I started with 
ipython notebook &

so that I could exit the terminal and ssh forward the notebook to my local machine (the machine with cuda is on azure)

**Comment by AwokeKnowing** [comment]
well it seems somehow something is messed up now. this is just an azure machine with nvida (nv 6 I think) and it was working yesterday

![image](https://cloud.githubusercontent.com/assets/2770322/26023254/de9ef532-376c-11e7-8ff9-9d4b8d3ab26a.png)

Now I don't know what to do.

**Comment by Jiaming-Liu** [comment]
@apaszke Seems to be more complex than I thought:

``` python
# from multiprocessing import set_start_method
# try:
#     set_start_method('spawn')
# except RuntimeError:
#     pass

# Above are NOT executed

import torch
from torch.multiprocessing import Process

def boom():
    b = torch.FloatTensor([1,2,3])
    # b = b.cuda(0) # Normal error msg.
    # b = b.cuda(1) # Normal error msg.
    b = torch.autograd.Variable(b)
    # b = b.cuda(1) # Normal error msg.
    b = b.cuda(0) # initialization error at /b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.c:55

a = torch.FloatTensor([2,2,3])
a = a.cuda(1)
a = torch.autograd.Variable(a)
p = Process(target=boom,args=())
p.daemon = True
p.start()
p.join()

```

Error:
```
THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.c line=55 error=3 : initialization error
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/------/test_boom.py", line 15, in boom
    b = b.cuda(0) #
  File "/------/torch/autograd/variable.py", line 240, in cuda
    return CudaTransfer(device_id, async)(self)
  File "/------/torch/autograd/_functions/tensor.py", line 160, in forward
    return i.cuda(async=self.async)
  File "/------/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (3) : initialization error at /b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.c:55
```

**Comment by soumith** [comment]
please see http://pytorch.org/docs/notes/multiprocessing.html#sharing-cuda-tensors

This is completely expected, and it is a fundamental CUDA limitation. We published the workaround there.

**Comment by apaszke** [comment]
It's expected that it fails, but it's not expected that it fails with that THC error. I'm reopening this, so we remember to investigate it further

**Comment by keven425** [comment]
I'm running in this exact same issue. What's the workaround for sharing cuda tensors across processes?

The example you provided here only works for CPU, not GPU: https://github.com/pytorch/examples/tree/master/mnist_hogwild

**Comment by apaszke** [comment]
The issue is only about an invalid error message, the snippet is incorrect anyway, so you can't expect it to work.

**Comment by Jiaming-Liu** [comment]
@keven425 Generally you will have to run in Python 3,and include 
``` Python 
from multiprocessing import set_start_method
try:
    set_start_method('spawn')
except RuntimeError:
    pass
```
To avoid fork()

**Comment by braingineer** [comment]
maybe related, not sure if it should be another issue:

```
import argparse
import torch
from multiprocessing import Process

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--gpu-id", default=0, type=int,
                        choices=list(range(torch.cuda.device_count())))

    return parser.parse_args()


def run_in_process():
    print(torch.cuda.device_count())

def main():
    args = parse_args()
    p = Process(target=run_in_process)
    p.start()
    p.join()

if __name__ == '__main__':
    main()
```

gives

```
Process Process-1:
Traceback (most recent call last):
  File "/home/brian/anaconda3/envs/t3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/brian/anaconda3/envs/t3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "maybe_pytorch_bug.py", line 15, in run_in_process
    print(torch.cuda.device_count())
  File "/home/brian/anaconda3/envs/t3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 190, in device_count
    _lazy_init()
  File "/home/brian/anaconda3/envs/t3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 83, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

if the `torch.cuda.device_count` is taken out of the argument parser, then there is no error.  Not a huge deal to work around, just wanted to flag it.

**Comment by soumith** [comment]
this is expected.
See: http://pytorch.org/docs/master/notes/multiprocessing.html#sharing-cuda-tensors

See the above workaround https://github.com/pytorch/pytorch/issues/1494#issuecomment-305993854

**Comment by braingineer** [comment]
Hi @soumith 

I didn't try that on the example right away (but was modifying my comment here to include it as you commented! :)).  This does solve this case.. I have another that is way more complex that the start method solution didn't fix. I'm not sure what the difference is at the moment between this minimum example as my more complex one. If I figure it out, I'll ping back.

**Comment by braingineer** [comment]
Figured it out. I was getting a `context has already been set` RuntimeError when trying to set the start method to 'spawn'.  

Found a buried sklearn import for some f1 computations. Moving the sklearn import inside the actual f1 function call allowed for the start method to be set inside the `if __name__=='__main__'`.

**Comment by gautamkmr** [comment]
I am hitting the same issue, however in stead of using `multiprocessing`  I am using [this](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) to launch single node training and issue happens when I try to create a synthetic dataset on GPU. 

```
class DummyDataset(data.Dataset):
    def __init__(self, num_classes):
        super(DummyDataset, self).__init__()
        # Create tensor on GPU 
        self.tensor = torch.randn(3, 224, 224, device=torch.device('cuda'))
        self.num_classes = num_classes

    def __getitem__(self, index):
        torch.manual_seed(index)
        random.seed(index)
        return self.tensor, \
               random.randint(0, self.num_classes - 1)
```

When I ran the training I get the error  
```
untimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/pytorch_sample/dummy_data.py", line 16, in __getitem__
    return torch.randn(3,224,224, device=torch.device('cuda')), \
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by gautamkmr** [comment]
I am hitting the same issue, however in stead of using `multiprocessing`  I am using [this](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) to launch single node training and issue happens when I try to create a synthetic dataset on GPU. 

```
class DummyDataset(data.Dataset):
    def __init__(self, num_classes):
        super(DummyDataset, self).__init__()
        # Create tensor on GPU 
        self.tensor = torch.randn(3, 224, 224, device=torch.device('cuda'))
        self.num_classes = num_classes

    def __getitem__(self, index):
        torch.manual_seed(index)
        random.seed(index)
        return self.tensor, \
               random.randint(0, self.num_classes - 1)
```

When I ran the training I get the error  
```
untimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/pytorch_sample/dummy_data.py", line 16, in __getitem__
    return torch.randn(3,224,224, device=torch.device('cuda')), \
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by chh7411898** [comment]
so  how to solve it ?  i have the same que
