### ISSUE TITLE
Non-deterministic ASAN hang with test_leaf_variable_sharing

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14997]
Failures look like this:

```
test_leaf_variable_sharing (test_multiprocessing.TestMultiprocessing) ... Timing out. Killing processes in state: S (sleeping)
S (sleeping)
S (sleeping)
Attempting to pull stack traces: 
command timed out


[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/local/fbcode/gcc-5-glibc-2.23/lib/libthread_db.so.1".
0x00007fe1332ceb20 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:84
84	T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)

Thread 1 (Thread 0x7fe1316b0000 (LWP 8430)):
#0  0x00007fe1332ceb20 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000004877d4 in poll ()
#2  0x0000000000429802 in main (argc=1, argv=0x7ffe09a77ec8) at caffe2/torch/lib/libshm/manager.cpp:114
[Inferior 1 (process 8430) detached]
```

It's not confirmed that ASAN is necessary to trigger this, but it would be consistent with other hangs that we've seen when running with ASAN in multiprocessing.

The test has been broken at least as early as Nov 27, 3:13pm

**Comment by ezyang** [comment]
haven't seen this since
