### ISSUE TITLE
ResNet -101 does not run when converted to sequential (returns dimension mismatch)

### ISSUE THREAD

**Issue by nickgkan** [pytorch/pytorch#15129]
## 🐛 Bug

I wanted to obtain convolutional features from ResNet-101. I had already figured out how to do it, but I wanted to run a simple test to check if I am applying the correct preprocessing steps, so instead of omitting the last layer, I transformed the whole network into a nn.Sequential(), only to get an error:
RuntimeError: size mismatch, m1: [2048 x 1], m2: [2048 x 1000] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:940

## To Reproduce

Here is the code:
```python
"""Test PyTorch ResNet-101."""
from matplotlib import pyplot as plt
from PIL import Image
from torch import nn
from torchvision import models, transforms


class ResNet101(nn.Module):
    """ResNet-101 PyTorch."""

    def __init__(self):
        """Initialize network and freeze layers."""
        super().__init__()
        self.resnet = nn.Sequential(
            *list(models.resnet101(pretrained=True).children())
        )
        for param in self.resnet.parameters():
            param.requires_grad = False

    def forward(self, x):
        """Forward pass."""
        x = self.resnet(x)
        return x


def resnet_eval(img_path):
    """Run a simple classification."""
    resnet = ResNet101().eval()
    img = Image.open(img_path)
    preprocessing = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])
    inputs = preprocessing(img).unsqueeze(0)
    print(inputs.shape)

    outputs = resnet(inputs)
    print(outputs.data.shape)
    # print(outputs)
    print(outputs[0].sort()[1][-1])
    plt.figure()
    plt.imshow(img)
    plt.axis('off')
    plt.show()
```

When I run resnet_eval with a valid image path, I get the following output:

```
torch.Size([1, 3, 224, 224])
Traceback (most recent call last):
  File "res.py", line 58, in <module>
    resnet_eval(folder + img_name)
  File "res.py", line 39, in resnet_eval
    outputs = resnet(inputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "res.py", line 22, in forward
    x = self.resnet(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [2048 x 1], m2: [2048 x 1000] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:940
```

Of course, transforming the whole net into a sequential model is non-sense, we can just replace the first line (after the docstring) of resnet_eval with
```
resnet = models.resnet101(pretrained=True).eval()
```
and get the expected output
```
torch.Size([1, 3, 224, 224])
torch.Size([1, 1000])
tensor(546)
```

Another approach is to remove the final layer, reshape the output tensor and then add the last layer again, like this:
```python
class ResNet101(nn.Module):
    """ResNet-101 PyTorch."""

    def __init__(self):
        """Initialize network and freeze layers."""
        super().__init__()
        self.resnet = nn.Sequential(
            *list(models.resnet101(pretrained=True).children())[:-1]
        )
        for param in self.resnet.parameters():
            param.requires_grad = False
        self.linear = list(models.resnet101(pretrained=True).children())[-1]

    def forward(self, x):
        """Forward pass."""
        x = self.resnet(x)
        x = x.view(x.shape[0], -1)
        x = self.linear(x)
        return x
```
and once again, this works as expected, giving the same output as when running
```
resnet = models.resnet101(pretrained=True).eval()
```

If I print the tensor values, they are identical in the two last cases. So why do I come accross the mismatch error in the first case (or equivalently, why is the last case valid)?

## Expected behavior

The first case should run smoothly, giving the same output as the second one.

## Environment

Tested with Python3.5 and 
torch==1.0.0
torchvision==0.2.1

**Comment by soumith** [comment]
your code is buggy, plain and simple.

```
 self.resnet = nn.Sequential(
            *list(models.resnet101(pretrained=True).children())
        )
```

The logic of resnet101 is not simply entirely encoded in it's `.children()`, read the `.forward` function for additional logic (in fact, in cases 2 and 3, you figured it out).

If you have questions in the future, post on our forums https://discuss.pytorch.org

If you are pretty sure it's a bug in the framework, file a github issue.

**Comment by nickgkan** [comment]
Ok, I checked the ```.forward``` method, it is all clear now. Thank you for your response!
