### ISSUE TITLE
Problem "torch.jit.trace()"ing pretrained Inception_v3 model

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#15216]
## 🐛 Bug
Hi. I was trying to make inception model available in c++ interface so I was trying to build a script module of it but this simple code fails:

``` python
import torch
import torchvision

# An instance of your model.
model = torchvision.models.inception_v3(pretrained=True)

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 299, 299)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)
```
output:
Traceback (most recent call last):
  File "inception-to-script.py", line 11, in <module>
    traced_script_module = torch.jit.trace(model, example)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/jit/__init__.py", line 635, in trace
    var_lookup_fn, _force_outplace)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torchvision/models/inception.py", line 109, in forward
    aux = self.AuxLogits(x)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torchvision/models/inception.py", line 308, in forward
    x = self.conv1(x)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torchvision/models/inception.py", line 326, in forward
    x = self.bn(x)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 1619, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 768, 1, 1])

I also tried with different input size but it failed. output:
Traceback (most recent call last):
  File "inception-to-script.py", line 11, in <module>
    traced_script_module = torch.jit.trace(model, example)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/jit/__init__.py", line 635, in trace
    var_lookup_fn, _force_outplace)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torchvision/models/inception.py", line 109, in forward
    aux = self.AuxLogits(x)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torchvision/models/inception.py", line 308, in forward
    x = self.conv1(x)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torchvision/models/inception.py", line 325, in forward
    x = self.conv(x)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shahriar/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: std::exception

I don't know if this is a bug or I did something wrong but this happened. I also tried it with resnet but these was no problem there

## Environment

OS: fedora
PyTorch version: 1.0.0 stable
Installation method: pip3
CUDA: not using cuda. installed the cpu version

**Comment by soumith** [comment]
@ShahriarSS you are giving an input with batch-size of 1 in training mode.

Either of the two things will work:

1. batch size of > 1:

```
example = torch.rand(2, 3, 299, 299)
```

2. Put the model in eval mode:

```
model = torchvision.models.inception_v3(pretrained=True)
model.eval()
```

However, that being said, I am seeing the following fail:

```
import torch
import torchvision

model = torchvision.models.inception_v3(pretrained=True)
model.eval()

example = torch.randn(2, 3, 299, 299)
traced_script_module = torch.jit.trace(model, example)
```

```
/scratch/soumith/pytorch/torch/jit/__init__.py:642: TracerWarning: Trace had nondeterministic nodes. Nodes:
        %x : Float(2, 2048, 1, 1) = aten::dropout(%input.266, %5133, %5134), scope: Inception3
This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
  _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
/scratch/soumith/pytorch/torch/jit/__init__.py:642: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Not within tolerance rtol=1e-05 atol=1e-05 at input[0, 664] (3.1920981407165527 vs. -0.4343012273311615) and 1999 other locations (100.00%)
  _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
/scratch/soumith/pytorch/torch/jit/__init__.py:642: TracerWarning: Output nr 2. of the traced function does not match the corresponding output of the Python function. Detailed error:
Not within tolerance rtol=1e-05 atol=1e-05 at input[0, 507] (-0.2636445462703705 vs. -1.134244441986084) and 1999 other locations (100.00%)
  _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
```

Confirmed by @zdevito that this is a bug in the tracer.

**Comment by ShahriarSS** [comment]
@soumith 
I did get the same warning when I set the batch size to 2.

**Comment by joaolcaas** [comment]
On pytorch's AlexNet model for cifar10 data set i just used model.eval() with batch 1 and it worked
`
input_example = th.rand(1, 3, 32, 32)
`
`
model.eval()
`
`
trace_model = th.jit.trace(model, input_example)
`

**Comment by longzeyilang** [comment]
How to modify the value of input_example for object detection such as Faster-RCNN? Because the input not only include image shape, but also include object information? such as x,y,w,h. and so on
