### ISSUE TITLE
Segmentation fault cuda 10

### ISSUE THREAD

**Issue by dizcza** [pytorch/pytorch#15296]
## 🐛 Bug

```
python3.6 -X faulthandler -c "import torch; torch.randn(5).cuda()"

Current thread 0x00007f2770fdd700 (most recent call first):
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162 in _lazy_init
  File "<string>", line 1 in <module>
Segmentation fault (core dumped)
```

## Environment

[conda] blas                      1.0                         mkl  
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl_fft                   1.0.6            py36hd81dba3_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] torch                     1.0.0a0                   <pip>
[conda] torchvision               0.2.1                     <pip>

 - PyTorch Version: 1.0.0 (`git checkout v1.0.0`)
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch: built from source
 - Build command you used (if compiling from source): `TORCH_CUDA_ARCH_LIST="3.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" pip install -v .`
 - Python version: 3.6.7
 - CUDA/cuDNN version: cuda 10.0, cuDNN 7.4
 - GPU models and configuration: GTX 760, architecture 3.0

### Description

Segmentation fault appears only with CUDA 10 (CUDA 9.2 works fine).

I've used your [Dockerfile](https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile) and changed the first line to `FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04`. It was built sucessfully but segmentation fault appears in run time. I also tried `FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04` and no errors appeared.

**Comment by dizcza** [comment]
Uninstalling magma-cuda92 didn't help. My guess is that building command `pip install` (or `python setup.py install`) silently ignored build errors and exited with a code 0. If I have time, I'll investigate build logs.

**Comment by tstandley** [comment]
Did you solve the issue? A similar issue seems to be plaguing me.

**Comment by tstandley** [comment]
For anyone interested, I had to uninstall anaconda completely and reinstall it and then pytorch to fix the issue. Uninstalling and reinstalling pytorch was not sufficient.

**Comment by dizcza** [comment]
With release tagged v1.0.1 I get the following error, trying to build same Dockerfile:
(If I pass USE_MKLDNN=OFF it seems to build successfully.)

```
    -- ******** Summary ********
    -- General:
    --   CMake version         : 3.5.1
    --   CMake command         : /usr/bin/cmake
    --   System                : Linux
    --   C++ compiler          : /usr/bin/c++
    --   C++ compiler version  : 5.4.0
    --   BLAS                  : MKL
    --   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized
    --   Build type            : Release
    --   Compile definitions   : TH_BLAS_MKL;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;USE_GCC_ATOMICS=1;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
    --   CMAKE_PREFIX_PATH     : /opt/conda/bin/../;/opt/conda/lib/python3.6/site-packages
    --   CMAKE_INSTALL_PREFIX  : /tmp/pip-req-build-qkdnih53/torch/lib/tmp_install
    --
    --   TORCH_VERSION         : 1.0.0
    --   CAFFE2_VERSION        : 1.0.0
    --   BUILD_ATEN_MOBILE     : OFF
    --   BUILD_ATEN_ONLY       : OFF
    --   BUILD_BINARY          : OFF
    --   BUILD_CUSTOM_PROTOBUF : ON
    --     Link local protobuf : ON
    --   BUILD_DOCS            : OFF
    --   BUILD_PYTHON          : ON
    --     Python version      : 3.6.8
    --     Python executable   : /opt/conda/bin/python
    --     Pythonlibs version  : 3.6.8
    --     Python library      : /opt/conda/lib/libpython3.6m.so.1.0
    --     Python includes     : /opt/conda/include/python3.6m
    --     Python site-packages: lib/python3.6/site-packages
    --   BUILD_CAFFE2_OPS      : ON
    --   BUILD_SHARED_LIBS     : ON
    --   BUILD_TEST            : ON
    --   USE_ASAN              : OFF
    --   USE_CUDA              : 1
    --     CUDA static link    : 0
    --     USE_CUDNN           : ON
    --     CUDA version        : 10.0
    --     cuDNN version       : 7.4.1
    --     CUDA root directory : /usr/local/cuda
    --     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
    --     cudart library      : /usr/local/cuda/lib64/libcudart.so
    --     cublas library      : /usr/local/cuda/lib64/libcublas.so
    --     cufft library       : /usr/local/cuda/lib64/libcufft.so
    --     curand library      : /usr/local/cuda/lib64/libcurand.so
    --     cuDNN library       : /usr/lib/x86_64-linux-gnu/libcudnn.so.7
    --     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
    --     CUDA include path   : /usr/local/cuda/include
    --     NVCC executable     : /usr/local/cuda/bin/nvcc
    --     CUDA host compiler  : /usr/bin/cc
    --     USE_TENSORRT        : OFF
    --   USE_ROCM              : 0
    --   USE_EIGEN_FOR_BLAS    :
    --   USE_FBGEMM            : 0
    --   USE_FFMPEG            : OFF
    --   USE_GFLAGS            : OFF
    --   USE_GLOG              : OFF
    --   USE_LEVELDB           : OFF
    --   USE_LITE_PROTO        : OFF
    --   USE_LMDB              : OFF
    --   USE_METAL             : OFF
    --   USE_MKL               : ON
    --   USE_MKLDNN            : ON
    --   USE_MOBILE_OPENGL     : OFF
    --   USE_NCCL              : ON
    --     USE_SYSTEM_NCCL     : ON
    --   USE_NNPACK            : 1
    --   USE_NUMPY             : ON
    --   USE_OBSERVERS         : ON
    --   USE_OPENCL            : OFF
    --   USE_OPENCV            : OFF
    --   USE_OPENMP            : OFF
    --   USE_PROF              : OFF
    --   USE_QNNPACK           : 1
    --   USE_REDIS             : OFF
    --   USE_ROCKSDB           : OFF
    --   USE_ZMQ               : OFF
    --   USE_DISTRIBUTED       : ON
    --     USE_MPI             : OFF
    --     USE_GLOO            : ON
    --     USE_GLOO_IBVERBS    : OFF
    --   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
    --   Private Dependencies : qnnpack;nnpack;cpuinfo;fp16;gloo;aten_op_header_gen;onnxifi_loader;rt;gcc_s;gcc;dl
    -- Configuring done
    CMake Warning (dev) at cmake/Dependencies.cmake:827 (add_dependencies):
      Policy CMP0046 is not set: Error on non-existent dependency in
      add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
      Use the cmake_policy command to set the policy and suppress this warning.

      The dependency target "nccl_external" of target "gloo_cuda" does not exist.
    Call Stack (most recent call first):
      CMakeLists.txt:201 (include)
    This warning is for project developers.  Use -Wno-dev to suppress it.

    CMake Error: install(EXPORT "Caffe2Targets" ...) includes target "caffe2" which requires target "mkldnn" that is not in the export set.
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        CUDNN_LIB_DIR
        NCCL_ROOT_DIR
        THD_SO_VERSION


    -- Build files have been written to: /tmp/pip-req-build-qkdnih53/build
    Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn --use-qnnpack caffe2'
    Running setup.py install for torch: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-req-build-qkdnih53
Removed build tracker '/tmp/pip-req-tracker-p6gs6fah'
Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-qkdnih53/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ot_7yjrx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-qkdnih53/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-qkdnih53/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ot_7yjrx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-qkdnih53/
```

**Comment by prasunanand** [comment]
Is anyone working on this ? I am getting the same issue with CUDA 10.1.

**Comment by dizcza** [comment]
I've successfully built pytorch v1.7.0 with CUDA 10.2 + cuDNN 7 and tried on the same GPU card (GTX 760, CUDA capability 3.0).

Dockerfile:
```Dockerfile
# syntax = docker/dockerfile:experimental
#
# NOTE: To build this you will need a docker version > 18.06 with
#       experimental enabled and DOCKER_BUILDKIT=1
#
#       If you do not use buildkit you are not going to have a good time
#
#       For reference:
#           https://docs.docker.com/develop/develop-images/build_enhancements/
ARG BASE_IMAGE=ubuntu:18.04
ARG PYTHON_VERSION=3.7

FROM ${BASE_IMAGE} as dev-base
RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        ccache \
        cmake \
        curl \
        git \
        libjpeg-dev \
        libpng-dev && \
    rm -rf /var/lib/apt/lists/*
RUN /usr/sbin/update-ccache-symlinks
RUN mkdir /opt/ccache && ccache --set-config=cache_dir=/opt/ccache
ENV PATH /opt/conda/bin:$PATH

FROM dev-base as conda
ARG PYTHON_VERSION=3.7
RUN curl -fsSL -v -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda install -y python=${PYTHON_VERSION} conda-build pyyaml numpy ipython&& \
    /opt/conda/bin/conda clean -ya

FROM dev-base as submodule-update
WORKDIR /opt/pytorch
COPY . .
RUN git submodule update --init --recursive --jobs 0

FROM conda as build
WORKDIR /opt/pytorch
COPY --from=conda /opt/conda /opt/conda
COPY --from=submodule-update /opt/pytorch /opt/pytorch

RUN pip install typing-extensions

RUN --mount=type=cache,target=/opt/ccache \
    TORCH_CUDA_ARCH_LIST="3.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    USE_ROCM=0 BUILD_TEST=0 USE_MPI=0 BUILD_CAFFE2_OPS=0 BUILD_CAFFE2=0 USE_OPENMP=0 \
    python setup.py install

FROM conda as conda-installs
ARG PYTHON_VERSION=3.7
ARG CUDA_VERSION=10.2
ARG CUDA_CHANNEL=nvidia
ARG INSTALL_CHANNEL=pytorch-nightly
ENV CONDA_OVERRIDE_CUDA=${CUDA_VERSION}
RUN /opt/conda/bin/conda install -c "${INSTALL_CHANNEL}" -c "${CUDA_CHANNEL}" -y python=${PYTHON_VERSION} pytorch torchvision torchtext "cudatoolkit=${CUDA_VERSION}" && \
    /opt/conda/bin/conda clean -ya
RUN /opt/conda/bin/pip install torchelastic

FROM ${BASE_IMAGE} as official
ARG PYTORCH_VERSION
LABEL com.nvidia.volumes.needed="nvidia_driver"
RUN --mount=type=cache,id=apt-final,target=/var/cache/apt \
    apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        libjpeg-dev \
        libpng-dev && \
    rm -rf /var/lib/apt/lists/*
COPY --from=conda-installs /opt/conda /opt/conda
ENV PATH /opt/conda/bin:$PATH
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV PYTORCH_VERSION ${PYTORCH_VERSION}
WORKDIR /workspace

FROM official as dev
# Should override the already installed version from the official-image stage
COPY --from=build /opt/conda /opt/conda
```

The docker.Makefile I borrowed from the master branch:
```make
DOCKER_REGISTRY           = docker.io
DOCKER_ORG                = $(shell docker info 2>/dev/null | sed '/Username:/!d;s/.* //')
DOCKER_IMAGE              = pytorch
DOCKER_FULL_NAME          = $(DOCKER_REGISTRY)/$(DOCKER_ORG)/$(DOCKER_IMAGE)

ifeq ("$(DOCKER_ORG)","")
$(warning WARNING: No docker user found using results from whoami)
DOCKER_ORG                = $(shell whoami)
endif

CUDA_VERSION              = 10.2
CUDNN_VERSION             = 7
BASE_RUNTIME              = ubuntu:18.04
BASE_DEVEL                = nvidia/cuda:$(CUDA_VERSION)-cudnn$(CUDNN_VERSION)-devel-ubuntu18.04

# The conda channel to use to install cudatoolkit
CUDA_CHANNEL              = nvidia
# The conda channel to use to install pytorch / torchvision
INSTALL_CHANNEL           = pytorch

PYTHON_VERSION            = 3.7
PYTORCH_VERSION           = $(shell git describe --tags --always)
# Can be either official / dev
BUILD_TYPE                = dev
BUILD_PROGRESS            = auto
BUILD_ARGS                = --build-arg BASE_IMAGE=$(BASE_IMAGE) \
							--build-arg PYTHON_VERSION=$(PYTHON_VERSION) \
							--build-arg CUDA_VERSION=$(CUDA_VERSION) \
							--build-arg CUDA_CHANNEL=$(CUDA_CHANNEL) \
							--build-arg PYTORCH_VERSION=$(PYTORCH_VERSION) \
							--build-arg INSTALL_CHANNEL=$(INSTALL_CHANNEL)
EXTRA_DOCKER_BUILD_FLAGS ?=
DOCKER_BUILD              = DOCKER_BUILDKIT=1 \
							docker build \
								--progress=$(BUILD_PROGRESS) \
								$(EXTRA_DOCKER_BUILD_FLAGS) \
								--target $(BUILD_TYPE) \
								-t $(DOCKER_FULL_NAME):$(DOCKER_TAG) \
								$(BUILD_ARGS) .
DOCKER_PUSH               = docker push $(DOCKER_FULL_NAME):$(DOCKER_TAG)

.PHONY: all
all: devel-image

.PHONY: devel-image
devel-image: BASE_IMAGE := $(BASE_DEVEL)
devel-image: DOCKER_TAG := $(PYTORCH_VERSION)-devel
devel-image:
	$(DOCKER_BUILD)

.PHONY: devel-image
devel-push: BASE_IMAGE := $(BASE_DEVEL)
devel-push: DOCKER_TAG := $(PYTORCH_VERSION)-devel
devel-push:
	$(DOCKER_PUSH)

.PHONY: runtime-image
runtime-image: BASE_IMAGE := $(BASE_RUNTIME)
runtime-image: DOCKER_TAG := $(PYTORCH_VERSION)-runtime
runtime-image:
	$(DOCKER_BUILD)
	docker tag $(DOCKER_FULL_NAME):$(DOCKER_TAG) $(DOCKER_FULL_NAME):latest

.PHONY: runtime-image
runtime-push: BASE_IMAGE := $(BASE_RUNTIME)
runtime-push: DOCKER_TAG := $(PYTORCH_VERSION)-runtime
runtime-push:
	$(DOCKER_PUSH)

.PHONY: clean
clean:
	-docker rmi -f $(shell docker images -q $(DOCKER_FULL_NAME))
```

The command to build a docker container then: `make -f docker.Makefile` which translates to

```
DOCKER_BUILDKIT=1 docker build --progress=auto  --target dev -t docker.io/dizcza/pytorch:v1.7.0-devel --build-arg BASE_IMAGE=nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 --build-arg PYTHON_VERSION=3.7 --build-arg CUDA_VERSION=10.2 --build-arg CUDA_CHANNEL=nvidia --build-arg PYTORCH_VERSION=v1.7.0 --build-arg INSTALL_CHANNEL=pytorch .
```

```python
>>> import torch
>>> torch.__version__
'1.7.0a0+e85d494'
>>> torch.cuda.get_device_capability()
(3, 0)
>>> torch.randn(3).cuda()
/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:81: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 760 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
tensor([-0.0445,  0.2598, -1.4096], device='cuda:0')
```

It works despite the warning which can be suppressed by removing the appropriate line in the `torch/cuda/__init__.py` before the build.
