### ISSUE TITLE
torch.cat inconsistent behaviour 

### ISSUE THREAD

**Issue by Nintorac** [pytorch/pytorch#1530]
concatenating an empty Tensor is successful while concatenating an empty Variable is not

>>> tensor1 = torch.FloatTensor()
>>> tensor2 = torch.randn(5,5)
>>> torch.cat([tensor1, tensor2])

>> -0.7869  0.3240 -0.4534 -0.5522  2.5649
>> -1.1812  0.1502  0.5114  0.9978 -0.6617
>> 0.2948 -0.8384 -1.1179 -0.1741 -0.1189
>> 0.5309 -0.5219 -0.2756  1.6858 -0.2393
>> 2.0381  1.0777  2.0937  1.0264  1.1870
>> [torch.FloatTensor of size 5x5]

>>> torch.cat([Variable(tensor1), Variable(tensor2)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/olly/miniconda3/envs/cuda/lib/python3.5/site-packages/torch/autograd/variable.py", line 841, in cat
    return Concat(dim)(*iterable)
  File "/home/olly/miniconda3/envs/cuda/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 309, in forward
    self.input_sizes = [i.size(self.dim) for i in inputs]
  File "/home/olly/miniconda3/envs/cuda/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 309, in <listcomp>
    self.input_sizes = [i.size(self.dim) for i in inputs]
RuntimeError: dimension 0 out of range of 0D tensor at /py/conda-bld/pytorch_1493670682084/work/torch/lib/TH/generic/THTensor.c:24

**Comment by gchanan** [comment]
This works on master.
