### ISSUE TITLE
[jit] torch.jit.trace grad functions: foo.grad_fn

### ISSUE THREAD

**Issue by vinodgro** [pytorch/pytorch#15383]

**Comment by vinodgro** [comment]
I tried this with 1.0

 `import torch
def f(x, y, flag):
    if bool(flag):
        return x * y
    else:
        return x - y


true = torch.tensor([True])
false = torch.tensor([False])

print(f(3.0, 5.0, true))
print(f(3.0, 5.0, false))

t1 = torch.tensor([3.0], requires_grad=True)
t2 = torch.tensor([5.0], requires_grad=True)
print(f(t1, t2, True))
print(f(t1, t2, False))

f1 = torch.jit.trace(f, (t1, t2, true))
f2 = torch.jit.trace(f, (t1, t2, false))

fp = f(t1, t2, true)
ff = torch.jit.trace(fp.grad_fn, ())
print(ff.graph)
print(f2(t1, t2, false))

print(f1.graph)`

get the following error

`Traceback (most recent call last):
  File "C:\data\bar.py", line 24, in <module>
    ff = torch.jit.trace(fp.grad_fn, ())
  File "C:\Users\vgrover\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 632, in trace
    module = TopLevelTracedModule(func, **executor_options)
  File "C:\Users\vgrover\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "C:\Users\vgrover\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 950, in init_then_register
    original_init(self, *args, **kwargs)
  File "C:\Users\vgrover\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 1282, in __init__
    self._name = orig.__name__
AttributeError: 'MulBackward0' object has no attribute '__name__'
`

**Comment by eellison** [comment]
Thanks for the feature request - we will discuss it

**Comment by vinodgro** [comment]
I discussed this with Adam Paszke, and he showed me how to do this in existing PyTorch JIT. So we can close this unless you think you think this is useful
