### ISSUE TITLE
JIT is not compatible with data parallel

### ISSUE THREAD

**Issue by daquexian** [pytorch/pytorch#15421]
## 🐛 Bug

JIT is not compatible with data parallel. So no one can train any model using more than one GPU.

## To Reproduce

1. Use resnet 18 script module from https://github.com/pytorch/pytorch/blob/0b219538cfb70503baa74053d3e827951e0ea6f9/test/test_jit.py#L5882-L5983
1. `model = torch.nn.DataParallel(model)`
1. Get the following error

> Traceback (most recent call last):
>   File "train.py", line 459, in <module>
>     main()
>   File "train.py", line 333, in main
>     train(train_loader, model, criterion, optimizer, epoch)
>   File "train.py", line 394, in train
>     output = model(input)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 142, in forward
>     replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 147, in replicate
>     return replicate(module, device_ids)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/replicate.py", line 31, in replicate
>     replica._parameters = replica._parameters.copy()
> AttributeError: 'OrderedParameterDict' object has no attribute 'copy'

If I firstly run `model = torch.nn.DataParallel(model)` for a nn.Module, then trace it, although the code runs, the loss doesn't decrease.

## Expected behavior

The code runs and the model gets trained

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40

Nvidia driver version: 390.77
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

Related issue: #12875 

Data parallel is such a fundamental module, I can't imagine JIT is not compatible with it and no official programmer have tested it. It makes the JIT totally unpractical for training (except toy models)

**Comment by gqchen** [comment]
Thanks @zdevito for detailed explanation of the problem. The root cause here is script modules currently cannot be properly deep-copied. I will work on fixing the problem.

**Comment by seongwook-ham** [comment]
i am also facing same problem. is there some progress?

**Comment by zdevito** [comment]
We are actively working on a fix, but we do not have a pull request just yet.

**Comment by gqchen** [comment]
PR is almost ready. I would definitely welcome you guys to try it out and
see if it works for you guys.

**Comment by gqchen** [comment]
#16891

**Comment by gqchen** [comment]
@seongwook-ham @daquexian if possible, can you guys try this PR for your case?

**Comment by seongwook-ham** [comment]
following message is printed when i build from this branch 
 File "train.py", line 15, in <module>
    import torch
  File "/home/hsw-server-ubuntu/anaconda3/envs/pytorchjit/lib/python3.6/site-packages/torch/__init__.py", line 279, in <module>
    import torch.nn
  File "/home/hsw-server-ubuntu/anaconda3/envs/pytorchjit/lib/python3.6/site-packages/torch/nn/__init__.py", line 3, in <module>
    from .parallel import DataParallel
  File "/home/hsw-server-ubuntu/anaconda3/envs/pytorchjit/lib/python3.6/site-packages/torch/nn/parallel/__init__.py", line 2, in <module>
    from .replicate import replicate
  File "/home/hsw-server-ubuntu/anaconda3/envs/pytorchjit/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 2, in <module>
    import torch.jit
  File "/home/hsw-server-ubuntu/anaconda3/envs/pytorchjit/lib/python3.6/site-packages/torch/jit/__init__.py", line 11, in <module>
    import torch.nn.functional as functional
AttributeError: module 'torch' has no attribute 'nn'

am i do something wrong? following is building command
conda create -n pytorchjit python=3.6
source activate pytorchjit
conda install scipy
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
conda install -c pytorch magma-cuda100
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git checkout script_module_data_parallel
git submodule update --init --recursive
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install

**Comment by gqchen** [comment]
Let me look into this.

**Comment by gqchen** [comment]
I am able to reproduce it after rebasing to the latest master.

**Comment by gqchen** [comment]
@seongwook-ham In your flow, you need to clone https://github.com/gqchen/pytorch, instead of https://github.com/pytorch/pytorch

**Comment by gqchen** [comment]
@seongwook-ham there is an actual build problem with this PR I'm looking into right now. So please hold on on testing this PR for now.

**Comment by seongwook-ham** [comment]
now is it fixed?

**Comment by gqchen** [comment]
@seongwook-ham while I have good reason to believe this PR fixed the problem, I'm yet to do a complete end-to-end training. I will keep this issue open until I have time to do that. It might be another two weeks before I have time for that. In the meantime, if you can try it out and let me know if it works for you, that would be great.

**Comment by seongwook-ham** [comment]
now is it fixed? i want to use pytorch to serve text analysis model. and it would be nice if i do not need to transform it tensorflow.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
