### ISSUE TITLE
Possible subtle bug in PackedTensorAccessor, or maybe behavior divergence with THDeviceTensor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#15494]
@lhuang04 was working on a port of `replication_pad1d` in https://github.com/pytorch/pytorch/pull/15485 and in the process ported some CUDA code from using THCDeviceTensor to using PackedTensorAccessor. However, the resulting code had memory errors:

```

Dec 21 21:00:33 ======================================================================
Dec 21 21:00:33 ERROR: test_ReplicationPad1d_cuda (__main__.TestNN)
Dec 21 21:00:33 ----------------------------------------------------------------------
Dec 21 21:00:33 Traceback (most recent call last):
Dec 21 21:00:33   File "/var/lib/jenkins/workspace/test/common_utils.py", line 293, in wrapper
Dec 21 21:00:33     method(*args, **kwargs)
Dec 21 21:00:33   File "test_nn.py", line 7173, in <lambda>
Dec 21 21:00:33     add(cuda_test_name, lambda self, test=test, kwargs=kwargs: test.test_cuda(self, **kwargs))
Dec 21 21:00:33   File "/var/lib/jenkins/workspace/test/common_nn.py", line 3063, in test_cuda
Dec 21 21:00:33     gpu_output = test_case._forward(gpu_module, gpu_input)
Dec 21 21:00:33   File "test_nn.py", line 503, in _forward
Dec 21 21:00:33     return module(input)
Dec 21 21:00:33   File "/opt/conda/lib/python3.6/contextlib.py", line 88, in __exit__
Dec 21 21:00:33     next(self.gen)
Dec 21 21:00:33   File "/var/lib/jenkins/workspace/test/common_utils.py", line 201, in freeze_rng_state
Dec 21 21:00:33     torch.cuda.set_rng_state(cuda_rng_state)
Dec 21 21:00:33   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/random.py", line 49, in set_rng_state
Dec 21 21:00:33     _lazy_call(cb)
Dec 21 21:00:33   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 122, in _lazy_call
Dec 21 21:00:33     callable()
Dec 21 21:00:33   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/random.py", line 47, in cb
Dec 21 21:00:33     _C._cuda_setRNGState(new_state_copy)
Dec 21 21:00:33 RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /var/lib/jenkins/workspace/aten/src/THC/THCTensorRandom.cu:92
```

Note that the backtrace is nonsense; we're not running with `CUDA_LAUNCH_BLOCKING=1` I did a decently close read of the diff but could not find any errors. So this may indicate some subtle semantic divergence, or outright bug, in PackedTensorAccessor.

Posting here in case anyone can spot the bug. CC @t-vi

**Comment by t-vi** [comment]
I think the illegal memory access is because the `PackedTensorAccessor`s are passed by reference.
While I admit that it's a bit subtle to find, I think that DeviceTensors worked exactly the same in this respect.

**Comment by t-vi** [comment]
I think this could be closed. :)
