### ISSUE TITLE
target out of bounds error in cross entropy 

### ISSUE THREAD

**Issue by dengzelu** [pytorch/pytorch#15508]
## 🐛 Bug
When using cross entropy loss, I want to set ignore_index=255 and reduction='none' at the same time. However, it doesn't work.

## To Reproduce
``` python
import torch
import torch.nn.functional as F
logits = torch.randn(6, 3)
target = torch.tensor([0, 1, 255, 0, 1, 2]).long()

# this works well
loss_mean = F.cross_entropy(input=logits, target=target, ignore_index=255, reduction='mean')

# not work
loss_none = F.cross_entropy(input=logits, target=target, ignore_index=255, reduction='none')
```
```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-05aa00c09776> in <module>
      8 
      9 # not work
---> 10 loss_none =  F.cross_entropy(input=logits, target=target, ignore_index=255, reduction='none')

~/anaconda3/envs/dzl/lib/python3.7/site-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   1968     if size_average is not None or reduce is not None:
   1969         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 1970     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   1971 
   1972 

~/anaconda3/envs/dzl/lib/python3.7/site-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1788                          .format(input.size(0), target.size(0)))
   1789     if dim == 2:
-> 1790         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   1791     elif dim == 4:
   1792         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: Target 255 out of bounds at /opt/conda/conda-bld/pytorch_1544202130060/work/aten/src/THNN/generic/ClassNLLCriterion.c:56
```

## Environment
 - PyTorch Version: 1.0.0
 - OS: Ubuntu 16.04.5 LTS
 - How you installed PyTorch: conda
 - Build command you used (if compiling from source): none
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0.130/7.4.1
 - GPU models and configuration: GPU 0: TITAN X (Pascal)

**Comment by programehr** [comment]
Hi,
The issue seems to persist in part. Consider the following code:

```
import torch
y=torch.tensor([[1.0,  0,  0, 0],
        [1,  0,  0, 0],
        [1,  0,  0, 0]])
t=torch.tensor([4,4,4],dtype=torch.long)
criterionNR(y, t)

Traceback (most recent call last):

  File "<ipython-input-16-7305794c622d>", line 9, in <module>
    criterionNR(y, t)

  File "C:\Users\Administrator\Anaconda3\envs\base-saremi\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\Administrator\Anaconda3\envs\base-saremi\lib\site-packages\torch\nn\modules\loss.py", line 929, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)

  File "C:\Users\Administrator\Anaconda3\envs\base-saremi\lib\site-packages\torch\nn\functional.py", line 2028, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)

  File "C:\Users\Administrator\Anaconda3\envs\base-saremi\lib\site-packages\torch\nn\functional.py", line 1843, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: Target 4 out of bounds at ..\aten\src\THNN/generic/ClassNLLCriterion.c:55
```



PyTorch Version: 1.0.0.dev20190401
OS: Windows 10
How you installed PyTorch: conda
Build command you used (if compiling from source): none
Python version: 3.7
@soumith 

Sorry, I didn't know if I should have opened a new issue.
Thanks.

**Comment by yuvalkirstain** [comment]
came across the same bug

**Comment by guoriyue** [comment]
same bug！

**Comment by zzzzZZZZ777** [comment]
no error , but get different value when compared with "reduction= mean"
