### ISSUE TITLE
Illegal memory access error when using nn.ConvTranspose2d

### ISSUE THREAD

**Issue by xiaoxiangyeyuwangye** [pytorch/pytorch#15584]
Hi, everyone.
I try to run a cleaner version of pytorch CycleGan implementation in this link:
[https://github.com/aitorzip/PyTorch-CycleGAN](url)
However, during training procedure, I met a error in backward propagation.
`
Traceback (most recent call last):
  File "D:/wangyesFile/pytorchlearning/PyTorch-CycleGAN-master - Copy/train.py", line 165, in <module>
    loss_G.backward()
  File "D:\Python36\lib\site-packages\torch\tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Python36\lib\site-packages\torch\autograd\__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at c:\a\w\1\s\tmp_conda_3.6_091443\conda\conda-bld\pytorch_1544087948354\work\aten\src\thc\generic/THCStorage.cpp:39
`
I have searched this problem with google and found some similar errors when using nn.Conv3d and nn.ConvTranspose3d.
The code in cyclegan utilizes nn.ConvTranspose2d in generator. I wonder if there is a relationship between this error and nn.ConvTranspose2d.
It is a weird problem because it doesn't happen in every training step, and has no rule to follow.
My environment is Win10, pytorch1.0, cuda9.2 and cudnn7.4.
Thanks for any suggestions.

**Comment by SsnL** [comment]
Try running with CUDA_LAUNCH_BLOCKING=1 to locate the exact line that errors.

**Comment by xiaoxiangyeyuwangye** [comment]
Thanks for suggestion. I add 
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
in my script. The error turned to this:

> File "D:/wangyesFile/pytorchlearning/PyTorch-CycleGAN-master - Copy/train.py", line 166, in <module>
    loss_G.backward()
  File "D:\Python36\lib\site-packages\torch\tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Python36\lib\site-packages\torch\autograd\__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

But I still have no idea about why this happen and how to fix it.

**Comment by SsnL** [comment]
After reading @soumith 's comment, I remember that when CUDNN doesn't have enough GPU memory, I also often get `CUDNN_STATUS_EXECUTION_FAILED` error (rather than CUDA OOM). I wonder if it is a CUDNN bug or there is something wrong in our code that allocates the workspace.

**Comment by xiaoxiangyeyuwangye** [comment]
Thanks for your suggestions @soumith . I will try the original cyclegan implementation later. In fact, I have checked the original implementation and the cleaner implementation. Although the codes seems different, the framework and loss function are totally the same.I just modify the cleaner implementation a little such as replacing 'Variable' With 'Tensor' because we use pytorch 1.0. I think I will meet the same issue. I will also try 'torch.backends.cudnn.benchmark=False'. I will do more test.
@SsnL I am not sure it is a CUDNN bug or due to our code. The code in cleaner cyclegan is really simple and easy to read. I don't think this issue is due to the code of cleaner cyclegan.

**Comment by xiaoxiangyeyuwangye** [comment]
@SsnL @soumith I did some more tests. I first monitored the memory during training. My GPU has 12GB memory and about 8.8 GB was employed during training. So I don't think this issue is due to out of memory. Then I add 'torch.backends.cudnn.benchmark=False' in my script, this error still raised. Finally I add 'torch.backends.cudnn.enaled=False' in my script, but it seems that the employed memory when training without cudnn (only with cuda) is much larger then that with cudnn. It even can not run one step because of out of memory in the final case.
I will try the original cyclegan later, hope something different may happen.

**Comment by xiaoxiangyeyuwangye** [comment]
I just tried the original cyclegan, but the error still happened.

**Comment by xiaoxiangyeyuwangye** [comment]
Is there any advice? I am still stuck in this issue.

**Comment by xiaoxiangyeyuwangye** [comment]
@SsnL @soumith Is it possible that this issue is caused by the incompatibility of graphic card driver version,  cuda version, cudnn version and pytorch version? I have tried many times with many different conditions, but this error still raised.

**Comment by xiaoxiangyeyuwangye** [comment]
It is strange that I have trained pytorch version Faster RCNN with the same condition. No error happened.

**Comment by andravin** [comment]
I wonder if it is possible for you to test a different kernel size in the nn.ConvTranspose2d layer. For example, if you are currently using kernel size 3 and stride 2 padding 1, try kernel size 2 and stride 2 padding 0 instead. I have experienced weird crashes in my own networks for certain combinations of nn.ConvTranspose2d parameters.

It would also be useful to generate the smallest possible sample code that reproduces the problem, so that others could easily test.

**Comment by batmanfightpredator** [comment]
@xiaoxiangyeyuwangye Is it possible caused by multi-GPU?I meet the same quesion. My code run well in  one 1060, but get same error when run in two GPU with same condition. Have you solved this error?
