### ISSUE TITLE
TensorIterator giving FloatingPointException

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#15599]
## 🐛 Bug

TensorIterator giving FloatingPointException-->

## To Reproduce

```python
import torch
batch_size = 16
lstm_hidden_size = 32
input_size = 8
output_size = 8
device = torch.device('cpu')
lstm_cell = torch.nn.LSTMCell(input_size + output_size, lstm_hidden_size).to(device)
predict_halt = torch.nn.Sequential(torch.nn.Linear(lstm_hidden_size, 1),
                                   torch.nn.Sigmoid()).to(device)
kwargs = {'device': device}
next_lstm_hidden_state = torch.zeros(batch_size, lstm_hidden_size, **kwargs)
next_lstm_cell_state = torch.zeros(batch_size, lstm_hidden_size, **kwargs)
lstm_hidden_state = torch.zeros(batch_size, lstm_hidden_size, **kwargs)
lstm_cell_state = torch.zeros(batch_size, lstm_hidden_size, **kwargs)
halt_cumulative = torch.zeros(batch_size, **kwargs)
halted = torch.zeros(batch_size, **kwargs).byte()
# Break on exceeding output or input
for i in range(10):
    input_ = torch.rand(batch_size, input_size, requires_grad=True, **kwargs)
    output = torch.rand(batch_size, output_size, requires_grad=True, **kwargs)
    # [batch_size, input_size + output_size]
    # Embedding of the current output and input state
    lstm_input = torch.cat((input_, output), dim=1)
    # lstm_hidden_state [batch_size, lstm_hidden_size]
    # lstm_cell_state [batch_size, lstm_hidden_size]
    lstm_hidden_state, lstm_cell_state = lstm_cell(lstm_input, (lstm_hidden_state, lstm_cell_state))
    #
    halt_probability = predict_halt(lstm_hidden_state)
    remainder = 1 - halt_cumulative
    halt_cumulative += torch.min(halt_probability.squeeze(1), remainder)
    halted = halt_cumulative.ge(1 - 0.01)
    # Update hidden state with remainder for ``halted`` sequences
    next_lstm_hidden_state[halted] = (lstm_hidden_state * remainder.unsqueeze(1))[halted]
    next_lstm_cell_state[halted] = (lstm_cell_state * remainder.unsqueeze(1))[halted]
    # Update hidden state with ``halt_probability`` for other sequences
    next_lstm_hidden_state[~halted] = (lstm_hidden_state * halt_probability)[~halted]
    next_lstm_cell_state[~halted] = (lstm_cell_state * halt_probability)[~halted]
    # Reset state for ``halted`` sequences, next hidden state is an accumulation from the
    # past states

    lstm_hidden_state[halted] = next_lstm_hidden_state[halted]
    lstm_cell_state[halted] = next_lstm_cell_state[halted]
    halt_cumulative = halt_cumulative.masked_fill(halted, 0)
    next_lstm_hidden_state = next_lstm_hidden_state.masked_fill(halted.unsqueeze(1), 0)
    next_lstm_cell_state = next_lstm_cell_state.masked_fill(halted.unsqueeze(1), 0)
lstm_hidden_state.sum().backward()
```

Stack Trace:

```
[Switching to Thread 0x7fffab235700 (LWP 42098)]
0x00007fffb72eb7d2 in at::DimCounter::DimCounter(c10::ArrayRef<long>, at::Range) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
(gdb) bt
#0  0x00007fffb72eb7d2 in at::DimCounter::DimCounter(c10::ArrayRef<long>, at::Range) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#1  0x00007fffb72ebf12 in at::TensorIterator::serial_for_each(std::function<void (int, char**, long const*, long, long)> const&, at::Range) const () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#2  0x00007fffb72ed433 in at::TensorIterator::serial_for_each(std::function<void (int, char**, long const*, long)> const&, at::Range) const () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#3  0x00007fffb7a98aad in at::native::(anonymous namespace)::index_put_kernel(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#4  0x00007fffb724b003 in void at::native::DispatchStub<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, bool), at::native::index_put_stub>::operator()<at::TensorIterator&, c10::SmallVector<long, 5u>&, c10::SmallVector<long, 5u>&, bool&>(c10::DeviceType, at::TensorIterator&, c10::SmallVector<long, 5u>&, c10::SmallVector<long, 5u>&, bool&) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#5  0x00007fffb7247d47 in at::native::index_put_(at::Tensor&, c10::ArrayRef<at::Tensor>, at::Tensor const&, bool) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#6  0x00007fffb74ba7d5 in at::TypeDefault::index_put_(at::Tensor&, c10::ArrayRef<at::Tensor>, at::Tensor const&, bool) const () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so
#7  0x00007fffb3fd031e in torch::autograd::VariableType::index_put_(at::Tensor&, c10::ArrayRef<at::Tensor>, at::Tensor const&, bool) const () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libtorch.so.1
#8  0x00007fffb3ef71b4 in torch::autograd::generated::IndexBackward::apply(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> >&&) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libtorch.so.1
#9  0x00007fffb3e9b7a6 in torch::autograd::Engine::evaluate_function(torch::autograd::FunctionTask&) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libtorch.so.1
#10 0x00007fffb3e9d880 in torch::autograd::Engine::thread_main(torch::autograd::GraphTask*) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libtorch.so.1
#11 0x00007fffb3e9a247 in torch::autograd::Engine::thread_init(int) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libtorch.so.1
#12 0x00007fffe6f63d1a in torch::autograd::python::PythonEngine::thread_init(int) () from /scratch/soumith/miniconda2/lib/python2.7/site-packages/torch/lib/libtorch_python.so
#13 0x00007fffe7eee678 in std::execute_native_thread_routine_compat (__p=<optimized out>) at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/thread.cc:94
#14 0x00007ffff7ba46ba in start_thread (arg=0x7fffab235700) at pthread_create.c:333
#15 0x00007ffff71ca41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) quit
```

## Expected behavior

No FPE

Originally reported by @PetrochukM

**Comment by soumith** [comment]
cc: @umanwizard @colesbury

**Comment by soumith** [comment]
As @colesbury told me (and I verified), this was fixed on master, and is party of the nightly builds.
It was fixed via https://github.com/pytorch/pytorch/pull/14986
