### ISSUE TITLE
RuntimeError: cudnn RNN backward can only be called in training mode

### ISSUE THREAD

**Issue by park-sj** [pytorch/pytorch#15788]
Hi, I need a help for visualizing of feature map, using Grad-CAM.
I have problem on my code, please help me.
I attach my code.

import torch
from torch.autograd import Variable
from torch.autograd import Function
from torchvision import models
from torchvision import utils
import cv2
import sys
import numpy as np
import argparse
import torch.nn as nn

learning_rate = 0.0002
num_epoch = 50
num_category = 30
img_dir = "D:\AID"
batch_size = 1
num_layers = 1
channel_input_size = 1
channel_hidden_size = 1
spatial_input_size = 1
spatial_hidden_size = 1

class RNN(nn.Module):
    def __init__(self):
        super(RNN, self).__init__()

        self.channel_hidden_size = channel_hidden_size
        self.spatial_hidden_size = spatial_hidden_size
        self.num_layers = num_layers

        self.channel_GRU = nn.GRU(channel_input_size, channel_hidden_size, num_layers, batch_first=True, bidirectional=True).cuda()

        self.sequence_length = self.depth = 1
        self.width_height = self.width = self.height = 1

        self.sigmoid = nn.Sigmoid()
        self.softmax = nn.Softmax()
        self.ReLU = nn.ReLU()

    def init_h0_channel(self):
        return Variable(torch.zeros(self.num_layers*2, self.depth, self.channel_hidden_size)).cuda()

    def attention(self, input, att):
        return input * att

    def Avg_pooling_channel(self, input):
        Avg_channal = nn.AvgPool2d(kernel_size=self.width_height, stride=1, padding=0)
        output = Avg_channal(input)
        return output

    def Max_pooling_channel(self, input):
        Max_channal = nn.MaxPool2d(kernel_size=self.width_height, stride=1, padding=0)
        output = Max_channal(input)
        return output

    def channel_attention(self, input):

        h0_channel = self.init_h0_channel()

        avg_channel = self.Avg_pooling_channel(input).view(batch_size, self.depth, -1).permute(1, 0, 2)
        max_channel = self.Max_pooling_channel(input).view(batch_size, self.depth, -1).permute(1, 0, 2)

        output, _ = self.channel_GRU(avg_channel, h0_channel) #output (seq_len, batch, hidden_size * num_directions)
        avg_fusion = output[:, :, 0] + output[:, :, 1]

        output, _ = self.channel_GRU(max_channel)
        max_fusion = output[:, :, 0] + output[:, :, 1]

        fusion = avg_fusion + max_fusion

        #temp = self.sigmoid(fusion.view(channel_hidden_size, self.depth, 1, 1))
        temp = self.sigmoid(fusion.permute(1, 0).view(batch_size, self.depth, 1, 1))
        out = self.attention(input, temp)

        return out

    def forward(self, input):
        self.sequence_length = self.depth = input.size()[1]
        self.width_height = self.width = self.height = input.size()[2]

        out = self.channel_attention(input)
        #out = self.spatial_attention(out)

        return out

class RNN_FC(nn.Module):
    def __init__(self):
        super(RNN_FC, self).__init__()
        self.RNN_attention = nn.Sequential(
            RNN(),
        )

    def forward(self, x):
        out = self.RNN_attention(x)
        return out

Densenet16 = models.densenet161(pretrained=True)

class Densenet161_ch_ver1(nn.Module):
    def __init__(self):
        super(Densenet161_ch_ver1, self).__init__()
        self.layer0 = nn.Sequential(nn.Sequential(*list(Densenet16.children())[0])[0:5],
                                    RNN_FC(),
                                    nn.Sequential(*list(Densenet16.children())[0])[5:7],
                                    RNN_FC(),
                                    nn.Sequential(*list(Densenet16.children())[0])[7:9],
                                    RNN_FC(),
                                    nn.Sequential(*list(Densenet16.children())[0])[9:11],
                                    RNN_FC(),
                                    nn.Sequential(*list(Densenet16.children())[0])[11],
                                    nn.AvgPool2d(kernel_size=7, stride=1, padding=0)
        )
        self.fc = nn.Sequential(
            nn.Linear(2208, 500),
            nn.BatchNorm1d(500),
            nn.ReLU(),
            nn.Linear(500, num_category),
            nn.ReLU()
        )

    def forward(self, x):
        out = self.layer0(x)
        out = out.view(batch_size, -1)
        out = self.fc(out)
        return out

class FeatureExtractor():
    """ Class for extracting activations and
    registering gradients from targetted intermediate layers """
    def __init__(self, model, target_layers):
        self.model = model
        self.target_layers = target_layers
        self.gradients = []

    def save_gradient(self, grad):
    	self.gradients.append(grad)

    def __call__(self, x):
        outputs = []
        self.gradients = []
        for name, module in self.model._modules.items():
            x = module(x)
            if name in self.target_layers:
                x.register_hook(self.save_gradient)
                outputs += [x]
        return outputs, x

class ModelOutputs():
	""" Class for making a forward pass, and getting:
	1. The network output.
	2. Activations from intermeddiate targetted layers.
	3. Gradients from intermeddiate targetted layers. """
	def __init__(self, model, target_layers):
		self.model = model

		self.feature_extractor = FeatureExtractor(nn.Sequential(*list(self.model.children())[0]), target_layers)

	def get_gradients(self):
		return self.feature_extractor.gradients

	def __call__(self, x):
		target_activations, output = self.feature_extractor(x)
		output = output.view(output.size(0), -1)
		output = nn.Sequential(*list(self.model.children())[1])(output)
		return target_activations, output

def preprocess_image(img):
	means=[0.485, 0.456, 0.406]
	stds=[0.229, 0.224, 0.225]

	preprocessed_img = img.copy()[: , :, ::-1]
	for i in range(3):
		preprocessed_img[:, :, i] = preprocessed_img[:, :, i] - means[i]
		preprocessed_img[:, :, i] = preprocessed_img[:, :, i] / stds[i]
	preprocessed_img = \
		np.ascontiguousarray(np.transpose(preprocessed_img, (2, 0, 1)))
	preprocessed_img = torch.from_numpy(preprocessed_img)
	preprocessed_img.unsqueeze_(0)
	input = Variable(preprocessed_img, requires_grad = True)
	return input

def show_cam_on_image(img, mask):
	heatmap = cv2.applyColorMap(np.uint8(255*mask), cv2.COLORMAP_JET)
	heatmap = np.float32(heatmap) / 255
	cam = heatmap + np.float32(img)
	cam = cam / np.max(cam)
	cv2.imwrite("cam.jpg", np.uint8(255 * cam))

class GradCam:
	def __init__(self, model, target_layer_names, use_cuda):
		self.model = model
		self.model.eval()
		self.cuda = use_cuda
		if self.cuda:
			self.model = model.cuda()

		self.extractor = ModelOutputs(self.model, target_layer_names)

	def forward(self, input):
		return self.model(input)

	def __call__(self, input, index = None):
		if self.cuda:
			features, output = self.extractor(input.cuda())
		else:
			features, output = self.extractor(input)

		if index == None:
			index = np.argmax(output.cpu().data.numpy())

		one_hot = np.zeros((1, output.size()[-1]), dtype=np.float32)
		one_hot[0][index] = 1
		one_hot = Variable(torch.from_numpy(one_hot), requires_grad=True)
		if self.cuda:
			one_hot = torch.sum(one_hot.cuda() * output)
		else:
			one_hot = torch.sum(one_hot * output)

		nn.Sequential(*list(self.model.children())[0]).zero_grad()
		nn.Sequential(*list(self.model.children())[1]).zero_grad()
		one_hot.backward()

		grads_val = self.extractor.get_gradients()[-1].cpu().data.numpy()

		target = features[-1]
		target = target.cpu().data.numpy()[0, :]

		weights = np.mean(grads_val, axis = (2, 3))[0, :]
		cam = np.zeros(target.shape[1 : ], dtype = np.float32)

		for i, w in enumerate(weights):
			cam += w * target[i, :, :]

		cam = np.maximum(cam, 0)
		cam = cv2.resize(cam, (224, 224))
		cam = cam - np.min(cam)
		cam = cam / np.max(cam)
		return cam

class GuidedBackpropReLU(Function):

    def forward(self, input):
        positive_mask = (input > 0).type_as(input)
        output = torch.addcmul(torch.zeros(input.size()).type_as(input), input, positive_mask)
        self.save_for_backward(input, output)
        return output

    def backward(self, grad_output):
        input, output = self.saved_tensors
        grad_input = None

        positive_mask_1 = (input > 0).type_as(grad_output)
        positive_mask_2 = (grad_output > 0).type_as(grad_output)
        grad_input = torch.addcmul(torch.zeros(input.size()).type_as(input), torch.addcmul(torch.zeros(input.size()).type_as(input), grad_output, positive_mask_1), positive_mask_2)

        return grad_input

class GuidedBackpropReLUModel:
	def __init__(self, model, use_cuda):
		self.model = model
		self.model.eval()
		self.cuda = use_cuda
		if self.cuda:
			self.model = model.cuda()

		# replace ReLU with GuidedBackpropReLU
		for idx, module in nn.Sequential(*list(self.model.children())[0])._modules.items():
			if module.__class__.__name__ == 'ReLU':
				self.model.features._modules[idx] = GuidedBackpropReLU()

	def forward(self, input):
		return self.model(input)

	def __call__(self, input, index = None):
		if self.cuda:
			output = self.forward(input.cuda())
		else:
			output = self.forward(input)

		if index == None:
			index = np.argmax(output.cpu().data.numpy())

		one_hot = np.zeros((1, output.size()[-1]), dtype = np.float32)
		one_hot[0][index] = 1
		one_hot = Variable(torch.from_numpy(one_hot), requires_grad = True)
		if self.cuda:
			one_hot = torch.sum(one_hot.cuda() * output)
		else:
			one_hot = torch.sum(one_hot * output)

		# self.model.features.zero_grad()
		# self.model.classifier.zero_grad()
		one_hot.backward()

		output = input.grad.cpu().data.numpy()
		output = output[0,:,:,:]

		return output

def get_args():
	parser = argparse.ArgumentParser()
	parser.add_argument('--use-cuda', action='store_true', default=False,
	                    help='Use NVIDIA GPU acceleration')
	parser.add_argument('--image-path', type=str, default='./examples/bridge_17.jpg',
	                    help='Input image path')
	args = parser.parse_args()
	args.use_cuda = args.use_cuda and torch.cuda.is_available()
	if args.use_cuda:
	    print("Using GPU for acceleration")
	else:
	    print("Using CPU for computation")

	return args

def run():
	""" python grad_cam.py <path_to_image>
	1. Loads an image with opencv.
	2. Preprocesses it for VGG19 and converts to a pytorch variable.
	3. Makes a forward pass to find the category index with the highest score,
	and computes intermediate activations.
	Makes the visualization. """

	args = get_args()

	# Can work with any model, but it assumes that the model has a
	# feature method, and a classifier method,
	# as in the VGG models in torchvision.

	ch_ver1 = Densenet161_ch_ver1()
	ch_ver1 = torch.load('./Densenet161_ch_ver1_044.pkl')

	grad_cam = GradCam(model = ch_ver1, target_layer_names = ["8"], use_cuda=args.use_cuda)

	img = cv2.imread(args.image_path, 1)
	img = np.float32(cv2.resize(img, (224, 224))) / 255
	input = preprocess_image(img)

	# If None, returns the map for the highest scoring category.
	# Otherwise, targets the requested index.
	target_index = None

	mask = grad_cam(input, target_index)

	show_cam_on_image(img, mask)

	gb_model = GuidedBackpropReLUModel(model=ch_ver1, use_cuda=args.use_cuda)
	gb = gb_model(input, index=target_index)
	utils.save_image(torch.from_numpy(gb), 'gb.jpg')

	cam_mask = np.zeros(gb.shape)
	for i in range(0, gb.shape[0]):
	    cam_mask[i, :, :] = mask

	cam_gb = np.multiply(cam_mask, gb)
	utils.save_image(torch.from_numpy(cam_gb), 'cam_gb.jpg')

if __name__ == '__main__':
    run()

---------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "grad-cam.py", line 359, in <module>
    run()
  File "grad-cam.py", line 343, in run
    mask = grad_cam(input, target_index)
  File "grad-cam.py", line 222, in __call__
    one_hot.backward()
  File "C:\Users\Sung-Jun Park\Anaconda3\envs\pytorch\lib\site-packages\torch\tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\Sung-Jun Park\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cudnn RNN backward can only be called in training mode

**Comment by park-sj** [comment]
> Hi, I need a help for visualizing of feature map, using Grad-CAM.
> I have problem on my code, please help me.
> I attach my code.
> 
> import torch
> from torch.autograd import Variable
> from torch.autograd import Function
> from torchvision import models
> from torchvision import utils
> import cv2
> import sys
> import numpy as np
> import argparse
> import torch.nn as nn
> 
> learning_rate = 0.0002
> num_epoch = 50
> num_category = 30
> img_dir = "D:\AID"
> batch_size = 1
> num_layers = 1
> channel_input_size = 1
> channel_hidden_size = 1
> spatial_input_size = 1
> spatial_hidden_size = 1
> 
> class RNN(nn.Module):
> def **init**(self):
> super(RNN, self).**init**()
> 
> ```
>     self.channel_hidden_size = channel_hidden_size
>     self.spatial_hidden_size = spatial_hidden_size
>     self.num_layers = num_layers
> 
>     self.channel_GRU = nn.GRU(channel_input_size, channel_hidden_size, num_layers, batch_first=True, bidirectional=True).cuda()
> 
>     self.sequence_length = self.depth = 1
>     self.width_height = self.width = self.height = 1
> 
>     self.sigmoid = nn.Sigmoid()
>     self.softmax = nn.Softmax()
>     self.ReLU = nn.ReLU()
> 
> def init_h0_channel(self):
>     return Variable(torch.zeros(self.num_layers*2, self.depth, self.channel_hidden_size)).cuda()
> 
> def attention(self, input, att):
>     return input * att
> 
> def Avg_pooling_channel(self, input):
>     Avg_channal = nn.AvgPool2d(kernel_size=self.width_height, stride=1, padding=0)
>     output = Avg_channal(input)
>     return output
> 
> def Max_pooling_channel(self, input):
>     Max_channal = nn.MaxPool2d(kernel_size=self.width_height, stride=1, padding=0)
>     output = Max_channal(input)
>     return output
> 
> def channel_attention(self, input):
> 
>     h0_channel = self.init_h0_channel()
> 
>     avg_channel = self.Avg_pooling_channel(input).view(batch_size, self.depth, -1).permute(1, 0, 2)
>     max_channel = self.Max_pooling_channel(input).view(batch_size, self.depth, -1).permute(1, 0, 2)
> 
>     output, _ = self.channel_GRU(avg_channel, h0_channel) #output (seq_len, batch, hidden_size * num_directions)
>     avg_fusion = output[:, :, 0] + output[:, :, 1]
> 
>     output, _ = self.channel_GRU(max_channel)
>     max_fusion = output[:, :, 0] + output[:, :, 1]
> 
>     fusion = avg_fusion + max_fusion
> 
>     #temp = self.sigmoid(fusion.view(channel_hidden_size, self.depth, 1, 1))
>     temp = self.sigmoid(fusion.permute(1, 0).view(batch_size, self.depth, 1, 1))
>     out = self.attention(input, temp)
> 
>     return out
> 
> def forward(self, input):
>     self.sequence_length = self.depth = input.size()[1]
>     self.width_height = self.width = self.height = input.size()[2]
> 
>     out = self.channel_attention(input)
>     #out = self.spatial_attention(out)
> 
>     return out
> ```
> class RNN_FC(nn.Module):
> def **init**(self):
> super(RNN_FC, self).**init**()
> self.RNN_attention = nn.Sequential(
> RNN(),
> )
> 
> ```
> def forward(self, x):
>     out = self.RNN_attention(x)
>     return out
> ```
> Densenet16 = models.densenet161(pretrained=True)
> 
> class Densenet161_ch_ver1(nn.Module):
> def **init**(self):
> super(Densenet161_ch_ver1, self).**init**()
> self.layer0 = nn.Sequential(nn.Sequential(*list(Densenet16.children())[0])[0:5],
> RNN_FC(),
> nn.Sequential(*list(Densenet16.children())[0])[5:7],
> RNN_FC(),
> nn.Sequential(*list(Densenet16.children())[0])[7:9],
> RNN_FC(),
> nn.Sequential(*list(Densenet16.children())[0])[9:11],
> RNN_FC(),
> nn.Sequential(*list(Densenet16.children())[0])[11],
> nn.AvgPool2d(kernel_size=7, stride=1, padding=0)
> )
> self.fc = nn.Sequential(
> nn.Linear(2208, 500),
> nn.BatchNorm1d(500),
> nn.ReLU(),
> nn.Linear(500, num_category),
> nn.ReLU()
> )
> 
> ```
> def forward(self, x):
>     out = self.layer0(x)
>     out = out.view(batch_size, -1)
>     out = self.fc(out)
>     return out
> ```
> class FeatureExtractor():
> """ Class for extracting activations and
> registering gradients from targetted intermediate layers """
> def **init**(self, model, target_layers):
> self.model = model
> self.target_layers = target_layers
> self.gradients = []
> 
> ```
> def save_gradient(self, grad):
> 	self.gradients.append(grad)
> 
> def __call__(self, x):
>     outputs = []
>     self.gradients = []
>     for name, module in self.model._modules.items():
>         x = module(x)
>         if name in self.target_layers:
>             x.register_hook(self.save_gradient)
>             outputs += [x]
>     return outputs, x
> ```
> class ModelOutputs():
> """ Class for making a forward pass, and getting:
> 1. The network output.
> 2. Activations from intermeddiate targetted layers.
> 3. Gradients from intermeddiate targetted layers. """
> def **init**(self, model, target_layers):
> self.model = model
> 
> ```
> 	self.feature_extractor = FeatureExtractor(nn.Sequential(*list(self.model.children())[0]), target_layers)
> 
> def get_gradients(self):
> 	return self.feature_extractor.gradients
> 
> def __call__(self, x):
> 	target_activations, output = self.feature_extractor(x)
> 	output = output.view(output.size(0), -1)
> 	output = nn.Sequential(*list(self.model.children())[1])(output)
> 	return target_activations, output
> ```
> def preprocess_image(img):
> means=[0.485, 0.456, 0.406]
> stds=[0.229, 0.224, 0.225]
> 
> ```
> preprocessed_img = img.copy()[: , :, ::-1]
> for i in range(3):
> 	preprocessed_img[:, :, i] = preprocessed_img[:, :, i] - means[i]
> 	preprocessed_img[:, :, i] = preprocessed_img[:, :, i] / stds[i]
> preprocessed_img = \
> 	np.ascontiguousarray(np.transpose(preprocessed_img, (2, 0, 1)))
> preprocessed_img = torch.from_numpy(preprocessed_img)
> preprocessed_img.unsqueeze_(0)
> input = Variable(preprocessed_img, requires_grad = True)
> return input
> ```
> def show_cam_on_image(img, mask):
> heatmap = cv2.applyColorMap(np.uint8(255*mask), cv2.COLORMAP_JET)
> heatmap = np.float32(heatmap) / 255
> cam = heatmap + np.float32(img)
> cam = cam / np.max(cam)
> cv2.imwrite("cam.jpg", np.uint8(255 * cam))
> 
> class GradCam:
> def **init**(self, model, target_layer_names, use_cuda):
> self.model = model
> self.model.eval()
> self.cuda = use_cuda
> if self.cuda:
> self.model = model.cuda()
> 
> ```
> 	self.extractor = ModelOutputs(self.model, target_layer_names)
> 
> def forward(self, input):
> 	return self.model(input)
> 
> def __call__(self, input, index = None):
> 	if self.cuda:
> 		features, output = self.extractor(input.cuda())
> 	else:
> 		features, output = self.extractor(input)
> 
> 	if index == None:
> 		index = np.argmax(output.cpu().data.numpy())
> 
> 	one_hot = np.zeros((1, output.size()[-1]), dtype=np.float32)
> 	one_hot[0][index] = 1
> 	one_hot = Variable(torch.from_numpy(one_hot), requires_grad=True)
> 	if self.cuda:
> 		one_hot = torch.sum(one_hot.cuda() * output)
> 	else:
> 		one_hot = torch.sum(one_hot * output)
> 
> 	nn.Sequential(*list(self.model.children())[0]).zero_grad()
> 	nn.Sequential(*list(self.model.children())[1]).zero_grad()
> 	one_hot.backward()
> 
> 	grads_val = self.extractor.get_gradients()[-1].cpu().data.numpy()
> 
> 	target = features[-1]
> 	target = target.cpu().data.numpy()[0, :]
> 
> 	weights = np.mean(grads_val, axis = (2, 3))[0, :]
> 	cam = np.zeros(target.shape[1 : ], dtype = np.float32)
> 
> 	for i, w in enumerate(weights):
> 		cam += w * target[i, :, :]
> 
> 	cam = np.maximum(cam, 0)
> 	cam = cv2.resize(cam, (224, 224))
> 	cam = cam - np.min(cam)
> 	cam = cam / np.max(cam)
> 	return cam
> ```
> class GuidedBackpropReLU(Function):
> 
> ```
> def forward(self, input):
>     positive_mask = (input > 0).type_as(input)
>     output = torch.addcmul(torch.zeros(input.size()).type_as(input), input, positive_mask)
>     self.save_for_backward(input, output)
>     return output
> 
> def backward(self, grad_output):
>     input, output = self.saved_tensors
>     grad_input = None
> 
>     positive_mask_1 = (input > 0).type_as(grad_output)
>     positive_mask_2 = (grad_output > 0).type_as(grad_output)
>     grad_input = torch.addcmul(torch.zeros(input.size()).type_as(input), torch.addcmul(torch.zeros(input.size()).type_as(input), grad_output, positive_mask_1), positive_mask_2)
> 
>     return grad_input
> ```
> class GuidedBackpropReLUModel:
> def **init**(self, model, use_cuda):
> self.model = model
> self.model.eval()
> self.cuda = use_cuda
> if self.cuda:
> self.model = model.cuda()
> 
> ```
> 	# replace ReLU with GuidedBackpropReLU
> 	for idx, module in nn.Sequential(*list(self.model.children())[0])._modules.items():
> 		if module.__class__.__name__ == 'ReLU':
> 			self.model.features._modules[idx] = GuidedBackpropReLU()
> 
> def forward(self, input):
> 	return self.model(input)
> 
> def __call__(self, input, index = None):
> 	if self.cuda:
> 		output = self.forward(input.cuda())
> 	else:
> 		output = self.forward(input)
> 
> 	if index == None:
> 		index = np.argmax(output.cpu().data.numpy())
> 
> 	one_hot = np.zeros((1, output.size()[-1]), dtype = np.float32)
> 	one_hot[0][index] = 1
> 	one_hot = Variable(torch.from_numpy(one_hot), requires_grad = True)
> 	if self.cuda:
> 		one_hot = torch.sum(one_hot.cuda() * output)
> 	else:
> 		one_hot = torch.sum(one_hot * output)
> 
> 	# self.model.features.zero_grad()
> 	# self.model.classifier.zero_grad()
> 	one_hot.backward()
> 
> 	output = input.grad.cpu().data.numpy()
> 	output = output[0,:,:,:]
> 
> 	return output
> ```
> def get_args():
> parser = argparse.ArgumentParser()
> parser.add_argument('--use-cuda', action='store_true', default=False,
> help='Use NVIDIA GPU acceleration')
> parser.add_argument('--image-path', type=str, default='./examples/bridge_17.jpg',
> help='Input image path')
> args = parser.parse_args()
> args.use_cuda = args.use_cuda and torch.cuda.is_available()
> if args.use_cuda:
> print("Using GPU for acceleration")
> else:
> print("Using CPU for computation")
> 
> ```
> return args
> ```
> def run():
> """ python grad_cam.py <path_to_image>
> 1. Loads an image with opencv.
> 2. Preprocesses it for VGG19 and converts to a pytorch variable.
> 3. Makes a forward pass to find the category index with the highest score,
> and computes intermediate activations.
> Makes the visualization. """
> 
> ```
> args = get_args()
> 
> # Can work with any model, but it assumes that the model has a
> # feature method, and a classifier method,
> # as in the VGG models in torchvision.
> 
> ch_ver1 = Densenet161_ch_ver1()
> ch_ver1 = torch.load('./Densenet161_ch_ver1_044.pkl')
> 
> grad_cam = GradCam(model = ch_ver1, target_layer_names = ["8"], use_cuda=args.use_cuda)
> 
> img = cv2.imread(args.image_path, 1)
> img = np.float32(cv2.resize(img, (224, 224))) / 255
> input = preprocess_image(img)
> 
> # If None, returns the map for the highest scoring category.
> # Otherwise, targets the requested index.
> target_index = None
> 
> mask = grad_cam(input, target_index)
> 
> show_cam_on_image(img, mask)
> 
> gb_model = GuidedBackpropReLUModel(model=ch_ver1, use_cuda=args.use_cuda)
> gb = gb_model(input, index=target_index)
> utils.save_image(torch.from_numpy(gb), 'gb.jpg')
> 
> cam_mask = np.zeros(gb.shape)
> for i in range(0, gb.shape[0]):
>     cam_mask[i, :, :] = mask
> 
> cam_gb = np.multiply(cam_mask, gb)
> utils.save_image(torch.from_numpy(cam_gb), 'cam_gb.jpg')
> ```
> if **name** == '**main**':
> run()
> 
> Traceback (most recent call last):
> File "grad-cam.py", line 359, in 
> run()
> File "grad-cam.py", line 343, in run
> mask = grad_cam(input, target_index)
> File "grad-cam.py", line 222, in **call**
> one_hot.backward()
> File "C:\Users\Sung-Jun Park\Anaconda3\envs\pytorch\lib\site-packages\torch\tensor.py", line 93, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "C:\Users\Sung-Jun Park\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd__init__.py", line 90, in backward
> allow_unreachable=True) # allow_unreachable flag
> RuntimeError: cudnn RNN backward can only be called in training mode
