### ISSUE TITLE
[JIT] Type annotation breaks Python Values

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#15809]
## Version 1: no type annotation; works as expected

```
class PythonValuesJIT1(torch.jit.ScriptModule):
    __constants__ = ['training_now']
    def __init__(self):
        super(PythonValuesJIT1, self).__init__()
        self.training_now = True
        self.lnorm = nn.LayerNorm([10, 10, 10])

    @torch.jit.script_method
    def forward(self, x):
        if self.training_now is not None:
            # I expect this function to be treated as python value
            # and therefore just don't care about it
            return self.training_only_code(x)

        return x

    def training_only_code(self, x):

        # do some torchscript incompatible logic
        arr = [1,2,3]
        for i, k in enumerate(arr):
            x[k] += x[k]

        return x

print PythonValuesJIT1().graph
```
```
## This works as we know the training_only_code is a python_value
graph(%x : Tensor) {
  %4 : Tensor = ^training_only_code()(%x)
  return (%4);
}
```

## Version 2: type annotation with list; breaks python values

```
class PythonValuesJIT2(torch.jit.ScriptModule):
    __constants__ = ['training_now']
    def __init__(self):
        super(PythonValuesJIT2, self).__init__()
        self.training_now = True
        self.lnorm = nn.LayerNorm([10, 10, 10])

    @torch.jit.script_method
    def forward(self, x):
        # type: (List[torch.Tensor]) -> List[torch.Tensor]

        if self.training_now is not None:
            # I expect this function to be treated as python value
            # and therefore just don't care about it
            return self.training_only_code(x)

        return x

    def training_only_code(self, x):
        # do some torchscript incompatible logic
        arr = [1,2,3]
        for i, k in enumerate(arr):
            x[k] += x[k]

        return x

print PythonValuesJIT2().graph

```
```
## This breaks

for operator (Tensor 0) -> Tensor:
expected a value of type Tensor for argument '0' but found Tensor[]
@torch.jit.script_method
def forward(self, x):
    # type: (List[torch.Tensor]) -> List[torch.Tensor]

    if self.training_now is not None:
        # I expect this function to be treated as python value
        # and therefore just don't care about it
        return self.training_only_code(x)
                                       ~ <--- HERE

    return x
:
@torch.jit.script_method
def forward(self, x):
    # type: (List[torch.Tensor]) -> List[torch.Tensor]

    if self.training_now is not None:
        # I expect this function to be treated as python value
        # and therefore just don't care about it
        return self.training_only_code(x)
               ~~~~~~~~~~~~~ <--- HERE

    return x
```
## Version 3: type annotation in the python value function; List is not defined

```
class PythonValuesJIT3(torch.jit.ScriptModule):
    __constants__ = ['training_now']
    def __init__(self):
        super(PythonValuesJIT3, self).__init__()
        self.training_now = True
        self.lnorm = nn.LayerNorm([10, 10, 10])

    @torch.jit.script_method
    def forward(self, x):
        # type: (List[torch.Tensor]) -> List[torch.Tensor]

        if self.training_now is not None:
            # I expect this function to be treated as python value
            # and therefore just don't care about it
            return self.training_only_code(x)

        return x

    def training_only_code(self, x):
        # type: (List[torch.Tensor]) -> List[torch.Tensor]

        # do some torchscript incompatible logic
        arr = [1,2,3]
        for i, k in enumerate(arr):
            x[k] += x[k]

        return x
print PythonValuesJIT3().graph
```

```
Traceback (most recent call last):
  File "source/experimental/toronto/python/experiments/turn_signal_classifier/issue.py", line 129, in <module>
    print PythonValuesJIT3().graph
  File "/home/sidney/.cache/bazel/_bazel_sidney/4ac27717c7007db6c8518c407f477fee/execroot/__main__/bazel-out/release_links/lib/python/torch/jit/__init__.py", line 953, in init_then_register
    _create_methods_from_stubs(self, methods)
  File "/home/sidney/.cache/bazel/_bazel_sidney/4ac27717c7007db6c8518c407f477fee/execroot/__main__/bazel-out/release_links/lib/python/torch/jit/__init__.py", line 914, in _create_methods_from_stubs
    self._create_methods(defs, rcbs, defaults)
  File "/home/sidney/.cache/bazel/_bazel_sidney/4ac27717c7007db6c8518c407f477fee/execroot/__main__/bazel-out/release_links/lib/python/torch/jit/annotations.py", line 52, in get_signature
    return parse_type_line(type_line)
  File "/home/sidney/.cache/bazel/_bazel_sidney/4ac27717c7007db6c8518c407f477fee/execroot/__main__/bazel-out/release_links/lib/python/torch/jit/annotations.py", line 90, in parse_type_line
    arg_ann = eval(arg_ann_str, _eval_env)
  File "<string>", line 1, in <module>
NameError: name 'List' is not defined
```

PyTorch version 1.1.0

**Comment by zdevito** [comment]
It looks like something is wrong when calling Python functions with non-tensors. We will look into this further, thanks for the report!

**Comment by driazati** [comment]
Version 3 should work now that #15721 is landed. Version 2 is expected to fail for now since without any annotations all args are assumed to be `torch.Tensor`s.

**Comment by sidazhang** [comment]
@driazati Since this is a python op. Why do you care what the argument types are?
Notice that I have a None flag so that I don't even compile it for inference (`if self.training_now is not None:
`)

**Comment by driazati** [comment]
We need the argument types for marshalling to Python / maintaining a call stack for graph execution.

Since `self.training_now` is defined, you could guard the Python code with `if self.training_now is None:`, which gives you:

```
graph(%x : Tensor[]) {
  return (%x);
}
```

**Comment by sidazhang** [comment]
But if self.training_now is not None, then I need to make sure the python function is annotated?

**Comment by suo** [comment]
Closing this out as #16055 added an `@ignore` annotation  that should resolve this.
