### ISSUE TITLE
 RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by xinleipan** [pytorch/pytorch#15862]
I'm just trying to initialize a tensor using the following code:

    z = torch.zeros(100,10).cuda()

and got the following error:

     RuntimeError: CUDA error: device-side assert triggered

i'm using a pytorch version of 1.0.0, on a 1080 TI GPU

**Comment by fmassa** [comment]
I can't reproduce this on my machine.
Is that the whole script that raises the issue for you?
By that, I mean if you have only the following lines in a python script
```python
import torch
z = torch.zeros(100,10).cuda()
```
does this indeed give you the aforementioned error?


If yes, then could you please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zou3519** [comment]
Closing due to inactivity. Please feel free to reopen it later.

**Comment by mkwissam** [comment]
I am getting the same problem. 
I have a code that is working fine on windows but when I try it on linux server I got the following error 
Traceback (most recent call last):
  File "generate_paraphrases.py", line 194, in <module>
    encode_data(out_file=args.out_file)
  File "generate_paraphrases.py", line 108, in encode_data
    torch_sent_len[:], tp_len, pp_vocab['EOS'], beam_size=3, max_steps=40)
  File "/home/wmaamar/python_projects/scpn-master/train_scpn.py", line 340, in batch_beam_search
    out_trans_hids = self.encode_transformations(out_trans, out_trans_lens, return_last=False)
  File "/home/wmaamar/python_projects/scpn-master/train_scpn.py", line 143, in encode_transformations
    all_hids, (enc_last_hid, _) = self.trans_encoder(pack(in_embs[indices],  lens.tolist(), batch_first=True), (t_hid_init, t_cell_init))
RuntimeError: CUDA error: device-side assert triggered

The code is working with sentences and i get the error only with some examples but I couldn't find the category of data that generates this problem 
Could anyone help me, please?

**Comment by sachin-r** [comment]
Facing the same issue

**Comment by sachin-r** [comment]
Facing the same issue
```
th.zeros(bsz, n).type(th.cuda.FloatTensor) 
```
throws the following error
```
RuntimeError: CUDA error: device-side assert triggered 
```
I tried to run with
```
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1" 
```
but didn't get any further details in the stacktrace

Anybody, please help.

**Comment by sebasantibanez** [comment]
> I can't reproduce this on my machine.
> Is that the whole script that raises the issue for you?
> By that, I mean if you have only the following lines in a python script
> 
> ```python
> import torch
> z = torch.zeros(100,10).cuda()
> ```
> 
> does this indeed give you the aforementioned error?
> 
> If yes, then could you please copy and paste the output from our
> [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
> (or fill out the checklist below manually).
> 
> You can get the script and run it with:
> 
> ```
> wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
> # For security purposes, please check the contents of collect_env.py before running it.
> python collect_env.py
> ```
> 
>     * PyTorch Version (e.g., 1.0):
> 
>     * OS (e.g., Linux):
> 
>     * How you installed PyTorch (`conda`, `pip`, source):
> 
>     * Build command you used (if compiling from source):
> 
>     * Python version:
> 
>     * CUDA/cuDNN version:
> 
>     * GPU models and configuration:
> 
>     * Any other relevant information:

I am facing the same issue. Running pytorch in AWS SageMaker. Please see environment below

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Amazon Linux AMI 2018.03
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.13.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch
```
