### ISSUE TITLE
CUDA out of memory on AWS p3.2xlarge GPU instance

### ISSUE THREAD

**Issue by AlessandroRiet** [pytorch/pytorch#16036]
## 🐛 Bug

RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 15.75 GiB total capacity; 14.26 GiB already allocated; 362.94 MiB free; 14.24 MiB cached)

## To Reproduce

1. Create AWS p3.2xlarge instance with Deep Learning AMI (Ubuntu) Version 20.0
1. git clone https://github.com/NVIDIA/pix2pixHD.git
1. sh scripts/train_1024p_24G.sh

---------- Networks initialized -------------
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /home/ubuntu/.torch/models/vgg19-dcbb9e9d.pth
100.0%
------------- Only training the local enhancer network (for 10 epochs) ------------
model [Pix2PixHDModel] was created
create web directory ./checkpoints/sketch2poster/web...
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pix2pixHD-train/models/pix2pixHD_model.py", line 172, in forward
    loss_G_VGG = self.criterionVGG(fake_image, real_image) * self.opt.lambda_feat
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pix2pixHD-train/models/networks.py", line 122, in forward
    x_vgg, y_vgg = self.vgg(x), self.vgg(y)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pix2pixHD-train/models/networks.py", line 412, in forward
    h_relu2 = self.slice2(h_relu1)        
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 15.75 GiB total capacity; 14.26 GiB already allocated; 362.94 MiB free; 14.24 MiB cached)

## Expected behavior

Training should start!

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 410.79
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0)
[pip] torchvision (0.2.1)
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by colesbury** [comment]
You're using a script with the comment "[Using GPUs with 24G memory](https://github.com/NVIDIA/pix2pixHD/blob/master/scripts/train_1024p_feat_24G.sh#L2)", but your GPU has ~16 GB of memory.

**Comment by colesbury** [comment]
(Try the `train_1024p_feat_12G.sh` script)
