### ISSUE TITLE
test_dag_net_forking is flaky on ROCm

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16229]
This was first surfaced in #15817 but I am filing a new bug for clarity.

Error looks like:

```
01:46:35 ../.local/lib/python2.7/site-packages/caffe2/python/hypothesis_test.py::TestOperators::test_constant_fill PASSED [  7%]
01:46:35 ../.local/lib/python2.7/site-packages/caffe2/python/hypothesis_test.py::TestOperators::test_cos PASSED [  8%]
01:46:36 ../.local/lib/python2.7/site-packages/caffe2/python/hypothesis_test.py::TestOperators::test_dag_net_forking ./.jenkins/caffe2/test.sh: line 120:  5452 Segmentation fault      (core dumped) "$PYTHON" -m pytest -x -v --disable-warnings --junit-xml="$pytest_reports_dir/result.xml" --ignore "$caffe2_pypath/python/test/executor_test.py" --ignore "$caffe2_pypath/python/operator_test/matmul_op_test.py" --ignore "$caffe2_pypath/python/operator_test/pack_ops_test.py" --ignore "$caffe2_pypath/python/mkl/mkl_sbn_speed_test.py" ${rocm_ignore_test[@]} "$caffe2_pypath/python" "${EXTRA_TESTS[@]}"
01:46:36 + echo 'Stopping container...'
```

https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-test/5483/console

This seems to be specifically a ROCm failure. CC @bddppq @iotamudelta

**Comment by ezyang** [comment]
CC @mrshenli

**Comment by ezyang** [comment]
Hello, any update on this? Otherwise I will disable this test. @bddppq @iotamudelta @mrshenli

**Comment by mrshenli** [comment]
no update from me

**Comment by petrex** [comment]
Is this a CPU test? cross-compilation maybe?

**Comment by bddppq** [comment]
Taken a closer look, this indeed looks related to rocm:

```

Thread 95 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffef7977700 (LWP 89694)]
0x00007ffff6d9f914 in _int_malloc () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6d9f914 in _int_malloc () from /lib64/libc.so.6
#1  0x00007ffff6da21ac in malloc () from /lib64/libc.so.6
#2  0x00007fffed98decd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#3  0x00007fffd73e7831 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#4  0x00007fffd73e80b6 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#5  0x00007fffd73deead in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#6  0x00007fffdbfe4798 in am_aligned_alloc () at /data/hcc_hip_antistatic/hcc/lib/hsa/hc_am.cpp:266
#7  0x00007fffe129b5ea in hip_internal::allocAndSharePtr(char const*, unsigned long, ihipCtx_t*, bool, unsigned int, unsigned int, unsigned long) () from /opt/rocm/hip/lib/libhip_hcc.so
#8  0x00007fffe129d75b in hipMalloc () from /opt/rocm/hip/lib/libhip_hcc.so
#9  0x00007fff37a2c9ff in caffe2::DefaultHIPAllocator::allocate(unsigned long) const () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#10 0x00007fff4e6217d6 in c10::TensorImpl::raw_mutable_data(caffe2::TypeMeta const&) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#11 0x00007fff4e7d9230 in caffe2::empty(c10::ArrayRef<long>, c10::TensorOptions) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#12 0x00007fff2bb8c8a7 in bool caffe2::FullyConnectedGradientOp<caffe2::HIPContext, caffe2::DefaultEngine, true>::DoRunWithType<float, float, float, float, float, float, float, float>() ()
   from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#13 0x00007fff2bb88988 in caffe2::FullyConnectedGradientOp<caffe2::HIPContext, caffe2::DefaultEngine, true>::RunOnDevice() () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#14 0x00007fff2bb47b0d in caffe2::Operator<caffe2::HIPContext>::RunAsync(int) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#15 0x00007fff4e786f20 in caffe2::AsyncNetBase::run(int, int) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#16 0x00007fff4e78d3a9 in caffe2::AsyncSchedulingNet::schedule(int, bool)::{lambda()#1}::operator()() const () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#17 0x00007fff4d86be33 in c10::ThreadPool::main_loop(unsigned long) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#18 0x00007fff4f99e5cf in execute_native_thread_routine () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#19 0x00007ffff77fadd5 in start_thread () from /lib64/libpthread.so.0
#20 0x00007ffff6e1aead in clone () from /lib64/libc.so.6
```

**Comment by petrex** [comment]
@ezyang Quick question, is it on centos only?

**Comment by bddppq** [comment]
@petrex it happens on ubuntu as well https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/8757/console

**Comment by bddppq** [comment]
The corruption should be caused by the gemm call before the memory allocation:
```
Thread 104 "python" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff5f63d700 (LWP 90896)]
0x00007ffff6d53207 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6d53207 in raise () from /lib64/libc.so.6
#1  0x00007ffff6d548f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff6d95d27 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff6d9e489 in _int_free () from /lib64/libc.so.6
#4  0x00007fffbe8534d2 in deallocate () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/ext/new_allocator.h:125
#5  deallocate () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/alloc_traits.h:462
#6  _M_deallocate () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/stl_vector.h:180
#7  _M_realloc_insert<std::shared_ptr<HSAOp> > () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/vector.tcc:448
#8  0x00007fffbe8367cc in emplace_back<std::shared_ptr<HSAOp> > () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/vector.tcc:105
#9  push_back () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/stl_vector.h:954
#10 pushAsyncOp () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:1405
#11 0x00007fffbe842c16 in EnqueueMarker () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:1990
#12 0x00007fffbe842539 in isEmpty () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:1528
#13 0x00007fffbe82ecfe in createOrstealRocrQueue () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:2293
#14 0x00007fffbe83191d in acquireLockedRocrQueue () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:4012
#15 0x00007fffbe839157 in dispatchKernelAsync () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:4572
#16 0x00007fffbe8388a7 in dispatch_hsa_kernel () at /data/hcc_hip_antistatic/hcc/lib/hsa/mcwamp_hsa.cpp:4242
#17 0x00007fffe1322571 in ihipModuleLaunchKernel(ihipModuleSymbol_t*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned long, ihipStream_t*, void**, void**, ihipEvent_t*, ihipEvent_t*) () from /opt/rocm/hip/lib/libhip_hcc.so
#18 0x00007fffe1323167 in hipModuleLaunchKernel () from /opt/rocm/hip/lib/libhip_hcc.so
#19 0x00007fffe134948f in hip_impl::hipLaunchKernelGGLImpl(unsigned long, dim3 const&, dim3 const&, unsigned int, ihipStream_t*, void**) () from /opt/rocm/hip/lib/libhip_hcc.so
#20 0x00007fff1a3d0fab in void hipLaunchKernelGGL<float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, void (*)(float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)>(void (*)(float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int), dim3 const&, dim3 const&, unsigned int, ihipStream_t*, float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) () from /opt/rocm/rocblas/lib/librocblas.so.0
#21 0x00007fff1a3e8d57 in Cijk_Ailk_Bjlk_SB_MT128x064x08_AF0EM01_ASEM01_BL0_DTL0_FL0_GRVW01_GSU01_ISA000_KLS_LPA00_LPB00_MGWVW01_NLCA01_NLCB01_PBC0_PGR0_PLR1_TT08_04_USFGRO00_VAW01_VW01_WG16_16_01_WGM08(float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, ihipStream_t*, unsigned int, ihipEvent_t**, ihipEvent_t**) () from /opt/rocm/rocblas/lib/librocblas.so.0
#22 0x00007fff1a1f9ff1 in rocblas_sgemm () from /opt/rocm/rocblas/lib/librocblas.so.0
#23 0x00007fff3aa4c07d in void caffe2::math::Gemm<float, caffe2::HIPContext, caffe2::DefaultEngine>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*, caffe2::HIPContext*, caffe2::TensorProto_DataType) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#24 0x00007fff2eab66fd in bool caffe2::FullyConnectedGradientOp<caffe2::HIPContext, caffe2::DefaultEngine, true>::DoRunWithType<float, float, float, float, float, float, float, float>() ()
   from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#25 0x00007fff2eab2988 in caffe2::FullyConnectedGradientOp<caffe2::HIPContext, caffe2::DefaultEngine, true>::RunOnDevice() () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#26 0x00007fff2ea71b0d in caffe2::Operator<caffe2::HIPContext>::RunAsync(int) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2_hip.so
#27 0x00007fff792d5f20 in caffe2::AsyncNetBase::run(int, int) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#28 0x00007fff792dc3a9 in caffe2::AsyncSchedulingNet::schedule(int, bool)::{lambda()#1}::operator()() const () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#29 0x00007fff783bae33 in c10::ThreadPool::main_loop(unsigned long) () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#30 0x00007fff7a4ed5cf in execute_native_thread_routine () from /root/pytorch/caffe2/python/../../torch/lib/libcaffe2.so
#31 0x00007ffff77fadd5 in start_thread () from /lib64/libpthread.so.0
#32 0x00007ffff6e1aead in clone () from /lib64/libc.so.6
```
From the stack trace looks like it's related to one of our recent bug report about HSAQueue issue. @scchan Could you help investigate whether it's related?

**Comment by scchan** [comment]
@bddppq yes, this is the same as the one in your recent bug report.

**Comment by bddppq** [comment]
https://github.com/pytorch/pytorch/pull/16639

**Comment by bddppq** [comment]
@scchan Is this the related fix? https://github.com/RadeonOpenCompute/hcc/commit/41f23b7a13a415453f7c8f54d6cc031fbec4ab74

**Comment by scchan** [comment]
@bddppq that one helps but also this fix here  https://github.com/RadeonOpenCompute/hcc/pull/1013

**Comment by bddppq** [comment]
Thanks @scchan @petrex for quick fix. For now we have temporarily skipped the test in our rocm CI, will re-enable it once the fix has come into the release (and our docker image).
