### ISSUE TITLE
Error message when trying to load a non-existent torch.jit.trace is quite bad

### ISSUE THREAD

**Issue by nlml** [pytorch/pytorch#16267]
## 🐛 Bug

When trying to load a file using `torch.jit.load(filename)`, if `filename` does not exist, the error message is very complex and misleading.

## To Reproduce

1. `import torch`
2. `torch.jit.load('NOT_A_REAL_FILE')`

```
>>> import torch
>>> torch.jit.load('NOT_A_REAL_FILE')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/jit/__init__.py", line 131, in load
    torch._C.import_ir_module(module_lookup, f, map_location)
RuntimeError: [enforce fail at inline_container.cc:130] . PytorchStreamReader failed opening archive.
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f1edc5befe1 in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x7f1edc5bec29 in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #2: torch::jit::PyTorchStreamReader::valid(char const*) + 0xe5 (0x7f1eddc976b5 in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libcaffe2.so)
frame #3: torch::jit::PyTorchStreamReader::PyTorchStreamReader(std::string, std::istream*) + 0x459 (0x7f1eddc99c79 in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libcaffe2.so)
frame #4: torch::jit::import_ir_module(std::function<std::shared_ptr<torch::jit::script::Module> (std::vector<std::string, std::allocator<std::string> > const&)>, std::string const&, c10::optional<c10::Device>) + 0x50 (0x7f1edb3251c0 in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x3a56c1 (0x7f1f169816c1 in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x116fac (0x7f1f166f2fac in /home/liam/.virtualenvs/py35/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #9: python() [0x5406df]
frame #11: python() [0x540199]
frame #13: python() [0x60c272]
frame #16: python() [0x46cfa0]
frame #17: python() [0x4cf2bd]
frame #19: __libc_start_main + 0xf0 (0x7f1f31e8f830 in /lib/x86_64-linux-gnu/libc.so.6)
```

## Expected behavior

Should provide a simple error message like "the file FILENAME does not exist"

## Environment

Reproduced in Python 3.5 and 3.6, with pytorch==1.0

**Comment by nlml** [comment]
I made a pull request to fix this here https://github.com/pytorch/pytorch/pull/16270

**Comment by suo** [comment]
Closing as the relevant PR has landed. Feel free to re-open if there's something left to address.
