### ISSUE TITLE
#16182 new test_stream_event_nogil test fails on ppc64le

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#16271]
## 🐛 Bug

FAIL: test_stream_event_nogil (__main__.TestCuda)

Traceback (most recent call last):
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/common_utils.py", line 296, in wrapper
    method(*args, **kwargs)
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/common_utils.py", line 120, in wrapper
    fn(*args, **kwargs)
  File "test_cuda.py", line 1736, in test_stream_event_nogil
    self.assertGreater(tok - tik, 0.05)
AssertionError: 0.037542104721069336 not greater than 0.05

----------------------------------------------------------------------

## To Reproduce

python -m unittest test_cuda.TestCuda.test_stream_event_nogil -v

## Environment

 - PyTorch Version (e.g., 1.0):   latest pull from master :  torch (1.1.0a0+e669f72)
 - OS (e.g., Linux):   RH 7.5
 - How you installed PyTorch (`conda`, `pip`, source):  source
 - Build command you used (if compiling from source):   python setup.py install
 - Python version:    3.7
 - CUDA/cuDNN version:     Cuda 10  cudnn 7.4.2
 - GPU models and configuration:    P100  x 2 
 - Any other relevant information:

**Comment by ezyang** [comment]
Likely same root cause as #16250
