### ISSUE TITLE
Couldn't export operator aten::max_pool2d_with_indices

### ISSUE THREAD

**Issue by drnikolaev** [pytorch/pytorch#16336]
## 🐛 Bug

Couldn't export operator `aten::max_pool2d_with_indices` while exporting TorchVision's squeezenet to ONNX.

## To Reproduce

1. Unzip and run attached [torch_exporter.zip](https://github.com/pytorch/pytorch/files/2793752/torch_exporter.zip) script like this:
```
python torch_exporter.py --arch squeezenet1_0 -e --epochs 1 --pretrained -b 32 models
```

2. Result:

```
=> using pre-trained model 'squeezenet1_0'
/home/snikolaev/anaconda3/lib/python3.6/site-packages/torchvision/models/squeezenet.py:94: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  init.kaiming_uniform(m.weight.data)
/home/snikolaev/anaconda3/lib/python3.6/site-packages/torchvision/models/squeezenet.py:92: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, mean=0.0, std=0.01)
SqueezeNet(
  (features): Sequential(
    (0): Conv2d(3, 96, kernel_size=(7, 7), stride=(2, 2))
    (1): ReLU(inplace)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (3): Fire(
      (squeeze): Conv2d(96, 16, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (4): Fire(
      (squeeze): Conv2d(128, 16, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (5): Fire(
      (squeeze): Conv2d(128, 32, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(32, 128, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(32, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (6): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (7): Fire(
      (squeeze): Conv2d(256, 32, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(32, 128, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(32, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (8): Fire(
      (squeeze): Conv2d(256, 48, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(48, 192, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(48, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (9): Fire(
      (squeeze): Conv2d(384, 48, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(48, 192, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(48, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (10): Fire(
      (squeeze): Conv2d(384, 64, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
    (11): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (12): Fire(
      (squeeze): Conv2d(512, 64, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace)
      (expand1x1): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace)
      (expand3x3): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace)
    )
  )
  (classifier): Sequential(
    (0): Dropout(p=0.5)
    (1): Conv2d(512, 1000, kernel_size=(1, 1), stride=(1, 1))
    (2): ReLU(inplace)
    (3): AvgPool2d(kernel_size=13, stride=1, padding=0)
  )
)
/home/snikolaev/pytorch2/torch/onnx/symbolic.py:162: UserWarning: ONNX export failed on max_pool2d_with_indices because ceil_mode not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
graph(%actual_input_1 : Float(10, 3, 224, 224)
      %learned_0 : Float(96, 3, 7, 7)
      %learned_1 : Float(96)
      %learned_2 : Float(16, 96, 1, 1)
.......
  %132 : Float(10, 512, 13, 13), %133 : Tensor = onnx::Dropout[ratio=0.5](%131), scope: SqueezeNet/Sequential[classifier]/Dropout[0]
  %134 : Float(10, 1000, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%132, %learned_50, %learned_51), scope: SqueezeNet/Sequential[classifier]/Conv2d[1]
  %135 : Float(10, 1000, 13, 13) = onnx::Relu(%134), scope: SqueezeNet/Sequential[classifier]/ReLU[2]
  %136 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0](%135), scope: SqueezeNet/Sequential[classifier]/AvgPool2d[3]
  %137 : Float(10, 1000, 1, 1) = onnx::AveragePool[kernel_shape=[13, 13], pads=[0, 0, 0, 0], strides=[1, 1]](%136), scope: SqueezeNet/Sequential[classifier]/AvgPool2d[3]
  %138 : Long() = onnx::Constant[value={0}](), scope: SqueezeNet
  %139 : Tensor = onnx::Shape(%137), scope: SqueezeNet
  %140 : Long() = onnx::Gather[axis=0](%139, %138), scope: SqueezeNet
  %141 : Long() = onnx::Constant[value={1000}](), scope: SqueezeNet
  %142 : Tensor = onnx::Unsqueeze[axes=[0]](%140)
  %143 : Tensor = onnx::Unsqueeze[axes=[0]](%141)
  %144 : Tensor = onnx::Concat[axis=0](%142, %143)
  %output1 : Float(10, 1000) = onnx::Reshape(%137, %144), scope: SqueezeNet
  return (%output1);
}

Traceback (most recent call last):
  File "/home/snikolaev/pytorch2/tv_rn50/torch_exporter.py", line 353, in <module>
    main()
  File "/home/snikolaev/pytorch2/tv_rn50/torch_exporter.py", line 134, in main
    export_params=True) # store the trained parameter weights inside the model file
  File "/home/snikolaev/pytorch2/torch/onnx/__init__.py", line 22, in _export
    return utils._export(*args, **kwargs)
  File "/home/snikolaev/pytorch2/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d_with_indices

Defined at:
/home/snikolaev/pytorch2/torch/nn/functional.py(486): max_pool2d_with_indices
/home/snikolaev/pytorch2/torch/nn/functional.py(494): _max_pool2d
/home/snikolaev/pytorch2/torch/_jit_internal.py(129): fn
/home/snikolaev/pytorch2/torch/nn/modules/pooling.py(148): forward
......
```

**Comment by vishwakftw** [comment]
Related to https://github.com/pytorch/pytorch/issues/2898.

**Comment by houseroad** [comment]
https://github.com/pytorch/pytorch/pull/16455 should solve the proble.

**Comment by gottbrath** [comment]
@drnikolaev  -- can you confirm that this is resolved?

**Comment by drnikolaev** [comment]
Thanks guys, will check tomorrow morning..

**Comment by spandantiwari** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/16455.

**Comment by drnikolaev** [comment]
Confirmed! Thank you folks!
