### ISSUE TITLE
MSELoss behaves strangely when shapes don't match

### ISSUE THREAD

**Issue by RyanMarcus** [pytorch/pytorch#16413]
## 🐛 Bug
The MSELoss criteria has a strange behavior when used with two tensors of different sizes -- I would expect this to throw an error. Instead it does... something else.

## To Reproduce

Install stable, non-CUDA torch, i.e.: https://download.pytorch.org/whl/cpu/torch-1.0.0-cp37-cp37m-linux_x86_64.whl

```python
>>> import torch
>>> import torch.nn as nn
>>> a = torch.Tensor([1, 2, 3])
>>> b = torch.Tensor([[1],[2],[3]])
>>> nn.MSELoss()(a, b)
tensor(1.3333)
```
## Expected behavior

I would've appreciated an error in this case. Perhaps there is some reason why someone might wish to call MSELoss with different sized arrays... but I think if the *number of dimensions* between the two vectors differs, it's likely the user's mistake.

I realize this is a "rookie mistake," but I promise it was *not* a fun way to spend 2 hours. Perhaps a friendly warning message could save someone the headache in the future?

## Environment
```
$ python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Arch Linux
GCC version: (GCC) 8.2.1 20181127
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro M1000M
Nvidia driver version: 415.27
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

## Additional context

It looks like this may have been looked at previously in issue #12129 or PR #5085 ?

**Comment by RyanMarcus** [comment]
This "bug" was not present in `0.4.1.post2`. That version throws this error, which seems reasonable:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmarcus/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rmarcus/local/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 421, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/rmarcus/local/lib/python3.7/site-packages/torch/nn/functional.py", line 1716, in mse_loss
    return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
  File "/home/rmarcus/local/lib/python3.7/site-packages/torch/nn/functional.py", line 1674, in _pointwise_loss
    return lambd_optimized(input, target, reduction)
RuntimeError: input and target shapes do not match: input [3], target [3 x 1] at /pytorch/aten/src/THNN/generic/MSECriterion.c:12
```

**Comment by RyanMarcus** [comment]
Confirmed. Sorry for the dup. :)
