### ISSUE TITLE
A bug in parallel.data_parallel when module_kwargs is not None

### ISSUE THREAD

**Issue by thstkdgus35** [pytorch/pytorch#16432]
## 🐛 Bug

A bug in [parallel.data_parallel](https://github.com/pytorch/pytorch/blob/fdaa77ae8b084eaa7535075538e9d80f4c4a8d1a/torch/nn/parallel/data_parallel.py#L159-L189) when
- The batch size is smaller than the number of GPUs
- With some keyword arguments (module_kwargs) in the custom forward function.

## To Reproduce

1. Please execute the test script below (with more than 4 GPUs available).

```python
import torch
from torch import nn
from torch.nn import parallel

def check(module, inputs, device_ids=None, output_device=None, dim=0, module_kwargs=None):
    '''
    This function is a just simple copy of nn.parallel.data_parallel:
    https://github.com/pytorch/pytorch/blob/fdaa77ae8b084eaa7535075538e9d80f4c4a8d1a/torch/nn/parallel/data_parallel.py#L159-L189
    '''
    if not isinstance(inputs, tuple):
        inputs = (inputs,)

    if device_ids is None:
        device_ids = list(range(torch.cuda.device_count()))

    if output_device is None:
        output_device = device_ids[0]

    inputs, module_kwargs = parallel.scatter_gather.scatter_kwargs(
        inputs, module_kwargs, device_ids, dim
    )
    print(module_kwargs)
    if len(device_ids) == 1:
        return module(*inputs[0], **module_kwargs[0])

    used_device_ids = device_ids[:len(inputs)]
    replicas = parallel.replicate(module, used_device_ids)
    outputs = parallel.parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
    return parallel.gather(outputs, output_device, dim)

class Test(nn.Conv2d):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def forward(self, x, msg='default'):
        print(msg)
        return super().forward(x)

if __name__ == '__main__':
    conv = Test(1, 1, 3, padding=1).cuda()
    x = torch.randn(4, 1, 4, 4).cuda()
    y = torch.randn(1, 1, 4, 4).cuda()

    print('x on 1 GPU with kwargs')
    check(conv, x, device_ids=range(1), module_kwargs={'msg': 'Hello'})
    print('x on 4 GPUs with kwargs')
    check(conv, x, device_ids=range(4), module_kwargs={'msg': 'Hello'})

    print('y on 1 GPU')
    check(conv, y, device_ids=range(1))
    print('y on 1 GPU with kwargs')
    check(conv, y, device_ids=range(1), module_kwargs={'msg': 'Hello'})
    print('y on 4 GPUs')
    check(conv, y, device_ids=range(4))
    print('y on 4 GPUs with kwargs')
    check(conv, y, device_ids=range(4), module_kwargs={'msg': 'Hello'}) # Error!
```

```bash
>>> python test.py
x on 1 GPU with kwargs
({'msg': 'Hello'},)
Hello
x on 4 GPUs with kwargs
({'msg': 'Hello'}, {'msg': 'Hello'}, {'msg': 'Hello'}, {'msg': 'Hello'})
Hello
Hello
Hello
Hello
y on 1 GPU
({},)
default
y on 1 GPU with kwargs
({'msg': 'Hello'},)
Hello
y on 4 GPUs
({},)
default
y on 4 GPUs with kwargs
({'msg': 'Hello'}, {'msg': 'Hello'}, {'msg': 'Hello'}, {'msg': 'Hello'})
Hello
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    check(conv, y, device_ids=range(4), module_kwargs={'msg': 'Hello'})
  File "test.py", line 24, in check
    outputs = parallel.parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/home/sanghyun/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/sanghyun/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/sanghyun/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```
## Expected behavior

``Test.forward()`` should be executed **only once** with the ``y on 4 GPUs with kwargs`` configuration (like ``y on 4 GPUs``). However, it seems that ``Test.forward()`` is called more than once, with an empty ``inputs``. We can see one ``Hello`` message below ``y on 4 GPUs with kwargs``, and I think ``parallel.parallel_apply`` should be terminated right after then.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): ``conda install pytorch torchvision -c pytorch``
 - Python version: Anaconda 3.7 (https://repo.continuum.io/archive/Anaconda3-2018.12-Linux-x86_64.sh)
 - CUDA/cuDNN version:
```bash
>>> nvcc --version
NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
```python
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.backends.cudnn.version()
7401
```
 - GPU models and configuration:
```bash
>>> nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:04:00.0 Off |                  N/A |
| 33%   57C    P2   106W / 250W |   5691MiB / 11172MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:05:00.0 Off |                  N/A |
| 41%   69C    P2   163W / 250W |   9115MiB / 11172MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:08:00.0 Off |                  N/A |
|  0%   26C    P8    18W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:09:00.0 Off |                  N/A |
| 23%   28C    P8    16W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 00000000:83:00.0 Off |                  N/A |
| 23%   20C    P8     7W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 00000000:84:00.0 Off |                  N/A |
|  0%   24C    P8     8W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 00000000:87:00.0 Off |                  N/A |
| 23%   27C    P8     8W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  On   | 00000000:88:00.0 Off |                  N/A |
| 23%   21C    P8     8W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      5671      C   python                                      5681MiB |
|    1      6349      C   python                                      9105MiB |
+-----------------------------------------------------------------------------+
```
(Used 4, 5, 6, 7 for the test script.)

**Comment by yf225** [comment]
In the documentation of `torch.nn.DataParallel` (https://pytorch.org/docs/stable/nn.html#torch.nn.DataParallel) it's mentioned that `The batch size should be larger than the number of GPUs used`, so I don't think we support batch size smaller than the number of GPUs at the moment.

**Comment by thstkdgus35** [comment]
@yf225, Thank you for your response.

I know that there is a documentation about ``batch_size`` and the number of GPUs, but I still think this is an unexpected error that should be prevented.

Here are some reasons:

1. Sometimes, we cannot make a full batch because of the number of training/test samples. For example, assume that we have 20 samples for training and there are 4 GPUs available. It will work. But when we train our model on 8-GPU machine, it will make an error. I know that a ``drop_last`` argument in ``dataloader`` can solve this problem. However, I think this is not the smartest solution we can have. Also, some people may want to use their full dataset without any drop (and of course, we should not drop any samples during evaluation).

2. The weird thing is: **``data_parallel`` works very well when there is no ``module_kwargs``**, even if a ``batch_size`` is smaller than the number of GPUs. That is because there is some implicit exception handler. If you see [this line](https://github.com/pytorch/pytorch/blob/fdaa77ae8b084eaa7535075538e9d80f4c4a8d1a/torch/nn/parallel/data_parallel.py#L142), or [this line](https://github.com/pytorch/pytorch/blob/fdaa77ae8b084eaa7535075538e9d80f4c4a8d1a/torch/nn/parallel/data_parallel.py#L186), the code prevents ``parallel_apply`` from assigning more devices than the ``batch_size``. That is why ``y on 4 GPUs`` makes no trouble in my sample code and people did not report about this issue.

3. Finally, I would like to point out that there is a straightforward and nice solution to this problem. What we should do is to move the below line
```python
used_device_ids = device_ids[:len(inputs)]
```
to upside. Like,
```python
    used_device_ids = device_ids[:inputs[0].size(dim)]
    inputs, module_kwargs = parallel.scatter_gather.scatter_kwargs(
        inputs, module_kwargs, used_device_ids, dim
    )
    if len(used_device_ids) == 1:
        return module(*inputs[0], **module_kwargs[0])
    #used_device_ids = device_ids[:len(inputs)]
```

I think there is no reason to keep current codes, in terms of consistency, clarity, generality, and even performance. At least, I believe PyTorch should raise an appropriate error message if someones try ``batch_size`` < n_GPUs with ``module_kwargs``.

Any discussions are welcomed and thank you for reading my report.

**Comment by zou3519** [comment]
At the very least we should raise an error message if batch_sizes < nGPUs

**Comment by ezyang** [comment]
This still doesn't raise an error:

```
(base) ezyang@devfair040:~/Dev$ python foo.py                                                               
x on 1 GPU with kwargs
Hello
x on 4 GPUs with kwargs
Hello
Hello
y on 1 GPU
default
y on 1 GPU with kwargs
Hello
y on 4 GPUs
default
y on 4 GPUs with kwargs
Hello
Traceback (most recent call last):
  File "foo.py", line 59, in <module>
    check(conv, y, device_ids=range(2), module_kwargs={'msg': 'Hello'}) # Error!
  File "/scratch/ezyang/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 230, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/scratch/ezyang/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/scratch/ezyang/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/scratch/ezyang/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/scratch/ezyang/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```
