### ISSUE TITLE
nn.CrossEntropyLoss cannot work in distributed mode

### ISSUE THREAD

**Issue by CoinCheung** [pytorch/pytorch#16546]
## 🐛 Bug

using nn.DistributedDataParallel instead of nn.DataParallel, the nn.CrossEntropyLoss report errors

## To Reproduce

My code is like this: 
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import time

import argparse


def parse_args():
    parse = argparse.ArgumentParser()
    parse.add_argument(
            '--local_rank',
            dest = 'local_rank',
            type = int,
            default = -1,
            )
    return parse.parse_args()


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3,
            64,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.conv2 = nn.Conv2d(64,
            256,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.conv3 = nn.Conv2d(256,
            19,
            kernel_size = 3,
            stride = 2,
            padding = 1,)

    def forward(self, x):
        H, W = x.size()[2:]
        x = self.conv1(x)
        x = self.conv2(x)
        logits = self.conv3(x)
        logits = F.interpolate(logits, (H, W), mode='bilinear')
        return logits


def train():
    args = parse_args()

    torch.cuda.set_device(args.local_rank)
    torch.distributed.init_process_group(
                backend='nccl',
                init_method='env://',
                )
    net = Net()
    net.train()
    net.cuda()
    net = nn.parallel.DistributedDataParallel(net,
            device_ids = [args.local_rank, ],
            output_device = args.local_rank
            )

    optim = torch.optim.SGD(
            net.parameters(),
            lr = 1e-3,
            momentum = 0.9,
            weight_decay = 5e-4)
    criteria = nn.CrossEntropyLoss()

    for i in range(10000):
        img = torch.randn(2, 3, 768, 768).cuda()
        lb = torch.randint(0, 19, [2,768,768]).cuda()
        optim.zero_grad()
        out = net(img)
        loss = criteria(out, lb)
        loss.backward()
        optim.step()


if __name__ == "__main__":
    train()
```
The error message is: 
```
/home/zhangzy/.local/lib/python3.5/site-packages/torch/nn/functional.py:2375: UserWarning: Def
ault upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Ple
ase specify align_corners=True if the old behavior is desired. See the documentation of nn.Ups
ample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

Traceback (most recent call last):
  File "playdist.py", line 87, in <module>
    train()
  File "playdist.py", line 81, in train
    loss.backward()
  File "/home/zhangzy/.local/lib/python3.5/site-packages/torch/tensor.py", line 102, in backwa
rd
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhangzy/.local/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90,
 in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/zhangzy/.local/lib/python3.5/site-packages/torch/nn/parallel/distributed.py", li
ne 384, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/home/zhangzy/.local/lib/python3.5/site-packages/torch/nn/parallel/distributed.py", li
ne 413, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types a
re supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], de
vices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupNCCL object at 0x7fd5d99356f8>, [[tensor([[[[0., 
0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
    ......
```
This is followed by many tensor values.

## Expected behavior

I am trying to compute pixel wised cross entropy loss, this works with dataParallel, but does not work with nn.distributed.DaraParallel

## Environment

Collecting environment information...
PyTorch version: 1.0.0a0+37627a1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.12.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 384.69
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.5)
[pip3] torch (1.0.0a0+37627a1)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by ezyang** [comment]
cc @mrshenli @pietern

**Comment by CoinCheung** [comment]
Sorry, the problem is that I have some useless layer defined in the model.  The code I above is a neat version. My local version is like this: 
```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3,
            64,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.conv2 = nn.Conv2d(64,
            256,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.conv3 = nn.Conv2d(256,
            19,
            kernel_size = 3,
            stride = 2,
            padding = 1,)class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3,
            64,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.conv2 = nn.Conv2d(64,
            256,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.conv3 = nn.Conv2d(256,
            19,
            kernel_size = 3,
            stride = 2,
            padding = 1,)
        self.linear = nn.Linear(10) # this is not used in the forward(), remove this the problem is solved
```
Here the `self.linear` is not used in the `forward()`, which brings the problem. After removing it, I have my problem solved. 

It is my bad coding style that causes this problem. I am closing this issue. Thanks for support!!
