### ISSUE TITLE
Pytorch Import:  failed to map segment Error 

### ISSUE THREAD

**Issue by Jamesswiz** [pytorch/pytorch#16558]
I installed Pytorch .3.1 using pip3 for python3.5, and the installation was successful.
However, I am unable to load the package in python

import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "user/.local/lib/python3.5/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libgcc_s.so.1: failed to map segment from shared object

Can anybody help, how to resolve this?

Best

**Comment by vladserkoff** [comment]
It seems you don't have gcc installed, either try to install pytorch from conda and it will install gcc for you, or get it from your package manager (apt, if it's ubuntu)

**Comment by albanD** [comment]
Closing due to lack of activity. Please reopen if you see this error again.

**Comment by xuzijian629** [comment]
I accidentally reproduced this error by

```python
>>> import resource
>>> resource.setrlimit(resource.RLIMIT_AS, (1000 * 1024 ** 2, -1))
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
ImportError: libtorch_cuda.so: failed to map segment from shared object
```

with ubuntu:18.04.

Since I can successfully import torch if I removed the resource limit, your problem might be simply memory shortage.
