### ISSUE TITLE
[JIT] NVRTC unknown error

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#16592]
## 🐛 Bug

I have consistently run into NVRTC unknown error. 

```RuntimeError: /pytorch-atg/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:138: NVRTC_ERROR unknown```

I ran with `export PYTORCH_FUSION_DEBUG=1`

and I got this:
```
fusion code:

typedef unsigned char uint8_t;
typedef signed char int8_t;
typedef short int  int16_t;
typedef long long int int64_t;



#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

typedef unsigned int IndexType;
template<typename T, size_t N>
struct TensorInfo {
  T* data;
  IndexType sizes[N];
  IndexType strides[N];
};
template<typename T>
struct TensorInfo<T, 0> {
  T * data;
};


extern "C" __global__
void kernel_0(IndexType totalElements, TensorInfo<float,1> t0, TensorInfo<float,1> t1, TensorInfo<float,1> t2 ) {
  
  for (IndexType linearIndex = blockIdx.x * blockDim.x + threadIdx.x;
        linearIndex < totalElements;
        linearIndex += gridDim.x * blockDim.x) {
      // Convert `linearIndex` into an offset of tensor:
      IndexType t0_offset = 0;
      IndexType t0_linearIndex = linearIndex;
      
      //printf("tensor t0 sizes[0] = %d, strides[0] = %d\n", t0.sizes[0],t0.strides[0]);
      size_t t0_dimIndex0 = t0_linearIndex ;
      t0_offset += t0_dimIndex0 * t0.strides[0];
      IndexType t1_offset = 0;
      IndexType t1_linearIndex = linearIndex;
      
      //printf("tensor t1 sizes[0] = %d, strides[0] = %d\n", t1.sizes[0],t1.strides[0]);
      size_t t1_dimIndex0 = t1_linearIndex ;
      t1_offset += t1_dimIndex0 ;
      IndexType t2_offset = 0;
      IndexType t2_linearIndex = linearIndex;
      
      //printf("tensor t2 sizes[0] = %d, strides[0] = %d\n", t2.sizes[0],t2.strides[0]);
      size_t t2_dimIndex0 = t2_linearIndex ;
      t2_offset += t2_dimIndex0 ;
      
      // calculate the results
      float n0 = t0.data[t0_offset];
      int n1 = -72;
      int n2 = 1;
      float n3 = (n0 - ((float) n2)*((float) n1));
      float n4 = 5.000000e+00f;
      float n5 = n3 * n4;
      float n6 = ceilf(n5);
      int n7 = 0;
      int n8 = 721;
      float n9 = (n6<n7?n7:(n6>n8?n8:n6));
      t1.data[t1_offset] = n9;
      t2.data[t2_offset] = n6;
      
    }
}

Traceback (most recent call last):
  File "/av/python/av/experimental/toronto/experiments/intentnet/train.py", line 436, in <module>
    sys.exit(main())
  File "/av/python/av/experimental/toronto/experiments/intentnet/train.py", line 428, in main
    trainer.train_model()
  File "/av/python/av/experimental/toronto/experiments/intentnet/train.py", line 258, in train_model
    should_run_eval = self.train()
  File "/av/python/av/experimental/toronto/experiments/intentnet/train.py", line 181, in train
    voxel_img = self.preprocessor(batched_frames)
  File "/av/lib/python/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: /pytorch-atg/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:138: NVRTC_ERROR unknown
```

## To Reproduce
I am unable to repro yet. I am working on a minimum repro at the moment

**Comment by sidazhang** [comment]
@suo One additional note, this only happens inside training? Do you think optimize is breaking due to some issues with gradients?

**Comment by flacjacket** [comment]
I am seeing a similar error on the following code:
```
import torch


class ConvResidual2d(torch.jit.ScriptModule):
    def __init__(self, channels):
        super(ConvResidual2d, self).__init__()

        self.conv1 = torch.nn.Conv2d(channels, channels, kernel_size=3, padding=1, bias=False)
        self.bn1 = torch.nn.BatchNorm2d(channels)
        self.conv2 = torch.nn.Conv2d(channels, channels, kernel_size=3, padding=1, bias=False)
        self.bn2 = torch.nn.BatchNorm2d(channels)

    @torch.jit.script_method
    def forward(self, x):
        residual = x
        residual = self.conv1(residual)
        residual = self.bn1(residual)
        residual = torch.nn.functional.relu(residual)
        residual = self.conv2(residual)
        residual = self.bn2(residual)

        # x = x + residual
        x += residual
        x = torch.nn.functional.relu(x)

        return x


model = ConvResidual2d(16)
model.cuda()
x = torch.rand((1, 16, 256, 256), device="cuda")
model(x)
print("grad ok")

with torch.no_grad():
    model(x)
print("no grad ok")
```
I'm not sure if this is exactly related, or just failing in a similar way.

This fails with:
```
fusion code:

typedef unsigned char uint8_t;
typedef signed char int8_t;
typedef short int  int16_t;
typedef long long int int64_t;



#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

typedef unsigned int IndexType;
template<typename T, size_t N>
struct TensorInfo {
  T* data;
  IndexType sizes[N];
  IndexType strides[N];
};
template<typename T>
struct TensorInfo<T, 0> {
  T * data;
};


extern "C" __global__
void kernel_0(IndexType totalElements, TensorInfo<float,1> t0, TensorInfo<float,1> t1, TensorInfo<float,1> t2 ) {
  
  for (IndexType linearIndex = blockIdx.x * blockDim.x + threadIdx.x;
        linearIndex < totalElements;
        linearIndex += gridDim.x * blockDim.x) {
      // Convert `linearIndex` into an offset of tensor:
      IndexType t0_offset = 0;
      IndexType t0_linearIndex = linearIndex;
      
      //printf("tensor t0 sizes[0] = %d, strides[0] = %d\n", t0.sizes[0],t0.strides[0]);
      size_t t0_dimIndex0 = t0_linearIndex ;
      t0_offset += t0_dimIndex0 ;
      IndexType t1_offset = 0;
      IndexType t1_linearIndex = linearIndex;
      
      //printf("tensor t1 sizes[0] = %d, strides[0] = %d\n", t1.sizes[0],t1.strides[0]);
      size_t t1_dimIndex0 = t1_linearIndex ;
      t1_offset += t1_dimIndex0 ;
      IndexType t2_offset = 0;
      IndexType t2_linearIndex = linearIndex;
      
      //printf("tensor t2 sizes[0] = %d, strides[0] = %d\n", t2.sizes[0],t2.strides[0]);
      size_t t2_dimIndex0 = t2_linearIndex ;
      t2_offset += t2_dimIndex0 ;
      
      // calculate the results
      float n0 = t0.data[t0_offset];
      float n1 = t1.data[t1_offset];
      int n2 = 1;
      float n3 = n0 + ((float) n2)*n1;
      float n4 = n3 < 0 ? 0.f : n3 ;
      t2.data[t2_offset] = n4;
      
    }
}

Traceback (most recent call last):
  File "test2.py", line 31, in <module>
    model(x)
  File "/home/svig/.cache/bazel/_bazel_svig/792f387f7f19eb90d29496b9fed6e88e/execroot/__main__/bazel-out/release_links/lib/python/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:139: NVRTC_ERROR unknown
```

If I change the addition to `x += residual`, then the forward pass works with the gradient, but in the no_grad block, I get a failure as:
```
fusion code:

typedef unsigned char uint8_t;
typedef signed char int8_t;
typedef short int  int16_t;
typedef long long int int64_t;



#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

typedef unsigned int IndexType;
template<typename T, size_t N>
struct TensorInfo {
  T* data;
  IndexType sizes[N];
  IndexType strides[N];
};
template<typename T>
struct TensorInfo<T, 0> {
  T * data;
};


extern "C" __global__
void kernel_0(IndexType totalElements, TensorInfo<float,2> t0, TensorInfo<float,2> t1, TensorInfo<float,1> t2, TensorInfo<float,2> t3, TensorInfo<float,2> t4, TensorInfo<float,1> t5 ) {

  for (IndexType linearIndex = blockIdx.x * blockDim.x + threadIdx.x;
        linearIndex < totalElements;
        linearIndex += gridDim.x * blockDim.x) {
      // Convert `linearIndex` into an offset of tensor:
      IndexType t0_offset = 0;
      IndexType t0_linearIndex = linearIndex;

      //printf("tensor t0 sizes[1] = %d, strides[1] = %d\n", t0.sizes[1],t0.strides[1]);
      size_t t0_dimIndex1 = t0_linearIndex % t0.sizes[1];
      t0_offset += t0_dimIndex1 * t0.strides[1];
      t0_linearIndex /= t0.sizes[1];

      //printf("tensor t0 sizes[0] = %d, strides[0] = %d\n", t0.sizes[0],t0.strides[0]);
      size_t t0_dimIndex0 = t0_linearIndex ;
      t0_offset += t0_dimIndex0 * t0.strides[0];
      IndexType t1_offset = 0;
      IndexType t1_linearIndex = linearIndex;

      //printf("tensor t1 sizes[1] = %d, strides[1] = %d\n", t1.sizes[1],t1.strides[1]);
      size_t t1_dimIndex1 = t1_linearIndex % t1.sizes[1];
      t1_offset += t1_dimIndex1 * t1.strides[1];
      t1_linearIndex /= t1.sizes[1];

      //printf("tensor t1 sizes[0] = %d, strides[0] = %d\n", t1.sizes[0],t1.strides[0]);
      size_t t1_dimIndex0 = t1_linearIndex ;
      t1_offset += t1_dimIndex0 * t1.strides[0];
      IndexType t2_offset = 0;
      IndexType t2_linearIndex = linearIndex;

      //printf("tensor t2 sizes[0] = %d, strides[0] = %d\n", t2.sizes[0],t2.strides[0]);
      size_t t2_dimIndex0 = t2_linearIndex ;
      t2_offset += t2_dimIndex0 ;
      IndexType t3_offset = 0;
      IndexType t3_linearIndex = linearIndex;

      //printf("tensor t3 sizes[1] = %d, strides[1] = %d\n", t3.sizes[1],t3.strides[1]);
      size_t t3_dimIndex1 = t3_linearIndex % t3.sizes[1];
      t3_offset += t3_dimIndex1 * t3.strides[1];
      t3_linearIndex /= t3.sizes[1];

      //printf("tensor t3 sizes[0] = %d, strides[0] = %d\n", t3.sizes[0],t3.strides[0]);
      size_t t3_dimIndex0 = t3_linearIndex ;
      t3_offset += t3_dimIndex0 * t3.strides[0];
      IndexType t4_offset = 0;
      IndexType t4_linearIndex = linearIndex;

      //printf("tensor t4 sizes[1] = %d, strides[1] = %d\n", t4.sizes[1],t4.strides[1]);
      size_t t4_dimIndex1 = t4_linearIndex % t4.sizes[1];
      t4_offset += t4_dimIndex1 * t4.strides[1];
      t4_linearIndex /= t4.sizes[1];

      //printf("tensor t4 sizes[0] = %d, strides[0] = %d\n", t4.sizes[0],t4.strides[0]);
      size_t t4_dimIndex0 = t4_linearIndex ;
      t4_offset += t4_dimIndex0 * t4.strides[0];
      IndexType t5_offset = 0;
      IndexType t5_linearIndex = linearIndex;

      //printf("tensor t5 sizes[0] = %d, strides[0] = %d\n", t5.sizes[0],t5.strides[0]);
      size_t t5_dimIndex0 = t5_linearIndex ;
      t5_offset += t5_dimIndex0 ;

      // calculate the results
      float n0 = t0.data[t0_offset];
      float n1 = t1.data[t1_offset];
      float n2 = t2.data[t2_offset];
      float n3 = t3.data[t3_offset];
      float n4 = t4.data[t4_offset];
      int n5 = 1;
      float n6 = 1.000000e-05f;
      float n7 = sqrtf(n4);
      float n8 = n7 + ((float) n5)*n6;
      float n9 = 1.f/(n8);
      float n10 = n9 * ((float) n5);
      float n11 = (n2 - ((float) n5)*n3);
      float n12 = n11 * n10;
      float n13 = n12 * n1;
      float n14 = n13 + ((float) n5)*n0;
      float n15 = n14 < 0 ? 0.f : n14 ;
      t5.data[t5_offset] = n15;

    }
}

Traceback (most recent call last):
  File "test2.py", line 36, in <module>
    model(x)
  File "/home/svig/.cache/bazel/_bazel_svig/792f387f7f19eb90d29496b9fed6e88e/execroot/__main__/bazel-out/release_links/lib/python/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:139: NVRTC_ERROR unknown
```

**Comment by sidazhang** [comment]
> I am seeing a similar error on the following code:

What version are you

**Comment by flacjacket** [comment]
Here is the information:
```
PyTorch version: 1.1.0a0+65d6f10
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P2000
Nvidia driver version: 410.104
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```
This is being built from source.

**Comment by soumith** [comment]
cc: @mruberry @ngimel if you know (now that we have a repro) why the NVRTC_ERROR is happening

**Comment by soumith** [comment]
also @flacjacket can you check if this reproduces with the nightly or source build, because #18327 might have fixed something related.

**Comment by sidazhang** [comment]
I no longer have this issue

@flacjacket can you still reproduce?

**Comment by sidazhang** [comment]
@soumith actually nope. You guys don't break on 1080ti anymore. But breaks on TitanXP

**Comment by flacjacket** [comment]
I just gave this a shot off 9696f06 and I am still seeing this problem.

**Comment by flacjacket** [comment]
I dug into this a bit more, and it looks like on the sample code that I posted before, the case running with gradient computations now works.

The `no_grad` case still fails, and requires both `x += residual` rather than `x = x + residual` and `inplace=True` relu's to run without hitting the NVRTC error.

There is a slight change in the fusion debug output running off this newer version:
```
fusion code:

typedef unsigned char uint8_t;
typedef signed char int8_t;
typedef short int  int16_t;
typedef long long int int64_t;



#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

typedef unsigned int IndexType;
template<typename T, size_t N>
struct TensorInfo {
  T* data;
  IndexType sizes[N];
  IndexType strides[N];
};
template<typename T>
struct TensorInfo<T, 0> {
  T * data;
};


extern "C" __global__
void kernel_0(IndexType totalElements, const TensorInfo<float,2> t0, const TensorInfo<float,2> t1, const TensorInfo<float,1> t2, const TensorInfo<float,2> t3, const TensorInfo<float,2> t4, const TensorInfo<float,1> t5 ) {
  
  for (IndexType linearIndex = blockIdx.x * blockDim.x + threadIdx.x;
        linearIndex < totalElements;
        linearIndex += gridDim.x * blockDim.x) {
      // Convert `linearIndex` into an offset of tensor:
      IndexType t0_offset = 0;
      IndexType t0_linearIndex = linearIndex;
      
      //printf("tensor t0 sizes[1] = %d, strides[1] = %d\n", t0.sizes[1],t0.strides[1]);
      size_t t0_dimIndex1 = t0_linearIndex % t0.sizes[1];
      t0_offset += t0_dimIndex1 * t0.strides[1];
      t0_linearIndex /= t0.sizes[1];
      
      //printf("tensor t0 sizes[0] = %d, strides[0] = %d\n", t0.sizes[0],t0.strides[0]);
      size_t t0_dimIndex0 = t0_linearIndex ;
      t0_offset += t0_dimIndex0 * t0.strides[0];
      IndexType t1_offset = 0;
      IndexType t1_linearIndex = linearIndex;
      
      //printf("tensor t1 sizes[1] = %d, strides[1] = %d\n", t1.sizes[1],t1.strides[1]);
      size_t t1_dimIndex1 = t1_linearIndex % t1.sizes[1];
      t1_offset += t1_dimIndex1 * t1.strides[1];
      t1_linearIndex /= t1.sizes[1];
      
      //printf("tensor t1 sizes[0] = %d, strides[0] = %d\n", t1.sizes[0],t1.strides[0]);
      size_t t1_dimIndex0 = t1_linearIndex ;
      t1_offset += t1_dimIndex0 * t1.strides[0];
      IndexType t2_offset = 0;
      IndexType t2_linearIndex = linearIndex;
      
      //printf("tensor t2 sizes[0] = %d, strides[0] = %d\n", t2.sizes[0],t2.strides[0]);
      size_t t2_dimIndex0 = t2_linearIndex ;
      t2_offset += t2_dimIndex0 ;
      IndexType t3_offset = 0;
      IndexType t3_linearIndex = linearIndex;
      
      //printf("tensor t3 sizes[1] = %d, strides[1] = %d\n", t3.sizes[1],t3.strides[1]);
      size_t t3_dimIndex1 = t3_linearIndex % t3.sizes[1];
      t3_offset += t3_dimIndex1 * t3.strides[1];
      t3_linearIndex /= t3.sizes[1];
      
      //printf("tensor t3 sizes[0] = %d, strides[0] = %d\n", t3.sizes[0],t3.strides[0]);
      size_t t3_dimIndex0 = t3_linearIndex ;
      t3_offset += t3_dimIndex0 * t3.strides[0];
      IndexType t4_offset = 0;
      IndexType t4_linearIndex = linearIndex;
      
      //printf("tensor t4 sizes[1] = %d, strides[1] = %d\n", t4.sizes[1],t4.strides[1]);
      size_t t4_dimIndex1 = t4_linearIndex % t4.sizes[1];
      t4_offset += t4_dimIndex1 * t4.strides[1];
      t4_linearIndex /= t4.sizes[1];
      
      //printf("tensor t4 sizes[0] = %d, strides[0] = %d\n", t4.sizes[0],t4.strides[0]);
      size_t t4_dimIndex0 = t4_linearIndex ;
      t4_offset += t4_dimIndex0 * t4.strides[0];
      IndexType t5_offset = 0;
      IndexType t5_linearIndex = linearIndex;
      
      //printf("tensor t5 sizes[0] = %d, strides[0] = %d\n", t5.sizes[0],t5.strides[0]);
      size_t t5_dimIndex0 = t5_linearIndex ;
      t5_offset += t5_dimIndex0 ;
      
      // calculate the results
      float n0 = __ldg(&t0.data[t0_offset]);
      float n1 = __ldg(&t1.data[t1_offset]);
      float n2 = __ldg(&t2.data[t2_offset]);
      float n3 = __ldg(&t3.data[t3_offset]);
      float n4 = __ldg(&t4.data[t4_offset]);
      int n5 = 1;
      float n6 = 1.000000e-05f;
      float n7 = sqrtf(n4);
      float n8 = n7 + ((float) n5)*n6;
      float n9 = 1.f/(n8);
      float n10 = n9 * ((float) n5);
      float n11 = (n2 - ((float) n5)*n3);
      float n12 = n11 * n10;
      float n13 = n12 * n1;
      float n14 = n13 + ((float) n5)*n0;
      float n15 = n14 < 0 ? 0.f : n14 ;
      t5.data[t5_offset] = n15;
      
    }
}

Traceback (most recent call last):
  File "test.py", line 36, in <module>
    model(x)
  File "/home/svig/.cache/bazel/_bazel_svig/792f387f7f19eb90d29496b9fed6e88e/execroot/__main__/bazel-out/release_links/lib/python/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:197: NVRTC_ERROR unknown
```

**Comment by flacjacket** [comment]
Some more information, trying to `torch.jit.save(model, path)` in that same script gives the following:
```
fusion code:

typedef unsigned char uint8_t;
typedef signed char int8_t;
typedef short int  int16_t;
typedef long long int int64_t;



#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

typedef unsigned int IndexType;
template<typename T, size_t N>
struct TensorInfo {
  T* data;
  IndexType sizes[N];
  IndexType strides[N];
};
template<typename T>
struct TensorInfo<T, 0> {
  T * data;
};


extern "C" __global__
void kernel_0(IndexType totalElements, TensorInfo<float,1> t0, TensorInfo<float,1> t1, TensorInfo<float,1> t2 ) {
  
  for (IndexType linearIndex = blockIdx.x * blockDim.x + threadIdx.x;
        linearIndex < totalElements;
        linearIndex += gridDim.x * blockDim.x) {
      // Convert `linearIndex` into an offset of tensor:
      IndexType t0_offset = 0;
      IndexType t0_linearIndex = linearIndex;
      
      //printf("tensor t0 sizes[0] = %d, strides[0] = %d\n", t0.sizes[0],t0.strides[0]);
      size_t t0_dimIndex0 = t0_linearIndex ;
      t0_offset += t0_dimIndex0 ;
      IndexType t1_offset = 0;
      IndexType t1_linearIndex = linearIndex;
      
      //printf("tensor t1 sizes[0] = %d, strides[0] = %d\n", t1.sizes[0],t1.strides[0]);
      size_t t1_dimIndex0 = t1_linearIndex ;
      t1_offset += t1_dimIndex0 ;
      IndexType t2_offset = 0;
      IndexType t2_linearIndex = linearIndex;
      
      //printf("tensor t2 sizes[0] = %d, strides[0] = %d\n", t2.sizes[0],t2.strides[0]);
      size_t t2_dimIndex0 = t2_linearIndex ;
      t2_offset += t2_dimIndex0 ;
      
      // calculate the results
      float n0 = t0.data[t0_offset];
      float n1 = t1.data[t1_offset];
      int n2 = 1;
      float n3 = n0 + ((float) n2)*n1;
      float n4 = n3 < 0 ? 0.f : n3 ;
      t2.data[t2_offset] = n4;
      
    }
}

Traceback (most recent call last):
  File "test.py", line 32, in <module>
    y = model(x)
  File "/home/svig/.cache/bazel/_bazel_svig/792f387f7f19eb90d29496b9fed6e88e/execroot/__main__/bazel-out/release_links/lib/python/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:197: NVRTC_ERROR unknown
```

**Comment by flacjacket** [comment]
Running with gradients and trying to backprop also fails.
Adding:
```
y = model(x)
z = torch.rand_like(y)
x = torch.nn.functional.mse_loss(y, z)
x.backwards()
```
gives:
```
fusion code:

typedef unsigned char uint8_t;
typedef signed char int8_t;
typedef short int  int16_t;
typedef long long int int64_t;



#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

typedef unsigned int IndexType;
template<typename T, size_t N>
struct TensorInfo {
  T* data;
  IndexType sizes[N];
  IndexType strides[N];
};
template<typename T>
struct TensorInfo<T, 0> {
  T * data;
};


extern "C" __global__
void kernel_0(IndexType totalElements, TensorInfo<float,1> t0, TensorInfo<float,1> t1, TensorInfo<float,1> t2 ) {
  
  for (IndexType linearIndex = blockIdx.x * blockDim.x + threadIdx.x;
        linearIndex < totalElements;
        linearIndex += gridDim.x * blockDim.x) {
      // Convert `linearIndex` into an offset of tensor:
      IndexType t0_offset = 0;
      IndexType t0_linearIndex = linearIndex;
      
      //printf("tensor t0 sizes[0] = %d, strides[0] = %d\n", t0.sizes[0],t0.strides[0]);
      size_t t0_dimIndex0 = t0_linearIndex ;
      t0_offset += t0_dimIndex0 ;
      IndexType t1_offset = 0;
      IndexType t1_linearIndex = linearIndex;
      
      //printf("tensor t1 sizes[0] = %d, strides[0] = %d\n", t1.sizes[0],t1.strides[0]);
      size_t t1_dimIndex0 = t1_linearIndex ;
      t1_offset += t1_dimIndex0 ;
      IndexType t2_offset = 0;
      IndexType t2_linearIndex = linearIndex;
      
      //printf("tensor t2 sizes[0] = %d, strides[0] = %d\n", t2.sizes[0],t2.strides[0]);
      size_t t2_dimIndex0 = t2_linearIndex ;
      t2_offset += t2_dimIndex0 ;
      
      // calculate the results
      float n0 = t0.data[t0_offset];
      float n1 = t1.data[t1_offset];
      int n2 = 1;
      float n3 = n0 + ((float) n2)*n1;
      float n4 = n3 < 0 ? 0.f : n3 ;
      t2.data[t2_offset] = n4;
      
    }
}

Traceback (most recent call last):
  File "test.py", line 32, in <module>
    y = model(x)
  File "/home/svig/.cache/bazel/_bazel_svig/792f387f7f19eb90d29496b9fed6e88e/execroot/__main__/bazel-out/release_links/lib/python/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:197: NVRTC_ERROR unknown
```

**Comment by sidazhang** [comment]
Yeah. I also see it when I train (inference is fine now. But train sometimes have problems)

**Comment by mruberry** [comment]
I agree it looks like an error and it could be hardware specific. I can't reproduce on Quadro P100 or V100 running the script 100+ times or its variant, though. Your environment data indicates Quadro P2000 hardware, do you get a consistent repro with that hardware or just on the TitanXP? Also, are these issues all on the same machine or is this multiple machines but the same GPU?

**Comment by svensht2** [comment]
For what its worth, I've been dealing with a crash in:
csrc/jit/fuser/cuda/fused_kernel.cpp:131: NVRTC_ERROR unknown 
I figured that the "unknown" was actually NVRTC_ERROR_BUILTIN_OPERATION_FAILURE =
libnvrtc was silently failing because it couldnt find lbnvrtc-builtin, which I think it dlopens and perhaps only looking for it in the same directory
Once I copied libnvrtc-builtin to the same lib folder as libnvrtc everything started working

**Comment by ngimel** [comment]
Closing, please reopen if workaround in https://github.com/pytorch/pytorch/issues/16592#issuecomment-486875369 does not solve it.

**Comment by suo** [comment]
@ngimel, can we get a more explicit error message in the case where libnvrtc-builtin is not found? That way we can tell if future "NVRTC_ERROR unknown" errors are from the same cause or not.

**Comment by flacjacket** [comment]
I'll note that I was able to figure out how to get the code that I was trying to use to run, but it didn't have anything to do with libnvrtc-builtin. What I did was change my forward function noted above (https://github.com/pytorch/pytorch/issues/16592#issuecomment-474984213) to use in-place relu's and changed from:
```
x = x + residual
x = torch.nn.functional.relu(x)

return x
```
to 
```
residual += x
residual = torch.nn.functional.relu_(residual)

return residual
```
It would seem to me there is some other issue.

**Comment by ngimel** [comment]
@suo pytorch is already correctly trying to extract error message from libnvrtc https://github.com/pytorch/pytorch/blob/428104c60a07938f97f33ab1b6c68c3ea91abb81/torch/csrc/jit/fuser/cuda/fused_kernel.cpp#L67-L73, the problem is libnvrtc is returning unhelpful "unknown error", which is a general problem with many cuda tools https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-59/750/5
@flacjacket by using inplace operation instead of out-of-place, you are disabling fusion, and thus do not require nvrtc anymore. It's a workaround, but it does not shed light on nvrtc problem. 
@mruberry was not able to repro this, so I'm not sure how to move forward.

**Comment by mruberry** [comment]
Update:

It turns out that nvrtc is incorrectly producing "unknown error" instead of NVRTC_ERROR_BUILTIN_OPERATION_FAILURE, which may be the error you're seeing. I submitted a PR to correct this ( #21174).

Would you please retry with a newer version of PyTorch containing this update? Alternatively you can port the update to your version of PyTorch, too (the code change is very small and safe). The nvrtc team here at NVIDIA suspects this is the error you're hitting and would like to confirm.

**Comment by sto-chastic** [comment]
I was getting this error on this line of code:

**Comment by mruberry** [comment]
Thanks for the update, @sto-chastic. To be clear, did you see NVRTC_ERROR_BUILTIN_OPERATION_FAILURE or "unknown error?" Also, which version of PyTorch are you using?

@csarofeen

**Comment by ezyang** [comment]
Unassigning stale assignee

**Comment by suo** [comment]
removed high priority as we don't have enough information to investigate right now :(

**Comment by sidazhang** [comment]
@suo  lol, you mean you don't have enough information to investigate an unknown error?

jks jks!


@mcarilli @mkolod you guys need to improve your error codes. Hahah! Stop playing error hide and seek with users! :P

**Comment by ngimel** [comment]
@sidazhang is it still an issue? I thought it was fixed one way or another, turned out to be some dlopen error?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
