### ISSUE TITLE
Problem with numpy while installing torch.

### ISSUE THREAD

**Issue by Pythonista7** [pytorch/pytorch#16609]
## ❓ Questions and Help
I was running this command to install pytorch on a python 3.6.7 ver with pip3 on ubuntu 16.04
**pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
pip3 install torchvision**

After pip3 installing ,on trying to "import torch" i get a error from numpy lib file and pain numpy import also throws:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ashwin/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/ashwin/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/ashwin/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/ashwin/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/ashwin/.local/lib/python3.6/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'**

I tried uninstalling numpy and downgrader to a ver from Nov 2018 which works fine ,but again on trying to install pytorch the same issue persists.
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by zou3519** [comment]
Could you please add some more information about your environment and what version of pytorch / numpy you have?

**Comment by Pythonista7** [comment]
Current Env is Python 3.6.7 on Ubuntu 18.04.  .The issue was resolved after I downgraded from Numpy 1.16.1 to Numpy 1.15.4, No issues with Torch now. Thank you @zou3519 :)
