### ISSUE TITLE
test_proper_exit is flaky

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#16608]
This causes errors like this on CI:

```
pytorch_linux_trusty_py3_6_gcc7_test build:

Jan 31 13:43:05 ======================================================================
Jan 31 13:43:05 FAIL: test_proper_exit (__main__.TestDataLoader)
Jan 31 13:43:05 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
Jan 31 13:43:05 ----------------------------------------------------------------------
Jan 31 13:43:05 Traceback (most recent call last):
Jan 31 13:43:05   File "/var/lib/jenkins/workspace/test/common_utils.py", line 120, in wrapper
Jan 31 13:43:05     fn(*args, **kwargs)
Jan 31 13:43:05   File "test_dataloader.py", line 790, in test_proper_exit
Jan 31 13:43:05     self.assertIsInstance(loader_p.exception, RuntimeError, desc)
Jan 31 13:43:05 AssertionError: ConnectionRefusedError('Traceback (most recent call last):\n  File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 175, in run\n    super(ErrorTrackingProcess, self).run()\n  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 354, in _test_proper_exit\n    for i, _ in enumerate(it):\n  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 507, in __next__\n    idx, batch = self._get_batch()\n  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 484, in _get_batch\n    success, data = self._try_get_batch()\n  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 442, in _try_get_batch\n    data = self.data_queue.get(timeout=timeout)\n  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 113, in get\n    return _ForkingPickler.loads(res)\n  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 257, in rebuild_storage_fd\n    fd = df.detach()\n  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach\n    with _resource_sharer.get_connection(self._id) as conn:\n  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection\n    c = Client(address, authkey=process.current_process().authkey)\n  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 487, in Client\n    c = SocketClient(address)\n  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient\n    s.connect(address)\nConnectionRefusedError: [Errno 111] Connection refused\n',) is not an instance of <class 'RuntimeError'> : test_proper_exit with use_workers=True, pin_memory=False, hold_iter_reference=False, exit_method=worker_kill
Jan 31 13:43:05 
```
https://circleci.com/gh/pytorch/pytorch/682993?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Formatted error message.
```py
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 175, in run
    super(ErrorTrackingProcess, self).run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 354, in _test_proper_exit
    for i, _ in enumerate(it):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 507, in __next__
    idx, batch = self._get_batch()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 484, in _get_batch
    success, data = self._try_get_batch()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 442, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 257, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

Interesting how it passed the `is_alive` checks at https://github.com/pytorch/pytorch/blob/d47108add0eaddbdaf1cf8bc95599faac66442cd/torch/utils/data/dataloader.py#L448-L450

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL

**Comment by ezyang** [comment]
Another failure occurrence: https://circleci.com/gh/pytorch/pytorch/731693?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
Another occurrence: https://circleci.com/gh/pytorch/pytorch/758305?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SsnL** [comment]
There seem to be two types of errors:
1. on `pytorch_linux_trusty_py3_6_gcc7_test`:
  the error described in the issue.
2. on `pytorch_linux_trusty_py2_7_test`:
  ```
   AssertionError: test_proper_exit with use_workers=True, pin_memory=False, hold_iter_reference=False, exit_method=worker_kill: loader process did not terminate, and had no exception
  ``

**Comment by peterjc123** [comment]
And on Windows: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/25535/console.

**Comment by SsnL** [comment]
weird windows failure on #14501:
```
18:50:11 ======================================================================
18:50:11 FAIL: test_proper_exit (__main__.TestDataLoader)
18:50:11 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
18:50:11 ----------------------------------------------------------------------
18:50:11 Traceback (most recent call last):
18:50:11   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test2\test\common_utils.py", line 129, in wrapper
18:50:11     fn(*args, **kwargs)
18:50:11   File "test_dataloader.py", line 795, in test_proper_exit
18:50:11     self.fail(fail_msg + ', and exited with code {} but had no exception'.format(loader_p.exitcode))
18:50:11 AssertionError: test_proper_exit with use_workers=True, pin_memory=True, hold_iter_reference=True, exit_method=None: loader process failed to setup within given time, and exited with code 3221225477 but had no exception
```

**Comment by SsnL** [comment]
For reference, with `faulthandler`, I found case of a hanging in `done_event.set()`. Not sure how that can happen:
```
Apr 23 03:43:21 Thread 0x00007ffa7bfff700 (most recent call first):
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 295 in wait
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 222 in _feed
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 864 in run
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 916 in _bootstrap_inner
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 884 in _bootstrap
Apr 23 03:43:21 
Apr 23 03:43:21 Thread 0x00007ffa80fcf700 (most recent call first):
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 295 in wait
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 222 in _feed
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 864 in run
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 916 in _bootstrap_inner
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/threading.py", line 884 in _bootstrap
Apr 23 03:43:21 
Apr 23 03:43:21 Current thread 0x00007ffa9a5ac740 (most recent call first):
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 95 in __enter__
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 230 in __enter__
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 346 in set
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 605 in _shutdown_workers
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637 in __del__
Apr 23 03:43:21   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 411 in _test_proper_exit
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93 in run
Apr 23 03:43:21   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 213 in run
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258 in _bootstrap
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 118 in _main
Apr 23 03:43:21   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 105 in spawn_main
Apr 23 03:43:21   File "<string>", line 1 in <module>
Apr 23 03:43:31 FAIL

Apr 23 03:43:38 
Apr 23 03:43:38 ======================================================================
Apr 23 03:43:38 FAIL: test_proper_exit (__main__.TestDataLoader)
Apr 23 03:43:38 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
Apr 23 03:43:38 ----------------------------------------------------------------------
Apr 23 03:43:38 Traceback (most recent call last):
Apr 23 03:43:38   File "/var/lib/jenkins/workspace/test/common_utils.py", line 129, in wrapper
Apr 23 03:43:38     fn(*args, **kwargs)
Apr 23 03:43:38   File "test_dataloader.py", line 824, in test_proper_exit
Apr 23 03:43:38     self.fail(fail_msg + ', and had no exception')
Apr 23 03:43:38 AssertionError: test_proper_exit with use_workers=True, pin_memory=False, hold_iter_reference=False, exit_method=worker_kill: loader process did not terminate, and had no exception
```

https://circleci.com/gh/pytorch/pytorch/1422877?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SsnL** [comment]
Merging content of https://github.com/pytorch/pytorch/issues/14501 here:

A previous failure on master
https://circleci.com/gh/pytorch/pytorch/1184431?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
@ailzhang Quick tip: "module: build" means build system problems; it doesn't refer to ci flakiness :)

**Comment by ezyang** [comment]
Still failing: https://circleci.com/gh/pytorch/pytorch/1738847?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SsnL** [comment]
@ezyang please disable if you see it happens again. i'll add strace printing to it after neurips deadline on thursday, and hopefully we can understand what the heck is going on.

**Comment by ezyang** [comment]
A more recent failure:

```

Jun 06 20:57:47 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore ... Process ErrorTrackingProcess-11:
Jun 06 20:57:47 Traceback (most recent call last):
Jun 06 20:57:47   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Jun 06 20:57:47     self.run()
Jun 06 20:57:47   File "test_dataloader.py", line 250, in run
Jun 06 20:57:47     super(ErrorTrackingProcess, self).run()
Jun 06 20:57:47   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Jun 06 20:57:47     self._target(*self._args, **self._kwargs)
Jun 06 20:57:47   File "test_dataloader.py", line 454, in _test_proper_exit
Jun 06 20:57:47     raise RuntimeError('Loader error')
Jun 06 20:57:47 RuntimeError: Loader error
Jun 06 20:57:52 Process ErrorTrackingProcess-13:
Jun 06 20:57:52 Traceback (most recent call last):
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Jun 06 20:57:52     self.run()
Jun 06 20:57:52   File "test_dataloader.py", line 250, in run
Jun 06 20:57:52     super(ErrorTrackingProcess, self).run()
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Jun 06 20:57:52     self._target(*self._args, **self._kwargs)
Jun 06 20:57:52   File "test_dataloader.py", line 439, in _test_proper_exit
Jun 06 20:57:52     for i, _ in enumerate(it):
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 583, in __next__
Jun 06 20:57:52     return self._process_next_batch(batch)
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 609, in _process_next_batch
Jun 06 20:57:52     raise batch.exc_type(batch.exc_msg)
Jun 06 20:57:52 RuntimeError: Traceback (most recent call last):
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 108, in _worker_loop
Jun 06 20:57:52     samples = collate_fn([dataset[i] for i in batch_indices])
Jun 06 20:57:52   File "test_dataloader.py", line 400, in __getitem__
Jun 06 20:57:52     raise RuntimeError('Worker error')
Jun 06 20:57:52 RuntimeError: Worker error
Jun 06 20:57:52 
Jun 06 20:57:52 Process ErrorTrackingProcess-15:
Jun 06 20:57:52 Traceback (most recent call last):
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Jun 06 20:57:52     self.run()
Jun 06 20:57:52   File "test_dataloader.py", line 250, in run
Jun 06 20:57:52     super(ErrorTrackingProcess, self).run()
Jun 06 20:57:52   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Jun 06 20:57:52     self._target(*self._args, **self._kwargs)
Jun 06 20:57:52   File "test_dataloader.py", line 454, in _test_proper_exit
Jun 06 20:57:52     raise RuntimeError('Loader error')
Jun 06 20:57:52 RuntimeError: Loader error
Jun 06 20:57:57 Process ErrorTrackingProcess-17:
Jun 06 20:57:57 Traceback (most recent call last):
Jun 06 20:57:57   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Jun 06 20:57:57     self.run()
Jun 06 20:57:57   File "test_dataloader.py", line 250, in run
Jun 06 20:57:57     super(ErrorTrackingProcess, self).run()
Jun 06 20:57:57   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Jun 06 20:57:57     self._target(*self._args, **self._kwargs)
Jun 06 20:57:57   File "test_dataloader.py", line 439, in _test_proper_exit
Jun 06 20:57:57     for i, _ in enumerate(it):
Jun 06 20:57:57   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 583, in __next__
Jun 06 20:57:57     return self._process_next_batch(batch)
Jun 06 20:57:57   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 609, in _process_next_batch
Jun 06 20:57:57     raise batch.exc_type(batch.exc_msg)
Jun 06 20:57:57 RuntimeError: Traceback (most recent call last):
Jun 06 20:57:57   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 108, in _worker_loop
Jun 06 20:57:57     samples = collate_fn([dataset[i] for i in batch_indices])
Jun 06 20:57:57   File "test_dataloader.py", line 400, in __getitem__
Jun 06 20:57:57     raise RuntimeError('Worker error')
Jun 06 20:57:57 RuntimeError: Worker error
Jun 06 20:57:57 
Jun 06 20:59:02 Current thread 0x00007fe1dfff0740 <python> (most recent call first):
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/forking.py", line 135 in poll
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/forking.py", line 154 in wait
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 145 in join
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 660 in _shutdown_workers
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 678 in __del__
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 261 in _bootstrap
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/forking.py", line 126 in __init__
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 130 in start
Jun 06 20:59:02   File "test_dataloader.py", line 849 in test_proper_exit
Jun 06 20:59:02   File "/var/lib/jenkins/workspace/test/common_utils.py", line 149 in wrapper
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 329 in run
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 393 in __call__
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 108 in run
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70 in __call__
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/runner.py", line 151 in run
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 232 in runTests
Jun 06 20:59:02   File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 95 in __init__
Jun 06 20:59:02   File "/var/lib/jenkins/workspace/test/common_utils.py", line 60 in run_tests
Jun 06 20:59:02   File "test_dataloader.py", line 1258 in <module>
Jun 06 20:59:07 Thread 0x00007fe1d8c74700 <python> (most recent call first):
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/socket.py", line 202 in accept
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/connection.py", line 275 in accept
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/connection.py", line 145 in accept
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/reduction.py", line 124 in _serve
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/threading.py", line 763 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/threading.py", line 810 in __bootstrap_inner
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/threading.py", line 783 in __bootstrap
Jun 06 20:59:07 
Jun 06 20:59:07 Thread 0x00007fe1c23d1700 <python> (most recent call first):
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/queues.py", line 264 in _feed
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/threading.py", line 763 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/threading.py", line 810 in __bootstrap_inner
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/threading.py", line 783 in __bootstrap
Jun 06 20:59:07 
Jun 06 20:59:07 Current thread 0x00007fe1dfff0740 <python> (most recent call first):
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/queues.py", line 131 in get
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 90 in _worker_loop
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258 in _bootstrap
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/forking.py", line 126 in __init__
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 130 in start
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 470 in __init__
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 194 in __iter__
Jun 06 20:59:07   File "test_dataloader.py", line 429 in _test_proper_exit
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114 in run
Jun 06 20:59:07   File "test_dataloader.py", line 250 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 258 in _bootstrap
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/forking.py", line 126 in __init__
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 130 in start
Jun 06 20:59:07   File "test_dataloader.py", line 849 in test_proper_exit
Jun 06 20:59:07   File "/var/lib/jenkins/workspace/test/common_utils.py", line 149 in wrapper
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 329 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 393 in __call__
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 108 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70 in __call__
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/runner.py", line 151 in run
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 232 in runTests
Jun 06 20:59:07   File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 95 in __init__
Jun 06 20:59:07   File "/var/lib/jenkins/workspace/test/common_utils.py", line 60 in run_tests
Jun 06 20:59:07   File "test_dataloader.py", line 1258 in <module>
Jun 06 20:59:12 FAIL
...

Jun 06 20:59:15 ======================================================================
Jun 06 20:59:15 FAIL: test_proper_exit (__main__.TestDataLoader)
Jun 06 20:59:15 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
Jun 06 20:59:15 ----------------------------------------------------------------------
Jun 06 20:59:15 Traceback (most recent call last):
Jun 06 20:59:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 149, in wrapper
Jun 06 20:59:15     fn(*args, **kwargs)
Jun 06 20:59:15   File "test_dataloader.py", line 906, in test_proper_exit
Jun 06 20:59:15     fail(fail_reason + ', and had exception {}'.format(loader_p.exception))
Jun 06 20:59:15   File "test_dataloader.py", line 897, in fail
Jun 06 20:59:15     self.fail(err_msg)
Jun 06 20:59:15 AssertionError: test_proper_exit with use_workers=True, pin_memory=False, hold_iter_reference=False, exit_method=worker_kill: loader process did not terminate, and had exception Traceback (most recent call last):
Jun 06 20:59:15   File "test_dataloader.py", line 250, in run
Jun 06 20:59:15     super(ErrorTrackingProcess, self).run()
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
Jun 06 20:59:15     self._target(*self._args, **self._kwargs)
Jun 06 20:59:15   File "test_dataloader.py", line 439, in _test_proper_exit
Jun 06 20:59:15     for i, _ in enumerate(it):
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 577, in __next__
Jun 06 20:59:15     idx, batch = self._get_batch()
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 554, in _get_batch
Jun 06 20:59:15     success, data = self._try_get_batch()
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 512, in _try_get_batch
Jun 06 20:59:15     data = self.data_queue.get(timeout=timeout)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/queues.py", line 135, in get
Jun 06 20:59:15     res = self._recv()
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 22, in recv
Jun 06 20:59:15     return pickle.loads(buf)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/pickle.py", line 1382, in loads
Jun 06 20:59:15     return Unpickler(file).load()
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/pickle.py", line 858, in load
Jun 06 20:59:15     dispatch[key](self)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/pickle.py", line 1133, in load_reduce
Jun 06 20:59:15     value = func(*args)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/multiprocessing/reductions.py", line 274, in rebuild_storage_fd
Jun 06 20:59:15     fd = multiprocessing.reduction.rebuild_handle(df)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/reduction.py", line 155, in rebuild_handle
Jun 06 20:59:15     conn = Client(address, authkey=current_process().authkey)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/connection.py", line 169, in Client
Jun 06 20:59:15     c = SocketClient(address)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/multiprocessing/connection.py", line 304, in SocketClient
Jun 06 20:59:15     s.connect(address)
Jun 06 20:59:15   File "/opt/python/2.7.9/lib/python2.7/socket.py", line 224, in meth
Jun 06 20:59:15     return getattr(self._sock,name)(*args)
Jun 06 20:59:15 error: [Errno 111] Connection refused
Jun 06 20:59:15 
Jun 06 20:59:15 Loader info:
Jun 06 20:59:15 	{'status': 'sleeping', 'cpu_times': pcputimes(user=0.23, system=0.21, children_user=0.01, children_system=0.0), 'name': 'python', 'num_ctx_switches': pctxsw(voluntary=2018, involuntary=5), 'pid': 27598, 'memory_full_info': pfullmem(rss=47456256, vms=794431488, shared=9064448, text=4096, lib=0, data=173649920, dirty=0, uss=3203072, pss=17477632, swap=0), 'io_counters': pio(read_count=135, write_count=53, read_bytes=0, write_bytes=4096, read_chars=233585, write_chars=4016), 'threads': [pthread(id=27598, user_time=0.23, system_time=0.21)], 'ionice': pionice(ioclass=0, value=4), 'open_files': [], 'nice': 0}
Jun 06 20:59:15 Worker(s) info:
Jun 06 20:59:15 	Worker 0:
Jun 06 20:59:15 		{'status': 'sleeping', 'cpu_times': pcputimes(user=0.0, system=0.0, children_user=0.0, children_system=0.0), 'name': 'python', 'num_ctx_switches': pctxsw(voluntary=19, involuntary=0), 'pid': 27600, 'memory_full_info': pfullmem(rss=48287744, vms=794025984, shared=10043392, text=4096, lib=0, data=173244416, dirty=0, uss=3543040, pss=18566144, swap=0), 'io_counters': pio(read_count=47, write_count=14, read_bytes=0, write_bytes=4096, read_chars=71291, write_chars=903), 'threads': [pthread(id=27600, user_time=0.0, system_time=0.0), pthread(id=27604, user_time=0.0, system_time=0.0), pthread(id=27606, user_time=0.0, system_time=0.0)], 'ionice': pionice(ioclass=0, value=4), 'open_files': [], 'nice': 0}
Jun 06 20:59:15 	Worker 1:
Jun 06 20:59:15 		exited with unknown code
```

https://circleci.com/gh/pytorch/pytorch/1934691?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by gchanan** [comment]
If this hasn't been fixed, I'll turn it off.

**Comment by SsnL** [comment]
@gchanan the flaky parts of it were already turned off.

**Comment by gchanan** [comment]
@SsnL ok, should we get rid of the high priority label then?

**Comment by SsnL** [comment]
Removing hi-priority label since the flaky parts were turned off in https://github.com/pytorch/pytorch/pull/22208

**Comment by pietern** [comment]
It is still flaky, see https://circleci.com/gh/pytorch/pytorch/3298238?

**Comment by zdevito** [comment]
https://app.circleci.com/jobs/github/pytorch/pytorch/3590735

**Comment by zdevito** [comment]
re-flaggin high-pri since it is still flaking out on CI.

**Comment by mruberry** [comment]
@SsnL Is this issue still relevant?

**Comment by SsnL** [comment]
I’m not really closely monitoring CI so I’m not sure.

**Comment by mruberry** [comment]
OK; I'll close this for now and see if it comes back. The test appears to be functioning correctly now.
