### ISSUE TITLE
ROCm 2.1: test_gamma_gpu_sample test fails

### ISSUE THREAD

**Issue by yet-another-account** [pytorch/pytorch#16661]
## 🐛 Bug
Failed test when building pytorch in ROCm 2.1 docker container. 

Log Excerpt:
```
...
test_jacobian_shape (test_distributions.TestTransforms) ... ok
test_jit_fwd (test_distributions.TestTransforms) ... ok
test_jit_inv (test_distributions.TestTransforms) ... ok
test_jit_jacobian (test_distributions.TestTransforms) ... ok
test_transform_shapes (test_distributions.TestTransforms) ... ok
test_transformed_distribution_shapes (test_distributions.TestTransforms) ... ok
test_univariate_forward_jacobian (test_distributions.TestTransforms) ... ok
test_univariate_inverse_jacobian (test_distributions.TestTransforms) ... ok
test_invalid (test_distributions.TestValidation) ... ok
test_valid (test_distributions.TestValidation) ... ok

======================================================================
FAIL: test_gamma_gpu_sample (test_distributions.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/pytorch/test/common_utils.py", line 296, in wrapper
    method(*args, **kwargs)
  File "/data/pytorch/test/test_distributions.py", line 1985, in test_gamma_gpu_sample
    failure_rate=1e-4)
  File "/data/pytorch/test/test_distributions.py", line 705, in _check_sampler_sampler
    self.assertLess(bias, threshold, message)
AssertionError: 0.094 not less than 0.06743384440337652 : Gamma(alpha=1.0, beta=0.1).sample() is biased:
[-0.005 -0.012  0.015  0.009  0.094  0.007 -0.049  0.006 -0.028 -0.037]

----------------------------------------------------------------------
Ran 190 tests in 13.375s

FAILED (failures=1, skipped=2)
Traceback (most recent call last):
  File "test/run_test.py", line 456, in <module>
    main()
  File "test/run_test.py", line 448, in main
    raise RuntimeError(message)
RuntimeError: test_distributions failed!
```

## To Reproduce

Followed instructions from [ROCm docs](https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html). `export HCC_AMDGPU_TARGET=gfx803` was run prior to building. 

## Expected behavior
Step 7 should finish without any errors.

## Environment

 - PyTorch Version (e.g., 1.0): master@7078b2ba
 - OS (e.g., Linux): Ubuntu 16.04 in docker
 - How you installed PyTorch (`conda`, `pip`, source): Source following ROCm
 - Build command you used (if compiling from source): Following ROCm tutorial (`.jenkins/pytorch/build.sh`)
 - Python version: 2.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: RX580
 - Any other relevant information:

## Additional context

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by hongxiayang** [comment]
This issue needs to be closed as it is too old
