### ISSUE TITLE
[build error] Build caffe error

### ISSUE THREAD

**Issue by terbed** [pytorch/pytorch#16693]
## ❓Error while building latest pytorch

```
[ 70%] Building CXX object caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/manager.cpp.o
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.hIn file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:120:
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.hIn file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:120:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
In file included from :120:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
120:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
:120:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
<built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:120:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
[ 70%] Built target caffe2_pybind11_state
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorCopy.cu.o
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:120:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/anaconda2/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at caffe2_gpu_generated_THCSleep.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCSleep.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCSleep.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
CMake Error at caffe2_gpu_generated_THCBlas.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCBlas.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCBlas.cu.o] Error 1
1 error generated.
CMake Error at caffe2_gpu_generated_THCReduceApplyUtils.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCReduceApplyUtils.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.o] Error 1
1 error generated.
1 error generated.
CMake Error at caffe2_gpu_generated_THCTensor.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensor.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensor.cu.o] Error 1
CMake Error at caffe2_gpu_generated_THCStorageCopy.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCStorageCopy.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorageCopy.cu.o] Error 1
1 error generated.
CMake Error at caffe2_gpu_generated_THCTensorCopy.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensorCopy.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorCopy.cu.o] Error 1
1 error generated.
CMake Error at caffe2_gpu_generated_THCStorage.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/Dani/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCStorage.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorage.cu.o] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Linking CXX executable ../../../../bin/torch_shm_manager
[ 70%] Built target torch_shm_manager
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 720, in <module>
    build_deps()
  File "setup.py", line 279, in build_deps
    build_dir='build')
  File "/Users/Dani/pytorch/tools/build_pytorch_libs.py", line 248, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/anaconda2/envs/pytorch/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8', 'install']' returned non-zero exit status 2.
```

I did the installing steps presented in the official website. This is on macOS.

UI.:
Interesting that there is string.h in the anaconda directory:
```
ls /anaconda2/bin/../include/c++/v1/
__bit_reference			cfenv				float.h				set
__bsd_locale_defaults.h		cfloat				forward_list			setjmp.h
__bsd_locale_fallbacks.h	chrono				fstream				shared_mutex
__config			cinttypes			functional			sstream
__cxxabi_config.h		ciso646				future				stack
__debug				climits				initializer_list		stdbool.h
__functional_03			clocale				inttypes.h			stddef.h
__functional_base		cmath				iomanip				stdexcept
__functional_base_03		codecvt				ios				stdint.h
__hash_table			complex				iosfwd				stdio.h
__libcpp_version		complex.h			iostream			stdlib.h
__locale			condition_variable		istream				streambuf
__mutex_base			csetjmp				iterator			string
__nullptr			csignal				limits				string.h
__refstring			cstdarg				limits.h			string_view
__split_buffer			cstdbool			list				strstream
__sso_allocator			cstddef				locale				support
__std_stream			cstdint				locale.h			system_error
__string			cstdio				map				tgmath.h
__threading_support		cstdlib				math.h				thread
__tree				cstring				memory				tuple
__tuple				ctgmath				module.modulemap		type_traits
__undef_min_max			ctime				mutex				typeindex
algorithm			ctype.h				new				typeinfo
any				cwchar				numeric				unordered_map
array				cwctype				optional			unordered_set
atomic				cxxabi.h			ostream				utility
bitset				deque				queue				valarray
cassert				errno.h				random				variant
ccomplex			exception			ratio				vector
cctype				experimental			regex				wchar.h
cerrno				ext				scoped_allocator		wctype.h

```

**Comment by martijnvanattekum** [comment]
similar to #16602

**Comment by hafbau** [comment]
> similar to #16602

I do not see how this is similar to #16602

**Comment by ezyang** [comment]
It seems like there is something wrong with your system headers. I'm not sure how we can help here. You could try blowing away your Anaconda environment and trying again.
