### ISSUE TITLE
error when saving big objects

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#1669]
```python
a = np.zeros(1000000000)
torch.save(a, 'a.pkl')
```

will fail with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guismay/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/home/guismay/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 186, in _save
    pickler.dump(obj)
SystemError: error return without exception set
```

However,
```python
a = np.zeros(1000000000)
torch.save(torch.from_numpy(a), 'a.pkl')
```
Seems to work properly.

**Comment by apaszke** [comment]
This is expected. We're serializing tensors via a custom code path, but numpy arrays go through regular pickler. There are known problems when you [serialize arrays that are >2GB](https://bugs.python.org/msg134369) (probably overflows in Python's C code). Won't fix.
