### ISSUE TITLE
test_events_multi_gpu_elapsed_time is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16759]
```
Feb 05 05:44:45 ======================================================================
Feb 05 05:44:45 ERROR: test_events_multi_gpu_elapsed_time (__main__.TestCuda)
Feb 05 05:44:45 ----------------------------------------------------------------------
Feb 05 05:44:45 Traceback (most recent call last):
Feb 05 05:44:45   File "/var/lib/jenkins/workspace/test/common_utils.py", line 296, in wrapper
Feb 05 05:44:45     method(*args, **kwargs)
Feb 05 05:44:45   File "/var/lib/jenkins/workspace/test/common_utils.py", line 120, in wrapper
Feb 05 05:44:45     fn(*args, **kwargs)
Feb 05 05:44:45   File "test_cuda.py", line 1880, in test_events_multi_gpu_elapsed_time
Feb 05 05:44:45     torch.cuda._sleep(TestCuda.FIFTY_MIL_CYCLES)
Feb 05 05:44:45   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 54, in _sleep
Feb 05 05:44:45     torch._C._cuda_sleep(cycles)
Feb 05 05:44:45 RuntimeError: cuda runtime error (33) : invalid resource handle at /var/lib/jenkins/workspace/aten/src/THC/THCSleep.cu:20
Feb 05 05:44:45 
Feb 05 05:44:45 ----------------------------------------------------------------------
```

log: https://circleci.com/gh/pytorch/pytorch/716538?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
cc @mrshenli

**Comment by ezyang** [comment]
Actually, it's not just flaky, it's totally broken. Reverting culprit commit #16705
