### ISSUE TITLE
ONNX export of interpolate crashes if used after mul with constant

### ISSUE THREAD

**Issue by tdanyluk** [pytorch/pytorch#16799]
## 🐛 Bug

ASSERT FAILED at /pytorch/aten/src/ATen/core/jit_type.h:128
## To Reproduce

1. run the code

import torch
import torch.nn.functional as F

class Interpolate(torch.nn.Module):
    def __init__(self, scale_factor=None, mode=None, align_corners=None):
        super(Interpolate, self).__init__()

        assert scale_factor is not None
        assert mode
        assert align_corners is None or isinstance(align_corners, bool)

        self.scale_factor = float(scale_factor)
        self.mode = str(mode)
        self.align_corners = align_corners

    def forward(self, input):
        return F.interpolate(input * 0.5, scale_factor=self.scale_factor, mode=self.mode, align_corners=self.align_corners)

dummy_input = torch.randn(10, 3, 224, 224, device='cuda')
model = Interpolate(scale_factor=2, mode='bilinear').cuda()

torch.onnx.export(model, dummy_input, "first.onnx", verbose=T

## Expected behavior

success

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 384.145
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.4.2
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/projects/torchnetworks/first.py", line 25, in <module>
    torch.onnx.export(model, dummy_input, "first.onnx", verbose=True)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/utils.py", line 227, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/utils.py", line 155, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/__init__.py", line 52, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/utils.py", line 504, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/symbolic.py", line 89, in wrapper
    return fn(g, *args)
  File "/home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/onnx/symbolic.py", line 657, in upsample_bilinear2d
    height_scale = float(output_size[-2]) / input.type().sizes()[-2]
RuntimeError: r ASSERT FAILED at /pytorch/aten/src/ATen/core/jit_type.h:128, please report a bug to PyTorch. (expect at /pytorch/aten/src/ATen/core/jit_type.h:128)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7feaf6b5ffe1 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7feaf6b5fdfa in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #2: std::shared_ptr<c10::CompleteTensorType> c10::Type::expect<c10::CompleteTensorType>() + 0x161 (0x7feb30ee1921 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x37a50b (0x7feb30ef750b in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x116fac (0x7feb30c93fac in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #5: PyCFunction_Call + 0x77 (0x4ea137 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #6: PyEval_EvalFrameEx + 0x59f6 (0x53c176 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #7: PyEval_EvalCodeEx + 0x13b (0x540b0b in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #8: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x4ec2e3]
frame #9: PyObject_Call + 0x47 (0x5c20e7 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #10: PyEval_EvalFrameEx + 0x252b (0x538cab in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #11: PyEval_EvalCodeEx + 0x87a (0x54124a in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #12: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x4ec3f7]
frame #13: PyObject_Call + 0x47 (0x5c20e7 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #14: PyEval_EvalFrameEx + 0x252b (0x538cab in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #15: PyEval_EvalCodeEx + 0x87a (0x54124a in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #16: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x4ec3f7]
frame #17: PyObject_Call + 0x47 (0x5c20e7 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #18: PyEval_EvalFrameEx + 0x252b (0x538cab in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #19: PyEval_EvalCodeEx + 0x13b (0x540b0b in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #20: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x4ec2e3]
frame #21: PyObject_Call + 0x47 (0x5c20e7 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #22: PyEval_CallObjectWithKeywords + 0x30 (0x534870 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #23: <unknown function> + 0x2fd294 (0x7feb30e7a294 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #24: torch::jit::BlockToONNX(torch::jit::Block*, torch::jit::Block*, torch::onnx::OperatorExportTypes, std::unordered_map<torch::jit::Value*, torch::jit::Value*, std::hash<torch::jit::Value*>, std::equal_to<torch::jit::Value*>, std::allocator<std::pair<torch::jit::Value* const, torch::jit::Value*> > >) + 0x4e9 (0x7feb30ed5a49 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #25: torch::jit::ToONNX(std::shared_ptr<torch::jit::Graph>&, torch::onnx::OperatorExportTypes) + 0x3d6 (0x7feb30ed6bc6 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #26: <unknown function> + 0x3561d9 (0x7feb30ed31d9 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #27: <unknown function> + 0x116fac (0x7feb30c93fac in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #28: PyCFunction_Call + 0x77 (0x4ea137 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #29: PyEval_EvalFrameEx + 0x614 (0x536d94 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #30: PyEval_EvalFrameEx + 0x4b14 (0x53b294 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #31: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x53fc97]
frame #32: PyEval_EvalFrameEx + 0x50bf (0x53b83f in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #33: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x5401ef]
frame #34: PyEval_EvalFrameEx + 0x50bf (0x53b83f in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #35: PyEval_EvalCodeEx + 0x13b (0x540b0b in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #36: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x4ec3f7]
frame #37: PyObject_Call + 0x47 (0x5c20e7 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #38: PyEval_EvalFrameEx + 0x252b (0x538cab in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #39: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x53fc97]
frame #40: PyEval_EvalFrameEx + 0x5513 (0x53bc93 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #41: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x53fc97]
frame #42: PyEval_EvalCode + 0x1f (0x5409bf in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #43: /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python() [0x60cb42]
frame #44: PyRun_FileExFlags + 0x9a (0x60efea in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #45: PyRun_SimpleFileExFlags + 0x1bc (0x60f7dc in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #46: Py_Main + 0x456 (0x640256 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #47: main + 0xe1 (0x4d0001 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)
frame #48: __libc_start_main + 0xf0 (0x7feb4aa12830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #49: _start + 0x29 (0x5d6999 in /home/AD.ADASWORKS.COM/tamas.danyluk/envs/torch/bin/python)

**Comment by soumith** [comment]
cc: @houseroad @zrphercule

**Comment by dusty-nv** [comment]
I also get this crash when a mul, div, or add proceeds Interpolate.  sub works fine.  
I added some debug trace to the symbolic exporter function for upsample operation, this is with a mul before:

```upsample_bilinear2d
   -- output_size=[64, 128]
   -- input_type=Tensor
   -- input=1013 defined in (%1013 : Tensor = onnx::Mul(%1010, %1012)
)
Traceback (most recent call last):
```
The crash occurs when `input.type().sizes()` is called, presumably because it doesn't have that data available unlike in the normal case below.  Below is with no mul/div/add (has tensor dims/type defined, and works as expected)
```upsample_bilinear2d
   -- output_size=[32, 64]
   -- input_type=Tensor
   -- input=940 defined in (%940 : Float(2, 256, 16, 32) = onnx::Elu[alpha=1](%936), scope: Resnet18_md/conv[iconv5]
)
   -- input_size=[2, 256, 16, 32]
```

**Comment by hadeson** [comment]
I got the same error when `weight.type().sizes()` is called: 
```
File "/home/sonct/.virtualenvs/caromap/lib/python3.5/site-packages/torch/onnx/symbolic_opset9.py", line 842, in _convolution
    weight_size = weight.type().sizes()
```
Using Pytorch 1.2.0, CUDA 10, Ubuntu 16.04.

**Comment by zhangguanheng66** [comment]
@hadeson Can you copy/paste your script so we can reproduce the error?
@houseroad @bddppq

**Comment by hadeson** [comment]
I was trying to convert this  [Pytorch implementation](https://github.com/lernapparat/lernapparat/blob/master/style_gan/pytorch_style_gan.ipynb) of StyleGAN. Below is the conversion code:
```
import numpy as np
import torch
import torch.utils.model_zoo as model_zoo
import torch.onnx
from torch import nn
from collections import OrderedDict
from model import G_mapping, G_synthesis, Truncation

def stylegan_G(batch_size=1):
    '''
    convert styleGan generate network (synthesis part only)
    '''
    stylegan_G_onnx_model = "onnx/" + "stylegan_G.onnx"
    weight_path = "./karras2019stylegan-ffhq-1024x1024.for_g_all.pt"
    g_all = nn.Sequential(OrderedDict([
        ('g_mapping', G_mapping()),
        ('g_synthesis', G_synthesis())    
    ]))
    g_all.load_state_dict(torch.load(weight_path))

    device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
    g_all.eval()
    g_all.to(device)
    x = torch.randn(batch_size, 18, 512).cuda()
    torch_out = torch.onnx._export(g_all[1],
                                x,
                                stylegan_G_onnx_model,
                                export_params=True)
    return torch_out, x

stylegan_G()
```
Note that I also had another conversion error with this line in NoiseLayer:
`noise = torch.randn(x.size(0), 1, x.size(2), x.size(3), device=x.device, dtype=x.dtype)`
which I bypassed by replacing with zeros:
`noise = torch.zeros(x.size(0), 1, x.size(2), x.size(3), device=x.device, dtype=x.dtype)`
