### ISSUE TITLE
[bug report] [ONNX] `torch.Size` is not recognized as `Iterable` in onnx-nization

### ISSUE THREAD

**Issue by fiarabbit** [pytorch/pytorch#17153]
## Description
The combination of `torch.randn()` and `torch.Tensor.size()` causes error during `torch.onnx.export()`.
This may be caused by c++ `int[]` is not treated samely to Python `list`.
This phenomenon might be also observed for other ATen method which is converted to ONNX method. (in this case, `randn` is converted to `ONNX::RandomNormal`)

## Code to reproduce
```reproduce.py
import torch


class MyModel(torch.nn.Module):
    def forward(self, x):
        # return torch.randn(3, 3)  # OK
        return torch.randn(*x.size())   # NG


model = MyModel()

dummy_input = torch.randn(3, 3)
torch.onnx.export(model, dummy_input, "mymodel.onnx")
```
```out.py
Traceback (most recent call last):
  File "/tmp/pycharm_project_192/main.py", line 12, in <module>
    torch.onnx.export(model, dummy_input, "mymodel.onnx")
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 227, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 155, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/__init__.py", line 52, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 504, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 1351, in randn
    return g.op('RandomNormal', shape_i=shape)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 452, in _graph_op
    n = g.insertNode(_newNode(g, opname, outputs, *args, **kwargs))
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 405, in _newNode
    _add_attribute(n, k, v, aten=aten)
  File "/home/user/python372/lib/python3.7/site-packages/torch/onnx/utils.py", line 383, in _add_attribute
    return getattr(node, kind + "_")(name, value)
TypeError: i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

Invoked with: %13 : Tensor = onnx::RandomNormal(), scope: MyModel
, 'shape', 9 defined in (%9 : int[] = prim::ListConstruct(%4, %8), scope: MyModel
) (occurred when translating randn)
```
The TypeError itself is a bit strange. `Node.is_()` should be called when the input is a `list` (if the output of `prim::ListConstruct()` constructs `list`), but actually `Node.i_()` is called.

## Expected Behavior
```expected.py
# Nothing to show. mymodel.onnx is successfully generated.
```

## Environment
```env.py
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.0

Versions of relevant libraries:
[pip3] numpy==1.16.0
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.1
[conda] Could not collec
```

**Comment by qmpzzpmq** [comment]
solved by remove random point
