### ISSUE TITLE
Got errors when training a model

### ISSUE THREAD

**Issue by Edwardf0t1** [pytorch/pytorch#17212]
## 🐛 Bug

when training a model, the following error emerged when the training is about to finish:

0 Loss: 1.0828, accuracy: 61.59%
1 Loss: 0.8400, accuracy: 70.28%
2 Loss: 0.7920, accuracy: 73.09%
3 Loss: 0.6798, accuracy: 77.37%
4 Loss: 0.6331, accuracy: 78.00%
5 Loss: 0.6493, accuracy: 78.30%
```
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 500, in run_mod_and_filter_tensor_outputs
    outs = wrap_retval(mod(*_clone_inputs(inputs)))
  File "/home/xx/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xx/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 1347, in forward
    return self._get_method('forward')(*args, **kwargs)
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:137: a PTX JIT compilation failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 140, in <module>
    traced_script_module = torch.jit.trace(model, example)
  File "/home/xx/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 643, in trace
    _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
  File "/home/xx/.local/lib/python3.5/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/xx/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 537, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(module, inputs, 'trace')
  File "/home/xx/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 506, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
	/pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:137: a PTX JIT compilation failed
```
## Environment

The C compiler identification is GNU 5.4.0
The CXX compiler identification is GNU 5.4.0
Ubuntu 16.04
Pytorch 1.0.0
cuda 10.0
cudnn:7.3.1
Python 3.5

**Comment by soumith** [comment]
could you please try our nightly binaries (go to pytorch.org and select the "Preview" instead of "Stable" in the version selector) and see if the issue reproduces?

**Comment by suo** [comment]
Going to close this as we don't have sufficient reproduction information. Feel free to reopen!

**Comment by nicolasCruzW21** [comment]
Hello, 
I have a similar issue. I can load a pth model correctly, but the error emerges when trying to trace the model using jit.

Ubuntu 16.04
Pytorch 1.1
cuda 10.0
cudnn:7.4.2
Python 3.6

I am able to export the model using pytorch 1.0 with cuda 9.0.
The error is:
Traceback (most recent call last):
  File "VisualizeResults.py", line 178, in <module>
    main(args)
  File "VisualizeResults.py", line 145, in main
    evaluateModel(args, modelA, up, image_list)
  File "VisualizeResults.py", line 76, in evaluateModel
    traced_script_module = torch.jit.trace(model, img_variable)
  File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 702, in trace
    _check_trace([example_inputs], func, executor_options, traced, check_tolerance, _force_outplace)
  File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 583, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(module, inputs, 'trace')
  File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 551, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
	Cannot encode RHS of the node, op not supported

**Comment by ZouDongj** [comment]
> Hello,
> I have a similar issue. I can load a pth model correctly, but the error emerges when trying to trace the model using jit.
> 
> Ubuntu 16.04
> Pytorch 1.1
> cuda 10.0
> cudnn:7.4.2
> Python 3.6
> 
> I am able to export the model using pytorch 1.0 with cuda 9.0.
> The error is:
> Traceback (most recent call last):
> File "VisualizeResults.py", line 178, in
> main(args)
> File "VisualizeResults.py", line 145, in main
> evaluateModel(args, modelA, up, image_list)
> File "VisualizeResults.py", line 76, in evaluateModel
> traced_script_module = torch.jit.trace(model, img_variable)
> File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/**init**.py", line 702, in trace
> _check_trace([example_inputs], func, executor_options, traced, check_tolerance, _force_outplace)
> File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
> return func(*args, **kwargs)
> File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/**init**.py", line 583, in _check_trace
> traced_outs = run_mod_and_filter_tensor_outputs(module, inputs, 'trace')
> File "/home/nicolas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/**init**.py", line 551, in run_mod_and_filter_tensor_outputs
> ' with test inputs.\nException:\n' + indent(str(e)))
> torch.jit.TracingCheckError: Tracing failed sanity checks!
> Encountered an exception while running the trace with test inputs.
> Exception:
> Cannot encode RHS of the node, op not supported

Have you solved this problem？
