### ISSUE TITLE
non-cudnn LSTM and GRU biases have wrong shapes

### ISSUE THREAD

**Issue by ShigekiKarita** [pytorch/pytorch#1721]
``` python
import torch
from torch.autograd import Variable


torch.backends.cudnn.enabled = False
in_size = 3
x = Variable(torch.rand(4, 2, in_size))
model = torch.nn.LSTM(in_size, 2, 1)  # GRU is also NG, RNN is OK
model.cuda()
print(model.bias_hh_l0.size())  # 8
y = model(x.cuda())
print(model.bias_hh_l0.size())  # 1x8 (!)
model.cpu()
model(x.cpu())
```

then

```
torch.Size([8])
torch.Size([1, 8])
Traceback (most recent call last):
  File "/home/skarita/work/playground/minasr/egs/lstm_cpu.py", line 14, in <module>
    model(x.cpu())
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 243, in forward
    nexth, output = func(input, hidden, weight)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 83, in forward
    hy, output = inner(input, hidden[l], weight[l])
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 112, in forward
    hidden = inner(input[i], hidden, *weight)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 30, in LSTMCell
    gates = F.linear(input, w_ih, b_ih) + F.linear(hx, w_hh, b_hh)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/functional.py", line 449, in linear
    return state(input, weight) if bias is None else state(input, weight, bias)
  File "/home/skarita/.pyenv/versions/anaconda3-4.3.0/envs/tf/lib/python3.6/site-packages/torch/nn/_functions/linear.py", line 14, in forward
    output.addr_(self.add_buffer, bias)
RuntimeError: vector and vector expected, got 1D, 2D tensors at /py/conda-bld/pytorch_1493679085273/work/torch/lib/TH/generic/THTensorMath.c:1350

Process finished with exit code 1
```

when there's no forward in cuda, it's ok.

**Comment by ShigekiKarita** [comment]
I think we should revert this unsqueeze
https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/thnn/rnnFusedPointwise.py#L14

**Comment by csarofeen** [comment]
Fix now included in https://github.com/pytorch/pytorch/pull/1683

**Comment by soumith** [comment]
fixed on master
