### ISSUE TITLE
Failed to build target caffe2_gpu

### ISSUE THREAD

**Issue by fiery1992** [pytorch/pytorch#17228]
I use the command like ReadMe:
python setup.py install
but it stock in Built target caffe2_gpu
below is the partial logs that I think maybe useful for you check.

```
-- ******** Summary ********
-- General:
--   CMake version         : 3.12.2
--   CMake command         : /cygdrive/u/zqfang/anaconda3/envs/tc27/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 5.4.0
--   BLAS                  : MKL
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;USE_GCC_ATOMICS=1;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /cygdrive/u/zqfang/anaconda3/envs/tc27
--   CMAKE_INSTALL_PREFIX  : /cygdrive/u/zqfang/pytorch/torch
--
--   TORCH_VERSION         : 1.1.0
--   CAFFE2_VERSION        : 1.1.0
--   BUILD_ATEN_MOBILE     : OFF
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : False
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 2.7.15
--     Python executable   : /cygdrive/u/zqfang/anaconda3/envs/tc27/bin/python
--     Pythonlibs version  : 2.7.15
--     Python library      : /cygdrive/u/zqfang/anaconda3/envs/tc27/lib/libpython2.7.so.1.0
--     Python includes     : /cygdrive/u/zqfang/anaconda3/envs/tc27/include/python2.7
--     Python site-packages: lib/python2.7/site-packages
--   BUILD_CAFFE2_OPS      : True
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   USE_ASAN              : OFF
--   USE_CUDA              : True
--     CUDA static link    : False
--     USE_CUDNN           : ON
--     CUDA version        : 8.0
--     cuDNN version       : 7.1.3
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so.7
--     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : False
--   USE_EIGEN_FOR_BLAS    :
--   USE_FBGEMM            : ON
--   USE_FFMPEG            : False
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : False
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : False
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : True
--   USE_NNPACK            : True
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : False
--   USE_OPENMP            : ON
--   USE_PROF              : OFF
--   USE_QNNPACK           : True
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : True
--     USE_MPI             : ON
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fbgemm;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;aten_op_header_gen;onnxifi_loader;rt;gcc_s;gcc;dl
-- Configuring done
CMake Warning (dev) at cmake/Dependencies.cmake:894 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

[ 73%] Building CXX object caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/manager.cpp.o
[ 73%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_batch_matmul_op.cu.o
[ 73%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_batch_moments_op.cu.o
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:31:17: error: ‘ncclInt8’ was not declared in this scope
     {at::kChar, ncclInt8},
                 ^
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:32:17: error: ‘ncclUint8’ was not declared in this scope
     {at::kByte, ncclUint8},
                 ^
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:35:16: error: ‘ncclInt32’ was not declared in this scope
     {at::kInt, ncclInt32},
                ^
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:38:1: error: could not convert ‘{{c10::kChar, <expression error>}, {c10::kByte, <expression error>}, {c10::kFloat, ncclFloat}, {c10::kDouble, ncclDouble}, {c10::kInt, <expression error>}, {c10::kLong, ncclInt64}, {c10::kHalf, ncclHalf}}’ from ‘<brace-enclosed initializer list>’ to ‘std::unordered_map<c10::ScalarType, ncclDataType_t>’
 };
 ^
[ 73%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_boolean_mask_ops.cu.o
In file included from /cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:1:0:
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘void thd::DataChannelNccl::_destroyNcclResources(THDGroup)’:
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:187:40: error: void value not ignored as it ought to be
         NCCL_CHECK(ncclCommDestroy(comm));
                                        ^
/cygdrive/u/zqfang/pytorch/torch/lib/THD/../THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
[ 81%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/rnn/recurrent_network_blob_fetcher_op_gpu.cc.o
[ 81%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/rnn/recurrent_network_executor_gpu.cc.o
[ 81%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/queue/queue_ops_gpu.cc.o
[ 81%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/iter_op_gpu.cc.o
[ 81%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/learning_rate_op_gpu.cc.o
[ 81%] Linking CXX shared library ../lib/libcaffe2_gpu.so
[ 86%] Built target caffe2_gpu
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 281, in build_deps
    build_dir='build')
  File "/cygdrive/u/zqfang/pytorch/tools/build_pytorch_libs.py", line 251, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/cygdrive/u/zqfang/anaconda3/envs/tc27/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '32', 'install']' returned non-zero exit status 2
```

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 2.7
Is CUDA available: N/A
CUDA runtime version: 8.0.44
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.25
cuDNN version: /usr/local/cuda-8.0/lib64/libcudnn.so.7.1.3

Versions of relevant libraries:
[pip] numpy==1.15.4
[conda] blas                      1.0                         mkl
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] mkl_fft                   1.0.10           py27ha843d7b_0
[conda] mkl_random                1.0.2            py27hd81dba3_0

**Comment by soumith** [comment]
please give full logs

**Comment by 2name** [comment]
@fiery1992 
Have you sovled it? I meet the same error.
I'm looking forward to your reply.

**Comment by ezyang** [comment]
Given the error, the most likely explanation is that you have an improper version of nccl:

```
/cygdrive/u/zqfang/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:187:40: error: void value not ignored as it ought to be
         NCCL_CHECK(ncclCommDestroy(comm));
```

Try seeing if your submodules are out of date, or if you have an out of date system install of nccl.
