### ISSUE TITLE
Structseq returned by hooks registered at nn.Module.register_backward_hook are not handled correctly on Python 2

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#17246]
## 🐛 Bug

Subissue of https://github.com/pytorch/pytorch/issues/16813

The following code works on python3 but not on python2:

```python
import torch

class F(torch.autograd.Function):

    @staticmethod
    def forward(ctx, x, y, z):
        return x

    @staticmethod
    def backward(ctx, x):
        return x, x, x

op = F.apply


class M(torch.nn.Module):

    def forward(self, x, y, z):
        return op(x, y, z)

m = M()

def hook(m, i, o):
    return i[0].svd()

m.register_backward_hook(hook)
a = torch.randn(5, 5, requires_grad=True)
b = torch.randn(5, requires_grad=True)
c = torch.randn(5, 5, requires_grad=True)
m(a, b, c).sum().backward()
```

Error message on python2 is

```
Traceback (most recent call last):
  File "geqrf_out.py", line 30, in <module>
    m(a, b, c).sum().backward()
  File "/usr/lib/python2.7/site-packages/torch/tensor.py", line 106, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/lib/python2.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
TypeError: expected tuple, but hook returned 'torch.return_types.svd'
```

## To fix

Change the tuple check inside `check_result` at `torch/csrc/autograd/python_hook.cpp`.

But I don't think if it worth any time to fix it right now since there might be redesign of `register_backward_hook`: https://github.com/pytorch/pytorch/issues/598 https://github.com/pytorch/pytorch/issues/12331

**Comment by zasdfgbnm** [comment]
python 2 support is ending soon, don't worth the time to fix.
