### ISSUE TITLE
CUDA softmax double backward w/ half is broken

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#17261]
## 🐛 Bug

```py
>>>
>>> import torch
>>> import torch.nn.functional as F
>>>
>>> x = torch.randn(3, 10, device='cuda', dtype=torch.half, requires_grad=True)
>>> y = F.softmax(x, dim=1, dtype=torch.float)
>>> y.sum().backward(create_graph=True)
>>> x.grad.sum().backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssnl/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 106, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ssnl/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: expected type torch.cuda.FloatTensor but got torch.cuda.HalfTensor

```

**Comment by vishwakftw** [comment]
I believe this has been fixed in https://github.com/pytorch/pytorch/commit/5fa78303edcfcc841c30ef27462f80904b3c79a2.
