### ISSUE TITLE
Multiprocessing's spawn says "Only Tensors of floating point dtype can require gradients" while it isn't

### ISSUE THREAD

**Issue by phizaz** [pytorch/pytorch#17345]
## 🐛 Bug

I have a module with an `int64` parameter. This parameter does not require gradient. 
However, during the use of `multiprocessing.spawn` it says that my parameter DOES require gradient.
This is incorrect.

## To Reproduce

Run the following code: 
```
import torch
import torch.multiprocessing as mp
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.i = nn.Parameter(torch.tensor(0), requires_grad=False)

def run(rank, net):
    print('start run rank:', rank)

if __name__ == "__main__":
    net = Net()
    net.share_memory()
    c = mp.spawn(run, args=[net], nprocs=1, join=False)
    c.join()
```

Results:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ta/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/ta/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/ta/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 82, in rebuild_tensor
    t = torch.nn.parameter.Parameter(t)
  File "/home/ta/anaconda3/lib/python3.6/site-packages/torch/nn/parameter.py", line 26, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point dtype can require gradients
Traceback (most recent call last):
  File "test_multiprocess.py", line 23, in <module>
    c.join()
  File "/home/ta/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, exitcode)
Exception: process 0 terminated with exit code 1
```

You see that the parameter doesn't require gradient. 

## Expected behavior

No error.

## Environment

```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] pytorch-policy==0.1.1
[pip] torch==1.0.1.post2
[pip] torchfile==0.1.0
[pip] torchnet==0.0.4
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] cuda100                   1.0                           0    pytorch
[conda] cuda92                    1.0                           0    pytorch
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py36h90e4bf4_5
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0
[conda] mkl_random                1.0.1            py36h4414c95_1
[conda] pytorch                   1.0.1           py3.6_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] pytorch-policy            0.1.1                     dev_0    <develop>
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi
```

**Comment by colesbury** [comment]
Bug is here:

https://github.com/pytorch/pytorch/blob/3145f46a2287619e79add11a8d543729b2590a14/torch/multiprocessing/reductions.py#L83-L84

nn.Parameter() needs `requires_grad=False` in constructor in this case

**Comment by soumith** [comment]
@colesbury the line right after, i.e. line 84 sets the requires_grad correctly, no?

**Comment by colesbury** [comment]
@soumith yes

**Comment by phizaz** [comment]
In the meanwhile, could I send the `state_dict` instead? What should be the right way to do it. I presume:

```
net = Net()
net.share_memory()
state_dict = copy.deepcopy(net.state_dict())
c = mp.spawn(run, args=[state_dict], nprocs=1, join=False)
...
# later times
state_dict.update(copy.deepcopy(net.state_dict()))
...
# in run(state_dict):
local_net.load_state_dict(state_dict)
```

I am concerned about the consistency of `state_dict` while it is being updated.
