### ISSUE TITLE
CuDNN detected while compile; returns false on compiledWithCuDNN() check

### ISSUE THREAD

**Issue by neiladit** [pytorch/pytorch#17426]
I'm building PyTorch from source using:
```
CUDNN_INCLUDE_DIR=~/cuda/include CUDNN_LIBRARY=~/cuda/lib64 python setup.py install
```
The compilation log gives this message indicating CuDNN was found and compiled with

```
Building with NumPy bindings
-- Detected cuDNN at /home/<user>/cuda/lib64, /home/<user>/cuda/include
-- Not using MIOpen
-- Detected CUDA at /usr/local/cuda
-- Using MKLDNN
-- Building NCCL library
-- Building with THD distributed package
-- Building with c10d distributed package
```

When I run a convolution layer, it does not call "cudnn_convolution" kernel, instead it calls the "thnn_conv2d" kernel. On inspecting the "use_cudnn" variable I realize -
```
use_cudnn is false due to this variable - detail::getCUDAHooks().compiledWithCuDNN()
```

Since, I compiled with cuDNN, I am not sure why the above variable is not true.

@soumith  Any suggestions? Thanks.

**Comment by soumith** [comment]
can you please give the full build log.

**Comment by neiladit** [comment]
```
[  0%] Built target nccl_external
[  0%] Built target onnxifi_loader
[  0%] Built target onnxifi_dummy
[  0%] Built target mkdisp
[  0%] Built target pthreadpool
[  0%] Built target clog
[  0%] Built target mkalias
[  0%] Built target mkrename
[  0%] Built target common
[  0%] Built target gtest
[  0%] Built target arraymap
[  0%] Built target mkrename_gnuabi
[  0%] Built target ATEN_CUDA_FILES_GEN_TARGET
[  1%] Built target benchmark
[  1%] Built target ATEN_CPU_FILES_GEN_TARGET
[  1%] Built target mkmasked_gnuabi
[  3%] Built target c10
[  4%] Built target gloo
[  5%] Built target libprotobuf-lite
[  5%] Built target onnxifi_wrapper
[  5%] Built target dispsse.c_generated
[  5%] Built target dispavx.c_generated
[  5%] Built target renamedsp256.h_generated
[  5%] Built target renameAVX.h_generated
[  5%] Built target headers
[  5%] Built target renameAVX2.h_generated
[  5%] Built target renameSSE4.h_generated
[  5%] Built target renameFMA4.h_generated
[  5%] Built target nnpack_reference_layers
[  5%] Built target renamedsp128.h_generated
[  5%] Built target renameAVX2128.h_generated
[  5%] Built target __aten_op_header_gen
[  5%] Built target cpuinfo
[  5%] Built target renameSSE2.h_generated
[  5%] Built target benchmark_main
[  5%] Built target gtest_main
[  5%] Built target torch_python_stubs
[  6%] Built target cpuinfo_internals
[  7%] Built target c10_cuda
[ 26%] Built target dispavx_obj
[ 27%] Built target python_copy_files
[ 27%] Built target sleefavx2
[ 27%] Built target sleeffma4
[ 27%] Built target sleefavx
[ 27%] Built target dispsse_obj
[ 29%] Built target libprotobuf
[ 29%] Built target sleefsse4
[ 29%] Built target c10_InlineDeviceGuard_test
[ 29%] Built target sleefavx2128
[ 30%] Built target c10_StreamGuard_test
[ 30%] Built target c10_registry_test
[ 31%] Built target c10_Half_test
[ 31%] Built target sleefsse2
[ 34%] Built target c10_LeftRight_test
[ 34%] Built target c10_TensorTypeId_test
[ 34%] Built target mkldnn
[ 34%] Built target nnpack
[ 34%] Built target c10_Array_test
[ 34%] Built target c10_DeviceGuard_test
[ 34%] Built target c10_typeid_test
[ 34%] Built target c10_InlineStreamGuard_test
[ 34%] Built target c10_Metaprogramming_test
[ 34%] Built target c10_flags_test
[ 34%] Built target c10_intrusive_ptr_test
[ 34%] Built target c10_TypeList_test
[ 34%] Built target c10_TypeTraits_test
[ 34%] Built target c10_cuda_CUDATest
[ 34%] Built target c10_logging_test
[ 36%] Built target qnnpack
[ 37%] Built target gloo_cuda
[ 37%] Built target sleef
[ 37%] Built target gloo_builder
[ 40%] Built target libprotoc
[ 41%] Built target protoc
[ 41%] Built target gen_onnx_proto
[ 41%] Built target Caffe2_PROTO
[ 41%] Built target caffe2_protos
[ 42%] Built target onnx_proto
[ 43%] Built target Caffe2_perfkernels_avx2
[ 43%] Built target Caffe2_perfkernels_avx
[ 44%] Built target onnx
[ 67%] Built target caffe2
[ 67%] Built target shm
[ 67%] Built target caffe2_module_test_dynamic
[ 67%] Built target caffe2_observers
[ 68%] Built target caffe2_pybind11_state
[ 68%] Built target torch_shm_manager
[ 69%] Built target THD
[ 83%] Built target caffe2_gpu
[ 83%] Built target cuda_stream_test
[ 83%] Built target device_test
[ 83%] Built target distributed_test
[ 83%] Built target bound_shape_inference_test
[ 83%] Built target TensorImpl_test
[ 83%] Built target blob_gpu_test
[ 84%] Built target init_test
[ 84%] Built target conv_to_nnpack_transform_test
[ 84%] Built target event_gpu_test
[ 84%] Built target tbb_init_test
[ 84%] Built target int8_roi_align_op_test
[ 85%] Built target cuda_rng_test
[ 85%] Built target batch_matmul_op_gpu_test
[ 85%] Built target pattern_net_transform_test
[ 85%] Built target depthwise3x3_conv_op_test
[ 85%] Built target dead_code_elim_test
[ 85%] Built target net_gpu_test
[ 85%] Built target utility_ops_gpu_test
[ 85%] Built target nnpack_test
[ 85%] Built target reshape_op_gpu_test
[ 85%] Built target extension_backend_test
[ 85%] Built target converter_nomigraph_test
[ 86%] Built target event_test
[ 86%] Built target common_subexpression_elimination_test
[ 86%] Built target graph_test
[ 86%] Built target cuda_optional_test
[ 86%] Built target elementwise_op_gpu_test
[ 86%] Built target generate_proposals_op_gpu_test
[ 86%] Built target cuda_integer_divider_test
[ 86%] Built target roi_align_op_gpu_test
[ 86%] Built target generate_proposals_op_util_boxes_test
[ 86%] Built target generate_proposals_op_util_nms_gpu_test
[ 86%] Built target verify_api_visibility
[ 87%] Built target net_dag_utils_test
[ 87%] Built target timer_test
[ 87%] Built target tensor_interop_test
[ 87%] Built target native_test
[ 87%] Built target GraphTest
[ 87%] Built target operator_test
[ 87%] Built target wrapdim_test
[ 87%] Built target broadcast_test
[ 87%] Built target half_test
[ 87%] Built target scalar_tensor_test
[ 87%] Built target net_test
[ 88%] Built target xla_tensor_test
[ 88%] Built target cast_test
[ 88%] Built target observer_test
[ 88%] Built target weakref_test
[ 88%] Built target cuda_apply_test
[ 88%] Built target dlconvertor_test
[ 88%] Built target cuda_packedtensoraccessor_test
[ 88%] Built target apply_utils_test
[ 88%] Built target operator_schema_test
[ 88%] Built target text_file_reader_utils_test
[ 88%] Built target backend_cutting_test
[ 89%] Built target string_ops_test
[ 89%] Built target TarjansImplTest
[ 89%] Built target inline_container_test
[ 89%] Built target scalar_test
[ 89%] Built target math_gpu_test
[ 89%] Built target context_gpu_test
[ 89%] Built target test_parallel
[ 90%] Built target int8_test
[ 90%] Built target operator_fallback_gpu_test
[ 90%] Built target context_test
[ 90%] Built target common_test
[ 90%] Built target operator_gpu_test
[ 90%] Built target atest
[ 90%] Built target basic
[ 90%] Built target TopoSortTest
[ 90%] Built target SubgraphMatcherTest
[ 90%] Built target batch_matmul_op_test
[ 90%] Built target ssa_test
[ 90%] Built target stats_test
[ 90%] Built target net_simple_refcount_test
[ 90%] Built target mobile_test
[ 90%] Built target cpuid_test
[ 90%] Built target parallel_net_test
[ 90%] Built target module_test
[ 90%] Built target net_async_tracing_test
[ 90%] Built target NeuralNetTest
[ 91%] Built target simple_queue_test
[ 91%] Built target undefined_tensor_test
[ 91%] Built target math_test
[ 91%] Built target workspace_test
[ 91%] Built target fatal_signal_asan_no_sig_test
[ 91%] Built target proto_utils_test
[ 91%] Built target fixed_divisor_test
[ 91%] Built target time_observer_test
[ 91%] Built target generate_proposals_op_util_nms_test
[ 91%] Built target smart_tensor_printer_test
[ 91%] Built target transform_test
[ 91%] Built target cuda_tensor_interop_test
[ 91%] Built target caffe2_pybind11_state_gpu
[ 91%] Built target AlgorithmsTest
[ 91%] Built target conv_transpose_op_mobile_test
[ 91%] Built target predictor_test
[ 91%] Built target BinaryMatchImplTest
[ 91%] Built target MatchTest
[ 91%] Built target cuda_half_test
[ 91%] Built target blob_test
[ 91%] Built target utility_ops_test
[ 91%] Built target boolean_unmask_ops_test
[ 91%] Built target c10d
[ 91%] Built target generate_proposals_op_test
[ 91%] Built target elementwise_op_test
[ 91%] Built target FileStoreTest
[ 91%] Built target TCPStoreTest
[ 91%] Built target c10d_cuda_test
[ 91%] Built target ProcessGroupGlooTest
[ 91%] Built target ProcessGroupGlooAsyncTest
[ 91%] Built target ProcessGroupNCCLTest
[ 92%] Built target caffe2_detectron_ops_gpu
[ 96%] Built target torch
[ 97%] Built target test_jit
[ 97%] Built target test_api
[100%] Built target torch_python
Install the project...
-- Install configuration: "Release"
Building wheel torch-1.1.0a0+c65b03b
-- Building version 1.1.0a0+c65b03b
running install
running build
running build_py
copying torch/version.py -> build/lib.linux-x86_64-3.6/torch
copying caffe2/proto/caffe2_legacy_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/predictor_consts_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/hsm_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/prof_dag_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/metanet_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/torch_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/caffe2_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
running build_ext
-- Building with NumPy bindings
-- Detected cuDNN at /home/na469/cuda/lib64, /home/na469/cuda/include
-- Not using MIOpen
-- Detected CUDA at /usr/local/cuda
-- Using MKLDNN
-- Building NCCL library
-- Building with THD distributed package 
-- Building with c10d distributed package 

Copying extension caffe2.python.caffe2_pybind11_state
Copying caffe2.python.caffe2_pybind11_state from torch/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so to /home/na469/pytorch/build/lib.linux-x86_64-3.6/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so

Copying extension caffe2.python.caffe2_pybind11_state_gpu
Copying caffe2.python.caffe2_pybind11_state_gpu from torch/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so to /home/na469/pytorch/build/lib.linux-x86_64-3.6/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so
running install_lib
copying build/lib.linux-x86_64-3.6/caffe2/proto/caffe2_legacy_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/predictor_consts_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/hsm_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/prof_dag_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/metanet_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/torch_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/caffe2_pb2.py -> /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/torch/version.py -> /home/na469/anaconda3/lib/python3.6/site-packages/torch
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/caffe2_legacy_pb2.py to caffe2_legacy_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/predictor_consts_pb2.py to predictor_consts_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/hsm_pb2.py to hsm_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/prof_dag_pb2.py to prof_dag_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/metanet_pb2.py to metanet_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/torch_pb2.py to torch_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/caffe2/proto/caffe2_pb2.py to caffe2_pb2.cpython-36.pyc
byte-compiling /home/na469/anaconda3/lib/python3.6/site-packages/torch/version.py to version.cpython-36.pyc
running install_egg_info
running egg_info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing entry points to torch.egg-info/entry_points.txt
writing top-level names to torch.egg-info/top_level.txt
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
removing '/home/na469/anaconda3/lib/python3.6/site-packages/torch-1.1.0a0+c65b03b-py3.6.egg-info' (and everything under it)
Copying torch.egg-info to /home/na469/anaconda3/lib/python3.6/site-packages/torch-1.1.0a0+c65b03b-py3.6.egg-info
running install_scripts
Installing convert-caffe2-to-onnx script to /home/na469/anaconda3/bin
Installing convert-onnx-to-caffe2 script to /home/na469/anaconda3/bin

```

**Comment by neiladit** [comment]
```
 [  0%] Built target nccl_external
[  0%] Built target onnxifi_loader
[  0%] Built target onnxifi_dummy
[  0%] Built target mkdisp
[  0%] Built target pthreadpool
[  0%] Built target clog
[  0%] Built target mkalias
[  0%] Built target mkrename
[  0%] Built target common
[  0%] Built target gtest
[  0%] Built target arraymap
[  0%] Built target mkrename_gnuabi
[  0%] Built target ATEN_CUDA_FILES_GEN_TARGET
[  1%] Built target benchmark
[  1%] Built target ATEN_CPU_FILES_GEN_TARGET
[  1%] Built target mkmasked_gnuabi
[  3%] Built target c10
[  4%] Built target gloo
[  5%] Built target libprotobuf-lite
[  5%] Built target onnxifi_wrapper
[  5%] Built target dispsse.c_generated
[  5%] Built target dispavx.c_generated
[  5%] Built target renamedsp256.h_generated
[  5%] Built target renameAVX.h_generated
[  5%] Built target headers
[  5%] Built target renameAVX2.h_generated
[  5%] Built target renameSSE4.h_generated
[  5%] Built target renameFMA4.h_generated
[  5%] Built target nnpack_reference_layers
[  5%] Built target renamedsp128.h_generated
[  5%] Built target renameAVX2128.h_generated
[  5%] Built target __aten_op_header_gen
[  5%] Built target cpuinfo
[  5%] Built target renameSSE2.h_generated
[  5%] Built target benchmark_main
[  5%] Built target gtest_main
[  5%] Built target torch_python_stubs
[  6%] Built target cpuinfo_internals
[  7%] Built target c10_cuda
[ 26%] Built target dispavx_obj
[ 27%] Built target python_copy_files
[ 27%] Built target sleefavx2
[ 27%] Built target sleeffma4
[ 27%] Built target sleefavx
[ 27%] Built target dispsse_obj
[ 29%] Built target libprotobuf
[ 29%] Built target sleefsse4
[ 29%] Built target c10_InlineDeviceGuard_test
[ 29%] Built target sleefavx2128
[ 30%] Built target c10_StreamGuard_test
[ 30%] Built target c10_registry_test
[ 31%] Built target c10_Half_test
[ 31%] Built target sleefsse2
[ 34%] Built target c10_LeftRight_test
[ 34%] Built target c10_TensorTypeId_test
[ 34%] Built target mkldnn
[ 34%] Built target nnpack
[ 34%] Built target c10_Array_test
[ 34%] Built target c10_DeviceGuard_test
[ 34%] Built target c10_typeid_test
[ 34%] Built target c10_InlineStreamGuard_test
[ 34%] Built target c10_Metaprogramming_test
[ 34%] Built target c10_flags_test
[ 34%] Built target c10_intrusive_ptr_test
[ 34%] Built target c10_TypeList_test
[ 34%] Built target c10_TypeTraits_test
[ 34%] Built target c10_cuda_CUDATest
[ 34%] Built target c10_logging_test
[ 36%] Built target qnnpack
[ 37%] Built target gloo_cuda
[ 37%] Built target sleef
[ 37%] Built target gloo_builder
[ 40%] Built target libprotoc
[ 41%] Built target protoc
[ 41%] Built target gen_onnx_proto
[ 41%] Built target Caffe2_PROTO
[ 41%] Built target caffe2_protos
[ 42%] Built target onnx_proto
[ 43%] Built target Caffe2_perfkernels_avx2
[ 43%] Built target Caffe2_perfkernels_avx
[ 44%] Built target onnx
[ 67%] Built target caffe2
[ 67%] Built target shm
[ 67%] Built target caffe2_module_test_dynamic
[ 67%] Built target caffe2_observers
[ 68%] Built target caffe2_pybind11_state
[ 68%] Built target torch_shm_manager
[ 69%] Built target THD
[ 83%] Built target caffe2_gpu
[ 83%] Built target cuda_stream_test
[ 83%] Built target device_test
[ 83%] Built target distributed_test
[ 83%] Built target bound_shape_inference_test
[ 83%] Built target TensorImpl_test
[ 83%] Built target blob_gpu_test
[ 84%] Built target init_test
[ 84%] Built target conv_to_nnpack_transform_test
[ 84%] Built target event_gpu_test
[ 84%] Built target tbb_init_test
[ 84%] Built target int8_roi_align_op_test
[ 85%] Built target cuda_rng_test
[ 85%] Built target batch_matmul_op_gpu_test
[ 85%] Built target pattern_net_transform_test
[ 85%] Built target depthwise3x3_conv_op_test
[ 85%] Built target dead_code_elim_test
[ 85%] Built target net_gpu_test
[ 85%] Built target utility_ops_gpu_test
[ 85%] Built target nnpack_test
[ 85%] Built target reshape_op_gpu_test
[ 85%] Built target extension_backend_test
[ 85%] Built target converter_nomigraph_test
[ 86%] Built target event_test
[ 86%] Built target common_subexpression_elimination_test
[ 86%] Built target graph_test
[ 86%] Built target cuda_optional_test
[ 86%] Built target elementwise_op_gpu_test
[ 86%] Built target generate_proposals_op_gpu_test
[ 86%] Built target cuda_integer_divider_test
[ 86%] Built target roi_align_op_gpu_test
[ 86%] Built target generate_proposals_op_util_boxes_test
[ 86%] Built target generate_proposals_op_util_nms_gpu_test
[ 86%] Built target verify_api_visibility
[ 87%] Built target net_dag_utils_test
[ 87%] Built target timer_test
[ 87%] Built target tensor_interop_test
[ 87%] Built target native_test
[ 87%] Built target GraphTest
[ 87%] Built target operator_test
[ 87%] Built target wrapdim_test
[ 87%] Built target broadcast_test
[ 87%] Built target half_test
[ 87%] Built target scalar_tensor_test
[ 87%] Built target net_test
[ 88%] Built target xla_tensor_test
[ 88%] Built target cast_test
[ 88%] Built target observer_test
[ 88%] Built target weakref_test
[ 88%] Built target cuda_apply_test
[ 88%] Built target dlconvertor_test
[ 88%] Built target cuda_packedtensoraccessor_test
[ 88%] Built target apply_utils_test
[ 88%] Built target operator_schema_test
[ 88%] Built target text_file_reader_utils_test
[ 88%] Built target backend_cutting_test
[ 89%] Built target string_ops_test
[ 89%] Built target TarjansImplTest
[ 89%] Built target inline_container_test
[ 89%] Built target scalar_test
[ 89%] Built target math_gpu_test
[ 89%] Built target context_gpu_test
[ 89%] Built target test_parallel
[ 90%] Built target int8_test
[ 90%] Built target operator_fallback_gpu_test
[ 90%] Built target context_test
[ 90%] Built target common_test
[ 90%] Built target operator_gpu_test
[ 90%] Built target atest
[ 90%] Built target basic
[ 90%] Built target TopoSortTest
[ 90%] Built target SubgraphMatcherTest
[ 90%] Built target batch_matmul_op_test
[ 90%] Built target ssa_test
[ 90%] Built target stats_test
[ 90%] Built target net_simple_refcount_test
[ 90%] Built target mobile_test
[ 90%] Built target cpuid_test
[ 90%] Built target parallel_net_test
[ 90%] Built target module_test
[ 90%] Built target net_async_tracing_test
[ 90%] Built target NeuralNetTest
[ 91%] Built target simple_queue_test
[ 91%] Built target undefined_tensor_test
[ 91%] Built target math_test
[ 91%] Built target workspace_test
[ 91%] Built target fatal_signal_asan_no_sig_test
[ 91%] Built target proto_utils_test
[ 91%] Built target fixed_divisor_test
[ 91%] Built target time_observer_test
[ 91%] Built target generate_proposals_op_util_nms_test
[ 91%] Built target smart_tensor_printer_test
[ 91%] Built target transform_test
[ 91%] Built target cuda_tensor_interop_test
[ 91%] Built target caffe2_pybind11_state_gpu
[ 91%] Built target AlgorithmsTest
[ 91%] Built target conv_transpose_op_mobile_test
[ 91%] Built target predictor_test
[ 91%] Built target BinaryMatchImplTest
[ 91%] Built target MatchTest
[ 91%] Built target cuda_half_test
[ 91%] Built target blob_test
[ 91%] Built target utility_ops_test
[ 91%] Built target boolean_unmask_ops_test
[ 91%] Built target c10d
[ 91%] Built target generate_proposals_op_test
[ 91%] Built target elementwise_op_test
[ 91%] Built target FileStoreTest
[ 91%] Built target TCPStoreTest
[ 91%] Built target c10d_cuda_test
[ 91%] Built target ProcessGroupGlooTest
[ 91%] Built target ProcessGroupGlooAsyncTest
[ 91%] Built target ProcessGroupNCCLTest
[ 92%] Built target caffe2_detectron_ops_gpu
[ 96%] Built target torch
[ 97%] Built target test_jit
[ 97%] Built target test_api
[100%] Built target torch_python
Install the project...
-- Install configuration: "Release"
Building wheel torch-1.1.0a0+c65b03b
-- Building version 1.1.0a0+c65b03b
running install
running build
running build_py
copying torch/version.py -> build/lib.linux-x86_64-3.6/torch
copying caffe2/proto/caffe2_legacy_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/predictor_consts_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/hsm_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/prof_dag_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/metanet_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/torch_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/caffe2_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
running build_ext
-- Building with NumPy bindings
-- Detected cuDNN at /home/<user>/cuda/lib64, /home/<user>/cuda/include
-- Not using MIOpen
-- Detected CUDA at /usr/local/cuda
-- Using MKLDNN
-- Building NCCL library
-- Building with THD distributed package
-- Building with c10d distributed package

Copying extension caffe2.python.caffe2_pybind11_state
Copying caffe2.python.caffe2_pybind11_state from torch/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so to /home/<user>/pytorch/build/lib.linux-x86_64-3.6/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so

Copying extension caffe2.python.caffe2_pybind11_state_gpu
Copying caffe2.python.caffe2_pybind11_state_gpu from torch/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so to /home/<user>/pytorch/build/lib.linux-x86_64-3.6/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so
running install_lib
copying build/lib.linux-x86_64-3.6/caffe2/proto/caffe2_legacy_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/predictor_consts_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/hsm_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/prof_dag_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/metanet_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/torch_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/caffe2_pb2.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/torch/version.py -> /home/<user>/anaconda3/lib/python3.6/site-packages/torch
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/caffe2_legacy_pb2.py to caffe2_legacy_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/predictor_consts_pb2.py to predictor_consts_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/hsm_pb2.py to hsm_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/prof_dag_pb2.py to prof_dag_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/metanet_pb2.py to metanet_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/torch_pb2.py to torch_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/caffe2/proto/caffe2_pb2.py to caffe2_pb2.cpython-36.pyc
byte-compiling /home/<user>/anaconda3/lib/python3.6/site-packages/torch/version.py to version.cpython-36.pyc
running install_egg_info
running egg_info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing entry points to torch.egg-info/entry_points.txt
writing top-level names to torch.egg-info/top_level.txt
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
removing '/home/<user>/anaconda3/lib/python3.6/site-packages/torch-1.1.0a0+c65b03b-py3.6.egg-info' (and everything under it)
Copying torch.egg-info to /home/<user>/anaconda3/lib/python3.6/site-packages/torch-1.1.0a0+c65b03b-py3.6.egg-info
running install_scripts
Installing convert-caffe2-to-onnx script to /home/<user>/anaconda3/bin
Installing convert-onnx-to-caffe2 script to /home/<user>/anaconda3/bin

```

**Comment by soumith** [comment]
this log is not complete, as it's the log of a second invocation.

First run `git clean -xfd` to clean all build files, and then run

```
CUDNN_INCLUDE_DIR=~/cuda/include CUDNN_LIBRARY=~/cuda/lib64 python setup.py install
```

Then paste that full log.

thanks.

**Comment by neiladit** [comment]
Thanks for pointing that out. When I build using `CUDNN_INCLUDE_DIR=~/cuda/include CUDNN_LIBRARY=~/cuda/lib64 python setup.py install` after the running the clean command I get this error:

```
[ 83%] Linking CXX shared library ../lib/libcaffe2_gpu.so
/home/<user>/cuda/lib64: file not recognized: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe2_gpu.so] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2   
Traceback (most recent call last):
  File "setup.py", line 720, in <module>
    build_deps()
  File "setup.py", line 279, in build_deps
    build_dir='build')
  File "/home/<user>/pytorch/tools/build_pytorch_libs.py", line 248, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/home/<user>/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '32', 'install']' returned non-zero exit status 2.
```

Am I not including the cud files properly?

**Comment by soumith** [comment]
CUDNN_LIBRARY should be the full path to `libcudnn.so`, not just the directory.

**Comment by neiladit** [comment]
@soumith Thanks for the help. CuDNN works now. The build command I used was:

`CUDNN_INCLUDE_DIR=~/cuda/include CUDNN_LIBRARY=~/cuda/lib64/libcudnn.so python setup.py install`
