### ISSUE TITLE
RuntimeError: cur_offset == offset ASSERT FAILED at ..\aten\src\ATen\native\cudnn\RNN.cpp:471, please report a bug to PyTorch. cur_offset = 36864; offset = 18432

### ISSUE THREAD

**Issue by romth777** [pytorch/pytorch#17438]
## To Reproduce

1. Calculate loss with criterion (NllLoss).
1. Call loss.backward().
1. Assert in the title occurs.

## Expected behavior
Calculate loss, with no clash.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.6.5
 - CUDA/cuDNN version: 9.0, V9.0.176
 - GPU models and configuration: Nvidia GeForce GTX 960
 - Any other relevant information: -

## Additional context
Also in the same code with: 
 - PyTorch Version (e.g., 1.0): 0.4.1
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.6.5
 - CUDA/cuDNN version: 9.2, V9.2.148
 - GPU models and configuration: Nvidia Titan X

Here is the message: 
Traceback (most recent call last):
  File "Train.py", line 415, in <module>
    trials=trials)
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "Train.py", line 386, in objective
    loss = train(**args)
  File "Train.py", line 242, in train
    loss.backward()
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/user/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CuDNN error: CUDNN_STATUS_BAD_PARAM

**Comment by romth777** [comment]
My issue is my bug and because of not to modify the pretrained embedding weight data type float32 (=.float()) with float64 (=.double()).
If anyone who checks my issue is there, thanks for cooperating.

**Comment by TianHaiFinger** [comment]
Hi, I have the same problem as you. Could you please describe your solution to this problem?
Thanks!

**Comment by romth777** [comment]
Hi, you should check if the data type is suitable; in my case, the embedding weight needs float64 type, then I fix it.
Cheers,

**Comment by TianHaiFinger** [comment]
Ok, I'll try. Thank you
