### ISSUE TITLE
RuntimeError: PyTorch was compiled without NumPy support

### ISSUE THREAD

**Issue by li0128** [pytorch/pytorch#17431]
python3 train.py 
RUNDIR: runs/fcn8s_pascal/3435
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train(cfg, writer, logger)
  File "train.py", line 77, in train
    model = get_model(cfg["model"], n_classes).to(device)
  File "/home/lxc/PythonProjects/pytorch-semseg-master/ptsemseg/models/__init__.py", line 23, in get_model
    model = model(n_classes=n_classes, **param_dict)
  File "/home/lxc/PythonProjects/pytorch-semseg-master/ptsemseg/models/fcn.py", line 321, in __init__
    get_upsampling_weight(m.in_channels, m.out_channels, m.kernel_size[0])
  File "/home/lxc/PythonProjects/pytorch-semseg-master/ptsemseg/models/utils.py", line 814, in get_upsampling_weight
    return torch.from_numpy(weight).float()
RuntimeError: PyTorch was compiled without NumPy support

**Comment by soumith** [comment]
use the issue template.
