### ISSUE TITLE
Windows CPU debug build fails at linking stage

### ISSUE THREAD

**Issue by slaweks17** [pytorch/pytorch#17489]
## 🐛 Bug
Hi, 
I can't build Windows Debug CPU version, the build fails during linking. 
I am using the latest source code. At the end of post there are exact commands I execute.
I am really after Libtorch build, I do not care about Python, but because I do not understand the whole thing, I feel obliged to build all.

Thank you,
Slawek

1. First of all an observation, CMakeLists.txt contains this:
set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -O0")
set (CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_STATIC_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -O0")
which causes endless warnings of unknown options.

Compilation appears successful  (2000 files or so) but then failures happen during linking
2.  
```Creating library lib\test_api.lib and object lib\test_api.exp
dataloader.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl torch::data::samplers::DistributedSampler<class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > >::set_epoch(unsigned __int64)" (__imp_?set_epoch@?$DistributedSampler@V?$vector@_KV?$allocator@_K@std@@@std@@@samplers@data@torch@@QEAAX_K@Z) referenced in function "private: virtual void __cdecl DataTest_CanSaveAndLoadDistributedRandomSampler_Test::TestBody(void)" (?TestBody@DataTest_CanSaveAndLoadDistributedRandomSampler_Test@@EEAAXXZ)
dataloader.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl torch::data::samplers::DistributedSampler<class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > >::epoch(void)const " (__imp_?epoch@?$DistributedSampler@V?$vector@_KV?$allocator@_K@std@@@std@@@samplers@data@torch@@QEBA_KXZ) referenced in function "private: virtual void __cdecl DataTest_CanSaveAndLoadDistributedRandomSampler_Test::TestBody(void)" (?TestBody@DataTest_CanSaveAndLoadDistributedRandomSampler_Test@@EEAAXXZ)
bin\test_api.exe : fatal error LNK1120: 2 unresolved externals
[2/3] Linking CXX shared library bin\torch_python.dll
FAILED: bin/torch_python.dll lib/torch_python.lib
```
3. And then, another failure
```LINK: command "C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1411~1.255\bin\HostX64\x64\link.exe /nologo caffe2\torch\CMakeFiles\torch_python.dir\csrc\DataLoader.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Device.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Dtype.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\DynamicTypes.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Exceptions.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\TypeInfo.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Generator.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Layout.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Module.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\PtrWrapper.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Size.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\Storage.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\api\src\python\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\functions\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\generated\python_functions.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\generated\python_nn_functions.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\generated\python_torch_functions.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\generated\python_variable_methods.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_anomaly_mode.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_cpp_function.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_engine.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_function.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_hook.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_legacy_variable.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_variable.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\autograd\python_variable_indexing.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\byte_order.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\batched\BatchTensor.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\passes\onnx.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\passes\onnx\fixup_onnx_loop.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\passes\onnx\prepare_division_for_onnx.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\passes\onnx\peephole.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\passes\to_batch.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\python_arg_flatten.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\python_interpreter.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\python_ir.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\python_tracer.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\script\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\script\lexer.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\script\module.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\jit\script\python_tree_views.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\multiprocessing\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\nn\THNN.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\onnx\init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\serialization.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\tensor\python_tensor.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\cuda_lazy_init.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\invalid_arguments.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\object_ptr.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\python_arg_parser.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_apply.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_dtypes.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_flatten.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_layouts.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_list.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_new.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_numpy.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tensor_types.cpp.obj caffe2\torch\CMakeFiles\torch_python.dir\csrc\utils\tuple_parser.cpp.obj /out:bin\torch_python.dll /implib:lib\torch_python.lib /pdb:bin\torch_python.pdb /dll /version:0.0 /debug /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT.LIB /DEBUG:FULL lib\torch.lib lib\shm.lib C:\local\Anaconda3\envs\PytorchDebug\libs\python37.lib lib\onnx.lib lib\onnx_proto.lib -WHOLEARCHIVE:F:/progs2/pytorchDebug/pytorch/build/lib/onnx.lib lib\caffe2.lib lib\libprotobufd.lib C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl\lib\intel64_win\mkl_intel_lp64.lib C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl\lib\intel64_win\mkl_intel_thread.lib C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl\lib\intel64_win\mkl_core.lib C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\compiler\lib\intel64_win\libiomp5md.lib lib\c10.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\torch_python.dll.manifest" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'python37_d.lib'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 709, in <module>
    build_deps()
  File "setup.py", line 281, in build_deps
    build_dir='build')
  File "F:\progs2\pytorchDebug\pytorch\tools\build_pytorch_libs.py", line 243, in build_caffe2
    cwd=build_dir, env=my_env)
  File "c:\local\Anaconda3\envs\PytorchDebug\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Debug', '--', '-j', '11']' returned non-zero exit status 1.
```
Now, I downloaded and copied python37_d.lib into C:\local\Anaconda3\envs\PytorchDebug\libs and python37_d.dll into C:\local\Anaconda3\envs\PytorchDebug, but it does not help.

## Environment
 - PyTorch Version: 1, latest code
 - OS: Windows 10
 - Build commands:
call c:\local\Anaconda3\scripts\activate PytorchDebug
rem Done before: conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
rem Done before, in f:\progs2\PytorchDebug: git clone --recursive https://github.com/pytorch/pytorch
F:
cd progs2\PytorchDebug\pytorch
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
set NO_CUDA=1
set DEBUG=1
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install

 - Python version: 3.7

**Comment by peterjc123** [comment]
If you build for libtorch, then please do this before build.
```cmd
: replace 
python setup.py install
: with
python tools\build_libtorch.py
```

**Comment by slaweks17** [comment]
Thank you. 
Unfortunately (this time after compiling 1319 files) I still fail at the same place:
```
  Creating library lib\test_api.lib and object lib\test_api.exp
dataloader.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl torch::data::samplers::DistributedSampler<class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > >::set_epoch(unsigned __int64)" (__imp_?set_epoch@?$DistributedSampler@V?$vector@_KV?$allocator@_K@std@@@std@@@samplers@data@torch@@QEAAX_K@Z) referenced in function "private: virtual void __cdecl DataTest_CanSaveAndLoadDistributedRandomSampler_Test::TestBody(void)" (?TestBody@DataTest_CanSaveAndLoadDistributedRandomSampler_Test@@EEAAXXZ)
dataloader.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl torch::data::samplers::DistributedSampler<class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > >::epoch(void)const " (__imp_?epoch@?$DistributedSampler@V?$vector@_KV?$allocator@_K@std@@@std@@@samplers@data@torch@@QEBA_KXZ) referenced in function "private: virtual void __cdecl DataTest_CanSaveAndLoadDistributedRandomSampler_Test::TestBody(void)" (?TestBody@DataTest_CanSaveAndLoadDistributedRandomSampler_Test@@EEAAXXZ)
bin\test_api.exe : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "tools\build_libtorch.py", line 25, in <module>
    build_python=False, rerun_cmake=True, build_dir='.')
  File "F:\progs2\pytorchDebug\pytorch\tools\build_pytorch_libs.py", line 243, in build_caffe2
    cwd=build_dir, env=my_env)
  File "c:\local\Anaconda3\envs\PytorchDebug\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Debug', '--', '-j', '11']' returned non-zero exit status 1.
```

**Comment by peterjc123** [comment]
The workground here is to use `set BUILD_TEST=OFF`. I'll look into it when I have time.

**Comment by slaweks17** [comment]
Thank you! I managed to built it.

**Comment by peterjc123** [comment]
If you have time, would you please try if #17494 fixes your problem?

**Comment by slaweks17** [comment]
Hi,
Yes. With #17494 I can build without set BUILD_TEST=OFF

Thanks!
