### ISSUE TITLE
DataParallel gives `RuntimeError: can't start new thread` error when threading.active_count() is only 6

### ISSUE THREAD

**Issue by yxchng** [pytorch/pytorch#17643]
## 🐛 Bug

How to resolve the problem of using DataParallel giving `RuntimeError: can't start new thread` error when threading.active_count() is only 6?

I have tried using Python 3.5 and Python 3.7 and both give the same error. I am using CUDA 10.1 with the latest PyTorch.

It occurs when I use 1 GPU or 2 GPUs with DataParallel. There is no problem if I run using 1 GPU **without** DataParallel.

I face this problem even with the imagenet code in the examples repository of PyTorch.

The way I use DataParallel is to add the line `model = nn.DataParallel(model)` in my code. Am I using it wrong? What else do I need to do?

## To Reproduce

Run the imagenet code in examples repository of PyTorch

## Stack trace
`
Epoch: [1/24] | Iter: [6061/14863] | Time/Batch: 0.524 | CurrLoss: 11.3428 | AveLoss: 11.3451 | MarginAcc@1: 0.016757% | MarginAcc@5: 0.048788% | Acc@1: 0.016757% | Acc@5: 0.048788%

6

Epoch: [1/24] | Iter: [6071/14863] | Time/Batch: 0.524 | CurrLoss: 11.3428 | AveLoss: 11.3451 | MarginAcc@1: 0.016793% | MarginAcc@5: 0.048965% | Acc@1: 0.016793% | Acc@5: 0.048965%

6

Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f8fa3d142f0>
Traceback (most recent call last):
  File "/run/mount/sdd1/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/run/mount/sdd1/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 696, in _shutdown_workers
    self.worker_result_queue.put(None)
  File "/run/mount/sdd1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 87, in put
    self._start_thread()
  File "/run/mount/sdd1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 170, in _start_thread
    self._thread.start()
  File "/run/mount/sdd1/anaconda3/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "train.py", line 328, in <module>
    main()
  File "train.py", line 193, in main
    train(device, data_loader, model, margin_linear, lambda_func, criterion, optimizer, scheduler, args)
  File "train.py", line 219, in train
    output = model(input)
  File "/run/mount/sdd1/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/run/mount/sdd1/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/run/mount/sdd1/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/run/mount/sdd1/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 73, in parallel_apply
    thread.start()
  File "/run/mount/sdd1/anaconda3/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
`

**Comment by zmonoid** [comment]
Hi, any solution on this issue?

**Comment by zmonoid** [comment]
@yxchng

**Comment by yxchng** [comment]
For me, the problem arises from a hardware issue that affects the GPU. Just checking, do you use a X99 motherboard? If so, then maybe you are facing the same problem as me.

**Comment by hoban-cs** [comment]
@yxchng  Hi, I got same problem here. I ran my code on GCP. was there any setting to solve this?

**Comment by yxchng** [comment]
@hoban-cs Hmmm... hardware issue is unlikely to happen on GCP. Have you printed out the result of `threading.active_count()`? Can you post a small reproducible code here?

My error was solved by adding `pci=nommconf` to the grub settings on a PC with Ubuntu OS. This is the solution to a hardware issue that affects many X99 motherboard with multi-GPUs. However, I don't  think this will help you since you are running your code on GCP.
