### ISSUE TITLE
Building pytorch on ARM failed

### ISSUE THREAD

**Issue by xiaolin-cheng** [pytorch/pytorch#17666]
My build failed on HiKey 970 board. It looks like a compiler issue. How can fix it? Thank you!

 60%] Building CXX object caffe2/CMakeFiles/caffe2.dir/core/net_async_task.cc.o
[ 60%] Building CXX object caffe2/CMakeFiles/caffe2.dir/core/net_async_task_future.cc.o
[ 60%] Building CXX object caffe2/CMakeFiles/caffe2.dir/core/net_async_task_graph.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
caffe2/CMakeFiles/caffe2.dir/build.make:4785: recipe for target 'caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:3119: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 710, in <module>
    build_deps()
  File "setup.py", line 282, in build_deps
    build_dir='build')
  File "/mount-sd/pytorch/tools/build_pytorch_libs.py", line 255, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8', 'install']' returned non-zero exit status 2

**Comment by Wheest** [comment]
Could be an issue with not being able to allocate enough virtual memory, increasing swap file size would be a good next step to try

**Comment by colesbury** [comment]
Yeah, running out of memory seems like the most likely cause.
