### ISSUE TITLE
[jit] Bad optional access during training for ScriptModule

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#17669]
## 🐛 Bug

There appears to be some regression recently, the following script produce a error saying bad optional access, it used to work several days ago. 

## To Reproduce

```python
import torch
import torch.nn as nn


class ScriptClassifier(torch.jit.ScriptModule):

    def __init__(self):
        super(ScriptClassifier, self).__init__()
        self.fc1 = nn.Linear(50, 50)
        self.relu1 = nn.ReLU()
        self.dout = nn.Dropout(0.2)
        self.fc2 = nn.Linear(50, 100)
        self.prelu = nn.PReLU(1)
        self.out = nn.Linear(100, 1)
        self.out_act = nn.Sigmoid()

    @torch.jit.script_method
    def forward(self, input_):
        a1 = self.fc1(input_)
        h1 = self.relu1(a1)
        dout = self.dout(h1)
        a2 = self.fc2(dout)
        h2 = self.prelu(a2)
        a3 = self.out(h2)
        y = self.out_act(a3)
        return y


script_model = ScriptClassifier()

opt = torch.optim.Adam(script_model.parameters(), lr=0.001, betas=(0.9, 0.999))
criterion = nn.BCELoss()


def train_epoch(model, opt, criterion, batch_size=50):
    model.train()
    losses = []
    for beg_i in range(0, X.size(0), batch_size):
        x_batch = X[beg_i:beg_i + batch_size, :]
        y_batch = Y[beg_i:beg_i + batch_size, :]
        #x_batch = Variable(x_batch)
        #y_batch = Variable(y_batch)

        opt.zero_grad()
        # (1) Forward
        y_hat = model(x_batch)
        # (2) Compute diff
        loss = criterion(y_hat, y_batch)
        # (3) Compute gradients
        loss.backward()
        # (4) update weights
        opt.step()
        losses.append(loss.data.numpy())
    return losses


X1 = torch.randn(1000, 50)
X2 = torch.randn(1000, 50) + 1.5
X = torch.cat([X1, X2], dim=0)
Y1 = torch.zeros(1000, 1)
Y2 = torch.ones(1000, 1)
Y = torch.cat([Y1, Y2], dim=0)

e_losses = []
num_epochs = 20
for e in range(num_epochs):
    e_losses += train_epoch(script_model, opt, criterion)
```

it gives error like:
```
Traceback (most recent call last):
  File "test_toy.py", line 67, in <module>
    e_losses += train_epoch(script_model, opt, criterion)
  File "test_toy.py", line 46, in train_epoch
    y_hat = model(x_batch)
  File "/scratch/wanchaol/local/pytorch/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: bad optional access
```

need to bisect and see whats going on

**Comment by wanchaol** [comment]
It turned out this related to #17523, @ailzhang is working on a fix
