### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED when batch size is too large

### ISSUE THREAD

**Issue by Strideradu** [pytorch/pytorch#17774]
## 🐛 Bug

Got the RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED when execute a CNN model. It only appears when I have multiple GPU and the batch size is too large ( for my task it is ok for 128 but not 256).

And the GPU memory still has some space

```
[dunan@nvl-003 ~]$ nvidia-smi
Thu Mar  7 15:51:19 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:15:00.0 Off |                    0 |
| N/A   43C    P0    76W / 300W |  30731MiB / 32510MiB |     74%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:16:00.0 Off |                    0 |
| N/A   43C    P0    73W / 300W |  27283MiB / 32510MiB |     78%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17565      C   python                                     30720MiB |
|    1     17565      C   python                                     27272MiB |
+-----------------------------------------------------------------------------+

```

## To Reproduce

```
Traceback (most recent call last):
  File "/mnt/home/dunan/Job/2018/DNA_classification/DeepDFam/predict.py", line 60, in <module>
    predict(args)
  File "/mnt/home/dunan/Job/2018/DNA_classification/DeepDFam/predict.py", line 31, in predict
    logit = data_parallel(model, feature)
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py",
 line 188, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py"
, line 83, in parallel_apply
    raise output
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py"
, line 59, in _worker
    output = module(*input, **kwargs)
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 48
9, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/dunan/Job/2018/DNA_classification/DeepDFam/models/SingleFrameCNN.py", line 354, in forward
    x = [F.relu(conv(x)).squeeze(3) for i, conv in enumerate(self.convs1)]
  File "/mnt/home/dunan/Job/2018/DNA_classification/DeepDFam/models/SingleFrameCNN.py", line 354, in <listcomp
>
    x = [F.relu(conv(x)).squeeze(3) for i, conv in enumerate(self.convs1)]
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 48
9, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/dunan/Job/2018/DNA_classification/DeepDFam/models/SingleFrameCNN.py", line 307, in forward
    x1 = [conv(x1[:, :, i:seq_len - self.kernel_size[0] + i + 1, :]) for i, conv in enumerate(self.convs1)]
  File "/mnt/home/dunan/Job/2018/DNA_classification/DeepDFam/models/SingleFrameCNN.py", line 307, in <listcomp
>
    x1 = [conv(x1[:, :, i:seq_len - self.kernel_size[0] + i + 1, :]) for i, conv in enumerate(self.convs1)]
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 48
9, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/dunan/anaconda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320,
 in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux release 7.4.1708 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB

Nvidia driver version: 396.44
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.16.1
[pip3] numpydoc==0.7.0
[pip3] torch==1.0.0
[pip3] torchtext==0.2.3
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] mkl                       2018.0.3                      1
[conda] mkl-dnn                   0.14                    intel_1  [intel]  intel
[conda] mkl-include               2018.0.2                      1
[conda] mkl-service               1.1.2                    py36_3
[conda] mkl_fft                   1.0.10                   py36_0    conda-forge
[conda] mkl_random                1.0.2                    py36_0    conda-forge
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchtext                 0.2.3                    pypi_0    pypi
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by ngimel** [comment]
Can you please collect cudnn log for your script? https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#api-logging 
It looks like OOM, when memory is close to the limit some allocations for internal structures may fail and errors would manifest as CUDNN_EXECUTION_FAILED, where in fact it is just and out of memory error in disguise. If you don't see this error while running the same per-gpu batch size on a single GPU, this is likely out-of-memory, because multi-gpu jobs require more memory.

**Comment by debvrat** [comment]
Hi,

I am getting the same error on a relatively small batch size: 64.
How do you get around this?

**Comment by ptrblck** [comment]
@debvrat could you post a code snippet to reproduce this issue, please?

**Comment by AWehenkel** [comment]
Hi,

I am experiencing the same issue with pytorch 1.4 and cuda 10.1. 
My code is running well when I use 1 GPU but once I go for two GPUs with data parallel it crashes with:
`File "/home/awehenkel/miniconda3/envs/UMNN/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/awehenkel/miniconda3/envs/UMNN/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`
Any idea on how I could solve this problem?
Thanks!

**Comment by ptrblck** [comment]
@AWehenkel Could you monitor the memory usage via `nvidia-smi` and make sure you are not running our of memory?
If you have enough memory left, could you update to the latest nightly and rerun the code?
Also, could you post a code snippet to reproduce this issue?

**Comment by AWehenkel** [comment]
Hi @ptrblck,
Thanks for your reply. The error was caused by my poor code quality, for those who could encounter the same problem here's what was wrong in my implementation. 

From what I understand Dataparallel clones the Parameters of the underlying model on the multiple GPUs and is agnostic about the rest of the model (it will only execute the forward method but won't move any properties of the model except its Parameters and won't call any other method (in particular it will not call the "to" method). 
I had some properties of my model that were tensors not defined as parameters (because I do not need their gradient), I had overwritten the "to" method in order to make the move from different location correct for these properties. This was my mistake. I only understood yesterday it was not the proper way to do it. Instead, the good way to do it is to put these tensors as parameters with requires_grad= false.

**Comment by ngimel** [comment]
@AWehenkel a more idiomatic way is to register those tensor attributes as [buffers ](https://pytorch.org/docs/stable/nn.html?highlight=register_buffer#torch.nn.Module.register_buffer). You are right, `.to()` is not called recursively on the model, so overriding it does not correctly maintain the device of the tensor attributes.
