### ISSUE TITLE
RuntimeError wen model.eval()

### ISSUE THREAD

**Issue by VCBE123** [pytorch/pytorch#17793]
## ❓ Questions and Help

when I  evaluate the model after trained one epoch. I got this essue.

```bash
Traceback (most recent call last):
  File "/home/wen/PycharmProjects/Attention-Echino/train.py", line 221, in <module>
    main()
  File "/home/wen/PycharmProjects/Attention-Echino/train.py", line 81, in main
    valObj, prec1, prec2 = evaluate(valloader, model, critertion)
  File "/home/wen/PycharmProjects/Attention-Echino/train.py", line 141, in evaluate
    output= model(input,target)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in forward
    return self.gather(outputs, self.output_device)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 136, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 65, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/cuda/comm.py", line 160, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError:  (gather at torch/csrc/cuda/comm.cpp:177)
frame #0: <unknown function> + 0xc48aea (0x7fc338656aea in /home/wen/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x39124b (0x7fc337d9f24b in /home/wen/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: _PyCFunction_FastCallDict + 0x154 (0x563b9f076744 in /home/wen/anaconda3/bin/python)
frame #3: <unknown function> + 0x19842c (0x563b9f0fd42c in /home/wen/anaconda3/bin/python)
frame #4: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #5: <unknown function> + 0x1918e4 (0x563b9f0f68e4 in /home/wen/anaconda3/bin/python)
frame #6: <unknown function> + 0x192771 (0x563b9f0f7771 in /home/wen/anaconda3/bin/python)
frame #7: <unknown function> + 0x198505 (0x563b9f0fd505 in /home/wen/anaconda3/bin/python)
frame #8: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #9: PyEval_EvalCodeEx + 0x966 (0x563b9f0f88c6 in /home/wen/anaconda3/bin/python)
frame #10: <unknown function> + 0x194094 (0x563b9f0f9094 in /home/wen/anaconda3/bin/python)
frame #11: PyObject_Call + 0x3e (0x563b9f07654e in /home/wen/anaconda3/bin/python)
frame #12: THPFunction_apply(_object*, _object*) + 0x38f (0x7fc33817d6af in /home/wen/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #13: PyCFunction_Call + 0x5f (0x563b9f07963f in /home/wen/anaconda3/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x542d (0x563b9f1274ad in /home/wen/anaconda3/bin/python)
frame #15: <unknown function> + 0x191bfe (0x563b9f0f6bfe in /home/wen/anaconda3/bin/python)
frame #16: <unknown function> + 0x192771 (0x563b9f0f7771 in /home/wen/anaconda3/bin/python)
frame #17: <unknown function> + 0x198505 (0x563b9f0fd505 in /home/wen/anaconda3/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #19: <unknown function> + 0x191bfe (0x563b9f0f6bfe in /home/wen/anaconda3/bin/python)
frame #20: <unknown function> + 0x192771 (0x563b9f0f7771 in /home/wen/anaconda3/bin/python)
frame #21: <unknown function> + 0x198505 (0x563b9f0fd505 in /home/wen/anaconda3/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x10c7 (0x563b9f123147 in /home/wen/anaconda3/bin/python)
frame #23: <unknown function> + 0x19253b (0x563b9f0f753b in /home/wen/anaconda3/bin/python)
frame #24: <unknown function> + 0x198505 (0x563b9f0fd505 in /home/wen/anaconda3/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #26: <unknown function> + 0x1918e4 (0x563b9f0f68e4 in /home/wen/anaconda3/bin/python)
frame #27: _PyFunction_FastCallDict + 0x3da (0x563b9f0f7e6a in /home/wen/anaconda3/bin/python)
frame #28: _PyObject_FastCallDict + 0x26f (0x563b9f076b0f in /home/wen/anaconda3/bin/python)
frame #29: _PyObject_Call_Prepend + 0x63 (0x563b9f07b6a3 in /home/wen/anaconda3/bin/python)
frame #30: PyObject_Call + 0x3e (0x563b9f07654e in /home/wen/anaconda3/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x19ec (0x563b9f123a6c in /home/wen/anaconda3/bin/python)
frame #32: <unknown function> + 0x1918e4 (0x563b9f0f68e4 in /home/wen/anaconda3/bin/python)
frame #33: _PyFunction_FastCallDict + 0x1bc (0x563b9f0f7c4c in /home/wen/anaconda3/bin/python)
frame #34: _PyObject_FastCallDict + 0x26f (0x563b9f076b0f in /home/wen/anaconda3/bin/python)
frame #35: _PyObject_Call_Prepend + 0x63 (0x563b9f07b6a3 in /home/wen/anaconda3/bin/python)
frame #36: PyObject_Call + 0x3e (0x563b9f07654e in /home/wen/anaconda3/bin/python)
frame #37: <unknown function> + 0x16ba91 (0x563b9f0d0a91 in /home/wen/anaconda3/bin/python)
frame #38: _PyObject_FastCallDict + 0x8b (0x563b9f07692b in /home/wen/anaconda3/bin/python)
frame #39: <unknown function> + 0x19857e (0x563b9f0fd57e in /home/wen/anaconda3/bin/python)
frame #40: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #41: <unknown function> + 0x19253b (0x563b9f0f753b in /home/wen/anaconda3/bin/python)
frame #42: <unknown function> + 0x198505 (0x563b9f0fd505 in /home/wen/anaconda3/bin/python)
frame #43: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #44: <unknown function> + 0x19253b (0x563b9f0f753b in /home/wen/anaconda3/bin/python)
frame #45: <unknown function> + 0x198505 (0x563b9f0fd505 in /home/wen/anaconda3/bin/python)
frame #46: _PyEval_EvalFrameDefault + 0x30a (0x563b9f12238a in /home/wen/anaconda3/bin/python)
frame #47: PyEval_EvalCodeEx + 0x329 (0x563b9f0f8289 in /home/wen/anaconda3/bin/python)
frame #48: PyEval_EvalCode + 0x1c (0x563b9f0f901c in /home/wen/anaconda3/bin/python)
frame #49: <unknown function> + 0x2163c4 (0x563b9f17b3c4 in /home/wen/anaconda3/bin/python)
frame #50: PyRun_FileExFlags + 0xa1 (0x563b9f17b7c1 in /home/wen/anaconda3/bin/python)
frame #51: PyRun_SimpleFileExFlags + 0x1c3 (0x563b9f17b9c3 in /home/wen/anaconda3/bin/python)
frame #52: Py_Main + 0x613 (0x563b9f17f4b3 in /home/wen/anaconda3/bin/python)
frame #53: main + 0xee (0x563b9f04802e in /home/wen/anaconda3/bin/python)
frame #54: __libc_start_main + 0xf0 (0x7fc34348a830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #55: <unknown function> + 0x1c3e0e (0x563b9f128e0e in /home/wen/anaconda3/bin/python)
```

**Comment by zou3519** [comment]
Please provide some more context.

**Comment by VCBE123** [comment]
I use 4 gpus with torch.nn.DataParallel, and set the batch size to 10. I  get the same error.
Sorry to that.

**Comment by VCBE123** [comment]
But It was strange when I set the batch size to 40 with 4 GPUs,I got the same error in evalue, my test set have 2410 images.  So the program crashed :
```bash
File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/cuda/comm.py", line 160, in gather
    return torch._C._gather(tensors, dim, destination)
```
the tensors have different shaoe:   [3,] [3, ] [3,] [1,]
