### ISSUE TITLE
CUDA large matrix-vector product causes illegal memory access

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#17897]
## 🐛 Bug

`torch.mv` causes an "illegal memory access" when multiplying a matrix with more than 2^31-1 elements. Note that each dim of the first matrix can fit in an `int`.

This is likely a bug in cuBLAS. Either cuBLAS should be fixed or PyTorch should issue multiple calls to `cublasSgemv`.

## To Reproduce

Note: you need ~10 GB on your GPU to run this example

```python
x = torch.ones(35783, 65133, device='cuda')
y = torch.randn(65133, device='cuda')
z = torch.mv(x, y)
torch.cuda.synchronize()  # report asynchronous error
```

## Environment

PyTorch master 066d1584 (Mar 11, 2019)
CUDA 9.2.88

**Comment by ezyang** [comment]
cc @ngimel; do you think this is a cublas bug? No matter what, however, we should probably just issue multiple calls to work around this.

We really need nightly tests with big inputs...

Some of our other matrix multiply functions seem affected as well:

```
>>> import torch
>>> x = torch.ones(35783, 65133, device='cuda')
>>> y = torch.randn(65133, 1, device='cuda')
>>> z = torch.mm(x, y)
>>> torch.cuda.synchronize()
THCudaCheck FAIL file=../torch/csrc/cuda/Module.cpp line=215 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/ezyang/pytorch-tmp/torch/cuda/__init__.py", line 358, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at ../torch/csrc/cuda/Module.cpp:215
```

@colesbury do you know how urgent this is? @izdeby might be interested in taking this up if it's not urgent.

**Comment by ngimel** [comment]
It is definitely a cublas bug.

**Comment by ezyang** [comment]
@colesbury When you get a chance, if you could paste your workaround code here that would be great :)
