### ISSUE TITLE
Fail to install PyTorch from source

### ISSUE THREAD

**Issue by LJXLJXLJX** [pytorch/pytorch#17906]
OS ：Windows10 64bit

I am trying to build libtorch for C++, I followed the official instructions

> set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
> set DISTUTILS_USE_SDK=1
> REM Run "Visual Studio 2017 Developer Command Prompt"
> python setup.py install

But I failed and got some error.

> D:\pytorch>python setup.py install
> Building wheel torch-1.1.0a0+b161ac9
> -- Building version 1.1.0a0+b161ac9
> ['cmake',
>  'D:\\pytorch',
>  '-GNinja',
>  '-DBUILDING_WITH_TORCH_LIBS=ON',
>  '-DBUILD_BINARY=False',
>  '-DBUILD_CAFFE2_OPS=True',
>  '-DBUILD_PYTHON=True',
>  '-DBUILD_SHARED_LIBS=ON',
>  '-DBUILD_TEST=True',
>  '-DBUILD_TORCH=ON',
>  '-DCAFFE2_STATIC_LINK_CUDA=False',
>  '-DCMAKE_BUILD_TYPE=Release',
>  '-DCMAKE_CXX_FLAGS=  /EHa',
>  '-DCMAKE_C_FLAGS=  /EHa',
>  '-DCMAKE_EXE_LINKER_FLAGS=',
>  '-DCMAKE_INSTALL_PREFIX=D:\\pytorch/torch',
>  '-DCMAKE_PREFIX_PATH=D:\\Anaconda3x64\\Lib\\site-packages',
>  '-DCMAKE_SHARED_LINKER_FLAGS=',
>  '-DINSTALL_TEST=True',
>  '-DNCCL_EXTERNAL=False',
>  '-DNUMPY_INCLUDE_DIR=D:/Anaconda3x64/lib/site-packages/numpy/core/include',
>  '-DONNX_ML=False',
>  '-DONNX_NAMESPACE=onnx_torch',
>  '-DPYTHON_EXECUTABLE=D:/Anaconda3x64/python.exe',
>  '-DPYTHON_INCLUDE_DIR=D:/Anaconda3x64/include',
>  '-DPYTHON_LIBRARY=D:/Anaconda3x64/libs/python36.lib',
>  '-DTHD_SO_VERSION=1',
>  '-DTORCH_BUILD_VERSION=1.1.0a0+b161ac9',
>  '-DUSE_CUDA=False',
>  '-DUSE_DISTRIBUTED=False',
>  '-DUSE_FBGEMM=True',
>  '-DUSE_FFMPEG=False',
>  '-DUSE_LEVELDB=False',
>  '-DUSE_LMDB=False',
>  '-DUSE_MKLDNN=True',
>  '-DUSE_NCCL=False',
>  '-DUSE_NNPACK=True',
>  '-DUSE_NUMPY=True',
>  '-DUSE_OPENCV=False',
>  '-DUSE_QNNPACK=True',
>  '-DUSE_ROCM=False',
>  '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
>  '-DUSE_SYSTEM_NCCL=False',
>  '-DUSE_TENSORRT=False',
>  '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON']
> -- The CXX compiler identification is unknown
> -- The C compiler identification is unknown
> CMake Error at CMakeLists.txt:11 (project):
>   The CMAKE_CXX_COMPILER:
> 
>     D:/cygwin/bin/c++.exe
> 
>   is not a full path to an existing compiler tool.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
>   to the compiler, or to the compiler name if it is in the PATH.
> 
> 
> CMake Error at CMakeLists.txt:11 (project):
>   The CMAKE_C_COMPILER:
> 
>     D:/cygwin/bin/cc
> 
>   is not a full path to an existing compiler tool.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
>   the compiler, or to the compiler name if it is in the PATH.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/pytorch/build/CMakeFiles/CMakeOutput.log".
> See also "D:/pytorch/build/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "setup.py", line 710, in <module>
>     build_deps()
>   File "setup.py", line 282, in build_deps
>     build_dir='build')
>   File "D:\pytorch\tools\build_pytorch_libs.py", line 239, in build_caffe2
>     my_env)
>   File "D:\pytorch\tools\build_pytorch_libs.py", line 219, in run_cmake
>     check_call(cmake_args, cwd=build_dir, env=my_env)
>   File "D:\Anaconda3x64\lib\subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', 'D:\\pytorch', '-GNinja', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DBUILD_TORCH=ON', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS=  /EHa', '-DCMAKE_C_FLAGS=  /EHa', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=D:\\pytorch/torch', '-DCMAKE_PREFIX_PATH=D:\\Anaconda3x64\\Lib\\site-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=D:/Anaconda3x64/lib/site-packages/numpy/core/include', '-DONNX_ML=False', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=D:/Anaconda3x64/python.exe', '-DPYTHON_INCLUDE_DIR=D:/Anaconda3x64/include', '-DPYTHON_LIBRARY=D:/Anaconda3x64/libs/python36.lib', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.1.0a0+b161ac9', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=False', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON']' returned non-zero exit status 1.
>

**Comment by LJXLJXLJX** [comment]
Sorry , I have made some mistakes myself.
