### ISSUE TITLE
undefined reference to `vmdLog2',`cblas_gemm_s8u8s32'

### ISSUE THREAD

**Issue by xiaoheizi123** [pytorch/pytorch#17903]
**issue deacription**

```
[ 83%] Building CXX object caffe2/CMakeFiles/reshape_op_gpu_test.dir/operators/reshape_op_gpu_test.cc.o
[ 83%] Building CXX object caffe2/CMakeFiles/utility_ops_gpu_test.dir/operators/utility_ops_gpu_test.cc.o
[ 83%] Building CXX object caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/operators/generate_proposals_op_util_nms_gpu_test.cc.o
[ 83%] Building CXX object caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/operators/generate_proposals_op_gpu_test.cc.o
[ 83%] Linking CXX executable ../bin/reshape_op_gpu_test
[ 83%] Linking CXX executable ../bin/utility_ops_gpu_test
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:104: recipe for target 'bin/reshape_op_gpu_test' failed
make[2]: *** [bin/reshape_op_gpu_test] Error 1
CMakeFiles/Makefile2:3056: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/utility_ops_gpu_test.dir/build.make:104: recipe for target 'bin/utility_ops_gpu_test' failed
make[2]: *** [bin/utility_ops_gpu_test] Error 1
CMakeFiles/Makefile2:3012: recipe for target 'caffe2/CMakeFiles/utility_ops_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
[ 83%] Linking CXX executable ../bin/generate_proposals_op_gpu_test
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/build.make:104: recipe for target 'bin/generate_proposals_op_gpu_test' failed
make[2]: *** [bin/generate_proposals_op_gpu_test] Error 1
CMakeFiles/Makefile2:3144: recipe for target 'caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/all] Error 2
[ 83%] Linking CXX executable ../bin/generate_proposals_op_util_nms_gpu_test
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32'
/home/zhengr/data/projects/caffe2-source/pytorch/build/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/build.make:104: recipe for target 'bin/generate_proposals_op_util_nms_gpu_test' failed
make[2]: *** [bin/generate_proposals_op_util_nms_gpu_test] Error 1
CMakeFiles/Makefile2:3100: recipe for target 'caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 710, in <module>
    build_deps()
  File "setup.py", line 282, in build_deps
    build_dir='build')
  File "/home/zhengr/data/projects/caffe2-source/pytorch/tools/build_pytorch_libs.py", line 255, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/home/zhengr/.conda/envs/caffe2-source/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', 'install']' returned non-zero exit status 2

build info
******** Summary ********
--   CMake version         : 3.13.4
--   CMake command         : /home/zhengr/.conda/envs/caffe2-source/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.9.3
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL
--   CMAKE_PREFIX_PATH     : /home/zhengr/.conda/envs/caffe2-source
--   CMAKE_INSTALL_PREFIX  : /home/zhengr/data/projects/caffe2-source/pytorch/torch
--   CMAKE_MODULE_PATH     : /home/zhengr/data/projects/caffe2-source/pytorch/cmake/Modules;/home/zhengr/data/projects/caffe2-source/pytorch/cmake/public/../Modules_CUDA_fix
-- 
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- 
-- ******** Summary ********
--   CMake version         : 3.13.4
--   CMake command         : /home/zhengr/.conda/envs/caffe2-source/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.9.3
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL
--   CMAKE_PREFIX_PATH     : /home/zhengr/.conda/envs/caffe2-source
--   CMAKE_INSTALL_PREFIX  : /home/zhengr/data/projects/caffe2-source/pytorch/torch
--   CMAKE_MODULE_PATH     : /home/zhengr/data/projects/caffe2-source/pytorch/cmake/Modules;/home/zhengr/data/projects/caffe2-source/pytorch/cmake/public/../Modules_CUDA_fix
-- 
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- 
-- ******** Summary ********
--   CMake version         : 3.13.4
--   CMake command         : /home/zhengr/.conda/envs/caffe2-source/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.9.3
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL
--   CMAKE_PREFIX_PATH     : /home/zhengr/.conda/envs/caffe2-source
--   CMAKE_INSTALL_PREFIX  : /home/zhengr/data/projects/caffe2-source/pytorch/torch
--   CMAKE_MODULE_PATH     : /home/zhengr/data/projects/caffe2-source/pytorch/cmake/Modules;/home/zhengr/data/projects/caffe2-source/pytorch/cmake/public/../Modules_CUDA_fix
-- 
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- Found CUDA with FP16 support, compiling with torch.cuda.HalfTensor
-- Removing -DNDEBUG from compile flags
-- Checking prototype magma_get_sgeqrf_nb for MAGMA_V2 - True
-- Compiling with MAGMA support
-- MAGMA INCLUDE DIRECTORIES: /home/zhengr/.conda/envs/caffe2-source/include
-- MAGMA LIBRARIES: /home/zhengr/.conda/envs/caffe2-source/lib/libmagma.a
-- MAGMA V2 check: 1
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Performing Test HAVE_GCC_GET_CPUID
-- Performing Test HAVE_GCC_GET_CPUID - Success
-- Performing Test NO_GCC_EBX_FPIC_BUG
-- Performing Test NO_GCC_EBX_FPIC_BUG - Success
-- Performing Test C_HAS_AVX_1
-- Performing Test C_HAS_AVX_1 - Failed
-- Performing Test C_HAS_AVX_2
-- Performing Test C_HAS_AVX_2 - Success
-- Performing Test C_HAS_AVX2_1
-- Performing Test C_HAS_AVX2_1 - Failed
-- Performing Test C_HAS_AVX2_2
-- Performing Test C_HAS_AVX2_2 - Success
-- Performing Test CXX_HAS_AVX_1
-- Performing Test CXX_HAS_AVX_1 - Failed
-- Performing Test CXX_HAS_AVX_2
-- Performing Test CXX_HAS_AVX_2 - Success
-- Performing Test CXX_HAS_AVX2_1
-- Performing Test CXX_HAS_AVX2_1 - Failed
-- Performing Test CXX_HAS_AVX2_2
-- Performing Test CXX_HAS_AVX2_2 - Success
-- AVX compiler support found
-- AVX2 compiler support found
-- Performing Test HAS_C11_ATOMICS
-- Performing Test HAS_C11_ATOMICS - Failed
-- Performing Test HAS_MSC_ATOMICS
-- Performing Test HAS_MSC_ATOMICS - Failed
-- Performing Test HAS_GCC_ATOMICS
-- Performing Test HAS_GCC_ATOMICS - Success
-- Atomics: using GCC intrinsics
-- Performing Test BLAS_F2C_DOUBLE_WORKS
-- Performing Test BLAS_F2C_DOUBLE_WORKS - Failed
-- Performing Test BLAS_F2C_FLOAT_WORKS
-- Performing Test BLAS_F2C_FLOAT_WORKS - Success
-- Performing Test BLAS_USE_CBLAS_DOT
-- Performing Test BLAS_USE_CBLAS_DOT - Success
-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API (mkl).
disabling ROCM because NOT USE_ROCM is set
-- MIOpen not found. Compiling without MIOpen support
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- OpenMP lib: provided by compiler
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VTune profiling environment is unset
-- Found MKL-DNN: TRUE
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for shm_open
-- Looking for shm_open - found
-- Looking for shm_unlink
-- Looking for shm_unlink - found
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - found
-- Performing Test C_HAS_THREAD
-- Performing Test C_HAS_THREAD - Success
-- GCC 4.9.3: Adding gcc and gcc_s libs to link line
-- NUMA paths:
-- /usr/include
-- /usr/lib/x86_64-linux-gnu/libnuma.so
-- Check size of long double
-- Check size of long double - done
-- Performing Test COMPILER_SUPPORTS_LONG_DOUBLE
-- Performing Test COMPILER_SUPPORTS_LONG_DOUBLE - Failed
-- Performing Test COMPILER_SUPPORTS_FLOAT128
-- Performing Test COMPILER_SUPPORTS_FLOAT128 - Success
-- Performing Test COMPILER_SUPPORTS_SSE2
-- Performing Test COMPILER_SUPPORTS_SSE2 - Success
-- Performing Test COMPILER_SUPPORTS_SSE4
-- Performing Test COMPILER_SUPPORTS_SSE4 - Success
-- Performing Test COMPILER_SUPPORTS_AVX
-- Performing Test COMPILER_SUPPORTS_AVX - Success
-- Performing Test COMPILER_SUPPORTS_FMA4
-- Performing Test COMPILER_SUPPORTS_FMA4 - Success
-- Performing Test COMPILER_SUPPORTS_AVX2
-- Performing Test COMPILER_SUPPORTS_AVX2 - Success
-- Performing Test COMPILER_SUPPORTS_SVE
-- Performing Test COMPILER_SUPPORTS_SVE - Failed
-- Performing Test COMPILER_SUPPORTS_AVX512F
-- Performing Test COMPILER_SUPPORTS_AVX512F - Failed
-- Performing Test COMPILER_SUPPORTS_OPENMP
-- Performing Test COMPILER_SUPPORTS_OPENMP - Success
-- Performing Test COMPILER_SUPPORTS_WEAK_ALIASES
-- Performing Test COMPILER_SUPPORTS_WEAK_ALIASES - Success
-- Performing Test COMPILER_SUPPORTS_BUILTIN_MATH
-- Performing Test COMPILER_SUPPORTS_BUILTIN_MATH - Success
-- Configuring build for SLEEF-v3.2
   Target system: Linux-4.15.0-46-generic
   Target processor: x86_64
   Host system: Linux-4.15.0-46-generic
   Host processor: x86_64
   Detected C compiler: GNU @ /usr/bin/cc
-- Using option `-Wall -Wno-unused -Wno-attributes -Wno-unused-result -Wno-psabi -ffp-contract=off -fno-math-errno -fno-trapping-math` to compile libsleef
-- Building shared libs : OFF
-- MPFR : LIB_MPFR-NOTFOUND
-- GMP : LIBGMP-NOTFOUND
-- RUNNING_ON_TRAVIS : 0
-- COMPILER_SUPPORTS_OPENMP : 1
-- pytorch is compiling with OpenMP. 
OpenMP CXX_FLAGS: -fopenmp. 
OpenMP libraries: /usr/lib/gcc/x86_64-linux-gnu/4.9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so.
-- /usr/bin/c++ /home/zhengr/data/projects/caffe2-source/pytorch/torch/abi-check.cpp -o /home/zhengr/data/projects/caffe2-source/pytorch/build/abi-check
-- Determined _GLIBCXX_USE_CXX11_ABI=0
-- Performing Test HAS_THREAD_LOCAL
-- Performing Test HAS_THREAD_LOCAL - Success
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5") 
-- MPI_LIBRARIES: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- Building the gloo backend with TCP support only
-- MPI_LINK_FLAGS: -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -pthread
-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- Building C10D with CUDA support
-- MPI_INCLUDE_PATH: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include/openmpi;/usr/lib/openmpi/include
-- MPI_LIBRARIES: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- MPIEXEC: /usr/bin/mpiexec
-- Include NCCL operators
-- Including IDEEP operators
-- Excluding image processing operators due to no opencv
-- Excluding video processing operators due to no opencv
-- Include Observer library
-- Caffe2 is compiling with OpenMP. 
OpenMP CXX_FLAGS: -fopenmp. 
OpenMP libraries: /usr/lib/gcc/x86_64-linux-gnu/4.9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so.
-- Using lib/python2.7/site-packages as python relative installation path
CMake Warning at CMakeLists.txt:421 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.

-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.13.4
--   CMake command         : /home/zhengr/.conda/envs/caffe2-source/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 4.9.3
--   BLAS                  : MKL
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;USE_GCC_ATOMICS=1;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /home/zhengr/.conda/envs/caffe2-source
--   CMAKE_INSTALL_PREFIX  : /home/zhengr/data/projects/caffe2-source/pytorch/torch

--   TORCH_VERSION         : 1.1.0
--   CAFFE2_VERSION        : 1.1.0
--   BUILD_ATEN_MOBILE     : OFF
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : False
--   BUILD_CUSTOM_PROTOBUF : ON
--     Protobuf compiler   : 
--     Protobuf includes   : 
--     Protobuf libraries  : 
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 2.7.15
--     Python executable   : /home/zhengr/.conda/envs/caffe2-source/bin/python
--     Pythonlibs version  : 2.7.15
--     Python library      : /home/zhengr/.conda/envs/caffe2-source/lib/libpython2.7.so.1.0
--     Python includes     : /home/zhengr/.conda/envs/caffe2-source/include/python2.7
--     Python site-packages: lib/python2.7/site-packages
--   BUILD_CAFFE2_OPS      : True
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   USE_ASAN              : OFF
--   USE_CUDA              : True
--     CUDA static link    : False
--     USE_CUDNN           : ON
--     CUDA version        : 8.0
--     cuDNN version       : 7.1.3
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so.7
--     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : False
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : False
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : False
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : False
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_NCCL              : True
--     USE_SYSTEM_NCCL     : True
--   USE_NNPACK            : True
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : False
--   USE_OPENMP            : ON
--   USE_PROF              : OFF
--   USE_QNNPACK           : True
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : True
--     USE_MPI             : ON
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;nnpack;cpuinfo;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
```

some one suggest  conda install mkl & conda install mkl-include for 'undefined reference to `vmdLog2'', and export CONDA_PREFIX=${CONDA_PREFIX:-"$(dirname $(which conda))/../"} for 'undefined reference 'tocblas_gemm_s8u8s32'', but it doesn't work here. 
can anyone help me?

**Comment by ezyang** [comment]
This is an mkl version mismatch, e.g., #5099. Upgrade your copy of mkl and mkl-include (and make sure there aren't any old versions hanging around) and try again. One easy way to make sure you get a hermetic environment is try the install from a fresh conda install.
