### ISSUE TITLE
Build compact libtorch from source with cmake 

### ISSUE THREAD

**Issue by bobqywei** [pytorch/pytorch#17920]
Hi. I am currently working with the PyTorch C++ API and I'm really enjoying the flexibility so far. However, for my use case, I would like the libraries to be as small as possible.

When building libtorch from source (using build_libtorch.py), what can be done to minimize the final package size? I have searched around but there does not seem to be any info related to this (other than cmake compiler optimisations).

**Comment by zou3519** [comment]
I think we don't support this at the moment. @yf225 can tell you more.

If it is not too much trouble, could you let us know what your use case is so we can motivate the problem better?

**Comment by yf225** [comment]
@bobqywei Are you building the CUDA version of libtorch or CPU version? Would love to know more about your use case so that we can make better suggestions.

**Comment by bobqywei** [comment]
@yf225 @zou3519 I am building the CUDA version of libtorch right now. As for my use case, I am hoping to use libtorch as part of a large project (some restrictions on external library size).

Currently I have tried changing some of the options in the CMakeLists, one interesting option is BUILD_ATEN_ONLY. But, when I set this to ON, I get this error:

`Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 25, in <module>
    build_python=False, rerun_cmake=True, build_dir='.')
  File "/home/bobw/pytorch/tools/build_pytorch_libs.py", line 259, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '12', 'install']' returned non-zero exit status 2`

Seems like it's still trying to build caffe2, and is related to this:

`In file included from /home/bobw/pytorch/caffe2/core/context_base.h:7:0,
                 from /home/bobw/pytorch/caffe2/core/context.h:10,
                 from /home/bobw/pytorch/caffe2/core/storage.h:14,
                 from /home/bobw/pytorch/caffe2/core/tensor.h:4,
                 from /home/bobw/pytorch/caffe2/core/blob.h:14,
                 from /home/bobw/pytorch/caffe2/core/operator.h:14,
                 from /home/bobw/pytorch/modules/module_test/module_test_dynamic.cc:18:
/home/bobw/pytorch/caffe2/proto/caffe2_pb.h:4:10: fatal error: caffe2/proto/caffe2.pb.h: No such file or directory
 #include <caffe2/proto/caffe2.pb.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/build.make:62: recipe for target 'modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/module_test_dynamic.cc.o' failed
make[2]: *** [modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/module_test_dynamic.cc.o] Error 1
CMakeFiles/Makefile2:5111: recipe for target 'modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/all' failed
make[1]: *** [modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

**Comment by ezyang** [comment]
`BUILD_CAFFE2_OPS=0` might help. But we don't have a good story for cutting out operators you don't need. It's something we're thinking about how to support for other use cases, like libtorch mobile.

**Comment by lee-junjie** [comment]
My scenario:
I am going to build a model serving with GRPC. 
However, both GPRC and Torch(mainly for Caffe?) libraries depend on protobuf. I am not familiar with CMake, and it's very painful for me to make the CMakeList.txt work well.

**Comment by bobqywei** [comment]
@ezyang I see, i'll give that a shot and see how it goes

**Comment by yf225** [comment]
Specifying `TORCH_CUDA_ARCH_LIST` to be targeting only your CUDA architecture will also make the package smaller (e.g. `TORCH_CUDA_ARCH_LIST=5.2` for Tesla M60).

**Comment by bobqywei** [comment]
@yf225 hmm, yea targeting specific CUDA architecture seems promising, will def try it. Thanks everyone for the suggestions so far.  

Also, this is a bit unrelated, but on the latest Pytorch build (no modifications), libtorch is not being compiled correctly and the resulting target executable produces this:`error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory`. I'm not sure what's going on here?

**Comment by yf225** [comment]
@bobqywei Do you mind opening a new issue for this problem, including the reproduction steps?

**Comment by NeilWangziyu** [comment]
@bobqywei Hi, I am also looking for some way to build a smaller libtorch for a larger project. Do you have any progress on it? Currently I am interesting in Jit module.

**Comment by ezyang** [comment]
Hi Neil! Static linking is a cheap way to have the linker DCE for you #21737 and we might also have a way to replace operator dynamic dispatch with hard-coded if statement to help the linker out more.

**Comment by ezyang** [comment]
Downgraded priority (I think I marked this as high priority in relation to what we are doing to reduce binary size in mobbile, bbut the ask here is for something else)

**Comment by amirmirzaei79** [comment]
Hi, I am looking for a way to build compact versions of libtorch (cpu) for PC.
I'm going to use it in robocup soccer simulation league and there is a restriction on project size so I need it to be as compact as possible and only include necessary operands.

**Comment by sukuya** [comment]
> Hi, I am looking for a way to build compact versions of libtorch (cpu) for PC.
> I'm going to use it in robocup soccer simulation league and there is a restriction on project size so I need it to be as compact as possible and only include necessary operands.

You can use the python script `build_libtorch.py` in `tools`  folder. Also, you may switch off the non useful components from `CMakeLists.txt` in `pytorch` root directory before running the build script.

**Comment by shyney7** [comment]
Has anyone here managed to compile libtorch with cmake? I would like to build using my custom cmake toolchain file to cross-compile for QNX. I need to use the QNX Software Dev. Platform and the custom gcc compiler from QNX called qcc. 

Unfortunately I encountered some problems which I describe here https://github.com/pytorch/pytorch/issues/38310#issue-616494038 . The first step is to compile libtorch from source.  Unfortunately I have no experience in compiling with python for C++. So I would be happy if you have suggestions how I can use cmake for compiling or change the python build files in a way that my toolchain file is taken into account.

**Comment by gemfield** [comment]
@shyney7 There is no official support for QNX yet, but you can try with scripts/build_android.sh and replace -DCMAKE_TOOLCHAIN_FILE from android's to QNX's.

**Comment by gemfield** [comment]
For libtorch static library build (on Linux) and usage, following links may be helpful:
https://github.com/CivilNet/libtorch
https://github.com/DeepVAC/libdeepvac/blob/master/CMakeLists.txt

**Comment by shyney7** [comment]
@gemfield Thank you so much for this information. I will try to figure out the context of your posted links and will try to cross-compile libtorch from source for QNX using the build_android.sh script. 
Unfortunately article of your page is in chinese and the google transator is pretty bad at translating chinese in my opinion. But I will try to understand everything. Hopefully I will be able to use libtorch for QNX. Otherwise we also considered to just use Linux with Preempt-RT for real-time compatability. I can also recommed https://github.com/yixuan/MiniDNN for building DNN in RTOS. It works fine on QNX since it just uses c++98 and is header only so you can simply cross-compile with plain cmake without the python dependencies such as Python3's PyYAML package that you need for compiling libtorch. (See the updated documentation file: https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst)
