### ISSUE TITLE
[JIT] state[input] != State::Unknown ASSERT FAILED at /pytorch/torch/csrc/jit/passes/specialize_autogradzero.cpp:57

### ISSUE THREAD

**Issue by YashSinha1996** [pytorch/pytorch#17962]
## 🐛 Bug
```
state[input] != State::Unknown ASSERT FAILED at /pytorch/torch/csrc/jit/passes/specialize_autogradzero.cpp:57, please report a bug to PyTorch.
```
Assert failing when trying to train a pytorch model where only a part of the model is JIT traced. 
Forward works without a hitch, backward gives this error
## To Reproduce

Refer: https://github.com/huggingface/pytorch-pretrained-BERT
Install: `pip install pytorch-pretrained-bert`

```
from pytorch_pretrained_bert.modeling import BertPreTrainedModel, BertEmbeddings, BertEncoder, BertPooler


class BertModel(BertPreTrainedModel):
    def __init__(self, config):
        super(BertModel, self).__init__(config)
        self.embeddings = BertEmbeddings(config)
        self.encoder = BertEncoder(config)
        self.pooler = BertPooler(config)
        self.apply(self.init_bert_weights)

    def forward(self, input_ids, token_type_ids, attention_mask):

        extended_attention_mask = attention_mask.unsqueeze(1).unsqueeze(2)

        extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype) # fp16 compatibility
        extended_attention_mask = (1.0 - extended_attention_mask) * -10000.0

        embedding_output = self.embeddings(input_ids, token_type_ids)
        encoded_layers = self.encoder(embedding_output,
                                      extended_attention_mask,
                                      output_all_encoded_layers=True)
        sequence_output = encoded_layers[-1]
        pooled_output = self.pooler(sequence_output)

        return tuple([tuple(encoded_layers), pooled_output])


class BertForPreTraining(BertPreTrainedModel):
    def __init__(self, config):
        super(BertForPreTraining, self).__init__(config)
        self.bert = BertModel(config)
        self.traced_bert = self.bert

        self.cls = BertPreTrainingHeads(config, self.bert.embeddings.word_embeddings.weight)
        self.apply(self.init_bert_weights)
        self.traced = False

    def trace_bert(self, input_ids, token_type_ids, attention_mask):
        if attention_mask is None:
            attention_mask = torch.ones_like(input_ids)
        if token_type_ids is None:
            token_type_ids = torch.zeros_like(input_ids)

        if not self.traced:
            self.traced_bert = torch.jit.trace(self.bert, tuple([input_ids, token_type_ids, attention_mask]))
            self.traced = True

        sequence_output, pooled_output = self.traced_bert(input_ids, token_type_ids, attention_mask)
        return sequence_output, pooled_output



    def forward(self, input_ids, token_type_ids=None, attention_mask=None, masked_lm_labels=None, next_sentence_label=None):
        sequence_output_all, pooled_output = self.trace_bert(input_ids, token_type_ids, attention_mask)
        sequence_output = sequence_output_all[-1]

        prediction_scores, seq_relationship_score = self.cls(sequence_output, pooled_output)

        if masked_lm_labels is not None and next_sentence_label is not None:
            loss_fct = CrossEntropyLoss(ignore_index=-1)
            masked_lm_loss = loss_fct(prediction_scores.view(-1, self.config.vocab_size), masked_lm_labels.view(-1))
            next_sentence_loss = loss_fct(seq_relationship_score.view(-1, 2), next_sentence_label.view(-1))
            total_loss = masked_lm_loss + next_sentence_loss
            return total_loss
        else:
            return prediction_scores, seq_relationship_score
```

Training:
```
model = BertForPreTraining.from_pretrained('path_to_pretrained_model')
loss = model(input_ids, token_type_ids, attention_mask, lm_labels, next_sent)
loss.backward()
```

## Expected behavior
Training on this kind of model would be nice

## Environment
 - PyTorch Version (e.g., 1.0): 1.0.0.dev20190312
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.5
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

## Additional context
I believe this is because during autograd it has no knowledge of the state of the input tensors? 
Sorry for any mistakes, Newbie at pytorch.

**Comment by suo** [comment]
@ailzhang would you have any insight here?

**Comment by ailzhang** [comment]
This might be related to the undef -> autogradzero, cc @wanchaol do you have any idea what could be happening?

**Comment by wanchaol** [comment]
that undef -> autogradzero is just a rename that it should not affect any semantics before/after. @YashSinha1996 can you provide a fully reproduciable script? I tried the above thing and it does not work because of missing inputs (like input_ids, attention_mask, etc.)

**Comment by YashSinha1996** [comment]
@wanchaol Sure. Using 
https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_lm_finetuning.py as base, replace the the line

**Comment by YashSinha1996** [comment]
@wanchaol Any progress in tracking down this issue?

**Comment by wanchaol** [comment]
So it gives me this error:

```
Traceback (most recent call last):
  File "bad_pytorch_example.py", line 652, in <module>
    main()
  File "bad_pytorch_example.py", line 533, in main
    model = BertForPreTraining.from_pretrained(args.bert_model)
  File "/private/home/wanchaol/.conda/envs/pt/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 581, in from_pretrained
    model = cls(config, *inputs, **kwargs)
  File "/private/home/wanchaol/temp/bert/modeling_trace.py", line 35, in __init__
    self.cls = BertPreTrainingHeads(config, self.bert.embeddings.word_embeddings.weight)
NameError: name 'BertPreTrainingHeads' is not defined
```

is this class defined somewhere else?

**Comment by YashSinha1996** [comment]
@wanchaol My bad that class was also supposed to be imported. I have updated the gist. Hope this helps.

**Comment by nict-wisdom** [comment]
@wanchaol @YashSinha1996
I reproduced the error with a much simpler model.
The complete executable source code is shown below.

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(64, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = x.contiguous()  # INSERTED
        return F.log_softmax(x, dim=1)

m = Net()
x = torch.randn(64, 1, 28, 28, requires_grad=True)
traced_net = torch.jit.trace(m, x)
traced_output = traced_net(x)
tgt = torch.randn(traced_output.size())
traced_output.backward(tgt)
```

This program will give you an error:

> Traceback (most recent call last):
  File "reproduce_17962.py", line 30, in <module>
    traced_output.backward(tgt)
 ...
RuntimeError: state[input] != State::Unknown ASSERT FAILED at ../torch/csrc/jit/passes/specialize_autogradzero.cpp:71, please report a bug to PyTorch.

I ran it with 1.1.0a0+a3933b8, which I built from the source. Note that the line number may be different from the original because I added some debug logging codes.

The model is the one in 
https://github.com/pytorch/examples/blob/master/mnist/main.py
but I just inserted 

`x = x.contiguous()`

The graph shown below is the differential graph for backward propagation which is passed to specializeAutogradZero(). An assertion in specializeAutogradZero() checks the validity of inputs of prim::GradOf[name="aten::add"] and throws an error because the input is None.
I guess something goes wrong with the differentiation with contiguous().

```
graph(%0 : Float(*, *),
      %1 : AutogradZeroTensor,
...
      %20 : Float(*, *)):
  %21 : int = prim::Constant[value=0]()
  %22 : None = prim::Constant()
  %23 : int = prim::Constant[value=1]()
  %24 : int[] = prim::Constant[value=[2, 2]]()
  %25 : int[] = prim::Constant[value=[0, 0]]()
  %26 : int[] = prim::Constant[value=[1, 1]]()
  %27 : bool = prim::Constant[value=0]()
  %29 : Tensor = aten::_log_softmax_backward_data(%0, %20, %23, %input)
  %32 : Tensor, %33 : Tensor = prim::GradOf[name="aten::add"](%22)
    block0():
      %34 : Tensor = aten::_grad_sum_to_size(%22, %17)
      %35 : Tensor = aten::mul(%22, %23)
      %36 : Tensor = aten::_grad_sum_to_size(%35, %18)
      -> (%34, %36)
...
```

**Comment by nict-wisdom** [comment]
@YashSinha1996

I also have been working on pytorch-pretrained-BERT.
I think that the error reported in this issue can be avoided by using reshape instead of contiguous and view. (But I'm not very sure because I'm a novice at pytorch.)

The modification could be
```
         context_layer = torch.matmul(attention_probs, value_layer)
-        context_layer = context_layer.permute(0, 2, 1, 3).contiguous()
+        context_layer = context_layer.permute(0, 2, 1, 3)
         new_context_layer_shape = context_layer.size()[:-2] + (self.all_head_size,)
-        context_layer = context_layer.view(*new_context_layer_shape)
+        context_layer = context_layer.reshape(*new_context_layer_shape)
         return context_layer
```
in pytorch_pretrained_bert/modeling.py

**Comment by wanchaol** [comment]
@nict-wisdom Thanks for providing a simpler reproducable model! We found the problem of `contiguous` and will submit a PR soon to fix it

**Comment by YashSinha1996** [comment]
@nict-wisdom Thanks a lot for looking into it, your suggestion worked!
