### ISSUE TITLE
librosa tests on Windows don't work

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#17981]
llvmlite fails with:

```
15:21:44 Collecting llvmlite>=0.27.0dev0 (from numba>=0.38.0->librosa>=0.6.2)
15:21:44   Downloading https://files.pythonhosted.org/packages/31/6a/2af9e150c053c194c751060b904ce9bdbb588ae3c6ce95569f95a2004884/llvmlite-0.27.1.tar.gz (104kB)
15:21:44 Building wheels for collected packages: librosa, audioread, resampy, numba, llvmlite
15:21:44   Building wheel for librosa (setup.py): started
15:21:45   Building wheel for librosa (setup.py): finished with status 'done'
15:21:45   Stored in directory: C:\Windows\system32\config\systemprofile\AppData\Local\pip\Cache\wheels\ce\49\68\87ba660f30e3977f0778e39ee2e944629cd37c2a0ce41f9ff1
15:21:45   Building wheel for audioread (setup.py): started
15:21:45   Building wheel for audioread (setup.py): finished with status 'done'
15:21:45   Stored in directory: C:\Windows\system32\config\systemprofile\AppData\Local\pip\Cache\wheels\53\02\90\7b5c4081b7470c550ab605f600bad237dde12a6b8999b11f50
15:21:45   Building wheel for resampy (setup.py): started
15:21:46   Building wheel for resampy (setup.py): finished with status 'done'
15:21:46   Stored in directory: C:\Windows\system32\config\systemprofile\AppData\Local\pip\Cache\wheels\ff\4f\ed\2e6c676c23efe5394bb40ade50662e90eb46e29b48324c5f9b
15:21:46   Building wheel for numba (setup.py): started
15:22:16   Building wheel for numba (setup.py): finished with status 'done'
15:22:16   Stored in directory: C:\Windows\system32\config\systemprofile\AppData\Local\pip\Cache\wheels\15\8d\95\6934f30194127da1befe0089e8f7e0aea0e8ce7d9bbda71ecf
15:22:16   Building wheel for llvmlite (setup.py): started
15:22:40   Building wheel for llvmlite (setup.py): finished with status 'error'
15:22:40   Complete output from command C:\Jenkins\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Windows\\TEMP\\pip-install-n4q6l4i8\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Windows\TEMP\pip-wheel-dkyrfd28 --python-tag cp36:
15:22:40   running bdist_wheel
15:22:40   C:\Jenkins\Miniconda3\python.exe C:\Windows\TEMP\pip-install-n4q6l4i8\llvmlite\ffi\build.py
15:22:40   -- The C compiler identification is MSVC 19.0.24215.1
15:22:40   -- The CXX compiler identification is MSVC 19.0.24215.1
15:22:40   -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
15:22:40   -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
15:22:40   -- Detecting C compiler ABI info
15:22:40   -- Detecting C compiler ABI info - done
15:22:40   -- Detecting C compile features
15:22:40   -- Detecting C compile features - done
15:22:40   -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
15:22:40   -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
15:22:40   -- Detecting CXX compiler ABI info
15:22:40   -- Detecting CXX compiler ABI info - done
15:22:40   -- Detecting CXX compile features
15:22:40   -- Detecting CXX compile features - done
15:22:40   -- Configuring done
15:22:40   -- Generating done
15:22:40   -- Build files have been written to: C:/Windows/Temp/tmpcclobwp4
15:22:40   -- The C compiler identification is MSVC 19.0.24215.1
15:22:40   -- The CXX compiler identification is MSVC 19.0.24215.1
15:22:40   -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
15:22:40   -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
15:22:40   -- Detecting C compiler ABI info
15:22:40   -- Detecting C compiler ABI info - done
15:22:40   -- Detecting C compile features
15:22:40   -- Detecting C compile features - done
15:22:40   -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
15:22:40   -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
15:22:40   -- Detecting CXX compiler ABI info
15:22:40   -- Detecting CXX compiler ABI info - done
15:22:40   -- Detecting CXX compile features
15:22:40   -- Detecting CXX compile features - done
15:22:40   CMake Error at CMakeLists.txt:9 (find_package):
15:22:40     Could not find a package configuration file provided by "LLVM" with any of
15:22:40     the following names:
15:22:40   
15:22:40       LLVMConfig.cmake
15:22:40       llvm-config.cmake
15:22:40   
15:22:40     Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
15:22:40     "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
15:22:40     provides a separate development package or SDK, be sure it has been
15:22:40     installed.
15:22:40   
15:22:40   
15:22:40   -- Configuring incomplete, errors occurred!
15:22:40   See also "C:/Windows/Temp/pip-install-n4q6l4i8/llvmlite/ffi/build/CMakeFiles/CMakeOutput.log".
15:22:40   Trying generator 'Visual Studio 14 2015 Win64'
15:22:40   Traceback (most recent call last):
15:22:40     File "C:\Windows\TEMP\pip-install-n4q6l4i8\llvmlite\ffi\build.py", line 167, in <module>
15:22:40       main()
15:22:40     File "C:\Windows\TEMP\pip-install-n4q6l4i8\llvmlite\ffi\build.py", line 155, in main
15:22:40       main_win32()
15:22:40     File "C:\Windows\TEMP\pip-install-n4q6l4i8\llvmlite\ffi\build.py", line 93, in main_win32
15:22:40       try_cmake(here_dir, build_dir, generator)
15:22:40     File "C:\Windows\TEMP\pip-install-n4q6l4i8\llvmlite\ffi\build.py", line 28, in try_cmake
15:22:40       subprocess.check_call(['cmake', '-G', generator, cmake_dir])
15:22:40     File "C:\Jenkins\Miniconda3\lib\subprocess.py", line 291, in check_call
15:22:40       raise CalledProcessError(retcode, cmd)
15:22:40   subprocess.CalledProcessError: Command '['cmake', '-G', 'Visual Studio 14 2015 Win64', 'C:\\Windows\\TEMP\\pip-install-n4q6l4i8\\llvmlite\\ffi']' returned non-zero exit status 1.
15:22:40   error: command 'C:\\Jenkins\\Miniconda3\\python.exe' failed with exit status 1
15:22:40   
```

This didn't use to fail prior to Mar 12 but I couldn't find any package upgrades in the interim which would have caused the problem (librosa, numba, llvmlite and pip didn't have updates on Mar 12). 

I could probably fix this by installing LLVM but this seems a bit overkill, and I'm not sure we actually care about this test.

CC @SsnL who added the librosa stuff initially. Do you think we should make this work on Windows again?

**Comment by peterjc123** [comment]
I'm now fixing it with `conda install numba`, which will also install llvmlite.

**Comment by SsnL** [comment]
This is intriguing. I'm fine with skipping on Windows, but if conda install numba is a simple fix, we can go for it.

**Comment by SsnL** [comment]
Thanks @peterjc123 !

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/pull/17954

**Comment by peterjc123** [comment]
landed into master. closing.
