### ISSUE TITLE
nn.CrossEntropyLoss() Assertion `t >= 0 && t < n_classes` failed

### ISSUE THREAD

**Issue by yangchengtest** [pytorch/pytorch#18014]
System:Ubuntu 16.04
Version:1.0.1.post2
python version:3.5

my code:
criterion = nn.CrossEntropyLoss().cuda(gpu)
print (pre_yaw.data)
print (pre_yaw.size())
print (label_yaw.size())
print (label_yaw.data)
loss_yaw = criterion(pre_yaw, label_yaw)

## this line error:
print(loss_yaw.data)

//pre_yaw size
torch.Size([16, 66])
//label_yaw size
torch.Size([16])
//label_yaw
tensor([ 5, 26, 45, 37,  5, 59, 42, 51, 39,  3, 43, 49, 55, 30, 29, 29],
       device='cuda:0')
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train_alexnet.py", line 166, in <module>
    print(loss_yaw.data)
  File "/home/vdo/.local/lib/python3.5/site-packages/torch/tensor.py", line 66, in __repr__
    return torch._tensor_str._str(self)
  File "/home/vdo/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 277, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/vdo/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 195, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/vdo/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 84, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317

all label_yaw are between 0 to 65.I don't know why there is an error.
Thanks.

**Comment by yangchengtest** [comment]
I have same data out of range.
The print function maybe delay...
