### ISSUE TITLE
copy.copy not working for ScriptModule

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#18106]
The following code does not work

```python
import torch
import copy

class M(torch.jit.ScriptModule):

    @torch.jit.script_method
    def forward(self, x):
        return x

m = M()
copy.copy(m)
```

Error message:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    copy.copy(m)
  File "/usr/lib/python3.7/copy.py", line 96, in copy
    rv = reductor(4)
  File "/home/gaoxiang/.virtualenvs/pt/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in __getstate__
    "Mixed serialization of script and non-script modules is not supported. " +
_pickle.PickleError: ScriptModules cannot be saved using torch.save. Mixed serialization of script and non-script modules is not supported. For purely script modules use my_script_module.save(<filename>) instead.
```

Related: https://github.com/pytorch/pytorch/issues/17422

**Comment by Krovatkin** [comment]
@zasdfgbnm  

Would you advise us if the workaround below is sufficient for your use case or are you suggesting that we should fix `copy.copy`? 

FYI: @suo @driazati 

```python
import torch
class M(torch.jit.ScriptModule):

    @torch.jit.script_method
    def forward(self, x):
        return x

m = M()
m.save("my_model")
t = torch.rand(2)
print (m.forward(t))
m2 = torch.jit.load("my_model")
print (m2.forward(t))
```

**Comment by zasdfgbnm** [comment]
@Krovatkin Yes, I suggest fixing the `copy.copy`. The use case is, for example, when there is a third-party library depending on PyTorch, this behavior might make objects in that library uncopyable:

```python
import torch
import copy


class MyComputerVisionModel(torch.jit.ScriptModule):

    @torch.jit.script_method
    def forward(self, x):
        return x


class MyImageProcessingLibrary:

    def __init__(self):
        self.model = MyComputerVisionModel()

    def something(self, *args):
        do_something_with_model(self.model, *args)


something = MyImageProcessingLibrary()
copy.deepcopy(something)
```

**Comment by Coderx7** [comment]
Any update on this? its been more than a year now!
@zasdfgbnm this is exactly the issue we are having right now! we cant use deepcopy becasue of this.

**Comment by Krovatkin** [comment]
cc: @suo

**Comment by suo** [comment]
This should be implemented, @jerryzh168 did this make the last release?

**Comment by jerryzh168** [comment]
No, I haven't get to python level functions, right now only the C++ functions are implemented. we can expose `copy.copy` now, but `copy.deepcopy` will need some work

**Comment by shalgi-beyond** [comment]
still trying to understand whether there's a workaround for this

**Comment by jerryzh168** [comment]
Right now we have two functions implemented on the underlying `cpp_module`(`m._c`) of the RecursiveScriptModule,
- `copy`, which is the shallow copy the the `cpp_module`, it creates a new object without copying the underlying data
- `deepcopy`, which is the deepcopy of the `cpp_module`, it creates a new object as well as deep copy ing the underlying data, including Tensor etc.

However both of them are only implemented in the c++ module, not in the python level. 

For `copy.copy` it is ready now, we can expose them in python by defining a `__copy__` in `RecursiveScriptModule`. 
We can do
```python
m = wrap_cpp_module(m._c.copy())
```
right now, but this can be exposed to python in `__copy__` method of `RecursiveScriptModule` so that people can just do `copy.copy(m)`

For `copy.deepcopy`, it's not implemented in python, so there is no workaround right now if you want to do the deepcopy in python(meaning if you want to copy the script module as part of some other python object or script module contains some other python object you also want to deepcopy), if you just want to deep copy the underlying `cpp_module`, then you can do this with:
```python
m = wrap_cpp_module(m._c.deepcopy())
```

**Comment by jerryzh168** [comment]
Since https://github.com/pytorch/pytorch/pull/40068 is landed, maybe you can try `copy.deepcopy` now

**Comment by jerryzh168** [comment]
https://github.com/pytorch/pytorch/pull/32685 is the PR that supports both `copy.copy` and `copy.deepcopy`, please try again to see if it works

**Comment by chenbohua3** [comment]
@jerryzh168 Nice work!  BTW, is there any plans to enable` __getstate__` [here](https://github.com/pytorch/pytorch/blob/6468bc4/torch/jit/__init__.py#L2078-L2082)？

We are trying to use **jit quantization observer** to calculate quantization scales **on torchscript level** and found it is too slow to calculate qparams. So we turn to use `multiprocessing` to accelerate that process. But we found it failed when we pass `torch.jit.RecursiveScriptModule` to each process because it does not have implementation of ` __getstate__`.

**Comment by jerryzh168** [comment]
> @jerryzh168 Nice work! BTW, is there any plans to enable` __getstate__` [here](https://github.com/pytorch/pytorch/blob/6468bc4/torch/jit/__init__.py#L2078-L2082)？
> 
> We are trying to use **jit quantization observer** to calculate quantization scales **on torchscript level** and found it is too slow to calculate qparams. So we turn to use `multiprocessing` to accelerate that process. But we found it failed when we pass `torch.jit.RecursiveScriptModule` to each process because it does not have implementation of ` __getstate__`.

cc @suo @zdevito @jamesr66a for `__getstate__` questions.

We are working on speeding up Histogram observer, @raghuramank100 @supriyar can you share the current status?

**Comment by supriyar** [comment]
> We are working on speeding up Histogram observer, @raghuramank100 @supriyar can you share the current status?

We are just getting started on the work to speed up histogram observer, initially focusing on speeding up the convert step in the quantization workflow, specifically the `_non_linear_param_search` function in `calculate_qparams`.

**Comment by Linux-cpp-lisp** [comment]
Seems like mixed serialization is still an open question (this issue and [another here](https://github.com/pytorch/pytorch/issues/15116#issuecomment-557228562), for example).

Is there any news on removing the raise in `__getstate__`? (@suo @jamesr66a @zdevito given the above CCs?) I've done some testing, and unless I'm missing something fundamental the solution is quite simple using `__reduce__` from the pickling API:
```python
In [1]: import torch

In [2]: import io, types

In [3]: def reduce(self):
   ...:     print("boo")
   ...:     buf = io.BytesIO()
   ...:     torch.jit.save(self, buf)
   ...:     return (loader, (buf.getvalue(),), None)
   ...: 

In [4]: def loader(b):
   ...:     print("hi")
   ...:     buf = io.BytesIO(b)
   ...:     return torch.jit.load(buf)
   ...: 

In [5]: del torch.jit.RecursiveScriptModule.__getstate__

In [6]: torch.jit.RecursiveScriptModule.__reduce__ = reduce

In [7]: m = torch.jit.script(torch.nn.Linear(3, 4))

In [8]: inp = torch.randn(3)

In [9]: m(inp)
Out[9]: tensor([ 1.1392,  0.2431, -0.5255,  0.2338], grad_fn=<AddBackward0>)

In [10]: torch.save(m, "tmp.pth")
boo

In [11]: m2 = torch.load("tmp.pth")
hi

In [12]: m2(inp)
Out[12]: tensor([ 1.1392,  0.2431, -0.5255,  0.2338], grad_fn=<AddBackward0>)

In [13]: m2
Out[13]: RecursiveScriptModule(original_name=Linear)
```
An uglier alternative I've used to avoid monkey-patching `RecursiveScriptModule` is:

- Removing the current `RecursiveScriptModule`'s `__getstate__` to avoid the error
- `torch.jit.save`ing the `RecursiveScriptModule` to a `bytes` in its parent's `__getstate__`
- `torch.jit.load`ing those `bytes` in the parent's `__setstate__`

You can see this in some of my code here: https://github.com/e3nn/e3nn/pull/262/commits/6a39e48ae279f88f2f62ca469efa81b74ea6385f

Would the devs be open to adding this sort of mixed serialization support through `__reduce__`? I would be happy to help if that would be at all useful.

Thanks!

**Comment by cxhernandez** [comment]
Has there been any update on this? We've also been hitting a this issue in multi-GPU training of serialized models.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
