### ISSUE TITLE
Indices of a Dataloader of a custom dataset class have type numpy.int64 type is causing an error

### ISSUE THREAD

**Issue by morawi** [pytorch/pytorch#18130]
## 🐛 Bug
To get around the problem, I had to use (inside the Dataset class):

```

def __getitem__(self, index):
index = int(index)
...
...
```

```
PyTorch 0.4
Python 3.6

```

**Comment by SsnL** [comment]
what's the error message?

**Comment by morawi** [comment]
@SsnL  Using debug mode, I noticed the issue with the indices having numpy.int64 type. Not sure why this happens here, although it has not been the case in several other programs I did! 
```
line 89, in test
    for data, target, word_str, weight in test_loader: 

  File "/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)

  File "/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)

TypeError: Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/load_imdb_dataset.py", line 253, in __getitem__
    img, word_str = self.get_sample(index)
  File "/datasets/load_imdb_dataset.py", line 244, in get_sample
    sentiment = self.data[index]['sentiment']
  File "/anaconda3/lib/python3.6/site-packages/torchnlp/datasets/dataset.py", line 48, in __getitem__
    raise TypeError('Invalid argument type.')
TypeError: Invalid argument type.
```

**Comment by SsnL** [comment]
You probably used a custom sampler that is causing the problem.

**Comment by morawi** [comment]
@SsnL No, I have not. Here is where the problem occurse

```
def get_sample(self, index):                
        sentiment = self.data[index]['sentiment'] 
        sentiment = 'negative.135' if  sentiment=='neg' else  'posative.792'  # the hashing number is added to be identified from other keywords in other datasets                     
                         
        return  sentiment    

 def __getitem__(self, index):
        index = int(index)       ''' The tweak that resolved the problem '''
        img, word_str = self.get_sample(index)        
        ToPIL = transforms.ToPILImage()   
        img = ToPIL(img)
```

**Comment by morawi** [comment]
@SsnL  So, could it be that `sample_idx` is causing the problem?

**Comment by SsnL** [comment]
Your sampler is returning an `np.int64`, this is normally not a problem but your dataset doesn't accept a value of that type. Since you control both the sampler and the dataset, I think that this isn't a pytorch problem.
