### ISSUE TITLE
download_mnist.py causes flaky tests

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#18451]
Trace observed in [this build](https://circleci.com/gh/pytorch/pytorch/1049822?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
Mar 25 18:22:52 + python tools/download_mnist.py --quiet -d test/cpp/api/mnist
Mar 25 18:22:58 Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz ...
Mar 25 18:22:58 Traceback (most recent call last):
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/urllib/request.py", line 1318, in do_open
Mar 25 18:22:58     encode_chunked=req.has_header('Transfer-encoding'))
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
Mar 25 18:22:58     self._send_request(method, url, body, headers, encode_chunked)
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
Mar 25 18:22:58     self.endheaders(body, encode_chunked=encode_chunked)
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
Mar 25 18:22:58     self._send_output(message_body, encode_chunked=encode_chunked)
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
Mar 25 18:22:58     self.send(msg)
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
Mar 25 18:22:58     self.connect()
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/http/client.py", line 936, in connect
Mar 25 18:22:58     (self.host,self.port), self.timeout, self.source_address)
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/socket.py", line 704, in create_connection
Mar 25 18:22:58     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
Mar 25 18:22:58   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
Mar 25 18:22:58     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Mar 25 18:22:58 socket.gaierror: [Errno -2] Name or service not known
```

Perhaps we should reconsider network dependencies in tests, or at least re-host this data in a more stable location.

**Comment by kostmo** [comment]
Here's [another failure](https://circleci.com/gh/pytorch/pytorch/1051020?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
Mar 25 19:36:53 + git clone https://github.com/pytorch/examples.git -b perftests
Mar 25 19:36:53 Testing: MNIST, GPU
Mar 25 19:36:53 Cloning into 'examples'...
Mar 25 19:36:58 + cd examples/mnist
Mar 25 19:36:58 + pip install -q -r requirements.txt
Mar 25 19:36:59 + python main.py --epochs 0
Mar 25 19:37:06 Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ../data/MNIST/raw/train-images-idx3-ubyte.gz
Mar 25 19:37:06 Extracting ../data/MNIST/raw/train-images-idx3-ubyte.gz
Mar 25 19:37:06 Traceback (most recent call last):
Mar 25 19:37:06   File "main.py", line 42, in <module>
Mar 25 19:37:06     transforms.Normalize((0.1307,), (0.3081,))
Mar 25 19:37:06   File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 68, in __init__
Mar 25 19:37:06     self.download()
Mar 25 19:37:06   File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 144, in download
Mar 25 19:37:06     self.extract_gzip(gzip_path=file_path, remove_finished=True)
Mar 25 19:37:06   File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 125, in extract_gzip
Mar 25 19:37:06     gzip.GzipFile(gzip_path) as zip_f:
Mar 25 19:37:06   File "/opt/conda/lib/python3.6/gzip.py", line 163, in __init__
Mar 25 19:37:06     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
Mar 25 19:37:06 FileNotFoundError: [Errno 2] No such file or directory: '../data/MNIST/raw/train-images-idx3-ubyte.gz'
```

**Comment by kostmo** [comment]
CC @ezyang @pjh5

**Comment by pjh5** [comment]
@ezyang did we get rid of this retry function https://github.com/pytorch/pytorch/blob/master/.circleci/config.yml#L630 ? It's a quick stopgap that helps in most cases.

**Comment by ezyang** [comment]
@pjh5 No, I don't think we got rid of it. It's just not uniformly applied in all the places it could help at.

**Comment by huydhn** [comment]
I'm closing this issue now as it's quite old.  The script is still in used, but it doesn't cause any issue for a long time AFAIK.
