### ISSUE TITLE
TestJitGeneratedModule.test_nn_Linear_no_bias occasional segfaults

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#18456]
```
Mar 25 22:31:57 test_nn_Linear_no_bias (__main__.TestJitGeneratedModule) ... Traceback (most recent call last):
Mar 25 22:31:57   File "test/run_test.py", line 457, in <module>
Mar 25 22:31:57     main()
Mar 25 22:31:57   File "test/run_test.py", line 449, in main
Mar 25 22:31:57     raise RuntimeError(message)
Mar 25 22:31:57 RuntimeError: test_jit failed! Received signal: SIGSEGV
Mar 25 22:31:57 + cleanup
```

log https://circleci.com/gh/pytorch/pytorch/1054782?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by suo** [comment]
@driazati I suspect this is similar to the problems noted with #18667

**Comment by driazati** [comment]
Closing since I haven't seen this recently but there was no real resolution so feel free to re-open if it happens again
