### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kefirski** [pytorch/pytorch#1846]
I am trying to train [this](https://github.com/analvikingur/CDVAE) model by 
`python train.py --use-cuda True --dropout 0.25 --batch-size 7 --num-iterations 2000000`

after several iterations (~16k) on my 8GB GPU I've got

```
THCudaCheck FAIL file=/data/users/soumith/builder/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    print(cdvae.translate(input, ['ru', 'ru'], batch_loader))
  File "/home/py36/CDVAE/model/cdvae.py", line 97, in translate
    return model_to.sample(bl, encoder_input.size()[1], encoder_input.is_cuda, z)
  File "/home/py36/CDVAE/model/vae/vae.py", line 115, in sample
    x, state, _, _ = self(0., None, x, z, state)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/py36/CDVAE/model/vae/vae.py", line 63, in forward
    out, final_state = self.generate(decoder_input, z, drop_prob, initial_state)
  File "/home/py36/CDVAE/model/vae/vae.py", line 79, in generate
    return self.decoder(decoder_input, z, initial_state)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/py36/CDVAE/model/vae/decoder.py", line 48, in forward
    result, final_state = self.rnn(decoder_input, initial_state)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 327, in forward
    return func(input, *fargs, **fkwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/function.py", line 201, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/function.py", line 223, in forward
    result = self.forward_extended(*nested_tensors)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 269, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/rnn.py", line 247, in forward
    fn.weight_buf = x.new(num_weights)
RuntimeError: cuda runtime error (2) : out of memory at /data/users/soumith/builder/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu:66
```

**Comment by analvikingur** [comment]
<img width="568" alt="2017-06-19 16 44 14" src="https://user-images.githubusercontent.com/8404265/27288345-232e0b88-550f-11e7-8d1b-d29981a86a53.png">
extra 528 MiB in GPU memory without any process on it

**Comment by apaszke** [comment]
I can take a look if you can isolate the code that leaks in a small snippet. It should be a standalone script so I can run it myself (e.g. use random tensors as input) and, as small as possible. 528MiB is probably because you have some processes that use up CUDA memory but aren't reported by nvidia-smi. Try running `killall python` or `killall python3` (if you don't have any other jobs/python scripts running)

**Comment by analvikingur** [comment]
[here](https://github.com/analvikingur/CDVAE/blob/master/leak/train.py) you can find standalone script of my model with random inputs.

Run it with argument `--use-cuda True`

**Comment by analvikingur** [comment]
Also, what about 528MiB –– they are still in GPU memory even after rebooting machine

**Comment by apaszke** [comment]
Then it's probably reserved for video memory (displaying stuff on your monitor)

**Comment by apaszke** [comment]
313 is still large, so it's going to take me a while to dissect the code. It would be super helpful if you managed to reduce the code to absolutely minimal size that still reproduces the leak (e.g. try to remove parts of the model as long as the leak persists).

**Comment by analvikingur** [comment]
I will try to reduce size of this snippet tomorrow

**Comment by soumith** [comment]
@kefirski just checking to see if you had a chance to reduce the size of the code. thank you!

**Comment by kefirski** [comment]
Oh, I forgot about this issue. 
I was trying to reproduce bug but realised that I have no memory leak
