### ISSUE TITLE
Error trying to convert to JitScript

### ISSUE THREAD

**Issue by emrul** [pytorch/pytorch#18528]
## 🐛 Bug

I'm hacking away at Flair (https://github.com/zalandoresearch/flair) to create a minimal script that can be jit'd via TorchScript and can run predictions.

I realise my work is not complete yet but I was iteratively working through the errors being reported until I received the following error:

> ASSERT FAILED at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.7/pytorch/torch/csrc/jit/ir.cpp:1387, please report a bug to PyTorch. (createList at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.7/pytorch/torch/csrc/jit/ir.cpp:1387)

## To Reproduce

1. Install Flair (pip install flair)
1. Refer to the 2 files in the gist here: https://gist.github.com/e/3644b54326794068d0f43e1fce4c1308
1. When trying to run try.py observe error that's thrown:

```

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
PyTorch Version:  1.0.1.post2
/Users/e/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/e/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/e/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/e/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/e/dev/***/flair/try_seq.py", line 25, in <module>
    tagger = ScriptSequenceTagger.load_from_file('resources/taggers/v001/best-model.pt')
  File "/Users/e/dev/***/flair/jit/ScriptSequenceTagger.py", line 157, in load_from_file
    locked_dropout=use_locked_dropout,
  File "/Users/e/anaconda3/envs/flair/lib/python3.7/site-packages/torch/jit/__init__.py", line 952, in init_then_register
    _create_methods_from_stubs(self, methods)
  File "/Users/e/anaconda3/envs/flair/lib/python3.7/site-packages/torch/jit/__init__.py", line 913, in _create_methods_from_stubs
    self._create_methods(defs, rcbs, defaults)
RuntimeError: v->type()->isSubtypeOf(elem_type) ASSERT FAILED at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.7/pytorch/torch/csrc/jit/ir.cpp:1387, please report a bug to PyTorch. (createList at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.7/pytorch/torch/csrc/jit/ir.cpp:1387)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 64 (0x11d465fc0 in libc10.dylib)
frame #1: torch::jit::Graph::createList(std::__1::shared_ptr<c10::Type> const&, c10::ArrayRef<torch::jit::Value*>) + 562 (0x11dc66752 in libtorch.1.dylib)
frame #2: torch::jit::script::tryCreateList(std::__1::shared_ptr<c10::Type>, torch::jit::Graph&, torch::jit::SourceRange const&, c10::ArrayRef<torch::jit::NamedValue>, std::__1::function<std::__1::basic_ostream<char, std::__1::char_traits<char> >& ()>, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<c10::Type>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<c10::Type> > > >&) + 796 (0x11dd4b03c in libtorch.1.dylib)
frame #3: torch::jit::script::tryMatchSchema(c10::FunctionSchema const&, torch::jit::SourceRange const&, torch::jit::Graph&, c10::optional<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool) + 4704 (0x11dd4c480 in libtorch.1.dylib)
frame #4: torch::jit::script::emitBuiltinCall(torch::jit::SourceRange const&, torch::jit::Graph&, c10::Symbol, c10::optional<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, bool) + 648 (0x11dd4d538 in libtorch.1.dylib)
frame #5: torch::jit::script::BuiltinFunction::call(torch::jit::SourceRange, torch::jit::script::Method&, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, unsigned long) + 157 (0x11dd4e75d in libtorch.1.dylib)
frame #6: torch::jit::script::to_ir::emitApplyExpr(torch::jit::script::Apply&, unsigned long) + 4523 (0x11dd81b1b in libtorch.1.dylib)
frame #7: torch::jit::script::to_ir::emitSugaredExpr(torch::jit::script::Expr, unsigned long, std::__1::shared_ptr<c10::Type>) + 513 (0x11dd6b771 in libtorch.1.dylib)
frame #8: torch::jit::script::to_ir::emitExpr(torch::jit::script::Expr, std::__1::shared_ptr<c10::Type>) + 96 (0x11dd6dff0 in libtorch.1.dylib)
frame #9: torch::jit::script::to_ir::emitLoopCommon(torch::jit::SourceRange, c10::optional<torch::jit::script::Expr>, c10::optional<torch::jit::script::Expr>, torch::jit::script::List<torch::jit::script::Stmt> const&, c10::optional<torch::jit::script::Ident>) + 219 (0x11dd70e2b in libtorch.1.dylib)
frame #10: torch::jit::script::to_ir::emitForRange(torch::jit::SourceRange, torch::jit::script::Ident const&, torch::jit::script::List<torch::jit::script::Expr> const&, torch::jit::script::List<torch::jit::script::Stmt> const&) + 264 (0x11dd73e28 in libtorch.1.dylib)
frame #11: torch::jit::script::to_ir::emitFor(torch::jit::script::For const&) + 1806 (0x11dd693ae in libtorch.1.dylib)
frame #12: torch::jit::script::to_ir::emitStatements(torch::jit::script::ListIterator<torch::jit::script::Stmt>, torch::jit::script::ListIterator<torch::jit::script::Stmt>) + 449 (0x11dd5d811 in libtorch.1.dylib)
frame #13: torch::jit::script::to_ir::to_ir(torch::jit::script::Def, std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::shared_ptr<torch::jit::script::SugaredValue>, torch::jit::script::Method&) + 1540 (0x11dd5af04 in libtorch.1.dylib)
frame #14: std::__1::__function::__func<torch::jit::script::defineMethodsInModule(std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::allocator<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)> > > const&, std::__1::shared_ptr<torch::jit::script::SugaredValue>)::$_7, std::__1::allocator<torch::jit::script::defineMethodsInModule(std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::allocator<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)> > > const&, std::__1::shared_ptr<torch::jit::script::SugaredValue>)::$_7>, void (torch::jit::script::Method&)>::operator()(torch::jit::script::Method&) + 218 (0x11dd5a65a in libtorch.1.dylib)
frame #15: torch::jit::script::Method::ensure_defined() + 191 (0x11a4cef4f in libtorch_python.dylib)
frame #16: torch::jit::script::try_emit_call_to(torch::jit::Graph&, torch::jit::SourceRange, torch::jit::script::Method&, c10::optional<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, torch::jit::script::Method*, bool) + 51 (0x11a4ce7b3 in libtorch_python.dylib)
frame #17: torch::jit::script::Method::emit_call_to(torch::jit::SourceRange, torch::jit::script::Method&, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>) + 494 (0x11a4cf22e in libtorch_python.dylib)
frame #18: torch::jit::script::MethodValue::call(torch::jit::SourceRange, torch::jit::script::Method&, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, unsigned long) + 142 (0x11a4a8a3e in libtorch_python.dylib)
frame #19: torch::jit::script::to_ir::emitApplyExpr(torch::jit::script::Apply&, unsigned long) + 4523 (0x11dd81b1b in libtorch.1.dylib)
frame #20: torch::jit::script::to_ir::emitSugaredExpr(torch::jit::script::Expr, unsigned long, std::__1::shared_ptr<c10::Type>) + 513 (0x11dd6b771 in libtorch.1.dylib)
frame #21: torch::jit::script::to_ir::emitExpr(torch::jit::script::Expr, std::__1::shared_ptr<c10::Type>) + 96 (0x11dd6dff0 in libtorch.1.dylib)
frame #22: torch::jit::script::to_ir::emitIntAndSliceIndexing(torch::jit::SourceRange const&, torch::jit::Value*, torch::jit::script::List<torch::jit::script::Expr> const&) + 527 (0x11dd7763f in libtorch.1.dylib)
frame #23: torch::jit::script::to_ir::emitSubscriptAssign(torch::jit::SourceRange const&, torch::jit::script::Subscript const&, torch::jit::NamedValue const&) + 506 (0x11dd7600a in libtorch.1.dylib)
frame #24: torch::jit::script::to_ir::emitSubscriptAssign(torch::jit::SourceRange const&, torch::jit::script::Subscript const&, torch::jit::script::Expr const&) + 226 (0x11dd759a2 in libtorch.1.dylib)
frame #25: torch::jit::script::to_ir::emitAssignment(torch::jit::script::Assign const&) + 1385 (0x11dd6ad49 in libtorch.1.dylib)
frame #26: torch::jit::script::to_ir::emitStatements(torch::jit::script::ListIterator<torch::jit::script::Stmt>, torch::jit::script::ListIterator<torch::jit::script::Stmt>) + 266 (0x11dd5d75a in libtorch.1.dylib)
frame #27: torch::jit::script::to_ir::to_ir(torch::jit::script::Def, std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::shared_ptr<torch::jit::script::SugaredValue>, torch::jit::script::Method&) + 1540 (0x11dd5af04 in libtorch.1.dylib)
frame #28: std::__1::__function::__func<torch::jit::script::defineMethodsInModule(std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::allocator<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)> > > const&, std::__1::shared_ptr<torch::jit::script::SugaredValue>)::$_7, std::__1::allocator<torch::jit::script::defineMethodsInModule(std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::allocator<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)> > > const&, std::__1::shared_ptr<torch::jit::script::SugaredValue>)::$_7>, void (torch::jit::script::Method&)>::operator()(torch::jit::script::Method&) + 218 (0x11dd5a65a in libtorch.1.dylib)
frame #29: torch::jit::script::Method::ensure_defined() + 191 (0x11ddab88f in libtorch.1.dylib)
frame #30: torch::jit::script::defineMethodsInModule(std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::__1::allocator<std::__1::function<std::__1::shared_ptr<torch::jit::script::SugaredValue> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, torch::jit::script::Method&, torch::jit::SourceRange const&)> > > const&, std::__1::shared_ptr<torch::jit::script::SugaredValue>) + 2472 (0x11dd50ec8 in libtorch.1.dylib)
frame #31: void pybind11::cpp_function::initialize<torch::jit::script::initJitScriptBindings(_object*)::$_3, void, std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<pybind11::function (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)>, std::__1::allocator<std::__1::function<pybind11::function (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)> > > const&, std::__1::vector<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, pybind11::object, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, pybind11::object> > >, std::__1::allocator<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, pybind11::object, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, pybind11::object> > > > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(torch::jit::script::initJitScriptBindings(_object*)::$_3&&, void (*)(std::__1::shared_ptr<torch::jit::script::Module>, std::__1::vector<torch::jit::script::Def, std::__1::allocator<torch::jit::script::Def> > const&, std::__1::vector<std::__1::function<pybind11::function (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)>, std::__1::allocator<std::__1::function<pybind11::function (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)> > > const&, std::__1::vector<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, pybind11::object, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, pybind11::object> > >, std::__1::allocator<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, pybind11::object, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, pybind11::object> > > > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 855 (0x11a4b44c7 in libtorch_python.dylib)
frame #32: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3531 (0x11a105e8b in libtorch_python.dylib)
<omitting python frames>
frame #37: __pyx_f_18_pydevd_frame_eval_35pydevd_frame_evaluator_darwin_37_64_get_bytecode_while_frame_eval + 6619 (0x119ef937b in pydevd_frame_evaluator_darwin_37_64.cpython-37m-darwin.so)
frame #41: __pyx_f_18_pydevd_frame_eval_35pydevd_frame_evaluator_darwin_37_64_get_bytecode_while_frame_eval + 6619 (0x119ef937b in pydevd_frame_evaluator_darwin_37_64.cpython-37m-darwin.so)
frame #49: __pyx_f_18_pydevd_frame_eval_35pydevd_frame_evaluator_darwin_37_64_get_bytecode_while_frame_eval + 6619 (0x119ef937b in pydevd_frame_evaluator_darwin_37_64.cpython-37m-darwin.so)
frame #53: __pyx_f_18_pydevd_frame_eval_35pydevd_frame_evaluator_darwin_37_64_get_bytecode_while_frame_eval + 6619 (0x119ef937b in pydevd_frame_evaluator_darwin_37_64.cpython-37m-darwin.so)
frame #59: __pyx_f_18_pydevd_frame_eval_35pydevd_frame_evaluator_darwin_37_64_get_bytecode_while_frame_eval + 9522 (0x119ef9ed2 in pydevd_frame_evaluator_darwin_37_64.cpython-37m-darwin.so)

```

## Expected behavior

If I made a mistake somewhere then a more descriptive error message that allows me to continue to resolve the issue.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.3
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] pytorch-pretrained-bert==0.6.1
[pip] torch==1.0.1.post2
[conda] pytorch-pretrained-bert   0.6.1                    pypi_0    pypi
[conda] torch                     1.0.1.post2              pypi_0    pypi

**Comment by driazati** [comment]
The gist link provided 404s, could you update it?

**Comment by emrul** [comment]
Oops - not sure what happened there: https://gist.github.com/emrul/3644b54326794068d0f43e1fce4c1308 (once again, please ignore the poor code - I am trying to incrementally do this work and just figuring out things from the error messages I get)

**Comment by suo** [comment]
@wanchaol can you take a look?

**Comment by eellison** [comment]
I just ran your gist on master and did not get an error. @emrul please reopen if your issue is not resolved.
