### ISSUE TITLE
Gloo deadlock after upgrading CI to 418.40.04, 418.43 or 418.56 driver (410.104 is OK)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#18659]
In https://github.com/pytorch/pytorch/pull/18433 I am upgrading our AMI image to Ubuntu 16.04, to fix a CircleCI flakiness problem. The driver we were previously using (NVIDIA-Linux-x86_64-410.79) doesn't support the 16.04 kernel, so I did the following upgrades:

* Driver upgrade: 410.79 to 418.56
* Docker upgrade: `18.06.2~ce~3-0~ubuntu` to `5:18.09.4~3-0~ubuntu-xenial`
* nvidia-docker upgrade: 2.0.3+docker18.06.2-1 to 2.0.3+docker18.09.4-1

No changes were made to the CUDA/gloo toolchain. After the upgrade, the test `test_reduce_basics_cuda` reliably fails on CUDA 8 and CUDA 9.2

Sample logs:
* https://circleci.com/gh/pytorch/pytorch/1115381?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/1115384?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/1115365?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Error:

```
Mar 30 21:19:31 test_reduce_basics_cuda (__main__.ProcessGroupGlooTest) ... Process process 0:
Mar 30 21:19:31 Traceback (most recent call last):
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 30 21:19:31     self.run()
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 30 21:19:31     self._target(*self._args, **self._kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 470, in _run
Mar 30 21:19:31     getattr(self, self.id().split(".")[2])()
Mar 30 21:19:31   File "test_c10d.py", line 434, in wrapper
Mar 30 21:19:31     fn(self)
Mar 30 21:19:31   File "test_c10d.py", line 50, in wrapper
Mar 30 21:19:31     return func(*args, **kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 1141, in test_reduce_basics_cuda
Mar 30 21:19:31     self._test_reduce_basics(lambda t: t.clone().cuda())
Mar 30 21:19:31   File "test_c10d.py", line 1132, in _test_reduce_basics
Mar 30 21:19:31     work.wait()
Mar 30 21:19:31 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:72] Timed out waiting 1000ms for recv operation to complete
Mar 30 21:19:31 Process process 1:
Mar 30 21:19:31 Traceback (most recent call last):
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 30 21:19:31     self.run()
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 30 21:19:31     self._target(*self._args, **self._kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 470, in _run
Mar 30 21:19:31     getattr(self, self.id().split(".")[2])()
Mar 30 21:19:31   File "test_c10d.py", line 434, in wrapper
Mar 30 21:19:31     fn(self)
Mar 30 21:19:31   File "test_c10d.py", line 50, in wrapper
Mar 30 21:19:31     return func(*args, **kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 1141, in test_reduce_basics_cuda
Mar 30 21:19:31     self._test_reduce_basics(lambda t: t.clone().cuda())
Mar 30 21:19:31   File "test_c10d.py", line 1132, in _test_reduce_basics
Mar 30 21:19:31     work.wait()
Mar 30 21:19:31 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:72] Timed out waiting 1000ms for recv operation to complete
Mar 30 21:19:31 Process process 2:
Mar 30 21:19:31 Traceback (most recent call last):
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 30 21:19:31     self.run()
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 30 21:19:31     self._target(*self._args, **self._kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 470, in _run
Mar 30 21:19:31     getattr(self, self.id().split(".")[2])()
Mar 30 21:19:31   File "test_c10d.py", line 434, in wrapper
Mar 30 21:19:31     fn(self)
Mar 30 21:19:31   File "test_c10d.py", line 50, in wrapper
Mar 30 21:19:31     return func(*args, **kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 1141, in test_reduce_basics_cuda
Mar 30 21:19:31     self._test_reduce_basics(lambda t: t.clone().cuda())
Mar 30 21:19:31   File "test_c10d.py", line 1132, in _test_reduce_basics
Mar 30 21:19:31     work.wait()
Mar 30 21:19:31 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [127.0.0.1]:2773
Mar 30 21:19:31 Process process 3:
Mar 30 21:19:31 Traceback (most recent call last):
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 30 21:19:31     self.run()
Mar 30 21:19:31   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 30 21:19:31     self._target(*self._args, **self._kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 470, in _run
Mar 30 21:19:31     getattr(self, self.id().split(".")[2])()
Mar 30 21:19:31   File "test_c10d.py", line 434, in wrapper
Mar 30 21:19:31     fn(self)
Mar 30 21:19:31   File "test_c10d.py", line 50, in wrapper
Mar 30 21:19:31     return func(*args, **kwargs)
Mar 30 21:19:31   File "test_c10d.py", line 1141, in test_reduce_basics_cuda
Mar 30 21:19:31     self._test_reduce_basics(lambda t: t.clone().cuda())
Mar 30 21:19:31   File "test_c10d.py", line 1132, in _test_reduce_basics
Mar 30 21:19:31     work.wait()
Mar 30 21:19:31 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [127.0.0.1]:36483
Mar 30 21:19:31 FAIL
```

cc @pietern @mrshenli

**Comment by ezyang** [comment]
This appears to affect 418.43 as well. Sample:

https://circleci.com/gh/pytorch/pytorch/1115953?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
I'm testing if driver upgrade without kernel upgrade is sufficient to cause the deadlock in https://github.com/pytorch/pytorch/pull/18669

**Comment by ezyang** [comment]
Confirmed that driver upgrade without kernel upgrade causes deadlock.

**Comment by ezyang** [comment]
Driver 410.104 doesn't work: https://circleci.com/gh/pytorch/pytorch/1125682?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
410.104 works.

418.40.04 does not.

**Comment by ezyang** [comment]
We are likely going to work around this by just not upgrading the driver too much.

**Comment by pietern** [comment]
@ezyang We can try to increase the timeout here and see if this is merely a perf regression? The CUDA aware collectives in the gloo backend currently simply memcpy the tensors from GPU to pinned memory on the CPU, then run the collective, and then copy them back. This means there's nothing fancy happening behind the covers here, it's just a bunch of memcpys to/from pinned host memory.

**Comment by ezyang** [comment]
Yes, let's increase the timeout in this case. @pietern, can you submit the patch?

I notice that with the "working" upgraded driver, we still get problems occasionally https://circleci.com/gh/pytorch/pytorch/1153287?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mrshenli** [comment]
@pietern do you need #16571?

**Comment by pietern** [comment]
@mrshenli No need, but let's try to merge it regardless, it's been sitting for a while.

**Comment by ngimel** [comment]
We can't repro internally with 418.67 and latest nightly, can this be closed?
