### ISSUE TITLE
RuntimeError: Couldn't open shared file mapping: <torch_21720_2430665410>, error code: <0>

### ISSUE THREAD

**Issue by YingqianWang** [pytorch/pytorch#18797]
Help! My computer is equipped with two 2080ti GPUs. However, when I train my algorithm on GPU 0, and somebody trains another algorithm (different project) on GPU 1, then error occurs:

Traceback (most recent call last):
  File "D:/wangyingqian/DeOccNet/train.py", line 132, in <module>
    main()
  File "D:/wangyingqian/DeOccNet/train.py", line 129, in main
    train(train_loader, 1, 500)
  File "D:/wangyingqian/DeOccNet/train.py", line 49, in train
    for idx_iter, (data, label, mask) in enumerate(train_loader):
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 207, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\storage.py", line 120, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_21720_2430665410>, error code: <0>

Same error offen occurs when I use DataParallel to train one algorithm on two GPUs...

**Comment by peterjc123** [comment]
> However, when I train my algorithm on GPU 0, and somebody trains another algorithm (different project) on GPU 1, then error occurs:

This is really weird. We are already adding the PIDs to the name of the mutex, semaphore, event and share memory blocks. Could PIDs for different users on the same machine be the same?

> Same error offen occurs when I use DataParallel to train one algorithm on two GPUs...

Sorry, DataParallel with multiple GPUs is not available on Windows. However, you can share the tensors with the multiprocessing library to achieve this goal.

**Comment by peterjc123** [comment]
For the first problem, the related document is [here](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-openfilemappinga). Looks like we will need some additional flags for the applications to support multiple users.

**Comment by peterjc123** [comment]
To be sure, could you please send the log of the kernel function calls? You can use API Monitor or Process Monitor and choose to watch the functions including `CreateFileMapping`, `OpenFileMapping`, `MapViewOfFile`, 'UnmapViewOfFile' and `CloseHandle`.

**Comment by J0-nas** [comment]
Hi,
I encountered a similar error (or same, I don't know) in a single GPU setting. Otherwise our software setup might be similar.
I use:
Windows 10
python 3.6.8
pytorch 1.1.0

and a GTX 1070.

While I don't use multiple GPUs I do use multiply python+pytorch instances to train multiple models at once.
I'm not 100% sure, but it seems like the error occured right when the training of one model is completed and the model got saved using:

`torch.save(best_model.state_dict(), save_loc)`

```
Traceback (most recent call last):
  File ".\train_2.py", line 213, in <module>
    main()
  File ".\train_2.py", line 207, in main
    optimizer, criterion, lr_scheduler, epoch_evaluator, output_dir, writer, logger, num_epochs=epochs)
  File ".\train_2.py", line 72, in train_model
    for batch in tqdm(dataloaders[phase]):
  File "J:\ProgramData\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 41, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "J:\ProgramData\Anaconda3\lib\site-packages\torch\storage.py", line 124, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_5296_3299743120>, error code: <0>
```

**Comment by peterjc123** [comment]
@J0-nas Could you please change https://github.com/pytorch/pytorch/blob/master/aten/src/TH/THAllocator.cpp#L91-L107 to the following code and then rebuild pytorch?
```
    if (flags_ & TH_ALLOCATOR_MAPPED_EXCLUSIVE) {
      event_ = CreateEvent(nullptr, FALSE, FALSE, eventname);
    } else if (flags_ & TH_ALLOCATOR_MAPPED_NOCREATE) {
      event_ = OpenEvent(EVENT_ALL_ACCESS, FALSE, eventname);
    } else {
      AT_ERROR("Expected either TH_ALLOCATOR_MAPPED_EXCLUSIVE or TH_ALLOCATOR_MAPPED_NOCREATE");
    }

    if (event_ == nullptr) {
      AT_ERROR("Couldn't open shared event: <", eventname, ">, error code: <", GetLastError(), ">");
    }

    if (flags_ & TH_ALLOCATOR_MAPPED_EXCLUSIVE) {
      handle_ = CreateFileMapping(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE, hfilesz.HighPart, hfilesz.LowPart, filename);
    } else if (flags_ & TH_ALLOCATOR_MAPPED_NOCREATE) {
      handle_ = OpenFileMapping(FILE_MAP_ALL_ACCESS, FALSE, filename);
    } else {
      AT_ERROR("Expected either TH_ALLOCATOR_MAPPED_EXCLUSIVE or TH_ALLOCATOR_MAPPED_NOCREATE");
    }

    if (handle_ == nullptr) {
      AT_ERROR("Couldn't open shared file mapping: <", filename, ">, error code: <", GetLastError(), ">");
    }
```
The steps to build pytorch on Windows:
1. Install (VS 2017 + CUDA 10.0 / 10.1 ) / (VS 2019 + CUDA 10.1) For VS, tick C++ desktop development. For CUDA, tick all options.
2. Install pyyaml `pip install pyyaml`
3. Install CMake 3.14.3
4. `set REL_WITH_DEB_INFO=1`
5. Follow the steps in README.md
6. You can use Ninja to speed up build `pip install ninja`

**Comment by xcc13** [comment]
> Help! My computer is equipped with two 2080ti GPUs. However, when I train my algorithm on GPU 0, and somebody trains another algorithm (different project) on GPU 1, then error occurs:
> 
> Traceback (most recent call last):
> File "D:/wangyingqian/DeOccNet/train.py", line 132, in
> main()
> File "D:/wangyingqian/DeOccNet/train.py", line 129, in main
> train(train_loader, 1, 500)
> File "D:/wangyingqian/DeOccNet/train.py", line 49, in train
> for idx_iter, (data, label, mask) in enumerate(train_loader):
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 637, in **next**
> return self._process_next_batch(batch)
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> RuntimeError: Traceback (most recent call last):
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 232, in default_collate
> return [default_collate(samples) for samples in transposed]
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 232, in
> return [default_collate(samples) for samples in transposed]
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\utils\data\dataloader.py", line 207, in default_collate
> storage = batch[0].storage()._new_shared(numel)
> File "D:\Anaconda3\envs\YingqianWang_base\lib\site-packages\torch\storage.py", line 120, in _new_shared
> return cls._new_using_filename(size)
> RuntimeError: Couldn't open shared file mapping: <torch_21720_2430665410>, error code: <0>
> 
> Same error offen occurs when I use DataParallel to train one algorithm on two GPUs...

hello,Yingqian. How did you solve this problem at last? I encounter the same problem.

**Comment by iremyux** [comment]
I am closing this issue due to lack of activity. Please feel free to open a new issue in the future if you encounter any problems or have feature requests.
