### ISSUE TITLE
python setup.py install failed. undefined references

### ISSUE THREAD

**Issue by toekneechin777** [pytorch/pytorch#18932]
## 🐛 Bug

Tried running python setup.py install and it failed when trying to link generate_proposals_op_gpu_test

## To Reproduce

1.     Uninstall all CUDA versions, Nvidia drivers
2.     Reinstall CUDA 10.1, CuDNN 7.5.0
3.     Make a fresh conda environment
4.     git clone --recursive https://github.com/pytorch/pytorch
5.     python setup.py install

```
[ 84%] Linking CXX executable ../bin/generate_proposals_op_gpu_test
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/blob_gpu_test.dir/build.make:103: recipe for target 'bin/blob_gpu_test' failed
make[2]: *** [bin/blob_gpu_test] Error 1
CMakeFiles/Makefile2:3743: recipe for target 'caffe2/CMakeFiles/blob_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/ anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference toto  `__cudaPopCallConfiguration'
/home`/cblas_gemm_s8u8s32_computeanthony'/
/pytorchhome//anthonybuild/lib/libcaffe2.so: undefined/ pytorchreference /tobuild `cblas_sgemm_pack_get_size'
/home//libanthony/pytorch//buildlibcaffe2.so/:lib /libcaffe2.so: undefinedundefined reference to ` cblas_gemm_s8u8s32_compute'
/homereference/ anthonyto/ pytorch/build/`lib/cblas_gemm_s8u8s32_pack_get_sizelibcaffe2.so: undefined 'reference
 to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/utility_ops_gpu_test.dir/build.make:103: recipe for target 'bin/utility_ops_gpu_test' failed
make[2]: *** [bin/utility_ops_gpu_test] Error 1
caffe2/CMakeFiles/cuda_rng_test.dir/build.make:103: recipe for target 'bin/cuda_rng_test' failed
make[2]: *** [bin/cuda_rng_test] Error 1
CMakeFiles/Makefile2:3919: recipe for target 'caffe2/CMakeFiles/cuda_rng_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/cuda_rng_test.dir/all] Error 2
CMakeFiles/Makefile2:3435: recipe for target 'caffe2/CMakeFiles/utility_ops_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/cuda_stream_test.dir/build.make:103: recipe for target 'bin/cuda_stream_test' failed
make[2]: *** [bin/cuda_stream_test] Error 1
CMakeFiles/Makefile2:3831: recipe for target 'caffe2/CMakeFiles/cuda_stream_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/cuda_stream_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/batch_matmul_op_gpu_test.dir/build.make:103: recipe for target 'bin/batch_matmul_op_gpu_test' failed
make[2]: *** [bin/batch_matmul_op_gpu_test] Error 1
CMakeFiles/Makefile2:3875: recipe for target 'caffe2/CMakeFiles/batch_matmul_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/batch_matmul_op_gpu_test.dir/all] Error 2
caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:103: recipe for target 'bin/reshape_op_gpu_test' failed
make[2]: *** [bin/reshape_op_gpu_test] Error 1
CMakeFiles/Makefile2:3479: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/build.make:103: recipe for target 'bin/generate_proposals_op_util_nms_gpu_test' failed
make[2]: *** [bin/generate_proposals_op_util_nms_gpu_test] Error 1
CMakeFiles/Makefile2:3523: recipe for target 'caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/build.make:103: recipe for target 'bin/generate_proposals_op_gpu_test' failed
make[2]: *** [bin/generate_proposals_op_gpu_test] Error 1
CMakeFiles/Makefile2:3567: recipe for target 'caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/cuda_cudnn_test.dir/build.make:103: recipe for target 'bin/cuda_cudnn_test' failed
make[2]: *** [bin/cuda_cudnn_test] Error 1
CMakeFiles/Makefile2:3787: recipe for target 'caffe2/CMakeFiles/cuda_cudnn_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/cuda_cudnn_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/build.make:103: recipe for target 'bin/conv_op_cache_cudnn_test' failed
make[2]: *** [bin/conv_op_cache_cudnn_test] Error 1
CMakeFiles/Makefile2:3699: recipe for target 'caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/net_gpu_test.dir/build.make:103: recipe for target 'bin/net_gpu_test' failed
make[2]: *** [bin/net_gpu_test] Error 1
CMakeFiles/Makefile2:3655: recipe for target 'caffe2/CMakeFiles/net_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/net_gpu_test.dir/all] Error 2
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_sgemm_pack_get_size'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_compute'
/home/anthony/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/mpi_gpu_test.dir/build.make:105: recipe for target 'bin/mpi_gpu_test' failed
make[2]: *** [bin/mpi_gpu_test] Error 1
CMakeFiles/Makefile2:3611: recipe for target 'caffe2/CMakeFiles/mpi_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/mpi_gpu_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 719, in <module>
    build_deps()
  File "setup.py", line 285, in build_deps
    build_dir='build')
  File "/home/anthony/pytorch/tools/build_pytorch_libs.py", line 280, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/home/anthony/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '12', 'install']' returned non-zero exit status 2.
```

## Expected behavior

Expected build to complete

## Environment

Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.16.0
[pip] numpydoc==0.8.0
[pip] pytorch-pretrained-bert==0.3.0
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.0
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.5.0                         1    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-include               2019.3                      199  
[conda] mkl-service               1.1.2                    py36_3  
[conda] mkl_fft                   1.0.4            py36h4414c95_1  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] pytorch                   0.3.0           py36_cuda8.0.61_cudnn7.0.3h37a80b5_4    pytorch
[conda] pytorch-pretrained-bert   0.3.0                     <pip>
[conda] torch                     1.0.1.post2               <pip>
[conda] torchvision               0.2.0            py36h17b6947_1    pytorch

## Additional context

I know I have previous versions of Cuda which is most likely the issue. I just have no idea how to get all the versions to sync up and what versions of what works with versions of other stuff.

**Comment by umanwizard** [comment]
I don't think this is related to CUDA since it is failing to find symbols from the BLAS library (like `cblas_gemm_s8u8s32_pack`).

**Comment by umanwizard** [comment]
At any rate, I think you would probably be able to get help quicker for this in the [forums](https://discuss.pytorch.org/), as it appears to be an issue with your individual setup. But please feel free to reopen if you think it is a more general issue with PyTorch.

**Comment by glample** [comment]
We had the same issue. Problem was the version of MKL which was not good. Just running:

```
conda remove mkl mkl-include
conda install numpy pyyaml mkl=2019.3 mkl-include setuptools cmake cffi typing
```

before the installation fixed the issue.

**Comment by songmeixu** [comment]
@toekneechin777 Have you solved this problem? I had the same issue, and the @glample method did not work out for me.

**Comment by ahmedbr** [comment]
> @toekneechin777 Have you solved this problem? I had the same issue, and the @glample method did not work out for me.

Have you solved it too ?
