### ISSUE TITLE
torchfile.T7ReaderException: unknown object type / typeidx: -1112529805

### ISSUE THREAD

**Issue by MeteoRex11** [pytorch/pytorch#18997]
I am currently trying to implement a StackGAN, but I am getting the following error:

`Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 242, in sample
    t_file = torchfile.load(datapath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchfile.py", line 414, in read_obj
    "unknown object type / typeidx: {}".format(typeidx))
torchfile.T7ReaderException: unknown object type / typeidx: -1112529805`

**Comment by peterjc123** [comment]
Please try appending the parameter long_size like this `load_lua(....., long_size=8)`.

**Comment by peterjc123** [comment]
For T7Reader, it should be `force_8bytes_long=True`.

**Comment by MeteoRex11** [comment]
> Please try appending the parameter long_size like this `load_lua(....., long_size=8)`.

Which file is this in?

**Comment by peterjc123** [comment]
C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py. For T7Reader, it should be force_8bytes_long=True.

**Comment by MeteoRex11** [comment]
I am getting the following error now:

`RuntimeError: CUDA error: unknown error`

for  
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()

**Comment by lifebl** [comment]
> C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py. For T7Reader, it should be force_8bytes_long=True.

Thank you. It's been bothering me for a long time
