### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by BCWang93** [pytorch/pytorch#19015]
```
/pytorch/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [119,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    main(opt)
  File "train.py", line 185, in main
    train(opt,writer)
  File "train.py", line 64, in train
    _loss_item=yolo_losses[i](outputs[i],labels)
  File "/home/a/anaconda3/envs/bcw_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/a/Bcw_data/YOLO_v3/models/yolo_loss.py", line 71, in forward
    loss_x=self.bce_loss(dx*coord_mask,tx*coord_mask) / (2*n_obj)
  File "/home/a/anaconda3/envs/bcw_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/a/anaconda3/envs/bcw_env/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 504, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/a/anaconda3/envs/bcw_env/lib/python3.6/site-packages/torch/nn/functional.py", line 2027, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

Anyon can help me!When I set the param as none like this 'nn.BCELoss()',it will works!But When I set the params as 'sizeaverage=False',it will give this error!This is why?

**Comment by umanwizard** [comment]
Can you give show the exact line that caused the error?

**Comment by umanwizard** [comment]
Could you post this to the [forums](https://discuss.pytorch.org/)? You would probably get a faster response.
