### ISSUE TITLE
Cannot export model using onnx - TypeError: elu() got an unexpected keyword argument 'scale' (occurred when translating elu)

### ISSUE THREAD

**Issue by SingL3** [pytorch/pytorch#19157]
Hello, I am trying to export a model using torch.onnx and I get the following error:

> Traceback (most recent call last):
  File "convert_to_onnx.py", line 30, in <module>
    convert_to_onnx(net, args.output_name)
  File "convert_to_onnx.py", line 16, in convert_to_onnx
    torch.onnx.export(net, input, output_name, verbose=True, input_names=input_names, output_names=output_names)
  File "/home/lin/anaconda3/envs/torch040/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/lin/anaconda3/envs/torch040/lib/python3.6/site-packages/torch/onnx/utils.py", line 84, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/home/lin/anaconda3/envs/torch040/lib/python3.6/site-packages/torch/onnx/utils.py", line 140, in _export
    trace.set_graph(_optimize_graph(trace.graph(), aten))
  File "/home/lin/anaconda3/envs/torch040/lib/python3.6/site-packages/torch/onnx/utils.py", line 95, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
  File "/home/lin/anaconda3/envs/torch040/lib/python3.6/site-packages/torch/onnx/__init__.py", line 40, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lin/anaconda3/envs/torch040/lib/python3.6/site-packages/torch/onnx/utils.py", line 368, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
TypeError: elu() got an unexpected keyword argument 'scale' (occurred when translating elu)

I am using pytorch 0.4.0 which I install by this command:

> conda install pytorch=0.4.0 cuda80 -c pytorch

So is there any solution? Thank you!

**Comment by spandantiwari** [comment]
@SingL3 - could you provide the repro steps for this. Also, there have been several improvements to the PyTorch ONNX exporter since 0.4.0 release. It would be helpful if you can try exporting from the latest release PyTorch 1.1, maybe even the nightly build, and see if you still hit this issue.

**Comment by garymm** [comment]
Closing due to lack of response from the reporter. Please open another issue with repro instructions if this is still a problem on the latest version of PyTorch.
