### ISSUE TITLE
Different behavior of torch.nn.MultiMarginLoss on CPU/GPU Tensors

### ISSUE THREAD

**Issue by zhmd** [pytorch/pytorch#19229]
## 🐛 Bug

According to the documentation, the input to torch.nn.MultiMarginLoss() should be:
- x (a 2D mini-batch Tensor)
- y (a 1D tensor of target class indices, **0 <= y <= x.size(1)**).

For CPU tensors, it will raise RuntimeError when target (y) is out of range, however that seems not the case for GPU tensors.
## To Reproduce

```
>>> a = torch.rand(3, 1)
>>> b = torch.LongTensor(3).random_(0, 5)
>>> criterion = torch.nn.MultiMarginLoss()
>>> criterion(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/cs.pitt.edu/usr0/miz44/opt/miniconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/cs.pitt.edu/usr0/miz44/opt/miniconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 1138, in forward
    weight=self.weight, reduction=self.reduction)
  File "/afs/cs.pitt.edu/usr0/miz44/opt/miniconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/nn/functional.py", line 2380, in multi_margin_loss
    return torch._C._nn.multi_margin_loss(input, target, p, margin, weight, reduction_enum)
RuntimeError: invalid argument 3: target out of range at /pytorch/aten/src/THNN/generic/MultiMarginCriterion.c:43
```
The above is the expected behavior. However, 
```
>>> criterion(a.cuda(), b.cuda())
tensor(0.4437, device='cuda:0')
```
I didn't quite understand how this value is calculated, as I suppose the behavior on CPU and GPU should be consistent?

When giving inputs with correct shape, the results on CPU and GPU tensors seem consistent.
```
>>> c = torch.rand(3, 5)
>>> criterion(c, b)
tensor(0.6158)
>>> criterion(c.cuda(), b.cuda())
tensor(0.6158, device='cuda:0')
```

## Expected behavior
A error message similar with CPU tensors should be given to warn about the unexpected input.

## Environment

Collecting environment information...
PyTorch version: 1.1.0.dev20190411
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux release 7.6.1810 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch-nightly==1.1.0.dev20190411
[pip] torchvision-nightly==0.2.3
[conda] torch-nightly             1.1.0.dev20190411          pypi_0    pypi
[conda] torchvision-nightly       0.2.3                    pypi_0    pypi

**Comment by ezyang** [comment]
It's probably just indexing random memory somewhere else in the CUDA caching allocator blocks. We should add an error check in this case.
