### ISSUE TITLE
timeout when load data

### ISSUE THREAD

**Issue by xuzheyuan624** [pytorch/pytorch#19258]
## 🐛 Bug

When I load dataset using torch.utils.data.Dataloader, the code stop running after getting a few batches. And it says timeout when I interrupt it. 

```
^CTraceback (most recent call last):
  File "train_rpn.py", line 145, in <module>
    main(args)
  File "train_rpn.py", line 121, in main
    train(model, train_dataloader, epoch, optimizer, lr_schedule, writer)
  File "train_rpn.py", line 36, in train
    for step, (videos, labels) in enumerate(train_dataloader):
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 545, in __next__
    idx, batch = self._get_batch()
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 522, in _get_batch
    success, data = self._try_get_batch()
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 480, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/xuzheyuan/.conda/envs/pytorch/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

**Comment by wollschl** [comment]
How did you solve the problem? Getting the exact same message

**Comment by GeoffreyChen777** [comment]
Same here...

**Comment by RuijieJ** [comment]
Same problem! Have you solved it?

**Comment by wollschl** [comment]
We solved it. It was just something wrong in our own dataset class. When we aborted it the last possible error message was just from the dataloader while the error was even deeper.

**Comment by GeoffreyChen777** [comment]
@wollschl Hi, Is it a transform bug or an io bug?

**Comment by wollschl** [comment]
For me it was no bug just an error in my code io related
