### ISSUE TITLE
DistributedDataParallelTest .test_dist_broadcast_coalesced_gloo is flaky

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19438]
```
Apr 18 21:18:12 ======================================================================
Apr 18 21:18:12 FAIL: test_dist_broadcast_coalesced_gloo (__main__.DistributedDataParallelTest)
Apr 18 21:18:12 ----------------------------------------------------------------------
Apr 18 21:18:12 Traceback (most recent call last):
Apr 18 21:18:12   File "test_c10d.py", line 448, in wrapper
Apr 18 21:18:12     self._join_processes(fn)
Apr 18 21:18:12   File "test_c10d.py", line 495, in _join_processes
Apr 18 21:18:12     self._check_return_codes(elapsed_time)
Apr 18 21:18:12   File "test_c10d.py", line 506, in _check_return_codes
Apr 18 21:18:12     self.assertEqual(p.exitcode, first_process.exitcode)
Apr 18 21:18:12   File "/var/lib/jenkins/workspace/test/common_utils.py", line 508, in assertEqual
Apr 18 21:18:12     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Apr 18 21:18:12 AssertionError: 7 not less than or equal to 1e-05 : 
Apr 18 21:18:12 
```

https://circleci.com/gh/pytorch/pytorch/1367049?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pietern** [comment]
I saw this one too -- it may be a real regression, but haven't been able to repro yet.

**Comment by SsnL** [comment]
It's been consistently failing on this pr: https://github.com/pytorch/pytorch/pull/19421

**Comment by pietern** [comment]
Don't have a local repro.

The `7` in that error messages makes me think this is caused by a `SIGBUS` (as in `abs(0 - 7) == 7`).

**Comment by pietern** [comment]
Another failure observed on master: https://circleci.com/gh/pytorch/pytorch/1372877

**Comment by pietern** [comment]
@SsnL Found the culprit in #19183. This is now broken on master.

**Comment by SsnL** [comment]
@pietern Thanks for digging this up!

**Comment by pietern** [comment]
Reverted in 563de88aa5c8ec1be3ad133021f34139ebf8ed08.
