### ISSUE TITLE
[jit] Flaky test: test_input_dict_of_dicts (__main__.TestJit)

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#19486]
https://circleci.com/gh/pytorch/pytorch/1381926?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

on PR https://github.com/pytorch/pytorch/pull/19470

log is

```
Apr 19 15:20:19 ======================================================================
Apr 19 15:20:19 ERROR: test_input_dict_of_dicts (__main__.TestJit)
Apr 19 15:20:19 ----------------------------------------------------------------------
Apr 19 15:20:19 Traceback (most recent call last):
Apr 19 15:20:19   File "test_jit.py", line 1667, in test_input_dict_of_dicts
Apr 19 15:20:19     self.checkTrace(test, (inputs,), allow_unused=True)
Apr 19 15:20:19   File "test_jit.py", line 561, in checkTrace
Apr 19 15:20:19     _force_outplace=_force_outplace)
Apr 19 15:20:19   File "/opt/python/3.5/lib/python3.5/site-packages/torch/jit/__init__.py", line 677, in trace
Apr 19 15:20:19     _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
Apr 19 15:20:19   File "/opt/python/3.5/lib/python3.5/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
Apr 19 15:20:19     return func(*args, **kwargs)
Apr 19 15:20:19   File "/opt/python/3.5/lib/python3.5/site-packages/torch/jit/__init__.py", line 569, in _check_trace
Apr 19 15:20:19     if compare_outputs(traced_outs, fn_outs, 'Python function'):
Apr 19 15:20:19   File "/opt/python/3.5/lib/python3.5/site-packages/torch/jit/__init__.py", line 557, in compare_outputs
Apr 19 15:20:19     atol=torch.testing._get_default_tolerance(orig, ref)[1])
Apr 19 15:20:19   File "/opt/python/3.5/lib/python3.5/site-packages/torch/testing/__init__.py", line 24, in assert_allclose
Apr 19 15:20:19     expected = expected.expand_as(actual)
Apr 19 15:20:19 RuntimeError: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [3, 2].  Tensor sizes: [2, 3]
```

**Comment by driazati** [comment]
Added in #18092
