### ISSUE TITLE
elementMap_.count(v) ASSERT FAILED at csrc/jit/passes/alias_analysis.cpp:536

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#19502]
## 🐛 Bug
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 529, in run_mod_and_filter_tensor_outputs
    outs = wrap_retval(mod(*_clone_inputs(inputs)))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 1407, in forward
    return self._get_method('forward')(*args, **kwargs)
RuntimeError: elementMap_.count(v) ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:536, please report a bug to PyTorch. (registerWrite at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:536)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fce0a6322a1 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fce0a631bda in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #2: torch::jit::AliasDb::registerWrite(torch::jit::Value const*, torch::jit::Node*) + 0x1dd (0x7fce035b48bd in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #3: torch::jit::AliasDb::analyzeImpl(torch::jit::Node*) + 0x675 (0x7fce035b5aa5 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #4: torch::jit::AliasDb::analyze(torch::jit::Node*) + 0xf (0x7fce035b64bf in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #5: torch::jit::AliasDb::analyze(torch::jit::Block*) + 0x33 (0x7fce035b65a3 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #6: torch::jit::AliasDb::analyze(std::shared_ptr<torch::jit::Graph> const&) + 0x92c (0x7fce035b84cc in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #7: torch::jit::AliasDb::AliasDb(std::shared_ptr<torch::jit::Graph>) + 0x3a8 (0x7fce035b8d98 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #8: torch::unique_type_for<torch::jit::AliasDb>::value torch::make_unique<torch::jit::AliasDb, std::shared_ptr<torch::jit::Graph>&>(std::shared_ptr<torch::jit::Graph>&) + 0x45 (0x7fce035d89e5 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #9: <unknown function> + 0xace7f5 (0x7fce035ce7f5 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #10: <unknown function> + 0xad5758 (0x7fce035d5758 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #11: <unknown function> + 0xad71d7 (0x7fce035d71d7 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #12: torch::jit::FuseGraph(std::shared_ptr<torch::jit::Graph>&) + 0x65 (0x7fce035d82e5 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #13: <unknown function> + 0xa64cd6 (0x7fce03564cd6 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
frame #14: <unknown function> + 0x479015 (0x7fce0ad07015 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0x450c0a (0x7fce0acdec0a in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0x1302fc (0x7fce0a9be2fc in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #18: python3() [0x4d9dc7]
frame #20: python3() [0x58f132]
frame #25: python3() [0x4d9e62]
frame #30: python3() [0x58f08b]
frame #44: python3() [0x54af20]
frame #50: python3() [0x630f22]
frame #53: python3() [0x65414e]
frame #55: __libc_start_main + 0xeb (0x7fce0ea74b6b in /lib/x86_64-linux-gnu/libc.so.6)
```

## To Reproduce

1. Tracing a model in python

## Expected behavior

Traces

## Environment

 - PyTorch Version (e.g., 1.0): Latest nightly 19th April
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip nightly
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0/7.5
 - GPU models and configuration: Titan V

**Comment by eellison** [comment]
Hi, thank you for raising an issue. 

Do you mind posting a repro? it's hard to investigate otherwise

**Comment by xsacha** [comment]
I simply ran: torch.jit.trace(my_model.pth).
Previous nightlife's had worked fine.

Model I tested that causes this issue: 
Network from this repository with the prebuilt model https://github.com/zisianw/FaceBoxes.PyTorch


Model: https://drive.google.com/file/d/1aRdcf692S2-oxNdoc6oOjIVvoyvSHl52/view?usp=sharing

**Comment by suo** [comment]
@xsacha  I'm having trouble following your instructions; I did the following:
1. Placed your model in `weights/` in the FaceBoxes.PyTorch dir, renaming it `FaceBoxes.pth`.
2. Ran `test.py` with the following modification:
```
 out = net(img)  # forward pass [line 116 in test.py]
 traced_model = torch.jit.trace(net, img)
 out = traced_model(img)
```
3. Did not get a crash.

Could you:
1. Confirm that this crash happens on PyTorch master.
2. Provide a small, self-contained script that has this problem so that it's easier for us to investigate?

Thanks!

**Comment by xsacha** [comment]
Thanks.
It was a nightly build from 19th April.
Did this commit fix the issue? https://github.com/pytorch/pytorch/commit/a421f882dc716aa8888931815d1178be6ef9ab73
I'll try it on the next nightly.

It was just this line that caused the crash: traced_model = torch.jit.trace(net, img)

**Comment by xsacha** [comment]
I can confirm it still happens on the latest nightly.

Collecting torch_nightly
  Downloading https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.1.0.dev20190420-cp37-cp37m-linux_x86_64.whl (702.6MB)
    100% |████████████████████████████████| 702.6MB 136kB/s 
Installing collected packages: torch-nightly
Successfully installed torch-nightly-1.1.0.dev20190420


```
  File "converttoc.py", line 56, in train
    traced_script_module = torch.jit.trace(net, torch.rand(1, 3, 1024, 1024))
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 677, in trace
    _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 567, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(module, inputs, 'trace')
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 535, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
        elementMap_.count(v) ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:554, please report a bug to PyTorch. (registerWrite at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:554)
        frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f2add3dd2a1 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
        frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f2add3dcbda in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
        frame #2: torch::jit::AliasDb::registerWrite(torch::jit::Value const*, torch::jit::Node*) + 0x1dd (0x7f2a7d94b07d in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #3: torch::jit::AliasDb::analyzeImpl(torch::jit::Node*) + 0x68d (0x7f2a7d94c9dd in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #4: torch::jit::AliasDb::analyze(torch::jit::Node*) + 0xf (0x7f2a7d94d3ff in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #5: torch::jit::AliasDb::analyze(torch::jit::Block*) + 0x33 (0x7f2a7d94d4e3 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #6: torch::jit::AliasDb::analyze(std::shared_ptr<torch::jit::Graph> const&) + 0x92c (0x7f2a7d94f40c in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #7: torch::jit::AliasDb::AliasDb(std::shared_ptr<torch::jit::Graph>) + 0x3a8 (0x7f2a7d94fcd8 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #8: torch::unique_type_for<torch::jit::AliasDb>::value torch::make_unique<torch::jit::AliasDb, std::shared_ptr<torch::jit::Graph>&>(std::shared_ptr<torch::jit::Graph>&) + 0x45 (0x7f2a7d970585 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #9: <unknown function> + 0xad5385 (0x7f2a7d966385 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #10: <unknown function> + 0xadc2f8 (0x7f2a7d96d2f8 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #11: <unknown function> + 0xaddd77 (0x7f2a7d96ed77 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #12: torch::jit::FuseGraph(std::shared_ptr<torch::jit::Graph>&) + 0x65 (0x7f2a7d96fe85 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #13: <unknown function> + 0xa67c36 (0x7f2a7d8f8c36 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so.1)
        frame #14: <unknown function> + 0x47d3f5 (0x7f2addab63f5 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
        frame #15: <unknown function> + 0x454c7a (0x7f2adda8dc7a in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
        frame #16: <unknown function> + 0x13121c (0x7f2add76a21c in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
        <omitting python frames>
        frame #18: python3() [0x4d9dc7]
        frame #20: python3() [0x58f132]
        frame #25: python3() [0x4d9e62]
        frame #30: python3() [0x58f08b]
        frame #44: python3() [0x54af20]
        frame #50: python3() [0x630f22]
        frame #53: python3() [0x65414e]
        frame #55: __libc_start_main + 0xeb (0x7f2ae180fb6b in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by suo** [comment]
Great, the script you provided triggers the crash for me. I'll investigate, thanks! No need to do the binary search

**Comment by suo** [comment]
Looks like the regression was introduced in #18266. Something about the layernorm fusion is violating a graph invariant—sticking a lint inside `refreshAliasDb` causes things to go crazy.

heads up @wanchaol that we should investigate tomorroow.
