### ISSUE TITLE
[jit] jit.trace segfault on variable slicing using `torch.narrow`

### ISSUE THREAD

**Issue by daiwei89** [pytorch/pytorch#19517]
## 🐛 Bug

I want to slice a tensor by a variable range such as ` x[:y]` where `x` is a tensor and `y` is a 0-dim tensor. Since normal way of slicing like the above  can't be captured by jit trace, I opted for `narrow` which causes segfault.

## To Reproduce

Run this code:

```
from __future__ import print_function
import torch

class VariableSlice(torch.nn.Module):
    def __init__(self):
        super(VariableSlice, self).__init__()

    def forward(self, x, y):
        #return x[:y]
        return x.narrow(0, 0, y)

onnx_path = "variable_slice.onnx"
model = VariableSlice()
torch_in = (torch.randint(0, 10, (2, 3)), torch.tensor(1))
torch_out = model(*torch_in)
torch.onnx.export(model, torch_in, onnx_path, verbose=True)
```

Output:

```
$ python variable_slice.py
Segmentation fault: 11
```

## Environment

PyTorch version: 1.1.0a0+43f9407
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

**Comment by eellison** [comment]
Is the segfault on onnx export ?

**Comment by eellison** [comment]
cc @houseroad

**Comment by daiwei89** [comment]
@eellison  Yes that's the line segfault occurs.

**Comment by daiwei89** [comment]
Instead of tracing, I tried scripting:

```
from __future__ import print_function
import torch

#class VariableSlice(torch.nn.Module):
class VariableSlice(torch.jit.ScriptModule):
    def __init__(self):
        super(VariableSlice, self).__init__()

    @torch.jit.script_method
    def forward(self, x, y : int):
        return x[:y]
        #return x.narrow(0, 0, y)

onnx_path = "variable_slice.onnx"
model = VariableSlice()
torch_in = (torch.randint(0, 10, (2, 3)), torch.tensor(1))
torch_out = model(*torch_in)
print("exporting now...")
#torch.onnx.export(model, torch_in, onnx_path, verbose=True)
model_onnx = torch.onnx._export(model, torch_in, onnx_path,
        verbose=True,
        operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
        example_outputs=torch_out)
```

The error is more informative:

```
exporting now...
Traceback (most recent call last):
  File "variable_slice.py", line 23, in <module>
    example_outputs=torch_out)
  File "/Users/weidai/envs/pt/lib/python3.7/site-packages/torch/onnx/__init__.py", line 19, in _export
    result = utils._export(*args, **kwargs)
  File "/Users/weidai/envs/pt/lib/python3.7/site-packages/torch/onnx/utils.py", line 358, in _export
    _retain_param_name, do_constant_folding)
  File "/Users/weidai/envs/pt/lib/python3.7/site-packages/torch/onnx/utils.py", line 273, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/Users/weidai/envs/pt/lib/python3.7/site-packages/torch/onnx/utils.py", line 165, in _optimize_graph
    torch._C._jit_pass_constant_propagation(graph)
RuntimeError:
Schema not found for node. File a bug report.
Node: %4 : Long(1, 3) = aten::slice(%x, %3, %3, %y, %2)

Input types:Long(2, 3), int, int, Long(), int
candidates were:
  aten::slice(Tensor self, int dim=<default>, int start=<default>, int end=<default>, int step=<default>) -> Tensor
  aten::slice(int[] l, int start, int end=<default>, int step=<default>) -> int[]
  aten::slice(float[] l, int start, int end=<default>, int step=<default>) -> float[]
  aten::slice(bool[] l, int start, int end=<default>, int step=<default>) -> bool[]
  aten::slice(Tensor[] l, int start, int end=<default>, int step=<default>) -> Tensor[]
  aten::slice(t[] l, int start, int end=<default>, int step=<default>) -> t[]
  aten::slice(string string, int start, int end=<default>, int step=<default>) -> string
graph(%x : Long(2, 3),
      %y : Long()):
  %2 : int = prim::Constant[value=1]()
  %3 : int = prim::Constant[value=0]()
  %4 : Long(1, 3) = aten::slice(%x, %3, %3, %y, %2)
  return (%4)
```

Will do more digging.

**Comment by daiwei89** [comment]
Using TorchScript did the trick:

```
class VariableSlice(torch.jit.ScriptModule):
    def __init__(self):
        super(VariableSlice, self).__init__()

    @torch.jit.script_method
    def forward(self, x, y, z):
        return x[:y, :z]
        #return x.narrow(0, 0, y)

onnx_path = "variable_slice.onnx"
model = VariableSlice()
torch_in = (torch.randint(0, 10, (2, 3)), torch.tensor(1),
        torch.tensor(1))
torch_out = model(*torch_in)
print("exporting now...")
model_onnx = torch.onnx._export(model, torch_in, onnx_path,
        verbose=True,
        operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
        example_outputs=torch_out)
```
