### ISSUE TITLE
[minor] list(empty tensor) fails

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1952]
`list(empty tensor)` fails, while `(empty tensor).tolist()` is ok. It might be better if they were consistent.

```python
list(torch.LongTensor())

#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File ".../torch/tensor.py", line 149, in __iter__
#    return iter(map(lambda i: self.select(0, i), _range(self.size(0))))
#RuntimeError: dimension 0 out of range of 0D tensor at .../torch/lib/TH/generic/THTensor.c:24

torch.LongTensor().tolist()
#[]
```

**Comment by vadimkantorov** [comment]
Converting to a list using `list()` isn't probably a good idea anyway, but this issue also breaks for loop iteration:
```python
tensor = get_tensor_from_somewhere()
for ind in tensor:
    print(ind)
```
