### ISSUE TITLE
TestJit.test_input_dict_unify is flaky

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19544]
## 🐛 Bug

it seems to rely on ordering of `values`, which is not guaranteed in python.

```py
Apr 21 15:06:42 ======================================================================
Apr 21 15:06:42 ERROR: test_input_dict_unify (__main__.TestJit)
Apr 21 15:06:42 ----------------------------------------------------------------------
Apr 21 15:06:42 Traceback (most recent call last):
Apr 21 15:06:42   File "test_jit.py", line 1652, in test_input_dict_unify
Apr 21 15:06:42     self.checkTrace(test, (inputs,), inputs_require_grads=False)
Apr 21 15:06:42   File "test_jit.py", line 561, in checkTrace
Apr 21 15:06:42     _force_outplace=_force_outplace)
Apr 21 15:06:42   File "/opt/python/3.5/lib/python3.5/site-packages/torch/jit/__init__.py", line 677, in trace
Apr 21 15:06:42     _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
Apr 21 15:06:42   File "/opt/python/3.5/lib/python3.5/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
Apr 21 15:06:42     return func(*args, **kwargs)
Apr 21 15:06:42   File "/opt/python/3.5/lib/python3.5/site-packages/torch/jit/__init__.py", line 575, in _check_trace
Apr 21 15:06:42     raise TracingCheckError(*diag_info)
Apr 21 15:06:42 torch.jit.TracingCheckError: Tracing failed sanity checks!
Apr 21 15:06:42 ERROR: Graphs differed across invocations!
Apr 21 15:06:42 	Graph diff:
Apr 21 15:06:42 		  graph(%0 : Dict[str, Tensor]):
Apr 21 15:06:42 		    %1 : Tensor[] = aten::values(%0)
Apr 21 15:06:42 		    %2 : Tensor, %3 : Tensor = prim::ListUnpack(%1)
Apr 21 15:06:42 		-   %4 : (Tensor, Tensor) = prim::TupleConstruct(%2, %3)
Apr 21 15:06:42 		?                                                  ----
Apr 21 15:06:42 		+   %4 : (Tensor, Tensor) = prim::TupleConstruct(%3, %2)
Apr 21 15:06:42 		?                                                 ++++
Apr 21 15:06:42 		    return (%4)
Apr 21 15:06:42 	First diverging operator:
Apr 21 15:06:42 	Node diff:
Apr 21 15:06:42 		- %4 : (Tensor, Tensor) = prim::TupleConstruct(%2, %3)
Apr 21 15:06:42 		?                                                ----
Apr 21 15:06:42 		+ %4 : (Tensor, Tensor) = prim::TupleConstruct(%3, %2)
Apr 21 15:06:42 		?                                               ++++
Apr 21 15:06:42 
```

https://circleci.com/gh/pytorch/pytorch/1407889?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@efaust

**Comment by suo** [comment]
I believe @efaust fixed this. Can you confirm?

**Comment by suo** [comment]
Should be fixed in master
