### ISSUE TITLE
test_input_dict_empty_list on ROCm is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#19565]
Sample failure:

```
13:28:05 ======================================================================
13:28:05 FAIL: test_input_dict_empty_list (__main__.TestJit)
13:28:05 ----------------------------------------------------------------------
13:28:05 Traceback (most recent call last):
13:28:05   File "test_jit.py", line 1701, in test_input_dict_empty_list
13:28:05     self.checkTrace(test, (inputs,))
13:28:05 AssertionError: "List trace" does not match "Dictionary inputs may only have string, int, or float keys (toDictKeyIValue at /var/lib/jenkins/workspace/torch/csrc/jit/pybind_utils.h:59)
13:28:05 frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f3b9dc4c8d7 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libc10.so)
13:28:05 frame #1: <unknown function> + 0x346931 (0x7f3b9e3c0931 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
13:28:05 frame #2: <unknown function> + 0x34a173 (0x7f3b9e3c4173 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
13:28:05 frame #3: <unknown function> + 0x349858 (0x7f3b9e3c3858 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
13:28:05 frame #4: <unknown function> + 0x3bee1a (0x7f3b9e438e1a in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
13:28:05 frame #5: <unknown function> + 0xcbd37 (0x7f3b9e145d37 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
13:28:05 <omitting python frames>
13:28:05 frame #56: __libc_start_main + 0xf5 (0x7f3ba60213d5 in /lib64/libc.so.6)
13:28:05 frame #57: /usr/bin/python() [0x40066e]
13:28:05 "
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-test/8857/console

**Comment by ezyang** [comment]
Another failure:

```
12:56:13 ======================================================================
12:56:13 FAIL: test_input_dict_empty_list (__main__.TestJit)
12:56:13 ----------------------------------------------------------------------
12:56:13 Traceback (most recent call last):
12:56:13   File "test_jit.py", line 1701, in test_input_dict_empty_list
12:56:13     self.checkTrace(test, (inputs,))
12:56:13 AssertionError: "List trace" does not match "Dictionary inputs may only have string, int, or float keys (toDictKeyIValue at /var/lib/jenkins/workspace/torch/csrc/jit/pybind_utils.h:59)
12:56:13 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x47 (0x7fa2c2d98cd7 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libc10.so)
12:56:13 frame #1: <unknown function> + 0x4bc61f (0x7fa2c346761f in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
12:56:13 frame #2: <unknown function> + 0x4b9a34 (0x7fa2c3464a34 in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
12:56:13 frame #3: <unknown function> + 0x4b8e6c (0x7fa2c3463e6c in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
12:56:13 frame #4: <unknown function> + 0x52f73a (0x7fa2c34da73a in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
12:56:13 frame #5: <unknown function> + 0x542e6b (0x7fa2c34ede6b in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
12:56:13 frame #6: <unknown function> + 0xc1fcb (0x7fa2c306cfcb in /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
12:56:13 frame #7: PyEval_EvalFrameEx + 0x9446 (0x4c5326 in /usr/bin/python)
12:56:13 frame #8: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #9: PyEval_EvalFrameEx + 0x58e6 (0x4c17c6 in /usr/bin/python)
12:56:13 frame #10: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #11: PyEval_EvalFrameEx + 0x58e6 (0x4c17c6 in /usr/bin/python)
12:56:13 frame #12: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #13: PyEval_EvalFrameEx + 0x6076 (0x4c1f56 in /usr/bin/python)
12:56:13 frame #14: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #15: /usr/bin/python() [0x4d57a3]
12:56:13 frame #16: PyObject_Call + 0x3e (0x4a587e in /usr/bin/python)
12:56:13 frame #17: PyEval_EvalFrameEx + 0x263e (0x4be51e in /usr/bin/python)
12:56:13 frame #18: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #19: /usr/bin/python() [0x4d5669]
12:56:13 frame #20: /usr/bin/python() [0x4eef5e]
12:56:13 frame #21: PyObject_Call + 0x3e (0x4a587e in /usr/bin/python)
12:56:13 frame #22: /usr/bin/python() [0x548fc3]
12:56:13 frame #23: PyEval_EvalFrameEx + 0x578d (0x4c166d in /usr/bin/python)
12:56:13 frame #24: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #25: /usr/bin/python() [0x4d57a3]
12:56:13 frame #26: PyObject_Call + 0x3e (0x4a587e in /usr/bin/python)
12:56:13 frame #27: PyEval_EvalFrameEx + 0x263e (0x4be51e in /usr/bin/python)
12:56:13 frame #28: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #29: /usr/bin/python() [0x4d5669]
12:56:13 frame #30: /usr/bin/python() [0x4eef5e]
12:56:13 frame #31: PyObject_Call + 0x3e (0x4a587e in /usr/bin/python)
12:56:13 frame #32: /usr/bin/python() [0x548fc3]
12:56:13 frame #33: PyEval_EvalFrameEx + 0x578d (0x4c166d in /usr/bin/python)
12:56:13 frame #34: PyEval_EvalFrameEx + 0x553f (0x4c141f in /usr/bin/python)
12:56:13 frame #35: PyEval_EvalFrameEx + 0x553f (0x4c141f in /usr/bin/python)
12:56:13 frame #36: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #37: /usr/bin/python() [0x4d57a3]
12:56:13 frame #38: /usr/bin/python() [0x4eef5e]
12:56:13 frame #39: /usr/bin/python() [0x4eeb66]
12:56:13 frame #40: /usr/bin/python() [0x4aaafb]
12:56:13 frame #41: PyEval_EvalFrameEx + 0x578d (0x4c166d in /usr/bin/python)
12:56:13 frame #42: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #43: PyEval_EvalFrameEx + 0x58e6 (0x4c17c6 in /usr/bin/python)
12:56:13 frame #44: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
12:56:13 frame #45: /usr/bin/python() [0x4eb69f]
12:56:13 frame #46: PyRun_FileExFlags + 0x82 (0x4e58f2 in /usr/bin/python)
12:56:13 frame #47: PyRun_SimpleFileExFlags + 0x186 (0x4e41a6 in /usr/bin/python)
12:56:13 frame #48: Py_Main + 0x54e (0x4938ce in /usr/bin/python)
12:56:13 frame #49: __libc_start_main + 0xf0 (0x7fa2c83fc830 in /lib/x86_64-linux-gnu/libc.so.6)
12:56:13 frame #50: _start + 0x29 (0x493299 in /usr/bin/python)
12:56:13 "
12:56:13 
12:56:13 ----------------------------------------------------------------------
12:56:13 Ran 1873 tests in 350.556s
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/17861/console

**Comment by ezyang** [comment]
This was fixed in https://github.com/pytorch/pytorch/commit/26f1c6d4d421995cb054ccc268a926d91551503c
