### ISSUE TITLE
TestJit.test_cpp broken on master

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19601]
## 🐛 Bug
```
Apr 23 05:09:48 ======================================================================
Apr 23 05:09:48 ERROR: test_cpp (__main__.TestJit)
Apr 23 05:09:48 ----------------------------------------------------------------------
Apr 23 05:09:48 Traceback (most recent call last):
Apr 23 05:09:48   File "/var/lib/jenkins/workspace/test/common_utils.py", line 129, in wrapper
Apr 23 05:09:48     fn(*args, **kwargs)
Apr 23 05:09:48   File "test_jit.py", line 1727, in test_cpp
Apr 23 05:09:48     torch._C._jit_run_cpp_tests(run_cuda=False)
Apr 23 05:09:48 RuntimeError: 
Apr 23 05:09:48 Schema not found for node. File a bug report.
Apr 23 05:09:48 Node: %3 : Tensor = aten::tensor(%2, %1, %0)
Apr 23 05:09:48 
Apr 23 05:09:48 Input types:float, int?, Device?
Apr 23 05:09:48 candidates were:
Apr 23 05:09:48   aten::tensor(float t, *, int? dtype=<default>, Device? device=<default>, bool requires_grad=<default>) -> Tensor
Apr 23 05:09:48   aten::tensor(int t, *, int? dtype=<default>, Device? device=<default>, bool requires_grad=<default>) -> Tensor
Apr 23 05:09:48   aten::tensor(bool t, *, int? dtype=<default>, Device? device=<default>, bool requires_grad=<default>) -> Tensor
Apr 23 05:09:48   aten::tensor(t[] data, *, int? dtype=<default>, Device? device=<default>, bool requires_grad=<default>) -> Tensor
Apr 23 05:09:48 graph():
Apr 23 05:09:48   %0 : Device? = prim::Constant()
Apr 23 05:09:48   %1 : int? = prim::Constant()
Apr 23 05:09:48   %2 : float = prim::Constant[value=1]()
Apr 23 05:09:48   %3 : Tensor = aten::tensor(%2, %1, %0)
Apr 23 05:09:48   %4 : Tensor[] = prim::ListConstruct(%3)
Apr 23 05:09:48   %5 : Tensor = aten::tensor(%2, %1, %0)
Apr 23 05:09:48   %6 : Tensor[] = prim::ListConstruct(%5)
Apr 23 05:09:48   %7 : (Tensor[], Tensor[]) = prim::TupleConstruct(%4, %6)
Apr 23 05:09:48   return (%7)
```

https://circleci.com/gh/pytorch/pytorch/1423249?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by SsnL** [comment]
Seems to be this patch https://github.com/pytorch/pytorch/pull/19445 cc @eellison

**Comment by suo** [comment]
Unlanding the offending patch
