### ISSUE TITLE
[jit] nn.LSTM errors in nn.ScriptModule

### ISSUE THREAD

**Issue by daiwei89** [pytorch/pytorch#19628]
## 🐛 Bug

Torch script errors on nn.LSTM due to return type mismatch.

## To Reproduce

run the following:

```python
from __future__ import print_function
import torch

class TestModule(torch.jit.ScriptModule):
    def __init__(self):
        super(TestModule, self).__init__()
        self.rnn = torch.nn.LSTM(10, 20, 2)

    @torch.jit.script_method
    def forward(self, x, seq_len):
        return self.rnn(x[:seq_len])

onnx_path = "test.onnx"
model = TestModule()
max_seq_len = 10
seq_len = 3
torch_in = (torch.randn(max_seq_len, 1, 10), torch.tensor(seq_len))
torch_out = model(*torch_in)
torch.onnx._export(model, torch_in, onnx_path,
    verbose=True,
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
    example_outputs=torch_out)
```

Error msg:

```
RuntimeError:
 expected value of type Tensor for return value but instead got value of type tuple.
Value: (tensor([[[ 0.0131, -0.0189, -0.0382, -0.0485, -0.0530,  0.0576, -0.0215,
          -0.0476,  0.0310, -0.0649,  0.0208,  0.0090,  0.0506, -0.0437,
          -0.0655, -0.0741, -0.0753,  0.0451,  0.0434,  0.0034]],

        [[ 0.0340, -0.0401, -0.0431, -0.0574, -0.0925,  0.1075, -0.0670,
          -0.0510,  0.0298, -0.1264,  0.0319,  0.0326,  0.0778, -0.0714,
          -0.1181, -0.0624, -0.1227,  0.0611,  0.0881,  0.0121]],

        [[ 0.0505, -0.0539, -0.0696, -0.0169, -0.0946,  0.1010, -0.0840,
          -0.0454,  0.0468, -0.1656,  0.0414,  0.0265,  0.0885, -0.0955,
          -0.1255, -0.0831, -0.1381,  0.0460,  0.0934, -0.0063]]],
       grad_fn=<StackBackward>), (tensor([[[ 0.0751, -0.0792,  0.1354, -0.1189,  0.0777,  0.1595,  0.0664,
           0.0679, -0.0291, -0.0530,  0.0622,  0.1268,  0.0217,  0.3393,
           0.0827, -0.0393,  0.0058,  0.1860, -0.1476, -0.0161]],

        [[ 0.0505, -0.0539, -0.0696, -0.0169, -0.0946,  0.1010, -0.0840,
          -0.0454,  0.0468, -0.1656,  0.0414,  0.0265,  0.0885, -0.0955,
          -0.1255, -0.0831, -0.1381,  0.0460,  0.0934, -0.0063]]],
       grad_fn=<StackBackward>), tensor([[[ 0.1532, -0.1940,  0.2310, -0.2605,  0.1665,  0.2493,  0.1354,
           0.3215, -0.1180, -0.1350,  0.3478,  0.3017,  0.0412,  0.5556,
           0.2099, -0.0888,  0.0103,  0.5196, -0.3361, -0.0461]],

        [[ 0.1015, -0.1073, -0.1859, -0.0310, -0.1853,  0.2024, -0.1587,
          -0.1042,  0.1006, -0.3469,  0.0950,  0.0528,  0.2027, -0.1976,
          -0.2762, -0.2110, -0.3665,  0.0898,  0.1874, -0.0121]]],
       grad_fn=<StackBackward>))):
operation failed in interpreter:
@torch.jit.script_method
def forward(self, x, seq_len):
    return self.rnn(x[:seq_len])
           ~~~~~~~~ <--- HERE
```

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

**Comment by driazati** [comment]
I can't seem to reproduce your error on master, but I do get a different ONNX related error (below). Could try your code with the PyTorch nightly version and see what happens?

```
Traceback (most recent call last):
  File "../test.py", line 67, in <module>
    example_outputs=torch_out)
  File "/home/pytorch/torch/onnx/__init__.py", line 19, in _export
    result = utils._export(*args, **kwargs)
  File "/home/pytorch/torch/onnx/utils.py", line 358, in _export
    _retain_param_name, do_constant_folding)
  File "/home/pytorch/torch/onnx/utils.py", line 254, in _model_to_graph
    method.graph, tuple(args) + tuple(params), example_outputs, False, propagate)
TypeError: _propagate_and_assign_input_and_output_shapes(): incompatible function arguments. The following argument types are
 supported:
    1. (arg0: torch._C.Graph, arg1: List[at::Tensor], arg2: List[at::Tensor], arg3: bool, arg4: bool) -> torch._C.Graph

Invoked with: graph(%x : Tensor,
      %seq_len : Tensor,
```

**Comment by Officium** [comment]
I can reproduce this issue.    
`torch.jit.script_method` wrapped function does not support tuple output in 1.0.1.post2 by design.
Discussions and possible solution can be found here https://github.com/pytorch/pytorch/issues/12801.

**Comment by bhosmer** [comment]
Recent master gives a different error on call to `_export`:
```
Traceback (most recent call last):
  File "scratch.py", line 22, in <module>
    example_outputs=torch_out)
  File "/Users/bhosmer/dev/pt/torch/onnx/__init__.py", line 26, in _export
    result = utils._export(*args, **kwargs)
  File "/Users/bhosmer/dev/pt/torch/onnx/utils.py", line 409, in _export
    fixed_batch_size=fixed_batch_size)
  File "/Users/bhosmer/dev/pt/torch/onnx/utils.py", line 262, in _model_to_graph
    method_graph, params = torch._C._jit_pass_lower_graph(model.forward.graph, model._c)
RuntimeError: isTensor() INTERNAL ASSERT FAILED at ../aten/src/ATen/core/ivalue_inl.h:90, please report a bug to PyTorch. Expected Tensor but got Bool (toTensor at ../aten/src/ATen/core/ivalue_inl.h:90)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 64 (0x10a7e2d80 in libc10.dylib)
frame #1: c10::IValue::toTensor() const & + 326 (0x113249cb6 in libtorch.dylib)
frame #2: torch::jit::LowerGraph(torch::jit::Graph&, c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > const&) + 158 (0x1160436ce in libtorch.dylib)
frame #3: void pybind11::cpp_function::initialize<torch::jit::initJITBindings(_object*)::$_20, std::__1::pair<std::__1::shared_ptr<torch::jit::Graph>, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> > >, std::__1::shared_ptr<torch::jit::Graph>&, torch::jit::script::Module const&, pybind11::name, pybind11::scope, pybind11::sibling>(torch::jit::initJITBindings(_object*)::$_20&&, std::__1::pair<std::__1::shared_ptr<torch::jit::Graph>, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> > > (*)(std::__1::shared_ptr<torch::jit::Graph>&, torch::jit::script::Module const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 242 (0x112a5b062 in libtorch_python.dylib)
frame #4: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3779 (0x1124715d3 in libtorch_python.dylib)
<omitting python frames>
frame #24: start + 1 (0x7fff6690c2e5 in libdyld.dylib)
frame #25: 0x0 + 2 (0x2 in ???)
```
Looks like the first slot value loaded [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/lower_graph.cpp#L121) is indeed a `Bool`, not a `Tensor`.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
