### ISSUE TITLE
Why nn.Sequential can't handle multiple input?

### ISSUE THREAD

**Issue by PistonY** [pytorch/pytorch#19808]
## ❓ Questions and Help
Only use `nn.Module` multiple input is work.
```python
import torch
from torch import nn

class mylayer(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 1, 1, bias=False)
        self.conv2 = nn.Conv2d(3, 32, 1, 1, bias=False)

    def forward(self, *input):
        x1, x2 = input
        y1 = self.conv1(x1)
        y2 = self.conv2(x2)
        return y1, y2

td = torch.rand(1, 3, 32, 32).cuda()
model = mylayer().cuda()
print(model(td, td))
```
But when I using `nn.Sequential`
```python
seq = nn.Sequential(mylayer(), mylayer())
out = seq(td, td)
```
Raise an error 
```
Traceback (most recent call last):
  File "C:/Users/soulf/PycharmProjects/pytorch-face/test.py", line 21, in <module>
    out = seq(td, td)
  File "C:\Users\soulf\AppData\Local\conda\conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```
Why this happened?Do you have any way to fix this?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by PistonY** [comment]
Ok,but are you sure it’s not a bug?

**Comment by soumith** [comment]
it's not a bug. Sequential does not handle multiple inputs.

**Comment by PistonY** [comment]
@soumith Hi, I changed `nn.Sequential` to this
```python
class mySequential(nn.Sequential):
    def forward(self, *input):
        for module in self._modules.values():
            input = module(*input)
        return input
```
And it could handle multiple inputs/outputs only need the number of outputs from the previous layer equals the number of inputs from the next layer.
```python
class n_to_n(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 3, 1, 1, bias=False)
        self.conv2 = nn.Conv2d(3, 3, 1, 1, bias=False)

    def forward(self, x1, x2):
        y1 = self.conv1(x1)
        y2 = self.conv2(x2)
        return y1, y2


class n_to_one(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 3, 1, 1, bias=False)
        self.conv2 = nn.Conv2d(3, 3, 1, 1, bias=False)

    def forward(self, x1, x2):
        y1 = self.conv1(x1)
        y2 = self.conv2(x2)
        return y1 + y2


class one_to_n(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 3, 1, 1, bias=False)
        self.conv2 = nn.Conv2d(3, 3, 1, 1, bias=False)

    def forward(self, x):
        y1 = self.conv1(x)
        y2 = self.conv2(x)
        return y1, y2

seq = mySequential(one_to_n(), n_to_n(), n_to_one()).cuda()
td = torch.rand(1, 3, 32, 32).cuda()

out = seq(td)
print(out.size())
```
```shell
torch.Size([1, 3, 32, 32])
```
What do you think?

**Comment by fmassa** [comment]
@PistonY check this comment https://github.com/pytorch/pytorch/pull/9979#issuecomment-408927000 and, more generally the PR.

It implements almost exactly what you mentioned, I wonder if the comments there apply here?

**Comment by PistonY** [comment]
Yes, It's the same thing totally.But @soumith  code should be more reasonable and solve my questions.

```python
class mySequential(nn.Sequential):
    def forward(self, inputs):
        for module in self._modules.values():
            if type(inputs) == tuple:
                inputs = module(*inputs)
            else:
                inputs = module(inputs)
        return inputs
```
If you don't want to change it. I just inherit `nn.Sequential` and write my own should be OK.

**Comment by GeislerSimon** [comment]
You can simply use `kwargs`. At least in PyTorch 1.4.0 they are passed properly through the `nn.Sequential` module to the subsequent module. So simply use `module(x1=x1, x2=x2, x3=x3)` instead.
