### ISSUE TITLE
Inconsistency: can instantiate Tensor from List, but cannot instantiate Variable

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#1986]
```
    V = torch.Tensor([
        [0.7, 0],
        [0.3, 0],
        [0.2, 0]
    ])
```
=> Ok

```
    V = autograd.Variable([
        [0.7, 0],
        [0.3, 0],
        [0.2, 0]
    ])
```
=> Fail

**Comment by albanD** [comment]
`Variable`s can only be built from an existing `Tensor`. This is expected behavior.

**Comment by hughperkins** [comment]
It is undeniably true that existing Variables can oly be built from an existing Tensor.  And it is expected behavior.  whether it is desirable behavior is less clear:
- per the docs: "Variable API is nearly the same as regular Tensor API (with the exception of a couple in-place methods, that would overwrite inputs required for gradient computation)."
- in practice, it would likely be trivial to add code to the `Variable` cosntructor, that checks if the incoming Value is a `Tensor`, and sends ti to the `Tensor` constructor, if it's not

**Comment by hughperkins** [comment]
Thats interesting. I tried throwing a `__init__` onto `Variable`, but seems it is not quite so simple as I assert :-)

```
    def __init__(self, tensor_or_array, requires_grad=False):
        print('Variable.__init__', tensor_or_array)
        # super(Variable, self).__init__(tensor_or_array, requires_grad=requires_grad)
        # _C._VariableBase.__init__(self, tensor_or_array, requires_grad=requires_grad)
        _C._VariableBase.__init__(self, tensor_or_array, requires_grad=requires_grad)
        print('self', self)
        print('dir(self)', dir(self))
        print('self.creator', self.creator)
```

Result:
```
dir(self) ['__add__', '__bool__', '__class__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__init_subclass__', '__ipow__', '__isub__', '__iter__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_add', '_addcop', '_advanced_index_add', '_backward_hooks', '_blas', '_execution_engine', '_fallthrough_methods', '_get_type', '_grad', '_grad_fn', '_static_blas', '_sub', '_torch', '_version', 'abs', 'acos', 'add', 'add_', 'addbmm', 'addbmm_', 'addcdiv', 'addcdiv_', 'addcmul', 'addcmul_', 'addmm', 'addmm_', 'addmv', 'addmv_', 'addr', 'addr_', 'asin', 'atan', 'backward', 'baddbmm', 'baddbmm_', 'bernoulli', 'bmm', 'byte', 'ceil', 'char', 'chunk', 'clamp', 'clone', 'contiguous', 'cos', 'cosh', 'cpu', 'cross', 'cuda', 'cumprod', 'cumsum', 'data', 'detach', 'detach_', 'diag', 'dist', 'div', 'div_', 'dot', 'double', 'eq', 'exp', 'exp_', 'expand', 'expand_as', 'float', 'floor', 'fmod', 'frac', 'gather', 'ge', 'ger', 'gesv', 'grad', 'grad_fn', 'gt', 'half', 'index_add', 'index_add_', 'index_copy', 'index_copy_', 'index_fill', 'index_fill_', 'index_select', 'int', 'inverse', 'is_leaf', 'is_same_size', 'kthvalue', 'le', 'lerp', 'log', 'log1p', 'long', 'lt', 'masked_copy', 'masked_copy_', 'masked_fill', 'masked_fill_', 'masked_scatter', 'masked_scatter_', 'masked_select', 'matmul', 'max', 'mean', 'median', 'min', 'mm', 'mode', 'mul', 'mul_', 'multinomial', 'mv', 'narrow', 'ne', 'neg', 'neg_', 'norm', 'output_nr', 'permute', 'pow', 'prod', 'reciprocal', 'register_hook', 'reinforce', 'remainder', 'renorm', 'repeat', 'requires_grad', 'resize', 'resize_as', 'round', 'rsqrt', 'scatter', 'scatter_', 'scatter_add', 'scatter_add_', 'select', 'short', 'sigmoid', 'sigmoid_', 'sign', 'sin', 'sinh', 'sort', 'split', 'sqrt', 'squeeze', 'squeeze_', 'std', 'sub', 'sub_', 'sum', 't', 'tan', 'tanh', 'tanh_', 'topk', 'trace', 'transpose', 'tril', 'triu', 'trunc', 'type', 'type_as', 'unfold', 'unsqueeze', 'var', 'view', 'view_as', 'volatile']
Traceback (most recent call last):
  File "testgrad.py", line 9, in <module>
    a_var = autograd.Variable(a, requires_grad=True)
  File "/home/ubuntu/conda3/envs/pytorch-dev/lib/python3.6/site-packages/torch/autograd/variable.py", line 53, in __init__
    print('self.creator', self.creator)
  File "/home/ubuntu/conda3/envs/pytorch-dev/lib/python3.6/site-packages/torch/autograd/variable.py", line 73, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'creator'
```

**Comment by hughperkins** [comment]
Ah, the error about `creator` is some issue in latest `master`, unrealted to this change. Although, there is an __init__ creatd on the cside. But that should be handle-able. Maybe

**Comment by apaszke** [comment]
I don't think there's any good way to handle creating Variables from lists -- it's hard to infer what tensor type to choose. We're not aiming for total compatibility of Tensor and Variable interfaces.
