### ISSUE TITLE
random module conflict

### ISSUE THREAD

**Issue by lmxhappy** [pytorch/pytorch#19943]
```
localhost:torch didi$ python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/didi/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 179, in <module>
    from .serialization import save, load
  File "/Users/didi/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 10, in <module>
    import tempfile
  File "/Users/didi/anaconda3/lib/python3.7/tempfile.py", line 45, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random' from 'random' (/Users/didi/anaconda3/lib/python3.7/site-packages/torch/random.py)
```
in tempfile.py when importing random it is to find the random module of torch instead of the sys random module

**Comment by soumith** [comment]
this is because you are running it from `/Users/didi/anaconda3/lib/python3.7/site-packages/torch/` or `/Users/didi/anaconda3/lib/python3.7/site-packages/torch/` is in your PYTHONPATH
