### ISSUE TITLE
RuntimeError: invalid argument 10: ldb should be at least max(1, 0), but have 0 at ../aten/src/TH/generic/THBlas.cpp:36

### ISSUE THREAD

**Issue by ZaydH** [pytorch/pytorch#20006]
## 🐛 Bug

Runtime error: 

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 20, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/zayd/repos/uo/double_decoder/driver.py", line 104, in <module>
    _main(_args, _pos_db, _unlabel_db, _enc_dim, [_args.pos_label])
  File "/Users/zayd/repos/uo/double_decoder/driver.py", line 62, in _main
    deep_pu.train_pu(p_db=pos_db, u_db=u_db, f_loss=DeepPU.simple_loss, quiet_mode=args.q)
  File "/Users/zayd/repos/uo/double_decoder/deep_pu.py", line 473, in train_pu
    loss.backward()
  File "/Users/zayd/.pyenv/versions/3.7.1/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/zayd/.pyenv/versions/3.7.1/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid argument 10: ldb should be at least max(1, 0), but have 0 at ../aten/src/TH/generic/THBlas.cpp:365
```

## To Reproduce

I do not get this in all cases.  I get it on an autoencoder with two decoders.  I did not get this error in 1.0.0.  I can dig into it more and try to make a streamlined MWE if the devs are unsure what could cause this.

## Expected behavior

In 1.0.0, this did not raise an issue.  It just pushed the loss backwards as expected.

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.4
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.16.1
[pip3] torch==1.1.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.1
[conda] Could not collect

**Comment by episodeyang** [comment]
I am having the same issue

**Comment by ZaydH** [comment]
@episodeyang Is it possible you somehow get a weird batch of size 0 or an output from a linear block of zero?

**Comment by episodeyang** [comment]
@ZaydH that is the problem! Thanks for your useful comment.

**Comment by ZaydH** [comment]
@episodeyang Was the program the batch size or the linear block of size zero?

@zhangguanheng66 is it worth putting a check into the linear block creation to ensure valid sizes?  Seems like an easy way to prevent weird/unexpected behavior.

**Comment by zhangguanheng66** [comment]
thanks @zaydh . We will accept the PR to fix it.

**Comment by ucalyptus** [comment]
@zhangguanheng66 was the PR created? Getting this error in Pysyft as well wrt lda.
https://github.com/OpenMined/PySyft/issues/2861
