### ISSUE TITLE
Implement similar PyTorch function as model.summary() in keras?

### ISSUE THREAD

**Issue by vibrantabhi19** [pytorch/pytorch#2001]
`model.summary` in keras gives a very fine visualization of your model and it's very convenient when it comes to debugging the network. Can we try to implement something like it in PyTorch?

**Comment by apaszke** [comment]
What kind of information that's not in `str(model)` would you like to see? Output shapes?

**Comment by ncullen93** [comment]
Sure you can! Here's something to get you started. (Adapted from other code, so it's not tested in the wild)

```python
    def summary(self, input_size):
        def register_hook(module):
            def hook(module, input, output):
                class_name = str(module.__class__).split('.')[-1].split("'")[0]
                module_idx = len(summary)

                m_key = '%s-%i' % (class_name, module_idx+1)
                summary[m_key] = OrderedDict()
                summary[m_key]['input_shape'] = list(input[0].size())
                summary[m_key]['input_shape'][0] = -1
                summary[m_key]['output_shape'] = list(output.size())
                summary[m_key]['output_shape'][0] = -1

                params = 0
                if hasattr(module, 'weight'):
                    params += th.prod(th.LongTensor(list(module.weight.size())))
                    if module.weight.requires_grad:
                        summary[m_key]['trainable'] = True
                    else:
                        summary[m_key]['trainable'] = False
                if hasattr(module, 'bias'):
                    params +=  th.prod(th.LongTensor(list(module.bias.size())))
                summary[m_key]['nb_params'] = params
                
            if not isinstance(module, nn.Sequential) and \
               not isinstance(module, nn.ModuleList) and \
               not (module == self.model):
                hooks.append(module.register_forward_hook(hook))

        if isinstance(input_size[0], list):
            x = [Variable(th.rand(1,*in_size)) for in_size in input_size]
        else:
            x = Variable(th.rand(1,*input_size))

        # create properties
        summary = OrderedDict()
        hooks = []
        # register hook
        model.apply(register_hook)
        # make a forward pass
        model(x)
        # remove these hooks
        for h in hooks:
            h.remove()

        return summary
```

**Comment by vibrantabhi19** [comment]
@apaszke `str(output)` works well for most cases but missed out on some `output_shape` is one of them
@ncullen93 The code looks works well. Can we think about a PR with some code refactoring to this?

**Comment by aditya1702** [comment]
Hello, I am new to pytorch and contributing to it. Can I try this one out?

**Comment by vibrantabhi19** [comment]
@aditya1702  yeah sure, as my information goes till now we don't have any functions to see the output_size and something similiar to keras model.summary

**Comment by EtienneDesticourt** [comment]
I think it would be useful to add hooks to the output of str(model).
I use str(model) in my logging system and currently I can't know whether my models used weight normalizations or not since it's a hook.

**Comment by isaykatsman** [comment]
After @ncullen93 posted his code, I added model summary to my local build of pytorch, and recently decided to clean the code up a little and make a PR. Can hopefully merge soon.

**Comment by vibrantabhi19** [comment]
Hi @isaykatsman the implementation is nice. Thanks.

**Comment by HTLife** [comment]
@ncullen93 
It that 'Variable' at the line `x = Variable(th.rand(1,*input_size))` a package?
How can I deal with this error?
```
global name 'Variable' is not defined
```

**Comment by apaszke** [comment]
`from torch.autograd import Variable`

**Comment by HTLife** [comment]
@apaszke 
I'm now running into this error
```bash
TypeError: initializer for ctype 'struct THCudaTensor *' must be a pointer to same type, not cdata 'struct THFloatTensor *'
```
I suspect that the dummy data generated by `Variable(th.rand(1,*input_size))` has wrong type.
How to generate THCudaTensor data type dummy data?

**Comment by HTLife** [comment]
I did some [modification ](https://gist.github.com/HTLife/b6640af9d6e7d765411f8aa9aa94b837)on the print out style to fit the style of Keras.  Hope it helps.

![_031618_024018_pm](https://user-images.githubusercontent.com/4699179/37507094-f99ace62-2927-11e8-8162-eb2f87ac8c91.jpg)
![_031618_023944_pm](https://user-images.githubusercontent.com/4699179/37507096-fb00beba-2927-11e8-9beb-e8ebb3d52aaa.jpg)

**Comment by backpropper** [comment]
This doesn't work for LSTM's.

**Comment by ShuvenduBikash** [comment]
It does not work with sequential() function. Do you have a solution for this?

```
class Discriminator(nn.Module):
    def __init__(self, in_channels=3):
        super(Discriminator, self).__init__()

        def discriminator_block(in_filters, out_filters, normalize=True):
            """Returns downsampling layers of each discriminator block"""
            layers = [nn.Conv2d(in_filters, out_filters, 4, stride=2, padding=1)]
            if normalize:
                layers.append(nn.InstanceNorm2d(out_filters))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers

        self.model = nn.Sequential(
            *discriminator_block(in_channels, 64, normalize=False),
            *discriminator_block(64, 128),
            *discriminator_block(128, 256),
            *discriminator_block(256, 512),
            nn.ZeroPad2d((1, 0, 1, 0)),
            nn.Conv2d(512, 1, 4, padding=1)
        )

    def forward(self, img):
        return self.model(img)

```


```
Traceback (most recent call last):
  File ".\test.py", line 118, in <module>
    summary(model, (3, 28, 28))
  File "C:\Users\bikas\Anaconda3\lib\site-packages\torchsummary\torchsummary.py", line 57, in summary
    model(x)
  File "C:\Users\bikas\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File ".\test.py", line 93, in forward
    return self.model(img)
  File "C:\Users\bikas\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\bikas\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\bikas\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    hook_result = hook(self, input, result)
  File "C:\Users\bikas\Anaconda3\lib\site-packages\torchsummary\torchsummary.py", line 26, in hook
    params += torch.prod(torch.LongTensor(list(module.weight.size())))
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by jongwook** [comment]
I wanted minimal changes but wanted to show the number of parameters, like: 

![image](https://user-images.githubusercontent.com/266841/42837079-013e5d74-89cb-11e8-9b49-25197774e743.png)

```python
def summary(model, file=sys.stderr):
    def repr(model):
        # We treat the extra repr like the sub-module, one item per line
        extra_lines = []
        extra_repr = model.extra_repr()
        # empty string will be split into list ['']
        if extra_repr:
            extra_lines = extra_repr.split('\n')
        child_lines = []
        total_params = 0
        for key, module in model._modules.items():
            mod_str, num_params = repr(module)
            mod_str = _addindent(mod_str, 2)
            child_lines.append('(' + key + '): ' + mod_str)
            total_params += num_params
        lines = extra_lines + child_lines

        for name, p in model._parameters.items():
            total_params += reduce(lambda x, y: x * y, p.shape)

        main_str = model._get_name() + '('
        if lines:
            # simple one-liner info, which most builtin Modules will use
            if len(extra_lines) == 1 and not child_lines:
                main_str += extra_lines[0]
            else:
                main_str += '\n  ' + '\n  '.join(lines) + '\n'

        main_str += ')'
        if file is sys.stderr:
            main_str += ', \033[92m{:,}\033[0m params'.format(total_params)
        else:
            main_str += ', {:,} params'.format(total_params)
        return main_str, total_params

    string, count = repr(model)
    if file is not None:
        print(string, file=file)
    return count
```

**Comment by PistonY** [comment]
> What kind of information that's not in `str(model)` would you like to see? Output shapes?

Total parameters and total FLOPS.

**Comment by VCBE123** [comment]
Can i draw the forward  pass graph similar to torchviz ? 
If i summary the model and get the visulization, that would be good.

**Comment by zamnius** [comment]
NameError: name 'th' is not defined
For example in the line: x = [Variable(th.rand(1,*in_size)).type(dtype) for in_size in input_size]
What is missing?

**Comment by hmrishavbandy** [comment]
@zamnius , here are the complete list of imports:

```
from torch.autograd import Variable
import torch as th
from torch import nn as nn
from collections import OrderedDict
from model import UNet3D
```
@ShuvenduBikash , this is probably what you figured out:
The lines 15-22 should be like this as all layers dont have bias.

```
                if hasattr(module,'weight') and module.weight is not None:
                    params += th.prod(th.LongTensor(list(module.weight.size())))
                    if module.weight.requires_grad:
                        summary[m_key]['trainable'] = True
                    else:
                        summary[m_key]['trainable'] = False
                if hasattr(module,'bias') and module.bias is not None:
                    params +=  th.prod(th.LongTensor(list(module.bias.size())))

```

**Comment by zou3519** [comment]
I don't remember why this was originally in the low-priority bin, but I'm tentatively marking this as triage review for discussion on whether or not this should be high-pri

**Comment by jbschlosser** [comment]
Removing high-pri for now since this is provided by [pytorch-summary](https://github.com/sksq96/pytorch-summary), which appears to work for most cases described here (including `nn.Sequential` models).

As of now, I don't see huge benefits to maintaining this within PyTorch core and would prefer to keep it in the separate repo, but I'm open to being convinced otherwise if it doesn't support your use case, etc.

**Comment by tuiiitendinh** [comment]
Hi, i'm new to pytorch.
Is there anyway to plot the graph of the model as well as export the sumary of the model without initialize an instance of the model? Like Keras, I would just load the model and then visualize it.
