### ISSUE TITLE
distributed tests failed on MAC

### ISSUE THREAD

**Issue by lynic** [pytorch/pytorch#2002]
I build pytorch from source.

All distributed tests failed on MAC:
Running distributed tests for the TCP backend
Process process 0:
Process process 1:
Process process 2:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/pytorch-dev/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/pytorch-dev/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./test_distributed.py", line 534, in _run
    getattr(self, self.id().split(".")[2])()
  File "./test_distributed.py", line 493, in wrapper
    fn(self)
  File "./test_distributed.py", line 445, in test_all_gather
    group, group_id, rank = self._init_global_test()
  File "./test_distributed.py", line 90, in _init_global_test
    group = [i for i in range(0, dist.get_world_size())]
AttributeError: module 'torch.distributed' has no attribute 'get_world_size'
......
FAILED (failures=31, skipped=2)

Is it normal?

**Comment by lynic** [comment]
okay, because I set NO_DISTRIBUTED=1 when I build pytorch from source.
