### ISSUE TITLE
MultivariateNormal fails with CUDA

### ISSUE THREAD

**Issue by kefirski** [pytorch/pytorch#20100]
## 🐛 Bug

MultivariateNormal fails on CUDA

## To Reproduce

For example, cpu version works fine

```
x = MultivariateNormal(t.ones(5, 3), t.eye(3))
x.log_prob(x.sample())
tensor([ -2.9737,  -4.3816,  -3.1320, -10.9442,  -3.1390])
```

But if I try to create  MultivariateNormal instance with CUDA tensors then:

```
x = MultivariateNormal(t.ones(5, 3).cuda(), t.eye(3).cuda())

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/distributions/multivariate_normal.py", line 142, in __init__
    self._unbroadcasted_scale_tril = torch.cholesky(self.covariance_matrix)
RuntimeError: CUDA error: invalid device function
```

I tried to workaround this issue by creating instance not from covariance matrix, but from `scale_tril`, but in this case `log_prob` method fails

```
x = MultivariateNormal(t.ones(5, 3).cuda(), scale_tril=t.eye(3).cuda())
x.sample()

tensor([[0.8211, 1.6837, 2.3296],
        [0.1134, 3.0275, 0.6402],
        [0.5820, 1.3581, 1.0628],
        [0.6996, 1.1009, 0.7085],
        [1.6969, 0.0917, 1.7386]], device='cuda:0')

x.log_prob(x.sample())

THCudaCheck FAIL file=/opt/pytorch/aten/src/THC/generic/THCTensorMathPointwise.cu line=324 error=98 : invalid device function
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/distributions/multivariate_normal.py", line 199, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributions/multivariate_normal.py", line 57, in _batch_mahalanobis
    M_swap = torch.triangular_solve(flat_x_swap, flat_L, upper=False)[0].pow(2).sum(-2)  # shape = b x c
RuntimeError: cuda runtime error (98) : invalid device function at /opt/pytorch/aten/src/THC/generic/THCTensorMathPointwise.cu:324
```

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.1.105

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 418.43
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[conda] blas                      1.0                         mkl
[conda] magma-cuda100             2.5.0                         1    soumith
[conda] mkl                       2019.3                      199
[conda] mkl-include               2019.3                      199
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] mkldnn                    0.16.1                        0    mingfeima
[conda] torch                     1.1.0                    pypi_0    pypi
```

[Here](https://pastebin.com/5FBN6W9e) is Dockerfile where I build Pytorch

**Comment by SsnL** [comment]
Likely due to the fact that magma100 is incompatible with cuda 10.1. I created an issue for this #20103

**Comment by kefirski** [comment]
@SsnL You are right, downgraded CUDA version to 10.0, everything works fine
