### ISSUE TITLE
[JIT] Source highlighting doesn't line up when tabs are used for indentation

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#20119]
```
import torch

@torch.jit.script
def foo(x):
		return torch.neg(x).foo()
```

```
Traceback (most recent call last):
  File "tabs.py", line 3, in <module>
    @torch.jit.script
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/jit/__init__.py", line 826, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
RuntimeError:
unknown builtin op: aten::foo
Here are some suggestions:
	aten::pop
	aten::to
	aten::cos
	aten::pow
	aten::dot
	aten::floor
	aten::fmod
	aten::log
	aten::fft
:
@torch.jit.script
def foo(x):
		return torch.neg(x).foo()
         ~~~~~~~~~~~~~~~~ <--- HERE
```

**Comment by gvskalyan** [comment]
@jamesr66a Are you able to export models trained in onnx to fairseq . If so is it from https://github.com/bddppq/onnx-fairseq. Is it such an old version of fairseq?
Thanks.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
