### ISSUE TITLE
ERROR: Command "python setup.py egg_info" when dockerfile build

### ISSUE THREAD

**Issue by graykode** [pytorch/pytorch#20134]
## To Reproduce

`docker build -t pytorch -f Dockerfile .`
```shell
    ['cmake',
     '-GNinja',
     '-DBUILDING_WITH_TORCH_LIBS=ON',
     '-DBUILD_BINARY=False',
     '-DBUILD_CAFFE2_OPS=True',
     '-DBUILD_PYTHON=True',
     '-DBUILD_SHARED_LIBS=ON',
     '-DBUILD_TEST=True',
     '-DBUILD_TORCH=ON',
     '-DCAFFE2_STATIC_LINK_CUDA=False',
     '-DCMAKE_BUILD_TYPE=Release',
     '-DCMAKE_CXX_FLAGS= ',
     '-DCMAKE_C_FLAGS= ',
     '-DCMAKE_EXE_LINKER_FLAGS=',
     '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-keauxx9z/torch',
     '-DCMAKE_PREFIX_PATH=/opt/conda/bin/../',
     '-DCMAKE_SHARED_LINKER_FLAGS=',
     '-DINSTALL_TEST=True',
     '-DNCCL_EXTERNAL=True',
     '-DNCCL_INCLUDE_DIR=/usr/include',
     '-DNCCL_ROOT_DIR=/usr/',
     '-DNCCL_SYSTEM_LIB=/usr/lib/x86_64-linux-gnu/libnccl.so.2.4.2',
     '-DNUMPY_INCLUDE_DIR=/opt/conda/lib/python3.6/site-packages/numpy/core/include',
     '-DONNX_ML=False',
     '-DONNX_NAMESPACE=onnx_torch',
     '-DPYTHON_EXECUTABLE=/opt/conda/bin/python',
     '-DPYTHON_INCLUDE_DIR=/opt/conda/include/python3.6m',
     '-DPYTHON_LIBRARY=/opt/conda/lib/libpython3.6m.so.1.0',
     '-DTHD_SO_VERSION=1',
     '-DTORCH_BUILD_VERSION=1.1.0a0+fc00bfd',
     '-DUSE_CUDA=True',
     '-DUSE_DISTRIBUTED=True',
     '-DUSE_FBGEMM=True',
     '-DUSE_FFMPEG=False',
     '-DUSE_LEVELDB=False',
     '-DUSE_LMDB=False',
     '-DUSE_MKLDNN=True',
     '-DUSE_NCCL=True',
     '-DUSE_NNPACK=True',
     '-DUSE_NUMPY=True',
     '-DUSE_OPENCV=False',
     '-DUSE_QNNPACK=True',
     '-DUSE_ROCM=False',
     '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
     '-DUSE_SYSTEM_NCCL=True',
     '-DUSE_TENSORRT=False',
     '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON',
     '/tmp/pip-req-build-keauxx9z']
Cleaning up...
  Removing source in /tmp/pip-req-build-keauxx9z
Removed file:///opt/pytorch from build tracker '/tmp/pip-req-tracker-27yyn7rz'
Removed build tracker '/tmp/pip-req-tracker-27yyn7rz'
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-keauxx9z/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 368, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 177, in prep_for_dist
    self.req.prepare_metadata()
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 539, in prepare_metadata
    self.run_egg_info()
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 617, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-keauxx9z/
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 1
```

## Expected behavior

This will be issue
```dockerfile
RUN TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    pip install -v .
```

## Environment

 - PyTorch Version (e.g., 1.0): lastest
 - OS (e.g., Linux): Window10 Home
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `docker build -t pytorch -f Dockerfile .`
 - Python version: master
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

**Comment by jrapin** [comment]
I've run into a similar issue, and using a lower number of jobs (MAX_JOBS=4 instead of 36, in my case) *seems* to have solved it, so this could be a resource issue.

Also, in my case, the logs started printing errors before the final `command` error. Maybe you also have some?
```
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_at_kern.cpp.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/build.make:75: recipe for target 'third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8DepthwiseAvx2.cc.o' failed
    make[2]: *** [third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8DepthwiseAvx2.cc.o] Error 4
    CMakeFiles/Makefile2:1049: recipe for target 'third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/all' failed
    make[1]: *** [third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_bn_kern.cpp.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/field_mask_utility.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/json_escaping.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/json_objectwriter.cc.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/build.make:96: recipe for target 'third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_halving_doubling.cc.o' failed
    make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_halving_doubling.cc.o] Error 4
    make[2]: *** Waiting for unfinished jobs....
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/json_stream_parser.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/object_writer.cc.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_bt_kern.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_an_kern.cpp.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/proto_writer.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/protostream_objectsource.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/protostream_objectwriter.cc.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_at_kern.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_bn_kern.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_bt_kern.cpp.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/type_info.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/type_info_test_helper.cc.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/ref_gemm_s8x8s32.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_convolution.cpp.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/utility.cc.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_convolution_utils.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_inner_product.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_x8s8s32x_convolution.cpp.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/json_util.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/message_differencer.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/time_util.cc.o
    CMakeFiles/Makefile2:1386: recipe for target 'third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/all' failed
    make[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/all] Error 2
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/type_resolver_util.cc.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_x8s8s32x_inner_product.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_1x1_conv_kernel_f32.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_1x1_convolution.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_conv_kernel_f32.cpp.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wire_format.cc.o
    [ 34%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wrappers.pb.cc.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_convolution.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_1x1_conv_kernel.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_1x1_convolution.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_kernel.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_winograd_kernel_f32.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_convolution.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_convolution_winograd.cpp.o
    [ 34%] Linking CXX static library ../../../lib/libprotobuf.a
    [ 34%] Built target libprotobuf
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_lrn.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_fp32_wino_conv_2x3.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_fp32_wino_conv_4x3.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_fp32_wino_conv_4x3_kernel.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp.o
    [ 34%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_1x1_convolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_conv_kernel.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_convolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_deconvolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_1x1_conv_kernel_f32.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_1x1_convolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_conv_kernel_f32.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_convolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_batch_normalization.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_transpose_src_utils.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_dw_conv_kernel_f32.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_dw_convolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_eltwise.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_i8i8_pooling.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_lrn.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_lrn_kernel_f32.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_pool_kernel_f32.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_pooling.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_reorder.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/jit_uni_reorder_utils.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/nchw_pooling.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ncsp_batch_normalization.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/nhwc_pooling.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/nspc_batch_normalization.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_batch_normalization.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_convolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_deconvolution.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_eltwise.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_inner_product.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_lrn.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_pooling.cpp.o
    [ 35%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_shuffle.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/ref_softmax.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_common.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_gru.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_gru_lbr.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_lstm.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_rnn.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_rnn.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/rnn/rnn_utils.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/simple_concat.cpp.o
    [ 36%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/simple_sum.cpp.o
    [ 36%] Linking CXX static library ../../../../lib/libmkldnn.a
    [ 36%] Built target mkldnn
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-b0tuxohg/setup.py", line 725, in <module>
        build_deps()
      File "/tmp/pip-req-build-b0tuxohg/setup.py", line 285, in build_deps
        build_dir='build')
      File "/tmp/pip-req-build-b0tuxohg/tools/build_pytorch_libs.py", line 281, in build_caffe2
        check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
      File "/opt/conda/envs/pypg/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j', '12', 'install']' returned non-zero exit status 2.
    Building wheel torch-1.1.0
    -- Building version 1.1.0
    ['cmake',
     '-DBUILDING_WITH_TORCH_LIBS=ON',
     '-DBUILD_BINARY=False',
     '-DBUILD_CAFFE2_OPS=True',
     '-DBUILD_PYTHON=True',
     '-DBUILD_SHARED_LIBS=ON',
     '-DBUILD_TEST=True',
     '-DBUILD_TORCH=ON',
     '-DCAFFE2_STATIC_LINK_CUDA=False',
     '-DCMAKE_BUILD_TYPE=Release',
     '-DCMAKE_CXX_FLAGS= ',
     '-DCMAKE_C_FLAGS= ',
     '-DCMAKE_EXE_LINKER_FLAGS=',
     '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-b0tuxohg/torch',
     '-DCMAKE_PREFIX_PATH=/opt/conda/envs/pypg',
     '-DCMAKE_SHARED_LINKER_FLAGS=',
     '-DINSTALL_TEST=True',
     '-DNCCL_EXTERNAL=True',
     '-DNCCL_INCLUDE_DIR=/usr/include',
     '-DNCCL_ROOT_DIR=/usr/',
     '-DNCCL_SYSTEM_LIB=/usr/lib/x86_64-linux-gnu/libnccl.so.2.4.2',
     '-DNUMPY_INCLUDE_DIR=/opt/conda/envs/pypg/lib/python3.7/site-packages/numpy/core/include',
     '-DONNX_ML=False',
     '-DONNX_NAMESPACE=onnx_torch',
     '-DPYTHON_EXECUTABLE=/opt/conda/envs/pypg/bin/python',
     '-DPYTHON_INCLUDE_DIR=/opt/conda/envs/pypg/include/python3.7m',
     '-DPYTHON_LIBRARY=/opt/conda/envs/pypg/lib/libpython3.7m.so.1.0',
     '-DTHD_SO_VERSION=1',
     '-DTORCH_BUILD_VERSION=1.1.0',
     '-DUSE_CUDA=True',
     '-DUSE_DISTRIBUTED=True',
     '-DUSE_FBGEMM=True',
     '-DUSE_FFMPEG=False',
     '-DUSE_LEVELDB=False',
     '-DUSE_LMDB=False',
     '-DUSE_MKLDNN=True',
     '-DUSE_NCCL=True',
     '-DUSE_NNPACK=True',
     '-DUSE_NUMPY=True',
     '-DUSE_OPENCV=False',
     '-DUSE_QNNPACK=True',
     '-DUSE_ROCM=False',
     '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
     '-DUSE_SYSTEM_NCCL=True',
     '-DUSE_TENSORRT=False',
     '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON',
     '/tmp/pip-req-build-b0tuxohg']
Cleaning up...
  Removing source in /tmp/pip-req-build-b0tuxohg
Removed file:///root/pytorch from build tracker '/tmp/pip-req-tracker-khnvylrf'
Removed build tracker '/tmp/pip-req-tracker-khnvylrf'
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-b0tuxohg/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 362, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 171, in prep_for_dist
    self.req.prepare_metadata()
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 537, in prepare_metadata
    self.run_egg_info()
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 615, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/opt/conda/envs/pypg/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-b0tuxohg/
Exited with code 1
```
