### ISSUE TITLE
[ROCm CI] test_LPPool1d_cuda occassional SIGIOT

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#20196]
```
23:57:08 test_LPPool1d_cuda (__main__.TestNN) ... Memory access fault by GPU node-5 (Agent handle: 0x25b3ed0) on address 0x7fa7236ca000. Reason: Page not present or supervisor privilege.
23:57:20 Traceback (most recent call last):
23:57:20   File "test/run_test.py", line 439, in <module>
23:57:20     main()
23:57:20   File "test/run_test.py", line 431, in main
23:57:20     raise RuntimeError(message)
23:57:20 RuntimeError: test_nn failed! Received signal: SIGIOT
```
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-test/10657/console

**Comment by jeffdaily** [comment]
Issue no longer observed in latest CI runs.

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm3.9-py3.6-test1/1998/consoleText

```
test_LPPool1d (__main__.TestNN) ... ok
test_LPPool1d_cuda (__main__.TestNN) ... ok
test_LPPool1d_norm (__main__.TestNN) ... ok
test_LPPool1d_norm_cuda (__main__.TestNN) ... ok
```
