### ISSUE TITLE
test_namedtuple_return is flakey

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#20198]
```
May 07 00:00:01 ======================================================================
May 07 00:00:01 ERROR: test_namedtuple_return (__main__.TestNamedTupleAPI)
May 07 00:00:01 ----------------------------------------------------------------------
May 07 00:00:01 Traceback (most recent call last):
May 07 00:00:01   File "test_namedtuple_return_api.py", line 93, in test_namedtuple_return
May 07 00:00:01     ret = b.pstrf()
May 07 00:00:01   File "/opt/python/nightly/lib/python3.7/site-packages/torch/tensor.py", line 259, in pstrf
May 07 00:00:01     return super(Tensor, self).pstrf(upper=upper)
May 07 00:00:01 RuntimeError: Lapack Error pstrf : matrix is rank deficient or not positive semidefinite at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorLapack.cpp:617
May 07 00:00:01 
May 07 00:00:01 ----------------------------------------------------------------------
```

**Comment by VitalyFedyunin** [comment]
cc @zou3519

**Comment by VitalyFedyunin** [comment]
Do you mind if I assign it to you, so you can reroute later?

**Comment by zou3519** [comment]
I'm not the point person for linear algebra and/or named tuple returns. I think maybe @zasdfgbnm was working on named tuple returns?

**Comment by zasdfgbnm** [comment]
@zou3519 Yes, this test was added by me, I will take a look.
