### ISSUE TITLE
RuntimeError: Not compiled with GPU support ( win10 )

### ISSUE THREAD

**Issue by img5d** [pytorch/pytorch#20254]
## ❓ Questions and Help

Hey , guys, I`m a beginner.I need a help.

When i tried maskrcnn-benchmark, at last i encountered the issues as the title: 

RuntimeError: Not compiled with GPU support (nms at c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\csrc\nms.h:22)
(no backtrace available)
[ WARN:0] terminating async callback

The method i used is Step-by-step installation 
(Anaconda3→Creating Virtual Environment →ipython→ maskrcnn_benchmark and coco api dependencies → conda install pytorch torchvision cudatoolkit=9.0 -c pytorch → install pycocotools → apex → download maskrcnn-benchmark → revise SigmodiFocalLoss_cuda.cu → instal  maskrcnn-benchmark , run demo test
 )
and my enviroment is 
win10.
Pytorch 1.1 
py3.6 cuda90 cudnn7.1
torchvision 0.2.2

The whole information as below:

Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 71, in main
    composite = coco_demo.run_on_opencv_image(img)
  File "C:\Users\GS63VR\train\maskrcnn-benchmark\demo\predictor.py", line 172, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "C:\Users\GS63VR\train\maskrcnn-benchmark\demo\predictor.py", line 205, in compute_prediction
    predictions = self.model(image_list)
  File "C:\Users\GS63VR\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\modeling\detector\generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "C:\Users\GS63VR\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\rpn.py", line 161, in forward
    return self._forward_test(anchors, objectness, rpn_box_regression)
  File "c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\rpn.py", line 187, in _forward_test
    boxes = self.box_selector_test(anchors, objectness, rpn_box_regression)
  File "C:\Users\GS63VR\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\inference.py", line 140, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\inference.py", line 120, in forward_for_single_feature_map
    score_field="objectness",
  File "c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\structures\boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
  File "C:\Users\GS63VR\Anaconda3\envs\test\lib\site-packages\apex-0.1-py3.6.egg\apex\amp\amp.py", line 22, in wrapper
RuntimeError: Not compiled with GPU support (nms at c:\users\gs63vr\train\maskrcnn-benchmark\maskrcnn_benchmark\csrc\nms.h:22)
(no backtrace available)
[ WARN:0] terminating async callback

**Comment by vishwakftw** [comment]
I believe this issue pertains to [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark).
