### ISSUE TITLE
 python setup.py install erroy

### ISSUE THREAD

**Issue by ytgcljj** [pytorch/pytorch#20312]
launchx-500-10802@launchx50010802:~/github/pytorch$ python setup.py install
Building wheel torch-1.1.0a0+d24c0aa
-- Building version 1.1.0a0+d24c0aa
make: *** No rule to make target 'install'。 停止。
Traceback (most recent call last):
  File "setup.py", line 728, in <module>
    build_deps()
  File "setup.py", line 294, in build_deps
    build_dir='build')
  File "/home/launchx-500-10802/github/pytorch/tools/build_pytorch_libs.py", line 291, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/home/launchx-500-10802/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', 'install']' returned non-zero exit status 2.

**Comment by ailzhang** [comment]
Hey Could you reopen the issue using our bug report template and collect the necessary env info? It's hard to tell without enough error messages. Thanks!
