### ISSUE TITLE
cat()/stack() calls in JIT do not accept lists of tensors

### ISSUE THREAD

**Issue by HapeMask** [pytorch/pytorch#20335]
## 🐛 Bug

When including a call to `th.cat(tensors)` in a ScriptModule, if `tensors` is a tuple of tensors the ScriptModule can be constructed, but if `tensors` is a list of tensors, the construction fails.

## To Reproduce

Run this short repro example:
```python
import torch as th

def f():
    return th.ones(3), th.ones(3)

class Mod(th.jit.ScriptModule):
    def __init__(self):
        super().__init__()
        self.fn = th.jit.trace(f, tuple())

    @th.jit.script_method
    def forward(self):
        x1, x2 = self.fn()
        return th.cat([x1, x2], dim=1) # <---- Fails
        #return th.cat((x1, x2), dim=1) # <---- Succeeds

mod = Mod()
```

The module will fail to construct unless the first cat() call is replaced w/the second.

## Expected behavior

cat() / stack() accepts lists or tuples of  #tensors

## Environment

 - PyTorch Version (e.g., 1.0): 1.1
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.7

## Additional Info

Stack trace of failed construction:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    mod = Mod()
  File ".../lib/python3.7/site-packages/torch/jit/__init__.py", line 1049, in init_then_register                                    
    _create_methods_from_stubs(self, methods)
  File ".../lib/python3.7/site-packages/torch/jit/__init__.py", line 1014, in _create_methods_from_stubs                            
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError:
arguments for call are not valid:

  for operator aten::cat(Tensor[] tensors, int dim=<default>) -> Tensor:
  expected a value of type Tensor[] for argument 'tensors' but found Tensor[]
  Empty lists default to List[Tensor]. Use torch.jit.annotate(List[my_type], []) to create an empty list of another type                                                                 
  @th.jit.script_method
  def forward(self):
      x1, x2 = self.fn()
      return th.cat([x1, x2], dim=1) # <---- Fails
                    ~~~~~~~ <--- HERE

  for operator aten::cat(Tensor[] tensors, int dim=<default>, *, Tensor out) -> Tensor:
  expected a value of type Tensor[] for argument 'tensors' but found Tensor[]
  Empty lists default to List[Tensor]. Use torch.jit.annotate(List[my_type], []) to create an empty list of another type                                                                 
  @th.jit.script_method
  def forward(self):
      x1, x2 = self.fn()
      return th.cat([x1, x2], dim=1) # <---- Fails
                    ~~~~~~~ <--- HERE
for call at:
@th.jit.script_method
def forward(self):
    x1, x2 = self.fn()
    return th.cat([x1, x2], dim=1) # <---- Fails
           ~~~~~~ <--- HERE
```

**Comment by suo** [comment]
@driazati can you take a look? it appears whatever type promotion we have for lists isn't working

**Comment by eellison** [comment]
This is fixed on master. Reopen if you are still having issues

**Comment by HapeMask** [comment]
@eellison thanks for the fix. I do see the above sample working properly now on master, but I have another example of what appears to be the same bug under different circumstances still present in the latest nightly. I've provided another repro below. I realize it probably looks very contrived but this is a minified version of something that's happening in my real code.

```python
import torch as th

class Mod(th.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return th.cat(2*[x], dim=0)
        #return th.cat((x, x), dim=0) <-- Unlike before, this will still cause the load below to fail.

class ScriptMod(th.jit.ScriptModule):
    def __init__(self, mod):
        super().__init__()
        x = th.zeros(1, 3)
        mod_fn = lambda : mod(x)
        self.mod = th.jit.trace(mod_fn, tuple())

    @th.jit.script_method
    def forward(self):
        return self.mod()

if __name__ == "__main__":
    with th.no_grad():
        cm = ScriptMod(Mod())
        cm.save("mod.ptj")
        cm = th.jit.load("mod.ptj") # <-- This will fail with the same error as in the original repro.
```

Output:

```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    cm = th.jit.load("mod.ptj") # <---this will fail with the same error as in the original repro above.
  File "/mnt/home/gbschwartz/anaconda/envs/py3_newpytorch_cuda10/lib/python3.7/site-packages/torch/jit/__init__.py", line 151, in load
    torch._C.import_ir_module(module_lookup, f, map_location, _extra_files)
RuntimeError: 
Arguments for call are not valid.
The following operator variants are available:
  
  aten::cat(Tensor[] tensors, int dim=<default>) -> Tensor:
  Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'List[Tensor]'.
  Empty lists default to List[Tensor]. Use torch.jit.annotate(List[my_type], []) to create an empty list of another type.
  
  aten::cat(Tensor[] tensors, int dim=<default>, *, Tensor out) -> Tensor:
  Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'List[Tensor]'.
  Empty lists default to List[Tensor]. Use torch.jit.annotate(List[my_type], []) to create an empty list of another type.

The original call is:
at code/mod.py:3:8
op_version_set = 1
def forward(self) -> Tensor:
  _0 = torch.cat([CONSTANTS.c0, CONSTANTS.c0], 0)
       ~~~~~~~~~ <--- HERE
  return torch.sum(_0, dtype=None)
Compiled from code test.py(9): forward
```
