### ISSUE TITLE
Problem using Pytorch-GPU

### ISSUE THREAD

**Issue by mkhoshle** [pytorch/pytorch#20344]
Hi all,

I am having trouble to run my code using GPU but it works totally fine on CPU. On GPU I get the following error:

```
/var/spool/slurmd/job1126990/slurm_script: line 32: 26153 Killed 
python $SLURM_SUBMIT_DIR/$my_file.py slurmstepd: error: 
Detected 3 oom-kill event(s) in step 1126990.batch cgroup. 
Some of your processes may have been killed by the cgroup out-of-memory handler.
```

In order to avoid the out of memory error I converted my mat file to h5 and I do not load all of my dataset into memory at the same time. My code runs perfectly fine on CPU. But this time I get the following error:

```
Traceback (most recent call last):                                              
  File "/scratch/mkhoshle/dl_final_project/gpu/Training.py", line 8, in <module>
    from torchvision import datasets                                            
  File "/home/mkhoshle/miniconda3/envs/ml-gpu/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models                                              
  File "/home/mkhoshle/miniconda3/envs/ml-gpu/lib/python3.6/site-packages/torchvision/models/__init__.py", line 62, in <module>
    from .alexnet import *                                                      
  File "/home/mkhoshle/miniconda3/envs/ml-gpu/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 1, in <module>
    import torch.nn as nn                                                       
  File "/home/mkhoshle/miniconda3/envs/ml-gpu/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *                                                      
ImportError: libiomp5.so: cannot open shared object file: No such file or directory
```

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS Linux release 7.4.1708 (Core) 
GCC version: (GCC) 8.2.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 396.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda80                    1.0                           0    soumith
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] cuda92                    1.0                           0    pytorch
[conda] libtorch-gpu              0.1.12                  nomkl_0  
[conda] mkl                       2019.3                      199  
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    soumith
[conda] torch-nightly             1.0.0.dev20181206          pypi_0    pypi
[conda] torchfile                 0.1.0                      py_0    conda-forge
[conda] torchvision               0.2.2.post3              pypi_0    pypi

```

And here is how I installed pytorch:

```
# Private conda environment                                                     
source activate ml-gpu
                                                                 
module load cuda/8.0.61                                                         
module load gcc/8.2.0                                                                                                   
module load cudnn/7.0                                                           
module list:
Currently Loaded Modulefiles:
  1) cuda/8.0.61       2) binutils/latest   3) gcc/8.2.0         4) cudnn/7.0

conda install pytorch cuda80 -c soumith
conda install torchvision cuda80 -c soumith
```
Does anyone knows what is the problem with my installation?

**Comment by soumith** [comment]
You dont have mkl installed in your anaconda environment. `conda install mkl` should do.

ImportError: libiomp5.so: cannot open shared object file: No such file or directory comes with that
