### ISSUE TITLE
[jit] can't use script classes as torch.jit.Attribute

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#20399]
```
@torch.jit.script
class BoundingBoxList:
    def __init__(self, bbox, image_size: Tuple[int, int], mode: str):
        self.size = image_size
        self.mode = mode
        self.bbox = bbox

class Foo(torch.jit.ScriptModule):
    def __init__(self, bbox):
        super(Foo, self).__init__(False)
        self.words = torch.jit.Attribute(bbox, BoundingBoxList)

    @torch.jit.script_method
    def forward(self, input):
        # type: (str) -> int
        return self.words.convert("xyxy")

f = Foo(BoundingBoxList(torch.rand(3, 4), (2, 3), "xyxy"))
```
results in:
```
Traceback (most recent call last):
  File "/Users/suo/scratch/test.py", line 64, in <module>
    f = Foo(BoundingBoxList(torch.rand(3, 4), (2, 3), "xyxy"))
  File "/Users/suo/pytorch/torch/jit/__init__.py", line 1178, in init_then_register
    original_init(self, *args, **kwargs)
  File "/Users/suo/scratch/test.py", line 57, in __init__
    self.words = torch.jit.Attribute(bbox, BoundingBoxList)
  File "/Users/suo/pytorch/torch/jit/__init__.py", line 1377, in __setattr__
    the_type = torch.jit.annotations.ann_to_type(value.type)
  File "/Users/suo/pytorch/torch/jit/annotations.py", line 184, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann.__name__))
ValueError: Unknown type annotation: 'BoundingBoxList'
```

**Comment by driazati** [comment]
I've kind of started on this in #19131, though it needs some rebasing to work on the qualified name changes.

**Comment by dzhulgakov** [comment]
Any progress? The serialization code for attributes might be useful for QTensor serialization - not directly, but it'd be nice to serialize QTensor in the same format as CustomClass (cc @ljk53). Also cc @jamesr66a as fixing this probably will make NamedTuples work too

**Comment by driazati** [comment]
This is fixed on master
