### ISSUE TITLE
NameError: name 'List' is not defined in custom_rnns LSTMCell jit fastrnns

### ISSUE THREAD

**Issue by xinliweiyuan** [pytorch/pytorch#20393]
## To Reproduce

seq_len, batch, input_size = 5, 12, 20
hidden_size = 32
inp = torch.randn(seq_len, batch, input_size)
state = LSTMState(torch.randn(batch, hidden_size),
                      torch.randn(batch, hidden_size))

lstm = LSTMLayer(LSTMCell, input_size, hidden_size)
out, out_state = lstm(inp, state)
print(out.shape)

rlstm = ReverseLSTMLayer(LSTMCell, input_size, hidden_size)
rlstm.forward(inp, state)

File "<string>", line 1, in <module>
NameError: name 'List' is not defined

The error happens in ReverseLSTMLayer. I debugged the codes. It happens since the ReverseLSTMLayer is initialized. There shouldn't be such problems cos the ReverseLSTMLayer and LSTMLayer are almost the same. Can you help me to fix it? Thanks. 

Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/PycharmProjects/Hawkes/gnn/custom_lstms.py", line 443, in <module>
    rlstm = ReverseLSTMLayer(LSTMCell, input_size, hidden_size)
  File "/usr/local/lib/python3.6/site-packages/torch/jit/__init__.py", line 952, in init_then_register
    _create_methods_from_stubs(self, methods)
  File "/usr/local/lib/python3.6/site-packages/torch/jit/__init__.py", line 913, in _create_methods_from_stubs
    self._create_methods(defs, rcbs, defaults)
  File "/usr/local/lib/python3.6/site-packages/torch/jit/annotations.py", line 52, in get_signature
    return parse_type_line(type_line)
  File "/usr/local/lib/python3.6/site-packages/torch/jit/annotations.py", line 90, in parse_type_line
    arg_ann = eval(arg_ann_str, _eval_env)
  File "<string>", line 1, in <module>

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.1):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 9.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by xinliweiyuan** [comment]
It is the PyTorch version problem.  I use the update command to update version 1.0, and cos the problem. While when I install 1.1 and uninstall 1.0. The problem solved.
