### ISSUE TITLE
[DataLoader] RuntimeError: unable to resize file </torch_22438_3818345986> to the right size

### ISSUE THREAD

**Issue by DHPO** [pytorch/pytorch#20409]
## 🐛 Bug

When I run program on server by SSH, DataLoader may cause this RuntimeError. 

If this error happens, in the same SSH session it can reproduce again (but file number varys).

But after I reconnecting SSH, everything is OK.

## To Reproduce

Cannot always reproduce.

Traceback:
```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    manager.train_img()
  File "/home/jimmy/graduation/video/manager.py", line 40, in train_img
    self._train_img_epoch()
  File "/home/jimmy/graduation/video/manager.py", line 181, in _train_img_epoch
    for i, (images, labels) in enumerate(loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 207, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/opt/conda/lib/python3.6/site-packages/torch/storage.py", line 120, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: unable to resize file </torch_22438_3818345986> to the right size
```

## Environment

(I use the official docker image)

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] torch                     1.0.1.post2              pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi

## Additional context

Something I think may cause this Error:
1. pytorch flags, I set 
- `torch.backends.cudnn.benchmark = True`
- `torch.multiprocessing.set_sharing_strategy('file_system')`
2. Long running SSH session. The session was running for more than 1 day before the error happens

**Comment by jeffreyksmithjr** [comment]
Closing this issue, because we need more information to effectively triage it. When you provide the requested information, feel free to reopen the issue, to let us know that we can continue with assessing the issue. This open/close/open cycle is how we manage the flow of issues, so your reopening of the issue will constitute the signal that lets us know to take a look at the issue again.

**Comment by lironmo** [comment]
same here.
line 64, in run_prediction
    for i_batch, data in enumerate(data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch-1.1.0-py3.7-linux-x86_64.egg/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.7/site-packages/torch-1.1.0-py3.7-linux-x86_64.egg/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/usr/local/lib/python3.7/site-packages/torch-1.1.0-py3.7-linux-x86_64.egg/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 113, in get

**Comment by ethanweber** [comment]
@DHPO I'm experiencing this problem, but it's not dependent on SSH for me. Did you figure out the issue / solution?

**Comment by llango** [comment]
Same problem 
2020-03-29 20:45:06,647    [ParamS-1] init_process_group creating groups
2020-03-29 20:45:06,648    [ParamS-1] init_process_group done
2020-03-29 20:45:06,658    [ParamC-1] init_process_group creating groups
2020-03-29 20:45:06,658    [ParamC-1] init_process_group done
2020-03-29 20:45:06,679     [PartS-1] init_process_group creating groups
2020-03-29 20:45:06,679     [PartS-1] init_process_group done
2020-03-29 20:45:07,514   [Trainer-1] Initializing global model...
Traceback (most recent call last):
  File "/home/pdl/archiconda3/envs/python36/bin/torchbiggraph_train", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_train')()
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/train.py", line 929, in main
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/train.py", line 904, in train
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/train.py", line 548, in train_and_report_stats
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/train.py", line 510, in load_embeddings
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/train.py", line 183, in init_embs
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/util.py", line 160, in fast_approx_rand
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torchbiggraph-1.0.1.dev0-py3.6.egg/torchbiggraph/util.py", line 127, in allocate_shared_tensor
  File "/home/pdl/archiconda3/envs/python36/lib/python3.6/site-packages/torch/storage.py", line 122, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: unable to resize file </torch_57669_4082009671> to the right size
Who can figure out the solution?

**Comment by cogwheel** [comment]
Same problem here. Seems dumb to have closed this.

**Comment by junjianli106** [comment]
I solved this problem by upgrading pytorch version
