### ISSUE TITLE
Sleef build failure: Usage : ../../bin/mkalias <vector width> <vector FP type> <vector int type> <mangled ISA> <extension>

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#20404]
```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 728, in <module>
    build_deps()
  File "setup.py", line 294, in build_deps
    build_dir='build')
  File "/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/tools/build_pytorch_libs.py", line 293, in build_caffe2
    check_call(ninja_cmd, cwd=build_dir, env=my_env)
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', 'install', '-v']' returned non-zero exit status 1.
*** Error code 1

Stop.
make: stopped in /usr/ports/science/py-pytorch
```

OR the same with GNU make

```
[ 41%] Built target libprotoc
make[2]: Leaving directory '/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build'
make[1]: *** [Makefile:144: all] Error 2
make[1]: Leaving directory '/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 728, in <module>
    build_deps()
  File "setup.py", line 294, in build_deps
    build_dir='build')
  File "/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/tools/build_pytorch_libs.py", line 296, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8', 'install']' returned non-zero exit status 2.
-- Building version 1.1.0a0
```

Log: https://people.freebsd.org/~yuri/py-pytorch-failure.log

1.0rc0-4217-g163f0e182
FreeBSD 11.2

**Comment by jeffreyksmithjr** [comment]
Could you run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py ?

**Comment by yurivict** [comment]
```
$ python3.6 collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: freebsd11
GCC version: Could not collect
CMake version: version 3.14.3

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GT 610
Nvidia driver version: 390.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by ezyang** [comment]
You need to look further up in your logs. Log output when running parallel builds can be confusing because the error doesn't show up in the end. In this particular case your error is:

```
make -f c10/test/CMakeFiles/c10_tempfile_test.dir/build.make c10/test/CMakeFiles/c10_tempfile_test.dir/depend
cd /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build/sleef/src/libm && ../../bin/mkalias > /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build/sleef/src/libm/include/alias_avx512f.h
Scanning dependencies of target fbgemm
make[3]: Leaving directory '/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build'
make[3]: Entering directory '/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build'
cd /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182 /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/c10/test /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build/c10/test /usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build/c10/test/CMakeFiles/c10_tempfile_test.dir/DependInfo.cmake --color=
make -f third_party/fbgemm/CMakeFiles/fbgemm.dir/build.make third_party/fbgemm/CMakeFiles/fbgemm.dir/build
Usage : ../../bin/mkalias <vector width> <vector FP type> <vector int type> <mangled ISA> <extension>
make[3]: *** [sleef/src/libm/CMakeFiles/alias_avx512f.h_generated.dir/build.make:61: sleef/src/libm/include/alias_avx512f.h] Error 255
make[3]: *** Deleting file 'sleef/src/libm/include/alias_avx512f.h'
make[3]: Leaving directory '/usr/ports/science/py-pytorch/work-py36/pytorch-1.0rc0-4217-g163f0e182/build'
make[2]: *** [CMakeFiles/Makefile2:6948: sleef/src/libm/CMakeFiles/alias_avx512f.h_generated.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

It looks like `mkalias` is not what the build for sleef is expecting. If you don't care about sleef, it might be possible to just build without it although I don't see a knob to do so.

**Comment by ezyang** [comment]
This looks like the same problem as #215.

**Comment by ezyang** [comment]
Fixing this bug should simply be a matter of updating sleef to upstream. However, we currently have a fork of sleef.

**Comment by yurivict** [comment]
This was due to wrong patches in the bundles ```sleef```.
