### ISSUE TITLE
RuntimeError: Creating MTGP constants failed

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#20489]
The MTGP constants error came back.

```
May 14 00:04:46 + python main.py --epochs 1 --no-log
May 14 00:04:52 Traceback (most recent call last):
May 14 00:04:52   File "main.py", line 116, in <module>
May 14 00:04:52     train(epoch)
May 14 00:04:52   File "main.py", line 84, in train
May 14 00:04:52     output = model(data)
May 14 00:04:52   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
May 14 00:04:52     result = self.forward(*input, **kwargs)
May 14 00:04:52   File "main.py", line 64, in forward
May 14 00:04:52     x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
May 14 00:04:52   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
May 14 00:04:52     result = self.forward(*input, **kwargs)
May 14 00:04:52   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/dropout.py", line 102, in forward
May 14 00:04:52     return F.dropout2d(input, self.p, self.training, self.inplace)
May 14 00:04:52   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 870, in dropout2d
May 14 00:04:52     else _VF.feature_dropout(input, p, training))
May 14 00:04:52 RuntimeError: Creating MTGP constants failed. at /var/lib/jenkins/workspace/aten/src/THC/THCTensorRandom.cu:33
```

https://circleci.com/gh/pytorch/pytorch/1680491?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by colesbury** [comment]
Is this specific to CUDA 8? (I see pytorch-linux-xenial-cuda8 in the log)

Might be wishful thinking on my part as we dropped CUDA 8 support

**Comment by syed-ahmed** [comment]
Should be "solved" after this lands 😆: https://github.com/pytorch/pytorch/pull/20886

**Comment by syed-ahmed** [comment]
Btw I have only seen this on Maxwells

**Comment by syed-ahmed** [comment]
ah-ha. Maxwell it is.
```
+ nvidia-smi
Mon May 13 23:59:59 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   30C    P0    44W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   37C    P0    41W / 150W |      0MiB /  7618MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by syed-ahmed** [comment]
This is now solved because curandStateMtgp constants are never created as a result of https://github.com/pytorch/pytorch/pull/20886. Closing this issue.
