### ISSUE TITLE
Exception when adding custom scalars in tensorboard

### ISSUE THREAD

**Issue by baldassarreFe** [pytorch/pytorch#20579]
## 🐛 Exception when adding custom scalars in tensorboard

An exception is raised when adding custom scalars using 

`TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorboard.SummaryMetadata.PluginData got list.`

## To Reproduce
Minimal code to reproduce:
```python
from torch.utils.tensorboard import SummaryWriter

with SummaryWriter() as writer:
    writer.add_custom_scalars({'Stuff': {
        'Losses': ['MultiLine', ['loss/(one|two)']],
        'Metrics': ['MultiLine', ['metric/(three|four)']],
    }})
```

Running this results in:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/some/path/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 733, in add_custom_scalars
    self._get_file_writer().add_summary(custom_scalars(layout))
  File "/some/path/python3.7/site-packages/torch/utils/tensorboard/summary.py", line 383, in custom_scalars
    smd = SummaryMetadata(plugin_data=PluginData)
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorboard.SummaryMetadata.PluginData got list.
```

## Environment

Please copy and paste the output from our
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti with Max-Q Design
Nvidia driver version: 418.43
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
```

## Additional context

The exception message is quite clear, the required type is `tensorboard.SummaryMetadata.PluginData` but we have a `list`, this happens [here](https://github.com/pytorch/pytorch/blob/09f22d10a695bfba8ffb3327b9920fd3358c00ee/torch/utils/tensorboard/summary.py#L381):
```python
    PluginData = [SummaryMetadata.PluginData(plugin_name='custom_scalars')]  # <--
    smd = SummaryMetadata(plugin_data=PluginData)
```

Should be enough to remove the surrounding square brackets, PR is coming.

**Comment by lanpa** [comment]
@baldassarreFe The fix is correct, will you make a PR?

**Comment by baldassarreFe** [comment]
@lanpa of course, I submitted the PR shortly after opening the issue and I saw you approved it yesterday. Let's just wait for a merge and we can close the issue ;)
