### ISSUE TITLE
"pip install --find-links" installs package from PyPI instead of pytorch.org

### ISSUE THREAD

**Issue by allegroai** [pytorch/pytorch#20585]
## 🐛 Bug

`pip install --find-links https://download.pytorch.org/whl/CUDA_VERSION/stable torch` installs package from PyPI and not from provided index.

## To Reproduce

```bash
$ pip install --find-links "https://download.pytorch.org/whl/cu80/stable" torch --no-cache
Looking in links: https://download.pytorch.org/whl/cu80/stable
Collecting torch
  Downloading https://files.pythonhosted.org/packages/69/60/f685fb2cfb3088736bafbc9bdbb455327bdc8906b606da9c9a81bae1c81e/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (676.9MB)
     |████████████████████████████████| 676.9MB 4.1MB/s
Collecting numpy (from torch)
  Downloading https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
     |████████████████████████████████| 17.3MB 2.5MB/s
Installing collected packages: numpy, torch
Successfully installed numpy-1.16.3 torch-1.1.0

```
Note the `https://files.pythonhosted.org` URL.
Adding `--verbose` gives more specific information:
```bash
$ pip install --find-links "https://download.pytorch.org/whl/cu80/stable" torch --no-cache --verbose --no-index
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-siy4ij3u
Created temporary directory: /tmp/pip-req-tracker-xaiowyuq
Created requirements tracker '/tmp/pip-req-tracker-xaiowyuq'
Created temporary directory: /tmp/pip-install-gvux7es0
Looking in links: https://download.pytorch.org/whl/cu80/stable
Collecting torch
  1 location(s) to search for versions of torch:
  * https://download.pytorch.org/whl/cu80/stable
  Skipping link https://download.pytorch.org/whl/cu80/stable (from -f); not a file
  Getting page https://download.pytorch.org/whl/cu80/stable
  Starting new HTTPS connection (1): download.pytorch.org:443
  https://download.pytorch.org:443 "GET /whl/cu80/stable HTTP/1.1" 200 6050
  Skipping page https://download.pytorch.org/whl/cu80/stable because the GET request got Content-Type: binary/octet-stream
  ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-xaiowyuq'
ERROR: No matching distribution found for torch
Exception information:
Traceback (most recent call last):
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 282, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/roee/.pyenv/versions/3.6.6/envs/v3.6.6/lib/python3.6/site-packages/pip/_internal/index.py", line 792, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for torch
```
With this line indicating the problem:
```bash
Skipping page https://download.pytorch.org/whl/cu80/stable because the GET request got Content-Type: binary/octet-stream
```

## Expected behavior

pip should be able to download the package matching the URL's cuda version from pytorch.org.

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Linux Mint 19 Tara
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 390.116
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] Could not collect
```

**Comment by soumith** [comment]
this is well-known PyPI behavior. They refuse to fix it.
I filed an issue to fix this on our end by actually changing package names to also add a +cudaversion.

Here's the issue: https://github.com/pytorch/pytorch/issues/19990

See my comment on the issue for further references and link to PyPI issue

**Comment by allegroai** [comment]
@soumith but it can't install the correct wheel even with `--no-index`, see the error regarding the content type

**Comment by soumith** [comment]
hmmm, i wonder if I'm supposed to name it `stable.html` or something so that S3 bucket doesn't serve it as binary content

**Comment by soumith** [comment]
I renamed it to `stable.html`. can you give it a try?

**Comment by allegroai** [comment]
Still doesn't work:
```
$ pip download --no-index -v torch -f https://download.pytorch.org/whl/cu80/stable.html
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-req-tracker-xli3886e
Created requirements tracker '/tmp/pip-req-tracker-xli3886e'
Created temporary directory: /tmp/pip-download-jh0p8czh
Looking in links: https://download.pytorch.org/whl/cu80/stable.html
Collecting torch
  1 location(s) to search for versions of torch:
  * https://download.pytorch.org/whl/cu80/stable.html
  Skipping link https://download.pytorch.org/whl/cu80/stable.html (from -f); unsupported archive format: .html
  Getting page https://download.pytorch.org/whl/cu80/stable.html
  Looking up "https://download.pytorch.org/whl/cu80/stable.html" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): download.pytorch.org:443
^[p  https://download.pytorch.org:443 "GET /whl/cu80/stable.html HTTP/1.1" 200 6050
  Updating cache with response from "https://download.pytorch.org/whl/cu80/stable.html"
  Response header has "no-store"
  Skipping page https://download.pytorch.org/whl/cu80/stable.html because the GET request got Content-Type: binary/octet-stream
  Could not find a version that satisfies the requirement torch (from versions: )
Removed build tracker '/tmp/pip-req-tracker-xli3886e'
No matching distribution found for torch
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/download.py", line 164, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/operations/prepare.py", line 269, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 196, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/index.py", line 688, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for torch
```

**Comment by soumith** [comment]
@allegroai I changed the metadata to text/html and tested that it started working.

**Comment by allegroai** [comment]
@soumith it works, but now the documentation is out of date as it says `/stable` instead of `/stable.html`. This can also be solved by adding a redirection from the former to the latter.

**Comment by soumith** [comment]
@allegroai where is the documentation? I just changed the urls back to `stable`

**Comment by allegroai-git** [comment]
Content type is octet-stream again:

```bash
$ pip download -f https://download.pytorch.org/whl/cu100/stable torch --no-deps -d cuda100 -v --no-index
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-req-tracker-w86uhdgz
Created requirements tracker '/tmp/pip-req-tracker-w86uhdgz'
Created temporary directory: /tmp/pip-download-btgipkmj
Looking in links: https://download.pytorch.org/whl/cu100/stable
Collecting torch
  1 location(s) to search for versions of torch:
  * https://download.pytorch.org/whl/cu100/stable
  Skipping link https://download.pytorch.org/whl/cu100/stable (from -f); not a file
  Getting page https://download.pytorch.org/whl/cu100/stable
  Looking up "https://download.pytorch.org/whl/cu100/stable" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): download.pytorch.org:443
  https://download.pytorch.org:443 "GET /whl/cu100/stable HTTP/1.1" 200 2082
  Updating cache with response from "https://download.pytorch.org/whl/cu100/stable"
  Response header has "no-store"
  Skipping page https://download.pytorch.org/whl/cu100/stable because the GET request got Content-Type: binary/octet-stream
  ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
Removed build tracker '/tmp/pip-req-tracker-w86uhdgz'
ERROR: No matching distribution found for torch
Exception information:
Traceback (most recent call last):
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/commands/download.py", line 164, in run
    resolver.resolve(requirement_set)
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 282, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/roee/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip/_internal/index.py", line 792, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for torch
```
