### ISSUE TITLE
nn.Embedding backwards slow under high row contention

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#20655]
## 🐛 Bug

nn.Embedding backward is very slow when there is high contention for a small number of rows in the embedding matrix. This can be ameliorated with different approaches to backward in this case.

## To Reproduce

```
import torch
import torch.nn as nn
from torch.nn import Parameter

class ParameterEmb(nn.Module):
    def __init__(self, n, dim):
        super().__init__()
        self.emb = Parameter(torch.zeros(n, dim))

    def forward(self, input):
        return self.emb.index_select(0, input)

class OneHotEmb(nn.Module):
    def __init__(self, n, dim):
        super().__init__()
        self.n = n
        self.emb = nn.Linear(n, dim, bias=False)

    def forward(self, input):
        onehot = torch.zeros(input.size(0), self.n, device=input.device)
        onehot.scatter_(1, input.unsqueeze(1), 1)
        return self.emb(onehot)

def forward_backward(M, x):
    return M(x).sum().backward()


N, D = 100, 100
E = nn.Embedding(N, D)
PE = ParameterEmb(N, D)
OHE = OneHotEmb(N, D)
```

Lets first time everything with a uniform distribution over input rows:
```
  x = (torch.arange(10000, dtype=torch.long) % N)

  %timeit forward_backward(E, x)
  %timeit forward_backward(PE, x)
  %timeit forward_backward(OHE, x)

  E.cuda()
  PE.cuda()
  OHE.cuda()
  x = x.cuda()

  %timeit forward_backward(E, x)
  %timeit forward_backward(PE, x)
  %timeit forward_backward(OHE, x)
```
Everything is fine here
```
  CPU Emb     2.87 ms ± 53.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
  CPU Param   12.8 ms ± 496 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
  CPU OneHOt  2.9 ms ± 288 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
  GPU Emb     343 µs ± 660 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
  GPU Param   150 µs ± 238 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
  GPU OneHOt  231 µs ± 983 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
But if I have high contention on a single row, Embedding becomes 20x slower while other approaches do not.

```
  x = torch.zeros(10000, dtype=torch.long)


  CPU Emb     31.5 ms ± 248 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
  CPU Param   12.8 ms ± 66.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
  CPU OneHOt  2.52 ms ± 95.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
  GPU Emb     6.34 ms ± 348 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)
  GPU Param   513 µs ± 198 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
  GPU OneHOt  205 µs ± 500 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

## Environment
```
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
...

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.2
[pip3] torch==1.0.1.post2
[pip3] torchbiggraph==1.dev0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.0                      118
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0
[conda] mkl_random                1.0.1            py37h4414c95_1
[conda] torch                     1.0.1.post2              pypi_0    pypi
[conda] torchvision               0.2.1                    py37_1    pytorch
 ```

**Comment by SsnL** [comment]
probably due to the atomicAdd

**Comment by trancelestial** [comment]
Any new insights into this issue?

**Comment by vmarkovtsev** [comment]
When you do the forward, you don't synchronize with the cuda stream. When you do the backward, there is an implicit stream sync inside Thrust. This stream sync takes much time under heavy load in concurrent streams since the work gets scheduled later.
```
#6  0x00007f1f4f26c118 in cudaStreamSynchronize () from /usr/local/lib/python3.10/dist-packages/torch/lib/libcudart-d0da41ae.so.11.0
#7  0x00007f1f519fe8a8 in thrust::pair<thrust::device_ptr<int>, thrust::device_ptr<int> > thrust::cuda_cub::unique_by_key_copy<thrust::detail::execute_with_allocator<at::cuda::ThrustAllocator&, thrust::cuda_cub::execute_on_stream_base>, thrust::device_ptr<int const>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::device_ptr<int>, thrust::device_ptr<int>, thrust::equal_to<int> >(thrust::cuda_cub::execution_policy<thrust::detail::execute_with_allocator<at::cuda::ThrustAllocator&, thrust::cuda_cub::execute_on_stream_base> >&, thrust::device_ptr<int const>, thrust::device_ptr<int const>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::device_ptr<int>, thrust::device_ptr<int>, thrust::equal_to<int>) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
#8  0x00007f1f519ff92f in long at::native::embedding_backward_cuda_kernel_unique_by_key<int>(at::Tensor const&, at::Tensor&) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
#9  0x00007f1f513f77c3 in at::native::embedding_backward_cuda_kernel(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, long, int, bool, at::Tensor const&, at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
#10 0x00007f1f513e1501 in at::native::embedding_dense_backward_cuda(at::Tensor const&, at::Tensor const&, long, long, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
#11 0x00007f1f52a24e2a in at::(anonymous namespace)::(anonymous namespace)::wrapper_CUDA__embedding_dense_backward(at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
#12 0x00007f1f52a2f510 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CUDA__embedding_dense_backward>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool> >, at::Tensor (at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
#13 0x00007f1fa4ca6fad in at::_ops::embedding_dense_backward::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#14 0x00007f1fa6a41f57 in torch::autograd::VariableType::(anonymous namespace)::embedding_dense_backward(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#15 0x00007f1fa6a42837 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool), &torch::autograd::VariableType::(anonymous namespace)::embedding_dense_backward>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#16 0x00007f1fa4d67969 in at::Tensor c10::callUnboxedKernelFunction<at::Tensor, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt&&, c10::SymInt&&, bool&&) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#17 0x00007f1fa4cfec1b in at::_ops::embedding_dense_backward::call(at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#18 0x00007f1fa4504414 in at::native::embedding_backward_symint(at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#19 0x00007f1fa572c3f2 in at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__embedding_backward(at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#20 0x00007f1fa572c5f6 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeImplicitAutograd__embedding_backward>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool> >, at::Tensor (at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#21 0x00007f1fa4d677f4 in at::Tensor c10::callUnboxedKernelFunction<at::Tensor, at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::SymInt&&, c10::SymInt&&, bool&&, bool&&) () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#22 0x00007f1fa4cfe3c2 in at::_ops::embedding_backward::call(at::Tensor const&, at::Tensor const&, c10::SymInt, c10::SymInt, bool, bool) ()
   from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
#23 0x00007f1fa6920da2 in torch::autograd::generated::EmbeddingBackward0::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) ()
```
