### ISSUE TITLE
[caffe2] convert Onnx DynamicSlice operator to caffe2  failed

### ISSUE THREAD

**Issue by hexiaoting** [pytorch/pytorch#20743]
## 🐛 Bug
When I convert onnx dynamicSlice operator to caffe2, it failed.
```
[libprotobuf FATAL /root/pytorch/third_party/protobuf/src/google/protobuf/repeated_field.h:1506] CHECK failed: (index) < (current_size_):
ONNX FATAL: CHECK failed: (index) < (current_size_):
Traceback (most recent call last):
  File "/root/pytorch-env3-tf1.12/bin/convert-onnx-to-caffe2", line 10, in <module>
    sys.exit(onnx_to_caffe2())
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/caffe2/python/onnx/bin/conversion.py", line 87, in onnx_to_caffe2
    init_net, predict_net = c2.onnx_graph_to_caffe2_net(onnx_model_proto)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 924, in onnx_graph_to_caffe2_net
    return cls._onnx_model_to_caffe2_net(model, device=device, opset_version=opset_version, include_initializers=True)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 917, in _onnx_model_to_caffe2_net
    raise RuntimeError('ONNX conversion failed')
RuntimeError: ONNX conversion failed
```
I found the reason is DynamicSlice's input_size is 3, and we should get the inputs from index 0-2 rather then 3:
caffe2/onnx/backend.cc
```
@@ -1080,7 +1108,7 @@ Caffe2Ops Caffe2Backend::CreateDynamicSlice(
   // arguments to the caffe2 Slice operator.
   std::string axes_tensor;
   if (onnx_node->node.input_size() > 2) {
-    axes_tensor = onnx_node->node.input(3);
+    axes_tensor = onnx_node->node.input(2);
   } else {
     axes_tensor = dummy_->NewDummyName();
     auto* c2_op = ret.ops.Add();
```

## To Reproduce

1.Original model:    tensorflow's [inceptionv4 model](https://github.com/tensorflow/models/tree/master/research/slim)
2.convert to onnx
3.onnx model convert to caffe2:
```
convert-onnx-to-caffe2 ./inception_v4/inception_v4.onnx --output ./inception_v4/onnx_predict_net.pb --init-net-output ./inception_v4/onnx_init_net.pb
```

## Expected behavior

produce onnx_predict_net.pb and onnx_init_net.pb successfully.
So I found that we can fix this issue by modify file:
caffe2/onnx/backend.cc
```
@@ -1080,7 +1108,7 @@ Caffe2Ops Caffe2Backend::CreateDynamicSlice(
   // arguments to the caffe2 Slice operator.
   std::string axes_tensor;
   if (onnx_node->node.input_size() > 2) {
-    axes_tensor = onnx_node->node.input(3);
+    axes_tensor = onnx_node->node.input(2);
   } else {
     axes_tensor = dummy_->NewDummyName();
     auto* c2_op = ret.ops.Add();
```

## Environment

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.1.0a0+8036af3
[pip3] torchvision==0.2.3a0+ccbb322
[conda] Could not collect

**Comment by ezyang** [comment]
Thanks for the report. Would you like to submit a PR with your change? (I am not too familiar with this code so I cannot easily tell at a glance if it is right or not.)

**Comment by hexiaoting** [comment]
@ezyang     I have submited a PR for this issue: [https://github.com/pytorch/pytorch/pull/20846](url)
