### ISSUE TITLE
Question about embed._backend.Embedding.apply

### ISSUE THREAD

**Issue by UCASJingKun** [pytorch/pytorch#20901]
For pytorch 0.3.1, the code is correct.

```python
embed = nn.Embedding(10,100)
embed._backend.Embedding.apply(...)
```

But for 0.4.0, I get an error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/***/anaconda2/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/backends/backend.py", line 10, in __getattr__
    raise NotImplementedError
NotImplementedError
```

**Comment by UCASJingKun** [comment]
What can I do to get the correct code.

**Comment by mrshenli** [comment]
Can you try upgrade to PyTorch v1.0+ and directly call `embed(input)` ([docs](https://pytorch.org/docs/stable/nn.html#embedding))?
