### ISSUE TITLE
conda's anaconda channel packaging is faulty

### ISSUE THREAD

**Issue by mranzinger** [pytorch/pytorch#2091]
I just installed a fresh pytorch using anaconda (Linux, Python 3.6.1, Cuda 8), and am getting the following ImportError on the line `import torch`:
```
Traceback (most recent call last):
  File "trainer.py", line 9, in <module>
    import torch
  File "/home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4thpp10THCSTensorIlEC1EP8THCStateP14THCSLongTensor
```

Python Info:
```
mranzinger@dev-cirra05:~/dev/image_classifier_pytorch$ conda -V
conda 4.3.22
mranzinger@dev-cirra05:~/dev/image_classifier_pytorch$ python -V
Python 3.6.1 :: Anaconda custom (64-bit)
```

Linker Info:
```
mranzinger@dev-cirra05:~/dev/image_classifier_pytorch$ ldd /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffd411eb000)
        libshm.so => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libshm.so (0x00007fb8982f5000)
        libcudart.so.8.0 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libcudart.so.8.0 (0x00007fb89808c000)
        libcudnn.so.6 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libcudnn.so.6 (0x00007fb88eb28000)
        libpython3.6m.so.1.0 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libpython3.6m.so.1.0 (0x00007fb88e621000)
        libTH.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libTH.so.1 (0x00007fb88e06d000)
        libTHS.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libTHS.so.1 (0x00007fb88de39000)
        libTHPP.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libTHPP.so.1 (0x00007fb88db61000)
        libTHNN.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libTHNN.so.1 (0x00007fb88d856000)
        libTHC.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libTHC.so.1 (0x00007fb87e7f6000)
        libTHCS.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libTHCS.so.1 (0x00007fb87e474000)
        libTHCUNN.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libTHCUNN.so.1 (0x00007fb87b771000)
        libnccl.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libnccl.so.1 (0x00007fb878a94000)
        libgcc_s.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../../libgcc_s.so.1 (0x00007fb87887d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb878645000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb87827b000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556dcc43b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb878073000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb877d69000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb877b65000)
        libstdc++.so.6 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6 (0x00007fb8777a8000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb8775a5000)
        libmkl_intel_lp64.so => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../.././libmkl_intel_lp64.so (0x00007fb876b82000)
        libmkl_intel_thread.so => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../.././libmkl_intel_thread.so (0x00007fb87511d000)
        libmkl_core.so => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../.././libmkl_core.so (0x00007fb873625000)
        libiomp5.so => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../.././libiomp5.so (0x00007fb87327a000)
        libgomp.so.1 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/../../.././libgomp.so.1 (0x00007fb873057000)
        libcublas.so.8.0 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libcublas.so.8.0 (0x00007fb8705bb000)
        libcurand.so.8.0 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libcurand.so.8.0 (0x00007fb86c644000)
        libcusparse.so.8.0 => /home/mranzinger/anaconda3/lib/python3.6/site-packages/torch/lib/libcusparse.so.8.0 (0x00007fb869b24000)
```

**Comment by soumith** [comment]
ugh, this is again because of the anaconda folks writing somewhat faulty packaging. I am in touch with them to resolve this next week. Here's what you have to do to fix this:

```
conda uninstall pytorch
conda uninstall libtorch
pip uninstall torch
pip uninstall torch # yes twice
```

And then now freshly install pytorch with the commands from pytorch.org (dont do `conda install pytorch`, do `conda install pytorch cuda80 -c soumith`

**Comment by mranzinger** [comment]
Workaround worked perfectly. Thanks (especially for the fast response)

**Comment by ntomita** [comment]
Worked! Thanks!!

**Comment by rasoolfa** [comment]
This error happens with Docker as well. I added those lines to the dockerfile, but it didn't solve the problem. Anyway posted a question here: https://discuss.pytorch.org/t/docker-problem-with-the-latest-source-and-conda/7292

**Comment by RoyiAvital** [comment]
It seems the latest Anaconda installs PyTorch 0.12.
Any chance telling them to update to the latest release?

**Comment by soumith** [comment]
this is no longer relevant and fixed.

**Comment by mirjunaid26** [comment]
> ugh, this is again because of the anaconda folks writing somewhat faulty packaging. I am in touch with them to resolve this next week. Here's what you have to do to fix this:
> 
> ```
> conda uninstall pytorch
> conda uninstall libtorch
> pip uninstall torch
> pip uninstall torch # yes twice
> ```
> 
> And then now freshly install pytorch with the commands from pytorch.org (dont do `conda install pytorch`, do `conda install pytorch cuda80 -c soumith`

Worked for me. Thanks, Soumith.
