### ISSUE TITLE
test_multinomial broken on rocm

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#20989]
```
15:38:58 test_multinomial (__main__.TestCuda) ... ### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_EXCEPTION (0x1016) at file:mcwamp_hsa.cpp line:1193
15:39:12 Traceback (most recent call last):
15:39:12   File "test/run_test.py", line 441, in <module>
15:39:12     main()
15:39:12   File "test/run_test.py", line 433, in main
15:39:12     raise RuntimeError(message)
15:39:12 RuntimeError: test_cuda failed! Received signal: SIGIOT
15:39:12 =================== sccache compilation log ===================
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/22387/console

**Comment by bddppq** [comment]
Breakage introduced by #20919, reverted in https://github.com/pytorch/pytorch/commit/5ddbfc97e9ce8555a7d515d51a5461edf8675c54
