### ISSUE TITLE
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

### ISSUE THREAD

**Issue by zhuker** [pytorch/pytorch#21154]
## 🐛 Bug

```
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/zhukov/git/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 183, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "/home/zhukov/git/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 114, in forward
    self.fake_B = self.netG_A(self.real_A)  # G_A(A)
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhukov/git/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 373, in forward
    return self.model(input)
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhukov/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
```

## To Reproduce

1. `git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git`
2. `python3 train.py --dataroot datasets/horse2zebra/`

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2070 with Max-Q Design
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.3.0
[conda] Could not collect

## Additional context

Installing nightly build fails loading cudart.9 (while i seem to be installing cu100 version of the nightly)  
```
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
```

**Comment by ezyang** [comment]
Using the stock conda install instructions for the repositroy (I had to downgrade scipy to not use the conda-forge and downloaded the horse2zebra dataset), I successfully ran training for 300 iterations without seeing a failure:

```
(epoch: 1, iters: 100, time: 0.296, data: 0.131) D_A: 0.269 G_A: 0.363 cycle_A: 2.376 idt_A: 1.056 D_B: 0.486 G_B:
0.437 cycle_B: 2.248 idt_B: 1.128
(epoch: 1, iters: 200, time: 0.293, data: 0.001) D_A: 0.255 G_A: 0.250 cycle_A: 3.711 idt_A: 0.677 D_B: 0.331 G_B: 0.377 cycle_B: 1.387 idt_B: 1.837 
(epoch: 1, iters: 300, time: 0.307, data: 0.001) D_A: 0.297 G_A: 0.236 cycle_A: 1.570 idt_A: 2.231 D_B: 0.294 G_B: 0.365 cycle_B: 4.770 idt_B: 0.673 
```

This was on a pair of Quadro GP100s. @zhuker, how long does it take before the error manifests?

Something that would be helpful: could you edit torch/nn/modules/conv.py to print out the inputs to the kernel that fails, and post that here? (Don't need tensor data, just shapes). If you manually call conv with those parameters, does it still fail?

**Comment by ptrblck** [comment]
I tried to reproduce this issue on an TITAN RTX and TITAN V using CUDA10 and the code runs fine.

However, if I install the PyTorch nightly binaries with CUDA10 first, then `torchvision`, PyTorch will be downgraded to `1.1.0` with CUDA9, which triggers this error on Turing GPUs.

To reproduce:
```
# Clean environment
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
Collecting torch_nightly
  Using cached https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.2.0.dev20190604-cp36-cp36m-linux_x86_64.whl
Installing collected packages: torch-nightly
Successfully installed torch-nightly-1.2.0.dev20190604

>>> import torch
>>> torch.__version__
'1.2.0.dev20190604'
>>> torch.version.cuda
'10.0.130'

pip install torchvision
...
Installing collected packages: torch, torchvision
Successfully installed torch-1.1.0 torchvision-0.3.0

>>> import torch
>>> torch.__version__
'1.1.0'
>>> torch.version.cuda
'9.0.176'

=======================================================================
# Clean environment
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
...
pip install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
Successfully installed torch-1.1.0 torchvision-0.3.0

>>> torch.__version__
'1.1.0'
>>> torch.version.cuda
'9.0.176'

=======================================================================
# Clean environment
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
...
pip install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl --no-deps

>>> torch.__version__
'1.2.0.dev20190604'
>>> torch.version.cuda
'10.0.130'
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/opt/conda/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/opt/conda/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /opt/conda/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv
```
@ezyang What would be the recommended way to install `torchvision` for PyTorch nightly build with CUDA10?
The pip install command for the stable version work fine.

@zhuker Could you check the currently used CUDA version using:
```python
import torch
print(torch.__version__)
print(torch.version.cuda)
```

**Comment by ptrblck** [comment]
@zhuker 
Additionally to the version printing, could you post the install command you were using and the complete output of these commands (tip from @mcarilli):
```
$ LD_DEBUG=libs python
>>> import torch
```

**Comment by ezyang** [comment]
@ptrblck Build from source, I think.

**Comment by nitinsatpute** [comment]
pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl 
Install pytorch  from above link. It will solve this issue.

**Comment by lesreaper** [comment]
Didn't work for me. RTX2080, Cuda 10, Pytorch 1.3. :(

**Comment by kritiagg** [comment]
Any updates on this issue?

**Comment by tengerye** [comment]
Hi, any update?

**Comment by ezyang** [comment]
If you are seeing this issue, please file a new issue with the steps to take to cause this error. The error here is very generic and we need to know more about the repro to help you debug here.

**Comment by DavidChou2017** [comment]
hi, I met the same problem, and my solution is to create a new conda env.My command is 'conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0' . Btw, my GPU is Quadro RTX 5000.

**Comment by JupiLogy** [comment]
Wanted to add that I've had this issue myself a couple of times now and it has always been fixed by a restart of my PC. Just in case anyone is also finding this same issue years later.
