### ISSUE TITLE
RuntimeError: error executing torch_shm_manager

### ISSUE THREAD

**Issue by dthboyd** [pytorch/pytorch#2125]
```python
#Let us show some of the training images, for fun.

import matplotlib.pyplot as plt
import numpy as np

# functions to show an image


def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))


# get some random training images
dataiter = iter(trainloader)
images, labels = dataiter.next()

# show images
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join('%5s' % classes[labels[j]] for j in range(4)))




```
```

RuntimeError                              Traceback (most recent call last)
<ipython-input-73-cfff7ccbdfa2> in <module>()
     15 # get some random training images
     16 dataiter = iter(trainloader)
---> 17 images, labels = dataiter.next()
     18 
     19 # show images

//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py in __next__(self)
    210                 self.reorder_dict[idx] = batch
    211                 continue
--> 212             return self._process_next_batch(batch)
    213 
    214     next = __next__  # Python 2 compatibility

//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    237         self._put_indices()
    238         if isinstance(batch, ExceptionWrapper):
--> 239             raise batch.exc_type(batch.exc_msg)
    240         return batch
    241 

RuntimeError: Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 90, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "//anaconda/lib/python3.5/site-packages/torch/storage.py", line 111, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "//anaconda/lib/python3.5/site-packages/torch/lib/torch_shm_manager" at /Users/soumith/miniconda2/conda-bld/pytorch_1493757035034/work/torch/lib/libshm/core.cpp:125

```
​

cc @ezyang @gchanan @zou3519

**Comment by bryant-pham** [comment]
Any solutions to this?

**Comment by eustomaqua** [comment]
Same situation and cannot resolve it....

**Comment by eustomaqua** [comment]
I changed the torch version and it worked.   
Firstly, I used "pip install torch==1.3.0" with "torchvision==0.4.0" and this issue happend.   
Then, I degraded the version "pip install torch==1.2.0" with "torchvision==0.4.0" and it worked.

**Comment by soumith** [comment]
@eustomaqua i've identified the reason for this issue for the 1.3.0 release. The affected build is OSX + pip, no other builds are affected. I am looking into fixing this asap.
Reference issue which introduced the problem: https://github.com/pytorch/pytorch/issues/18996

**Comment by soumith** [comment]
`pip install torch` will fix this now. Sorry for the delay, root-causing it and issuing new binaries took time.

**Comment by himanshivitcc** [comment]
I am facing the same issue:

Traceback (most recent call last):                                                                                                          
  File "pytorch_fastai.py", line 221, in <module>
    ds_train = PyTorchDataset('data/testing_folder_1/training/', batch_size = 8)
  File "/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py", line 99, in fit
    for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
  File "/anaconda3/lib/python3.7/site-packages/fastprogress/fastprogress.py", line 72, in __iter__
    for i,o in enumerate(self._gen):
  File "/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py", line 75, in __iter__
    for b in self.dl: yield self.proc_batch(b)
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py", line 127, in data_collate
    return torch.utils.data.dataloader.default_collate(to_data(batch))
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/anaconda3/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99


The pytorch version is : (1.3.0)

**Comment by soumith** [comment]
@himanshivitcc `pip install -U torch` will fix it

**Comment by sgdread** [comment]
I am still facing this issue when `torch.multiprocessing.set_sharing_strategy('file_system')`
