### ISSUE TITLE
test_array_adaptor and test_from_cuda_array_interface_active_device fails with numba version 0.44.0

### ISSUE THREAD

**Issue by syed-ahmed** [pytorch/pytorch#21269]
## 🐛 Bug
test_array_adaptor and test_from_cuda_array_interface_active_device fails with numba version 0.44.0

## To Reproduce

 - Run test_numba_integration with numba 0.44.0
```
Running test_numba_integration ... [2019-06-01 01:10:22.416268]
test_active_device (__main__.TestNumbaIntegration)
'as_cuda_array' tensor device must match active numba context. ... ok
test_array_adaptor (__main__.TestNumbaIntegration)
Torch __cuda_array_adaptor__ exposes tensor data to numba.cuda. ... FAIL
test_conversion_errors (__main__.TestNumbaIntegration)
Numba properly detects array interface for tensor.Tensor variants. ... ok
test_cuda_array_interface (__main__.TestNumbaIntegration)
torch.Tensor exposes __cuda_array_interface__ for cuda tensors. ... ok
test_from_cuda_array_interface (__main__.TestNumbaIntegration)
torch.as_tensor() and torch.tensor() supports the __cuda_array_interface__ protocol. ... ok
test_from_cuda_array_interface_active_device (__main__.TestNumbaIntegration)
torch.as_tensor() tensor device must match active numba context. ... FAIL
test_from_cuda_array_interface_lifetime (__main__.TestNumbaIntegration)
torch.as_tensor(obj) tensor grabs a reference to obj so that the lifetime of obj exceeds the tensor ... ok

======================================================================
FAIL: test_array_adaptor (__main__.TestNumbaIntegration)
Torch __cuda_array_adaptor__ exposes tensor data to numba.cuda.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numba_integration.py", line 123, in test_array_adaptor
    torch.arange(10).to(dt).numpy()
AssertionError: TypeError not raised

======================================================================
FAIL: test_from_cuda_array_interface_active_device (__main__.TestNumbaIntegration)
torch.as_tensor() tensor device must match active numba context.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numba_integration.py", line 345, in test_from_cuda_array_interface_active_device
    torch.as_tensor(numba_ary, device=torch.device("cuda", 1))
AssertionError: RuntimeError not raised

----------------------------------------------------------------------
Ran 7 tests in 2.401s

FAILED (failures=2)
Traceback (most recent call last):
  File "run_test_new.py", line 434, in <module>
    main()
  File "run_test_new.py", line 426, in main
    raise RuntimeError(message)
RuntimeError: test_numba_integration failed!
```
## Expected behavior

Tests in question pass

## Environment
```
Collecting environment information...
PyTorch version: 1.2.0a0+0885dd2
Is debug build: No
CUDA used to build PyTorch: 10.1.168

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.16.4
[pip] torch==1.2.0a0+0885dd2
[pip] torchtext==0.4.0
[pip] torchvision==0.2.1
[conda] magma-cuda100             2.1.0                         5    local
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] torch                     1.2.0a0+0885dd2          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi
```

## Additional context
Test passes with numba version 0.43.1. Also looks like 0.44.0 was added in conda couple days ago?: https://anaconda.org/numba/numba.

**Comment by ezyang** [comment]
@madsbk do you think you could take a look?

Not sure if this is an upstream problem or not; would have to read the release notes for 0.44.0.

**Comment by madsbk** [comment]
Sure, I can take a look
