### ISSUE TITLE
cuda runtime

### ISSUE THREAD

**Issue by encichou** [pytorch/pytorch#21276]
hallo every one ,recently  i have a  bug ,when i  train a resnet18 ,after 9000 iterator times ,some problem occured.could you help me ?

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=271 error=4 : unspecified launch failure       x
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=271 error=4 : unspecified launch failure       x
Traceback (most recent call last):                                                                                          x
  File "model_run.py", line 464, in <module>                                                                                x
    train(train_loader, model, criterion, optimizer, scheduler, epoch,log_file)                                             x
  File "model_run.py", line 163, in train                                                                                   x
    loss.backward()                                                                                                         x
  File "/data/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward                    x
    torch.autograd.backward(self, gradient, retain_graph, create_graph)                                                     x
  File "/data/home/encizhou/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward         x
    allow_unreachable=True)  # allow_unreachable flag                                                                       x
  File "/data/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 76, in apply            x
    return self._forward_cls.backward(self, *args)                                                                          x
  File "/data/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 30, in backward    x
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)                              x
  File "/data/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 41, in forward     x
    return comm.reduce_add_coalesced(grads, destination)                                                                    x
  File "/data/anaconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 119, in reduce_add_coalesced    x
    flat_tensors = [_flatten_dense_tensors(chunk) for chunk in chunks]                                                      x
  File "/data/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 144, in _flatten_dense_tensors     x
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)                                                     x
RuntimeError: cuda runtime error (4) : unspecified launch failure at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:271  x

**Comment by vishwakftw** [comment]
Closing this and keeping #21270 .
