### ISSUE TITLE
Unreasonable BN2d failure on nividia GPU

### ISSUE THREAD

**Issue by 2prime** [pytorch/pytorch#2140]
#BN2d may fail on nividia GPU.
I think there is something wrong when pytorch BN layer meets with CUDNN.
Error Traceback:
`
  File "/home/yplu/resnet/cifar/Resnet.py", line 123, in forward
    out = out + self.basic_block[i](out)
  File "/opt/software/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yplu/resnet/cifar/Resnet.py", line 77, in forward
    out = self.bn1(x)
  File "/opt/software/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/software/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 43, in forward
    self.training, self.momentum, self.eps)
  File "/opt/software/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/functional.py", line 463, in batch_norm
    return f(input, weight, bias)
RuntimeError: std::bad_cast
`
Code can be found from:
https://github.com/2prime/DeepLab/blob/master/ResNet/models/Resnet.py

**Comment by 2prime** [comment]
This code runs well on cpu.

**Comment by 2prime** [comment]
RuntimeError: std::bad_cast

**Comment by soumith** [comment]
@2prime could you tell me why you've closed it, is it somehow fixed? I haven't gotten around to investigating your script yet.

**Comment by matteorr** [comment]
I get the same error with the following simple network (I omitted parts that are not necessary):

    class Dense(nn.Module):
        def __init__(self):
            super(Dense, self).__init__()
            self.num_filters = 16
            self.kernel_size = 3

            self.conv1 = nn.Conv2d(3, self.num_filters, self.kernel_size, stride=2, padding=1)
            self.conv2 = nn.Conv2d(self.num_filters, 2*self.num_filters, self.kernel_size, stride=2, padding=1)
            # rest of layers

        def forward(self, i_data):
            h_data       = self.conv1(i_data)
            h_data_bn = nn.BatchNorm2d(self.num_filters)
            h_data       = self.conv2(h_data_bn(h_data))

            # rest of forward pass

Code works fine on cpu, but I get this runtime error when running on gpu by using `.cuda()`:

Traceback (most recent call last):
  File "pred_2d_hm.py", line 90, in <module>
    pred_htmps    = model(train_batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.../pytorch/models/PoseNet_heatmaps.py", line 35, in forward
    h_data    = self.conv2(h_data_bn(h_data))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/batchnorm.py", line 43, in forward
    self.training, self.momentum, self.eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 463, in batch_norm
    return f(input, weight, bias)
RuntimeError: std::bad_cast

- Driver Version: 375.66
- Gpu: GeForce GTX TITAN X

**Comment by youngfly11** [comment]
I have met the same question as you. Could you tell me how you fix it? Thanks in advance for help

**Comment by Jie-Xie** [comment]
Same here. I tried to use resnet50 to extract features. The code works on cpu but not gpu due to the same error.

**Comment by EgorDezhic** [comment]
Same here but with custom network:
```
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/batchnorm.py in forward(self, input)
     35         return F.batch_norm(
     36             input, self.running_mean, self.running_var, self.weight, self.bias,
---> 37             self.training, self.momentum, self.eps)
     38 
     39     def __repr__(self):

/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
    637                training=False, momentum=0.1, eps=1e-5):
    638     f = torch._C._functions.BatchNorm(running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled)
--> 639     return f(input, weight, bias)
    640 
    641 

RuntimeError: std::bad_cast
```
