### ISSUE TITLE
RuntimeError: cublas runtime error 

### ISSUE THREAD

**Issue by G-YY** [pytorch/pytorch#21459]
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411
My GPU is 2080ti,CUDA 10.0
How can I slove the problem?Thank you.

**Comment by fmassa** [comment]
Without further information, it's hard to say what the problem is. Here are some related issues https://github.com/pytorch/pytorch/issues/7548 https://github.com/pytorch/pytorch/issues/17334

Please copy and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py in here, as it can provide useful information to help us debug further.

**Comment by G-YY** [comment]
Thank you for your reply. @fmassa 
The env output is :
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==0.4.1
[pip3] torch-sparse==0.4.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py36he904b0f_5  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.0.1           cuda100py36he554f03_0  
[conda] torchvision               0.2.1                    py36_0


When I run my own script, the error is:
Traceback (most recent call last):
  File "tools/demo.py", line 188, in <module>
    demo()
  File "tools/demo.py", line 174, in demo
    corner_pred = eval_net(seg_pred, vertex_pred).cpu().detach().numpy()[0]
  File "/home/lab/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lab/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lab/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "tools/demo.py", line 54, in forward
    return ransac_voting_layer_v3(mask, vertex_pred, 512, inlier_thresh=0.99)
  File "/home/lab/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 592, in ransac_voting_layer_v3
    ATA=torch.matmul(normal.permute(0,2,1),normal)              # [vn,2,2]
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411

**Comment by ptrblck** [comment]
Seems to be a double post of #21587
