### ISSUE TITLE
[Tensorboard] Error loading embeddings in projector tab

### ISSUE THREAD

**Issue by tarrencev** [pytorch/pytorch#21465]
## 🐛 Bug

When running the `add_embedding` example provided in the documentation [here](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_embedding), I am unable to visualize the output in Tensorboard. When loading the projector page, the Tensorboard backend returns a 500 and the CLI throws an error (details below).

## To Reproduce

1. Generate embedding logs:

```
import torch
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter()
writer.add_embedding(torch.randn(100, 5))
writer.close()
```

2. Run Tensorboard and navigate to Projector tab (`--logdir=runs/`)

Backend returns the following response:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

The CLI throws the following error:

```
I0606 03:16:56.516376 140481921013504 _internal.py:97] ::ffff:172.17.13.114 - - [06/Jun/2019 03:16:56] "GET /data/plugin/projector/runs HTTP/1.1" 500 -
E0606 03:16:56.518899 140481921013504 _internal.py:97] Error on request:
Traceback (most recent call last):
  File "/home/tvanas/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "/home/tvanas/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/backend/application.py", line 346, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/home/tvanas/.local/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 235, in application
    resp = f(*args[:-2] + (request,))
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 471, in _serve_runs
    return Respond(request, list(self.configs.keys()), 'application/json')
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 323, in configs
    run_path_pairs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 403, in _read_latest_config_files
    ckpt_path = _find_latest_checkpoint(logdir)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 663, in _find_latest_checkpoint
    ckpt_path = tf.train.latest_checkpoint(os.path.join(dir_path, os.pardir))
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 336, in latest_checkpoint
    ckpt = get_checkpoint_state(checkpoint_dir, latest_filename)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 278, in get_checkpoint_state
    + checkpoint_dir)
ValueError: Invalid checkpoint state loaded from runs/..
```

Output logs:
events.out.tfevents.1559829982.0c15a53a365c.48733.0:
```
�K"	�țwG>�A
brain.Event:2/z�L
```

projector_config.pbtxt:
```
embeddings {
tensor_name: "default:00000"
tensor_path: "00000/default/tensors.tsv"
}
```

00000/default/tensors.tsv:
```
1.1024774312973022	0.14599047601222992	1.1333125829696655	-1.376415729522705	0.35197189450263977
0.12852966785430908	1.2924888134002686	2.3258771896362305	0.4094551205635071	-0.9674509167671204
-0.49151989817619324	0.7864876389503479	-0.145977184176445	-1.7831733226776123	0.6253240704536438
-0.9050264954566956	-0.15727081894874573	-1.5126099586486816	0.7933973670005798	-0.24805942177772522
-0.33359313011169434	0.06617540121078491	1.3840014934539795	-0.28165799379348755	0.002967419335618615
0.37702563405036926	1.3015050888061523	-0.2239067703485489	-0.9767733812332153	0.09394600987434387
-0.2536439001560211	0.6541917324066162	0.023369016125798225	-2.9497451782226562	-2.597632884979248
-1.475779414176941	0.20004883408546448	0.2913793921470642	-0.4929293096065521	0.20747123658657074
0.20261403918266296	0.800439178943634	1.0355433225631714	-0.19807030260562897	-1.3482170104980469
-0.5293643474578857	-2.550053119659424	1.5628432035446167	-0.0914018526673317	-0.33678126335144043
-1.253365159034729	0.10837583243846893	-1.218179702758789	1.7630726099014282	-1.5023692846298218
-0.4066146910190582	-0.9060298204421997	0.2876826822757721	-1.6201688051223755	-0.5986799001693726
-0.7315393686294556	0.5124865174293518	-1.2524452209472656	-0.021020300686359406	-0.7413328289985657
-0.4056398868560791	-0.19408762454986572	2.4326171875	1.6527291536331177	-1.4163233041763306
-2.307793378829956	-0.5375447273254395	-0.0314587764441967	0.03820500150322914	0.4690467119216919
1.0092682838439941	-0.22887824475765228	-0.2576455771923065	-1.0738937854766846	0.4300503432750702
-1.2844961881637573	-0.6324789524078369	0.18141502141952515	1.2007249593734741	-1.2435591220855713
-0.2944560647010803	-0.30900838971138	0.6547672748565674	0.46721088886260986	1.4614747762680054
0.3325675427913666	0.6142091155052185	-1.3689864873886108	-0.9946284890174866	-2.209622621536255
-0.8007447123527527	-0.735998809337616	0.16859301924705505	-0.5199798941612244	0.18564936518669128
-0.3856185972690582	-0.7982561588287354	0.17262598872184753	-0.3299645185470581	-0.7601485848426819
-0.4616570472717285	0.2751213014125824	0.7351075410842896	-0.7951990365982056	0.8445156812667847
-0.6992228031158447	0.7021928429603577	-1.079166054725647	-0.24383220076560974	-0.24464915692806244
-1.467533826828003	0.36852556467056274	1.122012972831726	0.5593079924583435	0.3000822961330414
0.6863416433334351	-0.8246442079544067	-0.8151698708534241	-1.5286537408828735	0.061087608337402344
1.2853147983551025	-0.46565085649490356	0.37368887662887573	1.074584722518921	-0.3877679109573364
0.10177365690469742	-0.4836900532245636	-0.8052391409873962	-1.8213623762130737	0.6586936712265015
-1.5349080562591553	0.01620706543326378	-1.205259919166565	-1.6959357261657715	-0.5249924063682556
1.7537239789962769	0.6530112028121948	0.6690295934677124	-0.8556013703346252	-0.3070293664932251
-0.9597391486167908	-0.5900903344154358	-1.2884207963943481	0.2505265176296234	-0.39310261607170105
-1.850782871246338	2.3328616619110107	0.6401166915893555	0.48730745911598206	-1.3238080739974976
0.3089190125465393	-0.2329721599817276	0.16585411131381989	-1.2650409936904907	-1.2074447870254517
0.5841067433357239	0.11635265499353409	-1.3992568254470825	0.3621869385242462	-0.9449983239173889
0.9608760476112366	-1.0604702234268188	-0.8606833219528198	1.0577419996261597	-0.6060283780097961
0.5682142376899719	1.2655072212219238	-0.8504678606987	-0.1493319571018219	-0.830419659614563
0.8147766590118408	-0.3173757791519165	1.0259201526641846	1.2312363386154175	1.0419567823410034
1.8649570941925049	0.8309797644615173	0.5996279120445251	-2.175163745880127	0.9246580600738525
-1.060111403465271	0.40117794275283813	-0.34563034772872925	1.0657483339309692	-0.6743314862251282
0.017109524458646774	1.170486330986023	-1.5011227130889893	0.25915244221687317	-0.38845938444137573
-0.2570567727088928	1.1473890542984009	-0.9311988949775696	1.1142531633377075	-1.3111717700958252
0.45996028184890747	1.7493394613265991	-1.9917476177215576	-0.42194655537605286	1.9982755184173584
-0.6000335812568665	0.2632238566875458	-0.9896512031555176	-0.6120739579200745	-0.9436551332473755
-0.5277581214904785	1.0921536684036255	0.42062005400657654	0.1720479428768158	-0.7127238512039185
1.0757927894592285	0.26300662755966187	0.5312227010726929	0.01646791584789753	-0.31319892406463623
0.2755647301673889	1.0412534475326538	-0.7867096066474915	0.2838738262653351	-1.0577797889709473
0.7587474584579468	-0.7949668169021606	-0.7410289645195007	-2.5534207820892334	-1.7323728799819946
3.3784587383270264	0.9245747923851013	-0.3854602873325348	-1.0697754621505737	1.7407174110412598
1.4308415651321411	-0.4672268331050873	-1.282057285308838	-0.9410136342048645	-0.7238077521324158
-2.173610210418701	1.4623254537582397	-2.5283265113830566	0.7635862231254578	1.3541758060455322
-0.830468475818634	0.8533920645713806	-1.5049118995666504	-1.27347731590271	-1.0963594913482666
-1.5214817523956299	0.5539343953132629	-0.8001036643981934	1.097811222076416	0.5467257499694824
-0.6949898600578308	-1.68156898021698	0.12709248065948486	-0.24685709178447723	-0.5264536738395691
0.5078966021537781	-0.486409068107605	0.2971917688846588	-0.9172251224517822	-0.11814987659454346
0.7483962178230286	-0.0497337244451046	-1.6402896642684937	-0.8242110013961792	-0.46947890520095825
0.39619168639183044	0.346567302942276	0.11632537096738815	1.6068814992904663	0.7658601999282837
0.19981293380260468	0.09091039001941681	0.6994942426681519	-0.30127251148223877	0.40874776244163513
0.6055932641029358	0.34254491329193115	1.2238452434539795	-0.10261289775371552	-0.5774653553962708
0.9891043901443481	-0.6567659974098206	-0.18836866319179535	0.7242745161056519	0.8085931539535522
1.1978973150253296	-1.4435288906097412	0.0854998379945755	1.3149425983428955	-0.6209897398948669
-0.5464993715286255	1.4642140865325928	0.4791718125343323	1.647328495979309	0.04675370454788208
1.1532251834869385	0.8451058864593506	0.5837728977203369	-0.4368080794811249	-0.17867577075958252
-0.6365047693252563	-0.5856267809867859	-0.28607773780822754	0.30488988757133484	2.29468035697937
1.4491363763809204	-0.8051658272743225	3.1703858375549316	1.9875961542129517	1.120442271232605
-1.2641617059707642	-1.1533465385437012	0.9746653437614441	-0.4474150240421295	1.4189103841781616
1.1238511800765991	1.3888249397277832	-1.3599199056625366	-1.1618751287460327	-0.6181862950325012
0.26005205512046814	-0.8726951479911804	0.7290729880332947	0.41287264227867126	1.6121326684951782
0.11263944953680038	0.36680513620376587	0.18039339780807495	0.8207205533981323	-0.672461748123169
-0.8022741079330444	0.11544150114059448	1.3186359405517578	0.537299633026123	-0.35646572709083557
0.5973818302154541	2.002401828765869	1.1187645196914673	0.3868894577026367	-1.0765811204910278
-0.5078219175338745	1.5523875951766968	0.9511246681213379	-0.9036806225776672	-0.4681116044521332
-0.8716646432876587	-0.496526300907135	0.5961962342262268	-0.7305524349212646	0.6526141166687012
0.36871016025543213	0.49780595302581787	-1.454744815826416	0.005436202511191368	-2.1937639713287354
0.4115055203437805	-1.996134877204895	-1.6407526731491089	0.14552046358585358	0.9351681470870972
-0.7492231130599976	0.5456019043922424	0.809817373752594	-0.6622924208641052	-0.8982560634613037
-0.09915147721767426	1.2106568813323975	-0.5666565895080566	-1.1994550228118896	1.7008827924728394
0.49392566084861755	0.1272023320198059	0.03866333141922951	0.28443121910095215	-0.7391626238822937
-1.6813246011734009	-2.440345048904419	1.1118440628051758	-1.2113646268844604	0.08937675505876541
-1.331673264503479	1.3542358875274658	-0.7063481211662292	-0.6827130913734436	0.24033065140247345
-1.5992083549499512	0.7393998503684998	-0.20265980064868927	-0.3151055574417114	0.980027973651886
0.32311686873435974	0.44812923669815063	0.19418968260288239	-2.005126953125	-0.21253710985183716
0.4188549816608429	-0.3444151282310486	-0.42816317081451416	0.07180894911289215	-0.5537504553794861
-1.5524441003799438	0.21125848591327667	1.5878243446350098	-0.4030749499797821	1.1161420345306396
-0.45579734444618225	-0.17540036141872406	0.8024147152900696	3.141489267349243	-1.4189679622650146
0.9400922060012817	-0.41919639706611633	-0.20009613037109375	0.6375116109848022	1.1364367008209229
-0.1809728890657425	1.7583476305007935	-0.35453739762306213	0.15331149101257324	1.475936770439148
-0.4617542028427124	0.5480459928512573	-0.6995880007743835	0.8096210956573486	-1.0917781591415405
0.20301620662212372	-0.3575208783149719	-2.255765199661255	0.4099944829940796	-0.32386094331741333
0.38580211997032166	0.6996671557426453	0.7079312205314636	0.6551006436347961	0.4395924210548401
0.8536319136619568	-1.7203963994979858	0.2051527351140976	-0.899313747882843	-0.11970006674528122
0.7152648568153381	-2.617185592651367	-0.6477780342102051	0.4085513651371002	-1.186480164527893
2.872231960296631	0.9818222522735596	0.22407695651054382	0.7756584286689758	-0.14084604382514954
-0.982560932636261	0.4606628119945526	0.3062102198600769	-0.47062885761260986	-1.1903021335601807
-0.09427227824926376	1.6383486986160278	1.2610610723495483	-0.05345598980784416	0.725378155708313
-0.45712485909461975	0.09468057751655579	0.4187769889831543	-0.11716299504041672	1.7702831029891968
-0.6357839107513428	1.028377652168274	0.23710091412067413	-0.8497236371040344	1.4288817644119263
-0.11958920955657959	-0.5059032440185547	-1.0971224308013916	0.22069263458251953	-0.1983407735824585
0.6818786263465881	-0.9153156876564026	-0.23125751316547394	-0.8941200971603394	0.3960205316543579
-0.5972825884819031	-1.1509487628936768	-0.3122699558734894	-1.399918556213379	1.372998833656311
-1.9598768949508667	-0.7605870366096497	0.48413461446762085	-1.13645601272583	-0.899420976638794
1.1898386478424072	0.3587009310722351	-0.7551220655441284	-1.2542623281478882	-1.571890115737915
```

## Expected behavior

SummaryWriter should correctly output logs, Tensorboard should properly read them.
 
## Environment

PyTorch version: 1.2.0.dev20190606
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 384.111
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch-nightly==1.2.0.dev20190606
[pip] torchfile==0.1.0
[pip] torchvision==0.2.2.post3
[pip] tb-nightly@1.14.0a20190605

**Comment by fmassa** [comment]
Related to https://github.com/pytorch/pytorch/issues/21448

@tarrencev can you try running the snippet in https://github.com/pytorch/pytorch/issues/21448#issuecomment-499478293 and see if it works for you? Maybe we need to specify `metadata=meta, label_img` etc in `add_embedding`?

**Comment by tarrencev** [comment]
@fmassa I tried running that and received the same error. Looks like it is being thrown here: https://github.com/tensorflow/tensorflow/blob/a4c3fa196506d26a1604d3518c58761221e99217/tensorflow/python/training/checkpoint_management.py#L277

So it seems it is looking for a `checkpoint` file... my output does not contain one, so `model_checkpoint_path` is not set. Do you have a `checkpoint` file in your summary logs folder?

**Comment by tarrencev** [comment]
Hmm this doesn't make sense but I was able to resolve the issue by moving my logs to a different folder. Everything else is the same...

**Comment by fmassa** [comment]
@tarrencev maybe there is a problematic checkpoint in the original folder which was messing up with TensorBoard?

**Comment by tarrencev** [comment]
The contents of the folders are the same. Let me try debug a bit and will post my findings if any.

**Comment by tarrencev** [comment]
@fmassa is seems the issue is as follows:

I have my SummaryWriter outputting to `results/scannet_poster/logs/`. There exists a folder in the parent directory with name `checkpoint/`, i.e. `results/checkpoint/`. For some reason, Tensorflow/Tensorboard is trying to resolve this as a TF checkpoint. If I rename the `checkpoint/` directory, everything works. Not sure why it is traversing the folder hierarchy like so.

**Comment by fmassa** [comment]
Thanks for the information!
