### ISSUE TITLE
Pytorch Multi-processing could not initialize CUDA object after initialize Network with Caffe

### ISSUE THREAD

**Issue by ywu36** [pytorch/pytorch#2153]
Hi,
I met a strange error that after I initialize a Caffe network using: 

`net = caffe.Net(CaffeModel, weights, caffe.TEST)`

Then, whenever I try to create a CUDA model in a subprocess using Pytorch: 

```
def traina(model):
    model2 = PytorchNetworkStructure().cuda()

processes = []
for model_idx in range(3):
    p = mp.Process(target=train, args=(PytorchModel,))
    p.start()
    processes.append(p)
for p in processes:
    p.join()
```

The program will report the error:

```

> Traceback (most recent call last):
>   File "/home/yuhang/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/home/yuhang/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "....py", line 43, in traina
>     model2 = Policy().cuda()
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 148, in cuda
>     return self._apply(lambda t: t.cuda(device_id))
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 119, in _apply
>     module._apply(fn)
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 125, in _apply
>     param.data = fn(param.data)
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 148, in <lambda>
>     return self._apply(lambda t: t.cuda(device_id))
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 66, in _cuda
>     return new_type(self.size()).copy_(self, async)
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 266, in _lazy_new
>     _lazy_init()
>   File "/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 85, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: cuda runtime error (3) : initialization error at /home/yuhang/dependencies/pytorch-master/torch/lib/THC/THCGeneral.c:74
> THCudaCheck FAIL file=/home/yuhang/dependencies/pytorch-master/torch/lib/THC/THCGeneral.c line=74 error=3 : initialization error
> Process Process-3:

```

Python version: 2.7.13

Someone could help ?

**Comment by soumith** [comment]
this is expected. read: http://pytorch.org/docs/master/notes/multiprocessing.html#sharing-cuda-tensors and https://discuss.pytorch.org/t/a-call-to-torch-cuda-is-available-makes-an-unrelated-multi-processing-computation-crash/4075/2?u=smth

**Comment by ywu36** [comment]
@soumith 
However, the error only happens after Caffe initialization. In a usual case, like training a Pytorch network alone, it did not happens.

**Comment by ywu36** [comment]
@soumith 
Maybe, actually, the error happens after the Caffe network is able to generate some outputs, which means the Caffe network already be initialized completely. The error only happens in the multi-process mode, in a normal function call (without mp.Process), the problem does not happen.
