### ISSUE TITLE
JIT RuntimeError: isTensor() ASSERT FAILED

### ISSUE THREAD

**Issue by edgarriba** [pytorch/pytorch#21536]
## RuntimeError: isTensor() ASSERT FAILED 🐛

We want to provide jitted versions of [Kornia](https://github.com/arraiyopensource/kornia) functions and by doing so during the tests we found the following issue when tracing a `nn.Module` that internally calls a scripted version of a simple function of the library:

```bash
(base) 1 edgar@edgar-ThinkPad-T460:~$ python test_jit.py
test_jit.py:17: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return op_script(input, height, width)
Traceback (most recent call last):
  File "test_jit.py", line 21, in <module>
    op_traced = torch.jit.trace(my_test_op, torch.rand(1,2,4,4))
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/jit/__init__.py", line 688, in trace
    var_lookup_fn, _force_outplace)
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "test_jit.py", line 17, in forward
    return op_script(input, height, width)
RuntimeError: isTensor() ASSERT FAILED at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/core/ivalue.h:209, please report a bug to PyTorch. (toTensor at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/core/ivalue.h:209)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f9d9e43ddc5 in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x96437d (0x7f9d9733137d in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #2: torch::jit::tracer::getNestedValueTrace(c10::IValue const&) + 0x41 (0x7f9d97593eb1 in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #3: <unknown function> + 0xa5af9b (0x7f9d97427f9b in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0xa5b15b (0x7f9d9742815b in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x458bf3 (0x7f9dcd772bf3 in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x12d07a (0x7f9dcd44707a in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: <unknown function> + 0x3e73e6 (0x7f9dcd7013e6 in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #29: <unknown function> + 0x44830b (0x7f9dcd76230b in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #30: <unknown function> + 0x45b1c4 (0x7f9dcd7751c4 in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #31: <unknown function> + 0x12d07a (0x7f9dcd44707a in /home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #46: __libc_start_main + 0xe7 (0x7f9ddaaeab97 in /lib/x86_64-linux-gnu/libc.so.6)
```

## To Reproduce

1. Install kornia: `pip install git+https://github.com/arraiyopensource/kornia`
2. Run the following script:
```python
import torch
import torch.nn as nn
 
import kornia
 
@torch.jit.script
def op_script(input: torch.Tensor, height: int,
              width: int) -> torch.Tensor:
    return kornia.normalize_pixel_coordinates(input, height, width)
 
class MyTestModule(nn.Module):
    def __init__(self):
        super(MyTestModule, self).__init__()
 
    def forward(self, input):
        height, width = input.shape[-2:]
        return op_script(input, height, width)
 
 
my_test_op = MyTestModule()
op_traced = torch.jit.trace(my_test_op, torch.rand(1,2,4,4))
```

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torchgeometry==0.1.0
[conda] mkl                       2019.3                      199
[conda] mkl_fft                   1.0.13           py37h516909a_1    conda-forge
[conda] mkl_random                1.0.4            py37hf2d7682_0    conda-forge
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch

**Comment by bhack** [comment]
Is it a duplicate of https://github.com/pytorch/pytorch/issues/21009?

**Comment by wanchaol** [comment]
Yes it should be a duplicate of #21009 and the bug already been fixed. Are you on pytorch 1.1 or on the pytorch nightlies? I would encourage you to try our nightlies to see if it has been resolve or not. I tried you script in master and it gives me this error

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    op_traced = torch.jit.trace(my_test_op, torch.rand(1,2,4,4))
  File "/scratch/wanchaol/local/pytorch/torch/jit/__init__.py", line 730, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/scratch/wanchaol/local/pytorch/torch/jit/__init__.py", line 849, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/scratch/wanchaol/local/pytorch/torch/nn/modules/module.py", line 492, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/scratch/wanchaol/local/pytorch/torch/nn/modules/module.py", line 482, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "test.py", line 17, in forward
    return op_script(input, height, width)
RuntimeError:
ValueError: Input pixel_coordinates must be of shape (*, 2). Got torch.Size([1, 2, 4, 4])
```
input not valid?

**Comment by edgarriba** [comment]
hi @wanchaol , I confirm that with the nigthly build at least the code doesn't crash. As for your error, the input should be (1,4,4,2) - sorry my bad.

Besides, we are not getting the expected behavior since the height and width are casted to constants during the trace and we might want to infer them at running time like in the eager version of the function.

I attach an updated version of what we might expect:
```python
import torch
import torch.nn as nn
from torch.testing import assert_allclose

import kornia

@torch.jit.script
def op_script(input: torch.Tensor, height: int,
              width: int) -> torch.Tensor:
    return kornia.normalize_pixel_coordinates(input, height, width)

class MyTestModule(nn.Module):
    def __init__(self):
        super(MyTestModule, self).__init__()

    def forward(self, input): 
        height, width = input.shape[-2:]
        return op_script(input, height, width)


my_test_op = MyTestModule()
op_traced = torch.jit.trace(my_test_op, torch.rand(1,4,4,2))

# create points grid

height, width = 5, 5
points = kornia.create_meshgrid(
    height, width, normalized_coordinates=False) # 1xHxWx2

# we expect that the traced function generalises with different
# input shapes. Ideally we might want to infer to traced the h and w.
assert_allclose(op_traced(points),
    kornia.normalize_pixel_coordinates(points, height, width))
```

we had an internal discussion about how to handle this cases and at the conclusion we arrived is to force all the signature parameters to be tensors. What would you recommend for that ?

**Comment by wanchaol** [comment]
Since height, weight are input dependent, it is better you can turn `MyTestModule` to ScriptModule as well, script mode should handle all the data dependent problem that could not be handled during tracing. 

Another option is to `op_script` take all tensors, and inside the op_script, cast the height and weight to int

**Comment by edgarriba** [comment]
tried you second solution assuming all tensors,
```python
@torch.jit.script
def op_script(input, height, width):
    return kornia.normalize_pixel_coordinates(input, int(height), int(width))
```
and getting this error trace:
```bash
(base) 1 edgar@edgar-ThinkPad-T460:~$ python test_jit.py 
Traceback (most recent call last):
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/jit/__init__.py", line 565, in run_mod_and_filter_tensor_outputs
    outs = wrap_retval(mod(*_clone_inputs(inputs)))
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "test_jit.py", line 22, in forward
    return op_script(input, height, width)
RuntimeError: op_script() expected a value of type 'Tensor' for argument 'height' but instead found type 'int'.
Inferred 'height' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 1
Value: 4
Declaration: op_script(Tensor input, Tensor height, Tensor width) -> Tensor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_jit.py", line 26, in <module>
    op_traced = torch.jit.trace(my_test_op, torch.rand(1,4,4,2))
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/jit/__init__.py", line 730, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/jit/__init__.py", line 859, in trace_module
    check_tolerance, _force_outplace, True)
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/jit/__init__.py", line 604, in _check_trace
    fn_outs = run_mod_and_filter_tensor_outputs(func, inputs, 'Python function')
  File "/home/edgar/software/kornia/.dev_env/lib/python3.7/site-packages/torch/jit/__init__.py", line 571, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the Python function with test inputs.
Exception:
        op_script() expected a value of type 'Tensor' for argument 'height' but instead found type 'int'.
        Inferred 'height' to be of type 'Tensor' because it was not annotated with an explicit type.
        Position: 1
        Value: 4
        Declaration: op_script(Tensor input, Tensor height, Tensor width) -> Tensor
```

**Comment by wanchaol** [comment]
@edgarriba in the second solution, you will need to pass height and weight as tensors, rather than ints. 

This should work:

```python
@torch.jit.script
def op_script(input, height, width):
    return kornia.normalize_pixel_coordinates(input, int(height), int(width))

class MyTestModule(nn.Module):
    def __init__(self):
        super(MyTestModule, self).__init__()

    def forward(self, input):
        height, width = input.shape[-2:]
        if not torch._C._get_tracing_state():
            height = torch.tensor(height)
            width = torch.tensor(width)

        return op_script(input, height, width)


my_test_op = MyTestModule()
op_traced = torch.jit.trace(my_test_op, torch.rand(1,4,4,2))
```

**Comment by wanchaol** [comment]
the reason why we have this `_get_tracing_state` condition here is, it will fail the tracing sanity check because the sanity check tries to run everything in python, which produce ints for `shape`, but tracing itself produce separate tensors for `shape`. This is kind of weird but must to have for tracing with casts. I would suggest you guys use the option 1 instead of option 2

**Comment by edgarriba** [comment]
@wanchaol thanks for providing a solution, but I don't feel quite convinced about it. I just see one thing here: from the maintenance side of the library if we want to provide jit ready functions to be traced, does it mean that we have to wrap every single function to a ScriptModule, cast all to tensors and so ? Also from user side, in case we don't provide such wrapping could be really a pain to the user and convert the whole thing to the worst user friendly lib ever.

A "quick" fix we figured out would be converting the non-tensors parameters from all signatures to tensor, meaning that this will break all our current api and its backward compatibility. We have also been tracking this issue: https://github.com/pytorch/pytorch/issues/20939 Do you think that this will make things easier from jit perspective side ?

**Comment by wanchaol** [comment]
@edgarriba Yeah that was something that I want to recommend. Our new API should be able to address your case, it can make you share the eager mode module and script module together, and our script module should handle the data dependent problem. You can already try the new API (probably in test_jit.py) since it's been landed recently. @driazati will also write up the documentation for it this week.

**Comment by suo** [comment]
@edgarriba is this still an issue for you?

**Comment by edgarriba** [comment]
@suo I think we can close this after your last patch
