### ISSUE TITLE
[JIT] Default method arguments for container types is broken

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#21545]
```
import torch
from typing import List

class Foo(torch.jit.ScriptModule):
    @torch.jit.script_method
    def forward(self, languages: List[str]=[], per_token_languages: List[List[str]]=[]):
        return torch.rand(3, 4)

f = Foo()
f.save('/tmp/test.zip')

torch.jit.load('/tmp/test.zip')
```

```
Traceback (most recent call last):
  File "repro_load_fail2.py", line 12, in <module>
    torch.jit.load('/tmp/test.zip')
  File "/Users/jamesreed/pytorch/torch/jit/__init__.py", line 147, in load
    torch._C.import_ir_module(module_lookup, f, map_location, _extra_files)
RuntimeError:
Return value was annotated as having type Tuple[List[str], List[List[str]]] but is actually of type Tuple[List[Tensor], List[Tensor]]:
at code/test.py:2:12
op_version_set = 1
def forward(self,
           ~~~~~~...  <--- HERE
    languages: List[str]=[],
    per_token_languages: List[List[str]]=[]) -> Tensor:
  _0 = torch.rand([3, 4], dtype=None, layout=None, device=None, pin_memory=None)
  return _0
```

cc @suo

**Comment by jamesr66a** [comment]
Relevant compiler code: https://github.com/pytorch/pytorch/blob/fe5ceea580600b2adf4a7509132ffaf2949189d1/torch/csrc/jit/script/compiler.cpp#L645

We need to handle this differently somehow

**Comment by eellison** [comment]
I'm not sure we should support default argument types for container types. This is one of the biggest gotchas in python.
```
def test(x=[]):
   x.append(1)
   return len(x)

print(test()) # 1
print(test()) # 2
```

**Comment by apaszke** [comment]
:+1: for not supporting this, but we should have a nice error message suggesting a fix.
