### ISSUE TITLE
test_signal_window_functions is flaky on ROCm

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#21585]
```
10:23:15 ======================================================================
10:23:15 FAIL: test_signal_window_functions (__main__.TestCuda)
10:23:15 ----------------------------------------------------------------------
10:23:15 Traceback (most recent call last):
10:23:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
10:23:15     method(*args, **kwargs)
10:23:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
10:23:15     method(*args, **kwargs)
10:23:15   File "test_cuda.py", line 2246, in test_signal_window_functions
10:23:15     _TestTorchMixin._test_signal_window_functions(self, device=torch.device('cuda'))
10:23:15   File "/var/lib/jenkins/workspace/test/test_torch.py", line 5840, in _test_signal_window_functions
10:23:15     test(window)
10:23:15   File "/var/lib/jenkins/workspace/test/test_torch.py", line 5831, in test
10:23:15     self.assertEqual(res, ref)
10:23:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 547, in assertEqual
10:23:15     assertTensorsEqual(x, y)
10:23:15   File "/var/lib/jenkins/workspace/test/common_utils.py", line 539, in assertTensorsEqual
10:23:15     self.assertLessEqual(max_err, prec, message)
10:23:15 AssertionError: tensor(0.9999, device='cuda:0') not less than or equal to 1e-05 : 
10:23:15 
```

Example: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/24583/console

**Comment by ezyang** [comment]
cc @bddppq 

More failures

```
05:38:26 ======================================================================
05:38:26 FAIL: test_DoubleTensor_dot (__main__.TestCuda)
05:38:26 ----------------------------------------------------------------------
05:38:26 Traceback (most recent call last):
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
05:38:26     method(*args, **kwargs)
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
05:38:26     method(*args, **kwargs)
05:38:26   File "test_cuda.py", line 659, in tmp
05:38:26     self.assertEqual(cpu_result, gpu_result, precision)
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 547, in assertEqual
05:38:26     assertTensorsEqual(x, y)
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 539, in assertTensorsEqual
05:38:26     self.assertLessEqual(max_err, prec, message)
05:38:26 AssertionError: tensor(9.3843) not less than or equal to 1e-05 : 
05:38:26 
05:38:26 ======================================================================
05:38:26 FAIL: test_signal_window_functions (__main__.TestCuda)
05:38:26 ----------------------------------------------------------------------
05:38:26 Traceback (most recent call last):
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
05:38:26     method(*args, **kwargs)
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
05:38:26     method(*args, **kwargs)
05:38:26   File "test_cuda.py", line 2246, in test_signal_window_functions
05:38:26     _TestTorchMixin._test_signal_window_functions(self, device=torch.device('cuda'))
05:38:26   File "/var/lib/jenkins/workspace/test/test_torch.py", line 5935, in _test_signal_window_functions
05:38:26     test(window)
05:38:26   File "/var/lib/jenkins/workspace/test/test_torch.py", line 5926, in test
05:38:26     self.assertEqual(res, ref)
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 547, in assertEqual
05:38:26     assertTensorsEqual(x, y)
05:38:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 539, in assertTensorsEqual
05:38:26     self.assertLessEqual(max_err, prec, message)
05:38:26 AssertionError: tensor(2045., device='cuda:0') not less than or equal to 1e-05 : 
05:38:26 
05:38:26 ----------------------------------------------------------------------
05:38:26 Ran 2136 tests in 306.392s
05:38:26 
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/24787//console

**Comment by bddppq** [comment]
Created a jira ticket in the amd jira. @iotamudelta Could you help follow up with the investigation?

**Comment by gottbrath** [comment]
Is this still happening? The corresponding Jira issue (FBA-84) is marked fixed but not closed

**Comment by gottbrath** [comment]
https://ontrack.amd.com/browse/FBA-84

**Comment by gottbrath** [comment]
from Diwaker "Chris Gottbrath fix was in VBIOS update (for MI25) and in ROCm2.5. Since the issue was reported on CI node (worker3), we upgraded the CI node (VBIOS D0513100-006 for MI25 and reinstalling ROCm 2.5) and verified that test is passing.

Please let us know, if you still see the issue on worker3."

Do we still see trouble with CI worker3?

**Comment by jeffdaily** [comment]
Closing.  Issue is no longer observed.
