### ISSUE TITLE
with emit_nvtx context manager is broken in current master.

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#21644]
```
$ docker pull pytorch/pytorch:nightly-runtime-cuda10.0-cudnn7
$ docker run --runtime=nvidia -it --rm --ipc=host pytorch/pytorch:nightly-runtime-cuda10.0-cudnn7
```
Run the following script:
```
import torch

a = torch.tensor([1,2,3], dtype=torch.float32, device='cuda')

with torch.cuda.profiler.profile():
    with torch.autograd.profiler.emit_nvtx():
        b = a.sum()
```

Result:
```
root@0727b6d13c99:/data/sandbox_python/autograd_explore/profiler# python test.py 
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    with torch.autograd.profiler.emit_nvtx():
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/profiler.py", line 398, in __enter__
    self.record_shapes
AttributeError: 'emit_nvtx' object has no attribute 'record_shapes'
```

The offending line is simple:
https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py#L398
I'd submit a quick PR to fix it, but I'm not sure what you guys actually want the value of record_shapes to be for this call.

**Comment by zou3519** [comment]
I don't know the answer to that question, but here's the PR that introduced it: https://github.com/pytorch/pytorch/pull/20035. cc @salexspb and @zdevito

**Comment by zou3519** [comment]
Seems like it should be `False` for backwards compatibility. We should probably add a `record_shapes` option to `emit_nvtx`'s `__init__`.

**Comment by mcarilli** [comment]
I have a local PR ready, gimme about an hour to test it.

**Comment by zou3519** [comment]
Do nvtx ranges support adding extra information (like the input shapes)? Not sure if `record_shapes` makes sense for `emit_nvtx`

**Comment by mcarilli** [comment]
> Do nvtx ranges support adding extra information (like the input shapes)? 

Not currently, but my PR https://github.com/pytorch/pytorch/pull/21691 includes some surgical changes to `torch/csrc/autograd/profiler.cpp` such that nvtx ranges can append shape information.

**Comment by zou3519** [comment]
I think this is fixed by @mcarilli's #21691
