### ISSUE TITLE
How can I verify caffe2 install success?

### ISSUE THREAD

**Issue by bruce2k** [pytorch/pytorch#21676]
## ❓ Questions and Help

hi,

OS is ubuntu17.10,
python 3.6.8

I installed Caffee2 in my PC, but I don't know how to verify if it's success.
the installation instructions follow "https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt"  select Ubuntu & Pre-Built Binaries , install command:

conda install pytorch-nightly cuda90 -c pytorch

Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/bruce/anaconda3/envs/maskrcnn

  added / updated specs:
    - cuda90
    - pytorch-nightly

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-nightly-1.2.0.dev20190612|py3.6_cuda10.0.130_cudnn7.5.1_0       450.4 MB  pytorch
    ------------------------------------------------------------
                                           Total:       450.4 MB

The following packages will be UPDATED:

  pytorch-nightly    1.2.0.dev20190610-py3.6_cuda10.0.130_~ --> 1.2.0.dev20190612-py3.6_cuda10.0.130_cudnn7.5.1_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
pytorch-nightly-1.2. | 450.4 MB  | ################################################################################################################################################################# | 100% 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

after every thing done, i execute following command to verify but  got "Failure"

~$ python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Failure

even i import core, workspace in python the error occurs ,anybody help me solve the problem? 

Thanks a lot!

Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core, workspace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruce/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
>>> import torch
>>> torch.__version__
'0.4.1'
>>>

**Comment by bruce2k** [comment]
after execute 'pip install future' the problem solved
