### ISSUE TITLE
No PyPI packages for Python 3.8 which will be released soon (expected October)

### ISSUE THREAD

**Issue by umanwizard** [pytorch/pytorch#21741]
```
~ ❯❯❯ LD_LIBRARY_PATH=$HOME/pysandbox/lib ~/pysandbox/bin/pip3 install torch
/Users/btv/pysandbox/lib/python3.8/site-packages/pip/_vendor/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
Collecting torch
/Users/btv/pysandbox/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py:220: PendingDeprecationWarning: encoding is deprecated, Use raw=False instead.
  warnings.warn(
  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    /Users/btv/pysandbox/lib/python3.8/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xm/k62yj65n0qd9n40myt10y8sjpk8rbt/T/pip-install-6cdjtra9/torch/setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).
    
    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xm/k62yj65n0qd9n40myt10y8sjpk8rbt/T/pip-install-6cdjtra9/torch/
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by stonebig** [comment]
Will we have a wheel for Python-3.8.0rc1 ?

**Comment by stonebig** [comment]
Will we have a wheel for Python-3.8.0rc2 ?

**Comment by soumith** [comment]
we will have wheels and binaries for python 3.8.0 stable, but only for the next pytorch release, which will be either 1.3.1 or 1.4.0

**Comment by talhakabakus** [comment]
Any ideas when will the next release be released? @soumith

**Comment by soumith** [comment]
sometime in december

**Comment by algoterranean** [comment]
@soumith Are we any closer to a known or planned release date?

**Comment by mileserickson** [comment]
Any updates on this? The current behavior (installation of `torch` version 0.1.2 and/or failure to install `torch>=1.0.0`) is potentially confusing to users.

**Comment by stonebig** [comment]
torch-1.4.0+cpu-cp38-cp38-win_amd64.whl is out

**Comment by soumith** [comment]
python 3.8 packages on PyPI are live for both OSX and Linux. 

https://pypi.org/project/torch/#files
