### ISSUE TITLE
pytorch installation problem

### ISSUE THREAD

**Issue by shwoo93** [pytorch/pytorch#2177]
Hello

In order to follow up with the current state of the pytorch version in github, I followed the below setup.

**Firstly, I build the image with cuda 8.0-ubuntu 14.04**

On top of this image, I made a container and installed anaconda and opencv.

**bash Anaconda3-4.4.0-Linux-x86_64.sh
conda update conda
conda install opencv**

After then, I cloned this github page and followed the instructions provided.

**git clone https://github.com/pytorch/pytorch.git
export CMAKE_PREFIX_PATH=[anaconda root directory]
conda install numpy pyyaml mkl setuptools cmake gcc cffi
conda install -c soumith magma-cuda80
python setup.py install
conda install torchvision**

After the above installation is finished, I tried to run my code but I got the following error....

Loading base network...
Traceback (most recent call last):
  File "train_deform.py", line 93, in <module>
    net.cuda()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 124, in _apply
    param.data = fn(param.data)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in <lambda>
    return self._apply(lambda t: t.cuda(device_id))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 272, in __new__
    _lazy_init()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 51, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
**AssertionError: Torch not compiled with CUDA enabled**

I also checked nvidia-smi and nvcc --version in order to check whether GPU and CUDA is well specified, However there was no problem with in it.

**I cant find the problem. Since I just installed magma-cuda80 right before the installing setup.py. What is the problem ?**

**Comment by ngimel** [comment]
Are you talking about docker images? Do runtime and devel dockerfiles in this repo not fit your needs?

**Comment by soumith** [comment]
Please see: https://github.com/pytorch/pytorch/blob/master/Dockerfile

**Comment by ngimel** [comment]
Problem was with ```conda install torchvision```. Please use provided Dockerfiles.

**Comment by xperzy** [comment]
Note that if you are using docker file from the pytorch git repo, the dockerfile could ONLY be run without error when you:

1. git clone the pytorch repo
2. run docker build -t pytorch . in the pytorch directory.

**Comment by shabazbpatel** [comment]
Using Docker is a good solution to have a reproducible environment. You can install docker from [here](https://docs.docker.com/engine/installation/). As answered by Soumith, you can use the Dockerfile. You can also try using [datmo](https://datmo.com) in order setup environment and track machine learning projects for making it reproducible.
