### ISSUE TITLE
test_nuclear_norm_axes_small_brute_force is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#21785]
```
Jun 14 15:36:31 ======================================================================
Jun 14 15:36:31 FAIL: test_nuclear_norm_axes_small_brute_force (__main__.TestCuda)
Jun 14 15:36:31 ----------------------------------------------------------------------
Jun 14 15:36:31 Traceback (most recent call last):
Jun 14 15:36:31   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
Jun 14 15:36:31     method(*args, **kwargs)
Jun 14 15:36:31   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
Jun 14 15:36:31     method(*args, **kwargs)
Jun 14 15:36:31   File "test_cuda.py", line 2696, in test_nuclear_norm_axes_small_brute_force
Jun 14 15:36:31     _TestTorchMixin._test_nuclear_norm_axes(self, device='cuda')
Jun 14 15:36:31   File "/var/lib/jenkins/workspace/test/test_torch.py", line 1052, in _test_nuclear_norm_axes
Jun 14 15:36:31     check_single_nuclear_norm(x, axes)
Jun 14 15:36:31   File "/var/lib/jenkins/workspace/test/test_torch.py", line 994, in check_single_nuclear_norm
Jun 14 15:36:31     self.assertTrue(np.allclose(ans.cpu(), expected, rtol=1e-02, atol=1e-03))
Jun 14 15:36:31 AssertionError: False is not true
Jun 14 15:36:31 
Jun 14 15:36:31 ----------------------------------------------------------------------
Jun 14 15:36:31 Ran 2140 tests in 129.723s
```

https://circleci.com/gh/pytorch/pytorch/1997492

First thing to check is if we're deterministically seeding correctly. If we are, then check for access to uninitialized memory.

cc @skrah

**Comment by skrah** [comment]
If I understand #21589 correctly, the test skip in #21638 is just a temporary workaround.

`cuda-memcheck --tool initcheck` shows **read** access to uninitialized memory in magma, but in many tests, not just `nuclear_norm`.

**Comment by skrah** [comment]
Can we close this in favor of #21821? I haven't seen the error again on master, so the #21638 changes appear to work.
