### ISSUE TITLE
ImportError: No module named hubconfs.bert_hubconf

### ISSUE THREAD

**Issue by luricheng** [pytorch/pytorch#21826]
### when I load bert by torch.hub, No module named hubconfs.bert_hubconf

```
/home/luricheng/.cache/torch/hub/huggingface_pytorch-pretrained-BERT_master/hubconf.py:3: RuntimeWarning: Parent module 'hubconf' not found while handling absolute import
  from hubconfs.bert_hubconf import (
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/luricheng/anaconda3/envs/py2/lib/python2.7/site-packages/torch/hub.py", line 336, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/luricheng/anaconda3/envs/py2/lib/python2.7/site-packages/torch/hub.py", line 77, in import_module
    return imp.load_source(name, path)
  File "/home/luricheng/.cache/torch/hub/huggingface_pytorch-pretrained-BERT_master/hubconf.py", line 3, in <module>
    from hubconfs.bert_hubconf import (
ImportError: No module named hubconfs.bert_hubconf
```

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by umanwizard** [comment]
Can you give a short example of the code you're using to load it?

**Comment by ailzhang** [comment]
@luricheng Try switching to python3 or latest pytorch master for py2 with `torch.hub.load(..., force_reload=True)`?

**Comment by ailzhang** [comment]
Closing this due to no response. Please feel free to reopen if you have followup questions.
