### ISSUE TITLE
untimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:111

### ISSUE THREAD

**Issue by EthanChen911238** [pytorch/pytorch#21825]
I use python 3.6.8 and pytorch version is 1.0.1
When I try to build Seq2Seq model and using CrossEntropyLoss, I got error message below

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=111 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "sent2hyngram_train.py", line 351, in <module>
    valid_loss, valid_acc = evaluate_multiTag(model, valid_corpus, criterion)
  File "sent2hyngram_train.py", line 327, in evaluate_multiTag
    loss = criterion(output, trg)
  File "/root/anaconda3/envs/Seq2Seq-LSTM-Attn-pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/Seq2Seq-LSTM-Attn-pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/root/anaconda3/envs/Seq2Seq-LSTM-Attn-pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/root/anaconda3/envs/Seq2Seq-LSTM-Attn-pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1790, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:111

I'm sure that my target embedding is [0, n_classes], but I still got this error.
Please help me.

**Comment by ngimel** [comment]
That error is usually caused by out-of-bounds target values, double check that they are between 0 and corresponding input size.

**Comment by EthanChen911238** [comment]
After I check my target value, it actually out-of-bounds.
Thanks a lot.
