### ISSUE TITLE
_jit_internal.weak_module does not allow ModuleList in __constants__

### ISSUE THREAD

**Issue by borchero** [pytorch/pytorch#21845]
## 🐛 Bug

When using ``torch.nn.ModuleList`` within a module annotated with ``torch._jit_internal.weak_module``, an error is raised in the forward method, incorrectly stating that the ModuleList is not added to ``__constants__`` although it is.

## To Reproduce

Minimum working example to reproduce the bug:

```
import torch
import torch.nn as nn
import torch.jit as jit
import torch._jit_internal as _jit

@_jit.weak_module
class MyWeakModule(nn.Module):

    __constants__ = ['linears']

    def __init__(self):
        super().__init__()
        self.linears = nn.ModuleList([nn.Linear(10, 10), nn.Linear(10, 10)])

    @_jit.weak_script_method
    def forward(self, x):
        for linear in self.linears:
            x = linear(x)
        return x

class MyScriptModule(jit.ScriptModule):

    def __init__(self):
        super().__init__()
        self.linear = MyWeakModule()

    @jit.script_method
    def forward(self, x):
        return self.linear(x)

if __name__ == '__main__':
    model = MyScriptModule()
    x = torch.rand(1, 10)
    out = model(x)
    print(out)
```

Traceback of Error:

```
Traceback (most recent call last):
  File "mmwe.py", line 32, in <module>
    model = MyScriptModule()
  File "/nfs/homedirs/user/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "mmwe.py", line 25, in __init__
    self.linear = MyWeakModule()
  File "/nfs/homedirs/user/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1238, in __setattr__
    value = _make_strong(value)
  File "/nfs/homedirs/user/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1410, in _make_strong
    proxy = WeakScriptModuleProxy(mod, stubs)
  File "/nfs/homedirs/user/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "/nfs/homedirs/user/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1344, in __init__
    _create_methods_from_stubs(self, stubs)
  File "/nfs/homedirs/user/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1012, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 
python value of type 'ModuleList' cannot be used as a tuple. Did you forget to add it to __constants__? :
@_jit.weak_script_method
def forward(self, x):
    for linear in self.linears:
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
        x = linear(x)
    return x
```

Note that the usage of ``ModuleList`` in this context is, of course, unnecessary. There exist use cases, however, where it cannot be avoided (I am currently implementing a stacked LSTM with different hidden dimensions).

## Expected behavior

Using ModuleList in ``__constants__`` should work even if ``weak_module`` is used instead
of ``ScriptModule``.

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 384.130
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi
```

## Additional context

I am aware that ``weak_module`` is only part of the internal API, however, to extend PyTorch's library of modules "natively", it should be possible to use ``weak_module`` instead of ``ScriptModule``.

**Comment by driazati** [comment]
This use case is addressed by the [new API](https://pytorch.org/docs/master/jit.html#migrating-to-pytorch-1-2-recursive-scripting-api)
