### ISSUE TITLE
RuntimeError: s__th_ne is not implemented for type SparseCPUType

### ISSUE THREAD

**Issue by simonepri** [pytorch/pytorch#21840]
## 🐛 Bug
See title

## To Reproduce
Unable to provide a short repro, I can provide the full code if necessary.

Ref: https://github.com/facebookresearch/PyTorch-BigGraph/issues/51#issuecomment-502410183

## Stack Trace

<details><summary>Show</summary>

```
sys:1: RuntimeWarning: Traceback of forward call that caused the error:
  File "PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 96, in <module>
    main()
  File "PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 78, in main
    train(train_config)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 804, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank):
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 381, in train_and_report_stats
    pool = create_pool(num_workers)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/util.py", line 115, in create_pool
    return mp.Pool(num_workers, initializer=_pool_init)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/batching.py", line 86, in call
    return f()
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/batching.py", line 120, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 124, in process_one_batch
    scores = model(batch_edges)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 1077, in forward
    Negatives.NONE,
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 1115, in forward_direction_agnostic
    self.num_uniform_negs, rel, src_entity_type, src_operator)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 904, in prepare_negatives
    num_chunks, num_uniform_neg)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 147, in sample_entities
    return self.get(torch.randint(low=0, high=self.weight.size(0), size=dims))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 140, in get
    input_, self.weight, max_norm=self.max_norm, sparse=True,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

sys:1: RuntimeWarning: Traceback of forward call that caused the error:
  File "PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 96, in <module>
    main()
  File "PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 78, in main
    train(train_config)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 804, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank):
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 381, in train_and_report_stats
    pool = create_pool(num_workers)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/util.py", line 115, in create_pool
    return mp.Pool(num_workers, initializer=_pool_init)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/batching.py", line 86, in call
    return f()
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/batching.py", line 120, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 124, in process_one_batch
    scores = model(batch_edges)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 1077, in forward
    Negatives.NONE,
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 1115, in forward_direction_agnostic
    self.num_uniform_negs, rel, src_entity_type, src_operator)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 904, in prepare_negatives
    num_chunks, num_uniform_neg)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 147, in sample_entities
    return self.get(torch.randint(low=0, high=self.weight.size(0), size=dims))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/model.py", line 140, in get
    input_, self.weight, max_norm=self.max_norm, sparse=True,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/batching.py", line 86, in call
    return f()
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/batching.py", line 120, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 139, in process_one_batch
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: s__th_ne is not implemented for type SparseCPUType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 96, in <module>
    main()
  File "PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 78, in main
    train(train_config)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 804, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank):
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 691, in train_and_report_stats
    num_parts=num_workers))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
RuntimeError: s__th_ne is not implemented for type SparseCPUType
```

</details>

## Environment
I was using Colab and BigGraph with `torch.autograd.set_detect_anomaly(True)`

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.3.0
[conda] Could not collect

**Comment by mruberry** [comment]
Closing this issue because of age. The cited function no longer appears to exist. @simonepri, if you think this is in error would you please update and reopen this issue?
