### ISSUE TITLE
NameError: name 'logging' is not defined

### ISSUE THREAD

**Issue by xyl576807077** [pytorch/pytorch#22011]
It seems the *_pytorch_graph.py* don't import *logging* module
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "new_paradigm_train.py", line 338, in <module>
    train(cfg, writer, logger)
  File "new_paradigm_train.py", line 263, in train
    writer.add_graph(model, images_val)
  File "/home/xyl/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 534, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/xyl/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 303, in graph
    logging.warn(ImportError(e))
NameError: name 'logging' is not defined
```

**Comment by soumith** [comment]
cc: @lanpa

**Comment by vishwakftw** [comment]
I think this has been fixed on master, because the point of error is non-existent on master.

**Comment by iArunava** [comment]
When will the changes be reflected in PyPI index? :thinking:

**Comment by soumith** [comment]
@iArunava in the next release end of this month

**Comment by CompRhys** [comment]
Any update on when the fix will be reflected on PyPI or conda?

**Comment by fmassa** [comment]
@CompRhys the next release will be out end of this week

**Comment by iszff** [comment]
I met the same question
