### ISSUE TITLE
Forward pass OK, backward pass broken for cat + repeat

### ISSUE THREAD

**Issue by ezliu** [pytorch/pytorch#2208]
When using cat followed by a repeat (which adds a dimension), the backprop throws the following errors:

```
Traceback (most recent call last):
  File "minimal.py", line 73, in <module>
    optimizer.step()
  File "/usr/local/lib/python2.7/site-packages/torch/optim/adam.py", line 74, in step
    p.data.addcdiv_(-step_size, exp_avg, denom)
RuntimeError: inconsistent tensor size at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:1127
```

AND

```
Traceback (most recent call last):
  File "minimal.py", line 72, in <module>
    loss.backward()
  File "/usr/local/lib/python2.7/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/usr/local/lib/python2.7/site-packages/torch/autograd/_functions/blas.py", line 40, in backward
    grad_matrix1 = torch.mm(grad_output, matrix2.t())
RuntimeError: matrices expected, got 3D, 2D tensors at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:1232
```

Below is a minimal case that demonstrates both of these errors. In both cases, the forward pass succeeds in computing some sort of loss, while the backward pass fails. The two defined `forward` methods demonstrate different RuntimeErrors being thrown. These RuntimeErrors are not thrown when tile is achieved by `tile_via_unsqueeze_repeat` or `tile_via_expand`, as shown below (uncomment the other model lines).

```
import torch
import torch.nn as nn
import torch.optim as optim

from torch.autograd import Variable


class Model(nn.Module):
    def __init__(self, tile_function):
        super(Model, self).__init__()
        self.weight1 = nn.Parameter(torch.rand(10, 5))
        self.weight2 = nn.Parameter(torch.rand(10, 5))

        self.cat = nn.Parameter(torch.rand(5, 1))

        self.tile = tile_function

    def forward(self, inp):
        mult1 = torch.mm(self.weight1, inp)
        mult2 = torch.mm(self.weight2, inp)
        cat = torch.cat([mult1, mult2], 1)

        tile = self.tile(cat)
        
        add = torch.sum(tile, 0)
        add = torch.sum(add, 1)
        add = torch.sum(add, 2)
        return add

    #def forward(self, inp):
    #    cat = torch.cat([self.cat, inp], 1)
    #    tile = self.tile(cat)
    #    
    #    add = torch.sum(tile, 0)
    #    add = torch.sum(add, 1)
    #    add = torch.sum(add, 2)
    #    return add


def tile_via_expand(x):
    a, b = x.size()
    x = torch.unsqueeze(x, 0)
    x = x.expand(100, a, b)
    return x

def tile_via_repeat(x):
    x = x.repeat(100, 1, 1)
    return x

def tile_via_unsqueeze_repeat(x):
    x = torch.unsqueeze(x, 0)
    x = x.repeat(100, 1, 1)
    return x

# Works
#model = Model(tile_via_expand)

# Works
#model = Model(tile_via_unsqueeze_repeat)

# Broken (yields errors in backprop)
model = Model(tile_via_repeat)

inp = Variable(torch.rand(5, 1))

optimizer = optim.Adam(model.parameters())

for i in xrange(10):
    loss = model(inp)
    print loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

```

**Comment by apaszke** [comment]
Fixed in #2095.
