### ISSUE TITLE
Segmentation fault Autograd 

### ISSUE THREAD

**Issue by shoukang** [pytorch/pytorch#22108]
Hi everyone,
 
When I train a CNN on cifar10, it seems that my training occasionally crashes with segmentation fault.

Error Message

```
#0  std::__push_heap<__gnu_cxx::__normal_iterator<torch::autograd::FunctionTask*, std::vector<torch::autograd::FunctionTask> >, long, torch::autograd::FunctionTask, __gnu_cxx::__ops::_Iter_com
p_val<torch::autograd::CompareFunctionTaskTime> > (__first=..., __holeIndex=1, __topIndex=__topIndex@entry=0, __value=...,
    __comp=...)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_heap.h:129
#1  0x00007fff59970892 in push_heap<__gnu_cxx::__normal_iterator<torch::autograd::FunctionTask*, std::vector<torch::autograd::FunctionTask> >, torch::autograd::CompareFunctionTaskTime> (__comp
=..., __last=..., __first=...)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_heap.h:199
#2  push (
    __x=<unknown type in /mnt/lustre/share/spring/envs/r0.2.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so, CU 0x3573e7d, DIE 0x363aba3>, this=0x5555b41e00a0)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_queue.h:510
#3  torch::autograd::ReadyQueue::push (this=0x5555b41e00a0, item=...)
    at torch/csrc/autograd/engine.cpp:188
#4  0x00007fff59974d98 in torch::autograd::Engine::thread_main (
    this=0x7fff5d3c6980 <engine>, graph_task=0x0)
    at torch/csrc/autograd/engine.cpp:264
#5  0x00007fff599701ae in torch::autograd::Engine::thread_init (
    this=this@entry=0x7fff5d3c6980 <engine>, device=device@entry=-1)
    at torch/csrc/autograd/engine.cpp:210
#6  0x00007fff5999f8da in torch::autograd::python::PythonEngine::thread_init (
    this=0x7fff5d3c6980 <engine>, device=-1)
    at torch/csrc/autograd/python_engine.cpp:39
#7  0x00007fffea123c5c in std::execute_native_thread_routine_compat (
    __p=<optimized out>)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libstdc++-v3/src/c++11/thread.cc:110
#8  0x00007ffff7bc6dc5 in start_thread () from /usr/lib64/libpthread.so.0
#9  0x00007ffff78f421d in clone () from /usr/lib64/libc.so.6
```

Training eight models separately on eight GPUs can accelerate reproducing.

I'm using pytorch 0.4.1, Linux version 3.10.0-327.36.3.el7.x86_64, Python 3.6, Cuda9.0, gcc 4.8.5, Titan X pascal.

**Comment by vishwakftw** [comment]
Can you provide a script to reproduce this issue?

**Comment by VitalyFedyunin** [comment]
@shoukang by any chance you can try installing new Pytorch, we have done a lot in terms of threading recently. And your problem might be related.

**Comment by albanD** [comment]
Optimistically closing this. Please re-open if you have a repro with latest pytorch.
