### ISSUE TITLE
aten::linspace error on Python 3.6

### ISSUE THREAD

**Issue by jamarshon** [pytorch/pytorch#22147]
## [jit] aten::linspace error on Python 3.6
For torchaudio's CI setup (https://github.com/pytorch/audio/blob/master/build_tools/travis/install.sh), pytorch nightly is used on linux. The job seems to fail for python 3.6 but not 3.5 due to some issue with aten::linspace (https://travis-ci.org/pytorch/audio/jobs/549804006). No code change occurred in the testing or torchaudio code meaning it should be a Pytorch issue.

## Error
```
Traceback (most recent call last):
  File "/home/travis/build/pytorch/audio/test/test_transforms.py", line 185, in test_mfcc
    torch_mfcc = mfcc_transform(audio_scaled)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 525, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: 
Schema not found for node. File a bug report.
Node: %stft_freqs.1 : Tensor = aten::linspace(%9, %39, %301, %5, %5, %35, %36) # /home/travis/build/pytorch/audio/torchaudio/functional.py:163:18
Input types:float, float, int, Scalar?, Scalar?, Device?, bool?
candidates were:
  aten::linspace(Scalar start, Scalar end, int steps=<default>, *, int? dtype=<default>, int? layout=<default>, Device? device=<default>, bool? pin_memory=<default>) -> Tensor
  aten::linspace(Scalar start, Scalar end, int steps=<default>, *, Tensor out) -> Tensor
within the graph:
graph(%self : ClassType<MFCC>,
      %sig.1 : Tensor):
  %2 : float = prim::Constant[value=10]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:276:42
  %3 : float = prim::Constant[value=1e-10]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:276:59
  %4 : None = prim::Constant() # /home/travis/build/pytorch/audio/torchaudio/functional.py:205:22
  %5 : Scalar? = prim::Constant()
  %6 : int = prim::Constant[value=1]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:139:60
  %7 : string = prim::Constant[value="Exception"]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:131:5
  %9 : float = prim::Constant[value=0]()
  %10 : int = prim::Constant[value=9223372036854775807]()
  %11 : int = prim::Constant[value=-1]() # /home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/torch/nn/functional.py:3079:53
  %12 : int = prim::Constant[value=-2]() # /home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/torch/nn/functional.py:3080:60
  %19 : string = prim::Constant[value="reflect"]() # /home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/torch/nn/functional.py:2804:24
  %24 : bool = prim::Constant[value=1]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:139:20
  %25 : bool = prim::Constant[value=0]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:201:51
  %26 : int = prim::Constant[value=2]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:201:39
  %27 : int = prim::Constant[value=200]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:200:70
  %28 : int = prim::Constant[value=400]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:200:58
  %29 : int = prim::Constant[value=0]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:200:35
  %30 : int = prim::Constant[value=10]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:170:21
  %31 : float = prim::Constant[value=700]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:166:68
  %32 : float = prim::Constant[value=1]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:166:54
  %33 : float = prim::Constant[value=2595]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:166:35
  %35 : Device? = prim::Constant()
  %36 : bool? = prim::Constant()
  %37 : float = prim::Constant[value=-1]() # /home/travis/build/pytorch/audio/torchaudio/functional.py:176:20
  %39 : float = prim::Constant[value=8000]() # /home/travis/build/pytorch/audio/torchaudio/transforms.py:238:69
  %41 : ClassType<MelSpectrogram> = prim::GetAttr[name="MelSpectrogram"](%self)
  %42 : ClassType<Spectrogram> = prim::GetAttr[name="spec"](%41)
  %43 : Tensor = prim::GetAttr[name="window"](%42)
  %44 : int = aten::dim(%sig.1) # /home/travis/build/pytorch/audio/torchaudio/functional.py:131:12
  %45 : bool = aten::eq(%44, %26) # /home/travis/build/pytorch/audio/torchaudio/functional.py:131:12
   = prim::If(%45) # /home/travis/build/pytorch/audio/torchaudio/functional.py:131:5
    block0():
      -> ()
    block1():
       = prim::RaiseException(%7) # /home/travis/build/pytorch/audio/torchaudio/functional.py:131:5
      -> ()
  %287 : Tensor = ^_stft()(%sig.1, %28, %27, %28, %43, %24, %19, %25, %24) # /home/travis/build/pytorch/audio/torchaudio/functional.py:138:14
  %spec_f.1 : Tensor = aten::transpose(%287, %6, %26) # /home/travis/build/pytorch/audio/torchaudio/functional.py:138:14
  %294 : Tensor = aten::pow(%spec_f.1, %26) # /home/travis/build/pytorch/audio/torchaudio/functional.py:143:14
  %368 : int[] = prim::Constant[value=[-1]]()
  %spec.1 : Tensor = aten::sum(%294, %368, %25) # /home/travis/build/pytorch/audio/torchaudio/functional.py:143:14
  %297 : ClassType<MelScale> = prim::GetAttr[name="fm"](%41)
  %298 : Tensor = prim::GetAttr[name="fb"](%297)
  %299 : int = aten::numel(%298) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:237:12
  %300 : bool = aten::eq(%299, %29) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:237:12
   = prim::If(%300) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:237:9
    block0():
      %301 : int = aten::size(%spec.1, %26) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:238:41
      %stft_freqs.1 : Tensor = aten::linspace(%9, %39, %301, %5, %5, %35, %36) # /home/travis/build/pytorch/audio/torchaudio/functional.py:163:18
      %375 : Float(*) = prim::Constant[value=<Tensor>]()
      %315 : Float(*) = aten::div(%375, %33) # /home/travis/build/pytorch/audio/torchaudio/functional.py:170:26
      %316 : Float(*) = aten::pow(%30, %315) # /home/travis/build/pytorch/audio/torchaudio/functional.py:170:21
      %317 : Float(*) = aten::sub(%316, %32, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:170:21
      %f_pts.1 : Float(*) = aten::mul(%317, %31) # <string>:2:10
      %319 : Float(*) = aten::slice(%f_pts.1, %29, %6, %10, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:172:14
      %320 : Float(*) = aten::slice(%f_pts.1, %29, %29, %11, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:172:26
      %f_diff.1 : Float(*) = aten::sub(%319, %320, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:172:14
      %322 : Float(*, *) = aten::unsqueeze(%f_pts.1, %29) # /home/travis/build/pytorch/audio/torchaudio/functional.py:173:14
      %323 : Tensor = aten::unsqueeze(%stft_freqs.1, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:173:35
      %slopes.1 : Tensor = aten::sub(%322, %323, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:173:14
      %376 : int[] = prim::Constant[value=[1]]()
      %z.1 : Double(*) = aten::zeros(%376, %5, %5, %35, %36) # /home/travis/build/pytorch/audio/torchaudio/functional.py:175:9
      %327 : Tensor = aten::slice(%slopes.1, %29, %29, %10, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:176:26
      %328 : Tensor = aten::slice(%327, %6, %29, %12, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:176:26
      %329 : Tensor = aten::mul(%328, %37) # <string>:2:10
      %330 : Float(*) = aten::slice(%f_diff.1, %29, %29, %11, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:176:44
      %down_slopes.1 : Tensor = aten::div(%329, %330) # /home/travis/build/pytorch/audio/torchaudio/functional.py:176:20
      %333 : Tensor = aten::slice(%327, %6, %26, %10, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:177:17
      %334 : Float(*) = aten::slice(%f_diff.1, %29, %6, %10, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:177:33
      %up_slopes.1 : Tensor = aten::div(%333, %334) # /home/travis/build/pytorch/audio/torchaudio/functional.py:177:17
      %336 : Tensor = aten::min(%down_slopes.1, %up_slopes.1) # /home/travis/build/pytorch/audio/torchaudio/functional.py:178:23
      %tmp_fb.1 : Tensor = aten::max(%z.1, %336) # /home/travis/build/pytorch/audio/torchaudio/functional.py:178:10
      %338 : Tensor = prim::GetAttr[name="fb"](%297)
      %339 : int[] = aten::size(%tmp_fb.1) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:240:29
      %340 : Tensor = aten::resize_(%338, %339) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:240:13
      %341 : Tensor = prim::GetAttr[name="fb"](%297)
      %342 : Tensor = aten::copy_(%341, %tmp_fb.1, %25) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:241:13
      -> ()
    block1():
      -> ()
  %343 : Tensor = prim::GetAttr[name="fb"](%297)
  %mel_spect.1 : Tensor = aten::matmul(%spec.1, %343) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:242:18
  %348 : ClassType<SpectrogramToDB> = prim::GetAttr[name="s2db"](%self)
  %349 : float = prim::GetAttr[name="top_db"](%348)
  %350 : Tensor = aten::clamp(%mel_spect.1, %3, %5) # /home/travis/build/pytorch/audio/torchaudio/functional.py:202:40
  %351 : Tensor = aten::log10(%350) # /home/travis/build/pytorch/audio/torchaudio/functional.py:202:28
  %spec_db.1 : Tensor = aten::mul(%351, %2) # <string>:2:10
  %spec_db.3 : Tensor = aten::sub_(%spec_db.1, %9, %6) # /home/travis/build/pytorch/audio/torchaudio/functional.py:203:5
  %355 : bool = aten::__isnot__(%349, %4) # /home/travis/build/pytorch/audio/torchaudio/functional.py:205:8
  %mel_spect.6 : Tensor = prim::If(%355) # /home/travis/build/pytorch/audio/torchaudio/functional.py:205:5
    block0():
      %top_db.5 : float = prim::unchecked_unwrap_optional(%349)
      %358 : Tensor = aten::max(%spec_db.3) # /home/travis/build/pytorch/audio/torchaudio/functional.py:206:46
      %359 : float = prim::Float(%358) # /home/travis/build/pytorch/audio/torchaudio/functional.py:206:40
      %360 : float = aten::sub(%359, %top_db.5) # /home/travis/build/pytorch/audio/torchaudio/functional.py:206:40
      %361 : int = prim::dtype(%spec_db.3)
      %362 : Device = prim::device(%spec_db.3)
      %new_spec_db_max.1 : Tensor = aten::tensor(%360, %361, %362, %25) # /home/travis/build/pytorch/audio/torchaudio/functional.py:206:27
      %spec_db.8 : Tensor = aten::max(%spec_db.3, %new_spec_db_max.1) # /home/travis/build/pytorch/audio/torchaudio/functional.py:207:19
      -> (%spec_db.8)
    block1():
      -> (%spec_db.3)
  %365 : Tensor = prim::GetAttr[name="dct_mat"](%self)
  %mfcc.1 : Tensor = aten::matmul(%mel_spect.6, %365) # /home/travis/build/pytorch/audio/torchaudio/transforms.py:341:16
  return (%mfcc.1)
:
at /home/travis/build/pytorch/audio/torchaudio/functional.py:163:18
        f_min (float): minimum frequency
        f_max (float): maximum frequency
        n_mels (int): number of mel bins
    Outputs:
        Tensor: triangular filter banks (fb matrix)
    """
    # get stft freq bins
    stft_freqs = torch.linspace(f_min, f_max, n_stft)
                 ~~~~~~~~~~~~~~ <--- HERE
    # calculate mel freq bins
    # hertz to mel(f) is 2595. * math.log10(1. + (f / 700.))
    m_min = 0. if f_min == 0 else 2595. * math.log10(1. + (f_min / 700.))
    m_max = 2595. * math.log10(1. + (f_max / 700.))
    m_pts = torch.linspace(m_min, m_max, n_mels + 2)
    # mel to hertz(mel) is 700. * (10**(mel / 2595.) - 1.)
    f_pts = 700. * (10**(m_pts / 2595.) - 1.)
    # calculate the difference between each mel point and each stft freq point in hertz
    f_diff = f_pts[1:] - f_pts[:-1]  # (n_mels + 1)
```

**Comment by jamesr66a** [comment]
Hello @jamarshon,

I believe this patch may fix the issue: https://github.com/pytorch/pytorch/pull/22186. I believe it will be landed soon and built into the nightly release. Could you please let us know if that does not fix the issue?

**Comment by jamarshon** [comment]
Yes it works now. Seems like the patch fixed it.
