### ISSUE TITLE
Linker failed on building source of PyTorch v1.1.0 with ROCm 2.4 on ARM64

### ISSUE THREAD

**Issue by wormwang** [pytorch/pytorch#22187]
## To Reproduce

1. AMD ROCm 2.4
2. PyTorch v1.1.0
3, Ubunut 18.0.4

export NO_CUDA=1
export NO_DISTRIBUTED=1
export NO_MKLDNN=1 
export NO_NNPACK=1
export NO_QNNPACK=1 

USE_ROCM=1 USE_LMDB=1 USE_OPENCV=1 MAX_JOBS=56 python setup.py install --user

Error log

```
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
[ 78%] Linking CXX shared library ../lib/libcaffe2_hip.so
../lib/libprotobuf.a(descriptor.cc.o): In function `std::pair<std::__detail::_Node_iterator<std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*>, false, true>, bool> std::_Hashtable<std::pair<void const*, char const*>, std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*>, std::allocator<std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*> >, std::__detail::_Select1st, google::protobuf::(anonymous namespace)::PointerStringPairEqual, google::protobuf::(anonymous namespace)::PointerStringPairHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*>, true> > > >(std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*>, true> > > const&, std::integral_constant<bool, true>) [clone .isra.1217]':
descriptor.cc:(.text+0x1d8): relocation truncated to fit: R_AARCH64_CALL26 against symbol `strcmp@@GLIBC_2.17' defined in .text section in /lib/aarch64-linux-gnu/libc.so.6
descriptor.cc:(.text+0x23c): relocation truncated to fit: R_AARCH64_CALL26 against symbol `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@@GLIBCXX_3.4.18' defined in .text section in /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so
../lib/libprotobuf.a(descriptor.cc.o): In function `std::pair<std::__detail::_Node_iterator<std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol>, false, true>, bool> std::_Hashtable<std::pair<void const*, char const*>, std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol>, std::allocator<std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol> >, std::__detail::_Select1st, google::protobuf::(anonymous namespace)::PointerStringPairEqual, google::protobuf::(anonymous namespace)::PointerStringPairHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol>, true> > > >(std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<void const*, char const*> const, google::protobuf::Symbol>, true> > > const&, std::integral_constant<bool, true>) [clone .isra.1240]':
descriptor.cc:(.text+0x4a0): relocation truncated to fit: R_AARCH64_CALL26 against symbol `strcmp@@GLIBC_2.17' defined in .text section in /lib/aarch64-linux-gnu/libc.so.6
descriptor.cc:(.text+0x504): relocation truncated to fit: R_AARCH64_CALL26 against symbol `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@@GLIBCXX_3.4.18' defined in .text section in /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so
../lib/libprotobuf.a(descriptor.cc.o): In function `std::pair<std::__detail::_Node_iterator<std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*>, false, true>, bool> std::_Hashtable<std::pair<google::protobuf::Descriptor const*, int>, std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*>, std::allocator<std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*> >, std::__detail::_Select1st, std::equal_to<std::pair<google::protobuf::Descriptor const*, int> >, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::Descriptor const*, int> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*>, true> > > >(std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<google::protobuf::Descriptor const*, int> const, google::protobuf::FieldDescriptor const*>, true> > > const&, std::integral_constant<bool, true>) [clone .isra.1253]':
descriptor.cc:(.text+0x798): relocation truncated to fit: R_AARCH64_CALL26 against symbol `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@@GLIBCXX_3.4.18' defined in .text section in /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so
../lib/libprotobuf.a(descriptor.cc.o): In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .isra.625]':
descriptor.cc:(.text+0xa24): relocation truncated to fit: R_AARCH64_CALL26 against symbol `std::__throw_logic_error(char const*)@@GLIBCXX_3.4' defined in .text section in /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so
../lib/libprotobuf.a(descriptor.cc.o): In function `std::_Hashtable<std::pair<void const*, char const*>, std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*>, std::allocator<std::pair<std::pair<void const*, char const*> const, google::protobuf::FieldDescriptor const*> >, std::__detail::_Select1st, google::protobuf::(anonymous namespace)::PointerStringPairEqual, google::protobuf::(anonymous namespace)::PointerStringPairHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::pair<void const*, char const*> const&)':
descriptor.cc:(.text+0xb6c): relocation truncated to fit: R_AARCH64_CALL26 against symbol `strcmp@@GLIBC_2.17' defined in .text section in /lib/aarch64-linux-gnu/libc.so.6
../lib/libprotobuf.a(descriptor.cc.o): In function `std::pair<std::__detail::_Node_iterator<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, false, true>, bool> std::_Hashtable<std::pair<google::protobuf::EnumDescriptor const*, int>, std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, std::allocator<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> >, std::__detail::_Select1st, std::equal_to<std::pair<google::protobuf::EnumDescriptor const*, int> >, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, true> > > >(std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, true> > > const&, std::integral_constant<bool, true>) [clone .isra.1224]':
descriptor.cc:(.text+0xec8): relocation truncated to fit: R_AARCH64_CALL26 against symbol `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@@GLIBCXX_3.4.18' defined in .text section in /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so
../lib/libprotobuf.a(descriptor.cc.o): In function `google::protobuf::(anonymous namespace)::OptionsToInterpret::OptionsToInterpret(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<int, std::allocator<int> >&, google::protobuf::Message const*, google::protobuf::Message*)':
descriptor.cc:(.text+0x1130): relocation truncated to fit: R_AARCH64_CALL26 against symbol `memmove@@GLIBC_2.17' defined in .text section in /lib/aarch64-linux-gnu/libc.so.6
../lib/libprotobuf.a(descriptor.cc.o): In function `google::protobuf::(anonymous namespace)::ToCamelCase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
descriptor.cc:(.text+0x11d4): relocation truncated to fit: R_AARCH64_CALL26 against symbol `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@@GLIBCXX_3.4.21' defined in .text section in /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so
descriptor.cc:(.text+0x1300): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2_hip.dir/build.make:5508: recipe for target 'lib/libcaffe2_hip.so' failed
make[2]: *** [lib/libcaffe2_hip.so] Error 1
CMakeFiles/Makefile2:5024: recipe for target 'caffe2/CMakeFiles/caffe2_hip.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_hip.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 725, in <module>
    build_deps()
  File "setup.py", line 285, in build_deps
    build_dir='build')
  File "/home/motech/pytorch-main/pytorch/tools/build_pytorch_libs.py", line 281, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '56', 'install']' returned non-zero exit status 2
```

**Comment by yf225** [comment]
@bddppq Would you like to take a look at this issue?

**Comment by wormwang** [comment]
if u need, we open our testing ARM64+ROCm server for u. pls email me wormwang@yahoo.com

**Comment by jeffdaily** [comment]
This issue is over a year old.  Please open if error is still observed on newer PyTorch + ROCm versions.
