### ISSUE TITLE
CUDA OOM for tiny Variable broadcast-add 

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#2225]
Reproduced this on two new versions of pytorch, but it doesn't happen in >1month old version. So probably some regression caused by broadcasting code.

```
import torch
import torch.nn as nn
from torch.autograd import Variable

a = Variable(torch.cuda.FloatTensor(500000,1,1))
b = Variable(torch.cuda.FloatTensor(500000,1))
a+b
```
leads to 

```
THCudaCheck FAIL file=/home/gchanan/local/pytorch8d/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    a+b
  File "/data/users/gchanan/pytorch8d/torch/autograd/variable.py", line 790, in __add__
    return self.add(other)
  File "/data/users/gchanan/pytorch8d/torch/autograd/variable.py", line 296, in add
    return self._add(other, False)
  File "/data/users/gchanan/pytorch8d/torch/autograd/variable.py", line 290, in _add
    return Add.apply(self, other, inplace)
  File "/data/users/gchanan/pytorch8d/torch/autograd/_functions/basic_ops.py", line 17, in forward
    return a.add(b)
RuntimeError: cuda runtime error (2) : out of memory at /home/gchanan/local/pytorch8d/torch/lib/THC/generic/THCStorage.cu:66
```

**Comment by apaszke** [comment]
It makes sense. Broadcasting will make the output be of size (500000, 500000, 1) because it aligns dims to the left not to the right:
```
500000         1    1
          500000    1
---------------------
500000    500000    1
```
