### ISSUE TITLE
Build failure with setup.py

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#22406]
Hi. I was building pytorch with setup.py and after
```
[100%] Built target torch_python
Install the project...
-- Install configuration: "Release"
```
And some output about copying files I got the following error:
```
running build_ext
-- Building with NumPy bindings
Traceback (most recent call last):
  File "setup.py", line 856, in <module>
    'python/serialized_test/data/operator_test/*.zip',
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 378, in run
    report('-- Detected cuDNN at ' + CUDNN_LIBRARY + ', ' + CUDNN_INCLUDE_DIR)
TypeError: can only concatenate str (not "NoneType") to str
```
I did ```print(CUDNN_LIBRARY, CUDNN_INCLUDE_DIR)``` and the output is ```None None``` but cudnn was found:
```
-- Found CUDNN: /usr/include  
-- Found cuDNN: v7.6.1  (include: /usr/include, library: /usr/lib/libcudnn.so)
``` 
I always build pytorch with just cmake and I wanted to use setup.py instead.
os: arch linux
cudnn version: 7.6.1.34
cuda version: 10.1.168

**Comment by peterjc123** [comment]
This is because they are calculated from different places, The first one is from the python side https://github.com/pytorch/pytorch/blob/master/tools/setup_helpers/cudnn.py and the other one is from cmake. Looks like we should unify this, by either moving the section into cmake or disabling the auto-detection code in cmake. cc @soumith

**Comment by dollysapra** [comment]
I got the same error. Is there something I can try to get my pytorch installation completed now?

Thanks,
Dolly

**Comment by peterjc123** [comment]
The workground is to set them explicitly through environment variables.
```bash
export CUDNN_INCLUDE_DIR="/usr/include"
export CUDNN_LIBRARY="/usr/lib/libcudnn.so"
```

**Comment by dollysapra** [comment]
Yes, I figured that :) Thanks! it is working for me now.
