### ISSUE TITLE
i have some problem about rsub().

### ISSUE THREAD

**Issue by ChrisHRZ** [pytorch/pytorch#22448]
I am trying to run a CNN name layoutNet. But there is some bug. 
The error is like this:
`Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main()
  File "main.py", line 70, in main
    trainLoss = trainer.train(trainLoader, epoch)
  File "/home/auto/workspace/wireframe/linepx/models/stackedHGB-train.py", line 39, in train
    for i, (inputData, line, imgids) in enumerate(trainLoader):
  File "/home/auto/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/auto/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/auto/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/auto/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/auto/workspace/wireframe/linepx/datasets/indoor.py", line 21, in __getitem__
    image = self.preprocess(image)
  File "/home/auto/workspace/wireframe/linepx/datasets/indoor.py", line 46, in preprocess
    im = t.normalize(im, mean, std)
  File "/home/auto/workspace/wireframe/linepx/datasets/transforms.py", line 29, in normalize
    ipt[:][:][0] = (ipt[:][:][0] - mean[0]) / std[0]
  File "/home/auto/.local/lib/python3.6/site-packages/torch/tensor.py", line 371, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
TypeError: rsub() received an invalid combination of arguments - got (Tensor, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, Number alpha)
 * (Tensor input, Number other, Number alpha)
`

**Comment by SsnL** [comment]
> got (Tensor, numpy.ndarray), but expected one of:

Your normalization stats are of the wrong type.

**Comment by ronaldpan** [comment]
change mean and std to np.array

**Comment by sachinkaundal** [comment]
i am getting same error, please help me out to solve this issue. Thanks in advance
