### ISSUE TITLE
SyncBatchNorm test mode

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#22538]
## 🐛 Bug

During evaluation in a none-distributed environment, SyncBatchNorm fails to revert back to BatchNorm; furthermore, there is no functionality provided by PyTorch to convert SyncBatchNorm back to BatchNorm.

```
Traceback (most recent call last):
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 455, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```

## Expected behavior

A model training in a distributed environment can be evaluated outside of a distributed environment.

**Comment by mrshenli** [comment]
Hi @PetrochukM, could you please share some more context of your use case? Why using `SyncBatchNorm` instead of `BatchNormxd` in a non-distributed environment?

**Comment by PetrochukM** [comment]
This is a local test of the model on a CPU after it has been trained.

**Comment by mrshenli** [comment]
The following should work. 

```python
>>> import torch.distributed as dist
>>> dist.init_process_group('gloo', init_method='file:///tmp/somefile', rank=0, world_size=1)
```

**Comment by PetrochukM** [comment]
Great. Thank you! :)

Would it be possible to remove this requirement? What do you think? This seems like unnecessary boilerplate for evaluation mode.

One way to do so would be to have a function that is the opposite of `convert_sync_batchnorm`.

**Comment by ezyang** [comment]
In triage, we decided that this relaxation seemed like a reasonable to do.

(Unrelated to this issue: @fmassa was wondering if there wasn't a reason why BatchNorm didn't just take a sync argument. @mrshenli will investigate.)

**Comment by ppwwyyxx** [comment]
Related to this, it is also unnecessary to require the use of DDP in testing mode. i.e., 
https://github.com/pytorch/pytorch/blob/d3f6d5885d68d47d38a475d4fc9cf1611c91920c/torch/nn/modules/batchnorm.py#L429-L430
should not happen in testing mode.
