### ISSUE TITLE
Pytorch compilation is terminated on Gentoo for security reason

### ISSUE THREAD

**Issue by seewpx** [pytorch/pytorch#22567]
## ❓ Questions and Help
```
[937/2456] Generating ../aten/src/ATen/CPUType.cpp, ../aten/src/ATen/CPUType.h, ../aten/src/ATen/Declarations.yaml, ../aten/src/ATen/ExtensionBackendRegistration.h, ../aten/src/ATen/Functions.h, ../aten/src/ATen/LegacyTHFunctionsCPU.cpp, ../aten/src/ATen/LegacyTHFunctionsCPU.h, ../aten/src/ATen/MSNPUType.cpp, ../aten/src/ATen/MSNPUType.h, ../aten/src/ATen/MkldnnCPUType.cpp, ../aten/src/ATen/MkldnnCPUType.h, ../aten/src/ATen/NativeFunctions.h, ../aten/src/ATen/QuantizedCPUType.cpp, ../aten/src/ATen/QuantizedCPUType.h, ../aten/src/ATen/RegistrationDeclarations.h, ../aten/src/ATen/SparseCPUType.cpp, ../aten/src/ATen/SparseCPUType.h, ../aten/src/ATen/TypeDefault.cpp, ../aten/src/ATen/TypeDefault.h, ../aten/src/ATen/XLAType.cpp, ../aten/src/ATen/XLAType.h, ../aten/src/ATen/CUDAType.cpp, ../aten/src/ATen/CUDAType.h, ../aten/src/ATen/LegacyTHFunctionsCUDA.cpp, ../aten/src/ATen/LegacyTHFunctionsCUDA.h, ../aten/src/ATen/SparseCUDAType.cpp, ../aten/src/ATen/SparseCUDAType.h
FAILED: aten/src/ATen/CPUType.cpp aten/src/ATen/CPUType.h aten/src/ATen/Declarations.yaml aten/src/ATen/ExtensionBackendRegistration.h aten/src/ATen/Functions.h aten/src/ATen/LegacyTHFunctionsCPU.cpp aten/src/ATen/LegacyTHFunctionsCPU.h aten/src/ATen/MSNPUType.cpp aten/src/ATen/MSNPUType.h aten/src/ATen/MkldnnCPUType.cpp aten/src/ATen/MkldnnCPUType.h aten/src/ATen/NativeFunctions.h aten/src/ATen/QuantizedCPUType.cpp aten/src/ATen/QuantizedCPUType.h aten/src/ATen/RegistrationDeclarations.h aten/src/ATen/SparseCPUType.cpp aten/src/ATen/SparseCPUType.h aten/src/ATen/TypeDefault.cpp aten/src/ATen/TypeDefault.h aten/src/ATen/XLAType.cpp aten/src/ATen/XLAType.h aten/src/ATen/CUDAType.cpp aten/src/ATen/CUDAType.h aten/src/ATen/LegacyTHFunctionsCUDA.cpp aten/src/ATen/LegacyTHFunctionsCUDA.h aten/src/ATen/SparseCUDAType.cpp aten/src/ATen/SparseCUDAType.h 
cd /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/build/caffe2 && /usr/bin/python3.6 /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/gen.py --source-path /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen --install_dir /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/build/aten/src/ATen /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/Declarations.cwrap /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/THNN/generic/THNN.h /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/THCUNN/generic/THCUNN.h /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/nn.yaml /var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/native/native_functions.yaml
Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/gen.py", line 494, in <module>
    generate_outputs()
  File "/var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/gen.py", line 425, in generate_outputs
    for file in cwrap_files
  File "/var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/cmake/../aten/src/ATen/gen.py", line 426, in <listcomp>
    for d in cwrap_parser.parse(file)]
  File "/var/tmp/portage/sci-libs/pytorch-9999/work/pytorch-9999/aten/src/ATen/cwrap_parser.py", line 18, in parse
    declaration = yaml.load('\n'.join(declaration_lines))
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 109, in load
    raise RuntimeError("Unsafe load() call disabled by Gentoo. See bug #659348")
RuntimeError: Unsafe load() call disabled by Gentoo. See bug #659348
```
The pyyaml's load() call Pytorch use is considered unsafe in Gentoo. Any load() call will raise error. 
What should I do to avoid this error?

##This is the Gentoo develop team's disccusion
https://bugs.gentoo.org/659348

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by seewpx** [comment]
```
diff --git a/aten/src/ATen/cwrap_parser.py b/aten/src/ATen/cwrap_parser.py
index f020dd030..32b4957c9 100644
--- a/aten/src/ATen/cwrap_parser.py
+++ b/aten/src/ATen/cwrap_parser.py
@@ -15,7 +15,7 @@ def parse(filename):
                 in_declaration = True
             elif line == ']]':
                 in_declaration = False
-                declaration = yaml.load('\n'.join(declaration_lines))
+                declaration = yaml.safe_load('\n'.join(declaration_lines))
                 declarations.append(declaration)
             elif in_declaration:
                 declaration_lines.append(line)
diff --git a/tools/cwrap/cwrap.py b/tools/cwrap/cwrap.py
index 5954fb817..c68e8f4d8 100644
--- a/tools/cwrap/cwrap.py
+++ b/tools/cwrap/cwrap.py
@@ -88,7 +88,7 @@ class cwrap(object):
                 in_declaration = True
             elif line == ']]':
                 in_declaration = False
-                declaration = yaml.load('\n'.join(declaration_lines))
+                declaration = yaml.safe_load('\n'.join(declaration_lines))
                 cwrap_common.set_declaration_defaults(declaration)
 
                 # Pass declaration in a list - maybe some plugins want to add
```

**Comment by vishwakftw** [comment]
Based on the bug report, I think the issue would be resolved if you update to a more recent version of PyYAML.

**Comment by seewpx** [comment]
@vishwakftw Yet a newest version 5.1.1 of PyYAML compared version 5.1 of mine have not any change at this place. But I have patch the code to avoid above error. Thank you!
