### ISSUE TITLE
[dataloader] Mysterious error when using spawn start_method 

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#22585]
Unfortunately, I couldn't find the root cause for the moment. The error disappears when I use the fork start_method. I also can't find what `deco` it refers to.

It seems that some function decorator / wrapping is happening badly, but I can't find what's to blame.

The error comes from `process.start()` impl for the spawn start method.
```
Traceback (most recent call last):
  File "train.py", line 968, in <module>
    train(start_epoch, start_iter, start_checkpoint)
  File "train.py", line 688, in train
    for i, data in enumerate(train_loader, start=from_iter):
  File "/miniconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 194, in __iter__
    return _DataLoaderIter(self)
  File "/miniconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 470, in __init__
    w.start()
  File "/miniconda/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/miniconda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/miniconda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/miniconda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/miniconda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/miniconda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/miniconda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'deco.<locals>.wrapped'
```

PyTorch version: 1.2.0.dev20190607

**Comment by vadimkantorov** [comment]
It is indeed the dataset object that can't be pickled with `ForkingPickler(file, protocol).dump(obj)` or with `pickle.dump(train_loader.dataset, open('/dev/null', 'wb'))`, but it's not a problem for start_method = 'fork'

**Comment by SsnL** [comment]
Don't know what is going on, but I'll provide a `start_method=` kwarg to `DataLoader` that may help resolving this.

**Comment by vadimkantorov** [comment]
It seems that start_method = 'fork' avoids doing pickling. Can this be true?

**Comment by vadimkantorov** [comment]
On actionable side, maybe the data loader could wrap `process.start` in try-catch to raise a more legible exception for the user (suggesting that dataset object or the collate function is not picklable).
