### ISSUE TITLE
Batched Triu And Tril Incorrect for Some Inputs

### ISSUE THREAD

**Issue by angusturner** [pytorch/pytorch#22581]
## 🐛 Bug

When passing a specific 4D tensor to `triu` or `tril`, the GPU implementation produces non-deterministic results. The CPU implementation produces `nan` values.

## To Reproduce

This is the minimum reproducible example I could come up with:

```python
x = torch.randn(1, 4, 4, 4)
x = x.transpose(0, 1)
for i in range(10):
    # note: results are often different on each run
    # or on CPU, outputs `nan`
    print(x.triu().sum())
```

Note that the issue does not seem to occur when:
- the transpose is omitted
- if `x.size(0) > 1`
- if the tensor has more or fewer dimensions

## Expected behavior

Values should be deterministic and not produces `NaN`

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 418.67
cuDNN version: 7501

Versions of relevant libraries:
[pip] numpy==1.16.1
[pip] torch==1.1.0
[pip] torchfile==0.1.0
[conda] torch                     1.1.0                     <pip>
[conda] torchfile                 0.1.0                     <pip>

**Comment by vishwakftw** [comment]
Hi @angusturner, thanks for raising the issue.

I am unable to reproduce the errors that you have encountered on the master branch. Could you please upgrade to a nightly build and see if the error persists? Thanks!

**Comment by zou3519** [comment]
@vishwakftw I can reproduce this on master, fwiw

**Comment by vishwakftw** [comment]
Oh, that’s weird. I’ll rebuild and see if the error persists. Sorry about the misinformation.

Could you please let know if the CUDA issue is there? A minor refactor was done to the CUDA kernel after 1.1.0, hence the question.

**Comment by zou3519** [comment]
I'm on `1.2.0a0+6947e19`, which is from 11 days ago

**Comment by vishwakftw** [comment]
I couldn’t reproduce this with `1.2.0a0+94bd5dd` (current master on my fork).

**Comment by zou3519** [comment]
I just checked out master and am still gettting this. After building with ASAN, I get the following stack trace:
```
In [1]: import torch                                                                         [283/27687]

In [2]: x = torch.randn(1, 4, 4, 4)
   ...: x = x.transpose(0, 1)
   ...: for i in range(10):
   ...:     # note: results are often different on each run
   ...:     # or on CPU, outputs `nan`
   ...:     print(x.triu().sum())
   ...:
   ...:
=================================================================
==1455515==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6120000041c0 at pc 0x7f5e20fe62a0
bp 0x7fffe95e1e10 sp 0x7fffe95e1e08
READ of size 4 at 0x6120000041c0 thread T0
SCARINESS: 17 (4-byte-read-heap-buffer-overflow)
    #0 0x7f5e20fe629f in void at::native::apply_triu_tril_single<float, true>(float*, float*, bool, long
, long, long, long, long, long, long)::'lambda'(long, long)::operator()(long, long) const caffe2/aten/sr
c/ATen/native/BatchLinearAlgebra.cpp:504
    #1 0x7f5e20fe5071 in void at::parallel_for<void at::native::apply_triu_tril_single<float, true>(floa
t*, float*, bool, long, long, long, long, long, long, long)::'lambda'(long, long)>(long, long, long, flo
at const&) caffe2/aten/src/ATen/ParallelOpenMP.h:36
    #2 0x7f5e20fe4719 in void at::native::apply_triu_tril_single<float, true>(float*, float*, bool, long
, long, long, long, long, long, long) caffe2/aten/src/ATen/native/BatchLinearAlgebra.cpp:497
    #3 0x7f5e20fe3fc0 in void at::native::apply_triu_tril<float, true>(at::Tensor&, at::Tensor const&, b
ool, long)::'lambda'(long, long)::operator()(long, long) const caffe2/aten/src/ATen/native/BatchLinearAl
gebra.cpp:551
    #4 0x7f5e20fe32b1 in void at::parallel_for<void at::native::apply_triu_tril<float, true>(at::Tensor&
, at::Tensor const&, bool, long)::'lambda'(long, long)>(long, long, long, void at::native::apply_triu_tr
il<float, true>(at::Tensor&, at::Tensor const&, bool, long)::'lambda'(long, long) const&) caffe2/aten/sr
c/ATen/ParallelOpenMP.h:36
    #5 0x7f5e20fe2924 in void at::native::apply_triu_tril<float, true>(at::Tensor&, at::Tensor const&, b
ool, long) caffe2/aten/src/ATen/native/BatchLinearAlgebra.cpp:547
    #6 0x7f5e20ff4562 in at::native::triu_cpu_out(at::Tensor&, at::Tensor const&, long)::$_8::operator()
() const::'lambda2'()::operator()() const caffe2/aten/src/ATen/native/BatchLinearAlgebra.cpp:620
    #7 0x7f5e20f8fc45 in at::native::triu_cpu_out(at::Tensor&, at::Tensor const&, long)::$_8::operator()
() const caffe2/aten/src/ATen/native/BatchLinearAlgebra.cpp:620
    #8 0x7f5e20f8efda in at::native::triu_cpu_out(at::Tensor&, at::Tensor const&, long) caffe2/aten/src/
ATen/native/BatchLinearAlgebra.cpp:620
    #9 0x7f5e211340ba in at::CPUType::triu_out(at::Tensor&, at::Tensor const&, long) buck-out/dev/gen/ca
ffe2/aten/gen_aten=CPUType.cpp/CPUType.cpp:2282
    #10 0x7f5e20f8ca38 in at::triu_out(at::Tensor&, at::Tensor const&, long) buck-out/dev/gen/caffe2/ate
n/generated-aten-headers-cpu#header-mode-symlink-tree-with-header-map,headers/ATen/Functions.h:3885
    #11 0x7f5e20f8c837 in at::native::triu(at::Tensor const&, long) caffe2/aten/src/ATen/native/BatchLin
earAlgebra.cpp:594
    #12 0x7f5e25043754 in at::TypeDefault::triu(at::Tensor const&, long) buck-out/dev/gen/caffe2/aten/ge
n_aten=TypeDefault.cpp/TypeDefault.cpp:4086
    #13 0x7f5e6791a49f in at::triu(at::Tensor const&, long) buck-out/dev/gen/caffe2/aten/generated-aten-
headers-cpu#header-mode-symlink-tree-with-header-map,headers/ATen/Functions.h:3889
    #14 0x7f5e678ba278 in torch::autograd::VariableType::triu(at::Tensor const&, long)::$_98::operator()
() const buck-out/dev/gen/caffe2/generate-code=VariableType_2.cpp/VariableType_2.cpp:11607
    #15 0x7f5e678b91ac in torch::autograd::VariableType::triu(at::Tensor const&, long) buck-out/dev/gen/
caffe2/generate-code=VariableType_2.cpp/VariableType_2.cpp:11605
    #16 0x7f5e6d2731cb in at::Tensor::triu(long) const caffe2/aten/src/ATen/core/TensorMethods.h:1471
    #17 0x7f5e6d5e47a8 in torch::autograd::dispatch_triu(at::Tensor&, long) buck-out/dev/gen/caffe2/gene
```

**Comment by vishwakftw** [comment]
Thank you @zou3519. I’ll check the code and get back to you by next afternoon.

**Comment by vishwakftw** [comment]
I'm able to reproduce the issue on CPU. Working on fixing it.
