### ISSUE TITLE
THCudaCheck FAIL after multiplication of big float64 matrices and sinchronizing

### ISSUE THREAD

**Issue by blednotik** [pytorch/pytorch#22593]
## To Reproduce

```
import numpy as np, torch, time, math, os, sys, cv2
a = torch.randn(10000, 10000)
a1 = a.to(dtype=torch.float64, device='cuda')

t=time.time(); b=torch.matmul(a1,a1); torch.cuda.synchronize(); time.time()-t
```

consistently produces THCudaCheck FAIL:

```
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=211 error=4 : unspecified launch failure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mlearning\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 365, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: cuda runtime error (4) : unspecified launch failure at ..\torch\csrc\cuda\Module.cpp:211
```

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 416.34
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] numpydoc==0.9.1
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.0.2            py37he774522_0
[conda] mkl_fft                   1.0.12           py37h14836fe_0
[conda] mkl_random                1.0.2            py37h343c172_0
[conda] pytorch                   1.1.0           py3.7_cuda100_cudnn7_1    pytorch
[conda] torchvision               0.3.0              py37_cu100_1    pytorch

## Additional context

Small matrices do not produce the error, it starts with about 7000*7000 size.

`torch.float32` does not produce the error, even at 15000*15000.

Without synchronize, there is no error.

After the error is produced, other calls to cuda may or may not produce errors.

**Comment by peterjc123** [comment]
I cannot reproduce this. And below is my env:
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Pro
GCC version: (Rev2, Built by MSYS2 project) 7.1.0
CMake version: version 3.14.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 430.86
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.1
[pip] pytorch-sphinx-theme==0.0.24
[pip] torch==1.1.0
[pip] torchfile==0.1.0
[pip] torchnet==0.0.1
[pip] torchtext==0.2.1
[pip] warpctc-pytorch==0.1
[conda] Could not collect
```

**Comment by blednotik** [comment]
I have CUDA 10, maybe that is the difference?

**Comment by peterjc123** [comment]
Maybe. would you please try whether downgrading CUDA helps?

**Comment by cristianPanaite** [comment]
Hello @blednotik,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get this error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
