### ISSUE TITLE
test_broadcast_ops intermittently segfaults

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#22698]
Pattern: https://circle.pytorch.org/pattern-details.html?pattern_id=83

```
Jul 06 09:41:22 test_broadcast_ops (__main__.ProcessGroupNCCLTest) ... Traceback (most recent call last):
Jul 06 09:41:22   File "test/run_test.py", line 434, in <module>
Jul 06 09:41:22     main()
Jul 06 09:41:22   File "test/run_test.py", line 426, in main
Jul 06 09:41:22     raise RuntimeError(message)
Jul 06 09:41:22 RuntimeError: test_c10d failed! Received signal: SIGSEGV
Jul 06 09:41:22 + cleanup
```

Sample

https://circleci.com/gh/pytorch/pytorch/2151019

cc @pietern

**Comment by ezyang** [comment]
This flakiness seems relatively low occurrence; no occurrences in a six day period.

**Comment by pietern** [comment]
This hasn't occurred since. Closing the issue.
