### ISSUE TITLE
Build Pytorch/Libtorch with TBB support is failing

### ISSUE THREAD

**Issue by abonnet** [pytorch/pytorch#22780]
## 🐛 Bug

Build Pytorch/Libtorch with TBB support is failing

## To Reproduce

1. Set environment variables  to use TBB:
```
export USE_CUDA=0
export PARALLEL_BACKEND=NATIVE
export USE_OPENMP=0 
export USE_TBB=1 
export MKL_TBB=1
export BLAS=MKL 
export USE_MKLDNN=1 
export MKLDNN_THREADING=TBB 
export BUILD_BINARY=1
export USE_EIGEN_THREADPOOL=1
```
2. Build: `python setup.py build`
```
...
-- ******** Summary ********
-- General:
--   CMake version         : 3.11.1
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 4.8.4
--   BLAS                  : MKL
--   CXX flags             :   -Wno-deprecated -fvisibility-inlines-hidden -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_NAMESPACE=onnx_torch;USE_GCC_ATOMICS=1;MKLDNN_THR=MKLDNN_THR_TBB;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python2.7/dist-packages
--   CMAKE_INSTALL_PREFIX  : /torch_build/pytorch/torch
-- 
--   TORCH_VERSION         : 1.2.0
--   CAFFE2_VERSION        : 1.2.0
--   BUILD_CAFFE2_MOBILE   : ON
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : True
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 2.7.6
--     Python executable   : /usr/bin/python
--     Pythonlibs version  : 2.7.6
--     Python library      : /usr/lib/libpython2.7.so.1.0
--     Python includes     : /usr/include/python2.7
--     Python site-packages: lib/python2.7/dist-packages
--   BUILD_CAFFE2_OPS      : True
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   INTERN_BUILD_MOBILE   : 
--   USE_ASAN              : False
--   USE_CUDA              : False
--   USE_ROCM              : False
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : False
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : False
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : False
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_NCCL              : False
--   USE_NNPACK            : True
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : False
--   USE_OPENMP            : False
--   USE_TBB               : True
--   USE_PROF              : OFF
--   USE_QNNPACK           : True
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : True
--     USE_MPI             : OFF
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   NAMEDTENSOR_ENABLED   : False
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fp16;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring incomplete, errors occurred!
See also "/torch_build/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/torch_build/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 752, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    build_dir='build')
  File "/torch_build/pytorch/tools/build_pytorch_libs.py", line 67, in build_caffe2
    rerun_cmake)
  File "/torch_build/pytorch/tools/setup_helpers/cmake.py", line 272, in generate
    self.run(args, env=my_env)
  File "/torch_build/pytorch/tools/setup_helpers/cmake.py", line 100, in run
    check_call(command, cwd=self._build_dir, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBLAS=MKL', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=True', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS= ', '-DCMAKE_C_FLAGS= ', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=/torch_build/pytorch/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python2.7/dist-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNAMEDTENSOR_ENABLED=False', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=/usr/lib/python2.7/dist-packages/numpy/core/include', '-DONNX_ML=True', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DPYTHON_INCLUDE_DIR=/usr/include/python2.7', '-DPYTHON_LIBRARY=/usr/lib/libpython2.7.so.1.0', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.2.0a0+1ffa9d3', '-DUSE_ASAN=False', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=True', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DUSE_OPENMP=False', '-DUSE_TBB=True', '-DINTEL_MKL_TBB=True', '-DMKLDNN_THREADING=TBB', '-DPARALLEL_BACKEND=NATIVE', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON', '/torch_build/pytorch']' returned non-zero exit status 1
```

## Expected behavior

It builds successfully. Building with OpenMP is working in the same environment.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 14.04.6 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 3.11.1

Python version: 2.7
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21

Versions of relevant libraries:
[pip] numpy==1.8.2
[conda] Could not collect
## Additional context

Attached CMakeOutput and CMakeError files.
[CMakeError.log](https://github.com/pytorch/pytorch/files/3384330/CMakeError.log)
[CMakeOutput.log](https://github.com/pytorch/pytorch/files/3384331/CMakeOutput.log)

**Comment by soumith** [comment]
cc: @ilia-cher

**Comment by ilia-cher** [comment]
@abonnet, a few comments/questions:

1. The build options interface for parallelism is not stabilized yet, in the trunk we changed the MKL threading option name to MKL_THREADING to mimic MKLDNN_THREADING, please use MKL_THREADING=TBB

2. I wonder why is PARALLEL_BACKEND=NATIVE? if you'd want to have a TBB build, then I'd recommend PARALLEL_BACKEND=NATIVE_TBB. Please note that we'll simplify this further and will post about available build options

3. From CMakeError.log I see that the build error is from linker when performing C tests, e.g.
```
Performing C SOURCE FILE Test BLAS_USE_CBLAS_DOT failed with the following output:
Change Dir: /torch_build/pytorch/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_f930b"
[1/2] Building C object CMakeFiles/cmTC_f930b.dir/src.c.o
[2/2] Linking C executable cmTC_f930b
FAILED: : && /usr/bin/cc -DBLAS_USE_CBLAS_DOT  -rdynamic CMakeFiles/cmTC_f930b.dir/src.c.o  -o cmTC_f930b -L/opt/intel/lib -Wl,-rpath,/opt/intel/lib -lmkl_intel_lp64 -lmkl_tbb_thread -lmkl_core -lpthread /usr/lib/x86_64-linux-gnu/libm.so /usr/lib/x86_64-linux-gnu/libdl.so && :
/opt/intel/lib/libmkl_tbb_thread.so: undefined reference to `tbb::task_group_context::cancel_group_execution()'
```

I haven't reproed this, but it seems the place that breaks is this: https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindBLAS.cmake#L243-L294
where we set "-lmkl_intel_lp64 -lmkl_tbb_thread -lmkl_core" but don't set "-ltbb"

One minor issue here is that we build TBB from source and we don't have it built yet when we do this C test check; I guess one solution would be to add -ltbb and use pre-installed TBB when linking these tests during cmake configuration time

**Comment by abonnet** [comment]
@ilia-cher Yes, I tried both for PARALLEL_BACKEND but the goal is to get a TBB build. Switching the flag MKL_THREADING is not solving the problem. Do you have a commit known to be working from master? I tried multiple commits but no luck.

**Comment by ilia-cher** [comment]
I've just tried these building settings on the latest trunk and it built successfully.
Is there any chance you could share the full log? e.g.
`USE_CUDA=0 PARALLEL_BACKEND=NATIVE USE_OPENMP=0  USE_TBB=1  MKL_THREADING=TBB BLAS=MKL  USE_MKLDNN=1  MKLDNN_THREADING=TBB  BUILD_BINARY=1 USE_EIGEN_THREADPOOL=1 python setup.py develop --cmake 2>&1 | tee ~/output.txt`

**Comment by abonnet** [comment]
I ran your command, still an issue. I have attached the full output.
[output.txt](https://github.com/pytorch/pytorch/files/3407750/output.txt)

**Comment by abonnet** [comment]
I ran your command with latest trunk and still got an issue. Attached is the output file
[output.txt](https://github.com/pytorch/pytorch/files/3407759/output.txt)

**Comment by ilia-cher** [comment]
Looks like the actual error you're experiencing is:
```
CMake Error at cmake/Dependencies.cmake:92 (install):
  install TARGETS given target "tbb" which does not exist in this directory.
```

will investigate

**Comment by abonnet** [comment]
Yes, that's the only suspicious output I can think of

**Comment by ilia-cher** [comment]
I managed to reproduce the issue by downgrading cmake to 3.11.0, originally I used 3.13.3 and it worked with it

**Comment by ilia-cher** [comment]
From https://cmake.org/cmake/help/v3.13/release/3.13.html:
"The install(TARGETS) command learned to install targets created outside the current directory."
Possibly related, will check further

**Comment by abonnet** [comment]
Ok, I can upgrade to 3.13.3.

**Comment by ilia-cher** [comment]
I'll update this cmake rule to make it compatible with older cmake versions

**Comment by abonnet** [comment]
Confirmed that upgrading to Cmake 3.13.3 is fixing the issue! Thanks a lot @ilia-cher
