### ISSUE TITLE
Getting cuda runtime error (48) with Jetson TX2 when running simple program

### ISSUE THREAD

**Issue by emoyers** [pytorch/pytorch#22785]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

When running in Jetson TX2 this simple code:
```python
import torch

dev = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
input1 = torch.rand(20, 20, 3).to(dev)
print(input1)
```
I'm getting this output:
```
THCudaCheck FAIL file=/home/nvidia/pytorch/aten/src/THC/generic/THCTensorMath.cu line=238 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "test_cuda_working.py", line 8, in <module>
    print(input1)
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 63, in __repr__
    return torch._tensor_str._str(self).encode(
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 286, in _str
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 204, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 234, in get_summarized_data
    start = [get_summarized_data(self[i]).reshape(-1) for i in range(0, PRINT_OPTS.edgeitems)]
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 237, in get_summarized_data
    return torch.cat((start + end))
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /home/nvidia/pytorch/aten/src/THC/generic/THCTensorMath.cu:238
```

If I change the code to:
```python
import torch

dev = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
input1 = torch.rand(18, 18, 3).to(dev)
print(input1)
```

It runs perfectly using cuda. Does anyone have an idea why this is happening?

**Comment by soumith** [comment]
how did you install pytorch on the jetson platform?

**Comment by emoyers** [comment]
I used this commands 
```
sudo apt-get install python-pip
pip install torch-1.0.0a0+8601b33-cp27-cp27mu-linux_aarch64.whl
pip install numpy
```

Following this [link](https://devtalk.nvidia.com/default/topic/1041716/pytorch-install-problem/).
