### ISSUE TITLE
Python build script error

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#22840]
## 🐛 Bug

```
 /media/jintian/netac/ai/libs/pytorch   master  python3 tools/build_pytorch_libs.py                                                     [23:27:29]
Traceback (most recent call last):
  File "tools/build_pytorch_libs.py", line 6, in <module>
    from .setup_helpers import escape_path
ModuleNotFoundError: No module named '__main__.setup_helpers'; '__main__' is not a package
 ✘  /media/jintian/netac/ai/libs/pytorch   master  cd tools                                                                            [23:27:39]
 /media/jintian/netac/ai/libs/pytorch/tools   master  python3 build_pytorch_libs.py                                                     [23:27:52]
Traceback (most recent call last):
  File "build_pytorch_libs.py", line 6, in <module>
    from .setup_helpers import escape_path
ModuleNotFoundError: No module named '__main__.setup_helpers'; '__main__' is not a package

```

**Comment by SsnL** [comment]
`build_pytorch_libs.py` is not supposed to be called on its own.

**Comment by peterjc123** [comment]
`build_pytorch_libs.py` doesn't do anything, it is just a utility script. I suppose you want to call `tools/build_libtorch.py`?

**Comment by jinfagang** [comment]
Ok, sorry.... I run the wrong script.
