### ISSUE TITLE
Out of memory error when double backward BatchNorm2d

### ISSUE THREAD

**Issue by hongyi-zhang** [pytorch/pytorch#2287]
Running many iterations of double backward involving BatchNorm2d may cause out of memory error. There may be a memory leak somewhere? Code to reproduce the error:
```
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.autograd import Variable


class BatchNormTest(nn.Module):
    def __init__(self, c, num_classes=2):
        super(BatchNormTest, self).__init__()
        self.bn = nn.BatchNorm2d(c)

    def forward(self, x):
        out = x
        out = self.bn(out)
        # any nonlinearity causes BatchNormBackward to fail
        out = F.relu(out)
        return out

c = 100
net = BatchNormTest(c)
use_cuda = True
inputs = Variable(torch.rand(100,c,100,100), requires_grad=True)
if use_cuda:
    net.cuda()
    inputs = inputs.cuda()

T = 100
for i in range(T):
    output = net(inputs)
    loss1 = torch.sum(output)
    grad_params = torch.autograd.grad(loss1, inputs, create_graph=True)

    grad = grad_params[0]
    loss = torch.sum(grad)

    loss.backward()
    print(i)
```
The error message:
```
THCudaCheck FAIL file=/private/home/hongyizmit/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "models/testres.py", line 37, in <module>
    loss.backward()                                                                               
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/nn/_functions/thnn/batchnorm_double_backwards.py", line 80, in batchnorm_double_backwards_fn
    gG = ggI * first_back_grad_input(gO, 1)
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/nn/_functions/thnn/batchnorm_double_backwards.py", line 73, in first_back_grad_input
    input_sub_mu.div(sigma2_eps) * sum_exclude_dim1(gO * input_sub_mu))
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/autograd/variable.py", line 829, in __mul__
    return self.mul(other)
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/autograd/variable.py", line 339, in mul
    return Mul.apply(self, other)
  File "/private/home/hongyizmit/.conda/envs/torchmaster/lib/python2.7/site-packages/torch/autograd/_functions/basic_ops.py", line 48, in forward
    return a.mul(b)
RuntimeError: cuda runtime error (2) : out of memory at /private/home/hongyizmit/pytorch/torch/lib/THC/generic/THCStorage.cu:66
```
This is probably related to the previous issue https://github.com/pytorch/pytorch/issues/2264

**Comment by gchanan** [comment]
If you have time, could you run against https://github.com/pytorch/pytorch/tree/v0.2.0 and https://github.com/pytorch/pytorch/commit/7c04f11d88fc2b7d9456cb0e570427a5052332f0 and tell me if you hit the same issue; I'll try to reproduce myself soon, but it may have to wait until tomorrow.

**Comment by gchanan** [comment]
I was able to reproduce on the above versions.

**Comment by hyqneuron** [comment]
hitting the same bug. This is killing me.

**Comment by gchanan** [comment]
A couple of notes from early investigations:
1) This doesn't seem to be solely a function of batchnorm; e.g. if you replace the relu in your code with a function whose backwards doesn't use the input or output (e.g. sum) it doesn't seem to hit this issue.
2) From playing around with the implementation, if we don't save the gradoutput from Backward to  BackwardBackward we free memory correctly.  Of course we need the gradoutput to calculate the BackwardBackward correctly, though.

**Comment by gchanan** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/2328 (master) / https://github.com/pytorch/pytorch/pull/2326 (v.0.2.0)

**Comment by pclucas14** [comment]
Hi, 
do I need to install from source, or can I install the fixed pytorch version using conda ? (sorry if this is a newbie question)

Thanks, 
Lucas

**Comment by hongyi-zhang** [comment]
@gchanan Great, thanks!
@pclucas14 I think you need to install from source to fix this :)

**Comment by Ossidy** [comment]
Thanks for your post, you really saved me!
