### ISSUE TITLE
Import fails on 0.2 release installed with Conda

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/pytorch#2301]
Hi,
Was running a build on CI that worked previously on 0.1.12, and I'm running into:
```
ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
```
when simply running `import torch`. I am installing the CPU version of pytorch with `conda install --yes pytorch torchvision -c soumith`.

I haven't yet been able to reproduce this on a Linux machine without a GPU (there's no issue when installing the CPU version on a machine with a GPU, ostensibly because the shared object file exists), but i will let you know when i do.

thanks for the new release, looks great -- can't wait to try it out!

**Comment by nelson-liu** [comment]
Managed to reproduce the issue on a Linux machine without a GPU (It obviously works on a linux machine with a GPU):

```
nfliu at zin in ~
$ conda create -n pytorch_test python=3.5
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/nfliu/miniconda3/envs/pytorch_test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0
    pip:        9.0.1-py35_1
    python:     3.5.3-1
    readline:   6.2-2
    setuptools: 27.2.0-py35_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py35_0
    xz:         5.2.2-1
    zlib:       1.2.8-3

Proceed ([y]/n)? y

openssl-1.0.2l 100% |##########################################################################################################################| Time: 0:00:00  41.26 MB/s
#
# To activate this environment, use:
# > source activate pytorch_test
#
# To deactivate this environment, use:
# > source deactivate pytorch_test
#

nfliu at zin in ~
$ source activate pytorch_test
(pytorch_test) nfliu at zin in ~
$ conda install pytorch torchvision -c soumith
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/nfliu/miniconda3/envs/pytorch_test:

The following NEW packages will be INSTALLED:

    cffi:        1.10.0-py35_0
    freetype:    2.5.5-2
    jbig:        2.1-0
    jpeg:        9b-0
    libffi:      3.2.1-1
    libgcc:      5.2.0-0
    libpng:      1.6.27-0
    libtiff:     4.0.6-3
    mkl:         2017.0.3-0
    numpy:       1.13.1-py35_0
    olefile:     0.44-py35_0
    pillow:      4.2.1-py35_0
    pycparser:   2.18-py35_0
    pytorch:     0.2.0-py35h6718bbe_1cu75 soumith
    six:         1.10.0-py35_0
    torchvision: 0.1.8-py35_2             soumith

Proceed ([y]/n)? y

jbig-2.1-0.tar 100% |##########################################################################################################################| Time: 0:00:00   6.59 MB/s
jpeg-9b-0.tar. 100% |##########################################################################################################################| Time: 0:00:00  29.41 MB/s
libffi-3.2.1-1 100% |##########################################################################################################################| Time: 0:00:00  13.00 MB/s
libgcc-5.2.0-0 100% |##########################################################################################################################| Time: 0:00:00  32.72 MB/s
mkl-2017.0.3-0 100% |##########################################################################################################################| Time: 0:00:02  56.25 MB/s
libpng-1.6.27- 100% |##########################################################################################################################| Time: 0:00:00  46.06 MB/s
libtiff-4.0.6- 100% |##########################################################################################################################| Time: 0:00:00  60.08 MB/s
freetype-2.5.5 100% |##########################################################################################################################| Time: 0:00:00  59.23 MB/s
numpy-1.13.1-p 100% |##########################################################################################################################| Time: 0:00:00  55.61 MB/s
olefile-0.44-p 100% |##########################################################################################################################| Time: 0:00:00  27.53 MB/s
pycparser-2.18 100% |##########################################################################################################################| Time: 0:00:00  46.97 MB/s
six-1.10.0-py3 100% |##########################################################################################################################| Time: 0:00:00  12.21 MB/s
cffi-1.10.0-py 100% |##########################################################################################################################| Time: 0:00:00  53.46 MB/s
pillow-4.2.1-p 100% |##########################################################################################################################| Time: 0:00:00  58.27 MB/s
pytorch-0.2.0- 100% |##########################################################################################################################| Time: 0:00:25  12.75 MB/s
torchvision-0. 100% |##########################################################################################################################| Time: 0:00:00  11.92 MB/s
(pytorch_test) nfliu at zin in ~
$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfliu/miniconda3/envs/pytorch_test/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
```

**Comment by soumith** [comment]
i'm working on fixing this, it'll be fixed in about 4 hours (new fixed binaries are being generated)

**Comment by soumith** [comment]
fixed now.

**Comment by optimass** [comment]
The problem still exist for python=3.6

**Comment by brando90** [comment]
I have the same issue but with:

`pytorch                   0.3.0           py36cuda8.0cudnn6.0_0    anaconda`

**Comment by brando90** [comment]
@soumith should I open a new git issue or should we address my problem in the forum. I made a question for it already:

https://discuss.pytorch.org/t/how-to-update-pytorch-using-cuda-to-the-most-recent-version/15416/5
