### ISSUE TITLE
BFloat16 doesn't work with CUDA yet

### ISSUE THREAD

**Issue by nottombrown** [pytorch/pytorch#23149]
## BFloat16 doesn't work with CUDA yet

I'd like to use bfloat16 for numeric stability within some cuda kernels that I'm working on. It seems like @izdeby added bfloat16 support in #21523 (thanks!) but I think that `tensor.copy_` is not yet exposed to the python API.

## To Reproduce

```
>>> ary = torch.randn(5, dtype=torch.float32)
>>> ary.bfloat16() # CPU bfloat16 is fine
tensor([ 0.2383, -1.4531,  0.2461,  2.5156,  1.1719], dtype=torch.bfloat16)

>>> ary.bfloat16().cuda() # CUDA  bfloat16 is sad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 82, in __repr__
    return torch._tensor_str._str(self)
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor_str.py", line 300, in _str
    tensor_str = _tensor_str(self, indent)
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor_str.py", line 200, in _tensor_str
    self = self.float()
RuntimeError: "copy_" not implemented for 'BFloat16'
```
## Expected behavior

I'd like torch to copy the memory from CPU memory to GPU memory.

## Environment
```
PyTorch version: 1.2.0.dev20190721
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.11.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] pytorch-memlab==0.0.3
[pip3] tcop-pytorch==0.0.0
[pip3] torch==1.2.0.dev20190721
[pip3] torch-bst==0.0.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch-memlab            0.0.3                    pypi_0    pypi
[conda] pytorch-nightly           1.2.0.dev20190721 py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] tcop-pytorch              0.0.0                     dev_0    <develop>
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torch-bst                 0.0.0                     dev_0    <develop>
```

**Comment by izdeby** [comment]
Hey, @nottombrown, we have just started working on BFloat16 tensor and first we are planning to add CPU support for several methods and only then consider CUDA part. Please, stay tuned for the updates and feel free to directly ping me in case you have any questions.

**Comment by nottombrown** [comment]
Ok, thanks for the update @izdeby!

**Comment by ezyang** [comment]
This works now

```
>>> torch.randn(5, dtype=torch.float32).bfloat16().cuda() 
tensor([-0.8945, -0.0928,  0.9492,  0.4316,  0.0122], device='cuda:0',
       dtype=torch.bfloat16)
```
