### ISSUE TITLE
RuntimeError: _thnn_conv2d_forward not supported on CPUType for Half

### ISSUE THREAD

**Issue by glenn-jocher** [pytorch/pytorch#23377]
## 🐛 Bug

When attempting to adapt our repo (https://github.com/ultralytics/yolov3) to FP16 inference we get this error. We attempted model.half() and then input.half(), using output = model(input).

## To Reproduce

1. git clone https://github.com/ultralytics/yolov3
2. add model.half() and img.half() in detect.py
3. python3 detect.py

```bash
python3 detect.py
Namespace(cfg='cfg/yolov3-spp.cfg', conf_thres=0.5, data='data/coco.data', fourcc='mp4v', images='data/samples', img_size=416, nms_thres=0.5, output='output', weights='weights/yolov3-spp.weights')
Using CPU

image 1/2 data/samples/bus.jpg: Traceback (most recent call last):
  File "/System/Volumes/Data/Users/glennjocher/PycharmProjects/yolov3/detect.py", line 145, in <module>
    output=opt.output)
  File "/System/Volumes/Data/Users/glennjocher/PycharmProjects/yolov3/detect.py", line 73, in detect
    pred, _ = model(img)
  File "/Users/glennjocher/anaconda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/System/Volumes/Data/Users/glennjocher/PycharmProjects/yolov3/models.py", line 181, in forward
    x = module(x)
  File "/Users/glennjocher/anaconda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/glennjocher/anaconda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/glennjocher/anaconda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/glennjocher/anaconda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: _thnn_conv2d_forward not supported on CPUType for Half
```

## Expected behavior

```bash
python3 detect.py
Namespace(cfg='cfg/yolov3-spp.cfg', conf_thres=0.5, data='data/coco.data', fourcc='mp4v', images='data/samples', img_size=416, nms_thres=0.5, output='output', weights='weights/yolov3-spp.weights')
Using CPU

image 1/2 data/samples/bus.jpg: 416x320 3 persons, 1 buss, 1 handbags, Done. (0.363s)
image 2/2 data/samples/zidane.jpg: 256x416 2 persons, 1 ties, Done. (0.308s)
Results saved to /Users/glennjocher/PycharmProjects/yolov3/output
```

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.1.0            py37h01d97ff_0    conda-forge
[conda] mkl_fft                   1.0.12           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] pytorch                   1.1.0                   py3.7_0    pytorch
[conda] torchvision               0.3.0             py37_cuNone_1    pytorch
```
## Additional context

What is the recommended method for running object detection models in FP16 in PyTorch? Can you provide an example please? Thank you!

**Comment by soumith** [comment]
the error is pretty explicit. the CPU fp16 backend doesn't have Convolution support, and we dont aim to flesh it out either. It's explicitly a skeleton backend to support the CUDA counterpart which is fully fleshed out.
Maybe you wanted to do `model.half().to('cuda')`

**Comment by dashesy** [comment]
The problem is that this makes it difficult to export/trace a model in CPU. It is useful to export a model to ONNX in a machine without CUDA. The final model is going to be run on CUDA.

Plus, some models are too big to run on a machine with normal graphics cards.

**Comment by glenn-jocher** [comment]
@dashesy I think this is answered well in https://github.com/pytorch/pytorch/issues/23377#issuecomment-515833386. PyTorch simply does not support FP16 CPU ops.

**Comment by dashesy** [comment]
@glenn-jocher I understand. It doesn't support currently. But there is a good rationale to support it: test, and export.
