### ISSUE TITLE
Cannot export DataParallel model

### ISSUE THREAD

**Issue by cbarburescu** [pytorch/pytorch#23431]
## 🐛 Bug

Hello guys,

@AlexMuresan and I are trying to export a model trained using DataParallel, but it does not work as expected. Instead of saving an .onnx file at the required path, our script prints some errors and exits.

## To Reproduce

1. Train a model wrapped in DataParallel
1. Try to export it using torch.onnx.export

Code:
```
dummy_input = torch.randn(config.BATCH_SIZE, 3, 96, 96).to(cuda_device)
torch.onnx.export(model, dummy_input, path + "lol.onnx", verbose=False)
```

Error:
```
Traceback (most recent call last):
  File "banana_slug.py", line 76, in <module>
    save_production_model(model, torch_devices[0], Config)
  File "/data/cbarburescu/repos/banana-slug/src/utils.py", line 124, in save_production_model
    torch.onnx.export(model, dummy_input, path + "lol.onnx", verbose=False)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 266, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 225, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 231, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 294, in forward
    out = self.inner(*trace_inputs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/data/cbarburescu/tf_env/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
 0.0779  0.0768  0.0807  0.0780  0.0799  0.0790  0.0937  0.0860  0.0855  0.0828
 0.0742  0.0778  0.0845  0.0807  0.0850  0.0760  0.0891  0.0872  0.0815  0.0819
.......................................................
 0.0746  0.0771  0.0800  0.0843  0.0809  0.0756  0.0966  0.0862  0.0768  0.0809
 0.0674  0.0787  0.0822  0.0797  0.0846  0.0735  0.0870  0.0833  0.0731  0.0861
[ Variable[CUDAType]{64,10} ]
```

## Expected behavior

The .onnx file should be saved at `path + "lol.onnx"`

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.3.0
[conda] Could not collect

## Additional context

What we tried:
1. putting the model in eval mode
1. enabling gradients for the `dummy_input` tensor

What worked: checking if the model is of type DataParallel and setting it to model.module if it is (before calling export).
```
if isinstance(model, torch.nn.DataParallel):
        model = model.module
```
I noticed you are doing the same on line 313 from https://github.com/pytorch/pytorch/blob/master/torch/onnx/utils.py , however something seems to be wrong and the cast is not done on your side.

**Comment by CanoeFZH** [comment]
According to the code you mentioned, I think it is by design behavior that this will raise a error when you try to export ```torch.nn.DataParallel``` without unwrapping it firstly to ```model.module```.
``` 
   if isinstance(model, torch.nn.DataParallel):
        raise ValueError('torch.nn.DataParallel is not supported by ONNX '
                         'exporter, please use \'attribute\' module to '
                         'unwrap model from torch.nn.DataParallel. Try '
                         'torch.onnx.export(model.module, ...)')
```

**Comment by sunanlin13174** [comment]
> According to the code you mentioned, I think it is by design behavior that this will raise a error when you try to export `torch.nn.DataParallel` without unwrapping it firstly to `model.module`.
> 
> ```
>    if isinstance(model, torch.nn.DataParallel):
>         raise ValueError('torch.nn.DataParallel is not supported by ONNX '
>                          'exporter, please use \'attribute\' module to '
>                          'unwrap model from torch.nn.DataParallel. Try '
>                          'torch.onnx.export(model.module, ...)')
> ```
how  unwrapping it firstly to model.module

**Comment by garymm** [comment]
This appears to be working as intended. Follow the instructions in the error message.

**Comment by SajjadAemmi** [comment]
Unwrap your model from the DataParallel module by calling the model.module attribute:
```
model = torch.nn.DataParallel(model)
onnx_model = torch.onnx.export(model.module, ...)
```
