### ISSUE TITLE
weight_norm on GRU followed by .cuda causes an assert

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#2343]
I haven't looked into this in depth but this looks fishy:
```
import torch.nn as nn
from torch.nn.utils.weight_norm import weight_norm
a = nn.GRU(100, 20)
b = weight_norm(a, name='weight_hh_l0')
b = weight_norm(b, name='weight_ih_l0')
b.cuda()
  File "<stdin>", line 1, in <module>
  File "/home/didoyang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/home/didoyang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    self.flatten_parameters()
  File "/home/didoyang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 107, in flatten_parameters
    rnn._copyParams(all_weights, params)
  File "/home/didoyang/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 186, in _copyParams
    assert param_from.type() == param_to.type()
```

More here: https://discuss.pytorch.org/t/built-in-weight-norm-on-rnn/5905

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by albanD** [comment]
@gchanan is this still an issue in 1.3.1?

**Comment by zou3519** [comment]
I can repro this on master:
```
(/scratch/rzou/pt/workspace-env) [0] rzou@devfair0317:/scratch/rzou/pt/workspace (workspace) $ ipython
Python 3.7.5 (default, Oct 25 2019, 15:51:11)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: import torch.nn as nn
         ...: from torch.nn.utils.weight_norm import weight_norm
         ...: a = nn.GRU(100, 20)
         ...: b = weight_norm(a, name='weight_hh_l0')
         ...: b = weight_norm(b, name='weight_ih_l0')
         ...: b.cuda()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-32caf7b63e89> in <module>
      4 b = weight_norm(a, name='weight_hh_l0')
      5 b = weight_norm(b, name='weight_ih_l0')
----> 6 b.cuda()

/scratch/rzou/pt/workspace/torch/nn/modules/module.py in cuda(self, device)
    302             Module: self
    303         """
--> 304         return self._apply(lambda t: t.cuda(device))
    305
    306     def cpu(self):

/scratch/rzou/pt/workspace/torch/nn/modules/rnn.py in _apply(self, fn)
    138
    139         # Flattens params (on CUDA)
--> 140         self.flatten_parameters()
    141
    142         return ret

/scratch/rzou/pt/workspace/torch/nn/modules/rnn.py in flatten_parameters(self)
    127                     all_weights, (4 if self.bias else 2),
    128                     self.input_size, rnn.get_cudnn_mode(self.mode), self.hidden_size, self.num_layers,
--> 129                     self.batch_first, bool(self.bidirectional))
    130
    131     def _apply(self, fn):

RuntimeError: param_from.type() == param_to.type() INTERNAL ASSERT FAILED at ../aten/src/ATen/native/cudnn/RNN.cpp:541, please report a bug to PyTorch. parame
ter types mismatch
```

**Comment by peterbell10** [comment]
The problem is:

1. `weight_norm` removes the parameters from the module's parameter list and makes them normal class attributes:
https://github.com/pytorch/pytorch/blob/bfeff1eb8f90aa1ff7e4f6bafe9945ad409e2d97/torch/nn/utils/weight_norm.py#L32-L40
2. Calling `b.cuda()` applies only to parameters, not to the weight attributes.
3. [`RNNBase.flatten_parameters`](https://github.com/pytorch/pytorch/blob/bfeff1eb8f90aa1ff7e4f6bafe9945ad409e2d97/torch/nn/modules/rnn.py#L93-L123) (which is called from `RNNBase._apply()` acts on `self._flat_weights` which includes the value of the weight attributes and the bias parameters. So, it contains a mix of CUDA and CPU tensors.

**Comment by PetrochukM** [comment]
This is my workaround for right now:

```python
def apply_weight_norm(module, weight):
    weight_norm = torch.nn.utils.weight_norm(module, weight)
    func = module.flatten_parameters

    def decorator(*args, **kwargs):
        device = getattr(module, weight + '_g').device
        setattr(module, weight, getattr(module, weight).to(device))
        return func(*args, **kwargs)

    module.flatten_parameters = decorator
    return weight_norm

```

This applies weight norm to an rnn module and overrides the `flatten_parameters` function.

**Comment by mruberry** [comment]
This appears to be fixed. @gchanan, do you want to verify?

**Comment by gchanan** [comment]
I tested this on nightly and it worked for me, so closing.
