### ISSUE TITLE
RuntimeError:  methods must have a self argument:

### ISSUE THREAD

**Issue by InternetExplorer9** [pytorch/pytorch#23483]
## 🐛 Bug

With TorchScript enabled & while attempting to trace, I get the following error:

`RuntimeError: methods must have a self argument:`

For the following class (in `/torch/jit/__init__.py L636`)

```
class TracerWarning(Warning):

    @staticmethod
    def ignore_lib_warnings():

        # We ignore warnings from all submodules excluding the JIT, because we need them e.g. for _check_trace
        warnings.filterwarnings('ignore', category=TracerWarning, module='torch.(?!jit)')
```

## Environment

PyTorch version: 1.2.0.dev20190719
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] numpydoc==0.9.1
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==1.1.0.post2
[conda] blas 1.0 mkl
[conda] mkl 2019.3 199
[conda] mkl-service 1.1.2 py37hfbe908c_5
[conda] mkl_fft 1.0.10 py37h5e564d8_0
[conda] mkl_random 1.0.2 py37h27c97d8_0
[conda] pytorch-nightly 1.2.0.dev20190719 py3.7_0 pytorch
[conda] pytorch-pretrained-bert 0.6.2 pypi_0 pypi
[conda] torch 1.2.0.dev20190715 pypi_0 pypi

## Additional context

Traceback

```

Traceback (most recent call last):
  File "export_pytorch_to_caffe2.py", line 121, in <module>
    main(args)
  File "export_pytorch_to_caffe2.py", line 77, in main
    model = load_model(args)
  File "export_pytorch_to_caffe2.py", line 35, in load_model
    model = TorchUSICModel(args.model_dir)
  File "/Users/kkhorram/Desktop/export/export-fresh/export-pytorch-to-caffe2/USICModel_original.py", line 120, in __init__
    self.encoder = Elmo(elmo_options_file, elmo_weights_file, 2, dropout=0, requires_grad=False)
  File "/anaconda3/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 110, in __init__
    vocab_to_cache=vocab_to_cache)
  File "/anaconda3/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 557, in __init__
    requires_grad=requires_grad)
  File "/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1304, in init_then_register
    _create_methods_from_stubs(self, methods)
  File "/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1260, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 999, in _try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1091, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1048, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError: 
methods must have a self argument:
at /anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py:636:5
    @staticmethod
     ~~~ <--- HERE
    def ignore_lib_warnings():
        # We ignore warnings from all submodules excluding the JIT, because we need them e.g. for _check_trace
        warnings.filterwarnings('ignore', category=TracerWarning, module='torch.(?!jit)')
'__torch__.torch.jit.TracerWarning.ignore_lib_warnings' is being compiled since it was called from 'pack_padded_sequence'
at /anaconda3/lib/python3.7/site-packages/torch/nn/utils/rnn.py:257:32

    Returns:
        a :class:`PackedSequence` object
    """
    if torch._C._get_tracing_state() and not isinstance(lengths, torch.Tensor):
        warnings.warn('pack_padded_sequence has been called with a Python list of '
                      'sequence lengths. The tracer cannot track the data flow of Python '
                      'values, and it will treat them as constants, likely rendering '
                      'the trace incorrect for any other combination of lengths.',
                      category=torch.jit.TracerWarning, stacklevel=2)
                               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    lengths = torch.as_tensor(lengths, dtype=torch.int64)
    if enforce_sorted:
        sorted_indices = None
    else:
        lengths, sorted_indices = torch.sort(lengths, descending=True)
        sorted_indices = sorted_indices.to(input.device)
        batch_dim = 0 if batch_first else 1
        input = input.index_select(batch_dim, sorted_indices)
'pack_padded_sequence' is being compiled since it was called from 'ElmoLstm.sort_and_run_forward'
at /anaconda3/lib/python3.7/site-packages/allennlp/modules/elmo_lstm.py:176:9
        # First count how many sequences are empty.
        batch_size = mask.size(0)
        num_valid = torch.sum(mask[:, 0]).int().item()

        sequence_lengths = get_lengths_from_binary_sequence_mask(mask)
        sorted_inputs, sorted_sequence_lengths, restoration_indices, sorting_indices =\
            sort_batch_by_length(inputs, sequence_lengths)

        # Now create a PackedSequence with only the non-empty, sorted sequences.
        packed_sequence_input = pack_padded_sequence(sorted_inputs[:num_valid, :, :],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                                                     sorted_sequence_lengths[:num_valid].data.tolist(),
                                                     batch_first=True)
        # Prepare the initial states.
        if not self.stateful:
            if hidden_state is None:
                initial_states = hidden_state
            elif isinstance(hidden_state, tuple):
                initial_states = [state.index_select(1, sorting_indices)[:, :num_valid, :].contiguous()
                                  for state in hidden_state]

```

**Comment by suo** [comment]
@wanchaol, can you take a look? Is this fixed by your pack_padded_sequence changes?

**Comment by InternetExplorer9** [comment]
> @wanchaol, can you take a look? Is this fixed by your pack_padded_sequence changes?

This is after I applied the fix for the _get_tracing_state() operator.

**Comment by wanchaol** [comment]
> > @wanchaol, can you take a look? Is this fixed by your pack_padded_sequence changes?
> 
> This is after I applied the fix for the _get_tracing_state() operator.

@InternetExplorer9 I think you are using tracing instead of scripting, the `get_tracing_state()` operator support is only used in scripting mode. We actually support PackPaddedSequence in script, I just landed it yesterday https://github.com/pytorch/pytorch/pull/23249, in this PR I also remove the `torch.jit.TracerWarning` so this error won't happen again if you checkout master

**Comment by InternetExplorer9** [comment]
Great, thanks!
