### ISSUE TITLE
Compilation error CUDA 10.0/Clang 8.0.0

### ISSUE THREAD

**Issue by abonnet** [pytorch/pytorch#23563]
## 🐛 Bug

I am getting a compilation error when building from source with CUDA 10.0 and Clang 8.0.0 on Ubuntu 14.04. Error message: `nvcc fatal   : The version ('8.0') of the host compiler ('clang') is not supported` while according to Clang website, Clang 8.0.0 is supporting CUDA 10.0.

Full output:
```
-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.13.3
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /clang_8.0.0/bin/clang++
--   C++ compiler id       : Clang
--   C++ compiler version  : 8.0.0
--   BLAS                  : MKL
--   CXX flags             : -stdlib=libc++ -Wno-deprecated -fvisibility-inlines-hidden -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_ML=1;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;USE_GCC_ATOMICS=1;MKLDNN_THR=MKLDNN_THR_TBB;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python2.7/dist-packages
--   CMAKE_INSTALL_PREFIX  : /torch_dir/pytorch/torch
-- 
--   TORCH_VERSION         : 1.2.0
--   CAFFE2_VERSION        : 1.2.0
--   BUILD_CAFFE2_MOBILE   : ON
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 2.7.6
--     Python executable   : /usr/bin/python
--     Pythonlibs version  : 2.7.6
--     Python library      : /usr/lib/libpython2.7.so.1.0
--     Python includes     : /usr/include/python2.7
--     Python site-packages: lib/python2.7/dist-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   INTERN_BUILD_MOBILE   : 
--   USE_ASAN              : OFF
--   USE_CUDA              : True
--     CUDA static link    : OFF
--     USE_CUDNN           : OFF
--     CUDA version        : 10.0
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /clang_8.0.0/bin/clang
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_MKLDNN_CBLAS      : OFF
--   USE_NCCL              : True
--     USE_SYSTEM_NCCL     : False
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : 0
--   USE_TBB               : 1
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : True
--     USE_MPI             : OFF
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   BUILD_NAMEDTENSOR   : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fbgemm;fp16;gloo;aten_op_header_gen;foxi_loader;rt;dl
-- Configuring done
-- Generating done
-- Build files have been written to: /torch_dir/pytorch/build
cmake --build . --target install --config Release -- -j 20
[54/3175] Performing build step for 'nccl_external'
FAILED: cd /torch_dir/pytorch/third_party/nccl/nccl && env CCACHE_DISABLE=1 SCCACHE_DISABLE=1 make CXX=/clang_8.0.0/bin/clang++ CUDA_HOME=/usr/local/cuda NVCC=/usr/local/cuda/bin/nvcc "NVCC_GENCODE=-gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_75,code=compute_75" BUILDDIR=/torch_dir/pytorch/build/nccl VERBOSE=0 -j && /usr/local/bin/cmake -E touch /torch_dir/pytorch/build/nccl_external-prefix/src/nccl_external-stamp/nccl_external-build
make -C src build BUILDDIR=/torch_dir/pytorch/build/nccl
make[1]: Entering directory `/torch_dir/pytorch/third_party/nccl/nccl/src'
Grabbing   include/nccl_net.h                  > /torch_dir/pytorch/build/nccl/include/nccl_net.h
Generating nccl.h.in                           > /torch_dir/pytorch/build/nccl/include/nccl.h
Compiling  init.cc                             > /torch_dir/pytorch/build/nccl/obj/init.o
Compiling  channel.cc                          > /torch_dir/pytorch/build/nccl/obj/channel.o
Compiling  bootstrap.cc                        > /torch_dir/pytorch/build/nccl/obj/bootstrap.o
Compiling  transport.cc                        > /torch_dir/pytorch/build/nccl/obj/transport.o
Compiling  enqueue.cc                          > /torch_dir/pytorch/build/nccl/obj/enqueue.o
Compiling  misc/group.cc                       > /torch_dir/pytorch/build/nccl/obj/misc/group.o
Compiling  misc/nvmlwrap.cc                    > /torch_dir/pytorch/build/nccl/obj/misc/nvmlwrap.o
Compiling  misc/ibvwrap.cc                     > /torch_dir/pytorch/build/nccl/obj/misc/ibvwrap.o
Compiling  misc/rings.cc                       > /torch_dir/pytorch/build/nccl/obj/misc/rings.o
Compiling  misc/utils.cc                       > /torch_dir/pytorch/build/nccl/obj/misc/utils.o
Compiling  misc/argcheck.cc                    > /torch_dir/pytorch/build/nccl/obj/misc/argcheck.o
Compiling  misc/trees.cc                       > /torch_dir/pytorch/build/nccl/obj/misc/trees.o
Compiling  misc/topo.cc                        > /torch_dir/pytorch/build/nccl/obj/misc/topo.o
Compiling  transport/p2p.cc                    > /torch_dir/pytorch/build/nccl/obj/transport/p2p.o
Compiling  transport/shm.cc                    > /torch_dir/pytorch/build/nccl/obj/transport/shm.o
Compiling  transport/net.cc                    > /torch_dir/pytorch/build/nccl/obj/transport/net.o
Compiling  transport/net_socket.cc             > /torch_dir/pytorch/build/nccl/obj/transport/net_socket.o
Compiling  transport/net_ib.cc                 > /torch_dir/pytorch/build/nccl/obj/transport/net_ib.o
Compiling  collectives/all_reduce.cc           > /torch_dir/pytorch/build/nccl/obj/collectives/all_reduce.o
Compiling  collectives/all_gather.cc           > /torch_dir/pytorch/build/nccl/obj/collectives/all_gather.o
Compiling  collectives/broadcast.cc            > /torch_dir/pytorch/build/nccl/obj/collectives/broadcast.o
Compiling  collectives/reduce.cc               > /torch_dir/pytorch/build/nccl/obj/collectives/reduce.o
Compiling  collectives/reduce_scatter.cc       > /torch_dir/pytorch/build/nccl/obj/collectives/reduce_scatter.o
init.cc:186:21: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
void __attribute__((optimize("O0"))) commPoison(ncclComm_t comm) {
                    ^
make[2]: Entering directory `/torch_dir/pytorch/third_party/nccl/nccl/src/collectives/device'
Generating rules                               > /torch_dir/pytorch/build/nccl/obj/collectives/device/Makefile.rules
make[2]: Leaving directory `/torch_dir/pytorch/third_party/nccl/nccl/src/collectives/device'
make[2]: Entering directory `/torch_dir/pytorch/third_party/nccl/nccl/src/collectives/device'
nvcc fatal   : The version ('8.0') of the host compiler ('clang') is not supported
make[2]: *** [/torch_dir/pytorch/build/nccl/obj/collectives/device/all_reduce.dep] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal   : The version ('8.0') of the host compiler ('clang') is not supported
make[2]: *** [/torch_dir/pytorch/build/nccl/obj/collectives/device/all_gather.dep] Error 1
nvcc fatal   : The version ('8.0') of the host compiler ('clang') is not supported
make[2]: *** [/torch_dir/pytorch/build/nccl/obj/collectives/device/broadcast.dep] Error 1
nvcc fatal   : The version ('8.0') of the host compiler ('clang') is not supported
make[2]: *** [/torch_dir/pytorch/build/nccl/obj/collectives/device/reduce.dep] Error 1
make[2]: Leaving directory `/torch_dir/pytorch/third_party/nccl/nccl/src/collectives/device'
make[1]: *** [/torch_dir/pytorch/build/nccl/obj/collectives/device/colldevice.a] Error 2
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
make[1]: Leaving directory `/torch_dir/pytorch/third_party/nccl/nccl/src'
make: *** [src.build] Error 2
[54/3175] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/protostream_objectwriter.cc.o
In file included from ../third_party/protobuf/src/google/protobuf/util/internal/protostream_objectwriter.cc:31:
In file included from ../third_party/protobuf/src/google/protobuf/util/internal/protostream_objectwriter.h:45:
../third_party/protobuf/src/google/protobuf/util/internal/proto_writer.h:113:24: warning: 'RenderBytes' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual ProtoWriter* RenderBytes(StringPiece name, StringPiece value) {
                       ^
../third_party/protobuf/src/google/protobuf/util/internal/object_writer.h:99:25: note: overridden virtual function is here
  virtual ObjectWriter* RenderBytes(StringPiece name, StringPiece value) = 0;
                        ^
1 warning generated.
[54/3175] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/extension_set.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 749, in <module>
    build_deps()
  File "setup.py", line 323, in build_deps
    cmake=cmake)
  File "/torch_dir/pytorch/tools/build_pytorch_libs.py", line 64, in build_caffe2
    cmake.build(my_env)
  File "/torch_dir/pytorch/tools/setup_helpers/cmake.py", line 340, in build
    self.run(build_args, my_env)
  File "/torch_dir/pytorch/tools/setup_helpers/cmake.py", line 93, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '20']' returned non-zero exit status 1

real	2m39.266s
user	3m56.916s
sys	0m7.882s
```

## To Reproduce

1. `git clone --recursive https://github.com/pytorch/pytorch && cd Pytorch`
2. ```# Compiler options
export CC=/clang_8.0.0/bin/clang
export CXX=${CC}++
export CFLAGS="-stdlib=libc++"
export TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
export TORCH_CUDA_ARCH_LIST="5.2;6.1;7.0;7.5+PTX"
export TH_BINARY_BUILD=1
export CMAKE_LIBRARY_PATH="/opt/intel/lib:/lib"
export CMAKE_INCLUDE_PATH="/opt/intel/include"
export USE_OPENMP=0
export USE_TBB=1
export BLAS=MKL
export MKL_THREADING=TBB
export MKLDNN_THREADING=TBB
export PARALLEL_BACKEND=NATIVE_TBB
export USE_CUDA=ON
export USE_CUDNN=OFF
export USE_NCCL=ON
```
3. `python setup.py build`

## Expected behavior

Compile successfully.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 14.04.6 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 3.13.3

Python version: 2.7
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by VitalyFedyunin** [comment]
As per https://docs.nvidia.com/cuda/archive/10.0/cuda-installation-guide-linux/index.html CUDA 10 supports only clang 6.

**Comment by soumith** [comment]
@abonnet you need to install CUDA 10.1, not 10.0, because 10.1 supports clang 8: https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html
