### ISSUE TITLE
segmentation faults when using multiprocessing_context='spawn' with large number of processes

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#23720]
Pytorch version `1.2.0.dev20190801+cu100` running into problem using `multiprocessing_context='spawn'` in the DataLoader

It works for 48 processes over two machines using `spawn` or 384 processes using default method, but segfaults for 384 processes after warnings like this ([log](https://app.wandb.ai/yaroslavvb/imagenet18/runs/ftvkloea/logs))
```
user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown 
  len(cache)) 
```
384 processes comes from 3 DataLoaders per process (test, validation, train), 8 workers per DataLoader, and separate process per GPU for 16 GPUs

**Comment by mrshenli** [comment]
cc @SsnL @cpuhrsch

**Comment by ElegantLin** [comment]
I also met this problem. The same warning message and finally it ended with
```
/home/432/dzl/.conda/envs/py36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/432/dzl/.conda/envs/py36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/432/dzl/.conda/envs/py36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/432/dzl/.conda/envs/py36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "main.py", line 420, in <module>
    main()
  File "main.py", line 109, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/432/dzl/.conda/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/home/432/dzl/.conda/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/home/432/dzl/.conda/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/432/dzl/examples/imagenet/main.py", line 151, in main_worker
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
  File "/home/432/dzl/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/home/432/dzl/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled cuda error
```

I also used `NCCL_INFO`. It looked normal before.
