### ISSUE TITLE
Segfault on .cuda() call

### ISSUE THREAD

**Issue by Aelphy** [pytorch/pytorch#23820]
## 🐛 Bug

I compiled master version of pytorch from sources with magma 2.2.0, cuda 10.0, cudnn 7.5
and everything works until the first .cuda() call:

## To Reproduce

1. `import torch`
2. `torch.randn(5).cuda()`

```
Program received signal SIGSEGV, Segmentation fault.
0x00002aaac0642803 in at::cuda::detail::CUDAHooks::initCUDA() const () from /cluster/home/mikhailu/.local/lib/python3.7/site-packages/torch/lib/libtorch.so
#0  0x00002aaac0642803 in at::cuda::detail::CUDAHooks::initCUDA() const () from /cluster/home/mikhailu/.local/lib/python3.7/site-packages/torch/lib/libtorch.so
#1  0x00002aaaba7180ec in void std::call_once<at::Context::lazyInitCUDA()::{lambda()#1}>(std::once_flag&, at::Context::lazyInitCUDA()::{lambda()#1}&&)::{lambda()#2}::_FUN() () from /cluster/home/mikhailu/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#2  0x00002aaaab245e70 in pthread_once () from /lib64/libpthread.so.0
#3  0x00002aaaba724341 in THCPModule_initExtension(_object*) () from /cluster/home/mikhailu/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#4  0x00002aaaaad69140 in _PyMethodDef_RawFastCallKeywords (method=0x16f7f40, self=<optimized out>, args=0x6b7618, nargs=0, kwnames=<optimized out>) at Objects/call.c:629
#5  0x00002aaaaad691d5 in _PyCFunction_FastCallKeywords (func=0x2aaab7852b40, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:730
#6  0x00002aaaaad4146f in call_function (kwnames=0x0, oparg=0, pp_stack=<synthetic pointer>) at Python/ceval.c:4554
#7  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3093
#8  0x00002aaaaad375d0 in function_code_fastcall (co=co@entry=0x2aab16e72660, args=<optimized out>, args@entry=0x0, nargs=nargs@entry=0, globals=globals@entry=0x2aab16e7d678) at Objects/call.c:283
#9  0x00002aaaaad68b6e in _PyFunction_FastCallDict (func=0x2aab16ed57b8, args=0x0, nargs=0, kwargs=0x0) at Objects/call.c:322
#10 0x00002aaaaad69e6e in _PyObject_CallFunctionVa (callable=0x2aab16ed57b8, format=<optimized out>, va=<optimized out>, is_size_t=<optimized out>) at Objects/call.c:931
#11 0x00002aaaaad6a111 in callmethod (is_size_t=0, va=0x7fffffffabc8, format=0x2aaaba8c2f8c "", callable=0x2aab16ed57b8) at Objects/call.c:1027
#12 PyObject_CallMethod (obj=<optimized out>, name=<optimized out>, format=0x2aaaba8c2f8c "") at Objects/call.c:1046
#13 0x00002aaaba6e6d23 in torch::utils::cuda_lazy_init() () from /cluster/home/mikhailu/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#14 0x00002aaaba2f2d5c in torch::autograd::THPVariable_cuda(_object*, _object*, _object*) () from /cluster/home/mikhailu/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#15 0x00002aaaaad6915b in _PyMethodDef_RawFastCallKeywords (method=<optimized out>, self=self@entry=0x2aaaaac81d38, args=args@entry=0x655950, nargs=nargs@entry=0, kwnames=kwnames@entry=0x0) at Objects/call.c:690
#16 0x00002aaaaad71f79 in _PyMethodDescr_FastCallKeywords (descrobj=0x2aaab7854cf0, args=args@entry=0x655948, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0) at Objects/descrobject.c:288
#17 0x00002aaaaad41688 in call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>) at Python/ceval.c:4579
#18 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#19 0x00002aaaaae57bfb in _PyEval_EvalCodeWithName (_co=_co@entry=0x2aaaaabddae0, globals=globals@entry=0x2aaaaaba61f8, locals=locals@entry=0x2aaaaaba61f8, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0x0, kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0x0, qualname=qualname@entry=0x0) at Python/ceval.c:3930
#20 0x00002aaaaae57d3d in PyEval_EvalCodeEx (_co=_co@entry=0x2aaaaabddae0, globals=globals@entry=0x2aaaaaba61f8, locals=locals@entry=0x2aaaaaba61f8, args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0) at Python/ceval.c:3959
#21 0x00002aaaaae57d8b in PyEval_EvalCode (co=co@entry=0x2aaaaabddae0, globals=globals@entry=0x2aaaaaba61f8, locals=locals@entry=0x2aaaaaba61f8) at Python/ceval.c:524
#22 0x00002aaaaae905c2 in run_mod (arena=0x2aaaaab1d0a8, flags=0x7fffffffb2a0, locals=0x2aaaaaba61f8, globals=0x2aaaaaba61f8, filename=<optimized out>, mod=<optimized out>) at Python/pythonrun.c:1035
#23 PyRun_StringFlags (str=str@entry=0x2aaaaac81ef0 "import torch; torch.randn(5).cuda()\n", start=start@entry=257, globals=0x2aaaaaba61f8, locals=0x2aaaaaba61f8, flags=flags@entry=0x7fffffffb2a0) at Python/pythonrun.c:959
#24 0x00002aaaaae9064b in PyRun_SimpleStringFlags (command=0x2aaaaac81ef0 "import torch; torch.randn(5).cuda()\n", flags=flags@entry=0x7fffffffb2a0) at Python/pythonrun.c:455
#25 0x00002aaaaaeb3242 in pymain_run_command (cf=0x7fffffffb2a0, command=<optimized out>) at Modules/main.c:385
#26 pymain_run_python (pymain=0x7fffffffb3b0) at Modules/main.c:2620
#27 pymain_main (pymain=pymain@entry=0x7fffffffb3b0) at Modules/main.c:2787
#28 0x00002aaaaaeb39dd in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:2822
#29 0x00002aaaabb80445 in __libc_start_main () from /lib64/libc.so.6
#30 0x000000000040066e in _start ()
```

## Expected behavior

I would expect not to have segfault but have a variable in GPU memory

## Environment

Collecting environment information...
PyTorch version: 1.2.0a0+f87a4cc
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux release 7.5.1804 (Core) 
GCC version: (GCC) 6.3.0
CMake version: version 3.14.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.39
cuDNN version: 7.5

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] tntorch==0.1.0
[pip3] torch==1.2.0a0+f87a4cc
[pip3] torchvision==0.2.2.post3

 - Any other relevant information:

**Comment by Aelphy** [comment]
fixed updating magma to 2.4.0
