### ISSUE TITLE
clang-tidy complains about dispatch macros

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#23947]
## 🐛 Bug

Over in https://github.com/pytorch/pytorch/pull/23942 I got a clang-tidy failure about dispatch macros -- I'll reproduce it here because I think the build will eventually go away:

```
Traceback (most recent call last):
  File "tools/clang_tidy.py", line 52, in run_shell_command
    output = subprocess.check_output(arguments).decode().strip()
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clang-tidy', '-p', 'build', '-config', '{"Checks": " -* ,bugprone-* ,-bugprone-forward-declaration-namespace ,-bugprone-macro-parentheses ,cppcoreguidelines-* ,-cppcoreguidelines-interfaces-global-init ,-cppcoreguidelines-owning-memory ,-cppcoreguidelines-pro-bounds-array-to-pointer-decay ,-cppcoreguidelines-pro-bounds-constant-array-index ,-cppcoreguidelines-pro-bounds-pointer-arithmetic ,-cppcoreguidelines-pro-type-cstyle-cast ,-cppcoreguidelines-pro-type-reinterpret-cast ,-cppcoreguidelines-pro-type-static-cast-downcast ,-cppcoreguidelines-pro-type-union-access ,-cppcoreguidelines-pro-type-vararg ,-cppcoreguidelines-special-member-functions ,hicpp-exception-baseclass ,hicpp-avoid-goto ,modernize-* ,-modernize-return-braced-init-list ,-modernize-use-auto ,-modernize-use-default-member-init ,-modernize-use-using ,performance-* ,-performance-noexcept-move-constructor ", "WarningsAsErrors": "*", "HeaderFilterRegex": "torch/csrc/.*", "AnalyzeTemporaryDtors": false, "CheckOptions": null}', '-line-filter', '[{"name": "torch/csrc/TypeInfo.cpp", "lines": [[87, 93], [149, 150], [161, 162]]}, {"name": "torch/csrc/autograd/python_variable_indexing.cpp", "lines": [[178, 179]]}, {"name": "torch/csrc/jit/fuser/codegen.cpp", "lines": [[107, 108]]}, {"name": "torch/csrc/jit/passes/shape_analysis.cpp", "lines": [[42, 43]]}, {"name": "torch/csrc/jit/register_prim_ops.cpp", "lines": [[89, 90]]}, {"name": "torch/csrc/utils/python_arg_parser.cpp", "lines": [[159, 160]]}]', 'torch/csrc/TypeInfo.cpp', 'torch/csrc/autograd/python_variable_indexing.cpp', 'torch/csrc/jit/fuser/codegen.cpp', 'torch/csrc/jit/passes/shape_analysis.cpp', 'torch/csrc/jit/register_prim_ops.cpp', 'torch/csrc/utils/python_arg_parser.cpp']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/clang_tidy.py", line 295, in <module>
    main()
  File "tools/clang_tidy.py", line 291, in main
    print(run_clang_tidy(options, line_filters, files))
  File "tools/clang_tidy.py", line 185, in run_clang_tidy
    output = run_shell_command(command)
  File "tools/clang_tidy.py", line 56, in run_shell_command
    raise RuntimeError("Error executing {}: {}".format(" ".join(arguments), error_output))
RuntimeError: Error executing clang-tidy -p build -config {"Checks": " -* ,bugprone-* ,-bugprone-forward-declaration-namespace ,-bugprone-macro-parentheses ,cppcoreguidelines-* ,-cppcoreguidelines-interfaces-global-init ,-cppcoreguidelines-owning-memory ,-cppcoreguidelines-pro-bounds-array-to-pointer-decay ,-cppcoreguidelines-pro-bounds-constant-array-index ,-cppcoreguidelines-pro-bounds-pointer-arithmetic ,-cppcoreguidelines-pro-type-cstyle-cast ,-cppcoreguidelines-pro-type-reinterpret-cast ,-cppcoreguidelines-pro-type-static-cast-downcast ,-cppcoreguidelines-pro-type-union-access ,-cppcoreguidelines-pro-type-vararg ,-cppcoreguidelines-special-member-functions ,hicpp-exception-baseclass ,hicpp-avoid-goto ,modernize-* ,-modernize-return-braced-init-list ,-modernize-use-auto ,-modernize-use-default-member-init ,-modernize-use-using ,performance-* ,-performance-noexcept-move-constructor ", "WarningsAsErrors": "*", "HeaderFilterRegex": "torch/csrc/.*", "AnalyzeTemporaryDtors": false, "CheckOptions": null} -line-filter [{"name": "torch/csrc/TypeInfo.cpp", "lines": [[87, 93], [149, 150], [161, 162]]}, {"name": "torch/csrc/autograd/python_variable_indexing.cpp", "lines": [[178, 179]]}, {"name": "torch/csrc/jit/fuser/codegen.cpp", "lines": [[107, 108]]}, {"name": "torch/csrc/jit/passes/shape_analysis.cpp", "lines": [[42, 43]]}, {"name": "torch/csrc/jit/register_prim_ops.cpp", "lines": [[89, 90]]}, {"name": "torch/csrc/utils/python_arg_parser.cpp", "lines": [[159, 160]]}] torch/csrc/TypeInfo.cpp torch/csrc/autograd/python_variable_indexing.cpp torch/csrc/jit/fuser/codegen.cpp torch/csrc/jit/passes/shape_analysis.cpp torch/csrc/jit/register_prim_ops.cpp torch/csrc/utils/python_arg_parser.cpp: /home/vsts/work/1/s/torch/csrc/TypeInfo.cpp:150:12: error: inside a lambda, '__func__' expands to the name of the function call operator; consider capturing the name of the enclosing function explicitly [bugprone-lambda-function-name,-warnings-as-errors]
    return AT_DISPATCH_INTEGRAL_TYPES(self->type, "max", [] {
           ^
/home/vsts/work/1/s/aten/src/ATen/Dispatch.h:219:9: note: expanded from macro 'AT_DISPATCH_INTEGRAL_TYPES'
        AT_ERROR(#NAME, " not implemented for '", toString(_st), "'");       \
        ^
/home/vsts/work/1/s/c10/util/Exception.h:373:32: note: expanded from macro 'AT_ERROR'
    C10_EXPAND_MSVC_WORKAROUND(TORCH_CHECK(false, ::c10::str(__VA_ARGS__)));  \
                               ^
/home/vsts/work/1/s/c10/util/Exception.h:245:5: note: expanded from macro 'TORCH_CHECK'
    C10_THROW_ERROR(Error,                                  \
    ^
/home/vsts/work/1/s/c10/util/Exception.h:141:26: note: expanded from macro 'C10_THROW_ERROR'
  throw ::c10::err_type({__func__, __FILE__, static_cast<uint32_t>(__LINE__)}, msg)
                         ^
/home/vsts/work/1/s/torch/csrc/TypeInfo.cpp:162:12: error: inside a lambda, '__func__' expands to the name of the function call operator; consider capturing the name of the enclosing function explicitly [bugprone-lambda-function-name,-warnings-as-errors]
    return AT_DISPATCH_INTEGRAL_TYPES(self->type, "min", [] {
           ^
/home/vsts/work/1/s/aten/src/ATen/Dispatch.h:219:9: note: expanded from macro 'AT_DISPATCH_INTEGRAL_TYPES'
        AT_ERROR(#NAME, " not implemented for '", toString(_st), "'");       \
        ^
/home/vsts/work/1/s/c10/util/Exception.h:373:32: note: expanded from macro 'AT_ERROR'
    C10_EXPAND_MSVC_WORKAROUND(TORCH_CHECK(false, ::c10::str(__VA_ARGS__)));  \
                               ^
/home/vsts/work/1/s/c10/util/Exception.h:245:5: note: expanded from macro 'TORCH_CHECK'
    C10_THROW_ERROR(Error,                                  \
    ^
/home/vsts/work/1/s/c10/util/Exception.h:141:26: note: expanded from macro 'C10_THROW_ERROR'
  throw ::c10::err_type({__func__, __FILE__, static_cast<uint32_t>(__LINE__)}, msg)
                         ^
##[error]Bash exited with code '1'.
##[section]Finishing: CmdLine
```

**Comment by gchanan** [comment]
easiest fix is probably just not to lint the lines; a better fix may be to introduce the scope without the lambda.
