### ISSUE TITLE
Using  `torch.utils.checkpoint.checkpoint_sequential` and `torch.autograd.grad` breaks when used in combination with `DistributedDataParallel`

### ISSUE THREAD

**Issue by jotterbach** [pytorch/pytorch#24005]
## 🐛 Bug

Using  `torch.utils.checkpoint.checkpoint_sequential` and `torch.autograd.grad` breaks when used in combination with `DistributedDataParallel` resulting in the following stacktrace

```
Traceback (most recent call last):                                                                    
  File "minimal_buggy_2.py", line 198, in <module>                                                    
    train(hps)                                                                                        
  File "minimal_buggy_2.py", line 179, in train                                                       
    loss.backward()                                                                                   
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward                
    torch.autograd.backward(self, gradient, retain_graph, create_graph)                               
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward      
    allow_unreachable=True)  # allow_unreachable flag                                                 
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/function.py", line 77, in apply         
    return self._forward_cls.backward(self, *args)                                                    
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 99, in backward       
    torch.autograd.backward(outputs, args)                                                            
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward      
    allow_unreachable=True)  # allow_unreachable flag                                                 
RuntimeError: has_marked_unused_parameters_ ASSERT FAILED at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:181, please report a bug to PyTorch.
```

## To Reproduce

1. Running `python -m torch.distributed.launch --nproc_per_node=2 minimal_buggy.py` works
1. Running `python -m torch.distributed.launch --nproc_per_node=2 minimal_buggy.py --parallel` breaks

The code for `minimal_buggy.py` is here:
```
from argparse import ArgumentParser, Namespace
import numpy as np

import torch
import torch.nn as nn
import torch.distributed as dist
from torch.utils.checkpoint import checkpoint_sequential

import torchvision.datasets as ds
from torchvision import transforms


class GradientStep(nn.Module):

    def __init__(self, energy):
        super(GradientStep, self).__init__()
        self._energy = energy
        self.step_size = 0.1

    def forward(self, x: torch.Tensor):
        with torch.enable_grad():
            x.requires_grad_()
            omega = self._energy(x).sum()
            grad_out = torch.ones_like(omega).to(x.device)
            dx = torch.autograd.grad(outputs=omega, inputs=x, grad_outputs=grad_out,
                                     create_graph=True, retain_graph=True,
                                     allow_unused=True)[0]
            dx.requires_grad_()
            x = (x - self.step_size ** 2 * dx)
        return x


class FFN(nn.Module):

    def __init__(self):
        super(FFN, self).__init__()
        self.n_hidden = 1024
        self._energy = nn.Sequential(
            nn.Linear(28**2, self.n_hidden),
            nn.LeakyReLU(),
            nn.Linear(self.n_hidden, self.n_hidden),
            nn.LeakyReLU(),
            nn.Linear(self.n_hidden, self.n_hidden),
            nn.LeakyReLU(),
            nn.Linear(self.n_hidden, 1))
        self.L = 10

    def forward(self, x: torch.Tensor):
        y = x.clone().to(x.device)
        y.requires_grad_()
        fwd = nn.Sequential(*[GradientStep(self._energy) for _ in range(self.L)])
        y = checkpoint_sequential(fwd, self.L, y)
        return y


def get_distributed_mnist_iterators(batch_size, **kwargs):
    def _worker_init_fn(worker_id):
        np.random.seed(np.random.get_state()[1][0] + worker_id)

    base_transforms = [
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.reshape(-1, ))]

    train_dataset = ds.MNIST(
        '/tmp/mnist/train',
        train=True,
        download=True,
        transform=transforms.Compose(base_transforms))

    test_dataset = ds.MNIST(
        '/tmp/mnist/test',
        train=False,
        download=True,
        transform=transforms.Compose(base_transforms))

    train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)
    test_sampler = torch.utils.data.distributed.DistributedSampler(test_dataset)

    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=kwargs.get('workers', 4),
        pin_memory=True,
        sampler=train_sampler,
        worker_init_fn=_worker_init_fn)

    test_loader = torch.utils.data.DataLoader(
        test_dataset,
        batch_size=kwargs.get('test_batch_size', 100),
        shuffle=False,
        num_workers=kwargs.get('workers', 4),
        pin_memory=True,
        sampler=test_sampler,
        worker_init_fn=_worker_init_fn)

    return train_loader, test_loader, train_sampler, test_sampler


def get_mnist_iterators(batch_size, **kwargs):

    base_transforms = [
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.reshape(-1, ))]

    train_dataset = ds.MNIST(
        '/tmp/mnist/train',
        train=True,
        download=True,
        transform=transforms.Compose(base_transforms))

    test_dataset = ds.MNIST(
        '/tmp/mnist/test',
        train=False,
        download=True,
        transform=transforms.Compose(base_transforms))

    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=kwargs.get('workers', 4),
        pin_memory=True,
        sampler=None)

    test_loader = torch.utils.data.DataLoader(
        test_dataset,
        batch_size=kwargs.get('test_batch_size', 100),
        shuffle=True,
        num_workers=kwargs.get('workers', 4),
        pin_memory=True,
        sampler=None)

    return train_loader, test_loader


def parse_args() -> Namespace:
    parser = ArgumentParser()
    parser.add_argument('--local_rank',
                            type=int,
                            default=0,
                            help="Is being set by the pytorch distributed launcher")

    parser.add_argument('--parallel',
                        default=False,
                        action='store_true')

    hps = parser.parse_args()
    return hps


def train(hps: Namespace):

    if hps.parallel:
        train_loader, test_loader, _, _ = get_distributed_mnist_iterators(
            batch_size=32)
    else:
        train_loader, test_loader = get_mnist_iterators(
            batch_size=32)

    model = FFN()
    model.cuda()
    if hps.parallel:
        model = nn.parallel.DistributedDataParallel(model)
    crit = nn.MSELoss()

    opt = torch.optim.Adam(model.parameters(), lr=1e-4)
    for epoch in range(100):
        for step, (b, lbl) in enumerate(train_loader):

            model.train()
            opt.zero_grad()
            model.zero_grad()
            corrupt_b = (b + 0.3 * torch.randn_like(b)).cuda()
            recons = model(corrupt_b)
            loss = crit(recons, b.cuda())
            loss.backward()
            opt.step()

            if dist.get_rank() == 0:
                if step % 10 == 0:
                    print(f'epoch {epoch}, batch: {step}, loss: {float(loss.cpu())}')


def setup():
    hps = parse_args()
    dist.init_process_group(backend='nccl', init_method=f'env://', rank=hps.local_rank)

    size = dist.get_world_size()
    group = torch.distributed.new_group(ranks=list(range(size)))
    return group, hps


if __name__ == "__main__":
    group, hps = setup()
    train(hps)
```

## Expected behavior

Expect either command to work independent of using `DistributedDataParallel` or not.

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.11.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] pytorch-memlab==0.0.3
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] pytorch-memlab            0.0.3                    pypi_0    pypi
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi
```

**Comment by mrshenli** [comment]
@jotterbach We haven't tested `DistributedDataParallel` on calling `autograd.grad` in forward yet. Does it work if  `checkpoint_sequential` is not involved?

CC @pietern

**Comment by jotterbach** [comment]
@mrshenli , it seems it doesn't work without the checkpoint either. Just changed the relevant line in the code so that the `FFN` looks like

```
class FFN(nn.Module):

    def __init__(self):
        super(FFN, self).__init__()
        self.n_hidden = 1024
        self._energy = nn.Sequential(
            nn.Linear(28**2, self.n_hidden),
            nn.LeakyReLU(),
            nn.Linear(self.n_hidden, self.n_hidden),
            nn.LeakyReLU(),
            nn.Linear(self.n_hidden, self.n_hidden),
            nn.LeakyReLU(),
            nn.Linear(self.n_hidden, 1))
        self.L = 10

    def forward(self, x: torch.Tensor):
        y = x.clone().to(x.device)
        y.requires_grad_()
        fwd = nn.Sequential(*[GradientStep(self._energy) for _ in range(self.L)])
        y = fwd(y)
        return y
```
The error message changes though and now looks like:

```
Traceback (most recent call last):
  File "minimal_buggy_2.py", line 198, in <module>
    train(hps)
  File "minimal_buggy_2.py", line 177, in train
    recons = model(corrupt_b)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 392, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You
 can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wa
sn't able to locate the output tensors in the return value of your module's `forward` function. Please include the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (pre
pare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:408)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f0ee54bc441 in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f0ee54bbd7a in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x5ec (0x7f0f24f81abc in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x6c753d (0x7f0f24f7753d in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x130fac (0x7f0f249e0fac in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyMethodDef_RawFastCallKeywords + 0x264 (0x560a143c76e4 in /opt/conda/bin/python)
frame #6: _PyCFunction_FastCallKeywords + 0x21 (0x560a143c7801 in /opt/conda/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x537e (0x560a144237ae in /opt/conda/bin/python)
frame #8: _PyEval_EvalCodeWithName + 0x2f9 (0x560a143644f9 in /opt/conda/bin/python)
frame #9: _PyFunction_FastCallDict + 0x1d5 (0x560a143655d5 in /opt/conda/bin/python)
frame #10: _PyObject_Call_Prepend + 0x63 (0x560a1437cc43 in /opt/conda/bin/python)
frame #11: PyObject_Call + 0x6e (0x560a1437195e in /opt/conda/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x1e20 (0x560a14420250 in /opt/conda/bin/python)
frame #13: _PyEval_EvalCodeWithName + 0x2f9 (0x560a143644f9 in /opt/conda/bin/python)
frame #14: _PyFunction_FastCallDict + 0x1d5 (0x560a143655d5 in /opt/conda/bin/python)
frame #15: _PyObject_Call_Prepend + 0x63 (0x560a1437cc43 in /opt/conda/bin/python)
frame #16: <unknown function> + 0x17116a (0x560a143bf16a in /opt/conda/bin/python)
frame #17: _PyObject_FastCallKeywords + 0x49b (0x560a143c7d2b in /opt/conda/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x4bf6 (0x560a14423026 in /opt/conda/bin/python)
frame #19: _PyFunction_FastCallKeywords + 0xfb (0x560a143c679b in /opt/conda/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x416 (0x560a1441e846 in /opt/conda/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x560a143644f9 in /opt/conda/bin/python)
frame #22: PyEval_EvalCodeEx + 0x44 (0x560a143653c4 in /opt/conda/bin/python)
frame #23: PyEval_EvalCode + 0x1c (0x560a143653ec in /opt/conda/bin/python)
frame #24: <unknown function> + 0x22f874 (0x560a1447d874 in /opt/conda/bin/python)
frame #25: PyRun_FileExFlags + 0xa1 (0x560a14487b81 in /opt/conda/bin/python)
frame #26: PyRun_SimpleFileExFlags + 0x1c3 (0x560a14487d73 in /opt/conda/bin/python)
frame #27: <unknown function> + 0x23ae5f (0x560a14488e5f in /opt/conda/bin/python)
frame #28: _Py_UnixMain + 0x3c (0x560a14488f7c in /opt/conda/bin/python)
frame #29: __libc_start_main + 0xf0 (0x7f0f31e65830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #30: <unknown function> + 0x1e0122 (0x560a1442e122 in /opt/conda/bin/python)
```

**Comment by mrshenli** [comment]
@jotterbach Can you try if setting `find_unused_parameters=True` in `DistributedDataParallel` constructor work? I wouldn't be surprised if it also fails (we haven't discussed supporting autograd.grad in forward call when designing the new DDP reducer), but we will look into it to see how to support this use case.

**Comment by jotterbach** [comment]
@mrshenli sure thing! Following outcomes:

- `find_unused_parameters=True` and **no** checkpoint works!
- `find_unused_parameters=True` and **with** checkpoint fails with the error message
```
Traceback (most recent call last):
  File "minimal_buggy_2.py", line 198, in <module>
    train(hps)
  File "minimal_buggy_2.py", line 179, in train
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 99, in backward
    torch.autograd.backward(outputs, args)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected to mark a variable ready only once. This error is caused by use of a module parameter outside the `forward` function. The return value of the `forward` function is inspected by the distributed data parallel wrapper to figure out if any of the module's parameters went unused. If this is the case, it knows they won't receive gradients in a backward pass. If any of those parameters are then used outside `forward`, this error condition is triggered. You can disable unused parameter detection by passing the keyword argument `find_unused_parameters=False` to `torch.nn.parallel.DistributedDataParallel`.
```

**Comment by mrshenli** [comment]
@jotterbach Thanks for reporting this. I confirm I can reproduce this locally. I think the problem with `checkpoint` in DDP is that `checkpoint` hides the real autograd graph been executed. In this case, there are 10 `FFN` stacked together. The `DistributedDataParallel.backward()` will trigger 10 forward-backward passes on the same `FFN` model. This happens inside DDP so no `prepare_for_backward` will be invoked. As a result `accumulate_grad` hook on the same parameter will be invoked 10 times, and thus hit that error.  

And there might be another problem with unused parameters. The autograd graph saw by DDP (by walking the autograd graph from outputs) contains 10 `CheckpointFunction`s (this is where the real autograd graph is hidden). I would assume that `CheckpointFunction` does not have an edge pointing to the original model parameters? If so, DDP [Reducer](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/reducer.cpp#L551-L575)  will treat those model parameters as used, and mark them as ready. Later, when the forward-backward is run within `CheckpointFunction`, those parameters will be marked as ready again, which can also trigger this error. (not 100% sure on this)

A wild attempt might be wrapping DDP's forward-backward with a `no_sync` context, which prevents DDP from apply grad reduction, and will accumulate grads locally. Then after exiting that `no_sync` context, do another dummy DDP forward-backward just to kick off the grad reduction. I haven't tried this yet.

cc @pietern Do you see if there is anything that we can do to support `checkpoint` in DDP?

**Comment by mrshenli** [comment]
Hi @jotterbach, 

@pietern has a suggestion on a work around for using checkpoint with DDP. We should be able to make it work if we delay the gradient reduction after the entire backward pass is done on all DDP processes, which would be similar to the [`delay_allreduce` mode in apex](https://github.com/NVIDIA/apex/blob/master/apex/parallel/distributed.py#L165). However, this will have some negative impact on performance as we can no longer overlap backward pass with reduction calls.  Does this sounds OK to you?

**Comment by saareliad** [comment]
+1, Got the same problem.

I checked and also got these:
> * `find_unused_parameters=True` and **no** checkpoint works!
> * `find_unused_parameters=True` and **with** checkpoint fails with the error message

BTW I get it on one a server with Titan-Vs but on another server with Titan-Xps I didn't. weird. 
Will try to reproduce this tomorrow.

**Comment by jotterbach** [comment]
@mrshenli I'd be happy to take that performance hit. Is this easily fixable using a `barrier()` in my code or is there more that needs to be done?

**Comment by mrshenli** [comment]
@jotterbach It would require adding a `delay_allreduce` arg to `DistributedDataParallel` constructor. Then in `reducer.cpp`, it should ignore backward hooks on params when `delay_allreduce=True`, and enqueue a bulk grad reduction callback to run after the entire backward pass is done. I will be working on it this Friday.

**Comment by lydials** [comment]
I meet the same problem, too. It occurs in retina net, where the same head is used for several feature maps.

**Comment by mrshenli** [comment]
Hey @jotterbach, @saareliad, @lydials

Could you please help to try if #24800 solves the problem (still WIP, early feedbacks are appreciated)? You can enable the new mode by setting `delay_allreduce=True` in DDP constructor. I converted @jotterbach's repro into a test, and seems working for me locally, but I haven't tested extensively.

**Comment by jotterbach** [comment]
@mrshenli Happy to give it a spin and see if it fixes the bug on my end and if I can integrate it into the larger code. Is there a pre-compiled binary or do I need to compile it myself?

**Comment by mrshenli** [comment]
@jotterbach Thanks! You will need to fetch the pull request and compile from source. I noticed there are some test failures on that PR. Let me fix those first.

**Comment by mrshenli** [comment]
@jotterbach Tests for #24800 look good now.

**Comment by jotterbach** [comment]
@mrshenli I was able to check out the branch and build from source
```running install_egg_info
running egg_info
creating torch.egg-info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing entry points to torch.egg-info/entry_points.txt
writing top-level names to torch.egg-info/top_level.txt
writing manifest file 'torch.egg-info/SOURCES.txt'
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
Copying torch.egg-info to /opt/conda/lib/python3.7/site-packages/torch-1.3.0a0+d3b96c9-py3.7.egg-info
running install_scripts
Installing convert-caffe2-to-onnx script to /opt/conda/bin
Installing convert-onnx-to-caffe2 script to /opt/conda/bin```

and pip list shows the right version. However, my version of torchvision doesn't seem to match the build

```Traceback (most recent call last):
  File "minimally_buggy_2.py", line 9, in <module>
    import torchvision.datasets as ds
  File "/opt/conda/lib/python3.7/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/opt/conda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/opt/conda/lib/python3.7/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /opt/conda/lib/python3.7/site-packages/torchvision/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE```

And trying to upgrade torchvision seems to downgrade the custom build to torch1.2.0. Any advice how to resolve the version matching so I can test?

**Comment by mrshenli** [comment]
> And trying to upgrade torchvision seems to downgrade the custom build to torch1.2.0.

Hi @jotterbach, by upgrade do you mean build from torchvision [source](https://github.com/pytorch/vision) as well?

@fmassa @soumith 
Is torchvision build somehow bound to PyTorch v1.20?

**Comment by jotterbach** [comment]
@mrshenli I complied torchvision now from source and the versions seem compatible then.
Happy to report that the fix works on the minimal example provided above and on the larger/messier code I work with. Thank you a lot!

**Comment by mrshenli** [comment]
@jotterbach Awesome! Thanks for trying it out!!

**Comment by mrshenli** [comment]
Hey @jotterbach 

Unfortunately, although the training does not crash anymore with #24800, it does not guarantee the numerical correctness, because the final callback I used to sync gradients does not work properly with reentrant backwards (backward in backward, as `checkpoint_sequential` does). We might need some change to the autograd engine to make it work. I created #24965 to track it, and will report back when we get it resolved.

**Comment by mrshenli** [comment]
@jotterbach Before #24965 and #24800 are addressed, you could try the following temporary solution (instead of using DDP) to get unblocked:

1. Each process run forward locally.
2. Each process run backward locally.
3. All processes use [c10d `all_reduce`](https://github.com/pytorch/pytorch/blob/da10614c3b654beea1106415ad9e3efc541f4d48/torch/distributed/distributed_c10d.py#L868) to collectively reduce gradients.
4. Each process run optimizer step locally to update params.

This is similar to what DDP `delay_allreduce` mode would do (but no bucketing optimization though).

**Comment by jotterbach** [comment]
Thanks for the update @mrshenli . I will give this a try and report back when I run into any problems!

**Comment by kiddie92** [comment]
maybe you can try with "apex.parallel DDP"

**Comment by ajtao** [comment]
@mrshenli I see that you're working on the delay allreduce feature. Is that something that's possible to try out at this point?

**Comment by mrshenli** [comment]
Hey @ajtao, sorry that I missed the question. Yes,  #35083 should be working now. We tested it internally. One thing I want to mention is that, as the `delay_allreduce` flag is actually mutual exclusive with `find_unused_parameters`, we need to some revamp to consolidate this two. There is an ongoing effort on modularizing DDP, we plan to absorb this issue into that project. I will post an RFC later this week about the modularizing DDP project.

So, for short term, #35083 should be able to unblock this issue, but that won't be the final API. The DDP revamp would take longer time to deliver.

**Comment by LvanderGoten** [comment]
Is there any progress? I guess most users that use gradient checkpointing also use DDP.

**Comment by neonbjb** [comment]
I'd love to hear of any progress too. This bug pretty much kills multi-GPU processing for me with `number_gpus` < 3. This is because gradient_checkpointing backwards passes are significantly more performant than non checkpointing passes on consumer GPUs. As a result I get numbers like this:

Baseline, no gradient_checkpointing: 1.0it/s
1 GPU, gradient_checkpointing: 1.6s/it
2 GPU, no gradient_checkpointing: 1.8s/it

As a result, it makes very little sense to involve a second GPU until the performance gap widens a bit.

If there has been no progress on this bug, I would be interested in looking into a solution as a PR.

**Comment by min-xu-ai** [comment]
@neonbjb very interesting numbers! What do you mean "consumer GPUs"? Why would that matter for gradient checkpointing?

FWIW, this test file contains various cases you can use checkpointing with DDP, including that cases it work and the cases it doesn't. https://github.com/facebookresearch/fairscale/blob/master/tests/nn/pipe/test_checkpoint_ddp.py

Again, I'd love to know more details about your performance observations, esp. consumer GPUs vs. server GPUs. Maybe it is because consumer GPUs have slower networking (lack of nvlink?) and running at higher clock rate (so faster compute)?

**Comment by neonbjb** [comment]
By "consumer GPUs" I mean GeForce GPUs meant for gaming, which have GDDR6 or GDDR6X memory. I believe the reason for the performance boosts in these GPUs is that they have compute on par with server-grade GPUs but much slower memory. This makes it so that it is actually faster to re-compute many operations than it is to retrieve them from memory.

I've been meaning to do a writeup on this to "stir the pot" and hopefully get this bug bumped in priority for awhile. It is not hard to test, and you can reproduce it on very simple models like GPT or Resnet. I'll try to get to that ASAP..

**Comment by zhaojuanmao** [comment]
@neonbjb as @min-xu-ai mentioned, DDP works with checkpointing for basic cases, only failed for two cases:  1) multiple backward passes for the same check-pointed models (e.g. you checkpoint same model multiple times),  2) set find_unused_parameter = true. you do not have to set it as true if your model train all parameters. 

which failure case did your code fall in?

**Comment by neonbjb** [comment]
I'm in the find_unused_parameter=true case currently. The networks I am working on are GANs, so one network always has grad turned off in the backward pass, which necessitates that setting (correct me if I'm wrong).

I will give DDP+checkpointing a try the next time I am out of this environment. This is good to know.

**Comment by min-xu-ai** [comment]
You can either try ddp.no_sync() workaround with checkpointing and reduce the gradients yourself or maybe checkout the sharded ddp from fairscale. Benjamin at fairscale might be able to help.

I have used ddp.no_sync myself with good results. One nice thing there is that you can hack the ddp source and avoid initializing the reducer, which saves memory from a copy of the gradients (ddp buckets). That extra memory can be used to translate into bigger batch size, which can improve your speed.

**Comment by neonbjb** [comment]
Thanks a ton @min-xu-ai I will try both. The fairscale stuff looks really intriguing, I have some reading to do..

**Comment by visionscaper** [comment]
@min-xu-ai Could you elaborate on both points (Combining ddp.no_sync() + reduce gradients manually, and "hack the ddp source and avoid initializing the reducer")

I guess your first point is something like this?
```
init_process_group(...)

# No gradient sync
with ddp.no_sync():
    model = MyModel(...)
    model(inputs).sum().backward()
    works = []

# Manual sync
for p in model.parameters():
    # to speed it up, you can also organize grads to larger buckets to make allreduce more efficient
    works.append(dist.all_reduce(p.grad, async_op=True))

for work in works:
    work.wait()
...
```

(Pseudo-code adopted from @mrshenli, [here](https://github.com/pytorch/pytorch/issues/43135#issuecomment-676852360))

What about your second point?
