### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#24085]
I install pytorch(1.1.0) from source, I want to upgrade to 1.2.0 by pip, report error.

```
# command
pip install -U torch torchvision

# error info
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting torch
  Downloading https://mirrors.aliyun.com/pypi/packages/05/65/5248be50c55ab7429dd5c11f5e2f9f5865606b80e854ca63139ad1a584f2/torch-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (748.9MB)
     |████████████████████████████████| 748.9MB 10.6MB/s 
Collecting torchvision
  Downloading https://mirrors.aliyun.com/pypi/packages/51/83/2d77d040e34bd8f70dcb4770f7eb7d0aa71e07738abf6831be863ade00db/torchvision-0.4.0-cp37-cp37m-manylinux1_x86_64.whl (8.8MB)
     |████████████████████████████████| 8.8MB 11.8MB/s 
Requirement already satisfied, skipping upgrade: numpy in /home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages (from torch) (1.16.4)
Requirement already satisfied, skipping upgrade: pillow>=4.1.1 in /home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/Pillow-6.0.0-py3.7-linux-x86_64.egg (from torchvision) (6.0.0)
Requirement already satisfied, skipping upgrade: six in /home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/six-1.12.0-py3.7.egg (from torchvision) (1.12.0)
Installing collected packages: torch, torchvision
  Found existing installation: torch 1.2.0a0+887ecf7
    Uninstalling torch-1.2.0a0+887ecf7:
      Successfully uninstalled torch-1.2.0a0+887ecf7
  Found existing installation: torchvision 0.3.0a0+ec20315
    Uninstalling torchvision-0.3.0a0+ec20315:
      Successfully uninstalled torchvision-0.3.0a0+ec20315
Successfully installed torch-1.2.0 torchvision-0.4.0
Traceback (most recent call last):
  File "/home/xtz/anaconda3/envs/pytorch_cp37/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 227, in main
    timeout=min(5, options.timeout)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 92, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_internal/download.py", line 380, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_internal/download.py", line 160, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 889, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1974, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1845, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1722, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1679, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision-0.3.0a0+ec20315-py3.7-linux-x86_64.egg'

```

**Comment by soumith** [comment]
it complains that something you installed previously is missing
`FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision-0.3.0a0+ec20315-py3.7-linux-x86_64.egg'`

clean your environment or start fresh
