### ISSUE TITLE
torch.fft crash when used with nn.DataParallel

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#24176]
## 🐛 Bug

Calling `torch.fft` on CUDA tensor in a `nn.DataParallel` wrapped module segfaults.

## To Reproduce

Run the following script on PyTorch master (77c08aa46c3f3460b95b89cbe357b99180bc824d) on a machine with 2 or more GPUs:

```python
import torch
import torch.nn as nn

class FFTSEGV(nn.Module):
    def forward(self, input):
        return torch.fft(input, 2)


model = FFTSEGV()
tensor = torch.rand(4, 3, 2).cuda()

out = model.cuda(0)(tensor.cuda(0))
print(out)

# Uncomment this to avoid segfault.
# Maybe it forces some lazy initialization to happen the correct way...
#out = model.cuda(1)(tensor.cuda(1))
#print(out)

# This segfaults if cuFFT didn't initialize on cuda:1.
dmodel = nn.DataParallel(model)
print(dmodel(tensor))
```

## Expected behavior

It shouldn't crash, but it crashes. Very likely lazy initialization gone wrong.

## Additional context

See https://discuss.pytorch.org/t/pytorch-fft-on-multiple-gpus/43532 for the original report.

**Comment by SsnL** [comment]
Uhh, could be the plan cache..

**Comment by SsnL** [comment]
stack (without debug build)
```
#0  0x00007fffd2f6699e in at::native::_run_cufft(at::native::detail::CuFFTConfig const&, at::Tensor&, long, bool, bool, bool, c10::ArrayRe
f<long>, bool, bool, c10::ArrayRef<long>, bool) () from /data/packages/pytorch/torch/lib/libtorch.so
#1  0x00007fffd2f6887c in at::native::_fft_cufft(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef
<long>) () from /data/packages/pytorch/torch/lib/libtorch.so
#2  0x00007fffd5dca40b in at::CUDAType::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::Ar
rayRef<long>) () from /data/packages/pytorch/torch/lib/libtorch.so
#3  0x00007fffd5693440 in torch::autograd::VariableType::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bo
ol, bool, c10::ArrayRef<long>) () from /data/packages/pytorch/torch/lib/libtorch.so
#4  0x00007fffd3a34c03 in at::native::_fft(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool) () from /data/pack$
ges/pytorch/torch/lib/libtorch.so
#5  0x00007fffd3a37995 in at::native::fft(at::Tensor const&, long, bool) () from /data/packages/pytorch/torch/lib/libtorch.so
#6  0x00007fffd3d7fd2f in at::TypeDefault::fft(at::Tensor const&, long, bool) () from /data/packages/pytorch/torch/lib/libtorch.so
#7  0x00007fffd54232df in torch::autograd::VariableType::fft(at::Tensor const&, long, bool) () from /data/packages/pytorch/torch/lib/libto
rch.so
#8  0x00007fffe89f1861 in torch::autograd::THPVariable_fft () from /data/packages/pytorch/torch/lib/libtorch_python.so

```

**Comment by AppleHolic** [comment]
Hello, is there any progress for solving this problem?

**Comment by edouardoyallon** [comment]
Hi, I'm running in this issue as well https://github.com/kymatio/kymatio/issues/479 .. any updates? thanks!

**Comment by choidongyeon** [comment]
Going off of @AppleHolic 's comment, it seems that there is a reference invalidation in CuFFTPlanCache. After doing some digging, I think [commit 54777b1](https://github.com/pytorch/pytorch/commit/54777b1e736becb12ded6dcf34d9f01d32b4f896) addresses the issue. I am unable to reproduce the original bug that @pietern reported.

**Comment by edouardoyallon** [comment]
Thanks 👍 !
