### ISSUE TITLE
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED during backward()

### ISSUE THREAD

**Issue by rinuboney** [pytorch/pytorch#2419]
I ran into a [problem](https://discuss.pytorch.org/t/unclear-cudnn-runtimeerror-during-backward/6202) when trying to implement some meta-learning algorithms. To summarize what I'm trying to do:

1. Compute the gradients of a model parametrized by `Theta` based on the loss from some training samples.
2.  Compute `Theta_ = Theta - lr*Theta_grad`
3. Compute loss of the model when parametrized by `Theta_` on some test samples.
4. Compute the gradients all the way back to `Theta`

Here is a simple code to reproduce the problem:
```
import torch as th
from torch.autograd import Variable
import torch.nn.functional as F

lr = 0.01
cuda = False

# Parameters
W1 = Variable(th.Tensor(3, 1, 2, 2), requires_grad=True)
W2 = Variable(th.Tensor(2, 3), requires_grad=True)

# Train data
x_1 = Variable(th.FloatTensor([[0.1, 0.2], [0.3, 0.4]])).view(1, 1, 2, 2)
x_2 = Variable(th.FloatTensor([[0.3, 0.6], [0.1, 0.4]])).view(1, 1, 2, 2)

# Test data
y_1 = Variable(th.LongTensor([1]))
y_2 = Variable(th.LongTensor([0]))

if cuda:
    W1, W2 = W1.cuda(), W2.cuda()
    x_1, x_2 = x_1.cuda(), x_2.cuda()
    y_1, y_2 = y_1.cuda(), y_2.cuda()

# Compute loss on train data using W1 and W2
out = F.conv2d(x_1, W1).view(1, -1)
train_output = F.linear(out, W2)
train_loss = F.cross_entropy(train_output, y_1)

# Compute gradients of W1 and W2
W1_grad, W2_grad = th.autograd.grad(train_loss, [W1, W2], create_graph=True)

# Compute W*_ based on W* and W*_grad
W1_ = W1 - lr*W1_grad
W2_ = W2 - lr*W2_grad

# Compute loss on test data using W1 and W2
out = F.conv2d(x_2, W1_).view(1, -1)
test_output = F.linear(out, W2_)
test_loss = F.cross_entropy(test_output, y_2)

# Compute gradients of W1 and W2 based on the test loss
test_loss.backward()
```

This code works when I run it on CPU ie., `cuda=False`, but fails with the following error when I run it on my GPU ie., `cuda=True`:
```
Traceback (most recent call last):
  File "main_f.py", line 260, in <module>
    test_loss.backward()
  File "/home/lib/python3.5/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/lib/python3.5/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

**Comment by zou3519** [comment]
This works on master. I think https://github.com/pytorch/pytorch/pull/3148 fixed it.
