### ISSUE TITLE
JIT infers List[Tensor] inccorectly to List[int]

### ISSUE THREAD

**Issue by moskomule** [pytorch/pytorch#24239]
## To Reproduce

```python
def channel(tensor: torch.Tensor) -> torch.Tensor:
    a = torch.randn(2)
    return a[tensor.long()]

@torch.jit.script
def full():
    torch.stack([channel(torch.randn(1, 3, 3) > 0) for _ in [0, 1, 2]])
```

This code throws an error below:

```bash
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    @torch.jit.script
  File "/opt/.miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "/opt/.miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
RuntimeError:
Arguments for call are not valid.
The following operator variants are available:

  aten::stack(Tensor[] tensors, int dim=0) -> (Tensor):
  Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'List[int]'.

  aten::stack(Tensor[] tensors, int dim=0, *, Tensor(a) out) -> (Tensor(a)):
  Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'List[int]'.

The original call is:
at test.py:10:5
@torch.jit.script
def full():
    torch.stack([channel(torch.randn(1, 3, 3) > 0) for _ in [0, 1, 2]])
    ~~~~~~~~~~~ <--- HERE
```

The equivalent code below works as expected

```python
def channel(tensor: torch.Tensor) -> torch.Tensor:
    a = torch.randn(2)
    return a[tensor.long()]

@torch.jit.script
def full():
    l = []
    for _ in range(3):
        l.append(channel(torch.randn(1, 3, 3) > 0))
    torch.stack(l)
````

## Expected behavior

`[channel(torch.randn(1, 3, 3) > 0) for _ in [0, 1, 2]]` is expected to be `List[Tensor]` but is inferred as `List[int]` by JIT.

## Environment

* Ubuntu 16.04/MacOS Mojave
* Python 3.7.4 (from conda)
* PyTorch 1.2.0 (from conda)

**Comment by driazati** [comment]
Looks like something is messed up in the list comprehension code,

This returns `List[int]`
```python
@torch.jit.script
def full():
    return [torch.randn(2) for _ in [0, 1, 2]]
```

But this returns `List[Tensor]` (which is correct)
```python
@torch.jit.script
def full():
    return [torch.randn(2)]
```

**Comment by eellison** [comment]
@Krovatkin this is the same list comprehension issue as earlier

**Comment by eellison** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/24271
