### ISSUE TITLE
test_fq_module is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#24265]
```
Aug 13 18:03:06 ======================================================================
Aug 13 18:03:06 FAIL: test_fq_module (__main__.TestFakeQuantizePerTensorAffine)
Aug 13 18:03:06 ----------------------------------------------------------------------
Aug 13 18:03:06 Traceback (most recent call last):
Aug 13 18:03:06   File "test_fake_quant.py", line 101, in test_fq_module
Aug 13 18:03:06     @given(device=st.sampled_from(['cpu', 'cuda'] if torch.cuda.is_available() else ['cpu']),
Aug 13 18:03:06   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 975, in wrapped_test
Aug 13 18:03:06     state.run()
Aug 13 18:03:06   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 703, in run
Aug 13 18:03:06     info.__expected_traceback,
Aug 13 18:03:06   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 570, in execute
Aug 13 18:03:06     result = self.test_runner(data, run)
Aug 13 18:03:06   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
Aug 13 18:03:06     return function(data)
Aug 13 18:03:06   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 568, in run
Aug 13 18:03:06     return test(*args, **kwargs)
Aug 13 18:03:06   File "test_fake_quant.py", line 123, in test_fq_module
Aug 13 18:03:06     np.testing.assert_allclose(dX.cpu(), X.grad.cpu().detach().numpy(), rtol=tolerance, atol=tolerance)
Aug 13 18:03:06   File "/opt/conda/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
Aug 13 18:03:06     verbose=verbose, header=header, equal_nan=equal_nan)
Aug 13 18:03:06   File "/opt/conda/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
Aug 13 18:03:07     raise AssertionError(msg)
Aug 13 18:03:07 AssertionError: 
Aug 13 18:03:07 Not equal to tolerance rtol=1e-06, atol=1e-06
Aug 13 18:03:07 
Aug 13 18:03:07 Mismatch: 50%
Aug 13 18:03:07 Max absolute difference: 0.51895916
Aug 13 18:03:07 Max relative difference: 1.
Aug 13 18:03:07  x: array([0.      , 0.206555], dtype=float32)
Aug 13 18:03:07  y: array([0.518959, 0.206555], dtype=float32)
Aug 13 18:03:07 
```

https://circleci.com/gh/pytorch/pytorch/2447186?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by raghuramank100** [comment]
This test is now stable. So closing this issue
