### ISSUE TITLE
Convert Caffe2 to ONNX error: AssertionError: type is "ExpandDims"

### ISSUE THREAD

**Issue by Joeywzr** [pytorch/pytorch#24392]
## 🐛 Bug

I have converted the ONNX models to Caffe2 models using `convert-onnx-to-caffe2` and I got `predict_net.pb` and `init_net.pb`. However, when I try to convert the Caffe2 models back to ONNX models, I got the following error message:

```shell
Traceback (most recent call last):
  File "/home/memo/.cache/bazel/_bazel_memo/74d5227f86e9c48dd23510319ac3d793/external/org_pocoo_werkzeug/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/memo/.cache/bazel/_bazel_memo/74d5227f86e9c48dd23510319ac3d793/external/org_pocoo_werkzeug/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/media/memo/Mess/tensorboardplugins-master/tensorboard/backend/application.py", line 349, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/home/memo/.cache/bazel/_bazel_memo/74d5227f86e9c48dd23510319ac3d793/external/org_pocoo_werkzeug/werkzeug/wrappers.py", line 291, in application
    return f(*args[:-2] + (request,))(*args[-2:])
  File "/media/memo/Mess/tensorboardplugins-master/tensorboard/plugins/convert/convert_plugin.py", line 159, in convert_model
    value_info=value_info)
  File "/home/memo/.local/lib/python3.6/site-packages/caffe2/python/onnx/frontend.py", line 350, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/home/memo/.local/lib/python3.6/site-packages/caffe2/python/onnx/frontend.py", line 195, in caffe2_net_to_onnx_graph
    cls._ssa_rewrite(predict_net, init_net, value_info)
  File "/home/memo/.local/lib/python3.6/site-packages/caffe2/python/onnx/frontend.py", line 320, in _ssa_rewrite
    assert re.match('GivenTensor.*Fill', op.type), "type is {}, \n{}".format(op.type, op)
AssertionError: type is ExpandDims, 
input: "497"
output: "499"
name: ""
type: "ExpandDims"
arg {
  name: "dims"
  ints: 0
}

```

Then I replaced the Caffe2 models to the models of https://github.com/caffe2/models and that works fine.

I transformed the .pb to .pbtxt and compared them, then I found that the models in https://github.com/caffe2/models don't have the "ExpandDims" operator. In addition to resnet50, other models have the same error.

So what should I do to solve this problem?

## To Reproduce

1. convert the ONNX models to Caffe2 models using `convert-onnx-to-caffe2`
2. convert the Caffe2 models back to ONNX models using `convert-caffe2-to-onnx` or the code as follows:

```python
source_path_pre = '/home/memo/PycharmProjects/ONNX/resnet50_pre.pb'
source_path_init = '/home/memo/PycharmProjects/ONNX/resnet50_init.pb'
destination_path = '/home/memo/PycharmProjects/ONNX/resnet50.onnx'

data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 224, 224)
value_info = {
    'data': (data_type, data_shape)
}

predict_net = caffe2_pb2.NetDef()
with open(source_path_pre, "rb") as predict_stream:
    predict_net.ParseFromString(predict_stream.read())
if predict_net.name == '':
	predict_net.name = 'modelName'

init_net = caffe2_pb2.NetDef()
with open(source_path_init, "rb") as init_stream:
	init_net.ParseFromString(init_stream.read())


onnx_model = c2_onnx.caffe2_net_to_onnx_model(predict_net=predict_net,
                                              init_net=init_net,
                                              value_info=value_info)
with open(destination_path, 'wb') as f:
	f.write(onnx_model.SerializeToString())

```

**note**: I followed the code in the instructions on https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb. 

## Expected behavior

Convert Caffe2 back to ONNX successfully

## Environment

```json
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Deepin 15.11
GCC version: (Debian 4.8.5-4) 4.8.5
CMake version: version 3.11.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: GeForce GTX 970M
Nvidia driver version: 390.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.2.0
[conda] torch                     1.1.0                     <pip>
```

**Comment by xkszltl** [comment]
This is not an official answer but I think it's one of those "unsupported" ops.
If so you may need to write it.
I did this for `MergeDim` with `Reshape`+`Squeeze` a while ago, you could probably do something similar with `Unsqueeze`: https://github.com/pytorch/pytorch/pull/16189

And here's the thread about ExpandDims/Unsqueeze in onnx repo: https://github.com/onnx/onnx/issues/494

**Comment by garymm** [comment]
Caffe2 is not being developed anymore so this is unlikely to get fixed.
