### ISSUE TITLE
SyncBatchNorm error when using model.eval() with DistributedDataParallel

### ISSUE THREAD

**Issue by superkoma** [pytorch/pytorch#24397]
## 🐛 Bug

```
Traceback (most recent call last):
  File "train.py", line 977, in <module>
    main()
  File "train.py", line 97, in main
    main_worker(ngpus_per_node, args, options)
  File "train.py", line 742, in main_worker
    total_loss.backward()
  File "/mnt/lustre/matao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/lustre/matao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64]] is at version 1423; expected version 1420 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```
## To Reproduce

1. Use `nn.SyncBatchNorm.convert_sync_batchnorm(model)` to convert the nn.BatchNorm2d to SyncBatchNorm2d layer;
2. Use `torch.nn.parallel.DistributedDataParallel(model.cuda(args.gpu), device_ids=[args.gpu], find_unused_parameters=True)` to wrap the model;
3. Start training, e.g., 100 epochs;
4. At 40th epoch, I use `model.eval()` to fix the parameters of Batchnorm layer, and continue to train other parameters of model, and the error happens now.

Brief code for the clear representation:
```
import torch.multiprocessing as mp
import torch.distributed as dist
import torch.nn as nn

dist.init_process_group(backend='nccl', init_method=args.dist_url,
                                world_size=world_size, rank=rank)

model = nn.SyncBatchNorm.convert_sync_batchnorm(model)

model = torch.nn.parallel.DistributedDataParallel(model.cuda(args.gpu), device_ids=[args.gpu], find_unused_parameters=True)

train_sampler = torch.utils.data.distributed.DistributedSampler(train_dset)

model.train()
for epoch in range(0, epochs):
    if epoch >= 40 and model.training:
        model.eval()
    loss.back_ward()

```

 - PyTorch Version: 1.1
 - OS: Linux
 - How you installed PyTorch: conda
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

I fix batchnorm layer at 40th epoch for the better performance of my model's training. And this will work when I use `nn.Dataparallel()` on single node multi gpus, but it doesn't work as I mentioned above on multi nodes multi gpus. And I'm sure the error is caused by setting `model.eval()`, is this the conflict between `SyncBatchNorm` and `model.eval()`?

**Comment by zou3519** [comment]
It's hard to tell what's going on without the module source code. It would be much easier for us to help out if you could post a minimal repro.

**Comment by superkoma** [comment]
> It's hard to tell what's going on without the module source code. It would be much easier for us to help out if you could post a minimal repro.

Thanks for your advice and I have made a minimal project (only L1 loss for image generation task, remove GAN loss) and found the problem doesn't exit. So it may not be the conflict between SyncBatchNorm and model.eval(). I will continue to do some experiments to find the problem and open the minimal repo if necessary.

**Comment by yshvrdhn** [comment]
If you are putting the model to eval mode, I think you should put your model under torch.no_grad() so that it does not wait for the gradients to be calculated for that particular.

**Comment by JialeTao** [comment]
> > It's hard to tell what's going on without the module source code. It would be much easier for us to help out if you could post a minimal repro.
> 
> Thanks for your advice and I have made a minimal project (only L1 loss for image generation task, remove GAN loss) and found the problem doesn't exit. So it may not be the conflict between SyncBatchNorm and model.eval(). I will continue to do some experiments to find the problem and open the minimal repo if necessary.

Hi, how do you solve this? I met the same problem whenm set model.eval() with DistributedDataParallel of pytorch1.5.

**Comment by TropComplique** [comment]
Hi. I have the same problem when using pytorch 1.7.1.

Here is the code to reproduce the problem:
```python
import os
import torch
import torch.nn as nn

import torch.distributed as dist
import torch.multiprocessing as mp


NUM_GPUS = 2
IS_TRAIN = False
# everything works when IS_TRAIN is True


class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()

        self.conv = nn.Conv2d(32, 32, 1, bias=False)
        self.norm = nn.SyncBatchNorm(32)
        self.relu = nn.ReLU(inplace=False)

    def forward(self, x):
        x = self.conv(x)
        x = self.norm(x)
        x = self.relu(x)
        return x


def worker(rank):

    torch.cuda.set_device(rank)
    device = torch.device(rank)
    dist.init_process_group(backend='nccl', world_size=NUM_GPUS, rank=rank)

    torch.autograd.set_detect_anomaly(True)
    model = Model().to(device).train(IS_TRAIN)
    model = nn.parallel.DistributedDataParallel(model, device_ids=[rank])

    x1 = torch.randn(16, 32, 128, 128, device=device)
    x2 = torch.randn(16, 32, 128, 128, device=device)

    y = model(x1) + model(x2)  # error is here
    # y = model(x1)  # everything works here
    loss = y.sum()
    loss.backward()


def main():
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    mp.spawn(worker, nprocs=NUM_GPUS, args=())


if __name__ == '__main__':
    main()
```

**Comment by TropComplique** [comment]
Hi @zou3519.
I have posted above a minimal code for the reproduction of the problem (in pytorch 1.7.1 and 1.8.0).

Also this code gives an error:
```python
import os
import torch
import torch.nn as nn

import torch.distributed as dist
import torch.multiprocessing as mp


NUM_GPUS = 1  # everything works when NUM_GPUS > 1
IS_TRAIN = True


class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()

        self.conv = nn.Conv2d(32, 32, 1, bias=False)
        self.norm = nn.SyncBatchNorm(32)
        self.relu = nn.ReLU(inplace=False)

    def forward(self, x):
        x = self.conv(x)
        x = self.norm(x)
        x = self.relu(x)
        return x


def worker(rank):

    torch.cuda.set_device(rank)
    device = torch.device(rank)
    dist.init_process_group(backend='nccl', world_size=NUM_GPUS, rank=rank)

    torch.autograd.set_detect_anomaly(True)
    model = Model().to(device).train(IS_TRAIN)
    model = nn.parallel.DistributedDataParallel(model, device_ids=[rank])

    x1 = torch.randn(16, 32, 128, 128, device=device)
    x2 = torch.randn(16, 32, 128, 128, device=device)

    y = model(x1) + model(x2)  # error is here
    # y = model(x1)  # everything works here
    loss = y.sum()
    loss.backward()


def main():
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    mp.spawn(worker, nprocs=NUM_GPUS, args=())


if __name__ == '__main__':
    main()
```

The error is:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32]] is at version 4; expected version 3 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```
