### ISSUE TITLE
torchaudio error

### ISSUE THREAD

**Issue by arijit17** [pytorch/pytorch#24402]
Thanks for introducing torchaudio. 
However, I'm getting an error on Linux, Python 3.5, CUDA 10.
Works OK on Linux, Python 3.5, and CUDA 9.2

Here is the error
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torchaudio/__init__.py", line 8, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torchaudio/functional.py", line 175, in <module>
    @torch.jit.script
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 58, in get_signature
    return parse_type_line(type_line)
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in parse_type_line
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in <listcomp>
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 227, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'
>>>

```

**Comment by soumith** [comment]
open an issue in https://github.com/pytorch/audio
