### ISSUE TITLE
Crashes on torch.cuda.memory_allocated(device)

### ISSUE THREAD

**Issue by hovnatan** [pytorch/pytorch#24463]
## 🐛 Bug

I have two Nvidia cards and after setting in the environment`CUDA_VISIBLE_DEVICES=1`, then running

    import torch                              
                                          
    device = torch.device("cuda:1")           
    print(torch.cuda.memory_allocated(device))
I get

    Traceback (most recent call last):
      File "bug.py", line 4, in <module>
        print(torch.cuda.memory_allocated(device))
      File "/home/hovnatan/miniconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 461, in memory_allocated                                          
       return torch._C._cuda_memoryAllocated(device)
    RuntimeError: 0 <= device && device < device_num INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1565272271120/work/c10/cuda/CUDACachingAllocator.cpp:667, please report a bug to PyTorch. Invalid device argument.

## Environment

    Collecting environment information...
    PyTorch version: 1.2.0
    Is debug build: No
    CUDA used to build PyTorch: 10.0.130

    OS: Ubuntu 16.04.6 LTS
    GCC version: (Ubuntu 8.3.0-16ubuntu3~16.04) 8.3.0
    CMake version: version 3.15.1

    Python version: 3.7
    Is CUDA available: Yes
    CUDA runtime version: 7.5.17
    GPU models and configuration: 
    GPU 0: GeForce RTX 2080
    GPU 1: GeForce RTX 2080

    Nvidia driver version: 418.56
    cuDNN version: Could not collect

    Versions of relevant libraries:
    [pip] numpy==1.17.0
    [pip] torch==1.2.0
    [pip] torchvision==0.4.0a0+6b959ee
    [conda] mkl                       2019.4                      243  
    [conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
    [conda] torchvision               0.4.0                py37_cu100    pytorch

**Comment by soumith** [comment]
the error message should be improved, but if you do `CUDA_VISIBLE_DEVICES=1`, you only have device 0 available, so doing `cuda:1` will not be valid (only `cuda:0` is valid)

**Comment by StuckinPhD** [comment]
I'm also getting this error.

but i managed to fix it by not specifying any device. For example, instead of using the command:

`torch.cuda.memory_allocated(device=torch.device('cuda:0'))`

I used:

`torch.cuda.memory_allocated()`

it still picks up ``cuda:0``, as thats the only device I have but for some reason if you dont specify the device the command works.

Hope this helped someone :)

**Comment by nflu** [comment]
Quoting from this [reply](https://github.com/pytorch/pytorch/issues/38100#issuecomment-625597025) 
"Once you set CUDA_VISIBLE_DEVICE, user of CUDA (PyTorch in this case) does not see devices outside the specified indices. Moreover, it sees the first in the specified list as device 0, the second as device 1, etc., which means that if CUDA_VISIBLE_DEVICES=3,2,1,0, the user program will in fact use gpu #3 when they ask for device numbered 0. Moreover, the user program will have no way to access devices outside that list."

So the solution is to always refer to devices in the range [0, device_num) in your python code
```
import torch                              
                                      
device = torch.device("cuda:0")           
print(torch.cuda.memory_allocated(device))
```
will refer to card 1 with `CUDA_VISIBLE_DEVICES=1`
