### ISSUE TITLE
[jit] Dict iterator invalidation doesn't match Python

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#24786]
This runs in TorchScript but throws an error in Python

```python
@torch.jit.script
def fn():
    a_dict = {'a': 1, 'b': 2, 'c': 3}
    sum = 0
    for key in a_dict:
        a_dict[str(a_dict[key])] = 1
        sum += a_dict[key]
    return sum

print(fn())
```

It outputs

```
6
```

but should output

```
Traceback (most recent call last):
  File "../test.py", line 15, in <module>
    print(fn())
  File "../test.py", line 10, in fn
    for key in a_dict:
RuntimeError: dictionary changed size during iteration
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
