### ISSUE TITLE
"Shared memory manager connection has timed out"

### ISSUE THREAD

**Issue by willwhitney** [pytorch/pytorch#2482]
This _seems_ to be a new error as of 0.2.0. I'm using a `torch.multiprocessing` Pool via `pool.map`.

```
Process ForkPoolWorker-5:
Traceback (most recent call last):
  File "/home/wwhitney/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/wwhitney/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wwhitney/anaconda3/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/wwhitney/anaconda3/lib/python3.6/multiprocessing/queues.py", line 345, in get
    return _ForkingPickler.loads(res)
  File "/home/wwhitney/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 86, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Shared memory manager connection has timed out at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/libshm/core.cpp:125
```

**Comment by varun19299** [comment]
Anyupdates on this?

I face the same error on pytorch 1.0

**Comment by varun19299** [comment]
Any updates to this? Im on pytorch 1.0

**Comment by yf225** [comment]
@varun19299 Would you like to try PyTorch 1.4 and see if this issue still happens?

**Comment by dreamflasher** [comment]
Pytorch 1.7, still an issue.

**Comment by thunderstudying** [comment]
Maybe lower num_workers may help.

Causation: When memory usage is close to 100%, this Error is likely to occur, so just take care of memory usage can avoid this error.
