### ISSUE TITLE
PyTorch 1.2 'module' object has no attribute 'BFloat16StorageBase'

### ISSUE THREAD

**Issue by in4ight** [pytorch/pytorch#24834]
I installed PyTorch 1.2 from pip:
`pip2 install torch torchvision --user`
Then when I import torch, it got the following error:
`Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/in4ight/.local/lib/python2.7/site-packages/torch/__init__.py", line 228, in <module>
    class BFloat16Storage(_C.BFloat16StorageBase, _StorageBase):
AttributeError: 'module' object has no attribute 'BFloat16StorageBase'
`

**Comment by cpuhrsch** [comment]
@in4ight - could you please provide more information about your environment as detailed in the bug report issue template?

Also, did you uninstall everything beforehand? Did you try this in a clean environment (e.g. a new conda enviornment)?

**Comment by in4ight** [comment]
Environment: 
- PyTorch Version: 1.2
 - OS (e.g., Linux): Linux Mint 18.3 （base： Ubuntu 16.04）
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
 - CUDA/cuDNN version: 10.0/7.5
 - GPU models and configuration: N/A
 - Any other relevant information: 
The first time I posted this issue, I tested on system python2.7 with PyTorch1.2. After that, I installed a new Anaconda2 environment and still got the same AttributeError message. I suppose perhaps I have to reinstall the whole linux system.

**Comment by agiokas-dbg** [comment]
I can confirm the same. It seems to happen on `AWS Deep Learning AMI` which is:
* PyTorch version 1.2.0
* OS Ubuntu 160.4
* Installed using `pip install -r requirements.txt`
* Python version 3.6.6
* CUDA 10 cuDNN 7.0

Below is the actual output:

```python
(venv) ubuntu@ip-XXX:~/data-analytics$ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/data-analytics/venv/lib/python3.6/site-packages/torch/__init__.py", line 228, in <module>
    class BFloat16Storage(_C.BFloat16StorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'BFloat16StorageBase'
```

The exact same code and package runs fine on Ubuntu 18.04 with exactly the same setup!

**Comment by soumith** [comment]
@agiokas-dbg and others.

I suspect that this is because of a duplicate PyTorch install (or related files) lingering somewhere on the file system. 

Can you try `pip uninstall -y torch; pip uninstall -y torch` and then reinstall, and try again?

**Comment by agiokas-dbg** [comment]
HI @soumith yes I can verify this is the case. I didn't have to uninstall torch, all I did was skip the activation script of AWS whicih is shown on start-up.
Upon login I had run:
```
source activate pytorch_p36
```
Which loaded python 3.6.6 and pytorch 1.2.0. Skipping that step and going into my own virtualenv seems to have fixed the problem, although please do bear in mind in my `venv` I am using pytorch 1.1.0. I can try with 1.2.0 just to verify the cause.

**Comment by vkuzmin-uber** [comment]
I meet the same problem with 
```
libc++abi.dylib: terminating with uncaught exception of type pybind11::error_already_set: AttributeError: 'module' object has no attribute 'BFloat16StorageBase'
```

and in my case I don't use "source activate pytorch_p36". Do you have an idea what is the reason of it?

**Comment by policeme** [comment]
I met this, did anybody solve this problem

**Comment by vkuzmin-uber** [comment]
> I met this, did anybody solve this problem

I solved it. I my case appeared I built with one version of libtorch and tried to use with another version of torch package. Just needed to clean files left from previous built. If you observd it, try it with completely new environment where you have no files/state from previos builds

**Comment by policeme** [comment]
@vkuzmin-uber clean the previous file in site-package?

**Comment by vkuzmin-uber** [comment]
in my case I built my project with different versions of libtorch and som files from previose built caused pronlems like this one.

**Comment by policeme** [comment]
I delete all of the previous files in site-package, but it didn't work, so I install the torch 1.1, it work, I don't know why didn't torch 1.2 work

**Comment by agiokas-dbg** [comment]
@policeme I think they are referring to compiling the cxx library, AFAIK python has already packaged them compiled.
