### ISSUE TITLE
[Distance functions] F.pdist backward CUDA invalid configuration

### ISSUE THREAD

**Issue by zudi-lin** [pytorch/pytorch#25045]
## 🐛 Bug

After passing the input through a `torch.nn.functional.pdist` function, the gradient *w.r.t.* to the input can not be correctly calculated on a cuda device.

## To Reproduce
```python
import torch
import torch.nn.functional as F

def test(device, dim=1024):
    x = torch.rand(dim, 4, requires_grad=True).to(device)
    y = torch.ones(dim, 1).to(device)
    vdist = F.pdist(x, 2)
    tdist = F.pdist(y, 1)

    vdist = 1/(1+vdist**2)
    loss = F.binary_cross_entropy(vdist, tdist)
    loss.backward()
    print(x.grad.data)
```

3. When increasing the tensor size and running
```python
test(torch.device('cuda'), dim=4096)
```
the error message is:
```
Traceback (most recent call last):
  File "test_pdist.py", line 16, in <module>
    test(torch.device('cuda'), 4096)
  File "test_pdist.py", line 12, in test
    loss.backward()
  File "/n/home/user/app/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/n/home/user/app/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: invalid configuration argument
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version: **1.2.0**
 - OS (e.g., Linux): **CentOS 7.6.1810 (Core)**
 - How you installed PyTorch (`conda`, `pip`, source): **conda**
 - Build command you used (if compiling from source): N/A
 - Python version: **3.6.7**
 - CUDA/cuDNN version: **V10.0.130**
 - GPU models and configuration: **GeForce GTX 1080**
 - Any other relevant information:

**Comment by SsnL** [comment]
A leaf node that collects gradient: `x = torch.rand(dim, 4, requires_grad=True)`

An intermediate result that does not collect gradient: `x = torch.rand(dim, 4, requires_grad=True).to('cuda')`

Use `x = torch.rand(dim, 4, requires_grad=True, device=device)` instead.

**Comment by AlbertHuyb** [comment]
Another solution can be found [here](https://discuss.pytorch.org/t/grad-is-none-even-when-requires-grad-true/29826): 
If you want to retain those gradients, call `w.retain_grad()` before calling `backward()`.
The result is as follows:

> tensor([[-7.7181e-04,  1.0914e-03,  2.4808e-04, -1.8249e-03],
>         [ 9.2315e-04,  1.4243e-03,  4.7810e-04, -2.3060e-04],
>         [ 1.6089e-03,  7.2334e-04,  1.6088e-03,  2.2344e-04],
>         ...,
>         [ 1.6721e-03, -2.4401e-04,  1.1168e-03,  1.3291e-03],
>         [ 1.4105e-03,  6.3654e-04,  1.3851e-03, -8.1672e-04],
>         [-1.5194e-03, -9.8220e-04, -1.0435e-03, -6.5006e-05]])
> tensor([[ 9.4154e-04, -1.8999e-03, -7.8445e-04,  3.2105e-04],
>         [-1.9154e-03, -8.5609e-05,  9.3095e-04,  6.7951e-04],
>         [ 4.1913e-04, -4.2681e-04,  3.1998e-04, -2.8135e-04],
>         ...,
>         [-1.7634e-03,  2.1089e-04, -4.7719e-04, -1.3069e-03],
>         [-7.2096e-04, -1.1096e-03, -1.3573e-03,  1.0148e-03],
>         [-5.4195e-04,  6.4787e-04,  1.8998e-03, -1.0437e-03]], device='cuda:0')

**Comment by zudi-lin** [comment]
Thanks @SsnL @AlbertHuyb, the first problem that there is no gradient for the input tensor on GPU has been solved. However, I met another problem in the backward pass. When running:
```python
import torch
import torch.nn.functional as F
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: ", device)

dim = 1024
x = torch.rand(dim, 4, requires_grad=True, device=device)
y = torch.ones(dim, 1, requires_grad=False, device=device)
vdist = F.pdist(x, 2)
tdist = F.pdist(y, 1)

vdist = 1/(1+vdist**2)
loss = F.binary_cross_entropy(vdist, tdist)
loss.backward()
print(x.grad.data)
```
the `loss.backward()` works properly and produce:
```
tensor([[-8.7084e-04,  2.3595e-04, -2.6945e-04,  1.4838e-03],
        [ 1.1696e-03, -7.8929e-04, -8.4497e-04, -1.6160e-03],
        [-1.5014e-03,  1.7565e-03,  5.9908e-05,  9.8752e-05],
        ...,
        [ 2.3797e-04, -1.0391e-03, -6.5520e-04, -1.7515e-03],
        [ 1.7547e-03, -1.3912e-03, -4.2819e-04, -1.1457e-04],
        [-9.2908e-04,  2.9623e-04, -1.9417e-03,  8.6289e-04]], device='cuda:0')
```
However, when changing the `dim` to 2048, the result is:
```
Traceback (most recent call last):
  File "test_pdist.py", line 16, in <module>
    test(torch.device('cuda'), 4096)
  File "test_pdist.py", line 12, in test
    loss.backward()
  File "/n/home/user/app/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/n/home/user/app/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: invalid configuration argument
```
Could you please help check this? Thanks again.

**Comment by SsnL** [comment]
@zudi-lin This looks like a CUDA config issue. Can you reproduce this on another CUDA machine?

**Comment by jimmychou0704** [comment]
@SsnL Do we have any updates on this? I am having the same issue if the dimension is larger than about 1450 (didn't check what the precise cut is, but it works if dim is less than 1300).

**Comment by alexeib** [comment]
i am having the same invalid cuda config doing pdist with tensor torch.Size([1870, 512])
also it apparently doesnt support half tensors

**Comment by kleinhenz** [comment]
I also see the same issue if the dimension is larger than about 1450.

**Comment by kleinhenz** [comment]
@SsnL can this be reopened? I can confirm that this is still a problem in 1.4.0.

The following code reliable reproduces the issue. The exact size threshold is 1449. The naive version works fine so it is not a resource issue.

```
import torch
import torch.nn as nn
import torch.nn.functional as F

print(torch.__version__)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
if torch.cuda.is_available(): print(torch.cuda.get_device_name())

def spike():
  N = 1449 # fails

  x0 = torch.rand(N, 3, requires_grad=True, device=device)
  x1 = x0.detach().clone()
  x1.requires_grad=True

  # backwards fails for N > 1448
  d0 = F.pdist(x0)
  l0 = torch.sum(d0) / (0.5 * N * (N - 1))
  l0.backward() 
  print(l0)
  
  # works
  d1 = torch.norm(x1[:, None] - x1, dim=2, p=2.0)
  l1 = torch.sum(d1) / (1.0 * N * (N - 1))
  l1.backward()
  print(l1)

spike()
```

output:

```
1.4.0
cuda:0
Tesla P100-PCIE-16GB
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-8f569d2fda32> in <module>()
     28   print(l1)
     29 
---> 30 spike()

2 frames
/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     97     Variable._execution_engine.run_backward(
     98         tensors, grad_tensors, retain_graph, create_graph,
---> 99         allow_unreachable=True)  # allow_unreachable flag
    100 
    101 

RuntimeError: CUDA error: invalid configuration argument
```

**Comment by ngimel** [comment]
cc @ptrblck @emcastillo. Probably a thing similar to #31167 should be done here. As it stands, it is a resource issue, because likely pdist backward on cuda is very inefficiently implemented.

**Comment by ptrblck** [comment]
#31593 relaxed the condition for the forward and backward passes for `pdist`.
@kleinhenz could you try the nightly binary, please?

@ngimel I agree that the performance could be improved, but we should track in in a separate bug.

**Comment by kleinhenz** [comment]
@ptrblck yes, it does work on nightly. thanks! Probably should have checked that first. Performance does still leave something to be desired compared to the naive solution.

```
1.6.0.dev20200416+cu101
cuda:0
Tesla P100-PCIE-16GB
input size = torch.Size([2000, 3])
pdist elapsed = 32.213985443115234
tensor(0.6534, device='cuda:0', grad_fn=<DivBackward0>)
naive elapsed = 2.1415040493011475
tensor(0.6534, device='cuda:0', grad_fn=<DivBackward0>)
```
