### ISSUE TITLE
RuntimeError: cudaGetLastError() == cudaSuccess INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/cuda/SummaryOps.cu:251, please report a bug to PyTorch. kernelHistogram1D failed

### ISSUE THREAD

**Issue by jianlong-yuan** [pytorch/pytorch#25087]
pytorch 1.2
cuda 10.0

Traceback (most recent call last):
  File "train.py", line 244, in <module>
    main()
  File "train.py", line 161, in train
    intersection, union, _ = intersectionAndUnion(pred, target, args.classes, args.ignore_label)
  File "/data/research/NAS/Darts_SEG4/utils.py", line 244, in intersectionAndUnion
    area_intersection = torch.histc(intersection, bins=K, min=0, max=K - 1)
RuntimeError: cudaGetLastError() == cudaSuccess INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/cuda/SummaryOps.cu:251, please report a bug to PyTorch. kernelHistogram1D failed

**Comment by andreaskoepf** [comment]
@jianlong-yuan Please provide a minimal code sample to reproduce the problem. Otherwise it will not be possible to effectively track down the bug. Please in general use the issue template to report a bug.

Source ref: The assert comes from a [macro](https://github.com/pytorch/pytorch/blob/5254b12002caf44a4df0ec56f6aea83877dd82f7/aten/src/ATen/native/cuda/SummaryOps.cu#L147) that is expanded in [CUDA_tensor_histogram()](https://github.com/pytorch/pytorch/blob/5254b12002caf44a4df0ec56f6aea83877dd82f7/aten/src/ATen/native/cuda/SummaryOps.cu#L190).

**Comment by yangyixiao** [comment]
Hi, I meet the same issue when the tensor("intersection" in this issue) has size 0.

**Comment by Neabfi** [comment]
Hey, I also have the issue when the tensor has size 0. Note that I only have the issue when the tensor is on GPU.

Minimal code to repro:
```
import torch
torch.histc(torch.tensor([]).cuda(), bins=4, min=0, max=1)
```
