### ISSUE TITLE
JIT local type annotations are broken

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#25086]
```
import torch

@torch.jit.script
def foo():
    x : int = 4
    return x

```
```
Traceback (most recent call last):
  File "hi.py", line 3, in <module>
    @torch.jit.script
  File "/scratch/zdevito/pytorch/torch/jit/__init__.py", line 1180, in script
    ast = get_jit_def(obj)
  File "/scratch/zdevito/pytorch/torch/jit/frontend.py", line 170, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/scratch/zdevito/pytorch/torch/jit/frontend.py", line 210, in build_def
    build_stmts(ctx, body))
  File "/scratch/zdevito/pytorch/torch/jit/frontend.py", line 126, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/scratch/zdevito/pytorch/torch/jit/frontend.py", line 126, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/scratch/zdevito/pytorch/torch/jit/frontend.py", line 186, in __call__
    return method(ctx, node)
  File "/scratch/zdevito/pytorch/torch/jit/frontend.py", line 293, in build_AnnAssign
    return Assign(lhs, rhs, the_type)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. torch._C._jit_tree_views.Assign(arg0: List[torch._C._jit_tree_views.Expr], arg1: torch._C._jit_tree_views.Expr)
    2. torch._C._jit_tree_views.Assign(arg0: List[torch._C._jit_tree_views.Expr], arg1: torch._C._jit_tree_views.Expr, arg2: torch._C._jit_tree_views.Expr)

Invoked with: <torch._C._jit_tree_views.Var object at 0x7fc5d766dd88>, <torch._C._jit_tree_views.Const object at 0x7fc5d766dd50>, <torch._C._jit_tree_views.Var object at 0x7fc5d766ddc0>
```

**Comment by Chillee** [comment]
These type annotations don't work in comments either.
