### ISSUE TITLE
TestQuantizedOps.test_adaptive_avg_pool2d is flaky

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#25097]
Due to #25096 , I can only find the following error trace.

```
Aug 23 03:42:23 
Aug 23 03:42:23 ======================================================================
Aug 23 03:42:23 ERROR: test_adaptive_avg_pool2d (__main__.TestQuantizedOps)
Aug 23 03:42:23 ----------------------------------------------------------------------
Aug 23 03:42:23 Traceback (most recent call last):
Aug 23 03:42:23   File "test_quantized.py", line 379, in test_adaptive_avg_pool2d
Aug 23 03:42:23     min_side=1, max_side=10),
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Aug 23 03:42:23     raise the_error_hypothesis_found
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 971, in wrapped_test
Aug 23 03:42:23     state.run()
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 703, in run
Aug 23 03:42:23     info.__expected_traceback,
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 570, in execute
Aug 23 03:42:23     result = self.test_runner(data, run)
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
Aug 23 03:42:23     return function(data)
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 568, in run
Aug 23 03:42:23     return test(*args, **kwargs)
Aug 23 03:42:23   File "test_quantized.py", line 379, in test_adaptive_avg_pool2d
Aug 23 03:42:23     min_side=1, max_side=10),
Aug 23 03:42:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 540, in test
Aug 23 03:42:23     raise DeadlineExceeded(runtime, self.settings.deadline)
Aug 23 03:42:23 hypothesis.errors.DeadlineExceeded: Test took 273.61ms, which exceeds the deadline of 200.00ms
Aug 23 03:42:23 
```

e.g. log: https://circleci.com/gh/pytorch/pytorch/2554740?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @ezyang @gchanan @jerryzh168 @jianyuh @dzhulgakov

**Comment by jianyuh** [comment]
@zafartahirov : Could you take a look at this timeout issue for the quantized avg_pool2d? Maybe reduce the number of tests or the problem sizes?

**Comment by SsnL** [comment]
It happened again:
```
Aug 25 09:48:22 Falsifying example: test_adaptive_avg_pool2d(self=<__main__.TestQuantizedOps testMethod=test_adaptive_avg_pool2d>, X=(array([[[[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]]],
Aug 25 09:48:22  
Aug 25 09:48:22  
Aug 25 09:48:22         [[[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]]],
Aug 25 09:48:22  
Aug 25 09:48:22  
Aug 25 09:48:22         [[[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]]],
Aug 25 09:48:22  
Aug 25 09:48:22  
Aug 25 09:48:22         [[[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]]],
Aug 25 09:48:22  
Aug 25 09:48:22  
Aug 25 09:48:22         [[[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]],
Aug 25 09:48:22  
Aug 25 09:48:22          [[1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.],
Aug 25 09:48:22           [1., 1., 1., 1.]]]], dtype=float32),
Aug 25 09:48:22  (1.6615347966615004e+35, 1, torch.quint8)), output_size_h=3, output_size_w=4)
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 1.934665551544843e-20 from one_of(floats(min_value=0.0, max_value=5.2080147452458e-20), floats(min_value=0.0, max_value=5.2080147452458e-20).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 1.9346656e-20 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 703726417228.1948 from one_of(floats(min_value=0.0, max_value=1099511496704.0156), floats(min_value=0.0, max_value=1099511496704.0156).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 703726400000.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 3.857142187443076e-21 from one_of(floats(min_value=0.0, max_value=6.171333685266585e-20), floats(min_value=0.0, max_value=6.171333685266585e-20).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 3.8571424e-21 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 807531725382.7849 from one_of(floats(min_value=0.0, max_value=1099511496704.0156), floats(min_value=0.0, max_value=1099511496704.0156).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 807531700000.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 2.9999999999999907 from integers(min_value=4613937818241073131, max_value=4613937818241073173).map(lambda x: int_to_float(x, width)) cannot be represented as dtype dtype('float32') - instead it becomes 3.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element -241890593130.49002 from one_of(floats(min_value=0.0, max_value=1099511496704.0156), floats(min_value=0.0, max_value=1099511496704.0156).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes -241890590000.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 245773158086.77988 from one_of(floats(min_value=0.0, max_value=1099511496704.0156), floats(min_value=0.0, max_value=1099511496704.0156).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 245773160000.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 1008963491093.0968 from one_of(floats(min_value=0.0, max_value=1099511496704.0156), floats(min_value=0.0, max_value=1099511496704.0156).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 1008963500000.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element 578415634411.9933 from one_of(floats(min_value=0.0, max_value=1099511496704.0156), floats(min_value=0.0, max_value=1099511496704.0156).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes 578415600000.0 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 25 09:48:22   since="2019-07-28",
Aug 25 09:48:22 ok
Aug 25 09:48:22 
Aug 25 09:48:22 ======================================================================
Aug 25 09:48:22 ERROR: test_adaptive_avg_pool2d (__main__.TestQuantizedOps)
Aug 25 09:48:22 ----------------------------------------------------------------------
Aug 25 09:48:22 Traceback (most recent call last):
Aug 25 09:48:22   File "test_quantized.py", line 379, in test_adaptive_avg_pool2d
Aug 25 09:48:22     min_side=1, max_side=10),
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Aug 25 09:48:22     raise the_error_hypothesis_found
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 971, in wrapped_test
Aug 25 09:48:22     state.run()
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 703, in run
Aug 25 09:48:22     info.__expected_traceback,
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 570, in execute
Aug 25 09:48:22     result = self.test_runner(data, run)
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
Aug 25 09:48:22     return function(data)
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 568, in run
Aug 25 09:48:22     return test(*args, **kwargs)
Aug 25 09:48:22   File "test_quantized.py", line 379, in test_adaptive_avg_pool2d
Aug 25 09:48:22     min_side=1, max_side=10),
Aug 25 09:48:22   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 540, in test
Aug 25 09:48:22     raise DeadlineExceeded(runtime, self.settings.deadline)
Aug 25 09:48:22 hypothesis.errors.DeadlineExceeded: Test took 262.39ms, which exceeds the deadline of 200.00ms
Aug 25 09:48:22 
```

https://circleci.com/gh/pytorch/pytorch/2572825?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
Optimistically closing as fixed thanks to @jerryzh168
