### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at C:/w/1/s/tmp_conda_3.6_041836/conda/conda-bld/pytorch_1556684464974/work/aten/src/THC/THCBlas.cu:259

### ISSUE THREAD

**Issue by linko994** [pytorch/pytorch#25165]
## 🐛 Bug
I get this error when trying to use my network with cuda. 

Full traceback:
Traceback (most recent call last):
  File "F:/Bachelorarbeit/Unity Projekt/ml-agents-master/ml-agents/mlagents/trainers/dqn/dqn.py", line 136, in <module>
    chosen_action = choose_action(state=state, epsilon=epsilon)
  File "F:/Bachelorarbeit/Unity Projekt/ml-agents-master/ml-agents/mlagents/trainers/dqn/dqn.py", line 68, in choose_action
    values = network(state)
  File "C:\Users\mariu\Anaconda3\envs\ml-agents81\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\Bachelorarbeit\Unity Projekt\ml-agents-master\ml-agents\mlagents\trainers\dqn\model.py", line 15, in forward
    x = F.relu(self.fc1(x))
  File "C:\Users\mariu\Anaconda3\envs\ml-agents81\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mariu\Anaconda3\envs\ml-agents81\lib\site-packages\torch\nn\modules\linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\mariu\Anaconda3\envs\ml-agents81\lib\site-packages\torch\nn\functional.py", line 1408, in linear
    output = input.matmul(weight.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at C:/w/1/s/tmp_conda_3.6_041836/conda/conda-bld/pytorch_1556684464974/work/aten/src/THC/THCBlas.cu:259

Environment:

 - PyTorch Version: 1.1
 - OS: Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.0 / 7.6.2.24

**Comment by peterjc123** [comment]
Maybe related to #7548.

**Comment by linko994** [comment]
> Maybe related to #7548.

Can you maybe elaborate on that? I couldn't fix this issue so far.

**Comment by peterjc123** [comment]
Would you please do `network.float()` first before passing in the input?

**Comment by linko994** [comment]
> Would you please do `network.float()` first before passing in the input?

Thanks for the suggestion. Now I don't get that error at choose_action anymore, but the same error at a different point in my code:

File "F:/Bachelorarbeit/Unity Projekt/ml-agents-master/ml-agents/mlagents/trainers/dqn/dqn.py", line 94, in train
    q_values = network(states).gather(1, actions)

This is how I sample my State from Replay Buffer
state = torch.tensor([state], dtype=torch.float, device= device)

This is how the batch is transformed during training (similar to pytorch.org DQN-Tutorial)g
transitions = memory.sample(batch_size)

    batch = Transition(*zip(*transitions))

    states = torch.cat(batch.states)

**Comment by peterjc123** [comment]
Please run the model on CPU first, and you'll get what's wrong there.

**Comment by linko994** [comment]
I wanted to try that, but now it just worked anyway and I have no clue why.

But the thing is: It's actually running a lot slower than before. And it doesn't really matter if I choose "cpu" or "cuda" as device, both are equally slow, while not specifying a device is way way faster.

**Comment by liyinhua4346** [comment]
I　have some problem with you when I run the B-CNN,I run this code on CPU，It works well,but when I run it by GPU,it accurs problem like this problem.

**Comment by peterjc123** [comment]
Is there a minimal reproducible code that I can try?

**Comment by ShotDownDiane** [comment]
i solved this problem by update my torch version from 0.4 to 1.2
