### ISSUE TITLE
Memory Error in pip install of torch 1.2.0 on Linux

### ISSUE THREAD

**Issue by hhuuggoo** [pytorch/pytorch#25164]
## 🐛 Bug

Attempting to install torch 1.2.0 on linux results in a MemoryError

```
$ pip install torch==1.2.0
Collecting torch==1.2.0
  Downloading https://files.pythonhosted.org/packages/05/65/5248be50c55ab7429dd5c11f5e2f9f5865606b80e854ca63139ad1a584f2/torch-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (748.9MB)
     |████████████████████████████████| 748.9MB 18.6MB/s eta 0:00:01ERROR: Exception:
Traceback (most recent call last):
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/download.py", line 924, in unpack_http_url
    progress_bar)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/download.py", line 829, in written_chunks
    for chunk in chunks:
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_internal/download.py", line 818, in resp_read
    decode_content=False):
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 479, in read
    data = self._fp.read(amt)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 65, in read
    self._close()
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 52, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 300, in cache_response
    cache_url, self.serializer.dumps(request, response, body=body)
  File "/home/hugo/miniconda3/envs/ptesting/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 72, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
MemoryError
```

## To Reproduce

1. pip install torch==1.2.0 (on linux)

## Expected behavior

Installation, without MemoryError

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

cc @ezyang @gchanan

**Comment by rgommers** [comment]
`pip` version may not matter, that `cachecontrol` code hasn't been touched in 2 years: https://github.com/pypa/pip/blame/master/src/pip/_vendor/cachecontrol/serialize.py#L72

Is this a machine with little memory? The wheel is 749 MB, and monitoring memory usage during `pip install` it looks like nothing crazy happens - certainly no more than 2 GB is used.

**Comment by hhuuggoo** [comment]
I've been doing repo2docker builds with 2g ram, and also building on my laptop which has 16gb.   I'll dig into it further (hopefully today)  and follow up.  Thanks all!

**Comment by hhuuggoo** [comment]
I can confirm that manually downloading the wheel and installing it with pip is no problem.  I'm trying to re-install from pypi again

**Comment by hhuuggoo** [comment]
It worked this time - maybe my system was low on memory when I was attempting it before.  I'll mark this issue as closed.  Thanks

**Comment by rgommers** [comment]
> I've been doing repo2docker builds with 2g ram,
>
> It worked this time - maybe my system was low on memory when I was attempting it before.

That must have been it, 2 GB is really borderline. Thanks for following up Hugo.

**Comment by elenzil** [comment]
I also encountered the MemoryError issue installing torch from a pip requirements.txt. This is on an azurecloud ubuntu box w/ 4GB ram.  Manually installing the wheel worked fine, except torchvision doesn't seem to respect the install of torch. ie, despite `pip list` showing torch 1.3.1, `pip install torchvision` or `pip install requirements`  both re-download  `torch-1.3.1-cp36-cp36m-manylinux1_x86_64.whl` and then encounter the memory error.

**Comment by vedmin** [comment]
> 
> .. `pip install --no-cache-dir install torchvision` seems to have gotten around the issue.

I guess there is a typo in your command. The command which worked for me: 

`pip --no-cache-dir install torchvision`

**Comment by dataf3l** [comment]
@elenzil can you explain how to "Manually install the wheel" please?

**Comment by dataf3l** [comment]
ok never mind I found this: https://stackoverflow.com/questions/27885397/how-do-i-install-a-python-package-with-a-whl-file

**Comment by khordoo** [comment]
I was trying to install it on a machine with 1GB of ram and was getting this error: 
It was for inference and I  did not need the GPU, So I only installed the CPU package which has a smaller pip file and it was installed with no error. 

`pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by PaleNeutron** [comment]
If any one face `Memory Error` in installation and the stacktrace mentioned **decompress**, try to add swap space.

For ubuntu users, follow: https://help.ubuntu.com/community/SwapFaq

**Comment by tawanda** [comment]
Thanks @PaleNeutron

In my case I was installing on Amazon Linux, I followed this guide and it fixed my issue

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/

**Comment by RNogales94** [comment]
This worked for me:
`pip install --no-cache-dir torch==1.2.0`

**Comment by OIliverSmith** [comment]
> I also encountered the MemoryError issue installing torch from a pip requirements.txt. This is on an azurecloud ubuntu box w/ 4GB ram. Manually installing the wheel worked fine, except torchvision doesn't seem to respect the install of torch. ie, despite `pip list` showing torch 1.3.1, `pip install torchvision` or `pip install requirements` both re-download `torch-1.3.1-cp36-cp36m-manylinux1_x86_64.whl` and then encounter the memory error.
> 
> .. `pip install --no-cache-dir install torchvision` seems to have gotten around the issue.

Worked for me thanks
