### ISSUE TITLE
Strange Variable error

### ISSUE THREAD

**Issue by kefirski** [pytorch/pytorch#2519]
```
import torch as t
from torch.autograd import Variable

if __name__ == '__main__':
    t = Variable(t.FloatTensor(2, 3))
    x = Variable(t.FloatTensor(2, 3))

```

causes

```
Traceback (most recent call last):
  File "/Users/daniil/projects/mnist_cdvae/test.py", line 6, in <module>
    x = Variable(t.FloatTensor(2, 3))
  File "/Users/daniil/anaconda/envs/datascience36/lib/python3.6/site-packages/torch/autograd/variable.py", line 65, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'FloatTensor'
```

**Comment by kefirski** [comment]
Oh, I have't seen that I have Variable named as "t"
