### ISSUE TITLE
torch.distributed.launch issue

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#25299]
When I use `-m torch.distributed.launch --nproc_per_node=2` to launch, report error:
```
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    run()
  File "train.py", line 123, in run
    process.run()
  File "/home/46332/Trunk/dh_aiflow/dh_aiflow_process/dh_aiflow_process.py", line 224, in run
    self._train(self.gpu_ids)
  File "/home/46332/Trunk/dh_aiflow/dh_aiflow_process/dh_aiflow_process.py", line 236, in _train
    model = dh_data_parallel(self.model, gpu, dist_config=self.dist_config)
  File "/home/46332/Trunk/dh_aiflow/dh_aiflow_process/utils.py", line 94, in dh_data_parallel
    model = torch.nn.parallel.DistributedDataParallel(model, find_unused_parameters=True)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:39, invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-u', 'train.py', '--local_rank=1', '--trained_weights', 'log/model_15250.pth', '--isai']' returned non-zero exit status 1. 
```

my commant is `CUDA_VISIBLE_DEVICES=2,3 python3 -m torch.distributed.launch --nproc_per_node=2 train.py --trained_weights log/model_15250.pth  --isai `

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by pietern** [comment]
Please include the version of PyTorch you're using.

An invalid argument error from NCCL indicates something in NCCL itself is going wrong. Can you run again with NCCL debugging enabled and report back what you see? Please refer to https://pytorch.org/docs/stable/distributed.html#other-nccl-environment-variables for the relevant environment variables.

**Comment by pietern** [comment]
No response, closing the issue.
