### ISSUE TITLE
Custome Dataset class gives TypeError: __call__() missing 1 required positional argument: 'target'

### ISSUE THREAD

**Issue by sarimmehdi** [pytorch/pytorch#25318]
Hi, this is the code for my custom dataset class:
```
class MyDataSet(Dataset):
    def __init__(self, img_list, transform):
        self.transform = transform
        self.imgs = []
        for img in img_list:
            self.imgs.append(img)

    def __len__(self):
        return len(self.imgs)

    def __getitem__(self, idx):
        img = Image.fromarray(self.imgs[idx]).convert("RGB")

        if self.transform:
            img = self.transform(img)

        return img
```
And this is how I call it:
```
if __name__ == '__main__':
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    transform = transforms.Compose([transforms.ToTensor()])

    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    model = model.to(device)

    videopath = 'intersection.mp4'
    vid = cv2.VideoCapture(videopath)
    success, frame = vid.read()
    image_array = []
    while success:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image_array.append(frame)
        success, frame = vid.read()

    dataset = MyDataSet(image_array, transform)
    indices = list(range(len(dataset)))
    dataset_subset = torch.utils.data.Subset(dataset, indices[:])
    dataset_loader = torch.utils.data.DataLoader(dataset_subset, batch_size=1, shuffle=False, num_workers=4)

    tensor_imgs = []
    for i, img in enumerate(dataset_loader):
        tensor_imgs.append(img)
```
This is the error I am getting:
```
Traceback (most recent call last):
  File "C:/Users/sarim/PycharmProjects/thesis/pytorch_learning.py", line 63, in <module>
    for i, img in enumerate(dataset_loader):
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataset.py", line 107, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\Users\sarim\PycharmProjects\thesis\pytorch_learning.py", line 37, in __getitem__
    img = self.transform(img)
TypeError: __call__() missing 1 required positional argument: 'target'
```
**Why am I being told of a missing positional argument?**

**EDIT:**
I decided to import a different transform:
`import torchvision.transforms as transforms`
But now I get the following error:
```
Traceback (most recent call last):
  File "C:/Users/sarim/PycharmProjects/thesis/pytorch_learning.py", line 63, in <module>
    for i, img in enumerate(dataset_loader):
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    exitcode = _main(fd)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
```

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
