### ISSUE TITLE
BatchNorm doesn't support DoubleTensor

### ISSUE THREAD

**Issue by PraveerSINGH** [pytorch/pytorch#2535]
Hey, Any specific reason why BatchNorm module excludes DoubleTensor's from its operations ? 

FloatTensor works fine with BatchNorm while DoubleTensor yields a cast error (similarly for cuda.DoubleTensor too)

`import torch
import torch.nn as nn
m = nn.BatchNorm2d(3)
input_var = torch.autograd.Variable(torch.DoubleTensor(2,3,5,5))
o  = m(input_var)
`

`Traceback (most recent call last):
  File "test.py", line 6, in <module>
    o  = m(input_var)
  File "/home/praveer/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/praveer/anaconda2/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 43, in forward
    self.training, self.momentum, self.eps)
  File "/home/praveer/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 439, in batch_norm
    return f(input, weight, bias)
RuntimeError: std::bad_cast
`

**Comment by apaszke** [comment]
It supports it, but you need to prepare it (use `m.double()`)

**Comment by Luckick** [comment]
@apaszke Hi, I just want to know how to add batch norm in a nn.Sequential() when I use DoubleTensor. Thank you.
