### ISSUE TITLE
test_numerical_consistency is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25386]
```
Aug 28 23:20:20 ======================================================================
Aug 28 23:20:20 FAIL: test_numerical_consistency (__main__.TestFakeQuantizePerTensorAffine)
Aug 28 23:20:20 Comparing numerical consistency between CPU quantize/dequantize op and the CPU fake quantize op
Aug 28 23:20:20 ----------------------------------------------------------------------
Aug 28 23:20:20 Traceback (most recent call last):
Aug 28 23:20:20   File "test_fake_quant.py", line 82, in test_numerical_consistency
Aug 28 23:20:20     @given(device=st.sampled_from(['cpu', 'cuda'] if torch.cuda.is_available() else ['cpu']),
Aug 28 23:20:20   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Aug 28 23:20:20     raise the_error_hypothesis_found
Aug 28 23:20:20   File "test_fake_quant.py", line 98, in test_numerical_consistency
Aug 28 23:20:20     np.testing.assert_allclose(Y, Y_prime.cpu(), rtol=tolerance, atol=tolerance)
Aug 28 23:20:20   File "/opt/conda/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
Aug 28 23:20:20     verbose=verbose, header=header, equal_nan=equal_nan)
Aug 28 23:20:20   File "/opt/conda/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
Aug 28 23:20:20     raise AssertionError(msg)
Aug 28 23:20:20 AssertionError: 
Aug 28 23:20:20 Not equal to tolerance rtol=1e-06, atol=1e-06
Aug 28 23:20:20 
Aug 28 23:20:20 Mismatch: 50%
Aug 28 23:20:20 Max absolute difference: 0.12598228
Aug 28 23:20:20 Max relative difference: 0.0078125
Aug 28 23:20:20  x: array([ 15.999752, -15.999752], dtype=float32)
Aug 28 23:20:20  y: array([ 15.999751, -16.125734], dtype=float32)
```

https://circleci.com/gh/pytorch/pytorch/2614322?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

*please please please* determinize your Hypothesis tests!!

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by zou3519** [comment]
`ERROR: test_conv_api (__main__.ModuleAPITest)` is also flaky (should I open a separate issue for that?)

**Comment by jerryzh168** [comment]
@zou3519 yeah please open another issue.

@ezyang OK, I'll derandomize it.

**Comment by ezyang** [comment]
Still flaking https://circleci.com/gh/pytorch/pytorch/2637286?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jerryzh168** [comment]
@ezyang will send a PR today

**Comment by jerryzh168** [comment]
https://github.com/pytorch/pytorch/pull/25513

**Comment by jerryzh168** [comment]
should be fixed now, how can we confirm?

**Comment by ezyang** [comment]
If you tested your diff locally, let's close this and reopen if we see more flakiness.
