### ISSUE TITLE
test_conv_api (__main__.ModuleAPITest) is flaky

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#25413]
```
Aug 29 17:40:42 ======================================================================
Aug 29 17:40:42 ERROR: test_conv_api (__main__.ModuleAPITest)
Aug 29 17:40:42 Tests the correctness of the conv module.
Aug 29 17:40:42 ----------------------------------------------------------------------
Aug 29 17:40:42 Traceback (most recent call last):
Aug 29 17:40:42   File "test_quantized_nn_mods.py", line 337, in test_conv_api
Aug 29 17:40:42     @unittest.skipIf(
Aug 29 17:40:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Aug 29 17:40:42     raise the_error_hypothesis_found
Aug 29 17:40:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 971, in wrapped_test
Aug 29 17:40:42     state.run()
Aug 29 17:40:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 703, in run
Aug 29 17:40:42     info.__expected_traceback,
Aug 29 17:40:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 599, in execute
Aug 29 17:40:42     % (test.__name__, text_repr[0])
Aug 29 17:40:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 758, in __flaky
Aug 29 17:40:42     raise Flaky(message)
Aug 29 17:40:42 hypothesis.errors.Flaky: Hypothesis test_conv_api(self=<__main__.ModuleAPITest testMethod=test_conv_api>, use_bias=True, use_fused=False) produces unreliable results: Falsified on the first call but did not on a subsequent one
Aug 29 17:40:42 
```

on: https://github.com/pytorch/pytorch/pull/25344

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by jerryzh168** [comment]
https://github.com/pytorch/pytorch/pull/25513

**Comment by ezyang** [comment]
Also https://circleci.com/gh/pytorch/pytorch/2644855?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
@jerryzh168 There still seems to be some problems with this test: https://circleci.com/gh/pytorch/pytorch/2713616?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
Sep 09 19:26:42 ======================================================================
Sep 09 19:26:42 ERROR: test_conv_api (__main__.ModuleAPITest)
Sep 09 19:26:42 Tests the correctness of the conv module.
Sep 09 19:26:42 ----------------------------------------------------------------------
Sep 09 19:26:42 Traceback (most recent call last):
Sep 09 19:26:42   File "test_quantized_nn_mods.py", line 332, in test_conv_api
Sep 09 19:26:42     @unittest.skipIf(
Sep 09 19:26:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Sep 09 19:26:42     raise the_error_hypothesis_found
Sep 09 19:26:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 971, in wrapped_test
Sep 09 19:26:42     state.run()
Sep 09 19:26:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 703, in run
Sep 09 19:26:42     info.__expected_traceback,
Sep 09 19:26:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 599, in execute
Sep 09 19:26:42     % (test.__name__, text_repr[0])
Sep 09 19:26:42   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 758, in __flaky
Sep 09 19:26:42     raise Flaky(message)
Sep 09 19:26:42 hypothesis.errors.Flaky: Hypothesis test_conv_api(self=<__main__.ModuleAPITest testMethod=test_conv_api>, use_bias=True, use_fused=False) produces unreliable results: Falsified on the first call but did not on a subsequent one
```

The build in question is rebased past your derandomize fix.

**Comment by jerryzh168** [comment]
@ezyang seems the indentation is wrong...here is the fix: https://github.com/pytorch/pytorch/pull/25934

**Comment by jerryzh168** [comment]
should be fixed now
