### ISSUE TITLE
[dataloader] Problem in exception reraise mechanism

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#25522]
For some reason my implementation of `dataset.__getitem__` is throwing a `subprocess.CalledProcessError` (a problem in my dataset loading code).

If I pass to DataLoader `num_workers > 0`, I get the following - probably some issues with exception reraising (missing exception args).
```
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    traineval(parser.parse_args())
  File "train.py", line 148, in traineval
    for batch_idx, (inputs, targets, filenames, input_percentages, target_lengths) in enumerate(train_data_loader):
  File "/miniconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/miniconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/miniconda/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'cmd'
```

**Comment by SsnL** [comment]
Yeah, this is awkward as `CalledProcessError` has a different ctor signature than most other exceptions. We should special case if similar to what we did for `KeyError`.

**Comment by vadimkantorov** [comment]
And maybe add some generic path that catches this "reraise error", prints some raw exception info and asks the user to file a bug?
