### ISSUE TITLE
Illegal instruction (core dumped) when using Conv2d

### ISSUE THREAD

**Issue by jakubLangr** [pytorch/pytorch#25523]
## 🐛 Bug
Illegal instruction (core dumped) when using Conv2d using [this as input](https://github.com/jakubLangr/perses/raw/master/input). 

## To Reproduce

```
In [1]: import torch

In [2]: conv = torch.nn.Conv2d(3, 64, kernel_size=(7,7), stride=(2,2), padding=(3,3), bias=False)

In [3]: x = torch.load('input')

In [4]: x
Out[4]:
tensor([[[[-0.7996, -0.0521, -0.7319,  ..., -0.0453,  0.9881, -0.3905],
          [ 0.7789, -0.9055, -0.5167,  ...,  0.3787,  0.2276, -0.8297],
          [-0.9147, -0.3941, -0.1271,  ..., -0.1467,  0.6478,  0.3696],
          ...,
          [ 0.4563,  0.8853,  0.1537,  ..., -0.8561, -0.9245, -0.5376],
          [-0.1859,  0.0765,  0.2984,  ..., -0.0040, -0.8265, -0.6507],
          [-0.6926, -0.2349,  0.0175,  ...,  0.1300,  0.3349, -0.1819]],

         [[-0.4613, -0.4903,  0.0789,  ...,  0.5209,  0.1583, -0.8239],
          [-0.9266, -0.5768, -0.9637,  ...,  0.7904,  0.6255,  0.1808],
          [-0.2333, -0.5591,  0.9442,  ..., -0.7542, -0.0698, -0.1947],
          ...,
          [-0.0411, -0.5006, -0.3359,  ..., -0.0121,  0.2003, -0.0907],
          [-0.0318,  0.4603, -0.2556,  ..., -0.1870,  0.2278, -0.4594],
          [ 0.0536, -0.8734, -0.1334,  ..., -0.4221,  0.1062,  0.4037]],

         [[ 0.3556, -0.4456,  0.4743,  ..., -0.6574, -0.5216,  0.2847],
          [-0.7888,  0.6877,  0.4465,  ..., -0.3108,  0.7402, -0.7318],
          [ 0.7823, -0.9500, -0.4293,  ...,  0.2182,  0.8570,  0.4308],
          ...,
          [-0.6707, -0.7425,  0.7873,  ..., -0.5571,  0.4995, -0.3201],
          [-0.5639,  0.5040,  0.0495,  ...,  0.8776, -0.4961,  0.0126],
          [ 0.4624, -0.0750,  0.3274,  ...,  0.4468,  0.3086,  0.7119]]]])

In [5]: conv(x)
Illegal instruction (core dumped)
```

## Expected behavior

Conv runs

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 418.56
cuDNN version: /usr/local/cuda-9.0/lib64/libcudnn.so.7.2.1

Versions of relevant libraries:
[pip3] numpy==1.16.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.1.0           cuda100py37he554f03_0
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.3.0           cuda100py37h72fc40a_0
```

## Additional context

This issue happens irrespective whether run on GPU or with `CUDA_VISIBLE_DEVICES='' python test.py`

cc @ezyang @gchanan @zou3519

**Comment by jakubLangr** [comment]
Part of the problem also is that debugger does not allow me to go one level deeper. Eventually I end up here and even stepping into the file, dumps the core. So I can't even see the traceback.
```
ipdb> c
Deleted breakpoint 1 at /home/jakub/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:338
> /home/jakub/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py(338)forward()
    337         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 338                         self.padding, self.dilation, self.groups)
    339

ipdb> s
Illegal instruction (core dumped)
```

**Comment by Nikronic** [comment]
Hi,
I have run the code in my environment and I cannot reproduce the issue.

My env:
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.3.0
[conda] Could not collect
```

**Comment by gchanan** [comment]
can you try on version 1.2?

**Comment by jakubLangr** [comment]
This is fascinating. @Nikronic I will try again with python 3.6, I think that was an option. I will try to convince our sys admin to also update cuDNN version, as you seem to be using a significantly newer version.

@gchanan I could try but the code I am running has a dependency on torch 1.1.0 or earlier at the moment. 

Will post an update tomorrow.

**Comment by jakubLangr** [comment]
Okay, so under `python3.6` and `torch 1.2.0` this operations succeeds on the same machine. No cuDNN update. There must be something about the combination that messes the system up.

**Comment by nicolefinnie** [comment]
I hit the problem but I think it was because my environment was broken. Reinstalling pytorch 1.1 along with its dependencies simply fixed the problem.

**Comment by nagakei05** [comment]
I Installed pytorch 1.1.0 via the default conda channel as the command below, and came across the same error.
```
conda install pytorch==1.1.0 torchvision==0.3.0 -c default
```

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.3.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 435.21
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.0.130                      0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] pytorch                   1.1.0           cuda100py37he554f03_0
[conda] torchvision               0.3.0           cuda100py37h72fc40a_0
```

## Additional Context
I ran the repro through gdb and got these results
```
Program received signal SIGILL, Illegal instruction.
0x00007fffbfabecdb in mkldnn::impl::scales_t::set(int, int, float const*) () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
(gdb) backtrace
#0  0x00007fffbfabecdb in mkldnn::impl::scales_t::set(int, int, float const*) () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#1  0x00007fffbfac0cc1 in mkldnn_primitive_desc_iterator_create_v2 () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#2  0x00007fffbe26d16f in mkldnn::primitive_desc::primitive_desc(void const*, mkldnn::primitive_attr const*, mkldnn::engine const&, mkldnn_primitive_desc const*) ()
   from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#3  0x00007fffbe27bc1d in at::native::mkldnn_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) ()
   from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#4  0x00007fffbe449ae4 in at::TypeDefault::mkldnn_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#5  0x00007fffc0edbe3e in torch::autograd::VariableType::mkldnn_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libtorch.so.1
#6  0x00007fffbdf8475b in at::native::_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool) () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#7  0x00007fffbe4424a1 in at::TypeDefault::_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#8  0x00007fffc104d67f in torch::autograd::VariableType::_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libtorch.so.1
#9  0x00007fffbdf795b7 in at::native::convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#10 0x00007fffbe44233a in at::TypeDefault::convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#11 0x00007fffc105168c in torch::autograd::VariableType::convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libtorch.so.1
#12 0x00007fffbdf78ed0 in at::native::conv2d(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) ()
   from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#13 0x00007fffbe4429d4 in at::TypeDefault::conv2d(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) const ()
   from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#14 0x00007fffc12526be in torch::autograd::VariableType::conv2d(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) const () from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libtorch.so.1
#15 0x00007fffe95b77c8 in torch::autograd::THPVariable_conv2d(_object*, _object*, _object*) ()
   from /home/dl-box/anaconda3/envs/vaidebug3.7/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#16 0x00005555556b9c94 in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:694
#17 0x00005555556b9db1 in _PyCFunction_FastCallKeywords (func=0x7ffff4ddae10, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:734
#18 0x00005555557255be in call_function (kwnames=0x0, oparg=7, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:4568
#19 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:3093
#20 0x000055555566a31b in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=0x7fff90fcbe40)
    at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:283
#21 _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:322
#22 0x0000555555688b93 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:908
#23 0x000055555567b95e in PyObject_Call () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:245
#24 0x000055555572251a in do_call_core (kwdict=0x7ffff7f09fa0, callargs=0x7ffff7f70b90, func=0x7ffff7f8aaa0) at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:4645
#25 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:3191
#26 0x00005555556692b9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:3930
#27 0x000055555566a3e5 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:376
#28 0x0000555555688b93 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:908
#29 0x00005555556c016a in slot_tp_call () at /tmp/build/80754af9/python_1588882889832/work/Objects/typeobject.c:6402
#30 0x00005555556c100b in _PyObject_FastCallKeywords () at /tmp/build/80754af9/python_1588882889832/work/Objects/call.c:199
#31 0x0000555555725186 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:4619
#32 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:3124
---Type <return> to continue, or q <return> to quit---
#33 0x00005555556692b9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:3930
#34 0x000055555566a1d4 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:3959
#35 0x000055555566a1fc in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at /tmp/build/80754af9/python_1588882889832/work/Python/ceval.c:524
#36 0x000055555577ff44 in run_mod () at /tmp/build/80754af9/python_1588882889832/work/Python/pythonrun.c:1035
#37 0x000055555578a2b1 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1588882889832/work/Python/pythonrun.c:988
#38 0x000055555578a4a3 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1588882889832/work/Python/pythonrun.c:429
#39 0x000055555578b5d5 in pymain_run_file (p_cf=0x7fffffffd680, filename=0x5555558c2900 L"repro.py", fp=0x55555591fba0) at /tmp/build/80754af9/python_1588882889832/work/Modules/main.c:462
#40 pymain_run_filename (cf=0x7fffffffd680, pymain=0x7fffffffd790) at /tmp/build/80754af9/python_1588882889832/work/Modules/main.c:1641
#41 pymain_run_python (pymain=0x7fffffffd790) at /tmp/build/80754af9/python_1588882889832/work/Modules/main.c:2902
#42 pymain_main () at /tmp/build/80754af9/python_1588882889832/work/Modules/main.c:3442
#43 0x000055555578b6fc in _Py_UnixMain () at /tmp/build/80754af9/python_1588882889832/work/Modules/main.c:3477
#44 0x00007ffff77e6b97 in __libc_start_main (main=0x55555564a3a0 <main>, argc=2, argv=0x7fffffffd8e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffd8d8) at ../csu/libc-start.c:310
#45 0x00005555557303c0 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

Also, running the same script with PyTorch 1.1.0 from the official PyTorch channel gave me no errors
