### ISSUE TITLE
Win10, No CUDA: ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by glungu** [pytorch/pytorch#25600]
## 🐛 Bug

After successful installation of pytorch and torchvision, importing torchvision produces the following error: 
ImportError: DLL load failed: The specified module could not be found.

## To Reproduce

1. Create virtual environment: `python -m venv xxx` and activate it
1. Install pytorch as prescribed: `pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl`
1. Install torchvision as prescribed: `pip install torchvision`
1. Start python interactive console: `python`, followed by command `import torchvision`. The result is below:

```
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Work\ML\xxx\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "C:\Work\ML\xxx\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
    from . import detection
  File "C:\Work\ML\xxx\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "C:\Work\ML\xxx\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "C:\Work\ML\xxx\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "C:\Work\ML\xxx\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: DLL load failed: The specified module could not be found.
```

## Expected behavior

The expected behavior is for command `import torchvision` to run without errors.

## Environment

Output from [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

```
>python collect_env.py
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.1
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] Could not collect
```

## Additional context
Notice there is no conda, just virtual environment and pip.

cc @ezyang @peterjc123

**Comment by peterjc123** [comment]
Please try the following.
```bash
pip uninstall torchvision
pip install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-win_amd64.whl
```

**Comment by glungu** [comment]
This did help indeed.
Thank you very much for quick response.
