### ISSUE TITLE
FasterRCNN and MaskRCNN doesn't work with DataParallel or DistributedDataParallel

### ISSUE THREAD

**Issue by Anjum48** [pytorch/pytorch#25627]
## 🐛 Bug

FasterRCNN and MaskRCNN doesn't work with DataParallel or DistributedDataParallel

## To Reproduce

1. Open the `PennFudanDataset` Colab example from the tutorial
2. Switch to local runtime on a machine with more than 1 GPU
3. Add `model = torch.nn.parallel.DataParallel(model)` after `model.to(device)` in cell 11
4. Set batch size > number of GPUs

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-c750cf7ed566> in <module>
      3 for epoch in range(num_epochs):
      4     # train for one epoch, printing every 10 iterations
----> 5     train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=10)
      6     # update the learning rate
      7     lr_scheduler.step()

~/engine.py in train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq)
     28         targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
     29 
---> 30         loss_dict = model(images, targets)
     31 
     32         losses = sum(loss for loss in loss_dict.values())

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    150             return self.module(*inputs[0], **kwargs[0])
    151         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 152         outputs = self.parallel_apply(replicas, inputs, kwargs)
    153         return self.gather(outputs, self.output_device)
    154 

~/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in parallel_apply(self, replicas, inputs, kwargs)
    160 
    161     def parallel_apply(self, replicas, inputs, kwargs):
--> 162         return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    163 
    164     def gather(self, outputs, output_device):

~/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup, devices)
     83         output = results[i]
     84         if isinstance(output, ExceptionWrapper):
---> 85             output.reraise()
     86         outputs.append(output)
     87     return outputs

~/anaconda3/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    367             # (https://bugs.python.org/issue2651), so we work around it.
    368             msg = KeyErrorMessage(msg)
--> 369         raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
    images, targets = self.transform(images, targets)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 40, in forward
    image = self.normalize(image)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 55, in normalize
    return (image - mean[:, None, None]) / std[:, None, None]
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0
```

## Expected behavior

It appears that when the model is replicated, somehow the input images change from 3 channels to 2 causing the size mismatch described in the traceback

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 19.04
GCC version: (Ubuntu 7.4.0-8ubuntu1) 7.4.0
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.9.1
[pip] pytorch-ignite==0.2.0
[pip] torch==1.2.0
[pip] torch-cluster==1.4.3
[pip] torch-geometric==1.3.0
[pip] torch-scatter==1.3.1
[pip] torch-sparse==0.4.0
[pip] torch-spline-conv==1.1.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] faiss-gpu                 1.5.1            py37h1a5d453_1    pytorch
[conda] ignite                    0.2.0                    py37_0    pytorch
[conda] libblas                   3.8.0                    10_mkl    conda-forge
[conda] libcblas                  3.8.0                    10_mkl    conda-forge
[conda] liblapack                 3.8.0                    10_mkl    conda-forge
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.11           py37h14c3975_0    conda-forge
[conda] mkl_random                1.0.2            py37h637b7d7_2    conda-forge
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torch-cluster             1.4.3                    pypi_0    pypi
[conda] torch-geometric           1.3.0                    pypi_0    pypi
[conda] torch-scatter             1.3.1                    pypi_0    pypi
[conda] torch-sparse              0.4.0                    pypi_0    pypi
[conda] torch-spline-conv         1.1.0                    pypi_0    pypi
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by fmassa** [comment]
It is expected that the model wobt work with DataParallel because the inputs to the model are different than what DataParallel expects. But it does work with DistributedDataParallel, for one example see the references/detection/train.py file in torchvision.

**Comment by Anjum48** [comment]
I am getting the same size mismatch error (same code but not run in Colab) with DistributedDataParallel as per the train.py example

**Comment by fmassa** [comment]
You should run the code as follows:

```
python -m torch.distributed.launch --nproc_per_node=2 --use_env train.py
```
and you should have things working as expected.

**Comment by Anjum48** [comment]
Thanks! I've finally got it to work :)

I'm no expert on this but I think I found a few issues with the `train.py` example after studying the [documentation](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) for `torch.distributed.launch` as some of the `args` used are not set anywhere as far as I can tell.

For example:
-  `args.gpu` should be `args.local_rank`
- `device = torch.device(args.device)` may need to be something like `device = torch.device(f'cuda:{args.local_rank}')`

**Comment by fmassa** [comment]
We don't need `args.local_rank` because of the `use_env` argument from launch that I pasted just before.
Same thing for the comment on device

**Comment by gabrielcustodio** [comment]
> Thanks! I've finally got it to work :)
> 
> I'm no expert on this but I think I found a few issues with the `train.py` example after studying the [documentation](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) for `torch.distributed.launch` as some of the `args` used are not set anywhere as far as I can tell.
> 
> For example:
> 
> * `args.gpu` should be `args.local_rank`
> * `device = torch.device(args.device)` may need to be something like `device = torch.device(f'cuda:{args.local_rank}')`

Would you share some of the code you did to set up?

**Comment by Anjum48** [comment]
@gabrielcustodio Check out my answer here: https://discuss.pytorch.org/t/size-mismatch-when-running-fasterrcnn-in-parallel/54979/7?u=anjum_sayed

There is a very specific way things have to be launched in order for everything to work properly. It took a while for a noob like me to figure it out, but it will work eventually
