### ISSUE TITLE
Normalization transformation with multi-processing results in error

### ISSUE THREAD

**Issue by yash1994** [pytorch/pytorch#25645]
## 🐛 Bug

I have a task in which I have to vectorize lots of images for that purpose I am using multi-processing process pool to open the image from the file path and apply transformation (Resize, ToTensor, Normalize) and return image tensor. If I remove normalization transformation then everything runs smoothly.

## To Reproduce

```python
import os
import torch
import torch.nn as nn
from PIL import Image
from torchvision import datasets, models, transforms
from multiprocessing import Pool

def read_image(filename):
    img_transforms = transforms.Compose([
        transforms.Resize((299,299)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    image = Image.open(filename)

    img = img_transforms(image)

    return img,filename

rows = [ ] # list of image_paths

with Pool(processes=4) as pool:
    for result, row in pool.map(read_image, rows):
        print(row, result.shape)
```

## Error Trace Stack

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "test.py", line 25, in read_image
    img = img_transforms(image)
  File "/home/yash/python3_env/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/yash/python3_env/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/yash/python3_env/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 217, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): Ubuntu 18.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0.130 / 7.4.1
 - GPU models and configuration: GeForce GTX 1050 Ti

**Comment by yash1994** [comment]
Sorry, my bad, the issue was with 'RGBA' image mode. Closing issue.
