### ISSUE TITLE
fatal error: 'string.h' file not found

### ISSUE THREAD

**Issue by vincentqb** [pytorch/pytorch#25669]
## 🐛 Bug

Compilation error:

```
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCBlas.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCBlas.cu.o


[58/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCSortUtils.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCSortUtils.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCSortUtils.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCSortUtils.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCSortUtils.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCSortUtils.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCSortUtils.cu.o


[59/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorMathCompareByte.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorMathCompareByte.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/./torch_generated_THCTensorMathCompareByte.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/./torch_generated_THCTensorMathCompareByte.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorMathCompareByte.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCTensorMathCompareByte.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/./torch_generated_THCTensorMathCompareByte.cu.o


[60/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathBlas.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathBlas.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathBlas.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathBlas.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathBlas.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCTensorMathBlas.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathBlas.cu.o


[61/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCStorage.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCStorage.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCStorage.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCStorage.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCStorage.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCStorage.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCStorage.cu.o


[62/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathReduce.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathReduce.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathReduce.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathReduce.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathReduce.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCTensorMathReduce.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathReduce.cu.o


[63/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorSortByte.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorSortByte.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/./torch_generated_THCTensorSortByte.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/./torch_generated_THCTensorSortByte.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorSortByte.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCTensorSortByte.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/./torch_generated_THCTensorSortByte.cu.o


[64/1762] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMode.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMode.cu.o 
cd /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -E make_directory /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/. && /Users/vincentqb/anaconda3/envs/pytorch-built/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMode.cu.o -D generated_cubin_file:STRING=/Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMode.cu.o.cubin.txt -P /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMode.cu.o.Release.cmake
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:115:
In file included from /usr/local/cuda/include/crt/common_functions.h:77:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
CMake Error at torch_generated_THCTensorMode.cu.o.Release.cmake:220 (message):
  Error generating
  /Users/vincentqb/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMode.cu.o


ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 756, in <module>
    build_deps()
  File "setup.py", line 321, in build_deps
    cmake=cmake)
  File "/Users/vincentqb/pytorch/tools/build_pytorch_libs.py", line 63, in build_caffe2
    cmake.build(my_env)
  File "/Users/vincentqb/pytorch/tools/setup_helpers/cmake.py", line 330, in build
    self.run(build_args, my_env)
  File "/Users/vincentqb/pytorch/tools/setup_helpers/cmake.py", line 143, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/vincentqb/anaconda3/envs/pytorch-built/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.
```

## To Reproduce

```
conda create -n pytorch-built python=3.7
conda activate pytorch-built
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing   
git submodule sync    
git submodule update --init --recursive  
python setup.py clean --all 
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}        
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0.post2
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-include               2019.4                      233  
[conda] mkl-service               2.0.2            py37h1de35cc_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0

## Additional context

* Related to #16693 and #16602 ?
* Tried `conda install -c conda-forge cmake` suggested [here](https://github.com/pytorch/pytorch/issues/16602#issuecomment-460348240)
* Tried to remove `-Werror` as mentioned [here](https://github.com/pytorch/pytorch/issues/16602#issuecomment-462966216)
* Tried python 3.{6,7}
* Tried from a fresh `git clone --recursive https://github.com/pytorch/pytorch`

**Comment by gchanan** [comment]
why is this labeled caffe2?

**Comment by vincentqb** [comment]
> why is this labeled caffe2?

The paths with errors link to caffe2. I'll remove the tag anyway based on your question.

**Comment by vincentqb** [comment]
As recommended by @zou3519, this works: 
```
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ NO_CUDA=1 python setup.py install
```
I had experimented with CUDA on mac a couple of days ago, so the explicit `NO_CUDA=1` removed the link to it.
