### ISSUE TITLE
Nightly build failure on Windows (`convert_to_int_of_same_size` related)

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#25763]
```
%SRC_DIR%\tmp_bin\sccache.exe  cl  /nologo /TP -DAT_PARALLEL_OPENMP=1 -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DMAGMA_V2 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_CUDA -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -D_OPENMP_NOFORCE_MANIFEST -D_THP_CORE -Dtorch_EXPORTS -Iaten\src -I..\aten\src -I. -I..\ -I..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\third_party\onnx -Ithird_party\onnx -I..\third_party\foxi -Ithird_party\foxi -I..\caffe2\..\torch\csrc\api -I..\caffe2\..\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I..\caffe2\aten\src\TH -Icaffe2\aten\src\TH -I..\caffe2\..\torch\..\aten\src -Icaffe2\aten\src -Icaffe2\..\aten\src -Icaffe2\..\aten\src\ATen -I..\caffe2\..\torch\csrc -I..\caffe2\..\torch\..\third_party\miniz-2.0.8 -I..\aten\src\TH -I..\aten\..\third_party\catch\single_include -I..\aten\src\ATen\.. -Icaffe2\aten\src\ATen -I..\third_party\miniz-2.0.8 -I..\caffe2\core\nomnigraph\include -Icaffe2\aten\src\THC -I..\aten\src\THC -I..\aten\src\THCUNN -I..\aten\src\ATen\cuda -I..\c10\.. -I..\third_party\cpuinfo\include -I..\third_party\FP16\include -I..\c10\cuda\..\.. -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -I..\mkl\include -I..\cmake\..\third_party\eigen -I%PREFIX%\include -IC:\w\1\s\TMP_CO~1.5_1\conda\CONDA-~2\PYTORC~1\_h_env\lib\site-packages\numpy\core\include -I..\cmake\..\third_party\pybind11\include -I\opt\rocm\hip\include -I\include -I..\cmake\..\third_party\cub -I..\magma_cuda100_release\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I..\caffe2 /DWIN32 /D_WINDOWS  /GR  /w /EHa /MP /bigobj -openmp -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION /MD /O2 /Ob2  /w /EHa /MP /bigobj   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -O2 /Ox /fp:strict /arch:AVX /DCPU_CAPABILITY=AVX /DCPU_CAPABILITY_AVX /showIncludes /Focaffe2\CMakeFiles\torch.dir\__\aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp.obj /Fdcaffe2\CMakeFiles\torch.dir\ /FS -c aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(738): error C2672: 'convert_to_int_of_same_size': no matching overloaded function found
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(731): note: while compiling class template member function 'void at::native::`anonymous-namespace'::ApplyGridSample<scalar_t,2,at::native::detail::GridSamplerInterpolation::Nearest,at::native::detail::GridSamplerPadding::Reflection,false>::backward(at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,const at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,const at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,int64_t,const at::vec256::`anonymous-namespace'::Vec256<float> &,const at::vec256::`anonymous-namespace'::Vec256<float> &,int64_t) const'
        with
        [
            scalar_t=scalar_t
        ]
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(1005): note: see reference to function template instantiation 'void at::native::`anonymous-namespace'::ApplyGridSample<scalar_t,2,at::native::detail::GridSamplerInterpolation::Nearest,at::native::detail::GridSamplerPadding::Reflection,false>::backward(at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,const at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,const at::TensorAccessor<scalar_t,3,at::DefaultPtrTraits,int64_t> &,int64_t,const at::vec256::`anonymous-namespace'::Vec256<float> &,const at::vec256::`anonymous-namespace'::Vec256<float> &,int64_t) const' being compiled
        with
        [
            scalar_t=scalar_t
        ]
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(948): note: see reference to class template instantiation 'at::native::`anonymous-namespace'::ApplyGridSample<scalar_t,2,at::native::detail::GridSamplerInterpolation::Nearest,at::native::detail::GridSamplerPadding::Reflection,false>' being compiled
%SRC_DIR%\aten\src\ATen/cpu/vec256/vec256_qint.h(632): note: see reference to class template instantiation 'at::vec256::`anonymous-namespace'::Vec256QuantizedConverter<c10::qint32,std::array<at::vec256::`anonymous-namespace'::Vec256<float>,1>,8>' being compiled
%SRC_DIR%\aten\src\ATen/cpu/vec256/vec256_qint.h(572): note: see reference to class template instantiation 'at::vec256::`anonymous-namespace'::Vec256QuantizedConverter<c10::quint8,std::array<at::vec256::`anonymous-namespace'::Vec256<float>,4>,32>' being compiled
%SRC_DIR%\aten\src\ATen/cpu/vec256/vec256_qint.h(512): note: see reference to class template instantiation 'at::vec256::`anonymous-namespace'::Vec256QuantizedConverter<c10::qint8,std::array<at::vec256::`anonymous-namespace'::Vec256<float>,4>,32>' being compiled
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 321, in build_deps
    cmake=cmake)
  File "C:\w\1\s\TMP_CO~1.5_1\conda\CONDA-~2\PYTORC~1\work\tools\build_pytorch_libs.py", line 63, in build_caffe2
    cmake.build(my_env)
  File "C:\w\1\s\TMP_CO~1.5_1\conda\CONDA-~2\PYTORC~1\work\tools\setup_helpers\cmake.py", line 330, in build
    self.run(build_args, my_env)
  File "C:\w\1\s\TMP_CO~1.5_1\conda\CONDA-~2\PYTORC~1\work\tools\setup_helpers\cmake.py", line 143, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\w\1\s\TMP_CO~1.5_1\conda\CONDA-~2\PYTORC~1\_h_env\lib\subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 1
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(738): error C2770: invalid explicit template argument(s) for 'at::vec256::`anonymous-namespace'::Vec256<int_of_size<sizeof(T)>::type> at::vec256::`anonymous-namespace'::convert_to_int_of_same_size(const at::vec256::`anonymous-namespace'::Vec256<T> &)'
%SRC_DIR%\aten\src\ATen/cpu/vec256/vec256_base.h(498): note: see declaration of 'at::vec256::`anonymous-namespace'::convert_to_int_of_same_size'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(742): error C3536: 'i_x_nearest': cannot be used before it is initialized
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(742): error C2678: binary '>': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: could be 'at::Tensor at::operator >(c10::Scalar,const at::Tensor &)'
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: or       'at::Tensor at::operator >(const at::Tensor &,c10::Scalar)'
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: or       'at::Tensor at::operator >(const at::Tensor &,const at::Tensor &)'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(742): note: while trying to match the argument list '(int, at::vec256::`anonymous-namespace'::Vec256<int>)'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(742): error C2678: binary '<': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: could be 'at::Tensor at::operator <(c10::Scalar,const at::Tensor &)'
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: or       'at::Tensor at::operator <(const at::Tensor &,c10::Scalar)'
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: or       'at::Tensor at::operator <(const at::Tensor &,const at::Tensor &)'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(742): note: while trying to match the argument list '(int, at::vec256::`anonymous-namespace'::Vec256<int>)'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(745): error C2678: binary '+': no operator found which takes a left-hand operand of type 'at::vec256::`anonymous-namespace'::Vec256<int>' (or there is no acceptable conversion)
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: could be 'at::Tensor at::operator +(c10::Scalar,const at::Tensor &)'
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: or       'at::Tensor at::operator +(const at::Tensor &,c10::Scalar)'
%SRC_DIR%\aten\src\ATen/TensorOperators.h(95): note: or       'at::Tensor at::operator +(const at::Tensor &,const at::Tensor &)'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(745): note: while trying to match the argument list '(at::vec256::`anonymous-namespace'::Vec256<int>, int)'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(748): error C3536: 'i_mask': cannot be used before it is initialized
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(748): error C2228: left of '.store' must have class/struct/union
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(748): note: type is 'int'
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(750): error C3536: 'i_gInp_offset': cannot be used before it is initialized
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(750): error C2228: left of '.store' must have class/struct/union
aten\src\ATen\native\cpu\GridSamplerKernel.cpp.AVX.cpp(750): note: type is 'int'
```
This error will not occur every time in the build. 

cc @ezyang @gchanan @zou3519 @peterjc123

**Comment by peterjc123** [comment]
cc @ezyang

**Comment by ezyang** [comment]
Yes, I've seen this one before too. Seemingly related #25393 and #25389

**Comment by xsacha** [comment]
Is this why the Debug version of the nightly is over a month old?
The Release nightly seems to be recent.

**Comment by peterjc123** [comment]
No, it was caused by some disk space issues on the build machines. Should be okay now.

**Comment by gchanan** [comment]
Going to optimistically close based on @peterjc123's comment.

**Comment by peterjc123** [comment]
@gchanan Well, https://github.com/pytorch/pytorch/issues/25763#issuecomment-535274864 is a reply to https://github.com/pytorch/pytorch/issues/25763#issuecomment-535218977, not the problem itself. But anyway, I haven't seen this error for a long time. So it's okay to close this issue.

**Comment by eezstreet** [comment]
Still occurring as of latest master.

**Comment by seven-mile** [comment]
Any workaround available? I can repro this stably with nightly builds after xmas...
