### ISSUE TITLE
(PyTorch1.1 and 1.2) RuntimeError: Can't detach views in-place. Use detach() instead

### ISSUE THREAD

**Issue by ssdyue** [pytorch/pytorch#25814]
In my code, run `optimizer.zero_grad()`, there is an error here:

```
File "/home/backend/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 164, in zero_grad
    p.grad.detach_()
RuntimeError: Can't detach views in-place. Use detach() instead
```
Should I modify `detach_()` to `detach()` here?

**Comment by ezyang** [comment]
cc @yf225

**Comment by ezyang** [comment]
Somehow the gradient on a function is a view. I don't think any of our code permits this to happen. Can you share more about your program in question?

**Comment by SsnL** [comment]
@ezyang It could happen, e.g., when one does
```py
big_tensor[1:2] = leaf
loss = big_tensor().sum()
loss.backward()
```
Then the gradient for `leaf` is `torch.ones_like(big_tensor)[1:2]`, which is a view.

**Comment by ezyang** [comment]
argh. Upgrading priority, in that case

**Comment by ssdyue** [comment]
This problem occurs under the following conditions：

```
for data, target in enumerate(dataloader):
    optimizer.zero_grad()
    ***
    loss.backward()
    for param in model.parameters():
        grad = param.grad
        grad_op = function(grad)  ### function represents the processing of the gradient
        grad_res = grad_op.reshape(param.shape)
        param.grad = grad_res
    optimizer.step()
```

I have done a few tests below：

```
t = torch.rand(2,3,4)
t_reshape = t.reshape(24,1)  ### or t_reshape = t.view(-1,1)
t_reshape.detach_()

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: Can't detach views in-place. Use detach() instead
```

but the following code can run:

`t_reshape.detach()`

or

```
t_np = numpy.array(t_reshape)
t = torch.from_numpy(t_np)
t.detach_()
```

**Comment by knowlsie** [comment]
I'm running into this issue. Is there any workaround to modify gradients without this being an issue?

**Comment by albanD** [comment]
@SsnL  another simple fix here could be to say that `AccumulateGrad` is responsible to never set the grad to a view. In that case, it will `.clone()` the result.
Given all the efforts we do to reuse the same grad buffer when it exists, having one as a view of another Tensor can be dangerous anyway I think.
Would you be happy with that change?

**Comment by jefferythewind** [comment]
Just for anyone who had this problem, like I did. I was able to get around this by altering the code to set the gradients of the parameters with a `.clone()` of the tensor.

For example, I was getting the error with this code.

`optimizer.param_groups[0]['params'][j].grad = final_grad`

and changing it to this made the error go away.

`optimizer.param_groups[0]['params'][j].grad = final_grad.clone()`
