### ISSUE TITLE
USE_MKLDNN=0 has no effect and causes ideep build error

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#25849]
```
export USE_MKLDNN=0
export BUILD_TEST=0
export USE_DISTRIBUTED=0
export USE_GLOO=0
export USE_C10D_GLOO=0

sudo python3 setup.py build --cmake
sudo python3 setup.py install --cmake

```

error:

```
/pytorch/third_party/ideep/include/ideep/utils.hpp:15:21: fatal error: mkl_vsl.h: No such file or directory
compilation terminated.
caffe2/CMakeFiles/torch.dir/build.make:2729: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5289: recipe for target 'caffe2/CMakeFiles/torch.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/autox-sz/departments/perception/software/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/autox-sz/departments/perception/software/pytorch/tools/setup_helpers/cmake.py", line 333, in build
    self.run(build_args, my_env)
  File "/autox-sz/departments/perception/software/pytorch/tools/setup_helpers/cmake.py", line 143, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 2

```

Abviously, I don't use mkldnn, but it keep try using mkldnn and can not found a dependencies.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by XiaobingSuper** [comment]
@jinfagang, I can't reproduce it, can you post your full build log? thanks!

**Comment by jinfagang** [comment]
```
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/cpu/FlushDenormal.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/detail/CPUGuardImpl.cpp.o
In file included from //pytorch/third_party/ideep/include/ideep/lru_cache.hpp:7:0,
                 from pytorch/third_party/ideep/include/ideep/tensor.hpp:10,
                 from /pytorch/third_party/ideep/include/ideep.hpp:40,
                 from //pytorch/aten/src/ATen/Version.cpp:10:
/pytorch/third_party/ideep/include/ideep/utils.hpp:15:21: fatal error: mkl_vsl.h: No such file or directory
compilation terminated.
caffe2/CMakeFiles/torch.dir/build.make:2729: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5289: recipe for target 'caffe2/CMakeFiles/torch.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 333, in build
    self.run(build_args, my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 143, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 2

```


My command history:

```
USE_MKLDNN=0 USE_DISTRIBUTED=0 USE_C10D_GLOO=0 sudo python3 setup.py install --cmake
```

I tried both set `USE_MKLDNN=0` or export it, but all has no effect.....

**Comment by jinfagang** [comment]
Also, I have `rm -r build` before every build, so that it should not be cache issue.

I have tried this several times, always gives me this error...... No matter how I export the variable or set it before command like above./

**Comment by XiaobingSuper** [comment]
@jinfagang, the build log which I want see is like:
```
(pytorch-gpu) [xiaobinz@mlt-gpu207 pytorch-xiaobing]$ USE_MKLDNN=0 USE_DISTRIBUTED=0 USE_C10D_GLOO=0 python setup.py install --cmake
Building wheel torch-1.3.0a0+29be5d9
-- Building version 1.3.0a0+29be5d9
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/xiaobinz/Downloads/pytorch-xiaobing/torch -DCMAKE_PREFIX_PATH=/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages -DNUMPY_INCLUDE_DIR=/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/xiaobinz/anaconda3/envs/pytorch-gpu/bin/python -DPYTHON_INCLUDE_DIR=/home/xiaobinz/anaconda3/envs/pytorch-gpu/include/python3.6m -DPYTHON_LIBRARY=/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/libpython3.6m.so.1.0 -DTORCH_BUILD_VERSION=1.3.0a0+29be5d9 -DUSE_C10D_GLOO=0 -DUSE_CUDA=True -DUSE_DISTRIBUTED=False -DUSE_MKLDNN=0 -DUSE_NUMPY=True /home/xiaobinz/Downloads/pytorch-xiaobing
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Success
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Failed
-- NUMA is not available
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Failed
-- Turning off deprecation warning due to glog.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS - Failed
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/xiaobinz/Downloads/pytorch-xiaobing/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- Trying to find preferred BLAS backend of choice: MKL
-- MKL_THREADING = OMP
```
or 

```
-- ******** Summary ********
-- General:
--   CMake version         : 3.14.0
--   CMake command         : /home/xiaobinz/anaconda3/envs/pytorch-gpu/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 4.8.5
--   BLAS                  : MKL
--   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_ML=1;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages;/usr/local/cuda
--   CMAKE_INSTALL_PREFIX  : /home/xiaobinz/Downloads/pytorch-xiaobing/torch
--
--   TORCH_VERSION         : 1.3.0
--   CAFFE2_VERSION        : 1.3.0
--   BUILD_CAFFE2_MOBILE   : ON
--   USE_STATIC_DISPATCH   : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.6.9
--     Python executable   : /home/xiaobinz/anaconda3/envs/pytorch-gpu/bin/python
--     Pythonlibs version  : 3.6.9
--     Python library      : /home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/libpython3.6m.so.1.0
--     Python includes     : /home/xiaobinz/anaconda3/envs/pytorch-gpu/include/python3.6m
--     Python site-packages: lib/python3.6/site-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   INTERN_BUILD_MOBILE   :
--   USE_ASAN              : OFF
--   USE_CUDA              : True
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 9.0
--     cuDNN version       : 7.1.2
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so
--     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    :
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : ON
--   USE_TBB               : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : False
--   BUILD_NAMEDTENSOR   : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fp16;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring done
```
I can know whether works for your setting  if you posted log have those information. You can see my build log: USE_MKLDNN=**OFF** if I set USE_MKLDNN=0 in install command.

**Comment by jinfagang** [comment]
I actually got MKLDNN issue:

```
-- ******** Summary ********
--   CMake version         : 3.15.0-rc4
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 6.5.0
--   CXX flags             :  -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_ML=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python3/dist-packages;/usr/local/cuda
--   CMAKE_INSTALL_PREFIX  : eption/software/pytorch/torch
--   CMAKE_MODULE_PATH     : /ke/Modules;n/software/pytorch/cmake/public/../Modules_CUDA_fix;xternal
-- 
--   ONNX version          : 1.5.0
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : ON
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : ON
--     Python version      : 
--     Python executable   : /usr/bin/python3
--     Python includes     : /usr/include/python3.5m
-- 
-- ******** Summary ********
--   CMake version         : 3.15.0-rc4
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 6.5.0
--   CXX flags             :  -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_ML=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python3/dist-packages;/usr/local/cuda
--   CMAKE_INSTALL_PREFIX  : //pytorch/torch
--   CMAKE_MODULE_PATH     : //../Modules_CUDA_fix
-- 
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : ON
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : ON
--     Python version      : 
--     Python executable   : /usr/bin/python3
--     Python includes     : /usr/include/python3.5m
-- Found CUDA with FP16 support, compiling with torch.cuda.HalfTensor
-- Removing -DNDEBUG from compile flags
-- MAGMA not found. Compiling without MAGMA support
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Performing Test HAVE_GCC_GET_CPUID
-- Performing Test HAVE_GCC_GET_CPUID - Success
-- Performing Test NO_GCC_EBX_FPIC_BUG
-- Performing Test NO_GCC_EBX_FPIC_BUG - Success
-- Performing Test C_HAS_AVX_1
-- Performing Test C_HAS_AVX_1 - Failed
-- Performing Test C_HAS_AVX_2
-- Performing Test C_HAS_AVX_2 - Success
-- Performing Test C_HAS_AVX2_1
-- Performing Test C_HAS_AVX2_1 - Failed
-- Performing Test C_HAS_AVX2_2
-- Performing Test C_HAS_AVX2_2 - Success
-- Performing Test CXX_HAS_AVX_1
-- Performing Test CXX_HAS_AVX_1 - Failed
-- Performing Test CXX_HAS_AVX_2
-- Performing Test CXX_HAS_AVX_2 - Success
-- Performing Test CXX_HAS_AVX2_1
-- Performing Test CXX_HAS_AVX2_1 - Failed
-- Performing Test CXX_HAS_AVX2_2
-- Performing Test CXX_HAS_AVX2_2 - Success
-- AVX compiler support found
-- AVX2 compiler support found
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found a library with LAPACK API (open).
disabling ROCM because NOT USE_ROCM is set
-- MIOpen not found. Compiling without MIOpen support
-- MKLDNN_THREADING = OMP:COMP
CMake Warning (dev) at third_party/ideep/mkl-dnn/cmake/options.cmake:33 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'MKLDNN_ENABLE_CONCURRENT_EXEC'.
Call Stack (most recent call first):
  third_party/ideep/mkl-dnn/cmake/utils.cmake:24 (include)
  third_party/ideep/mkl-dnn/CMakeLists.txt:74 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

```


I can not see USE+MKLDNN off....

**Comment by jinfagang** [comment]
```
cmake version 3.15.0-rc4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

**Comment by XiaobingSuper** [comment]
@jinfagang , there has another summary log behind your given in the build step, perhaps you can paste your full log into [gist](https://gist.github.com/) which we can fully find the reasons for this failure(also paste conda list or pip list). by the way, I also asked my colleague to reproduce it, he also couldn't get the expected failure. Thanks!

**Comment by jinfagang** [comment]
the problem is `sudo`, in case anyone else caguht this, pls using `sudo -E`
