### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1199: ordinal not in range(128)

### ISSUE THREAD

**Issue by sclarkson** [pytorch/pytorch#25891]
## 🐛 Bug

CPP extension ompilation with LANG set to a UTF-8 encoding will cause an ASCII decoding error in Python 2.7

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    extra_include_paths=["/usr/include/python2.7"])
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 787, in load_inline
    is_python_module)
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 880, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 972, in _build_extension_module
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1199: ordinal not in range(128)
```

Probably the subprocess should set LC_ALL=C

## To Reproduce

1. Install torch 1.2.0 from PyPI for Python 2.7
2. Run the following snippet with LANG=en_US.UTF-8
```
import torch.utils.cpp_extension
torch.utils.cpp_extension.load_inline(
        name="test",
        cpp_sources="int main() { return 0 }",
        extra_include_paths=["/usr/include/python2.7"])

```

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 2.7.15+
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

cc @yf225

**Comment by urandu** [comment]
Please assign me this issue.

**Comment by sclarkson** [comment]
Closing, since this only affected Python 2 which is no longer supported.
