### ISSUE TITLE
Python hang after using torch.exp()

### ISSUE THREAD

**Issue by GanjinZero** [pytorch/pytorch#25904]
## 🐛 Bug

Using function torch.exp() makes python hang. I test some other functions like torch.sum(), torch.abs(), these functions can return right results.

## To Reproduce

```
torch.exp(torch.Tensor([0, math.log(2)]))
```
Python just hang, python cannot be closed by using CTRL+C under Ubuntu 16.04.

## Expected behavior

Out[2]: Tensor([1, 2])

## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 410.93
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.9.1
[pip] torch==1.2.0
[pip] torch-cluster==1.4.2
[pip] torch-geometric==1.2.1
[pip] torch-scatter==1.2.0
[pip] torch-sparse==0.4.0
[pip] torch-spline-conv==1.1.0
[pip] torchsummaryX==1.3.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py36h90e4bf4_5  
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torch-cluster             1.4.2                    pypi_0    pypi
[conda] torch-geometric           1.2.1                    pypi_0    pypi
[conda] torch-scatter             1.2.0                    pypi_0    pypi
[conda] torch-sparse              0.4.0                    pypi_0    pypi
[conda] torch-spline-conv         1.1.0                    pypi_0    pypi
[conda] torchsummaryx             1.3.0                    pypi_0    pypi
[conda] torchvision               0.2.2.post2              pypi_0    pypi

**Comment by rsokl** [comment]
I am unable to reproduce this on PyTorch 1.2. 

![image](https://user-images.githubusercontent.com/29104956/64617682-e0bf9b80-d3ac-11e9-80bf-3a653a2cec42.png)

**Comment by fmassa** [comment]
@GanjinZero can you get us a stack trace from gdb when the process hang?
Something like
```
gdb attach <pid>
thread apply all bt
```
and give back the results?

**Comment by GanjinZero** [comment]
I have no knowledge about gdb, so I only copy the result from it.
```
Attaching to process 7319
[New LWP 7322]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f670d7de827 in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) thread apply all bt

Thread 2 (Thread 0x7f670a68f700 (LWP 7322)):
#0  0x00007f670dacd827 in futex_abstimed_wait_cancelable (private=0, 
    abstime=0x0, expected=0, futex_word=0x7f670403a900)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7f670403a900, abstime=0x0)
    at sem_waitcommon.c:111
#2  0x00007f670dacd8d4 in __new_sem_wait_slow (sem=0x7f670403a900, 
    abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f670dacd97a in __new_sem_wait (sem=<optimized out>)
    at sem_wait.c:29
#4  0x000055e450513f76 in PyThread_acquire_lock_timed ()
    at /tmp/build/80754af9/python_1546130271559/work/Python/thread_pthread.h:386
#5  0x000055e4505a61ac in acquire_timed (timeout=-1000000000, 
    lock=0x7f670403a900)
    at /tmp/build/80754af9/python_1546130271559/work/Modules/_threadmodule.c:68
#6  lock_PyThread_acquire_lock ()
    at /tmp/build/80754af9/python_1546130271559/work/Modules/_threadmodule.c:151
---Type <return> to continue, or q <return> to quit---
```

**Comment by alittlealone** [comment]
I met the same problem with you!
How did you solve this problem?

**Comment by GanjinZero** [comment]
> I met the same problem with you!
> How did you solve this problem?

try another version of pytorch

**Comment by albanD** [comment]
The deadlock happens when you try to run python code. Can you give the full code sample of what you were doing when it happens?
