### ISSUE TITLE
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

### ISSUE THREAD

**Issue by ShadowGlory** [pytorch/pytorch#2593]
I am trying to train dataset with pytorch-yolo2 (https://github.com/marvis/pytorch-yolo2)
It well worked with python 2.7, but when I turned to python 3.5.2, I got the error message like below.
I have installed Pytorch 0.2.0.post3 in both python2.7 and python 3.5.
I will be very appreciate for help.

```
Traceback (most recent call last):
 File "train.py", line 161, in train
    output = model(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 58, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shadowglory/pytorch-yolo2/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 51, in conv2d
    _pair(0), groups, torch.backends.cudnn.benchmark, torch.backends.cudnn.enabled)
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

```

**Comment by allenye0119** [comment]
In python2, `5 / 2` will give you 2, but in python3, `5 / 2` equals `2.5`, you need to use `5 // 2`  which will give you 2.
I think you only need to change [this line](https://github.com/marvis/pytorch-yolo2/blob/6e64ef0229d0254eccf36c18d8ba7792eea89a2d/darknet.py#L149) so that `pad` will be an int.

**Comment by ShadowGlory** [comment]
Thanks so much for the answer. It solved.
