### ISSUE TITLE
model.updateParameters(lr) in torch/legacy/nn not working

### ISSUE THREAD

**Issue by iacolippo** [pytorch/pytorch#2613]
I implemented a model using `torch.legacy` because I have to do particular things and I'm starting from a PyTorch implementation. I think this method may be broken.

If I run this code:
https://gist.github.com/iacolippo/df46eebd6d7ea20402e87229e7258a7a

I get this error:

```
Traceback (most recent call last):
  File "reproducing_bug.py", line 52, in <module>
    model.updateParameters(1)
  File "/usr/local/lib/python3.5/dist-packages/torch/legacy/nn/Container.py", line 32, in updateParameters
    self.applyToModules(lambda m: m.updateParameters(learningRate))
  File "/usr/local/lib/python3.5/dist-packages/torch/legacy/nn/Container.py", line 26, in applyToModules
    func(module)
  File "/usr/local/lib/python3.5/dist-packages/torch/legacy/nn/Container.py", line 32, in <lambda>
    self.applyToModules(lambda m: m.updateParameters(learningRate))
  File "/usr/local/lib/python3.5/dist-packages/torch/legacy/nn/Module.py", line 79, in updateParameters
    params, gradParams = self.parameters()
TypeError: 'NoneType' object is not iterable
```

This happens whenever the Sequential model has layers without parameters. Removing ReLUs and LogSoftMax solves the problem.

I think this happens because `self.parameters()` returns `None` for `Module`s which don't have parameters and `params, gradParams = None` raises the error. I tried this both on Python2.7 and Python 3.5 and it's the same.

**Comment by iacolippo** [comment]
Solved by #2624
