### ISSUE TITLE
nn.Embedding error when using max_norm

### ISSUE THREAD

**Issue by aron-bordin** [pytorch/pytorch#2620]
```
>>> torch.__version__
'0.2.0_3'
>>> embedding = nn.Embedding(10, 3, max_norm=3, norm_type=2)
>>> input = Variable(torch.LongTensor([[1,2,4,5],[4,3,2,9]]))
>>> embedding(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "AAA/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "AAA/venv/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "AAA/venv/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 48, in forward
    cls._renorm(indices, weight, max_norm, norm_type)
TypeError: _renorm() missing 1 required positional argument: 'norm_type'
```

**Comment by fmassa** [comment]
This has been fixed with the latest version in master, the PR fixing is in https://github.com/pytorch/pytorch/pull/2336

**Comment by karandwivedi42** [comment]
Is there any workaround (since I am using conda binary build of pytorch 2.0)?

**Comment by soumith** [comment]
i'm cutting a minor release this week for the JIT, it should be in that release.
