### ISSUE TITLE
Trouble installing the pytorch

### ISSUE THREAD

**Issue by mantues** [pytorch/pytorch#26276]
I had trouble installing the pytorch from the command line.
`pip install torch torchvision`
The error message below occurs after processing. I would appreciate your assistance.

> $ pip install torch torchvision

Collecting torch
Downloading https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz (128kB)
100% |████████████████████████████████| 133kB 1.7MB/s
Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info/torch.egg-info
writing requirements to pip-egg-info/torch.egg-info/requires.txt
writing pip-egg-info/torch.egg-info/PKG-INFO
writing top-level names to pip-egg-info/torch.egg-info/top_level.txt
writing dependency_links to pip-egg-info/torch.egg-info/dependency_links.txt
writing manifest file 'pip-egg-info/torch.egg-info/SOURCES.txt'
error: package directory 'torch/cuda' does not exist

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fl4Xuy/torch/

**Comment by JamesTrick** [comment]
@mantues - Just as a general troubleshooting step, can you try update your setuptools? Running`pip install --upgrade setuptool` will do this for you. Then try re-install.

**Comment by mantues** [comment]
@JamesTrick 
Thank you for your help.
I tried  `pip install --upgrade setuptool`, but it didn't work.
The error message below occurs

Collecting setuptool
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/setuptool/

**Comment by erfaneshrati** [comment]
`pip3 install nvidia-pyindex` helped me resolve this issue.

**Comment by medlen** [comment]
I had the same problem, I solved it by downgrading python version from 3.10 to 3.8.
