### ISSUE TITLE
There's something wrong with the quantization hypothesis tests (ASAN induced)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26279]
In the past few days, we've had seemingly "unrelated" pull requests persistently induce test failures in Hypothesis on the ASAN configuration:

- https://github.com/pytorch/pytorch/pull/23959
- https://github.com/pytorch/pytorch/pull/23668

The failures look like:

```
Sep 14 04:04:55 ======================================================================
Sep 14 04:04:55 ERROR: test_observer_scriptable (__main__.ObserverTest)
Sep 14 04:04:55 ----------------------------------------------------------------------
Sep 14 04:04:55 Traceback (most recent call last):
Sep 14 04:04:55   File "test_quantization.py", line 781, in test_observer_scriptable
Sep 14 04:04:55     def test_observer_scriptable(self, obs):
Sep 14 04:04:55   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Sep 14 04:04:55     raise the_error_hypothesis_found
Sep 14 04:04:55   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 971, in wrapped_test
Sep 14 04:04:55     state.run()
Sep 14 04:04:55   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 703, in run
Sep 14 04:04:55     info.__expected_traceback,
Sep 14 04:04:55   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 599, in execute
Sep 14 04:04:55     % (test.__name__, text_repr[0])
Sep 14 04:04:55   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 758, in __flaky
Sep 14 04:04:55     raise Flaky(message)
Sep 14 04:04:55 hypothesis.errors.Flaky: Hypothesis test_observer_scriptable(self=<__main__.ObserverTest testMethod=test_observer_scriptable>, obs=MinMaxObserver(min_val=0.04582923310366971, max_val=0.5946920703352084)) produces unreliable results: Falsified on the first call but did not on a subsequent one
Sep 14 04:04:55 
Sep 14 04:04:55 ----------------------------------------------------------------------
```

or

```
Sep 16 11:38:49 ======================================================================
Sep 16 11:38:49 ERROR: test_qadd_scalar_relu (__main__.TestQuantizedOps)
Sep 16 11:38:49 ----------------------------------------------------------------------
Sep 16 11:38:49 Traceback (most recent call last):
Sep 16 11:38:49   File "test_quantized.py", line 141, in test_qadd_scalar_relu
Sep 16 11:38:49     elements=st.floats(-1e6, 1e6, allow_nan=False),
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1012, in wrapped_test
Sep 16 11:38:49     raise the_error_hypothesis_found
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 971, in wrapped_test
Sep 16 11:38:49     state.run()
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 703, in run
Sep 16 11:38:49     info.__expected_traceback,
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 570, in execute
Sep 16 11:38:49     result = self.test_runner(data, run)
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
Sep 16 11:38:49     return function(data)
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 568, in run
Sep 16 11:38:49     return test(*args, **kwargs)
Sep 16 11:38:49   File "test_quantized.py", line 141, in test_qadd_scalar_relu
Sep 16 11:38:49     elements=st.floats(-1e6, 1e6, allow_nan=False),
Sep 16 11:38:49   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 540, in test
Sep 16 11:38:49     raise DeadlineExceeded(runtime, self.settings.deadline)
Sep 16 11:38:49 hypothesis.errors.DeadlineExceeded: Test took 255.47ms, which exceeds the deadline of 200.00ms
Sep 16 11:38:49 
Sep 16 11:38:49 ----------------------------------------------------------------------
```

Unlike #25248, these failures happen deterministically (thanks @jerryzh168!) However, it seems that the tests are still far too brittle.

There's a few obvious ways we could try to fix the symptoms:

* Increase (or disable) Hypothesis deadline
* Double check that we are reseeding the RNG on every *test* (as opposed to once at the beginning of the test suite; if you only do it once, you are susceptible to addition of new tests perturbing the results of other tests)

However, there is also probably something more deeply wrong with these tests (for example, why is `test_qadd_scalar_relu` taking 255ms? Should it *really* be taking that long? Why is `test_observer_scriptable` failing in the first place?) This should be investigated.

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @smessmer @hx89

**Comment by jerryzh168** [comment]
we do have no_deadline decorator: https://github.com/pytorch/pytorch/blob/master/test/hypothesis_utils.py#L258
I remember @zafartahirov mentioned before it's because the old version of hypothesis is counting the time of generating examples into the runtime of tests.

**Comment by smessmer** [comment]
Added @no_deadline to test_qadd_scalar_relu in an attempt to fix master, but now it fails on master due to floating point accuracy, saying -3e-5 is not close enough to zero.

**Comment by smessmer** [comment]
`test_equal` seems to be fragile too, see https://circleci.com/gh/pytorch/pytorch/2877951?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console which fails on master and the fix in https://github.com/pytorch/pytorch/pull/26599

**Comment by gchanan** [comment]
@dzhulgakov can you put someone on this?

**Comment by jerryzh168** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/27616

**Comment by zafartahirov** [comment]
@jerryzh168 Did it fix it? SHould we close this issue?

**Comment by jerryzh168** [comment]
I think so, closing now, please open another issue if similar problems comes up again. @ezyang
