### ISSUE TITLE
problem with mkldnn and march=native on Intel Sandybridge processors

### ISSUE THREAD

**Issue by branfosj** [pytorch/pytorch#26287]
## To Reproduce

1. Build PyTorch with -march=native on an Intel Sandybridge processor
1. Run the test case below. This test case is a simplification of https://github.com/pytorch/pytorch/blob/v1.2.0/test/test_mkldnn.py#L336

Code of:
```python
x = torch.randn(2, dtype=torch.float32)
softmax = torch.nn.Softmax(dim=0)
softmax(x.to_mkldnn())
```

Produces error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rds/bear-apps/devel/2019a/branfosj-eb-1/EL7/EL7-sandybridge/software/PyTorch/1.2.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/rds/bear-apps/devel/2019a/branfosj-eb-1/EL7/EL7-sandybridge/software/PyTorch/1.2.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 982, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "/rds/bear-apps/devel/2019a/branfosj-eb-1/EL7/EL7-sandybridge/software/PyTorch/1.2.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/functional.py", line 1230, in softmax
    ret = input.softmax(dim)
RuntimeError: basic_string::append
```

## Expected behavior

That it should not fail.

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 8.2.0
CMake version: version 3.13.3

Python version: 3.7.2
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.2.0
[conda] Could not collect

PyTorch built from source
Build command: PYTORCH_BUILD_VERSION=1.2.0 PYTORCH_BUILD_NUMBER=1 VERBOSE=1 LDFLAGS="$LDFLAGS -ldl" USE_FFMPEG=ON USE_GLOO_IBVERBS=1 USE_GFLAGS=ON USE_GLOG=ON /rds/bear-apps/devel/2019a/branfosj-eb-4/EL7/EL7-haswell/software/Python/3.7.2-GCCcore-8.2.0/bin/python setup.py build
CFLAGS and CXXFLAGS are set to -O2 -ftree-vectorize -march=native -fno-math-errno

Note that the problem does not appear:
1.  if I remove the `-march=native`
1. nor is it seen on Haswell or Cascadelake processors.

cc @ezyang @gchanan @zou3519 @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by soumith** [comment]
cc: @XiaobingSuper and team

**Comment by boegel** [comment]
I'm seeing the same problem on our Intel Sany Bridge systems, but not on Intel Broadwell, Intel Haswell or Intel Skylake.

**Comment by XiaobingSuper** [comment]
@vpirogov

**Comment by XiaobingSuper** [comment]
@boegel, @branfosj , please wait, I am now to find a Sany Bridge processor to reproduce it. Can you first open MKLDNN verbose by `export MKLDNN_VERBOSE=1` and post the output log for us?

**Comment by boegel** [comment]
@XiaobingSuper That produces a little bit more info, but not a whole lot... Does this help?

```
$ export MKLDNN_VERBOSE=1
$ python -c "import torch; x = torch.randn(2, dtype=torch.float32); softmax = torch.nn.Softmax(dim=0); softmax(x.to_mkldnn())"
mkldnn_verbose,info,Intel(R) MKL-DNN v0.18.1 (Git Hash N/A),Intel(R) Advanced Vector Extensions (Intel(R) AVX)
mkldnn_verbose,exec,reorder,simple:any,undef,in:f32_x out:f32_x,num:1,2,9.2998
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/software/PyTorch/1.2.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/software/PyTorch/1.2.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 982, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "/software/PyTorch/1.2.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/functional.py", line 1230, in softmax
    ret = input.softmax(dim)
RuntimeError: basic_string::append
```

**Comment by XiaobingSuper** [comment]
@boegel, thanks!

**Comment by XiaobingSuper** [comment]
@branfosj , @boegel, I triede to reproduce this issue in my side, but it failed. I list my build steps, please tell me if I am wrong.
### Device dtaills:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               42
Model name:          Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
Stepping:            7
CPU MHz:             2501.000
CPU max MHz:         2501.0000
BogoMIPS:            5002.00
Virtualization:      VT-x
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave osxsave avx lahf_lm ibrs ibpb stibp ssbd
```
### Build commands
```
export CC=gcc
export CFLAGS="-O2 -ftree-vectorize -march=native -fno-math-errno"
export CXX=g++
export CXXFLAGS="-O2 -ftree-vectorize -march=native -fno-math-errno"
python setup.py install
```
I also attatch my build log: [build.log](https://github.com/pytorch/pytorch/files/3629339/build.log)

And then run ```python -c "import torch; x = torch.randn(2, dtype=torch.float32); softmax = torch.nn.Softmax(dim=0); softmax(x.to_mkldnn())"```
I can pass the case and get the following log:
```
mkldnn_verbose,info,Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20),Intel(R) Advanced Vector Extensions (Intel(R) AVX)
mkldnn_verbose,exec,reorder,simple:any,undef,in:f32_x out:f32_x,num:1,2,3.36792
mkldnn_verbose,exec,softmax,ref:any,forward_training,fdata:x fdiff:undef,,x2,0.0529785
```
By the way, I also build [mkldnn](https://github.com/intel/mkl-dnn/tree/v0.18.1) from source with `-march=native`, the mkldnn [softmax test case](https://github.com/intel/mkl-dnn/blob/v0.18.1/tests/gtests/test_softmax_forward.cpp) is also passed.

**Comment by boegel** [comment]
@XiaobingSuper How did you collect the device details exactly (for easy comparison)?
For me, the system has 2 8-core Intel Xeon E5-2670 processors (Intel Sandy Bridge).
That's a different range of processors (server vs consumer), not sure if that has impaxt here...

I've also tested building mkldnn 0.18.1 from source using the same compiler toolchain and `-march=native`, and the full test suite (incl. `test_softmax_backward` and `test_softmax_forward`) passes without problems.

How do we go from here? Is there any additional information we can provide to help figure this out? Any changes to the PyTorch code that could help pinpoint the issue on our end?

**Comment by vpirogov** [comment]
Hi @boegel,

Thanks for running the tests with the library. Intel MKL-DNN v0.18.1 builds with -mnative by default and validated on Intel AVX systems. So the defect in the library is unlikely here. We need @XiaobingSuper to reproduce the issue to debug further.

**Comment by XiaobingSuper** [comment]
@boegel,  Can you collect your device details by `lscpu` so that I can compare your device's instruction set with my device. By the way, can you apply the follwing patch to pytorch,  this patch calls MKLDNN directly. If this patch can pass the test case, it is not MKLDNN's problem but ideep's problem.
```
diff --git a/aten/src/ATen/native/mkldnn/SoftMax.cpp b/aten/src/ATen/native/mkldnn/SoftMax.cpp
index cfd88a1..8ddf7c3 100644
--- a/aten/src/ATen/native/mkldnn/SoftMax.cpp
+++ b/aten/src/ATen/native/mkldnn/SoftMax.cpp
@@ -20,6 +20,10 @@ Tensor mkldnn_softmax(
 #else // AT_MKLDNN_EBABLED
 
 #include <ATen/native/mkldnn/MKLDNNCommon.h>
+#include <ATen/mkldnn/Runtime.h>
+#include <ATen/native/mkldnn/Utils.h>
+
+using namespace mkldnn;
 
 namespace at {
 namespace native {
@@ -32,10 +36,28 @@ Tensor mkldnn_softmax(
       !half_to_float,
       "softmax with half to float conversion is not supported on Mkldnn");
   const int64_t wrapped_dim = maybe_wrap_dim(dim, self.dim());
+  auto output = empty_mkldnn(self.sizes(), self.options());
+  
   ideep::tensor& x = itensor_from_mkldnn(self);
-  ideep::tensor y;
-  ideep::softmax_forward::compute<AllocForMKLDNN>(x, y, wrapped_dim);
-  return new_with_itensor_mkldnn(std::move(y), self.options());
+  ideep::tensor& y = itensor_from_mkldnn(output);
+
+  memory::format format = static_cast<memory::format>(x.get_descriptor().get_mkldnn_memory_desc_t()->format);
+  auto data_t = memory::data_type::f32;
+  auto cpu_engine = CpuEngine::Instance().get_engine();
+
+  auto mem_desc = memory::desc(x.get_dims(), data_t, format);
+  auto mem_prim_desc = memory::primitive_desc(mem_desc, cpu_engine);
+  auto softmax_desc = softmax_forward::desc(prop_kind::forward, mem_desc, wrapped_dim);
+  auto src = memory(mem_prim_desc, x.get_data_handle());
+  auto dst = memory(mem_prim_desc, y.get_data_handle());
+
+  auto softmax_prim_desc = softmax_forward::primitive_desc(softmax_desc, cpu_engine);
+  auto softmax = softmax_forward(softmax_prim_desc, src, dst);
+  std::vector<primitive> net;
+  net.push_back(softmax);
+  Stream::Instance().get_stream().submit(net);
+
+  return output;
 }
 
 } // namespace native
```
Thanks!

**Comment by boegel** [comment]
Output of `lscpu`:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Stepping:              7
CPU MHz:               2599.841
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              5199.93
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts spec_ctrl intel_stibp flush_l1d
```

I'll try the suggested patch, and keep you posted...

**Comment by boegel** [comment]
@XiaobingSuper With the patch applied, all tests (incl. `test_softmax`) pass on Intel Sandy Bridge for me...

**Comment by XiaobingSuper** [comment]
@boegel, I can reproduce it in my laptop(Sand Bridge processor) using GCC8.3 now , so this problem is also associated with complier(my system's gcc is gcc5,), there is patch can solve it, can you test it in your side? if it is ok, I will pull a request.
```
diff --git a/include/ideep/utils.hpp b/include/ideep/utils.hpp
index eae2981..01f5c05 100644
--- a/include/ideep/utils.hpp
+++ b/include/ideep/utils.hpp
@@ -112,14 +112,8 @@ using bytestring = std::string;

 inline void to_bytes(bytestring& bytes, const int arg) {
   auto as_cstring = reinterpret_cast<const char*>(&arg);
-#ifndef __AVX__
   if (arg == 0) return;
   auto len = sizeof(arg) - (__builtin_clz(arg) / 8);
-#else
-  unsigned int lz;
-  asm volatile ("lzcntl %1, %0": "=r" (lz): "r" (arg));
-  auto len = sizeof(int) - lz / 8;
-#endif
   bytes.append(as_cstring, len);
 }
```
you can first in the **pytorch/third_party/ideep/** folder , and then apply this patch. Thanks!

**Comment by boegel** [comment]
@XiaobingSuper I've tested the proposed patch, and it indeed fixes the problem I was seeing on Intel Sandy Bridge with `softmax`.

Out of curiosity: do you know why this code specific to systems supporting AVX was there?

**Comment by boegel** [comment]
@branfosj Can you submit a test report from Intel Sandy Bridge to confirm the fix?

**Comment by boegel** [comment]
@branfosj For https://github.com/easybuilders/easybuild-easyconfigs/pull/9010, I mean :)

**Comment by branfosj** [comment]
Yes, that has fixed the problem. Thanks!

**Comment by ngoldbaum** [comment]
@XiaobingSuper :wave: Hi I'm one of the Engineers from Quansight going through the pytorch issue backlog. It looks like your proposed patch is working for people who have tested it. I was going to try confirming using a Sandy Bridge machine I have access to and then putting in a pull request with a fix to the `ideep` repository but wanted to check with you first if you had plans for a more in-depth change.

**Comment by XiaobingSuper** [comment]
@branfosj , @boegel, we have upgrade mkldnn to [0.21.1](https://github.com/pytorch/pytorch/pull/27597) which can solve this problem. Thanks.

**Comment by gchanan** [comment]
@albanD will verify this is fixed.

**Comment by pinzhenx** [comment]
Closing due to lack of activity
