### ISSUE TITLE
RuntimeError: tensor.ndimension() == static_cast<int64_t>(expected_size.size()) INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by AvivWn** [pytorch/pytorch#26400]
## 🐛 Bug

Hey
I am trying to train my model. I am using Multi-GPU training.
While training I get the next Runtime error:

```
RuntimeError: tensor.ndimension() == static_cast<int64_t>(expected_size.size()) INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1565272279342/work/torch/csrc/cuda/comm.cpp:220, please report a bug to PyTorch.  (gather at /opt/conda/conda-bld/pytorch_1565272279342/work/torch/csrc/cuda/comm.cpp:220)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f75fc2dfe37 in /home/nlp/avivwn/miniconda3/envs/nomlex/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::cuda::gather(c10::ArrayRef<at::Tensor>, long, c10::optional<int>) + 0x6b6 (0x7f75708af616 in /home/nlp/avivwn/miniconda3/envs/nomlex/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x5fa742 (0x7f75fd9c7742 in /home/nlp/avivwn/miniconda3/envs/nomlex/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1c8316 (0x7f75fd595316 in /home/nlp/avivwn/miniconda3/envs/nomlex/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #14: THPFunction_apply(_object*, _object*) + 0x98f (0x7f75fd7ba4bf in /home/nlp/avivwn/miniconda3/envs/nomlex/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #63: __libc_start_main + 0xf5 (0x7f760725c495 in /lib64/libc.so.6)
```

The error occurs in different time each training, sometimes at start and sometimes later, but always when calling the forward method of the model:
`outputs = model(padded_batch_indexed_tokens, padded_batch_tags, sents_lengths)`

## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 418.87.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.16.4
[pip] numpydoc==0.8.0
[pip] pytorch-transformers==1.1.0
[pip] torch==1.2.0
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] mkl                       2019.3                      199  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.2.0                    pypi_0    pypi

## Additional context

Currently I am using try and except over the forward call, but I want to know what this bug means and why it is reproducing only on some training points.

Thanks in advance

**Comment by izdeby** [comment]
Hi, @AvivWn, can you provide some minimal code that reproduces the issue?

**Comment by VitalyFedyunin** [comment]
Leaving untriaged as it still requires reproduction

**Comment by VitalyFedyunin** [comment]
BTW it looks like you have error in your data loading or models and different GPUs return tensors with different sizes.

**Comment by andreaskoepf** [comment]
I  guess the problem is the use of `AT_ASSERT` instead of `AT_CHECK` (https://github.com/pytorch/pytorch/issues/20287) in the `gather()` impl: https://github.com/pytorch/pytorch/blob/0b6186d7783175dcbea8bbab7aed20b592a9a01d/torch/csrc/cuda/comm.cpp#L220

The assert is triggered when tensors of different dimensionality are passed, e.g.:
`torch.cuda.comm.gather([torch.rand(1, device='cuda'), torch.rand(1, 1, device='cuda')])`

**Comment by gchanan** [comment]
removing high priority until we get a reproduction.

**Comment by meikuam** [comment]
I've got this error too while multigpu train of MaskRCNN.

`  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 68, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/cuda/comm.py", line 165, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: tensor.ndimension() == static_cast<int64_t>(expected_size.size()) INTERNAL ASSERT FAILED at /pytorch/torch/csrc/cuda/comm.cpp:220, please report a bug to PyTorch.  (gather at /pytorch/torch/csrc/cuda/comm.cpp:220)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fab8e10b273 in /home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::cuda::gather(c10::ArrayRef<at::Tensor>, long, c10::optional<int>) + 0x6b6 (0x7fab92859cc6 in /home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x5f336a (0x7fabed1f136a in /home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1d3ef4 (0x7fabecdd1ef4 in /home/user/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
`

**Comment by Hansoluo** [comment]
Same error too while multigpu train of CenterNet

```bash
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    hm_loss, cls_loss, total_loss, hm_prec1 = metrics
  File "train.py", line 43, in train_epoch
    hm_pred, logits = model(img, centers=centers)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 68, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/user/.local/lib/python3.6/site-packages/torch/cuda/comm.py", line 165, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: tensor.ndimension() == static_cast<int64_t>(expected_size.size()) ASSERT FAILED at /pytorch/torch/csrc/cuda/comm.cpp:232, please report a bug to PyTorch. (gather at /pytorch/torch/csrc/cuda/comm.cpp
:232)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fb84a94b441 in /home/user/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fb84a94ad7a in /home/user/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: torch::cuda::gather(c10::ArrayRef<at::Tensor>, long, c10::optional<int>) + 0x962 (0x7fb82a3d8792 in /home/user/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x5a230c (0x7fb84b31c30c in /home/user/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x130cfc (0x7fb84aeaacfc in /home/user/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyCFunction_FastCallKeywords + 0x1eb (0x52367b in python3.6)
frame #6: python3.6() [0x57dbf9]
frame #7: _PyEval_EvalFrameDefault + 0x45f (0x57642f in python3.6)
frame #8: python3.6() [0x5754b7]
frame #9: python3.6() [0x57ed4b]
frame #10: python3.6() [0x57dcdc]
frame #11: _PyEval_EvalFrameDefault + 0x45f (0x57642f in python3.6)
frame #12: PyEval_EvalCodeEx + 0x5b2 (0x57e482 in python3.6)
frame #13: python3.6() [0x4fb873]
frame #14: PyObject_Call + 0x3a (0x4e7a2a in python3.6)
frame #15: THPFunction_apply(_object*, _object*) + 0x6b1 (0x7fb84b12d481 in /home/user/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #16: PyCFunction_Call + 0x5f (0x523b9f in python3.6)
frame #17: _PyEval_EvalFrameDefault + 0x5b3b (0x57bb0b in python3.6)
frame #18: python3.6() [0x575894]
frame #19: _PyFunction_FastCallDict + 0x1da (0x57f60a in python3.6)
frame #20: _PyObject_FastCallDict + 0x1d9 (0x4e7359 in python3.6)
frame #21: python3.6() [0x573cad]
frame #22: PySequence_Tuple + 0x137 (0x4e6d27 in python3.6)
frame #23: python3.6() [0x52e690]
frame #24: python3.6() [0x533255]
frame #25: _PyObject_FastCallKeywords + 0x10b (0x4e754b in python3.6)
frame #26: python3.6() [0x57dd85]
frame #27: _PyEval_EvalFrameDefault + 0x45f (0x57642f in python3.6)
frame #28: python3.6() [0x575894]
frame #29: python3.6() [0x57ed4b]
frame #30: python3.6() [0x57dcdc]
frame #31: _PyEval_EvalFrameDefault + 0x45f (0x57642f in python3.6)
frame #32: python3.6() [0x5757ee]
frame #33: python3.6() [0x57ed4b]
frame #34: python3.6() [0x57dcdc]
frame #35: _PyEval_EvalFrameDefault + 0x11dd (0x5771ad in python3.6)
frame #36: python3.6() [0x57ec8d]
frame #37: python3.6() [0x57dcdc]
frame #38: _PyEval_EvalFrameDefault + 0x45f (0x57642f in python3.6)
frame #39: python3.6() [0x5754b7]
frame #40: _PyFunction_FastCallDict + 0x440 (0x57f870 in python3.6)
frame #41: _PyObject_Call_Prepend + 0x24c (0x4e839c in python3.6)
frame #42: PyObject_Call + 0x3a (0x4e7a2a in python3.6)
frame #43: _PyEval_EvalFrameDefault + 0x1b49 (0x577b19 in python3.6)
frame #44: python3.6() [0x5754b7]
frame #45: _PyFunction_FastCallDict + 0x440 (0x57f870 in python3.6)
frame #46: _PyObject_Call_Prepend + 0x24c (0x4e839c in python3.6)
frame #47: PyObject_Call + 0x3a (0x4e7a2a in python3.6)
frame #48: python3.6() [0x538df4]
frame #49: _PyObject_FastCallKeywords + 0x10b (0x4e754b in python3.6)
frame #50: python3.6() [0x57dd85]
frame #51: _PyEval_EvalFrameDefault + 0x11dd (0x5771ad in python3.6)
frame #52: python3.6() [0x57ec8d]
frame #53: python3.6() [0x57dcdc]
frame #54: _PyEval_EvalFrameDefault + 0x45f (0x57642f in python3.6)
frame #55: python3.6() [0x5754b7]
frame #56: PyEval_EvalCode + 0x23 (0x575233 in python3.6)
frame #57: python3.6() [0x5eab22]
frame #58: PyRun_FileExFlags + 0x9a (0x5eaf8a in python3.6)
frame #59: PyRun_SimpleFileExFlags + 0x1a7 (0x5ead47 in python3.6)
frame #60: Py_Main + 0x623 (0x5f0253 in python3.6)
frame #61: main + 0xe9 (0x4d1d99 in python3.6)
frame #62: __libc_start_main + 0xf0 (0x7fb84f027830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #63: _start + 0x29 (0x5e8569 in python3.6)
```

**Comment by Hansoluo** [comment]
There is some error in my code, model had different return values and dimentions. I fixed it by assert the same value.
