### ISSUE TITLE
"type id is VariableTensorId" runtime error for some mobile models

### ISSUE THREAD

**Issue by ljk53** [pytorch/pytorch#26764]
## Summary
Since PR #25597 landed some models started failing to run with mobile build with the following error:
```
type id is VariableTensorId
terminate called after throwing an instance of 'std::runtime_error'
  what():  false CHECK FAILED at ../c10/core/Backend.h
```

For the specific model the problem can be workaround if we use AutoGradMode guard + AutoNonVariableTypeMode guard around torch::jit::load().

But setting AutoNonVariableTypeMode guard before torch::jit::load() will cause some other models to fail:
```
terminating with uncaught exception of type
c10::Error: !v.defined() || v.is_variable()
INTERNAL ASSERT FAILED at../torch/csrc/jit/ir.h (t_ at ../torch/csrc/jit/ir.h:718)
```

We need find root cause and figure out a more robust solution to address both cases.

Edit 1:
PR #25597 is not the root cause. I analyzed root cause and proposed a solution on #26868 .

Edit 2:
We decided to solve this problem with #26908 + #26868.

Edit 3:
In 1.3 release we solve this problem with #27274 + #26868, we replaced #26908 with #27274 due to perf regression.

Edit 4:
We need add guard to TensorMethods.h as revealed by pytorch/android-demo-app#19.

**Comment by ezyang** [comment]
#25597 is supposed to be 100% semantics preserving. How do we know it's the culprit commit? If it is the culprit I will need to rereview it more closely for bugs

**Comment by ljk53** [comment]
@ezyang - I remember I was able to run the failed model on mobile with autograd stripped + use_static_dispatch before. I started seeing this error for some internal models since a couple weeks ago - roughly aligned with the PR. And the VariableTensorId type id in the error message seems to be introduced by this PR. That's how I *guess* it might be related.
But there are a lot of changes in between so I totally could be wrong. It's good to know that the PR is supposed to be semantics preserving. Let me dig into it a bit more first.

**Comment by ezyang** [comment]
Even the tiniest stack trace would be super helpful here.

The error might be related to the static dispatch test, which, to my understanding, is not super well tested in CI. Something like:

```
 switch(tensorTypeIdToBackend(impl::dispatchTypeId(${type_set}))) {
      ${static_dispatch_function_switches}
      default:
          AT_ERROR("${api_name} not implemented for ", at::toString(${type_set}));
  }
```

dispatchTypeId can return a variable type id if it is passed a variable and variable mode is enabled. That would subsequently fail. Let me cut a PR that you can try testing with.

**Comment by ljk53** [comment]
The problem happened during jit::load(), without NonVariable guard, it hits the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  false CHECK FAILED at ../c10/core/Backend.h
The above operation failed in interpreter, with the following stack trace:
at code/__torch__/torch/nn/_intrinsic/quantized/modules/conv_relu.py:66:10
    _22 = self.stride
    _23 = self.padding
    _24 = self.dilation
    _25 = self.groups
    _26, _27, = _22
    _28 = [_26, _27]
    _29, _30, = _23
    _31 = [_29, _30]
    _32, _33, = _24
    _34 = ops.quantized.conv_prepack(_20, _21, _28, _31, [_32, _33], _25)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    self._packed_params = _34
    self.weight_scale = torch.q_scale(_20)
    self.scale = (state)[12]
    self.zero_point = (state)[13]
    return None
  def _weight_bias(self: __torch__.torch.nn._intrinsic.quantized.modules.conv_relu.ConvReLU2d) -> Tuple[Tensor, Optional[Tensor]]:
    _35, _36 = ops.quantized.conv_unpack(self._packed_params)
    return (_35, _36)
  def set_weight_bias(self: __torch__.torch.nn._intrinsic.quantized.modules.conv_relu.ConvReLU2d,
Compiled from code at /home/supriyar/miniconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/quantized/modules/conv.py:107:30
    def set_weight_bias(self, w, b):
        # type: (torch.Tensor, Optional[torch.Tensor]) -> None
        self._packed_params = torch.ops.quantized.conv_prepack(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            w, b, self.stride, self.padding, self.dilation, self.groups)
        self.weight_scale = w.q_scale()

Aborted (core dumped)
```

Seems the real problem is: Usually it only calls variable_factories.h methods during model load and variable_factories.h methods have NonVariable guards. For quantized model it calls other ops like conv_prepack, which are not wrapped by NonVariable guards.

**Comment by ljk53** [comment]
Reopen for https://github.com/pytorch/android-demo-app/issues/19

Repro setups:
1. checkout "https://github.com/junjuew/pytorch-android-issue-19" and follow the readme to get traced model: "serialized.pt";

2. run "scripts/build_mobile.sh -DBUILD_BINARY=ON" to create a host binary with mobile build config (disable autograd, use static dispatch, etc);

3. run "build_mobile/bin/speed_benchmark_torch --model=/tmp/serialized.pt --input_dims="1,3,224,224" --input_type=float --iter=1" in gdb:
```
#6  0x000000000102a3ad in c10::tensorTypeIdToBackend ()
#7  0x000000000102a77c in torch::jit::(anonymous namespace)::tensorEqual(at::Tensor const&, at::Tensor const&) ()
#8  0x000000000102b580 in torch::jit::EqualNode::operator()(torch::jit::Node const*, torch::jit::Node const*) const ()
#9  0x000000000106bf5d in std::pair<std::__detail::_Node_iterator<torch::jit::Node*, true, true>, bool> std::_Hashtable<torch::jit::Node*, torch::jit::Node*, std::allocator<torch::jit::Node*>, std::__detail::_Identity, torch::jit::EqualNode, torch::jit::HashNode, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_insert<torch::jit::Node* const&>(torch::jit::Node* const&, std::integral_constant<bool, true>) ()
#10 0x000000000106b9af in torch::jit::(anonymous namespace)::ConstantPooling(torch::jit::Block*, std::unordered_set<torch::jit::Node*, torch::jit::HashNode, torch::jit::EqualNode, std::allocator<torch::jit::Node*> >&, torch::jit::AliasDb const&) ()
#11 0x000000000106bc6c in torch::jit::ConstantPooling(std::shared_ptr<torch::jit::Graph> const&) ()
#12 0x000000000112da13 in torch::jit::script::runCleanupPasses(std::shared_ptr<torch::jit::Graph>&) ()
#13 0x000000000115e418 in torch::jit::script::to_ir::to_ir(torch::jit::script::Def const&, std::shared_ptr<torch::jit::script::Resolver>, torch::jit::script::Self const*, torch::jit::Function&) ()
#14 0x0000000001130159 in torch::jit::script::CompilationUnit::define(c10::optional<c10::QualifiedName> const&, torch::jit::script::Def const&, std::shared_ptr<torch::jit::script::Resolver> const&, torch::jit::script::Self const*, std::unordered_map<std::string, torch::jit::Function*, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, torch::jit::Function*> > > const&, bool) const::{lambda(torch::jit::Function&)#1}::operator()(torch::jit::Function&) const ()
#15 0x00000000011ba430 in torch::jit::Function::ensure_defined() ()
#16 0x000000000112fc68 in torch::jit::script::CompilationUnit::define(c10::optional<c10::QualifiedName> const&, std::vector<torch::jit::script::Def, std::allocator<torch::jit::script::Def> > const&, std::vector<std::shared_ptr<torch::jit::script::Resolver>, std::allocator<std::shared_ptr<torch::jit::script::Resolver> > > const&, torch::jit::script::Self const*, bool) ()
#17 0x000000000100dd54 in torch::jit::script::SourceImporterImpl::importClass(c10::QualifiedName const&, torch::jit::script::ClassDef const&, bool) ()
#18 0x000000000100ea5d in torch::jit::script::SourceImporterImpl::importNamedType(std::string const&, torch::jit::script::ClassDef const&) ()
#19 0x000000000101186c in torch::jit::script::SourceImporterImpl::findNamedType(c10::QualifiedName const&) ()
#20 0x0000000001005f63 in torch::jit::script::SourceImporter::loadNamedType(c10::QualifiedName const&) const ()
#21 0x0000000001012d0c in std::_Function_handler<c10::StrongTypePtr (c10::QualifiedName const&), torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::string const&)::{lambda(c10::QualifiedName const&)#2}>::_M_invoke(std::_Any_data const&, c10::QualifiedName const&) ()
#22 0x0000000000ff4be5 in torch::jit::Unpickler::readInstruction() ()
#23 0x0000000000ff6930 in torch::jit::Unpickler::run() ()
#24 0x0000000000ff6a74 in torch::jit::Unpickler::parse_ivalue() ()
#25 0x0000000001012877 in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::string const&) ()
#26 0x0000000001014196 in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::deserialize(c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) ()
```

**Comment by ezyang** [comment]
Yes I think that's the right call. Are you planning to redo it or should I resubmit?
