### ISSUE TITLE
[JIT] Overload mechanism doesn't seem to properly extract schema

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#26847]
```
import torch

class FooBar(torch.nn.Module):
    __overloads__ = {'kek': ['top_kek']}

    def kek(self):
        return True

    @torch.jit.export
    def top_kek(self):
        return False

    @torch.jit.export
    def test(self):
        return self.kek()

    def forward(self):
        return torch.rand(3, 4)

f = FooBar()
torch.jit.script(f)
```

Output

```
Traceback (most recent call last):
  File "overload_repro.py", line 21, in <module>
    torch.jit.script(f)
  File "/home/jamesreed/pytorch/torch/jit/__init__.py", line 1188, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/home/jamesreed/pytorch/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/jamesreed/pytorch/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/jamesreed/pytorch/torch/jit/__init__.py", line 1408, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 

top_kek() -> ():
Expected at most 0 arguments but found 1 positional arguments.
:
at overload_repro.py:15:15
    @torch.jit.export
    def test(self):
        return self.kek()
               ~~~~~~~~ <--- HERE
```

In the example, I printed out the schema that we're trying to match against, and that turns out to be `top_kek() -> ()`, which seems incorrect since it should at least have a `self`

cc @suo

**Comment by eellison** [comment]
`__overloads__` should be deleted, since it's a deprecated way of doing overloads. It's currently blocked by the use of `ScriptModule` with overloads with `QuantizedLSTM`.  

The recommended method using `torch.jit._overload_method` works for your example above. `@_overload_method` wasn't implemented for `ScriptModule` api since we're deprecating it.

```
class FooBar(torch.nn.Module):
    @torch.jit._overload_method
    def kek(self):
        # type: () -> bool
        pass

    @torch.jit.export
    def kek(self):
        return True

    @torch.jit.export
    def test(self):
        return self.kek()

    def forward(self):
        return torch.rand(3, 4)

f = FooBar()
torch.jit.script(f)
```

**Comment by jamesr66a** [comment]
@eellison in this case that doesn't actually work because I want to switch which method is called between Python and script. @driazati actually showed me `torch.jit.is_scripting`, so i'm unblocked on this

**Comment by suo** [comment]
This was fixed during the frontend rewrite, the repro behaves correctly now (even for old `__overloads__` style stuff)
