### ISSUE TITLE
buidling pytorch：subprocess.CalledProcessError

### ISSUE THREAD

**Issue by leemengxing** [pytorch/pytorch#26883]
```
General:
--   CMake version         : 3.6.3
--   CMake command         : /home/limengxing/anaconda3/envs/torch_source/bin/cmake
--   System                : Linux
--   C++ compiler          : /home/limengxing/gcc-5.4/bin/g++
--   C++ compiler id       : GNU
--   C++ compiler version  : 5.4.0
--   BLAS                  : MKL
--   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_ML=1;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;IDEEP_USE_MKL;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /home/limengxing/anaconda3/envs/torch_source;/usr/local/cuda
--   CMAKE_INSTALL_PREFIX  : /home/limengxing/pytorch/torch
-- 
--   TORCH_VERSION         : 1.3.0
--   CAFFE2_VERSION        : 1.3.0
--   BUILD_CAFFE2_MOBILE   : ON
--   USE_STATIC_DISPATCH   : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.6.2
--     Python executable   : /home/limengxing/anaconda3/envs/torch_source/bin/python
--     Pythonlibs version  : 3.6.2
--     Python library      : /home/limengxing/anaconda3/envs/torch_source/lib/libpython3.6m.so.1.0
--     Python includes     : /home/limengxing/anaconda3/envs/torch_source/include/python3.6m
--     Python site-packages: lib/python3.6/site-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   INTERN_BUILD_MOBILE   : 
--   USE_ASAN              : OFF
--   USE_CUDA              : True
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 10.0
--     cuDNN version       : 7.5.1
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so
--     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /home/limengxing/gcc-5.4/bin/gcc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_MKLDNN_CBLAS      : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : ON
--   USE_TBB               : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : OFF
--     USE_GLOO            : ON
--   BUILD_NAMEDTENSOR   : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;pytorch_qnnpack;nnpack;cpuinfo;fbgemm;fp16;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring incomplete, errors occurred!
See also "/home/limengxing/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/limengxing/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 756, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/home/limengxing/pytorch/tools/build_pytorch_libs.py", line 56, in build_caffe2
    rerun_cmake)
  File "/home/limengxing/pytorch/tools/setup_helpers/cmake.py", line 318, in generate
    self.run(args, env=my_env)
  File "/home/limengxing/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/limengxing/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/limengxing/anaconda3/envs/torch_source', '-DNUMPY_INCLUDE_DIR=/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/limengxing/anaconda3/envs/torch_source/bin/python', '-DPYTHON_INCLUDE_DIR=/home/limengxing/anaconda3/envs/torch_source/include/python3.6m', '-DPYTHON_LIBRARY=/home/limengxing/anaconda3/envs/torch_source/lib/libpython3.6m.so.1.0', '-DTORCH_BUILD_VERSION=1.3.0a0+0a8a779', '-DUSE_CUDA=True', '-DUSE_NUMPY=True', '/home/limengxing/pytorch']' returned non-zero exit status 1.
```

**Comment by leemengxing** [comment]
thank you for your help

**Comment by leemengxing** [comment]
When I tried to update cmake = 3.9, the problem was solved. But another problem arises again.
[3263/3411] Linking CXX shared module caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so
ninja: build stopped: subcommand failed.

**Comment by vincentqb** [comment]
Can you provide the steps to reproduce? Please also copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py). You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

If you do not need GPU support, you can try adding the environment variable `NO_CUDA=1`.

**Comment by leemengxing** [comment]
Thank you for your help. I've solved this problem. This problem is because I did not install ncll.

**Comment by syqlyx** [comment]
> Thank you for your help. I've solved this problem. This problem is because I did not install ncll.

Hi, I encountered the same problem and I want to confirm whether you mean **nccl** instead of **ncll**?
