### ISSUE TITLE
opset11 _interpolate NameErro:name "offset" is not defined

### ISSUE THREAD

**Issue by leemengxing** [pytorch/pytorch#26956]
## To Reproduce

1.3.0a0+0a8a779
[ResNet] Initialize weights...
Traceback (most recent call last):
  File "/home/limengxing/pycharm_folder/Human-Segmentation-PyTorch/export_onnx.py", line 48, in <module>
    output_names=outputs,dynamic_axes=dynamic_axes,verbose=True,opset_version=11)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/utils.py", line 355, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/utils.py", line 235, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/utils.py", line 592, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/home/limengxing/anaconda3/envs/torch_source/lib/python3.6/site-packages/torch/onnx/symbolic_opset11.py", line 51, in symbolic_fn
    offsets = g.op("Constant", value_t=torch.ones(offset, dtype=torch.int64))
NameError: name 'offset' is not defined

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.0a0+0a8a779
 - OS (e.g., Linux):centos7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version:3.6
 - CUDA/cuDNN version:10.0/7.5
 - GPU models and configuration:
 - Any other relevant information:

**Comment by leemengxing** [comment]
To use linear interpolation, I compiled torch from the source code and set opset = 11, but why did I return such an error?I'm converting deeplabv3 + model from pytrch to onnx

**Comment by YanxianChen** [comment]
I have the same problem. Have you solved it？

**Comment by garymm** [comment]
@leemengxing is this still an issue on the latest PyTorch nightly? If so please provide full repro instructions.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
