### ISSUE TITLE
datasets.ImageFolder error  "in __getattr__ raise AttributeError(name) AttributeError: __exit__"

### ISSUE THREAD

**Issue by tryerrorman** [pytorch/pytorch#2701]
When I use the datasets.ImageFolder,  I came across the following error:

```
Traceback (most recent call last):
  File "/home/fenglei/app/pycharm/helpers/pydev/pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/fenglei/app/pycharm/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fenglei/PycharmProjects/transfer-learning/transferlearningtutorial.py", line 121, in <module>
    model_ft = train_model(model_ft, criterion, optimizer_ft, exp_lr_scheduler,num_epochs=25)
  File "/home/fenglei/PycharmProjects/transfer-learning/transferlearningtutorial.py", line 69, in train_model
    for i, data in enumerate(dset_loaders[phase]):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torchvision/datasets/folder.py", line 118, in __getitem__
    img = self.loader(path)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/datasets/folder.py", line 65, in default_loader
    return pil_loader(path)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/datasets/folder.py", line 45, in pil_loader
    with Image.open(f) as img:
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: __exit__

```

By debugging, found the error occur in the "pil_loader(path):" function

When I change the function as the following, the error disappear.

```
def pil_loader(path):

    # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)

    with open(path, 'rb') as f:

        # with Image.open(f) as img:

        #     return img.convert('RGB')

        img = Image.open(f)

        return  img.convert('RGB')
```

Can any one tell me why?

**Comment by varunagrawal** [comment]
You need to return the function call outside your context manager.

**Comment by tryerrorman** [comment]
@varunagrawal  can you explain in more detail. The "pil_loader(path):" is in the pytorch official files. Should   I edit the codes there, or should I change the way to use the function datesets.ImageFolder.

Thank you!

**Comment by gddingcs** [comment]
I've also come across this problem today, anyone throwing some light on it?

**Comment by gddingcs** [comment]
I edited the source file `folder.py` making following changes. Seems working now.

`    with open(path, 'rb') as f:
       # with Image.open(f) as img:
          #  return img.convert('RGB')
	img = Image.open(f)
	return img.convert('RGB')`

**Comment by varunagrawal** [comment]
@tryerrorman what version of PIL are you using? From a closer inspection of the error, it seems that the context manager support of the PIL Image class is missing.
I checked the source code for the Image class and it does have context manager support.

**Comment by ghju** [comment]
I had the same issue, and upgrading the Pillow library resolved it.
Try this:
`pip install --upgrade Pillow `

**Comment by mp4253** [comment]
I am having error coming in my code that raise attributeerror(name).
So what to be done now??
