### ISSUE TITLE
Error in converting pytorch model to onnx format

### ISSUE THREAD

**Issue by zhangleileiCO** [pytorch/pytorch#27032]
Hi,

We are trying to convert a pytorch model to a onnx format binary file.

We are are facing the following error:
Attempted to trace FusedLayerNormAffineFunction, but tracing of legacy 

here is the error stack:
Traceback (most recent call last):
  File "convert.py", line 85, in <module>
    cli_main()
  File "convert.py", line 81, in cli_main
    main(args)
  File "convert.py", line 76, in main
    torch.onnx.export(model, dummy_input, "onnx_model_name.onnx", verbose=True)
  File "/home/tangyue/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 224, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 192, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/jit/__init__.py", line 196, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/jit/__init__.py", line 251, in forward
    out = self.inner(*trace_inputs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fairseq/fairseq/models/fairseq_model.py", line 247, in forward
    encoder_out = self.encoder(src_tokens, src_lengths=src_lengths, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fairseq/fairseq/models/transformer.py", line 247, in forward
    x = layer(x, encoder_padding_mask)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fairseq/fairseq/models/transformer.py", line 573, in forward
    x = self.maybe_layer_norm(self.self_attn_layer_norm, x, after=True)
  File "/home/fairseq/fairseq/models/transformer.py", line 588, in maybe_layer_norm
    return layer_norm(x)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/.pyenv/versions/torch_3.6.8/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 153, in forward
    input, self.weight, self.bias)
RuntimeError: Attempted to trace FusedLayerNormAffineFunction, but tracing of legacy functions is not supported

 Could you please provide any clue, any help would be greatly appreciated.

**Comment by garymm** [comment]
@zhangleileiCO is this still an issue on latest PyTorch nightly? If so please provide full repro instructions.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
