### ISSUE TITLE
RuntimeError: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /opt/conda/conda-bld/pytorch_1502004572321/work/torch/lib/THC/generic/THCStorage.cu:66

### ISSUE THREAD

**Issue by rsanjaykamath** [pytorch/pytorch#2704]
I encountered this error. 

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1502004572321/work/torch/lib/THC/generic/THCStorage.cu line=66 error=46 : all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "scripts/reader/train.py", line 544, in <module>
    main(args)
  File "scripts/reader/train.py", line 426, in main
    model.cuda()
  File "/people/sanjay/DrQA/drqa/reader/model.py", line 460, in cuda
    self.netowork = self.network.cuda()
  File "/people/sanjay/anaconda2/envs/drqa/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/people/sanjay/anaconda2/envs/drqa/lib/python3.6/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/people/sanjay/anaconda2/envs/drqa/lib/python3.6/site-packages/torch/nn/modules/module.py", line 124, in _apply
    param.data = fn(param.data)
  File "/people/sanjay/anaconda2/envs/drqa/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in <lambda>
    return self._apply(lambda t: t.cuda(device_id))
  File "/people/sanjay/anaconda2/envs/drqa/lib/python3.6/site-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/people/sanjay/anaconda2/envs/drqa/lib/python3.6/site-packages/torch/cuda/__init__.py", line 269, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /opt/conda/conda-bld/pytorch_1502004572321/work/torch/lib/THC/generic/THCStorage.cu:66

Here is the GPU status 

![screenshot from 2017-09-12 10 50 42](https://user-images.githubusercontent.com/18527321/30316662-40a55406-97a8-11e7-9873-ca6c1d34cc8b.png)

Even though GPU 0 is free, it doesn't allow me launch my code.

**Comment by rsanjaykamath** [comment]
Apologies for the issue, I had set an environment variable to use only GPU 1. 

Feels so stupid of me to post it here without checking the code. Sorry!

**Comment by JunhaoWang** [comment]
How did you fix it?

**Comment by rsanjaykamath** [comment]
I had set an environment variable to use GPU 1 in my script, which I forgot to change. Which is why it wasn't using GPU 0.

**Comment by rebeen** [comment]
Restart the program with os.environ["CUDA_VISIBLE_DEVICES"] = '0'
