### ISSUE TITLE
CPU/GPU inconsistency for gradient of x.norm() when x.norm() == 0

### ISSUE THREAD

**Issue by fdraxler** [pytorch/pytorch#2721]
Running backward() on the norm of a tensor with zero norm on the GPU is inconsistent with the behaviour on the CPU. The GPU raises a RuntimeError, the CPU sets the gradient to nan.

This code reproduces the inconsistency:

```
import torch
a = torch.FloatTensor((5,5))
a.zero_()

# Calculate norm  on CPU
v = torch.autograd.Variable(a, requires_grad=True)
n = v.norm()
n.backward()
print(v.grad) # Variable containing: nan nan [torch.FloatTensor of size 2]

# Calculate norm with CUDA
vc = torch.autograd.Variable(a, requires_grad=True).cuda()
nc = vc.norm()
nc.backward() # Raises RuntimeError
print(vc.grad) # never reached
```

Check out the full stack trace to identify the relevant code parts:

```
Traceback (most recent call last):
  File "<ipython-input>", line 1, in <module>
    nc.backward()
  File "/.../site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/.../site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/.../site-packages/torch/autograd/_functions/reduce.py", line 244, in backward
    scale_v = (grad_output / ctx.norm).expand_as(input)
  File "/.../site-packages/torch/autograd/variable.py", line 841, in __div__
    return self.div(other)
  File "/.../site-packages/torch/autograd/variable.py", line 354, in div
    return DivConstant.apply(self, other)
  File "/.../site-packages/torch/autograd/_functions/basic_ops.py", line 171, in forward
    return tensor.div(ctx.constant)
RuntimeError: invalid argument 3: divide by zero at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensorMathPairwise.cu:66
```

My torch version is 0.2.0 (py36h53baedd_4cu80)

**Comment by soumith** [comment]
this should now be fixed on master via https://github.com/pytorch/pytorch/pull/2775
Now subgradient is used at 0 and 0 is returned instead.
