### ISSUE TITLE
Improve error message if Python function is not found on callee instead of crashing

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#27368]
@rohan-varma found that when the target Python function is missing on the callee side when using `rpc`/`remote`, the callee will hit segfault instead of sending the error message back to the caller. 

```python
# On caller
import torch
import torch.distributed as dist

dist.init_process_group("gloo", init_method='tcp://127.0.0.1:12356', world_size=2, rank=1)
dist.init_model_parallel("worker0")

def my_tensor_function(a, b):
    return a + b

ret = dist.rpc_sync("worker1", my_tensor_function, args=(torch.ones(2, 2), torch.ones(2, 2)))
dist.join_rpc()
```

```python
# On callee
import torch.distributed as dist

#def my_tensor_function(a, b):
#        return a + b

dist.init_process_group("gloo", init_method='tcp://127.0.0.1:12356', world_size=2, rank=0)
dist.init_model_parallel("worker1")
dist.join_rpc()
```

For example, the above program will show the following error messages on the callee:

```
Thread 6 "python" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 4177163]
PyErr_Fetch (p_type=0x7fffb37fd740, p_value=0x7fffb37fd748, p_traceback=0x7fffb37fd750) at /tmp/build/80754af9/python_1553721932202/work/Python/errors.c:339          
339     /tmp/build/80754af9/python_1553721932202/work/Python/errors.c: No such file or directory.                                                                     
(gdb) backtrace
#0  PyErr_Fetch (p_type=0x7fffb37fd740, p_value=0x7fffb37fd748, p_traceback=0x7fffb37fd750) at /tmp/build/80754af9/python_1553721932202/work/Python/errors.c:339      
#1  0x00007fffe26bca53 in pybind11::error_already_set::~error_already_set() () from /data/users/shenli/pytorch/torch/lib/libtorch_python.so                           
#2  0x00007fffe23ce0bc in __gxx_exception_cleanup (code=<optimized out>, exc=0x7fffa0000e40)                                                                          
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:49                
#3  __gxx_exception_cleanup (code=<optimized out>, exc=<optimized out>)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:33                
#4  0x00007fffd2d2314b in torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const ()                                            
   from /data/users/shenli/pytorch/torch/lib/libtorch.so
#5  0x00007fffe2be5556 in torch::distributed::rpc::ProcessGroupAgent::enqueueRecv(torch::distributed::rpc::RecvWork)::{lambda(torch::distributed::rpc::RecvWork&)#1}::operator()(torch::distributed::rpc::RecvWork&) const () from /data/users/shenli/pytorch/torch/lib/libtorch_python.so                                                   
#6  0x00007fffcc0cff13 in c10::ThreadPool::main_loop(unsigned long) () from /data/users/shenli/pytorch/torch/lib/libc10.so                                            
#7  0x00007fffe23ea421 in std::execute_native_thread_routine_compat (__p=<optimized out>)                                                                             
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/thread.cc:94                  
#8  0x00007ffff7bc6dd5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007ffff78efead in clone () from /lib64/libc.so.6
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
@mrshenli @rohan-varma Is this still a legit issue? I recall seeing some error handling PRs go in.

**Comment by zhaojuanmao** [comment]
we can catch exception remotely and send the exception back to users. but if server crashes, we should not expect error message right?

**Comment by zhaojuanmao** [comment]
what we can do is to check python function exists or not before executing it and having segment fault. if python function does not exist, we need send error message back to users.

**Comment by rohan-varma** [comment]
@zhaojuanmao Are you working on this or can I take this one?

**Comment by zhaojuanmao** [comment]
@rohan-varma feel free to grab it. thanks for working on it!
