### ISSUE TITLE
Windows nightly conda builds failed for CUDA 10.0

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#27463]
Error text:
```
[1349/2712] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/operators/torch_generated_elementwise_ops.cu.obj
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "C:\w\1\s\TMP_CO~1.6_1\conda\CONDA-~2\PYTORC~1\work\tools\build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "C:\w\1\s\TMP_CO~1.6_1\conda\CONDA-~2\PYTORC~1\work\tools\setup_helpers\cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "C:\w\1\s\TMP_CO~1.6_1\conda\CONDA-~2\PYTORC~1\work\tools\setup_helpers\cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\w\1\s\TMP_CO~1.6_1\conda\CONDA-~2\PYTORC~1\_h_env\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 1.
FAILED: caffe2/CMakeFiles/torch.dir/operators/torch_generated_elementwise_ops.cu.obj 
cmd.exe /C "cd /D %SRC_DIR%\build\caffe2\CMakeFiles\torch.dir\operators && %BUILD_PREFIX%\Library\bin\cmake.exe -E make_directory C:/w/1/s/tmp_conda_3.6_192245/conda/conda-bld/pytorch_1570389883815/work/build/caffe2/CMakeFiles/torch.dir/operators/. && %BUILD_PREFIX%\Library\bin\cmake.exe -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=C:/w/1/s/tmp_conda_3.6_192245/conda/conda-bld/pytorch_1570389883815/work/build/caffe2/CMakeFiles/torch.dir/operators/./torch_generated_elementwise_ops.cu.obj -D generated_cubin_file:STRING=C:/w/1/s/tmp_conda_3.6_192245/conda/conda-bld/pytorch_1570389883815/work/build/caffe2/CMakeFiles/torch.dir/operators/./torch_generated_elementwise_ops.cu.obj.cubin.txt -P C:/w/1/s/tmp_conda_3.6_192245/conda/conda-bld/pytorch_1570389883815/work/build/caffe2/CMakeFiles/torch.dir/operators/torch_generated_elementwise_ops.cu.obj.Release.cmake"
elementwise_ops.cu
elementwise_ops.cu
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include\thrust/detail/type_traits.h(390): error C2065: 'ITEMS_PER_THREAD': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include\thrust/detail/type_traits.h(396): note: see reference to class template instantiation 'thrust::detail::or_<Condition1,Condition2,Condition3,Condition4,Condition5,Condition6,Condition7,Condition8,Condition9,Condition10>' being compiled
CMake Error at torch_generated_elementwise_ops.cu.obj.Release.cmake:281 (message):
  Error generating file
  C:/w/1/s/tmp_conda_3.6_192245/conda/conda-bld/pytorch_1570389883815/work/build/caffe2/CMakeFiles/torch.dir/operators/./torch_generated_elementwise_ops.cu.obj

```

cc @peterjc123

**Comment by peterjc123** [comment]
cc @ezyang

**Comment by ezyang** [comment]
@peterjc123 intermittent failure? I don't see any recent changes to this source file

**Comment by peterjc123** [comment]
Yes, it doesn't appear every time duing builds.

**Comment by peterjc123** [comment]
But it will fail in this specific job only: Windows_CUDA_Conda_Build PY3.5_100

**Comment by pietern** [comment]
I'm surprised that `error C2065: 'ITEMS_PER_THREAD': undeclared identifier` can be intermittent...

Indicates a parallel race in loading the headers in NVCC, perhaps? Really weird...

**Comment by peterjc123** [comment]
@pietern Let's see whether it appears in today's build.

**Comment by peterjc123** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/33700.
