### ISSUE TITLE
torch.histc segfaults if array has inf

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#27464]
```
python3 -c 'import torch; torch.histc(torch.tensor([float("inf")]))'
Segmentation fault (core dumped)
```

Stack trace:
```
#0  0x00007f4d48bbac2a in THFloatTensor_histc () from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch.so
#1  0x00007f4d488f0da5 in at::native::legacy::cpu::_th_histc(at::Tensor const&, long, c10::Scalar, c10::Scalar) () from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch.so
#2  0x00007f4d487f61c7 in at::CPUType::(anonymous namespace)::histc(at::Tensor const&, long, c10::Scalar, c10::Scalar) () from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch.so
#3  0x00007f4d4884e6cb in c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long, c10::Scalar, c10::Scalar), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, c10::Scalar, c10::Scalar> >, at::Tensor (at::Tensor const&, long, c10::Scalar, c10::Scalar)>::call(c10::OperatorKernel*, at::Tensor const&, long, c10::Scalar, c10::Scalar) () from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch.so
#4  0x00007f4d4a7b69d2 in torch::autograd::VariableType::(anonymous namespace)::histc(at::Tensor const&, long, c10::Scalar, c10::Scalar) ()
   from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch.so
#5  0x00007f4d4884e6cb in c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long, c10::Scalar, c10::Scalar), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, c10::Scalar, c10::Scalar> >, at::Tensor (at::Tensor const&, long, c10::Scalar, c10::Scalar)>::call(c10::OperatorKernel*, at::Tensor const&, long, c10::Scalar, c10::Scalar) () from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch.so
#6  0x00007f4d5ebf015b in torch::autograd::THPVariable_histc () from /miniconda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
```

cc @ezyang @SsnL @gchanan

**Comment by nairbv** [comment]
@anjali411 will take a look

**Comment by vadimkantorov** [comment]
the fixing PRs have been merged, closing this
