### ISSUE TITLE
ppc64le test_cuda.py failures

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#2754]
I am using ppc64 Ubuntu 16.04. 
I compiled pytorch version 0.2.0 and am running into some problems with test_cuda.py.
To isolate the failures I commented out some of the types and float_types like so:

types = [
\#    torch.FloatTensor,
\#    torch.DoubleTensor,
\#    torch.LongTensor,
\#    torch.IntTensor,
\#    torch.ShortTensor,
    torch.CharTensor,
\#    torch.ByteTensor,
]

float_types = [
   torch.FloatTensor,
\#   torch.DoubleTensor
]  # TODO: add half...

Then I run "python test_cuda.py"
I get a bunch of these errors:
/opt/pytorch/torch/lib/THC/THCTensorTopK.cuh:431: void gatherTopK(TensorInfo<T, IndexType>, IndexType, IndexType, IndexType, IndexType, TensorInfo<T, IndexType>, IndexType, IndexType, TensorInfo<long, IndexType>, IndexType) [with T = char, IndexType = unsigned int, Dim = 3, Order = true]: block: [64,0,0], thread: [9,0,0] Assertion `writeIndex < outputSliceSize` failed.

the only difference in each line are the block and thread data 

I also get a bunch of these for different tests:

  ERROR: test_CharTensor_tril (__main__.TestCuda)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "mytest_cuda.py", line 358, in tmp
    gpu_tensor = to_gpu(cpu_tensor)
  File "/opt/pytorch/test/common.py", line 89, in to_gpu
    return obj.clone().type(t)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/_utils.py", line 35, in _type
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/pytorch/torch/lib/THC/generic/THCTensorCopy.c:18

all failing at the same THCTensorCopy.c:18

All these failures only happen with type = torch.CharTensor

here is output of nvidia-smi
\# nvidia-smi
Fri Sep 15 21:54:54 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:03:00.0 Off |                    0 |
| N/A   45C    P0    59W / 149W |    426MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:04:00.0 Off |                    0 |
| N/A   30C    P8    30W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000002:03:00.0 Off |                    0 |
| N/A   32C    P8    26W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000002:04:00.0 Off |                    0 |
| N/A   25C    P8    29W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by avmgithub** [comment]
hi, if anyone from the community can give me some pointers on where to keep looking to fix this problem, I would appreciate it.  I've narrowed the failures to 3 operations in the test_cuda.py
   ('topk', small_3d_unique, lambda t: [2, 1, False, True], 'dim_sort'),
   ('topk', small_3d_unique, lambda t: [2, -1, False, True], 'neg_dim_sort'),
   ('topk', small_3d_unique, lambda t: [2, 1, True, True], 'dim_desc_sort'),

And this only happens when using  torch.CharTensor  (but in cuda)

And in the file torch/lib/THC/THCTensorTopK.cuh,  the failure is happening in 
function gatherTopK  , line 431   
assert(writeIndex < outputSliceSize);

I print out the writeIndex and outputSliceSize,  the writeIndex starts at 0 and goes up to a max of  but the outputSliceSize remains at 2.  

Also, I do not know if this has any bearing but on ppc64 char is unsigned while on x86 char is signed.
I appreciate any pointers on which part of the code I can be looking into.

**Comment by avmgithub** [comment]
This seemed to have been fixed by #2440

**Comment by avmgithub** [comment]
issue #2440 changed the use of char in /torch/lib/THC/THCNumerics.cuh to int_8 and uint_8 and therefore fixed the problem in ppc64le as well
