### ISSUE TITLE
torch.nn.Linear(?, 1) does not support batch size 0

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#27619]
## 🐛 Bug

```python
import torch

print(torch.__version__)
print(torch.version.git_version)

l = torch.nn.Linear(100, 1)
print(l(torch.randn(0, 100)))
```

fails with error
```
1.4.0a0+b9b9fd4
b9b9fd4fadc4d4fa0b030941a35011956eafa10b
Traceback (most recent call last):
  File "minimum2.py", line 7, in <module>
    print(l(torch.randn(0, 100)))
  File "/home/xgao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xgao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/xgao/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: invalid argument 13: ldc should be at least max(1, m=0), but have 0 at ../aten/src/TH/generic/THBlas.cpp:367
```

The git version is
```
commit b9b9fd4fadc4d4fa0b030941a35011956eafa10b
Author: peter <peterghost86@gmail.com>
Date:   Wed Oct 9 09:30:02 2019 -0700
```

## To Reproduce

See code above

## Expected behavior

Get a tensor of shape `(0, 1)`

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0a0+b9b9fd4
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.252
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 430.26
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0a0+b9b9fd4
[pip] torchani==0.10.dev15+ga94a267
[pip] torchvision==0.5.0.dev20190917
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl-service               2.3.0            py37h516909a_0    conda-forge
[conda] mkl_fft                   1.0.14           py37h516909a_1    conda-forge
[conda] mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
[conda] pytorch                   1.3.0.dev20190911 py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch-nightly
[conda] torch                     1.3.0a0+b1338a3          pypi_0    pypi
[conda] torchani                  0.10.dev15+ga94a267           dev_0    <develop>
[conda] torchvision               0.5.0.dev20190917          pypi_0    pypi
```

**Comment by zou3519** [comment]
It looks like addmm doesn't have zero-sized-dim support.

**Comment by zasdfgbnm** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/28613
