### ISSUE TITLE
LSTM architecture has met a explosive growth in the training process

### ISSUE THREAD

**Issue by qijiezhao** [pytorch/pytorch#2769]
Hi,  everyone:

I build a model based on LSTM as follows:
    
	class LSTM(nn.Module):
	    def __init__(self,
	                 input_len=1024,
	                 hidden_len=1024,
	                 model_len=12,
	                 target_size=101,
	                 is_softmax=True):
	        super(LSTM,self).__init__()
	        self.hidden_len=hidden_len
	        self.is_softmax=is_softmax
	        self.lstm=nn.LSTM(input_len,hidden_len,batch_first=True)
	        self.target_size=target_size
	        self.hidden2class=nn.Linear(hidden_len,target_size)
	        self.hidden=self.init_hidden()
	    def init_hidden(self):
	        return (Variable(torch.zeros(1, 1, self.hidden_len)),
	            Variable(torch.zeros(1, 1, self.hidden_len)))
	    def forward(self,x):
	        lstm_out,self.hidden=self.lstm(
	            x,self.hidden
	        )
	        cls_scores=self.hidden2class(lstm_out[:,-1,:]).view(-1,self.target_size)
	        if self.is_softmax:
	            cls_scores=F.log_softmax(cls_scores)
	        return cls_scores
and the training process is as follows:

	def train(train_data,model,criterion,optimizer,epoch):
	    model.train()
	    for i,(input,target) in enumerate(train_data):
	
	        if use_cuda:
	            target=target.cuda(async=True)
	        input_var=torch.autograd.Variable(input)
	        target_var=torch.autograd.Variable(target)
	
	        output=model(input_var)
	        loss=criterion(output,target_var)
	
	        prec1,prec5=accuracy(output.data,target,topk=(1,5))
	        losses.update(loss.data[0],input.size(0))
	
	        optimizer.zero_grad()
	        loss.backward(retain_graph=True)
	        optimizer.step()
       
 `

When not add the parameter "retain_graph" in the loss.backward function, I received an error message:

	Traceback (most recent call last):
	  File "temporal_pool.py", line 328, in <module>
	    main()
	  File "temporal_pool.py", line 174, in main
	    train(train_data,model,loss_function,optimizer,epoch)
	  File "temporal_pool.py", line 216, in train
	    loss.backward()
	  File "/opt/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
	    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
	  File "/opt/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
	    variables, grad_variables, retain_graph)
	  File "/opt/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 91, in apply
	    return self._forward_cls.backward(self, *args)
	  File "/opt/anaconda2/lib/python2.7/site-packages/torch/autograd/_functions/basic_ops.py", line 52, in backward
	    a, b = ctx.saved_variables
	RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

But, when added the parameter,  My training process has met a trouble that, the time consumed each iteration endlessly increasing!  The snapshot is like below:

	2:36,671 - INFO - Epoch: [0][84/190], lr: 0.01000	Time 7.042 (3.650)	Data 0.003 (0.004)	Loss 1.0369 (2.5610)	Prec@1 90.000 (59.741)	Prec@5 94.000 (77)
	2017-09-18 13:22:43,930 - INFO - Epoch: [0][85/190], lr: 0.01000	Time 7.259 (3.692)	Data 0.003 (0.004)	Loss 0.6710 (2.5391)	Prec@1 96.000 (60.163)	Prec@5 100.000 (7)
	2017-09-18 13:22:51,523 - INFO - Epoch: [0][86/190], lr: 0.01000	Time 7.593 (3.737)	Data 0.003 (0.004)	Loss 0.8195 (2.5193)	Prec@1 98.000 (60.598)	Prec@5 100.000 (7)
	2017-09-18 13:22:58,701 - INFO - Epoch: [0][87/190], lr: 0.01000	Time 7.179 (3.776)	Data 0.002 (0.004)	Loss 0.7179 (2.4988)	Prec@1 94.000 (60.977)	Prec@5 100.000 (7)
	2017-09-18 13:23:06,277 - INFO - Epoch: [0][88/190], lr: 0.01000	Time 7.576 (3.818)	Data 0.002 (0.004)	Loss 0.9274 (2.4812)	Prec@1 80.000 (61.191)	Prec@5 98.000 (78)
	2017-09-18 13:23:14,097 - INFO - Epoch: [0][89/190], lr: 0.01000	Time 7.820 (3.863)	Data 0.003 (0.004)	Loss 0.7612 (2.4621)	Prec@1 96.000 (61.578)	Prec@5 100.000 (7)
	2017-09-18 13:23:21,841 - INFO - Epoch: [0][90/190], lr: 0.01000	Time 7.744 (3.905)	Data 0.002 (0.004)	Loss 0.6913 (2.4426)	Prec@1 98.000 (61.978)	Prec@5 100.000 (7)
	2017-09-18 13:23:29,396 - INFO - Epoch: [0][91/190], lr: 0.01000	Time 7.555 (3.945)	Data 0.004 (0.004)	Loss 0.8286 (2.4251)	Prec@1 92.000 (62.304)	Prec@5 94.000 (78)
	2017-09-18 13:23:36,920 - INFO - Epoch: [0][92/190], lr: 0.01000	Time 7.524 (3.984)	Data 0.002 (0.004)	Loss 0.8006 (2.4076)	Prec@1 90.000 (62.602)	Prec@5 98.000 (79)
	2017-09-18 13:23:44,831 - INFO - Epoch: [0][93/190], lr: 0.01000	Time 7.911 (4.025)	Data 0.002 (0.004)	Loss 0.7698 (2.3902)	Prec@1 96.000 (62.957)	Prec@5 100.000 (7)
	2017-09-18 13:23:53,035 - INFO - Epoch: [0][94/190], lr: 0.01000	Time 8.204 (4.069)	Data 0.003 (0.004)	Loss 0.8519 (2.3740)	Prec@1 92.000 (63.263)	Prec@5 98.000 (79)
	2017-09-18 13:24:00,845 - INFO - Epoch: [0][95/190], lr: 0.01000	Time 7.810 (4.108)	Data 0.002 (0.004)	Loss 0.7559 (2.3571)	Prec@1 90.000 (63.542)	Prec@5 98.000 (79)
	2017-09-18 13:24:08,728 - INFO - Epoch: [0][96/190], lr: 0.01000	Time 7.883 (4.147)	Data 0.002 (0.004)	Loss 0.7015 (2.3400)	Prec@1 92.000 (63.835)	Prec@5 100.000 (7)
	2017-09-18 13:24:17,098 - INFO - Epoch: [0][97/190], lr: 0.01000	Time 8.370 (4.190)	Data 0.002 (0.004)	Loss 0.8148 (2.3245)	Prec@1 84.000 (64.041)	Prec@5 98.000 (80)
	2017-09-18 13:24:25,550 - INFO - Epoch: [0][98/190], lr: 0.01000	Time 8.452 (4.233)	Data 0.002 (0.004)	Loss 0.7163 (2.3082)	Prec@1 86.000 (64.263)	Prec@5 98.000 (80)
	2017-09-18 13:24:33,836 - INFO - Epoch: [0][99/190], lr: 0.01000	Time 8.286 (4.274)	Data 0.002 (0.004)	Loss 0.6683 (2.2918)	Prec@1 86.000 (64.480)	Prec@5 98.000 (80)
	2017-09-18 13:24:42,290 - INFO - Epoch: [0][100/190], lr: 0.01000	Time 8.454 (4.315)	Data 0.002 (0.004)	Loss 0.6422 (2.2755)	Prec@1 94.000 (64.772)	Prec@5 100.000 (8)
	2017-09-18 13:24:50,672 - INFO - Epoch: [0][101/190], lr: 0.01000	Time 8.382 (4.355)	Data 0.002 (0.004)	Loss 0.7038 (2.2601)	Prec@1 90.000 (65.020)	Prec@5 100.000 (8)
	2017-09-18 13:25:00,062 - INFO - Epoch: [0][102/190], lr: 0.01000	Time 9.389 (4.404)	Data 0.002 (0.004)	Loss 0.6784 (2.2447)	Prec@1 88.000 (65.243)	Prec@5 98.000 (80)
	2017-09-18 13:25:09,428 - INFO - Epoch: [0][103/190], lr: 0.01000	Time 9.366 (4.452)	Data 0.002 (0.004)	Loss 0.7145 (2.2300)	Prec@1 90.000 (65.481)	Prec@5 98.000 (81)
	2017-09-18 13:25:18,487 - INFO - Epoch: [0][104/190], lr: 0.01000	Time 9.059 (4.496)	Data 0.004 (0.004)	Loss 0.6637 (2.2151)	Prec@1 90.000 (65.714)	Prec@5 98.000 (81)
	2017-09-18 13:25:27,151 - INFO - Epoch: [0][105/190], lr: 0.01000	Time 8.664 (4.535)	Data 0.002 (0.004)	Loss 0.6512 (2.2004)	Prec@1 92.000 (65.962)	Prec@5 100.000 (8)
	2017-09-18 13:25:36,368 - INFO - Epoch: [0][106/190], lr: 0.01000	Time 9.217 (4.579)	Data 0.002 (0.004)	Loss 0.6434 (2.1858)	Prec@1 92.000 (66.206)	Prec@5 100.000 (8)
	2017-09-18 13:25:45,407 - INFO - Epoch: [0][107/190], lr: 0.01000	Time 9.039 (4.620)	Data 0.002 (0.004)	Loss 0.6722 (2.1718)	Prec@1 82.000 (66.352)	Prec@5 100.000 (8)
	2017-09-18 13:25:55,124 - INFO - Epoch: [0][108/190], lr: 0.01000	Time 9.717 (4.667)	Data 0.002 (0.004)	Loss 0.5507 (2.1569)	Prec@1 94.000 (66.606)	Prec@5 100.000 (8)
	2017-09-18 13:26:04,149 - INFO - Epoch: [0][109/190], lr: 0.01000	Time 9.024 (4.706)	Data 0.002 (0.004)	Loss 0.5493 (2.1423)	Prec@1 96.000 (66.873)	Prec@5 98.000 (82)
	2017-09-18 13:26:13,310 - INFO - Epoch: [0][110/190], lr: 0.01000	Time 9.161 (4.747)	Data 0.002 (0.004)	Loss 0.6473 (2.1288)	Prec@1 90.000 (67.081)	Prec@5 100.000 (8)
	2017-09-18 13:26:22,946 - INFO - Epoch: [0][111/190], lr: 0.01000	Time 9.636 (4.790)	Data 0.002 (0.004)	Loss 0.5715 (2.1149)	Prec@1 94.000 (67.321)	Prec@5 100.000 (8)
	2017-09-18 13:26:33,026 - INFO - Epoch: [0][112/190], lr: 0.01000	Time 10.081 (4.837)	Data 0.002 (0.004)	Loss 0.5555 (2.1011)	Prec@1 92.000 (67.540)	Prec@5 100.000 (8)
	2017-09-18 13:26:42,249 - INFO - Epoch: [0][113/190], lr: 0.01000	Time 9.223 (4.876)	Data 0.003 (0.004)	Loss 0.4574 (2.0867)	Prec@1 98.000 (67.807)	Prec@5 100.000 (8)
	2017-09-18 13:26:51,917 - INFO - Epoch: [0][114/190], lr: 0.01000	Time 9.668 (4.917)	Data 0.002 (0.004)	Loss 0.7171 (2.0748)	Prec@1 88.000 (67.983)	Prec@5 100.000 (8)
	2017-09-18 13:27:01,647 - INFO - Epoch: [0][115/190], lr: 0.01000	Time 9.730 (4.959)	Data 0.002 (0.004)	Loss 0.4380 (2.0607)	Prec@1 98.000 (68.241)	Prec@5 100.000 (8)
	2017-09-18 13:27:11,674 - INFO - Epoch: [0][116/190], lr: 0.01000	Time 10.027 (5.002)	Data 0.002 (0.004)	Loss 0.5357 (2.0477)	Prec@1 96.000 (68.479)	Prec@5 98.000 (83)
	2017-09-18 13:27:21,527 - INFO - Epoch: [0][117/190], lr: 0.01000	Time 9.853 (5.043)	Data 0.003 (0.004)	Loss 0.5669 (2.0351)	Prec@1 94.000 (68.695)	Prec@5 98.000 (83)
	2017-09-18 13:27:31,056 - INFO - Epoch: [0][118/190], lr: 0.01000	Time 9.529 (5.081)	Data 0.002 (0.004)	Loss 0.6435 (2.0234)	Prec@1 92.000 (68.891)	Prec@5 94.000 (83)
	2017-09-18 13:27:41,082 - INFO - Epoch: [0][119/190], lr: 0.01000	Time 10.026 (5.122)	Data 0.002 (0.004)	Loss 0.5540 (2.0112)	Prec@1 88.000 (69.050)	Prec@5 100.000 (8)
	2017-09-18 13:27:50,734 - INFO - Epoch: [0][120/190], lr: 0.01000	Time 9.653 (5.159)	Data 0.002 (0.004)	Loss 0.5452 (1.9991)	Prec@1 92.000 (69.240)	Prec@5 100.000 (8)
	2017-09-18 13:28:00,682 - INFO - Epoch: [0][121/190], lr: 0.01000	Time 9.948 (5.199)	Data 0.002 (0.004)	Loss 0.8453 (1.9896)	Prec@1 82.000 (69.344)	Prec@5 96.000 (83)
	2017-09-18 13:28:10,677 - INFO - Epoch: [0][122/190], lr: 0.01000	Time 9.995 (5.238)	Data 0.002 (0.004)	Loss 0.6531 (1.9787)	Prec@1 92.000 (69.528)	Prec@5 100.000 (8)
	2017-09-18 13:28:21,240 - INFO - Epoch: [0][123/190], lr: 0.01000	Time 10.562 (5.281)	Data 0.002 (0.004)	Loss 0.5329 (1.9671)	Prec@1 88.000 (69.677)	Prec@5 100.000 (8)
	2017-09-18 13:28:31,558 - INFO - Epoch: [0][124/190], lr: 0.01000	Time 10.318 (5.321)	Data 0.002 (0.004)	Loss 0.6132 (1.9562)	Prec@1 90.000 (69.840)	Prec@5 100.000 (8)
	2017-09-18 13:28:42,142 - INFO - Epoch: [0][125/190], lr: 0.01000	Time 10.585 (5.363)	Data 0.002 (0.004)	Loss 0.4761 (1.9445)	Prec@1 96.000 (70.048)	Prec@5 100.000 (8)
	2017-09-18 13:28:52,802 - INFO - Epoch: [0][126/190], lr: 0.01000	Time 10.660 (5.404)	Data 0.002 (0.004)	Loss 0.4652 (1.9328)	Prec@1 96.000 (70.252)	Prec@5 100.000 (8)
	2017-09-18 13:29:03,661 - INFO - Epoch: [0][127/190], lr: 0.01000	Time 10.859 (5.447)	Data 0.003 (0.004)	Loss 0.4837 (1.9215)	Prec@1 98.000 (70.469)	Prec@5 100.000 (8)
	2017-09-18 13:29:14,862 - INFO - Epoch: [0][128/190], lr: 0.01000	Time 11.201 (5.492)	Data 0.003 (0.004)	Loss 0.4328 (1.9100)	Prec@1 96.000 (70.667)	Prec@5 100.000 (8)
	2017-09-18 13:29:25,954 - INFO - Epoch: [0][129/190], lr: 0.01000	Time 11.092 (5.535)	Data 0.002 (0.004)	Loss 0.6569 (1.9003)	Prec@1 90.000 (70.815)	Prec@5 96.000 (84)
	2017-09-18 13:29:36,764 - INFO - Epoch: [0][130/190], lr: 0.01000	Time 10.810 (5.575)	Data 0.004 (0.004)	Loss 0.4948 (1.8896)	Prec@1 94.000 (70.992)	Prec@5 100.000 (8)
	2017-09-18 13:29:47,688 - INFO - Epoch: [0][131/190], lr: 0.01000	Time 10.923 (5.615)	Data 0.002 (0.004)	Loss 0.4707 (1.8789)	Prec@1 94.000 (71.167)	Prec@5 100.000 (8)
	2017-09-18 13:29:58,851 - INFO - Epoch: [0][132/190], lr: 0.01000	Time 11.164 (5.657)	Data 0.006 (0.004)	Loss 0.5153 (1.8686)	Prec@1 92.000 (71.323)	Prec@5 100.000 (8)
	2017-09-18 13:30:10,097 - INFO - Epoch: [0][133/190], lr: 0.01000	Time 11.246 (5.699)	Data 0.002 (0.004)	Loss 0.4860 (1.8583)	Prec@1 94.000 (71.493)	Prec@5 98.000 (85)
	2017-09-18 13:30:21,123 - INFO - Epoch: [0][134/190], lr: 0.01000	Time 11.026 (5.738)	Data 0.002 (0.004)	Loss 0.4441 (1.8478)	Prec@1 98.000 (71.689)	Prec@5 100.000 (8)
	2017-09-18 13:30:32,364 - INFO - Epoch: [0][135/190], lr: 0.01000	Time 11.242 (5.779)	Data 0.002 (0.004)	Loss 0.6027 (1.8387)	Prec@1 94.000 (71.853)	Prec@5 98.000 (85)
	2017-09-18 13:30:43,511 - INFO - Epoch: [0][136/190], lr: 0.01000	Time 11.147 (5.818)	Data 0.002 (0.004)	Loss 0.4439 (1.8285)	Prec@1 94.000 (72.015)	Prec@5 100.000 (8)
	2017-09-18 13:30:56,065 - INFO - Epoch: [0][137/190], lr: 0.01000	Time 12.553 (5.867)	Data 0.002 (0.004)	Loss 0.4715 (1.8187)	Prec@1 92.000 (72.159)	Prec@5 100.000 (8)
	2017-09-18 13:31:07,832 - INFO - Epoch: [0][138/190], lr: 0.01000	Time 11.768 (5.909)	Data 0.003 (0.004)	Loss 0.4727 (1.8090)	Prec@1 96.000 (72.331)	Prec@5 100.000 (8)
	2017-09-18 13:31:19,450 - INFO - Epoch: [0][139/190], lr: 0.01000	Time 11.618 (5.950)	Data 0.002 (0.004)	Loss 0.4232 (1.7991)	Prec@1 96.000 (72.500)	Prec@5 100.000 (8)
	2017-09-18 13:31:31,482 - INFO - Epoch: [0][140/190], lr: 0.01000	Time 12.032 (5.993)	Data 0.002 (0.004)	Loss 0.5206 (1.7900)	Prec@1 92.000 (72.638)	Prec@5 98.000 (85)
	2017-09-18 13:31:42,916 - INFO - Epoch: [0][141/190], lr: 0.01000	Time 11.434 (6.032)	Data 0.002 (0.003)	Loss 0.3838 (1.7801)	Prec@1 98.000 (72.817)	Prec@5 100.000 (8)
	2017-09-18 13:31:54,853 - INFO - Epoch: [0][142/190], lr: 0.01000	Time 11.936 (6.073)	Data 0.002 (0.003)	Loss 0.6089 (1.7719)	Prec@1 90.000 (72.937)	Prec@5 98.000 (86)
	2017-09-18 13:32:06,966 - INFO - Epoch: [0][143/190], lr: 0.01000	Time 12.113 (6.115)	Data 0.002 (0.003)	Loss 0.4373 (1.7626)	Prec@1 96.000 (73.097)	Prec@5 100.000 (8)
	2017-09-18 13:32:20,037 - INFO - Epoch: [0][144/190], lr: 0.01000	Time 13.070 (6.163)	Data 0.002 (0.003)	Loss 0.5992 (1.7546)	Prec@1 86.000 (73.186)	Prec@5 100.000 (8)
	2017-09-18 13:32:33,020 - INFO - Epoch: [0][145/190], lr: 0.01000	Time 12.983 (6.209)	Data 0.002 (0.003)	Loss 0.4786 (1.7459)	Prec@1 90.000 (73.301)	Prec@5 100.000 (8)
	2017-09-18 13:32:44,395 - INFO - Epoch: [0][146/190], lr: 0.01000	Time 11.375 (6.245)	Data 0.002 (0.003)	Loss 0.3436 (1.7363)	Prec@1 100.000 (73.483)	Prec@5 100.000 (8)
	2017-09-18 13:32:55,576 - INFO - Epoch: [0][147/190], lr: 0.01000	Time 11.181 (6.278)	Data 0.002 (0.003)	Loss 0.3963 (1.7273)	Prec@1 98.000 (73.649)	Prec@5 100.000 (8)
	2017-09-18 13:33:07,442 - INFO - Epoch: [0][148/190], lr: 0.01000	Time 11.867 (6.315)	Data 0.002 (0.003)	Loss 0.4661 (1.7188)	Prec@1 92.000 (73.772)	Prec@5 98.000 (86)
	2017-09-18 13:33:19,375 - INFO - Epoch: [0][149/190], lr: 0.01000	Time 11.932 (6.353)	Data 0.002 (0.003)	Loss 0.4874 (1.7106)	Prec@1 96.000 (73.920)	Prec@5 100.000 (8)
	2017-09-18 13:33:31,265 - INFO - Epoch: [0][150/190], lr: 0.01000	Time 11.890 (6.390)	Data 0.002 (0.003)	Loss 0.3156 (1.7014)	Prec@1 98.000 (74.079)	Prec@5 100.000 (8)
	2017-09-18 13:33:42,987 - INFO - Epoch: [0][151/190], lr: 0.01000	Time 11.722 (6.425)	Data 0.002 (0.003)	Loss 0.2942 (1.6921)	Prec@1 100.000 (74.250)	Prec@5 100.000 (8)
	2017-09-18 13:33:55,927 - INFO - Epoch: [0][152/190], lr: 0.01000	Time 12.940 (6.467)	Data 0.002 (0.003)	Loss 0.4054 (1.6837)	Prec@1 96.000 (74.392)	Prec@5 100.000 (8)
	2017-09-18 13:34:08,886 - INFO - Epoch: [0][153/190], lr: 0.01000	Time 12.959 (6.509)	Data 0.002 (0.003)	Loss 0.5405 (1.6763)	Prec@1 92.000 (74.506)	Prec@5 100.000 (8)
	2017-09-18 13:34:21,638 - INFO - Epoch: [0][154/190], lr: 0.01000	Time 12.752 (6.550)	Data 0.002 (0.003)	Loss 0.4229 (1.6682)	Prec@1 94.000 (74.632)	Prec@5 100.000 (8)
	2017-09-18 13:34:34,436 - INFO - Epoch: [0][155/190], lr: 0.01000	Time 12.798 (6.590)	Data 0.004 (0.003)	Loss 0.4031 (1.6601)	Prec@1 96.000 (74.769)	Prec@5 100.000 (8)
	2017-09-18 13:34:47,209 - INFO - Epoch: [0][156/190], lr: 0.01000	Time 12.773 (6.629)	Data 0.002 (0.003)	Loss 0.4090 (1.6521)	Prec@1 94.000 (74.892)	Prec@5 100.000 (8)
	2017-09-18 13:34:59,683 - INFO - Epoch: [0][157/190], lr: 0.01000	Time 12.474 (6.666)	Data 0.003 (0.003)	Loss 0.3058 (1.6436)	Prec@1 100.000 (75.051)	Prec@5 100.000 (8)
	2017-09-18 13:35:12,320 - INFO - Epoch: [0][158/190], lr: 0.01000	Time 12.636 (6.704)	Data 0.002 (0.003)	Loss 0.5007 (1.6364)	Prec@1 92.000 (75.157)	Prec@5 98.000 (87)
	2017-09-18 13:35:24,694 - INFO - Epoch: [0][159/190], lr: 0.01000	Time 12.374 (6.739)	Data 0.003 (0.003)	Loss 0.4987 (1.6293)	Prec@1 92.000 (75.263)	Prec@5 98.000 (87)
	2017-09-18 13:35:37,976 - INFO - Epoch: [0][160/190], lr: 0.01000	Time 13.282 (6.780)	Data 0.002 (0.003)	Loss 0.2993 (1.6210)	Prec@1 98.000 (75.404)	Prec@5 100.000 (8)
	2017-09-18 13:35:51,475 - INFO - Epoch: [0][161/190], lr: 0.01000	Time 13.499 (6.821)	Data 0.002 (0.003)	Loss 0.5275 (1.6143)	Prec@1 88.000 (75.481)	Prec@5 96.000 (87)
	2017-09-18 13:36:05,019 - INFO - Epoch: [0][162/190], lr: 0.01000	Time 13.545 (6.862)	Data 0.0

So, why did this happen?   Anyone who also ever met this could give me a hand?  Many thanks!

**Comment by aa1607** [comment]
I had this problem just earlier today and I was implementing an RNN as well.  it went away  when i properly detatched my hidden states using h = h.detach() ; c = c.detach(). The model was backpropagating the hidden state further than it should and it was causing massive memory usage. Not sure if thats your problem but I cant see detach or .'repackage_hidden' in your code so that could be it.

**Comment by qijiezhao** [comment]
@aa1607 thx for your answer! 
I solved this problem not long after I propose this issue. As you mentioned, the hidden state is updated following the chained RNN, So the solution is to change another variable to replace the hidden state.
The code is as follows:
    def init_hidden(self,x=None):
        if x==None:
            return (Variable(torch.zeros(self.n_layers, training_batch_size, self.hidden_len)),
                Variable(torch.zeros(self.n_layers, training_batch_size, self.hidden_len)))
        else:
            return (Variable(x[0].data),Variable(x[1].data))

    def forward(self,x):
        lstm_out,self.hidden_out=self.lstm(
            x,self.hidden
        )
        cls_scores=self.hidden2class(self.dropout(lstm_out[:,-1,:])).view(-1,self.target_size)
        if self.is_softmax:
            cls_scores=self.log_softmax(cls_scores)
        self.hidden=self.init_hidden(self.hidden_out)
        return cls_scores

**Comment by FrancescoSaverioZuppichini** [comment]
Hello guys, same problem. I tried with your code, but the error is the same
