### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by oggyoggy448** [pytorch/pytorch#27693]
I am trying to run the following code with anaconda  4.7.12

```
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

```
Unfortunately I'm getting the following error
```
Traceback (most recent call last):
  File "A:/python programming/demo_pytorch/main.py", line 2, in <module>
    import torch
  File "C:\Users\nouma\Anaconda3\lib\site-packages\torch\__init__.py", line 44, in <module>
    import numpy as _np  # noqa: F401
  File "C:\Users\nouma\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\nouma\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\nouma\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

cc @peterjc123

**Comment by peterjc123** [comment]
lt is likely that your environment is messed up. As you can see from the traceback, there are two python environments involved here:
1. C:\Users\nouma\AppData\Roaming\Python\Python37
2. C:\Users\nouma\Anaconda3
Please make sure your `PATH` is clean and you can actually remove one of them first.

**Comment by oggyoggy448** [comment]
I'd removed all the numpy libraries and installed everything from the beginning and that solution worked for me.

**Comment by sthabinod** [comment]
Still not working!

**Comment by sthabinod** [comment]
I am having this kind of problem in django!
Can anybody could solve this or have similar kind of problem.
Error: 
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by peterjc123** [comment]
@sthabinod Well, it means that at least one dependency in the DLL load chain is not a valid one. You may get some better idea if you debug with Process Monitor or the Debugging Tools for Windows.

**Comment by Mubashir-alam** [comment]
I uninstall python and anaconda and reinstall it again but same error.
uncell(0, 'E:/spider 1.py')
Traceback (most recent call last):

  File "E:\spider 1.py", line 8, in <module>
    import pandas as pd

  File "C:\Users\P.C.S\anaconda3\lib\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)

  File "C:\Users\P.C.S\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init

  File "C:\Users\P.C.S\AppData\Roaming\Python\Python38\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))

  File "C:\Users\P.C.S\anaconda3\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by peterjc123** [comment]
@Mubashir-alam You have multiple Python installations. 
C:\Users\P.C.S\anaconda3
C:\Users\P.C.S\AppData\Roaming\Python\Python38
And I guess the second one is 32-bit, not 64-bit. That's why it throws this error.

**Comment by mesamis** [comment]
Just type "print(self._name)" in the place of error - e.g. file "C:\Users\nouma\Anaconda3\lib\ctypes\__init__.py", just before line 356.
Eg.g. in my case if take "C:\gnuwin32\bin\magic1.dll" instead of "magic1.dll".
I fix it to temporary remove "C:\gnuwin32\bin\" from PATH.

**Comment by chulbulji67** [comment]
OSError                                   Traceback (most recent call last)
<ipython-input-3-b7c74cbf5af0> in <module>
----> 1 import sklearn

c:\users\chlbul\appdata\local\programs\python\python37\lib\site-packages\sklearn\__init__.py in <module>
     80     from . import _distributor_init  # noqa: F401
     81     from . import __check_build  # noqa: F401
---> 82     from .base import clone
     83     from .utils._show_versions import show_versions
     84 

c:\users\chlbul\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py in <module>
     11 import re
     12 
---> 13 import numpy as np
     14 
     15 from . import __version__

~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py in <module>
     21             # NOTE: would it change behavior to load ALL
     22             # DLLs at this path vs. the name restriction?
---> 23             WinDLL(os.path.abspath(filename))
     24             DLL_filenames.append(filename)
     25     if len(DLL_filenames) > 1:

c:\users\chlbul\appdata\local\programs\python\python37\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application

what should I do?

**Comment by rezasarvani** [comment]
> Just type "print(self._name)" in the place of error - e.g. file "C:\Users\nouma\Anaconda3\lib\ctypes\__init__.py", line 356", just before line 356.
> Eg.g. in my case if take "C:\gnuwin32\bin\magic1.dll" instead of "magic1.dll".
> I fix it to temporary remove "C:\gnuwin32\bin" from PATH.

Thanks A Lot, That actually solved my problem, i also moved python path higher in the list of environment variables

**Comment by BraveWei** [comment]
@sthabinod Hello, may I know whether you have fixed the issue? I got the same problem, thanks.

**Comment by rezasarvani** [comment]
> @sthabinod Hello, may I know whether you have fixed the issue? I got the same problem, thanks.

Hi, I can not completely recall what have i done to fix it, but probably it has something to do with the comment that i replied to

**Comment by BraveWei** [comment]
@sthabinod Thanks for your kind reply. I fixed the issue related to the package version by reinstalling it.

**Comment by artem-gordeev** [comment]
Hello everyone struggling with python, I had similar problem, may be this experience will help someone
imported sklearn, but program logs said:

File "C:\Users\А\AppData\Roaming\Python\Python38\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\А\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 не является приложением Win32

with sklearn everything was ok, but it used preinstalled scipy, then I decided to reinstall in by
pip uninstall scipy -> pip install scipy 
And solved this problem, so the problem also might be in preinstalled packages

**Comment by oumaimasami** [comment]
C:\Users\user\Desktop\storefront>pipenv install mysqlclient
Installing mysqlclient...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\cli\options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\cli\command.py", line 222, in install
    do_install(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\core.py", line 2161, in do_install
    c = pip_install(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\core.py", line 1550, in pip_install
    pip_args = get_pip_args(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\core.py", line 1388, in get_pip_args
    if project.environment.pip_version >= parse_version("19.0"):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\project.py", line 319, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\project.py", line 299, in get_environment
    environment = Environment(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\environment.py", line 70, in __init__
    self._base_paths = self.get_paths()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\environment.py", line 394, in get_paths
    c = subprocess_run(command)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\utils\processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Sarvesh09** [comment]
I only have 3 files in Python310 folder in c drive ,they are as follows
_tkinter.lib
python3.lib
python310.lib

I dont get which file is conflicting ,when i call a subprocess.
I get the below error :

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Sarvesh\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\MSC IT\Part 2\Project\My project\login.py", line 42, in login_function
    else :subprocess.call('two_people.jpg')
  File "C:\Users\Sarvesh\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Sarvesh\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Sarvesh\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Christiano300** [comment]
I had the same problem with matplotlib, but as it turned out, numpy was causing the issue. I fixed it with "pip install --upgrade numpy"

**Comment by robinwilliamsxu** [comment]
> lt is likely that your environment is messed up. As you can see from the traceback, there are two python environments involved here:
> 
> 1. C:\Users\nouma\AppData\Roaming\Python\Python37
> 2. C:\Users\nouma\Anaconda3
> 
> Please make sure your `PATH` is clean and you can actually remove one of them first.

i delete the different python libary package, and it work,  not the path.

**Comment by Nora-Hosseini** [comment]
Hello everyone,
I am encountering an issue when attempting to load a dll library in Python. I would appreciate any help regarding this issue. Is the problem with compiling dll file ?
--------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[29], line 2
      1 # Load the simulator and controller interface
----> 2 controller_int = ROSCO_ci.ControllerInterface(lib_name,param_filename=param_file)
      3 sim = ROSCO_sim.Sim(turbine,controller_int)
      5 # Define a wind speed history

File ~\ROSCO\rosco\toolbox\control_interface.py:88, in ControllerInterface.__init__(self, lib_name, param_filename, **kwargs)
     85         pass
     87 try:
---> 88     self.init_discon()
     89 except ValueError:
     90     pass

File ~\ROSCO\rosco\toolbox\control_interface.py:97, in ControllerInterface.init_discon(self)
     95 self.torque = 0
     96 # -- discon
---> 97 self.discon = cdll.LoadLibrary(self.lib_name)
     98 self.avrSWAP = np.zeros(self.avr_size)
    100 # Define some avrSWAP parameters, NOTE: avrSWAP indices are offset by -1 from Fortran

File ~\anaconda3\Lib\ctypes\__init__.py:460, in LibraryLoader.LoadLibrary(self, name)
    459 def LoadLibrary(self, name):
--> 460     return self._dlltype(name)

File ~\anaconda3\Lib\ctypes\__init__.py:379, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    376 self._FuncPtr = _FuncPtr
    378 if handle is None:
--> 379     self._handle = _dlopen(self._name, mode)
    380 else:
    381     self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Nora-Hosseini** [comment]
Hello everyone,
I am encountering an issue when attempting to load a dll library in Python. I would appreciate any help regarding this issue. Is the problem with compiling dll file?

--------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[29], line 2
      1 # Load the simulator and controller interface
----> 2 controller_int = ROSCO_ci.ControllerInterface(lib_name,param_filename=param_file)
      3 sim = ROSCO_sim.Sim(turbine,controller_int)
      5 # Define a wind speed history

File ~\ROSCO\rosco\toolbox\control_interface.py:88, in ControllerInterface.__init__(self, lib_name, param_filename, **kwargs)
     85         pass
     87 try:
---> 88     self.init_discon()
     89 except ValueError:
     90     pass

File ~\ROSCO\rosco\toolbox\control_interface.py:97, in ControllerInterface.init_discon(self)
     95 self.torque = 0
     96 # -- discon
---> 97 self.discon = cdll.LoadLibrary(self.lib_name)
     98 self.avrSWAP = np.zeros(self.avr_size)
    100 # Define some avrSWAP parameters, NOTE: avrSWAP indices are offset by -1 from Fortran

File ~\anaconda3\Lib\ctypes\__init__.py:460, in LibraryLoader.LoadLibrary(self, name)
    459 def LoadLibrary(self, name):
--> 460     return self._dlltype(name)

File ~\anaconda3\Lib\ctypes\__init__.py:379, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    376 self._FuncPtr = _FuncPtr
    378 if handle is None:
--> 379     self._handle = _dlopen(self._name, mode)
    380 else:
    381     self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application
