### ISSUE TITLE
Can't install pytorch using pip under Windows 10

### ISSUE THREAD

**Issue by rakso20000** [pytorch/pytorch#27815]
## 🐛 Bug

Trying to install the stable release following instructions from https://pytorch.org/get-started/locally/ results in the message `ERROR: No matching distribution found for torch===1.3.0`.

Trying to install the preview release results in a python error.

## To Reproduce

1. Try to install python as instructed in https://pytorch.org/get-started/locally/

**Stable (1.3)** error:
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch===1.3.0
  ERROR: Could not find a version that satisfies the requirement torch===1.3.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.3.0
```

**Preview (Nightly)** error:
```
Looking in links: https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
Collecting torch
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/fb/01/03fd7e503c16b3dc262483e5555ad40974ab5da8b9879e164b56c1f4ef6f/torchvision-0.2.2.post3-py2.py3-none-any.whl
Requirement already satisfied: pyyaml in c:\program files (x86)\python37-32\lib\site-packages (from torch) (5.1.2)
Requirement already satisfied: numpy in c:\program files (x86)\python37-32\lib\site-packages (from torchvision) (1.17.2)
Collecting pillow>=4.1.1 (from torchvision)
  Using cached https://files.pythonhosted.org/packages/6e/42/cbcafb97c5e288a0340bfdffb883faa14cf1e2edd81727f0bac6d0150d4a/Pillow-6.2.0-cp37-cp37m-win32.whl
Collecting six (from torchvision)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: torch, pillow, six, torchvision
  Running setup.py install for torch: started
    Running setup.py install for torch: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\root\\AppData\\Local\\Temp\\pip-install-sdujsaav\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\root\\AppData\\Local\\Temp\\pip-install-sdujsaav\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\root\AppData\Local\Temp\pip-record-q50tvjyk\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\root\AppData\Local\Temp\pip-install-sdujsaav\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\root\AppData\Local\Temp\pip-install-sdujsaav\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "C:\Program Files (x86)\Python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files (x86)\Python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\root\AppData\Local\Temp\pip-install-sdujsaav\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Program Files (x86)\Python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\root\AppData\Local\Temp\pip-install-sdujsaav\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files (x86)\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\root\\AppData\\Local\\Temp\\pip-install-sdujsaav\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\root\\AppData\\Local\\Temp\\pip-install-sdujsaav\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\root\AppData\Local\Temp\pip-record-q50tvjyk\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

## Expected behavior

PyTorch gets installed.

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1070 Ti
Nvidia driver version: 436.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.2
[conda] Could not collect
```

**Comment by vishwakftw** [comment]
cc: @soumith

**Comment by soumith** [comment]
hmm this makes no sense, the Windows wheels are right there in the files that pypi is looking for. And Python 3.7 is supported.

@peterjc123 do you know what is going on?

**Comment by peterjc123** [comment]
@rakso20000 From the location of your python installation, it seems that you are using Python 32-bit. Please use Python 64-bit instead. @soumith Any ideas to make this more obvious to the users?

**Comment by gchanan** [comment]
Going to put enhancement, since this isn't a bug.  If there's something we can do to make this more obvious, that would be nice.

**Comment by alexeygolyshev** [comment]
I can confirm the installation problem on Windows. conda offers PyTorch 1.0.

```
(torch13) C:\Users\Alexey>conda install pytorch cudatoolkit=10.1 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Anaconda3\envs\torch13

  added / updated specs:
    - cudatoolkit=10.1
    - pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ninja-1.9.0                |   py37h74a9793_0         238 KB
    pytorch-1.0.0              |py3.7_cuda90_cudnn7_1       605.7 MB  pytorch
    ------------------------------------------------------------
                                           Total:       605.9 MB
```
										   
										   
This works: `pip install https://download.pytorch.org/whl/cu101/torch-1.3.0-cp37-cp37m-win_amd64.whl`

**Comment by peterjc123** [comment]
@alexeygolyshev Why do you post here? Is there any relation between your problem and the one in the main topic? Your issue is related to https://github.com/pytorch/pytorch/issues/27745. Please post there, okay?

**Comment by alexeygolyshev** [comment]
@peterjc123 Workaround for `pip` in my comment: `pip install https://download.pytorch.org/whl/cu101/torch-1.3.0-cp37-cp37m-win_amd64.whl`

**Comment by peterjc123** [comment]
@alexeygolyshev That's off-topic. I'll delete your replies here. Please post in the correct location.

**Comment by alexeygolyshev** [comment]
@peterjc123 Why do you think that my comments were off-topic? I successfully installed PyTorch 1.3 and shared my experience. This issue is called "Can't install pytorch using pip under Windows 10". I suggested a solution: `pip install https://download.pytorch.org/whl/cu101/torch-1.3.0-cp37-cp37m-win_amd64.whl`

**Comment by peterjc123** [comment]
Yes, but the author's issue is about installing it in a 32-bit environment. Let me change the name for that.

**Comment by soumith** [comment]
1. we could upload dummy sdist for 32-bit that fail with a better error message. Right now it is compiling the `sdist` but failing with ` ModuleNotFoundError: No module named 'tools.nnwrap'`

**Comment by mcDandy** [comment]
I know, this is for x86 python, but I have x64 version and still got `...ModuleNotFoundError: No module named 'tools.nnwrap...` error

https://github.com/pytorch/pytorch/issues/27815#issuecomment-541394453 helped

**Comment by peterjc123** [comment]
@soumith Do you have a plan to do it? Maybe the message should contain some info like the python version (e.g 3.8), the cpu arch (e.g. 32/64) and os platform(e.g. linux-64/osx-64/win-32/win-64).

**Comment by soumith** [comment]
@peterjc123 low pri right now for me, I likely wont get to it.

**Comment by mantaionut** [comment]
I tried to reproduce using a 32-bit environment but I could not get that specific error when using the nightly build. Instead, I got `Could not find any downloads that satisfy the requirement torch` since there are no compatible packages. Also, this issue happens on Linux as well if you try to install PyTorch in a 32-bit environment.

**Comment by mantaionut** [comment]
Since this issue is pip related and can happen on other platforms as well I will remove the Windows label.

**Comment by iremyux** [comment]
Since the Windows label was removed, I am also removing it from 'Pytorch on Windows' project.
