### ISSUE TITLE
Caffe2 - support for translating layers: res5c_up_pose_pose, res3d_pose_pose and res5c_up_posec with caffe_translator

### ISSUE THREAD

**Issue by xRiot** [pytorch/pytorch#27822]
## 🚀 Feature
`caffe_translator` module in Caffe2 does currently not support: `res5c_up_pose_pose`, `res3d_pose_pose` and `res5c_up_posec` layers.

## Motivation

We're experiencing difficulties with migrating over from Caffe (v1.0.0) to Caffe2 (0.8.2) due to some layers in our pretrained model not being supported yet.

## Pitch

Official support for these missing layers would be greatly appreciated!

## Alternatives

Similar report but not useful for us from facebook/caffe2: [#994](https://github.com/facebookarchive/caffe2/issues/994)

## Additional context

When attempting to convert the model we encounter the following error: 
```
root@50edd6072431:/srv# python -m caffe2.python.caffe_translator pretrained.prototxt pretrained.caffemodel
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
INFO:caffe_translator:Translate layer conv1
INFO:caffe_translator:Translate layer bn_conv1
INFO:caffe_translator:Translate layer scale_conv1
INFO:caffe_translator:Translate layer conv1_relu
INFO:caffe_translator:Translate layer pool1
INFO:caffe_translator:Translate layer res2a_branch1
INFO:caffe_translator:Translate layer bn2a_branch1
INFO:caffe_translator:Translate layer scale2a_branch1
INFO:caffe_translator:Translate layer res2a_branch2a
INFO:caffe_translator:Translate layer bn2a_branch2a
INFO:caffe_translator:Translate layer scale2a_branch2a
INFO:caffe_translator:Translate layer res2a_branch2a_relu
INFO:caffe_translator:Translate layer res2a_branch2b
INFO:caffe_translator:Translate layer bn2a_branch2b
INFO:caffe_translator:Translate layer scale2a_branch2b
INFO:caffe_translator:Translate layer res2a_branch2b_relu
INFO:caffe_translator:Translate layer res2a_branch2c
INFO:caffe_translator:Translate layer bn2a_branch2c
INFO:caffe_translator:Translate layer scale2a_branch2c
INFO:caffe_translator:Translate layer res2a
INFO:caffe_translator:Translate layer res2a_relu
INFO:caffe_translator:Translate layer res2b_branch2a
INFO:caffe_translator:Translate layer bn2b_branch2a
INFO:caffe_translator:Translate layer scale2b_branch2a
INFO:caffe_translator:Translate layer res2b_branch2a_relu
INFO:caffe_translator:Translate layer res2b_branch2b
INFO:caffe_translator:Translate layer bn2b_branch2b
INFO:caffe_translator:Translate layer scale2b_branch2b
INFO:caffe_translator:Translate layer res2b_branch2b_relu
INFO:caffe_translator:Translate layer res2b_branch2c
INFO:caffe_translator:Translate layer bn2b_branch2c
INFO:caffe_translator:Translate layer scale2b_branch2c
INFO:caffe_translator:Translate layer res2b
INFO:caffe_translator:Translate layer res2b_relu
INFO:caffe_translator:Translate layer res2c_branch2a
INFO:caffe_translator:Translate layer bn2c_branch2a
INFO:caffe_translator:Translate layer scale2c_branch2a
INFO:caffe_translator:Translate layer res2c_branch2a_relu
INFO:caffe_translator:Translate layer res2c_branch2b
INFO:caffe_translator:Translate layer bn2c_branch2b
INFO:caffe_translator:Translate layer scale2c_branch2b
INFO:caffe_translator:Translate layer res2c_branch2b_relu
INFO:caffe_translator:Translate layer res2c_branch2c
INFO:caffe_translator:Translate layer bn2c_branch2c
INFO:caffe_translator:Translate layer scale2c_branch2c
INFO:caffe_translator:Translate layer res2c
INFO:caffe_translator:Translate layer res2c_relu
INFO:caffe_translator:Translate layer res3a_branch1
INFO:caffe_translator:Translate layer bn3a_branch1
INFO:caffe_translator:Translate layer scale3a_branch1
INFO:caffe_translator:Translate layer res3a_branch2a
INFO:caffe_translator:Translate layer bn3a_branch2a
INFO:caffe_translator:Translate layer scale3a_branch2a
INFO:caffe_translator:Translate layer res3a_branch2a_relu
INFO:caffe_translator:Translate layer res3a_branch2b
INFO:caffe_translator:Translate layer bn3a_branch2b
INFO:caffe_translator:Translate layer scale3a_branch2b
INFO:caffe_translator:Translate layer res3a_branch2b_relu
INFO:caffe_translator:Translate layer res3a_branch2c
INFO:caffe_translator:Translate layer bn3a_branch2c
INFO:caffe_translator:Translate layer scale3a_branch2c
INFO:caffe_translator:Translate layer res3a
INFO:caffe_translator:Translate layer res3a_relu
INFO:caffe_translator:Translate layer res3b1_branch2a
INFO:caffe_translator:Translate layer bn3b1_branch2a
INFO:caffe_translator:Translate layer scale3b1_branch2a
INFO:caffe_translator:Translate layer res3b1_branch2a_relu
INFO:caffe_translator:Translate layer res3b1_branch2b
INFO:caffe_translator:Translate layer bn3b1_branch2b
INFO:caffe_translator:Translate layer scale3b1_branch2b
INFO:caffe_translator:Translate layer res3b1_branch2b_relu
INFO:caffe_translator:Translate layer res3b1_branch2c
INFO:caffe_translator:Translate layer bn3b1_branch2c
INFO:caffe_translator:Translate layer scale3b1_branch2c
INFO:caffe_translator:Translate layer res3b1
INFO:caffe_translator:Translate layer res3b1_relu
INFO:caffe_translator:Translate layer res3b2_branch2a
INFO:caffe_translator:Translate layer bn3b2_branch2a
INFO:caffe_translator:Translate layer scale3b2_branch2a
INFO:caffe_translator:Translate layer res3b2_branch2a_relu
INFO:caffe_translator:Translate layer res3b2_branch2b
INFO:caffe_translator:Translate layer bn3b2_branch2b
INFO:caffe_translator:Translate layer scale3b2_branch2b
INFO:caffe_translator:Translate layer res3b2_branch2b_relu
INFO:caffe_translator:Translate layer res3b2_branch2c
INFO:caffe_translator:Translate layer bn3b2_branch2c
INFO:caffe_translator:Translate layer scale3b2_branch2c
INFO:caffe_translator:Translate layer res3b2
INFO:caffe_translator:Translate layer res3b2_relu
INFO:caffe_translator:Translate layer res3b3_branch2a
INFO:caffe_translator:Translate layer bn3b3_branch2a
INFO:caffe_translator:Translate layer scale3b3_branch2a
INFO:caffe_translator:Translate layer res3b3_branch2a_relu
INFO:caffe_translator:Translate layer res3b3_branch2b
INFO:caffe_translator:Translate layer bn3b3_branch2b
INFO:caffe_translator:Translate layer scale3b3_branch2b
INFO:caffe_translator:Translate layer res3b3_branch2b_relu
INFO:caffe_translator:Translate layer res3b3_branch2c
INFO:caffe_translator:Translate layer bn3b3_branch2c
INFO:caffe_translator:Translate layer scale3b3_branch2c
INFO:caffe_translator:Translate layer res3b3
INFO:caffe_translator:Translate layer res3b3_relu
INFO:caffe_translator:Translate layer res4a_branch1
INFO:caffe_translator:Translate layer bn4a_branch1
INFO:caffe_translator:Translate layer scale4a_branch1
INFO:caffe_translator:Translate layer res4a_branch2a
INFO:caffe_translator:Translate layer bn4a_branch2a
INFO:caffe_translator:Translate layer scale4a_branch2a
INFO:caffe_translator:Translate layer res4a_branch2a_relu
INFO:caffe_translator:Translate layer res4a_branch2b
INFO:caffe_translator:Translate layer bn4a_branch2b
INFO:caffe_translator:Translate layer scale4a_branch2b
INFO:caffe_translator:Translate layer res4a_branch2b_relu
INFO:caffe_translator:Translate layer res4a_branch2c
INFO:caffe_translator:Translate layer bn4a_branch2c
INFO:caffe_translator:Translate layer scale4a_branch2c
INFO:caffe_translator:Translate layer res4a
INFO:caffe_translator:Translate layer res4a_relu
INFO:caffe_translator:Translate layer res4b1_branch2a
INFO:caffe_translator:Translate layer bn4b1_branch2a
INFO:caffe_translator:Translate layer scale4b1_branch2a
INFO:caffe_translator:Translate layer res4b1_branch2a_relu
INFO:caffe_translator:Translate layer res4b1_branch2b
INFO:caffe_translator:Translate layer bn4b1_branch2b
INFO:caffe_translator:Translate layer scale4b1_branch2b
INFO:caffe_translator:Translate layer res4b1_branch2b_relu
INFO:caffe_translator:Translate layer res4b1_branch2c
INFO:caffe_translator:Translate layer bn4b1_branch2c
INFO:caffe_translator:Translate layer scale4b1_branch2c
INFO:caffe_translator:Translate layer res4b1
INFO:caffe_translator:Translate layer res4b1_relu
INFO:caffe_translator:Translate layer res4b2_branch2a
INFO:caffe_translator:Translate layer bn4b2_branch2a
INFO:caffe_translator:Translate layer scale4b2_branch2a
INFO:caffe_translator:Translate layer res4b2_branch2a_relu
INFO:caffe_translator:Translate layer res4b2_branch2b
INFO:caffe_translator:Translate layer bn4b2_branch2b
INFO:caffe_translator:Translate layer scale4b2_branch2b
INFO:caffe_translator:Translate layer res4b2_branch2b_relu
INFO:caffe_translator:Translate layer res4b2_branch2c
INFO:caffe_translator:Translate layer bn4b2_branch2c
INFO:caffe_translator:Translate layer scale4b2_branch2c
INFO:caffe_translator:Translate layer res4b2
INFO:caffe_translator:Translate layer res4b2_relu
INFO:caffe_translator:Translate layer res4b3_branch2a
INFO:caffe_translator:Translate layer bn4b3_branch2a
INFO:caffe_translator:Translate layer scale4b3_branch2a
INFO:caffe_translator:Translate layer res4b3_branch2a_relu
INFO:caffe_translator:Translate layer res4b3_branch2b
INFO:caffe_translator:Translate layer bn4b3_branch2b
INFO:caffe_translator:Translate layer scale4b3_branch2b
INFO:caffe_translator:Translate layer res4b3_branch2b_relu
INFO:caffe_translator:Translate layer res4b3_branch2c
INFO:caffe_translator:Translate layer bn4b3_branch2c
INFO:caffe_translator:Translate layer scale4b3_branch2c
INFO:caffe_translator:Translate layer res4b3
INFO:caffe_translator:Translate layer res4b3_relu
INFO:caffe_translator:Translate layer res4b4_branch2a
INFO:caffe_translator:Translate layer bn4b4_branch2a
INFO:caffe_translator:Translate layer scale4b4_branch2a
INFO:caffe_translator:Translate layer res4b4_branch2a_relu
INFO:caffe_translator:Translate layer res4b4_branch2b
INFO:caffe_translator:Translate layer bn4b4_branch2b
INFO:caffe_translator:Translate layer scale4b4_branch2b
INFO:caffe_translator:Translate layer res4b4_branch2b_relu
INFO:caffe_translator:Translate layer res4b4_branch2c
INFO:caffe_translator:Translate layer bn4b4_branch2c
INFO:caffe_translator:Translate layer scale4b4_branch2c
INFO:caffe_translator:Translate layer res4b4
INFO:caffe_translator:Translate layer res4b4_relu
INFO:caffe_translator:Translate layer res4b5_branch2a
INFO:caffe_translator:Translate layer bn4b5_branch2a
INFO:caffe_translator:Translate layer scale4b5_branch2a
INFO:caffe_translator:Translate layer res4b5_branch2a_relu
INFO:caffe_translator:Translate layer res4b5_branch2b
INFO:caffe_translator:Translate layer bn4b5_branch2b
INFO:caffe_translator:Translate layer scale4b5_branch2b
INFO:caffe_translator:Translate layer res4b5_branch2b_relu
INFO:caffe_translator:Translate layer res4b5_branch2c
INFO:caffe_translator:Translate layer bn4b5_branch2c
INFO:caffe_translator:Translate layer scale4b5_branch2c
INFO:caffe_translator:Translate layer res4b5
INFO:caffe_translator:Translate layer res4b5_relu
INFO:caffe_translator:Translate layer res4b6_branch2a
INFO:caffe_translator:Translate layer bn4b6_branch2a
INFO:caffe_translator:Translate layer scale4b6_branch2a
INFO:caffe_translator:Translate layer res4b6_branch2a_relu
INFO:caffe_translator:Translate layer res4b6_branch2b
INFO:caffe_translator:Translate layer bn4b6_branch2b
INFO:caffe_translator:Translate layer scale4b6_branch2b
INFO:caffe_translator:Translate layer res4b6_branch2b_relu
INFO:caffe_translator:Translate layer res4b6_branch2c
INFO:caffe_translator:Translate layer bn4b6_branch2c
INFO:caffe_translator:Translate layer scale4b6_branch2c
INFO:caffe_translator:Translate layer res4b6
INFO:caffe_translator:Translate layer res4b6_relu
INFO:caffe_translator:Translate layer res4b7_branch2a
INFO:caffe_translator:Translate layer bn4b7_branch2a
INFO:caffe_translator:Translate layer scale4b7_branch2a
INFO:caffe_translator:Translate layer res4b7_branch2a_relu
INFO:caffe_translator:Translate layer res4b7_branch2b
INFO:caffe_translator:Translate layer bn4b7_branch2b
INFO:caffe_translator:Translate layer scale4b7_branch2b
INFO:caffe_translator:Translate layer res4b7_branch2b_relu
INFO:caffe_translator:Translate layer res4b7_branch2c
INFO:caffe_translator:Translate layer bn4b7_branch2c
INFO:caffe_translator:Translate layer scale4b7_branch2c
INFO:caffe_translator:Translate layer res4b7
INFO:caffe_translator:Translate layer res4b7_relu
INFO:caffe_translator:Translate layer res4b8_branch2a
INFO:caffe_translator:Translate layer bn4b8_branch2a
INFO:caffe_translator:Translate layer scale4b8_branch2a
INFO:caffe_translator:Translate layer res4b8_branch2a_relu
INFO:caffe_translator:Translate layer res4b8_branch2b
INFO:caffe_translator:Translate layer bn4b8_branch2b
INFO:caffe_translator:Translate layer scale4b8_branch2b
INFO:caffe_translator:Translate layer res4b8_branch2b_relu
INFO:caffe_translator:Translate layer res4b8_branch2c
INFO:caffe_translator:Translate layer bn4b8_branch2c
INFO:caffe_translator:Translate layer scale4b8_branch2c
INFO:caffe_translator:Translate layer res4b8
INFO:caffe_translator:Translate layer res4b8_relu
INFO:caffe_translator:Translate layer res4b9_branch2a
INFO:caffe_translator:Translate layer bn4b9_branch2a
INFO:caffe_translator:Translate layer scale4b9_branch2a
INFO:caffe_translator:Translate layer res4b9_branch2a_relu
INFO:caffe_translator:Translate layer res4b9_branch2b
INFO:caffe_translator:Translate layer bn4b9_branch2b
INFO:caffe_translator:Translate layer scale4b9_branch2b
INFO:caffe_translator:Translate layer res4b9_branch2b_relu
INFO:caffe_translator:Translate layer res4b9_branch2c
INFO:caffe_translator:Translate layer bn4b9_branch2c
INFO:caffe_translator:Translate layer scale4b9_branch2c
INFO:caffe_translator:Translate layer res4b9
INFO:caffe_translator:Translate layer res4b9_relu
INFO:caffe_translator:Translate layer res4b10_branch2a
INFO:caffe_translator:Translate layer bn4b10_branch2a
INFO:caffe_translator:Translate layer scale4b10_branch2a
INFO:caffe_translator:Translate layer res4b10_branch2a_relu
INFO:caffe_translator:Translate layer res4b10_branch2b
INFO:caffe_translator:Translate layer bn4b10_branch2b
INFO:caffe_translator:Translate layer scale4b10_branch2b
INFO:caffe_translator:Translate layer res4b10_branch2b_relu
INFO:caffe_translator:Translate layer res4b10_branch2c
INFO:caffe_translator:Translate layer bn4b10_branch2c
INFO:caffe_translator:Translate layer scale4b10_branch2c
INFO:caffe_translator:Translate layer res4b10
INFO:caffe_translator:Translate layer res4b10_relu
INFO:caffe_translator:Translate layer res4b11_branch2a
INFO:caffe_translator:Translate layer bn4b11_branch2a
INFO:caffe_translator:Translate layer scale4b11_branch2a
INFO:caffe_translator:Translate layer res4b11_branch2a_relu
INFO:caffe_translator:Translate layer res4b11_branch2b
INFO:caffe_translator:Translate layer bn4b11_branch2b
INFO:caffe_translator:Translate layer scale4b11_branch2b
INFO:caffe_translator:Translate layer res4b11_branch2b_relu
INFO:caffe_translator:Translate layer res4b11_branch2c
INFO:caffe_translator:Translate layer bn4b11_branch2c
INFO:caffe_translator:Translate layer scale4b11_branch2c
INFO:caffe_translator:Translate layer res4b11
INFO:caffe_translator:Translate layer res4b11_relu
INFO:caffe_translator:Translate layer res4b12_branch2a
INFO:caffe_translator:Translate layer bn4b12_branch2a
INFO:caffe_translator:Translate layer scale4b12_branch2a
INFO:caffe_translator:Translate layer res4b12_branch2a_relu
INFO:caffe_translator:Translate layer res4b12_branch2b
INFO:caffe_translator:Translate layer bn4b12_branch2b
INFO:caffe_translator:Translate layer scale4b12_branch2b
INFO:caffe_translator:Translate layer res4b12_branch2b_relu
INFO:caffe_translator:Translate layer res4b12_branch2c
INFO:caffe_translator:Translate layer bn4b12_branch2c
INFO:caffe_translator:Translate layer scale4b12_branch2c
INFO:caffe_translator:Translate layer res4b12
INFO:caffe_translator:Translate layer res4b12_relu
INFO:caffe_translator:Translate layer res4b13_branch2a
INFO:caffe_translator:Translate layer bn4b13_branch2a
INFO:caffe_translator:Translate layer scale4b13_branch2a
INFO:caffe_translator:Translate layer res4b13_branch2a_relu
INFO:caffe_translator:Translate layer res4b13_branch2b
INFO:caffe_translator:Translate layer bn4b13_branch2b
INFO:caffe_translator:Translate layer scale4b13_branch2b
INFO:caffe_translator:Translate layer res4b13_branch2b_relu
INFO:caffe_translator:Translate layer res4b13_branch2c
INFO:caffe_translator:Translate layer bn4b13_branch2c
INFO:caffe_translator:Translate layer scale4b13_branch2c
INFO:caffe_translator:Translate layer res4b13
INFO:caffe_translator:Translate layer res4b13_relu
INFO:caffe_translator:Translate layer res4b14_branch2a
INFO:caffe_translator:Translate layer bn4b14_branch2a
INFO:caffe_translator:Translate layer scale4b14_branch2a
INFO:caffe_translator:Translate layer res4b14_branch2a_relu
INFO:caffe_translator:Translate layer res4b14_branch2b
INFO:caffe_translator:Translate layer bn4b14_branch2b
INFO:caffe_translator:Translate layer scale4b14_branch2b
INFO:caffe_translator:Translate layer res4b14_branch2b_relu
INFO:caffe_translator:Translate layer res4b14_branch2c
INFO:caffe_translator:Translate layer bn4b14_branch2c
INFO:caffe_translator:Translate layer scale4b14_branch2c
INFO:caffe_translator:Translate layer res4b14
INFO:caffe_translator:Translate layer res4b14_relu
INFO:caffe_translator:Translate layer res4b15_branch2a
INFO:caffe_translator:Translate layer bn4b15_branch2a
INFO:caffe_translator:Translate layer scale4b15_branch2a
INFO:caffe_translator:Translate layer res4b15_branch2a_relu
INFO:caffe_translator:Translate layer res4b15_branch2b
INFO:caffe_translator:Translate layer bn4b15_branch2b
INFO:caffe_translator:Translate layer scale4b15_branch2b
INFO:caffe_translator:Translate layer res4b15_branch2b_relu
INFO:caffe_translator:Translate layer res4b15_branch2c
INFO:caffe_translator:Translate layer bn4b15_branch2c
INFO:caffe_translator:Translate layer scale4b15_branch2c
INFO:caffe_translator:Translate layer res4b15
INFO:caffe_translator:Translate layer res4b15_relu
INFO:caffe_translator:Translate layer res4b16_branch2a
INFO:caffe_translator:Translate layer bn4b16_branch2a
INFO:caffe_translator:Translate layer scale4b16_branch2a
INFO:caffe_translator:Translate layer res4b16_branch2a_relu
INFO:caffe_translator:Translate layer res4b16_branch2b
INFO:caffe_translator:Translate layer bn4b16_branch2b
INFO:caffe_translator:Translate layer scale4b16_branch2b
INFO:caffe_translator:Translate layer res4b16_branch2b_relu
INFO:caffe_translator:Translate layer res4b16_branch2c
INFO:caffe_translator:Translate layer bn4b16_branch2c
INFO:caffe_translator:Translate layer scale4b16_branch2c
INFO:caffe_translator:Translate layer res4b16
INFO:caffe_translator:Translate layer res4b16_relu
INFO:caffe_translator:Translate layer res4b17_branch2a
INFO:caffe_translator:Translate layer bn4b17_branch2a
INFO:caffe_translator:Translate layer scale4b17_branch2a
INFO:caffe_translator:Translate layer res4b17_branch2a_relu
INFO:caffe_translator:Translate layer res4b17_branch2b
INFO:caffe_translator:Translate layer bn4b17_branch2b
INFO:caffe_translator:Translate layer scale4b17_branch2b
INFO:caffe_translator:Translate layer res4b17_branch2b_relu
INFO:caffe_translator:Translate layer res4b17_branch2c
INFO:caffe_translator:Translate layer bn4b17_branch2c
INFO:caffe_translator:Translate layer scale4b17_branch2c
INFO:caffe_translator:Translate layer res4b17
INFO:caffe_translator:Translate layer res4b17_relu
INFO:caffe_translator:Translate layer res4b18_branch2a
INFO:caffe_translator:Translate layer bn4b18_branch2a
INFO:caffe_translator:Translate layer scale4b18_branch2a
INFO:caffe_translator:Translate layer res4b18_branch2a_relu
INFO:caffe_translator:Translate layer res4b18_branch2b
INFO:caffe_translator:Translate layer bn4b18_branch2b
INFO:caffe_translator:Translate layer scale4b18_branch2b
INFO:caffe_translator:Translate layer res4b18_branch2b_relu
INFO:caffe_translator:Translate layer res4b18_branch2c
INFO:caffe_translator:Translate layer bn4b18_branch2c
INFO:caffe_translator:Translate layer scale4b18_branch2c
INFO:caffe_translator:Translate layer res4b18
INFO:caffe_translator:Translate layer res4b18_relu
INFO:caffe_translator:Translate layer res4b19_branch2a
INFO:caffe_translator:Translate layer bn4b19_branch2a
INFO:caffe_translator:Translate layer scale4b19_branch2a
INFO:caffe_translator:Translate layer res4b19_branch2a_relu
INFO:caffe_translator:Translate layer res4b19_branch2b
INFO:caffe_translator:Translate layer bn4b19_branch2b
INFO:caffe_translator:Translate layer scale4b19_branch2b
INFO:caffe_translator:Translate layer res4b19_branch2b_relu
INFO:caffe_translator:Translate layer res4b19_branch2c
INFO:caffe_translator:Translate layer bn4b19_branch2c
INFO:caffe_translator:Translate layer scale4b19_branch2c
INFO:caffe_translator:Translate layer res4b19
INFO:caffe_translator:Translate layer res4b19_relu
INFO:caffe_translator:Translate layer res4b20_branch2a
INFO:caffe_translator:Translate layer bn4b20_branch2a
INFO:caffe_translator:Translate layer scale4b20_branch2a
INFO:caffe_translator:Translate layer res4b20_branch2a_relu
INFO:caffe_translator:Translate layer res4b20_branch2b
INFO:caffe_translator:Translate layer bn4b20_branch2b
INFO:caffe_translator:Translate layer scale4b20_branch2b
INFO:caffe_translator:Translate layer res4b20_branch2b_relu
INFO:caffe_translator:Translate layer res4b20_branch2c
INFO:caffe_translator:Translate layer bn4b20_branch2c
INFO:caffe_translator:Translate layer scale4b20_branch2c
INFO:caffe_translator:Translate layer res4b20
INFO:caffe_translator:Translate layer res4b20_relu
INFO:caffe_translator:Translate layer res4b21_branch2a
INFO:caffe_translator:Translate layer bn4b21_branch2a
INFO:caffe_translator:Translate layer scale4b21_branch2a
INFO:caffe_translator:Translate layer res4b21_branch2a_relu
INFO:caffe_translator:Translate layer res4b21_branch2b
INFO:caffe_translator:Translate layer bn4b21_branch2b
INFO:caffe_translator:Translate layer scale4b21_branch2b
INFO:caffe_translator:Translate layer res4b21_branch2b_relu
INFO:caffe_translator:Translate layer res4b21_branch2c
INFO:caffe_translator:Translate layer bn4b21_branch2c
INFO:caffe_translator:Translate layer scale4b21_branch2c
INFO:caffe_translator:Translate layer res4b21
INFO:caffe_translator:Translate layer res4b21_relu
INFO:caffe_translator:Translate layer res4b22_branch2a
INFO:caffe_translator:Translate layer bn4b22_branch2a
INFO:caffe_translator:Translate layer scale4b22_branch2a
INFO:caffe_translator:Translate layer res4b22_branch2a_relu
INFO:caffe_translator:Translate layer res4b22_branch2b
INFO:caffe_translator:Translate layer bn4b22_branch2b
INFO:caffe_translator:Translate layer scale4b22_branch2b
INFO:caffe_translator:Translate layer res4b22_branch2b_relu
INFO:caffe_translator:Translate layer res4b22_branch2c
INFO:caffe_translator:Translate layer bn4b22_branch2c
INFO:caffe_translator:Translate layer scale4b22_branch2c
INFO:caffe_translator:Translate layer res4b22
INFO:caffe_translator:Translate layer res4b22_relu
INFO:caffe_translator:Translate layer res5a_branch1
INFO:caffe_translator:Translate layer bn5a_branch1
INFO:caffe_translator:Translate layer scale5a_branch1
INFO:caffe_translator:Translate layer res5a_branch2a
INFO:caffe_translator:Translate layer bn5a_branch2a
INFO:caffe_translator:Translate layer scale5a_branch2a
INFO:caffe_translator:Translate layer res5a_branch2a_relu
INFO:caffe_translator:Translate layer res5a_branch2b
INFO:caffe_translator:Translate layer bn5a_branch2b
INFO:caffe_translator:Translate layer scale5a_branch2b
INFO:caffe_translator:Translate layer res5a_branch2b_relu
INFO:caffe_translator:Translate layer res5a_branch2c
INFO:caffe_translator:Translate layer bn5a_branch2c
INFO:caffe_translator:Translate layer scale5a_branch2c
INFO:caffe_translator:Translate layer res5a
INFO:caffe_translator:Translate layer res5a_relu
INFO:caffe_translator:Translate layer res5b_branch2a
INFO:caffe_translator:Translate layer bn5b_branch2a
INFO:caffe_translator:Translate layer scale5b_branch2a
INFO:caffe_translator:Translate layer res5b_branch2a_relu
INFO:caffe_translator:Translate layer res5b_branch2b
INFO:caffe_translator:Translate layer bn5b_branch2b
INFO:caffe_translator:Translate layer scale5b_branch2b
INFO:caffe_translator:Translate layer res5b_branch2b_relu
INFO:caffe_translator:Translate layer res5b_branch2c
INFO:caffe_translator:Translate layer bn5b_branch2c
INFO:caffe_translator:Translate layer scale5b_branch2c
INFO:caffe_translator:Translate layer res5b
INFO:caffe_translator:Translate layer res5b_relu
INFO:caffe_translator:Translate layer res5c_branch2a
INFO:caffe_translator:Translate layer bn5c_branch2a
INFO:caffe_translator:Translate layer scale5c_branch2a
INFO:caffe_translator:Translate layer res5c_branch2a_relu
INFO:caffe_translator:Translate layer res5c_branch2b
INFO:caffe_translator:Translate layer bn5c_branch2b
INFO:caffe_translator:Translate layer scale5c_branch2b
INFO:caffe_translator:Translate layer res5c_branch2b_relu
INFO:caffe_translator:Translate layer res5c_branch2c
INFO:caffe_translator:Translate layer bn5c_branch2c
INFO:caffe_translator:Translate layer scale5c_branch2c
INFO:caffe_translator:Translate layer res5c
INFO:caffe_translator:Translate layer res5c_relu
INFO:caffe_translator:Translate layer res5c_up_pose_pose
INFO:caffe_translator:Translate layer res3d_pose_pose
INFO:caffe_translator:Translate layer crop1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/caffe2/python/caffe_translator.py", line 713, in <module>
    caffenet, caffenet_pretrained, is_test=True
  File "/usr/local/caffe2/python/caffe_translator.py", line 129, in TranslateModel
    return TranslatorRegistry.TranslateModel(*args, **kwargs)
  File "/usr/local/caffe2/python/caffe_translator.py", line 122, in TranslateModel
    layer, pretrained_blobs, is_test)
  File "/usr/local/caffe2/python/caffe_translator.py", line 70, in TranslateLayer
    str(layer))
KeyError: 'No translator registered for layer: name: "crop1"\ntype: "Crop"\nbottom: "res5c_up_pose_pose"\nbottom: "res3d_pose_pose"\ntop: "res5c_up_posec"\n yet.'
```
I've uploaded the affected pretrained model to: [Dropbox](https://www.dropbox.com/s/u0o6yfqtufz2he5/model.zip)

Thanks in advance for any kind of help!

**Comment by soumith** [comment]
caffe2 does not have official public support anymore. So, closing this issue as `wontfix`
