### ISSUE TITLE
RuntimeError: _th_normal_ not supported on CPUType/CUDAType for Int

### ISSUE THREAD

**Issue by g-karthik** [pytorch/pytorch#27953]
## 🐛 Bug
```
RuntimeError: _th_normal_ not supported on CPUType for Int

RuntimeError: _th_normal_ not supported on CUDAType for Int
```

## To Reproduce

In a Deep Learning AMI EC2 instance, do `source activate pytorch_p36` first, followed by:

```
>>> import torch
>>> a = torch.randn((4,5), dtype=torch.int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: _th_normal_ not supported on CPUType for Int
>>> a = torch.randn((4,5), dtype=torch.int, device="cuda")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: _th_normal_ not supported on CUDAType for Int
```

## Expected behavior

No errors.

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Amazon Linux AMI 2018.03
 - How you installed PyTorch (`conda`, `pip`, source): conda (I think? This is the standard pytorch_p36 environment in the Deep Learning AMI)
 - Build command you used (if compiling from source): Don't know
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0.130
 - GPU models and configuration:

GPU 0: Tesla V100-SXM2-32GB

GPU 1: Tesla V100-SXM2-32GB

GPU 2: Tesla V100-SXM2-32GB

GPU 3: Tesla V100-SXM2-32GB

GPU 4: Tesla V100-SXM2-32GB

GPU 5: Tesla V100-SXM2-32GB

GPU 6: Tesla V100-SXM2-32GB

GPU 7: Tesla V100-SXM2-32GB

 - Any other relevant information: N/A

**Comment by g-karthik** [comment]
Actually never mind, I guess I cannot use `dtype=torch.int` with `randn()` and should instead just use the `randint()` method.
