### ISSUE TITLE
[quantization] Dynamic LSTM doesn't serialize properly when traced

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#27954]
Repro

```python
import torch
import copy
import io
from torch.quantization import default_qconfig, quantize_dynamic

class LSTMDynamicModel(torch.nn.Module):
    def __init__(self):
        super(LSTMDynamicModel, self).__init__()
        self.qconfig = default_qconfig
        self.lstm = torch.nn.LSTM(2, 2).to(dtype=torch.float)

    def forward(self, x):
        x = self.lstm(x)
        return x

d_in, d_hid = 2, 2
model = LSTMDynamicModel().eval()
cell = model.lstm

# Replace parameter values s.t. the range of values is exactly
# 255, thus we will have 0 quantization error in the quantized
# GEMM call. This i s for testing purposes.
#
# Note that the current implementation does not support
# accumulation values outside of the range representable by a
# 16 bit integer, instead resulting in a saturated value. We
# must take care that in our test we do not end up with a dot
# product that overflows the int16 range, e.g.
# (255*127+255*127) = 64770. So, we hardcode the test values
# here and ensure a mix of signedness.
vals = [[100, -155],
        [100, -155],
        [-155, 100],
        [-155, 100],
        [100, -155],
        [-155, 100],
        [-155, 100],
        [100, -155]]
if isinstance(cell, torch.nn.LSTM):
    num_chunks = 4
vals = vals[:d_hid * num_chunks]
cell.weight_ih_l0 = torch.nn.Parameter(
    torch.tensor(vals, dtype=torch.float),
    requires_grad=False)
cell.weight_hh_l0 = torch.nn.Parameter(
    torch.tensor(vals, dtype=torch.float),
    requires_grad=False)

ref = copy.deepcopy(cell)

model_int8 = quantize_dynamic(model=model, dtype=torch.qint8)
model_fp16 = quantize_dynamic(model=model, dtype=torch.float16)

# Smoke test extra reprs
cell_int8 = model_int8.lstm
cell_fp16 = model_fp16.lstm

assert type(cell_int8) == torch.nn.quantized.dynamic.LSTM, \
    'torch.nn.LSTM should be converted to torch.nn.quantized.dynamic.LSTM after quantize_dynamic'
assert type(cell_fp16) == torch.nn.quantized.dynamic.LSTM, \
    'torch.nn.LSTM should be converted to torch.nn.quantized.dynamic.LSTM after quantize_dynamic'

niter = 10
x = torch.tensor([[100, -155],
                  [-155, 100],
                  [100, -155]], dtype=torch.float).unsqueeze(0).repeat(niter, 1, 1)

h0_vals = [[-155, 100],
           [-155, 155],
           [100, -155]]

hx = torch.tensor(h0_vals, dtype=torch.float).unsqueeze(0)
cx = torch.tensor(h0_vals, dtype=torch.float).unsqueeze(0)

if isinstance(ref, torch.nn.LSTM):
    hiddens = (hx, cx)

ref_out, ref_hid = ref(x, hiddens)

# Compare int8 quantized to unquantized
output_int8, final_hiddens_int8 = cell_int8(x, hiddens)

torch.testing.assert_allclose(output_int8, ref_out)

for out_val, ref_val in zip(final_hiddens_int8, ref_hid):
    torch.testing.assert_allclose(out_val, ref_val)

class ScriptWrapper(torch.nn.Module):
    def __init__(self, cell):
        super(ScriptWrapper, self).__init__()
        self.cell = cell

    def forward(self, x, hiddens):
        # type: (torch.Tensor, Tuple[torch.Tensor, torch.Tensor]) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]
        return self.cell(x, hiddens)

# TODO: TorchScript overloads don't work without this wrapper
cell_script = torch.jit.trace(ScriptWrapper(cell_int8), (x, (hx, cx)))
# cell_script = torch.jit.script(ScriptWrapper(cell_int8))
out_script, hid_script = cell_script(x, hiddens)
for out_val, ref_val in zip(out_script, ref_out):
    torch.testing.assert_allclose(out_val, ref_val)

# Test save/load
b = io.BytesIO()
# torch.jit.save(cell_script, b)
torch.jit.save(cell_script, 'foo.zip')

loaded = torch.jit.load('foo.zip')
loaded(x, (hx, cx))
```

Output

```
../aten/src/ATen/native/QuantizedLinear.cpp:328: UserWarning: FOUND weight out of range 
../aten/src/ATen/native/QuantizedLinear.cpp:328: UserWarning: FOUND weight out of range 
Traceback (most recent call last):
  File "export_test.py", line 110, in <module>
    loaded(x, (hx, cx))
  File "/data/users/jamesreed/pytorch/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: Expected temporary cpp type wrapper of type PackedLinearWeight
The above operation failed in interpreter, with the following stack trace:
at code/__torch__/torch/nn/modules/module.py:11:17
    argument_2: Tuple[Tensor, Tensor]) -> Tuple[Tensor, Tuple[Tensor, Tensor]]:
    hx, hx0, = argument_2
    _0, _1, _2 = torch.quantized_lstm(input, [hx, hx0], [CONSTANTS.c0, CONSTANTS.c1], True, 1, 0., True, False, False, dtype=12, use_dynamic=True)
                 ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0, (_1, _2))
Compiled from code /data/users/jamesreed/pytorch/torch/nn/quantized/dynamic/modules/rnn.py(332): forward_impl
/data/users/jamesreed/pytorch/torch/nn/quantized/dynamic/modules/rnn.py(347): forward_tensor
/data/users/jamesreed/pytorch/torch/nn/quantized/dynamic/modules/rnn.py(386): forward
/data/users/jamesreed/pytorch/torch/nn/modules/module.py(525): _slow_forward
/data/users/jamesreed/pytorch/torch/nn/modules/module.py(539): __call__
export_test.py(95): forward
/data/users/jamesreed/pytorch/torch/nn/modules/module.py(525): _slow_forward
/data/users/jamesreed/pytorch/torch/nn/modules/module.py(539): __call__
/data/users/jamesreed/pytorch/torch/jit/__init__.py(1013): trace_module
/data/users/jamesreed/pytorch/torch/jit/__init__.py(874): trace
export_test.py(98): <module>

```

cc @suo @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by jamesr66a** [comment]
cc @suo

**Comment by jamesr66a** [comment]
As a workaround, users can apply this post-processing to their model after calling `quantize_dynamic`:

```
            def visit_and_script(mod):
                if isinstance(mod, torch.nn.quantized.dynamic.modules.LSTM):
                    return torch.jit.script(mod)
                for k, v in mod.named_children():
                    setattr(mod, k, visit_and_script(v))
                return mod

            model = visit_and_script(model)
```

**Comment by jamesr66a** [comment]
This is an intersection of multiple issues:

* Overload mechanism doesn't work for tracing
* Tracing doesn't capture attribute lookups for list attributes

**Comment by Yeongtae** [comment]
Is it work now? 
I am also facing this problem.

**Comment by jerryzh168** [comment]
> @jamesr66a
> Is it work now?
> I am also facing this problem in PyTorch 1.3.0.
> 
> Which PyTorch version do I use to solve this problem?

Looks like this is fixed after 1.3.0 is released, I think you should be able to find it in nightly version, or try 1.3.1(not sure if this is fixed there) or wait for 1.4.0 I think

**Comment by Yeongtae** [comment]
It's only occurred when we use 8bit quantization on LSTM with jit.trace.
It's fine 8-bit quantization on LSTM with jit.script.

**Comment by Yeongtae** [comment]
> @jamesr66a
> Is it work now?
> I am also facing this problem in PyTorch 1.3.0.
> 
> Which PyTorch version do I use to solve this problem?

It's only occurred when we use the 8-bit quantization on LSTM with jit.trace.
It's fine the 8-bit quantization on LSTM with jit.script.

So, my solution to this problem is to use the 8-bit quantization with jit.script.
