### ISSUE TITLE
no module named reduction

### ISSUE THREAD

**Issue by visonpon** [pytorch/pytorch#2797]
**import torch**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 336, in <module>
    import torch.cuda
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 16, in <module>
    from multiprocessing.util import register_after_fork as _register_after_fork
  File "/home/*/pytorch-master/torch/multiprocessing/__init__.py", line 17, in <module>
    from .reductions import init_reductions
  File "/home/*/pytorch-master/torch/multiprocessing/reductions.py", line 5, in <module>
    from multiprocessing.reduction import ForkingPickler
ImportError: No module named reduction
```

**Comment by soumith** [comment]
what is `python --version`? that has to be there in the default multiprocessing package usually.

https://github.com/python/cpython/blob/2.7/Lib/multiprocessing/reduction.py

**Comment by soumith** [comment]
closing because it's pretty much not pytorch related. likely a broken python install.

**Comment by cpbotha** [comment]
Just in case anyone else stumbles into this issue like I just did:

You will see this issue if your current working directory is `site-packages/torch`, in which case any `import multiprocessing` will import torch's own conveniently named `multiprocessing` package, and not the default one.

(I saw this, because I was diagnosing LD_LIBRARY_PATH issues with my wheel build of PyTorch 1.0 preview + CUDA 10.)
