### ISSUE TITLE
How to quantize resnet in pytorch 1.3?

### ISSUE THREAD

**Issue by Arctanxy** [pytorch/pytorch#28202]
I tried to quantize resnet18 refer to https://pytorch.org/tutorials/advanced/dynamic_quantization_tutorial.html

but I got this error
```
>>> from torchvision.models import resnet18
>>> net= resnet18()
>>> from torch.quantization import quantize_dynamic
>>> qnet = quantize_dynamic(net,{nn.Conv2d,nn.Linear},dtype=torch.qint8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\quantization\quantize.py", line 241, in quantize_dynamic
    convert(model, mapping, inplace=True)
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\quantization\quantize.py", line 294, in convert
    reassign[name] = swap_module(mod, mapping)
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\quantization\quantize.py", line 316, in swap_module
    new_mod = mapping[type(mod)].from_float(mod)
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\nn\quantized\dynamic\modules\linear.py", line 70, in from_float
    qlinear = Linear(mod.in_features, mod.out_features)
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\nn\quantized\dynamic\modules\linear.py", line 33, in __init__
    super(Linear, self).__init__(in_features, out_features, bias_)
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\nn\quantized\modules\linear.py", line 119, in __init__
    self.set_weight_bias(qweight, bias)
  File "E:\Program Files\Anaconda3\envs\torch\lib\site-packages\torch\nn\quantized\modules\linear.py", line 208, in set_weight_bias
    self._packed_params = torch.ops.quantized.linear_prepack(w, b)
RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine (operator () at ..\aten\src\ATen\native\quantized\cpu\qlinear_prepack.cpp:202)
(no backtrace available)
```

How can I solve it?

my environment:

torch1.3.0+cpu 
windows 7
python3.6.6

**Comment by Naresh1318** [comment]
From what I’ve seen. Dynamic quantization using the above mentioned function call does not support Conv2d.

**Comment by Arctanxy** [comment]
> From what I’ve seen. Dynamic quantization using the above mentioned function call does not support Conv2d.

Thank you.

**Comment by soumith** [comment]
next time, please ask questions on https://discuss.pytorch.org

**Comment by zhanyike** [comment]
I met the same error,have you solved this problem?thanks

**Comment by asmitakhaneja** [comment]
> I met the same error,have you solved this problem?thanks

A workaround to solve this issue is :
`torch.backends.quantized.engine = 'qnnpack'```
