### ISSUE TITLE
[jit][script] torch.jit.script does not support nn.ModuleDict

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#28339]
## 🐛 Bug

`torch.jit.script` does not seem to support code that uses an `nn.ModuleDict`.

## To Reproduce

If we try to run this code, using the example module from the `nn.ModuleDict` docstring:

```python
import torch
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.choices = nn.ModuleDict(
            {"conv": nn.Conv2d(10, 10, 3), "pool": nn.MaxPool2d(3)}
        )
        self.activations = nn.ModuleDict(
            [["lrelu", nn.LeakyReLU()], ["prelu", nn.PReLU()]]
        )

    def forward(self, x, choice, act):
        x = self.choices[choice](x)
        x = self.activations[act](x)
        return x

torch.jit.script(MyModule())
```

we get the following stack trace:

```python
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    torch.jit.script(MyModule())
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 
'module' object is not subscriptable:
at a.py:15:12
    def forward(self, x, choice, act):
        x = self.choices[choice](x)
            ~~~~~~~~~~~~~~~~~~~ <--- HERE
        x = self.activations[act](x)
        return x
```
## Environment

```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: version 3.14.5

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] numpy-quaternion==2019.7.23.15.26.49
[pip] torch==1.3.0
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0               py3.6_cpu_0  [cpuonly]  pytorch
```

cc @suo

**Comment by eellison** [comment]
Hi, thanks for the report & succinct repro! 

This issue is related to https://www.google.com/search?q=index+into+modulelist . Because Modules aren't fully first class in the type system we don't have a way of representing the type you get out of `moduledict[key]`. We are aware of this limitation and would like to fix it but it will likely be at least a few releases.

As with ModuleLists, Moduledicts are only supported to iterate over.

Depending on the size of your moduledict, the following (not great) workaround might be acceptable. 

```
class MyModule(nn.Module):
    __constants__ = ['choices', 'activations']

    def __init__(self):
        super(MyModule, self).__init__()
        self.choices = nn.ModuleDict(
            {"conv": nn.Conv2d(10, 10, 3), "pool": nn.MaxPool2d(3)}
        )
        self.activations = nn.ModuleDict(
            [["lrelu", nn.LeakyReLU()], ["prelu", nn.PReLU()]]
        )

    def forward(self, x, choice, act):
        x = self.call_choice(x, choice)
        x = self.call_activation[act](x)
        return x

    def call_choice(self, x, choice: str):
      for key, module in self.choices.items():
        if key == choice:
          return module(x)
      throw Exception("Key not Found: {}".format(choice))

    def call_activation(self, x, act: str):
      for key, module in self.activations.items():
        if key == act:
          return module(x)
      throw Exception("Key not Found: {}".format(act))
```

**Comment by suo** [comment]
Going to close this as https://github.com/pytorch/pytorch/issues/16123 is already tracking. Thanks for the report!
