### ISSUE TITLE
error executing torch_shm_manager in cifar10_tutorial.py

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#28345]
## To Reproduce

```
pip3 install torch
pip3 install torchvision
git clone https://github.com/pytorch/tutorials.git
cd tutorials/beginner_source/blitz
python3 cifar10_tutorial.py
```

```
Traceback (most recent call last):
  File "cifar10_tutorial.py", line 104, in <module>
    images, labels = dataiter.next()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/usr/local/lib/python3.7/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/usr/local/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
```

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15
GCC version: Could not collect
CMake version: version 3.15.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] pytorch-transformers==1.0.0
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1
[conda] Could not collect

cc @SsnL

**Comment by kgodara** [comment]
Experienced the same issue on OSX. Setting `num_workers=0` on the DataLoaders solved it, even though the tutorial only recommends it for Windows.

**Comment by pietern** [comment]
@lutzroeder Do you happen to get more output during the crash, as to why it failed to start?

**Comment by lutzroeder** [comment]
@pietern There is no other output. No error with the workaround @kgodara suggested. Repros reliably on macOS Catalina.

**Comment by fedor-chervinskii** [comment]
Same here, different example, but also fails the first iteration of Dataloader, with exactly the same output, OSX 10.14.5. `num_workers=0` solves the problem

**Comment by pietern** [comment]
Can you confirm that `/usr/local/lib/python3.7/site-packages/torch/bin/torch_shm_manager` exists?

I ran the same commands, in a fresh conda environment with PyTorch 1.3, on macOS 10.14, and the process happily starts training and I never get to see this crash.

**Comment by soumith** [comment]
this was fixed with the release of `1.3.0.post2` binaries for OSX. Please do `pip install -U torch` to fix it.

**Comment by cslxiao** [comment]
It still happens even with PyTorch 1.4!

**Comment by GayatriPurandharT** [comment]
This happens with PyTorch 1.4.0 in the ubuntu18.04 environment too!

**Comment by silvercondor** [comment]
Any help to resolve this? installed torch 1.4.0 but bin folder is missing
