### ISSUE TITLE
"module has no attribute 'downsample'" when scripting torchvision's resnet

### ISSUE THREAD

**Issue by hans1929** [pytorch/pytorch#28351]
The "torch.jit.script()" doesn't work for resnet from torch vision. 
When I run:
`model = torchvision.models.resnet18()`
`sm = torch.jit.script(model)`

I have:

> Traceback (most recent call last):
  File "convert_model_to_cpp.py", line 63, in <module>
    sm = torch.jit.script(model)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 195, in make_strong_submodule
    new_strong_submodule = recursive_script(module)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 116, in recursive_script
    return create_constant_iterable_module(mod)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 233, in create_constant_iterable_module
    modules[key] = recursive_script(submodule)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError:
module has no attribute 'downsample':
at /home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torchvision/models/resnet.py:66:11
        identity = x
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)
        out = self.conv2(out)
        out = self.bn2(out)
        if self.downsample is not None:
           ~~~~~~~~~~~~~~~ <--- HERE
            identity = self.downsample(x)
        out += identity
        out = self.relu(out)
        return out
'__torch__.torchvision.models.resnet.BasicBlock.forward' is being compiled since it was called from '__torch__.torchvision.models.resnet.ResNet.forward'
at /home/hans/Documents/vehicle_verification/env_pytorch/lib/python3.6/site-packages/torchvision/models/resnet.py:201:8
    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.layer1(x)
        ~~~~~~~~~~~~~~~~~ <--- HERE
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        return x

I understand tracing could do the job but still wondering if anyone can help with this.


cc @suo

**Comment by suo** [comment]
Thanks for the report! cc'ing @eellison who has been working on Torchvision script compat—is this a known issue?

**Comment by fmassa** [comment]
I believe you need to use a nightly version of torchvision (and thus a nightly version of PyTorch) for resnet to be scriptable.

**Comment by eellison** [comment]
Yes this was fixed in https://github.com/pytorch/vision/pull/1343 

As @fmassa said, you need to be on torchvision nightly
