### ISSUE TITLE
setup.py: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#28365]
```
Traceback (most recent call last):
  File "setup.py", line 761, in <module>
    extensions, cmdclass, packages, entry_points = configure_extension_build()
  File "setup.py", line 639, in configure_extension_build
    cuda_lib_path = os.path.join(CUDA_HOME, lib_dir)
  File "/home/ezyang/Dev/pytorch-tmp-env/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
````

was just doing a normal build

**Comment by ezyang** [comment]
cc @xuhdev it looks like this happens if I have a cmake cache with `USE_CUDA` on, but somehow CUDA detection from setup.py no longer picks up cuda (so `CUDA_HOME` is None)

**Comment by xuhdev** [comment]
Could you test #28373?
