### ISSUE TITLE
distribute process error

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#28403]
My data save in NFS, so I want to copy it to SSD in my computer.
I writer a function in my DatasetClass, and start it by Process, the code such as:
```python
  __init__(self):
    ...
    if self.replace_data_path is not None:
      self.replace_data_path = os.path.abspath(self.replace_data_path)
      self.copy_finish = multiprocessing.Value(ctypes.c_bool, False)
      self.p = Process(target=self.copy_data, args=[self.copy_finish])
      self.p.start()

  def copy_data(self, stop_file):
    copy_start_time = time.time()
    if os.path.exists(self.replace_data_path):
      shutil.rmtree(self.replace_data_path)

    shutil.copytree(self.data_path, self.replace_data_path)
    with open(stop_file, "w") as f:
      f.write("replace_path={}".format(self.replace_data_path))

```
But when I use multiprocessing `mp.spawn`, the program report error:
```
Traceback (most recent call last):
  File "/home/zgz/jinn_code/boundary_project/voc_code/voc_train.py", line 193, in <module>
    process.run()
  File "/home/zgz/jinn_code/Jinn/dh_aiflow/dh_aiflow_process/dh_aiflow_process.py", line 217, in run
    nprocs=self.dist_config.ngpus_per_node)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 162, in spawn
    process.start()
  File "/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
2019-10-22 11:01:59,261 - INFO - copy data process: 24137 delete

```

**Comment by as754770178** [comment]
I create Dataset Object in __name="__main__" filed, so the init function of Dataset only call once.

**Comment by fmassa** [comment]
We use GitHub issues to track bugs and feature requests.
Please redirect questions like this to the forums http://discuss.pytorch.org
