### ISSUE TITLE
torch.jit.script and inheritance

### ISSUE THREAD

**Issue by alsrgv** [pytorch/pytorch#28411]
## 🐛 Bug

While trying to run [DeepLabV3+](https://github.com/pytorch/vision/blob/master/torchvision/models/segmentation/deeplabv3.py) model with TorchScript, I noticed that ASPPPooling operation was failing due to shape mismatch:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in doit
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 1 and 240 in dimension 2 at /pytorch/aten/src/THC/generi
c/THCTensorMath.cu:71
The above operation failed in interpreter, with the following stack trace:
at /root/.cache/torch/hub/pytorch_vision_master/torchvision/models/segmentation/deeplabv3.py:99:14
    def forward(self, x):
        res = []
        for conv in self.convs:
            res.append(conv(x))
        print('main forward()', [r.shape for r in res])
        res = torch.cat(res, dim=1)
              ~~~~~~~~~ <--- HERE
        return self.project(res)
```

After further digging, it turned out that `torch.jit.script` seems to have issue with inheritance and ignores this instruction: https://github.com/pytorch/vision/blob/master/torchvision/models/segmentation/deeplabv3.py#L61

If ASPPPooling is modified to not inherit from Sequential API, everything works as expected.

## To Reproduce

```python
import torch
from torch import nn
from torch.nn import functional as F
from torchvision.models.segmentation.deeplabv3 import ASPPPooling

p = ASPPPooling(1, 1)
p.eval()

t = torch.zeros(1, 1, 3, 3)
print('ok:', p(t).shape)
# ok: torch.Size([1, 1, 3, 3])

pp = torch.jit.script(p)
print('bug:', pp(t).shape)
# bug: torch.Size([1, 1, 1, 1])

class ASPPPoolingV2(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ASPPPoolingV2, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.conv2d = nn.Conv2d(in_channels, out_channels, 1, bias=False)
        self.bn = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU()

    def forward(self, x):
        size = x.shape[-2:]
        x = self.avg_pool(x)
        x = self.conv2d(x)
        x = self.bn(x)
        x = self.relu(x)
        return F.interpolate(x, size=size, mode='bilinear', align_corners=False)

p = ASPPPoolingV2(1, 1)
p.eval()

print('ok:', p(t).shape)
# ok: torch.Size([1, 1, 3, 3])

pp = torch.jit.script(p)
print('ok:', pp(t).shape)
# ok: torch.Size([1, 1, 3, 3])
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @suo

**Comment by alsrgv** [comment]
Nevermind, saw the fix in #27549
