### ISSUE TITLE
[BUG] Can't Deepcopy module with weightnorm

### ISSUE THREAD

**Issue by jramapuram** [pytorch/pytorch#28594]
## 🐛 Bug

A module with `weight_norm` applied cannot be deep copied.

## To Reproduce

Example:

```python
import torch
import torch.nn as nn

from copy import deepcopy

net = nn.Sequential(nn.utils.weight_norm(nn.Linear(2, 3)), nn.Linear(3, 10))
net2 = deepcopy(net) # error out here
````

Result:

```bash
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

## Expected behavior

Proper deepcopy of nn.Module

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15
GCC version: Could not collect
CMake version: version 3.15.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] mkl_fft                   1.0.14           py37h5e564d8_0
[conda] mkl_random                1.1.0            py37ha771720_0
[conda] pytorch                   1.3.0                   py3.7_0    pytorch
[conda] torchvision               0.4.1                  py37_cpu    pytorch

## Additional context

N/A

**Comment by zhangguanheng66** [comment]
you should remove `nn.utils.weight_norm` there. The error message says everything.

**Comment by jramapuram** [comment]
Not really sure this is a solution. I think `weight_norm` should be deep-copyable since deepcopy of a module is a simple and elegant solution to exact copy duplication.

In fact the error message (in a complicated project) does not provide any information that weight_norm is the problem:

```bash
bash Traceback (most recent call last):
  File "main.py", line 626, in <module>
    run(args)
  File "main.py", line 596, in run
    train_loop(data_loaders, model, fid_model, grapher, args)
  File "main.py", line 513, in train_loop
    model.fork()
  File "/Users/jramapuram/Dropbox/projects/LifelongVAE_pytorch/models/student_teacher.py", line 406, in fork
    self.teacher = deepcopy(self.student)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jramapuram/.venv/envs/pytorch1.2-py37/lib/python3.7/site-packages/torch/tensor.py", line 23, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

**Comment by zhangguanheng66** [comment]
So you do need a nn module with exactly same weights?

**Comment by jramapuram** [comment]
Yes, consider a situation of sequential generative replay: one model replays data to a new model at a new task. At this boundary the original model is copied and having to remove weight_norm to deepcopy is potentially error prone. I'm sure there are other use cases as well, but this is what I am currently doing.

**Comment by PetrochukM** [comment]
I am having a similar issue. I need to every so often export the model to a C++ interface and before the export, I need to `deepcopy` to avoid any side effects during the export. It's a pain to remove and recreate the weight norm without messing it up.

**Comment by lunixbochs** [comment]
I just ran into this and did a more involved monkey patch because I didn't want to manually save and restore:

```
# fix weightnorm deepcopy
from torch.nn.utils.weight_norm import WeightNorm
orig_deepcopy = getattr(layer, '__deepcopy__', None)
def __deepcopy__(self, memo):
    # save and delete all weightnorm weights on self
    weights = {}
    for hook in self._forward_pre_hooks.values():
        if isinstance(hook, WeightNorm):
            weights[hook.name] = getattr(self, hook.name)
            delattr(self, hook.name)
    # remove this deepcopy method, restoring the object's original one if necessary
    __deepcopy__ = self.__deepcopy__
    if orig_deepcopy:
        self.__deepcopy__ == orig_deepcopy
    else:
        del self.__deepcopy__
    # actually do the copy
    result = copy.deepcopy(self)
    # restore weights and method on self
    for name, value in weights.items():
        setattr(self, name, value)
    self.__deepcopy__ = __deepcopy__
    return result
# bind __deepcopy__ to the weightnorm'd layer
layer.__deepcopy__ = __deepcopy__.__get__(layer, layer.__class__)
```

**Comment by kaurrachneet6** [comment]
Is this solved yet. I am facing the same error.

**Comment by dlangerm** [comment]
Not to pile on but I just ran into this issue myself with PytorchLightning. It seems that checkpointing is broken if stochastic weight averaging is enabled on the trainer, which is caused by this bug.

**Comment by safelix** [comment]
I also ran into this issue. The problem seems to be inherent to modules with weight norm, since the `module.weight` needs to be computed from `module.weight_g` and `module.weight_v` and thus is not a leave node. 

Since I only deepcopy the module during initialization, I detached `module.weight` from the graph with
```python
self.weight = self.weight_v.detach()

If the module needs to be module should be deepcopied during initialization,

**Comment by safelix** [comment]
I also ran into this issue. The problem seems to be inherent to modules with weight norm, since the `module.weight` needs to be computed from `module.weight_g` and `module.weight_v` and thus is not a leave node.

In my case I only need to deepcopy the module during initialization. As a workaround, I replaced the `module.weight` with a detached copy of `module.weight_v`. Their values will be the same at initialization and the correct computational graph will be recovered before the first call to `forward()` because of the prehook:
```python
module = nn.utils.weight_norm(module)
module.weight = module.weight_v.detach()
```

Alternatively, if one would want to call deepcopy at any time during training, the correct way to detach and reattach the `module.weight` to the graph should be:
```python
module = nn.utils.weight_norm(module)

# potentially update module.weight_v or module.weight_g
module.weight = torch._weight_norm(module.weight_v, module.weight_g, dim).detach()
module_copy = deepcopy(module)
module.weight = torch._weight_norm(module.weight_v, module.weight_g, dim) #reattach
```

**Comment by trinh-hoang-hiep** [comment]
i have same problem, any idea can sovle it?

**Comment by jiqing-feng** [comment]
I found a way to solve this issue, you can first convert the model into eval mode by `model = model.eval()` and then run this model  `model(**input)`. Maybe after running this model the weight norm can be deep copied. You can check if the grad_fn in the weight 
norm tensor is disappearing.
