### ISSUE TITLE
Local docker build fails if you haven't initialized submodules

### ISSUE THREAD

**Issue by cdw** [pytorch/pytorch#2862]
To reproduce:
1. clone clean copy of master
2. run `docker build ./`

What happens:
Local docker build fails on step 12 b/c the build assumes that submodules have been initialized with `git submodule update --init` and then copied over to the container by the prior `COPY . . ` step. 

To fix:
Initialize the submodules before initiating the build, or initialize them in the docker container before continuing the build. 

Actual error code:
```
Step 9/12 : RUN TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .
 ---> Running in 4f4eb6920fa9
Processing /opt/pytorch
  Running setup.py (path:/tmp/pip-qyteks6m-build/setup.py) egg_info for package from file:///opt/pytorch
    Running command python setup.py egg_info
    Could not find /tmp/pip-qyteks6m-build/torch/lib/gloo/CMakeLists.txt
    Did you run 'git submodule update --init'?
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qyteks6m-build/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qyteks6m-build/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 1
```

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/commit/9defb8e653a345f044f7bc35d75751b8666f7bb6

**Comment by soumith** [comment]
thanks for reporting!
