### ISSUE TITLE
Can't successfully install pytorch with python3.6 on my pi 4 

### ISSUE THREAD

**Issue by JoeJoeMango** [pytorch/pytorch#28648]
**my pi info:**
Linux raspberrypi 4.19.50-v7l+ #895 SMP Thu Jun 20 16:03:42 BST 2019 armv7l GNU/Linux

It gets to this point in the installation and I get this err:

```
[ 44%] Built target c10_LeftRight_test
/usr/bin/ld: ../../../lib/libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text+0x24): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [third_party/protobuf/cmake/CMakeFiles/protoc.dir/build.make:87: bin/protoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: third_party/protobuf/cmake/CMakeFiles/protoc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 44%] Built target c10_bfloat16_test
[ 44%] Built target sleefdetpurecfma_scalar
[ 44%] Built target sleefdetpurec_scalar
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 751, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    cmake=cmake)
  File "/home/pi/Desktop/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/pi/Desktop/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/pi/Desktop/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/pi/miniconda3/envs/mimicVoice/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
```
I need it to run on python3.6 
Is this enough info to get some advice?

**Comment by albanD** [comment]
Hi,

Could you give more informations about you environment? gcc version in particular?

**Comment by JoeJoeMango** [comment]
Hey AlbanD,
I am running a conda enviorment, python3.6 and my gcc version is (Raspbian 8.3.0-6+rpi1) 8.3.0

**Comment by albanD** [comment]
Does the fix proposed in https://github.com/pytorch/pytorch/issues/22898 works for you?

**Comment by JoeJoeMango** [comment]
This step is a bit confusing:
Change CMAKE_CXX_FLAGS variable in CMakeLists.txt file (in the main directory). i.e. add line 
There are so many lines that start with this:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -latomic")`

Do you know where specifically I need to replace it

**Comment by albanD** [comment]
They all append to the current value.
So you can put it anywhere it's going to run, [here](https://github.com/pytorch/pytorch/blob/3f119a5f52210f599ad9f5916c83186b8a01856a/CMakeLists.txt#L192) for example

**Comment by JoeJoeMango** [comment]
I did it and it seems to be running great. At 99% at the moment. 
I was gonna give you a thumbs up when I get to 100%

**Comment by JoeJoeMango** [comment]
still says 
`ModuleNotFoundError: No module named 'torch'`

**Comment by albanD** [comment]
Did you use the same python to install and test?
Make sure you don't try to import torch from the pytorch root directory as the folder named `torch` confuses the python import?
Did the installation completed without any errors?

**Comment by JoeJoeMango** [comment]
Hey does this happen to look familiar to you?

`[  9%] Linking CXX static library ../../../lib/libbenchmark.a
[  9%] Built target benchmark
[  9%] Linking CXX static library ../../../lib/libgtest.a
[  9%] Built target gtest
make: *** [Makefile:141: all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-nnpack --use-mkldnn --use-qnnpack caffe2'
`

**Comment by JoeJoeMango** [comment]
I am pretty sure thats what I am doing. Yes it completed with no errors.
When I try to use it I get this:
`Traceback (most recent call last):
  File "demo_cli.py", line 4, in <module>
    from encoder import inference as encoder
  File "/home/pi/Desktop/Real-Time-Voice-Cloning/encoder/inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "/home/pi/Desktop/Real-Time-Voice-Cloning/encoder/model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'
`

**Comment by albanD** [comment]
You have the intructions [here](https://github.com/pytorch/pytorch#from-source).

**Comment by JoeJoeMango** [comment]
I have done this and it built with no errors and it still does not see the module torch

**Comment by albanD** [comment]
You need to make sure that the `python` you use to run the `python setup.py install` is the same as the one you use to check. Otherwise you can try to uninstall torch with `pip uninstall torch` (associated with the same python above).

**Comment by JoeJoeMango** [comment]
I wiped it from my system and started over:
Put that one line in the CMake file
I cant get past this point now:
```

Scanning dependencies of target protoc
[ 46%] Building CXX object third_party/protobuf/cmake/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o
[ 46%] Linking CXX executable ../../../bin/protoc
/usr/bin/ld: ../../../lib/libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text+0x24): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [third_party/protobuf/cmake/CMakeFiles/protoc.dir/build.make:87: bin/protoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: third_party/protobuf/cmake/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 751, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    cmake=cmake)
  File "/home/pi/Downloads/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/pi/Downloads/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/pi/Downloads/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/pi/miniconda3/envs/mimicVoice/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.

```

**Comment by albanD** [comment]
Unfortunately I don't have a pi to test this.
You want to make sure that your code is compiled with the `-latomic` flag. From the informations at the beginning of the setup.py file, you can try `CFLAGS=-latomic python setup.py install` ?

**Comment by notrudyyy** [comment]
@albanD I think this can be closed now?
