### ISSUE TITLE
PyTorch fails in the runtime: ImportError: /usr/local/lib/libtorch.so: Undefined symbol "cpuinfo_isa"

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#28772]
```
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import torch 
  File "/usr/local/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /usr/local/lib/libtorch.so: Undefined symbol "cpuinfo_isa"
```

Version 1.3.0
FreeBSD 12

**Comment by asobhy-qnx** [comment]
I am cross compiling for QNX and I came across this issue @yurivict how did you resolve this?

**Comment by yurivict** [comment]
```PyTorch``` doesn't yet build on FreeBSD.

But I don't remember why I closed it exactly.

Please feel free to reopen if you observe the same symptom.
