### ISSUE TITLE
Getting Build Error

### ISSUE THREAD

**Issue by PyExtreme** [pytorch/pytorch#28795]
I am building PyTorch and I am getting the following error. Would be great to know how to fix it.

Thank you

```
[10/699] Building CXX object caffe2/CMakeFiles/torch.dir/operators/spatial_batch_norm_gradient_op.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 751, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    cmake=cmake)
```

**Comment by zhangguanheng66** [comment]
Please follow the template to open an issue. We need more information.
