### ISSUE TITLE
Build getting terminated

### ISSUE THREAD

**Issue by PyExtreme** [pytorch/pytorch#28833]
## ❓ Questions and Help

I have made some changes in a file and while I am building in develop mode, the build is getting terminated due to errors in some other file. The command which I have executed is here:

`MAX_JOBS=8 DEBUG=1 USE_DISTRIBUTED=0 USE_MKLDNN=0 USE_CUDA=0 BUILD_TEST=1 USE_FBGEMM=0 USE_NNPACK=0 USE_QNNPACK=0 python setup.py develop` 

The error which I am getting is this:

```
/usr/include/c++/7/ext/new_allocator.h:119:19: error: invalid application of ‘__alignof__’ to incomplete type ‘torch::at::Tensor’
  if (alignof(_Tp) > __STDCPP_DEFAULT_NEW_ALIGNMENT__)
/usr/include/c++/7/ext/new_allocator.h:121:34: error: invalid application of ‘__alignof__’ to incomplete type ‘torch::at::Tensor’
      ::operator delete(__p, std::align_val_t(alignof(_Tp)));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
[13/690] Building CXX object caffe2/CMakeFiles/torch.dir/operators/swish_op.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 751, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    cmake=cmake)
  File "/home/ankit_jha/test/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/ankit_jha/test/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/ankit_jha/test/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.
```

Also, I have previously made commits but never faced this issue. What could be possible reasons for this and how should I resolve it?

Moreover, I am running the build command in my separate branch. 

Thank you

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org for questions.

**Comment by ifedan** [comment]
Also please provide the environment you use
