### ISSUE TITLE
Unable to build cuda extension without nvidia runtime with PyTorch 1.3

### ISSUE THREAD

**Issue by vladserkoff** [pytorch/pytorch#28955]
## 🐛 Bug
I'm trying to build a pytorch cuda extension (https://github.com/microsoft/pytorch_od) inside a docker container, for this I'm using official dev image `pytorch/pytorch:1.3-cuda10.1-cudnn7-devel`. But the build fails with an error stating that no nvidia driver has been found, see the traceback at the bottom.
When I try to build it inside a runnig container with `--runtime=nvidia` this builds successfully. This was not an issue with `pytorch/pytorch:1.2-cuda10.0-cudnn7-devel` image.

## To Reproduce

Here's my Dockerfile:
```
FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel
RUN git clone https://github.com/microsoft/pytorch_od /build/mictorch
WORKDIR /build/mictorch
RUN pip wheel --no-deps .
```
<details>
<summary>Python traceback</summary>

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-1xpkr4i_/setup.py", line 89, in <module>
      'Topic :: Software Development',
    File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 353, in build_extensions
      build_ext.build_extensions(self)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/opt/conda/lib/python3.6/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 269, in unix_wrap_compile
      "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 977, in _get_cuda_arch_flags
      capability = torch.cuda.get_device_capability()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 328, in get_device_capability
      prop = get_device_properties(device)
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 334, in get_device_properties
      init()  # will define _get_device_properties and _CudaDeviceProperties
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 164, in init
      _lazy_init()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
      _check_driver()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 102, in _check_driver
      http://www.nvidia.com/Download/index.aspx""")
  AssertionError:
  Found no NVIDIA driver on your system. Please check that you
  have an NVIDIA GPU and installed a driver from
  http://www.nvidia.com/Download/index.aspx
  ----------------------------------------
  ERROR: Failed building wheel for mictorch
  Running setup.py clean for mictorch
Failed to build mictorch
```
</details>

## Expected behavior

The extension builds successfully without nvidia runtime.

## Additional content
I've mentioned this in the extension repo, the maintainer thinks that the issue is not with the extension https://github.com/microsoft/pytorch_od/issues/11

cc @ezyang

**Comment by qzhong0605** [comment]
You may set the default runtime of `dockerd` to `nvidia`  if you want to build with `cuda`. You can follow [this way](https://github.com/NVIDIA/nvidia-docker/issues/595)

**Comment by vladserkoff** [comment]
In my opinion it should be possible to build on a machine without a nvidia GPU. I'm building the extension inside a CI, and then use the image on a GPU machine. And it is possible with pytorch 1.2.

**Comment by qzhong0605** [comment]
It's possible with `pytorch 1.2` because you were inside a running container with `--runtime=nvidia`. 

However, you failed when building an image based on `pytorch/pytorch:1.3-cuda10.1-cudnn7-devel` through `Dockerfile` because the `runtime` for a started `container` was not `nvidia`.

**Comment by vladserkoff** [comment]
@qzhong0605, that's not correct. It is possible to build inside `pytorch/pytorch:1.2-cuda10.0-cudnn7-devel` without nvidia runtime.

**Comment by dashesy** [comment]
There should be no need for a cuda runtime to build for cuda. Otherwise it will be impossible to build in a machine that has no GPU, or build a code base for contiguous integration. `_get_cuda_arch_flags` should default to a fixed set of architectures when current machine has no cuda. 
In fact even if the current machine has a particular GPU, we would like to be able to build for a different set of architectures. 
A solution would be to provide an environment variable, if set use it instead of probing the current hardware.

**Comment by qzhong0605** [comment]
@vladserkoff my answer is not correct. It's possible to build with `cuda runtime` just by `nvcc` tool.  

@dashesy You are right.  The problem could be worked around with a fixed set of architectures. 
It could be done by setting an environment `TORCH_CUDA_ARCH_LIST`

**Comment by dashesy** [comment]
Great! `TORCH_CUDA_ARCH_LIST=All` should be fine, but binary size may be large. I wonder what is a good compromise, to avoid really old hardware.

**Comment by qzhong0605** [comment]
A default value for `TORCH_CUDA_ARCH_LIST` on `cpp_extension.py` may be more suitable than the `None` value.

**Comment by fnst-yule** [comment]
It seems causing several similar issues. Maybe a default value of `TORCH_CUDA_ARCH_LIST` is a good choise for improvement .

**Comment by bwesen** [comment]
Hi, I got hit by this right now as well - the C++ extension framework dumps a "ValueError: Unknown CUDA arch (3.0) or GPU not supported" when I try to build the extension on another machine (with an old GPU). I want it to ignore the GPU, I'm just testing to build stuff on it, I'm never going to run it on it. It does have the CUDA 10.2 and nvidia 440 drivers installed.

The linked #27222 issue is closed and points to this issue with the comment that "a solution is here" but what was the solution? :)

**Comment by bwesen** [comment]
Ok, seems the solution is to set TORCH_CUDA_ARCH_LIST to something like Pascal or Turing etc. before building, this will skip the GPU check. Maybe add a print to the build script, that suggests this instead of just throwing the ValueError would be useful.
