### ISSUE TITLE
ConnectionResetError when using dataLoader

### ISSUE THREAD

**Issue by ShuangjunLiu** [pytorch/pytorch#28950]
## 🐛 Bug

ConnectionResetError  when 'pin_memory=True' for dataLoader.  
A simple test case is provided.
( I found the issue in a more complex training code with larger dataset. I made a simple code to pinpoint the problem) 

## To Reproduce
```

from torch.utils.data import Dataset, DataLoader

class Set_ex(Dataset):
	def __init__(self):
		self.lst = [1, 2, 3, 4, 5, 6, 7, 8]

	def __getitem__(self, index):
		return self.lst[index]

	def __len__(self):
		return len(self.lst)

if __name__ == "__main__":
	## ex_call1 loader
	ds_ex = Set_ex()
	dsLoader = DataLoader(ds_ex, 3, True, num_workers=20,  pin_memory=True)
	iterator = iter(dsLoader)
	dtIn =next(iterator)

	print(dtIn)
```
output + error infor: 
> tensor([5, 8, 1])
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 21, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

## Expected behavior

this simple code suppose to finish without error. 

## Additional test 

- If 'pin_memory=False',  no problem 
- If change the batch_size or num_workers, can work sometimes.  batch_size=2,  workers=20 will not work. 
- Test on another Centos OS cluster node, no such problem.  Same pytorch install via conda, same CUDA, same python3.7. 
- Run same code several times, sometimes it worked, sometimes failed. 

pin_memory seems to cause the trouble.  
Problem seems random.  

## Environment
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.12.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu9.0.176_1    pytorch

**Comment by SsnL** [comment]
I believe that this has been fixed in 1.3. Could you update and try again?

**Comment by ShuangjunLiu** [comment]
I follow the official install [guide ](https://pytorch.org/) to install with command: 

> conda install pytorch torchvision cudatoolkit=9.0 -c pytorch -c defaults -c numba/label/dev
As I have CUDA 9.0 on my computer. 

It only brought me to Pytorch1.1 

Could you show me a proper way for 1.3 install?  

Thanks!

**Comment by ShuangjunLiu** [comment]
## problem 
After updating to pytorch 1.3, this issue sticks there.  It randomly happened during repeating test. 

## test case 
Still the demo code provided above.   
In 4 runs, 3 succeeded, one failed.  

## env 
I create a new environment py37 on my system with system infor below. 

> PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.12.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.0           py3.7_cuda9.2.148_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                 py37_cu92    pytorch




> (py37) jun@aclab-H97M-D3H:~/codesPool/dsTool/ex_utils$ python ex_cls_pth.py
tensor([5, 2, 7])
(py37) jun@aclab-H97M-D3H:~/codesPool/dsTool/ex_utils$ python ex_cls_pth.py
tensor([6, 4, 3])
(py37) jun@aclab-H97M-D3H:~/codesPool/dsTool/ex_utils$ python ex_cls_pth.py
tensor([8, 6, 4])
(py37) jun@aclab-H97M-D3H:~/codesPool/dsTool/ex_utils$ python ex_cls_pth.py
tensor([6, 4, 5])
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by SsnL** [comment]
Thanks for the update. Unfortunately I can't reproduce on 18.04 with PyTorch 1.3. Sometimes low amount of available shm can cause problems. Could you check that?

**Comment by ShuangjunLiu** [comment]
The shm seems to be large enough for a loader with only 8 entries which is quoted here. 
It is possible that it is not reproduced on another machine as it also works fine on a cluster node with same pytorch version and centos OS.  

> (py37) jun@aclab-H97M-D3H:~/codesPool/dsTool$ df -h
Filesystem             Size  Used Avail Use% Mounted on
udev                   7.8G     0  7.8G   0% /dev
tmpfs                  1.6G   26M  1.6G   2% /run
/dev/sdc1              440G  142G  277G  34% /
tmpfs                  7.8G  256K  7.8G   1% /dev/shm

**Comment by SsnL** [comment]
I'm pretty out of clue then.... If you find more info, or this turns out to lead to bugs, let us know! Thanks.

**Comment by ShuangjunLiu** [comment]
Would you like to increase the list size like 
`self.lst = list(range(1000000))`

After this, it occurs more frequently one my  machine.

**Comment by ShuangjunLiu** [comment]
Besides ConnectionResetError, sometimes it also shows  EOFERROR cited here.  

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 499, in Client
    deliver_challenge(c, authkey)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 729, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/jun/miniconda3/envs/py37/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by SsnL** [comment]
@ShuangjunLiu I'm running this in a `while True` loop yet still can't reproduce the exception.

**Comment by KaiHoo** [comment]
@SsnL I also get the same error training mask RCNN models with torch 1.4.0, torch vision 0.5.0 (I load all images into memory). The error **always** occurs near the end of third epochs. I have 400G memories and 110G shm. I use watch -n 1 "tail nohup.out && free -h && df -h" to see what happened when error occurs but both the memory and shm are OK. I did not use pin_memory. Any ideas?

"""
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/tiger/conda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detection/train.py", line 116, in <module>
    main(args)
  File "detection/train.py", line 82, in main
    train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=50)
  File "/opt/tiger/path/detection/engine.py", line 27, in train_one_epoch
    for images, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/opt/tiger/path/detection/utils.py", line 209, in log_every
    for obj in iterable:
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 819055) is killed by signal: Killed.
"""

**Comment by KaiHoo** [comment]
@SsnL @ShuangjunLiu I can also repeat the error with torch 1.5.0
```
from torch.utils.data import Dataset, DataLoader

class Set_ex(Dataset):
	def __init__(self):
		self.lst = [1, 2, 3, 4, 5, 6, 7, 8]

	def __getitem__(self, index):
		return self.lst[index]

	def __len__(self):
		return len(self.lst)

if __name__ == "__main__":
	## ex_call1 loader
	ds_ex = Set_ex()
	dsLoader = DataLoader(ds_ex, 3, True, num_workers=20,  pin_memory=True)
	iterator = iter(dsLoader)
	dtIn =next(iterator)

	print(dtIn)
```

**Comment by SeaOfOcean** [comment]
reproduce in 1.6.0+cu101

**Comment by Gateway2745** [comment]
@hukkai Were you able to find a solution to the crash?

**Comment by Gateway2745** [comment]
@hukkai Hi. I am also getting the same error output as you with `pin_memory=False`. Were you able to find the cause/fix? Thanks.

**Comment by leslie-arch** [comment]
> 
So， have you fixed this problem? Is this a bug? I'm using pytorch 1.7.X....
