### ISSUE TITLE
torch.mean(x, dims=[]) has incorrect gradient in 1.2

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#28993]
## 🐛 Bug

```
import torch
torch.__version__
x = torch.ones(3, requires_grad=True)
out = x.mean([])  # gives 1, as expected
out.backward()
x.grad  # gives tensor([1., 1., 1.]) which is incorrect!
```
`torch.mean(x, [])` should be equivalent to `torch.mean(x)` unless I am missing something. Compare the above code to the following code:
```
y = torch.ones(3, requires_grad=True)
out = y.mean()
out.backward()
y.grad  # gives tensor([0.333, 0.333, 0.333]) as expected
```

This is on PyTorch 1.2. One can't actually run this code on PyTorch 1.3 (it says the gradient is not implemented).

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL @albanD @gqchen

**Comment by zou3519** [comment]
For context: the reason why the gradient is not implemented on 1.3 and master is because of https://github.com/pytorch/pytorch/issues/28286 (I am working on the fix). Separately from that problem, and as reported in this issue, the gradient seems to be incorrect.

**Comment by colesbury** [comment]
@gchanan suggests back porting the fix to 1.3.1

cc @soumith

**Comment by zou3519** [comment]
@v0dro I am going to fix this in the next few hours because we might want a backport for this asap, sorry about that.

**Comment by zou3519** [comment]
I checked the history of this issue and I believe it has been around since multidim support for torch.sum was added. In particular, I checked pt 1.1 and pt 1.2, and the bug is present in both.

I think it is fine if we don't backport this for the following two reasons:
1. the bug is present in both 1.1 and 1.2 so it's not a "regression". Running the above code in 1.3 causes an error for "gradient not implemented" to be thrown; which is better than an incorrect gradient imo.
2. a full fix would probably take a while (more than 1 day) and need to extend to all reduction functions (see #29137 )

Let me know your thoughts @gchanan @soumith

**Comment by gchanan** [comment]
ya, let's not fix it in 1.3.1.

**Comment by zou3519** [comment]
Going to unassign me because I am not actively working on this right now

**Comment by kurtamohler** [comment]
I'd like to work on this issue, if no one else is looking at it right now.

**Comment by zou3519** [comment]
@kurtamohler this task is blocked by https://github.com/pytorch/pytorch/issues/29137 (pytorch has incorrect behavior in forward-pass of `torch.mean(x, dims=[])`. We should fix the behavior of the forward pass first before we fix the behavior of the backward pass.

**Comment by kurtamohler** [comment]
@zou3519, oh I see. Thanks for pointing that out.

**Comment by zou3519** [comment]
> @zou3519, oh I see. Thanks for pointing that out.

Feel free to coordinate with @pbelevich on that issue if you're interested in working on it

**Comment by kurtamohler** [comment]
Coming back to this issue after working on #29137. In that issue, it was decided that `tensor.mean(dims=())` should not be the same as `tensor.mean()`, since dims=() means "no reduction". So that means the gradient should be different.

However, after applying my fix for #29137 (PR #30822), I get an error when I try to calculate the gradient of `tensor.mean(dims=())`:

```
>>> import torch
>>> x = torch.ones(3, requires_grad=True)
>>> out = x.mean([])
>>> out
tensor([1., 1., 1.], grad_fn=<MeanBackward1>)
>>> out.backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kurtamohler/development/pytorch/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/kurtamohler/development/pytorch/torch/autograd/__init__.py", line 93, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "/home/kurtamohler/development/pytorch/torch/autograd/__init__.py", line 34, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```

I'm not sure why there's an error, but I think the correct behavior should be that `x.grad` comes out to `[0, 0, 0]`, since there was no change between `x` and `out`. Am I correct about that?

**Comment by albanD** [comment]
This errors happens because `out` contains more than one element. If you want to backward such Tensor, you need to provide the initial gradients. `torch.ones_like(out)` for example or equivalently `out.sum().backward()`.
Also if you want to check that the gradients you implemented are correct, you can use [`autograd.gradcheck`](https://pytorch.org/docs/stable/autograd.html?highlight=gradcheck#torch.autograd.gradcheck).

**Comment by rgommers** [comment]
Note, this is blocked for the same reason as https://github.com/pytorch/pytorch/issues/29137#issuecomment-578538543 (support for `dim=None`).
