### ISSUE TITLE
RuntimeError: !t.is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:591

### ISSUE THREAD

**Issue by chimoses** [pytorch/pytorch#29026]
## 🐛 Bug

RuntimeError: !t.is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:591

## To Reproduce
File "/home/jinzhu/pro/UIL/GraphMatch/layers.py", line 42, in forward
    output = torch.spmm(adj, support) 
RuntimeError: !t.is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:591, please report a bug to PyTorch.

**Comment by colesbury** [comment]
@chimoses can you provide the PyTorch version you're using? Any code to reproduce this issue would also be helpful.

**Comment by tgebhart** [comment]
For what it's worth, I am able to reproduce this error if my sparse tensor is not on the correct device. 

For example, using pytorch version 1.3.1:
```
import numpy as np
import torch

i = torch.LongTensor((np.arange(10),np.arange(10)))
v = torch.FloatTensor(np.random.normal(size=10))
G = torch.sparse.FloatTensor(i,v,torch.Size((100,100)))
x = torch.Tensor(np.random.normal(size=100))
device = torch.device('cuda:0')
x = x.to(device)
torch.mm(G, x.unsqueeze(1))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: !t.is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:591, please report a bug to PyTorch. 
```

**Comment by ZhangYikaii** [comment]
If sparse tensor is on the same device, can it solve the problem?
