### ISSUE TITLE
[jit][script] Support namedtuples from other files

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#29035]
## 🐛 Bug

`torch.jit.script` seems to choke when using namedtuples imported from other modules. There are possibly two distinct bugs here:

## To Reproduce

Suppose I have three files:

a.py
```python
from typing import NamedTuple
class Type(NamedTuple):
    t: int
```

b.py:
```python
import torch
import torch.nn as nn

import a

class M(nn.Module):
    def forward(self) -> a.Type:
        return a.Type(1)

torch.jit.script(M())
```

c.py:
```python
import torch
import torch.nn as nn

import a

class M(nn.Module):
    def forward(self):
        return a.Type(1)

torch.jit.script(M())
```

Then running `b.py` fails with:
```python
Traceback (most recent call last):
  File "b.py", line 10, in <module>
    torch.jit.script(M())
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 
Unknown type name 'a.Type':
at b.py:7:25
    def forward(self) -> a.Type:
                         ~~~~~~ <--- HERE
        return a.Type(1)
```

while running `c.py` fails with:
```python
Traceback (most recent call last):
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/_utils_internal.py", line 46, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "/opt/anaconda/envs/test/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/opt/anaconda/envs/test/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c.py", line 10, in <module>
    torch.jit.script(M())
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 1075, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/frontend.py", line 148, in get_jit_class_def
    self_name=self_name) for method in methods]
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/frontend.py", line 148, in <listcomp>
    self_name=self_name) for method in methods]
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/jit/frontend.py", line 160, in get_jit_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(fn)
  File "/opt/anaconda/envs/test/lib/python3.7/site-packages/torch/_utils_internal.py", line 50, in get_source_lines_and_file
    "Make sure original .py files are available. Original error: {}").format(filename, e))
OSError: Can't get source for None. TorchScript requires source access in order to carry out compilation. Make sure original .py files are available. Original error: could not get source code
```

Using a namedtuple defined *within* the same file works just fine though.

## Expected behavior

Both `b.py` and `c.py` run without errors

## Environment
```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.0
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0               py3.7_cpu_0  [cpuonly]  pytorch
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by suo** [comment]
@jamesr66a mind taking a look when you get a chance?

**Comment by eellison** [comment]
To give an update on this: @driazati has been working on resolve type aliases by value instead of textually. This is close to being done but not fully finished. The only limitation right now is that we don't support resolution of `.` on types/namespaces within the body of TorchScript functions. As a workaround, until that is landed, the following works.

a.py
```
from typing import NamedTuple
class Type(NamedTuple):
    t: int
```
b.py:
```
import torch
import torch.nn as nn

import a

a_type_alias = a.Type  # TorchScript doesn't support '.' on types in function body yet
class M(nn.Module):
    def forward(self) -> a.Type:
        return alias(1)

torch.jit.script(M())
```
c.py:
```
import torch
import torch.nn as nn

import a
type_alias = a.Type
class M(nn.Module):
    def forward(self):
        return type_alias(1)

torch.jit.script(M())
```
