### ISSUE TITLE
[Feature request] Provide binaries for Python 3.8

### ISSUE THREAD

**Issue by tjf801** [pytorch/pytorch#29090]
## 🐛 Bug

Trying to install torch results in a python error.

## To Reproduce

1. Install Python (python-3.8.0-amd64.exe)
2. run pip install numpy
3. run pip install torch torchvision -f https://download.pytorch.org/whl/torch_stable.html

## Expected behavior

Pytorch gets installed

## Environment

```
C:\Windows\system32>python C:\temp\collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
OS: Microsoft Windows 10 Home
GCC version: (GCC) 4.6.1
CMake version: Could not collect
Python version: 3.8
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 980 Ti
Nvidia driver version: 430.86
cuDNN version: Could not collect
Versions of relevant libraries:
[pip3] numpy==1.17.3
[conda] Could not collect
```

## Additional context

Full console output:
```
C:\Windows\system32>pip install torch torchvision -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/fb/01/03fd7e503c16b3dc262483e5555ad40974ab5da8b9879e164b56c1f4ef6f/torchvision-0.2.2.post3-py2.py3-none-any.whl
Collecting pyyaml
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
     |████████████████████████████████| 266kB 1.3MB/s
Collecting six
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: numpy in c:\program files\python38\lib\site-packages (from torchvision) (1.17.3)
Collecting pillow>=4.1.1
  Downloading https://files.pythonhosted.org/packages/b6/5a/ee223b0503ebba3d6adcf24516cbae85d581058f2bac635fc82e4bd6c2bf/Pillow-6.2.1-cp38-cp38-win_amd64.whl (2.0MB)
     |████████████████████████████████| 2.0MB 6.4MB/s
Installing collected packages: pyyaml, torch, six, pillow, torchvision
    Running setup.py install for pyyaml ... done
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qo2q0sjc\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qo2q0sjc\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tyler\AppData\Local\Temp\pip-record-72uhhcea\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Tyler\AppData\Local\Temp\pip-install-qo2q0sjc\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Tyler\AppData\Local\Temp\pip-install-qo2q0sjc\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "c:\program files\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Tyler\AppData\Local\Temp\pip-install-qo2q0sjc\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\program files\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Tyler\AppData\Local\Temp\pip-install-qo2q0sjc\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qo2q0sjc\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qo2q0sjc\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tyler\AppData\Local\Temp\pip-record-72uhhcea\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

```

cc @ezyang @gchanan @zou3519

**Comment by peterjc123** [comment]
Python 3.8 binaries are not yet available. cc @soumith

**Comment by tjf801** [comment]
ah. didn't think of that.

**Comment by aybberk** [comment]
Python is upgraded to 3.8 in arch linux based distros recently, I suppose many arch or manjaro users are waiting for 3.8 binaries.

**Comment by rlaPHOENiX** [comment]
Any update on this? A LOT of software on Arch Linux Repository are rebuilt specifically for 3.8 so it's a tad bit annoying setting up an environment just for torch.

**Comment by dvolgyes** [comment]
The more worrying part for me that i don't see progress for nightly testing of python3.8. 
I mean no wheel for 1.4dev or 1.5dev (https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html), and i don't see that e.g. someone would update the 
setup.py in https://github.com/pytorch/pytorch/blob/master/setup.py to have 3.8 included, etc.

Is there any issue which tracks the requirements for a python3.8 binary? What blocks the nightly builds? Or it is just matter of updated build scripts?

**Comment by hyperfraise** [comment]
There is this though : " torch-1.4.0-cp38-cp38-linux_x86_64.whl". I'm not aware if this is good or just a dud ?

**Comment by ezyang** [comment]
Sorry about the lack of communication; @seemethere is working on this.

**Comment by rlaPHOENiX** [comment]
Latest torch now has Python 3.8 binaries, this can be closed I believe.

**Comment by hyperfraise** [comment]
This worked on my machine 
```
veesion@earth2:~$ python3.8 -m pip install https://download.pytorch.org/whl/nightly/cu101/torch-1.4.0-cp38-cp38-linux_x86_64.whl --user
Collecting torch==1.4.0
  Using cached https://download.pytorch.org/whl/nightly/cu101/torch-1.4.0-cp38-cp38-linux_x86_64.whl
Installing collected packages: torch
Successfully installed torch-1.4.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
veesion@earth2:~$ python3.8
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 
```

**Comment by ezyang** [comment]
I'm going to keep this open for now until the website is fixed (it still implies only 3.7 is available)

**Comment by rlaPHOENiX** [comment]
> I'm going to keep this open for now until the website is fixed (it still implies only 3.7 is available)

The 3.7 provided command also works with 3.8.x but I assume that's not why you are keeping it open, but regardless isn't this specific issue resolved? The issue was to provide binaries for 3.8, which it has.

**Comment by peterjc123** [comment]
It cannot be closed because the binaries for Python 3.8 are not fully released on PyPI and Anaconda Cloud. (e.g. MacOS on PyPI, [MacOS, Linux] on Anaconda Cloud).

**Comment by seemethere** [comment]
macOS binaries should be covered in https://github.com/pytorch/pytorch/pull/31948

and should be good to start the release process after it has been merged.

**Comment by soumith** [comment]
waiting on macOS v1.4.0 builds to finish in https://github.com/pytorch/pytorch/pull/31542

**Comment by soumith** [comment]
after they finish, for Linux, macOS, need to build torchvision binaries

**Comment by soumith** [comment]
- website wizard updated.
- torch, torchvision, torchaudio stable binaries for python 3.8 are live.
