### ISSUE TITLE
crash when call dist.new_group(ranks=local_ranks, backend='gloo')

### ISSUE THREAD

**Issue by hujuntao123** [pytorch/pytorch#29115]
## 🐛 Bug

process crash when call dist.new_group(ranks=local_ranks, backend='gloo')

## To Reproduce

1.
1.
1.

dist.init_process_group(backend='gloo', init_method=args.dist_url, world_size=args.world_size, rank=args.rank)
local_group = dist.new_group(ranks=local_ranks, backend='gloo')

Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/opt/CAT/egs/swbd/swbd_recog_h_adpsgd.py", line 249, in speech_recognition_wsj
    local_group = dist.new_group(ranks=local_ranks, backend='gloo')
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1490, in new_group
    timeout=timeout)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 478, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/address.cc:29] sizeof(ss_) == bytes.size(). 128 vs 42
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.3):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 10.0.130
 - GPU models and configuration:
 - Any other relevant information:

**Comment by nakulgulati** [comment]
Is there a way to identify what might be misconfigured between the 2 nodes as mentioned in the mentioned CrypTen#323 issue?

In my setup, I am trying to run distributed training across Mac (master node) and a Linux (Ubuntu) (worker node) within the same network.
