### ISSUE TITLE
_compared_saved_loaded doesn't work with torch.tensor constants

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#29125]
Steps to reproduce:

1. Add this test to `test_jit.py`:

```
    def test_trace_modern_ctor(self):
        class MyModule(nn.Module):
            def forward(self, x):
                return (x + 1, torch.tensor([0.0]))

        # Shouldn't fail sanity checks
        traced_rec = torch.jit.trace(MyModule(), torch.randn(2, 2))
```

2. Run test:

```
Traceback (most recent call last):
  File "test/test_jit.py", line 324, in test_trace_modern_ctor
    traced_rec = torch.jit.trace(MyModule(), torch.randn(2, 2))
  File "/scratch/ezyang/pytorch-tmp/torch/jit/__init__.py", line 880, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/scratch/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1020, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/scratch/ezyang/pytorch-tmp/test/jit_utils.py", line 178, in emitModuleHook
    self._compared_saved_loaded(module)
  File "/scratch/ezyang/pytorch-tmp/test/jit_utils.py", line 164, in _compared_saved_loaded
    self.assertMultiLineEqual(a, b)
AssertionError: 'op_v[210 chars]NTS.c1, torch.device("cpu"), 7, False, False, [84 chars]_1\n' != 'op_v[210 chars]NTS.c0, t
orch.device("cpu"), 7, False, False, [84 chars]_1\n'
  op_version_set = 1
  class Module(Module):
    __parameters__ = []
    training : bool
    def forward(self: __torch__.torch.nn.modules.module.Module,
      x: Tensor) -> Tuple[Tensor, Tensor]:
-     _0 = torch.to(CONSTANTS.c1, torch.device("cpu"), 7, False, False, None)
?                              ^
+     _0 = torch.to(CONSTANTS.c0, torch.device("cpu"), 7, False, False, None)
?                              ^
-     _1 = (torch.add(x, CONSTANTS.c0, alpha=1), torch.detach(_0))
?                                   ^
+     _1 = (torch.add(x, CONSTANTS.c1, alpha=1), torch.detach(_0))
?                                   ^
      return _1
```

Seems like there's something wrong where we are not resetting constant numbering second time around.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
