### ISSUE TITLE
[jit] RuntimeError: Expected ty->isSubtypeOf(atype) to be true, but got false. 

### ISSUE THREAD

**Issue by Rikorose** [pytorch/pytorch#29122]
## 🐛 Bug

I am not quite sure, but I think this error occurs if a TracedModule is getting scripted.
Only present in the latest nightly from today. It works in 1.3.0.

```py
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    train(config, os.path.expanduser(args.data_dir))
  File "train.py", line 25, in train
    clcnet = torch.jit.script(clcnet)
  File "/cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/jit/__init__.py", line 1239, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 527, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 324, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 374, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/jit/__init__.py", line 1625, in _construct
    init_fn(script_module)
  File "/cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 357, in init_fn
    cpp_module._register_module(name, scripted._c)
RuntimeError: Expected ty->isSubtypeOf(atype) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.) (addOrCheckAttribute at /pytorch/aten/src/ATen/core/jit_type.h:1498)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fabee542c03 in /cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x60ee7b (0x7fac3871de7b in /cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x60f3a4 (0x7fac3871e3a4 in /cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x6217e8 (0x7fac387307e8 in /cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x22b974 (0x7fac3833a974 in /cluster/schroeter/miniconda/envs/clc-lme171-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyMethodDef_RawFastCallKeywords + 0x264 (0x557138f32c34 in python train.py)
frame #6: _PyCFunction_FastCallKeywords + 0x21 (0x557138f32d51 in python train.py)
frame #7: _PyEval_EvalFrameDefault + 0x52e6 (0x557138f9f4d6 in python train.py)
frame #8: _PyEval_EvalCodeWithName + 0xab8 (0x557138ee2978 in python train.py)
frame #9: _PyFunction_FastCallKeywords + 0x387 (0x557138f32437 in python train.py)
frame #10: _PyEval_EvalFrameDefault + 0x416 (0x557138f9a606 in python train.py)
frame #11: _PyFunction_FastCallKeywords + 0xfb (0x557138f321ab in python train.py)
frame #12: _PyEval_EvalFrameDefault + 0x4b29 (0x557138f9ed19 in python train.py)
frame #13: _PyEval_EvalCodeWithName + 0xab8 (0x557138ee2978 in python train.py)
frame #14: _PyFunction_FastCallKeywords + 0x387 (0x557138f32437 in python train.py)
frame #15: _PyEval_EvalFrameDefault + 0x416 (0x557138f9a606 in python train.py)
frame #16: _PyFunction_FastCallKeywords + 0xfb (0x557138f321ab in python train.py)
frame #17: _PyEval_EvalFrameDefault + 0x416 (0x557138f9a606 in python train.py)
frame #18: _PyFunction_FastCallKeywords + 0xfb (0x557138f321ab in python train.py)
frame #19: _PyEval_EvalFrameDefault + 0x4b29 (0x557138f9ed19 in python train.py)
frame #20: _PyEval_EvalCodeWithName + 0x2f9 (0x557138ee21b9 in python train.py)
frame #21: _PyFunction_FastCallKeywords + 0x325 (0x557138f323d5 in python train.py)
frame #22: _PyEval_EvalFrameDefault + 0x4b29 (0x557138f9ed19 in python train.py)
frame #23: _PyFunction_FastCallKeywords + 0xfb (0x557138f321ab in python train.py)
frame #24: _PyEval_EvalFrameDefault + 0x416 (0x557138f9a606 in python train.py)
frame #25: _PyEval_EvalCodeWithName + 0x2f9 (0x557138ee21b9 in python train.py)
frame #26: PyEval_EvalCodeEx + 0x44 (0x557138ee3094 in python train.py)
frame #27: PyEval_EvalCode + 0x1c (0x557138ee30bc in python train.py)
frame #28: <unknown function> + 0x22a9e4 (0x557138ff99e4 in python train.py)
frame #29: PyRun_FileExFlags + 0xa1 (0x557139003de1 in python train.py)
frame #30: PyRun_SimpleFileExFlags + 0x1c3 (0x557139003fd3 in python train.py)
frame #31: <unknown function> + 0x2360c5 (0x5571390050c5 in python train.py)
frame #32: _Py_UnixMain + 0x3c (0x5571390051ec in python train.py)
frame #33: __libc_start_main + 0xe7 (0x7fac41af3b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #34: <unknown function> + 0x1daf7d (0x557138fa9f7d in python train.py)

```

## To Reproduce

This error message makes it quite hard to isolate and provide an reproducable example. However, if I don't trace the child module, the error is gone.

## Expected behavior

A TracedModule should be convertable to a ScriptModule as explained in the JIT tutorial.

## Environment

Running on torch1.4.0.dev20191103+cu100

## Additional context

Code that fails introduced in: #28408 
Relevant line: https://github.com/pytorch/pytorch/blob/529c2df/aten/src/ATen/core/jit_type.h#L1478

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by suo** [comment]
Thanks for the speedy report! @wanchaol, can you take a look?

**Comment by wanchaol** [comment]
@Rikorose I did some investigation on this, it seems tracedModule can be successfully turned into ScriptModule on my side. The below works fine. Did you happen to have a re-produciable example that I could look at?

```python
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        return self.conv(x)

n = Net()
example_forward_input = torch.rand(1, 1, 3, 3)


# Trace a module (implicitly traces `forward`) and construct a
# `ScriptModule` with a single `forward` method
module = torch.jit.trace(n, example_forward_input)


class ScriptNet(nn.Module):
    def __init__(self):
        super(ScriptNet, self).__init__()
        self.net = torch.jit.trace(n, example_forward_input)
    def forward(self, input):
        return self.net(input)

scripted_mod = torch.jit.script(ScriptNet())
print(scripted_mod.graph)
print(scripted_mod(example_forward_input))
scripted_traced = torch.jit.script(module)
scripted_traced(example_forward_input)
```

**Comment by Rikorose** [comment]
Your example works fine. Here is an examples that fails:

```py
from typing import Optional, Tuple, List

import torch
import torch.nn as nn
from torch import Tensor

print(torch.__version__)

bs = 2
n_feat = 4
n_time_steps = 5


class Cell(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x: Tensor, state: Tensor) -> Tuple[Tensor, Tensor]:
        return x + state, state


class MyRNN(nn.Module):
    def __init__(self, trace=True):
        super().__init__()
        example_cell_input = torch.rand((bs, n_feat))
        example_cell_state = torch.rand((bs, n_feat))
        self.cell = Cell()
        if trace:
            self.cell = torch.jit.trace(
                self.cell, (example_cell_input, example_cell_state)
            )
            print(self.cell.graph)

    def forward(
        self, x: Tensor, state: Optional[Tensor] = None
    ) -> Tuple[Tensor, Tensor]:
        # x has shape [bs, n_time_steps, n_feat]
        # state has shape [bs, n_feat]
        if state is None:
            state = x[:, 0]
        inputs = torch.unbind(x, dim=1)
        outputs: List[Tensor] = []
        for input in inputs:
            out, state = self.cell(input, state)
            outputs.append(out)
        return torch.stack(outputs, dim=1), state


class Net(nn.Module):
    def __init__(self, trace=True):
        super().__init__()
        self.rnn = MyRNN(trace)

    def forward(self, x):
        return self.rnn(x)


example_input = torch.rand(bs, n_time_steps, n_feat)

net = torch.jit.script(Net(trace=False))
print(net.graph)
print(net(example_input)[0])


net = torch.jit.script(Net(trace=True))
print(net.graph)
print(net(example_input)[0])
```

ouptut:
```
1.4.0.dev20191103+cpu
graph(%self : ClassType<Net>,
      %x.1 : Tensor):
  %4 : None = prim::Constant()
  %2 : ClassType<MyRNN> = prim::GetAttr[name="rnn"](%self)
  %5 : (Tensor, Tensor) = prim::CallMethod[name="forward"](%2, %x.1, %4) # test-nightly.py:59:15
  return (%5)

tensor([[[0.8084, 0.9042, 1.1501, 0.8738],
         [0.9917, 1.2599, 1.2465, 0.8415],
         [0.7193, 0.6867, 1.0401, 1.2140],
         [0.7443, 0.4924, 1.3704, 1.0598],
         [0.9982, 1.0509, 0.7343, 0.9564]],

        [[0.0747, 1.6732, 1.9521, 0.5010],
         [0.6123, 1.4940, 1.3034, 0.5132],
         [0.9979, 1.5280, 1.0916, 1.0831],
         [0.2090, 1.4861, 1.5874, 1.0162],
         [0.1722, 1.7448, 1.7260, 1.0295]]])
graph(%self : ClassType<Module>,
      %x : Float(2, 4),
      %state : Float(2, 4)):
  %3 : int = prim::Constant[value=1](), scope: Cell # test-nightly.py:23:0
  %4 : Float(2, 4) = aten::add(%x, %state, %3), scope: Cell # test-nightly.py:23:0
  %5 : (Float(2, 4), Float(2, 4)) = prim::TupleConstruct(%4, %state)
  return (%5)

Traceback (most recent call last):
  File "test-nightly.py", line 69, in <module>
    net = torch.jit.script(Net(trace=True))
  File "/home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/jit/__init__.py", line 1239, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 527, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 324, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 374, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/jit/__init__.py", line 1625, in _construct
    init_fn(script_module)
  File "/home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/jit/_recursive.py", line 357, in init_fn
    cpp_module._register_module(name, scripted._c)
RuntimeError: Expected ty->isSubtypeOf(atype) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.) (addOrCheckAttribute at /pytorch/aten/src/ATen/core/jit_type.h:1498)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f83438fcc03 in /home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x5d8a1b (0x7f8344345a1b in /home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x5d8f44 (0x7f8344345f44 in /home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x5eb388 (0x7f8344358388 in /home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x205824 (0x7f8343f72824 in /home/schroeter/.virtualenvs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #38: __libc_start_main + 0xf3 (0x7f8354d1a1a3 in /lib64/libc.so.6)
```


output with torch 1.3:
```
1.3.0+cpu
graph(%self : ClassType<Net>,
      %x.1 : Tensor):
  %19 : int = prim::Constant[value=1]() # test-nightly.py:40:20
  %18 : int = prim::Constant[value=0]() # test-nightly.py:40:25
  %16 : int = prim::Constant[value=9223372036854775807]()
  %15 : bool = prim::Constant[value=1]() # test-nightly.py:43:8
  %4 : None = prim::Constant()
  %20 : bool = aten::__is__(%4, %4) # test-nightly.py:39:11
  %state.16 : Tensor = prim::If(%20) # test-nightly.py:39:8
    block0():
      %22 : Tensor = aten::slice(%x.1, %18, %18, %16, %19) # test-nightly.py:40:20
      %state.3 : Tensor = aten::select(%22, %19, %18) # test-nightly.py:40:20
      -> (%state.3)
    block1():
      %state.6 : Tensor = prim::unchecked_unwrap_optional(%4)
      -> (%state.6)
  %inputs.1 : Tensor[] = aten::unbind(%x.1, %19) # test-nightly.py:41:17
  %outputs.1 : Tensor[] = prim::ListConstruct()
  %27 : int = aten::len(%inputs.1) # test-nightly.py:43:8
  %state : Tensor = prim::Loop(%27, %15, %state.16) # test-nightly.py:43:8
    block0(%29 : int, %state.17 : Tensor):
      %input.1 : Tensor = aten::__getitem__(%inputs.1, %29) # test-nightly.py:43:8
      %32 : Tensor = aten::add(%input.1, %state.17, %19) # test-nightly.py:19:15
      %33 : Tensor[] = aten::append(%outputs.1, %32) # test-nightly.py:45:12
      -> (%15, %state.17)
  %34 : Tensor = aten::stack(%outputs.1, %19) # test-nightly.py:46:15
  %35 : (Tensor, Tensor) = prim::TupleConstruct(%34, %state)
  return (%35)

tensor([[[1.0364, 1.2812, 1.5786, 0.7055],
         [0.5862, 1.2645, 1.7089, 0.6976],
         [1.4981, 1.4103, 1.3854, 0.4430],
         [1.0085, 0.8317, 1.0783, 0.6536],
         [1.1869, 0.7174, 1.2420, 0.6019]],

        [[0.9784, 1.5539, 0.1289, 0.6238],
         [1.3010, 1.3545, 1.0116, 0.7779],
         [1.4245, 1.4506, 0.6269, 0.8208],
         [1.1967, 1.3468, 1.0084, 0.8542],
         [1.2746, 1.4780, 0.9470, 1.0152]]])
graph(%self : ClassType<Cell>,
      %x : Float(2, 4),
      %state : Float(2, 4)):
  %3 : int = prim::Constant[value=1](), scope: Cell # test-nightly.py:19:0
  %4 : Float(2, 4) = aten::add(%x, %state, %3), scope: Cell # test-nightly.py:19:0
  %5 : (Float(2, 4), Float(2, 4)) = prim::TupleConstruct(%4, %state)
  return (%5)

graph(%self : ClassType<Net>,
      %x.1 : Tensor):
  %19 : int = prim::Constant[value=1]() # test-nightly.py:40:20
  %18 : int = prim::Constant[value=0]() # test-nightly.py:40:25
  %16 : int = prim::Constant[value=9223372036854775807]()
  %15 : bool = prim::Constant[value=1]() # test-nightly.py:43:8
  %4 : None = prim::Constant()
  %20 : bool = aten::__is__(%4, %4) # test-nightly.py:39:11
  %state.16 : Tensor = prim::If(%20) # test-nightly.py:39:8
    block0():
      %22 : Tensor = aten::slice(%x.1, %18, %18, %16, %19) # test-nightly.py:40:20
      %state.3 : Tensor = aten::select(%22, %19, %18) # test-nightly.py:40:20
      -> (%state.3)
    block1():
      %state.6 : Tensor = prim::unchecked_unwrap_optional(%4)
      -> (%state.6)
  %inputs.1 : Tensor[] = aten::unbind(%x.1, %19) # test-nightly.py:41:17
  %outputs.1 : Tensor[] = prim::ListConstruct()
  %27 : int = aten::len(%inputs.1) # test-nightly.py:43:8
  %state : Tensor = prim::Loop(%27, %15, %state.16) # test-nightly.py:43:8
    block0(%29 : int, %state.17 : Tensor):
      %input.1 : Tensor = aten::__getitem__(%inputs.1, %29) # test-nightly.py:43:8
      %32 : Float(2, 4) = aten::add(%input.1, %state.17, %19), scope: Cell # test-nightly.py:19:0
      %33 : Tensor[] = aten::append(%outputs.1, %32) # test-nightly.py:45:12
      -> (%15, %state.17)
  %34 : Tensor = aten::stack(%outputs.1, %19) # test-nightly.py:46:15
  %35 : (Tensor, Tensor) = prim::TupleConstruct(%34, %state)
  return (%35)

tensor([[[1.0364, 1.2812, 1.5786, 0.7055],
         [0.5862, 1.2645, 1.7089, 0.6976],
         [1.4981, 1.4103, 1.3854, 0.4430],
         [1.0085, 0.8317, 1.0783, 0.6536],
         [1.1869, 0.7174, 1.2420, 0.6019]],

        [[0.9784, 1.5539, 0.1289, 0.6238],
         [1.3010, 1.3545, 1.0116, 0.7779],
         [1.4245, 1.4506, 0.6269, 0.8208],
         [1.1967, 1.3468, 1.0084, 0.8542],
         [1.2746, 1.4780, 0.9470, 1.0152]]])
```

**Comment by wanchaol** [comment]
@Rikorose thanks for the example! This seems happening even before https://github.com/pytorch/pytorch/pull/28408, I will post when I find the real issue.

**Comment by wanchaol** [comment]
possibly related to module dedup, the full error message on my side is:
```
Traceback (most recent call last):
  File "/home/wanchaol/test.py", line 239, in <module>
    net = torch.jit.script(Net(trace=True))
  File "/data/users/wanchaol/pytorch/torch/jit/__init__.py", line 1239, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/data/users/wanchaol/pytorch/torch/jit/_recursive.py", line 566, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/data/users/wanchaol/pytorch/torch/jit/_recursive.py", line 334, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/data/users/wanchaol/pytorch/torch/jit/_recursive.py", line 389, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/data/users/wanchaol/pytorch/torch/jit/__init__.py", line 1639, in _construct
    init_fn(script_module)
  File "/data/users/wanchaol/pytorch/torch/jit/_recursive.py", line 372, in init_fn
    cpp_module._register_module(name, scripted._c)
RuntimeError: __torch__.___torch_mangle_1.MyRNN is not compatible with the type __torch__.MyRNN for the field 'rnn' (addOrCheckAttribute at ../aten/src/ATen/core/jit_type.h:1508)
```
`MyRNN` is created when we scripted the `Net`, the ConcreteModuleType of `Net` created a `__torch__.MyRNN`, and this ConcreteModuleType of `MyRNN` seems poisoned because it contains tracing module, therefore when we recursively script `self.rnn` itself, the ConcreteModuleType store could not find the previous one, and generate a new ConcreteModuleType and give a JitType of `___torch_mangle_1.MyRNN`.

This is probably related to how we handle the module dedup case when mixing tracing and scripting, @suo can you take a look?

**Comment by suo** [comment]
This is fixed by https://github.com/pytorch/pytorch/pull/29583

**Comment by suo** [comment]
Closing as the fix has landed
