### ISSUE TITLE
PytorchStreamWriter failed opening archive.

### ISSUE THREAD

**Issue by zsk423200** [pytorch/pytorch#29186]
## ❓ Questions and Help

pytorch:1.3
torchvision:0.4.1

i want to save TorchScipt model:
```
import torch
import torchvision

# An instance of your model.
model = torchvision.models.resnet18()

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 224, 224)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)
# output = traced_script_module(torch.ones(1, 3, 224, 224))
# print(output[0, :5])
traced_script_module.save("traced_resnet_model.pt")
```
the same as the [tutorials](https://pytorch.org/tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing),but has the error:
```
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    traced_script_module.save("traced_resnet_model.pt")
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 1559, in save
    return self._c.save(*args, **kwargs)
RuntimeError: [enforce fail at inline_container.cc:319] . PytorchStreamWriter failed opening archive.
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x5b (0x7f1ca5b2241b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamWriter::valid(char const*) + 0xe6 (0x7f1ca9fa0a06 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamWriter::PyTorchStreamWriter(std::string, std::ostream*) + 0x74d (0x7f1ca9fa3c5d in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: torch::jit::ExportModule(torch::jit::script::Module const&, std::string const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, bool) + 0x127 (0x7f1cab4eb007 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x57eaf2 (0x7f1cd9c2eaf2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x206aa6 (0x7f1cd98b6aa6 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: __libc_start_main + 0xf0 (0x7f1ce94e3830 in /lib/x86_64-linux-gnu/libc.so.6)
```
where am i wrong??

**Comment by MaybeS** [comment]
Same problem here
@zsk423200  did you solve this problem?

**Comment by jtao151617** [comment]
tried change the saving path worked for me

**Comment by StevenJokes** [comment]
@jtao151617  How to fix it ? I almost die for it.

**Comment by jtao151617** [comment]
> @jtao151617 How to fix it ? I almost die for it.

I changed the saving path to a different directory to make sure there is no constrain to create a new file.

**Comment by hhsecond** [comment]
For anyone who would reach here in the future: in my case, my script did not have access to write to the `path` I had given. So changing the path or giving the required permission on the path had fixed mine

**Comment by niklasbubeck** [comment]
To also add something, for me the error occurred when my memory was used up :)

**Comment by akn264** [comment]
> For anyone who would reach here in the future: in my case, my script did not have access to write to the `path` I had given. So changing the path or giving the required permission on the path had fixed mine

hey sorry for the basic question, but how did you know your script didn't have access to write to the provided path? I'm able to save some logging info, but run into this error when trying to save a model checkpoint in the same directory as the logging info
