### ISSUE TITLE
RuntimeError: CUDA out of memory with available GPU memory

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/pytorch#29198]
I'm running Pytorch bert with adam optimizer. I get a CUDA OOM: 

`RuntimeError: CUDA out of memory. Tried to allocate 352.00 MiB (GPU 0; 7.92 GiB total capacity; 1.67 GiB already allocated; 156.00 MiB free; 124.28 MiB cached)`

but I actually I have some GiG available:

```
Traceback (most recent call last):
 File "train.py", line 156, in <module>
   train(model, train_iter, optimizer, criterion)
 File "train.py", line 29, in train
   optimizer.step()
 File "/usr/local/lib/python3.6/dist-packages/torch/optim/adam.py", line 77, in step
   state['exp_avg_sq'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 352.00 MiB (GPU 0; 7.92 GiB total capacity; 1.67 GiB already allocated; 156.00 MiB free; 124.28 MiB cached)
```

where when the error came out I had

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    On   | 00000000:01:00.0 Off |                  N/A |
| 73%   82C    P2   138W / 200W |   5560MiB /  8111MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    On   | 00000000:03:00.0 Off |                  N/A |
| 66%   68C    P2   108W / 210W |   5261MiB /  8119MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1264      G   /usr/lib/xorg/Xorg                            39MiB |
|    0      1461      G   /usr/bin/gnome-shell                          11MiB |
|    0     29120      C   python                                      5497MiB |
|    1     29607      C   python                                      5249MiB |
+-----------------------------------------------------------------------------+
```

**Comment by VitalyFedyunin** [comment]
Hi! Can you please provide minimal reproducible script.

**Comment by loretoparisi** [comment]
@VitalyFedyunin yes thank you.
The reference repository is Kyubyong's https://github.com/Kyubyong/bert_ner

The line that causes the OOM is `optimizer.step()`:
https://github.com/Kyubyong/bert_ner/blob/master/train.py#L25 

```python
      optimizer.zero_grad()
        logits, y, _ = model(x, y) # logits: (N, T, VOCAB), y: (N, T)

        logits = logits.view(-1, logits.shape[-1]) # (N*T, VOCAB)
        y = y.view(-1)  # (N*T,)

        loss = criterion(logits, y)
        loss.backward()

        optimizer.step()
```
It uses `zero_grad` so it should not retain the gradients.

We use BERT's `multi_cased_L-12_H-768_A-12` model (https://github.com/google-research/bert), hence, loaded from pre-trained model:

`self.bert = BertModel.from_pretrained('bert-base-cased')`

started like

```
python3 train.py \
--logdir /root/data/checkpoints/finetuning_model100 \
--finetuning \
--batch_size 16 \
--lr 5e-5 \
--n_epochs 10
```

We have tried `batch_size` to 16, 8, 4, 2 with the same OOM result.
