### ISSUE TITLE
Cannot Import torch 1.3 on Windows10 without GPU but To import torch 1.2 is well done

### ISSUE THREAD

**Issue by Yunseong-Jeong** [pytorch/pytorch#29279]
## 🐛 Bug

Error when installing torch 1.3 version using pip at https://pytorch.org/get-started/locally/
## To Reproduce

<code>pip3 install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html</code>

Error Message
<code>>>> import torch </code>
<code>Traceback (most recent call last): </code>
<code>  File "<stdin>", line 1, in <module> </code>
<code> File "C:\Users\jbnu\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module> </code>
<code>     from torch._C import *</code>
<code>ImportError: DLL load failed: 지정된 프로시저를 찾을 수 없습니다. </code>
![image](https://user-images.githubusercontent.com/52766795/68275518-411e4100-00af-11ea-9b72-6f22286bb1a2.png)

## Expected behavior

So I installed Previous Version 1.2
<code>pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html</code>

![image](https://user-images.githubusercontent.com/52766795/68275707-c9044b00-00af-11ea-91cf-dcff3d28774b.png)

## Environment
<pre>
PyTorch version: 1.2.0+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.2.0+cpu
[pip3] torchvision==0.4.0+cpu
[conda] Could not collect
</pre>

## Additional context

I think that Previous version is more stable than Current version so that compare to previous code , current code is overwritten by previous code
but I'm not sure that this way is suitable.

I want to fix this bug. so can i try to fix it?

cc @peterjc123

**Comment by peterjc123** [comment]
You could use https://github.com/lucasg/Dependencies to open `[PYTHONPATH]\lib\site-packages\torch\_C.pyd` to see which DLLs are not able to be loaded.

**Comment by peterjc123** [comment]
Oh, looks like it's the same problem as #29356.

**Comment by peterjc123** [comment]
Wait, you are using CPU builds? Then it is not related to #29356. Would you please use Process Monitor or Dependencies and post the log here?

**Comment by Yunseong-Jeong** [comment]
![image](https://user-images.githubusercontent.com/52766795/68364694-10531000-0172-11ea-9fef-10cd00e5b0c0.png)
I think that is not _C.pyd , is _C.cp37-win_amd64.pyd
is it right??

Just in case, I take a screenshot of version 1.2.
![image](https://user-images.githubusercontent.com/52766795/68365131-257c6e80-0173-11ea-8f59-932fe44eba52.png)

**Comment by Yunseong-Jeong** [comment]
Run torch/utils/collect_env.py in pytorch 1.3
```
C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\utils>python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.3.0+cpu
[pip3] torchvision==0.4.1+cpu
[conda] Could not collect
```
Run torch/utils/collect_env.py in pytorch 1.2
```
PyTorch version: 1.2.0+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.2.0+cpu
[pip3] torchvision==0.4.0+cpu
[conda] Could not collect
```

**Comment by peterjc123** [comment]
What about running this code: https://gist.github.com/peterjc123/21143c0c9426a025618260dde5b6219a?

**Comment by Yunseong-Jeong** [comment]
```
C:\Users\jbnu\Desktop>python check_import.py
It seems `import torch` should work.You may try to add `C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Library\bin` to the environment variable `PATH`.
And make sure you restart the command prompt when you apply any changes to the environment.
```

![image](https://user-images.githubusercontent.com/52766795/68366407-996c4600-0176-11ea-847a-b533963ca065.png)

and then
```
C:\Users\jbnu\Desktop>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jbnu\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: 지정된 프로시저를 찾을 수 없습니다.
>>>
```

**Comment by peterjc123** [comment]
That's weird. Would you please read this article https://www.codeproject.com/Articles/560816/Troubleshooting-dependency-resolution-problems-usi?

**Comment by Yunseong-Jeong** [comment]
I will read and try it

**Comment by Yunseong-Jeong** [comment]
```
C:\Users\jbnu\Downloads\DependzBinary>Dependz.exe -i ./ProcMonLog.XML -p python.exe -v
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
Process: python.exe
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
        Error: Illegal characters in path.
kernel.appcore.dll - Resolved: C:\Windows\System32\kernel.appcore.dll
Probed Paths:
        C:\Windows\System32\kernel.appcore.dll

ntdll.dll - Resolved: C:\Windows\System32\ntdll.dll
Probed Paths:
        C:\Windows\System32\ntdll.dll

kernel32.dll - Resolved: C:\Windows\System32\kernel32.dll
Probed Paths:
        C:\Windows\System32\kernel32.dll

KernelBase.dll - Resolved: C:\Windows\System32\KernelBase.dll
Probed Paths:
        C:\Windows\System32\KernelBase.dll

ucrtbase.dll - Resolved: C:\Windows\System32\ucrtbase.dll
Probed Paths:
        C:\Windows\System32\ucrtbase.dll

python37.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\python37.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\python37.dll

vcruntime140.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\vcruntime140.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\vcruntime140.dll

shlwapi.dll - Resolved: C:\Windows\System32\shlwapi.dll
Probed Paths:
        C:\Windows\System32\shlwapi.dll

version.dll - Resolved: C:\Windows\System32\version.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\VERSION.dll
        C:\Windows\System32\version.dll

msvcrt.dll - Resolved: C:\Windows\System32\msvcrt.dll
Probed Paths:
        C:\Windows\System32\msvcrt.dll

combase.dll - Resolved: C:\Windows\System32\combase.dll
Probed Paths:
        C:\Windows\System32\combase.dll

rpcrt4.dll - Resolved: C:\Windows\System32\rpcrt4.dll
Probed Paths:
        C:\Windows\System32\rpcrt4.dll

bcryptprimitives.dll - Resolved: C:\Windows\System32\bcryptprimitives.dll
Probed Paths:
        C:\Windows\System32\bcryptprimitives.dll

gdi32.dll - Resolved: C:\Windows\System32\gdi32.dll
Probed Paths:
        C:\Windows\System32\gdi32.dll

win32u.dll - Resolved: C:\Windows\System32\win32u.dll
Probed Paths:
        C:\Windows\System32\win32u.dll

gdi32full.dll - Resolved: C:\Windows\System32\gdi32full.dll
Probed Paths:
        C:\Windows\System32\gdi32full.dll

msvcp_win.dll - Resolved: C:\Windows\System32\msvcp_win.dll
Probed Paths:
        C:\Windows\System32\msvcp_win.dll

user32.dll - Resolved: C:\Windows\System32\user32.dll
Probed Paths:
        C:\Windows\System32\user32.dll

ws2_32.dll - Resolved: C:\Windows\System32\ws2_32.dll
Probed Paths:
        C:\Windows\System32\ws2_32.dll

advapi32.dll - Resolved: C:\Windows\System32\advapi32.dll
Probed Paths:
        C:\Windows\System32\advapi32.dll

sechost.dll - Resolved: C:\Windows\System32\sechost.dll
Probed Paths:
        C:\Windows\System32\sechost.dll

imm32.dll - Resolved: C:\Windows\System32\imm32.dll
Probed Paths:
        C:\Windows\System32\imm32.dll

cryptsp.dll - Resolved: C:\Windows\System32\cryptsp.dll
Probed Paths:
        C:\Windows\System32\cryptsp.dll

rsaenh.dll - Resolved: C:\Windows\System32\rsaenh.dll
Probed Paths:
        C:\Windows\System32\rsaenh.dll

bcrypt.dll - Resolved: C:\Windows\System32\bcrypt.dll
Probed Paths:
        C:\Windows\System32\bcrypt.dll

cryptbase.dll - Resolved: C:\Windows\System32\cryptbase.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\CRYPTBASE.dll
        C:\Windows\System32\cryptbase.dll

tzres.dll - Resolved: C:\Windows\System32\tzres.dll
Probed Paths:
        C:\Windows\System32\tzres.dll

python3.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\python3.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\python3.dll

ole32.dll - Resolved: C:\Windows\System32\ole32.dll
Probed Paths:
        C:\Windows\System32\ole32.dll

oleaut32.dll - Resolved: C:\Windows\System32\oleaut32.dll
Probed Paths:
        C:\Windows\System32\oleaut32.dll

libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll

libcrypto-1_1-x64.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\DLLs\libcrypto-1_1-x64.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\DLLs\libcrypto-1_1-x64.dll

torch_python.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\torch_python.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\torch_python.dll
        C:\Windows\System32\torch_python.dll
        C:\Windows\System\torch_python.dll
        C:\Windows\torch_python.dll
        C:\Users\jbnu\torch_python.dll
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\torch_python.dll

torch.dll - Resolved: C:\Windows\System32\torch.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\torch.dll
        C:\Windows\System32\torch.dll

c10.dll - Resolved: C:\Windows\System32\c10.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\c10.dll
        C:\Windows\System32\c10.dll

shm.dll - Resolved: C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\shm.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\shm.dll
        C:\Windows\System32\shm.dll
        C:\Windows\System\shm.dll
        C:\Windows\shm.dll
        C:\Users\jbnu\shm.dll
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\shm.dll

msvcp140.dll - Resolved: C:\Windows\System32\msvcp140.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\MSVCP140.dll
        C:\Windows\System32\msvcp140.dll

libiomp5md.dll - Resolved: C:\Windows\System32\libiomp5md.dll
Probed Paths:
        C:\Users\jbnu\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\libiomp5md.dll
        C:\Windows\System32\libiomp5md.dll
```

it's too long... i don't know   to occur "Error: Illegal characters in path."

**Comment by peterjc123** [comment]
Wait, why would the torch dlls like `torch.dll`, `libiomp5md.dll`, `c10.dll` appear in the system dir `C:\Windows\System32`? Could you please delete them all and try again? According to the mechanism of the windows, the DLLs in the system path will always be loaded first.

**Comment by Yunseong-Jeong** [comment]
```
C:\Users\jbnu>pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.3.1+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.3.1%2Bcpu-cp37-cp37m-win_amd64.whl (71.3MB)
     |████████████████████████████████| 71.3MB 384kB/s
Collecting torchvision==0.4.2+cpu
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.4.2%2Bcpu-cp37-cp37m-win_amd64.whl (750kB)
     |████████████████████████████████| 757kB ...
Requirement already satisfied: numpy in c:\users\jbnu\appdata\local\programs\python\python37\lib\site-packages (from torch==1.3.1+cpu) (1.17.3)
Requirement already satisfied: pillow>=4.1.1 in c:\users\jbnu\appdata\local\programs\python\python37\lib\site-packages (from torchvision==0.4.2+cpu) (6.2.1)
Requirement already satisfied: six in c:\users\jbnu\appdata\local\programs\python\python37\lib\site-packages (from torchvision==0.4.2+cpu) (1.13.0)
Installing collected packages: torch, torchvision
  Found existing installation: torch 1.3.0+cpu
    Uninstalling torch-1.3.0+cpu:
      Successfully uninstalled torch-1.3.0+cpu
  Found existing installation: torchvision 0.4.1+cpu
    Uninstalling torchvision-0.4.1+cpu:
      Successfully uninstalled torchvision-0.4.1+cpu
Successfully installed torch-1.3.1+cpu torchvision-0.4.2+cpu

C:\Users\jbnu>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from __future__ import print_function
>>> x =torch.rand(5,3)
>>> print(x)
tensor([[0.5968, 0.5827, 0.1775],
        [0.3794, 0.6390, 0.9961],
        [0.5367, 0.9790, 0.6728],
        [0.9425, 0.3383, 0.0573],
        [0.5086, 0.1542, 0.0715]])
>>>
```

Well done!! Thanks to your help :)
