### ISSUE TITLE
pip torch install error

### ISSUE THREAD

**Issue by jeffersonmike** [pytorch/pytorch#29394]
## 🐛 Bug

I am trying to install torch via pip and return the below error. Very new to this. If there is more info I can provide, let me know. 

Installing collected packages: pytorch
    Running setup.py install for pytorch ... error
    ERROR: Command errored out with exit status 1:

 - OS: Windows 
 - pip
 - Build command: pip install torch
 - Python version: 3.8 (32 bit)

## To Reproduce

1.pip install torch

C:\Users\jeffe\Documents\model-squeezenet>pip install torch
Collecting torch
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
Requirement already satisfied: pyyaml in c:\users\jeffe\appdata\local\programs\python\python38-32\lib\site-packages (from torch) (5.1.2)
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jeffe\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-yg1l215e\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-yg1l215e\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jeffe\AppData\Local\Temp\pip-record-e7rdsc5l\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\jeffe\AppData\Local\Temp\pip-install-yg1l215e\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jeffe\AppData\Local\Temp\pip-install-yg1l215e\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "c:\users\jeffe\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jeffe\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jeffe\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\jeffe\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jeffe\AppData\Local\Temp\pip-install-yg1l215e\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\jeffe\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jeffe\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jeffe\AppData\Local\Temp\pip-install-yg1l215e\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jeffe\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-yg1l215e\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-yg1l215e\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jeffe\AppData\Local\Temp\pip-record-e7rdsc5l\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by soumith** [comment]
1. we dont support 32-bit Python
2. We don't yet support Python 3.8, that support is being tracked in https://github.com/pytorch/pytorch/issues/29090
