### ISSUE TITLE
AdaptiveMaxPool3d tests need to generate non-equal values

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#2939]
Intermittent test failures occurring on AdaptiveMaxPool3d.

@gchanan and I have seen this in the past where Max pooling has exactly the same values in the same window, then it's differently resolved on CPU/GPU. For example [0 2.5 2.5 3] can give a max index of `1` or `2` on CUDA depending on the runtime.

So generating input values that are within epsilon of each other is important (especially at half precision).

@SsnL fix that one.

```
======================================================================
FAIL: test_AdaptiveMaxPool3d_tuple (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 3477, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "<https://build.pytorch.org/job/pytorch-master-py2-linux/ws/builder/pytorch/test/common_nn.py",> line 631, in __call__
    self._do_test(test_case, module, input)
  File "test_nn.py", line 109, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "<https://build.pytorch.org/job/pytorch-master-py2-linux/ws/builder/pytorch/test/common_nn.py",> line 519, in check_jacobian
    PRECISION
AssertionError: 0.4831197783494723 not less than or equal to 1e-05

======================================================================
FAIL: test_AdaptiveMaxPool3d_tuple_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 3478, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "<https://build.pytorch.org/job/pytorch-master-py2-linux/ws/builder/pytorch/test/common_nn.py",> line 711, in test_cuda
    test_case.assertEqual(cpu_gradInput, gpu_gradInput, 2e-4)
  File "<https://build.pytorch.org/job/pytorch-master-py2-linux/ws/builder/pytorch/test/common.py",> line 215, in assertEqual
    assertTensorsEqual(x, y)
  File "<https://build.pytorch.org/job/pytorch-master-py2-linux/ws/builder/pytorch/test/common.py",> line 207, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: 2.0 not less than or equal to 0.0002
```

**Comment by SsnL** [comment]
Will do. Thanks for identifying the issue.
