### ISSUE TITLE
Building 1.3.1 fails with "error: too few arguments to function"

### ISSUE THREAD

**Issue by SteffenBauer** [pytorch/pytorch#29444]
## 🐛 Bug

Local build of v1.3.1 fails; on two different machines ~~where build of 1.3.0 works fine.~~

## To Reproduce

1. Clean checkout of pytorch with `git clone --recursive https://github.com/pytorch/pytorch` etc. as described in README.md
2. `cd pytorch; git checkout tags/v1.3.1`
3. Build a wheel package with `USE_CUDA=1 CFLAGS="-march=native" USE_CUDNN=1 USE_FBGEMM=0 BUILD_TEST=0 USE_MKLDNN=1 USE_NNPACK=0 USE_QNNPACK=0 USE_DISTRIBUTED=0 BUILD_CAFFE2_OPS=0 USE_OPENMP=1 TORCH_CUDA_ARCH_LIST="5.0" USE_NCCL=0 python3 ./setup.py bdist_wheel`

Build breaks with these last lines, on two machines with different environment, with the same error ("too few arguments to function")

```
[1821/2164] Building CXX object caffe2/CMakeFiles/torch.dir/opt/onnxifi_op.cc.o
FAILED: caffe2/CMakeFiles/torch.dir/opt/onnxifi_op.cc.o 
/usr/bin/c++  -DAT_PARALLEL_OPENMP=1 -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_CUDA -D_FILE_OFFSET_BITS=64 -D_THP_CORE -Dtorch_EXPORTS -Iaten/src -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../caffe2/../torch/csrc/api -I../caffe2/../torch/csrc/api/include -I../caffe2/aten/src/TH -Icaffe2/aten/src/TH -I../caffe2/../torch/../aten/src -Icaffe2/aten/src -Icaffe2/../aten/src -Icaffe2/../aten/src/ATen -I../caffe2/../torch/csrc -I../caffe2/../torch/../third_party/miniz-2.0.8 -I../aten/src/TH -I../aten/../third_party/catch/single_include -I../aten/src/ATen/.. -Icaffe2/aten/src/ATen -I../third_party/miniz-2.0.8 -I../caffe2/core/nomnigraph/include -Icaffe2/aten/src/THC -I../aten/src/THC -I../aten/src/THCUNN -I../aten/src/ATen/cuda -I../c10/.. -I../aten/src/ATen/native/quantized/cpu/qnnpack/include -I../aten/src/ATen/native/quantized/cpu/qnnpack/src -I../aten/src/ATen/native/quantized/cpu/qnnpack/deps/clog/include -Iconfu-srcs/pthreadpool/include -Iconfu-srcs/cpuinfo/include -Iconfu-srcs/fp16/include -Ithird_party/ideep/mkl-dnn/include -I../third_party/ideep/mkl-dnn/src/../include -I../c10/cuda/../.. -isystem ../cmake/../third_party/eigen -isystem /usr/include/python3.5m -isystem /usr/local/lib/python3.5/dist-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /opt/rocm/hip/include -isystem /include -isystem ../cmake/../third_party/cub -isystem /usr/local/cuda/include -isystem ../third_party/ideep/include -isystem include -march=native -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -fPIC   -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -Wno-maybe-uninitialized -fvisibility=hidden -DCAFFE2_BUILD_MAIN_LIB -O2 -std=gnu++11 -MD -MT caffe2/CMakeFiles/torch.dir/opt/onnxifi_op.cc.o -MF caffe2/CMakeFiles/torch.dir/opt/onnxifi_op.cc.o.d -o caffe2/CMakeFiles/torch.dir/opt/onnxifi_op.cc.o -c ../caffe2/opt/onnxifi_op.cc
In file included from ../c10/core/CPUAllocator.h:7:0,
                 from ../caffe2/core/allocator.h:3,
                 from ../caffe2/core/context.h:9,
                 from ../caffe2/opt/onnxifi_op.h:8,
                 from ../caffe2/opt/onnxifi_op.cc:1:
../caffe2/opt/onnxifi_op.h: In instantiation of ‘caffe2::OnnxifiOp<Context>::buildBackendAndGraph(caffe2::Workspace*, const std::vector<long unsigned int>&, const string&)::<lambda()> [with Context = caffe2::CPUContext]’:
../caffe2/opt/onnxifi_op.h:186:22:   required from ‘struct caffe2::OnnxifiOp<Context>::buildBackendAndGraph(caffe2::Workspace*, const std::vector<long unsigned int>&, const string&) [with Context = caffe2::CPUContext; std::__cxx11::string = std::__cxx11::basic_string<char>]::<lambda()>’
../caffe2/opt/onnxifi_op.h:258:5:   required from ‘void caffe2::OnnxifiOp<Context>::buildBackendAndGraph(caffe2::Workspace*, const std::vector<long unsigned int>&, const string&) [with Context = caffe2::CPUContext; std::__cxx11::string = std::__cxx11::basic_string<char>]’
../caffe2/opt/onnxifi_op.h:124:25:   required from ‘caffe2::OnnxifiOp<Context>::OnnxifiOp(const caffe2::OperatorDef&, caffe2::Workspace*) [with Context = caffe2::CPUContext]’
../c10/util/Registry.h:184:50:   required from ‘static ObjectPtrType c10::Registerer<SrcType, ObjectPtrType, Args>::DefaultCreator(Args ...) [with DerivedType = caffe2::OnnxifiOp<caffe2::CPUContext>; SrcType = std::__cxx11::basic_string<char>; ObjectPtrType = std::unique_ptr<caffe2::OperatorBase>; Args = {const caffe2::OperatorDef&, caffe2::Workspace*}]’
../caffe2/opt/onnxifi_op.cc:430:1:   required from here
../c10/util/Logging.h:232:33: error: too few arguments to function
   CAFFE_ENFORCE_THAT_IMPL(Equals((x), (y)), #x " == " #y, __VA_ARGS__)
                                 ^
../c10/util/Logging.h:200:61: note: in definition of macro ‘CAFFE_ENFORCE_THAT_IMPL’
     const EnforceFailMessage& CAFFE_ENFORCE_THAT_IMPL_r_ = (condition); \
                                                             ^
../caffe2/opt/onnxifi_op.h:245:7: note: in expansion of macro ‘CAFFE_ENFORCE_EQ’
       CAFFE_ENFORCE_EQ(
       ^
In file included from /usr/include/c++/5/memory:79:0,
                 from ../third_party/protobuf/src/google/protobuf/stubs/common.h:41,
                 from third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:9,
                 from third_party/onnx/onnx/onnx-ml.pb.h:2,
                 from ../third_party/onnx/onnx/onnx_pb.h:50,
                 from ../caffe2/opt/onnxifi_op.h:5,
                 from ../caffe2/opt/onnxifi_op.cc:1:
/usr/include/c++/5/functional:2246:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = caffe2::OnnxifiOp<Context>::buildBackendAndGraph(caffe2::Workspace*, const std::vector<long unsigned int>&, const string&) [with Context = caffe2::CPUContext; std::__cxx11::string = std::__cxx11::basic_string<char>]::<lambda()>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = std::shared_ptr<caffe2::onnx::BackendGraphInfo>; _ArgTypes = {}]’, declared using local type ‘caffe2::OnnxifiOp<Context>::buildBackendAndGraph(caffe2::Workspace*, const std::vector<long unsigned int>&, const string&) [with Context = caffe2::CPUContext; std::__cxx11::string = std::__cxx11::basic_string<char>]::<lambda()>’, is used but never defined [-fpermissive]
       function<_Res(_ArgTypes...)>::
       ^
[1828/2164] Building CXX object caffe2/CMakeFiles/torch.dir/opt/tvm_transformer.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./setup.py", line 756, in <module>
    build_deps()
  File "./setup.py", line 324, in build_deps
    cmake=cmake)
  File "/tmp/workspace/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/tmp/workspace/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/tmp/workspace/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1
```

## Expected behavior

Build succeeds and .whl package is generated.

## Environment
Machine 1:

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS
 - How you installed PyTorch (`conda`, `pip`, source): N/A, is a build issue.
 - Build command you used (if compiling from source): See above step 3) in section "To reproduce"
 - Python version: 3.5
 - CUDA/cuDNN version: CUDA 9.0.176 cuDNN 7.2.1
 - GPU models and configuration: GeForce 940MX

Machine 2:
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Debian GNU/Linux 10 (buster)
 - How you installed PyTorch (`conda`, `pip`, source): N/A, is a build issue.
 - Build command you used (if compiling from source): See above step 3) in section "To reproduce", only difference environment variable `TORCH_CUDA_ARCH_LIST="3.0" ` because of different GPU card.
 - Python version: 3.7
 - CUDA/cuDNN version: CUDA 9.2.148 cuDNN 7.4.6
 - GPU models and configuration: GeForce GT 730M

## Additional context

Already tried `git submodule sync; git submodule update --init --recursive` to update third party libraries and complete fresh checkout; nothing works, error unchanged. ~~Build of v1.3.0 worked absolutely fine on both machines with exactly same configuration and build command line.~~ (Edit: see next comment; v1.3.0 build now also fails)

**Comment by SteffenBauer** [comment]
Addendum: Just tried again to build v1.3.0, and this time it also fails with above error.
```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git checkout tags/v1.3.0
USE_CUDA=1 CFLAGS="-march=native" USE_CUDNN=1 USE_FBGEMM=0 BUILD_TEST=0 USE_MKLDNN=1 USE_NNPACK=0 USE_QNNPACK=0 USE_DISTRIBUTED=0 BUILD_CAFFE2_OPS=0 USE_OPENMP=1 TORCH_CUDA_ARCH_LIST="5.0" USE_NCCL=0 python3 ./setup.py bdist_wheel
```
As my build of v1.3.0 worked a few days ago, I suspect that something could have changed in one of the submodule third party libraries (as the error happens in `onnxifi_op.cc`, perhaps something in onnx?)

**Comment by soumith** [comment]
1.3.0's submodule hashes are frozen, and 1.3.1's submodules didn't change from 1.3.0. So I suspect something on your machine has changed.

**Comment by albanD** [comment]
@SteffenBauer don't you need to update submodules after checking out the tag?

**Comment by SteffenBauer** [comment]
@albanD: You were completely right, my fault. Doing all cleanly from scratch now it builds v1.3.1:
```
git checkout tags/v1.3.1
git submodule sync
git submodule update --init --recursive
<env variables...> python3 ./setup.py bdist_wheel
```
and it compiles now.
I checked out the submodules so far before the tag. Obviously it worked so far accidentally.

I close this now.
