### ISSUE TITLE
torch.nn.functional.cosine_similarity(x, y) result greater than 1.0, and x != y.

### ISSUE THREAD

**Issue by DogeWatch** [pytorch/pytorch#29442]
## 🐛 Bug

torch.nn.functional.cosine_similarity(x, y) result greater than 1.0, and x != y.

## To Reproduce

1. download [cosine_similarity.zip](https://github.com/pytorch/pytorch/files/3823279/cosine_similarity.zip)
2. python test.py

```
$ python test.py
cuda version:  10.0.130
torch version:  1.2.0
torch.Size([10, 64]) torch.Size([10, 64])
[ 0.85775983  1.          1.0000002   1.          0.9742242   0.6287892
 -0.6490739   0.24800973  0.6147525   0.7990689 ]
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [6,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print(loss(c,label))
  File "~/miniconda3/envs/mdecpp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "~/miniconda3/envs/mdecpp/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 498, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "~/miniconda3/envs/mdecpp/lib/python3.7/site-packages/torch/nn/functional.py", line 2051, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

## Environment
```
$ python collect_env.py                                                                
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration:
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl
[conda] faiss-cpu                 1.6.0            py37h6bb024c_0    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @walterddr @jerryzh168

**Comment by albanD** [comment]
Hi,

Thanks for the good repro !

I double checked and `c.max() - 1 == 1.1921e-07`.
So this definitely happens because of floating point imprecision. And the result is within floating point number precision. It is just infortunate that it is above 1.

Maybe we want to harden `cosine_similarity` to never return anything `> 1`.

**Comment by nikitaved** [comment]
Upon a closer look at the repro, we can see that the input to the `BCELoss` is just not correct as it has a negative value. Still the overshoot with `cosine_similarity` happens. Such that you know...

**Comment by nikitaved** [comment]
Closing as https://github.com/pytorch/pytorch/pull/31378 improves numerical properties of the loss.
