### ISSUE TITLE
TestFakeQuantizePerTensor. test_numerical_consistency_per_tensor is failing in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29462]
Build: pytorch_linux_xenial_cuda9_cudnn7_py2_test

```
Nov 08 17:34:44 test_numerical_consistency_per_tensor (__main__.TestFakeQuantizePerTensor)
Nov 08 17:34:45 Comparing numerical consistency between CPU quantize/dequantize op and the CPU fake quantize op ... FAIL
Nov 08 17:34:45 
Nov 08 17:34:45 ======================================================================
Nov 08 17:34:45 FAIL: test_numerical_consistency_per_tensor (__main__.TestFakeQuantizePerTensor)
Nov 08 17:34:45 Comparing numerical consistency between CPU quantize/dequantize op and the CPU fake quantize op
Nov 08 17:34:45 ----------------------------------------------------------------------
Nov 08 17:34:45 Traceback (most recent call last):
Nov 08 17:34:45   File "test_fake_quant.py", line 112, in test_numerical_consistency_per_tensor
Nov 08 17:34:45     @given(device=st.sampled_from(['cpu', 'cuda'] if torch.cuda.is_available() else ['cpu']),
Nov 08 17:34:45   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 960, in wrapped_test
Nov 08 17:34:45     state.run()
Nov 08 17:34:45   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 692, in run
Nov 08 17:34:45     info.__expected_traceback,
Nov 08 17:34:45   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/hypothesis/core.py", line 559, in execute

```

See: https://app.circleci.com/jobs/github/pytorch/pytorch/3529175.

Unfortunately it's not clear which PR is causing this failure since the failure chain was preceded by an intermittent dataloader failure (#27278).

@jamesr66a any ideas?

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by jerryzh168** [comment]
looks like`pytorch_linux_xenial_cuda9_cudnn7_py2_test` is removed by https://github.com/pytorch/pytorch/pull/29479, what's the plan ?

**Comment by mruberry** [comment]
We're removing Python2 support from PyTorch and have stopped testing some builds accordingly. If you think this issue is exclusively Python2-related then you can close it for now.

**Comment by jerryzh168** [comment]
looks like it is, closing
