### ISSUE TITLE
TestQuantizedOps. test_adaptive_avg_pool2d_nhwc is flaky in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29480]
build: pytorch-win-ws2016-cuda9-cudnn7-py3-test2
see: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/54601//console

```
20:40:24 ======================================================================
20:40:24 ERROR: test_adaptive_avg_pool2d_nhwc (__main__.TestQuantizedOps)
20:40:24 ----------------------------------------------------------------------
20:40:24 Traceback (most recent call last):
20:40:24   File "test_quantized.py", line 660, in test_adaptive_avg_pool2d_nhwc
20:40:24     min_side=1, max_side=10),
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 997, in wrapped_test
20:40:24     raise the_error_hypothesis_found
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 956, in wrapped_test
20:40:24     state.run()
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 692, in run
20:40:24     info.__expected_traceback,
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 559, in execute
20:40:24     result = self.test_runner(data, run)
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\executors.py", line 56, in default_new_style_executor
20:40:24     return function(data)
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 557, in run
20:40:24     return test(*args, **kwargs)
20:40:24   File "test_quantized.py", line 660, in test_adaptive_avg_pool2d_nhwc
20:40:24     min_side=1, max_side=10),
20:40:24   File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 535, in test
20:40:24     raise DeadlineExceeded(runtime, self.settings.deadline)
20:40:24 hypothesis.errors.DeadlineExceeded: Test took 250.00ms, which exceeds the deadline of 200.00ms
20:40:24 
20:40:24 ----------------------------------------------------------------------
20:40:24 Ran 34 tests in 71.188s
20:40:24 
20:40:24 FAILED (errors=1, skipped=7)
20:40:24 Falsifying example: test_adaptive_avg_pool2d_nhwc(self=<__main__.TestQuantizedOps testMethod=test_adaptive_avg_pool2d_nhwc>, X=(array([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],
20:40:24  
20:40:24  
20:40:24         [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
20:40:24           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]], dtype=float32),
20:40:24  (1.0, 0, torch.qint8)), output_size_h=10, output_size_w=10)
20:40:24 Traceback (most recent call last):
20:40:24   File "run_test.py", line 454, in <module>
20:40:24     main()
20:40:24   File "run_test.py", line 446, in main
20:40:24     raise RuntimeError(message)
20:40:24 RuntimeError: test_quantized failed!
```

@jamesr66a 

Saw this a couple times just recently on Master.

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by mruberry** [comment]
Happened again on pytorch_linux_xenial_cuda9_cudnn7_py3_NO_AVX2_test.
See: https://app.circleci.com/jobs/github/pytorch/pytorch/3544324

**Comment by mruberry** [comment]
Failures are now very frequent.

**Comment by lly-zero-one** [comment]
https://github.com/pytorch/pytorch/pull/29502
