### ISSUE TITLE
Internal NCCL Error when using mutiprocessdistributed mode

### ISSUE THREAD

**Issue by dzk9528** [pytorch/pytorch#29482]
## Environment

- GPU: Tesla T4(4 gpu for one node), also test on GTX 1080ti(4 gpu for one node)
- Pytorch: 1.3.0
- CUDA: 10
- Python3.7
- Ubuntu 16.04.6 LTS

## Docker command

```
nvidia-docker run -ti --rm --name ${DOCKER_NAME} \
                       --network=host \
                       --shm-size=16gb \
                       --ulimit memlock=-1 \
                       -p ${PORT}:${PORT} \
                       -e COLUMNS="tput cols" \
                       -e LINES="tput lines" \
                       -v /ssd:/ssd \
                       $DOCKER_ADDRESS \
                       bash
```

## NCCL Environmental Variables

- NCCL_SOCKET_IFNAME=eth0
- MASTER_ADDR is set as host server address
- MASTER_PORT is set as ${PORT}

## Bug info on node 0

```bash
gpu617:22841:22841 [0] bootstrap.cc:37 NCCL WARN Bootstrap : no socket interface found
gpu617:22841:22841 [0] NCCL INFO init.cc:128 -> 3
gpu617:22841:22841 [0] NCCL INFO bootstrap.cc:76 -> 3
gpu617:22841:22841 [0] NCCL INFO bootstrap.cc:245 -> 3
gpu617:22841:22841 [0] NCCL INFO bootstrap.cc:266 -> 3
Traceback (most recent call last):
  File "/workspace/pyface/engine/trainer.py", line 325, in <module>
    main(args)
  File "/workspace/pyface/engine/trainer.py", line 61, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/pyface/engine/trainer.py", line 125, in main_worker
    model = modeling.builder(args)
  File "/workspace/pyface/lib/modeling.py", line 37, in builder
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu], output_device=args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:374, internal error
```

### Bug info on node 1
```bash
Traceback (most recent call last):
  File "/workspace/pyface/engine/trainer.py", line 325, in <module>
    main(args)
  File "/workspace/pyface/engine/trainer.py", line 61, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/pyface/engine/trainer.py", line 125, in main_worker
    model = modeling.builder(args)
  File "/workspace/pyface/lib/modeling.py", line 37, in builder
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu], output_device=args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: Connection reset by peer
```

### Personal thoughts

1. It seems like in the `ProcessGroupNCCL.cpp`, the `ncclGetUniqueId(&ncclID)` return an internal error. 

2. when I try `watch 'lsof -i -P -n | grep LISTEN'`, this is the output

```bash
python  2251 root    5u  IPv4 118058800      0t0  TCP *:${PORT} (LISTEN)
```

But the output disappeared after `gpu617:22841:22841 [0] bootstrap.cc:37 NCCL WARN Bootstrap : no socket interface found` shows

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by dzk9528** [comment]
Find reason...wrong `NCCL_SOCKET_IFNAME=eth0`, should check `ifconfig` to find it.

**Comment by Hukongtao** [comment]
How did you resolve it?

**Comment by lyyi599** [comment]
> I met the same error as you. How did you resolve it?

you can type **ifconfig** in the console to find the socket name. Normally, it should start with **eno1** or **enp**. Best wish.
