### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by muddledluck** [pytorch/pytorch#29504]
Traceback (most recent call last):
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\Project\Preetika\preetika.py", line 8, in <module>
    engine = pyttsx3.init()
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
  File "C:\Users\saral\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os

**Comment by ngimel** [comment]
Can you please provide more information to reproduce the issue? Possibly a short script reproducing the error, along with the environment information collected via  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py script.

**Comment by muddledluck** [comment]
> Can you please provide more information to reproduce the issue? Possibly a short script reproducing the error, along with the environment information collected via https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py script.

![Screenshot (184)](https://user-images.githubusercontent.com/30544140/68614362-c1490a00-04e6-11ea-8af3-1f80b80c9a6a.png)

**Comment by ngimel** [comment]
Your error is coming from pyttsx3, it does not look like a pytorch issue at all.

**Comment by muddledluck** [comment]
> Your error is coming from pyttsx3, it does not look like a pytorch issue at all.

so what should I do ???

**Comment by ngimel** [comment]
File an issue with pyttsx3? Closing this one.

**Comment by muddledluck** [comment]
ok :)
