### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by tantingting1012** [pytorch/pytorch#29516]
model = model.to(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 426, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 424, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

**Comment by ngimel** [comment]
Can you please provide a reproduction script for your issue, along with information about your environment gathered by collect_env script? ( https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

**Comment by mhangaard** [comment]
I got a very similar traceback to this when testing my pytorch (after installing a bunch of .NET dependencies using apt).

My script:
```
import torch
import torch.nn as nn
import torch.optim as optim


class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = torch.nn.Linear(10, 10).to('cuda:0')
        self.relu = torch.nn.ReLU()
        self.net2 = torch.nn.Linear(10, 5).to('cuda:1')

    def forward(self, x):
        x = self.relu(self.net1(x.to('cuda:0')))
        return self.net2(x.to('cuda:1'))


model = ToyModel()
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

optimizer.zero_grad()
outputs = model(torch.randn(20, 10))
labels = torch.randn(20, 5).to('cuda:1')
loss_fn(outputs, labels).backward()
optimizer.step()
```

my environment running @ngimel's script:
```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 418.87.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] gpytorch==0.3.6
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] gpytorch                  0.3.6                         0    gpytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch
(torchenv) mh@mh-legion:~/tmp$
```

finally, nvidia-smi
```
$ nvidia-smi 
Mon Jan 20 12:36:41 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    On   | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P0    24W /  N/A |    901MiB /  6078MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1179      G   /usr/lib/xorg/Xorg                            36MiB |
|    0      1332      G   /usr/bin/gnome-shell                          48MiB |
|    0      2555      G   /usr/lib/xorg/Xorg                           290MiB |
|    0      2768      G   /usr/bin/gnome-shell                         325MiB |
|    0      3142      G   ...uest-channel-token=11631031364635802205    58MiB |
|    0     18070      G   ...uest-channel-token=15583915017394039797    54MiB |
|    0     18115      G   ...uest-channel-token=13519740334469980282    83MiB |
+-----------------------------------------------------------------------------+
```

**Comment by fuuman** [comment]
I also call `model.to(device)`.

Traceback: 
```
Traceback (most recent call last):
  File "bert_att_weight_retrieval.py", line 381, in <module>
    main()
  File "bert_att_weight_retrieval.py", line 244, in main
    model.to(device)
  File "/run/media/marco/Daten/GitHub/feature-importance/venv36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/run/media/marco/Daten/GitHub/feature-importance/venv36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/run/media/marco/Daten/GitHub/feature-importance/venv36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/run/media/marco/Daten/GitHub/feature-importance/venv36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/run/media/marco/Daten/GitHub/feature-importance/venv36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/run/media/marco/Daten/GitHub/feature-importance/venv36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
```
Output of the `collect_env.py` script: 
```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Manjaro Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1660
Nvidia driver version: 440.82
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.17.1
[pip3] torch==1.0.1.post2
[conda] Could not collect
```
Output of `nvidia-smi`:
```
Wed May 27 13:22:05 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1660    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P8     9W / 120W |    413MiB /  5936MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       750      G   /usr/lib/Xorg                                275MiB |
|    0      2536      G   ...RubyMine/ch-0/201.6668.156/jbr/bin/java     3MiB |
|    0      5829      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   125MiB |
|    0     23410      G   ...yCharm-P/ch-0/201.6668.115/jbr/bin/java     3MiB |
+-----------------------------------------------------------------------------+

```

**Comment by sum-coderepo** [comment]
Did you resolve the issue?
