### ISSUE TITLE
TestQuantizedOps .test_max_pool2d is flaky in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29540]
build: py3.6-clang7-rocmdeb-ubuntu16.04-test2
link: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/6227//console

```
00:23:09 test_qtopk_nhwc (__main__.TestQuantizedOps) ... test_quantized.py:755: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
00:23:11   indices = torch.tensor(torch.from_numpy(X)).long()
00:23:11 ok
00:23:11 
00:23:11 ======================================================================
00:23:11 ERROR: test_max_pool2d (__main__.TestQuantizedOps)
00:23:11 ----------------------------------------------------------------------
00:23:11 Traceback (most recent call last):
00:23:11   File "test_quantized.py", line 403, in test_max_pool2d
00:23:11     min_side=1, max_side=10),
00:23:11   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 1005, in wrapped_test
00:23:11     raise the_error_hypothesis_found
00:23:11   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 964, in wrapped_test
00:23:11     state.run()
00:23:11   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 696, in run
00:23:11     info.__expected_traceback,
00:23:11   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 592, in execute
00:23:11     % (test.__name__, text_repr[0])
00:23:11   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 751, in __flaky
00:23:11     raise Flaky(message)
00:23:11 hypothesis.errors.Flaky: Hypothesis test_max_pool2d(self=<__main__.TestQuantizedOps testMethod=test_max_pool2d>, X=(array([[[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]]],
00:23:11        dtype=float32), (1.0, 0, torch.quint8)), kernel=5, stride=None, dilation=1, padding=1, ceil_mode=False) produces unreliable results: Falsified on the first call but did not on a subsequent one
00:23:11 
00:23:11 ----------------------------------------------------------------------
00:23:11 Ran 34 tests in 32.503s
00:23:11 
00:23:11 FAILED (errors=1, skipped=1)
00:23:11 Falsifying example: test_max_pool2d(self=<__main__.TestQuantizedOps testMethod=test_max_pool2d>, X=(array([[[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]],
00:23:11  
00:23:11         [[250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.],
00:23:11          [250., 250., 250., 250., 250., 250., 250., 250., 250., 250.]]],
00:23:11        dtype=float32), (1.0, 0, torch.quint8)), kernel=5, stride=None, dilation=1, padding=1, ceil_mode=False)
00:23:11 Unreliable test timings! On an initial run, this test took 255.72ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 1.28 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.
00:23:11 Traceback (most recent call last):
00:23:11   File "test/run_test.py", line 454, in <module>
00:23:11     main()
00:23:11   File "test/run_test.py", line 446, in main
00:23:11     raise RuntimeError(message)
00:23:11 RuntimeError: test_quantized failed!
```

@jamesr66a 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by jamesr66a** [comment]
Something is blowing out the runtime for these ops on the first iteration but not subsequent ones. Does this only happen on ROCm?

**Comment by mruberry** [comment]
Unclear. This particular issue has only been seen on ROCm so far.

**Comment by gottbrath** [comment]
Based on Mike Ruberry's comment that "This particular issue has only been seen on ROCm so far." I added the module: rocm label and creating an issue in the AMD Jira system https://ontrack.amd.com/browse/FBA-145

**Comment by jerryzh168** [comment]
we don't have cuda kernels for quantized ops right now, this is probably doesn't have anything to do with rocm. can we just add @no_deadline? @jamesr66a

**Comment by gottbrath** [comment]
ok .. i added a comment in Jira that this one might be a red herring and gave it a lower priority.

**Comment by jeffdaily** [comment]
Corresponding JIRA has been closed.  Test is part of slow test category of CI.  Was unable to reproduce locally.
