### ISSUE TITLE
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type NoneType

### ISSUE THREAD

**Issue by echan00** [pytorch/pytorch#29551]
## 🐛 Bug

I am receiving this error on pytorch model export to onnx:
`RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type NoneType`

The error says that tuples are supported but got unsupported type NoneType. I checked the type of the variable `out` and it is a tuple at the error `out_vars, _ = _flatten(out)`

## Code To Reproduce (download [save_entire_model](https://www.dropbox.com/s/qkeeuafeij1vhdu/save_entire_model?dl=0))
```
import onnx
import torch

model = torch.load('save_entire_model')
text_input = torch.randint(low=0, high=5000, size=(10, 10))    
input_names = ['inputs']
output_names = ['predictions']
dummy_inputs = (text_input, text_input, text_input, text_input)
torch.onnx.export(model, args=dummy_inputs, input_names=input_names,
                      output_names=output_names, f='some_file')
```

Stack trace:
```
Traceback (most recent call last):
  File "pytorch_to_tf_serving.py", line 192, in <module>
    main(args)
  File "pytorch_to_tf_serving.py", line 171, in main
    num_inputs=len(dummy_inputs))
  File "pytorch_to_tf_serving.py", line 59, in export_onnx
    output_names=output_names, f=file)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 355, in forward
    out_vars, _ = _flatten(out)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type NoneType
```

## Environment

Torch (tried both version:  1.3.0 and 1.3.1)
Onnx Version: 1.6.0
Python 3.7

cc @suo

**Comment by echan00** [comment]
Printing out at `out_vars, _ = _flatten(out)` for reference

```
print(out)

(tensor([[[-4.1578, -4.1578, -1.8524,  ..., -4.1594, -4.1578, -4.1578]]],
       grad_fn=<UnsafeViewBackward>), {'attn': None, 'inner_states': [tensor([[[ 6.5853e-01,  1.9622e+00,  5.2403e-01,  1.3518e+00,  9.9456e-01,
           8.0950e-01,  8.5349e-01,  9.1109e-01,  6.9116e-01,  1.0574e+00,
           1.1588e+00,  1.2319e+00,  7.6108e-01,  8.5800e-01,  1.0273e+00,
           ...
           3.0374e-01, -3.2607e-01,  3.6841e-01,  1.0497e+00, -2.5193e-02,
          -1.2096e+00,  1.8086e+00,  1.2666e+00, -3.6409e-01, -1.6221e-01,
           4.1684e-01,  2.2308e-01]]], grad_fn=<TransposeBackward0>), tensor([[[ 0.7815,  1.4128,  1.9144,  1.8692,  1.7535,  1.0596,  1.0799,
           0.5365,  0.0243,  0.7807, -0.3897,  0.7187,  0.0199, -0.0509,
           1.5221,  0.4457,  0.5508,  0.1087, -0.3167, -0.4753, -0.7531,
          -1.0527, -0.3692, -2.0728,  0.1707,  0.9737,  0.4161, -0.9744,
           0.5162, -0.4486,  0.6815,  0.6126,  0.1605,  0.5801,  0.0412,
           ...
           0.6921,  0.0800,  0.0286, -0.6501,  0.5827,  0.6020,  0.5745,
           0.3589, -1.1048,  0.6465,  0.2867,  0.0266,  1.4155, -0.0256,
          -0.7655, -0.4462,  0.0533,  0.6699,  0.0787, -0.8774,  0.3115,
           0.3766, -0.0529, -0.4690, -1.1208,  0.6119, -0.9409, -0.1704,
           0.7990]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.9257e-01,  5.7292e-01,  1.9897e+00,  8.0829e-01,  1.5144e+00,
          -7.2408e-02,  1.5286e+00,  2.5415e-01, -2.6596e-01,  6.2154e-01,
          -4.0602e-02,  2.9882e-01, -3.7910e-01,  3.8766e-01,  6.7494e-01,
           4.4782e-01,  1.7771e-01,  5.8628e-01, -3.1065e-01, -5.8914e-01,
          ...
          -4.1657e-01, -7.0362e-01,  7.6075e-01, -5.7479e-02,  4.2632e-02,
           1.6327e+00,  1.7667e-01, -5.0550e-01, -5.8816e-02, -1.6673e-03,
           1.1482e+00, -2.9425e-01, -1.9979e-01,  4.6860e-02,  1.3203e-01,
          -5.2750e-02, -4.8923e-01, -2.8561e-01,  6.3911e-01, -5.4759e-01,
          -8.0562e-01,  5.4077e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-3.6923e-01,  1.1787e-01,  6.8096e-01, -1.1662e-01,  7.9530e-01,
           7.5198e-02,  1.3509e+00, -1.9241e-01,  4.2809e-01,  8.5573e-01,
           8.1631e-02, -2.5475e-01, -2.5125e-01, -4.8125e-01,  8.8949e-02,
           ...
          -4.2894e-01, -1.1260e+00,  1.3172e-01,  5.3614e-02,  3.8973e-01,
           1.7613e+00,  4.3753e-01, -8.9063e-01,  1.0734e-01, -2.4127e-01,
           1.3317e+00,  2.4966e-01,  2.4230e-02,  2.0564e-01, -3.2092e-01,
          -4.5192e-01,  3.3854e-01, -9.5419e-02,  9.0669e-01, -1.0363e-01,
          -2.2488e-01,  5.9252e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.9980e-01, -8.8662e-02,  5.5508e-01, -3.7160e-01,  5.1152e-01,
          -1.4307e-01,  6.6887e-01, -5.6462e-01,  3.1639e-01,  4.0311e-01,
          -8.1127e-02, -1.2407e-01,  1.6268e-02, -4.6536e-01,  3.3411e-03,
          -1.9008e-01, -4.9672e-01,  1.2119e-01,  2.1825e-01, -8.8838e-02,
          ...
          -2.8393e-01, -8.2706e-01,  2.5620e-01,  2.3472e-01,  7.5266e-01,
           1.7218e+00,  6.2751e-01, -9.3120e-01, -1.8472e-01, -6.3412e-01,
           1.2557e+00,  4.0351e-01, -4.1754e-01,  2.5825e-01, -3.8045e-01,
          -4.9765e-01, -4.4675e-03, -4.8094e-02,  7.2632e-01, -8.7025e-02,
          -8.7379e-02, -1.2132e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.0780e-01,  5.5197e-02,  5.9898e-01, -3.9491e-01,  4.2754e-01,
          -1.5410e-01,  1.9608e-01, -1.9214e-01,  1.4762e-01,  2.1785e-02,
          -5.0449e-02, -8.8102e-02, -1.3401e-02, -3.3706e-01, -2.6365e-01,
          -1.9809e-01, -7.9834e-01,  1.4816e-01, -2.2289e-01, -4.0357e-01,
           8.2309e-01, -1.2184e-02, -2.5760e-01, -1.1096e+00,  2.4079e-01,
           4.6590e-01,  2.7868e-02, -8.2683e-02,  2.9244e-01, -1.1489e+00,
          -1.2771e+00, -2.1309e-01,  8.9728e-01, -4.2586e-02,  9.6222e-02,
          -4.7323e-01, -8.3574e-01,  1.0025e-01,  9.3586e-01, -3.3361e-02,
           2.4802e-01, -6.1986e-02,  5.9020e-01, -9.1314e-02,  8.7482e-01,
          -1.0048e+00,  5.5580e-01,  5.8401e-01, -5.5002e-02, -9.5364e-02,
          -7.5579e-01, -4.3763e-01, -2.7567e-01, -8.7940e-02, -1.9796e+00,
          -4.9066e-01, -1.0722e-01,  4.9114e-02,  3.2016e-01, -1.4293e-01,
           1.0401e+00,  5.0015e-01,  3.3204e-01, -1.0009e+00, -1.3682e-01,
           ...
           1.7445e+00,  5.5370e-01, -9.2174e-01, -7.8583e-03, -6.1203e-01,
           1.7788e+00,  1.4459e-01, -5.9285e-01,  8.9575e-02, -6.8424e-01,
          -6.6729e-01,  1.9540e-01,  1.2908e-01,  5.0190e-01, -2.8455e-01,
           1.1437e-01,  1.6649e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.0390e+00, -3.8058e-01,  1.1982e+00,  1.0307e+00,  2.2017e+00,
          -7.2041e-01, -6.5582e-01, -6.0439e-01,  2.6163e+00,  2.6794e+00,
          -3.9632e-01,  8.4476e-01, -4.9725e-02, -3.3735e-01, -7.3748e-01,
           1.3937e-01, -3.2264e+00,  1.7292e+00, -1.9069e+00, -1.1043e+00,
           1.3631e+00, -1.0812e+00,  9.8197e-01, -9.3629e-01,  9.0489e-01,
           ...
           7.1485e+00,  1.7797e+00, -4.3819e+00,  7.5024e-01, -2.7905e+00,
           6.3797e+00,  2.4715e-01, -3.0974e+00,  1.6144e-01, -4.0366e+00,
          -9.4790e-01, -5.1752e-01,  6.3931e-01,  7.7930e-01, -1.0142e+00,
           1.9082e-01, -2.0802e+00]]], grad_fn=<NativeLayerNormBackward>)]})(tensor([[[-4.1578, -4.1578, -1.8524,  ..., -4.1594, -4.1578, -4.1578]]],
       grad_fn=<UnsafeViewBackward>), {'attn': None, 'inner_states': [tensor([[[ 6.5853e-01,  1.9622e+00,  5.2403e-01,  1.3518e+00,  9.9456e-01,
           8.0950e-01,  8.5349e-01,  9.1109e-01,  6.9116e-01,  1.0574e+00,
           1.1588e+00,  1.2319e+00,  7.6108e-01,  8.5800e-01,  1.0273e+00,
           8.8919e-01,  4.4198e-01,  9.5432e-01,  8.6082e-01,  6.3129e-01,
           ...
          -2.2889e-01, -1.3020e+00,  2.6334e-01, -5.1085e-01,  5.7180e-01,
          -4.7181e-01, -3.0248e-01,  1.1660e+00, -1.3143e+00, -2.4814e-01,
           3.8736e-01,  7.4091e-01, -8.4835e-01,  8.4147e-02, -6.0665e-01,
           3.0374e-01, -3.2607e-01,  3.6841e-01,  1.0497e+00, -2.5193e-02,
          -1.2096e+00,  1.8086e+00,  1.2666e+00, -3.6409e-01, -1.6221e-01,
           4.1684e-01,  2.2308e-01]]], grad_fn=<TransposeBackward0>), tensor([[[ 0.7815,  1.4128,  1.9144,  1.8692,  1.7535,  1.0596,  1.0799,
           0.5365,  0.0243,  0.7807, -0.3897,  0.7187,  0.0199, -0.0509,
           1.5221,  0.4457,  0.5508,  0.1087, -0.3167, -0.4753, -0.7531,
          -1.0527, -0.3692, -2.0728,  0.1707,  0.9737,  0.4161, -0.9744,
          ...
           0.6921,  0.0800,  0.0286, -0.6501,  0.5827,  0.6020,  0.5745,
           0.3589, -1.1048,  0.6465,  0.2867,  0.0266,  1.4155, -0.0256,
          -0.7655, -0.4462,  0.0533,  0.6699,  0.0787, -0.8774,  0.3115,
           0.3766, -0.0529, -0.4690, -1.1208,  0.6119, -0.9409, -0.1704,
           0.7990]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.9257e-01,  5.7292e-01,  1.9897e+00,  8.0829e-01,  1.5144e+00,
          -7.2408e-02,  1.5286e+00,  2.5415e-01, -2.6596e-01,  6.2154e-01,
          -4.0602e-02,  2.9882e-01, -3.7910e-01,  3.8766e-01,  6.7494e-01,
          ...
           1.1482e+00, -2.9425e-01, -1.9979e-01,  4.6860e-02,  1.3203e-01,
          -5.2750e-02, -4.8923e-01, -2.8561e-01,  6.3911e-01, -5.4759e-01,
          -8.0562e-01,  5.4077e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-3.6923e-01,  1.1787e-01,  6.8096e-01, -1.1662e-01,  7.9530e-01,
           7.5198e-02,  1.3509e+00, -1.9241e-01,  4.2809e-01,  8.5573e-01,
           8.1631e-02, -2.5475e-01, -2.5125e-01, -4.8125e-01,  8.8949e-02,
           2.1274e-01, -5.7217e-01,  5.1387e-01,  5.2827e-02, -4.0502e-01,
           ...
          -4.2894e-01, -1.1260e+00,  1.3172e-01,  5.3614e-02,  3.8973e-01,
           1.7613e+00,  4.3753e-01, -8.9063e-01,  1.0734e-01, -2.4127e-01,
           1.3317e+00,  2.4966e-01,  2.4230e-02,  2.0564e-01, -3.2092e-01,
          -4.5192e-01,  3.3854e-01, -9.5419e-02,  9.0669e-01, -1.0363e-01,
          -2.2488e-01,  5.9252e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.9980e-01, -8.8662e-02,  5.5508e-01, -3.7160e-01,  5.1152e-01,
          -1.4307e-01,  6.6887e-01, -5.6462e-01,  3.1639e-01,  4.0311e-01,
          -8.1127e-02, -1.2407e-01,  1.6268e-02, -4.6536e-01,  3.3411e-03,
          -1.9008e-01, -4.9672e-01,  1.2119e-01,  2.1825e-01, -8.8838e-02,
          ...
          -2.8393e-01, -8.2706e-01,  2.5620e-01,  2.3472e-01,  7.5266e-01,
           1.7218e+00,  6.2751e-01, -9.3120e-01, -1.8472e-01, -6.3412e-01,
           1.2557e+00,  4.0351e-01, -4.1754e-01,  2.5825e-01, -3.8045e-01,
          -4.9765e-01, -4.4675e-03, -4.8094e-02,  7.2632e-01, -8.7025e-02,
          -8.7379e-02, -1.2132e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.0780e-01,  5.5197e-02,  5.9898e-01, -3.9491e-01,  4.2754e-01,
          -1.5410e-01,  1.9608e-01, -1.9214e-01,  1.4762e-01,  2.1785e-02,
          -5.0449e-02, -8.8102e-02, -1.3401e-02, -3.3706e-01, -2.6365e-01,
          -1.9809e-01, -7.9834e-01,  1.4816e-01, -2.2289e-01, -4.0357e-01,
          ...
          -1.2083e+00, -1.5162e+00,  3.8445e-01,  5.3880e-01,  1.8609e+00,
          -2.0355e-01, -8.1770e-01,  7.2046e-01,  1.2444e-01,  6.4893e-01,
           1.7445e+00,  5.5370e-01, -9.2174e-01, -7.8583e-03, -6.1203e-01,
           1.7788e+00,  1.4459e-01, -5.9285e-01,  8.9575e-02, -6.8424e-01,
          -6.6729e-01,  1.9540e-01,  1.2908e-01,  5.0190e-01, -2.8455e-01,
           1.1437e-01,  1.6649e-01]]], grad_fn=<NativeLayerNormBackward>), tensor([[[-1.0390e+00, -3.8058e-01,  1.1982e+00,  1.0307e+00,  2.2017e+00,
          -7.2041e-01, -6.5582e-01, -6.0439e-01,  2.6163e+00,  2.6794e+00,
          -3.9632e-01,  8.4476e-01, -4.9725e-02, -3.3735e-01, -7.3748e-01,
           1.3937e-01, -3.2264e+00,  1.7292e+00, -1.9069e+00, -1.1043e+00,
           ...
           7.1485e+00,  1.7797e+00, -4.3819e+00,  7.5024e-01, -2.7905e+00,
           6.3797e+00,  2.4715e-01, -3.0974e+00,  1.6144e-01, -4.0366e+00,
          -9.4790e-01, -5.1752e-01,  6.3931e-01,  7.7930e-01, -1.0142e+00,
           1.9082e-01, -2.0802e+00]]], grad_fn=<NativeLayerNormBackward>)]})
```

**Comment by echan00** [comment]
Thought this might be useful information. The error for torch 1.3 and 1.3.1 is:

`RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type NoneType`

But torch 1.2, 1.1, 1.0 is:

`RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict`

**Comment by ShawnNew** [comment]
You can wrap the multi-input needs to pass to the network to a dictionary. Note that you should also un-wrap the input to whatever you want in your forward function.

**Comment by echan00** [comment]
Thanks @ShawnNew , do you mind being more specific about your suggestion? I am new to pytorch and still figuring out how it works.

What do you mean by "wrap the multi-input"? And where should that happen?

**Comment by pynsigrid** [comment]
Maybe you could check your `model.forward()` for some clues.
I have encountered the same problem before, but now I have found a solution. My `forward()` function of image-to-image model is like: 
`def forward(self, images_a, images_b):
        raise NotImplementedError`
So there will return a `Nonetype` when `model.eval()`.
Additionally, you can print out at `out_vars, _ = _flatten(out)` to track changes in your input data.

**Comment by shubhambhokare1** [comment]
@echan00 The difference in error statements for versions 1.3+ is due to the fact that dictionary support was added in 1.3

The support for NoneType arguments was added in #45792

**Comment by spandantiwari** [comment]
Closing now. Please reopen if the issue persists.
