### ISSUE TITLE
[jit][script] No flow-sensitive typing for torchscript class elements

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#29573]
## 🐛 Bug

`torch.jit.script` has flow-sensitive typing (allowing `assert`s and `if` statements to dynamically change the types of variables), but this does not work for torchscript class elements or named tuples.

## To Reproduce

Running the following script:

```python
from typing import NamedTuple, Optional
import torch.nn as nn
import torch

class S(NamedTuple):
    s: Optional[int]

class B(nn.Module):
    def forward(self):
        return S(None)

class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.mod = B()
        self.x = torch.zeros(20)
    def forward(self):
        s = self.mod.forward()
        if s.s is None:
            return self.x[0]
        else:
            assert s.s is not None
            return self.x[s.s]

torch.jit.script(A())
```

fails with

```
Traceback (most recent call last):
  File "a.py", line 25, in <module>
    torch.jit.script(A())
  File "/home/alan/workspace/pytorch/pytorch/torch/jit/__init__.py", line 1243, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/home/alan/workspace/pytorch/pytorch/torch/jit/_recursive.py", line 539, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/alan/workspace/pytorch/pytorch/torch/jit/_recursive.py", line 319, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/home/alan/workspace/pytorch/pytorch/torch/jit/_recursive.py", line 367, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/home/alan/workspace/pytorch/pytorch/torch/jit/_recursive.py", line 279, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 
Unsupported operation: indexing tensor with unsupported index type 'Optional[int]'. Only ints, slices, and tensors are supported:
at a.py:23:19
        else:
            assert s.s is not None
            return self.x[s.s]
                   ~~~~~~~~~~ <--- HERE
```

In our code, this leads to awkward workarounds like:
```python
start = 0 if s.start is None else s.start                                
assert start is not None  # why is this necessary?
```

## Expected behavior

Ideally, flow-sensitive typing would work with fields variables. Notably, this already works if you don't put these variables with containers (i.e. you work with "raw" `Optional[int]`s).

## Environment

```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.0
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0               py3.6_cpu_0  [cpuonly]  pytorch
```

cc @suo

**Comment by eellison** [comment]
This is a documented limitation in https://pytorch.org/docs/stable/jit.html#optional-type-refinement. Closing this issue since it's a dup of https://github.com/pytorch/pytorch/issues/22155.
