### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by ray342649093** [pytorch/pytorch#2964]
I just run some training code and this error raised occasionally. Is there any idea to fix this issue?

THCudaCheck FAIL file=/pytorch/torch/lib/THC/THCTensorCopy.cu line=190 error=4 : unspecified launch failure
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 166, in train
    output = model(input_var)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    return self.gather(outputs, self.output_device)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 73, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 50, in gather
    return gather_map(outputs)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 46, in gather_map
    return Gather(target_device, dim=dim)(*outputs)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 39, in forward
    return comm.gather(inputs, self.dim, self.target_device)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/cuda/comm.py", line 204, in gather
    result.narrow(dim, chunk_start, tensor.size(dim)).copy_(tensor, True)
RuntimeError: cuda runtime error (4) : unspecified launch failure at /pytorch/torch/lib/THC/THCTensorCopy.cu:190
terminate called without an active exception
Aborted (core dumped)

**Comment by apaszke** [comment]
Can you please post the input sizes you used when you got this error?

**Comment by ray342659093** [comment]
the input size was like (8,9,224,224)

**Comment by apaszke** [comment]
input to what? from the stack trace it seems that you were running some kind of model, and I need to know the input size at the time when `.copy_` was called (line 204 in gather.py)

**Comment by ray342659093** [comment]
I was running resnet101, and the input size is (8,9,224,224), it is a batch with size of 8 and each sample is a stack of 3 224x224 images

**Comment by apaszke** [comment]
did you use the imagenet example? with how many GPUs?

**Comment by apaszke** [comment]
actually, you can't run a regular resnet101 with 9 input channels, so you must have modified something

**Comment by ray342659093** [comment]
I am sorry, I forgot that I did reshape the input by using view(-1,3,224,224), so the input size should be (8*3,3,224,224). I used 3 frames from each video in ucf101 as training sample just like Temporal Segment Network like this https://github.com/yjxiong/tsn-pytorch. I used four 1080Ti gpus to train this model.

**Comment by jimmykobe** [comment]
I got the same problem

**Comment by xllau** [comment]
Have anyone solved this problem?

**Comment by Garethlomax** [comment]
Any update on this?

**Comment by zhangguanheng66** [comment]
@Garethlomax Can you post your script to reproduce the error?
