### ISSUE TITLE
test_insert_quant_dequant JIT test is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#29693]
## 🐛 Bug

JIT test `test_insert_quant_dequant` seems to be flaky:
```
Nov 12 00:58:42 ERROR: test_insert_quant_dequant (test_jit.TestJit)
Nov 12 00:58:42 ----------------------------------------------------------------------
Nov 12 00:58:42 Traceback (most recent call last):
Nov 12 00:58:42   File "/var/lib/jenkins/workspace/test/jit_utils.py", line 578, in wrapper
Nov 12 00:58:42     fn(*args, **kwargs)
Nov 12 00:58:42   File "/var/lib/jenkins/workspace/test/test_jit.py", line 1120, in test_insert_quant_dequant
Nov 12 00:58:42     assert len(m._c._get_modules()) == 1, \
Nov 12 00:58:42 AttributeError: 'torch._C.ScriptModule' object has no attribute '_get_modules'
```

Some failure examples:
 https://app.circleci.com/jobs/github/pytorch/pytorch/3565293, https://app.circleci.com/jobs/github/pytorch/pytorch/3565292

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by jerryzh168** [comment]
this should be fixed now, could you pull the master?

**Comment by ezyang** [comment]
@jerryzh168 where as this fixed? If you link to a PR feel free to close this

**Comment by jerryzh168** [comment]
this is fixed I think
