### ISSUE TITLE
test_async_parsing (jit.test_async.TestAsync) segfaults non-deterministically

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#29764]
https://app.circleci.com/jobs/github/pytorch/pytorch/3582889
https://app.circleci.com/jobs/github/pytorch/pytorch/3584169

```
Nov 13 16:15:54 OK
Nov 13 16:15:54 Running test_jit ... [2019-11-13 16:15:54.945027]
Nov 13 16:15:56 test_async_grad_guard_no_grad (jit.test_async.TestAsync) ... ok
Nov 13 16:15:56 test_async_grad_guard_with_grad (jit.test_async.TestAsync) ... ok
Nov 13 16:15:56 test_async_parsing (jit.test_async.TestAsync) ... Traceback (most recent call last):
Nov 13 16:15:56   File "test/run_test.py", line 453, in <module>
Nov 13 16:15:56     main()
Nov 13 16:15:56   File "test/run_test.py", line 446, in main
Nov 13 16:15:56     raise RuntimeError(message)
Nov 13 16:15:56 RuntimeError: test_jit failed! Received signal: SIGSEGV
Nov 13 16:15:56 =================== sccache compilation log ===================
Nov 13 16:15:56 + cleanup
Nov 13 16:15:56 + retcode=1
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by zdevito** [comment]
https://app.circleci.com/jobs/github/pytorch/pytorch/3589357

**Comment by ezyang** [comment]
This has affected me too

**Comment by mruberry** [comment]
I think we need to make our triage guidance stricter and immediately start skipping these flaky tests. Someone on the JIT team should skip this test ASAP.

**Comment by zdevito** [comment]
@driazati can you disable this test? I believe you are the JIT oncall at the moment.

**Comment by mruberry** [comment]
See also: 

https://github.com/pytorch/pytorch/issues/29842

Maybe disable both while you're in there?

**Comment by driazati** [comment]
for posterity a backtrace gives but I'm still looking into it

```
0       torch::jit::InterpreterStateImpl::runImpl       ../torch/csrc/jit/interpreter.cpp:850
1       torch::jit::InterpreterStateImpl::runAsync      ../torch/csrc/jit/interpreter.cpp:1085
2       torch::jit::InterpreterState::runAsync          ../torch/csrc/jit/interpreter.cpp:1152
3       torch::jit::InterpreterContinuation::operator() ../torch/csrc/jit/interpreter.cpp:1165
4       std::_Function_handler::_M_invoke               <c++ std library>
5       std::function::operator()() const               <c++ std library>
6       at::::operator() const                          ../aten/src/ATen/ParallelThreadPoolNative.cpp:74
7       std::__invoke_impl                              <c++ std library>
8       std::__invoke                                   <c++ std library>
9       std::_Bind::__call                              <c++ std library>
10      std::_Bind::operator()<>                        <c++ std library>
11      std::_Function_handler::_M_invoke               <c++ std library>
12      std::function::operator()() const               <c++ std library>
13      c10::ThreadPool::main_loop                      ../c10/core/thread_pool.cpp:109
14      c10::ThreadPool::::operator() const             ../c10/core/thread_pool.cpp:20
15      std::__invoke_impl                              <c++ std library>
16      std::__invoke                                   <c++ std library>
17      std::thread::_Invoker::_M_invoke                <c++ std library>
18      std::thread::_Invoker::operator()               <c++ std library>
19      std::thread::_State_impl::_M_run                <c++ std library>
20      std::execute_native_thread_routine              <c++ std library>
21      start_thread                                    pthread_create.c:479
22      clone                                           ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by driazati** [comment]
@Krovatkin after some investigation this looks like an interpreter bug, do you mind taking a look?

**Comment by zdevito** [comment]
I was able to repro locally, and put up the PR above that fixes it. The test-disabling PR hasn't landed yet, so this fix PR cannot revert the test disable.
