### ISSUE TITLE
New ROCM Flakiness

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#29760]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/6888//console

```
test_send_recv_with_tag (__main__.TestDistBackend) ... skipped 'Nccl does not support send/recv'
22:08:46 
22:08:46 ======================================================================
22:08:46 FAIL: test_DistributedDataParallel (__main__.TestDistBackend)
22:08:46 ----------------------------------------------------------------------
22:08:46 Traceback (most recent call last):
22:08:46   File "test_distributed.py", line 1986, in wrapper
22:08:46     self._join_and_reduce(fn)
22:08:46   File "test_distributed.py", line 2096, in _join_and_reduce
22:08:46     first_process.exitcode == SKIP_IF_ROCM_EXIT_CODE
22:08:46 AssertionError
22:08:46 
22:08:46 ----------------------------------------------------------------------
22:08:46 Ran 91 tests in 445.031s
22:08:46 
22:08:46 FAILED (failures=1, skipped=75)
22:08:46 Traceback (most recent call last):
22:08:46   File "test/run_test.py", line 453, in <module>
22:08:46     main()
22:08:46   File "test/run_test.py", line 446, in main
22:08:46     raise RuntimeError(message)
22:08:46 RuntimeError: test_distributed failed!
22:08:46 + cleanup
22:08:46 + retcode=1
22:08:46 + set +x
22:08:46 =================== sccache compilation log ===================
```

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by zdevito** [comment]
Maybe addressed in https://github.com/pytorch/pytorch/pull/29736

**Comment by rohan-varma** [comment]
I think the underlying error is this portion of the stack trace?

```
22:02:28   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
22:02:28     self.run()
22:02:28   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
22:02:28     self._target(*self._args, **self._kwargs)
22:02:28   File "test_distributed.py", line 2062, in _run
22:02:28     getattr(self, self.id().split(".")[2])()
22:02:28   File "test_distributed.py", line 1988, in wrapper
22:02:28     fn(self)
22:02:28   File "test_distributed.py", line 118, in wrapper
22:02:28     return func(*args, **kwargs)
22:02:28   File "test_distributed.py", line 134, in wrapper
22:02:28     return func(*args, **kwargs)
22:02:28   File "test_distributed.py", line 1862, in test_DistributedDataParallel
22:02:28     self._test_DistributedDataParallel(gpu_subset=gpus, rank=rank)
22:02:28   File "test_distributed.py", line 1797, in _test_DistributedDataParallel
22:02:28     model_DDP, device_ids=gpu_subset
22:02:28   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 305, in __init__
22:02:28     self._ddp_init_helper()
22:02:28   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 323, in _ddp_init_helper
22:02:28     self._module_copies = replicate(self.module, self.device_ids, detach=True)
22:02:28   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 146, in replicate
22:02:28     setattr(replica, key, Parameter(param))
22:02:28   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/nn/parameter.py", line 26, in __new__
22:02:28     return torch.Tensor._make_subclass(cls, data, requires_grad)
22:02:28 RuntimeError: Only Tensors of floating point dtype can require gradients
```

**Comment by gottbrath** [comment]
Is this unique to the ROCm systems? Should we add a label "module:rocm" to this?

**Comment by gottbrath** [comment]
https://ontrack.amd.com/browse/FBA-153

**Comment by jithunnair-amd** [comment]
The failures with test_DistributedDataParallel were not a result of flakiness, but some very specific conditions as detailed in https://github.com/pytorch/pytorch/issues/32018.

**Comment by jithunnair-amd** [comment]
@zdevito The fix for the test_DistributedDataParallel test has been merged into upstream in #32356. Since this is the only mentioned in this issue, can we close this issue?

**Comment by jithunnair-amd** [comment]
@gottbrath ^^

**Comment by mruberry** [comment]
Closing per @jithunnair-amd.
