### ISSUE TITLE
SGD fails on sparse matrix

### ISSUE THREAD

**Issue by antonior92** [pytorch/pytorch#29814]
## 🐛 Bug

One SGD step for optimizing a model with a sparse parameter matrix gives me a RuntimeError

## To Reproduce

```
import torch
from torch import nn

class TrainNet(nn.Module):
    def __init__(self, in_features, out_features):
        super(TrainNet, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = torch.nn.Parameter(torch.randn(out_features, in_features).to_sparse().requires_grad_(True))


    def forward(self, input):
        x = torch.sparse.mm(self.weight, input)
        return x


model = TrainNet(10, 20)
opt = torch.optim.SGD(model.parameters(), 0.01)
inp = torch.ones((10, 30), dtype=torch.float32)
model.train()

model.zero_grad()
out = model(inp)
out.sum().backward()
opt.step()
```

gives me the error 
```
Traceback (most recent call last):
  File "<input>", line 25, in <module>
  File "/Users/antonio/miniconda3/envs/python3_6/lib/python3.6/site-packages/torch/optim/sgd.py", line 106, in step
    p.data.add_(-group['lr'], d_p)
RuntimeError: set_indices_and_values_unsafe is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

## Environment
```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.15.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py36hfbe908c_0  
[conda] mkl_fft                   1.0.14           py36h5e564d8_0  
[conda] mkl_random                1.1.0            py36ha771720_0  
[conda] pytorch                   1.3.1                   py3.6_0    pytorch
[conda] tensorflow                1.14.0          mkl_py36h933f829_0  
[conda] tensorflow-base           1.14.0          mkl_py36h655c25b_0  
[conda] torchvision               0.4.2                  py36_cpu    pytorch
```
## Additional context

Just changing on `sgd.py`:
```
p.data.add_(-group['lr'], d_p)
```
to:
```
with torch.no_grad():
    p.add_(-group['lr'], d_p)
```
seems to fix the problem.

cc @vincentqb

**Comment by richardmcai** [comment]
Also having this issue. Seems to be related to #15070

**Comment by lematt1991** [comment]
I'm also seeing this bug.  I tried wrapping the `step` call in a `torch.no_grad()` `with` block, but am still getting the error.  Why is it that 

```Python
with torch.no_grad():
    opt.step()
```
fails, but moving the `with torch.no_grad()` into the SGD step succeeds?

**Comment by richardmcai** [comment]
This seems to have been fixed in pytorch 1.5

**Comment by vincentqb** [comment]
I confirm that I cannot reproduce this in master too. I will close this issue, but please feel free to re-open if this persists on master.

**Comment by zimmer-m** [comment]
I am getting this Runtime error when using basic SGD with momentum = 0.9, on pytorch 1.5.0 cpu_py37hd91cbb3_0.

**Comment by cadaverous-lives** [comment]
I am also getting this exact error with momentum on pytorch 1.5.1.

**Comment by vincentqb** [comment]
@zimmer-m and @cadaverous-lives -- can you provide details about your environment?

**Comment by zimmer-m** [comment]
Sure. This is probably not the smallest piece of code to reproduce this, by observed this when using the TextSentiment model with Sparse EmbeddingBag from [this official example](https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html). The error does not happen when I set sparse to False or momentum to 0.

**Setup:**
`python                    3.7.7                hcff3b4d_5 
pytorch                   1.5.0           cpu_py37hd91cbb3_0  
torchtext                 0.6.0                    pypi_0    pypi
`
**Code:**
`import torch, torchtext
import torch.nn as nn

class TextSentiment(nn.Module):
    # Based on https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html
    def __init__(self, vocab_size, embed_dim, num_class):
        super().__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, sparse=True) # Sparse needs to be true to not raise error
        self.fc = nn.Linear(embed_dim, num_class)

    def forward(self, text, offsets):
        embedded = self.embedding(text, offsets)
        return self.fc(embedded)

@torch.no_grad()
def generate_batch_ag_news(batch):
    label = torch.tensor([entry[0] for entry in batch])
    text = [entry[1] for entry in batch]
    offsets = [0] + [len(entry) for entry in text]

    offsets = torch.tensor(offsets[:-1]).cumsum(dim=0)
    text = torch.cat(text)
    return text, offsets, label

trainData, testData = torchtext.datasets.AG_NEWS(root='datasets/ag_news-data', ngrams=3, vocab=None)
vocabSize = len(trainData.get_vocab())
numClasses = len(trainData.get_labels())
embedDim = 32
trainLoader = torch.utils.data.DataLoader(trainData, batch_size=1024, shuffle=True,
                                          collate_fn=generate_batch_ag_news)
testLoader = torch.utils.data.DataLoader(testData, batch_size=1024, shuffle=False,
                                         collate_fn=generate_batch_ag_news)

model = TextSentiment(vocabSize, embedDim, numClasses)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)  # Setting momentum = 0.0 also solves the problem
criterion = torch.nn.CrossEntropyLoss()

for text, offsets, y_target in trainLoader:
    optimizer.zero_grad()
    output = model.eval()(text, offsets)
    loss = criterion(output, y_target)
    loss.backward()
    optimizer.step()`

**Output:**
`120000lines [00:09, 12300.29lines/s]
120000lines [00:16, 7385.75lines/s]
7600lines [00:00, 7914.08lines/s]
Traceback (most recent call last):
  File "minimal_code_example.py", line 43, in <module>
    optimizer.step()
  File "/home/miniconda3/envs/IOL/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/miniconda3/envs/IOL/lib/python3.7/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: set_indices_and_values_unsafe is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)

Process finished with exit code 1
`
Hope this is of help!

**Comment by v-vedantha** [comment]
Does anyone know how to deal with this problem?

**Comment by vkkhare** [comment]
The error still persists in torch 1.8. As a work around, I removed the `.detach()` call from `functional.sgd` 

```python
def sgd(params: List[Tensor],
        d_p_list: List[Tensor],
        momentum_buffer_list: List[Optional[Tensor]],
        *,
        weight_decay: float,
        momentum: float,
        lr: float,
        dampening: float,
        nesterov: bool):
    r"""Functional API that performs SGD algorithm computation.
    See :class:`~torch.optim.SGD` for details.
    """

    for i, param in enumerate(params):

        d_p = d_p_list[i]
        if weight_decay != 0:
            d_p = d_p.add(param, alpha=weight_decay)

        if momentum != 0:
            buf = momentum_buffer_list[i]

            if buf is None:
                buf = torch.clone(d_p) #-----HERE
                momentum_buffer_list[i] = buf
            else:
                buf.mul_(momentum).add_(d_p, alpha=1 - dampening)

            if nesterov:
                d_p = d_p.add(buf, alpha=momentum)
            else:
                d_p = buf

        param.add_(d_p, alpha=-lr)
```

**Comment by pjelement** [comment]
Find a way to solve this is updating in-place function to deal with sparse tensor:

if buf is None:
    buf = torch.clone(d_p).detach()
    momentum_buffer_list[i] = buf

To


  if buf is None:
      if d_p.is_sparse:
          buf = torch.clone(d_p.to_dense()).detach()
      else:
          buf = torch.clone(d_p).detach()
