### ISSUE TITLE
Problems with multiple users, single install

### ISSUE THREAD

**Issue by steige2** [pytorch/pytorch#29817]
## 🐛 Bug

import torch works for me but does not work for anyone else

## To Reproduce

python
>>> import torch
(for me, quiet completion)
(for another user, the following:)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/N/soft/rhel7/deeplearning/Python-3.7.4/lib/python3.7/site-packages/torch/__init__.py", line 228, in <module>
    class BFloat16Storage(_C.BFloat16StorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'BFloat16StorageBase'

## Expected behavior
quiet completion

## Environment

$ python collect_env.py
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
GCC version: (GCC) 6.3.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] numpy-utils==0.1.5.1
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect

**Comment by steige2** [comment]
Rebuilding everything (from a fresh python install) as opposed to an update to torch and torchvision seems to have fixed the problem. The root cause of what we observed, is not understood to me and the problem really should not occur at all. I also had a friendly user test before and after I installed the many other packages we have on our production instances. The troublesome import worked both before and after those installs which leads me to conclude the issue was not caused by packages external to torch. I'm going to leave this open in the hope someone with more insight than me will comment further.
