### ISSUE TITLE
Illegal memory access -- bug 

### ISSUE THREAD

**Issue by johnwlambert** [pytorch/pytorch#2983]
My pytorch training ran successfully for 150 epochs, then crashes as follows (I've never experienced this bug before in 6+ months of pytorch):

> THCudaCheck FAIL file=/py/conda-bld/pytorch_1490981920203/work/torch/lib/THC/THCTensorCopy.cu line=85 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 462, in <module>
    main(opt)
  File "train.py", line 176, in main
    _, _ = run_epoch(                  opt, epoch, train_loader, model, criterion, optimizer, None,         criterion2,  train=True)
  File "train.py", line 192, in run_epoch
    criterion, model, epoch, step, data_loader, optimizer, tag, criterion2)
  File "train.py", line 329, in run_iteration
    x_output_v = model(images_v)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 62, in forward
    return self.gather(outputs, self.output_device)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 74, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 50, in gather
    return gather_map(outputs)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 46, in gather_map
    return Gather(target_device, dim=dim)(*outputs)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 38, in forward
    return comm.gather(inputs, self.dim, self.target_device)
  File "/PATH_TO_HERE/anaconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 206, in gather
    result.narrow(dim, chunk_start, tensor.size(dim)).copy_(tensor, True)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /py/conda-bld/pytorch_1490981920203/work/torch/lib/THC/THCTensorCopy.cu:85

**Comment by apaszke** [comment]
What version are you using? Can you check the sizes of inputs to `gather`? It would be great if we could get a small script that reproduces the problem.

**Comment by johnwlambert** [comment]
Will try to reproduce. When I run 'python; import torch; torch.__version__;' I see version:
'0.1.11+b13b701'

**Comment by apaszke** [comment]
BTW I'd recommend updating to 0.2. 0.1.11 is 6 months old

**Comment by SsnL** [comment]
@johnwlambert Were you able to reproduce this on a small script? Or is this solved in later PyTorch version?

**Comment by johnwlambert** [comment]
Haven't been able to reproduce, feel free to close this issue.
