### ISSUE TITLE
torch.distributions.normal.Normal is not JIT supported

### ISSUE THREAD

**Issue by CamiWilliams** [pytorch/pytorch#29843]
## 🐛 Bug
When trying to use `torch.distributions.normal.Normal` in a JIT function, you get `torch.jit.frontend.NotSupportedError: comprehension ifs not supported yet`.

## To Reproduce
I am writing a function and calling `torch.distributions.normal.Normal.sample()`.

1. Call `torch.distributions.normal.Normal` in a function tagged with `@torch.jit.script`.

```
torch.distributions.normal.Normal(torch.mean(waveform), 1).sample()
```

## Expected behavior

JIT to compile funciton

## Traceback

```
Traceback (most recent call last):
  File "test/test_functional.py", line 6, in <module>
    import torchaudio
  File "/private/home/cwillycs/audio/torchaudio/__init__.py", line 7, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/private/home/cwillycs/audio/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/private/home/cwillycs/audio/torchaudio/functional.py", line 904, in <module>
    def dither(waveform, probability_density_function="TPDF", noise_shaping=False, ns_filter=""):
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 1075, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 148, in get_jit_class_def
    self_name=self_name) for method in methods]
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 169, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 209, in build_def
    build_stmts(ctx, body))
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 127, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 185, in __call__
    return method(ctx, node)
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 283, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 185, in __call__
    return method(ctx, node)
  File "/private/home/cwillycs/.local/lib/python2.7/site-packages/torch/jit/frontend.py", line 681, in build_ListComp
    raise NotSupportedError(r, "comprehension ifs not supported yet")
torch.jit.frontend.NotSupportedError: comprehension ifs not supported yet:
at /private/home/cwillycs/.local/lib/python2.7/site-packages/torch/distributions/distribution.py:263:23
    def __repr__(self):
        param_names = [k for k, _ in self.arg_constraints.items() if k in self.__dict__]
                        <--- HERE
        args_string = ', '.join(['{}: {}'.format(p, self.__dict__[p]
                                if self.__dict__[p].numel() == 1
                                else self.__dict__[p].size()) for p in param_names])
        return self.__class__.__name__ + '(' + args_string + ')'
'Normal' is being compiled since it was called from 'dither'
at /private/home/cwillycs/audio/torchaudio/functional.py:952:8
        random_tensor = int(torch.randint(wave_size, [1, ]).item())
        RPDF_dither = waveform[0][random_tensor] - 0.5

        signal_scaled_RPDF_dithered = signal_scaled + RPDF_dither
        quantised_signal_scaled_RPDF_dithered = torch.round(signal_scaled_RPDF_dithered)
        quantised_signal_RPDF_dithered = quantised_signal_scaled_RPDF_dithered / down_scaling

        dithered = quantised_signal_RPDF_dithered
    elif (probability_density_function == "GPDF"):
        gaussian_dither = torch.distributions.normal.Normal(torch.mean(waveform), 1).sample()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        signal_scaled_gaussian_dithered = signal_scaled + gaussian_dither
        quantised_signal_scaled_gaussian_dithered = torch.round(signal_scaled_gaussian_dithered)
        quantised_signal_gaussian_dithered = quantised_signal_scaled_gaussian_dithered / down_scaling

        dithered = quantised_signal_gaussian_dithered
    else:
        TPDF_dither = torch.bartlett_window(wave_size + 1)
```

## Additional context

Relevant to [PR #319](https://github.com/pytorch/audio/pull/319)

**Comment by ailzhang** [comment]
Sounds like this is a feature request for the `list comprehension with ifs`. Will discuss the priority in the triage meeting for it.

**Comment by eellison** [comment]
Dup of https://github.com/pytorch/pytorch/issues/27504

**Comment by rickstaa** [comment]
I experience the same problem when trying to apply the torch.jit.script method on a gaussian actor. For me, however, the error has now changed to the less informative `'Call' object has no attribute 'id'` error. Is this is caused by recent changes in the `torch.jit.script` method or am I doing something wrong?

### Code to reproduce the error

```python
import torch
import numpy as np


@torch.jit.script
def normal_test(wave):
    return torch.distributions.normal.Normal(torch.mean(wave), 1).sample()


if __name__ == "__main__":

    # Create wave
    wave_x = np.linspace(-5, 5, 15)
    wave_y = torch.sin(torch.FloatTensor(wave_x))

    # Run Normal Jit test
    print(type(normal_test))  # torch.jit.ScriptFuncion
    print(normal_test.code)
    print(normal_test(wave_y))
```

**Comment by jiangsy** [comment]
The error of 'Call' object has no attribute 'id' seems to be caused by the `with torch.no_grad()` in `sample()` , (relevant to #44768). However, even if I remove the entire `sample()` function, new errors still come when unpacking the tuple in `self.loc, self.scale = broadcast_all(loc, scale)` (relevant to #28303). Hope that `torch.distributions` can be supported by jit since it's commonly used in probabilistic actors in reinforcement learning.

**Comment by jiangsy** [comment]
It may also require a better support of Class (e.g. inheritance #26177).. so things may be a little bit tricky

**Comment by jiangsy** [comment]
a minimal workaround for torch.Normal could be 

``` python
class Normal:
    @property
    def mean(self):
        return self.loc

    @property
    def stddev(self):
        return self.scale

    @property
    def variance(self):
        return self.stddev.pow(2)

    def __init__(self, loc: torch.Tensor, scale: torch.Tensor):
        self.loc = torch.broadcast_tensors(loc, scale)[0]
        self.scale = torch.broadcast_tensors(loc, scale)[1]
        self._batch_shape = list(self.loc.size())

    def _extended_shape(self, sample_shape: List[int]) -> List[int]:
        return sample_shape + self._batch_shape

    def sample(self, sample_shape: List[int] = []):
        shape = self._extended_shape(sample_shape)
        return torch.normal(self.loc.expand(shape), self.scale.expand(shape))

    def rsample(self, sample_shape: List[int] = []):
        shape: List[int] = self._extended_shape(sample_shape)
        eps = torch.normal(torch.zeros(shape), torch.ones(shape))
        return self.loc + eps * self.scale

    def log_prob(self, value):
        var = (self.scale ** 2)
        log_scale = self.scale.log()
        return -((value - self.loc) ** 2) / (2 * var) - log_scale - math.log(math.sqrt(2 * math.pi))

    def entropy(self):
        return 0.5 + 0.5 * math.log(2 * math.pi) + torch.log(self.scale)

    @property
    def _natural_params(self):
        return (self.loc / self.scale.pow(2), -0.5 * self.scale.pow(2).reciprocal())

    def _log_normalizer(self, x: torch.Tensor, y: torch.Tensor):
        return -0.25 * x.pow(2) / y + 0.5 * torch.log(-math.pi / y)
```

**Comment by johnc1231** [comment]
Also running into this problem, can't create a torchscript function using the `StudentT` distribution.

**Comment by perone** [comment]
It would be nice actually if there are tests in torch checking that the distributions are TorchScript-compatible, as this is a very common scenario.

**Comment by datumbox** [comment]
I needed to use Beta and found myself in a similar situation. My workaround was to use the `torch._sample_dirichlet()` method (Dirichlet is the generalization of Beta for multi-variate setup). The method is private, so one uses it at their own risk but the idea is that you could use one of the functional versions that exist for sampling from different distributions.

**Comment by ProGamerGov** [comment]
I recently came a similar issue, and even wrapping the torch.distributions call in a separate class function under `torch.jit.ignore` doesn't work:

```
self = RecursiveScriptModule(original_name=TestModule)
input = (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., ...1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]]),)
kwargs = {}, forward_call = <torch._C.ScriptMethod object at 0x7f6e68659c50>

    def _call_impl(self, *input, **kwargs):
        forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.forward)
        # If we don't have any hooks, we want to skip the rest of the logic in
        # this function, and just call forward.
        if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
                or _global_forward_hooks or _global_forward_pre_hooks):
>           return forward_call(*input, **kwargs)
E           RuntimeError: The following operation failed in the TorchScript interpreter.
E           Traceback of TorchScript (most recent call last):
E             File "test.py", line 634, in forward
E                   assert x.dim() == 4
E                   if self.is_distribution:
E                       value = self._sample_distribution()
E                               ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
E                   else:
E                       n = int(
E           RuntimeError: AttributeError: 'RecursiveScriptModule' object has no attribute 'get_distribution'
E           
```

**Comment by ProGamerGov** [comment]
I found a simple workaround to making torch.distributions JIT compatible by using an inner class inside of a function: 

```
import torch

def jit_prob_dist(
    prob_dist: torch.distributions.distribution.Distribution,
) -> torch.nn.Module:
    class JITProbDist(torch.nn.Module):
        @torch.jit.ignore
        def sample(self):
            return prob_dist.sample()

    return JITProbDist()


prob_dist_uniform = torch.distributions.Uniform(0.95, 1.05)

prob_dist_module = jit_prob_dist(prob_dist_uniform)

print(prob_dist_module.sample().item())
prob_dist_module = torch.jit.script(prob_dist_module)
print(prob_dist_module.sample().item())
```

**Comment by rickstaa** [comment]
@ProGamerGov That seems like a good work-around for now. Thanks!

**Comment by IcarusWizard** [comment]
I am facing the same problem. Any update so far?

**Comment by ericg108** [comment]
same problem..any update?

**Comment by rschiewer** [comment]
Still a problem with torch==2.0.1 unfortunately.

My current workaround:
- Wrap calls to the actual distribution object into torch.jit.ignore functions as @ProGamerGov pointed out.
- If the distribution object is needed in multiple places, transport its naked  parameter tensor(s) around, this works fine with scripted functions. Tuples or dicts are a good way to generalize your code over different distributions.
- Use helper functions to build a distribution from a stack of naked parameters.

**Comment by ProGamerGov** [comment]
@huiyusong Unfortunately, I am not sure how you would resolve those issues

**Comment by andife** [comment]
I would also be interested in that functionality. Same problem with 2.2.0.dev20231006+cpu.

I am mainly interested in exporting a model containing this to onnx.... but presumably the new dynamo export also runs via jit? (ok, maybe it is better to open a separate issue?)

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
