### ISSUE TITLE
died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by PistonY** [pytorch/pytorch#29889]
## 🐛 Bug
Hello, I use Pytorch to train my model, and suddenly raise a error, I've tried for a few times, I could train for some epochs, and this error suddenly comes out.
I really don't know why and how to figure this.
```shell
Traceback (most recent call last):
  File "/home/xddz/.conda/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xddz/.conda/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xddz/.conda/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/xddz/.conda/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command XXXXX (my script params) died with <Signals.SIGSEGV: 11>.
```
## Environment

I use Ubuntu 18.04
CUDA: 10.1
CUDNN: 7.6
Pytorch: 1.3 with miniconda.
I use to this to launch.
```shell
python -u -m torch.distributed.launch my_script --params
```

**Comment by nyyznyyz1991** [comment]
I have the same problem, can anyone offer some solutions?

**Comment by PistonY** [comment]
Try Python 3.6.

**Comment by lilei461536135** [comment]
I come up with the same died with <Signals.SIGSEGV: 11>
Test Content: NVIDIA NGC BERT for Pytorch Squad fine-tuning
The docker image built based on nvcr.io/nvidia/pytorch-19.09-py3
>>> print(torch.__version__)
1.2.0a0+afb7a16

**Comment by nicolasugrinovic** [comment]
@PistonY I know this is kind of old, but could you fix the issue. How did you do it?

**Comment by densechen** [comment]
Me, too
