### ISSUE TITLE
AttributeError: module 'torch.cuda.profiler' has no attribute 'initialize'

### ISSUE THREAD

**Issue by alexholdenmiller** [pytorch/pytorch#3013]
```
>>> with torch.autograd.profiler.profile(use_nvprof=True, trace_path='results') as prof:
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ahm/anaconda3/lib/python3.6/site-packages/torch/autograd/profiler.py", line 89, in __enter__
    torch.cuda.profiler.initialize()
AttributeError: module 'torch.cuda.profiler' has no attribute 'initialize'
```

it looks like `/home/ahm/anaconda3/lib/python3.6/site-packages/torch/autograd/profiler.py` just has `init` (which needs an output_file argument) but no `initialize`

**Comment by soumith** [comment]
this was fixed in https://github.com/pytorch/pytorch/pull/3120
