### ISSUE TITLE
[windows] driver shut down

### ISSUE THREAD

**Issue by micklexqg** [pytorch/pytorch#3019]
I reinserted my GPU. but then I came into a very strange problem. the code stucks at test.(training successfully for 1 epoch but then it got stuck at testing)
Alexnet is with the error:
Couldn’t open shared file mapping: <torch_14808_1591070686>, error code: <1455> at D:\Downloads\pytorch-master-1\torch\lib\TH\THAllocator.c:154
resnet is with the error of “driver shut down” beside the above.
but the gpu worked well for keras and matlab. I think my condition is similar as issue 56 https://github.com/pytorch/examples/issues/56
Is it a bug?

**Comment by micklexqg** [comment]
#pytorch/examples#56

**Comment by soumith** [comment]
cc: @peterjc123

**Comment by peterjc123** [comment]
@micklexqg Which version are you using?

**Comment by peterjc123** [comment]
Also, remember to shutdown your existing background python processes before running a new one.

**Comment by micklexqg** [comment]
@peterjc123 , I noticed I have installed two different packages(0.1.12 and 0.2.1) . I deleted and uninstalled all (Anaconda + pycharm+pytorch) and then reinstalled them(Python 3.5.2+pytorch 0.1.12). And I think this problem has something to do with multiprocess. So I set the worker 0(I find the training becomes a little slower). For now, everything works well. 
Thanks!

**Comment by aitaoquanyi** [comment]
@micklexqg  i find set worker 0 ( the training becomes much slower ), do you sove this problem now?

**Comment by peterjc123** [comment]
@aitaoquanyi You asked in two issues with different errors. The error code of these two are not the same. Can you please send me the complete traceback for me to detect the underlying problem?

**Comment by peterjc123** [comment]
@aitaoquanyi It seems this error is hardware related. You may try updating the drivers of your graphics card. However, if this doesn't help, then you can only use num_worker =0, I think.

**Comment by aitaoquanyi** [comment]
@peterjc123 thanks, i will try.

**Comment by peterjc123** [comment]
@aitaoquanyi And it may be related the TDR settings on Windows. 
 Since there is a timeout for driver operation, drivers will get shutdown when it exceeds the timeout. You can try modifying this according to [here](https://www.pugetsystems.com/labs/hpc/Working-around-TDR-in-Windows-for-a-better-GPU-computing-experience-777/).

**Comment by chuong98** [comment]
Setting num_worker =0 can solve the problem, but significantly slow. Compare to num_worker=8, I can feel it like 8 times slower. Any real solution for this?

**Comment by peterjc123** [comment]
@chuong98 Your code and machine specs, please.

**Comment by chuong98** [comment]
Hi, thanks for your support. 

My machine's spec:
CPU: AMD Threadripper 1900x
GPU: 2x1080Ti
Operate Sys: Window 10
Pytorch is installed in cuda.
Running mode:  DataParallel(self.model).to(self.device)

Here is the error code: 
`  
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 187, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 187, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 162, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "C:\Users\Chuong\AppData\Local\conda\conda\envs\pytorch_env\lib\site-packages\torch\storage.py", line 118, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_12900_2928290023>, error code: <0>
`

**Comment by peterjc123** [comment]
@chuong98 There may be some bug in `nn.DataParallel`. As a workground, you can manually start multiple processes that run on different GPUs. See this [post](https://github.com/pytorch/pytorch/issues/12276) for details.

**Comment by usamabaig1** [comment]
Hey, Can you help me out on this please?
`Traceback (most recent call last):
  File "FYP/NCRF/wsi/bin/train.py", line 281, in <module>
    main()
  File "FYP/NCRF/wsi/bin/train.py", line 277, in main
    run(args)
  File "FYP/NCRF/wsi/bin/train.py", line 191, in run
    optimizer = SGD(model.parameters(), lr=cfg['lr'], momentum=cfg['momentum'])
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\optim\sgd.py", line 57, in __init__
    super(SGD, self).__init__(params, defaults)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\optim\optimizer.py", line 39, in __init__
    self.add_param_group(param_group)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\optim\optimizer.py", line 153, in add_param_group
    raise ValueError("optimizing a parameter that doesn't require gradients")
ValueError: optimizing a parameter that doesn't require gradients

(Py36gpu) C:\Users\Usama Baig>python FYP/NCRF/wsi/bin/train.py FYP/NCRF/configs/resnet18_base.json FYP/NCRF/SAVE_PATH/Inceptiontest
THCudaCheck FAIL file=c:\anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\thc\generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "FYP/NCRF/wsi/bin/train.py", line 281, in <module>
    main()
  File "FYP/NCRF/wsi/bin/train.py", line 277, in main
    run(args)
  File "FYP/NCRF/wsi/bin/train.py", line 235, in run
    dataloader_normal_train)
  File "FYP/NCRF/wsi/bin/train.py", line 65, in train_epoch
    output = model(data) # forward prop
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\parallel\data_parallel.py", line 71, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usama Baig\FYP\NCRF\wsi\bin/../..\wsi\model\inceptionresnetv2.py", line 357, in forward
    x = self.features(x)
  File "C:\Users\Usama Baig\FYP\NCRF\wsi\bin/../..\wsi\model\inceptionresnetv2.py", line 322, in features
    x = self.conv2d_4a(x)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usama Baig\FYP\NCRF\wsi\bin/../..\wsi\model\inceptionresnetv2.py", line 52, in forward
    x = self.bn(x)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\modules\batchnorm.py", line 37, in forward
    self.training, self.momentum, self.eps)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\nn\functional.py", line 1013, in batch_norm
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at c:\anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\thc\generic/THCStorage.cu:58
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x0000019DE4E02748>>
Traceback (most recent call last):
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\utils\data\dataloader.py", line 333, in __del__
    self._shutdown_workers()
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\utils\data\dataloader.py", line 319, in _shutdown_workers
    self.data_queue.get()
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Usama Baig\AppData\Local\conda\conda\envs\Py36gpu\lib\site-packages\torch\multiprocessing\reductions.py", line 86, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Couldn't open shared file mapping: <torch_14388_1155387754>, error code: <2> at C:\Anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\TH\THAllocator.c:157`

**Comment by peterjc123** [comment]
@usamabaig1 The actual error is `RuntimeError: cuda runtime error (2) : out of memory`. You are just using too much GPU memory.

**Comment by usamabaig1** [comment]
But the window's task manager GPU doesn't show any signs of it. It gives this error barely after a minute and the GPU utilization barely exceeds 5pc.

**Comment by houta-higuchi** [comment]
I set my dataloader ```num_worker=3``` and it works now.
