### ISSUE TITLE
pytorch_java_only-1.4.0-20191120.095751-9.jar  load model bug

### ISSUE THREAD

**Issue by princexiaobai** [pytorch/pytorch#30227]
## To Reproduce
pytorch_java_only-1.4.0-SNAPSHOT/pytorch_java_only-1.4.0-20191120.095751-9.jar 
when load pytorch model by java, throw exeception:

Caused by: java.lang.NoClassDefFoundError: org/pytorch/Module$NativePeer
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:22)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
	at org.pytorch.NativePeer.<clinit>(NativePeer.java:10)
	at org.pytorch.Module.load(Module.java:23)

1. mvn clean package 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by dreiss** [comment]
We made a change that requires updating both the Java and C++ sides of the JNI library simultaneously.  It looks like you're using the latest Java jar, so please download the latest libtorch and try again.

cc @xcheng16 and @IvanKobzarev .  This should never affect our internal builds or external release builds, but it can happen to anyone external using snapshot/nightly.  If we need to make a change like this again (moving NativePeer out of Module), maybe we should think about adding a mechanism to generate a clearer error message if the Java and C++ are out of sync.
