### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED, again, with large batch size

### ISSUE THREAD

**Issue by zxytim** [pytorch/pytorch#3038]
script to reproduce the error:
```
#!/usr/bin/env python3
import torch
from torch import nn
from torch.nn import Parameter
import torch.nn.functional as F
from torch.autograd import Variable

input = Variable(torch.zeros(200704, 32).cuda())

running_mean = torch.zeros(32).cuda()
running_var = torch.ones(32).cuda()

weight = Parameter(torch.ones(32).cuda())
bias = Parameter(torch.ones(32).cuda())

F.batch_norm(input, running_mean, running_var, weight, bias,
             training=True)

```
result:
```
Traceback (most recent call last):
  File "./2017-10-09.batch_norm.py", line 17, in <module>
    training=True)
  File "/home/zxy/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 639, in batch_norm
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

```
I'm using pytorch 0.2.0_3, with CUDA 8.0 and cudnn 6.0.20

**Comment by soumith** [comment]
this is fixed on master via https://github.com/pytorch/pytorch/pull/2919
Will be part of next release.

**Comment by zxytim** [comment]
Thanks Soumith, its good to hear that the problem has been
already addressed.
BTW, when will be the next release?
