### ISSUE TITLE
Can't use linux wheel without ld path modifications

### ISSUE THREAD

**Issue by chyzzqo2** [pytorch/pytorch#30450]
Trying to run simple sample code

```python3 -c 'import torch; torch.rand(100, pin_memory=True)'``` 

errors with

```RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory```

if i modify my LD_LIBRARY_PATH to include the lib directory extracted from the wheel `/usr/local/lib/pythonx.x/site-packages/torch/lib` then everything works. But I shouldn't have to do that.

```
PyTorch version: 1.4.0.dev20191125
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 430.50
cuDNN version: /usr/local/cuda/lib64/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] torch==1.4.0.dev20191125
[conda] Could not collect
```

Even though the above shows a nightly build I've tested on python 2.7 and 3.7 with versions 1.2.0 1.3.0, 1.3.1 and 1.4.0.dev20191125. Version 1.1 worked fine.

Any suggestions?

cc @ezyang

**Comment by peterjc123** [comment]
cc @soumith  @pjh5

**Comment by pietern** [comment]
I notice your base path for Python is `/usr/local`, which could be related here..

Shouldn't Python take care of setting the appropriate loader paths?

**Comment by pietern** [comment]
I installed PyTorch 1.3.1 in a fresh conda environment to dig a bit, and can't figure out where `libcaffe2_nvrtc.so` is supposed to be loaded. Can you provide a stack trace of the error?

**Comment by chyzzqo2** [comment]
I'm talking here about the using system python with the wheels provided by pypi.org. Conda does is a different environment and does things differently.

`/usr/local/lib` or `/usr/lib` is immaterial. I can reproduce both ways.

**Comment by chyzzqo2** [comment]
I'm not very familiar with this code base but from what i can gather from code comments is that libcaffe2_nvrtc is lazy loaded via hooks. Because the so's that you are distributing are not in the system library path but in a directory buried inside your python code that lazy loading isn't working. I could be totally wrong here but i think that you need to tell the lazy loader where to find these libraries since they are in a non standard location.

**Comment by chyzzqo2** [comment]
Stack trace is unhelpful
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory```

strace is more interesting here's the part where it tries to load that lib:

```bind(8, {sa_family=AF_UNIX, sun_path=@"cuda-uvmfd-4026532646-715\0"}, 29) = 0
listen(8, 128)                          = 0
clone(child_stack=0x7f0f95c25fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f0f95c269d0, tls=0x7f0f95c26700, child_tidptr=0x7f0f95c269d0) = 721
futex(0x55ae03263a08, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 715
futex(0x7f0f48481d70, FUTEX_WAKE_PRIVATE, 2147483647) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efee30) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x4a, 0xc0), 0x7fffc9efeed0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efee00) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efece0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efece0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efece0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efed70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efed70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efece0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efece0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efece0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efed70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efed70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efed90) = 0
futex(0x7f0f8dde6950, FUTEX_WAKE_PRIVATE, 2147483647) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe790) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe670) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe670) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe670) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe700) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe700) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe670) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe670) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe670) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe700) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe700) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efe720) = 0
futex(0x55ae022d9d70, FUTEX_WAKE_PRIVATE, 2147483647) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efec00) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeae0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeae0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeae0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeb70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeb70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeae0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeae0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeae0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeb70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeb70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffc9efeb90) = 0
futex(0x7f0f8ddc9240, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "tls/x86_64/x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda/lib64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 10
fstat(10, {st_mode=S_IFREG|0644, st_size=65396, ...}) = 0
mmap(NULL, 65396, PROT_READ, MAP_PRIVATE, 10, 0) = 0x7f0fa10dd000
close(10)                               = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7f0fa10dd000, 65396)           = 0
futex(0x7f0fa1fa0270, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f0f907af1a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "Traceback (most recent call last"..., 35Traceback (most recent call last):
) = 35
write(2, "  File \"<string>\", line 1, in <m"..., 39  File "<string>", line 1, in <module>
) = 39
openat(AT_FDCWD, "<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/apps/python3/lib/python37.zip/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/apps/python3/lib/python3.7/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/apps/python3/lib/python3.7/lib-dynload/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/apps/python3/lib/python3.7/site-packages/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "RuntimeError: Error in dlopen or"..., 118RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory
) = 118
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0fa1beff20}, {sa_handler=0x7f0fa21bade0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0fa1beff20}, 8) = 0
munmap(0x7f0f46d18000, 262144)          = 0
sigaltstack(NULL, {ss_sp=0x55ae01a72000, ss_flags=0, ss_size=8192}) = 0
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
futex(0x7f0f9ec6c948, FUTEX_WAKE_PRIVATE, 2147483647) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
munmap(0x7f0f98428000, 33554432)        = 0
munmap(0x7f0f95c27000, 33554432)        = 0
munmap(0x7f0f93426000, 33554432)        = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by soumith** [comment]
I suspect that this is something deeper, i.e. libcaffe2_nvrtc.so is not able to be loaded.

But if the issue is reproducible on 1.2 and 1.3 as well, there are no recent commits that are the issue. I am not entirely sure what's up. I cannot reproduce this on a fresh docker env on Ubuntu 16.04, 18.04 or CentOS7 that uses system Python (not Conda).

@chyzzqo2 any chance you can repro the issue in a docker? That'd be ideal for making progress on our end.

**Comment by chyzzqo2** [comment]
You have a docker image you'd like to me to use to try it out?

**Comment by chyzzqo2** [comment]
> I suspect that this is something deeper, i.e. libcaffe2_nvrtc.so is not able to be loaded.

That was my thought too but changing LD_LIBRARY_PATH did make it work, so the libs themselves seem to be fine.

I was using 18.04, what image were you using to test?

**Comment by chyzzqo2** [comment]
Traced this down to another shared library injecting it's own version of dlopen. So this isn't actually broken by default. Thanks for the pointer on trying with the included images and sorry for the noise.

**Comment by pietern** [comment]
@chyzzqo2 Wow, never heard of that before!

Can you share which library this was, so I know what to avoid? LOL!

**Comment by chyzzqo2** [comment]
It was an internal library similar to libmonitor, loaded via a sitecustomize hook.
