### ISSUE TITLE
`torch.multiprocessing.spawn` fails when `join=False`

### ISSUE THREAD

**Issue by joshim5** [pytorch/pytorch#30461]
## 🐛 Bug

Invoking `torch.multiprocessing.spawn(fn, args=(), nprocs=n, join=False)` raises a `FileNotFoundError` when `join=False`. In contrast, `join=True` works as expected.

## To Reproduce

The following script reproduces the error on pytorch versions `1.1.0` and `1.3.0a0+f25d01e`.

```	
import torch.multiprocessing as mp
import time

def worker(nproc, arg1, arg2, arg3):
    # do something...
    test = True

if __name__ == '__main__':
    mp.spawn(worker, (None, None, None), nprocs=1, join=False)
    time.sleep(3)
    print('terminated')
```

The script fails with the following error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../python3.7/multiprocessing/spawn.py", line 105 in spawn_main
    exitcode = _main(fd)
  File ".../python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File ".../python3.7/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
terminated
```

Note that `terminated` is printed, showing that the error occurs in the worker thread.

## Expected behavior

The `FileNotFoundError` should not occur. Indeed, `terminated` is printed without any errors if we change `join=False` to `join=True`.

## Environment

PyTorch version: 1.3.0a0+f25d01e
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0a0+f25d01e
[pip] torchvision==0.5.0a0+937c83a
[conda] blas                      1.0                   mkl.conda
[conda] magma-cuda100             2.5.1                         1    pytorch
[conda] mkl                       2019.4                243.conda
[conda] mkl-include               2019.4                243.conda
[conda] mkl-service               2.3.0           py37he904b0f_0.conda
[conda] mkl_fft                   1.0.14          py37ha843d7b_0.conda
[conda] mkl_random                1.1.0           py37hd6b4f25_0.conda
[conda] torch                     1.3.0a0+f25d01e           <pip>

**Comment by pietern** [comment]
Per https://pytorch.org/docs/stable/multiprocessing.html#torch.multiprocessing.spawn, calling `spawn` with `join=False` makes it return a `SpawnContext`. This object contains the PIDs of the spawned processes, the inter process queues, etc.

In your example, you don't use this return and it is destructed immediately. By the time the worker process has started, it can no longer find the handles to the inter process queues that it was promised and prints the error. You can fix this by updating your example as follows:

```diff
diff --git a/repro_org.py b/repro.py
index be44c3d..e971db4 100644
--- a/repro_org.py
+++ b/repro.py
@@ -6,7 +6,8 @@ def worker(nproc, arg1, arg2, arg3):
     test = True
 
 if __name__ == '__main__':
-    mp.spawn(worker, (None, None, None), nprocs=1, join=False)
+    ctx = mp.spawn(worker, (None, None, None), nprocs=1, join=False)
     time.sleep(3)
     print('terminated')
+    ctx.join()
```

We could fix this by waiting until all processes were actually started before returning. This might cause an issue when they terminate, but at least it would get rid of this gnarly error message.
