### ISSUE TITLE
Two tests failing in test_torch.py when run from a GPU server

### ISSUE THREAD

**Issue by nairbv** [pytorch/pytorch#30488]
When I run `python test_torch.py` on a GPU server, there are two tests that consistently fail. Could be environment related?

## To Reproduce
```
[26 17:10:54 ~/repos/pytorch/test]$ python test_torch.py TestTorchDeviceTypeCUDA.test_lu_cuda
F
======================================================================
FAIL: test_lu_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bvaughan/repos/pytorch/test/common_utils.py", line 631, in wrapper
    method(*args, **kwargs)
  File "/home/bvaughan/repos/pytorch/test/common_device_type.py", line 179, in instantiated_test
    return test(self, device_arg)
  File "/home/bvaughan/repos/pytorch/test/common_device_type.py", line 334, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bvaughan/repos/pytorch/test/common_device_type.py", line 334, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bvaughan/repos/pytorch/test/test_torch.py", line 12571, in test_lu
    run_test(device, True)
  File "/home/bvaughan/repos/pytorch/test/test_torch.py", line 12565, in run_test
    run_subtest(ms, batch, device, pivot, singular=True, a=a)
  File "/home/bvaughan/repos/pytorch/test/test_torch.py", line 12541, in run_subtest
    self.assertEqual(P.matmul(L.matmul(U)), a)
  File "/home/bvaughan/repos/pytorch/test/common_utils.py", line 808, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/bvaughan/repos/pytorch/test/common_utils.py", line 766, in assertTensorsEqual
    self.assertTrue(torch.equal(nan_mask, torch.isnan(b)), message)
AssertionError: False is not true :

----------------------------------------------------------------------
Ran 1 test in 11.984s

FAILED (failures=1)

[26 17:19:38 ~/repos/pytorch/test]$ python test_torch.py TestTorchDeviceTypeCUDA.test_det_logdet_slogdet_batched_cuda_float64
F
======================================================================
FAIL: test_det_logdet_slogdet_batched_cuda_float64 (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bvaughan/repos/pytorch/test/common_utils.py", line 631, in wrapper
    method(*args, **kwargs)
  File "/home/bvaughan/repos/pytorch/test/common_device_type.py", line 196, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/home/bvaughan/repos/pytorch/test/common_device_type.py", line 334, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bvaughan/repos/pytorch/test/common_device_type.py", line 334, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bvaughan/repos/pytorch/test/test_torch.py", line 7083, in test_det_logdet_slogdet_batched
    run_test(matsize, batchdims, mat_chars=['sing'])
  File "/home/bvaughan/repos/pytorch/test/test_torch.py", line 7079, in run_test
    self.assertEqual(actual_value, expected_value, allow_inf=True)
  File "/home/bvaughan/repos/pytorch/test/common_utils.py", line 808, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/bvaughan/repos/pytorch/test/common_utils.py", line 766, in assertTensorsEqual
    self.assertTrue(torch.equal(nan_mask, torch.isnan(b)), message)
AssertionError: False is not true :

----------------------------------------------------------------------
Ran 1 test in 11.352s

FAILED (failures=1)
```

## Environment
```
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Tesla M40
GPU 1: Tesla M40
GPU 2: Tesla M40
GPU 3: Tesla M40
GPU 4: Tesla M40
GPU 5: Tesla M40
GPU 6: Tesla M40
GPU 7: Tesla M40

Nvidia driver version: 396.69
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] numpydoc==0.9.1
[pip3] torch==1.4.0a0+4714237
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] mkldnn                    0.16.1                        0    mingfeima
[conda] torch                     1.2.0a0+b632d3b          pypi_0    pypi
[conda] torchtext                 0.3.1                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi
```
## Additional context

Running on master, not sure why the above script says N/A for pytorch version.

cc @ezyang @gchanan @zou3519 @jerryzh168 @ngimel

**Comment by mruberry** [comment]
@csarofeen fyi

**Comment by charleshofer** [comment]
I am seeing these two failures on `ppc64le` as well

**Comment by pearu** [comment]
I cannot reproduce the test failures when considering the following variations:
```
OS: ubuntu 18.04, centos 7.6
GPU devices (all 2x): GeForce RTX 2060 SUPER, Quadro RTX 6000/8000, TITAN RTX
CUDA: 9.2, 10.1
pytorch: current master, 1.4.0
```
(I don't have access to `ppc64le` system here.)

From the description of this issue, notice:
```
[pip3] torch==1.4.0a0+4714237
[conda] torch                     1.2.0a0+b632d3b          pypi_0    pypi
```
that is, there exists two torch version in the system: 1.2 and 1.4. This is odd but does not necessarily lead to the current issue.

@nairbv , can you confirm that this issue still exists in your environment when using pytorch master?
If so, could you run
```
git clean -xdf
git submodule foreach --recursive git clean -xfd
git checkout master
git pull --rebase
git submodule sync --recursive
git submodule update --init --recursive
python setup.py develop --cmake-only > cmake.output 2>&1
python setup.py develop  # or install if preferred
python test/test_torch.py TestTorchDeviceTypeCUDA.test_lu_cuda
```
and post the content of `cmake.output` here? This would be helpful for reproducing the issue.

**Comment by choidongyeon** [comment]
Hey @nairbv, were you able to find a workaround for this?
