### ISSUE TITLE
[jit] Cannot create a `Tuple[List[T]]`

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#30482]
This fails

```python
@torch.jit.script
def fn(x):
    # type: (List[int])
    return tuple(x)
```

```
Traceback (most recent call last):
  File "../test.py", line 190, in <module>
    @torch.jit.script
  File "/home/davidriazati/dev/pytorch/torch/jit/__init__.py", line 1276, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
cannot statically infer the expected size of a list in this context:
  File "../test.py", line 193
def fn(x):
    # type: (List[int])
    return tuple(x)
           ~~~~~~~ <--- HERE
```

but this works

```python
@torch.jit.script
def fn(x):
    # type: (List[int])
    return (x,)
```

cc @suo

**Comment by aryan461** [comment]
So how we shold convert a list integers to a tuple of integers (with unknown length) and it is still sciptable?

**Comment by eellison** [comment]
If you know the length of the list, you can convert it to a tuple by explicitly creating a tuple `(li[0], li[1], ...)`. If you don't know, I would try to rewrite your code to a list of integers instead of a tuple of integers with unknown length.
