### ISSUE TITLE
jit and GRU

### ISSUE THREAD

**Issue by cinhcet** [pytorch/pytorch#30539]
## 🐛 Bug
I try to convert a simple GRU module to torch script, but it gives the following error, for both tracing and scripting:
```
Traceback (most recent call last):
  File "/home/user/git/pyTorchTest/python/test.py", line 15, in <module>
    torch.jit.trace(RNN(), torch.zeros((10,10,10)))
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 858, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 991, in trace_module
    module = make_module(mod, _module_class, _compilation_unit, tuple(inputs.keys()))
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 709, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 1462, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 1462, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 1733, in __init__
    self._modules[name] = make_module(submodule, TracedModule, _compilation_unit)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 705, in make_module
    return torch.jit._recursive.recursive_script(mod, exclude_methods)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/__init__.py", line 2073, in _get_named_tuple_properties
    annotations.append(torch.jit.annotations.ann_to_type(obj.__annotations__[field]))
  File "/home/user/pytorch/lib/python3.5/site-packages/torch/jit/annotations.py", line 258, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[torch.Tensor, NoneType]'
```

Am I missing something completely obvious?

## To Reproduce
```
import torch

class RNN(torch.nn.Module):
    def __init__(self):
        super(RNN, self).__init__()
        self.rnn = torch.nn.GRU(input_size=10,
                                hidden_size=10,
                                batch_first=True)

    def forward(self, inputs):
        x, _ = self.rnn(inputs)
        return x


torch.jit.trace(RNN(), torch.zeros((10,10,10)))
torch.jit.script(RNN())
```

## Expected behavior

should not produce this error

## Environment
Collecting environment information...
PyTorch version: 1.3.1+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.12.1
[pip3] torch==1.3.1+cpu
[pip3] torchvision==0.4.2+cpu
[conda] Could not collect

## Additional context
When I try the same with other layers like Linear or convolutional ones, it works.

cc @suo

**Comment by cinhcet** [comment]
I tried the same with the nightly build (on a different machine), now tracing seems to work, scripting still not:
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    torch.jit.script(RNN())
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/__init__.py", line 1250, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/__init__.py", line 1588, in _construct
    init_fn(script_module)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 471, in infer_methods_to_compile
    overload_stubs = make_stubs_for_overloads(overload_info)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/_recursive.py", line 433, in make_stubs_for_overloads
    torch.jit._check_no_signature(overload_fn)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/__init__.py", line 2032, in _check_no_signature
    signature = torch.jit.annotations.get_signature(func, None, None)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/annotations.py", line 71, in get_signature
    return parse_type_line(type_line, rcb, loc)
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/annotations.py", line 122, in parse_type_line
    arg_types = [ann_to_type(ann, resolver) for ann in arg_ann]
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/annotations.py", line 122, in <listcomp>
    arg_types = [ann_to_type(ann, resolver) for ann in arg_ann]
  File "/home/user/pytorchNightly/lib/python3.5/site-packages/torch/jit/annotations.py", line 250, in ann_to_type
    the_type = torch._C._resolve_type(ann.__name__, loc, rcb)
TypeError: _resolve_type(): incompatible function arguments. The following argument types are supported:
    1. (arg0: str, arg1: torch._C._jit_tree_views.SourceRange, arg2: Callable[[str], function]) -> torch._C.Type

Invoked with: 'Union', None, None
```


## Environment
Collecting environment information...
PyTorch version: 1.4.0.dev20191127+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.4.0.dev20191127+cpu
[pip3] torchvision==0.5.0.dev20191127+cpu
[conda] Could not collect

**Comment by cinhcet** [comment]
On further investigation I tried python 3.6 and pytorch 1.3.1, now everything (both tracing and scripting) works

Collecting environment information...
PyTorch version: 1.3.1+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1+cpu
[pip3] torchvision==0.4.2+cpu
[conda] Could not collect


So somehow it has to do with the python version

**Comment by cinhcet** [comment]
I have reproduced this issue on multiple machines with installations from different people. 
If it is ubuntu 16.04 with python 3.5, it crashes, if it is python 3.6, it works.

So for me this is kind of resolved, since I could just convert the model to torchscript with python 3.6, even though the model was trained with python 3.5.

I would still found it interesting whether someone else also experienced this or shall I close the issue?

**Comment by suo** [comment]
Thanks for the investigation! Our policy is to support the latest three major version of Python. As of the release of Python 3.8 (10/14/19), we don't support Python 3.5 anymore, so if things are working for you on Python 3.6 we probably won't look into it. 

So I'll close the issue for now, but if anyone sees something similar on supported versions of Python feel free to reopen!
