### ISSUE TITLE
Running fp32 softmax on a fp16 tensor for dimensions other than the last fails during the backward pass

### ISSUE THREAD

**Issue by felix-schneider** [pytorch/pytorch#30572]
## 🐛 Bug

When training models in FP16, it is typical to run softmax operations (such as within attention) in FP32. It seems that when you run softmax on a dimension other than the last dimension of the tensor, the backward pass fails.

## To Reproduce

```python
import torch
import torch.nn.functional as F

a = torch.rand(2, 2, 2, 2, requires_grad=True).half().cuda()
b = F.softmax(a, dim=-1, dtype=torch.float32)[0, 0, 0, 0]
c = F.softmax(a, dim=1, dtype=torch.float32)[0, 0, 0, 0]

b.backward(retain_graph=True)
c.backward(retain_graph=True)
```

Output is
```
Traceback (most recent call last):
  File "softmax_bug.py", line 9, in <module>
    c.backward(retain_graph=True)
  File "---/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "---/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: expected scalar type Float but found Half
```
Note that `b.backward` does not fail.

## Expected behavior

No exception

## Environment

```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.2.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX
GPU 4: TITAN RTX
GPU 5: TITAN RTX

Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL @albanD @gqchen @ngimel

**Comment by mruberry** [comment]
Thanks for reporting this issue! I checked and this is still occurring. 

@csarofeen @albanD

**Comment by albanD** [comment]
I can't reproduce this on CPU. @felix-schneider does that work on CPU for you?

**Comment by felix-schneider** [comment]
No, the problem needs these specific circumstances:
1) Half-precision tensor
2) On GPU
3) Running softmax
4) On a dimension other than the last
5) With `dtype=torch.float32` NOT by casting to `float()` first
6) Run backward

**Comment by albanD** [comment]
According to @ngimel  this is a buggy half prevision code in the CUDA implementation. Is someone fixing it?

**Comment by zasdfgbnm** [comment]
@albanD I will work on this
