### ISSUE TITLE
gradients of symeig not correct and gradcheck fails

### ISSUE THREAD

**Issue by michael-koller-91** [pytorch/pytorch#30578]
## 🐛 Bug

The off-diagonal elements of torch.symeig's gradients are off by a factor of 2. Further, checking the gradients with torch.autograd.gradcheck gives a RuntimeError.

## To Reproduce

The following code computes an eigenvalue decomposition of a symmetric matrix and corresponding derivatives with two different approaches. One approach uses torch.symeig and backward() to compute the gradient. The second approach uses torch.symeig and numerical differentiation to compute the gradient.
Further, torch.autograd.gradcheck is called to test torch.symeig and it gives a RuntimeError.

```
import numpy as np
import torch
from torch.autograd import Variable


def get_numerical_gradient(func, x, epsilon):
    """
    Numerical differentiation.
    If e_ij is the matrix with 1 in row i, column j and 0 elsewhere,
    get_numerical_gradient computes
        g_ij = func(x + epsilon*e_ij) - func(x - epsilon*e_ij))/(2*epsilon)
    for all i and j and returns the gradient matrix constructed from
    the g_ij.
    """
    g = np.zeros_like(x)
    for i in range(0, x.shape[0]):
        for j in range(0, x.shape[1]):
            e = np.zeros_like(x)
            e[i, j] = 1.0
            g[i, j] = (func(x+epsilon*e) - func(x-epsilon*e)) / (2*epsilon)
    return g


#
# The following two functions perform the same calculation: a sum over all
# eigenvalues and eigenvectors
#
def sum_val_plus_vec_torch(x):
    d, u = torch.symeig(x, eigenvectors=True)
    return torch.sum(d) + torch.sum(u)


# This version is used for numerical differentiation.
def sum_val_plus_vec_np(x):
    x_torch = Variable(torch.from_numpy(x.copy()))
    s = sum_val_plus_vec_torch(x_torch)
    return s.data.numpy()


# for numerical gradient
epsilon = 1e-6
# random symmetric matrix
dim = 2
M = np.random.randn(dim, dim)
M = M + M.T

# numerical gradient
grad_num = get_numerical_gradient(sum_val_plus_vec_np, M, epsilon)

# torch gradient
M_torch = Variable(torch.from_numpy(M.copy()), requires_grad=True)
sum_torch = sum_val_plus_vec_torch(M_torch)
sum_torch.backward()
grad_torch = M_torch.grad.data.numpy()

print('-'*10, 'numerical differentiation')
print(grad_num)
print('-'*10, 'torch')
print(grad_torch)

M_torch = Variable(torch.from_numpy(M.copy()), requires_grad=True)
print(torch.autograd.gradcheck(sum_val_plus_vec_torch, M_torch))
```
This prints
```
---------- numerical differentiation
[[1.00980921 0.08135323]
 [0.         0.99019079]]
---------- torch
[[1.00980921 0.04067662]
 [0.04067662 0.99019079]]
Traceback (most recent call last):
  File "grad_test.py", line 62, in <module>
    print(torch.autograd.gradcheck(sum_val_plus_vec_torch, M_torch))
  File "C:\Users\abc\Miniconda3\envs\main\lib\site-packages\torch\autograd\gradcheck.py", line
289, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "C:\Users\abc\Miniconda3\envs\main\lib\site-packages\torch\autograd\gradcheck.py", line
227, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[1.0098],
        [0.0814],
        [0.0000],
        [0.9902]], dtype=torch.float64)
analytical:tensor([[1.0098],
        [0.0407],
        [0.0407],
        [0.9902]], dtype=torch.float64
```
Some observations can be made:
First, since numerical differentiation is not implemented to take the symmetry of the matrix M into account, only an upper triangular matrix is computed. This is true for both the version implemented above and for the error message of torch.autograd.gradcheck. The two numerical differentiation versions are identical.
Second, the off-diagonal elements computed via backward() and those computed via numerical differentiation differ by a factor of 2.

## Expected behavior

The derivative computed via backward() should (at least in the upper triangular part) be identical to the numerical differentiation gradient. The reason why this is not the case is that the structure of inputs to torch.symeig (i.e., the symmetry of the inputs) is not taken into account in the backward pass of torch.symeig. Derivatives of functions of symmetric matrices need some extra care, as equation (138) in the [matrix cookbook](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf) highlights. As far as I can tell, only the [line of code which computes the return value of symeig's backward()](https://github.com/pytorch/pytorch/blob/dd52f50fc85e6710f020936c1fc5f14673508350/tools/autograd/templates/Functions.cpp#L1797) needs to be modified.
To demonstrate this, the following implements a custom gradient of symeig where the backward pass return value is changed slightly.
```
class SymEig(torch.autograd.Function):
    """
    This modified version of torch.symeig has different gradients.
    The forward pass is not modified.
    """
    @staticmethod
    def forward(ctx, in_tensor):
        d, u = torch.symeig(in_tensor, eigenvectors=True)
        ctx.save_for_backward(d, u)
        return d, u

    @staticmethod
    def backward(ctx, *grad_output):
        gd, gu = grad_output
        d, u = ctx.saved_tensors
        grad_input = None

        ut = u.transpose(-2, -1)

        F = d.unsqueeze(-2) - d.unsqueeze(-1)
        F.diagonal(0, -2, -1).fill_(float('inf'))
        F.pow_(-1)

        F.mul_(torch.matmul(ut, gu))

        grad_input = torch.matmul(
            u,
            torch.matmul(torch.diag_embed(gd) + F, ut)
        )
        # until this point, no modification
        #
        # since A is symmetric, use equation (138) matrix cookbook
        return grad_input + grad_input.transpose(-2, -1) \
            - torch.diag_embed(grad_input.diagonal(dim1=-2, dim2=-1))


# test modified torch gradient
def sum_val_plus_vec_torch_modified(x):
    d, u = SymEig.apply(x)
    return torch.sum(d) + torch.sum(u)


M_torch_modified = Variable(torch.from_numpy(M.copy()), requires_grad=True)
sum_torch_modified = sum_val_plus_vec_torch_modified(M_torch_modified)
sum_torch_modified.backward()
grad_torch_modified = M_torch_modified.grad.data.numpy()

print('-'*10, 'torch modified')
print(grad_torch_modified)
```
This prints
```
---------- torch modified
[[1.00980921 0.08135323]
 [0.08135323 0.99019079]]
```
This agrees with numerical differentiation.

So, should the implementation of symeig_backward be changed?

## Environment

Output from environment collection script:
```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.3.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] pytorch                   1.3.1           py3.7_cuda101_cudnn7_0    pytorch
```

cc @vishwakftw @SsnL @jianyuh

**Comment by SsnL** [comment]
There is ambiguity here since symeig is only defined for symmetrical matrices (So you can view the result being computed by using either triangular part or both). It is more intuitive to return a symmetrical gradient, so that change was made. Context: https://github.com/pytorch/pytorch/issues/22807

**Comment by michael-koller-91** [comment]
Yes, the gradient needs to be symmetric. For symeig, is has been made symmetric in #23018. However, according to, e.g., equation (138) in the [matrix cookbook](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf), the chosen way of symmetrization is only almost correct. That's why I opened this issue.

**Comment by fmassa** [comment]
I think this reasoning makes sense. If @vishwakftw agrees, let's change the derivative of `symeig` according to @michael-koller-91 comment

**Comment by githubgregersen** [comment]
Im not sure how to reconcile the above with the following (creating a symmetric matrix by broadcasting a single vector)
```
def get_numerical_gradient_v(func, x, epsilon):
    assert len(x.shape)==1
    g = np.zeros(x.shape)
    for i in range(0, x.shape[0]):
        e = np.zeros(x.shape)
        e[i] = 1.0
        g[i] = (func(x+epsilon*e) - func(x-epsilon*e)) / (2*epsilon)
    return g

def symmetric_combine(v):
    n = 3.0
    M = (0.5*(v[...,None]**n + v[None,...]**n)**(1/n))
    return M

def func_numpy(v):
    M = symmetric_combine(v)
    assert(M==M.T).all()
    d, u = np.linalg.eigh(M, UPLO="U")
    result = np.sum(d) + np.sum(u)
    return result

def func_torch(v, getgrad=False):
    M = symmetric_combine(v)
    assert (M == M.T).byte().all()
    d, u = torch.symeig(M, eigenvectors=True)
    result = torch.sum(d) + torch.sum(u)
    if getgrad:
        result.backward()
        return v.grad.data.numpy()
    return result

def func_torch_modified(v, getgrad=False):
    M = symmetric_combine(v)
    assert (M==M.T).byte().all()
    d, u = SymEig.apply(M)
    result = torch.sum(d) + torch.sum(u)
    if getgrad:
        result.backward()
        return v.grad.data.numpy()
    return result

np.random.seed(2020)
# for numerical gradient
epsilon = 1e-6
# random symmetric matrix will be (dim x dim)
dim = 3
p = np.random.random(dim) + 1.0

ngrad_numpy = get_numerical_gradient_v(func_numpy, p.copy(), epsilon)
ngrad_torch = get_numerical_gradient_v(func_torch, torch.tensor(p), epsilon)
ngrad_torch_mod = get_numerical_gradient_v(func_torch_modified, torch.tensor(p), epsilon)
grad_torch = func_torch(torch.tensor(p, requires_grad=True), True)
grad_torch_mod = func_torch_modified(torch.tensor(p, requires_grad=True), True)

print('-'*10, 'numpy numerical')
print(ngrad_numpy)
print('-'*10, 'torch numerical')
print(ngrad_torch)
print('-'*10, 'torch mod numerical')
print(ngrad_torch_mod)
print('-'*10, 'torch analytic')
print(grad_torch)
print('-'*10, 'torch mod analytic')
print(grad_torch_mod)


torch.autograd.gradcheck(func_torch, torch.tensor(p, requires_grad=True))
torch.autograd.gradcheck(func_torch_modified, torch.tensor(p, requires_grad=True))
```
Which produces:
```---------- numpy numerical
[0.48886428 0.80186956 0.7265407 ]
---------- torch numerical
[0.48886428 0.80186956 0.7265407 ]
---------- torch mod numerical
[0.48886428 0.80186956 0.7265407 ]
---------- torch analytic
[0.48886428 0.80186956 0.7265407 ]
---------- torch mod analytic
[0.67149538 0.78753635 0.68563576]

Traceback (most recent call last):
  File "./test_symeig.py", line 117, in <module>
    torch.autograd.gradcheck(func_torch_modified, torch.tensor(p, requires_grad=True))
  File "/gdn/centos7/0001/x3/prefixes/pytorch/1.4.0-cuda10-01c7__37694f0bcc63/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 289, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/gdn/centos7/0001/x3/prefixes/pytorch/1.4.0-cuda10-01c7__37694f0bcc63/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 227, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[0.4889],
        [0.8019],
        [0.7265]], dtype=torch.float64)
analytical:tensor([[0.6715],
        [0.7875],
        [0.6856]], dtype=torch.float64)
```

IE, the current implementation produces the correct numerical gradients, while the SymEig class in the first post does not.

**Comment by githubgregersen** [comment]
Taking it one step further, and directly specifying the unique N*(N+1)/2 parameters of the symmetric matrix (and reusing the rest of the code from update#3):
```
DIM = 3

def build_symmetric(M, v):
    idiag = np.diag_indices(DIM)
    iupper = np.triu_indices(DIM,1)
    M[idiag] = v[:DIM]
    M[iupper] = v[DIM:]
    M.T[iupper] = v[DIM:]
    return M

def func_numpy(v):
    M = np.empty((DIM,DIM))
    build_symmetric(M, v)
    assert(M==M.T).all()
    d, u = np.linalg.eigh(M, UPLO="U")
    result = np.sum(d) + np.sum(u)
    return result

def func_torch(v, getgrad=False):
    M = torch.empty((DIM,DIM), dtype=torch.double)
    build_symmetric(M, v)
    assert (M == M.T).byte().all()
    d, u = torch.symeig(M, eigenvectors=True)
    result = torch.sum(d) + torch.sum(u)
    if getgrad:
        result.backward()
        return v.grad.data.numpy()
    return result

def func_torch_modified(v, getgrad=False):
    M = torch.empty((DIM,DIM), dtype=torch.double)
    build_symmetric(M, v)
    assert (M==M.T).byte().all()
    d, u = SymEig.apply(M)
    result = torch.sum(d) + torch.sum(u)
    if getgrad:
        result.backward()
        return v.grad.data.numpy()
    return result

np.random.seed(2020)
# for numerical gradient
epsilon = 1e-6
p = np.random.random(int(DIM*(DIM+1)/2)) + 1.0
```
produces
```
---------- numpy numerical
[ 0.62609536  1.17912154  1.1947831  -0.11645342  0.01913861  0.19356785]
---------- torch numerical
[ 0.62609536  1.17912154  1.1947831  -0.11645342  0.01913861  0.19356785]
---------- torch mod numerical
[ 0.62609536  1.17912154  1.1947831  -0.11645342  0.01913861  0.19356785]
---------- torch analytic
[ 0.62609536  1.17912154  1.1947831  -0.11645342  0.01913861  0.19356785]
---------- torch mod analytic
[ 0.62609536  1.17912154  1.1947831  -0.23290684  0.03827722  0.38713569]
```
So it looks like the current implementation is correct.

**Comment by michael-koller-91** [comment]
Thank you for your investigation. I think the surprising result might be due to the fact that by using the build_symmetric function, one effectively has not ```DIM*DIM``` variables but ```(DIM*(DIM+1)/2)``` which leads to a wrong result. This is reflected by the fact that the gradient in your last post has only dimension 6 instead of 9.

If we explicitly create a matrix with ```DIM*DIM``` independent variables, the result is consistent again. After running your code, I ran the following:
```
# copied from your code
M = torch.empty((DIM, DIM), dtype=torch.double)
M = build_symmetric(M, torch.tensor(p.copy()))
# matrix with DIM*DIM variables
MM = torch.autograd.Variable(M, requires_grad=True)
assert (MM == MM.T).byte().all()
d, u = SymEig.apply(MM)
result = torch.sum(d) + torch.sum(u)
result.backward()

print('-'*10, 'torch mod analytic')
print(MM.grad.data.numpy())
```
This prints
```
---------- torch mod analytic
[[ 0.62609536 -0.11645342  0.01913861]
 [-0.11645342  1.17912154  0.19356785]
 [ 0.01913861  0.19356785  1.1947831 ]]
```
This is consistent with the gradients you posted.

**Comment by githubgregersen** [comment]
This paper says the gradient in the matrix cookbook is wrong (ie, one can not form the symmetric gradient Gsym(A) via G(A)+G(A)^T - diag(G(A) )

What is the gradient of a scalar function of a symmetric matrix? 
https://arxiv.org/pdf/1911.06491.pdf

**Comment by michael-koller-91** [comment]
Nice, thank you for the link to this paper! That's the solution of the issue. So, in summary, all sources which use G(A) + G(A)^T - diag(G(A)) are not correct. Instead, (G(A) + G(A)^T) / 2 is the correct formula. Since the latest version implements exactly this, everything is fine.

Thanks for the discussion.
