### ISSUE TITLE
[jit] `@ignore` methods are broken

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#30625]
```python
class MyModule(nn.Module):
    def forward(self):
        pass

    @torch.jit.ignore
    def call_np(self) -> int:
        return np.random.choice(2, p=[.95,.05])

    @torch.jit.export
    def func(self):
        done = self.call_np()
        print (done)

scripted_module = torch.jit.script(MyModule())
print(scripted_module.func.graph)
scripted_module.func()
```

should work but outputs

```
Traceback (most recent call last):
  File "../test.py", line 190, in <module>
    scripted_module = torch.jit.script(MyModule())
  File "/home/davidriazati/dev/pytorch/torch/jit/__init__.py", line 1250, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/home/davidriazati/dev/pytorch/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/davidriazati/dev/pytorch/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/home/davidriazati/dev/pytorch/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/home/davidriazati/dev/pytorch/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 

(__torch__.MyModule self, Tensor 0) -> (int 0):
Argument 0 not provided.
:
  File "../test.py", line 187
    @torch.jit.export
    def func(self):
        done = self.call_np()
               ~~~~~~~~~~~~ <--- HERE
        print (done)
```

cc @suo

**Comment by eellison** [comment]
Isn't this the same issue as https://github.com/pytorch/pytorch/issues/28537 ?

**Comment by eellison** [comment]
Closing because I think this is the same issue. reopen if you'd like.

**Comment by driazati** [comment]
Keeping open to save the test case

**Comment by eellison** [comment]
This works now because of https://github.com/pytorch/pytorch/pull/29300
