### ISSUE TITLE
TestTorchDeviceTypeXLA: Could not start gRPC server

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#30717]
Excerpt from [this CircleCI build](https://circleci.com/gh/pytorch/pytorch/3768299) on the `master` branch:

```
Dec 04 01:51:20 E1204 01:51:20.635135781     187 server_chttp2.cc:40]        {"created":"@1575424280.635041133","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":348,"referenced_errors":[{"created":"@1575424280.635039519","description":"Failed to add any wildcard listeners","file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":324,"referenced_errors":[{"created":"@1575424280.635019167","description":"Address family not supported by protocol","errno":97,"file":"external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":379,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:40934"},{"created":"@1575424280.635038986","description":"Unable to configure socket","fd":7,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1575424280.635035502","description":"Address already in use","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
Dec 04 01:51:20 2019-12-04 01:51:20.635182: E tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:509] Unknown: Could not start gRPC server
Dec 04 01:51:20 2019-12-04 01:51:20.637020: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: tensorflow::NewServer(server_def, &server_) == ::tensorflow::Status::OK() (Unknown: Could not start gRPC server vs. OK)
Dec 04 01:51:20 
Dec 04 01:51:20 Running tests...
Dec 04 01:51:20 ----------------------------------------------------------------------
Dec 04 01:51:20 
Dec 04 01:51:20 ======================================================================
Dec 04 01:51:20 ERROR [0.000s]: setUpClass (__main__.TestTorchDeviceTypeXLA)
Dec 04 01:51:20 ----------------------------------------------------------------------
Dec 04 01:51:20 Traceback (most recent call last):
Dec 04 01:51:20   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 326, in setUpClass
Dec 04 01:51:20     cls.primary_device = str(xm.xla_device())
Dec 04 01:51:20   File "/opt/conda/lib/python3.6/site-packages/torch_xla-0.8-py3.6-linux-x86_64.egg/torch_xla/core/xla_model.py", line 142, in xla_device
Dec 04 01:51:20     devices = get_xla_supported_devices(devkind=devkind)
Dec 04 01:51:20   File "/opt/conda/lib/python3.6/site-packages/torch_xla-0.8-py3.6-linux-x86_64.egg/torch_xla/core/xla_model.py", line 42, in get_xla_supported_devices
Dec 04 01:51:20     xla_devices = torch_xla._XLAC._xla_get_devices()
Dec 04 01:51:20 RuntimeError: tensorflow/compiler/xla/xla_client/xrt_local_service.cc:56 : Check failed: tensorflow::NewServer(server_def, &server_) == ::tensorflow::Status::OK() (Unknown: Could not start gRPC server vs. OK)
```

cc @ezyang @gchanan @zou3519 @ailzhang

**Comment by kostmo** [comment]
Another instance observed here: https://circleci.com/gh/pytorch/pytorch/3785488

**Comment by ailzhang** [comment]
This "address already in use" error happens when port 40934 is in use and we want to start another gRPC server listening to it. IIRC we don't overlap builds on a single machine so this could probably caused by a incorrectly decommission machine  from CircleCI. 
We can fix it by killing whatever is listening on 40934 before build - if we are certain builds are separated, or randomize the port. 
I'll lower the priority but fix it later.
