### ISSUE TITLE
Multithreaded Generator Error when in Debug

### ISSUE THREAD

**Issue by kleingeo** [pytorch/pytorch#30736]
I am using PyCharm (newest version, 2019.3) with pytorch and have been testing the code in debug mode. In debug mode when using the ```DataLoader``` from ```torch.utils.data``` with ```num_workers > 0``` the code breaks and returns the error below. However, when training not in debug mode there isn't any problem. I am also using the newest pytorch version, 1.3.1+cu92.  The generator gets passed the dataset below, which does not have any pytorch functions in it (no augmentation or anything fancy like that).

```python
import pandas as pd
import numpy as np
from Dataset.BaseDataset import BaseDataset

from torch.utils.data import Dataset
class SpineDataSet(Dataset):

    def __init__(self, params, df, spine_main_path, seg_main_path, isTrain=False):
        """
        Parameters
        ----------
        params : Parameters.ParameterBuilder.Parameters
            Parameters for model, training and dataset
        df : pd.Dataframe
            Dataframe used to track samples
        spine_main_path : str
            String for the location of the samples
        seg_main_path : str
            String for the location of the labels
        """
        self.df = df
        self.params = params
        self.isTrain = isTrain
        self.spine_main_path = spine_main_path
        self.seg_main_path = seg_main_path

        self.seg_filename_list = df['seg_filename'].to_list()
        self.spine_filename_list = df['spine_filename'].to_list()

        from ImageUtils.CropPadImg import CropPadImg

        self.crop_pad = CropPadImg(sample_size=self.params.sample_size,
                                   translation=False,
                                   centered=True)

    def __len__(self):
        """
        Length of total number of samples
        """
        return len(self.seg_filename_list)

    def __getitem__(self, sample_idx):
        """
        Generates a single sample
        """
        spine_sample = self.spine_filename_list[sample_idx]
        seg_sample = self.seg_filename_list[sample_idx]

        x_data = np.load(self.spine_main_path + '/' + spine_sample).astype(np.float32)
        y_data = np.load(self.seg_main_path + '/' + seg_sample).astype(np.uint8)

        x_data = np.where(x_data < -1024, -1024, x_data)
        x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min()) * 255
        x_data, y_data = self.crop_pad([x_data, y_data])

        x_data = np.expand_dims(x_data, axis=0)
        y_data = np.expand_dims(y_data, axis=0)

        x_data = x_data.astype(np.float32)
        y_data = y_data.astype(np.float32)

        sample = {'image': x_data,
                  'label': y_data}
        return sample
```

```python
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/geklein/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Traceback (most recent call last):
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/geklein/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Traceback (most recent call last):
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/geklein/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Traceback (most recent call last):
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/geklein/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Traceback (most recent call last):
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/geklein/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Traceback (most recent call last):
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/geklein/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/geklein/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/multiprocessing/util.py", line 322, in _exit_function
    p.join()
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/multiprocessing/util.py", line 322, in _exit_function
    p.join()
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Traceback (most recent call last):
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 12040) is killed by signal: Terminated. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geklein/miniconda3/envs/main_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 12040) exited unexpectedly
```

**Comment by gchanan** [comment]
I believe this may be https://youtrack.jetbrains.com/issue/PY-39242?_ga=2.228724636.1685273318.1575652274-333064415.1575652274 and doesn't look related to PyTorch.
