### ISSUE TITLE
TestAutogradDeviceTypeCUDA.test_to_sparse_cuda doesn't work

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#30820]
After applying https://github.com/pytorch/pytorch/pull/30821/ you will get the error for this test:

```
======================================================================                                                                                                      
ERROR: test_to_sparse_cuda (__main__.TestAutogradDeviceTypeCUDA)                                                                                                            
----------------------------------------------------------------------                                                                                                      
Traceback (most recent call last):                                                                                                                                          
  File "/data/users/ezyang/pytorch-tmp/test/common_utils.py", line 631, in wrapper                                                                                           
    method(*args, **kwargs)                                                                                                                                                 
  File "/data/users/ezyang/pytorch-tmp/test/common_utils.py", line 631, in wrapper                                                                                          
    method(*args, **kwargs)                                                                                                                                                  
  File "/data/users/ezyang/pytorch-tmp/test/common_device_type.py", line 179, in instantiated_test                                                                          
    return test(self, device_arg)                                                                                                                                            
  File "test/test_autograd.py", line 3538, in do_test                                                                                                                       
    check(name)                                                                                                                                                              
  File "test/test_autograd.py", line 3463, in check                                                                                                                         
    output_variable, (self_variable,) + args_variable)                                                                                                                       
  File "test/test_autograd.py", line 3391, in run_grad_and_gradgrad_checks                                                                                                   
    test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))                                                                    
  File "/data/users/ezyang/pytorch-tmp/torch/autograd/gradcheck.py", line 404, in gradgradcheck                                                                             
    nondet_tol=nondet_tol)                                                                                                                                                  
  File "/data/users/ezyang/pytorch-tmp/torch/autograd/gradcheck.py", line 259, in gradcheck                                                                                 
    func_out = func(*tupled_inputs)                                                                                                                                         
  File "/data/users/ezyang/pytorch-tmp/torch/autograd/gradcheck.py", line 400, in new_func                                                                                  
    grad_inputs = torch.autograd.grad(outputs, input_args, grad_outputs, create_graph=True)                                                                                 
  File "/data/users/ezyang/pytorch-tmp/torch/autograd/__init__.py", line 157, in grad                                                                                       
    inputs, allow_unused)                                                                                                                                                   
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.    
                                                                                                                                                                             
----------------------------------------------------------------------  
```

I tried reproducing without gradcheck but was unable to:

```
import torch
from torch.autograd import Variable

x = Variable(torch.randn(5, 5, dtype=torch.double, device='cuda'), requires_grad=True)
y = x.to_sparse().to_dense()
torch.autograd.grad(y, x, torch.randn(5, 5, dtype=torch.double, device='cuda', requires_grad=True), create_graph=True)
```

So I am not too sure what is going on here.

cc @ezyang @gchanan @zou3519 @ngimel @vincentqb

**Comment by gchanan** [comment]
think it's worth discussing if it's high priority.
