### ISSUE TITLE
error occures when trying to import torch, "ImportError: cannot import name 'ClassType'"

### ISSUE THREAD

**Issue by Simona787** [pytorch/pytorch#30862]
## 🐛 Bug
`import torch`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/__init__.py", line 307, in <module>
    import torch.nn.quantized
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/nn/quantized/__init__.py", line 6, in <module>
    from .modules import *  # noqa: F401
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/nn/quantized/modules/__init__.py", line 5, in <module>
    from .activation import ReLU
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/nn/quantized/modules/activation.py", line 6, in <module>
    from .. import functional as F
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/nn/quantized/functional.py", line 8, in <module>
    from torch._ops import ops
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/_ops.py", line 9, in <module>
    import torch.jit
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/jit/__init__.py", line 7, in <module>
    import torch.jit.annotations
  File "/home/**/py3env_pytorch_1.2/lib/python3.6/site-packages/torch/jit/annotations.py", line 9, in <module>
    from torch._C import TensorType, TupleType, FloatType, IntType, \
ImportError: cannot import name 'ClassType'

## To Reproduce

1.pip3 install torch
2.python
3.import torch

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.0
 - OS (e.g., Linux):ubuntu18.4
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:python3.6
 - CUDA/cuDNN version:10.01
 - GPU models and configuration:
 - Any other relevant information:

**Comment by gchanan** [comment]
can you try with version 1.3.1?

**Comment by gchanan** [comment]
this is almost certainly an installation issue on your end; otherwise a number of people would have reported this.  Can you also try reinstalling from scratch?

Please reopen if you try reinstalling and it doesn't work.

**Comment by Simona787** [comment]
> this is almost certainly an installation issue on your end; otherwise a number of people would have reported this. Can you also try reinstalling from scratch?
> 
> Please reopen if you try reinstalling and it doesn't work.


Yes, I've installed it from scratch,but still get the same problem.
I even try to install from source, And here occures another error
![2019-12-07 23-35-35屏幕截图](https://user-images.githubusercontent.com/17819275/70377037-85b92880-194a-11ea-83f1-d6782e7d34ea.png)

**Comment by Simona787** [comment]
> this is almost certainly an installation issue on your end; otherwise a number of people would have reported this. Can you also try reinstalling from scratch?
> 
> Please reopen if you try reinstalling and it doesn't work.

Yes, I've installed it from scratch,but still get the same problem.
I even try to install it from source, but here occures another error
![2019-12-07 23-39-37屏幕截图](https://user-images.githubusercontent.com/17819275/70377068-de88c100-194a-11ea-9d09-da6ee2fae43e.png)

**Comment by bencrts** [comment]
I had a similar issue with the error message: ImportError: cannot import name 'nan'. The fix was to do: 

`pip3 uninstall torch`

multiple times (3, in my case) untill the message `Cannot uninstall requirement torch, not installed` appeared. After this, a fresh install via:

`pip3 install torch==0.3.1`

seemed to fix the problem.
