### ISSUE TITLE
 bert model encoding error on python3.6.8

### ISSUE THREAD

**Issue by gentelyang** [pytorch/pytorch#30938]
data_config: {'world_size': 1, 'rank': -1, 'persist_state': 0, 'lazy': False, 'transpose': False, 'data_set_type': 'supervised', 'seq_length': 256, 'eval_seq_length': 256, 'samples_per_shard': 100}
configuring data
Traceback (most recent call last):
  File "pretrain_bert.py", line 490, in <module>
    main()
  File "pretrain_bert.py", line 417, in main
    (train_data, val_data, test_data), tokenizer = data_config.apply(args)
  File "/ssd2/bert1/Megatron-LM/configure_data.py", line 33, in apply
    return make_loaders(args)
  File "/ssd2/bert1/Megatron-LM/configure_data.py", line 166, in make_loaders
    train, tokenizer = data_utils.make_dataset(**data_set_args)
  File "/ssd2/bert1/Megatron-LM/data_utils/__init__.py", line 93, in make_dataset
    datasets = [get_dataset_from_path(p) for p in path]
  File "/ssd2//bert1/Megatron-LM/data_utils/__init__.py", line 93, in <listcomp>
    datasets = [get_dataset_from_path(p) for p in path]
  File "/ssd2/bert1/Megatron-LM/data_utils/__init__.py", line 82, in get_dataset_from_path
    delim=delim, drop_unlabeled=drop_unlabeled, loose_json=loose)
  File "/ssd2/bert1/Megatron-LM/data_utils/__init__.py", line 50, in get_dataset
    text = json_dataset(path, **kwargs)
  File "/ssd2/bert1/Megatron-LM/data_utils/datasets.py", line 327, in __init__
    for j in self.load_json_stream(self.path):
  File "/ssd2/bert1/Megatron-LM/data_utils/datasets.py", line 436, in load_json_stream
    for j in generator:
  File "/ssd2/bert1/Megatron-LM/data_utils/datasets.py", line 432, in gen_helper
    for row in f:
  File "/ssd2/bert1/Megatron-LM/bert_env/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5507: ordinal not in range(128)

**Comment by SsnL** [comment]
The error is not related to pytorch.

I would suggest try loading with other encodings like uft-8.
