### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Neeyan** [pytorch/pytorch#30940]
## ❓ Questions and Help

I installed pytorch by anaconda in a new created environment. Then I followed instructions from https://pypi.org/project/torchvision/. 
I can use torchvision in CPU, but in GPU always goes wrong. And I read the list, when I run the _CUDA development tips_ I got the same error. 
system: win10; cuda vision: 10.0

**This is the code from the forum:**
`import torch
import time
size = 128*512
nrep = 100
nbytes_read_write = 4 # this is number of bytes read + written by a kernel. Change this to fit your kernel.

for i in range(10):
    a=torch.Tensor(size).cuda().uniform_()
    torch.cuda.synchronize()
    start = time.time()
    # dry run to alloc
    out = a.uniform_()
    torch.cuda.synchronize()
    start = time.time()
    for i in range(nrep):
      out = a.uniform_()
    torch.cuda.synchronize()
    end = time.time()
    timec = (end-start)/nrep
    print("uniform, size, elements", size, "forward", timec, "bandwidth (GB/s)", size*(nbytes_read_write)*1e-9/timec)
    size *=2`

**This is the error description:**
`runfile('C:/Users/CUGID/Desktop/untitled0test.py', wdir='C:/Users/CUGID/Desktop')
Traceback (most recent call last):

  File "<ipython-input-1-458cdf791a0d>", line 1, in <module>
    runfile('C:/Users/CUGID/Desktop/untitled0test.py', wdir='C:/Users/CUGID/Desktop')

  File "C:\Users\CUGID\Anaconda3\envs\pytorch\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\CUGID\Anaconda3\envs\pytorch\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/CUGID/Desktop/untitled0test.py", line 15, in <module>
    a=torch.Tensor(size).cuda().uniform_()

  File "C:\Users\CUGID\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()

  File "C:\Users\CUGID\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")

AssertionError: Torch not compiled with CUDA enabled`

**Comment by peterjc123** [comment]
Please install a CUDA version of PyTorch and TorchVision according to the steps on https://pytorch.org.
