### ISSUE TITLE
RuntimeError: has_marked_unused_parameters_ INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1570910687650/work/torch/csrc/distributed/c10d/reducer.cpp:290, please report a bug to PyTorch.

### ISSUE THREAD

**Issue by jcw521** [pytorch/pytorch#31035]
## 🐛 Bug

I want to use distributed method on pytorch but I got a following error message.
```
Traceback (most recent call last):
  File "main.py", line 325, in <module>
    main()
  File "main.py", line 120, in main
    mp.spawn(train, nprocs=args.gpu_num, args=(args, encoder, train_data, dev_data))
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jcw/VAIRLsentence/main.py", line 228, in train
    train_actor_critic(args, env, actor, critic, env_optim, actor_optim, critic_optim, leaners_set)
  File "/home/jcw/VAIRLsentence/Scheme.py", line 201, in train_actor_critic
    loss.backward(retain_graph=True)
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: has_marked_unused_parameters_ INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1570910687650/work/torch/csrc/distributed/c10d/reducer.cpp:290, please report a bug to PyTorch.
```
It seems like because of loss-backward functions.
The weird thing is that the loss-backward functions of other models in front of this error message are worked well.

## To Reproduce
main.py
```
def main():
    args = parse_arg()
    
    #call encoder & check voca size
    encoder = Encoder(args)
    args.voca_size = encoder.get_vocab_size()
    _, args.action_size = DtoB(args.voca_size, None)
    print('INFO: {} voca size & {} action size'.format(args.voca_size, args.action_size))
    
    #call dataset
    io = DataIO(args)
    io.load_wiki()
    train_data, dev_data, test_data = io.build_train_dev_test(suffle=True)
    print('INFO: build {} train data, {} valid data & {} test data'.format(len(train_data), len(dev_data), len(test_data)))
    train_data, dev_data, test_data = DatesetForLoader(train_data), DatesetForLoader(dev_data), DatesetForLoader(test_data)
    
    #cuda process
    args.multi_gpu = True if args.device and args.gpu_num > 1 else False
    
    if args.multi_gpu:
        mp.set_start_method('spawn')
        args.world_size = args.gpu_num * args.world_size
        args.workers = int((args.workers + args.gpu_num - 1) / args.gpu_num)
        
        mp.spawn(train, nprocs=args.gpu_num, args=(args, encoder, train_data, dev_data))
    else:
        train(None, args, encoder, train_data, dev_data)
    
    if args.multi_gpu:
        mp.spawn(train, nprocs=args.gpu_num, args=(args, io, encoder, test_data))
    else:
        test(None, args, io, encoder, test_data)
    
    return

def train(gpu_id, args, encoder, train_data, dev_data=None):
    
    if gpu_id is not None:
        args.verbose = False
        args.gpu_id = gpu_id
        torch.cuda.set_device(args.gpu_id)
        args.rank = args.rank * args.gpu_num + args.gpu_id
        
    #build models
    env = Environment(args)
    vdb = VDB(args)
    actor = Actor(args)
    critic = Critic(args)
    
    #previous trained model
    if args.load_model is not None:
        saved_ckpt_path = os.path.join(args.cur_path, 'save_model', str(args.load_model))
        ckpt = torch.load(saved_ckpt_path)
        
        env.load_state_dict(ckpt['env'])
        vdb.load_state_dict(ckpt['vdb'])
        actor.load_state_dict(ckpt['actor'])
        critic.load_state_dict(ckpt['critic'])
    
    #define optimization
    env_optim = optim.Adam(env.parameters(), lr=args.learning_rate)
    vdb_optim = optim.Adam(vdb.parameters(), lr=args.learning_rate)
    actor_optim = optim.Adam(actor.parameters(), lr=args.learning_rate)
    critic_optim = optim.Adam(critic.parameters(), lr=args.learning_rate, weight_decay=args.l2_rate)
    print('INFO: model constructions are finished')
    
    if args.device:
        print('INFO: activate CUDA process')
        if args.multi_gpu:
            
            dist.init_process_group(backend='nccl',
                                    init_method=args.init_method,
                                    world_size=args.world_size,
                                    rank=args.rank)
            
            env.cuda(args.gpu_id), actor.cuda(args.gpu_id), critic.cuda(args.gpu_id), vdb.cuda(args.gpu_id)
            
            env = DistributedDataParallel(env, device_ids=[args.gpu_id])
            actor = DistributedDataParallel(actor, device_ids=[args.gpu_id])
            critic = DistributedDataParallel(critic, device_ids=[args.gpu_id])
            vdb = DistributedDataParallel(vdb, device_ids=[args.gpu_id])
            
            print('INFO: multi-gpu process on {} gpu'.format(args.gpu_id))
        else:
            env.cuda(), actor.cuda(), critic.cuda(), vdb.cuda()
    else:
        print('INFO: activate CPU process')
        
    if args.multi_gpu:
        train_sampler = DistributedSampler(train_data)
        train_loader = DataLoader(train_data, batch_size=args.ppo_update_num, num_workers=args.workers, pin_memory=True, sampler=train_sampler)
        
        if dev_data is not None: 
            dev_sampler = DistributedSampler(dev_data)
            dev_loader = DataLoader(dev_data, batch_size=args.ppo_update_num, num_workers=args.workers, pin_memory=True, sampler=dev_sampler)
    else:
        train_loader = DataLoader(train_data, batch_size=args.ppo_update_num)
        
        if dev_data is not None:
            dev_loader = DataLoader(dev_data, batch_size=args.ppo_update_num)

    
    leaners_set, experts_set = [], []
    train_discrim_flag = True
    
    cnt, prev_l_len, prev_e_len = 0, 0, 0
    for epoch in range(args.epoch):
        
        for idx, samples in enumerate(train_loader):
            start_time = time.time()
            
            #demonstrate expert & keywords
            key_set = expert_simulation(args, encoder, env, samples, experts_set)
            
            #simulate sentence generation
            _ = leaner_simulation(args, encoder, env, actor, vdb, key_set, leaners_set)
            
            #adjust memory size & delete old pairs
            print("INFO: {} leaner set added, {} expert set added".format(len(leaners_set) - prev_l_len, len(experts_set) - prev_e_len))
            while len(leaners_set) > args.memory_maxlen:
                del leaners_set[0]
            while len(experts_set) > args.memory_maxlen:
                del experts_set[0]
            prev_l_len, prev_e_len = len(leaners_set), len(experts_set)
            
            if train_discrim_flag:
                expert_acc, learner_acc = train_vdb(args, env, vdb, env_optim, vdb_optim, leaners_set, experts_set, 0)
                print("INFO: Expert {:.2f}% & Leaner {:.2f}%".format(expert_acc * 100, learner_acc * 100))
                if expert_acc > args.suspend_accu_exp and learner_acc > args.suspend_accu_gen:
                    train_discrim_flag = False
            
            #train actor&critic
            train_actor_critic(args, env, actor, critic, env_optim, actor_optim, critic_optim, leaners_set)
            
            print("INFO: run {:.2f} seconds in {}\n".format(time.time() - start_time, cnt))
            cnt += 1
        
        if cnt % 100 == 0 and dev_loader is not None:
            print('INFO: validation..')
            rand_num = random.randrange(0, len(dev_loader))
            for jdx, dev_sample in enumerate(dev_loader):
                if not (jdx == rand_num):
                    continue
                dev_key = expert_simulation(args, encoder, env, dev_sample, [])
                gen_sen = leaner_simulation(args, encoder, env, actor, vdb, dev_key, [])
                avg_score = METEOR_score(dev_sample, gen_sen)
                print('INFO: average METEOR score {:.4f}'.format(avg_score))
            
            model_path = os.path.join(args.cur_path, args.save_path)
            if not os.path.isdir(model_path):
                os.makedirs(model_path)
            
            ckpt_path = os.path.join(model_path, str(epoch)+'_ckpt.pth.tar')
            torch.save({
                    'env': env.state_dict(),
                    'vdb': vdb.state_dict(),
                    'actor': actor.state_dict(),
                    'critic': critic.state_dict(),
                    'args': args,
                    'score': avg_score
                    }, ckpt_path)
        
    return
```
Scheme.py
```
def train_vdb(args, env, vdb, env_opt, vdb_opt, leaners, experts, beta):
    env.train(), vdb.train()
    
    #leaners set
    leaner_old_prev = torch.cat([h for h, p_a, a, c, r in leaners], dim=1) #tensor(layer num * memory len * dim)
    leaner_old_act = torch.cat([p_a for h, p_a, a, c, r in leaners], dim=0) #tensor(memory len, token id)
    leaner_actions = [a for h, p_a, a, c, r in leaners] #list(memory len) * tensor(1 * act size)
    
    #experts set
    expert_old_prev = torch.cat([h for h, p_a, a in experts], dim=1) #tensor(layer num * memory len * dim)
    expert_old_act = torch.cat([p_a for h, p_a, a in experts], dim=0) #tensor(memory len * token id)
    experts_actions = [a for h, p_a, a in experts] #list(memory len) * tensor(1 * act size)
    
    if args.device:
        leaner_old_prev, leaner_old_act = leaner_old_prev.cuda(), leaner_old_act.cuda()
        expert_old_prev, expert_old_act = expert_old_prev.cuda(), expert_old_act.cuda()
    
    criterion = torch.nn.BCELoss()
    
    if args.verbose:
        vdb_iter = tqdm(range(args.vdb_update_num), desc='updating VDB..', ncols=100, leave=True)
    else:
        vdb_iter = range(args.vdb_update_num)
        print('INFO: vdb update')
        
    for _ in vdb_iter:
        #leaners set
        leaners_states, _ = env(leaner_old_act, leaner_old_prev) #tensor(memory len * dim)
        leaners_states = list(torch.split(leaners_states, 1, dim=0)) #list(memory len) * tensor(1 * dim)
        leaner_pairs = [torch.cat([s, a.cuda() if args.device else a], dim=-1) for s, a in zip(leaners_states, leaner_actions)]
        leaner_pairs = torch.cat(leaner_pairs, dim=0) #tensor(memory len, dim + act size)
        
        #experts set
        experts_states, _ = env(expert_old_act, expert_old_prev) #tensor(memory len * dim)
        experts_states = list(torch.split(experts_states, 1, dim=0)) #list(memory len) * tensor(1 * dim)
        expert_pairs = [torch.cat([s, a.cuda() if args.device else a], dim=-1) for s, a in zip(experts_states, experts_actions)]
        expert_pairs = torch.cat(expert_pairs, dim=0) #tensor(memory len, dim + act size)
        
        learner, l_mu, l_logvar = vdb(leaner_pairs)
        expert, e_mu, e_logvar = vdb(expert_pairs)
        
        l_kld = kl_divergence(l_mu, l_logvar).mean()
        e_kld = kl_divergence(e_mu, e_logvar).mean()
        
        bottleneck_loss = 0.5 * (l_kld + e_kld) - args.i_c
        beta = max(0, beta + args.alpha_beta * bottleneck_loss).detach()
        
        ones = torch.ones((leaner_pairs.shape[0], 1))
        zeros = torch.zeros((expert_pairs.shape[0], 1))
        
        if args.device:
            ones, zeros = ones.cuda(), zeros.cuda()
        
        loss = criterion(learner, ones) + criterion(expert, zeros) + beta * bottleneck_loss
        
        env_opt.zero_grad()
        loss.backward(retain_graph=True)
        env_opt.step()
        
        vdb_opt.zero_grad()
        loss.backward(retain_graph=True)
        vdb_opt.step()
    
    expert_acc = ((vdb(expert_pairs)[0] < 0.5).float()).mean()
    learner_acc = ((vdb(leaner_pairs)[0] > 0.5).float()).mean()
    return expert_acc, learner_acc

def train_actor_critic(args, env, actor, critic, env_opt, actor_opt, critic_opt, leaners):
    env.train(), actor.train(), critic.train()
    
    n = len(leaners)
    arr = np.arange(n)
    
    #leaners set
    old_prev = torch.cat([h for h, p_a, a, c, r in leaners], dim=1) #tensor(layer num * memory len * dim)
    old_act = torch.cat([p_a for h, p_a, a, c, r in leaners], dim=0) #tensor(memory len, token id)
    actions = torch.cat([a for h, p_a, a, c, r in leaners], dim=0) #tensor(memory len * act size)
    condition = torch.cat([c for h, p_a, a, c, r in leaners], dim=0) #tensor(memory len * dim)
    rewards = [r for h, p_a, a, c, r in leaners] #list(memory len)
    
    if args.device:
        old_prev, old_act, actions, condition = old_prev.cuda(), old_act.cuda(), actions.cuda(), condition.cuda()
    
    states, _ = env(old_act, old_prev) #tensor(memory len * dim)
    
    old_values = critic(states)
    returns, advants = get_gae(args, rewards, old_values)
    
    mu, std = actor(states, condition)
    old_policy = log_prob_density(actions, mu, std)
    
    criterion = torch.nn.MSELoss()
    
    if args.verbose:
        actor_critic_iter = tqdm(range(args.ppo_update_num), desc='updating actor-critic..', ncols=100, leave=True)
    else:
        actor_critic_iter = range(args.ppo_update_num)
        print('INFO: actor-critic update')
    
    for _ in actor_critic_iter:
        np.random.shuffle(arr)
        
        for i in range(n // args.batch_size): 
            batch_index = arr[args.batch_size * i : args.batch_size * (i + 1)]
            batch_index = torch.LongTensor(batch_index)
            
            inputs1, _ = env(old_act[batch_index], old_prev[:, batch_index, :])
            inputs2 = condition[batch_index]
            actions_samples = actions[batch_index]
            returns_samples = returns.unsqueeze(1)[batch_index]
            advants_samples = advants.unsqueeze(1)[batch_index]
            oldvalue_samples = old_values[batch_index].detach()
            
            values = critic(inputs1)
            clipped_values = oldvalue_samples + torch.clamp(values - oldvalue_samples, -args.clip_param, args.clip_param)
            
            critic_loss1 = criterion(clipped_values, returns_samples)
            critic_loss2 = criterion(values, returns_samples)
            critic_loss = torch.max(critic_loss1, critic_loss2).mean()
            
            loss, ratio, entropy = surrogate_loss(actor, advants_samples, inputs1, inputs2, old_policy.detach(), actions_samples, batch_index)
            
            clipped_ratio = torch.clamp(ratio, 1.0 - args.clip_param, 1.0 + args.clip_param)
            
            clipped_loss = clipped_ratio * advants_samples
            actor_loss = -torch.min(loss, clipped_loss).mean()
            
            loss = actor_loss + 0.5 * critic_loss - 0.001 * entropy
            
            env_opt.zero_grad()
            loss.backward(retain_graph=True)
            env_opt.step()
            
            critic_opt.zero_grad()
            loss.backward(retain_graph=True) 
            critic_opt.step()

            actor_opt.zero_grad()
            loss.backward()
            actor_opt.step()
    return
```

## Environment
```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.15.0-rc3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 418.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] pytorch-nlp==0.4.1
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-nlp               0.4.1                    pypi_0    pypi
[conda] torchvision               0.4.1                py37_cu101    pytorch
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by zhangguanheng66** [comment]
@mrshenli

**Comment by pietern** [comment]
You call `loss.backward` more than once.

I would expect the first call to `loss.backward` to compute and accumulate and globally reduce gradients in all parameters across the different models. Then the second call to `loss.backward` would compute and accumulate, but not trigger global reduction (see `reducer.cpp` in `finalize_backward` -- it sets `expect_autograd_hooks_` to `false`).

The code snippets don't include line numbers, so I can't tell which of them throws. Can you clarify?

**Comment by jcw521** [comment]
Maybe you are right. The error message is occurred at
```
critic_opt.zero_grad()
loss.backward(retain_graph=True)  ← here
critic_opt.step()
```
However, I can't understand that `loss.backward` functions are processed well in `train_vdb` but not in `train_actor_critic`.
what makes difference? :(

**Comment by pietern** [comment]
I suppose that in `train_vdb` you actually produce gradients for all model parameters, whereas in `train_actor_critic` you don't. When you don't, the reducer (the code that triggers gradient reduction) remains armed and waiting for more gradients. Instead of receiving gradients for the remaining gradients, in your code you'll produce new gradients for the same parameters, triggering the error.

You can rewrite your code like this to fix the issue:

```python
            env_opt.zero_grad()
            critic_opt.zero_grad()
            actor_opt.zero_grad()
            loss.backward()
            env_opt.step()
            critic_opt.step()
            actor_opt.step()
```

**Comment by jcw521** [comment]
@pietern 
As your advice, I changed my code to like that
```
env_opt.zero_grad()
critic_opt.zero_grad()
actor_opt.zero_grad()

loss.backward()

env_opt.step()
critic_opt.step()
actor_opt.step()
```
but it got another error.
```
Traceback (most recent call last):
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jcw/PycharmProjects/VAIRLtext/main.py", line 235, in train
    train_actor_critic(args, env, actor, critic, env_optim, actor_optim, critic_optim, leaners_set)
  File "/home/jcw/PycharmProjects/VAIRLtext/Scheme.py", line 190, in train_actor_critic
    loss, ratio, entropy = surrogate_loss(actor, advants_samples, inputs1, inputs2, old_policy.detach(), actions_samples, batch_index)
  File "/home/jcw/PycharmProjects/VAIRLtext/Scheme.py", line 54, in surrogate_loss
    mu, std = actor(states, cond)
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jcw/tmp/anaconda3/envs/VAIRLtext/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 459, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /opt/conda/conda-bld/pytorch_1570910687650/work/torch/csrc/distributed/c10d/reducer.cpp:518)
```
So, I modified `DistributedDataParallel`
```
env = DistributedDataParallel(env, device_ids=[args.gpu_id], find_unused_parameters=True)
actor = DistributedDataParallel(actor, device_ids=[args.gpu_id], find_unused_parameters=True)
critic = DistributedDataParallel(critic, device_ids=[args.gpu_id], find_unused_parameters=True)
vdb = DistributedDataParallel(vdb, device_ids=[args.gpu_id], find_unused_parameters=True)
```
Then, It works!! Thank you very much!! I'm very appreciate to you!! :)

**Comment by pietern** [comment]
Excellent! Thanks for the update.

This means you have either a data dependent control flow in your model, or you simply define some parameters and never use them. If it's the former, then great. If it's the latter, I would look for the parameters that you're not using and remove them. There is a small perf cost to finding unused parameters that you can remove if this is the case.
