### ISSUE TITLE
How to install pytorch for CUDA 10.2?

### ISSUE THREAD

**Issue by tensor2flow** [pytorch/pytorch#31098]
Hello everyone. I have installed CUDA 10.2 and i tried to install pytorch on windows.
But I catched error like this:
FAILED: build.ninja
C:\Users\TensorFlow\.conda\envs\torch\Library\bin\cmake.exe -SF:\Git\pytorch -BF:\Git\pytorch\build
ninja: error: rebuilding 'build.ninja': subcommand failed
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "F:\Git\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "F:\Git\pytorch\tools\setup_helpers\cmake.py", line 337, in build
    self.run(build_args, my_env)
  File "F:\Git\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\TensorFlow\.conda\envs\torch\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.

Help me, please. How to I can fix this bug?

**Comment by peterjc123** [comment]
Full log, please.

**Comment by izdeby** [comment]
Please, use our [forums](https://discuss.pytorch.org/) for questions. Thank you
