### ISSUE TITLE
Building from source without CUDA is failing for 1.2

### ISSUE THREAD

**Issue by xDuck** [pytorch/pytorch#31210]
## 🐛 Bug

Trying to build Pytorch from source on a 1.2 or similar build without CUDA because my project depends on 1.2. Seems to always be an issue with Caffe2 on any commit I try. I had at one point around September 17th made a successful build (from master I think) but I forgot to pin the commit and can no longer reproduce the build.

```
[ 83%] Building CXX object caffe2/CMakeFiles/torch.dir/quantization/server/caffe2_dnnlowp_utils.cc.o
In file included from /root/pytorch/caffe2/quantization/server/dnnlowp_op.h:11,
                 from /root/pytorch/caffe2/quantization/server/batch_matmul_dnnlowp_op.h:20,
                 from /root/pytorch/caffe2/quantization/server/batch_matmul_dnnlowp_op.cc:17:
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: error: ‘Packed3x3ConvMatrix’ is not a member of ‘fbgemm’
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                           ^~~~~~~~~~~~~~~~~~~
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: note: suggested alternative: ‘PackBMatrix’
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                           ^~~~~~~~~~~~~~~~~~~
                           PackBMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: error: ‘Packed3x3ConvMatrix’ is not a member of ‘fbgemm’
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: note: suggested alternative: ‘PackBMatrix’
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                           ^~~~~~~~~~~~~~~~~~~
                           PackBMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:46: error: template argument 1 is invalid
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                                              ^
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: error: ‘Packed3x3x3ConvMatrix’ is not a member of ‘fbgemm’
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                           ^~~~~~~~~~~~~~~~~~~~~
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: note: suggested alternative: ‘PackedDepthWiseConvMatrix’
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                           ^~~~~~~~~~~~~~~~~~~~~
                           PackedDepthWiseConvMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: error: ‘Packed3x3x3ConvMatrix’ is not a member of ‘fbgemm’
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: note: suggested alternative: ‘PackedDepthWiseConvMatrix’
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                           ^~~~~~~~~~~~~~~~~~~~~
                           PackedDepthWiseConvMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:48: error: template argument 1 is invalid
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                                                ^
[ 83%] Building CXX object caffe2/CMakeFiles/torch.dir/quantization/server/channel_shuffle_dnnlowp_op.cc.o
gmake[2]: *** [caffe2/CMakeFiles/torch.dir/quantization/server/batch_matmul_dnnlowp_op.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /root/pytorch/caffe2/quantization/server/conv_pool_dnnlowp_op_base.h:10,
                 from /root/pytorch/caffe2/quantization/server/channel_shuffle_dnnlowp_op.h:5,
                 from /root/pytorch/caffe2/quantization/server/channel_shuffle_dnnlowp_op.cc:1:
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: error: ‘Packed3x3ConvMatrix’ is not a member of ‘fbgemm’
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                           ^~~~~~~~~~~~~~~~~~~
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: note: suggested alternative: ‘PackBMatrix’
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                           ^~~~~~~~~~~~~~~~~~~
                           PackBMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: error: ‘Packed3x3ConvMatrix’ is not a member of ‘fbgemm’
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:27: note: suggested alternative: ‘PackBMatrix’
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                           ^~~~~~~~~~~~~~~~~~~
                           PackBMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:39:46: error: template argument 1 is invalid
   std::shared_ptr<fbgemm::Packed3x3ConvMatrix> W_depthwise_3x3;
                                              ^
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: error: ‘Packed3x3x3ConvMatrix’ is not a member of ‘fbgemm’
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                           ^~~~~~~~~~~~~~~~~~~~~
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: note: suggested alternative: ‘PackedDepthWiseConvMatrix’
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                           ^~~~~~~~~~~~~~~~~~~~~
                           PackedDepthWiseConvMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: error: ‘Packed3x3x3ConvMatrix’ is not a member of ‘fbgemm’
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:27: note: suggested alternative: ‘PackedDepthWiseConvMatrix’
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                           ^~~~~~~~~~~~~~~~~~~~~
                           PackedDepthWiseConvMatrix
/root/pytorch/caffe2/quantization/server/fbgemm_pack_blob.h:40:48: error: template argument 1 is invalid
   std::shared_ptr<fbgemm::Packed3x3x3ConvMatrix> W_depthwise_3x3x3;
                                                ^
gmake[2]: *** [caffe2/CMakeFiles/torch.dir/quantization/server/channel_shuffle_dnnlowp_op.cc.o] Error 1
gmake[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
gmake: *** [all] Error 2
cmake -DBUILD_PYTHON=False -DBUILD_TEST=False -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/pytorch/torch -DCMAKE_PREFIX_PATH=/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages -DPYTHON_EXECUTABLE=/opt/rh/rh-python36/root/usr/bin/python -DPYTHON_INCLUDE_DIR=/opt/rh/rh-python36/root/usr/include/python3.6m -DUSE_CUDA=False -DUSE_NCCL=OFF -DUSE_NUMPY=True /root/pytorch
cmake --build . --target install --config Release -- -j 4
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 23, in <module>
    rerun_cmake=True, cmake_only=False, cmake=CMake())
  File "/root/pytorch/tools/build_pytorch_libs.py", line 63, in build_caffe2
    cmake.build(my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 331, in build
    self.run(build_args, my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
The command '/bin/sh -c source /root/.bashrc && cd pytorch && mkdir build && cd build && BUILD_TEST=OFF USE_NCCL=OFF USE_CUDA=0 python ../tools/build_libtorch.py' returned a non-zero code: 1
```

## To Reproduce

Dockerfile
```
ARG cuda_version=10.1
ARG cudnn_version=7
ARG centos=7
# FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel-centos${centos}
FROM centos:7.4.1708
USER root
WORKDIR /root

# Dependencies 

RUN yum update -y
RUN yum install -y --nogpgcheck \
    centos-release-scl \
    epel-release
RUN yum -y --nogpgcheck install \
    devtoolset-8-gcc* \
    git \
    gflags-devel \
    glog-devel \
    #    libiomp-devel \
    openmpi-devel \
    protobuf-compiler \
    rh-python36-python \
    rh-python36-python-pip \
    rh-python36-python-setuptools \
    rh-python36-PyYAML \
    wget \
    cmake3 \
    make

# Intel MKL installation

RUN yum-config-manager --add-repo https://yum.repos.intel.com/setup/intelproducts.repo
RUN yum -y --nogpgcheck install intel-mkl-64bit-2019.1-053
RUN rm /opt/intel/mkl/lib/intel64/*.so

# Download and build libtorch with MKL support

# ENV TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5"
# ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
RUN git clone --recurse-submodules https://github.com/pytorch/pytorch.git
# RUN cd pytorch && git checkout 8554416a199c4cec01c60c7015d8301d2bb39b64
RUN cd pytorch && git checkout 0ad8c679aedd0c881664c804f06598e100172339

RUN cd /usr/bin && ln -s cmake3 cmake
RUN echo 'source scl_source enable devtoolset-8' >> /root/.bashrc
RUN echo 'source scl_source enable rh-python36' >> /root/.bashrc

RUN source /root/.bashrc && cd pytorch && mkdir build && cd build && BUILD_TEST=OFF USE_NCCL=OFF USE_CUDA=0 python ../tools/build_libtorch.py

# Prepare built package

RUN cd && mkdir -p libtorch/include && mkdir -p libtorch/share
RUN cp -r pytorch/build/build/lib libtorch
RUN cp -r pytorch/torch/share/cmake libtorch/share/cmake
RUN for dir in ATen c10 caffe2 torch; do cp -r pytorch/torch/include/$dir libtorch/include; done

CMD [ "/bin/bash", "-" ]
```

**Comment by 6o6o** [comment]
I confirm. Same issue when building torch-1.4.0a0+04b9324 on Linux Fedora 22
```
CUDA version        : 9.1
cuDNN version       : 7.5.0
```

**Comment by xDuck** [comment]
I think I found the issue, all the modules in `third_party` are not pinned for each release of PyTorch so you cannot reproduce builds.

**Comment by xDuck** [comment]
Seems my Git Submodules weren't updated when I cloned and then checked out a previous commit. Fixed by not checking out submodules until after I had checked out the revision I wanted.
