### ISSUE TITLE
Script method can't call a scripted function when it is decorated with `@torch.no_grad`

### ISSUE THREAD

**Issue by seanprime7** [pytorch/pytorch#31259]
## 🐛 Bug

With the new JIT API, a script method can no longer call a scripted function when it is decorated with `@torch.no_grad`

## To Reproduce

This issue can be reproduced with the example below:

```
$ cat test1.py
import torch
import torch.nn as nn

@torch.jit.script
@torch.no_grad()
def foo(x):
    return x + 1

class Test1(torch.jit.ScriptModule):
    @torch.jit.script_method
    @torch.no_grad()
    def forward(self, x):
        return foo(x)

m1 = Test1()
print(m1.graph_for(torch.zeros(4, 3)))

$ python test1.py
graph(%self : ClassType<Test1>,
      %x.1 : Float(*, *)):
  %2 : int = prim::Constant[value=1]() # /home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/autograd/grad_mode.py:7:15
  %3 : Float(*, *) = aten::add(%x.1, %2, %2) # /home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/autograd/grad_mode.py:7:11
  return (%3)

$ cat test2.py
import torch
import torch.nn as nn

@torch.jit.script
@torch.no_grad()
def foo(x):
    return x + 1

class Test2(nn.Module):
    @torch.no_grad()
    def forward(self, x):
        return foo(x)

m2 = torch.jit.script(Test2())
print(m2.graph_for(torch.zeros(4, 3)))

$ python test2.py
Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    m2 = torch.jit.script(Test2())
  File "/home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError:
undefined value foo:
at /home/selee/conda/envs/plugin/lib/python3.7/site-packages/torch/autograd/grad_mode.py:12:15
    @torch.no_grad()
    def forward(self, x):
        return foo(x)
               ~~~ <--- HERE
```

`test1.py` uses the deprecated JIT API, and `forward` in `Test1` can call the scripted `foo` as expected.
However, `test2.py` uses the new JIT API, and `forward` in `Test2` cannot call the scripted `foo`.

This looks like a regression with the new API.

## Expected behavior

The new API is expected to support it as the old API does.

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Ubuntu 18.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source):
 - Python version: 3.7

**Comment by suo** [comment]
@driazati can you take a look?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
