### ISSUE TITLE
JIT trace() -> save() -> load() -> copy() for modules with submodules is broken

### ISSUE THREAD

**Issue by jhhurwitz** [pytorch/pytorch#31268]
## 🐛 Bug

Modules with registered submodules (tested with resnet and mobilenet v2), cannot be copied after saved and loaded. **Note: copying without saving and loading does not produce an error**. 

## To Reproduce

```python
import torch
from torchvision import models

class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.submodule = models.resnet50()
    def forward(self, x):
        return self.submodule(x)

my_module = MyModule()
my_module.eval()
x = torch.rand(1, 3, 224, 224)
traced_cell = torch.jit.trace(my_module, x)
traced_cell.save('my_module.pth')
loaded_model = torch.jit.load('my_module.pth')
loaded_model.copy()
```

Creates stacktrace:
```bash
Users/****/venv/bin/python /Users/****/temporal-shift-module/test.py
Traceback (most recent call last):
  File "/Users/****/temporal-shift-module/test.py", line 20, in <module>
    loaded_model.copy()
  File "/Users/****/venv/lib/python3.7/site-packages/torch/jit/__init__.py", line 1644, in copy
    return ScriptModule(_cpp_module=self._c._clone())
RuntimeError: class '__torch__.torch.nn.modules.conv.___torch_mangle_2.Conv2d' already defined. (register_type at ../torch/csrc/jit/script/compilation_unit.h:166)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x114e249e7 in libc10.dylib)
frame #1: torch::jit::script::CompilationUnit::register_type(std::__1::shared_ptr<c10::NamedType>) + 524 (0x11ecaeefc in libtorch.dylib)
frame #2: torch::jit::script::create_module_object(c10::QualifiedName, std::__1::shared_ptr<torch::jit::script::CompilationUnit>, bool) + 1178 (0x11ef3819a in libtorch.dylib)
frame #3: torch::jit::script::Module::Module(c10::QualifiedName, std::__1::shared_ptr<torch::jit::script::CompilationUnit>, bool) + 247 (0x11ef38567 in libtorch.dylib)
frame #4: torch::jit::script::Module::clone_impl(std::__1::unordered_map<std::__1::shared_ptr<c10::Type>, std::__1::shared_ptr<c10::Type>, std::__1::hash<std::__1::shared_ptr<c10::Type> >, std::__1::equal_to<std::__1::shared_ptr<c10::Type> >, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<c10::Type> const, std::__1::shared_ptr<c10::Type> > > >&) const + 328 (0x11ef3e128 in libtorch.dylib)
frame #5: torch::jit::script::Module::clone_impl(std::__1::unordered_map<std::__1::shared_ptr<c10::Type>, std::__1::shared_ptr<c10::Type>, std::__1::hash<std::__1::shared_ptr<c10::Type> >, std::__1::equal_to<std::__1::shared_ptr<c10::Type> >, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<c10::Type> const, std::__1::shared_ptr<c10::Type> > > >&) const + 1291 (0x11ef3e4eb in libtorch.dylib)
frame #6: torch::jit::script::Module::clone_impl(std::__1::unordered_map<std::__1::shared_ptr<c10::Type>, std::__1::shared_ptr<c10::Type>, std::__1::hash<std::__1::shared_ptr<c10::Type> >, std::__1::equal_to<std::__1::shared_ptr<c10::Type> >, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<c10::Type> const, std::__1::shared_ptr<c10::Type> > > >&) const + 1291 (0x11ef3e4eb in libtorch.dylib)
frame #7: torch::jit::script::Module::clone() const + 43 (0x11ef3df1b in libtorch.dylib)
frame #8: _ZZN8pybind1112cpp_function10initializeIZNS0_C1IN5torch3jit6script6ModuleES6_JEJNS_4nameENS_9is_methodENS_7siblingEEEEMT0_KFT_DpT1_EDpRKT2_EUlPKS6_E_S6_JSL_EJS7_S8_S9_EEEvOSB_PFSA_SD_ESJ_ENKUlRNS_6detail13function_callEE_clESS_ + 116 (0x11b77cab4 in libtorch_python.dylib)
frame #9: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3372 (0x11b2b3cfc in libtorch_python.dylib)
frame #10: _PyMethodDef_RawFastCallKeywords + 545 (0x10b3dbf28 in Python)
frame #11: _PyCFunction_FastCallKeywords + 44 (0x10b3db493 in Python)
frame #12: call_function + 746 (0x10b4711d6 in Python)
frame #13: _PyEval_EvalFrameDefault + 7016 (0x10b469da9 in Python)
frame #14: function_code_fastcall + 112 (0x10b3db86e in Python)
frame #15: call_function + 753 (0x10b4711dd in Python)
frame #16: _PyEval_EvalFrameDefault + 7016 (0x10b469da9 in Python)
frame #17: _PyEval_EvalCodeWithName + 1835 (0x10b471a6f in Python)
frame #18: PyEval_EvalCode + 42 (0x10b4681b9 in Python)
frame #19: run_mod + 54 (0x10b496f61 in Python)
frame #20: PyRun_FileExFlags + 164 (0x10b495f7c in Python)
frame #21: PyRun_SimpleFileExFlags + 266 (0x10b495636 in Python)
frame #22: pymain_main + 4896 (0x10b4ae106 in Python)
frame #23: _Py_UnixMain + 75 (0x10b4ae993 in Python)
frame #24: start + 1 (0x7fff54d36015 in libdyld.dylib)
```

## Expected behavior

We would expect there to not be an issue with copying a loaded JIT module with a submodule.

## Environment

 - PyTorch Version: 1.3.1
 - OS: MacOS / Linux
 - How you installed PyTorch: Pip
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0.130 (Linux)
 - GPU models and configuration: 4 X GeForce RTX 2080 Ti (Linux)
 - Any other relevant information: Reproducible using libtorch `torch::jit::script::Module::clone` in the currently nightly build.

cc @suo

**Comment by jhhurwitz** [comment]
Hello, is there any update on this? 

As far as I can tell, this would disallow multi-gpu training for these types of models after they are serialized to disk, since `clone` is an essential method for copying to multiple gpus.

**Comment by suo** [comment]
Sorry, looks like we missed this during the holiday season. @ZolotukhinM, @jerryzh168, iirc you guys implemented module cloning—can you take a look at this issue?

**Comment by jerryzh168** [comment]
I can take a look
