### ISSUE TITLE
torch runtime error when manual link libmkldnn.so

### ISSUE THREAD

**Issue by cjld** [pytorch/pytorch#31300]
## 🐛 Bug

I manual link libmkldnn.so, because I want to use some functions inside mkldnn, but pytorch get runtime error when I manual link libmkldnn.so

## To Reproduce

```
import ctypes, os

mkl_lib_name="MY_MKL_PATH/lib/libmkldnn.so"
dlopen_flags = os.RTLD_NOW | os.RTLD_GLOBAL # | os.RTLD_DEEPBIND
ctypes.CDLL(mkl_lib_name, dlopen_flags)

nchw = [2, 3, 100, 100]
oihw = [4, 3, 5, 5]

import torch
m = torch.nn.Conv2d(3, 4, 5, 1, 2)
m(torch.rand(*nchw))
```
get runtime error
```
Traceback (most recent call last):
  File "a.py", line 13, in <module>
    m(torch.rand(*nchw))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: std::exception
```

## Expected behavior

No runtime error

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1
[conda] Could not collect

**Comment by cjld** [comment]
One possible solution: Pass -Bsymbolic or -Bsymbolic-functions to the linker when compiling pytorch

<https://stackoverflow.com/questions/6538501/linking-two-shared-libraries-with-some-of-the-same-symbols>

**Comment by ihnorton** [comment]
Note that `-Bsymbolic` can have some unexpected side-effects [1]. On linux, you may be able to solve the problem without any build system changes by loading your own `mkldnn` library in a separate namespace using `dlmopen` [2] instead. `dlmopen` is not explicitly provided by ctypes, but can be called directly, and then used to construct a CDLL:

```
import ctypes, os

selfimg = ctypes.CDLL('')
selfimg.dlmopen.restype = ctypes.c_void_p
selfimg.dlerror.restype = ctypes.c_char_p

lib_path = b"/home/ubuntu/bld/TileDB-r/dist/lib/libtiledb.so"
dlopen_flags = os.RTLD_NOW | os.RTLD_GLOBAL # | os.RTLD_DEEPBIND

try:
    _h = selfimg.dlmopen(-1, lib_path, dlopen_flags)
    my_dll = ctypes.CDLL(lib_path, handle=_h)
except Exception as exc:
    print(exc)
    print("Possibly got dlerror: '{}'".format(selfimg.dlerror()))
```

then use as usual:
```
>>> my_dll
<CDLL 'my_dll', handle 5611d5f23810 at 0x7ff5f3e928d0>


>>> my_dll.tiledb_ctx_alloc
<_FuncPtr object at 0x7ff5f08d8368>
```

[1] https://software.intel.com/en-us/articles/performance-tools-for-software-developers-bsymbolic-can-cause-dangerous-side-effects
[2] https://manpages.debian.org/testing/manpages-dev/dlmopen.3.en.html
