### ISSUE TITLE
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

### ISSUE THREAD

**Issue by pccai** [pytorch/pytorch#31302]
**Ubuntu16.04/pytorch 1.1:**
.....
Epoch 0
/usr/local/lib/python3.6/site-packages/torch/nn/functional.py:1386: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    train(start_epoch+epoch)
  File "train.py", line 184, in train
    ntt[0], ntt[1], ntt[2])
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/PaperRobot/Existing paper reading/model/GATA.py", line 19, in forward
    graph = self.graph(node_features, adj)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/PaperRobot/Existing paper reading/model/GAT.py", line 18, in forward
    x = torch.cat([att(x, adj) for att in self.attentions], dim=1)
  File "/usr/PaperRobot/Existing paper reading/model/GAT.py", line 18, in <listcomp>
    x = torch.cat([att(x, adj) for att in self.attentions], dim=1)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/PaperRobot/Existing paper reading/model/graph_attention.py", line 37, in forward
    attention = F.dropout(attention, self.dropout, training=self.training)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 830, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

**Comment by colesbury** [comment]
The allocation failed because there's not enough CPU memory. The error message for this failure is bad (sorry) -- the message was made more clear in PyTorch 1.2

**Comment by zou3519** [comment]
I am closing this based on @colesbury's comment that we fixed the error message in PyTorch 1.2.
