### ISSUE TITLE
adam.py - ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by RebolloM** [pytorch/pytorch#31377]
I am trying to run the below pre-train script using [MASS-Summarization](https://github.com/microsoft/MASS/tree/master/MASS-summarization) and fairseq and I get the below error. Please advise?

Windows 10
CUDA 10
python 3.6
fairseq==0.9.0
torch==1.2.0

...\MASS\MASS-summarization>fairseq-train processed --user-dir=mass --task=masked_s2s --arch=transformer_mass_base --sample-break-mode=none --tokens-per-sample=512 --criterion=masked_lm --optimizer=adam --adam-betas='(0.9,0.98)' --adam-eps=1e-6 --clip-norm=0.0 --lr-scheduler=polynomial_decay --lr=0.0005 --warmup-updates=10000 --total-num-update=125000 --dropout=0.1 --attention-dropout=0.1 --weight-decay=0.01 --max-sentences=8 --update-freq=16 --ddp-backend=no_c10d

Error:
model transformer_mass_base, criterion MaskedLmLoss
| num. model params: 123469824 (num. trained: 123469824)
| training on 1 GPUs
| max tokens per GPU = None and max sentences per GPU = 8
| no existing checkpoint found checkpoints\checkpoint_last.pt
| loading train data for epoch 0
| loaded 1160905 examples from: processed\train
| epoch 001: 0%| | 0/1751 [00:00<?, ?it/s]Traceback (most recent call last):
File "c:\users\devbox.conda\envs\p3.6\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\users\devbox.conda\envs\p3.6\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\devbox.conda\envs\p3.6\Scripts\fairseq-train.exe_main.py", line 7, in
File "c:\users\devbox.conda\envs\p3.6\lib\site-packages\fairseq_cli\train.py", line 333, in cli_main
main(args)
File "c:\users\devbox.conda\envs\p3.6\lib\site-packages\fairseq_cli\train.py", line 86, in main
train(args, trainer, task, epoch_itr)
File "c:\users\devbox.conda\envs\p3.6\lib\site-packages\fairseq_cli\train.py", line 127, in train
log_output = trainer.train_step(samples)
File "c:\users\devbox.conda\envs\p3.6\lib\site-packages\fairseq\trainer.py", line 437, in train_step
self.optimizer.step()
File "c:\users\devbox.conda\envs\p3.6\lib\site-packages\fairseq\optim\fairseq_optimizer.py", line 98, in step
self.optimizer.step(closure)
File "c:\users\devbox.conda\envs\p3.6\lib\site-packages\fairseq\optim\adam.py", line 155, in step
beta1, beta2 = group['betas']
ValueError: too many values to unpack (expected 2)

**Comment by pbelevich** [comment]
@RebolloM is it fairseq issue? If so please create an issues in fairseq project and close this one
