### ISSUE TITLE
torch.stft causes segmentation fault with data parellel.

### ISSUE THREAD

**Issue by kamo-naoyuki** [pytorch/pytorch#31412]
## 🐛 Bug

torch.stft causes segmentation fault with data parellel.

## To Reproduce
```python
import torch
class Stft(torch.nn.Module):
    def forward(self, x):
        y = torch.stft(x, n_fft=512)
        return y
a = Stft()
x = torch.randn(2, 2000)
torch.nn.parallel.data_parallel(a, (x,), device_ids=[0])
print("single gpu passed")
torch.nn.parallel.data_parallel(a, (x,), device_ids=[0, 1])
print("two gpu passed")
```

This exits with segmentation fault after `single gpu passed`

## Expected behavior

Work with data_parallel.

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1-py3.7_cuda10.0.130_cudnn7.6.3_0 (1.0.1 can work)
 - OS (e.g., Linux): CentOS7
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: cuda 10.0
 - GPU models and configuration: Tesla K80 
 - Any other relevant information:

cc @ezyang @gchanan @zou3519

**Comment by SsnL** [comment]
Seems to work on `'1.4.0a0+0723b8b'`... maybe someone with 1.3.1 can try to reproduce.

**Comment by kamo-naoyuki** [comment]
```
gdb --args python a.py
GNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-26.el7
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.
(gdb) r
Starting program: <--secret-->/python a.py
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for <--secret-->/lib/python3.7/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
Detaching after fork from child process 130732.
BFD: warning: <--secret-->/lib/python3.7/site-packages/torch/lib/../../../../libmkl_core.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000002
[New Thread 0x7fffa176c700 (LWP 130761)]
[New Thread 0x7fffa0f6b700 (LWP 130763)]
[New Thread 0x7fff8f277700 (LWP 130765)]
[New Thread 0x7fff8ea76700 (LWP 130795)]
[New Thread 0x7fff8cf79700 (LWP 130796)]

Thread 5 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8ea76700 (LWP 130795)]
0x00007fffea68015d in std::__detail::_List_node_base::_M_hook (this=0x7fff7800a530, __position=0x7fff78009b70)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++98/list.cc:132
132	/home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++98/list.cc: No such file or directory.
```

**Comment by gortizji** [comment]
I'm getting the same error with `torch.fft` as well. It does not happen to me when I use 2 GPUs, but it does with 4 and more. I am running the nightly build `1.4.0dev20191218`. Also when built from source. The segmentation fault seems to occur only for some batch sizes. I am using 4 P100 GPUs and `cuda=10.1`.

The following code can reproduce the error.

```
import torch
class FFT(torch.nn.Module):
    def forward(self, x):
        y = torch.fft(x, dim=-1)
        return y
a = FFT()
x = torch.randn(2, 2000)
torch.nn.parallel.data_parallel(a, (x,), device_ids=[0])
print("single gpu passed")
torch.nn.parallel.data_parallel(a, (x,), device_ids=[0, 1, 2, 3])
print("four gpu passed")
```

**Comment by SsnL** [comment]
@gortizji Unfortunately I still can't reproduce this. If you are able to do a debug build (with `DEBUG=1`), could you post the gdb trace? Thank you!

**Comment by kamo-naoyuki** [comment]
I could also reproduce with source build of torch-1.4.0a0+d6ddfab d6ddfab11fe92400c4201b1d9e322f930d74ee5a and got same trace as the above results.

I don't know how to go ahead the trace  from list.cc

```
#0  0x00007fffe45cf15d in std::__detail::_List_node_base::_M_hook (this=0x7fff6c004750, __position=0x7fff6c004780)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++98/list.cc:132
#1  0x00007fffc2ede0df in std::list<std::pair<at::native::detail::CuFFTParams, at::native::detail::CuFFTConfig>, std::allocator<std::pair<at::native::detail::CuFFTParams, at::native::detail::CuFFTConfig> > >::_M_insert<std::piecewise_construct_t const&, std::tuple<at::native::detail::CuFFTParams&>, std::tuple<at::Tensor&, long&, bool&, bool&, c10::ArrayRef<long>&, bool&, c10::ArrayRef<long>&> > (
    this=0x7fff6c004780, __position=..., __args#0=..., __args#1=..., __args#2=...) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_list.h:1802
#2  0x00007fffc2edc65e in std::list<std::pair<at::native::detail::CuFFTParams, at::native::detail::CuFFTConfig>, std::allocator<std::pair<at::native::detail::CuFFTParams, at::native::detail::CuFFTConfig> > >::emplace_front<std::piecewise_construct_t const&, std::tuple<at::native::detail::CuFFTParams&>, std::tuple<at::Tensor&, long&, bool&, bool&, c10::ArrayRef<long>&, bool&, c10::ArrayRef<long>&> > (
    this=0x7fff6c004780, __args#0=..., __args#1=..., __args#2=...) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_list.h:1083
#3  0x00007fffc2edaf4c in at::native::detail::CuFFTParamsLRUCache::try_emplace_value<at::native::detail::CuFFTParams, at::Tensor&, long&, bool&, bool&, c10::ArrayRef<long>&, bool&, c10::ArrayRef<long>&> (
    this=0x7fff6c004758, key=..., value_args#0=..., value_args#1=@0x7fff8cc4fea8: 1, value_args#2=@0x7fff8cc4fea4: false, value_args#3=@0x7fff8cc4fea0: true, value_args#4=..., 
    value_args#5=@0x7fff8cc4fe94: true, value_args#6=...) a <secret>/pytorch_20191224/aten/src/ATen/native/cuda/CuFFTPlanCache.h:414
#4  0x00007fffc2ed5101 in at::native::_fft_cufft (self=..., signal_ndim=1, complex_input=false, complex_output=true, inverse=false, checked_signal_sizes=..., normalized=false, onesided=true, output_sizes=...)
    at <secret>/pytorch_20191224/aten/src/ATen/native/cuda/SpectralOps.cu:374
#5  0x00007fffc3d48964 in at::CUDAType::(anonymous namespace)::_fft_with_size (self=..., signal_ndim=1, complex_input=false, complex_output=true, inverse=false, checked_signal_sizes=..., normalized=false, 
    onesided=true, output_sizes=...) at aten/src/ATen/CUDAType.cpp:881
#6  0x00007fffc3dfcb51 in c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > >::operator() (this=0x555556ad61d0, args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, 
    args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/boxing/kernel_lambda.h:23
#7  0x00007fffc3dedbf6 in c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > >, at::Tensor (at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)>::call(c10::OperatorKernel*, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>) (functor=0x555556ad61d0, 
    args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/boxing/kernel_functor.h:261
#8  0x00007fffda0389e2 in c10::KernelFunction::callUnboxed<at::Tensor, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > (this=0x555555dadc88, opHandle=..., 
    args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/boxing/KernelFunction_impl.h:62
#9  0x00007fffda03836f in c10::Dispatcher::callUnboxed<at::Tensor, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > (
    this=0x7fffe42ced20 <c10::Dispatcher::singleton()::_singleton>, op=..., args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, args#8=...)
    at ../aten/src/ATen/core/dispatch/Dispatcher.h:179
#10 0x00007fffda037ce2 in c10::OperatorHandle::callUnboxed<at::Tensor, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > (
    this=0x7fffe42ea478 <_ZZN2atL14_fft_with_sizeERKNS_6TensorElbbbN3c108ArrayRefIlEEbbS5_E2op>, args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, 
    args#8=...) at ../aten/src/ATen/core/dispatch/Dispatcher.h:154
#11 0x00007fffdc9a4667 in at::_fft_with_size (self=..., signal_ndim=1, complex_input=false, complex_output=true, inverse=false, checked_signal_sizes=..., normalized=false, onesided=true, output_sizes=...)
    at aten/src/ATen/Functions.h:4605
#12 0x00007fffdc9b9889 in torch::autograd::VariableType::(anonymous namespace)::<lambda()>::operator()(void) const (__closure=0x7fff8cc508a0) at ../torch/csrc/autograd/generated/VariableType_2.cpp:541
#13 0x00007fffdc9ba0d5 in torch::autograd::VariableType::(anonymous namespace)::_fft_with_size (self=..., signal_ndim=1, complex_input=false, complex_output=true, inverse=false, checked_signal_sizes=..., 
    normalized=false, onesided=true, output_sizes=...) at ../torch/csrc/autograd/generated/VariableType_2.cpp:542
#14 0x00007fffda3a274b in c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > >::operator() (this=0x555556692770, args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, 
    args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/boxing/kernel_lambda.h:23
#15 0x00007fffda395bba in c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > >, at::Tensor (at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)>::call(c10::OperatorKernel*, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>) (functor=0x555556692770, 
    args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/boxing/kernel_functor.h:261
#16 0x00007fffda0389e2 in c10::KernelFunction::callUnboxed<at::Tensor, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > (this=0x555555dae048, opHandle=..., 
    args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/boxing/KernelFunction_impl.h:62
#17 0x00007fffda03836f in c10::Dispatcher::callUnboxed<at::Tensor, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > (
    this=0x7fffe42ced20 <c10::Dispatcher::singleton()::_singleton>, op=..., args#0=..., args#1=1, args#2=false, args#3=true, args#4=false, args#5=..., args#6=false, args#7=true, args#8=...)
    at ../aten/src/ATen/core/dispatch/Dispatcher.h:179
#18 0x00007fffda037ce2 in c10::OperatorHandle::callUnboxed<at::Tensor, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > (
    this=0x7fffe42d25a8 <at::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)::op>, args#0=..., args#1=1, args#2=false, args#3=true, 
    args#4=false, args#5=..., args#6=false, args#7=true, args#8=...) at ../aten/src/ATen/core/dispatch/Dispatcher.h:154
#19 0x00007fffda0337a9 in at::_fft_with_size (self=..., signal_ndim=1, complex_input=false, complex_output=true, inverse=false, checked_signal_sizes=..., normalized=false, onesided=true, output_sizes=...)
    at aten/src/ATen/Functions.h:4605
```
