### ISSUE TITLE
Support DataParallel with PackedSequence

### ISSUE THREAD

**Issue by dreamgonfly** [pytorch/pytorch#31422]
## 🚀 Feature
Ability to feed PackedSequence into DataParallel model as input. This can reduce wasteful data transfer when dealing with variable length data.

## Motivation
Dealing with variable length data as input to DataParallel is painful. If you put them into a python list, DataParallel scatter them along wrong axis (instead of splitting the list into equal size, it splits the elements inside the list). You can pad them to the same size, but then you waste memory and transfer bandwidth moving meaningless padding values. 

The ideal solution would be DataParallel supporting PackedSequence input, because PackedSequence is designed for handling variable length data.

## Pitch
I propose that we can do something like the below example.
```python
from torch.nn.utils.rnn import pack_sequence
data = pack_sequence([
    torch.tensor([[0.1, 0.1, 0.1], [0.2, 0.2, 0.2]]), 
    torch.tensor([[0.1, 0.1, 0.1], [0.2, 0.2, 0.2], [0.3, 0.3, 0.3]])
  ], 
  enforce_sorted=False
)
model = nn.LSTM(3, 100)
dp_model = nn.DataParallel(model)
dp_model.to('cuda')

output = dp_model(data)
```

## Alternatives
Padding variable length data to the same length and use them as input. This is wasteful in terms of memory and transfer bandwidth.

## Additional context
FYI, the above example produces this error with 1.2.0 version
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 564, in forward
    return self.forward_tensor(input, hx)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 539, in forward_tensor
    max_batch_size = input.size(0) if self.batch_first else input.size(1)
AttributeError: 'tuple' object has no attribute 'size'
```

**Comment by viannecc** [comment]
I encountered the same problems. Hope someone can solve the issue.

**Comment by mrshenli** [comment]
+1 for supporting variable length inputs for DataParallel, but I am not sure if `PackedSequence` would be the appropriate way to handle it. Packing multiple tensors into one might incur unnecessary overhead as those tensors will need to be scattered to different devices (hence storages) later. Besides, `PackedSequence` currently only lives in RNN utils. If DataParallel depends on it, we probably will need to move it a more general util location.

An alternative might be allowing DataParallel to take a list of tensors, where the length of the list must match the number of devices?

@cpuhrsch Will `NestedTensor`s help here?

**Comment by cpuhrsch** [comment]
@mrshenli - Indeed I'd say NestedTensors would be the principled approach to this, but only up to a certain point. I think in this case you want the constituents to be of different devices, which goes against one of the key assumptions of a NestedTensor (same dtype, layout, device etc.). But you could pass one NestedTensor per device, which each can efficiently represent collections of variably sized Tensors.

**Comment by leedtan** [comment]
@dreamgonfly Talking about this with @mrshenli . Just to clarify, your example is saying something like "I have a minibatch of size 2, but every minibatch the samples will have different lengths. Maybe the first minibatch has arrays of length 2 and 3, and the second minibatch has samples of length 5 and 1, etc. Also, in the above example, the individual elements in a sample are vectors of length 3 (samples are like sentences and the elements in them are like word vectors)?

**Comment by leedtan** [comment]
@dreamgonfly data parallel forward function calls scatter from scatter_gather.py which recursively dives into the lists until it has tensors to scatter between devices. Maybe what you are looking for is just an option on DataParallel (No need for pack_sequence) to scatter at the top level of the list? Would this type of API work"

from torch import nn

# batch size = 2 and sequence lengths = (2, 3)
data = [
    torch.tensor([[0.1, 0.1, 0.1], [0.2, 0.2, 0.2]]).to(0), 
    torch.tensor([[0.1, 0.1, 0.1], [0.2, 0.2, 0.2], [0.3, 0.3, 0.3]]).to(0)
  ]
model = nn.LSTM(3, 100)
dp = nn.DataParallel(model.to(0), device_ids=[0, 1])
# All of each sample got allocated to the same device.
output = dp(data)

output, _ = dp_model(data)
