### ISSUE TITLE
cuDNN convolution does not handle empty input tensor

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#31425]
## 🐛 Bug

code
```python
import torch

print(torch.__version__)
print(torch.version.cuda)
b = torch.nn.Conv2d(32, 32, 2, bias=False, padding=1)
a = torch.randn(2, 32, 0, 5)
print('cpu:', b(a).shape)
b.cuda()
a = a.cuda()
print('cuda:', b(a).shape)
```

output
```
1.4.0.dev20191217
10.1
cpu: torch.Size([2, 32, 1, 6])
Traceback (most recent call last):
  File "conv-empty.py", line 10, in <module>
    print('cuda:', b(a).shape)
  File "/home/xgao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xgao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self._conv_forward(input, self.weight)
  File "/home/xgao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

```

## Environment

```
PyTorch version: 1.4.0.dev20191217
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.324
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 430.50
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] pytorch-ignite==0.2.1
[pip] torch==1.4.0.dev20191217
[pip] torch-nightly==1.2.0.dev20190722
[pip] torchani==1.0.2.dev29+gd32081e
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.5.1                         1    pytorch
[conda] magma-cuda101             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl-service               2.3.0            py37h516909a_0    conda-forge
[conda] mkl_fft                   1.0.15           py37h516909a_1    conda-forge
[conda] mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
[conda] pytorch-ignite            0.2.1                    pypi_0    pypi
[conda] torch                     1.4.0.dev20191217          pypi_0    pypi
[conda] torch-nightly             1.2.0.dev20190722          pypi_0    pypi
[conda] torchani                  1.0.2.dev29+gd32081e           dev_0    <develop>
[conda] torchvision               0.4.2                    pypi_0    pypi
```

**Comment by zasdfgbnm** [comment]
cc: @csarofeen @ptrblck

**Comment by kurtamohler** [comment]
I can start looking into this.

**Comment by nikitaved** [comment]
@zasdfgbnm, does it mean that this 2d convolution is treated like a 1d convolution on a CPU?
Does the code has to switch to 1d convolution, or just carry one with redundant weights and propagate zero gradient to them in backward?

**Comment by cpuhrsch** [comment]
Easy for us to add a guard, but will also inform cuDNN team to send a fix. Not high priority for now since it's not a very common error.

**Comment by ezyang** [comment]
The guard should be easy to add
