### ISSUE TITLE
DISABLED test_get_gradients (dist_autograd_test.DistAutogradJitTestWithSpawn)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#31489]
## 🐛 Bug

`DistAutogradJitTestWithSpawn` is broken, see failures:

```
Dec 19 10:57:24 RuntimeError: 
Dec 19 10:57:24 Python builtin <built-in method get_gradients of PyCapsule object at 0x7f1cf22662a0> is currently not supported in Torchscript:
Dec 19 10:57:24   File "/var/lib/jenkins/workspace/test/dist_autograd_test.py", line 1583
Dec 19 10:57:24         def dist_get_gradients(context_id):
Dec 19 10:57:24             # type: (int) -> (Dict[Tensor, Tensor])
Dec 19 10:57:24             return dist_autograd.get_gradients(context_id)
Dec 19 10:57:24                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Dec 19 10:57:24 
Dec 19 10:57:24 Process process 0:
Dec 19 10:57:24 Traceback (most recent call last):
Dec 19 10:57:24   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Dec 19 10:57:24     self.run()
Dec 19 10:57:24   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Dec 19 10:57:24     self._target(*self._args, **self._kwargs)
Dec 19 10:57:24   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 198, in _run
Dec 19 10:57:24     getattr(self, test_name)()
Dec 19 10:57:24   File "/var/lib/jenkins/workspace/test/dist_utils.py", line 96, in new_test_method
Dec 19 10:57:24     return_value = old_test_method(self, *arg, **kwargs)
Dec 19 10:57:24   File "/var/lib/jenkins/workspace/test/dist_autograd_test.py", line 1580, in test_get_gradients
Dec 19 10:57:24     @torch.jit.script
Dec 19 10:57:24   File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 1305, in script
Dec 19 10:57:24     fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))

```

Example failure: https://app.circleci.com/jobs/github/pytorch/pytorch/4016445
## To Reproduce

This reproduces on master currenty.

cc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley

**Comment by rohan-varma** [comment]
It looks like this is broken since https://github.com/pytorch/pytorch/pull/31269. Assigning author of that PR @driazati as well as the original test author @wanchaol

**Comment by wanchaol** [comment]
https://github.com/pytorch/pytorch/pull/31492 fix this

**Comment by driazati** [comment]
Closing since the fix has landed
