### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#31483]
Although I have installed "pytorch" and "text" with python and python3 using

```
python setup.py install --user
python3 setup.py install --user
```
When I want to text_classification tutorial, I get this error

```
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import torch
  File "/home/mnaderan/.local/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /home/mnaderan/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: _Py_ZeroStruct
corrupted size vs. prev_size
Aborted (core dumped)
```
I don't know what is missing here. Any way to fix that?

cc @ezyang

**Comment by ngimel** [comment]
This looks like an error with the envoronment, can you try creating a clean virtual environment, install pytorch and torchtext according to instructions. If your problem persists, please also provide the output of environment collection script

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by mahmoodn** [comment]
Conda is not installed and I don't have root access to install it.
Right now, I see 
```
$ python ../collect_env.py                        Collecting environment information...
PyTorch version: 1.4.0a0+2488231
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: TITAN V

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] torch==1.4.0a0+2488231
[pip] torchtext==0.4.0
[pip] torchvision==0.5.0a0+5c03d59
[conda] Could not collect
```

**Comment by mahmoodn** [comment]
I have uploaded the log files here
[pt.zip](https://github.com/pytorch/pytorch/files/3985199/pt.zip)
.
As you can see, both PyTorch and Text have been successfully installed via python2.7 and python3.

**Comment by ngimel** [comment]
You env log shows that you have functional torch install with python 2, can you try running the same env collection script with python3?

**Comment by mahmoodn** [comment]
It says `collect` not found.

```
$ python3 collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.1.168
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: TITAN V

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.4.0a0+2488231
[pip3] torchtext==0.4.0
[conda] Could not collect
```

But I can not install collect via pip3
```
$ pip3 install --user collect
Collecting collect
  Downloading https://files.pythonhosted.org/packages/cf/5e/c0f0f51d081665374a2c219ea4ba23fb1e179b70dded96dc16606786d828/collect-0.1.1.tar.gz
Collecting couchdbkit>=0.5.7 (from collect)
  Downloading https://files.pythonhosted.org/packages/a1/13/9e9ff695a385c44f62b4766341b97f2bd8b596962df2a0beabf358468b70/couchdbkit-0.6.5.tar.gz (81kB)
    100% |████████████████████████████████| 81kB 1.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hg_juowy/couchdbkit/setup.py", line 25, in <module>
        long_description = file(
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hg_juowy/couchdbkit/
```

**Comment by ngimel** [comment]
It says there's no pytorch under python3:
```
PyTorch version: N/A
```
Please create a clean python 3 environment and follow either binary install instructions from pytorch.org, or installation instructions from github.

**Comment by mahmoodn** [comment]
Thank you. Seems that the installation was broken.

**Comment by xiaoyao0104** [comment]
libtorch_python.so: undefined symbol: _Py_ZeroStruct #42450
