### ISSUE TITLE
Cannot build Dockerfile

### ISSUE THREAD

**Issue by joerg84** [pytorch/pytorch#3154]
Building the docker image fails for me with the below errors.
Any advice?

```
    Install the project...
    -- Install configuration: "Release"
    -- Installing: /tmp/pip-31nirwmz-build/torch/lib/tmp_install/lib/libTHNN.so.1
    -- Installing: /tmp/pip-31nirwmz-build/torch/lib/tmp_install/lib/libTHNN.so
    -- Set runtime path of "/tmp/pip-31nirwmz-build/torch/lib/tmp_install/lib/libTHNN.so.1" to ""
    -- Installing: /tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THNN/THNN.h
    -- Installing: /tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THNN/generic/THNN.h
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Removing -DNDEBUG from compile flags
    -- TH_LIBRARIES: /tmp/pip-31nirwmz-build/torch/lib/tmp_install/lib/libTH.so.1
    -- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "5.5")
    -- Checking prototype magma_get_sgeqrf_nb for MAGMA_V2 - True
    -- Compiling with MAGMA support
    -- MAGMA INCLUDE DIRECTORIES: /opt/conda/envs/pytorch-py3.6/include
    -- MAGMA LIBRARIES: /opt/conda/envs/pytorch-py3.6/lib/libmagma.a
    -- MAGMA V2 check: 1
    -- got cuda version 8.0
    -- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
    -- CUDA_NVCC_FLAGS:  -DTH_INDEX_BASE=0 -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include   -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/TH -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THC   -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THS -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THCS   -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THPP -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THNN   -I/tmp/pip-31nirwmz-build/torch/lib/tmp_install/include/THCUNN;-Xfatbin -compress-all;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_61,code=compute_61;-DCUDA_HAS_FP16=1
    -- THC_SO_VERSION: 1
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        ATEN_LIBRARIES
        CMAKE_DEBUG_POSTFIX
        CMAKE_INSTALL_LIBDIR
        NCCL_EXTERNAL
        NO_CUDA
        THCS_LIBRARIES
        THCUNN_LIBRARIES
        THCUNN_SO_VERSION
        THC_LIBRARIES
        THD_SO_VERSION
        THNN_LIBRARIES
        THNN_SO_VERSION
        THPP_LIBRARIES
        THS_LIBRARIES
        TH_SO_VERSION
        cwrap_files
        nanopb_BUILD_GENERATOR

```
    -- Build files have been written to: /tmp/pip-31nirwmz-build/torch/lib/build/THC
    [  1%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
    [  2%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
    [  3%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
    [  4%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
    [  6%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
    [  7%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
    [  8%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
    [  9%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
    [ 10%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
    [ 12%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o
    [ 13%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o
    [ 14%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o
    [ 15%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o
    [ 17%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathReduce.cu.o
    [ 18%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathScan.cu.o
    [ 19%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorIndex.cu.o
    [ 20%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorConv.cu.o
    [ 21%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorRandom.cu.o
    [ 23%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorScatterGather.cu.o
    [ 24%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o
    [ 25%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorSort.cu.o
    [ 26%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorTypeUtils.cu.o
    [ 28%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCSortUtils.cu.o
    [ 29%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMode.cu.o
    Killed
    CMake Error at THC_generated_THCTensorMode.cu.o.cmake:267 (message):
      Error generating file
      /tmp/pip-31nirwmz-build/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMode.cu.o```

```
Command "/opt/conda/envs/pytorch-py3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-31nirwmz-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tgmvvuq5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-31nirwmz-build/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/opt/conda/envs/pytorch-py3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-31nirwmz-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tgmvvuq5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-31nirwmz-build/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 1```

**Comment by ngimel** [comment]
Most likely you don't have enough RAM in your system.
