### ISSUE TITLE
TorchBind broken on rocm

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#31551]
with https://github.com/pytorch/pytorch/pull/29501

```
20:15:47 ======================================================================
20:15:47 ERROR: test_torchbind (__main__.TestScript)
20:15:47 ----------------------------------------------------------------------
20:15:47 Traceback (most recent call last):
20:15:47   File "test_jit.py", line 4561, in test_torchbind
20:15:47     test_equality(f, lambda x: x)
20:15:47   File "test_jit.py", line 4553, in test_equality
20:15:47     obj1 = f()
20:15:47   File "test_jit.py", line 4558, in f
20:15:47     val = torch.classes._TorchScriptTesting_Foo(5, 3)
20:15:47   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/_classes.py", line 9, in __getattr__
20:15:47     proxy = torch._C._get_custom_class_python_wrapper(attr)
20:15:47 RuntimeError: Class _TorchScriptTesting_Foo not registered!
20:15:47 
20:15:47 ----------------------------------------------------------------------
```

**Comment by peterjc123** [comment]
Also on Windows: https://app.circleci.com/jobs/github/pytorch/pytorch/4048833

**Comment by mruberry** [comment]
Master looks green. Is this fixed or a flaky test issue? (If flaky, please add the flaky test label.)

**Comment by peterjc123** [comment]
@mruberry The windows tests are disabled so the CI is green.

**Comment by mruberry** [comment]
That is surprising. Do we have an issue for these test suites being disabled? 

Also, when were they disabled and why?

**Comment by peterjc123** [comment]
Because the naming of the tests is wrong. We are trying to revert it in https://github.com/pytorch/pytorch/pull/30897.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
