### ISSUE TITLE
[Error] Distributed training

### ISSUE THREAD

**Issue by chongruo** [pytorch/pytorch#31576]
encounter an error when using distributed training. Not sure how to fix it. 

envs:  pytorch-1.2 + cuda10.0

```shell
loading annotations into memory...
Done (t=14.32s)
creating index...
index created!
loading annotations into memory...
Done (t=0.47s)
creating index...
index created!
Initializing weights...
123124312312
223124312312
Begin training!

Traceback (most recent call last):
  File "train.py", line 540, in <module>
    train()
  File "train.py", line 305, in train
    for datum in data_loader:
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self.sampler_iter)  # may raise StopIteration
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/utils/data/distributed.py", line 48, in __iter__
    indices = torch.randperm(len(self.dataset), generator=g).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch-1.2/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch-1.2/bin/python', '-u', 'train.py', '--local_rank=0', '--config=yolact_resnet50_config']' returned non-zero exit status 1.
```

cc @SsnL @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by rohan-varma** [comment]
Hi, unless you are reporting a specific bug, please use the forums (https://discuss.pytorch.org/) for questions about code (it would also be helpful to post the script that leads to this error).
