### ISSUE TITLE
Bug in ForkingPickler for multiprocessing spawn context for shared storages on Linux

### ISSUE THREAD

**Issue by alxmopo3ov** [pytorch/pytorch#31571]
Hello!

This code 

```python
import torch
import multiprocessing


def _mp_foo(*args, **kwargs):
    pass


if __name__ == '__main__':
    ctx = multiprocessing.get_context("spawn")

    t = torch.randn(100)
    t1 = t.narrow(0, 0, 10)
    t2 = t.narrow(0, 0, 10)
    t3 = t.narrow(0, 10, 20)

    p = ctx.Process(
        target=_mp_foo,
        args=(t1, t2, t3),
        daemon=True
    )
    p.start()
    p.join()
```

Ends up with

```
Traceback (most recent call last):
  File "spawn_dup.py", line 22, in <module>
    p.start()
  File "/home/alxmopo3ov/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/alxmopo3ov/anaconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/alxmopo3ov/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/alxmopo3ov/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/alxmopo3ov/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    cmd, self._fds)
  File "/home/alxmopo3ov/anaconda3/lib/python3.7/multiprocessing/util.py", line 420, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep
```

I have not completely investigated the problem, but looks like that issue in ForkingPickler.

When spawning new process, forking pickler for tensors sends several file descriptors for shared tensors. Here https://github.com/google/python-subprocess32/blob/master/_posixsubprocess.c#L129 CPython checks that file descriptors list does not have duplicates.

If we insert prints here https://github.com/python/cpython/blob/master/Lib/multiprocessing/popen_spawn_posix.py#L47 
before and after reduction.dump (which is actually call for ForkingPickler), for this script, you will see this ends up using three identical ids, which corresponds to the same storage of three passed tensors. 

System:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

I have not read the tensors reduction code yet, but I guess this issue should not be hard to fix

**Comment by Evpok** [comment]
I have been tracing this a bit and it boils down to [`reduce_storage`](https://github.com/pytorch/pytorch/blob/e75fb4356b752097d093c7013ba85c9eb82961ef/torch/multiprocessing/reductions.py#L322) calling [`mp.reduction.DupFd`](https://github.com/python/cpython/blob/077061a7b24917aaf31057885c69919c5a553c88/Lib/multiprocessing/reduction.py#L191) which in turn calls [`mp.popen_spawn_posix.Popen.duplicate_for_child`](https://github.com/python/cpython/blob/c09a9f56c08d80567454cae6f78f738a89e1ae94/Lib/multiprocessing/popen_spawn_posix.py#L34), which appends the fd to its internal list of tracked fds even it if is already there.

Now I am far out of my depth here but it seems that either duplicate fds should not be added in the first place in `reduce_storage` or the fd list should be sanitized by the ForkingPickler before passing them to the spawned process. I have no idea where to start with this, though.

Still, I am curious: why does this not happen more often when using multiprocessing? What is preventing this situation?

**Comment by Evpok** [comment]
One non-obvious situation where this could happen is when unbinding tensors, I ran into this when doing something boiling down to

```python
 t = torch.randn(3, 5, 7)
l = t.unbind(0)
p = ctx.Process(
    target=_mp_foo,
    args=(l,),
    daemon=True
)
```

**Comment by danpovey** [comment]
I have spent quite a long time trying to debug this issue.  It happens for me when using a DataLoader with num_workers >= 1, when the dataset contains objects from our project k2 (specifically: our type k2.RaggedInt, which is actually _k2.RaggedInt from a pybind11-wrapped C++ library).  It only happens when using `torch.multiprocessing.set_start_method('spawn')`.  (We have to spawn, for other reasons related to DDP).   _k2.RaggedInt defines its pickling as follows, returning a tuple of torch tensors (it has been changed since, but in the same spirit, only using 2 not 3 tensors).
```
  pyclass.def(py::pickle(
      [](const PyClass &obj) {
        DeviceGuard guard(obj.Context());
        K2_CHECK_EQ(obj.NumAxes(), 2)
            << "Only support Ragged with NumAxes() == 2 for now";
        Array1<int32_t> row_splits1 = obj.RowSplits(1);
        Array1<int32_t> row_ids1 = obj.RowIds(1);
        Array1<T> values = obj.values;
        return py::make_tuple(ToTorch(row_splits1), ToTorch(row_ids1),
                              ToTorch(values));  // these are Torch tensors
      },
      [](py::tuple t) {
        K2_CHECK_EQ(t.size(), 3) << "Invalid state";
        torch::Tensor row_splits1_tensor = t[0].cast<torch::Tensor>();
        DeviceGuard guard(GetContext(row_splits1_tensor));
        Array1<int32_t> row_splits1 = FromTorch<int32_t>(row_splits1_tensor);
        torch::Tensor row_ids1_tensor = t[1].cast<torch::Tensor>();
        Array1<int32_t> row_ids1 = FromTorch<int32_t>(row_ids1_tensor);
        torch::Tensor values_tensor = t[2].cast<torch::Tensor>();
        Array1<T> values = FromTorch<T>(values_tensor);
        RaggedShape shape = RaggedShape2(&row_splits1, &row_ids1, -1);
        PyClass obj(shape, values);
        return obj;
    }
```
The initial error, like yours, is: `ValueError: bad value(s) in fds_to_keep`.  If I suppress that by changing the system library multiprocessing/util.py around line 426 to read:
```
    import _posixsubprocess
    passfds = tuple(sorted(list(map(int, passfds))))
```
... to remove duplicate fds that will cause the immediate error, the error becomes as follows (sorry, I have added various debug statements to print stuff out, so these stack traces wouldn't necessarily be printed out with unmodified code):
```
python3 test_dataset.py 
[813354, 830896, 147170, 836198, 869728, 170092, 176124, 1004626, 791734, 533432, 737790, 501646, 243824, 112002, 316174, 622708, 174012, 123116, 994246, 943904, 635162, 122970, 826376, 183272, 497032, 954156, 7957\
08, 106384, 632300, 199554, 69260, 930330, 822724, 467738, 976740, 391252, 356044, 455946, 317078, 746510, 510692, 52306, 584620, 795604, 946090, 126382, 842768, 319360, 606592, 838386, 375824, 911366, 729012, 1584\
02, 684342, 877354, 144092, 552440, 882082, 116954, 368902, 451618, 387764, 452130, 246392, 490014, 80050, 126604]
size= 1010457 , fd= 60 , cls= <class 'torch.IntStorage'> , exception traceback is:
Traceback (most recent call last):
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 288, in rebuild_storage_fd
    storage = cls._new_shared_fd(fd, size)
RuntimeError: unable to resize file <filename not specified> to the right size
Current traceback is
File "<string>", line 1, in <module>
File "/usr/lib/python3.8/multiprocessing/spawn.py", line 117, in spawn_main
    exitcode = _main(fd, parent_sentinel)
File "/usr/lib/python3.8/multiprocessing/spawn.py", line 127, in _main
    self = reduction.pickle.load(from_parent)
File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 295, in rebuild_storage_fd
    for line in traceback.format_stack():
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 127, in _main
    self = reduction.pickle.load(from_parent)
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 297, in rebuild_storage_fd
    raise e
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 288, in rebuild_storage_fd
    storage = cls._new_shared_fd(fd, size)
RuntimeError: unable to resize file <filename not specified> to the right size
Exception is:  unable to resize file <filename not specified> to the right size
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 117, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 131, in _main
    raise e
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 127, in _main
    self = reduction.pickle.load(from_parent)
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 297, in rebuild_storage_fd
    raise e
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 288, in rebuild_storage_fd
    storage = cls._new_shared_fd(fd, size)
RuntimeError: unable to resize file <filename not specified> to the right size
Traceback (most recent call last):
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
```
So the key error is: `RuntimeError: unable to resize file <filename not specified> to the right size`, and in this case we have `size= 1010457 , fd= 60` and the `cls` is a `torch.IntStorage`.  This is in the line:
```
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 288, in rebuild_storage_fd
    storage = cls._new_shared_fd(fd, size)
```
However, I don't understand the stack traces at all.  It seems like rebuild_storage_fd in torch's multiprocessing/reductions.py is being called directly from:
```
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 127, in _main
    self = reduction.pickle.load(from_parent)
```
i.e. from the system library, but if you follow what 'reduction.pickle' is in spawn.py, it just goes to 'pickle' in /usr/lib/python3.8/multiprocessing/context.py, which is just an import of the system package `pickle`.  So it seems by some strange mechanism, this rebuild_storage_fd is ultimately being called from the pickle package-- I guess via some pickle class object, but IDK how we lost the stack trace of that. I did my best to print out the stack trace by changing torch's reductions.py to read:
```
def rebuild_storage_fd(cls, df, size):
    fd = df.detach()
    try:
        storage = storage_from_cache(cls, fd_id(fd))
        if storage is not None:
            return storage
        storage = cls._new_shared_fd(fd, size)
        shared_cache[fd_id(fd)] = StorageWeakRef(storage)
        return storage
    except Exception as e:
        print("size=", size, ", fd=", fd, ", cls=", cls, ", exception traceback is:")
        traceback.print_exc()
        print("Current traceback is")
        for line in traceback.format_stack():
            print(line.strip())
        raise e
    finally:
        os.close(fd)
```
(added "except" block).
So anyway, it's clear that something is going wrong with pickling objects, but I don't know what.
Looking at the code for `_new_shared_fd`, which is defined in Torch, it looks like the main reason it might
fail, given that the fd and size are both positive integers, is that the system call `dup` fails, and I think
the most likely reason that might fail is that the file descriptor given was not valid, i.e. was not an open file
descriptor.  At least it doesn't look like a ulimit problem and the file descriptor is in the right range, so
I think that's the only possible failure mode.

Possibly something went wrong in a forked pickling process, but all traces of the errors were lost somehow?


My torch version is 1.7.1+cu101.
