### ISSUE TITLE
torch nightly CPU (1.4.0.dev20191223) breaks torchvision: std::bad_alloc

### ISSUE THREAD

**Issue by tgaddair** [pytorch/pytorch#31597]
## 🐛 Bug

Installing the latest nightly torch on MacOS and importing torchvision fails with a `std::bad_alloc`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/env/latest/lib/python3.7/site-packages/torchvision/__init__.py", line 10, in <module>
    from .extension import _HAS_OPS
  File "/home/user/env/latest/lib/python3.7/site-packages/torchvision/extension.py", line 50, in <module>
    _check_cuda_version()
  File "/hom/user/env/latest/lib/python3.7/site-packages/torchvision/extension.py", line 29, in _check_cuda_version
    _version = torch.ops.torchvision._cuda_version()
MemoryError: std::bad_alloc
```

## To Reproduce

1. `pip install --pre torch torchvision -v -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`
2. `python -c "import torchvision"`

Versions:

torch: 1.4.0.dev20191223
torchvision: 0.5.0.dev20191223

NOTE that rolling back to torch==1.4.0.dev20191219 does not exhibit this error.

On Linux, we observe similar failures (segfault).

cc @ezyang @gchanan @zou3519 @fmassa

**Comment by gchanan** [comment]
@fmassa can you look at this?

**Comment by ezyang** [comment]
Ping me if you need help on this

**Comment by mattip** [comment]
By now the whole stack of software installed has changed, and does not segfault on my (linux) machine:
```
$ virtualenv /tmp/venv
$ source /tmp/venv/bin/activate
$ pip install --pre torch torchvision -v -f \
    https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
$ python -c "import torchvision"
# no segfault
```

```
$pip list
Package     Version              
----------- ---------------------
future      0.18.2               
numpy       1.19.0rc1            
Pillow      7.1.2                
pip         20.0.2               
setuptools  45.2.0               
torch       1.6.0.dev20200521+cpu
torchvision 0.7.0.dev20200520+cpu
wheel       0.34.2               
```
