### ISSUE TITLE
'torch.load' report 'bad pickle data'

### ISSUE THREAD

**Issue by hnuhchen** [pytorch/pytorch#31615]
## To Reproduce

Hello, everyone. I am using pytorch1.0.1 to load pretrained models.
According to torch/serialization.py,
```
Example:
        >>> torch.load('tensors.pt')
        # Load all tensors onto the CPU
        >>> torch.load('tensors.pt', map_location=torch.device('cpu'))
        # Load all tensors onto the CPU, using a function
        >>> torch.load('tensors.pt', map_location=lambda storage, loc: storage)
        # Load all tensors onto GPU 1
        >>> torch.load('tensors.pt', map_location=lambda storage, loc: storage.cuda(1))
        # Map tensors from GPU 1 to GPU 0
        >>> torch.load('tensors.pt', map_location={'cuda:1':'cuda:0'})
        # Load tensor from io.BytesIO object
        >>> with open('tensor.pt') as f:
                buffer = io.BytesIO(f.read())
        >>> torch.load(buffer)
```
It means that i can read pth files in bytes, and then call io.BytesIO(). 'torch.load' can load the buffer because 'io.BytesIO' is a file-like object. 
But when i test the [pth file](https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth), it failed, the detailed information is
```
Traceback (most recent call last):
  File "test1.py", line 24, in <module>
    model_params = torch.load(pth_buf, map_location='cpu')
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: bad pickle data
```

my code is 
```
with open('./model/alexnet/ch/alexnet-owt-4df8aa71.pth', 'rb') as f:
    file_buf = f.read()
pth_buf = io.BytesIO(file_buf)
model_params = torch.load(pth_buf, map_location='cpu')
```

Notice that i must use pth buffer rather than pth file.

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):  1.0.1
 - OS (e.g., Linux):  ubuntu16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.5.2
 - CUDA/cuDNN version: no
 - GPU models and configuration: no
 - Any other relevant information:

**Comment by mruberry** [comment]
Can you provide a complete, minimal snippet demonstrating the issue? It would be helpful to see how, exactly, you're hitting the error you describe.

**Comment by hnuhchen** [comment]
@mruberry 
hello, here is minimal snippet.
the pth file is [file](https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth), 
you can try it.
```
with open('./model/alexnet/ch/alexnet-owt-4df8aa71.pth', 'rb') as f:
    file_buf = f.read()
pth_buf = io.BytesIO(file_buf)
model_params = torch.load(pth_buf, map_location='cpu')
```

**Comment by hnuhchen** [comment]
Hello, @mruberry, did you reproduce the problem? Could you tell me the reason of the problem and how to solve the problem?
Thank you very much.

**Comment by mruberry** [comment]
I cannot reproduce this issue when I create a pth file.

I have not tried with yours. Is it possible your pth wasn't saved properly?

**Comment by hnuhchen** [comment]
@mruberry
Thank you for your answer.

Actually, not all pytorch models can lead to this error.  You can try this model [alexnet](https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth), then you will reproduce this error.

**Comment by mruberry** [comment]
Thanks @hnuhchen, do you have a script that creates this file, too? It would be helpful to see how the pth is created.

**Comment by hnuhchen** [comment]
@mruberry The code is here. https://pytorch.org/docs/stable/_modules/torchvision/models/alexnet.html
Maybe the model is a pytorch official model

**Comment by mruberry** [comment]
I'm still not able to reproduce this, sorry :(

I can create the AlexNet model, save it to a file, and run your snippet to load the file without incident.

**Comment by stgzr** [comment]
Same issue. Please download via "https://download.pytorch.org/models/resnet50-19c8e357.pth" then you will meet "_pickle.UnpicklingError: unpickling stack underflow", using python3

**Comment by stgzr** [comment]
``` python
import io
import torch


with open("resnet50-19c8e357.pth", "rb") as fd:
    buf = io.BytesIO(fd.read())
    
state_dict = torch.load(buf, "cpu")
```
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

**Comment by mruberry** [comment]
Got it. I can reproduce this! 

However I can still use torch.load() on the actual file without issue. Is there some reason why you want to use this approach instead? Maybe we should just update the example to not include this case?

**Comment by stgzr** [comment]
> Got it. I can reproduce this!
> 
> However I can still use torch.load() on the actual file without issue. Is there some reason why you want to use this approach instead? Maybe we should just update the example to not include this case?

In my case, I need to load the model remotely, so I just get the object then read it into an `io.BytesIO` then use `torch.load`. But not all of the model files have this issue, I suppose there is something wrong with the pth files such as [resnet50-19c8e357.pth](https://download.pytorch.org/models/resnet50-19c8e357.pth).

**Comment by mruberry** [comment]
I see. Thanks for adding that context. After I download the pth I can save it to a file and successfully load it using `io.BytesIO(fd.read())`, do you see that, too? 

I wonder if PyTorch stopped being able to pth files serialized by older PyTorch versions using this method.

**Comment by mruberry** [comment]
We should add a test ensuring that old pth files can be read as expected by newer PyTorch versions.
