### ISSUE TITLE
No variables after importing model to onnx

### ISSUE THREAD

**Issue by TheArheus** [pytorch/pytorch#31705]
Hello, I cannot export my PyTorch model correctly. Creating `model.onnx` don't cause any problems, but I have only one variable after exporting it.

Here is my model:
```
def predict_transform(prediction, inp_dim, anchors, num_classes, CUDA=True):
    batch_size = prediction.size(0)
    stride = inp_dim // prediction.size(2)
    grid_size = inp_dim // stride
    bbox_attrs = 5 + num_classes
    num_anchors = len(anchors)

    prediction = prediction.view(batch_size, bbox_attrs * num_anchors, grid_size * grid_size)
    prediction = prediction.transpose(1, 2).contiguous()
    prediction = prediction.view(batch_size, grid_size * grid_size * num_anchors, bbox_attrs)
    # anchors = [(a[0]/stride, a[1]/stride) for a in anchors]

    # Sigmoid the  centre_X, centre_Y. and object confidencce
    prediction = torch.cat((torch.sigmoid(prediction[:, :, 0:1]), prediction[:, :, 1:]), dim=2)
    prediction = torch.cat((torch.sigmoid(prediction[:, :, 1:2]), prediction[:, :, 2:]), dim=2)
    prediction = torch.cat((torch.sigmoid(prediction[:, :, 3:4]), prediction[:, :, 4:]), dim=2)
    # prediction[:,:,1] = torch.sigmoid(prediction[:,:,1])
    # prediction[:,:,4] = torch.sigmoid(prediction[:,:,4])

    # Add the center offsets
    grid = torch.arange(grid_size)
    a, b = torch.meshgrid(grid, grid)
    x_offset = a.type(torch.FloatTensor).view(-1, 1)
    y_offset = b.type(torch.FloatTensor).view(-1, 1)

    if CUDA:
        x_offset = x_offset.cuda()
        y_offset = y_offset.cuda()

    x_y_offset = torch.cat((x_offset, y_offset), 1).repeat(1, num_anchors).view(-1, 2).unsqueeze(0)

    prediction = torch.cat((prediction[:, :, :2], prediction[:, :, :2].add(x_y_offset)), dim=2)
    # prediction[:,:,:2] += x_y_offset

    # log space transform height and the width
    anchors = torch.FloatTensor(anchors)

    # if CUDA: anchors = anchors.cuda()
    anchors = anchors.repeat(grid_size * grid_size, 1).unsqueeze(0)

    prediction = torch.cat((prediction[:, :, 2:4], torch.exp(prediction[:, :, 2:4]) * anchors), dim=2)
    # prediction[:,:,2:4] = torch.exp(prediction[:,:,2:4])*anchors
    prediction = torch.cat((prediction[:, :, 5:5 + num_classes], torch.sigmoid(prediction[:, :, 5:5 + num_classes])))
    # prediction[:,:,5: 5 + num_classes] = torch.sigmoid(prediction[:,:, 5 : 5 + num_classes])
    prediction = torch.cat((prediction[:, :, :4], prediction[:, :, :4] * stride))
    # prediction[:,:,:4] *= stride

    return prediction


class EmptyLayer(nn.Module):
    def __init__(self):
        super(EmptyLayer, self).__init__()


class DetectionLayer(nn.Module):
    def __init__(self, anchors):
        super(DetectionLayer, self).__init__()
        self.anchors = anchors

    def forward(self, x, inp_dim, num_classes, confidence):
        x = x.data
        prediction = x
        #stride = inp_dim // prediction.size(2)
        #self.anchors = [(a[0] / stride, a[1] / stride) for a in self.anchors]
        prediction = predict_transform(prediction, inp_dim, self.anchors, num_classes, confidence)
        return prediction


class MaxPoolStride1(nn.Module):
    def __init__(self, kernel_size):
        super(MaxPoolStride1, self).__init__()
        self.kernel_size = kernel_size
        self.pad = kernel_size - 1

    def forward(self, x):
        padded_x = F.pad(x, (0, self.pad, 0, self.pad), mode="replicate")
        pooled_x = nn.MaxPool2d(self.kernel_size, self.pad)(padded_x)
        return pooled_x


class DarkNet(nn.Module):
    def __init__(self, cfgfile):
        super(DarkNet, self).__init__()
        self.blocks = parse_cfg(cfgfile)
        self.net_info, self.module_list, self.input_names = create_module(self.blocks)

    def get_blocks(self):
        return self.blocks

    def get_moduel_list(self):
        return self.module_list

    def get_input_names(self):
        return self.input_names

    def forward(self, x, CUDA=False):
        detections = []
        modules = self.blocks[1:]
        outputs = {}
        write = 0

        for i, module in enumerate(modules):
            module_type = (module["type"])
            if module_type == "convolutional" or module_type == "upsample" or module_type == "maxpool":
                x = self.module_list[i](x)
                outputs[i] = x

            elif module_type == "route":
                layers = module["layers"]
                layers = [int(a) for a in layers]

                if (layers[0]) > 0:
                    layers[0] = layers[0] - i

                if len(layers) == 1:
                    x = outputs[i + (layers[0])]
                else:
                    if (layers[1]) > 0:
                        layers[1] = layers[1] - i

                    map1 = outputs[i + layers[0]]
                    map2 = outputs[i + layers[1]]

                    x = torch.cat((map1, map2), 1)
                outputs[i] = x

            elif module_type == "shortcut":
                from_ = int(module["from"])
                x = outputs[i - 1] + outputs[i + from_]
                outputs[i] = x

            elif module_type == 'yolo':
                anchors = self.module_list[i][0].anchors
                # Get the input dimensions
                inp_dim = int(self.net_info["height"])

                # Get the number of classes
                num_classes = int(module["classes"])

                # Output the result
                x = x.data
                x = predict_transform(x, inp_dim, anchors, num_classes, CUDA)

                #if type(x) == int:
                #    continue

                if not write:
                    detections = x
                    write = 1
                else:
                    detections = torch.cat((detections, x), 1)

            #outputs[i] = outputs[i - 1]
            outputs[i] = x
        return detections

    def load_weights(self, weightfile):
        fp = open(weightfile, "rb")
        header = np.fromfile(fp, dtype=np.int32, count=5)
        self.header = torch.from_numpy(header)
        self.seen = self.header[3]

        weights = np.fromfile(fp, dtype=np.float32)
        ptr = 0

        for i in range(len(self.module_list)):
            module_type = self.blocks[i + 1]["type"]

            if module_type == "convolutional":
                model = self.module_list[i]
                try:
                    batch_normalize = int(self.blocks[i + 1]["batch_normalize"])
                except:
                    batch_normalize = 0

                conv = model[0]
                if batch_normalize:
                    bn = model[1]
                    num_bn_biases = bn.bias.numel()

                    bn_biases = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases

                    bn_weights = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases

                    bn_running_mean = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases

                    bn_running_var = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases

                    bn_biases = bn_biases.view_as(bn.bias.data)
                    bn_weights = bn_weights.view_as(bn.weight.data)
                    bn_running_mean = bn_running_mean.view_as(bn.running_mean)
                    bn_running_var = bn_running_var.view_as(bn.running_var)

                    bn.bias.data.copy_(bn_biases)
                    bn.weight.data.copy_(bn_weights)
                    bn.running_mean.copy_(bn_running_mean)
                    bn.running_var.copy_(bn_running_var)
                else:
                    num_biases = conv.bias.numel()

                    conv_biases = torch.from_numpy(weights[ptr:ptr + num_biases])
                    ptr += num_biases

                    conv_biases = conv_biases.view_as(conv.bias.data)

                    conv.bias.data.copy_(conv_biases)
                num_weights = conv.weight.numel()

                conv_weights = torch.from_numpy(weights[ptr:ptr + num_weights])
                ptr += num_weights

                conv_weights = conv_weights.view_as(conv.weight.data)
                conv.weight.data.copy_(conv_weights)

net = DarkNet("cfg/yolov3.cfg")
net.load_weights("yolov3.weights")
for param in net.parameters():
    param.requires_grad = False
# in_val = get_test_input()
# pred = net(in_val, torch.cuda.is_available())

input_names = net.get_input_names()
output_names = ["output1"]

model = torchvision.models.alexnet(pretrained=True)
print(model)

torch.onnx._export(net, torch.ones((1, 3, 224, 224)), "model.onnx", export_params=True, verbose=False, opset_version=7)
```

For verbose = True in export methos I have next onnx model:
```
graph(%input.1 : Float(1, 3, 224, 224),
      %1 : Float(32, 3, 3, 3),
      %2 : Float(32),
      %3 : Float(32),
      %4 : Float(32),
      %5 : Float(32),
      %6 : Long(),
      %7 : Float(64, 32, 3, 3),
      %8 : Float(64),
      %9 : Float(64),
      %10 : Float(64),
      %11 : Float(64),
      %12 : Long(),
      %13 : Float(32, 64, 1, 1),
      %14 : Float(32),
      %15 : Float(32),
      %16 : Float(32),
      %17 : Float(32),
      %18 : Long(),
      %19 : Float(64, 32, 3, 3),
      %20 : Float(64),
      %21 : Float(64),
      %22 : Float(64),
      %23 : Float(64),
      %24 : Long(),
      %25 : Float(128, 64, 3, 3),
      %26 : Float(128),
      %27 : Float(128),
      %28 : Float(128),
      %29 : Float(128),
      %30 : Long(),
      %31 : Float(64, 128, 1, 1),
      %32 : Float(64),
      %33 : Float(64),
      %34 : Float(64),
      %35 : Float(64),
      %36 : Long(),
      %37 : Float(128, 64, 3, 3),
      %38 : Float(128),
      %39 : Float(128),
      %40 : Float(128),
      %41 : Float(128),
      %42 : Long(),
      %43 : Float(64, 128, 1, 1),
      %44 : Float(64),
      %45 : Float(64),
      %46 : Float(64),
      %47 : Float(64),
      %48 : Long(),
      %49 : Float(128, 64, 3, 3),
      %50 : Float(128),
      %51 : Float(128),
      %52 : Float(128),
      %53 : Float(128),
      %54 : Long(),
      %55 : Float(256, 128, 3, 3),
      %56 : Float(256),
      %57 : Float(256),
      %58 : Float(256),
      %59 : Float(256),
      %60 : Long(),
      %61 : Float(128, 256, 1, 1),
      %62 : Float(128),
      %63 : Float(128),
      %64 : Float(128),
      %65 : Float(128),
      %66 : Long(),
      %67 : Float(256, 128, 3, 3),
      %68 : Float(256),
      %69 : Float(256),
      %70 : Float(256),
      %71 : Float(256),
      %72 : Long(),
      %73 : Float(128, 256, 1, 1),
      %74 : Float(128),
      %75 : Float(128),
      %76 : Float(128),
      %77 : Float(128),
      %78 : Long(),
      %79 : Float(256, 128, 3, 3),
      %80 : Float(256),
      %81 : Float(256),
      %82 : Float(256),
      %83 : Float(256),
      %84 : Long(),
      %85 : Float(128, 256, 1, 1),
      %86 : Float(128),
      %87 : Float(128),
      %88 : Float(128),
      %89 : Float(128),
      %90 : Long(),
      %91 : Float(256, 128, 3, 3),
      %92 : Float(256),
      %93 : Float(256),
      %94 : Float(256),
      %95 : Float(256),
      %96 : Long(),
      %97 : Float(128, 256, 1, 1),
      %98 : Float(128),
      %99 : Float(128),
      %100 : Float(128),
      %101 : Float(128),
      %102 : Long(),
      %103 : Float(256, 128, 3, 3),
      %104 : Float(256),
      %105 : Float(256),
      %106 : Float(256),
      %107 : Float(256),
      %108 : Long(),
      %109 : Float(128, 256, 1, 1),
      %110 : Float(128),
      %111 : Float(128),
      %112 : Float(128),
      %113 : Float(128),
      %114 : Long(),
      %115 : Float(256, 128, 3, 3),
      %116 : Float(256),
      %117 : Float(256),
      %118 : Float(256),
      %119 : Float(256),
      %120 : Long(),
      %121 : Float(128, 256, 1, 1),
      %122 : Float(128),
      %123 : Float(128),
      %124 : Float(128),
      %125 : Float(128),
      %126 : Long(),
      %127 : Float(256, 128, 3, 3),
      %128 : Float(256),
      %129 : Float(256),
      %130 : Float(256),
      %131 : Float(256),
      %132 : Long(),
      %133 : Float(128, 256, 1, 1),
      %134 : Float(128),
      %135 : Float(128),
      %136 : Float(128),
      %137 : Float(128),
      %138 : Long(),
      %139 : Float(256, 128, 3, 3),
      %140 : Float(256),
      %141 : Float(256),
      %142 : Float(256),
      %143 : Float(256),
      %144 : Long(),
      %145 : Float(128, 256, 1, 1),
      %146 : Float(128),
      %147 : Float(128),
      %148 : Float(128),
      %149 : Float(128),
      %150 : Long(),
      %151 : Float(256, 128, 3, 3),
      %152 : Float(256),
      %153 : Float(256),
      %154 : Float(256),
      %155 : Float(256),
      %156 : Long(),
      %157 : Float(512, 256, 3, 3),
      %158 : Float(512),
      %159 : Float(512),
      %160 : Float(512),
      %161 : Float(512),
      %162 : Long(),
      %163 : Float(256, 512, 1, 1),
      %164 : Float(256),
      %165 : Float(256),
      %166 : Float(256),
      %167 : Float(256),
      %168 : Long(),
      %169 : Float(512, 256, 3, 3),
      %170 : Float(512),
      %171 : Float(512),
      %172 : Float(512),
      %173 : Float(512),
      %174 : Long(),
      %175 : Float(256, 512, 1, 1),
      %176 : Float(256),
      %177 : Float(256),
      %178 : Float(256),
      %179 : Float(256),
      %180 : Long(),
      %181 : Float(512, 256, 3, 3),
      %182 : Float(512),
      %183 : Float(512),
      %184 : Float(512),
      %185 : Float(512),
      %186 : Long(),
      %187 : Float(256, 512, 1, 1),
      %188 : Float(256),
      %189 : Float(256),
      %190 : Float(256),
      %191 : Float(256),
      %192 : Long(),
      %193 : Float(512, 256, 3, 3),
      %194 : Float(512),
      %195 : Float(512),
      %196 : Float(512),
      %197 : Float(512),
      %198 : Long(),
      %199 : Float(256, 512, 1, 1),
      %200 : Float(256),
      %201 : Float(256),
      %202 : Float(256),
      %203 : Float(256),
      %204 : Long(),
      %205 : Float(512, 256, 3, 3),
      %206 : Float(512),
      %207 : Float(512),
      %208 : Float(512),
      %209 : Float(512),
      %210 : Long(),
      %211 : Float(256, 512, 1, 1),
      %212 : Float(256),
      %213 : Float(256),
      %214 : Float(256),
      %215 : Float(256),
      %216 : Long(),
      %217 : Float(512, 256, 3, 3),
      %218 : Float(512),
      %219 : Float(512),
      %220 : Float(512),
      %221 : Float(512),
      %222 : Long(),
      %223 : Float(256, 512, 1, 1),
      %224 : Float(256),
      %225 : Float(256),
      %226 : Float(256),
      %227 : Float(256),
      %228 : Long(),
      %229 : Float(512, 256, 3, 3),
      %230 : Float(512),
      %231 : Float(512),
      %232 : Float(512),
      %233 : Float(512),
      %234 : Long(),
      %235 : Float(256, 512, 1, 1),
      %236 : Float(256),
      %237 : Float(256),
      %238 : Float(256),
      %239 : Float(256),
      %240 : Long(),
      %241 : Float(512, 256, 3, 3),
      %242 : Float(512),
      %243 : Float(512),
      %244 : Float(512),
      %245 : Float(512),
      %246 : Long(),
      %247 : Float(256, 512, 1, 1),
      %248 : Float(256),
      %249 : Float(256),
      %250 : Float(256),
      %251 : Float(256),
      %252 : Long(),
      %253 : Float(512, 256, 3, 3),
      %254 : Float(512),
      %255 : Float(512),
      %256 : Float(512),
      %257 : Float(512),
      %258 : Long(),
      %259 : Float(1024, 512, 3, 3),
      %260 : Float(1024),
      %261 : Float(1024),
      %262 : Float(1024),
      %263 : Float(1024),
      %264 : Long(),
      %265 : Float(512, 1024, 1, 1),
      %266 : Float(512),
      %267 : Float(512),
      %268 : Float(512),
      %269 : Float(512),
      %270 : Long(),
      %271 : Float(1024, 512, 3, 3),
      %272 : Float(1024),
      %273 : Float(1024),
      %274 : Float(1024),
      %275 : Float(1024),
      %276 : Long(),
      %277 : Float(512, 1024, 1, 1),
      %278 : Float(512),
      %279 : Float(512),
      %280 : Float(512),
      %281 : Float(512),
      %282 : Long(),
      %283 : Float(1024, 512, 3, 3),
      %284 : Float(1024),
      %285 : Float(1024),
      %286 : Float(1024),
      %287 : Float(1024),
      %288 : Long(),
      %289 : Float(512, 1024, 1, 1),
      %290 : Float(512),
      %291 : Float(512),
      %292 : Float(512),
      %293 : Float(512),
      %294 : Long(),
      %295 : Float(1024, 512, 3, 3),
      %296 : Float(1024),
      %297 : Float(1024),
      %298 : Float(1024),
      %299 : Float(1024),
      %300 : Long(),
      %301 : Float(512, 1024, 1, 1),
      %302 : Float(512),
      %303 : Float(512),
      %304 : Float(512),
      %305 : Float(512),
      %306 : Long(),
      %307 : Float(1024, 512, 3, 3),
      %308 : Float(1024),
      %309 : Float(1024),
      %310 : Float(1024),
      %311 : Float(1024),
      %312 : Long(),
      %313 : Float(512, 1024, 1, 1),
      %314 : Float(512),
      %315 : Float(512),
      %316 : Float(512),
      %317 : Float(512),
      %318 : Long(),
      %319 : Float(1024, 512, 3, 3),
      %320 : Float(1024),
      %321 : Float(1024),
      %322 : Float(1024),
      %323 : Float(1024),
      %324 : Long(),
      %325 : Float(512, 1024, 1, 1),
      %326 : Float(512),
      %327 : Float(512),
      %328 : Float(512),
      %329 : Float(512),
      %330 : Long(),
      %331 : Float(1024, 512, 3, 3),
      %332 : Float(1024),
      %333 : Float(1024),
      %334 : Float(1024),
      %335 : Float(1024),
      %336 : Long(),
      %337 : Float(512, 1024, 1, 1),
      %338 : Float(512),
      %339 : Float(512),
      %340 : Float(512),
      %341 : Float(512),
      %342 : Long(),
      %343 : Float(1024, 512, 3, 3),
      %344 : Float(1024),
      %345 : Float(1024),
      %346 : Float(1024),
      %347 : Float(1024),
      %348 : Long(),
      %349 : Float(255, 1024, 1, 1),
      %350 : Float(255),
      %351 : Float(256, 512, 1, 1),
      %352 : Float(256),
      %353 : Float(256),
      %354 : Float(256),
      %355 : Float(256),
      %356 : Long(),
      %357 : Float(256, 768, 1, 1),
      %358 : Float(256),
      %359 : Float(256),
      %360 : Float(256),
      %361 : Float(256),
      %362 : Long(),
      %363 : Float(512, 256, 3, 3),
      %364 : Float(512),
      %365 : Float(512),
      %366 : Float(512),
      %367 : Float(512),
      %368 : Long(),
      %369 : Float(256, 512, 1, 1),
      %370 : Float(256),
      %371 : Float(256),
      %372 : Float(256),
      %373 : Float(256),
      %374 : Long(),
      %375 : Float(512, 256, 3, 3),
      %376 : Float(512),
      %377 : Float(512),
      %378 : Float(512),
      %379 : Float(512),
      %380 : Long(),
      %381 : Float(256, 512, 1, 1),
      %382 : Float(256),
      %383 : Float(256),
      %384 : Float(256),
      %385 : Float(256),
      %386 : Long(),
      %387 : Float(512, 256, 3, 3),
      %388 : Float(512),
      %389 : Float(512),
      %390 : Float(512),
      %391 : Float(512),
      %392 : Long(),
      %393 : Float(255, 512, 1, 1),
      %394 : Float(255),
      %395 : Float(128, 256, 1, 1),
      %396 : Float(128),
      %397 : Float(128),
      %398 : Float(128),
      %399 : Float(128),
      %400 : Long(),
      %401 : Float(128, 384, 1, 1),
      %402 : Float(128),
      %403 : Float(128),
      %404 : Float(128),
      %405 : Float(128),
      %406 : Long(),
      %407 : Float(256, 128, 3, 3),
      %408 : Float(256),
      %409 : Float(256),
      %410 : Float(256),
      %411 : Float(256),
      %412 : Long(),
      %413 : Float(128, 256, 1, 1),
      %414 : Float(128),
      %415 : Float(128),
      %416 : Float(128),
      %417 : Float(128),
      %418 : Long(),
      %419 : Float(256, 128, 3, 3),
      %420 : Float(256),
      %421 : Float(256),
      %422 : Float(256),
      %423 : Float(256),
      %424 : Long(),
      %425 : Float(128, 256, 1, 1),
      %426 : Float(128),
      %427 : Float(128),
      %428 : Float(128),
      %429 : Float(128),
      %430 : Long(),
      %431 : Float(256, 128, 3, 3),
      %432 : Float(256),
      %433 : Float(256),
      %434 : Float(256),
      %435 : Float(256),
      %436 : Long(),
      %437 : Float(255, 256, 1, 1),
      %438 : Float(255)):
  %439 : Float(4, 3087, 0) = onnx::Constant[value=[ Variable[CPUFloatType]{4,3087,0} ]]()
  return (%439)
```

How can I correctly export my model to onnx model. Thank you

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by bpstark** [comment]
@TheArheus this issue appears to be a continuation of #2513, Are these related? Additionally to reproduce this issue, can you please provide a fully runnable set of code, In the code snippet you provide you have errors in the Darknet __init__ function
bug.py|92 col 23 error| [undefined-variable] Undefined variable 'parse_cfg'
bug.py|93 col 61 error| [undefined-variable] Undefined variable 'create_module'
I would also need the cfg and weights file you are referencing in the code.

Again however looking at the code that I do see and the output, be aware that tracing will completely unroll all loops, and remove all branches. Instead you may want to try something along the lines of

`
net_scripted = torch.jit.script(DarkNet())
dummy_input = torch.ones((1, 3, 224, 224))
output = net_scripted(dummy_input)

torch.onnx.export(net_scripted, 
                  (dummy_input), 
                  'model.onnx', 
                  verbose=True,
                  input_names=['input_data'], 
                  example_outputs=output
                 )
`

**Comment by TheArheus** [comment]
Yeah, They're related. And here is my full code source
https://drive.google.com/file/d/1apvEplsAmXomkd5TbSYA3m78PvDXci1z/view?usp=sharing

**Comment by bpstark** [comment]
@TheArheus looking at your code I did still have to make some changes to be able to run the code at all, that said it looks like one of the major issues is how you are handling the yolo modules, in that you use 
```python
x = x.data
```
which causes the tensor to not be able to continue tracing. Take a look at the code I have attached, which should help to produce a more correct graph. Also note: after running through the code I do not think you actually do need scripting, as your loop and conditionals appear to be on static data rather than on the input, thus will not change even if input size changes.

https://gist.github.com/bpstark/78e17ed98648ccbbf90e486903185724

**Comment by TheArheus** [comment]
I tried your code, but have this errors:
```
C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\utils.py:617: UserWarning: ONNX export failed on ATen operator meshgrid because torch.onnx.symbolic_opset9.meshgrid does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "C:/Users/1/PycharmProjects/untitled/yolo.py", line 348, in <module>
    main()
  File "C:/Users/1/PycharmProjects/untitled/yolo.py", line 335, in main
    example_outputs=output)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "C:\Users\1\Anaconda3\lib\site-packages\torch\onnx\symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'meshgrid'
```

**Comment by bpstark** [comment]
@TheArheus It appears that meshgrid is a rather new addition to the opset registry, I am not yet sure as to what release it will be a part of let me investigate further.

**Comment by bpstark** [comment]
@TheArheus support for meshgrid was added into V1.4 of pytorch so you can upgrade to that and you should be able to export the model.

**Comment by TheArheus** [comment]
@bpstark Ok, I used another environment with torch nightly. And now I have a problem with `nn.Upsample()` function while creating `Sequential`:
F:\Env\Anaconda\lib\site-packages\torch\nn\modules\upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "C:/Users/hell_/PycharmProjects/untitled/yolo.py", line 362, in <module>
    main()
  File "C:/Users/hell_/PycharmProjects/untitled/yolo.py", line 342, in main
    output = net(in_val, False)
  File "F:\Env\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/hell_/PycharmProjects/untitled/yolo.py", line 229, in forward
    x = torch.cat((map1, map2), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 2 and 14 in dimension 2 at c:\n\pytorch_1559129895673\work\aten\src\th\generic/THTensorMoreMath.cpp:1307

**Comment by TheArheus** [comment]
Ok, I just reworked it a little bit and It's finaly exported well. Thank you very much

**Comment by TheArheus** [comment]
Hi @bpstark, sorry for interrupting you, but after exporting my model to onnx I got new error while importing it to keras. Here is my error:
```
DEBUG:onnx2keras:concat:Concat Keras layers.
WARNING:onnx2keras:concat:!!! IMPORTANT INFORMATION !!!
WARNING:onnx2keras:concat:Something goes wrong with concat layers. Will use TF fallback.
WARNING:onnx2keras:concat:---
Traceback (most recent call last):
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx2keras\reshape_layers.py", line 110, in convert_concat
    name=keras_name)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\keras\layers\merge.py", line 705, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 745, in __call__
    inputs = nest.map_structure(_convert_non_tensor, inputs)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\util\nest.py", line 535, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\util\nest.py", line 535, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 743, in _convert_non_tensor
    return ops.convert_to_tensor(x)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type NoneType).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/1/PycharmProjects/untitled/onnx_.py", line 6, in <module>
    k_model = onnx2keras.onnx_to_keras(model, ["input_data"])
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx2keras\converter.py", line 177, in onnx_to_keras
    keras_names
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx2keras\reshape_layers.py", line 122, in convert_concat
    layers[node_name] = lambda_layer(layer_input)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 745, in __call__
    inputs = nest.map_structure(_convert_non_tensor, inputs)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\util\nest.py", line 535, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\util\nest.py", line 535, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 743, in _convert_non_tensor
    return ops.convert_to_tensor(x)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\1\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type NoneType).
```
Thank you

**Comment by bpstark** [comment]
@TheArheus I tried to run the session via ORT, and I was able to run successfully. This seems like an issue with the Keras layer then.

**Comment by TheArheus** [comment]
@bpstark I tried only standart method:
```
import onnx
import onnx2keras

model = onnx.load_model("model.onnx")
k_model = onnx2keras.onnx_to_keras(model, ["input_data"])
```

So, this is should be better way?:
```
import onnxruntime as ort

sess = ort.InferenceSession('model.onnx')
```

**Comment by TheArheus** [comment]
Hi, can you   provide a code you used  for importing onnx modell to keras?

**Comment by jeremycochoy** [comment]
From what I see, it looks like your `onnx2keras` is having troubles loading your ONNX model. Since the model seams to run with ort, it is quite likely the torch->ONNX conversion went fine and your ONNX model behave as expected. Try to update your onnx2keras library. If it still doesn't work, you should probably reach the onnx2keras team as they may have a better understanding of the situation. :)
