### ISSUE TITLE
unable to open shared memory object </torch_5962_408180057> in read-write mode

### ISSUE THREAD

**Issue by ever4244** [pytorch/pytorch#31701]
I encountered a "unable to open shared memory object </torch_5962_408180057> in read-write mode" when running codes in https://github.com/raymondhs/fairseq-laser/issues/2

The script I used:
```
export CUDA_VISIBLE_DEVICES="0,1"
fairseq-train data-bin/iwslt17.de_fr.en.bpe16k/ \
  --max-epoch 17 \
  --task translation_laser \
  --lang-pairs de-en,fr-en \
  --arch laser_lstm_artetxe \
  --encoder-num-layers 5 \
  --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
  --lr 0.001 --lr-scheduler fixed \
  --weight-decay 0.0 --criterion cross_entropy \
  --save-dir checkpoints/laser_lstm5_newcodetest2GPU \
  --update-freq 8 \
  --no-progress-bar --log-interval 50 \
  --max-tokens 200 \
  --ddp-backend=no_c10d 
``
error report:

```
i.bash 
| distributed init (rank 0): tcp://localhost:11279
| distributed init (rank 1): tcp://localhost:11279
| initialized host wei-desktop as rank 1
| initialized host wei-desktop as rank 0
Namespace(adam_betas='(0.9, 0.98)', adam_eps=1e-08, arch='laser_lstm_artetxe', best_checkpoint_metric='loss', bpe=None, bucket_cap_mb=25, clip_norm=0.0, cpu=False, criterion='cross_entropy', curriculum=0, data='data-bin/iwslt17.de_fr.en.bpe16k/', dataset_impl=None, ddp_backend='no_c10d', decoder_dropout=0.1, decoder_embed_dim=320, decoder_hidden_dim=2048, decoder_langtok=False, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method='tcp://localhost:11279', distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=2, empty_cache_freq=0, encoder_dropout=0.1, encoder_embed_dim=320, encoder_hidden_dim=512, encoder_langtok=None, encoder_num_layers=5, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_updates=-1, keep_last_epochs=-1, lang_embed_dim=32, lang_embeddings=True, lang_pairs='de-en,fr-en', lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=50, lr=[0.001], lr_scheduler='fixed', lr_shrink=0.1, max_epoch=17, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=200, max_tokens_valid=200, max_update=0, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=True, no_save=False, no_save_optimizer_state=False, num_workers=1, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints/laser_lstm5_newcodetest2GPU', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation_laser', tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, train_subset='train', update_freq=[8], upsample_primary=1, use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_updates=0, weight_decay=0.0)
| [de] dictionary: 13880 types
| [en] dictionary: 13880 types
| [fr] dictionary: 13880 types
| loaded 1080 examples from: data-bin/iwslt17.de_fr.en.bpe16k/valid.de-en.de
| loaded 1080 examples from: data-bin/iwslt17.de_fr.en.bpe16k/valid.de-en.en
| data-bin/iwslt17.de_fr.en.bpe16k/ valid de-en 1080 examples
| loaded 1210 examples from: data-bin/iwslt17.de_fr.en.bpe16k/valid.fr-en.fr
| loaded 1210 examples from: data-bin/iwslt17.de_fr.en.bpe16k/valid.fr-en.en
| data-bin/iwslt17.de_fr.en.bpe16k/ valid fr-en 1210 examples
/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq/models/fairseq_model.py:280: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  for key in self.keys
LaserLSTMModel(
  (models): ModuleDict(
    (de-en): FairseqModel(
      (encoder): LaserLSTMEncoder(
        (embed_tokens): Embedding(13880, 320, padding_idx=1)
        (lstm): LSTM(320, 512, num_layers=5, dropout=0.1, bidirectional=True)
      )
      (decoder): LaserLSTMDecoder(
        (embed_tokens): Embedding(13880, 320, padding_idx=1)
        (embed_lang): Embedding(4, 32, padding_idx=0)
        (lstm): LSTM(1376, 2048)
        (sentemb_hidden_proj): Linear(in_features=1024, out_features=2048, bias=True)
        (sentemb_cell_proj): Linear(in_features=1024, out_features=2048, bias=True)
        (fc_out): Linear(in_features=2048, out_features=13880, bias=True)
      )
    )
    (fr-en): FairseqModel(
      (encoder): LaserLSTMEncoder(
        (embed_tokens): Embedding(13880, 320, padding_idx=1)
        (lstm): LSTM(320, 512, num_layers=5, dropout=0.1, bidirectional=True)
      )
      (decoder): LaserLSTMDecoder(
        (embed_tokens): Embedding(13880, 320, padding_idx=1)
        (embed_lang): Embedding(4, 32, padding_idx=0)
        (lstm): LSTM(1376, 2048)
        (sentemb_hidden_proj): Linear(in_features=1024, out_features=2048, bias=True)
        (sentemb_cell_proj): Linear(in_features=1024, out_features=2048, bias=True)
        (fc_out): Linear(in_features=2048, out_features=13880, bias=True)
      )
    )
  )
)
| model laser_lstm_artetxe, criterion CrossEntropyCriterion
| num. model params: 98202296 (num. trained: 98202296)
/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq/models/fairseq_model.py:280: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  for key in self.keys
| training on 2 GPUs
| max tokens per GPU = 200 and max sentences per GPU = None
| no existing checkpoint found checkpoints/laser_lstm5_newcodetest2GPU/checkpoint_last.pt
| loading train data for epoch 0
| loaded 209522 examples from: data-bin/iwslt17.de_fr.en.bpe16k/train.de-en.de
| loaded 209522 examples from: data-bin/iwslt17.de_fr.en.bpe16k/train.de-en.en
| data-bin/iwslt17.de_fr.en.bpe16k/ train de-en 209522 examples
| loaded 236653 examples from: data-bin/iwslt17.de_fr.en.bpe16k/train.fr-en.fr
| loaded 236653 examples from: data-bin/iwslt17.de_fr.en.bpe16k/train.fr-en.en
| data-bin/iwslt17.de_fr.en.bpe16k/ train fr-en 236653 examples
Traceback (most recent call last):
  File "/home/wei/anaconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq_cli/train.py", line 329, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/wei/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/wei/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/wei/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq_cli/train.py", line 296, in distributed_main
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq_cli/train.py", line 86, in main
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq_cli/train.py", line 126, in train
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq/progress_bar.py", line 181, in __iter__
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq/data/iterators.py", line 314, in __next__
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq/data/iterators.py", line 43, in __next__
  File "/home/wei/LIWEI_workspace/fairseq_liweimod/fairseq/fairseq/data/iterators.py", line 36, in __iter__
  File "/home/wei/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
  File "/home/wei/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File "/home/wei/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
  File "/home/wei/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_6038_3481262419> in read-write mode
```


`

I have tried 3 things:
1: set max number of segments  from 4096 to 16384

------ Shared Memory Limits --------
max number of segments = 16384
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014398509481980
min seg size (bytes) = 1

2: put model, data and task files into fairseq folder instead of using --user-dir 
https://github.com/microsoft/MASS/tree/master/MASS-summarization#other-questions

3: I also test to run a fairseq standard program with 2GPU without problem:

```
export CUDA_VISIBLE_DEVICES="0,1"
fairseq-train $data_root \
    --max-epoch 50 \
    --ddp-backend=no_c10d \
    --task multilingual_translation --lang-pairs en-es,es-en,es-en \
    --arch multilingual_transformer_iwslt_de_en \
    --share-decoders --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' \
    --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr '1e-09' \
    --warmup-updates 4000 --warmup-init-lr '1e-07' \
    --label-smoothing 0.1 --criterion label_smoothed_cross_entropy \
    --dropout 0.3 --weight-decay 0.0001 \
    --save-dir checkpoints/multilingual_transformer_UNtest2GPU \
    --max-tokens 4000 \
    --update-freq 8
```



My environment:

    fairseq Version master
    PyTorch Version 10.1
    OS linux
    How you installed fairseq conda
    Python version: 3.7
    CUDA/cuDNN version: 10.1
    GPU models and configuration: 1080ti

**Comment by agolynski** [comment]
Could you create an issue in https://github.com/pytorch/fairseq?
