### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by yc-zc** [pytorch/pytorch#31758]
## To Reproduce

1. python train.py
1.

dataloader = DataLoader(
                                   dataset,
                                   batch_size=1,
                                   num_workers=0,
                                   pin_memory=True)
for index, item in enumerate(dataloader):
## Expected behavior
train

## Environment
Ubuntu 16.04 LTS
Conda 4.3.30 Python 3.7.5
PyTorch 1.0.0, 1.1.0, installed using command provided on PyTorch.org
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by yc-zc** [comment]
PyTorch 1.0.0 is also tried, the error is the same

**Comment by Usama-Zafar** [comment]
You are providing number of workers as 0? Shouldn't it be atleast 1?

**Comment by yc-zc** [comment]
> You are providing number of workers as 0? Shouldn't it be atleast 1?

No

**Comment by ezyang** [comment]
Can you please try with a more recent version of PyTorch? 1.1 is somewhat old at this point. Also, your code sample is not complete, which means we cannot easily try to reproduce it. If you can post the entire file in question that would be helpful.

**Comment by ezyang** [comment]
If also possible (once you switch to a newer version of PyTorch), attaching gdb and getting a backtrace at the segfault point would also be helpful.

**Comment by SsnL** [comment]
In particular, it would be great if you can provide your dataset code. Since you are not using multiprocessing dataloading, it is likely that the segfault actually came from that.

**Comment by yc-zc** [comment]
> Can you please try with a more recent version of PyTorch? 1.1 is somewhat old at this point. Also, your code sample is not complete, which means we cannot easily try to reproduce it. If you can post the entire file in question that would be helpful.

Thank you all for the response, since this is actually not my issue (my friend does not have a github account), it would take longer to get all the things you guys require prepared.

**Comment by yc-zc** [comment]
```python
# Copyright (c) SenseTime. All Rights Reserved.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import argparse
import logging
import os
import time
import math
import json
import random
import numpy as np

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tensorboardX import SummaryWriter
from torch.nn.utils import clip_grad_norm_
from torch.utils.data.distributed import DistributedSampler

from pysot.utils.lr_scheduler import build_lr_scheduler
from pysot.utils.log_helper import init_log, print_speed, add_file_handler
#from pysot.utils.distributed import dist_init, DistModule, reduce_gradients, average_reduce, get_rank, get_world_size
from pysot.utils.model_load import load_pretrain, restore_from
from pysot.utils.average_meter import AverageMeter
from pysot.utils.misc import describe, commit
from pysot.models.model_builder import ModelBuilder
from pysot.datasets.dataset import TrkDataset
from pysot.core.config import cfg


logger = logging.getLogger('global')
parser = argparse.ArgumentParser(description='siamrpn tracking')
parser.add_argument('--cfg', type=str, default='config.yaml',
                    help='configuration of tracking')
parser.add_argument('--seed', type=int, default=123456,
                    help='random seed')
parser.add_argument('--local_rank', type=int, default=0,
                    help='compulsory for pytorch launcer')
args = parser.parse_args()


def seed_torch(seed=0):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def build_data_loader():
    logger.info("build train dataset")
    # train_dataset
    train_dataset = TrkDataset()
    logger.info("build dataset done")
    train_sampler = None

    train_loader = DataLoader(train_dataset,
                              batch_size=cfg.TRAIN.BATCH_SIZE,
                              num_workers=cfg.TRAIN.NUM_WORKERS,
                              pin_memory=True,
                              sampler=train_sampler)
    return train_loader


def build_opt_lr(model, current_epoch=0):
    if current_epoch >= cfg.BACKBONE.TRAIN_EPOCH:
        for layer in cfg.BACKBONE.TRAIN_LAYERS:
            for param in getattr(model.backbone, layer).parameters():
                param.requires_grad = True
            for m in getattr(model.backbone, layer).modules():
                if isinstance(m, nn.BatchNorm2d):
                    m.train()
    else:
        for param in model.backbone.parameters():
            param.requires_grad = False
        for m in model.backbone.modules():
            if isinstance(m, nn.BatchNorm2d):
                m.eval()

    trainable_params = []
    trainable_params += [{'params': filter(lambda x: x.requires_grad,
                                           model.backbone.parameters()),
                          'lr': cfg.BACKBONE.LAYERS_LR * cfg.TRAIN.BASE_LR}]

    if cfg.ADJUST.ADJUST:
        trainable_params += [{'params': model.neck.parameters(),
                              'lr': cfg.TRAIN.BASE_LR}]

    trainable_params += [{'params': model.rpn_head.parameters(),
                          'lr': cfg.TRAIN.BASE_LR}]

    if cfg.MASK.MASK:
        trainable_params += [{'params': model.mask_head.parameters(),
                              'lr': cfg.TRAIN.BASE_LR}]

    if cfg.REFINE.REFINE:
        trainable_params += [{'params': model.refine_head.parameters(),
                              'lr': cfg.TRAIN.LR.BASE_LR}]

    optimizer = torch.optim.SGD(trainable_params,
                                momentum=cfg.TRAIN.MOMENTUM,
                                weight_decay=cfg.TRAIN.WEIGHT_DECAY)

    lr_scheduler = build_lr_scheduler(optimizer, epochs=cfg.TRAIN.EPOCH)
    lr_scheduler.step(cfg.TRAIN.START_EPOCH)
    return optimizer, lr_scheduler


def log_grads(model, tb_writer, tb_index):
    def weights_grads(model):
        grad = {}
        weights = {}
        for name, param in model.named_parameters():
            if param.grad is not None:
                grad[name] = param.grad
                weights[name] = param.data
        return grad, weights

    grad, weights = weights_grads(model)
    feature_norm, rpn_norm = 0, 0
    for k, g in grad.items():
        _norm = g.data.norm(2)
        weight = weights[k]
        w_norm = weight.norm(2)
        if 'feature' in k:
            feature_norm += _norm ** 2
        else:
            rpn_norm += _norm ** 2

        tb_writer.add_scalar('grad_all/'+k.replace('.', '/'),
                             _norm, tb_index)
        tb_writer.add_scalar('weight_all/'+k.replace('.', '/'),
                             w_norm, tb_index)
        tb_writer.add_scalar('w-g/'+k.replace('.', '/'),
                             w_norm/(1e-20 + _norm), tb_index)
    tot_norm = feature_norm + rpn_norm
    tot_norm = tot_norm ** 0.5
    feature_norm = feature_norm ** 0.5
    rpn_norm = rpn_norm ** 0.5

    tb_writer.add_scalar('grad/tot', tot_norm, tb_index)
    tb_writer.add_scalar('grad/feature', feature_norm, tb_index)
    tb_writer.add_scalar('grad/rpn', rpn_norm, tb_index)


def train(train_loader, model, optimizer, lr_scheduler, tb_writer):
    cur_lr = lr_scheduler.get_cur_lr()
    #rank = get_rank()
    rank = 0

    average_meter = AverageMeter()

    def is_valid_number(x):
        return not(math.isnan(x) or math.isinf(x) or x > 1e4)

    #world_size = get_world_size()
    world_size = 1
    num_per_epoch = len(train_loader.dataset) // \
        cfg.TRAIN.EPOCH // (cfg.TRAIN.BATCH_SIZE * world_size)
    start_epoch = cfg.TRAIN.START_EPOCH
    epoch = start_epoch

    if not os.path.exists(cfg.TRAIN.SNAPSHOT_DIR):
        os.makedirs(cfg.TRAIN.SNAPSHOT_DIR)

    logger.info("model\n{}".format(describe(model)))
    end = time.time()
    for idx, data in enumerate(train_loader):
        if epoch != idx // num_per_epoch + start_epoch:
            epoch = idx // num_per_epoch + start_epoch

            if True:
                torch.save(
                        {'epoch': epoch,
                         'state_dict': model.state_dict(),
                         'optimizer': optimizer.state_dict()},
                        cfg.TRAIN.SNAPSHOT_DIR+'/checkpoint_e%d.pth' % (epoch))

            if epoch == cfg.TRAIN.EPOCH:
                return

            if cfg.BACKBONE.TRAIN_EPOCH == epoch:
                logger.info('start training backbone.')
                optimizer, lr_scheduler = build_opt_lr(model, epoch)
                logger.info("model\n{}".format(describe(model)))

            lr_scheduler.step(epoch)
            cur_lr = lr_scheduler.get_cur_lr()
            logger.info('epoch: {}'.format(epoch+1))

        tb_idx = idx
        if idx % num_per_epoch == 0 and idx != 0:
            for idx, pg in enumerate(optimizer.param_groups):
                logger.info('epoch {} lr {}'.format(epoch+1, pg['lr']))
                if rank == 0:
                    tb_writer.add_scalar('lr/group{}'.format(idx+1),
                                         pg['lr'], tb_idx)

        #data_time = average_reduce(time.time() - end)
        data_time = time.time() - end
        if rank == 0:
            tb_writer.add_scalar('time/data', data_time, tb_idx)

        outputs = model(data)
        loss = outputs['total_loss']

        if is_valid_number(loss.data.item()):
            optimizer.zero_grad()
            loss.backward()
            #reduce_gradients(model)

            if rank == 0 and cfg.TRAIN.LOG_GRADS:
                log_grads(model, tb_writer, tb_idx)

            # clip gradient
            clip_grad_norm_(model.parameters(), cfg.TRAIN.GRAD_CLIP)
            optimizer.step()

        batch_time = time.time() - end
        batch_info = {}
        batch_info['batch_time'] = batch_time
        batch_info['data_time'] = data_time
        for k, v in sorted(outputs.items()):
           batch_info[k] = v.data.item()
        average_meter.update(**batch_info)

        if rank == 0:
            for k, v in batch_info.items():
                tb_writer.add_scalar(k, v, tb_idx)

            if (idx+1) % cfg.TRAIN.PRINT_FREQ == 0:
                info = "Epoch: [{}][{}/{}] lr: {:.6f}\n".format(
                            epoch+1, (idx+1) % num_per_epoch,
                            num_per_epoch, cur_lr)
                for cc, (k, v) in enumerate(batch_info.items()):
                    if cc % 2 == 0:
                        info += ("\t{:s}\t").format(
                                getattr(average_meter, k))
                    else:
                        info += ("{:s}\n").format(
                                getattr(average_meter, k))
                logger.info(info)
                print_speed(idx+1+start_epoch*num_per_epoch,
                            average_meter.batch_time.avg,
                            cfg.TRAIN.EPOCH * num_per_epoch)
        end = time.time()


def main():
    '''
    rank, world_size = dist_init()
    '''
    logger.info("init done")


    # load cfg
    cfg.merge_from_file(args.cfg)
    rank = 0
    if rank == 0:
        if not os.path.exists(cfg.TRAIN.LOG_DIR):
            os.makedirs(cfg.TRAIN.LOG_DIR)
        init_log('global', logging.INFO)
        if cfg.TRAIN.LOG_DIR:
            add_file_handler('global',
                             os.path.join(cfg.TRAIN.LOG_DIR, 'logs.txt'),
                             logging.INFO)

        logger.info("Version Information: \n{}\n".format(commit()))
        logger.info("config \n{}".format(json.dumps(cfg, indent=4)))

    # create model
    model = ModelBuilder().cuda().train()
    #dist_model = DistModule(model)

    # load pretrained backbone weights
    if cfg.BACKBONE.PRETRAINED:
        cur_path = os.path.dirname(os.path.realpath(__file__))
        backbone_path = os.path.join(cur_path, '../', cfg.BACKBONE.PRETRAINED)
        load_pretrain(model.backbone, backbone_path)

    # create tensorboard writer
    if rank == 0 and cfg.TRAIN.LOG_DIR:
        tb_writer = SummaryWriter(cfg.TRAIN.LOG_DIR)
    else:
        tb_writer = None

    # build dataset loader
    train_loader = build_data_loader()

    # build optimizer and lr_scheduler
    #optimizer, lr_scheduler = build_opt_lr(dist_model.module, cfg.TRAIN.START_EPOCH)
    optimizer, lr_scheduler = build_opt_lr(model,cfg.TRAIN.START_EPOCH)

    # resume training
    if cfg.TRAIN.RESUME:
        logger.info("resume from {}".format(cfg.TRAIN.RESUME))
        assert os.path.isfile(cfg.TRAIN.RESUME), \
            '{} is not a valid file.'.format(cfg.TRAIN.RESUME)
        model, optimizer, cfg.TRAIN.START_EPOCH = \
            restore_from(model, optimizer, cfg.TRAIN.RESUME)

    # load pretrained_models
    elif cfg.TRAIN.PRETRAINED:
        load_pretrain(model, cfg.TRAIN.PRETRAINED)
    #dist_model = DistModule(model)
    logger.info(lr_scheduler)
    logger.info("model prepare done")

   #strat train
    #train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
    train(train_loader, model, optimizer, lr_scheduler, tb_writer)


if __name__ == '__main__':
    seed_torch(args.seed)
    main()

```

**Comment by lanpa** [comment]
Looks like you have multiple pytorch versions installed in the environment. Can you confirm that?

**Comment by yc-zc** [comment]
> Looks like you have multiple pytorch versions installed in the environment. Can you confirm that?

Yes, we have tried different versions of pytorch to see if it has been fixed.

**Comment by lanpa** [comment]
@yc-zc Please use a clean env so that only one version of pytorch is installed.

**Comment by boakotoko** [comment]
Do you solve this problem？I have the same problem.Can you tell me how to do this
?

**Comment by ezyang** [comment]
High priority to attempt to run the repro and get the crash.

**Comment by albanD** [comment]
cc @VitalyFedyunin who is looking into dataloader as well.

**Comment by zyc-ai** [comment]
> @yc-zc Please use a clean env so that only one version of pytorch is installed.

Each pytorch is installed in a seperate env. And actually I don't think it is possible to install two pytorch in a single env.

**Comment by zyc-ai** [comment]
> > @yc-zc Please use a clean env so that only one version of pytorch is installed.
> 
> Each pytorch is installed in a seperate env. And actually I don't think it is possible to install two pytorch in a single conda env.

**Comment by kurtamohler** [comment]
For anyone who tries to run the repro script, you'll have to install pysot from its github repo, here: https://github.com/STVIR/pysot
However, the script depends on a `config.yaml` file that I don't have:
```
$ PYTHONPATH=$HOME/develop/pysot:$PYTHONPATH python ~/tmp/tmp.py 
[2020-09-07 13:46:55,055-rk0-tmp.py#259] init done
Traceback (most recent call last):
  File "/home/endoplasm/tmp/tmp.py", line 323, in <module>
    main()
  File "/home/endoplasm/tmp/tmp.py", line 263, in main
    cfg.merge_from_file(args.cfg)
  File "/home/endoplasm/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
```

@zyc-ai, could you please post that `config.yaml` file so we can run the script?

**Comment by zyc-ai** [comment]
> For anyone who tries to run the repro script, you'll have to install pysot from its github repo, here: https://github.com/STVIR/pysot
> Note that there is a conda-forge package called pysot, but that won't work, it's either out of date or unrelated.
> 
> However, the script depends on a `config.yaml` file that I don't have:
> 
> ```
> $ PYTHONPATH=$HOME/develop/pysot:$PYTHONPATH python ~/tmp/tmp.py 
> [2020-09-07 13:46:55,055-rk0-tmp.py#259] init done
> Traceback (most recent call last):
>   File "/home/endoplasm/tmp/tmp.py", line 323, in <module>
>     main()
>   File "/home/endoplasm/tmp/tmp.py", line 263, in main
>     cfg.merge_from_file(args.cfg)
>   File "/home/endoplasm/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 211, in merge_from_file
>     with open(cfg_filename, "r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
> ```
> 
> @zyc-ai, could you please post that `config.yaml` file so we can run the script?

https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr/config.yaml

**Comment by kurtamohler** [comment]
@zyc-ai, ah thanks, I didn't realize it was inside the pysot repo. I tried putting your repro script in the `experiments/siamrpn_r50_l234_dwxcorr` directory and executing it from that location. I used the `$PYTHONPATH` setting that the pysot `README.md` tells me to use. However, I get this error:

```
$ PYTHONPATH=/home/endoplasm/develop/pysot:$PYTHONPATH python repro.py
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/endoplasm/develop/pysot/pysot/datasets/../../training_dataset/vid/train.json'
```

Indeed, train.json does not exist for me:
```
$ ls /home/endoplasm/develop/pysot/pysot/datasets/../../training_dataset/vid/
gen_json.py  par_crop.py  parse_vid.py  readme.md  visual.py
```

But I noticed that there's a `readme.md` file there, which tells me to download an 86 GB file, `http://bvisionweb1.cs.unc.edu/ilsvrc2015/ILSVRC2015_VID.tar.gz`. Wow! I'll let that go over night. I'm not actually 100% sure if downloading this file is necessary, so please let me know if it's not.

**Comment by zyc-ai** [comment]
@kurtamohler Thank you very much for helping!

> Wow! I'll let that go over night. I'm not actually 100% sure if downloading this file is necessary, so please let me know if it's not.

I'm not sure if you must download the dataset, but technically you can make some data by np.random()?

**Comment by kurtamohler** [comment]
@zyc-ai, that's a good idea. However, I don't know what the randomized data should look like. Could you please provide us a reproduction script that randomly generates all the required data, so that it doesn't require all these datasets (and preferably doesn't require pySOT either).

At the moment, I think the reproduction script above takes way too much effort to run, so I'm going to stop for now. It requires the reproducer to learn the structure of part of the pySOT source tree. It requires more than 100 GB worth of datasets to be downloaded (there is at least one more dataset than what I mentioned above, maybe more), and there does not appear to be a single script or command that we can run to download all of the required datasets--instead, it requires reading the `readme` files within the dataset directories of pySOT to find out what commands need to be run in order to obtain and format the datasets.

**Comment by Infatum** [comment]
Encountered same issue  on DenseNet train  ```Batch 1153-th loss: 0.0016166185960173607
Batch 1154-th loss: 0.0008452047477476299
Batch 1155-th loss: 0.0009657655609771609
Batch 1156-th loss: 0.0006721302634105086
Batch 1157-th loss: 0.000771171529777348
Batch 1158-th loss: 0.0008306880481541157
Batch 1159-th loss: 0.0007560861995443702
Batch 1160-th loss: 0.0006361253326758742
Batch 1161-th loss: 0.0006033303216099739
Batch 1162-th loss: 0.001279963180422783
Batch 1163-th loss: 0.0005342689109966159
Batch 1164-th loss: 0.0008794516907073557
Batch 1165-th loss: 0.0005679660243913531
Batch 1166-th loss: 0.0006545549840666354
Batch 1167-th loss: 0.0005956455133855343
Batch 1168-th loss: 0.0006277130451053381
Batch 1169-th loss: 0.000554810045287013
Batch 1170-th loss: 0.00046467105858027935
Batch 1171-th loss: 0.00043926347279921174
Batch 1172-th loss: 0.001174585078842938
Batch 1173-th loss: 0.0014530051266774535
Batch 1174-th loss: 0.000631380476988852
Segmentation fault (core dumped)``` was also using DataLoader

**Comment by kurtamohler** [comment]
Thank you for letting us know @Infatum! We still need a minimal reproducer script to be able to look into this problem. If you have one, please share! Since we can't be sure yet about whether these two problems have the same root cause, could you please open a new issue and link to this one as likely to be related? Feel free to cc me

**Comment by Infatum** [comment]
> Thank you for letting us know @Infatum! We still need a minimal reproducer script to be able to look into this problem. If you have one, please share! Since we can't be sure yet about whether these two problems have the same root cause, could you please open a new issue and link to this one as likely to be related? Feel free to cc me

I've only faced it on pytorch with 11 cuda, reverted to cuda 10 and this error disappeared. Cold this behaviour mean I have too old GPU(Nvidia GeForce 1060)?

**Comment by kurtamohler** [comment]
@Infatum, CUDA 11 supports GeForce 1060, so no, your GPU is not too old. There is evidently some interaction between CUDA 11 and DataLoader that causes the crash, but we won't know how to fix it until we have a way to reproduce the crash. If you can, please post a script that reproduces the issue

**Comment by grekiki** [comment]
Attaching a code that generates random inputs and gives a segmentation fault only on GPU, should't have any dependencies

```
import numpy as np
from random import random

def sample_generator():
    while True:
        x = random()
        y = int(10*x)/10
        yield x, y

import torch
from torch import nn

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(1, 1000),
            nn.ReLU(),
            nn.Linear(1000, 1),
            nn.ReLU()
        )

    def forward(self, x):
        logits = self.linear_relu_stack(x)
        return logits

from torch.utils.data import Dataset, DataLoader
device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
print(device)

generator = sample_generator()

def random_data_dataset(length):
    raw_in = [next(generator) for _ in range(length)]
    #print(len(raw_in))

    i_data = []
    o_data = []
    for i, data in enumerate(raw_in):
        x = data[0]
        y = data[1]
        data_input = torch.zeros((1,))
        data_input[0]=x
        data_output = torch.zeros((1,))
        data_output[0]=y
        i_data.append(data_input)
        o_data.append(data_output)
    return SimDataset(length, i_data, o_data)


in_set = random_data_dataset(1000)
out_set = random_data_dataset(1000)
train_dataloader = DataLoader(in_set, batch_size=64, shuffle=True, drop_last=True)
test_dataloader = DataLoader(out_set, batch_size=64, shuffle=False)

def train_loop(dataloader, model, loss_fn, optimizer, debug):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        X = X.to(device)
        y = y.to(device)
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    if debug:
        loss = loss.item()
        print(f"loss: {loss:>10f}")


def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            X = X.to(device)
            y = y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()

    test_loss /= num_batches
    print(f"Test Error: {test_loss:>10f} \n")

model = NeuralNetwork()
model.to(device)
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

epochs = 101
print(len(train_dataloader))
print(len(test_dataloader))
for t in range(epochs):
    if t%5 == 0:
        print(f"Epoch {t}")
    train_loop(train_dataloader, model, loss_fn, optimizer, t%10==0)
    if t%5 == 0:
        test_loop(test_dataloader, model, loss_fn)
print("Done!")
```

This crashes on a GTX 1060 3GB with torch version 1.8.1+cu111

**Comment by kurtamohler** [comment]
Great, thanks @grekiki! When I run it, I get the error `NameError: name 'SimDataset' is not defined`. Do you have a definition for this class?

**Comment by grekiki** [comment]
Sorry about that, was copying from notebook cell by cell.

'''


class SimDataset(Dataset):
    def __init__(self, length, i, o):
        self.len = length
        self.i = i
        self.o = o

    def __len__(self):
        return self.len

    def __getitem__(self, idx):
        return self.i[idx], self.o[idx]
'''

**Comment by kurtamohler** [comment]
Awesome, thanks @grekiki! I can run it now, but I don't get the segfault in my environment. Would you mind running the following commands and post the results here so I can try to emulate your environment to get the error?

```bash
$ wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
$ python collect_env.py
```

**Comment by grekiki** [comment]
```
Collecting environment information...
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Jun 12 2021, 19:40:22)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060 3GB
Nvidia driver version: 460.80
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect
```

**Comment by nazmicancalik** [comment]
Any updates on this issue? @kurtamohler Thanks!

**Comment by kurtamohler** [comment]
Sorry, this dropped off my radar. The segfault doesn't happen in my environment with the latest PyTorch, but I still haven't tried older versions yet. I will try it within the next week.

What version of PyTorch are you using @nazmicancalik ?

**Comment by kurtamohler** [comment]
I've set up a couple environments to try to reproduce the issue. The environments I tried were modeled after @grekiki's environment (unfortunately, their account has been deleted now, so might never even see this).

I made a repo that has environment setup scripts to make this easier for me to manage: https://github.com/kurtamohler/pytorch-dataloader-segfault-investigation

The `test.py` script is the reproducer code that @grekiki posted.

There are two environments in that repo. Here's what they give when I run `collect_env.py`

`env0`:

<details>
<summary>Click to expand/collapse</summary>

```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-97-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.8.1+cu111              pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi
```

</details>


`env1` (the same as `env0` except that it uses CUDA 11.2 instead of 11.1):

<details>
<summary>Click to expand/collapse</summary>

```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-97-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.2.67
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.8.1+cu111              pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi
```

</details>

Neither of those environments reproduce the issue for me. These environments install pytorch with pip, since that's what @grekiki did. Out of curiousity, I also tried installing with conda, but unsurprisingly that didn't reproduce the issue either (I assume the packages are exactly the same in conda and pip).

Some notable differences between my environments and @grekiki's is that they had this driver and gpu:
```
GPU models and configuration: GPU 0: GeForce GTX 1060 3GB`
Nvidia driver version: 460.80
```

while I'm using this driver and gpu:
```
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 470.103.01
```

It's possible that if I used the same hardware and driver, I would be able to reproduce the issue. It also might be possible that @grekiki's CUDA installation was not configured the same way as mine. It's interesting that their `collect_env.py` output says this:
```
Is CUDA available: True
CUDA runtime version: Could not collect
```

while mine correctly says which CUDA version I'm using.

Since I don't have a ton of information to work with and I'm not really making any progress, I'm unassigning myself from this issue now
