### ISSUE TITLE
[ONNX] test_interpolate_downsample does not work with opset 10

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/pytorch#31750]
Flaky test disabled by https://github.com/pytorch/pytorch/pull/31751.

**Comment by Krovatkin** [comment]
There are two errors related to this test:

```
======================================================================
ERROR: test_interpolate_downsample (__main__.TestONNXRuntime_opset10)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/home/villedepommes/github/pytorches/profile_changes/test/onnx/test_pytorch_common.py", line 54, in wrapper
    return func(self)
  File "test/onnx/test_pytorch_onnx_onnxruntime.py", line 1049, in test_interpolate_downsample
    self._interpolate_tests(False)
  File "test/onnx/test_pytorch_onnx_onnxruntime.py", line 1042, in _interpolate_tests
    self._interpolate_script(xi, mode_i, False, is_upsample)
  File "test/onnx/test_pytorch_onnx_onnxruntime.py", line 1000, in _interpolate_script
    self.run_test(model, x, atol=1e-6)
  File "test/onnx/test_pytorch_onnx_onnxruntime.py", line 118, in run_test
    fixed_batch_size=fixed_batch_size)
  File "test/onnx/test_pytorch_onnx_onnxruntime.py", line 79, in run_model_test
    fixed_batch_size=fixed_batch_size)
  File "/private/home/villedepommes/miniconda3/envs/enable_tests/lib/python3.7/site-packages/torch/onnx/__init__.py", line 26, in _export
    result = utils._export(*args, **kwargs)
  File "/private/home/villedepommes/miniconda3/envs/enable_tests/lib/python3.7/site-packages/torch/onnx/utils.py", line 466, in _export
    fixed_batch_size=fixed_batch_size)
  File "/private/home/villedepommes/miniconda3/envs/enable_tests/lib/python3.7/site-packages/torch/onnx/utils.py", line 336, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/private/home/villedepommes/miniconda3/envs/enable_tests/lib/python3.7/site-packages/torch/onnx/utils.py", line 152, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/private/home/villedepommes/miniconda3/envs/enable_tests/lib/python3.7/site-packages/torch/onnx/__init__.py", line 187, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/private/home/villedepommes/miniconda3/envs/enable_tests/lib/python3.7/site-packages/torch/onnx/utils.py", line 726, in _run_symbolic_function
    n.kindOf("value")))
RuntimeError: Unsupported prim::Constant kind: `fs`. Send a bug report.

----------------------------------------------------------------------
Ran 1 test in 0.167s

FAILED (errors=1)
```


```
Dec 31 08:49:23 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset10::test_interpolate_downsample Fatal Python error: Segmentation fault
Dec 31 08:49:23 
Dec 31 08:49:23 Current thread 0x00007f1b479bb700 (most recent call first):
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 43 in repr_instance
Dec 31 08:49:23   File "/usr/lib/python3.6/reprlib.py", line 65 in repr1
Dec 31 08:49:23   File "/usr/lib/python3.6/reprlib.py", line 55 in repr
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 36 in repr
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 67 in saferepr
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 655 in repr_args
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 736 in repr_traceback_entry
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 777 in repr_traceback
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 829 in repr_excinfo
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 597 in getrepr
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/nodes.py", line 299 in _repr_failure_py
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/python.py", line 818 in repr_failure
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/reports.py", line 279 in from_item_and_call
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/runner.py", line 252 in pytest_runtest_makereport
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187 in _multicall
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 86 in <lambda>
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 92 in _hookexec
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/runner.py", line 178 in call_and_report
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/runner.py", line 95 in runtestprotocol
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/runner.py", line 80 in pytest_runtest_protocol
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187 in _multicall
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 86 in <lambda>
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 92 in _hookexec
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 258 in pytest_runtestloop
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187 in _multicall
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 86 in <lambda>
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 92 in _hookexec
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 237 in _main
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 193 in wrap_session
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 230 in pytest_cmdline_main
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187 in _multicall
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 86 in <lambda>
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 92 in _hookexec
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__
Dec 31 08:49:23   File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 90 in main
Dec 31 08:49:23   File "/usr/local/bin/pytest", line 11 in <module>
Dec 31 08:49:23 /var/lib/jenkins/workspace/scripts/onnx/test.sh: line 63: 20732 Segmentation fault      (core dumped) pytest "${args[@]}" "$top_dir/test/onnx/test_pytorch_onnx_onnxruntime.py"
```

**Comment by Krovatkin** [comment]
the first one should get fixed by https://github.com/pytorch/pytorch/pull/31503

**Comment by janeyx99** [comment]
@Krovatkin are there plans to fix the second error with this test? If not, should we just delete this test as it's been disabled for over 2 years now?

**Comment by janeyx99** [comment]
This is already disabled in the code so renaming the issue so our disable infra doesn't redundantly try disabling it.

**Comment by BowenBao** [comment]
@janeyx99 thanks for checking back, I think this issue was resolved way back and the tests were enabled. https://github.com/pytorch/pytorch/blob/9f1468ae6c8e6e3938a3f1cfb9378e11af2fd0cd/test/onnx/test_pytorch_onnx_onnxruntime.py#L2802 Closing.
