### ISSUE TITLE
torchvision transforms broken by Pillow 7.0 release

### ISSUE THREAD

**Issue by oteph** [pytorch/pytorch#31770]
## 🐛 Bug

Pillow just released 7.0.0. This breaks torchvision.transforms as the import fails:

```
Traceback (most recent call last):
  File "examples/mnist.py", line 5, in <module>
    from torchvision.transforms import (
  File "/home/felix/.local/share/virtualenvs/repro-Cd9xy9KO/lib/python3.6/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/home/felix/.local/share/virtualenvs/repro-Cd9xy9KO/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/felix/.local/share/virtualenvs/repro-Cd9xy9KO/lib/python3.6/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/felix/.local/share/virtualenvs/repro-Cd9xy9KO/lib/python3.6/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/felix/.local/share/virtualenvs/repro-Cd9xy9KO/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/felix/.local/share/virtualenvs/repro-Cd9xy9KO/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'

```
https://github.com/python-pillow/Pillow/releases

## To Reproduce
run
`from torchvision.transforms import Compose`

## Environment

torch==1.3.1
torchvision==0.4.2
torchvision==7.0.0

## Fix

I pinned pillow to version 6.2.2. After this the import works again

**Comment by peterjc123** [comment]
Please post to https://github.com/pytorch/vision/issues. thank you.

**Comment by hugovk** [comment]
Duplicate of https://github.com/pytorch/vision/issues/1712:

> We will be releasing a new version of PyTorch and torchvision early next week, so this should be soon fixed.
