### ISSUE TITLE
test_debug_info is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#31846]
https://app.circleci.com/jobs/github/pytorch/pytorch/4122172
https://app.circleci.com/jobs/github/pytorch/pytorch/4122175

```
an 03 21:59:53 ======================================================================
Jan 03 21:59:53 ERROR [300.034s]: test_debug_info (__main__.RpcTestWithSpawn)
Jan 03 21:59:53 ----------------------------------------------------------------------
Jan 03 21:59:53 Traceback (most recent call last):
Jan 03 21:59:53   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 130, in wrapper
Jan 03 21:59:53     self._join_processes(fn)
Jan 03 21:59:53   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 211, in _join_processes
Jan 03 21:59:53     self._check_return_codes(elapsed_time)
Jan 03 21:59:53   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 230, in _check_return_codes
Jan 03 21:59:53     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Jan 03 21:59:53 RuntimeError: Process 0 terminated or timed out after 300.0178077220917 seconds
```

**Comment by rohan-varma** [comment]
The error is:

```
Jan 03 21:53:38 ......Process process 0:
Jan 03 21:53:38 Traceback (most recent call last):
Jan 03 21:53:38   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
Jan 03 21:53:38     self.run()
Jan 03 21:53:38   File "/opt/python/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
Jan 03 21:53:38     self._target(*self._args, **self._kwargs)
Jan 03 21:53:38   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 198, in _run
Jan 03 21:53:38     getattr(self, test_name)()
Jan 03 21:53:38   File "/var/lib/jenkins/workspace/test/dist_utils.py", line 96, in new_test_method
Jan 03 21:53:38     return_value = old_test_method(self, *arg, **kwargs)
Jan 03 21:53:38   File "/var/lib/jenkins/workspace/test/rpc_test.py", line 1325, in test_debug_info
Jan 03 21:53:38     self.assertEqual(expected.keys(), info.keys())
Jan 03 21:53:38   File "/var/lib/jenkins/workspace/test/common_utils.py", line 867, in assertEqual
Jan 03 21:53:38     allow_inf=allow_inf)
Jan 03 21:53:38   File "/var/lib/jenkins/workspace/test/common_utils.py", line 848, in assertEqual
Jan 03 21:53:38     super(TestCase, self).assertEqual(x, y, message)
Jan 03 21:53:38   File "/opt/python/3.5/lib/python3.5/unittest/case.py", line 829, in assertEqual
Jan 03 21:53:38     assertion_func(first, second, msg=msg)
Jan 03 21:53:38   File "/opt/python/3.5/lib/python3.5/unittest/case.py", line 1202, in assertMultiLineEqual
Jan 03 21:53:38     self.fail(self._formatMessage(msg, standardMsg))
Jan 03 21:53:38   File "/opt/python/3.5/lib/python3.5/unittest/case.py", line 670, in fail
Jan 03 21:53:38     raise self.failureException(msg)
Jan 03 21:53:38 AssertionError: 'num_pending_users' != 'thread_pool_size'
Jan 03 21:53:38 - num_pending_users
Jan 03 21:53:38 + thread_pool_size
```

Seems to be related to adding `num_pending_users` in https://github.com/pytorch/pytorch/pull/31539? Although not sure why the test does not fail every time. Will investigate.

**Comment by rohan-varma** [comment]
I took a look but so far unable to reproduce with hundreds of runs. Will ssh into the CI docker to check if I can repro there.

**Comment by ezyang** [comment]
If you setup a Dr. CI rule for this you can find out how frequent the failure occurrence is. cc @kostmo

**Comment by mrshenli** [comment]
@ezyang @kostmo is there a link to how to setup a Dr. CI rule?

**Comment by kostmo** [comment]
Hi @mrshenli, I have just added some instructions [on the internal wiki](https://our.internmc.facebook.com/intern/wiki/Dr._CI/Operation/Creating_a_new_pattern_for_the_log_scanner/).

**Comment by rohan-varma** [comment]
Looks like python 3.5 only failure - it might be because of dict key ordering? https://stackoverflow.com/questions/1867861/how-to-keep-keys-values-in-same-order-as-declared
