### ISSUE TITLE
error when building pytorch 1.1.0 from source

### ISSUE THREAD

**Issue by knsong** [pytorch/pytorch#31943]
## 🐛 Bug
When building pytorch 1.1.0 from source with explicitly setting `-D_GLIBCXX_USE_CXX11_ABI=0`, I met such error:
```
pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `gloo::getCudaPCIBusID(int)'
pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```
how to solve that? 
**Without `export CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS"`**, I can build pytorch successfully, but when importing extend module which is built also from source in the same environment from python , I will meet error`my_module.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`,  and my `torch._C._GLIBCXX_USE_CXX11_ABI == True`.(referenced [here](https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627))

## To Reproduce

```
git clone https://github.com/pytorch/pytorch.git && git checkout tags/v1.1.0
... # do some change to reset the third_party submodules to the correct commit with tags/v1.1.0
export USE_NINJA=OFF
export CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS"
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Linux version 3.10.0-327.ali2012.alios7.x86_64
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
```
export USE_NINJA=OFF
export CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS"
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
```
 - Python version: 3.6.9 | Anaconda [GCC 7.3.0] on linux
 - CUDA/cuDNN version: cuda10.0
 - GPU models and configuration: nvidia tesla v100 16GB
 - gcc:  5.5.0

**Comment by zou3519** [comment]
Can you try building with NO_DISTRIBUTED=1 ?

**Comment by markdjwilliams** [comment]
I am also experiencing the same issue, with pytorch 1.3.1 and 1.4.0 (I did not test earlier versions) on CentOS 6 / gcc 6.4 when defining _GLIBCXX_USE_CXX11_ABI=0 via CFLAGS.

Configuring with either NO_DISTRIBUTED=1 or USE_GLOO=0 is my current workaround. Perhaps there are ways of addressing this by modifying gloo's cmake scripts, but I've not yet explored this. I'd like to re-enable gloo if possible.

**Comment by cheneyfan** [comment]
same error.
cmake 3.16.5
gcc 7.3
centos7

**Comment by markdjwilliams** [comment]
I'm also experiencing this issue, and I'm using the same workaround - although I would ultimately like to build with support for distributed training.

**Comment by esghif** [comment]
This has worked for me (probably not the cleanest solution) in my docker file:

RUN cd /tmp && \
	git clone https://github.com/pytorch/pytorch
RUN cd /tmp/pytorch && \
	git reset --hard  4ff3872 && \
	git submodule sync && \
	git submodule update --init --recursive

RUN sed -i \
	'/include(CMakeDependentOption)/i \
	set(GLIBCXX_USE_CXX11_ABI 0)' \
 	/tmp/pytorch/CMakeLists.txt
RUN sed -i \
	's/set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC")/set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0")/g' \
 	/tmp/pytorch/third_party/gloo/CMakeLists.txt
RUN sed -i \
	'/gloo_list_append_if_unique(CUDA_NVCC_FLAGS "-Xcompiler" "-fPIC")/i \
	gloo_list_append_if_unique(CUDA_NVCC_FLAGS "-Xcompiler" "-D_GLIBCXX_USE_CXX11_ABI=0")' \
 	/tmp/pytorch/third_party/gloo/cmake/Cuda.cmake

ENV CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS"
ENV CMAKE_PREFIX_PATH=/opt/conda

RUN cd /tmp/pytorch && \
    echo $CMAKE_PREFIX_PATH && \
    python setup.py install

**Comment by tyoc213** [comment]
apparently hit this one, but dont want to do the sed...

```
[5102/5621] Linking CXX executable bin/List_test
FAILED: bin/List_test 
: && /usr/bin/clang++-8  -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp=libiomp5 -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG  -rdynamic -pthread caffe2/CMakeFiles/List_test.dir/__/aten/src/ATen/core/List_test.cpp.o  -o bin/List_test  -Wl,-rpath,/home/tyoc213/Documents/github/pytorch/build/lib:/home/tyoc213/miniconda3/envs/xla/lib:/usr/local/cuda/lib64:  lib/libgtest_main.a  lib/libtorch.so  lib/libtorch_cuda.so  lib/libtorch_cpu.so  lib/libprotobuf.a  /home/tyoc213/miniconda3/envs/xla/lib/libmkl_intel_lp64.so  /home/tyoc213/miniconda3/envs/xla/lib/libmkl_intel_thread.so  /home/tyoc213/miniconda3/envs/xla/lib/libmkl_core.so  /home/tyoc213/miniconda3/envs/xla/lib/libiomp5.so  /usr/lib/x86_64-linux-gnu/libpthread.so  -lm  /usr/lib/x86_64-linux-gnu/libdl.so  lib/libdnnl.a  -ldl  lib/libc10_cuda.so  lib/libc10.so  /usr/local/cuda/lib64/libcudart.so  /usr/lib/x86_64-linux-gnu/libnvToolsExt.so  /usr/local/cuda/lib64/libcufft.so  /usr/local/cuda/lib64/libcurand.so  /usr/local/cuda/lib64/libcublas.so  /usr/local/cuda/lib64/libcudnn.so  lib/libgtest.a  -pthread && :
/usr/bin/ld: lib/libtorch_cuda.so: undefined reference to `gloo::getCudaPCIBusID(int)'
/usr/bin/ld: lib/libtorch_cuda.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[5103/5621] Linking CXX executable bin/kernel_lambda_test
FAILED: bin/kernel_lambda_test 
: && /usr/bin/clang++-8  -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp=libiomp5 -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG  -rdynamic -pthread caffe2/CMakeFiles/kernel_lambda_test.dir/__/aten/src/ATen/core/boxing/impl/kernel_lambda_test.cpp.o  -o bin/kernel_lambda_test  -Wl,-rpath,/home/tyoc213/Documents/github/pytorch/build/lib:/home/tyoc213/miniconda3/envs/xla/lib:/usr/local/cuda/lib64:  lib/libgtest_main.a  lib/libtorch.so  lib/libtorch_cuda.so  lib/libtorch_cpu.so  lib/libprotobuf.a  /home/tyoc213/miniconda3/envs/xla/lib/libmkl_intel_lp64.so  /home/tyoc213/miniconda3/envs/xla/lib/libmkl_intel_thread.so  /home/tyoc213/miniconda3/envs/xla/lib/libmkl_core.so  /home/tyoc213/miniconda3/envs/xla/lib/libiomp5.so  /usr/lib/x86_64-linux-gnu/libpthread.so  -lm  /usr/lib/x86_64-linux-gnu/libdl.so  lib/libdnnl.a  -ldl  lib/libc10_cuda.so  lib/libc10.so  /usr/local/cuda/lib64/libcudart.so  /usr/lib/x86_64-linux-gnu/libnvToolsExt.so  /usr/local/cuda/lib64/libcufft.so  /usr/local/cuda/lib64/libcurand.so  /usr/local/cuda/lib64/libcublas.so  /usr/local/cuda/lib64/libcudnn.so  lib/libgtest.a  -pthread && :
/usr/bin/ld: lib/libtorch_cuda.so: undefined reference to `gloo::getCudaPCIBusID(int)'
/usr/bin/ld: lib/libtorch_cuda.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[5105/5621] Building CXX object caffe2/CMakeFiles/blob_test.dir/core/blob_test.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 765, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/home/tyoc213/Documents/github/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/tyoc213/Documents/github/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/home/tyoc213/Documents/github/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/tyoc213/miniconda3/envs/xla/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.

```

I have set all this variables....

```
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export CXX_ABI=0
export cxx_abi=0
export cuda=1 # new
export USE_CUDA=1
export CXX=clang++-8
export GPU_NUM_DEVICES=1
export CC=clang-8
export GLIBCXX_USE_CXX11_ABI=0
export CFLAGS="${CFLAGS} -D_GLIBCXX_USE_CXX11_ABI=0"
export CXXFLAGS="${CXXFLAGS} -D_GLIBCXX_USE_CXX11_ABI=0"
```

But Im stuck now...

**Comment by yichi-yang** [comment]
The problems seem to be [this line in gloo/cmake/Cuda.cmake](https://github.com/facebookincubator/gloo/blob/master/cmake/Cuda.cmake#L169).
`set(CUDA_PROPAGATE_HOST_FLAGS OFF)`
If you comment it out nvcc will pass _GLIBCXX_USE_CXX11_ABI=0 to the host compiler.
