### ISSUE TITLE
ModuleNotFoundError: No module named 'hypothesis.searchstrategy'

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#31993]
We appear to not be compatible with hypothesis-5.1.2

```
Traceback (most recent call last):
  File "test/test_nn.py", line 56, in <module>
    import hypothesis_utils as hu
  File "/data/users/ezyang/pytorch-tmp/test/hypothesis_utils.py", line 9, in <module>
    from hypothesis.searchstrategy import SearchStrategy
ModuleNotFoundError: No module named 'hypothesis.searchstrategy'
```

**Comment by ezyang** [comment]
hypothesis commit that broke us 60e4f52fc03061c8f40d3bc56dd7849a6845b2c5

**Comment by ezyang** [comment]
fixed on master
