### ISSUE TITLE
test_quantized is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#32000]
## 🐛 Bug

`test_quantized` is failing in macos CI: https://app.circleci.com/jobs/github/pytorch/pytorch/4182545. Looks like `future` cannot be imported:\.

Sample error:

```
Jan 08 21:29:07 Running test_quantized ... [2020-01-08 21:29:07.689188]
Jan 08 21:29:07 Traceback (most recent call last):
Jan 08 21:29:07   File "test_quantized.py", line 2, in <module>
Jan 08 21:29:07     from future.builtins import round
Jan 08 21:29:07 ModuleNotFoundError: No module named 'future'
Jan 08 21:29:07 Traceback (most recent call last):
Jan 08 21:29:07   File "test/run_test.py", line 456, in <module>
Jan 08 21:29:07     main()
Jan 08 21:29:07   File "test/run_test.py", line 449, in main
Jan 08 21:29:07     raise RuntimeError(message)
Jan 08 21:29:07 RuntimeError: test_quantized failed!
Jan 08 21:29:07 + cleanup
Jan 08 21:29:07 + retcode=1
Jan 08 21:29:07 + set +x
```

Not sure if this is resolved but I've seen it after rebasing the past couple of days, so reporting it just in case.

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
This should be fixed now, please feel free to re-open if it's not
