### ISSUE TITLE
DistributedDataParallel non-floating point dtype parameter with requires_grad=False

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#32018]
## 🐛 Bug

1. Using DistributedDataParallel
2. on a model that has at-least one non-floating point dtype parameter with requires_grad=False
3. with a WORLD_SIZE <= nGPUs/2 on the machine

results in an error "Only Tensors of floating point dtype can require gradients".

## To Reproduce

1. Use a machine which has at least 4 GPUs
2. Build pytorch from source for python3.6 OR use one of the available docker images.
3. Run the following command: "BACKEND=nccl WORLD_SIZE=2 TEMP_DIR=/tmp python3.6 test_distributed.py --verbose TestDistBackend.test_DistributedDataParallel"

The model used in the test has a `long` (`int64`) parameter with `requires_grad=False`: https://github.com/pytorch/pytorch/blob/master/test/test_distributed.py#L59

On a ROCm build of PyTorch, I get the below stack trace (although this issue isn't ROCm-specific):
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 2097, in _run
    getattr(self, self.id().split(".")[2])()
  File "test_distributed.py", line 2023, in wrapper
    fn(self)
  File "test_distributed.py", line 117, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "test_distributed.py", line 1849, in test_DistributedDataParallel
    self._test_DistributedDataParallel(gpu_subset=gpus, rank=rank)
  File "test_distributed.py", line 1784, in _test_DistributedDataParallel
    model_DDP, device_ids=gpu_subset
  File "/root/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 305, in __init__
    self._ddp_init_helper()
  File "/root/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 323, in _ddp_init_helper
    self._module_copies = replicate(self.module, self.device_ids, detach=True)
  File "/root/.local/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 147, in replicate
    setattr(replica, key, Parameter(param))
  File "/root/.local/lib/python3.6/site-packages/torch/nn/parameter.py", line 26, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point dtype can require gradients
FAIL
```

## Expected behavior

Test should pass.

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0a0+b8f50d9
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 16.04.5 LTS
GCC version: Could not collect
CMake version: version 3.6.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
ROCm version: 2.10

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.4.0a0+b8f50d9
[pip3] torchvision==0.4.2
[conda] Could not collect
```

**Comment by jithunnair-amd** [comment]
I was able to get the test to pass with the following change. I can file a PR if this looks right:
```
diff --git a/torch/nn/parallel/replicate.py b/torch/nn/parallel/replicate.py
index 45632e1..46b9767 100644
--- a/torch/nn/parallel/replicate.py
+++ b/torch/nn/parallel/replicate.py
@@ -143,7 +143,7 @@ def replicate(network, devices, detach=False):
                 for j in range(num_replicas):
                     replica = module_copies[j][i]
                     param = param_copies[j][param_idx]
-                    setattr(replica, key, Parameter(param))
+                    setattr(replica, key, Parameter(param, requires_grad=param.requires_grad))
                     # TODO: We need to manually set _parameters with a bare
                     # non-parameter Tensor, otherwise gradients don't
                     # accumulate in the original parameters when you call
```

**Comment by pietern** [comment]
Thanks for filing the issue. The fix looks sane to me. What do you think, @mrshenli @agolynski?

**Comment by agolynski** [comment]
I've talked to @mrshenli offline and he mentioned that seems like there is some mixing of data parallel and distributed data parallel going on here. if so, we do not recommend this for clients, maybe just use distributed data parallel only?

For purely data parallel models, Shen drew a autograd dependency picture where replicated operators would depend on the original one for their derivatives (pardon, if my terminology is incorrect here). If this is the case, maybe replicas should always have requires_grad = false (if my reasoning made any sense)?

**Comment by mrshenli** [comment]
I see, this is for our own tests. @agolynski @pietern you are right, and my previous comments were wrong. 

@jithunnair-amd thanks for catching this error and proposing the fix! Would you like to submit a PR for it? Will be very glad to help land it.

@yf225 is it possible to get a 4-gpu container from CircleCI? It will help to expose this issue. I submitted a request ticket to CircleCI around last April, but didn't get updates for a while. Do you know if 4-gpu container is available now?

**Comment by jithunnair-amd** [comment]
@mrshenli Done. #32356

**Comment by yf225** [comment]
> @yf225 is it possible to get a 4-gpu container from CircleCI? It will help to expose this issue. I submitted a request ticket to CircleCI around last April, but didn't get updates for a while. Do you know if 4-gpu container is available now?

My guess is that we still don't have 4-gpu container yet. @ezyang @kostmo Would it be something we can ask CircleCI again for?

**Comment by ezyang** [comment]
File a ticket with them and let us know what they respond

**Comment by jithunnair-amd** [comment]
@ezyang @yf225 Is there any update on adding 4-GPU CUDA containers to CircleCI? I came across another issue that shows up on ROCm builds only because we have 4-GPU ROCm machines on CI.

**Comment by jithunnair-amd** [comment]
Although, even with a 4-GPU machine, such issues will only surface when the `WORLD_SIZE` is set to 2 so that there's more than 1 device per process. This won't happen in pytorch CI because of https://github.com/pytorch/pytorch/blob/master/test/run_test.py#L183, which will set the `WORLD_SIZE` to 3 for a 4-GPU machine.

@mrshenli Is my understanding above correct?
