### ISSUE TITLE
[discussion] Relax optimizer constructor constraints for simplicity

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#32021]
`lr` is required. However if we do call `load_state_dict` after optimizer construction, the passed state overwrites the `lr` value just passed to the constructor (and we have no convenience method for updating the `lr` of all `param_groups` if we want to use a new `lr` even after restoring optimizer state and momentum buffers).
```
>>> torch.optim.SGD([torch.Tensor()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda/lib/python3.7/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/miniconda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 51, in __init__
    self.add_param_group(param_group)
  File "/miniconda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 207, in add_param_group
    name)
ValueError: parameter group didn't specify a value of required optimization parameter lr
```

#### Less pertinent:
Passing an empty param list is impossible, but passing a `requires_grad=False` like above is possible (or having parameters without grad in runtime). For simplifying the code it may be easier to remove this check and allow empty param sets (in this case the optimizer.step won't do anything).
```
>>> torch.optim.SGD()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'params'
>>> torch.optim.SGD([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda/lib/python3.7/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/miniconda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 46, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

**Comment by vadimkantorov** [comment]
It would be nice to have an optimizer utility for resetting all param_groups to some values. One way:
`optimizer.load_state_dict(state_dict, reset_to_defaults = True)`, another way: `optimizer.reset_to_defaults()`.

This situation occurs when needed to load_state_dict optimizer state to load Adam-like optimizer buffers, but when one wants to reset lr to a new value. The naive way of creating an optimizer with target lr/weight_decay/... and then load_state_dict does not work as naively expected.

**Comment by vadimkantorov** [comment]
Another motivation for dropping mandatory `lr` in constructor: if all param groups specify their own lr

**Comment by vadimkantorov** [comment]
This is partially done for SGD it seems, it now checks that lr is set within param groups. The only issue is that the error message is confusing when a list of parameters is passed in without an lr.
