### ISSUE TITLE
build pytorch from source fauled: undefined reference to `cusparseGetErrorString(cusparseStatus_t)'

### ISSUE THREAD

**Issue by dongxiao92** [pytorch/pytorch#32083]
## To Reproduce

follow the instruction from [](https://github.com/pytorch/pytorch)
> git clone --recursive https://github.com/pytorch/pytorch
> cd pytorch
> # if you are updating an existing checkout
> git submodule sync
> git submodule update --init --recursive
> export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
> python setup.py install

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
building pytorch failed, thus no libtorch_global_deps.so was generated and collect_env.py cannot run.

 - PyTorch Version (e.g., 1.0): latest, with commit 927c2a02b0b29a0fafcced8d65896dd417023067
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): as described above
 - Python version: 3.7.4, anaconda
 - CUDA/cuDNN version: cuda 10.1, cudnn 7.1.3
 - GPU models and configuration: Nvidia GTX 1070
 - Any other relevant information:

The error message is listed below.
     ^
[2372/2767] Linking CXX executable bin/graph_test
FAILED: bin/graph_test 
: && /usr/bin/c++  -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -rdynamic -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -pthread caffe2/CMakeFiles/graph_test.dir/core/graph_test.cc.o  -o bin/graph_test -L/home/v-doxia/anaconda3/lib -Wl,-rpath,/home/v-doxia/anaconda3/lib:/home/v-doxia/working/pytorch/build/lib:/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64: lib/libgtest_main.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch.so -Wl,--as-needed -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cpu.so -Wl,--as-needed lib/libprotobuf.a -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -fopenmp -lpthread -lm /usr/lib/x86_64-linux-gnu/libdl.so lib/libmkldnn.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so -Wl,--as-needed lib/libc10_cuda.so lib/libc10.so /usr/local/cuda-10.1/lib64/libnvToolsExt.so /usr/local/cuda-10.1/lib64/libcudart.so /usr/local/cuda-10.1/lib64/libcufft.so /usr/local/cuda-10.1/lib64/libcurand.so /usr/lib/x86_64-linux-gnu/libcublas.so /usr/local/cuda/lib64/libcudnn.so lib/libgtest.a -pthread && :
/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so: undefined reference to `cusparseGetErrorString(cusparseStatus_t)'
collect2: error: ld returned 1 exit status
[2373/2767] Linking CXX executable bin/roi_align_op_gpu_test
FAILED: bin/roi_align_op_gpu_test 
: && /usr/bin/c++  -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -rdynamic -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -pthread    -rdynamic caffe2/CMakeFiles/roi_align_op_gpu_test.dir/operators/roi_align_op_gpu_test.cc.o  -o bin/roi_align_op_gpu_test -L/home/v-doxia/anaconda3/lib -Wl,-rpath,/usr/local/cuda-10.1/lib64:/home/v-doxia/anaconda3/lib:/home/v-doxia/working/pytorch/build/lib:/usr/local/cuda/lib64: /usr/local/cuda-10.1/lib64/libcudart.so lib/libgtest_main.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch.so -Wl,--as-needed -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cpu.so -Wl,--as-needed lib/libprotobuf.a -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -fopenmp -lpthread -lm -ldl lib/libmkldnn.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so -Wl,--as-needed lib/libc10_cuda.so lib/libc10.so /usr/local/cuda-10.1/lib64/libnvToolsExt.so /usr/local/cuda-10.1/lib64/libcudart.so /usr/local/cuda-10.1/lib64/libcufft.so /usr/local/cuda-10.1/lib64/libcurand.so -lcublas /usr/local/cuda/lib64/libcudnn.so lib/libgtest.a -pthread && :
/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so: undefined reference to `cusparseGetErrorString(cusparseStatus_t)'
collect2: error: ld returned 1 exit status
[2375/2767] Linking CXX executable bin/operator_fallback_gpu_test
FAILED: bin/operator_fallback_gpu_test 
: && /usr/bin/c++  -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -rdynamic -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -pthread    -rdynamic caffe2/CMakeFiles/operator_fallback_gpu_test.dir/operators/operator_fallback_gpu_test.cc.o  -o bin/operator_fallback_gpu_test -L/home/v-doxia/anaconda3/lib -Wl,-rpath,/usr/local/cuda-10.1/lib64:/home/v-doxia/anaconda3/lib:/home/v-doxia/working/pytorch/build/lib:/usr/local/cuda/lib64: /usr/local/cuda-10.1/lib64/libcudart.so lib/libgtest_main.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch.so -Wl,--as-needed -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cpu.so -Wl,--as-needed lib/libprotobuf.a -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -fopenmp -lpthread -lm -ldl lib/libmkldnn.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so -Wl,--as-needed lib/libc10_cuda.so lib/libc10.so /usr/local/cuda-10.1/lib64/libnvToolsExt.so /usr/local/cuda-10.1/lib64/libcudart.so /usr/local/cuda-10.1/lib64/libcufft.so /usr/local/cuda-10.1/lib64/libcurand.so -lcublas /usr/local/cuda/lib64/libcudnn.so lib/libgtest.a -pthread && :
/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so: undefined reference to `cusparseGetErrorString(cusparseStatus_t)'
collect2: error: ld returned 1 exit status
[2376/2767] Linking CXX executable bin/utility_ops_gpu_test
FAILED: bin/utility_ops_gpu_test 
: && /usr/bin/c++  -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -rdynamic -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -pthread    -rdynamic caffe2/CMakeFiles/utility_ops_gpu_test.dir/operators/utility_ops_gpu_test.cc.o  -o bin/utility_ops_gpu_test -L/home/v-doxia/anaconda3/lib -Wl,-rpath,/usr/local/cuda-10.1/lib64:/home/v-doxia/anaconda3/lib:/home/v-doxia/working/pytorch/build/lib:/usr/local/cuda/lib64: /usr/local/cuda-10.1/lib64/libcudart.so lib/libgtest_main.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch.so -Wl,--as-needed -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cpu.so -Wl,--as-needed lib/libprotobuf.a -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -fopenmp -lpthread -lm -ldl lib/libmkldnn.a -Wl,--no-as-needed,/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so -Wl,--as-needed lib/libc10_cuda.so lib/libc10.so /usr/local/cuda-10.1/lib64/libnvToolsExt.so /usr/local/cuda-10.1/lib64/libcudart.so /usr/local/cuda-10.1/lib64/libcufft.so /usr/local/cuda-10.1/lib64/libcurand.so -lcublas /usr/local/cuda/lib64/libcudnn.so lib/libgtest.a -pthread && :
/home/v-doxia/working/pytorch/build/lib/libtorch_cuda.so: undefined reference to `cusparseGetErrorString(cusparseStatus_t)'
collect2: error: ld returned 1 exit status
[2387/2767] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_misc.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/v-doxia/working/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/v-doxia/working/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/home/v-doxia/working/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/v-doxia/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by dongxiao92** [comment]
guys, any idea?

**Comment by ptrblck** [comment]
@zasdfgbnm Could this error be raised due to the usage of `cusparseGetErrorString` [here](https://github.com/pytorch/pytorch/blob/62b1a5f8466991b3e042345e1c786d520c3b9d91/aten/src/ATen/cuda/Exceptions.h#L38) without [this guard and definition](https://github.com/pytorch/pytorch/blob/62b1a5f8466991b3e042345e1c786d520c3b9d91/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu#L11-L49) for cusparse>10.2?

**Comment by zasdfgbnm** [comment]
@ptrblck It's hard to say whether it's due to this exact guard, but the message sounds weird.

@dongxiao92 Could you try a full cleanup before rebuild? I personally use:

```bash
yes | sh -c 'pip uninstall torch; pip uninstall torch; pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;pip uninstall torch; pip uninstall torch;'
python setup.py clean; python setup.py clean; python setup.py clean; python setup.py clean
```

Most of the time when I see a linker error, clean before rebuild would resolve the issue.

**Comment by dongxiao92** [comment]
@ptrblck I tried to [guard](https://github.com/pytorch/pytorch/blob/62b1a5f8466991b3e042345e1c786d520c3b9d91/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu#L11-L49) the declaration here(https://github.com/pytorch/pytorch/blob/62b1a5f8466991b3e042345e1c786d520c3b9d91/aten/src/ATen/cuda/Exceptions.h#L38) but still got the same error.
@zasdfgbnm Currently I'm working with pytorch installed via conda. Do I need to uninstall it before a clean build (I just use python setup build for the pytorch source)?

**Comment by zasdfgbnm** [comment]
@dongxiao92 It's better to uninstall it via conda. But usually, if you don't do so, it still works.

**Comment by dongxiao92** [comment]
@zasdfgbnm Hi, I tried uninstall pytorch via conda and re-build pytorch, but still got the same error.

**Comment by denfromufa** [comment]
I have the same error with this setup here:

https://github.com/pytorch/pytorch/issues/31438

**Comment by peterbell10** [comment]
I ran into the same error when trying to build with CUDA 9. In my case the error was caused by the compiler including cuSPARSE headers from CUDA 10.1 (so not defining `cusparseGetErrorString` in `SparseCUDABlas.cu`) but linking against cuSPARSE from CUDA 9 which doesn't define the function. For me, the fix is gh-32404 and setting `USE_CUDNN=0` which gets rid of CUDA 10 from the include path.

@dongxiao92 I notice that in your build command there is a mixture of `/usr/local/cuda-10.1/` and `/usr/local/cuda/`. Do you have multiple CUDA versions installed? It could be that the include is correctly picking up CUDA 10.1 but perhaps you're being linked against an older cuSPARSE?

As a check, `build/CMakeCache.txt` from the pytorch folder should contain the cusparse path as something like:
```
CUDA_cusparse_LIBRARY:FILEPATH=/usr/local/cuda-10.1/lib64/libcusparse.so
```

**Comment by dongxiao92** [comment]
@peterbell10 
Thanks for your advice! Actually there are tow versions of cuda installed on my machine.  The cusparse library found is in the cuda-10.1 and cudnn is in the cuda directory. So there may be the root cause! 
But as all cuda-related libraries except cusparse are located in the cuda directory and I find no simple way to change their locations instead of changing it one by one. I tried to construct a new cudnn environment in my home directory but still encountered this error, which may be caused by other cuda libraries in the cuda directory.

**Comment by peterbell10** [comment]
Maybe try setting the `CUDA_HOME` variable before compiling. And make sure to delete the build folder first.
```sh
export CUDA_HOME=/usr/local/cuda-10.1/
```

**Comment by denfromufa** [comment]
I tried replacing the signature of this error function, but this did not help either:

```
data/gpfs/Projects/CSE_hpda/pytorch/build/lib/libtorch_cuda.so: undefined reference to `getCusparseErrorString(cusparseStatus_t)'
```

Pytorch has 3 places where this function is used, but the dependency graph for all these CUDA libraries is huge to make sure that compatible packages in system/conda/third-party are used:

```
(pytorch.1.3.ompi4) $ grep -r getCusparseErrorString .
./aten/src/ATen/cuda/Exceptions.h:const char *getCusparseErrorString(cusparseStatus_t status);
./aten/src/ATen/cuda/Exceptions.h:                getCusparseErrorString(__err),                  \
./aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu:const char* getCusparseErrorString(cusparseStatus_t status) {
Binary file ./build/lib/libtorch_cuda.so matches
Binary file ./build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/CuSparseHandlePool.cpp.o matches
Binary file ./build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/sparse/cuda/torch_cuda_generated_SparseCUDABlas.cu.o matches

```

**Comment by hartb** [comment]
Note that function `getCusparseErrorString()` was actually introduced to `libcusparse` during the lifetime of CUDA 10.1.

It was not present in 10.1.105 (original CUDA 10.1 release):

```
$ objdump -T libcusparse.so.10.1.105 | grep GetErrorString
$
```

But had appeared by the time of 10.1.243 (CUDA 10.2 Update 2):

```
$ objdump -T cudatoolkit-10.1.243-616.gc122b8b/cuda/lib/libcusparse.so.10.3.0.243 | grep GetErrorString
00000000000b9fe0 g    DF .text  0000000000000048  libcusparse.so.10 0x60 cusparseGetErrorString
```

And I'm not sure about 10.1.168 (CUDA 10.1 Update 1).

So when building against CUDA 10.1, whether you want the guard (https://github.com/pytorch/pytorch/blob/62b1a5f8466991b3e042345e1c786d520c3b9d91/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu#L11-L49) (i.e. whether you need PyTorch's local definition of `cusparseGetErrorString()` or whether that would collide so you instead need to use `libcusparse`'s) will depend on which CUDA 10.1 update you have (and if you need it, you'd need to adjust the version check in the guard).

If you move to CUDA 10.2, then `libcusparse` should always have the function and you'd always want to use cusparse's copy, so would always want the guard (and version checks in the guard are correct).

In @denfromufa 's case, the function name is slightly different (`getCusparseErrorString` vs `cusparseGetErrorString`). The function was renamed for a while (in PyTorch 1.1.0), but has since be renamed back:

```
v1.0.1:aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu:std::string cusparseGetErrorString(cusparseStatus_t status) {
v1.1.0:aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu:std::string getCusparseErrorString(cusparseStatus_t status) {
v1.2.0:aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu:std::string cusparseGetErrorString(cusparseStatus_t status) {
v1.3.1:aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu:std::string cusparseGetErrorString(cusparseStatus_t status) {
```

For builds from the source where the routine is renamed to `getCusparseErrorString`, I'm not sure why you'd ever suffer an undefined symbol. That symbol will be local to Pytorch, never come from cusparse.

**Comment by hartb** [comment]
(Ah, and I think @denfromufa 's issue was due to me originally pointing him at the wrong fix for this. Sorry!)

**Comment by xenogenesi** [comment]
I have the opposite problem but I think it is related, I am trying to build pytorch 1.0.0 with cuda 10.2 and the compiler finds two implementations of the function, consequently the call is ambiguous.

[gist Dockerfile.build-pytorch](https://gist.github.com/xenogenesi/a523df140c73cb356dc5fa4e2fcf5c05)

If you have any suggestions I can try to patch the sources but it is not clear to me which implementation should be kept in this case.

```sh
[ 67%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_gpu_generated_SparseCUDABlas.cu.o
/pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu(58): error: more than one instance of function "at::native::sparse::cuda::cusparseGetErrorString" matches the argument list:
            function "cusparseGetErrorString(cusparseStatus_t)"
            function "at::native::sparse::cuda::cusparseGetErrorString(cusparseStatus_t)"
            argument types are: (cusparseStatus_t)

1 error detected in the compilation of "/tmp/tmpxft_00004ccc_00000000-6_SparseCUDABlas.cpp1.ii".
CMake Error at caffe2_gpu_generated_SparseCUDABlas.cu.o.Release.cmake:279 (message):
  Error generating file
  /pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/./caffe2_gpu_generated_SparseCUDABlas.cu.o


caffe2/CMakeFiles/caffe2_gpu.dir/build.make:1260: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_gpu_generated_SparseCUDABlas.cu.o' failed
```

**Comment by Oshino-Ougi** [comment]
> I have the opposite problem but I think it is related, I am trying to build pytorch 1.0.0 with cuda 10.2 and the compiler finds two implementations of the function, consequently the call is ambiguous.
> 
> [gist Dockerfile.build-pytorch](https://gist.github.com/xenogenesi/a523df140c73cb356dc5fa4e2fcf5c05)
> 
> If you have any suggestions I can try to patch the sources but it is not clear to me which implementation should be kept in this case.
> 
> ```shell
> [ 67%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_gpu_generated_SparseCUDABlas.cu.o
> /pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu(58): error: more than one instance of function "at::native::sparse::cuda::cusparseGetErrorString" matches the argument list:
>             function "cusparseGetErrorString(cusparseStatus_t)"
>             function "at::native::sparse::cuda::cusparseGetErrorString(cusparseStatus_t)"
>             argument types are: (cusparseStatus_t)
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00004ccc_00000000-6_SparseCUDABlas.cpp1.ii".
> CMake Error at caffe2_gpu_generated_SparseCUDABlas.cu.o.Release.cmake:279 (message):
>   Error generating file
>   /pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/./caffe2_gpu_generated_SparseCUDABlas.cu.o
> 
> 
> caffe2/CMakeFiles/caffe2_gpu.dir/build.make:1260: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_gpu_generated_SparseCUDABlas.cu.o' failed
> ```
> 
> **edit**
> 
> Following @hartb suggestion (above) I disabled the function in `SparseCUDABlas.cu` and kept the one in the library, and the build finished successfully.

Hi, can I know how you solved it? I also got two implementations of the function `cusparseGetErrorString`, how to disabled one? 

Should I use `getCusparseErrorString` to replace `cusparseGetErrorString`in `/pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu`?

Or only need to delete all of this function in`/pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu`?
