### ISSUE TITLE
np.mean breaks when called on a list of cuda tensors

### ISSUE THREAD

**Issue by epignatelli** [pytorch/pytorch#32100]
## 🐛 Bug

When using `np.mean` on a list of `torch.tensor`s, whose device is different from `torch.device(type='cpu')`, an error is thrown.

The rationale for considering this a bug is that,if pytorch supports `np.mean` somehow, that should be supported fully.

Copying the tensors back to the cpu removes the error.

## To Reproduce

```python
np.mean([torch.tensor(1., device=torch.device("cuda")), torch.tensor(2.4, device=torch.device("cuda"))])
```
Out:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in mean
  File "~/.conda/envs/pytorch/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3257, in mean
    out=out, **kwargs)
  File "~/.conda/envs/pytorch/lib/python3.7/site-packages/numpy/core/_methods.py", line 161, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'
```
## Expected behavior
The operation should not raise `Error`s.
Copying the tensors back to the cpu removes the error.

```python
tensor_list = [torch.tensor(1., device=torch.device("cuda")), torch.tensor(2.4, device=torch.device("cuda"))]
np.mean([tensor.cpu() for tensor in tensor_list])

```

## Environment
```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 430.50
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.1
[pip] torchsummary==1.5.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.1           py3.7_cuda9.2.148_cudnn7.6.3_0    pytorch
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.4.2                 py37_cu92    pytorch
```

**Comment by zhangguanheng66** [comment]
Reproduce the error. It works with cpu tensors, though.

**Comment by ezyang** [comment]
Numpy doesn't support CUDA operations, so we definitely don't expect this to work. The error message is kind of weird and may be worth investigating further though

**Comment by mruberry** [comment]
@ezyang is right that you shouldn't expect this to work, and the error is generated by NumPy, not PyTorch. Think of it as if you're sticking a strange Python object into a NumPy function: the NumPy function goes to look for an attribute but discovers it's not there. Fixing this likely requires changes in NumPy.
