### ISSUE TITLE
Can't import torch on latest master

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#32186]
## 🐛 Bug

```
(/scratch/rzou/pt/master-env) [0] rzou@devfair0317:/scratch/rzou/pt/master (master) $ python
Python 3.7.5 (default, Oct 25 2019, 15:51:11)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/rzou/pt/master/torch/__init__.py", line 106, in <module>
    _load_global_deps()
  File "/scratch/rzou/pt/master/torch/__init__.py", line 64, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/scratch/rzou/pt/master-env/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /private/home/rzou/local/miniconda3/lib/libmpichcxx.so.3: undefined symbol: __cxa_pure_virtual
```

## To Reproduce

1. check out pytorch at 4a26bb9b18
1. build pytorch 
1. import torch

## Additional context

Deleting libmpichcxx.so from `miniconda3/lib/` and rebuilding pytorch seems to solve the problem, but I don't know where libmpichcxx.so came from at all

**Comment by Borda** [comment]
We have the same issue with just released 1.5 version running on Windows
```
ImportError while loading conftest 'D:\a\pytorch-lightning\pytorch-lightning\tests\conftest.py'.
tests\__init__.py:4: in <module>
    import torch
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\torch\__init__.py:81: in <module>
    ctypes.CDLL(dll)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\ctypes\__init__.py:348: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: [WinError 126] The specified module could not be found
```
https://github.com/PyTorchLightning/pytorch-lightning/pull/1552/checks?check_run_id=608401885

**Comment by zou3519** [comment]
@Borda you might want to open a new issue for that. Your issue looks different (mine is from a conflicting libmpichcxx.so)

**Comment by guol-fnst** [comment]
Can you provide outputs of "collect_env.py"?

**Comment by yummycats** [comment]
> We have the same issue with just released 1.5 version running on Windows
> 
> ```
> ImportError while loading conftest 'D:\a\pytorch-lightning\pytorch-lightning\tests\conftest.py'.
> tests\__init__.py:4: in <module>
>     import torch
> c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\torch\__init__.py:81: in <module>
>     ctypes.CDLL(dll)
> c:\hostedtoolcache\windows\python\3.6.8\x64\lib\ctypes\__init__.py:348: in __init__
>     self._handle = _dlopen(self._name, mode)
> E   OSError: [WinError 126] The specified module could not be found
> ```
> 
> https://github.com/PyTorchLightning/pytorch-lightning/pull/1552/checks?check_run_id=608401885

hello:), have you solve this problem? I meet the same problem.

**Comment by ksaur** [comment]
@Borda @yummycats I had the same stacktrace as you (within github actions), but  changed it to:
```
pip install torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
(with the +cpu). Maybe that will help?

**Comment by Borda** [comment]
> @Borda you might want to open a new issue for that. Your issue looks different (mine is from a conflicting libmpichcxx.so)

my issue was resolved by explicitly installing CPU version for a machine without GPU...
