### ISSUE TITLE
Torchscript fails to run after successful compilation

### ISSUE THREAD

**Issue by AbhishekShah212** [pytorch/pytorch#32199]
## 🐛 Bug

The Torchscript engine in Pytorch compiles the model, but fails to run it due to a library error. 

## To Reproduce

1. Run the below file
```
import torch
class TensorConstant(torch.nn.Module):
    def __init__(self, value):
        # type: (Tensor) -> None
        super(TensorConstant, self).__init__()
        self.val = torch.tensor(value)

    def forward(self, xs):
        # type: (Tuple[Dict[str,Tensor], Dict[str, Tensor]]) -> Tensor
        reals, bools = xs
        return self.val

class Real(torch.nn.Module):
    def __init__(self, name):
        super(Real, self).__init__()
        self.name = name

    def forward(self, xs):
        # type: (Tuple[Dict[str,Tensor], Dict[str, Tensor]]) -> Tensor
        reals, bools = xs
        return reals[self.name]

class Minus(torch.nn.Module):
    def __init__(self, f1, f2):
        super(Minus, self).__init__()
        self.f1 = f1
        self.f2 = f2

    def forward(self, xs):
        # type: (Tuple[Dict[str,Tensor], Dict[str, Tensor]]) -> Tensor
        val = self.f1.forward(xs) - self.f2.forward(xs)
        return val

xs = ({'foo': torch.tensor(1.0, requires_grad=True)}, {})
f1 = TensorConstant(2.0)
f2 = Real("foo")
model = Minus(f1, f2)

print(model(xs)) # works

scripted_model = torch.jit.script(model)
print(scripted_model(xs)) # fails
```
2. You will then get the following error: 
```
tensor(1., grad_fn=<SubBackward0>)
Traceback (most recent call last):
  File "tests/minimal.py", line 42, in <module>
    print(scripted_model(xs)) # fails
  File "/local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: type with contained types did not overload createWithContained: ClassType<TensorConstant> (createWithContained at /tmp/pip-req-build-58y_cjjl/aten/src/ATen/core/jit_type.h:183)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7fffc62f81cd in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x4133c3 (0x7fffe8bd93c3 in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x1188f6a (0x7fffc74c3f6a in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x118ff6e (0x7fffc74caf6e in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x37d3783 (0x7fffc9b0e783 in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x37d3cee (0x7fffc9b0ecee in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: torch::jit::GraphExecutor::GraphExecutor(std::shared_ptr<torch::jit::Graph>) + 0xd5 (0x7fffc9a324d5 in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: std::call_once<torch::jit::Function::get_executor()::{lambda()#1}>(std::once_flag&, torch::jit::Function::get_executor()::{lambda()#1}&&)::{lambda()#2}::_FUN() + 0xd6 (0x7fffe8c9d466 in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xf827 (0x7ffff7bc5827 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #9: <unknown function> + 0x50e1b5 (0x7fffe8cd41b5 in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x50ed0c (0x7fffe8cd4d0c in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x1c7126 (0x7fffe898d126 in /local/user/miniconda3/envs/env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #33: __libc_start_main + 0xe7 (0x7ffff77e6b97 in /lib/x86_64-linux-gnu/libc.so.6)
```

## Expected behavior

I expect the model before compilation and after compilation via torchscript to output the same result (`tensor(1., grad_fn=<SubBackward0>)`). The code should not crash.
## Environment

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 418.56
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4

Versions of relevant libraries:
[pip3] numpy==1.17.4
[conda] _pytorch_select           0.2                       gpu_0
[conda] _tflow_select             2.3.0                       mkl
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.2.0           cuda100py37h938c94c_0
[conda] tensorflow                2.0.0           mkl_py37h66b46cc_0
[conda] tensorflow-base           2.0.0           mkl_py37h9204916_0
[conda] torchvision               0.4.0           cuda100py37hecfc37a_0
```
## Additional context

My current understanding is that it is an error due to the instance variable `self.val` in the `TensorConstant` class. I think this because there is no error in the `Real` class and the main difference is that `Real` class does not return an instance variable in the `forward` method, but the `TensorConstant` class does.  

cc @suo

**Comment by eellison** [comment]
Hi @AbhishekShah212, thank you for opening a succinct repro. I tried your example on master and I didn't have any issues:

```
xs = ({'foo': torch.tensor(1.0, requires_grad=True)}, {})
f1 = TensorConstant(2.0)
f2 = Real("foo")
model = Minus(f1, f2)

print(model(xs)) # works
# tensor(1., grad_fn=<SubBackward0>)

scripted_model = torch.jit.script(model)
print(scripted_model(xs)) # fails
# tensor(1., grad_fn=<SubBackward0>)
```

Could you try updating to a more recent version of pytorch ? I see that you're on `1.2` currently.

**Comment by AbhishekShah212** [comment]
I upgraded and this resolved the issue, thanks for the quick reply!
