### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by deep999** [pytorch/pytorch#3222]
Hy, I'm ( new) Ubuntu user and I get error while trying to install pytorch. Any tips what to do? Haven't found anything via google.

...-Lenovo-G50-30:~$ pip3 install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl 
Collecting torch==0.2.0.post3 from http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl
  Downloading http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl (340.6MB)
    100% |████████████████████████████████| 340.6MB 16.5MB/s 
Requirement already satisfied: numpy in ./.local/lib/python3.5/site-packages (from torch==0.2.0.post3)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from torch==0.2.0.post3)
Installing collected packages: torch
Exception:
Traceback (most recent call last):
  File "/home/.../.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/.../.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/.../.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/.../.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/.../.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/.../.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/.../.local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/.../.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/torch-0.2.0.post3.dist-info'

**Comment by deep999** [comment]
SOLVED: add "sudo" before input to terminal if anyone needs it!

**Comment by apaszke** [comment]
It's usually a bad idea to install packages with `sudo`, as the build process can execute arbitrary code on your machine and you can get hacked. It's better practice to use `virtualenv` or `conda` environments.
