### ISSUE TITLE
Python 3.8 Windows JIT test failure

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#32287]
## To Reproduce

Error text:
```pytb
======================================================================
FAIL: test_unmatched_type_annotation (__main__.TestScript)
----------------------------------------------------------------------
RuntimeError: 
Number of type annotations (2) did not match the number of function parameters (1):
  File "test_jit.py", line 4302
            @torch.jit.script
            def invalid2(a):
                         ~~~...  <--- HERE
                # type: (Int, Int) -> Int
                return a + 2


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_jit.py", line 4302, in test_unmatched_type_annotation
    def invalid2(a):
AssertionError: "def\ invalid2\(a\):\
\ \ \ \ \ \ \ \ \ \ \ \ \~\~\~\~\~\~\~\~\~\~\~\~\~\~\ <\-\-\-\ HERE\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \#\ type:\ \(Int,\ Int\)\ \->\ Int\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ return\ a\ \+\ 2" does not match "
Number of type annotations (2) did not match the number of function parameters (1):
  File "test_jit.py", line 4302
            @torch.jit.script
            def invalid2(a):
                         ~~~...  <--- HERE
                # type: (Int, Int) -> Int
                return a + 2
"
```
See https://app.circleci.com/jobs/github/pytorch/pytorch/4269821.

## Expected behavior

Test pass

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 8a5e21a
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

**Comment by peterjc123** [comment]
Since it doesn't affect correctness, I'll skip this test for Windows and Python 3.8.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
