### ISSUE TITLE
DataParallel does not work with sparse parameters

### ISSUE THREAD

**Issue by madlag** [pytorch/pytorch#32444]
## 🐛 Bug

DataParallel does not work with sparse parameters.
The root issue is located in the model replication part of DataParallel.
I have a fix proposal for this and can make a pull request : https://github.com/madlag/pytorch/commit/a64aacd4168ac73f50ee9e6ed16cfdca8e22af1d
(this fixes completely DataParallel for version 1.4)

## To Reproduce

Run the following code on a machine with at least 2 gpus : 
```
import torch
import torch.nn
import torch.sparse
import torch.nn.parallel.replicate as replicate

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        indices = torch.LongTensor([[0,1,2],[0,0,0]])
        values = torch.tensor([0.0,0.0,0.0])
        t = torch.sparse.FloatTensor(indices, values, [3,3])
        self.p = torch.nn.Parameter(t)

m = MyModule().cuda()
replicate(m, [0,1])
```

You will get this error message :
```
Traceback (most recent call last):
  File "test_data_parallel.py", line 15, in <module>
    replicate(m, [0,1])
  File "/home/lagunas/ml/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 92, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, False)
  File "/home/lagunas/ml/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
RuntimeError: Could not run 'aten::view' with arguments from the 'SparseCUDATensorId' backend. 'aten::view' is only available for these backends: [CUDATensorId, QuantizedCPUTensorId, VariableTensorId, CPUTensorId, MkldnnCPUTensorId].
```

## Expected behavior

The expected behaviour should be to replicate correctly the model containing sparse parameter.

## Environment

PyTorch 1.4, with two GPUS.

```Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce GTX 1080

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] numpydoc==0.9.1
[pip] torch==1.4.0
[pip] torch-scatter==1.4.0
[pip] torch-sparse==0.4.3
[pip] torchfile==0.1.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py37h7b6447c_0  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torch-scatter             1.4.0                    pypi_0    pypi
[conda] torch-sparse              0.4.3                    pypi_0    pypi
[conda] torchfile                 0.1.0                      py_0    conda-forge
[conda] torchvision               0.5.0                py37_cu100    pytorch
```

**Comment by mrshenli** [comment]
cc @zhaojuanmao

**Comment by zhaojuanmao** [comment]
@madlag thanks for reporting, feel free to send out PR and we can help review.

**Comment by madlag** [comment]
Thank you, that was fast !
I sent the PR : https://github.com/pytorch/pytorch/pull/32486 
It includes some fixes for test_data_parallel.py, a new test for this issue, and the fix itself.

**Comment by madlag** [comment]
A similar bug exists for Boolean tensors as well, when used as buffers :
```
import torch
import torch.nn
import torch.nn.parallel.replicate as replicate

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        mask = torch.zeros(3, dtype=bool)
        self.register_buffer("mask", mask)

m = MyModule().cuda()
replicate(m, [0,1])
```
Exception : 
```
Traceback (most recent call last):
  File "test_data_parallel2.py", line 51, in <module>
    replicate(m, [0,1])
  File "/home/lagunas/ml/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 103, in replicate
    buffer_copies_not_rg = _broadcast_coalesced_reshape(buffers_not_rg, devices, detach=True)
  File "/home/lagunas/ml/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 67, in _broadcast_coalesced_reshape
    return comm.broadcast_coalesced(tensors, devices)
  File "/home/lagunas/ml/anaconda3/lib/python3.7/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: Unconvertible NCCL type
```
My fix is not handling this case, a larger refactor would be needed.

**Comment by zhaojuanmao** [comment]
I tried to read related codes and debug the sparse tensors replicate issue, and found out that sparse tensors are actually broadcast properly among devices, it seems that we are returning view of sparse tensors and auto grad function (Class Broadcast is a grad function) complains about it. if I copy the sparse tensor view to a new sparse tensor before returning in Broadcast.forward(), there is no error any more.

**Comment by AliLotfi92** [comment]
Can anyone give me an update on this issue? I have the same problem. 
Below is the link to the code;
https://discuss.pytorch.org/t/pytorch-with-multi-gpus/78616/3

**Comment by mrshenli** [comment]
@zhaojuanmao is there a simple work around for this or is there anything that we should fix?

**Comment by zhaojuanmao** [comment]
@mrshenli I will do a work around like what I tried "copy the sparse tensor view to a new sparse tensor and return the new sparse tensor in Broadcast.forward(), there is no error any more."

**Comment by AliLotfi92** [comment]
@zhaojuanmao, can you please explain more.

**Comment by mrshenli** [comment]
@AliLotfi92 I think @zhaojuanmao was referring to https://github.com/pytorch/pytorch/pull/32226, we might need a similar fix for Broadcast.

**Comment by AliLotfi92** [comment]
thanks @mrshenli!
