### ISSUE TITLE
[jit] Unable to get module 'type' while using Jit.script

### ISSUE THREAD

**Issue by neeraj-j** [pytorch/pytorch#32526]
## 🐛 Bug

Jit.script does not support type() or "\.\_\_class__" for getting module type

## To Reproduce

```
import torch
import torch.nn as nn

class Foo(nn.Module):
    def __init__(self):
        super(Foo, self).__init__()
        self.identity = nn.Identity()

    def forward(self, x):
        #if self.identity.__class__ ==  nn.Identity:
        #if isinstance(self.identity, nn.Identity):
        if type(self.identity) == nn.Identity:
              x = self.identity(x)
        return x

f = Foo()
scripted = torch.jit.script(f)
```
I get following error:
```
RuntimeError: 

(Tensor 0) -> (Tensor 0):
Expected a value of type 'Tensor' for argument '0' but instead found type '__torch__.torch.nn.modules.linear.Identity'.
:
  File "C:/Users/jain_/.PyCharmCE2019.2/config/scratches/scratch_2.py", line 11
    def forward(self, x):
        if type(self.identity) == nn.Identity:
           ~~~~ <--- HERE
        #if self.identity.__class__ == nn.Identity:
            x = self.identity(x)
```
If I use
`self.identity.__class__`  instead of `type(self.identity)`, I get following error:
```
Traceback (most recent call last):
  File "C:/Users/jain_/.PyCharmCE2019.2/config/scratches/scratch_2.py", line 18, in <module>
    scripted = torch.jit.script(f)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\_recursive.py", line 570, in compile_unbound_method
    stub = make_stub(fn)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\jit\_recursive.py", line 32, in make_stub
    rcb = _jit_internal.createResolutionCallbackFromClosure(func)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\_jit_internal.py", line 126, in createResolutionCallbackFromClosure
    closure = get_closure(fn)
  File "C:\sw\Anaconda3\envs\python3\lib\site-packages\torch\_jit_internal.py", line 71, in get_closure
    captures.update(fn.__globals__)
AttributeError: type object 'type' has no attribute '__globals__'
```

Any workaround would be appreciated

## Expected behavior

Should be able to find the module type

## Environment

pytorch : 1.4 (conda, stable)
OS: windows 10
CUDA: None

cc @suo

**Comment by driazati** [comment]
This error is disguising the real bug which is that `type()` is not supported in TorchScript, so it is being inserted as a call to Python. Since the `type()` function has no type annotations, TorchScript assumes all the arguments are `Tensor`s, hence the error.

There's no good workaround at runtime, but you could lift the check into `__init__` (which runs in Python and is not looked at by the TorchScript compiler), and use the result in your `forward()`:

```python
import torch
import torch.nn as nn

class Foo(nn.Module):
    def __init__(self):
        super(Foo, self).__init__()
        self.identity = nn.Identity()
        self.use_identity = type(self.identity) == nn.Identity

    def forward(self, x):
        if self.use_identity:
              x = self.identity(x)
        return x

f = Foo()
scripted = torch.jit.script(f)
```

**Comment by neeraj-j** [comment]
Thanks, for the prompt response. I created a static map of layer type in "init". Similar to your solution and used it in forward.

**Comment by fmbao** [comment]
same question.How to solve it

**Comment by fmbao** [comment]
> same question.How to solve it

I solve it by del code about "assert"
