### ISSUE TITLE
HardTanh and UpsamplingBilinear2d not supported by ONNX

### ISSUE THREAD

**Issue by vweilv** [pytorch/pytorch#3253]
I tried to export my PyTorch model to ONNX but two error occur:
(1) Hardtanh error
`Traceback (most recent call last):
  File "/Users/lv/PycharmProjects/Pp/model.py", line 127, in <module>
    export_params=True)      # store the trained parameter weights inside the model file
  File "/Users/lv/anaconda/lib/python2.7/site-packages/torch/onnx.py", line 96, in _export
    torch._C._jit_pass_onnx(trace)
  File "/Users/lv/anaconda/lib/python2.7/site-packages/torch/onnx.py", line 121, in run_symbolic
    return symbolic_fn(*args)
  File "/Users/lv/anaconda/lib/python2.7/site-packages/torch/nn/_functions/thnn/auto.py", line 133, in symbolic
    return symbolic_fn(*args, **kwargs)
TypeError: 'NoneType' object is not callable (occurred when translating Hardtanh)`

(2) UpsamplingBilinear2d error
`Traceback (most recent call last):
  File "/Users/lv/PycharmProjects/Pp/model.py", line 127, in <module>
    export_params=True)      # store the trained parameter weights inside the model file
  File "/Users/lv/anaconda/lib/python2.7/site-packages/torch/onnx.py", line 105, in _export
    proto = trace.export(list(model.state_dict().values()))
RuntimeError: Couldn't export UpsamplingBilinear2d function - maybe it doesn't implement a symbolic definition?`

---------------------------------------
So, how can I fix the errors? Thank you.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ezyang** [comment]
Thanks for the report. It looks like `Hardtanh` and `UpsamplingBilinear2d` are not currently supported. I filed two bugs in upstream ONNX tracker for this:

* https://github.com/onnx/onnx/issues/141
* https://github.com/onnx/onnx/issues/142

**Comment by spandantiwari** [comment]
Both UpsamplingBilinear2D and HardTanh should be supported now. Please reopen this if you see any issues.
