### ISSUE TITLE
test_cos_scalar_cpu in test_autograd.py  is flaky

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#32595]
Looks like it fails sometimes in master.
recent example:
https://app.circleci.com/jobs/github/pytorch/pytorch/4334972
https://app.circleci.com/jobs/github/pytorch/pytorch/4335324
https://app.circleci.com/jobs/github/pytorch/pytorch/4334257

Error message:
```
Jan 24 14:04:35   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 407, in gradgradcheck
Jan 24 14:04:35     nondet_tol=nondet_tol)
Jan 24 14:04:35   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 297, in gradcheck
Jan 24 14:04:35     'The tolerance for nondeterminism was {}.'.format(nondet_tol))
Jan 24 14:04:35   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 229, in fail_test
Jan 24 14:04:35     raise RuntimeError(msg)
Jan 24 14:04:35 RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient. The tolerance for nondeterminism was 0.0.
Jan 24 14:04:35 
Jan 24 14:04:35 ----------------------------------------------------------------------
Jan 24 14:04:35 Ran 1046 tests in 293.286s
Jan 24 14:04:35 
Jan 24 14:04:35 FAILED (errors=1, skipped=13, expected failures=1)
Jan 24 14:04:35 
Jan 24 14:04:35 Generating XML reports...
Jan 24 14:04:35 Traceback (most recent call last):
Jan 24 14:04:35   File "test/run_test.py", line 456, in <module>
Jan 24 14:04:35     main()
Jan 24 14:04:35   File "test/run_test.py", line 449, in main
Jan 24 14:04:35     raise RuntimeError(message)
Jan 24 14:04:35 RuntimeError: test_autograd failed!
Jan 24 14:04:35 + cleanup
Jan 24 14:04:35 + retcode=1
Jan 24 14:04:35 + set +x
```

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by jerryzh168** [comment]
oh, it's already tracked in https://github.com/pytorch/pytorch/issues/32502
