### ISSUE TITLE
test_broadcast_coalesced_nccl is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#32643]
## 🐛 Bug

Example failure: 
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/14617/console

```
08:02:54 ======================================================================
08:02:54 ERROR: test_broadcast_coalesced_nccl (__main__.CommTest)
08:02:54 ----------------------------------------------------------------------
08:02:54 Traceback (most recent call last):
08:02:54   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 174, in wrapper
08:02:54     self._join_processes(fn)
08:02:54   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 255, in _join_processes
08:02:54     self._check_return_codes(elapsed_time)
08:02:54   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 274, in _check_return_codes
08:02:54     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
08:02:54 RuntimeError: Process 1 terminated or timed out after 156.02865886688232 seconds
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by ezyang** [comment]
I think https://github.com/pytorch/pytorch/pull/32338 is responsible

**Comment by zhaojuanmao** [comment]
closing as #32338 was reverted and test failure did not happen any more
