### ISSUE TITLE
Dynamic LSTM quantization fails with engine 'qnnpack' when LSTM is part of another module

### ISSUE THREAD

**Issue by PCerles** [pytorch/pytorch#32676]
## 🐛 Bug

Dynamic LSTM quantization fails with engine 'qnnpack.' Am trying to export an LSTM based model for use on mobile devices. This only happens when the LSTM module is a submodule of another torch.nn.Module.

## To Reproduce
```
x = torch.zeros(1, 12, 80)
torch.backends.quantized.engine = 'qnnpack'
model = torch.nn.LSTM(80, 48, 4, batch_first=True, bidirectional=True, dropout=0.0)
quant_model = torch.quantization.quantize_dynamic(
                model, {nn.LSTM}, dtype=torch.qint8
)
torch.set_num_threads(1)
traced = torch.jit.trace(quant_model, x)
```
^ Successful
```
    class SimpleModel(torch.nn.Module):
        def __init__(self):
            super(SimpleModel, self).__init__()
            self.lstm = torch.nn.LSTM(80, 48, 4, batch_first=True, bidirectional=True, dropout=0.0)

        def forward(self, x):
            y, h = self.lstm(x)
            return y
    torch.backends.quantized.engine = 'qnnpack'
    model = SimpleModel()

    quant_model = torch.quantization.quantize_dynamic(
                model, {nn.LSTM}, dtype=torch.qint8
    )
    x = torch.zeros(1, 12, 80)
    traced = torch.jit.trace(quant_model, x)
    traced.save("traced_quantized.pt")
```
Error:
```
Traceback (most recent call last):
  File "check.py", line 109, in <module>
    main()
  File "check.py", line 88, in main
    traced = torch.jit.trace(quant_model, x)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "check.py", line 68, in forward
    y, h = self.lstm(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/dynamic/modules/rnn.py", line 375, in forward
    return self.forward_tensor(input, hx)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/dynamic/modules/rnn.py", line 336, in forward_tensor
    input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/dynamic/modules/rnn.py", line 317, in forward_impl
    self.batch_first, dtype=self.dtype, use_dynamic=True)
RuntimeError: Expected temporary cpp type wrapper of type PackedLinearWeight
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: TITAN RTX

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-ignite==0.2.1
[pip3] pytorch-lamb==1.0.0
[pip3] torch==1.4.0
[pip3] torchaudio==0.4.0
[pip3] torchvision==0.5.0
[pip3] warpctc-pytorch==0.1
[pip3] warprnnt-pytorch==0.1
[conda] Could not collec
```

*Update* Looks like it will not work anyway given this line https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/RNN.cpp#L311. Is there any release schedule for RNNs working on NNPACK?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jianyuh** [comment]
Currently, we only support the dynamic quantized LSTM with FBGEMM on the CPU server side. For the QNNPACK support of LSTM on the mobile side (release schedule for RNNs), cc @supriyar

**Comment by supriyar** [comment]
Thanks for flagging this. Support is being added here - https://github.com/pytorch/pytorch/pull/32757

**Comment by PCerles** [comment]
Thanks so much!
