### ISSUE TITLE
Error tracing custom autograd.Function

### ISSUE THREAD

**Issue by twostay** [pytorch/pytorch#32822]
## 🐛 Bug

I got an error when I tried to use jit to trace my autograd Function. In previous Pytorch versions(1.1.0), this works, but recently I updated to 1.4.0, and this stopped working. I'm not exactly sure which version exactly did this stopped working. 
## To Reproduce

1. Make sure you have Pytorch1.4.0
2. Make a custom autograd Function. In  my case, I'm using this one
```
class raw(autograd.Function):
    @staticmethod
    def forward(ctx, inp):
        ctx.a = (inp * inp + 1).reciprocal()
        ctx.b = ctx.a.sqrt()
        return inp * ctx.b

    @staticmethod
    def backward(ctx, grad_output):
        return grad_output * ctx.a * ctx.b
```
3. Trace this Function.
```
from torch import jit
jit.trace(raw.apply, example_inputs=tc.randn(1))
```
4. The error should orginate from the line of tracing and look like this:
```
......................
    jit.trace(raw.apply, example_inputs=tc.randn(1))
  File "...\Python37\lib\site-packages\torch\jit\__init__.py", line 903, in trace
    name = _qualified_name(func)
  File "...\Python37\lib\site-packages\torch\_jit_internal.py", line 696, in _qualified_name
    "__module__ can't be None.".format(name))
RuntimeError: Could not get qualified name for class 'apply': __module__ can't be None.
```

## Expected behavior
I expect the tracing to work like how the previous versions did. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.4.0+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.4.0+cpu
[pip3] torchvision==0.5.0+cpu
[conda] Could not collect

## Additional context
I'm bad at using Github so if I missed something please tell me :)

**Comment by twostay** [comment]
It seems that tracing autograd functions isn't working for versions from 1.2.0 to 1.4.0(CPU version), I think it worked on 1.1.0 or 1.0.1(I can't remember the exact version I used); I didn't test it on nightly.

**Comment by hubertta** [comment]
This is still broken on 1.5.0:
```
In [11]: torch.__version__
Out[11]: '1.5.0'

In [12]: import torch.autograd as autograd

In [13]: import torch as tc

In [14]: class raw(autograd.Function):
    ...:     @staticmethod
    ...:     def forward(ctx, inp):
    ...:         ctx.a = (inp * inp + 1).reciprocal()
    ...:         ctx.b = ctx.a.sqrt()
    ...:         return inp * ctx.b
    ...: 
    ...:     @staticmethod
    ...:     def backward(ctx, grad_output):
    ...:         return grad_output * ctx.a * ctx.b
    ...:     

In [15]: from torch import jit
    ...: jit.trace(raw.apply, example_inputs=tc.randn(1))
    ...: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-01e6e0a83b2b> in <module>()
      1 from torch import jit
----> 2 jit.trace(raw.apply, example_inputs=tc.randn(1))

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, _force_outplace, _module_class, _compilation_unit)
    894                              "Please use trace_module")
    895 
--> 896     name = _qualified_name(func)
    897     traced = torch._C._create_function_from_trace(name, func, example_inputs,
    898                                                   var_lookup_fn,

/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py in _qualified_name(obj)
    772     if module_name is None:
    773         raise RuntimeError("Could not get qualified name for class '{}': "
--> 774                            "__module__ can't be None.".format(name))
    775 
    776     # if getattr(sys.modules[module_name], name) is not obj:

RuntimeError: Could not get qualified name for class 'apply': __module__ can't be None.
```

**Comment by meryemJanatiIdrissi** [comment]
I get the same issue using Scripting (torch 1.4.0+cpu):

`class CNNNet_CIFAR(nn.Module):

    def __init__(self, conv1_dim=100, save=False):
        super(CNNNet_CIFAR, self).__init__()
        self.conv1 = nn.Conv2d(3, 1, 5, stride=1, padding=2)
        self.normalize1 = syft_nn.BatchNorm2d(conv1_dim, save=save)

    def forward(self, x):
        x = F.relu(self.normalize1((self.conv1(x))))
        return x

model = CNNNet_CIFAR_MyBN(save=False)
scripted_model = torch.jit.script(model)
`

is it because of the torch version?

**Comment by ifgovh** [comment]
In pytorch 1.7, it still failed. Is this bug hard to be fixed?

**Comment by marwanelsheriif** [comment]
any updates? still fails on torch==1.10.0

**Comment by suo** [comment]
@gmagogsfm I thought we fixed this at some point?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
