### ISSUE TITLE
failed to register operator torchvision::_new_empty_tensor_op

### ISSUE THREAD

**Issue by ankane** [pytorch/pytorch#32821]
## 🐛 Bug

The example for `torch.hub.list` on [this page](https://pytorch.org/docs/stable/hub.html) is failing with:

```txt
Downloading: "https://github.com/pytorch/vision/archive/master.zip" to /Users/andrew/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "boom.py", line 3, in <module>
    entrypoints = torch.hub.list('pytorch/vision', force_reload=True)
  File "/usr/local/lib/python3.7/site-packages/torch/hub.py", line 283, in list
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/usr/local/lib/python3.7/site-packages/torch/hub.py", line 75, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/hubconf.py", line 4, in <module>
    from torchvision.models.alexnet import alexnet
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/torchvision/ops/__init__.py", line 13, in <module>
    _register_custom_op()
  File "/Users/andrew/.cache/torch/hub/pytorch_vision_master/torchvision/ops/_register_onnx_ops.py", line 49, in _register_custom_op
    register_custom_op_symbolic('torchvision::_new_empty_tensor_op', new_empty_tensor_op, _onnx_opset_version)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 200, in register_custom_op_symbolic
    return utils.register_custom_op_symbolic(symbolic_name, symbolic_fn, opset_version)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 793, in register_custom_op_symbolic
    .format(symbolic_name))
RuntimeError: Failed to register operator torchvision::_new_empty_tensor_op.                            The symbolic name must match the format Domain::Name,                            and sould start with a letter and contain only                            alphanumerical characters
```

## To Reproduce

```py
import torch

entrypoints = torch.hub.list('pytorch/vision', force_reload=True)
```

## Expected behavior

No error

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.16.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect

**Comment by ankane** [comment]
Ah, looks like it's related to https://github.com/pytorch/vision/issues/1827. For others who run into this, you can do:

```py
entrypoints = torch.hub.list('pytorch/vision:v0.5.0', force_reload=True)
```

**Comment by sharkdeng** [comment]
> Ah, looks like it's related to [pytorch/vision#1827](https://github.com/pytorch/vision/issues/1827). For others who run into this, you can do:
> 
> ```python
> entrypoints = torch.hub.list('pytorch/vision:v0.5.0', force_reload=True)
> ```

works for me, change from pytorch/vision:v0.6.0 to 0.5.0
