### ISSUE TITLE
CUDA error: an illegal memory access was encountered when using output_padding in nn.ConvTranspose3d

### ISSUE THREAD

**Issue by flysofast** [pytorch/pytorch#32866]
I'm building a simple Encoder-Decoder architecture for video with 3D Convolutions and TransposedConv. The aim is make it fully convolutional so it would work with any video size.
The Encoder looks like this:
```  
    padding = int((kernel_size - 1)/2) #kernel_size = 5
    self.network = nn.Sequential(    
       nn.Conv3d(3, 128, kernel_size=kernel_size, stride=1, padding=padding),
       nn.BatchNorm3d(128, affine=False),
       nn.ReLU(True),

       nn.Conv3d(128, 64, kernel_size=kernel_size, stride=2, padding=padding),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),

       nn.Conv3d(64, 64, kernel_size=kernel_size, stride=2, padding=padding),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),

       nn.Conv3d(64, 24, kernel_size=kernel_size, stride=1, padding=padding),
       nn.BatchNorm3d(output_channels, affine=False),
       nn.ReLU(True)
    )
````
And here is the Decoder:
```
    padding = int((kernel_size - 1)/2) #kernel_size = 5
    self.network = nn.Sequential( 
       nn.ConvTranspose3d(self.input_channels, 64, kernel_size=kernel_size, stride=1, padding=padding),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),
    
       nn.ConvTranspose3d(64, 64, kernel_size=kernel_size, stride=2, padding=padding, output_padding=1),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),

       nn.ConvTranspose3d(64, 128, kernel_size=kernel_size, stride=2, padding=padding, output_padding=1),
       nn.BatchNorm3d(128, affine=False),
       nn.ReLU(True),

       nn.Conv3d(128, self.output_channels, kernel_size=kernel_size, stride=1, padding=padding),
    )
````
I trained the model with input size of (NxCxHxW) = (16x3x112x112). The outputs of each layer looks like this:

```
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv3d-1    [-1, 128, 16, 112, 112]          48,128
       BatchNorm3d-2    [-1, 128, 16, 112, 112]               0
              ReLU-3    [-1, 128, 16, 112, 112]               0
            Conv3d-4        [-1, 64, 8, 56, 56]       1,024,064
       BatchNorm3d-5        [-1, 64, 8, 56, 56]               0
              ReLU-6        [-1, 64, 8, 56, 56]               0
            Conv3d-7        [-1, 64, 4, 28, 28]         512,064
       BatchNorm3d-8        [-1, 64, 4, 28, 28]               0
              ReLU-9        [-1, 64, 4, 28, 28]               0
           Conv3d-10        [-1, 24, 4, 28, 28]         192,024
      BatchNorm3d-11        [-1, 24, 4, 28, 28]               0
             ReLU-12        [-1, 24, 4, 28, 28]               0
        Encoder3D-13        [-1, 24, 4, 28, 28]               0
   
  ConvTranspose3d-16        [-1, 64, 4, 28, 28]         192,064
      BatchNorm3d-17        [-1, 64, 4, 28, 28]               0
             ReLU-18        [-1, 64, 4, 28, 28]               0
  ConvTranspose3d-19        [-1, 64, 8, 56, 56]         512,064
      BatchNorm3d-20        [-1, 64, 8, 56, 56]               0
             ReLU-21        [-1, 64, 8, 56, 56]               0
  ConvTranspose3d-22    [-1, 128, 16, 112, 112]       1,024,128
      BatchNorm3d-23    [-1, 128, 16, 112, 112]               0
             ReLU-24    [-1, 128, 16, 112, 112]               0
           Conv3d-25      [-1, 3, 16, 112, 112]          48,003
        Decoder3D-26      [-1, 3, 16, 112, 112]               0
================================================================
````
After the the model got trained, I tested in on a UCF-101 video sequence of size (Frames x Width x Height) = (16 x 342 x 256) with `os.environ["CUDA_LAUNCH_BLOCKING"] = "1"` and got this error:
```
Traceback (most recent call last):
  File "reconstruct.py", line 80, in <module>
    torchsummary.summary(model, dataloader.dataset[0].shape)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/VCM/E2E/Model/model.py", line 57, in forward
    x_hat = self.decoder(y)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/VCM/E2E/AutoEncoder/model3d.py", line 84, in forward
    x = self.network(x)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 921, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: CUDA error: an illegal memory access was encountered
````
However if I ran the code on CPU and not using CUDA it will output a frame sequence of size (344 x 256) which is 2 pixels more in its width.
Another way to make to code run is at inference time change the output_padding in both TransposedConv layers in the Decoder to 0. Then I would get this sequence of size (341 x 253)

I hope this has something to do with the arithmetic as in this paper https://arxiv.org/pdf/1603.07285.pdf, rather than a bug. I'd appreciate if you can point me into the right direction, so that my model can take in any video size and reconstruct it to the same size automatically.

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ezyang** [comment]
I'm not too sure what the true problem is, but whatever it is, we shouldn't be triggering an illegal memory access from CUDA, we should have cuaght the error earlier. What version of PyTorch are you running? Do you think you could make a standalone repro script (e.g., by feeding in the network a `torch.randn(...)` of appropriate size?)

**Comment by ezyang** [comment]
Can you also run the env script so we can find out the cudnn version

**Comment by flysofast** [comment]
Here is my env setup:
````
------------------------  ----------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                     1.17.3
detectron2                0.1 @/home/namle/VCM/nam_playground/mod-detectron2/detectron2_repo/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_70
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3,4,5,6,7       Tesla V100-SXM2-32GB
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.2
torchvision               0.4.2 @/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  ----------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ezyang** [comment]
Yeah, see if you can try with 1.4.0 (and master) and see if it is still a problem.

**Comment by flysofast** [comment]
@ezyang It still happens on Pytorch 1.4 unfortunately. Here is the updated environment:
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.4.0
[pip] torchsummary==1.5.1
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.5.0                py37_cu101    pytorch

```

**Comment by ezyang** [comment]
OK, eagerly awaiting the dummy test code.

**Comment by rgommers** [comment]
@flysofast can I gently remind you about the dummy test code for this issue? Without a reproducer it'll be hard to tackle this.

**Comment by flysofast** [comment]
> 
> 
> @flysofast can I gently remind you about the dummy test code for this issue? Without a reproducer it'll be hard to tackle this.

Hi,
Sorry for this very late reply. Here is a quick reproducer:
https://gist.github.com/flysofast/3937b9b6409f254cb5bae40f964b513a
