### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by zihaozhang9** [pytorch/pytorch#32881]
When I train the code, the following problem suddenly appears

Traceback (most recent call last):
  File "main.py", line 211, in <module>
    train(args,model,train_loader,optimizer,epoch)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/yolo/zzh_yolo/zzh_yolo_mobilenet/train.py", line 22, in train
    loss, outputs = model(imgs, targets)
  File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/yolo/zzh_yolo/zzh_yolo_mobilenet/models.py", line 297, in forward
    x = module(x)
  File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

System information
-ubuntu18.04

gmp                       6.1.2                h6c8ec71_1    defaults
google-auth               1.10.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.26.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      pypi_0    pypi
imagecorruptions          1.0.0                    pypi_0    pypi
imageio                   2.6.1                    pypi_0    pypi
imgaug                    0.2.6                    pypi_0    pypi
importlib_metadata        1.4.0                    py36_0    defaults
intel-openmp              2019.4                      243    defaults
ipykernel                 5.1.4            py36h39e3cac_0    defaults
ipython                   7.11.1           py36h39e3cac_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jedi                      0.16.0                   py36_0    defaults
jinja2                    2.10.3                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonpatch                 1.24                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
jsonschema                3.2.0                    py36_0    defaults
jupyter                   1.0.0                    py36_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jupyter_client            5.3.4                    py36_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.1                    py36_0    defaults
leveldb                   1.20                 hf484d3e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libprotobuf               3.8.0                hd408876_0    defaults
libsodium    
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py36_0    defaults
opencv-contrib-python     3.4.1.15                 pypi_0    pypi
opencv-python             4.1.2.30                 pypi_0    pypi
openssl                   1.1.1d               h7b6447c_3    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
parso                     0.6.0                      py_0    defaults
pbr                       5.1.3                    pypi_0    pypi
pcre                      8.43                 he6710b0_0    defaults
pexpect                   4.8.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    5.0.0                    pypi_0    pypi
pip                       20.0.2                   py36_1    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            3.0.3                      py_0    defaults
protobuf                  3.8.0            py36he6710b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ptyprocess                0.6.0                    py36_0    defaults
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.7                    pypi_0    pypi
pycocotools               2.0.0                    pypi_0    pypi
pygments                  2.5.2                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
pyrsistent                0.15.7           py36h7b6447c_0    defaults
python                    3.6.8                h0371630_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pyzmq                     18.1.0           py36he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.6.0                      py_1    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
send2trash                1.5.0                    py36_0    defaults
setuptools                41.2.0                   pypi_0    pypi
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.14.0                   py36_0    defaults
snappy                    1.1.7                hbae5bb6_3    defaults
sqlite                    3.30.1               h7b6447c_0    defaults
tb-nightly                2.0.0a20190915           pypi_0    pypi
tensorboard               2.1.0                    pypi_0    pypi
tensorflow                1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
terminado                 0.8.3                    py36_0    defaults
terminaltables            3.1.0                    pypi_0    pypi
testpath                  0.4.4                      py_0    defaults
thop                      0.0.31-1912272122          pypi_0    pypi
tk                        8.6.8                hbc83047_0    defaults
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.5.0                py36_cu101    pytorch
tornado                   6.0.3            py36h7b6447c_0    defaults
tqdm                      4.35.0                   pypi_0    pypi
traitlets                 4.3.3                    py36_0    defaults
urllib3                   1.25.7                   pypi_0    pypi
visdom                    0.1.8.9                  pypi_0    pypi
wcwidth                   0.1.7                    py36_0    defaults
webencodings              0.5.1                    py36_1    defaults
websocket-client          0.57.0                   pypi_0    pypi
wheel                     0.34.1                   py36_0    defaults
widgetsnbextension        3.5.1                    py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zipp                      0.6.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

AND :

` export | grep cuda`
declare -x CUDA_HOME="/usr/local/cuda-10.1"
declare -x LD_LIBRARY_PATH="”/usr/local/cuda-10.1/lib64:/home/nnir712/anaconda3/pkgs/libprotobuf-3.5.2-h6f1eeef_0/lib:/home/nnir712/anaconda3/pkgs/libprotobuf-3.8.0-hd408876_0/lib:BRARY_PATH:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64”:/home/nnir712/anaconda3/lib"
declare -x PATH="/home/nnir712/.local/bin:/home/nnir712/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/home/nnir712/anaconda3/pkgs/libprotobuf-3.5.2-h6f1eeef_0/bin:/home/nnir712/anaconda3/pkgs/libprotobuf-3.8.0-hd408876_0/bin:/home/nnir712/.local/bin:/home/nnir712/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/home/nnir712/anaconda3/pkgs/libprotobuf-3.5.2-h6f1eeef_0/bin:/home/nnir712/anaconda3/pkgs/libprotobuf-3.8.0-hd408876_0/bin:/home/nnir712/anaconda3/envs/zzhpy36/bin:/home/nnir712/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/nnir712/anaconda3/lib:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/nnir712/anaconda3/lib"

**Comment by carlodavid012** [comment]
check this solution https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-execution-failed/31169/8 and https://github.com/NVIDIA/tacotron2/issues/109

**Comment by zihaozhang9** [comment]
> check this solution https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-execution-failed/31169/8 and [NVIDIA/tacotron2#109](https://github.com/NVIDIA/tacotron2/issues/109)

Yesterday, I tried many versions of graphics driver, CUDA, cudnn and pytorch.
Then I discovered a magical phenomenon, when only 10 pictures are loaded in the graphics card, it can be trained normally. When loading 100 pictures, the video memory uses about 3G, and then reports an error.
From this I suspect that it is not the version that is wrong, it should be the graphics card hardware failure.

**Comment by carlodavid012** [comment]
@zihaozhang9 try running it on CPU on few epochs and check if there is an error

**Comment by carlodavid012** [comment]
check this https://github.com/pytorch/pytorch/issues/32921#issuecomment-581734069

**Comment by zasdfgbnm** [comment]
@zihaozhang9 Could you try the latest nightly build? A recent fix https://github.com/pytorch/pytorch/pull/33073 is supposed to fix some of these errors.

**Comment by zihaozhang9** [comment]
> @zihaozhang9 Could you try the latest nightly build? A recent fix #33073 is supposed to fix some of these errors.

Sorry, I can't confirm at the moment that the problem above is a pytorch problem. Because I tried to install tensorflow, a similar problem occurred. And [Nvidia ](https://devtalk.nvidia.com/default/topic/1072514/container-tensorflow/tensorflow-cuda_error_mis-aligned_address-misaligned-address/post/5434061/#5434061)suggested that I use the reproducer to find the problem. But I don't currently use reproducer.

At the moment I suspect it is an Ubuntu system or GPU hardware problem. However, due to the effects of COVID-19, I could not return to the laboratory to find out the cause.
My GPU has been idle.

Thank you very much for your reply, I will try if I have the chance. I no longer try to install pytroch recently. Because I have tried to install the graphics driver, CUDA, cudnn, conda, tf, pytroch many times, these operations have not resolved the error.
Thanks~

**Comment by debvrat** [comment]
Hi,

How do you get around this issue? What is causing it?

My environment details are:
Windows 10
CUDA 10.2
conda 4.8.3
Python 3.7.6
Pytorch 1.0.0
torchvision 0.2.2

**Comment by zihaozhang9** [comment]
> Hi,
> 
> How do you get around this issue? What is causing it?
> 
> My environment details are:
> 
> > Windows 10
> > CUDA 10.2
> > conda 4.8.3
> > Python 3.7.6
> > Pytorch 1.0.0
> > torchvision 0.2.2

At present, I have not solved this problem. In my case, I think that reinstalling the system, Anconda, and installing pytorch with conda can solve it.

**Comment by xwang233** [comment]
Can you run your script with `CUDA_LAUNCH_BLOCKING=1 python script.py` and post the updated error message here? Also, it would be nice to have a minimum repro script. This could be an internal cuDNN issue. A repro script would be helpful to solve the problem. Thanks!

**Comment by NakitaOza** [comment]
@zihaozhang9 @debvrat I am facing the same problem. I have Nvidia RTX 3060 12 GB. I think hardware is not the issue. Did you find any solution yet?
I am using Pytorch 1.4.0, WSL 2 Ubuntu 20.4 on Windows 11. CUDA 11.6.
I have also tried multiple combinations of versions for the above and still could not find a solution.

**Comment by zihaozhang9** [comment]
我已收到您发送的邮件。我会及时查看。

**Comment by byli2223** [comment]
> @zihaozhang9 @debvrat I am facing the same problem. I have Nvidia RTX 3060 12 GB. I think hardware is not the issue. Did you find any solution yet? It works on CPU though. I am using Pytorch 1.4.0, WSL 2 Ubuntu 20.4 on Windows 11. CUDA 11.6. I have also tried multiple combinations of versions for the above and still could not find a solution.
> 
> This also works successfully on my other system with Nvidia GeForce GTX 1050 Ti.
> 
> The code is here: https://github.com/NakitaOza/fcd/tree/development. I get the error when I run command: `python fcd_main.py --mode train --dataset L8Biome --image_size 128 --batch_size 8 --experiment_name FCD`

Hi, were you able to resolve this issue? I have almost identical setup as you do and got the same error when training. I have 3060, torch 1.4, WSL2, Ubuntu 20.4 windows 11, but CUDA 10.1. For me it takes a couple of minutes before the error shows up. I monitored GPU memory and it's far away from maxing out.

This is the network I'm trying to train:
https://github.com/hongwang01/InDuDoNet/tree/2587e91e6d9945bb9ca1efef223aa16e7ec56266

**Comment by ptrblck** [comment]
@byli2223 your Ampere GPU needs CUDA11 as well as cuDNN8, so update PyTorch to the latest stable or nightly release with the CUDA11 runtime.
