### ISSUE TITLE
 from torch._C import * (ImportError: DLL load failed)

### ISSUE THREAD

**Issue by ksiv** [pytorch/pytorch#32916]
## 🐛 Bug
Bad import error handling
By rising this issue my target not to get it to work "somehow"
But to improve the error handling giving to the people an opportunity to understand what went wrong.
I seen A LOT of such issues through the internet where solution was to reinstall totally different components to make it work and even downgrade the product which is totally NOT acceptable in today's world.
Other suggestion is to change packaging system which is not relate to the issue but worked for some people.
For some people adding some Cuda libs into some unpredictable place works

## To Reproduce

1. pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
2. python
3. help()
4. modules torch

Here is a list of modules whose name or summary contains 'torch'.
If there are any, enter a module name to get more help.

<generator object walk_packages at 0x000002AA581F4A48>
<generator object walk_packages at 0x000002AA581F4AC8>
torch - The torch package contains data structures for multi-dimensional
<generator object walk_packages at 0x000002AA581F4AC8>
torchfile - Mostly direct port of the Lua and C serialization implementation to
torchvision
<generator object walk_packages at 0x000002AA581F4AC8>

5. quit
6. >>> import torch
<generator object walk_packages at 0x000002AA54151CC8>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\__init__.py", line 86, in <module>
    from torch._C import *
ImportError: DLL load failed: Module not found.
7. add print(_dl_flags.environ['PATH']) into __init__
show me many paths including 
C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\lib;
this is the place where torch.dll is 
So it definitely sees the torch but which DLL it wants to load? 
running python with -v key did not help. 

## Expected behavior
Expected: 
-(min ) error contains what file it was looking for. So one should be able to find this in their system and fix the path OR not to find it in the system and add it into it.
 -(max) user friendly and at the same time useful error description

## Environment

```

 C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\lib;C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\Library\bin;C:\Program Files\NVIDIA Corporation\NvToolsExt\bin\x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Live\Shared;d:\php\;C:\Program Files\nodejs\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64;C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\lib;C:\Users\Asus\AppData\Roaming\npm;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Roaming\Composer\vendor\bin;C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts;c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64;C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\lib;;C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\.libs
<generator object walk_packages at 0x000002517FB64648>
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 850M
Nvidia driver version: 441.22
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.5.0
[conda] Could not collect
## Additional context

<!-- Add any other context about the problem here. -->


Thanks!

**Comment by ksiv** [comment]
File operations ended with 
NAME NOT FOUND 
\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\torch_python.dll
\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\torch_python.dll
\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\torch_python.dll
C:\Windows\System32\torch_python.dll

this torch_python.dll as the rest is located in torch/lib
any idea why it does not want to check lib folder?

as I can see this path is in _dl_flags.environ['PATH'] in __init__

**Comment by peterjc123** [comment]
Let's split your issues into two issues, the first part is the bug about the dll loading problem and the second part is the feature request to make it user-friendly.

## Bug
Apparently, from your description, you are using a non-standard python distribution. As for standard python distributions, we refer to Anaconda and Python from the official site. And in that python distribution, the current patch for dll paths doesn't work. You could try out sth like https://github.com/pytorch/pytorch/pull/17191.

## Feature
Let's clarify what exactly do you want?
1. Generate better exception messages.
2. A tool to debug dll loading issues.

### Better exception messages
Maybe we could achieve this by explicitly loading the DLLs before doing `torch._C`. By doing this, a message box with the detailed error will be shown. But for CI, it may block the build process. We may design an option to use the current dll load logic.

### dll loading debugging tools
This is hard to implement and we don't want reinvent the tools given there are several available, like Process Monitor and Dependencies. But we may point the user to our doc and write a few docs about it.

cc @ezyang

**Comment by ezyang** [comment]
I feel if you are building from source the onus is on you to get your development environment setup properly. Maybe we can warn in setup.py if it seems like the DLLs aren't going to be found, but it seems like that is about as good as we should try to do. (On our binary distributions we can arrange for all the necessary dlls to show up in the right places.)

**Comment by ksiv** [comment]
I m using vanilla Windows 10 python. 
To install it in Windows 10. Issue command 'python'
follow Windows 10 instruction to install.
I m not building anything. 
Anaconda looks a bit grotesque to add to my already clogged system. 
my workaround for this issue is to copy all files from torch/lib into torch.
(torch.rand(5, 3) - works)
I think, proper error text would help a bunch of guys using torch.
I m pretty old IT dude so I simply looked in fopen error operations but for some guys it can be tough.

**Comment by peterjc123** [comment]
You mean the Python distribution in the Microsoft Store? Well, that's extremely hard for us to test for that. First, we need to have a client version of Windows installation. Normally with those cloud providers and the CI service providers, they only provide Windows Server. Second, we need to figure out how to install that through Powershell/CMD.

**Comment by ksiv** [comment]
Yep this is from Store (https://docs.python.org/3/using/windows.html#windows-store)

Well as per https://stackoverflow.com/questions/47120993/how-to-make-loadlibrary-to-show-error-dialog-when-there-are-missing-dependencies

it seems to be a python issue not pytorch. 

My workaround is enough for me I used Process Explorer from sysinternals  to find out what and where it tries to open an to move those libs in the place it is looking in.
So I m pretty happy atm.
It's up to you where to do anything about it (having all mentioned difficulties in linked question). 
Thanks a lot for timely response.

P.S. you might be interested in one more thing if you look at the picture attached you ll see a try to open <stdin> as regular file located in DLL folder. it's not related to this issue most likely , but looks funny nevertheless :-)

**Comment by Jeff-Winchell** [comment]
I have the same error message that comes from just running
import torch

I deleted all traces of python from my computer, installed miniconda, created an environment from the base for pytorch, switched to that environment and ran 
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

This is on a Windows 10 computer with an nvidia Geforce GTX 1050 and an nvidia driver (version 445). (device manager shows this GPU to be functioning). I have NO other NVidia software on the computer as elsewhere on this website pytorch people said these binaries from the pytorch conda install made installing Nvidia Cuda toolkit/cudnn software irrelevant.

**Comment by peterjc123** [comment]
@Jeff-Winchell Would you please provide the logs using Process Monitor?

**Comment by Jeff-Winchell** [comment]
By that do you mean using this tool?
https://support.malwarebytes.com/hc/en-us/articles/360039025073-Use-Process-Monitor-to-create-real-time-event-logs

**Comment by peterjc123** [comment]
@Jeff-Winchell Yep.

**Comment by Jeff-Winchell** [comment]
And I should log just the point where I try to execute 
import torch

or should I be logging the install too?

**Comment by Jeff-Winchell** [comment]
After my initial post I also tried to do pip install instead. (I deleted the conda env I had created, recreated a new one (but cloned the base since pip requires python and other stuff, not an empty conda environment).  I used the recommended pip command:
pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html

after that I loaded python and tried to run import torch. I also got the DLL load failed message. Attached is a link to the pml log file from the few seconds before and after typing 
import torch
https://drive.google.com/file/d/10CavbWbxjuUvShDXkFy0cIBgyUwdwWHS/view?usp=sharing

**Comment by Jeff-Winchell** [comment]
Prior to doing all of this I have uninstalled virtually every software I can't live without. I am a bit loathe to downgrade my nvidia driver to the one that came out when cuda 10.1 came out since I went through so much work to get the nvidia GPU to be recognized by the OS.

**Comment by peterjc123** [comment]
@Jeff-Winchell I'm surprised to find that `VCRUNTIME140_1.dll` is not distributed through conda. You could resolve that by installing the VC Redist that could be downloaded [here](https://aka.ms/vs/16/release/vc_redist.x64.exe).
`

**Comment by Jeff-Winchell** [comment]
installing that solved the problem.

(As a side note) I now finally have torch.cuda.is_available() returning true.
