### ISSUE TITLE
Not linked against libmpi ?

### ISSUE THREAD

**Issue by eLvErDe** [pytorch/pytorch#3292]
Hi there,

Here is what happen with my package built against openmpi:
```

Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /usr/lib/python3/dist-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: ompi_mpi_char
>>> 
```

_C.so seems miss -lmpi linking, don't you think ?

```
root@zelda.domain.llu:~# ldd /usr/lib/python3/dist-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffd1dff4000)
	libshm.so => /usr/lib/python3/dist-packages/torch/lib/libshm.so (0x00007f13ed80e000)
	libcudart.so.8.0 => /usr/lib/x86_64-linux-gnu/libcudart.so.8.0 (0x00007f13ed5a8000)
	libnvToolsExt.so.1 => /usr/lib/x86_64-linux-gnu/libnvToolsExt.so.1 (0x00007f13ed39f000)
	libnccl.so.1 => /usr/lib/x86_64-linux-gnu/libnccl.so.1 (0x00007f13e99ae000)
	libcudnn.so.6 => /usr/lib/x86_64-linux-gnu/libcudnn.so.6 (0x00007f13e044c000)
	libTH.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTH.so.1 (0x00007f13dfe86000)
	libTHS.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTHS.so.1 (0x00007f13dfc56000)
	libTHPP.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTHPP.so.1 (0x00007f13df7df000)
	libTHNN.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTHNN.so.1 (0x00007f13df4c6000)
	libATen.so.1 => /usr/lib/python3/dist-packages/torch/lib/libATen.so.1 (0x00007f13ded48000)
	libTHC.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTHC.so.1 (0x00007f13a3827000)
	libTHCS.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTHCS.so.1 (0x00007f13a3012000)
	libTHCUNN.so.1 => /usr/lib/python3/dist-packages/torch/lib/libTHCUNN.so.1 (0x00007f1392ccf000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1392ab8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f139289b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f13924fc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f13eef10000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f13922f4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1391f72000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1391c6e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1391a6a000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f139183d000)
	libcublas.so.8.0 => /usr/lib/x86_64-linux-gnu/libcublas.so.8.0 (0x00007f138ee8d000)
	libcurand.so.8.0 => /usr/lib/x86_64-linux-gnu/libcurand.so.8.0 (0x00007f138af24000)
	libcusparse.so.8.0 => /usr/lib/x86_64-linux-gnu/libcusparse.so.8.0 (0x00007f1388416000)
```

**Comment by apaszke** [comment]
Hmmm yes. Can you please paste the content of `torch/lib/tmp_install/THD_deps.txt` here, and post a full build log to a gist?

**Comment by eLvErDe** [comment]
Not so easy because it's being built in an ephermal environment. I'll try to.provide this tomorrow.

**Comment by eLvErDe** [comment]
Hi there,

Here's the resulting .so file using mpi symbols but not being linked:

```
root@nsc-srve:~/pytorch-0.2.0# strings debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/_C.x86_64-linux-gnu.so | grep -i ompi_mpi
ompi_mpi_comm_world
ompi_mpi_uint64_t
ompi_mpi_uint8_t
ompi_mpi_comm_null
ompi_mpi_int
ompi_mpi_char
ompi_mpi_unsigned_char
ompi_mpi_float
ompi_mpi_double
ompi_mpi_short
ompi_mpi_unsigned_short
ompi_mpi_unsigned
ompi_mpi_long
ompi_mpi_unsigned_long
ompi_mpi_long_long_int
ompi_mpi_unsigned_long_long
ompi_mpi_op_min
ompi_mpi_op_max
ompi_mpi_op_sum
ompi_mpi_op_prod
root@nsc-srve:~/pytorch-0.2.0# ldd debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/_C.x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffcff3fd000)
        /usr/lib/cowdancer/libcowdancer.so (0x00007f70d33a0000)
        libshm.so => /root/pytorch-0.2.0/debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/lib/libshm.so (0x00007f70d3199000)
        libTH.so.1 => /root/pytorch-0.2.0/debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/lib/libTH.so.1 (0x00007f70d2b03000)
        libTHS.so.1 => /root/pytorch-0.2.0/debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/lib/libTHS.so.1 (0x00007f70d28d3000)
        libTHPP.so.1 => /root/pytorch-0.2.0/debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/lib/libTHPP.so.1 (0x00007f70d25fc000)
        libTHNN.so.1 => /root/pytorch-0.2.0/debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/lib/libTHNN.so.1 (0x00007f70d22d6000)
        libATen.so.1 => /root/pytorch-0.2.0/debian/python-torch-avx-sse42/usr/lib/python2.7/dist-packages/torch/lib/libATen.so.1 (0x00007f70d1e1a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70d1bfd000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70d19e0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70d1641000)
        /lib64/ld-linux-x86-64.so.2 (0x000055ff0d9e6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70d143b000)
        libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f70d1218000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f70d0fee000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f70d0de6000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70d0a64000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70d0760000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f70d0531000)
```

**Comment by eLvErDe** [comment]
Sadly there's no THD_deps.txt file anywhere, here's root of the build folder:

```
root@nsc-srve:~/pytorch-0.2.0# ls ./debian/build/avx-sse42/torch/lib/tmp_install/
bin  include  lib  share
```

**Comment by eLvErDe** [comment]
And the complete build log attached.

Btw, if you're a Debian/Ubuntu user, I'd be happy to share my package and instruction to get it build yourself if that can help (I have additional build issue of different Debian/Ubuntu versions to come...).

Best regards, Adam.
[build.txt](https://github.com/pytorch/pytorch/files/1428313/build.txt)

**Comment by apaszke** [comment]
There's something weird happening. You're building gloo, but still getting "Found Gloo: FALSE". However, `libgloo.a` is successfully linked into `_C.so`. On the other hand, MPI is found but not linked. You're likely getting some weird mix up with old build artifacts

**Comment by eLvErDe** [comment]
Hi,

Impossible, it's being build in a clean ephemeral environment every time !

**Comment by mruberry** [comment]
Closing due to age. If this is still an issue (somehow) please reopen.
