### ISSUE TITLE
pytorch 1.4 breaks torch.jit.script(LSTM/GRU)

### ISSUE THREAD

**Issue by julianmack** [pytorch/pytorch#32976]
## To Reproduce

Steps to reproduce the behaviour:
```shell
conda create -n pytorch1.4 python=3.7 pytorch=1.4 -c pytorch -y
conda activate pytorch1.4
python3
```
In `python3` interpreter
```python
import torch

input_size = 3
num_layers = 2
seq_len = 3
batch = 3
args = (torch.randn(seq_len, batch, input_size),)
scripted_lstm = torch.jit.script(torch.nn.LSTM(input_size, 3, num_layers))
scripted_lstm(*args)
```

Throws error message:
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/julian/miniconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/julian/miniconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/jit/__init__.py", line 1678, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/home/julian/miniconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/jit/__init__.py", line 1499, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/home/julian/miniconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'RecursiveScriptModule' object has no attribute 'forward'
```

## Expected behaviour

The expected behaviour is for the `scripted_lstm(*args)` not to output an error and return the tensor. 
I get this behaviour when I use `1.3` and replace the first x2 bash lines above with:
```shell
conda create -n pytorch1.3 python=3.7 pytorch=1.3 -c pytorch -y
conda activate pytorch1.3
```

## Environment

```shell
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti with Max-Q Design
Nvidia driver version: 430.64
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] torch-stft==0.1.4
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
```

## Additional context

N/A

**Comment by suo** [comment]
Bug reproduces for me, looks related to how we resolve overloads. That's quite bad.

**Comment by suo** [comment]
From @eellison: this is a known regression. The workaround is to call the lstm's forward from within a script function, like:
```
@torch.jit.script
def foo(input):
   scripted_lstm(input)
```

If you're curious about the implementation detail, it's because we need to statically know the types of the inputs in order to perform overload resolution (LSTM is somewhat special in that its `forward` method accepts either a Tensor or a PackedSequence). This is not strictly necessary, so we will fix it in a forthcoming release, but for now the workaround provides the static type information we need.

**Comment by julianmack** [comment]
Hi @suo and @eellison. Many thanks - the workaround solves it.

**Comment by narfanar** [comment]
This happens with a custom RNN cell (coincidence?!) stacked using a `nn.Sequential`.

I'll try to get a minimal example.

My custom cell takes only tensors, not packed sequences.

**Comment by zheddie** [comment]
hi @suo , I found you used an instance called "scripted_lstm", Can I know how to make it available? You know, the issue is LSTM can support both Tensor and PackedSequence. And also when we do the scripting , it tried to know the shape of the input . I am curious how to make a scripted_lstm without knowing of these information. thanks.

**Comment by JiahangXu** [comment]
Hi, I got a similar issue as this issue, #51835, and the discuss https://discuss.pytorch.org/t/no-graph-attribute-when-use-torch-jit-overload-method/76128. I cannot get the attr `.graph` for overloaded method, which is, however, necessary in my purpose. I wonder if @eellison has add the api like `model.forwards.graphs` (acutally the overloaded model does not have the attribute `forward` yet), or `model.forward.graph_for_types(1)` for users to get access to the graph with overloaded forward method. If the issue has been fixed, please let me know. Thanks a lot!

**Comment by RidiculousDoge** [comment]
hi @suo, I wonder if there is a solution to this problem?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
