### ISSUE TITLE
Segfault running pytorch + onnx

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#33003]
## 🐛 Bug
I'm getting a segfault when running this binary https://download.pytorch.org/whl/cu100/torch-1.4.0%2Bcu100-cp36-cp36m-linux_x86_64.whl together with onnx 1.6 installed from pypi.

I'm getting the following stack trace:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007f28b63c3cdf in std::_Hashtable<std::string, std::pair<std::string const, std::pair<std::unordered_set<std::string const*, std::hash<std::string const*>, std::equal_to<std::string const*>, std::allocator<std::string const*> >, std::string> >, std::allocator<std::pair<std::string const, std::pair<std::unordered_set<std::string const*, std::hash<std::string const*>, std::equal_to<std::string const*>, std::allocator<std::string const*> >, std::string> > >, std::__detail::_---Type <return> to continue, or q <return> to quit---
Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear() ()
   from /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so
#0  0x00007f28b63c3cdf in std::_Hashtable<std::string, std::pair<std::string const, std::pair<std::unordered_set<std::string const*, std::hash<std::string const*>, std::equal_to<std::string const*>, std::allocator<std::string const*> >, std::string> >, std::allocator<std::pair<std::string const, std::pair<std::unordered_set<std::string const*, std::hash<std::string const*>, std::equal_to<std::string const*>, std::allocator<std::string const*> >, std::string> > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear()
    () from /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so
#1  0x00007f288c37dea7 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#2  0x00007f288c478dd6 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#3  0x00007f288c430e67 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
---Type <return> to continue, or q <return> to quit---
#4  0x00007f288c42bffe in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#5  0x00007f288c433cf5 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#6  0x00007f288c4a045d in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#7  0x00007f288c4a0f46 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#8  0x00007f288c4a2484 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#9  0x00007f288c4a29cb in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#10 0x00007f288c35dec3 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#11 0x00007f288c37728b in ?? ()
   from /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-3---Type <return> to continue, or q <return> to quit---
6m-x86_64-linux-gnu.so
#12 0x000000000050ac25 in ?? ()
#13 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#14 0x0000000000509d48 in ?? ()
#15 0x000000000050aa7d in ?? ()
#16 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#17 0x0000000000509d48 in ?? ()
#18 0x000000000050aa7d in ?? ()
#19 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#20 0x0000000000508245 in ?? ()
#21 0x000000000050a080 in ?? ()
#22 0x000000000050aa7d in ?? ()
#23 0x000000000050d390 in _PyEval_EvalFrameDefault ()
#24 0x0000000000508245 in ?? ()
#25 0x000000000050a080 in ?? ()
#26 0x000000000050aa7d in ?? ()
#27 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#28 0x0000000000508245 in ?? ()
#29 0x000000000050a080 in ?? ()
#30 0x000000000050aa7d in ?? ()
#31 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#32 0x0000000000509d48 in ?? ()
#33 0x000000000050aa7d in ?? ()
---Type <return> to continue, or q <return> to quit---
#34 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#35 0x0000000000509d48 in ?? ()
#36 0x000000000050aa7d in ?? ()
#37 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#38 0x0000000000508245 in ?? ()
#39 0x000000000050b403 in PyEval_EvalCode ()
#40 0x0000000000635222 in ?? ()
#41 0x00000000006352d7 in PyRun_FileExFlags ()
#42 0x0000000000638a8f in PyRun_SimpleFileExFlags ()
#43 0x0000000000639631 in Py_Main ()
#44 0x00000000004b0f40 in main ()
```

so it looks like onnx is calling symbol defined in libtorch.so, and crashes due to binary compatibility issues. Recompiling onnx does fix the issue for me.

So I'm wondering whether the offending symbol:
```
std::_Hashtable<std::string, std::pair<std::string const, std::pair<std::unordered_set<std::string const*, std::hash<std::string const*>, std::equal_to<std::string const*>, std::allocator<std::string const*> >, std::string> >, std::allocator<std::pair<std::string const, std::pair<std::unordered_set<std::string const*, std::hash<std::string const*>, std::equal_to<std::string const*>, std::allocator<std::string const*> >, std::string> > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear()
```
should be made invisible. 

I can prepare further instructions to reproduce if needed. But if it's an issue of visibility I perhaps don't have to.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by huangrichen11** [comment]
what is your complie version ? i got same error

**Comment by ppwwyyxx** [comment]
No longer seeing the same error no pytorch 1.5 & cu101
