### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by junjimei** [pytorch/pytorch#33029]
**Hi, I'm trying to run this code from the following repository (https://github.com/CorentinJ/Real-Time-Voice-Cloning), I already installed all requirements, however I'm getting this error when I run the demo_cli.py:**

AssertionError: Torch not compiled with CUDA enabled

**This is the full text I get when I run it:**

runfile('C:/Users/isabel/Desktop/VOICE CLONER/Real-Time-Voice-Cloning-master/demo_cli.py', wdir='C:/Users/isabel/Desktop/VOICE CLONER/Real-Time-Voice-Cloning-master')
Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    low_mem:           False
    no_sound:          False

Running a test of your configuration...

Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.
Traceback (most recent call last):

  File "<ipython-input-6-e2d49148a56d>", line 1, in <module>
    runfile('C:/Users/isabel/Desktop/VOICE CLONER/Real-Time-Voice-Cloning-master/demo_cli.py', wdir='C:/Users/isabel/Desktop/VOICE CLONER/Real-Time-Voice-Cloning-master')

  File "C:\Users\isabel\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile

  File "C:\Users\isabel\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    # =============================================================================

  File "C:/Users/isabel/Desktop/VOICE CLONER/Real-Time-Voice-Cloning-master/demo_cli.py", line 47, in <module>
    device_id = torch.cuda.current_device()

  File "C:\Users\isabel\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 377, in current_device
    _lazy_init()

  File "C:\Users\isabel\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 196, in _lazy_init
    _check_driver()

  File "C:\Users\isabel\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")

AssertionError: Torch not compiled with CUDA enabled

**CUDA 10.0 is installed. I already tried uninstalling Pytorch and installing it again with the command "conda install pytorch torchvision cudatoolkit=10.0 -c pytorch", but it didn't work. Can anyone help with this issue?? Thank you so much!**

**Comment by peterjc123** [comment]
What is the output of `conda list | findstr "torch"`? Do you have multiple installation of Anaconda?
