### ISSUE TITLE
RuntimeError: tensor does not have a device?

### ISSUE THREAD

**Issue by jecampagne** [pytorch/pytorch#33037]
## 🐛 Bug

RuntimeError: tensor does not have a device

## To Reproduce
import torch
import torch.nn as nn
from torch.autograd import grad

x= torch.randn(2,5,64,64,dtype=torch.float)
x.requires_grad = True
x1 = nn.Conv2d(5,64,5, padding=2, bias=True)(x)
x1 = nn.PReLU(64, init=0.25)(x1)
x2 = nn.Conv2d(5,32,3, padding=1, bias=True)(x)
x2 = nn.PReLU(32, init=0.25)(x2)
out = torch.cat((x1, x2), dim=1)
out = nn.Linear(64,1)(out)
out = nn.Sigmoid()(out)
g, = grad(out.sum(), x, create_graph=True)
grad(g.sum(), x)
```





## Environment


## Additional context
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.2.1                    py37_0
<!-- Add any other context about the problem here. -->


```
I have run with a recent night build '1.5.0.dev20200204'` and the problem  rises a different error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: tensor does not have a device (device at /opt/conda/conda-bld/pytorch_1580803991946/work/c10/core/TensorImpl.h:463)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x4e (0x2b5fdb439f5e in .../anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: at::Tensor::options() const + 0x1ef (0x2b5fa2511adf in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: torch::autograd::generated::SliceBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0xea (0x2b5fac25fa9a in.../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x2e6e26d (0x2b5fac9da26d in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x152b (0x2b5fac9d675b in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x588 (0x2b5fac9d7bf8 in.../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::thread_init(int) + 0x39 (0x2b5fac9cee19 in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x2b5fa28e0e38 in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xc819d (0x2b5fa011919d in .../anaconda3/lib/python3.7/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #9: <unknown function> + 0x7e65 (0x2b5f815e2e65 in /lib64/libpthread.so.0)
frame #10: clone + 0x6d (0x2b5f818f588d in /lib64/libc.so.6)
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by jecampagne** [comment]
Here is the results with the nightly build
```
### Training model ###
> Parameters:
	batch_size: 2
	epochs: 5
	nloop: 5
Use device....:  cpu
Traceback (most recent call last):
  File "bugs_v4.py", line 117, in <module>
    main()
  File "bugs_v4.py", line 107, in main
    grad(g.sum(), new_img_batch)
  File ".../anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: tensor does not have a device (device at /opt/conda/conda-bld/pytorch_1580803991946/work/c10/core/TensorImpl.h:463)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x4e (0x7f23dbfe7f5e in .../anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: at::Tensor::options() const + 0x1ef (0x7f240df50adf in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: torch::autograd::generated::SliceBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0xea (0x7f240a81aa9a in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x2e6e26d (0x7f240af9526d in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x152b (0x7f240af9175b in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x588 (0x7f240af92bf8 in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f240af89e19 in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f240e31fe38 in .../anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xc819d (0x7f241753819d in .../anaconda3/lib/python3.7/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #9: <unknown function> + 0x7e65 (0x7f2435dc5e65 in /lib64/libpthread.so.0)
frame #10: clone + 0x6d (0x7f2435aee88d in /lib64/libc.so.6)
```

with the following settings

```
Collecting environment information...
PyTorch version: 1.5.0.dev20200204
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.5.0.dev20200204
[pip] torchvision==0.6.0a0+7741c84
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.5.0.dev20200204 py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.6.0.dev20200204      py37_cu101    pytorch-nightly
```

**Comment by ptrblck** [comment]
For the sake of completeness: [related forum post](https://discuss.pytorch.org/t/runtimeerror-tensor-does-not-have-a-device/67556) with some debugging information.

**Comment by fmassa** [comment]
cc @albanD who already started debugging the issue in the forum post

**Comment by mrshenli** [comment]
Another occurrence #37765, seems to be a race?

**Comment by albanD** [comment]
No this one is not a race, it is just that the backward formula is not handling undefined Tensors (that correspond to a Tensor full of 0s) properly.

**Comment by mrshenli** [comment]
> No this one is not a race, it is just that the backward formula is not handling undefined Tensors (that correspond to a Tensor full of 0s) properly.

I see. Then this is different from #37765 which does not seem to use undefined tensors.

**Comment by albanD** [comment]
The formula should properly handle this now.

**Comment by HernandoR** [comment]
FYI, I solved my case of `RuntimeError: tensor does not have a device?` by aligning my compile version of torch and running version.

My error occurred when accessing x.device in my cpp extension of torch. after specify build time dependency, it was gone. i.e.
```toml
[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "pybind11",
    "jinja2",
    "cython",
    "torch>=2.2.0,<2.3.0",
    "numpy",
]
```
