### ISSUE TITLE
Conv Transposed + Layer Norm = "RuntimeError: columns needs to be contiguous"

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#33168]
## 🐛 Bug

I'm unable to run layer normalization after a transposed convolution in PyTorch 1.4.

## To Reproduce

```python
import torch

in_channels = 64
out_channels = 128
scale_factor = 8
batch_size = 8
length = 16

conv = torch.nn.ConvTranspose1d(
    in_channels, out_channels, kernel_size=scale_factor * 2, stride=scale_factor)
layer_norm = torch.nn.LayerNorm(out_channels)

input_ = torch.randn(batch_size, in_channels, length).contiguous()
input_ = conv(input_).contiguous()
input_ = layer_norm(input_.transpose(1, 2).contiguous()).contiguous()
input_.sum().backward()
```

```bash
Traceback (most recent call last):
  File "blah.py", line 15, in <module>
    input_.sum().backward()
  File "/Users/michaelp/Code/Text-to-Speech/venv/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/michaelp/Code/Text-to-Speech/venv/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: columns needs to be contiguous
```

cc @VitalyFedyunin

**Comment by cpuhrsch** [comment]
@VitalyFedyunin - could this be related to memory formats?

**Comment by VitalyFedyunin** [comment]
We havn't touched Conv1d yet, but this is in my area of expertise to debug and fix, I will take over this issue.

**Comment by VitalyFedyunin** [comment]
Note: Reproducible on nightly (master) as well

**Comment by VitalyFedyunin** [comment]
Fixed

**Comment by Guitaricet** [comment]
Is there any workaround for this issue until new pytorch release?
