### ISSUE TITLE
torch.Tensor.add, add_, etc. documentation doesn't match api.

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#33187]
## 📚 Documentation

For example [torch.add](https://pytorch.org/docs/master/tensors.html#torch.Tensor.add) says

```
add(value) → Tensor
    add(other, *, value=1) -> Tensor

    See torch.add()
```

But indeed the value flag doesn't exist.

```
>>> import torch
>>> a = torch.randn(1, 3)
>>> b = torch.randn(1, 3)
>>> a
tensor([[-0.5835, -0.1405, -1.8119]])
>>> b
tensor([[ 0.8623, -1.3727,  1.5434]])
>>> a.add(b)
tensor([[ 0.2789, -1.5132, -0.2685]])
>>> a.add(b, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() takes 1 positional argument but 2 were given
>>> a.add(b, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() takes 1 positional argument but 2 were given
>>> a.add(b, valu=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() got an unexpected keyword argument 'valu'
>>> a.add(b, value=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() got an unexpected keyword argument 'value'
>>> a.add(b, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() takes 1 positional argument but 2 were given
```

Instead one has to use ```alpha``` as a flag.

```
>>> import torch
>>> a = torch.randn(1, 3)
>>> b = torch.randn(1, 3)
>>> a.add(a, alpha=3.0)
tensor([[ 3.3190, -0.4248, -3.6609]])
```

There are many other instances of this in the documentation.

**Comment by gchanan** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/19200.
