### ISSUE TITLE
Loading pretrained model

### ISSUE THREAD

**Issue by enjoykcc456** [pytorch/pytorch#33180]
Hi, 

Recently i have converted a detectron model using the tools/convert_pkl_to_pb.py from Detetron repo which results in model_init.pb,  model.pb and model.pbtxt. Then, i try to load the pretrained model following this tutorial (https://github.com/facebookarchive/tutorials/blob/master/Loading_Pretrained_Models.ipynb). By, following through the tutorial, i was able to make predictions using the provided model. However, when i try with the converted model, the following error occurs. 

```
[E operator.cc:203] Cannot find operator schema for BatchPermutation. Will skip schema checking.
Traceback (most recent call last):
  File "infer.py", line 153, in <module>
    p = workspace.Predictor(init_net, predict_net)
  File "/opt/conda/lib/python3.6/site-packages/caffe2/python/workspace.py", line 186, in Predictor
    return C.Predictor(StringifyProto(init_net), StringifyProto(predict_net))
RuntimeError: [enforce fail at operator.cc:273] op. Cannot create operator of type 'BatchPermutation' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "roi_feat_shuffled" input: "rois_idx_restore_int32_gpu_0" output: "roi_feat" name: "" type: "BatchPermutation" device_option { device_type: 1 device_id: 0 }
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x5b (0x7fd70bf1341b in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int) + 0xc14 (0x7fd70eaec084 in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #2: caffe2::SimpleNet::SimpleNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x2e0 (0x7fd70eae4040 in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #3: <unknown function> + 0x278338e (0x7fd70eae638e in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #4: std::_Function_handler<std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > (std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*), std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > (*)(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*&&) + 0xf (0x7fd70eabaf7f in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #5: caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x464 (0x7fd70eaacb74 in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #6: caffe2::Workspace::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, bool) + 0xfe (0x7fd70eb297ee in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #7: caffe2::Predictor::Predictor(caffe2::PredictorConfig) + 0x323 (0x7fd70edbb853 in /opt/conda/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #8: <unknown function> + 0x4f8a5 (0x7fd73e1298a5 in /opt/conda/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x4fb77 (0x7fd73e129b77 in /opt/conda/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x95696 (0x7fd73e16f696 in /opt/conda/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #30: __libc_start_main + 0xf0 (0x7fd76da8e830 in /lib/x86_64-linux-gnu/libc.so.6)
```
Anyone knows why this happen?

Thanks

**Comment by enjoykcc456** [comment]
Hi, i have solve issue mentioned above by importing the Detectron ops.
```
from caffe2.python import dyndep
import detectron.utils.env as envu

def import_detectron_ops():
    """Import Detectron ops."""
    detectron_ops_lib = envu.get_detectron_ops_lib()
    dyndep.InitOpsLibrary(detectron_ops_lib)

import_detectron_ops()
```
However, when i tried to run the inference script again on the model converted by using tools/convert_pkl_to_pb.py with argument of --device cpu. The following error occurs.

```
Traceback (most recent call last):
  File "test_pytorch_infer/infer.py", line 168, in <module>
    results = p.run({'data': img})
RuntimeError: [enforce fail at conv_op.cc:24] nnpack_status == nnp_status_success. NNPack is not supported here!
Error from operator: 
input: "data" input: "conv1_w" input: "res_conv1_bn_b" output: "conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "stride" i: 2 } arg { name: "pad" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { } engine: "NNPACK"frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7fc6557092e7 in /pytorch/build/lib/libc10.so)
frame #1: <unknown function> + 0x27ea1ad (0x7fc62aa6d1ad in /pytorch/build/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0xea99 (0x7fc65b9d5a99 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #3: <unknown function> + 0x27ea0f3 (0x7fc62aa6d0f3 in /pytorch/build/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x27ebdd3 (0x7fc62aa6edd3 in /pytorch/build/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x2070fb5 (0x7fc62a2f3fb5 in /pytorch/build/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x1f4c515 (0x7fc62a1cf515 in /pytorch/build/lib/libtorch_cpu.so)
frame #7: caffe2::SimpleNet::Run() + 0x196 (0x7fc629ef6e46 in /pytorch/build/lib/libtorch_cpu.so)
frame #8: caffe2::Workspace::RunNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x120 (0x7fc629f42830 in /pytorch/build/lib/libtorch_cpu.so)
frame #9: caffe2::Predictor::run_map_workspace(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, caffe2::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, caffe2::Tensor> > > const&) + 0x497 (0x7fc62a2594f7 in /pytorch/build/lib/libtorch_cpu.so)
frame #10: caffe2::Predictor::operator()(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, caffe2::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, caffe2::Tensor> > > const&, std::vector<caffe2::Tensor, std::allocator<caffe2::Tensor> >*) + 0x2e (0x7fc62a25a6fe in /pytorch/build/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x54883 (0x7fc655dae883 in /pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x9b4f0 (0x7fc655df54f0 in /pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-x86_64-linux-gnu.so)
<omitting python frames>
frame #15: python3() [0x539a13]
frame #17: python3() [0x6292c2]
frame #22: __libc_start_main + 0xf0 (0x7fc65b61d830 in /lib/x86_64-linux-gnu/libc.so.6)
```

Then, when i run the inference script on the model converted with argument --device gpu. The following error occurs. 
```
Traceback (most recent call last):
  File "test_pytorch_infer/infer.py", line 167, in <module>
    results = p.run({'data': img})
RuntimeError: [enforce fail at predictor.cc:14] BlobIsTensorType(*blob, CPU). Blob is not a CPU Tensor: data
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7f7bba2e02e7 in /pytorch/build/lib/libc10.so)
frame #1: <unknown function> + 0x1fd3edf (0x7f7b8ee2dedf in /pytorch/build/lib/libtorch_cpu.so)
frame #2: caffe2::Predictor::run_map_workspace(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, caffe2::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, caffe2::Tensor> > > const&) + 0x3e4 (0x7f7b8ee30444 in /pytorch/build/lib/libtorch_cpu.so)
frame #3: caffe2::Predictor::operator()(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, caffe2::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, caffe2::Tensor> > > const&, std::vector<caffe2::Tensor, std::allocator<caffe2::Tensor> >*) + 0x2e (0x7f7b8ee316fe in /pytorch/build/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x54883 (0x7f7bba985883 in /pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x9b4f0 (0x7f7bba9cc4f0 in /pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-35m-x86_64-linux-gnu.so)
<omitting python frames>
frame #8: python3() [0x539a13]
frame #10: python3() [0x6292c2]
frame #15: __libc_start_main + 0xf0 (0x7f7bc01f4830 in /lib/x86_64-linux-gnu/libc.so.6)
```
Anyone knows what should i do to fix this?

Thanks in advance.
