### ISSUE TITLE
PyTorch 1.4.0 expects wrong number of input arguments for `@ignore` annotated method in ScriptModule

### ISSUE THREAD

**Issue by haowen-xu** [pytorch/pytorch#33397]
## 🐛 Bug

PyTorch 1.4.0 expects wrong number of input arguments for `@ignore`  annotated method in ScriptModule.

## To Reproduce

The following piece of code:

```python
class MyModule(torch.nn.Module):

    @ignore
    def python_func(self, x: Tensor) -> Tensor:
        return x + x

    def forward(self, input: Tensor) -> Tensor:
        return self.python_func(input)


m = script(MyModule())
print(m.code)
```

would produce the following traceback:

```
Traceback (most recent call last):
  File "/Users/ipwx/projects/tensorkit/debug.py", line 17, in <module>
    m = script(MyModule())
  File "/opt/local/miniconda3/envs/py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/opt/local/miniconda3/envs/py3.6/lib/python3.6/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/opt/local/miniconda3/envs/py3.6/lib/python3.6/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/opt/local/miniconda3/envs/py3.6/lib/python3.6/site-packages/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/opt/local/miniconda3/envs/py3.6/lib/python3.6/site-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 

(__torch__.MyModule self, Tensor 0, Tensor 1) -> (Tensor 0):
Argument 1 not provided.
:
  File "/Users/ipwx/projects/tensorkit/debug.py", line 14
    def forward(self, input: Tensor):
        return self.python_func(input)
               ~~~~~~~~~~~~~~~~ <--- HERE
```

And I cannot understand why it expects two input tensors rather than one.

## Expected behavior

The above code should run without error.

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Mac OSX 10.15.3
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): none
 - Python version: 3.6
 - CUDA/cuDNN version: none
 - GPU models and configuration: none
 - Any other relevant information: none

cc @suo

**Comment by suo** [comment]
Thanks for the report! I'll take a look

**Comment by eellison** [comment]
I think this was fixed with https://github.com/pytorch/pytorch/pull/29300...

**Comment by driazati** [comment]
Closing since this is fixed on master (you can get the fix locally by using the nightly version of PyTorch instead of `v1.4.0`)
