### ISSUE TITLE
test_jit_fuser is flaky on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#33401]
## 🐛 Bug

Error text:
```pytb
======================================================================
ERROR: test_abs_cpu (__main__.TestFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 592, in wrapper
    fn(*args, **kwargs)
  File "test_jit_fuser.py", line 79, in test_abs_cpu
    self._test_fused_abs()
  File "test_jit_fuser.py", line 74, in _test_fused_abs
    self.assertAllFused(func.graph_for(a))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\jit\__init__.py", line 2094, in _graph_for
    self(*args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 87, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 84, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: Caught an unknown exception!

======================================================================
ERROR: test_chunk_correctness (__main__.TestFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 592, in wrapper
    fn(*args, **kwargs)
  File "test_jit_fuser.py", line 223, in test_chunk_correctness
    return self._test_chunk_correctness(self, 'cpu')
  File "test_jit_fuser.py", line 218, in _test_chunk_correctness
    self.checkScript(fn, [tensor])
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 398, in checkScript
    opt_script_outputs = scripted_fn(*recording_inputs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 87, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 84, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: Caught an unknown exception!

======================================================================
ERROR: test_scalar (__main__.TestFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 592, in wrapper
    fn(*args, **kwargs)
  File "test_jit_fuser.py", line 851, in test_scalar
    ge = self.checkScript(fn, (x, y))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 398, in checkScript
    opt_script_outputs = scripted_fn(*recording_inputs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 87, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 84, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: Caught an unknown exception!

======================================================================
ERROR: test_where_and_typing (__main__.TestFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 592, in wrapper
    fn(*args, **kwargs)
  File "test_jit_fuser.py", line 906, in test_where_and_typing
    self.assertAllFused(script_f.graph_for(x, y), except_for={'prim::TupleConstruct'})
  File "C:\Users\circleci\project\build\win_tmp\build\torch\jit\__init__.py", line 2094, in _graph_for
    self(*args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 87, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 84, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: Caught an unknown exception!

----------------------------------------------------------------------
Ran 46 tests in 11.883s

FAILED (errors=4, skipped=10)
Traceback (most recent call last):
  File "run_test.py", line 486, in <module>
    main()
  File "run_test.py", line 479, in main
    raise RuntimeError(message)
RuntimeError: test_jit_fuser failed!
```

## To Reproduce

1. python setup.py build
2. python run_test,py -i jit_fuser

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): source
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla P4
 - Any other relevant information:

## Additional context

This is likely due to the AVX512 auto vectorizer supported in the latest build of VS 2019. I'll try to figure out how to correctly detect whether it is supported on a client machine.

cc @ezyang @gchanan @zou3519 @suo

**Comment by peterjc123** [comment]
Looks like I'm wrong. It fails even when `/arch:AVX2` is applied. What's more, the exception is thrown during the call of `scripted_func.graph_for`, which is not related to the fuser code. cc @ezyang

**Comment by peterjc123** [comment]
Maybe https://github.com/pytorch/pytorch/pull/33336 is the cause.

**Comment by peterjc123** [comment]
Interestingly, the issue is caused by the wrong usage of `_spawnve`. The third parameter `argv` in that function requires an array of `const char *` that ends with `nullptr`. Repairing it fixes the issue.
