### ISSUE TITLE
Dataloader make reading slower

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#33407]
# dataset: image_dataset.py
```
# -*-coding:utf-8-*-

import os
import cv2
import time


class ImageDataset(object):
  def __init__(self, data_path="/home/zgz/DataSet/coco/2017/train2017"):
    self.data_path = data_path

    self.image_list = []
    for root, dirs, files in os.walk(data_path):
      for file in files:
        if file.endswith("jpg"):
          image_file = os.path.join(root, file)
          self.image_list.append(image_file)
    self.image_totoal_num = len(self.image_list)

    self.image_num = 0

  def __len__(self):
    return self.image_totoal_num

  def __getitem__(self, index):
    # print("coco dataset : {}".format(self.image_num))
    # start_time = time.time()
    self.image_num = self.image_num + 1
    image = cv2.imread(self.image_list[index])
    aug_image = cv2.resize(image, (468, 468))
    # print("{} cost time : {}".format(self.image_num, time.time() - start_time))
    return aug_image

image_loader = ImageDataset()
```

# data loader test script：
```
# dataloader
import os, time
import torch
import random

print(torch.__version__)
from torch.multiprocessing import Process, Manager, Lock

print("mutli test")
from image_dataset import image_loader


def image_reader(sign, share_ls, lock):
  print(sign, 'pid:', os.getpid())
  max_len = len(image_loader)

  from torch.utils.data import DataLoader
  pytorch_loader = DataLoader(dataset=image_loader,
                              batch_size=3,
                              shuffle=False,
                              sampler=None,
                              batch_sampler=None,
                              num_workers=0,
                              collate_fn=None,
                              pin_memory=False,
                              drop_last=False,
                              timeout=0,
                              worker_init_fn=None,
                              multiprocessing_context=None)

  for _ in range(10000):
    index = random.randint(0, max_len)
    aug_image = image_loader[index]

  # for _ in pytorch_loader:
    with lock:
      share_ls[0] = share_ls[0] + 1
      # print("{} : {}".format(os.getpid(), share_ls[0]))
      if share_ls[0] % 1000 == 0:
        cur_time = time.time()
        print("reader {} , total time: {}, cur time: {}".format(share_ls[0],
                                                                cur_time - share_ls[1],
                                                                cur_time - share_ls[2]))
        share_ls[2] = cur_time


# Main
def run():
  print('Main:', os.getpid())

  m = Manager()
  share_ls = m.list()
  total_reader_num = 0
  total_start_time = time.time()
  cur_start_time = time.time()
  share_ls.append(total_reader_num)
  share_ls.append(total_start_time)
  share_ls.append(cur_start_time)

  plist = []
  lock = Lock()
  for j in range(5):
    p = Process(target=image_reader, args=('process', share_ls, lock))
    p.start()
    plist.append(p)

  for p in plist:
    p.join()
  print("test =================================")


if __name__ == "__main__":
  run()
```
When I comment 
```
for _ in range(10000):
    index = random.randint(0, max_len)
    aug_image = image_loader[index]
```
to use `for _ in pytorch_loader`, the program become slow.

cc @SsnL

**Comment by as754770178** [comment]
I try my code and find that `pin_memory` will cost some time. If `pin_memory=False` total cost time: 168s,  If `pin_memory=True` total cost time: 294s.
I suggest put `pin_memory`  at the end of `_worker_loop`. I test that get data from `worker_result_queue` also cost time.

**Comment by SsnL** [comment]
You are not using `num_workers > 0` so the worker related variables are not relevant. 

Memory pinning must be done in main process as most of the times you do not want the worker processes to initialize CUDA contexts. 

The data loader also converts the NumPy array to PyTorch Tensors and collates them into a batch, which your 
```py
for _ in range(10000):
    index = random.randint(0, max_len)
    aug_image = image_loader[index]
```
does not do. They also return different number of samples. So the two timings are not comparable.

**Comment by as754770178** [comment]
Sorry, I didn't describe it clearly.
If `num_workers == 0` and control process number by `torch.multiprocessing`, the two programs work the same.

If  control process number by `num_workers`, the effects of the two programs are inconsistent. The delay is mainly due to the following aspects:
(1) get data from queue
(2) Ensure that the order of fetching and storing data in `data_queue` is consistent, that `rcvd_idx 
== send_idx`.
(3) `index_queue` control number of prefetched data. Sometimes `index_queue` empty, `worker_loop` must wait
(4) add pin_momery and convert Tensor operation

I have a question that convert Tensor exec by `collate_fn` in `worker_loop`. We can also pass a parameter control whether exec memeory pinning in  `worker_loop`.  I think memeory pinning in `worker_loop` also can't go wrong, although this is not necessary. But I don't think memory pinning must be done in main process.

**Comment by as754770178** [comment]
I think Queue solves the problem that put faster than get. When use small model, forward is very fast.
pin_memory does not play a cache effect, and memory pinning in single thread is slow.

**Comment by as754770178** [comment]
I try put `pin_memory` in `worker_loop`, report error:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=3 : initialization error
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/python14/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/python14/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zgz/jinn_code/boundary_project/pytorch_dataloader_test/pytorch_dataloader_test.py", line 44, in image_reader
    for _ in pytorch_loader:
  File "/usr/local/python14/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zgz/jinn_code/Jinn/dh_aiflow/dh_aiflow_utils/dh_dataloader/dataloader.py", line 141, in _next_data
    return self._process_data(data)
  File "/usr/local/python14/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 882, in _process_data
    data.reraise()
  File "/usr/local/python14/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/zgz/jinn_code/Jinn/dh_aiflow/dh_aiflow_utils/dh_dataloader/worker.py", line 87, in dh_worker_loop
    data = pin_memory(data)
  File "/usr/local/python14/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 47, in pin_memory
    return data.pin_memory()
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/THCGeneral.cpp:50
```
Can you explain why?
Is it caused by multiple processes being initialized at the same time?

**Comment by as754770178** [comment]
#685
