### ISSUE TITLE
`torch.seed()` and `torch.initial_seed()` returns not-long numbers

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#33546]
Our function that give the current or initial seed do not play well with setting these seeds.

```python
import torch

torch.manual_seed(torch.initial_seed()) # Same with torch.seed()
```
Fails with:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-055df2441829> in <module>
----> 1 import torch; torch.manual_seed(torch.initial_seed())

source/torch/random.py in manual_seed(seed)
     32         torch.cuda.manual_seed_all(seed)
     33
---> 34     return default_generator.manual_seed(seed)
     35
     36

RuntimeError: Overflow when unpacking long
```

cc @ezyang @gchanan @zou3519 @pbelevich

**Comment by SsnL** [comment]
:) if we fix this, we can finally just use `np.random.seed(torch.initial_seed())`

**Comment by vishwakftw** [comment]
With ebb008e, I seem to not be getting any errors with the MWE.

**Comment by jonasrauber** [comment]
Actually, because of this even just `torch.seed()` fails if you have GPU.

**Comment by GuillaumeLeclerc** [comment]
It seems impossible to have pseudo-randomness in a section of the code (in my case train test split) without making the whole code deterministic as we are unable to restore the initial state of the RNG.

**Comment by stas00** [comment]
Another similar issue that affects multiple tests in transformers.

https://github.com/huggingface/transformers/issues/5639

to reproduce:
```
# test.py
import torch
print(f"Torch version: f{torch.__version__}")

x = torch.tensor(data=[[1,2],[3,4]], dtype=torch.long, device=None)
x = x.to('cuda:0')
seed = torch.seed()
```

```
$ python tests/test.py
Torch version: f1.5.1

Traceback (most recent call last):
  File "tests/test.py", line 10, in <module>
    seed = torch.seed()
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/random.py", line 45, in seed
    torch.cuda.manual_seed_all(seed)
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/cuda/random.py", line 111, in manual_seed_all
    _lazy_call(cb)
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/cuda/__init__.py", line 99, in _lazy_call
    callable()
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/cuda/random.py", line 109, in cb
    default_generator.manual_seed(seed)
RuntimeError: Overflow when unpacking long
```

**Comment by stas00** [comment]
Thank you very much for fixing this bug!
