### ISSUE TITLE
JIT tracing check fails with boolean tensor modifications

### ISSUE THREAD

**Issue by jseppanen** [pytorch/pytorch#33692]
## 🐛 Bug

Tracing code that modifies a boolean tensor fails with TracingCheckError. Tracing works only with `torch.jit.trace(..., check_trace=False)`.

## To Reproduce

Small repro case:

```
import torch
import torch.nn


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self):
        mask = torch.zeros(5, dtype=torch.bool)
        mask[1] = True
        return mask


model = Model()

# fails with torch.jit.TracingCheckError
traced_model = torch.jit.trace(model, ())

# works
#traced_model = torch.jit.trace(model, (), check_trace=False)
```

Running `python bool_trace.py` fails with:

```
Traceback (most recent call last):
  File "bool_trace.py", line 17, in <module>
    traced_model = torch.jit.trace(model, ())
  File "/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1044, in trace_module
    check_tolerance, _force_outplace, True, _module_class)
  File "/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/jit/__init__.py", line 685, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit.TracingCheckError: Tracing failed sanity checks!
ERROR: Tensor-valued Constant nodes differed in value across invocations. This often indicates that the tracer has encountered untraceable code.
	Node:
		%11 : Tensor = prim::Constant[value={1}]() # bool_trace.py:12:0
	Source Location:
		bool_trace.py(12): forward
		/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
		/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
		/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/jit/__init__.py(1034): trace_module
		/home/jarno/miniconda3/envs/scratch/lib/python3.6/site-packages/torch/jit/__init__.py(882): trace
		bool_trace.py(17): <module>
	Comparison exception: 	Subtraction, the `-` operator, with two bool tensors is not supported. Use the `^` or `logical_xor()` operator instead.
```

## Expected behavior

tracing should work equally well with `check_trace=True` as `=False`

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
```

**Comment by acairncross** [comment]
This is being caused by `torch.testing.assert_allclose`, which tries to subtract tensors from each other, being called on pairs of bool tensor constants in the original and traced modules [here](https://github.com/pytorch/pytorch/blob/v1.4/torch/jit/__init__.py#L609). `numpy.testing.assert_allclose` doesn't have this problem since [it promotes (one of) its arguments to at least some float type](https://github.com/numpy/numpy/blob/v1.18.1/numpy/core/numeric.py#L2254-L2255).

Interestingly, `check_trace` only has a problem with constant nodes being bools, and not with the output/s being bool, because [the output is converted to double before being passed to `assert_allclose`](https://github.com/pytorch/pytorch/blob/v1.4/torch/jit/__init__.py#L655). This is why the `mask[1] = True` is needed to trigger the error.

**Comment by uchihaltachi** [comment]
I also met this mistake, how did you solve it

**Comment by acairncross** [comment]
This seems to have been fixed in master (b7b99ab0c8f82100177729b9751481852d83e77e), maybe due to #38872 ?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
