### ISSUE TITLE
pin_memory error in DataLoader

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#33754]
I want to accelerate DataLoader, so I add pin_memory in worker_loop. The code show as below:
```
        try:
          data = fetcher.fetch(index)
          from torch.utils.data._utils.pin_memory import pin_memory
          data = pin_memory(data)
        except Exception as e:
          if isinstance(e, StopIteration) and dataset_kind == _DatasetKind.Iterable:
            data = _IterableDatasetStopIteration(worker_id)
```
But program report error:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=3 : initialization error
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/python14/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/python14/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zgz/jinn_code/boundary_project/pytorch_dataloader_test/pytorch_dataloader_test.py", line 44, in image_reader
    for _ in pytorch_loader:
  File "/usr/local/python14/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zgz/jinn_code/Jinn/dh_aiflow/dh_aiflow_utils/dh_dataloader/dataloader.py", line 141, in _next_data
    return self._process_data(data)
  File "/usr/local/python14/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 882, in _process_data
    data.reraise()
  File "/usr/local/python14/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/zgz/jinn_code/Jinn/dh_aiflow/dh_aiflow_utils/dh_dataloader/worker.py", line 87, in dh_worker_loop
    data = pin_memory(data)
  File "/usr/local/python14/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 47, in pin_memory
    return data.pin_memory()
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/THCGeneral.cpp:50
```
Can you explain why?
Is it caused by multiple processes being initialized at the same time?

**Comment by SsnL** [comment]
You shouldn't do memory pinning in workers. It requires CUDA context, and using CUDA in multiprocessing is advised against. In particular, in `fork`, it does not work, as you observed. Using `spawn` would solve the CUDA initialization issue, but the tensor will need to be moved to shared memory for transfer, rendering the pinning useless.

In general, you shouldn't need to speed up memory pinning, as the computation would be the major bottleneck, and multithreaded pinning should not be hurting you.

**Comment by as754770178** [comment]
@SsnL 
```
# train.py
import time
import torch.multiprocessing as mp
from torch.utils.data import DataLoader
from image_dataset import ImageDataset


class CustomProcess(object):
  def __init__(self, dataset, model):
    self.dataset = dataset
    self.model = model

  def run(self):
    mp.spawn(self.train, nprocs=4)

  def train(self, id):
    pytorch_loader = DataLoader(dataset=self.dataset,
                                batch_size=64,
                                shuffle=False,
                                sampler=None,
                                batch_sampler=None,
                                num_workers=4,
                                collate_fn=None,
                                pin_memory=True,
                                drop_last=False,
                                timeout=0,
                                worker_init_fn=None,
                                multiprocessing_context=None)

    train_time = 0
    stime = time.time()
    # model.share_memory()
    for data in pytorch_loader:
      # train
      output = model(data)
      train_time = train_time + 1
      if train_time % 100 == 0:
        etime = time.time()
        print("train time: {}, cost time: {}".format(train_time, etime - stime))
        stime = etime


if __name__ == "__main__":
  process = CustomProcess(ImageDataset("./coco/train"))
  process.run()
```

I test that use `mp.spawn`, the `pin_memory` in DataLoader comes into effect. But I don't call `model.share_memory()`.
I have the following questions:
(1) call `share_memory()`  is not necessary for `mp.spawn`, or `mp.spawn` can call `share_memory()` automatically?
(2) `share_memory` and `pin_memory` conflict?
Now I don't understand the relation between `mp.spawn`, `share_memory` and `pin_memory`.

**Comment by as754770178** [comment]
@SsnL 
I try use `Process` not `spawn`, the `pin_memory` still useful.
```
import time
from torch.multiprocessing import Process

from image_dataset import ImageDataset
from torch.utils.data import DataLoader


def image_reader():
  pytorch_loader = DataLoader(dataset=ImageDataset("./coco/train"),
                              batch_size=64,
                              shuffle=False,
                              sampler=None,
                              batch_sampler=None,
                              num_workers=4,
                              collate_fn=None,
                              pin_memory=True,
                              drop_last=False,
                              timeout=0,
                              worker_init_fn=None,
                              multiprocessing_context=None)

  read_time = 0
  stime = time.time()
  for _ in pytorch_loader:
    read_time = read_time + 1
    if read_time % 100 == 0:
      etime = time.time()
      print("read time: {}, cost time: {}".format(read_time, etime - stime))
      stime = etime


def run():
  plist = []
  for j in range(5):
    p = Process(target=image_reader)
    p.start()
    plist.append(p)

  for p in plist:
    p.join()


if __name__ == "__main__":
  run()
```

**Comment by SsnL** [comment]
@as754770178 Your new scripts are different from your original change (described on the top of this issue) though. These new scripts surely will take advantage of pin_memory, because it is just running training in another process. However, if the dataloader workers do pin_memory, it will not be useful, for reasons I described above.
