### ISSUE TITLE
Tensor length mismatch in index_put_ with torch.uint8 indices

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#33751]
## 🐛 Bug

Runtime error with tensor shape mismatch on both CPU and GPU CUDA for index_put_. 

## To Reproduce

Run the following script 

```python
import torch 

N = 21

dt = torch.int8
# device = "cuda:0"
device = "cpu"

a = torch.ones(N, dtype=dt, device=device)
indices = torch.arange(0, N, dtype=torch.uint8, device=device)
values = torch.ones(N, dtype=dt, device=device)

print(a.shape)
print(indices.shape)
print(values.shape)

a.index_put_((indices, ), values, accumulate=True)

print(a)
```

Output with `device = "cuda:0"` 
```
torch.Size([21])
torch.Size([21])
torch.Size([21])
20 1 1 21
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at /home/xwang/Developer/pytorch/aten/src/ATen/native/IndexingUtils.h:20)
Traceback (most recent call last):
  File "/home/X/Developer/pytorch-test/index-put.py", line 23, in <module>
    a.index_put_((indices, ), values, accumulate=True)
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel() INTERNAL ASSERT FAILED at /home/xwang/Developer/pytorch/aten/src/ATen/native/cuda/Indexing.cu:219, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor2021
```
Note that "20 1 1 21" are from a printf statement I added [here](https://github.com/pytorch/pytorch/blob/adbe2898706982cd04be469116db0d39e162f3f1/aten/src/ATen/native/cuda/Indexing.cu#L218) for `linearIndex.numel(), sliceSize, nElemBefore, value.numel()`, which clearly shows an error. 

Output with `device = "cpu"` 
```
torch.Size([21])
torch.Size([21])
torch.Size([21])
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at ../aten/src/ATen/native/IndexingUtils.h:20)
Traceback (most recent call last):
  File "/home/X/Developer/pytorch-test/index-put.py", line 23, in <module>
    a.index_put_((indices, ), values, accumulate=True)
RuntimeError: shape mismatch: value tensor of shape [21] cannot be broadcast to indexing result of shape [20]
```

## Expected behavior

If we change the `dtype` of `indices` to `torch.long`, everything works fine. 

## Environment

PyTorch version: 1.5.0a0+a186246
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Fedora 31 (Workstation Edition)
GCC version: (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 440.31
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.5.0a0+a186246
[pip3] torchvision==0.4.2
[conda] Could not collect

## Additional context

I can help working on this problem. I'm just not sure if it's worth to do since `torch.uint8` indexing is stated to be "deprecated". 

cc @ezyang @gchanan @zou3519

**Comment by ngimel** [comment]
Thank you for your report. This is indeed a bug, but the bug is not what it appears to be. Before bool tensors were supported, uint8 tensors could be used for indexing, but they were interpreted only as boolean mask, not as actual indices values. If your example is rewritten to use uint8 tensor as a boolean mask, it works:
```
In [24]: import torch  
    ...:  
    ...: N = 21 
    ...:  
    ...: dt = torch.int8 
    ...: # device = "cuda:0" 
    ...: device = "cpu" 
    ...:  
    ...: a = torch.ones(N, dtype=dt, device=device) 
    ...: indices = torch.ones(N, dtype=torch.uint8, device=device) 
    ...: values = torch.ones(N, dtype=dt, device=device) 
    ...:  
    ...: print(a.shape) 
    ...: print(indices.shape) 
    ...: print(values.shape) 
    ...:  
    ...: a.index_put_((indices, ), values, accumulate=True) 
    ...:  
    ...: print(a)                                                                                                                        
```
but we indeed should fix misinterpretation of uint8 tensor as actual indices values - that should be simply forbidden and error out. Setting high priority because of a crash.

**Comment by tano297** [comment]
Hi @ngimel 

I am having this problem with long indexes when using the gpu.

I am trying to make a grid and then vote on it given certain indexes with index_put_ and accumulate=True.

Example to reproduce:

```py
import torch

# sizes for grid
B = 3
H = 3
W = 4

# grid
grid = torch.zeros(B, H, W).long()

# index for batch
batch_idx = torch.arange(B).repeat_interleave(H*W).long()

# index for H and W dimentions (for simplicity I only do (1,1) so we know what to expect)
hw_idx = torch.ones_like(batch_idx)

# do the indexing in the cpu
print("Index in CPU. Expected result is vote = H*W = 12 in every (1,1) pixel")
idx = torch.stack([batch_idx, hw_idx, hw_idx], dim=0)
vote = torch.tensor(1).long()
grid.index_put_(tuple(idx), vote, accumulate=True)
print(grid)

# do the same in gpu
print("Index result in GPU. Expected result is vote = H*W = 12 in every (1,1) pixel")
grid = grid.zero_().cuda()
idx = idx.cuda()
vote = vote.cuda()
grid.index_put_(tuple(idx), vote, accumulate=True)
print(grid)
```

Result:
```
$ python3 example.py 
Index in CPU. Expected result is vote = H*W = 12 in every (1,1) pixel
tensor([[[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]]])
Index result in GPU. Expected result is vote = H*W = 12 in every (1,1) pixel
Traceback (most recent call last):
  File "example.py", line 30, in <module>
    grid.index_put_(tuple(idx), vote, accumulate=True)
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Indexing.cu":220, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor361
```

Any pointers on how to go about trying to fix it? I'd like to help, since this is functionality I use a lot, and in pytorch 1.1 it was working for me. Thanks!

### Environment

PyTorch version: 1.6.0.dev20200609
OS: Ubuntu 18.04
Python version: 3.7
Is CUDA available: Yes
CUDA version: 10.2, V10.2.89
GPU models and configuration: GPU 0: NVIDIA Quadro P6000
Nvidia driver version: 440.33.01

**Comment by tano297** [comment]
@xwang233 can you please re-open this if you can verify the behavior?

**Comment by xwang233** [comment]
@tano297 I believe the problem you see is the same as https://github.com/pytorch/pytorch/issues/39227. `index_put` on GPU with `accumulate=True`, the `values` tensor is not automatically expanded to the shape of `indices`. You will need to expand that yourself, or wait for a fix.

**Comment by tano297** [comment]
I confirm this, you are very right.

```py
import torch

# sizes for grid
B = 3
H = 3
W = 4

# grid
grid = torch.zeros(B, H, W).long()

# index for batch
batch_idx = torch.arange(B).repeat_interleave(H*W).long()

# index for H and W dimentions (for simplicity I only do (1,1) so we know what to expect)
hw_idx = torch.ones_like(batch_idx)

# do the indexing in the cpu
print("Index in CPU. Expected result is vote = H*W = 12 in every (1,1) pixel")
idx = torch.stack([batch_idx, hw_idx, hw_idx], dim=0)
vote = torch.tensor(1).long()
grid.index_put_(tuple(idx), vote, accumulate=True)
print(grid)

# do the same in gpu
print("Index result in GPU (scalar value). Expected result is vote = H*W = 12 in every (1,1) pixel")
grid = grid.zero_().cuda()
idx = idx.cuda()
vote = vote.cuda()
try:
  grid.index_put_(tuple(idx), vote, accumulate=True)
  print(grid)
except Exception as e:
  print("FAILED")
  print(e)

# do the same in gpu
print("Index result in GPU (tensor value). Expected result is vote = H*W = 12 in every (1,1) pixel")
grid = grid.zero_().cuda()
idx = idx.cuda()
vote = vote.repeat(B*H*W).cuda()
grid.index_put_(tuple(idx), vote, accumulate=True)
print(grid)
```
Result:
```
python3 /home/tano/Downloads/example.py
Index in CPU. Expected result is vote = H*W = 12 in every (1,1) pixel
tensor([[[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]]])
Index result in GPU (scalar value). Expected result is vote = H*W = 12 in every (1,1) pixel
FAILED
linearIndex.numel()*sliceSize*nElemBefore == value.numel() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Indexing.cu":220, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor361
Index result in GPU (tensor value). Expected result is vote = H*W = 12 in every (1,1) pixel
tensor([[[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0, 12,  0,  0],
         [ 0,  0,  0,  0]]], device='cuda:0')
```
