### ISSUE TITLE
Flaky test test_quantized_rnn on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#33756]
## 🐛 Bug

Error text:
```pytb
======================================================================
ERROR: test_quantized_rnn (__main__.PostTrainingDynamicQuantTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_quantization.py", line 540, in test_quantized_rnn
    def test_quantized_rnn(self, qengine):
  File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 1116, in wrapped_test
    raise the_error_hypothesis_found
  File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 1071, in wrapped_test
    state.run_engine()
  File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 789, in run_engine
    info.__expected_traceback,
  File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 656, in execute_once
    % (test.__name__, text_repr[0])
  File "C:\Jenkins\Miniconda3\lib\site-packages\hypothesis\core.py", line 856, in __flaky
    raise Flaky(message)
hypothesis.errors.Flaky: Hypothesis test_quantized_rnn(self=<__main__.PostTrainingDynamicQuantTest testMethod=test_quantized_rnn>, qengine='fbgemm') produces unreliable results: Falsified on the first call but did not on a subsequent one

----------------------------------------------------------------------
Ran 36 tests in 63.768s

FAILED (errors=1, skipped=1)
Falsifying example: test_quantized_rnn(
    self=<__main__.PostTrainingDynamicQuantTest testMethod=test_quantized_rnn>,
    qengine='fbgemm',
)
Failed to reproduce exception. Expected: 
Traceback (most recent call last):
  File "test_quantization.py", line 736, in test_quantized_rnn
    y, (h, c) = cell_dq(x, (h, c))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\quantized\dynamic\modules\rnn.py", line 373, in forward
    return self.forward_tensor(input, hx)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\quantized\dynamic\modules\rnn.py", line 334, in forward_tensor
    input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\quantized\dynamic\modules\rnn.py", line 315, in forward_impl
    self.batch_first, dtype=self.dtype, use_dynamic=True)
RuntimeError: In ChooseQuantizationParams, min should be less than or equal to max

Traceback (most recent call last):
  File "run_test.py", line 493, in <module>
    main()
  File "run_test.py", line 486, in main
    raise RuntimeError(message)
RuntimeError: test_quantization failed!
```
Failed CI jobs:
https://app.circleci.com/jobs/github/pytorch/pytorch/4584022
https://app.circleci.com/jobs/github/pytorch/pytorch/4585793

## To Reproduce

1. python run_test.py -i quantization

## Expected behavior

Test passes.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla P4
 - Any other relevant information:

## Additional context

cc @jianyuh @shz0116

**Comment by jianyuh** [comment]
https://github.com/pytorch/pytorch/pull/33750

**Comment by jianyuh** [comment]
Tracked the issue in https://github.com/pytorch/pytorch/issues/32644.
