### ISSUE TITLE
Models saved in C++ LibTorch with torch::save, cannot be loaded in python using torch.load

### ISSUE THREAD

**Issue by JamieMair** [pytorch/pytorch#33811]
## 🐛 Bug

Models saved in C++ LibTorch with torch::save, cannot be loaded in python using torch.load. When I save a custom model (a class which inherits from torch::nn::Module) using torch::save(model, filepath), the result is a zip archive (.pt). The archive has the same structure as [it should](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/docs/serialization.md) but python comes up with the error 

## To Reproduce

1. Save a class which inherits from the torch::nn::Module class in C++ using torch::save
2. Try to load that saved archive in python using torch.load
3. Find this error below: 

`Traceback (most recent call last):
  File "torch_plotting.py", line 59, in <module>
    policy_model, value_model = load_models(containing_path, model_number)
  File "torch_plotting.py", line 37, in load_models
    policy_model = torch.load(policy_file)
  File "/home/jamie/anaconda3/envs/tensorflow/lib/python3.7/site-packages/torch/serialization.py", line 528, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/jamie/anaconda3/envs/tensorflow/lib/python3.7/site-packages/torch/serialization.py", line 782, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named '__torch__'`

## Expected behavior

Expect to have a fully loaded model that behaves the same way as the c++ one which I can use to perform inference.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 19.10
GCC version: (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
CMake version: version 3.16.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] numpydoc==0.9.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

## Additional context

I am using the libtorch provided by [this link](https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.4.0%2Bcpu.zip) and using cmake to build my project.

**Comment by agolynski** [comment]
The error seems a bit strange "ModuleNotFoundError: No module named '__torch__'". Have you tried saving/loading models from py<->py or cpp<->cpp to make sure that works for you?

**Comment by adampauls** [comment]
I'm experiencing the same issue. cpp <-> cpp works fine, but loading from python does not work. 

In __torch__.py in the saved module, I see
```class Module(Module):```

I'm pretty new to python so I don't know if the name clash is a problem. I did not provide the name `Module` (I named the module `test`), so I'm a little bit confused as to how the name became `Module`.

**Comment by adampauls** [comment]
Okay, my problem was that I was calling `torch.load` on a `torch::jit::script::Module.` `torch.jit.load` seems to work.

**Comment by JamieMair** [comment]
> The error seems a bit strange "ModuleNotFoundError: No module named '**torch**'". Have you tried saving/loading models from py<->py or cpp<->cpp to make sure that works for you?

CPP to CPP saving and loading works just fine, haven't tried with python to python but I assume that is fine.

**Comment by jianyin2016** [comment]
I met exactly the same issue earlier, right, libtorch is still in beta.

**Comment by saw-ai** [comment]
The same issue

**Comment by glaringlee** [comment]
@saw-ai @JamieMair @jianyin2016 
For pytorch 1.4, please follow use pickle_save under libtorch, for eg.
torch::Tensor x = torch::ones({1, 2, 3});
std::vector<char> f = torch::pickle_save(x);

And you can use torch.load under python side.

In 1.5 and later, you can use save directly. Please be aware that 1.4 saved module might not be able to load under 1.5.

**Comment by FuryBaM** [comment]
I did it!

```cpp
    void save_weights(const std::string& path) {
        std::ofstream file(path, std::ios::binary);
		to(torch::kCPU);
		for (const auto& param : parameters()) {
			auto data = param.data().contiguous(); // Tensor
			auto size = data.numel(); // int64_t
            file.write(reinterpret_cast<const char*>(&size), sizeof(size));
            file.write(reinterpret_cast<const char*>(data.data_ptr<float>()), size * sizeof(float));
		}
        file.close();
	}

    void load_weights(const std::string& path) {
        std::ifstream file(path, std::ios::binary);
        if (!file) {
            throw std::runtime_error("Failed to open file for reading: " + path);
        }

        for (auto& param : parameters()) {
            int64_t size;
            if (!file.read(reinterpret_cast<char*>(&size), sizeof(size))) {
                throw std::runtime_error("Failed to read size of parameter.");
            }

            if (size == 0) {
                throw std::runtime_error("Invalid parameter size read from file.");
            }

            std::vector<float> param_data(size);
            if (!file.read(reinterpret_cast<char*>(param_data.data()), size * sizeof(float))) {
                throw std::runtime_error("Failed to read parameter data.");
            }

            param.data().copy_(torch::tensor(param_data).view_as(param));
        }

        file.close();
    }
```

```python
    def save_binary_weights(self, path):
        with open(path, "wb") as file:
            for param in self.parameters():
                data = param.data.contiguous().cpu().view(-1).numpy().astype("float32")
                size = len(data)
                file.write(struct.pack('Q', size))
                file.write(struct.pack(f'{size}f', *data))
    
    def load_binary_weights(self, path: str):
        with open(path, "rb") as file:
            for param in self.parameters():
                size = struct.unpack('Q', file.read(8))[0]
                param_data = struct.unpack(f'{size}f', file.read(size * 4))
                param.data.copy_(torch.tensor(param_data).view_as(param))
```
`
