### ISSUE TITLE
Wrong error is raised for property of nn.Module

### ISSUE THREAD

**Issue by mpariente** [pytorch/pytorch#33934]
## 🐛 Bug

When there `__getattr__` raises an error inside a property in nn.Module, it's on the property itself, not on the attribute that caused the error.

## To Reproduce
Here is a small script to reproduce the issue.
```python
from torch import nn


class MyModule(nn.Module):
    @property
    def something(self):
        hey = self.unknown_function()
        return hey


model = MyModule()
print(model.something)


```
This raises `AttributeError: 'MyModule' object has no attribute 'something'`

## Expected behavior

I'd expect this to be raised `AttributeError: 'MyModule' object has no attribute 'unknown_function'`. This is the case if `something` is a function instead of a property.

**Comment by ezyang** [comment]
For comparison:

```
tanmayshankar-ubuntu-r90qrw28:~ ezyang$ python arf.py 
Traceback (most recent call last):
  File "arf.py", line 9, in <module>
    print(model.something)
  File "arf.py", line 4, in something
    hey = self.unknown_function()
AttributeError: MyModule instance has no attribute 'unknown_function'
tanmayshankar-ubuntu-r90qrw28:~ ezyang$ cat arf.py
class MyModule:
    @property
    def something(self):
        hey = self.unknown_function()
        return hey


model = MyModule()
print(model.something)
```

**Comment by mpariente** [comment]
Should I try to fix it? I can give it a try.

**Comment by ezyang** [comment]
@mpariente Sure! It probably has to do with the fact that we define `__getattr__` and `__setattr__` on `Module` base class.

**Comment by mpariente** [comment]
It actually is more complicated than I thought and it's a common issue. 
It turns out that `property` directly calls `getattr` and doesn't go through `__getattribute__` so if an error occurs in a property and `__getattr__` is overwritten by the class, this type of misleading error will appear.

See [this](https://github.com/encode/django-rest-framework/pull/2530/files#diff-6dc9b019ec1d96c56e0e31dac3bba51cL488) for example.

For example, this already breaks 
```python
class MyObject(object):
    @property
    def something(self):
        hey = self.unknown_function()
        return hey

    def __getattr__(self, name):
        raise AttributeError("'{}' object has no attribute '{}'".format(
            type(self).__name__, name))


model = MyObject()
print(model.something)
```

**Comment by mpariente** [comment]
The only way I can make it work is by having the old `__getattr__` code inside the `__getattribute__` so that `name` is not lost during the error.

```patch
--- torch/nn/modules/module.py	(revision 2b79bab029ec387618f6b9724a4027b81fbda33c)
+++ torch/nn/modules/module.py	(date 1583446218560)
@@ -577,21 +577,24 @@
         if '_load_state_dict_pre_hooks' not in self.__dict__:
             self._load_state_dict_pre_hooks = OrderedDict()
 
-    def __getattr__(self, name):
-        if '_parameters' in self.__dict__:
-            _parameters = self.__dict__['_parameters']
-            if name in _parameters:
-                return _parameters[name]
-        if '_buffers' in self.__dict__:
-            _buffers = self.__dict__['_buffers']
-            if name in _buffers:
-                return _buffers[name]
-        if '_modules' in self.__dict__:
-            modules = self.__dict__['_modules']
-            if name in modules:
-                return modules[name]
-        raise AttributeError("'{}' object has no attribute '{}'".format(
-            type(self).__name__, name))
+    def __getattribute__(self, name):
+        try:
+            return super(Module, self).__getattribute__(name)
+        except AttributeError as err:
+            if '_parameters' in self.__dict__:
+                _parameters = self.__dict__['_parameters']
+                if name in _parameters:
+                    return _parameters[name]
+            if '_buffers' in self.__dict__:
+                _buffers = self.__dict__['_buffers']
+                if name in _buffers:
+                    return _buffers[name]
+            if '_modules' in self.__dict__:
+                modules = self.__dict__['_modules']
+                if name in modules:
+                    return modules[name]
+            raise AttributeError("'{}' object has no attribute '{}'".format(
+                type(self).__name__, name))
 
     def __setattr__(self, name, value):
         def remove_from(*dicts):
```


If there is no `__getattr__` method in `nn.Module`, it will never be called. So the code is intent of the code is even clearer in this way IMO.
