### ISSUE TITLE
Wrong error is raised when RPC APIs deal with sparse tensor

### ISSUE THREAD

**Issue by doudoubobo** [pytorch/pytorch#33939]
## 🐛 Bug

When RPC APIs deal with sparse tensor, a wrong error is raised.

## To Reproduce

Here is a small script to reproduce the issue.
```python
import multiprocessing as mp
import torch
from torch.distributed import rpc
import os

def my_mm(a, b):
    return torch.mm(a, b)

def my_spmm(a, b):
    return torch.spmm(a, b)

def _run_process(rank, world_size):
    name = "worker{}".format(rank)
    # Initialize RPC.
    rpc.init_rpc(name=name,rank=rank,world_size=world_size)
    if rank == 0:
        i = torch.LongTensor([[0, 1, 1],[2, 0, 2]])
        v = torch.FloatTensor([3, 4, 5])
        t1 = torch.sparse.FloatTensor(i, v, torch.Size([2,3]))
        t2 = torch.Tensor([[1,4],[7,9],[6,3]])
        result1 = rpc.rpc_async("worker1", my_mm, args=(t1.to_dense(), t2))
        print (result1.wait())
        result2 = rpc.rpc_async("worker1", my_spmm, args=(t1, t2))
        print (result2.wait())

def run_process(rank, world_size):
    _run_process(rank, world_size)
    rpc.shutdown()

processes = []
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '29500'
# Run world_size workers.
world_size = 2
for i in range(world_size):
    p = mp.Process(target=run_process, args=(i, world_size))
    p.start()
    processes.append(p)

for p in processes:
    p.join()
```

## Environment
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.0
 
## Expected behavior
`result1` should be equal to `result2`

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @vincentqb

**Comment by mrshenli** [comment]
@doudoubobo thanks for reporting. I can reproduce this issue, and the error is as following:

```
tensor([[18.,  9.],
        [34., 31.]])
Process Process-1:
Traceback (most recent call last):
  File "/home/shenli/local/miniconda/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                                                  
    self.run()
  File "/home/shenli/local/miniconda/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 99, in run                                                          
    self._target(*self._args, **self._kwargs)
  File "test.py", line 27, in run_process
    _run_process(rank, world_size)
  File "test.py", line 24, in _run_process
    print (result2.wait())
RuntimeError: Encountered exception in ProcessGroupAgent::enqueueSend: sparse tensors do not have storage (storage at ../aten/src/ATen/SparseTensorImpl.cpp:77)       
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7ff3855759e6 in /data/users/shenli/pytorch/torch/lib/libc10.so)                        
frame #1: at::SparseTensorImpl::storage() const + 0xae (0x7ff3984e0cfe in /data/users/shenli/pytorch/torch/lib/libtorch_cpu.so)                                       
frame #2: torch::distributed::rpc::cloneSparseTensors(std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x96 (0x7ff39abee1a6 in /data/users/shenli/pytorch/torch/lib/libtorch_cpu.so)
frame #3: torch::distributed::rpc::wireSerialize(std::vector<char, std::allocator<char> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x3cd
(0x7ff39abef50d in /data/users/shenli/pytorch/torch/lib/libtorch_cpu.so)
frame #4: torch::distributed::rpc::ProcessGroupAgent::handleSend(torch::distributed::rpc::SendWork const&) + 0x47 (0x7ff39da83ee7 in /data/users/shenli/pytorch/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x8b485d (0x7ff39da8485d in /data/users/shenli/pytorch/torch/lib/libtorch_python.so)                                                   
frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x23b (0x7ff3855718db in /data/users/shenli/pytorch/torch/lib/libc10.so)                                        
frame #7: <unknown function> + 0xc819d (0x7ff39f41419d in /data/users/shenli/miniconda/envs/pytorch/bin/../lib/libstdc++.so.6)                                        
frame #8: <unknown function> + 0x7dd5 (0x7ff3cee58dd5 in /lib64/libpthread.so.0)
frame #9: clone + 0x6d (0x7ff3ceb81ead in /lib64/libc.so.6)
```

**Comment by jjlilley** [comment]
@mrshenli  So, the issue is that JIT Pickler doesn't yet support pickling sparse tensors. Not sure where this is on their priority list.
 - Ideally, once this happens, this would just work.
 - Though, we have to also add a !has_storage() check in this file first
 - We could un-sparseify the tensors automatically, but that could be quite slow - not sure if that's what we really want? Maybe defer to users for now?

**Comment by jjlilley** [comment]
https://github.com/pytorch/pytorch/pull/34626 will add the has_storage() check.

**Comment by mrshenli** [comment]
> We could un-sparseify the tensors automatically, but that could be quite slow - not sure if that's what we really want? Maybe defer to users for now?

Yep, deferring it + good error message sound good to me.
