### ISSUE TITLE
Handle infinity in Variables without error

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#3397]
`Tensor.sum()` behaves as expected; `Variable.sum()` raises an overflow error:
```py
torch.Tensor([float('inf')]).sum()
# inf

torch.autograd.Variable(torch.Tensor([float('inf')])).sum()
# RuntimeError: value cannot be converted to type double without overflow: inf

print(torch.__version__)
# 0.2.0+c10898f
```

**Comment by fritzo** [comment]
This is still broken as of 66d24c50671fa
```py
>>> torch.autograd.Variable(torch.Tensor([float('inf')])).sum()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: value cannot be converted to type double without overflow: inf
>>> torch.__version__
'0.2.0+66d24c5'
```

**Comment by colesbury** [comment]
We need to merge ATen back into PyTorch

**Comment by qipeng** [comment]
It seems this is broken again on tags/v0.3.0
```
torch.autograd.Variable(torch.Tensor([float('inf')])).sum()
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# RuntimeError: value cannot be converted to type double without overflow: inf
print(torch.__version__)
# 0.3.0b0+af3964a
```
