### ISSUE TITLE
max_pool2d doesn't check if input is contiguous: max_pool2d_with_indices_out_cuda_frame failed with error code 0 with specific inputs

### ISSUE THREAD

**Issue by fanbeatsman** [pytorch/pytorch#33988]
## 🐛 Bug

I have a specific tensor that crashes `torch.max_pool2d`. Curiously if I copy the values themselves into a fresh Tensor with all the attributes set to be the same as the problematic tensor, it works.

## To Reproduce
Download my problematic tensor here https://github.com/fanbeatsman/pytorchBug and run the following script.

```
import torch
import torch.nn as nn
problem_tensor = torch.load("tensorProblem.pt")
max_pooled = torch.max_pool2d(problem_tensor, 2, 2, 0, 1, False)
```
`RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0`

## Environment
PyTorch version: 1.5.0.dev20200213
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.15.5

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-DGXS-32GB
GPU 1: Tesla V100-DGXS-32GB
GPU 2: Tesla V100-DGXS-32GB
GPU 3: Tesla V100-DGXS-32GB

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torchvision==0.6.0.dev20200214
[conda] Could not collect

## Additional context
For some reason, if I run the following code instead, it works. It feels like the Tensor object of problem_tensor is corrupted even if all properties of both tmp and problem_tensor look the same.

```
import torch
import torch.nn as nn
problem_tensor = torch.load("tensorProblem.pt")
tmp = torch.zeros(problem_tensor.size())
tmp[:,:,:,:] = problem_tensor[:,:,:,:]
max_pooled = torch.max_pool2d(tmp, 2, 2, 0, 1, False)
```
`Ok`

The origins of where I got my problematic tensor was an intermediate activation of running the pretrained VGG16 network from the Pytorch network zoo.

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ptrblck** [comment]
Thanks for the report @fanbeatsman!

It seems the error is thrown, as `problemTensor` is not contiguous, as can be seen by the strides.
Calling `problem_tensor = problem_tensor.contiguous()` solves the issue.

@xwang233 will have a look at it.

**Comment by fanbeatsman** [comment]
@ptrblck Thanks for such a fast response. I think i see my problem. I called view to preprocess my data and didn't know it doesn't actually change the underlying content when feeding into VGG. Is there an API call that does what `view()` does but that actually changes the content? Or do I have to do something lie `view().contigous()`?

**Comment by ezyang** [comment]
Adding the contiguity check (or just running `.contiguous()` on the input) should be easy to do

**Comment by ezyang** [comment]
cuda kernel crash marking high priority

**Comment by xwang233** [comment]
This problem is similar to #34083. A fix will be provided. 

The `problem_tensor` has a size of (1, 256, 32, 32). The requested shared memory size per block is 64 kb, which is greater than the 48 kb limit.

**Comment by CarlBhy** [comment]
i meet this question when i install python 3.7 and i try to add the ".contiguous",but it didnt work 
`Traceback (most recent call last):
  File "tools/train_net.py", line 201, in <module>
    main()
  File "tools/train_net.py", line 194, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 94, in train
    arguments,
  File "/home/sc/carl_test/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 84, in do_train
    loss_dict = model(images, targets)
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/sc/carl_test/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    features = self.backbone(images.tensors)
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sc/carl_test/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 72, in forward
    last_results = self.top_blocks(results[-1])
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sc/carl_test/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 81, in forward
    return [F.max_pool2d(x, 1, 2, 0)]
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/_jit_internal.py", line 181, in fn
    return if_false(*args, **kwargs)
  File "/home/sc/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/functional.py", line 488, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0
`
