### ISSUE TITLE
JIT: Hidden tensors aren't changing device correctly with traced RNNs

### ISSUE THREAD

**Issue by ksanjeevan** [pytorch/pytorch#34256]
## 🐛 Bug
Chaning deviced of traced RNNs doesn't correctly move the hidden tensors which results in device errors at inference.

## To Reproduce
```python
import torch
import torch.nn as nn

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, 5)
        self.conv2 = nn.Conv2d(16, 16, 5)

        self.rnn = nn.LSTM(512, 64, 2, batch_first=True)
        self.lin = nn.Linear(64, 2)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.transpose(1, -1)
        x = x.reshape(x.size(0), x.size(1), -1)

        x, _ = self.rnn(x)
        x = x[:, -1]

        return self.lin(x)

x = torch.randn(16, 1, 40, 40).cuda()
m = Net().cuda()

traced_m = torch.jit.trace(m, x)

traced_m.save('model_gpu.pt')


xcpu = torch.randn(16, 1, 40, 40)
cpu_model = torch.jit.load('model_gpu.pt', map_location=torch.device('cpu'))

print( cpu_model(xcpu) )
```

Will give:
```
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cpu and hidden tensor at cuda:0
The above operation failed in interpreter.
Traceback (most recent call last):
Serialized   File "code/__torch__/torch/nn/modules/module/___torch_mangle_3.py", line 18
    _4 = ops.prim.NumToTensor(torch.size(x, 1))
    orig_input = torch.reshape(x, [int(_3), int(_4), -1])
    _5 = torch.slice((_1).forward(orig_input, ), 0, 0, 9223372036854775807, 1)
                      ~~~~~~~~~~~ <--- HERE
    input0 = torch.select(_5, 1, -1)
    return (_0).forward(input0, )
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py(559): forward
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
problem.py(21): forward
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py(1034): trace_module
/home/kiran/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py(882): trace
problem.py(29): <module>
Serialized   File "code/__torch__/torch/nn/modules/module/___torch_mangle_1.py", line 25, in forward
    max_batch_size = ops.prim.NumToTensor(torch.size(orig_input, 0))
    hx = torch.zeros([2, int(max_batch_size), 64], dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False)
    x, _8, _9 = torch.lstm(orig_input, [hx, hx], [_7, _6, _5, _4, _3, _2, _1, _0], True, 2, 0., True, False, True)
                ~~~~~~~~~~ <--- HERE
    return x
```
## Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchaudio==0.4.0a0+719bcc7
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchaudio                0.4.0                      py36    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

cc @suo

**Comment by ksanjeevan** [comment]
Hey @suo, do you know if this is reproducible or maybe an issue only I'm having?

**Comment by ksanjeevan** [comment]
@VitalyFedyunin , @suo, wondering if this is reproducible or is the API not expected to move JIT models across devices? Thanks.

**Comment by ksanjeevan** [comment]
solved it with https://github.com/pytorch/pytorch/issues/15272. Was confused since the torchscript doc didn't call out RNNs specifically causing this issue.
