### ISSUE TITLE
DISABLED test_backward_simple_script_call (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#34264]
Test is flaky

https://app.circleci.com/jobs/github/pytorch/pytorch/4694579

```
Mar 04 21:35:48 Traceback (most recent call last):
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 04 21:35:48     self.run()
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 04 21:35:48     self._target(*self._args, **self._kwargs)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 243, in _run
Mar 04 21:35:48     getattr(self, test_name)()
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 68, in new_test_method
Mar 04 21:35:48     return_value = old_test_method(self, *arg, **kwargs)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1296, in test_backward_simple_script_call
Mar 04 21:35:48     forward_ret = self._exec_func(exec_mode, my_script_add, t1, t2)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 192, in _exec_func
Mar 04 21:35:48     "worker{}".format(self._next_rank()), method, args=(args)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 21:35:48     return func(*args, **kwargs)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 526, in rpc_sync
Mar 04 21:35:48     return fut.wait()
Mar 04 21:35:48 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
Mar 04 21:35:48 Process process 0:
Mar 04 21:35:48 Traceback (most recent call last):
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 04 21:35:48     self.run()
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 04 21:35:48     self._target(*self._args, **self._kwargs)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 243, in _run
Mar 04 21:35:48     getattr(self, test_name)()
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 68, in new_test_method
Mar 04 21:35:48     return_value = old_test_method(self, *arg, **kwargs)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1296, in test_backward_simple_script_call
Mar 04 21:35:48     forward_ret = self._exec_func(exec_mode, my_script_add, t1, t2)
Mar 04 21:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 202, in _exec_func
Mar 04 21:35:48     return fut.wait()
Mar 04 21:35:48 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
Mar 04 21:35:48 terminate called after throwing an instance of 'std::runtime_error'
Mar 04 21:35:48   what():  RPC ran for more than 60000 milliseconds and timed out.
Mar 04 21:37:51 E...........Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:675)
Mar 04 21:37:51 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:675)
Mar 04 21:37:51 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:675)
Mar 04 21:37:51 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:675)
Mar 04 21:37:52 .[E request_callback.cpp:39] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 04 21:37:52 [E request_callback.cpp:39] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 04 21:37:52 [E request_callback.cpp:39] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 04 21:37:52 [E request_callback.cpp:39] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 04 21:38:18 ......................
Mar 04 21:38:18 ======================================================================
Mar 04 21:38:18 ERROR [161.083s]: test_backward_simple_script_call (__main__.DistAutogradTestWithSpawn)
Mar 04 21:38:18 ----------------------------------------------------------------------
Mar 04 21:38:18 Traceback (most recent call last):
Mar 04 21:38:18   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Mar 04 21:38:18     self._join_processes(fn)
Mar 04 21:38:18   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in _join_processes
Mar 04 21:38:18     self._check_return_codes(elapsed_time)
Mar 04 21:38:18   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 275, in _check_return_codes
Mar 04 21:38:18     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Mar 04 21:38:18 RuntimeError: Process 2 terminated or timed out after 161.0687735080719 seconds
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by zhaojuanmao** [comment]
GIL change in #33329 could cause deadlock
