### ISSUE TITLE
torch.cat does not call __torch_function__ properly

### ISSUE THREAD

**Issue by wazizian** [pytorch/pytorch#34294]
## 🐛 Bug

```torch.cat``` (and ```torch.stack```) do not call ```__torch_function__``` properly on non ```Tensor``` objects. The first argument of ```torch.cat``` is supposed to be a sequence of tensors, but it seems to look for a ```__torch_function__``` method on the sequence object and not the individual elements of the sequence.

## To Reproduce

Consider the following class,
```
class TensorLike:
    def __torch_function__(func, args=(), kwargs=None):
        print("{} call to __torch_function__ of TensorLike".format(func))
```
This works properly on most functions such as,
```
>>> torch.add(TensorLike(), 1)
<__main__.TensorLike object at 0x7fec113f7d50> call to __torch_function__ of TensorLike
```
However, on ```torch.cat```
```
>>> torch.cat((TensorLike(), TensorLike()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected Tensor as element 0 in argument 0, but got TensorLike

>>> torch.cat((TensorLike(),))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected Tensor as element 0 in argument 0, but got TensorLike

>>> torch.cat(TensorLike())
<__main__.TensorLike object at 0x7fec113f7d50> call to __torch_function__ of TensorLike

```

## Expected behavior

Doing ```torch.cat((TensorLike(), TensorLike()))``` or ```torch.cat((TensorLike(),))``` should call the ```__torch_function__``` of  ```TensorLike``` as described [here](https://pytorch.org/docs/master/notes/extending.html#operations-on-multiple-types-that-define-torch-function). Moreover, ```torch.cat(TensorLike())``` should fail as ```torch.cat``` expects a sequence as its first argument.

It seems that for ```torch.cat```, ```_get_overloaded_args``` in ```torch/_overrides.py``` should ensure the first argument is a sequence and look for a ```__torch_function__``` on the elements of this sequence.

## Environment

Collecting environment information...
PyTorch version: 1.5.0.dev20200304
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0.dev20200304
[conda] torch 
 
## Additional context

The override for ```torch.cat``` is tested in ```test/test_overrides.py``` but I think the wrong signature is used for testing. Indeed, ``` generate_tensor_like_override_tests``` [here](https://github.com/pytorch/pytorch/blob/ac6e75a1651cd14cec7f2f41b2c7b9ec7dcb3ecf/test/test_overrides.py#L1066) calls ```torch.cat``` with ```TensorLike()``` as first argument instead of sequence of such objects.
A heuristic to remedy this would be to pass a sequence of ```TensorLike``` if the argument is named ```tensors```.

Please let me know if I can help,

Cheers,

Waïss

**Comment by yf225** [comment]
I am putting `numpy` tag on this issue, because it can be related to the workstream at https://github.com/pytorch/rfcs/pull/3.

**Comment by rgommers** [comment]
The signature in the test is `tensors, dim=0, out=None` which seems right, but construction of `func_args` in `generate_tensor_like_override_tests` may indeed generate the wrong thing it seems (since `nargs==1` here).

Cc @ngoldbaum, @hameerabbasi

**Comment by wazizian** [comment]
Indeed, ```func_args``` is built as ```[TensorLike()]```, while it should be something like ```[(TensorLike(), TensorLike())]```, shouldn't it?
If it helps, I can try to fix the tests and do a PR, please let me know.

**Comment by ngoldbaum** [comment]
I'm looking at it right now.

The heuristics used in the `TensorLike` tests to generate arguments aren't very sophisticated. Right now they ignore keyword arguments, for example.

**Comment by ngoldbaum** [comment]
Hmm, this is a little bit more complicated actually because `torch.cat` isn't implemented in Python, so this is an issue with the C++ argument parsing. `torch.cat` doesn't go through the python `_get_overloaded_args` function as suggested in the issue.

**Comment by wazizian** [comment]
As a comparison, here is the doc explaining how ```numpy``` deals with the dispatch for the concatenation function:
[https://numpy.org/neps/nep-0018-array-function-protocol.html#finding-arguments](https://numpy.org/neps/nep-0018-array-function-protocol.html#finding-arguments)

**Comment by ngoldbaum** [comment]
It looks like we just never added support for `__torch_function__` in `PythonArgs::tensorlist` or `PythonArgs::tensorlist_n`, see e.g.:

https://github.com/pytorch/pytorch/blob/b1bd950a4d3a06b4e105cb77238fb7df01fad4da/torch/csrc/utils/python_arg_parser.h#L271-L273

This just calls `THPVariable_Check`, which doesn't have any checking for `__torch_function__`.

The fix is to replace the call to `THPVariable_Check` with a set of statements that is similar to the usage of `THPVariable_CheckExact` and `THPVariable_Check` inside of `FunctionParameter::check`:

https://github.com/pytorch/pytorch/blob/b1bd950a4d3a06b4e105cb77238fb7df01fad4da/torch/csrc/utils/python_arg_parser.cpp#L244-L251

I'll see if it makes sense to refactor the C++ `__torch_function__` handling code into a helper function and then use that helper function in `PythonArgs::tensorlist` and `PythonArgs::tensorlist_n`.

**Comment by ezyang** [comment]
btw @wazizian, what are you using `__torch_function__` for, if I may ask :)

**Comment by ngoldbaum** [comment]
On further reflection, this is a little more tricky than I thought.

To ground this discussion, here's what `cat` looks like in the generated version of `python_torch_functions.cpp`:

https://gist.github.com/ngoldbaum/b44f7711e61d3adb3f801e62354f3767

My earlier suggestion could work, but it will require a more extensive refactor than I anticipated. Basically, right now `tensorlist` and `tensorlist_n` don't have a way to signal to the caller that the caller needs to handle calling `__torch_function__`. We'd also probably need to change the codegen to support this change, e.g. by adding handling for early returning the result of calling `__torch_function__` between line 19 and 20 in the gist.

It would be much nicer if we could forego all that and use the existing `__torch_function__` handling code on line 11-13 of the gist. The problem there is that right now `TensorList` arguments completely bypass the handling we added to the argument parser for `__torch_function__`-implementing operands. Right now, for `TensorList` operands like `cat` takes, all the argument parser does is check that the argument is a tuple or list:

https://github.com/pytorch/pytorch/blob/cb689a5d68a9c4c203f0d3dffbb1ef2cb7d2a506/torch/csrc/utils/python_arg_parser.cpp#L289

So I think the clearest way forward is to expand the above switch case for `ParameterType::TENSOR_LIST` to scan over the elements of the list or tuple, check if they are either a tensor or have a `__torch_function__` attribute, probably re-using the code from the `ParameterType::TENSOR` case.

The problem with this is that it introduces runtime cost. I can partially ameliorate that cost by removing the call to `THPVariable_Check` from `PythonArgs::tensorlist` when it scans over the list, but we would still need to iterate over the input list or tuple twice whereas right now we're only iterating over it once inside of `PythonArgs::tensorlist`.

Do you have any thoughts on this @ezyang? Is it ok to incur a little extra runtime cost here? Also pinging @rgommers and @hameerabbasi.

This is getting a little in the weeds so I'm happy to hop on a video chat if that would help to clarify things quickly. For now, unless I hear differently, I'm going to try to implement my approach as outlined here so we can run some benchmarks and see if the extra cost is significant.

**Comment by ezyang** [comment]
I believe I understand the problem. The fact that this is an issue suggests that we implemented things incorrectly in the first place; that is to say, we put the `has_torch_function` test too early. Here's an alternative codegen for this function:

```
static PyObject * THPVariable__cat(PyObject* self_, PyObject* args, PyObject* kwargs)
{
  HANDLE_TH_ERRORS
  static PythonArgParser parser({
    "_cat(TensorList tensors, int64_t dim=0, *, Tensor out=None)",
  }, /*traceable=*/true);

  ParsedArgs<3> parsed_args;
  auto _r = parser.parse(args, kwargs, parsed_args);
  if (_r.isNone(2)) {
    // aten::_cat(Tensor[] tensors, int dim=0) -> Tensor
    auto predispatch__cat = [](TensorList tensors, int64_t dim) -> Tensor {
      if(_r.has_torch_function()) {
        return handle_torch_function(_r, args, kwargs, THPVariableFunctionsModule, "torch");
      }
      return wrap(dispatch__cat(tensors, dim));
    };
    auto dispatch__cat = [](TensorList tensors, int64_t dim) -> Tensor {
      pybind11::gil_scoped_release no_gil;
      return at::_cat(tensors, dim);
    };
    return predispatch__cat(_r.tensorlist(0), _r.toInt64(1));
  } else {
    // ... similar ...
  }
  Py_RETURN_NONE;
  END_HANDLE_TH_ERRORS
}
```

The idea is to not do the `has_torch_function` test until after we've extracted the arguments. At this point, we have gone over all the tensor list arguments and so we know if any of them weren't exactly tensors.

The downside to this is we are now "wastefully" unpacking all of the Python arguments into C++ types, only to discover this was all wasted work (because something was a `__torch_function__`, and so now we should throw this work out and directly redispatch using the given PyObject argument objects.

----

For now I would go ahead with your suggested modification, let's check the performance implication. One benefit of iterating at the `check()` phase is it means we can now distinguish overloads between integers and tensor lists (right now, this is not supported, because we only poke at the top level.)

**Comment by wazizian** [comment]
You're welcome to ask, @ezyang :)
We are working with graph neural networks, and we use masks to manipulate batches of graphs of different sizes. To separate this logic from the models, we are experimenting with a tensor-like class which takes care of masking, and we rely on ```__torch_function__``` to make it compatible with some of the ```torch``` functions. (The code is [here](https://github.com/wazizian/graph_neural_net/tree/mixed_batches/toolbox).)

**Comment by ezyang** [comment]
^- @cpuhrsch, may be of interest to you.

**Comment by cpuhrsch** [comment]
@wazizian - as an obligatory pluck for [nestedtensor](https://github.com/pytorch/nestedtensor). [MaskedTensor](https://github.com/wazizian/graph_neural_net/blob/mixed_batches/toolbox/maskedtensor.py#L50) seems quite similar in goal as what NestedTensor is trying to achieve. If I'm not mistaken you're taking the approach of [matchbox](https://github.com/salesforce/matchbox).

**Comment by wazizian** [comment]
Indeed, but we preferred to keep using batched operations (unlike NestedTensor, if I'm not mistaken). However I didn't know about matchedtensor and I'll definitely take a look at it! Thank you for the suggestion :-)

**Comment by GFabien** [comment]
Hi! Any update on this issue? I am investigating a way to create a Keras-like summary function from [pytorch-summary](https://github.com/sksq96/pytorch-summary) including the "connected to" field using a forward pass with tensor-like objects containing additional metadata following [this](https://pytorch.org/docs/stable/notes/extending.html#extending-torch-with-a-tensor-wrapper-type) implementation. <br>
However, it breaks when going through a torch.cat operation or going through some layers like BatchNorm. For my use case, a workaround using forward_pre_hooks takes care of layers like BatchNorm but not torch.cat operations as no hooks can be set on them. One could encapsulate these operations in layers but it would require to change the networks which is not practical. <br>
Thanks for your help!

**Comment by GFabien** [comment]
Ok, thank you. Good luck!

**Comment by ezyang** [comment]
@hameerabbasi If it's just tests holding up the issue, maybe we should just manually test cat :) BTW, the in progress PR to fix is https://github.com/pytorch/pytorch/pull/34725 It looks like it's been a month, does there need to be some unblocking here?

**Comment by hameerabbasi** [comment]
@ezyang I’ve been prioritising PyTorch/rfcs#3 over it. I just opened #37091. 

I could remove the automatic test gen from #34725 if you like.

**Comment by ezyang** [comment]
No that's OK, I just wanted to make sure you weren't blocked on something that doesn't seem like a real blocker. #37091 seems like a good reason to not be making progress on this.

**Comment by cpuhrsch** [comment]
Are there any workarounds for this yet?

**Comment by rgommers** [comment]
@cpuhrsch there aren't. The (WIP) open PR for this updates the C++ argument parser to handle list of Tensor, which is the right way to do it but nontrivial. `cat` is all C++; a stopgap would be to add a thin Python layer to it (similar to, e.g., `broadcast_tensors`), but that would of course add function call overhead so I expect that's not acceptable to put into master.

You could probably fairly easily monkeypatch this though, if that's acceptable for you as a workaround. Something like:
```
from torch._overrides import has_torch_function, handle_torch_function

original_cat = torch.cat


def cat(tensors, dim=0, out=None) -> Tensor:
    if not torch.jit.is_scripting():
        if any(type(t) is not Tensor for t in tensors) and has_torch_function(tensors):
            return handle_torch_function(cat, tensors, *tensors, dim=dim, out=out)
    return original_cat(tensors, dim=dim, out=out)


torch.cat = cat
```

**Comment by jeffreysijuntan** [comment]
I was also having this issue and tried the monkey-patch approach. It works for most of the cases. But when I was testing with a `torchvision.models`, there is one line that has the `@torch.jit.script` and invoke JIT for my custom `cat` function. I got error because of it.  My custom cat function is declared as follows:

```
@staticmethod
    def cat(tensors, dim=0, out=None):
        if not torch.jit.is_scripting():
            is_cuda_long = any(hasattr(t, "tensor") for t in tensors)
            tensors = [t.tensor() if hasattr(t, "tensor") else t for t in tensors]
            if is_cuda_long:
                return CUDALongTensor(torch_cat(tensors, dim=dim, out=out))
        return torch_cat(tensors, dim=dim)
```

The error message is as follows:
```
> RuntimeError:
> Arguments for call are not valid.
> The following variants are available:
>
>   aten::cat(Tensor[] tensors, int dim=0) -> (Tensor):
>   Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'Tensor (inferred)'.
>   Inferred the value for argument 'tensors' to be of type 'Tensor' because it was not annotated with an explicit type.
>
>   aten::cat.names(Tensor[] tensors, str dim) -> (Tensor):
>   Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'Tensor (inferred)'.
>   Inferred the value for argument 'tensors' to be of type 'Tensor' because it was not annotated with an explicit type.
>
>   aten::cat.names_out(Tensor[] tensors, str dim, *, Tensor(a!) out) -> (Tensor(a!)):
>   Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'Tensor (inferred)'.
>   Inferred the value for argument 'tensors' to be of type 'Tensor' because it was not annotated with an explicit type.
>
>   aten::cat.out(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> (Tensor(a!)):
>   Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'Tensor (inferred)'.
>   Inferred the value for argument 'tensors' to be of type 'Tensor' because it was not annotated with an explicit type.
>
> The original call is:
>   File "/data/users/sijun/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/crypten/examples/tfe_benchmarks#link-tree/crypten/cuda/cuda_tensor.py", line 206
>             # if is_cuda_long:
>             #     return CUDALongTensor(torch_cat(tensors, dim=dim, out=out))
>         return torch_cat(tensors, dim=dim)
>                ~~~~~~~~~ <--- HERE
> 'cat' is being compiled since it was called from 'encode_boxes'
>   File "/data/users/sijun/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/crypten/examples/tfe_benchmarks#link-tree/torchvision/models/detection/_utils.py", line 124
>     targets_dh = wh * torch.log(gt_heights / ex_heights)
>
>     targets = torch.cat((targets_dx, targets_dy, targets_dw, targets_dh), dim=1)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>     return targets
>
```

Are there any ways I can write my code to pass the JIT compilation while maintaining the same functionality? Thanks!

**Comment by jeffreysijuntan** [comment]
Also, is there a timeline for fixing this issue?

**Comment by ezyang** [comment]
@hameerabbasi is looking into it! We have a mostly complete PR that just needs some extra work at https://github.com/pytorch/pytorch/pull/34725

**Comment by jeffreysijuntan** [comment]
Great! Can't wait for the PR to land.
