### ISSUE TITLE
can't scripting ModuleList

### ISSUE THREAD

**Issue by amberhappy** [pytorch/pytorch#34302]
I can't scripting nn.MouleList, and more qustion about idex the modulelist.
When I run code like this:
```
class Sub(torch.nn.Module):
    def __init__(self, i):
        super(Sub, self).__init__()
        self.i = i
    def forward(self, thing):
        return thing - self.i
    
class M(torch.nn.Module):
    __constants__ = ['mods']
    def __init__(self):
        super(M, self).__init__()
        self.mods = nn.ModuleList([Sub(i) for i in range(10)])
    def forward(self, v):
        v = self.mods[4].forward(v)
        v = self.mods[-1].forward(v)
        v = self.mods[-9].forward(v)
        return v
    
traced_model = torch.jit.script(M())
```
then erros occurs:
```
Traceback (most recent call last):
  File "/home/luqian/work/nnUnet-station/list_script.py", line 25, in <module>
    traced_model = torch.jit.script(M())
  File "/home/luqian/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1162, in script
    return _convert_to_script_module(obj)
  File "/home/luqian/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1812, in _convert_to_script_module
    return WeakScriptModuleProxy(mod, stubs)
  File "/home/luqian/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/luqian/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1710, in __init__
    ScriptModule.__setattr__(self, name, getattr(original, name))
  File "/home/luqian/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1596, in __setattr__
    raise RuntimeError("attempting to re-assign constant '{}' in {}".format(attr, type(self).__name__))
RuntimeError: attempting to re-assign constant 'mods' in WeakScriptModuleProxy
```
Thanks!

cc @suo

**Comment by driazati** [comment]
This should be supported now with #29236, it looks like you're on a very old version of PyTorch (you can check with `print(torch.__version__)`. For you to get the fix, you'll have to use the nightly version of PyTorch (version should be 1.5 or greater). Closing since this should be fixed, please re-open if you have any problems
