### ISSUE TITLE
DISABLED test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#34432]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/20231//console

```
22:09:03 ======================================================================
22:09:03 FAIL: test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)
22:09:03 ----------------------------------------------------------------------
22:09:03 Traceback (most recent call last):
22:09:03   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
22:09:03     self._join_processes(fn)
22:09:03   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in _join_processes
22:09:03     self._check_return_codes(elapsed_time)
22:09:03   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 276, in _check_return_codes
22:09:03     self.assertEqual(p.exitcode, first_process.exitcode)
22:09:03   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 915, in assertEqual
22:09:03     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
22:09:03 AssertionError: 16 not less than or equal to 1e-05 : 
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by pritamdamania87** [comment]
Closing this one out since it doesn't look like we run this CI job anymore.
