### ISSUE TITLE
No module named tools.nnwrap when installing py35 torch on Windows

### ISSUE THREAD

**Issue by gvashishtha** [pytorch/pytorch#34612]
## 🐛 Bug

I get an ImportError when trying to install torchvision from a pip wheel on Windows in a fresh conda environment.

## To Reproduce

1. `conda create -n py35 python=3.5`
1. `conda activate py35`
1. `pip install "https://download.pytorch.org/whl/cpu/torchvision-0.5.0%2Bcpu-cp35-cp35m-win_amd64.whl"`

```
(py351) C:\Users\govashis>pip install "https://download.pytorch.org/whl/cpu/torchvision-0.5.0%2Bcpu-cp35-cp35m-win_amd64.whl"
Collecting torchvision==0.5.0+cpu from https://download.pytorch.org/whl/cpu/torchvision-0.5.0%2Bcpu-cp35-cp35m-win_amd64.whl
  Using cached https://download.pytorch.org/whl/cpu/torchvision-0.5.0%2Bcpu-cp35-cp35m-win_amd64.whl
Collecting six (from torchvision==0.5.0+cpu)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting torch (from torchvision==0.5.0+cpu)
  Downloading https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz (128kB)
    100% |################################| 133kB 2.8MB/s
Collecting pillow>=4.1.1 (from torchvision==0.5.0+cpu)
  Using cached https://files.pythonhosted.org/packages/24/ab/0fcfd4690d15eb8039a278b173fac2ede5d4139998195a6de3dd370399f4/Pillow-7.0.0-cp35-cp35m-win_amd64.whl
Collecting numpy (from torchvision==0.5.0+cpu)
  Using cached https://files.pythonhosted.org/packages/3a/18/7f8ef94683f2a45a786f47d48e8fd11e49cfd1ff68b0b87054e5078f2b46/numpy-1.18.1-cp35-cp35m-win_amd64.whl
Collecting pyyaml (from torch->torchvision==0.5.0+cpu)
  Downloading https://files.pythonhosted.org/packages/8a/53/a649f98cd5ab851dc48677b8ae775113756286d040622381d385afdc5a32/PyYAML-5.3-cp35-cp35m-win_amd64.whl (208kB)
    100% |################################| 215kB 6.4MB/s
Building wheels for collected packages: torch
  Running setup.py bdist_wheel for torch ... error
  Complete output from command C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\govashis\\AppData\\Local\\Temp\\pip-install-yrlynq4_\\torch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\govashis\AppData\Local\Temp\pip-wheel-alseemmq --python-tag cp35:
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\govashis\AppData\Local\Temp\pip-install-yrlynq4_\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\site-packages\setuptools\__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\govashis\AppData\Local\Temp\pip-install-yrlynq4_\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ImportError: No module named 'tools.nnwrap'

  ----------------------------------------
  Failed building wheel for torch
  Running setup.py clean for torch
  Complete output from command C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\govashis\\AppData\\Local\\Temp\\pip-install-yrlynq4_\\torch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'

  ----------------------------------------
  Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: six, pyyaml, torch, pillow, numpy, torchvision
  Running setup.py install for torch ... error
    Complete output from command C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\govashis\\AppData\\Local\\Temp\\pip-install-yrlynq4_\\torch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\govashis\AppData\Local\Temp\pip-record-tugfyqtu\install-record.txt --single-version-externally-managed --compile:
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\govashis\AppData\Local\Temp\pip-install-yrlynq4_\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\site-packages\setuptools\__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\govashis\AppData\Local\Temp\pip-install-yrlynq4_\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\govashis\AppData\Local\Temp\pip-install-yrlynq4_\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ImportError: No module named 'tools.nnwrap'

    ----------------------------------------
Command "C:\Users\govashis\AppData\Local\Continuum\miniconda3\envs\py351\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\govashis\\AppData\\Local\\Temp\\pip-install-yrlynq4_\\torch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\govashis\AppData\Local\Temp\pip-record-tugfyqtu\install-record.txt --single-version-externally-managed --compile" failed with error
```

## Expected behavior

Expected installation to proceed without errors.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: version 3.15.5

Python version: 3.5
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 391.40
cuDNN version: Could not collect

## Additional context

pip version 10.0.1

cc @ezyang @seemethere

**Comment by gvashishtha** [comment]
One workaround for now: `pip install https://download.pytorch.org/whl/nightly/cpu/torch-1.4.0.dev20191015%2Bcpu-cp35-cp35m-win_amd64.whl` (this randomly chosen nightly build doesn't produce the same error as the main one)

**Comment by peterjc123** [comment]
Would you please try the following command?
```
pip install torch torchvision -f https://download.pytorch.org/whl/cpu/torch_stable.html
```

**Comment by peterjc123** [comment]
I don't think this is possible to fix because 
1. You are using direct link, so it won't find  any package unless it is hosted on pypi. 
2. However, windows binares are not available on pypi.

**Comment by rsboaventura** [comment]
The following command solved the problem for me (CUDA 11.0):

pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by atomicnick-02** [comment]
after running

 pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

i came across this 

ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0+cpu

**Comment by peterjc123** [comment]
> after running
> 
> pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
> 
> i came across this
> 
> ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
> ERROR: No matching distribution found for torch==1.4.0+cpu

Are you using Python x86? We only support Python x64 on Windows.

**Comment by seemethere** [comment]
Looks like the original issue here has been resolved!

Going to close this, thank you @peterjc123 for helping with this issue.
