### ISSUE TITLE
DISABLED test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#34716]
This is still flaky after #34505 

https://app.circleci.com/pipelines/github/pytorch/pytorch/139235/workflows/eedfde36-e956-4d3f-952b-24fd62639d14/jobs/4801429

```
Mar 13 15:10:46 .Process process 2:
Mar 13 15:10:46 Traceback (most recent call last):
Mar 13 15:10:46   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 13 15:10:46     self.run()
Mar 13 15:10:46   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 13 15:10:46     self._target(*self._args, **self._kwargs)
Mar 13 15:10:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 243, in _run
Mar 13 15:10:46     getattr(self, test_name)()
Mar 13 15:10:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 68, in new_test_method
Mar 13 15:10:46     return_value = old_test_method(self, *arg, **kwargs)
Mar 13 15:10:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 856, in test_stress_heavy_rpc_torchscript
Mar 13 15:10:46     self._stress_test_rpc(heavy_rpc_torchscript, repeat=20, args=(torch.ones(100, 100),))
Mar 13 15:10:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 838, in _stress_test_rpc
Mar 13 15:10:46     self.assertEqual(fut.wait(), 0)
Mar 13 15:10:46 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
Mar 13 15:11:25 Timing out after 100 seconds and killing subprocesses.
Mar 13 15:11:27 ERank 2 finished testing 1000 times in 0.6682846546173096 seconds.
Mar 13 15:11:27 Rank 1 finished testing 1000 times in 0.6684725284576416 seconds.
Mar 13 15:11:27 Rank 0 finished testing 1000 times in 0.34218406677246094 seconds.
Mar 13 15:11:27 Rank 3 finished testing 1000 times in 0.4612858295440674 seconds.
Mar 13 15:11:31 ......
Mar 13 15:11:31 ======================================================================
Mar 13 15:11:31 ERROR [100.092s]: test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)
Mar 13 15:11:31 ----------------------------------------------------------------------
Mar 13 15:11:31 Traceback (most recent call last):
Mar 13 15:11:31   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Mar 13 15:11:31     self._join_processes(fn)
Mar 13 15:11:31   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in _join_processes
Mar 13 15:11:31     self._check_return_codes(elapsed_time)
Mar 13 15:11:31   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 323, in _check_return_codes
Mar 13 15:11:31     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Mar 13 15:11:31 RuntimeError: Process 0 terminated or timed out after 100.08271050453186 seconds
```

cc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by zhaojuanmao** [comment]
tried stress run 100 times and can not reproduce it so far

**Comment by zhaojuanmao** [comment]
can reproduce it in local OSS stress runs with following error:

[E request_callback.cpp:39] Received error while processing request type 0: bad_weak_ptr
Rank 0 finished testing 20 times in 0.020754337310791016 seconds.
Process process 3:
Traceback (most recent call last):
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 243, in _run
    getattr(self, test_name)()
  File "/home/yanlizhao/pytorch/torch/testing/_internal/dist_utils.py", line 68, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/distributed/rpc/rpc_test.py", line 892, in test_stress_heavy_rpc_torchscript
    self._stress_test_rpc(heavy_rpc_torchscript, repeat=20, args=(torch.ones(100, 100),))
  File "/home/yanlizhao/pytorch/torch/testing/_internal/distributed/rpc/rpc_test.py", line 874, in _stress_test_rpc
    self.assertEqual(fut.wait(), 0)
RuntimeError: Error on Node 0: bad_weak_ptr
Rank 1 finished testing 20 times in 0.022899866104125977 seconds.
Rank 2 finished testing 20 times in 0.02346634864807129 seconds.

**Comment by zhaojuanmao** [comment]
Process process 2:
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
Traceback (most recent call last):
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 243, in _run
    getattr(self, test_name)()
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
  File "/home/yanlizhao/pytorch/torch/testing/_internal/dist_utils.py", line 71, in new_test_method
    rpc.shutdown(graceful=clean_shutdown)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
[E thread_pool.cpp:112] Exception in thread pool task: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 240, in shutdown
    _wait_all_workers()
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 165, in _wait_all_workers
    args=(sequence_id, self_worker_name,),
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 542, in rpc_sync
    return fut.wait()
RuntimeError: Encountered exception in ProcessGroupAgent::enqueueSend: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:24265: Connection reset by peer
Process process 1:
Traceback (most recent call last):
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 243, in _run
    getattr(self, test_name)()
  File "/home/yanlizhao/pytorch/torch/testing/_internal/dist_utils.py", line 71, in new_test_method
    rpc.shutdown(graceful=clean_shutdown)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 240, in shutdown
    _wait_all_workers()
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 165, in _wait_all_workers
    args=(sequence_id, self_worker_name,),
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 542, in rpc_sync
    return fut.wait()
RuntimeError: Encountered exception in ProcessGroupAgent::enqueueSend: [/home/yanlizhao/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [2401:db00:21:604e:face:0:13:0]:8835: Connection reset by peer
Process process 3:
Traceback (most recent call last):
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 243, in _run
    getattr(self, test_name)()
  File "/home/yanlizhao/pytorch/torch/testing/_internal/dist_utils.py", line 68, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/distributed/rpc/rpc_test.py", line 892, in test_stress_heavy_rpc_torchscript
    self._stress_test_rpc(heavy_rpc_torchscript, repeat=20, args=(torch.ones(100, 100),))
  File "/home/yanlizhao/pytorch/torch/testing/_internal/distributed/rpc/rpc_test.py", line 874, in _stress_test_rpc
    self.assertEqual(fut.wait(), 0)
RuntimeError: RPC ran for more than 60000 milliseconds and timed out.

**Comment by zhaojuanmao** [comment]
I  ran this test  on  OSS  repo  using  "python ...." 1000  times and  "pytest  ..." 500 times, can not  reproduce it. 

Would like to close  it and see  whether  it will happen again in master in  the next a  few days

**Comment by zhaojuanmao** [comment]
reopening, tried stress ran 1000  times again, found one  repro

Ran 1 test in 0.728s

OK
[E request_callback_impl.cpp:94] Received error while processing request type 0: bad_weak_ptr
Process process 0:
Traceback (most recent call last):
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 243, in _run
    getattr(self, test_name)()
  File "/home/yanlizhao/pytorch/torch/testing/_internal/dist_utils.py", line 69, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/distributed/rpc/rpc_test.py", line 895, in test_stress_heavy_rpc_torchscript
    self._stress_test_rpc(heavy_rpc_torchscript, repeat=20, args=(torch.ones(100, 100),))
  File "/home/yanlizhao/pytorch/torch/testing/_internal/distributed/rpc/rpc_test.py", line 877, in _stress_test_rpc
    self.assertEqual(fut.wait(), 0)
RuntimeError: Error on Node 1: bad_weak_ptr
[E request_callback_impl.cpp:94] Received error while processing request type 2: TypeError: 'NoneType' object is not callable

At:
  /home/yanlizhao/pytorch/torch/distributed/rpc/internal.py(101): deserialize
  /home/yanlizhao/pytorch/torch/distributed/rpc/internal.py(122): deserialize

Process process 3:
Traceback (most recent call last):
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yanlizhao/local/anaconda3/envs/py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 243, in _run
    getattr(self, test_name)()
  File "/home/yanlizhao/pytorch/torch/testing/_internal/dist_utils.py", line 72, in new_test_method
    rpc.shutdown(graceful=clean_shutdown)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 240, in shutdown
    _wait_all_workers()
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 165, in _wait_all_workers
    args=(sequence_id, self_worker_name,),
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yanlizhao/pytorch/torch/distributed/rpc/api.py", line 554, in rpc_sync
    return fut.wait()
RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
E
======================================================================
ERROR: test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 175, in wrapper
    self._join_processes(fn)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 285, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/home/yanlizhao/pytorch/torch/testing/_internal/common_distributed.py", line 323, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 1 terminated or timed out after 100.08614683151245 seconds

----------------------------------------------------------------------
Ran 1 test in 100.147s

**Comment by mrshenli** [comment]
It has been a while, not sure if some of any recent fixes solved this problem. Close for now and let it run on master.
