### ISSUE TITLE
Feature Request: Distributed send arbitrary objects

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3473]
It would be useful for torch.distributed.send and .recv to be able to send arbitrary objects. I have two requests:

1. One version of send and recv that does not copy to tensor, but instead returns a new tensor. This way, we can send tensors of arbitrary sizes, useful for many reinforcement learning settings
2. Ability to send arbitrary Python objects, preferrably over pickle streams. mpi4py supports this mode, and it is sometimes very useful to prototype with despite its inefficiencies.

**Comment by bsolano** [comment]
Hello.

It would be advantageous.  It would permit to do distributed computing in a higher level of abstraction.  Although transferring complete neural networks is unpractical because of their size, these can be transferred as compressed objects like Uber AI Labs did in "Deep Neuroevolution: Genetic Algorithms Are a Competitive Alternative for Training Deep Neural Networks for Reinforcement Learning".

I am currently trying to reproduce a form of compressed neural networks using Pytorch and to train using a distributed environment.  The fact that the operators only permit tensors is an obstacle.  Some people solve it using worker queues such as Redis.

Bests.

**Comment by ultmaster** [comment]
I believe the following code snippet solves the problem, to some extent.

```python
def reduce_python_object(obj, rank, distributed=True):
    # Collect object from replicas and form a list
    if not distributed:
        return [obj]
    MAX_LENGTH = 2 ** 20  # 1M
    world_size = int(os.environ["WORLD_SIZE"])
    assert 0 <= rank < world_size
    result = []
    for i in range(world_size):
        if rank == i:
            data = pickle.dumps(obj)
            data_length = len(data)
            data = data_length.to_bytes(4, "big") + data
            assert len(data) < MAX_LENGTH
            data += bytes(MAX_LENGTH - len(data))
            data = np.frombuffer(data, dtype=np.uint8)
            assert len(data) == MAX_LENGTH
            tensor = torch.from_numpy(data).cuda()
        else:
            tensor = torch.zeros(MAX_LENGTH, dtype=torch.uint8, device="cuda")
        dist.all_reduce(tensor, op=dist.ReduceOp.SUM)
        data = tensor.cpu().numpy().tobytes()
        length = int.from_bytes(data[:4], "big")
        data = data[4:length + 4]
        result.append(pickle.loads(data))
    return result
```

Usage:

```python
reduce_python_object({f"random{args.local_rank + 5}": args.local_rank / 800}, args.local_rank)
```

**Comment by pritamdamania87** [comment]
The send/recv APIs still don't support this, but you can probably use the RPC framework: https://pytorch.org/docs/stable/rpc.html to send arbitrary data around in a distributed environment.

**Comment by zw0610** [comment]
> The send/recv APIs still don't support this, but you can probably use the RPC framework: https://pytorch.org/docs/stable/rpc.html to send arbitrary data around in a distributed environment.

I seems not correct if I define a class in rpc node A and send it to rpc node B. Error listed below occurs:
```
AttributeError("Can't get attribute 'A' on <module '__main__' (built-in)> Default RPC pickler does not serialize\n            function code. Ensure that UDFs are defined on both caller and\n            callee modules.")
Traceback (most recent call last):
  File "/Users/lucas/miniconda3/envs/torch/lib/python3.9/site-packages/torch/distributed/rpc/internal.py", line 159, in deserialize
    ret = unpickler.load()
AttributeError: Can't get attribute 'A' on <module '__main__' (built-in)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lucas/miniconda3/envs/torch/lib/python3.9/site-packages/torch/distributed/rpc/internal.py", line 205, in _run_function
    raise python_udf
AttributeError: Can't get attribute 'A' on <module '__main__' (built-in)> Default RPC pickler does not serialize
            function code. Ensure that UDFs are defined on both caller and
            callee modules.
```

**Comment by npuichigo** [comment]
My use case is to use ray data, but distribution needs to pass part of its `SplitDataset` to other workers. So I use native [ray train](https://docs.ray.io/en/latest/train/train.html) to launch distributed PyTorch.
```
import ray

@ray.remote
class Worker:

    def train(self, data_iterator):
        for batch in data_iterator.iter_batches(batch_size=8):
            pass

ds = ray.data.read_csv("s3://anonymous@air-example-data/iris.csv")
workers = [Worker.remote() for _ in range(4)]
shards = ds.streaming_split(n=4, equal=True)
ray.get([w.train.remote(s) for w, s in zip(workers, shards)])
```

**Comment by andoorve** [comment]
Should be closed by https://github.com/pytorch/pytorch/commit/b96b1e8cff029bb0a73283e6e7f6cc240313f1dc
