### ISSUE TITLE
network-based TorchHub tests contribute to CI flakiness

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#34751]
Perhaps this suite of tests can be run on nightly instead of on each `master` commit?

See this [example failure on `master` branch](https://circleci.com/gh/pytorch/pytorch/4763382):

```
Mar 11 05:06:21 ======================================================================
Mar 11 05:06:21 ERROR [0.403s]: test_download_url_to_file (__main__.TestHub)
Mar 11 05:06:21 ----------------------------------------------------------------------
Mar 11 05:06:21 Traceback (most recent call last):
Mar 11 05:06:21   File "test_utils.py", line 547, in test_download_url_to_file
Mar 11 05:06:21     hub.download_url_to_file(TORCHHUB_EXAMPLE_RELEASE_URL, temp_file, progress=False)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/site-packages/torch/hub.py", line 394, in download_url_to_file
Mar 11 05:06:21     u = urlopen(url)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
Mar 11 05:06:21     return opener.open(url, data, timeout)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
Mar 11 05:06:21     response = meth(req, response)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
Mar 11 05:06:21     'http', request, response, code, msg, hdrs)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
Mar 11 05:06:21     return self._call_chain(*args)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
Mar 11 05:06:21     result = func(*args)
Mar 11 05:06:21   File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
Mar 11 05:06:21     raise HTTPError(req.full_url, code, msg, hdrs, fp)
Mar 11 05:06:21 urllib.error.HTTPError: HTTP Error 401: UNAUTHORIZED
```

cc @ezyang @gchanan @zou3519 @ailzhang, @suo

**Comment by suo** [comment]
@ailzhang any thoughts? We want to reduce the number of tests that are accessing network.

**Comment by ailzhang** [comment]
I guess I'll first add a retry to hub tests to minimize the failure rate.
I can send a PR for it.  
Also as discussed with @kostmo offline, if we want to move network dependent tests to a separate job per operation system, I think that's also fine. :D
