### ISSUE TITLE
RuntimeError: CUDA error (3): initialization error 

### ISSUE THREAD

**Issue by zhoumingyi** [pytorch/pytorch#3491]
```
import torch
import torch.multiprocessing as mp

def subprocesses(A, B, D, i, j, size):
    D[(j * size):((j + 1) * size), i] = torch.mul(B[:, i], A[j, i])

def task(A, B):

    size1 = A.shape
    size2 = B.shape
    D = torch.zeros([size1[0]*size2[0], size1[1]]).cuda()
    D.share_memory_()
    
    for i in range(1):
        processes = []
        for j in range(size1[0]):  
            p = mp.Process(target=subprocesses, args=(A, B, D, i, j, size2[0]))
            p.start()
            processes.append(p)
        for p in processes:
            p.join()

    return D

A = torch.rand(3, 3).cuda()
B = torch.rand(3, 3).cuda()
C = task(A,B)
print(C)
```
I run these codes using pytorch 0.2.0, python 3.5 with error

```
Process Process-1:
Traceback (most recent call last):
Process Process-2:
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "<ipython-input-2-cbb040477c37>", line 3, in subprocesses
    D[(j * size):((j + 1) * size), i] = torch.mul(B[:, i], A[j, i])
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
RuntimeError: CUDA error (3): initialization error
  File "<ipython-input-2-cbb040477c37>", line 3, in subprocesses
    D[(j * size):((j + 1) * size), i] = torch.mul(B[:, i], A[j, i])
RuntimeError: CUDA error (3): initialization error
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-2-cbb040477c37>", line 3, in subprocesses
    D[(j * size):((j + 1) * size), i] = torch.mul(B[:, i], A[j, i])
RuntimeError: CUDA error (3): initialization error
```
But using cpu( ) woks fine

**Comment by soumith** [comment]
as mentioned in http://pytorch.org/docs/master/notes/multiprocessing.html#sharing-cuda-tensors

insert this to the top of your script

```
import torch
torch.multiprocessing.set_start_method("spawn")
```

**Comment by zhoumingyi** [comment]
Thanks
But it also returned errors when I Inserted it 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mingyi/桌面/test/test.py", line 2, in <module>
    torch.multiprocessing.set_start_method("spawn")
  File "/usr/lib/python3.5/multiprocessing/context.py", line 231, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 106, in spawn_main
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.5/runpy.py", line 254, in run_path
    run_name="__mp_main__")
  File "/usr/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mingyi/桌面/test/test.py", line 2, in <module>
    exec(code, run_globals)
  File "/home/mingyi/桌面/test/test.py", line 2, in <module>
    torch.multiprocessing.set_start_method("spawn")
  File "/usr/lib/python3.5/multiprocessing/context.py", line 231, in set_start_method
    torch.multiprocessing.set_start_method("spawn")
  File "/usr/lib/python3.5/multiprocessing/context.py", line 231, in set_start_method
    raise RuntimeError('context has already been set')
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
RuntimeError: context has already been set

    0     0     0
    0     0     0
    0     0     0
    0     0     0
    0     0     0
    0     0     0
    0     0     0
    0     0     0
    0     0     0
[torch.FloatTensor of size 9x3]


Process finished with exit code 0

```
