### ISSUE TITLE
DISABLED test_backward_node_failure (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#34952]
https://app.circleci.com/pipelines/github/pytorch/pytorch/141441/workflows/a4d5bdb8-6425-4c59-9997-a468ad951b01/jobs/4854537

```
Mar 18 11:19:47 ----------------------------------------------------------------------
Mar 18 11:20:06 ............[E request_callback_impl.cpp:94] Received error while processing request type 15: TypeError: 'NoneType' object is not callable
Mar 18 11:20:48 F.....................Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:48 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:48 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:48 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:49 .[E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 11:20:49 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 11:20:49 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 11:20:49 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 11:20:50 .Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:50 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:50 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:50 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:20:50   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:20:50   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:20:50   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:20:50   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:21:14 .................Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:21:14 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:21:14 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:21:14 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:21:14   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:21:14   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:21:14   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 11:21:14   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 11:21:23 ........
Mar 18 11:21:23 ======================================================================
Mar 18 11:21:23 FAIL [6.131s]: test_backward_node_failure (__main__.DistAutogradTestWithSpawn)
Mar 18 11:21:23 ----------------------------------------------------------------------
Mar 18 11:21:23 Traceback (most recent call last):
Mar 18 11:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Mar 18 11:21:23     self._join_processes(fn)
Mar 18 11:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in _join_processes
Mar 18 11:21:23     self._check_return_codes(elapsed_time)
Mar 18 11:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 324, in _check_return_codes
Mar 18 11:21:23     self.assertEqual(p.exitcode, first_process.exitcode)
Mar 18 11:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 915, in assertEqual
Mar 18 11:21:23     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Mar 18 11:21:23 AssertionError: 11 not less than or equal to 1e-05 : 
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by rohan-varma** [comment]
Taking a look, never saw this before: 
`Received error while processing request type 15: TypeError: 'NoneType' object is not callable`. Not sure if this indicates that python interpreter is unavailable in the remote end.

**Comment by pritamdamania87** [comment]
Couldn't repro this failure and it is likely fixed by the PRs that fixed https://github.com/pytorch/pytorch/issues/35099.

**Comment by rohan-varma** [comment]
It looks like this came up again: https://github.com/pytorch/pytorch/issues/38232
