### ISSUE TITLE
DISABLED test_autograd_context (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#34960]
https://app.circleci.com/pipelines/github/pytorch/pytorch/141487/workflows/6ccb9e3c-5ce3-4884-8c80-657207053845/jobs/4855438

```
Mar 18 08:54:22 Generating XML reports...
Mar 18 08:54:23 Running distributed/rpc/test_dist_autograd_spawn ... [2020-03-18 08:54:23.107885]
Mar 18 08:54:24 
Mar 18 08:54:24 Running tests...
Mar 18 08:54:24 ----------------------------------------------------------------------
Mar 18 08:56:06 .Timing out after 100 seconds and killing subprocesses.
Mar 18 08:56:54 E..........ss....................Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:56:54 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:56:54 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:56:54 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:56:55 .[E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 08:56:55 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 08:56:55 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 08:56:55 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41
Mar 18 08:56:57 ./Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:56:57   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:56:57 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:56:57   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:56:57 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:56:57   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:56:57 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:56:57   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:56:57 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:56:57 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (Warning: operator()Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. at  (../torch/csrc/jit/python/pybind_utils.h:operator() at 684../torch/csrc/jit/python/pybind_utils.h)
Mar 18 08:56:57 :684)
Mar 18 08:56:57 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:57:21 ................./Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:57:21   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:57:21 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:57:21   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:57:21 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:57:21   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:57:21 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.
Mar 18 08:57:21   warnings.warn("Argument order of nn.functional.embedding_bag was changed. "
Mar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)
Mar 18 08:57:31 ........
Mar 18 08:57:31 ======================================================================
Mar 18 08:57:31 ERROR [100.051s]: test_autograd_context (__main__.DistAutogradTestWithSpawn)
Mar 18 08:57:31 ----------------------------------------------------------------------
Mar 18 08:57:31 Traceback (most recent call last):
Mar 18 08:57:31   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Mar 18 08:57:31     self._join_processes(fn)
Mar 18 08:57:31   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 285, in _join_processes
Mar 18 08:57:31     self._check_return_codes(elapsed_time)
Mar 18 08:57:31   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 323, in _check_return_codes
Mar 18 08:57:31     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Mar 18 08:57:31 RuntimeError: Process 0 terminated or timed out after 100.02388215065002 seconds
Mar 18 08:57:31 
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
Tried a few hundred times on linux and macos locally, but cannot reproduce the error. Looks like there might be a race for our shutdown. Trying with CI docker env now.

**Comment by mrshenli** [comment]
Tried on the failed MacOS CI docker environment, still cannot reproduce. But I noticed that the `test_autograd_context` test case takes very long to finish in MacOS CI env (~10sec). I am not sure if it could be some bad luck resource contention making this take even longer to finish (> 100sec) and finally leads to timeout. So submitted #35037 to reduce the number of iterations.
