### ISSUE TITLE
`device_count()` returns 1 while `torch._C._cuda_getDeviceCount()` returns 2?

### ISSUE THREAD

**Issue by PingHGao** [pytorch/pytorch#35020]
# Environment：
- Win10
- Pytorch 1.3.0
- python3.7（Anaconda3）
# Problem
I am using dataparallel in Pytorch to use the two 2080Ti GPUs. Code are like below:
```python
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = Darknet(opt.model_def)  
model.apply(weights_init_normal) 

model = nn.DataParallel(model, device_ids=[0, 1]).to(device)
```
But when run this code, I encounter errors below:
```
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/PyTorch-YOLOv3-master/train.py", line 74, in <module>
    model = nn.DataParallel(model, device_ids=[0, 1]).to(device)
  File "C:\Users\Administrator\Anaconda3\envs\py37_torch1.3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "C:\Users\Administrator\Anaconda3\envs\py37_torch1.3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "C:\Users\Administrator\Anaconda3\envs\py37_torch1.3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "C:\Users\Administrator\Anaconda3\envs\py37_torch1.3\lib\site-packages\torch\cuda\__init__.py", line 337, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```
When I debug into it, I find the function `device_count()` in `get_device_properties()` returns 1 while I have 2 GPU on my machine. And `torch._C._cuda_getDeviceCount()` returns 2 in Anaconda Prompt. What is wrong?

cc @ngimel

**Comment by peterjc123** [comment]
I tried to move a different model with PyTorch 1.4.0 and cannot reproduce your problem.
The code is listed below:
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.optim.lr_scheduler import StepLR


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.dropout1 = nn.Dropout2d(0.25)
        self.dropout2 = nn.Dropout2d(0.5)
        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        x = self.dropout1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output

if __name__ == '__main__':
    net = Net()
    print(torch.cuda.device_count())
    print(torch._C._cuda_getDeviceCount())
    device = torch.device('cuda')
    model = nn.DataParallel(net, device_ids=[0, 1]).to(device)
```
BTW, you mentioned the function `device_count()` in `get_device_properties()` returns 1. Could you elaborate a little bit? I think `get_device_properties` is a device-level function and only returns the information of a device.

**Comment by PingHGao** [comment]
I solved it by adding `os.environ["CUDA_VISIBLE_DEVICES"] = '0,1'`. When not adding this sentence, the error occurs. I am using this machine, I will try to reproduce this error when the matchine is free if it would help.
