### ISSUE TITLE
Compilation error on aarch64

### ISSUE THREAD

**Issue by louisabraham** [pytorch/pytorch#35049]
## 🐛 Bug

I'm trying to compile pytorch on manjaro arm (pinebook pro).

```bash
pacman -Syu python python-numpy python-yaml python-cffi python-setuptools cmake

export NO_CUDA=1
export NO_DISTRIBUTED=1
export NO_MKLDNN=1 
export BUILD_TEST=0
export MAX_JOBS=6
export USE_SYSTEM_NCCL=0
export USE_NCC=OFF
export VERBOSE=1
export USE_OPENMP=1

git clone https://github.com/pytorch/pytorch --recursive
cd pytorch
python setup.py install
```

The last lines are

```
[ 58%] Building C object sleef/src/libm/CMakeFiles/sleefpurec_scalar.dir/sleefsimddp.c.o
cd /home/louisabraham/pytorch/build/sleef/src/libm && /usr/bin/cc -DDORENAME=1 -DENABLE_ALIAS=1 -DENABLE_BUILTIN_MATH=1 -DENABLE_PUREC_SCALAR=1 -DENABLE_SYS_getrandom=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DSLEEF_STATIC_LIBS=1 -D_FILE_OFFSET_BITS=64 -I/home/louisabraham/pytorch/build/aten/src -I/home/louisabraham/pytorch/aten/src -I/home/louisabraham/pytorch/build -I/home/louisabraham/pytorch -I/home/louisabraham/pytorch/build/caffe2/contrib/aten -I/home/louisabraham/pytorch/third_party/onnx -I/home/louisabraham/pytorch/build/third_party/onnx -I/home/louisabraham/pytorch/third_party/foxi -I/home/louisabraham/pytorch/build/third_party/foxi -I/home/louisabraham/pytorch/third_party/NNPACK/include -I/home/louisabraham/pytorch/third_party/NNPACK/src -I/home/louisabraham/pytorch/third_party/cpuinfo/include -I/home/louisabraham/pytorch/third_party/pthreadpool/include -I/home/louisabraham/pytorch/third_party/FXdiv/include -I/home/louisabraham/pytorch/third_party/psimd/include -I/home/louisabraham/pytorch/third_party/FP16/include -I/home/louisabraham/pytorch/third_party/pthreadpool/src -I/home/louisabraham/pytorch/third_party/sleef/src/common -I/home/louisabraham/pytorch/third_party/sleef/src/arch -I/home/louisabraham/pytorch/build/sleef/src/libm/include -I/home/louisabraham/pytorch/third_party/sleef/src/libm -isystem /home/louisabraham/pytorch/build/third_party/gloo -isystem /home/louisabraham/pytorch/cmake/../third_party/gloo -isystem /home/louisabraham/pytorch/third_party/protobuf/src -isystem /home/louisabraham/pytorch/third_party/gemmlowp -isystem /home/louisabraham/pytorch/third_party/neon2sse -isystem /home/louisabraham/pytorch/third_party/XNNPACK/include -isystem /home/louisabraham/pytorch/cmake/../third_party/eigen -isystem /usr/include/python3.8 -isystem /usr/lib/python3.8/site-packages/numpy/core/include -isystem /home/louisabraham/pytorch/cmake/../third_party/pybind11/include  -Wall -Wno-unused -Wno-attributes -Wno-unused-result -Wno-psabi -ffp-contract=off -fno-math-errno -fno-trapping-math -O3 -DNDEBUG -DNDEBUG -fPIC   -DCAFFE2_USE_GLOO -D__NEON__ -DUSE_GCC_GET_CPUID -DTH_HAVE_THREAD -std=gnu99 -o CMakeFiles/sleefpurec_scalar.dir/sleefsimddp.c.o   -c /home/louisabraham/pytorch/third_party/sleef/src/libm/sleefsimddp.c
make[2]: Leaving directory '/home/louisabraham/pytorch/build'
[ 58%] Built target sleefdetadvsimd
make[2]: Leaving directory '/home/louisabraham/pytorch/build'
[ 58%] Built target sleefadvsimdnofma
make[2]: Leaving directory '/home/louisabraham/pytorch/build'
[ 58%] Built target sleefadvsimd
make[2]: Leaving directory '/home/louisabraham/pytorch/build'
[ 58%] Built target sleefpurec_scalar
make[1]: Leaving directory '/home/louisabraham/pytorch/build'
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 745, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    build_caffe2(version=version,
  File "/home/louisabraham/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/louisabraham/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/home/louisabraham/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
```

**Comment by louisabraham** [comment]
I added 

```bash
git checkout v1.4.0
git submodule sync
git submodule update --init --recursive
```

and now I get

```
/home/louisabraham/pytorch/c10/util/LeftRight.h:67:10: error: ‘typename std::result_of<F(const T&)>::type c10::LeftRight<T>::read(F&&) const [with F = c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = at::Tensor; Args = {const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>; T = ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>; typename std::result_of<F(const T&)>::type = at::Tensor]’, declared using local type ‘c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = at::Tensor; Args = {const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>’, is used but never defined [-fpermissive]
make[2]: *** [caffe2/CMakeFiles/torch.dir/build.make:265: caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Context.cpp.o] Error 1
make[2]: Leaving directory '/home/louisabraham/pytorch/build'
make[1]: *** [CMakeFiles/Makefile2:2481: caffe2/CMakeFiles/torch.dir/all] Error 2
make[1]: Leaving directory '/home/louisabraham/pytorch/build'
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    build_caffe2(version=version,
  File "/home/louisabraham/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/louisabraham/pytorch/tools/setup_helpers/cmake.py", line 335, in build
    self.run(build_args, my_env)
  File "/home/louisabraham/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
```

**Comment by deepseek** [comment]
@louisabraham did you succeed?

**Comment by louisabraham** [comment]
No, I didn't try after that

**Comment by deepseek** [comment]
https://nmilosev.svbtle.com/compling-arm-stuff-without-an-arm-board-build-pytorch-for-the-raspberry-pi

**Comment by marty1885** [comment]
I ran into the same issue on aarch64. I am able to work around it by downloading sleef 3.5.1, install it to system and set the `USE_SYSTEM_SLEEF=ON` flag.

Hope it helps

**Comment by louisabraham** [comment]
Rad! I will definitely try tonight :)

**Comment by marty1885** [comment]
To be clear. I set the CMake flag (editing CMakeLists.txt), not by exporting. And I built pytorch using a modified Arch Linux's [PKGBUILD](https://github.com/archlinux/svntogit-community/tree/packages/python-pytorch/trunk). Not sure if the patches have helped in other ways.

**Comment by louisabraham** [comment]
Thank you very much, I was able to compile torch.

Here are instructions taken from my [blogpost](https://louisabraham.github.io/articles/pinebook-pro-setup.html)

---

After some effort and the help of [marty1885](https://github.com/pytorch/pytorch/issues/35049), I could compile the latest version of PyTorch.

First, compile and install sleef: <https://sleef.org/compile.xhtml> (you will need sudo to install). You should also add the following line to your `.bashrc` (or equivalent)
```
export LD_LIBRARY_PATH='$LD_LIBRARY_PATH:/usr/local/lib'
```

If you are using Python 3.8 and do not want to wait for HOURS, you can download my precompiled wheel [here](/misc/torch-1.6.0a0+b31f58d-cp38-cp38-linux_aarch64.whl).

Here is how I produced it:

1\. Install the dependencies (this command is for arch/manjaro)
```
pacman -Syu python python-numpy python-yaml python-cffi python-setuptools python-wheel cmake
```
2\. Download source code and compile
```bash
git clone https://github.com/pytorch/pytorch --recursive
cd pytorch

git checkout v1.6.0-rc7 # I chose the latest tag
git submodule sync
git submodule update --init --recursive
```
3\. Edit CMakeLists.txt to set two flags:

```
option(USE_PYTORCH_QNNPACK "Use ATen/QNNPACK (quantized 8-bit operators)" OFF)
option(USE_SYSTEM_SLEEF "Use system-provided sleef." ON)
```
4\. Compile
```bash
export BUILD_TEST=0
export MAX_JOBS=6 # use all the cores, set to a lower number if you want to use your computer while compiling
export USE_SYSTEM_NCCL=0
export USE_DISTRIBUTED=0
export USE_QNNPACK=0

python setup.py bdist_wheel
```

The wheel will be in the `dist/` folder.


Whether you compiled or downloaded the `.whl`, you can install it with
```
pip install torch-1.6.0a0+b31f58d-cp38-cp38-linux_aarch64.whl
```

**Comment by marty1885** [comment]
@louis2889184 Wow, that's a very clear and easy to follow instruction!

Since you are at it. May you try if your build of PyTorch can utilize multiple cores? Mine seems to be single core only and I can't figure out why. I think I'll make another report if you are also experiencing the same issue.

**Comment by louisabraham** [comment]
Thanks :)

What do you mean by "multiple cores"? Do you mean BLAS parallelism? or torch.distributed?

**Comment by marty1885** [comment]
Oops.. I mean BLAS parallelism.

**Comment by louisabraham** [comment]
What is your protocol to test?

```
>>> print(torch.__config__.show())
PyTorch built with:
  - GCC 10.2
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, USE_CUDA=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

>>> print(torch.__config__.parallel_info())
ATen/Parallel:
        at::get_num_threads() : 6
        at::get_num_interop_threads() : 6
OpenMP 201511 (a.k.a. OpenMP 4.5)
        omp_get_max_threads() : 6
MKL not found
MKLDNN not found
std::thread::hardware_concurrency() : 6
Environment variables:
        OMP_NUM_THREADS : [not set]
        MKL_NUM_THREADS : [not set]
ATen parallel backend: OpenMP
```

**Comment by marty1885** [comment]
Please run:

```python
import torch
print(torch.__config__.show())
print(torch.__config__.parallel_info())
t = torch.ones([8000, 8000])
print(t@t)
```

It generates a large matrix (large enough so there's enough time to observe) then performs matrix multiplication.

Then run `top`, `htop` or whatever to see if PyTorch is performing the matrix multiplication in parallel.

Mine look like this
![image](https://user-images.githubusercontent.com/8792393/94040956-2efadd80-fdfc-11ea-8a01-95db285ce0eb.png)

By the looks of the output, I may have messed up something? `at::get_num_threads()` should be 16 on my system.

**Comment by louisabraham** [comment]
By default, I had blas (lapack) installed. Installing openblas made me use multiple threads (and drastically improved even single thread performance).

**Comment by louisabraham** [comment]
Also you don't have OpenMP, which is strange as it is usually bundled with the compiler.

**Comment by louisabraham** [comment]
Strangely, rerunning cmake after installing OpenBLAS doesn't change the BLAS : MKL option so it's probably useless to recompile as the problem either will be solved by installing OpenBLAS or comes from another source (most likely OpenMP).

**Comment by marty1885** [comment]
Ahh... so its caused by LAPACK. Installed OpenBLAS (replaces LAPACK) and it runs in parallel. Thank you!

MKL and MLK-DNN are different products (yeah, bad naming). MKL is x86 only while MKL-DNN supports a wide family of processors. The relation is kinda convoluted and I have to hack CMake to convince PyTorch MKL-DNN is available on ARM. I don't get why PyTorch prioritizes using BLAS instead of NNPACK and NKL-DNN tho. 

I think I built my PyTorch with TBB instead of OpenMP. As a step debugging why nothing is running in parallel.

**Comment by louisabraham** [comment]
Really nice! I don't think PyTorch can use oneDNN (they renamed it) "instead" of BLAS, they are probably not the same APIs. Maybe for more neural networky functions it will use oneDNN.

> I think I built my PyTorch with TBB instead of OpenMP. As a step debugging why nothing is running in parallel.

You can probably check by testing OMP_NUM_THREADS and tbb::init (with ctypes) to set the number of threads manually.

**Comment by louisabraham** [comment]
Closing this since it was solved long time ago [above](https://github.com/pytorch/pytorch/issues/35049#issuecomment-697540349)
