### ISSUE TITLE
[JIT] If a python function type comment is referring to a wrong type, JIT frontend gives a not helpful error message

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#35074]
```
        dst_worker_name = worker_name((self.rank + 1) % self.world_size)
        input_0 = torch.ones(2, 2)
        input_1 = 1
        expected_res = torch.add(input_0, input_1)

        @torch.jit.ignore
        def python_return_future():
            # type: () -> Future[Tensor]
            fut = rpc.rpc_async(dst_worker_name, torch.add, (input_0, input_1), {})
            return fut

        @torch.jit.script
        def script_use_future():
            # type: () -> Tensor
            fut = python_return_future()
            return fut.wait()

        res = script_use_future()
        self.assertEqual(res, expected_res)
```

The error message is
```
/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/testing/_internal/common_distributed.py:181: Caught exception:
Traceback (most recent call last):
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 178, in wrapper
    fn(self)
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/testing/_internal/dist_utils.py", line 69, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 35, in test_script_call_python_return_future
    @torch.jit.script
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/jit/__init__.py", line 1296, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/jit/annotations.py", line 80, in get_signature
    signature = parse_type_line(type_line, rcb, loc)
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/jit/rpc_fork#binary,link-tree/torch/jit/annotations.py", line 163, in parse_type_line
    ret_ann = eval(ret_ann_str, {}, EvalEnv(rcb))  # noqa: P204
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not subscriptable
exiting process with exit code: 10
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
