### ISSUE TITLE
CuDNN ConvTranspose1d issue with transposed cuda Variable (can't convert to contiguous)

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#3512]
```python
>>> import torch
>>> import torch.nn as nn
>>> from torch.autograd import Variable
>>> 
>>> x = Variable(torch.randn(1, 1, 1024).cuda())
>>> m = nn.ConvTranspose1d(1024, 1, 1).cuda()
>>> 
>>> x.is_contiguous()
True
>>> x.transpose(1, 2).is_contiguous()
True
>>> m(x.transpose(1, 2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 259, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 463, in forward
    output_padding, self.groups, self.dilation)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 149, in conv_transpose1d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
>>> m(x.transpose(1, 2).contiguous())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 259, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 463, in forward
    output_padding, self.groups, self.dilation)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 149, in conv_transpose1d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
>>> 
>>> y = x.cpu().transpose(1, 2).cuda()
>>> m(y)
Variable containing:
(0 ,.,.) = 
  0.7149
[torch.cuda.FloatTensor of size 1x1x1 (GPU 0)]

>>> torch.version.__version__
'0.2.0+c74f7d8'
```

What I have found out:
- m(x.transpose(1, 2).contiguous()) is not working because x.transpose(1, 2).is_contiguous() is evaluated to True, letting .contiguous() does nothing.
- This code works with cudnn disabled.
- This code works with Conv1d.

**Comment by zou3519** [comment]
This has been fixed on master:
![image](https://user-images.githubusercontent.com/5652049/32459250-fd587eaa-c2fc-11e7-8dd3-ca35df49f98d.png)
You can build pytorch from source to avoid this bug or wait for the next release.

**Comment by qbx2** [comment]
Wow, I'll build it again. Thank you.
