### ISSUE TITLE
hasSpecialCase INTERNAL ASSERT FAILED: We don't have an op for aten::to but it isn't a special case.

### ISSUE THREAD

**Issue by Randl** [pytorch/pytorch#35180]
## Stack trace
```
RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case. (analyzeImpl at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f672f887193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x410926b (0x7f6733feb26b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x410afc0 (0x7f6733fecfc0 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: torch::jit::AliasDb::AliasDb(std::shared_ptr<torch::jit::Graph>) + 0x215 (0x7f6733fed265 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #4: torch::jit::EliminateDeadCode(std::shared_ptr<torch::jit::Graph> const&, torch::jit::DCESideEffectPolicy) + 0x5e (0x7f673402532e in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x4157a4b (0x7f6734039a4b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #6: torch::jit::FixupTraceScopeBlocks(std::shared_ptr<torch::jit::Graph>&, torch::jit::script::Module*) + 0x38b (0x7f673403ce3b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #7: torch::jit::tracer::trace(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::function<std::vector<c10::IValue, std::allocator<c10::IValue> > (std::vector<c10::IValue, std::allocator<c10::IValue> >)> const&, std::function<std::string (at::Tensor const&)>, bool, torch::jit::script::Module*) + 0x5a6 (0x7f67341f9aa6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x758231 (0x7f677b17c231 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x771ab2 (0x7f677b195ab2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x2961c4 (0x7f677acba1c4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #11: _PyCFunction_FastCallDict + 0x35c (0x5674fc in /usr/bin/python3)
frame #12: /usr/bin/python3() [0x50abb3]
frame #13: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #14: /usr/bin/python3() [0x508245]
frame #15: /usr/bin/python3() [0x50a080]
frame #16: /usr/bin/python3() [0x50aa7d]
frame #17: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #18: /usr/bin/python3() [0x508245]
frame #19: /usr/bin/python3() [0x50a080]
frame #20: /usr/bin/python3() [0x50aa7d]
frame #21: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #22: /usr/bin/python3() [0x508245]
frame #23: /usr/bin/python3() [0x50a080]
frame #24: /usr/bin/python3() [0x50aa7d]
frame #25: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #26: /usr/bin/python3() [0x508245]
frame #27: /usr/bin/python3() [0x50a080]
frame #28: /usr/bin/python3() [0x50aa7d]
frame #29: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #30: /usr/bin/python3() [0x509d48]
frame #31: /usr/bin/python3() [0x50aa7d]
frame #32: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #33: /usr/bin/python3() [0x508245]
frame #34: PyEval_EvalCode + 0x23 (0x50b403 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x635222]
frame #36: PyRun_FileExFlags + 0x97 (0x6352d7 in /usr/bin/python3)
frame #37: PyRun_SimpleFileExFlags + 0x17f (0x638a8f in /usr/bin/python3)
frame #38: Py_Main + 0x591 (0x639631 in /usr/bin/python3)
frame #39: main + 0xe0 (0x4b0f40 in /usr/bin/python3)
frame #40: __libc_start_main + 0xe7 (0x7f6783c12b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #41: _start + 0x2a (0x5b2fda in /usr/bin/python3)
```

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 440.59
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect

**Comment by suo** [comment]
Thanks for the report! This happens if we generate a malformed operator schema; it would be helpful if you could post a script we can use to reproduce you're issue so we can track it down. Thanks!

**Comment by Randl** [comment]
I happens when I try to write graph to tensorboard. I'll try to create reproducible example l

**Comment by xsacha** [comment]
I got this same error when trying to trace a module that had DataParallel applied to it. Removing DataParallel fixed it.

**Comment by catscanner210** [comment]
> I got this same error when trying to trace a module that had DataParallel applied to it. Removing DataParallel fixed it.

me too,  remove nn.DataParallel(net) fix it, but why

**Comment by catscanner210** [comment]
same issue here, it seems that it's nn.DataParallel is not working with torch.utils.tensorboard SummaryWriter

python 3.7
torch 1.4.0
torchvision 0.5.0

> hasSpecialCase INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case. (analyzeImpl at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f53c7c3d193 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
> frame #1: <unknown function> + 0x410926b (0x7f52e33d026b in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #2: <unknown function> + 0x410afc0 (0x7f52e33d1fc0 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #3: torch::jit::AliasDb::AliasDb(std::shared_ptr<torch::jit::Graph>) + 0x215 (0x7f52e33d2265 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #4: torch::jit::EliminateDeadCode(std::shared_ptr<torch::jit::Graph> const&, torch::jit::DCESideEffectPolicy) + 0x5e (0x7f52e340a32e in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #5: <unknown function> + 0x4157a4b (0x7f52e341ea4b in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #6: torch::jit::FixupTraceScopeBlocks(std::shared_ptr<torch::jit::Graph>&, torch::jit::script::Module*) + 0x38b (0x7f52e3421e3b in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #7: torch::jit::tracer::trace(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::function<std::vector<c10::IValue, std::allocator<c10::IValue> > (std::vector<c10::IValue, std::allocator<c10::IValue> >)> const&, std::function<std::string (at::Tensor const&)>, bool, torch::jit::script::Module*) + 0x5a6 (0x7f52e35deaa6 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #8: <unknown function> + 0x759091 (0x7f53c8d1d091 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #9: <unknown function> + 0x7728e2 (0x7f53c8d368e2 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #10: <unknown function> + 0x295a74 (0x7f53c8859a74 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> <omitting python frames>
> frame #36: __libc_start_main + 0xf5 (0x7f53d31b8505 in /lib64/libc.so.6)
> 
> Error occurs, No graph saved
> Traceback (most recent call last):
>   File "train.py", line 233, in <module>
>     train()
>   File "train.py", line 57, in train
>     writer.add_graph(net,fake_images)
>   File "/home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 707, in add_graph
>     self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
>   File "/home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 291, in graph
>     raise e
>   File "/home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 285, in graph
>     trace = torch.jit.trace(model, args)
>   File "/home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/jit/__init__.py", line 882, in trace
>     check_tolerance, _force_outplace, _module_class)
>   File "/home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/jit/__init__.py", line 1034, in trace_module
>     module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
> RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case. (analyzeImpl at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f53c7c3d193 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
> frame #1: <unknown function> + 0x410926b (0x7f52e33d026b in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #2: <unknown function> + 0x410afc0 (0x7f52e33d1fc0 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #3: torch::jit::AliasDb::AliasDb(std::shared_ptr<torch::jit::Graph>) + 0x215 (0x7f52e33d2265 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #4: torch::jit::EliminateDeadCode(std::shared_ptr<torch::jit::Graph> const&, torch::jit::DCESideEffectPolicy) + 0x5e (0x7f52e340a32e in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #5: <unknown function> + 0x4157a4b (0x7f52e341ea4b in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #6: torch::jit::FixupTraceScopeBlocks(std::shared_ptr<torch::jit::Graph>&, torch::jit::script::Module*) + 0x38b (0x7f52e3421e3b in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #7: torch::jit::tracer::trace(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::function<std::vector<c10::IValue, std::allocator<c10::IValue> > (std::vector<c10::IValue, std::allocator<c10::IValue> >)> const&, std::function<std::string (at::Tensor const&)>, bool, torch::jit::script::Module*) + 0x5a6 (0x7f52e35deaa6 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #8: <unknown function> + 0x759091 (0x7f53c8d1d091 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #9: <unknown function> + 0x7728e2 (0x7f53c8d368e2 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #10: <unknown function> + 0x295a74 (0x7f53c8859a74 in /home/alex/miniconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> <omitting python frames>
> frame #36: __libc_start_main + 0xf5 (0x7f53d31b8505 in /lib64/libc.so.6)

**Comment by wanxinzzz** [comment]
> same issue here, it seems that torch.utils.tensorboard SummaryWriter add_graph is not working with nn.DataParallel model
> 
> ```
> parallel_model = nn.DataParallel(model)
> writer = SummaryWriter(log_dir)
> # writer.add_graph(parallel_model,dummy_images)
> ```
> 
> I have to comment out the third line to make parallel trainning working.
> 
> python 3.7
> torch 1.4.0
> torchvision 0.5.0
> 
> > hasSpecialCase INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case. (analyzeImpl at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300)

For me, this issues could simply solve by
```
parallel_model = nn.DataParallel(model)
writer = SummaryWriter(log_dir)
writer.add_graph(parallel_model.module,dummy_images)
```

**Comment by ruguowoshiyu** [comment]
> I got this same error when trying to trace a module that had DataParallel applied to it. Removing DataParallel fixed it.
thanks a lot, it worked

**Comment by gemfield** [comment]
@wanxinzzz Same issue, and in https://github.com/DeepVAC/deepvac we use exactly the same workaround.

**Comment by CorentinJ** [comment]
Getting the same issue, but not with a DataParallel model... It's a sequence to sequence model, and there's a tensor that always produce this error whatever is the operation I do to it.

**Comment by Coderx7** [comment]
I faced the same error when trying to trace a model and save the jit version. 
It was caused by the use the now infamous DataParallel! 
I simply used `model.module` instead of model and problem solved: 
```
     ...
    model_traced = torch.jit.trace(model.module, dummy_input)
    torch.jit.save(model_traced, save_path)
```

**Comment by MainJackson** [comment]
> I faced the same error when trying to trace a model and save the jit version.
> It was caused by the use the now infamous DataParallel!
> I simply used `model.module` instead of model and problem solved:
> 
> ```
> ...
> model_traced = torch.jit.trace(model.module, dummy_input)
> torch.jit.save(model_traced, save_path)
> ```
@Coderx7 hello,I just want to know where you edit in code?which file?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
