### ISSUE TITLE
Raspberry Pi Zero build fails

### ISSUE THREAD

**Issue by baqwas** [pytorch/pytorch#35234]
## 🐛 Bug

Cannot build from source on Raspberry Pi Zero 1.3

## To Reproduce

1. Install prequisite packages
2. Clone GitHub respository to local folder
3. Export flags for build
```
export USE_CUDA=OFF
export USE_DISTRIBUTED=OFF
export USE_MKLDNN=OFF
export USE_NNPACK=OFF
export USE_QNNPACK=OFF
```
4. Ran the following command from the source folder:
`python3 setup.py build`

Encountered the following error message at the 12% mark when:
```
[ 12%] Building C object confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/threadpool-pthreads.c.o
In file included from /home/pi/projects/pytorch/build/confu-srcs/pthreadpool/src/threadpool-pthreads.c:35:
/home/pi/projects/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_t function,
```

```
/tmp/ccAfk6Hs.s:2530: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
make[2]: *** [confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/build.make:76: confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/threadpool-pthreads.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:517: confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "/home/pi/projects/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)

```
## Expected behavior

Build should completion should be 100%.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
```
pi@raspbari3:~/projects/pytorch $ python3 collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Raspbian GNU/Linux 10 (buster)
GCC version: (Raspbian 8.3.0-6+rpi1) 8.3.0
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[conda] Could not collect
```

You can get the script and run it with:
```

```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): Raspbian (Debian) Buster
 - How you installed PyTorch (source): **git clone**
 - Build command you used (if compiling from source):
 - Python version: **python3**
 - CUDA/cuDNN version: **None**
 - GPU models and configuration: **None**
 - Any other relevant information:

**Comment by baqwas** [comment]
Hello!
After reading other notes in this forum, I ran the following commands and repeated the build command:

```
git submodule update --remote third_party/protobuf
git submodule update --init –-recursive
```

The error message now is different, as follows:
```
[  9%] Linking CXX executable ../../../bin/protoc
/usr/bin/ld: ../../../lib/libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text+0x24): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [third_party/protobuf/cmake/CMakeFiles/protoc.dir/build.make:87: bin/protoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: third_party/protobuf/cmake/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "/home/pi/projects/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/pi/projects/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/pi/projects/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '1']' returned non-zero exit status 2.
```
Please advise (perhaps some flag or setting is incorrect at my end). Much appreciated.

Kind regards.

**Comment by baqwas** [comment]
Also, cannot build using pip:
```
$ sudo python3 -m pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.4.0+cpu
  Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch==1.4.0+cpu
$ 
```
