### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by dublinsky** [pytorch/pytorch#3527]
hello, I install the latest anaconda and follow the guide of code compilation steps showing on the github page, but frequently get the same error /libTH.so.1: undefined symbol: convolve_5x5_sse. 
then I checkout the previous branch, named as origin/autograd_debug, this time the compilation is successful, I install it, but the code test is still frustrating, the libTH.so.1 still has the same error.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/j/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/j/anaconda2/lib/python2.7/site-packages/torch/lib/libTH.so.1: undefined symbol: convolve_5x5_sse
>>> 
call for help!

**Comment by dublinsky** [comment]
I have checkout the distribution v0.1.9, and recompile the code of this branch, pytorch acts correctly this time.

**Comment by soumith** [comment]
@dublinsky how are ou getting the latest version of pytorch? did you do:

```
git clone --recursive https://github.com/pytorch/pytorch
```

Because libTH.so.1 is no longer built, so you must be on some old version.

**Comment by SsnL** [comment]
The compile steps probably have changed since 0.1.9 days...

**Comment by m-dp** [comment]
Same problem: 
to install, 
```
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" 
conda install numpy pyyaml mkl setuptools cmake cffi
conda install -c soumith magma-cuda80
git clone --recursive https://github.com/pytorch/pytorch 

python setup.py install
```
as per the instructions at https://github.com/pytorch/pytorch#from-source

Results: 
```
../libATen.so.1: undefined reference to `convolve_5x5_sse'
collect2: error: ld returned 1 exit status
src/ATen/test/CMakeFiles/basic.dir/build.make:114: recipe for target 'src/ATen/test/basic' failed
make[2]: *** [src/ATen/test/basic] Error 1
CMakeFiles/Makefile2:338: recipe for target 'src/ATen/test/CMakeFiles/basic.dir/all' failed
make[1]: *** [src/ATen/test/CMakeFiles/basic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../libATen.so.1: undefined reference to `convolve_5x5_sse'
collect2: error: ld returned 1 exit status
src/ATen/test/CMakeFiles/undefined_tensor_test.dir/build.make:114: recipe for target 'src/ATen/test/undefined_tensor_test' failed
make[2]: *** [src/ATen/test/undefined_tensor_test] Error 1
CMakeFiles/Makefile2:264: recipe for target 'src/ATen/test/CMakeFiles/undefined_tensor_test.dir/all' failed
make[1]: *** [src/ATen/test/CMakeFiles/undefined_tensor_test.dir/all] Error 2
../libATen.so.1: undefined reference to `convolve_5x5_sse'
collect2: error: ld returned 1 exit status
src/ATen/test/CMakeFiles/scalar_test.dir/build.make:114: recipe for target 'src/ATen/test/scalar_test' failed
make[2]: *** [src/ATen/test/scalar_test] Error 1
CMakeFiles/Makefile2:375: recipe for target 'src/ATen/test/CMakeFiles/scalar_test.dir/all' failed
make[1]: *** [src/ATen/test/CMakeFiles/scalar_test.dir/all] Error 2
../libATen.so.1: undefined reference to `convolve_5x5_sse'
collect2: error: ld returned 1 exit status
src/ATen/test/CMakeFiles/scalar_tensor_test.dir/build.make:114: recipe for target 'src/ATen/test/scalar_tensor_test' failed
make[2]: *** [src/ATen/test/scalar_tensor_test] Error 1
CMakeFiles/Makefile2:301: recipe for target 'src/ATen/test/CMakeFiles/scalar_tensor_test.dir/all' failed
make[1]: *** [src/ATen/test/CMakeFiles/scalar_tensor_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/5371
