### ISSUE TITLE
ONNX export support for sparse tensors

### ISSUE THREAD

**Issue by rdv0011** [pytorch/pytorch#35294]
## 🐛 Bug

ONNX converter fails because of RuntimeError

## To Reproduce

1. Run convert2ONNX.py

```bash
RuntimeError: sparse tensors do not have is_contiguous (is_contiguous at /Users/distiller/project/conda/conda-bld/pytorch_1579025983502/work/aten/src/ATen/SparseTensorImpl.cpp:55)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x105bed267 in libc10.dylib)
frame #1: at::SparseTensorImpl::is_contiguous(c10::MemoryFormat) const + 456 (0x107a1a328 in libtorch.dylib)
frame #2: at::native::contiguous(at::Tensor const&, c10::MemoryFormat) + 42 (0x107e19a0a in libtorch.dylib)
frame #3: at::TypeDefault::contiguous(at::Tensor const&, c10::MemoryFormat) + 112 (0x1081ed5b0 in libtorch.dylib)
frame #4: torch::autograd::VariableType::(anonymous namespace)::contiguous(at::Tensor const&, c10::MemoryFormat) + 970 (0x10a5f8a7a in libtorch.dylib)
frame #5: c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, c10::MemoryFormat), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, c10::MemoryFormat> >, at::Tensor (at::Tensor const&, c10::MemoryFormat)>::call(c10::OperatorKernel*, at::Tensor const&, c10::MemoryFormat) + 20 (0x10827af44 in libtorch.dylib)
```

## Expected behavior

1. No runtime issues and converted model in ONNX format

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.15.5

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.2
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl_fft                   1.0.6            py35hb8a8100_0  
[conda] mkl_random                1.0.1            py35h5d10147_1  
[conda] pytorch                   1.4.0                   py3.5_0    pytorch
[conda] torchvision               0.5.0                  py35_cpu    pytorch
```

 ## Additional context

The reason might be that the constructor ```GraphEncoder::EncodeTensor()``` tries to call not implemented function ```SparseTensorImpl::is_contiguous(at::MemoryFormat)```.
Why it happens is explained in the comment:
```
   // Add a buffer to the raw_data_export_map for the caller to dump into an
   // external data store. If external_ref is not specified, we instead dump
   // the contiguous data into the protobuf itself
   if (defer_weight_export_ && external_ref) {
```
Since either```external_ref``` or ```defer_weight_export_``` is not set it goes that way.
Also it might be logically correct to assume that it is a design issue because it stops on assert:
```
AT_ASSERT(t.is_contiguous());
```
The follow up question is why ```GraphEncoder::EncodeTensor()``` is used to serialise a sparse tensor.

**UPDATE 2**
I have to modify an original model to replace a native function which is not traceable with a symbolic one:
 ```python
    @staticmethod
    def symbolic(g, W, x):
        y = g.op("MatMul", W, x)
        return y
```
According to the comment one of the arguments of this function is sparse. The other one is probably not: def forward(ctx, W, x):  # W is SPARSE
I guess ```y = g.op("MatMul", W, x)``` does not accept W as sparse.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/969340>

**Comment by Magnusgaertner** [comment]
Hi, i have difficulties understanding what this issue is about - 

I created a minimal example of torch.onnx.export that tries to export a Module which uses torch.sparse (the content does not make much sense): 

```python
#!python3

import torch
import torch.onnx
import torch.sparse
from torch.nn import Module

class SparseModel(Module):

    def __init__(self):
        super(SparseModel, self).__init__()
        i = [[0, ],
             [0, ]]
        v = [42, ]
        self.s = torch.sparse_coo_tensor(i, v, (1, 1))

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return self.s.to_dense() # works if we change the output to "return input" (no usage of sparse tensors)

model = SparseModel()
model.eval()

input_dummy = torch.randn(1, 60, 60, 1, requires_grad=False)
model_out_dummy = model(input_dummy)

model_path = 'model.py'
torch.onnx.export(model, input_dummy, f=model_path, export_params=True, opset_version=14,
                  do_constant_folding=False, input_names=['input'], output_names=['output'])
```
which fails as follows: 

<details>
  <summary>Traceback (click to expand): </summary>
  
```python
Traceback (most recent call last):
  File "interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-2aa0834f0ef2>", line 25, in <module>
    torch.onnx.export(model, input_dummy, f=model_path, export_params=True, opset_version=14,
  File "venv_dev/lib/python3.8/site-packages/torch/onnx/__init__.py", line 321, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "venv_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 134, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "venv_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 746, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "venv_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 520, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "venv_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 464, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "venv_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 415, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "venv_dev/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "venv_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "venv_dev/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "venv_dev/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "venv_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "venv_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "<ipython-input-13-2aa0834f0ef2>", line 16, in forward
    return self.s.to_dense()
RuntimeError: Unsupported value kind: Tensor
```
</details>

Is this the right issue-thread for this minimal, failing example? 
Is there any workarounds to use onnx together with torch.sparse?

Best, 
Magnus

**Comment by ykk648** [comment]
[msdata.visualstudio.com/Vienna/_workitems/edit/969340](https://msdata.visualstudio.com/Vienna/_workitems/edit/969340) access fail

`401 - Uh-oh, you do not have access.
Your account, ykk648@hotmail.com is not authorized to view this page. Make sure the URL is correct and your account has access. View a list of your organizations [here](https://go.microsoft.com/fwlink/?LinkId=309329). You may request access by contacting the admin.
2022/8/9 1:50:45 (UTC)
4a051391-4581-4281-b623-d32fdf40105e
`

**Comment by lh-13** [comment]
Have you solved it? @rdv0011 @ykk648

**Comment by sandeepnmenon** [comment]
This is really important for 3D models. Is this fix in the roadmap?

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` does not support sparse tensors and there is no plan to support it

`torch.onnx.dynamo_export` is the latest exporter and it is currently working to have sparse tensors supported - hopefully in a few weeks.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by tuanavu** [comment]
Hey @thiagocrepaldi, do you know if `torch.onnx.dynamo_export` support convert `sparse_coo_tensor` to ONNX. Based on the official doc here, it is not supported yet: https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html
