### ISSUE TITLE
indexing operator `[]` inconsistent

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#3531]
In the following code, some of the assignments assign `7` to some of the `a` elements, and some dont. It is not obvious to me which will work, and which will fail, without trying them. In addition, there is no indication (eg Exception or similar) when I try an assigment that has failed.

```
import torch
import numpy as np
from torch import nn
from torch.autograd import Variable


a = torch.rand(5, 4)
idxes = torch.LongTensor([0, 2])
idxes2 = torch.LongTensor([0])
a[idxes] = 5
print('a', a)  # works

a = torch.rand(5, 4)
a[idxes].fill_(5)  # doesnt work...
print('a', a)

a = torch.rand(5, 4)
a[idxes][idxes2] = 7  # doesnt work
print('a', a)

a = torch.rand(5, 4)
a[:, :2][idxes] = 7  # works
print('a', a)

a = torch.rand(5, 4)
a[:3][idxes] = 7  # works
print('a', a)

a = torch.rand(5, 4)
a[idxes][:, 1] = 7  # doesnt work
print('a', a)

a = torch.rand(5, 4)
a[:, 1][idxes] = 7  # works
print('a', a)

a = torch.rand(5, 4)
a[:, 1:2][idxes] = torch.FloatTensor(2, 1).fill_(7)  # works
print('a', a)

a = torch.rand(5, 4)
a[idxes][:, 1:2] = torch.FloatTensor(2, 1).fill_(7)  # doesnt work
print('a', a)

a = torch.rand(5, 4)
a[idxes][:, 1] = torch.FloatTensor(2).fill_(7)  # doesnt work
print('a', a)

a = torch.rand(5, 4)
a[:, 1][idxes] = torch.FloatTensor(2).fill_(7)  # works
print('a', a)
```

Output:
```
a 
 5.0000  5.0000  5.0000  5.0000
 0.6669  0.7807  0.0194  0.5675
 5.0000  5.0000  5.0000  5.0000
 0.4356  0.6602  0.6314  0.1092
 0.2036  0.2000  0.9816  0.8419
[torch.FloatTensor of size 5x4]

a 
 0.3230  0.4947  0.9506  0.0903
 0.9365  0.6267  0.2055  0.5788
 0.0463  0.6830  0.7359  0.4857
 0.6834  0.6994  0.3476  0.7177
 0.2500  0.0212  0.2585  0.4837
[torch.FloatTensor of size 5x4]

a 
 0.1980  0.7275  0.6299  0.9513
 0.4572  0.7067  0.0579  0.1477
 0.5097  0.1671  0.6404  0.7760
 0.4492  0.4818  0.1498  0.8576
 0.2303  0.6345  0.6970  0.5469
[torch.FloatTensor of size 5x4]

a 
 7.0000  7.0000  0.4355  0.4932
 0.4353  0.6230  0.5347  0.6431
 7.0000  7.0000  0.1284  0.1781
 0.0731  0.6473  0.7768  0.8538
 0.9966  0.4716  0.2759  0.9330
[torch.FloatTensor of size 5x4]

a 
 7.0000  7.0000  7.0000  7.0000
 0.0324  0.4269  0.8712  0.8241
 7.0000  7.0000  7.0000  7.0000
 0.3683  0.1049  0.5597  0.4110
 0.6722  0.0703  0.5564  0.3533
[torch.FloatTensor of size 5x4]

a 
 0.0015  0.8867  0.4910  0.9876
 0.7295  0.9467  0.1075  0.4583
 0.5853  0.3886  0.4904  0.0028
 0.3870  0.8603  0.1500  0.9434
 0.2598  0.2121  0.9444  0.0043
[torch.FloatTensor of size 5x4]

a 
 0.4600  7.0000  0.3556  0.6450
 0.1235  0.3156  0.5313  0.3157
 0.0833  7.0000  0.1210  0.0142
 0.4484  0.0013  0.3783  0.6595
 0.2480  0.2504  0.8774  0.0878
[torch.FloatTensor of size 5x4]

a 
 0.1780  7.0000  0.3915  0.0832
 0.1211  0.8207  0.4420  0.6502
 0.4522  7.0000  0.9128  0.6761
 0.7840  0.0848  0.5557  0.2763
 0.7523  0.9910  0.2690  0.9558
[torch.FloatTensor of size 5x4]

a 
 0.7608  0.1659  0.2132  0.8333
 0.0869  0.8376  0.9227  0.2002
 0.1625  0.0105  0.9849  0.5148
 0.5452  0.5200  0.5355  0.3178
 0.4197  0.9294  0.4172  0.0469
[torch.FloatTensor of size 5x4]

a 
 0.1802  0.0364  0.0561  0.9782
 0.8888  0.6768  0.7167  0.8842
 0.2234  0.3741  0.8251  0.7813
 0.1033  0.4776  0.5335  0.7562
 0.6567  0.6115  0.0832  0.6691
[torch.FloatTensor of size 5x4]

a 
 0.2363  7.0000  0.7369  0.6097
 0.9366  0.3713  0.3765  0.2912
 0.1712  7.0000  0.0485  0.5060
 0.8131  0.1654  0.5321  0.8097
 0.9726  0.6265  0.1156  0.7550
[torch.FloatTensor of size 5x4]
```

**Comment by apaszke** [comment]
All of this is expected and as far as I know is exactly the same in NumPy and Lua Torch. Basically, there are two kinds of indexing - simple and advanced. Simple are things like adding dimensions, slicing and selecting along dimensions. Advanced indexing is masking and selecting a number of indices. Simple indexing always returns a view, and advanced indexing always returns a tensor that doesn't share memory with the original one.

Now, if you did the indexing in one go (e.g. `a[idxes, 1]` instead of `a[:, 1][idxes]`), then all these examples would work, because `__setitem__` gets called only once and we will sort everything out for you. However, in Python semantics `a[idxes][:, 1] = 1` is no different than this:
```python
__tmp = a[idxes] # NOTE: __tmp doesn't share memory with a!
__tmp[:, 1] = 1
```
We, as a library, only see a single call to `__getitem__` and single call to `__setitem__` and there's no way for us to determine if you did this in a single line, and the result is a temporary, or if it was performed in multiple lines and it's clear what happens.

**Comment by hughperkins** [comment]
It does appear to be consistent with numpy. I find it extremely bug-prone. I think it would be safer to have two operators, like, maybe by default it always does advanced indexing, but if you want the view, then you'd do something specific like `indexed_view()`. This would then crash out with an exception if the requested view is impossible.

**Comment by hughperkins** [comment]
(but anyway, is it fair to say that, in every case, using a LongTensor for indexing will *never* return a view?)

**Comment by hughperkins** [comment]
actually ... `a[indxes, 1]` doesnt work for me?

```
a = torch.rand(5, 4)
a[idxes, 1] = 7
print('a', a)
```

gives:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 61, in <module>
    a[idxes, 1] = 7
TypeError: indexing a tensor with an object of type torch.LongTensor. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.
```

**Comment by apaszke** [comment]
This works fine for me. Yes, indexing with a list of indices will never return a view (even if they form a consecutive range). What's your PyTorch version?

**Comment by hughperkins** [comment]
> Yes, indexing with a list of indices will never return a view (even if they form a consecutive range)

Ok, understood.

> This works fine for me.
> What's your PyTorch version?
```
(root) ~ $ cat /tmp/test3.py
import torch

idxes = torch.LongTensor([0, 2])
a = torch.rand(5, 4)
a[idxes, 1:2] = 7  # gives exception
print('a', a)
(root) ~ $ python /tmp/test3.py
Traceback (most recent call last):
  File "/tmp/test3.py", line 5, in <module>
    a[idxes, 1:2] = 7  # gives exception
TypeError: indexing a tensor with an object of type torch.LongTensor. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.
(root) ~ $ conda list | grep sou
pytorch                   0.2.0                py36_1cu75    soumith
torchvision               0.1.9                    py36_1    soumith
```
