### ISSUE TITLE
MacOS Error: subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by jonsaadfalcon** [pytorch/pytorch#35414]
When trying to install Pytorch from source with CUDA enabled, I get the following error after running the last command in the set of instructions for installation (https://github.com/pytorch/pytorch#from-source). 

ninja: error: '/usr/local/cuda/lib/libnvToolsExt.dylib', needed by 'lib/libtorch_cuda.dylib', missing and no known rule to make it
Traceback (most recent call last):
  File "setup.py", line 745, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/Users/jonsaadfalcon/Documents/PoloClub Research/AdversarialProject/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/Users/jonsaadfalcon/Documents/PoloClub Research/AdversarialProject/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/Users/jonsaadfalcon/Documents/PoloClub Research/AdversarialProject/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/jonsaadfalcon/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 1.

The previously solved issues for this problem were on Windows so idk how to solve it on MacOS. Thank you for the help.

**Comment by ikasou** [comment]
Just sorted this out myself. You are missing libnvToolsExt.dylib. This used to exist in the standard lib directory of the cuda toolkits until cuda-10.0 . For some reason it doesn't exist for cuda-10.2, so I sym-linked to an older version of the cuda toolkit I had installed (namely the 10.0).

**Comment by fbarulli** [comment]
@ikasou 
Im having the same issue, can you please provide more instructions on how to do this?

cheers

**Comment by kadir-gunel** [comment]
@fbarulli  the solution is to install cuda 10.0 and system link it to the pytorch installation. So that the installation script will be able to see the missing dynamic lib. 
It does not matter if you have cuda version 10.2, just download cuda 10.0. Different cuda version can live together.

**Comment by malfet** [comment]
Closing as won't-fix: Intel (x86) macOS is no longer supported — PyTorch no longer ships x86-64 macOS binaries, and these old macOS/toolchain configurations (e.g. OS X 10.13, pre-AVX x86 builds) are EOL. If you hit an issue on Apple Silicon with a current release, please open a new report.
