### ISSUE TITLE
ONNX export failed on ATen operator quantized_lstm

### ISSUE THREAD

**Issue by jmccauley-nx** [pytorch/pytorch#35536]
## 🐛 Bug

Exporting dynamically-quantized LSTM model from [tutorial](https://pytorch.org/tutorials/advanced/dynamic_quantization_tutorial.html) fails.

## To Reproduce

1. Follow the Dynamic Quantization on an LSTM word language model tutorial [steps](https://pytorch.org/tutorials/advanced/dynamic_quantization_tutorial.html)
2. Once this works, add the following line to the bottom of the file:

`
torch.onnx.export(quantized_model, (input_, hidden), "lstm_quantized.onnx", verbose=True)
`

This produces the following error:
`
/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator quantized_lstm because torch.onnx.symbolic_opset9.quantized_lstm does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "lstm.py", line 286, in <module>
    torch.onnx.export(quantized_model, (input_, hidden), model_onnx_path, verbose=True)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 656, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/jmpy/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'quantized_lstm'
`

## Expected behavior

ONNX model should be generated

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0               py3.7_cpu_0  [cpuonly]  pytorch
[conda] torchvision               0.5.0                  py37_cpu  [cpuonly]  pytorch
```
## Additional context

Running on a VM

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1682084>
