### ISSUE TITLE
After quantization, torchvision's resnet18 report error when forward

### ISSUE THREAD

**Issue by whl287** [pytorch/pytorch#35595]
## 🐛 Bug
After quantization, torchvision's resnet18 report error when forward:
<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not run 'aten::add_.Tensor' with arguments from the 'QuantizedCPUTensorId' backend. 'aten::add_.Tensor' is only available for these backends: [CUDATensorId, SparseCPUTensorId, VariableTensorId, CPUTensorId, MkldnnCPUTensorId, SparseCUDATensorId].
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/huawei/.conda/envs/py35/lib/python3.5/site-packages/torchvision/models/resnet.py", line 216
    def forward(self, x):
        return self._forward_impl(x)
               ~~~~~~~~~~~~~~~~~~ <--- HERE
Serialized   File "code/__torch__/torchvision/models/resnet.py", line 21
  def forward(self: __torch__.torchvision.models.resnet.ResNet,
    x: Tensor) -> Tensor:
    return (self)._forward_impl(x, )
            ~~~~~~~~~~~~~~~~~~~ <--- HERE
  def _forward_impl(self: __torch__.torchvision.models.resnet.ResNet,
    x: Tensor) -> Tensor:
Serialized   File "code/__torch__/torchvision/models/resnet.py", line 28, in _forward_impl
    x2 = (self.relu).forward(x1, )
    x3 = (self.maxpool).forward(x2, )
    x4 = (self.layer1).forward(x3, )
          ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    x5 = (self.layer2).forward(x4, )
    x6 = (self.layer3).forward(x5, )
  File "/home/huawei/.conda/envs/py35/lib/python3.5/site-packages/torch/nn/modules/container.py", line 100
    def forward(self, input):
        for module in self:
            input = module(input)
                    ~~~~~~ <--- HERE
        return input
Serialized   File "code/__torch__/torch/nn/modules/container.py", line 11, in forward
    _0 = getattr(self, "0")
    _1 = getattr(self, "1")
    input0 = (_0).forward(input, )
              ~~~~~~~~~~~ <--- HERE
    return (_1).forward(input0, )
Serialized   File "code/__torch__/torchvision/models/resnet.py", line 52, in forward
    out3 = (self.bn2).forward(out2, )
    out4 = torch.add_(out3, x, alpha=1)
    return (self.relu).forward(out4, )
            ~~~~~~~~~~~~~~~~~~ <--- HERE
  File "/home/huawei/.conda/envs/py35/lib/python3.5/site-packages/torchvision/models/resnet.py", line 70
            identity = self.downsample(x)

        out += identity
        ~~~~~~~~~~~~~~~ <--- HERE
        out = self.relu(out)
Serialized   File "code/__torch__/torchvision/models/resnet.py", line 51, in forward
    out2 = (self.conv2).forward(out1, )
    out3 = (self.bn2).forward(out2, )
    out4 = torch.add_(out3, x, alpha=1)
           ~~~~~~~~~~ <--- HERE
    return (self.relu).forward(out4, )

</pre>
## To Reproduce

Steps to reproduce the behavior:

1.
1.
1.

<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): <b>1.4.0</b>
 - OS (e.g., Linux): <b>Linux</b>
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.5
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->


cc @fmassa @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by z-a-f** [comment]
Are you using the model from `torchvision.models` or from `torchvision.models.quantization`? The "quantizable" models are located here: https://github.com/pytorch/vision/tree/master/torchvision/models/quantization

**Comment by raghuramank100** [comment]
From the logs, it looks like you are not using functionalmodules for add, please see this code for info on how to use it:
https://github.com/pytorch/vision/blob/master/torchvision/models/quantization/resnet.py#L41

Also, since question is better answered in the pytorch forums, so closing this issue.
