### ISSUE TITLE
cuda runtime error (802) : system not yet initialized .../THCGeneral.cpp:50

### ISSUE THREAD

**Issue by pherrusa7** [pytorch/pytorch#35710]
Dear all,

After installing Pytorch successfully, it fails when trying to see current devices, hence I can't use the GPUs:

```
conda create -n myenv
conda activate myenv
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
python
import torch
torch.cuda.current_device()
```
Then, the following error appears:
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCGeneral.cpp line=50 error=802 : system not yet initialized
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/iarai/home/pedro.herruzo/.conda/envs/qwe2/lib/python3.6/site-packages/torch/cuda/__init__.py", line 377, in current_device
    _lazy_init()
  File "/iarai/home/pedro.herruzo/.conda/envs/qwe2/lib/python3.6/site-packages/torch/cuda/__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (802) : system not yet initialized at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCGeneral.cpp:50
```
The GPU is the following:
```
nvidia-smi
Mon Mar 30 23:17:07 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM3...  On   | 00000000:1E:00.0 Off |                    0 |
| N/A   37C    P0    31W / 350W |      0MiB / 32510MiB |      0%      Default |
```
However, it works perfectly in the following gpu in a different machine:
```
nvidia-smi
Mon Mar 30 23:22:17 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:1B:00.0 Off |                    0 |
| N/A   41C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
```
And also in this one:
```
nvidia-smi
Mon Mar 30 23:24:31 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:1B:00.0 Off |                    0 |
| N/A   43C    P0    28W / 250W |     12MiB / 32510MiB |      0%      Default |
```
I tried to find a solution with no luck, hopefully, someone can help with this issue.

cc @ngimel

**Comment by ailzhang** [comment]
It looks like GPU is not properly found in the first machine? Did you try to compile something in CUDA examples just to make sure it works? https://github.com/NVIDIA/cuda-samples

**Comment by pherrusa7** [comment]
Thanks for the suggestion @ailzhang, run the examples was the key!

running `bandwidthTest` we got the following:

```
[CUDA Bandwidth Test] - Starting...
Running on...

cudaGetDeviceProperties returned 802
-> system not yet initialized
CUDA error at bandwidthTest.cu:256 code=802(cudaErrorSystemNotReady) "cudaSetDevice(currentDevice)"
```

We traced the error and found the bit that was missing here: https://www.supermicro.com/support/faqs/faq.cfm?faq=31029

After installing what they say, everything is working! Thanks!

**Comment by BitMindLab** [comment]
https://www.supermicro.com/support/faqs/faq.cfm?faq=31029  is not available now

> Thanks for the suggestion @ailzhang, run the examples was the key!
> 
> running `bandwidthTest` we got the following:
> 
> ```
> [CUDA Bandwidth Test] - Starting...
> Running on...
> 
> cudaGetDeviceProperties returned 802
> -> system not yet initialized
> CUDA error at bandwidthTest.cu:256 code=802(cudaErrorSystemNotReady) "cudaSetDevice(currentDevice)"
> ```
> 
> We traced the error and found the bit that was missing here: https://www.supermicro.com/support/faqs/faq.cfm?faq=31029
> 
> After installing what they say, everything is working! Thanks!

**Comment by lpuglia** [comment]
Note to my future self (and whoever may needs it) here is the full procedure:

if you get the following error using cuda in pytorch:

```
RuntimeError: cuda runtime error (802) : system not yet initialized at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCGeneral.cpp:50
```

try to compile and run one of the samples in:

```
https://github.com/NVIDIA/cuda-samples.git
```

```
git clone https://github.com/NVIDIA/cuda-samples.git
cd repo/cuda-samples/Samples/bandwidthTest
make
./bandwidthTest
```

Note: `nvcc` is going to be located in `/usr/local/cuda/bin`

if you get:

```
> ./bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...

cudaGetDeviceProperties returned 802
-> system not yet initialized
CUDA error at bandwidthTest.cu:256 code=802(cudaErrorSystemNotReady) "cudaSetDevice(currentDevice)" 
```

it means that the Data Center GPU manager is not installed. What you want to do is to install the nvidia DCGM, fetch the repository keys:

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --keyserver-options http-proxy=http://proxy-chain.intel.com:911  --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
```

if you get:
```
>  sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
Executing: /tmp/apt-key-gpghome.qjhmgicscb/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
gpg: requesting key from 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub'
gpg: WARNING: unable to fetch URI https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub: Connection timed out
```

you may need to manually set the proxy:
```
sudo apt-key adv --keyserver-options http-proxy=<PROXY-ADDRESS:PORT>  --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
```

then you can install the repository and the package:

```
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
sudo apt-get install -y datacenter-gpu-manager
```


terminate the host engine:
```
sudo nv-hostengine -t
```

and start the fabricmanager
```
sudo service nvidia-fabricmanager start
```

if you get
```
> sudo service nvidia-fabricmanager start
Failed to start nvidia-fabricmanager.service: Unit nvidia-fabricmanager.service not found.
```

install the fabric manager and start it:
```
sudo apt-get install cuda-drivers-fabricmanager-<version>
sudo service nvidia-fabricmanager start
```

executing the program will now work:

```
> ./bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: NVIDIA A100-SXM4-40GB
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     26.1

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     25.6

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     1152.7

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

as well as pytorch-cuda:

```
> ipython
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
tor
In [2]: torch.cuda.is_available()
Out[2]: True
```

**Comment by schmmd** [comment]
We had the same issue with an A100 machine on CUDA 11.3.  Installing fabric manager addressed it.

**Comment by mrhalyang** [comment]
**centos 7 && A100**
## 1.install DCGM
1. wget https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/datacenter-gpu-manager-2.1.7-1-x86_64.rpm
2. rpm -Uvh datacenter-gpu-manager-2.1.7-1-x86_64.rpm

## 2.install fabricmanager
dnf install -y cuda-drivers-fabricmanager-<version>

**Comment by Dominic-ZZ** [comment]
We had the same problem, but it was fine after the reboot

**Comment by JohnTesla** [comment]
jag@Aigen:~/codes/cuda-samples-master/bin/x86_64/linux/release$ ./bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...
cudaGetDeviceProperties returned 802
-> system not yet initialized
**CUDA error at bandwidthTest.cu:256 code=802(cudaErrorSystemNotReady) "cudaSetDevice(currentDevice)"**

jag@Aigen:~$ sudo systemctl start nvidia-fabricmanager.service
**Job for nvidia-fabricmanager.service failed because the control process exited with error code.**
See "systemctl status nvidia-fabricmanager.service" and "journalctl -xe" for details.

This refference said thai no need to install fabric to PCI-E 1 GPU card [](https://forums.developer.nvidia.com/t/problem-starting-fabricmanager-in-ubuntu-20-04-lts/255215)

**Comment by phifaner** [comment]
I met the same problem, because of contradiction between CUDA driver's version and fabricmanager version.
