### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got -4)

### ISSUE THREAD

**Issue by seerdecker** [pytorch/pytorch#36046]
## 🐛 Bug

The following script triggers a bug with torch.nn.functional.max_pool2d on CUDA. The bug does not trigger on CPU.

## To Reproduce

```
#!/usr/bin/env python3

import os, sys
import numpy as np
import torch

cuda_flag = 1

def numpy_to_torch_var(np_t):
    if cuda_flag: t = torch.from_numpy(np_t).cuda()
    else: t = torch.from_numpy(np_t).clone()
    t.requires_grad = True
    return t

prev_layer = numpy_to_torch_var(np.random.randn(1, 84, 84).astype(np.float32))
prev_layer = torch.nn.functional.max_pool2d(prev_layer, kernel_size=(3, 3))
```
Output is
```
Traceback (most recent call last):
  File "./torch_bug2.py", line 16, in <module>
    prev_layer = torch.nn.functional.max_pool2d(prev_layer, kernel_size=(3, 3))
  File "/home/delta/.local/lib/python3.7/site-packages/torch/_jit_internal.py", line 210, in fn
    return if_false(*args, **kwargs)
  File "/home/delta/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 539, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got -4)
```

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0.dev20200405+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 19.10
GCC version: (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.6.0.dev20200405+cu101
[pip3] torchvision==0.6.0.dev20200405+cu101
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by lufol** [comment]
Works fine on [colab](https://colab.research.google.com/drive/1LE7wjsyq-p54tgC3uB8akJoTJqQo1hxq)

**Comment by lufol** [comment]
Could you try running it with pytorch 1.4.0 ?

**Comment by seerdecker** [comment]
Works fine in 1.4.0. It's the nightly build that fails.

**Comment by zou3519** [comment]
Marked as high-pri for regression

**Comment by ngimel** [comment]
It's this line https://github.com/pytorch/pytorch/blob/82d58ed484eb04f894475de0551055f7e070f481/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu#L361 introduced by #34519. cc @xwang233, maxpool2d can accept 3d tensors, in this case batch dimension is implicitly assumed to be 1.

**Comment by gchanan** [comment]
That PR is in the 1.5 release branch, so we should get a fix in.
