### ISSUE TITLE
RuntimeError CUDA error despite CUDA available and GPU supported

### ISSUE THREAD

**Issue by andmax** [pytorch/pytorch#36062]
Got the following error (on Ubuntu 18.04 with PyTorch 1.14, Nvidia driver version 440.64, CUDA toolkit 10.1, GPU GeForce GTX Titan) despite PyTorch saying CUDA and CUDNN are available:

RuntimeError: CUDA error: no kernel image is available for execution on the device

Script to reproduce:

```
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)
device = torch.device('cuda')
print(torch.cuda.get_device_properties(device))
print(torch.tensor([1.0, 2.0]).cuda())
```

Output:

```
1.4.0
True
True
_CudaDeviceProperties(name='GeForce GTX TITAN', major=3, minor=5, total_memory=6082MB, multi_processor_count=14)
Traceback (most recent call last):
  File "test_pytorch_cuda.py", line 7, in <module>
    print(torch.tensor([1.0, 2.0]).cuda())
  File "/home/deepstation/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/tensor.py", line 159, in __repr__
    return torch._tensor_str._str(self)
  File "/home/deepstation/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/deepstation/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/deepstation/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

cc @ezyang @seemethere @ngimel

**Comment by zou3519** [comment]
The action item here seems to be to improve the error message to be more friendly

**Comment by andmax** [comment]
Or go back at compiling binaries for CUDA architectures 3.0 and up, instead of 3.7 and up as per (starting from) PyTorch 1.3.1.  The following issue has a discussion on this: [31285](https://github.com/pytorch/pytorch/issues/31285).  Ideally, PyTorch should support CUDA architectures matching CUDA toolkit support.  That is if CUDA 10.1 supports compute capability 3.0 and up, and PyTorch is compiled against CUDA 10.1, then PyTorch should also support archs from 3.0 and up.
