### ISSUE TITLE
Cannot convert model to onnx

### ISSUE THREAD

**Issue by stereomatchingkiss** [pytorch/pytorch#36069]
## To Reproduce

1. Clone the project from [github](https://github.com/intel-isl/MiDaS)
2. install pytorch 1.4.0
3. Download the  [model ](https://drive.google.com/file/d/1nqW_Hwj86kslfsXR7EnXpEWdO2csz1cC)and put in into the root folder of the project
4. Create to_onnx.py in the root folder of the project

to_onnx.py

```
import os
import glob
import torch
import utils
import cv2

from torchvision.transforms import Compose
from models.midas_net import MidasNet
from models.transforms import Resize, NormalizeImage, PrepareForNet

import onnx
import onnxruntime

def test_model_accuracy(export_model_name, raw_output, input):    
    ort_session = onnxruntime.InferenceSession(export_model_name)

    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    # compute ONNX Runtime output prediction
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input)}
    ort_outs = ort_session.run(None, ort_inputs)	

    # compare ONNX Runtime and PyTorch results
    np.testing.assert_allclose(to_numpy(raw_output), ort_outs[0], rtol=1e-03, atol=1e-05)

    print("Exported model has been tested with ONNXRuntime, and the result looks good!")		

def export_model(model, input, export_model_name):
    torch.onnx.export(model, input, export_model_name, verbose=False, export_params=True)	
    onnx_model = onnx.load(export_model_name)    
    onnx.checker.check_model(onnx_model)
    graph_output = onnx.helper.printable_graph(onnx_model.graph)
    with open("graph_output.txt", mode="w") as fout:
        fout.write(graph_output)
		
device = torch.device("cpu")

 # load network
model_path = "model.pt"
model = MidasNet(model_path, non_negative=True)

transform = Compose(
        [
            Resize(
                384,
                384,
                resize_target=None,
                keep_aspect_ratio=True,
                ensure_multiple_of=32,
                resize_method="lower_bound",
                image_interpolation_method=cv2.INTER_CUBIC,
            ),
            NormalizeImage(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            PrepareForNet(),
        ]
)

model.to(device)
model.eval()

img = utils.read_image("input/line_up_00.jpg")
img_input = transform({"image": img})["image"]

# compute
#with torch.no_grad():
sample = torch.from_numpy(img_input).to(device).unsqueeze(0)
print("sample type = ", type(sample), ", shape of sample = ", sample.shape)
print(sample)	
prediction = model.forward(sample)

export_model_name = "midas.onnx"	

#encoder_script_module = torch.jit.trace(model, img_input)
#encoder_script_module.save(export_model_name)

export_model(model, img_input, export_model_name)
```

## Expected behavior

The model convert to onnx and pass the accuracy test.

## Real behavior

It give me error messages

**File "to_onnx.py", line 72, in
export_model(model, img_input, export_model_name)
File "to_onnx.py", line 30, in export_model
torch.onnx.export(model, input, export_model_name, verbose=False, export_params=True, opset_version=11)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx_init_.py", line 148, in export
strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 66, in export
dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 416, in _export
fixed_batch_size=fixed_batch_size)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 279, in _model_to_graph
graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\onnx\utils.py", line 236, in _trace_and_get_graph_from_model
trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, return_inputs_states=True)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\jit_init.py", line 277, in _get_trace_graph
outs = ONNXTracedModule(f, _force_outplace, return_inputs, return_inputs_states)(*args, **kwargs)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\modules\module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\jit_init.py", line 332, in forward
in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type numpy.ndarray**

## Environment

[pip] numpy==1.17.5
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] cudatoolkit               10.1.243             h74a9793_0    anaconda
[conda] libblas                   3.8.0                     8_mkl    conda-forge
[conda] libcblas                  3.8.0                     8_mkl    conda-forge
[conda] liblapack                 3.8.0                     8_mkl    conda-forge
[conda] mkl                       2019.5                      281    anaconda
[conda] numpy                     1.17.5           py36hc71023c_0    conda-forge
[conda] pytorch                   1.4.0           py3.6_cuda101_cudnn7_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

## Additional context

The type of the input(img_input) is a tensor, output is a tensor too, not sure why it would give us error messages like that.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by stereomatchingkiss** [comment]
My bad, export_model function do input numpy but not tensor, it should be

`export_model(model, sample, export_model_name)`

instead of

`export_model(model, img_inputv, export_model_name)`

After I change it to sample but not img_input, the error message change to

```
 %1162 : Float(1, 128, 384, 576) = onnx::Upsample[mode="linear"](%1135, %1161) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\functional.py:2530:0
  %1163 : Float(1, 32, 384, 576) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%1162, %scratch.output_conv.2.weight, %scratch.output_conv.2.bias) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\modules\conv.py:342:0
  %1164 : Float(1, 32, 384, 576) = onnx::Relu(%1163) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\functional.py:912:0
  %1165 : Float(1, 1, 384, 576) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%1164, %scratch.output_conv.4.weight, %scratch.output_conv.4.bias) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\modules\conv.py:342:0
  %1166 : Float(1, 1, 384, 576) = onnx::Relu(%1165) # C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\torch\nn\functional.py:912:0
  %1167 : Float(1, 384, 576) = onnx::Squeeze[axes=[1]](%1166) # C:\Users\yyyy\programs\Qt\app_to_simplify_ml\cv_projects\clients\mobile_depth_estimation\MiDaS\models\midas_net.py:76:0
  return (%1167)
```

**Comment by stereomatchingkiss** [comment]
I can convert the model after I change opset to 11.

`torch.onnx.export(model, input, export_model_name, verbose=False, export_params=True, opset_version=11)	`

But the precision test fail

```
export_model(model, sample, export_model_name)
test_model_accuracy(export_model_name, prediction, sample)

```
**Traceback (most recent call last):
  File "to_onnx.py", line 78, in <module>
    test_model_accuracy(export_model_name, prediction, sample)
  File "to_onnx.py", line 26, in test_model_accuracy
    np.testing.assert_allclose(to_numpy(raw_output), ort_outs[0], rtol=1e-03, atol=1e-05)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\numpy\testing\_private\utils.py", line 1548, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Users\yyyy\Anaconda3\envs\torchreid\lib\site-packages\numpy\testing\_private\utils.py", line 861, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 168755 / 221184 (76.3%)
Max absolute difference: 0.28403193
Max relative difference: 810.0278
 x: array([[[0.098411, 0.08588 , 0.086399, ..., 0.02793 , 0.      ,
         0.      ],
        [0.039169, 0.049598, 0.057025, ..., 0.      , 0.      ,...
 y: array([[[0.      , 0.      , 0.      , ..., 0.      , 0.      ,
         0.      ],
        [0.      , 0.      , 0.      , ..., 0.      , 0.      ,...**

**Comment by stereomatchingkiss** [comment]
Not sure why, but export again fix the bug
