### ISSUE TITLE
test_qadd_scalar_relu is failing on pytorch_macos_10_13_py3_test

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36127]
```
Apr 06 22:13:50   test_qadd_relu_same_qparams (__main__.TestQuantizedOps) ... ok (0.008s)
Apr 06 22:13:54   test_qadd_scalar_relu (__main__.TestQuantizedOps) ... Falsifying example: test_qadd_scalar_relu(
Apr 06 22:13:54     self=<__main__.TestQuantizedOps testMethod=test_qadd_scalar_relu>,
Apr 06 22:13:54     A=(array([-418627.78, -500000.38], dtype=float32),
Apr 06 22:13:54      (1960.7857843137256, 255, torch.quint8)),
Apr 06 22:13:54     b=838235.9375,
Apr 06 22:13:54 )
Apr 06 22:13:54 FAIL (4.204s)
Apr 06 22:13:56   test_qclamp (__main__.TestQuantizedOps) ... ok (1.510s)
Apr 06 22:13:57   test_qelu (__main__.TestQuantizedOps) ... ok (0.941s)
Apr 06 22:13:58   test_qhardsigmoid (__main__.TestQuantizedOps) ... ok (0.724s)
Apr 06 22:13:58   test_qmul_broadcast (__main__.TestQuantizedOps) ... ok (0.005s)
Apr 06 22:13:58   test_qmul_relu_different_qparams (__main__.TestQuantizedOps) ... ok (0.008s)
Apr 06 22:14:09   test_qmul_relu_same_qparams (__main__.TestQuantizedOps) ... ok (11.121s)
Apr 06 22:14:09   test_qrelu (__main__.TestQuantizedOps) ... ok (0.545s)
Apr 06 22:14:10   test_qrelu6 (__main__.TestQuantizedOps) ... ok (0.556s)
Apr 06 22:14:11   test_qrelu_leaky (__main__.TestQuantizedOps) ... ok (0.853s)
Apr 06 22:14:12   test_qsigmoid (__main__.TestQuantizedOps) ... ok (1.073s)
Apr 06 22:14:13   test_qtanh (__main__.TestQuantizedOps) ... ok (0.793s)
Apr 06 22:14:13   test_qtopk (__main__.TestQuantizedOps) ... quantization/test_quantized.py:1112: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
Apr 06 22:14:13   indices = torch.tensor(torch.from_numpy(X)).long()
Apr 06 22:14:15 ok (2.559s)
Apr 06 22:14:15   test_qtopk_nhwc (__main__.TestQuantizedOps) ... quantization/test_quantized.py:1138: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
Apr 06 22:14:15   indices = torch.tensor(torch.from_numpy(X)).long()
Apr 06 22:14:19 ok (4.218s)
Apr 06 22:14:19 
Apr 06 22:14:19 ======================================================================
Apr 06 22:14:19 FAIL [4.204s]: test_qadd_scalar_relu (__main__.TestQuantizedOps)
Apr 06 22:14:19 ----------------------------------------------------------------------
Apr 06 22:14:19 Traceback (most recent call last):
Apr 06 22:14:19   File "quantization/test_quantized.py", line 399, in test_qadd_scalar_relu
Apr 06 22:14:19     elements=hu.floats(-1e6, 1e6, allow_nan=False),
Apr 06 22:14:19   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 1090, in wrapped_test
Apr 06 22:14:19     raise the_error_hypothesis_found
Apr 06 22:14:19   File "quantization/test_quantized.py", line 423, in test_qadd_scalar_relu
Apr 06 22:14:19     {} vs {}".format(C_ref.dequantize(), C_hat.dequantize()))
Apr 06 22:14:19   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 894, in assertEqual
Apr 06 22:14:19     assertTensorsEqual(x, y)
Apr 06 22:14:19   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 860, in assertTensorsEqual
Apr 06 22:14:19     self.assertLessEqual(max_err, prec, message)
Apr 06 22:14:19 AssertionError: tensor(3291.0312) not less than or equal to 1e-05 : Scalar add results don't match:   
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by z-a-f** [comment]
I'll take a look

**Comment by andrewor14** [comment]
Closing this since the test doesn't exist anymore
