### ISSUE TITLE
Multiprocessing context not compatible with ProcessPoolExecutor

### ISSUE THREAD

**Issue by zbyte64** [pytorch/pytorch#36156]
## 🐛 Bug

`concurrent.futures.ProcessPoolExecutor` accepts `mp_context` as an argument and the python documents state:

> mp_context: A multiprocessing context to launch the workers. This
                object should provide SimpleQueue, Queue and Process.

However, passing `torch.multiprocessing` as an argument does not work entirely. `ProcessPoolExecutor` is able to run tasks but eventually an error like this will happen:

`RuntimeError: unable to write to file </torch_15_514316460>`

## To Reproduce

1. create an executor with pytorch: `ProcessPoolExecutor(4, mp_context=torch.multiprocessing)`
2. submit tasks that involve tensors as arguments or returns
3. loop enough times to see the error

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/concurrent/futures/process.py", line 205, in _sendback_result
    exception=exception))
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 358, in put
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_13_1503712156>
```

## Expected behavior

`torch.multiprocessing` is expected to be a drop in replacement and should integrate with other python built-ins.

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.4.0
[pip] torch-cluster==1.5.4
[pip] torch-geometric==1.4.3
[pip] torch-scatter==2.0.4
[pip] torch-sparse==0.6.1
[pip] torch-spline-conv==1.2.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.17.4           py37hc1035e2_0  
[conda] numpy-base                1.17.4           py37hde5b4d6_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torch-cluster             1.5.4                    pypi_0    pypi
[conda] torch-geometric           1.4.3                    pypi_0    pypi
[conda] torch-scatter             2.0.4                    pypi_0    pypi
[conda] torch-sparse              0.6.1                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchvision               0.5.0                py37_cu101    pytorch

```
 Built using the pytorch docker image.

## Additional context

On my two machines I only have problems if I set the number of workers to 4 or higher.

**Comment by zbyte64** [comment]
I noticed that `ProcessPoolExecutor` uses a Queue class not derived from the mp_context passed in. Tried to see if swapping it out for one derived from torch.multiprocessing would work -  it did not. Here's the attempt:

https://github.com/zbyte64/pytorch-fuzzdom/blob/179e2375b266cc6868acc6c8476849d1cb06fd98/fuzzdom/process.py

**Comment by zbyte64** [comment]
I think the key to this issue is implementing a pytorch friendly multiprocessing context as seen in here: https://github.com/python/cpython/blob/master/Lib/multiprocessing/context.py

**Comment by zbyte64** [comment]
Real culprit: https://github.com/pytorch/pytorch/issues/2926#issuecomment-364099144l

The issue was running out of shared memory in docker. You can use ProcessPoolExecutor along with asyncio to construct tensors:

```python
        loop = asyncio.get_event_loop()
        v_obs = await loop.run_in_executor(
            executor, state_to_vector, obs, self.prior_actions
        )
```
