### ISSUE TITLE
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/THCGeneral.cpp:313

### ISSUE THREAD

**Issue by nikitamehrotra12** [pytorch/pytorch#36311]
## 🐛 Bug

I am getting  Cuda runtime error while doing binary classification with geometric graph convolutions. I tried running the code with cuda launch blocking and here is the stack track:
```
Traceback (most recent call last):
  File "GeniePathCosLoss100d.py", line 535, in <module>
    loss, predictions= model(x1,edge1_.long(),x2,edge2_.long(),y_)
  File "/home/nikitam/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "GeniePathCosLoss100d.py", line 507, in forward
    op2 = self.geniepath(x2_[:,-1,:],e2)
  File "/home/nikitam/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "GeniePathCosLoss100d.py", line 486, in forward
    x, (h, c) = self.gplayers[i](x, edge_index, h, c)
  File "/home/nikitam/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "GeniePathCosLoss100d.py", line 469, in forward
    x = self.breadth_func(x, edge_index)
  File "/home/nikitam/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "GeniePathCosLoss100d.py", line 447, in forward
    x = self.gatconv(x, edge_index)
  File "/home/nikitam/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "GeniePathCosLoss100d.py", line 302, in forward
    return self.propagate(edge_index, size=size, x=x)
  File "GeniePathCosLoss100d.py", line 194, in propagate
    out = self.message(**msg_kwargs)
  File "GeniePathCosLoss100d.py", line 315, in message
    print("cat",torch.cat([x_i, x_j], dim=2).shape)

```
I tried but I am not able to figure out the reason for the same.

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GeForce RTX 2080 Ti

cc @ngimel

**Comment by zhangguanheng66** [comment]
Need repro

**Comment by nikitamehrotra12** [comment]
here is the link to collab notebook: https://colab.research.google.com/drive/12F5gP8pDyIx60jUO2YQ0JHLT56ps8Wkh
I have added the sample program and a toy dataset to reproduce the above error

**Comment by nikitamehrotra12** [comment]
Its resolved now, there was some index out of bound error.

So closing this issue now.
