### ISSUE TITLE
PyTorch no longer supports this GPU because it is too old.

### ISSUE THREAD

**Issue by Snuffy4** [pytorch/pytorch#36315]
I have installed CUDA ToolKit 8.0
`pip install torch==1.0.1 -f https://download.pytorch.org/whl/cu80/torch_stable.html`
Installed version 1.0.1 for CUDA 8.0 WINDOWS.

An error appears
```
Found GPU0 GeForce GT 630M which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Found 1 GPUs available. Using GPU 0 (GeForce GT 630M) of compute capability 2.1 with 2.1Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Traceback (most recent call last):
  File "demo_cli.py", line 61, in <module>
    encoder.load_model(args.enc_model_fpath)
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\encoder\inference.py", line 32, in load_model
    _model = SpeakerEncoder(_device, torch.device("cpu"))
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\encoder\model.py", line 21, in __init__
    batch_first=True).to(device)
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\nn\modules\rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\nn\modules\rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_ARCH_MISMATCH
```
But Wikipedia says that CUDA 8.0 supports compute capability 2.0 - 6. x, my video card has 2.1 compute capability
![Снимок](https://user-images.githubusercontent.com/44814286/78903490-e173f980-7a83-11ea-9c84-cb3209cbc86e.PNG)

**Comment by peterjc123** [comment]
No, it's the limitation of our repo. We only build binaries for CC 3.5 and up in PyTorch 1.0.1.

**Comment by Snuffy4** [comment]
What should I do? Where to get version 1.0.1 for 2.1

**Comment by peterjc123** [comment]
You could only build from source.

**Comment by Snuffy4** [comment]
How do I compile on Windows?

**Comment by peterjc123** [comment]
Install VS2017 with 14.11 toolchain, VS2015 and CUDA 8, and then type in the following commands.
```
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1

REM As for CUDA 8, VS2015 Update 3 is also required to build PyTorch. Use the following line.
set "CUDAHOSTCXX=%VS140COMNTOOLS%\..\..\VC\bin\amd64\cl.exe"

call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install
```

**Comment by Snuffy4** [comment]
Compilation finished, what does it mean?
```
building 'torch._C' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\torch
creating build\temp.win-amd64-3.7\Release\torch\csrc
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\kisel\anaconda3\envs\TestVoice\include -IC:\Users\kisel\anaconda3\envs\TestVoice\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tptorch/csrc/stub.cpp /Fobuild\temp.win-amd64-3.7\Release\torch/csrc/stub.obj -D_THP_CORE -DONNX_NAMESPACE=onnx_torch /MD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275
cl: командная строка warning D9025: переопределение "/EHs" на "/EHa"
stub.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\pytorch\pytorch\torch\lib "/LIBPATH:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/" /LIBPATH:C:\Users\kisel\anaconda3\envs\TestVoice\libs /LIBPATH:C:\Users\kisel\anaconda3\envs\TestVoice\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" shm.lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-3.7\Release\torch/csrc/stub.obj /OUT:build\lib.win-amd64-3.7\torch\_C.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\torch/csrc\_C.cp37-win_amd64.lib /NODEFAULTLIB:LIBCMT.LIB C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\pytorch\pytorch\torch\lib\caffe2_gpu.lib
LINK : fatal error LNK1181: не удается открыть входной файл "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\pytorch\pytorch\torch\lib\caffe2_gpu.lib"
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\link.exe' failed with exit status 1181
```

**Comment by peterjc123** [comment]
Could you please provide the full log?

**Comment by Snuffy4** [comment]
what file?

**Comment by peterjc123** [comment]
`python setup.py install 2>&1 > build.log` and then share `build.log`.

**Comment by Snuffy4** [comment]
My compilation lasted about 2 hours, should I compile again?

**Comment by peterjc123** [comment]
You can upload that log first. If it is unhelpful, then you may need to do that again.

**Comment by Snuffy4** [comment]
[log.txt](https://github.com/pytorch/pytorch/files/4461496/log.txt)

**Comment by Snuffy4** [comment]
Help me please

**Comment by peterjc123** [comment]
I didn't see any error related to `caffe2_gpu`. Would you please delete the cache, build again and provide the full log?

**Comment by peterjc123** [comment]
Previously I have packages compiled for Kepler cards but they got expired. I have removed VS 2015 and CUDA 8 so it will be complicated for me to install them back to get a single package. BTW, even if the package can be generated, I don't think it will be too useful because 1. cudnn is not supported on your card. 2. According to the specs, your card can only host lightweight workloads, in which cpus may work better.
