### ISSUE TITLE
DISABLED test_check_failed_messages (__main__.FaultyAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#36332]
https://app.circleci.com/pipelines/github/pytorch/pytorch/153028/workflows/c3ba2031-4e43-41d4-8399-c69cd09b49d7/jobs/5100538

```
Apr 09 11:58:38 ======================================================================
Apr 09 11:58:38 ERROR [100.118s]: test_check_failed_messages (__main__.FaultyAgentRpcTestWithSpawn)
Apr 09 11:58:38 ----------------------------------------------------------------------
Apr 09 11:58:38 Traceback (most recent call last):
Apr 09 11:58:38   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Apr 09 11:58:38     self._join_processes(fn)
Apr 09 11:58:38   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 285, in _join_processes
Apr 09 11:58:38     self._check_return_codes(elapsed_time)
Apr 09 11:58:38   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 323, in _check_return_codes
Apr 09 11:58:38     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Apr 09 11:58:38 RuntimeError: Process 1 terminated or timed out after 100.0106930732727 seconds
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
@osalpekar does #36239 fix this issue by any chance?

**Comment by osalpekar** [comment]
Looks like this test is pretty stable since merging https://github.com/pytorch/pytorch/pull/37978, should we close this issue and re-open if we see more failures?

**Comment by pritamdamania87** [comment]
Closing this out since the test seems stable since #37978.
