### ISSUE TITLE
RuntimeError when using DistributedDataParallel

### ISSUE THREAD

**Issue by ray342659093** [pytorch/pytorch#3641]
I tried to use DistributedDataParallel to do distributed training across different machines. However, I got error message below

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 323, in _reduction_thread_fn
    _process_batch()  # just to have a clear scope
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 307, in _process_batch
    nccl.reduce(dev_coalesced, root=0, streams=nccl_streams)
  File "/home/rusu5516/.local/lib/python2.7/site-packages/torch/cuda/nccl.py", line 45, in reduce
    torch._C._nccl_reduce(inputs, outputs, streams, root, op)
RuntimeError: all inputs must have the same number of elements
```
I do not know where these inputs come from and why they do not have the same number of elements. Anyone has clues for this?

**Comment by apaszke** [comment]
There might a bug inside DistributedDataParallel. Can you please share a minimal code example that would let us reproduce this?

**Comment by ray342659093** [comment]
I just run the training of this project https://github.com/yjxiong/tsn-pytorch by changing the DataParallel to DistributedDataParallel and used Distributedsampler as a sampler for DataLoader. I think it is because I used a single gpu in rank 0 machine and two gpus in rank 1 machine. when I only used a single gpu in rank 1 machine, this message wont show up.

**Comment by andrew-yang0722** [comment]
I got the above error message with 0.2.0 version.

When I build pytorch master branch.
No error message. It works well.
Thank you.

**Comment by andrew-yang0722** [comment]
But I got other error message.
I run the code with 32 ranks that is in 2 machine( 8Gpu + 8Gpu)
I am training imagenet classification to check efficiency of distribution.
sometimes It occurs after 16 epoch. and sometimes it occurs in first epoch.


```
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/hanmail/pt/local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 322, in _reduction_thread_fn
    _process_batch()  # just to have a clear scope
  File "/hanmail/pt/local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 315, in _process_batch
    dist.all_reduce(coalesced, group=group_id)
  File "/hanmail/pt/local/lib/python2.7/site-packages/torch/distributed/__init__.py", line 216, in all_reduce
    return torch._C._dist_all_reduce(tensor, op, group)
RuntimeError: [/daum/users/andrew/project/pytorch/torch/lib/gloo/gloo/transport/tcp/buffer.cc:76] Read timeout [10.61.42.72]:3493

Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/hanmail/pt/local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 322, in _reduction_thread_fn
    _process_batch()  # just to have a clear scope
  File "/hanmail/pt/local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 315, in _process_batch
    dist.all_reduce(coalesced, group=group_id)
  File "/hanmail/pt/local/lib/python2.7/site-packages/torch/distributed/__init__.py", line 216, in all_reduce
    return torch._C._dist_all_reduce(tensor, op, group)
RuntimeError: [/daum/users/andrew/project/pytorch/torch/lib/gloo/gloo/transport/tcp/buffer.cc:76] Read timeout [10.61.42.72]:35742
```

**Comment by flauted** [comment]
I encountered this error message when using multiple multi-gpu machines. It did not occur when using a single multi-gpu machine - albeit with DataParallel, not DistributedDataParallel - nor when using multiple single-gpu machines (also didn't occur when using multi-gpu machines with ``CUDA_VISIBLE_DEVICES=1`` on both). I didn't try combinations of single- and multi- gpu as the OP here felt that caused his problem. PyTorch version 0.3.0.post4.

I solved the problem by deleting a ``nn.Linear`` that I assigned to an attribute during the ``__init__`` of a custom ``nn.Module`` but never used during ``forward``.

IMO this case deserves a better error message or should be documented with DistributedDataParallel.

Thanks!

**Comment by minzhouGithub** [comment]
I encountered the same error today! It really confuses me. Now I've solved it thanks to your comment. 
I used the COCO dataset to train a PSPNet-50, which has a auxiliary loss. And when training, the net computed the auxiliary result but I didn't add it to the loss. Then I got this same error. Once I add this auxiliary loss into the total loss, the error disappeared.

**Comment by minzhouGithub** [comment]
I encountered the same error today! It really confuses me. Now I've solved it thanks to your comment. 
I used the COCO dataset to train a PSPNet-50, which has a auxiliary loss. And when training, the net computed the auxiliary result but I didn't add it to the loss. Then I got this same error. Once I add this auxiliary loss into the total loss, the error disappeared.

**Comment by ezyang** [comment]
I'm going to guess that this is fixed, and close it. Please file a new issue if you repro this on a more recent version of PyTorch.
