### ISSUE TITLE
TorchScript doesn't parse floats that are not inf-y.

### ISSUE THREAD

**Issue by erip** [pytorch/pytorch#36432]
## 🐛 Bug

TorchScript should permit non-inf strings to be parsed as floats, but this is currently not permitted.

## To Reproduce

1. `conda install -c pytorch pytorch -y`
1. `python test.py`

##### `test.py`

```python
#!/usr/bin/env python

import torch

def parse_float_from_str(s: str) -> float:
    return float(torch.split(s, "_", -1)[0])

if __name__ == "__main__":
    scripted_f = torch.jit.script(parse_float_from_str)
    print(scripted_f("0_1"))
```

##### Stack Trace

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(scripted_f("0_1"))
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "test.py", line 6, in parse_float_from_str
def parse_float_from_str(s: str) -> float:
    return float(torch.split(s, "_", -1)[0])
           ~~~~~ <--- HERE
RuntimeError: Only 'inf' or '-inf' can be cast to a float, but got '0'
```

## Expected behavior

The above snippet should print `0.0` to the console.

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.17.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[conda] _pytorch_select           0.1                       cpu_0
[conda] blas                      1.0                         mkl
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-service               2.3.0            py36h0b31af3_0    conda-forge
[conda] numpy                     1.18.1           py36hdc5ca10_1    conda-forge
[conda] pytorch                   1.4.0           cpu_py36hf9bb1df_0
```

cc @suo

**Comment by erip** [comment]
It seems this is fixed in nightly, actually.

**Comment by erip** [comment]
I have confirmed this does _not_ working in `v1.5.0-rc3`. Is there any chance of a backport into 1.5.0?

**Comment by eellison** [comment]
@erip you could try resubmitting https://github.com/pytorch/pytorch/pull/35352 to the release branch, I think it's about closed / soon to close though. cc @ailzhang who submitted the PR. 

If it doesnt get in you can register your own operator that implements this as a workaround, although i know that's kind of annoying.

I'm going to close this issue bc as u stated it is fixed on master.

**Comment by erip** [comment]
Cheers, @eellison. Hopefully it makes it in!
