### ISSUE TITLE
Help me PLEASE!!!!! OSError: [WinError 127]

### ISSUE THREAD

**Issue by Snuffy4** [pytorch/pytorch#36460]
PyTorch has compiled for CUDA 8.0, run the script, and now this problem! How many already can be, I several days try to just put your package, and you normally can not help
```
(TestVoice) C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\__init__.py", line 80, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] Не найдена указанная процедура
```

**Comment by mruberry** [comment]
Hey @Snuffy4, sorry to hear you're having a problem! This issue looks more appropriate for our forums, here: https://discuss.pytorch.org/. 

Also, as a sidenote, PyTorch only supports CUDA 9.2+ now.
