### ISSUE TITLE
JIT ONNX: List indexing fails when converting ScriptModule to ONNX

### ISSUE THREAD

**Issue by IlyaOvodov** [pytorch/pytorch#36478]
## 🐛 Bug
```
class MyClass(nn.Module):
    def __init__(self):
        super(MyClass, self).__init__()
    def forward(self, x: List[Tensor]):
        x = x[0]
        return x
model = MyClass()
img = [torch.zeros((2, 3,))]
x = model(img) # OK
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img[0]) # OK
model = torch.jit.script(model)
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img[0]) # fail
```
->
```
Traceback (most recent call last):
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 351, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 97, in _optimize_graph
    torch._C._jit_pass_dce(graph)
RuntimeError: kind_.is_prim() INTERNAL ASSERT FAILED at ..\torch\csrc\jit\ir\ir.cpp:1058, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::__getitem__ doesn't have one either. We don't know if this op has side effects.
```
## Environment
pytorch version 1.5.0a0+2dc2933

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by suo** [comment]
cc @spandantiwari

**Comment by kjdorow7** [comment]
I was getting the same issue, but found a work around. After experimenting with the code provided by @IlyaOvodov, I discovered that the following produces an onnx file.

```
import torch
import torch.nn as nn
from torch import Tensor

from typing import List

class MyClass(nn.Module):
    def __init__(self):
        super(MyClass, self).__init__()
    def forward(self, x: List[Tensor]):
        # x = x[0] # FAILS
        x1 = x[0] # WORKS
        return x
        
model = MyClass()
img = [torch.zeros((2, 3,))]
x = model(img) # OK

torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img[0]) # OK
model = torch.jit.script(model)
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img[0]) # fail
```

**Comment by david-macleod** [comment]
I believe the only reason the # WORKS case works is because x1 is never used, so is removed from the graph. If you `return x1` it breaks

**Comment by BowenBao** [comment]
tensor list as model input is currently not supported for ONNX export. Workarounds could be to 
1. use concatenated tensor as input instead, if tensor shapes are compatible for concat.
2. send in tuple of tensors or flattened tensors as input if number of element in list is fixed.

Could you share which model is affected by this?

**Comment by garymm** [comment]
This seems to have gotten fixed at some point. The example now produces this output:

```
graph(%x.1 : Tensor[]):
  %1 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={0}]()
  %2 : Float(2, 3, strides=[3, 1], requires_grad=0, device=cpu) = onnx::SequenceAt(%x.1, %1)
  return (%2)
```
