### ISSUE TITLE
INTERNAL ASSERT FAILED at mmdet/ops/nms/src/nms_cpu.cpp:7

### ISSUE THREAD

**Issue by modjtabaf** [pytorch/pytorch#36506]
## 🐛 Bug

I am trying to run the single GPU test on MMDetection toolbox ax explained [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md).

## To Reproduce

I ran the first example provided by issuing the following command:

```
python tools/test.py configs/faster_rcnn_r50_fpn_1x.py \
    checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth \
    --show
```

## Expected behavior

I expect not to see any errors!

## Environment

Here is the output of the environment collection script:

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Debian GNU/Linux 9.11 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 418.87.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.15.1
[pip3] torch==1.4.0
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch                   1.4.0           cuda101py37h02f0884_0  
[conda] torchvision               0.5.0                    pypi_0    pypi
```

## Additional context

Here is the output I got:

```
loading annotations into memory...
Done (t=0.54s)
creating index...
index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 170, in <module>
    main()
  File "tools/test.py", line 148, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/apis/test.py", line 19, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/home/jupyter/bin/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/bin/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jupyter/bin/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/models/detectors/base.py", line 149, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/models/detectors/base.py", line 130, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/models/detectors/two_stage.py", line 303, in simple_test
    self.test_cfg.rpn)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/models/detectors/test_mixins.py", line 34, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 276, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 92, in get_bboxes_single
    proposals, _ = nms(proposals, cfg.nms_thr)
  File "/home/jupyter/mojtaba/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 54, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: !dets.type().is_cuda() INTERNAL ASSERT FAILED at mmdet/ops/nms/src/nms_cpu.cpp:7, please report a bug to PyTorch. dets must be a CPU tensor (nms_cpu_kernel at mmdet/ops/nms/src/nms_cpu.cpp:7)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7faf42f662ad in /home/jupyter/bin/anaconda3/envs/py37/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: at::Tensor nms_cpu_kernel<float>(at::Tensor const&, float) + 0x882 (0x7faefec0fcf2 in /home/jupyter/mojtaba/mmdetection/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so)
frame #2: nms(at::Tensor const&, float) + 0x362 (0x7faefebfd6e2 in /home/jupyter/mojtaba/mmdetection/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x3d48d (0x7faefebc148d in /home/jupyter/mojtaba/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x3b8c3 (0x7faefebbf8c3 in /home/jupyter/mojtaba/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
```

**Comment by mrshenli** [comment]
@modjtabaf 

Looks like this bug needs to be reported to https://github.com/open-mmlab/mmdetection instead. The error message says `please report a bug to PyTorch` because the code in that repo is using assert macro from PyTorch [here](https://github.com/open-mmlab/mmdetection/blob/ef58bc62d3b5ee992b37e9277a7aa7701d8c1757/mmdet/ops/nms/src/nms_cpu.cpp#L7). 

I am closing this issue, but please feel free to reopen if you believe something needs to be fixed in PyTorch. Thanks!

**Comment by modjtabaf** [comment]
Thanks, @mrshenli. I will do what you suggested.

**Comment by Liu0329** [comment]
@modjtabaf Same problem. Have you solved it ?

**Comment by modjtabaf** [comment]
@Liu0329 I found a temporary workaround but, I didn't pursue it any further because I switched to another tool. My temporary workaround was to edit line 54 of the file nms_wrapper.py as below:
`# inds = nms_cuda.nms(dets_th, iou_thr)`
`inds = nms_cpu.nms(dets_th.cpu(), iou_thr).cuda()`

**Comment by jcdubron** [comment]
@modjtabaf It works to replace the function name "nms" with "nms_cpu" in `nms_cpu.cpp` as well as `PYBIND11_MODULE`. I guess it may conflict with `nms_cuda.cpp` for the same name.
