### ISSUE TITLE
Multiprocessing on Python 3.8 fails with cannot pickle '_io.TextIOWrapper'

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#36515]
## To Reproduce

On macOS with a python 3.8 environment

Install `v1.5.0-rc3` from our test repositories
```
pip install -f https://download.pytorch.org/whl/test/cpu/torch_test.html torch
```

Run the test suite for distributed:

```
python test/run_test.py -v -i distributed/test_distributed
...
======================================================================
ERROR: test_sparse_all_reduce_sum_cuda (__main__.TestDistBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distributed/test_distributed.py", line 2080, in setUp
    self.processes.append(self._spawn_process(rank))
  File "distributed/test_distributed.py", line 2101, in _spawn_process
    process.start()
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/eliuriegas/.pyenv/versions/miniconda3-4.3.30/envs/test38/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

----------------------------------------------------------------------
```

## Expected behavior

The tests pass
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.3
GCC version: Could not collect
CMake version: version 3.16.5

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.2
[pip] torch==1.5.0
[conda] torch                     1.5.0                    pypi_0    pypi
```

## Additional context

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment]
cc @osalpekar

**Comment by osalpekar** [comment]
This test is supposed to be skipped if CUDA isn't available, and this environment doesn't seem to have CUDA. Will look into why this test wasn't skipped.

**Comment by seemethere** [comment]
@osalpekar This includes all tests that run under `distributed/test_distributed`

I just chose that one since it was last in the list

Related issue (from ansible):
https://github.com/ansible/ansible/issues/63973#issuecomment-546995228

**Comment by rohan-varma** [comment]
@seemethere @osalpekar Haven't looked too deeply, but this is likely because of a spawn vs fork multiprocessing issue. In py3.8, spawn is now default instead of fork. We use a bunch of tempfiles in these tests, and spawn method can't pickle those:

https://gist.github.com/rohan-varma/1fe828948e0b48bb6c9be38465c51647
