### ISSUE TITLE
Typecasting issue in MSELoss

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#36553]
## 🐛 Bug

Cannot backprop through MSELoss when it is provided with different dtypes.

## To Reproduce

```py
import torch


class SimpleModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.layer = torch.nn.Linear(1, 1)

    def forward(self, x):
        return self.layer(x)


model = SimpleModel().double()
X = torch.rand(100, 1).double()
Y = torch.rand(100, 1).float()

optimizer = torch.optim.Adam(model.parameters())
model.train()
optimizer.zero_grad()

loss = torch.nn.MSELoss()(model(X), Y)  # leads to failure
# loss = ((model(X) - Y) ** 2).mean()  # works

loss.backward() # fails here
optimizer.step()
```

> Traceback (most recent call last):
>   File "foo.py", line 29, in <module>
>     loss.backward()
>   File "/home/twoertwe/miniforge3/envs/panama/lib/python3.8/site-packages/torch/tensor.py", line 195, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/twoertwe/miniforge3/envs/panama/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
>     Variable._execution_engine.run_backward(
> RuntimeError: expected dtype Double but got dtype Float

## Expected behavior

MSELoss either throws an error or it should be able to deal with mixed dtypes.

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 9.2.1-17ubuntu1~16.04) 9.2.1 20191102
CMake version: version 3.15.1

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.64
cuDNN version: /usr0/local/cuda-9.0/lib64/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] hamiltorch==0.3.1.dev3
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] hamiltorch                0.3.1.dev3               pypi_0    pypi
[conda] mkl                       2020.0                      166    conda-forge
[conda] numpy                     1.18.1           py38h8854b6b_1    conda-forge
[conda] pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py38_cu101    pytorch
```

**Comment by mrshenli** [comment]
cc @nairbv
