### ISSUE TITLE
[1.4.1] cmake3 not found

### ISSUE THREAD

**Issue by tuxmaster5000** [pytorch/pytorch#36572]
On CentOS7 the cmake 3 binary is called cmake3, but at the build for pytorch only an call to cmake is done. But cmake is not installed,
'which cmake3' will find the path to it.
As I see in the source code of pytorch, there is some code to find cmake3, but it looks like it will nor work.
```
 which cmake3
/usr/bin/cmake3
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
+ LDFLAGS='-Wl,-z,relro '
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Building wheel torch-1.4.0a0
-- Building version 1.4.0a0
cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/builddir/build/BUILD/torch-1.4.1/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3.6/site-packages -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib64/libpython3.6m.so.1.0 -DTORCH_BUILD_VERSION=1.4.0a0 -DUSE_NUMPY=True /builddir/build/BUILD/torch-1.4.1
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/builddir/build/BUILD/torch-1.4.1/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/builddir/build/BUILD/torch-1.4.1/tools/setup_helpers/cmake.py", line 319, in generate
    self.run(args, env=my_env)
  File "/builddir/build/BUILD/torch-1.4.1/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
```

**Comment by tuxmaster5000** [comment]
It looks like the part is buggy.
```
def _get_cmake_command():
        "Returns cmake command."

        cmake_command = 'cmake'
        if IS_WINDOWS:
            return cmake_command
        cmake3 = which('cmake3')
        if cmake3 is not None:
            cmake = which('cmake')
            if cmake is not None:
                bare_version = CMake._get_version(cmake)
                if (bare_version < LooseVersion("3.5.0") and
                        CMake._get_version(cmake3) > bare_version):
                    cmake_command = 'cmake3'
        return cmake_command
```
When cmak3 was found and no cmake command is found, then cmake_command will stay at cmake instant of  cmake3.

**Comment by colesbury** [comment]
Uh, yeah that looks buggy. A PR fixing it would be welcome.

**Comment by guol-fnst** [comment]
I came up the same bug.
So if @tuxmaster5000 is too busy to fix it , I can try on it.
