### ISSUE TITLE
RuntimeError: Expected cuda::check_device({sparse_, r_, t, dense}) to be true, but got false.  

### ISSUE THREAD

**Issue by maihefande** [pytorch/pytorch#36649]
I try to use  DataParallel to model ,and i get this.I don't know why and how to fix it ，is there any suggestion?
I use DataParallel  like this:
if cmd_args.mode == 'gpu':
        classifier = classifier.cuda()
        classifier = nn.DataParallel(classifier)

Exception has occurred: RuntimeError
Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/server/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/server/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/server/disk/lt/androfcg/classifier.py", line 32, in forward
    embed,labels= self.s2v(batch_graph, S2VLIB)
  File "/home/server/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/server/disk/lt/androfcg/classifier.py", line 89, in forward
    h = self.mean_field(node_feat, n2n_sp)
  File "/home/server/disk/lt/androfcg/classifier.py", line 99, in mean_field
    input_message = self.w_n2l(node_feat[i])
  File "/home/server/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/server/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected cuda::check_device({sparse_, r_, t, dense}) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
  File "/home/server/disk/lt/androfcg/main.py", line 28, in loop_dataset
    _, loss, acc = classifier(selected_idx,S2VLIB)
  File "/home/server/disk/lt/androfcg/main.py", line 77, in <module>
    avg_loss = loop_dataset(S2VLIB, classifier, train_idx, optimizer=optimizer)

**Comment by maihefande** [comment]
Is there any other infomation i need to provide？

**Comment by TMLOG** [comment]
I encountered the same problem with you, did you fix it?

**Comment by ehedlin** [comment]
For me it had to do with devices on separate GPUs being matmul'd
