### ISSUE TITLE
softmax doesn't support negative dimensions

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#3677]
on 0.2.0+502aaf3 (can't try on master because of https://github.com/pytorch/pytorch/issues/3669):
```python
import torch

torch.nn.functional.softmax(torch.autograd.Variable(torch.Tensor(1,2,3,4).cuda()), dim = -1)
#Traceback (most recent call last):
# File "<stdin>", line 1, in <module>
#  File ".../lib/python2.7/site-packages/torch/nn/functional.py", line 768, in softmax
#    return torch._C._nn.softmax(input, dim)
#RuntimeError: invalid argument 4: dim out of range (got -1, but input has 4 dims) at .../pytorch/aten/src/THCUNN/generic/SoftMax.cu:15

torch.nn.functional.softmax(torch.autograd.Variable(torch.Tensor(1,2,3,4).cuda()), dim = 3) # works
```

**Comment by SsnL** [comment]
also broken on branch v0.3.0

**Comment by soumith** [comment]
well the question then becomes, did it ever support negative dimensions?

**Comment by soumith** [comment]
if it didn't support negative dims in `0.2.0` then i wont mark it as a release blocker for 0.3

**Comment by SsnL** [comment]
@soumith in 0.2.0 there wasn't a dim keyword arg.
