### ISSUE TITLE
Flakiness in TestAutogradDeviceTypeCUDA

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36788]
Updates: see below for more up to date analysis. 

Multiple builds are sporadically failing with the same error but on different tests in TestAutogradDeviceTypeCUDA. 

The first occurrence of this issue I can find is on https://github.com/pytorch/pytorch/commit/63e5058c885309f577a3871d18603eb5580b7996. 

Where it produced:

```
Apr 17 02:43:16   test_simple_backward_same_input (__main__.TestMultithreadAutograd) ... ok (0.010s)
Apr 17 02:43:16 
Apr 17 02:43:16 ======================================================================
Apr 17 02:43:16 ERROR [0.200s]: test_frac_cuda (__main__.TestAutogradDeviceTypeCUDA)
Apr 17 02:43:16 ----------------------------------------------------------------------
Apr 17 02:43:16 Traceback (most recent call last):
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 710, in wrapper
Apr 17 02:43:16     method(*args, **kwargs)
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 710, in wrapper
Apr 17 02:43:16     method(*args, **kwargs)
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
Apr 17 02:43:16     return test(self, device_arg)
Apr 17 02:43:16   File "test_autograd.py", line 4231, in do_test
Apr 17 02:43:16     check(name)
Apr 17 02:43:16   File "test_autograd.py", line 4154, in check
Apr 17 02:43:16     output_variable, (self_variable,) + args_variable)
Apr 17 02:43:16   File "test_autograd.py", line 4084, in run_grad_and_gradgrad_checks
Apr 17 02:43:16     test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 416, in gradgradcheck
Apr 17 02:43:16     nondet_tol=nondet_tol)
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 291, in gradcheck
Apr 17 02:43:16     numerical = get_numerical_jacobian(fn, tupled_inputs, eps=eps)
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 134, in get_numerical_jacobian
Apr 17 02:43:16     outb = fn(input).clone()
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 288, in fn
Apr 17 02:43:16     return _as_tuple(func(*input))[i]
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 412, in new_func
Apr 17 02:43:16     grad_inputs = torch.autograd.grad(outputs, input_args, grad_outputs, create_graph=True)
Apr 17 02:43:16   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 158, in grad
Apr 17 02:43:16     inputs, allow_unused)
Apr 17 02:43:16 RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /var/lib/jenkins/workspace/torch/csrc/autograd/engine.cpp:893, please report a bug to PyTorch. 
Apr 17 02:43:16 
Apr 17 02:43:16 ----------------------------------------------------------------------
Apr 17 02:43:16 Ran 1983 tests in 760.799s
```

in the pytorch_windows_vs2019_py36_cuda10.1_test2 build.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @wanchaol

**Comment by mruberry** [comment]
Another example from pytorch_linux_xenial_cuda9_2_cudnn7_py3_gcc7_test

```
Apr 17 02:07:43   test_simple_backward_same_input (__main__.TestMultithreadAutograd) ... ok (0.010s)
Apr 17 02:07:43 
Apr 17 02:07:43 ======================================================================
Apr 17 02:07:43 ERROR [0.144s]: test_matrix_power_n=1_cuda (__main__.TestAutogradDeviceTypeCUDA)
Apr 17 02:07:43 ----------------------------------------------------------------------
Apr 17 02:07:43 Traceback (most recent call last):
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 710, in wrapper
Apr 17 02:07:43     method(*args, **kwargs)
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 710, in wrapper
Apr 17 02:07:43     method(*args, **kwargs)
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
Apr 17 02:07:43     return test(self, device_arg)
Apr 17 02:07:43   File "test_autograd.py", line 4231, in do_test
Apr 17 02:07:43     check(name)
Apr 17 02:07:43   File "test_autograd.py", line 4154, in check
Apr 17 02:07:43     output_variable, (self_variable,) + args_variable)
Apr 17 02:07:43   File "test_autograd.py", line 4084, in run_grad_and_gradgrad_checks
Apr 17 02:07:43     test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 416, in gradgradcheck
Apr 17 02:07:43     nondet_tol=nondet_tol)
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 290, in gradcheck
Apr 17 02:07:43     analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(tupled_inputs, o, nondet_tol=nondet_tol)
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 166, in get_analytical_jacobian
Apr 17 02:07:43     retain_graph=True, allow_unused=True)
Apr 17 02:07:43   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 158, in grad
Apr 17 02:07:43     inputs, allow_unused)
Apr 17 02:07:43 RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /var/lib/jenkins/workspace/torch/csrc/autograd/engine.cpp:893, please report a bug to PyTorch. 
Apr 17 02:07:43 
Apr 17 02:07:43 ----------------------------------------------------------------------
Apr 17 02:07:43 Ran 1983 tests in 836.419s
```

**Comment by mruberry** [comment]
build pytorch_linux_xenial_cuda9_cudnn7_py3_test on PR #35613 

```

Apr 16 18:34:46 test_simple_backward_same_input (__main__.TestMultithreadAutograd) ... ok (0.011s)
--
5406 | Apr 16 18:34:46
5407 | Apr 16 18:34:46 ======================================================================
5408 | Apr 16 18:34:46 ERROR [0.128s]: test_add_scalar_broadcast_rhs_cuda (__main__.TestAutogradDeviceTypeCUDA)
5409 | Apr 16 18:34:46 ----------------------------------------------------------------------
5410 | Apr 16 18:34:46 Traceback (most recent call last):
5411 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 704, in wrapper
5412 | Apr 16 18:34:46 method(*args, **kwargs)
5413 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 704, in wrapper
5414 | Apr 16 18:34:46 method(*args, **kwargs)
5415 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
5416 | Apr 16 18:34:46 return test(self, device_arg)
5417 | Apr 16 18:34:46 File "test_autograd.py", line 4231, in do_test
5418 | Apr 16 18:34:46 check(name)
5419 | Apr 16 18:34:46 File "test_autograd.py", line 4154, in check
5420 | Apr 16 18:34:46 output_variable, (self_variable,) + args_variable)
5421 | Apr 16 18:34:46 File "test_autograd.py", line 4084, in run_grad_and_gradgrad_checks
5422 | Apr 16 18:34:46 test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
5423 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 416, in gradgradcheck
5424 | Apr 16 18:34:46 nondet_tol=nondet_tol)
5425 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 290, in gradcheck
5426 | Apr 16 18:34:46 analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(tupled_inputs, o, nondet_tol=nondet_tol)
5427 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 166, in get_analytical_jacobian
5428 | Apr 16 18:34:46 retain_graph=True, allow_unused=True)
5429 | Apr 16 18:34:46 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 158, in grad
5430 | Apr 16 18:34:46 inputs, allow_unused)
5431 | Apr 16 18:34:46 RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /var/lib/jenkins/workspace/torch/csrc/autograd/engine.cpp:893, please report a bug to PyTorch.
```

**Comment by mruberry** [comment]
First occurrence seems to be here https://github.com/pytorch/pytorch/pull/36675 (log below). This is shortly after https://github.com/pytorch/pytorch/pull/36640 went in.


Apr 16 16:28:41
--
5407 | Apr 16 16:28:41 ======================================================================
5408 | Apr 16 16:28:41 ERROR [0.120s]: test_view_cuda (__main__.TestAutogradDeviceTypeCUDA)
5409 | Apr 16 16:28:41 ----------------------------------------------------------------------
5410 | Apr 16 16:28:41 Traceback (most recent call last):
5411 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 704, in wrapper
5412 | Apr 16 16:28:41 method(*args, **kwargs)
5413 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 704, in wrapper
5414 | Apr 16 16:28:41 method(*args, **kwargs)
5415 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
5416 | Apr 16 16:28:41 return test(self, device_arg)
5417 | Apr 16 16:28:41 File "test_autograd.py", line 4231, in do_test
5418 | Apr 16 16:28:41 check(name)
5419 | Apr 16 16:28:41 File "test_autograd.py", line 4154, in check
5420 | Apr 16 16:28:41 output_variable, (self_variable,) + args_variable)
5421 | Apr 16 16:28:41 File "test_autograd.py", line 4084, in run_grad_and_gradgrad_checks
5422 | Apr 16 16:28:41 test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
5423 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 416, in gradgradcheck
5424 | Apr 16 16:28:41 nondet_tol=nondet_tol)
5425 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 290, in gradcheck
5426 | Apr 16 16:28:41 analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(tupled_inputs, o, nondet_tol=nondet_tol)
5427 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 166, in get_analytical_jacobian
5428 | Apr 16 16:28:41 retain_graph=True, allow_unused=True)
5429 | Apr 16 16:28:41 File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 158, in grad
5430 | Apr 16 16:28:41 inputs, allow_unused)
5431 | Apr 16 16:28:41 RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /var/lib/jenkins/workspace/torch/csrc/autograd/engine.cpp:893, please report a bug to PyTorch.

**Comment by mruberry** [comment]
These lines looks very suspicious to me:

```
if (!graphTask_->future_completed_.exchange(true)) {
  graphTask_->future_result_->setErrorIfNeeded(err.what());
}
```

I'm not going to revert #36640 since it claims to be fixing another race, it's almost a day old, and this flaky failure is sporadic so we won't know immediately if the unland worked, but please look at this failure carefully ASAP.

@pritamdamania @jjlilley

**Comment by jjlilley** [comment]
I believe we simply can s/setErrorIfNeeded/setError/, since the setErrorIfNeeded() logic isn't needed anymore.

#36640 does fix an observed error from #35101 that I made to address an inter-task locking issue.

**Comment by pritamdamania87** [comment]
@mruberry Thanks for flagging, I'll try to find a fix for this today.

**Comment by mruberry** [comment]
Now observable in other tests. From build pytorch_linux_xenial_cuda10_1_cudnn7_py3_gcc7_test:

```
Apr 17 23:47:44   test_torch_nn_functional_softmax_spatial_special_cuda (__main__.TestCppApiParity) ... ok (0.013s)
Apr 17 23:47:44 
Apr 17 23:47:44 ======================================================================
Apr 17 23:47:44 ERROR [0.007s]: test_torch_nn_AdaptiveAvgPool3d_single_cuda (__main__.TestCppApiParity)
Apr 17 23:47:44 ----------------------------------------------------------------------
Apr 17 23:47:44 Traceback (most recent call last):
Apr 17 23:47:44   File "/var/lib/jenkins/workspace/test/cpp_api_parity/module_impl_check.py", line 251, in test_fn
Apr 17 23:47:44     unit_test_class=self, test_params=unit_test_class.module_test_params_map[self._testMethodName])
Apr 17 23:47:44   File "/var/lib/jenkins/workspace/test/cpp_api_parity/module_impl_check.py", line 134, in test_forward_backward
Apr 17 23:47:44     script_module, python_output, python_grad_dict = run_python_forward_backward(unit_test_class, test_params)
Apr 17 23:47:44   File "/var/lib/jenkins/workspace/test/cpp_api_parity/module_impl_check.py", line 112, in run_python_forward_backward
Apr 17 23:47:44     python_output.sum().backward()
Apr 17 23:47:44   File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
Apr 17 23:47:44     torch.autograd.backward(self, gradient, retain_graph, create_graph)
Apr 17 23:47:44   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
Apr 17 23:47:44     allow_unreachable=True)  # allow_unreachable flag
Apr 17 23:47:44 RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /var/lib/jenkins/workspace/torch/csrc/autograd/engine.cpp:892, please report a bug to PyTorch. 
Apr 17 23:47:44 
Apr 17 23:47:44 ----------------------------------------------------------------------
Apr 17 23:47:44 Ran 798 tests in 13.948s
```

**Comment by jjlilley** [comment]
Oh, interesting -`mark_graph_task_completed()` effectively no longer guarantees that the future is completed before exiting - it's possible to exit when it's only in the process of being completed. Which isn't good enough for the assert that is being quoted above. 

(This is basically the `pthread_once()` problem underneath the hood)

What I think might solve is simply a 1-line addition of a future->waitNoThrow() call to the early exit path in mark_graph_task_complete().
    This will have the property of guaranteeing that the future is completed on exit - probably a property that people expect. And the cost won't be too high, since it's not the common fast-path.

I'll write this up, unless we have other ideas.

**Comment by pritamdamania87** [comment]
@jjlilley Thats a great observation, I think that explains the flakiness we are seeing here!

**Comment by albanD** [comment]
The PR has been merged. Please re-open if we see this again.
