### ISSUE TITLE
Standardize idioms for error context in c10::Error in c10/util/Exception.h

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#36954]
A common situation when reporting errors is that we don't know enough about the context at the point we are reporting the error. For example, in the new op registration API we have:

```
#define DEF_PRELUDE "def(\"", schema.operator_name(), "\"): "
Library& Library::_def(c10::FunctionSchema&& schema, c10::OperatorName* out_name) & {
  TORCH_CHECK(kind_ == DEF || kind_ == FRAGMENT,
    DEF_PRELUDE,
    "Cannot define an operator inside of a ", kind_, " block.  "
    "All def()s should be placed in the (unique) TORCH_LIBRARY block for their namespace.  ",
    ERROR_CONTEXT
  );
```

However, the description of what the shape of the def operation was is misleading, because `_def` may be called from the implementation of `def(schema, impl)` (and so the error message would misreport that it's from a `def(schema)` call). These things may seem minor, but there are more major situations where lack of context can seriously impede understanding of an error message (e.g., a BLAS failure in some low level helper function, which should we report as having occurred when someone did a matrix multiply call.)

Today, `c10::Error` supports a limited form of error context in the form of its `AppendMessage` method, which can be used append an arbitrary string at the end of the existing c10 exception string. This is used in very few places. The purpose of this issue is to propose a more general formatting and API convention for adding context, with the intent of using it more broadly in the codebase.

----

Typical message format today:

```
>>> torch.zeros(2,3) + torch.zeros(3,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
```

Suggested updated format with context:

```
>>> torch.zeros(2,3) + torch.zeros(3,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
  In operator "add.Tensor"
```

Notes about format:
* Each line of context is indented two spaces and occupies a newline. (The expectation is that context is short and does not need to line wrap). Context is capitalized. Unless you have a good reason not to, it should start with "In ..." 
* Lines of context do NOT record the C++ file/line number that installed them (But perhaps in a hypothetical mode where we unconditionally report C++ backtraces, c.f. #25716, we could also contain file and line numbers of the context adding lines)

EDIT: I have a suggested refinement on format. If there is only one line of error context, we should fold it into the previous line. So you have:

```
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1 (In operator "add.Tensor")
```

With two lines, we give them separate lines:

```
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
  In operator "add.Tensor"
  In operator "addmm"
```

How to augment errors in this way, from C++:

```
try {
  ...
} catch (c10::Error& e) {
  TORCH_RERAISE(e, "Context message");
}
```

Context message follows the same formatting conventions as `TORCH_CHECK`.

Possible alternatives:
* Install context as "fake" C++ frames in the Python backtrace. We shouldn't do this as it may interfere with IDE support of jump to error (which will only expect Python files in the trace)
* Use TorchScript style error reporting. TorchScript style errors look like:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(scripted_f("0_1"))
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "test.py", line 6, in parse_float_from_str
def parse_float_from_str(s: str) -> float:
    return float(torch.split(s, "_", -1)[0])
           ~~~~~ <--- HERE
RuntimeError: Only 'inf' or '-inf' can be cast to a float, but got '0'
```

I'd prefer not to use this style because having two tracebacks in the error message impedes understanding of the error block; most PyTorch errors should just have one "Traceback", and the error context I'm thinking of would apply to most PyTorch errors

* Print the entire C++ stack trace. This is generally not so useful to end users; while they can crack open the Python code referenced by a Python backtrace, there is generally no way to get to the C++ code (or modify it and see what happens)

**Comment by ezyang** [comment]
Some possible refinements on C++ API: an attractive alternate API for context addition is an RAII structure, which appends the context onto the exception in its destructor. We would have to maintain a thread local tracking the "current exception", ensure that it is maintained correctly. This has performance cost (unlike exception handling frames, which are free if no exception is raised).

Conclusion: continue with explicit exception try-catch frames for now.
