### ISSUE TITLE
is_cuda() internal assert failure

### ISSUE THREAD

**Issue by lijunzh** [pytorch/pytorch#37100]
## 🐛 Bug

This bug report is created as instructed by the fail message below:

```
Traceback (most recent call last):
File "qat_residual.py", line 60, in <module>
TRAINING_DEVICE, print_freq=500)
File "/home/lijun/repo/quant/utils.py", line 73, in train_one_epoch
output = model(image)
File "/home/lijun/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
result = self.forward(*input, **kwargs)
File "/home/lijun/repo/quant/residual_model.py", line 312, in forward
return self._forward_impl(x)
File "/home/lijun/repo/quant/residual_model.py", line 295, in _forward_impl
x = self.conv1(x)
File "/home/lijun/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
result = self.forward(*input, **kwargs)
File "/home/lijun/conda/lib/python3.7/site-packages/torch/nn/qat/modules/conv.py", line 36, in forward
self._conv_forward(input, self.weight_fake_quant(self.weight)))
File "/home/lijun/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
result = self.forward(*input, **kwargs)
File "/home/lijun/conda/lib/python3.7/site-packages/torch/quantization/fake_quantize.py", line 86, in forward
self.ch_axis, self.quant_min, self.quant_max)
RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1587428398394/work/aten/src/ATen/native/cuda/Loops.cuh:56, please report a bug to PyTorch.
```

## To Reproduce

1. A float-point number ResNet was trained 
1. The pre-trained ResNet was prepared for QAT
1. When QAT ran on the first epoch, it raised the message above.

## Expected behavior

The model should be able to move from system memory to GPU memory.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by peterjc123** [comment]
Seems to be a duplicate of https://github.com/pytorch/pytorch/issues/36802.

**Comment by lijunzh** [comment]
@peterjc123 Yes, the workaround mentioned in #36802 solves the problem. However, it would be better PyTorch can keep a consistent behavior between 1.4 and 1.5.
