### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED for ConvTranspose2d backward with FP16 inputs

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#37157]
## 🐛 Bug

While helping @vfdev-5 integrate `torch.cuda.amp` with [Ignite](https://github.com/pytorch/ignite), he asked me to debug a CycleGan+Amp example.  I saw weird nondeterministic errors.  Eventually I narrowed down a repro with ConvTranspose2d, FP16 inputs, and shapes taken from cyclegan.  It fails with illegal memory accesses in `SlowConvTranspose2DBackward`.  (The repro does not involve `torch.cuda.amp` or @vfdev-5 's script at all, so I think these are innocent.)

I don't know the cause yet, the failure may or may not occur based on input addresses, and I'm not sure what distinguishes "bad" input addresses.
 
Posting for visibility.  I will check for similar issues and keep digging.  Related:
- https://github.com/pytorch/pytorch/issues/31690, which discusses how nonzero `output_padding` can force ConvTranspose2d to use the "slow conv" backend (im2col+col2im+cublas GEMM) instead of cudnn.
- https://github.com/pytorch/pytorch/issues/23545, same failing call (ConvTranspose2d with FP16 inputs, even the same shapes as my repro!) but fails with different symptoms.  The "fix" (https://github.com/pytorch/pytorch/commit/9130ab380a4af0c67036ea8fce937156cfd0a8c8) is a one-line change that replaced a macro with a hardcoded character, so any deep memory movement problems likely weren't affected.
- https://github.com/pytorch/pytorch/issues/15584, also cyclegan backward() failure, but failure came from cudnn.  Not resolved.

## To Reproduce
This may not work on a different system, but `out.sum().backward()` reliably fails for me at iteration 48.
```python
import torch

dtype = torch.half

for i in range(0,500):
    torch.cuda.manual_seed(17)
    # dummy tensors to fuzz where ConvTranspose2d inputs get allocated
    dummy0 = torch.empty((7777*i,), device="cuda", dtype=dtype)
    a = torch.randn((6, 256, 50, 50), device="cuda", dtype=dtype)
    dummy1 = torch.empty((7777*i,), device="cuda", dtype=dtype)
    # shape from CycleGAN
    m = torch.nn.ConvTranspose2d(256, 128, kernel_size=3, stride=2, padding=1, output_padding=1, bias=True).cuda().to(dtype)
    dummy2 = torch.empty((7777*i,), device="cuda", dtype=dtype)
    out = m(a)
    out.sum().backward()
    print(i,
          "weight grad sum = ", m.weight.grad.data.double().sum().item() if m.weight.grad is not None else None,
          "bias grad sum = ", m.bias.grad.data.double().sum().item() if m.bias.grad is not None else None)
    m.zero_grad()
```

Stack trace with `CUDA_LAUNCH_BLOCKING=1`
(weight grad and bias grad sums are deterministic for the first 47 iterations)
```
weight grad sum =  1366953.875 bias grad sum =  98304.0
47 torch.Size([6, 128, 100, 100]) 140174484123648 140173632753664 140173635366912
140173633344000
weight grad sum =  1366953.875 bias grad sum =  98304.0
48 torch.Size([6, 128, 100, 100]) 140174476443648 140173636979712 140173633344000
140173637570048
Traceback (most recent call last):
  File "transpose2d.py", line 131, in <module>
    out.sum().backward()
  File "/home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)` (gemm<c10::Half> at ../aten/src/ATen/cuda/CUDABlas.cpp:226)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f7d201cbe1a in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x35ccb46 (0x7f7d239b2b46 in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x35cd4d9 (0x7f7d239b34d9 in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: at::native::(anonymous namespace)::slow_conv_transpose2d_acc_grad_parameters_cuda_template(at::Tensor const&, at::Tensor const&, at::Tensor&, at::Tensor&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, int) + 0xe46 (0x7f7d22946446 in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::native::slow_conv_transpose2d_backward_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x422 (0x7f7d2294c3d2 in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x3649d49 (0x7f7d23a2fd49 in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x365927d (0x7f7d23a3f27d in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x2bae96a (0x7f7d43cbe96a in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0xf39d3d (0x7f7d42049d3d in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::autograd::generated::SlowConvTranspose2DBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x520 (0x7f7d4391f490 in /home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
...
```

`cuda-memcheck --tool memcheck python transpose2d.py` reports a bunch of invalid reads like
```
 Invalid __global__ read of size 2
=========     at 0x00001340 in void gemv2T_kernel_val<int, int, __half, __half, float, int=128, int=16, int=2, int=2, bool=0, cublasGemvParams<cublasGemvTensorStridedBatched<__half const >, cublasGemvTensorStridedBatched<__half>, float>>(__half const , float, float)
=========     by thread (112,0,0) in block (768,0,0)
=========     Address 0x7f58ea60000e is out of bounds
=========     Device Frame:void gemv2T_kernel_val<int, int, __half, __half, float, int=128, int=16, int=2, int=2, bool=0, cublasGemvParams<cublasGemvTensorStridedBatched<__half const >, cublasGemvTensorStridedBatched<__half>, float>>(__half const , float, float) (void gemv2T_kernel
_val<int, int, __half, __half, float, int=128, int=16, int=2, int=2, bool=0, cublasGemvParams<cublasGemvTensorStridedBatched<__half const >, cublasGemvTensorStridedBatched<__half>, float>>(__half const , float, float) : 0x1340)
...
=========     Host Frame:/home/mcarilli/anaconda3/envs/python373/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so (_ZN2at6native97_GLOBAL__N__73_tmpxft_00003c73_00000000_7_NaiveConvolutionTranspose2d_compute_61_cpp1_ii_1a68c69d55slow_conv_transpose2d_acc_grad_parameters_cuda_
templateERKNS_6TensorES4_RS2_S5_S4_S4_N3c108ArrayRefIlEES8_S8_S8_S8_i + 0xe46) [0x2560446]
```

## Environment
Cublas is being loaded from a vanilla public cuda 10.2 install:
```
(python373) $ LD_DEBUG=libs python transpose2d.py 2>&1 | grep cublas
      ...
      8876:     calling init: /home/mcarilli/cuda_versions/10.2_files/cuda-toolkit/lib64/libcublasLt.so.10
      8876:     calling init: /home/mcarilli/cuda_versions/10.2_files/cuda-toolkit/lib64/libcublas.so.10
```

Pytorch is based on a recent-ish master (`__version__` is unique because it's a source build from a local commit with debugging print statements).

cc @ezyang @gchanan @zou3519 @csarofeen @ptrblck

**Comment by ngimel** [comment]
Hi priority because it is a crash.

**Comment by mcarilli** [comment]
At the [spot where the error occurs](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/NaiveConvolutionTranspose2d.cu#L736), the gemv arguments have the expected shape.  If replace the gemv call with dummy in-place `add_(0.0)`s applied to the argument tensors, the repro runs end to end under cuda-memcheck without errors, so the argument tensors appear properly allocated.

Looks more and more like a misconfigured cublas call or an internal cublas error.  Tomorrow i'll figure out which.
