### ISSUE TITLE
RuntimeError: has_marked_unused_parameters_ INTERNAL ASSERT FAILED at /tmp/pip-req-build-p5q91txh/torch/csrc/distributed/c10d/reducer.cpp:290, please report a bug to PyTorch.

### ISSUE THREAD

**Issue by cym3223** [pytorch/pytorch#37339]
I want to use distributed method (torch.nn.parallel.DistributedDataParallel) on pytorch but I got a following error message.

## 🐛 Bug
    Traceback (most recent call last):
      File "train.py", line 387, in <module>
        train(epoch_num, opt)
      File "train.py", line 126, in train
        total_loss_D.backward()
      File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph)
      File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward 
        allow_unreachable=True)  # allow_unreachable flag
    RuntimeError: has_marked_unused_parameters_ INTERNAL ASSERT FAILED at /tmp/pip-req-build-p5q91txh/torch/csrc/distributed/c10d/reducer.cpp:290, please report a bug to PyTorch.

It seems like because of loss-backward functions.
The weird thing is that the loss-backward functions of vanilla pix2pixHD model in front of this error message are worked well.

## To Reproduce

# train.py
if __name__ == '__main__':

    try:
        opt = TrainOptions().parse()
        torch.distributed.init_process_group(init_method='file:///data/sharedfile',backend="nccl",world_size=opt.world_size,rank=opt.rank,group_name="pix_ddp",)

        # prepare training data
        training_data_loader, all_process = get_training_set(opt)

        model = models.import_model(opt.model)()
        model.initialize(opt)
        model = torch.nn.parallel.DistributedDataParallel(model, device_ids=opt.gpu_ids)

        def train(epoch, opt):
            total_G_gan = 0
            total_G_l1 = 0
            total_G_fea = 0
            total_G_ssim = 0
            total_G_mask = 0
            total_G_fr = 0
            total_G_shape = 0

            for iteration, batch in enumerate(training_data_loader, 0):
                pafs, condition, target, mask, mask_real, pafs_preview, \
                target_landmarks, target_params, img_paths = \
                    batch[0], batch[1], batch[2], batch[3], batch[4], batch[5], batch[6], batch[7], batch[8]

                losses_D, losses_G, fake_B = model(pafs, condition, target, mask, mask_real, pafs_preview,
                                                   target_params)

                losses_D = [torch.mean(x) for x in losses_D]
                losses_G = [torch.mean(x) for x in losses_G]

                total_loss_D = (losses_D[0] + losses_D[1]) * 0.5
                total_loss_G = (losses_G[0] + losses_G[1] + losses_G[2] + losses_G[3])

                model.module.optimizer_G.zero_grad()
                total_loss_G.backward()
                model.module.optimizer_G.step()

                model.module.optimizer_D.zero_grad()
                total_loss_D.backward()
                model.module.optimizer_D.step()

## Environment

 - PyTorch Version : 1.2
 - Linux : 16.04
 - conda installed PyTorch
 - Python version : 3.6.9
 - CUDA/cuDNN version : 10.0/7.6.0
 - models : based on pix2pixHD

**Comment by cym3223** [comment]
after I modified "find_unused_parameters=True" in torch.nn.parallel.DistributedDataParallel(model, device_ids=opt.gpu_ids, find_unused_parameters=True)
it could run
