### ISSUE TITLE
[JIT] Not support for MaskRCNNPredictor

### ISSUE THREAD

**Issue by immortal3** [pytorch/pytorch#37344]
I am trying to product jit trace output of the MaskRCNNPredictor model for mobile deployment. The model was created using PyTorch's [official tutorial](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html).
Model code is following.
```python
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
in_features = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, 2)
in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
hidden_layer = 256
model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask,
                                                                hidden_layer,
                                                                2)
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

model.load_state_dict(torch.load("saved.model", map_location=device))
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example, strict=True)
traced_script_module.save("android_model.pt")```
```
using jit trace produces the following results. I have built the lastest pytorch(1.6.0a0+f41742f) from source following issue of [named tuple/dict in jit trace](https://github.com/pytorch/pytorch/issues/16453). 

```
/usr/local/lib/python3.7/site-packages/torch/tensor.py:459: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/usr/local/lib/python3.7/site-packages/torch/nn/functional.py:2892: UserWarning: The default behavior for interpolate/upsample with float scale_factor will change in 1.6.0 to align with other frameworks/libraries, and use scale_factor directly, instead of relying on the computed output size. If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor will change "
/usr/local/lib/python3.7/site-packages/torch/nn/functional.py:2902: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  dtype=torch.float32)).float())) for i in range(dim)]
/usr/local/lib/python3.7/site-packages/torchvision/models/detection/rpn.py:164: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead. (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:81.)
  torch.tensor(image_size[1] / g[1], dtype=torch.int64, device=device)] for g in grid_sizes]
/usr/local/lib/python3.7/site-packages/torchvision/models/detection/rpn.py:164: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(image_size[1] / g[1], dtype=torch.int64, device=device)] for g in grid_sizes]
/usr/local/lib/python3.7/site-packages/torchvision/ops/boxes.py:117: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_x = torch.min(boxes_x, torch.tensor(width, dtype=boxes.dtype, device=boxes.device))
/usr/local/lib/python3.7/site-packages/torchvision/ops/boxes.py:119: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_y = torch.min(boxes_y, torch.tensor(height, dtype=boxes.dtype, device=boxes.device))
/usr/local/lib/python3.7/site-packages/torchvision/ops/poolers.py:216: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:760.)
  idx_in_level = torch.nonzero(levels == level).squeeze(1)
/usr/local/lib/python3.7/site-packages/torchvision/models/detection/transform.py:254: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  for s, s_orig in zip(new_size, original_size)
/usr/local/lib/python3.7/site-packages/torchvision/models/detection/roi_heads.py:381: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(M + 2 * padding).to(torch.float32) / torch.tensor(M).to(torch.float32)
Traceback (most recent call last):
  File "android_model.py", line 20, in <module>
    traced_script_module = torch.jit.trace(model, example, strict=False)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 883, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 1037, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, strict, _force_outplace)
RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
```

Looks like some output is not from mentioned supported types but i am unable to find one?

cc @suo

**Comment by aldasmallthings** [comment]
this seems like a serious issue, is anyone looking into it? it's disabling tensors from being transformed in fast ai...

**Comment by wanchaol** [comment]
@aldasmallthings I am looking into it.

**Comment by immortal3** [comment]
@aldasmallthings  Can you elaborate on  "disabling tensors from being transformed in fast ai...". I am wondering how JIT and FastAI is correlated here.

**Comment by wanchaol** [comment]
@immortal3 can you share your entire e2e script? I don't know where/how do you serialize the `saved.model`.

**Comment by immortal3** [comment]
@wanchaol 
I followed [this tutorail](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html). after training save the model.

**Comment by prabhuomkar** [comment]
I am able to reproduce the same error, not for MaskRCNN but for FCN-ResNet101 from PyTorch Hub:
```
model = torch.hub.load('pytorch/vision:v0.6.0', 'fcn_resnet101', pretrained=True)
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save("fcn.pt")
```

**Comment by wanchaol** [comment]
> I am able to reproduce the same error, not for MaskRCNN but for FCN-ResNet101 from PyTorch Hub:
> 
> ```
> model = torch.hub.load('pytorch/vision:v0.6.0', 'fcn_resnet101', pretrained=True)
> model.eval()
> example = torch.rand(1, 3, 224, 224)
> traced_script_module = torch.jit.trace(model, example)
> traced_script_module.save("fcn.pt")
> ```
> 
> **Error:**
> `RuntimeError: Only tensors, lists and tuples of tensors can be output from traced functions`

@prabhuomkar this is not the same error, you got this error because we don't support dictionary as an output yet for v1.5, and the FCN-ResNet has a dict output, this is a recent feature added in https://github.com/pytorch/pytorch/pull/36696

Consider switching to master build or nightlies and run this:
```
traced_script_module = torch.jit.trace(model, example, strict=False)
```

**Comment by GilbertPan97** [comment]
I have the same error when I convert pytorch model to torch script

Environment:
* Pytorch: 1.11.0 (for training) -> platform: ubuntu 20.04
* torchvision: 0.12.0
* libtorch-cpu: 1.13.1 (for predicting) -> platform: windows 10

Here is model function:
```
def get_model_instance_segmentation(num_classes, load_pretrain_weights=True):
    # get maskrcnn model form torchvision.models
    # load an instance segmentation model pre-trained on COCO
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=load_pretrain_weights)

    # get number of input features for the classifier
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    # replace the pre-trained head with a new one
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

    # now get the number of input features for the mask classifier
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    # and replace the mask predictor with a new one
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask,
                                                       hidden_layer,
                                                       num_classes)

    return model
```

After trained MaskRCNN model, I convert it to torch script with code:
```
def generate_torch_script(pytorch_model, device, img_file, save_path):
    # input of the model (from pil image to tensor, do not normalize image)
    original_img = Image.open(img_file).convert('RGB')      # load image
    data_transform = transforms.Compose([transforms.ToTensor()])
    img = data_transform(original_img)
    img = torch.unsqueeze(img, dim=0).to(device)        # expand batch dimension to device

    # export the model
    pytorch_model.eval()
    if device.type == 'cpu':
        pytorch_model = pytorch_model.cpu()
    traced_script_module = torch.jit.trace(pytorch_model, img)
    traced_script_module.save(save_path)
```
I got the following error:
```
Traceback (most recent call last):
  File "/home/repo_git/Mask_RCNN/MaskRCNN-Pytorch/src/torch_script_gen.py", line 99, in <module>
    main()
  File "/home/repo_git/Mask_RCNN/MaskRCNN-Pytorch/src/torch_script_gen.py", line 87, in main
    generate_torch_script(model, device, IMG_PATH, model_save_path)     # export onnx model
  File "/home/repo_git/Mask_RCNN/MaskRCNN-Pytorch/src/torch_script_gen.py", line 51, in generate_torch_script
    traced_script_module = torch.jit.trace(pytorch_model, img)
  File "/home/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
```
 Any ideas to solve this problem temporarily?

Additionally, `traced_script_module = torch.jit.script(pytorch_model, img)` can help me to obtain model script, while it can't be loaded correctly with `torch::jit::load(model_path)` in C++. (As shown in fig)

![error](https://user-images.githubusercontent.com/48231519/215306349-b25819ef-0320-4c32-a56d-9e10ffc9896b.jpg)
