### ISSUE TITLE
Error in the installation of torch

### ISSUE THREAD

**Issue by ImLuckyWiz** [pytorch/pytorch#37379]
ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lucky\\AppData\\Local\\Temp\\pip-install-_fpxa43a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\lucky\\AppData\\Local\\Temp\\pip-install-_fpxa43a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\lucky\AppData\Local\Temp\pip-record-_1ewxcoj\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files (x86)\python38-32\Include\torch'
         cwd: C:\Users\lucky\AppData\Local\Temp\pip-install-_fpxa43a\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lucky\AppData\Local\Temp\pip-install-_fpxa43a\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "c:\program files (x86)\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files (x86)\python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files (x86)\python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files (x86)\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\lucky\AppData\Local\Temp\pip-install-_fpxa43a\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\program files (x86)\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\lucky\AppData\Local\Temp\pip-install-_fpxa43a\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lucky\\AppData\\Local\\Temp\\pip-install-_fpxa43a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\lucky\\AppData\\Local\\Temp\\pip-install-_fpxa43a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\lucky\AppData\Local\Temp\pip-record-_1ewxcoj\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files (x86)\python38-32\Include\torch' Check the logs for full command output.

**Comment by peterjc123** [comment]
Well, `pip install torch` won't work because windows wheels are not hosted on PyPI . Please try the steps on https://pytorch.org.

**Comment by peterjc123** [comment]
Well, you are using 32-bit Python. We don't release binaries for that. Please use 64-bit Python instead.
