### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered with channels_last

### ISSUE THREAD

**Issue by tstandley** [pytorch/pytorch#37449]
I get an illegal memory access when trying to train mnasnet (any version) with apex (O1) and channels_last

## To Reproduce

use the apex imagenet example:

python -m torch.distributed.launch --nproc_per_node=2 main_amp.py -a=mnasnet1_3 --b 224 --workers 4 --channels-last=True --opt-level=O1  -b=256 /intel_nvme/imagenet_data/

Traceback (most recent call last):
  File "main_amp.py", line 542, in <module>
    main()
  File "main_amp.py", line 247, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main_amp.py", line 353, in train
    scaled_loss.backward()
  File "/home/tstand/anaconda3/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/handle.py", line 123, in scale_loss
    optimizer._post_amp_backward(loss_scaler)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 249, in post_backward_no_master_weights
    post_backward_models_are_masters(scaler, params, stashed_grads)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 135, in post_backward_models_are_masters
    scale_override=(grads_have_scale, stashed_have_scale, out_scale))
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 184, in unscale_with_stashed
    out_scale/stashed_have_scale)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 148, in unscale_with_stashed_python
    self.dynamic)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 22, in axpby_check_overflow_python
    cpu_sum = float(model_grad.float().sum())
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f5827507536 in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7f582774afbe in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f58274f7abd in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5236b2 (0x7f58732c06b2 in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523756 (0x7f58732c0756 in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x19dfce (0x55748c40bfce in /home/tstand/anaconda3/bin/python)
frame #6: <unknown function> + 0x103948 (0x55748c371948 in /home/tstand/anaconda3/bin/python)
frame #7: <unknown function> + 0x114267 (0x55748c382267 in /home/tstand/anaconda3/bin/python)
frame #8: <unknown function> + 0x11427d (0x55748c38227d in /home/tstand/anaconda3/bin/python)
frame #9: <unknown function> + 0x11427d (0x55748c38227d in /home/tstand/anaconda3/bin/python)
frame #10: PyDict_SetItem + 0x502 (0x55748c3cd602 in /home/tstand/anaconda3/bin/python)
frame #11: PyDict_SetItemString + 0x4f (0x55748c3ce0cf in /home/tstand/anaconda3/bin/python)
frame #12: PyImport_Cleanup + 0x9e (0x55748c40d91e in /home/tstand/anaconda3/bin/python)
frame #13: Py_FinalizeEx + 0x67 (0x55748c483367 in /home/tstand/anaconda3/bin/python)
frame #14: <unknown function> + 0x227d93 (0x55748c495d93 in /home/tstand/anaconda3/bin/python)
frame #15: _Py_UnixMain + 0x3c (0x55748c4960bc in /home/tstand/anaconda3/bin/python)
frame #16: __libc_start_main + 0xf3 (0x7f5875ba81e3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #17: <unknown function> + 0x1d0990 (0x55748c43e990 in /home/tstand/anaconda3/bin/python)

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "main_amp.py", line 542, in <module>
    main()
  File "main_amp.py", line 247, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main_amp.py", line 353, in train
    scaled_loss.backward()
  File "/home/tstand/anaconda3/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/handle.py", line 123, in scale_loss
    optimizer._post_amp_backward(loss_scaler)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 249, in post_backward_no_master_weights
    post_backward_models_are_masters(scaler, params, stashed_grads)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 135, in post_backward_models_are_masters
    scale_override=(grads_have_scale, stashed_have_scale, out_scale))
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 184, in unscale_with_stashed
    out_scale/stashed_have_scale)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 148, in unscale_with_stashed_python
    self.dynamic)
  File "/home/tstand/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 22, in axpby_check_overflow_python
    cpu_sum = float(model_grad.float().sum())
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f911c250536 in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7f911c493fbe in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f911c240abd in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5236b2 (0x7f91680096b2 in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523756 (0x7f9168009756 in /home/tstand/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x19dfce (0x5599d63f8fce in /home/tstand/anaconda3/bin/python)
frame #6: <unknown function> + 0x103948 (0x5599d635e948 in /home/tstand/anaconda3/bin/python)
frame #7: <unknown function> + 0x114267 (0x5599d636f267 in /home/tstand/anaconda3/bin/python)
frame #8: <unknown function> + 0x11427d (0x5599d636f27d in /home/tstand/anaconda3/bin/python)
frame #9: <unknown function> + 0x11427d (0x5599d636f27d in /home/tstand/anaconda3/bin/python)
frame #10: PyDict_SetItem + 0x502 (0x5599d63ba602 in /home/tstand/anaconda3/bin/python)
frame #11: PyDict_SetItemString + 0x4f (0x5599d63bb0cf in /home/tstand/anaconda3/bin/python)
frame #12: PyImport_Cleanup + 0x9e (0x5599d63fa91e in /home/tstand/anaconda3/bin/python)
frame #13: Py_FinalizeEx + 0x67 (0x5599d6470367 in /home/tstand/anaconda3/bin/python)
frame #14: <unknown function> + 0x227d93 (0x5599d6482d93 in /home/tstand/anaconda3/bin/python)
frame #15: _Py_UnixMain + 0x3c (0x5599d64830bc in /home/tstand/anaconda3/bin/python)
frame #16: __libc_start_main + 0xf3 (0x7f916a8f11e3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #17: <unknown function> + 0x1d0990 (0x5599d642b990 in /home/tstand/anaconda3/bin/python)

Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 19.10
GCC version: (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect (not installed outside pytorch)
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 440.82
cuDNN version: Could not collect (not installed outside pytorch)

Versions of relevant libraries:
[pip3] numpy==1.18.3
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_0  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0    conda-forge
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch

**Comment by xwang233** [comment]
I tried this on my 2070 at master with `CUDA_LAUNCH_BLOCKING=1` and got `RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED (operator() at ../aten/src/ATen/native/cudnn/Conv.cpp:981)`. However, it is working fine on V100.

**Comment by ngimel** [comment]
Setting hi-pri because it's a crash, but looks like it is a cudnn bug, so not actionable on our side.

**Comment by xwang233** [comment]
This should've been fixed in the latest cudnn v8. https://developer.nvidia.com/cudnn

**Comment by tstandley** [comment]
Does the nightly pytorch release bundle cudnn 8 yet?

**Comment by ezyang** [comment]
not sure. paging binaries peeps

**Comment by gemfield** [comment]
With Pytorch 1.6 / CUDA 10.2 /CUDNN7, I got follow error occasionally:
```bash
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train(None)
  File "/gemfield/hostpv/gemfield/deepvac/lib/syszux_deepvac.py", line 335, in __call__
    self.process()
  File "train.py", line 163, in process
    self.processTrain()
  File "/gemfield/hostpv/gemfield/deepvac/lib/syszux_deepvac.py", line 294, in processTrain
    self.doBackward()
  File "train.py", line 139, in doBackward
    self.loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1595629403081/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7fb3e291677d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xb5d (0x7fb3e2b66d9d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fb3e2902b1d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x53f0ea (0x7fb41c1990ea in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #17: __libc_start_main + 0xe7 (0x7fb442bdfb97 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

**Comment by ptrblck** [comment]
Double post from [the forum](https://discuss.pytorch.org/t/cuda-error-an-illegal-instruction-was-encountered/88326/3?u=ptrblck). 
> Could you post a minimal code snippet to reproduce this issue as well as your currently installed NVIDIA driver and the GPU you are using?

**Comment by gemfield** [comment]
@ptrblck 
Very strange... after decrese the batch size, the error just gone.

**Comment by gautamsreekumar** [comment]
I had a similar issue which disappeared when I decreased the batch size. Any idea as to why this is happening? I was using PyTorch AMP in conda environment. PyTorch == 1.7.0, cudatoolkit==11.0.221

**Comment by robin5540** [comment]
@xwang233 Not sure if I'm running into the same bug. Here is the symptom I see on RTX5000 / CUDA11 / cuDNN8 / pytorch 1.7.1
```
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([6, 512, 196, 350], dtype=torch.half, device='cuda', requires_grad=True).to(memory_format=torch.channels_last)
net = torch.nn.Conv2d(512, 16, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half().to(memory_format=torch.channels_last)
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f6cac075260
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 6, 512, 196, 350,
    strideA = 35123200, 1, 179200, 512,
output: TensorDescriptor 0x7f6cac003120
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 6, 16, 196, 350,
    strideA = 1097600, 1, 5600, 16,
weight: FilterDescriptor 0x7f6cac07dee0
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NHWC
    nbDims = 4
    dimA = 16, 512, 1, 1,
Pointer addresses:
    input: 0x7f6fee000000
    output: 0x7f6cf8000000
    weight: 0x7f6c375f8000
Additional pointer addresses:
    grad_output: 0x7f6cf8000000
    grad_input: 0x7f6fee000000
Backward data algorithm: 1

  In call to configurable 'train_model' (<function train_model at 0x7f73a5d70488>) in scope 'train'
```

The repro generated doesn't when running inside ipython.

When running on V100 / CUDA 10 / cuDNN7 / pytorch 1.6.0
I get OOM, or no valid cuDNN conv algo error.

**Comment by xwang233** [comment]
@robin5540 Thanks for reporting the issue. Are you running a distributed training (DDP) or a single GPU model?

**Comment by sidroopdaska** [comment]
Any update as to why this occurs and a potential resolution?

**Comment by Hazarapet** [comment]
+1
