### ISSUE TITLE
RuntimeError: Shared memory manager connection has timed out at /tmp/pip-req-build-ufslq_a9/torch/lib/libshm/core.cpp:99

### ISSUE THREAD

**Issue by Wenqian1228** [pytorch/pytorch#37482]
## ❓ Questions and Help

when I train on the default config, after a few epochs,  I run into this error
`epoch 5, lr: 7.1e-02, cls: 0.093, ctr: 0.031, reg: 0.887, iou: 0.757, data: 1.2e-04, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.093, ctr: 0.031, reg: 0.887, iou: 0.757, data: 1.2e-04, fwd: 3.0e-01, bwd: 1.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.098, ctr: 0.035, reg: 0.886, iou: 0.756, data: 1.1e-04, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.098, ctr: 0.035, reg: 0.886, iou: 0.756, data: 1.1e-04, fwd: 3.0e-01, bwd: 1.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.100, ctr: 0.033, reg: 0.897, iou: 0.754, data: 9.2e-05, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.100, ctr: 0.033, reg: 0.897, iou: 0.754, data: 9.2e-05, fwd: 3.0e-01, bwd: 1.5e-01, optim
: 2.2e-01, :  18%|█▊        | 106/585 [04:24<20:47,  2.60s/it]Traceback (most recent call last):
  File "./main/train.py", line 111, in <module>
    trainer.train()
  File "/mnt/lustre/zhaowenqian/tracking/video_analyst-master/videoanalyst/engine/trainer/trainer_impl/regular_trainer.py", line 100, in train
    training_data = next(self._dataloader)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Shared memory manager connection has timed out at /tmp/pip-req-build-ufslq_a9/torch/lib/libshm/core.cpp:99`

which I cannot locate where the problem is
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by lufol** [comment]
I noticed that you use multiple workers for the dataloader. Could you rerun your code with `num_workers=0` in the DataLoader and see if this error persists?

**Comment by ngimel** [comment]
Please ask questions on the forums, discuss.pytorch.org.
