### ISSUE TITLE
DISABLED test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#37495]
This test is failing intermittently on multiple builds with increasing frequency recently and no clear cause. 

```
Apr 29 09:14:17 ======================================================================
Apr 29 09:14:17 ERROR [0.030s]: test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)
Apr 29 09:14:17 ----------------------------------------------------------------------
Apr 29 09:14:17 Traceback (most recent call last):
Apr 29 09:14:17   File "/var/lib/jenkins/workspace/test/quantization/test_quantize.py", line 862, in test_default_quantized_lstm
Apr 29 09:14:17     y, (h, c) = cell_dq(x, (h, c))
Apr 29 09:14:17   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 562, in __call__
Apr 29 09:14:17     result = self.forward(*input, **kwargs)
Apr 29 09:14:17   File "/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py", line 351, in forward
Apr 29 09:14:17     return self.forward_tensor(input, hx)
Apr 29 09:14:17   File "/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py", line 312, in forward_tensor
Apr 29 09:14:17     input, hx, batch_sizes, max_batch_size, sorted_indices)
Apr 29 09:14:17   File "/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py", line 293, in forward_impl
Apr 29 09:14:17     self.batch_first, dtype=self.dtype, use_dynamic=True)
Apr 29 09:14:17 RuntimeError: In ChooseQuantizationParams, min should be less than or equal to max
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo @ezyang @gchanan @zou3519

**Comment by supriyar** [comment]
@raghuramank100 this should be resolved now, right?

**Comment by vkuzo** [comment]
this test does not exist anymore
