### ISSUE TITLE
test_tiny_half_norm_ is consistently failing on ROCm

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#37493]
Log from py3.6-clang7-rocmdeb-ubuntu16.04-test2:

```
07:47:45 ======================================================================
07:47:45 FAIL: test_tiny_half_norm_ (__main__.TestCuda)
07:47:45 ----------------------------------------------------------------------
07:47:45 Traceback (most recent call last):
07:47:45   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 699, in wrapper
07:47:45     method(*args, **kwargs)
07:47:45   File "test_cuda.py", line 1820, in test_tiny_half_norm_
07:47:45     self.assertGreater(b.norm().item(), 0)
07:47:45 AssertionError: 0.0 not greater than 0
07:47:45 
07:47:45 ----------------------------------------------------------------------
```

**Comment by kshitij12345** [comment]
Reference : https://github.com/pytorch/pytorch/pull/36653
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/37375/
