### ISSUE TITLE
tensor_iterator_test: AddressSanitizer: heap-buffer-overflow

### ISSUE THREAD

**Issue by aditya7fb** [pytorch/pytorch#37490]
## 🐛 Bug
==52671==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x609000000318 at pc 0x000105a224f8 bp 0x7ffeea2820a0 sp 0x7ffeea282098
WRITE of size 4 at 0x609000000318 thread T0

## To Reproduce

1. Built on Mac with USE_ASAN:BOOL=ON (python3 setup.py install)
2. ninja -j8
3. ./bin/tensor_iterator_test 

```
==52671==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x609000000318 at pc 0x000105a224f8 bp 0x7ffeea2820a0 sp 0x7ffeea282098
WRITE of size 4 at 0x609000000318 thread T0
    #0 0x105a224f7 in void c10::function_ref<void (char**, long long const*, long long)>::callback_fn<void at::native::(anonymous namespace)::cpu_serial_kernel<TensorIteratorTest_SerialLoopUnary_Byte_Test::TestBody()::$_0>(at::TensorIterator&, TensorIteratorTest_SerialLoopUnary_Byte_Test::TestBody()::$_0&&)::'lambda'(char**, long long const*, long long)>(long, char**, long long const*, long long) (tensor_iterator_test:x86_64+0x1000a64f7)
    #1 0x10b190868 in void c10::function_ref<void (char**, long long const*, long long, long long)>::callback_fn<at::TensorIterator::serial_for_each(c10::function_ref<void (char**, long long const*, long long)>, at::Range) const::$_7>(long, char**, long long const*, long long, long long) (libtorch_cpu.dylib:x86_64+0xf72868)
    #2 0x10b17785f in at::TensorIterator::serial_for_each(c10::function_ref<void (char**, long long const*, long long, long long)>, at::Range) const (libtorch_cpu.dylib:x86_64+0xf5985f)
    #3 0x10b178645 in at::TensorIterator::serial_for_each(c10::function_ref<void (char**, long long const*, long long)>, at::Range) const (libtorch_cpu.dylib:x86_64+0xf5a645)
    #4 0x105987e94 in TensorIteratorTest_SerialLoopUnary_Byte_Test::TestBody() (tensor_iterator_test:x86_64+0x10000be94)
    #5 0x105a99e45 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (tensor_iterator_test:x86_64+0x10011de45)
    #6 0x105a99b48 in testing::Test::Run() (tensor_iterator_test:x86_64+0x10011db48)
    #7 0x105a9d813 in testing::TestInfo::Run() (tensor_iterator_test:x86_64+0x100121813)
    #8 0x105a9f9e4 in testing::TestCase::Run() (tensor_iterator_test:x86_64+0x1001239e4)
    #9 0x105ad1e44 in testing::internal::UnitTestImpl::RunAllTests() (tensor_iterator_test:x86_64+0x100155e44)
    #10 0x105ad0905 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (tensor_iterator_test:x86_64+0x100154905)
    #11 0x105ad063b in testing::UnitTest::Run() (tensor_iterator_test:x86_64+0x10015463b)
    #12 0x105a5c81f in main (tensor_iterator_test:x86_64+0x1000e081f)
    #13 0x7fff67beecc8 in start (libdyld.dylib:x86_64+0x1acc8)

0x609000000319 is located 0 bytes to the right of 25-byte region [0x609000000300,0x609000000319)
allocated by thread T0 here:
    #0 0x105cbafb0 in wrap_posix_memalign (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x43fb0)
    #1 0x105bc80ad in c10::alloc_cpu(unsigned long) (libc10.dylib:x86_64+0x80ad)
    #2 0x105bcbbdc in c10::DefaultCPUAllocator::allocate(unsigned long) const (libc10.dylib:x86_64+0xbbdc)
    #3 0x10b0e68fb in at::native::empty_cpu(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0xec88fb)
    #4 0x10b8e0fed in at::CPUType::empty_memory_format(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0x16c2fed)
    #5 0x10b887c0e in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat> > >, at::Tensor (c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0x1669c0e)
    #6 0x10b88776f in at::(anonymous namespace)::empty_memory_format(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0x166976f)
    #7 0x10b887c0e in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat> > >, at::Tensor (c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0x1669c0e)
    #8 0x10a24d9b9 in at::Tensor c10::OperatorHandle::callUnboxed<at::Tensor, c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat> >(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) const (libtorch_cpu.dylib:x86_64+0x2f9b9)
    #9 0x1124020f0 in torch::autograd::VariableType::empty_memory_format(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0x81e40f0)
    #10 0x10b887c0e in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat> > >, at::Tensor (c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) (libtorch_cpu.dylib:x86_64+0x1669c0e)
    #11 0x10a24d9b9 in at::Tensor c10::OperatorHandle::callUnboxed<at::Tensor, c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat> >(c10::ArrayRef<long long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) const (libtorch_cpu.dylib:x86_64+0x2f9b9)
    #12 0x10b1863d8 in at::TensorIterator::fast_set_up() (libtorch_cpu.dylib:x86_64+0xf683d8)
    #13 0x10b17bee9 in at::TensorIterator::build() (libtorch_cpu.dylib:x86_64+0xf5dee9)
    #14 0x10b17d3d1 in at::TensorIterator::unary_op(at::Tensor&, at::Tensor const&, bool) (libtorch_cpu.dylib:x86_64+0xf5f3d1)
    #15 0x105987db8 in TensorIteratorTest_SerialLoopUnary_Byte_Test::TestBody() (tensor_iterator_test:x86_64+0x10000bdb8)
    #16 0x105a99e45 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (tensor_iterator_test:x86_64+0x10011de45)
    #17 0x105a99b48 in testing::Test::Run() (tensor_iterator_test:x86_64+0x10011db48)
    #18 0x105a9d813 in testing::TestInfo::Run() (tensor_iterator_test:x86_64+0x100121813)
    #19 0x105a9f9e4 in testing::TestCase::Run() (tensor_iterator_test:x86_64+0x1001239e4)
    #20 0x105ad1e44 in testing::internal::UnitTestImpl::RunAllTests() (tensor_iterator_test:x86_64+0x100155e44)
    #21 0x105ad0905 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (tensor_iterator_test:x86_64+0x100154905)
    #22 0x105ad063b in testing::UnitTest::Run() (tensor_iterator_test:x86_64+0x10015463b)
    #23 0x105a5c81f in main (tensor_iterator_test:x86_64+0x1000e081f)
    #24 0x7fff67beecc8 in start (libdyld.dylib:x86_64+0x1acc8)

SUMMARY: AddressSanitizer: heap-buffer-overflow (tensor_iterator_test:x86_64+0x1000a64f7) in void c10::function_ref<void (char**, long long const*, long long)>::callback_fn<void at::native::(anonymous namespace)::cpu_serial_kernel<TensorIteratorTest_SerialLoopUnary_Byte_Test::TestBody()::$_0>(at::TensorIterator&, TensorIteratorTest_SerialLoopUnary_Byte_Test::TestBody()::$_0&&)::'lambda'(char**, long long const*, long long)>(long, char**, long long const*, long long)
Shadow bytes around the buggy address:
  0x1c1200000010: fa fa fa fa fa fa fa fa 00 00 00 01 fa fa fa fa
  0x1c1200000020: fa fa fa fa fa fa fa fa fd fa fa fa fa fa fa fa
  0x1c1200000030: fa fa fa fa fa fa fa fa fd fa fa fa fa fa fa fa
  0x1c1200000040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1200000050: 00 00 00 01 fa fa fa fa fa fa fa fa fa fa fa fa
=>0x1c1200000060: 00 00 00[01]fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1200000070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1200000080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1200000090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c12000000a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c12000000b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==52671==ABORTING
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): top of the trunk
 - OS (e.g., Linux): Macos
 - How you installed PyTorch (`conda`, `pip`, source): git clone
 - Build command you used (if compiling from source): ninja
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by ngimel** [comment]
cc @malfet - do you think it's a false positive or a real bug?

**Comment by ngimel** [comment]
Setting hi-pri for now, looks like a bug. Strange that it is not caught in the CI.

**Comment by malfet** [comment]
This looks real. And I'm really curious why it wasn't detected in CI. Perhaps because currently ASAN tests are run using clang-5. Let's see if this will get detected by clang-9 ASAN testing.
