### ISSUE TITLE
Segfault while exiting multiprocess spawn on Ubuntu 20.04

### ISSUE THREAD

**Issue by sclarkson** [pytorch/pytorch#37663]
## 🐛 Bug

Mutliprocess spawn can segfault while exiting the parent process on glibc 2.3.1

```
$ python3.8 test/distributed/test_c10d_spawn.py
........
----------------------------------------------------------------------
Ran 8 tests in 41.343s

OK
Segmentation fault (core dumped)
```

## To Reproduce

1. Install pytorch 1.5.0 with pip on Ubuntu 20.04
1. Run c10d_spawn unit test `python3.8 pytorch/test/distributed/test_c10d_spawn.py`
1. Observe that all tests succeed, but that the process segfaults while exiting

## Expected behavior

Parent process should exit cleanly

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): n/a
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2 / 7.6.5
 - GPU models and configuration: 2x 980 Ti
 - Any other relevant information:

## Additional context

I compiled a debug build from source to get the backtrace.

```
#0  __memcmp_avx2_movbe () at ../sysdeps/x86_64/multiarch/memcmp-avx2-movbe.S:267
#1  0x00007fffcdbdbd6c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fffcab58609 in std::operator< <char, std::char_traits<char>, std::allocator<char> > (__lhs="/torch_16_2081822676", __rhs=<error: Cannot access memory at address 0x7000700070007>) at /usr/include/c++/9/bits/basic_string.h:6229
#3  0x00007fffcab57b0f in std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (this=0x7fffcbbd3450 <torch::(anonymous namespace)::cuda_ipc_global_entities+48>, 
    __x="/torch_16_2081822676", __y=<error: Cannot access memory at address 0x7000700070007>) at /usr/include/c++/9/bits/stl_function.h:386
#4  0x00007fffcab52c1e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> > > >::_M_lower_bound (this=0x7fffcbbd3450 <torch::(anonymous namespace)::cuda_ipc_global_entities+48>, __x=0x45be6db0, __y=0x7fffcbbd3458 <torch::(anonymous namespace)::cuda_ipc_global_entities+56>, 
    __k=<error: Cannot access memory at address 0x7000700070007>) at /usr/include/c++/9/bits/stl_tree.h:1929
#5  0x00007fffcab524bf in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> > > >::lower_bound (this=0x7fffcbbd3450 <torch::(anonymous namespace)::cuda_ipc_global_entities+48>, __k=<error: Cannot access memory at address 0x7000700070007>)
    at /usr/include/c++/9/bits/stl_tree.h:1282
#6  0x00007fffcab51e15 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> > > >::lower_bound (this=0x7fffcbbd3450 <torch::(anonymous namespace)::cuda_ipc_global_entities+48>, __x=<error: Cannot access memory at address 0x7000700070007>) at /usr/include/c++/9/bits/stl_map.h:1258
#7  0x00007fffcab518f7 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<torch::(anonymous namespace)::CudaIPCRefCountersFile> > > >::operator[] (this=0x7fffcbbd3450 <torch::(anonymous namespace)::cuda_ipc_global_entities+48>, __k=<error: Cannot access memory at address 0x7000700070007>) at /usr/include/c++/9/bits/stl_map.h:495
#8  0x00007fffcab50983 in torch::(anonymous namespace)::ReturnRefCounter (handle=<error: Cannot access memory at address 0x7000700070007>, offset=1970350607237127) at ../torch/csrc/CudaIPCTypes.cpp:105
#9  0x00007fffcab51140 in torch::CudaIPCSentData::~CudaIPCSentData (this=0x958010, __in_chrg=<optimized out>) at ../torch/csrc/CudaIPCTypes.cpp:165
#10 0x00007fffcab5793e in std::default_delete<torch::CudaIPCSentData>::operator() (this=0x45074a78, __ptr=0x958010) at /usr/include/c++/9/bits/unique_ptr.h:81
#11 0x00007fffcab571f8 in std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> >::~unique_ptr (this=0x45074a78, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:292
#12 0x00007fffcab596be in std::_Destroy<std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> > > (__pointer=0x45074a78) at /usr/include/c++/9/bits/stl_construct.h:98
#13 0x00007fffcab58e36 in std::_Destroy_aux<false>::__destroy<std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> >*> (__first=0x45074a78, __last=0x45074ae0) at /usr/include/c++/9/bits/stl_construct.h:108
#14 0x00007fffcab58054 in std::_Destroy<std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> >*> (__first=0x45074a70, __last=0x45074ae0) at /usr/include/c++/9/bits/stl_construct.h:137
#15 0x00007fffcab5775d in std::_Destroy<std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> >*, std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> > > (__first=0x45074a70, 
    __last=0x45074ae0) at /usr/include/c++/9/bits/stl_construct.h:206
#16 0x00007fffcab56eb9 in std::vector<std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> >, std::allocator<std::unique_ptr<torch::CudaIPCSentData, std::default_delete<torch::CudaIPCSentData> > > >::~vector
    (this=0x7fffcbbd3490 <torch::(anonymous namespace)::cuda_ipc_global_entities+112>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_vector.h:677
#17 0x00007fffcab50531 in torch::(anonymous namespace)::CudaIPCSentDataLimbo::~CudaIPCSentDataLimbo (this=0x7fffcbbd3490 <torch::(anonymous namespace)::cuda_ipc_global_entities+112>, __in_chrg=<optimized out>)
    at ../torch/csrc/CudaIPCTypes.cpp:55
#18 0x00007fffcab503a7 in torch::(anonymous namespace)::CudaIPCGlobalEntities::~CudaIPCGlobalEntities (this=0x7fffcbbd3420 <torch::(anonymous namespace)::cuda_ipc_global_entities>, __in_chrg=<optimized out>)
    at ../torch/csrc/CudaIPCTypes.cpp:36
#19 0x00007ffff7e19a27 in __run_exit_handlers (status=0, listp=0x7ffff7fbb718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#20 0x00007ffff7e19be0 in __GI_exit (status=<optimized out>) at exit.c:139
#21 0x00000000006775f7 in Py_Exit (sts=0) at ../Python/pylifecycle.c:2299
#22 0x000000000067761b in handle_system_exit () at ../Python/pythonrun.c:658
#23 0x0000000000677842 in _PyErr_PrintEx (set_sys_last_vars=1, tstate=0x95c810) at ../Python/pythonrun.c:763
#24 PyErr_PrintEx (set_sys_last_vars=1) at ../Python/pythonrun.c:763
#25 0x0000000000678484 in PyErr_Print () at ../Python/pythonrun.c:769
#26 PyRun_SimpleFileExFlags (fp=<optimized out>, filename=<optimized out>, closeit=<optimized out>, flags=0x7fffffffe398) at ../Python/pythonrun.c:434
#27 0x00000000006af6ce in pymain_run_file (cf=0x7fffffffe398, config=0x95bb70) at ../Modules/main.c:381
#28 pymain_run_python (exitcode=0x7fffffffe390) at ../Modules/main.c:565
#29 Py_RunMain () at ../Modules/main.c:644
#30 0x00000000006afa59 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:698
#31 0x00007ffff7df70b3 in __libc_start_main (main=0x4ec760 <main>, argc=2, argv=0x7fffffffe578, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe568) at ../csu/libc-start.c:308
#32 0x00000000005f6ede in _start () at ../Objects/obmalloc.c:1233
```

**Comment by ezyang** [comment]
cc @VitalyFedyunin

**Comment by mrshenli** [comment]
add a data point: cannot reproduce this on Ubuntu 18.04 with glibc 2.27

**Comment by mrshenli** [comment]
cc @agolynski

**Comment by sclarkson** [comment]
I compiled python3.6 and python3.7 on 20.04, and neither crashed.I compiled python3.8 on 18.04, and it did not crash either. So it appears that this is 20.04 and python3.8 specific.

I tried to do a bisect on python, but ran into some issues. Will try again shortly.

**Comment by agolynski** [comment]
this seems obsolete at this point. @sclarkson feel free to reopen the issue if you have more data.
