### ISSUE TITLE
[CI] Test Distributed : test_all_gather_multigpu (__main__.TestDistBackend)

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#37669]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/26118/console
```
23:00:29 ======================================================================
23:00:29 ERROR: test_all_gather_multigpu (__main__.TestDistBackend)
23:00:29 ----------------------------------------------------------------------
23:00:29 Traceback (most recent call last):
23:00:29   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 184, in wrapper
23:00:29     self._join_processes(fn)
23:00:29   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in _join_processes
23:00:29     self._check_return_codes(elapsed_time)
23:00:29   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 324, in _check_return_codes
23:00:29     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
23:00:29 RuntimeError: Process 0 terminated or timed out after 100.08543348312378 seconds
23:00:29 
23:00:29 ----------------------------------------------------------------------
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment]
cc @agolynski

**Comment by mrshenli** [comment]
Closing for now as this no longer shows on master. Please feel free to reopen if this emerges again.
