### ISSUE TITLE
Hooks don't propagate error, try to call __name__

### ISSUE THREAD

**Issue by Ge0rges** [pytorch/pytorch#37672]
## 🐛 Bug

Hello all. This bug originally posted on discuss [here](https://discuss.pytorch.org/t/pytorch-expects-hook-to-have-name/78709/6).

Original crash was because `module.register_hook()` expected an object on which `__name__` could be called. Investigation led @albanD to find that errors aren't being propagated up, and hooks require a `try: except:` block around them. With that block however, this bug still persists. Below is code to reproduce the bug. 

## To Reproduce
Run the code below.

```
import torch.nn as nn
import torch
import numpy as np
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import os

from torch.utils.data import DataLoader, RandomSampler

# You should be able to ignore this
class SimpleModel(nn.Module):
    def __init__(self, sizes):
        super(SimpleModel, self).__init__()
        # Encoder
        encoder_layers = self.set_module('encoder', sizes)
        encoder_layers.append(nn.Sigmoid())
        self.encoder = nn.Sequential(*encoder_layers)

    def forward(self, x):
        x = self.encoder(x)
        return x

    def set_module(self, label, sizes):
        sizes = sizes[label]

        layers = [self.get_layer(sizes[0], sizes[1])]

        for i in range(1, len(sizes) - 1):
            layers.append(nn.LeakyReLU())
            layers.append(self.get_layer(sizes[i], sizes[i+1]))

        return layers

    def get_layer(self, input, output):
        layer = nn.Linear(input, output)
        torch.nn.init.kaiming_uniform_(layer.weight, mode='fan_in', nonlinearity='leaky_relu')

        return layer

def get_modules(model):
    modules = {}

    for name, param in model.named_parameters():
        module = name[0: name.index('.')]

        if module not in modules.keys():
            modules[module] = []

        modules[module].append((name, param))

    return modules

# Hook class
class ActiveGradsHook:
    def __init__(self, previously_active: [bool], currently_active: [bool], bias=False):

        # Could be None for biases
        if previously_active is not None:
            self.previously_active = torch.BoolTensor(previously_active).long().nonzero().view(-1).numpy()

        # Should never be None
        self.currently_active = torch.BoolTensor(currently_active).long().nonzero().view(-1).numpy()

        self.is_bias = bias

        # self.__name__ = None # THIS WILL FIX YOUR CRASH

    def __call__(self, grad):
        grad_clone = grad.clone().detach()

        if self.is_bias:
            grad_clone[self.currently_active] = 0

        else:
            grad_clone[self.currently_active, :] = 0
            grad_clone[:, self.previously_active] = 0

        return grad_clone

def train_new_neurons(old_sizes, new_sizes, model, batch_loader, optimizer):
    # Generate hooks for each layer
    hooks = []
    modules = get_modules(model)

    for module_name, parameters in modules.items():
        previously_active_weights = [False] * new_sizes[module_name][0]

        for param_name, param in parameters:
            split_param_name = param_name.split(".")  # Splits action.0.weights
            param_index = int(split_param_name[1])

            # Map every two indices to one
            param_index -= param_index % 2
            param_index /= 2
            param_index = int(param_index)

            old_size = old_sizes[module_name][param_index + 1]
            new_size = new_sizes[module_name][param_index + 1]
            neurons_added = new_size - old_size

            # Input/Output must stay the same
            if param_index == len(old_sizes[module_name]) - 1:
                assert old_size == new_size
                continue

            # Freeze biases/weights
            if "bias" in param_name:
                active_biases = [False] * old_size + [True] * neurons_added
                hook = ActiveGradsHook(None, active_biases, bias=True)

                hook = param.register_hook(hook)
                hooks.append(hook)

            else:

                active_weights = [False] * old_size + [True] * neurons_added
                hook = ActiveGradsHook(previously_active_weights, active_weights, bias=False)

                hook = param.register_hook(hook)
                hooks.append(hook)

                previously_active_weights = active_weights

    # Train simply
    train(batch_loader, model, optimizer)

    # Remove hooks
    for hook in hooks:
        hook.remove()


def train(batch_loader, model, optimizer):
    for batch_idx, (inputs, action_target) in enumerate(batch_loader):
        with torch.autograd.detect_anomaly():

            action_output = model(inputs)

            criterion = torch.nn.BCELoss()
            action_loss = criterion(action_output, action_target)

            # Compute gradient and do SGD step
            optimizer.zero_grad()
            action_loss.backward()
            optimizer.step()


def get_mnist_loader():
    dataset = datasets.MNIST

    def one_hot_mnist(targets):
        targets_onehot = torch.zeros(10)
        targets_onehot[targets] = 1
        return targets_onehot

    transform_all = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,)),
        transforms.Lambda(lambda a: a.view(-1))
    ])

    root = os.path.join(os.path.dirname(__file__), "./MNIST")
    dataset = dataset(root=root, train=True, download=True, transform=transform_all, target_transform=one_hot_mnist)

    sampler = RandomSampler(dataset)
    return DataLoader(dataset, sampler=sampler, batch_size=128, num_workers=0, pin_memory=False)


if __name__ == "__main__":
    sizes = {"encoder": [784, 312, 128, 10]}
    new_sizes = {"encoder": [784, 624, 256, 10]}

    model = SimpleModel(sizes)
    optimizer = torch.optim.SGD(model.parameters(), lr=1, momentum=0)
    mnist_loader = get_mnist_loader()

    train_new_neurons(sizes, new_sizes, model, mnist_loader, optimizer)

```

Below stack trace:

```
File "/Users/GeorgesKanaan/Documents/Development/Python/KNet/src/main_scripts/train.py", line 101, in l1
    penalty += param.norm(1)
  File "/Users/GeorgesKanaan/Documents/Development/Python/KNet/venv/lib/python3.8/site-packages/torch/tensor.py", line 342, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "/Users/GeorgesKanaan/Documents/Development/Python/KNet/venv/lib/python3.8/site-packages/torch/functional.py", line 838, in norm
    return _VF.norm(input, p)
 (print_stack at ../torch/csrc/autograd/python_anomaly_mode.cpp:60)
Traceback (most recent call last):
  File "/Users/GeorgesKanaan/Documents/Development/Python/KNet/src/main_scripts/train.py", line 58, in train
    total_loss.backward()
  File "/Users/GeorgesKanaan/Documents/Development/Python/KNet/venv/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/GeorgesKanaan/Documents/Development/Python/KNet/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError: 'ActiveGradsHook' object has no attribute '__name__'
```

To propagate the error, wrap the `_call_` method of the hook obejct in `try:except:`

## Expected behavior

Error is properly propagated, __name__ isn't called on hook.

## Environment

 - PyTorch Version: 1.5.0
 - OS: Ubuntu 19
 - How you installed PyTorch: pip
 - Python version: 3.7
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
First step will be to reduce the code sample to get a better idea where it comes from.

**Comment by Ge0rges** [comment]
@albanD I pruned some code from the reproduction sample. It's quite barebones now, the module is simple, there's a function to just get the MNIST data loader and then the longest function is untouchable as it's the one that generates the hooks.

**Comment by albanD** [comment]
The errors seems to be caused by this code [here](https://github.com/pytorch/pytorch/blob/b1790794f67f094e73a28174898d4714dfa96a52/torch/csrc/autograd/python_hook.cpp#L167) that assumes that `__name__` exists (which is always true for functions but might not be for custom objects).

**Comment by Ge0rges** [comment]
There was a bug I encountered where modules didn't like having attributes with names that started with '__' could this be related?

**Comment by Ge0rges** [comment]
Let me know if I can be of any more help. I don't have a good enough grasp on the pytorch code base to submit a commit myself fro this unfortunately.
