### ISSUE TITLE
Pickling of _VariableFunctions no longer works in 1.5

### ISSUE THREAD

**Issue by amatsukawa** [pytorch/pytorch#37703]
## 🐛 Bug

Pickling basic things in torch that are `torch._C._VariableFunctions` seems to no longer work. Pickling is core to the functioning of various libraries, such as pyspark with cloudpickle.

## To Reproduce 

```
(pytorch15)$ python
Python 3.8.2 (default, Mar 26 2020, 10:43:30)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.5.0'
>>> import pickle
>>> pickle.dumps(torch.tanh)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'torch._C._VariableFunctions'>: it's not the same object as torch._C._VariableFunctions
```

## Expected behavior

Pickling should work.

## Environment
```
(pytorch15)$ python collect_env.py
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py38hfbe908c_0
[conda] mkl_fft                   1.0.15           py38h5e564d8_0
[conda] mkl_random                1.1.0            py38h6440ff4_0
[conda] numpy                     1.18.1           py38h7241aed_0
[conda] numpy-base                1.18.1           py38h6575580_1
[conda] pytorch                   1.5.0                   py3.8_0    pytorch
```
## Additional context

This works in v1.4
```
(pytorch14)$ python
Python 3.8.2 (default, Mar 26 2020, 10:43:30)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.4.0'
>>> import pickle
>>> pickle.dumps(torch.tanh)
b'\x80\x04\x95E\x00\x00\x00\x00\x00\x00\x00\x8c\x08builtins\x94\x8c\x07getattr\x94\x93\x94\x8c\x08torch._C\x94\x8c\x12_VariableFunctions\x94\x93\x94\x8c\x04tanh\x94\x86\x94R\x94.'
```

```
(pytorch14)$ python collect_env.py
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py38hfbe908c_0
[conda] mkl_fft                   1.0.15           py38h5e564d8_0
[conda] mkl_random                1.1.0            py38h6440ff4_0
[conda] numpy                     1.18.1           py38h7241aed_0
[conda] numpy-base                1.18.1           py38h6575580_1
[conda] pytorch                   1.4.0                   py3.8_0    pytorch
```

cc @ezyang @gchanan @zou3519 @yf225 @glaringlee

**Comment by amatsukawa** [comment]
Weirdly this pickling doesn't work _most_ of the time, but does in certain instances (eg. a class variable).

```
>>> import torch
>>> import pickle
>>> pickle.dumps({'key': torch.add})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'torch._C._VariableFunctions'>: it's not the same object as torch._C._VariableFunctions
>>> pickle.dumps((torch.add, torch.tanh))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'torch._C._VariableFunctions'>: it's not the same object as torch._C._VariableFunctions
>>> class A(object):
...   def __init__(self, f):
...     self.f = f
...
>>> a = A(torch.add)
>>> pickle.dumps(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'torch._C._VariableFunctions'>: it's not the same object as torch._C._VariableFunctions
>>> class B(object):
...   f = torch.tanh
...
>>> b = B()
>>> pickle.dumps(b)
b'\x80\x04\x95\x15\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x01B\x94\x93\x94)\x81\x94.'
```

**Comment by ngimel** [comment]
Hi priority because it is a crash and a regression.

**Comment by ezyang** [comment]
The error appears, because the class of VariableFunctions is incorrectly declared to be itself:

```
>>> print(torch._C._VariableFunctions)
<torch._C._VariableFunctions object at 0x7f06a62ea170>
>>> print(torch._C._VariableFunctions.__class__)
<class 'torch._C._VariableFunctions'>
```

**Comment by N3bul0** [comment]
This affects segmentation models from torchvision, too. Is there any way to mitigate without building pytorch from source?
I'd like to change back to 1.4.0 if that helps but the release archive starts with version 1.2.0 downwards.

**Comment by ezyang** [comment]
I can't think of a good workaround, besides some sort of monkeypatching (but I don't think you can monkeypatch C objects). Milestoning for 1.5.1 (cc @gchanan)

**Comment by NilsRethmeier** [comment]
If any newcomers come here and wonder how to fix this. Upgrading to 1.5.1 fixed the issue. Downgrading to 1.4.1 may too.

That is
`conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.1 -c pytorch` if you use vision
`conda install pytorch==1.5.1 cudatoolkit=10.1 -c pytorch` if you use NLP.

depending on your cuda version.
