### ISSUE TITLE
Forwad method for ModuleList/Dict

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#37718]
## 🚀 Feature
If all modules in a `ModuleList` or `ModuleDict` expect the same input, e.g., in an ensemble, it would be convenient to call forward directly on the List/Dict. This could potentially also lead to  speed up (compared to `[module(x) for module in module_list]`) if the individual models could process the data in parallel.

## Motivation
Convenience and potential speed up.

## Pitch
A forward function for `ModuleList` and `ModuleDict` that forwards any *args and **kwargs to the individual models in a parallel manner (returning a list/dict of what ever the forward method returns).

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/36459

**Comment by ngimel** [comment]
So there's a pretty easy workaround (`[module(x) for module in module_list]`) and realizing speed-ups for generic modules is pretty hard. I'm not convinced that having this as a feature is very useful.

**Comment by twoertwein** [comment]
Wouldn't `torch.jit.fork` and `torch.jit.wait` would be a perfect way to implement that?

For ModuleList
```py
def forward(self, *args, **kwargs):
    futures = [torch.jit.fork(module, *args, **kwargs) for module in self.module_list]
    return [torch.jit.wait(future) for future in futures]
```
For ModuleDict
```py
def forward(self, *args, **kwargs):
    futures = {name: torch.jit.fork(module, *args, **kwargs) for name, module in self.module_dict.items()}
    return {name: torch.jit.wait(future) for name, future in futures.items()]
```

**Comment by vadimkantorov** [comment]
Currently ModuleDict error is not very clear (I think it should error out clearly with "forward not supported"):
```
>>> torch.nn.ModuleDict(dict(a = torch.nn.Linear(2, 2), b = torch.nn.Linear(2, 4)))(torch.rand(3, 2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 1 positional argument but 2 were given
```

https://discuss.pytorch.org/t/mix-of-nn-sequential-and-nn-moduledict/104724

**Comment by shaibagon** [comment]
I second @vadimkantorov : This is the same for `ModuleList`, see [this SO question](https://stackoverflow.com/q/65096679/1714410).

If you decide to stay with `NotImplementedError` in `forward` you need to make sure the code gets there. 

Maybe adding explicit `__call__` method that throws the `NotImplementedError` as well to get a better error message faster?

**Comment by vadimkantorov** [comment]
I think NotImplemented in `forward` may be better, because it could then be overridden if someone derives from ModuleDict

**Comment by shaibagon** [comment]
@vadimkantorov I see your point. We can leave the existing `ModuleList`/`ModuleDict` as-is (apart from #48698) and have all the fancy `forward` options people request here implemented in derived class, e.g. `ModuleListParallel`.

The thing is I'm not sure the "default" behavior of `ModuleList` should be to apply all the sub-modules in parallel, as requested here. I don't think we should change the default behavior. But we do need to have a clear error message when someone tries to `forward` through a `ModuleList`.

**Comment by vadimkantorov** [comment]
> (apart from #48698)

If derived classes are accounted for - probably better to adjust that PR to make forward throw NotImplemented. Otherwise, the implementor would have to override both forward and `__call__`

**Comment by shaibagon** [comment]
@vadimkantorov I took your advice implementing #48698 - it only fixes `forward` method such that it will actually reach the `NotImplementedError` in the `forward` and not throw the `TypeError` as you witnessed yourself.

I did _not_ change anything w.r.t `__call__` in either `ModuleList` nor `ModuleDict` in #48698, as you suggested.

It would be tremendously kind if you could peak at #48698, and perhaps even "support" it.

**Comment by eellison** [comment]
> def forward(self, *args, **kwargs):
    futures = [torch.jit.fork(module, *args, **kwargs) for module in self.module_list]
    return [torch.jit.wait(future) for future in futures]

@twoertwein that only works if you assume that each module independently applies the inputs, which i'm not sure is a valid  assumption for all  ModuleLists. 

However, for your own implementation you can achieve by subclassing ModuleList/ModuleDict
```
import torch
from torch import nn

class CustomModuleList(nn.ModuleList):
    def __init__(self):
        super(CustomModuleList, self).__init__(
            [nn.ReLU(), nn.ReLU()])

    def forward(self, x):
        futures = [torch.jit.fork(module, x) for module in self]
        return [torch.jit.wait(future) for future in futures]

torch.jit.script(CustomModuleList()) # compiles
```

**Comment by twoertwein** [comment]
thanks for the example!

> @twoertwein that only works if you assume that each module independently applies the inputs, which i'm not sure is a valid assumption for all ModuleLists.

I assume people would use `Sequential` and not `ModuleList` in such a case. Or more generally, if there is an arbitrary dependency, people wouldn't call `forward` on `ModuleList` as there is no way it can magically infer how the models should be plugged in with each other.

**Comment by eellison** [comment]
That may or may not be true with ModuleLists, I don't think it applies to ModuleDicts:  https://github.com/pytorch/vision/blob/973db14523d338fa4e772574fe4d49763fb25245/torchvision/models/_utils.py#L62

& IMO it would be kind of weird to have different behavior b/w ModuleLists and ModuleDict. Yea agreed that there is  no general way to infer how the modules  relate to each other.

**Comment by shaibagon** [comment]
@twoertwein and @eellison my 2 cents: In my experience, `ModuleList` and `ModuleDict` are used as _containers_ for modules, and more often that not the stored modules are _not_ intended for parallel run on the same inputs.

The idea of leaving  `ModuleList` and `ModuleDict` as-is but allowing to easily derive "parallel" classes from them seems like the right course of action.
