### ISSUE TITLE
DistributedDataParallel does not support Modules that take no inputs.

### ISSUE THREAD

**Issue by HapeMask** [pytorch/pytorch#37814]
## 🐛 Bug

If you wrap a module that takes no input in DDP and try to call the forward pass, it fails with an IndexError.

## To Reproduce

```python
import os

import torch as th
from torch.nn.parallel import DistributedDataParallel

class Holder(th.nn.Module):
    def __init__(self):
        super().__init__()
        self.x = th.nn.Parameter(th.zeros(3))
    def forward(self):
        return self.x

os.environ["MASTER_ADDR"] = "127.0.0.1"
os.environ["MASTER_PORT"] = "12345"
os.environ["WORLD_SIZE"] = "1"
th.distributed.init_process_group(
    backend="nccl",
    init_method="env://",
    world_size=1,
    rank=0,
)
holder = Holder().cuda()
holder = DistributedDataParallel(holder, device_ids=[0])
x = holder()
```

Result:
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    x = holder()
  File ".../torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File ".../torch/nn/parallel/distributed.py", line 445, in forward
    output = self.module(*inputs[0], **kwargs[0])
IndexError: tuple index out of range
```

## Expected behavior

No exception is raised.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1/7.6.5
 - GPU models and configuration: v100

**Comment by mruberry** [comment]
Thank you for reporting this issue, @HapeMask! We would accept a PR fixing this.

**Comment by HapeMask** [comment]
Sure, see #37902.
