### ISSUE TITLE
`torch.log10` with float32 produces different results on different CPU

### ISSUE THREAD

**Issue by mthrok** [pytorch/pytorch#37833]
## 🐛 Bug

Hi Team

Not sure this is a bug but I noticed that `torch.log10` produces different results on different CPUs, when tensor dtype is `float32`.
(It produces the consistent result when `float32`)

- **A** `Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz` (`2xlarge+` resource class on CircleCI's docker executor)

    <Details> <Summary>Flags</Summary>

    ```
    [
      "3dnowprefetch",
      "abm",
      "adx",
      "aes",
      "aperfmperf",
      "apic",
      "arat",
      "arch_perfmon",
      "avx",
      "avx2",
      "avx512bw",
      "avx512cd",
      "avx512dq",
      "avx512f",
      "avx512vl",
      "bmi1",
      "bmi2",
      "clflush",
      "clflushopt",
      "clwb",
      "cmov",
      "constant_tsc",
      "cpuid",
      "cx16",
      "cx8",
      "de",
      "erms",
      "f16c",
      "fma",
      "fpu",
      "fsgsbase",
      "fxsr",
      "hle",
      "ht",
      "hypervisor",
      "ida",
      "invpcid",
      "invpcid_single",
      "lahf_lm",
      "lm",
      "mca",
      "mce",
      "mmx",
      "monitor",
      "movbe",
      "mpx",
      "msr",
      "mtrr",
      "nonstop_tsc",
      "nopl",
      "nx",
      "ospke",
      "osxsave",
      "pae",
      "pat",
      "pcid",
      "pclmulqdq",
      "pdpe1gb",
      "pge",
      "pku",
      "pni",
      "popcnt",
      "pse",
      "pse36",
      "pti",
      "rdrand",
      "rdrnd",
      "rdseed",
      "rdtscp",
      "rep_good",
      "rtm",
      "sep",
      "smap",
      "smep",
      "ss",
      "sse",
      "sse2",
      "sse4_1",
      "sse4_2",
      "ssse3",
      "syscall",
      "tsc",
      "tsc_adjust",
      "tsc_deadline_timer",
      "tsc_known_freq",
      "tscdeadline",
      "vme",
      "x2apic",
      "xgetbv1",
      "xsave",
      "xsavec",
      "xsaveopt",
      "xsaves",
      "xtopology"
    ]
    ```
    </Details>
vs 

- **B** `Intel(R) Xeon(R) CPU @ 2.30GHz` (Windows executor of CircleCI)
    <Details> <Summary>Flags</Summary>

    ```
    [
      "3dnow",
      "clflush",
      "cmov",
      "de",
      "dts",
      "fxsr",
      "ia64",
      "mca",
      "mce",
      "mmx",
      "mtrr",
      "pse",
      "sep",
      "serial",
      "ss",
      "sse",
      "sse2",
      "tm"
    ]
    ```
    </Details>

- **C** `Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz` (`gpu.small` resource class and `ubuntu-1604-cuda-10.1:201909-23` VM on CircleCI's GPU executor)
    <Details> <Summary>Flags</Summary>

    ```
    [
      "3dnowprefetch",
      "abm",
      "adx",
      "aes",
      "aperfmperf",
      "apic",
      "avx",
      "avx2",
      "bmi1",
      "bmi2",
      "clflush",
      "cmov",
      "constant_tsc",
      "cx16",
      "cx8",
      "de",
      "erms",
      "f16c",
      "fma",
      "fpu",
      "fsgsbase",
      "fxsr",
      "hle",
      "ht",
      "hypervisor",
      "invpcid",
      "invpcid_single",
      "lahf_lm",
      "lm",
      "mca",
      "mce",
      "mmx",
      "movbe",
      "msr",
      "mtrr",
      "nonstop_tsc",
      "nopl",
      "nx",
      "osxsave",
      "pae",
      "pat",
      "pcid",
      "pclmulqdq",
      "pdpe1gb",
      "pge",
      "pni",
      "popcnt",
      "pse",
      "pse36",
      "pti",
      "rdrand",
      "rdrnd",
      "rdseed",
      "rdtscp",
      "rep_good",
      "rtm",
      "sep",
      "smep",
      "sse",
      "sse2",
      "sse4_1",
      "sse4_2",
      "ssse3",
      "syscall",
      "tsc",
      "tsc_deadline_timer",
      "tscdeadline",
      "vme",
      "x2apic",
      "xsave",
      "xsaveopt",
      "xtopology"
    ]
    ```
    </Details>
    
    **Note** GPU is not used for this report.

Skimming through the [code](https://github.com/search?q=log10+repo%3Apytorch%2Fpytorch+path%3Aaten%2Fsrc%2FATen%2Fcpu%2Fvec256&type=Code&ref=advsearch&l=&l=) and looking at the flags above, it seems that `avx512` is making the difference. (Only **A** has `avx512`.)

## To Reproduce

1. Run `torch.log10` for the same input (`float32`) on different CPUs.
1. Compare the results.

You can download my results from here.
1. [**A** `Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz`](https://app.circleci.com/pipelines/github/pytorch/audio/1701/workflows/98abb595-c128-4b0a-9d4a-d967178ca000/jobs/43147/artifacts)
2. [**B** `Intel(R) Xeon(R) CPU @ 2.30GHz`](https://app.circleci.com/pipelines/github/pytorch/audio/1701/workflows/98abb595-c128-4b0a-9d4a-d967178ca000/jobs/43151/artifacts)
3. [**C** `Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz`](https://app.circleci.com/pipelines/github/pytorch/audio/1701/workflows/98abb595-c128-4b0a-9d4a-d967178ca000/jobs/43136/artifacts)

Input Tensor to `torch.log10` is `amplitude_to_DB-clamped.pt` and the output is `amplitude_to_DB-log.pt`.

Using the following comparison script, I get the following error.

<Details><Summary>Comparison Script</Summary>

```python
#!/usr/bin/env python3
import sys
import torch


def _main():
    if len(sys.argv) != 3:
        print(f'Usage sys.argv[0] <Tensor1> <Tensor2>')
        sys.exit(1)

    tensor1 = torch.load(sys.argv[1])
    tensor2 = torch.load(sys.argv[2])

    torch.testing.assert_allclose(tensor1, tensor2)


if __name__ == '__main__':
    _main()
```

</Details>

**CPU A vs B**

```
$ python ../compare_tensor.py linux-cpu/amplitude_to_DB-log.pt windows-cpu/amplitude_to_DB-log.pt
Traceback (most recent call last):
  File "../compare_tensor.py", line 20, in <module>
    _main()
  File "../compare_tensor.py", line 16, in _main
    torch.testing.assert_allclose(tensor1, tensor2)
  File "/Users/moto/miniconda3/lib/python3.7/site-packages/torch/testing/__init__.py", line 60, in assert_allclose
    raise AssertionError(msg)
AssertionError: Not within tolerance rtol=0.0001 atol=1e-05 at input[0, 95, 19] (-9.582792282104492 vs. -9.671723365783691) and 22024 other locations (17.00%)
```

**CPU A vs C**

```
$ python ../compare_tensor.py linux-cpu/amplitude_to_DB-log.pt linux-gpu/amplitude_to_DB-log.pt
Traceback (most recent call last):
  File "../compare_tensor.py", line 20, in <module>
    _main()
  File "../compare_tensor.py", line 16, in _main
    torch.testing.assert_allclose(tensor1, tensor2)
  File "/Users/moto/miniconda3/lib/python3.7/site-packages/torch/testing/__init__.py", line 60, in assert_allclose
    raise AssertionError(msg)
AssertionError: Not within tolerance rtol=0.0001 atol=1e-05 at input[0, 95, 19] (-9.582792282104492 vs. -9.671723365783691) and 22024 other locations (17.00%)
```

**CPU B vs C**

```
$ python ../compare_tensor.py windows-cpu/amplitude_to_DB-log.pt linux-gpu/amplitude_to_DB-log.pt
$
```

## Expected behavior

`torch.log10` produces the same result, or closer result.

## Environment

<Details><Summary> For **A** </Summary>

```
PyTorch version: 1.6.0.dev20200505
Is debug build: No
CUDA used to build PyTorch: None
 
OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect
 
Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0.dev20200505
[pip] torchaudio==0.6.0a0+778fd64
[conda] blas                      1.0                         mkl 
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] numpy                     1.18.1           py36h4f9e942_0  
[conda] numpy-base                1.18.1           py36hde5b4d6_1  
[conda] pytorch                   1.6.0.dev20200505     py3.6_cpu_0  [cpuonly]  pytorch-nightly
[conda] torchaudio                0.6.0a0+778fd64           dev_0    <develop>
```

</Details>

<Details><Summary> For **B** </Summary>

``` 
PyTorch version: 1.6.0.dev20200505
Is debug build: No 
CUDA used to build PyTorch: None 

OS: Microsoft Windows Server 2019 Datacenter
GCC version: Could not collect
CMake version: Could not collect
 
Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.4 
[pip] torch==1.6.0.dev20200505 
[pip] torchaudio==0.6.0a0+778fd64
[conda] Could not collect
```

</Details>

<Details><Summary> For **C** </Summary>

```
PyTorch version: 1.6.0.dev20200505 
Is debug build: No 
CUDA used to build PyTorch: 10.1 
 
OS: Ubuntu 18.04.3 LTS 
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 
CMake version: Could not collect 
 
Python version: 3.8 
Is CUDA available: Yes 
CUDA runtime version: Could not collect 
GPU models and configuration: GPU 0: Tesla M60 
Nvidia driver version: 418.87.00 
cuDNN version: Could not collect 
 
Versions of relevant libraries: 
[pip] numpy==1.18.1 
[pip] torch==1.6.0.dev20200505 
[pip] torchaudio==0.6.0a0+778fd64 
[conda] blas                      1.0                         mkl   
[conda] cudatoolkit               10.1.243             h6bb024c_0   
[conda] mkl                       2020.0                      166   
[conda] mkl-service               2.3.0            py38he904b0f_0   
[conda] mkl_fft                   1.0.15           py38ha843d7b_0   
[conda] mkl_random                1.1.0            py38h962f231_0   
[conda] numpy                     1.18.1           py38h4f9e942_0   
[conda] numpy-base                1.18.1           py38hde5b4d6_1   
[conda] pytorch                   1.6.0.dev20200505 py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly 
[conda] torchaudio                0.6.0a0+778fd64           dev_0    <develop> 
```
</Details>

## Additional context

Some tests in torchaudio fails due to this.

cc @VitalyFedyunin

**Comment by mruberry** [comment]
Hey @mthrok, I'm not sure there's much PyTorch can do here if there really is a difference in how C++ is computing these values across these implementations. It seems like a "below PyTorch" issue unless the computation is actually "wrong" (way off the mark) in one case.

**Comment by mthrok** [comment]
@mruberry 
Yes, that makes sense. I wanted to leave a record of this finding and double check if there is something that we can work on.

While filling out this issue I also found that `float64` produces consistent result, so we are going to use `float64` in torchaudio to resolve the issue we are having.

Thanks!
