### ISSUE TITLE
DISABLED test_barrier_full_group_cuda (__main__.TestDistBackend)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38015]
https://app.circleci.com/pipelines/github/pytorch/pytorch/165903/workflows/5805cf41-ee8c-4a5d-bf4d-512b57b0b9b0/jobs/5383911/steps

```
May 07 08:33:15 ======================================================================
May 07 08:33:15 FAIL [0.206s]: test_barrier_full_group_cuda (__main__.TestDistBackend)
May 07 08:33:15 ----------------------------------------------------------------------
May 07 08:33:15 Traceback (most recent call last):
May 07 08:33:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 173, in wrapper
May 07 08:33:15     self._join_processes(fn)
May 07 08:33:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 275, in _join_processes
May 07 08:33:15     self._check_return_codes(elapsed_time)
May 07 08:33:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 327, in _check_return_codes
May 07 08:33:15     "Expected zero exit code but got {}".format(first_process.exitcode)
May 07 08:33:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 973, in assertEqual
May 07 08:33:15     super().assertLessEqual(abs(x - y), atol, message)
May 07 08:33:15 AssertionError: 77 not less than or equal to 1e-05 : Expected zero exit code but got 77
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by rohan-varma** [comment]
I think we can close this, since the error message indicates in was an issue with my PR (I took out the 77 exit skip code). The PR should now be fixed.
