### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Tylersuard** [pytorch/pytorch#38090]
## Issue description

Attempting to run Detectron 2, getting the above error

## Code example
python demo.py –config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --webcam \  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

Ubuntu 20
Pytorch 1.4.0
Python3.7

## System Info
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by glaringlee** [comment]
@Tylersuard 
I think it might be better to post this issue here:
https://github.com/facebookresearch/detectron2/issues

**Comment by malfet** [comment]
@Tylersuard thank you for reporting the issue. Can you please check if ` python -c 'import torch;print(torch.eye(3))'` works as expected. Also, please use post the output of `collect_env.py` tool, for example by issuing `python -c 'from torch.utils.collect_env import main; main()'` command

**Comment by ncdejito** [comment]
installed the previous version in the meantime
`wget https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/detectron2-0.1.1%2Bcu101-cp36-cp36m-linux_x86_64.whl
pip install detectron2-0.1.1+cu101-cp36-cp36m-linux_x86_64.whl`

**Comment by winswang** [comment]
> @Tylersuard thank you for reporting the issue. Can you please check if ` python -c 'import torch;print(torch.eye(3))'` works as expected. Also, please use post the output of `collect_env.py` tool, for example by issuing `python -c 'from torch.utils.collect_env import main; main()'` command

Hi I encountered the same issue. the eye(3) gave me the results as expected. The collect_env gave me:
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.2
[pip] numpydoc==0.9.1
[pip] pyronn-torch==0.1.2.post0.dev1+g49261ca
[pip] pytorch-msssim==0.1.5
[pip] pytorch3d==0.2.0
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] Could not collect

Any clue what might be wrong?

**Comment by usbhub** [comment]
So I ran into this issue with maskrcnn-benchmark and came across this page when googling for a solution. Turns out what happened was I had downgraded my pytorch from 1.5.0 to 1.3.1 (for an unrelated reason) but had built maskrcnn-benchmark against the 1.5.0 torch, which has separated out static libraries libtorch_cpu.so and libtorch_cuda.so (instead of just libtorch.so), see: https://github.com/pytorch/pytorch/issues/29235 . My guess is they built the newest detectron 2 wheels against 1.5.0 and so that is why you are getting the error since it is expecting different static libraries, I would expect it would work if you upgraded to pytorch 1.5.0.

**Comment by ppwwyyxx** [comment]
As the [detectron2 installation instsructions](https://detectron2.readthedocs.io/tutorials/install.html#install-pre-built-detectron2-linux-only) and [release notes](https://github.com/facebookresearch/detectron2/releases) say, each pre-built release of detectron2 has to work with the corresponding pytorch version. Please follow the instructions.

**Comment by kalyan369** [comment]
> there's something in 0.1.2, installed the previous version in the meantime and it worked for me
> `wget https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/detectron2-0.1.1%2Bcu101-cp36-cp36m-linux_x86_64.whl`
> `pip install detectron2-0.1.1+cu101-cp36-cp36m-linux_x86_64.whl`

Issue got resolved with a slight change to the above commands based on my current python version with below commands

> 'wget https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/detectron2-0.1.1%2Bcu101-cp37-cp37m-linux_x86_64.whl'
> 'pip install detectron2-0.1.1+cu101-cp37-cp37m-linux_x86_64.whl'

**Comment by aravindpai** [comment]
I ran into the similar problem. It's due to the conflict between the versions of PyTorch. Upgrade torch to 1.5.

!pip install -U torch==1.5

**Comment by ajread4** [comment]
I am getting the same, libtorch_cpu.so error as above. The error occurs when trying to run: 

from torch_geometric.data import Data

The output of "python -m torch.utils.collect_env" is : 

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.2.0
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 2.8.12.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla K40c
GPU 1: Tesla K40c
GPU 2: Tesla K40c
GPU 3: Tesla K40c

Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.7.0
[pip3] torch-scatter==2.0.7
[pip3] torch-sparse==0.6.9
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] pytorch                   1.8.0               py3.8_cpu_0  [cpuonly]  pytorch
[conda] torch-cluster             1.5.9                    pypi_0    pypi
[conda] torch-geometric           1.7.0                    pypi_0    pypi
[conda] torch-scatter             2.0.7                    pypi_0    pypi
[conda] torch-sparse              0.6.9                    pypi_0    pypi
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                  py38_cpu  [cpuonly]  pytorch

**Comment by baiqv** [comment]
I meet same problem how to slove?
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 455.45.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.4.0
[pip3] torchtext==0.5.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

**Comment by semigok** [comment]
I had the similar problem. I think it is because of the compatibility issue with torch versions and the CUDA version you use. CUDA is backwards compatible only withing the same main version such as 11.x or 9.x. If you install the wrong pytorch packages/wheel you can get this error. Just uninstall torch related packages and reinstall them with the correct ones.

**Comment by bayan264** [comment]
I have the same problem and the same error, and these are the properties of my environment:
yTorch version: 1.4.0

Is debug build: No

CUDA used to build PyTorch: 10.1



OS: Ubuntu 22.04.3 LTS

GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

CMake version: Could not collect



Python version: 3.6

Is CUDA available: No

CUDA runtime version: No CUDA

GPU models and configuration: No CUDA

Nvidia driver version: No CUDA

cuDNN version: No CUDA



Versions of relevant libraries:

[pip3] numpy==1.15.4

[pip3] torch==1.4.0

[pip3] torch-scatter==2.0.7

[pip3] torch-sparse==0.6.9

[pip3] torchvision==0.2.1

[conda] _pytorch_select           0.2                       gpu_0  

[conda] blas                      1.0                         mkl  

[conda] mkl                       2019.5                      281    conda-forge

[conda] mkl-service               2.3.0            py36h516909a_0    conda-forge

[conda] mkl_fft                   1.1.0            py36hc1659b7_1    conda-forge

[conda] mkl_random                1.1.0            py36hb3f55d8_0    conda-forge

[conda] pytorch                   1.4.0           cuda101py36h02f0884_0  

[conda] torch-scatter             2.0.7                    pypi_0    pypi

[conda] torch-sparse              0.6.9                    pypi_0    pypi

[conda] torchvision               0.2.1                    py36_0

How can I solve the problem?
