### ISSUE TITLE
Pybind11 cpp extensions broken with pytorch v1.5.0

### ISSUE THREAD

**Issue by bcharlier** [pytorch/pytorch#38122]
## 🐛 Bug

Dear community,

I am a dev from [KeOps project](https://github.com/getkeops/keops/) building optimized operations written in C++/Cuda that are compatible with pytorch (among others scientific languages). 

We successfully build python modules compatible with pyTorch since the pyTorch v0.2... But the last v1.5 broke our modules with a runtime error complaining about [missing symbols](https://github.com/getkeops/keops/issues/59).

To simplify the analysis you may find below a minimal working example that builds a module through pybind11n the spirit of [pytorch doc](https://pytorch.org/tutorials/advanced/cpp_frontend.html#writing-a-basic-application). 

It should output a file `test_module.cpython-38-x86_64-linux-gnu.so` that can be imported from python. This module works well when building with pytorch 1.4 but raised a runtime error when building with pytorch v1.5. 

## To Reproduce

Assuming pyTorch and pybind11 installed (e.g. through conda).  There are 2 files

`module_test.cpp` contains

```cpp
#include <torch/extension.h>
#include <pybind11/pybind11.h>
// Main function
at::Tensor foo(int s) {
     return torch::eye(s);
}    

// PyBind11 entry point 
PYBIND11_MODULE(test_module, m) {
m.def("foo", &foo, "Entry point to test module");
}
```   
and `CMakeList.txt` contains
```
project(test_module LANGUAGES CXX)

find_package(Torch REQUIRED)
find_package(pybind11  REQUIRED)

pybind11_add_module(test_module ${CMAKE_CURRENT_SOURCE_DIR}/test_module.cpp)
target_link_libraries(test_module PUBLIC "${TORCH_LIBRARIES}")
```
it can be compile with

 ```bash
$ mkdir build
$ cd build
$ cmake -DCMAKE_PREFIX_PATH="/home/bcharlier/.conda/envs/keops/lib/python3.8/site-packages/torch/" .. && make
```
and run with (note that `torch` is imported first)
```
$ python -c "import torch; print(torch.__version__); import test_module; print(test_module.foo(3))"

1.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/bcharlier/src/test_module/build/test_module.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z16THPVariable_WrapN2at6TensorE
```
The missing symbol is not exactly the same when [building a module with the keops library](https://github.com/getkeops/keops/issues/59)... But I guess this is irrelevant.

## Expected behavior

It works fine when compiling with pytorch v1.4

```bash
$ cmake -DCMAKE_PREFIX_PATH="/home/bcharlier/.conda/envs/keops_torch14/lib/python3.8/site-packages/torch/" .. && make
$ python -c "import torch; print(torch.__version__); import test_module; print(test_module.foo(3))"
1.4.0
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
```

## Environment

The bug was reported by various users running on linux. Here is my config:

```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Arch Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.14.0

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Quadro T2000
Nvidia driver version: 440.82
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.4
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.0.15           py38ha843d7b_0  
[conda] mkl_random                1.1.0            py38h962f231_0  
[conda] numpy                     1.18.1           py38h4f9e942_0  
[conda] numpy-base                1.18.1           py38hde5b4d6_1  
[conda] pytorch                   1.5.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch

```

**Comment by zou3519** [comment]
Marking high-pri tentatively for regression

**Comment by malfet** [comment]
@bcharlier, thank you very much for reporting the issue.

**Comment by malfet** [comment]
For some reason `THPVariable_Wrap(at::Tensor)` function implementation were moved from `libtorch` to `libtorch_python`

**Comment by ezyang** [comment]
This may be related to our changes to `RTLD_GLOBAL`

**Comment by malfet** [comment]
You are right, ` TORCH_USE_RTLD_GLOBAL=YES python -c 'import torch; import test_module;print(test_module.foo(3))'` indeed make symbol visible.

**Comment by bcharlier** [comment]
thank you guys for the quick and useful feed back. I have lost hours on that...

The `TORCH_USE_RTLD_GLOBAL=YES` does the trick and fix the pykeops issue. 

Do you plan to change this flag in a future release or should I considered the new standard to link the module ?

**Comment by ezyang** [comment]
The flag will not be changed in a future release, since RTLD_GLOBAL means you have to make sure all of your C++ symbols line up properly across all of your libraries, or you'll get mysterious segfaults. We will always keep this as an option, however, for cases when you have control over all of the binaries you're linking against.

That being said, a more direct and correct fix is probably to link your extension against `libtorch_python`, which would also make the symbols available.

**Comment by malfet** [comment]
I plan to add new `PYTHON_TORCH_LIBRARIES` (or `TORCH_PYTHON_LIBRARIES`) cmake variable, that extend `TORCH_LIBRARIES` by adding `libtorch_python.so` (and will be a no-op on Windows)

**Comment by bcharlier** [comment]
adding an explicit linking against `libtorch_python` is indeed the way to go. It fixed the issue.

@malfet : yes! the `TorchConfig.cmake` definitely deserve a little bit of clean up... I should confess that I do not use it because:

1. the CMake files shipped with pytorch do not honor the new `find_package()` behavior. Cmake 3.17 now throws dev warning. E.g.
```
The package name passed to `find_package_handle_standard_args` (torch) does
not match the name of the calling package (Torch). This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
/usr/lib64/cmake/Torch/TorchConfig.cmake:130 (find_package_handle_standard_args)
CMakeLists.txt:5 (find_package)
This warning is for project developers. Use -Wno-dev to suppress it.
```

2. when doing a `find_package(Torch)` every dependencies of torch are loaded through CMake. In particular, Caffe2 Cmake file is looking for cuda even with pytorch v1.3+cpu release throwing an Error on machine without gpu.

A general though: the torch includes are (in my point of view) a little bit greedy as they include everything. A bit of modularity could help to make Pytorch a standard not only in the ML community, but also in other computational scientific fields (as the elementary bricks are there:  fast tensor algebra, autodiff, extensive doc, great community). 

Anyway, thank again for your work and the nice feed back.

**Comment by captainjtx** [comment]
Thanks ! Hit the same issue complaining on `undefined symbol: THPVariableClass`. Linking explicitly against `libtorch_python.so` solves my problem !

**Comment by CoinCheung** [comment]
Hi, 

I met same problem and setting `TORCH_USE_RTLD_GLOBAL=YES` does not solve my problem. I am using pytorch1.6 from conda and libtorch downloaded from official download page. Any suggestions please ?

**Comment by CoinCheung** [comment]
My error message is: `ImportError: /root/repo/play/build/play.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

**Comment by CoinCheung** [comment]
Solved, I recompiled my pytorch and ues the libtorch in the `torch/` directory of the compiled source path. And use the `TORCH_USE_RTLD_GLOBAL=YES` method will work. It seems that  pytorch and libtorch should be compiled under same circumstance.

**Comment by gemfield** [comment]
On PyTorch 1.6, same issue:
```python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import syszux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /gemfield/hostpv/gemfield/libdeepvac/build/lib/syszux.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
```

workaround:

```cmake
find_library(TORCH_PYTHON_LIBRARY torch_python PATHS "${TORCH_INSTALL_PREFIX}/lib")
message(STATUS "TORCH_PYTHON_LIBRARY: ${TORCH_PYTHON_LIBRARY}")
target_link_libraries( syszux "${TORCH_LIBRARIES}" ${TORCH_PYTHON_LIBRARY} ${OpenCV_LIBS} deepvac)
```

**Comment by monajalal** [comment]
@gemfield could you please explain a little more on your workaround?

How did you fix it? Where did you add those three lines?

**Comment by gemfield** [comment]
@monajalal You can have a look at https://github.com/DeepVAC/libdeepvac/blob/master/python/CMakeLists.txt

**Comment by mthrok** [comment]
> I plan to add new `PYTHON_TORCH_LIBRARIES` (or `TORCH_PYTHON_LIBRARIES`) cmake variable, that extend `TORCH_LIBRARIES` by adding `libtorch_python.so` (and will be a no-op on Windows)

@gemfield 's workaround worked for me, yet this addition will be nice  @malfet :)

**Comment by slulura** [comment]
> adding an explicit linking against `libtorch_python`



> adding an explicit linking against `libtorch_python` is indeed the way to go. It fixed the issue.
> 
> @malfet : yes! the `TorchConfig.cmake` definitely deserve a little bit of clean up... I should confess that I do not use it because:
> 
> 1. the CMake files shipped with pytorch do not honor the new `find_package()` behavior. Cmake 3.17 now throws dev warning. E.g.
> 
> ```
> The package name passed to `find_package_handle_standard_args` (torch) does
> not match the name of the calling package (Torch). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> /usr/lib64/cmake/Torch/TorchConfig.cmake:130 (find_package_handle_standard_args)
> CMakeLists.txt:5 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.
> ```
> 
> 1. when doing a `find_package(Torch)` every dependencies of torch are loaded through CMake. In particular, Caffe2 Cmake file is looking for cuda even with pytorch v1.3+cpu release throwing an Error on machine without gpu.
> 
> A general though: the torch includes are (in my point of view) a little bit greedy as they include everything. A bit of modularity could help to make Pytorch a standard not only in the ML community, but also in other computational scientific fields (as the elementary bricks are there: fast tensor algebra, autodiff, extensive doc, great community).
> 
> Anyway, thank again for your work and the nice feed back.

How do you do this?

**Comment by souptc** [comment]
Hi, hit the same issue in my scenario. Manually link with libtorch_python fixed it, but to support build on different platform, I need manually adjust the lib path and name, for example, it is named as torch_python.dll on windows. Could we add the support in TorchConfig.cmake to make it easier?

**Comment by yaadhavraajagility** [comment]
> My error message is: `ImportError: /root/repo/play/build/play.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

Did you manage to fix this?

**Comment by adizhol** [comment]
Amazing that this is still an issue for pytroch 1.11.0.
In CMAKE after you do `find_package(Torch REQUIRED)`
and print `message("TORCH LIBS ${TORCH_LIBRARIES}")`
you get 
`TORCH LIBS torch;torch_library;/usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so;/usr/local/cuda/lib64/stubs/libcuda.so;/usr/local/cuda/lib64/libnvrtc.so;/usr/local/cuda/lib64/libnvToolsExt.so;/usr/local/cuda/lib64/libcudart.so;/usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so`

and you can see that libtorch_python.so is missing, and there's no documented way of adding it...
