### ISSUE TITLE
test_cpp_warnings_have_python_context_cpu fails under some build configurations

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#38135]
On my local DEBUG build I have

```
======================================================================
FAIL: test_cpp_warnings_have_python_context_cpu (__main__.TestTorchDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 210, in instantiated_test
    return test(self, device_arg)
  File "test/test_torch.py", line 5943, in test_cpp_warnings_have_python_context
    self.assertTrue(re.search(s, str(warning.message)) is not None)
AssertionError: False is not true
```

This is because two warnings are emitted:

```
[<warnings.WarningMessage object at 0x7f437bebc780>, <warnings.WarningMessage object at 0x7f437c51d780>]
```

The first warning is:

```
pybind11-bound class 'torch.distributed.rpc.RRef' is using an old-style placement-new '__setstate__' which has been deprecated. See the upgrade guide in pybind11's docs. This message is only visible when compiled in debug mode.
```

**Comment by ezyang** [comment]
cc @mruberry who introduced the test

**Comment by mruberry** [comment]
"This message is only visible when compiled in debug mode." ... Cool! I'll see if there's a good way to address this.
