### ISSUE TITLE
internal assert failed bug due to argmax gradfn

### ISSUE THREAD

**Issue by successar** [pytorch/pytorch#38209]
## 🐛 Bug

Following code returns an internal assert error. Possibly due to argmax result having a gradfn attribute (which should not be the case, argmax is not differentiable).

## To Reproduce

```python
import torch
x = torch.randn((10, 2)).cuda()
x.requires_grad = True
y = x*x
l = y.argmax(-1)
z = y[torch.arange(y.shape[0]), l]
z.sum().backward()
```

## Expected behavior

Should not return any errors

```
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    z.sum().backward()
  File "/home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError: range.second - range.first == t.size() INTERNAL ASSERT FAILED at /pytorch/torch/csrc/autograd/generated/Functions.cpp:57, please report a bug to PyTorch. inconsistent range for TensorList output (copy_range at /pytorch/torch/csrc/autograd/generated/Functions.cpp:57)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fc142aa3536 in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x28906ae (0x7fc181c186ae in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torch::autograd::generated::IndexBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0xcb (0x7fc181c56c9b in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x2d89c05 (0x7fc182111c05 in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7fc18210ef03 in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7fc18210fce2 in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::thread_init(int) + 0x39 (0x7fc182108359 in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7fc18e843548 in /home/jainsarthak/miniconda3/envs/fresh/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xcfb24 (0x7fc18f705b24 in /usr/lib/libstdc++.so.6)
frame #9: <unknown function> + 0x946f (0x7fc190af046f in /usr/lib/libpthread.so.0)
frame #10: clone + 0x43 (0x7fc190a203d3 in /usr/lib/libc.so.6)
```
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Manjaro Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: TITAN RTX
GPU 2: GeForce GT 1030

Nvidia driver version: 440.82
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.4
[pip] torch==1.5.0
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] torch                     1.5.0                    pypi_0    pypi

**Comment by BrettRyland** [comment]
Seems to work in the nightly: `pip3 install --upgrade --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html`

**Comment by successar** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/37789
