### ISSUE TITLE
_pickle.PickleError: ScriptModules cannot be saved using torch.save.

### ISSUE THREAD

**Issue by feiyangsuo** [pytorch/pytorch#38214]
The full error log:
```
Traceback (most recent call last):
  File "E:/Projects/Python/BridgeHole/main.py", line 204, in <module>
    train_and_eval(24, val_split=0.1)
  File "E:/Projects/Python/BridgeHole/main.py", line 199, in train_and_eval
    torch.save(model, os.path.join(save_dir, "epoch_{}.pth".format(epoch)))
  File "D:\Applications\Anaconda2\envs\dl\lib\site-packages\torch\serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "D:\Applications\Anaconda2\envs\dl\lib\site-packages\torch\serialization.py", line 149, in _with_file_like
    return body(f)
  File "D:\Applications\Anaconda2\envs\dl\lib\site-packages\torch\serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "D:\Applications\Anaconda2\envs\dl\lib\site-packages\torch\serialization.py", line 297, in _save
    pickler.dump(obj)
  File "D:\Applications\Anaconda2\envs\dl\lib\site-packages\torch\jit\__init__.py", line 1308, in __getstate__
    "For purely script modules use my_script_module.save(<filename>) instead.")
_pickle.PickleError: ScriptModules cannot be saved using torch.save. Mixed serialization of script and non-script modules is not supported. For purely script modules use my_script_module.save(<filename>) instead.

```
I'm using pytorch 1.1.0 and torchvision 0.2.0 under cuda 9.0.
This error was raised when executing `torch.save(model, model_path)`. I've never seen error like this before, even have no idea what a `ScriptModule` is...
This error didn't show up when I run the same code under another environment with pytorch 1.5.0 and torchvision 0.6.0 under cuda 10.0. But the later environment is on my lab'a sever and is hard to debug on it. I have to use the former environment however.

cc @suo

**Comment by feiyangsuo** [comment]
Another strange thing is, when I check `torchvision.__version__` it's 0.3.0, but `conda list torchvison` tells  me my torchvision is 0.2.0.  Since I can use module `torchvision.models.detection`, I think it's actually 0.3.0.

**Comment by ailzhang** [comment]
It looks like you're trying to save a ScriptModule in pytorch 1.1 (IIRC it was not supported in that version). 

You'll either have to downgrade your torchvision or upgrade your pytorch verison.
