### ISSUE TITLE
DISABLED test_graph_for_builtin_call (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38234]
https://app.circleci.com/pipelines/github/pytorch/pytorch/167150/workflows/2511637a-170c-4e0e-899a-46bfc66adbf3/jobs/5411670/steps

```
May 08 23:55:04   test_graph_for_builtin_call (__main__.DistAutogradTestWithSpawn) ... Timing out after 100 seconds and killing subprocesses.
May 08 23:55:04 ERROR (100.070s)
```

```
May 08 23:55:32 ======================================================================
May 08 23:55:32 ERROR [100.070s]: test_graph_for_builtin_call (__main__.DistAutogradTestWithSpawn)
May 08 23:55:32 ----------------------------------------------------------------------
May 08 23:55:32 Traceback (most recent call last):
May 08 23:55:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 184, in wrapper
May 08 23:55:32     self._join_processes(fn)
May 08 23:55:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in _join_processes
May 08 23:55:32     self._check_return_codes(elapsed_time)
May 08 23:55:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 324, in _check_return_codes
May 08 23:55:32     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
May 08 23:55:32 RuntimeError: Process 0 terminated or timed out after 100.05419659614563 seconds
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
Let's see if #38512 #38364 #38366 #38376 and #38348 are sufficient to fix this.
