### ISSUE TITLE
When TorchScripted module has bad type annotation you get bad error message

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#38233]
Suppose that you incorrectly annotated bias in Conv as `Tensor` rather than `Optional[Tensor]`. When you script it you get this error:

```
              
======================================================================                                  
ERROR: test_dropout_eval (__main__.TestScript)                                                                
----------------------------------------------------------------------                                        
Traceback (most recent call last):                                                                            
  File "test/test_jit.py", line 8581, in test_dropout_eval                                                    
    script_mod = ScriptMod()                                                                                  
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1528, in init_then_script    
    original_init(self, *args, **kwargs)                                                                      
  File "test/test_jit.py", line 8550, in __init__                                                             
    self.Conv2d_1a_3x3 = ScriptedConv2d(3, 32, kernel_size=3, stride=2)                                       
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1534, in init_then_script                 
    self.__dict__["_actual_script_module"] = torch.jit._recursive.create_script_module(self, make_stubs)        File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 305, in create_script_module                return create_script_module_impl(nn_module, concrete_type, stubs_fn)                                        File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 360, in create_script_module_impl           script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)                           
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1673, in _construct                       
    init_fn(script_module)                                                                                    
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 341, in init_fn                             scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)               File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 360, in create_script_module_impl           script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)                             File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1673, in _construct             
    init_fn(script_module)                                                                                    
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 326, in init_fn                             cpp_module.setattr(name, orig_value)                                                                      RuntimeError: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'at::Tensor'       
```

This is a super useless error message. It doesn't tell you any context about the error in question.

**Comment by eellison** [comment]
Can you post a repro?

**Comment by eellison** [comment]
For 
```
@torch.jit.script
def foo(x = None):
    pass
```

The error message is:
> RuntimeError: 
Expected a default value of type Tensor on parameter "x". Because "x" was not annotated with an explicit type it is assumed to be type 'Tensor'.:
  File "test/test_jit.py", line 4188
        @torch.jit.script
        def foo(x = None):
        ~~~~~~~~~~~~~~~~~~...  <--- HERE
            pass

And for 
```
@torch.jit.script
def foo(x):
    pass

foo(None)
```
you get:
> RuntimeError: foo() Expected a value of type 'Tensor' for argument 'x' but instead found type 'NoneType'.
Inferred 'x' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 0
Value: None
Declaration: foo(Tensor x) -> (None)
Cast error details: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'at::Tensor'

Both of these error messages are pretty good...

**Comment by ezyang** [comment]
Apply this patch:

```
diff --git a/torch/nn/modules/conv.py b/torch/nn/modules/conv.py
index 5c6be5f912..79cc609082 100644
--- a/torch/nn/modules/conv.py
+++ b/torch/nn/modules/conv.py
@@ -19,6 +19,8 @@ class _ConvNd(Module):
                      'out_channels', 'kernel_size']
     __annotations__ = {'bias': Optional[torch.Tensor]}
 
+    bias: torch.Tensor
+
     def __init__(self, in_channels, out_channels, kernel_size, stride,
                  padding, dilation, transposed, output_padding,
                  groups, bias, padding_mode):
```

Then run 

```
python test/test_jit.py TestScript.test_dropout_eval
```

You get

```
======================================================================
ERROR: test_dropout_eval (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_jit.py", line 8600, in test_dropout_eval
    script_mod = ScriptMod()
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1515, in init_then_script
    original_init(self, *args, **kwargs)
  File "test/test_jit.py", line 8569, in __init__
    self.Conv2d_1a_3x3 = ScriptedConv2d(3, 32, kernel_size=3, stride=2)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1521, in init_then_script
    self.__dict__["_actual_script_module"] = torch.jit._recursive.create_script_module(self, make_stubs)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 305, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 359, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1660, in _construct
    init_fn(script_module)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 340, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 359, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1660, in _construct
    init_fn(script_module)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_recursive.py", line 325, in init_fn
    cpp_module.setattr(name, orig_value)
RuntimeError: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'at::Tensor'

----------------------------------------------------------------------
```

**Comment by eellison** [comment]
I don't know what the exact fix here is, but probably running this example with gdb and backtracking frrom the error should reveal a place to add a better error message

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
