### ISSUE TITLE
DISABLED test_self_remote_rref_as_rpc_arg (__main__.RpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38236]
Same error as #37795. Looks like the GIL fix is not sufficient. 

https://app.circleci.com/pipelines/github/pytorch/pytorch/166686/workflows/dab671cc-3e57-460d-b588-85c1c7715fd4/jobs/5401139/steps

```
May 08 05:16:00   test_self_remote_rref_as_rpc_arg (__main__.RpcTestWithSpawn) ... ERROR:root:Caught exception: 
May 08 05:16:00 Traceback (most recent call last):
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 187, in wrapper
May 08 05:16:00     fn()
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 85, in new_test_method
May 08 05:16:00     return_value = old_test_method(self, *arg, **kwargs)
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 360, in test_self_remote_rref_as_rpc_arg
May 08 05:16:00     self._test_self_remote_rref_as_rpc_arg(dst)
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 354, in _test_self_remote_rref_as_rpc_arg
May 08 05:16:00     self.assertEqual(ret, torch.ones(2, 2) + 1 + 3 + torch.ones(2, 2) + 1)
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 883, in assertEqual
May 08 05:16:00     (rtol, atol) = self.get_default_tolerance(x, y)
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 869, in get_default_tolerance
May 08 05:16:00     a_tol = self.get_default_tolerance(a)
May 08 05:16:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 855, in get_default_tolerance
May 08 05:16:00     dtype = a.dtype
```

```
May 08 05:16:25 ======================================================================
May 08 05:16:25 ERROR [1.224s]: test_self_remote_rref_as_rpc_arg (__main__.RpcTestWithSpawn)
May 08 05:16:25 ----------------------------------------------------------------------
May 08 05:16:25 Traceback (most recent call last):
May 08 05:16:25   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 184, in wrapper
May 08 05:16:25     self._join_processes(fn)
May 08 05:16:25   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in _join_processes
May 08 05:16:25     self._check_return_codes(elapsed_time)
May 08 05:16:25   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 319, in _check_return_codes
May 08 05:16:25     raise RuntimeError(error)
May 08 05:16:25 RuntimeError: Processes 2 exited with error code 10
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
Tried a few thousands of times locally and in CI docker, but can no longer reproduce on master. Closing for now to let it run.
