### ISSUE TITLE
DISABLED test_backward_node_failure (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38232]
https://app.circleci.com/pipelines/github/pytorch/pytorch/167142/workflows/f9f81117-4442-4d4f-a792-a0cf8ccef7a9/jobs/5411466/steps

```
May 09 00:31:28   test_backward_node_failure (__main__.DistAutogradTestWithSpawn) ... [E thread_pool.cpp:112] Exception in thread pool task: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:40840
May 09 00:31:28 [E thread_pool.cpp:112] Exception in thread pool task: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:21152
May 09 00:31:28 [E container.cpp:248] Could not release Dist Autograd Context on node 1: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:21152 on node: 2
May 09 00:31:28 [E container.cpp:248] Could not release Dist Autograd Context on node 3: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:39126 on node: 2
May 09 00:31:28 [E container.cpp:248] Could not release Dist Autograd Context on node 1: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:50871 on node: 0
May 09 00:31:28 [E container.cpp:248] Could not release Dist Autograd Context on node 3: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:40840 on node: 0
May 09 00:33:07 Timing out after 100 seconds and killing subprocesses.
May 09 00:33:07 ERROR (100.021s)
May 09 00:33:08   test_backward_node_failure_python_udf (__main__.DistAutogradTestWithSpawn) ... [E thread_pool.cpp:112] Exception in thread pool task: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:34446
May 09 00:33:08 [E container.cpp:248] Could not release Dist Autograd Context on node 2: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:8079 on node: 0
May 09 00:33:08 [E container.cpp:248] Could not release Dist Autograd Context on node 2: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:10419 on node: 1
May 09 00:33:08 ok (0.918s)
```

```
May 09 00:33:59 ======================================================================
May 09 00:33:59 ERROR [100.021s]: test_backward_node_failure (__main__.DistAutogradTestWithSpawn)
May 09 00:33:59 ----------------------------------------------------------------------
May 09 00:33:59 Traceback (most recent call last):
May 09 00:33:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 184, in wrapper
May 09 00:33:59     self._join_processes(fn)
May 09 00:33:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in _join_processes
May 09 00:33:59     self._check_return_codes(elapsed_time)
May 09 00:33:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 324, in _check_return_codes
May 09 00:33:59     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
May 09 00:33:59 RuntimeError: Process 2 terminated or timed out after 100.0092408657074 seconds
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by jjlilley** [comment]
Shen, any ideas on what we should do with these?

As a group communication protocol, the underlying gloo/process_group doesn't seemed to be designed to be very elastic or resilient during the teardown phase? (maybe this is a mistaken perception? though I spent a bit of time looking at the teardown of this test case).

Once there's one dead receive socket, things seem to be effectively over.. even if we allow the listenLoop to recover, it will basically busy spin on the dead recv socket.

**Comment by mrshenli** [comment]
Hey @jjlilley sorry about the delay. 

Let's see if #38512 #38364 #38366 #38376 and #38348 are sufficient to fix this. Closing this for now.
