### ISSUE TITLE
RuntimeError: arg_types.size() == param_names.size() - (moduleSelf_ ? 1 : 0) INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#38240]
Steps to reproduce: edit `Module.__call__` to add a seemingly innocuous type signature:

```
    def __call__(self, *input: Any, **kwargs: Any):
```

This results in an assert failure:

```
======================================================================                                        
ERROR: test_call_python_mod_from_script_fn (__main__.TestScript)                                              
----------------------------------------------------------------------                 
Traceback (most recent call last):                                                                            
  File "test/test_jit.py", line 13838, in test_call_python_mod_from_script_fn                                 
    @torch.jit.script                                                                                         
  File "/data/users/ezyang/pytorch-tmp/torch/jit/__init__.py", line 1327, in script                           
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))                       
RuntimeError: arg_types.size() == param_names.size() - (moduleSelf_ ? 1 : 0) INTERNAL ASSERT FAILED at "../torch/csrc/jit/python/python_sugared_value.cpp":91, please report a bug to PyTorch.  
```

some prints from relevant internal variables:

```
signature = ([Any, Any], Tensor)                                                                              
param_names = self                                                                                            
moduleSelf_ = 0 
```

**Comment by hal-314** [comment]
I get this exact error with other code with Pytroch 1.9. It triggers due to  `from_tensor` classmethod. If I remove it, this error doesn't happen.

```python
class BBoxes:
    def __init__(self, bboxes: torch.Tensor, raise_if_not_floating_point: bool = True):
        if not bboxes.is_floating_point():
            if raise_if_not_floating_point:
                raise ValueError(f"Coordinates must be in floating point. Got {bboxes.dtype}")
            else:
                bboxes = bboxes.float()

        if bboxes.numel() == 0:
            # Use reshape, so we don't end up creating a new tensor that does not depend on
            # the inputs (and consequently confuses jit)
            bboxes = bboxes.reshape((-1, 4))

        if not (3 <= bboxes.ndim <= 4 and bboxes.shape[-2:] == (4, 2)):
            raise ValueError(f"BBoxes shape must be (N, 4, 2) or (B, N, 4, 2). Got {bboxes.shape}.")

        self._bboxes = bboxes

    def clip(self, height, width):
        r"""Clip the bboxes by limiting x coordinates to the range [0, width] and y coordinates to the range
        [0, height].

        Args:
            height: the height to clip the bboxes.
            width: the width to clip the bboxes.
        """
        clamped_bboxes = self._bboxes.detach().clone()
        clamped_bboxes[..., 0].clamp_(0, width)
        clamped_bboxes[..., 1].clamp_(0, height)
        # Due to some torch.jit.script bug (at least <= 1.9), you need to pass all arguments to __init__ when
        # constructing the class from inside of a method.
        return BBoxes(clamped_bboxes, False)

    @classmethod
    def from_tensor(cls, boxes: torch.Tensor, mode: str = "xyxy") -> "BBoxes":
        r"""Convert 2D bounding boxes to kornia format according to the format in which the boxes are provided.

        Args:
            boxes: 2D boxes to be transformed, shape of :math:`(N,4)` or :math:`(B,N,4)`.
            mode: The format in which the boxes are provided.

                * 'xyxy': boxes are assumed to be in the format ``xmin, ymin, xmax, ymax`` where ``width = xmax - xmin`` and
                  ``height = ymax - ymin``.
                * 'xyxy_plus_1': like 'xyxy' where ``width = xmax - xmin + 1`` and  ``height = ymax - ymin + 1``.
                * 'xywh': boxes are assumed to be in the format ``xmin, ymin, width, height`` where ``width = xmax - xmin``
                  and ``height = ymax - ymin``.
                * 'xywh_plus_1': like 'xywh' where ``width = xmax - xmin + 1`` and  ``height = ymax - ymin + 1``.

        Returns:
            2D Bounding boxes tensor in kornia format, shape of :math:`(N, 4, 2)` or :math:`(B, N, 4, 2)` and dtype of
            ``boxes`` if it's a floating point data type and ``float`` if not.

        Examples:
            >>> boxes_xyxy = torch.as_tensor([[0, 3, 1, 4], [5, 1, 8, 4]])
            >>> BBoxes.from_tensor(boxes_xyxy, mode='xyxy')
        """
        if not (2 <= boxes.ndim <= 3 and boxes.shape[-1] == 4):
            raise ValueError(f"BBox shape must be (N, 4) or (B, N, 4). Got {boxes.shape}.")

        batched = boxes.ndim == 3
        boxes = boxes if batched else boxes.unsqueeze(0)
        boxes = boxes if boxes.is_floating_point() else boxes.float()

        xmin, ymin = boxes[..., 0], boxes[..., 1]
        mode = mode.lower()
        if mode in ("xyxy", "xyxy_plus_1"):
            height, width = boxes[..., 3] - boxes[..., 1], boxes[..., 2] - boxes[..., 0]
        elif mode in ("xywh", "xywh_plus_1"):
            height, width = boxes[..., 3], boxes[..., 2]
        else:
            raise ValueError(f"Unknown mode {mode}")

        if mode.endswith("plus_1"):
            height -= 1
            width -= 1

        quadrilaterals = BBoxes._boxes_to_polygons(xmin, ymin, width, height)
        quadrilaterals = quadrilaterals if batched else quadrilaterals.squeeze(0)
        # Due to some torch.jit.script bug (at least <= 1.9), you need to pass all arguments to __init__ when
        # constructing the class from inside of a method.
        return BBoxes(quadrilaterals)

    def to_tensor(self,  mode: str = "xyxy") -> torch.Tensor:
        r"""Convert 2D bounding boxes in kornia format to the format specified by ``mode``.

        Args:
            kornia_boxes: boxes to be transformed, shape of :math:`(N, 4, 2)` or :math:`(B, N, 4, 2)`.
            mode: the ouput box format. It could be:

                * 'xyxy': boxes are defined as ``xmin, ymin, xmax, ymax`` where ``width = xmax - xmin`` and
                  ``height = ymax - ymin``.
                * 'xyxy_plus_1': like 'xyxy' where ``width = xmax - xmin + 1`` and  ``height = ymax - ymin + 1``.
                * 'xywh': boxes are defined as ``xmin, ymin, width, height`` where ``width = xmax - xmin``
                  and ``height = ymax - ymin``.
                * 'xywh_plus_1': like 'xywh' where ``width = xmax - xmin + 1`` and  ``height = ymax - ymin + 1``.
                * 'vertices': boxes are defined by their vertices points in the following ``clockwise`` order: *top-left,
                  top-right, bottom-right, bottom-left*. Vertices coordinates are in (x,y) order. Finally, box width and
                  height are defined as ``width = xmax - xmin`` and ``height = ymax - ymin``.
                * 'vertices_plus_1': like 'vertices' where ``width = xmax - xmin + 1`` and  ``height = ymax - ymin + 1``.

        Returns:
            Bounding boxes tensor the ``mode`` format. The shape is :math:`(N, 4, 2)` or :math:`(B, N, 4, 2)` in 'vertices'
            or 'vertices_plus_1' mode and :math:`(N, 4)` or :math:`(B, N, 4)` in all other cases.

        Examples:
            >>> bboxes_xyxy = torch.as_tensor([[0, 3, 1, 4], [5, 1, 8, 4]])
            >>> bboxes = BBoxes.from_tensor(bboxes_xyxy)
            >>> assert (bboxes_xyxy == bboxes.to_tensor(mode='xyxy')).all()
        """
        batched_bboxes = self._bboxes if self._is_batch else self._bboxes.unsqueeze(0)

        # Create boxes in xyxy format.
        boxes = (torch.stack([batched_bboxes.min(dim=-2).values, batched_bboxes.max(dim=-2).values], dim=-2)
                 .view(batched_bboxes.shape[0], batched_bboxes.shape[1], 4))

        mode = mode.lower()
        if mode in ("xyxy", "xyxy_plus_1"):
            pass
        elif mode in ("xywh", "xywh_plus_1", "vertices", "vertices_plus_1"):
            height, width = boxes[..., 3] - boxes[..., 1], boxes[..., 2] - boxes[..., 0]
            boxes[..., 2] = width
            boxes[..., 3] = height
        else:
            raise ValueError(f"Unknown mode {mode}")

        if mode.endswith("plus_1"):
            offset = torch.as_tensor([0, 0, 1, 1], device=boxes.device, dtype=boxes.dtype)
            boxes = boxes + offset

        if mode.startswith('vertices'):
            boxes = self._boxes_to_polygons(boxes[..., 0], boxes[..., 1], boxes[..., 2], boxes[..., 3])

        boxes = boxes if self._is_batch else boxes.squeeze(0)
        return boxes

    @property
    def _is_batch(self):
        return self._bboxes.ndim == 4

    # Note: it must be defined inside the class to support `torch.jit.script(BBoxes) and can't be an staticmethod
    @classmethod
    def _boxes_to_polygons(cls, xmin: torch.Tensor, ymin: torch.Tensor, width: torch.Tensor, height: torch.Tensor) -> torch.Tensor:
        if not xmin.ndim == ymin.ndim == width.ndim == height.ndim == 2:
            raise ValueError("We expect to create a batch of boxes in vertices format (B, N, 4, 2)")

        # Create (B,N,4,2) with all points in top left position of the bounding box
        polygons = torch.zeros((xmin.shape[0], xmin.shape[1], 4, 2), device=xmin.device, dtype=xmin.dtype)
        polygons[..., 0] = xmin.unsqueeze(-1)
        polygons[..., 1] = ymin.unsqueeze(-1)
        # Shift top-right, bottom-right, bottom-left points to the right coordinates
        polygons[..., 1, 0] += width  # Top right
        polygons[..., 2, 0] += width  # Bottom right
        polygons[..., 2, 1] += height  # Bottom right
        polygons[..., 3, 1] += height  # Bottom left
        return polygons
```

**Comment by munael** [comment]
I'm getting this when compiling a class with many custom class dependencies. I've fixed all the other signature issues that the jit reported, but this one doesn't point to any actual code :/

> arg_types.size() == param_names.size() - (moduleSelf_ ? 1 : 0) INTERNAL ASSERT FAILED at "../torch/csrc/jit/python/python_sugared_value.cpp":92

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
