### ISSUE TITLE
SIGXCPU at test_cholesky_solve with AMD EPYC 7742 64-Core Processor

### ISSUE THREAD

**Issue by surak** [pytorch/pytorch#38241]
## 🐛 Bug

RuntimeError: test_autograd failed! Received signal: SIGXCPU

## To Reproduce

1. `python test/run_test.py -v `

```
test_checkpointing (__main__.TestAutograd) ... skipped 'test is slow; run with PYTORCH_TEST_WITH_SLOW to enable test'
test_cholesky (__main__.TestAutograd) ... ok
test_cholesky_inverse (__main__.TestAutograd) ... ok
test_cholesky_solve (__main__.TestAutograd) ... Traceback (most recent call last):
  File "test/run_test.py", line 455, in <module>
    main()
  File "test/run_test.py", line 448, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed! Received signal: SIGXCPU
```

## Expected behavior

To pass the test

## Environment

`cpu time               (seconds, -t) 7200`

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): CentOS Linux 7 (Core)
 - How you installed PyTorch (`conda`, `pip`, source): source 
 - Build command you used (if compiling from source): `PYTORCH_BUILD_VERSION=1.4.0 PYTORCH_BUILD_NUMBER=1 VERBOSE=1 BUILD_CUSTOM_PROTOBUF=0 LDFLAGS="$LDFLAGS -ldl" USE_FFMPEG=ON USE_IBVERBS=1 USE_GFLAGS=ON USE_GLOG=ON CUDNN_INCLUDE_PATH=$EBROOTCUDNN/include CUDNN_LIBRARY_PATH=$EBROOTCUDNN/lib CUDNN_LIB_DIR=$EBROOTCUDNN/lib64 CUDNN_INCLUDE_DIR=$EBROOTCUDNN/include USE_SYSTEM_NCCL=1 NCCL_INCLUDE_DIR=$EBROOTNCCL/include pybind11_DIR=$EBROOTPYBIND11 TORCH_CUDA_ARCH_LIST="3.5 3.7 6.0 7.0"  python setup.py build`
 - Python version: 3.6.8
 - CUDA/cuDNN version: CUDA 10.1.105 / cuDNN 7.5.1.10
 - GPU models and configuration: NVIDIA V100
 - Any other relevant information:

```Currently Loaded Modules:
  1) Stages/Devel-2019a         (S)  14) freetype/.2.10.0   (H)  27) libspatialindex/.1.9.0           (H)  40) FFmpeg/.4.1.3                  (H)
  2) EasyBuild/4.1.2                 15) gperf/.3.1         (H)  28) NASM/.2.14.02                    (H)  41) nvidia/.driver                 (H,g)
  3) Developers/InstallSoftware      16) util-linux/.2.33.1 (H)  29) libjpeg-turbo/.2.0.2             (H)  42) CUDA/10.1.105                  (g)
  4) GCCcore/.8.3.0             (H)  17) fontconfig/.2.13.1 (H)  30) Python/3.6.8                          43) cuDNN/7.5.1.10-CUDA-10.1.105   (g)
  5) binutils/.2.32             (H)  18) X11/20190311            31) imkl/.2019.3.199                 (H)  44) magma/2.5.1
  6) bzip2/.1.0.6               (H)  19) Tk/.8.6.9          (H)  32) SciPy-Stack/2019a.1-Python-3.6.8      45) NCCL/2.4.6-1-CUDA-10.1.105     (g)
  7) zlib/.1.2.11               (H)  20) XZ/.5.2.4          (H)  33) MPFR/4.0.2                            46) pybind11/.2.2.4-Python-3.6.8   (H)
  8) ncurses/.6.1               (H)  21) libxml2/.2.9.9     (H)  34) GMP/6.1.2                             47) protobuf/.3.7.1                (H)
  9) libreadline/.8.0           (H)  22) libxslt/.1.1.33    (H)  35) numactl/2.0.12                        48) hypothesis/4.38.1-Python-3.6.8
 10) Tcl/8.6.9                       23) libffi/.3.2.1      (H)  36) libunwind/.1.3.1                 (H)  49) Ninja/1.9.0
 11) SQLite/.3.27.2             (H)  24) libyaml/.0.2.2     (H)  37) glog/.0.4.0                      (H)  50) GCC/8.3.0
 12) expat/.2.2.6               (H)  25) Java/1.8                38) gflags/.2.2.2                    (H)
 13) libpng/.1.6.36             (H)  26) PostgreSQL/11.2         39) x264/.20190429                   (H)
```

## Additional context

This is one of our new supercomputers, with AMD EPYC CPUs and NVIDIA V100s.

**Comment by ailzhang** [comment]
Hmmm we don't have the hardware to reproduce the error. It'll be better to narrow down where the SIGXCPU happens using gdb and provide more information. Thanks!
