### ISSUE TITLE
[CI] test_broadcast_coalesced (__main__.TestCuda): Memory exception on virtual address

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#38303]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/27223/console

```
04:40:23 test_broadcast_coalesced (__main__.TestCuda) ... Memory exception on virtual address 0xbeefdeadb000, node id 5 : Page not present
04:40:32 Address does not belong to a known buffer
04:40:32 Memory access fault by GPU node-5 (Agent handle: 0x3471970) on address 0xbeefdeadb000. Reason: Page not present or supervisor privilege.
04:40:39 Traceback (most recent call last):
04:40:39   File "test/run_test.py", line 690, in <module>
04:40:39     main()
04:40:39   File "test/run_test.py", line 683, in main
04:40:39     raise RuntimeError(message)
04:40:39 RuntimeError: test_cuda failed! Received signal: SIGIOT
```

cc @ezyang @gchanan @zou3519

**Comment by kshitij12345** [comment]
Link to similar issues for reference:
* https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/52
* https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/302

**Comment by kshitij12345** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test1/31646/console

```
18:15:09 test_AvgPool3d_divisor_stride1_pad0_gpu_input_cuda (__main__.TestNN) ... Memory exception on virtual address 0x7effdec00000, node id 5 : Page not present
18:15:09 Address does not belong to a known buffer
18:15:09 Memory access fault by GPU node-5 (Agent handle: 0x39f1720) on address 0x7effdec00000. Reason: Page not present or supervisor privilege.
18:15:19 Traceback (most recent call last):
18:15:19   File "test/run_test.py", line 690, in <module>
18:15:19     main()
18:15:19   File "test/run_test.py", line 683, in main
18:15:19     raise RuntimeError(message)
18:15:19 RuntimeError: test_nn failed! Received signal: SIGIOT
18:15:19 + cleanup
18:15:19 + retcode=1
18:15:19 + set +x
```

**Comment by jeffdaily** [comment]
This test is passing in latest ROCm 3.9 CI.  Please reopen if issue persists.
