### ISSUE TITLE
DISABLED test_backward_multiple_output_tensors (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38317]
https://app.circleci.com/jobs/github/pytorch/pytorch/5438276

```
May 12 07:02:57 ======================================================================
May 12 07:02:57 ERROR [1.119s]: test_backward_multiple_output_tensors (__main__.DistAutogradTestWithSpawn)
May 12 07:02:57 ----------------------------------------------------------------------
May 12 07:02:57 Traceback (most recent call last):
May 12 07:02:57   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 214, in wrapper
May 12 07:02:57     self._join_processes(fn)
May 12 07:02:57   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 316, in _join_processes
May 12 07:02:57     self._check_return_codes(elapsed_time)
May 12 07:02:57   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 349, in _check_return_codes
May 12 07:02:57     raise RuntimeError(error)
May 12 07:02:57 RuntimeError: Processes 0 2 3 exited with error code 10
May 12 07:02:57 
May 12 07:02:57 ----------------------------------------------------------------------
```

```
May 12 07:01:49   test_backward_multiple_output_tensors (__main__.DistAutogradTestWithSpawn) ... [E thread_pool.cpp:112] Exception in thread pool task: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [172.17.0.2]:36787: Connection reset by peer on node: 3
May 12 07:01:49 ERROR:root:Caught exception: 
May 12 07:01:49 Traceback (most recent call last):
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 217, in wrapper
May 12 07:01:49     fn()
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 85, in new_test_method
May 12 07:01:49     return_value = old_test_method(self, *arg, **kwargs)
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1144, in test_backward_multiple_output_tensors
May 12 07:01:49     exec_mode, [loss], context_id, local_grads, t
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 861, in _verify_backwards
May 12 07:01:49     self._verify_backwards_remote(tensors, context_id, local_grads, *args)
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 864, in _verify_backwards_remote
May 12 07:01:49     dist_autograd.backward(context_id, tensors)
May 12 07:01:49 RuntimeError: Error on Node 2: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [172.17.0.2]:40883: Connection reset by peer on node: 2
May 12 07:01:49 exiting process with exit code: 10
May 12 07:01:49 ERROR:root:Caught exception: 
May 12 07:01:49 Traceback (most recent call last):
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 217, in wrapper
May 12 07:01:49     fn()
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 85, in new_test_method
May 12 07:01:49     return_value = old_test_method(self, *arg, **kwargs)
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1140, in test_backward_multiple_output_tensors
May 12 07:01:49     val = self._exec_func(exec_mode, torch.chain_matmul, [t1, t2, t3])
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 210, in _exec_func
May 12 07:01:49     self._next_rank(), exec_mode, method, *args
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 199, in _exec_func_with_dst
May 12 07:01:49     return rpc.rpc_sync(worker_name(dst), method, args=(args))
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
May 12 07:01:49     return func(*args, **kwargs)
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 609, in rpc_sync
May 12 07:01:49     return fut.wait()
May 12 07:01:49 RuntimeError: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [172.17.0.2]:12717: Connection reset by peer on node: 0
May 12 07:01:49 exiting process with exit code: 10
May 12 07:01:49 ERROR:root:Caught exception: 
May 12 07:01:49 Traceback (most recent call last):
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 217, in wrapper
May 12 07:01:49     fn()
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 85, in new_test_method
May 12 07:01:49     return_value = old_test_method(self, *arg, **kwargs)
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1135, in test_backward_multiple_output_tensors
May 12 07:01:49     tensor_list = self._exec_func(exec_mode, torch.split, t, 2)
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 210, in _exec_func
May 12 07:01:49     self._next_rank(), exec_mode, method, *args
May 12 07:01:49   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 201, in _exec_func_with_dst
May 12 07:01:49     return rpc.remote(worker_name(dst), method, args=(args)).to_here()
May 12 07:01:49 RuntimeError: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [172.17.0.2]:36787: Connection reset by peer on node: 3
May 12 07:01:49 exiting process with exit code: 10
May 12 07:01:49 Process 0 terminated with exit code 10, terminating remaining processes.
May 12 07:01:49 ERROR (1.119s)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @jjlilley @mrzzd @bdhirsh @xush6528

**Comment by mrshenli** [comment]
Let's see if #38512 #38364 #38366 #38376 and #38348 are sufficient to fix this.

**Comment by gcramer23** [comment]
The test is failing in CI https://app.circleci.com/pipelines/github/pytorch/pytorch/375291/workflows/e3684f16-e8e7-4b7d-bdfc-3ddcc0e32abc/jobs/15831281. It failed two times in a row.  It passes on the AI cluster.

**Comment by clee2000** [comment]
I'm fairly sure this test either got renamed or was deleted
