### ISSUE TITLE
DISABLED test_embedding_bag_with_no_grad_tensors (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38324]
https://app.circleci.com/jobs/github/pytorch/pytorch/5435365

```
May 12 04:44:40   test_embedding_bag_with_no_grad_tensors (__main__.DistAutogradTestWithSpawn) ... [W pybind_utils.h:736] Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (function operator())
May 12 04:44:40 [W pybind_utils.h:736] Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (function operator())
May 12 04:44:40 [E process_group_agent.cpp:689] Encountered exception in ProcessGroupAgent::listenLoop(): [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [172.17.0.2]:23463: Connection reset by peer on worker 1. This means that the RPC agent is in an unhealthy state and unusable.
May 12 04:44:40 ERROR:root:Caught exception: 
May 12 04:44:40 Traceback (most recent call last):
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 217, in wrapper
May 12 04:44:40     fn()
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 88, in new_test_method
May 12 04:44:40     rpc.shutdown(graceful=clean_shutdown)
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
May 12 04:44:40     return func(*args, **kwargs)
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 242, in shutdown
May 12 04:44:40     _wait_all_workers()
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
May 12 04:44:40     return func(*args, **kwargs)
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 164, in _wait_all_workers
May 12 04:44:40     args=(sequence_id, self_worker_name,),
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
May 12 04:44:40     return func(*args, **kwargs)
May 12 04:44:40   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 609, in rpc_sync
May 12 04:44:40     return fut.wait()
May 12 04:44:40 RuntimeError: Encountered exception in ProcessGroupAgent::enqueueSend: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [172.17.0.2]:38308: Connection reset by peer on node: 2
May 12 04:44:40 exiting process with exit code: 10
May 12 04:44:41 Process 2 terminated with exit code 10, terminating remaining processes.
May 12 04:44:41 ERROR (1.018s)
```

```
May 12 04:45:05 ======================================================================
May 12 04:45:05 ERROR [1.018s]: test_embedding_bag_with_no_grad_tensors (__main__.DistAutogradTestWithSpawn)
May 12 04:45:05 ----------------------------------------------------------------------
May 12 04:45:05 Traceback (most recent call last):
May 12 04:45:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 214, in wrapper
May 12 04:45:05     self._join_processes(fn)
May 12 04:45:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 316, in _join_processes
May 12 04:45:05     self._check_return_codes(elapsed_time)
May 12 04:45:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 349, in _check_return_codes
May 12 04:45:05     raise RuntimeError(error)
May 12 04:45:05 RuntimeError: Processes 2 exited with error code 10
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
Let's see if #38512 #38364 #38366 #38376 and #38348 are sufficient to fix this.
