### ISSUE TITLE
 forward() missing 1 required positional argument: 'input'

### ISSUE THREAD

**Issue by boundles** [pytorch/pytorch#3833]
Traceback (most recent call last):
  File "main.py", line 505, in <module>
    main(parser.parse_args())
  File "main.py", line 459, in main
    model = train(args, model, True) #Train encoder
  File "main.py", line 216, in train
    outputs = model(inputs, only_encode=enc)
  File "/home/darren.wy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/darren.wy/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/darren.wy/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 78, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/darren.wy/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/home/darren.wy/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/home/darren.wy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

Pls any solutions?

**Comment by apaszke** [comment]
This is related to examples. Since you opened an issue there I’m closing this one. Please don’t cross post issues in the future
