### ISSUE TITLE
C++ extension with nightly build generates undefined symbol.

### ISSUE THREAD

**Issue by mthrok** [pytorch/pytorch#38360]
## 🐛 Bug

I am building a torchscript custom class with an external library (`sentencepiece`). I noticed that when I build the extension with PyTorch I compiled from the source, it works fine, but when I use nightly build version of PyTorch, it introduces an undefined symbol to the resulting extension and it fails to import the extension.
I am not sure if this is bug or I am not compiling the external library correct, and I would like to get an advice.

## To Reproduce

Run the following script in a Ubuntu:18.04 container.

<Details><Summary>1. build_with_souce_installation.sh </Summary>

```bash
#!/usr/bin/env bash

# Install requirements
apt update
apt install -y -q --no-install-recommends \
  build-essential \
  cmake \
  git \
  openssh-client \
  wget \
  ca-certificates

# Install conda
wget -O miniconda.sh http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash miniconda.sh -b -f -p /conda

eval "$(/conda/bin/conda shell.bash hook)"
conda init

# Create env
conda create -y --prefix /test-env python=3.8
conda activate /test-env
conda install -y numpy ninja pyyaml mkl mkl-include setuptools cmake cffi

# build and install pytorch
git clone --recursive https://github.com/pytorch/pytorch
(
    cd pytorch
    git submodule update --init --recursive
    export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
    python setup.py install
)

# build and install torchtext
git clone https://github.com/mthrok/text
(
    cd text
    git fetch
    git checkout fix-import
    git submodule update --init --recursive
    python setup.py install
)

# check symbols
nm /test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/_torchtext.so | grep sentencepiece | grep ToString

# import torchtext
cd /
python -c 'import torchtext'
```

</Details>

<Details><Summary>2. build_with_nightly.sh </Summary>

```bash
#!/usr/bin/env bash

apt update
apt install -y -q --no-install-recommends \
    build-essential \
    cmake \
    git \
    openssh-client \
    wget \
    ca-certificates

# Install conda
wget -O miniconda.sh http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash miniconda.sh -b -f -p /conda

eval "$(/conda/bin/conda shell.bash hook)"
conda init

# Create env
conda create -y --prefix /test-env python=3.8
conda activate /test-env
conda install -y numpy ninja pyyaml mkl mkl-include setuptools cmake cffi

# Install PyTorch nightly
conda install -y pytorch cpuonly -c pytorch-nightly

# build and install torchtext
git clone https://github.com/mthrok/text
(
    cd text
    git fetch
    git checkout fix-import
    git submodule update --init --recursive
    python setup.py install
)

# Check symbols
nm /test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/_torchtext.so | grep sentencepiece | grep ToString

# import torchtext
cd /
python -c 'import torchtext'
```

</Details>

Case 1: `python -c "import torchtext"` at the end succeeds.
Case 2: `python -c "import torchtext"` fails with the following error.

```
(/test-env) root@81d3d5629532:/# python -c "import torchtext"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/__init__.py", line 36, in <module>
    _init_extension()
  File "/test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/__init__.py", line 32, in _init_extension
    torch.ops.load_library(ext_specs.origin)
  File "/test-env/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/test-env/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/_torchtext.so: undefined symbol: _ZNK13sentencepiece4util6Status8ToStringEv
```

When I check the symbols, I do not see an undefined symbol in the case1, but I see an undefined symbol in the case2.

**Case 1.** No undefined symbol
```
(/test-env) root@d07331cca911:/# nm /test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/_torchtext.so | grep sentencepiece | grep ToString
000000000009cfe0 T _ZNK13sentencepiece3bpe7Trainer6Symbol8ToStringB5cxx11Ev
00000000000d7d70 T _ZNK13sentencepiece4util6Status8ToStringB5cxx11Ev
```

**Case 2.** An undefined symbol

```
(/test-env) root@81d3d5629532:/# nm /test-env/lib/python3.8/site-packages/torchtext-0.6.0-py3.8-linux-x86_64.egg/torchtext/_torchtext.so | grep sentencepiece | grep ToString
000000000009c220 T _ZNK13sentencepiece3bpe7Trainer6Symbol8ToStringB5cxx11Ev
00000000000d6fb0 T _ZNK13sentencepiece4util6Status8ToStringB5cxx11Ev
                 U _ZNK13sentencepiece4util6Status8ToStringEv
```

## Expected behavior

`python -c "import torchtext"` should succeed in case 2.

## Environment

<Details> <Summary>Env1</Summary>

```
PyTorch version: 1.6.0a0+d5a7d79
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.14.0

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0a0+d5a7d79
[pip] torchtext==0.6.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.0.15           py38ha843d7b_0
[conda] mkl_random                1.1.0            py38h962f231_0
[conda] numpy                     1.18.1           py38h4f9e942_0
[conda] numpy-base                1.18.1           py38hde5b4d6_1
[conda] torch                     1.6.0a0+d5a7d79          pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
```

</Details>

<Details> <Summary>Env2</Summary>

```
PyTorch version: 1.6.0.dev20200512
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.14.0

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0.dev20200512
[pip] torchtext==0.6.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.0.15           py38ha843d7b_0
[conda] mkl_random                1.1.0            py38h962f231_0
[conda] numpy                     1.18.1           py38h4f9e942_0
[conda] numpy-base                1.18.1           py38hde5b4d6_1
[conda] pytorch                   1.6.0.dev20200512     py3.8_cpu_0  [cpuonly]  pytorch-nightly
[conda] torchtext                 0.6.0                    pypi_0    pypi
```

</Details>

## Additional context

During the build step of `torchtext`, `sentencepiece` is firstly built statically using `cmake` and provided `CMakeLists`, then linked against our torchtext extension.

**Comment by ezyang** [comment]
It looks like a C++ compiler version mismatch

**Comment by mthrok** [comment]
Where can I find the correct compiler version?
I thought if the compiler version is wrong, the build process would produce warning.

**Comment by mthrok** [comment]
So according to [this](https://github.com/pytorch/builder/blob/f0dd04b3d803980d6c6a39ca3e19523272fe476a/conda/Dockerfile#L10), nightly build uses gcc `7.3.1`.

```
# gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and my environments have gcc `7.5.0`

```
# gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

 Is 7.5 not compatible with 7.3?

**Comment by mthrok** [comment]
Yes, it was just a compiler mismatch.
