### ISSUE TITLE
[CI] test_gloo_backend_2gpu_module (__main__.DistributedDataParallelTest)

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#38395]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/27582/console
```
09:34:27 ======================================================================
09:34:27 ERROR: test_gloo_backend_2gpu_module (__main__.DistributedDataParallelTest)
09:34:27 ----------------------------------------------------------------------
09:34:27 Traceback (most recent call last):
09:34:27   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
09:34:27     self._join_processes(fn)
09:34:27   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
09:34:27     self._check_return_codes(elapsed_time)
09:34:27   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
09:34:27     raise RuntimeError(error)
09:34:27 RuntimeError: Processes 1 exited with error code 10
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by kshitij12345** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/27875/console

```
18:34:46 ======================================================================
18:34:46 ERROR: test_gloo_backend_2gpu_module (__main__.DistributedDataParallelTest)
18:34:46 ----------------------------------------------------------------------
18:34:46 Traceback (most recent call last):
18:34:46   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
18:34:46     self._join_processes(fn)
18:34:46   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
18:34:46     self._check_return_codes(elapsed_time)
18:34:46   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
18:34:46     raise RuntimeError(error)
18:34:46 RuntimeError: Processes 1 exited with error code 10
```

**Comment by zhaojuanmao** [comment]
closing it, it is not reported anymore, also it only failed on rocm. rocm tests were fixed a while ago
