### ISSUE TITLE
[CI] rocmdeb-ubuntu : test_*_bfloat16_cuda (__main__.TestNNDeviceTypeCUDA)

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#38396]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test1/31353/console

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test1/31369/console

```
09:24:32 ======================================================================
09:24:32 FAIL: test_activations_bfloat16_cuda (__main__.TestNNDeviceTypeCUDA)
09:24:32 ----------------------------------------------------------------------
09:24:32 Traceback (most recent call last):
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 753, in wrapper
09:24:32     method(*args, **kwargs)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 210, in instantiated_test
09:24:32     return test(self, device_arg)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 465, in only_fn
09:24:32     return fn(slf, device, *args, **kwargs)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 404, in dep_fn
09:24:32     return fn(slf, device, *args, **kwargs)
09:24:32   File "test_nn.py", line 11063, in test_activations_bfloat16
09:24:32     self._test_bfloat16_ops(torch.nn.ReLU(), device, inp_dims=(5), prec=1e-2)
09:24:32   File "test_nn.py", line 11057, in _test_bfloat16_ops
09:24:32     self.assertEqual(out1, out2, atol=prec)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 989, in assertEqual
09:24:32     assertTensorsEqual(x, y)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 924, in assertTensorsEqual
09:24:32     self.assertEqual(a.dtype, b.dtype)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1022, in assertEqual
09:24:32     super().assertEqual(x, y, message)
09:24:32 AssertionError: torch.float32 != torch.bfloat16 : 
09:24:32 
09:24:32 ======================================================================
09:24:32 FAIL: test_pooling_bfloat16_cuda (__main__.TestNNDeviceTypeCUDA)
09:24:32 ----------------------------------------------------------------------
09:24:32 Traceback (most recent call last):
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 753, in wrapper
09:24:32     method(*args, **kwargs)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 210, in instantiated_test
09:24:32     return test(self, device_arg)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 465, in only_fn
09:24:32     return fn(slf, device, *args, **kwargs)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 404, in dep_fn
09:24:32     return fn(slf, device, *args, **kwargs)
09:24:32   File "test_nn.py", line 11074, in test_pooling_bfloat16
09:24:32     self._test_bfloat16_ops(torch.nn.AvgPool1d(3, stride=2), device, inp_dims=(8, 4, 16), prec=0.05)
09:24:32   File "test_nn.py", line 11057, in _test_bfloat16_ops
09:24:32     self.assertEqual(out1, out2, atol=prec)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 989, in assertEqual
09:24:32     assertTensorsEqual(x, y)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 924, in assertTensorsEqual
09:24:32     self.assertEqual(a.dtype, b.dtype)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1022, in assertEqual
09:24:32     super().assertEqual(x, y, message)
09:24:32 AssertionError: torch.float32 != torch.bfloat16 : 
09:24:32 
09:24:32 ======================================================================
09:24:32 FAIL: test_softmax_bfloat16_cuda (__main__.TestNNDeviceTypeCUDA)
09:24:32 ----------------------------------------------------------------------
09:24:32 Traceback (most recent call last):
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 753, in wrapper
09:24:32     method(*args, **kwargs)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 210, in instantiated_test
09:24:32     return test(self, device_arg)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 465, in only_fn
09:24:32     return fn(slf, device, *args, **kwargs)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 404, in dep_fn
09:24:32     return fn(slf, device, *args, **kwargs)
09:24:32   File "test_nn.py", line 11084, in test_softmax_bfloat16
09:24:32     self._test_bfloat16_ops(torch.nn.Softmax(dim=1), device, inp_dims=(16, 32), prec=1e-2)
09:24:32   File "test_nn.py", line 11057, in _test_bfloat16_ops
09:24:32     self.assertEqual(out1, out2, atol=prec)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 989, in assertEqual
09:24:32     assertTensorsEqual(x, y)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 924, in assertTensorsEqual
09:24:32     self.assertEqual(a.dtype, b.dtype)
09:24:32   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1022, in assertEqual
09:24:32     super().assertEqual(x, y, message)
09:24:32 AssertionError: torch.float32 != torch.bfloat16 :
```

**Comment by jeffdaily** [comment]
These tests are enabled and passing in latest ROCm CI.
