### ISSUE TITLE
Python builtin function next() is currently not supported in Torchscript

### ISSUE THREAD

**Issue by GrzegorzKarchNV** [pytorch/pytorch#38473]
## 🐛 Bug

Python builtin function next() is currently not supported in Torchscript

## To Reproduce

```bash
import torch
from torch import nn

class Next(nn.Module):
    def __init__(self):
        super(Next, self).__init__()
    def forward(self, x):
        device = next(self.parameters()).device
        x = x.to(device)
        return x

model = Next()
model.cuda()

jitted_model = torch.jit.script(model)
```

```bash
Traceback (most recent call last):
  File "next.py", line 15, in <module>
    jitted_model = torch.jit.script(model)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 1267, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py", line 299, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py", line 346, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py", line 273, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:
Python builtin <built-in function next> is currently not supported in Torchscript:
  File "next.py", line 8
    def forward(self, x):
        device = next(self.parameters()).device
                 ~~~~ <--- HERE
        x = x.to(device)
        return x
```

## Expected behavior

Successful conversion to TorchScript

## Environment

PYTORCH_VERSION=1.5.0a0+8f84ded

**Comment by SplitInfinity** [comment]
Even if `next` was supported, generators like `self.parameters` are not, so this still wouldn't work. What you could do is convert the parameters to a list and store an index into that list in `__init__`:
```
def __init__(self):
   <create params>
  self.p = list(self.parameters())
  self.i = 0
```
and then use `self.i` to index into the list in forward and increment it:
```
def forward(self, x):
  device = self.p[self.i].device
  self.i += 1
  x = x.to(device)
  return x
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
