### ISSUE TITLE
expected scalar type Half but found Float with torch.cuda.amp and torch.nn.DataParallel

### ISSUE THREAD

**Issue by blizda** [pytorch/pytorch#38487]
## 🐛 Bug

I try to using amp in Pytorch core with torch.nn.DataParallel for multi-gpu training. I wrap forward pass in model to autocast, but get error  

## To Reproduce

1. install sinkhorn_transformer==0.4.4, transformers
2. run following script

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import sinkhorn_transformer
from sinkhorn_transformer import SinkhornTransformerLM
from transformers import BertTokenizer, AdamW
from torch.cuda.amp import autocast, GradScaler 

def mask_tokens(inputs: torch.Tensor, tokenizer, mlm_probability=0.15, pad=True):
    """ Prepare masked tokens inputs/labels for masked language modeling: 80% MASK, 10% random, 10% original. """
    labels = inputs.clone()
    # mlm_probability defaults to 0.15 in Bert
    probability_matrix = torch.full(labels.shape, mlm_probability)
    special_tokens_mask = [
        tokenizer.get_special_tokens_mask(val, already_has_special_tokens=True) for val in labels.tolist()
    ]
    probability_matrix.masked_fill_(torch.tensor(special_tokens_mask, dtype=torch.bool), value=0.0)
    if tokenizer._pad_token is not None:
        padding_mask = labels.eq(tokenizer.pad_token_id)
        probability_matrix.masked_fill_(padding_mask, value=0.0)
    masked_indices = torch.bernoulli(probability_matrix).bool()
    labels[~masked_indices] = -100  # We only compute loss on masked tokens

    # 80% of the time, we replace masked input tokens with tokenizer.mask_token ([MASK])
    indices_replaced = torch.bernoulli(torch.full(labels.shape, 0.8)).bool() & masked_indices
    inputs[indices_replaced] = tokenizer.convert_tokens_to_ids(tokenizer.mask_token)

    # 10% of the time, we replace masked input tokens with random word
    indices_random = torch.bernoulli(torch.full(labels.shape, 0.5)).bool() & masked_indices & ~indices_replaced
    random_words = torch.randint(len(tokenizer), labels.shape, dtype=torch.long)
    inputs[indices_random] = random_words[indices_random]

    if pad:
        input_pads = tokenizer.max_len - inputs.shape[-1]
        label_pads = tokenizer.max_len - labels.shape[-1]
        
        inputs = F.pad(inputs, pad=(0,input_pads), value=tokenizer.pad_token_id)
        labels = F.pad(labels, pad=(0,label_pads), value=tokenizer.pad_token_id)
    
    # The rest of the time (10% of the time) we keep the masked input tokens unchanged
    return inputs, labels

def read_batch_from_dataset_restored(tokenizer):
    batch = []
    iterat = 0
    for it in range(1000):
        yield torch.randint(3, tokenizer.vocab_size, (4, 40960))

class LossWraper(nn.Module):
  def __init__(self, model, loss=None):
    super(LossWraper, self).__init__()
    self.model = model
    self.loss = loss
    
  @autocast()
  def forward(self, inputs, labels=None):
    loss_mx = labels != -100
    output = self.model(inputs)
    output = output[loss_mx].view(-1, tokenizer.vocab_size)
    labels = labels[loss_mx].view(-1)
    loss = self.loss(output, labels)
    return loss, output

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = SinkhornTransformerLM(
    num_tokens= tokenizer.vocab_size,
    dim = 768,
    depth = 12,
    max_seq_len = 40960,
    heads = 16,
    buckets = 64,
    causal = False,           # auto-regressive or not
    sinkhorn_iter = 7,        # number of sinkhorn iterations - default is set at reported best in paper
    n_sortcut = 2,            # use sortcut to reduce complexity to linear time
    temperature = 0.75,       # gumbel temperature - default is set at reported best in paper
    non_permutative = False,  # allow buckets of keys to be sorted to queries more than once
    attn_sort_net = True,     # attention to reorder the buckets, unlocks flexible sequence lengths
    ff_chunks = 10,           # feedforward chunking, from Reformer paper
    reversible = True,        # make network reversible, from Reformer paper
    ff_dropout = 0.1,         # feedforward dropout
    attn_dropout = 0.1,       # post attention dropout
    attn_layer_dropout = 0.1, # post attention layer dropout
    layer_dropout = 0.1,      # add layer dropout, from 'Reducing Transformer Depth on Demand' paper
    weight_tie = True,        # tie layer parameters, from Albert paper
    emb_dim = 128,            # embedding factorization, from Albert paper
    ff_glu = True,            # use GLU in feedforward, from paper 'GLU Variants Improve Transformer'
    n_local_attn_heads = 4,   # replace N heads with local attention, suggested to work well from Routing Transformer paper
)
device = torch.device("cuda")
loss_fn = nn.CrossEntropyLoss()
model = LossWraper(model, loss_fn)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
model.to(device)
scaler = GradScaler()
model = torch.nn.DataParallel(model)
model.train()
for ep in range(50):
    running_loss = 0.0
    for it in read_batch_from_dataset_restored(tokenizer):
        optimizer.zero_grad()
        torch.cuda.empty_cache()
        inp, mask = mask_tokens(it, tokenizer)
        inputs, labels = inp.to("cuda"), mask.to("cuda")
        with autocast():
            output = model(inputs, labels)
            loss = output[0]
            loss = loss.mean()
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.25)
        scaler.step(optimizer)
        scaler.update()
```

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-7a29bfd8a4a8> in <module>
     62             loss = loss.mean()
     63         print(loss)
---> 64         scaler.scale(loss).backward()
     65         scaler.unscale_(optimizer)
     66         #with amp.scale_loss(loss, optimizer) as scaled_loss:

/opt/anaconda/envs/pytorch_apex_core_cuda_10.1/lib/python3.8/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    182                 products. Defaults to ``False``.
    183         """
--> 184         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    185 
    186     def register_hook(self, hook):

/opt/anaconda/envs/pytorch_apex_core_cuda_10.1/lib/python3.8/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    119         retain_graph = create_graph
    120 
--> 121     Variable._execution_engine.run_backward(
    122         tensors, grad_tensors, retain_graph, create_graph,
    123         allow_unreachable=True)  # allow_unreachable flag

RuntimeError: expected scalar type Half but found Float

## Environment

PyTorch version: 1.6.0.dev20200514
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0.dev20200514
[pip] torchvision==0.7.0.dev20200514
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.0.15           py38ha843d7b_0  
[conda] mkl_random                1.1.0            py38h962f231_0  
[conda] numpy                     1.18.1           py38h4f9e942_0  
[conda] numpy-base                1.18.1           py38hde5b4d6_1  
[conda] pytorch                   1.6.0.dev20200514 py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.7.0.dev20200514      py38_cu101    pytorch-nightly

**Comment by ptrblck** [comment]
Hi @blizda,

thanks for raising this issue.
Based on the provided code it seems that the `@autocast` decorator should be placed correctly.

We'll try to reproduce this issue and debug.

CC @mcarilli

**Comment by blizda** [comment]
Also, If replaced 

```python
@autocast()
  def forward(self, inputs, labels=None):
    loss_mx = labels != -100
    output = self.model(inputs)
    output = output[loss_mx].view(-1, tokenizer.vocab_size)
    labels = labels[loss_mx].view(-1)
    loss = self.loss(output, labels)
    return loss, output
```

to 

```python
  def forward(self, inputs, labels=None):
    with autocast():
        loss_mx = labels != -100
        output = self.model(inputs)
        output = output[loss_mx].view(-1, tokenizer.vocab_size)
        labels = labels[loss_mx].view(-1)
        loss = self.loss(output, labels)
    return loss, output
```
the issue is still reproducing

**Comment by mcarilli** [comment]
Do you know if this model uses any [custom autograd functions](https://pytorch.org/docs/master/notes/amp_examples.html#autocast-and-custom-autograd-functions)?

**Comment by blizda** [comment]
> Do you know if this model uses any [custom autograd functions](https://pytorch.org/docs/master/notes/amp_examples.html#autocast-and-custom-autograd-functions)?

I'm not 100 percent sure, but as far as I understand, no.

**Comment by JCBrouwer** [comment]
Hello, I'm seeing the same error as well. My model does have CUDA extensions, but I've added custom_fwd & custom_bwd to the forward/backward definitions. Also I'm using DistributedDataParallel not DataParallel. 

If I set cast_inputs it does work, but I believe that shouldn't be necessary.

The traceback:
```
Traceback (most recent call last):
  File "train.py", line 442, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, scaler, g_ema, device)
  File "train.py", line 107, in train
    fake_img, _ = generator(noise)
  File "/home/hans/.conda/envs/maua-stylegan2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hans/code/maua-stylegan2/model.py", line 455, in forward
    styles = [self.style(s) for s in styles]
  File "/home/hans/code/maua-stylegan2/model.py", line 455, in <listcomp>
    styles = [self.style(s) for s in styles]
  File "/home/hans/.conda/envs/maua-stylegan2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hans/.conda/envs/maua-stylegan2/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/hans/.conda/envs/maua-stylegan2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hans/code/maua-stylegan2/model.py", line 142, in forward
    out = fused_leaky_relu(out, self.bias * self.lr_mul)
  File "/home/hans/code/maua-stylegan2/op/fused_act.py", line 82, in fused_leaky_relu
    return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale)
  File "/home/hans/.conda/envs/maua-stylegan2/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 195, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/hans/code/maua-stylegan2/op/fused_act.py", line 51, in forward
    out = fused.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
RuntimeError: expected scalar type Half but found Float
```

Top of call stack:
```
        with th.cuda.amp.autocast():
            noise = make_noise(args.batch_size, args.latent_size, args.mixing_prob, device)
            fake_img, _ = generator(noise)
            fake_pred = discriminator(fake_img)
            real_pred = discriminator(real_img)

            # logistic loss
            real_loss = F.softplus(-real_pred)
            fake_loss = F.softplus(fake_pred)
            d_loss = real_loss.mean() + fake_loss.mean()

        discriminator.zero_grad()
        scaler.scale(d_loss).backward()
        scaler.step(d_optim)
```

Site of the error:
```
class FusedLeakyReLUFunction(Function):
    @staticmethod
    @torch.cuda.amp.custom_fwd
    def forward(ctx, input, bias, negative_slope, scale):
        empty = input.new_empty(0)
        print(input.dtype, bias.dtype, empty.dtype)
        out = fused.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
        ctx.save_for_backward(out)
        ctx.negative_slope = negative_slope
        ctx.scale = scale
        return out
```
The print just before the failing call prints `torch.float16 torch.float32 torch.float16`

The full code can be found here: https://github.com/JCBrouwer/maua-stylegan2/

PS: Let me know if I should move this to a separate issue!

**Comment by mcarilli** [comment]
`@torch.cuda.amp.custom_fwd` (without any arguments) + `@torch.cuda.amp.custom_bwd`
- does not cast forward inputs
- ensures calls to _native_ Pytorch methods in custom autograd forward/backward methods are properly handled by autocast
- doesn't know about your `fused_bias_act` extension function, so doesn't do anything to help it.

Therefore, when using a custom extension function within a custom autograd function, (`@torch.cuda.amp.custom_fwd(cast_inputs=fdsa)` is necessary to ensure the extension function gets arguments with the right dtypes.  `cast_inputs=fdsa` expresses what dtype you want the function to run in.

If it's fine in fp16 or fp32, and all it needs is for arguments to have matching dtypes, maybe I should add a `cast_inputs="promote_to_match"`) option.

As an alternative to the decorators, you can always locally disable autocast and force inputs to particular types, ie
```python
    def forward(ctx, input, bias, negative_slope, scale):
        empty = input.new_empty(0)
        with autocast(enabled=False):
            out = fused.fused_bias_act(input.float(), bias.float(), empty.float(), 3, 0, negative_slope, scale)
        ...
    def backward(ctx, ...):
        with autocast(enabled=False):
            return fused.xyz(grad0.float,...)
```

**Comment by blizda** [comment]
@mcarilli I get same error with another model set ```python TORCH_SHOW_CPP_STACKTRACES=1``` and run 

```python
RuntimeError: expected scalar type Half but found Float
Exception raised from data_ptr<c10::Half> at /pytorch/build/aten/src/ATen/core/TensorMethods.cpp:8627 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7ff887b971e2 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::Half* at::Tensor::data_ptr<c10::Half>() const + 0x113 (0x7ff871111823 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #2: void at::native::(anonymous namespace)::LayerNormKernelImplInternal<c10::Half>(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, c10::Half, at::Tensor*, at::Tensor*, at::Tensor*) + 0x4c (0x7ff82ef09eec in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: at::native::(anonymous namespace)::LayerNormKernelImpl(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, double, at::Tensor*, at::Tensor*, at::Tensor*) + 0x445 (0x7ff82ef03125 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::native::layer_norm_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, double) + 0x137 (0x7ff82ef03737 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xf4216e (0x7ff82d79316e in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xa9da9b (0x7ff87086ca9b in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: at::native_layer_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, double) + 0x142 (0x7ff870fadb72 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2f839cc (0x7ff872d529cc in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0xa9da9b (0x7ff87086ca9b in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::native_layer_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, double) + 0x142 (0x7ff870fadb72 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: at::native::layer_norm(at::Tensor const&, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, double, bool) + 0x9f (0x7ff870d23daf in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x12c5d52 (0x7ff871094d52 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x2ecbb73 (0x7ff872c9ab73 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0xa9da78 (0x7ff87086ca78 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #15: at::layer_norm(at::Tensor const&, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, double, bool) + 0x14b (0x7ff870ff0f3b in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x30d1f7 (0x7ff8987491f7 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #17: _PyMethodDef_RawFastCallKeywords + 0x264 (0x557f8e8b6c94 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #18: _PyCFunction_FastCallKeywords + 0x21 (0x557f8e8b6db1 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x4dee (0x557f8e9225be in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #20: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #21: _PyFunction_FastCallKeywords + 0x325 (0x557f8e8b6435 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x4a59 (0x557f8e922229 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #23: _PyFunction_FastCallDict + 0x10b (0x557f8e86731b in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #24: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #25: PyObject_Call + 0x6e (0x557f8e87895e in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x1d4a (0x557f8e91f51a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #27: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #28: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #29: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #30: <unknown function> + 0x16c16a (0x557f8e8bd16a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #31: _PyObject_FastCallKeywords + 0x48b (0x557f8e8be00b in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x51d1 (0x557f8e9229a1 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #33: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #34: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #35: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #36: PyObject_Call + 0x6e (0x557f8e87895e in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x1d4a (0x557f8e91f51a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #38: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #39: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #40: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #41: <unknown function> + 0x16c16a (0x557f8e8bd16a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #42: PyObject_Call + 0x6e (0x557f8e87895e in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #43: _PyEval_EvalFrameDefault + 0x1d4a (0x557f8e91f51a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #44: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #45: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #46: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #47: PyObject_Call + 0x6e (0x557f8e87895e in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x1d4a (0x557f8e91f51a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #49: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #50: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #51: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #52: <unknown function> + 0x16c16a (0x557f8e8bd16a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #53: PyObject_Call + 0x6e (0x557f8e87895e in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #54: _PyEval_EvalFrameDefault + 0x1d4a (0x557f8e91f51a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #55: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #56: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #57: _PyEval_EvalFrameDefault + 0x1d4a (0x557f8e91f51a in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #58: _PyEval_EvalCodeWithName + 0x2f9 (0x557f8e8662b9 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #59: _PyFunction_FastCallDict + 0x1d5 (0x557f8e8673e5 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #60: _PyObject_Call_Prepend + 0x63 (0x557f8e885b93 in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #61: PyObject_Call + 0x6e (0x557f8e87895e in /opt/anaconda/envs/install_nt_from_pip/bin/python)
frame #62: torch::autograd::PyNode::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x183 (0x7ff898977733 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #63: <unknown function> + 0x33bce67 (0x7ff87318be67 in /opt/anaconda/envs/install_nt_from_pip/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
```

**Comment by JCBrouwer** [comment]
Thanks for the response @mcarilli 

I think the documentation should make it more clear that this autocasting only happens for native pytorch functions. A "promote_to_match" setting would be nice (seems like a sane default to me).

I've tried out setting cast_inputs. While `@torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)` does correctly cast everything to float32, `@torch.cuda.amp.custom_fwd(cast_inputs=torch.float16)` gives me the same results as above: only some of the inputs are actually cast to float16. Manually calling half() on all the inputs just after my print does work, so I don't think the issue is the extension.

**Comment by PrimeF** [comment]
I'm also getting a similar error to @blizda.

**Comment by CoinCheung** [comment]
Hi,

If I want my customer extensions to be smart to cast its inputs according to the `with autocast` statement, how could I do this please ?

**Comment by dougsouza** [comment]
In my case, the error only happens when the model has BatchNorm2d layers. I am using torch==1.9.0.

**Comment by tongchangD** [comment]
when i export pth to onnx, It appeared
```
RuntimeError: ONNX export failed: Couldn't export Python operator FusedLeakyReLUFunction
```

**Comment by pur80a** [comment]
In my case this error appeared when I had [accelerate](https://pypi.org/project/accelerate/) installed
