### ISSUE TITLE
Converting RPC model using torch.jit.script issue

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#38580]
## 🐛 Bug

After reading [Pytorch RPC tutorial](https://pytorch.org/tutorials/intermediate/rpc_tutorial.html#distributed-rnn-using-distributed-autograd-and-distributed-optimizer), I've tried to convert a simple RPC-based model using `torch.jit.script`, but faced some errors. Not sure whether https://github.com/pytorch/pytorch/issues/37136 is related

## To Reproduce

```python
# Helper functions
def get_local_rank():
    return int(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])

def init_rpc():
    world_size=2
    rank=get_local_rank()
    os.environ['MASTER_ADDR'] = '10.123.134.28'
    os.environ['MASTER_PORT'] = '21234'
    if rank == 1:
        rpc.init_rpc("rank1", rank=rank, world_size=world_size)
    else:
        rpc.init_rpc("rank0", rank=rank, world_size=world_size)

def shutdown_rpc():
    rpc.shutdown()

# Define RPC-based model with 2 modules being remote used by DistModelParallel main model
class Net1(nn.Module):
    def __init__(self):
        pass
    def forward(self, input):
        return input

class Net2(nn.Module):
    def __init__(self,):
        pass
    def forward(self, input):
        return input

class DistModelParallel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = rpc.remote("rank0", Net1)
        self.net2 = rpc.remote("rank1", Net2)
       
    def forward(self, input):
        outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, args=input)
        # outputs2_rref = rpc.rpc_async(self.net2, Net2.forward, args=(outputs1_rref))
        # return outputs2_rref
        return input

# Repro'ing the issue
init_rpc()
rank = get_local_rank()
if rank == 1:
    dmp = DistModelParallel()
    scripted_model = torch.jit.script(dmp)
    print(f'{"*"*80}\n{scripted_model.code}\n{"-"*80}')
shutdown_rpc()
```
## Expected behavior

Model should be converted to TorchScript

## Environment

```bash
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.16.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 440.82
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0
[conda] blas                      2.15                        mkl    conda-forge
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] libblas                   3.8.0                    15_mkl    conda-forge
[conda] libcblas                  3.8.0                    15_mkl    conda-forge
[conda] liblapack                 3.8.0                    15_mkl    conda-forge
[conda] liblapacke                3.8.0                    15_mkl    conda-forge
[conda] magma-cuda100             2.5.1                         1    pytorch
[conda] mkl                       2020.0                      166    conda-forge
[conda] mkl-include               2020.0                      166    conda-forge
[conda] numpy                     1.18.1           py37h95a1406_0    conda-forge
[conda] torch                     1.5.0                    pypi_0    pypi
[conda] torchvision               0.6.0                    pypi_0    pypi
```

## Additional context

Back trace is

````python
Traceback (most recent call last):
  File "model_rpc.py", line 55, in <module>
    scripted_model = torch.jit.script(model)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1261, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 305, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 361, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 279, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:
rpc_async(dst_worker_name, user_callable, args, kwargs)does not support kwargs yet:
  File "model_rpc.py", line 41
    def forward(self, input: Tensor):
        args = [input]
        fut_child = rpc.rpc_async(self.child_rref.owner(), ChildModule.forward, args=args)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        ret = fut_child.wait()
        return ret

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[18704,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

cc @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by suo** [comment]
cc @wanchaol, do you mind taking a look?

**Comment by wanchaol** [comment]
@thiagocrepaldi thanks for the report! As you noticed in the error message: `rpc_async(dst_worker_name, user_callable, args, kwargs)does not support kwargs yet`, can you try just passing `args` in instead of doing `args=args`?

TorchScript support for RPC is still experimental and we are working on making it better (e.g. support this error case)

**Comment by thiagocrepaldi** [comment]
> 
> 
> @thiagocrepaldi thanks for the report! As you noticed in the error message: `rpc_async(dst_worker_name, user_callable, args, kwargs)does not support kwargs yet`, can you try just passing `args` in instead of doing `args=args`?
> 
> TorchScript support for RPC is still experimental and we are working on making it better (e.g. support this error case)

Thanks for the repply @wanchaol. I tried replacing `outputs1_rref = rpc.rpc_async(self.net1, args=input` by `outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, input)` and got the following error:
```bash
RuntimeError: 
Tensor cannot be used as a tuple:
  File "model_rpc2.py", line 47
    def forward(self, input):
        outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, input)
                                                               ~~~~~ <--- HERE
```

Then I replace by `outputs1_rref = rpc.rpc_async(self.net1, (input)` and I got the same. I believe the first argument of this tuple should be the `self` for  `Net1.forward` method, but when I try `outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, (self.net1, input))`, I get the following error:

```bash
RuntimeError: 

forward(Tensor self, Tensor input) -> (Tensor):
Expected a value of type 'Tensor' for argument 'self' but instead found type 'RRef[PyObject]'.
Inferred 'self' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "model_rpc2.py", line 48
    def forward(self, input):
        outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, (self.net1, input))
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```
which kind of makes sense, since `Net1.forward(self, input` doesn't have type hints. However, if I try to annotate `Net1.forward` with something like:

```python
from torch import Tensor
import torch.nn as nn

class Net1(nn.Module):
    def __init__(self):
        pass

    def forward(self : nn.Module, input):
        return input
```

and run torchScript again, I get another error

```bash
RuntimeError: 
Unknown type name 'nn.Module':
  File "model_rpc2.py", line 33
    def forward(self : nn.Module, input):
                       ~~~~~~~~~ <--- HERE
        return input
'forward' is being compiled since it was called from 'DistModelParallel.forward'
  File "model_rpc2.py", line 50
    def forward(self, input):
        outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, (self.net1, input))
                                      ~~~~~~~~~ <--- HERE
```

That is odd as `nn.Module` is used to define the classes itself, but it is not accepted for type hint annotation. I have added `from __future__ import annotations` to try to workaround it, but it didnt help.

Finally and to my surprise, if I use the following code,

```python
class Net1(nn.Module):
    def __init__(self):
        pass

    def forward(self, input):
        return input

class Net2(nn.Module):
    def __init__(self,):
        pass

    def forward(self, input):
        return input

class DistModelParallel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = rpc.remote("rank0", Net1)
        self.net2 = rpc.remote("rank1", Net2)
        
    def forward(self, input):
        outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, (input, input))
        outputs1 = outputs1_rref.wait()
        outputs2_rref = rpc.rpc_async(self.net2, Net2.forward, (outputs1, outputs1))
        outputs2 = outputs2_rref.wait()
        return outputs2
```
 TorchScript succeed and printed the following code and graph

``` bash
def forward(self,
    input: Tensor) -> Tensor:
  _0 = self.net1
  _1 = (input, input)
  outputs1_rref = ops.prim.rpc_async(_0, "__torch__.forward", _1)
  outputs1 = torch.wait(outputs1_rref)
  _2 = self.net2
  _3 = (outputs1, outputs1)
  outputs2_rref = ops.prim.rpc_async(_2, "__torch__.___torch_mangle_0.forward", _3)
  return torch.wait(outputs2_rref)

graph(%self : __torch__.DistModelParallel,
      %input.1 : Tensor):
  %17 : str = prim::Constant[value="__torch__.___torch_mangle_0.forward"]() # model_rpc2.py:51:24
  %6 : str = prim::Constant[value="__torch__.forward"]() # model_rpc2.py:49:24
  %2 : RRef[PyObject] = prim::GetAttr[name="net1"](%self)
  %10 : (Tensor, Tensor) = prim::TupleConstruct(%input.1, %input.1)
  %outputs1_rref.1 : Future[Tensor] = prim::rpc_async(%2, %6, %10) # model_rpc2.py:49:24
  %outputs1.1 : Tensor = aten::wait(%outputs1_rref.1) # model_rpc2.py:50:19
  %13 : RRef[PyObject] = prim::GetAttr[name="net2"](%self)
  %21 : (Tensor, Tensor) = prim::TupleConstruct(%outputs1.1, %outputs1.1)
  %outputs2_rref.1 : Future[Tensor] = prim::rpc_async(%13, %17, %21) # model_rpc2.py:51:24
  %outputs2.1 : Tensor = aten::wait(%outputs2_rref.1) # model_rpc2.py:52:19
  return (%outputs2.1)
```

Is this last attempt the correct way to export RPC-based model using `torch.jit.script`?
If not, could you provide an example of how to achieve such RPC-based model conversion to `torch.jit.script` or guidance on how to fix this example?

**Comment by xush6528** [comment]
@thiagocrepaldi The first argument to `rpc.rpc_async(...)` should be destination worker name.

**Comment by thiagocrepaldi** [comment]
> 
> 
> @thiagocrepaldi The first argument to `rpc.rpc_async(...)` should be destination worker name.
> 
> There is a API doc to help you get familiar with RPC API. https://pytorch.org/docs/stable/rpc.html

Thanks @xush6528, I've missed the `.owner()` on the rrefs. By addint it, the output to the scxenario where input is `(input, input)` gets a `torch.owner()` node and becomes:

```python
def forward(self,
    input: Tensor) -> Tensor:
  _0 = torch.owner(self.net1)
  _1 = (input, input)
  outputs1_rref = ops.prim.rpc_async(_0, "__torch__.forward", _1)
  outputs1 = torch.wait(outputs1_rref)
  _2 = torch.owner(self.net2)
  _3 = (outputs1, outputs1)
  outputs2_rref = ops.prim.rpc_async(_2, "__torch__.___torch_mangle_0.forward", _3)
  return torch.wait(outputs2_rref)

graph(%self : __torch__.DistModelParallel,
      %input.1 : Tensor):
  %19 : str = prim::Constant[value="__torch__.___torch_mangle_0.forward"]() # model_rpc2.py:51:24
  %7 : str = prim::Constant[value="__torch__.forward"]() # model_rpc2.py:49:24
  %2 : RRef[PyObject] = prim::GetAttr[name="net1"](%self)
  %3 : int = aten::owner(%2) # model_rpc2.py:49:38
  %11 : (Tensor, Tensor) = prim::TupleConstruct(%input.1, %input.1)
  %outputs1_rref.1 : Future[Tensor] = prim::rpc_async(%3, %7, %11) # model_rpc2.py:49:24
  %outputs1.1 : Tensor = aten::wait(%outputs1_rref.1) # model_rpc2.py:50:19
  %14 : RRef[PyObject] = prim::GetAttr[name="net2"](%self)
  %15 : int = aten::owner(%14) # model_rpc2.py:51:38
  %23 : (Tensor, Tensor) = prim::TupleConstruct(%outputs1.1, %outputs1.1)
  %outputs2_rref.1 : Future[Tensor] = prim::rpc_async(%15, %19, %23) # model_rpc2.py:51:24
  %outputs2.1 : Tensor = aten::wait(%outputs2_rref.1) # model_rpc2.py:52:19
  return (%outputs2.1)
```

But the main issue is still there. Why `outputs1_rref = rpc.rpc_async(self.net1, Net1.forward, (input, input))` needs the `(input, input)` instead of just `(input)` or `(self.net1, input)` or ``(self.net1.local_value(), input)` so that the `self` from `Net1.forward(self, input)` is passed the right types. `self` is not a `Tensor`, so passing `(input, input)` should be incorrect.

I've read https://pytorch.org/docs/stable/rpc.html, but it only shows how it works for methods, not class methods (which has to deal with the `self` attribute. There might be a bug or undocumented syntax here. Any help is appreciated

**Comment by xush6528** [comment]
@thiagocrepaldi 

For the missing doc, it's tracked in https://github.com/pytorch/pytorch/issues/37459. 
You can look at the [tests](https://github.com/pytorch/pytorch/blob/2caa2f3cab6eb473abb00ea1e2682b222fbec17d/torch/testing/_internal/distributed/rpc/rpc_test.py#L378) in the [PR](https://github.com/pytorch/pytorch/pull/36619) that introduces this API as examples to learn how to use the new API at the moment. 

The implementation detail is it calls a common de-RRef [template](https://github.com/pytorch/pytorch/blob/2caa2f3cab6eb473abb00ea1e2682b222fbec17d/torch/distributed/rpc/rref_proxy.py#L4-L13) for you. 

But notice this API is for Python only. It is not torchscript-able now.

You can write your torchscripted de-RRef helper yourself. You will have to write one helper for each method because of different method signatures. This is also what we do internally at facebook.

We are exploring code-generating different torchscrip-table helpers in https://github.com/pytorch/pytorch/pull/37139. 
I believe the idea could be transferred to RRRef helper as well.

**Comment by thiagocrepaldi** [comment]
> You can write your torchscripted de-RRef helper yourself. You will have to write one helper for each method because of different method signatures. This is also what we do now. We don't have easier API as well at the moment unfortunately.

Cool, it seems #37139 would be the final solution for torchscripting RPC models, but I can certainly try writing the mentioned helper. Would you have an code snippet for it?

As a side question, given the model as described in the Issue feed `(input, input)` as input to the model, is the torchscrip graph in the previous message correct? If it is, then using `(input, input)` is a temporary workaround to torchscript a RPC model.
