### ISSUE TITLE
RuntimeError: num_gpus <= 16 INTERNAL ASSERT FAILED 

### ISSUE THREAD

**Issue by hustzxd** [pytorch/pytorch#38616]
## 🐛 Bug
I am not sure if this is a bug, or there is a problem with my environment configuration.

```bash
RuntimeError: num_gpus <= 16 INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022060824/work/c10/cuda/CUDAStream.cpp:208, please report a bug to PyTorch. Number of CUDA devices on the machine is larger than the compiled max number of gpus expected (16). Increase that and recompile.
```
## To Reproduce
```python
import torch
torch.zeros(2).cuda(0)
```
## Expected behavior
RuntimeError: num_gpus <= 16 INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022060824/work/c10/cuda/CUDAStream.cpp:208, please report a bug to PyTorch. Number of CUDA devices on the machine is larger than the compiled max number of gpus expected (16). Increase that and recompile.
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: PH402 SKU 200
GPU 1: PH402 SKU 200
GPU 2: PH402 SKU 200
GPU 3: PH402 SKU 200
GPU 4: PH402 SKU 200
GPU 5: PH402 SKU 200
GPU 6: PH402 SKU 200
GPU 7: PH402 SKU 200
GPU 8: PH402 SKU 200
GPU 9: PH402 SKU 200
GPU 10: PH402 SKU 200
GPU 11: PH402 SKU 200
GPU 12: PH402 SKU 200
GPU 13: PH402 SKU 200
GPU 14: PH402 SKU 200
GPU 15: PH402 SKU 200
GPU 16: PH402 SKU 200
GPU 17: PH402 SKU 200
GPU 18: PH402 SKU 200
GPU 19: PH402 SKU 200

Nvidia driver version: 430.09
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.4.0
[conda] _pytorch_select           0.2                       gpu_0    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.1.243             h6bb024c_0    defaults
[conda] mkl                       2020.0                      166    defaults
[conda] mkl-service               2.3.0            py37he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py37ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py37hd6b4f25_0    defaults
[conda] numpy                     1.18.1           py37h4f9e942_0    defaults
[conda] numpy-base                1.18.1           py37hde5b4d6_1    defaults
[conda] numpydoc                  0.9.2                      py_0    defaults
[conda] pytorch                   1.4.0           cuda101py37h02f0884_0    defaults

cc @ngimel

**Comment by glaringlee** [comment]
add triage review label, it seems the num_gpus need a bigger number.

**Comment by agolynski** [comment]
You seem to have 19 GPUs, have you tried setting C10_COMPILE_TIME_MAX_GPUS?

**Comment by hustzxd** [comment]
If I set a specific graphics card id, there will be no error.
`CUDA_VISIBLE_DEVICES=0` or
` CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15'`

**Comment by gchanan** [comment]
our recommendation is to recompile.  If other people run into the same issue we can consider increasing the default in the future.

**Comment by cloudhan** [comment]
> You seem to have 19 GPUs, have you tried setting C10_COMPILE_TIME_MAX_GPUS?

You count from 0, so there are 20 GPUs

**Comment by che85** [comment]
Hi, I am experiencing similar issues.

First, I got pytorch compiled from source and working with CUDA 11.8 on H100 cards and after an hour or so i started getting these errors. I have 3x H100 cards in this machine. 

After compiling pytorch again, I am still getting the errors. 

Does anyone know what's going on? 

```
(cuda11) [Downloads]$ python -c "import torch; print(torch.__version__); torch.zeros(2).cuda(0);"
2.0.0a0+git27ab1df
Traceback (most recent call last):
  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 260, in _lazy_init
    queued_call()
  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 145, in _check_capability
    capability = get_device_capability(d)
  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 388, in get_device_capability
    prop = get_device_properties(device)
  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 406, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/home/herzc/sources/pytorch/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 264, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/home/herzc/sources/pytorch/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

CUDA call was originally invoked at:

['  File "<string>", line 1, in <module>\n', '  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 843, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "/home/herzc/sources/pytorch/torch/__init__.py", line 1148, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 843, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 197, in <module>\n    _lazy_call(_check_capability)\n', '  File "/home/herzc/sources/pytorch/torch/cuda/__init__.py", line 195, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']


```

**Comment by che85** [comment]
For some reason, restarting the machine (RHEL8) seemed to have worked, but I still don't get why this happened in the first place.

**Comment by aparna-aketi** [comment]
I am having a similar issue.

Traceback (most recent call last):
  File "/home/min/a/saketi/Desktop/research/fall22/quasi_gradient_tracking/trainer.py", line 462, in <module>
    spawn(init_process, args=(size,run), nprocs=size, join=True)
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/cuda/__init__.py", line 242, in _lazy_init
    queued_call()
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/cuda/__init__.py", line 125, in _check_capability
    capability = get_device_capability(d)
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
    prop = get_device_properties(device)
  File "/home/min/a/saketi/anaconda3/envs/A40/lib/python3.9/site-packages/torch/cuda/__init__.py", line 375, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch.

**Comment by ricardorei** [comment]
Is there any solution for this? I am getting similar errors on a machine with A100's

**Comment by cmosguy** [comment]
> `export CUDA_VISIBLE_DEVICES=0` or
> `export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15'`

Setting these environment variables worked.  However, how does one know how many devices are available and what to set this to when running on remote farm jobs with varying num devices?

**Comment by kir152** [comment]
I am encountering the same error on the A100 GPUs. A temporary workaround is to restart the machine, but simply setting the `CUDA_VISIBLE_DEVICES` environment variable (e.g., `export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7'`) does not resolve the issue. 

Is there a more robust solution that prevents the need for restarting the machine each time this error occurs? Any guidance would be much appreciated.

**Comment by BramVanroy** [comment]
I am experieicning this on our cluster as well on a bunch of A100 40GBs. Interestingly, the exact same deterministic install on A100 80GBs does work.

CUDA11.7 and torch 2.0.1.

**Comment by cmosguy** [comment]
@BramVanroy  the issue is I do not have rights to restart the server, so are there any ideas about root cause how and how to resolve this issue?

**Comment by cmosguy** [comment]
You know what, I found out I had the following:

```env | grep CUDA
CUDA_VISIBLE_DEVICES=0,1,2,3
CUDA_VISIBLE_DEVICES1=MIG-GPU-2a18fccc-9496-464d-d204-4394c26b56d6/13/0```

So I did the following:
```
unset CUDA_VISIBLE_DEVICES1
export CUDA_VISIBLE_DEVICES=0
```
and then it started working.  Does anyone know what this is the case?

**Comment by dydxdt** [comment]
> ```dotenv
> CUDA_VISIBLE_DEVICES1
> ```
what's the CUDA_VISIBLE_DEVICES1 parameter mean? I also can't restart the a100 machine and get caught in this error.

**Comment by alexshmmy** [comment]
Same problem here. I have access to a cluster with a bunch of A100 GPUs. When I allocate one GPU, the following simple code executes properly:

```python
import torch

print(f"Pytorch version: {torch.__version__}")
print(f"Is CUDA available?: {torch.cuda.is_available()}")
print(f"Number of CUDA devices: {torch.cuda.device_count()}")
device = torch.device('cuda')
print(f"A torch tensor: {torch.rand(5).to(device)}")
```

Output:

```
Pytorch version: 2.0.1+cu117
Is CUDA available?: True
Number of CUDA devices: 1
A torch tensor: tensor([0.3157, 0.8026, 0.1049, 0.2574, 0.2896], device='cuda:0')
```

When for exactlyt he same code I allocate two A100 GPUs, I get as output:

```
Pytorch version: 2.0.1+cu117
Is CUDA available?: True
Number of CUDA devices: 2

RuntimeError device >= 0 && device < num_gpus INTERNAL ASSERT FAILED
```

I tried the solution suggested `export CUDA_VISIBLE_DEVICES=0,1` or to compile it as `CUDA_VISIBLE_DEVICES=0,1 python script.py`, but does not work for me. Any ideas how to proceed for here? I need the second GPU to proceed with a LLM that does not fit in one GPU.

**Comment by cmosguy** [comment]
@alexshmmy  - I resolved my problem by not setting the devices variable when I submitted to the cluster.  We use IBM LSF to submit jobs to the GPU farm and what I found out was you have to let the job create the `CUDA_VISIBLE_DEVICES` variables and then things just started to work for me.

**Comment by zhanwenchen** [comment]
Sometimes this is a problem with the batch size being too big (so OOM but wrong error message).

**Comment by youkaichao** [comment]
Here is my error:

```text
CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

CUDA call was originally invoked at:

  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/ray/_private/workers/default_worker.py", line 282, in <module>
    worker.main_loop()
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/ray/_private/worker.py", line 847, in main_loop
    self.core_worker.run_task_loop()
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/ray/_private/function_manager.py", line 574, in load_actor_class
    actor_class = self._load_actor_class_from_gcs(
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/ray/_private/function_manager.py", line 677, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gcpuser/vllm/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gcpuser/vllm/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, DeviceConfig, ModelConfig,
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gcpuser/vllm/vllm/config.py", line 7, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/torch/__init__.py", line 1431, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in <module>
    _lazy_call(_check_capability)
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/torch/cuda/__init__.py", line 244, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
```

My error lives inside `ray`. Not sure what can I do.

However, I can run the following script correctly:

```python
import torch
torch.cuda.set_device(0)
torch.cuda.set_device(1)
x = torch.zeros(10000, 100000).cuda(1)
x = torch.zeros(10000, 100000).cuda(0)
```

**Comment by youkaichao** [comment]
Looking at my error message with care, I actually find something abnormal:

```text
CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus 
INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, 
please report a bug to PyTorch. device=1, num_gpus=�
```

Also took a look at how this message is constructed:

https://github.com/pytorch/pytorch/blob/c568b84794447b023747cd5a1bf47288fc657b77/aten/src/ATen/cuda/CUDAContext.cpp#L47-L53

And the definition of the macro `AT_ASSERT`:

https://github.com/pytorch/pytorch/blob/c568b84794447b023747cd5a1bf47288fc657b77/c10/util/Exception.h#L677-L686

I think the problem should be that cuda context is either not initialized (`num_gpus = -1`) or initialized incorrectly (where `num_gpus` can be any negative number).

That being said, I suppose this is a driver issue, and maybe I should switch to another machine :)

**Comment by tjasmin111** [comment]
I'm getting the same error. Outputs of PyTorch looks good though. What is the problem? How to fix it?

`RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=`

Some pytorch outputs:
```
Python 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:34) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.zeros(2).cuda(0)
tensor([0., 0.], device='cuda:0')
>>> print(torch.__version__)
2.3.0+cu118
>>> print(f"Is CUDA available?: {torch.cuda.is_available()}")
Is CUDA available?: True
>>> print(f"Number of CUDA devices: {torch.cuda.device_count()}")
Number of CUDA devices: 3
>>> device = torch.device('cuda')
>>> print(f"A torch tensor: {torch.rand(5).to(device)}")
A torch tensor: tensor([0.6085, 0.7618, 0.6855, 0.5276, 0.1606], device='cuda:0')
```

Full stack trace:

```
Traceback (most recent call last):
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 306, in _lazy_init
    queued_call()
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 174, in _check_capability
    capability = get_device_capability(d)
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 448, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/conda/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 583, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/conda/lib/python3.9/site-packages/ultralytics/engine/model.py", line 528, in val
    validator(model=self.model)
  File "/home/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/conda/lib/python3.9/site-packages/ultralytics/engine/validator.py", line 126, in __call__
    device=select_device(self.args.device, self.args.batch),
  File "/home/conda/lib/python3.9/site-packages/ultralytics/utils/torch_utils.py", line 156, in select_device
    p = torch.cuda.get_device_properties(i)
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 444, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 312, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

  File "/home/conda/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/conda/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/conda/lib/python3.9/site-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/conda/lib/python3.9/site-packages/ultralytics/data/base.py", line 15, in <module>
    from torch.utils.data import Dataset
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/conda/lib/python3.9/site-packages/torch/__init__.py", line 1478, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 238, in <module>
    _lazy_call(_check_capability)
  File "/home/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 235, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
```
