### ISSUE TITLE
Providing CUDA tensor to model on CPU causes a crash

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [pytorch/pytorch#38623]
## 🐛 Bug

Pytorch crashes Google colab session when calling a LSTM model running on CPU (located in RAM) on input located in GPU VRAM.

NOTE: This doesn't happen with Linear model.

## To Reproduce

Colab notebook https://colab.research.google.com/drive/1ojp92wmp_Rh_NWMLbQJEeXmDdTL-TSkE?usp=sharing

1. Create a LSTM model running on CPU
2. Create input on GPU
3. Call the model on the input.

Code:
```
import torch
from torch import nn

def testing():
    d_batch = 4
    d_input = 100
    d_hidden = 100
    num_layers = 1
    d_max_seq_len = 1

    m = nn.LSTM(d_input, d_hidden, num_layers=num_layers, dropout=0, batch_first=True)

    device = torch.device('cuda:0')
    enc_phrases = torch.randn(d_batch, d_max_seq_len, d_input, device=device)
    results = m(enc_phrases)

testing()
```

Error:
![pytorch_bug](https://user-images.githubusercontent.com/20921177/82142799-a328e180-985c-11ea-96da-c005ca8bc542.png)
![pytorch_bug_logs](https://user-images.githubusercontent.com/20921177/82142801-a754ff00-985c-11ea-9eff-d4ac9eeb82e2.png)

Colab crash logs https://bpa.st/3VRQ

## Expected behavior

I would expect it to print a traceback and warn the user instead of crashing the entire session.
This sort of errors are caught when the model is running on GPU and the input is not on GPU VRAM.

Code:
```
import torch
from torch import nn

def testing():
    d_batch = 4
    d_input = 100
    d_hidden = 100
    num_layers = 1
    d_max_seq_len = 1

    m = nn.Linear(d_input, d_hidden)

    device = torch.device('cuda:0')
    enc_phrases = torch.randn(d_batch, d_input, device=device)
    results = m(enc_phrases)

testing()
```

Error:
```
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat2' in call to _th_mm
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.0+cu101
[conda] Could not collect

 - PyTorch Version (e.g., 1.0): 1.5.0+cu101
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): Colab
 - Build command you used (if compiling from source): Colab has pytorch preinstalled
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1.243
 - GPU models and configuration: GPU 0: Tesla K80
 - Any other relevant information:

## Additional context

This sort of error is very annoying to debug. I tried https://docs.python.org/3/library/faulthandler.html and it still didn't catch it. Sometimes in large projects to forget to move your
model to GPU, etc. It took me a long time (8 hours+) to find out what the issue was. Please fix this as soon as possible. Any sort of error or tracebacks if FAAAAAAAAAAAAAAAAR more useful than crashing the Google colab/Jupyter session.

**Comment by agolynski** [comment]
Thanks for reporting this and thanks @albanD for helping to triage this!

**Comment by HarikrishnanBalagopal** [comment]
This is off-topic but since I have your attention, is there something pytorch can do about CUDA memory error reports? I hate GPU memory math:

```
RuntimeError: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 0; 14.73 GiB total capacity; 13.68 GiB already allocated; 29.88 MiB free; 13.99 GiB reserved in total by PyTorch)
```
13.99 GiB reserved - 13.68 GiB already allocated = around 300 MB worst case
but it says 29.88 MiB free
ALSO it failed to allocate 28.00 MiB even though 29.88 MiB is free.

WTF? who wrote the code that does these calculations? That math doesn't add up.
It also gives no indication about how much memory is actually available for use.

Even worse, after it fails one time because of a large batch size (Ex: 512), it will then start failing even for very small batch sizes (Ex: 4) that were previously working fine. The only solution seems to be to restart the system.

Note: The CUDA out of memory error I pasted is from a Google Cloud deep learning instance with CUDA 10, a Nvidia Tesla T4 GPU with 15079 MiB VRAM and 13 GB RAM running Debian 9 `Linux newf3-vm 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux` and pytorch version '1.4.0'

**Comment by albanD** [comment]
@HarikrishnanBalagopal I don't think this is relevant for this issue.
Please feel free to contribute your constructive ideas to improve the message in  https://github.com/pytorch/pytorch/issues/32101.
For recovery for OOM errors, this is not all in our control unfortunately, you can find a lengthy discussion about this in the issue that discuss this exact topic: https://github.com/pytorch/pytorch/issues/18853.

**Comment by peterbell10** [comment]
This issue doesn't reproduce locally for me. I tried running from a normal python script and a jupyter notebook. Both give a `RuntimeError`:
```
RuntimeError: Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
```

On google colab, I was able to reproduce under `cuda-gdb` which gives this backtrace:
```
#0  0x00007f3bb6d0da22 in _Ux86_64_getcontext ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#1  0x00007f3bb6d0ff94 in _ULx86_64_dwarf_search_unwind_table ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#2  0x00007f3bb6d101b3 in _ULx86_64_dwarf_search_unwind_table ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#3  0x00007f3bb6d0e15d in _Ux86_64_getcontext ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#4  0x00007f3bb6d0f3f1 in _Ux86_64_getcontext ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#5  0x00007f3bb6d0fa99 in _Ux86_64_getcontext ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#6  0x00007f3bb6d0be71 in _ULx86_64_step ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#7  0x00007f3bb6d0abd5 in __libunwind_Unwind_Resume ()
   from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#8  0x00007f3b6e47bf00 in at::native::_cudnn_rnn(at::Tensor const&, c10::ArrayRef<at::Tensor>, long, at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, long, bool, double, bool, bool, c10::ArrayRef<long>, at::Tensor const&) () from /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so
```

So, it seems to actually be trying to raise the error but `libunwind` is crashing. Presumable when the stack trace is being generated for `c10::Error`.

**Comment by ezyang** [comment]
Hmm, does this mean we should just disable backtrace generation on colab? Not sure how to test for this.

**Comment by mruberry** [comment]
Lowering priority since fix is unclear.
