### ISSUE TITLE
[CI] TestNCCL

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#38649]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28162/console

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28170/console

```
05:55:46 ----------------------------------------------------------------------
05:55:46 Ran 32 tests in 0.002s
05:55:46 
05:55:46 OK (skipped=32)
05:55:46 Running distributed/test_nccl ... [2020-05-18 05:55:46.565481]
05:55:49 test_all_gather (__main__.TestNCCL) ... ok
05:56:08 test_all_reduce (__main__.TestNCCL) ... ok
05:56:08 test_broadcast (__main__.TestNCCL) ... FAIL
05:56:08 test_reduce (__main__.TestNCCL) ... FAIL
05:56:08 test_reduce_scatter (__main__.TestNCCL) ... FAIL
05:56:08 test_unique_id (__main__.TestNCCL) ... ok
05:56:08 
05:56:08 ======================================================================
05:56:08 FAIL: test_broadcast (__main__.TestNCCL)
05:56:08 ----------------------------------------------------------------------
05:56:08 Traceback (most recent call last):
05:56:08   File "distributed/test_nccl.py", line 39, in test_broadcast
05:56:08     self.assertEqual(tensors[i], expected)
05:56:08   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1083, in assertEqual
05:56:08     self.assertTrue(result, msg=message)
05:56:08 AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 128 element(s) (out of 128) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.648508608341217 (3.0674540996551514 vs. 0.4189454913139343), which occurred at index 46.
05:56:08 
05:56:08 ======================================================================
05:56:08 FAIL: test_reduce (__main__.TestNCCL)
05:56:08 ----------------------------------------------------------------------
05:56:08 Traceback (most recent call last):
05:56:08   File "distributed/test_nccl.py", line 52, in test_reduce
05:56:08     self.assertEqual(tensors[0], expected)
05:56:08   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1083, in assertEqual
05:56:08     self.assertTrue(result, msg=message)
05:56:08 AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 128 element(s) (out of 128) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.811781644821167 (6.046049118041992 vs. 3.234267473220825), which occurred at index 114.
05:56:08 
05:56:08 ======================================================================
05:56:08 FAIL: test_reduce_scatter (__main__.TestNCCL)
05:56:08 ----------------------------------------------------------------------
05:56:08 Traceback (most recent call last):
05:56:08   File "distributed/test_nccl.py", line 100, in test_reduce_scatter
05:56:08     self.assertEqual(outputs[i], expected[i])
05:56:08   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1083, in assertEqual
05:56:08     self.assertTrue(result, msg=message)
05:56:08 AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 32 element(s) (out of 32) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 4.589726448059082 (7.646427154541016 vs. 3.0567007064819336), which occurred at index 23.
05:56:08 
05:56:08 ----------------------------------------------------------------------
```

**Comment by kshitij12345** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28436/console

**Comment by kshitij12345** [comment]
Closing in favour of #38833 #38834 #38835
