### ISSUE TITLE
Implement torch.erf for complex dtypes

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#38650]
```
>>> torch.erf(torch.tensor([2j, -3.5, 4j]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: erf_vml_cpu not implemented for 'ComplexFloat'
>>> torch.erf(torch.tensor([2j, -3.5, 4j]).cuda())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "erf_cuda" not implemented for 'ComplexFloat'
>>> import numpy as np
>>> import scipy.special
>>> scipy.special.erf(np.array([2j, -3.5, 4j]))
array([ 0.        +1.85648024e+01j, -0.99999926+0.00000000e+00j,
        0.        +1.29695973e+06j])
>>>
```

**Comment by redsnic** [comment]
I have written a tiny module to implement the ERF for complex numbers in torch. 

https://github.com/redsnic/torch_erf

It follows the algorithm described in:

Weideman, J. Andre C. "Computation of the complex error function." SIAM Journal on Numerical Analysis 31.5 (1994): 1497-1518

You can find some comparisons with the more sophisticated scipy implementation in the man folder.
