### ISSUE TITLE
DISABLED test_remote_script_module (__main__.JitRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38722]
https://app.circleci.com/pipelines/github/pytorch/pytorch/171687/workflows/704f208c-d74a-4fa0-9579-334819e55a40/jobs/5520032/steps

```
May 19 05:26:19 ======================================================================
May 19 05:26:19 ERROR [1.121s]: test_remote_script_module (__main__.JitRpcTestWithSpawn)
May 19 05:26:19 ----------------------------------------------------------------------
May 19 05:26:19 Traceback (most recent call last):
May 19 05:26:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
May 19 05:26:19     self._join_processes(fn)
May 19 05:26:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
May 19 05:26:19     self._check_return_codes(elapsed_time)
May 19 05:26:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
May 19 05:26:19     raise RuntimeError(error)
May 19 05:26:19 RuntimeError: Processes 2 exited with error code 10
```

```
May 19 05:25:59   test_remote_script_module (__main__.JitRpcTestWithSpawn) ... [E request_callback_impl.cpp:96] Received error while processing request type 0: 
May 19 05:25:59 Unknown type name '__torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface':
May 19 05:25:59 __torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface
May 19 05:25:59 ERROR:root:Caught exception: 
May 19 05:25:59 Traceback (most recent call last):
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
May 19 05:25:59     fn()
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 85, in new_test_method
May 19 05:25:59     return_value = old_test_method(self, *arg, **kwargs)
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 889, in test_remote_script_module
May 19 05:25:59     args=(remote_ref, torch.ones(self.rank)),
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
May 19 05:25:59     return func(*args, **kwargs)
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 614, in rpc_sync
May 19 05:25:59     return fut.wait()
May 19 05:25:59 RuntimeError: Error on Node 3: 
May 19 05:25:59 Unknown type name '__torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface':
May 19 05:25:59 __torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface
May 19 05:25:59 exiting process with exit code: 10
May 19 05:25:59 [E request_callback_impl.cpp:96] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
May 19 05:25:59 Traceback of TorchScript (most recent call last):
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 799, in run_ref_script_module
May 19 05:25:59 def run_ref_script_module(ref_script_module, t):
May 19 05:25:59     # type: (RRef[MyModuleInterface], Tensor) -> Tensor
May 19 05:25:59     module = ref_script_module.to_here()
May 19 05:25:59              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
May 19 05:25:59     return module.forward() + t
May 19 05:25:59 RuntimeError: User RRef with RRefId=GloballyUniqueId(1, 0) and ForkId=GloballyUniqueId(1, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker2, to user, worker1.
May 19 05:25:59 
May 19 05:25:59 [E request_callback_impl.cpp:96] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
May 19 05:25:59 Traceback of TorchScript (most recent call last):
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 799, in run_ref_script_module
May 19 05:25:59 def run_ref_script_module(ref_script_module, t):
May 19 05:25:59     # type: (RRef[MyModuleInterface], Tensor) -> Tensor
May 19 05:25:59     module = ref_script_module.to_here()
May 19 05:25:59              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
May 19 05:25:59     return module.forward() + t
May 19 05:25:59 RuntimeError: User RRef with RRefId=GloballyUniqueId(0, 0) and ForkId=GloballyUniqueId(0, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker1, to user, worker0.
May 19 05:25:59 
May 19 05:25:59 [E request_callback_impl.cpp:96] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
May 19 05:25:59 Traceback of TorchScript (most recent call last):
May 19 05:25:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 799, in run_ref_script_module
May 19 05:25:59 def run_ref_script_module(ref_script_module, t):
May 19 05:25:59     # type: (RRef[MyModuleInterface], Tensor) -> Tensor
May 19 05:25:59     module = ref_script_module.to_here()
May 19 05:25:59              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
May 19 05:25:59     return module.forward() + t
May 19 05:25:59 RuntimeError: User RRef with RRefId=GloballyUniqueId(3, 0) and ForkId=GloballyUniqueId(3, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker0, to user, worker3.
May 19 05:25:59 
May 19 05:25:59 Process 2 terminated with exit code 10, terminating remaining processes.
May 19 05:25:59 ERROR (1.121s)
May 19 05:26:00   test_remote_script_throw (__main__.JitRpcTestWithSpawn) ... [E request_callback_impl.cpp:96] Received error while processing request type 7: The following operation failed in the TorchScript interpreter.
May 19 05:26:00 Traceback of TorchScript (most recent call last):
May 19 05:26:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 136, in script_raise_func
May 19 05:26:00 def script_raise_func(value):
May 19 05:26:00     if value.numel() == 2:
May 19 05:26:00         raise ValueError("Expected error")
May 19 05:26:00         ~~~~~~~~~~~~~~~~~~ <--- HERE
May 19 05:26:00     return value + 1
May 19 05:26:00 RuntimeError: Exception
```

cc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by pritamdamania87** [comment]
Haven't been able to repro this locally. Closing this issue out to see if this is resolved in master already.
