### ISSUE TITLE
DISABLED test_rref_proxy_reuse (__main__.TensorPipeAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38756]
https://app.circleci.com/pipelines/github/pytorch/pytorch/171962/workflows/ae1c1fcb-e266-41d7-9219-f5ea466bd250/jobs/5529141/steps

```
May 20 01:25:50 ======================================================================
May 20 01:25:50 FAIL [2.023s]: test_rref_proxy_reuse (__main__.TensorPipeAgentRpcTestWithSpawn)
May 20 01:25:50 ----------------------------------------------------------------------
May 20 01:25:50 Traceback (most recent call last):
May 20 01:25:50   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
May 20 01:25:50     self._join_processes(fn)
May 20 01:25:50   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
May 20 01:25:50     self._check_return_codes(elapsed_time)
May 20 01:25:50   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 349, in _check_return_codes
May 20 01:25:50     i, first_process.exitcode, p.exitcode
May 20 01:25:50   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1116, in assertEqual
May 20 01:25:50     self.assertTrue(result, msg=message)
May 20 01:25:50 AssertionError: False is not true : Expect process 1 exit code to match Process 0 exit code of -6, but got 0
```

```
May 20 01:25:08   test_rref_proxy_reuse (__main__.TensorPipeAgentRpcTestWithSpawn) ... [W tensorpipe_agent.cpp:222] RPC agent is being closed. Skip sending rpc response
May 20 01:25:08 [W tensorpipe_agent.cpp:383] Read response error: EOF: end of file
May 20 01:25:08 terminate called after throwing an instance of '[W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:25:08 std::runtime_error'
May 20 01:25:08   what():  EOF: end of file
May 20 01:25:08 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:25:08 FAIL (2.023s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
All tests should now be fixed as part of the stack ending in #39441.
