### ISSUE TITLE
DISABLED test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38755]
https://app.circleci.com/pipelines/github/pytorch/pytorch/171962/workflows/ae1c1fcb-e266-41d7-9219-f5ea466bd250/jobs/5529195/steps

```
May 20 01:23:21 ======================================================================
May 20 01:23:21 ERROR [100.083s]: test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)
May 20 01:23:21 ----------------------------------------------------------------------
May 20 01:23:21 Traceback (most recent call last):
May 20 01:23:21   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
May 20 01:23:21     self._join_processes(fn)
May 20 01:23:21   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
May 20 01:23:21     self._check_return_codes(elapsed_time)
May 20 01:23:21   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 344, in _check_return_codes
May 20 01:23:21     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
May 20 01:23:21 RuntimeError: Process 2 terminated or timed out after 100.06697463989258 seconds
```

```
May 20 01:18:27 [W tensorpipe_agent.cpp:222] RPC agent is being closed. Skip sending rpc response
May 20 01:18:27 [E request_callback_impl.cpp:96] Received error while processing request type 19: currentRpcAgent_ INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/distributed/rpc/rpc_agent.cpp":246, please report a bug to PyTorch. Current RPC agent is not set!
May 20 01:18:27 Exception raised from getCurrentRpcAgent at /var/lib/jenkins/workspace/torch/csrc/distributed/rpc/rpc_agent.cpp:246 (most recent call first):
May 20 01:18:27 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fa961e71f79 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
May 20 01:18:27 frame #1: torch::distributed::rpc::RpcAgent::getCurrentRpcAgent() + 0x3f4 (0x7fa95cc85974 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:18:27 frame #2: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0x64 (0x7fa95cc78f04 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:18:27 frame #3: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x5f (0x7fa95ccbddcf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:18:27 frame #4: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0xfa (0x7fa962e71bca in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
May 20 01:18:27 frame #5: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x1e (0x7fa95cc84e6e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:18:27 frame #6: <unknown function> + 0xa64c13 (0x7fa962e7bc13 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
May 20 01:18:27 frame #7: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7fa961e5f90b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
May 20 01:18:27 frame #8: <unknown function> + 0xc8421 (0x7fa96236b421 in /opt/conda/lib/libstdc++.so.6)
May 20 01:18:27 frame #9: <unknown function> + 0x76ba (0x7fa96b30a6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
May 20 01:18:27 frame #10: clone + 0x6d (0x7fa96b04041d in /lib/x86_64-linux-gnu/libc.so.6)
May 20 01:18:27 
May 20 01:18:27 [W tensorpipe_agent.cpp:222] RPC agent is being closed. Skip sending rpc response
May 20 01:18:27 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:27 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:27 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:27 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:27 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:27 ok (1.720s)
May 20 01:18:28   test_backward_multiple_round_trips (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:28 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:28 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:28 ok (1.220s)
May 20 01:18:29   test_backward_no_grad_on_tensor (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:29 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:29 [W tensorpipe_agent.cpp:258] Server read message: EOF: end of file
May 20 01:18:29 ok (1.218s)
May 20 01:20:09   test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... Timing out after 100 seconds and killing subprocesses.
May 20 01:20:09 ERROR (100.083s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
All tests should now be fixed as part of the stack ending in #39441.
