### ISSUE TITLE
test_float_to_int_conversion_finite_cpu_int16 is failing on MacOS

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#38752]
```
May 19 08:56:50 ======================================================================
May 19 08:56:50 FAIL [0.003s]: test_float_to_int_conversion_finite_cpu_int16 (__main__.TestTorchDeviceTypeCPU)
May 19 08:56:50 ----------------------------------------------------------------------
May 19 08:56:50 Traceback (most recent call last):
May 19 08:56:50   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 234, in instantiated_test
May 19 08:56:50     result = test(self, device_arg, dtype)
May 19 08:56:50   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 501, in only_fn
May 19 08:56:50     return fn(self, device, *args, **kwargs)
May 19 08:56:50   File "test_torch.py", line 16627, in test_float_to_int_conversion_finite
May 19 08:56:50     self._float_to_int_conversion_helper(vals, device, dtype)
May 19 08:56:50   File "test_torch.py", line 16603, in _float_to_int_conversion_helper
May 19 08:56:50     self.assertEqual(torch.from_numpy(a), t.cpu())
May 19 08:56:50   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1083, in assertEqual
May 19 08:56:50     self.assertTrue(result, msg=message)
May 19 08:56:50 AssertionError: False is not true : Tensors failed to compare as equal! Found 1 different element(s) (out of 9), with the greatest difference of 32768 (-32768 vs. 0) occuring at index 0.
May 19 08:56:50 
May 19 08:56:50 ----------------------------------------------------------------------
```

This issue first appears on Master after this PR https://github.com/pytorch/pytorch/pull/38641, which seems unrelated. 

I am disabling the test.

cc @ezyang @gchanan @zou3519 @mruberry

**Comment by ezyang** [comment]
Between the first failing master run and the previous successful run, I observe a difference in numpy version

```
May [-19 07:57:17-]{+18 23:27:45+}     numpy-base-1.18.1          |   [-py37hc72aeb7_1-]{+py37ha711998_1+}         3.9 MB
```

Same version, but py37hc72aeb7_1 versus py37ha711998_1

**Comment by kshitij12345** [comment]
https://dr.pytorch.org/api/view-log-full?build_id=116733106

**Comment by ptrblck** [comment]
Might be related to https://github.com/numpy/numpy/issues/19881 and/or https://github.com/numpy/numpy/issues/16073
