### ISSUE TITLE
DISABLED test_trainer_ps (__main__.TensorPipeAgentDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38758]
https://app.circleci.com/pipelines/github/pytorch/pytorch/171959/workflows/3211d854-a984-469e-8984-602211e6a3d6/jobs/5528985/steps

```
May 20 01:54:09 ======================================================================
May 20 01:54:09 FAIL [1.415s]: test_trainer_ps (__main__.TensorPipeAgentDistAutogradTestWithSpawn)
May 20 01:54:09 ----------------------------------------------------------------------
May 20 01:54:09 Traceback (most recent call last):
May 20 01:54:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
May 20 01:54:09     self._join_processes(fn)
May 20 01:54:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
May 20 01:54:09     self._check_return_codes(elapsed_time)
May 20 01:54:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 349, in _check_return_codes
May 20 01:54:09     i, first_process.exitcode, p.exitcode
May 20 01:54:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1116, in assertEqual
May 20 01:54:09     self.assertTrue(result, msg=message)
May 20 01:54:09 AssertionError: False is not true : Expect process 3 exit code to match Process 0 exit code of 0, but got -6
```

```
May 20 01:54:04   test_trainer_ps (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:222] RPC agent is being closed. Skip sending rpc response
May 20 01:54:04 [E request_callback_impl.cpp:96] Received error while processing request type 19: currentRpcAgent_ INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/distributed/rpc/rpc_agent.cpp":246, please report a bug to PyTorch. Current RPC agent is not set!
May 20 01:54:04 Exception raised from getCurrentRpcAgent at /var/lib/jenkins/workspace/torch/csrc/distributed/rpc/rpc_agent.cpp:246 (most recent call first):
May 20 01:54:04 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f9ba771714b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
May 20 01:54:04 frame #1: torch::distributed::rpc::RpcAgent::getCurrentRpcAgent() + 0x404 (0x7f9bb4e89f44 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #2: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0x64 (0x7f9bb4e7c494 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #3: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x5f (0x7f9bb4ec60cf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #4: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0xf8 (0x7f9bbadab518 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
May 20 01:54:04 frame #5: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x1e (0x7f9bb4e88bfe in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #6: <unknown function> + 0xb80a65 (0x7f9bbadb4a65 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
May 20 01:54:04 frame #7: c10::ThreadPool::main_loop(unsigned long) + 0x2b3 (0x7f9ba7704f93 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
May 20 01:54:04 frame #8: <unknown function> + 0xc819d (0x7f9bbc40419d in /opt/conda/lib/libstdc++.so.6)
May 20 01:54:04 frame #9: <unknown function> + 0x76ba (0x7f9be64266ba in /lib/x86_64-linux-gnu/libpthread.so.0)
May 20 01:54:04 frame #10: clone + 0x6d (0x7f9be615c41d in /lib/x86_64-linux-gnu/libc.so.6)
May 20 01:54:04 
May 20 01:54:04 [E request_callback_impl.cpp:96] Received error while processing request type 19: currentRpcAgent_ INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/distributed/rpc/rpc_agent.cpp":246, please report a bug to PyTorch. Current RPC agent is not set!
May 20 01:54:04 Exception raised from getCurrentRpcAgent at /var/lib/jenkins/workspace/torch/csrc/distributed/rpc/rpc_agent.cpp:246 (most recent call first):
May 20 01:54:04 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f878b3da14b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
May 20 01:54:04 frame #1: torch::distributed::rpc::RpcAgent::getCurrentRpcAgent() + 0x404 (0x7f8798b4cf44 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #2: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0x64 (0x7f8798b3f494 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #3: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x5f (0x7f8798b890cf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #4: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0xf8 (0x7f879ea6e518 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
May 20 01:54:04 frame #5: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x1e (0x7f8798b4bbfe in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
May 20 01:54:04 frame #6: <unknown function> + 0xb80a65 (0x7f879ea77a65 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
May 20 01:54:04 frame #7: c10::ThreadPool::main_loop(unsigned long) + 0x2b3 (0x7f878b3c7f93 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
May 20 01:54:04 frame #8: <unknown function> + 0xc819d (0x7f87a00c719d in /opt/conda/lib/libstdc++.so.6)
May 20 01:54:04 frame #9: <unknown function> + 0x76ba (0x7f87ca0e96ba in /lib/x86_64-linux-gnu/libpthread.so.0)
May 20 01:54:04 frame #10: clone + 0x6d (0x7f87c9e1f41d in /lib/x86_64-linux-gnu/libc.so.6)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
All tests should now be fixed as part of the stack ending in #39441.
