### ISSUE TITLE
libtorch 1.5.0 build from source failed on Cent OS 7

### ISSUE THREAD

**Issue by lanking520** [pytorch/pytorch#38763]
## 🐛 Bug

I tried to build with my custom C++ application with Cent OS 7 and it failed. Then I tried to build from source with pytorch 1.5.0 and it crashed in a different place.

Since the website claim Cent OS 7 is supported with GLIbc version > 2.17, how I can use it on Cent OS 7?

## To Reproduce

```
# download https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.5.0%2Bcpu.zip
# My custom cmake follow the guideline
```

error messaage
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building torch with the host...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found torch: /home/centos/pytorch/pytorch-native/libtorch/lib/libtorch.so
-- Found JNI: /usr/lib/jvm/jre/lib/amd64/libjawt.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/centos/pytorch/build

In file included from /home/centos/pytorch/pytorch-native/libtorch/include/c10/util/typeid.h:22:0,
                 from /home/centos/pytorch/pytorch-native/src/pytorch_jni_utils.h:16,
                 from /home/centos/pytorch/pytorch-native/src/ai_pytorch_jni_PyTorchLibrary_nn_functional.cc:15:
/home/centos/pytorch/pytorch-native/libtorch/include/c10/util/C++17.h:16:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
 #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
  ^
/home/centos/pytorch/pytorch-native/libtorch/include/c10/util/C++17.h:24:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
  ^
In file included from /home/centos/djl/pytorch/pytorch-native/libtorch/include/c10/util/ArrayRef.h:19:0,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/c10/core/MemoryFormat.h:5,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/ATen/core/TensorBody.h:5,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/ATen/Tensor.h:11,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/ATen/Context.h:4,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/ATen/ATen.h:5,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/centos/djl/pytorch/pytorch-native/libtorch/include/torch/script.h:3,
                 from /home/centos/djl/pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc:13:
/home/centos/djl/pytorch/pytorch-native/libtorch/include/c10/util/C++17.h:16:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
 #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
  ^
/home/centos/djl/pytorch/pytorch-native/libtorch/include/c10/util/C++17.h:24:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
  ^
In file included from /home/centos/djl/pytorch/pytorch-native/libtorch/include/c10/util/typeid.h:22:0,
                 from /home/centos/djl/pytorch/pytorch-native/src/djl_pytorch_jni_utils.h:16,
                 from /home/centos/djl/pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_isjm.cc:15:
/home/centos/djl/pytorch/pytorch-native/libtorch/include/c10/util/C++17.h:16:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
```

After this, build from source

```
# checkout tags/v1.5.0
mkdir build && cd build
python3 ../tools/build_libtorch.py
```

Error message
```
cmake -DBUILD_PYTHON=False -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/cmake -DCMAKE_INSTALL_PREFIX=/home/centos/pytorch/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3.6/site-packages -DNUMPY_INCLUDE_DIR=/home/centos/.local/lib/python3.6/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DUSE_NUMPY=True /home/centos/pytorch
-- The CXX compiler identification is unknown
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/cmake
-- Check for working CXX compiler: /usr/bin/cmake -- broken
CMake Error at /usr/local/share/cmake-3.6/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/bin/cmake" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeTmp



  Run Build Command:"/usr/bin/gmake" "cmTC_53171/fast"

  /usr/bin/gmake -f CMakeFiles/cmTC_53171.dir/build.make
  CMakeFiles/cmTC_53171.dir/build

  gmake[1]: Entering directory
  `/home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeTmp'

  Building CXX object CMakeFiles/cmTC_53171.dir/testCXXCompiler.cxx.o

  /usr/bin/cmake -o CMakeFiles/cmTC_53171.dir/testCXXCompiler.cxx.o -c
  /home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx


  CMake Error: The source directory
  "/home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx"
  is a file, not a directory.

  Specify --help for usage, or press the help button on the CMake GUI.

  gmake[1]: *** [CMakeFiles/cmTC_53171.dir/testCXXCompiler.cxx.o] Error 1

  gmake[1]: Leaving directory
  `/home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeTmp'

  gmake: *** [cmTC_53171/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:23 (project)


-- Configuring incomplete, errors occurred!
See also "/home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/centos/pytorch/build_libtorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 23, in <module>
    rerun_cmake=True, cmake_only=False, cmake=CMake())
  File "/home/centos/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/home/centos/pytorch/tools/setup_helpers/cmake.py", line 323, in generate
    self.run(args, env=my_env)
  File "/home/centos/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON=False', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_COMPILER=/usr/bin/cmake', '-DCMAKE_INSTALL_PREFIX=/home/centos/pytorch/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python3.6/site-packages', '-DNUMPY_INCLUDE_DIR=/home/centos/.local/lib/python3.6/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DUSE_NUMPY=True', '/home/centos/pytorch']' returned non-zero exit status 1.
```

## Environment

Collecting environment information...
Is debug build: No

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 3.6.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

cc @malfet @yf225 @glaringlee

**Comment by malfet** [comment]
Please update the compiler to use at least H.C.-5.4 (for example, by installing devtoolset-7)

**Comment by lanking520** [comment]
I tried to update GCC and it worked, thank you.
