### ISSUE TITLE
max_pool1d creates illegal memory access for large kernel sizes

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#38764]
## 🐛 Bug

Reported in the forum in [this post](https://discuss.pytorch.org/t/functional-max-pool1d-cuda-error-on-large-tensor/81985) by Robert-Jan Bruintjes.

Minimal code snippet copied from the post:
```python
import torch
import torch.nn.functional as F

x = 6.
size = 10. ** 6
print(f"Size of second dimension: {int(size)}")
poolsize = 4
x = torch.rand((1,int(size),poolsize), requires_grad=True).to('cuda:0')
y = F.max_pool1d(x.contiguous(), kernel_size=poolsize, stride=None, padding=0)

loss = torch.sum(y)
loss.backward()

"""
Traceback (most recent call last):
  File "efficient-segmentation/minimal_example.py", line 14, in <module>
    loss.backward()
  File "/home/nfs/username/miniconda3/envs/pytorch-cuda10/lib/python3.7/site-packages/torch/tensor.py", line 184, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/nfs/username/miniconda3/envs/pytorch-cuda10/lib/python3.7/site-packages/torch/autograd/__init__.py", line 123, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered
...
```

Verified with latest nightly binary `1.6.0.dev20200506-py3.7_cuda10.2.89`

CUDA core dump yields:
```
CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x5591bfb37ca0
[Current focus set to CUDA kernel 0, grid 7, block (0,0,160), thread (0,0,0), device 0, sm 0, warp 16, lane 0]
#0  0x00005591bfb37cc0 in void at::native::(anonymous namespace)::max_pool_backward_nchw<float, float>(int, float const*, long const*, int, int, int, int, int, int, int, int, int, int, int, int, int, int, float*)
   <<<(1,1,65535),(256,1,1)>>> ()
```

CC @xwang233 to take a shot at it.

cc @ngimel @albanD @mruberry

**Comment by chinmay5** [comment]
```
import torch

a = torch.rand([128, 442368, 5], device="cuda", requires_grad=True)

mod = torch.nn.MaxPool1d(5)

out = mod(a)

out.backward(torch.ones_like(out))
```

This is the minimal code and when using it I would get

![image](https://user-images.githubusercontent.com/16525717/84528118-5f03f200-acdf-11ea-980f-2a45613fa036.png)

I have created a new virtual environment and used the nightly build
![image](https://user-images.githubusercontent.com/16525717/84528174-77740c80-acdf-11ea-9f6c-c23bc14774b4.png)
