### ISSUE TITLE
test_stream_event_nogil fails on my devfair

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#38807]
```
test_stream_event_nogil (__main__.TestCuda) ... FAIL

======================================================================
FAIL: test_stream_event_nogil (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/home/ezyang/pytorch-tmp2/torch/testing/_internal/common_utils.py", line 796, in wrapper
    method(*args, **kwargs)
  File "/private/home/ezyang/pytorch-tmp2/torch/testing/_internal/common_utils.py", line 796, in wrapper
    method(*args, **kwargs)
  File "/private/home/ezyang/pytorch-tmp2/torch/testing/_internal/common_utils.py", line 389, in wrapper
    fn(*args, **kwargs)
  File "test/test_cuda.py", line 1303, in test_stream_event_nogil
    parent_time = sync_func(self, TestCuda.FIFTY_MIL_CYCLES)
  File "test/test_cuda.py", line 1267, in _event_wait
    self.assertTrue(s1.query())
AssertionError: False is not true

----------------------------------------------------------------------
```

This is running on devfair040

There have been many flaky reports about this, maybe there is something fundamentally wrong with this test.

cc @ngimel @mrshenli

**Comment by Flamefire** [comment]
I'm having the same issue on Power with V100 GPUs using PyTorch 1.6.0-rc2. Stacktrace is the same

**Comment by Flamefire** [comment]
I analyzed the test and might have found the problem:
The test code is:
```
        s1.synchronize()
        s1.record_event(e_tok)

        self.assertTrue(s0.query())
        self.assertTrue(s1.query())
```

So what it does is it syncs the stream, then records an event and immediately asserts the stream is ready. This can fail if the query is executed fast enough. So to fix this it should be waited for the event or stream to be ready. Judging from the surrounding code the following should be correct:

```
s1.synchronize()
e_tok.record(s0)
e_tok.synchronize()

self.assertTrue(s0.query())
self.assertTrue(s1.query())
```
