### ISSUE TITLE
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from

### ISSUE THREAD

**Issue by asjt2020** [pytorch/pytorch#39028]
i am not filmier with this.. I am not using NVIDIA GPU , but i have Intel HD graphics 4000.

can anyone help me?

========================= Video dataset #images = 1 =========
====================================== DIW NETWORK TRAIN FROM Ours_Bilinear=======================
===================Loading Pretrained Model OURS ===================================
./checkpoints/test_local\best_depth_Ours_Bilinear_inc_3_net_G.pth
Traceback (most recent call last):
File "2dtodepth.py", line 32, in
model = pix2pix_model.Pix2PixModel(opt)
File "C:\2dtodepth\prog\models\pix2pix_model.py", line 114, in init
new_model.cuda(), device_ids=range(torch.cuda.device_count()))
File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda
return self._apply(lambda t: t.cuda(device))
File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
module._apply(fn)
File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
module._apply(fn)
File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 199, in _apply
param.data = fn(param.data)
File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 265, in
return self.apply(lambda t: t.cuda(device))
File "C:\Program Files\Python37\lib\site-packages\torch\cuda_init.py", line 162, in _lazy_init
check_driver()
File "C:\Program Files\Python37\lib\site-packages\torch\cuda_init.py", line 82, in _check_driver
http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

C:\2dtodepth\prog>pause
Press any key to continue . . .

**Comment by peterjc123** [comment]
Intel GPU is not supported currently. You'll need to remove the `.cuda()` calls.
