### ISSUE TITLE
Problems implementing complex support for acosh, asinh, tanh

### ISSUE THREAD

**Issue by krshrimali** [pytorch/pytorch#39128]
## 🐛 Bug

There is an unexpected behavior (on Windows and MacOS) while trying to implement complex support for `acosh, asinh, atanh` Unary Ops. (Please see: https://github.com/pytorch/pytorch/pull/38388)

For Windows VS2019, CUDA 10.1:

```
Input Tensor:  tensor([(0.0000+0.0000j),  (1.2300+infj), (-0.0600+nanj),  (inf+2.9800j),
            (inf+infj),     (inf+nanj),  (nan+0.0000j),  (nan-0.0600j),
            (nan+infj),     (nan+nanj)])
asinh output:  tensor([(0.0000+0.0000j),  (inf+1.5708j),     (nan+nanj),  (inf+0.0000j),
         (inf+0.7854j),     (nan+nanj),     (nan+nanj),     (nan+nanj),
            (nan+nanj),     (nan+nanj)])
```

For Windows VS2019 CPU:

```
Input Tensor:  tensor([(0.0000+0.0000j),  (1.2300+infj), (-0.0600+nanj),  (inf+2.9800j),
            (inf+infj),     (inf+nanj),  (nan+0.0000j),  (nan-0.0600j),
            (nan+infj),     (nan+nanj)])
asinh output:  tensor([(0.0000+0.0000j),  (inf+1.5708j),     (nan+nanj),  (inf+0.0000j),
         (inf+0.7854j),     (nan+nanj),     (nan+nanj),     (nan+nanj),
            (nan+nanj),     (nan+nanj)])
```

While on MacOS, the call `torch.asinh()` throws a `RuntimeError`:

```
May 27 11:55:42   test_asinh_domain_complex_cpu_complex64 (__main__.TestTorchDeviceTypeCPU) ... Sample:  tensor([(0.0000+0.0000j),  (1.2300+infj), (-0.0600+nanj),  (inf+2.9800j),
May 27 11:55:42             (inf+infj),     (inf+nanj),  (nan+0.0000j),  (nan-0.0600j),
May 27 11:55:42             (nan+infj),     (nan+nanj)])
May 27 11:55:42 Traceback (most recent call last):
May 27 11:55:42   File "test/run_test.py", line 689, in <module>
May 27 11:55:42     main()
May 27 11:55:42   File "test/run_test.py", line 682, in main
May 27 11:55:42     raise RuntimeError(message)
May 27 11:55:42 RuntimeError: test_torch failed! Received signal: SIGILL
```

These logs are from the test cases that were written to test domains for these trigonometric functions. Please see the removed tests here which were used: https://github.com/pytorch/pytorch/pull/38388/commits/ccfe7c14423a5bede6c976aea520ac10833a67e7.

## To Reproduce

1. Use the following git commands:
```
git remote add test https://github.com/krshrimali/pytorch.git
git fetch test
git checkout test/complex-support-acosh-like
```
2. Build PyTorch using the branch `test/complex-support-acosh-like`.
3. Run tests: `python test/test_torch.py`. Please note that the tests fail on VS2019 (CPU and CUDA-10.1) and throw `RuntimeError` on MacOS.

**Note:** the stack traces/logs have been provided in the bug description.

## Expected behavior

Here is how Linux systems return output for `asinh` on the input tensors mentioned in the bug description.

```
tensor([(0.0000+0.0000j),  (inf+1.5708j),     (nan+nanj),  (inf+0.0000j),
         (inf+0.7854j),     (inf+nanj),  (nan+0.0000j),     (nan+nanj),
            (inf+nanj),     (nan+nanj)])
```

Here is a concise table on how the behavior diverges:

```
Input       |    Windows     |    Linux
(inf, nan)  |   (nan, nan)   |   (inf, nan)
(nan, 0.)   |   (nan, nan)   |   (nan, 0.)
(nan, inf)  |   (nan, nan)   |   (inf, nan)
```

**Note:** Windows diverges similarly on CPU and CUDA-10.1.

## Additional context

If you are keen on how the results are compared, please see: https://github.com/pytorch/pytorch/pull/38388#issuecomment-630158866.

cc: @mruberry, @anjali411

**Comment by kshitij12345** [comment]
Not sure if the issue is same, but have a look at 
https://github.com/pytorch/pytorch/blob/e3934dfae8ac62acb94f8916b7a763085a8cc87b/aten/src/ATen/native/cuda/UnaryFractionKernels.cu#L60-L100

Since the default behaviour of `thrust::complex` is not the same as `std::complex`, you might have to handle the edge cases differently.

**Comment by krshrimali** [comment]
Thanks, @kshitij12345 - I see what you mean, but I'm wondering if the edge cases are handled differently because of the op (reciprocal) itself or because of the difference in behavior of `thrust::complex` and `std::complex`.

Just a few points on why this could be more than handling edge cases differently:

* This behavior is divergent for CPU as well. And `thrust` is specific to CUDA.
* The reason why the edge cases are handled differently, can be because it's `reciprocal` op. Like, for other ops (like trigonometric functions: `acos`, `cosh` etc.) - they don't handle the edge cases separately. I may be wrong here, though.
* This is specific to Windows (in terms of different output) and Mac OS (`RuntimeError`), so there should be a reason why it works with gcc and not other compilers. I'm not sure about this.

**Comment by kshitij12345** [comment]
@krshrimali You might be correct. I just thought it may be relevant.

As for the difference between the compilers, maybe you can try [godbolt.org](https://godbolt.org/)
for MSVC in case you don't have access to Windows with a simple program and verify the outputs.
```C++
#include <iostream>
#include <complex>
#include <cmath>
#include <limits>

int main(){
  auto cplx = std::complex<double>(std::numeric_limits<double>::quiet_NaN(),42.0);
  std::cout << std::asinh(cplx);
}
```

**Comment by krshrimali** [comment]
Thanks, @kshitij12345! I had tested this behavior using local Windows System (VS 2019), and it gave expected results using `std::asinh`. So, it doesn't seem to be a problem with `std::op` on VS2019. I should have mentioned this in the issue itself, but yeah - thanks for pointing it out :)

**Comment by mruberry** [comment]
Hey @krshrimali, thanks for filing this issue! Are the first two codeblocks identical in the above though? 

And just so I'm sure I understand the issue, it's only Windows CPU that's divergent NumPy's behavior, right? Windows CUDA and the Linux behavior matched NumPy's?

**Comment by krshrimali** [comment]
> Hey @krshrimali, thanks for filing this issue! Are the first two codeblocks identical in the above though?

@mruberry - Yes, the first two codeblocks are identical (i.e. same output for Windows CUDA and CPU).
 
> And just so I'm sure I understand the issue, it's only Windows CPU that's divergent NumPy's behavior, right? Windows CUDA and the Linux behavior matched NumPy's?

No, Windows CUDA and CPU both show divergent behavior compared to NumPy's behavior. 

For example: `torch.asinh(complex(float('inf'), float('nan')))` gives `nan + nanj` while NumPy gives `inf + nanj`.

In this table (also in the issue description):

```
Input       |    Windows     |    Linux
(inf, nan)  |   (nan, nan)   |   (inf, nan)
(nan, 0.)   |   (nan, nan)   |   (nan, 0.)
(nan, inf)  |   (nan, nan)   |   (inf, nan)
```

Here, the "Windows" column corresponds to both CPU and CUDA systems. (since they both give same output, so I grouped them to one).

**Comment by mruberry** [comment]
Aha! Thank you for clarifying. Would you just amend that table to have column titles Windows (CPU and CUDA) and Linux (CPU and CUDA) and NumPy (Linux and Windows)? I know that's verbose, but that might make it easier to read.

**Comment by krshrimali** [comment]
Sure, @mruberry! I've updated the column titles in the issue description. Thanks!
