### ISSUE TITLE
Try Address Sanitizer in MSVC builds

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#39226]
## 🚀 Feature

According to https://www.codeproject.com/Articles/5269130/Address-Sanitizer-in-Visual-Cplusplus, x64 ASAN will be added in Visual C++ Update 16.7 Preview 1. Maybe we can have a try.

## Motivation

To improve the quality of the builds.

## Pitch

Have a try when it's available. In the long run, add a CI test for this.

## Alternatives

1. Use the native one
2. Use the one from clang on Windows

**Comment by peterjc123** [comment]
Tried it with MSVC 16.7 Preview 2.
Source code (`test_asan.cpp`):
```cpp
// test_asan.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>

int main()
{
    auto t = new int[5]{1, 2, 3, 4, 5};
    t[100] = 1;
}
```
Build command:
```powershell
cl /EHsc /O2 /MD /fsanitize=address test_asan.cpp /Z7 /link clang_rt.asan_dynamic-x86_64.lib clang_rt.asan_dynamic_runtime_thunk-x86_64.lib /DEBUG:FULL
```
ASAN env setup:
```cmd
set ASAN_OPTIONS=symbolize=1:detect_leaks=0
set ASAN_SYMBOLIZER_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.28919\bin\HostX64\x64
test_asan.exe
```
ASAN output:
```
=================================================================
==8076==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x11e08d6001d0 at pc 0x7ff7b8d314bd bp 0x0043bc4ffe30 sp 0x0043bc4ffe38
WRITE of size 4 at 0x11e08d6001d0 thread T0
==8076==WARNING: Failed to use and restart external symbolizer!
    #0 0x7ff7b8d314bc in main C:\Users\peter\source\repos\test_asan\test_asan\test_asan.cpp:9
    #1 0x7ff7b8d3263f in __scrt_common_main_seh D:\agent\_work\8\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #2 0x7ffae49b6fd3 in BaseThreadInitThunk+0x13 (C:\WINDOWS\System32\KERNEL32.DLL+0x180016fd3)
    #3 0x7ffae65dcec0 in RtlUserThreadStart+0x20 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18004cec0)

Address 0x11e08d6001d0 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow C:\Users\peter\source\repos\test_asan\test_asan\test_asan.cpp:9 in main
Shadow bytes around the buggy address:
  0x04169f0bffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04169f0bfff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04169f0c0000: fa fa 00 00 00 06 fa fa 00 00 04 fa fa fa fd fd
  0x04169f0c0010: fd fa fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa
  0x04169f0c0020: 00 00 00 fa fa fa 00 00 00 00 fa fa 00 00 00 00
=>0x04169f0c0030: fa fa 00 00 00 00 fa fa 00 00[00]00 fa fa 00 00
  0x04169f0c0040: 00 00 fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa
  0x04169f0c0050: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x04169f0c0060: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x04169f0c0070: fd fa fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x04169f0c0080: fd fd fd fd fa fa 00 00 02 fa fa fa 00 00 02 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==8076==ABORTING
```

**Comment by peterjc123** [comment]
@ezyang @malfet What do you think?

**Comment by malfet** [comment]
It’s an interesting option to add to cmake. But unless it’s faster to compile and run than clang or will it provide better coverage I don’t think it would be useful to run full ASAN test suite under more than one configuration.

**Comment by peterjc123** [comment]
> But unless it’s faster to compile and run than clang or will it provide better coverage I don’t think it would be useful to run full ASAN test suite under more than one configuration.

I'll have a try first. And I won't add ASAN tests for all confs, just one.

**Comment by peterjc123** [comment]
> But unless it’s faster to compile and run than clang or will it provide better coverage

I' not going to replace the current one with the MSVC one. Actually, I just want to get more test coverage in Windows-only codepaths.

**Comment by ezyang** [comment]
Master only ASAN seems reasonable.

BTW, we did an internal better engineering survey and we polled people what infra they found useful. ASAN got **zero** votes XD

**Comment by peterjc123** [comment]
> BTW, we did an internal better engineering survey and we polled people what infra they found useful. ASAN got **zero** votes XD

LOL. Actually, `import torch` doesn't pass in MSVC-ASAN builds.
