### ISSUE TITLE
WinError 6 when importing the pytorch library

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#39327]
## 🐛 Bug

```pytb
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import torch
  File "C:\tools\miniconda3\envs\env3.8\lib\site-packages\torch\__init__.py", line 92, in <module>
    raise err
OSError: [WinError 6] The handle is invalid. Error loading "C:\tools\miniconda3\envs\env3.8\lib\site-packages\torch\lib\cublasLt64_10.dll" or one of its dependencies.
```
The possible values of the DLLs that fail to read are listed as follows:
```
cublasLt64_10.dll
torch_cuda.dll
torch_cpu.dll
```
Currently, it only happens when trying to load the CUDA DLLs on a CPU only agent.

Related test runs:
https://app.circleci.com/pipelines/github/pytorch/vision/2701/workflows/42e21ef5-c302-4385-bc6d-6b6508919d4f/jobs/148667
https://circleci.com/gh/pytorch/pytorch/5563811?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## To Reproduce

1. import torch

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): nightly
 - Build command you used (if compiling from source): pip/conda
 - Python version: 3.6/3.8
 - CUDA/cuDNN version: 10.1&10.2
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

Seems to be intermittent. Because when I reran the job with SSH, it is gone.

**Comment by peterjc123** [comment]
It seems that we forget to set the return type and when it is not set, it defaults to `int`, while `LoadLibrary` returns a `void *`. If all the lower bits are zero, then it will become zero after casting.
