### ISSUE TITLE
WeightNorm CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by jtatusko** [pytorch/pytorch#3941]
Fails with CUDNN, works without. Tested on 0.2 and master
```python
import torch
from torch import nn
from torch.nn.modules.conv import Conv2d
from torch.nn.utils import weight_norm
from torch.autograd import Variable


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = weight_norm(Conv2d(2, 2, 3, padding=1))

    def forward(self, x):
        return self.conv(x)


if __name__ == '__main__':
    use_cuda = torch.cuda.is_available()
    FloatTensor = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor

    net = Net()
    if use_cuda:
        net.cuda()

    a = Variable(FloatTensor(1, 2, 5, 5))
    print(net(a))
```

```
Traceback (most recent call last):
  File "bleh.py", line 26, in <module>
    print(net(a))
  File "/home/heron/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "bleh.py", line 14, in forward
    return self.conv(x)
  File "/home/heron/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/heron/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/heron/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by jtatusko** [comment]
Update CUDNN fixed

**Comment by Lan1991Xu** [comment]
Hi, Can I know how update the cudnn? just download from the offical website. It seems pytorch already help you download the cudnn.
