### ISSUE TITLE
DISABLED test_backward_node_failure_python_udf (__main__.TensorPipeAgentDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#39464]
https://app.circleci.com/pipelines/github/pytorch/pytorch/176505/workflows/8f440b54-caea-453a-b9ad-3385827a6ea9/jobs/5672422/steps

```
Jun 03 19:00:50   test_backward_node_failure_python_udf (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:312] RPC agent for worker2 encountered error when reading incoming request: pipe closed
Jun 03 19:00:50 [W tensorpipe_agent.cpp:312] RPC agent for worker2 encountered error when reading incoming request: pipe closed
Jun 03 19:00:50 [E container.cpp:248] Could not release Dist Autograd Context on node 3: pipe closed
Jun 03 19:00:50 terminate called after throwing an instance of 'std::out_of_range'
Jun 03 19:00:50   what():  _Map_base::at
```

```
Jun 03 19:04:08 ======================================================================
Jun 03 19:04:08 FAIL [1.620s]: test_backward_node_failure_python_udf (__main__.TensorPipeAgentDistAutogradTestWithSpawn)
Jun 03 19:04:08 ----------------------------------------------------------------------
Jun 03 19:04:08 Traceback (most recent call last):
Jun 03 19:04:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jun 03 19:04:08     self._join_processes(fn)
Jun 03 19:04:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
Jun 03 19:04:08     self._check_return_codes(elapsed_time)
Jun 03 19:04:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 349, in _check_return_codes
Jun 03 19:04:08     i, first_process.exitcode, p.exitcode
Jun 03 19:04:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1100, in assertEqual
Jun 03 19:04:08     self.assertTrue(result, msg=msg)
Jun 03 19:04:08 AssertionError: False is not true : Expect process 2 exit code to match Process 0 exit code of 0, but got -6
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by mrshenli** [comment]
@lw it shows more info this time.

**Comment by lw** [comment]
Should be fixed by https://github.com/pytorch/tensorpipe/pull/177

**Comment by mrshenli** [comment]
@lw Do we need a PR to bump up TensorPipe submodule version?

**Comment by lw** [comment]
Yes, I wanted to get a few more commits in but actually let's first get this fixed and worry about those later. I'll send out a PR right away.

**Comment by mrshenli** [comment]
Closing this issue to re-enable this test as #39598 is in.
