### ISSUE TITLE
TestTorchDeviceTypeCPU.test_complex_flip_cpu_complex128 - TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#39478]
I was running tests locally and I got:

```
E
======================================================================
ERROR: test_complex_flip_cpu_complex128 (__main__.TestTorchDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
    result = test(self, device_arg, dtype)
  File "test/test_torch.py", line 8094, in test_complex_flip
    self._np_compare_func((torch_fn, np_fn), data, device, dtype)
  File "test/test_torch.py", line 6400, in _np_compare_func
    np_result = torch.from_numpy(np_fn(a).copy())
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.6/site-packages/numpy/lib/function_base.py", line 206, in flip
    indexer[axis] = slice(None, None, -1)
TypeError: list indices must be integers or slices, not tuple

----------------------------------------------------------------------
```

I wonder if there's something wrong with my numpy version

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by kshitij12345** [comment]
Looking at the docs, I guess the numpy version on local system is less than `1.15`
https://numpy.org/doc/stable/reference/generated/numpy.flip.html

**Comment by mruberry** [comment]
Thanks @kshitij12345. Since this issue was filed flip testing has changed considerably, and NumPy 1.15 is 2+ years old now. For more recent NumPy version requirements we should probably add version checks.
