### ISSUE TITLE
When the name of running file is "dis.py", the pytorch environment will be crashed.

### ISSUE THREAD

**Issue by szq0214** [pytorch/pytorch#39473]
## 🐛 Bug

 import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 17, in <module>
    from ._utils_internal import get_file_path, prepare_multiprocessing_environment
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/_utils_internal.py", line 4, in <module>
    import inspect
  File "/home/jq1/jq2/anaconda3/lib/python3.7/inspect.py", line 35, in <module>
    import dis
  File "/home/jq1/jq2/projects/moco_fast/FixRes/dis.py", line 10, in <module>
    import torch.nn as nn
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/nn/modules/__init__.py", line 1, in <module>
    from .module import Module
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 6, in <module>
    from ..parameter import Parameter
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/nn/parameter.py", line 5, in <module>
    class Parameter(torch.Tensor):
AttributeError: module 'torch' has no attribute 'Tensor'

 import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 17, in <module>
    from ._utils_internal import get_file_path, prepare_multiprocessing_environment
  File "/home/jq1/jq2/anaconda3/lib/python3.7/site-packages/torch/_utils_internal.py", line 4, in <module>
    import inspect
  File "/home/jq1/jq2/anaconda3/lib/python3.7/inspect.py", line 56, in <module>
    for k, v in dis.COMPILER_FLAG_NAMES.items():
AttributeError: module 'dis' has no attribute 'COMPILER_FLAG_NAMES'

## To Reproduce

1. python dis.py
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): Python 3.7.6 
 - OS (e.g., Linux): Linux version 3.10.0-957.10.1.el7.x86_64 
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by SsnL** [comment]
You have a file that shadows a builtin library of python https://docs.python.org/3/library/dis.html , which should not happen unless you are messing with Python's import path or PATH, neither of which is recommended. It's not really PyTorch's fault. Any code that uses `inspect` would be broken.

**Comment by mrshenli** [comment]
Since this is not actionable, I am closing this issue. Please feel free to reopen if this turns out to be a concrete change request.
