### ISSUE TITLE
Export fake quantization function to ONNX

### ISSUE THREAD

**Issue by skyw** [pytorch/pytorch#39502]
## 🚀 Feature

Export fake_quantize_per_tensor_affine and fake_quantize_per_channel_affine functions to ONNX.

## Motivation

To support deploying QAT network by backend like TensorRT  outside pytorch through ONNX, fake quantization needs to be exported to ONNX operator.

## Pitch

fake quantization will be broken into a pair of QuantizeLinear and DequantizeLinear ONNX operator.

## Additional context

Fake quantization is effectively quantize followed dequantize. Have discussed with @raghuramank100 and reached an agreement this is the right way to export. 

Similar functionality has been added to tensorflow-onnx, https://github.com/onnx/tensorflow-onnx/pull/919. 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by Zehaos** [comment]
Good point!

**Comment by skyw** [comment]
Thanks @Zehaos. What was discussed with @jamesr66a and @raghuramank100 is I'll also contribute the PR. If the owner of the code is OK with it.

**Comment by jamesr66a** [comment]
Hi @skyw, this proposal looks good! Please feel free to contribute the PR

**Comment by skyw** [comment]
Thanks, James. Filed PR https://github.com/pytorch/pytorch/pull/39738

**Comment by ZyrianovS** [comment]
On current master.

In `test/onnx/test_models.py` `TestModels` gets its `opset_version` from `torch.onnx.symbolic_helper` which is 9 by default. https://github.com/pytorch/pytorch/blob/master/test/onnx/test_models.py#L50
https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_helper.py#L847

```
from torch.onnx.symbolic_helper import _export_onnx_opset_version 
opset_version = _export_onnx_opset_version
print(opset_version)
9
```
```
python test/onnx/test_models.py

Ran 32 tests in 27.295s

OK (skipped=10)
```
So it skipped 10 tests by default, including I believe `test_fake_quant`, `test_qat_resnet_pertensor` and `test_qat_resnet_per_channel` with  `@skipIfUnsupportedMinOpsetVersion` wrapper set to 10 and 13 opset_version that I was trying to debug in my QAT pipeline.

If we set `_default_onnx_opset_version` in `torch.onnx.symbolic_helper` to 13 and test with that so it does not skip those QAT tests I get:
```
Ran 32 tests in 38.009s

FAILED (errors=3, skipped=5)
```

```
ERROR: test_fake_quant (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/simon/pytorch/test/onnx/test_pytorch_common.py", line 51, in wrapper
    return func(self)
  File "test/onnx/test_models.py", line 184, in test_fake_quant
    self.exportTest(toC(FakeQuantNet()), toC(x))
  File "test/onnx/test_models.py", line 56, in exportTest
    graph = torch.onnx.utils._trace(model, inputs, OperatorExportTypes.ONNX)
  File "/home/simon/pytorch/torch/onnx/utils.py", line 378, in _trace
    trace_graph = _optimize_graph(trace_graph, operator_export_type, params_dict={})
  File "/home/simon/pytorch/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/simon/pytorch/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/simon/pytorch/torch/onnx/utils.py", line 1058, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 167, in wrapper
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)]
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 167, in <listcomp>
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)]
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 94, in _parse_arg
    "for argument '{}' of node '{}', got '{}'.".format(arg_name, node_name, value.node().kind()))
RuntimeError: Expected node type 'onnx::Constant' for argument 'scale' of node 'fake_quantize_per_tensor_affine', got 'prim::Param'.
```
```
ERROR: test_qat_resnet_per_channel (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/simon/pytorch/test/onnx/test_pytorch_common.py", line 51, in wrapper
    return func(self)
  File "test/onnx/test_models.py", line 226, in test_qat_resnet_per_channel
    self.exportTest(toC(qat_resnet50), toC(x))
  File "test/onnx/test_models.py", line 56, in exportTest
    graph = torch.onnx.utils._trace(model, inputs, OperatorExportTypes.ONNX)
  File "/home/simon/pytorch/torch/onnx/utils.py", line 378, in _trace
    trace_graph = _optimize_graph(trace_graph, operator_export_type, params_dict={})
  File "/home/simon/pytorch/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/simon/pytorch/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/simon/pytorch/torch/onnx/utils.py", line 1058, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 167, in wrapper
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)]
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 167, in <listcomp>
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)]
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 94, in _parse_arg
    "for argument '{}' of node '{}', got '{}'.".format(arg_name, node_name, value.node().kind()))
RuntimeError: Expected node type 'onnx::Constant' for argument 'scale' of node 'fake_quantize_per_tensor_affine', got 'prim::Param'.
```
```
ERROR: test_qat_resnet_pertensor (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/simon/pytorch/test/onnx/test_pytorch_common.py", line 51, in wrapper
    return func(self)
  File "test/onnx/test_models.py", line 205, in test_qat_resnet_pertensor
    self.exportTest(toC(qat_resnet50), toC(x))
  File "test/onnx/test_models.py", line 56, in exportTest
    graph = torch.onnx.utils._trace(model, inputs, OperatorExportTypes.ONNX)
  File "/home/simon/pytorch/torch/onnx/utils.py", line 378, in _trace
    trace_graph = _optimize_graph(trace_graph, operator_export_type, params_dict={})
  File "/home/simon/pytorch/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/simon/pytorch/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/simon/pytorch/torch/onnx/utils.py", line 1058, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 167, in wrapper
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)]
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 167, in <listcomp>
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)]
  File "/home/simon/pytorch/torch/onnx/symbolic_helper.py", line 94, in _parse_arg
    "for argument '{}' of node '{}', got '{}'.".format(arg_name, node_name, value.node().kind()))
RuntimeError: Expected node type 'onnx::Constant' for argument 'scale' of node 'fake_quantize_per_tensor_affine', got 'prim::Param'.
```
I was getting the same errors when I updated to `torch 1.10.0` in my QAT training pipeline. Rolling back to `torch 1.9.1` solved the issue.
