### ISSUE TITLE
[CI] FAIL: test_n_threads (__main__.TestOpenMP_ParallelFor)

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#39509]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/30483/console

```
20:59:39 ======================================================================
20:59:39 FAIL: test_n_threads (__main__.TestOpenMP_ParallelFor)
20:59:39 Make sure there is no memory leak with many threads
20:59:39 ----------------------------------------------------------------------
20:59:39 Traceback (most recent call last):
20:59:39   File "test_openmp.py", line 66, in test_n_threads
20:59:39     self.func_rss(300)
20:59:39   File "test_openmp.py", line 54, in func_rss
20:59:39     msg='memory did not stabilize, {}'.format(str(list(last_rss))))
20:59:39 AssertionError: False is not true : memory did not stabilize, [1495425024, 1495425024, 1495564288, 1495564288, 1495564288]
```

cc @ezyang @gchanan @zou3519

**Comment by ilia-cher** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/40175
