### ISSUE TITLE
DISABLED test_handle_send_exceptions (__main__.TensorPipeAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#39504]
https://app.circleci.com/pipelines/github/pytorch/pytorch/176674/workflows/e3c75b34-bb32-4516-a3e5-68831e29b192/jobs/5678980/steps

```
Jun 03 23:34:34   test_handle_send_exceptions (__main__.TensorPipeAgentRpcTestWithSpawn) ... [W tensorpipe_agent.cpp:312] RPC agent for worker2 encountered error when reading incoming request: pipe closed
Jun 03 23:34:34 terminate called after throwing an instance of 'std::out_of_range'
Jun 03 23:34:34   what():  _Map_base::at
Jun 03 23:34:34 [W tensorpipe_agent.cpp:453] RPC agent for worker1 encountered error when reading incoming request: ECONNRESET: connection reset by peer
Jun 03 23:34:34 [W tensorpipe_agent.cpp:436] RPC agent for worker1 encountered error when writing outgoing request: ECONNRESET: connection reset by peer
Jun 03 23:34:34 FAIL (1.221s)
```

```
Jun 03 23:37:23 ======================================================================
Jun 03 23:37:23 FAIL [1.221s]: test_handle_send_exceptions (__main__.TensorPipeAgentRpcTestWithSpawn)
Jun 03 23:37:23 ----------------------------------------------------------------------
Jun 03 23:37:23 Traceback (most recent call last):
Jun 03 23:37:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jun 03 23:37:23     self._join_processes(fn)
Jun 03 23:37:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
Jun 03 23:37:23     self._check_return_codes(elapsed_time)
Jun 03 23:37:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 349, in _check_return_codes
Jun 03 23:37:23     i, first_process.exitcode, p.exitcode
Jun 03 23:37:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1131, in assertEqual
Jun 03 23:37:23     self.assertTrue(result, msg=msg)
Jun 03 23:37:23 AssertionError: False is not true : Expect process 2 exit code to match Process 0 exit code of 0, but got -6
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
Should be fixed by https://github.com/pytorch/tensorpipe/pull/177

**Comment by mrshenli** [comment]
Closing this issue to re-enable this test as #39598 is in.
