### ISSUE TITLE
[JIT] Cannot call at::cudnn_convolution in Python with torch.utils.cpp_extension

### ISSUE THREAD

**Issue by allankevinrichie** [pytorch/pytorch#39518]
## 🐛 Bug

I want to call some ATen ops that seem not accessible from PyTorch directly to build some new ops. After some efforts, I found a simple solution using `torch.utils.cpp_extension.load_inline`:

```Python
from torch.utils.cpp_extension import load_inline
at_ops = load_inline(
        name='at_ops',
        cpp_sources=["""
        using namespace at;
        """],
        functions=[
            "mkldnn_convolution",
            "mkldnn_convolution_backward",
            #"cudnn_convolution",
            "cudnn_convolution_backward",
            "cudnn_grid_sampler",
            "cudnn_grid_sampler_backward"
        ],
        with_cuda=True
)
```
The above code worked as expected, which successfully bound the corresponding ATen ops to the Python module 'at_ops'.

Strangely enough, I found that the jit compiler will fail if I uncomment the `cudnn_convolution` line:

```Python
from torch.utils.cpp_extension import load_inline
at_ops = load_inline(
        name='at_ops',
        cpp_sources=["""
        using namespace at;
        """],
        functions=[
            "mkldnn_convolution",
            "mkldnn_convolution_backward",
            "cudnn_convolution",
            "cudnn_convolution_backward",
            "cudnn_grid_sampler",
            "cudnn_grid_sampler_backward"
        ],
        with_cuda=True
)
```
The above code will cause the following error

```bash
Traceback (most recent call last):
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\Ziheng\anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c803b01bfdc8>", line 1, in <module>
    runfile('E:/OneDrive/文档/projects/Saliency-Detection-in-360-Videos/sconv/tools/load_at_ops.py', wdir='E:/OneDrive/文档/projects/Saliency-Detection-in-360-Videos/sconv/tools')
  File "C:\Program Files\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/OneDrive/文档/projects/Saliency-Detection-in-360-Videos/sconv/tools/load_at_ops.py", line 102, in <module>
    with_cuda=True
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1046, in load_inline
    is_python_module)
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1086, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'at_ops': [1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=at_ops -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\Ziheng\anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -c C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp /Fomain.o 
FAILED: main.o 
cl /showIncludes -DTORCH_EXTENSION_NAME=at_ops -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\Ziheng\anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -c C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp /Fomain.o 
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28612 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp(6): error C2672: 'torch::wrap_pybind_function': no matching overloaded function found
C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp(6): error C2783: 'auto torch::wrap_pybind_function(Func &&)': could not deduce template argument for 'Func'
C:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\torch/csrc/Exceptions.h(319): note: see declaration of 'torch::wrap_pybind_function'
ninja: build stopped: subcommand failed.

```
 
I just have no idea why this happened...

## To Reproduce

1. run the following code:
```Python
from torch.utils.cpp_extension import load_inline
at_ops = load_inline(
        name='at_ops',
        cpp_sources=["""
        using namespace at;
        """],
        functions=[
            "cudnn_convolution",
        ],
        with_cuda=True
)
```

will cause the following error message:

```bash
Traceback (most recent call last):
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\Ziheng\anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c803b01bfdc8>", line 1, in <module>
    runfile('E:/OneDrive/文档/projects/Saliency-Detection-in-360-Videos/sconv/tools/load_at_ops.py', wdir='E:/OneDrive/文档/projects/Saliency-Detection-in-360-Videos/sconv/tools')
  File "C:\Program Files\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/OneDrive/文档/projects/Saliency-Detection-in-360-Videos/sconv/tools/load_at_ops.py", line 102, in <module>
    with_cuda=True
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1046, in load_inline
    is_python_module)
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1086, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "C:\Users\Ziheng\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'at_ops': [1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=at_ops -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\Ziheng\anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -c C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp /Fomain.o 
FAILED: main.o 
cl /showIncludes -DTORCH_EXTENSION_NAME=at_ops -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\Ziheng\anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -c C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp /Fomain.o 
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28612 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp(6): error C2672: 'torch::wrap_pybind_function': no matching overloaded function found
C:\Users\Ziheng\AppData\Local\Temp\torch_extensions\at_ops\main.cpp(6): error C2783: 'auto torch::wrap_pybind_function(Func &&)': could not deduce template argument for 'Func'
C:\Users\Ziheng\anaconda3\lib\site-packages\torch\include\torch/csrc/Exceptions.h(319): note: see declaration of 'torch::wrap_pybind_function'
ninja: build stopped: subcommand failed.
```

## Expected behavior
`at::cudnn_convolution` can be called from Python via `at_ops.cudnn_convolution`.

## Environment
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.16.19112601-MSVC_2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.5.0
[pip] torchvision==0.6.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              h74a9793_1  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37hb782905_0  
[conda] mkl_fft                   1.0.15           py37h14836fe_0  
[conda] mkl_random                1.1.0            py37h675688f_0  
[conda] numpy                     1.18.1           py37h93ca92e_0  
[conda] numpy-base                1.18.1           py37hc3f5095_1  
[conda] numpydoc                  0.9.2                      py_0  
[conda] pytorch                   1.5.0           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch

## Additional context

cc @suo

**Comment by peterjc123** [comment]
I think `load_inline` is not ready for Windows. Will look into it later.

**Comment by peterjc123** [comment]
More details on pybind docs with overloaded functions: https://pybind11.readthedocs.io/en/stable/classes.html#overloaded-methods.

**Comment by allankevinrichie** [comment]
Thanks for your comment @peterjc123 , I think you are right. The problem is solved by explicitly handling overload resolution. I'm closing this issue.
