### ISSUE TITLE
[JIT] Cannot directly run tests in test_module_interface 

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#39523]
I got an error in CI. The details of the error are not important:

```
Jun 04 03:31:34 ======================================================================
Jun 04 03:31:34 ERROR [0.129s]: test_freeze_module_with_interface (jit.test_module_interface.TestModuleInterface)
Jun 04 03:31:34 ----------------------------------------------------------------------
Jun 04 03:31:34 Traceback (most recent call last):
Jun 04 03:31:34   File "/var/lib/jenkins/workspace/test/jit/test_module_interface.py", line 436, in test_freeze_module_with_interface
Jun 04 03:31:34     class ModInterface(torch.nn.Module):
Jun 04 03:31:34   File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 1400, in interface
Jun 04 03:31:34     raise RuntimeError("TorchScript interface does not support inheritance yet. "
Jun 04 03:31:34 RuntimeError: TorchScript interface does not support inheritance yet. Please directly inherit from 'object' or 'nn.Module'.
Jun 04 03:31:34 
```

On my local build, I try to run this tesst. The test doesn't exist.

```
(/scratch/ezyang/pytorch-tmp2-env) ezyang@devfair040:~/pytorch-tmp2$ python test/test_jit.py jit.test_module_interface.TestModuleInterface.test_freeze_module_with_interface
E
======================================================================
ERROR: jit (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'jit'

----------------------------------------------------------------------
```

I try to run the test file directly. I get this:

```
python test/jit/test_module_interface.py TestModuleInterface.test_freeze_module_with_interface
Traceback (most recent call last):
  File "test/jit/test_module_interface.py", line 17, in <module>
    raise RuntimeError("This test file is not meant to be run directly, use:\n\n"
RuntimeError: This test file is not meant to be run directly, use:

        python test/test_jit.py TESTNAME

```

In the end, the only way I can figure out how to run a single test is pytest *specifically* on the subfile (`test_jit.py` doesn't work)

```
pytest test/jit/test_module_interface.py -k test_freeze_module_with_interface
```

Running test files directly should ork

cc @suo

**Comment by jamesr66a** [comment]
In keeping with the convention for JIT tests, the proper way to run this test suite is:

```
python test/test_jit.py TestModuleInterface
```

However, this is currently broken on master due to a missing import. I've added the import in this PR: https://github.com/pytorch/pytorch/pull/39592. After landing, these tests should be runnable manually

**Comment by mattip** [comment]
PR #39592 has been merged.

**Comment by mattip** [comment]
Can we close the issue?

**Comment by ezyang** [comment]
sure
