### ISSUE TITLE
[JIT] OrderedDict doesn't support custom objects

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#39569]
There seems to be an inconsistency with how  `OrderedDict` is handled by torchscript compared to `dict`. 

Minimal example illustrating that `OrderedDict` doesn't seem to support custom objects, while dict do.
```python
import torch; from typing import Dict; from collections import OrderedDict

class C:
    def __init__(self, x):
        self.x = x

def f(x):
    # this fails with the below error
    d : Dict[str, C] = OrderedDict()
    # this works
    # d : Dict[str, C] = {}

    d['a'] = C(x)
    d['b'] = C(2 * x)
    return d

ff = torch.jit.script(f)
```

with the error message

```python
Traceback (most recent call last):
  File "tst.py", line 17, in <module>
    ff = torch.jit.script(f)
  File "/Users/fmassa/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 1369, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
Variable 'd' is annotated with type Dict[str, __torch__.C] but is being assigned to a value of type Dict[str, Tensor]:
  File "tst.py", line 9
def f(x):
    d : Dict[str, C] = OrderedDict()
    ~ <--- HERE
    d['a'] = C(x)
    d['b'] = C(2 * x)
```

**Comment by jamesr66a** [comment]
Hi @fmassa, this is indeed a difference in semantics between Python and TorchScript. To work around this, you can use a type-annotated empty list in the constructor of `OrderedDict`:

```
import torch; from typing import Dict, Tuple, List; from collections import OrderedDict

class C:
    def __init__(self, x):
        self.x = x

def f(x):
    # this fails with the below error
    dummy = torch.jit.annotate(List[Tuple[str, C]], [])
    d : Dict[str, C] = OrderedDict(dummy)
    # this works
    # d : Dict[str, C] = {}

    d['a'] = C(x)
    d['b'] = C(2 * x)
    return d

ff = torch.jit.script(f)
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
