### ISSUE TITLE
Dataloader._shutdown_workers hangs

### ISSUE THREAD

**Issue by moi90** [pytorch/pytorch#39570]
## 🐛 Bug

Dataloader._shutdown_workers hangs unexpectedly. The program has to be killed with Ctrl-C. 

```
  File "iterative_clustering.py", line 80, in calculate_features
    for batch in tqdm(dataloader, desc=f"Features (pass {i})"):
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/tqdm/std.py", line 1119, in __iter__
    for obj in iterable:
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 571, in __next__
    self._shutdown_workers()
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 659, in _shutdown_workers
    w.join()
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

## To Reproduce

```python
    features = np.zeros((n_samples, n_features))
    model.eval()
    with torch.no_grad():
        for i in range(n_passes):
            offset = 0
            for batch in tqdm(dataloader, desc=f"Features (pass {i})"):
                batch_images = torch.rot90(batch["image"].cuda(), i, (-2, -1))
                assert (
                    batch_images.size() == batch["image"].size()
                ), f"{batch_images.size()} vs. {batch['image'].size()}"
                batch_features = model.forward(batch_images)
                batch_features = torch.flatten(batch_features, 1).cpu().numpy()
                batch_size = batch_features.shape[0]
                features[offset : offset + batch_size] += batch_features
                offset += batch_size
```

The error happens in the forth (last) iteration of `for i in range(n_passes)`. `num_workers` is 8. 

## Expected behavior

I would expect the loop to terminate without problems.

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Linux Mint 18.1 Serena
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: GeForce GTX TITAN X
Nvidia driver version: 384.98
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] pytorch-lightning==0.7.2.dev0
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               9.0                  h13b8566_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] pytorch-lightning         0.7.2.dev0               pypi_0    pypi
[conda] torchvision               0.3.0           py37_cu9.0.176_1    pytorch

## Additional info

When examining the code, I see no reason why this wouldn't work. A work-around may be passing a timeout to `w.join()` at the expense of leaving zombie processes around.

cc @SsnL

**Comment by moi90** [comment]
Could be related to #9985 and https://github.com/tqdm/tqdm/issues/611 .

**Comment by VitalyFedyunin** [comment]
Have you tried pytorch 1.5? We did a lot of multiprocessing improvements since 1.1

**Comment by moi90** [comment]
I have not tried to upgrade pytorch as I'm in the middle of some experiments and don't want to change anything important. I did however upgrade tqdm to 4.46.0 (previously 4.44.1) and the problem so far did not occur again. If this turns out to be just a coincidence, I'm going to reopen the bug.

**Comment by moi90** [comment]
Unfortunately, the problem was not solved by upgrading tqdm. I will try pytorch 1.5 and report my results.

**Comment by moi90** [comment]
I upgraded to 1.5 (which required upgrading CUDA which required updating the graphics driver. A nightmare...), but unfortunately, the problem still persists. I will try to investigate further.

**Comment by moi90** [comment]
I hangs at the same place:

```
  File "iterative_clustering.py", line 80, in calculate_features
    for batch in tqdm(dataloader, desc=f"Features (pass {i})"):
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 830, in _next_data
    self._shutdown_workers()
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 942, in _shutdown_workers
    w.join()
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/data1/mschroeder/miniconda3/envs/20-ssdc/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by en4bz** [comment]
This may or may not be related and may already be a know issue but Dataloader seems to be broken with respect to cuda forking semantics. Forking after calling `cuInit` is not allowed by cuda which Dataloader (at least in 1.3.1) appears to do. This is probably fine since Dataloader doesn't actually make any cuda calls but I could envision a case where a thread in the parent locks a mutex  via a cuda call then forks a DataLoader on another thread. After the fork the lock remains locked in the child and when cuda is unloaded in the child at shutdown it blocks on the mutex and causes the child to hang on shutdown. A a full backtrace of the child process via gdb would be helpful in confirming or invalidating this hypothesis.

**Comment by moi90** [comment]
@en4bz Thanks for thinking about my problem! Can you provide further directions on how to get such a trace?

**Comment by TrentBrick** [comment]
FWIW I am having a very similar issue. 

Python 3.5, tqdm 4.46.1. Torch 1.5.0 on Ubuntu LTS 16.04 with one T4 GPU and 16 core CPU. 

My training loop is as follows: 
1. Use Ray multiprocessing to collect rollouts from an OpenAI gym. 
2. Use these to train a model using DataLoader. 
3. Use Ray multiprocessing to perform evolutionary search optimization. 
4. Repeat. 

I can do one full cycle of this. Then on the 2nd cycle it hangs right as step #2. should finish for the very last batch in the epoch. Ctrl+C results in same error message which brought me here. 

I suspect my issue may be arising from the Ray Multiprocessing workers clashing as I am getting an error associated with this too? (I am using from ray.util.multiprocessing import Pool which should kill the workers when they have finished, however.)

`  File "/home/trentonbricken/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 345, in __next__                                                                           [64/1898]
    data = self._next_data()                                                                                                                                                                              
  File "/home/trentonbricken/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 830, in _next_data                                                                                  
    self._shutdown_workers()                                                                                                                                                                              
  File "/home/trentonbricken/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 942, in _shutdown_workers
    w.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/trentonbricken/.local/lib/python3.5/site-packages/ray/worker.py", line 869, in shutdown
    time.sleep(0.5)
KeyboardInterrupt`

**Comment by SsnL** [comment]
@TrentBrick Interesting that it hangs reliably! Could you try to come up with an as-minimal-as-possible reproducing code?

**Comment by moi90** [comment]
@SsnL Thanks! Your commit should solve my problem for know. I will try it out as soon as possible.

**Comment by Cathy-t** [comment]
Appeared when I was debugging. When I run, the problem disappeared.

Traceback (most recent call last):
  File "/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/train.py", line 336, in <module>
    main(args)
  File "train.py", line 134, in main
    train_loss = train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 177, in train
    for cnt, (ref, a) in enumerate(train_loader, 1):
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 571, in __next__
    self._shutdown_workers()
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 659, in _shutdown_workers
    w.join()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by qqqqxxyy** [comment]
I have meet the exactly same problem

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2ba644bdb710>
Traceback (most recent call last):
  File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 926, in __del__
    self._shutdown_workers()
  File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 906, in _shutdown_workers
    w.join()
  File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt:

Then I changed tqdm version from 4.61.2 to 4.40.0. The problem magically solved. I have no idea why, but it works.
torch : 1.3.1 
python : 3.7

**Comment by 0424zzc** [comment]
> I have meet the exactly same problem
> 
> Exception ignored in: <function _MultiProcessingDataLoaderIter.**del** at 0x2ba644bdb710> Traceback (most recent call last): File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 926, in **del** self._shutdown_workers() File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 906, in _shutdown_workers w.join() File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/multiprocessing/process.py", line 140, in join res = self._popen.wait(timeout) File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait return self.poll(os.WNOHANG if timeout == 0.0 else 0) File "/project/zmwang/YeJ/anaconda3/envs/qxy_I2C_1.3.1_3.7/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll pid, sts = os.waitpid(self.pid, flag) KeyboardInterrupt:
> 
> Then I changed tqdm version from 4.61.2 to 4.40.0. The problem magically solved. I have no idea why, but it works. torch : 1.3.1 python : 3.7

This solution also works for me. Thanks for sharing!!!
