### ISSUE TITLE
ninja stacktrace obscures build error

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3967]
Here is my most recent compile failure (due to a mistake I made):

```
torch/csrc/autograd/generated/Functions.cpp:584:23: error: converting to ‘std::tuple<at::Tensor, a[82/50144]
 at::Tensor>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-paramete
r-1-1> >::tuple(const _Elements& ...) [with _Elements = {at::Tensor, at::Tensor, at::Tensor}]’
   return {ggG, ggB, gO}; // TODO remove me
                       ^
[62/96] gcc -pthread -fno-strict-aliasing -g -O2 -...4-2.7/torch/csrc/autograd/generated/VariableType.d
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 726, in <module>
    install_requires=['pyyaml', 'numpy'],
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 213, in run
    setuptools.command.develop.develop.run(self)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/site-packages/setuptools/command/develop.py", l
ine 36, in run
    self.install_for_development()
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/site-packages/setuptools/command/develop.py", l
ine 134, in install_for_development
    self.run_command('build_ext')
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 313, in run
    setuptools.command.build_ext.build_ext.run(self)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/site-packages/setuptools/command/build_ext.py",
 line 75, in run
    _build_ext.run(self)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/command/build_ext.py", line 340, in r
un
    self.build_extensions()
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/command/build_ext.py", line 449, in b
uild_extensions
    self.build_extension(ext)
  File "/data/users/ezyang/pytorch-python2/tools/setup_helpers/ninja_builder.py", line 92, in build_extensio
n
    self._build_default(ext)
  File "/data/users/ezyang/pytorch-python2/tools/setup_helpers/ninja_builder.py", line 43, in _build_default
    return setuptools.command.build_ext.build_ext.build_extension(self, ext)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/site-packages/setuptools/command/build_ext.py",
 line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/command/build_ext.py", line 531, in b
uild_extension
    target_lang=language)
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/distutils/ccompiler.py", line 691, in link_shar
ed_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/data/users/ezyang/pytorch-python2/tools/setup_helpers/ninja_builder.py", line 82, in link
    builder.run()
  File "/data/users/ezyang/pytorch-python2/tools/setup_helpers/ninja_builder.py", line 28, in run
    subprocess.check_call([self.ninja_program, '-f', self.filename])
  File "/home/ezyang/local/pytorch-python2-env/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ezyang/local/pytorch-python2-env/lib/python2.7/site-packages
/ninja/data/bin/ninja', '-f', 'build/build.torch._C.ninja']' returned non-zero exit status 1
```

The stacktrace is so long I can't see the actual compile error.

**Comment by ezyang** [comment]
This no longer happens
