### ISSUE TITLE
TestTorchDeviceTypeCPU.test_float_to_int_conversion_finite_cpu_uint8 is broken on PowerPC

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#39671]
From https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le/1099/console
```
======================================================================
FAIL: test_float_to_int_conversion_finite_cpu_uint8 (__main__.TestTorchDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/miniconda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/home/jenkins/miniconda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 542, in only_fn
    return fn(self, device, *args, **kwargs)
  File "test_torch.py", line 17152, in test_float_to_int_conversion_finite
    self._float_to_int_conversion_helper(vals, device, dtype)
  File "test_torch.py", line 17127, in _float_to_int_conversion_helper
    self.assertEqual(torch.from_numpy(a), t.cpu())
  File "/home/jenkins/miniconda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1085, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! Found 2 different element(s) (out of 9), with the greatest difference of 255 (0 vs. 255) occuring at index 2.
```

**Comment by ptrblck** [comment]
I guess it might be related to https://github.com/numpy/numpy/issues/19881
