### ISSUE TITLE
how to use custom define python obj in torchscript

### ISSUE THREAD

**Issue by chuanhuayang** [pytorch/pytorch#39719]
I am ready convert a pytorch module to ScriptModule, and then load it in c++，but i am blocked by this error `This attribute exists on the Python module, but we failed to convert Python type: 'Vocab' to a TorchScript type`, the `Vocab` is a python object i define. the demo code is here:
   
    import torch
    class Vocab(object):
        def __init__(self, name):
            self.name = name

        def show(self):
            print("dict:" + self.name)

    class Model(torch.nn.Module):
        def __init__(self, ):
            super(Model, self).__init__()
            self.layers = torch.nn.Linear(2, 3)
            self.encoder = 4
            self.vocab = Vocab("vocab")

        def forward(self, x):
            name = self.vocab.name
            print("forward show encoder:" + str(self.encoder))
            print("vocab:" + name)
            enc_hidden = []
            step = len(x) // 2
            for i in range(step):
                enc_hidden.append((x[2*i] + x[2*i + 1])/2)
            enc_hidden = torch.stack(enc_hidden, 0)
            enc_hidden = self.__show(enc_hidden)
            return self.layers(enc_hidden)

        @torch.jit.export
        def __show(self, x):
            return x + 1

    model = Model()
    data = torch.randn(10, 2)
    script_model = torch.jit.script(model)
    print(script_model)
    r1 = model(data)
    print(r1)
the error msg:

    Traceback (most recent call last):
      File "/mnt/d/python_projects/pytorch_deploy/model4.py", line 47, in <module>
        script_model = torch.jit.script(model)
      File "/mnt/d/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 1261, in script
        return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
      File "/mnt/d/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 305, in create_script_module
        return create_script_module_impl(nn_module, concrete_type, stubs_fn)
      File "/mnt/d/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 361, in create_script_module_impl
        create_methods_from_stubs(concrete_type, stubs)
      File "/mnt/d/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 279, in create_methods_from_stubs
        concrete_type._create_methods(defs, rcbs, defaults)
     RuntimeError: 
      Module 'Model' has no attribute 'vocab' (This attribute exists on the Python module, but we failed to convert Python type: 'Vocab' to a TorchScript type.):
      File "/mnt/d/python_projects/pytorch_deploy/model4.py", line 26
      def forward(self, x):
        name = self.vocab.name
           ~~~~~~~~~~ <--- HERE
        print("forward show encoder:" + str(self.encoder))
        print("vocab:" + name)
so how can i use my own python object in torchscript?

**Comment by chuanhuayang** [comment]
my pytorch version is：linux , cpu，1.5.0 version

**Comment by eellison** [comment]
Hi, @chuanhuayang, I got your repro working with the following. I'm going to update the issue name here to better reflect the issue. 


```
import torch

@torch.jit.script
class Vocab(object):
    def __init__(self, name: str):
        self.name = name

    def show(self):
        print("dict:" + self.name)

class Model(torch.nn.Module):
    def __init__(self, ):
        super(Model, self).__init__()
        self.layers = torch.nn.Linear(2, 3)
        self.encoder = 4
        self.vocab = Vocab("vocab")

    def forward(self, x):
        name = self.vocab.name
        print("forward show encoder:" + str(self.encoder))
        print("vocab:" + name)
        enc_hidden = []
        step = len(x) // 2
        for i in range(step):
            enc_hidden.append((x[2*i] + x[2*i + 1])/2)
        enc_hidden = torch.stack(enc_hidden, 0)
        enc_hidden = self._show(enc_hidden)
        return self.layers(enc_hidden)

    @torch.jit.export
    def _show(self, x):
        return x + 1

model = Model()
data = torch.randn(10, 2)
script_model = torch.jit.script(model)
print(script_model)
r1 = model(data)
print(r1)
```

**Comment by eellison** [comment]
Also, I had to rename `__show` to `_show`,  issue https://github.com/pytorch/pytorch/issues/39745 here for that.

**Comment by chuanhuayang** [comment]
Yes， thank you for your answer. the `@torch.jit.script` and the `name: str` used for attribute class is worked, do you mean this is a bug and will be fixed in the future?

**Comment by eellison** [comment]
@chuanhuayang , yea those are bugs and will be fixed

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
