### ISSUE TITLE
"RuntimeError: Broken pipe" when using torch.distributed.barrier()

### ISSUE THREAD

**Issue by vgoklani** [pytorch/pytorch#39722]
## 🐛 Bug

Traceback (most recent call last):
  File "test.py", line 53, in <module>
    main()
  File "test.py", line 49, in main
    torch.multiprocessing.spawn(build_model, nprocs=2, args=(args,), join=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/root/src/transformerz/test.py", line 35, in build_model
    torch.distributed.barrier()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1485, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe

## To Reproduce

	"""pytorch test code"""
	import os
	import argparse
	import time
	import torch
	from logger import get_logger

	log = get_logger(__name__)

	def argparser():
		parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
		parser.add_argument('--number-gpus', default=torch.cuda.device_count(), type=int, help='number of gpus per node')
		parser.add_argument('--gpu-rank', default=0, type=int, help='ranking within the nodes')
		parser.add_argument('--nodes', default=1, type=int, help='')

		args = parser.parse_args()
		args.world_size = args.number_gpus * args.nodes
		return args

	def build_model(gpu, args):
		torch.cuda.set_device(gpu)
		log.info(gpu)

		rank = args.gpu_rank * args.number_gpus + gpu
		torch.distributed.init_process_group(
			backend='nccl',
			init_method='env://',
			world_size=args.world_size,
			rank=rank)

		if gpu not in [-1, 0]:
			log.info(f"BARRIER UP -> GPU:{gpu}")
			torch.distributed.barrier()

			time.sleep(10)

			log.info(f"BARRIER DOWN -> GPU:{gpu}")
			torch.distributed.barrier()

	def main():
		os.environ['NCCL_BLOCKING_WAIT'] = '1'
		os.environ['MASTER_ADDR'] = '127.0.0.1'
		os.environ['MASTER_PORT'] = '29500'

		args = argparser()
		torch.multiprocessing.spawn(build_model, nprocs=2, args=(args,), join=True)

	if __name__ == '__main__':
		main()

Please put code snippet above in "test.py" and run via

`python test.py`

running on pytorch v'1.5.0'

installed via conda

on a desktop/workstation with two NVIDIA RTX 6000 cards

## Expected behavior

Expected to see one GPU block and wait for the other to finish working, and then resume. Instead the whole loop breaks with the error code shown above.

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Quadro RTX 6000
GPU 1: Quadro RTX 6000

Nvidia driver version: 440.64
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torch-model-archiver==0.1.0b20200409
[pip3] torchaudio==0.5.0
[pip3] torchserve==0.0.1b20200409
[pip3] torchtext==0.6.0
[pip3] torchvision==0.6.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch                     1.5.0                    pypi_0    pypi
[conda] torch-model-archiver      0.1.0b20200409           pypi_0    pypi
[conda] torchaudio                0.5.0                    pypi_0    pypi
[conda] torchserve                0.0.1b20200409           pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.6.0                    pypi_0    pypi

**Comment by christopherhesse** [comment]
@mrshenli 

Using `torch==1.5.1+cu101` I have seen a similar error and altered your script to reproduce the issue:

```py
import os
import torch

world_size = 2

def _do_useless_allreduce(group):
    # doing this seems to avoid "RuntimeError: Broken pipe" when using a group with a set 
    # of ranks that does not include rank 0
    x = torch.ones((1,), dtype=torch.float32, device="cuda")
    torch.distributed.all_reduce(x, group=group)


def run(gpu):
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    torch.cuda.set_device(gpu)
    print(f"rank = {gpu}")

    torch.distributed.init_process_group(
        backend='nccl',
        init_method='env://',
        world_size=world_size,
        rank=gpu)

    # works
    # group = torch.distributed.new_group(ranks=(0,))
    # print(f"BARRIER UP -> GPU:{gpu}")
    # torch.distributed.barrier(group=group)
    # print(f"BARRIER DOWN -> GPU:{gpu}")

    # fails with RuntimeError: broken pipe
    group = torch.distributed.new_group(ranks=(1,))
    print(f"BARRIER UP -> GPU:{gpu}")
    torch.distributed.barrier(group=group)
    print(f"BARRIER DOWN -> GPU:{gpu}")

    # works
    # _do_useless_allreduce(torch.distributed.group.WORLD)
    # group = torch.distributed.new_group(ranks=(1,))
    # _do_useless_allreduce(group)
    # print(f"BARRIER UP -> GPU:{gpu}")
    # torch.distributed.barrier(group=group)
    # print(f"BARRIER DOWN -> GPU:{gpu}")

def main():
    torch.multiprocessing.spawn(run, nprocs=world_size, join=True)


if __name__ == '__main__':
    main()
```

Do you get `RuntimeError: broken pipe` if you run this script?
