### ISSUE TITLE
Segmentation fault, pytorch version '0.2.0_3'

### ISSUE THREAD

**Issue by amulyahwr** [pytorch/pytorch#3985]
I am receiving an error "Segmentation fault" while using pytorch version '0.2.0_3'. Please anybody can guide me through this error! This is the first time I am receiving this error.

**Trace:**
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffec8ffc700 (LWP 10015)]
0x00007fffda3a7492 in operator[] (this=0x7ffec8ffbc10, __n=0) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_vector.h:780
780	/opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_vector.h: No such file or directory.
(gdb) where
#0  0x00007fffda3a7492 in operator[] (this=0x7ffec8ffbc10, __n=0) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_vector.h:780
#1  torch::autograd::InputBuffer::add(unsigned long, std::shared_ptr<torch::autograd::Variable>&&) (this=this@entry=0x7ffec8ffbc10, pos=pos@entry=0, 
    var=std::shared_ptr (count 1, weak 1) 0x7ffd941525c0) at torch/csrc/autograd/input_buffer.cpp:16
#2  0x00007fffda39a32b in torch::autograd::Engine::evaluate_function (this=this@entry=0x7fffdb6e0b40 <engine>, task=...)
    at torch/csrc/autograd/engine.cpp:215
#3  0x00007fffda39b573 in torch::autograd::Engine::thread_main (this=this@entry=0x7fffdb6e0b40 <engine>, queue=std::shared_ptr (count 3, weak 0) 0x18d5dd10, 
    device=device@entry=0) at torch/csrc/autograd/engine.cpp:117
#4  0x00007fffda3bf417 in PythonEngine::thread_main (this=0x7fffdb6e0b40 <engine>, queue=std::shared_ptr (count 3, weak 0) 0x18d5dd10, device=0)
    at torch/csrc/autograd/python_engine.cpp:23
#5  0x00007fffda39f77a in operator()<std::shared_ptr<torch::autograd::ReadyQueue>, int, void> (__object=<optimized out>, this=<optimized out>)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/functional:569
#6  _M_invoke<0ul, 1ul, 2ul> (this=<optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/functional:1700
#7  operator() (this=<optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/functional:1688
#8  std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (torch::autograd::Engine::*)(std::shared_ptr<torch::autograd::ReadyQueue>, int)> (torch::autograd::Engine*, std::shared_ptr<torch::autograd::ReadyQueue>, int)> >::_M_run() (this=<optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/thread:115
#9  0x00007fffdb19fa20 in execute_native_thread_routine () from /usr/local/lib64/python2.7/site-packages/torch/_C.so
#10 0x00007ffff77eade5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffff6e0e30d in clone () from /lib64/libc.so.6

**Comment by amulyahwr** [comment]
Resolved the issue by removing a bug in the code. Thanks!
