### ISSUE TITLE
Importing librosa is causing pytorch_macos_10_13_py3_test to fail

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#39876]
See https://app.circleci.com/pipelines/github/pytorch/pytorch/179668/workflows/2f657073-2a56-4c0a-bdb1-993085ea257b/jobs/5794714/steps:

```
Jun 11 12:31:15 Running test_cuda ... [2020-06-11 12:31:15.288329]
Jun 11 12:31:17 Traceback (most recent call last):
Jun 11 12:31:17   File "test_cuda.py", line 20, in <module>
Jun 11 12:31:17     from test_torch import AbstractTestCases
Jun 11 12:31:17   File "/Users/distiller/project/test/test_torch.py", line 54, in <module>
Jun 11 12:31:17     import librosa
Jun 11 12:31:17   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/librosa/__init__.py", line 12, in <module>
Jun 11 12:31:17     from . import core
Jun 11 12:31:17   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/librosa/core/__init__.py", line 125, in <module>
Jun 11 12:31:17     from .time_frequency import *  # pylint: disable=wildcard-import
Jun 11 12:31:17   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/librosa/core/time_frequency.py", line 11, in <module>
Jun 11 12:31:17     from ..util.exceptions import ParameterError
Jun 11 12:31:17   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/librosa/util/__init__.py", line 77, in <module>
Jun 11 12:31:17     from .utils import *  # pylint: disable=wildcard-import
Jun 11 12:31:17   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/librosa/util/utils.py", line 15, in <module>
Jun 11 12:31:17     from .decorators import deprecated
Jun 11 12:31:17   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/librosa/util/decorators.py", line 9, in <module>
Jun 11 12:31:17     from numba.decorators import jit as optional_jit
Jun 11 12:31:17 ModuleNotFoundError: No module named 'numba.decorators'
Jun 11 12:31:17 Traceback (most recent call last):
Jun 11 12:31:17   File "test/run_test.py", line 711, in <module>
Jun 11 12:31:17     main()
Jun 11 12:31:17   File "test/run_test.py", line 704, in main
Jun 11 12:31:17     raise RuntimeError(message)
Jun 11 12:31:17 RuntimeError: test_cuda failed!
```

cc @mruberry

**Comment by mruberry** [comment]
Addressed, at least temporarily, by https://github.com/pytorch/pytorch/pull/39875#event-3436044623
