### ISSUE TITLE
Cannot open Spyder

### ISSUE THREAD

**Issue by zihanw4** [pytorch/pytorch#40116]
I'm pretty new to python, and just starting learning it with some books. One of the books recommended me to install anaconda, so I followed. When I was exploring the functions, I found that every time I try to turn on the Spyder, it comes up something like this.
Traceback (most recent call last):
File "D:\ANACONDA3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "D:\ANACONDA3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "D:\ANACONDA3\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "D:\ANACONDA3\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "D:\ANACONDA3\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 141, in start
self.kite_process = run_program(path)
File "D:\ANACONDA3\lib\site-packages\spyder\utils\programs.py", line 214, in run_program
return subprocess.Popen(fullcmd, **subprocess_kwargs)
File "D:\ANACONDA3\lib\subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "D:\ANACONDA3\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Pretty confused and hopefully can get some guidance. 

Thanks

cc @peterjc123 @nbcsm @guyang3532

**Comment by malfet** [comment]
@zihanw4 why do you think this is a PyTorch issue? Looks like the Spyder issue, which should be filed against https://github.com/spyder-ide/spyder ?
