### ISSUE TITLE
caffe2 error during compilation of PyTorch with ROCm on Archlinux

### ISSUE THREAD

**Issue by chiboreache** [pytorch/pytorch#40269]
aur package: _python-pytorch-cuda-git_ `ROCM=ON`

```sh

:: Downloading the latest sources for a devel package python-pytorch-cuda-git...

:: Starting the build:
==> Making package: python-pytorch-git 1.3.1.r27648.02e091902f6-1 (Fri Jun 19 07:52:01 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Updating pytorch git repo...
Fetching origin
==> Validating source files with sha512sums...
pytorch ... Skipped
==> Extracting sources...
-> Creating working copy of pytorch git repo...
Reset branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Building without cuda and without MKL-DNN
Building wheel torch-1.3.1
-- Building version 1.3.1
cmake --build . --target install --config Release -- -j 8
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
File "setup.py", line 732, in <module>
build_deps()
File "setup.py", line 311, in build_deps
build_caffe2(version=version,
File "/home/chibo/.cache/pikaur/build/python-pytorch-git/src/pytorch-git/tools/build_pytorch_libs.py", line 62, in build_caffe2
cmake.build(my_env)
File "/home/chibo/.cache/pikaur/build/python-pytorch-git/src/pytorch-git/tools/setup_helpers/cmake.py", line 345, in build
self.run(build_args, my_env)
File "/home/chibo/.cache/pikaur/build/python-pytorch-git/src/pytorch-git/tools/setup_helpers/cmake.py", line 141, in run
check_call(command, cwd=self.build_dir, env=env)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.
==> ERROR: A failure occurred in build().
Aborting...
```

cc @malfet @zklaus @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @jataylo @hongxiayang @naromero77amd @pragupta @jerrymannil @xinyazhang

**Comment by vincentqb** [comment]
Can you provide more information about the steps required to reproduce this error? Please also copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py). You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by chiboreache** [comment]
>steps required to reproduce this error

1. `aur python-pytorch-cuda-git`

>get the script and run

 ```sh
↪ python collect_env.py
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Arch Linux
GCC version: (GCC) 10.1.0
CMake version: version 3.17.3

Python version: 3.8
Is CUDA available: No
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] Could not collect
```

ps: `aur` is just `alias aur='pikaur -S'` in fish

**Comment by chiboreache** [comment]
tryed installing via yay, and get more valuable errors

```sh
Could not find a package configuration file provided by "rocrand" with any
of the following names:

rocrandConfig.cmake
rocrand-config.cmake
```

full
---

```sh


***** Library versions from cmake find_package *****

CMake Error at cmake/public/LoadHIP.cmake:131 (find_package):
By not providing "Findrocrand.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "rocrand", but
CMake did not find one.

Could not find a package configuration file provided by "rocrand" with any
of the following names:

rocrandConfig.cmake
rocrand-config.cmake

Add the installation prefix of "rocrand" to CMAKE_PREFIX_PATH or set
"rocrand_DIR" to a directory containing one of the above files.  If
"rocrand" provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first):
cmake/public/LoadHIP.cmake:167 (find_package_and_print_version)
cmake/Dependencies.cmake:1093 (include)
CMakeLists.txt:469 (include)


-- Configuring incomplete, errors occurred!
See also "/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git/build/CMakeFiles/CMakeOutput.log".
See also "/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
File "setup.py", line 734, in <module>
build_deps()
File "setup.py", line 313, in build_deps
build_caffe2(version=version,
File "/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git/tools/build_pytorch_libs.py", line 54, in build_caffe2
cmake.generate(version,
File "/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git/tools/setup_helpers/cmake.py", line 329, in generate
self.run(args, env=my_env)
File "/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git/tools/setup_helpers/cmake.py", line 141, in run
check_call(command, cwd=self.build_dir, env=env)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python3.8/site-packages', '-DNUMPY_INCLUDE_DIR=/usr/lib/python3.8/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_LIBRARY=/usr/lib/libpython3.8.so.1.0', '-DTORCH_BUILD_VERSION=1.7.0a0+eebd492', '-DUSE_CUDA=OFF', '-DUSE_CUDNN=OFF', '-DUSE_MKLDNN=OFF', '-DUSE_MKLDNN_CBLAS=OFF', '-DUSE_NCCL=OFF', '-DUSE_NUMPY=True', '/home/chibo/.cache/yay/python-pytorch-git/src/pytorch-git']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
Aborting...
error making: %!s(func() string=0x562ba7d06ed0)
```
