### ISSUE TITLE
Py pip installation error,zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cudnn64_7.dll

### ISSUE THREAD

**Issue by LJWxyz** [pytorch/pytorch#40268]
## 🐛 Bug

Py3.7 Installation,
:zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cudnn64_7.dll

## To Reproduce
get py 3.7,create a venv ,pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html

ERROR: Exception:
Traceback (most recent call last):
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\operations\prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\operations\prepare.py", line 164, in unpack_http_url
    unpack_file(from_path, location, content_type)
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\utils\unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\site-packages\pip\_internal\utils\unpacking.py", line 139, in unzip_file
    shutil.copyfileobj(fp, destfp)
  File "e:\coding\pyfastcache\pyvenv\venv37_gpuacc\lib\shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "E:\Coding\Python3.7.4\Lib\zipfile.py", line 899, in read
    data = self._read1(n)
  File "E:\Coding\Python3.7.4\Lib\zipfile.py", line 989, in _read1
    self._update_crc(data)
  File "E:\Coding\Python3.7.4\Lib\zipfile.py", line 917, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cudnn64_7.dll'

win 10_py3.7 venv:

(Venv37_gpuacc) E:\Coding\PYSourceCode\torch>collect_env.py
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 425.45
cuDNN version: E:\NvidiaGPUtool\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect

cc @ezyang @seemethere @malfet @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
Looks like the binary is corrupted. Could you please download it again?

**Comment by ezyang** [comment]
Also the version of torch is quite old.

**Comment by ezyang** [comment]
Please reopen the issue if redownloading the wheel doesn't fix the problem

**Comment by LJWxyz** [comment]
still have the problem,request reopen.^^. Thanks for the fast feedback.

**Comment by peterjc123** [comment]
You could try `pip download xxx` instead of `pip install xxx`. And then please calculate the checksum(e.g sha1, md5).

**Comment by peterjc123** [comment]
```CMD
C:\Users\XXX\Downloads>certutil -hashfile torch-1.5.1-cp37-cp37m-win_amd64.whl MD5
MD5 hash of torch-1.5.1-cp37-cp37m-win_amd64.whl:
cdc36eb1e21df23b025bae3cb21999c7
CertUtil: -hashfile command completed successfully.

C:\Users\XXX\Downloads>certutil -hashfile torch-1.5.1-cp37-cp37m-win_amd64.whl SHA1
SHA1 hash of torch-1.5.1-cp37-cp37m-win_amd64.whl:
40abdd26d859c270960f11698870962abec6800d
CertUtil: -hashfile command completed successfully.
```

**Comment by nbcsm** [comment]
you may also want to try the `no-cache` option, wondering whether it is caused by a corrupted ache.

`pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html --no-cache`

**Comment by mjack3** [comment]
(venv) jack3@jack3-System-Product-Name:~/tkh-projects/02-AD/code/TKHAD_Industry$ pip3 install torch==1.11.0+cu113 --extra-index-url https://download.pytorch.org/whl/cu113 --no-cache
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch==1.11.0+cu113
  Downloading https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp310-cp310-linux_x86_64.whl (1637.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 GB 75.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in ./venv/lib/python3.10/site-packages (from torch==1.11.0+cu113) (4.3.0)
Installing collected packages: torch
ERROR: Exception:
Traceback (most recent call last):
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 461, in run
    installed = install_given_reqs(
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 790, in install
    install_wheel(
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 727, in install_wheel
    _install_wheel(
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 587, in _install_wheel
    file.save()
  File "/home/jack3/tkh-projects/02-AD/code/TKHAD_Industry/venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.10/zipfile.py", line 925, in read
    data = self._read1(n)
  File "/usr/lib/python3.10/zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "/usr/lib/python3.10/zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/libtorch_cuda_cpp.so'
