### ISSUE TITLE
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error

### ISSUE THREAD

**Issue by Tramac** [pytorch/pytorch#40273]
When I startup a distributed training task with 1 nodes, but got NCCL RuntimeError:
```
XXX:430:430 [0] NCCL INFO NET/Socket : Using [0]xgbe0:10.89.245.11<0>
XXX:430:430 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
XXX:430:430 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
NCCL version 2.4.2+cuda9.0
XXX:431:431 [1] NCCL INFO NET/Socket : Using [0]xgbe0:10.89.245.11<0>
XXX:431:431 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
XXX:431:431 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.

XXX:430:2237 [0] include/topo.h:27 NCCL WARN Could not find real path of /sys/class/pci_bus/0000:02/../../0000:02:00.0
XXX:430:2237 [0] NCCL INFO init.cu:864 -> 2
XXX:430:2237 [0] NCCL INFO init.cu:887 -> 2
XXX:430:2237 [0] NCCL INFO init.cu:911 -> 2
XXX:430:2237 [0] NCCL INFO misc/group.cu:69 -> 2 [Async thread]
Traceback (most recent call last):
  File "distributed_data_parallel.py", line 55, in <module>
    output_device=args.local_rank)
  File "/home/XXX/python3_env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__

XXX:431:2239 [1] include/topo.h:27 NCCL WARN Could not find real path of /sys/class/pci_bus/0000:03/../../0000:03:00.0
XXX:431:2239 [1] NCCL INFO init.cu:864 -> 2
XXX:431:2239 [1] NCCL INFO init.cu:887 -> 2
    self.broadcast_bucket_size)
XXX:431:2239 [1] NCCL INFO init.cu:911 -> 2
XXX:431:2239 [1] NCCL INFO misc/group.cu:69 -> 2 [Async thread]
  File "/home/XXX/python3_env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error
```
Environment
-------------
```
pytorch 1.1.0
cuda 9.0
NCCL 2.4.2
python 3.6
```
script
--------------
```
#!/bin/bash
gpus=0,1
gpun=2

export NCCL_DEBUG=INFO
export NCCL_SOCKET_IFNAME='xgbe0'
export NCCL_IB_DISABLE=1

CUDA_VISIBLE_DEVICES=$gpus python3 -m torch.distributed.launch --nproc_per_node=$gpun distributed_data_parallel.py
```
The script comes from: https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed

I have tried:
--------
```
python3 -m torch.distributed.launch --nnodes=1 --nproc_per_node=$gpun --master_addr=my_ip --master_port=9999 distributed_data_parallel.py
```
```
export NCCL_SOCKET_IFNAME='xgbe0'
```
This error always exists, plz help!!!

**Comment by snash4** [comment]
Hi Tramac, 
Were you able to fix the error?
