### ISSUE TITLE
from torch._C import default_generator ImportError: cannot import name 'default_generator'

### ISSUE THREAD

**Issue by forgetso** [pytorch/pytorch#40295]
## 🐛 Bug

I cloned the torch repository and compiled it myself so that it would run with rocm. After about 3 hours, when I tested it, it failed not being able to import something called default_generator.

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/pytorch/torch/__init__.py", line 315, in <module>
    from .random import set_rng_state, get_rng_state, manual_seed, initial_seed, seed
  File "/data/pytorch/torch/random.py", line 4, in <module>
    from torch._C import default_generator
ImportError: cannot import name 'default_generator'
```

## To Reproduce

```
clone pytorch
cd pytorch
git submodule init
git submodule update
pytorch/tools/amd_build.py
USE_ROCM=1 MAX_JOBS=4 python setup.py install --user
```

Checking the pytorch github (torch/_C/__init__.pyi.in)  I can see that there is the following line 165:

```
_GLIBCXX_USE_CXX11_ABI: _bool
default_generator: Generator
```
The default_generator line is missing from my torch/_C/__init__.pyi.in.

## Expected behavior

After compiling and installing pytorch, I will be able to use it without ImportErrors.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.1                      217  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.18.1           py36h4f9e942_0  
[conda] numpy-base                1.18.1           py36hde5b4d6_1

```
 - Any other relevant information:
I am using ROCM (rocminfo output below):
```
jenkins@865e51bab284:~$ rocminfo
sh: 1: lsmod: not found
ROCk module is NOT loaded, possibly no GPU devices
Able to open /dev/kfd read-write
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD FX(tm)-8350 Eight-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD FX(tm)-8350 Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      16384(0x4000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            8                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32970308(0x1f71644) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32970308(0x1f71644) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx701                             
  Uuid:                    GPU-XX                             
  Marketing Name:          Device 67b0                        
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26544(0x67b0)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1000                               
  BDFID:                   256                                
  Internal Node ID:        1                                  
  Compute Unit:            44                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304(0x400000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx701          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                FALSE                              
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```

cc @malfet @jeffdaily @sunway513

**Comment by ezyang** [comment]
In the past, there has been trouble with ROCm compiler where it fails but it still returns exit code 0. Check your full build log to see if there are any error messages.

**Comment by forgetso** [comment]
Thanks for replying. Is the build log stored anywhere or does it only appear in the terminal? I've not been able to find it in the pytorch build folder and I can't see any errors in the last 1000 lines of build in the terminal.

FYI - I have since tried the build again on Ubuntu 16 and get the same error. collect_py output below:

```
Collecting environment information...
PyTorch version: 1.6.0a0+c73095e
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 16.04.6 LTS
GCC version: Could not collect
CMake version: version 3.6.3

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.6.0a0+5092323
[pip3] torchvision==0.6.0a0+43e94b3
[conda] Could not collect

```

**Comment by forgetso** [comment]
I've rerun the build and attached the log output. I can't see any mention of errors. Just lots of warnings. The same thing happens when I try to import torch.

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/pytorch/torch/__init__.py", line 315, in <module>
    from .random import set_rng_state, get_rng_state, manual_seed, initial_seed, seed
  File "/data/pytorch/torch/random.py", line 4, in <module>
    from torch._C import default_generator
ImportError: cannot import name 'default_generator'
```
The tests fail with the following:

```
frame #63: _PyObject_Call_Prepend + 0x24c (0x4e839c in /usr/bin/python3.6)

Traceback (most recent call last):
  File "test/run_test.py", line 721, in <module>
    main()
  File "test/run_test.py", line 714, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed! Received signal: SIGIOT

```

[log.txt](https://github.com/pytorch/pytorch/files/4807564/log.txt)

**Comment by jeffdaily** [comment]
If you try to import torch while inside the top level pytorch source tree it will import the torch directory and not the installed torch module.  Try changing your current working directory and see if the issue resolves.

**Comment by jeffdaily** [comment]
What was your command to start run_test.py?  Our CI script will execute .jenkins/pytorch/test.sh which sets the env var PYTORCH_TEST_WITH_ROCM to skip certain tests that aren’t relevant to our platform or are known to fail.

**Comment by forgetso** [comment]
I've scrapped the VM that I used earlier. I'll try rerunning the build script again now and let you know what happens after I've reinstalled torch. 

The command I used for the testing was:

`PYTORCH_TEST_WITH_ROCM=1 python test/run_test.py --verbose`

**Comment by forgetso** [comment]
Importing torch from outwith /data/pytorch has worked - thanks! The tests still fail.

```
Running test_autograd ... [2020-06-20 18:03:57.239323]
test_accumulate_grad (__main__.TestAutograd) ... terminate called after throwing an instance of 'c10::Error'
  what():  HIP error: hipErrorNoDevice (deviceCount at /root/pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:98)
```
Is this to do with me using a gfx701 graphics card and it not being supported by OpenCL 2.0? I found the following elsewhere:

> It should not be reporting support for gfx701 since gfx701 simply doesn't have the required capabilities to support device enqueue on ROCm. Now, it turns out that other 2.0 features can be used, but we don't report 2.0 unless all the 2.0 features work.
[Source](https://github.com/jjhelmus/berryconda/issues/58)

**Comment by hongxiayang** [comment]
This issue needs to be closed as it is too old
