### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by gautamkmr** [pytorch/pytorch#40403]
## 🐛 Bug

I am getting CUDA re-initialize error.  
I am using below code to generate synthetic dataset on GPU. To perform distributed training I am using [official PyTorch distributed training helper](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) script.
```
import random
import torch
import torch.utils.data as data


class DummyDataset(data.Dataset):
    def __init__(self, num_classes):
        super(DummyDataset, self).__init__()
        # Create tensor on GPU 
        self.tensor = torch.randn(3, 224, 224, device=torch.device('cuda'))
        self.num_classes = num_classes

    def __getitem__(self, index):
        torch.manual_seed(index)
        random.seed(index)
        return self.tensor, \
               random.randint(0, self.num_classes - 1)
```
It throws following error 

```
in execute
    class_targets) in enumerate(train_dataset_loader):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/usr/local/lib/python3.6/site-packages/torch/storage.py", line 126, in _new_shared
    return cls(size)
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 477, in _lazy_new
    _lazy_init()
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

```
I tried to follow the workaround mentioned in this [discussion](https://discuss.pytorch.org/t/runtimeerror-cannot-re-initialize-cuda-in-forked-subprocess-to-use-cuda-with-multiprocessing-you-must-use-the-spawn-start-method/14083/6) and changed my `DummyDataSet` class as follows

```
import random
import torch
torch.multiprocessing.set_start_method('spawn')# good solution !!!!
import torch.utils.data as data


class DummyDataset(data.Dataset):
    def __init__(self, num_classes):
        super(DummyDataset, self).__init__()
        # Create tensor on GPU 
        self.tensor = torch.randn(3, 224, 224, device=torch.device('cuda'))
        self.num_classes = num_classes

    def __getitem__(self, index):
        time.sleep(0.1);# !!!!!! In order to test, should be have virtual process time !!!!!!
        torch.manual_seed(index)
        random.seed(index)
        return self.tensor, \
               random.randint(0, self.num_classes - 1)
```
This gives another error 
```
  File "/pytorch_sample/dummy_data.py", line 3, in <module>
    torch.multiprocessing.set_start_method('spawn')# good solution !!!!
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/local/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/usr/local/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1108) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
````

I am 
## Environment
```
Collecting environment information...
PyTorch version: 1.4.0a0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.4.0a0
[pip3] torchvision==0.5.0a0
[conda] Could not collect
```

## Additional context

cc @ngimel @SsnL @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by gautamkmr** [comment]
Similar issue was reported [here](https://github.com/pytorch/pytorch/issues/1494)

**Comment by zou3519** [comment]
This is a known issue with the CUDA runtime: https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing. As you've noted, the workaround is to use the `spawn` start method.

Do you have a step-by-step repro for the problem?

**Comment by ngimel** [comment]
cc @VitalyFedyunin

**Comment by gautamkmr** [comment]
> Do you have a step-by-step repro for the problem? I am not sure if this is a user problem or if there is some problem with torch.distributed.launch

using following dataset with [official script](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) will reproduce.

```
import random
import torch
import torch.utils.data as data

class DummyDataset(data.Dataset):
    def __init__(self, num_classes):
        super(DummyDataset, self).__init__()
        # Create tensor on GPU 
        self.tensor = torch.randn(3, 224, 224, device=torch.device('cuda'))
        self.num_classes = num_classes

    def __getitem__(self, index):
        torch.manual_seed(index)
        random.seed(index)
        return self.tensor, \
               random.randint(0, self.num_classes - 1)
```

**Comment by mrshenli** [comment]
cc distributed oncall @agolynski

**Comment by mrshenli** [comment]
Hey @gautamkmr what are the arguments you passed to the launching script?

**Comment by SsnL** [comment]
Yeah, you should just user spawn @gautamkmr . Closing since this looks like user error.

**Comment by ngimel** [comment]
In original issue, second attempt uses spawn:
```
torch.multiprocessing.set_start_method('spawn')# good solution !!!!
```
but it still leads to an error. Could be user error.

**Comment by mrshenli** [comment]
Reopening as this seem to relate to `torch.distributed` launching script, which uses `subprocess.Popen` to create subprocesses and does not create CUDA context. So even if the `Popen` is implemented using fork instead of spawn, it should work.

To reproduce, we will need the arguments @gautamkmr passed to the launching script.

**Comment by gautamkmr** [comment]
well the argument is very simple 
```
python launch.py --nproc_per_node=8 --fp16 train.py
```

In `train.py` I have pasted basic code that is needed to reproduce it. 

```
if __name__=="__main__":
    args = parse_args()

    torch.cuda.set_device(args.gpu)

    # Initialize distributed communication
    torch.distributed.init_process_group(backend='nccl',
                                         init_method="env://",
                                         world_size=world_size)


    # Define bunch of variables

    dataset = DummyDataset(num_classes=num_classes)
    model = ImageNetClassifier(
        num_classes=num_classes,
        ignore_label=ignore_label,
        label_smoothing=label_smoothing,
        base_model="resnet50"
    )
    print('Finish instantiating model')
    
    # Run training loop below 
```

**Comment by gautamkmr** [comment]
> Yeah, you should just use spawn @gautamkmr . Closing since this looks like user error.

`spawn` did not work. I am also curious how do you use spawn in [official script](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py)  I think if this is workaround probably we should add that part in `launch.py` as well.

**Comment by SsnL** [comment]
@gautamkmr `set_start_method('spawn')` should be inside `if __name__ == '__main__'`. It really is not relevant to `launch.py` but just how you should use multiprocessing data loader with CUDA tensors. Alternatively, you could just set `multiprocessing_context='spawn'` when creating the data loader.

**Comment by gautamkmr** [comment]
So I tried with following code block in `launch.py` and its still same issue. 

```
if __name__ == "__main__":
    torch.multiprocessing.set_start_method('spawn')# good solution !!!!
    main()
```

**Comment by gautamkmr** [comment]
ok so I made `pin_memory=False` which lead to following error 
```
RuntimeError: Attempted to set the storage of a tensor on device "cuda:5" to a storage on different device "cuda:0".  This is no longer allowed; the devices must match.

```

**Comment by gautamkmr** [comment]
Is this something not supported ? or it was supported but not anymore ?

**Comment by TAOSHss** [comment]
`Traceback (most recent call last):
  File "training.py", line 233, in <module>
    main()
  File "training.py", line 230, in main
    train(config)
  File "training.py", line 89, in train
    for step, samples in enumerate(dataloader):
  File "/home/intern1/anaconda3/envs/airiacvlib/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/intern1/anaconda3/envs/airiacvlib/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/intern1/anaconda3/envs/airiacvlib/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/intern1/anaconda3/envs/airiacvlib/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/intern1/anaconda3/envs/airiacvlib/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/intern1/anaconda3/envs/airiacvlib/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/intern1/taosihui/YOLOv3_PyTorch-master/training/../common/coco_dataset.py", line 54, in __getitem__
    sample = self.transforms(sample)
  File "/home/intern1/taosihui/YOLOv3_PyTorch-master/training/../common/data_transforms.py", line 20, in __call__
    img = t(img)
  File "/home/intern1/taosihui/YOLOv3_PyTorch-master/training/../common/data_transforms.py", line 100, in __call__
    image = cv2.resize(image, self.new_size, interpolation=self.interpolation)
TypeError: Expected Ptr<cv::UMat> for argument 'src'
`
I continuously use the torch utils. Data. DataLoader will quote this error twice, it cause I can't to training and validation program

**Comment by VitalyFedyunin** [comment]
Are you using same code snippet as before to get this error? 

If so, you might try to pass `args.gpu` device to `self.tensor = torch.randn(3, 224, 224, device=torch.device('cuda'))` this function.

**Comment by Mon-ius** [comment]
I meet the same error months ago. Because I mixed the CPU operation and GPU operation inside the dataloader procedure. 

To avoid the error for simplicity, Call `DataLoader` with parameter `num_workers=0`.  

For example:
```
DataLoader(train_dataset, shuffle=True, batch_size=batch_size, num_workers=0)
```


In my suggestions, you have two ways to fix your code with multi-process during the data loading procedure: 
1. running all related codes in CPU mode.
2. running all related codes in GPU mode.
Then, you can do `DataLoader(train_dataset, shuffle=True, batch_size=batch_size, num_workers=128)`, etc.

Considering, Nvidia A100 80GB is just released. Maybe the first one can help to fix the problem in practice.

**Comment by Sentient07** [comment]
I had the same issue and it was resolved by `not` placing the tensors on GPU from within the `Dataset` class. Hope that helps

**Comment by agirbau** [comment]
I had the same issue (fork not working, spawn not recognizing common variables). To solve it, I did a workaround it by placing all the common variables outside \_\_main\_\_, as explained [here](https://newbedev.com/workaround-for-using-name-main-in-python-multiprocessing), as it seems that when doing "spawn" a new Python process is started from scratch, and would not import the things initialized in \_\_main\_\_. Hope it helps!

**Comment by pengzhi1998** [comment]
@goswamig Hi! When I do:
`torch.multiprocessing.set_start_method('spawn')
`
I'll face another problem: TypeError: can't pickle _thread.lock objects. Do you have any suggestions? Thank you!

**Comment by chh7411898** [comment]
I have the same problem. How did you solve it at last
I try to set workers=0 ,But it slows down the training speed

**Comment by VitalyFedyunin** [comment]
@[chh7411898](https://github.com/chh7411898) You probably initialize some structures before the training loop. It is very hard to tell what is going on exactly without seeing all code. In short - make sure there is no tensors created before calling DataLoader.

**Comment by taylover-pei** [comment]
> 

Have you solved it?

**Comment by taylover-pei** [comment]
> @goswamig Hi! When I do: `torch.multiprocessing.set_start_method('spawn') ` I'll face another problem: TypeError: can't pickle _thread.lock objects. Do you have any suggestions? Thank you!

Have you solved it?

**Comment by pengzhi1998** [comment]
Sorry I didn't. I just used single process at last.

**Comment by VitalyFedyunin** [comment]
Yes. Several options:
1) Use `spawn` method.
2) Do not do any GPU operations inside of the Dataset __init__ and inside of the main code, move everything into __get_iterm__ or __iter__

**Comment by ngocdung03** [comment]
I recently encountered this error with Pytorch Lightning, but I think it is a Pytorch issue under the hood. `torch.multiprocessing.set_start_method('spawn')` does not work for me. Lately I discovered that I should set `num_workers = 0`.  `num_workers` > 0 works well for CPU. However, when I ran the model in a GPU available environment, things messed up.

**Comment by emerygoossens** [comment]
I have this issue because the length of my inputs are varied.

Hacky Workaround: Set num_workers=0 and batch_size=1. To up the effective batch size to say, 32, you can then use accumulate_grad_batches=32 in the pl.Trainer class.

Anyone else have a better solution?

**Comment by skkodali** [comment]
I am also having the same issue. When i ran the inference in a GPU, getting the error `Cannot re-initialize CUDA in forked subprocess`. When i try to set the `multiprocessing.set_start_method('spawn')`, i was getting `context has already been set` as i was using `multiprocessing.Lock()` which is setting the context by default to `fork()`. The only thing that worked for me was to run the model on `cpu` mode. Is there any workaround to use `gpu` mode.

**Comment by leedrake5** [comment]
No solution to contribute, but do want to note that this is still an issue

**Comment by majidAdibian77** [comment]
> @gautamkmr `set_start_method('spawn')` should be inside `if __name__ == '__main__'`. It really is not relevant to `launch.py` but just how you should use multiprocessing data loader with CUDA tensors. Alternatively, you could just set `multiprocessing_context='spawn'` when creating the data loader.

In my code, I added `torch.multiprocessing.set_start_method('spawn')` on top of python file but was getting `context has already been set` error. But when I move it to `if __name__ == '__main__`  scope, the error is gone and the code worked well!

**Comment by wangqiim** [comment]
<img width="383" alt="未命名1675863949" src="https://user-images.githubusercontent.com/59993523/217547425-367bdf80-7bf3-4f57-9958-c33d99174b1b.png">

```python
multiprocessing.set_start_method('spawn', force=True)
```

**Comment by alexlatif** [comment]
@wangqiim your code does force the spawn correctly but then this error occurs inside the Dataset / Dataloader

  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'Dataset' on <module '__main__' (built-in)>

i believe this type of idea would fix

if __name__ == '__main__':
    # Set start method to 'spawn'
    multiprocessing.set_start_method('spawn', force=True)
    
    # Create pool of workers
    with multiprocessing.Pool(MAX_WORKERS) as pool:
        # Run parallel processes
        pool.map(process_data, data_list)
        
   which makes sense, but it all seems overly complex given the desired interface simplicity of torch.device("cuda:0")

**Comment by phdykd** [comment]
I am on Azure Databricks and using 13.0nc12s_v3 Cluster. I am using pytorch_lightning library.

This is the error I am getting :"RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method".

I used this one :"

import torch.multiprocessing as mp
mp.set_start_method('spawn', force=True)

from pytorch_lightning.callbacks import EarlyStopping
", but still getting the same issue. Any solution?

Thanks

**Comment by MarcBresson** [comment]
@VitalyFedyunin  
> Yes. Several options:
> 
>     1. Use `spawn` method.
>     2. Do not do any GPU operations inside of the Dataset **init** and inside of the main code, move everything into **get_iterm** or **iter**

option 2. does not seem to be right according to my own experience and to https://github.com/pytorch/pytorch/issues/40403#issuecomment-943878223. 

However, is it still an ongoing issue ? I have a piece of code that works perfectly on my laptop (with a NVIDIA GPU), but when I try the same code on my school's supercomputer that has a VM with a single GPU, it doesn't.

**Comment by ElizabethCappon** [comment]
When using Celery, set `celery -A tasks worker --pool=threads`. Using `--pool=solo` will also solve the cuda error, but makes Celery's `control.inspect()` return None.

I got this error using torch and Transformers in a FastAPI+Celery+Redis environment. It kept popping up when calling Transformers `TrainingArguments()`. I've tried setting `torch.mulitprocessing('spawn', force=True)` on top of all my scripts and after `if __name__ == '__main__':
`. But the same error kept showing. I've tried setting `dataloader_num_workers` to 0 in `TrainingArguments()` and setting uvicorn's `workers=1`, but also to no avail. Took me 2 days to figure this out...

**Comment by Dev-Gaju** [comment]
when I add `import torch.multiprocessing as mp
mp.set_start_method('spawn')` and remove `precision=16` this code `trainer = pl.Trainer(accelerator="gpu", devices=2, max_epochs=2)`workes for me.

**Comment by 751K** [comment]
I had the same problem, and while setting to spawn worked for me, it caused a huge memory overhead in my code and greatly affected my training speed

**Comment by bingwork** [comment]
FYI，setting num_workers=0, pin_memory=False in dataloader works for me.

**Comment by kerkathy** [comment]
Just for anyone who's stupid like me. Accidentally running a script by `python <script.py>` but not `accelerate launch <script.py>` might also cause this error.

**Comment by ovo-Tim** [comment]
> when I add `import torch.multiprocessing as mp mp.set_start_method('spawn')` and remove `precision=16` this code `trainer = pl.Trainer(accelerator="gpu", devices=2, max_epochs=2)`workes for me.

Not work for me:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/tim/tim/wqx/train.py", line 13, in <module>
    mp.set_start_method('spawn')
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
^C
Detected KeyboardInterrupt, attempting graceful shutdown ...
Traceback (most recent call last):
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 961, in _run
    call._call_callback_hooks(self, "on_fit_start")
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 218, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/callbacks/lr_finder.py", line 130, in on_fit_start
    self.lr_find(trainer, pl_module)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/callbacks/lr_finder.py", line 113, in lr_find
    self.optimal_lr = _lr_find(
                      ^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/tuner/lr_finder.py", line 278, in _lr_find
    _try_loop_run(trainer, params)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/tuner/lr_finder.py", line 523, in _try_loop_run
    loop.run()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 197, in run
    self.setup_data()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 263, in setup_data
    iter(self._data_fetcher)  # creates the iterator inside the fetcher
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 104, in __iter__
    super().__iter__()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 51, in __iter__
    self.iterator = iter(self.combined_loader)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 351, in __iter__
    iter(iterator)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 92, in __iter__
    super().__iter__()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 43, in __iter__
    self.iterators = [iter(iterable) for iterable in self.iterables]
                      ^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    self._iterator = self._get_iterator()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__
    w.start()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/tim/wqx/train.py", line 126, in <module>
    lr_find_results = tuner.lr_find(model,
                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/tuner/tuning.py", line 180, in lr_find
    self._trainer.fit(model, train_dataloaders, val_dataloaders, datamodule)
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 60, in _call_and_handle_interrupt
    trainer._teardown()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1008, in _teardown
    loop.teardown()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 411, in teardown
    self._data_fetcher.teardown()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 79, in teardown
    self.reset()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 141, in reset
    super().reset()
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 75, in reset
    self.length = sized_len(self.combined_loader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/fabric/utilities/data.py", line 51, in sized_len
    length = len(dataloader)  # type: ignore [arg-type]
             ^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.12.5/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 358, in __len__
    raise RuntimeError("Please call `iter(combined_loader)` first.")
RuntimeError: Please call `iter(combined_loader)` first.

**Comment by Little-Podi** [comment]
> @[chh7411898](https://github.com/chh7411898) You probably initialize some structures before the training loop. It is very hard to tell what is going on exactly without seeing all code. In short - make sure there is no tensors created before calling DataLoader.

I solved my issue by following this guide. The problem for me was caused by a torch.Tensor that was preloaded into my dataset. I finally fixed it by adding `map_location="cpu"` to torch.load().

**Comment by ngimel** [comment]
closing the issue, as this is expected behavior. Please open new issues if there are bugs.
