### ISSUE TITLE
TypeError: len() of a 0-d tensor

### ISSUE THREAD

**Issue by JsPassion** [pytorch/pytorch#40432]
Hi,
Kindly help me to solve the error arising due to assert len(..) = len(..) stmt which was initially written using torch 0.2.0 torchvision 0.1.9 but is causing an issue in torch 1.5.1 torchvision 0.5.0 (for compatibility with cuda 10.1).

Traceback (most recent call last):
  File "./main.py", line 186, in <module>
    cuda=cuda
  File "/home/js/GR/train.py", line 102, in train
    collate_fn=collate_fn,
  File "/home/js/GR/dgr.py", line 130, in train_with_replay
    collate_fn=collate_fn,
  File "/home/js/GR/dgr.py", line 205, in _train_batch_trainable_with_replay
    callback(trainable, progress, batch_index, result)
  File "/home/js/GR/train.py", line 157, in cb
    result['g_loss'], 'generator g loss', iteration, env=env
  File "/home/js/GR/visual.py", line 88, in visualize_scalar
    [name], name, iteration, env=env
  File "/home/js/GR/visual.py", line 93, in visualize_scalars
    assert len(scalars) == len(names)
  File "/home/js/anaconda3/envs/env_con/lib/python3.5/site-packages/torch/tensor.py", line 445, in __len__
    raise TypeError("len() of a 0-d tensor")
TypeError: len() of a 0-d tensor

**Comment by zou3519** [comment]
Please direct any questions to https://discuss.pytorch.org/. We try to have each issue in the issue tracker be a valid issue or feature request.

**Comment by vadimkantorov** [comment]
`torch.tensor(1).numel() == 1`, but `len(torch.tensor(1))` fails. Would it make sense to allow `len` for scalar tensors as well? I use `len(...)` on tensors sometimes for more idiomatic checks than `numel()`

@zou3519 Could you please reopen this and turn it into a feature request?
