### ISSUE TITLE
DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40435]
https://app.circleci.com/pipelines/github/pytorch/pytorch/184408/workflows/fc2c5be1-9269-4d74-9c9d-4f7947f9a2c8/jobs/5971378/steps

```
Jun 22 21:21:42 ======================================================================
Jun 22 21:21:42 ERROR [61.059s]: test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)
Jun 22 21:21:42 ----------------------------------------------------------------------
Jun 22 21:21:42 Traceback (most recent call last):
Jun 22 21:21:42   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jun 22 21:21:42     self._join_processes(fn)
Jun 22 21:21:42   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
Jun 22 21:21:42     self._check_return_codes(elapsed_time)
Jun 22 21:21:42   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
Jun 22 21:21:42     raise RuntimeError(error)
Jun 22 21:21:42 RuntimeError: Processes 3 exited with error code 10
```

```
Jun 22 21:21:37   test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison) ... ERROR:root:Caught exception: 
Jun 22 21:21:37 Traceback (most recent call last):
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
Jun 22 21:21:37     fn()
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 93, in new_test_method
Jun 22 21:21:37     return_value = old_test_method(self, *arg, **kwargs)
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 566, in test_ddp_dist_autograd_local_vs_remote
Jun 22 21:21:37     remote_layer1 = RemoteModule("worker0", nn.Linear, args=(10, 5, False))
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/nn/api/remote_module.py", line 215, in __init__
Jun 22 21:21:37     super().__init__(on, module_cls, args, kwargs)
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/nn/api/remote_module.py", line 137, in __init__
Jun 22 21:21:37     (module_cls, args, kwargs, _module_interface_cls),
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 80, in wrapper
Jun 22 21:21:37     return func(*args, **kwargs)
Jun 22 21:21:37   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 711, in rpc_sync
Jun 22 21:21:37     return fut.wait()
Jun 22 21:21:37 RuntimeError: RPCErr:1:RPC ran for more than 60000 milliseconds and timed out.
Jun 22 21:21:37 exiting process with exit code: 10
Jun 22 21:21:37 Process 3 terminated with exit code 10, terminating remaining processes.
Jun 22 21:21:37 ERROR (61.059s)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley

**Comment by pritamdamania87** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/40495
