### ISSUE TITLE
DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40433]
https://app.circleci.com/pipelines/github/pytorch/pytorch/184408/workflows/fc2c5be1-9269-4d74-9c9d-4f7947f9a2c8/jobs/5971373/steps

```
Jun 23 04:22:14 ======================================================================
Jun 23 04:22:14 ERROR [61.183s]: test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)
Jun 23 04:22:14 ----------------------------------------------------------------------
Jun 23 04:22:14 Traceback (most recent call last):
Jun 23 04:22:14   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jun 23 04:22:14     self._join_processes(fn)
Jun 23 04:22:14   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
Jun 23 04:22:14     self._check_return_codes(elapsed_time)
Jun 23 04:22:14   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
Jun 23 04:22:14     raise RuntimeError(error)
Jun 23 04:22:14 RuntimeError: Processes 3 exited with error code 10
```

```
Jun 23 04:22:08   test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison) ... ERROR:root:Caught exception: 
Jun 23 04:22:08 Traceback (most recent call last):
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
Jun 23 04:22:08     fn()
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 93, in new_test_method
Jun 23 04:22:08     return_value = old_test_method(self, *arg, **kwargs)
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 569, in test_ddp_dist_autograd_local_vs_remote
Jun 23 04:22:08     layer1.weight = remote_layer1.module_rref.to_here().weight
Jun 23 04:22:08 RuntimeError: RPCErr:1:RPC ran for more than 60000 milliseconds and timed out.
Jun 23 04:22:08 exiting process with exit code: 10
Jun 23 04:22:08 ERROR:root:Caught exception: 
Jun 23 04:22:08 Traceback (most recent call last):
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
Jun 23 04:22:08     fn()
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 93, in new_test_method
Jun 23 04:22:08     return_value = old_test_method(self, *arg, **kwargs)
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 574, in test_ddp_dist_autograd_local_vs_remote
Jun 23 04:22:08     ddp_model = DistributedDataParallel(layer2)
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 329, in __init__
Jun 23 04:22:08     self.broadcast_bucket_size)
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 545, in _distributed_broadcast_coalesced
Jun 23 04:22:08     dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
Jun 23 04:22:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:14761
Jun 23 04:22:08 exiting process with exit code: 10
Jun 23 04:22:08 ERROR:root:Caught exception: 
Jun 23 04:22:08 Traceback (most recent call last):
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
Jun 23 04:22:08     fn()
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 93, in new_test_method
Jun 23 04:22:08     return_value = old_test_method(self, *arg, **kwargs)
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 576, in test_ddp_dist_autograd_local_vs_remote
Jun 23 04:22:08     loss.backward()
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
Jun 23 04:22:08     torch.autograd.backward(self, gradient, retain_graph, create_graph)
Jun 23 04:22:08   File "/opt/python/nightly/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
Jun 23 04:22:08     allow_unreachable=True)  # allow_unreachable flag
Jun 23 04:22:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:31108
Jun 23 04:22:08 exiting process with exit code: 10
Jun 23 04:22:08 Process 3 terminated with exit code 10, terminating remaining processes.
Jun 23 04:22:08 ERROR (61.183s)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley

**Comment by mrshenli** [comment]
@mcarilli mentioned that this failure might relate to changes in #40358

**Comment by pritamdamania87** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/40495
