### ISSUE TITLE
DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparisonTensorPipe)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40453]
Similar to #40435, very like this is **not** caused by TensorPipe.

https://app.circleci.com/pipelines/github/pytorch/pytorch/184590/workflows/0a65582a-2068-4803-9bbc-35c220afcf8f/jobs/5978379/steps

https://app.circleci.com/pipelines/github/pytorch/pytorch/184559/workflows/5cfef953-6647-4916-b3ba-ee2c439ae652/jobs/5977287/steps

```
Jun 23 11:43:34 ======================================================================
Jun 23 11:43:34 ERROR [62.283s]: test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparisonTensorPipe)
Jun 23 11:43:34 ----------------------------------------------------------------------
Jun 23 11:43:34 Traceback (most recent call last):
Jun 23 11:43:34   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jun 23 11:43:34     self._join_processes(fn)
Jun 23 11:43:34   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
Jun 23 11:43:34     self._check_return_codes(elapsed_time)
Jun 23 11:43:34   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
Jun 23 11:43:34     raise RuntimeError(error)
Jun 23 11:43:34 RuntimeError: Processes 3 exited with error code 10
```

```
Jun 23 11:43:18   test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparisonTensorPipe) ... ERROR:root:Caught exception: 
Jun 23 11:43:18 Traceback (most recent call last):
Jun 23 11:43:18   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
Jun 23 11:43:18     fn()
Jun 23 11:43:18   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 93, in new_test_method
Jun 23 11:43:18     return_value = old_test_method(self, *arg, **kwargs)
Jun 23 11:43:18   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 571, in test_ddp_dist_autograd_local_vs_remote
Jun 23 11:43:18     layer1.weight = remote_layer1.module_rref.to_here().weight
Jun 23 11:43:18 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jun 23 11:43:18 exiting process with exit code: 10
Jun 23 11:43:18 [W tensorpipe_agent.cpp:491] RPC agent for worker0 encountered error when reading incoming request from worker3: EOF: end of file (this is expected to happen during shutdown)
Jun 23 11:43:18 Process 3 terminated with exit code 10, terminating remaining processes.
Jun 23 11:43:18 ERROR (62.283s)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley @jiayisuse @lw @beauby

**Comment by pritamdamania87** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/40495

**Comment by pritamdamania87** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/40495
