### ISSUE TITLE
Not able to launch tensorboard using pytorch 

### ISSUE THREAD

**Issue by arpitvw** [pytorch/pytorch#40500]
I have installed tensorboard (pip install tensoboard)
but while launching it I am getting below error

folder_path_for_runs> tensorboard --logdir=runs
Traceback (most recent call last):
  File "c:\users\srava\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\srava\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\srava\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\users\srava\anaconda3\lib\site-packages\tensorboard\main.py", line 43, in <module>
    from tensorboard import default
  File "c:\users\srava\anaconda3\lib\site-packages\tensorboard\default.py", line 39, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "c:\users\srava\anaconda3\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 26, in <module>
    from tensorboard import plugin_util
  File "c:\users\srava\anaconda3\lib\site-packages\tensorboard\plugin_util.py", line 27, in <module>
    import markdown
  File "c:\users\srava\anaconda3\lib\site-packages\markdown\__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "c:\users\srava\anaconda3\lib\site-packages\markdown\core.py", line 26, in <module>
    from . import util
  File "c:\users\srava\anaconda3\lib\site-packages\markdown\util.py", line 85, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())
TypeError: entry_points() missing 1 required positional argument: 'name'

i am using pytroch 1.5.0+cu101

**Comment by ziqiaomeng** [comment]
Any follow-ups? I meet the same issue.

**Comment by ChunyunShen** [comment]
I also meet the same issue...how to solve it?

**Comment by arpitvw** [comment]
i am still waiting for any response from team

**Comment by ziqiaomeng** [comment]
> I also meet the same issue...how to solve it?

I solved issues. It is probably caused by the version of Markdown. Do not use the latest version of Markdown. Select an older version.

**Comment by ziqiaomeng** [comment]
> i am still waiting for any response from team
> […](#)

Could see my comments above and have a try

**Comment by ChunyunShen** [comment]
> > I also meet the same issue...how to solve it?
> 
> I solved issues. It is probably caused by the version of Markdown. Do not use the latest version of Markdown. Select an older version.

changing the version of Markdown from 3.2.2 to 3.1.1 is Ok. Thanks!

**Comment by HaixiongLi** [comment]
> > I also meet the same issue...how to solve it?
> 
> I solved issues. It is probably caused by the version of Markdown. Do not use the latest version of Markdown. Select an older version.

how to change the version of markdown？

**Comment by ChunyunShen** [comment]
> > > I also meet the same issue...how to solve it?
> > 
> > 
> > I solved issues. It is probably caused by the version of Markdown. Do not use the latest version of Markdown. Select an older version.
> 
> how to change the version of markdown？

first uninstall previous version and then install the right version
