### ISSUE TITLE
Compiling PyTorch with 11.0, V11.0.167

### ISSUE THREAD

**Issue by griff4692** [pytorch/pytorch#40563]
## 🐛 Bug

My CUDA driver is 11.0 but it seems cudatoolkit only goes up to version 10.2.  This causes there to be a mismatch when I try to install apex.

Here is the stack trace from installing apex with the command

`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`

    torch.__version__  = 1.5.1

    /tmp/pip-req-build-qbjtmvks/setup.py:51: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2020 NVIDIA Corporation
    Built on Wed_May__6_19:09:25_PDT_2020
    Cuda compilation tools, release 11.0, V11.0.167
    Build cuda_11.0_bu.TC445_37.28358933_0
    from /usr/local/cuda/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-qbjtmvks/setup.py", line 130, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-qbjtmvks/setup.py", line 85, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.2.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error

Should I just comment out the error or is there a better workaround?

**Comment by malfet** [comment]
@griff4692 to avoid subtle interoperability issues, current model requires that pytorch and extensions to be compiled against the same version of CUDA. If you want to use CUDA-11, please recompile pytorch with CUDA-11 as well.
