### ISSUE TITLE
[JIT] Tracing BCE loss throws error when using weight

### ISSUE THREAD

**Issue by davors72** [pytorch/pytorch#40679]
## 🐛 Bug

When tracing BCELoss with the optional weight parameter  (see https://pytorch.org/docs/master/generated/torch.nn.BCELoss.html) it throws:

```Traceback (most recent call last):
  File "repro.py", line 13, in <module>
    c = torch.jit.trace(model, [input, target])
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 875, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 1027, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 517, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/functional.py", line 2375, in binary_cross_entropy
    new_size = _infer_size(target.size(), weight.size())
RuntimeError: expected int at position 0, but got: Tensor
```

## To Reproduce

```
import torch

weight = torch.randn(3)
model = torch.nn.BCELoss(weight=weight)

input = torch.empty(3).uniform_()
target = torch.empty(3).random_(2)

# Fine.
normal = model(input, target)
print(normal)

# Errors.
c = torch.jit.trace(model, [input, target])
c(input, target)
```

## Expected behavior

A weight parameter on the class should just work. If there is some reason it isn't supported a clearer error message should be thrown.

## Environment

```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.16.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.18.1
[pip3] torch==1.5.0
[pip3] torchtext==0.6.0
[pip3] torchvision==0.6.0
[conda] Could not collect
```

**Comment by wconstab** [comment]
Issue seems to be with `Module.cpp:THPModule_infersize` calling `THPUtils_unpackLongs` on a Size object, which is constructed differently depending on tracing or not.
- when not tracing: a Size is backed by a tuple of ints. 
- when tracing, it is backed by a tuple of 1-d Tensors that wrap ints (done intentionally to provide the tracer insight into how those tensors are used - see [THPSize_New](https://github.com/pytorch/pytorch/blob/master/torch/csrc/Size.cpp#L25)

A naive fix could be to handle unpacking 1-d tensors instead of ints when in tracing mode in `THPModule_infersize`, or potentially one layer deeper inside `THPUtils_unpackLongs`.  However, this would seem to defeat the purpose of wrapping the sizes in tensors in the first place - namely, downstream from the call to `_infer_size`, anything dependent on that inferred size would be incorrectly frozen into the program instead of being data dependent.

Perhaps a better fix would be to make at::infer_size operate correctly on a Size composed of 1-d tensors, thus preserving the metadata.
Thoughts @suo @eellison?

**Comment by suo** [comment]
Sorry for the late reply. I think the second fix is better: if sizes can sometimes (really only under tracing) be composed of tensors, then we should update the primitives operating on sizes to expect that. An additional place to edit would be the place where we bind `_infer_size` into the JIT ([here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/register_special_ops.cpp#L298)); we'd need to add a tensor list overload.

**Comment by wconstab** [comment]
@suo @gchanan What do you think about the latest PR, which removes infer_size usage from BCE?  The existing test cases don't appear to exercise this in a meaningful way, although there is enough complexity in how the input shapes to the kernel get expanded that I can't say for sure this is a no-op change.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
