### ISSUE TITLE
Error in caffe2 when building pytorch from source

### ISSUE THREAD

**Issue by Tang-YH** [pytorch/pytorch#40698]
## 🐛 Bug

While building pytorch from source, the script returns this error:
```
[ 97%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/python_dimname.cpp.o
/home/tangyh/opt/pytorch/torch/csrc/DataLoader.cpp: In function ‘PyObject* THPModule_removeWorkerPIDs(PyObject*, PyObject*)’:
/home/tangyh/opt/pytorch/torch/csrc/DataLoader.cpp:185:21: Error：expected primary-expression before ‘(’ token
  185 |     throw ValueError("Cannot find worker information for _BaseDataLoaderIter with id %" PRId64, key);
      |                     ^
/home/tangyh/opt/pytorch/torch/csrc/DataLoader.cpp:185:88: Error：expected ‘)’ before ‘PRId64’
  185 |     throw ValueError("Cannot find worker information for _BaseDataLoaderIter with id %" PRId64, key);
      |                     ~                                                                  ^~~~~~~
      |                                                                                        )
[ 97%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Size.cpp.o
[ 97%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Storage.cpp.o
[ 97%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/TypeInfo.cpp.o
[ 97%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/api/src/python/init.cpp.o
[ 98%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/autograd/init.cpp.o
[ 98%] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/autograd/functions/init.cpp.o
gmake[2]: *** [caffe2/torch/CMakeFiles/torch_python.dir/build.make:148：caffe2/torch/CMakeFiles/torch_python.dir/csrc/DataLoader.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:11454：caffe2/torch/CMakeFiles/torch_python.dir/all] Error 2
gmake: *** [Makefile:161：all] Error 2
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    build_caffe2(version=version,
  File "/home/tangyh/opt/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/tangyh/opt/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/tangyh/opt/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/tangyh/.local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 2.
```

## To Reproduce

```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python setup.py install
```

## Environment

```

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS release 6.6 (Final)
GCC version: (GCC) 9.3.0
CMake version: version 3.17.3

Python version: 3.8
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] numpydoc                  0.9.2                      py_0
```
I wasn't building pytorch with Anaconda, but the dependensies should be all installed.

cc @malfet @SsnL

**Comment by ababushk** [comment]
I've faced the same issue when tried to build Torch in manylinux2010 Docker image (https://github.com/pypa/manylinux), which is based on CentOS 6 in order to produce binaries compatible with old Linux distros.
In my case, I was able to switch to manylinux2014, which is based on CentOS 7 and the build has passed. I'm not sure why, because they contain the same GCC 9.3.0, however manylinux2014 ships devtoolset-9, and manylinux2010 ships devtoolset-8

**Comment by ShoufaChen** [comment]
This reply solved my problem. https://github.com/pytorch/pytorch/issues/35185#issuecomment-633726339

**Comment by sanmai-NL** [comment]
@Tang-YH Can this issue be closed?
