### ISSUE TITLE
Improve error messaging when using dictionaries as inputs to a trace

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#40886]
## Motivation

The JIT tracer supports using dictionaries as input, like:
```
import torch
from typing import Dict

class TestModule(torch.nn.Module):
    def __init__(self):
        super(TestModule, self).__init__()

    def forward(self, dict_input):
       return dict_input['x']

input_1 = {'x': torch.tensor(1)}
m = TestModule()
m_traced = torch.jit.trace(m, (input_1, ))
```

However, the tracer "burns in" the structure of the dict (more precisely, it inlines all keys as constants and burns in the value types). The resulting graph looks like:
```
graph(%self : __torch__.TestModule,
      %2 : Dict(str, Tensor)):
  %3 : str = prim::Constant[value="x"]()
  %4 : Long() = aten::__getitem__(%2, %3)
  return (%4)
```

If you try to use a dictionary with a different key, you will get a very opaque error message
```
input_2 = {'y': torch.tensor(1)}
m_traced(input_2)

Traceback (most recent call last):
  File "/private/home/suo/scratch/test.py", line 27, in <module>
    m_traced(input_2)
  File "/scratch/suo/pytorch/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
/scratch/suo/pytorch/torch/jit/__init__.py(1108): trace_module
/scratch/suo/pytorch/torch/jit/__init__.py(954): trace
/private/home/suo/scratch/test.py(24): <module>
RuntimeError: KeyError: x
```

We ought to improve the error messaging here, with reference to the expected structure and how it's different from the structure the user passed in.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
