### ISSUE TITLE
torch.jit.TracingCheckError: Tracing failed sanity checks!  When I am using torch.utils.checkpoint ?

### ISSUE THREAD

**Issue by halostorm** [pytorch/pytorch#40912]
## ❓ Questions and Help

**define function_factory**

```
def _bn_function_factory(norm, relu, conv):
	def bn_function(inputs):
		concated_features = inputs
		bottleneck_output = relu(norm(conv(concated_features)))
		return bottleneck_output
	return bn_function
```

**part of my model** 

```
class NET(nn.Module):
	def __init__(self, emb_dims=512):
		super(NET, self).__init__()
		self.k = k
		self.conv1 = nn.Conv2d(6, 64, kernel_size=1, bias=False)
		self.relu1 = nn.ReLU(inplace=True)
		self.bn1 = nn.BatchNorm2d(64)
	def forward(self, x):
		bn_function = _bn_function_factory(self.bn1, self.relu1, self.conv1)
		batch_size, num_dims, num_points = x.size()
		x = cp.checkpoint(bn_function, x)
```

**export model to torch script**

```
model.eval()
src = torch.rand(16, 3, 512).cuda()
tgt = torch.rand(16, 3, 512).cuda()
model_output = torch.jit.trace(model, (src, tgt))
output = model_output(src, tgt)
model_output.save('checkpoints/' + args.exp_name + '/frozen_model.pt')
```

When I use torch.utils.checkpoint to group model, there is error as bellow... It works if i don't use torch.utils.checkpoint, 
Such as " x = bn_function (x)", but "x = cp.checkpoint(bn_function1, x)" not work to export torch script .

**If someone others meet this issue?** 

```
Traceback (most recent call last):
  File "main.py", line 874, in <module>
    main()
  File "main.py", line 842, in main
    freeze(args, net)
  File "main.py", line 707, in freeze
    model = torch.jit.trace(net, (src, tgt))
  File "/home/duwenwen/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 875, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/duwenwen/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 1037, in trace_module
    check_tolerance, _force_outplace, True, _module_class)
  File "/home/duwenwen/.local/lib/python3.5/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/duwenwen/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 675, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit.TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%self.1 : __torch__.model.DCP,
		        %x.1 : Tensor,
		        %x.8 : Tensor):
		    %3 : __torch__.model.SVDHead = prim::GetAttr[name="head"](%self.1)
		    %4 : __torch__.model.Transformer = prim::GetAttr[name="pointer"](%self.1)
		    %5 : __torch__.model.DGCNN = prim::GetAttr[name="emb_nn"](%self.1)
		    %20 : __torch__.torch.nn.modules.activation.ReLU = prim::GetAttr[name="relu5"](%5)
		    %21 : __torch__.torch.nn.modules.batchnorm.BatchNorm2d = prim::GetAttr[name="bn5"](%5)
		    %22 : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv5"](%5)
		    %23 : __torch__.torch.nn.modules.activation.ReLU = prim::GetAttr[name="relu4"](%5)
		    %24 : __torch__.torch.nn.modules.batchnorm.BatchNorm2d = prim::GetAttr[name="bn4"](%5)
		    %25 : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv4"](%5)
		    %26 : __torch__.torch.nn.modules.activation.ReLU = prim::GetAttr[name="relu3"](%5)
		    %27 : __torch__.torch.nn.modules.batchnorm.BatchNorm2d = prim::GetAttr[name="bn3"](%5)
		    %28 : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv3"](%5)
		    %29 : __torch__.torch.nn.modules.activation.ReLU = prim::GetAttr[name="relu1"](%5)
		    %30 : __torch__.torch.nn.modules.batchnorm.BatchNorm2d = prim::GetAttr[name="bn1"](%5)
		    %31 : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv1"](%5)
		    %32 : int = prim::Constant[value=0](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:329:0
		    %33 : int = aten::size(%x.1, %32), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:329:0
		    %batch_size.2 : Tensor = prim::NumToTensor(%33), scope: __module.emb_nn
		    %35 : int = aten::Int(%batch_size.2), scope: __module.emb_nn
		    %36 : int = prim::Constant[value=2](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:329:0
		    %37 : int = aten::size(%x.1, %36), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:329:0
		    %num_points.2 : Tensor = prim::NumToTensor(%37), scope: __module.emb_nn
		    %39 : int = aten::Int(%num_points.2), scope: __module.emb_nn
		    %40 : int = prim::Constant[value=2](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %41 : int = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %42 : Tensor = aten::transpose(%x.1, %40, %41), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %43 : int = prim::Constant[value=0](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %44 : Tensor = aten::contiguous(%42, %43), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %45 : Tensor = aten::matmul(%44, %x.1), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %46 : Tensor = prim::Constant[value={-2}](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %inner.1 : Tensor = aten::mul(%45, %46), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:72:0
		    %48 : int = prim::Constant[value=2](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:73:0
		    %49 : Tensor = aten::pow(%x.1, %48), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:73:0
		    %50 : int = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:73:0
		    %51 : int[] = prim::ListConstruct(%50), scope: __module.emb_nn
		    %52 : bool = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:73:0
		    %53 : None = prim::Constant(), scope: __module.emb_nn
		    %xx.1 : Tensor = aten::sum(%49, %51, %52, %53), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:73:0
		    %55 : Tensor = aten::neg(%xx.1), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %56 : int = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %57 : Tensor = aten::sub(%55, %inner.1, %56), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %58 : int = prim::Constant[value=2](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %59 : int = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %60 : Tensor = aten::transpose(%xx.1, %58, %59), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %61 : int = prim::Constant[value=0](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %62 : Tensor = aten::contiguous(%60, %61), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %63 : int = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %pairwise_distance.1 : Tensor = aten::sub(%57, %62, %63), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:74:0
		    %65 : int = prim::Constant[value=10](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:76:0
		    %66 : int = prim::Constant[value=-1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:76:0
		    %67 : bool = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:76:0
		    %68 : bool = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:76:0
		    %69 : Tensor, %idx.1 : Tensor = aten::topk(%pairwise_distance.1, %65, %66, %67, %68), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:76:0
		    %71 : int = prim::Constant[value=0](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:83:0
		    %72 : int = aten::size(%idx.1, %71), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:83:0
		    %batch_size.1 : Tensor = prim::NumToTensor(%72), scope: __module.emb_nn
		    %74 : int = aten::Int(%batch_size.1), scope: __module.emb_nn
		    %75 : int = aten::Int(%batch_size.1), scope: __module.emb_nn
		    %76 : Scalar = aten::ScalarImplicit(%batch_size.1), scope: __module.emb_nn
		    %77 : int = prim::Constant[value=1](), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:83:0
		    %78 : int = aten::size(%idx.1, %77), scope: __module.emb_nn # /home/duwenwen/Workspace/dcp/model.py:83:0
		    %num_points.1 : Tensor = prim::NumToTensor(%78), scope: __module.emb_nn
		    %80 : int = aten::Int(%num_points.1), scope: __module.emb_nn
		    %81 : int = aten::Int(%num_points.1), scope: __module.emb_nn

```

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting this issue Halo. 

I tried to reproduce this issue but your example isn't complete so I wrote my own repro case, but the error I got is different.
Here is my repro:https://gist.github.com/gmagogsfm/b4fea857ccc1372b75117b943d9924d9

Could you help me look deeper into this issue by
1) Providing a complete (and preferably minimal repro)?
2) Verify whether the error message in original comment is complete? It doesn't look like a diff patch to me.

Thanks

**Comment by halostorm** [comment]
Sorry, I didn't give all issue information, the following code can be used to test the problem I encountered. And the error like "graph diff, node diff" is new to me...

```
import torch
import torch.nn as nn
import torch.utils.checkpoint as cp


def _bn_function_factory(norm, relu, conv):
	def bn_function(inputs):
		_features = inputs
		_output = relu(norm(conv(_features)))
		return _output

	return bn_function


class NET(nn.Module):
	def __init__(self):
		super(NET, self).__init__()
		self.conv = nn.Conv2d(6, 64, kernel_size=1, bias=False)
		self.relu = nn.ReLU(inplace=True)
		self.bn = nn.BatchNorm2d(64)

	def forward(self, x):
		bn_function = _bn_function_factory(self.bn, self.relu, self.conv)
		x = cp.checkpoint(bn_function, x)
		# x = bn_function(x) # This way works.
		return x


if __name__ == '__main__':
	model = NET()
	model.eval()
	input = torch.rand(16, 6, 128, 20)
	model_output = torch.jit.trace(model, input)
	output = model_output(input)
	model_output.save('frozen_model.pt')

```

**Comment by gmagogsfm** [comment]
Thanks for the repro. Now I can see a clear error message. There are 2 issues:

1) The immediate issue is that you are putting invocation of bn_function_factory inside forward(), which results a new function object every time forward prop is run. See this github gist to fix that:
https://gist.github.com/gmagogsfm/8b4bc15b5814729cfb323453ae114622

2) As far as I know, torchscript doesn't support checkpointing, so even if you fix first issue, the program still complains about:
RuntimeError:
Could not export Python function call 'CheckpointFunction'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:

@suo Do you know any workaround regarding checkpointing?

**Comment by halostorm** [comment]
@gmagogsfm 
Thank you very much for pointing out the mistake, it's a careless bug... Maybe I have to find other way to export the model.
