### ISSUE TITLE
Test failures on Power using OpenBLAS/Eigen

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41186]
## 🐛 Bug

I have some tests failing on a Power system. As MKL is not (easily?) available there I'm using the automatic fallback to Eigen/OpenBlas.
The failing tests are:
- test_solve_batched_broadcast_A_cpu
- test_solve_batched_broadcast_b_cpu
- test_solve_batched_cpu
- test_solve_batched_dims_cpu

Those are only 4 out of 1961 which fail

## To Reproduce

1. `python setup.py install`
1. `cd tests`
1. `python run_tests.py`

## Expected behavior

Tests pass

## Environment

PyTorch Version: 1.5.1

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (GCC) 8.3.0
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB

Nvidia driver version: 440.64.00
cuDNN version: 7.6.4.38

Versions of relevant libraries:
[pip3] numpy==1.17.3

## Additional context

The failed tests output look like this:

```
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 1.3259e+00,  0.0000e+00,  0.0000e+00,  ...,  3.9608e+06,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.3259e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.3259e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.3575e-02,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -2.3575e-02,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00, -2.3575e-02]])
analytical:tensor([[ 1.3259,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.3259,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.3259,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.0236,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0236,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.0236]])

```

**Comment by mruberry** [comment]
Thank you for reporting this issue, @Flamefire. That looks like a wild deviation. I don't think we have any builds that test Eigen or OpenBLAS currently, unfortunately.

**Comment by Flamefire** [comment]
I was pointed to some Power CI builds (which do use Eigen and OpenBLAS) in another issue recently: https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le/1128/consoleFull

It seems the tests pass fine there.

Checking the first lines `[1.3259e+00,  0.0000e+00,  0.0000e+00,  ...,  3.9608e+06, 0.0000e+00,  0.0000e+00] == [ 1.3259,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]`, does that mean a value that should be zero is calculated to be almost 4 million? The other values seem to match so I suspect a real bug here. Although it might be fixed for 1.6 already or it is some uninitialized memory causing random failures. I'll try to check the 1.6 RC

**Comment by Flamefire** [comment]
Ok, I've been working on this in the 1.5.1 version again and noticed something strange:   
If I run `python test_autograd.py` I get the 4 mentioned failures. If I try to run the tests alone via `python test_autograd.py -k test_solve` then the tests pass. Using `--verbose` I see `test_solve_batched_broadcast_A_cpu (__main__.TestAutogradDeviceTypeCPU) ... ok` so that tests looks like it is executed. This is fully reproducible but I don't know how/why the results differ like that.

**Comment by Flamefire** [comment]
I have another datapoint: In PyTorch 1.4 `torch.matmul` was very sensitive to `OMP_NUM_THREADS` returning different values when a high number of threads is used. As our power system has 176 cores this was triggered. A simple test repro is 
[precision-test.tar.gz](https://github.com/pytorch/pytorch/files/4932870/precision-test.tar.gz)

It was taken from one of the distribution tests which would randomly fail and runs the same matmul 10 times. Sometimes the output is:
```
tensor([0.3668, 1.6332, 1.2861, 7.1525, 4.9346], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5955, 1.2872, 7.2709, 4.9836], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
tensor([0.2874, 1.5961, 1.2872, 7.3472, 5.0201], dtype=torch.float64)
```

This looks like the kind of deviations I see in other failing tests on that system. However this fails to reproduce with PyTorch 1.6. But it is possible, that other functions suffer from a similar issue although they still fail with `OMP_NUM_THREADS=4`. Maybe some functions use the physical CPU number instead?

**Comment by mruberry** [comment]
@Flamefire, sorry, just to verify, which of these issues reproduce on 1.6?

**Comment by Flamefire** [comment]
The initially reported tests in test_torch (changed the title to clarify) fail on 1.5.1 and 1.6-rc3. The matmul failure is only reproducible in 1.4.0.

I mentioned the latter only because something must have been changed after 1.4 which solved the matmul issue. Maybe something similar can be done for this issue.

**Comment by mruberry** [comment]
> The initially reported tests in test_torch (changed the title to clarify) fail on 1.5.1 and 1.6-rc3. The matmul failure is only reproducible in 1.4.0.
> 
> I mentioned the latter only because something must have been changed after 1.4 which solved the matmul issue. Maybe something similar can be done for this issue.

Got it. Thank you.

**Comment by Flamefire** [comment]
A similar issue was discovered on a Skylake x86 system with V100 GPUs. So it may not be the CPU arch which is the problem but the GPUs, as our POWER system has also V100 GPUs.
The error from the skylake system is:
```

ERROR: test_qr_tall_many_batched_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 777, in wrapper
    method(*args, **kwargs)
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4498, in do_test
    check(name)
  File "test_autograd.py", line 4415, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4306, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 492, in gradgradcheck
    nondet_tol=nondet_tol, check_undefined_grad=check_undefined_grad)
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/scratch/eb-0fSwtH/tmpdfZdJa/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[10.4996,  1.4885,  4.3596,  ...,  0.0000,  0.0000,  0.0000],
        [ 1.4885,  2.0670, -0.1535,  ...,  0.0000,  0.0000,  0.0000],
        [ 4.3596, -0.1535,  3.3428,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.6585,  0.3541,  0.4280],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.3541, -0.4100,  0.2916],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.4280,  0.2916, -0.6260]])
analytical:tensor([[10.4996,  1.4885,  4.3596,  ...,  0.0000,  0.0000,  0.0000],
        [ 1.4885,  2.0670, -0.1535,  ...,  0.0000,  0.0000,  0.0000],
        [ 4.3596, -0.1535,  3.3428,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.6585,  0.3541,  0.4280],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.3541, -0.4100,  0.2916],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.4280,  0.2916, -0.6260]])
```

For a full, lengthy build log see https://gist.github.com/skumons/eae2971ba9a5962e14ec23adf0413526
