### ISSUE TITLE
test_upsampling_not_recompute_scale_factor fails with Eigen/OpenBLAS

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41187]
## 🐛 Bug

I'm getting a test failure of test_upsampling_not_recompute_scale_factor

## To Reproduce

1. python setup.py install
1. cd test
1. python run_tests.py

```
======================================================================
FAIL: test_upsampling_not_recompute_scale_factor (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 7199, in test_upsampling_not_recompute_scale_factor
    self.assertEqual(out_t, expected_out_t)
  File "/tmp/easybuild-tmp/eb-lWK_ii/tmpPLa9_o/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 884, in assertEqual
    assertTensorsEqual(x, y)
  File "/tmp/easybuild-tmp/eb-lWK_ii/tmpPLa9_o/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 850, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.57356e-05, dtype=torch.float32) not less than or equal to 1e-05 : 

```

## Expected behavior

Tests pass

## Environment

PyTorch version: 1.5.1

OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
GCC version: (GCC) 8.3.0
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
cuDNN version: 7.6.4.38

Versions of relevant libraries:
[pip3] numpy==1.17.3

**Comment by mruberry** [comment]
Thanks for reporting this issue, @Flamefire. Looks like that test may need a slightly higher tolerance.

**Comment by guol-fnst** [comment]
> Thanks for reporting this issue, @Flamefire. Looks like that test may need a slightly higher tolerance. We would accept a PR fixing this.

Is it ok just to increase the tolerance simply (ex. from 1e-05 to1e-04)? Or do we need to calculate it carefully?

**Comment by Flamefire** [comment]
I just checked the 1.6.0-rc2 and there the tolerance was already increased to 1.e-4. So this is only relevant in case another release in the 1.5.x series is done.

**Comment by mruberry** [comment]
> I just checked the 1.6.0-rc2 and there the tolerance was already increased to 1.e-4. This makes it pass on our systems.
> 
> So this is only relevant in case another release in the 1.5.x series is done.

Glad to hear it! We're not planning another 1.5.x release. Are we OK to close this issue?
