### ISSUE TITLE
JIT tests fail with ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41254]
## 🐛 Bug

Running the JIT tests in `test_cpp_extensions_jit.py` results in `ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"`

## To Reproduce

1. build&install
1. python test_cpp_extensions_jit.py

Failure:

```
======================================================================
ERROR: test_cpp_frontend_module_has_same_output_as_python (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 387, in wrapper
    fn(*args, **kwargs)
  File "test_cpp_extensions_jit.py", line 425, in test_cpp_frontend_module_has_same_output_as_python
    verbose=True,
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 969, in load
    keep_intermediates=keep_intermediates)
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1185, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1533, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/sw/installed/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/sw/installed/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_cpp_frontend_module_has_up_to_date_attributes (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 387, in wrapper
    fn(*args, **kwargs)
  File "test_cpp_extensions_jit.py", line 555, in test_cpp_frontend_module_has_up_to_date_attributes
    verbose=True,
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 969, in load
    keep_intermediates=keep_intermediates)
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1185, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1533, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/sw/installed/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/sw/installed/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_cpp_frontend_module_python_inter_op (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 387, in wrapper
    fn(*args, **kwargs)
  File "test_cpp_extensions_jit.py", line 457, in test_cpp_frontend_module_python_inter_op
    verbose=True,
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 969, in load
    keep_intermediates=keep_intermediates)
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1185, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1533, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/sw/installed/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/sw/installed/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_warning (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 707, in test_warning
    warn_mod.foo(t, 1)
RuntimeError: Error with CPUDoubleType

```

## Environment

PyTorch 1.5.1 and 1.6.0-rc2 show the same behavior

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (GCC) 8.3.0
CMake version: version 3.15.3

Python version: 3.7

cc @suo @gmagogsfm

**Comment by eellison** [comment]
cc @malfet build, @ezyang @mruberry who recently touched `test_cpp_extensions_jit.py`

**Comment by ezyang** [comment]
on a recent nightly on OS X this test passes for me. Might be something env related

```
(pytorch-deps) ezyang-mbp:test ezyang$ python test_cpp_extensions_jit.py TestCppExtensionJIT.test_cpp_frontend_module_has_same_output_as_python
Using /Users/ezyang/Library/Caches/torch_extensions as PyTorch extensions root...
Creating extension directory /Users/ezyang/Library/Caches/torch_extensions/cpp_frontend_extension...
Emitting ninja build file /Users/ezyang/Library/Caches/torch_extensions/cpp_frontend_extension/build.ninja...
Building extension module cpp_frontend_extension...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF cpp_frontend_extension.o.d -DTORCH_EXTENSION_NAME=cpp_frontend_extension -DTORCH_API_INCLUDE_EXTENSION_H -isystem /Users/ezyang/Dev/pytorch-tmp2/torch/include -isystem /Users/ezyang/Dev/pytorch-tmp2/torch/include/torch/csrc/api/include -isystem /Users/ezyang/Dev/pytorch-tmp2/torch/include/TH -isystem /Users/ezyang/Dev/pytorch-tmp2/torch/include/THC -isystem /Users/ezyang/miniconda3/envs/pytorch-deps/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /Users/ezyang/Dev/pytorch-tmp2/test/cpp_extensions/cpp_frontend_extension.cpp -o cpp_frontend_extension.o 
[2/2] c++ cpp_frontend_extension.o -shared -L/Users/ezyang/Dev/pytorch-tmp2/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -undefined dynamic_lookup -o cpp_frontend_extension.so
Loading extension module cpp_frontend_extension...
.
----------------------------------------------------------------------
Ran 1 test in 8.379s

OK
```

**Comment by Flamefire** [comment]
Maybe already fixed now, can't reproduce either. Only thing now is https://github.com/pytorch/pytorch/issues/41242
