### ISSUE TITLE
binaries compiled against newer numpy, but executed with older numpy error out

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#413]
```
In [1]: import torch
^[[A---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c031d3dd82fc> in <module>()
----> 1 import torch

/Users/chinso/anaconda/lib/python2.7/site-packages/torch/__init__.pyc in <module>()
     43 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
     44
---> 45 from torch._C import *
     46
     47 __all__ += [name for name in dir(_C)

ImportError: numpy.core.multiarray failed to import
```

**Comment by tiard** [comment]
I have the exact same issue, could you give me an idea of how to fix this?

**Comment by soumith** [comment]
upgrade your numpy

**Comment by GrumpyZhou** [comment]
````
>>> import torch
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import 
````
I already have bumpy 1.11.2... Any idea how to fix this?
