### ISSUE TITLE
How to make build_pytorch_android.sh running with python 3 on mac?

### ISSUE THREAD

**Issue by hehedaozuiteng** [pytorch/pytorch#41309]
Hi all, I was trying to following the tutrials from https://pytorch.org/mobile/android/#building-pytorch-android-from-source.

when I run the  

> git clone https://github.com/pytorch/pytorch.git
> cd pytorch
> sh ./scripts/build_pytorch_android.sh

It reports me the error such that 

>   File "/Users/huanghenglin/pytorch/tools/shared/module_loader.py", line 12, in import_module
>     from importlib.machinery import SourceFileLoader
> ImportError: No module named machinery

I guessn this issue was caused by the scrip run the module_loader.py with python 2.

I already set the python 3 as my default python by adding the following code on .zshrc

> export PATH=${PATH}:/usr/local/opt/python@3.8/libexec/bin
> alias python="/usr/local/opt/python@3.8/libexec/bin/python"

and the code 

> from importlib.machinery import SourceFileLoader

runs ok on terminal's python.

the end part of report from the secipt:

> [ 63%] Generating ../../torch/csrc/autograd/generated/Functions.cpp, ../../torch/csrc/jit/generated/generated_unboxing_wrappers_0.cpp, ../../torch/csrc/jit/generated/generated_unboxing_wrappers_1.cpp, ../../torch/csrc/jit/generated/generated_unboxing_wrappers_2.cpp, ../../torch/csrc/autograd/generated/Functions.h, ../../torch/csrc/autograd/generated/variable_factories.h, ../../torch/csrc/autograd/generated/python_functions.cpp, ../../torch/csrc/autograd/generated/python_variable_methods.cpp, ../../torch/csrc/autograd/generated/python_torch_functions.cpp, ../../torch/csrc/autograd/generated/python_nn_functions.cpp, ../../torch/csrc/autograd/generated/python_functions.h
> Traceback (most recent call last):
>   File "tools/setup_helpers/generate_code.py", line 118, in <module>
>     main()
>   File "tools/setup_helpers/generate_code.py", line 113, in main
>     options.force_schema_registration,
>   File "tools/setup_helpers/generate_code.py", line 34, in generate_code
>     from tools.autograd.gen_autograd import gen_autograd, gen_autograd_python
>   File "/Users/huanghenglin/pytorch/tools/autograd/gen_autograd.py", line 30, in <module>
>     from .utils import YamlLoader, split_name_params, signature_without_args
>   File "/Users/huanghenglin/pytorch/tools/autograd/utils.py", line 15, in <module>
>     CodeTemplate = import_module('code_template', 'aten/src/ATen/code_template.py').CodeTemplate
>   File "/Users/huanghenglin/pytorch/tools/shared/module_loader.py", line 12, in import_module
>     from importlib.machinery import SourceFileLoader
> ImportError: No module named machinery
> make[2]: *** [../torch/csrc/autograd/generated/Functions.cpp] Error 1
> make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
> make: *** [all] Error 2
> 

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by hehedaozuiteng** [comment]
it is problem from shell
