### ISSUE TITLE
Converting deepvoice3 pytorch model to onnx format 

### ISSUE THREAD

**Issue by kundanapillari** [pytorch/pytorch#41304]
I am trying to convert deepvoice3 single speaker tts model to onnx format. Got pre-trained model trained over LJSpeech dataset from deepvoice3 github: https://github.com/r9y9/deepvoice3_pytorch.
Referenced in this [PR](https://github.com/onnx/models/pull/323)

The conversion function used is torch.onnx.export. When I run the export function, the error seems to be in the forward function for Decoder.

Questions:

1. Can this model be converted to onnx? (Do I need a custom embedding operator to convert the model?)
2. What changes do I need to make to fix the error? (code and error given below)

Code for conversion:
```
import torch
from deepvoice3_pytorch.tests.test_deepvoice3 import _test_data
from deepvoice3_pytorch.train import build_model
from deepvoice3_pytorch.train import restore_parts, load_checkpoint

use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

model = build_model()
model = load_checkpoint(checkpoint_path, model, None, True)

sequence = np.array(synthesis._frontend.text_to_sequence(text, p=0))
sequence = torch.from_numpy(sequence).unsqueeze(0).long().to(device)
text_positions = torch.arange(1, sequence.size(-1) + 1).unsqueeze(0).long().to(device)

dummy_model_input = (sequence, text_positions)

output_onnx_model ='deepvoice3.onnx'

torch.onnx.export(model, 
                  dummy_model_input, 
                  output_onnx_model,
                  input_names=['sequence', 'text_positions'], 
                  dynamic_axes={'sequence': {1:'sequence'}, 'text_positions': {1: 'pos'}},
                  output_names=['mel_outputs', 'linear_outputs', 'alignments', 'done'],
                  opset_version=11,
                  verbose=True)
```

This is the error I get:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-43-6e99f8a6337e> in <module>
      6                   output_names=['mel_outputs', 'linear_outputs', 'alignments', 'done'],
      7                   opset_version=11,
----> 8                   verbose=True)

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
    166                         do_constant_folding, example_outputs,
    167                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs,
--> 168                         custom_opsets, enable_onnx_checker, use_external_data_format)
    169 
    170 

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
     67             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs,
     68             custom_opsets=custom_opsets, enable_onnx_checker=enable_onnx_checker,
---> 69             use_external_data_format=use_external_data_format)
     70 
     71 

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, enable_onnx_checker, use_external_data_format)
    486                                                         example_outputs, propagate,
    487                                                         _retain_param_name, val_do_constant_folding,
--> 488                                                         fixed_batch_size=fixed_batch_size)
    489 
    490         # TODO: Don't allocate a in-memory string for the protobuf

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, training, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size)
    332             model.graph, tuple(in_vars), False, propagate)
    333     else:
--> 334         graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
    335         state_dict = _unique_state_dict(model)
    336         params = list(state_dict.values())

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in _trace_and_get_graph_from_model(model, args, training)
    289     with set_training(model, training):
    290         trace_graph, torch_out, inputs_states = \
--> 291             torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
    292         warn_on_static_input_change(inputs_states)
    293 

/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in _get_trace_graph(f, args, kwargs, _force_outplace, return_inputs, _return_inputs_states)
    276     if not isinstance(args, tuple):
    277         args = (args,)
--> 278     outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
    279     return outs
    280 

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in forward(self, *args)
    359             in_vars + module_state,
    360             _create_interpreter_name_lookup_fn(),
--> 361             self._force_outplace,
    362         )
    363 

/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in wrapper(*args)
    346             if self._return_inputs_states:
    347                 inputs_states.append(_unflatten(args[:len(in_vars)], in_desc))
--> 348             outs.append(self.inner(*trace_inputs))
    349             if self._return_inputs_states:
    350                 inputs_states[0] = (inputs_states[0], trace_inputs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    546                 input = result
    547         if torch._C._get_tracing_state():
--> 548             result = self._slow_forward(*input, **kwargs)
    549         else:
    550             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    532                 recording_scopes = False
    533         try:
--> 534             result = self.forward(*input, **kwargs)
    535         finally:
    536             if recording_scopes:

~/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py in forward(self, text_sequences, mel_targets, speaker_ids, text_positions, frame_positions, input_lengths)
     77         mel_outputs, alignments, done, decoder_states = self.seq2seq(
     78             text_sequences, mel_targets, speaker_embed,
---> 79             text_positions, frame_positions, input_lengths)
     80 
     81         # Reshape

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    546                 input = result
    547         if torch._C._get_tracing_state():
--> 548             result = self._slow_forward(*input, **kwargs)
    549         else:
    550             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    532                 recording_scopes = False
    533         try:
--> 534             result = self.forward(*input, **kwargs)
    535         finally:
    536             if recording_scopes:

~/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py in forward(self, text_sequences, mel_targets, speaker_embed, text_positions, frame_positions, input_lengths)
    122             encoder_outputs, mel_targets,
    123             text_positions=text_positions, frame_positions=frame_positions,
--> 124             speaker_embed=speaker_embed, lengths=input_lengths)
    125 
    126         return mel_outputs, alignments, done, decoder_states

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    546                 input = result
    547         if torch._C._get_tracing_state():
--> 548             result = self._slow_forward(*input, **kwargs)
    549         else:
    550             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    532                 recording_scopes = False
    533         try:
--> 534             result = self.forward(*input, **kwargs)
    535         finally:
    536             if recording_scopes:

~/deepvoice3_pytorch/deepvoice3_pytorch/deepvoice3.py in forward(self, encoder_out, inputs, text_positions, frame_positions, speaker_embed, lengths)
    287         if inputs.size(-1) == self.in_dim:
    288             inputs = inputs.view(inputs.size(0), inputs.size(1) // self.r, -1)
--> 289         assert inputs.size(-1) == self.in_dim * self.r
    290 
    291         # expand speaker embedding for all time steps

AssertionError: 
```
Thanks! 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by malfet** [comment]
Quick glance at the backtrace suggests, that may be your `dummy_model_input` is incompatible with the model. (Have you check if `model(dummy_model_input)` would succeed)

**Comment by kundanapillari** [comment]
Yes, the dummy_model_input successfully runs and generates the right output for the pytorch model but fails when the export function is executed.

**Comment by spandantiwari** [comment]
@kundanapillari - I don't see from your stack trace what exactly is the error in ONNX export. Can you do the following:'
1) Set model.eval() before export.
2) Can you set the device to cpu and run the model on cpu for export?

**Comment by kundanapillari** [comment]
I still get the same error as above even after making these changes
```
device = torch.device("cpu")

model = build_model()
model = load_checkpoint(checkpoint_path, model, None, True)
model.eval()
```

**Comment by spandantiwari** [comment]
@kundanapillari - is the `checkpoint_path` target available somewhere. Also, as I asked above, I don't see any clear error message in the error stack. Maybe if you run this as a Python script (not a notebook) you may get a useful error stack. Can you please send these?

**Comment by kundanapillari** [comment]
I get this error now when I run the script:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-22c82b830bf1> in <module>
     28                   dynamic_axes={'sequence': {1:'sequence'}, 'text_positions': {1: 'pos'}},
     29                   output_names=['mel_outputs', 'linear_outputs', 'alignments', 'done'],
---> 30                   verbose=True)

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes)
    130                         operator_export_type, opset_version, _retain_param_name,
    131                         do_constant_folding, example_outputs,
--> 132                         strip_doc_string, dynamic_axes)
    133 
    134 

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes)
     62             operator_export_type=operator_export_type, opset_version=opset_version,
     63             _retain_param_name=_retain_param_name, do_constant_folding=do_constant_folding,
---> 64             example_outputs=example_outputs, strip_doc_string=strip_doc_string, dynamic_axes=dynamic_axes)
     65 
     66 

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes)
    327                                                         output_names, operator_export_type,
    328                                                         example_outputs, propagate,
--> 329                                                         _retain_param_name, do_constant_folding)
    330 
    331         # TODO: Don't allocate a in-memory string for the protobuf

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, training, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop)
    211             model.graph, tuple(in_vars), False, propagate)
    212     else:
--> 213         graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
    214         state_dict = _unique_state_dict(model)
    215         params = list(state_dict.values())

/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py in _trace_and_get_graph_from_model(model, args, training)
    169     # training mode was.)
    170     with set_training(model, training):
--> 171         trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
    172 
    173     if orig_state_dict_keys != _unique_state_dict(model).keys():

/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in get_trace_graph(f, args, kwargs, _force_outplace, return_inputs)
    254     if not isinstance(args, tuple):
    255         args = (args,)
--> 256     return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
    257 
    258 

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in forward(self, *args)
    321         try:
    322             trace_inputs = _unflatten(all_trace_inputs[:len(in_vars)], in_desc)
--> 323             out = self.inner(*trace_inputs)
    324             out_vars, _ = _flatten(out)
    325             torch._C._tracer_exit(tuple(out_vars))

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    543                 input = result
    544         if torch._C._get_tracing_state():
--> 545             result = self._slow_forward(*input, **kwargs)
    546         else:
    547             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    529         tracing_state._traced_module_stack.append(self)
    530         try:
--> 531             result = self.forward(*input, **kwargs)
    532         finally:
    533             tracing_state.pop_scope()

~/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py in forward(self, text_sequences, mel_targets, speaker_ids, text_positions, frame_positions, input_lengths)
     77         mel_outputs, alignments, done, decoder_states = self.seq2seq(
     78             text_sequences, mel_targets, speaker_embed,
---> 79             text_positions, frame_positions, input_lengths)
     80 
     81         # Reshape

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    543                 input = result
    544         if torch._C._get_tracing_state():
--> 545             result = self._slow_forward(*input, **kwargs)
    546         else:
    547             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    529         tracing_state._traced_module_stack.append(self)
    530         try:
--> 531             result = self.forward(*input, **kwargs)
    532         finally:
    533             tracing_state.pop_scope()

~/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py in forward(self, text_sequences, mel_targets, speaker_embed, text_positions, frame_positions, input_lengths)
    114         # (B, T, text_embed_dim)
    115         encoder_outputs = self.encoder(
--> 116             text_sequences, lengths=input_lengths, speaker_embed=speaker_embed)
    117 
    118         # Mel: (B, T//r, mel_dim*r)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    543                 input = result
    544         if torch._C._get_tracing_state():
--> 545             result = self._slow_forward(*input, **kwargs)
    546         else:
    547             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    529         tracing_state._traced_module_stack.append(self)
    530         try:
--> 531             result = self.forward(*input, **kwargs)
    532         finally:
    533             tracing_state.pop_scope()

~/deepvoice3_pytorch/deepvoice3_pytorch/deepvoice3.py in forward(self, text_sequences, text_positions, lengths, speaker_embed)
     88         # １D conv blocks
     89         for f in self.convolutions:
---> 90             x = f(x, speaker_embed_btc) if isinstance(f, Conv1dGLU) else f(x)
     91 
     92         # Back to B x T x C

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    543                 input = result
    544         if torch._C._get_tracing_state():
--> 545             result = self._slow_forward(*input, **kwargs)
    546         else:
    547             result = self.forward(*input, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    529         tracing_state._traced_module_stack.append(self)
    530         try:
--> 531             result = self.forward(*input, **kwargs)
    532         finally:
    533             tracing_state.pop_scope()

~/deepvoice3_pytorch/deepvoice3_pytorch/modules.py in forward(self, x, speaker_embed)
    138 
    139     def forward(self, x, speaker_embed=None):
--> 140         return self._forward(x, speaker_embed, False)
    141 
    142     def incremental_forward(self, x, speaker_embed=None):

~/deepvoice3_pytorch/deepvoice3_pytorch/modules.py in _forward(self, x, speaker_embed, is_incremental)
    155             x = x[:, :, :residual.size(-1)] if self.causal else x
    156 
--> 157         a, b = x.split(x.size(splitdim) // 2, dim=splitdim)
    158         if self.speaker_proj is not None:
    159             softsign = F.softsign(self.speaker_proj(speaker_embed))

/opt/anaconda3/lib/python3.7/site-packages/torch/tensor.py in split(self, split_size, dim)
    306             return super(Tensor, self).split(split_size, dim)
    307         else:
--> 308             return super(Tensor, self).split_with_sizes(split_size, dim)
    309 
    310     def unique(self, sorted=True, return_inverse=False, return_counts=False, dim=None):

TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not Tensor
```
This is the [checkpoint_path](https://www.dropbox.com/s/5ucl9remrwy5oeg/20180505_deepvoice3_checkpoint_step000640000.pth?dl=0) file.

**Comment by KsenijaS** [comment]
Can you please share how did you install deepvoice3_pytorch package? Using only pip install deepvoice3_pytorch doesn't allow access to  train, tests etc.
Also can you please share the pytorch and python version. I believe that tensorflow is also required for this model environment so if you could also share the tensorflow version.

**Comment by kundanapillari** [comment]
I cloned the [deepvoice3](https://github.com/r9y9/deepvoice3_pytorch) github repo to access the files. 
Python and PyTorch versions: 
* Python >= 3.5
* PyTorch >= v1.0.0

I didn't use tensorflow. It also did not state in the requirements:
```
Requirements
Python >= 3.5
CUDA >= 8.0
PyTorch >= v1.0.0
nnmnkwii >= v0.0.11
MeCab (Japanese only)
```

**Comment by KsenijaS** [comment]
Can you please share your pytorch version that you have installed in your conda environment.
I found that exception: "TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not Tensor" has been fixed in pytorch 1.5
https://github.com/pytorch/pytorch/issues/27551
https://github.com/pytorch/pytorch/pull/32493
If you have lower pytorch version can you try upgrading it to 1.5 to see if it solves the issue.

**Comment by KsenijaS** [comment]
Can you please share what kind of setup have you done to run test file inside the clone github repo.
I get this error when tried to run your scrip inside github repo:
  File "test.py", line 3, in <module>
    from deepvoice3_pytorch.train import build_model
  File "/home/ksenija/deepvoice/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py", line 3, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'deepvoice3_pytorch.version'

**Comment by kundanapillari** [comment]
> @kundanapillari Can you please share what kind of setup have you done to run test file inside the clone github repo.
> I get this error when tried to run your scrip inside github repo:
> File "test.py", line 3, in
> from deepvoice3_pytorch.train import build_model
> File "/home/ksenija/deepvoice/deepvoice3_pytorch/deepvoice3_pytorch/**init**.py", line 3, in
> from .version import **version**
> ModuleNotFoundError: No module named 'deepvoice3_pytorch.version'

@KsenijaS  I ran this statement to fix the error: python setup.py develop

**Comment by kundanapillari** [comment]
> @kundanapillari Can you please share your pytorch version that you have installed in your conda environment.
> I found that exception: "TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not Tensor" has been fixed in pytorch 1.5
> #27551
> #32493
> If you have lower pytorch version can you try upgrading it to 1.5 to see if it solves the issue.

@KsenijaS Thanks! I am using pytorch 1.5 and I don't get that error anymore. However, I am getting this error when converting:
```
~/deepvoice3_pytorch/deepvoice3_pytorch/deepvoice3.py in forward(self, encoder_out, inputs, text_positions, frame_positions, speaker_embed, lengths)
    322 
    323         # Generic case: B x T x C -> B x C x T
--> 324         x = x.transpose(1, 2)
    325 
    326         # Prenet

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
```
I don't know why this error is showing because when I run my deepvoice3 pytorch model and give dummy_input as my input, I don't get an error and it produces the right output

**Comment by KsenijaS** [comment]
@kundanapillari I still cannot run the file, now I get this error:
ModuleNotFoundError: No module named 'deepvoice3_pytorch.train'

Can you please list all the steps how did you install deepvoice3_pytorch

**Comment by kundanapillari** [comment]
@KsenijaS you probably need to cd into deepvoice3_pytorch and then run it 
```
git clone https://github.com/r9y9/deepvoice3_pytorch && cd deepvoice3_pytorch
```

**Comment by KsenijaS** [comment]
@kundanapillari I did that and it doesn't work for me

**Comment by kundanapillari** [comment]
@KsenijaS what specific file are you running again. The repo doesn't have "test.py" file

**Comment by KsenijaS** [comment]
@kundanapillari test.py is your script that I tried to run inside the clone repo. Tell mw hoe to easily repro your failure:
1.where do you run your script
2. how did you install deepvoice3_pytorch package
3. are there any additional steps

**Comment by KsenijaS** [comment]
@kundanapillari can you tell me the value of text in sequence = np.array(synthesis._frontend.text_to_sequence(text, p=0))

**Comment by KsenijaS** [comment]
@kundanapillari Can you tell me how did you get ONNX model of deepvoice3 model that is part of your PR https://github.com/onnx/models/pull/323.
Could you previously convert the model and now you can't?

**Comment by kundanapillari** [comment]
I was initially able to convert the model by giving a different input to the exporter that is the test_data() from the test.deepvoice3 file. This provides 3 parameters/features from an array of sentences. However, this is not the same input for the original pytorch model where you send in one sentence at a way. I don't know why the exporter only works when the input is different from the original pytorch model. Because of this, I get incorrect audio output from the ONNX model.

**Comment by kundanapillari** [comment]
> assert inputs.size(-1) == self.in_dim * self.r
> AssertionError

I also got the same error but to test it I commented this statement in the file which is when I get the dimension error.

**Comment by KsenijaS** [comment]
@kundanapillari can you tell me what exact inputs do you use? What is the value of text? What is  input for the original pytorch model ?

**Comment by kundanapillari** [comment]
@KsenijaS This is how I run my original PyTorch model 
```
from deepvoice3_pytorch.train import build_model
from deepvoice3_pytorch.train import restore_parts, load_checkpoint

device = torch.device("cpu")

model = build_model()
model = load_checkpoint(checkpoint_path, model, None, True)

text = "Hello World" 
sequence = np.array(synthesis._frontend.text_to_sequence(text, p=0))
sequence = torch.from_numpy(sequence).unsqueeze(0).long().to(device)
text_positions = torch.arange(1, sequence.size(-1) + 1).unsqueeze(0).long().to(device)

mel_outputs, linear_outputs, alignments, done = model(sequence, text_positions=text_positions)
```

**Comment by KsenijaS** [comment]
I converted the model by replacing text_positions with text_positions = torch.rand(sequence.size(0), 12, 80)
I am still getting a mismatch between ort and pytorch model and I'm currently looking into that.

**Comment by KsenijaS** [comment]
@kundanapillari I think I found what was causing a mismatch between pytorch and ort. Some part of the deepvoice model needs to be scripted:
Can you try replacing lines 170 and 171 https://github.com/r9y9/deepvoice3_pytorch/blob/master/deepvoice3_pytorch/deepvoice3.py#L170 with x = attention_script(x, values) where attention_script is the scripting function defined at the top of the file:
```
@torch.jit.script
def attention_script(x, values):
    s = int(values.size(1))
    div = int(1.0) / s
    t = math.sqrt(div)
    x = x * (s * t)
    return x
```
my script for converting to onnx and matching numbers between ort and  pytorch:
```
import torch
from train import build_model
from train import restore_parts, load_checkpoint
import train
import synthesis
import numpy as np
import hparams
import json
from deepvoice3_pytorch import frontend
synthesis._frontend = getattr(frontend, "en")
train._frontend =  getattr(frontend, "en")

preset = "/home/ksenija/Downloads/20180505_deepvoice3_ljspeech.json"
checkpoint_path = "/home/ksenija/Downloads/20180505_deepvoice3_checkpoint_step000640000.pth"
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

# Load parameters from preset
with open(preset) as f:
  hparams.hparams.parse_json(f.read())

model = build_model()
model = load_checkpoint(checkpoint_path, model, None, True)
model.to(device)
model.eval()

text = "Generative adversarial network or variational auto-encoder."

def helper(model, text, p=0):
  sequence = np.array(synthesis._frontend.text_to_sequence(text, p=p))
  sequence = torch.from_numpy(sequence).unsqueeze(0).long().to(device)
  text_positions = torch.randn(sequence.size(0), 12, 80)
 
  return model, sequence, text_positions

model, sequence, text_positions = helper(model, text)

def convert_to_onnx(model, sequence, text_positions):
  dummy_model_input = (sequence, text_positions)
  output_onnx_model ='deepvoice3.onnx'

  torch.onnx.export(model, 
                    dummy_model_input, 
                    output_onnx_model,
                    input_names=['sequence', 'text_positions'], 
                    dynamic_axes={'sequence': {0:'sequence'}, 'text_positions': {1: 'pos'}},
                    output_names=['mel_outputs', 'linear_outputs', 'alignments', 'done'],
                    opset_version=12,
                    verbose=True)

convert_to_onnx(model, sequence, text_positions)

import onnxruntime

ort_session = onnxruntime.InferenceSession('deepvoice3.onnx')

def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(sequence), ort_session.get_inputs()[1].name: to_numpy(text_positions)}
ort_outs = ort_session.run(None, ort_inputs)
torch_outs = model(sequence, text_positions)

[np.testing.assert_allclose(to_numpy(out), ort_out, rtol=1e-04, atol=1e-04) for out, ort_out in zip(torch_outs, ort_outs)]
```
Let me know if this solution works for you

**Comment by kundanapillari** [comment]
@KsenijaS Thanks for the solution. I am able to convert the model into onnx format with making the changes stated above,, however, the ort_outs and torch_outs both produced inaudible audio output. I think this is because my original pytorch model took the input text_positions as ```text_positions = torch.arange(1, sequence.size(-1) + 1).unsqueeze(0).long().to(device)``` for which I got the right audio output. 

I think using ```text_positions = torch.randn(sequence.size(0), 12, 80)``` statement is allowing me to convert the model and get the ```ort_outs``` but not producing the right audio output. The way the audio output is generated from output tensors is given in the tts function in synthesis.py file.

**Comment by KsenijaS** [comment]
@kundanapillari how exactly do you run this model in pytorch, because I get the same Assertion error when trying to run model in PyTorch and converting to ONNX, using the text_positions input that you sent me:
assert inputs.size(-1) == self.in_dim * self.r
AssertionError

**Comment by kundanapillari** [comment]
@KsenijaS I used this [notebook](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/DeepVoice3_single_speaker_TTS_en_demo.ipynb#scrollTo=GR1XRy-ykbz_) (fixed few import errors) to run the model and produce the audio.

**Comment by KsenijaS** [comment]
@kundanapillari can you share your script?

**Comment by kundanapillari** [comment]
@KsenijaS This is my script
```
%pylab inline
! pip install -q librosa nltk

import torch
import numpy as np
import librosa
import librosa.display
import IPython
from IPython.display import Audio
# need this for English text processing frontend
import hparams
import json
import nltk
from train import build_model
from train import restore_parts, load_checkpoint
! python -m nltk.downloader cmudict

preset = "20180505_deepvoice3_ljspeech.json"
checkpoint_path = "20180505_deepvoice3_checkpoint_step000640000.pth"



# Load parameters from preset
with open(preset) as f:
    hparams.hparams.parse_json(f.read())
  
# Inject frontend text processor
import synthesis
import train
from deepvoice3_pytorch import frontend
synthesis._frontend = getattr(frontend, "en")
train._frontend =  getattr(frontend, "en")

# alises
fs = hparams.hparams.sample_rate
hop_length = hparams.hparams.hop_size


def tts(model, text, p=0, speaker_id=None, fast=True, figures=True):
  from synthesis import tts as _tts
  waveform, alignment, spectrogram, mel = _tts(model, text, p, speaker_id, fast)
  if figures:
      visualize(alignment, spectrogram)
  IPython.display.display(Audio(waveform, rate=fs))
  
def visualize(alignment, spectrogram):
  label_fontsize = 16
  figure(figsize=(16,16))

  subplot(2,1,1)
  imshow(alignment.T, aspect="auto", origin="lower", interpolation=None)
  xlabel("Decoder timestamp", fontsize=label_fontsize)
  ylabel("Encoder timestamp", fontsize=label_fontsize)
  colorbar()

  subplot(2,1,2)
  librosa.display.specshow(spectrogram.T, sr=fs, 
                           hop_length=hop_length, x_axis="time", y_axis="linear")
  xlabel("Time", fontsize=label_fontsize)
  ylabel("Hz", fontsize=label_fontsize)
  tight_layout()
  colorbar()


device = torch.device("cpu")

model = build_model()
model = load_checkpoint(checkpoint_path, model, None, True)


texts = [
    "Scientists at the CERN laboratory say they have discovered a new particle.",
    "There's a way to measure the acute emotional intelligence that has never gone out of style.",
    "President Trump met with other leaders at the Group of 20 conference.",
    "The Senate's bill to repeal and replace the Affordable Care Act is now imperiled.",
    "Generative adversarial network or variational auto-encoder.",
    "The buses aren't the problem, they actually provide a solution.",
    "peter piper picked a peck of pickled peppers how many peppers did peter piper pick.",
    "Some have accepted this as a miracle without any physical explanation.",
]


for idx, text in enumerate(texts):
  print(idx, text)
  tts(model, text, figures=False)
```

**Comment by KsenijaS** [comment]
@kundanapillari The exception: assert inputs.size(-1) == self.in_dim * self.r is caused because pytorch model is called with keyword argument text_position (model(sequences, text_position=text_position)) while onnx model is not.
If you look at the order of arguments in MultiSpeakerTTSModel forward function (self, text_sequences, mel_targets=None, speaker_ids=None, text_positions=None, frame_positions=None, input_lengths=None), mel targets comes right after text_sequences and onnx will pass the value to mel_targets instead of text_positions.
You can simply reverse the order of arguments in forward function so that text_positions in the 2nd argument or you can create a wrapper around the model: https://github.com/microsoft/onnxruntime/blob/e1901a7e10b4a156093288d0c0a200700f3caa5e/orttraining/orttraining/python/ort_trainer.py#L258

But there is a bigger issue, the incremental_forward function that is called for Decoder part: https://github.com/r9y9/deepvoice3_pytorch/blob/master/deepvoice3_pytorch/deepvoice3.py#L367
contains a while loop that exits using only break statements, break statements are not supported in ONNX. That means that the model will be indefinitely converting to ONNX model, since it cannot exit the while loop.
https://github.com/r9y9/deepvoice3_pytorch/blob/master/deepvoice3_pytorch/deepvoice3.py#L397
The part with the loop statement needs to be rewritten in order for model to be able to be exported to ONNX

**Comment by garymm** [comment]
Based on the last update, changes to the model have been identified that could make it convertible to ONNX.
Closing due to age and lack of activity. Please open a new issue if more help is needed.

**Comment by lifa08** [comment]
> The way the audio output is generated from output tensors is given in the tts function in synthesis.py file.

@KsenijaS @kundanapillari Can you share what change you have made regarding the text_position and the while loop? Thank you! @kundanapillari, I am wondering why [your model ](https://github.com/onnx/models/pull/323)has not been merged to the master?
