### ISSUE TITLE
test_nn failures on power

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41469]
## 🐛 Bug

Multiple test from test_nn are failing on our Power system:

- test_Conv2d_depthwise_padded
- test_conv_double_backward
- test_Conv2d_groups
- test_grad_conv2d_input
- test_conv_large_cpu

The first is a RuntimeError the others fail to calculate correct results

## To Reproduce

1. python run_test.py -i test_nn

```
======================================================================
ERROR: test_Conv2d_depthwise_padded (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 8728, in <lambda>
    add(test_name, lambda self, test=test: test(self))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_nn.py", line 4434, in __call__
    self._do_test(test_case, module, input)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_nn.py", line 4671, in _do_test
    lambda x, *args, **kw: test_case._forward(module, x), (input,) + params)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1713, in _assertGradAndGradgradChecks
    test_case.assertTrue(gradgradcheck(apply_fn, inputs))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 492, in gradgradcheck
    nondet_tol=nondet_tol, check_undefined_grad=check_undefined_grad)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 324, in gradcheck
    'The tolerance for nondeterminism was {}.'.format(nondet_tol))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient. The tolerance for nondeterminism was 0.0.

======================================================================
ERROR: test_conv_double_backward (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 7842, in test_conv_double_backward
    no_weight, dtype=dtype)
  File "test_nn.py", line 7792, in run_conv_double_back_test
    return gradgradcheck(func, inputs, (grad_y,))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 492, in gradgradcheck
    nondet_tol=nondet_tol, check_undefined_grad=check_undefined_grad)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 3,
numerical:tensor([[-1.3174,  0.8718,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-2.6116, -1.3174,  0.8718,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -2.6116, -1.3174,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.7469,  0.1656,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.6374, -0.7469,  0.1656],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.6374, -0.7469]])
analytical:tensor([[-1.3174,  0.8718,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-2.6116, -1.3174,  0.8718,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -2.6116, -1.3174,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.7469,  0.1656,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.6374, -0.7469,  0.1656],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.6374, -0.7469]])


======================================================================
FAIL: test_Conv2d_groups (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 8728, in <lambda>
    add(test_name, lambda self, test=test: test(self))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_nn.py", line 4434, in __call__
    self._do_test(test_case, module, input)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_nn.py", line 4665, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_nn.py", line 4285, in check_jacobian
    PRECISION
AssertionError: tensor(977923.9321) not less than or equal to 1e-05

======================================================================
FAIL: test_grad_conv2d_input (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 7988, in test_grad_conv2d_input
    self.run_grad_conv_test(F.conv2d, F.grad.conv2d_input, 2, 'input')
  File "test_nn.py", line 7979, in run_grad_conv_test
    dilation=dilation))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1131, in assertAlmostEqual
    self.assertEqual(x, y, msg=msg, atol=prec, rtol=rtol)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1085, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 156 element(s) (out of 196) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 16.72914933368872 (6.796779018482627 vs. -9.932370315206093), which occurred at index (1, 0, 2, 5).

======================================================================
FAIL: test_conv_large_cpu (__main__.TestNNDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_nn.py", line 9966, in test_conv_large
    self.assertEqual(ret[2048:4096], conv(input_large[2048:4096]))
  File "/lustre/ssd/ws/s3248973-EasyBuild2/easybuild-ml/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1085, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 19392 element(s) (out of 16777216) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 3.704709053039551 (1.3201072216033936 vs. -2.3846018314361572), which occurred at index (352, 1, 46, 30).
```

As you can see the error are rather large. This is similar to my other issues regarding the power platform 

## Environment

PyTorch version: 1.6.0-rc3
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (GCC) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB

Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.6.0

cc @albanD @mruberry

**Comment by ezyang** [comment]
@albanD this might be related to the locking problems you're trying to fix, perhaps they are more noticeable on POWER

**Comment by albanD** [comment]
This PR: https://github.com/pytorch/pytorch/pull/40887 is about to land fixing some thread safety issues.
It might be that but I don't expect these tests to run in a multithreaded environment (for the autograd).

I is quite surprising issues though.
@ezyang do we have access to some power machines to investigate this?

**Comment by ezyang** [comment]
Maybe @Flamefire can share :)

**Comment by Flamefire** [comment]
I'm using the one at the taurus cluster at TU Dresden where I work. Access is possible through application.

What about the CI machines you seem to use currently listed as "Linux (ppc64le) GPU" on the Readme?

**Comment by albanD** [comment]
I'm not sure where this build is running, I can't find it on circle ci. @seemethere do you know by any chance?

**Comment by Flamefire** [comment]
I'm still seeing this issue, however after resolving a long standing bug in OpenBLAS on POWER the issue got much better. I see a failure in `test_conv_large_cpu` which is always as follows:

```
  File "test_nn.py", line 11037, in test_conv_large
    self.assertEqual(grad1, grad2)
  File "/tmp/easybuild-tmp/eb-lLyC0t/tmpDMHg8P/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1136, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 162 element(s) (out of 256) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 8.416175842285156e-05 (-2.2611513137817383 vs. -2.261235475540161), which occurred at index (0, 0, 4, 4).
```

The actual values are constant, so the results are at least stable now. When checking the test code I see a comment:

```
        # When computing the backward, we are using the `max(dim=1)`` to create
        # some sparsity. Without this sparsity, the rounding error would be
        # too large (as large as 1e-5) to satisfy the creterion (1e-6) of `assertEqual`
```

Hence I think the test itself might be unstable. I also see a dependency on OMP_NUM_THREADS: With only a single thread the results seem to be close enough. Increasing to e.g. 11 threads the results start to differ, however the above numbers appear well before the max number of threads (according to `nproc`) is reached. Using an OpenBLAS built without OpenMP support complains about it being called from within OpenMP. So it is possible that the issue is in fact in PyTorch and caused/shown by heavy parallelism

A simple "fix" would be to increase the tolerance. I don't really understand the comment mentioned above but maybe this differing results are OK.

**Comment by albanD** [comment]
Thanks for the update!

From what I understand from this test, the input is very large (and so there are very large reductions in the backward). So they have to use this trick to avoid the reduction in one dimension (and thus reduce reduction errors).

Given the values, it does look like a loss of precision due to different float reduction ordering. But is it expected for this reduction to be less precise on power compared to other arch?

**Comment by Flamefire** [comment]
> But is it expected for this reduction to be less precise on power compared to other arch?

I'm not fully sure but it is possible: The low-level details of e.g. OpenBLAS differ between archs and IIRC x86 often uses 80bit registers for intermediate results and POWER might not so rounding errors could happen earlier and get propagated. However as the issue disappears when OpenMP is effectively disabled it might be caused by some scheduling.

I can try to further trace down where the differences arise exactly but it is not particularly easy to pinpoint due to the many layers the control flows until ultimately ending in e.g. OpenBLAS.

**Comment by albanD** [comment]
That sounds good for me. Do we have a mechanism to change the precision just when running on power?

**Comment by Flamefire** [comment]
I'd simply increase it for all platforms as it seems to be CPU core count related due to OpenBLAS switching distribution mechanisms based on that: https://github.com/xianyi/OpenBLAS/issues/2923

**Comment by albanD** [comment]
I do agree that we're walking a very thin line here even on x86. But i prefer to have a tighter test. So that we can actually detect if something is changing with our numerical precision.
This test hasn't been flaky on our CI ever. So I would prefer to keep it as-is for x86 as much as possible.

**Comment by Flamefire** [comment]
Resolved now by not running those tests on CPU anymore. See https://github.com/pytorch/pytorch/pull/45332 and https://github.com/pytorch/pytorch/pull/48429
