### ISSUE TITLE
Hooks registered to weight norm parameters cause RuntimeError

### ISSUE THREAD

**Issue by andrrizzi** [pytorch/pytorch#41529]
## 🐛 Bug

Registering hooks to the `g` and `v` parameters created by `weight_norm` that zero out the gradient of some masked parameters causes any operation performed on the tensor passed as input to one of the hooks to crash. This happens only if hooks are registered for both `g` and `v` (rather than only one of them).

## To Reproduce

I installed a fresh conda environment with
```
conda create --name temptorch pytorch -c pytorch
```

and this is the code to reproduce the error
```python
#!/usr/bin/env python


import torch
from torch import norm_except_dim
from torch.nn import Linear


class ApplyMask:
    """Hook that applies a mask to a tensor.

    Parameters
    ----------
    norm : bool, optional
        If True, the mask is applied to a norm vector (i.e., g) rather
        than a matrix (i.e., v or w). Default is False.
    """

    def __init__(self, mask, dim=0, norm=False):
        # Precompute the masked indices.
        self._zero_indices = None
        if norm:
            # For g, we need to zet to zero only those vectors
            # that have zero norm because of the mask.
            self._zero_indices = torch.nonzero(norm_except_dim(mask, 2, dim).flatten() == 0.0)
        else:
            self._zero_indices = mask == 0.0

    def __call__(self, w):
        # Hooks are not supposed to modify the argument.
        w = w.clone()
        # A simple element-wise multiplication doesn't work if there are NaNs.
        w[self._zero_indices] = 0.0

        print(f'\nPerformed operation successfuly for tensor of shape {w.shape}\n')
        return w


if __name__ == '__main__':
    batch_size = 2
    in_features = 4
    out_features = 5

    # Generate random input. Make sure the test is reproducible.
    generator = torch.Generator()
    generator.manual_seed(0)
    x = torch.randn(batch_size, in_features, generator=generator, requires_grad=True)

    # Lower triangular mask.
    mask = torch.tril(torch.ones(out_features, in_features, requires_grad=False))

    # Create a weight-normalized masked linear layer.
    linear = Linear(in_features, out_features, bias=True)

    # Apply weight normalization.
    from torch.nn.utils import weight_norm
    linear = weight_norm(linear, name='weight', dim=0)

    # Register hook to zero out gradient in the masked weights.
    linear.weight_g.register_hook(ApplyMask(mask, dim=0, norm=True))
    linear.weight_v.register_hook(ApplyMask(mask))

    # The gradient of the masked parameters should be zero.
    y = linear(x)
    loss = torch.sum(y)
    loss.backward()
```

This is the full output I get for this code
```
/Users/distiller/project/conda/conda-bld/pytorch_1591914893314/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)

Performed operation successfully for tensor of shape torch.Size([5, 1])

Traceback (most recent call last):
  File "temp_error_torch.py", line 66, in <module>
    loss.backward()
  File "/Users/bla/miniconda/envs/temptorch/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/bla/miniconda/envs/temptorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError: <method 'clone' of 'torch._C._TensorBase' objects> returned a result with an error set
```
but any operation performed on `w` at the beginning of `ApplyMask.__call__` will fail (with a different message).

## Expected behavior

It shouldn't crash.

## Environment

```
Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-service               2.3.0            py38h0b31af3_0    conda-forge
[conda] mkl_fft                   1.1.0            py38h3b54f70_1    conda-forge
[conda] mkl_random                1.1.0            py38h4a8c4bd_0    conda-forge
[conda] numpy                     1.18.5           py38h1da2735_0  
[conda] numpy-base                1.18.5           py38h3304bdc_0  
[conda] pytorch                   1.5.1                   py3.8_0    pytorch
```

## Additional context

The reason I'm doing this I'm working with masked linear layers and I'm adding hooks to the `g` and `v` parameters created by `weight_norm` that zero out the gradient of the masked parameters (which might be NaN for some masks, see #19126).

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @mruberry

**Comment by zou3519** [comment]
Tentatively marking this as hi-pri because I expect this to work

**Comment by albanD** [comment]
Hi,

I cannot reproduce this on master (and this kind of error vaguely rings a bell). Can you try on a nightly build to see if it already fixed please?

**Comment by andrrizzi** [comment]
The problem does indeed disappear with the nightly build. Apologies for not trying it before. Thank you!
