### ISSUE TITLE
test_tensorboard.py test_figure and test_figure_list no longer work with matplotlib 3.3.0

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#41680]
## 🐛 Bug

Discovered in https://github.com/pytorch/pytorch/pull/38796

When you run these tests with matplotlib 3.3.0 they no longer work

```
Jul 20 08:04:54 ======================================================================
Jul 20 08:04:54 FAIL [0.177s]: test_figure (__main__.TestTensorBoardFigure)
Jul 20 08:04:54 ----------------------------------------------------------------------
Jul 20 08:04:54 Traceback (most recent call last):
Jul 20 08:04:54   File "test_tensorboard.py", line 642, in test_figure
Jul 20 08:04:54     self.assertFalse(plt.fignum_exists(figure.number))
Jul 20 08:04:54 AssertionError: True is not false
Jul 20 08:04:54 
Jul 20 08:04:54 ======================================================================
Jul 20 08:04:54 FAIL [1.110s]: test_figure_list (__main__.TestTensorBoardFigure)
Jul 20 08:04:54 ----------------------------------------------------------------------
Jul 20 08:04:54 Traceback (most recent call last):
Jul 20 08:04:54   File "test_tensorboard.py", line 664, in test_figure_list
Jul 20 08:04:54     self.assertTrue(all([plt.fignum_exists(figure.number) is False for figure in figures]))  # noqa F812
Jul 20 08:04:54 AssertionError: False is not true
Jul 20 08:04:54 
Jul 20 08:04:54 ----------------------------------------------------------------------
Jul 20 08:04:54 Ran 50 tests in 41.752s
```

I don't know enough about the APIs in question to say if this is an upstream bug or not.

## To Reproduce

1. Install matplotlib 3.3.0
2. Build PyTorch
3. Run the tensorboard tests

**Comment by seemethere** [comment]
This is currently blocking: https://github.com/pytorch/pytorch/pull/40950

**Comment by malfet** [comment]
Hmm, this looks like a matplotlib bug to me:
```
#!/usr/bin/env python3
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

figure = plt.figure()
plt.axis('scaled')
plt.tight_layout()
matplotlib.backends.backend_agg.FigureCanvasAgg(figure)
plt.close(figure)
print("Matplotlib version:", matplotlib.__version__)
assert plt.fignum_exists(figure.number) == False
```
Following works with matplotlib-3.2.1 and fails with 3.3.0
