### ISSUE TITLE
Inconsistency loading quantized models when state_dict with Version==None

### ISSUE THREAD

**Issue by salimmj** [pytorch/pytorch#41684]
## 🐛 Bug

`nn.quantized.Linear` encounters KeyError when loading from state_dict. When saving from state_dict, version 3 format is used, but loading evaluates `local_metadata.get('version', None) == None` which defaults to using version 1 format.

## To Reproduce

1. Import DistilBert from transformers library
1. Quantize it dynamically and save it, it shouldn't have `_metadata` saved in state_dict
1. Load it again, you should get an error

```
File "/home/.venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 827, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/.venv/lib/python3.6/site-packages/torch/nn/quantized/modules/linear.py", line 207, in _load_from_state_dict
    weight = state_dict.pop(prefix + 'weight')
KeyError: '_distilbert.transformer.layer.0.attention.q_lin.weight'
```

## Expected behavior

I expected the model to load without issue. 

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.5
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.1
[pip3] numpy==1.18.4
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==1.5.0
[pip3] torchvision==0.3.0
[conda] Could not collect

## Additional context

More context can be found here: https://discuss.pytorch.org/t/loading-quantized-model-from-state-dict-with-version-none/89042

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by salimmj** [comment]
@raghuramank100 I'd love to help fix this and make a PR but I'm not sure where the version gets saved. I'm wondering if there is a way to enforce saving the version at the checkpoint creation step.

**Comment by malfet** [comment]
Looks like the issue has been upgraded from 1.7 to 1.8 to 1.9 with no recent updates.
Removing milestone flag for now.

**Comment by vkuzo** [comment]
I verified that the issue is not reproducible on master, with https://gist.github.com/vkuzo/771ce07a18ee77dd54bae2d1453b8d0e and inspecting the `metadata` variable in the state dict loader of `LinearPackedParams`.

**Comment by SalahuddinSSH** [comment]
Hi! I am using torch 2.2.2 and the same issue appeared. I have a custom architecture based on transformer model (Attention + FeedForward). I quantized my model and saved it successfully. However, when I tried to load the weights, it gave me the same error.

Preparing for weights loading

```
model.eval()
model.transformer.qconfig = get_default_qat_qconfig(args.quantize_engine) 
model.transformer.tok_embeddings.qconfig = float_qparams_weight_only_qconfig
torch.quantization.prepare(model.transformer, inplace=True)
torch.quantization.convert(model.transformer, inplace=True)
```

Weights Loading

```
model_path = "./models/test_model.pth"
# Ensure the state_dict is an OrderedDict
state_dict = torch.load(model_path, map_location='cpu')
res = model.load_state_dict(state_dict, strict=True)
```

Error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[15], line 6
      3 # Ensure the state_dict is an OrderedDict
      4 state_dict = torch.load(model_path, map_location='cpu')
----> 6 res = model.load_state_dict(state_dict, strict=True)

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:2139, in Module.load_state_dict(self, state_dict, strict, assign)
   2132         out = hook(module, incompatible_keys)
   2133         assert out is None, (
   2134             "Hooks registered with ``register_load_state_dict_post_hook`` are not"
   2135             "expected to return new values, if incompatible_keys need to be modified,"
   2136             "it should be done inplace."
   2137         )
-> 2139 load(self, state_dict)
   2140 del load
   2142 if strict:

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:2127, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2125         child_prefix = prefix + name + '.'
   2126         child_state_dict = {k: v for k, v in local_state_dict.items() if k.startswith(child_prefix)}
-> 2127         load(child, child_state_dict, child_prefix)
   2129 # Note that the hook can modify missing_keys and unexpected_keys.
   2130 incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:2127, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2125         child_prefix = prefix + name + '.'
   2126         child_state_dict = {k: v for k, v in local_state_dict.items() if k.startswith(child_prefix)}
-> 2127         load(child, child_state_dict, child_prefix)
   2129 # Note that the hook can modify missing_keys and unexpected_keys.
   2130 incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)

    [... skipping similar frames: Module.load_state_dict.<locals>.load at line 2127 (2 times)]

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:2127, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2125         child_prefix = prefix + name + '.'
   2126         child_state_dict = {k: v for k, v in local_state_dict.items() if k.startswith(child_prefix)}
-> 2127         load(child, child_state_dict, child_prefix)
   2129 # Note that the hook can modify missing_keys and unexpected_keys.
   2130 incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:2121, in Module.load_state_dict.<locals>.load(module, local_state_dict, prefix)
   2119 if assign:
   2120     local_metadata['assign_to_params_buffers'] = assign
-> 2121 module._load_from_state_dict(
   2122     local_state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
   2123 for name, child in module._modules.items():
   2124     if child is not None:

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/torch/ao/nn/quantized/modules/linear.py:220, in Linear._load_from_state_dict(self, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
    216 version = local_metadata.get('version', None)
    218 if version is None or version == 1:
    219     # We moved the parameters into a LinearPackedParameters submodule
--> 220     weight = state_dict.pop(prefix + 'weight')
    221     bias = state_dict.pop(prefix + 'bias')
    222     state_dict.update({prefix + '_packed_params.weight': weight,
    223                        prefix + '_packed_params.bias': bias})

KeyError: 'transformer.layers.0.attention.wq.weight'
```
