### ISSUE TITLE
QAT from scratch throws an error 

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#41791]
Trying to train a model from scratch using QAT throws an error. For example, I was trying to train the MobileNetV2 for CIFAR10 (https://gist.github.com/z-a-f/aca7c6f745361ad768ee73add7c5ad44), and got the following error:

```console
Epoch 1/100
Traceback (most recent call last):
  File "train_distillation.py", line 205, in <module>
    main()
  File "train_distillation.py", line 166, in main
    device=device
  File "/home/z-a-f/Desktop/Research/Quantized_Ensemble_Distillation/cifar10_run.py", line 18, in epoch_self_distillation_train
    student_logits = student_model(x)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Desktop/Research/Quantized_Ensemble_Distillation/qat_models/mobilenetv2.py", line 135, in forward
    x = self.features(x)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Desktop/Research/Quantized_Ensemble_Distillation/qat_models/mobilenetv2.py", line 67, in forward
    return self.conv(x)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/intrinsic/qat/modules/conv_fused.py", line 273, in forward
    return self.activation_post_process(F.relu(ConvBn2d._forward(self, input)))
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/fake_quantize.py", line 92, in forward
    _scale, _zero_point = self.calculate_qparams()
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/fake_quantize.py", line 87, in calculate_qparams
    return self.activation_post_process.calculate_qparams()
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/observer.py", line 295, in calculate_qparams
    return self._calculate_qparams(self.min_val, self.max_val)
  File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/observer.py", line 142, in _calculate_qparams
    min_val, max_val
AssertionError: min nan should be less than max nan
```
PyTorch version: 1.7.0a0+ffad0c8

Training parameters:

```console
dataset: CIFAR10
max_epochs: 100
batch_size: 256
optimizer: SGD
optimizer_kwargs:
  lr: 0.01
  weight_decay: 0.01
  momentum: 0.9
  nesterov: True
scheduler: OneCycleLR
scheduler_kwargs:
  max_lr: 0.01
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
Thanks for the report!  We've looked into this a few months ago and didn't find any evidence of QAT code misbehaving, it just looked like the doing QAT on random weights could lead to exploding gradients.  We verified that this issue goes away if you train for a couple of epochs before enabling QAT.

Closing for now, but feel free to reopen if we think it warrants further investigation.

**Comment by ai1361720220000** [comment]
> Trying to train a model from scratch using QAT throws an error. For example, I was trying to train the MobileNetV2 for CIFAR10 (https://gist.github.com/z-a-f/aca7c6f745361ad768ee73add7c5ad44), and got the following error:
> 
> ```
> Epoch 1/100
> Traceback (most recent call last):
>   File "train_distillation.py", line 205, in <module>
>     main()
>   File "train_distillation.py", line 166, in main
>     device=device
>   File "/home/z-a-f/Desktop/Research/Quantized_Ensemble_Distillation/cifar10_run.py", line 18, in epoch_self_distillation_train
>     student_logits = student_model(x)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Desktop/Research/Quantized_Ensemble_Distillation/qat_models/mobilenetv2.py", line 135, in forward
>     x = self.features(x)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/container.py", line 117, in forward
>     input = module(input)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Desktop/Research/Quantized_Ensemble_Distillation/qat_models/mobilenetv2.py", line 67, in forward
>     return self.conv(x)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/container.py", line 117, in forward
>     input = module(input)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/container.py", line 117, in forward
>     input = module(input)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/intrinsic/qat/modules/conv_fused.py", line 273, in forward
>     return self.activation_post_process(F.relu(ConvBn2d._forward(self, input)))
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/nn/modules/module.py", line 726, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/fake_quantize.py", line 92, in forward
>     _scale, _zero_point = self.calculate_qparams()
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/fake_quantize.py", line 87, in calculate_qparams
>     return self.activation_post_process.calculate_qparams()
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/observer.py", line 295, in calculate_qparams
>     return self._calculate_qparams(self.min_val, self.max_val)
>   File "/home/z-a-f/Git/pytorch-dev/pytorch/torch/quantization/observer.py", line 142, in _calculate_qparams
>     min_val, max_val
> AssertionError: min nan should be less than max nan
> ```
> 
> PyTorch version: 1.7.0a0+ffad0c8
> 
> Training parameters:
> 
> ```
> dataset: CIFAR10
> max_epochs: 100
> batch_size: 256
> optimizer: SGD
> optimizer_kwargs:
>   lr: 0.01
>   weight_decay: 0.01
>   momentum: 0.9
>   nesterov: True
> scheduler: OneCycleLR
> scheduler_kwargs:
>   max_lr: 0.01
> ```
> 
> cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

hello did you solve the problem?

**Comment by ai1361720220000** [comment]
> Pytorch 1.6， same problem occurs, is there any solution for this ?

hello, did you solve the problem?

**Comment by poor1017** [comment]
Pytorch 1.7.1， same problem occurs, is there any solution for this ?
