### ISSUE TITLE
Defining default argument with undefined tensor (Tensor x = {}) leads to static initialization order fiasco

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4197]
If you trigger this, you may see test failure like this:

```
======================================================================
ERROR: test_RReLU (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn.py", line 3587, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/var/lib/jenkins/pytorch-1/test/common_nn.py", line 653, in __call__
    self.test_noncontig(test_case, module, input)
  File "/var/lib/jenkins/pytorch-1/test/common_nn.py", line 681, in test_noncontig
    output = test_case._forward(module, input)
  File "test/test_nn.py", line 234, in _forward
    return module(input)
  File "/opt/conda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/torch/nn/modules/activation.py", line 91, in forward
    return F.rrelu(input, self.lower, self.upper, self.training, self.inplace)
  File "/opt/conda/lib/python2.7/site-packages/torch/nn/functional.py", line 715, in rrelu
    return torch._C._nn.rrelu(input, lower, upper, training)
RuntimeError: CPU backend type not enabled.
```

Or segfault on program exit, dying in Context destructor. Whether or not the failure happens will depend on your machine.

I'm working on fixing it.

**Comment by ezyang** [comment]
Actually, does not appear to be the problem.
