### ISSUE TITLE
Error, Compiled pytorch from source on power9 machine(cannot import name '_add_docstr' from 'torch._C' (unknown location)..)

### ISSUE THREAD

**Issue by Mon-ius** [pytorch/pytorch#42117]
I tried to compile pytorch from source on IBM power9. 

The compile progress was success. But when I import torch insider python the error shows
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/torch/__init__.py", line 326, in <module>
    from .tensor import Tensor
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/torch/tensor.py", line 9, in <module>
    from torch._C import _add_docstr
ImportError: cannot import name '_add_docstr' from 'torch._C' (unknown location)
```

cc @malfet

**Comment by ngimel** [comment]
Are you starting your python interpreter from pytorch root directory? Depending on how you installed pytorch that might lead to errors, try changing directory.

**Comment by Mon-ius** [comment]
As a non-root user, I install the pytorch on the specific folder.  

`python setup.py install --prefix ~/.share/conda-env/ml`

The full log for the compile progress is on:  [Full_log](https://github.com/Mon-ius/bluebear_hpc/blob/master/compile_log.txt)

**Comment by malfet** [comment]
@Mon-ius please make sure to start python interpreter with a different current working directory than source checkout folder (Those errors often appear when one tries to import pytorch from the source repository.

**Comment by Mon-ius** [comment]
Then, I found it failed on test.

`python run_test.py`
```

Fail to import hypothesis in common_utils, tests are not derandomized
Test executor: ['/rds/bear-apps/2019b/EL7-power9/software/Python/3.7.4-GCCcore-8.3.0/bin/python']
Running test_autograd ... [2020-07-27 18:12:42.201691]
Fail to import hypothesis in common_utils, tests are not derandomized
/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  "PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild "
```

```
test_autograd.py:6404: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  self.assertIsNone(a.grad)
...........s...................................................../castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1430: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/torch/csrc/utils/python_arg_parser.cpp:797.)
  cond = ((det < 0) ^ (sign < 0)).nonzero()
...............s.......................................................................................................................................................................................................s........................................s...........s......................................s............................................................s.................EEEEE..........................................................test_autograd.py:6525: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format. (Triggered internally at  /castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/aten/src/ATen/native/TensorIterator.cpp:918.)
  (a * b).sum().backward()
test_autograd.py:6525: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (Triggered internally at  /castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/aten/src/ATen/native/TensorIterator.cpp:924.)
  (a * b).sum().backward()
.................................................................................................................................................................s.................................../castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  "PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild "
........................................................................................................................................s........ss..................................sssssssssssssss......................................................................................................................................................................test_autograd.py:6404: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  self.assertIsNone(a.grad)
............ss..................................................ssssssssss...........................................sss.......................................................................................................................................................ss..................................................ssssss.........................................../castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  "PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild "
....................................................................sssssssssssssssss......................................................................................sssssssssss..................................................................................................................................................................................................
======================================================================
ERROR: test_solve_batched_broadcast_A_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4495, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4376, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
```

```
ERROR: test_solve_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4495, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4376, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 1,
```

**Comment by xiwei777** [comment]
dont start python on you compiled file

**Comment by Mon-ius** [comment]
> dont start python on you compiled file

Same thing, when I run pytorch test from other location.

**Comment by Mon-ius** [comment]
Tried to run test again. On `pytorch/run_test.py`

```
................................................................................................................................................................s..............s....................................s..s...............................................................................................................................................................s.......................................................test_autograd.py:6404: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  self.assertIsNone(a.grad)
...........s...................................................../castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1430: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/torch/csrc/utils/python_arg_parser.cpp:797.)
  cond = ((det < 0) ^ (sign < 0)).nonzero()
...............s.......................................................................................................................................................................................................s........................................s...........s......................................s............................................................s.................EEFEE..........................................................test_autograd.py:6525: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format. (Triggered internally at  /castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/aten/src/ATen/native/TensorIterator.cpp:918.)
  (a * b).sum().backward()
test_autograd.py:6525: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (Triggered internally at  /castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/download/pytorch/aten/src/ATen/native/TensorIterator.cpp:924.)
  (a * b).sum().backward()
.................................................................................................................................................................s.................................../castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  "PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild "
........................................................................................................................................s........ss..................................sssssssssssssss......................................................................................................................................................................test_autograd.py:6404: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  self.assertIsNone(a.grad)
............ss..................................................ssssssssss...........................................sss.......................................................................................................................................................ss..................................................ssssss.........................................../castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  "PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild "
....................................................................sssssssssssssssss......................................................................................sssssssssss..................................................................................................................................................................................................
======================================================================
ERROR: test_solve_batched_broadcast_A_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4495, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4376, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-1.1024,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.1024,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -1.1024,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -2.4509,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -2.4509,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -2.4509]])
analytical:tensor([[-1.1024, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000],
        [-0.0000, -1.1024, -0.0000,  ..., -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -1.1024,  ..., -0.0000, -0.0000, -0.0000],
        ...,
        [-0.0000, -0.0000, -0.0000,  ..., -2.4509, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -2.4509, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -2.4509]])


======================================================================
ERROR: test_solve_batched_broadcast_b_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4495, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4376, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 1.5572e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.5572e+00,  0.0000e+00,  ...,  0.0000e+00,
          8.4454e+05, -8.6908e+05],
        [ 0.0000e+00,  0.0000e+00,  1.5572e+00,  ..., -3.6515e-01,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00, -2.9233e-01,  ..., -1.9649e+00,
          0.0000e+00,  3.5468e+06],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -1.9649e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00, -1.9649e+00]])
analytical:tensor([[ 1.5572,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.5572,  0.0000,  ...,  0.0000,  1.7619,  0.0000],
        [ 0.0000,  0.0000,  1.5572,  ..., -0.3651,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.2923,  ..., -1.9649,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -1.9649,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -1.9649]])


======================================================================
ERROR: test_solve_batched_dims_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4495, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4376, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 318, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-1.3716,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.3716,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -1.3716,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.6611,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.6611,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.6611]])
analytical:tensor([[-1.3716, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000],
        [-0.0000, -1.3716, -0.0000,  ..., -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -1.3716,  ..., -0.0000, -0.0000, -0.0000],
        ...,
        [-0.0000, -0.0000, -0.0000,  ...,  0.6611, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000,  0.6611, -0.0000],
        [-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000,  0.6611]])


======================================================================
ERROR: test_solve_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4495, in check
    output_variable, (self_variable,) + args_variable)
  File "test_autograd.py", line 4376, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 324, in gradcheck
    'The tolerance for nondeterminism was {}.'.format(nondet_tol))
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 254, in fail_test
    raise RuntimeError(msg)
RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient. The tolerance for nondeterminism was 0.0.

======================================================================
FAIL: test_solve_batched_cpu (__main__.TestAutogradDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 217, in instantiated_test
    return test(self, device_arg)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 4578, in do_test
    check(name)
  File "test_autograd.py", line 4486, in check
    self.assertEqual(unpack_variables(output_variable), output_tensor)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1111, in assertEqual
    exact_dtype=exact_dtype, exact_device=exact_device)
  File "/castles/nr/projects/d/duanj-ai-in-medical-imaging/.share/conda-env/ml/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1085, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 3 element(s) (out of 125) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.625191373384391 (-2.064151111715964 vs. 0.561040261668427), which occurred at index (4, 2, 4).

----------------------------------------------------------------------
Ran 2377 tests in 4378.389s

FAILED (failures=1, errors=4, skipped=84, expected failures=1)
Traceback (most recent call last):
  File "pytorch/test/run_test.py", line 744, in <module>
    main()
  File "pytorch/test/run_test.py", line 733, in main
    raise RuntimeError(err)
RuntimeError: test_autograd failed!
```

**Comment by Mon-ius** [comment]
Create new lated issuse: [#42156](https://github.com/pytorch/pytorch/issues/42156)
