### ISSUE TITLE
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type int

### ISSUE THREAD

**Issue by smpurkis** [pytorch/pytorch#42391]
I am receiving this error on pytorch model export to onnx:
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type int

The error says that tuples are supported but got unsupported type NoneType. I checked the type of the variable out and it is a tuple at the error `out_vars, _ = _flatten(out)`

Code To Reproduce
```import warnings

import pytorch_lightning as pl
import torch
import torch.nn.functional as F
from sklearn.metrics import accuracy_score
from torch import nn

# from utils import get_dataloaders

warnings.filterwarnings("ignore")


def conv_block(in_channels=8, out_channels=16, kernel_size=3, stride=2, padding=1):
    return nn.Sequential(
        nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride,
                  padding=padding),
        nn.ReLU(),
        nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride,
                  padding=padding),
        nn.ReLU(),
        nn.Dropout2d(0.25))


class Net(pl.LightningModule):
    def __init__(self):
        super(Net, self).__init__()
        self.model_size = 1
        self.pool = nn.MaxPool2d(2, 2)

        self.conv1 = nn.Conv2d(in_channels=3, out_channels=8 * self.model_size, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=8 * self.model_size, out_channels=16 * self.model_size, kernel_size=3,
                               padding=1)
        self.conv3 = nn.Conv2d(in_channels=16 * self.model_size, out_channels=32 * self.model_size, kernel_size=3,
                               padding=1)
        self.conv = nn.Conv2d(in_channels=16 * self.model_size, out_channels=16 * self.model_size, kernel_size=3,
                              padding=1)

        self.conv_block_start = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=8 * self.model_size, kernel_size=3, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(in_channels=8 * self.model_size, out_channels=16 * self.model_size, kernel_size=3, stride=2,
                      padding=1), nn.ReLU())
        self.conv_block1 = conv_block(in_channels=16 * self.model_size, out_channels=16 * self.model_size,
                                      kernel_size=3,
                                      stride=2,
                                      padding=1)
        self.conv_block2 = conv_block(in_channels=16 * self.model_size, out_channels=16 * self.model_size,
                                      kernel_size=3,
                                      stride=2,
                                      padding=1)
        self.global_avg_pooling2D = nn.AdaptiveAvgPool2d(1)

        self.out = nn.Linear(in_features=16, out_features=2)

    def forward(self, t):
        t = t

        t = self.conv_block_start(t)
        t = self.conv_block1(t)
        t = self.conv_block2(t)

        t = self.global_avg_pooling2D(t)
        t = t.view(-1, t.shape[1])

        t = self.out(t)
        t = F.softmax(t, dim=1)
        return t

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat_probability = self(x)
        loss_fn = torch.nn.CrossEntropyLoss()
        loss = loss_fn(y_hat_probability, y)

        y_hat = torch.argmax(y_hat_probability, dim=1).cpu()
        acc = torch.tensor(accuracy_score(y.cpu(), y_hat, normalize=True))
        return {"loss": loss, "acc": acc}

    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat_probability = self(x)
        loss_fn = torch.nn.CrossEntropyLoss()

        val_loss = loss_fn(y_hat_probability, y)
        y_hat = torch.argmax(y_hat_probability, dim=1).cpu()
        val_acc = torch.tensor(accuracy_score(y.cpu(), y_hat, normalize=True))
        return {"val_loss": val_loss,
                "val_acc": val_acc}

    def training_epoch_end(self, outputs):
        acc = torch.stack([x["acc"] for x in outputs]).mean()

        log = {"acc": acc}

        return {"log": log, "progress_bar": log}

    def validation_epoch_end(self, outputs):
        val_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        val_acc = torch.stack([x["val_acc"] for x in outputs]).mean()

        log = {"val_loss": val_loss,
               "val_acc": val_acc}

        return {"log": log, "progress_bar": log}

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters())

    # def train_dataloader(self):
    #     train_dataloader = get_dataloaders()[0]
    #     return train_dataloader
    #
    # def val_dataloader(self):
    #     val_dataloader = get_dataloaders()[1]
    #     return val_dataloader


if __name__ == "__main__":
    rand_tensor = torch.rand(1, 3, 256, 256)
    net = Net()
    test = net(rand_tensor)
    # print(test.shape)
    # summary(net, rand_tensor)
    # train_dataloader, val_dataloader = get_dataloaders()
    # trainer = pl.Trainer(min_epochs=1, max_epochs=1)
    # trainer.fit(net)
    # torch.save(net, "bare_rtf")
    torch.onnx.export(net, rand_tensor.size(), "bare_rtf.onnx", verbose=True)
```
Stack trace:

```
Traceback (most recent call last):
  File "/home/sam/PycharmProjects/pytorch_playground/model.py", line 128, in <module>
    torch.onnx.export(net, rand_tensor.size(), "bare_rtf.onnx", verbose=True)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sam/envs/py7/lib/python3.7/site-packages/torch/jit/__init__.py", line 333, in forward
    in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type int
```
I've tried looking at related tickets with similar error (difference being `But got unsupported type int`). Other tickets:
https://github.com/pytorch/pytorch/issues/29551 - still open, mentions something about wrapping multi-inputs as a dict
https://discuss.pytorch.org/t/torch-onnx-export-fails/72418 - mentions the types in `self.forward()` being non-Tensors, mine are all Tensors, from input to output, so can't be that.
https://github.com/pytorch/pytorch/issues/13040 - still open, multiple reports, with a solution?! but can't work out exactly what it means

Environment:
onnx==1.7.0
onnxruntime==1.4.0
pytorch-lightning==0.8.5
torch==1.5.1
torch-summary==1.4.0
torchstat==0.0.7
torchsummary==1.5.1
torchvision==0.6.1
scikit-learn==0.23.1
scipy==1.5.2
Python 3.7.8

cc @suo @gmagogsfm

**Comment by carlsummer** [comment]
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type Yolact

**Comment by carlsummer** [comment]
As of March 10, 2019, Pytorch DataParallel still doesn't support JIT Script Modules

**Comment by menchunlei** [comment]
i met the same error, but can't solve it.

**Comment by 9lan9** [comment]
hi, do you have the solution now?

**Comment by 9lan9** [comment]
> hi, do you have the solution now?

can print the content in `in_vars, in_desc = _flatten(args)` to see the problem

**Comment by menchunlei** [comment]
> hi, do you have the solution now?

Have a try to put the inputs/outputs as tensor not scalar.

**Comment by 9lan9** [comment]
> > hi, do you have the solution now?
> 
> Have a try to put the inputs/outputs as tensor not scalar.

yes, already solved it.

**Comment by phemiloyeAI** [comment]
> 

Hi, @9lan9  I'm facing a similar issue. Could you share how you fixed it? thanks
