### ISSUE TITLE
libtorch_python.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#42450]
Hi
Is there any idea about this error?
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import torch
  File "/home/mahmood/.local/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /home/mahmood/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: _Py_ZeroStruct
corrupted size vs. prev_size
Aborted (core dumped)
```
I didn't have such a problem. I also tried to reinstall pythorch via `python3 setup.py install --user`. I don't see any problem with this output:
```
[100%] Built target torch_python
Install the project...
-- Install configuration: "Release"
running install
running build
running build_py
copying torch/version.py -> build/lib.linux-x86_64-3.6/torch
copying caffe2/proto/prof_dag_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/caffe2_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/predictor_consts_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/torch_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/hsm_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/caffe2_legacy_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
copying caffe2/proto/metanet_pb2.py -> build/lib.linux-x86_64-3.6/caffe2/proto
running build_ext
-- Building with NumPy bindings
-- Detected cuDNN at /home/mahmood/cudnn-7.6.2/lib64, /home/mahmood/cudnn-7.6.2/include
-- Detected CUDA at /home/mahmood/cuda-10.1.168
-- Using MKLDNN
-- Not using CBLAS in MKLDNN
-- Building NCCL library
-- Building with distributed package

Copying extension caffe2.python.caffe2_pybind11_state
torch/lib/python3/dist-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so does not exist

Copying extension caffe2.python.caffe2_pybind11_state_gpu
torch/lib/python3/dist-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so does not exist
running install_lib
copying build/lib.linux-x86_64-3.6/torch/version.py -> /home/mahmood/.local/lib/python3.6/site-packages/torch
copying build/lib.linux-x86_64-3.6/caffe2/proto/prof_dag_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/caffe2_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/predictor_consts_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/torch_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/hsm_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/caffe2_legacy_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
copying build/lib.linux-x86_64-3.6/caffe2/proto/metanet_pb2.py -> /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/torch/version.py to version.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/prof_dag_pb2.py to prof_dag_pb2.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/caffe2_pb2.py to caffe2_pb2.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/predictor_consts_pb2.py to predictor_consts_pb2.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/torch_pb2.py to torch_pb2.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/hsm_pb2.py to hsm_pb2.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/caffe2_legacy_pb2.py to caffe2_legacy_pb2.cpython-36.pyc
byte-compiling /home/mahmood/.local/lib/python3.6/site-packages/caffe2/proto/metanet_pb2.py to metanet_pb2.cpython-36.pyc
running install_egg_info
running egg_info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing entry points to torch.egg-info/entry_points.txt
writing top-level names to torch.egg-info/top_level.txt
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
removing '/home/mahmood/.local/lib/python3.6/site-packages/torch-1.4.0a0+2488231.egg-info' (and everything under it)
Copying torch.egg-info to /home/mahmood/.local/lib/python3.6/site-packages/torch-1.4.0a0+2488231.egg-info
running install_scripts
Installing convert-caffe2-to-onnx script to /home/mahmood/.local/bin
Installing convert-onnx-to-caffe2 script to /home/mahmood/.local/bin
```
Any note on that?

cc @ezyang @seemethere @malfet

**Comment by agolynski** [comment]
Could you try following instructions here?
https://github.com/pytorch/pytorch/issues/31483

**Comment by mahmoodn** [comment]
Sorry for duplication. I will try reinstalling one more time.
