### ISSUE TITLE
ONNX : Exporting HardShrink or SoftShrink operator to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by nitin2212** [pytorch/pytorch#42470]
##Bug
RuntimeError: Exporting the operator softshrink to ONNX opset version 9 is not supported.

I tried to export a simple model having SoftShrink/HardShrink Activation layer  but it give the error:

```
Traceback (most recent call last):
  File "activations.py", line 19, in <module>
    torch.onnx.export(model, dummy_input, "activation.onnx", opset_version=12)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 351, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 154, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 199, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 739, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py", line 109, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator softshrink to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

## To Reproduce

Export this model :

```
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.Softshrink(),
    torch.nn.Linear(H, D_out),
)

```

## Expected behavior

Successfully export the model to onnx.

## Environment

torch version : 1.5.1
onnx version : 1.7
python: 3.6

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Yes, this is most likely not supported in the exporter. Could you please consider submitting a PR for it?

**Comment by shubhambhokare1** [comment]
Hi @nitin2212 ,

We’ve gone ahead and closed this issue because it has been resolved elsewhere. This resolution can be found [here](https://github.com/pytorch/pytorch/pull/66969).
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
