### ISSUE TITLE
pytorch tests failed

### ISSUE THREAD

**Issue by beew** [pytorch/pytorch#42498]
## 🐛 Bug
compiled pytorch from source successfully, but some tests failed

## To Reproduce
After finish installing, run python testsrun_test.py, 5 tests failed
```
ERROR: test_cpp_frontend_module_has_same_output_as_python (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 467, in test_cpp_frontend_module_has_same_output_as_python
    extension = torch.utils.cpp_extension.load(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 965, in load
    return _jit_compile(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1192, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1542, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_cpp_frontend_module_has_up_to_date_attributes (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 595, in test_cpp_frontend_module_has_up_to_date_attributes
    extension = torch.utils.cpp_extension.load(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 965, in load
    return _jit_compile(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1192, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1542, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_cpp_frontend_module_python_inter_op (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 498, in test_cpp_frontend_module_python_inter_op
    extension = torch.utils.cpp_extension.load(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 965, in load
    return _jit_compile(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1192, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1542, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_cpp_frontend_module_python_inter_op_with_cuda (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 617, in test_cpp_frontend_module_python_inter_op_with_cuda
    extension = torch.utils.cpp_extension.load(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 965, in load
    return _jit_compile(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1192, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1542, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bernard/opt/python38/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: generic_type: type "Net" referenced unknown base type "torch::nn::Module"

======================================================================
ERROR: test_warning (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 749, in test_warning
    warn_mod.foo(t, 1)
RuntimeError: Error with CPUDoubleType

----------------------------------------------------------------------
Ran 23 tests in 220.052s

FAILED (errors=5)
Traceback (most recent call last):
  File "run_test.py", line 752, in <module>
    main()
  File "run_test.py", line 741, in main
    raise RuntimeError(err)
RuntimeError: test_cpp_extensions_jit failed!

## Environment

 - PyTorch Version: 1.7.0a0+4cdbe5c
 - OS (e.g., Linux): Ubuntu Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 

```
export BUILD_ONNX_PYTHON=1 USE_CUDA=1 USE_CUDNN=1 USE_MKLDNN=1 USE_TENSORRT=1 USE_OPENCV=1 USE_FFMPEG=1 USE_LMDB=1

python setup.py build

python setup.py install 
```
In my setup, python = python3

 - Python version: 3.8.5
 - CUDA/cuDNN version:CUDA10.0, CUDNN7.6.5.32.1
 - GPU models and configuration: GTX1070

**Comment by beew** [comment]
run_test.py for pytorch 1.6.0 on python3.7.8 gives these additional errors in the begining
```
Running test_autograd ... [2020-08-04 09:20:27.454127]
..[W python_anomaly_mode.cpp:42] Warning: Error detected in MyFuncBackward. No forward pass information available. Enable detect anomaly during forward pass for more information. (function print_stack)
[W python_anomaly_mode.cpp:60] Warning: Error detected in MyFuncBackward. Traceback of forward call that caused the error:
  File "test_autograd.py", line 6588, in <module>
    run_tests()
  File "/home/bernard/opt/python37/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 284, in run_tests
    unittest.main(argv=argv)
  File "/home/bernard/opt/python37/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/bernard/opt/python37/lib/python3.7/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/bernard/opt/python37/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/home/bernard/opt/python37/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/bernard/opt/python37/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/home/bernard/opt/python37/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/home/bernard/opt/python37/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "test_autograd.py", line 3311, in test_anomaly_detect_nan
    out = MyFunc.apply(inp, inp, False)
 (function print_stack)
.......................s................................test_autograd.py:370: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  self.assertIsNone(x.grad)
..test_autograd.py:422: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  self.assertIsNone(x_list[0].grad)
test_autograd.py:429: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
```

**Comment by ailzhang** [comment]
Hmmm did you build pytorch 1.6 and 1.7 from source?

**Comment by beew** [comment]
@ailzhang 
yes.
