### ISSUE TITLE
NCCL operation fails with torch.int16 tensors

### ISSUE THREAD

**Issue by vineeths96** [pytorch/pytorch#42519]
## 🐛 Bug

NCCL operations (like torch.distributed.all_gather()) fails with error "Unsupported data type for NCCL process group" when tensors of toch.int16 type are used.

## To Reproduce

1. Code for the MWE
```python
import torch
import torch.distributed as dist
import argparse
import os

def initiate_distributed():
    env_dict = {
        key: os.environ[key]
        for key in ("MASTER_ADDR", "MASTER_PORT", "RANK", "WORLD_SIZE")
    }

    print(f"[{os.getpid()}] Initializing Process Group with: {env_dict}")
    dist.init_process_group(backend='nccl', init_method="env://")

    print(f"[{os.getpid()}] Initialized Process Group with: RANK = {dist.get_rank()}, "
          + f"WORLD_SIZE = {dist.get_world_size()}" + f", backend={dist.get_backend()}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--local_rank', type=int, default=0)
    parser.add_argument('--local_world_size', type=int, default=1)
    args = parser.parse_args()

    initiate_distributed()
    n_workers = torch.distributed.get_world_size()

    device = torch.device(f'cuda:{args.local_rank}')
    torch.random.manual_seed(args.local_rank)

    tensor = torch.tensor([-1,2,3,-5], device=device, dtype=torch.int16)
    tensor_list = [torch.empty_like(tensor) for i in range(n_workers)]

    gather_op = dist.all_gather(tensor_list, tensor, async_op=True)
    gather_op.wait()
```
1. Launch with torch.distributed.launch by
```python
 python -m torch.distributed.launch --nnode=1 --node_rank=0 --nproc_per_node=2 compressors_test.py --local_world_size=2
```

Error trace:
```
[109941] Initializing Process Group with: {'MASTER_ADDR': '127.0.0.1', 'MASTER_PORT': '29500', 'RANK': '0', 'WORLD_SIZE': '2'}
[109942] Initializing Process Group with: {'MASTER_ADDR': '127.0.0.1', 'MASTER_PORT': '29500', 'RANK': '1', 'WORLD_SIZE': '2'}
[109942] Initialized Process Group with: RANK = 1, WORLD_SIZE = 2, backend=nccl
[109941] Initialized Process Group with: RANK = 0, WORLD_SIZE = 2, backend=nccl
Traceback (most recent call last):
  File "compressors_test.py", line 34, in <module>
    gather_op = dist.all_gather(tensor_list, tensor, async_op=True)
  File "/home/vineeth/anaconda3/envs/QSGD-PT/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1185, in all_gather
Traceback (most recent call last):
  File "compressors_test.py", line 34, in <module>
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: Unsupported data type for NCCL process group
    gather_op = dist.all_gather(tensor_list, tensor, async_op=True)
  File "/home/vineeth/anaconda3/envs/QSGD-PT/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1185, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: Unsupported data type for NCCL process group
Traceback (most recent call last):
  File "/home/vineeth/anaconda3/envs/QSGD-PT/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vineeth/anaconda3/envs/QSGD-PT/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vineeth/anaconda3/envs/QSGD-PT/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/vineeth/anaconda3/envs/QSGD-PT/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/vineeth/anaconda3/envs/QSGD-PT/bin/python', '-u', 'compressors_test.py', '--local_rank=1', '--local_world_size=2']' returned non-zero exit status 1.
```

## Expected behavior
Successful NCCL operation.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 1080Ti *2
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
@vineeths96 below are the currently supported types in `ProcesssGroupNCCL`:

https://github.com/pytorch/pytorch/blob/ecb88c5d11895a68e5f20917d27a0debbc0f0697/torch/lib/c10d/ProcessGroupNCCL.cpp#L46-L59

Just checked NCCL's data types, they don't have 16-bits integer either: https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#nccldatatype-t

Is it acceptable to use 32-bits integer or 16-bits floating point number for your application?

**Comment by vineeths96** [comment]
@mrshenli Thank you for the clarification. 

I am actually trying to reduce the number of bits communicated during allreduce. Using 32bit int or 16bit floats would increase communication. I will try to find a workaround. 

Anyways I am closing this issue for now.

**Comment by Bing-a-ling7** [comment]
Hello, I encounter this issus today. However, I can't use other type except `int16` in my application. 
**Is there a way to solve this problem? I want multi-GPU to train my model.**
