### ISSUE TITLE
Python3 segfaults or doesn't load torch after installation

### ISSUE THREAD

**Issue by fsdoma** [pytorch/pytorch#42526]
#42035 

 after installing torch using ``pip3 install torch'' 

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'     ## before installation
>>> import torch
Segmentation fault (core dumped)                            ## after installation
frank@thunderstorm:~$ python                                ## installed torchvision using ``pip3 install -U torchvision''
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named torch                       # at least no segfault anymore
>>> 

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): pip3
- Build command you used (if compiling from source):
- OS: UbuntuStudio 18.04, 4.15.0-112-lowlatency #113-Ubuntu SMP PREEMPT x86_64 GNU/Linux
- PyTorch version: torch-1.6.0
- Python version: 3.6.9
- CUDA/cuDNN version: 
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version: not installed
- Versions of any other relevant libraries:

**Comment by glaringlee** [comment]
@fsdoma 
Can you check `pip3 list` see whether torch is installed?

**Comment by glaringlee** [comment]
@malfet 
This is not really build, probably user env issue. 
We don't have a 'installation' related tag, mark this as build for now.

**Comment by malfet** [comment]
It's very often the case , that pip and python belong to a different version. Can you please run the installation as `python3 -m pip install torch` and then, if previous command succeeds, run  `python3 -c 'import torch;print(torch.__version__)`

**Comment by fsdoma** [comment]
This approach solved the problem. If I start python3 ``import torch''
succeeds.
I cannot understand tough why pip3 list showed torch (1.6.0) but within
python I got a message that there is no module torch.

Maybe instead of using pip3 in bash I should use the ``python3 -c 'import
<module>;print(<module>.__version__)'' approach in the future.
I'll try this out - thanks for the hint.
