### ISSUE TITLE
Build script complains that gcc is < 6 even though gcc version is 8

### ISSUE THREAD

**Issue by chsasank** [pytorch/pytorch#42581]
## 🐛 Bug

Build script complains that gcc is < 6 even though gcc version is 8. see environment for evidence

## To Reproduce

1. Install miniconda3.
1. Follow instructions to clone and build pytorch: https://github.com/pytorch/pytorch/#from-source
1. python setup.py bdist_wheel

```
(torch_cpu) sasank@qure3:pytorch$ python setup.py bdist_wheel                                                                                                                                                  
Building wheel torch-1.4.0a0+7404463
-- Building version 1.4.0a0+7404463
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/users/sasank/personal/opengc/pytorch/torch -DCMAKE_PREFIX_PATH=/home/users/sasank/miniconda3/envs/torch_cpu -DNUMPY_INCLUDE_DIR=/home/users/sasank/miniconda3/envs/torch_cpu/lib/python3.7/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/users/sasank/miniconda3/envs/torch_cpu/bin/python -DPYTHON_INCLUDE_DIR=/home/users/sasank/miniconda3/envs/torch_cpu/include/python3.7m -DPYTHON_LIBRARY=/home/users/sasank/miniconda3/envs/torch_cpu/lib/libpython3.7m.a -DTORCH_BUILD_VERSION=1.4.0a0+7404463 -DUSE_CUDA=0 -DUSE_NUMPY=True /home/users/sasank/personal/opengc/pytorch
CMake Error at cmake/MiscCheck.cmake:29 (message):
  Please use GCC 6 or higher on Ubuntu 17.04 and higher.  For more
  information, see: https://github.com/caffe2/caffe2/issues/1633
Call Stack (most recent call first):
  CMakeLists.txt:369 (include)


-- Configuring incomplete, errors occurred!
See also "/home/users/sasank/personal/opengc/pytorch/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/users/sasank/personal/opengc/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2                                                                                                      
    rerun_cmake)
  File "/home/users/sasank/personal/opengc/pytorch/tools/setup_helpers/cmake.py", line 319, in generate
    self.run(args, env=my_env)
  File "/home/users/sasank/personal/opengc/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/users/sasank/miniconda3/envs/torch_cpu/lib/python3.7/subprocess.py", line 363, in check_call                                                                                                     
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/users/sasank/personal/opengc/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/users/sasank/miniconda3/envs/torch_cpu', '-DNUMPY_INCLUDE_DIR=/home/users/sasank/miniconda3/envs/torch_cpu/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/users/sasank/miniconda3/envs/torch_cpu/bin/python', '-DPYTHON_INCLUDE_DIR=/home/users/sasank/miniconda3/envs/torch_cpu/include/python3.7m', '-DPYTHON_LIBRARY=/home/users/sasank/miniconda3/envs/torch_cpu/lib/libpython3.7m.a', '-DTORCH_BUILD_VERSION=1.4.0a0+7404463', '-DUSE_CUDA=0', '-DUSE_NUMPY=True', '/home/users/sasank/personal/opengc/pytorch']' returned non-zero exit status 1.                              
(torch_cpu) sasank@qure3:pytorch$ gcc --version
gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(torch_cpu) sasank@qure3:pytorch$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

```

## Expected behavior

Build and install happens smoothly.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
$ python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 440.44
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.1           py37hbc911f0_0
[conda] numpy-base                1.19.1           py37hfa32c7d_0

```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.7
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

## Additional context

I installed gcc-8 using command from SO here: https://askubuntu.com/a/1028656

**Comment by chsasank** [comment]
Turns out conda is doing some random things with env variables which seem to be messing things up. See https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html

```
(torch_cpu) sasank@qure3:pytorch$ printenv  | grep cc
GCC_NM=/home/users/sasank/miniconda3/envs/torch_cpu/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
GCC_RANLIB=/home/users/sasank/miniconda3/envs/torch_cpu/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
GCC_AR=/home/users/sasank/miniconda3/envs/torch_cpu/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
CC=/home/users/sasank/miniconda3/envs/torch_cpu/bin/x86_64-conda_cos6-linux-gnu-cc
GCC=/home/users/sasank/miniconda3/envs/torch_cpu/bin/x86_64-conda_cos6-linux-gnu-gcc
```

Even the `/home/users/sasank/miniconda3/envs/torch_cpu/bin/x86_64-conda_cos6-linux-gnu-gcc` is >6 version anyway.

**Comment by thinking-tower** [comment]
@chsasank what happens if you explicitly passed in the locations of the compiler?

`CC=<where your gcc8.0 is> CXX=<where your g++8.0 is> python setup.py bdist_wheel`

**Comment by chsasank** [comment]
Unfortunately, I got the same error as above. 

Since then, I have removed the existing miniconda3 installation and reinstalled miniconda (again). And the error for gcc is gone. I can work on reproducing the issue with fresh miniconda installation.

**Comment by chsasank** [comment]
I've just tried to reproduce the issue again with a fresh environment and I'm not able to. Should've been some issue with my conda installation. You can close the issue and reopen if somebody gets the same error.

**Comment by gchanan** [comment]
removing high priority, this looks extremely likely to be a configuration issue.

**Comment by gakadam** [comment]
I am facing the same issue with gcc-8.4 and CUDA-10.2.

gcc-8.4 is in my home folder, but `python setup.py install` picks up `/usr/local/bin/gcc` which is gcc-4.8.5

I tried
`CC=/mypathto/gcc-8.4`
`CXX=/mypathto/gxx-8.4`

My conda was installed after gcc-8.4.

In my `printenv` I do not see `GCC/GCC_RANLIB` etc.
I do see `CC` and `CXX` directing to proper path.

How to rectify this?

Thank you.
