### ISSUE TITLE
CI tests run without scipy, leading to breakages

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#4260]
On master, test_beta_log_prob is broken
```
root@99bcba64cb05:/opt/pytorch/pytorch/test# python test_distributions.py 
............/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/distributions/distribution.py:39: UserWarning: sample_n will be deprecated. Use .sample((n,)) instead
  warnings.warn('sample_n will be deprecated. Use .sample((n,)) instead', UserWarning)
...E............/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:2329: RuntimeWarning: overflow encountered in exp
  return np.exp(self._logpdf(x, a))
......
======================================================================
ERROR: test_beta_log_prob (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_distributions.py", line 361, in test_beta_log_prob
    self.assertAlmostEqual(actual_log_prob, expected_log_prob, places=3)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/unittest/case.py", line 870, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: type numpy.ndarray doesn't define __round__ method

----------------------------------------------------------------------
Ran 34 tests in 1.055s

FAILED (errors=1)
```
and looks like it is just skipped in CI because of https://github.com/pytorch/pytorch/blob/master/test/test_distributions.py#L12-L18. PR that added this test is #4117, cc @fritzo
This is not the first time CI passed due to tests being skipped, and as more things are added that depend on scipy, may be CI should be updated.

**Comment by fritzo** [comment]
Thanks, I'll take a look. What is your `python --version` and `pip --freeze`?

**Comment by ngimel** [comment]
```
root@99bcba64cb05:/opt/pytorch/pytorch/test# python --version
Python 3.6.3 :: Anaconda, Inc.
root@99bcba64cb05:/opt/pytorch/pytorch/test# conda list
# packages in environment at /opt/conda:
#
asn1crypto                0.22.0           py36h265ca7c_1  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2017.7.27.1      py36h8b7b77e_0  
cffi                      1.10.0           py36had8d393_1  
chardet                   3.0.4            py36h0f667ec_1  
conda                     4.3.30           py36h5d9f9f4_0  
conda-build               3.1.2                    py36_0  
conda-env                 2.6.0                h36134e3_1  
conda-verify              2.0.0            py36h98955d8_0  
cryptography              2.0.3            py36ha225213_1  
filelock                  2.0.13           py36h646ffb5_0  
glob2                     0.6              py36he249c77_0  
idna                      2.6              py36h82fb2a8_1  
jinja2                    2.10             py36ha16c418_0  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                h4deb6c0_3  
libgcc-ng                 7.2.0                h7cc24e2_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
markupsafe                1.0              py36hd9260cd_1  
ncurses                   6.0                  h06874d7_1  
openssl                   1.0.2l               h077ae2c_5  
patchelf                  0.9                  hf79760b_2  
pip                       9.0.1            py36h8ec8b28_3  
pkginfo                   1.4.1            py36h215d178_1  
pycosat                   0.6.2            py36h1a0ea17_1  
pycparser                 2.18             py36hf9f622e_1  
pyopenssl                 17.2.0           py36h5cc804b_0  
pysocks                   1.6.7            py36hd97a5b1_1  
python                    3.6.3                hc9025b9_1  
pyyaml                    3.12             py36hafb9ca4_1  
readline                  7.0                  hac23ff0_3  
requests                  2.18.4           py36he2e5f8d_1  
ruamel_yaml               0.11.14          py36ha2fb22d_2  
setuptools                36.5.0           py36he42e2e1_0  
six                       1.10.0           py36hcac75e4_1  
sqlite                    3.20.1               h6d8b0f3_1  
tk                        8.6.7                h5979e9b_1  
urllib3                   1.22             py36hbe7ace6_0  
wheel                     0.29.0           py36he7f4e38_1  
xz                        5.2.3                h2bcbf08_1  
yaml                      0.1.7                h96e3832_1  
zlib                      1.2.11               hfbfcf68_1  
root@99bcba64cb05:/opt/pytorch/pytorch/test# pip freeze
asn1crypto==0.23.0
attrs==17.3.0
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
codecov==2.0.10
coverage==4.4.2
cryptography==2.1.4
cymem==1.31.2
cytoolz==0.8.2
decorator==4.1.2
dill==0.2.7.1
flake8==3.5.0
ftfy==4.4.3
html5lib==1.0.1
idna==2.6
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.0
mccabe==0.6.1
murmurhash==0.26.4
nltk==3.2.5
numpy==1.13.3
olefile==0.44
parso==0.1.1
pathlib==1.0.1
pexpect==4.3.0
pickleshare==0.7.4
Pillow==4.3.0
plac==0.9.6
pluggy==0.6.0
preshed==1.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
pycodestyle==2.3.1
pycparser==2.18
pyflakes==1.6.0
Pygments==2.2.0
pyOpenSSL==17.5.0
PySocks==1.6.7
pytest==3.3.1
pytest-cov==2.5.1
pytest-pythonpath==0.7.1
PyYAML==3.12
regex==2017.11.9
requests==2.18.4
revtok==0.0.1
scipy==1.0.0
simplegeneric==0.8.1
six==1.11.0
spacy==1.9.0
termcolor==1.1.0
thinc==6.5.2
toolz==0.8.2
torch==0.4.0a0
torchtext==0.2.0
torchvision==0.2.0
tqdm==4.19.4
traitlets==4.3.2
ujson==1.35
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.10.11
```

**Comment by fritzo** [comment]
Thanks, I'm trying to reproduce and will submit a fix asap. Sorry for the breakage!

**Comment by ngimel** [comment]
Changing ```expected_log_prob``` to ```expected_log_prob[0]``` here https://github.com/pytorch/pytorch/blob/master/test/test_distributions.py#L361 fixes it for me, I don't know if this fix is appropriate. No problem :-), CI should catch such things, hence my issue is about CI, not about a particular PR.

**Comment by ezyang** [comment]
After we merge #4261 it will be very easy to add `pip install scipy` to the CI.

**Comment by ezyang** [comment]
Hmm, actually, I'm a bit confused, because our CI docker images already have scipy on them...

**Comment by ngimel** [comment]
Can you take a look if tests in test_distributions.py were actually skipped?

**Comment by ezyang** [comment]
Yes, let me turn on verbose test output from PyTorch

**Comment by alicanb** [comment]
I just checked the CI build on one the latest PRs, it says 11 tests were skipped.

**Comment by fritzo** [comment]
One of the `test_distributions.py` tests is now failing due to refactoring in the last few days. It would have been caught by CI.
<details>

```
=================================================== FAILURES ====================================================
___________________________________ TestDistributions.test_gamma_sample_grad ____________________________________

self = <test_distributions.TestDistributions testMethod=test_gamma_sample_grad>

    @unittest.skipIf(not TEST_NUMPY, "Numpy not found")
    def test_gamma_sample_grad(self):
        self._set_rng_seed(1)
        num_samples = 100
        for alpha in [1e-3, 1e-2, 1e-1, 1e0, 1e1, 1e2, 1e3, 1e4]:
            alphas = Variable(torch.Tensor([alpha] * num_samples), requires_grad=True)
            betas = Variable(torch.ones(num_samples))
            x = Gamma(alphas, betas).rsample()
>           x.sum().backward()

test/test_distributions.py:415:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
torch/autograd/variable.py:103: in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

variables = (Variable containing:
1.00000e-07 *
  3.8609
[torch.DoubleTensor of size 1]
,)
grad_variables = (Variable containing:
 1
[torch.DoubleTensor of size 1]
,), retain_graph = False
create_graph = False

    def backward(variables, grad_variables=None, retain_graph=None, create_graph=False):
        """Computes the sum of gradients of given variables w.r.t. graph leaves.

        The graph is differentiated using the chain rule. If any of ``variables``
        are non-scalar (i.e. their data has more than one element) and require
        gradient, the function additionally requires specifying ``grad_variables``.
        It should be a sequence of matching length, that contains gradient of
        the differentiated function w.r.t. corresponding variables (``None`` is an
        acceptable value for all variables that don't need gradient tensors).

        This function accumulates gradients in the leaves - you might need to zero
        them before calling it.

        Arguments:
            variables (sequence of Variable): Variables of which the derivative will be
                computed.
            grad_variables (sequence of (Tensor, Variable or None)): Gradients w.r.t.
                each element of corresponding variables.  Any tensors will be
                automatically converted to Variables that are volatile unless
                ``create_graph`` is ``True``.  None values can be specified for scalar
                Variables or ones that don't require grad. If a None value would
                be acceptable for all grad_variables, then this argument is optional.
            retain_graph (bool, optional): If ``False``, the graph used to compute the grad
                will be freed. Note that in nearly all cases setting this option to ``True``
                is not needed and often can be worked around in a much more efficient
                way. Defaults to the value of ``create_graph``.
            create_graph (bool, optional): If ``True``, graph of the derivative will
                be constructed, allowing to compute higher order derivative products.
                Defaults to ``False``.
        """
        variables = (variables,) if isinstance(variables, Variable) else tuple(variables)

        if grad_variables is None:
            grad_variables = [None] * len(variables)
        elif isinstance(grad_variables, Variable) or torch.is_tensor(grad_variables):
            grad_variables = [grad_variables]
        else:
            grad_variables = list(grad_variables)

        grad_variables = _make_grads(variables, grad_variables)
        if retain_graph is None:
            retain_graph = create_graph

        Variable._execution_engine.run_backward(
>           variables, grad_variables, retain_graph, create_graph)
E       RuntimeError: VariableType::_standard_gamma_grad NYI

torch/autograd/__init__.py:83: RuntimeError
```
</details>

**Comment by ezyang** [comment]
OK, I think the problem is we installed scipy on the system Python but not the Conda one. I'm on it.

**Comment by ezyang** [comment]
We are no longer skipping at distributions tests in master CI:

```
Running torch.distributions tests
....................../opt/conda/lib/python3.6/site-packages/torch/distributions/distribution.py:53: UserWarning: sample_n will be deprecated. Use .sample((n,)) instead
  warnings.warn('sample_n will be deprecated. Use .sample((n,)) instead', UserWarning)
............/opt/conda/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:920: RuntimeWarning: overflow encountered in exp
  return np.exp(self._logpdf(x, df))
....................
----------------------------------------------------------------------
Ran 54 tests in 1.904s

OK
```
