### ISSUE TITLE
pyinstaller exe generated fails to run  Faster RCNN model due to runtime exception cannot find nms function

### ISSUE THREAD

**Issue by karimhasebou** [pytorch/pytorch#42618]
Whenever i run the faster RCNN model provided in pytorch pretrained models list i get the following stacktrace when running the exe generated 

  File "site-packages\flask\app.py", line 2447, in wsgi_app
  File "site-packages\flask\app.py", line 1952, in full_dispatch_request
  File "site-packages\flask\app.py", line 1821, in handle_user_exception
  File "site-packages\flask\_compat.py", line 39, in reraise
  File "site-packages\flask\app.py", line 1950, in full_dispatch_request
  File "site-packages\flask\app.py", line 1936, in dispatch_request
  File "pytorchVizTool\flaskr\ModelServer.py", line 95, in GeneratePredsForFile
  File "pytorchVizTool\flaskr\ModelServer.py", line 95, in <listcomp>
  File "pytorchVizTool\flaskr\FasterRCNN.py", line 100, in predict
  File "pytorchVizTool\flaskr\FasterRCNN.py", line 142, in get_bounding_box_prediction
  File "site-packages\torch\nn\modules\module.py", line 550, in __call__
  File "site-packages\torchvision\models\detection\generalized_rcnn.py", line 70, in forward
  File "site-packages\torch\nn\modules\module.py", line 550, in __call__
  File "site-packages\torchvision\models\detection\rpn.py", line 488, in forward
  File "site-packages\torchvision\models\detection\rpn.py", line 410, in filter_proposals
  File "site-packages\torchvision\ops\boxes.py", line 75, in batched_nms
  File "site-packages\torchvision\ops\boxes.py", line 35, in nms
  File "site-packages\torch\_ops.py", line 61, in __getattr__
RuntimeError: No such operator torchvision::nms

Running the python files directly doesnt give that error.

During the build i got these warnings

59296 WARNING: lib not found: impi.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_blacs_intelmpi_ilp64.dll
59552 WARNING: lib not found: msmpi.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_blacs_msmpi_ilp64.dll
59600 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_blacs_mpich2_lp64.dll
59776 WARNING: lib not found: msmpi.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_blacs_msmpi_lp64.dll
59829 WARNING: lib not found: pgc14.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_pgi_thread.dll
59833 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_pgi_thread.dll
59846 WARNING: lib not found: pgf90.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_pgi_thread.dll
60129 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_blacs_mpich2_ilp64.dll
60181 WARNING: lib not found: impi.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\Library\bin\mkl_blacs_intelmpi_lp64.dll
60702 WARNING: lib not found: torch_python.dll dependency of c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\torch\_C.cp35-win_amd64.pyd

I have checked, my pc does indeed have torch_python.dll so am quite confused by the error message

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
Please provide version of Python, PyTorch, TorchVision as well as your OS and Cuda version. (You can do it by running `python -mtorch.utils.collect_env` and pasting its output here, if you don't have a functioning PyTorch installation, you can directly download and run script from https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py )
Judging by `torch_C.cp35-win_amd64.pyd` your are running pytorch-1.4.0 or older. Is there a reason why you don't want to try the same with PyTorch-1.6.0?

**Comment by karimhasebou** [comment]
> Please provide version of Python, PyTorch, TorchVision as well as your OS and Cuda version. (You can do it by running `python -mtorch.utils.collect_env` and pasting its output here, if you don't have a functioning PyTorch installation, you can directly download and run script from https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py )
> Judging by `torch_C.cp35-win_amd64.pyd` your are running pytorch-1.4.0 or older. Is there a reason why you don't want to try the same with PyTorch-1.6.0?

PyTorch version: 1.5.0+cpu
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.5
Is CUDA available: No
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: Quadro M2000M
Nvidia driver version: 442.23
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.14.2
[pip] torch==1.5.0+cpu
[pip] torchsummary==1.5.1
[pip] torchvision==0.6.0+cpu
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      216
[conda] torch                     1.5.0+cpu                pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.6.0+cpu                pypi_0    pypi

am running torch 1.5 because i believe torch 1.6 is not available on python 3.5.

**Comment by karimhasebou** [comment]
Without the function overloading of the JIT methods just importing pytorch will throw an exception in the exe as follows 
Traceback (most recent call last):
  File "site-packages\torch\_utils_internal.py", line 46, in get_source_lines_and_file
  File "inspect.py", line 936, in getsourcelines
  File "inspect.py", line 767, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pytorchVizTool\cli.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "pytorchVizTool\flaskr\ModelServer.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\models\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\ops\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\a-kahas\appdata\local\continuum\anaconda3\envs\exe_creator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\ops\poolers.py", line 41, in <module>
  File "site-packages\torch\jit\__init__.py", line 1280, in script
  File "site-packages\torch\jit\__init__.py", line 1107, in _compile_and_register_class
  File "site-packages\torch\jit\frontend.py", line 152, in get_jit_class_def
  File "site-packages\torch\jit\frontend.py", line 152, in <listcomp>
  File "site-packages\torch\jit\frontend.py", line 164, in get_jit_def
  File "site-packages\torch\_utils_internal.py", line 53, in get_source_lines_and_file
OSError: Can't get source for <function LevelMapper.__call__ at 0x000002392145A268>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code
[7500] Failed to execute script cli

**Comment by karimhasebou** [comment]
I found the function registering nms operation as follows

![image](https://user-images.githubusercontent.com/11773009/89517576-2c0b4580-d7da-11ea-9ff6-d5914c0dc617.png)

And i tied calling it from my main thinking maybe pyinstaller doesnt recognize thats it being used within pytorch but still nothing worked

**Comment by karimhasebou** [comment]
it turns out pyinstaller is not copying the torchvision directory to the build directory. Should a hook be made to make sure torchvision is loaded by torch ?

**Comment by mszhanyi** [comment]
It might be helpful for you issue, https://github.com/pytorch/vision/issues/1899#issuecomment-598200938

**Comment by karimhasebou** [comment]
> It might be helpful for you issue, [pytorch/vision#1899 (comment)](https://github.com/pytorch/vision/issues/1899#issuecomment-598200938)

Explicitly copying torchvision using the mentioned issue solves the issue

**Comment by gorgeous369** [comment]
I have met the same problem. Could you teach me how to solve it after copying the torchvision? Many thanks.

**Comment by yahahahoo** [comment]
> > It might be helpful for you issue, [pytorch/vision#1899 (comment)](https://github.com/pytorch/vision/issues/1899#issuecomment-598200938)
> 
> Explicitly copying torchvision to the build directory using the mentioned issue solves the issue

I also met this problem. Have you solved it？
