### ISSUE TITLE
RuntimeError: each element in list of batch should be of equal size 

### ISSUE THREAD

**Issue by zyc-ai** [pytorch/pytorch#42654]
## 🐛 Bug
```python
"python3.7/site-packages/torch/utils/data/_utils/collate.py", line 82, in default_collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size
```

## To Reproduce

···python
model = models.resnet50()

transform = transforms.Compose([
    transforms.Resize((480, 640)),
    transforms.ToTensor(),
])

train_dataset = datasets.CocoDetection(
    root=args.train_dataset, annFile=args.train_annotation, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64)

for (img, anno) in train_loader:
    out = model(img)
```

<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->

## Expected behavior
forward
<!-- A clear and concise description of what you expected to happen. -->

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda -c pytorch
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100
 - Any other relevant information:

## Additional context
It was fine first, and suddenly have the issue after I came back from dinner. 
Resolved by downgrade to PyTorch 1.5.0
<!-- Add any other context about the problem here. -->

**Comment by ailzhang** [comment]
Hmmm the error message seem to be clear enough, I think the todo here is to make sure we didn't accidentally regress from 1.5.0?

**Comment by SsnL** [comment]
Agree with @ailzhang . The issue lies in your dataset code and is a user error.

**Comment by zyc-ai** [comment]
> Agree with @ailzhang . The issue lies in your dataset code and is a user error.

Did you mean it is a torchvision issue instead?

**Comment by shreyaskamathkm** [comment]
Running into the same problem. In my case, I am performing a semantic segmentation. I have an image with four channels ```[B,4, H, W]``` as input and a mask with 1 channel ```[B,H,W]``` as ground truth. I receive the following error. This was not the case in PyTorch 1.5.0.

```
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [4, 768, 1024] at entry 0 and [768, 1024] at entry 1
```

**Comment by zyc-ai** [comment]
> Running into the same problem. In my case, I am performing semantic segmentation. I have an image with four channels `[B,4, H, W]` as input and a mask with 1 channel `[B,H,W]` as ground truth. I receive the following error. This was not the case in PyTorch 1.5.0.
> 
> ```
> Original Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
>     return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [4, 768, 1024] at entry 0 and [768, 1024] at entry 1
> ```



> Ran into the same problem and found @zyc-ai 's solution. Same as @shreyaskamathkm, I was using a multi channel input. In my case, I was using video data to feed it into `conv3d` with `[Batch, Channel, Sequence, Height, Width]`, but I solved the issue by downgrading to 1.5.0 as well.

Looks like not an issue of torchvision @SsnL

**Comment by SsnL** [comment]
@shreyaskamathkm 's error aren't even the same as yours. Also while it is unclear what @Toraudonn 's error is, based on their description, it looks similar to @shreyaskamathkm 's rather than yours. 

Your error message is pretty straightforward. The batch is a list of samples, some parts of the same is a Sequence, but they are not of the same length for all samples in the same batch.

**Comment by Khoa-NT** [comment]
I have the same error when in Dataset I return a dict that contains a list.

```python
class Sample_dataset(torch.utils.data.Dataset):
    def __init__(self, ...):
        ...
    def __len__(self, ...):
        ...
    def __getitem__(self, index):
        data = {}
        image, target = self.getdata(index)
        data["image"] = image
        data["target "] = target 
        ex_list = [1, 2, 3, 4]
        data["my_list"] = ex_list 
        return data
```

**Comment by Vincentyua** [comment]
I encountered the same problem, but because my sample is in map format, my solution is to use the collate_fn parameter in the DataLoader to solve this problem
`data_loader = torch.utils.data.DataLoader(
        batch_size=batch_size,
        dataset=data,
        shuffle=shuffle,
        num_workers=0,
        collate_fn=lambda x: x
    )`

**Comment by jsrozner** [comment]
I have this error on pytorch 1.6 but not on 1.5. I reverted to 1.5.1. I am using a simple Dataset where each item is a dictionary.

**Comment by cattpku** [comment]
Same problem here for both 1.6 and 1.7, by reverting to 1.5, it can successfully proceed.

**Comment by hukaidong** [comment]
same problem here for torch 1.7, other version not being tested yet

**Comment by ZhiyuanChen** [comment]
> @shreyaskamathkm 's error aren't even the same as yours. Also while it is unclear what @Toraudonn 's error is, based on their description, it looks similar to @shreyaskamathkm 's rather than yours.
> 
> Your error message is pretty straightforward. The batch is a list of samples, some parts of the same is a Sequence, but they are not of the same length for all samples in the same batch.

I do agree it's straightforward. But it doesn't look like expected behaviour.

**Comment by fathia-ghribi** [comment]
hello guys !!
i have a csv file like a database, i wanted to train a topic modeling algorithm on this file. when i execute this code (https://github.com/sebkim/lda2vec-pytorch/blob/master/training.py). i got the following error  :` 
epoch 1
  0%|                                                                                          | 0/152 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 58, in main
    train(
  File "C:\Users\fathi\lda2vecpytorch\training.py", line 113, in train
    for batch in tqdm(iterator):
  File "C:\Users\fathi\anaconda\envs\pytor\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "C:\Users\fathi\anaconda\envs\pytor\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\fathi\anaconda\envs\pytor\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\fathi\anaconda\envs\pytor\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Users\fathi\anaconda\envs\pytor\lib\site-packages\torch\utils\data\_utils\collate.py", line 81, in default_collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size` 
how to fix this error

**Comment by fathia-ghribi** [comment]
> D'accord avec @ailzhang . Le problème réside dans le code de votre ensemble de données et est une erreur de l'utilisateur.

how to fix this error ??

**Comment by fathia-ghribi** [comment]
> même problème ici pour torch 1.7, les autres versions n'étant pas encore testées

me too pytorch version 1.7 , how to  fix this ??

**Comment by rachtibat** [comment]
In my case the problem was, that the labels were dictionaries and not tensors. You have to use collate_fn as Vincentyua suggested

**Comment by Santosh-Gupta** [comment]
> In my case the problem was, that the labels were dictionaries and not tensors. You have to use collate_fn as Vincentyua suggested

This seemed to have worked for me, as my data was in the form of dictionaries, though I am having trouble figuring out why @Vincentyua solution of `collate_fn=lambda x: x ` was able to fix it.

**Comment by niektuytel** [comment]
old way:
```python
    loader = DataLoader(.....)

    for element in tqdm(loader):
        print(element)
```

new way
```python

    loader = DataLoader(..... , collate_fn=lambda x: x )
    dataiter = iter(loader)
    data = dataiter.next()

    for element in tqdm(data):
        print(element)
```

**Comment by ZhiyuanChen** [comment]
> old way:
> 
> ```python
>     loader = DataLoader(.....)
> 
>     for element in tqdm(loader):
>         print(element)
> ```
> 
> new way
> 
> ```python
>     loader = DataLoader(..... , collate_fn=lambda x: x )
>     dataiter = iter(loader)
>     data = dataiter.next()
> 
>     for element in tqdm(data):
>         print(element)
> ```

This is definitely a workaround, not a solve

**Comment by abradley60** [comment]
I was getting the same error. In my case, it was an issue with the csv's I was reading my labels from. I had made a change and introduced an additional field in one of the csv's. Check you have consistent fields across the datasets you are reading with the dataloader (torchvision 0.10.0)

**Comment by nocoolsandwich** [comment]
i just wanna know why this happen

**Comment by omar-araboghli** [comment]
> 
> 
> I encountered the same problem, but because my sample is in map format, my solution is to use the collate_fn parameter in the DataLoader to solve this problem
> `data_loader = torch.utils.data.DataLoader( batch_size=batch_size, dataset=data, shuffle=shuffle, num_workers=0, collate_fn=lambda x: x )`

The following collate_fn produces the same standard expected result from a DataLoader. It solved my purpose, when my batch consists of >1 instances and instances can have different dimensions.

```python
def collate_fn(instances):
    batch = []

    for i in range(len(instances[0])):
        batch.append([instance[i] for instance in instances])

    return batch
```

**Comment by JustDoItY** [comment]
train_loader = data.DataLoader(train_data, batch_size=2, collate_fn=lambda x: x)

def selectedImg(data):
  return data[0]

batch = next(iter(train_loader))

imgs = th.stack(list(map(selectedImg, batch)), 0) # this is tensor[2, 3, 224, 224]


this is worked, but so so so weird. coco design for this? i am a problem, why dataloader return tuple struct, yet net need tensor

**Comment by wenfahu** [comment]
```python
loader = DataLoader(..... , collate_fn=lambda x: tuple(zip(*x)) )
```
Could be yet another workaround

**Comment by gao-shi** [comment]
> > In my case the problem was, that the labels were dictionaries and not tensors. You have to use collate_fn as Vincentyua suggested
> 
> This seemed to have worked for me, as my data was in the form of dictionaries, though I am having trouble figuring out why @Vincentyua solution of `collate_fn=lambda x: x ` was able to fix it.

My error is caused by returning a numpy array rather than a tensor

**Comment by gautamjain1009** [comment]
> > I encountered the same problem, but because my sample is in map format, my solution is to use the collate_fn parameter in the DataLoader to solve this problem
> > `data_loader = torch.utils.data.DataLoader( batch_size=batch_size, dataset=data, shuffle=shuffle, num_workers=0, collate_fn=lambda x: x )`
> 
> The following collate_fn produces the same standard expected result from a DataLoader. It solved my purpose, when my batch consists of >1 instances and instances can have different dimensions.
> 
> ```python
> def collate_fn(instances):
>     batch = []
> 
>     for i in range(len(instances[0])):
>         batch.append([instance[i] for instance in instances])
> 
>     return batch
> ```
@omar-araboghli how will you pass this function in the dataloader, 
`
loader = DataLoader(dataset, batch_size =4, num_workers=4,collate_fn=collate_fn(?????))`

**Comment by zzyzeyuan** [comment]
Same problem in torch 2.0.0.
