### ISSUE TITLE
Runtime error occurred when backwarding the loss

### ISSUE THREAD

**Issue by wondervictor** [pytorch/pytorch#4265]
When running my model with GPU, I have append `.cuda()` for all the network and variables as well as loss critetions. 

````
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    train(opt=params)
  File "train.py", line 115, in train
    current_loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'
````

**Comment by wondervictor** [comment]
I've fixed it :)
I created a Variable in my network and didn't define it as a cuda variable.
