### ISSUE TITLE
How to build libtorch static libraries on Windows?

### ISSUE THREAD

**Issue by lawlict** [pytorch/pytorch#42722]
I'm developing the Windows program using libtorch dynamic libraries released on pytorch website. However, I find the dynamic libraries are quite large (the torch_cpu.dll is larger than 100MB). Is there the static library version, or how could I build the libtorch static library by myself?

Look forward to your response. Thanks a lot!

**Comment by xsacha** [comment]
Last time I tried, the filesize was > 2GB and failed to link due to size.

**Comment by peterjc123** [comment]
Have you tried MinSizeRel builds?

**Comment by peterjc123** [comment]
You may refer to https://github.com/pytorch/pytorch/pull/39848/files.

**Comment by xsacha** [comment]
Problem becomes how to debug the build

**Comment by peterjc123** [comment]
Maybe you could try adding the compiler option `/Zi`?

**Comment by mszhanyi** [comment]
@xsacha , after building, you could find Torch.sln in build directory.

**Comment by lawlict** [comment]
> @xsacha , after building, you could find Torch.sln in build directory.

Hi, xsacha. I am not sure whether it is the correct way to build libtorch, but I just clone down the pytorch source and run build_libtorch.py in the tools/ directory. To be specific:
```
cd tools
 BUILD_SHARED_LIBS=OFF python build_libtorch.py
```
It fails, and part of the logfile is: 
```
[783/2266] Building CXX object caffe2\CMakeFiles\KernelFunction_test.dir\__\aten\src\ATen\core\boxing\KernelFunction_test.cpp.obj
FAILED: caffe2/CMakeFiles/KernelFunction_test.dir/__/aten/src/ATen/core/boxing/KernelFunction_test.cpp.obj 
"D:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe"  /nologo /TP -DAT_CORE_STATIC_WINDOWS=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -Iaten\src -I..\..\aten\src -I. -I..\..\ -I..\..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\..\third_party\onnx -Ithird_party\onnx -I..\..\third_party\foxi -Ithird_party\foxi -Iinclude -Icaffe2\aten\src\TH -I..\..\aten\src\TH -Icaffe2\aten\src -I..\..\aten\..\third_party\catch\single_include -I..\..\aten\src\ATen\.. -Icaffe2\aten\src\ATen -I..\..\third_party\miniz-2.0.8 -I..\..\caffe2\core\nomnigraph\include -I..\..\torch\csrc\api -I..\..\torch\csrc\api\include -I..\..\c10\.. -Ithird_party\ideep\mkl-dnn\include -I..\..\third_party\ideep\mkl-dnn\src\..\include -I..\..\third_party\cpuinfo\include -I..\..\third_party\fbgemm\include -I..\..\third_party\fbgemm -I..\..\third_party\fbgemm\third_party\asmjit\src -I..\..\third_party\FP16\include -I..\..\third_party\fmt\include -I..\..\cmake\..\third_party\googletest\googlemock\include -I..\..\cmake\..\third_party\googletest\googletest\include -I..\..\third_party\protobuf\src -I..\..\third_party -I..\..\cmake\..\third_party\eigen -I..\..\cmake\..\third_party\pybind11\include -I..\..\third_party\ideep\mkl-dnn\include -I..\..\third_party\ideep\include -I..\..\third_party\googletest\googletest\include -I..\..\third_party\googletest\googletest /DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION /MT /O2 /Ob2 /DNDEBUG /w /bigobj -DNDEBUG -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD /EHsc /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -DASMJIT_STATIC -std:c++14 /showIncludes /Focaffe2\CMakeFiles\KernelFunction_test.dir\__\aten\src\ATen\core\boxing\KernelFunction_test.cpp.obj /Fdcaffe2\CMakeFiles\KernelFunction_test.dir\ /FS -c ..\..\aten\src\ATen\core\boxing\KernelFunction_test.cpp
..\..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2066: 强制转换到函数类型是非法的
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): note: 参见对正在编译的 类 模板 实例化 "c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>" 的引用
        with
        [
            Return=int64_t
        ]
..\..\aten\src\ATen\core\boxing\KernelFunction_test.cpp(263): note: 参见对正在编译的函数 模板 实例化“Return c10::KernelFunction::call<int64_t,int64_t,int64_t>(const c10::OperatorHandle &,int64_t,int64_t) const”的引用
        with
        [
            Return=int64_t
        ]
..\..\c10/core/MemoryFormat.h(56): note: 参见对正在编译的 类 模板 实例化 "c10::ArrayRef<int64_t>" 的引用
..\..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2070: “FuncType”: 非法的 sizeof 操作数
        with
        [
            FuncType=int64_t (int64_t,int64_t)
        ]
..\..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2338: Function signature contains one or more unsupported parameter and/or return types. Look for a nearby error like "'call' is not a member of 'c10::impl::BoxedKernelWrapper<(your function type), void>'" - (your function type) is the unsupported signature.
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): error C2039: “call”: 不是“c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>”的成员
        with
        [
            Return=int64_t
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): note: 参见“c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>”的声明
        with
        [
            Return=int64_t
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): error C2672: “c10::KernelFunction::call”: 未找到匹配的重载函数
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(66): error C2783: “Return c10::KernelFunction::call(const c10::OperatorHandle &,Args...) const”: 未能为“Return”推导 模板 参数
..\..\aten\src\ATen/core/boxing/KernelFunction.h(87): note: 参见“c10::KernelFunction::call”的声明
..\..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2070: “FuncType”: 非法的 sizeof 操作数
        with
        [
            FuncType=void (int64_t,int64_t)
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): error C2039: “call”: 不是“c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>”的成员
        with
        [
            Return=void
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): note: 参见“c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>”的声明
        with
        [
            Return=void
        ]
..\..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2070: “FuncType”: 非法的 sizeof 操作数
        with
        [
            FuncType=std::tuple<int64_t,int64_t> (int64_t,int64_t)
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): error C2039: “call”: 不是“c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>”的成员
        with
        [
            Return=std::tuple<int64_t,int64_t>
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): note: 参见“c10::impl::BoxedKernelWrapper<Return (int64_t,int64_t),void>”的声明
        with
        [
            Return=std::tuple<int64_t,int64_t>
        ]
..\..\aten\src\ATen/core/boxing/impl/boxing.h(100): error C2070: “FuncType”: 非法的 sizeof 操作数
        with
        [
            FuncType=std::tuple<at::Tensor &,at::Tensor &> (at::Tensor &,at::Tensor &,c10::Scalar,c10::Scalar)
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): error C2039: “call”: 不是“c10::impl::BoxedKernelWrapper<Return (at::Tensor &,at::Tensor &,c10::Scalar,c10::Scalar),void>”的成员
        with
        [
            Return=std::tuple<at::Tensor &,at::Tensor &>
        ]
..\..\aten\src\ATen/core/boxing/KernelFunction_impl.h(61): note: 参见“c10::impl::BoxedKernelWrapper<Return (at::Tensor &,at::Tensor &,c10::Scalar,c10::Scalar),void>”的声明
        with
        [
            Return=std::tuple<at::Tensor &,at::Tensor &>
        ]
[784/2266] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\ChanelShuffle.cpp.obj
[785/2266] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\Blas.cpp.obj
[786/2266] Linking CXX executable bin\c10_intrusive_ptr_test.exe
[787/2266] Building CXX object caffe2\CMakeFiles\thread_init_test.dir\__\aten\src\ATen\test\thread_init_test.cpp.obj
[788/2266] Building CXX object caffe2\CMakeFiles\data_filler_test.dir\predictor\emulator\data_filler_test.cc.obj
ninja: build stopped: subcommand failed.
cmake -GNinja -DBUILD_PYTHON=False -DBUILD_SHARED_LIBS=OFF -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=E:\Desktop\Git\pytorch\torch -DCMAKE_PREFIX_PATH=D:\Anaconda3\Lib\site-packages -DPYTHON_EXECUTABLE=D:\Anaconda3\python.exe -DPYTHON_INCLUDE_DIR=D:\Anaconda3\include -DUSE_NUMPY=True E:\Desktop\Git\pytorch
cmake --build . --target install --config Release -- -j 6
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 23, in <module>
    rerun_cmake=True, cmake_only=False, cmake=CMake())
  File "E:\Desktop\Git\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "E:\Desktop\Git\pytorch\tools\setup_helpers\cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "E:\Desktop\Git\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "D:\Anaconda3\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 1.
```
View also the full log file: [build.log](https://github.com/pytorch/pytorch/files/5077836/build.log)
Could you give me a hand, please?

**Comment by mszhanyi** [comment]
@lawlict, you'd better use VS2019 to build the latest baseline.

The attached are the batch commands, which I personally used to set envs, based on the tutorial.
You could refer them to setup your environment variables. Hope it's helpful for you.

replace .txt to .bat 
[setenv.txt](https://github.com/pytorch/pytorch/files/5082372/setenv.txt)
[setcudaenv.txt](https://github.com/pytorch/pytorch/files/5082373/setcudaenv.txt)

**Comment by xsacha** [comment]
I was able to build the static release version of the latest nightly, last night. However, I had to disable FBGEMM due to undefined linker errors for fbgemm::Quantize.
The torch_cpu.lib exceeds 2GB.

**Comment by JanMikicki** [comment]
Hey uh, @lawlict did you solve this? I'm getting similar errors.

**Comment by lawlict** [comment]
@JanMikicki , No yet. I have switched to onnx for solution.

**Comment by skyline75489** [comment]
@JanMikicki @lawlict I'm seeing similar error when using VS2017. You may want to use VS2019 for it to work.

**Comment by JanMikicki** [comment]
> @JanMikicki @lawlict I'm seeing similar error when using VS2017. You may want to use VS2019 for it to work.

I've given up atm, but maybe I will try this in the future. I did kinda want to use cuda 10.0 though and I don't know if VS2019 is compatible with it.
