### ISSUE TITLE
Build failed on Raspberry Pi: fatal error: gloo/algorithm.h: No such file or directory

### ISSUE THREAD

**Issue by Creator-360** [pytorch/pytorch#42776]
Hello,
I tried to build PyTorch on my Raspberry Pi and this error showed up.
How can I fix it ?

Computer: Raspberry Pi 4
OS: Raspberry Pi OS (last version)

```
[ 95%] Built target torch_shm_manager
In file included from /home/pi/pytorch/pytorch/test/cpp/rpc/test_e2e_process_group.cpp:5:
/home/pi/pytorch/pytorch/torch/lib/c10d/../c10d/ProcessGroupGloo.hpp:10:10: fatal error: gloo/algorithm.h: No such file or directory
 #include <gloo/algorithm.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [test_cpp_rpc/CMakeFiles/test_cpp_rpc.dir/build.make:102: test_cpp_rpc/CMakeFiles/test_cpp_rpc.dir/test_e2e_process_group.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:11455: test_cpp_rpc/CMakeFiles/test_cpp_rpc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target torch_python
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 321, in build_deps
    cmake=cmake)
  File "/home/pi/pytorch/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/pi/pytorch/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/pi/pytorch/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
```

cc @malfet

**Comment by guibronzatti** [comment]
Did you find a solution for that error? I'm having the same error

**Comment by malfet** [comment]
Please try commenting out this line:
https://github.com/pytorch/pytorch/blob/752f433a2484db25f076b2fc85c40ab191656bd9/test/cpp/rpc/CMakeLists.txt#L6
Fix is coming
