### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:27 for spectral norm

### ISSUE THREAD

**Issue by Dylan-H-Wang** [pytorch/pytorch#42800]
Hi guys,

I have a GPU GeForce GTX TITAN X with python 3.7.4 and CUDA 10.1. I am training my GAN on this GPU and it seems like the following errors occasionally happens during the training process and it always related to the spectral norm which is provided  
by `torch.nn.utils.spectral_norm` [here](https://pytorch.org/docs/stable/generated/torch.nn.utils.spectral_norm.html#torch.nn.utils.spectral_norm)

In this example it happens at iteration 180 and another fail (not list hear) happens at iteration 5800. Is that a bug?

```Traceback (most recent call last):
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/HDD2/hwan7885/proj_hr/gan_ST_map_cnn/sagan/train_cifar10.py", line 15, in <module>
    trainer.train()
  File "/mnt/HDD2/hwan7885/proj_hr/gan_ST_map_cnn/sagan/trainer.py", line 261, in train
    fake_images = self.G(z, real_labels)
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/HDD2/hwan7885/proj_hr/gan_ST_map_cnn/sagan/sagan_models.py", line 188, in forward
    act4 = self.block4(act3, labels)    # n x g_conv_dim*2 x 64 x 64
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/HDD2/hwan7885/proj_hr/gan_ST_map_cnn/sagan/sagan_models.py", line 151, in forward
    x0 = self.snconv2d0(x0)
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/site-packages/torch/nn/modules/module.py", line 714, in _call_impl
    result = hook(self, input)
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/site-packages/torch/nn/utils/spectral_norm.py", line 99, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "/mnt/HDD2/hwan7885/anaconda3/envs/Nepean/lib/python3.7/site-packages/torch/nn/utils/spectral_norm.py", line 85, in compute_weight
    sigma = torch.dot(u, torch.mv(weight_mat, v))
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:27```

**Comment by xwang233** [comment]
Can you provide your pytorch version using the following script?

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Dylan-H-Wang** [comment]
Just update my question with outputs from the script

**Comment by xwang233** [comment]
Thanks! Can you also provide a minimal script that can reproduce this issue?

**Comment by Dylan-H-Wang** [comment]
I am using the code from this [repo](https://github.com/voletiv/self-attention-GAN-pytorch), the spectral normal module is used in this [script](https://github.com/voletiv/self-attention-GAN-pytorch/blob/master/sagan_models.py) (snconv2d). 

I am doing the cifar10 training , and you can try with `python train.py --dataset cifar10 --data_path 'a/b/c' --save_path 'o/p/q' --batch_size 64 --name sagan`

Since this error happens randomly, I don't know how to reproduce it exactly at the beginning. From my experiment, it can happen very early at around epoch 50, and it can happen very late at around epoch 5000. In my experiment, it happens at line 131, 156 and line 206 of [this scipt](https://github.com/voletiv/self-attention-GAN-pytorch/blob/master/trainer.py) (maybe as long as the model uses spectral norm, this error is possible to happen).
