### ISSUE TITLE
Can not get pytorch working with tensorboard

### ISSUE THREAD

**Issue by chanchanhui** [pytorch/pytorch#42861]
## To Reproduce

I follow the tutorials in pytorch.org It occurs error：TensorBoard logging requires TensorBoard version 1.15 or above, but I have install TensorBoard already. When I run `tensorboard --logdir=runs`,it work normally.I use `from torch.utils.tensorboard import SummaryWriter` at the beginning, but it occurs the error as same as above. Then I use` from tensorboardX import SummaryWriter`The bug confuses me for days. Is there any alternative to tensorboard？

Here is the code:

```
#from torch.utils.tensorboard import SummaryWriter
from tensorboardX import SummaryWriter
writer = SummaryWriter('runs/fashion_mnist_experiment_1')
#get some random training images
dataiter = iter(trainloader)
images , labels = dataiter.next()
#create grid of images
img_grid = torchvision.utils.make_grid(images)
matplotlib_imshow(img_grid,one_channel=True)
writer.add_image('four_fashion_images',img_grid)
writer.add_graph(net, images)
writer.close()
```
## Error
```

ImportError                               Traceback (most recent call last)
<ipython-input-12-d38808675cb4> in <module>
----> 1 writer.add_graph(net, images)
      2 writer.close()

~\anaconda3\envs\torch2\lib\site-packages\tensorboardX\writer.py in add_graph(self, model, input_to_model, verbose)
    791 
    792         """
--> 793         from torch.utils.tensorboard._pytorch_graph import graph
    794         self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
    795 

~\anaconda3\envs\torch2\lib\site-packages\torch\utils\tensorboard\__init__.py in <module>
      2 from distutils.version import LooseVersion
      3 if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
----> 4     raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
      5 del LooseVersion
      6 del tensorboard
```

ImportError: TensorBoard logging requires TensorBoard version 1.15 or above

## Environment

```

 - PyTorch Version (e.g., 1.0):1.6
 - OS (e.g., Linux):Window 10 
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:
 - Any other relevant information:
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
tensorflow                1.2.1                    py36_0    defaults
pytorch                   1.6.0           py3.6_cuda102_cudnn7_0    pytorch
torchvision               0.7.0                py36_cu102    pytorch
future                    0.18.2                   py36_1    defaults
protobuf                  3.12.3           py36h33f27b4_0    defaults

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by yutaizhou** [comment]
#20140

**Comment by alealv** [comment]
Hi, I'm having the same issue and it isn't clear for me how to solve it.
Also the issue it's quite old but #20140 seems to be resolved 

### How to reproduce
In a freshly new virtual env
```bash
➜ pip install torch tensorboard
...
➜ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch.utils.tensorboard import SummaryWriter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aalvarez/.virtualenvs/tmp-f48aef87d0fa5d3/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'setuptools._distutils' has no attribute 'version'
```

```bash
aalvarez in ~/.virtualenvs/tmp-f48aef87d0fa5d3 at ml-2 via tmp-f48aef87d0fa5d3
➜ pip list
Package                 Version
----------------------- ---------
absl-py                 1.0.0
cachetools              5.0.0
certifi                 2021.10.8
charset-normalizer      2.0.10
google-auth             2.4.1
google-auth-oauthlib    0.4.6
grpcio                  1.43.0
idna                    3.3
importlib-metadata      4.10.1
Markdown                3.3.6
numpy                   1.22.1
oauthlib                3.1.1
pip                     21.3.1
protobuf                3.19.3
pyasn1                  0.4.8
pyasn1-modules          0.2.8
requests                2.27.1
requests-oauthlib       1.3.0
rsa                     4.8
setuptools              60.0.5
six                     1.16.0
tensorboard             2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
torch                   1.10.1
typing_extensions       4.0.1
urllib3                 1.26.8
Werkzeug                2.0.2
wheel                   0.37.1
zipp                    3.7.0
```
