### ISSUE TITLE
undefined symbol: FLAGS_caffe2_keep_on_shrink

### ISSUE THREAD

**Issue by peijason** [pytorch/pytorch#43040]
Failed to `import torch` installed by **pip**, with the following ERROR messages:

```
✗ python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.8/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: ~/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: FLAGS_caffe2_keep_on_shrink
>>> 
```

**Comment by izdeby** [comment]
@peijason, can you, please, provide more info? what pytorch version did you install? how exactly did you install it? do you have all the dependencies?

**Comment by peijason** [comment]
@izdeby 
Hi, @izdeby , My ENV:

```console
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
➜  ~ python --version
Python 3.8.2
➜  ~ gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I successfully installed **PyTorch** by `pip install -U --user torch`. But when I tried to **import torch**, I got this **undefined symbol ERROR**:

```console
➜  ~ python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.8/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: ~/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: FLAGS_caffe2_keep_on_shrink
```
