### ISSUE TITLE
Error when trying to autocast forward method in nn.sequential model 

### ISSUE THREAD

**Issue by alexisdrakopoulos** [pytorch/pytorch#43204]
I am on PyTorch 1.6 through the AWS DLAMI pytorch_latest_p36.

I have a simple model

```
class Network(nn.Module):

    def __init__(self, layer_sizes, neuron_fc=2048):
        super().__init__()

        layers = [nn.Linear(layer_sizes[0], neuron_fc),
                       nn.BatchNorm1d(neuron_fc, momentum=0.9),
                       nn.ReLU(True),
                       nn.Dropout(0.2),
                       nn.Linear(neuron_fc, layer_sizes[1])]
    
        self.classifier = nn.Sequential(*layers)

    @autocast()
    def forward(self, input):
        return self.classifier(input)
```

which works fine without the @autocast decorator. However to enable multi-GPU training I need to call @autocast on the forward method as written in the docs. When I do this I get this error:

```
Traceback (most recent call last):
  File "cub.py", line 113, in <module>
    epoch_val=True)
  File "/dev/shm/model/model.py", line 642, in train
    embeddings = self.embedder(fc_out)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py", line 135, in decorate_autocast
    return func(*args, **kwargs)
  File "/dev/shm/model/model.py", line 94, in forward
    input = self.classifier(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/functional.py", line 1672, in linear
    if input.dim() == 2 and bias is not None:
AttributeError: 'function' object has no attribute 'dim'
```

Note that the network above is used as two separate models in the following way:

```
self.embedder = nn.DataParallel(Network(layer_sizes=[2048, 512], neuron_fc=2048))
self.classifier= nn.DataParallel(Network(layer_sizes=[512, 1000], neuron_fc=2048))
```

and training takes place as such:

```
for i, data in enumerate(dataloader):
    inputs, labels = data
    with autocast():
          embeddings = self.embedder(inputs)
         logits = self.classifier(embeddings)
```

**Comment by alexisdrakopoulos** [comment]
Nevermind I had a bug and missed a foward method from another model hence the "inputs" error, my bad.
