### ISSUE TITLE
Cannot find CUDA devices when the machine stays idle for a while

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#43281]
From this discussion: https://discuss.pytorch.org/t/pytorch-suddenyl-stops-recognising-gpu/93384

> I am using PyTorch through Anaconda Environment and something weird happens. While working or if I leave the machine for some time and come back, PyTorch stops recognizing the GPU. And the only way it starts recognizing the GPU is after rebooting the machine.

```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/THC/THCGeneral.cpp line=47 error=999 : unknown error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/work/lib/python3.8/site-packages/torch/cuda/__init__.py", line 330, in current_device
    _lazy_init()
  File "/home/user/anaconda3/envs/work/lib/python3.8/site-packages/torch/cuda/__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (999) : unknown error at /opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/THC/THCGeneral.cpp:47
```

The user confirmed that `nvidia-smi` works fine though and the following command can fix the problem. 

```
$ sudo rmmod nvidia_uvm
$ sudo modprobe nvidia_uvm
```

**Comment by malfet** [comment]
Doesn't look like a pytorch specific problem to me, but rather a glitch in CUDA driver/runtime (perhaps caused by some power management settings)
