### ISSUE TITLE
`affine_grid` cannot pass `gradcheck`

### ISSUE THREAD

**Issue by zck119** [pytorch/pytorch#4329]
I'm testing a modification of spatial transformer network, which fails the `gradcheck`. So I run `gradcheck` with the implementation provided in pytorch and found that this also fails `gradcheck`: 

Code: 
```python
import torch
from torch.autograd import Variable
from torch.autograd.gradcheck import gradcheck
import numpy as np
from torch.nn.functional import affine_grid

grid_sz = 2    # set small so output from gradcheck is also small. 
theta = torch.FloatTensor(np.random.rand(1,2,3))
theta = Variable(theta, requires_grad=True)
def func(v):
    return affine_grid(v, torch.Size([1, 1, grid_sz, grid_sz]))
gradcheck(func, (theta,))
```

Output: 
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    gradcheck(func, (theta,))
  File "/Users/chengkaizhang/bin/anaconda3/envs/python_test/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 181, in gradcheck
    return fail_test('for output no. %d,\n numerical:%s\nanalytical:%s\n' % (j, numerical, analytical))
  File "/Users/chengkaizhang/bin/anaconda3/envs/python_test/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 166, in fail_test
    raise RuntimeError(msg)
RuntimeError: for output no. 0,
 numerical:(
-1.0729  0.0000  1.0133  0.0000 -1.0133  0.0000  1.0729  0.0000
-1.0729  0.0000 -1.0133  0.0000  1.0133  0.0000  1.0729  0.0000
 1.0133  0.0000  1.0133  0.0000  1.0133  0.0000  1.0729  0.0000
 0.0000 -0.9537  0.0000  0.9835  0.0000 -0.9537  0.0000  1.0133
 0.0000 -1.0133  0.0000 -1.0133  0.0000  1.0133  0.0000  1.0133
 0.0000  0.9835  0.0000  1.0133  0.0000  1.0133  0.0000  1.0133
[torch.FloatTensor of size 6x8]
,)
analytical:(
   -1     0     1     0    -1     0     1     0
   -1     0    -1     0     1     0     1     0
    1     0     1     0     1     0     1     0
    0    -1     0     1     0    -1     0     1
    0    -1     0    -1     0     1     0     1
    0     1     0     1     0     1     0     1
[torch.FloatTensor of size 6x8]
,)
```

It seems that the error is a bit larger than normally expected (e.g. -0.9537 vs -1). I set the grid size small so I can show output from `gradcheck`. Setting `grid_sz` to 200 still fail the test. 

Any thoughts?

**Comment by ezyang** [comment]
Thanks for the test, I can repro on HEAD:

```
(/home/ezyang/Dev/pytorch-env) ezyang@autobox:~/Dev/pytorch$ python affine.py 
Traceback (most recent call last):
  File "affine.py", line 12, in <module>
    gradcheck(func, (theta,))
  File "/home/ezyang/Dev/pytorch/torch/autograd/gradcheck.py", line 182, in gradcheck
    return fail_test('for output no. %d,\n numerical:%s\nanalytical:%s\n' % (j, numerical, analytical))
  File "/home/ezyang/Dev/pytorch/torch/autograd/gradcheck.py", line 167, in fail_test
    raise RuntimeError(msg)
RuntimeError: for output no. 0,
 numerical:(
-1.0133  0.0000  1.0133  0.0000 -0.9537  0.0000  1.0729  0.0000
-1.0133  0.0000 -1.0133  0.0000  0.9537  0.0000  1.0729  0.0000
 1.0133  0.0000  1.0133  0.0000  0.9537  0.0000  1.0133  0.0000
 0.0000 -1.0729  0.0000  1.0133  0.0000 -1.0133  0.0000  1.0729
 0.0000 -1.0729  0.0000 -1.0133  0.0000  1.0133  0.0000  1.0729
 0.0000  1.0133  0.0000  1.0133  0.0000  1.0133  0.0000  1.0729
[torch.FloatTensor of size 6x8]
,)
analytical:(
   -1     0     1     0    -1     0     1     0
   -1     0    -1     0     1     0     1     0
    1     0     1     0     1     0     1     0
    0    -1     0     1     0    -1     0     1
    0    -1     0    -1     0     1     0     1
    0     1     0     1     0     1     0     1
[torch.FloatTensor of size 6x8]
,)

(/home/ezyang/Dev/pytorch-env) ezyang@autobox:~/Dev/pytorch$ git rev-parse HEAD
3b7fbc397e5802ae4948db817e71100a9c6b6551
```

**Comment by fmassa** [comment]
Can you try running the test in double precision instead of single (float) precision?

**Comment by zck119** [comment]
The function can pass the test in double precision, but I feel the error seems too much off (-0.9537 vs -1) even for single precision.

**Comment by soumith** [comment]
i'm closing the issue, as this is expected to an extent. we dont expect finite difference tests to pass in single precision
