### ISSUE TITLE
DISABLED test_device_maps_remote (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#43368]
https://app.circleci.com/pipelines/github/pytorch/pytorch/202821/workflows/1f12878d-497a-4e55-99a8-5c2748d424a8/jobs/6846434/steps

```
Aug 20 23:34:08 ======================================================================
Aug 20 23:34:08 FAIL [5.925s]: test_device_maps_remote (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
Aug 20 23:34:08 ----------------------------------------------------------------------
Aug 20 23:34:08 Traceback (most recent call last):
Aug 20 23:34:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 223, in wrapper
Aug 20 23:34:08     self._join_processes(fn)
Aug 20 23:34:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 330, in _join_processes
Aug 20 23:34:08     self._check_return_codes(elapsed_time)
Aug 20 23:34:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 373, in _check_return_codes
Aug 20 23:34:08     i, first_process.exitcode, p.exitcode
Aug 20 23:34:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1161, in assertEqual
Aug 20 23:34:08     self.assertTrue(result, msg=msg)
Aug 20 23:34:08 AssertionError: False is not true : Expect process 3 exit code to match Process 0 exit code of 0, but got -11
```

```
Aug 20 23:34:01   test_device_maps_remote (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... [W tensorpipe_agent.cpp:576] RPC agent for worker0 encountered error when reading incoming request from worker2: EOF: end of file (this is expected to happen during shutdown)
Aug 20 23:34:01 [W tensorpipe_agent.cpp:576] RPC agent for worker0 encountered error when reading incoming request from worker3: EOF: end of file (this is expected to happen during shutdown)
Aug 20 23:34:01 [W tensorpipe_agent.cpp:529] RPC agent for worker0 encountered error when sending response to request #3 to worker3: EOF: end of file
Aug 20 23:34:02 [W tensorpipe_agent.cpp:576] RPC agent for worker1 encountered error when reading incoming request from worker0: EOF: end of file (this is expected to happen during shutdown)
Aug 20 23:34:02 [W tensorpipe_agent.cpp:529] RPC agent for worker1 encountered error when sending response to request #5 to worker0: EOF: end of file
Aug 20 23:34:02 [W tensorpipe_agent.cpp:718] RPC agent for worker1 encountered error when sending outgoing request #3 to worker2: EPIPE: broken pipe
Aug 20 23:34:02 FAIL (5.925s)
Aug 20 23:34:03   test_device_maps_return_to_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... skip (0.913s)
Aug 20 23:34:04   test_device_maps_return_to_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... skip (0.913s)
Aug 20 23:34:05   test_device_maps_wrong_worker_name (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... [W tensorpipe_agent.cpp:576] RPC agent for worker2 encountered error when reading incoming request from worker0: EOF: end of file (this is expected to happen during shutdown)
Aug 20 23:34:05 [W tensorpipe_agent.cpp:576] RPC agent for worker0 encountered error when reading incoming request from worker3: EOF: end of file (this is expected to happen during shutdown)
Aug 20 23:34:05 [W tensorpipe_agent.cpp:576] RPC agent for worker0 encountered error when reading incoming request from worker2: EOF: end of file (this is expected to happen during shutdown)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
Weird, a segfault, may be something serious. This is a flake though, right? It wasn't happening consistently?

It's a shame we have so little information to go on when we get these flakes. It may be a good investment to add some mechanism to automatically print some extra info when a test fails. In this case, the backtrace of when the segfault occurred would have been invaluable.

It seems there exists a standard tool that can be linked into programs that automatically installs a signal handler for SEGFAULT that prints exactly that. For example, it can be used throgh `LD_PRELOAD=/lib/libSegFault.so`. It may make sense to try it out...

This discussion relates to #40137.

**Comment by mrshenli** [comment]
closing this issue to see if it is still flaky with the latest version.
