### ISSUE TITLE
Complex Linear does not work

### ISSUE THREAD

**Issue by jonashaag** [pytorch/pytorch#43477]
## 🐛 Bug

```pycon
>> torch.__version__
'1.7.0.dev20200819'
>>> torch.nn.Linear(5, 1)(torch.zeros(3, 5, dtype=torch.complex64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".../torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File ".../torch/nn/functional.py", line 1682, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: expected scalar type Float but found ComplexFloat
```

cc @ezyang @gchanan @zou3519 @bdhirsh @anjali411 @dylanbespalko @mruberry @albanD @nikitaved @rgommers

**Comment by ezyang** [comment]
This is because the linear parameters are floats rather than complex floats. I'm not sure if you wanted them to be floats; if you did, then we need some sort of type promotion here.

**Comment by jonashaag** [comment]
Sorry for being unclear. I wanted them to be complex and for Linear to do complex matmul.

**Comment by ezyang** [comment]
Does `torch.nn.Linear(5, 1).to(torch.complex64)` work?

**Comment by jonashaag** [comment]
```
>>> torch.nn.Linear(5, 1).to(torch.complex64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 605, in to
    'dtypes, but got desired dtype={}'.format(dtype))
TypeError: nn.Module.to only accepts floating point dtypes, but got desired dtype=torch.complex64
>>> torch.__version__
'1.7.0.dev20200826'
```

**Comment by VitalyFedyunin** [comment]
Downgrading priority during triage review meeting, in case of objections please clarify priority bump.

**Comment by ezyang** [comment]
Oh, this was an complex numbers internal priority bump to keep track of more important complex number issues. I'll rebump and remove the triage review tag.
