### ISSUE TITLE
Useless Exception traces when DataSet timing out

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#43502]
Steps to reproduce:
1) Install pytorch master
2) Install torchvision master
3) Install https://github.com/pytorch/examples
4) Modify torchvision to introduce random timeouts inside of ImageFolder class (and reinstall)
```
diff --git a/torchvision/datasets/folder.py b/torchvision/datasets/folder.py
index dffa0a9..bcc871b 100644
--- a/torchvision/datasets/folder.py
+++ b/torchvision/datasets/folder.py
@@ -153,6 +153,10 @@ IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif', '.tif
 def pil_loader(path):
     # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
     with open(path, 'rb') as f:
+        import time
+        import random
+        if random.random() > 0.999:
+            time.sleep(10000)
         img = Image.open(f)
         return img.convert('RGB')
```
5) Run imagenet example from https://github.com/pytorch/examples
6) When training stuck try to Ctrl+C or Kill child process do get useless Exception traces

Interrupted with Ctrl+C

```
(p38) ➜  imagenet git:(master) ✗ python main.py -b 32 --gpu 1 --epochs 20 --workers 8 -a resnet50 data
List
__name__
Optional
'_SpecialForm' object has no attribute '__name__'
Set
__name__
main.py:97: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 1 for training
=> creating model 'resnet50'
Epoch: [0][  0/778]     Time  3.059 ( 3.059)    Data  0.476 ( 0.476)    Loss 7.8664e+00 (7.8664e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
Epoch: [0][ 10/778]     Time  0.639 ( 0.830)    Data  0.000 ( 0.043)    Loss 2.8784e+01 (2.5900e+01)    Acc@1  46.88 ( 46.88)   Acc@5 100.00 ( 90.91)
Epoch: [0][ 20/778]     Time  0.641 ( 0.739)    Data  0.000 ( 0.038)    Loss 3.3539e+00 (1.4972e+01)    Acc@1  34.38 ( 47.17)   Acc@5 100.00 ( 95.24)
Epoch: [0][ 30/778]     Time  0.637 ( 0.707)    Data  0.000 ( 0.037)    Loss 3.6132e+00 (1.2208e+01)    Acc@1  59.38 ( 47.98)   Acc@5 100.00 ( 96.77)
Epoch: [0][ 40/778]     Time  0.639 ( 0.690)    Data  0.000 ( 0.036)    Loss 1.6624e+01 (1.1439e+01)    Acc@1  37.50 ( 47.94)   Acc@5 100.00 ( 97.56)
Epoch: [0][ 50/778]     Time  0.637 ( 0.680)    Data  0.000 ( 0.035)    Loss 2.2245e+01 (1.0695e+01)    Acc@1  65.62 ( 48.65)   Acc@5 100.00 ( 98.04)
^CTraceback (most recent call last):
  File "main.py", line 420, in <module>
    main()
  File "main.py", line 115, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 241, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 275, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 424, in __next__
    data = self._next_data()
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 1058, in _next_data
    idx, data = self._get_data()
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 1014, in _get_data
    success, data = self._try_get_data()
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 862, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/private/home/vitalyf/anaconda3/envs/p38/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/private/home/vitalyf/anaconda3/envs/p38/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

Interrupted with kill

```
(p38) ➜  imagenet git:(master) ✗ python main.py -b 32 --gpu 1 --epochs 20 --workers 8 -a resnet50 data
List
__name__
Optional
'_SpecialForm' object has no attribute '__name__'
Set
__name__
main.py:97: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 1 for training
=> creating model 'resnet50'
Epoch: [0][  0/778]     Time  3.022 ( 3.022)    Data  0.479 ( 0.479)    Loss 7.1807e+00 (7.1807e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
Traceback (most recent call last):
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 862, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/private/home/vitalyf/anaconda3/envs/p38/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/private/home/vitalyf/anaconda3/envs/p38/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/vitalyf/pytorch/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 30019) is killed by signal: Terminated. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 420, in <module>
    main()
  File "main.py", line 115, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 241, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 275, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 424, in __next__
    data = self._next_data()
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 1058, in _next_data
    idx, data = self._get_data()
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 1014, in _get_data
    success, data = self._try_get_data()
  File "/home/vitalyf/pytorch/torch/utils/data/dataloader.py", line 875, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 30019) exited unexpectedly
```

None of this traces identify `time.sleep(10000)` as 'stuck' instruction.

**Comment by VitalyFedyunin** [comment]
Reserved for DataLoader bootcampers

**Comment by VitalyFedyunin** [comment]
Related #33296

**Comment by erjia-guan** [comment]
Interrupted with Ctrl+C
The KeyboardInterrupt Signal Execution:
1. loader function
2. worker: _worker_loop() (Child daemon thread)
3. DataLoader (Main thread)
So, in order to print out traceback from worker, add traceback.print_exc() to generate error in the child thread (worker):
<pre>
def _worker_loop(dataset_kind, dataset, index_queue, data_queue, done_event,
                 auto_collation, collate_fn, drop_last, seed, init_fn, worker_id,
                 num_workers, persistent_workers):
    try:
        ...
    except KeyboardInterrupt:
        # Main process will raise KeyboardInterrupt anyways.
        <b>traceback.print_exc()</b>
        pass
</pre>
The Traceback:
```
^CTraceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 112, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 245, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 280, in train
Traceback (most recent call last):
Traceback (most recent call last):
    for i, (images, target) in enumerate(train_loader):
Traceback (most recent call last):
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 435, in __next__
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/worker.py", line 203, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 151, in __getitem__
    sample = self.loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 193, in default_loader
    return pil_loader(path)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/worker.py", line 203, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 173, in pil_loader
    time.sleep(10000)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 151, in __getitem__
    sample = self.loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 193, in default_loader
    return pil_loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 173, in pil_loader
    time.sleep(10000)
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/worker.py", line 203, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 151, in __getitem__
    sample = self.loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 193, in default_loader
    return pil_loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 173, in pil_loader
    time.sleep(10000)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/worker.py", line 203, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
KeyboardInterrupt
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 151, in __getitem__
    sample = self.loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 193, in default_loader
    return pil_loader(path)
  File "/Users/erjia/workspace/vision/torchvision/datasets/folder.py", line 173, in pil_loader
    time.sleep(10000)
KeyboardInterrupt
    data = self._next_data()
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/Users/erjia/workspace/pytorch/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/Users/erjia/tools/miniconda3/envs/pytorch/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/Users/erjia/tools/miniconda3/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/Users/erjia/tools/miniconda3/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/Users/erjia/tools/miniconda3/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/Users/erjia/tools/miniconda3/envs/pytorch/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/erjia/tools/miniconda3/envs/pytorch/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/Users/erjia/workspace/pytorch/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 72427) is killed by signal: Unknown signal: 0.
```
All traceback info are printed out from all workers. 


Kill child process
The SIGTERM Signal Flow:
1. worker: _worker_loop() (Child daemon thread)
`_set_worker_signal_handlers()` (defined in **DataLoader.cpp**) handles the signal `SIGTERM` of child thread by re-raising `SIGTERM` to kill the current child daemon thread.
2. DataLoader (Main thread)
`_set_SIGCHLD_handler` (defined in **signal_handling.py**) uses `_error_if_any_worker_fails` to check any thread is failed, and raise `RuntimeError` to terminate main thread and other child threads.

Need to figure out:
In the worker thread, the signal `SIGTERM` has already been handled. And it seems there is issue with python signal handler.
https://docs.python.org/3/library/signal.html#execution-of-python-signal-handlers 
The python signal handler is executed before C low level handler, when I test it.

Proposal for kill:
Raise an runtime error from `_set_worker_signal_handlers()` in **DataLoader.cpp**, and worker in python catch the runtime error in this case, then terminate the child thread?

**Comment by SsnL** [comment]
@VitalyFedyunin  I don't know what this issue is trying to achieve. I strongly advise against unconditionally printing out the traces from workers on SIGINT. Most of the time when you SIGINT, you ***are not*** investigating stuck data set code. It is unreasonable to have main process tracebacks overwhelmed by a trace from every single worker, often interleaved together, and often with tens or even >30 workers. This will just create a massively unpleasant experience for most use cases. 

If you have slow dataset code, the proper way to investigate is just either (1) use `num_workers=0` or (2) profile dataset code and write to log file (per worker).  We could have some debug mode that properly logs errors and signals, but unconditionally printing out SIGINT traces is not the way to do this.

**Comment by VitalyFedyunin** [comment]
@ssnl agree, overly verbose (30x processes) dump is dangerous for usability. We currently do research on possibility of generating useful debug if user had to terminate stuck process. 

Unfortunately num_workers=0 or profiling not always working, as such kind of 'stuck process' sometimes manifest after hours/days of training. 

Anyway be sure, that we are not landing >30 similar debug traces as is.

**Comment by erjia-guan** [comment]
Just make some notes for the second scenario, as the worker is killed by user.
By injecting a traceback function within the signal hander in **DataLoader.cpp**
```
static void traceback() {
  std::cout << "Worker with pid " << getpid() << " is terminated. Traceback:\n";
  pybind11::gil_scoped_acquire gil;

  THPObjectPtr mod_tb(PyImport_ImportModule("traceback"));
  if (!mod_tb) {
    throw python_error();
  }

  THPObjectPtr stack_list(PyObject_CallMethod(mod_tb, "format_stack", ""));
  if (!stack_list) {
    throw python_error();
  }

  THPObjectPtr empty_string(PyUnicode_FromString(""));
  if (!empty_string) {
    throw python_error();
  }

  THPObjectPtr msg(PyUnicode_Join(empty_string, stack_list));
  if (!msg) {
    throw python_error();
  }

  std::cout << THPUtils_unpackString(msg.get());
}
```
```
static void handler_SIGTERM(int sig, siginfo_t *info, void *ctx)
{
  ...
  if (sigemptyset(&sa.sa_mask) != 0 || sigaction(SIGTERM, &sa, nullptr) != 0) {
    _exit(EXIT_FAILURE);
  } else {
    traceback();
    raise(SIGTERM);
  }
}
```

Since there are ways to traceback of **KeyboardInterrupted** and trace stack of `SIGTERM`, we can determine the methodology to log these information (may setting up a DEBUG flag) in the future.
cc: @VitalyFedyunin
