### ISSUE TITLE
AttributeError: Can't pickle local object 'GraphModule.__new__.<locals>.GraphModuleImpl'

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#43513]
Failed when trying to run ddp with qat
```
Traceback (most recent call last):
  File "test_resnet.py", line 88, in <module>
    join=True)
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/jerryzh/anaconda3/envs/modelathon/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'GraphModule.__new__.<locals>.GraphModuleImpl'
```

cc @gmagogsfm @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jamesr66a** [comment]
@jerryzh168 let me know if this is still an issue
