### ISSUE TITLE
getattr should not be used as a node name in GraphModule

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#43522]
e.g. after symbolic trace shufflenet:
```python
...
    getattr = cat_1.data
    size = getattr.size()
    getitem = size[0]
    getitem_1 = size[1]
    getitem_2 = size[2]
    getitem_3 = size[3]
    floordiv = getitem_1 // 2
    view = cat_1.view(getitem, 2, floordiv, getitem_2, getitem_3)
    transpose_1 = torch.transpose(view, 1, 2)
    contiguous = transpose_1.contiguous()
    view_1 = contiguous.view(getitem, -1, getitem_2, getitem_3)
    chunk_1 = view_1.chunk(2, dim = 1)
    getitem_4 = chunk_1[0]
    getitem_5 = chunk_1[1]
    stage2_1_branch2_0 = getattr(getattr(self.stage2, "1").branch2, "0")(getitem_5)
...
```

we will get following if we try to script:
```
Traceback (most recent call last):
  File "/data/users/jerryzh/pytorch/test/quantization/test_quantize_fx.py", line 833, in test_torchvision
    script = torch.jit.script(graph_module)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_script.py", line 888, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 317, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 376, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 292, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:
cannot call a value of type 'Tensor':
    getitem_4 = chunk_1[0]
    getitem_5 = chunk_1[1]
    stage2_1_branch2_0 = getattr(getattr(self.stage2, "1").branch2, "0")(getitem_5)
                                 ~~~~~~~ <--- HERE
    stage2_1_branch2_1 = getattr(getattr(self.stage2, "1").branch2, "1")(stage2_1_branch2_0)
    stage2_1_branch2_2 = getattr(getattr(self.stage2, "1").branch2, "2")(stage2_1_branch2_1)


----------------------------------------------------------------------
Ran 1 test in 17.521s
```

cc @gmagogsfm

**Comment by suo** [comment]
Is this torchvision's shufflenet? Can you post a repro

**Comment by jerryzh168** [comment]
> Is this torchvision's shufflenet? Can you post a repro

yes it's the shufflenet in torchvision, cc'ed you in my PR: https://github.com/pytorch/pytorch/pull/43526
