### ISSUE TITLE
JIT incorrectly records slice bounds

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#43548]
```python
import torch

class TestModule(torch.nn.Module):
    def forward(self, features, features_len):
        # assumes batch_size == 1
        eos_mask = torch.arange(features.shape[1]).eq(features_len).float()
        features[:,:,2] = eos_mask.unsqueeze(0)
        return features

features = torch.tensor(
    [[[1.0, 1.0, 0.0],
     [0.0, 0.0, 0.0]]]
)
print('features.shape=', features.shape)
features_len = torch.tensor([1])

module = TestModule()
traced_module = torch.jit.trace_module(module, dict(forward=(features, features_len,)))
print('Traced module code:')
print(traced_module.code)

print('Original module output:')
print(module(features.clone(), features_len))
print('Traced module output:')
print(module(features.clone(), features_len))

new_features = torch.tensor(
    [[[1.0, 1.0, 0.0],
     [1.0, 1.0, 0.0],
     [0.0, 0.0, 0.0]]]
)
print('new_features.shape=', new_features.shape)
new_features_len = torch.tensor([2])

print('Original module output:')
print(module(new_features.clone(), new_features_len))
print('Traced module output:')
print(traced_module(new_features.clone(), new_features_len))
```

```
features.shape= torch.Size([1, 2, 3])
Traced module code:
def forward(self,
    features: Tensor,
    features_len: Tensor) -> Tensor:
  _0 = ops.prim.NumToTensor(torch.size(features, 1))
  _1 = torch.arange(annotate(number, _0), dtype=None, layout=0, device=torch.device("cpu"), pin_memory=False)
  eos_mask = torch.to(torch.eq(_1, features_len), 6, False, False, None)
  _2 = torch.unsqueeze(eos_mask, 0)
  _3 = torch.slice(features, 0, 0, 9223372036854775807, 1)
  _4 = torch.slice(_3, 1, 0, 9223372036854775807, 1)
  _5 = torch.select(_4, 2, 2)
  _6 = torch.expand(torch.view(_2, [2]), [1, 2], implicit=True)
  _7 = torch.copy_(_5, _6, False)
  return features

Original module output:
tensor([[[1., 1., 0.],
         [0., 0., 1.]]])
Traced module output:
tensor([[[1., 1., 0.],
         [0., 0., 1.]]])
new_features.shape= torch.Size([1, 3, 3])
Original module output:
tensor([[[1., 1., 0.],
         [1., 1., 0.],
         [0., 0., 1.]]])
Traced module output:
Traceback (most recent call last):
  File "foo.py", line 38, in <module>
    print(traced_module(new_features.clone(), new_features_len))
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
foo.py(7): forward
/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py(704): _slow_forward
/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py(720): _call_impl
/miniconda/lib/python3.8/site-packages/torch/jit/__init__.py(1109): trace_module
foo.py(18): <module>
RuntimeError: shape '[2]' is invalid for input of size 3
```

cc @ezyang @gchanan @zou3519 @gmagogsfm

**Comment by vadimkantorov** [comment]
Also, what is 9223372036854775807 constant? Is it equivalent of None?

**Comment by gmagogsfm** [comment]
Hi vadimkantorov,

The error you are seeing is because different shapes of inputs are passed to module during tracing and execution. So it is expected to error.

As for 9223372036854775807, it is the default (max) value for `end` argument of `slice`. see [here](https://github.com/pytorch/pytorch/blob/4e0ac120e9a8b096069c2f892488d630a5c8f358/aten/src/ATen/native/native_functions.yaml#L2876).

**Comment by vadimkantorov** [comment]
In the trace it is recorded correctly in `torch.arange(...)` call as  `torch.size(features, 1)`. However it is not recorded correctly in `expand` call. That's what's strange.

@ezyang

**Comment by vadimkantorov** [comment]
@suo could you please take a look at this one? is it closed correctly?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
