### ISSUE TITLE
`nn.Module` + `@property` = wrong traceback message

### ISSUE THREAD

**Issue by siahuat0727** [pytorch/pytorch#43542]
## To Reproduce

Code

```python
import torch.nn as nn
 
class Module(nn.Module):
    def __init__(self):
        super().__init__()
        self.foo
 
    @property
    def foo(self):
        return [].bar  # This error cannot be traced correctly
        # return error  # This error can be traced correctly
 
Module()
```

Output

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    Module()
  File "main.py", line 6, in __init__
    self.foo
  File "/home/shengfa/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Module' object has no attribute 'foo'
```

## Expected behavior

Output if remove either `nn.Module` or `@property`

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    Module()
  File "main.py", line 6, in __init__
    self.foo
  File "main.py", line 10, in foo
    return [].bar  # This error can be traced correctly
AttributeError: 'list' object has no attribute 'bar'
```

## Environment

```
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: PH402 SKU 200
GPU 1: PH402 SKU 200
GPU 2: PH402 SKU 200
GPU 3: PH402 SKU 200
GPU 4: PH402 SKU 200
GPU 5: PH402 SKU 200
GPU 6: PH402 SKU 200
GPU 7: PH402 SKU 200

Nvidia driver version: 440.59
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-lightning==0.9.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect
```

cc @albanD @mruberry

**Comment by mariosasko** [comment]
This is a well-known issue (see [this](https://stackoverflow.com/questions/45016491/misleading-error-message-when-attributeerror-is-raised-in-property-of-class-deri)). It can be reproduced with the following code:
```python
class MyClass:

    def __init__(self):
        super().__init__()

    @property
    def foo(self):
        return 1
   
    @property
    def foo_error(self):
        return [].bar
    
    def __getattr__(self, name):
        return object.__getattr__(name)

print(MyClass().foo) # this works
print(MyClass().foo_error) #error
```
The reason for the misleading error message is that the `nn.Module` overrides the `object`'s `__getattr__` to allow access to the stored parameters/buffers/submodules with the dot notation (`model.buffer`).

**Comment by mariosasko** [comment]
This is a well-known issue (see [this](https://stackoverflow.com/questions/45016491/misleading-error-message-when-attributeerror-is-raised-in-property-of-class-deri)). It can be reproduced with the following code.
```python
class MyClass:

    @property
    def foo_error(self):
        return [].bar
        # raise AttributeError # or raise the error directly (it gets suppressed)
    
    def __getattr__(self, name):
        return object.__getattr__(name)

print(MyClass().foo_error)
```
`nn.Module` overrides the `object`'s `__getattr__` to allow access to the stored parameters/buffers/submodules with the dot notation (`model.buffer`).

**Comment by mruberry** [comment]
This does seem more like a Python language issue than a PyTorch issue, as I understand it.
