### ISSUE TITLE
gradcheck fails with cryptic error

### ISSUE THREAD

**Issue by jpeg729** [pytorch/pytorch#4355]
I tried implementing the [ISRLU activation](https://arxiv.org/pdf/1710.09967.pdf) but the `gradcheck` fails. I have pytorch 0.3.0 installed via conda.

Here is the code.
```python
import torch
from torch.autograd import Function

class ISRLU(Function):
    @staticmethod
    def forward(ctx, tensor, alpha=1):
        negatives = torch.min(tensor, 0 * tensor)
        ctx.nisr = torch.rsqrt(1. + alpha * (negatives ** 2))
        # ctx.nisr == 1 where tensor elements are positive
        return tensor * ctx.nisr

    @staticmethod
    def backward(ctx, grad_out):
        return ctx.nisr ** 3, None

ISRLU = ISRLU.apply

if __name__ == "__main__":
    from torch.autograd import Variable, gradcheck
    inputs = (Variable(torch.randn(20,20).double(), requires_grad=True), Variable(torch.randn(20,20).double(), requires_grad=True),)
    test = gradcheck(ISRLU, inputs, eps=1e-6, atol=1e-4)
    print(test)
```
And here is the error.
```
Traceback (most recent call last):
  File "activations/isrlu.py", line 50, in <module>
    test = gradcheck(ISRLU, inputs, eps=1e-6, atol=1e-4)
  File "/home/mpage/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 176, in gradcheck
    analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(_as_tuple(inputs), o)
  File "/home/mpage/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 110, in get_analytical_jacobian
    output.backward(grad_output, create_graph=True)
  File "/home/mpage/miniconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/mpage/miniconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: expected Variable or None (got torch.DoubleTensor)
```
Any ideas?

Interestingly, `gradcheck` isn't documented on the pytorch website. It is mentioned on the "Extending pytorch" page, but you won't find it on the `torch.autograd` page.

**Comment by apaszke** [comment]
The error message is quite self descriptive. You're returning a Tensor from `backward`, while you should have returned a Variable. If you want to return a tensor add `@once_differentiable`.

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).

**Comment by jpeg729** [comment]
I'm sorry, I really thought this was a bug.
I agree this question was more suited to the forums.
