### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PannuMuthu** [pytorch/pytorch#43604]
Issue description
Attempting to run Detectron 2, getting the above error

Code example
python demo.py –config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --webcam \ --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

Ubuntu 20
Pytorch 1.4.0
Python3.7

System Info
Traceback (most recent call last):
File "demo.py", line 11, in
from detectron2.data.detection_utils import read_image
File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/data/init.py", line 4, in
from .build import (
File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/data/build.py", line 14, in
from detectron2.structures import BoxMode
File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/structures/init.py", line 6, in
from .keypoints import Keypoints, heatmaps_to_keypoints
File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/structures/keypoints.py", line 6, in
from detectron2.layers import interpolate
File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/layers/init.py", line 3, in
from .deform_conv import DeformConv, ModulatedDeformConv
File "/home/ty/anaconda3/envs/detectron_env/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 10, in
from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by mruberry** [comment]
@PannuMuthu is this because you didn't build detectron2? See https://github.com/facebookresearch/detectron2/issues/157.

**Comment by malfet** [comment]
@PannuMuthu, can you please run `python -m torch.utils.collect_env` and post results here? Also, how did you install PyTorch? From PiP or have you build it yourself?

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues already:

> Undefined symbols that contains TH,aten,torch,caffe2; missing torch dynamic libraries; segmentation fault immediately when using detectron2.
This usually happens when detectron2 or torchvision is not compiled with the version of PyTorch you’re running.
If the error comes from a pre-built torchvision, uninstall torchvision and pytorch and reinstall them following pytorch.org. So the versions will match.
If the error comes from a pre-built detectron2, check release notes to see the corresponding pytorch version required for each pre-built detectron2. Or uninstall and reinstall the correct pre-built detectron2.

**Comment by malfet** [comment]
Duplicate of #38090 — same detectron2 `demo.py` failure and identical traceback (`from detectron2 import _C` -> `ImportError: libtorch_cpu.so`). Root cause is a version mismatch: the prebuilt detectron2 `_C` extension was compiled against a different PyTorch than the one installed (PyTorch 1.5.0 split `libtorch.so` into `libtorch_cpu.so`/`libtorch_cuda.so`, see #29235). Align the detectron2 and torch versions. Consolidating into #38090.
