### ISSUE TITLE
How to see the weight  value of the quantified model?

### ISSUE THREAD

**Issue by YongtaoHuang1994** [pytorch/pytorch#43625]
How to see the weight  value of the quantified model?

Error:
```
torch.nn.modules.module.ModuleAttributeError: 'LinearPackedParams' object has no attribute '_parameters'
```

Code:
```
import torch
import numpy as np
import matplotlib.pyplot as plt

MODLE_LOCATION = "./models/mfi_0.97400.pth"
MODLE_LOCATION_QUAN = "./models/quantized_1_model.pth"
TENSOR_NAME = "fc1.weight"

def plot_distribution(model_name, tensor_set, resolution):
    model = torch.load(model_name)
    print(model)
    params = model.state_dict()
    tensor_value = params[TENSOR_NAME]
    tensor_value_np = tensor_value.numpy()
    tensor_value_np = tensor_value_np.flatten()
    bins = np.arange(-1, 1, resolution)
    plt.hist(tensor_value_np,bins) 
    plt.title("histogram") 
    plt.show()


if __name__ == '__main__':
    plot_distribution(MODLE_LOCATION, TENSOR_NAME, 0.01)
    plot_distribution(MODLE_LOCATION_QUAN, TENSOR_NAME, 0.01)
```

Output:
```
(bnntorch) D:\FewShotMFI\Python\MFI_pytorch>python  plt_distribution.py
LeNet5_Improved(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (bn1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (max_pool_1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (max_pool_2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=400, out_features=180, bias=True)
  (dropout1): Dropout(p=0.2, inplace=False)
  (fc2): Linear(in_features=180, out_features=100, bias=True)
  (dropout2): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=100, out_features=20, bias=True)
)
LeNet5_Improved(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (bn1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (max_pool_1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (max_pool_2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): DynamicQuantizedLinear(in_features=400, out_features=180, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
  (dropout1): Dropout(p=0.2, inplace=False)
  (fc2): DynamicQuantizedLinear(in_features=180, out_features=100, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
  (dropout2): Dropout(p=0.2, inplace=False)
  (fc3): DynamicQuantizedLinear(in_features=100, out_features=20, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
)
Traceback (most recent call last):
  File "plt_distribution.py", line 26, in <module>
    plot_distribution(MODLE_LOCATION_QUAN, TENSOR_NAME, 0.01)
  File "plt_distribution.py", line 14, in plot_distribution
    params = model.state_dict()
  File "C:\Users\huangyongtao\AppData\Local\conda\conda\envs\bnntorch\lib\site-packages\torch\nn\modules\module.py", line 900, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "C:\Users\huangyongtao\AppData\Local\conda\conda\envs\bnntorch\lib\site-packages\torch\nn\modules\module.py", line 900, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "C:\Users\huangyongtao\AppData\Local\conda\conda\envs\bnntorch\lib\site-packages\torch\nn\modules\module.py", line 897, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "C:\Users\huangyongtao\AppData\Local\conda\conda\envs\bnntorch\lib\site-packages\torch\nn\quantized\modules\linear.py", line 62, in _save_to_state_dict
    super(LinearPackedParams, self)._save_to_state_dict(destination, prefix, keep_vars)
  File "C:\Users\huangyongtao\AppData\Local\conda\conda\envs\bnntorch\lib\site-packages\torch\nn\modules\module.py", line 856, in _save_to_state_dict
    for name, param in self._parameters.items():
  File "C:\Users\huangyongtao\AppData\Local\conda\conda\envs\bnntorch\lib\site-packages\torch\nn\modules\module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'LinearPackedParams' object has no attribute '_parameters'

```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
you can do `fc.weight()` and `fc.bias()`(https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/linear.py#L233)

**Comment by jerryzh168** [comment]
btw please post questions to https://discuss.pytorch.org/c/quantization/17

**Comment by jerryzh168** [comment]
closing now, please feel free to reopen if you have further questions
