### ISSUE TITLE
Error in saving pytorch model

### ISSUE THREAD

**Issue by gentaiscool** [pytorch/pytorch#4372]
I got this error after I called retain_grad() on my variable. I worked in python 3.5.

Traceback (most recent call last):
  File "main.py", line 256, in <module>
    torch.save(model, f)
  File "/home/genta/.local/lib/python3.5/site-packages/torch/serialization.py", line 134, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/genta/.local/lib/python3.5/site-packages/torch/serialization.py", line 116, in _with_file_like
    return body(f)
  File "/home/genta/.local/lib/python3.5/site-packages/torch/serialization.py", line 134, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/genta/.local/lib/python3.5/site-packages/torch/serialization.py", line 197, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'Variable.retain_grad.<locals>.retain_grad_hook'

Appreciate any useful help. Thanks

**Comment by apaszke** [comment]
Did you call that on a parameter? There's no need to do so - parameters have to be leaves and will retain grad anyway. If you did that on an intermediate Variable - those can't be pickled and that's a known thing. If you cached any intermediates in your model you'll need to remove them before picking.
