### ISSUE TITLE
[jit] allow tracing to only compile export methods, instead of generating scriptmodule for submodule

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#43729]
from internal post https://fb.workplace.com/groups/329222650990087/permalink/709480952964253/

Tracing currently examine if module has export methods, if it has, it tries to compile the methods of that module, during the compilation, it will compile any submodule as scripting (with the default methods infer rule), see https://github.com/pytorch/pytorch/blob/825ec18eed9ea96328f1151ab172998964724307/torch/jit/_recursive.py#L352  User might want only compile those export methods, but still trace other methods for those submodules (e.g. other methods cann't be easily scripted). 

We should consider changing the behavior to allow it

cc @gmagogsfm

**Comment by wanchaol** [comment]
cc @suo @eellison Example code snippet that crashes

```python
import torch
import torch.nn as nn

class SubModule(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):
        # example code can only be traced, but not scripted
        func = lambda a: a + 1
        return func(input)


class ParentModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.submod = SubModule()

    def forward(self, input):
        return input + 1

    @torch.jit.export
    def test_a(self, input):
        return input - 3



input = torch.randn(3, 4)
model = ParentModule()
traced = torch.jit.trace(model, input)
```

with crashes:
```
Traceback (most recent call last):
  File "/private/home/wanchaol/test_trace.py", line 89, in <module>
  ...
  File "/scratch/wanchaol/pytorch/torch/jit/frontend.py", line 225, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: Lambda aren't supported:
  File "/private/home/wanchaol/test_trace.py", line 69
    def forward(self, input):
        # example code can only be traced, but not scripted
        func = lambda a: a + 1
               ~ <--- HERE
        return func(input)
```

Note that if we comment out the `jit.export` in `ParentModule`, it works nicely, this is because:

If we have `export` methods in parentModule, we are invoking a recursive compilation to compile the `submod`, see https://github.com/pytorch/pytorch/blob/7816d53798efcd1dc68a83a2964ee6d4ef4181ca/torch/jit/_trace.py#L567, and will compile the `submod` from `forward` use the default inference rule. see https://github.com/pytorch/pytorch/blob/7816d53798efcd1dc68a83a2964ee6d4ef4181ca/torch/jit/_recursive.py#L356



But if we don't have `jit.export`, we are just creating dummy ScriptModule and trace the methods from `forward` to generate the ScriptMethods and install them. 

My approach in https://github.com/pytorch/pytorch/pull/43872 is to allow tracing to pass submodule methods infer rule so that we don't always use the default rule to compile the submodule (then we could avoid scripting the `forward`).
