### ISSUE TITLE
Getting Cuda error (3): initialization error

### ISSUE THREAD

**Issue by fer-git** [pytorch/pytorch#4377]
I got a problem when I need to iterate through DataLoader. I think the problem lies on num_workers parameter in DataLoader. Here is a snippet to reproduce the error:

```
import torch
from torch.utils.data import DataLoader, TensorDataset

features = torch.cuda.LongTensor(range(12)).view(3, 4)
labels = torch.cuda.LongTensor(range(3))
dataset = TensorDataset(features, labels)
dataloader = DataLoader(dataset, num_workers=2)
for feat, lab in dataloader:
    print(feat)
    print(lab)
```
The error that I got:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fernandopratama/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/home/fernandopratama/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/fernandopratama/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/fernandopratama/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/fernandopratama/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 39, in __getitem__
    return self.data_tensor[index], self.target_tensor[index]
RuntimeError: CUDA error (3): initialization error
```
I do not have issues when I run it on CPU with num_workers > 0 and on GPU with num_workers=0.

My torch version is 0.3.0.post4
Python version is 3.6.4
Ubuntu version is 17.04
Cuda version is 9.0.176

**Comment by apaszke** [comment]
See [multiprocessing docs](http://pytorch.org/docs/master/multiprocessing.html#sharing-cuda-tensors). If you want to use CUDA, change the start method (it's a limitation of the CUDA runtime, we can't do anything about this).
