### ISSUE TITLE
torch.tensor does not support list of complex tensor

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#43833]
```python
>>> torch.tensor([torch.tensor(1)])
tensor([1])
>>> torch.tensor([torch.tensor(1j)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: value cannot be converted to type double without overflow: (0,1)
>>> torch.tensor([1j])
tensor([0.+1.j])
```

cc @ezyang @anjali411 @dylanbespalko

**Comment by zasdfgbnm** [comment]
I think the root cause is because tensor objects do not have `__complex__`:
```
>>> complex(torch.tensor(1j))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: value cannot be converted to type double without overflow: (0,1)
>>> torch.tensor(1j).__complex__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tensor' object has no attribute '__complex__'
```
