### ISSUE TITLE
new stride propagation logic in TensorIterator (#42922) broke examples/imagenet

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#43998]
## 🐛 Bug

The following commit has broken the examples/imagenet trainer.

commit c8bc298d6c7850a1b33416eea56e4fc365d6af9a
Author: Natalia Gimelshein <ngimel@fb.com>
Date:   Thu Aug 20 10:48:26 2020 -0700

streamline stride propagation logic in TensorIterator (#42922)

## To Reproduce

1. git clone https://github.com/pytorch/examples.git
2. Download imagenet dataset.
3. Run imagenet
cd examples/imagenet
python3.6 main.py -a resnet50 --dist-url 'tcp://127.0.0.1:8080' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 /dockerx/Imagenet --epochs 91 --batch-size 1024  -j$(nproc)

## Backtrace/Exception
```
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 109, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/root/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/root/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/root/examples/imagenet/main.py", line 245, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "/root/examples/imagenet/main.py", line 294, in train
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/root/examples/imagenet/main.py", line 423, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

## Expected behavior

Should get typical output, for example

```
Epoch: [0][   0/1252]   Time 20.707 (20.707)    Data 17.063 (17.063)    Loss 7.0843e+00 (7.0843e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
Epoch: [0][   0/1252]   Time 20.737 (20.737)    Data 16.294 (16.294)    Loss 7.0663e+00 (7.0663e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.78 (  0.78)
Epoch: [0][   0/1252]   Time 20.748 (20.748)    Data 17.260 (17.260)    Loss 7.1067e+00 (7.1067e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.78 (  0.78)
Epoch: [0][   0/1252]   Time 20.763 (20.763)    Data 17.383 (17.383)    Loss 6.9512e+00 (6.9512e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.78 (  0.78)
Epoch: [0][   0/1252]   Time 20.707 (20.707)    Data 15.991 (15.991)    Loss 7.1026e+00 (7.1026e+00)    Acc@1   0.00 (  0.00)   Acc@5   1.56 (  1.56)
Epoch: [0][   0/1252]   Time 20.789 (20.789)    Data 17.108 (17.108)    Loss 7.0619e+00 (7.0619e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
Epoch: [0][   0/1252]   Time 20.730 (20.730)    Data 16.861 (16.861)    Loss 7.1637e+00 (7.1637e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.78 (  0.78)
Epoch: [0][   0/1252]   Time 20.709 (20.709)    Data 17.581 (17.581)    Loss 7.1278e+00 (7.1278e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
Epoch: [0][  10/1252]   Time  0.404 ( 2.229)    Data  0.000 ( 1.581)    Loss 7.2817e+00 (7.2198e+00)    Acc@1   0.00 (  0.07)   Acc@5   0.00 (  0.64)
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] torch==1.6.0
[pip] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py37_cu101    pytorch
```

**Comment by ngimel** [comment]
Is it happening with distributed only, or with regular training too?

**Comment by ngimel** [comment]
The repro is easy
```
import torch

def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res

bs =128
output = torch.randn(bs, 1024)
target = torch.randint(1024, (bs,))
accuracy(output, target, topk=(1,5))
```
I'll send the fix to imagenet example, it should be calling `reshape` instead of view.

**Comment by ngimel** [comment]
https://github.com/pytorch/examples/pull/820

**Comment by jeffdaily** [comment]
Fix was confirmed back in September.  Closing issue now.  Thanks.
