### ISSUE TITLE
Model can foward but onnx export throw a bug

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#44012]
My model can get forward using GPU, but onnx export got a bug:

```
Traceback (most recent call last):
  File "models/onnx_export.py", line 60, in <module>
    output_names=['output'])  # output_names=['output']
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 409, in _model_to_graph
    _export_onnx_opset_version)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

```

this is not my model logic error since the model using pytorch can forward, it that a bug in onnx export? It says I need GPU in a node but I have every single node in GPU, how could that possible? Besides, my model can forward using pytorch, if that happen, the pyotorch model forward can catach it.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
The recommended way is to set the device to cpu (and also to eval mode) before export. Can you try that?

**Comment by spandantiwari** [comment]
@jinfagang - just checking if you were able to try the suggestion and if it helped.

**Comment by spandantiwari** [comment]
Please reopen if there's still some issue.
