### ISSUE TITLE
fx: unable to symbolically trace simple nn.Sequential model

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#44111]
## 🐛 Bug

Seeing errors when trying to trace simple models based on `nn.Sequential`:

```
Traceback (most recent call last):
  File "/home/vasiliy/nfs/pytorch_scripts/gm_sequential_bug.py", line 7, in <module>
    gm = symbolic_trace(m)
  File "/data/users/vasiliy/pytorch/torch/fx/symbolic_trace.py", line 222, in symbolic_trace
    return GraphModule(root, graph)
  File "/data/users/vasiliy/pytorch/torch/fx/graph_module.py", line 65, in __init__
    self._generate_forward()
  File "/data/users/vasiliy/pytorch/torch/fx/graph_module.py", line 83, in _generate_forward
    exec_with_source(self.code, gbls)
  File "/data/users/vasiliy/pytorch/torch/fx/graph_module.py", line 18, in exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key_0>", line 3
SyntaxError: cannot assign to literal
```

Note: doesn't repro on real models using `nn.Sequential`, I have only seen it on toy examples.

## To Reproduce

1. run this script: https://gist.github.com/vkuzo/c37d42607a11770ab9f2a976bb0b98dc
2. see this error: https://gist.github.com/vkuzo/70e3eca34211864f6c7be4c4bbfd558b

**Comment by vkuzo** [comment]
@jamesr66a , could someone from the JIT team take a look?

**Comment by jamesr66a** [comment]
The source generated here is:
```
def forward(self, input):
    0 = getattr(self, "0")(input)
    

    return 0
```

And is a result of `Sequential` using integers in strings as keys (which is invalid in Python and thus why the `getattr` is emitted rather than a `self.0` attribute fetch.

I'll see how hard it is to sanitize the identifiers in this scenario

**Comment by vkuzo** [comment]
likely related, we encountered https://gist.github.com/vkuzo/30f358c505def3085e10f185c2df41de today while checking whether classy vision models are traceable.  Relevant line where an invalid variable name is attempted to be created:

```
blocks_0_block0-0_downsample_0 = getattr(getattr(getattr(self.blocks, "0"), "block0-0").downsample, "0")(initial_block__module_3)
```

**Comment by jamesr66a** [comment]
People should really stop using invalid identifier names as attribute names....

**Comment by jamesr66a** [comment]
https://github.com/pytorch/pytorch/pull/44808

**Comment by vkuzo** [comment]
thanks for the fix!

**Comment by vkuzo** [comment]
just a heads up, seems like there was a regression and this now fails with a different error:

```
import torch                   
import torch.nn as nn          
                               
m = nn.Sequential(             
    nn.Conv2d(1, 1, 1),        
)                              
gm = torch.fx.symbolic_trace(m)

...

Traceback (most recent call last):
  File "/home/vasiliy/local/tmp/quant_fx_playground.py", line 16, in <module>
    mp = torch.quantization.prepare_fx(m, qconfig_dict)
  File "/data/users/vasiliy/pytorch/torch/quantization/quantize_fx.py", line 190, in pr
epare_fx
    return _prepare_fx(model, qconfig_dict, inplace, prepare_custom_config_dict)
  File "/data/users/vasiliy/pytorch/torch/quantization/quantize_fx.py", line 64, in _pr
epare_fx
    graph_module = _fuse_fx(graph_module, inplace)
  File "/data/users/vasiliy/pytorch/torch/quantization/quantize_fx.py", line 24, in _fu
se_fx
    return fuser.fuse(graph_module, inplace)
  File "/data/users/vasiliy/pytorch/torch/quantization/fx/fuse.py", line 38, in fuse
    env[node.name] = self.fused_graph.node_copy(node, load_arg)
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 265, in node_copy
    name = self._name(sanitized_name)
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 283, in _name
    if op[0].isdigit():
IndexError: string index out of range
```

**Comment by vkuzo** [comment]
actually, my bad, that trace points to quantization and not symbolic tracing, will file a separate issue.  Sorry :)

**Comment by Priyanshu88** [comment]
Hey @vkuzo, did you get your issue resolved, I am facing similar problem:

```  File "/mmrazor/mmrazor/models/task_modules/tracer/fx/custom_tracer.py", line 319, in call_method
    return self.create_proxy('call_method', name, args, kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/proxy.py", line 66, in create_proxy
    args_ = self.create_arg(args)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 344, in create_arg
    return super().create_arg(a)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/proxy.py", line 140, in create_arg
    return type(a)(self.create_arg(elem) for elem in a)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/proxy.py", line 140, in <genexpr>
    return type(a)(self.create_arg(elem) for elem in a)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 298, in create_arg
    return self.create_node("get_attr", n_, (), {})
  File "/opt/conda/lib/python3.9/site-packages/torch/ao/quantization/fx/tracer.py", line 114, in create_node
    node = super().create_node(kind, target, args, kwargs, name, type_expr)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/proxy.py", line 46, in create_node
    return self.graph.create_node(kind, target, args, kwargs, name, type_expr)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/graph.py", line 777, in create_node
    name = self._graph_namespace.create_name(candidate, None)
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/graph.py", line 137, in create_name
    if candidate[0].isdigit():
IndexError: string index out of range```

**Comment by dgcnz** [comment]
> actually, my bad, that trace points to quantization and not symbolic tracing, will file a separate issue. Sorry :)

Hey @vkuzo, could you link to that issue? I think I'm having a similar problem when export quantizing dinov2.
