### ISSUE TITLE
random crashing in asyncio with AMP and DistributedDataParallel using cuDNN GRUs

### ISSUE THREAD

**Issue by greaber** [pytorch/pytorch#44246]
## 🐛 Bug

I'm experiencing my training crashing when using the new cuDNN RNN support from AMP added by @mcarilli together with DistributedDataParallel.  Unfortunately, this crashing is random and usually doesn't happen until my training has been running for several hours, so it is hard for me even to come up with a small example to reproduce it.  All I see is an endless loop of the following stack trace:

```
Exception in thread Thread-4225356:
Traceback (most recent call last):
  File "/home/grant/miniconda3/lib/python3.7/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/home/grant/miniconda3/lib/python3.7/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '5 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/grant/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 102, in in_thread
    line = self.pt_app.prompt()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/home/grant/miniconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 778, in run_async
    return await _run_async2()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 760, in _run_async2
    result = await _run_async()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 683, in _run_async
    with self.input.attach(read_from_input):
  File "/home/grant/miniconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/prompt_toolkit/input/vt100.py", line 176, in _attached_input
    loop.add_reader(fd, callback)
  File "/home/grant/miniconda3/lib/python3.7/asyncio/selector_events.py", line 329, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/home/grant/miniconda3/lib/python3.7/asyncio/selector_events.py", line 259, in _add_reader
    (handle, None))
  File "/home/grant/miniconda3/lib/python3.7/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted
```

I'm not even sure if it is a PyTorch bug, but I am using AMP and DDP in what I think is a totally standard way, so at a minimum it seems like a case where PyTorch should provide better info about what is wrong.  Can anyone suggest anything based just on this stack trace?

## Environment

PyTorch version: 1.7.0.dev20200904
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 440.82
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.7.0.dev20200904
[pip3] torchvision==0.8.0.dev20200904
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] torch                     1.7.0.dev20200904          pypi_0    pypi
[conda] torchvision               0.8.0.dev20200904          pypi_0    pypi

**Comment by greaber** [comment]
I can't reproduce this now, probably it is not a real bug, closing.
