### ISSUE TITLE
mean with repeated dim gives inconsistent results for cpu and cuda

### ISSUE THREAD

**Issue by tgsmdww** [pytorch/pytorch#44273]
## To Reproduce

```
import torch
a = torch.arange(1,17).float().reshape(4,4)
print(a)
cpu_res = torch.mean(a, (0,0))
cuda_res = torch.mean(a.cuda(), (0,0))
print(cpu_res)
print(cuda_res)
```
Result is 
```
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([1.7500, 2.0000, 2.2500, 2.5000])
tensor([ 7.,  8.,  9., 10.], device='cuda:0')
```

When transfer a same dim like 0 twice, CUDA and CPU return different result. It seems like CPU calculates mean twice and CUDA not.

cc @ezyang @gchanan @zou3519

**Comment by kshitij12345** [comment]
It is the same case with `torch.sum`
```python
>>> import torch
>>> x = torch.randn(3,3,3)
>>> x.sum(dim=(0,0))
tensor([[-0.4405,  1.1700, -1.0653],
        [ 2.0856, -2.0031,  2.3432],
        [-0.5296,  1.0978, -1.6175]])
>>> x.sum(dim=(0,1))
tensor([ 1.1155,  0.2646, -0.3395])
>>> import numpy
>>> x_np = x.numpy()
>>> x_np.sum(axis=(0, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Desktop/Repositories/Pytorch/PytorchENV/lib/python3.7/site-packages/numpy/core/_methods.py", line 47, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
ValueError: duplicate value in 'axis'

```

**Comment by zhangguanheng66** [comment]
inconsistent results for `torch.mean` operator on cpu and cuda.

**Comment by ezyang** [comment]
What version of PyTorch are you testing on?
