### ISSUE TITLE
How to package pytorch with the file build from source.

### ISSUE THREAD

**Issue by Abbyyan** [pytorch/pytorch#44460]
## ❓ Questions and Help

I've noticed in https://github.com/pytorch/pytorch/issues/31285 that pytorch only compile binaries for NV cards with CC 3.7 and up. Now i've build pytorch from source on my machine. Is there any way to package it into a new pip image please？ Thanks a lot.

cc @malfet @seemethere @walterddr

**Comment by colesbury** [comment]
Use `python setup.py bdist_wheel` to build a wheel file. The wheel file will be in the `dist` sub-directory.

**Comment by malfet** [comment]
Please reopen the issue if following would not solve you problem.

**Comment by Abbyyan** [comment]
> Use `python setup.py bdist_wheel` to build a wheel file. The wheel file will be in the `dist` sub-directory.

Thanks a lot.

**Comment by chasebrignac** [comment]
What does CC stand for? CUDA Compute? I'm showing CUDA version 11.6 when I run `nvidia-smi` but when I use this python line `pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization')` I got the error:

```
Traceback (most recent call last):
  File "annotate.py", line 21, in <module>
    pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization')
  File "/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/pipeline.py", line 98, in from_pretrained
    pipeline = Klass(**config["pipeline"].get("params", {}))
  File "/usr/local/lib/python3.8/dist-packages/pyannote/audio/pipelines/speaker_diarization.py", line 117, in __init__
    model.to(seg_device)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 121, in to
    return super().to(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/rnn.py", line 189, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/rnn.py", line 175, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by chasebrignac** [comment]
I think I found the answer. CC is CUDA Compute Capability. You can see yours in linux by running
```
nvidia-smi --query-gpu=compute_cap --format=csv
```
If you are running a docker container you can check your GPU from the docker container by running
```
!sudo docker run -it --gpus all mcaption:latest nvidia-smi --query-gpu=compute_cap --format=csv
```
For me I get compute cap 8.0 which I think is fairly recent... Maybe it's because pyannotate hasn't been updated in awhile and so needs a lower compute_cap?
```
compute_cap
8.0
```
