### ISSUE TITLE
TestJitGeneratedModule.test_nn_CTCLoss_lengths_intlists fails if not skipped

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#44503]
In https://github.com/pytorch/pytorch/commit/fa158c4ca60d7bcd1ec52bdfaf4cee2d8d9e923a, if I remove the `check_jit`s and run:

 `python test_jit.py TestJitGeneratedModule.test_nn_CTCLoss_lengths_intlists`

I get:
```
======================================================================
ERROR: test_nn_CTCLoss_lengths_intlists (__main__.TestJitGeneratedModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 528, in wrapper
    fn(*args, **kwargs)
  File "test_jit.py", line 15776, in do_test
    check_against_reference(self, create_script_module, create_nn_module, f_args_variable, no_grad=no_grad)
  File "test_jit.py", line 15380, in check_against_reference
    outputs_test = self.runAndSaveRNG(func, nograd_inputs, kwargs)
  File "/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 583, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "test_jit.py", line 15741, in create_script_module
    module = make_module(script)
  File "test_jit.py", line 15738, in make_module
    module.define(script)
  File "/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages/torch/jit/_script.py", line 311, in define
    return self._actual_script_module.define(src)
  File "/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages/torch/jit/_script.py", line 529, in define
    self._c._define(self._concrete_type, src, rcb)
RuntimeError: expected ident but found '[' here:
  File "<string>", line 2

def forward(self, i0, i1, [50, 50, 50], [30, 25, 20]):
                          ~ <--- HERE
    return self.submodule(i0, i1, [50, 50, 50], [30, 25, 20])
```

If I had to guess, it looks like a typing problem because CTCLoss in python supports int arrays, but the signature only says it supports Tensors.  But the error message is pretty incomprehensible, so this is a guess.

**Comment by SplitInfinity** [comment]
```
class CTCLoss(_Loss):
    ...
    ...
    ...
    __constants__ = ['blank', 'reduction']
    blank: int
    zero_infinity: bool

    def __init__(self, blank: int = 0, reduction: str = 'mean', zero_infinity: bool = False):
        super(CTCLoss, self).__init__(reduction=reduction)
        self.blank = blank
        self.zero_infinity = zero_infinity

    def forward(self, log_probs: Tensor, targets: Tensor, input_lengths: Tensor, target_lengths: Tensor) -> Tensor:
        return F.ctc_loss(log_probs, targets, input_lengths, target_lengths, self.blank, self.reduction,
                          self.zero_infinity)
```

Yeah, looks like a typing problem. JIT doesn't have a `Union` type, so the only options here are:
- disable the test
- annotate the type of `input_lengths` and `targets_lengths` as `Any` and modify the code accordingly (perform type refinement in the body of `forward` and handle the cases in which they are `Tensors` and `List[int]` separately)
- supply `Tensors` in the test instead (although this seems to defeat the point of the test)

**Comment by gchanan** [comment]
the test is disabled for now.  There is already a test that supplies Tensors so correct, no point in doing that.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
