### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:18

### ISSUE THREAD

**Issue by GeorgeBohw** [pytorch/pytorch#4454]
the errors as following:

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    generated = model.inference(data['label'], data['inst'])
  File "/home/george/project/pix2pixHD/models/pix2pixHD_model.py", line 175, in inference
    input_label, inst_map, _, _ = self.encode_input(Variable(label), Variable(inst), infer=True)    
  File "/home/george/project/pix2pixHD/models/pix2pixHD_model.py", line 106, in encode_input
    inst_map = inst_map.data.cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:18

it mean the memory is not enough?
anybody know how to solve it？appreciate！

**Comment by GeorgeBohw** [comment]
it's ok when i change to use another gpu（change gpu_id to 1）,maybe the problem is from gpu itself.

**Comment by pardha-fission** [comment]
I am also working on the same pix2pixHD repository and facing the same issue can you please give of how you solved it
