### ISSUE TITLE
torch.distributed ignores passed MASTER_PORT

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#44544]
Despite the passed port, it still tries to bind and to connect to a random port. If this is due to some TCP binding error, it should be printed. This is extremely confusing :(

```python
import os
import torch
import argparse
import torch.distributed as dist

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--backend', default='gloo')
    parser.add_argument('--rank', type=int, default=0)
    parser.add_argument('--world-size', type=int, default=1)
    args = parser.parse_args()
    dist.init_process_group(args.backend, init_method="env://", rank=args.rank, world_size=args.world_size)
    print(f"Master node {os.environ['MASTER_ADDR']}:{os.environ['MASTER_PORT']}. Rank {args.rank}. World size: {args.world_size}")
    test_tensor = torch.tensor(args.rank+1)
    if args.backend == 'nccl':
        test_tensor = test_tensor.cuda()
    dist.all_reduce(test_tensor, op=dist.ReduceOp.SUM)
    print(f"Test value: {test_tensor.item()}, expected: {sum(range(args.world_size+1))}")
```

```
Test standalone

Node 1
Input: 
GLOO_SOCKET_IFNAME=team0 MASTER_ADDR=10.81.13.54 MASTER_PORT=12345 python distributed_example.py
Output: 
Master node 10.81.13.54:12345. Rank 0. World size: 1
Test value: 1, expected: 1

Node 2
Input: 
GLOO_SOCKET_IFNAME=team0 MASTER_ADDR=10.81.13.51 MASTER_PORT=12345 python distributed_example.py 
Output: 
Master node 10.81.13.51:12345. Rank 0. World size: 1
Test value: 1, expected: 1

Test disctibuted Gloo

Node 1
Input: 
GLOO_SOCKET_IFNAME=team0 MASTER_ADDR=10.81.13.54 MASTER_PORT=12345 python distributed_example.py --rank 0 --world-size 2
Output: 
Traceback (most recent call last):
  File "distributed_example.py", line 11, in <module>
    dist.init_process_group('gloo', init_method="env://", rank=args.rank, world_size=args.world_size)
  File "/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 425, in init_process_group
    _default_pg = _new_process_group_helper(
  File "/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 499, in _new_process_group_helper
    pg = ProcessGroupGloo(
RuntimeError: [/opt/conda/conda-bld/pytorch_1595629411241/work/third_party/gloo/gloo/transport/tcp/pair.cc:769] connect [10.81.13.51]:11169: No route to host

Node 2
Input:
GLOO_SOCKET_IFNAME=team0 MASTER_ADDR=10.81.13.54 MASTER_PORT=12345 python distributed_example.py --rank 1 --world-size 2
Output:

Test distributed NCCL

Node 1
Input:
NCCL_SOCKET_IFNAME=team0 NCCL_DEBUG=INFO MASTER_ADDR=10.81.13.54 MASTER_PORT=12345 python distributed_example.py --rank 0 --world-size 2 --backend nccl
Output:
Master node 10.81.13.54:12345. Rank 0. World size: 2
srs-ds11:64570:64570 [0] NCCL INFO Bootstrap : Using [0]team0:10.81.13.54<0>
srs-ds11:64570:64570 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

srs-ds11:64570:64570 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
srs-ds11:64570:64570 [0] NCCL INFO NET/Socket : Using [0]team0:10.81.13.54<0>
NCCL version 2.4.8+cuda10.1
srs-ds11:64570:65266 [0] NCCL INFO Setting affinity for GPU 0 to 55,55555555

Node 2
Input:
NCCL_SOCKET_IFNAME=team0 NCCL_DEBUG=INFO MASTER_ADDR=10.81.13.54 MASTER_PORT=12345 python distributed_example.py --rank 1 --world-size 2 --backend nccl
Output:
Master node 10.81.13.54:12345. Rank 1. World size: 2
srs-ds8:192240:192240 [0] NCCL INFO Bootstrap : Using [0]team0:10.81.13.51<0>
srs-ds8:192240:192240 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

srs-ds8:192240:192240 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
srs-ds8:192240:192240 [0] NCCL INFO NET/Socket : Using [0]team0:10.81.13.51<0>
srs-ds8:192240:192316 [0] NCCL INFO Setting affinity for GPU 0 to 55,55555555

srs-ds8:192240:192316 [0] include/socket.h:390 NCCL WARN Connect to 10.81.13.54<34419> failed : No route to host
srs-ds8:192240:192316 [0] NCCL INFO bootstrap.cc:100 -> 2
srs-ds8:192240:192316 [0] NCCL INFO bootstrap.cc:326 -> 2
srs-ds8:192240:192316 [0] NCCL INFO init.cc:695 -> 2
srs-ds8:192240:192316 [0] NCCL INFO init.cc:951 -> 2
srs-ds8:192240:192316 [0] NCCL INFO misc/group.cc:69 -> 2 [Async thread]
Traceback (most recent call last):
  File "distributed_example.py", line 17, in <module>
    dist.all_reduce(test_tensor, op=dist.ReduceOp.SUM)
  File "/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 936, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1595629411241/work/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8
```

**Comment by vadimkantorov** [comment]
From strace it seems that server itself tries also to connect somewhere (by some random port). Very strange

**Comment by pritamdamania87** [comment]
Unfortunately for gloo it seems like we just pick random ports for the client and there is no way to configure this currently. NCCL seems to be doing the same based on the logs you pasted (`srs-ds8:192240:192316 [0] include/socket.h:390 NCCL WARN Connect to 10.81.13.54<34419> failed : No route to host
`). I couldn't find a way to configure this for NCCL, maybe you can create a gh issue in https://github.com/NVIDIA/nccl asking if there is a way to make NCCL work where there is a firewall and you'd like to only open a handful of ports for NCCL to use.

**Comment by vadimkantorov** [comment]
I found the gloo issue https://github.com/facebookincubator/gloo/issues/54 and created issue https://github.com/NVIDIA/nccl/issues/388

In the meanwhile, it would be good to have PyTorch highlight this behavior very clearly in docs (including some references on this ephemenal port range and where it is set up). A user may think that the opening MASTER_PORT on the server is enough for everything to work (since this port is mentioned in every tutorial), but that's not  the case.

**Comment by initzhang** [comment]
Stuck on this problem too.
I don't have the super user privilege to change the system-wide ephemeral port range(there are many other services like NFS running on the machine, such change is dangerous also).

I am wondering it is possible to : 1. clone the source code of PyTorch 2. modify the [gloo code here](https://github.com/facebookincubator/gloo/blob/9c1876a9000c9585c9406941770950404128bbe2/gloo/transport/tcp/pair.cc#L173) by manually set the `attr.ai_addr.sin_port` to my desired port for client back-connection 3. rebuild the pytorch from scratch?

I know this is really a bad idea, any suggestions or better solutions?

**Comment by jcowles** [comment]
What's the correct workaround for this, assuming the firewall is locking down most ports?

**Comment by ifahim** [comment]
@jcowles Did you find a workaround for this? with limited set of ports?

**Comment by seonglae** [comment]
This is still an issue for multi-node with limited port number

**Comment by SebastianScherer88** [comment]
bump. i encounter this whenever i use anything other than `static` in the rendezvous backend argument. im setting up a distributed pytorch kubernetes cluster, and a workaround here is to
1. use `static` as the backend argument
2. this leads to the TCP store being created on node 0
3. create a service that points to node 0
4. use that service's url/dns as the rendezvous endpoint arg

i've tried using the etcd setup with a dedicated etcd k8s pod and k8s service point to it, but the torch distributed processes with `etcd` backend keep trying to access a random port on node 0 as described in this thread. very odd imo
