### ISSUE TITLE
test_autograd test fails with ROCm

### ISSUE THREAD

**Issue by apalazzi** [pytorch/pytorch#44546]
## 🐛 Bug

When using pytorch+ROCm the test suite fails on the following tests:

* test_profiler_custom_op (__main__.TestAutograd)
* test_profiler_emit_nvtx_cuda (__main__.TestAutogradDeviceTypeCUDA)
* test_ctc_loss_cudnn_cuda (__main__.TestAutogradDeviceTypeCUDA)

I have the same exact behaviour either when using the docker and when building pytorch from sources.

## To Reproduce

1. Install pytorch, either with the docker ( sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 8G rocm/pytorch:latest) or by compiling the sources
2. start the test suite: USE_ROCM=1 python3 test/run_test.py --verbose

```======================================================================
ERROR: test_profiler_custom_op (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 387, in wrapper
    fn(*args, **kwargs)
  File "test_autograd.py", line 2834, in test_profiler_custom_op
    inst = torch.classes._TorchScriptTesting._PickleTester([3, 4])
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/_classes.py", line 10, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '_TorchScriptTesting._PickleTester', but it does not exist! Ensure that it is registered via torch::class_

======================================================================
ERROR: test_profiler_emit_nvtx_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/cuda/profiler.py", line 45, in profile
    start()
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/cuda/profiler.py", line 35, in start
    check_error(cudart().cudaProfilerStart())
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 208, in check_error
    raise CudaError(res)
torch.cuda.CudaError: hipErrorNotSupported (cudaError.???)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 815, in wrapper
    method(*args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 815, in wrapper
    method(*args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 257, in instantiated_test
    result = test(self, *args)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 479, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 586, in only_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 6305, in test_profiler_emit_nvtx
    with torch.cuda.profiler.profile():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/cuda/profiler.py", line 48, in profile
    stop()
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/cuda/profiler.py", line 39, in stop
    check_error(cudart().cudaProfilerStop())
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 208, in check_error
    raise CudaError(res)
torch.cuda.CudaError: hipErrorNotSupported (cudaError.???)

======================================================================
FAIL: test_ctc_loss_cudnn_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 815, in wrapper
    method(*args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 815, in wrapper
    method(*args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 257, in instantiated_test
    result = test(self, *args)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 586, in only_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 479, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 799, in wrap_fn
    return fn(self, device, *args, **kwargs)
  File "test_autograd.py", line 6249, in test_ctc_loss_cudnn
    self.assertTrue("Cudnn" in str(loss_cudnn.grad_fn))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2411 tests in 578.609s

FAILED (failures=1, errors=2, skipped=164, expected failures=1)
Traceback (most recent call last):
  File "test/run_test.py", line 721, in <module>
    main()
  File "test/run_test.py", line 710, in main
    raise RuntimeError(err)
RuntimeError: test_autograd failed!
```

## Expected behavior

All the tests should complete successfully.

## Environment

PyTorch version: 1.7.0a0+f02753f
Is debug build: False
CUDA used to build PyTorch: Could not collect

OS: Pop!_OS 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0a0+f02753f
[conda] Could not collect

NOTE: when building from sources, I checked out the 1.6 branch.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @jeffdaily @sunway513 @mruberry @VitalyFedyunin

**Comment by albanD** [comment]
Hi,

I think this is fixed in master no?
The first test has been moved to the proper files for torchbind and the two cuda tests are now properly protected with `@skipCUDAIfRocm`.
Can you confirm it is all good now?

**Comment by jeffdaily** [comment]
Test suite should be run with `PYTORCH_TEST_WITH_ROCM=1` to activate the `@skipIfRocm` and `@skipCUDAIfRcom` decorators.

**Comment by jeffdaily** [comment]
Closing.  Reproducer step (2) had `USE_ROCM=1`, but it should have been `PYTORCH_TEST_WITH_ROCM=1`.
