### ISSUE TITLE
PyTorch 1.6 DataParallel causes CUDNN_STATUS_BAD_PARAM in backward pass

### ISSUE THREAD

**Issue by xdever** [pytorch/pytorch#44551]
## 🐛 Bug

On a machine having 2 different GPUs DataParallel causes a crash in the C++ backed with RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM error message. With disabled CUDNN it works fine. 

The crash is stochastic and the probability depends on the used model. Simpler convnets works fine. The probability is related to the number of batchnorms used in the model, however, I was unable to figure out how exactly (it is not monotonic). An easy way to test this is to start with a convnet without batchnorm, and start stacking batchnoms at an arbitrary position in the network. It will start crashing with a certain probability. After enough batchnorms it crashes with P=1.

## To Reproduce

Running the following script

```python
import torch
from torchvision.models import resnet101

rnn = resnet101(num_classes=10).cuda()
par = torch.nn.DataParallel(rnn)

inp = torch.randn(100, 3, 32, 32).cuda()

par(inp).sum().backward()
```
Causes the following crash:

```
/home/robert/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:26: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
Traceback (most recent call last):
  File "crash.py", line 9, in <module>
    par(inp).sum().backward()
  File "/home/robert/.local/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/robert/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
Exception raised from operator() at /pytorch/aten/src/ATen/native/cudnn/Conv.cpp:1141 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f3d36ba51e2 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xebb822 (0x7f3d37ec9822 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xebd985 (0x7f3d37ecb985 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xebe24e (0x7f3d37ecc24e in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xebe910 (0x7f3d37ecc910 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::cudnn_convolution_backward_weight(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x49 (0x7f3d37eccb69 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xf1f53b (0x7f3d37f2d53b in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xf4f178 (0x7f3d37f5d178 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: at::cudnn_convolution_backward_weight(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x1ad (0x7f3d72e052ad in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::native::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x18a (0x7f3d37ec678a in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0xf1f445 (0x7f3d37f2d445 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0xf4f1d4 (0x7f3d37f5d1d4 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #12: at::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x1e2 (0x7f3d72e14242 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x2ec9c62 (0x7f3d74ad7c62 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x2ede224 (0x7f3d74aec224 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: at::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x1e2 (0x7f3d72e14242 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::generated::CudnnConvolutionBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x258 (0x7f3d7495ec38 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x3375bb7 (0x7f3d74f83bb7 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1400 (0x7f3d74f7f400 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x7f3d74f7ffa1 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #20: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x89 (0x7f3d74f78119 in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #21: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x4a (0x7f3d8271386a in /home/robert/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #22: <unknown function> + 0xcfb74 (0x7f3d8365cb74 in /usr/lib/libstdc++.so.6)
frame #23: <unknown function> + 0x9422 (0x7f3d84903422 in /usr/lib/libpthread.so.0)
frame #24: clone + 0x43 (0x7f3d84a1bbf3 in /usr/lib/libc.so.6)
```

## Expected behavior

Don't crash. If for some reason CUDNN requires to have identical GPUs if running in parallel, then display a runtime error that is easier to interpret than this. I assumed the error is in my code and lost a few hours debugging it.

## Environment

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.1.0
Clang version: Could not collect
CMake version: version 3.17.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 440.82
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.7.0
[conda] Could not collect

## Additional context

I tried reproducing the error on other machines having identical GPUs and I failed. That is not the only difference nor in hardware nor in the software environment, so it is hard to compare.

**Comment by VitalyFedyunin** [comment]
To be honest you are using two non well supported features of pytorch DataParallel (Distributed DataParallel is the preferred way) and hardware setup with two different GPUs.

**Comment by blakeliu** [comment]
@RobertCsordas   I meet the same bug!  [https://github.com/ultralytics/yolov5/issues/1469#issuecomment-757408613](url)
### I use tiny-imagenet 200 dataset train with [https://github.com/pytorch/examples/blob/master/imagenet/main.py](url), the same with outputs
```
python main.py /home/blake/data/cv/tiny-imagenet-200/data -a resnet18
=> creating model 'resnet18'
/home/blake/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py:30: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
Epoch: [0][  0/391]	Time  4.114 ( 4.114)	Data  0.710 ( 0.710)	Loss 7.0178e+00 (7.0178e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.00 (  0.00)
Epoch: [0][ 10/391]	Time  0.325 ( 0.655)	Data  0.000 ( 0.066)	Loss 5.4858e+00 (6.1251e+00)	Acc@1   0.39 (  0.60)	Acc@5   3.52 (  3.05)
Epoch: [0][ 20/391]	Time  0.324 ( 0.499)	Data  0.000 ( 0.044)	Loss 5.3769e+00 (5.8164e+00)	Acc@1   1.56 (  1.00)	Acc@5   7.03 (  4.45)
....
....
....
Epoch: [0][370/391]	Time  0.321 ( 0.350)	Data  0.000 ( 0.022)	Loss 4.4054e+00 (4.8019e+00)	Acc@1   8.20 (  5.25)	Acc@5  26.56 ( 16.66)
Epoch: [0][380/391]	Time  0.338 ( 0.349)	Data  0.000 ( 0.022)	Loss 4.2434e+00 (4.7897e+00)	Acc@1  12.89 (  5.36)	Acc@5  26.95 ( 16.92)
Traceback (most recent call last):
  File "/home/blake/cv/torch/examples/imagenet/main.py", line 429, in <module>
    main()
  File "/home/blake/cv/torch/examples/imagenet/main.py", line 112, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/home/blake/cv/torch/examples/imagenet/main.py", line 245, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/blake/cv/torch/examples/imagenet/main.py", line 301, in train
    loss.backward()
  File "/home/blake/anaconda3/envs/torch/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/blake/anaconda3/envs/torch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```

### My software environment
```
OS: Ubuntu 18.04.5 LTS

Driver Version: 460.32.03

(torch) blake@workstation:~/cv/yolo/yolov5$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

(torch) blake@workstation:~/cv/yolo/yolov5$ conda list python
# packages in environment at /home/blake/anaconda3/envs/torch:
python                    3.7.9                h7579374_0    defaults
python-dateutil           2.8.1                    pypi_0    pypi


(torch) blake@workstation:~/cv/yolo/yolov5$ conda list torch
torch                     1.7.1+cu110              pypi_0    pypi
torchaudio                0.7.2                    pypi_0    pypi
torchvision               0.8.2+cu110              pypi_0    pypi

(torch) blake@workstation:~/cv/yolo/yolov5$ nvidia-smi 
Sun Jan 10 11:35:12 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   37C    P8    13W / 180W |    523MiB /  8118MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2070    Off  | 00000000:02:00.0 Off |                  N/A |
| 34%   14C    P8    17W / 175W |     10MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by rubencart** [comment]
Same here. No error when running on 1 single GPU or on CPU. When running on 2 GPUs, 1 Titan Xp and 1 Titan RTX, I get the following.
Error:
```
Traceback (most recent call last):
  File "/cw/liir/NoCsBack/testliir/rubenc/.pycharm_helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/cw/liir/NoCsBack/testliir/rubenc/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/cw/liir/NoCsBack/testliir/rubenc/SOA-OP-GAN/OP-GAN/code/reproduce2.py", line 63, in <module>
    out = net(data)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2, 100, 16, 16], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(100, 50, kernel_size=[3, 3], padding=[1, 1], stride=[2, 2], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [2, 2, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f45aed0d910
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 100, 16, 16, 
    strideA = 25600, 256, 16, 1, 
output: TensorDescriptor 0x7f45aed0ad50
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 50, 8, 8, 
    strideA = 3200, 64, 8, 1, 
weight: FilterDescriptor 0x7f45b721e230
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 50, 100, 3, 3, 
Pointer addresses: 
    input: 0x7f45fa600000
    output: 0x7f45fa669a00
    weight: 0x7f45fa632000
Forward algorithm: 1
python-BaseException
```
The suggested code does not reproduce it, but this does:
```python
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([4, 100, 16, 16], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Sequential(
    torch.nn.Conv2d(100, 50, kernel_size=[3, 3], padding=[1, 1], stride=[2, 2], dilation=[1, 1], groups=1),
    torch.nn.BatchNorm2d(50),
    torch.nn.Conv2d(50, 25, kernel_size=[3, 3], padding=[1, 1], stride=[2, 2], dilation=[1, 1], groups=1),
    torch.nn.BatchNorm2d(25),
)
net = torch.nn.parallel.DataParallel(net)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
```
Python 3.8.5, pytorch 1.7.1 (build py3.8_cuda11.0.221_cudnn8.0.5_0), CUDA version 11.2. Let me know if you want more info.

**Comment by pearceja** [comment]
I get the same with RTX 3070 and RTX 2070

**Comment by xwang233** [comment]
For cudnn convolutions on multiple different GPUs, the cache of cudnn convolution algorithms might be related. See https://github.com/pytorch/pytorch/issues/50844. 

cc @zasdfgbnm @ngimel

**Comment by drkkgy** [comment]
I am getting the same error with RTX 3060 and GTX1080Ti

**Comment by ptrblck** [comment]
@drkkgy could you provide a minimal, executable code snippet to reproduce this issue, please?

**Comment by drkkgy** [comment]
Hi, @ptrblck I was running the same notebook(2 separate copies) with different GPU Ids (0,1)  to use both of my GPUs to train the same model at the same time but separately with different hyperparameters.  

Minimal execution looked something like this just switch the device Id in two copies of the notebook!!

# importing required libraries
import numpy as np
import os

import torch 
print("Pytorch library version =", torch.__version__)
import torchvision
import torchvision.transforms as transforms
import torchvision.datasets as data

## Libraries to build CNN Model
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim


#DATA



## Defining the transfroms in pytorch to apply on the dataset for pre-processing.

data_transform = transforms.Compose(
                                [transforms.ToTensor(),
                                 transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])

# Declaring the batch size to be used for batching the dataset.
batch_size = 4

trainset = data.CIFAR10(root='./data',train=True,download=True,transform=data_transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,shuffle=True, num_workers=2)

testset = data.CIFAR10(root='./data',train=False,transform=data_transform)

testloader = torch.utils.data.DataLoader(testset,batch_size=batch_size,shuffle=True,num_workers=2)

data_class_label = ('plane', 'car', 'bird', 'cat','deer', 'dog', 'frog', 'horse', 'ship', 'truck')


# Training the CNN 
def Train(use_gpu,device_id,cnn_model,model_criterion,model_optimizer,
                          model_name ='test1',loss_freq=2000,
                          epochs=2):
    
    Basic_CNN = cnn_model
    if use_gpu:
        Basic_CNN.cuda(device_id)    
    criterion = model_criterion
    CNN_optimzer = model_optimizer
    model_name = model_name
    loss_freq = loss_freq
    Epochs = epochs
        
        
    for epochs in range(Epochs):
        
        current_loss = 0.0
        
        for i , data in enumerate(trainloader,0):
                
            
            train_img,labels = data
            if(use_gpu):
                train_img,labels = train_img.cuda(device_id),labels.cuda(device_id)

            CNN_optimzer.zero_grad()# Ensuring no redual gradients is left by making it zero.

            # Forward propagation

            out = Basic_CNN(train_img)


            loss = criterion(out,labels)

            # Backward propagation

            loss.backward() 

            # Updating weights of the CNNs various layers

            CNN_optimzer.step()

            # Output loss status

            current_loss += loss.item()

            if i % loss_freq == (loss_freq-1):      # prinitng the loss every 2000 steps
                print('Epcoh = %d/%d Trained Data Count = %5d  loss: %.3f '%(epochs + 1,Epochs,i+1,current_loss/loss_freq))
                current_loss
                current_loss = 0.0

    # Testing model performance
    correct_pred = 0
    total_preds = 0

    with torch.no_grad(): 
        for data in testloader:
            test_images ,label = data
            if use_gpu:
                test_images ,label = test_images.cuda(device_id) ,label.cuda(device_id)        

            output = Basic_CNN(test_images)
            
            
            _,predictions = torch.max(output.data,1) # Selecting the class with maximum score
            total_preds += label.size(0)
            correct_pred += (predictions == label).sum().item()

    print( 'Accuracy of the model on 10000 test images : %d %%' % (100*(correct_pred/total_preds) ))

    
    
## Normal Model
class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.convlayer1 = nn.Conv2d(3, 6, 5)
        self.Maxpool = nn.MaxPool2d(2,2)
        self.convlayer2 = nn.Conv2d(6,32,5)
        self.fullconnlayer1 = nn.Linear(32*5*5,120)
        self.fullconnlayer2 = nn.Linear(120,88)
        self.fullconnlayer3 = nn.Linear(88,10)  
        
    def forward(self,z):
        z = self.Maxpool(F.relu(self.convlayer1(z)))
        z = self.Maxpool(F.relu(self.convlayer2(z)))
        z = torch.flatten(z,1) # Flattening all dimesnions except  batch to feed to a Deep network
        z = F.relu(self.fullconnlayer1(z))
        z = F.relu(self.fullconnlayer2(z))
        z = self.fullconnlayer3(z)
        
        return z
CNN_model = CNN()
criterion = nn.CrossEntropyLoss()
CNN_optimzer = optim.SGD(improved_CNN.parameters(),lr = learning_rate, momentum=momentum)


Train(use_gpu=True,device_id=0,cnn_model = CNN_model,
                      model_criterion = criterion,
                      model_optimizer = CNN_optimzer,
                      epochs=Epochs)

**Comment by drkkgy** [comment]
Hi, @ptrblck I was running the same notebook(2 separate copies) with different GPU Ids (0,1)  to use both of my GPUs to train the same model at the same time but separately with different hyperparameters.  

Minimal execution looked something like this just switch the device Id in two copies of the notebook!!

`
import numpy as np
import os

import torch 
print("Pytorch library version =", torch.__version__)
import torchvision
import torchvision.transforms as transforms
import torchvision.datasets as data


import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim


data_transform = transforms.Compose(
                                [transforms.ToTensor(),
                                 transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])


batch_size = 4

trainset = data.CIFAR10(root='./data',train=True,download=True,transform=data_transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,shuffle=True, num_workers=2)

testset = data.CIFAR10(root='./data',train=False,transform=data_transform)

testloader = torch.utils.data.DataLoader(testset,batch_size=batch_size,shuffle=True,num_workers=2)

data_class_label = ('plane', 'car', 'bird', 'cat','deer', 'dog', 'frog', 'horse', 'ship', 'truck')

def Train(use_gpu,device_id,cnn_model,model_criterion,model_optimizer,
                          model_name ='test1',loss_freq=2000,
                          epochs=2):
    
    Basic_CNN = cnn_model
    if use_gpu:
        Basic_CNN.cuda(device_id)    
    criterion = model_criterion
    CNN_optimzer = model_optimizer
    model_name = model_name
    loss_freq = loss_freq
    Epochs = epochs
        
        
    for epochs in range(Epochs):
        
        current_loss = 0.0
        
        for i , data in enumerate(trainloader,0):
                
            
            train_img,labels = data
            if(use_gpu):
                train_img,labels = train_img.cuda(device_id),labels.cuda(device_id)

            CNN_optimzer.zero_grad()
           
            out = Basic_CNN(train_img)


            loss = criterion(out,labels)

            
            loss.backward() 

            

            CNN_optimzer.step()

           

            current_loss += loss.item()

            if i % loss_freq == (loss_freq-1):     
                print('Epcoh = %d/%d Trained Data Count = %5d  loss: %.3f '%(epochs + 1,Epochs,i+1,current_loss/loss_freq))
                current_loss
                current_loss = 0.0


    correct_pred = 0
    total_preds = 0

    with torch.no_grad(): 
        for data in testloader:
            test_images ,label = data
            if use_gpu:
                test_images ,label = test_images.cuda(device_id) ,label.cuda(device_id)        

            output = Basic_CNN(test_images)
            
            
            _,predictions = torch.max(output.data,1) # Selecting the class with maximum score
            total_preds += label.size(0)
            correct_pred += (predictions == label).sum().item()

    print( 'Accuracy of the model on 10000 test images : %d %%' % (100*(correct_pred/total_preds) ))

    
    
class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.convlayer1 = nn.Conv2d(3, 6, 5)
        self.Maxpool = nn.MaxPool2d(2,2)
        self.convlayer2 = nn.Conv2d(6,32,5)
        self.fullconnlayer1 = nn.Linear(32*5*5,120)
        self.fullconnlayer2 = nn.Linear(120,88)
        self.fullconnlayer3 = nn.Linear(88,10)  
        
    def forward(self,z):
        z = self.Maxpool(F.relu(self.convlayer1(z)))
        z = self.Maxpool(F.relu(self.convlayer2(z)))
        z = torch.flatten(z,1) # Flattening all dimesnions except  batch to feed to a Deep network
        z = F.relu(self.fullconnlayer1(z))
        z = F.relu(self.fullconnlayer2(z))
        z = self.fullconnlayer3(z)
        
        return z
CNN_model = CNN()
criterion = nn.CrossEntropyLoss()
CNN_optimzer = optim.SGD(improved_CNN.parameters(),lr = learning_rate, momentum=momentum)


Train(use_gpu=True,device_id=0,cnn_model = CNN_model,
                      model_criterion = criterion,
                      model_optimizer = CNN_optimzer,
                      epochs=Epochs)
    
`

**Comment by puririshi98** [comment]
The original poster finds the issue when trying data parallel with two mismatched gpus on an old version of PyTorch. I found that I can replicate the issue simply by using one gpu after the other in a for loop. This issue is not reproducible in recent containers like master-py3-devel but it is present in much older containers like 21.02-py3-devel.
```
import torch
from torchvision.models import *
for i in range(2):
    with torch.backends.cudnn.flags(enabled=?):
        rnn = resnet101(num_classes=10).cuda(i)
        par=rnn
        print("starting loop for device:",i)
        for j in range(2,10):
            inp = torch.randn(j, 3, 32, 32).cuda(i)
            o=par(inp)
            o.sum().backward()
            par.zero_grad()
            print('completed batchsize=',j)
            torch.cuda.synchronize()
```
1.if i set the cudnn enabled flag to True the error occurs.
2.if i set the cudnn enabled flag to False the error does not occur.
3.if i set the cudnn enabled flag to be bool(i) such that it is false for the first gpu and then true for the second, there is no error.
4.if i set the cudnn enabled flag to be not bool(i) there is no error.
The error only occurs when cudnn is enabled for both gpus, whether they are used in data parallel  as the original poster has done or sequentially in a for loop over cuda devices as I have done above. This leads me to believe that the issue is that cudnn selects some optimal kernels for one gpu and then tries to reuse these for the second and gets an issue. The solution is a per device CudNN cache, which has already been implemented in recent versions of torch.


Line: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cudnn/ConvShared.h#L20


Commit: https://github.com/pytorch/pytorch/pull/50892
 
This commit exists in PyTorch 1.9
As such, it would be good to check if updating to PyTorch 1.9 would solve this issue.

**Comment by the-drunk-coder** [comment]
Hi,

I'm on Pytorch 1.11, and I'm getting the same error without using DataParallel at all, on a vGPU.

It works on the CPU. 

Not sure if it's related.

**Comment by tokisakikaguya** [comment]
> I am getting the same error with RTX 3060 and GTX1080Ti Pytorch version 1.8.2
Hello, have you solved this problem?
