### ISSUE TITLE
conv_forward: TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not list

### ISSUE THREAD

**Issue by Tagar** [pytorch/pytorch#44628]
## To Reproduce

$ conda install -c fastai -c pytorch fastai fastbook powerai::"sentencepiece<0.1.90" 

```
import fastbook
fastbook.setup_book()
from fastbook import *

from fastai.vision.all import *
path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = cnn_learner(dls, resnet34, metrics=error_rate)

learn.fine_tune(1)
```

produces:
```
Traceback (most recent call last):
  File "<command-8165228>", line 4, in <module>
    learn.fine_tune(1)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastcore/utils.py", line 473, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/callback/schedule.py", line 161, in fine_tune
    self.fit_one_cycle(freeze_epochs, slice(base_lr), pct_start=0.99, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastcore/utils.py", line 473, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/callback/schedule.py", line 113, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastcore/utils.py", line 473, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 207, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 197, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 191, in _do_epoch
    self._do_epoch_train()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 183, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 161, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 179, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/fastai/learner.py", line 164, in _do_one_batch
    self.pred = self.model(*self.xb)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-57c25c54-7ac2-440e-8bda-2d19b805411d/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not list
```

additional debugging showed following local variables inside of `_conv_forward` when it failed:

```
{'self': Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), 
            padding=(3, 3), bias=False), 
'input': [0], 
'weight': Parameter containing:
tensor([[[[ 5.4109e-03, -6.9092e-03,  7.8839e-03,  ...,  4.9072e-02,  3.0660e-02,  2.5398e-02],
          [ 4.1081e-02,  3.1296e-02,  3.2265e-02,  ...,  3.3145e-02,  2.9754e-02,  4.1735e-02],
          [ 4.9519e-03, -3.1705e-02, -6.1310e-02,  ..., -9.7493e-02, -1.1601e-01, -1.2191e-01],
          ...,

```

## Expected behavior

No errors expected.

## Environment

 - PyTorch Version (e.g., 1.0): **1.6.0**

List of some of the conda/pip packages - 

```
...
fastai                    2.0.10                     py_0    fastai
fastbook                  0.0.11             pyh39e3cac_0    fastai
fastcore                  1.0.9                      py_0    fastai
fastprogress              1.0.0              pyh39e3cac_0    fastai
fastscript                1.0.0                         0    fastai
nbdev                     1.0.18                     py_0    fastai
...
pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
torchvision               0.7.0                py37_cu101    pytorch
...
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-base           2.2.0           mkl_py37hd506778_0  
tensorflow-estimator      2.3.0                    pypi_0    pypi
...
```

 - OS (e.g., Linux): Ubuntu 18.04.5 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda, see above 
 - Build command you used (if compiling from source): didn't build manually
 - Python version: 3.7.6
 - CUDA/cuDNN version: CUDA 10.1 Update 2, cuDNN 7.6.5, NCCL 2.7.3, TensorRT 6.0.1
 - GPU models and configuration: ec2 instance g4dn.4xlarge
 - Any other relevant information: Databricks ML Runtime 7.3

**Comment by mariosasko** [comment]
Hi,

it seems that you are passing `list` instead of `torch.Tensor` to the conv layer. In that case, you can call `torch.tensor(input)` and optionally set the `dtype` to `torch.float` if the inputs are integers to fix the issue.

**Comment by albanD** [comment]
Hi,

This does not seem related to core pytorch but more a bad use of a library.
We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by Tagar** [comment]
@mariosasko @albanD thank you for looking at this issue

conv2d is called internally by `fastai` library. It might be an issue in fast ai then.

Notice that when `_conv_forward` fails, it has weights as a Tensor already, and only `input` is a  list of one single value 0, literally `[0]` as seen in the debug dump above. 

Last 7 calls in the exception stack were from pytorch internal functions so I thought the issue might be here
```
  File "../torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "../torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "../torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "../torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not list
```

but I understand that `input` must have come as `[0]` (single-element list of zero) from fastai directly somehow. I was trying to follow the logic in both of these libraries, but couldn't completely follow how `input` was going through all of these functions. 

Thanks again I will open an issue in fastai .
