### ISSUE TITLE
[JIT] RuntimeError:  ill formed octal specifier for List[str]

### ISSUE THREAD

**Issue by lamhoangtung** [pytorch/pytorch#44708]
## 🐛 Bug

I'm trying to export a Pytorch model using TorchScript and use the exported model to run on a production env.
The conversion is fine and I can export a `.pt` TorchScript model but unable to load them in. The problem seems to be cause by a weird list of string that I have in the original python code.

## To Reproduce

Run this:

```python
import torch
from typing import List

class Model(torch.jit.ScriptModule):
    def __init__(self):
        super(Model, self).__init__()

    @torch.jit.script_method
    def process(self, x: int) -> str:
        vocab: List[str] = ['<unk>', '<blank>', '<s>', '</s>', '\\;', 'n', 'h', 'N', 'i', 'H', 'g', 'T', 't', 'c', 'C', 'a', 'u', 'G', '0', '1', 'm', 'o', 'I', ',', 'r', '2', 'á', 'Đ', 'à', 'A', 'y', 'e', 'p', ':', 'M', 'V', '9', '.', 's', 'S', 'D', 'K', 'ư', 'P', 'l', 'd', 'R', '3', '8', 'L', 'U', '5', '-', 'ê', 'B', '7', '4', '6', 'đ', 'ô', '/', 'ạ', 'ộ', 'Y', 'Q', 'ă', 'â', 'ố', 'À', 'ơ', 'v', 'O', 'Á', 'X', 'ậ', 'ú', 'Ư', 'Ộ', 'Â', 'ờ', 'ệ', 'ả', 'ị', 'k', 'b', 'ớ', 'Ấ', 'Ố', 'ọ', 'ế', 'ồ', 'Ệ', 'q', 'í', 'E', 'Ó', 'Ê', 'Ế', 'Ả', 'ấ', 'Ị', 'ì', 'ự', 'ầ', 'Ô', 'Ủ', 'ắ', 'ó', 'ã', 'Ỏ', 'Ã', 'Ì', 'ẹ', 'ỉ', 'Ứ', 'ò', 'Ò', 'Ĩ', 'Ạ', 'f', 'ể', 'Ụ', 'ợ', 'ề', 'Ă', 'ủ', 'Ơ', 'w', '<', 'Ớ', 'Ề', 'ứ', ')', 'x', 'ĩ', 'ũ',
                    '(', 'ụ', 'Ễ', 'ặ', 'é', 'Ỵ', 'Ờ', 'Ở', 'Ầ', 'Ú', 'ễ', 'ổ', 'Ậ', 'Í', 'ữ', '"', 'ù', 'F', 'ỹ', 'ẳ', 'ở', 'Ợ', 'Ự', 'Ể', 'Ồ', 'ỳ', 'Ọ', 'ý', 'ừ', 'Ữ', 'Ổ', 'Ù', 'ử', 'Ắ', 'Ý', 'W', 'z', 'ằ', 'Ỉ', '%', 'ẩ', 'Ũ', 'õ', 'J', 'Ặ', ';', 'ẻ', 'Ừ', '–', 'j', 'Ử', 'ỷ', "'", 'ỏ', 'ẽ', '+', '@', 'Ỗ', 'Ẩ', 'Ỳ', 'ỗ', 'É', 'Z', 'Ằ', 'Ỹ', '#', 'Ẫ', 'ẫ', 'Õ', 'ẵ', '&', 'Ẽ', 'è', 'Ẻ', 'Ẹ', 'ỡ', 'Ỷ', 'Ỡ', '_', '=', '>', 'È', 'Ẳ', '�', 'Ð', ']', '[', '?', 'ỵ', 'Ẵ', '\x08', '*', '’', '|', '!', '≤', '“', '$', '”', '\uf0b7', '̣', '—', '•', 'ﬁ', '́', '\uf0a7', 'ç', 'Ö', 'ƣ', '…', '{', '~', 'Ä', 'Ï', 'ﬂ', '̀', '̃', '❹', 'Ñ', '≥', 'Å', 'Ø', '−', '❶', '°', 'Ş', 'Ť', '▬', '}', 'Ć', '̉', '❷', 'ø', 'Ą', '‐', '→', '■', '\uf076', '\uf0bd', '\x08Đ', '\x7f', '\x9b', '\x9f', '©', '±', 'Û', 'ö', 'Š', 'ɂ', 'ˆ', '\uf0fc', '\x08S', '\x08V', '\x08t', '\\', 'rỘị', '\x82', '\x93', '\xad', '×', 'ñ', 'Ż', '‘', '€', '●', '❸', '년', '\ue035', '\ue067', '\uf071', '\uf0d8', 'ﬃ']
        return vocab[x]

model = Model()
scripted_model = torch.jit.script(model)
scripted_model.save('scripted_model_test_bug.pt')


loaded_model = torch.jit.load('scripted_model_test_bug.pt')
res = loaded_model.process(5)
print(res)
```

And here is the bug:
```console
Traceback (most recent call last):
  File "ill.py", line 19, in <module>
    loaded_model = torch.jit.load('scripted_model_test_bug.pt')
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 275, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: 
 ill formed octal specifier:
  File "ill.py", line 10
    @torch.jit.script_method
    def process(self, x: int) -> str:
        vocab: List[str] = ['<unk>', '<blank>', '<s>', '</s>', '\\;', 'n', 'h', 'N', 'i', 'H', 'g', 'T', 't', 'c', 'C', 'a', 'u', 'G', '0', '1', 'm', 'o', 'I', ',', 'r', '2', 'á', 'Đ', 'à', 'A', 'y', 'e', 'p', ':', 'M', 'V', '9', '.', 's', 'S', 'D', 'K', 'ư', 'P', 'l', 'd', 'R', '3', '8', 'L', 'U', '5', '-', 'ê', 'B', '7', '4', '6', 'đ', 'ô', '/', 'ạ', 'ộ', 'Y', 'Q', 'ă', 'â', 'ố', 'À', 'ơ', 'v', 'O', 'Á', 'X', 'ậ', 'ú', 'Ư', 'Ộ', 'Â', 'ờ', 'ệ', 'ả', 'ị', 'k', 'b', 'ớ', 'Ấ', 'Ố', 'ọ', 'ế', 'ồ', 'Ệ', 'q', 'í', 'E', 'Ó', 'Ê', 'Ế', 'Ả', 'ấ', 'Ị', 'ì', 'ự', 'ầ', 'Ô', 'Ủ', 'ắ', 'ó', 'ã', 'Ỏ', 'Ã', 'Ì', 'ẹ', 'ỉ', 'Ứ', 'ò', 'Ò', 'Ĩ', 'Ạ', 'f', 'ể', 'Ụ', 'ợ', 'ề', 'Ă', 'ủ', 'Ơ', 'w', '<', 'Ớ', 'Ề', 'ứ', ')', 'x', 'ĩ', 'ũ',
                                                                                                                                                                               ~ <--- HERE
                    '(', 'ụ', 'Ễ', 'ặ', 'é', 'Ỵ', 'Ờ', 'Ở', 'Ầ', 'Ú', 'ễ', 'ổ', 'Ậ', 'Í', 'ữ', '"', 'ù', 'F', 'ỹ', 'ẳ', 'ở', 'Ợ', 'Ự', 'Ể', 'Ồ', 'ỳ', 'Ọ', 'ý', 'ừ', 'Ữ', 'Ổ', 'Ù', 'ử', 'Ắ', 'Ý', 'W', 'z', 'ằ', 'Ỉ', '%', 'ẩ', 'Ũ', 'õ', 'J', 'Ặ', ';', 'ẻ', 'Ừ', '–', 'j', 'Ử', 'ỷ', "'", 'ỏ', 'ẽ', '+', '@', 'Ỗ', 'Ẩ', 'Ỳ', 'ỗ', 'É', 'Z', 'Ằ', 'Ỹ', '#', 'Ẫ', 'ẫ', 'Õ', 'ẵ', '&', 'Ẽ', 'è', 'Ẻ', 'Ẹ', 'ỡ', 'Ỷ', 'Ỡ', '_', '=', '>', 'È', 'Ẳ', '�', 'Ð', ']', '[', '?', 'ỵ', 'Ẵ', '\x08', '*', '’', '|', '!', '≤', '“', '$', '”', '\uf0b7', '̣', '—', '•', 'ﬁ', '́', '\uf0a7', 'ç', 'Ö', 'ƣ', '…', '{', '~', 'Ä', 'Ï', 'ﬂ', '̀', '̃', '❹', 'Ñ', '≥', 'Å', 'Ø', '−', '❶', '°', 'Ş', 'Ť', '▬', '}', 'Ć', '̉', '❷', 'ø', 'Ą', '‐', '→', '■', '\uf076', '\uf0bd', '\x08Đ', '\x7f', '\x9b', '\x9f', '©', '±', 'Û', 'ö', 'Š', 'ɂ', 'ˆ', '\uf0fc', '\x08S', '\x08V', '\x08t', '\\', 'rỘị', '\x82', '\x93', '\xad', '×', 'ñ', 'Ż', '‘', '€', '●', '❸', '년', '\ue035', '\ue067', '\uf071', '\uf0d8', 'ﬃ']
        return vocab[x]
Serialized   File "code/__torch__.py", line 7
  def process(self: __torch__.Model,
    x: int) -> str:
    vocab = ["<unk>", "<blank>", "<s>", "</s>", "\\;", "n", "h", "N", "i", "H", "g", "T", "t", "c", "C", "a", "u", "G", "0", "1", "m", "o", "I", ",", "r", "2", "\0)+\/-)", "\0),\/*0", "\0)+\/,0", "A", "y", "e", "p", ":", "M", "V", "9", ".", "s", "S", "D", "K", "\0).\/.0", "P", "l", "d", "R", "3", "8", "L", "U", "5", "-", "\0)+\/.*", "B", "7", "4", "6", "\0),\/+)", "\0)+\//,", "/", "\0-)\/0*\/-)", "\0-)\/0+\/,)", "Y", "Q", "\0),\/)+", "\0)+\/-*", "\0-)\/0+\/+)", "\0)+\.00", "\0).\/-)", "v", "O", "\0)+\/))", "X", "\0-)\/0*\/.-", "\0)+\/0*", "\0).\/./", "\0-)\/0+\/+0", "\0)+\/)*", "\0-)\/0+\/,-", "\0-)\/0+\/)/", "\0-)\/0*\/-+", "\0-)\/0+\/*+", "k", "b", "\0-)\/0+\/,+", "\0-)\/0*\/-,", "\0-)\/0+\/*0", "\0-)\/0+\/*-", "\0-)\/0*\/0/", "\0-)\/0+\/++", "\0-)\/0+\/).", "q", "\0)+\/.-", "E", "\0)+\/++", "\0)+\/**", "\0-)\/0*\/0.", "\0-)\/0*\/-*", "\0-)\/0*\/--", "\0-)\/0+\/**", "\0)+\/.,", "\0-)\/0+\//)", "\0-)\/0*\/-/", "\0)+\/+,", "\0-)\/0+\/-.", "\0-)\/0*\/./", "\0)+\//+", "\0)+\/-+", "\0-)\/0+\/*.", "\0)+\/)+", "\0)+\/*,", "\0-)\/0*\/0)", "\0-)\/0+\/*)", "\0-)\/0+\/-0", "\0)+\//*", "\0)+\/+*", "\0),\/-0", "\0-)\/0*\/,0", "f", "\0-)\/0+\/)+", "\0-)\/0+\/-,", "\0-)\/0+\/-+", "\0-)\/0+\/))", "\0),\/)*", "\0-)\/0+\/-/", "\0).\/,0", "w", "<", "\0-)\/0+\/,*", "\0-)\/0+\.00", "\0-)\/0+\/.)", ")", "x", "\0),\/.)", "\0)-\/.)", "(", "\0-)\/0+\/--", "\0-)\/0+\/),", "\0-)\/0*\///", "\0)+\/.)", "\0-)\/0+\//,", "\0-)\/0+\/,,", "\0-)\/0+\/,.", "\0-)\/0*\/-.", "\0)+\/,*", "\0-)\/0+\/)-", "\0-)\/0+\/+-", "\0-)\/0*\/.,", "\0)+\/*-", "\0-)\/0+\/./", "\"", "\0)+\/0)", "F", "\0-)\/0+\/0)", "\0-)\/0*\//+", "\0-)\/0+\/,/", "\0-)\/0+\/-*", "\0-)\/0+\/.0", "\0-)\/0+\/)*", "\0-)\/0+\/+*", "\0-)\/0+\//+", "\0-)\/0+\/*,", "\0)+\/0-", "\0-)\/0+\/.+", "\0-)\/0+\/..", "\0-)\/0+\/+,", "\0)+\/,)", "\0-)\/0+\/.-", "\0-)\/0*\/..", "\0)+\/,-", "W", "z", "\0-)\/0*\//)", "\0-)\/0+\/)0", "%", "\0-)\/0*\/.)", "\0)-\/-0", "\0)+\//-", "J", "\0-)\/0*\//.", ";", "\0-)\/0*\/0+", "\0-)\/0+\/.*", "\0-*\.00\/++", "j", "\0-)\/0+\/.,", "\0-)\/0+\///", "\'", "\0-)\/0+\/*/", "\0-)\/0*\/0-", "+", "@", "\0-)\/0+\/+.", "\0-)\/0*\/-0", "\0-)\/0+\//*", "\0-)\/0+\/+/", "\0)+\/*)", "Z", "\0-)\/0*\/.0", "\0-)\/0+\//0", "#", "\0-)\/0*\/.*", "\0-)\/0*\/.+", "\0)+\/+-", "\0-)\/0*\//-", "&", "\0-)\/0*\/0,", "\0)+\/-0", "\0-)\/0*\/0*", "\0-)\/0*\//0", "\0-)\/0+\/-)", "\0-)\/0+\//.", "\0-)\/0+\/,0", "_", "=", ">", "\0)+\/)0", "\0-)\/0*\//*", "\0./\/0/\/0-", "\0)+\/*0", "]", "[", "?", "\0-)\/0+\//-", "\0-)\/0*\//,", "\b", "*", "\0-*\.00\/,)", "|", "!", "\0-*\/*)\/-,", "\0-*\.00\/,,", "$", "\0-*\.00\/,-", "\0./\/)*\///", "\0*,\/-+", "\0-*\.00\/+,", "\0-*\.00\/-*", "\0./\/.,\/))", "\0*,\/))", "\0./\/)*\/-/", "\0)+\/-/", "\0)+\/+.", "\0).\/-+", "\0-*\.00\/-.", "{", "~", "\0)+\/),", "\0)+\/*/", "\0./\/.,\/)*", "\0*,\.00", "\0*,\/)+", "\0-*\/,-\/0)", "\0)+\/+)", "\0-*\/*)\/--", "\0)+\/)-", "\0)+\/+0", "\0-*\/)0\/+*", "\0-*\/,-\//.", "\0)*\/.0", "\0)-\/,.", "\0)-\/-,", "\0-*\/+.\/.,", "}", "\0),\/).", "\0*,\/*)", "\0-*\/,-\///", "\0)+\//0", "\0),\/),", "\0-*\.00\/*0", "\0-*\/).\/+*", "\0-*\/+.\/,0", "\0./\/))\//.", "\0./\/)*\/0-", "\b\0),\/*0", "\177", "\0)*\/,+", "\0)*\/,/", "\0)*\/.)", "\0)*\//)", "\0)+\/,+", "\0)+\//.", "\0)-\/,0", "\0*)\/)*", "\0*+\/).", "\0./\/)+\/0,", "\bS", "\bV", "\bt", "\\", "r\0-)\/0+\/+0\0-)\/0+\/*+", "\0)*\/)*", "\0)*\/++", "\0)*\/.-", "\0)+\/+/", "\0)+\//)", "\0)-\/0+", "\0-*\.00\/+0", "\0-*\/)*\/.,", "\0-*\/+/\/*/", "\0-*\/,-\//0", "\0.+\/)-\/),", "\0..\.00\//-", "\0..\/))\/-/", "\0./\/))\//)", "\0./\/)+\/+0", "\0./\/.,\/)+"]
                                                                                                                                                                ~~~~~~~~~~ <--- HERE
    return vocab[x]
```

## Expected behavior

The above code sample should be able to load the exported model and should produce an output, which in this case is a character `n` (the 5th element of `vocab` list)

## Environment
```console
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 10.14.5 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.17)
CMake version: version 3.15.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.4.3
[pip3] numpy==1.17.2
[pip3] torch==1.3.1
[pip3] torchtext==0.5.0
[pip3] torchvision==0.7.0
[conda] _pytorch_select           0.1                       cpu_0  
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] msgpack-numpy             0.4.4.3                  pypi_0    pypi
[conda] numpy                     1.17.2           py37h99e6662_0  
[conda] numpy-base                1.17.2           py37h6575580_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] tensorflow                1.15.0          mkl_py37hb249377_0  
[conda] tensorflow-base           1.15.0          mkl_py37h032239d_0  
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
```

## Additional context

I had also tried to load the exported model in pytorch C++ and having the same problem.

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
I was able to reproduce this error in 1.6 but not in 1.7. Can you try 1.7? You can either build from source or use the nightly builds from pytorch.org.

**Comment by lamhoangtung** [comment]
@SplitInfinity Sure I will try 1.7 soon

**Comment by lamhoangtung** [comment]
Thanks for the help @SplitInfinity. I can confirm that 1.7 solved the problem :D
