### ISSUE TITLE
DISABLED test_future_passed_between_python_and_jit (__main__.ProcessGroupJitRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#44734]
https://app.circleci.com/pipelines/github/pytorch/pytorch/214167/workflows/f701b331-f6de-4bd9-b5df-ab014f654485/jobs/7480330/steps

```
Sep 15 09:32:47 ======================================================================
Sep 15 09:32:47 ERROR [0.930s]: test_future_passed_between_python_and_jit (__main__.ProcessGroupJitRpcTestWithSpawn)
Sep 15 09:32:47 ----------------------------------------------------------------------
Sep 15 09:32:47 Traceback (most recent call last):
Sep 15 09:32:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 244, in wrapper
Sep 15 09:32:47     self._join_processes(fn)
Sep 15 09:32:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 361, in _join_processes
Sep 15 09:32:47     self._check_return_codes(elapsed_time)
Sep 15 09:32:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 397, in _check_return_codes
Sep 15 09:32:47     raise RuntimeError(error)
Sep 15 09:32:47 RuntimeError: Processes 3 exited with error code 10
```

```
Sep 15 09:28:59   test_future_passed_between_python_and_jit (__main__.ProcessGroupJitRpcTestWithSpawn) ... [E request_callback_no_python.cpp:618] Received error while processing request type 0: attempted to get undefined function two_args_two_kwargs
Sep 15 09:28:59 Exception raised from get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:71 (most recent call first):
Sep 15 09:28:59 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f874517768b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Sep 15 09:28:59 frame #1: <unknown function> + 0x7ac264 (0x7f875b5ff264 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Sep 15 09:28:59 frame #2: torch::distributed::rpc::RequestCallbackImpl::processScriptCall(torch::distributed::rpc::ScriptCall&, std::function<void (torch::distributed::rpc::Message)> const&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, long, std::shared_ptr<torch::utils::Future<torch::distributed::rpc::Message> > const&) const + 0xaf (0x7f875bbcf74f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Sep 15 09:28:59 frame #3: torch::distributed::rpc::RequestCallbackNoPython::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, long, std::shared_ptr<torch::utils::Future<torch::distributed::rpc::Message> > const&) const + 0x3f4 (0x7f87547bc304 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Sep 15 09:28:59 frame #4: torch::distributed::rpc::RequestCallbackImpl::processRpcWithErrors(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, long, std::shared_ptr<torch::utils::Future<torch::distributed::rpc::Message> > const&) const + 0x2f (0x7f875bbd116f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Sep 15 09:28:59 frame #5: <unknown function> + 0x353fa04 (0x7f87547b9a04 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Sep 15 09:28:59 frame #6: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&) const + 0x38b (0x7f87547bb2eb in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Sep 15 09:28:59 frame #7: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x1e (0x7f87547b813e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Sep 15 09:28:59 frame #8: torch::distributed::rpc::ProcessGroupAgent::handleRecv(torch::distributed::rpc::RecvWork&) + 0xc4 (0x7f875bbaf284 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Sep 15 09:28:59 frame #9: <unknown function> + 0xd5d1b2 (0x7f875bbb01b2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Sep 15 09:28:59 frame #10: c10::ThreadPool::main_loop(unsigned long) + 0x2b3 (0x7f8745165e33 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Sep 15 09:28:59 frame #11: <unknown function> + 0xd0b10 (0x7f8767917b10 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
Sep 15 09:28:59 frame #12: <unknown function> + 0x76ba (0x7f87851e76ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Sep 15 09:28:59 frame #13: clone + 0x6d (0x7f8784f1d4dd in /lib/x86_64-linux-gnu/libc.so.6)
Sep 15 09:28:59 
Sep 15 09:28:59 ERROR:root:Caught exception: 
Sep 15 09:28:59 Traceback (most recent call last):
Sep 15 09:28:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 247, in wrapper
Sep 15 09:28:59     fn()
Sep 15 09:28:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 71, in new_test_method
Sep 15 09:28:59     return_value = old_test_method(self, *arg, **kwargs)
Sep 15 09:28:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 278, in test_future_passed_between_python_and_jit
Sep 15 09:28:59     self.assertEqual(future_wait_in_script(ret_fut), expected_res)
Sep 15 09:28:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 121, in prof_func_call
Sep 15 09:28:59     return prof_callable(func_call, *args, **kwargs)
Sep 15 09:28:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 118, in prof_callable
Sep 15 09:28:59     return callable(*args, **kwargs)
Sep 15 09:28:59 RuntimeError: The following operation failed in the TorchScript interpreter.
Sep 15 09:28:59 Traceback of TorchScript (most recent call last):
Sep 15 09:28:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 276, in future_wait_in_script
Sep 15 09:28:59         @torch.jit.script
Sep 15 09:28:59         def future_wait_in_script(fut: Future[Tensor]) -> Tensor:
Sep 15 09:28:59             return fut.wait()
Sep 15 09:28:59                    ~~~~~~~~ <--- HERE
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu @gmagogsfm @xush6528

**Comment by gmagogsfm** [comment]
@wanchaol Wanchao, is `wait()` supported?

**Comment by wanchaol** [comment]
I just tried this locally, and it seems it's working properly now, closing it.
