### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by FTD007** [pytorch/pytorch#44828]
runned on 
pytorch 1.4
cuda 10.1
tesla K80

I thought K80 is 3.7 already but still get this error

error message:

THCudaCheck FAIL file=/pytorch/aten/src/ATen/native/cuda/Dropout.cu line=147 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/bin/tape-train-distributed", line 8, in <module>
    sys.exit(run_train_distributed())
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/main.py", line 252, in run_train_distributed
    args.node_rank, args.master_addr, args.master_port)
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/utils/distributed_utils.py", line 169, in launch_process_group
    while not process_context.join():
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/utils/distributed_utils.py", line 122, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/utils/distributed_utils.py", line 38, in _wrap
    fn(**kwargs)
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/main.py", line 191, in run_train
    training.run_train(**train_args)
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/training.py", line 508, in run_train
    viz, num_log_iter, gradient_accumulation_steps)
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/training.py", line 299, in run_train_epoch
    loss, metrics = runner.forward(batch)  # type: ignore
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/training.py", line 85, in forward
    outputs = self.model(**batch)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/models/modeling_bert.py", line 484, in forward
    outputs = self.bert(input_ids, input_mask=input_mask)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/models/modeling_bert.py", line 446, in forward
    embedding_output = self.embeddings(input_ids)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/dartfs-hpc/rc/lab/C/CBKlab/Bdai/bertprotein/tape/models/modeling_bert.py", line 142, in forward
    embeddings = self.dropout(embeddings)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/torch/nn/modules/dropout.py", line 54, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/dartfs-hpc/rc/home/w/f00355w/.conda/envs/tape/lib/python3.6/site-packages/torch/nn/functional.py", line 807, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /pytorch/aten/src/ATen/native/cuda/Dropout.cu:147

cc @ngimel

**Comment by ngimel** [comment]
Please try with the latest pytorch version, reopen if issue persists.

**Comment by FTD007** [comment]
> Please try with the latest pytorch version, reopen if issue persists.

I need a pytorch version >1.0 <1.5, btw how to reopen? do you mean start a new issue?

**Comment by ngimel** [comment]
1.4 version won't be fixed. Any other version in the range you've mention should work on K80.

**Comment by FTD007** [comment]
Oh ok, let me try. BTW does he cuda version matter? I am using 10.1, should I lower it to 10 or 9 for pytorch 1.3 or 1.2
