### ISSUE TITLE
`emit_nvtx` example in docs seems to be broken.

### ISSUE THREAD

**Issue by lematt1991** [pytorch/pytorch#44881]
## 🐛 Bug

Following an (adapted) version of the example provided in the docs for [`emit_nvtx`](https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.emit_nvtx) produces the following error:

```Python
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    with torch.autograd.profiler.emit_nvtx():
  File "/scratch/mattle/.conda/lib/python3.7/site-packages/torch/autograd/profiler.py", line 553, in __enter__
    False
RuntimeError: Profiler is already enabled on this thread
```

## To Reproduce

```Python
import torch

print(f'Version = {torch.__version__}')

x = torch.rand(100, 100, device='cuda')

with torch.autograd.profiler.profile():
    temp = x * x
    with torch.autograd.profiler.emit_nvtx():
        temp = x * x
```

Yields the following output:

```Python
Version = 1.6.0
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    with torch.autograd.profiler.emit_nvtx():
  File "/scratch/mattle/.conda/lib/python3.7/site-packages/torch/autograd/profiler.py", line 553, in __enter__
    False
RuntimeError: Profiler is already enabled on this thread
```

## Expected behavior

No error

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.6.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.1           py37hbc911f0_0  
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] numpydoc                  1.1.0                     <pip>
[conda] pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.9
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @jlin27

**Comment by bertmaher** [comment]
I think the error here is that:
```
with torch.autograd.profiler.profile():
```
should be
```
with torch.cuda.profiler.profile():
```

I've made that mistake as well and it seems confusing to have `emit_nvtx` in the `autograd.profiler` package, but enable its use via the `cuda.profiler` package.

**Comment by lematt1991** [comment]
Ah you're right, I totally missed that!  Thanks for pointing this out, it works using `torch.cuda.profiler.profile()`.  I'll close the issue.
