### ISSUE TITLE
Inconsistent result from FBGEMM and QNNPACK quantization backends

### ISSUE THREAD

**Issue by dbalchev** [pytorch/pytorch#44939]
## 🐛 Bug

Running quantized convolution with FBGEMM and QNNPACK yield different results. Since I noticed they handle the bias differently (FBGEMM adds it as a float, but QNNPACK quantizes it) I tried some tricks to workaround that, but found a case where their results differ even when there's no bias.I tried reproducing the calculations by hand and it seems the result from FBGEMM is wrong. 
## To Reproduce

1. Run the following unittest:
```python
import unittest
import torch


class QuantizationIssue(unittest.TestCase):
    def setUp(self):
        self.input_fp32 = torch.tensor([
            [5.384835, 12.083044, 27.318186],
            [12.4770565, 27.580862, 22.327364],
            [26.136148, 22.721376, 4.859485],
        ], dtype=torch.float32)
        self.input_scale = 0.13133743405342102
        self.input_zero_point = 1
        self.input_q = torch.quantize_per_tensor(
            self.input_fp32, self.input_scale, self.input_zero_point, dtype=torch.quint8,
        )
        self.input_expected_int_repr = torch.tensor([
            [42, 93, 209], [96, 211, 171], [200, 174, 38]
        ], dtype=torch.uint8)

        self.weight_fp32 = torch.tensor([
            [-0.3740014433860779, -0.2629697620868683, -0.17531317472457886],
            [-0.14317242801189423, 0.2074539214372635, 0.31264182925224304],
            [0.09350036084651947, 0.34478259086608887, 0.17531317472457886],
        ], dtype=torch.float32)
        self.weight_zero_point = 0
        self.weight_scale = 0.0029218862764537334
        self.weight_q = torch.quantize_per_tensor(
            self.weight_fp32, self.weight_scale, self.weight_zero_point, dtype=torch.qint8,
        )
        self.weight_expected_int_repr = torch.tensor([
            [-128, -90, -60], [-49, 71, 107], [32, 118, 60]
        ], dtype=torch.int8)
        self.output_scale = 0.10707724094390869
        self.output_zero_point = 0
        self.expected_output_int_repr = 113

    # This check verifies test validity
    def test_consistent_input(self):
        self.assertTrue((self.input_q.int_repr() == self.input_expected_int_repr).all())

    # This check verifies test validity
    def test_consistent_weight(self):
        self.assertTrue((self.weight_q.int_repr() == self.weight_expected_int_repr).all())

    # This check verifies test validity
    def test_qnnpack_conv(self):
        torch.backends.quantized.engine ='qnnpack'
        self._run_convolution()

    # THIS IS THE TEST THAT DEMONSTRATES THE ISSUE
    def test_fbgemm_conv(self):
        torch.backends.quantized.engine ='fbgemm'
        self._run_convolution()

    # This check verifies test validity
    def test_manual_calculation(self):
        flat_input = self.input_expected_int_repr.reshape([-1]).int()
        flat_weight = self.weight_expected_int_repr.reshape([-1]).int()
        qsum = ((flat_input - self.input_zero_point) * (flat_weight - self.weight_zero_point)).sum()
        unquantized_result = qsum * self.input_scale * self.weight_scale / self.output_scale
        rounded_result = torch.round(unquantized_result).item()
        self.assertEqual(rounded_result, self.expected_output_int_repr)

    def _run_convolution(self):
        conv_layer = torch.nn.intrinsic.quantized.ConvReLU2d(
            1, 1, (3, 3), bias=False
        )
        conv_layer.scale = self.output_scale
        conv_layer.zero_point = self.output_zero_point
        conv_layer.set_weight_bias(self.weight_q[None, None, :, :], None)
        output = conv_layer(self.input_q[None, None, :, :])
        self.assertEqual(output.int_repr().item(), self.expected_output_int_repr)


if __name__ == '__main__':
    unittest.main()

```
```
# python test_engine.py -v
test_consistent_input (__main__.QuantizationIssue) ... ok
test_consistent_weight (__main__.QuantizationIssue) ... ok
test_fbgemm_conv (__main__.QuantizationIssue) ... FAIL
test_manual_calculation (__main__.QuantizationIssue) ... ok
test_qnnpack_conv (__main__.QuantizationIssue) ... ok

======================================================================
FAIL: test_fbgemm_conv (__main__.QuantizationIssue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_engine.py", line 50, in test_fbgemm_conv
    self._run_convolution()
  File "test_engine.py", line 68, in _run_convolution
    self.assertEqual(output.int_repr().item(), self.expected_output_int_repr)
AssertionError: 111 != 113

----------------------------------------------------------------------
Ran 5 tests in 0.017s

FAILED (failures=1)
```

## Expected behavior

FBGEMM and QNNPACK to yield the same result, given the same inputs and weights. It would  be great to have the same handling of biases, but I understand that's a big and possibly breaking change.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
Collecting environment information...
PyTorch version: 1.6.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro M1200
Nvidia driver version: 440.100
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0+cpu
[conda] numpy                     1.19.2                    <pip>
[conda] torch                     1.6.0+cpu                 <pip>
```

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by dbalchev** [comment]
I dug deeper into FBGEMM implementation and found out that in this example I get a saturation in `vpmaddubsw` (`211 * 71 + 171 * 107 == 33278`). 

The issue can be closed, since this is a quirk of the implementation, but IMO this should be documented, since it's a bit obscure and hard to trace. (:

**Comment by vkuzo** [comment]
there is a `reduce_range` argument for observers to prevent the overflow in fbgemm (see https://pytorch.org/docs/stable/quantization.html, search for `reduce_range`).  Agreed that it's hard to find and we should document it better.

cc @raghuramank100
