### ISSUE TITLE
RuntimeError: DataLoader worker (pid 23616) is killed by signal: Terminated.

### ISSUE THREAD

**Issue by Jensen-Su** [pytorch/pytorch#4507]
Here is the error info
```PYTHON
Traceback (most recent call last):
  File "train_multi_task.py", line 192, in <module>
    experiment(config)
  File "train_multi_task.py", line 82, in experiment
    data_list.append(iter_.next())
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 267, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 246, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/queue.py", line 22, in recv
    return pickle.loads(buf)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/reductions.py", line 68, in rebuild_storage_fd
    fd = multiprocessing.reduction.rebuild_handle(df)
  File "/usr/lib/python2.7/multiprocessing/reduction.py", line 157, in rebuild_handle
    new_handle = recv_handle(conn)
  File "/usr/lib/python2.7/multiprocessing/reduction.py", line 83, in recv_handle
    return _multiprocessing.recvfd(conn.fileno())
OSError: [Errno 4] Interrupted system call
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
Error in sys.exitfunc:
Exception RuntimeError: RuntimeError('DataLoader worker (pid 23604) is killed by signal: Terminated.',) in <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f73ba2c8850>> ignored
Exception IOError: IOError(104, 'Connection reset by peer') in <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f73ba2c1890>> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 30, in _run_exitfuncs
    traceback.print_exc()
  File "/usr/lib/python2.7/traceback.py", line 233, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 133, in updatecache
    lines = fp.readlines()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 172, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 23616) is killed by signal: Terminated.
```
I'm lost...

**Comment by netheril96** [comment]
One solution might be moving your codes to Python 3.5+, where [syscalls failing with EINTR are retried automatically](https://www.python.org/dev/peps/pep-0475/).

**Comment by lysuhin** [comment]
+1
Installed the latest build from the source, now getting similar one:
`RuntimeError: DataLoader worker (pid 28124) is killed by signal: Illegal instruction.`

**Comment by apaszke** [comment]
What’s your CPU?

**Comment by SsnL** [comment]
@Jensen-Su Sorry about the tracing being polluted by the final RunTimeError. Your real issue is that EINTR interrupts `queue.get`. Python doesn't handle this until 3.5. I'll send out a PR to address these two things.

@lysuhin Your issue is unrelated to the above one. What did you do in your dataset's `__getitem__`? Also, as asked by @apaszke , what's your CPU?

**Comment by zengxianyu** [comment]
I meet the same problem using the newest pytorch:

Traceback (most recent call last):
  File "train_cls.py", line 70, in <module>
    for ib, (data, lbl) in enumerate(train_loader):
  File "/home/crow/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 259, in __next__
    return self._process_next_batch(batch)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 293, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ZeroDivisionError: Traceback (most recent call last):
  File "/home/crow/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 56, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 122, in __getitem__
    img = self.loader(path)
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 69, in default_loader
    return pil_loader(path)
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 51, in pil_loader
    img = Image.open(f)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2506, in open
    im = _open_core(fp, filename, prefix)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2496, in _open_core
    im = factory(fp, filename)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 757, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/crow/anaconda2/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 335, in _open
    handler(self, i)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 127, in APP
    dpi = x_resolution[0] / x_resolution[1]
ZeroDivisionError: integer division or modulo by zero

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/crow/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/util.py", line 328, in _exit_function
    p.join()
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/process.py", line 148, in join
    res = self._popen.wait(timeout)
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 172, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 37825) is killed by signal: Terminated.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/crow/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/util.py", line 328, in _exit_function
    p.join()
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/process.py", line 148, in join
    res = self._popen.wait(timeout)
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/home/crow/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/crow/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 172, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 37825) is killed by signal: Terminated.

**Comment by SsnL** [comment]
You should look at the first error. It clearly says division by zero.

**Comment by shirishr** [comment]
I too got this error below, but I am on Python 3.6, would that be the cause?
RuntimeError: DataLoader worker (pid 8591) is killed by signal: Illegal instruction.

Trace reproduced below:
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    for i, data in enumerate(dataset):
  File "/home/sam/Documents/ComputerVision/pytorch-CycleGAN-and-pix2pix/data/custom_dataset_data_loader.py", line 44, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/sam/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/home/sam/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/sam/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 8591) is killed by signal: Illegal instruction.

**Comment by ernestcai** [comment]
I met the same issue as @shirishr. It was simply because of not enough memory, you may add more memory / swap space to solve the problem.

**Comment by MaratZakirov** [comment]
I have same problem on pytorch 0.4.1, but on 0.3.1 don't

**Comment by JosephKJ** [comment]
Using just the parent thread for data-loading would be a workaround.

`num_workers=0 `

Ref: https://github.com/pytorch/pytorch/issues/5363#issuecomment-368370624

**Comment by zhuyangda** [comment]
Does it become slower when the num_workers=0?

**Comment by Abhishek-kumar-k** [comment]
In which file we have to set num_workers=0 ?

> Using just the parent thread for data-loading would be a workaround.
> 
> `num_workers=0 `
> 
> Ref: [#5363 (comment)](https://github.com/pytorch/pytorch/issues/5363#issuecomment-368370624)

**Comment by Abhishek-kumar-k** [comment]
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-e19a41c0004b> in <module>
    292 
    293     })
--> 294     run(args)

<ipython-input-1-e19a41c0004b> in run(args)
    212         t_start = time.time()
    213 
--> 214         train_loss, train_auc = train_model(mrnet, train_loader, epoch, num_epochs, optimizer, writer, current_lr, log_every)
    215         val_loss, val_auc = evaluate_model(mrnet, validation_loader, epoch, num_epochs, writer, current_lr)
    216 

<ipython-input-1-e19a41c0004b> in train_model(model, train_loader, epoch, num_epochs, optimizer, writer, current_lr, log_every)
     44         weight = weight[0]
     45 
---> 46         prediction = model.forward(image.float())
     47 
     48         loss = torch.nn.BCEWithLogitsLoss(weight=weight)(prediction, label)

~/CKMRI/model.py in forward(self, x)
     14     def forward(self, x):
     15         x = torch.squeeze(x, dim=0)
---> 16         features = self.pretrained_model.features(x)
     17         pooled_features = self.pooling_layer(features)
     18         pooled_features = pooled_features.view(pooled_features.size(0), -1)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py in forward(self, input)
     98     def forward(self, input):
     99         for module in self:
--> 100             input = module(input)
    101         return input
    102 

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py in forward(self, input)
    347 
    348     def forward(self, input):
--> 349         return self._conv_forward(input, self.weight)
    350 
    351 class Conv3d(_ConvNd):

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight)
    344                             _pair(0), self.dilation, self.groups)
    345         return F.conv2d(input, weight, self.bias, self.stride,
--> 346                         self.padding, self.dilation, self.groups)
    347 
    348     def forward(self, input):

~/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py in handler(signum, frame)
     64         # This following call uses `waitid` with WNOHANG from C side. Therefore,
     65         # Python can still get and update the process status successfully.
---> 66         _error_if_any_worker_fails()
     67         if previous_handler is not None:
     68             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 3203) is killed by signal: Killed.
