### ISSUE TITLE
DISABLED test_backward_ddp_outside_uneven_inputs (__main__.TensorPipeDdpUnderDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#45118]
https://app.circleci.com/pipelines/github/pytorch/pytorch/217196/workflows/15141629-1343-446c-a9cf-230f9c6b4527/jobs/7655526/steps

Probably same issue as #45105, which affects ProcessGroup.

```
Sep 22 01:48:33   test_backward_ddp_outside_uneven_inputs (__main__.TensorPipeDdpUnderDistAutogradTestWithSpawn) ... 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:342 INFO p:process 0 t:MainThread: Running the trainer #0...
Sep 22 01:48:33 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:344 INFO p:process 0 t:MainThread: Initing trainer process group by trainer #0 with ranks [0, 1, 2, 3]
Sep 22 01:48:33 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:342 INFO p:process 2 t:MainThread: Running the trainer #2...
Sep 22 01:48:33 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:342 INFO p:process 1 t:MainThread: Running the trainer #1...
Sep 22 01:48:33 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:344 INFO p:process 1 t:MainThread: Initing trainer process group by trainer #1 with ranks [0, 1, 2, 3]
Sep 22 01:48:33 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:344 INFO p:process 2 t:MainThread: Initing trainer process group by trainer #2 with ranks [0, 1, 2, 3]
Sep 22 01:48:33 2020-09-22 01:48:33,735 ddp_under_dist_autograd_test.py:342 INFO p:process 3 t:MainThread: Running the trainer #3...
Sep 22 01:48:33 2020-09-22 01:48:33,736 ddp_under_dist_autograd_test.py:344 INFO p:process 3 t:MainThread: Initing trainer process group by trainer #3 with ranks [0, 1, 2, 3]
Sep 22 01:48:33 2020-09-22 01:48:33,736 ddp_under_dist_autograd_test.py:328 INFO p:process 4 t:MainThread: The remote worker is running.
Sep 22 01:48:33 2020-09-22 01:48:33,736 ddp_under_dist_autograd_test.py:362 INFO p:process 5 t:MainThread: Running the master process...
Sep 22 01:48:33 2020-09-22 01:48:33,740 ddp_under_dist_autograd_test.py:353 INFO p:process 1 t:MainThread: Waiting for shutdown signal on trainer #1...
Sep 22 01:48:33 2020-09-22 01:48:33,740 ddp_under_dist_autograd_test.py:353 INFO p:process 2 t:MainThread: Waiting for shutdown signal on trainer #2...
Sep 22 01:48:33 2020-09-22 01:48:33,740 ddp_under_dist_autograd_test.py:353 INFO p:process 3 t:MainThread: Waiting for shutdown signal on trainer #3...
Sep 22 01:48:33 2020-09-22 01:48:33,741 ddp_under_dist_autograd_test.py:375 INFO p:process 5 t:MainThread: Created remote rrefs on master
Sep 22 01:48:33 2020-09-22 01:48:33,741 ddp_under_dist_autograd_test.py:389 INFO p:process 5 t:MainThread: Running DDP + RPC test with simulating uneven inputs across trainers.
Sep 22 01:48:33 2020-09-22 01:48:33,743 ddp_under_dist_autograd_test.py:93 INFO p:process 4 t:Dummy-1: Initing RemoteEM with 2 3
Sep 22 01:48:33 2020-09-22 01:48:33,744 ddp_under_dist_autograd_test.py:119 INFO p:process 4 t:Dummy-2: Initing RemoteNet with 5 3
Sep 22 01:48:33 2020-09-22 01:48:33,761 ddp_under_dist_autograd_test.py:353 INFO p:process 0 t:MainThread: Waiting for shutdown signal on trainer #0...
Sep 22 01:48:33 ERROR:root:Caught exception: 
Sep 22 01:48:33 Traceback (most recent call last):
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 246, in wrapper
Sep 22 01:48:33     fn()
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 70, in new_test_method
Sep 22 01:48:33     return_value = old_test_method(self, *arg, **kwargs)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 476, in test_backward_ddp_outside_uneven_inputs
Sep 22 01:48:33     self._do_test(DdpMode.OUTSIDE, simulate_uneven_inputs=True)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 455, in _do_test
Sep 22 01:48:33     self._master_process(ddp_mode, simulate_uneven_inputs)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 377, in _master_process
Sep 22 01:48:33     ddp_mode, simulate_uneven_inputs, remote_em_rref, remote_net_rref
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 423, in do_test_on_master
Sep 22 01:48:33     ddp_grads, non_ddp_grads = future.wait()
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 177, in _handle_exception
Sep 22 01:48:33     raise result.exception_type(result.msg)
Sep 22 01:48:33 AssertionError: On WorkerInfo(id=0, name=worker0):
Sep 22 01:48:33 AssertionError('On WorkerInfo(id=0, name=worker0):\nAssertionError(\'Default process group is not initialized\')\nTraceback (most recent call last):\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function\n    result = python_udf.func(*python_udf.args, **python_udf.kwargs)\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 186, in __init__\n    if ddp_mode in (DdpMode.INSIDE, DdpMode.OUTSIDE)\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1979, in new_group\n    _check_default_pg()\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg\n    "Default process group is not initialized"\nAssertionError: Default process group is not initialized\n')
Sep 22 01:48:33 Traceback (most recent call last):
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function
Sep 22 01:48:33     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 78, in _call_method
Sep 22 01:48:33     return method(rref.local_value(), *args, **kwargs)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 177, in _handle_exception
Sep 22 01:48:33     raise result.exception_type(result.msg)
Sep 22 01:48:33 AssertionError: On WorkerInfo(id=0, name=worker0):
Sep 22 01:48:33 AssertionError('Default process group is not initialized')
Sep 22 01:48:33 Traceback (most recent call last):
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function
Sep 22 01:48:33     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 186, in __init__
Sep 22 01:48:33     if ddp_mode in (DdpMode.INSIDE, DdpMode.OUTSIDE)
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1979, in new_group
Sep 22 01:48:33     _check_default_pg()
Sep 22 01:48:33   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
Sep 22 01:48:33     "Default process group is not initialized"
Sep 22 01:48:33 AssertionError: Default process group is not initialized
Sep 22 01:48:33 
Sep 22 01:48:33 
Sep 22 01:48:33 exiting process with exit code: 10
Sep 22 01:48:33 [W tensorpipe_agent.cpp:577] RPC agent for worker3 encountered error when reading incoming request from worker5: EOF: end of file (this is expected to happen during shutdown)
Sep 22 01:48:33 [W tensorpipe_agent.cpp:577] RPC agent for worker2 encountered error when reading incoming request from worker5: EOF: end of file (this is expected to happen during shutdown)
Sep 22 01:48:33 [W tensorpipe_agent.cpp:577] RPC agent for worker1 encountered error when reading incoming request from worker5: EOF: end of file (this is expected to happen during shutdown)
Sep 22 01:48:33 [W tensorpipe_agent.cpp:577] RPC agent for worker4 encountered error when reading incoming request from worker5: EOF: end of file (this is expected to happen during shutdown)
Sep 22 01:48:33 [W tensorpipe_agent.cpp:577] RPC agent for worker0 encountered error when reading incoming request from worker5: EOF: end of file (this is expected to happen during shutdown)
Sep 22 01:48:33 Process 5 terminated with exit code 10, terminating remaining processes.
Sep 22 01:48:33 ERROR (2.333s)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jjlilley

**Comment by mrshenli** [comment]
closed by #45181
