### ISSUE TITLE
DISABLED test_backward_ddp_inside (__main__.TensorPipeDdpUnderDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#45122]
https://app.circleci.com/pipelines/github/pytorch/pytorch/217203/workflows/9228f0bf-ed03-47fe-9a3d-dc736b8e14c3/jobs/7653966/steps

Same as #40434, but for TensorPipe backend

```
Sep 21 23:53:07 ERROR:root:Caught exception: 
Sep 21 23:53:07 Traceback (most recent call last):
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 246, in wrapper
Sep 21 23:53:07     fn()
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 70, in new_test_method
Sep 21 23:53:07     return_value = old_test_method(self, *arg, **kwargs)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 481, in test_backward_ddp_inside
Sep 21 23:53:07     self._do_test(DdpMode.INSIDE)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 455, in _do_test
Sep 21 23:53:07     self._master_process(ddp_mode, simulate_uneven_inputs)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 377, in _master_process
Sep 21 23:53:07     ddp_mode, simulate_uneven_inputs, remote_em_rref, remote_net_rref
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 423, in do_test_on_master
Sep 21 23:53:07     ddp_grads, non_ddp_grads = future.wait()
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 177, in _handle_exception
Sep 21 23:53:07     raise result.exception_type(result.msg)
Sep 21 23:53:07 AssertionError: On WorkerInfo(id=0, name=worker0):
Sep 21 23:53:07 AssertionError('On WorkerInfo(id=0, name=worker0):\nAssertionError(\'Default process group is not initialized\')\nTraceback (most recent call last):\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function\n    result = python_udf.func(*python_udf.args, **python_udf.kwargs)\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 186, in __init__\n    if ddp_mode in (DdpMode.INSIDE, DdpMode.OUTSIDE)\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1979, in new_group\n    _check_default_pg()\n  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg\n    "Default process group is not initialized"\nAssertionError: Default process group is not initialized\n')
Sep 21 23:53:07 Traceback (most recent call last):
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function
Sep 21 23:53:07     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 78, in _call_method
Sep 21 23:53:07     return method(rref.local_value(), *args, **kwargs)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 177, in _handle_exception
Sep 21 23:53:07     raise result.exception_type(result.msg)
Sep 21 23:53:07 AssertionError: On WorkerInfo(id=0, name=worker0):
Sep 21 23:53:07 AssertionError('Default process group is not initialized')
Sep 21 23:53:07 Traceback (most recent call last):
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function
Sep 21 23:53:07     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 186, in __init__
Sep 21 23:53:07     if ddp_mode in (DdpMode.INSIDE, DdpMode.OUTSIDE)
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1979, in new_group
Sep 21 23:53:07     _check_default_pg()
Sep 21 23:53:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
Sep 21 23:53:07     "Default process group is not initialized"
Sep 21 23:53:07 AssertionError: Default process group is not initialized
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
Isn't this a duplicate of #45116?

**Comment by mrshenli** [comment]
> Isn't this a duplicate of #45116?

Yes didn't realize that. Let me close this one.
