### ISSUE TITLE
[Native] ConvTranspose2d crashed

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#45172]
## 🐛 Bug

PyTorch native ConvTranspose2d failed

## To Reproduce

```python
import torch
print(torch.__version__)

x = torch.randn(6, 28, 108, 108, dtype=torch.half, device='cuda', requires_grad=True)\
    .to(memory_format=torch.channels_last)
net = torch.nn.ConvTranspose2d(28, 28, kernel_size=1, groups=1).cuda().half()\
    .to(memory_format=torch.channels_last)

with torch.backends.cudnn.flags(enabled=False, deterministic=True, benchmark=True, allow_tf32=True):
    out = net(x)
    out.backward(torch.randn_like(out))

torch.cuda.synchronize()
```

Exception stacktrace:
```
1.7.0a0+c947ab0
Traceback (most recent call last):
  File "conv-9-22-2020.py", line 11, in <module>
    out.backward(torch.randn_like(out))
  File "/home/xwang/Developer/pytorch/torch/tensor.py", line 215, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xwang/Developer/pytorch/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: The size of tensor a (11664) must match the size of tensor b (108) at non-singleton dimension 2
Exception raised from infer_size at ../aten/src/ATen/ExpandUtils.cpp:20 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x68 (0x7f45340f3eb8 in /home/xwang/Developer/pytorch/torch/lib/libc10.so)
frame #1: <unknown function> + 0x6ba429 (0x7f453cb57429 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #2: at::TensorIterator::compute_shape(at::TensorIteratorConfig const&) + 0xd3 (0x7f453da81da3 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #3: at::TensorIterator::build(at::TensorIteratorConfig&) + 0x67 (0x7f453da85d17 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #4: at::TensorIterator::TensorIterator(at::TensorIteratorConfig&) + 0xc8 (0x7f453da85fb8 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x14199a4 (0x7f453d8b69a4 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #6: at::native::copy_(at::Tensor&, at::Tensor const&, bool) + 0x53 (0x7f453d8b74a3 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #7: at::Tensor& c10::Dispatcher::callWithDispatchKey<at::Tensor&, at::Tensor&, at::Tensor const&, bool>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, at::Tensor const&, bool)> const&, c10::DispatchKey, at::Tensor&, at::Tensor const&, bool) const + 0xac (0x7f453de549ac in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #8: at::Tensor::copy_(at::Tensor const&, bool) const + 0xd9 (0x7f453df99e79 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #9: at::native::(anonymous namespace)::slow_conv_transpose2d_acc_grad_parameters_cuda_template(at::Tensor const&, at::Tensor const&, at::Tensor&, at::Tensor&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, int) + 0x1b3d (0x7f4535e7cfdd in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #10: at::native::slow_conv_transpose2d_backward_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x3e6 (0x7f4535e7f4d6 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x2ddb632 (0x7f4536f19632 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #12: <unknown function> + 0x2dfc248 (0x7f4536f3a248 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #13: <unknown function> + 0x19f6db3 (0x7f453de93db3 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #14: at::slow_conv_transpose2d_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x297 (0x7f453ddb5377 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x2e7e74e (0x7f453f31b74e in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x182dd58 (0x7f453dccad58 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x19f6db3 (0x7f453de93db3 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #18: at::slow_conv_transpose2d_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x297 (0x7f453ddb5377 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::generated::SlowConvTranspose2DBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x3e0 (0x7f453f186020 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #20: <unknown function> + 0x317ebeb (0x7f453f61bbeb in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #21: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1852 (0x7f453f616852 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #22: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x5d0 (0x7f453f6171c0 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #23: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x9b (0x7f453f610d9b in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #24: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x5e (0x7f45440dcc6e in /home/xwang/Developer/pytorch/torch/lib/libtorch_python.so)
frame #25: <unknown function> + 0xcfc24 (0x7f454fb33c24 in /usr/lib/libstdc++.so.6)
frame #26: <unknown function> + 0x93e9 (0x7f456c8333e9 in /usr/lib/libpthread.so.0)
frame #27: clone + 0x43 (0x7f456c94c293 in /usr/lib/libc.so.6)
```

Note that this **failed** on pytorch commit 1.7.0a0+ c947ab0, but **passed** on 1.7.0a0+ 4810365. So one of the commits merged on 9/21 could be the problem.

Also note that we have cudnn flags **enabled=False**, so this is **not** a cuDNN issue.

## Expected behavior

No fail.

## Environment

```
Collecting environment information...
PyTorch version: 1.7.0a0+c947ab0
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.1
[pip] torch==1.7.0a0
[pip] torchvision==0.8.0a0+b28d480
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] nomkl                     3.0                           0
[conda] numpy                     1.19.1           py38h30dfecb_0
[conda] numpy-base                1.19.1           py38h75fe3a5_0
[conda] torch                     1.7.0a0                   dev_0    <develop>
[conda] torchvision               0.8.0a0+b28d480          pypi_0    pypi
```

## Additional context

A simple bisection can find the problematic commit. 

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by ezyang** [comment]
It's almost certainly e2f49c8437421919bdd3a55a49c6b35af1e36a7d. cc @walterddr

**Comment by walterddr** [comment]
on it
