### ISSUE TITLE
Backward of repeat() crash if repeated size is 0

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#45201]
Repro:

```python
import torch

a = torch.rand(10, requires_grad=True)

b = a.repeat(0)

b.sum().backward()
```

Fails with:
```
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    b.sum().backward()
  File "/usr/local/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: chunk expects `chunks` to be greater than 0, got: 0
```

This should return a gradient full of 0s

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved

**Comment by rajarsheem** [comment]
Was this issue solved because I still observe it in PyTorch 1.8.1. I had to explicitly ensure that repeated size is > 0 to overcome this error.
