### ISSUE TITLE
descriptor 'add' of 'torch._C._VariableBase' object needs an argument

### ISSUE THREAD

**Issue by zchky** [pytorch/pytorch#4530]
the pytorch document said that the add opeartion can be like this
         ` torch.add(input, value=1, other, out=None)`
but it will rise the error of descriptor 'add' of 'torch._C._VariableBase' object needs an argument
when i do 
        `torch.add(input=a, value=0.01, other=a)`

a is a Variable  like
Variable containing:
 5.0500
[torch.FloatTensor of size 1]

but torch.add(a, 0.01, a) is fine to work

**Comment by zou3519** [comment]
I'll fix the docs for this later. 

@zchky The behavior for this the add function is a little funky because a non-named argument comes after a named one. You shouldn't give names for `input` and `other` when calling, so
`torch.add(a, 0.1, a)` is good. When you leave out the value 0.1, it's inferred that when you're calling `torch.add(a, b)`, `value` is 1.

**Comment by gchanan** [comment]
@zou3519  I don't think this issue is specific to `add`; For example variants of `mul` have the same behavior:
```
>>> a=Variable(torch.randn(2,3))
>>> torch.mul(input=a, value=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'mul' of 'torch._C._VariableBase' object needs an argument
>>> torch.mul(input=a, other=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'mul' of 'torch._C._VariableBase' object needs an argument
```

**Comment by colesbury** [comment]
We haven't updated the docs yet because the signature is different between Variable and Tensor.
