### ISSUE TITLE
Error when running distributed rpc parameter server example

### ISSUE THREAD

**Issue by DN6** [pytorch/pytorch#45338]
## 🐛 Bug

Hello. I'm trying to run the distributed RPC [example](https://github.com/pytorch/examples/blob/master/distributed/rpc/parameter_server/rpc_parameter_server.py) using two EC2 instances running Amazon's Deep Learning AMI. I'm encountering the following issue. 

Traceback on Master Node
```
(pytorch_p36) ubuntu@ip-172-31-67-172:~/examples/_pytorch/examples/distributed/rpc/parameter_server$ python rpc_parameter_server.py --world_size 2 --rank 0 --num_gpus 2 --master_addr 172.31.67.172
PS master initializing RPC
RPC initialized! Running parameter server...
Using 2 GPUs to train
Putting first 2 convs on cuda:0
Putting rest of layers on cuda:1
terminate called after throwing an instance of 'gloo::IoException'
  what():  [/opt/conda/conda-bld/pytorch_1579022034529/work/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [172.31.78.254]:13001: Connection reset by peer
```
Traceback on Worker Node
```
(pytorch_p36) ubuntu@ip-172-31-78-254:~/examples/_pytorch/examples/distributed/rpc/parameter_server$ python rpc_parameter_server.py --world_size 2 --rank 1 --num_gpus 2 --master_addr 172.31.67.172
Worker rank 1 initializing RPC
Worker 1 done initializing RPC
Rank 1 training batch 0 loss 2.3232274055480957
Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "rpc_parameter_server.py", line 224, in run_worker
    run_training_loop(rank, num_gpus, train_loader, test_loader)
  File "rpc_parameter_server.py", line 183, in run_training_loop
    dist_autograd.backward(cid, [loss])
TypeError: backward(): incompatible function arguments. The following argument types are supported:
    1. (roots: List[at::Tensor]) -> None
Invoked with: 281474976710656, [tensor(2.3232, grad_fn=<NllLossBackward>)]
```
## To Reproduce

1. Create two instances EC2 instances with the Deep Learning AMI
2. Clone Pytorch Examples repo on each machine and run [rpc_parameter_server script](https://github.com/pytorch/examples/blob/master/distributed/rpc/parameter_server/rpc_parameter_server.py) on master and worker nodes  

## Expected behavior

Example should download the MNIST dataset and train a Pytorch Neural Network in a distributed model parallel way. 

## Environment

Both machines have the same environment

```
PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.17.3
Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
Nvidia driver version: 450.51.06
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h830a2c2_0    conda-forge
[conda] numpy                     1.19.1           py36hbc911f0_0
[conda] numpy-base                1.19.1           py36hfa32c7d_0
[conda] numpydoc                  0.9.2                      py_0
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch
```

## Additional context
Specs for EC2 Machine
```
Instance Size: p3.8xlarge
GPUs-Tesla V100 
GPU Peer to Peer NVLINK
GPU Memory 64GB
vCPUs 32
Memory (GB) 244
Network Bandwidth 10Gbps
EBS Bandwidth 7GBps
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jjlilley

**Comment by zou3519** [comment]
cc @mrshenli @pritamdamania -- marked this as hi-pri because it's a tutorial example. Could you take a look please?

**Comment by mrshenli** [comment]
Hey @DN6, looks like you are using PyTorch v1.4 where RPC is a beta feature. Since v1.5, the `dist_autograd.backward()` API added a `context_id` field as the first argument to make it functional. Upgrading to the latest version should fix this error.

**Comment by mrshenli** [comment]
Hey @DN6, I am closing this issue. Please feel free to reopen if the error persist after upgrading to the latest version. Thanks.
