### ISSUE TITLE
Found dtype Long but expected Float

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#45373]
I had a python code which was fine with python2.7 and older pytorch versions. However, as I cloned the latest pytorch version today and installed that via `python3 setup.py install --user`, I now get this error

```
Starting Training Loop...
Traceback (most recent call last):
  File "main.py", line 245, in <module>
    errD_real = criterion(output, label)
  File "/home/mahmood/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mahmood/.local/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 530, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/mahmood/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 2527, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: Found dtype Long but expected Float
```

The code looks like
```
        # Forward pass real batch through D
        output = netD(real_cpu).view(-1)
        # Calculate loss on all-real batch
        errD_real = criterion(output, label)
        # Calculate gradients for D in backward pass
        errD_real.backward()
```

Any idea to fix that in new version?

**Comment by mahmoodn** [comment]
That is part of the dcgan code in the tutorial.
@inkawhich do you have any idea?

**Comment by mahmoodn** [comment]
The fix is [here](https://github.com/pytorch/tutorials/blob/master/beginner_source/dcgan_faces_tutorial.py#L594)
```
label = torch.full((b_size,), real_label, dtype=torch.float, device=device)
```
