### ISSUE TITLE
Backward for sparse tensor item select does not work

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#45459]
## 🐛 Bug

Computing a backward of sparse tensor item selection fails.

## To Reproduce

```
>>> a = torch.sparse_coo_tensor([[0]], [1.0], (1,), requires_grad=True)
>>> a[0]
tensor(1., grad_fn=<SelectBackward>)
>>> a[0].backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pearu/git/Quansight/pytorch/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/pearu/git/Quansight/pytorch/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function SelectBackward returned an invalid gradient at index 0 - expected type TensorOptions(dtype=float, device=cpu, layout=Sparse, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)) but got TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))

```

## Expected behavior

Backward for a strided tensor item selection works:
```
>>> a = torch.tensor([1.], requires_grad=True)
>>> a[0].backward()
>>> a.grad
tensor([1.])
```

Hence, for a sparse tensor, this should happen:
```
>>> a = torch.sparse_coo_tensor([[0]], [1.0], (1,), requires_grad=True)
>>> a[0].backward()
>>> a.grad
tensor(indices=tensor([[0]]),
       values=tensor([1.]),
       size=(1,), nnz=1, layout=torch.sparse_coo)
```

## Environment

 - PyTorch Version: 1.7.0 (current master)

**Comment by enegrini** [comment]
Any news on this? Thanks

**Comment by albanD** [comment]
Hi,

There are still ongoing discussions on the semantic of the backward pass for sparse Tensor. We plan on finishing that before the end of the year so that we know how this issue (and many similar ones) should be fixed.
