### ISSUE TITLE
CUDA crash when backproping through a reference to a transposed matrix

### ISSUE THREAD

**Issue by dianlujitao** [pytorch/pytorch#45567]
## 🐛 Bug

I'm trying to implement a tied autoencoder where the weights of the decoder are simply the transpose of the encoder. However, I got a CUDA crash when invoking `.backward()`, but it works fine on CPU. An MWE and workaround are provided below.

## To Reproduce

The MWE is as follows:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class FakeAE(nn.Module):
    def __init__(self):
        super().__init__()
        self.enc_w = nn.Parameter(torch.Tensor(3, 5))
        self.dec_w = self.enc_w.T

        nn.init.normal_(self.enc_w)

    def encode(self, data):
        return F.linear(data, self.enc_w)

    def decode(self, data):
        # return F.linear(data, self.enc_w.T)  # workaround the error
        return F.linear(data, self.dec_w)

    def forward(self, data):
        return self.decode(self.encode(data))


def main():
    device = 'cuda'
    # device = 'cpu'  # works!
    ae = FakeAE().to(device)
    criterion = nn.MSELoss()
    optimizer = optim.SGD(ae.parameters(), lr=1)

    data = torch.rand((2, 5)).to(device)
    rec = ae(data)
    loss = criterion(data, rec)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


if __name__ == "__main__":
    main()
```

1. Run the code above

Notice my comments in code, if the transpose of the parameter is directly passed to`F.linear()` instead of storing as a class member first and pass it later, the program won't crash. Furthermore, if the program is executed on CPU, no crash is observed in either case.

## Expected behavior

Not crash.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 440.82
 - GPU models and configuration: TITAN Xp
 - Any other relevant information:

## Additional context

Error messages:

```
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    main()
  File "test.py", line 37, in main
    loss.backward()
  File "/home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
Exception raised from createCublasHandle at /opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/ATen/cuda/CublasHandlePool.cpp:8 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f207987e77d in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xcec005 (0x7f207a9d0005 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: at::cuda::getCurrentCUDABlasHandle() + 0xb75 (0x7f207a9d0ee5 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xcdf097 (0x7f207a9c3097 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::native::(anonymous namespace)::addmm_out_cuda_impl(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) + 0xf7e (0x7f207bd27ace in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::mm_cuda(at::Tensor const&, at::Tensor const&) + 0xb3 (0x7f207bd295c3 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xd04d20 (0x7f207a9e8d20 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x7b1990 (0x7f20b078a990 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, at::Tensor const&, at::Tensor const&) const + 0xbc (0x7f20b0f72c7c in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::mm(at::Tensor const&, at::Tensor const&) + 0x4b (0x7f20b0ec3b0b in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2c2be8f (0x7f20b2c04e8f in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x7b1990 (0x7f20b078a990 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #12: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, at::Tensor const&, at::Tensor const&) const + 0xbc (0x7f20b0f72c7c in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: at::Tensor::mm(at::Tensor const&) const + 0x4b (0x7f20b105910b in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x2a6d217 (0x7f20b2a46217 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::generated::MmBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x25f (0x7f20b2a61c3f in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x30d1017 (0x7f20b30aa017 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1400 (0x7f20b30a5860 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x7f20b30a6401 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x89 (0x7f20b309e579 in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #20: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x4a (0x7f20b73c81ba in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #21: <unknown function> + 0xc819d (0x7f20b9ed519d in /home/dianlujitao/pkgs/miniconda3/envs/dcn/lib/python3.8/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #22: <unknown function> + 0x76ba (0x7f20d42046ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #23: clone + 0x6d (0x7f20d3f3a41d in /lib/x86_64-linux-gnu/libc.so.6)
```

cc @ngimel

**Comment by ngimel** [comment]
cc @ptrblck, @xwang233

**Comment by ptrblck** [comment]
@dianlujitao Could you check, if `ae.dec_w` was properly pushed to the device as well?
In `1.7.0.dev20200830` I get a proper error message claiming:
```python
RuntimeError: Tensor for argument #3 'mat2' is on CPU, but expected it to be on GPU (while checking arguments for addmm)
```
which is raised, because the tensor assignment in `self.dec_w = self.enc_w.T` doesn't register this tensor as a parameter as can also be seen here:
```python
ae = FakeAE().to(device)
print(dict(ae.named_parameters()))
> {'enc_w': Parameter containing:
tensor([[-1.2423,  0.1530, -0.3113, -1.4797, -0.9570],
        [-0.4318,  0.9830, -0.9902,  2.1654,  0.6976],
        [-0.1927, -0.5456,  0.6199,  1.3405,  2.3754]], device='cuda:0',
       requires_grad=True)}
```
The error message you are seeing shouldn't be raised, but it seems the nightlies after 1.6 raise the proper error.

I'm not completely sure, if `self.dec_w = self.enc_w.T` should register `dec_w` as a parameter, but think that reusing `self.enc_w.T` in the `forward` might be the right approach here.

**Comment by ngimel** [comment]
Thanks for looking into this @ptrblck. `self.dec_w = self.enc_w.T` won't register dec_w as a parameter (because self.dec_w is not a leaf in this case). The error is cause because `self.dec_w` is not a parameter and thus is not moved to device. Using `self.enc_w.T` is the right approach that preserves sharing semantics. 
Closing, as the error message raised now is correct.
