### ISSUE TITLE
Missing hydra-core dependencies when trying to load fairseq from torch hub

### ISSUE THREAD

**Issue by yrf1** [pytorch/pytorch#45786]
Got this error when trying to run a simple command: 
`torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')`
```
Traceback (most recent call last):
 File "machine_translation.py", line 10, in <module>
  en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')
 File "/home/yifung2/miniconda3/envs/VQA/lib/python3.7/site-packages/torch/hub.py", line 364, in load
  entry = _load_entry_from_hubconf(hub_module, model)
 File "/home/yifung2/miniconda3/envs/VQA/lib/python3.7/site-packages/torch/hub.py", line 232, in _load_entry_from_hubconf
  _check_dependencies(m)
 File "/home/yifung2/miniconda3/envs/VQA/lib/python3.7/site-packages/torch/hub.py", line 221, in _check_dependencies
  raise RuntimeError('Missing dependencies: {}'.format(', '.join(missing_deps)))
RuntimeError: Missing dependencies: hydra-core. 
``` 

Here are all my package versions and dependencies for reproducibility:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
antlr4-python3-runtime    4.8                      pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
blas                      1.0                         mkl    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
catalogue                 1.0.0                      py_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.14.0                   pypi_0    pypi
chardet                   3.0.4           py37hc8dfbb8_1007    conda-forge
click                     7.0                      pypi_0    pypi
cryptography              2.8              py37h72c5cf5_1    conda-forge
cudatoolkit               10.1.243             h6bb024c_0  
cymem                     2.0.3            py37he1b5a44_0    conda-forge
cython                    0.29.15                  pypi_0    pypi
cython-blis               0.4.1            py37h516909a_0    conda-forge
en-core-web-sm-mirror     2.2.5                    pypi_0    pypi
fairseq                   0.9.0                    pypi_0    pypi
fastbpe                   0.1.0                    pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
hydra-core                1.0.3                    pypi_0    pypi
idna                      2.8                   py37_1000    conda-forge
importlib-resources       3.0.0                    pypi_0    pypi
importlib_metadata        1.5.0                    py37_0    conda-forge
intel-openmp              2020.0                      166  
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    py37_0    conda-forge
language-check            1.1                      pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
murmurhash                1.0.0            py37he1b5a44_0    conda-forge
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
olefile                   0.46                     py37_0  
omegaconf                 2.0.2                    pypi_0    pypi
openssl                   1.1.1d               h516909a_0    conda-forge
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_1    conda-forge
plac                      0.9.6                    py37_0  
portalocker               1.5.2                    pypi_0    pypi
preshed                   3.0.2            py37he1b5a44_1    conda-forge
pycparser                 2.19                     pypi_0    pypi
pyopenssl                 19.1.0                   py37_0    conda-forge
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.6                h0371630_2  
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
regex                     2020.1.8                 pypi_0    pypi
requests                  2.22.0                   py37_1    conda-forge
sacrebleu                 1.4.3                    pypi_0    pypi
sacremoses                0.0.38                   pypi_0    pypi
setuptools                45.2.0                   py37_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
spacy                     2.2.3            py37hc9558a2_0    conda-forge
sqlite                    3.31.1               h7b6447c_0  
srsly                     1.0.0            py37he1b5a44_0    conda-forge
thinc                     7.3.0            py37hc9558a2_0    conda-forge
tk                        8.6.8                hbc83047_0  
torchvision               0.5.0                py37_cu101    pytorch
tqdm                      4.42.1                     py_0    conda-forge
typing                    3.7.4.1                  pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
wasabi                    0.6.0                      py_0    conda-forge
wheel                     0.34.2                   py37_0    conda-forge
xz                        5.2.4                h14c3975_4  
zipp                      2.2.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

Help please! Thank you!

cc @ailzhang

**Comment by sh1lpa** [comment]
I was trying to run simple single line code torch.hub.list(pytorch , fairseq) from fairseq repo 
got the similar error 
trying resolving using solution at  #2678
Traceback (most recent call last):
    torch.hub.list('pytorch/fairseq')  # [..., 'transformer.wmt16.en-de', ... ]
  File "/home/dlbox/anaconda3/lib/python3.6/site-packages/torch/hub.py", line 286, in list
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/dlbox/anaconda3/lib/python3.6/site-packages/torch/hub.py", line 75, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dlbox/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 33, in <module>
    raise RuntimeError('Missing dependencies: {}'.format(', '.join(missing_deps)))
RuntimeError: Missing dependencies: hydra-core

**Comment by koren-v** [comment]
The same

**Comment by ailzhang** [comment]
For missing dependency you'll need to pip install yourself. Hub doesn't only detects but don't install automatically. Closing, please feel free to reopen if you have any followup questions. 
`pip install -q hydra-core`
