### ISSUE TITLE
[feature request] Weight norm option for RNN cells

### ISSUE THREAD

**Issue by williamFalcon** [pytorch/pytorch#4578]
So, looks like [#1601](https://github.com/pytorch/pytorch/issues/1601) added weight norm to pytorch. However, what do you guys think about weightnorm within each RNN cell type that can be enabled through an option?   

Such as:    
```python    
 rnn = nn.RNN(10, 20, 2, weight_norm=True)
```   

The implementation would add weight norm to each of the weights within the cell hidden output (which you can do now if you run your own loop and add weightnorm at the output of each step, but not possible if you feed in the full sequence).    Paper reference "[RECURRENT BATCH NORMALIZATION](https://arxiv.org/pdf/1603.09025.pdf)"   

Or is there a way to do this already?    (happy to add if you guys think this is useful).

**Comment by SsnL** [comment]
You can already achieve it now. For instance,
```
>>> rnn = nn.RNN(10,10,2)  # build an RNN
>>> nn.utils.weight_norm(rnn, 'weight_hh_l0')  # apply weight_norm to any particular weight you want
```

**Comment by SsnL** [comment]
I believe the reason is that WN is not as widely used as the other options
you mentioned. If it becomes a standard thing, it would make more sense to
support this. However, if you need this often in your project, you can
still easily write a simple function that returns such modules with WN
enabled.

**Comment by harikrishnavydana** [comment]
@SsnL @williamFalcon 
is this the correct way for adding weight normalization to LSTMS


       self.blstm1 = nn.LSTM(self.input_size,self.hidden_size, 1,batch_first=True,bidirectional=True).cuda()
      self.blstm1=wtnrm(wtnrm(self.blstm1,'weight_ih_l0'),'weight_hh_l0')
      self.blstm1=wtnrm(wtnrm(self.blstm1,'weight_ih_l0_reverse'),'weight_hh_l0_reverse')

**Comment by williamFalcon** [comment]
@SsnL  
```python 
lstm = weight_norm(nn.LSTM(30, 100, num_layers=2, batch_first=True)) 
```

**Comment by PetrochukM** [comment]
When applying weight normalization to an LSTM, shouldn't we be applying it to each weight vector separately? The current approach makes that difficult.

**Comment by PetrochukM** [comment]
Never mind, the basic use case looks like it has bugs:
```
Traceback (most recent call last):
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/opt/wellsaid-labs/Text-to-Speech/src/bin/train/spectrogram_model/__main__.py", line 141, in _train
    trainer = (Trainer.from_checkpoint if checkpoint else Trainer)(**trainer_kwargs)
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/hparams/hparams.py", line 574, in decorator
    return function(*args, **kwargs)
  File "/opt/wellsaid-labs/Text-to-Speech/src/bin/train/spectrogram_model/trainer.py", line 118, in __init__
    self.model.to(device)
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 124, in _apply
    self.flatten_parameters()
  File "/opt/wellsaid-labs/Text-to-Speech/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 120, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: No function is registered for schema aten::_cudnn_rnn_flatten_weight(Tensor[] weight_arr, int weight_stride0, int input_size, 
int mode, int hidden_size, int num_layers, bool batch_first, bool bidirectional) -> Tensor on backend CPU
```
