### ISSUE TITLE
DISABLED test_backward_python_udf_error (__main__.TensorPipeDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#45846]
```
Oct 03 06:32:41 ======================================================================
Oct 03 06:32:41 ERROR [1.738s]: test_backward_python_udf_error (__main__.TensorPipeDistAutogradTestWithSpawn)
Oct 03 06:32:41 ----------------------------------------------------------------------
Oct 03 06:32:41 Traceback (most recent call last):
Oct 03 06:32:41   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in wrapper
Oct 03 06:32:41     self._join_processes(fn)
Oct 03 06:32:41   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 373, in _join_processes
Oct 03 06:32:41     self._check_return_codes(elapsed_time)
Oct 03 06:32:41   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 409, in _check_return_codes
Oct 03 06:32:41     raise RuntimeError(error)
Oct 03 06:32:41 RuntimeError: Processes 0 exited with error code 10
Oct 03 06:32:41 
Oct 03 06:32:41 ----------------------------------------------------------------------
```

```
Oct 03 06:21:23   test_backward_python_udf_error (__main__.TensorPipeDistAutogradTestWithSpawn) ... /opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)
Oct 03 06:21:23   return torch._C._cuda_getDeviceCount() > 0
Oct 03 06:21:23 ERROR:root:Caught exception: 
Oct 03 06:21:23 RuntimeError: Error on Node 2: Error on Node 3: could not compute gradients for some functions
Oct 03 06:21:23 
Oct 03 06:21:23 During handling of the above exception, another exception occurred:
Oct 03 06:21:23 
Oct 03 06:21:23 Traceback (most recent call last):
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 259, in wrapper
Oct 03 06:21:23     fn()
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Oct 03 06:21:23     return_value = old_test_method(self, *arg, **kwargs)
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1420, in test_backward_python_udf_error
Oct 03 06:21:23     dist_autograd.backward(context_id, [loss.sum()])
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/unittest/case.py", line 217, in __exit__
Oct 03 06:21:23     expected_regex.pattern, str(exc_value)))
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
Oct 03 06:21:23     raise self.test_case.failureException(msg)
Oct 03 06:21:23 AssertionError: "Simulate error on backward pass" does not match "Error on Node 2: Error on Node 3: could not compute gradients for some functions"
Oct 03 06:21:23 exiting process with exit code: 10
Oct 03 06:21:23 /opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)
Oct 03 06:21:23   return torch._C._cuda_getDeviceCount() > 0
Oct 03 06:21:23 ERROR:root:Caught exception: 
Oct 03 06:21:23 RuntimeError: Error on Node 0: Error on Node 1: Error on Node 2: 'NoneType' object is not callable
Oct 03 06:21:23 
Oct 03 06:21:23 During handling of the above exception, another exception occurred:
Oct 03 06:21:23 
Oct 03 06:21:23 Traceback (most recent call last):
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 259, in wrapper
Oct 03 06:21:23     fn()
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Oct 03 06:21:23     return_value = old_test_method(self, *arg, **kwargs)
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1420, in test_backward_python_udf_error
Oct 03 06:21:23     dist_autograd.backward(context_id, [loss.sum()])
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/unittest/case.py", line 217, in __exit__
Oct 03 06:21:23     expected_regex.pattern, str(exc_value)))
Oct 03 06:21:23   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
Oct 03 06:21:23     raise self.test_case.failureException(msg)
Oct 03 06:21:23 AssertionError: "Simulate error on backward pass" does not match "Error on Node 0: Error on Node 1: Error on Node 2: 'NoneType' object is not callable"
Oct 03 06:21:23 exiting process with exit code: 10
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby @agolynski

**Comment by lw** [comment]
Do you have a CircleCI link for this?

I am a bit surprised to see lines such as these in the logs:
```
Oct 03 06:21:23 /opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)
Oct 03 06:21:23   return torch._C._cuda_getDeviceCount() > 0
Oct 03 06:21:23 ERROR:root:Caught exception: 
Oct 03 06:21:23 RuntimeError: Error on Node 0: Error on Node 1: Error on Node 2: 'NoneType' object is not callable
```
Does this perhaps mean we're trying to run tests that require CUDA on machines that have no GPUs available?

**Comment by pritamdamania87** [comment]
Closing this out for now since we don't have a circle ci link for this and I can't repro it locally.
