### ISSUE TITLE
DISABLED test_dist_optim_functional (__main__.ProcessGroupDistOptimizerTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#45845]
https://app.circleci.com/pipelines/github/pytorch/pytorch/222748/workflows/bdb3ac90-090d-4cdb-830a-b545dda0e2a8/jobs/7974440/steps

```
Oct 02 21:08:26 ======================================================================
Oct 02 21:08:26 ERROR [61.704s]: test_dist_optim_functional (__main__.ProcessGroupDistOptimizerTestWithSpawn)
Oct 02 21:08:26 ----------------------------------------------------------------------
Oct 02 21:08:26 Traceback (most recent call last):
Oct 02 21:08:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in wrapper
Oct 02 21:08:26     self._join_processes(fn)
Oct 02 21:08:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 373, in _join_processes
Oct 02 21:08:26     self._check_return_codes(elapsed_time)
Oct 02 21:08:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 409, in _check_return_codes
Oct 02 21:08:26     raise RuntimeError(error)
Oct 02 21:08:26 RuntimeError: Processes 1 2 exited with error code 10
Oct 02 21:08:26 
Oct 02 21:08:26 ----------------------------------------------------------------------
```

```
Oct 02 20:59:05   test_dist_optim_functional (__main__.ProcessGroupDistOptimizerTestWithSpawn) ... RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Oct 02 20:59:05 RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Oct 02 20:59:05 RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Oct 02 20:59:05 RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Oct 02 20:59:05 /opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py:132: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)
Oct 02 20:59:05   allow_unreachable=True)  # allow_unreachable flag
Oct 02 20:59:05 ERROR:root:Caught exception: 
Oct 02 20:59:05 Traceback (most recent call last):
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 259, in wrapper
Oct 02 20:59:05     fn()
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Oct 02 20:59:05     return_value = old_test_method(self, *arg, **kwargs)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 241, in test_dist_optim_functional
Oct 02 20:59:05     optim.Adagrad, [remote_param1, remote_param2], lr=0.05
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 197, in __init__
Oct 02 20:59:05     self.remote_optimizers = _wait_for_all(remote_optim_futs)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 112, in _wait_for_all
Oct 02 20:59:05     raise exception
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 107, in _wait_for_all
Oct 02 20:59:05     results.append(fut.wait())
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 177, in _handle_exception
Oct 02 20:59:05     raise result.exception_type(result.msg)
Oct 02 20:59:05 RuntimeError: On WorkerInfo(id=1, name=worker1):
Oct 02 20:59:05 RuntimeError("Can't redefine method: step on class: __torch__.torch.distributed.optim.optimizer._ScriptLocalOptimizer",)
Oct 02 20:59:05 Traceback (most recent call last):
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 164, in _run_function
Oct 02 20:59:05     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 91, in _new_script_local_optimizer
Oct 02 20:59:05     _ScriptLocalOptimizer(optim_cls, local_params_rref, *args, **kwargs), _ScriptLocalOptimizerInterface)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/jit/_script.py", line 210, in init_then_script
Oct 02 20:59:05     ] = torch.jit._recursive.create_script_module(self, make_stubs, share_types=not added_methods_in_init)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
Oct 02 20:59:05     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py", line 410, in create_script_module_impl
Oct 02 20:59:05     create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
Oct 02 20:59:05   File "/opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py", line 304, in create_methods_and_properties_from_stubs
Oct 02 20:59:05     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
Oct 02 20:59:05 RuntimeError: Can't redefine method: step on class: __torch__.torch.distributed.optim.optimizer._ScriptLocalOptimizer
Oct 02 20:59:05 
Oct 02 20:59:05 exiting process with exit code: 10
Oct 02 20:59:05 [E request_callback_no_python.cpp:581] Received error while processing request type 15: TypeError: 'NoneType' object is not callable
Oct 02 20:59:05 
Oct 02 20:59:05 At:
Oct 02 20:59:05   /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py(129): deserialize
Oct 02 20:59:05   /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py(150): deserialize
Oct 02 20:59:05 
Oct 02 21:00:05 /opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py:132: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)
Oct 02 21:00:05   allow_unreachable=True)  # allow_unreachable flag
Oct 02 21:00:05 ERROR:root:Caught exception: 
Oct 02 21:00:05 Traceback (most recent call last):
Oct 02 21:00:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 259, in wrapper
Oct 02 21:00:05     fn()
Oct 02 21:00:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Oct 02 21:00:05     return_value = old_test_method(self, *arg, **kwargs)
Oct 02 21:00:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 250, in test_dist_optim_functional
Oct 02 21:00:05     loss = torch.add(output2.wait(), t1)
Oct 02 21:00:05 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Oct 02 21:00:05 exiting process with exit code: 10
Oct 02 21:00:05 /opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py:132: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)
Oct 02 21:00:05   allow_unreachable=True)  # allow_unreachable flag
Oct 02 21:00:05 ERROR:root:Caught exception: 
Oct 02 21:00:05 Traceback (most recent call last):
Oct 02 21:00:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 259, in wrapper
Oct 02 21:00:05     fn()
Oct 02 21:00:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Oct 02 21:00:05     return_value = old_test_method(self, *arg, **kwargs)
Oct 02 21:00:05   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 255, in test_dist_optim_functional
Oct 02 21:00:05     new_w1 = rpc_async_method(MyModule.get_w, remote_module1).wait()
Oct 02 21:00:05 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
cc @wanchaol can this be relevant to the recent distributed optimizer chagnes?

**Comment by wanchaol** [comment]
taking a look now
