### ISSUE TITLE
Fix windows test skipped in test/test_serialization.py

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#45917]
Window tests was skipped in previous commits in test/test_serialization.py

Namely some tests are skipped with
```
@unittest.skipIf(IS_WINDOWS, "NamedTemporaryFile on windows")
```
However, Usage of `NamedTemporaryFile` in other test files are not skipped on windows. thus we should be able to re-enabled them.

cc @ezyang @gchanan @zou3519 @mruberry @VitalyFedyunin @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by mruberry** [comment]
Interesting. Let's try it?

**Comment by walterddr** [comment]
yes. I realized this during one test fix. will try to double back on this one later

**Comment by walterddr** [comment]
The tests are actually failing for windows with exception log:
```
Executing ['C:\\Jenkins\\Miniconda3\\python.exe', 'test_serialization.py', '--verbose'] ... [2020-10-07 00:50:36.825332]
Test results will be stored in test-reports\python-unittest

Running tests...
----------------------------------------------------------------------
  test_load_error_msg (__main__.TestBothSerialization) ... ok (1.175s)
  test_load_nonexistent_device (__main__.TestBothSerialization) ... skip (0.009s)
  test_load_python2_unicode_module (__main__.TestBothSerialization) ... ok (0.217s)
  test_load_unicode_error_msg (__main__.TestBothSerialization) ... ok (0.006s)
  test_serialization (__main__.TestBothSerialization) ... ok (0.007s)
  test_serialization_backwards_compat (__main__.TestBothSerialization) ... ok (0.133s)
  test_serialization_dill (__main__.TestBothSerialization) ... skip (0.011s)
  test_serialization_dill_version_not_supported (__main__.TestBothSerialization) ... skip (0.000s)
  test_serialization_fake_zip (__main__.TestBothSerialization) ... ERROR (0.003s)
  test_serialization_filelike (__main__.TestBothSerialization) ... ok (0.004s)
  test_serialization_filelike_api_requirements (__main__.TestBothSerialization) ... ok (0.002s)
  test_serialization_filelike_missing_attrs (__main__.TestBothSerialization) ... ok (0.002s)
  test_serialization_filelike_stress (__main__.TestBothSerialization) ... ok (0.646s)
  test_serialization_filelike_uses_readinto (__main__.TestBothSerialization) ... ok (0.012s)
  test_serialization_gzip (__main__.TestBothSerialization) ... ok (0.010s)
  test_serialization_map_location (__main__.TestBothSerialization) ... ok (2.371s)
  test_serialization_new_format_old_format_compat (__main__.TestBothSerialization) ... ok (0.129s)
  test_serialization_offset_gzip (__main__.TestBothSerialization) ... ok (0.006s)
  test_serialization_save_warnings (__main__.TestBothSerialization) ... ok (0.002s)
  test_serialization_sparse (__main__.TestBothSerialization) ... ERROR (0.003s)
  test_serialization_sparse_invalid (__main__.TestBothSerialization) ... ERROR (0.003s)
  test_serialization_storage_slice (__main__.TestBothSerialization) ... ok (0.002s)
  test_serialization_zipfile_utils (__main__.TestBothSerialization) ... ERROR (0.367s)
Traceback (most recent call last):
  File "run_test.py", line 778, in <module>
    main()
  File "run_test.py", line 761, in main
    raise RuntimeError(err_message)
RuntimeError: test_serialization failed!
```

i guess this is due to https://bugs.python.org/issue14243. but I am not 100% sure.

**Comment by peterjc123** [comment]
You may refer to https://stackoverflow.com/a/15235559.

**Comment by walterddr** [comment]
did a bit of research: `torch.save(..., filename)` will cause the file to be opened twice and it is not supported in windows, just like @peterjc123 mentioned. However seems like `torch.save(..., file_handler)` doesn't cause the same problem.

So tentative solution is to remove restriction by only accessing using file_handler (and skip those steps if requires path/filename access).
