### ISSUE TITLE
Reproducibility breaks down with weighted Cross Entropy loss

### ISSUE THREAD

**Issue by arsenzaryan** [pytorch/pytorch#46024]
Hello, the following code ceases to be reproducible when the weights in cross entropy are non-integers. Here’s the example:
```python
import numpy as np
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader


h, w, in_ch, out_ch = 32, 32, 3, 5
class Dtst(Dataset):
    def __init__(self, N=20):
        self.X = [torch.randn([in_ch, h, w], dtype=torch.float32) for _ in range(N)]
        self.Y = [torch.randint(low=0, high=out_ch, size=(h,w), dtype=torch.int64) for _ in range(N)]
        
    def __getitem__(self, ix):
        return self.X[ix], self.Y[ix]
    
    def __len__(self):
        return len(self.Y)


class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Conv2d(in_channels=in_ch, out_channels=10, kernel_size=3, padding=1)
        self.drop = nn.Dropout2d(p=0.1)
        self.layer2 = nn.Conv2d(in_channels=10, out_channels=out_ch, kernel_size=3, padding=1)

    def forward(self, x):
        out = self.layer2(self.drop(self.layer1(x)))
        return out

seed = 4
torch.backends.cudnn.enabled = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = True
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
np.random.seed(seed)

dtst = Dtst()
model = Network()

device = 'cuda'
model.to(device)
class_weights = ((torch.arange(out_ch)+1).type(torch.FloatTensor)**0.5).to(device)

loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)
opt = torch.optim.Adam(model.parameters())

preds_dict = dict()
for e in range(1500):
    dtldr = DataLoader(dtst, batch_size=4)
    for x,y in dtldr:
        preds = model(x.to(device))
        loss = loss_fn(preds, y.to(device))
        loss.backward()
        opt.step()

        preds_argmax = preds.argmax(dim=1).flatten()
        preds_dict.update(Counter(preds_argmax.tolist()))

print(sorted(preds_dict.items(), key=lambda x: x[1]))
print(model.layer1.weight.data.norm(2).item())
```

It’s a simple network with a very basic Dataset, and a simple train loop.
This code is not reproducible. But when I remove the (**0.5) part from the class_weights it becomes reproducible. I.e., if the class weight values are actual floats, not integers cast to floats, then the code is not reproducible.

Also, the problem exists only on cuda. If the device is set to ‘cpu’, the code is reproducible again!
I run this on Ubuntu 18. My environment is the following:
pytorch 1.6.0
cudatoolkit 10.1.243
numpy 1.19.1

P.S. I've already opened the same issue in pytorch forum ((https://discuss.pytorch.org/t/reproducibility-breaks-down-with-weighted-cross-entropy-loss/96632)) but since there is no answer there for a long time, thought maybe in will get more attention here.

**Comment by mruberry** [comment]
cc @kurtamohler, too, for the determinism issue.

Thanks for reporting this issue, @arsenzaryan. We'll take a look.

**Comment by yanz0920** [comment]
There are several possible points：
1. torch.backends.cudnn.benchmark = False
2. replace Adam to SGD

reference to https://www.learnopencv.com/ensuring-training-reproducibility-in-pytorch/
Good Luck！

**Comment by arsenzaryan** [comment]
@yanz0920 those suggestions don't help, I tried. Neither separately nor in combination. It seems there is something deeper here.
Thanks anyway

**Comment by kurtamohler** [comment]
The new `torch.set_deterministic(True)` function (which hasn't been released yet, as far as I know) sheds a little bit of light. When I run your script with that, I get this error:

```
Traceback (most recent call last):
  File "tmp.py", line 58, in <module>
    preds = model(x.to(device))
...
RuntimeError: Deterministic behavior was enabled with either `torch.set_deterministic(True)` or `at::Context::setDeterministic(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility
```

This error happens with some of the CUDA matrix multiply operations. When I set `CUBLAS_WORKSPACE_CONFIG=:4096:8`, this particular source of nondeterminism goes away. However, now I get another error:

```
Traceback (most recent call last):
  File "tmp.py", line 59, in <module>
    loss = loss_fn(preds, y.to(device))
  File "/home/endoplasm/develop/pytorch-new-full-requires-grad-36455/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/endoplasm/develop/pytorch-new-full-requires-grad-36455/torch/nn/modules/loss.py", line 961, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/endoplasm/develop/pytorch-new-full-requires-grad-36455/torch/nn/functional.py", line 2439, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/endoplasm/develop/pytorch-new-full-requires-grad-36455/torch/nn/functional.py", line 2237, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: SpatialClassNLLCriterion_updateOutput does not have a deterministic implementation, but you set 'torch.set_deterministic(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```

If I surround that loss_fn call with
```
torch.set_deterministic(False)
loss = loss_fn(preds, y.to(device))
torch.set_deterministic(True)
```

I don't get any more errors. So it seems likely that the nondeterminism in this script is coming from the fact that `torch._C._nn.nll_loss2d` is nondeterministic. However, it is possible that there are other sources of nondeterminism that we don't currently have error messages for.

**Comment by arsenzaryan** [comment]
isn't that a serious problem if ```torch._C._nn.nll_loss2d``` is nondeterministic? Or we should expect in the future that this is the normal behavior?

**Comment by mruberry** [comment]
How significant a numeric different are you seeing between each run?

Currently many operations in CUDA are technically nondeterministic because float addition is not actually commutative, and we don't typically try to ensure that floats are always added in the same order for performance reasons.

**Comment by arsenzaryan** [comment]
the difference is already considerable for the code above after only 1500 iterations. For real trainings where the number of iterations can be of order 100K, the difference between 2 'deterministic' runs is no better than for 2 non-deterministic runs.

**Comment by mruberry** [comment]
Over many runs the networks can diverge and the results will be very different. I'm curious what differences you're observing just calling the loss function with the same inputs again? Maybe your network is extremely sensitive to small differences?

**Comment by arsenzaryan** [comment]
my network is a pretty deep CNN with a loss consisting of sum of several terms, one of which is the weighted cross entropy. In two consecutive runs I observe a difference in loss already in the 3rd digit after 100 steps. But in case I use unweighted CE (as noted in the thread above) there is no difference even in the 16th digit of the loss.

**Comment by mruberry** [comment]
Interesting. I appreciate what you're saying. Per @kurtamohler's comment we should be sure that we've identified all sources of nondeterminism here. We are also interested in deterministic versions of nondeterministic operations, and we would probably take a PR implementing one. Otherwise, you may want to try using the experimental `set_deterministic` flag that @kurtamohler created and changing your program to rely on deterministic ops for the moment, if determinism is important.

**Comment by bwittmann** [comment]
Any updates on this? This seems to be still the case.
