### ISSUE TITLE
MNIST download error ..

### ISSUE THREAD

**Issue by etilelab** [pytorch/pytorch#46022]
- PyTorch Version (e.g., 1.0): torch==1.6.0
torchvision==0.7.0
 - OS (e.g., Linux): mac os
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7
 - CUDA/cuDNN version: none
 - GPU models and configuration: none

torch==1.6.0
torchvision==0.7.0

my source code
train_data = datasets.MNIST(root='data', train=True, transform=transforms.ToTensor(), download=True)

but. .. this error

/Users/itaegyeong/Desktop/projects/torch_test/venv/bin/python /Users/itaegyeong/Desktop/projects/torch_test/test.py
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "/Users/itaegyeong/Desktop/projects/torch_test/test.py", line 11, in <module>
    train_data = datasets.MNIST(root='data', train=True, transform=transforms.ToTensor(), download=True)
  File "/Users/itaegyeong/Desktop/projects/torch_test/venv/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
    self.download()
  File "/Users/itaegyeong/Desktop/projects/torch_test/venv/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 137, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/Users/itaegyeong/Desktop/projects/torch_test/venv/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 235, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/Users/itaegyeong/Desktop/projects/torch_test/venv/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 83, in download_url
    raise e
  File "/Users/itaegyeong/Desktop/projects/torch_test/venv/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 71, in download_url
    reporthook=gen_bar_updater()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1354, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

Why did you have this problem?

**Comment by mruberry** [comment]
Looks like the server hosting the dataset was unavailable when you tried to acquire it. This happens sometimes. Would you try again, maybe in a few days? You can also try and download the dataset from that sever directly and see if it works.

I'm going to close this for now since I expect it's not a PyTorch issue, but if you can access the dataset as expected but PyTorch is still failing please reopen it with an update.
