### ISSUE TITLE
Exception type changed when it's raised in backward operation

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#46088]
## 🐛 Bug

If there is an exception raised in the backward operation of custom function, PyTorch always raised RuntimeError and does not preserve the exception type.

## To Reproduce

    import torch

    class MyFunc(torch.autograd.Function):
        @staticmethod
        def forward(ctx, x):
            return x

        @staticmethod
        def backward(ctx, gradx):
            raise TypeError("this should be TypeError")

    a = torch.tensor(2.).requires_grad_()
    a1 = MyFunc.apply(a)
    print(torch.autograd.grad(a1, a))

The output:

    Traceback (most recent call last):
      File "test.py", line 14, in <module>
        print(torch.autograd.grad(a1, a))
      File "/home/mfkasim/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 192, in grad
        inputs, allow_unused)
    RuntimeError: this should be TypeError

It becomes `RuntimeError` despite it's specified as `TypeError`

## Expected behavior

The exception type should be conserved.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0+cpu
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.4
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

**Comment by ezyang** [comment]
This should be relatively "easy" to fix (although we may not have an idiomatic way to do this in the codebase). Would be a good starter task for someone looking to learn more about Python C API.

**Comment by albanD** [comment]
Hi,

Shouldn't this be solved by https://github.com/pytorch/pytorch/pull/43684 ?
Can you double check that this still happens on master by using a nightly build?
