### ISSUE TITLE
test_cat_cuda (__main__.TestTensorExprFuser) fails

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#46102]
## 🐛 Bug

`test_cat_cuda (__main__.TestTensorExprFuser)` fails

## To Reproduce

```
python test/test_tensorexpr.py TestTensorExprFuser.test_cat_cuda
```

```
======================================================================
ERROR: test_cat_cuda (__main__.TestTensorExprFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 828, in wrapper
    method(*args, **kwargs)
  File "test_tensorexpr.py", line 1048, in test_cat_cuda
    self._test_cat('cuda')
  File "test_tensorexpr.py", line 1036, in _test_cat
    x = warmup_and_run_forward(traced, *values)
  File "test_tensorexpr.py", line 42, in warmup_and_run_forward
    results = f(*args)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 127, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 124, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: UNSUPPORTED DTYPE
----------------------------------------------------------------------
```
## Expected behavior

no fail

## Environment

1.8.0a0+ 59414b3

## Additional context

A new failure found last night. https://github.com/pytorch/pytorch/pull/45788 might be related @eellison

**Comment by ngimel** [comment]
test_tensorexpr is not run in CI, due to --exclude-jit-executor. @ZolotukhinM, @Krovatkin is this expected to pass?

**Comment by ZolotukhinM** [comment]
Thanks for reporting, I'll take a look! "UNSUPPORTED DTYPE" is an indication of a bug in TE.

> test_tensorexpr is not run in CI, due to --exclude-jit-executor

Where is this option set (and do you know why?)?

**Comment by ngimel** [comment]
I don't know why. run_tests.py has a command-line option --exclude-jit-executor. When it is set, a number of tests (that depend on various profiling executor and fuser settings, test_tensorexpr is among them) are not run. In our regular cuda CI config, it is set, see e.g. here https://github.com/pytorch/pytorch/blob/be137e45cddf1f0b04ae7a6827a586ca4b3323f2/.jenkins/pytorch/test.sh#L135. 
I can repro the failure on devfair with the command given.

**Comment by ZolotukhinM** [comment]
The change to the test config seemed to be accidentally introduced in #45778.

**Comment by ZolotukhinM** [comment]
I was able to reproduce the failure too (among with some others), investigating now.

**Comment by ZolotukhinM** [comment]
Bisected the failure locally to #45789. Unfortunately, that change just made the tests more accurate, so it just exposed the bug. I plan to disable those tests for now and re-enable the CI, then come back to the failures themselves.

**Comment by ZolotukhinM** [comment]
I believe the real problem is this (I posted it as a separate issue in #46145 first but then realized that it'd be almost an exact duplicate of this issue):

> I suspect that the issue was introduced in #44972. When we start a fusion group from aten::cat we need to check that its input is prim::ListConstruct and pull into the group immediately. If we don't and rely on the usual logic to pull the ListConstruct node, it will fail to pass device checks - the output of the ListConstruct node has a type of Tensor[] from which we cannot deduce the device and have to conservatively bail.

**Comment by ZolotukhinM** [comment]
I think I know what's going on and luckily it seems like a minor problem. #45789 changed the default value of min size of a fusion group in our tests from 2 to 1 - it turns out we have a bug with how we handle `aten::cat` in this case.

When the min-size of fusion groups is set to 1, we create a fusion group as soon as we encounter a supported node. In other cases we wait for at least one more node to be present before we create a fusion group. For `aten::cat` we need a special handling since it always needs to be fused along with its input `ListConstruct`. Apparently, something went wrong with handling this special case when the fusion group was created for just `aten::cat`
