### ISSUE TITLE
Complex backward returns NaN values

### ISSUE THREAD

**Issue by jonashaag** [pytorch/pytorch#46155]
## 🐛 Bug

I am training this model: https://github.com/jonashaag/asteroid/blob/dccrn-recipe/asteroid/models/dccrnet.py

Tried PyTorch 1.6.x with CUDA 10.1 and PyTorch Nightly with CUDA 10.2. I can successfully train the model with CUDA 11.1 and PyTorch Nightly on another machine. I can't test CUDA 11.1 on the failing machine though.

## To Reproduce

Run https://github.com/jonashaag/asteroid/blob/dccrn-recipe/egs/dns_challenge/dccrn/run.sh, wait for ~100 batches -> crash

Unfortunately the autogenerated code snippet from PyTorch does not fail, and I don't have a minimal reproducing code.

```
  File "train.py", line 138, in main                                                                                                                                       [320/1659]
    trainer.fit(system)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 454, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 53, in train
    results = self.train_or_test()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/base_accelerator.py", line 50, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 501, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 527, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 662, in run_training_batch
    self.trainer.hiddens
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 741, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 302, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 61, in training_step
    output = self.__training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 69, in __training_step
    output = self.trainer.model.training_step(*args)
  File "/root/asteroid/asteroid/engine/system.py", line 116, in training_step
    loss, orig_loss = self.common_step(batch, batch_nb, train=True)
  File "/root/asteroid/asteroid/engine/system.py", line 93, in common_step
    est_targets = self(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/engine/system.py", line 66, in forward
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/models/base_models.py", line 248, in forward
    est_masks = self.masker(tf_rep)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/masknn/base.py", line 120, in forward
    return super().forward(x.unsqueeze(1))
  File "/root/asteroid/asteroid/masknn/base.py", line 39, in forward
    x = enc(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/masknn/convolutional.py", line 429, in forward
    return self.activation(self.norm(self.conv(x)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/complex_nn.py", line 129, in forward
    self.re_module(x.real) - self.im_module(x.imag),
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 390, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 387, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

Automated repo script (doesn't crash):

```
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([20, 1, 257, 186], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(1, 32, kernel_size=[5, 2], padding=[2, 0], stride=[2, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
```

```
ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [2, 0, 0]
    stride = [2, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x5588803927e0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 20, 1, 257, 186,
    strideA = 47802, 47802, 186, 1,
output: TensorDescriptor 0x5588808e1aa0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 20, 32, 129, 185,
    strideA = 763680, 23865, 185, 1,
weight: FilterDescriptor 0x558880392c00
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 32, 1, 5, 2,
Pointer addresses:
    input: 0x7f77c0353000
    output: 0x7f77d6000000
    weight: 0x7f7a2d600000
Forward algorithm: 1
```

When running with anomaly detection:

```
Warning: Error detected in StackBa
ckward. Traceback of forward call that caused the error:
  File "train.py", line 173, in <module>
    main(arg_dic)
  File "train.py", line 139, in main
    trainer.fit(system)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 454, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 53, in train
    results = self.train_or_test()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/base_accelerator.py", line 50, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 501, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 527, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 662, in run_training_batch
    self.trainer.hiddens
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 741, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 302, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 61, in training_step
    output = self.__training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 69, in __training_step
    output = self.trainer.model.training_step(*args)
  File "/root/asteroid/asteroid/engine/system.py", line 116, in training_step
    loss, orig_loss = self.common_step(batch, batch_nb, train=True)
  File "/root/asteroid/asteroid/engine/system.py", line 93, in common_step
    est_targets = self(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/engine/system.py", line 66, in forward
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/models/base_models.py", line 248, in forward
    est_masks = self.masker(tf_rep)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/masknn/base.py", line 120, in forward
    return super().forward(x.unsqueeze(1))
  File "/root/asteroid/asteroid/masknn/base.py", line 43, in forward
    x = dec(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/masknn/convolutional.py", line 480, in forward
    return self.activation(self.norm(self.deconv(x)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/asteroid/asteroid/complex_nn.py", line 104, in forward
    return as_torch_complex((self.re_module(x.real), self.im_module(x.imag)))
  File "/root/asteroid/asteroid/complex_nn.py", line 48, in as_torch_complex
    return torch.view_as_complex(torch.stack(x, dim=-1))

 (function _print_stack)
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main(arg_dic)
  File "train.py", line 139, in main
    trainer.fit(system)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 454, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 53, in train
    results = self.train_or_test()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/base_accelerator.py", line 50, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 501, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 527, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 662, in run_training_batch
    self.trainer.hiddens
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 748, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 278, in backward
    result.closure_loss = self.trainer.accelerator_backend.backward(result.closure_loss, optimizer, opt_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/base_accelerator.py", line 90, in backward
    model_ref.backward(self, closure_loss, optimizer, opt_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/hooks.py", line 357, in backward
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 227, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 138, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'StackBackward' returned nan values in its 0th output.
```

## Expected behavior

Should train with no crash

## Environment

(Oops, forgot to gather this data, and the machine is already de-provisioned...)

**Comment by glaringlee** [comment]
'high priority' since this caused unexpected crash

**Comment by ezyang** [comment]
cc @xwang233 who authored the convolution repro code, maybe you can figure out where the repro code generation is going wrong here.

**Comment by xwang233** [comment]
Hmm, I think the repro code generation is working normally since the generated code looks similar to the raw cuDNN inputs. It's just that the generated code can't reproduce the error for some unknown reasons. 

@jonashaag Thanks for reporting the issue. I'm a bit confused about your post as you mentioned two machines and three cuda versions. Would you double check the GPU model, CUDA version, and cuDNN version when you see the failure? You can also get these information with `python -m torch.utils.collect_env`.

**Comment by jonashaag** [comment]
It’s a 1080 Ti running CUDA 10.1 (PyTorch 1.6). I also tried 10.2 with nightly.

On a different machine that’s almost identical to the failing one (some OS, GPU) I can use CUDA 11.1 with nightly, there it works, but I don’t if it has anything to do with those versions in the first place. It could also be the that something is wrong with that machine. 

I can get you the exact versions used, and when (if) I can get my hand on the failing machine again I can try to get even more details, but I can’t guarantee to be able to reproduce it, sorry :(

**Comment by xwang233** [comment]
I think it's the cuDNN library that causes failure. CUDA 10.1 and 10.2 are very likely installed with cuDNN 7.6.5 in your system. Many bugs in 7.6.5 were fixed in cuDNN 8, which is usually installed with CUDA 11.0 or 11.1. It would be nice to check if the model is still failing in cuDNN 8 + cuda 11. Then, we can provide a fix if it still fails in the latest library versions.

**Comment by ezyang** [comment]
@xwang233 one alternate possible explanation is the problem is stride related. In the backtrace, I see:

```
    self.re_module(x.real) - self.im_module(x.imag),
```

x.real and x.imag are going to produce non-contiguous tensors.

**Comment by xwang233** [comment]
@ezyang , the cudnn raw inputs with dim and stride show that the input and output tensors are contiguous. I suggest that we wait @jonashaag to confirm the cudnn version. If the problem still exists in cudnn 8, I'll try a repro and let cudnn team fix the crash.

**Comment by jonashaag** [comment]
I just checked, the versions I used are as follows:

- PyTorch 1.6.x, CUDA 10.1, cuDNN 7.6.3
- PyTorch Nightly, CUDA 10.2, cuDNN 7.6.5
- PyTorch Nightly, CUDA 11.1, cuDNN 8.0.3

**Comment by anjali411** [comment]
Hi @xwang233 just checking in since we didn't hear back from you in a while

**Comment by xwang233** [comment]
Hi @anjali411 , since user is seeing worked behavior in cuda 11.1 and cudnn 8, should we just recommend new library versions? We may add patch to block those shapes from using cudnn in old versions, e.g. cudnn 7, if that's preferred.

**Comment by anjali411** [comment]
> We may add patch to block those shapes from using cudnn in old versions, e.g. cudnn 7, if that's preferred.

I think it would be preferable to clearly error out for old versions.

**Comment by anjali411** [comment]
@xwang233 any updates?

**Comment by xwang233** [comment]
cc @ngimel @ptrblck , what should we do to handle those cudnn convolution errors in cudnn 7, but fixed in cudnn 8?

> since user is seeing worked behavior in cuda 11.1 and cudnn 8, should we just recommend new library versions? We may add patch to block those shapes from using cudnn in old versions, e.g. cudnn 7, if that's preferred.

**Comment by ngimel** [comment]
If we know the shapes for which cudnn 7 produces silent wrong results we should either use native conv on them or error out. But I'm not sure you can get a good bug surface?

**Comment by malfet** [comment]
Removing the milestone as there seems to be no progress on the issue since Mar 2021
