### ISSUE TITLE
[FX]Add support for len() on Proxy

### ISSUE THREAD

**Issue by scottxu0730** [pytorch/pytorch#46210]
__len__ isn't defind on Proxy. Please add support for len() on Proxy.

**Comment by jamesr66a** [comment]
It looks like `len` does not support a user-defined class returning an object that is not coercible to an int. @huiguoo reported an error:

```
Traceback (most recent call last):
  File "len.py", line 12, in <module>
    traced = torch.fx.symbolic_trace(lt)
  File "/data/users/huiguo/pytorch/torch/fx/symbolic_trace.py", line 323, in symbolic_trace
    return GraphModule(root if isinstance(root, torch.nn.Module) else torch.nn.Module(), Tracer().trace(root))
  File "/data/users/huiguo/pytorch/torch/fx/symbolic_trace.py", line 301, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "len.py", line 5, in forward
    return len(x)
TypeError: 'Proxy' object cannot be interpreted as an integer
```

Tracing this back, the erroneous call-chain is:

1) builtin_len is the implementation of `len` and calls into `PyObject_Size`
https://github.com/python/cpython/blob/2085bd0877e17ad4d98a4586d5eabb6faecbb190/Python/bltinmodule.c#L1548

2) `PyObject_Size` eventually dispatches to `slot_sq_length`, which calls `PyNumber_Index` https://github.com/python/cpython/blob/47f075d96b9c205c6731f8599206172c3e209242/Objects/typeobject.c#L6074

3) `PyNumber_Index` type-checks the returned value and throws the witnessed error if it is not castable: https://github.com/python/cpython/blob/47f075d96b9c205c6731f8599206172c3e209242/Objects/abstract.c#L1266

For now, I think the course of action to take now is:

1) Move the behavior (i.e. emitting `call_function` to `builtins.len`) into a new function (`torch.fx.len(item : Any) -> Union[Proxy, int]` for example). If the input type is not a `Proxy`, just return `len(item)` directly. Otherwise, emit the call to `call_function` and return the corresponding `Proxy`
2) Make `Proxy.__len__` throw an error guiding the user to replace their call to `len` with a call to `torch.fx.len`

This will be similar to the `torch.assert` workaround we use for assert statements. In the long term, it would be nice if we could swap out `len` for `torch.fx.len` automatically, but I think and explicit error message is fine for now.
