### ISSUE TITLE
Variables are behaving strangely for indexing

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#4623]
In python2:

```python
import torch

a = torch.autograd.Variable(torch.ones(50))

i = torch.IntTensor([[5, 10]])
j = torch.autograd.Variable(i)

for x0, x1 in i:
    print(a[x0:x1].size())
# expectedly:
# (5,)

# Case 1. If uncommented produces the exception below:
# x0, x1 = j[0]
# print(a[x0:x1].size())
# wat? why zero? and where does the exception come from?
#(0,)
#Traceback (most recent call last):
#  File "bug.py", line 14, in <module>
#    for x0, x1 in j:
#TypeError: slice indices must be integers or None or have an __index__ method

# Case 2
for x0, x1 in j:
    print('print1', x0, x1)
    print('print2', x0, x1, 'is:', a[x0:x1].size())

# ok, this is known due to variable[0] is always a variable
#('print1', Variable containing:
# 5
#[torch.IntTensor of size 1]
#, Variable containing:
# 10
#[torch.IntTensor of size 1]
#)

# mega-wat?
#('print2', Traceback (most recent call last):
#  File "bug.py", line 13, in <module>
#    print('print2', x0, x1, 'is:', a[x0:x1].size())
#  File ".../python2.7/site-packages/torch/autograd/variable.py", line 73, in __repr__
#    return 'Variable containing:' + self.data.__repr__()
#  File ".../python2.7/site-packages/torch/tensor.py", line 144, in __repr__
#    return str(self)
#  File ".../python2.7/site-packages/torch/tensor.py", line 150, in __str__
#    if sys.version_info > (3,):
#TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by colesbury** [comment]
One problem is the slice parsing code didn't properly handle the error return. That caused the weird error messages.

The other problem is that `Variable` doesn't implement `__index__` so you can't use Variables as slice indices.

**Comment by vadimkantorov** [comment]
@colesbury Thanks for looking into it. The error messages popping seemingly after execution of the offending code were indeed strange.

**Comment by soumith** [comment]
#4732 is merged now.
