### ISSUE TITLE
test_distributed_* does not show error details from the subprocess

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#46276]
I tried explicitly raise an error in the test function, below is what I got when I use `pytest -kvs`. It only shows the error code, which is not helpful for debugging.

```
____________________________________________ DistributedDataParallelTest.test_gloo_backend_cpu_module_grad_is_view ____________________________________________$
torch/testing/_internal/common_distributed.py:267: in wrapper
    self._join_processes(fn)
torch/testing/_internal/common_distributed.py:384: in _join_processes
    self._check_return_codes(elapsed_time)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_c10d.DistributedDataParallelTest testMethod=test_gloo_backend_cpu_module_grad_is_view>, elapsed_time = 0.10043525695800781

    def _check_return_codes(self, elapsed_time):
        """
        Checks that the return codes of all spawned processes match, and skips
        tests if they returned a return code indicating a skipping condition.
        """
        first_process = self.processes[0]
        # first, we check if there are errors in actual processes
        # (via TEST_ERROR_EXIT CODE), and raise an exception for those.
        # the reason we do this is to attempt to raise a more helpful error
        # message than "Process x terminated/timed out"
        # TODO: we should pipe the exception of the failed subprocess here.
        # Currently, the actual exception is displayed as a logging output.
        errored_processes = [
            (i, p)
            for i, p in enumerate(self.processes)
            if p.exitcode == MultiProcessTestCase.TEST_ERROR_EXIT_CODE
        ]
        if errored_processes:
            error = "Processes {} exited with error code {}".format(
                " ".join([str(i) for (i, _) in errored_processes]),
                MultiProcessTestCase.TEST_ERROR_EXIT_CODE,
            )
>           raise RuntimeError(error)
E           RuntimeError: Processes 0 1 exited with error code 10

torch/testing/_internal/common_distributed.py:420: RuntimeError
```

**Comment by rohan-varma** [comment]
It looks like this issue might be specific to `pytest` as I was able to use the OSS test runner as follows: `python test/run_test.py --verbose -i distributed/test_distributed_fork`.

And I was able to see the raised error, such as:
```
Fail to import hypothesis in common_utils, tests are not derandomized
test_Backend_enum_class (__main__.TestDistBackendWithFork) ... ERROR:root:Caught exception:
Traceback (most recent call last):
  File "/home/rvarm1/pytorch/torch/testing/_internal/common_distributed.py", line 259, in wrapper
    fn()
  File "/home/rvarm1/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 442, in test_Backend_enum_class
    raise ValueError("intentional error")
ValueError: intentional error
exiting process with exit code: 10
ERROR:root:Caught exception:
Traceback (most recent call last):
  File "/home/rvarm1/pytorch/torch/testing/_internal/common_distributed.py", line 259, in wrapper
    fn()
  File "/home/rvarm1/pytorch/torch/testing/_internal/distributed/distributed_test.py", line 442, in test_Backend_enum_class
    raise ValueError("intentional error")
ValueError: intentional error
exiting process with exit code: 10
Process 1 terminated with exit code 10, terminating remaining processes.
ERROR
```

Not sure why it doesn't work the same for pytest or if there is a way to specify the specific test without pytest.
