### ISSUE TITLE
v1.7.0-rc1 4 data loader test failures: unexpected keyword argument 'persistent_workers'

### ISSUE THREAD

**Issue by choidongyeon** [pytorch/pytorch#46297]
## 🐛 Bug

There are four test failures when running `test_dataloader.py`, all of them are related to `persistent_workers`. I don't have enough context on this right now to understand what's up. Are there plans to fix this before 1.7.0 is officially released?

## To Reproduce

`python test_dataloader.py`

```
======================================================================
FAIL: test_proper_exit (__main__.TestDataLoader)
There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda3/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 387, in wrapper
    fn(*args, **kwargs)
  File "test_dataloader.py", line 1579, in test_proper_exit
    self.fail(fail_msg)
AssertionError: test_proper_exit with is_iterable_dataset=True, use_workers=True, pin_memory=False, hold_iter_reference=True, exit_method=None: loader process failed to setup within given time, and had exception Traceback (most recent call last):
  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 361, in run
    super(ErrorTrackingProcess, self).run()
  File "//anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 591, in _test_proper_exit
    persistent_workers=persistent_workers)
TypeError: __init__() got an unexpected keyword argument 'persistent_workers'


======================================================================
FAIL: test_timeout (__main__.TestDataLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataloader.py", line 970, in test_timeout
    self.assertIsInstance(p.exception, RuntimeError)
AssertionError: TypeError('Traceback (most recent call last):\n  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 361, in run\n    super(ErrorTrackingProcess, self).run()\n  File "//anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 494, in _test_timeout\n    persistent_workers=persistent_workers)\nTypeError: __init__() got an unexpected keyword argument \'persistent_workers\'\n',) is not an instance of <class 'RuntimeError'>

======================================================================
FAIL: test_proper_exit (__main__.TestDataLoaderPersistentWorkers)
There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda3/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 387, in wrapper
    fn(*args, **kwargs)
  File "test_dataloader.py", line 1579, in test_proper_exit
    self.fail(fail_msg)
AssertionError: test_proper_exit with is_iterable_dataset=True, use_workers=True, pin_memory=False, hold_iter_reference=True, exit_method=None: loader process failed to setup within given time, and had exception Traceback (most recent call last):
  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 361, in run
    super(ErrorTrackingProcess, self).run()
  File "//anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 591, in _test_proper_exit
    persistent_workers=persistent_workers)
TypeError: __init__() got an unexpected keyword argument 'persistent_workers'


======================================================================
FAIL: test_timeout (__main__.TestDataLoaderPersistentWorkers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataloader.py", line 970, in test_timeout
    self.assertIsInstance(p.exception, RuntimeError)
AssertionError: TypeError('Traceback (most recent call last):\n  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 361, in run\n    super(ErrorTrackingProcess, self).run()\n  File "//anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File "/Users/choidong/opensource/pytorch/test/test_dataloader.py", line 494, in _test_timeout\n    persistent_workers=persistent_workers)\nTypeError: __init__() got an unexpected keyword argument \'persistent_workers\'\n',) is not an instance of <class 'RuntimeError'>

----------------------------------------------------------------------
Ran 128 tests in 146.626s

FAILED (failures=4, errors=71, skipped=11)
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @SsnL @VitalyFedyunin @ejguan @mruberry

**Comment by SsnL** [comment]
Did you uninstall old versions?

**Comment by heitorschueroff** [comment]
I could not repro the error above but instead I get `fixture 'worker_id' not found` error for test method `test_worker_info_init_fn`. And test method `test_proper_exit` keeps alternating between worker error and loader error.

**Comment by ejguan** [comment]
Agree with @SsnL.
Cleaning up the environment will solve the issue, since persistent_workers is just introduced to 1.7.0

**Comment by ejguan** [comment]
> I could not repro the error above but instead I get `fixture 'worker_id' not found` error for test method `test_worker_info_init_fn`. And test method `test_proper_exit` keeps alternating between worker error and loader error.

I think we explicitly introduce the `worker_error` and `loader_error` to check if the `DataLoader` can exit properly.

**Comment by choidongyeon** [comment]
Hi @SsnL, thanks for the advice - I created a new conda env to test this out again and do not run into the issue anymore. Thank you for the explanation @ejguan ! Closing issue.
