### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.version'

### ISSUE THREAD

**Issue by shitian-ni** [pytorch/pytorch#4650]
Error import torch after `conda install pytorch torchvision -c pytorch`

```
(pytorch-py3.6) root@0a7c92d23653:/workspace/pytorch# pip freeze | grep torch
torch==0.3.0.post4
torchtext==0.2.0
torchvision==0.1.9
(pytorch-py3.6) root@0a7c92d23653:/workspace/pytorch# python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/pytorch/torch/__init__.py", line 14, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'torch.version'
```
My hardware is AWS p3.2xlarge.
Using nvidia GPU cloud pytorch docker.
Trying to update exisiting pytorch version.

**Comment by lanpa** [comment]
Are you under pytorch source directory?

**Comment by apaszke** [comment]
It looks like you are. Change the directory and you should be good.
