### ISSUE TITLE
torch script error for fairseq language model

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#46517]
❓ Questions and Help
export_pt.py ：
model = load_model_ensemble_and_task([args.input_model])[0][0]
model.eval()
model_dict = model.decoder.dictionary
generator = SequenceGenerator([model], model_dict, beam_size=args.beam_size)
scripted_generator = torch.jit.script(generator)
scripted_generator.save(args.output_model)

But the following problem occurs：

File "export_pt.py", line 62, in
main()
File "export_pt.py", line 55, in main
return create_script_module(nn_module, infer_methods_to_compile(nn_module))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
Traceback (most recent call last):
scripted_generator = torch.jit.script(generator)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/init.py", line 1255, in script
return torch.jit._recursive.recursive_script(obj)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/init.py", line 1593, in _construct
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
return create_script_module(nn_module, infer_methods_to_compile(nn_module))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
File "/usr/local/lib/python3.6/dist-packages/torch/jit/init.py", line 1593, in _construct
scripted = recursive_script(orig_value)
return create_script_module(nn_module, infer_methods_to_compile(nn_module))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 493, in infer_methods_to_compile
stubs.append(make_stub_from_method(nn_module, method))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 40, in make_stub_from_method
ast = torch.jit.get_jit_def(func, self_name="RecursiveScriptModule")
File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 171, in get_jit_def
return build_def(ctx, py_ast.body[0], type_line, self_name)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 223, in build_param_list
"""
Run the forward pass for a decoder-only model.
init_fn(script_module)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 328, in init_fn
scripted = recursive_script(orig_value)
script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
init_fn(script_module)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 328, in init_fn
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
return make_stub(func)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 33, in make_stub
File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 201, in build_def
param_list = build_param_list(ctx, py_def.args, self_name)
raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
File "/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py", line 435
def forward(self, src_tokens, **kwargs):
~~~~~~~ <--- HERE


How can i solve this problem？

cc @gmagogsfm

**Comment by wconstab** [comment]
@ismymajia Could you help us out with a more detailed repro? it looks like only part of the relevant code is pasted.  If this pertains to an internal task/diff you could post the number here for the sake of clarity.

**Comment by ismymajia** [comment]
1. The export_pt.py file is as follows ：

import torch
from fairseq.checkpoint_utils import load_model_ensemble_and_task
from fairseq.sequence_generator import SequenceGenerator
model = load_model_ensemble_and_task([args.input_model])[0][0]
model.eval()
model_dict = model.decoder.dictionary
generator = SequenceGenerator([model], model_dict, beam_size=args.beam_size)
scripted_generator = torch.jit.script(generator)
scripted_generator.save(args.output_model)

2. Run export_pt.py and  the following problem occurs：

File "export_pt.py", line 62, in
main()
File "export_pt.py", line 55, in main
return create_script_module(nn_module, infer_methods_to_compile(nn_module))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
Traceback (most recent call last):
scripted_generator = torch.jit.script(generator)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/init.py", line 1255, in script
return torch.jit._recursive.recursive_script(obj)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/init.py", line 1593, in _construct
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
return create_script_module(nn_module, infer_methods_to_compile(nn_module))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
File "/usr/local/lib/python3.6/dist-packages/torch/jit/init.py", line 1593, in _construct
scripted = recursive_script(orig_value)
return create_script_module(nn_module, infer_methods_to_compile(nn_module))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 493, in infer_methods_to_compile
stubs.append(make_stub_from_method(nn_module, method))
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 40, in make_stub_from_method
ast = torch.jit.get_jit_def(func, self_name="RecursiveScriptModule")
File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 171, in get_jit_def
return build_def(ctx, py_ast.body[0], type_line, self_name)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 223, in build_param_list
"""
Run the forward pass for a decoder-only model.
init_fn(script_module)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 328, in init_fn
scripted = recursive_script(orig_value)
script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
init_fn(script_module)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 328, in init_fn
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
return make_stub(func)
File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 33, in make_stub
File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 201, in build_def
param_list = build_param_list(ctx, py_def.args, self_name)
raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
File "/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py", line 435
def forward(self, src_tokens, **kwargs):


3.  The above error is specifically fairseq_model.py#L464
https://github.com/pytorch/fairseq/blob/a48f235636557b8d3bc4922a6fa90f3a0fa57955/fairseq/models/fairseq_model.py#L464

How to solve it ？

@wconstab

**Comment by AtomLee4279** [comment]
Me toooooo~~~hurry up!! I'm waiting for all of your answers!!~

**Comment by suo** [comment]
Hi, TorchScript is a statically typed language and thus cannot take `**kwargs` as an input. This seems like a gap in fairseq's support for scripting their models—I suggest making an issue there to follow up with them about it. Thanks!

cc. @myleott for who the right person to route this to is. Going to close this issue out for now as it isn't particularly actionable on our end, but feel free to reopen or comment with any questions.
