### ISSUE TITLE
Pytorch+ROCm+Archlinux: build stopped when Build CXX object test_api/CMakeFiles/test_api.dir/modules.cpp.o

### ISSUE THREAD

**Issue by izypd** [pytorch/pytorch#46528]
## 🐛 Bug

Hello! I am trying to build Pytorch 1.7.0rc2 in Archlinux. But build stopped when Build CXX object test_api/CMakeFiles/test_api.dir/modules.cpp.o

## To Reproduce

1.install Archlinux or EndeavourOS.
2.[add arch4edu to your Archlinux](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux)
3.run `yay -S rocm-dev rocm-utils rocm-libs rccl` then `yay -S python-pytorch-opt-rocm` in console

Error code as so:
```
[4489/4848] Linking CXX shared library lib/libtorch_hip.so
FAILED: lib/libtorch_hip.so 
: && /usr/bin/c++ -fPIC -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG  -Wl,--no-as-needed -rdynamic -shared -Wl,-soname,libtorch_hip.so -o lib/libtorch_hip.so caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHReduceApplyUtils.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/
```
code is too long, so I skip some.
```
CMakeFiles/torch_hip.dir/__/torch/csrc/jit/tensorexpr/cuda_codegen.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/cuda/nccl.cpp.o  -Wl,-rpath,/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc2-rocm/build/lib:/opt/rocm/hip/lib:/opt/rocm/miopen/lib:/opt/rocm/rccl/lib:/opt/rocm/roctracer/lib:/opt/rocm/rocblas/lib:/opt/rocm/rocfft/lib:/opt/rocm/hiprand/lib:/opt/rocm/hipsparse/lib:/opt/intel/mkl/lib/intel64:/opt/rocm/lib:/opt/rocm/rocrand/lib:/usr/lib/openmpi:  lib/libc10_hip.so  /opt/rocm/hip/lib/libamdhip64.so  /opt/rocm/miopen/lib/libMIOpen.so  /opt/rocm/rccl/lib/librccl.so  /opt/rocm/hip/lib/libamdhip64.so  /opt/rocm/roctracer/lib/libroctx64.so  /opt/rocm/rocblas/lib/librocblas.so.0.1  /opt/rocm/rocfft/lib/librocfft.so.0.1  /opt/rocm/hiprand/lib/libhiprand.so.1.1  /opt/rocm/hipsparse/lib/libhipsparse.so.0.1  lib/libgloo_hip.a  lib/libc10.so  -Wl,--no-as-needed,"/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc2-rocm/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobuf.a  /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so  /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so  /opt/intel/mkl/lib/intel64/libmkl_core.so  -fopenmp  /usr/lib/libpthread.so  -lm  /usr/lib/libdl.so  lib/libdnnl.a  -pthread  -ldl  /opt/rocm/hip/lib/libamdhip64.so.3.8.20413-  -L/opt/rocm/llvm/lib/clang/11.0.0/include/../lib/linux  -lclang_rt.builtins-x86_64  /opt/rocm/hip/lib/libamdhip64.so  lib/libgloo.a  /usr/lib/openmpi/libmpi_cxx.so  /usr/lib/openmpi/libmpi.so  -lpthread  -Wl,-rpath-link,/opt/rocm/lib:/opt/rocm/rocfft/lib:/opt/rocm/rocrand/lib && :
c++: error: -E or -x required when input is from standard input
```
and build stopped after the code below
```
[4500/4848] Building CXX object test_api/CMakeFiles/test_api.dir/modules.cpp.o
cc1plus: 警告：command-line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
cc1plus: 附注：unrecognized command-line option ‘-Wno-implicit-int-float-conversion’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-unused-command-line-argument’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-exceptions’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-inconsistent-missing-override’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-macro-redefined’ may have been intended to silence earlier diagnostics
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    build_deps()
  File "setup.py", line 308, in build_deps
    build_caffe2(version=version,
  File "/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc2-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc2-rocm/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc2-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 1.
```
## Expected behavior

Build pytorch sucessfuly.

## Environment

 - PyTorch Version : 1.7.0rc2
 - OS : Archlinux
 - How you installed PyTorch : source
 - Build command you used (if compiling from source): `yay -S python-pytorch-opt-rocm`
 - Python version: 3.8.5
 - CUDA/cuDNN version: not CUDA, is ROCm 3.8.0
 - GPU models and configuration: Radeon VII

cc @malfet @seemethere @walterddr @jeffdaily @sunway513

**Comment by acxz** [comment]
This issue has been fixed with the latest Arch package, @izypd I believe you can close this issue.
