### ISSUE TITLE
ModuleNotFoundError when installing PyTorch via pip on aarch64 environment

### ISSUE THREAD

**Issue by jo7ueb** [pytorch/pytorch#46522]
## 🐛 Bug

Couldn't install PyTorch via pip. It's critical.

## To Reproduce

1. ` python3 -m pip install --no-binary torch torch`

Here's output.
```
root@pynq:~# python3 -m pip install --no-binary torch torch
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from torch) (3.12)
Skipping wheel build for torch, due to binaries being disabled for it.
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fh45j_29/torch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fh45j_29/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-857uyf6r/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/torch
         cwd: /tmp/pip-install-fh45j_29/torch/
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fh45j_29/torch/setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-fh45j_29/torch/setup.py", line 99, in run
        self.run_command('build_deps')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-fh45j_29/torch/setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fh45j_29/torch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fh45j_29/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-857uyf6r/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/torch Check the logs for full command output.
```

## Expected behavior

Install succeeds.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 429, in <module>
    main()
  File "collect_env.py", line 424, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 419, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 276, in get_env_info
    if torch.version.hip is None:  # cuda version
NameError: name 'torch' is not defined
```

 - PyTorch Version (e.g., 1.0): latest
 - OS (e.g., Linux): Linux pynq 4.19.0-xilinx-v2019.1 #1 SMP Sat Oct 12 00:54:10 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: Python 3.6.5
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: Ultra96-V2 board

**Comment by jo7ueb** [comment]
I tried as [official document](https://pytorch.org/get-started/locally/) says.
Also I got an error.

```
root@pynq:~# python3 -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.6.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.6.0+cpu
```

**Comment by jo7ueb** [comment]
Content on PyPI might be wrong?

**Comment by ezyang** [comment]
Your original command is failing because it is picking up an ancient version of PyTorch. We don't generally support installing from source from PyPI. I recommend getting a source tarball and building from source for ARM.

Releng crew is CC'ed as this is effectively a feature request for aarch64 official binaries.

**Comment by jo7ueb** [comment]
@ezyang 

> We don't generally support installing from source from PyPI.

Simply why?

>  I recommend getting a source tarball and building from source for ARM.
I just want to build with pip.
This is usual way to install python package!

**Comment by jo7ueb** [comment]
Anyway, thanks for the comment.

**Comment by ezyang** [comment]
Oh, good news, I learned yesterday that 1.7 we will start providing official ARM64 binaries, so that's another option.

@soumith do you remember why we stopped providing source dists on pypi? I think the reason is that for most people it will take several hours to finish building PyTorch (and chances are they don't have all the toolchain they need either), so it's almost certainly not the right fallback when no package is available.

**Comment by soumith** [comment]
@ezyang the number of dependencies and submodules we have is the first reason, the compile time is the second. we'd rather fail fast rather than take users through painful hell.

**Comment by jo7ueb** [comment]
@soumith @ezyang Thanks for the comment.
I understood there's some reason not to provide source dist on pypi.

If there's an error/warning message telling user to build manually, we can follow as instructed.
I suggest to implement some error/warning message instead.

Thanks.

**Comment by jo7ueb** [comment]
Marking related issues.
#27815 #34798 #42832 #41310 #19406 #37126 #40203 #37379 #29090 #29395 #29394 #28840

**Comment by ezyang** [comment]
I wonder if we can upload a fake source package that just errors when you try to build it. Maybe PyPI won't like that though...

**Comment by soumith** [comment]
there are some pypi packages that do that. in fact, we have such a fake package for `pip install pytorch`: https://pypi.org/project/pytorch/1.0.2/#files

The entire source is a setup.py (and some metadata) that look like this:

```
import sys
import webbrowser
from distutils.core import setup

message = 'You tried to install "pytorch". The package named for PyTorch is "torch"'

argv = lambda x: x in sys.argv

if (argv('install') or  # pip install ..
        (argv('--dist-dir') and argv('bdist_egg'))):  # easy_install
    raise Exception(message)


if argv('bdist_wheel'):  # modern pip install
    raise Exception(message)


setup(
    name='pytorch',
    version='1.0.2',
    maintainer='Soumith Chintala',
    maintainer_email='soumith@pytorch.org',
    long_description=message,
)

```

**Comment by ezyang** [comment]
@malfet seems like a good task to add to the infra list

**Comment by AshokBhat** [comment]
> Oh, good news, I learned yesterday that 1.7 we will start providing official ARM64 binaries, so that's another option.
Hi @ezyang, This is great news. Where are the binaries being hosted? Reason - I cannot seem to find Arm64 binaries in either 1.7 PyPI repo (https://pypi.org/project/torch/#files) or PyTorch wheel repo (https://download.pytorch.org/whl/torch_stable.html. )

**Comment by ezyang** [comment]
IIRC, ARM binaries were delayed for after the release, but IIRC we are still on track to release them.
