### ISSUE TITLE
Build 1.6 from source failed.

### ISSUE THREAD

**Issue by GeoffreyChen777** [pytorch/pytorch#46534]
I'm trying to build v1.6 on a POWER8 ppc64le machine.

CUDA 10.2
GCC 7.3 / 8.2

but I got plenty of errors:

<details>
........

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(877): error: template parameter "_UTypes" may not be redeclared in this scope

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(877): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(879): error: argument list for class template "std::tuple" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(879): error: "pair" is not a function or static data member

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(881): error: argument list for class template "std::tuple" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(881): error: expected a ")"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(881): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(883): error: argument list for class template "std::tuple" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(883): error: expected a ")"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(882): error: declaration is incompatible with template parameter "_UTypes"
(880): here

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(882): error: too many template parameters -- does not match previous declaration (declared
(880): here)

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(883): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(885): error: argument list for class template "std::tuple" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(885): error: expected a ")"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(884): error: declaration is incompatible with template parameter "_T1"
(882): here

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(884): error: too few template parameters -- does not match previous declaration (declared
(882): here)

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(885): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(899): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(901): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(969): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(980): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1066): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1077): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1089): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1099): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1109): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1115): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1119): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1128): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1140): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1152): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1162): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1173): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1183): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1193): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1203): error: argument list for variable template "std::allocator_arg_t" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/tuple(1626): error: inline specifier allowed on function declarations only

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(662): error: argument list for class template "std::function" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(662): error: expected a type specifier

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(662): error: function returning function is not allowed

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(662): error: template parameter "_Res" may not be redeclared in this scope

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(662): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(666): error: argument list for class template "std::function" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(666): error: template parameter "_Functor" may not be redeclared in this scope

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_function.h(666): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/optional(74): error: inline specifier allowed on function declarations only

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/optional(1035): error: argument list for class template "std::optional" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/optional(1035): error: too few template parameters -- does not match previous declaration (declared
/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/array(243): here)

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/optional(1035): error: expected a ";"

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h(360): error: argument list for class template "std::shared_ptr" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h(360): error: "weak_ptr" is not a function or static data member

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h(362): error: argument list for class template "std::shared_ptr" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h(362): error: "unique_ptr" is not a function or static data member

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h(589): error: argument list for class template "std::weak_ptr" is missing

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h(589): error: "shared_ptr" is not a function or static data member

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_mutex.h(142): error: inline specifier allowed on function declarations only

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_mutex.h(145): error: inline specifier allowed on function declarations only

/gpfs/home/wmg/wmrkwh/miniconda3/envs/geo/powerpc64le-conda_cos7-linux-gnu/include/c++/7.3.0/bits/std_mutex.h(148): error: inline specifier allowed on function declarations only

95 errors detected in the compilation of "/tmp/tmpxft_00018e1b_00000000-6_THCTensorIndex.cpp1.ii".
CMake Error at torch_cuda_generated_THCTensorIndex.cu.o.Release.cmake:281 (message):
  Error generating file
  /gpfs/home/wmg/wmrkwh/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensorIndex.cu.o

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 732, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/gpfs/home/wmg/wmrkwh/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/gpfs/home/wmg/wmrkwh/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/gpfs/home/wmg/wmrkwh/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/wmg/wmrkwh/miniconda3/envs/geo/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.
</details>

Any suggestions? Thanks!~

**Comment by GeoffreyChen777** [comment]
Rebuild GCC7.4 from source solved this error.
