### ISSUE TITLE
[jit] Support module dict operations when called inside ignore function

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#46549]
Some bugs underlying is causing the moduledict behave weird in `ignore` functions:

```python
import torch

class MyModule(torch.nn.Module):
    # module: torch.nn.ModuleDict
    def __init__(self):
        super().__init__()
        self.module = torch.nn.ModuleDict()
        self.module["AA"] = torch.nn.Linear(2, 2)

    @torch.jit.ignore
    def not_scripted(self, input):
        for name, module in self.module.items():
            return module(input)

    def forward(self, input):
        out = self.not_scripted(input)
        return out




input = torch.rand([2, 2])
print(input)
# scripted = torch.jit.script(MyModule())
scripted = torch.jit.script(MyModule())
scripted(input)
```

errors out like below
```
python /tmp/d.py
tensor([[0.0791, 0.3666],
        [0.9646, 0.1956]])
Traceback (most recent call last):
  File "/tmp/d.py", line 26, in <module>
    scripted(input)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/tmp/d.py", line 16, in forward
    def forward(self, input):
        out = self.not_scripted(input)
              ~~~~~~~~~~~~~~~~~ <--- HERE
        return out
RuntimeError: RuntimeError: __torch__.torch.nn.modules.container.ModuleDict does not have a field with name 'items'

At:
  /tmp/d.py(12): not_scripted
  /opt/anaconda3/lib/python3.7/site-packages/torch/jit/_recursive.py(614): lazy_binding_method
  /opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(550): __call__
  /tmp/d.py(26): <module>
```

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
I investigated this and the issue is that `self.module` is scripted, even when accessed in an ignored function. The interface for `ScriptModule` doesn't have `items()` because it is used for all scripted modules, even those that are not `ModuleDicts`. I found this workaround:

```
    @torch.jit.ignore
    def not_scripted(self, input):
        if isinstance(self.module, torch._C.ScriptModule):
            # When called from TorchScript
            # Wrap the ModuleDict in Python wrapper. This will expose _modules member as a torch.jit._script.OrderedModuleDict
            wrapped = torch.jit._recursive.wrap_cpp_module(self.module)
            # Use wrapped._modules instead of self.module.items()
            for name, module in wrapped._modules.items():
                 return module(input)
        else:
            # Eager mode
            for name, module in self.modules.items():
                 return module(input)
```
