### ISSUE TITLE
fx quantization: nn.sequential not fuseable

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#46562]
Running `torch.quantization.prepare_fx` on a toy nn.Sequential model fails.  From early inspection it looks like something in quantization creates a name which starts with a digit, which then violates an assumption in FX.

code:
```
import torch                                                           
import torch.nn as nn                                                  
                                                                       
m = nn.Sequential(                                                     
    nn.Conv2d(1, 1, 1),                                                
)                                                                      
m.eval()                                                               
                                                                       
qconfig_dict = {'': torch.quantization.get_default_qconfig('qnnpack')} 
mp = torch.quantization.prepare_fx(m, qconfig_dict)                    
```

trace:
```
Traceback (most recent call last):
  File "/home/vasiliy/local/tmp/quant_fx_playground.py", line 10, in <module>
    mp = torch.quantization.prepare_fx(m, qconfig_dict)
  File "/data/users/vasiliy/pytorch/torch/quantization/quantize_fx.py", line 190, in prepare_fx
    return _prepare_fx(model, qconfig_dict, inplace, prepare_custom_config_dict)
  File "/data/users/vasiliy/pytorch/torch/quantization/quantize_fx.py", line 64, in _prepare_fx
    graph_module = _fuse_fx(graph_module, inplace)
  File "/data/users/vasiliy/pytorch/torch/quantization/quantize_fx.py", line 24, in _fuse_fx
    return fuser.fuse(graph_module, inplace)
  File "/data/users/vasiliy/pytorch/torch/quantization/fx/fuse.py", line 38, in fuse
    env[node.name] = self.fused_graph.node_copy(node, load_arg)
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 265, in node_copy
    name = self._name(sanitized_name)
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 283, in _name
    if op[0].isdigit():
IndexError: string index out of range
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
@jerryzh168 , would you be interested in taking a look? Otherwise I can.

**Comment by jerryzh168** [comment]
> @jerryzh168 , would you be interested in taking a look? Otherwise I can.

please go ahead, it takes some time to land my current PRs.

**Comment by vkuzo** [comment]
sg

**Comment by jerryzh168** [comment]
@vkuzo looks like I need this now, I'll take a look.

**Comment by vkuzo** [comment]
Seems like the issue is caused by `copy.deepcopy` failing on GraphModule instances of `nn.Sequential`:

```
import torch                                                                                         
import torch.nn as nn                                                                                
m = nn.Sequential(nn.Conv2d(1, 1, 1))                                                                
gm = torch.fx.symbolic_trace(m)                                                                      
import copy                                                                                          
gm_copy = copy.deepcopy(gm)                                                                          

...

Traceback (most recent call last):                                                                       
  File "<stdin>", line 1, in <module>                                                                    
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 153, in deepcopy        
    y = copier(memo)                                                                                     
  File "/data/users/vasiliy/pytorch/torch/fx/graph_module.py", line 199, in __deepcopy__                 
    fake_mod.__dict__ = copy.deepcopy(self.__dict__)                                                     
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 146, in deepcopy        
    y = copier(x, memo)                                                                                  
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 230, in _deepcopy_dict  
    y[deepcopy(key, memo)] = deepcopy(value, memo)                                                       
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 153, in deepcopy        
    y = copier(memo)                                                                                     
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 150, in __deepcopy__                        
    output_val = g.graph_copy(self, val_map=memo)                                                        
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 137, in graph_copy                          
    val_map[node] = self.node_copy(node, lambda n : val_map[n])                                          
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 279, in node_copy                           
    name = self._name(sanitized_name)                                                                    
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 297, in _name                               
    if op[0].isdigit():                                                                                  
IndexError: string index out of range                                                                    
>>>                                                                                                      
```

**Comment by vkuzo** [comment]
filed https://github.com/pytorch/pytorch/issues/46925 for the issue in FX, will see if someone from FX core can take a look

**Comment by vkuzo** [comment]
this works now after the fix in https://github.com/pytorch/pytorch/issues/46925
