### ISSUE TITLE
ERROR GENERATING FILE (caffe2)

### ISSUE THREAD

**Issue by iremonur** [pytorch/pytorch#46644]
## ❓ Questions and Help

Hi, after I run “python setup.py install”, I get this error :

[3894/5004] Building NVCC (Device) obj…cuda_generated_THCTensorTopKShort.cu.o
FAILED: caffe2/CMakeFiles/torch_cuda.dir//aten/src/THC/generated/torch_cuda_generated_THCTensorTopKShort.cu.o
cd /home/ionur1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir//aten/src/THC/generated && /home/ionur1/anaconda3/envs/conda_env/bin/cmake -E make_directory /home/ionur1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir//aten/src/THC/generated/. && /home/ionur1/anaconda3/envs/conda_env/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/ionur1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir//aten/src/THC/generated/./torch_cuda_generated_THCTensorTopKShort.cu.o -D generated_cubin_file:STRING=/home/ionur1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir//aten/src/THC/generated/./torch_cuda_generated_THCTensorTopKShort.cu.o.cubin.txt -P /home/ionur1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir//aten/src/THC/generated/torch_cuda_generated_THCTensorTopKShort.cu.o.Release.cmake
/home/ionur1/pytorch/aten/src/THC/THCDeviceUtils.cuh(38): error: identifier “__ldg” is undefined
detected during:
instantiation of “T doLdg(const T *) [with T=int16_t]”
/home/ionur1/pytorch/aten/src/ATen/native/cuda/SortingRadixSelect.cuh(201): here
instantiation of “void at::native::countRadixUsingMask<scalar_t,bitwise_t,index_t,CountType,RadixSize,RadixBits>(CountType *, CountType *, bitwise_t, bitwise_t, int, index_t, index_t, scalar_t *) [with scalar_t=int16_t, bitwise_t=uint32_t, index_t=uint32_t, CountType=int, RadixSize=4, RadixBits=2]”
/home/ionur1/pytorch/aten/src/ATen/native/cuda/SortingRadixSelect.cuh(337): here
instantiation of “void at::native::radixSelect<scalar_t,bitwise_t,index_t,Order>(scalar_t *, index_t, index_t, index_t, int *, scalar_t *) [with scalar_t=int16_t, bitwise_t=uint32_t, index_t=uint32_t, Order=true]”
/home/ionur1/pytorch/aten/src/THC/THCTensorTopK.cuh(69): here
instantiation of “void gatherTopK<T,IndexType,Dim,Order>(TensorInfo<T, IndexType>, IndexType, IndexType, IndexType, IndexType, TensorInfo<T, IndexType>, IndexType, IndexType, TensorInfo<int64_t, IndexType>, IndexType) [with T=int16_t, IndexType=uint32_t, Dim=1, Order=true]”
/home/ionur1/pytorch/aten/src/THC/generic/THCTensorTopK.cu(127): here

1 error detected in the compilation of “/tmp/tmpxft_0000297e_00000000-6_THCTensorTopKShort.cpp1.ii”.
CMake Error at torch_cuda_generated_THCTensorTopKShort.cu.o.Release.cmake:281 (message):
Error generating file
/home/ionur1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorTopKShort.cu.o

[3901/5004] Building NVCC (Device) obj…rch_cuda_generated_THCTensorIndex.cu.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File “setup.py”, line 724, in
build_deps()
File “setup.py”, line 312, in build_deps
build_caffe2(version=version,
File “/home/ionur1/pytorch/tools/build_pytorch_libs.py”, line 62, in build_caffe2
cmake.build(my_env)
File “/home/ionur1/pytorch/tools/setup_helpers/cmake.py”, line 346, in build
self.run(build_args, my_env)
File “/home/ionur1/pytorch/tools/setup_helpers/cmake.py”, line 141, in run
check_call(command, cwd=self.build_dir, env=env)
File “/home/ionur1/anaconda3/envs/conda_env/lib/python3.8/subprocess.py”, line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ‘[‘cmake’, ‘–build’, ‘.’, ‘–target’, ‘install’, ‘–config’, ‘Release’, ‘–’, ‘-j’, ‘8’]’ returned non-zero exit status 1.

Note: I tried to run with python and python3, nothing has changed. I activated Conda environment before running the commands.

OS: Ubuntu 18.04.1 LTS
CUDA Version 10.2.89
cudNN Version 7603
Python : 3.8.5
GPU : GPU0 Quadro K3100M
GCC version : 8.4.0

I would like to be very glad if you help me with this.

**Comment by zou3519** [comment]
Seems like https://github.com/pytorch/pytorch/pull/46535 should fix this

**Comment by iremonur** [comment]
Thank you but I don't understand what I must to do solve this problem. Could you explain?

**Comment by zou3519** [comment]
Can you patch #46535 into your local pytorch checkout and see if it compiles?

**Comment by iremonur** [comment]
Thank you for your response, I checked out GitHub Pull Request #46535 but now, I get this error :

Building wheel torch-1.8.0a0
-- Building version 1.8.0a0
cmake --build . --target install --config Release -- -j 8
[0/1] Re-running CMake...
-- std::exception_ptr is supported.
-- Turning off deprecation warning due to glog.
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- 
-- 3.11.4.0
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/ionur1/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- Trying to find preferred BLAS backend of choice: MKL
-- MKL_THREADING = OMP
CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  cmake/Modules/FindMKL.cmake:213 (FIND_PACKAGE)
  cmake/Modules/FindMKL.cmake:307 (CHECK_ALL_LIBRARIES)
  cmake/Dependencies.cmake:136 (find_package)
  CMakeLists.txt:517 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  cmake/Modules/FindMKL.cmake:213 (FIND_PACKAGE)
  cmake/Modules/FindMKL.cmake:307 (CHECK_ALL_LIBRARIES)
  cmake/Dependencies.cmake:136 (find_package)
  CMakeLists.txt:517 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- MKL libraries: /home/ionur1/anaconda3/envs/conda_env/lib/libmkl_intel_lp64.so;/home/ionur1/anaconda3/envs/conda_env/lib/libmkl_gnu_thread.so;/home/ionur1/anaconda3/envs/conda_env/lib/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so
-- MKL include directory: /home/ionur1/anaconda3/envs/conda_env/include
-- MKL OpenMP type: GNU
-- MKL OpenMP library: -fopenmp
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /home/ionur1/anaconda3/envs/conda_env/bin/python3 (found version "3.7.9") 
-- NNPACK backend is x86-64
-- Failed to find LLVM FileCheck
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  third_party/fbgemm/CMakeLists.txt:59 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  third_party/fbgemm/CMakeLists.txt:59 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at third_party/fbgemm/CMakeLists.txt:61 (message):
  OpenMP found! OpenMP_C_INCLUDE_DIRS =


CMake Warning at third_party/fbgemm/CMakeLists.txt:136 (message):
  ==========


CMake Warning at third_party/fbgemm/CMakeLists.txt:137 (message):
  CMAKE_BUILD_TYPE = Release


CMake Warning at third_party/fbgemm/CMakeLists.txt:138 (message):
  CMAKE_CXX_FLAGS_DEBUG is -g


CMake Warning at third_party/fbgemm/CMakeLists.txt:139 (message):
  CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG


CMake Warning at third_party/fbgemm/CMakeLists.txt:140 (message):
  ==========


** AsmJit Summary **
   ASMJIT_DIR=/home/ionur1/pytorch/third_party/fbgemm/third_party/asmjit
   ASMJIT_TEST=FALSE
   ASMJIT_TARGET_TYPE=STATIC
   ASMJIT_DEPS=pthread;rt
   ASMJIT_LIBS=asmjit;pthread;rt
   ASMJIT_CFLAGS=-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-fno-math-errno;-fno-threadsafe-statics;-fno-semantic-interposition;-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS_DBG=
   ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants
-- Found Numa  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
-- Using third party subdirectory Eigen.
-- Found PythonInterp: /home/ionur1/anaconda3/envs/conda_env/bin/python3 (found suitable version "3.7.9", minimum required is "3.0") 
CMake Error at cmake/Dependencies.cmake:926 (if):
  if given arguments:

    "VERSION_LESS" "3"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:517 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ionur1/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/ionur1/pytorch/build/CMakeFiles/CMakeError.log".
FAILED: build.ninja 
/home/ionur1/anaconda3/envs/conda_env/bin/cmake --regenerate-during-build -S/home/ionur1/pytorch -B/home/ionur1/pytorch/build
ninja: error: rebuilding 'build.ninja': subcommand failed
Traceback (most recent call last):
  File "setup.py", line 724, in <module>
    build_deps()
  File "setup.py", line 317, in build_deps
    cmake=cmake)
  File "/home/ionur1/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/ionur1/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/home/ionur1/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/ionur1/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.

**Comment by dcboy** [comment]
> Thank you for your response, I checked out GitHub Pull Request #46535 but now, I get this error :
> 
> ## Building wheel torch-1.8.0a0
> -- Building version 1.8.0a0
> cmake --build . --target install --config Release -- -j 8
> [0/1] Re-running CMake...
> -- std::exception_ptr is supported.
> -- Turning off deprecation warning due to glog.
> -- Current compiler supports avx2 extension. Will build perfkernels.
> -- Current compiler supports avx512f extension. Will build fbgemm.
> -- Building using own protobuf under third_party per request.
> -- Use custom protobuf build.
> -- 3.11.4.0
> -- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/ionur1/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
> -- Trying to find preferred BLAS backend of choice: MKL
> -- MKL_THREADING = OMP
> CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
> The package name passed to `find_package_handle_standard_args` (OpenMP_C)
> does not match the name of the calling package (OpenMP). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
> cmake/Modules/FindMKL.cmake:213 (FIND_PACKAGE)
> cmake/Modules/FindMKL.cmake:307 (CHECK_ALL_LIBRARIES)
> cmake/Dependencies.cmake:136 (find_package)
> CMakeLists.txt:517 (include)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
> The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
> does not match the name of the calling package (OpenMP). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
> cmake/Modules/FindMKL.cmake:213 (FIND_PACKAGE)
> cmake/Modules/FindMKL.cmake:307 (CHECK_ALL_LIBRARIES)
> cmake/Dependencies.cmake:136 (find_package)
> CMakeLists.txt:517 (include)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- MKL libraries: /home/ionur1/anaconda3/envs/conda_env/lib/libmkl_intel_lp64.so;/home/ionur1/anaconda3/envs/conda_env/lib/libmkl_gnu_thread.so;/home/ionur1/anaconda3/envs/conda_env/lib/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so
> -- MKL include directory: /home/ionur1/anaconda3/envs/conda_env/include
> -- MKL OpenMP type: GNU
> -- MKL OpenMP library: -fopenmp
> -- Brace yourself, we are building NNPACK
> -- Found PythonInterp: /home/ionur1/anaconda3/envs/conda_env/bin/python3 (found version "3.7.9")
> -- NNPACK backend is x86-64
> -- Failed to find LLVM FileCheck
> -- git Version: v1.4.0-505be96a
> -- Version: 1.4.0
> -- Performing Test HAVE_STD_REGEX -- success
> -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
> -- Performing Test HAVE_POSIX_REGEX -- success
> -- Performing Test HAVE_STEADY_CLOCK -- success
> CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
> The package name passed to `find_package_handle_standard_args` (OpenMP_C)
> does not match the name of the calling package (OpenMP). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
> third_party/fbgemm/CMakeLists.txt:59 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /home/ionur1/anaconda3/envs/conda_env/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
> The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
> does not match the name of the calling package (OpenMP). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
> third_party/fbgemm/CMakeLists.txt:59 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning at third_party/fbgemm/CMakeLists.txt:61 (message):
> OpenMP found! OpenMP_C_INCLUDE_DIRS =
> 
> # CMake Warning at third_party/fbgemm/CMakeLists.txt:136 (message):
> CMake Warning at third_party/fbgemm/CMakeLists.txt:137 (message):
> CMAKE_BUILD_TYPE = Release
> 
> CMake Warning at third_party/fbgemm/CMakeLists.txt:138 (message):
> CMAKE_CXX_FLAGS_DEBUG is -g
> 
> CMake Warning at third_party/fbgemm/CMakeLists.txt:139 (message):
> CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG
> 
> # CMake Warning at third_party/fbgemm/CMakeLists.txt:140 (message):
> ** AsmJit Summary **
> ASMJIT_DIR=/home/ionur1/pytorch/third_party/fbgemm/third_party/asmjit
> ASMJIT_TEST=FALSE
> ASMJIT_TARGET_TYPE=STATIC
> ASMJIT_DEPS=pthread;rt
> ASMJIT_LIBS=asmjit;pthread;rt
> ASMJIT_CFLAGS=-DASMJIT_STATIC
> ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-fno-math-errno;-fno-threadsafe-statics;-fno-semantic-interposition;-DASMJIT_STATIC
> ASMJIT_PRIVATE_CFLAGS_DBG=
> ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants
> -- Found Numa (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
> -- Using third party subdirectory Eigen.
> -- Found PythonInterp: /home/ionur1/anaconda3/envs/conda_env/bin/python3 (found suitable version "3.7.9", minimum required is "3.0")
> CMake Error at cmake/Dependencies.cmake:926 (if):
> if given arguments:
> 
> ```
> "VERSION_LESS" "3"
> ```
> 
> Unknown arguments specified
> Call Stack (most recent call first):
> CMakeLists.txt:517 (include)
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/ionur1/pytorch/build/CMakeFiles/CMakeOutput.log".
> See also "/home/ionur1/pytorch/build/CMakeFiles/CMakeError.log".
> FAILED: build.ninja
> /home/ionur1/anaconda3/envs/conda_env/bin/cmake --regenerate-during-build -S/home/ionur1/pytorch -B/home/ionur1/pytorch/build
> ninja: error: rebuilding 'build.ninja': subcommand failed
> Traceback (most recent call last):
> File "setup.py", line 724, in
> build_deps()
> File "setup.py", line 317, in build_deps
> cmake=cmake)
> File "/home/ionur1/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
> cmake.build(my_env)
> File "/home/ionur1/pytorch/tools/setup_helpers/cmake.py", line 346, in build
> self.run(build_args, my_env)
> File "/home/ionur1/pytorch/tools/setup_helpers/cmake.py", line 141, in run
> check_call(command, cwd=self.build_dir, env=env)
> File "/home/ionur1/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.

is same for me , how to resolve?
