### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Kdc23** [pytorch/pytorch#4672]
i'm trying to run python prepro_feats.py from this repo [https://github.com/xiadingZ/video-caption.pytorch]
The error I'm getting:
/home/k23/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
"please use transforms.Resize instead.")
Traceback (most recent call last):
File "prepro_feats.py", line 126, in
model = model.cuda()
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
return self._apply(lambda t: t.cuda(device))
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
module._apply(fn)
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
module._apply(fn)
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
module._apply(fn)
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
param.data = fn(param.data)
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in
return self._apply(lambda t: t.cuda(device))
File "/home/koeldc23/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 69, in cuda
return new_type(self.size()).copy(self, async)
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/cuda/init.py", line 453, in _lazy_new
_lazy_init()
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/cuda/init.py", line 152, in _lazy_init
_check_driver()
File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/cuda/init.py", line 74, in _check_driver
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How do I compile Torch with CUDA? I've followed the following steps to install PyTorch
$ git clone https://github.com/pytorch/pytorch
$ export CMAKE_PREFIX_PATH=/home/alexis/anaconda2
$ conda install numpy mkl setuptools cmake gcc cffi
$ conda install -c soumith magma-cuda80
$ pip install -r requirements.txt
$ python setup.py install

Unable to figure this out. Kindly help. Thanks!

**Comment by apaszke** [comment]
I replied in the other issue where you posted the comment. Please don't post multiple times.
