### ISSUE TITLE
torch.utils.tensorboard.SummaryWriter.add_embedding fails for some label_img sizes

### ISSUE THREAD

**Issue by alekseynp** [pytorch/pytorch#46739]
## 🐛 Bug

`torch.utils.tensorboard.SummaryWriter.add_embedding` fails for some label_img sizes.
Suspect that square and non-square width>height works, but non-square width<height fails.

## To Reproduce

```
import torch
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter('./')
writer.add_embedding(
    torch.randn(100, 256),
    label_img=torch.randn(100, 3, 32, 32)
)

writer = SummaryWriter('./')
writer.add_embedding(
    torch.randn(100, 256),
    label_img=torch.randn(100, 3, 10, 10)
)

writer = SummaryWriter('./')
writer.add_embedding(
    torch.randn(100, 256),
    label_img=torch.randn(100, 3, 10, 32)
)

writer = SummaryWriter('./')
writer.add_embedding(
    torch.randn(100, 256),
    label_img=torch.randn(100, 3, 32, 10)
)
```

```
Traceback (most recent call last):
  File "scratch.py", line 25, in <module>
    label_img=torch.randn(100, 3, 32, 10)
  File "/home/user/.conda/envs/detectron2/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 805, in add_embedding
    make_sprite(label_img, save_path)
  File "/home/user/.conda/envs/detectron2/lib/python3.7/site-packages/torch/utils/tensorboard/_embedding.py", line 36, in make_sprite
    arranged_augment_square_HWC[:arranged_img_HWC.shape[0], :, :] = arranged_img_HWC
ValueError: could not broadcast input array from shape (320,100,3) into shape (100,100,3)
```
## Expected behavior

Success.

## Environment

```
python collect_env.py 
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Quadro GV100
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 455.28
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.19.1
[pip3] segmentation-models-pytorch==0.1.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.1           py37hbc911f0_0  
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py37_cu101    pytorch
```

Tagging @bornaghotbi who contributed to this issue.

**Comment by samedii** [comment]
I'm also having issues with `make_sprite`. It is not creating a correct sprite sheet and the projector is showing multiple images per sample while others do not have any image label. I saw this and don't want to add another issue yet since this issue is probably very related.

**Comment by busFred** [comment]
I also encounter the same issue and I looked into their `make_sprite` implementation. I think to make it works for all image size, some kind of optimization problem needs to be solved so that a minimum square sprite image can be created to hold all the input images.
I think the following line in `make_sprite` assumes the `label_img` be sqaure images.
https://github.com/pytorch/pytorch/blob/d4bbebbb97ea35e8dd8a43451f64e533bb91b662/torch/utils/tensorboard/_embedding.py#L30

**Comment by alessandro-peron-sdg** [comment]
I am experiencing the same problem, it seems that if the height is bigger than the width throws an error, if it is the reverse images are not displayed correctly and you get overlapping images on the same sprite
