### ISSUE TITLE
Raise a TypeError when nn.Module.train parameter misuse.

### ISSUE THREAD

**Issue by km19809** [pytorch/pytorch#46763]
## 🚀 Feature

Raise a Type Error when a user misuses nn.Module.train
## Motivation

I requested this because the TypeError prevents misuse. \
Pytorch has type hint, but I do not think that is enough. \
When I was training a pytorch model, I met an error:\
 `TypeError: dropout(): argument 'train' (position 3) must be bool, not torch.device`\
I tried to find that, but the argument 'train' did not exist.
After a while, I found that I typed wrong. I used `model.train(device)`, not `model.train(True)` .\
The error should be raised from 'nn.Module.train'.

## Pitch

If a user uses a variable which is not boolean as parameter, please raise a TypeError.
## Additional context

Snippet of my code:
```
model.train(device)

    last_valid_loss=float('infinity')
    for epoch in tqdm(range(checkpoint_epoch,epoches)):
        train_loss_list=[]
        valid_loss_list=[]
        for data in tqdm(trainset):
            optimizer.zero_grad()
            data = data.to(ctx)
            label = torch.where(data!=padding_id, data, torch.ones_like(data)*-100)
            mask = torch.where(data!=padding_id,torch.ones_like(data),torch.zeros_like(data))
            output=model(data, labels=label, attention_mask=mask)
```
Full TraceBack:
```
Traceback (most recent call last):
  File "/code/train_test.py", line 62, in <module>
    output=model(data, labels=label, attention_mask=mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_gpt2.py", line 604, in forward
    use_cache=use_cache,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_gpt2.py", line 472, in forward
    hidden_states = self.drop(hidden_states)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/dropout.py", line 54, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 936, in dropout
    else _VF.dropout(input, p, training))
TypeError: dropout(): argument 'train' (position 3) must be bool, not torch.device
```
p.s. Sorry for my bad English. I have translated word by word, so it may be very awkward.

cc @albanD @mruberry

**Comment by mruberry** [comment]
Thanks for the suggestion, @zhangguanheng66! We would accept a PR implementing this check.
