### ISSUE TITLE
Error with installing through Pip

### ISSUE THREAD

**Issue by BigDvsRL** [pytorch/pytorch#46775]
Since i havent found that Topic yet....

I'm always getting an Error when i'm trying to install Pytorch through Pip3 on my Windows 10 system

Error:

Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied: pyyaml in c:\users\flo\appdata\local\programs\python\python37-32\lib\site-packages (from torch) (5.1.1)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\flo\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Flo\AppData\Local\Temp\pip-wheel-hsr0c19g'
       cwd: C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\flo\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\flo\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Flo\AppData\Local\Temp\pip-record-52w23mh0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\flo\appdata\local\programs\python\python37-32\Include\torch'
         cwd: C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\users\flo\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\flo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Flo\AppData\Local\Temp\pip-install-8nf3k99v\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\flo\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pip-install-8nf3k99v\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Flo\AppData\Local\Temp\pip-record-52w23mh0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\flo\appdata\local\programs\python\python37-32\Include\torch' Check the logs for full command output.

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by zhangguanheng66** [comment]
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by malfet** [comment]
Please download PyTorch Windows wheels from download.pytorch.org rather than from PyPi repo, as documented in
https://pytorch.org/get-started/locally/
For example, trying installing using the following command:
```
pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by peterjc123** [comment]
Also, please use Python x64 instead.

**Comment by BigDvsRL** [comment]
> 
> 
> Please download PyTorch Windows wheels from download.pytorch.org rather than from PyPi repo, as documented in
> https://pytorch.org/get-started/locally/
> For example, trying installing using the following command:
> 
> ```
> pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
> ```


Result:

C:\Users\Flo>pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.6.0

**Comment by peterjc123** [comment]
@BigDvsRL Two possible reasons:
1. You are using Python x86. But we only support Python x64.
2. You are using Python 3.9. But we only support Python 3.6-3.8.

**Comment by BigDvsRL** [comment]
> 
> 
> Also, please use Python x64 instead.

Now i installed Python 3.7 64-bit

Current Error:

Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied: pyyaml in c:\users\flo\appdata\local\programs\python\python37\lib\site-packages (from torch) (5.3.1)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py): started
  Building wheel for torch (setup.py): finished with status 'error'
  Running setup.py clean for torch
Failed to build torch
Installing collected packages: torch
    Running setup.py install for torch: started
    Running setup.py install for torch: finished with status 'error'

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Flo\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Flo\AppData\Local\Temp\pip-wheel-gnf4d244'
       cwd: C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "C:\Users\Flo\AppData\Roaming\Python\Python37\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Flo\AppData\Roaming\Python\Python37\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Flo\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Flo\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Flo\AppData\Local\Temp\pip-record-yz97tume\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Flo\AppData\Roaming\Python\Python37\Include\torch'
         cwd: C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "C:\Users\Flo\AppData\Roaming\Python\Python37\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Flo\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Flo\AppData\Local\Temp\pycharm-packaging\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Flo\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Flo\\AppData\\Local\\Temp\\pycharm-packaging\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Flo\AppData\Local\Temp\pip-record-yz97tume\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Flo\AppData\Roaming\Python\Python37\Include\torch' Check the logs for full command output.

**Comment by peterjc123** [comment]
Please use `pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html` with Python x64.

**Comment by BigDvsRL** [comment]
> 
> 
> Please use `pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html` with Python x64.

You're right, it worked

I read through the Website. Maybe you should write it down somewhere that 64bit is needed
