### ISSUE TITLE
FX: unable to copy.deepcopy a traced instance of nn.Sequential

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#46925]
Symbolically tracing and then `copy.deepcopy`'ing an instance of `nn.Sequential` currently fails:

```
import torch                                                                                         
import torch.nn as nn                                                                                
m = nn.Sequential(nn.Conv2d(1, 1, 1))                                                                
gm = torch.fx.symbolic_trace(m)                                                                      
import copy                                                                                          
gm_copy = copy.deepcopy(gm)                                                                          

...

Traceback (most recent call last):                                                                       
  File "<stdin>", line 1, in <module>                                                                    
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 153, in deepcopy        
    y = copier(memo)                                                                                     
  File "/data/users/vasiliy/pytorch/torch/fx/graph_module.py", line 199, in __deepcopy__                 
    fake_mod.__dict__ = copy.deepcopy(self.__dict__)                                                     
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 146, in deepcopy        
    y = copier(x, memo)                                                                                  
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 230, in _deepcopy_dict  
    y[deepcopy(key, memo)] = deepcopy(value, memo)                                                       
  File "/home/vasiliy/local/miniconda3/envs/pytorch/lib/python3.8/copy.py", line 153, in deepcopy        
    y = copier(memo)                                                                                     
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 150, in __deepcopy__                        
    output_val = g.graph_copy(self, val_map=memo)                                                        
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 137, in graph_copy                          
    val_map[node] = self.node_copy(node, lambda n : val_map[n])                                          
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 279, in node_copy                           
    name = self._name(sanitized_name)                                                                    
  File "/data/users/vasiliy/pytorch/torch/fx/graph.py", line 297, in _name                               
    if op[0].isdigit():                                                                                  
IndexError: string index out of range                                                                    
>>>                                        
``` 

This is needed to unblock the resolution of https://github.com/pytorch/pytorch/issues/46562, which in turn is needed for expanding production model coverage.

**Comment by vkuzo** [comment]
cc @jamesr66a , thoughts if someone on FX could take a look?

**Comment by jamesr66a** [comment]
This should be resolved by https://github.com/pytorch/pytorch/pull/46958

Please let me know if you see any further issues
