### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Masterkmp** [pytorch/pytorch#46972]
### There is a error in running process,and error is  as follows:how to make it?

Traceback (most recent call last):
  File "D:/CodingProject/PycharmProjects/Codes/main.py", line 47, in <module>
    get_train(model, Epochs, train_loader,test_loader,test_y_labels,optimizer, loss_func)
  File "D:\CodingProject\PycharmProjects\Codes\classify.py", line 77, in get_train
    get_test(test_loader,test_y,model)
  File "D:\CodingProject\PycharmProjects\Codes\classify.py", line 35, in get_test
    test_output = model(batch_x)#
  File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\CodingProject\PycharmProjects\Models\gcn.py", line 70, in forward
    out_g1 = self.gc(out, adj_Metrix)
  File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\CodingProject\PycharmProjects\Models\Layers\gcn_layers.py", line 57, in forward
    support = torch.bmm(input, weight_matrix)
RuntimeError: invalid argument 6: expected 3D tensor at c:\new-builder_3\win-wheel\pytorch\aten\src\thc\generic/THCTensorMathBlas.cu:466

**Comment by VitalyFedyunin** [comment]
Hello! Looks like you are passing invalid sized tensor into the `bmm` operator. But it is hard to say without seeing your code. As it seems coding mistake for me (and not pytorch bug), please refer all further questions to the forum https://discuss.pytorch.org/
