### ISSUE TITLE
GeForce RTX 3080 with Yolov5 detect.py(ingerence) Error:Torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute

### ISSUE THREAD

**Issue by zl751209a** [pytorch/pytorch#46971]
## ❓ GeForce RTX 3080 with Yolov5 detect.py(ingerence) Error:Torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute

version is following:
NVIDIA-SMI 456.71       Driver Version: 456.71 
torch 1.7.0+cu110
torchaudio 0.7.0
torchvision 0.8.1+cu110
Cuda compilation tools, release 11.1, V11.1.74

 Training goes well. Ingerence has this problem"Torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute".

```
yolov5-master>python detect.py
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=640, iou_thres=0.45, save_conf=False, save_dir='inference/output', save_txt=False, source='inference/images', update=False, view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 3080', total_memory=10240MB)

Fusing layers...
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 63, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "d:\ProgramData\Anaconda3\envs\tf37\lib\site-packages\torch\nn\modules\module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Yolo\yolov5-master\models\yolo.py", line 116, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\Yolo\yolov5-master\models\yolo.py", line 136, in forward_once
    x = m(x)  # run
  File "d:\ProgramData\Anaconda3\envs\tf37\lib\site-packages\torch\nn\modules\module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Yolo\yolov5-master\models\common.py", line 92, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "d:\ProgramData\Anaconda3\envs\tf37\lib\site-packages\torch\nn\modules\module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Yolo\yolov5-master\models\common.py", line 36, in fuseforward
    return self.act(self.conv(x))
  File "d:\ProgramData\Anaconda3\envs\tf37\lib\site-packages\torch\nn\modules\module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\envs\tf37\lib\site-packages\torch\nn\modules\activation.py", line 438, in forward
    return F.hardswish(input, self.inplace)
  File "d:\ProgramData\Anaconda3\envs\tf37\lib\site-packages\torch\nn\modules\module.py", line 796, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'
```

**Comment by mruberry** [comment]
Is that hardswish layer quantized? The inplace attribute for quantized hardswish was removed in https://github.com/pytorch/pytorch/pull/36545. cc @vkuzo.

**Comment by zl751209a** [comment]
The script has been running without any issue.
`yolov5-master>python detect.py --weight best.pt`
Ingerence has this problem"Torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'"
`yolov5-master>python detect.py`   
(default yolov5s.pt)

**Comment by zl751209a** [comment]
> Is that hardswish layer quantized? The inplace attribute for quantized hardswish was removed in #36545. cc @vkuzo.

The script has been running without any issue.
yolov5-master>python detect.py --weight best.pt
This script has this problem"Torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'"
yolov5-master>python detect.py
(default yolov5s.pt)
Why?:)

**Comment by zhaoyuliang5** [comment]
I also encountered this problem，the problem has been resolved。
open ~/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py 
'return F.hardswish(input, self.inplace)'    replace with   'return F.hardswish(input)'

**Comment by zl751209a** [comment]
Thank you. Maybe  https://github.com/ultralytics/yolov5/releases/tag/v3.1
-----][-----]\：zhaoyuliang5 <notifications@github.com>_：pytorch/pytorch <pytorch@noreply.github.com>=：zl751209a <zl751209a@sina.com.cn> 作者 <author@noreply.github.com>[re： [pytorch/pytorch] Yolov5 检测.py（ingerence） 错误：Torch.nn.module.module.module.Module.Module：3：'硬swish'对象没有属性"就位"（#46971）[2020]1111]10]44]



我也遇到了这个问题，问题已经解决了。打开 +/.local/lib/python3.8/站点包/火炬/nn/模块/激活.py'返回 F.hardswish（输入，自我.就地）'替换为"返回 F.hardswish（输入）"



•您收到此消息是因为您创作了线程。直接回复此电子邮件，在 GitHub上查看，或取消订阅。

**Comment by HsLOL** [comment]
> I also encountered this problem，the problem has been resolved。
> open ~/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py
> 'return F.hardswish(input, self.inplace)' replace with 'return F.hardswish(input)'



hi @zhaoyuliang5 
I try this solution, but it doesn't work...

**Comment by DrRyanHuang** [comment]
`Ubuntu 18.04` 
`CUDA 11.0`
`Cudnn 8.0.4`
`Python 3.8`

I also encountered this problem
Make sure your env 's Python is correct.

That works:
> I also encountered this problem，the problem has been resolved。
> open ~/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py
> 'return F.hardswish(input, self.inplace)' replace with 'return F.hardswish(input)'

Thxxxxxxxxxxxxxxxxxx!

**Comment by IanMHoffman** [comment]
I am also encountering this. Using zhaoyuliang5's fix makes it run but it will not actually detect for me nor will it output anything. Is there any information I can provide to help track this down?

**Comment by supriyar** [comment]
This issue doesn't seem related to quantization, please clarify if it is.

**Comment by mruberry** [comment]
I think you're right, @supriyar. Initially I thought it was due to the change in quantization, but closer review suggests the 'inplace' attribute is somehow absent from the module, although I can't understand how that would happen. This will need a closer analysis.

**Comment by ezyang** [comment]
Looking at the changelog for https://github.com/ultralytics/yolov5/releases/tag/v3.1 I'm guessing that the module was created by deserialization of a Pickle from an older version of PyTorch, or some other similarly hardcoded fashion. In that case, attributes that you would otherwise expect to be present could be missing.

When new fields are added to Python modules, we are supposed to add a `__setstate__` method to make sure fields get properly set when the pickle is old. But it is very easy to forget and it looks like it was forgotten here. 

inplace attribute was added in https://github.com/pytorch/pytorch/pull/42346 cc @miraliahmadli and @albanD who was reviewer

**Comment by albanD** [comment]
Taking a step back, users should NOT serialize full models and only the state dicts as very explicitly stated in our doc.

I agree that we should fix this and I agree with @ezyang analysis but I am not sure this is actually high priority as users using PyTorch as instructed won't hit this.

**Comment by gchanan** [comment]
given the number of people who hit it I think we should fix.  I.e. our strategy should generally be "don't do that", but if enough people run into a specific issue that is easy to fix we can address it as a one-off.
