### ISSUE TITLE
[JIT] scripting torchaudio.transforms.MFCC() error 

### ISSUE THREAD

**Issue by qute012** [pytorch/pytorch#46979]
Hi. I face problem when i use torchaudio.transforms.MFCC() as preprocessing on android app. Help ME

---version---
pytorch::1.7.0
torchaudio::0.7.0

scripting from nn.Module 
```
mfcc = torchaudio.transforms.MFCC()
scripted.save("./mfcc.pt")
```

When Module implements on android's java code, it doesn't work, Module forward function don't recognize forward in script.
errors:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.real_time_speech_command, PID: 17200
    com.facebook.jni.CppException: Method 'forward' is not defined.
    Exception raised from get_method at ../../../../src/main/cpp/libtorch_include/x86/torch/csrc/jit/api/object.h:91 (most recent call first):
    (no backtrace available)
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:48)
        at com.example.real_time_speech_command.MainActivity.startRecognition(MainActivity.java:224)
        at com.example.real_time_speech_command.MainActivity.access$400(MainActivity.java:48)
        at com.example.real_time_speech_command.MainActivity$2.onClick(MainActivity.java:184)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by qute012** [comment]
Add gradle dependencies

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.zagum:SpeechRecognitionView:1.2.2'
    //implementation 'org.pytorch:pytorch_android:1.4.0'
    //implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android:1.7.0'
}
```
