### ISSUE TITLE
Inappropriate error message when slicing with a numpy tensor

### ISSUE THREAD

**Issue by docsjoo** [pytorch/pytorch#4704]
Using PyTorch 0.3.0
I was trying to use ByteArrays to index a tensor and got some really baffling error messages that I think are in error.

For comparison, here's what I was trying to do, essentially, which works in numpy:
```
>>> import numpy as np
>>> import torch
>>> a = np.arange(10)
>>> b = np.zeros([10])
>>> c = np.zeros([1,1,10])
>>> p = a > 5
>>> b[p] = 1
>>> b
array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.])
>>> c[:,:,p] = 1
>>> c
array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.]]])
```

Here's what happens for PyTorch tensors:
```
>>> at = torch.arange(10)
>>> bt = torch.zeros(10)
>>> ct = torch.zeros(1,1,10)
>>> bt[p] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Performing basic indexing on a tensor and encountered an error indexing dim 0 with an object of type numpy.ndarray. The only supported types are integers, slices, numpy scalars, or if indexing with a torch.LongTensor or torch.ByteTensor only a single Tensor may be passed.
```
All well and good, since I was using ```p``` which is of the wrong type. What I actually did, however, was

```
>>> ct[:,:,p] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 140309067918200 from broadcast indexer is out of range for dimension 2 (of size 10)
```
Which just seems weird and confused me a whole lot.

**Comment by zou3519** [comment]
Thanks for the report, @docsjoo. I believe this has been fixed on master already:
```
In [3]: import numpy as np
   ...: import torch
   ...: from torch.autograd import Variable
   ...: a = np.arange(10)
   ...: b = np.zeros([10])
   ...: c = np.zeros([1,1,10])
   ...: p = a > 5
   ...: at = torch.arange(10)
   ...: bt = torch.zeros(10)
   ...: ct = torch.zeros(1,1,10)
   ...: ct[:,:,p]
   ...:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-d0f58b700302> in <module>()
      9 bt = torch.zeros(10)
     10 ct = torch.zeros(1,1,10)
---> 11 ct[:,:,p]

IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors. The indexing object at posi
tion 2 is of type numpy.ndarray and cannot be converted
```

The fix will be in the next release.
