### ISSUE TITLE
ONNX Export: RuntimeError: !node->kind().is_aten() && !node->kind().is_prim() && !node->kind().is_attr()

### ISSUE THREAD

**Issue by pranjaldatta** [pytorch/pytorch#47042]
## 🐛 Bug

ONNX Export of a Custom Implementation of EfficientDet fails. The full error is, 

```
RuntimeError: !node->kind().is_aten() && !node->kind().is_prim() && !node->kind().is_attr() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/serialization/export.cpp":453, please report a bug to PyTorch. 
```

## To Reproduce

1. Download the Requirements mentioned [here](https://gist.github.com/pranjaldatta/e9653ab788c24dc080d5d89001e83844#file-requirements-txt)
2. Copy the main file [here](https://gist.github.com/pranjaldatta/e9653ab788c24dc080d5d89001e83844#file-infer_effdet-py)
3. In another file, in the same directory run the following code, 
```python
import os
import sys 

from infer_effdet.py import EfficientDet # the file we copied from the gist

import torch
import onnx
import numpy as np
import cv2

model = EfficientDet(
    num_classes=6
)

model = model.eval()

dummy = torch.randn(1, 3, 512, 512)
model.backbone_net.model.set_swish(memory_efficient=False)

torch.onnx.export(
    model, 
    dummy, 
    "trial6.onnx", 
    export_params=True, 
    verbose=False,
    opset_version=11, 
)

model.backbone_net.model.set_swish(memory_efficient=True)

```

## Expected behavior

The model should export without any error as the model works fine in normal inference mode.

## Error with Full stack trace

```shell
Warning: ONNX Scalar Type Analysis - Scalar types mismatch for tensor inputs of operator onnx::Mul. Please report a bug to PyTorch. The scalar type Double of the first tensor is chosen.
Warning: ONNX Scalar Type Analysis - Scalar types mismatch for tensor inputs of operator onnx::Mul. Please report a bug to PyTorch. The scalar type Double of the first tensor is chosen.
Traceback (most recent call last):
  File "src/models/efficientdet/convert_to_onnx.py", line 42, in <module>
    example_outputs=ret_val
  File "/home/pranjal/anaconda3/envs/oureye/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/pranjal/anaconda3/envs/oureye/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/pranjal/anaconda3/envs/oureye/lib/python3.7/site-packages/torch/onnx/utils.py", line 545, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: !node->kind().is_aten() && !node->kind().is_prim() && !node->kind().is_attr() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/serialization/export.cpp":453, please report a bug to PyTorch. 

```
## Environment

```shell
Collecting environment information...
PyTorch version: 1.6.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.0
[pip3] numpy==1.19.2
[pip3] torch==1.6.0+cpu
[pip3] torchvision==0.7.0+cpu
[conda] efficientnet-pytorch      0.7.0                    pypi_0    pypi
[conda] numpy                     1.19.2                   pypi_0    pypi
[conda] torch                     1.6.0+cpu                pypi_0    pypi
[conda] torchvision               0.7.0+cpu                pypi_0    pypi

```
## Additional context

 After looking at many different issues especially #45816 I refactored code to remove any List Unpack and unsupported operations. After a long drawn process of manual debugging, I figured, that in the *forward()* method of the *EfficientDet* Class, 
```python 

    def forward(self, x):


        is_training = False
        imgs = x 

        c3, c4, c5 = self.backbone_net(imgs)
        p3 = self.conv3(c3)
        p4 = self.conv4(c4)
        p5 = self.conv5(c5)
        p6 = self.conv6(c5)
        p7 = self.conv7(p6)

        features = [p3, p4, p5, p6, p7]
        features = self.bifpn(features)

        regression = torch.cat([self.regressor(feature) for feature in features], dim=1)
        classification = torch.cat([self.classifier(feature) for feature in features], dim=1)
        anchors = self.anchors(imgs)


            
        ret_val =  _scriptfied_func(anchors, regression, classification, imgs)
        
        #a = ret_val[0, :, 0]
        #b = ret_val[1, :, 0]
        #c = ret_val[2, :]
        #print(a)
        #print(ret_val.shape)
        sample_ret =  torch.stack([
        torch.zeros(64, 4), torch.zeros(64, 4), torch.zeros(64, 4)], dim=0)
        #print(sample_ret.shape) 
        return ret_val
```
if  **sample_ret** is returned, it compiles fine. But if I return, **ret_val** (which is what I need), it throws up the error above. 
Both **sample_ret** and **ret_val** are Tensors of shape [3, x, 4] created with torch.Stack operation. I am really at a loss why would this be an error. 

Any help is really appreciated!

**Comment by pranjaldatta** [comment]
Also, Any pointer regarding the reason for the occurrence of these warnings would be very helpful. 
```shell
Warning: ONNX Scalar Type Analysis - Scalar types mismatch for tensor inputs of operator onnx::Mul. Please report a bug to PyTorch. The scalar type Double of the first tensor is chosen.
```

**Comment by spandantiwari** [comment]
@KsenijaS - can you please take a look at this issue.

**Comment by KsenijaS** [comment]
@pranjaldatta runtime error is caused by prim::ListUnpackand will be fixed by this patch: https://github.com/pytorch/pytorch/pull/46264
Warnings are caused because ONNX scalar type analysis wasn't being consistent with PyTorch and will be fixed by this patch: https://github.com/pytorch/pytorch/pull/46629

**Comment by pranjaldatta** [comment]
@KsenijaS Thanks a lot! Would be waiting for the fixes! In the meantime, could you suggest some ways to bypass this at the first place, like the code snippets in the example above, that is causing this? So that I can refactor and avoid these at the first place? 

Sorry if that's asking too much, kinda a beginner in these things.

**Comment by KsenijaS** [comment]
@pranjaldatta change the line inside infer_effdet.py: batch_size, num_channels, height, width = img.shape
into:
batch_size, num_channels, height, width = img.shape[0], img.shape[1], img.shape[2], img.shape[3]
and that should avoid runtime error

**Comment by pranjaldatta** [comment]
Hey @KsenijaS, thanks for your help. It looks like the issue was resolved the above PRs. May I know when the fixes would be available for pip/conda install? or do I have to build from source? (sorry if this sounds like a too noob question)

**Comment by KsenijaS** [comment]
@pranjaldatta it is probably available on pytorch-nightly:
cpu: 
conda install pytorch torchvision torchaudio cpuonly -c pytorch-nightly
gpu, depending of cuda version installed:
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-nightly
