### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'get_filesystem'

### ISSUE THREAD

**Issue by seyeeet** [pytorch/pytorch#47139]
I am using pytorch 1.7 on ubuntu 14.04 and python 3.6.6
I am running this [document](https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html) from the pytorch doc for visualization but it gives me the following error at the stage:

```
# log embeddings
features = images.view(-1, 28 * 28)
writer.add_embedding(features,
                    metadata=class_labels,
                    label_img=images.unsqueeze(1))
writer.close()
```
I get this error:

```
2020-10-30 19:02:49.526278: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):

  File "/media/Seyeeet/office/tsne/untitled4.py", line 122, in <module>
    label_img=images.unsqueeze(1))

  File "/home/Seyeeet/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 792, in add_embedding
    fs = tf.io.gfile.get_filesystem(save_path)

AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'get_filesystem'
```
I am also using this version for tf and tb
```
from tensorboard import version; print(version.VERSION)
import tensorflow as tf; print(tf.__version__)
2.3.0
2.3.0
```

**Comment by sergedurand** [comment]
Hi,
I have the same error when running the example from https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_embedding

```python
import keyword
import torch
from torch.utils.tensorboard import SummaryWriter


meta = []
while len(meta)<100:
    meta = meta+keyword.kwlist # get some strings
meta = meta[:100]

for i, v in enumerate(meta):
    meta[i] = v+str(i)

label_img = torch.rand(100, 3, 10, 32)
for i in range(100):
    label_img[i]*=i/100.0

writer = SummaryWriter()
writer.add_embedding(torch.randn(100, 5), metadata=meta, label_img=label_img)
writer.add_embedding(torch.randn(100, 5), label_img=label_img)
writer.add_embedding(torch.randn(100, 5), metadata=meta)
writer.close()
```

Same error in a jupyter notebook local runtime, directly as .py file locally, and also on a google colab notebook:
https://colab.research.google.com/drive/1xQnGKw_1DECksgzXvpMyiqDs430hSw1y?usp=sharing

Also with tensorboard 2.3.0, and torch 1.6.0

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-51aba378bca8> in <module>()
     17 
     18 writer = SummaryWriter()
---> 19 writer.add_embedding(torch.randn(100, 5), metadata=meta, label_img=label_img)
     20 writer.add_embedding(torch.randn(100, 5), label_img=label_img)
     21 writer.add_embedding(torch.randn(100, 5), metadata=meta)

/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/writer.py in add_embedding(self, mat, metadata, label_img, global_step, tag, metadata_header)
    786         save_path = os.path.join(self._get_file_writer().get_logdir(), subdir)
    787 
--> 788         fs = tf.io.gfile.get_filesystem(save_path)
    789         if fs.exists(save_path):
    790             if fs.isdir(save_path):

AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'get_filesystem'
```

**Comment by mariosasko** [comment]
Try to uninstall tensorflow with pip. If `import tensorflow` returns ImportError then tensorboard fallbacks to tensorflow stub that has `get_filesystem` defined.

**Comment by seyeeet** [comment]
@mariosasko I already tried that and still get the error

**Comment by sergedurand** [comment]
Uninstalling tensforlow did work for me (if you're on a notebook you need to restart runtime), but it's not a very satisfying solution.

Anoter solution is to go to the tf() function at the root of the problem (should be where your python libraries are in "tensorboard\compat\ \__init\__.py") and comment out the attempt to import tensorflow:
```python
    # try:
    #     from tensorboard.compat import notf
    # except ImportError:
    #     try:
    #         import tensorflow
    # 
    #         return tensorflow
    #     except ImportError:
    #         pass
    from tensorboard.compat import tensorflow_stub

    return tensorflow_stub

```

However I don't know if it'll break something elsewhere...

**Comment by proger** [comment]
I found this quick monkey patching workaround that worked too: https://stackoverflow.com/a/61624923

```
import tensorflow as tf
import tensorboard as tb
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile
```

**Comment by shaswat-dharaiya** [comment]
Solution mentioned by @proger worked for me.
