### ISSUE TITLE
import torch: AttributeError: module 'torch.distributed' has no attribute 'BuiltinCommHookType'

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#47153]
After building the latest master https://github.com/pytorch/pytorch/commit/ee0033af9b7531ba0a453844dc621f8cfa140c20 with,

```bash
USE_DISTRIBUTED=0 USE_GLOO=0 BUILD_TEST=0 USE_CUDA=1 USE_MKLDNN=0 DEBUG=0 python setup.py install
```

On importing torch, I get the following error,
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.conda/envs/PytorchENV/lib/python3.7/site-packages/torch/__init__.py", line 526, in <module>
    from .functional import *
  File "/home/user/.conda/envs/PytorchENV/lib/python3.7/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/home/user/.conda/envs/PytorchENV/lib/python3.7/site-packages/torch/nn/__init__.py", line 3, in <module>
    from .parallel import DataParallel
  File "/home/user/.conda/envs/PytorchENV/lib/python3.7/site-packages/torch/nn/parallel/__init__.py", line 5, in <module>
    from .distributed import DistributedDataParallel
  File "/home/user/.conda/envs/PytorchENV/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 93, in <module>
    class DistributedDataParallel(Module):
  File "/home/user/.conda/envs/PytorchENV/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1064, in DistributedDataParallel
    self, comm_hook_type: dist.BuiltinCommHookType
AttributeError: module 'torch.distributed' has no attribute 'BuiltinCommHookType'
>>> 
```

Previously there was no issue with the same.

Probably related to https://github.com/pytorch/pytorch/commit/ee0033af9b7531ba0a453844dc621f8cfa140c20

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by jonasteuwen** [comment]
Same problem on OS X.

**Comment by robieta** [comment]
@SciPioneer This breaks and `USE_DISTRIBUTED=0` build.
