### ISSUE TITLE
torch.save has a maximum size regardless of RAM

### ISSUE THREAD

**Issue by gunthergl** [pytorch/pytorch#47201]
## To Reproduce

```
import torch

limit =      2147483647
over_limit = 2147483648

x = torch.zeros(limit)
torch.save(x, 'under_limit.pt')
x = torch.zeros(over_limit)  # fails
torch.save(x, 'over_limit.pt')
```

Traceback: 
```
Traceback (most recent call last):
  File "I_dont_think_you_need_my_path/2020-11-02_max_torch_save/03_torch_save_failing.py", line 9, in <module>
    torch.save(x, 'over_limit.pt')
  File "C:\Users\mi_so\.conda\envs\conda_base\lib\site-packages\torch\serialization.py", line 363, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "C:\Users\mi_so\.conda\envs\conda_base\lib\site-packages\torch\serialization.py", line 475, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
TypeError: write_record(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.PyTorchFileWriter, arg0: str, arg1: str, arg2: int) -> None
    2. (self: torch._C.PyTorchFileWriter, arg0: str, arg1: int, arg2: int) -> None

Invoked with: <torch._C.PyTorchFileWriter object at 0x00000204636340F0>, 'data/2217904421808', 2218188488832, -8589934592
```

## Expected behavior
The tensor should be saved without error. I found the numbers by testing and https://stackoverflow.com/questions/17298129/python-pickle-size-limit. The problem seems to be that in `def _save() [...] zip_file.write_record(name, storage.data_ptr(), num_bytes)` `num_bytes < 0`

I understand that this is mainly a pickle-issue and my workaround for the moment will be to check if a given tensor is over that limit. If it is, change to save the x.numpy() array with numpy. But I do not like it very much - is there a better option?

## Environment

python collect_env.py
```
[pip3] numpy==1.19.2
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38hb782905_0
[conda] mkl_fft                   1.2.0            py38h45dec08_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] numpy                     1.19.2           py38hadc3359_0
[conda] numpy-base                1.19.2           py38ha3acd2a_0
[conda] pytorch                   1.7.0               py3.8_cpu_0  [cpuonly]  pytorch
[conda] torchaudio                0.7.0                      py38    pytorch
[conda] torchvision               0.8.1                  py38_cpu  [cpuonly]  pytorch
```
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8.5

**Comment by mruberry** [comment]
cc @jamesr66a 

Thanks for reporting this issue, @gunthergl. This would be nice to fix, but I think we'd need to review the design of a fix before accepting a change.

**Comment by ProGamerGov** [comment]
I just ran into this issue, and it would be nice to have it fixed.

**Comment by thavlik** [comment]
I am having this issue as well with `1.7.1+cu110`.

**Comment by Handagot** [comment]
I am having the same issue with 1.9.1. Would be nice if it could be fixed.
