### ISSUE TITLE
USE_CUDA=0 python3 setup.py install failed on A64FX, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [pytorch/pytorch#47273]
... 
[50/350] Building CXX object test_api/CMakeFiles/test_api.dir/modules.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data/jw/pytorch/setup.py", line 724, in <module>
    build_deps()
  File "/data/jw/pytorch/setup.py", line 312, in build_deps
    build_caffe2(version=version,
  File "/data/jw/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/data/jw/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/data/jw/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake3', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '48']' returned non-zero exit status 1.

cc @malfet @seemethere @walterddr

**Comment by skyline75489** [comment]
Hi, can you please provide the info about what the exact subcommand is failing? Something like GCC error or linker error?

**Comment by LutzWeischerFujitsu** [comment]
USE_CUDA=0 python3 setup.py install --verbose > error.log
Traceback (most recent call last):
  File "/data/jw/pytorch/setup.py", line 724, in <module>
    build_deps()
  File "/data/jw/pytorch/setup.py", line 312, in build_deps
    build_caffe2(version=version,
  File "/data/jw/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/data/jw/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/data/jw/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake3', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '48']' returned non-zero exit status 1.

error.log attached 
[error.log](https://github.com/pytorch/pytorch/files/5523413/error.log)

**Comment by skyline75489** [comment]
Thanks. It seems that the compiler is not happy with the code. Can you run [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) and show us the output?

**Comment by LutzWeischerFujitsu** [comment]
Works now.

**Comment by walterddr** [comment]
closing this. please feel free to reopen if your problem hasn't been resolved
