### ISSUE TITLE
JIT PTX error when loading a TorchScript model that performs torch.exp(x**2), with pytorch 1.7.0 and nightly

### ISSUE THREAD

**Issue by IgnacioJPickering** [pytorch/pytorch#47304]
## 🐛 Bug

TorchScript compiled model fails after a few evaluations of calling autograd.grad, if the model executes torch.exp(x**2)
this happens in pytorch 1.7.0+cu101 and nightly pytorch

## To Reproduce

```
import torch
device = torch.device('cuda')
x = torch.tensor([0.],dtype=torch.double,requires_grad=True,device=device)

class Model(torch.nn.Module):
    def forward(self, x):
        return torch.exp(x**2)

# this code errors out
model_jit = torch.jit.script(Model()).to(device).double()
for j in range(3):
    out = model_jit(x)
    _ = torch.autograd.grad(out, x)

```

Error message:

```
Traceback (most recent call last):
  File "error.py", line 14, in <module>
    _ = torch.autograd.grad(out, x)
  File "/home/ignacio/anaconda3/envs/torchani/lib/python3.7/site-packages/torch/autograd/__init__.py", line 204, in grad
    inputs, allow_unused)
RuntimeError: CUDA driver error: a PTX JIT compilation failed
```

## Expected behavior

Code should run correctly with no errors

## Environment
```
Collecting environment information...
PyTorch version: 1.7.0+cu101
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 6000
Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] pytorch-memlab==0.2.2
[pip] torch==1.7.0+cu101
[pip] torchvision==0.7.0.dev20200610
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch-memlab            0.2.2                    pypi_0    pypi
[conda] torch                     1.7.0+cu101              pypi_0    pypi
[conda] torchvision               0.7.0.dev20200610          pypi_0    pypi
```

## Additional context

Code fails also with the nightly pytorch version. The x**2 inside exp is important for the code to fail, also it needs multiple sequential evaluations to fail. The same model not JIT scripted does not fail or produce any warnings or errors,  code works correctly on pytorch 1.6.0+cu101, code also fails in a GeForce 2080 Ti.

cc @gmagogsfm

**Comment by nickgg** [comment]
This looks like a bug in how the TensorExpr fuser lowers aten::pow, I'm looking into it.

**Comment by nickgg** [comment]
Added a fix for one issue, uncovered another and will update.
