### ISSUE TITLE
My demo app uses other package name will crash but org.pytorch.demo

### ISSUE THREAD

**Issue by binhongwang** [pytorch/pytorch#47342]
## 🐛 Bug
My demo app uses other package name will crash but org.pytorch.demo while loading pt.

## To Reproduce

I face a issue.My demo app uses other package name will crash but use org.pytorch.demo as pkgname is OK

Below is my crash stack
01-02 04:32:25.713 32127 32127 E AndroidRuntime: FATAL EXCEPTION: main
01-02 04:32:25.713 32127 32127 E AndroidRuntime: Process: com.tct.pt, PID: 32127
01-02 04:32:25.713 32127 32127 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tct.pt/com.tct.pt.MainActivity}: com.facebook.jni.CppException: empty_strided not implemented for CUDA
01-02 04:32:25.713 32127 32127 E AndroidRuntime: Exception raised from empty_strided at /var/lib/jenkins/workspace/build_android/aten/src/ATen/Functions.cpp:3806 (most recent call first):
01-02 04:32:25.713 32127 32127 E AndroidRuntime: (no backtrace available)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3500)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2115)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7762)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: Caused by: com.facebook.jni.CppException: empty_strided not implemented for CUDA
01-02 04:32:25.713 32127 32127 E AndroidRuntime: Exception raised from empty_strided at /var/lib/jenkins/workspace/build_android/aten/src/ATen/Functions.cpp:3806 (most recent call first):
01-02 04:32:25.713 32127 32127 E AndroidRuntime: (no backtrace available)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at org.pytorch.NativePeer.initHybrid(Native Method)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at org.pytorch.NativePeer.(NativePeer.java:24)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at org.pytorch.Module.load(Module.java:23)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at com.tct.pt.MainActivity.onCreate(MainActivity.java:21)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:8000)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7984)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1312)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3473)
01-02 04:32:25.713 32127 32127 E AndroidRuntime: ... 11 more

## Expected behavior
don't crash

## Environment
org.pytorch:pytorch_android:1.6.0

**Comment by ejguan** [comment]
Do you have some script which we could use to reproduce the problem?

**Comment by binhongwang** [comment]
Hi ejgun

> Do you have some script which we could use to reproduce the problem?

I can't reproduce this issue.It is strange.Have you fix this bug on org.pytorch:pytorch_android:1.6.0?
