### ISSUE TITLE
how to use torch.utils.checkpoint + gru with variable length sequence?

### ISSUE THREAD

**Issue by liuyyy111** [pytorch/pytorch#47439]
I just want to use torch.utils.checkpoint on GRU to save gpu memory.

```
    def check(self, packed):
        out, _ = self.rnn(packed)
        padded = pad_packed_sequence(out, batch_first=True)

        return padded

    def forward(self, x, lengths):
        """Handles variable size captions
        """
        x = self.embed(x)
   
        packed = pack_padded_sequence(x, lengths, batch_first=True)
        padded = checkpoint(self.check, packed)
```
my code is shown above.

i got a warning:
<b>UserWarning: None of the inputs have requires_grad=True. Gradients will be None</b>
because packed is a PackedSequence, it has no attribute requires_grad

then, i tried another way to do it
``` 
    def check(self, x, lengths):
        packed = pack_padded_sequence(x, lengths, batch_first=True)
        out, _ = self.rnn(packed)
        padded = pad_packed_sequence(out, batch_first=True)

        return padded

    def forward(self, x, lengths):
        """Handles variable size captions
        """
        x = self.embed(x)
        padded = checkpoint(self.check, x, lengths)
```
than i got a error. 

Traceback (most recent call last):
  File "D:\安装程序\PyCharm 2019.2.3\helpers\pydev\pydevd.py", line 2073, in <module>
    main()
  File "D:\安装程序\PyCharm 2019.2.3\helpers\pydev\pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\安装程序\PyCharm 2019.2.3\helpers\pydev\pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "D:\安装程序\PyCharm 2019.2.3\helpers\pydev\pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\安装程序\PyCharm 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/study/workspace/Python/xxxx/train.py", line 300, in <module>
    main()
  File "D:/study/workspace/Python/xxxx/train.py", line 144, in main
    train(opt, train_loader, model, epoch, val_loader)
  File "D:/study/workspace/Python/xxxx/train.py", line 181, in train
    model.train_emb(*train_data)
  File "D:\study\workspace\Python\SCAN\model.py", line 632, in train_emb
    loss.backward()
  File "D:\Environment\Anaconda\envs\PyTorch\lib\site-packages\torch\tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Environment\Anaconda\envs\PyTorch\lib\site-packages\torch\autograd\__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
<b>RuntimeError: element 1 of tensors does not require grad and does not have a grad_fn</b>

so, i want to know how can i use torch.utils.checkpoint on gru with variable length sequence

thank you

**Comment by glaringlee** [comment]
@zou3519 Any advise?

**Comment by kenenbek** [comment]
Any update?

**Comment by kenenbek** [comment]
I create similar question here https://discuss.pytorch.org/t/how-to-use-gradient-checkpointing-on-packed-sequence/121145

**Comment by PatrickFahy99** [comment]
> I created similar question here https://discuss.pytorch.org/t/how-to-use-gradient-checkpointing-on-packed-sequence/121145

any luck?
