### ISSUE TITLE
[fx] scripting a model with tensor list as input fails

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#47481]
Running a scripted symbolically traced model that expects tensor list as input fails.
It works on the symbolically traced model
 
Repro
```
class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        # type: (List[Tensor]) -> Tensor
        return x[0] + x[1]

m = M().eval()
input = [torch.rand(3, 3, dtype=torch.float), torch.rand(3, 3, dtype=torch.float)]
m(input)

traced = torch.fx.symbolic_trace(m)
script = torch.jit.script(traced)
traced(input) # works
script(input)
```

Throws the error
```
Traceback (most recent call last):
  File "examples/scripts/test_fx.py", line 57, in <module>
    script(input)
  File "/home/supriyar/local/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: forward() Expected a value of type 'Tensor (inferred)' for argument 'x' but instead found type 'list'.
Inferred 'x' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 1
Value: [tensor([[0.7001, 0.1083, 0.5039],
        [0.8313, 0.5919, 0.7486],
        [0.4022, 0.0909, 0.0835]]), tensor([[0.7651, 0.9900, 0.5516],
        [0.8685, 0.1888, 0.5661],
        [0.4313, 0.1694, 0.5259]])]
Declaration: forward(__torch__.torch.fx.graph_module.GraphModuleImpl self, Tensor x) -> (Tensor)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

cc @3l1

**Comment by supriyar** [comment]
@jamesr66a is this something you could help with?
