### ISSUE TITLE
multiprocess pickle error

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#47489]
I run in multiprocess mode, report error.
```
import torch.multiprocessing as mp
mp.spawn(
        self._process,
        nprocs=self.gpu_nums)
```
error info:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
... ...
Traceback (most recent call last):
  File "yolo_v3_train.py", line 192, in <module>
    process.run()
  File "/usr/local/python/lib/python3.7/site-packages/dh_aiflow/dh_aiflow_process/dh_aiflow_process.py", line 291, in run
    nprocs=self._dist_config.ngpus_per_node)
  File "/usr/local/python/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/python/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 5 terminated with signal SIGKILL
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/local/python/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
/usr/local/python/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/python/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/python/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
```

cc @mruberry

**Comment by glaringlee** [comment]
@as754770178 
Can you provide your environment info? like version of pytorch, cpu, memory, etc.
It would be very helpful to us if you can provide a minimal code to reproduce this.

And can you check your memory usage and try lower the number of process you created? From the log, it is also possible that you were running out of memory.

**Comment by as754770178** [comment]
I fix this issue by clean my memory.
