### ISSUE TITLE
[complex] torch.sqrt: Incorrect value on MacOS

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#47500]
With PR https://github.com/pytorch/pytorch/pull/47424 (newly added test_sqrt_complex_edge_values_cpu_complex64 fails on MacOS)

https://app.circleci.com/jobs/github/pytorch/pytorch/8729272

```
test_sqrt_complex_edge_values_cpu_complex64 - TestTorchDeviceTypeCPU
Traceback (most recent call last):
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 272, in instantiated_test
    result = test_fn(self, *args)
  File "test_torch.py", line 19753, in test_sqrt_complex_edge_values
    self.compare_with_numpy(torch.sqrt, np.sqrt, x)
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 954, in compare_with_numpy
    self.assertEqual(np_result, torch_result, **kwargs)
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1071, in assertEqual
    exact_dtype=exact_dtype, exact_device=exact_device)
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1183, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Scalars failed to compare as equal! Comparing the real part 0.0002494214568287134 and 754.97900390625 gives a difference of 754.9787544847932, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 0.000991472705078125!
```

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @anjali411 @dylanbespalko @mruberry @rgommers

**Comment by walterddr** [comment]
Did a bit of digging. seems like this has nothing to do with the vec256 but more of the fact that std::sqrt was implemented as (a*a + b*b)^0.5 where as the it should've been using something similar to `hypot`, e.g. |a| * (1+(b/a)^2)^0.5 .

**Comment by kshitij12345** [comment]
In that case, shouldn't first case blow up as well :thinking: ,
`-1e+20 * -1e+20 = 1e+40` which is outside of float's range

```
x = torch.tensor(0. - 1.0000e+20j, dtype=dtype, device=device)
self.compare_with_numpy(torch.sqrt, np.sqrt, x)

x = torch.tensor(-1.0000e+20 - 4988429.2000j, dtype=dtype, device=device)
self.compare_with_numpy(torch.sqrt, np.sqrt, x)
```

**Comment by ezyang** [comment]
Maybe Herbie can help. https://herbie.uwplse.org/

**Comment by malfet** [comment]
Looking at it now...

**Comment by malfet** [comment]
Here is a base-line C++ repro:
```
#include <complex>
#include <iostream>
#include <cmath>

int main(void) {
  std::complex<float> x(-1.0000e+20, - 4988429.2000);
  std::cout << "x=" << x << " std::sqrt(x)=" << std::sqrt(x) << std::endl;
  return 0;
}
```
Returns correct value if libstdc++ is used, but wrong one with  libc++

**Comment by malfet** [comment]
And `csqrtf` returns a correct result on Mac, but I'm not sure how to call it from the C++ compiler.
