### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_ClassVar'

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#47569]
`TORCH_CUDA_ARCH_LIST="5.2" NO_TEST=1 USE_MKLDNN=1 FULL_CAFFE2=1 python setup.py build`

brings me the following **ERROR** message:

```console
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "....../pytorch/tools/codegen/gen.py", line 15, in <module>
    from tools.codegen.model import *
  File "....../pytorch/tools/codegen/model.py", line 40, in <module>
    class Location:
  File "~/.local/lib/python3.8/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "~/.local/lib/python3.8/site-packages/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "~/.local/lib/python3.8/site-packages/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "~/.local/lib/python3.8/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "~/.local/lib/python3.8/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
-- 
CMake Error at cmake/Codegen.cmake:199 (message):
  Failed to get generated_cpp list
Call Stack (most recent call first):
  caffe2/CMakeLists.txt:2 (include)


-- Configuring incomplete, errors occurred!
See also "....../pytorch/build/CMakeFiles/CMakeOutput.log".
See also "....../pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 763, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    build_caffe2(version=version,
  File "....../pytorch/tools/build_pytorch_libs.py", line 54, in build_caffe2
    cmake.generate(version,
  File "....../pytorch/tools/setup_helpers/cmake.py", line 330, in generate
    self.run(args, env=my_env)
  File "....../pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=....../pytorch/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python3/dist-packages', '-DCUDA_NVCC_EXECUTABLE=/usr/local/cuda/bin/nvcc', '-DJAVA_HOME=/usr/lib/jvm/default-java', '-DNUMPY_INCLUDE_DIR=~/.local/lib/python3.8/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/bin/python', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_LIBRARY=/usr/lib/libpython3.8.so.1.0', '-DTORCH_BUILD_VERSION=1.8.0a0', '-DUSE_MKLDNN=1', '-DUSE_NUMPY=True', '....../pytorch']' returned non-zero exit status 1.
```

So, any suggestions?

cc @ezyang @gchanan @zou3519 @bdhirsh @malfet @seemethere @walterddr @rgommers @xuzhao9 @gramster

**Comment by heitorschueroff** [comment]
Marking as high priority as this is causing the build to fail.

**Comment by walterddr** [comment]
can you share your result for running `torch/utils/collect_env.py`? it seems like you installed a version of dataclasses that is not compatible
Another thing you can try is uninstalling it by running `pip uninstall dataclasses`

**Comment by ezyang** [comment]
This doesn't look like our problem, the error is in dataclasses, which shouldn't be installed on 3.8 anyway

**Comment by liyiyu36** [comment]
> can you share your result for running `torch/utils/collect_env.py`? it seems like you installed a version of dataclasses that is not compatible
> Another thing you can try is uninstalling it by running `pip uninstall dataclasses`

I uninstalled the dataclasses, and the error remians, throwing the same message.

**Comment by ezyang** [comment]
Can you post the "same" new error message? If you uninstalled dataclasses there should no longer be files at `~/.local/lib/python3.8/site-packages/dataclasses.py`

**Comment by rgommers** [comment]
No further follow-up and looks like an issue specific to the user environment, so closing. @jiapei100 if you think there's more to do here please feel free to reopen (and provide more details).
