### ISSUE TITLE
Pytorch 1.7.0 with cuda 11.1.1 and cudnn 8.0.5

### ISSUE THREAD

**Issue by WangWenhao0716** [pytorch/pytorch#47669]
Hi, currently cuda 11.1.1 and cudnn 8.0.5 are both available, according to former replies from Nvidia engineers, they will bring performance improvement to 3080/3090 GPUs.
The requested feature is when will PyTorch officially support them?
Thanks

**Comment by malfet** [comment]
We do plan to add support for CUDA-11.1 nightly binary builds soon.

**Comment by WangWenhao0716** [comment]
Thanks and please remind that cudnn8.0.5 is very important and do Not use 8.0.4.



发自我的iPhone


------------------ Original ------------------

**Comment by gjghks** [comment]
@malfet Hi, you mean that the error about 'RuntimeError: nvrtc: error' will be fixed in nightly version with cuda-11.1?

**Comment by malfet** [comment]
@WangWenhao0716 any reason why you need 8.0.5 in particular?

@gjghks can you please give more details about nvrtc error?

**Comment by WangWenhao0716** [comment]
according &nbsp;to Nvidia official report, cudnn8.0.5 brings “significant improvement on 3090”, therefore cudnn8.0.5 is needed.


By the way, my friend has tested cudnn8.0.5 using mxnet, a breakthrough performance on 3090 has been observed.



发自我的&nbsp;iPad


------------------ Original ------------------

**Comment by gjghks** [comment]
@malfet 

- my env
CUDA: v11.0 , cuDNN: v8.0.5.39
OS: Windows 10 Edu (build 19042.610)
GPU: Geforce RTX 3070
Driver version: 457.30
Using Pytorch nightly 1.8.0.dev20201110

I just run 'yolact' eval.py
I checked it is okay using other GPU not 30xx.

```
C:\ProgramData\Anaconda3\envs\sewer\python.exe D:/Code/yolact/eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.15 --top_k=15 --image=0005.jpg
Config not specified. Parsed yolact_base_config from the file name.

Loading model...C:\ProgramData\Anaconda3\envs\sewer\lib\site-packages\torch\jit\_recursive.py:197: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
C:\ProgramData\Anaconda3\envs\sewer\lib\site-packages\torch\jit\_recursive.py:197: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
C:\ProgramData\Anaconda3\envs\sewer\lib\site-packages\torch\jit\_recursive.py:197: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
 Done.
Traceback (most recent call last):
  File "D:/Code/yolact/eval.py", line 1105, in <module>
    evaluate(net, dataset)
  File "D:/Code/yolact/eval.py", line 881, in evaluate
    evalimage(net, args.image)
  File "D:/Code/yolact/eval.py", line 600, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "D:/Code/yolact/eval.py", line 151, in prep_display
    score_threshold   = args.score_threshold)
  File "D:\Code\yolact\layers\output_utils.py", line 98, in postprocess
    boxes[:, 1], boxes[:, 3] = sanitize_coordinates(boxes[:, 1], boxes[:, 3], h, cast=False)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)**

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_max_add_clamp_min_sub_clamp(int v0, float* t1, float* t2, int v3, float* aten_clamp, float* aten_clamp_1) {
{
  if (512 * blockIdx.x + threadIdx.x<2 ? 1 : 0) {
    float t1_1 = __ldg(t1 + 512 * blockIdx.x + threadIdx.x);
    float t2_1 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_clamp[512 * blockIdx.x + threadIdx.x] = (minimum(t2_1,t1_1)) - (float)(v0)<0.f ? 0.f : (minimum(t2_1,t1_1)) - (float)(v0);
    aten_clamp_1[512 * blockIdx.x + threadIdx.x] = (maximum(t2_1,t1_1)) + (float)(v0)>(float)(v3) ? (float)(v3) : (maximum(t2_1,t1_1)) + (float)(v0);
  }
}
}


Process finished with exit code 1
```

and I found the same error in google.

https://forums.developer.nvidia.com/t/isaac-gym-3090-issues/159080
https://forums.developer.nvidia.com/t/cuda-11-1-nvrtc-runtime-error-ga102-architecture/158083

I hope this issue will be fixed soon.

and please tell us.

**Comment by ngimel** [comment]
Please open a separate issue for this, it's a jit issue. cc @ZolotukhinM

**Comment by WangWenhao0716** [comment]
> @WangWenhao0716 any reason why you need 8.0.5 in particular?
> 
> @gjghks can you please give more details about nvrtc error?
The official [release-notes](https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html#rel-805).

**Comment by WangWenhao0716** [comment]
@malfet 
The cudnn 8.0.5 with PyTorch compiled by ourselves runs 7.8% to 26.4% much faster than PyTorch 1.7.0 with 8.0.3 on a single 3090 card.
The cudnn 8.0.5 with PyTorch compiled by ourselves runs 12.9% to 20.0% much faster than PyTorch 1.7.0 with 8.0.3 on four 3090 cards.
As a result, official support of cudnn 8.0.5 is necessary.
Thanks.

**Comment by peterjc123** [comment]
@malfet The latest cudatoolkit package on Anaconda Cloud is still 11.0.  https://anaconda.org/anaconda/cudatoolkit So it seems that we can only see them in the wheels packages.

**Comment by malfet** [comment]
@ngimel jit failure is likely caused by nvrtc from cuda-11.0 failing to compile for sm_86

**Comment by ngimel** [comment]
Yeah, so jit-generated kernels should be compiled for 80 in this case, like the rest of pytorch.

**Comment by lonce** [comment]
> We do plan to add support for CUDA-11.1 nightly binary builds soon.

Looking forward to that!

**Comment by mahirkukreja** [comment]
> We do plan to add support for CUDA-11.1 nightly binary builds soon.

@malfet Any updated on this?

**Comment by muladzevitali** [comment]
> We do plan to add support for CUDA-11.1 nightly binary builds soon.

@malfet Are there any updates?

**Comment by UlrichFreitag** [comment]
@JVedant yes it works, but it is not as optimized as using CUDA 11.1. In my experience, I had better performance with a custom build of PyTorch (see https://github.com/pytorch/pytorch/issues/48588#issuecomment-746425124) compiled with CUDA 11.1.

For what I remember, CUDA 11.1 (and upper) with the static CuDNN 8.0.5 build on it gives better performance that using a CuDNN 8.0.5 build on CUDA 11.0.

I think @janeyx99 had some annoying linking issues while trying to enable this support in a good way as you can see here: https://github.com/pytorch/pytorch/issues/48588#issuecomment-736081324

But with CUDA 11.2 out, I would believe that adding an official support gets critical now for performance reasons. Maybe @janeyx99, @ptrblck or @seemethere have more information on when this support would be available?

**Comment by malfet** [comment]
Adding sm_86 while keeping all other architectures is not easy, as it pushes binary size above 2GB limit, which results in internal linker error among other things.

**Comment by WangWenhao0716** [comment]
A possible solution is deleting out-of-date architectures.



发自我的&nbsp;iPad


------------------ Original ------------------

**Comment by UlrichFreitag** [comment]
> Adding sm_86 while keeping all other architectures is not easy, as it pushes binary size above 2GB limit, which results in internal linker error among other things.

I see. Does that means that the support of this won't be in the officials build of PyTorch 1.8?
