### ISSUE TITLE
How to install Pytorch on AIX7.2 without internet access?

### ISSUE THREAD

**Issue by bergen288** [pytorch/pytorch#47681]
I am trying to install Pytorch on AIX7.2 server without internet access.  I have pytorch-1.0.2.tar.gz from PYPI website and run the PIP installation as ```python -m pip install Flask --no-build-isolation --no-index --find-links ./ $pkg``` where $pkg is pytorch-1.0.2.tar.gz.  However, it has the following error.  How to fix it?  Is it possible to install pytorch on a server without internet access?

Thanks.
```
Looking in links: ./
Processing ./pytorch-1.0.2.tar.gz
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py): started
  Building wheel for pytorch (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-84fugyap/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-84fugyap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-640v38y9
       cwd: /tmp/pip-req-build-84fugyap/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-84fugyap/setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
    Running setup.py install for pytorch: started
    Running setup.py install for pytorch: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-84fugyap/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-84fugyap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k2dyu_63/install-record.txt --single-version-externally-managed --compile --install-headers /opt/freeware/include/python3.7m/pytorch
         cwd: /tmp/pip-req-build-84fugyap/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-84fugyap/setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-84fugyap/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-84fugyap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k2dyu_63/install-record.txt --single-version-externally-managed --compile --install-headers /opt/freeware/include/python3.7m/pytorch Check the logs for full command output.
```

**Comment by malfet** [comment]
From the error message it looks like you need to rename the source package to `torch-1.0.2.tar.gz` before invoking the pip command. Alternatively, one can untar the package and then invoke setup.py with develop option: `python setup.py develop`
