### ISSUE TITLE
Error in test_quantize - missing FBGEMM implementation

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#47748]
## 🐛 Bug

I'm getting errors on our power machine with various tests in test_quantize where the results vary wildly. Some tests in that file are decorated with `skipIfNoFBGEMM` but some are not.

So first question would then be when exactly FBGEMM is required. And if it is "correct" that results may vary wildly when it isn't present or if a hard error is more appropriate and missing somewhere.

One if the failing test is at
https://github.com/pytorch/pytorch/blob/ae5c2febb912066f1a8dec8b54451c09195b2c6d/test/quantization/test_quantize.py#L539

It looks very similar to the test above it but is not decorated with `skipIfNoFBGEMM` 

## To Reproduce

1. Build without FBGEMM (USE_FBGEMM=0)
1. run test_quantize

```
======================================================================
FAIL: test_quantized_embedding_bag (quantization.test_quantize.TestPostTrainingStatic)
Test the post-training quantization flow, serialization and scripting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pytorch-1.7.0/test/quantization/test_quantize.py", line 556, in test_quantized_embedding_bag
    self.checkScriptable(quantized_model, [[indices, offsets, per_sample_weights]], check_save_load=True)
  File "<prefix>/lib/python3.7/site-packages/torch/testing/_internal/common_quantization.py", line 455, in checkScriptable
    self._checkScriptable(orig_mod, scripted, calib_data, check_save_load)
  File "<prefix>/lib/python3.7/site-packages/torch/testing/_internal/common_quantization.py", line 463, in _checkScriptable
    self._checkModuleCorrectnessAgainstOrig(orig_mod, script_mod, calib_data)
  File "<prefix>/lib/python3.7/site-packages/torch/testing/_internal/common_quantization.py", line 480, in _checkModuleCorrectnessAgainstOrig
    self.assertEqual(scripted_output, ref_output)
  File "<prefix>/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1136, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 28 element(s) (out of 72) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.8254044849182073e+31 (1.0050204780942328e+20 vs. 1.8254044849282575e+31), which occurred at index (4, 8).

======================================================================
FAIL: test_embedding_byte (quantization.test_quantized_op.TestQuantizedEmbeddingOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pytorch-1.7.0/test/quantization/test_quantized_op.py", line 3017, in test_embedding_byte
    embedding_dim=st.integers(5, 50).filter(lambda x: x % 4 == 0))
  File "/sw/installed/hypothesis/4.44.2-GCCcore-8.3.0-Python-3.7.4/lib/python3.7/site-packages/hypothesis/core.py", line 991, in wrapped_test
    raise the_error_hypothesis_found
  File "/pytorch-1.7.0/test/quantization/test_quantized_op.py", line 3045, in test_embedding_byte
    torch.testing.assert_allclose(ref, qresult, atol=0.005, rtol=1e-3)
  File "<prefix>/lib/python3.7/site-packages/torch/testing/__init__.py", line 223, in assert_allclose
    raise AssertionError(msg)
AssertionError: With rtol=0.001 and atol=0.005, found 216 element(s) (out of 216) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.988373875617981 (1.988373875617981 vs. 2.3694278276172396e-38), which occurred at index (7, 4).

======================================================================
FAIL: test_embedding_api (quantization.test_quantized_module.TestStaticQuantizedModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pytorch-1.7.0/test/quantization/test_quantized_module.py", line 711, in test_embedding_api
    num_embeddings=st.integers(10, 50),
  File "/sw/installed/hypothesis/4.44.2-GCCcore-8.3.0-Python-3.7.4/lib/python3.7/site-packages/hypothesis/core.py", line 991, in wrapped_test
    raise the_error_hypothesis_found
  File "/pytorch-1.7.0/test/quantization/test_quantized_module.py", line 739, in test_embedding_api
    self.assertEqual(module_out, ref)
  File "<prefix>/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1136, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 11 element(s) (out of 224) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 6.992425247630423e+23 (9.090164966199132e+17 vs. 6.992434337795389e+23), which occurred at index (7, 0)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): RHEL 7.7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Python version: 3.7.4
 - CUDA/cuDNN version: 10.1
 - Any other relevant information: Fails on POWER and x86 if FBGEMM is disabled

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by Flamefire** [comment]
I traced this to this TODO comment which is still present in master: https://github.com/pytorch/pytorch/blob/ae5c2febb912066f1a8dec8b54451c09195b2c6d/aten/src/ATen/native/quantized/cpu/qembeddingbag.cpp#L306

This should have never passed QC, I don't mind it not being implemented yet, but then please at least add a `TORCH_CHECK(false, "This PyTorch installation was not built with FBGEMM operators");` or similar so a clear error is raised and not simply have the computation skipped.

**Comment by vkuzo** [comment]
@supriyar , would you be interested in taking a look?

**Comment by supriyar** [comment]
Thanks for flagging, yes these tests should have the skipIfNoFBGEMM decorator on them. I'm surprised they passed CI, I thoguht we do run tests there without FBGEMM enabled. 
I'll fix this and and a `TORCH_CHECK` in the non-fbgemm path
