### ISSUE TITLE
Exporting a scripted LSTM failed with "Modules that are called during a trace must be registered as submodules of the thing being traced"

### ISSUE THREAD

**Issue by wangzbo** [pytorch/pytorch#47887]
I am trying to export LSTM using torch.jit.script(), but failed with the error:

RuntimeError: **Tried to trace <__torch__.LSTMWrapper object at 0x7f9bade35020> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.**

OS: mac 10.14.6
python: 3.7.6 64-bit
pytorch: 1.6.0

Here is the simple code to recreate:

```
import torch
from torch.nn import LSTM
from typing import Tuple, Optional
from torch import Tensor

class LSTMWrapper(torch.nn.Module):
    def __init__(self,input_size: int, hidden_size: int,
                 num_layers: int = 1, batch_first: bool = False,
                 dropout: float = 0.):
        super(LSTMWrapper, self).__init__()  
        self.lstm = LSTM(input_size=input_size,
                           hidden_size=hidden_size,
                           batch_first=batch_first,
                           num_layers=num_layers,
                           dropout=dropout)

    def forward(self, inp:Tensor, hidden:Optional[Tuple[Tensor, Tensor]] = None)->Tuple[Tensor,Tuple[Tensor, Tensor]]:
        return self.lstm(inp, hidden)

class ScriptLSTMModel(torch.nn.Module):
    def __init__(self):
        super(ScriptLSTMModel, self).__init__()  
        self.script_lstm = torch.jit.script(LSTMWrapper(input_size=300,
                           hidden_size=50,
                           batch_first=True,
                           num_layers=2,
                           dropout=0.3))
    def forward(self, inp, hidden = None):
        return self.script_lstm(inp, hidden)


script_lstm = ScriptLSTMModel()
output=script_lstm(torch.rand(5,11,300))
torch.onnx.export(script_lstm, 
        torch.rand(5,11,300),
        "./scriptLSTM.onnx", 
        opset_version=11,
        export_params=True, 
        example_outputs = output,
        verbose=True, 
        do_constant_folding=False)
```

Is this an issue or am I using the exoprt or torch.jit.script incorrectly? Thank you for any comments.

**Comment by suo** [comment]
I believe the ONNX exporter's support for scripted modules (as opposed to exporting an `nn.Module` directly) is still a work in progress. cc @spandantiwari for further commentary.

**Comment by spandantiwari** [comment]
From first look, this could be an issue with conversion to ScriptModule using torch.jit.script. There is an open issue with scripting RNNs: https://github.com/pytorch/pytorch/issues/28418

**Comment by suo** [comment]
@spandantiwari I think this is a separate issue, as the model is correctly scripting, but failing in the ONNX export step

**Comment by wangzbo** [comment]
Thank you for your replies. I think it is not the same as issue #28418, since it did not export the model to onnx format.
If I comment out the lines of "torch.onnx.export()", there is no error thrown and I can successfully print the output. 

I paste the full trace here:

> 
>   File "/Users/wangzbo/work/simple.py", line 42, in <module>
>     do_constant_folding=False)
>   File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
>     custom_opsets, enable_onnx_checker, use_external_data_format)
>   File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
>     use_external_data_format=use_external_data_format)
>   File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
>     fixed_batch_size=fixed_batch_size)
>   File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
>     graph, torch_out = _trace_and_get_graph_from_model(model, args)
>   File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
>     torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
>   File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
>     outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 426, in forward
>     self._force_outplace,
>   File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 412, in wrapper
>     outs.append(self.inner(*trace_inputs))
>   File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
>     result = self._slow_forward(*input, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
>     result = self.forward(*input, **kwargs)
>   File "/Users/wangzbo/work/simple.py", line 29, in forward
>     return self.script_lstm(inp, hidden)
>   File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
>     result = self._slow_forward(*input, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 694, in _slow_forward
>     return self.forward(*input, **kwargs)
> RuntimeError: Tried to trace <__torch__.LSTMWrapper object at 0x7fdd3615c0f0> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.

@suo @spandantiwari

**Comment by spandantiwari** [comment]
Understood. 
@wangzbo - have you looked at the doc page for ONNX: https://pytorch.org/docs/master/onnx.html
There are some details and tips listed there (particularly related to indexing and tracing vs scripting) which may be useful. You may need to update some parts of the model code (based on the error message).

**Comment by neginraoof** [comment]
This is actually a tracer issue. Tracer only knows type Tensor for all input, output, and intermediate values. In this case, looks like the issue is that tracer is not able to turn the LSTMWrapper class into a tensor value. Is there a reason why you are not scripting the ScriptLSTMModel class?

**Comment by zheddie** [comment]
Not sure whether this is same issue, but I also got error on onnx.export on a scripted_lstm as blow:
```
class myLSTM2(torch.nn.Module):
    def __init__(self):
        super(myLSTM2, self).__init__()  
        self.lstm = LSTM(input_size=300,
                           hidden_size=50,
                           batch_first=True,
                           num_layers=2,
                           dropout=0.3)

    def forward(self, inp:Tensor, hidden:Optional[Tuple[Tensor, Tensor]] = None)->Tuple[Tensor,Tuple[Tensor, Tensor]]:
        return self.lstm(inp, hidden)
mm = myLSTM2()
mm.eval()
inputs = torch.rand(64,11,300)
tmm = torch.jit.script(mm,inputs)
output=tmm(inputs)
torch.onnx.export(tmm 
        ,inputs
        ,"./myLSTM.onnx" 
        ,opset_version=11
        ,export_params=True 
        ,example_outputs = output
        ,verbose=True
        ,do_constant_folding=False
        )
```
The error message is as below:
```
Traceback (most recent call last):
  File "zbtestlstm2.py", line 43, in <module>
    ,do_constant_folding=False
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 411, in _model_to_graph
    use_new_jit_passes)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 359, in _create_jit_graph
    method_graph, params = torch._C._jit_pass_lower_graph(graph, model._c)
RuntimeError: Unknown type bool encountered in graph lowering. This type is not supported in ONNX export.
```

**Comment by zheddie** [comment]
@suo, Hi , you help to take a look on it ? We are trying creating a scripted LSTM ONNX model . I tried to dig further into the pytorch code, looks like the error is coming from here: Does it mean that we only support following non-Tensor type of Object? In fact, I didn't figure out why a "bool" type of data was generated from lower_graph() routine. 
```
      TORCH_CHECK(
          (type ==
           getCustomClass(
               "__torch__.torch.classes.quantized.Conv2dPackedParamsBase")) ||
              (type ==
               getCustomClass(
                   "__torch__.torch.classes.quantized.Conv3dPackedParamsBase")) ||
              (type ==
               getCustomClass(
                   "__torch__.torch.classes.quantized.LinearPackedParamsBase")),
          "Unknown type ",
          type->repr_str(),
          " encountered in graph lowering. This type is not supported in ONNX export.");
```

**Comment by zheddie** [comment]
with the debug of lower_graph() routine, I figured out that module's "attr::name" attribute's string value is "lstm". This "lstm" submodule's type is "__torch__.torch.nn.modules.rnn.LSTM". This submodule's "attr::name" attribute's string value is "training", and this attribute's  type is "bool", which is finally causing the failure message above.  Really don't know why the attr::name of a LSTM is a bool IValue. :-(.

**Comment by zheddie** [comment]
From the class Module , looks like the "training" is one bool field, but it's for the base class Module, which is not specific for RNNBase or even LSTM. Didn't know why the LSTM module 's "attr::name" attribute slot is pointing to the "training" attribute.

**Comment by ppwwyyxx** [comment]
Changing this line:
https://github.com/pytorch/pytorch/blob/515d9fb2a99586e62cfb941cfc51e86e7d58c1f4/torch/csrc/jit/python/pybind_utils.h#L973
to `if (true)` should make the code trace correctly.

However that's obviously not a correct fix. 
One potential solution is to add a new flag/option/tracing mode in pytorch, that would trace scripted module by executing them, instead of just including their code. 
Having this mode will also help with internal issues like https://fb.workplace.com/groups/1405155842844877/posts/5235887943104962/ and https://fb.workplace.com/groups/1405155842844877/posts/5105952749431816/.

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1552836>

**Comment by veriff-javiervgd** [comment]
Is there any updates on this? I have the exact same use case described by @wangzbo with exact same error. My use case: trying to export a Object Detection model for which the anchor generation depends on the input image size (which is dynamic). So the rest of the model is traced but I would like the anchors generation module to be scripted.

**Comment by vietvq1511** [comment]
Has this issue been fixed yet? I also have the exact same use case as described by @wangzbo so I would really appreciate somebody to tell me if this has been fixed or are there any workaround for this error.

**Comment by justinchuby** [comment]
Can reproduce

**Comment by borisfom** [comment]
@ppwwyyxx : The error is still there. That prevents some important nets to be exported in ONNX for NVIDIA Riva.

**Comment by borisfom** [comment]
Also, observation: export passes if the top-level module is  ScriptModule, so calling jit.trace() on the whole model before onnx.export can serve as workaround. Note: in that case, onnx.export still fails if jit.freeze() is called.

**Comment by csukuangfj** [comment]
> ONNX export of any TorchScript submodule (scripted or traced) fails with "Modules that are called during a trace must be registered as submodules of the thing being traced" #86261

Thanks! This works for me. See https://github.com/kakashidan/icefall/pull/2

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
