### ISSUE TITLE
TorchScript is unable to distinguish int and ScalarType

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#47964]
## 🐛 Bug

I am adding a new operator `tensor.view(dtype)` in https://github.com/pytorch/pytorch/pull/47951, and getting lots of JIT failures.

With https://github.com/pytorch/pytorch/pull/47951, the script to reproduce this issue is

```python
import torch

def f(x):
    return x.view(-1)

s = torch.jit.script(f)
print(s.graph)

x = torch.randn(5, 5, 5)
s(x)
```

and there will be an error message

```
graph(%x.1 : Tensor):
  %4 : int = prim::Constant[value=-1]() # jit-view.py:4:18
  %5 : Tensor = aten::view(%x.1, %4) # jit-view.py:4:11
  return (%5)

Traceback (most recent call last):
  File "jit-view.py", line 10, in <module>
    s(x)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "jit-view.py", line 4, in f
def f(x):
    return x.view(-1)
           ~~~~~~ <--- HERE
RuntimeError: Viewing a tensor as a new dtype with different bytes is not supported.
```

**Comment by zasdfgbnm** [comment]
Does ScalarType has to be int in JIT? Can I change it to a new type `ScalarType`?

**Comment by mruberry** [comment]
Can you elaborate on what's going on here? 

I was expecting to see x.view(torch.int32) based on your description.

**Comment by zasdfgbnm** [comment]
@mruberry I am doing
```python
x.view(-1)
```
where the `-1` has type int, and in principle, JIT should find and execute the overload
```
aten::view(Tensor(a) self, int[] size) -> Tensor(a)
```
However, JIT does not have a separate type for `ScalarType` in [jit_type.h](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/jit_type.h), and all `ScalarType` are considered as `int`. As a result, JIT will find and execute the wrong overload
```
aten::view(Tensor(a) self, ScalarType dtype) -> Tensor(a)
```

**Comment by mruberry** [comment]
I see. Would a temporary workaround be to add a kwarg-only "dtype" to view()? So you could do view(shape, dtype=...)? That wouldn't be a copy of NumPy's API but it would provide a mechanism to use the functionality.

**Comment by zasdfgbnm** [comment]
What if I don't want to change the shape, and only the dtype?

**Comment by mruberry** [comment]
t.view(t.shape, dtype=...)

**Comment by mruberry** [comment]
I suppose what bites about that is you probably rarely (never?) want to change both the dtype and the shape, though. Maybe not a compelling option.

**Comment by zasdfgbnm** [comment]
I don't know. Let me try adding a new JIT type to get an idea of how easy/hard it is.

**Comment by mruberry** [comment]
There are other options we can consider (after sleeping on it):

- creating a new function, like `view_as_dtype`
- reusing the `view_as` function

**Comment by zasdfgbnm** [comment]
@mruberry Yeah, these two sound like a plan too.

**Comment by zasdfgbnm** [comment]
Looks like there are related PRs: https://github.com/pytorch/pytorch/pull/30694 https://github.com/pytorch/pytorch/pull/31074

**Comment by zasdfgbnm** [comment]
@mruberry Look like a better solution is to modify codegen to blocklist the new overload from generating JIT registry?

**Comment by mruberry** [comment]
Sound good. I think it's very unlikely someone would want to jit this operation, or a program involving this operation.

**Comment by suo** [comment]
This is sadly the result of a long-standing issue where we pun `ScalarType` and `LayoutType` to just be ints in the JIT type system. It's a little bit tricky to fix due to backward compatibility concerns, but we should commit to doing so. cc @gmagogsfm to add to our plans for next half

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
