### ISSUE TITLE
"No module named torch.version"

### ISSUE THREAD

**Issue by Myrakami** [pytorch/pytorch#47968]
Help
I'm trying to run a script and generates the error "No module named torch.version"
What should I do?

```
C:\Users\Murakami\Desktop\super-resolution-master>pip freeze
dataclasses==0.6
future==0.18.2
lxml==4.6.1
numpy==1.19.4
Pillow==8.0.1
pytils==0.3
PyYAML==5.3.1
six==1.15.0
tools==0.1.9
torch==1.7.0
torchaudio==0.7.0
torchvision==0.8.1
typing-extensions==3.7.4.3

C:\Users\Murakami\Desktop\super-resolution-master>python main.py -m srgan
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from torch.utils.data import DataLoader
  File "C:\Users\Murakami\AppData\Local\Programs\Python\Python38\torch\__init__.py", line 24, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'torch.version'

C:\Users\Murakami\Desktop\super-resolution-master>
```

**Comment by peterjc123** [comment]
How did you install PyTorch?

**Comment by Myrakami** [comment]
> How did you install PyTorch?

Command line of this site
`pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
`

**Comment by Myrakami** [comment]
I fixed the problem: reinstalled python.
