### ISSUE TITLE
build pytorch from source on ubuntu, building error from fbgemm::SparseAdaGradSignature

### ISSUE THREAD

**Issue by CnybTseng** [pytorch/pytorch#47993]
Compiling  functions.cu                        > /data/tseng/toolkit/pytorch/build/nccl/obj/collectives/device/functions.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/queue/rebatching_queue.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/queue/rebatching_queue_ops.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/adadelta_op.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/adagrad_fused.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/adagrad_op.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/adam_op.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/clip_tensor_op.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/ftrl_op.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/gftrl_op.cc.o
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/iter_op.cc.o
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.h:3:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.cc:1:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h: In member function 'bool caffe2::SparseAdagradOp::DoRunWithType()':
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:253:16: error: no match for call to '(fbgemm::SparseAdaGradSignature<int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int32_t*, float&, const float& '
           lr[0]);
                ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.h:3:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.cc:1:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:263:16: error: no match for call to '(fbgemm::SparseAdaGradSignature<long int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const long int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int64_t*, float&, const float&)'
           lr[0]);
                ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_fused.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const long int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:0:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h: In member function 'bool caffe2::SparseAdagradOp::DoRunWithType()':
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:253:16: error: no match for call to '(fbgemm::SparseAdaGradSignature<int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int32_t*, float&, const float& '
           lr[0]);
                ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:0:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:263:16: error: no match for call to '(fbgemm::SparseAdaGradSignature<long int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const long int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int64_t*, float&, const float&)'
           lr[0]);
                ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const long int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
[ 67%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/sgd/lars_op.cc.o
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:0:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h: In instantiation of 'bool caffe2::RowWiseSparseAdagradOp<Context>::DoRunWithType() [with SIndex = int; Context = caffe2::CPUContext]':
/data/tseng/toolkit/pytorch/caffe2/core/operator.h:1302:1:   required from 'static bool caffe2::DispatchHelper<caffe2::TensorTypes<FirstType, Types ...>, ExtraArgs ...>::call(Op*, const caffe2::TypeMeta&) [with Op = caffe2::RowWiseSparseAdagradOp<caffe2::CPUContext>; FirstType = int; Types = {long int}; ExtraArgs = {}]'
/data/tseng/toolkit/pytorch/caffe2/core/operator.h:1302:1:   required from 'static bool caffe2::DispatchHelper<caffe2::TensorTypes<FirstType, Types ...>, ExtraArgs ...>::call(Op*, const caffe2::Tensor&) [with Op = caffe2::RowWiseSparseAdagradOp<caffe2::CPUContext>; FirstType = int; Types = {long int}; ExtraArgs = {}]'
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:376:63:   required from 'bool caffe2::RowWiseSparseAdagradOp<Context>::RunOnDevice() [with Context = caffe2::CPUContext]'
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:215:1:   required from here
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:434:26: error: no match for call to '(fbgemm::SparseAdaGradSignature<int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int*, float&, const float&)'
       num_rows_processed = kernel_i32_(
                          ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:0:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:444:26: error: no match for call to '(fbgemm::SparseAdaGradSignature<long int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const long int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int64_t*, float&, const float&)'
       num_rows_processed = kernel_i64_(
                          ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const long int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:0:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h: In instantiation of 'bool caffe2::RowWiseSparseAdagradOp<Context>::DoRunWithType() [with SIndex = long int; Context = caffe2::CPUContext]':
/data/tseng/toolkit/pytorch/caffe2/core/operator.h:1302:1:   required from 'static bool caffe2::DispatchHelper<caffe2::TensorTypes<FirstType, Types ...>, ExtraArgs ...>::call(Op*, const caffe2::TypeMeta&) [with Op = caffe2::RowWiseSparseAdagradOp<caffe2::CPUContext>; FirstType = long int; Types = {}; ExtraArgs = {}]'
/data/tseng/toolkit/pytorch/caffe2/core/operator.h:1302:1:   required from 'static bool caffe2::DispatchHelper<caffe2::TensorTypes<FirstType, Types ...>, ExtraArgs ...>::call(Op*, const caffe2::TypeMeta&) [with Op = caffe2::RowWiseSparseAdagradOp<caffe2::CPUContext>; FirstType = int; Types = {long int}; ExtraArgs = {}]'
/data/tseng/toolkit/pytorch/caffe2/core/operator.h:1302:1:   required from 'static bool caffe2::DispatchHelper<caffe2::TensorTypes<FirstType, Types ...>, ExtraArgs ...>::call(Op*, const caffe2::Tensor&) [with Op = caffe2::RowWiseSparseAdagradOp<caffe2::CPUContext>; FirstType = int; Types = {long int}; ExtraArgs = {}]'
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:376:63:   required from 'bool caffe2::RowWiseSparseAdagradOp<Context>::RunOnDevice() [with Context = caffe2::CPUContext]'
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:215:1:   required from here
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:434:26: error: no match for call to '(fbgemm::SparseAdaGradSignature<int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const int32_t*, float&, const float& '
       num_rows_processed = kernel_i32_(
                          ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
In file included from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:0:
/data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:444:26: error: no match for call to '(fbgemm::SparseAdaGradSignature<long int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const long int*, float, float, float)>}) (long int&, int64_t, float*&, const float*&, float*&, const long int*, float&, const float&)'
       num_rows_processed = kernel_i64_(
                          ^
In file included from /data/tseng/toolkit/pytorch/caffe2/core/operator.h:9:0,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.h:3,
                 from /data/tseng/toolkit/pytorch/caffe2/sgd/adagrad_op.cc:1:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = int; _ArgTypes = {int, long unsigned int, float*, const float*, float*, const long int*, float, float, float}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   candidate expects 9 arguments, 8 provided
caffe2/CMakeFiles/torch_cpu.dir/build.make:10984: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/sgd/adagrad_fused.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/sgd/adagrad_fused.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
caffe2/CMakeFiles/torch_cpu.dir/build.make:10997: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/sgd/adagrad_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/sgd/adagrad_op.cc.o] Error 1
Archiving  objects                             > /data/tseng/toolkit/pytorch/build/nccl/obj/collectives/device/colldevice.a
Linking    libnccl.so.2.7.8                    > /data/tseng/toolkit/pytorch/build/nccl/lib/libnccl.so.2.7.8
Generating nccl.pc.in                          > /data/tseng/toolkit/pytorch/build/nccl/lib/pkgconfig/nccl.pc
Archiving  libnccl_static.a                    > /data/tseng/toolkit/pytorch/build/nccl/lib/libnccl_static.a
/data/tseng/toolkit/pytorch/third_party/nccl/nccl/src
[ 67%] No install step for 'nccl_external'
[ 67%] Completed 'nccl_external'
[ 67%] Built target nccl_external
[ 67%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/gloo_cuda_generated_cuda.cu.o
[ 67%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
[ 67%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/gloo_cuda_generated_cuda_private.cu.o
CMakeFiles/Makefile2:9310: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target gloo_cuda
[ 68%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_local.cc.o
[ 68%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_ring.cc.o
[ 68%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_bcube.cc.o
[ 68%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_halving_doubling.cc.o
[ 68%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_broadcast_one_to_all.cc.o
[ 68%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/cuda_allreduce_ring_chunked.cc.o
[ 68%] Linking CXX static library ../../../lib/libgloo_cuda.a
[ 68%] Built target gloo_cuda
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    cmake=cmake)
  File "/data/tseng/toolkit/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/data/tseng/toolkit/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/data/tseng/toolkit/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/opt/conda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 2.
root@eb7398d8aac0:/data/tseng/toolkit/pytorch#

**Comment by skyline75489** [comment]
Can you run [collect_env.py](https://github.com/pytorch/pytorch/blob/513f62b45ba18edff9cf034d09bd12803485db40/torch/utils/collect_env.py) and show us the output?

Please read the issue instruction and do not delete the issue template. Otherwise there's no way we can have enough information about the issue.

**Comment by CnybTseng** [comment]
> Can you run [collect_env.py](https://github.com/pytorch/pytorch/blob/513f62b45ba18edff9cf034d09bd12803485db40/torch/utils/collect_env.py) and show us the output?
> 
> Please read the issue instruction and do not delete the issue template. Otherwise there's no way we can have enough information about the issue.

In PyTorch source directory:
# python torch/utils/collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "torch/utils/collect_env.py", line 429, in <module>
    main()
  File "torch/utils/collect_env.py", line 424, in main
    output = get_pretty_env_info()
  File "torch/utils/collect_env.py", line 419, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "torch/utils/collect_env.py", line 276, in get_env_info
    if torch.version.hip is None:  # cuda version
AttributeError: module 'torch.version' has no attribute 'hip'

**Comment by skyline75489** [comment]
No. Do not run the script under PyTorch source directory. The source code itself interferes with the `collect_env.py`. Copy the script somewhere else and run it.

**Comment by skyline75489** [comment]
Wait, you don't have any version of PyTorch installed? Guess `collect_env.py` is not ready if there is no PyTorch at all..

**Comment by zou3519** [comment]
We probably need more information to debug this, but it would be nice if collect_env.py worked without a PyTorch installation

**Comment by CnybTseng** [comment]
> Wait, you don't have any version of PyTorch installed? Guess `collect_env.py` is not ready if there is no PyTorch at all..

I have installed PyTorch-1.2.0. Same error happened when I copy collect_env.py to another directory.
# python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 429, in <module>
    main()
  File "collect_env.py", line 424, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 419, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 276, in get_env_info
    if torch.version.hip is None:  # cuda version
AttributeError: module 'torch.version' has no attribute 'hip'

**Comment by CnybTseng** [comment]
> We probably need more information to debug this, but it would be nice if collect_env.py worked without a PyTorch installation

I created a virtual environment without pytorch using: /opt/conda/bin/virtualenv ./tttest
Running collect_env.py will failed too:
# python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 429, in <module>
    main()
  File "collect_env.py", line 424, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 419, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 276, in get_env_info
    if torch.version.hip is None:  # cuda version
NameError: name 'torch' is not defined

**Comment by skyline75489** [comment]
OK, torch 1.2.0 is like kinda old. So I guess `collect_env.py` isn't really ready. But I could not understand `NameError: name 'torch' is not defined`. If `import torch` failed, then it shouldn't run the code who try to import `torch.version.hip`. What conda version are you using? My conda does not even have virtualenv.

**Comment by CnybTseng** [comment]
> OK, torch 1.2.0 is like kinda old. So I guess `collect_env.py` isn't really ready. But I could not understand `NameError: name 'torch' is not defined`. If `import torch` failed, then it shouldn't run the code who try to import `torch.version.hip`. What conda version are you using? My conda does not even have virtualenv.

I'm using conda 4.9.2
When I use collect_env.py from pytorch master branch:
# python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by skyline75489** [comment]
OK I think the problem is that GCC 5.4.0 is a rather old version of GCC.  AFAIK, the recommended version is somewhere around GCC 9.

**Comment by CnybTseng** [comment]
> OK I think the problem is that GCC 5.4.0 is a rather old version of GCC. AFAIK, the recommended version is somewhere around GCC 9.

Using gcc-10.2.0 will also build fail:
Compiling  functions.cu                        > /data/tseng/toolkit/pytorch/build/nccl/obj/collectives/device/functions.o
Archiving  objects                             > /data/tseng/toolkit/pytorch/build/nccl/obj/collectives/device/colldevice.a
Linking    libnccl.so.2.7.8                    > /data/tseng/toolkit/pytorch/build/nccl/lib/libnccl.so.2.7.8
Generating nccl.pc.in                          > /data/tseng/toolkit/pytorch/build/nccl/lib/pkgconfig/nccl.pc
Archiving  libnccl_static.a                    > /data/tseng/toolkit/pytorch/build/nccl/lib/libnccl_static.a
/data/tseng/toolkit/pytorch/third_party/nccl/nccl/src
[ 52%] No install step for 'nccl_external'
[ 52%] Completed 'nccl_external'
[ 52%] Built target nccl_external
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    cmake=cmake)
  File "/data/tseng/toolkit/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/data/tseng/toolkit/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/data/tseng/toolkit/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/opt/conda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 2.

**Comment by jeshxxx** [comment]
Is there any progress？I also met this problem.

**Comment by jeshxxx** [comment]
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.44
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[conda] Could not collect
Buiding pytorch from tag v1.7.0.

**Comment by malfet** [comment]
@jeshxxx , @CnybTseng : after updating to a new gcc, can you please share a full build log ?
And aren't cuda-10.2 incompatible with gcc-9?
cc: @ngimel

**Comment by ngimel** [comment]
gcc 9 is incompatible with cuda 10.x https://docs.nvidia.com/cuda/archive/10.2/cuda-installation-guide-linux/index.html

**Comment by melrobin** [comment]
Same error on Fedora 33 using gcc 10.2.1

**Comment by AsavarTzeth** [comment]
I'm running into the same error with gcc 10.2.0 with a cpu only build. So cuda or not, doesn't appear to make any difference.

**Comment by EricSteinberger** [comment]
Same error on Ubuntu using gcc 8

**Comment by melrobin** [comment]
It seems that PR ##52255 will resolve this, but it has not been fully approved.

**Comment by edrozenberg** [comment]
Same issue trying to build `1.7.1`

```
Linux 5.10.15 #1 SMP Wed Feb 10 14:06:55 CST 2021 x86_64 
Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz GenuineIntel GNU/Linux

magma-2.5.4

gcc-10.2.0
gcc-brig-10.2.0
gcc-g++-10.2.0
gcc-gdc-10.2.0
gcc-gfortran-10.2.0
gcc-gnat-10.2.0
gcc-go-10.2.0
gcc-objc-10.2.0
gccmakedep-1.0.3

automake-1.16.2
cmake-3.19.4
gccmakedep-1.0.3
imake-1.0.8
make-4.3
makedepend-1.0.6
pmake-1.111

nvidia-cuda-11.2.1
nvidia-cudnn-8.1.0.77_11.2
nvidia-driver-460.39
nvidia-kernel-460.39_5.10.15
nvidia-ml-py3-7.352.0
nvidia-nccl-2.8.4.1_11.2
nvidia-tensorrt-7.2.2.3_11.1
```

**Comment by cjolivier01** [comment]
happenned to me, seems issue was fbgemm was not at correct commit after rebase/merge due to git thinking there was an edit in there

**Comment by edrozenberg** [comment]
@cjolivier01 Thanks but no luck here. Downloaded latest `1.8.0` source. Did a git checkout of pytorch master branch and copied all of third_party from the git checkout to the `1.8.0` source. Same error:

```
error: no match for call to ‘(fbgemm::SparseAdaGradSignature<int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const int*, float, float, float, const double*, long int)>}) (long int&, int64_t, float*&, const float*&, float*&, const int32_t*, float&, const float&, const float&)’
  260 |           weight_decay_);
```

I assume the `1.8.0` source will build with some specific versions of the various third_party packages but I don't see it documented anywhere. Currently don't know how any user can manage to build any of the official release tags (1.7.x, 1.8.x etc). I'm only able to build the git checkout of master currently.

**Comment by cjolivier01** [comment]
you did a sync of the submodules? can you check the commit id of the fbgemm
submodule in pytorch against what is the top commit in your git log?

**Comment by cjolivier01** [comment]
there’s that PR listed up there that didn’t help?

**Comment by edrozenberg** [comment]
@cjolivier01 thanks I'm not able to make any sense of that PR and the many bot statuses and info listed there. If that PR is relevant, it's not helping anybody currently who is trying to build a release tarball such as 1.8.0.

If my earlier description unclear, here is the precise script I ran just now to get a `1.8.0` build failure. I ran exactly this script, and there was no previous code at all in that directory - so no issues with old code. I'm having zero clue why building release source such as `1.8.0` is having this `fbgemm` issue. No such issue building git checkouts.
```
#!/usr/bin/bash

# Define release source version
rver='1.8.0'

# Define source and package directories
sdir='/usr/local/src/pytorch-test/src'
pdir='/usr/local/src/pytorch-test/pkg'

mkdir -p $sdir $pdir

# Download git source & release source, rsync third_party dir to the release
cd $sdir
wget https://github.com/pytorch/pytorch/archive/v${rver}.tar.gz -O - | tar -xz
git clone --recursive https://github.com/pytorch/pytorch pytorch-git
rsync -av pytorch-git/third_party/ pytorch-${rver}/third_party/

# Go to the release source dir
cd pytorch-${rver}

# Define build params
export BLAS='OpenBLAS'
export BUILD_SPLIT_CUDA=1
export TORCH_CUDA_ARCH_LIST='3.5;6.1;7.0;7.5;8.0;8.6'
export USE_SYSTEM_NCCL=1
export NCCL_ROOT_DIR='/opt/nvidia/nccl'
export NCCL_INCLUDE_DIR='/opt/nvidia/nccl/include'

# Build the source
python3 setup.py install --root=${pdir}
```

Build output (partial):
```
In file included from ../caffe2/sgd/adagrad_fused.h:3,
                 from ../caffe2/sgd/adagrad_fused.cc:1:
../caffe2/sgd/adagrad_op.h: In member function ‘bool caffe2::SparseAdagradOp::DoRunWithType()’:
../caffe2/sgd/adagrad_op.h:260:24: error: no match for call to ‘(fbgemm::SparseAdaGradSignature<int>::Type {aka std::function<int(int, long unsigned int, float*, const float*, float*, const int*, float, float, float, const double*, long int)>}) (long int&, int64_t, float*&, const float*&, float*&, const int32_t*, float&, const float&, const float&)’
  260 |           weight_decay_);
      |                        ^
```

**Comment by melrobin** [comment]
I was able to build from the latest sources.  The pull request did not help, but 'git update submodules' did allow a build.

**Comment by edrozenberg** [comment]
@melrobin "latest sources" you mean `git clone` or you mean `1.8.0`. Yes `git clone` works for me, `1.8.0` does not and that's my issue.

**Comment by melrobin** [comment]
Yes that's right....when I clone the repository it works.

**Comment by ShuttleDDD** [comment]
same error when building 1.8.1, so annoying.
$ python3 collect.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: yes
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: P106-090
Nvidia driver version: 460.67
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[conda] Could not collect

**Comment by elementgreen** [comment]
As hinted at by @melrobin doing a submodule update fixed this issue for me, namely:
`git submodule update --recursive`

I think this might be needed after doing a checkout of a branch or tag, such as v1.8.1 in my case.

**Comment by CnybTseng** [comment]
> As hinted at by @melrobin doing a submodule update fixed this issue for me, namely:
> `git submodule update --recursive`
> 
> I think this might be needed after doing a checkout of a branch or tag, such as v1.8.1 in my case.

Your solution works for me too. My building step as follows:
$ git clone --recursive https://github.com/pytorch/pytorch
$ cd pytorch
if you are updating an existing checkout
$ git submodule sync
$ git submodule update --init --recursive
$ git checkout v1.8.1
$ git submodule update --recursive
$ export PATH=$PATH:/opt/conda/bin
$ export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
$ python setup.py install
