### ISSUE TITLE
ShuffleNet_v2: batch input issue after convert pytorch model to onnx model

### ISSUE THREAD

**Issue by Suntester** [pytorch/pytorch#48093]
## 🐛 Bug

After convert ShuffleNet_v2 pytorch model to  onnx model, show below error when using the model inferencing by a batch(e.g. 6 images), it looks that dynamic axes property led to this error.
can anyone tell me what wrong is?
Thanks

## To Reproduce

```
import torch
from torch.autograd import Variable
import torchvision
from torchvision import datasets, models, transforms
import torch.nn as nn
import onnxruntime as rt
from PIL import Image
import numpy as np
import onnx

shuffle_net = models.shufflenet_v2_x0_5(pretrained=True)
# Export the pytorch model to ONNX
dummy_input = torch.randn(1, 3, 224, 224, requires_grad=True) 
torch.onnx.export(shuffle_net, dummy_input, "shuffleNet.onnx",  opset_version=11, do_constant_folding=True, export_params=True, input_names=['input_images'], output_names=['output']
, dynamic_axes={"input_images": [0], "output": [0]})
# load onnx model
sess = rt.InferenceSession("shuffleNet.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
print('input_name: ' + input_name)
print('label_name: ' + label_name)

img = Image.open('./test.jpg').resize((224, 224))
image_raw_data = np.asarray(img, dtype=np.float32)
image_raw_data = np.transpose(image_raw_data, (2, 0, 1))[np.newaxis, :, :, :]
# random initialize array
images_raw_data = np.ones([1, 3, 224, 224], dtype=np.float32)
# [6, 3, 224, 224]
for i in range(5):
    images_raw_data = np.concatenate((images_raw_data, image_raw_data), axis=0)

pred_onx = sess.run([label_name], {input_name: images_raw_data})
print(pred_onx)
```

I get this error
```
Downloading: "https://download.pytorch.org/models/shufflenetv2_x0.5-f707e7126e.pth" to /root/.cache/torch/hub/checkpoints/shufflenetv2_x0.5-f707e7126e.pth
100.0%
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:958: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input input_images
  'Automatically generated names will be applied to each dynamic axes of input {}'.format(key))
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:958: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input output
  'Automatically generated names will be applied to each dynamic axes of input {}'.format(key))
input_name: input_images
label_name: output
2020-11-17 13:04:51.461699971 [E:onnxruntime:, sequential_executor.cc:309 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_19' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{6,48,28,28}, requested shape:{1,2,24,28,28}

Traceback (most recent call last):
  File "test_export.py", line 32, in <module>
    pred_onx = sess.run([label_name], {input_name: images_raw_data})
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_19' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{6,48,28,28}, requested shape:{1,2,24,28,28}

```

## Environment

 - PyTorch Version :  1.6.0  
 - OS : ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.2
 - onnx: 1.6.0
 - onnxruntime: 1.4.0

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by Suntester** [comment]
can anyone help solve this problem? ：）

**Comment by fatcat-z** [comment]
> can anyone help solve this problem? ：）

This should be an issue of shfflenet_v2 model. The PR of pytorch/vision is going to fix this.

**Comment by spandantiwari** [comment]
@Suntester - this issue was fixed in torchvision repo. Please try it out and confirm.

**Comment by Suntester** [comment]
@fatcat-z @spandantiwari 
I test it and it works fine. Thank you.

**Comment by spandantiwari** [comment]
@fatcat-z  - can you please link the tochvision PR here.

**Comment by spandantiwari** [comment]
PR linked above.
