### ISSUE TITLE
wheels for python3.5 fail to install: .dist-info directory not found

### ISSUE THREAD

**Issue by lopuhin** [pytorch/pytorch#482]
```
$ pip --version
pip 9.0.1 from /home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages (python 3.5)

$ pip install https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp35-cp35m-linux_x86_64.whl 
Collecting torch-cuda80==0.1.6.post17 from https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp35-cp35m-linux_x86_64.whl
  Using cached https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp35-cp35m-linux_x86_64.whl
Requirement already satisfied: pyyaml in ./venv/lib/python3.5/site-packages (from torch-cuda80==0.1.6.post17)
Installing collected packages: torch-cuda80
Exception:
Traceback (most recent call last):
  File "/home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/kostia/ml/pytorch-tutorials/venv/lib/python3.5/site-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: torch-cuda80==0.1.6.post17 .dist-info directory not found
```

**Comment by soumith** [comment]
thanks for the report.
I believe that error message appears but pytorch actually does get installed (that's what I've seen).

I'm working through the wheel issues

**Comment by lopuhin** [comment]
Thanks for a swift reply! Indeed, ``import torch`` works, on to the tutorial :)

**Comment by soumith** [comment]
this is fixed now

**Comment by pushytoxin** [comment]
This was annoying me for a while on a completely unrelated project, but I figured out why it appears.

he reason for the error message is that the actual file name of the .whl is not the same as the .dist-info directory that's in the zip/whl file.

To fix, you have to rename the .whl file!
