### ISSUE TITLE
[FR] bool tensor should support basic arithmetics

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#48353]
## 🚀 Feature

Numpy supports this (e.g., `100-x`) and I don't know why that we can't type promote bool torch tensors.

**Comment by mruberry** [comment]
The error message suggests this choice was made to avoid confusion with inverting the boolean tensor:

```
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
```

**Comment by rgommers** [comment]
`x - 100` also doesn't work, so I think that error message is accidental (or just weird) here. The `*`, `+` and `/` operators do work with bool tensors, so `-` should as well for consistency. 

It's not quite clear to me from a bit of testing whether upcasting bools is still a work in progress or not. The `add`, `sum` functions do upcast for example, while `sin`, `cos`, `remainder` error out. Should they all be made to work like numpy? There's something to say for "no" of course, semantically doing numerical operations on booleans doesn't make all that much sense.

**Comment by mruberry** [comment]
> `x - 100` also doesn't work, so I think that error message is accidental (or just weird) here. The `*`, `+` and `/` operators do work with bool tensors, so `-` should as well for consistency.

This would probably be fine.


> It's not quite clear to me from a bit of testing whether upcasting bools is still a work in progress or not. The `add`, `sum` functions do upcast for example, while `sin`, `cos`, `remainder` error out. Should they all be made to work like numpy? 

I would lean towards 'yes' we *should* be consistent and support type promotion for bools. But, following your next point, @rgommers, it doesn't seem very high priority.

**Comment by gchanan** [comment]
The error message is to avoid subtraction or negation on boolean data types, so type promoting out of bool should be fine.

Also, the error message is bad in this case because it leaks an implementation detail and gives a worse error message:

```
>>> -torch.tensor(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Negation, the `-` operator, on a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
>>> torch.tensor(True) - torch.tensor(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Subtraction, the `-` operator, with two bool tensors is not supported. Use the `^` or `logical_xor()` operator instead
```
