### ISSUE TITLE
When I install Pytorch successfully, but when I import torch, it get wrong. Help Me Please!

### ISSUE THREAD

**Issue by NHI-KH** [pytorch/pytorch#48454]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/torch/__init__.py", line 526, in <module>
    from .functional import *
  File "/usr/local/lib/python3.7/dist-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 12, in <module>
    from .._jit_internal import boolean_dispatch, List, Optional, _overload, Tuple
  File "/usr/local/lib/python3.7/dist-packages/torch/_jit_internal.py", line 29, in <module>
    from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by ngimel** [comment]
Please use forums for questions, discuss.pytorch.org. The error message indicate that you don't have `typing_extensions` module, please install it by `pip install typing_extensions`.
