### ISSUE TITLE
Ambiguous RuntimeError raised when device of input PackedSequence does not match with nn.LSTM's device

### ISSUE THREAD

**Issue by imkzh** [pytorch/pytorch#48511]
## 🚀 Enhancement Request
I got 
```
RuntimeError: Expected !pre_compute_input to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```
while in forward function of LSTM(on gpu), called with PackedSequence(on cpu).
I called the module with wrong input by mistake and waste whole night to figure it out because of this misleading and ambiguous error message(i am thinking if this is a implementation bug or environment related issue at the first time).

The following code reproduces the exception:
```
import torch
query = [
  torch.randn(3, 5),  
  torch.randn(6, 5),
  torch.randn(4, 5),
  torch.randn(7, 5),
]

lstm = torch.nn.LSTM(input_size=5, hidden_size=10, num_layers=3).cuda()
query = torch.nn.utils.rnn.pack_sequence(query, enforce_sorted=False)  # <-- note: query is on cpu and lstm is on cuda
out = lstm(query)  # <-- should raise exceptions that make sense.
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 738, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 579, in forward
    result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,
RuntimeError: Expected !pre_compute_input to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

## Pitch

Raise "device mismatch" exceptions like other functions/modules would do.

## Additional context
PyTorch Version: 1.6.0

**Comment by mruberry** [comment]
Thanks for filing this issue, @imkzh. This is a great suggestion and we would accept a PR improving this error message. Sorry you spent so long diagnosing the issue.
