### ISSUE TITLE
PyTorch fails to run on Apple Silicon

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#48524]
## 🐛 Bug

PyTorch fails to run on Apple M1, even under Rosetta.

There are other bugs tracking GPU support, this is tracking running on CPU in the first place.

## To Reproduce

Repro 1: pip install torch -f torch_nightly

```
~: pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html 
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/site-packages (from torch) (5.3.1)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-wheel-q7qa6l16
       cwd: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-record-telojsxn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/torch
         cwd: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py", line 99, in run
        self.run_command('build_deps')
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-94hztydp/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-record-telojsxn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/torch Check the logs for full command output.
```

Repro 2: Build form source:

```
~/Projects: git clone --recursive git@github.com:pytorch/pytorch.git
Cloning into 'pytorch'...
[...]
Updating files: 100% (7916/7916), done.
[...]
~/Projects: cd pytorch 
~/Projects/pytorch: pip install .
Processing ~/Projects/pytorch
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.8/site-packages (from torch==1.8.0a0) (3.7.4.3)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... |
done
  Created wheel for torch: filename=torch-1.8.0a0-cp38-cp38-macosx_11_0_x86_64.whl size=70560736 sha256=8795bde6fff5887d78c4892322baa065177cc4e426b60c24d7ccd8ecf3ddd359
  Stored in directory: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-ephem-wheel-cache-yghtbkkx/wheels/9f/19/d8/d152ef0068f3405760be791c37a4cd6f1bf9e2373c801eb517
Successfully built torch
Installing collected packages: torch
Successfully installed torch-1.8.0a0
~/Projects/pytorch: 
~/Projects/pytorch: python
Python 3.8.6 (default, Nov 24 2020, 20:54:58) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Projects/pytorch/torch/__init__.py", line 24, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'torch.version'
>>> 
``` 

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 11.0.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.27)
CMake version: version 3.19.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.4
[conda] Could not collect

#48145

cc @ezyang @seemethere @malfet @walterddr

**Comment by ezyang** [comment]
Repro 1 fails because we don't have ARM binaries on pip, so it picks up an ancient version of torch which advertises itself as source wheel.

Repro 2... it doesn't look like a build of PyTorch actually happened. What if you `python setup.py install` instead of using pip?

**Comment by lutzroeder** [comment]
@ezyang both started working today after updating to Python 3.9.0 and pip 20.3 (probably using Rosetta) which unblocks the scenario.

**Comment by malfet** [comment]
PyTorch should be buildable from source on M1, see https://github.com/pytorch/pytorch/issues/48145 Will try to start uploading M1 wheels intermittently.
And even if one does not update pip to  20.3, PyTorch stable binaries should be downloadable from https://download.pytorch.org/whl/torch_stable.html , see https://github.com/pytorch/pytorch/issues/47978

**Comment by roberthajdu92** [comment]
It works for me natively now (blazing fast anyway, thanks guys!!! :)). Now same error happens above if I just want to build torch in Docker with python3.7-8-9-slim on M1.

**Comment by roberthajdu92** [comment]
> It works for me natively now (blazing fast anyway, thanks guys!!! :)). Now same error happens above if I just want to build torch in Docker with python3.7-8-9-slim on M1.

It's confirmed works now with PyTorch nightly cpu (only) on M1 Macs at this date. Thanks guys!

**Comment by elbamos** [comment]
> PyTorch should be buildable from source on M1, see #48145 Will try to start uploading M1 wheels intermittently.
> And even if one does not update pip to 20.3, PyTorch stable binaries should be downloadable from https://download.pytorch.org/whl/torch_stable.html , see #47978

@malfet Did you ever start uploading those M1 wheels, and if so, to where?  Thank you for all you have done on this!
