### ISSUE TITLE
test_fs_pool fails

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#48579]
## 🐛 Bug

When running the test on x86 I get the following failure:

```
FAIL: test_fs_pool (__main__.TestMultiprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_multiprocessing.py", line 350, in test_fs_pool
    self._test_pool(repeat=TEST_REPEATS)
  File "test_multiprocessing.py", line 322, in _test_pool
    do_test()
  File "test_multiprocessing.py", line 205, in __exit__
    self.test_case.assertFalse(self.has_shm_files())
AssertionError: True is not false
```

## To Reproduce

1.`PYTORCH_BUILD_VERSION=1.7.0 PYTORCH_BUILD_NUMBER=1 MAX_JOBS=12 BLAS=Eigen USE_FFMPEG=1 BUILD_CUSTOM_PROTOBUF=0 USE_IBVERBS=1 USE_CUDA=1 TORCH_CUDA_ARCH_LIST="3.7;6.1;7.0" USE_METAL=0   /sw/installed/Python/3.7.4-GCCcore-8.3.0/bin/python setup.py build` / install
1. `cd test && python run_test.py --verbose`

## Environment

```
PyTorch version: 1.7.0
CUDA used to build PyTorch: 10.1.243

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (GCC) 8.3.0
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 450.36.06
cuDNN version: 7.6.4.38

Versions of relevant libraries:
[pip3] numpy==1.17.3
```

**Comment by ejguan** [comment]
Can not reproduce on MacOS or Linux x86.

**Comment by Flamefire** [comment]
This seems to be very flaky, it only happens sometimes. Example failure log excerpt: https://gist.github.com/Flamefire/45b3c6fcad2512a81c47e9657ee27ece

**Comment by Flamefire** [comment]
I just ran that 8 times and it failed 1 time and succeeded 7 times, so this is rare but annoying
