### ISSUE TITLE
Error when exiting tutorial script

### ISSUE THREAD

**Issue by matouf** [pytorch/pytorch#4871]
- OS: 
Ubuntu 16.04
- PyTorch version: 
master, at commit aaa0288aed4d2a35be835e2b7cf315332b966797
- How you installed PyTorch (conda, pip, source): 
Using git and built using the dockerfile for cuda 9 and cudnn v7
- Python version: 3.6.4
- CUDA/cuDNN version:
cuda 9.0 and cudnn 7
- GPU models and configuration:
Geforce 1080
- GCC version (if compiling from source):
gcc 5.4.0

- Script to reproduce the bug: 
the tutorial script for cifar10 classification: http://pytorch.org/tutorials/_downloads/cifar10_tutorial.py

At the end of the script execution, I have the following error message:
`Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/popen_fork.py", line 35, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 172, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 710) is killed by signal: Terminated.
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f296ab343c8>>
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in __del__
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 310, in _shutdown_workers
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/queues.py", line 337, in get
ImportError: sys.meta_path is None, Python is likely shutting down
`

**Comment by SsnL** [comment]
Should be fixed in #4643

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/4643
