### ISSUE TITLE
RuntimeError: Python type cannot be used as a value:

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#48795]
## 🐛 Bug

```
Traceback (most recent call last):
  File "~/Desktop/repro.py", line 5, in <module>
    torch.jit.script(model).save('densenet161.pt')
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 897, in script
    return torch.jit._recursive.create_script_module(
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 370, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 426, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 406, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 426, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 406, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 426, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 406, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 430, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/lib/python3.9/site-packages/torch/jit/_recursive.py", line 322, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Python type cannot be used as a value:
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/densenet.py", line 33
    def forward(self, x):
        new_features = super(_DenseLayer, self).forward(x)
                             ~~~~~~~~~~~ <--- HERE
        if self.drop_rate > 0:
            new_features = F.dropout(new_features, p=self.drop_rate, training=self.training)
```

## To Reproduce

```
pip install --upgrade --pre torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

```
import torch
import torchvision
model = torchvision.models.densenet161(pretrained=False)
model.eval()
torch.jit.script(model).save('densenet161.pt')
```

## Environment

Collecting environment information...
PyTorch version: 1.8.0.dev20201203
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.0.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.27)
CMake version: version 3.19.1

Python version: 3.9 (64-bit runtime)
Is CUDA available: False

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.0.dev20201203
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

@malfet @gmagogsfm #48692

cc @gmagogsfm

**Comment by lutzroeder** [comment]
```
import torch
import torchvision
model = torchvision.models.inception_v3(pretrained=False)
model.eval()
torch.jit.script(model).save('inception_v3.pt')
```

```
RuntimeError: 

aux is not defined in the false branch:
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/inception.py", line 112
        x = self.Mixed_6e(x)
        # N x 768 x 17 x 17
        if self.training and self.aux_logits:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            aux = self.AuxLogits(x)
            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        # N x 768 x 17 x 17
        x = self.Mixed_7a(x)
and was used here:
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/inception.py", line 131
        # N x 1000 (num_classes)
        if self.training and self.aux_logits:
            return x, aux
                      ~~~ <--- HERE
        return x
```

**Comment by malfet** [comment]
@lutzroeder is this specific to Python-3.9 or can you reproduce it with 3.8?

**Comment by lutzroeder** [comment]
`torchvision-0.2.2.post3` is what gets installed on M1 Big Sur when running `pip install --upgrade --pre torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`.

```
~: pip install --upgrade --pre torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torchvision
  Downloading torchvision-0.2.2.post3-py2.py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 2.5 MB/s 
Requirement already satisfied: six in /usr/local/Cellar/protobuf/3.14.0/libexec/lib/python3.9/site-packages (from torchvision) (1.15.0)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.9/site-packages (from torchvision) (8.0.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from torchvision) (1.19.4)
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.8.0.dev20201203-cp39-none-macosx_10_9_x86_64.whl (113.6 MB)
     |████████████████████████████████| 113.6 MB 208 kB/s 
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/site-packages (from torch->torchvision) (3.7.4.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from torchvision) (1.19.4)
Installing collected packages: torch, torchvision
Successfully installed torch-1.8.0.dev20201203 torchvision-0.2.2.post3
```

**Comment by rishic3** [comment]
Any resolution to this? I'm experiencing the same issue.
