### ISSUE TITLE
cudnn cannot be pickled by cloudpickle

### ISSUE THREAD

**Issue by briankosw** [pytorch/pytorch#48832]
## 🐛 Bug

I was spawning parallel processes using Joblib for training distributed PyTorch code, and I get the error that the cudnn object cannot be pickled. After pruning as much extraneous code as possible, I've identified that cloudpickle is unable to pickle cudnn, as demonstrated in the minimal repro below:

## To Reproduce

```python
# main.py
import torch.backends.cudnn
import cloudpickle


def foo():
    print(torch.backends.cudnn)


cloudpickle.dumps(foo)
```

```shell
>>> python main.py

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    cloudpickle.dumps(foo)
  File "/Users/BrianKo/anaconda3/envs/hydra38/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/BrianKo/anaconda3/envs/hydra38/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'CudnnModule' object
```

## Expected behavior

If you use Python's native pickle instead, the above repro works.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): macOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

**Comment by mruberry** [comment]
This seems like a cloudpickle issue since this works in pickle, although I'm not sure PyTorch intended to support this in the first place and it's probably working as an accident.

**Comment by briankosw** [comment]
Hi @mruberry, could you just briefly explain why PyTorch didn't intend to support this? It definitely does seem like a cloudpickle issue, so I've reported the issue there as well.

**Comment by mruberry** [comment]
I just doubt that anyone thought about picking `torch.backends.cudnn`. Maybe someone did.

**Comment by omry** [comment]
Note that the code does not attempt to serialize torch.backends.cudnn. This is probably a side effect of something global it's changing or otherwise a bug in cloudpickle.

basic pickle is doing a very poor job at serializing functions properly and cloudpickle is handling things much better in general.
I am not surprised pickle "works", but I think it's just an illusion :).

**Comment by omry** [comment]
The good folks at cloudpickle did some digging and have suggestions for possible fixes in PyTorch [here](https://github.com/cloudpipe/cloudpickle/issues/405).

It would be great if the solution they are offering there would be evaluated.

**Comment by mruberry** [comment]
That's very generous of them to spend their time debugging this. The suggested fix looks straightforward to apply. I've suggested we validate whether that will address the end-to-end scenario here.

**Comment by nzw0301** [comment]
any update?
