### ISSUE TITLE
Inconsistent size error when using pin_memory() after torch.unbind()

### ISSUE THREAD

**Issue by sytrus-in-github** [pytorch/pytorch#4894]
- OS: Ubuntu 14.04
- PyTorch version: 0.3.0.post4
- How you installed PyTorch: conda
- Python version: 3.6.3
- CUDA version: 8

Script to reproduce the error:
```python
import torch
a = torch.zeros(3, 4)
a1, a2, a3 = torch.unbind(a, 0)
a1 = a1.pin_memory()
```
```
Traceback (most recent call last):

  File "<ipython-input-67-b93d604f6d7e>", line 1, in <module>
    a1 = a1.pin_memory()

  File "<path-to>/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 82, in pin_memory
    return type(self)().set_(storage.pin_memory()).view_as(self)

  File "<path-to>/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 198, in view_as
    return self.view(tensor.size())

RuntimeError: invalid argument 2: size '[4]' is invalid for input with 12 elements at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/TH/THStorage.c:41
```

**Comment by zou3519** [comment]
Thank you for the bug report!

This doesn't error out on `Variable`s:
```
import torch
from torch.autograd import Variable
a = Variable(torch.zeros(3, 4))
a1, a2, a3 = torch.unbind(a, 0)
a1 = a1.pin_memory()
```
The RuntimeError with tensors will be fixed when Tensor and Variable are merged.

**Comment by sytrus-in-github** [comment]
As for pytorch 0.4 (nightly build 2018.04.20, installed via conda) this problem does not exist anymore. 
```python
>>> import torch
>>> a = torch.zeros(3, 4)
>>> a1, a2, a3 = torch.unbind(a, 0)
>>> a1 = a1.pin_memory()
>>> torch.__version__
'2018.04.20'
```
Closing the issue.

**Comment by zou3519** [comment]
@sytrus-in-github good to hear!
