### ISSUE TITLE
RuntimeError: Exporting the operator uniform to ONNX opset version 12 is not supported.

### ISSUE THREAD

**Issue by iuhiyuh** [pytorch/pytorch#49001]
## 🐛 Bug

It may be a dynamic axes ops occur this bug.
Is dynamic axis operation not supported yet？

## To Reproduce

**1.** 
```python
def __init__(self, input_channels, n_segment=8, n_div=8, mode='shift'):
        super(ShiftModule, self).__init__()
        input_channels = input_channels
        self.n_segment = n_segment
        fold_div = n_div
        fold = input_channels // fold_div
        self.conv_shift = nn.Conv1d(
            input_channels, input_channels,
            kernel_size=3, padding=1, groups=input_channels,
            bias=False)
        
def forward(self, x):
        nt, c, h, w = x.size()
        n_batch = nt // self.n_segment
        x = x.view(n_batch, self.n_segment, c, h, w)
        x = x.permute([0, 3, 4, 2, 1])  # (n_batch, h, w, c, n_segment)
        x = x.contiguous().view(n_batch * h * w, c, self.n_segment)
        
        x = x.view(n_batch, h, w, c, self.n_segment)
        x = x.permute([0, 4, 3, 1, 2])  # (n_batch, n_segment, c, h, w)
        x = x.contiguous().view(nt, c, h, w)
        return x
```
it's normal

**2.**
```python
def forward(self, x):
        nt, c, h, w = x.size()
        n_batch = nt // self.n_segment
        x = x.view(n_batch, self.n_segment, c, h, w)
        x = x.permute([0, 3, 4, 2, 1]) 
        x = x.contiguous().view(n_batch * h * w, c, self.n_segment)
        x = self.conv_shift(x)  # (n_batch*h*w, c, n_segment)
        x = x.view(n_batch, h, w, c, self.n_segment)
        x = x.permute([0, 4, 3, 1, 2])  # (n_batch, n_segment, c, h, w)
        x = x.contiguous().view(nt, c, h, w)
        return x
```
When `x = self.conv_shift(x)` is added, the runtimeerror will be thrown

## Log
```
Traceback (most recent call last):
  File "/home/huyihui/workspace/tsm/main.py", line 441, in <module>
    main()
  File "/home/huyihui/workspace/tsmi/main.py", line 213, in main
    train(train_loader, model, criterion, optimizer, epoch, log_training, tf_writer)
  File "/home/huyihui/workspace/tsm/main.py", line 274, in train
    torch.onnx.export(model, inputs, f, opset_version=12)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 930, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator uniform to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

Process finished with exit code 1
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by marvosyntactical** [comment]
Did you manage to resolve your issue?

**Comment by BowenBao** [comment]
Tried running locally and it seems support was added and model converted successfully. Closing.
