### ISSUE TITLE
Enable torch.where to support float16/bfloat16 type inputs

### ISSUE THREAD

**Issue by Kiyosora** [pytorch/pytorch#49075]
## 🐛 Bug

It seems that `torch.where` does not accept the input of `float16`/`bfloat16` types Tensor. 
I'm quite not sure does this is the way it should be. Maybe we can make a bit of improvement that to make `torch.where` support `float16`/`bfloat16` inputs.

## To Reproduce
```
>>> t=torch.arange(0,6).resize(2,3).to(dtype=torch.bfloat16)
>>> torch.where(t>2,torch.ones_like(t),t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "where_cpu" not implemented for 'BFloat16'

>>> t=torch.arange(0,6).resize(2,3).to(dtype=torch.float16)
>>> torch.where(t>2,torch.ones_like(t),t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "where_cpu" not implemented for 'Half'
```

## Expected behavior

```
>>> t=torch.arange(0,6).resize(2,3).to(dtype=torch.bfloat16)
>>> torch.where(t>2,torch.ones_like(t),t)
tensor([[0., 1., 2.],
        [1., 1., 1.]], dtype=torch.bfloat16)

>>> t=torch.arange(0,6).resize(2,3).to(dtype=torch.float16)
>>> torch.where(t>2,torch.ones_like(t),t)
tensor([[0., 1., 2.],
        [1., 1., 1.]], dtype=torch.float16)
```

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+d3b3387
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A
OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0
Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 450.51.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.8.0a0
[conda] blas                      1.0                         mkl    defaults
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217    defaults
[conda] mkl-include               2020.1                      217    defaults
[conda] mkl-service               2.3.0            py37he904b0f_0    defaults
[conda] mkl_fft                   1.1.0            py37h23d657b_0    defaults
[conda] mkl_random                1.1.1            py37h0573a6f_0    defaults
[conda] numpy                     1.18.5           py37ha1c710e_0    defaults
[conda] numpy-base                1.18.5           py37hde5b4d6_0    defaults
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.8.0a0                   dev_0    <develop>
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
Thank you for making this suggestion, @Kiyosora. We we would accept a PR adding this functionality.
