### ISSUE TITLE
test_stress_heavy_rpc_torchscript (__main__.ProcessGroupRpcTestWithSpawn) is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#49094]
This seems to be rare. So not disabling it yet to get more error logs.

https://app.circleci.com/pipelines/github/pytorch/pytorch/247779/workflows/3ae77ff8-3dd4-4cb7-ab26-220113a927ae/jobs/9447729/steps

```
Dec 09 15:14:41 ======================================================================
Dec 09 15:14:41 ERROR [61.029s]: test_stress_heavy_rpc_torchscript (__main__.ProcessGroupRpcTestWithSpawn)
Dec 09 15:14:41 ----------------------------------------------------------------------
Dec 09 15:14:41 Traceback (most recent call last):
Dec 09 15:14:41   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 280, in wrapper
Dec 09 15:14:41     self._join_processes(fn)
Dec 09 15:14:41   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 397, in _join_processes
Dec 09 15:14:41     self._check_return_codes(elapsed_time)
Dec 09 15:14:41   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _check_return_codes
Dec 09 15:14:41     raise RuntimeError(error)
Dec 09 15:14:41 RuntimeError: Processes 1 exited with error code 10
```

```
Dec 09 15:13:20   test_stress_heavy_rpc_torchscript (__main__.ProcessGroupRpcTestWithSpawn) ... RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Dec 09 15:13:20 RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Dec 09 15:13:20 RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Dec 09 15:13:20 RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Dec 09 15:14:20 ERROR:root:Caught exception: 
Dec 09 15:14:20 Traceback (most recent call last):
Dec 09 15:14:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 283, in wrapper
Dec 09 15:14:20     fn()
Dec 09 15:14:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Dec 09 15:14:20     return_value = old_test_method(self, *arg, **kwargs)
Dec 09 15:14:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 2024, in test_stress_heavy_rpc_torchscript
Dec 09 15:14:20     self._stress_test_rpc(heavy_rpc_torchscript, repeat=20, args=(torch.ones(100, 100),))
Dec 09 15:14:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 2005, in _stress_test_rpc
Dec 09 15:14:20     for val in torch.futures.wait_all(futs):
Dec 09 15:14:20   File "/opt/conda/lib/python3.6/site-packages/torch/futures/__init__.py", line 196, in wait_all
Dec 09 15:14:20     return [fut.wait() for fut in torch._C._collect_all(cast(List[torch._C.Future], futures)).wait()]
Dec 09 15:14:20 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Dec 09 15:14:20 exiting process with exit code: 10
Dec 09 15:14:20 Process 1 terminated with exit code 10, terminating remaining processes.
Dec 09 15:14:20 ERROR (61.029s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @gmagogsfm

**Comment by zhaojuanmao** [comment]
same as #50702
