### ISSUE TITLE
Unknown failure for test_reference_numerics_sinc_cuda_complex64 

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#49133]
## 🐛 Bug
Operator `torch.sinc` fails on certain values for complex64 but succeeds for complex128
```
======================================================================
FAIL: test_reference_numerics_sinc_cpu_complex64 (__main__.TestUnaryUfuncsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jeffrey/local/pytorch/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
    result = test_fn(self, *args)
  File "/home/jeffrey/local/pytorch/torch/testing/_internal/common_device_type.py", line 247, in test_wrapper
    return test(*args, **kwargs)
  File "/home/jeffrey/local/pytorch/torch/testing/_internal/common_utils.py", line 571, in wrapper
    fn(*args, **kwargs)
  File "test/test_unary_ufuncs.py", line 299, in test_reference_numerics
    self.assertEqualHelper(actual, expected, msg, dtype=dtype, exact_dtype=exact_dtype)
  File "test/test_unary_ufuncs.py", line 236, in assertEqualHelper
    self.assertEqual(actual.item(), expected, **kwargs)
  File "/home/jeffrey/local/pytorch/torch/testing/_internal/common_utils.py", line 1180, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Scalars failed to compare as equal! Comparing the imaginary part -2466718720.0 and -2466714431.7981887 gives a difference of 4288.201811313629, but the allowed difference with rtol=1.3e-06 and atol=0.01 is only 3206.7387613376454!
```

## To Reproduce

1. run `python test/test_unary_ufuncs.py -k sinc`

## Expected behavior

Sinc output should return about the same value as numpy

## Environment

PyTorch version: 1.8.0a0+3157bcf
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3070
Nvidia driver version: 455.38
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-sphinx-theme==0.0.19
[pip3] torch==1.8.0a0
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.19                   pypi_0    pypi
[conda] torch                     1.8.0a0                   dev_0    <develop>

**Comment by soulitzer** [comment]
fyi sinc isn't landed yet, just creating this issue in advance
