### ISSUE TITLE
Missing ‘get_trace_graph’ function in Pytorch1.7

### ISSUE THREAD

**Issue by Wei-Zhuo** [pytorch/pytorch#49153]
‘get_trace_graph’ function could be found in old version Pytorch, e.g. 1.1.0, but i could not find it in 1.7.0 version. 
I replace `torch.jit.get_trace_graph(model, arg)` by
```
torch.jit.trace(model, args).graph
```
but it returns
```
Traceback (most recent call last):
  File "tools/train.py", line 298, in <module>
    main()
  File "tools/train.py", line 123, in main
    writer_dict['writer'].add_graph(sor_model, (dump_input, ))
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 223, in graph
    traced = torch.jit.trace(model, args)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 928, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ivc/anaconda3/envs/PT/lib/python3.6/site-packages/torch/jit/_trace.py", line 988, in __init__
    assert isinstance(orig, torch.nn.Module)
AssertionError
```
 I do really appreciate any advice.

**Comment by t-vi** [comment]
This function is considered private/undocumented API and has been renamed `_get_trace_graph`. It is not advised to use this function.
What you likely want is use the ONNX module, not the JIT one, but it is hard to tell without the steps to reproduce the error.

P.S.: The best place to ask questions like this is the [forum](https://discuss.pytorch.org/).

**Comment by Wei-Zhuo** [comment]
> This function is considered private/undocumented API and has been renamed `_get_trace_graph`. It is not advised to use this function.
> What you likely want is use the ONNX module, not the JIT one, but it is hard to tell without the steps to reproduce the error.
> 
> P.S.: The best place to ask questions like this is the [forum](https://discuss.pytorch.org/).

Thanks. I'll keep that in mind.
