### ISSUE TITLE
torch.topk(k=0) does not work on float tensors

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#49205]
## 🐛 Bug

`torch.topk(k=0)` does not work on float tensors, as originally reported in https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-710/105326/5

cc: @ptrblck 

## To Reproduce

```python
import torch

# This case works well
x = torch.tensor([1,2,3,4,5,2,1,-1,-4,12,4]).cuda()
torch.topk(x,k=0,largest=False)
torch.cuda.synchronize()
print("case 1 works!")

# This case fails
x = torch.tensor([1,2,3,4,5,2,1,-1,-4,12,4], dtype=torch.float).cuda()
torch.topk(x,k=0,largest=False)
torch.cuda.synchronize()
print("case 2 works!")
```

Output
```
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [0,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [1,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [2,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [3,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [4,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [5,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [6,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [7,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [8,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [9,0,0] Assertion `writeIndex < outputSliceSize` failed.
/home/gaoxiang/pytorch-master/aten/src/THC/THCTensorTopK.cuh:107: gatherTopK: block: [0,0,0], thread: [10,0,0] Assertion `writeIndex < outputSliceSize` failed.
Traceback (most recent call last):
  File "/home/gaoxiang/misc/topk.py", line 12, in <module>
    torch.cuda.synchronize()
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 380, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
Exception raised from device_synchronize at ../c10/cuda/CUDAFunctions.cpp:130 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x5c (0x7fd26d98d6dc in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::device_synchronize() + 0xfa (0x7fd2cbf2f76a in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #2: THCPModule_cudaSynchronize(_object*, _object*) + 0x2d (0x7fd2a66a3c2d in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #16: __libc_start_main + 0xf2 (0x7fd2d920e152 in /usr/lib/libc.so.6)

case 1 works!
```

## Expected behavior

both case 1 and case 2 works

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+9dca055
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.1

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.0a0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @bdhirsh @ngimel
Edit: edited title and description to be more accurate.

**Comment by ngimel** [comment]
Adding high priority due to crash.

**Comment by gchanan** [comment]
@bdhirsh this is fixed right?
