### ISSUE TITLE
Bug when combining AMP with channels_last memory format

### ISSUE THREAD

**Issue by zixeljupo** [pytorch/pytorch#49282]
## 🐛 Bug when combining AMP with channels_last memory format

CUDA unexpectedly fails with different errors when training torchvision models with AMP and channels_last memory format.

## To Reproduce

1. Create new conda environment:
`conda create -n test_environment python=3.7 && conda activate test_environment`

2. Install torch, torchvision, cudatoolkit:
`conda install pytorch=1.7.1 torchvision=0.8.2 cudatoolkit=10.2 -c pytorch`
3. Run the following code snippet:

```
import torch
from torch.cuda import amp
from torchvision.models import mnasnet0_5 as model_class


device = torch.device('cuda:0')
torch.cuda.set_device(device)

model = model_class(pretrained=False)
model = model.to(device=device, memory_format=torch.channels_last)

model.train()

scaler = amp.GradScaler(enabled=True)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

x = torch.zeros((1, 3, 256, 256), dtype=torch.float, device=device)
x = x.contiguous(memory_format=torch.channels_last)

for i in range(100):

    optimizer.zero_grad()

    with amp.autocast(enabled=True):
        loss = model(x).contiguous(memory_format=torch.contiguous_format).mean()

    scaler.scale(loss).backward()
    scaler.step(optimizer)
    scaler.update()

    print('done with batch ' + str(i + 1))
```

This script run results with:
```
(test_environment) naumenko@Cube02:~$ python amp_and_channels_last.py
done with batch 0
Traceback (most recent call last):
  File "amp_and_channels_last.py", line 28, in <module>
    scaler.step(optimizer)
  File "/home/naumenko/miniconda3/envs/test_environment/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 320, in step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/home/naumenko/miniconda3/envs/test_environment/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 320, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
RuntimeError: CUDA error: an illegal memory access was encountered
```

When running this code with batch size=16 and CUDA_LAUNCH_BLOCKING=1, it produces the following stack trace:
```
(test_environment) naumenko@Cube02:~$ CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=3 python amp_and_channels_last.py
done with batch 0
Traceback (most recent call last):
  File "amp_and_channels_last.py", line 27, in <module>
    scaler.scale(loss).backward()
  File "/home/naumenko/miniconda3/envs/test_environment/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/naumenko/miniconda3/envs/test_environment/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132,in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 24, 64, 64], dtype=torch.half, device='cuda', requires_grad=True).to(memory_format=torch.channels_last)
net = torch.nn.Conv2d(24, 16, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half().to(memory_format=torch.channels_last)
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f4968075e10
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 1, 24, 64, 64,
    strideA = 98304, 1, 1536, 24,
output: TensorDescriptor 0x7f49680740c0
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 1, 16, 64, 64,
    strideA = 65536, 1, 1024, 16,
weight: FilterDescriptor 0x7f496807dd50
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NHWC
    nbDims = 4
    dimA = 16, 24, 1, 1,
Pointer addresses:
    input: 0x7f497179f200
    output: 0x7f49709cc000
    weight: 0x7f49719ff800
Additional pointer addresses:
    grad_output: 0x7f49709cc000
    grad_input: 0x7f497179f200
Backward data algorithm: 1
```

## Expected behavior

Expected behavior: clear run without errors.

## Environment

Environment settings:
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.5 LTS (x86_64)
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 430.26
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he8ac12f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.2           py37h54aff64_0
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.8.2                py37_cu102    pytorch

**Comment by xwang233** [comment]
Thanks for the report. Do you also see the error with the short repro script provided in the exception message? If so, can you also try a cuda 11 + cudnn 8 wheel and see if the cudnn error still exists?

**Comment by zixeljupo** [comment]
I tested short reproduction script in failing setup, and it did not show any error, even when looping the execution script.

I tested reproduction steps on other machines I have access to, and it did not show any error (one was with 1080ti and another with Titan V). I suppose that it can be a driver problem or something like that.

I'll test this one with cuda 11 + cudnn 8 as xwang233 suggested, and will report my results.

**Comment by ptrblck** [comment]
@zixeljupo  I just reran your two code snippets with the latest stable PyTorch release `1.7.1` using CUDA11.0+cudnn8.0.5 as well as CUDA10.2+cudnn7.6.5 and both work on my RTX 2080Ti.

My CUDA10.2 env:
```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.86
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: TITAN V

Nvidia driver version: 455.23.05
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.8.2                py38_cu102    pytorch
```

My CUDA11.0 env:
```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.86
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: TITAN V

Nvidia driver version: 455.23.05
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] torchvision               0.8.2                py38_cu110    pytorch
```

I added `print(torch.cuda.get_device_name(0))` at the beginning of the script and masked the 2080Ti with `CUDA_VISIBLE_DEVICES` to make sure I'm not using the TitanV.

I'm currently unsure, what might be causing the illegal memory access in your code.

**Comment by ptrblck** [comment]
@zixeljupo were you able to reproduce the illegal memory access using the CUDA11.0+cudnn8.0.5 binaries?
Also, do you have any changes in the initially posted code or are you able to reproduce the issue with the posted code?

**Comment by zixeljupo** [comment]
> @zixeljupo were you able to reproduce the illegal memory access using the CUDA11.0+cudnn8.0.5 binaries?
> Also, do you have any changes in the initially posted code or are you able to reproduce the issue with the posted code?

No, I did not have time to do this yet. Could you tell, please, whether there is a wheel with both cuda and cudnn in it, or I should install cudnn by myself, and then somehow provide the path to it to pytorch? This will help a lot to finish this.

**Comment by xwang233** [comment]
@zixeljupo You can get a pytorch 1.7.1 or nightly wheel here https://pytorch.org/get-started/locally/ with cuda 11.0 + cudnn 8.0.5. Just make sure you choose cuda 11.0 there. The wheels are bundled with cuda and cudnn runtime, and you don't need to install them separately.

You may need to update the Nvidia driver to above 455 to use cuda 11.0.

**Comment by zixeljupo** [comment]
> @zixeljupo were you able to reproduce the illegal memory access using the CUDA11.0+cudnn8.0.5 binaries?
> Also, do you have any changes in the initially posted code or are you able to reproduce the issue with the posted code?

This started working properly under latest nvidia driver and cuda 11. I suppose the main problem was the driver version (430.26). Maybe, someone can reproduce this error by installing this driver. Not sure whether I should close this issue as the problem can hurt someone with the same driver version.
