### ISSUE TITLE
wheels for python2.7 install failed: cuda 8.0

### ISSUE THREAD

**Issue by Xls1994** [pytorch/pytorch#493]
sudo pip install https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp27-cp27mu-linux_x86_64.whl

Collecting torch-cuda80==0.1.6.post17 from https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp27-cp27mu-linux_x86_64.whl
  Downloading https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp27-cp27mu-linux_x86_64.whl (394.0MB)
    100% |████████████████████████████████| 394.0MB 4.0kB/s 
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from torch-cuda80==0.1.6.post17)
Installing collected packages: torch-cuda80
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: torch-cuda80==0.1.6.post17 .dist-info directory not found

**Comment by Xls1994** [comment]
My Cuda version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

**Comment by fmassa** [comment]
I think this is related to https://github.com/pytorch/pytorch/issues/482
Could you try seeing if `import torch` works for you?

**Comment by apaszke** [comment]
Yeah, that's an exact duplicate. Let's track this problem in a single issue (#482).
