### ISSUE TITLE
Type annotations of constant values in Modules are not honored

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#49511]
## 🐛 Bug

When we insert a constant to a module class's constant table, a type is inferred based on the concrete value only rather than reading from user's type annotation. Later when constant is used, a type is re-constructed based on stored IValue alone. This can lead to subsequent failures due to type mismatch.

Where constant type is inferred:
https://github.com/pytorch/pytorch/blob/676bfa6dbd389a6077c4c5dfb8fcc8f186bca4c1/torch/csrc/jit/frontend/concrete_module_type.cpp#L221

Where type is recosntructed when creating a constant IR value based on IValue:
https://github.com/pytorch/pytorch/blob/676bfa6dbd389a6077c4c5dfb8fcc8f186bca4c1/torch/csrc/jit/python/python_sugared_value.cpp#L463

## To Reproduce

Run following code:
```
import torch

class Model(torch.nn.Module):
    def __init__(
        self, dropout: float=0.0
    ):
        super(Model, self).__init__()
        self.do = torch.nn.Dropout(dropout)

    def forward(self, input0: torch.Tensor):
        return self.do(input0)

# this works:
# dropout_rate: float = 0.0

# this doesn't:
dropout_rate: float = 0

model = Model(dropout_rate)
scripted = torch.jit.script(model)
```

Inside `torch.nn.Dropout`, `dropout_rate` is stored in its constant `p`, which is also annotated as `float`
https://github.com/pytorch/pytorch/blob/676bfa6dbd389a6077c4c5dfb8fcc8f186bca4c1/torch/nn/modules/dropout.py#L9

Error message:
```
Traceback (most recent call last):
  File "min_type_hint.py", line 20, in <module>
    scripted = torch.jit.script(model)
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 897, in script
    return torch.jit._recursive.create_script_module(
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_recursive.py", line 370, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_recursive.py", line 426, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_recursive.py", line 406, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_recursive.py", line 430, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_recursive.py", line 322, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:

dropout(Tensor input, float p=0.5, bool training=True, bool inplace=False) -> (Tensor):
Expected a value of type 'float' for argument 'p' but instead found type 'int'.
:
  File "/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/dropout.py", line 58
    def forward(self, input: Tensor) -> Tensor:
        return F.dropout(input, self.p, self.training, self.inplace)
               ~~~~~~~~~ <--- HERE
```

## Expected behavior

Expect TorchScript to respect user type annotation and infer constant `dropout_rate` is float not int.

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Nikitha, should we move this to in-progress?

**Comment by SplitInfinity** [comment]
At the very least, we should include in the error message a suggestion that the user needs to use a float literal (e.g. `0.0`).

**Comment by gmagogsfm** [comment]
I think this has been fixed. Closing.
