### ISSUE TITLE
Recent Python versions break JIT tests (locally defined classes don't work well, even with global)

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#49617]
## 🐛 Bug

Recent Python versions updated the inspect.getsource* mechanism for classes. This breaks many of our JIT tests.

## To Reproduce

Run test/test_jit.py on Python 3.9.

## Expected behavior

Tests pass.

## Environment

Python 3.9
PyTorch master

## Additional context

Python bug report: https://bugs.python.org/issue42666

My impression is that it's a case of "Don't do that then".

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @gmagogsfm

**Comment by t-vi** [comment]
@malfet I heard rumors you might be looking at this. :)

**Comment by eellison** [comment]
Related: https://github.com/pytorch/pytorch/issues/28258

**Comment by malfet** [comment]
@t-vi I've fixed some issues with torch.jit parsing, but not all. Do you have a short example what is still not working in master?

**Comment by t-vi** [comment]
As of b5ab0a7f781411878b30b0d83cda47f9c364dc03 (Friday Jan 8), test/test_jit.py throws a lot of errors, e.g. TestEnum.
E.g.:
```
EEEEEEEEEEEEEEE
======================================================================
ERROR: test_closed_over_enum_constant (jit.test_enum.TestEnum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/_utils_internal.py", line 49, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "/usr/lib/python3.9/inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.9/inspect.py", line 851, in findsource
    raise OSError('could not find class definition')
OSError: could not find class definition

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tv/pytorch/pytorch/test/jit/test_enum.py", line 219, in test_closed_over_enum_constant
    def closed_over_aliased_type():
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/jit/_script.py", line 977, in script
    fn = torch._C._jit_script_compile(
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/jit/annotations.py", line 329, in try_ann_to_type
    torch.jit._script._recursive_compile_class(ann, loc)
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/jit/_script.py", line 1094, in _recursive_compile_class
    _compile_and_register_class(obj, rcb, _qual_name)
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/jit/_script.py", line 62, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/jit/frontend.py", line 175, in get_jit_class_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(cls, torch._C.ErrorReport.call_stack())
  File "/home/tv/pytorch/pytorch/build/lib.linux-x86_64-3.9/torch/_utils_internal.py", line 56, in get_source_lines_and_file
    raise OSError(msg) from e
OSError: Can't get source for <enum 'Color'>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
'__torch__.jit.test_enum.Color' is being compiled since it was called from 'closed_over_aliased_type'
  File "/home/tv/pytorch/pytorch/test/jit/test_enum.py", line 220
        @torch.jit.script
        def closed_over_aliased_type():
            return a.RED.value
                   ~~~~~~~~~~~ <--- HERE


```

**Comment by gmagogsfm** [comment]
> @t-vi I've fixed some issues with torch.jit parsing, but not all. Do you have a short example what is still not working in master?

@malfet, could you show me a few example PRs on how you fixed these issues? interested to learn more about it and see if I can help.

**Comment by malfet** [comment]
@gmagogsfm I don't think we can do much here, as @t-vi correctly pointed out, this is regression in Python-3.9 inspect side, where following ceased to work:
```
import inspect

def test_me():
    global Barr
    class Barr:
        pass
    print(inspect.getsource(Barr))

if __name__ == "__main__":
    test_me()
```
But what I don't understand, is why use of `global` is so prevalent in JIT tests?
