### ISSUE TITLE
DISABLED test_profiler_with_script_remote_rpc_single_threaded (__main__.TensorPipeRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#49634]
https://app.circleci.com/pipelines/github/pytorch/pytorch/253337/workflows/d7deaf65-3973-4e30-9892-c286d8b843b0/jobs/9751335/steps

```
Dec 18 23:49:33 ======================================================================
Dec 18 23:49:33 ERROR [1.444s]: test_profiler_with_script_remote_rpc_single_threaded (__main__.TensorPipeRpcTestWithSpawn)
Dec 18 23:49:33 ----------------------------------------------------------------------
Dec 18 23:49:33 Traceback (most recent call last):
Dec 18 23:49:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 280, in wrapper
Dec 18 23:49:33     self._join_processes(fn)
Dec 18 23:49:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 397, in _join_processes
Dec 18 23:49:33     self._check_return_codes(elapsed_time)
Dec 18 23:49:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _check_return_codes
Dec 18 23:49:33     raise RuntimeError(error)
Dec 18 23:49:33 RuntimeError: Processes 1 exited with error code 10
```

```
Dec 18 23:45:14   test_profiler_with_script_remote_rpc_single_threaded (__main__.TensorPipeRpcTestWithSpawn) ... ERROR:root:Caught exception: 
Dec 18 23:45:14 Traceback (most recent call last):
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 283, in wrapper
Dec 18 23:45:14     fn()
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 35, in wrapper
Dec 18 23:45:14     return_value = f(self, *args, **kwargs)
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Dec 18 23:45:14     return_value = old_test_method(self, *arg, **kwargs)
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1766, in test_profiler_with_script_remote_rpc_single_threaded
Dec 18 23:45:14     self._run_test_profiler_with_script_remote_rpc()
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1752, in _run_test_profiler_with_script_remote_rpc
Dec 18 23:45:14     use_record_function=True,
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1583, in _profiler_test_with_rpc
Dec 18 23:45:14     self.assertTrue(scope_event.time_range.end > rpc_event.time_range.end)
Dec 18 23:45:14   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
Dec 18 23:45:14     raise self.failureException(msg)
Dec 18 23:45:14 AssertionError: False is not true
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by rohan-varma** [comment]
Haven't been able to reproduce in CI after 1000+ runs, so closing to re-enable. Sent #49983 which should improve the logging a bit in case it does fail again.
