### ISSUE TITLE
File "setup.py", line 773:subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by tobimichigan** [pytorch/pytorch#49677]
## To Reproduce

1. clone the pytorch git repo
2. install dependencies
3. run setup.py

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 660M
Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[conda] # packages in environment at /home/ur/anaconda3/envs/Pytorch_env:

```

 - PyTorch Version (building from current source on predefined pytorch conda env):
 - OS ( Linux):
 - How you installed PyTorch (source):
 - Build command you used (if compiling from source:python3 setup.py install):
 - Python version 3.8:
 - CUDA/cuDNN version 11:
 - GPU models and configuration GTX 630m:
 - Any other relevant information:
Error occured at 5%, 23% and 29 % respectively.
## Additional context

<!-- Add any other context about the problem here. -->

**Comment by ngimel** [comment]
Please provide full build logs.

**Comment by malfet** [comment]
GTX 630m is [sm_20](https://en.wikipedia.org/wiki/Fermi_(microarchitecture)) GPU isn't it? If this is the case, then attempting to build PyTorch from source with CUDA-11.1 is expected to fail, as CUDA-11 (nor CUDA-10) support code generation for those generation of GPUs.

**Comment by ngimel** [comment]
I think 630m is sm_30 (Kepler) which is also not supported.

**Comment by tobimichigan** [comment]
@malfet @ngimel @svenstaro @eklitzke 
Okay guys, here we go(pls see the img attached.:
This is the actual script: 

`(Pytorch_env) usr@usr-P2542:~/Algorithms/pytorch$ python3 setup.py install
Building wheel torch-1.8.0a0
-- Building version 1.8.0a0
cmake --build . --target install --config Release -- -j 8
[1/5683] Performing build step for 'nccl_external'
............
Traceback (most recent call last):
  File "setup.py", line 773, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "/home/usr/Algorithms/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/usr/Algorithms/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/home/usr/Algorithms/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/usr/anaconda3/envs/Pytorch_env/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.`
![pytorch_Issues](https://user-images.githubusercontent.com/5084987/102937401-58cea980-44aa-11eb-88a6-bc14b354d2d9.png)
