### ISSUE TITLE
amp does not work with LayerNorm gradient checkpointing

### ISSUE THREAD

**Issue by mli0603** [pytorch/pytorch#49738]
## 🐛 Bug

When wrapping a LayerNorm that has gradient checkpointed layer, it reports error `RuntimeError: expected scalar type Half but found Float` if amp is used. Specifically, it seems like the gradient scaler is the problem.

Full traceback
```
Traceback (most recent call last):
  File "/home/max/anaconda3/envs/sttr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/max/anaconda3/envs/sttr/lib/python3.6/site-packages/torch/random.py", line 121, in fork_rng
    yield
  File "/home/max/anaconda3/envs/sttr/lib/python3.6/site-packages/torch/utils/checkpoint.py", line 95, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/max/git_ws/stereo-transformer/dev/test_amp_checkpointing.py", line 17, in custom_forward
    return module(*inputs)
  File "/home/max/anaconda3/envs/sttr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/max/anaconda3/envs/sttr/lib/python3.6/site-packages/torch/nn/modules/normalization.py", line 170, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "/home/max/anaconda3/envs/sttr/lib/python3.6/site-packages/torch/nn/functional.py", line 2095, in layer_norm
    torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
```

## To Reproduce
Run following code
```
import torch
import torch.nn as nn
from torch.utils.checkpoint import checkpoint


class Net(nn.Module):
    def __init__(self, in_size, out_size):
        super().__init__()

        self.conv = nn.Conv2d(in_size, out_size, 1)
        self.norm = nn.LayerNorm(64)

    def forward(self, inp):
        # checkpoint cross attn
        def create_custom_forward(module):
            def custom_forward(*inputs):
                return module(*inputs)

            return custom_forward

        output = checkpoint(create_custom_forward(self.conv), inp)
        output = output.permute(0, 2, 3, 1)  # permute so we have channel in the end
        output = checkpoint(create_custom_forward(self.norm), output)

        return output


in_size = 32
out_size = 64
net = Net(in_size, out_size).cuda()
opt = torch.optim.SGD(net.parameters(), lr=0.001)

net.train()

# without amp
for epoch in range(10):
    inp = torch.randn([1, 32, 32, in_size], requires_grad=True).cuda()
    output = net(inp)
    loss = output.sum()
    loss.backward()
    opt.step()
    opt.zero_grad()  # set_to_none=True here can modestly improve performance

print("finish training without amp")

# with amp
scaler = torch.cuda.amp.GradScaler()

for epoch in range(10):
    inp = torch.randn([1, 32, 32, in_size], requires_grad=True).cuda()
    with torch.cuda.amp.autocast():
        output = net(inp)
        loss = output.sum()
    scaler.scale(loss).backward()
    scaler.step(opt)
    scaler.update()
    opt.zero_grad()  # set_to_none=True here can modestly improve performance

print("finish training with amp")
```
## Expected behavior
With amp enabled, it should not report bug and run like without amp.

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: TITAN RTX
Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

cc @mcarilli

**Comment by mcarilli** [comment]
Can you check if https://github.com/pytorch/pytorch/pull/49757 fixes the issue?  Diffs are 2 lines of python, should be easy to reinstall if you built from source.  If you installed from pip, alter your installed pytorch in place:
```
>>> import sys
>>> import torch
>>> sys.modules["torch"]
```
and edit `torch/utils/checkpoint.py` with the PR's diffs at the path `sys.modules["torch"]` points to.

**Comment by mli0603** [comment]
@mcarilli Yes, the commit seems to fix it. I didn't check if they produce the same result, but the code example runs without any error. Thanks!
When will this be merged?

**Comment by mcarilli** [comment]
Soon, it's a small change and @ngimel already approved it.
