### ISSUE TITLE
Error when running nn.Unflatten with TorchScript 

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#49742]
## To Reproduce

If you run
```python
import torch
import torch.nn as nn

s = nn.Unflatten(1, (5, 5))
s.forward(torch.rand((5, 25)))  # Works Fine

jit = torch.jit.script(s)
jit.forward(torch.rand((5, 25)))
```

Brings up

```
Traceback (most recent call last):
  File "scratch.py", line 8, in <module>
    jit.forward(torch.rand((5, 25)))
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/nn/modules/flatten.py", line 133, in forward
    def forward(self, input: Tensor) -> Tensor:
        return input.unflatten(self.dim, self.unflattened_size)
               ~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: false INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1607370140761/work/aten/src/ATen/core/boxing/KernelFunction.cpp":76, please report a bug to PyTorch. Tried to call KernelFunction::callBoxed() on a KernelFunction that can only be called with KernelFunction::call(). opname: aten::unflatten.int If you're using mobile selective build please make sure to include all ops exported from `torch.jit.export_opnames(model)`.
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux (Fedora 32)
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Python version: 3.6.10
 - CUDA/cuDNN version: N/A

cc @gmagogsfm

**Comment by alanhdu** [comment]
This is potentially related to https://github.com/pytorch/pytorch/issues/49538, although the error message is quite different, so it could be a unrelated bug.

**Comment by nikithamalgifb** [comment]
Took a quick look, I was not able to reproduce the same error on my local setup. May be the exact setup is required to reproduce the issue?

**Comment by alanhdu** [comment]
The exact output from `collect_env.py`:

```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora release 32 (Thirty Two) (x86_64)
GCC version: (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Clang version: 10.0.1 (Fedora 10.0.1-3.fc32)
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py36h8c4c3a4_2    conda-forge
[conda] mkl_fft                   1.2.0            py36h68bb277_1    conda-forge
[conda] mkl_random                1.2.0            py36h7c3b610_1    conda-forge
[conda] numpy                     1.19.2           py36h54aff64_0  
[conda] numpy-base                1.19.2           py36hfa32c7d_0  
[conda] pytorch                   1.7.1               py3.6_cpu_0  [cpuonly]  pytorch
```

**Comment by pfeatherstone** [comment]
I've seen this too when trying to do an ONNX export

**Comment by alanhdu** [comment]
`torch.jit.script` seems to work now, although there's still a problem using `torch.jit.trace` -- I will close this issue and keep the tracing issue in https://github.com/pytorch/pytorch/issues/49538 to avoid duplicates.
