### ISSUE TITLE
Max pool segfaults

### ISSUE THREAD

**Issue by Antupis** [pytorch/pytorch#4986]
OS: 	Linux Mint 17.3 Rosa
PyTorch version: 0.3post4
How you installed PyTorch (conda, pip, source): pip
Python version: 3.5.2

Max pool segfaults when  kernel size is bigger than input tensor.
Example

```
import torch
from torch import nn, autograd

i = autograd.Variable(torch.randn(1, 1, 1))
m = nn.MaxPool1d(2)
m(i)

*** Error in `python3': free(): invalid pointer: 0x00007f2413977720 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f242754c7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f242755537a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f242755953c]

```

**Comment by zou3519** [comment]
Thanks for the report! This appears to be fixed in master:
```
>>> import torch
>>> from torch import nn, autograd
>>>
>>> i = autograd.Variable(torch.randn(1, 1, 1))
>>> m = nn.MaxPool1d(2)
>>> m(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/rzou/pytorch/pytorch/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/private/home/rzou/pytorch/pytorch/torch/nn/modules/pooling.py", line 65, in forward
    self.return_indices)
  File "/private/home/rzou/pytorch/pytorch/torch/nn/functional.py", line 333, in max_pool1d
    ret = torch._C._VariableFunctions.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (1x1x1). Calculated output size: (1x1x0). Output size is too small at /private/home/rzou/pytorch/pytorch/aten/
src/THNN/generic/SpatialDilatedMaxPooling.c:67
``
