### ISSUE TITLE
MultiGPU hangs Titan Xp in multiprocessing/queue.py

### ISSUE THREAD

**Issue by malbergo** [pytorch/pytorch#4987]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Hi there,**

I have been trying for about a week and a half to get all 3 of my NVIDIA Titan Xp, but the process always hangs in the multiprocessing directory in the "queues.py" and the "synchronizing.py" whenever I use more than 1 of them.

MY SETUP:
- OS: macOS Sierra 10.12.5
- PyTorch version: 0.3.0.post4
- PyTorch installation via pip
-Python version: 3.5
-CUDA/cuDNN version: CUDA 8.0.61  and torch.backends.cudnn.version() = 7003
-GPU models and configuration: 3 NVIDIA Titan Xps installed on PCI express board 

This problem seems to occur whenever I use the data parallel functionality in PyTorch. It happens on very simple calculations and in things like ConvNets etc. It loads the network architecture and then gets stuck at what seems to be the beginning of training the network.

> Traceback (most recent call last):
  File "train.py", line 229, in <module>
    output = netD(inputv)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chris/Documents/MPhilProjects/GANs/PyTorchApproach/DCGAN-pytorch/model.py", line 110, in forward
    output = nn.parallel.data_parallel(self.main, input, range(self.ngpu))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 113, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/parallel_apply.py", line 59, in parallel_apply
    thread.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 36, in _worker_loop
    r = index_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
Process Process-2:
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 36, in _worker_loop
    r = index_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 342, in get
    with self._rlock:
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 36, in _worker_loop
    r = index_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 342, in get
    with self._rlock:
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

I tried looking at the connections b/w them and got the following result:
![image](https://user-images.githubusercontent.com/6062598/35688012-1823ef76-0768-11e8-8fca-c6147df47a80.png)

I tried testing the p2pBandwidth example that comes in cuda and got the following result:
![image](https://user-images.githubusercontent.com/6062598/35688187-786df2aa-0768-11e8-87d0-a6c7462df3bd.png)

But I am still essentially clueless as to why they won't work together. Any advice / solutions would be **greatly** appreciated!

Best,
Michael

**Comment by apaszke** [comment]
Are you running multiple data parallel training scripts that use the same GPUs (or share at least one of them)?

**Comment by malbergo** [comment]
Thanks for your quick response. I am running the "examples DCGAN" from the PyTorch repository [here](https://github.com/pytorch/examples/tree/master/dcgan).

**Comment by apaszke** [comment]
My question was not so much about the concrete script you're running, but about how you are launching it, or rather how many instances do you launch at the same time. It's a known fact that if you'll have multiple data-parallel scripts running at the same time, then you can get deadlocks because of the NVIDIA's NCCL library that we're using for communication between GPUs.

**Comment by malbergo** [comment]
Thanks for clarifying. The only calls to data_parallel in the script are in the definitions of the discriminator and generator in the GAN model being employed. This call is made like:

`class _netG(nn.Module): `

    def __init__(self, ngpu):
        super(_netG, self).__init__()
        self.ngpu = ngpu
        self.main = nn.Sequential(
            # input is Z, going into a convolution
            nn.ConvTranspose2d(     nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            # state size. (ngf*8) x 4 x 4
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            # state size. (ngf*4) x 8 x 8
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            # state size. (ngf*2) x 16 x 16
            nn.ConvTranspose2d(ngf * 2,     ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            # state size. (ngf) x 32 x 32
            nn.ConvTranspose2d(    ngf,      nc, 4, 2, 1, bias=False),
            nn.Tanh()
            # state size. (nc) x 64 x 64
        )

    def forward(self, input):
        if isinstance(input.data, torch.cuda.FloatTensor) and self.ngpu > 1:
            output = nn.parallel.data_parallel(self.main, input, range(self.ngpu))
        else:
            output = self.main(input)
        return output`

`netG = _netG(ngpu
netG.apply(weight_init)
if opt.netG != ":
      netG.load_state_dict(torch.load(opt.netG))
print(netG)`


From my perspective, though I still could be misunderstanding your, it seems that there is only one data_parallel script (or would you consider a second being the one in the discriminator?). The script allows for a flag to specify the number of gpus to use as well,  i.e. "--ngpu 2" or "--ngpu 1".

**Comment by SsnL** [comment]
@malbergo Okay, Adam is asking whether you are launching multiple such scripts?

**Comment by malbergo** [comment]
Hi @SsnL, thanks for clarifying. I'm not running multiple such scripts. That is the only script I am running. I cloned the pytorch/examples/dcgan repo, updated the directory paths to align with mine for dataset loading, ran it successfully on CPU and 1 GPU, and see it stall with the above error for n > 1 gpus. I am not running any other scripts that use data_parallel (or any other scripts at all). 

From what I can tell, running the main.py file in the example found [here](https://github.com/pytorch/examples/tree/master/dcgan) does not make calls to other scripts that may use data_parallel.

**Comment by Stonesjtu** [comment]
Seems like you are locked in the multi-worker version `dataloader`, could you plz upload your customized `dataloader` and `dataset`?

**Comment by malbergo** [comment]
Thanks for looking into this @Stonesjtu. I have this problem however with the exact example given by PyTorch. My custom dataloader and dataset are below.

Definition for loading function:

`
```
 def load_physics_data(filename1, filename2):

    f1 = h5py.File('/home/chris/Documents/MPhilProjects/GANs/delphes-gans/' + filename1, 'r')

    f2 = h5py.File('/home/chris/Documents/MPhilProjects/GANs/delphes-gans/' + filename2, 'r')

    #These return shape (num_images x image_dim=64 x image_dim=64)
    data1 = np.asarray(f1['1'])
    data2 = np.asarray(f2['1'])
    data = np.concatenate((data1,data2),0)
    #data_reshape = data.reshape(data.shape[0], data.shape[1] * data.shape[2])
    return
```

Then loading the data:

```
if opt.dataset == 'physics':
    data = load_physics_data('3million64', "2million64")
    data = torch.Tensor(data[:,np.newaxis,:,:])
    print(type(data))
    labels = torch.Tensor(np.zeros(data.shape[0]))
    print(type(labels))
    dataset = torch.utils.data.TensorDataset(data, labels)
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=opt.batchSize)

```


**Here** are the ones supplied in the PyTorch example:


```
if opt.dataset in ['imagenet', 'folder', 'lfw']:
    # folder dataset
    dataset = dset.ImageFolder(root=opt.dataroot,
                               transform=transforms.Compose([
                                   transforms.Resize(opt.imageSize),
                                   transforms.CenterCrop(opt.imageSize),
                                   transforms.ToTensor(),
                                   transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                               ]))

dataloader = torch.utils.data.DataLoader(dataset, batch_size=opt.batchSize,
                                       shuffle=True, num_workers=int(opt.workers))
```

**Comment by SsnL** [comment]
Does your script work without DataParallel but with DataLoader with `num_workers > 0`?

**Comment by malbergo** [comment]
I just tried with num_workers = 5 in DataLoader and no DataParallel and the script runs. What does this signify to you? Could you explain to me what num_workers is doing?

**Comment by SsnL** [comment]
@malbergo Sorry for the late response. This means that unlike suggested above dataloader probably has nothing to do with this issue. `num_workers` basically says how many subprocesses you want to create solely for data loading purpose. 

Unfortunately we can't reproduce the issue you are seeing. It sounds like that it could be an issue in broadcasting. Could you try to build from source and see if the problem still occurs?

**Comment by Stonesjtu** [comment]
@malbergo you may as well insert some `print` into the source file `data_parallel.py` and see what's blocking.

**Comment by malbergo** [comment]
I'll try to build from source and see what happens. I will let you know. I very much appreciate your help in trying to sort this out!

**Comment by soulslicer** [comment]
I have the same issue, 'ConvTranspose2d' causes a deadlock

**Comment by soulslicer** [comment]
Resolved: had to do

```
smp = mp.get_context('spawn')
self.queue = smp.Queue()
```

instead of 

```
self.queue = mp.Queue()
```
