### ISSUE TITLE
GRU and LSTM fail for seq_len = 0

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#50192]
## 🐛 Bug

[GRU](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html) and [LSTM](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html) raise a RuntimeError for inputs of `seq_len` 0.

## To Reproduce

Example:

```python3
import torch

input_size = 5
hidden_size = 6
rnn = torch.nn.GRU(input_size, hidden_size)

for seq_len in reversed(range(4)):
    output, h_n = rnn(torch.zeros(seq_len, 10, input_size))
    print('{}, {}'.format(output.shape, h_n.shape))
```

Output:
```
torch.Size([3, 10, 6]), torch.Size([1, 10, 6])
torch.Size([2, 10, 6]), torch.Size([1, 10, 6])
torch.Size([1, 10, 6]), torch.Size([1, 10, 6])
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    output, h_n = rnn(torch.zeros(seq_len, 10, input_size))
  File "/opt/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/miniconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 739, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: stack expects a non-empty TensorList
```

## Expected behavior

Should output a tensor of size `torch.Size([0, 10, 6])` and `h_0`.

## Environment

```
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: version 3.19.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0
[pip3] torch-summary==1.4.3
[pip3] torchvision==0.8.1
[conda] _pytorch_select           0.1                       cpu_0  
[conda] blas                      1.0                         mkl  
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] libmklml                  2019.0.5                      0  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py38h9ed2024_0  
[conda] mkl_fft                   1.2.0            py38hc64f4ea_0  
[conda] mkl_random                1.1.1            py38h959d312_0  
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torch-summary             1.4.3                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi
```

**Comment by zou3519** [comment]
We would accept a patch fixing this. Either a better error message or returning the correctly-shaped tensor should be good here.

**Comment by mariosasko** [comment]
This is what you get if you set `seq_len` to 0:
```python
>>> torch.zeros(0, 10, 2)
tensor([], size=(0, 10, 2))
```
It's expected that you can't perform meaningful operations on an empty tensor.

However, a more informative error message would be great.

**Comment by carlosgmartin** [comment]
@mariosasko 

> It's expected that you can't perform meaningful operations on an empty tensor.

You can. PyTorch handles arithmetic with dimensions of size 0. See also https://github.com/pytorch/pytorch/issues/4582#issuecomment-755944010.

**Comment by mariosasko** [comment]
@carlosgmartin Thanks for linking the relevant PR!

What I've meant is it's not common to work with multi-dim tensors where one dimension is equal to 0, so I wouldn't rely on this behavior. Let's see what the experts have to say.

**Comment by zou3519** [comment]
In general, PyTorch is supposed to handle operations on tensors dimensions of size 0. If you spot some code that doesn't work, please file a bug report (like this one).

There are situations where users want to use tensors with a batch dimension of size 0 (one example I saw recently was when a user sharded data across devices and some of the data had size-0 batch dims).

**Comment by jonykarki** [comment]
I would like to work on this. Any suggestions on what I should do? How difficult is this?

**Comment by carlosgmartin** [comment]
@jonykarki It seems to originate from [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorShape.cpp#L1423).

**Comment by zou3519** [comment]
The task here is two-fold I think:
1) determine if it makes sense for RNN/LSTM to return something in this case or error out. Our RNNs go through a few different backends (cudnn, thnn) so we should check that whichever solution we pick works consistently across the backends.
2) make the RNN/LSTM do whatever we decided in (1).

**Comment by carlosgmartin** [comment]
@zou3519 I think the RNN/stack function should return the correct result (A) rather than raising an error (B). I see at least 3 reasons for this:

1. From a definitional perspective, the RNN/stack function ought to handle lists of arbitrary length. A list of length 0 is still a list. Therefore, the RNN/stack function ought to handle a list of length 0. This is related to the themes I expressed [here](https://github.com/pytorch/pytorch/issues/4582#issuecomment-755944010) and [here](https://github.com/pytorch/pytorch/issues/50402#issue-783772305), as well as your own observation [earlier](https://github.com/pytorch/pytorch/issues/50192#issuecomment-756348893): That the base case *is still a case*. And it arises in real scenarios.

2. It is easier for a user to reproduce B under A, if desired for some reason, than it is to reproduce A under B. 

3. It is more common & appropriate to seek A rather than B. It's not even clear to me why one would prefer the latter. There is nothing *intrinsic to the semantics* of the RNN/stack function that should exclude length-0 inputs. If a user wants to exclude length-0 inputs for some reason that is idiosyncratic to their program, they should probably be doing that error-handling themselves, and probably earlier in their program. 

Arbitrarily excluding lists of length 0 is akin to arbitrarily excluding lists of length 1 as well.

**Comment by zou3519** [comment]
@carlosgmartin I fully agree that it would be nice (and make more sense) for RNNs to support seq_len = 0.

The thing I am concerned about is that fixing this can be a little tricky due to us having many backends for RNNs. We call into roughly the following:
- On CPU we implement our own RNN using regular PyTorch ops. This one should be relatively straightforward to fix, if we see a seq_len=0 we should do special handling to work around the "stack with empty TensorList" issue.
- On CUDA we have our own "fused THNN" CUDA kernel. This should also be relatively straightforward to fix; if we see a seq_len=0 then we should do special handling.
- On CUDA instead of calling our "fused THNN" kernel we usually call the optimized cuDNN kernel because it has superior performance to our own CUDA kernel. I don't know if the kernel supports zero-size sequence length (that's a TODO item to look into). Past cases (e.g. convolution) imply that it probably does not. Because this is a third-party library, we cannot modify the code here, so we would need to call into our "fused THNN" kernel

**Comment by zou3519** [comment]
Actually, I am overthinking this -- I was worried that we need to do some extra computation to return a new hidden state, but there is no new hidden state because the sequence length is 0, so we just return the initial hidden state

**Comment by zou3519** [comment]
(Reserving this task)

**Comment by ShujaHaider-Dev** [comment]
We are not passing a sequence with the length 0. We are passing a sentence like Apple is going down

**Comment by ShujaHaider-Dev** [comment]
Turns out inputs without a space causes this error
