### ISSUE TITLE
Tracing with autocast failed with error: "Cannot insert a Tensor that requires grad as a constant"

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#50231]
## 🐛 Bug

```
Traceback (most recent call last):
  File "repro_autocast_trace.py", line 33, in <module>
    model = torch.jit.trace(model, (x, y))
  File "/home/bowbao/repos/pytorch/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/bowbao/repos/pytorch/torch/jit/_trace.py", line 966, in trace_module
    _module_class,
  File "/home/bowbao/repos/pytorch/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/bowbao/repos/pytorch/torch/jit/_trace.py", line 335, in _check_trace
    _compilation_unit=torch._C.CompilationUnit(),
  File "/home/bowbao/repos/pytorch/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/home/bowbao/repos/pytorch/torch/nn/modules/module.py", line 878, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/bowbao/repos/pytorch/torch/nn/modules/module.py", line 851, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "repro_autocast_trace.py", line 14, in forward
    out = self.fc1(x)
  File "/home/bowbao/repos/pytorch/torch/nn/modules/module.py", line 878, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/bowbao/repos/pytorch/torch/nn/modules/module.py", line 851, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/bowbao/repos/pytorch/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/bowbao/repos/pytorch/torch/nn/functional.py", line 1665, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
```

## To Reproduce

Run the following script:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class NeuralNetWithLoss(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNetWithLoss, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x, target):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return F.nll_loss(F.log_softmax(out, dim=1), target), out

input_size = 784
hidden_size = 500
num_classes = 10

model = NeuralNetWithLoss(input_size, hidden_size, num_classes)
model.cuda()
model.eval()

with torch.cuda.amp.autocast():
    x = torch.randn(32, input_size).cuda()
    y = torch.randint(0, 10, (32,)).cuda()

    model = torch.jit.trace(model, (x, y))
```

The issue looks similar to #40910, which was using tracing with apex amp.

**Comment by gmagogsfm** [comment]
@SplitInfinity to follow-up to get more information on use case.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
