### ISSUE TITLE
Using old-style  functions: RuntimeError: _Map_base::at

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5025]
A simple old-style function (on version '0.4.0a0+b7752ef'):

The error message is quite cryptic :)

```python
class OldFunction(torch.autograd.Function):
    def forward(self, *inputs):
        return [torch.FloatTensor([1])]
        # or return []

class Module(torch.nn.Module):
    def forward(self, *inputs):
        return OldFunction()(*inputs)

Module()()
```
Traceback (most recent call last):
  File "bar.py", line 12, in <module>
    Module()(*[])
  File ".../python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "bar.py", line 10, in forward
    return OldFunction()(*inputs)
RuntimeError: _Map_base::at
```

**Comment by vadimkantorov** [comment]
Now it's `TypeError: NewFunctionBackward.forward: expected Variable (got list) for return value 0` which is better, but if it said that a Tuple is expected instead of List or if it cast List to a Tuple automatically, it would be better

**Comment by ezyang** [comment]
This should be relatively simple to fix

**Comment by albanD** [comment]
I think that technically, it expects that you return a either a single Tensor, or use python multiple return to return a bunch of Tensors.
It just happens that internally in python this is represented by a tuple and we can't see the difference between the two.

You think that "expected Tensor or tuple of Tensor (got list)..." is the right error message? Or you have something else in mind?

**Comment by vadimkantorov** [comment]
Yeah. I think "expected Tensor or tuple of Tensor (got list)..." would be perfect. In many places in Python both lists and tuples are accepted, so a clear error message here would be helpful!

In the old days, it even crashed :)

**Comment by rakshithvasudev** [comment]
Hello All,  I'd like to take this issue.
