### ISSUE TITLE
ModuleNotFoundError: No module named '__torch__'

### ISSUE THREAD

**Issue by Nakupenda-7** [pytorch/pytorch#50261]
**Resume training, load the model and report an error**
Loading Backbone Checkpoint './model/EfficientNet-b0/model/Epoch_36_Time_2021-01-07-00-31_checkpoint.pth'
Traceback (most recent call last):
File "train.py", line 370, in
main()
File "train.py", line 44, in main
mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, cfg, val_dataset))
File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
while not spawn_context.join():
File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "/mnt/cavaface.pytorch/train.py", line 222, in main_worker
backbone.load_state_dict(torch.load(BACKBONE_RESUME_ROOT, map_location=loc))
File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/serialization.py", line 528, in load
return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/serialization.py", line 782, in _load
result = unpickler.load()
ModuleNotFoundError: No module named '__torch__'

**Comment by skyline75489** [comment]
请不要删除 Issue 模版中原有的内容，并按照模版内容提供尽可能多的信息。

Please do not delete what is in the Issue Template and provide the necessary context accordingly.

请提供一个[最小的，可复现的例子](https://stackoverflow.com/help/minimal-reproducible-example)。

Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) if it's possible.

**Comment by gchanan** [comment]
do you have a reproduction?  Otherwise it's unlikely we can help.
