### ISSUE TITLE
Occur bug when convert a model with str input to ONNX

### ISSUE THREAD

**Issue by Toudsour** [pytorch/pytorch#50363]
## To Reproduce

Just run my following code:
```
import torch
from typing import List, Tuple


class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()

    def forward(self, input: str) -> List[str]:
        temp_str = input.split()
        return [it + 'ing' for it in temp_str]


model = torch.jit.script(MyModule())
input = "abc"
torch.onnx.export(model, (input), 'string_loop.onnx', verbose=True,
                  input_names=['input_string'])
```

Get error message on my machine 
```
Traceback (most recent call last):
  File "/home/toud/Code/scratch/Python/pytorch_convert/String/basic_string_test.py", line 16, in <module>
    torch.onnx.export(model, (input), 'string_loop.onnx', verbose=True,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 409, in _model_to_graph
    graph, params, torch_out = _create_jit_graph(model, args,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 367, in _create_jit_graph
    graph = _propagate_and_assign_input_shapes(
RuntimeError: s_iter != stack.end() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/python/script_init.cpp":448, please report a bug to PyTorch. 

Process finished with exit code 1
```

## Expected behavior

I want to test if I could have export a model with str input to ONNX format. If I can, it means I could write some pre-processing or post-processsing with torchscript and export them to ONNX for inference.

## Environment

PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.1+cpu
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cpu
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@Toudsour - FYI - only tensor, list and tuples are supported as input to the export API.

**Comment by Toudsour** [comment]
Thank @spandantiwari  for the explanation.

Does PyTorch plan to support more types in the future?

**Comment by spandantiwari** [comment]
ONNX standard currently support only the following types: tensor, sequence, map. That is one of the reasons for the current type support. We don't have immediate plans for adding more types for model inputs to export API. 
As a workaround, would it possible to consider encoding the strings to numeric representation in this case?

**Comment by Toudsour** [comment]
We thought about using a numeric tensor as input and convert it into string in the torch script, so I tried the following code:
```
class StringSplit(torch.nn.Module):
    def __init__(self):
        super(StringSplit, self).__init__()

    def forward(self, input):
        sentence = ""
        for i in input:
            sentence = sentence + chr(i)
        words = sentence.split()
        return words


model = torch.jit.script(StringSplit())
input = torch.tensor([99, 100, 111, 120], dtype=torch.int8)
torch.onnx.export(model, input, 'string_loop.onnx', verbose=True,
                  input_names=['input_string'])
```

but I got:
```
/usr/bin/python3.8 /home/toud/Code/scratch/Python/pytorch_convert/String/basic_string_test.py
Traceback (most recent call last):
  File "/home/toud/Code/scratch/Python/pytorch_convert/String/basic_string_test.py", line 34, in <module>
    torch.onnx.export(model, input, 'string_loop.onnx', verbose=True,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 968, in _run_symbolic_function
    torch._C._jit_pass_onnx_block(b, new_block, operator_export_type, env)
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 930, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/toud/.local/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator chr to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

Process finished with exit code 1

```
Do you know how how to convert the numeric tensor into string?

**Comment by seizeMx** [comment]
I have same problem, did you find solution to close this? @Toudsour
