### ISSUE TITLE
[TorchScript] Rough edges discovered during type system rewrite

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#50444]
Use this issue to document all the rough edges discovered during the (re-)writing of TorchScript type system (#50434 ).

- Behaviors of user-defined subclasses of torch.tensor are silently ignored (https://github.com/gmagogsfm/TorchScriptStudy/blob/main/tensor_subclass.py). Since we do not allow user-defined subclasses of torch.tensor, it should be explicitly detected in try_ann_to_type() to give users meaningful warning of error message

- When module type constructor is invoked inside TorchScript, the error message is mystic.

https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-module.bad.py

```
python test-module.bad.py 
Eager:  5
Traceback (most recent call last):
  File "test-module.bad.py", line 23, in <module>
    m = torch.jit.script(MyModel(2))
  File "/data/users/pengwu/pytorch/torch/jit/_script.py", line 901, in script
    qualified_name = _qualified_name(obj)
  File "/data/users/pengwu/pytorch/torch/_jit_internal.py", line 870, in _qualified_name
    raise RuntimeError("Could not get name of python class object")
RuntimeError: Could not get name of python class object
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
