### ISSUE TITLE
When I was compiling, these errors appeared, what should I do

### ISSUE THREAD

**Issue by nmanhong** [pytorch/pytorch#50523]
My command is "python3 setup.py build --cmake-only" "ccmake build", I chose openblas, "python3 setup.py install".
My system is based on arm
An error was prompted:
```
"FAILED: bin/native_test
: && /opt/rh/devtoolset-7/root/usr/bin/c++ -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -O2 -DNDEBUG -DNDEBUG -rdynamic caffe2/CMakeFiles/native_test.dir/__/aten/src/ATen/test/native_test.cpp.o -o bin /native_test -Wl,-rpath,/home/loongson/gitTest/pytorch/build/lib:/usr/local/lib64: lib/libgtest_main.a -Wl,--no-as-needed,"/home/loongson/ gitTest/pytorc h/build/lib/libtorch.so" -Wl,--as-needed -Wl,--no-as-needed,"/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so" -Wl, --as-needed lib/libprotobuf.a lib/libc10.so /usr/local/lib64/libopenblas.so lib/libgtest.a -pthread &&:
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘zgemm_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘sdot_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘daxpy_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘zdotc_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘dgemv_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘scopy_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘zdotu_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘dscal_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘dgemm_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘dcopy_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘cdotc_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘cdotu_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘cgemm_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘sgemm_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘saxpy_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘sgemv_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘ddot_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘dswap_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘sscal_’
/home/loongson/gitTest/pytorch/build/lib/libtorch_cpu.so: undefined reference to ‘sswap_’
collect2: error: ld returned 1 exit status
[2407/2809] Building CXX object caffe2/CMakeFiles/vec256_t...AULT.dir/__/aten/src/ATen/test/vec256_test_all_types.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 773, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/home/loongson/gitTest/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/loongson/gitTest/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/loongson/gitTest/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command'['cmake3','--build','.','--target','install','--config','Release','--','-j' , '4']' returned non-zero exit status 1.
[loongson@localhost pytorch]$ python3 setup.py clean
Building wheel torch-1.8.0a0
"
```
cc @malfet @seemethere @walterddr

**Comment by nmanhong** [comment]
@svenstaro

**Comment by walterddr** [comment]
could you share more on your setting. e.g. how did you install openblas? do you have multiple installed in your system? and does the linker flag `/usr/local/lib64/libopenblas.so` actually contains the share library you desire?

**Comment by nmanhong** [comment]
@walterddr
Yes, there is my openblas shared library. When I switch to 1.7, these errors disappeared

**Comment by malfet** [comment]
@nmanhong can you please share the full build log (please `rm -rf build` folder before running `setup.py` again)
