### ISSUE TITLE
Unable to compile CUDAExtension with Pytorch 1.5 or above

### ISSUE THREAD

**Issue by MisakaZipi** [pytorch/pytorch#50530]
## To Reproduce

1.I try to reproduce some projects that need to compile CUDAExtension, such as 
      https://github.com/baowenbo/DAIN/blob/master/PWCNet/correlation_package_pytorch1_0/setup.py
   But it only works with PyTorch 1.4 and below and now I hope to implement this project on 3090 GPU

Traceback (most recent call last):
  File "/root/miniconda3/envs/ddd/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/ddd/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I also tried other methods, such as changing - v to -- version. Not successful
## Expected behavior

Would you please tell me what should I do to solve this problem?

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.7.1
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): conda 
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration:3090
 - Any other relevant information:

**Comment by ppwwyyxx** [comment]
On 3090 GPUs, extension build flag is wrong before https://github.com/pytorch/pytorch/pull/47585

**Comment by gchanan** [comment]
@mrshenli why is this marked bc-breaking?

**Comment by glaringlee** [comment]
@MisakaZipi 
Ninja became the default compile option for cpp extension. If you don't have ninja installed. Try this:
cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)}
