### ISSUE TITLE
When used DDP multi nodes, NCCL Connection timed out in pytorch 1.7.x (torch1.6 is ok)

### ISSUE THREAD

**Issue by maqy1995** [pytorch/pytorch#50575]
## ❓ Questions and Help

NCCL version is 2.7.8.
CUDA version is 10.2.
the system is Centos7.
Is it a bug? Has anyone else encountered this problem in the same environment?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by pritamdamania87** [comment]
@maqy1995 Can you provide a repro script?

**Comment by maqy1995** [comment]
> @maqy1995 Can you provide a repro script?

Of course. Here is a demo.I used two machine and each mahine has two gpus(each machine should run the python srcipt and set different node rank by `--nr`).
```
# -*- coding: utf-8 -*-

import argparse
import time

import torch.multiprocessing as mp
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel
from torch.utils.data import random_split
from torchvision import datasets, transforms
import torch.utils.data.distributed


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x)


# def metric_average(val, name):
#     tensor = torch.tensor(val)
#     avg_tensor = hvd.allreduce(tensor, name=name)
#     return avg_tensor.item()


def run(proc_id, n_gpus, devices, args, kwargs):
    dev_id = devices[proc_id]
    rank = args.nr * n_gpus + proc_id

    world_size = n_gpus * args.nodes

    mnist_train = \
        datasets.MNIST('data-%d' % rank, train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ]))

    if n_gpus > 1 or args.nodes > 1:
        dist_init_method = 'tcp://{master_ip}:{master_port}'.format(
            master_ip=args.master_ip, master_port=args.master_port)
        torch.distributed.init_process_group(backend="nccl",
                                             init_method=dist_init_method,
                                             world_size=world_size,
                                             rank=rank)

    train_dataset, test_dataset = random_split(
        mnist_train, [55000, 5000])

    # use DistributedSampler to partition the training data.
    train_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset, num_replicas=world_size, rank=rank)
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=args.batch_size, sampler=train_sampler, **kwargs)

    # Horovod: use DistributedSampler to partition the test data.
    test_sampler = torch.utils.data.distributed.DistributedSampler(
        test_dataset, num_replicas=world_size, rank=rank)
    test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=args.test_batch_size,
                                              sampler=test_sampler, **kwargs)

    model = Net()
    model = model.to(dev_id)

    if n_gpus > 1 or args.nodes > 1:
        model = DistributedDataParallel(model, device_ids=[dev_id])

    # match ray
    optimizer = optim.Adam(model.parameters(), lr=1e-3)

    # train epoch
    start = time.time()
    for epoch in range(1, args.epochs + 1):
        model.train()
        # Horovod: set epoch to sampler for shuffling.
        i = 0
        for batch_idx, (data, target) in enumerate(train_loader):
            data, target = data.to(dev_id), target.to(dev_id)
            optimizer.zero_grad()
            output = model(data)
            loss = F.nll_loss(output, target)
            loss.backward()
            optimizer.step()
            i += 1
            if batch_idx % args.log_interval == 0 and rank == 0:
                print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(data), len(train_sampler),
                           100. * batch_idx / len(train_sampler), loss.item()))

        if rank == 0:
            print("batch num is {}".format(i))

    # test
    model.eval()
    test_loss = 0.
    test_accuracy = 0.
    for data, target in test_loader:
        data, target = data.to(dev_id), target.to(dev_id)
        output = model(data)
        # sum up batch loss
        test_loss += F.nll_loss(output, target, size_average=False).item()
        # get the index of the max log-probability
        pred = output.data.max(1, keepdim=True)[1]
        test_accuracy += pred.eq(target.data.view_as(pred)).cpu().float().sum()

    test_loss /= len(test_sampler)
    test_accuracy /= len(test_sampler)

    # print first output on first rank
    # TODO how to get all data's accuracy?
    if rank == 0:
        print('\nTest set: Average loss: {:.4f}, Accuracy: {:.2f}%\n'.format(
            test_loss, 100. * test_accuracy))

    print("duration time=", time.time() - start)


if __name__ == '__main__':
    start1 = time.time()
    # Training settings
    parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
    parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                        help='input batch size for training (default: 64)')
    parser.add_argument('--test-batch-size', type=int, default=64, metavar='N',
                        help='input batch size for testing (default: 64)')
    parser.add_argument('--epochs', type=int, default=5, metavar='N',
                        help='number of epochs to train (default: 5)')
    parser.add_argument('--lr', type=float, default=0.001, metavar='LR',
                        help='learning rate (default: 0.001)')
    parser.add_argument('--seed', type=int, default=42, metavar='S',
                        help='random seed (default: 42)')
    parser.add_argument('--log-interval', type=int, default=10, metavar='N',
                        help='how many batches to wait before logging training status')
    parser.add_argument('--nr', type=int, default=0,
                        help="current node's rank")
    parser.add_argument('--gpu', type=str, default='0,1',
                        help="Comma separated list of GPU device IDs.")
    parser.add_argument('--nodes', type=int, default=2,
                        help="number of nodes for training")
    parser.add_argument('--master-ip', type=str, default='10.3.68.117',
                        help="master ip for DDP")
    parser.add_argument('--master-port', type=int, default=12346,
                        help="master port for DDP")
    args = parser.parse_args()

    torch.manual_seed(args.seed)

    devices = list(map(int, args.gpu.split(',')))
    n_gpus = len(devices)

    kwargs = {'num_workers': 1, 'pin_memory': True}

    # mnist_train = \
    #     datasets.MNIST('data-0', train=True, download=True,
    #                    transform=transforms.Compose([
    #                        transforms.ToTensor(),
    #                        transforms.Normalize((0.1307,), (0.3081,))
    #                    ]))

    if n_gpus == 1:
        run(0, n_gpus, devices, args, kwargs)
    else:
        mp.spawn(run, args=(n_gpus, devices, args, kwargs), nprocs=n_gpus)

    print("all time is {} s".format(time.time() - start1))
```

when I use torch 1.6.0, it runs ok. But if I change torch version to 1.7.x, it runs failed with log:
```
(rapids) [root@hikBigDataTestGpu2 torch_ddp_test]# python torch_minist_DDP.py
hikBigDataTestGpu2:1449:1449 [0] NCCL INFO Bootstrap : Using [0]eno4:10.3.68.117<0> [1]vethe94aab9:fe80::a86b:69ff:fe67:e3fe%vethe94aab9<0>
hikBigDataTestGpu2:1449:1449 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hikBigDataTestGpu2:1449:1449 [0] NCCL INFO NET/IB : No device found.
hikBigDataTestGpu2:1449:1449 [0] NCCL INFO NET/Socket : Using [0]eno4:10.3.68.117<0> [1]vethe94aab9:fe80::a86b:69ff:fe67:e3fe%vethe94aab9<0>
hikBigDataTestGpu2:1449:1449 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO Bootstrap : Using [0]eno4:10.3.68.117<0> [1]vethe94aab9:fe80::a86b:69ff:fe67:e3fe%vethe94aab9<0>
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO NET/IB : No device found.
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO NET/Socket : Using [0]eno4:10.3.68.117<0> [1]vethe94aab9:fe80::a86b:69ff:fe67:e3fe%vethe94aab9<0>
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO Using network Socket
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO Setting affinity for GPU 1 to ffff,0000ffff
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Channel 00/02 :    0   1   2   3
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Channel 01/02 :    0   1   2   3
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->2|2->0->1/-1/-1
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Channel 00 : 3[86000] -> 0[3b000] [receive] via NET/Socket/1
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Channel 00 : 0[3b000] -> 1[5e000] via P2P/IPC
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO Channel 00 : 1[5e000] -> 2[5f000] [send] via NET/Socket/1
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO Call to connect returned Connection timed out, retrying
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO Call to connect returned Connection timed out, retrying

hikBigDataTestGpu2:1450:1665 [1] include/socket.h:403 NCCL WARN Connect to fe80::d41d:3bff:fe09:5487%vethe94aab9<55982> failed : Connection timed out
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO transport/net_socket.cc:313 -> 2
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO include/net.h:21 -> 2
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO transport/net.cc:161 -> 2
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO transport.cc:68 -> 2
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO init.cc:766 -> 2
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO init.cc:840 -> 2
hikBigDataTestGpu2:1450:1665 [1] NCCL INFO group.cc:73 -> 2 [Async thread]
Traceback (most recent call last):
  File "torch_minist_DDP.py", line 182, in <module>
    mp.spawn(run, args=(n_gpus, devices, args, kwargs), nprocs=n_gpus)
  File "/root/miniconda3/envs/rapids/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/rapids/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/rapids/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/rapids/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/maqy/torch_ddp_test/torch_minist_DDP.py", line 64, in run
    rank=rank)
  File "/root/miniconda3/envs/rapids/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/root/miniconda3/envs/rapids/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

```

**Comment by robin5540** [comment]
Building 1.7.1 with NCCL 2.4.8 fixed this issue for me.

**Comment by maqy1995** [comment]
> Building 1.7.1 with NCCL 2.4.8 fixed this issue for me.

@robin5540, thanks for your reply.  Compiling PyTorch by source code will be more troublesome, I hope the community can fix this problem in the future. I used Pytorch 1.6.x now, which hasn't this issue.

**Comment by robin5540** [comment]
OMG, I think I know actual problem 🤦 🤣 

```
hikBigDataTestGpu2:1450:1665 [1] include/socket.h:403 NCCL WARN Connect to fe80::d41d:3bff:fe09:5487%vethe94aab9<55982> failed : Connection timed out
```

NCCL 2.7.8 probably had some change in interface selection behavior. It's trying to connect to another node via a virtual interface, that probably only serves local traffic. You can try setting `NCCL_SOCKET_IFNAME= eno4`.

2.4.8 probably just picks the first one, maybe 2.7.8 prefers IPv6? (Someone tag some NCCL folks here?)

https://docs.nvidia.com/deeplearning/nccl/archives/nccl_278/user-guide/docs/env.html#nccl-socket-ifname

**Comment by maqy1995** [comment]
> NCCL 2.7.8 probably had some change in interface selection behavior. It's trying to connect to another node via a virtual interface, that probably only serves local traffic. You can try setting `NCCL_SOCKET_IFNAME=eno4`.

I'm not sure if this is the problem, because there are some info about `eno4`:
```
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO Bootstrap : Using [0]*eno4*:10.3.68.117<0> [1]vethe94aab9:fe80::a86b:69ff:fe67:e3fe%vethe94aab9<0>
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO NET/IB : No device found.
hikBigDataTestGpu2:1450:1450 [1] NCCL INFO NET/Socket : Using [0] *eno4* :10.3.68.117<0> [1]vethe94aab9:fe80::a86b:69ff:fe67:e3fe%vethe94aab9<0>
```
And I tried to set `NCCL_SOCKET_IFNAME` to `eno4`, but the problem still exists in pytorch 1.7.

**Comment by robin5540** [comment]
@maqy1995 weird. I ran in to a similar issue, something something a box with multiple interfaces and networks. When I specified interface NCCL only printed the one I specified, and all the vethe ones disappeared.

Also, it looks like your two GPUs are on the same box. Why isn't NCCL using shared memory or IPC?

**Comment by maqy1995** [comment]
> @maqy1995 weird. I ran in to a similar issue, something something a box with multiple interfaces and networks. When I specified the interface env var, NCCL only printed the one I specified, and all the vethe ones disappeared.
> 
> Also, it looks like your two GPUs are on the same box. Why isn't NCCL using shared memory or IPC?

@robin5540, after I set `NCCL_SOCKET_IFNAME = eno4`, the information printed by NCCL is the same as you described, no vethe info is printed.( The printed information in my last reply was copied from my comment in 2021.01.23)

In my environment, I use two nodes to run ddp, which nodes have two gpus, maybe this is the reason why NCCL printed info has both P2P/IPC and NET/Socket like this:
```
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Channel 00 : 3[86000] -> 0[3b000] [receive] via NET/Socket/1
hikBigDataTestGpu2:1449:1663 [0] NCCL INFO Channel 00 : 0[3b000] -> 1[5e000] via P2P/IPC
```

**Comment by robin5540** [comment]
@maqy1995 i see. Did you set `NCCL_SOCKET_IFNAME` on one of the nodes or both?

I think the problem is cause by the peer providing a local-only address. If you set `NCCL_SOCKET_IFNAME` on both nodes to use your `10/` network, the problem may be solved?
```
hikBigDataTestGpu2:1450:1665 [1] include/socket.h:403 NCCL WARN Connect to fe80::d41d:3bff:fe09:5487%vethe94aab9<55982> failed : Connection timed out
```

**Comment by maqy1995** [comment]
I set `NCCL_SOCKET_IFNAME` on both nodes, but unfortunately, this issue has not been resolved.

**Comment by maqy1995** [comment]
I try to use **pytorch1.8.0**, but there are some other issues:
```
(base) [root@hikBigDataTestGpu2 torch_ddp_test]# python torch_minist_DDP.py
hikBigDataTestGpu2:29177:29177 [0] NCCL INFO Bootstrap : Using [0]eno4:10.3.68.117<0>
hikBigDataTestGpu2:29177:29177 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hikBigDataTestGpu2:29177:29177 [0] NCCL INFO NET/IB : No device found.
hikBigDataTestGpu2:29177:29177 [0] NCCL INFO NET/Socket : Using [0]eno4:10.3.68.117<0>
hikBigDataTestGpu2:29177:29177 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
hikBigDataTestGpu2:29178:29178 [1] NCCL INFO Bootstrap : Using [0]eno4:10.3.68.117<0>
hikBigDataTestGpu2:29178:29178 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hikBigDataTestGpu2:29178:29178 [1] NCCL INFO NET/IB : No device found.
hikBigDataTestGpu2:29178:29178 [1] NCCL INFO NET/Socket : Using [0]eno4:10.3.68.117<0>
hikBigDataTestGpu2:29178:29178 [1] NCCL INFO Using network Socket
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 00/02 :    0   1   2   3
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 01/02 :    0   1   2   3
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Setting affinity for GPU 1 to ffff,0000ffff
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->3|3->0->1/-1/-1
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 00 : 3[5e000] -> 0[3b000] [receive] via NET/Socket/0
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Channel 00 : 1[5e000] -> 2[3b000] [send] via NET/Socket/0
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 00 : 0[3b000] -> 1[5e000] via P2P/IPC
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Channel 00 : 2[3b000] -> 1[5e000] [receive] via NET/Socket/0
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Channel 00 : 1[5e000] -> 0[3b000] via P2P/IPC
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 01 : 3[5e000] -> 0[3b000] [receive] via NET/Socket/0
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Channel 01 : 1[5e000] -> 2[3b000] [send] via NET/Socket/0
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 01 : 0[3b000] -> 1[5e000] via P2P/IPC
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO Channel 01 : 1[5e000] -> 0[3b000] via P2P/IPC
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
hikBigDataTestGpu2:29178:29419 [1] NCCL INFO comm 0x7f7ba0000e00 rank 1 nranks 4 cudaDev 1 busId 5e000 - Init COMPLETE
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO Channel 01 : 0[3b000] -> 3[5e000] [send] via NET/Socket/0
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
hikBigDataTestGpu2:29177:29418 [0] NCCL INFO comm 0x7f5a20000e00 rank 0 nranks 4 cudaDev 0 busId 3b000 - Init COMPLETE
hikBigDataTestGpu2:29177:29177 [0] NCCL INFO Launch mode Parallel
Traceback (most recent call last):
  File "torch_minist_DDP.py", line 182, in <module>
    mp.spawn(run, args=(n_gpus, devices, args, kwargs), nprocs=n_gpus)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/maqy/torch_ddp_test/torch_minist_DDP.py", line 99, in run
    output = model(data)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maqy/torch_ddp_test/torch_minist_DDP.py", line 30, in forward
    x = F.relu(F.max_pool2d(self.conv1(x), 2))
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

```

**Comment by RuABraun** [comment]
I'm getting this with pytorch 1.10.1, any hints on how to debug
