### ISSUE TITLE
test_custom_batch_pin_worker fails on Windows with coverage

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#50661]
## 🐛 Bug

Met when testing https://github.com/pytorch/pytorch/pull/50660. It seems that the test cannot pass when running in coverage mode.
Main process
```pytb
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 422, in wrapper
    fn(*args, **kwargs)
  File "test_dataloader.py", line 2160, in test_custom_batch_pin_worker
    for sample in loader:
  File "C:\Users\circleci\project\build\win_tmp\build\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\circleci\project\build\win_tmp\build\torch\utils\data\dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "C:\Users\circleci\project\build\win_tmp\build\torch\utils\data\dataloader.py", line 1143, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
```
Child process:
```pytb
Traceback (most recent call last):
  File "c:\jenkins\miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\jenkins\miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\utils\data\_utils\pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "c:\jenkins\miniconda3\lib\multiprocessing\queues.py", line 113, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'SimpleCustomBatch' on <module '__main__' from 'C:\\Jenkins\\Miniconda3\\Scripts\\coverage.exe\\__main__.py'>
```
See https://app.circleci.com/pipelines/github/pytorch/pytorch/261028/workflows/ce92c13a-17bb-484f-bd2e-9ff5aa03840c/jobs/10212393

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mszhanyi** [comment]
@peterjc123 is coverage mode the interactive mode?
For python interactive mode on windows, the main module in newly spawned process is empty module.

**Comment by peterjc123** [comment]
@mszhanyi https://github.com/nedbat/coveragepy/blob/master/__main__.py#L11 It spawns the module using `runpy.run_module`.
