### ISSUE TITLE
Launching two processes causes hanging

### ISSUE THREAD

**Issue by rafi-cohen** [pytorch/pytorch#50669]
## 🐛 Bug

Launching two processes causes hanging.

## To Reproduce

1. Run the following Python code:
```python
from torch import multiprocessing as mp
from torchvision.models import resnet50


def main():
    model = resnet50()

    copy1 = [p.clone() for p in model.parameters()]
    copy2 = [p.clone() for p in model.parameters()]

    processes = []
    for rank in range(2):
        process = mp.Process(target=run_worker, args=(rank,))
        process.start()
        processes.append(process)

    for p in processes:
        p.join()


def run_worker(rank):
    print(f'Started Worker {rank}')
    model = resnet50()
    print('Does get here')
    local_copy = [p.clone() for p in model.parameters()]
    print('And should also get here')


if __name__ == "__main__":
    main()
```
2. Wait a while and see that it hangs
3. Press `ctrl-c` to stop execution once you're convinced it hung

## Expected behavior

Each process should print `f'Started Worker {rank}'`, `'Does get here'`, `'And should also get here'`, and finally quit. The program should end successfully.

## Actual behavior
Each process prints `f'Started Worker {rank}'` and `'Does get here'`, but does not print `'And should also get here'`. After `ctrl-c`, the two subprocesses remain alive.

## Environment

Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect (CUDA Version 10.2.89, checked manually using the `/usr/local/cuda/version.txt` file)
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.8.2                py38_cu102    pytorch

## Additional context

One thing I don't quite understand is that omitting lines 8-9, where `copy1` and `copy2` are defined, somehow prevents the bug from occurring. This is despite the fact that they aren't actually used anywhere in the code. However, in my real scenario, `copy1` and `copy2` are used before launching the two processes, and their memory is shared between them. Each process reads from and writes to this shared memory. So removing those lines isn't a feasible solution.

Also, this code works on my Windows computer (same Python and PyTorch versions), and it also worked on a friends Linux computer (not sure about their environment). This led me to think I might have some environment issues, but the issue persists even after completely reinstalling Conda, Python, and PyTorch (and nothing else). Another thing I tried is checking different versions of PyTorch. The issue persisted on versions 1.8.0, 1.6.0, 1.5.1, but did not occur on version 1.4.0.

**Comment by imaginary-person** [comment]
This is an open issue in PyTorch, which, in turn, is caused by a known limitation of OpenMP.
If an OpenMP thread pool exists in a process before `fork()`, then in PyTorch, a deadlock occurs upon `fork()`.
As per https://bisqwit.iki.fi/story/howto/openmp/#OpenmpAndFork,
> _After OpenMP features are utilized, a fork is only allowed if the child process does not use OpenMP features, or it does so as a completely new process (such as after exec())_

There are two workarounds, of which you can probably use the first one, before this issue is fixed in the source code:
1. Use `spawn() `instead of `fork()`.
`spawn()` is a bit slower than `fork()` but avoids the issue.
Simply add  `mp.set_start_method('spawn')` at the start of your program.
This workaround is probably better for your program.

2. If you also need to import torch for some reason, there's another workaround as well.
By default, Torch's OpenMP implementation uses as many threads as the number of physical cores on a machine.
So, if your code used any OpenMP operations under the hood, use `torch.set_num_threads(1)` before forking.  
However, after forking, you can set the number of OpenMP threads to another value as well.

Source: https://github.com/pytorch/pytorch/issues/17199#issuecomment-465313245

**Comment by rafi-cohen** [comment]
Thank you, both workarounds seem to work for this example.
However, with my real code, only the second workaround works. Using `spawn()` instead of `fork()` fails with the following error:
```
Traceback (most recent call last):
  File "/path/to/file.py", line 26, in <module>
    main()
  File "/path/to/file.py", line 14, in main
    process.start()
  File "/path/to/env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/path/to/env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/path/to/env/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/path/to/env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/path/to/env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/path/to/env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/path/to/env/lib/python3.8/multiprocessing/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
ValueError: bad value(s) in fds_to_keep

Process finished with exit code 1
```

Here is a minimal example reproducing this:
```python
from torch import multiprocessing as mp
from torchvision.models import resnet50


def main():
    mp.set_start_method('spawn')
    model = resnet50()
    model.share_memory()
    shared_parameters = [p.data for p in model.parameters()]

    processes = []
    for _ in range(2):
        process = mp.Process(target=run_worker, args=(model, shared_parameters))
        process.start()
        processes.append(process)

    for p in processes:
        p.join()


def run_worker(*args, **kwargs):
    pass


if __name__ == "__main__":
    main()
```

It seems related to https://github.com/pytorch/pytorch/issues/31571?

**Comment by imaginary-person** [comment]
> Thank you, both workarounds seem to work for this example.
> However, with my real code, only the second workaround works. Using `spawn()` instead of `fork()` fails with the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/path/to/file.py", line 26, in <module>
>     main()
>   File "/path/to/file.py", line 14, in main
>     process.start()
>   File "/path/to/env/lib/python3.8/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/path/to/env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "/path/to/env/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/path/to/env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/path/to/env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/path/to/env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 58, in _launch
>     self.pid = util.spawnv_passfds(spawn.get_executable(),
>   File "/path/to/env/lib/python3.8/multiprocessing/util.py", line 452, in spawnv_passfds
>     return _posixsubprocess.fork_exec(
> ValueError: bad value(s) in fds_to_keep
> 
> Process finished with exit code 1
> ```
> 
> Here is a minimal example reproducing this:
> 
> ```python
> from torch import multiprocessing as mp
> from torchvision.models import resnet50
> 
> 
> def main():
>     mp.set_start_method('spawn')
>     model = resnet50()
>     model.share_memory()
>     shared_parameters = [p.data for p in model.parameters()]
> 
>     processes = []
>     for _ in range(2):
>         process = mp.Process(target=run_worker, args=(model, shared_parameters))
>         process.start()
>         processes.append(process)
> 
>     for p in processes:
>         p.join()
> 
> 
> def run_worker(*args, **kwargs):
>     pass
> 
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> It seems related to #31571?

In this example, shared memory is not being set up properly.
Please refer to [this discussion](https://github.com/pytorch/pytorch/issues/35858#issuecomment-611170163) for a solution.

**Comment by rafi-cohen** [comment]
Thank you for your response,

> In this example, shared memory is not being set up properly if `spawn()` is used.

I'm not sure that shared memory is the issue here. Omitting the `model.share_memory()` line results in the same error. Even replacing 
```python
    model = resnet50()
    model.share_memory()
    shared_parameters = [p.data for p in model.parameters()]
```
with
```python
    t1 = torch.ones((224, 224, 3))
    t2 = t1.data
```
gives that error. (obviously, in this case you'd also need to `import torch` and pass `args=(t1, t2)` to each `Process`).
I do believe this is related to the issue I linked to earlier.

> Please refer to [this discussion](https://github.com/pytorch/pytorch/issues/35858#issuecomment-611170163) for a solution.

I read that thread, but notice that I'm not using DDP, so I'm not sure if this is relevant in my case.
Using `deepcopy` is not an option for me, since I need the two processes to access the same copy of the parameters.
And the `Queue` solution feels like a hacky workaround. Why would passing arguments directly using `args` fail where passing them through a `Queue` works?
I tried it anyway, but it didn't work either. Changing the code to:
```python
from torch import multiprocessing as mp
from torchvision.models import resnet50


def main():
    mp.set_start_method('spawn')
    model = resnet50()
    model.share_memory()
    shared_parameters = [p.data for p in model.parameters()]
    queue = mp.Queue()
    args = (model, shared_parameters)
    queue.put(args)
    queue.put(args)
    processes = []
    for _ in range(2):
        process = mp.Process(target=run_worker, args=(queue,))
        process.start()
        processes.append(process)

    for p in processes:
        p.join()


def run_worker(queue, *args, **kwargs):
    args = queue.get()


if __name__ == "__main__":
    main()
```
I get the following error:
```
Traceback (most recent call last):
  File "/path/to/file.py", line 29, in <module>
  File "/path/to/file.py", line 17, in main
  File "/path/to/env/lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/path/to/env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
  File "/path/to/env/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
  File "/path/to/env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
OSError: [Errno 24] Too many open files: '/path/to/env/lib/python3.8/multiprocessing/popen_fork.py'
Traceback (most recent call last):
  File "/path/to/env/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/path/to/env/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/path/to/env/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
  File "/path/to/env/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/path/to/env/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/path/to/env/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/path/to/env/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/path/to/env/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/path/to/env/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/path/to/env/lib/python3.8/shutil.py", line 628, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/path/to/env/lib/python3.8/shutil.py", line 624, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
OSError: [Errno 24] Too many open files: '/tmp/pymp-aubnbcrb'

Process finished with exit code 1
```

**Comment by imaginary-person** [comment]
Hello Rafi,

The [discussion](https://github.com/pytorch/pytorch/issues/35858#issuecomment-611170163) I referred to is indeed relevant here to the example code you posted today and on Jan 19.

The example you provided today would run properly if you would set 
`mp.set_sharing_strategy('file_system')`

From the [Sharing Strategies section of the PyTorch documentation on MultiProcessing](https://pytorch.org/docs/stable/multiprocessing.html#sharing-strategies):
_Note that if there will be a lot of tensors shared, this strategy will keep a large number of file descriptors open most of the time. If your system has low limits for the number of open file descriptors, and you can’t raise them, you should use the file_system strategy._

**Comment by rafi-cohen** [comment]
> The example you posted today would run properly if you would set
> `mp.set_sharing_strategy('file_system')`

Thank you, this indeed worked. This also allowed me to pass the arguments directly, without the need to use a `Queue` at all.
I'm still a bit puzzled, though. Recall one of my previous examples:
> Even replacing
> 
> ```python
>     model = resnet50()
>     model.share_memory()
>     shared_parameters = [p.data for p in model.parameters()]
> ```
> 
> with
> 
> ```python
>     t1 = torch.ones((224, 224, 3))
>     t2 = t1.data
> ```
> 
> gives that error. (obviously, in this case you'd also need to `import torch` and pass `args=(t1, t2)` to each `Process`).

As I just mentioned, adding `mp.set_sharing_strategy('file_system')` fixed the `ValueError: bad value(s) in fds_to_keep` I was getting.
Using `ulimit -n`, I see that the maximum number of open file descriptors in my system is 1024. Does PyTorch actually use that many file descriptors to pass just two tensors? If not, then why does setting the sharing strategy to `file_system` fix that?

> _it seems like args can handle memory space between the parent process and one child process correctly, but would fail if there are multiple children processes. Using multiprocessing.Queue worked in this case._

Is this a limitation that is planned to be fixed? Having to pass arguments through a `Queue` isn't ideal, and not always possible.
For example, `Lock`, or other synchronized objects, cannot be passed through a `Queue`. Trying to do so will result in `Runtime Error: Lock objects should only be shared between processes through inheritance`. This means you could have a troublesome object that contains a `Lock`, that would be impossible to pass through a `Queue`, and neither through a `Process`'s `args`.

**Comment by imaginary-person** [comment]
Hello @rafi-cohen, please note that there's a difference between those two errors: `the bad values in fds_to_keep` and the `Too many open files`. Only the former is related to #31571, and not the latter, which is  [a conscious design decision](https://github.com/pytorch/pytorch/wiki/Multiprocessing-Technical-Notes).

In the following example, you get a `ValueError: bad value(s) in fds_to_keep`. It doesn't mean that there are too many FDs, which is a different error.
```
    t1 = torch.ones((224, 224, 3))
    t2 = t1.data
```
As for the ValueError issue, I've explained it below. Since it's quite verbose, please feel free to skip it if it's irrelevant to you now.
As for passing objects that have a lock, perhaps @ngimel or someone else from the PyTorch team can help.

### `ValueError: bad value(s) in fds_to_keep`
This particular error is due to bugs in both PyTorch's multiprocessing module & Python's.
I think that the PyTorch team is already aware of it because  #31571 had been triaged,
so it seems like they decided it's not worth fixing.
You can use a workaround, though.


Basically, in the above example, with the shared memory approach on CPU (not CUDA, which uses the filesystem approach), only one FD is used for sharing both the tensors.

While trying to spawn another process on Linux, if multiple tensors share the same file descriptor (with the shared-memory approach), the PyTorch multiprocessing module calls `DupFd` on the same FD multiple times:
https://github.com/pytorch/pytorch/blob/fcf8b712348f21634044a5d76a69a59727756357/torch/multiprocessing/reductions.py#L322

However, Python's multiprocessing module is still buggy and while spawing, it duplicates an FD on which `DupFd` is called to a list of FDs that are to be shared with a child process:
https://github.com/python/cpython/blob/5f18c223391eef8c7d01241b51a7b2429609dd84/Lib/multiprocessing/reduction.py#L195

This list is then used in `spawnv_passfds()` in a call to `_posixsubprocess.fork_exec()`:
https://github.com/python/cpython/blob/5f18c223391eef8c7d01241b51a7b2429609dd84/Lib/multiprocessing/util.py#L452

In `_posixsubprocess.c`, checks exist to ensure that all the FDs in the list are unique, positive, and in a sorted order.
If duplicate entries are found, a `ValueError: bad value(s) in fds_to_keep exception is raised`, and the execution is terminated.

From Python's perspective, there's a simple fix, for which I've raised a [PR](https://github.com/python/cpython/pull/24461), but  PyTorch still needs to handle this issue at its end. 

You can even apply that fix locally if you've write access to the Python libs on your system, but it won't help.
Even after applying the Python fix, in this particular example, PyTorch would try to `close` one FD twice, which would raise an exception. It'd also try to `stat` it after having closed it, which would raise another exception. I haven't gone through enough of the code to know what exactly happens when in PyTorch's multiprocessing module, so I don't know what else is broken in the handling of examples such as the one above & the one listed in #31571, but I believe it's broken & it seems that it was decided not to fix this issue.

**Comment by kracon7** [comment]
Hi @imaginary-person and @rafi-cohen 
Could you please elaborate more on this?

> Another alternative is to do a custom build from source & use ICC OpenMP instead of libgomp (which is used by default), since Intel's OpenMP doesn't have this issue.

I'm not sure how should I implement this option. Thanks a lot!!

**Comment by imaginary-person** [comment]
> > Another alternative is to do a custom build from source & use ICC OpenMP instead of libgomp (which is used by default), since Intel's OpenMP doesn't have this issue.

Hello @kracon7, you don't really need to build from source with ICC, and can simply link PyTorch with Intel OpenMP at run-time by using `LD_PRELOAD`.

Intel MKL uses Intel OpenMP, so I believe it also installs libiomp5.so. So, if you installed MKL (`apt-get install libmkl-dev` on Ubuntu), then you'd probably have `libiomp5.so` in `/usr/lib/x86_64-linux-gnu`.

You can use the environment variable `LD_PRELOAD` to link OpenMP at run-time.
eg. `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libiomp5.so`.

**Comment by taras-janea** [comment]
Closing this issue due to inactivity. If you continue to experience this problem or have any related concerns, please don't hesitate to open a new issue.
