### ISSUE TITLE
[PyTorch Mobile] NNAPI prototype installer no longer available

### ISSUE THREAD

**Issue by windmaple** [pytorch/pytorch#50678]
## To Reproduce

On this page, 'pip install --upgrade --pre --find-links https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html torch==1.8.0.dev20201106+cpu torchvision==0.9.0.dev20201107+cpu' the packages are no longer available. If I use 'torch==1.8.0.dev20201120 torchvision==0.9.0.dev20201120', I got the following

Traceback (most recent call last):
  File "nnapi.py", line 101, in <module>
    make_mobilenetv2_nnapi(Path(os.environ["HOME"]) / "mobilenetv2-nnapi", quantize_mode)
  File "nnapi.py", line 67, in make_mobilenetv2_nnapi
    nnapi_model = torch.backends._nnapi.prepare.convert_model_to_nnapi(traced, input_tensor)
  File "/Users/wind/miniconda2/envs/experimental/lib/python3.7/site-packages/torch/backends/_nnapi/prepare.py", line 169, in convert_model_to_nnapi
    ser_model, used_weights, inp_mem_fmts, out_mem_fmts = serialize_model(model, inputs)
  File "/Users/wind/miniconda2/envs/experimental/lib/python3.7/site-packages/torch/backends/_nnapi/serializer.py", line 1363, in serialize_model
    return _NnapiSerializer(config).serialize_model(module, inputs)
  File "/Users/wind/miniconda2/envs/experimental/lib/python3.7/site-packages/torch/backends/_nnapi/serializer.py", line 520, in serialize_model
    self.add_node(node)
  File "/Users/wind/miniconda2/envs/experimental/lib/python3.7/site-packages/torch/backends/_nnapi/serializer.py", line 641, in add_node
    raise Exception("Unsupported node kind (%r) in node %r" % (node.kind(), node))
Exception: Unsupported node kind ('aten::size') in node %13 : int = aten::size(%input.88, %32) # /Users/wind/miniconda2/envs/experimental/lib/python3.7/site-packages/torchvision/models/mobilenet.py:185:0

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.8.0.dev20201120
 - OS (e.g., Linux): Mac
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ValerianGonnot** [comment]
This is the same issue as #50533
