### ISSUE TITLE
distributed/rpc/test_tensorpipe_agent test_device_maps_return_to_gpu_self fails

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#50671]
## 🐛 Bug

`distributed/rpc/test_tensorpipe_agent.test_device_maps_return_to_gpu_self` fails

This was originally detected on a V100 x4 system a few days ago. When I tried that on my 2 GPU system, I also got a failure but with different error message.

## To Reproduce

```bash
python test/run_test.py -i distributed/rpc/test_tensorpipe_agent -- -v -k test_device_maps_return_to_gpu_self
```

Error message on V100x4 (latest master commit, test is started by `python test/run_test.py`)

```
======================================================================
ERROR [12.860s]: test_device_maps_return_to_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6
```

Error message on my 2 GPU system

```
$ python test/run_test.py -i distributed/rpc/test_tensorpipe_agent -- -v -k test_device_maps_return_to_gpu_self
Running distributed/rpc/test_tensorpipe_agent ... [2021-01-17 13:46:22.387855]
Executing ['/usr/bin/python', 'distributed/rpc/test_tensorpipe_agent.py', '-v', '-k', 'test_device_maps_return_to_gpu_self'] ... [2021-01-17 13:46:22.387905]
Traceback (most recent call last):
  File "/home/xwang/Developer/pytorch/test/distributed/rpc/test_tensorpipe_agent.py", line 7, in <module>
    from torch.testing._internal.distributed.rpc_utils import (
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/distributed/rpc_utils.py", line 33, in <module>
    from torch.testing._internal.distributed.rpc.jit.rpc_test import JitRpcTest
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 144, in <module>
    def script_add_ones_with_record_function(x, block: str):
  File "/home/xwang/Developer/pytorch/torch/jit/_script.py", line 979, in script
    fn = torch._C._jit_script_compile(
  File "/home/xwang/Developer/pytorch/torch/jit/annotations.py", line 337, in try_ann_to_type
    torch.jit._script._recursive_compile_class(ann, loc)
  File "/home/xwang/Developer/pytorch/torch/jit/_script.py", line 1095, in _recursive_compile_class
    rcb = _jit_internal.createResolutionCallbackForClassMethods(obj)
  File "/home/xwang/Developer/pytorch/torch/_jit_internal.py", line 333, in createResolutionCallbackForClassMethods
    captures.update(get_type_hint_captures(fn))
  File "/home/xwang/Developer/pytorch/torch/_jit_internal.py", line 293, in get_type_hint_captures
    arg_annotation_str = get_annotation_str(arg.annotation) if arg.annotation else None
  File "/home/xwang/Developer/pytorch/torch/_jit_internal.py", line 241, in get_annotation_str
    return f"{get_annotation_str(annotation.value)}[{get_annotation_str(annotation.slice.value)}]"  # type: ignore
AttributeError: 'Name' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/xwang/Developer/pytorch/test/run_test.py", line 911, in <module>
    main()
  File "/home/xwang/Developer/pytorch/test/run_test.py", line 890, in main
    raise RuntimeError(err_message)
RuntimeError: distributed/rpc/test_tensorpipe_agent failed!
```

## Expected behavior

No fail

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+0ea1abe
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce GTX 1070 Ti

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0a0
[conda] Could not collect
```

## Additional context

https://github.com/pytorch/pytorch/pull/44418 might be related.

Also, I found the test has a decorator `@skip_if_lt_x_gpu(4)`, but it still "sort of " failed on my 2 GPU system.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @ptrblck

**Comment by xwang233** [comment]
Seeing more failures on different machines: 2x A100 and 4x V100 (2 machines)

Nightly built at 1.8.0a0+ 4511f2c

<details><summary> very long logs </summary>
<p>

```
Running tests...
----------------------------------------------------------------------
  test_ddp_dist_autograd_local_vs_remote_gpu (__main__.TensorPipeDdpComparisonTestWithSpawn) ... OK (6.639s)
  test_gpu_simple (__main__.TensorPipeDistAutogradTestWithSpawn) ... OK (3.939s)
  test_gpu_to_cpu_continuation (__main__.TensorPipeDistAutogradTestWithSpawn) ... OK (4.650s)
  test_gpu_to_cpu_continuation_gpu_root (__main__.TensorPipeDistAutogradTestWithSpawn) ... OK (3.838s)
  test_basic_nccl_ckpt_always (__main__.TensorPipePipeWithDDPTestWithSpawn) ... SKIP (0.000s)
  test_basic_nccl_ckpt_except_last (__main__.TensorPipePipeWithDDPTestWithSpawn) ... SKIP (0.000s)
  test_basic_nccl_ckpt_never (__main__.TensorPipePipeWithDDPTestWithSpawn) ... OK (7.240s)
  test_basic_nccl_ckpt_never_find_unused (__main__.TensorPipePipeWithDDPTestWithSpawn) ... OK (7.138s)
  test_profiler_remote_cuda (__main__.TensorPipeRpcTestWithSpawn) ... OK (13.475s)
  test_device_map_gpu_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (5.440s)
  test_device_map_gpu_default_to_non_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (5.243s)
  test_device_map_gpu_mixed_1 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (100.067s)
  test_device_map_gpu_mixed_2 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (100.200s)
  test_device_map_gpu_mixed_3 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (14.761s)
  test_device_map_gpu_mixed_4 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (100.169s)
  test_device_map_gpu_mixed_5 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (16.586s)
  test_device_map_gpu_mixed_6 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (15.880s)
  test_device_map_gpu_mixed_7 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (15.884s)
  test_device_map_gpu_mixed_8 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (100.187s)
  test_device_map_gpu_mixed_self_1 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.453s)
  test_device_map_gpu_mixed_self_2 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (8.255s)
  test_device_map_gpu_mixed_self_3 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (9.062s)
  test_device_map_gpu_mixed_self_4 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.644s)
  test_device_map_gpu_mixed_self_5 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.445s)
  test_device_map_gpu_mixed_self_6 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.347s)
  test_device_map_gpu_mixed_self_7 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.448s)
  test_device_map_gpu_mixed_self_8 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.948s)
  test_device_map_gpu_non_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (100.121s)
  test_device_map_gpu_non_default_to_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR (7.143s)
  test_device_maps_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (5.140s)
  test_device_maps_multi_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.453s)
  test_device_maps_multi_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (7.446s)
  test_device_maps_return_to_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (12.459s)
  test_device_maps_return_to_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... FAIL (12.894s)

======================================================================
ERROR [5.440s]: test_device_map_gpu_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [5.243s]: test_device_map_gpu_default_to_non_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [100.067s]: test_device_map_gpu_mixed_1 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 458, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 1 terminated or timed out after 100.02399039268494 seconds

======================================================================
ERROR [100.200s]: test_device_map_gpu_mixed_2 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 458, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 2 terminated or timed out after 100.01017475128174 seconds

======================================================================
ERROR [14.761s]: test_device_map_gpu_mixed_3 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [100.169s]: test_device_map_gpu_mixed_4 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 458, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 2 terminated or timed out after 100.07772183418274 seconds

======================================================================
ERROR [16.586s]: test_device_map_gpu_mixed_5 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 453, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Processes 2 exited with error code 10

======================================================================
ERROR [15.880s]: test_device_map_gpu_mixed_6 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 453, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Processes 1 exited with error code 10

======================================================================
ERROR [15.884s]: test_device_map_gpu_mixed_7 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 453, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Processes 2 exited with error code 10

======================================================================
ERROR [100.187s]: test_device_map_gpu_mixed_8 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 458, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 2 terminated or timed out after 100.04805278778076 seconds

======================================================================
ERROR [7.453s]: test_device_map_gpu_mixed_self_1 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [8.255s]: test_device_map_gpu_mixed_self_2 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [9.062s]: test_device_map_gpu_mixed_self_3 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.644s]: test_device_map_gpu_mixed_self_4 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.445s]: test_device_map_gpu_mixed_self_5 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.347s]: test_device_map_gpu_mixed_self_6 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.448s]: test_device_map_gpu_mixed_self_7 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.948s]: test_device_map_gpu_mixed_self_8 (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [100.121s]: test_device_map_gpu_non_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 458, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 2 terminated or timed out after 100.09047436714172 seconds

======================================================================
ERROR [7.143s]: test_device_map_gpu_non_default_to_default (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 453, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Processes 2 exited with error code 10

======================================================================
ERROR [5.140s]: test_device_maps_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.453s]: test_device_maps_multi_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [7.446s]: test_device_maps_multi_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [12.459s]: test_device_maps_return_to_gpu (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

======================================================================
ERROR [12.894s]: test_device_maps_return_to_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 469, in _check_return_codes
    self.assertEqual(
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6

----------------------------------------------------------------------
Ran 34 tests in 736.599s

FAILED (errors=25, skipped=2)

Generating XML reports...
Test results will be stored in test-reports/dist-gloo
Timing out after 100 seconds and killing subprocesses.
Timing out after 100 seconds and killing subprocesses.
Timing out after 100 seconds and killing subprocesses.
Process 2 terminated with exit code 10, terminating remaining processes.
Process 1 terminated with exit code 10, terminating remaining processes.
Process 2 terminated with exit code 10, terminating remaining processes.
Timing out after 100 seconds and killing subprocesses.
Timing out after 100 seconds and killing subprocesses.
Process 2 terminated with exit code 10, terminating remaining processes.
distributed/rpc/test_tensorpipe_agent failed!
```

</p>
</details>

**Comment by mrshenli** [comment]
hey @xwang233, TensorPipe's CUDA support is in progress, and is not in a stable state yet. We are actively working on that. Will let you know when it's ready. Thanks for reporting this!

**Comment by mrshenli** [comment]
this issue no longer occurs on master, closing. #53287 tracks `test_device_maps_gpu`, and the fix will be landed soon.
