### ISSUE TITLE
`test_fn_grad_acosh_cuda_complex128 - TestGradientsCUDA` fails on `windows_vs2019_py36_cuda10.1`

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#50692]
Following up on the gradcheck test failure for `torch.cosh` from https://github.com/pytorch/pytorch/pull/50387
https://app.circleci.com/pipelines/github/pytorch/pytorch/261091/workflows/319caa42-c585-421c-b21f-32a502638e2c/jobs/10216581
```

Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 286, in instantiated_test
    raise rte
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 281, in instantiated_test
    result = test_fn(self, *args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 255, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 119, in test_fn_grad
    self._grad_test_helper(device, dtype, op, op.get_op())
  File "test_ops.py", line 106, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck')
  File "test_ops.py", line 94, in _check_helper
    check_grad_dtypes=True))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\autograd\gradcheck.py", line 381, in gradcheck
    "Gradients failed to compare equal for grad output = 1j. ")
  File "C:\Users\circleci\project\build\win_tmp\build\torch\autograd\gradcheck.py", line 370, in checkIfNumericalAnalyticAreClose
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\autograd\gradcheck.py", line 287, in fail_test
    raise RuntimeError(msg)
RuntimeError: Gradients failed to compare equal for grad output = 1j. Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-2.5771e-02+0.1099j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  1.2735e-01+0.1064j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j, -7.6532e+05-0.0515j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
         -1.3490e+06+0.1241j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j, -6.1856e+05+0.0505j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j, -1.1579e+06-0.1131j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          1.0484e+06+0.0913j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j, -1.2854e-01-0.0386j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  9.9856e+05-0.1089j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
         -4.3169e-02+0.0922j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j, -5.7707e+05+0.2326j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j, -7.2790e+05+0.0543j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
         -1.1915e+06+0.2744j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j, -9.2353e+05+0.1120j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j, -3.7270e-01+0.3160j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          1.2642e-01-0.0298j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  1.2440e+06+0.1352j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j, -1.4538e+06-0.1133j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          9.4520e-02+0.0271j,  0.0000e+00+0.0000j],
        [ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  0.0000e+00+0.0000j,
          0.0000e+00+0.0000j, -1.7523e-01+0.0542j]], device='cuda:0')
analytical:tensor([[-0.0258+0.1099j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j, -0.1274+0.1064j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j, -0.0538+0.0515j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -0.0282+0.1241j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
         -0.0713+0.0505j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j, -0.0499+0.1131j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j, -0.0529+0.0913j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -0.1285+0.0386j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
         -0.0707+0.1089j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j, -0.0432+0.0922j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j, -0.3997+0.2326j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -0.0612+0.0543j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
         -0.1142+0.2744j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j, -0.0855+0.1120j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j, -0.3727+0.3160j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -0.1264+0.0298j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
         -0.0463+0.1352j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j, -0.0134+0.1133j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j, -0.0945+0.0271j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -0.1752+0.0542j]],
       device='cuda:0')
```

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @mruberry @VitalyFedyunin @walterddr @ezyang @anjali411 @dylanbespalko @Lezcano @nikitaved @maxluk @guyang3532 @gunandrose4u

**Comment by albanD** [comment]
The difference seems quite big here, could it be that we actually gradcheck at a point where the function is not differentiable?

Note that the acos test is failing similarly and is similarly disabled.

**Comment by mruberry** [comment]
> The difference seems quite big here, could it be that we actually gradcheck at a point where the function is not differentiable?
> 
> Note that the acos test is failing similarly and is similarly disabled.

That's possible but it seems unlikely. Currently we generate values within the function's domain and we bound away from the edges of the domain by 1e-5. So we could generate 1+1e-5 as input to acosh. But I think we also verify that if given an input outside its domain (like a value < 1) then acosh returns NaN.

**Comment by albanD** [comment]
I think the problem is with the assumption that if `[a, b]` is a valid real domain, then the square `[a, b] x [a, b]` is a valid complex domain (which is what is done in the make_tensor function when the dtype is complex):
```python
eps = 1e-5
a = torch.tensor((-0.5 + eps * 1j, -.5 - eps * 1j))
print(a.acos())
# tensor([2.0944-1.1576e-05j, 2.0944+1.1549e-05j])
# Notice that the sign of the imaginary part is flipped

**Comment by mruberry** [comment]
Interesting! That's true we do make that assumption. If that's the issue then we could update the OpInfo's sample inputs. I wonder if there's a better way to model complex domains? I suppose the most general thing we could do is allow OpInfos to specify custom tensor generators, and those generators could ensure values are within the domain.

**Comment by albanD** [comment]
Another (not as good) solution is to provide a real domain such that the corresponding complex one is valid. In this case `[0, 1]` would work I think.

**Comment by anjali411** [comment]
I think in some cases with symmetric domain like `acos`, it might be useful to construct the complex tensor by randomly generating ian absolute value and angle tensor separately, and using `torch.polar(abs, angle)`. We could easily enable this by adding `**kwargs` input to `make_tensor`.
