### ISSUE TITLE
DISABLED test_trainer_ps (__main__.TensorPipeDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#50700]
https://app.circleci.com/pipelines/github/pytorch/pytorch/260886/workflows/5b771d1a-d1b3-401f-9cb2-d0e491a72e16/jobs/10204990/steps

```
Jan 16 03:25:06 ======================================================================
Jan 16 03:25:06 ERROR [61.706s]: test_trainer_ps (__main__.TensorPipeDistAutogradTestWithSpawn)
Jan 16 03:25:06 ----------------------------------------------------------------------
Jan 16 03:25:06 Traceback (most recent call last):
Jan 16 03:25:06   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 300, in wrapper
Jan 16 03:25:06     self._join_processes(fn)
Jan 16 03:25:06   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 417, in _join_processes
Jan 16 03:25:06     self._check_return_codes(elapsed_time)
Jan 16 03:25:06   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 453, in _check_return_codes
Jan 16 03:25:06     raise RuntimeError(error)
Jan 16 03:25:06 RuntimeError: Processes 0 3 exited with error code 10
Jan 16 03:25:06 
Jan 16 03:25:06 ----------------------------------------------------------------------
```

```
Jan 16 03:14:24   test_trainer_ps (__main__.TensorPipeDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:14:24 [W tensorpipe_agent.cpp:63] Failed to look up the IP address for the hostname (EAI_NONAME: unknown node or service), defaulting to 127.0.0.1
Jan 16 03:15:24 ERROR:root:Caught exception: 
Jan 16 03:15:24 Traceback (most recent call last):
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 303, in wrapper
Jan 16 03:15:24     fn()
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Jan 16 03:15:24     return_value = old_test_method(self, *arg, **kwargs)
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1044, in test_trainer_ps
Jan 16 03:15:24     self._test_trainer_ps(create_tensor, _run_trainer)
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1040, in _test_trainer_ps
Jan 16 03:15:24     torch.futures.wait_all(futures)
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/futures/__init__.py", line 196, in wait_all
Jan 16 03:15:24     return [fut.wait() for fut in torch._C._collect_all(cast(List[torch._C.Future], futures)).wait()]
Jan 16 03:15:24 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jan 16 03:15:24 exiting process with exit code: 10
Jan 16 03:15:24 ERROR:root:Caught exception: 
Jan 16 03:15:24 Traceback (most recent call last):
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 303, in wrapper
Jan 16 03:15:24     fn()
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Jan 16 03:15:24     return_value = old_test_method(self, *arg, **kwargs)
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1044, in test_trainer_ps
Jan 16 03:15:24     self._test_trainer_ps(create_tensor, _run_trainer)
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 1040, in _test_trainer_ps
Jan 16 03:15:24     torch.futures.wait_all(futures)
Jan 16 03:15:24   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/futures/__init__.py", line 196, in wait_all
Jan 16 03:15:24     return [fut.wait() for fut in torch._C._collect_all(cast(List[torch._C.Future], futures)).wait()]
Jan 16 03:15:24 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jan 16 03:15:24 exiting process with exit code: 10
Jan 16 03:15:24 [W tensorpipe_agent.cpp:777] RPC agent for worker1 encountered error when reading incoming response from worker3: EOF: end of file
Jan 16 03:15:24 [W tensorpipe_agent.cpp:590] RPC agent for worker1 encountered error when reading incoming request from worker3: EOF: end of file (this is expected to happen during shutdown)
Jan 16 03:15:24 [W tensorpipe_agent.cpp:590] RPC agent for worker1 encountered error when reading incoming request from worker0: EOF: end of file (this is expected to happen during shutdown)
Jan 16 03:15:24 [W tensorpipe_agent.cpp:777] RPC agent for worker1 encountered error when reading incoming response from worker0: EOF: end of file
Jan 16 03:15:24 Process 0 terminated with exit code 10, terminating remaining processes.
Jan 16 03:15:24 ERROR (61.706s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @agolynski @cbalioglu

**Comment by janeyx99** [comment]
Closing as TensorPipeDistAutogradTestWithSpawn hasn't occurred in our test times table in 2 weeks. https://fburl.com/scuba/pytorch_test_times/ytjng8mk And this test case thus no longer exists.
