### ISSUE TITLE
DISABLED test_barrier_timeout_group (__main__.TestDistBackendWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#50754]
https://app.circleci.com/pipelines/github/pytorch/pytorch/261469/workflows/4c0ccb6d-d5ca-49b9-9c10-0ca450ea12b3/jobs/10239823/steps

https://app.circleci.com/pipelines/github/pytorch/pytorch/261499/workflows/ad4ef96e-2e57-432a-b5a8-da169b821335/jobs/10239862/steps

```
======================================================================
ERROR [4.639s]: test_barrier_timeout_group (__main__.TestDistBackendWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 453, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Processes 0 exited with error code 10

----------------------------------------------------------------------
```

```
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 303, in wrapper
    fn()
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\distributed\distributed_test.py", line 553, in test_barrier_timeout_group
    _, group_id, _ = self._init_group_test(timeout=timeout)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\distributed\distributed_test.py", line 348, in _init_group_test
    group_id = dist.new_group(group, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\distributed\distributed_c10d.py", line 2524, in new_group
    _store_based_barrier(global_rank, default_store, timeout)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\distributed\distributed_c10d.py", line 215, in _store_based_barrier
    rank, store_key, world_size, worker_count, timeout))
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:2 (world_size=3, worker_count=1, timeout=0:00:01)
exiting process with exit code: 10
Process 0 terminated with exit code 10, terminating remaining processes.
ERROR (4.639s)
```

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by mszhanyi** [comment]
same as #50662

**Comment by malfet** [comment]
Can we increase the timeout to 5 sec on Windows?

**Comment by mszhanyi** [comment]
fixed by https://github.com/pytorch/pytorch/pull/51330
