### ISSUE TITLE
DISABLED test_check_failed_messages (__main__.FaultyFaultyAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#50842]
https://app.circleci.com/pipelines/github/pytorch/pytorch/262075/workflows/c4838cd4-d639-454b-8982-7b3f1bb99d6d/jobs/10273657/steps

```
Jan 20 21:32:07 ======================================================================
Jan 20 21:32:07 ERROR [61.639s]: test_check_failed_messages (__main__.FaultyFaultyAgentRpcTestWithSpawn)
Jan 20 21:32:07 ----------------------------------------------------------------------
Jan 20 21:32:07 Traceback (most recent call last):
Jan 20 21:32:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 282, in wrapper
Jan 20 21:32:07     self._join_processes(fn)
Jan 20 21:32:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 399, in _join_processes
Jan 20 21:32:07     self._check_return_codes(elapsed_time)
Jan 20 21:32:07   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 435, in _check_return_codes
Jan 20 21:32:07     raise RuntimeError(error)
Jan 20 21:32:07 RuntimeError: Processes 0 exited with error code 10
Jan 20 21:32:07 
Jan 20 21:32:07 ----------------------------------------------------------------------
```

```
Jan 20 21:29:30   test_check_failed_messages (__main__.FaultyFaultyAgentRpcTestWithSpawn) ... ERROR:root:Caught exception: 
Jan 20 21:29:30 Traceback (most recent call last):
Jan 20 21:29:30   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Jan 20 21:29:30     fn()
Jan 20 21:29:30   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Jan 20 21:29:30     return_value = old_test_method(self, *arg, **kwargs)
Jan 20 21:29:30   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 4174, in test_check_failed_messages
Jan 20 21:29:30     self.assertEqual(rref.to_here(), torch.add(torch.ones(2, 2), torch.ones(2, 2)))
Jan 20 21:29:30 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jan 20 21:29:30 exiting process with exit code: 10
Jan 20 21:29:30 Process 0 terminated with exit code 10, terminating remaining processes.
Jan 20 21:29:30 ERROR (61.639s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @agolynski

**Comment by mrshenli** [comment]
cc @osalpekar

**Comment by pritamdamania87** [comment]
This is failing due to an internal issue in PyTorch in terms of how we use std::type_index in getCustomClassTypeMap (see https://github.com/pytorch/pytorch/issues/51229 for more details).

**Comment by janeyx99** [comment]
This test doesn't seem to exist anymore. There is a test_check_failed_messages from the suite FaultyFaultyAgentRpcTest instead that has been running just fine https://fburl.com/scuba/pytorch_test_times/eqzb4tvm
