### ISSUE TITLE
DISABLED test_reduce_sum_cuda_twice (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#50840]
https://app.circleci.com/pipelines/github/pytorch/pytorch/262011/workflows/38a58985-2b09-4dfa-80ee-d9025fa109c8/jobs/10274301/steps

```
Jan 20 20:53:22 ======================================================================
Jan 20 20:53:22 ERROR [2.546s]: test_reduce_sum_cuda_twice (__main__.TestDistBackendWithFork)
Jan 20 20:53:22 ----------------------------------------------------------------------
Jan 20 20:53:22 Traceback (most recent call last):
Jan 20 20:53:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 282, in wrapper
Jan 20 20:53:22     self._join_processes(fn)
Jan 20 20:53:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 399, in _join_processes
Jan 20 20:53:22     self._check_return_codes(elapsed_time)
Jan 20 20:53:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 435, in _check_return_codes
Jan 20 20:53:22     raise RuntimeError(error)
Jan 20 20:53:22 RuntimeError: Processes 2 exited with error code 10
Jan 20 20:53:22 
Jan 20 20:53:22 ----------------------------------------------------------------------
```

```
Jan 20 20:53:19   test_reduce_sum_cuda_twice (__main__.TestDistBackendWithFork) ... ERROR:root:Caught exception: 
Jan 20 20:53:19 Traceback (most recent call last):
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Jan 20 20:53:19     fn()
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 50, in wrapper
Jan 20 20:53:19     return func(*args, **kwargs)
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 158, in wrapper
Jan 20 20:53:19     return func(*args, **kwargs)
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 1272, in test_reduce_sum_cuda_twice
Jan 20 20:53:19     rank_to_GPU,
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 1237, in _test_reduce_twice_helper
Jan 20 20:53:19     secondary_op_call=lambda: dist.reduce(tensors[1], src, op, group_id))
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 1348, in call_dist_op
Jan 20 20:53:19     self.assertEqual(len(events), len(op_calls))
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1210, in assertEqual
Jan 20 20:53:19     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Jan 20 20:53:19   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
Jan 20 20:53:19     raise self.failureException(msg)
Jan 20 20:53:19 AssertionError: False is not true : Scalars failed to compare as equal! Comparing 1 and 2 gives a difference of 1, but the allowed difference with rtol=0 and atol=0 is only 0!
Jan 20 20:53:19 exiting process with exit code: 10
Jan 20 20:53:19 Process 2 terminated with exit code 10, terminating remaining processes.
Jan 20 20:53:19 ERROR (2.546s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by pritamdamania87** [comment]
Closing this one out since I haven't been able to repro this locally or even in the CircleCI environment.

**Comment by mrshenli** [comment]
reopen as it still persist on master,

https://app.circleci.com/pipelines/github/pytorch/pytorch/271513/workflows/98cbef65-69e8-491f-b496-1a000f5294b3/jobs/10785763/steps

https://app.circleci.com/pipelines/github/pytorch/pytorch/271550/workflows/d54dfbfd-248c-469b-9367-8884336ca493/jobs/10787774/steps

**Comment by pritamdamania87** [comment]
Closing this to re-enable the test and trigger logging added in https://github.com/pytorch/pytorch/pull/56406, please re-open when a new failure is encountered.
