### ISSUE TITLE
DISABLED test_device_maps_multi_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#50881]
https://app.circleci.com/pipelines/github/pytorch/pytorch/262382/workflows/f23c73a1-fcd2-46c5-a28c-cf6827d744e2/jobs/10289993/steps

```
Jan 21 11:15:43 ======================================================================
Jan 21 11:15:43 ERROR [6.137s]: test_device_maps_multi_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn)
Jan 21 11:15:43 ----------------------------------------------------------------------
Jan 21 11:15:43 Traceback (most recent call last):
Jan 21 11:15:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 282, in wrapper
Jan 21 11:15:43     self._join_processes(fn)
Jan 21 11:15:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 399, in _join_processes
Jan 21 11:15:43     self._check_return_codes(elapsed_time)
Jan 21 11:15:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 435, in _check_return_codes
Jan 21 11:15:43     raise RuntimeError(error)
Jan 21 11:15:43 RuntimeError: Processes 1 exited with error code 10
Jan 21 11:15:43 
Jan 21 11:15:43 ----------------------------------------------------------------------
```

```
Jan 21 11:15:08   test_device_maps_multi_gpu_self (__main__.TensorPipeTensorPipeAgentRpcTestWithSpawn) ... ERROR:root:Caught exception: 
Jan 21 11:15:08 Traceback (most recent call last):
Jan 21 11:15:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Jan 21 11:15:08     fn()
Jan 21 11:15:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
Jan 21 11:15:08     return func(*args, **kwargs)
Jan 21 11:15:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 4922, in test_device_maps_multi_gpu_self
Jan 21 11:15:08     self._test_device_maps_multi_gpu(dst)
Jan 21 11:15:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 4910, in _test_device_maps_multi_gpu
Jan 21 11:15:08     self.assertEqual(rets[0], (torch.zeros(2) + torch.ones(2)).to(1))
Jan 21 11:15:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1165, in assertEqual
Jan 21 11:15:08     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Jan 21 11:15:08   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
Jan 21 11:15:08     raise self.failureException(msg)
Jan 21 11:15:08 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 0 element(s) (out of 2) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0 (1.0 vs. 1.0), which occurred at index 0.
Jan 21 11:15:08 exiting process with exit code: 10
Jan 21 11:15:09 [W tensorpipe_agent.cpp:648] RPC agent for worker0 encountered error when reading incoming request from worker1: EOF: end of file (this is expected to happen during shutdown)
Jan 21 11:15:09 Process 1 terminated with exit code 10, terminating remaining processes.
Jan 21 11:15:09 ERROR (6.137s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by mrshenli** [comment]
hmmm, this error message does not make sense to me:

```
Jan 21 11:15:08 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 0 element(s) (out of 2) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0 (1.0 vs. 1.0), which occurred at index 0.
Jan 21 11:15:08 exiting process with exit code: 10
```

**Comment by mrshenli** [comment]
This should be a stream synchronization issue where the `allclose` comparison was done before the ops in the stream are executed. 

https://github.com/pytorch/pytorch/blob/4cca08368b4c32ea39f1e0b309628373e92ab8ab/torch/testing/__init__.py#L129-L160
