### ISSUE TITLE
dataloader bug need help

### ISSUE THREAD

**Issue by panxin801** [pytorch/pytorch#50939]
Hello. I use python3+torch1.5_cu101, I want to use multi gpu for training, so I want to speed up the dataloading speed ,and then I set dataloader(num_worker=0),  and after a 1 day the following bug emits

'7264850 /mnt/mnt1/wav/G0825/session01/DTM2_100_ahead_000_G0825_S5786_00.wav
7264851 (81920,)
7264852 (81920,)
7264853 (81920,)
7264854 (81920,)
7264855 (81920,)
7264856 (81920,)/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer         division of tensors using div or / is deprecated, and in a future release d        iv will perform true division as in Python 3. Use true_divide or floor_divid        e (// in Python) instead.
7264857 Traceback (most recent call last):
7264858   File "train.py", line 91, in <module>
7264859     trainer.train()
7264860   File "/root/panxin_m/src/trainer.py", line 25, in train
7264861     train_loss = self.iter_one_epoch()
7264862   File "/root/panxin_m/src/trainer.py", line 48, in iter_one_epoch
7264863     train_data = next(loader_iter)
7264864   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader        .py", line 345, in __next__
7264865     data = self._next_data()
7264866   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader        .py", line 856, in _next_data
7264867     return self._process_data(data)
7264868   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader        .py", line 881, in _process_data
7264869     data.reraise()
7264870   File "/root/.local/lib/python3.7/site-packages/torch/_utils.py", line 395,         in reraise
7264871     raise self.exc_type(msg)
7264872 ValueError: Caught ValueError in DataLoader worker process 6.
7264873 Original Traceback (most recent call last):
7264874   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/_utils/wor        ker.py", line 178, in _worker_loop
7264875     data = fetcher.fetch(index)
7264876   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fet        ch.py", line 47, in fetch
7264877     return self.collate_fn(data)
7264878   File "/root/panxin_m/src/data.py", line 139, in __call__
7264879     padded_waveforms, lengths = load_batch_waves(paths, self.channels)
7264880   File "/root/panxin_m/src/data.py", line 99, in load_batch_waves
7264881     sample_rate, waveform = utils.load_wave(path, channels)
7264882   File "/root/panxin_m/src/utils.py", line 33, in load_wave
7264883     datas = np.append(datas, data[np.newaxis,:], axis=0)
7264884   File "<__array_function__ internals>", line 6, in append
7264885   File "/root/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.        py", line 4693, in append
7264886     return concatenate((arr, values), axis=axis)
7264887   File "<__array_function__ internals>", line 6, in concatenate
7264888 ValueError: all the input array dimensions for the concatenation axis must m        atch exactly, but along dimension 1, the array at index 0 has size 69632 and         the array at index 1 has size 36677
7264889'

In the experiment I read wave audio files, each file has 16 input channels. And I can 100% sure that the length of each channels are the same. but I dont know why in one of the workers, this error occurs. seems the dataloader did not read different channels and concat them as I expected. can you help me if I made something wrong ,and thank you.

**Comment by glaringlee** [comment]
@panxin801 
How you prepared your dataset? 
Can you post more info (a code sample would be great!)?

**Comment by SsnL** [comment]
Error is from your own dataset code, as clearly stated in the trace
```
7264878 File "/root/panxin_m/src/data.py", line 139, in call
7264879 padded_waveforms, lengths = load_batch_waves(paths, self.channels)
7264880 File "/root/panxin_m/src/data.py", line 99, in load_batch_waves
7264881 sample_rate, waveform = utils.load_wave(path, channels)
7264882 File "/root/panxin_m/src/utils.py", line 33, in load_wave
7264883 datas = np.append(datas, data[np.newaxis,:], axis=0)
7264884 File "<array_function internals>", line 6, in append
7264885 File "/root/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base. py", line 4693, in append
7264886 return concatenate((arr, values), axis=axis)
7264887 File "<array_function internals>", line 6, in concatenate
7264888 ValueError: all the input array dimensions for the concatenation axis must m atch exactly, but along dimension 1, the array at index 0 has size 69632 and the array at index 1 has size 36677
7264889'
```

**Comment by panxin801** [comment]
Thank you for the reply, and here is my source code of function load_wave_batch(path,channels)
```
def load_wave_batch(paths, channels):
    waveforms = []  # dims like [batch,16,xxx]
    lengths = []
    for path in paths:
        sample_rate, waveform = utils.load_wave(
            path, channels
        )  # utils.load_wave has been modified for reading array mic datas and return it. waveform should be like [16,xxx] dimension
        waveform = torch.from_numpy(waveform)
        waveforms.append(waveform)
        lengths.append(waveform.shape[1])
    # following parts need some changing
    # waveforms = np.array(waveforms, dtype=np.float32)
    max_length = max(lengths)
    # The following needs some changing
    padded_waveforms = torch.zeros(len(lengths), channels, max_length)
    for i in range(len(lengths)):
        padded_waveforms[i,:,:lengths[i]] += waveforms[i]
    return padded_waveforms, torch.LongTensor(lengths)
```
path is my read path like :/data/wave/C_1_00.wav, /data/wave/C_1_01.wav ... ... /data/wave/C_1_15.wav. That means 16 different channels of audio.
channels: is a int number set to 16.
Also, I put the repo here on github `https://github.com/panxin801/multiASR/blob/master/src/data.py`

**Comment by panxin801** [comment]
This is some parts of my train.py code 
```
with open(args.config) as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    dataconfig = config["data"]
    trainingconfig = config["training"]
    modelconfig = config["model"]

    training_set = data.SpeechDataset(dataconfig["trainset"])
    valid_set = data.SpeechDataset(dataconfig["devset"], reverse=True)
    if "vocab_path" in dataconfig:
        tokenizer = data.CharTokenizer(dataconfig["vocab_path"])
    else:
        raise ValueError("Unknown tokenizer.")
    if modelconfig['signal']["feature_type"] == 'offline':
        collate = data.FeatureCollate(tokenizer, dataconfig["maxlen"])
    else:
        collate = data.WaveCollate(tokenizer, dataconfig["maxlen"],
                                   dataconfig["channels"])

    ngpu = 1
    if "multi_gpu" in trainingconfig and trainingconfig["multi_gpu"] == True:
        ngpu = torch.cuda.device_count()
    trainingsampler = data.TimeBasedSampler(training_set,
                                            trainingconfig["batch_time"] *
                                            ngpu,
                                            ngpu,
                                            shuffle=True)
    validsampler = data.TimeBasedSampler(
        valid_set, trainingconfig["batch_time"] * ngpu, ngpu,
        shuffle=False)  # for plot longer utterance

    tr_loader = torch.utils.data.DataLoader(
        training_set,
        collate_fn=collate,
        batch_sampler=trainingsampler,
        shuffle=False,
        num_workers=dataconfig["fetchworker_num"])
    cv_loader = torch.utils.data.DataLoader(
        valid_set,
        collate_fn=collate,
        batch_sampler=validsampler,
        shuffle=False,
        num_workers=dataconfig["fetchworker_num"])
```

In data.py the source code of collate_fn is implemention here
```
class WaveCollate(object):
    def __init__(self, tokenizer, maxlen, channels):
        self.tokenizer = tokenizer
        self.maxlen = maxlen
        self.channels = channels
        return

    def __call__(self, batch):
        print("WaveCollate called")
        utts = [d["utt"] for d in batch]
        paths = [d["path"] for d in batch]
        trans = [d["transcript"] for d in batch]
        timer = utils.Timer()
        timer.tic()
        padded_waveforms, wave_lengths = load_wave_batch(paths, self.channels)
        logging.debug("Wave Loading Time: {}s".format(timer.toc()))
        timer.tic()
        rawids_list = [self.tokenizer.encode(t) for t in trans]
        ids, labels, paddings = gen_casual_targets(
            rawids_list, self.maxlen, self.tokenizer.to_id(SOS_SYM),
            self.tokenizer.to_id(EOS_SYM))
        logging.debug("Transcription Processing Time: {}s".format(timer.toc()))
        return utts, padded_waveforms, wave_lengths, ids, labels, paddings
```
