### ISSUE TITLE
DISABLED test_async_function_remote_multi (__main__.TensorPipeJitRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#50965]
This seems to be rare, so not disabling yet. 

https://app.circleci.com/pipelines/github/pytorch/pytorch/263014/workflows/1359adb7-9dd9-4540-ba5e-e78fe944182c/jobs/10324519/steps

```
Jan 22 16:43:25 ======================================================================
Jan 22 16:43:25 ERROR [1.551s]: test_async_function_remote_multi (__main__.TensorPipeJitRpcTestWithSpawn)
Jan 22 16:43:25 ----------------------------------------------------------------------
Jan 22 16:43:25 Traceback (most recent call last):
Jan 22 16:43:25   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 282, in wrapper
Jan 22 16:43:25     self._join_processes(fn)
Jan 22 16:43:25   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 399, in _join_processes
Jan 22 16:43:25     self._check_return_codes(elapsed_time)
Jan 22 16:43:25   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 435, in _check_return_codes
Jan 22 16:43:25     raise RuntimeError(error)
Jan 22 16:43:25 RuntimeError: Processes 3 exited with error code 10
Jan 22 16:43:25 
Jan 22 16:43:25 ----------------------------------------------------------------------
```

```
Jan 22 16:30:40   test_async_function_remote_multi (__main__.TensorPipeJitRpcTestWithSpawn) ... [W tensorpipe_agent.cpp:648] RPC agent for worker1 encountered error when reading incoming request from worker0: ECONNRESET: connection reset by peer (this is expected to happen during shutdown)
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #24 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #25 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #23 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #3 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #27 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #28 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #26 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #29 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #30 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #4 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #31 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #5 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #20 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #32 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #6 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #9 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #33 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #7 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #21 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #35 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #10 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #22 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #34 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #8 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #36 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #37 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #11 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #13 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #38 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #12 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #14 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #17 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #40 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #15 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #39 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #16 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #18 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #19 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #41 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #42 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:596] RPC agent for worker1 encountered error when sending response to request #43 to worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker1 encountered error when reading incoming response from worker0: ECONNRESET: connection reset by peer
Jan 22 16:30:40 Failed to respond to 'Shutdown Proceed' in time, got error ECONNRESET: connection reset by peer
Jan 22 16:30:40 [W tensorpipe_agent.cpp:648] RPC agent for worker2 encountered error when reading incoming request from worker0: EOF: end of file (this is expected to happen during shutdown)
Jan 22 16:30:40 [W tensorpipe_agent.cpp:648] RPC agent for worker3 encountered error when reading incoming request from worker0: EOF: end of file (this is expected to happen during shutdown)
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:838] RPC agent for worker3 encountered error when reading incoming response from worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #29 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #30 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #32 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #31 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #34 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #33 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #35 to worker0: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #37 to worker0: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #36 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #39 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #38 to worker0: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #41 to worker0: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [W tensorpipe_agent.cpp:810] RPC agent for worker3 encountered error when sending outgoing request #40 to worker0: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 [E thread_pool.cpp:112] Exception in thread pool task: EOF: end of file
Jan 22 16:30:40 ERROR:root:Caught exception: 
Jan 22 16:30:40 Traceback (most recent call last):
Jan 22 16:30:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Jan 22 16:30:40     fn()
Jan 22 16:30:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Jan 22 16:30:40     return_value = old_test_method(self, *arg, **kwargs)
Jan 22 16:30:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 1362, in test_async_function_remote_multi
Jan 22 16:30:40     self.assertEqual(rrefs[i].to_here(), torch.ones(2, 2) + i)
Jan 22 16:30:40 RuntimeError: EOF: end of file
Jan 22 16:30:40 exiting process with exit code: 10
Jan 22 16:30:40 ERROR:root:Caught exception: 
Jan 22 16:30:40 Traceback (most recent call last):
Jan 22 16:30:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Jan 22 16:30:40     fn()
Jan 22 16:30:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Jan 22 16:30:40     return_value = old_test_method(self, *arg, **kwargs)
Jan 22 16:30:40   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 1362, in test_async_function_remote_multi
Jan 22 16:30:40     self.assertEqual(rrefs[i].to_here(), torch.ones(2, 2) + i)
Jan 22 16:30:40 RuntimeError: EOF: end of file
Jan 22 16:30:40 exiting process with exit code: 10
Jan 22 16:30:40 Process 3 terminated with exit code 10, terminating remaining processes.
Jan 22 16:30:40 ERROR (1.551s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @gmagogsfm

**Comment by gmagogsfm** [comment]
Removing `jit` label as it doesn't seem JIT-related now. Please let me know if that's not the case. Thanks.

**Comment by gcramer23** [comment]
There is another issue tracking this test https://github.com/pytorch/pytorch/issues/46863.

**Comment by janeyx99** [comment]
Closing as #46863 is resolbved.
