### ISSUE TITLE
.parameters() not supported in JIT because of yield

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#51019]
## 🐛 Bug

There seems to be a `.parameters()` in the [ScriptModule](https://pytorch.org/docs/stable/generated/torch.jit.ScriptModule.html#torch.jit.ScriptModule.parameters). It would be great if instead of translating the normal `.parameters()` to JIT (which fails because of a `yield`) it directly uses the `ScriptModule`'s `.parameters()`.
```py
import torch


class Test(torch.nn.Module):
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        for parameter in self.parameters():
            x = x.to(device=parameter.device)
            break
        return x


print(torch.__version__)  # 1.7.1+cu101
model = Test()
torch.jit.script(model)
```
```
Traceback (most recent call last):
  File "test_pytorch.py", line 14, in <module>
    torch.jit.script(model)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 897, in script
    return torch.jit._recursive.create_script_module(
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 410, in create_script_module_imp
l
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 304, in create_methods_and_prope
rties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 676, in compile_unbound_method
    stub = make_stub(fn, fn.__name__)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 37, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 221, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 255, in build_def
    build_stmts(ctx, body))
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 127, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 127, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 229, in __call__
    return method(ctx, node)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 435, in build_For
    [build_expr(ctx, stmt.iter)], build_stmts(ctx, stmt.body))
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 127, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 127, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 229, in __call__
    return method(ctx, node)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 363, in build_Expr
    return ExprStmt(build_expr(ctx, value))
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/frontend.py", line 228, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: Yield aren't supported:
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090
        """
        for name, param in self.named_parameters(recurse=recurse):
            yield param
            ~ <--- HERE
```

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi twoertwein, thanks for reporting this issue. I think ScriptModule's documentation shows a `parameters` method only because it inherits from normal `torch.nn.Module`, itself doesn't implement a TorchScrpt-able `parameters` method.

**Comment by twoertwein** [comment]
Is there a recommended way to get the device of a ScriptModule/its parameters (in my case all parameters are on the same device)?

**Comment by gmagogsfm** [comment]
> Is there a recommended way to get the device of a ScriptModule/its parameters (in my case all parameters are on the same device)?

Does it have to be in TorchScript? If not, ScriptModule still exposes the same `parameters` method in Eager that you can use. You may even use it in a function/method that is decorated with `torch.jit.ignore` even if caller is in TorchScript.
 
If it does have to be in TorchScript, then you can access the device by access `device` property of individual parameters (if you know the structure of module and name of parameter)

Hope this is helpful.
