### ISSUE TITLE
len of ModuleList is incorrect for jitted models

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#51018]
## 🐛 Bug

```py
from typing import Final

import torch


class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.models: Final = torch.nn.modules.container.ModuleList([])

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if len(self.models) != 0:
            x = self.models[0](x)
        return x


print(torch.__version__)  # 1.7.1+cu101
model = Test()
torch.jit.script(model)
```

```traceback-python
Traceback (most recent call last):
  File "test_pytorch.py", line 19, in <module>
    torch.jit.script(model)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 897, in script
    return torch.jit._recursive.create_script_module(
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 410, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 304, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Index 0 out of range of length 0:
  File "test_pytorch.py", line 13
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if len(self.models) != 0:
            x = self.models[0](x)
                ~~~~~~~~~~~~~~ <--- HERE
        return x
```

**Comment by gmagogsfm** [comment]
Note: this fails during compilation not during forward invocation. We should probably meta-compile condition of `if` to avoid this.

**Comment by twoertwein** [comment]
I assume this issue can be closed: #43942 and #49728 describe the same underlying issue and they seem to be fixed for 1.8 :)

**Comment by twoertwein** [comment]
nope, still doesn't work on 1.8.0 :( but the issues linked above suggest that it should work?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
