### ISSUE TITLE
GNU and LLVM OpenMP conflict when using MKL and KINETO under conda build

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#51026]
## 🐛 Bug

When building pytorch with MKL and KINETO enabled under conda environment, importing torch fails with the message:
```
$ python -c 'import torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pearu/git/pytorch/pytorch/torch/__init__.py", line 192, in <module>
    from torch._C import *
ImportError: /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so.1: version `OACC_2.0' not found (required by /home/pearu/git/pytorch/pytorch/torch/lib/libtorch_cpu.so)
```

## To Reproduce

1. Setup conda environment using `conda env create --file=pytorch-cuda-dev.yaml` where <code>pytorch-cuda-dev.yaml</code>:

<details>

```
name: pytorch-cuda-dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3
  - numpy
  - ninja
  - pyyaml
  - mkl
  - mkl-include
  - setuptools
  - cmake
  - cffi
  - typing
  - pytest
  - compilers
  - flake8
  - psutil
  - hypothesis
  - nvcc_linux-64=11.0
  - magma-cuda110
  - mypy
  - clang-tools
```

</details>

2. Build PyTorch using `python setup.py develop`
3. Try `import torch`

## Expected behavior

`import torch` should succeed.

## Environment

Output of `collect_env.py`:
<details>

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A (pearu: it is 11.0.3)
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0
Clang version: 11.0.1 (https://github.com/conda-forge/clangdev-feedstock 9fbb64b62ff49e9d206a06e62453b27557b3ed73)
CMake version: version 3.19.3

Python version: 3.9 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2060 SUPER
GPU 1: GeForce RTX 2060 SUPER

Nvidia driver version: 460.27.04
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1.243/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0a0+unknown
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.19.5           py39hdbf815f_1    conda-forge
[conda] torch                     1.8.0a0+unknown           dev_0    <develop>
```

</details>

The details of conda environment are described in https://github.com/conda-forge/ctng-compilers-feedstock/issues/49

## Additional context

Notice that the MKL conda package requires Intel/LLVM OpenMP while PyTorch KINETO component links against `${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti_static.a`, see https://github.com/pytorch/pytorch/blob/48b6b9221a544f7d5b7d6f93eec2fa304da8af94/cmake/Dependencies.cmake#L1816 that references `acc_get_device_type@@OACC_2.0` which is defined only in GNU OpenMP.

### Workaround

As a workaround, one can build an importable `torch` by disabling KINETO: `USE_KINETO=0`. Btw, building without `MKL` also leads to an importable `torch`.

### Possible solution

To keep KINETO enabled, one could use `USE_CUPTI_SO=1`. However, when the static `cupti` library exists, `USE_CUPTI_SO` is ignored, see https://github.com/pytorch/pytorch/blob/48b6b9221a544f7d5b7d6f93eec2fa304da8af94/cmake/Dependencies.cmake#L1815-L1825

With
```
export USE_CUPTI_SO=1
export LDFLAGS="${LDFLAGS} -Wl,-rpath-link,${CUDA_HOME}/extras/CUPTI/lib64 -L${CUDA_HOME}/extras/CUPTI/lib64"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CUDA_HOME}/extras/CUPTI/lib64
```
and applying the following patch
<details>

```
diff --git a/cmake/Dependencies.cmake b/cmake/Dependencies.cmake
index e138a86c61..d9ab896bfa 100644
--- a/cmake/Dependencies.cmake
+++ b/cmake/Dependencies.cmake
@@ -1812,16 +1812,16 @@ if(USE_KINETO)
   message(STATUS "  KINETO_LIBRARY_TYPE = ${KINETO_LIBRARY_TYPE}")
   message(STATUS "  CUDA_SOURCE_DIR = ${CUDA_SOURCE_DIR}")
 
-  if(EXISTS ${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti_static.a)
-    set(CUDA_cupti_LIBRARY "${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti_static.a")
-  elseif(EXISTS ${CUDA_SOURCE_DIR}/lib64/libcupti_static.a)
-    set(CUDA_cupti_LIBRARY "${CUDA_SOURCE_DIR}/lib64/libcupti_static.a")
-  elseif(USE_CUPTI_SO)
+  if(USE_CUPTI_SO)
     if(EXISTS ${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti.so)
       set(CUDA_cupti_LIBRARY "${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti.so")
     elseif(EXISTS ${CUDA_SOURCE_DIR}/lib64/libcupti.so)
       set(CUDA_cupti_LIBRARY "${CUDA_SOURCE_DIR}/lib64/libcupti.so")
     endif()
+  elseif(EXISTS ${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti_static.a)
+    set(CUDA_cupti_LIBRARY "${CUDA_SOURCE_DIR}/extras/CUPTI/lib64/libcupti_static.a")
+  elseif(EXISTS ${CUDA_SOURCE_DIR}/lib64/libcupti_static.a)
+    set(CUDA_cupti_LIBRARY "${CUDA_SOURCE_DIR}/lib64/libcupti_static.a")
   endif()
 
   if(EXISTS ${CUDA_SOURCE_DIR}/extras/CUPTI/include)
```

</details>

I was able to build an importable pytorch with both MKL and KINETO components enabled.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @malfet @seemethere @walterddr

**Comment by ngimel** [comment]
cc @ilia-cher

**Comment by ilia-cher** [comment]
I wonder whether we should just enable USE_CUPTI_SO by default but we have to then make sure that actual release builds are built only with statically linked kineto and cupti
cc. @malfet

**Comment by ilia-cher** [comment]
USE_CUPTI_SO is only for development purposes, release builds are always compiled with libraries statically linked in
let's my try to repro and see if we can possibly update kineto build config

**Comment by seemethere** [comment]
Labeling this as high priority since this is causing our nightlies to fail for conda builds on Python 3.9. Also do note that I added this to the `1.8.0` milestone and this will be a release blocking issue for any scheduled RCs we plan to do in the upcoming weeks.

Issue text from #51310:

Appears as though nightly conda builds are currently failing with:

```
Jan 28 10:15:20 + python -c 'import torch'
Jan 28 10:15:20 Traceback (most recent call last):
Jan 28 10:15:20   File "<string>", line 1, in <module>
Jan 28 10:15:20   File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/__init__.py", line 192, in <module>
Jan 28 10:15:20     from torch._C import *
Jan 28 10:15:20 ImportError: /opt/conda/envs/testenv/lib/python3.9/site-packages/torch/lib/../../../../libgomp.so.1: version `OACC_2.0' not found (required by /opt/conda/envs/testenv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
```

Builds for this started failing between Jan 22, 2021 and Jan 23, 2021 (7494f0233aabb5109e068f3cad73e20dc6a8dd23...6aec1eba1582ef2c3486652ec0a6cd0ce346b83d)

Note that these builds are only failing for 

Link to [CircleCI Logs](https://app.circleci.com/pipelines/github/pytorch/pytorch/263351/workflows/a6cbec9b-8731-4681-94dc-feff02429f81/jobs/10343343) and [build artifact](https://10342399-65600975-gh.circle-artifacts.com/0/final_pkgs/pytorch-1.8.0.dev20210123-py3.9_cuda11.0.221_cudnn8.0.5_0.tar.bz2)

**Comment by ilia-cher** [comment]
(a quick update: we've identified the issue and will send a fix)

**Comment by malfet** [comment]
Hmm, `acc_get_device_type` is defined as weak-symbol in libcupti_static.a:
```
$ readelf -s /usr/local/cuda/lib64/libcupti_static.a|grep acc_get_
 35287: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND acc_get_device_type
```
which means, it does not need to be satisfied in order to load the library/executable. Consider following example:
```
$ printf "#include <cupti.h>\nint main() { uint32_t numMetrics=0; return cuptiGetNumMetrics(&numMetrics);}"|gcc -x c -  -I/usr/local/cuda/include -L/usr/local/cuda/lib64 -lcupti_static -lm -lrt -ldl -lpthread
$ ./a.out ; echo $?
0
$ readelf -s ./a.out |grep acc_get
   166: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND acc_get_device_type
 19461: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND acc_get_device_type
```
@pearu, are you building with CUDA-11 by any chance?

**Comment by pearu** [comment]
Yes, we are using CUDA 11.0.3. If needed, I can try to reproduce the issue with other cuda versions 9.2 - 11.2. Just let me know.

**Comment by pearu** [comment]
@malfet I think your cupti test is fine but I am not sure how this represents the situation when the issue appears.

So, to reiterate, we have
```
$ python -c 'import torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pearu/git/pytorch/pytorch/torch/__init__.py", line 192, in <module>
    from torch._C import *
ImportError: /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so.1: version `OACC_2.0' not found (required by /home/pearu/git/pytorch/pytorch/torch/lib/libtorch_cpu.so)
$ ldd /home/pearu/git/pytorch/pytorch/torch/lib/libtorch_cpu.so
/home/pearu/git/pytorch/pytorch/torch/lib/libtorch_cpu.so: /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so.1: version `OACC_2.0' not found (required by /home/pearu/git/pytorch/pytorch/torch/lib/libtorch_cpu.so)
	linux-vdso.so.1 (0x00007ffd666ad000)
	libgomp.so.1 => /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so.1 (0x00007f2df66e3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2defdc7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2defbbf000)
	libgcc_s.so.1 => /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgcc_s.so.1 (0x00007f2df66bc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2def9bb000)
	libmkl_intel_lp64.so => /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libmkl_intel_lp64.so (0x00007f2deec9b000)
	libmkl_gnu_thread.so => /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libmkl_gnu_thread.so (0x00007f2decf3b000)
	libmkl_core.so => /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libmkl_core.so (0x00007f2de88fa000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2de855c000)
	libcudart.so.11.0 => /usr/local/cuda-11.0.3/lib64/libcudart.so.11.0 (0x00007f2de82de000)
	libc10.so => /home/pearu/git/pytorch/pytorch/torch/lib/libc10.so (0x00007f2df663a000)
	libstdc++.so.6 => /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libstdc++.so.6 (0x00007f2de8169000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2de7d78000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2df6593000)
```
The following
```
$ for f in $(find $CONDA_PREFIX -name 'lib*' -print); do test -n "$(nm $f 2> /dev/null | grep OACC_2.0)" && echo $f; done
/home/pearu/miniconda3/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/sysroot/lib64/libgomp.so
/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so
/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so.1.0.0
```
shows that symbols with version `OACC_2.0` are only defined in `libgomp.so` (that is symlink to `libgomp.so.1.0.0`, the GNU OpenMP library) but the `ldd` shows (see above) that `libtorch_cpu.so` picks up `libgomp.so.1` which is symlink to `libomp.so`, the LLVM OpenMP library.

It is not clear to me yet what processes in building pytorch brings in `OACC_2.0` symbols to `libtorch_cpu.so`.

**Comment by pearu** [comment]
Not sure if useful, the pytorch build shows:
```
- pytorch is compiling with OpenMP. 
OpenMP CXX_FLAGS: -fopenmp. 
OpenMP libraries: /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so;/home/pearu/miniconda3/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so.
-- Caffe2 is compiling with OpenMP. 
OpenMP CXX_FLAGS: -fopenmp. 
OpenMP libraries: /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so;/home/pearu/miniconda3/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so.
```

Btw, when `python -c 'import torch'` fails then
```
LD_PRELOAD=$CONDA_PREFIX/lib/libgomp.so python -c 'import torch'
```
succeeds (although using both `libgomp.so` and `libgomp.so.1` does not make sense as one corresponds to GNU and another to LLVM OpenMP).

**Comment by malfet** [comment]
@pearu you are building it in conda-forge, right? I yet not understand why, but look like this issue only manifests if built with conda-forge, where libgomp.so.1 contains a versioned symbol `acc_get_device_type@@OACC_2.0`

**Comment by pearu** [comment]
@malfet , no, the issue appears also in a local server when using conda-forge packages.
For the record, here's the output of your test:
```
$ printf "#include <cupti.h>\nint main() { uint32_t numMetrics=0; return cuptiGetNumMetrics(&numMetrics);}"|gcc -x c -  -I$CUDA_HOME/include/ -L$CUDA_HOME/lib64 -I$CUDA_HOME/extras/CUPTI/include -L$CUDA_HOME/extras/CUPTI/lib64 -Wl,--trace-symbol='acc_get_device_type' -lcupti_static -lm -lrt -ldl -lpthread -lgomp; readelf -s -W ./a.out |grep acc_get
/home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/local/cuda-11.0.3/extras/CUPTI/lib64/libcupti_static.a(libcupti_static_partial_mangled.o): reference to acc_get_device_type
/home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/../x86_64-conda-linux-gnu/sysroot/lib/../lib/libgomp.so: definition of acc_get_device_type
   273: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND acc_get_device_type@OACC_2.0 (7)
  4216: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND acc_get_device_type@@OACC_2.0

```

**Comment by pearu** [comment]
Notice that replacing `-lgomp` with `-L$CONDA_PREFIX/lib -lomp` works:
```
$ printf "#include <cupti.h>\nint main() { uint32_t numMetrics=0; return cuptiGetNumMetrics(&numMetrics);}"|gcc -x c -  -I$CUDA_HOME/include/ -L$CUDA_HOME/lib64 -I$CUDA_HOME/extras/CUPTI/include -L$CUDA_HOME/extras/CUPTI/lib64 -L$CONDA_PREFIX/lib -Wl,--trace-symbol='acc_get_device_type' -lcupti_static -lm -lrt -ldl -lpthread -lomp; readelf -s -W ./a.out |grep acc_get
/home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/local/cuda-11.0.3/extras/CUPTI/lib64/libcupti_static.a(libcupti_static_partial_mangled.o): reference to acc_get_device_type
   167: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND acc_get_device_type
 20597: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND acc_get_device_type
```

**Comment by pearu** [comment]
Here is a small reproducer script for the conda environment:
```
export PACKAGES="compilers"  # TEST 1 SUCCEEDS
export PACKAGES="compilers mkl"  # TEST 1 FAILS
export TESTENV=gomp-test

CONDA_BASE=$(conda info --base)
rm -rf $CONDA_BASE/envs/$TESTENV
source $CONDA_BASE/etc/profile.d/conda.sh
conda create -y -c conda-forge -n $TESTENV $PACKAGES
conda activate $TESTENV

echo "TEST 1"

printf "#include <openacc.h>\nint main() { acc_device_t dev_type = acc_get_device_type(); return acc_get_num_devices(dev_type)+90; }"|gcc -x c -  -Wl,--trace-symbol='acc_get_device_type' -lgomp -o ./test1 ; readelf -s -W ./test1 | grep acc_get
./test1
echo "-> $?"
```
that outputs:
```
TEST 1
/home/pearu/miniconda3/envs/gomp-test/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/cc2fk8qP.o: reference to acc_get_device_type
/home/pearu/miniconda3/envs/gomp-test/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/pearu/miniconda3/envs/gomp-test/bin/../x86_64-conda-linux-gnu/sysroot/lib/../lib/libgomp.so: definition of acc_get_device_type
     5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND acc_get_num_devices@OACC_2.0 (3)
     6: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND acc_get_device_type@OACC_2.0 (3)
    67: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND acc_get_num_devices@@OACC_2.0
    68: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND acc_get_device_type@@OACC_2.0
./test1: /home/pearu/miniconda3/envs/gomp-test/lib/libgomp.so.1: version `OACC_2.0' not found (required by ./test1)
-> 1
```
When not having `mkl` in the environment, the test1 succeeds (output is 91).

**Comment by seemethere** [comment]
Going to re-open this as we're still seeing this issue on CUDA 11.0 builds that utilize `conda-forge`:

https://app.circleci.com/pipelines/github/pytorch/pytorch/270308/workflows/b21fcb35-2ced-4100-8933-9612f26724a7/jobs/10719686

**Comment by seemethere** [comment]
Going to go ahead and remove this from the `1.8.0` milestone since we're moving forward with setting `USE_KINETO=0` for all conda packages.

See https://github.com/pytorch/builder/pull/650

**Comment by ilia-cher** [comment]
> Going to go ahead and remove this from the `1.8.0` milestone since we're moving forward with setting `USE_KINETO=0` for all conda packages.
> 
> See [pytorch/builder#650](https://github.com/pytorch/builder/pull/650)

https://github.com/pytorch/pytorch/pull/51818 should finally mitigate the issue

**Comment by Borda** [comment]
Hello, may I ask what is the recommendation for people who installed PT 1.8dev from the Conda channel pytoch-nightly, would just setting `USE_KINETO=0` solved the problem?

**Comment by pearu** [comment]
> Hello, may I ask what is the recommendation for people who installed PT 1.8dev from the Conda channel pytoch-nightly, would just setting `USE_KINETO=0` solved the problem?

No, it would not. `USE_KINETO=0` as a workaround would be needed for building pytorch. But I believe #51818 will fix this issue so that this workaround would not be needed anymore.

**Comment by pearu** [comment]
I confirm that the build of the current PT master when using conda environment produces an importable `torch`. Thanks, @malfet @ilia-cher !

**Comment by Borda** [comment]
sounds good, but is there. eta when this importable version will be available also on Conda nightly? :]

**Comment by malfet** [comment]
@Borda it should be available in nightly
