### ISSUE TITLE
Unclear error message thrown by stft if input and window arguments are on different devices

### ISSUE THREAD

**Issue by listener17** [pytorch/pytorch#51042]
Hi!

I have some code which was running fine on PyTorch 1.5. 

Today, I upgraded to latest n' greatest Pytorch 1.7.1, and now it's throwing at error.

"
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
"

* Is there a method to find out which tensors are on CPU and which ones are in GPU?
* Isn't it possible to simply continue running my code as it was before, by simply making use of tensors on both CPU and GPU?

cc @ngimel @mruberry @peterbell10 @walterddr

**Comment by bdhirsh** [comment]
Hi @listener17. If this seems like a regression from 1.5 to 1.7.1, can you post a minimum code repro with the full log output, as well as your environment information? (which you can get by running and pasting output from this script: https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py

As a side note, you can use `t.device()` to tell you the device that your tensor lives on.

**Comment by ngimel** [comment]
You can get a cpp stacktrace to see which op is throwing an error using `TORCH_SHOW_CPP_STACKTRACES=1 `

**Comment by listener17** [comment]
Hi @bdhirsh:

Here is the environment information:
```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
CMake version: version 3.5.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 440.64.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.7.1
[pip] torchaudio==0.7.0a0+a853dff
[pip] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchaudio                0.7.2                      py37    pytorch
[conda] torchvision               0.7.0                    pypi_0    pypi
```

And the output error log:


```
Loaded 81717 idx2slice items
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    main(opts)
  File "train.py", line 100, in main
    va_dloader=va_dloader, device=device)
  File "/mnt/deeplearning/project04/listener17/qrnn/gan/models/model.py", line 306, in train
    g_sc_loss, g_mag_loss = stft_criterion(Genh.squeeze(1), clean.squeeze(1))
  File "/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/deeplearning/project04/listener17/qrnn/gan/models/loss.py", line 94, in forward
    sc_loss, mag_loss = layer(fake_signals, true_signals)
  File "/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/deeplearning/project04/listener17/qrnn/gan/models/loss.py", line 71, in forward
    predicts_mag = stft(predicts, self.fft_size, self.hop_size, self.win_size, self.window)
  File "/mnt/deeplearning/project04/listener17/qrnn/gan/models/loss.py", line 15, in stft
    x_stft = torch.stft(x, fft_size, hop_size, win_size, window, return_complex=False)
  File "/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/functional.py", line 516, in stft
    normalized, onesided, return_complex)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by listener17** [comment]
Hi @bdhirsh:

You could try to run the standalone loss.py:
https://github.com/yanggeng1995/FB-MelGAN/blob/master/utils/loss.py

as CUDA_VISIBLE_DEVICES=1 python loss.py

You will get the error with PyTorch 1.7.1.

**Comment by ngimel** [comment]
The error is thrown from stft, cc @peterbell10 @mruberry
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Exception raised from compute_types at ../aten/src/ATen/TensorIterator.cpp:386 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7fb0789796ac in /private/home/ngimel/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7fb0789400b8 in /private/home/ngimel/pytorch/torch/lib/libc10.so)
frame #2: at::TensorIteratorBase::compute_types(at::TensorIteratorConfig const&) + 0x488 (0x7fb0888a4d18 in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #3: at::TensorIteratorBase::build(at::TensorIteratorConfig&) + 0x7e (0x7fb0888a7f5e in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #4: at::TensorIteratorBase::build_binary_op(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0xfb (0x7fb0888a856b in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #5: at::TensorIterator::binary_op(at::Tensor&, at::Tensor const&, at::Tensor const&) + 0x3d (0x7fb0888a867d in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #6: at::native::mul(at::Tensor const&, at::Tensor const&) + 0x57 (0x7fb088a1af37 in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x328cb85 (0x7fb07bc5db85 in /private/home/ngimel/pytorch/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x328cbf8 (0x7fb07bc5dbf8 in /private/home/ngimel/pytorch/torch/lib/libtorch_cuda.so)
frame #9: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, at::Tensor const&, at::Tensor const&) const + 0x10e (0x7fb08919192e in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #10: at::mul(at::Tensor const&, at::Tensor const&) + 0x5f (0x7fb088f46ecf in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x342c6c5 (0x7fb08aa6c6c5 in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x342ca18 (0x7fb08aa6ca18 in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #13: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, at::Tensor const&, at::Tensor const&) const + 0x10e (0x7fb08919192e in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #14: at::Tensor::mul(at::Tensor const&) const + 0x5f (0x7fb08946591f in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #15: at::native::stft(at::Tensor const&, long, c10::optional<long>, c10::optional<long>, at::Tensor const&, bool, c10::optional<bool>, c10::optional<bool>) + 0x1619 (0x7fb088c77ea9 in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x1d5e802 (0x7fb08939e802 in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #17: at::Tensor::stft(long, c10::optional<long>, c10::optional<long>, c10::optional<at::Tensor> const&, bool, c10::optional<bool>, c10::optional<bool>) const + 0x18e (0x7fb08949286e in /private/home/ngimel/pytorch/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x6fda94 (0x7fb09024ca94 in /private/home/ngimel/pytorch/torch/lib/libtorch_python.so)
frame #19: _PyMethodDef_RawFastCallKeywords + 0x264 (0x56250d600114 in /private/home/ngimel/opt/anaconda3/envs/pt/bin/python)
```

**Comment by ngimel** [comment]
If you replace this line https://github.com/yanggeng1995/FB-MelGAN/blob/master/utils/loss.py#L55 with 
```
self.register_buffer("window", torch.hann_window(win_size))
```
the script runs. Apparently torch.stft requires all arguments to be on the same device, and registering `window` as buffer moves window to cuda when `.cuda()` is called on the module. 
cc @peterbell10 for better error message from stft.

**Comment by peterbell10** [comment]
I'm pretty sure `stft` only historically accepted windows on the wrong device by accident. It comes from this window padding code:
https://github.com/pytorch/pytorch/blob/e400150c3b38107460156d4e45f964ed8c71952c/aten/src/ATen/native/SpectralOps.cpp#L243-L247

It uses `self.options()` instead of `windows.options()`, so could silently change device but also down-cast dtypes (which broke complex windows for example). However, if you have `len(window) == n_fft` then this padding code isn't called and the call would give this error message.

**Comment by ngimel** [comment]
@peterbell10 I agree that requiring window to be on the same device is reasonable behavior, and I don't think we should change it. I just think the error message could be better.

**Comment by listener17** [comment]
Thank you @ngimel.
I agree, error message could be better!

Thanks @peterbell10: it was good for me to know :-)

Please close the issue.

**Comment by ngimel** [comment]
I'll leave it open for error message improvement
