### ISSUE TITLE
Native code assert or hang on process exit with a torch.jit.script model on multi-GPU

### ISSUE THREAD

**Issue by nurpax** [pytorch/pytorch#51055]
## 🐛 Bug

Running a multi-GPU module with TorchScript on multiple GPUs can hang on process exit or trigger a native side assertion.

## To Reproduce

Run the below code sample on a V100 based DGX-1 system with multiple GPUs.  This may trigger also on other types of hardware, but a repro does seem to require multiple GPUs.

Note: the code has comments WORKS/HANGS/CRASHES.  The repro can be modified in a few different ways to make the bug go away.  Please see the code comments.  The currently copy&pasted version always either hung or crashed for me.

```
import torch
#----------------------------------------------------------------------------
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.img_mean = torch.nn.Parameter(torch.zeros([3, 1, 1]))
        self.img_std = torch.nn.Parameter(torch.zeros([3, 1, 1]))

    def forward(self, x):
        batch_size, channels, height, width = x.shape # [NCHW]
        # Emulate tf.image.resize_bilinear(x, [224, 224]), including the funky alignment.
        new_width, new_height = 224, 224
        #theta = [[1.0, 0.0, 1.0 / width - 1.0 / new_width], [0.0, 1.0, 1.0 / height - 1.0 / new_height]]
        #theta = torch.as_tensor(theta, dtype=x.dtype, device=x.device).unsqueeze(0).repeat([batch_size, 1, 1])
        theta = torch.eye(2, 3, device=x.device)
        theta[0, 2] += theta[0, 0] / width - theta[0, 0] / new_width
        theta[1, 2] += theta[1, 1] / height - theta[1, 1] / new_height
        theta = theta.to(x.dtype).unsqueeze(0).repeat([batch_size, 1, 1])
        grid = torch.nn.functional.affine_grid(theta, [batch_size, channels, new_height, new_width], align_corners=False)
        x = torch.nn.functional.grid_sample(x, grid, mode='bilinear', padding_mode='border', align_corners=False)

        # Scale dynamic range from [0,255] to [0,1].
        x /= 255

        # Normalize according to training data statistics.
        x = x - self.img_mean; x = x / self.img_std # HANGS/CRASHES
        #x -= self.img_mean; x /= self.img_std # WORKS
        #x = x.contiguous() - self.img_mean; x = x.contiguous() / self.img_std # WORKS
        return x

#----------------------------------------------------------------------------

def process_fn(rank):
    #module = MyModule() # WORKS
    module = torch.jit.script(MyModule()) # HANGS/CRASHES
    device = torch.device('cuda', rank)
    module = module.to(device)
    #if rank == 0: print(module.code)
    if rank == 0: print('rank 0 start')
    for _ in range(1000): module(torch.zeros([64, 3, 224, 224], device=device))
    if rank == 0: print('rank 0 end')

#----------------------------------------------------------------------------

def run():
    torch.multiprocessing.set_start_method('spawn')
    # nprocs 2, 4, 8 fail, no failure with nprocs=1
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=8)
```

Here's a couple of different stack traces that trigger with the repro case:

```
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Traceback (most recent call last):
  File "/mnt/nvr_results/jhellsten/gan/debug/00027-torch_jit_multiprocess_hang-hel-8gpu/src/dnnlib/submission/submit.py", line 338, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/mnt/nvr_results/jhellsten/gan/debug/00027-torch_jit_multiprocess_hang-hel-8gpu/src/torch_jit_multiprocess_hang.py", line 54, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=dnnlib.submit_config.num_gpus)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 247, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 205, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 146, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 7 terminated with signal SIGABRT
```

Another:

```
python: tpp.c:82: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Traceback (most recent call last):
  File "/mnt/debug/00028-torch_jit_multiprocess_hang-hel-8gpu/src/dnnlib/submission/submit.py", line 338, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/mnt/debug/00028-torch_jit_multiprocess_hang-hel-8gpu/src/torch_jit_multiprocess_hang.py", line 54, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=dnnlib.submit_config.num_gpus)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 247, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 205, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 146, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with signal SIGABRT
```

## Expected behavior

I'd expect the multi-GPU case to run to completion and exit (including a clean exit of all the subprocesses).

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

=============
== PyTorch ==
=============

NVIDIA Release 20.12 (build 17950526)
PyTorch Version 1.8.0a0+1606899

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED.

dnnlib: Running collect_env.farmmain() on fi-dgx01...
Collecting environment information...
PyTorch version: 1.8.0a0+1606899
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.8.0a0+1606899
[pip3] torchtext==0.9.0a0
[pip3] torchvision==0.9.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.19.2           py38h6163131_0  
[conda] numpy-base                1.19.2           py38h75fe3a5_0  
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.8.0a0+1606899          pypi_0    pypi
[conda] torchtext                 0.9.0a0                  pypi_0    pypi
[conda] torchvision               0.9.0a0                  pypi_0    pypi
dnnlib: Finished collect_env.farmmain() in 5s.
```

## Additional context

I tried on multiple pytorch container images.  The one used in this bug report should be available publicly.  This was with a few different pytorch versions but can confirm that I got the repro with also the standard pytorch 1.7.1 version when basing the install on cuda-runtime container images directly.

**Comment by nikithamalgifb** [comment]
Quick update: I was not able to reproduce the same issue, but however ran into this even with nprocs = 1
```
Traceback (most recent call last):
  File "critical.py", line 50, in <module>
    run()
  File "critical.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=1)
  File "/data/users/nikithamalgi/cuda_streams/pytorch/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/users/nikithamalgi/cuda_streams/pytorch/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data/users/nikithamalgi/cuda_streams/pytorch/torch/multiprocessing/spawn.py", line 139, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
```
I tried in both `module = torch.jit.script(MyModule())` and also `MyModule()`. But received the same error. 
@nurpax : Do we need any special setting?

**Comment by nurpax** [comment]
@nikithamalgifb I haven't seen this particular problem.  I'm running on Linux with Python 3.8.5.

I just tried this code again on our cluster and I can easily reproduce the hang on 4 or more GPUs.  You definitely ran with 2, 4 or more GPUs enabled?  2 GPUs took more tries to hang but from past testing 8 GPU hung or asserted every time for me.

I could try running this with a matching container image if you have a public docker image that I could try with.  Did you by any chance try Docker and the `nvcr.io/nvidia/pytorch:20.12-py3` image?

**Comment by nurpax** [comment]
I tried this again on another 4xGPU machine and can consistently get it to hang or crash with an assert.  Below you can find the exact source code (basically the same as above)  and the exact Docker invocation that I used:

`multigpu.py`:

```
import torch
#----------------------------------------------------------------------------
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.img_mean = torch.nn.Parameter(torch.zeros([3, 1, 1]))
        self.img_std = torch.nn.Parameter(torch.zeros([3, 1, 1]))

    def forward(self, x):
        batch_size, channels, height, width = x.shape # [NCHW]
        # Emulate tf.image.resize_bilinear(x, [224, 224]), including the funky alignment.
        new_width, new_height = 224, 224
        #theta = [[1.0, 0.0, 1.0 / width - 1.0 / new_width], [0.0, 1.0, 1.0 / height - 1.0 / new_height]]
        #theta = torch.as_tensor(theta, dtype=x.dtype, device=x.device).unsqueeze(0).repeat([batch_size, 1, 1])
        theta = torch.eye(2, 3, device=x.device)
        theta[0, 2] += theta[0, 0] / width - theta[0, 0] / new_width
        theta[1, 2] += theta[1, 1] / height - theta[1, 1] / new_height
        theta = theta.to(x.dtype).unsqueeze(0).repeat([batch_size, 1, 1])
        grid = torch.nn.functional.affine_grid(theta, [batch_size, channels, new_height, new_width], align_corners=False)
        x = torch.nn.functional.grid_sample(x, grid, mode='bilinear', padding_mode='border', align_corners=False)

        # Scale dynamic range from [0,255] to [0,1].
        x /= 255

        # Normalize according to training data statistics.
        x = x - self.img_mean; x = x / self.img_std # HANGS/CRASHES
        #x -= self.img_mean; x /= self.img_std # WORKS
        #x = x.contiguous() - self.img_mean; x = x.contiguous() / self.img_std # WORKS
        return x

#----------------------------------------------------------------------------

def process_fn(rank):
    #module = MyModule() # WORKS
    module = torch.jit.script(MyModule()) # HANGS/CRASHES
    device = torch.device('cuda', rank)
    module = module.to(device)
    #if rank == 0: print(module.code)
    if rank == 0: print('rank 0 start')
    for _ in range(1000): module(torch.zeros([64, 3, 224, 224], device=device))
    if rank == 0: print('rank 0 end')

#----------------------------------------------------------------------------

def run():
    torch.multiprocessing.set_start_method('spawn')
    # nprocs 2, 4, 8 fail, no failure with nprocs=1
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=4)

if __name__ == '__main__':
    run()
```

Invoke with docker (from a directory with the above multigpu.py file):

```
docker run -w /scratch -v `pwd`:/scratch --gpus all -it --rm nvcr.io/nvidia/pytorch:20.12-py3 python multigpu.py
```

Usually it hangs.  But it can also trigger an assertion, like this (direct copy&paste from my shell that just repro'd it):

```
=============
== PyTorch ==
=============

NVIDIA Release 20.12 (build 17950526)
PyTorch Version 1.8.0a0+1606899

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --ipc=host ...

rank 0 start
rank 0 end
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Traceback (most recent call last):
  File "multigpu.py", line 51, in <module>
    run()
  File "multigpu.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=4)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 247, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 205, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 146, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 3 terminated with signal SIGABRT
```

**Comment by nikithamalgifb** [comment]
I retried again and was able to run.

(pytorch) [nikithamalgi@devgpu227.prn2 /data/users/nikithamalgi/cuda_streams/pytorch] python repro.py 
rank 1 start
rank 0 start
rank 1 start
rank 0 end

My setup has only 2 devices and hence, I tried with nprocs = 2 and didn't see the hang. 
I'm going to try and see if I can find a machine with 4 or more GPU's

**Comment by nurpax** [comment]
I was able to get it to hang with nproc=2 pretty easily, not on every run but probably over 50% chance.

I already asked above but does it repro for you with Docker (as detailed above)?  Maybe I should try with a nightly PyTorch build too.

**Comment by nikithamalgifb** [comment]
No I haven't tried the docker setup yet. I am going to try out the Pytorch-1.7. Earlier Pytorch was 1.8, based on Master. Can you once try nightly-pytorch?

**Comment by nurpax** [comment]
I can try nightly-pytorch.  Somehow the conda install from the pytorch.org install page failed for me and pip install ran into some weird package conflicts.  I tried this on the NVIDIA base container, maybe the conda install doesn't work on that cleanly.

**Comment by nikithamalgifb** [comment]
Yeah, I am going through the same issue with pytorch-nightly. I am trying out pytoch-1.7. Hopefully that works!

**Comment by nikithamalgifb** [comment]
You may have to create a new conda environment. Just tried with both pytorch-nightly and pytorch-1.7. I see the issue only in 1.7 and not in the nightly. Can you give nightly a try? Although I could try only nprocs=2

**Comment by nurpax** [comment]
Consistently hangs for me with pytorch nightly and CUDA 10.2.  (Note: definitely have seen this on Pytorch 1.7 with CUDA 11 too).

```
root@10315eb09e27:/scratch# python multigpu.py
1.8.0.dev20210129
rank 0 start
rank 0 end
^CTraceback (most recent call last):
  File "multigpu.py", line 52, in <module>
    run()
  File "multigpu.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=2)
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 99, in join
    ready = multiprocessing.connection.wait(
  File "/opt/conda/envs/torch/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/torch/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

I was unable to install CUDA 11 nightly due to this error when running this 

`conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch-nightly`

in a new conda environment:

```
InvalidArchiveError('Error with archive /opt/conda/pkgs/pytorch-1.8.0.dev20210129-py3.8_cuda11.0.221_cudnn8.0.5_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nSeek failed')
```

So here's what I know so far:

- pytorch 1.7 (various versions of docker image), fail on both CUDA 10.2 and CUDA 11
- pytorch nightly w/ CUDA 10.2: hangs with nproc=2, hangs or asserts with nproc=4 or more
- unable to install nightly with CUDA 11

@nikithamalgifb When you say "see the issue", you mean the bug (assert or hang) repro'd for you with pytorch-1.7?

I can try more combinations if I just figure out how to get the nightlies to install.  Or if you have any other debugging tips, I'm happy to try and help.  This bug is pretty serious for us as we are nervous using torch.jit if it's unstable like this.

**Comment by nikithamalgifb** [comment]
Can you once try conda install pytorch torchvision torchaudio cudatoolkit=9.2 -c pytorch-nightly ? 

@nurpax : For me it was a hang( Took about ~10 mins). I did not see the assert.

**Comment by nurpax** [comment]
Did you mean cudatoolkit=10.2?  I can't get 9.2 to install and that feels pretty old.

@nikithamalgifb "Took about ~10 mins" -- what do you mean took ten minutes?  For it to hang?  Did you run the command in a loop for this to happen?  For me a single invocation hangs or asserts in a few seconds, or nothing bad happens and it exits cleanly.

Anyway, I'll try to repro with multiple different versions (both pytorch and base image).  I worked on it a bit over the weekend and with some containers it asserts/hangs easily, with some versions it works a lot better.  I just need to rerun all my experiments and summarize so that it's easier to follow what works and what doesn't.

**Comment by nikithamalgifb** [comment]
I know 9.2 is old. Just wanted to verify if it still hangs for you on 9.2. Please post your findings when you have them then.

**Comment by nurpax** [comment]
OK, sorry for the long comment.  I have repro'd this problem now on multiple different nightly and cuda versions.  I'll summarize first, the latter part of this comment will contain a Dockerfile that I used to build images, command line used to build it, and raw notes on what happened in the various versions.

A hang is the most common occurrence, but I was able to easily repro multiple assertions as well.  The assertions are similar to what I have posted in comments above.

Summary:

| Container      | Result |
|:---------------|:------|
| torchtest:9.2  | First try after image build with assert. |
| torchtest:10.2 | First try after image build hangs. |
| torchtest:11.0 | conda install fails with archive error, see raw notes below |
| nvcr.io/nvidia/pytorch:20.12-py3 | hangs but couldn't get the same assert now. |
| nvcr.io/nvidia/pytorch:20.11-py3 | asserts  |

Container tag for `torchtest` means what cudatoolkit version was used during pytorch installation.

This is what I used to build the containers:

```
(export CV=9.2 && docker build --build-arg CV=$CV -t torchtest:$CV . | tee buildlog.txt)
(export CV=10.2 && docker build --build-arg CV=$CV -t torchtest:$CV . | tee buildlog.txt)
(export CV=11.0 && docker build --build-arg CV=$CV -t torchtest:$CV . | tee buildlog.txt)
```

Dockerfile:

```
FROM nvidia/cuda:11.1-cudnn8-runtime
ARG CV
RUN echo Building for cudatoolkit-$CV

# FROM nvcr.io/nvidia/pytorch:20.12-py3

ENV PYTHONUNBUFFERED=1

RUN apt-get -y update && apt-get -y install wget
RUN cd /tmp && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash ./Miniconda3-latest-Linux-x86_64.sh -p /opt/conda -b

ENV PATH="/opt/conda/bin:${PATH}"

WORKDIR /app

RUN conda create --name torch

# Make RUN commands use the new environment:
# https://pythonspeed.com/articles/activate-conda-dockerfile/
SHELL ["conda", "run", "-n", "torch", "/bin/bash", "-c"]

# torchvision is NOT installed -- its installation fails
# for CUDA 9.2.  But the repro case does not use torchvision anyway.
RUN conda install pytorch cudatoolkit=$CV -c pytorch-nightly

# Entry point start bash in the torch conda environment created above.
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "torch", "bash"]
```

I run the bug repro like this  (replace image tag for different versions):

```
docker run -w /scratch -v `pwd`:/scratch --gpus all -it --rm torchtest:9.2
$ # in the container
$ python multigpu.py
```

Raw error notes:

`nvcr.io/nvidia/pytorch:20.11-py3` first try asserts:

```
root@920248813d7d:/scratch# python multigpu.py
torch version: 1.8.0a0+17f8c32
cuda version: 11.1
rank 0 start
rank 0 end
python: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Traceback (most recent call last):
  File "multigpu.py", line 53, in <module>
    run()
  File "multigpu.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=4)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 247, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 205, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 152, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT
```

`nvcr.io/nvidia/pytorch:20.12-py3` first try OK, second try gangs, ctrl-c:

```
root@1bb85110d6ed:/scratch# python multigpu.py
torch version: 1.8.0a0+1606899
cuda version: 11.1
rank 0 start
rank 0 end
^CTraceback (most recent call last):
  File "multigpu.py", line 53, in <module>
    run()
  File "multigpu.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=4)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 247, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 205, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 115, in join
    ready = multiprocessing.connection.wait(
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

`torchtest:10.2` hangs on first try, ctrl-c:

```
jhellsten@fi-gpu-station-02:~/dev$ docker run -w /scratch -v `pwd`:/scratch --gpus all -it --rm torchtest:10.2
pytroot@6bf974010f35:/scratch# python multigpu.py
torch version: 1.8.0.dev20210201
cuda version: 10.2
rank 0 start
rank 0 end
^CTraceback (most recent call last):
  File "multigpu.py", line 53, in <module>
    run()
  File "multigpu.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=4)
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 99, in join
    ready = multiprocessing.connection.wait(
  File "/opt/conda/envs/torch/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/torch/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

`torchtest:9.2` assertion on first try:

```
jhellsten@fi-gpu-station-02:~/dev$ docker run -w /scratch -v `pwd`:/scratch --gpus all -it --rm torchtest:9.2
root@720ab80fcf91:/scratch# python multigpu.py
torch version: 1.8.0.dev20210111
cuda version: 9.2
rank 0 start
rank 0 end
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Traceback (most recent call last):
  File "multigpu.py", line 53, in <module>
    run()
  File "multigpu.py", line 48, in run
    torch.multiprocessing.spawn(fn=process_fn, args=(), nprocs=4)
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with signal SIGABRT
root@720ab80fcf91:/scratch#
```


Archive error:

```
Step 11/12 : RUN conda install pytorch cudatoolkit=$CV -c pytorch-nightly
 ---> Running in e6ae216208ea
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['/bin/bash', '-c', 'conda install pytorch cudatoolkit=$CV -c pytorch-nightly']' command failed.  (See above for error)

InvalidArchiveError('Error with archive /opt/conda/pkgs/pytorch-1.8.0.dev20210201-py3.8_cuda11.0.221_cudnn8.0.5_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nSeek failed')
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
