### ISSUE TITLE
Random ctypes.ArgumentError: Don't know how to convert parameter 8

### ISSUE THREAD

**Issue by antspy** [pytorch/pytorch#5107]
- OS: Ubuntu 16.04 
- PyTorch version: 3.6 
- How you installed PyTorch (conda, pip, source): conda
- Python version: 0.3
- CUDA/cuDNN version: 8
- GPU models and configuration: Titan X (Pascal)

I am battling with a weird bug now. I start training a model, and everything works fine for a certain numbers of epochs. At what appears to be a random epoch, the following error occurs:

`ctypes.ArgumentError: argument 8: <class 'TypeError'>: Don't know how to convert parameter 8
`
This is the full traceback of the error:

```
Traceback (most recent call last):
    File "/home/code/train.py", line 100 in train
loss.backward()
  File "/home/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 335, in _do_backward
    result = super(NestedIOFunction, self)._do_backward(gradients, retain_variables)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 343, in backward
    result = self.backward_extended(*nested_gradients)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 325, in backward_extended
    grad_hx)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 401, in backward_grad
    ctypes.c_void_p(fn.reserve.data_ptr()), fn.reserve.size(0)
ctypes.ArgumentError: argument 8: <class 'TypeError'>: Don't know how to convert parameter 8

```

I encountered this bug the first time about a week ago, when a run was stopped after 10 epochs. 
I restarted it, and it went through all 15 epochs. Then I started another run with different parameters, and it ran for 5 epochs. I restarted it, and it stopped after 1 epoch. Now I am restarting it again, but I have no idea how to debug this! Does somebody have any idea?

**Comment by ezyang** [comment]
@antspy If you can make your training script available to us, we can try to repro it.

Alternately, there was recently a rewrite of the cuDNN RNN codepath in HEAD; you might try building a copy of PyTorch from source and see if it resolves your problem.

**Comment by zou3519** [comment]
@marcodel13 this can happen if there is a cudnn version mismatch. As ezyang mentioned, we rewrote the cuDNN RNN codepath recently. Upgrading to 0.4 should make the problem go away.
