### ISSUE TITLE
[JIT] Printing nodes in inlined_graph fails with seg fault

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#51100]
## 🐛 Bug

Printing the nodes in the `inlined_graph` of a traced model creates a segfault using a source build with commit `1.8.0a0+52ea372`.

## To Reproduce

Code snippet provided Alex Settle (thank you!) to reproduce this issue:
```python
import torch

class MyCell(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(4, 4)

    def forward(self, x, h):
        new_h = torch.tanh(self.linear(x) + h)
        return new_h, new_h

def main():
    my_cell = MyCell()
    my_cell.cuda().to(memory_format=torch.contiguous_format)
    loss_fn = torch.nn.L1Loss()
    optimizer = torch.optim.SGD(my_cell.parameters(), lr=0.01)
    x = torch.rand(3, 4, device='cuda')
    h = torch.rand(3, 4, device='cuda')
    target = torch.rand(3, 4, device='cuda')
    logits, _ = my_cell(x, h)
    loss = loss_fn(logits, target)
    loss.backward(retain_graph=True)
    optimizer.step()

    ## Capture a trace of the network
    traced_cell = torch.jit.trace(my_cell, (x,h))
    traced_loss = torch.jit.trace(loss_fn, (logits, target))
    print("Printing Graph view of  model")
    print(traced_cell.graph)
    print("Printing Inlinded Graph view of  model")
    print(traced_cell.inlined_graph)
    print("Printing Inlinded Graph view of  loss")
    print(traced_loss.inlined_graph)
    print ("Printing Params -> {}".format(my_cell.named_parameters()))
    for param in my_cell.named_parameters():
        print("Param -> {}".format(param))

    graph_nodes = traced_cell.graph.nodes()
    ## Printing each node in graph works
    print("Printing each Node in graph works")
    for node in graph_nodes:
        print ("Node -> {}".format(node))

    inlined_nodes = traced_cell.inlined_graph.nodes()
    ## Printing each node in graph works
    print("Printing each Node in inlinde graph - fails w/ segfault")
    for node in inlined_nodes:
        print ("Node -> {}".format(node))


if __name__ == "__main__":
    main()
```

Output from `gdb` (I removed the successfully printed graphs):
```
Printing Graph view of  model
graph(%self.1 : __torch__.MyCell,
[...]

Printing Inlinded Graph view of  model
graph(%self.1 : __torch__.MyCell,
[...]

Printing Inlinded Graph view of  loss
graph(%self : __torch__.torch.nn.modules.loss.L1Loss,
[...]

Printing Params -> <generator object Module.named_parameters at 0x7ffe370e0580>
Param -> ('linear.weight', Parameter containing:
tensor([[ 0.1594, -0.1016,  0.1722,  0.1352],
[...]
Param -> ('linear.bias', Parameter containing:
tensor([ 0.0376, -0.2151, -0.3131, -0.0835], device='cuda:0',
       requires_grad=True))
Printing each Node in graph works
Node -> %21 : __torch__.torch.nn.modules.linear.Linear = prim::GetAttr[name="linear"](%self.1)
[...]

Printing each Node in inlinde graph - fails w/ segfault
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffcce2e29b in pybind11::detail::type_caster_base<torch::jit::Node>::cast(torch::jit::Node const*, pybind11::return_value_policy, pybind11::handle) () from /workspace/src/pytorch/torch/lib/libtorch_python.so
(gdb) bt
#0  0x00007fffcce2e29b in pybind11::detail::type_caster_base<torch::jit::Node>::cast(torch::jit::Node const*, pybind11::return_value_policy, pybind11::handle) () from /workspace/src/pytorch/torch/lib/libtorch_python.so
#1  0x00007fffcce2fe74 in pybind11::cpp_function::initialize<pybind11::make_iterator<(pybind11::return_value_policy)6, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::Node*>(torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>)::{lambda(pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&)#2}, torch::jit::Node*, pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::return_value_policy>(pybind11::make_iterator<(pybind11::return_value_policy)6, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::Node*>(torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>)::{lambda(pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&)#2}&&, torch::jit::Node* (*)(pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /workspace/src/pytorch/torch/lib/libtorch_python.so
#2  0x00007fffccb03dcb in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /workspace/src/pytorch/torch/lib/libtorch_python.so
#3  0x00005555556d3f76 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x7ffff7a03cc0) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:742
#4  PyCFunction_Call (func=0x7ffff7a03cc0, args=<optimized out>, kwargs=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:772
#5  0x000055555569185f in _PyObject_MakeTpCall (callable=0x7ffff7a03cc0, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:159#6  0x00005555556dff64 in _PyObject_Vectorcall (kwnames=0x0, nargsf=1, args=0x7fffffffd6a8, callable=0x7ffff7a03cc0) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:125
#7  method_vectorcall (method=<optimized out>, args=0x0, nargsf=<optimized out>, kwnames=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/classobject.c:67
#8  0x00005555555d1f36 in _PyObject_Vectorcall (callable=0x7ffe371324c0, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#9  0x00005555556d2ec5 in _PyObject_FastCall () at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:147
#10 call_unbound (nargs=<optimized out>, args=<optimized out>, self=<optimized out>, func=<optimized out>, unbound=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/typeobject.c:1456
#11 call_method (nargs=0, args=0x0, name=0x5555558a9c20 <PyId___next__.15157>, obj=0x7ffe2e583ef0) at /tmp/build/80754af9/python_1599203911753/work/Objects/typeobject.c:1485
#12 slot_tp_iternext (self=0x7ffe2e583ef0) at /tmp/build/80754af9/python_1599203911753/work/Objects/typeobject.c:6729
#13 0x000055555571546c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3202
#14 0x00005555556df86b in function_code_fastcall (globals=<optimized out>, nargs=0, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:283
#15 _PyFunction_Vectorcall (func=<optimized out>, stack=0x7ffff7b1a5b0, nargsf=<optimized out>, kwnames=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:410
#16 0x0000555555652b84 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7b1a5b0, callable=0x7ffff7b631f0) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#17 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558eb100) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#18 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#19 0x00005555556dea92 in _PyEval_EvalCodeWithName (_co=0x7ffff79e8240, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2,
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#20 0x00005555556df754 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0,
    closure=0x0) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4327
#21 0x000055555576dedc in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:718
#22 0x000055555576df84 in run_eval_code_obj (co=0x7ffff79e8240, globals=0x7ffff7b7af80, locals=0x7ffff7b7af80) at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:1125
#23 0x00005555557a01f4 in run_mod (mod=<optimized out>, filename=<optimized out>, globals=0x7ffff7b7af80, locals=0x7ffff7b7af80, flags=<optimized out>, arena=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:1147
#24 0x00005555556686e1 in PyRun_FileExFlags (fp=0x5555558e8340, filename_str=<optimized out>, start=<optimized out>, globals=0x7ffff7b7af80, locals=0x7ffff7b7af80, closeit=1, flags=0x7fffffffdc78)
    at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:1063
#25 0x0000555555668ac6 in PyRun_SimpleFileExFlags (fp=0x5555558e8340, filename=<optimized out>, closeit=1, flags=0x7fffffffdc78) at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:428
#26 0x000055555566998b in pymain_run_file (cf=0x7fffffffdc78, config=0x5555558ea4c0) at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:387
#27 pymain_run_python (exitcode=0x7fffffffdc70) at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:612
#28 Py_RunMain () at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:691
#29 0x00005555557a2d19 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:1137
#30 0x00007ffff7dd10b3 in __libc_start_main (main=0x55555566a460 <main>, argc=2, argv=0x7fffffffde78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde68) at ../csu/libc-start.c:308
#31 0x0000555555732e93 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

## Environment

```
PyTorch version: 1.8.0a0+52ea372
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.8.0a0+52ea372
[pip3] torchtext==0.9.0a0
[pip3] torchvision==0.9.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] nomkl                     3.0                           0
[conda] numpy                     1.19.2           py38h6163131_0
[conda] numpy-base                1.19.2           py38h75fe3a5_0
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.8.0a0+52ea372           dev_0    <develop>
[conda] torchtext                 0.9.0a0                  pypi_0    pypi
[conda] torchvision               0.9.0a0                  pypi_0    pypi
```

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting, I think this is same as https://github.com/pytorch/pytorch/issues/50454 

I will close this one, please follow up in the other thread so that we can keep discussion in one place.
