### ISSUE TITLE
[TorchScript Usability] error message when invoking __init__ of module types inside TorchScript

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#51136]
## Problem description

Since subclasses of `torch.nn.Module` are treated as `TSInstanceClassType`, the `__init__()` method of such types is not considered TorchScript methods and thus they are not supposed to be invoked inside TorchScript. 

The error-message we issue now is counter-intuitive to users.

Test case: [test-module.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-module.py)

```
python test-module.py 
Eager:  5
Traceback (most recent call last):
  File "test-module.bad.py", line 23, in <module>
    m = torch.jit.script(MyModel(2))
  File "/data/users/pengwu/pytorch/torch/jit/_script.py", line 901, in script
    qualified_name = _qualified_name(obj)
  File "/data/users/pengwu/pytorch/torch/_jit_internal.py", line 870, in _qualified_name
    raise RuntimeError("Could not get name of python class object")
RuntimeError: Could not get name of python class object
```

## Desired behavior

The error message of "Could not get name of python class object" is really confusing. Can we say something like "cannot invoke __init__() method of subclasses of `torch.nn.Module` classes"?

Related to #50444

**Comment by gmagogsfm** [comment]
This is actually same as problem 3 in [#51140](https://github.com/pytorch/pytorch/issues/51140). Basically instances of classes cannot be scripted.

After fixing that, the error becomes:
```
Tried to access nonexistent attribute or method '__init__' of type 'Tensor'.:
  File "repro2.py", line 5
    def __init__(self, v):
        super().__init__()
        ~~~~~~~~~~~~~~ <--- HERE
        self.x = v
'TestModule.__init__' is being compiled since it was called from '__torch__.TestModule'
  File "repro2.py", line 19
    def doSomething(self, val: int) -> int:
        # error: should not invoke the constructor of module type
        myModel = TestModule(self.val)
                  ~~~~~~~~~~ <--- HERE
        return myModel(val)
'__torch__.TestModule' is being compiled since it was called from 'MyModel.doSomething'
  File "repro2.py", line 19
    def doSomething(self, val: int) -> int:
        # error: should not invoke the constructor of module type
        myModel = TestModule(self.val)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return myModel(val)
```

There is still room for improvement, ie. when recursively compiling classes we should explicitly check whether class is a subclass of `nn.Module`

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
