### ISSUE TITLE
[TorchScript Usability] Earlier type checking needed for interface type

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#51137]
## Problem description

Interface types  do not allow to define constructors, but the error message complains about return type of `__init__` not annotated

Test case: [test-interface.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-interface.py)
```
> python test-interface.py 
Traceback (most recent call last):
  File "test-interface.py", line 4, in <module>
    class TestInterface(torch.nn.Module):
  File "/data/users/pengwu/pytorch/torch/jit/_script.py", line 1043, in interface
    torch._C._jit_script_interface_compile(
RuntimeError: 
interface declarations must have a return type annotated.:
  File "test-interface.py", line 7
    def __init__(self):
    ~~~~~~~~~~~~~~~~~~~
        pass
        ~~~~ <--- HERE
```

## Desired behavior

The error message should simply say that interface types cannot define `__init__` methods

Related to #50444

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
