### ISSUE TITLE
[TorchScript Usability] Non-intuitive error messages for user errors 

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#51140]
Test case 1: [test-enum-mystic-error-message.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-enum-mystic-error-message.py) 

The test failed because `em_fn` was annotated as `@torch.script.jit`, but also supplied as input to `torch.script.jit(em_fn)`. The error message is not helpful to users. Instead, JIT should just tolerate `@torch.script.jit` instead of issuing errors. Similarly for modules that are annotated as `@torch.script.jit`but is also supplied as input to `torch.jit.trace(...)`
```
> python test-enum-mystic-error-message.py 
Traceback (most recent call last):
  File "test-enum-mystic-error-message.py", line 18, in <module>
    m = torch.jit.script(enum_fn)
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 936, in script
    ast = get_jit_def(obj, obj.__name__)
AttributeError: 'torch._C.ScriptFunction' object has no attribute '__name__'
```

Test case 2: [test-enum-annotated.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-enum-annotated.py)

The test failed because `enum` class is annotated as `@torch.jit.script` and is treated as a custom class
```
> python test-enum-annotated.py Traceback (most recent call last):
  File "test-enum-annotated.py", line 7, in <module>
    class Color(Enum):
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 913, in script
    raise RuntimeError(
RuntimeError: TorchScript classes must be new-style classes. Please inherit from 'object'.
```

Test case 3: [test-tuple.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-tuple.py)

Not exactly sure what is wrong with the example, perhaps it is related to decorators or passing a non-module object to `trace.jit.script()`?

```
> python test-tuple.py 
Traceback (most recent call last):
  File "test-tuple.py", line 14, in <module>
    m = torch.jit.script(MyClass(2, (1,2)))
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 901, in script
    qualified_name = _qualified_name(obj)
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/_jit_internal.py", line 793, in _qualified_name
    raise RuntimeError("Could not get name of python class object")
RuntimeError: Could not get name of python class object
```

Related to #50444

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
