### ISSUE TITLE
RuntimeError: Exporting the operator numpy_T to ONNX opset version 9, 10, 11 & 12 is not supported

### ISSUE THREAD

**Issue by DJ543** [pytorch/pytorch#51183]
## 🐛 Bug

RuntimeError: Exporting the operator numpy_T to ONNX opset version 9, 10, 11 & 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

## To Reproduce

i have a error message

Traceback (most recent call last):
  File "model2onnx.py", line 69, in <module>
    main()
  File "model2onnx.py", line 63, in main
    onnx_export(model, args.output_path, input)
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "model2onnx.py", line 51, in onnx_export
    torch_onnx.export(model, dummy_input, output_dir,
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 930, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator numpy_T to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

## Expected behavior

torch_onnx.export(model, dummy_input, output_dir,
                      input_names=input_names, output_names=output_names,opset_version=12)

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 450.102.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torch2trt==0.1.0
[pip3] torchgeometry==0.1.2
[pip3] torchvision==0.8.1
[conda] cudatoolkit               10.0.130                      0
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torch2trt                 0.1.0                    pypi_0    pypi
[conda] torchgeometry             0.1.2                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by DJ543** [comment]
I located the bug in:

head=dict(
type='AMSoftmaxClsHead',
num_classes=7,
in_channels=512,
loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
topk=(1,),
margin=0.15
)

**Comment by malfet** [comment]
Thank you for reporting. We will accept PR that fixes it.

**Comment by ynjiun** [comment]
has this bug been fixed? how to download the fix? Thanks.

**Comment by deutschmn** [comment]
@ynjiun Could you provide example code of how to fully reproduce the issue? Which model are you trying to convert to ONNX?

**Comment by deutschmn** [comment]
I had the same problem because there was a `.T` call on a tensor in my model. Replacing it by `.transpose(0, 1)` fixed it.

**Comment by siboehm** [comment]
Minimally reproducible example:
```python
import torch

# create a simple module
class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.linear = torch.nn.Linear(300, 10)

    def forward(self, x):
        return x @ self.linear.weight.T + self.linear.bias

dummy_input = torch.randn(1, 300)
 # making sure that the shapes work out
print(MyModule()(dummy_input))

torch.onnx.export(MyModule(), dummy_input, "test.onnx")
```

Returns the following traceback (running on current master):
<details>

```python-traceback
Traceback (most recent call last):
  File "/Users/siboehm/repos/pytorch/aten_transpose_issue.py", line 16, in <module>
    torch.onnx.export(MyModule(), dummy_input, "test.onnx")
  File "/Users/siboehm/repos/pytorch/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/Users/siboehm/repos/pytorch/torch/onnx/utils.py", line 162, in export
    _export(
  File "/Users/siboehm/repos/pytorch/torch/onnx/utils.py", line 1071, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/Users/siboehm/repos/pytorch/torch/onnx/utils.py", line 728, in _model_to_graph
    graph = _optimize_graph(
  File "/Users/siboehm/repos/pytorch/torch/onnx/utils.py", line 307, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/Users/siboehm/repos/pytorch/torch/onnx/__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Users/siboehm/repos/pytorch/torch/onnx/utils.py", line 1418, in _run_symbolic_function
    raise symbolic_registry.UnsupportedOperatorError(
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::numpy_T to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

```

</details>

**Comment by siboehm** [comment]
Minimally reproducible example:
```python
import torch

# create a simple module
class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()

    def forward(self, x):
        return x.T

dummy_input = torch.randn(1, 300)
torch.onnx.export(MyModule(), dummy_input, "aten_transpose_issue.onnx", opset_version=13, verbose=True)
```

fails on current master with:
<details>

```python-traceback
ONNX graph being constructed during exception:
graph(%0 : Float(1, 300, strides=[300, 1], requires_grad=0, device=cpu)):
  return ()

Torch IR graph at exception: graph(%0 : Float(1, 300, strides=[300, 1], requires_grad=0, device=cpu)):
  %3 : Float(300, 1, strides=[1, 300], requires_grad=0, device=cpu) = aten::numpy_T(%0) # /scratch/pytorch/aten_transpose_issue.py:9:0
  return (%3)

Traceback (most recent call last):
  File "/scratch/pytorch/aten_transpose_issue.py", line 12, in <module>
    torch.onnx.export(MyModule(), dummy_input, "aten_transpose_issue.onnx", opset_version=13, verbose=True)
  File "/scratch/pytorch/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/scratch/pytorch/torch/onnx/utils.py", line 162, in export
    _export(
  File "/scratch/pytorch/torch/onnx/utils.py", line 1071, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/scratch/pytorch/torch/onnx/utils.py", line 728, in _model_to_graph
    graph = _optimize_graph(
  File "/scratch/pytorch/torch/onnx/utils.py", line 307, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/scratch/pytorch/torch/onnx/__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/scratch/pytorch/torch/onnx/utils.py", line 1418, in _run_symbolic_function
    raise symbolic_registry.UnsupportedOperatorError(
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::numpy_T to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

</details>
