### ISSUE TITLE
[numpy] torch.ceil and torch.floor don't support integer inputs while Numpy does

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51199]
```python
>>> import torch
>>> import numpy as np
>>> torch.__version__
'1.8.0a0+1935880'
>>> t = torch.randint(1, (3,))
>>> np.floor(t.numpy())
array([0., 0., 0.])
>>> np.ceil(t.numpy())
array([0., 0., 0.])
>>> torch.floor(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "floor" "_vml_cpu" not implemented for 'Long'
>>> torch.ceil(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "ceil" "_vml_cpu" not implemented for 'Long'
```

**Comment by malfet** [comment]
Thank you for reporting. Seems pretty simple to implement
