### ISSUE TITLE
Error of running

### ISSUE THREAD

**Issue by LucasColas** [pytorch/pytorch#51275]
## 🐛 Bug

Hello,
I wanted to use `torch.jit.load()`. However I got en error when I tried to run my script.

## To Reproduce

1.import torch
2.create a file
3.Use torch.jit.load(<your_file>)

```
with open("weights", "wb") as f:
    f.write(weights)


model_object = torch.jit.load("weights")
```

## Expected behavior

I expected a return of a ScriptModule. 

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): 

> pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

 - Python version: 3.6.5
 - CUDA/cuDNN version: None
 - GPU models and configuration: AMD Radeon Vega Graphics

**Comment by malfet** [comment]
@LucasColas can you actually print the actual error you are seeing? Also, what is 'weights' variable in your example? Tensor?

**Comment by LucasColas** [comment]
Hello,
weights is a variable which contains weights traced of a neural network. It's not a tensor. It is only bytes.

Here is my error :

> Traceback (most recent call last):
>   File "neural_net.py", line 56, in <module>
>     torch.load("weights.pt")
>   File "/home/psycle/Documents/Psycle-Research/tests_networks/env/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
>     return torch.jit.load(opened_file)
>   File "/home/psycle/Documents/Psycle-Research/tests_networks/env/lib/python3.6/site-packages/torch/jit/_serialization.py", line 164, in load
>     cu, f.read(), map_location, _extra_files
> RuntimeError: Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. 'aten::empty_strided' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
> 
> CPU: registered at /pytorch/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
> BackendSelect: registered at /pytorch/build/aten/src/ATen/BackendSelectRegister.cpp:761 [kernel]
> Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
> AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:7974 [autograd kernel]
> Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_0.cpp:9341 [kernel]
> Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
> Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
> VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
