### ISSUE TITLE
[ROCm] test_linalg.py failures after hipMAGMA integration

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#51303]
As requested by @malfet in https://github.com/pytorch/pytorch/pull/51238, this issue captures the newly failing tests after integrating hipMAGMA into the ROCm PyTorch build.  These tests were decorated with `@skipCUDAIfRocm` to proceed with the PR.  Debugging these skipped tests is the next step, and captured here with this issue.

Attached is full log.  Copied here is the summary.
[test_linalg.log](https://github.com/pytorch/pytorch/files/5890132/test_linalg.log)

```
ERROR: test_lobpcg_basic_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_addbmm_cuda_bfloat16 (__main__.TestLinalgCUDA)
FAIL: test_addmv_cuda_float16 (__main__.TestLinalgCUDA)
FAIL: test_baddbmm_cuda_bfloat16 (__main__.TestLinalgCUDA)
FAIL: test_bmm_cuda_bfloat16 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_det_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_det_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_det_logdet_slogdet_batched_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lobpcg_ortho_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_unpack_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_norm_dtype_cuda (__main__.TestLinalgCUDA)
FAIL: test_norm_fro_2_equivalence_old_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_svd_lowrank_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_tensorinv_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
```

cc @jeffdaily @sunway513

**Comment by jeffdaily** [comment]
Additional test failures identified.  https://github.com/pytorch/pytorch/pull/51915 skips them for now.

test_ops.py
```
ERROR: test_fn_grad_linalg_inv_cuda_complex128 (__main__.TestGradientsCUDA)
ERROR: test_fn_grad_linalg_inv_cuda_float64 (__main__.TestGradientsCUDA)
ERROR: test_fn_grad_linalg_slogdet_cuda_complex128 (__main__.TestGradientsCUDA)
ERROR: test_fn_grad_linalg_slogdet_cuda_float64 (__main__.TestGradientsCUDA)
ERROR: test_fn_grad_linalg_solve_cuda_complex128 (__main__.TestGradientsCUDA)
ERROR: test_fn_grad_linalg_solve_cuda_float64 (__main__.TestGradientsCUDA)
ERROR: test_fn_gradgrad_linalg_inv_cuda_complex128 (__main__.TestGradientsCUDA)
ERROR: test_fn_gradgrad_linalg_inv_cuda_float64 (__main__.TestGradientsCUDA)
ERROR: test_fn_gradgrad_linalg_slogdet_cuda_complex128 (__main__.TestGradientsCUDA)
ERROR: test_fn_gradgrad_linalg_slogdet_cuda_float64 (__main__.TestGradientsCUDA)
ERROR: test_fn_gradgrad_linalg_solve_cuda_complex128 (__main__.TestGradientsCUDA)
ERROR: test_fn_gradgrad_linalg_solve_cuda_float64 (__main__.TestGradientsCUDA)
FAIL: test_variant_consistency_jit_linalg_inv_cuda_complex128 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_inv_cuda_complex64 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_inv_cuda_float32 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_inv_cuda_float64 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_slogdet_cuda_complex128 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_slogdet_cuda_complex64 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_slogdet_cuda_float32 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_slogdet_cuda_float64 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_solve_cuda_complex128 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_solve_cuda_complex64 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_solve_cuda_float32 (__main__.TestCommonCUDA)
FAIL: test_variant_consistency_jit_linalg_solve_cuda_float64 (__main__.TestCommonCUDA)
```

test_autograd.py
```
ERROR: test_det_batched_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_det_batched_distinct_singular_values_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_det_batched_symmetric_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_det_batched_symmetric_pd_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_det_batched_symmetric_psd_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_inverse_batched_complex_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_inverse_batched_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_logdet_batched_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_logdet_batched_distinct_singular_values_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_logdet_batched_symmetric_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_logdet_batched_symmetric_pd_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_lu_square_batch_no_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_lu_square_batch_with_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_lu_square_many_batches_no_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_lu_square_many_batches_with_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_matrix_power_n=-2_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_broadcast_A_complex_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_broadcast_A_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_broadcast_b_complex_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_broadcast_b_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_complex_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_dims_complex_cuda (__main__.TestAutogradDeviceTypeCUDA)
ERROR: test_solve_batched_dims_cuda (__main__.TestAutogradDeviceTypeCUDA)
```

test_linalg
```
FAIL: test_cholesky_inverse_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_cholesky_inverse_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_cholesky_inverse_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_cholesky_inverse_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_slogdet_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_slogdet_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_slogdet_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_slogdet_cuda_float64 (__main__.TestLinalgCUDA)
```

**Comment by jeffdaily** [comment]
One more test failure identified.  Skipped by #52064.

```
======================================================================
ERROR: test_norm_matrix_degenerate_shapes_cuda_float32 (__main__.TestLinalgCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 887, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 572, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 572, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test/test_linalg.py", line 1358, in test_norm_matrix_degenerate_shapes
    run_test_case(input, ord, dim, keepdim, ord in error_ords)
  File "test/test_linalg.py", line 1339, in run_test_case
    result = torch.linalg.norm(input, ord, dim, keepdim)
RuntimeError: magma: The value of work_size(-9223372036854775808) is too large to fit into a magma_int_t (4 bytes)

----------------------------------------------------------------------
```
