### ISSUE TITLE
TorchScript class compilation failure with pybind11-2.6.2

### ISSUE THREAD

**Issue by aclex** [pytorch/pytorch#51379]
## 🐛 Bug

Now that `master` seems to return to upstream [pybind11](https://github.com/pybind/pybind11), it turns out, that some of the TorchScript-enabled classes fail to be compiled during the run. I tried my best to find something similar here in issues, but failed.

## To Reproduce
The simplest way to reproduce it that I found is just importing [timm](https://github.com/rwightman/pytorch-image-models) of recent versions (0.3.4 will do). Steps to reproduce the behavior:

1. `pip install timm`
1. `import timm` in Python interpreter.
1. The output is something like that:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/.local/lib/python3.8/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/ray/.local/lib/python3.8/site-packages/timm/models/__init__.py", line 1, in <module>
    from .cspnet import *
  File "/home/ray/.local/lib/python3.8/site-packages/timm/models/cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "/home/ray/.local/lib/python3.8/site-packages/timm/models/helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "/home/ray/.local/lib/python3.8/site-packages/timm/models/layers/__init__.py", line 4, in <module>
    from .anti_aliasing import AntiAliasDownsampleLayer
  File "/home/ray/.local/lib/python3.8/site-packages/timm/models/layers/anti_aliasing.py", line 22, in <module>
    class DownsampleJIT(object):
  File "/usr/lib/python3.8/site-packages/torch/jit/_script.py", line 924, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/usr/lib/python3.8/site-packages/torch/jit/_script.py", line 64, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
TypeError: Object of type 'module' is not an instance of 'function'
```

With pybind11<=2.6.1 it works just fine (without any output). I guess it's somehow connected with pybind/pybind11#2701 mentioned in the release 2.6.2.

## Environment

PyTorch version: 1.7.0a0+57bffc3
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Gentoo/Linux (x86_64)
GCC version: (Gentoo 9.3.0-r2 p4) 9.3.0
Clang version: 11.0.0
CMake version: version 3.17.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.7.0a0
[pip3] torchvision==0.8.0a0
[conda] Could not collect

## Additional context

Pytorch compiled using [ebuild here](https://github.com/aclex/pytorch-ebuild).

**Comment by gmagogsfm** [comment]
> ## 🐛 Bug
> Now that `master` seems to return to upstream [pybind11](https://github.com/pybind/pybind11), it turns out, that some of the TorchScript-enabled classes fail to be compiled during the run. I tried my best to find something similar here in issues, but failed.
> 
> ## To Reproduce
> The simplest way to reproduce it that I found is just importing [timm](https://github.com/rwightman/pytorch-image-models) of recent versions (0.3.4 will do). Steps to reproduce the behavior:
> 
> 1. `pip install timm`
> 2. `import timm` in Python interpreter.
> 3. The output is something like that:
> 
> ```shell
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ray/.local/lib/python3.8/site-packages/timm/__init__.py", line 2, in <module>
>     from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
>   File "/home/ray/.local/lib/python3.8/site-packages/timm/models/__init__.py", line 1, in <module>
>     from .cspnet import *
>   File "/home/ray/.local/lib/python3.8/site-packages/timm/models/cspnet.py", line 20, in <module>
>     from .helpers import build_model_with_cfg
>   File "/home/ray/.local/lib/python3.8/site-packages/timm/models/helpers.py", line 17, in <module>
>     from .layers import Conv2dSame, Linear
>   File "/home/ray/.local/lib/python3.8/site-packages/timm/models/layers/__init__.py", line 4, in <module>
>     from .anti_aliasing import AntiAliasDownsampleLayer
>   File "/home/ray/.local/lib/python3.8/site-packages/timm/models/layers/anti_aliasing.py", line 22, in <module>
>     class DownsampleJIT(object):
>   File "/usr/lib/python3.8/site-packages/torch/jit/_script.py", line 924, in script
>     _compile_and_register_class(obj, _rcb, qualified_name)
>   File "/usr/lib/python3.8/site-packages/torch/jit/_script.py", line 64, in _compile_and_register_class
>     torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
> TypeError: Object of type 'module' is not an instance of 'function'
> ```
> 
> With pybind11<=2.6.1 it works just fine (without any output). I guess it's somehow connected with [pybind/pybind11#2701](https://github.com/pybind/pybind11/pull/2701) mentioned in the release 2.6.2.
> 
> ## Environment
> PyTorch version: 1.7.0a0+57bffc3
> Is debug build: False
> CUDA used to build PyTorch: None
> ROCM used to build PyTorch: N/A
> 
> OS: Gentoo/Linux (x86_64)
> GCC version: (Gentoo 9.3.0-r2 p4) 9.3.0
> Clang version: 11.0.0
> CMake version: version 3.17.4
> 
> Python version: 3.8 (64-bit runtime)
> Is CUDA available: False
> CUDA runtime version: No CUDA
> GPU models and configuration: No CUDA
> Nvidia driver version: No CUDA
> cuDNN version: No CUDA
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.19.4
> [pip3] pytorch-sphinx-theme==0.0.24
> [pip3] torch==1.7.0a0
> [pip3] torchvision==0.8.0a0
> [conda] Could not collect
> 
> ## Additional context
> Pytorch compiled using [ebuild here](https://github.com/aclex/pytorch-ebuild).
> 
> cc @gmagogsfm

Hi Alexey, I have a few questions, could you clarify?

What do you mean by "master returns to upstream pybind11"? AFAIK, we never had our fork of pybind11.

"that some of the TorchScript-enabled classes fail to be compiled during the run" -> what does "the run" refer to? CI?

**Comment by aclex** [comment]
@gmagogsfm yes, sure, sorry for the delay.

> What do you mean by "master returns to upstream pybind11"? AFAIK, we never had our fork of pybind11.

Yeah, I mean using the custom implementation of pybind11 for the 1.7.1 release mentioned at #48312 and returning back to the upstream at recent 6f3aa58. I also should add here, that the exact pybind11 submodule revision currently used may be earlier, than the version 2.6.2, it's just my voluntary try to compile Pytorch against pybind11-2.6.2, so this issue is kind of preliminary.

> "that some of the TorchScript-enabled classes fail to be compiled during the run" -> what does "the run" refer to? CI?

Unfortunately, I'm not too much into internal mechanics of TorchScript, but here I mean it fails right at the import of certain Python classes, which is easily reproduced with the steps I've mentioned above. Maybe I'm wrong, but, as I see it, the compilation procedure is triggered at this moment.

**Comment by gmagogsfm** [comment]
> @gmagogsfm yes, sure, sorry for the delay.
> 
> > What do you mean by "master returns to upstream pybind11"? AFAIK, we never had our fork of pybind11.
> 
> Yeah, I mean using the custom implementation of pybind11 for the 1.7.1 release mentioned at #48312 and returning back to the upstream at recent [6f3aa58](https://github.com/pytorch/pytorch/commit/6f3aa58d8023757ce7eabeee48fa86f8ed6308b8). I also should add here, that the exact pybind11 submodule revision currently used may be earlier, than the version 2.6.2, it's just my voluntary try to compile Pytorch against pybind11-2.6.2, so this issue is kind of preliminary.
> 
> > "that some of the TorchScript-enabled classes fail to be compiled during the run" -> what does "the run" refer to? CI?
> 
> Unfortunately, I'm not too much into internal mechanics of TorchScript, but here I mean it fails right at the import of certain Python classes, which is easily reproduced with the steps I've mentioned above. Maybe I'm wrong, but, as I see it, the compilation procedure is triggered at this moment.

Thanks for the clarification. Does this mean if you use current specified submodule revision, `import torch` still works?

**Comment by aclex** [comment]
@gmagogsfm
> Does this mean if you use current specified submodule revision, import torch still works?

I've just double checked it, so here's the exact situation:
1. `import torch` works in any cases I tried.
2. `import timm` (given it's already pre-installed) works fine with custom pybind11 implementation (used in PyTorch-1.7.1 release), but fails due to the described failure in TorchScript code in current PyTorch `master`, which references pybind/pybind11@8e5d3d2, while the check was apparently added at pybind/pybind11@30eb39e which is also contained in recent pybind11-2.6.2 release.

**Comment by eellison** [comment]
cc @malfet who did some work related to pybind compatibility

**Comment by acxz** [comment]
Just gonna add another datapoint to this issue:

Reproducible example:
```python
import torch
@torch.jit.script
def fn(tensor1, tensor2, value, out):
    torch.addcmul(tensor1, tensor2, value, out)
```

Output:
```bash
Traceback (most recent call last):
  File "/home/acxz/test.py", line 17, in <module>
    def fn(tensor1, tensor2, value, out):
  File "/usr/lib/python3.9/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
TypeError: Object of type 'module' is not an instance of 'function'
```
PyTorch version: 1.7.1
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Arch Linux
GCC version: 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.2

Python version: 3.9.1

Versions of relevant libraries:
pybind11: 2.6.2

Possible relevant lines of code:
https://github.com/pytorch/pytorch/blob/58eb23378f2a376565a66ac32c93a316c45b6131/torch/jit/_script.py#L994

https://github.com/pytorch/pytorch/blob/705fa7e9642ee5ba34f4214497149b11e39eb420/torch/csrc/jit/python/script_init.cpp#L1353

https://github.com/pytorch/pytorch/blob/705fa7e9642ee5ba34f4214497149b11e39eb420/torch/csrc/jit/python/script_init.cpp#L376

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
