### ISSUE TITLE
[numpy] `round` and `trunc` not supported for Integral Type while Python and NumPy supports them

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51406]
```python
>>> import torch
>>> import numpy
>>> import math
>>> t = torch.ones(3, dtype=torch.int)
>>> numpy.trunc(t.numpy())
array([1., 1., 1.])
>>> numpy.round(t.numpy())
array([1, 1, 1], dtype=int32)
>>> math.trunc(1)
1
>>> round(1)
1
>>> torch.trunc(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "trunc" "_vml_cpu" not implemented for 'Int'
>>> torch.round(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "round" "_vml_cpu" not implemented for 'Int'
```

cc: @mruberry

**Comment by firstprayer** [comment]
This is because "round" and "trunc" are configured to only apply for float/double types 

https://github.com/pytorch/pytorch/blob/de8cd6b20118f5c7d060c41e87bf6b90f7e20eed/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp#L726

What's the motivation for supporting these operators for integers? It seems to be no-op given that they are already rounded/truncated.

**Comment by mruberry** [comment]
> What's the motivation for supporting these operators for integers? It seems to be no-op given that they are already rounded/truncated.

We try to be consistent with Python and NumPy.
