### ISSUE TITLE
[TorchScript Usability] Type-checker too strict for Optional type initialization pattern

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#51563]
**To reproduce**

Test case: [test-optional.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-optional.py)

```
python test-optional.py 
Eager:  1
Traceback (most recent call last):
  File "test-optional.py", line 10, in <module>
    scripted_fn = torch.jit.script(fn)
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
Variable 'b' previously has type None but is now being assigned to a value of type int
:
  File "test-optional.py", line 6
    b = None
    if a>100:
        b = 1
        ~ <--- HERE
    return b
```

**Desired behavior**

This requires a collaboration between auto-inferencer and type-checker. In this case, the auto-inferencer should deduce that `b` is of type `Optional[int]` (by joining possible types of `b` along all possible execution path.

Related to #50444

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
