### ISSUE TITLE
[docs] FractionalMaxPool2d : _random_samples arg is present in signature but undocumented.

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51623]
## 📚 Documentation

`_random_samples` arg is present in signature but undocumented. Not sure if it is private argument based on the name, but since it is part of the public API, I think it should have some detail about what it does.

https://pytorch.org/docs/master/generated/torch.nn.FractionalMaxPool2d.html?highlight=fractionalmax

![Screenshot from 2021-02-03 12-42-52](https://user-images.githubusercontent.com/19503980/106711506-a0a22e00-661d-11eb-93d7-3dd47ee24eb9.png)

**Comment by kshitij12345** [comment]
Also `fractional_max_pool2d` is not documented. Not sure if it should be a separate issue of its own.
https://pytorch.org/docs/master/nn.functional.html

**Comment by zou3519** [comment]
Based on the name my guess is that the attribute is private. What say you, @jbschlosser?

**Comment by jbschlosser** [comment]
Agree that the intention is for the attribute to be private, as indicated by the preceding underscore. This is consistent with what is done elsewhere (e.g. the undocumented `_weight` in [nn.EmbeddingBag](https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html)).

That said, my opinion is that we shouldn't have undocumented inputs in the public API, underscore or not. But I think that should be done consistently, so I suggest opening a broader issue for discussion on whether we should document these across all modules.

> Also fractional_max_pool2d is not documented. Not sure if it should be a separate issue of its own.

Nice catch! I agree there should be a separate issue for documenting it.

**Comment by kshitij12345** [comment]
Another question, because it is a private argument is it fine to not check that both the Tensors are on same device? Or should there be checks for that?

Sample Snippet:
```python
>>> import torch
>>> x = torch.randn(1, 2, 7, 7, requires_grad=True, device='cpu')
>>> samples = x.new(1, 2, 2).uniform_()
>>> torch.nn.functional.fractional_max_pool2d(x.cuda(), (2, 2), output_size=(3, 3), _random_samples=samples)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/tensor.py", line 193, in __repr__
    return torch._tensor_str._str(self)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/_tensor_str.py", line 383, in _str
    return _str_intern(self)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/_tensor_str.py", line 358, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/_tensor_str.py", line 242, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/_tensor_str.py", line 90, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: an illegal memory access was encountered
>>> torch.nn.functional.fractional_max_pool2d(x, (2, 2), output_size=(3, 3), _random_samples=samples.cuda())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by heitorschueroff** [comment]
FractionalMaxPool3D is also not documented. What is intent of the _random_samples?
