### ISSUE TITLE
DISABLED test_single_threaded_rref_owner (__main__.ProcessGroupProcessGroupAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#51657]
https://app.circleci.com/pipelines/github/pytorch/pytorch/268750/workflows/17646620-4305-4220-88dd-a4b19b66d69d/jobs/10632737/steps

```
Feb 03 09:04:39 ======================================================================
Feb 03 09:04:39 ERROR [62.097s]: test_single_threaded_rref_owner (__main__.ProcessGroupProcessGroupAgentRpcTestWithSpawn)
Feb 03 09:04:39 ----------------------------------------------------------------------
Feb 03 09:04:39 Traceback (most recent call last):
Feb 03 09:04:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 282, in wrapper
Feb 03 09:04:39     self._join_processes(fn)
Feb 03 09:04:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 399, in _join_processes
Feb 03 09:04:39     self._check_return_codes(elapsed_time)
Feb 03 09:04:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 435, in _check_return_codes
Feb 03 09:04:39     raise RuntimeError(error)
Feb 03 09:04:39 RuntimeError: Processes 0 exited with error code 10
```

```
Feb 03 08:56:11   test_single_threaded_rref_owner (__main__.ProcessGroupProcessGroupAgentRpcTestWithSpawn) ... WARNING:torch.distributed.rpc.api:RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Feb 03 08:56:11 WARNING:torch.distributed.rpc.api:RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Feb 03 08:56:11 WARNING:torch.distributed.rpc.api:RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Feb 03 08:56:11 WARNING:torch.distributed.rpc.api:RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend.
Feb 03 08:57:11 ERROR:root:Caught exception: 
Feb 03 08:57:11 Traceback (most recent call last):
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Feb 03 08:57:11     fn()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 3956, in test_single_threaded_rref_owner
Feb 03 08:57:11     self.assertEqual(2 * (torch.zeros(2, 2) + i), futs[i].wait())
Feb 03 08:57:11 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Feb 03 08:57:11 exiting process with exit code: 10
Feb 03 08:57:11 ERROR:root:Caught exception: 
Feb 03 08:57:11 Traceback (most recent call last):
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Feb 03 08:57:11     fn()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 3975, in test_single_threaded_rref_owner
Feb 03 08:57:11     dist.barrier()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2427, in barrier
Feb 03 08:57:11     work.wait()
Feb 03 08:57:11 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:21219
Feb 03 08:57:11 exiting process with exit code: 10
Feb 03 08:57:11 ERROR:root:Caught exception: 
Feb 03 08:57:11 Traceback (most recent call last):
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Feb 03 08:57:11     fn()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 3975, in test_single_threaded_rref_owner
Feb 03 08:57:11     dist.barrier()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2427, in barrier
Feb 03 08:57:11     work.wait()
Feb 03 08:57:11 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:5782
Feb 03 08:57:11 exiting process with exit code: 10
Feb 03 08:57:11 ERROR:root:Caught exception: 
Feb 03 08:57:11 Traceback (most recent call last):
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
Feb 03 08:57:11     fn()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 3975, in test_single_threaded_rref_owner
Feb 03 08:57:11     dist.barrier()
Feb 03 08:57:11   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2427, in barrier
Feb 03 08:57:11     work.wait()
Feb 03 08:57:11 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:52905
Feb 03 08:57:11 exiting process with exit code: 10
Feb 03 08:57:11 Process 0 terminated with exit code 10, terminating remaining processes.
Feb 03 08:57:11 ERROR (62.097s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
Closing this out to re-enable the test to capture better debugging output which might help in resolving this flaky issue. Please re-open this when a new flaky test is found.

**Comment by garymm** [comment]
I believe this test flaked again [here](https://app.circleci.com/pipelines/github/pytorch/pytorch/324113/workflows/36d0197e-ed6e-4397-9b8f-473c791d583a/jobs/13561591). I don't have permissions to re-open this issue. Shall I open another one?
