### ISSUE TITLE
Torch DataLoader fails to reraise error from sqlalchemy.

### ISSUE THREAD

**Issue by Erotemic** [pytorch/pytorch#51663]
## 🐛 Bug

The `reraise` functionality in torch.utils.data.dataloader seems to break when used in combination with sqlalchemy. 

## To Reproduce

I have a Dataset that uses an sqlalchemy engine to lookup item information. I'm still working out how to do that correctly, but in the process it seems like torch is not handling errors from sqlalchemy correctly: 

```
  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 2 required positional arguments: 'params' and 'orig'
```

When I dug into this I printed the `msg` before this TypeError was raised and got

```
'Caught DatabaseError in DataLoader worker process 1.\nOriginal Traceback (most recent call last):\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1311, in fetchmany\n    l = self.process_rows(self._fetchmany_impl(size))\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1224, in _fetchmany_impl\n    return self.cursor.fetchmany(size)\nsqlite3.DatabaseError: database disk image is malformed\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop\n    data = fetcher.fetch(index)\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File "debug_memory.py", line 66, in __getitem__\n    sample = self.data.load_item(idx)\n  File "/home/joncrall/code/ndsampler/ndsampler/coco_sampler.py", line 321, in load_item\n    sample = self.load_positive(index, pad=pad,\n  File "/home/joncrall/code/ndsampler/ndsampler/coco_sampler.py", line 373, in load_positive\n    sample = self.load_sample(tr, pad=pad, window_dims=window_dims,\n  File "/home/joncrall/code/ndsampler/ndsampler/coco_sampler.py", line 588, in load_sample\n    sample = self._load_slice(tr, window_dims, pad, padkw)\n  File "/home/joncrall/code/ndsampler/ndsampler/coco_sampler.py", line 696, in _load_slice\n    tr_ = self._infer_target_attributes(tr)\n  File "/home/joncrall/code/ndsampler/ndsampler/coco_sampler.py", line 656, in _infer_target_attributes\n    if aid in self.dset.anns:\n  File "/home/joncrall/code/scriptconfig/scriptconfig/dict_like.py", line 56, in __contains__\n    return key in self.keys()\n  File "/home/joncrall/code/kwcoco/kwcoco/coco_sql_dataset.py", line 328, in keys\n    chunk = result.fetchmany(300)\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1316, in fetchmany\n    self.connection._handle_dbapi_exception(\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception\n    util.raise_(\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_\n    raise exception\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1311, in fetchmany\n    l = self.process_rows(self._fetchmany_impl(size))\n  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1224, in _fetchmany_impl\n    return self.cursor.fetchmany(size)\nsqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed\n(Background on this error at: http://sqlalche.me/e/13/4xp6)\n'
```

So I'm doing something wrong where my sqlite database is malformed (likely writing to it over multiple workers). But the issue with torch is that it is not reraising the error correctly. This seems related to: https://github.com/celery/celery/issues/5057

## Expected behavior

I would expect the error hit by sqlalchemy to be raised. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
(py38) joncrall@Ooo:~/code/netharn/dev$ python collect_env.py
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.17.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 450.102.04
cuDNN version: /home/joncrall/.local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] adabelief-pytorch==0.0.5
[pip3] numpy==1.19.5
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.7.1
[pip3] torch-cluster==1.5.7
[pip3] torch-geometric==1.6.1
[pip3] torch-liberator==0.0.5
[pip3] torch-optimizer==0.0.1a16
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.7
[pip3] torchvision==0.8.2
[conda] adabelief-pytorch         0.0.5                    pypi_0    pypi
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     1.7.1                    pypi_0    pypi
[conda] torch-cluster             1.5.7                    pypi_0    pypi
[conda] torch-geometric           1.6.1                    pypi_0    pypi
[conda] torch-liberator           0.0.5                     dev_0    <develop>
[conda] torch-optimizer           0.0.1a16                 pypi_0    pypi
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torch-sparse              0.6.7                    pypi_0    pypi
[conda] torchvision               0.8.2                    pypi_0    pypi
```

**Comment by ejguan** [comment]
It's the error that we fail to re-construct the exception.
I have seen a PR working on it #40437

**Comment by Erotemic** [comment]
@ejguan That looks like the issue. I'm glad there are eyes on it. This can be closed now or once  #40437 is merged.
