### ISSUE TITLE
Using LAPACK on Pi4 (64Bit Raspberry Pi OS RAM 8GB)

### ISSUE THREAD

**Issue by hokaso** [pytorch/pytorch#51700]
I currently run Raspberry Pi OS 64Bit Beta on my Pi4.
I'm almost done getting stable-baselines3[extra] running, but I get a runtime error when Torch tries to calculate a qr decomposition using LAPACK.
Here is what I have been doing (using a virtualenv with python3.7) on the Pi:

pip install numpy scikit-build
pip install torch-1.8.0a0-cp37-cp37m-linux_aarch64.whl
sudo apt install libssl-dev libjpeg-dev sudo apt install gfortran libopenblas-dev liblapack-dev
sudo apt install libatlas-base-dev # for better performance, optional
sudo apt install -y python3-scipy
pip install stable-baselines3[extra]

A small PyTorch test script ran successfully, but this example crashed at the line
model = PPO(...) https://github.com/DLR-RM/stable-baselines3#example The error message was

>>> model = PPO('MlpPolicy', env, verbose=1)
Using cpu device
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/official_get_started/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 120, in __init__
    self._setup_model()
  File "/home/pi/official_get_started/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 123, in _setup_model
    super(PPO, self)._setup_model()
  File "/home/pi/official_get_started/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 119, in _setup_model
    **self.policy_kwargs  # pytype:disable=not-instantiable
  File "/home/pi/official_get_started/lib/python3.7/site-packages/stable_baselines3/common/policies.py", line 406, in __init__
    self._build(lr_schedule)
  File "/home/pi/official_get_started/lib/python3.7/site-packages/stable_baselines3/common/policies.py", line 502, in _build
    module.apply(partial(self.init_weights, gain=gain))
  File "/home/pi/official_get_started/pytorch/torch/nn/modules/module.py", line 445, in apply
    module.apply(fn)
  File "/home/pi/official_get_started/pytorch/torch/nn/modules/module.py", line 445, in apply
    module.apply(fn)
  File "/home/pi/official_get_started/pytorch/torch/nn/modules/module.py", line 446, in apply
    fn(self)
  File "/home/pi/official_get_started/lib/python3.7/site-packages/stable_baselines3/common/policies.py", line 197, in init_weights
    nn.init.orthogonal_(module.weight, gain=gain)
  File "/home/pi/official_get_started/pytorch/torch/nn/init.py", line 447, in orthogonal_
    q, r = torch.qr(flattened)
RuntimeError: qr: LAPACK library not found in compilation

What should I change in order to fix this issue? It seems like installing liblapack-dev wasn't enough?

Could it be that the pytorch wheel I compiled comes without Lapack, since I installed Lapack afterwards? But then why isn't torch.qr(..) using another implementation?

https://raspberrypi.stackexchange.com/questions/117550/using-lapack-on-pi4-64bit-raspberry-pi-os

cc @ezyang @seemethere @malfet @walterddr @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @IvanYashchuk

**Comment by hokaso** [comment]
I've got a way to work out: 
1. https://github.com/ljk53/pytorch-rpi download torch-1.7.0a0-cp38-cp38-linux_aarch64.whl and pip3 install
2. apt install libopenblas-dev
3. success!
