### ISSUE TITLE
torch.fx.symbolic_trace fails on torch.arange with input-dependent size

### ISSUE THREAD

**Issue by slayton58** [pytorch/pytorch#51803]
## 🐛 Bug

I'm trying to use torch.fx.symbolic_trace to trace an `arange` call where the first argument to `arange` is part of the size of the input tensor:
```
l = x.size(1)
torch.arange(l, dtype=torch.long, device='cuda')
```
And it fails.

## To Reproduce

```
import torch
from torch.fx import symbolic_trace
def test(x):
    l = x.size(1)
    return torch.arange(l, dtype=torch.long, device='cuda')
traced = symbolic_trace(test)
```
Trace:
```
Traceback (most recent call last):
  File "repro.py", line 6, in <module>
    traced = symbolic_trace(test)
  File "/opt/pytorch/pytorch/torch/fx/symbolic_trace.py", line 606, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/pytorch/pytorch/torch/fx/symbolic_trace.py", line 355, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "repro.py", line 5, in test
    return torch.arange(l, dtype=torch.long, device='cuda')
TypeError: arange() received an invalid combination of arguments - got (Proxy, device=str, dtype=torch.dtype), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 *
```

## Expected behavior

Method is successfully traced

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+28c5d90
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
$GPUs
Nvidia driver version: 455.34
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0a0+28c5d90
[pip3] torchvision==0.9.0a0+ced96a0
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] nomkl                     3.0                           0
[conda] numpy                     1.19.2           py38h6163131_0
[conda] numpy-base                1.19.2           py38h75fe3a5_0
[conda] torch                     1.8.0a0+28c5d90           dev_0    <develop>
[conda] torchvision               0.9.0a0+ced96a0          pypi_0    pypi
```

**Comment by juancamilog** [comment]
related bug, it also fails in the device depends on the input

    import torch
    from torch.fx import symbolic_trace
    def test(x):
        return torch.arange(10, dtype=torch.float, device=x.device)
    traced = symbolic_trace(test)

**Comment by MHGL** [comment]
https://github.com/DeepVAC/deepvac/issues/116

**Comment by alexander-soare** [comment]
From the [torch fx docs](https://pytorch.org/docs/stable/fx.html) (Miscellanea section) "(deterministic) tensor constructors are currently not traceable (if they have dynamic inputs)". Still, I'd like to know if there's some workaround. I'm new to FX but could we somehow customise the `Tracer` to handle this specific sort of situation as and when needed?

**Comment by rjkat** [comment]
Late to the party but found this thread when I ran into the same problem. I think I may have found a workaround:

```python
l = x.size(1)
workaround = x.new_ones(l).cumsum(0) - 1
```

**Comment by aksenventwo** [comment]
I found that there is a common method to solve many similar problems, converting the function into module and using `is_leaf_module` feature

```python
import torch

from torch.fx import Tracer
from torch.fx import symbolic_trace
from torch.fx.graph_module import GraphModule


class CustomedTracer(Tracer):
    """
    ``Tracer`` is the class that implements the symbolic tracing functionality
    of ``torch.fx.symbolic_trace``. A call to ``symbolic_trace(m)`` is equivalent
    to ``Tracer().trace(m)``.
    This Tracer override the ``is_leaf_module`` function to make symbolic trace
    right in some cases.
    """
    def __init__(self, *args, customed_leaf_module=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.customed_leaf_module = customed_leaf_module

    def is_leaf_module(self, m: torch.nn.Module, module_qualified_name : str) -> bool:
        """
        A method to specify whether a given ``nn.Module`` is a "leaf" module.
        Leaf modules are the atomic units that appear in
        the IR, referenced by ``call_module`` calls. By default,
        Modules in the PyTorch standard library namespace (torch.nn)
        are leaf modules. All other modules are traced through and
        their constituent ops are recorded, unless specified otherwise
        via this parameter.
        Args:
            m (Module): The module being queried about
            module_qualified_name (str): The path to root of this module. For example,
                if you have a module hierarchy where submodule ``foo`` contains
                submodule ``bar``, which contains submodule ``baz``, that module will
                appear with the qualified name ``foo.bar.baz`` here.
        """
        if self.customed_leaf_module and isinstance(m, self.customed_leaf_module):
            return True
        return m.__module__.startswith('torch.nn') and not isinstance(m, torch.nn.Sequential)



class ArangeForFx(torch.nn.Module):
    def forward(self, x):
        return torch.arange(x)



class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.arange = ArangeForFx()

    def forward(self, x):
        l = x.size(1)
        return self.arange(l).to(dtype=torch.long, device=x.device)


model = Net()

tracer = CustomedTracer(customed_leaf_module=(ArangeForFx,))
graph = tracer.trace(model)
name = model.__class__.__name__ if isinstance(model, torch.nn.Module) else model.__name__
traced = GraphModule(tracer.root, graph, name)

print(traced.code)
```

```shell
def forward(self, x):
    size = x.size(1)
    arange_1 = self.arange(size);  size = None
    getattr_1 = x.device;  x = None
    to = arange_1.to(dtype = torch.int64, device = getattr_1);  arange_1 = getattr_1 = None
    return to
```

**Comment by lixhk** [comment]
good job, but modify many

**Comment by lixhk** [comment]
Good job, but usually modify many,  because  people define network usually not consider tx tracer,  if  there is no hyperparameter involved,(not weights or bias), they prefer to use the function not module.   


The best method, there is an official method of automatic replacement, to convert the `function` to `module` and set `is_leaf_module` feature.

**Comment by larenzhang** [comment]
> I found that there is a common method to solve many similar problems, converting the function into module and using `is_leaf_module` feature
> 
> ```python
> import torch
> 
> from torch.fx import Tracer
> from torch.fx import symbolic_trace
> from torch.fx.graph_module import GraphModule
> 
> 
> class CustomedTracer(Tracer):
>     """
>     ``Tracer`` is the class that implements the symbolic tracing functionality
>     of ``torch.fx.symbolic_trace``. A call to ``symbolic_trace(m)`` is equivalent
>     to ``Tracer().trace(m)``.
>     This Tracer override the ``is_leaf_module`` function to make symbolic trace
>     right in some cases.
>     """
>     def __init__(self, *args, customed_leaf_module=None, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.customed_leaf_module = customed_leaf_module
> 
>     def is_leaf_module(self, m: torch.nn.Module, module_qualified_name : str) -> bool:
>         """
>         A method to specify whether a given ``nn.Module`` is a "leaf" module.
>         Leaf modules are the atomic units that appear in
>         the IR, referenced by ``call_module`` calls. By default,
>         Modules in the PyTorch standard library namespace (torch.nn)
>         are leaf modules. All other modules are traced through and
>         their constituent ops are recorded, unless specified otherwise
>         via this parameter.
>         Args:
>             m (Module): The module being queried about
>             module_qualified_name (str): The path to root of this module. For example,
>                 if you have a module hierarchy where submodule ``foo`` contains
>                 submodule ``bar``, which contains submodule ``baz``, that module will
>                 appear with the qualified name ``foo.bar.baz`` here.
>         """
>         if self.customed_leaf_module and isinstance(m, self.customed_leaf_module):
>             return True
>         return m.__module__.startswith('torch.nn') and not isinstance(m, torch.nn.Sequential)
> 
> 
> 
> class ArangeForFx(torch.nn.Module):
>     def forward(self, x):
>         return torch.arange(x)
> 
> 
> 
> class Net(torch.nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.arange = ArangeForFx()
> 
>     def forward(self, x):
>         l = x.size(1)
>         return self.arange(l).to(dtype=torch.long, device=x.device)
> 
> 
> model = Net()
> 
> tracer = CustomedTracer(customed_leaf_module=(ArangeForFx,))
> graph = tracer.trace(model)
> name = model.__class__.__name__ if isinstance(model, torch.nn.Module) else model.__name__
> traced = GraphModule(tracer.root, graph, name)
> 
> print(traced.code)
> ```
> 
> ```shell
> def forward(self, x):
>     size = x.size(1)
>     arange_1 = self.arange(size);  size = None
>     getattr_1 = x.device;  x = None
>     to = arange_1.to(dtype = torch.int64, device = getattr_1);  arange_1 = getattr_1 = None
>     return to
> ```
> 
> **In order to avoid passing `customed_leaf_module` each time, I upgrade it.**
> 
> ```python
> import torch
> 
> from torch.fx import Tracer
> from torch.fx import symbolic_trace
> from torch.fx.graph_module import GraphModule
> 
> 
> class CustomedTracer(Tracer):
>     """
>     ``Tracer`` is the class that implements the symbolic tracing functionality
>     of ``torch.fx.symbolic_trace``. A call to ``symbolic_trace(m)`` is equivalent
>     to ``Tracer().trace(m)``.
>     This Tracer override the ``is_leaf_module`` function to make symbolic trace
>     right in some cases.
>     """
>     def __init__(self, *args, customed_leaf_module=None, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.customed_leaf_module = customed_leaf_module
> 
>     def is_leaf_module(self, m: torch.nn.Module, module_qualified_name : str) -> bool:
>         """
>         A method to specify whether a given ``nn.Module`` is a "leaf" module.
>         Leaf modules are the atomic units that appear in
>         the IR, referenced by ``call_module`` calls. By default,
>         Modules in the PyTorch standard library namespace (torch.nn)
>         are leaf modules. All other modules are traced through and
>         their constituent ops are recorded, unless specified otherwise
>         via this parameter.
>         Args:
>             m (Module): The module being queried about
>             module_qualified_name (str): The path to root of this module. For example,
>                 if you have a module hierarchy where submodule ``foo`` contains
>                 submodule ``bar``, which contains submodule ``baz``, that module will
>                 appear with the qualified name ``foo.bar.baz`` here.
>         """
>         if self.customed_leaf_module and isinstance(m, self.customed_leaf_module):
>             return True
>         
>         if hasattr(m, '_is_leaf_module') and m._is_leaf_module:
>             return True
> 
>         return m.__module__.startswith('torch.nn') and not isinstance(m, torch.nn.Sequential)
> 
> 
> 
> class ArangeForFx(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self._is_leaf_module = True
> 
>     def forward(self, x):
>         return torch.arange(x)
> 
> 
> 
> class Net(torch.nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.arange = ArangeForFx()
> 
>     def forward(self, x):
>         l = x.size(1)
>         return self.arange(l).to(dtype=torch.long, device=x.device)
> 
> 
> model = Net()
> # tracer = CustomedTracer(customed_leaf_module=(ArangeForFx,))
> 
> tracer = CustomedTracer()
> graph = tracer.trace(model)
> name = model.__class__.__name__ if isinstance(model, torch.nn.Module) else model.__name__
> traced = GraphModule(tracer.root, graph, name)
> 
> print(traced.code)
> ```
> 
> Even the control flow, you can also successfully trace:
> 
> ```python
> import torch
> 
> from torch.fx import Tracer
> from torch.fx import symbolic_trace
> from torch.fx.graph_module import GraphModule
> 
> 
> class CustomedTracer(Tracer):
>     """
>     ``Tracer`` is the class that implements the symbolic tracing functionality
>     of ``torch.fx.symbolic_trace``. A call to ``symbolic_trace(m)`` is equivalent
>     to ``Tracer().trace(m)``.
>     This Tracer override the ``is_leaf_module`` function to make symbolic trace
>     right in some cases.
>     """
>     def __init__(self, *args, customed_leaf_module=None, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.customed_leaf_module = customed_leaf_module
> 
>     def is_leaf_module(self, m: torch.nn.Module, module_qualified_name : str) -> bool:
>         """
>         A method to specify whether a given ``nn.Module`` is a "leaf" module.
>         Leaf modules are the atomic units that appear in
>         the IR, referenced by ``call_module`` calls. By default,
>         Modules in the PyTorch standard library namespace (torch.nn)
>         are leaf modules. All other modules are traced through and
>         their constituent ops are recorded, unless specified otherwise
>         via this parameter.
>         Args:
>             m (Module): The module being queried about
>             module_qualified_name (str): The path to root of this module. For example,
>                 if you have a module hierarchy where submodule ``foo`` contains
>                 submodule ``bar``, which contains submodule ``baz``, that module will
>                 appear with the qualified name ``foo.bar.baz`` here.
>         """
>         if self.customed_leaf_module and isinstance(m, self.customed_leaf_module):
>             return True
>         
>         if hasattr(m, '_is_leaf_module') and m._is_leaf_module:
>             return True
> 
>         return m.__module__.startswith('torch.nn') and not isinstance(m, torch.nn.Sequential)
> 
> 
> 
> class ArangeForFx(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self._is_leaf_module = True
> 
>     def forward(self, x):
>         return torch.arange(x)
> 
> 
> class TestIf(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self._is_leaf_module = True
>     
>     def forward(self, x):
>         if x.sum() > 0:
>             return x + 1
>         else:
>             return x - 1
> 
> 
> 
> class Net(torch.nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.test_if = TestIf()
> 
>     def forward(self, x):
>         return self.test_if(x)
> 
> 
> model = Net()
> tracer = CustomedTracer()
> graph = tracer.trace(model)
> name = model.__class__.__name__ if isinstance(model, torch.nn.Module) else model.__name__
> traced = GraphModule(tracer.root, graph, name)
> 
> y = traced(torch.zeros(5) - 1)
> print(y) # tensor([-2., -2., -2., -2., -2.])
> 
> y = traced(torch.zeros(5) + 1)
> print(y) # tensor([2., 2., 2., 2., 2.])
> ```


 when  I use the above code,  I have following question:
 for j in self.arrange(seq_len):
  File "/usr/local/lib/python3.7/site-packages/torch/fx/proxy.py", line 248, in __iter__
    return self.tracer.iter(self)
  File "/usr/local/lib/python3.7/site-packages/torch/fx/proxy.py", line 161, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors
