### ISSUE TITLE
[jit] Keyword-arg expansion for constants

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#51808]
## 🐛 Bug
`self.kwargs` is declared by typing to be immutable and is also practically immutable because of  `MappingProxyType` (no one holds a reference to the original dict and the dict is declared to contain only immutable objects). Theoretically, jit should be able to identify (based on typing) that `self.kwargs` is a constant and convert `**self.kwargs` to `dim=1`. Unfortunately,  that doesn't happen and `torch.jit.frontend.NotSupportedError: keyword-arg expansion is not supported` is raised.
```py
from types import MappingProxyType
from typing import Mapping, Final

import torch

class Test(torch.nn.Module):
    def __init__(self, **kwargs):
        super().__init__()
        self.kwargs: Final[Mapping[str, int]] = MappingProxyType(kwargs)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x.sum(**self.kwargs)


model = Test(dim=1)
model = torch.jit.script(model)
```

**Comment by twoertwein** [comment]
a simpler/more frequent use case might be:

```py
def forward(x: torch.Tensor) -> torch.Tensor
    device_dtype = {'device': x.device, 'dtype': x.dtype}  # assume device_dtype is used more than one time
    return x + some_tensor.to(**device_dtype)
```
In this case the keys are fixed but the values might change.

**Comment by gmagogsfm** [comment]
@penguinwu @Lilyjjo  another example of constant folding module instance attribute to improve usability

**Comment by penguinwu** [comment]
@gmagogsfm @Lilyjjo This case applies to non-module objects too. It is about taking advantage of the semantics of `Final` in our IR transformation. But the basic mechanism utilized is the same, so we can accommodate both cases in one implementation.

**Comment by twoertwein** [comment]
a slightly more general comment: If I'm interpreting the python docs about `Final` correctly, `Final` does not mean that an object is constant (unless it is immutable and all of its sub-objects), it only means that the object cannot be re-assigned (`id(...)` does not change). I think pytorch seems to interpret it differently: A `Final[List]` (should be able to append to it) seems to become a `Tuple` when jit'ed. I assume that might be an intentional choice to allow more optimizations to take place. It might be good to more prominently mention that difference in the docs.


```py
from typing import Final, List

import torch


class Test(torch.nn.Module):
    xs: Final[List[torch.Tensor]]  # needs to be declared here, it is not being picked up in __init__
    def __init__(self, **kwargs):
        super().__init__()
        self.xs = []

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        self.xs.append(x)
        return self.xs.pop()


model = Test()
model = torch.jit.script(model)
```
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = torch.jit.script(model)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 897, in script
    return torch.jit._recursive.create_script_module(
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 410, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 304, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Tried to access nonexistent attribute or method 'append' of type 'Tuple[]'.:
  File "test.py", line 13
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        self.xs.append(x)
        ~~~~~~~~~~~~~~ <--- HERE
        return self.xs.pop()
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
