### ISSUE TITLE
methods decorated with torch.jit._overload_method are not accessible

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#51835]
## 🐛 Bug
The following code compiles but it fails when trying to find the `forward` method.

```py
from typing import overload

import torch


class Test(torch.nn.Module):
    @overload
    @torch.jit._overload_method
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        ...

    @overload
    @torch.jit._overload_method
    def forward(
        self, x: torch.nn.utils.rnn.PackedSequence
    ) -> torch.nn.utils.rnn.PackedSequence:
        ...

    def forward(self, x):
        return x


model = Test()
model = torch.jit.script(model)
model(torch.ones(10))
model(
    torch.nn.utils.rnn.pack_padded_sequence(
        torch.ones(10, 1, 20), torch.ones(10), batch_first=True
    )
)
```

```
Traceback (most recent call last):
  File "foo.py", line 25, in <module>
    model(torch.ones(10))
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 558, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 288, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'forward'
```

**Comment by twoertwein** [comment]
I think even pytorch's GRU is affected by that! I'm getting the same RunTime error when calling a jit'ed GRU.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
