### ISSUE TITLE
M1 release and nightly binaries

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#51854]
## 🐛 Bug

PyTorch fails to install on M1 (both release and nightly) when running with Python arm64.

## To Reproduce

```
~: /opt/homebrew/bin/python3 -m pip install torch  
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied: pyyaml in /opt/homebrew/lib/python3.9/site-packages (from torch) (5.4.1)
WARNING: The candidate selected for download or install is a yanked version: 'torch' candidate (version 0.1.2.post2 at https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz#sha256=a43e37f8f927c5b18f80cd163daaf6a1920edafcab5102e02e3e14bb97d9c874 (from https://pypi.org/simple/torch/))
Reason for being yanked: 0.1.2 is past it's support date and confuses users on unsupported platforms
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-wheel-m7tlhyn2
       cwd: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/homebrew/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-record-mw103z31/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/torch
         cwd: /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py", line 99, in run
        self.run_command('build_deps')
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"'; __file__='"'"'/private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-install-q1tl3j74/torch_2e99672321724fb3af317936a037bd6c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2b/hhkbvbds4x71jgh0pk3rfkx00000gn/T/pip-record-mw103z31/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/torch Check the logs for full command output.
```

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 11.2 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.18.4

Python version: 3.9 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.0
[conda] Could not collect

#48524 @malfet

cc @malfet @seemethere @walterddr

**Comment by albanD** [comment]
The compilation should be working just fine now. Note that some tests are failing though (for various reasons, not only M1): https://github.com/pytorch/pytorch/issues/56809

You can also get binaries from nightly by just following the instructions here: https://pytorch.org/get-started/locally/ (an x86 python will pull the x86 package and an arm64 python will pull the arm64 package).
