### ISSUE TITLE
Memory leak when using lambda in class

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#51883]
## 🐛 Bug

I have detected a memory leak when using a lambda function inside a Python class.

## To Reproduce

```python
import torch

class Class1(object):
    def __init__(self, x0):
        self.x0 = x0
        self.obj2 = Class2()
        self._leak_fcn = lambda: self.obj2.fcn()  # source of memory leak!

class Class2(object):
    def fcn(self):
        pass

def fcn(x0):
    obj1 = Class1(x0)
    return x0

def test_fcn():
    shape = (50000000, 3)
    y0 = torch.randn(shape).to(torch.double).to(torch.device("cuda"))
    y = fcn(y0)
    return y

for i in range(100):
    test_fcn()
    torch.cuda.empty_cache()
    print("memory allocated: %f MiB" % float(torch.cuda.memory_allocated() / 1024 ** 2))
```

The output of the script above is:
```
memory allocated: 1144.409180 MiB
memory allocated: 2288.818359 MiB
memory allocated: 3433.227539 MiB
memory allocated: 1144.409180 MiB
memory allocated: 2288.818359 MiB
memory allocated: 3433.227539 MiB
memory allocated: 4577.636719 MiB
memory allocated: 5722.045898 MiB
memory allocated: 6866.455078 MiB
memory allocated: 8010.864258 MiB
memory allocated: 9155.273438 MiB
memory allocated: 1144.409180 MiB
memory allocated: 2288.818359 MiB
memory allocated: 3433.227539 MiB
memory allocated: 4577.636719 MiB
memory allocated: 5722.045898 MiB
memory allocated: 6866.455078 MiB
memory allocated: 8010.864258 MiB
memory allocated: 9155.273438 MiB
memory allocated: 10299.682617 MiB
memory allocated: 11444.091797 MiB
Traceback (most recent call last):
  File "memtest.py", line 27, in <module>
    test_fcn()
  File "memtest.py", line 22, in test_fcn
    y0 = torch.randn(shape).to(dtype).to(device)
RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 11.91 GiB total capacity; 11.18 GiB already allocated; 140.25 MiB free; 11.19 GiB reserved in total by PyTorch)
```

## Expected behavior

No memory leak should happen.

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.0a0+4803eaf
 - OS (e.g., Linux): Linux (Ubuntu 18.04.5 LTS)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: Titan X (Pascal)
 - Any other relevant information: -

## Additional context

If I comment out the line containing `self._leak_fcn`, no memory leak detected:
```
memory allocated: 0.000000 MiB
memory allocated: 0.000000 MiB
memory allocated: 0.000000 MiB
...
```
There is also no memory leak if I define the `_leak_fcn` as a method of the class instead of using lambda function.

I'm not sure if the problem is from PyTorch or from Python.

**Comment by mfkasim1** [comment]
I might have an answer for this and this is likely not an issue from PyTorch, but from Python (as it also happens even if I use numpy).
The source of the problem is the circular reference between the lambda and `Class1`.
The leak also happens if I set `Class2` to have a reference to `Class1` (even without the lambda function).

Here's the discussion: https://stackoverflow.com/questions/66106830/memory-leak-when-using-lambda-in-python-class?noredirect=1#comment116877475_66106830

I'm closing this as the problem most probably not from PyTorch.
