### ISSUE TITLE
CUDA inverse() causes illegal memory access

### ISSUE THREAD

**Issue by rightaditya** [pytorch/pytorch#51930]
**Update:** this issue has been updated to only track CUDA inverse() causing an illegal memory access. The original issue is below. See https://github.com/pytorch/pytorch/issues/52700, which tracks the bug in det().

## 🐛 Bug

For certain tensors on CUDA, calling `tensor.det()` returns some `nan` values where it should return `0.`, and calling `tensor.inverse()` causes CUDA illegal memory access. I'm not sure exactly which properties of the tensor are responsible for triggering this, so I've attached an example tensor that triggers this issue as a 
[gzipped .pt file](https://github.com/pytorch/pytorch/files/5948348/nandet.pt.gz) (the file would have been >100MB otherwise).

## To Reproduce

Download [nandet.pt.gz](https://github.com/pytorch/pytorch/files/5948348/nandet.pt.gz), then to reproduce:
```python
>>> import gzip, torch
>>> nandet = torch.load(gzip.open('nandet.pt.gz')).cuda()
>>> nandet.shape
torch.Size([8, 10, 616, 616])
>>> nandet.det()
tensor([[nan, 0., 1., 0., 1., 0., nan, nan, nan, 1.],
        [1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 1., 0., -0., nan, 0., 1., 1., 0.],
        [1., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 0., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')
>>> nandet.inverse()
CUDA runtime error: an illegal memory access was encountered (700) in magma_sgetrf_batched at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/src/sgetrf_batched.cpp:213
CUDA runtime error: an illegal memory access was encountered (700) in magma_sgetrf_batched at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/src/sgetrf_batched.cpp:214
CUDA runtime error: an illegal memory access was encountered (700) in magma_sgetrf_batched at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/src/sgetrf_batched.cpp:215
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/interface_cuda/interface.cpp:944
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/interface_cuda/interface.cpp:945
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/interface_cuda/interface.cpp:946
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: an illegal memory access was encountered
```

## Expected behavior

Calling `nandet.det()` should return `0.` where it is returning `nan`, and, since there are non-invertible matrices, `nandet.inverse()` should still raise a `RuntimeError` complaining about that, and there shouldn't be any illegal memory accesses:
```python
>>> nandet.det()
tensor([[0., 0., 1., 0., 1., 0., 0., 0., 0., 1.],
        [1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 1., 0., 0., 0., 0., 1., 1., 0.],
        [1., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 0., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')
>>> nandet.inverse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: inverse_cuda: For batch 0: U(19,19) is zero, singular U.
```

## Environment

PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 450.51.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-lightning==1.1.8
[pip3] torch==1.7.1+cu110
[conda] Could not collect

## Additional context

Only the first row has meaningful content past index 248; for the other rows, anything past that index is an identity matrix, and so excluding it shouldn't affect the determinants or inversions. In other words, I would expect `nandet[1:, :, :248, :248].det()` to yield exactly the same results as `nandet[1:].det()`. But for some reason, these two differ at the index that has a `nan` as well as the one just before it (`0.` vs `-0.`):
```python
>>> nandet[1:].det()
tensor([[1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 1., 0., -0., nan, 0., 1., 1., 0.],
        [1., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 0., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')
>>> nandet[1:, :, :248, :248].det()
tensor([[1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 1., 0., 0., 0., 0., 1., 1., 0.],
        [1., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 0., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')
```
(EDIT: fixed output for last command; I had previously accidentally re-pasted the output of the first)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
Thank you for filing this issue, @rightaditya, we'll take a look!

**Comment by ngimel** [comment]
Seems that batched magma functions produce wrong results:
```
In [13]: nandet[5,5].det()                 # non-batched                                                                                                                                                                  
Out[13]: tensor(0., device='cuda:0')

In [14]: nandet[5,5].unsqueeze_(0).det()        #same tensor, but will call batched lu                                                                                                                                                             
Out[14]: tensor([nan], device='cuda:0')
```

**Comment by rightaditya** [comment]
I forgot to note this, but the `sign` part of `slogdet()` seems to work (`logabsdet` is still broken):
```python
>>> nandet.slogdet()
torch.return_types.slogdet(
sign=tensor([[-0., 0., 1., 0., 1., 0., 0., -0., -0., 1.],
        [1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 1., 0., -0., -0., 0., 1., 1., 0.],
        [1., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 0., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0'),
logabsdet=tensor([[nan, -inf, 0., -inf, 0., -inf, nan, nan, nan, 0.],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf, 0., -inf],
        [0., -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, 0.],
        [0., 0., 0., 0., 0., -inf, -inf, 0., 0., 0.],
        [-inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, 0.],
        [0., -inf, 0., -inf, -inf, nan, -inf, 0., 0., -inf],
        [0., 0., 0., -inf, -inf, 0., 0., 0., 0., 0.],
        [0., 0., -inf, -inf, 0., 0., 0., -inf, 0., 0.]], device='cuda:0'))
```

I am calculating the determinant before inverting to check the batch for singular matrices, so luckily `slogdet()[0]` can handle this (though, because `det()` and `slogdet()` are relatively slow, it would be nice if `inverse()` could fill in `nan` values for singular matrices rather than throwing an unrecoverable error---see #33051).

**Comment by mruberry** [comment]
I tweaked this issue so we have one issue per problem (just to make tracking easier).
