### ISSUE TITLE
Overwritten method has wrong self when JIT'ed

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#51942]
## 🐛 Bug
Doing the following is probably not a good programming style. It might be better to throw an error during compilation or use the correct `self`.

```py
import torch

class A(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.other_object = B()
        self.fun = self.other_object.fun  # ugly but works in python

    @torch.jit.export
    def fun(self) -> int:
        return 1


class B(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.int = 2

    @torch.jit.export
    def fun(self) -> int:
        return self.int


model = torch.jit.script(A())
model.fun()
```

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = torch.jit.script(A())
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 897, in script
    return torch.jit._recursive.create_script_module(
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 410, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 304, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Module 'A' has no attribute 'int' :
  File "test.py", line 22
    @torch.jit.export
    def fun(self) -> int:
        return self.int
               ~~~~~~~~ <--- HERE
```

**Comment by SplitInfinity** [comment]
We iterate through `dir(module)` to find methods and then inspect their source code after. Perhaps we should skip the iteration altogether and use the source code directly?

I would argue that the error you have shown is the one you refer to when you say `it might be better to throw an error during compilation." What can be improved about the error message?

**Comment by twoertwein** [comment]
The error message is okay, I was just expecting that it would happen during compilation: Normally JIT seems to check all variables/attributes at compilation time.

**Comment by SplitInfinity** [comment]
It is a compilation error; you can see `model = torch.jit.script(A())` in the traceback. However, the exception type is `RuntimeError` which is probably confusing. Perhaps it's worth using a different exception type for things that are truly compilation errors?

**Comment by twoertwein** [comment]
oh yes, sorry you are right :)

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
