### ISSUE TITLE
[complex] torch.conj function variant supports bool, float16 but out variant doesn't

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51949]
```python
>>> import torch
>>> torch.__version__
'1.8.0a0+fcf8b71'
>>> t = torch.randn(3)
>>> torch.conj(t)
tensor([-0.3089,  0.6107,  0.1792]) # function variant with float
>>> torch.conj(t, out=torch.zeros_like(t)) # out variant with float
tensor([-0.3089,  0.6107,  0.1792])
>>> t_b = t.to(torch.bool)
>>> torch.conj(t_b) # function variant with bool
tensor([True, True, True])
>>> torch.conj(t_b, out=torch.zeros_like(t_b)) # out variant with bool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "conj_cpu" not implemented for 'Bool'
>>> t_b = t_b.cuda()
>>> torch.conj(t_b) # function variant with bool cuda
tensor([True, True, True], device='cuda:0')
>>> torch.conj(t_b, out=torch.zeros_like(t_b)) # out variant with bool cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "conj_cuda" not implemented for 'Bool'
>>> t_f16 = t.to(torch.float16)
>>> torch.conj(t_f16) # function variant with float16
tensor([-0.3088,  0.6108,  0.1792], dtype=torch.float16)
>>> torch.conj(t_f16, out=torch.zeros_like(t_f16)) # out variant with float16
tensor([-0.3088,  0.6108,  0.1792], dtype=torch.float16)
>>> t_f16 = t.to(torch.float16).cuda()
>>> torch.conj(t_f16) # function variant with float16 cuda
tensor([-0.3088,  0.6108,  0.1792], device='cuda:0', dtype=torch.float16)
>>> torch.conj(t_f16, out=torch.zeros_like(t_f16)) # out variant with float16 cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "conj_cuda" not implemented for 'Half'
```

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by anjali411** [comment]
@kshitij12345 thanks for filing this issue! we should definitely support the out version for `Half` as well. I think it's discrepancy is because we return `self` for non-complex tensors, so `conj` is enabled for all dtypes by default. I also found a numpy compat issue:
```
>>> np.conj(np.array([True]))
array([1], dtype=int8)
```
It's hard to fix this because we still want to return self for `conj` to maintain the autograd performance.
