### ISSUE TITLE
Memory leak when applying autograd.grad in backward

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#51978]
## 🐛 Bug

There is a memory leak when applying `torch.autograd.grad` in `Function`'s `backward`.
However, it only happens if `create_graph` in the `torch.autograd.grad` is set to be `False`.

## To Reproduce

```python
import torch

class Functional1(torch.autograd.Function):
    @staticmethod
    def forward(ctx, fcn, y0, *params):
        ctx.fcn = fcn
        ctx.save_for_backward(y0, *params)
        return y0
    @staticmethod
    def backward(ctx, grad_yout):
        yout, *params = ctx.saved_tensors
        with torch.enable_grad():
            params_copy = [p.clone().requires_grad_() for p in params]
            yfcn = ctx.fcn(yout, *params_copy)
        # NOTE: setting create_graph to False removes the memory leak
        grad_params = torch.autograd.grad(yfcn, params_copy, grad_outputs=grad_yout,
                                          create_graph=torch.is_grad_enabled())
        return (None, None, *grad_params)

def fcn2(x, x2):
    return x + x2

def test_fcn():
    shape = (10000, 10000)
    y0 = torch.zeros(shape).to(torch.double).to(torch.device("cuda"))
    y2 = y0.clone().requires_grad_()
    loss = (Functional1.apply(fcn2, y0, y2) ** 2).sum()
    # NOTE: setting create_graph to False removes the memory leak, even if
    # retain_graph is still True
    loss.backward(retain_graph=True, create_graph=True)

for i in range(5):
    test_fcn()
    torch.cuda.empty_cache()
    mem = float(torch.cuda.memory_allocated() / (1024 * 1024))
    print("memory allocated:", mem, "MiB")
```

The output of the above script is:
```
memory allocated: 2288.81884765625 MiB
memory allocated: 4577.6376953125 MiB
memory allocated: 6866.45654296875 MiB
memory allocated: 9155.275390625 MiB
Traceback (most recent call last):
  File "memtest.py", line 33, in <module>
    test_fcn()
  File "memtest.py", line 30, in test_fcn
    loss.backward(retain_graph=True, create_graph=True)
  File "/home/muhammadkasim/anaconda2/envs/torchdev/lib/python3.8/site-packages/torch/tensor.py", line 225, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/muhammadkasim/anaconda2/envs/torchdev/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 764.00 MiB (GPU 0; 11.91 GiB total capacity; 11.18 GiB already allocated; 138.25 MiB free; 11.19 GiB reserved in total by PyTorch)
```

## Expected behavior

No memory leak should happen, like in the case where `create_graph=False` with output:
```
memory allocated: 0.0 MiB
memory allocated: 0.0 MiB
memory allocated: 0.0 MiB
memory allocated: 0.0 MiB
memory allocated: 0.0 MiB
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.0a0+4803eaf
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: TITAN X
 - Any other relevant information:

## Additional context

N/A

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by soulitzer** [comment]
Hmm from here https://pytorch.org/docs/stable/autograd.html, it looks like it is expected that reference cycles are created when calling `.backward()` with `create_graph=True`. So avoid the memory leak, doing `del y2.grad` before returning from `test_fcn` should work.

For example something like this also leaks:
```
import torch

class Functional1(torch.autograd.Function):
    @staticmethod
    def forward(ctx, a):
        return torch.ones_like(a)
    @staticmethod
    def backward(ctx, gO):
        return gO
def test_fcn():
    x = torch.randn((30, 10000), requires_grad=True, device="cuda")
    y = Functional1.apply(x).exp()
    y.backward(torch.ones_like(y), create_graph=True)

for i in range(5):
    test_fcn()
    torch.cuda.empty_cache()
    mem = float(torch.cuda.memory_allocated() / (1024 * 1024))
    print("memory allocated:", mem, "MiB")
```

**Comment by mfkasim1** [comment]
Thanks, @soulitzer. I didn't know that this is a known leak. Should I close this?

**Comment by albanD** [comment]
Closing this PR in favor of https://github.com/pytorch/pytorch/issues/7343
Happy to discuss there if you have any follow up on that :)
