### ISSUE TITLE
Unable to build: subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Breidenbach** [pytorch/pytorch#52096]
## 🐛 Bug

Trying to build on Mac OSX from source, build terminated with:
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.

## To Reproduce

1.  Install dependencies as documented on web page
2.  git clone --recursive https://github.com/pytorch/pytorch
3. cd to pytorch directory
4.  git submodule update --init --recursive 
5. export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install 2>&1 | tee build_new.txt

log of output after additional context below

Clean build of caffe2 (logged messages 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 10.15.6 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[conda] mkl                       2020.2                      260
[conda] mkl-include               2020.2                      260
[conda] numpy                     1.19.2           py38h63973fd_0
[conda] numpy-base                1.19.2           py38h68fea81_0
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

[build_new.txt](https://github.com/pytorch/pytorch/files/5961572/build_new.txt)

**Comment by xuhdev** [comment]
Could you give more information? What are the output before the error messages?

**Comment by xuhdev** [comment]
Relevant error message is here:

```
cd /Users/hal/pytorch && /Users/hal/opt/anaconda3/envs/caffe2-lmdb/bin/python tools/setup_helpers/generate_code.py --declarations-path /Users/hal/pytorch/build/aten/src/ATen/Declarations.yaml --native-functions-path aten/src/ATen/native/native_functions.yaml --nn-path aten/src   --force_schema_registration
Traceback (most recent call last):
  File "tools/setup_helpers/generate_code.py", line 183, in <module>
    main()
  File "tools/setup_helpers/generate_code.py", line 168, in main
    generate_code(
  File "tools/setup_helpers/generate_code.py", line 60, in generate_code
    gen_autograd_python(
  File "/Users/hal/pytorch/tools/autograd/gen_autograd.py", line 130, in gen_autograd_python
    differentiability_infos = load_derivatives(
  File "/Users/hal/pytorch/tools/autograd/load_derivatives.py", line 41, in load_derivatives
    infos = [
  File "/Users/hal/pytorch/tools/autograd/load_derivatives.py", line 42, in <listcomp>
    create_differentiability_info(defn, functions_by_signature, functions_by_schema)
  File "/Users/hal/pytorch/tools/autograd/load_derivatives.py", line 192, in create_differentiability_info
    raise RuntimeError(f'could not find ATen function for schema: {specification} '
RuntimeError: could not find ATen function for schema: _fake_quantize_learnable_per_tensor_affine(Tensor self, Tensor scale, Tensor zero_point, int quant_min, int quant_max) -> Tensor .  Available signatures:
_fake_quantize_learnable_per_tensor_affine(Tensor self, Tensor scale, Tensor zero_point, int quant_min, int quant_max, float grad_factor=1.0) -> Tensor
```

**Comment by VitalyFedyunin** [comment]
You probably took broken master state, can you please try to update to most recent version of repo and do clean build.

**Comment by Breidenbach** [comment]
I downloaded again into a new directory, and get exactly the same error.

**Comment by walterddr** [comment]
#49315 seems to be the last one modifying _fake_quantize_learnable_per_tensor_affine and it added one additional argument

**Comment by malfet** [comment]
@Breidenbach can you share list of conda packages installed on your system? Also `md5 torch/share/ATen/Declarations.yaml aten/src/ATen/native/native_functions.yaml`

**Comment by Breidenbach** [comment]
Conda packages in the environment I am using:
[conda-packages-in-this-environment.txt](https://github.com/pytorch/pytorch/files/5966938/conda-packages-in-this-environment.txt)
md5: torch/share/ATen/Declarations.yaml: No such file or directory
MD5 (aten/src/ATen/native/native_functions.yaml) = 0279fb7de1eb993c63dc5b5b99874ca0
