### ISSUE TITLE
jit.script crashes when type annotation `Dict[str, object]`

### ISSUE THREAD

**Issue by robin5540** [pytorch/pytorch#52106]
## 🐛 Bug

@bryce-evans found this bug

This looks like a bug in the map initialization logic. I guess the type problem should have been caught before trying to construct the Dict.

Stacktrace:
```
#0  0x00007ffff4f73ac4 in c10::DictType::create(std::shared_ptr<c10::Type>, std::shared_ptr<c10::Type>) () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#1  0x00007ffff503df37 in void pybind11::cpp_function::initialize<void pybind11::detail::initimpl::factory<torch::jit::initPythonIRBindings(_object*)::{lambda(std::shared_ptr<c10::Type>, std::shared_ptr<c10::Type>)#94}, pybind11::detail::void_type (*)(), std::shared_ptr<c10::DictType> (std::shared_ptr<c10::Type>, std::shared_ptr<c10::Type>), pybind11::detail::void_type>::execute<pybind11::class_<pybind11::detail::void_type (*)(), c10::Type, c10::DictType>>(pybind11::class_<pybind11::detail::void_type (*)(), c10::Type, c10::DictType>&) &&::{lambda(pybind11::detail::value_and_holder&, std::shared_ptr<c10::Type>, std::shared_ptr<c10::Type>)#1}, void, pybind11::detail::value_and_holder, std::shared_ptr<c10::Type>, std::shared_ptr<c10::Type>, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor>(pybind11::class_<pybind11::detail::void_type (*)(), c10::Type, c10::DictType>&&, void (*)(pybind11::detail::value_and_holder, std::shared_ptr<c10::Type>, std::shared_ptr<c10::Type>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::detail::is_new_style_constructor const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN ()
   from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#2  0x00007ffff4c198f3 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#3  0x00005555556d3706 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x7fffa6230f90) at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:742
#4  PyCFunction_Call () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:772
#5  0x000055555569125f in _PyObject_MakeTpCall () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:159
#6  0x00005555556df8dc in _PyObject_Vectorcall (kwnames=0x0, nargsf=3, args=0x7fffffff9de0, callable=0x7fffa6230f90) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:125
#7  method_vectorcall () at /tmp/build/80754af9/python_1593706424329/work/Objects/classobject.c:89
#8  0x0000555555690a41 in PyVectorcall_Call () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:199
#9  0x00005555556e022a in slot_tp_init () at /tmp/build/80754af9/python_1593706424329/work/Objects/typeobject.c:6758
#10 0x00005555556911d4 in type_call (kwds=0x0, args=0x7fff983570c0, type=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Objects/typeobject.c:991
#11 _PyObject_MakeTpCall () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:159
#12 0x00005555557155e5 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x55555595f3a0, callable=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:125
#13 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558ea090) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#14 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3500
#15 0x00005555556de7af in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#16 0x00005555556df243 in _PyFunction_Vectorcall.localalias.353 () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:435
#17 0x0000555555690a41 in PyVectorcall_Call () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:199
#18 0x00007ffff4f128a4 in pybind11::detail::simple_collector<(pybind11::return_value_policy)1>::call(_object*) const () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#19 0x00007ffff5082ad9 in torch::jit::(anonymous namespace)::PythonResolver::resolveType(std::string const&, torch::jit::SourceRange const&) ()
   from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#20 0x00007fffe69329b8 in torch::jit::ScriptTypeParser::parseTypeFromExpr(torch::jit::Expr const&) const () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#21 0x00007fffe693389f in torch::jit::ScriptTypeParser::parseArgsFromDecl(torch::jit::Decl const&, bool) () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#22 0x00007fffe69345f3 in torch::jit::ScriptTypeParser::parseSchemaFromDef(torch::jit::Def const&, bool) () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#23 0x00007fffe6913636 in torch::jit::to_ir::emitDef(torch::jit::Def const&, torch::jit::Self const*, torch::jit::Block*) () from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#24 0x00007fffe6914a4f in torch::jit::to_ir::to_ir(torch::jit::Def const&, std::shared_ptr<torch::jit::Resolver>, torch::jit::Self const*, torch::jit::Function&) ()
   from /home/xu.meng/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
```

## To Reproduce

This code should get a type mismatch instead of crash 
```python3
from typing import List, Dict
import torch
class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, labels: torch.Tensor):
        self.compute_loss(labels)
    def compute_loss(self, labels: Dict[str, object]):
        return None

torch.jit.script(MyModel())
```

this code should give type not found instead of crash
```python3
from typing import List, Dict
import torch
class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, labels: Dict[str, object]):
        return labels

torch.jit.script(MyModel())
```

## Expected behavior

Exception instead of crash

## Environment

Ubuntu 18.04 -- CUDA 10 and CUDA 11
1.6.0, 1.7.0, 1.7.1

MacOS
1.7.1

**Comment by robin5540** [comment]
This bug seems to have been fixed on the latest master.
```
(base) ➜  pytorch git:(master) git rev-parse HEAD
a1b8f3d4b6ada3721a3d9d8266f86dcb04f17fcb
```

**Comment by robin5540** [comment]
Dupe of https://github.com/pytorch/pytorch/issues/49362

fixed in https://github.com/pytorch/pytorch/commit/26e076d19e6936c9fd548412e15c0c815c588762
