### ISSUE TITLE
PyTorch incompatible with `dataclasses`

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#52127]
## 🐛 Bug

For some reason, using PyTorch with `dataclasses` messes up the reference between the optimizer and the model. Using `dataclasses.astuple` screws up `.grad` for my `model`. 

I'm not sure what's happening under the hood; however, I didn't expect PyTorch to be affected by a Python core library module.

## To Reproduce

```python
import dataclasses
import pathlib

import torch
import torch.nn
import torch.optim

path = pathlib.Path("checkpoint.pt")
device = torch.device("cpu")


@dataclasses.dataclass(frozen=True)
class State:

    model: torch.nn.Module
    optimizer: torch.optim.Adam


def make_state():
    print("make_state...")
    model = torch.nn.LSTM(10, 20, 2).to(device)
    params = list(filter(lambda p: p.requires_grad, model.parameters()))
    optimizer = torch.optim.Adam(params)
    return State(model, optimizer)


def run_step(state):
    print("run_step...")
    input = torch.randn(5, 3, 10).to(device)
    output, _ = state.model(input)
    state.model.zero_grad()
    output.sum().backward()
    params = state.optimizer.param_groups[0]["params"]
    assert all([p.grad is not None for p in params]), "No gradients found."
    state.optimizer.step()


def main():
    state = make_state()

    # NOTE: These lines cause the bug.
    args = dataclasses.astuple(state)
    del state
    state = State(*args)

    run_step(state)


main()
```

Sample output:
```
make_state...
run_step...
Traceback (most recent call last):
  File "test_again.py", line 45, in <module>
    main()
  File "test_again.py", line 42, in main
    run_step(State(*args))
  File "test_again.py", line 34, in run_step
    assert all([p.grad is not None for p in params]), "No gradients found."
AssertionError: No gradients found.
```

## Expected behavior

The expected behavior is that unpacking and packing `dataclasses` wouldn't affect PyTorch.

## Environment

```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-nlp==0.5.0
[pip3] torch==1.7.1
[conda] Could not collect
```

**Comment by SsnL** [comment]
hardly a pytorch fault. `as_tuple` deep copies https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/dataclasses.py#L1069

**Comment by PetrochukM** [comment]
Thanks! So, strange, I didn't expect `dataclasses` to do that, and it's not documented.
