### ISSUE TITLE
Starting training.. stuck 

### ISSUE THREAD

**Issue by anayavol** [pytorch/pytorch#52131]
I am using https://github.com/facebookresearch/mmf and while training, the system gets stuck either on **Loading dataset(using 2 gpus)** or **Starting training(using single gpu)**
### 2021-02-09T17:15:17 | mmf.trainers.core.training_loop: Starting training...

**when I interrupt training it gives me**
_2021-02-09T17:15:17 | mmf.utils.general: Total Parameters: 254918110. Trained Parameters: 254918110
2021-02-09T17:15:17 | mmf.trainers.core.training_loop: Starting training...
^CTraceback (most recent call last):
  File "/home/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/mmf-master/mmf-master/mmf_cli/run.py", line 122, in run
    main(configuration, predict=predict)
  File "/home/mmf-master/mmf-master/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/mmf-master/mmf-master/mmf/trainers/mmf_trainer.py", line 123, in train
    self.training_loop()
  File "/home/mmf-master/mmf-master/mmf/trainers/core/training_loop.py", line 31, in training_loop
    self.run_training_epoch()
  File "/home/mmf-master/mmf-master/mmf/trainers/core/training_loop.py", line 75, in run_training_epoch
    for idx, batch in enumerate(self.train_loader):
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)_

**I am keeping batch size=32 and num_worker=4**

The **nvidia-smi** command gives me this.
![image](https://user-images.githubusercontent.com/78897812/107609364-850fd680-6c60-11eb-9af0-2fdb1a7d7990.png)

**environment information**
PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.7 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.18.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80

Nvidia driver version: 430.64
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0+cu101
[pip3] torchtext==0.5.0
[pip3] torchvision==0.7.0+cu101
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.0.130 0
[conda] mkl 2020.2 256
[conda] mkl-service 2.3.0 py36he8ac12f_0
[conda] mkl_fft 1.2.0 py36h23d657b_0
[conda] mkl_random 1.1.1 py36h0573a6f_0
[conda] numpy 1.19.2 py36h54aff64_0
[conda] numpy-base 1.19.2 py36hfa32c7d_0
[conda] torch 1.4.0+cu100 pypi_0 pypi
[conda] torchtext 0.5.0 pypi_0 pypi
[conda] torchvision 0.7.0+cu101 pypi_0 pypi

Please let me know what could be the reason. i kept num_worker=0 too but it didn't work as well

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

Also I think that you want to provide the stack trace when you set `num_worker=0` when you open your post there as it will be more informative than the one with multiple workers!
