### ISSUE TITLE
C++ standard library confusion

### ISSUE THREAD

**Issue by aweits** [pytorch/pytorch#52208]
## 🐛 Bug

After building py-torch from source with a newer version of gcc (and libstdc++), we get the following error on import:

```shell
[aweits@localhost ~]$ python
Python 3.8.7 (default, Jan  6 2021, 14:20:25) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aweits/GIT/UPSTREAMSPACK/spack/opt/spack/linux-centos8-skylake_avx512/gcc-9.3.0/py-torch-1.7.1-gja66kub643ix7sevlid27wcsdimbxgx/lib/python3.8/site-packages/torch/__init__.py", line 190, in <module>
    from torch._C import *
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/aweits/GIT/UPSTREAMSPACK/spack/opt/spack/linux-centos8-skylake_avx512/gcc-9.3.0/py-torch-1.7.1-gja66kub643ix7sevlid27wcsdimbxgx/lib/python3.8/site-packages/torch/lib/libtorch_python.so)

```
# To Reproduce

1. Build from source with a newer-than-system gcc/libstdc++, and newer cuda libraries that depend on libstdc++

## Expected behavior
Should cleanly import. The issue is that the "empty" library introduced in commit ddff4ef pulls in the Nvidia libraries, which *then* pull in the system libstdc++. This is incorrect in this case as the libstdc++ that was included/built with the compiler should be used instead. This can be avoided/fixed by changing the following:

```shell
'torch_global_deps PROPERTIES LINKER_LANGUAGE C'
```
to
```shell
'torch_global_deps PROPERTIES LINKER_LANGUAGE CXX'
```
in caffe2/CMakeLists.txt

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): from source, using spack
 - Build command you used (if compiling from source): 
 - Python version:
 - CUDA/cuDNN version: 11.1.1/8.0.4.30-11.1
 - GPU models and configuration: Nvidia Quadro P4000
 - Any other relevant information:

## Additional context

https://github.com/spack/spack/issues/18867

**Comment by aweits** [comment]
Output from a ldd on a version compiled with 'torch_global_deps PROPERTIES LINKER_LANGUAGE C'
```shell
LD_DEBUG=all ldd libtorch_global_deps.so
```
[fails.txt](https://github.com/pytorch/pytorch/files/6022719/fails.txt)

**Comment by aweits** [comment]
Output from a ldd on a version compiled with 'torch_global_deps PROPERTIES LINKER_LANGUAGE CXX'
```shell
LD_DEBUG=all ldd libtorch_global_deps.so
```
[works.txt](https://github.com/pytorch/pytorch/files/6022733/works.txt)
