### ISSUE TITLE
Conv3D error : CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/pytorch#52211]
## 🐛 Bug

A cudnn error is raised using the code below. I suppose that the issue is related to #4632 #13636.

## To Reproduce

```
import torch
import torch.nn.functional as F

torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True

class Simpler3DNet(torch.nn.Module):
   
    def __init__(self, large_bn=False):
        super(Simpler3DNet, self).__init__()
        self.conv1 = torch.nn.Conv3d(1, 32, kernel_size=5, padding=2)
        self.conv2 = torch.nn.Conv3d(32, 64, kernel_size=5, padding=2)
        self.conv3 = torch.nn.Conv3d(64, 128, kernel_size=3, padding=1)
        self.fc1 = torch.nn.Linear(128, 64)
        self.fc2 = torch.nn.Linear(64, 1)
        self.bn1 = torch.nn.BatchNorm3d(32)
        self.bn2 = torch.nn.BatchNorm3d(64)
        self.bn3 = torch.nn.BatchNorm3d(128)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.bn1(x)
        x = F.max_pool3d(x, 5)
        x = F.relu(self.conv2(x))
        x = self.bn2(x)
        x = F.max_pool3d(x, 5)
        x = F.relu(self.conv3(x))
        x = self.bn3(x)
        x = F.max_pool3d(x, 4)

        x = x.view(-1, 128)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.relu(x).flatten()


if __name__ == '__main__':
    data = torch.randn([70, 1, 100, 100, 100], dtype=torch.half, device='cuda', requires_grad=True)
    net = Simpler3DNet()
    net = net.cuda().half()
    out = net(data)
    out.backward(torch.randn_like(out))
    torch.cuda.synchronize()
```

The error is 
```
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([70, 32, 20, 20, 20], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv3d(32, 64, kernel_size=[5, 5, 5], padding=[2, 2, 2], stride=[1, 1, 1], dilation=[1, 1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_HALF
    padding = [2, 2, 2]
    stride = [1, 1, 1]
    dilation = [1, 1, 1]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x555b8925c250
    type = CUDNN_DATA_HALF
    nbDims = 5
    dimA = 70, 32, 20, 20, 20, 
    strideA = 256000, 8000, 400, 20, 1, 
output: TensorDescriptor 0x555b8925c300
    type = CUDNN_DATA_HALF
    nbDims = 5
    dimA = 70, 64, 20, 20, 20, 
    strideA = 512000, 8000, 400, 20, 1, 
weight: FilterDescriptor 0x555b8925c2c0
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 5
    dimA = 64, 32, 5, 5, 5, 
Pointer addresses: 
    input: 0x7f4690000000
    output: 0x7f4680000000
    weight: 0x7f49c2800000
```
Note that the snippet code is ok...

If I disable `cudnn` adding the following line
```
torch.backends.cudnn.enabled = False
```

I have another error
```
Traceback (most recent call last):
  File "/home/irsrvhome1/R11/desrozis/issue.py", line 63, in <module>
    out = net(data)
  File "/disk1/work/desrozis/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/irsrvhome1/R11/desrozis/issue.py", line 45, in forward
    x = F.relu(self.conv2(x))
  File "/disk1/work/desrozis/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk1/work/desrozis/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 572, in forward
    return F.conv3d(input, self.weight, self.bias, self.stride,
RuntimeError: CUDA error: an illegal memory access was encountered
```

## Expected behavior

The code should run without error

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 440.33.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.7.1
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.7.1                    pypi_0    pypi

Help is welcome.

**Comment by ptrblck** [comment]
Thanks for reporting this issue!
I'm able to reproduce the `CUDNN_STATUS_INTERNAL_ERROR` in the `1.7.1` binary with cudnn7.6.5.32.
I was hoping to be able to recommend to switch to cudnn8, but then you'll be facing a `SIGFPE, Arithmetic exception`.

I'm also able to reproduce the illegal memory access in the native kernels at:
```
Thread 1 "python" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 2411, block (0,2,42975), thread (0,0,0), device 0, sm 0, warp 19, lane 0]
0x00005555a4606100 in void at::native::(anonymous namespace)::max_pool3d_with_indices_single_out_frame<c10::Half>(c10::Half*, at::GenericPackedTensorAccessor<c10::Half, 4ul, at::DefaultPtrTraits, long>, at::GenericPackedTensorAccessor<long, 4ul, at::DefaultPtrTraits, long>, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int)<<<(1,3,44800),(32,8,1)>>> ()
```

As the next steps I'll check this behavior in the nightlies/master, create internal cudnn issues for the former errors, and keep debugging the max pooling kernel.

**Comment by xwang233** [comment]
Seems like this is a pooling issue. This short repro can trigger the IMA as well. I'll take a look.

```python
import torch

x = torch.randn(70, 32, 100, 100, 100, dtype=torch.half, device='cuda')

y = torch.nn.functional.max_pool3d(x, 5)

torch.cuda.synchronize()
```

Env:

```
Collecting environment information...
PyTorch version: 1.9.0a0+a86027d
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.19.3

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.67
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce GTX 1070 Ti

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0a0+a86027d
[conda] Could not collect
```

**Comment by xwang233** [comment]
This is because there is an int32 multiplication overflow happened here.

https://github.com/pytorch/pytorch/blob/b824fc4de22c0e278ec57669b1b82c2d8e1f7394/aten/src/ATen/native/cuda/DilatedMaxPool3d.cu#L56

For the above repro script, 

```python
slice = 70 * 32 = 2240
itime = 100
iheight = 100
iwidth = 100
```

so the RHS of the CUDA code exceeds 2147483648 and turns into negative. `inputData` pointer then points to some weird memory location.

An easy fix is to do the multiplication in `int64_t`

```diff
diff --git a/aten/src/ATen/native/cuda/DilatedMaxPool3d.cu b/aten/src/ATen/native/cuda/DilatedMaxPool3d.cu
index e6eacbb842..10c8ebb958 100644
--- a/aten/src/ATen/native/cuda/DilatedMaxPool3d.cu
+++ b/aten/src/ATen/native/cuda/DilatedMaxPool3d.cu
@@ -53,7 +53,7 @@ __global__ static void max_pool3d_with_indices_single_out_frame(
       wStart += dilationW;
 
     int maxIndex =  tStart * iheight * iwidth + hStart * iwidth + wStart;
-    inputData += slice * itime * iheight * iwidth;
+    inputData += static_cast<int64_t>(slice) * itime * iheight * iwidth;
 
     scalar_t max = at::numeric_limits<scalar_t>::lower_bound(); // -Infinity
 ```

or we can add a template argument like `bool use_32bit_indexing` to instantiate another version, which would make the binary size slightly larger (scalar_t x bool x arch?)

cc @ngimel  would any of these be an acceptable fix?

**Comment by ngimel** [comment]
I've opened a new issue for max pooling.
