### ISSUE TITLE
CosineAnnealingWarmRestarts LR scheduler fails when lash_epoch != -1

### ISSUE THREAD

**Issue by aclex** [pytorch/pytorch#52236]
## 🐛 Bug

`torch.optim.lr_scheduler.CosineAnnealingWarmRestarts` construction fails, when `last_epoch` parameter isn't equal to `-1` (i.e., the user wants to continue scheduling from the specified epoch).

## To Reproduce

```python
import torch

l = torch.nn.Linear(20, 30)
op = torch.optim.SGD([{"params": l.parameters(), "initial_lr": 0.01}], lr=0.01)
sch = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(op, 1, last_epoch=1)
```

The output as of current `master` is something like that:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 965, in __init__
    super(CosineAnnealingWarmRestarts, self).__init__(optimizer, last_epoch, verbose)
  File "/usr/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 79, in __init__
    self.step()
  File "/usr/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 1008, in step
    self.T_cur = self.T_cur + 1
AttributeError: 'CosineAnnealingWarmRestarts' object has no attribute 'T_cur'
```

## Expected behavior

No output meaning the construction succeeded.

## Environment

PyTorch version: 1.7.0a0+57bffc3
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Gentoo/Linux (x86_64)
GCC version: (Gentoo 9.3.0-r2 p4) 9.3.0
Clang version: 11.0.0
CMake version: version 3.18.5

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.7.0a0
[pip3] torchvision==0.8.0a0
[conda] Could not collect

**Comment by Ir1d** [comment]
hi @vincentqb seems #49631 fixes this
