### ISSUE TITLE
🐛 memory leaks with coalesce method

### ISSUE THREAD

**Issue by aocsa** [pytorch/pytorch#52253]
## 🐛 Bug

I've  found out a couple of memory leaks with the algorithm for `sparse_sum` and `sparse_matmul` when I run the test using `CUDATestBase` as base class for `test_sparse.py`.

## To Reproduce

```python
import torch

def test_sparse_sum():
    device = 'cuda'
    i = torch.tensor([[0], [4]], dtype=torch.long, device=device)
    v = torch.tensor([[[-0.4567, -1.8797,  0.0380,  1.4316]]], dtype=torch.double, device=device)
    S = torch.sparse_coo_tensor(i, v, dtype=torch.double, device=device)
    S = S.coalesce()
    S.requires_grad_(True) # when this is True this line cause the memory leak
    print(S)
    f = torch.sparse.sum(S)

test_sparse_sum()
torch.cuda.empty_cache()

```
generates: 

```
cuda-memcheck --leak-check full  python test/test_sparse.py 
========= CUDA-MEMCHECK
/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  warnings.warn(
s/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  warnings.warn(
None
>> _sparse_sum(const SparseTensor& input)
========= Leaked 2097152 bytes at 0x7efecac00000
=========     Saved host backtrace up to driver entry point at cudaMalloc time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuMemAlloc_v2 + 0x1b7) [0x2b8257]
=========     Host Frame:/usr/local/cuda-11.0/lib64/libcudart.so.11.0 [0x32ffe]
=========     Host Frame:/usr/local/cuda-11.0/lib64/libcudart.so.11.0 [0x1032b]
=========     Host Frame:/usr/local/cuda-11.0/lib64/libcudart.so.11.0 (cudaMalloc + 0x107) [0x3dab7]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libc10_cuda.so [0x2b035]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libc10_cuda.so [0x28e0a]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libc10_cuda.so [0x2c42b]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libc10_cuda.so [0x2d1e3]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cuda.so (_ZN2at6native10empty_cudaEN3c108ArrayRefIlEENS1_8optionalINS1_10ScalarTypeEEENS4_INS1_6LayoutEEENS4_INS1_6DeviceEEENS4_IbEENS4_INS1_12MemoryFormatEEE + 0x187) [0x372a7fa]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cuda.so [0x3ad1684]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cuda.so [0x3c1d887]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x243fc6d]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x26ae7e6]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x272169c]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x273eb51]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x243fc6d]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so (_ZN2at5emptyEN3c108ArrayRefIlEENS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE + 0x736) [0x202424b]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so (_ZN2at6native5randnEN3c108ArrayRefIlEENS1_8optionalINS_9GeneratorEEERKNS1_13TensorOptionsE + 0x64) [0x1d5d529]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so (_ZN2at6native5randnEN3c108ArrayRefIlEERKNS1_13TensorOptionsE + 0x5d) [0x1d5d47a]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x2a0dfb8]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x2a26013]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x2b247fb]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x2465073]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x26c8461]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x272812c]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x274718b]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so [0x2465073]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_cpu.so (_ZN2at5randnEN3c108ArrayRefIlEENS0_13TensorOptionsE + 0x68a) [0x20dada2]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_python.so [0x744178]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_python.so [0x957a73]
=========     Host Frame:/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/lib/libtorch_python.so [0x958aef]
=========     Host Frame:python [0x15eed5]
=========     Host Frame:python (_PyObject_MakeTpCall + 0x316) [0x145b26]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x55a9) [0x1e3939]
=========     Host Frame:python (_PyFunction_Vectorcall + 0x19a) [0x19f6ca]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x3ba) [0x1de74a]
=========     Host Frame:python [0x1385a0]
=========     Host Frame:python [0x1aba67]
=========     Host Frame:python (_PyObject_MakeTpCall + 0x3c6) [0x145bd6]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4e0a) [0x1e319a]
=========     Host Frame:python [0x1385a0]
=========     Host Frame:python [0x19fefa]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x3ba) [0x1de74a]
=========     Host Frame:python [0x138dd0]
=========     Host Frame:python (_PyFunction_Vectorcall + 0x336) [0x19f866]
=========     Host Frame:python [0x1a00d3]
=========     Host Frame:python (_PyObject_Call + 0x10b) [0x15f2db]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x2d4c) [0x1e10dc]
=========     Host Frame:python [0x138dd0]
=========     Host Frame:python [0x19fefa]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x3ba) [0x1de74a]
=========     Host Frame:python (_PyFunction_Vectorcall + 0x19a) [0x19f6ca]
=========
F
======================================================================
FAIL: test_sparse_sum_cuda_float64 (__main__.TestSparseCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/testing/_internal/common_utils.py", line 887, in wrapper
    method(*args, **kwargs)
  File "/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/testing/_internal/common_utils.py", line 887, in wrapper
    method(*args, **kwargs)
  File "/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/testing/_internal/common_utils.py", line 712, in __exit__
    self.testcase.assertEqual(
  File "/home/alexander/git/Quansight/pytorch_sd_elwise_matmul/torch/testing/_internal/common_utils.py", line 1228, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing 0 and 1024 gives a difference of 1024, but the allowed difference with rtol=0 and atol=0 is only 0!
__main__.TestSparseCUDA.test_sparse_sum_cuda_float64 leaked 1024 bytes CUDA memory on device 0

----------------------------------------------------------------------
```
## Expected behavior

No leaks with cuda-memcheck 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @aocsa @nikitaved @pearu @mruberry

**Comment by mruberry** [comment]
We would definitely accept a PR fixing these!
