### ISSUE TITLE
Unlucky batch->device split by DataParallel causes an exception

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#52260]
I have a batch shape of `[36, 4, 147, 64, 64]` and 7 devices on. Somehow it cuts it into exactly 6 slices, and the last device gets an empty input tuple, so makes a nasty exception. If the tuple is empty it should not simply call the replica instead of trying to unpack the tuple anway.

I think I already commented on a related problem somewhere, but can't find the issue right now

```
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 39, in parallel_apply
    if kwargs_tup is not None:
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 6 on device 6.
Original Traceback (most recent call last):
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```

**Comment by likenneth** [comment]
Also met this issue although the DP is deprecated now. We know: Actual BS <= Set BS. And the error will happen with Actual BS < Number of GPU. Thus raising the Set BS will reduce the probability of going unlucky, but this is not we want :)
