### ISSUE TITLE
DISABLED test_send_recv_with_tag (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#52284]
## 🐛 Bug

https://app.circleci.com/pipelines/github/pytorch/pytorch/273841/workflows/6653ba97-9e41-42b0-9147-da66f708ccff/jobs/10918797/tests

```
Feb 15 18:20:15   test_send_recv_with_tag (__main__.TestDistBackendWithFork) ... ERROR:root:Caught exception: 
Feb 15 18:20:15 Traceback (most recent call last):
Feb 15 18:20:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 289, in wrapper
Feb 15 18:20:15     fn()
Feb 15 18:20:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 1002, in test_send_recv_with_tag
Feb 15 18:20:15     self.assertEqual(event_count, expected_event_count)
Feb 15 18:20:15   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1228, in assertEqual
Feb 15 18:20:15     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Feb 15 18:20:15   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
Feb 15 18:20:15     raise self.failureException(msg)
Feb 15 18:20:15 AssertionError: False is not true : Scalars failed to compare as equal! Comparing 1 and 2 gives a difference of 1, but the allowed difference with rtol=0 and atol=0 is only 0!
Feb 15 18:20:15 exiting process with exit code: 10
Feb 15 18:20:15 Process 0 terminated with exit code 10, terminating remaining processes.
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
ssh'd into https://app.circleci.com/pipelines/github/pytorch/pytorch/274605/workflows/5c8f249f-6464-4202-add1-869dec1f5990/jobs/10974822 and ran the test thousands of times, but it succeeded every time which is strange, since I saw this test fail repeatedly before I disabled it. Will re-enable for now to see if this continues to occur.

**Comment by rohan-varma** [comment]
Reopen as the issue occurs again: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/11002713/output/107/0?file=true&allocation-id=602ef6cd42bb1e0da6afde7c-0-build%2F6631F048

**Comment by rohan-varma** [comment]
Close since the test name has changed: https://github.com/pytorch/pytorch/issues/56690
