### ISSUE TITLE
[windows] test_variant_consistency_eager_masked_fill_cuda_complex128: Misaligned Address CUDA

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#52437]
```
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 292, in instantiated_test
    raise rte
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 265, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 249, in test_variant_consistency_eager
    **sample.kwargs)
RuntimeError: CUDA error: misaligned address
```

Reference: https://app.circleci.com/pipelines/github/pytorch/pytorch/274941/workflows/e45fcb4a-8347-4bf8-b590-f82aaafbc52c/jobs/10981321

Looks similar to #51980

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mszhanyi** [comment]
from the log, the cuda version is 11.2 too

**Comment by peterjc123** [comment]
So, is this one fixed as it looks similar to https://github.com/pytorch/pytorch/issues/51980?

**Comment by kshitij12345** [comment]
Yes, it is fixed in https://github.com/pytorch/pytorch/pull/54596. Thanks for pointing that out!!
