### ISSUE TITLE
torch::jit::load crashes with "memmove_avx_unaligned_erms" error

### ISSUE THREAD

**Issue by christian-rauch** [pytorch/pytorch#52453]
## 🐛 Bug

Under some unknown circumstances, loading model via `torch::jit::load` on CUDA 11.0 results in a crash:
```
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:436
#1  0x00007fff868350b4 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::forward_iterator_tag) [clone .isra.102] ()
    at [...]/install/torch_cpp/lib/libc10.so
#2  0x00007fff86835e78 in c10::Device::Device(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at [...]/install/torch_cpp/lib/libc10.so
#3  0x00007fffe2a7663d in torch::jit::Unpickler::readInstruction() () at [...]/install/torch_cpp/lib/libtorch_cpu.so
#4  0x00007fffe2a78540 in torch::jit::Unpickler::run() () at [...]/install/torch_cpp/lib/libtorch_cpu.so
#5  0x00007fffe2a78af1 in torch::jit::Unpickler::parse_ivalue() () at [...]/install/torch_cpp/lib/libtorch_cpu.so
#6  0x00007fffe2a1c9c2 in torch::jit::readArchiveAndTensors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&) () at [...]/install/torch_cpp/lib/libtorch_cpu.so
#7  0x00007fffe2a1ccdd in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.789] () at [...]/install/torch_cpp/lib/libtorch_cpu.so
#8  0x00007fffe2a1f605 in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::deserialize(c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) [clone .constprop.788] () at [...]/install/torch_cpp/lib/libtorch_cpu.so
#9  0x00007fffe2a1fbd9 in torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) ()
    at [...]/install/torch_cpp/lib/libtorch_cpu.so
#10 0x00007fffe2a22535 in torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) () at [...]/install/torch_cpp/lib/libtorch_cpu.so
```

The backtrace only mentiones `libtorch_cpu.so` although I am linking both libraries:
```
libtorch_cpu.so => [...]/install/torch_cpp/lib/libtorch_cpu.so
    libgomp-75eea7e8.so.1 => [...]/install/torch_cpp/lib/libgomp-75eea7e8.so.1
    libcudart-3f3c6934.so.11.0 => [...]/install/torch_cpp/lib/libcudart-3f3c6934.so.11.0
libtorch_cuda.so => [...]/install/torch_cpp/lib/libtorch_cuda.so
    libc10_cuda.so => [...]/install/torch_cpp/lib/libc10_cuda.so
    libnvToolsExt-24de1d56.so.1 => [...]/install/torch_cpp/lib/libnvToolsExt-24de1d56.so.1
libc10.so => [...]/install/torch_cpp/lib/libc10.so
libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
libnvToolsExt.so.1 => /usr/local/cuda/targets/x86_64-linux/lib/libnvToolsExt.so.1
```

This issue does not occur on CPU with the same library and saved model.

## To Reproduce

I cannot share the original project in which this issue occurs. This project P 1) links a library L that implements loading the model and data I/O and in turn links to `libtorch_cpu.so` and `libtorch_cuda.so from https://download.pytorch.org/libtorch/cu110/libtorch-cxx11-abi-shared-with-deps-1.7.1%2Bcu110.zip, and 2) links directly to CUDA for other purposes.

I cannot reproduce this on a simpler example. So this might be related to linking CUDA multiple times in the executable.

## Expected behaviour

`torch::jit::load` should not crash and at least present an error or warning to inform about any issues.

## Environment

```
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1650
Nvidia driver version: 460.32.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.0
[pip3] torchvision==0.8.1
[conda] Could not collect
```

## Additional context

cc @gmagogsfm

**Comment by ansley** [comment]
We haven't been able to reproduce the issue for the reasons you stated in your original post. We believe it may be an error with your linking code. Please reopen an issue if you can provide a minimal reproducible example. Thank you!
