### ISSUE TITLE
[JIT] nn.Sequential of nn.Module with input type List[torch.Tensor] inferred to torch.Tensor

### ISSUE THREAD

**Issue by lamhoangtung** [pytorch/pytorch#52588]
## 🐛 Bug

I'm trying to convert a `nn.Sequential` model that consist of some `nn.Module` that had input type `List[torch.Tensor]` to Scripted model. But the TorchScript seems to infer the input type for those child module to `torch.Tensor` only 
## To Reproduce

1. Run this block of code

```python
import torch
import torch.nn as nn
from typing import List

class ModelWithInputAsListOfTensor(nn.Module):
    def __init__(self):
        super(ModelWithInputAsListOfTensor, self).__init__()
        self.x = 2

    def forward(self, x: List[torch.Tensor]) -> List[torch.Tensor]:
        # print("Receiving type", type(x), len(x), type(x[0]))
        # print("Receiving list of tensor", len(x), type(x[0]))
        for each in x:
            each *= self.x
        return x

model = nn.Sequential(
    ModelWithInputAsListOfTensor(),
    ModelWithInputAsListOfTensor()
)

# Original model
test_input: List[torch.Tensor] = [torch.ones((2, 2)), torch.ones((3, 3)), torch.ones((4, 4))]
res = model(test_input)
print(res)

# Scripted model
scripted_model = torch.jit.script(model)
print(scripted_model)

print("---------------------")

# Input as typing.List[torch.Tensor]
test_input: List[torch.Tensor] = [torch.ones((2, 2)), torch.ones((3, 3)), torch.ones((4, 4))]
res = scripted_model(test_input)
print(res)

print("---------------------")

# Input as torch.jit.annotate(List[torch.Tensor])
test_input = torch.jit.annotate(List[torch.Tensor], [torch.ones((2, 2)), torch.ones((3, 3)), torch.ones((4, 4))])
res = scripted_model(test_input)
print(res)
```

2. Then you will get this output:
```console
[tensor([[4., 4.],
        [4., 4.]]), tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]), tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])]
RecursiveScriptModule(
  original_name=Sequential
  (0): RecursiveScriptModule(original_name=ModelWithInputAsListOfTensor)
  (1): RecursiveScriptModule(original_name=ModelWithInputAsListOfTensor)
)
---------------------
Traceback (most recent call last):
  File "tests/test_seq.py", line 32, in <module>
    res = scripted_model(test_input)
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: forward() Expected a value of type 'Tensor (inferred)' for argument 'input' but instead found type 'list'.
Inferred 'input' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 1
Value: [tensor([[1., 1.],
        [1., 1.]]), tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])]
Declaration: forward(__torch__.torch.nn.modules.container.Sequential self, Tensor input) -> (Tensor[])
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

Which indicate that the normal Pytorch model work! And TorchScript seems to infer the input type for `ModelWithInputAsListOfTensor` to `torch.Tensor`, instead of `List[torch.Tensor]`.

I also tried `torch.jit.annotate(List[torch.Tensor])` but it does not work as well

## Expected behavior

The scripted model can be infer properly. `nn.Sequential` with `nn.Module` that had input type of `List[torch.Tensor]` should be infer as `List[torch.Tensor]`, not `torch.Tensor`

## Environment

```console
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.18.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchtext==0.6.0
[pip3] torchvision==0.8.2
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.2.0            py37hc64f4ea_0  
[conda] mkl_random                1.1.1            py37h959d312_0  
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] pytorch                   1.7.1                   py3.7_0    pytorch
[conda] tensorflow                1.14.0          mkl_py37h085be34_0  
[conda] tensorflow-base           1.14.0          mkl_py37h5a24fda_0  
[conda] torchaudio                0.7.2                      py37    pytorch
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.8.2                  py37_cpu    pytorch
```

## Additional context

Am I doing something wrong ...... hmmm. Anw, thanks for checking by

cc @gmagogsfm

**Comment by ansley** [comment]
The fix for this is to subclass `nn.Sequential` and redeclare `forward` with the input typed as a list of tensors. We'll add a note to the documentation, as it's not necessarily intuitive

**Comment by lamhoangtung** [comment]
@ansley. My own fix is to use `nn.ModuleList` instead of `nn.Sequential` since they had the same state_dict structure. But it would require to rewrite a forward pass a little bit. Anw, I thinks this is a bug and should be fixed.

**Comment by ankursakhuja** [comment]
Hi @ansley, @lamhoangtung :

Just checking if there's been any updates on this issue w.r.t. PyTorch 1.9 ?
I'm facing a similar issue and was wondering if we currently have a workaround?
Apparently the workaround suggested above won't work because as detailed in https://github.com/pytorch/pytorch/issues/42885#issuecomment-678385108, inheritance is not currently supported in TorchScript (?).

Basically I need to export a model using TorchScript. This model uses a nn.Sequential that inputs and outputs Tensor[List].
However the JIT compiler complains of type mismatch because it's default type inference is Tensor, even after explicit annotation.
Would appreciate any leads for the current status / workarounds.

Thanks,
Ankur

**Comment by dav-ell** [comment]
Having the same problem here. Any udpates?
