### ISSUE TITLE
Add custom types to PyTorch

### ISSUE THREAD

**Issue by RaulMurillo** [pytorch/pytorch#52673]
## ❓ Questions and Help

Is it possible to create a PyTorch extension module that adds support for a new type of tensors?

As far as I know, in the case of NumPy,  it is possible to define a [Python extension type](https://docs.python.org/3/extending/newtypes_tutorial.html), as well as adding built-in support for this new type to NumPy with an [extension module](https://numpy.org/doc/stable/user/c-info.how-to-extend.html) that allows generating ndarrays of this custom type. Examples of this are the [rational](https://github.com/numpy/numpy-dtypes/tree/master/npytypes/rational) and [quaternion](https://github.com/moble/quaternion) packages.

Therefore, I wonder if there is a similar manner to do this (or to extend the previous NumPy dtypes) in PyTorch, so that it is possible to declare tensors of such type and perform math calculations with them (of course, all the arithmetic operations should be re-defined for this new type).

I read the [Extending PyTorch](https://pytorch.org/docs/stable/notes/extending.html#extending-torch) documentation, although I guess this way is not the most efficient one and it has some limitations, as the need to generate tensors of already-known types in some cases.
Rather, I would be looking to write an extension module such as those aforementioned (the process of which is detailed at https://numpy.org/doc/stable/user/c-info.how-to-extend.html), so that it includes a new `torch.dtype`.

Currently, if trying to create a tensor of any custom type, let's say `my_type` (which is numeric and supported either in Python or NumPy via an extension module), the following error arises:
```python
>>> arr = np.array([1., 3., 5., 7., 9.], dtype=np.my_type)
>>> arr
array([1, 2, 3, 4], dtype=my_type)
>>> torch.tensor([1., 3., 5., 7., 9.], dtype=np.my_type)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tensor(): argument 'dtype' must be torch.dtype, not type
>>> torch.tensor(arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert np.ndarray of type my_module.my_type. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

The main problem is that the custom dtype that I am defining is not based on float or ints structures, but rather on a kind of custom floating-point format whose implementation uses unsigned int for storage and redefines all arithmetic operations bit-wise.

**Comment by anjali411** [comment]
Before complex number support became native, complex dtypes were supported out-of-tree through a PyTorch extension written by @dylanbespalko here: https://gitlab.com/pytorch-complex/pytorch-cpu-strided-complex/-/tree/master

**Comment by albanD** [comment]
Hi,

You have two options here:
- Extend from python to make your python class a Tensor-like object. You can then overwrite the method you need on that class. This is the extending doc you mentioned above.
- Extend from C++ by creating a new TensorImpl with corresponding dispatcher key. You can then register your implementation to the dispatcher properly. This is what third party libs like torch/xla or the complex one @anjali411 linked above is doing to create new Tensor type.

Note that the `torch.dtype` is a python construct though and so there is no real way to extend it atm.
