### ISSUE TITLE
CUDA Illegal memory access for softmax

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#52715]
Related https://github.com/pytorch/pytorch/issues/52716

```python
import torch
x = torch.randn((1100000000, 2), device="cuda:0", dtype=torch.float16, requires_grad=True)
y = torch.nn.functional.log_softmax(x, dim=-1)
y.backward(y)
torch.cuda.synchronize()
```
```
Traceback (most recent call last):
  File "/home/gaoxiang/misc/softmax.py", line 6, in <module>
    torch.cuda.synchronize()
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 402, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
Exception raised from device_synchronize at ../c10/cuda/CUDAFunctions.cpp:135 (most recent call first):
frame #0: <unknown function> + 0x8101f (0x7fd7fefe201f in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x80d85 (0x7fd7fefe1d85 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x80b49 (0x7fd7fefe1b49 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #3: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x4c (0x7fd82bf16102 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x40 (0x7fd7fefe0dc0 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #5: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7b (0x7fd7fefdf58c in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #6: c10::cuda::device_synchronize() + 0x7c (0x7fd7ff04e27b in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #7: THCPModule_cudaSynchronize(_object*, _object*) + 0x3f (0x7fd838be3dec in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #21: __libc_start_main + 0xd5 (0x7fd8659aeb25 in /usr/lib/libc.so.6)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel

**Comment by vadimkantorov** [comment]
i hope these fixed can get into 1.8.0 ...
