### ISSUE TITLE
CUDA error: invalid configuration argument for softmax

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#52716]
Related: https://github.com/pytorch/pytorch/issues/52715
```python
import torch
x = torch.randn((2200000000, 1), device="cuda:0", dtype=torch.float16, requires_grad=True)
torch.cuda.profiler.start()
y = torch.nn.functional.log_softmax(x, dim=-1)
y.backward(y)
torch.cuda.profiler.stop()
torch.cuda.synchronize()
```
```
Traceback (most recent call last):
  File "/home/gaoxiang/misc/softmax.py", line 4, in <module>
    y = torch.nn.functional.log_softmax(x, dim=-1)
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 1672, in log_softmax
    ret = input.log_softmax(dim)
RuntimeError: CUDA error: invalid configuration argument
Exception raised from dispatch_softmax_forward at /home/gaoxiang/pytorch-cmake/aten/src/ATen/native/cuda/PersistentSoftmax.cuh:268 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x5c (0x7f16cef45e3c in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x64 (0x7f16cef19828 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: void dispatch_softmax_forward<c10::Half, c10::Half, float, true>(c10::Half*, c10::Half const*, int, int, int) + 0x2ef (0x7f16d0aa249f in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x1b3c2dd (0x7f16d0aa52dd in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::Tensor at::native::(anonymous namespace)::host_softmax<at::native::(anonymous namespace)::LogSoftMaxForwardEpilogue, true>(at::Tensor const&, long, bool) + 0x485 (0x7f16d0aa7455 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::log_softmax_cuda(at::Tensor const&, long, bool) + 0x21 (0x7f16d0a9f0e1 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x2608468 (0x7f16d1571468 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x2608518 (0x7f16d1571518 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x153562a (0x7f16f56b062a in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x1536289 (0x7f16f56b1289 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2c9e5e6 (0x7f16f6e195e6 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x2c9e75b (0x7f16f6e1975b in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #12: at::_log_softmax(at::Tensor const&, long, bool) + 0x13c (0x7f16f53a15ac in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #13: at::native::log_softmax(at::Tensor const&, long, c10::optional<c10::ScalarType>) + 0x75 (0x7f16f50cbb95 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x17e95f8 (0x7f16f59645f8 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x17e9697 (0x7f16f5964697 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #16: at::Tensor::log_softmax(long, c10::optional<c10::ScalarType>) const + 0x137 (0x7f16f5acba97 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x55c212 (0x7f16fc960212 in /home/gaoxiang/.local/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #32: __libc_start_main + 0xd5 (0x7f1729217b25 in /usr/lib/libc.so.6)
```

cc @ngimel

**Comment by zasdfgbnm** [comment]
fixed
