### ISSUE TITLE
test_hooks_cpp ASAN detected memory corruption

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5281]
```
[~/Dev/pytorch-asan] ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer ASAN_OPTIONS=symbolize=1 python test/test_autograd.py  TestAutograd.test_hooks_cpp                               
=================================================================
==1620364== ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f6a7b4ae99c at pc 0x7f6a86545a0b bp 0x7ffee2ed7830 sp 0x7ffee2ed7828
READ of size 4 at 0x7f6a7b4ae99c thread T0
    #0 0x7f6a86545a0a in torch::autograd::Variable::output_nr() const /data/users/ezyang/pytorch-asan/torch/csrc/autograd/variable.h:498
    #1 0x7f6a8691996b in torch::autograd::SavedVariable::SavedVariable(torch::autograd::Variable const&, bool) /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/save
d_variable.cpp:17
    #2 0x7f6a86ab2353 in torch::autograd::VariableType::thnn_batch_norm_forward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tenso
r const&, bool, double, double) const /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/VariableType.cpp:16613
    #3 0x7f6a6b1288b6 in at::Type::thnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, doubl
e) const /home/ezyang/Dev/pytorch-asan/torch/lib/build/aten/src/ATen/ATen/Type.cpp:2872
    #4 0x7f6a86ab110b in torch::autograd::VariableType::thnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&
, bool, double, double) const /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/VariableType.cpp:16561
    #5 0x7f6a6ac3a760 in at::thnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double) /ho
me/ezyang/Dev/pytorch-asan/torch/lib/build/aten/src/ATen/ATen/Functions.h:2681
    #6 0x7f6a6ac3ada0 in at::native::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double, 
bool) /home/ezyang/Dev/pytorch-asan/aten/src/ATen/native/BatchNorm.cpp:57
    #7 0x7f6a6b12ba53 in at::Type::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double, bo
ol) const /home/ezyang/Dev/pytorch-asan/torch/lib/build/aten/src/ATen/ATen/Type.cpp:3061
    #8 0x7f6a86ad9cb7 in torch::autograd::VariableType::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, boo
l, double, double, bool) const /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/VariableType.cpp:18052
    #9 0x7f6a86cea171 in at::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double, bool) /d
ata/users/ezyang/pytorch-asan/torch/lib/tmp_install/include/ATen/Functions.h:2849
    #10 0x7f6a86dbf015 in torch::autograd::dispatch_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, d
ouble, double, bool) /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/python_torch_functions_dispatch.h:755
    #11 0x7f6a86d1a227 in torch::autograd::THPVariable_batch_norm(_object*, _object*, _object*) /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/python_to
rch_functions.cpp:1392
    #12 0x55629ea72fd3 in _PyCFunction_FastCallDict (/data/users/ezyang/pytorch-asan-env/bin/python3.6+0x10efd3)
    #13 0x55629eb00beb in call_function (/data/users/ezyang/pytorch-asan-env/bin/python3.6+0x19cbeb)
    #14 0x55629eb25199 in _PyEval_EvalFrameDefault (/data/users/ezyang/pytorch-asan-env/bin/python3.6+0x1c1199)
    #15 0x55629eaf99a5 in _PyEval_EvalCodeWithName (/data/users/ezyang/pytorch-asan-env/bin/python3.6+0x1959a5)
```

**Comment by ezyang** [comment]
Another instance of this error:

```
==1120693== ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f947ba2c99c at pc 0x7f9486ac3a0b bp 0x7fffe28fe990 sp 0x7fffe28fe980
READ of size 4 at 0x7f947ba2c99c thread T0
    #0 0x7f9486ac3a0a in torch::autograd::Variable::output_nr() const /data/users/ezyang/pytorch-asan/torch/csrc/autograd/variable.h:498
    #1 0x7f9486e9796b in torch::autograd::SavedVariable::SavedVariable(torch::autograd::Variable const&, bool) /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/saved_v
ariable.cpp:17
    #2 0x7f9487030353 in torch::autograd::VariableType::thnn_batch_norm_forward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor c
onst&, bool, double, double) const /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/VariableType.cpp:16613
    #3 0x7f946b6a68b6 in at::Type::thnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double) 
const /home/ezyang/Dev/pytorch-asan/torch/lib/build/aten/src/ATen/ATen/Type.cpp:2872
    #4 0x7f948702f10b in torch::autograd::VariableType::thnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, b
ool, double, double) const /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/VariableType.cpp:16561
    #5 0x7f946b1b8760 in at::thnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double) /home/
ezyang/Dev/pytorch-asan/torch/lib/build/aten/src/ATen/ATen/Functions.h:2681
    #6 0x7f946b1b8da0 in at::native::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double, boo
l) /home/ezyang/Dev/pytorch-asan/aten/src/ATen/native/BatchNorm.cpp:57
    #7 0x7f946b6a9a53 in at::Type::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double, bool)
 const /home/ezyang/Dev/pytorch-asan/torch/lib/build/aten/src/ATen/ATen/Type.cpp:3061
    #8 0x7f9487057cb7 in torch::autograd::VariableType::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, 
double, double, bool) const /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/VariableType.cpp:18052
    #9 0x7f9487268171 in at::batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double, bool) /data
/users/ezyang/pytorch-asan/torch/lib/tmp_install/include/ATen/Functions.h:2849
    #10 0x7f948733d015 in torch::autograd::dispatch_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, doub
le, double, bool) /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/python_torch_functions_dispatch.h:755
    #11 0x7f9487298227 in torch::autograd::THPVariable_batch_norm(_object*, _object*, _object*) /home/ezyang/Dev/pytorch-asan/torch/csrc/autograd/generated/python_torch
_functions.cpp:1392
    #12 0x55ac80e88fd3 in _PyCFunction_FastCallDict (/data/users/ezyang/pytorch-asan-env/bin/python3.6+0x10efd3)
```
