### ISSUE TITLE
Exporting a ResnetGenerator from UGTIT to a onnx model failed

### ISSUE THREAD

**Issue by JustLuoyu** [pytorch/pytorch#52826]
## 🐛 Bug

Traceback (most recent call last):
  File "C:/Users/LY/PycharmProjects/CartoonCamera/ugatit/convert2onnx.py", line 38, in <module>
    test_export()
  File "C:/Users/LY/PycharmProjects/CartoonCamera/ugatit/convert2onnx.py", line 35, in test_export
    torch.onnx.export(model, x.to(device), 'resnet.onnx')
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\utils.py", line 930, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "C:\Users\LY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\onnx\symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator var to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

## To Reproduce

1. check out UGTIT pytorch code
2. run my test export function:
def test_export():
    model = ResnetGenerator(input_nc=3, output_nc=3, ngf=32, n_blocks=4, img_size=224, light=False)
    x = torch.randn((1, 3, 224, 224))
    torch.onnx.export(model, x.to(device), 'resnet.onnx')
class ResnetGenerator is within UGTIT's networks.py

## Environment

PyTorch version: 1.7.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 企业版
GCC version: Could not collect
Clang version: 10.0.0 
CMake version: version 3.18.5

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 456.71
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] facenet-pytorch==2.5.1
[pip3] numpy==1.18.4
[pip3] torch==1.7.1+cu101
[pip3] torchaudio==0.7.2
[pip3] torchfile==0.1.0
[pip3] torchvision==0.8.2+cu101
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
Support for `var` operator was added in https://github.com/pytorch/pytorch/pull/45678. If this is still an issue with the latest PyTorch nightly, please open a new issue with more detailed reproduction instructions. Ideally something we can copy-paste to reproduce the issue.
