### ISSUE TITLE
Turn on ASAN in CI

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5283]
This is a tracking issue for turning on address sanitizer in our CI, so we can more easily catch memory corruption errors. These errors can be especially pernicious, because memory corruption often results in nondeterministic failures, or failures which only occur on certain platforms (e.g., Windows) because memory layout is different.

As a user, it is somewhat difficult to operate address sanitizer correctly with PyTorch, because (1) PyTorch historically did not propagate `CFLAGS` to libraries (fixed in https://github.com/pytorch/pytorch/pull/5269) and (2) PyTorch compiled with ASAN will be dynamically loaded, which means you must `LD_PRELOAD` the ASAN dynamic library before running Python. This is an error-prone process because there are usually multiple copies of `libasan.so` on your system, one per compiler toolchain, and there is no obvious indication which library the compiler is expecting to be linked against (asked in https://stackoverflow.com/questions/48833176/get-location-of-libasan-from-gcc-clang)

Supposing you overcome all of these problems. Then you will have an ASAN build of PyTorch which is sufficient to catch bugs, if you have a reproducing test case. However, if we intend to run ASAN in CI, we would like to run ASAN on the *entirety* of our test suite. However, our C code is varied and interesting enough that I have managed to cause ASAN bugs in a number of different configurations.

**gcc 4.8.5 20150623 (Red Hat 4.8.5-16).** This is the default devgpu GCC. You have to `yum install libasan` to get the shared library you need at `/usr/lib64/libasan.so.0` but it has not raised spurious problems as far as I can tell.

**gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5** This GCC (same version, no less) from Ubuntu triggers an CHECK failure in ASAN:

```
test_AdaptiveMaxPool1d_indices (__main__.TestNN) ... ==7948==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/asan/asan_interceptors.cc:384 "((__interception::real___cxa_throw)) != (0)" (0x0, 0x0)
    #0 0x7fbb6a5b0bc5  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe4bc5)
    #1 0x7fbb6a5cd8f5 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x1018f5)
    #2 0x7fbb6a503e8c in __interceptor___cxa_throw (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37e8c)
    #3 0x7fbb4b31c496 in torch::autograd::SavedVariable::unpack(std::shared_ptr<torch::autograd::Function>) const torch/csrc/autograd/saved_variable.cpp:42
```

This problem also occurred with **gcc-7 (Ubuntu 7.2.0-1ubuntu1~14.04) 7.2.0**. Upstream bug filed at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84428

**gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609.**

This one had troubles with the shadow mapping.

```
jenkins@ff742997f986:~/pytorch-1$ ASAN_OPTIONS=protect_shadow_gap=0 LD_PRELOAD=/usr/lib/x86_64-linux
-gnu/libasan.so.2 python test/test_nn.py -v TestNN.test_AdaptiveMaxPool1d_indices
==4890==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.
==4890==ASan shadow was supposed to be located in the [0x00007fff7000-0x10007fff7fff] range.
==4890==Process memory map follows:
        0x00007fff7000-0x00008fff7000
        0x00008fff7000-0x02008fff7000
        0x02008fff7000-0x10007fff8000
```

**clang version 3.9.1-4ubuntu3~14.04.3 (tags/RELEASE_391/rc2)** 

`-fsanitize=address` does not work at all:

```
jenkins@37ecc4612171:~/pytorch$ clang-3.9 -fsanitize=address test.c             
                                 
/usr/bin/ld: /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib/linux/libclang_rt.asan
-x86_64.a(asan_allocator.cc.o): unrecognized relocation (0x2a) in section `.text
'
/usr/bin/ld: final link failed: Bad value
```

Filed for Ubuntu at https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.9/+bug/1750099

**clang version 5.0.0-3~16.04.1 (tags/RELEASE_500/final)** This one also has the "Shadow memory range interleaves with an existing memory mapping" error if you just pass `CFLAGS=-fsanitize=address`, but I managed to diagnose the underlying issue and solve the problem: https://github.com/google/sanitizers/issues/918

----

Based on the situation, I think the correct plan is to plan a clang build on Xenial with ASAN enabled (with the correct parameters.) This will also help us test clang on some more configurations than what our OS X builds are doing.

P.S. One alternative strategy, which may be profitable considering the difficulty of getting ASAN to work on these platforms, is to roll our own poor man versions of ASAN.  This can be quite done by we can manually add redzones around all of our allocations, and then check if the redzone was clobbered when we free. This won't be able to determine the memory corruption as precisely ASAN (you'll only find out it was clobbered at free time) but it would be portable and always available, when you suspect memory corruption. Given that the clang builds seem to now be working, I don't advise going this route.

**Comment by ezyang** [comment]
Merged!
