### ISSUE TITLE
`embedding_bag(..., include_last_offset=True)` should always error if `offsets[-1] != input.size()`

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#52851]
## 🐛 Bug

As far as I can tell, if `embedding_bag` is given `include_last_offset=True`, then the last element of `offsets` is always supposed to be equal to the size of `input`. My understanding is based on the original issue that proposed adding the `include_last_offset` feature: #29019

However, it is possible to set `offsets[-1] != input.size(0)`. This doesn't seem right to me.

## To Reproduce

```python
>>> embeddings = torch.randn(3, 4)

# Here's a basic valid example with include_last_offset=False
>>> torch.nn.functional.embedding_bag(torch.tensor([0, 0, 1, 2, 0]), embeddings, torch.tensor([0, 3]))
tensor([[ 1.0285,  0.6390, -0.9468,  0.8279],
        [ 0.0011,  0.9743, -0.5688,  0.5476]])

# Here's the correct equivalent call with include_last_offset=True, where offsets[-1] == input.size(0)
>>> torch.nn.functional.embedding_bag(torch.tensor([0, 0, 1, 2, 0]), embeddings, torch.tensor([0, 3, 5]), include_last_offset=True)
tensor([[ 1.0285,  0.6390, -0.9468,  0.8279],
        [ 0.0011,  0.9743, -0.5688,  0.5476]])

# It's possible to set offsets[-1] != input.size(0). offsets[-1]==0 would
# indicate that input.size(0) is 0, which is not true in this case
>>> torch.nn.functional.embedding_bag(torch.tensor([0, 0, 1, 2, 0]), embeddings, torch.tensor([0, 3, 0]), include_last_offset=True)
tensor([[ 1.0285,  0.6390, -0.9468,  0.8279],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

# Evidently, CUDA treats this logically faulty case differently than CPU
>>> torch.nn.functional.embedding_bag(torch.tensor([0, 0, 1, 2, 0]).cuda(), embeddings.cuda(), torch.tensor([0, 3, 0]).cuda(), include_last_offset=True)
tensor([[ 1.0285,  0.6390, -0.9468,  0.8279],
        [ 0.0011,  0.9743, -0.5688,  0.5476]], device='cuda:0')

# There is at least a check to prevent offsets[-1] > input.size(0), on CPU,
# but the check should be more strict
>>> torch.nn.functional.embedding_bag(torch.tensor([0, 0, 1, 2, 0]), embeddings, torch.tensor([0, 3, 100]), include_last_offset=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kurtamohler/development_old/pytorch-EmbeddingBag-padding_idx/torch/nn/functional.py", line 2110, in embedding_bag
    ret, _, _, _ = torch.embedding_bag(
RuntimeError: offsets[-1] can not be greater than input's length 5 but got offsets[-1] of 100

# But the offsets[-1] > input.size(0) check does not happen on CUDA
>>> torch.nn.functional.embedding_bag(torch.tensor([0, 0, 1, 2, 0]).cuda(), embeddings.cuda(), torch.tensor([0, 3, 100]).cuda(), include_last_offset=True)
tensor([[ 1.0285,  0.6390, -0.9468,  0.8279],
        [ 0.0011,  0.9743, -0.5688,  0.5476]], device='cuda:0')
```

## Expected behavior

If `include_last_offset=True`, `embedding_bag` should error if `offsets[-1] != input.size()`

## Environment
```
PyTorch version: 1.8.0a0+bc30a6a
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 460.27.04
cuDNN version: /usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.0a0
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.19.4           py39hdbf815f_2    conda-forge
[conda] torch                     1.8.0a0                   dev_0    <develop>
```

**Comment by kurtamohler** [comment]
The `include_last_offset` feature's documentation could be improved as well. I couldn't understand what it was for until I searched for the original issue.

**Comment by jbschlosser** [comment]
@kurtamohler Interesting find! Seems like there is a lot going on here. As you mentioned, the CUDA and CPU versions definitely differ, which is no good:
```python
import torch
from torch.nn.functional import embedding_bag

torch.manual_seed(1)
embeddings = torch.randn(3, 4)
input = torch.tensor([0, 0, 1, 2, 0])

# include_last_offset=False for reference:
print('===== include_last_offset=False =====')
offsets = torch.tensor([0, 3])
print('CPU:', embedding_bag(input, embeddings, offsets))
print('CUDA:', embedding_bag(input.cuda(), embeddings.cuda(), offsets.cuda()))
print()

# Non-monotonically increasing offsets in the middle.
print('===== Non-monotonically increasing offsets in the middle =====')
offsets = torch.tensor([0, 3, 2, 5])
print('CPU:', embedding_bag(input, embeddings, offsets, include_last_offset=True))
print('CUDA:', embedding_bag(input.cuda(), embeddings.cuda(), offsets.cuda(), include_last_offset=True))
print()

# Non-monotonically increasing offsets at the end.
print('===== Non-monotonically increasing offsets at the end =====')
offsets = torch.tensor([0, 3, 2])
print('CPU:', embedding_bag(input, embeddings, offsets, include_last_offset=True))
print('CUDA:', embedding_bag(input.cuda(), embeddings.cuda(), offsets.cuda(), include_last_offset=True))
print()

# Monotonically increasing offsets with offsets[-1] != input.size(0)
print('===== Monotonically increasing offsets with offsets[-1] != input.size(0) =====')
offsets = torch.tensor([0, 3, 4])
print('CPU:', embedding_bag(input, embeddings, offsets, include_last_offset=True))
print('CUDA:', embedding_bag(input.cuda(), embeddings.cuda(), offsets.cuda(), include_last_offset=True))
```

```
===== include_last_offset=False =====
CPU: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [-0.1831, -0.1481, -0.4153,  0.2815]])
CUDA: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [-0.1831, -0.1481, -0.4153,  0.2815]], device='cuda:0')

===== Non-monotonically increasing offsets in the middle =====
CPU: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2727, -0.1541, -0.7845,  0.3149]])
CUDA: .../EmbeddingBag.cu:107: EmbeddingBag_updateOutputKernel_sum_mean:
block: [0,0,0], thread: [0,1,0] Assertion `end >= begin` failed.

===== Non-monotonically increasing offsets at the end =====
CPU: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
CUDA: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [-0.1831, -0.1481, -0.4153,  0.2815]], device='cuda:0')

===== Monotonically increasing offsets with offsets[-1] != input.size(0) =====
CPU: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [-0.5138, -0.2815, -0.4461, -0.0291]])
CUDA: tensor([[ 0.2903,  0.1226, -0.4665,  0.5414],
        [-0.1831, -0.1481, -0.4153,  0.2815]], device='cuda:0')
```
Summary:
1. Non-monotonically increasing `offsets` in the middle (e.g. `[0, 3, 2, 5]`)
  * CPU: Inserts zeros for the bag from 3 to 2; computes correctly for the bag from 2 to 5
  * CUDA: `.../EmbeddingBag.cu:107: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [0,1,0] Assertion 'end >= begin' failed.`
2. Non-monotonically increasing `offsets` at the end (e.g. `[0, 3, 2]`)
  * CPU: Inserts zeros for the bag from 3 to 2
  * CUDA: Ignores the last offset and treats it as `input.size(0)` unconditionally
3. Monotonically increasing `offsets` with `offsets[-1] != input.size(0)` (e.g. `[0, 3, 4]` with input size 5)
  * CPU: Computes mean incorrectly for the bag from 3 to 4; it uses the correct embeddings in the numerator but uses `input.size(0) - 3 = 2` instead of `offsets[-1] - 3 = 1` for the denominator
  * CUDA: Ignores the last offset and treats it as `input.size(0)` unconditionally

***

The proposed fix of enforcing `offsets[-1] == input.size(0)`:
* Will newly error for cases 2 and 3, making CPU / CUDA behave the same
* Errors for case 3 instead of performing incorrect CPU computation
* Will break code that depended on the old CUDA behavior of ignoring the last offset and treating it as `input.size(0)` unconditionally (cases 2 and 3)
* Does not address the CPU / CUDA discrepancies of case 1 - ideally, should semantics here be to insert zeros for non-monotonically increasing offsets OR to ensure monotonically increasing offsets? Need to pick one and apply it consistently

**Comment by kurtamohler** [comment]
Thanks for bringing that up @jbschlosser. I was aware of the issues with non-monotonically increasing offsets (#55549 - note that non-monotonically increasing offsets can act differently with different `mode` settings), but I did not make the connection between that and `include_last_offset`.

I suppose the question is, will any user actually want offsets to be non-monotonically increasing?

**Comment by jbschlosser** [comment]
> I suppose the question is, will any user actually want offsets to be non-monotonically increasing?

I can't think of a reason why the user would want this. It's easy enough to keep offset constant to get a 0-size bag.
