### ISSUE TITLE
[Bug] Model restoration on non cuda computer

### ISSUE THREAD

**Issue by EKami** [pytorch/pytorch#5286]
- OS: macOS 10.13.3
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.4
- CUDA/cuDNN version: NA
- GPU models and configuration: NA

Hello,
I'm trying to restore a trained model with:
```
model.load_state_dict(torch.load(file))
```

But I'm getting a:
```
Traceback (most recent call last):
  File "srgan.py", line 160, in <module>
    main()
  File "srgan.py", line 154, in main
    evaluate(args)
  File "srgan.py", line 75, in evaluate
    ModelSaverCallback.restore_model([netG], saved_model_dir.absolute())
  File "/Users/Ekami/workspace/Torchlight/examples/torchlight/nn/train_callbacks.py", line 269, in restore_model
    model.load_state_dict(torch.load(file))
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 420, in _load
    result = unpickler.load()
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 389, in persistent_load
    data_type(size), location)
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 87, in default_restore_location
    result = fn(storage, location)
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 69, in _cuda_deserialize
    return obj.cuda(device)
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/_utils.py", line 61, in _cuda
    with torch.cuda.device(device):
  File "/Users/Ekami/Programs/anaconda/envs/dl/lib/python3.6/site-packages/torch/cuda/__init__.py", line 207, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'
```
The model was trained on a cuda device but it shouldn't be an issue to restore it from a non-cuda device right? It seems to be an internal error where `_cuda_getDevice` is called but it shouldn't. The error is very easily reproductible as my code is [here](https://github.com/EKami/Torchlight/tree/showcase/memory-leak). All you have to do is to clone it with: `git clone -b showcase/memory-leak git@github.com:EKami/Torchlight.git`, cd into the `examples` folder and run the script on a non-cuda computer with `python srgan.py eval --on_cpu`. You should get the error immediately.

**Comment by elanmart** [comment]
According to [docs](http://pytorch.org/docs/master/torch.html#torch.load), I believe you should be loading your models with
```python
torch.load(file, map_location='cpu')
```

**Comment by EKami** [comment]
You're right, I didn't see it my bad. Closing this issue.

**Comment by mariosfourn** [comment]
I added map_location='cpu' and I still get the same error
