### ISSUE TITLE
PyTorch build failing on Ubuntu 20.04 with a linker error

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#52886]
## 🐛 Bug

PyTorch build is failing on some Ubuntu 20.04 machines with a Linker error.

## To Reproduce

1. Clone PyTorch repo recursively with
`git clone --recursively https://github.com/pytorch/pytorch`
2. Run build
`sudo USE_OPENMP=1 DEBUG=1 python3 setup.py develop`
3. Build fails. Number of threads had earlier been changed manually by me to 1.
```
[ 67%] Linking CXX shared library ../lib/libtorch_cpu.so
collect2: error: ld returned 1 exit status
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/build.make:19252: lib/libtorch_cpu.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:9602: caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "/users/pytorch/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/users/pytorch/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/users/pytorch/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Debug', '--', '-j', '1']' returned non-zero exit status 2.
```

## Expected behavior

Build should not fail.

## Environment

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Python version: 3.8 (64-bit runtime)
Ninja was not installed
Processor: Intel Xeon Gold 6142

## Additional context

I also encountered this issue in two other environments recently: [WSL2 with Ubuntu 20.04](https://docs.nvidia.com/cuda/wsl-user-guide/index.html), and on my laptop running Ubuntu 20.04. In the latter case, I was able to eventually build it after uninstalling `ninja`. The former is still unresolved.
However, I haven't installed ninja on the systems for which I reported this issue. Also, being out of memory isn't the issue, as these systems have 384 GB RAM.

cc @malfet @seemethere @walterddr

**Comment by imaginary-person** [comment]
Looks like the build issue is because the system ran out of storage space. I'll simply have to mount an attached disk. 
Not sure how I can fix the WSL2 issue, though, as I've ample space on Windows.
