### ISSUE TITLE
[TorchScript Usability]  More intuitive error message when passing wrong types to `torch.jit.script()`

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#52920]
## 🐛 Bug

Test case: [test-instanceclass.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-instanceclass.py)

This example passes an object of an arbitrary class to `trace.jit.script()`, but `trace.jit.script()` only accepts function objects or module objects. But the error message is not intuitive:
```
Traceback (most recent call last):
  File "test-instanceclass.py", line 14, in <module>
    m = torch.jit.script(MyClass(2, (1,2)))
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 901, in script
    qualified_name = _qualified_name(obj)
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/_jit_internal.py", line 793, in _qualified_name
    raise RuntimeError("Could not get name of python class object")
RuntimeError: Could not get name of python class object
```

A preferred error message should be something like this:
```
torch.jit.trace() expects function or module objects
```

**Comment by gmagogsfm** [comment]
I think this is related to on-going work from @SplitInfinity about adding reference semantics to objects. Assigning to @SplitInfinity

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
