### ISSUE TITLE
torch.fold failed export to onnx after traced with torch.jit.scripting

### ISSUE THREAD

**Issue by 24hours** [pytorch/pytorch#52958]
## To Reproduce

```python
import torch 
import torch.nn as nn
import torch.nn.functional as F

class SlideInference(nn.Module):
    def __init__(self):
        super().__init__()
        self.c1 = nn.Conv2d(3, 1, 3, 1, padding=1)

    def forward(self, img):
        stride = (85, 85)
        crop_size = (128, 128)

        c = img.size(1)
        h = img.size(2)
        w = img.size(3)

        pad_h = (crop_size[0] - h) % crop_size[0]
        pad_w = (crop_size[1] - w) % crop_size[1]

        img = F.pad(img, (0, pad_w, 0, pad_h))
        unfold = F.unfold(img, crop_size, stride=stride)

        win_count = unfold.size(2)

        imgs = unfold.permute([0, 2, 1])
        imgs = torch.reshape(imgs, (-1, c, *crop_size))

        preds = []
        split_imgs = torch.split(imgs, 2, 0)
        for img in split_imgs:
            preds.append(self.c1(img))

        pred = torch.cat(preds, 0)
        pred = torch.reshape(pred, (-1, win_count, crop_size[0] * crop_size[1]))
        pred = pred.permute([0, 2, 1])

        # # currently export dont support torch.fold
        # pred = torch.fold(pred, [h, w], crop_size, stride=stride)

        return pred


img = torch.ones([2, 3, 224, 224])
model = SlideInference()
# This line caused the error
model = torch.jit.script(model)

example_output = model(img)

with torch.no_grad():
    torch.onnx.export(
            model,
            img,
            './output.onnx',
            example_outputs=example_output,
            opset_version=12)
```

Traceback (most recent call last):
  File "export_test.py", line 69, in <module>
    opset_version=12)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 824, in _run_symbolic_function
    operator_export_type)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 745, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 109, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator prim_Uninitialized to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

In order to correctly generate `loop` operator in onnx, I need to run 'model = torch.jit.script(model)`, however `torch.unfold` will crash with error above.

## Expected behavior

ONNX export should work.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.6.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchvision==0.2.2.post3
[conda] efficientnet-pytorch      0.6.3                     <pip>
[conda] numpy                     1.20.0                    <pip>
[conda] numpy                     1.19.4                    <pip>
[conda] numpy                     1.20.1                    <pip>
[conda] pytorch-lightning         1.1.1                     <pip>
[conda] segmentation-models-pytorch 0.1.0                     <pip>
[conda] torch                     1.6.0+cpu                 <pip>
[conda] torchaudio                0.7.2                     <pip>
[conda] torchvision               0.8.2+cpu                 <pip>

## Additional context

I'm using this code to perform slide inference for segmentation. Currently ONNX export don't support `torch.fold` but I'm depending `loop` and `torch.unfold` to work.

**Comment by shubhambhokare1** [comment]
Can you try with latest nightly version. I tried your repro and see no issue on my side

**Comment by shubhambhokare1** [comment]
Hi @24hours ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team

**Comment by fedeloper** [comment]
same problem, cannot use jit or onnx with model with F.unfold
