### ISSUE TITLE
lr_scheduler _triangular2_scale_fn calculation is overflowed

### ISSUE THREAD

**Issue by switiz** [pytorch/pytorch#52989]
## To Reproduce

1. train use lr_schedular

`scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.00005,
                                            step_size_up=5, max_lr=0.0001,
                                            gamma=0.5, mode='triangular2', cycle_momentum=False)
`

epoch : 0, loss : 1.70, cer : 0.76, **learning_rate : [5e-05]** :  15%|████▌                          | 10239/70036 [2:09:07<12:34:05,  1.32it/s]
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    train(opt)
  File "train.py", line 43, in train
    loss, cer = train_on_epoch(train_loader, vocab, model, device, i, metric, optimizer, criterion)
  File "train.py", line 75, in train_on_epoch
    scheduler.step()
  File "C:\Users\sanma\.conda\envs\xray_pytorch\lib\site-packages\torch\optim\lr_scheduler.py", line 154, in step
    values = self.get_lr()
  File "C:\Users\sanma\.conda\envs\xray_pytorch\lib\site-packages\torch\optim\lr_scheduler.py", line 906, in get_lr
    lr = base_lr + base_height * self.scale_fn(cycle)
  File "C:\Users\sanma\.conda\envs\xray_pytorch\lib\site-packages\torch\optim\lr_scheduler.py", line 878, in _triangular2_scale_fn
    return 1 / (2. ** (x - 1))
OverflowError: (34, 'Result too large')

-> _triangular2_scale_fn return error because calculate float operation is overflowed

## Expected behavior
working normally

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): windows10 pro
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.8
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: rtx 3080
 - Any other relevant information:

**Comment by H-Huang** [comment]
Can you also include the code with which you trained with?

**Comment by switiz** [comment]
### here's my train code

      optimizer = torch.optim.Adam(params=model.parameters(), lr=1e-5, weight_decay=1e-05)
      criterion = torch.nn.CTCLoss(blank=vocab.blank_id, reduction='mean', zero_infinity=True)
      scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.00005, step_size_up=5, max_lr=0.0001, gamma=0.5, mode='triangular2', cycle_momentum=False)

      def train_on_epoch(train_loader, model, optimizer, criterion, scheduler, device, epoch, metric, pre_loss):
        model.train()
        time_stamp = 0
        total_num = 0
        progress_bar = tqdm(train_loader)
        cer = 0.0
        for data in progress_bar:
            inputs, targets, input_lengths, target_lengths = data
            inputs = inputs.to(device)
            targets = targets.to(device)
            outputs, output_lengths = model(inputs, input_lengths)
            target_lengths = torch.as_tensor(target_lengths).to(device)
            loss = criterion(outputs.transpose(0, 1), targets, output_lengths, target_lengths)
            total_num += int(input_lengths.sum())
            optimizer.zero_grad()
            epoch_loss = loss.item()
            time_stamp += 1
            if time_stamp == 10 or time_stamp % 5000 == 0 or time_stamp == len(train_loader):
                cer = metric(targets, outputs.max(-1)[1])
            loss.backward()
            optimizer.step()
            scheduler.step()
            torch.cuda.empty_cache()
            progress_bar.set_description('epoch : {}, loss : {:.2f}, cer : {:.2f}, learning_rate : {} '.format(epoch, epoch_loss, cer, scheduler.get_last_lr()))

thank you
