### ISSUE TITLE
[distributed] test_pytorch_parity failure

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#53108]
https://app.circleci.com/pipelines/github/pytorch/pytorch/279938/workflows/ee0159ec-6a2a-4d9f-b2d7-6e54de560a31/jobs/11251750

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 418, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 461, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
    fn()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 560, in test_pytorch_parity
    check_optimizer_equivalence(opt)
  File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 541, in check_optimizer_equivalence
    sharded_optimizer.consolidate_state_dict(recipient_rank=reference_rank)
TypeError: consolidate_state_dict() got an unexpected keyword argument 'recipient_rank'

```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by kshitij12345** [comment]
Another reference: 
https://app.circleci.com/pipelines/github/pytorch/pytorch/279976/workflows/9f732710-0467-4a25-9795-5f912dc434dd/jobs/11253204

**Comment by blefaudeux** [comment]
Ok, that's an argument rename from @mrshenli recently, I can fix that

**Comment by blefaudeux** [comment]
it has been fixed already

**Comment by blefaudeux** [comment]
Minor stub fix attached, but CI wise it should already be fine, Shen fixed it earlier

**Comment by blefaudeux** [comment]
fixed by now
