### ISSUE TITLE
test_gather_checks (__main__.ProcessGroupGlooTest) is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#53138]
https://app.circleci.com/pipelines/github/pytorch/pytorch/280063/workflows/8e5e4de5-b0c7-4d77-b5b8-5401bc122c12/jobs/11258099/steps

```
Mar 02 18:36:20 ======================================================================
Mar 02 18:36:20 ERROR [0.238s]: test_gather_checks (__main__.ProcessGroupGlooTest)
Mar 02 18:36:20 ----------------------------------------------------------------------
Mar 02 18:36:20 Traceback (most recent call last):
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
Mar 02 18:36:20     self._join_processes(fn)
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 418, in _join_processes
Mar 02 18:36:20     self._check_return_codes(elapsed_time)
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 461, in _check_return_codes
Mar 02 18:36:20     raise RuntimeError(error)
Mar 02 18:36:20 RuntimeError: Process 0 exited with error code 10 and exception:
Mar 02 18:36:20 Traceback (most recent call last):
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 02 18:36:20     getattr(self, test_name)()
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 02 18:36:20     fn()
Mar 02 18:36:20   File "distributed/test_c10d.py", line 1297, in test_gather_checks
Mar 02 18:36:20     pg = c10d.ProcessGroupGloo(store, self.rank, self.world_size, self.opts())
Mar 02 18:36:20 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:46295
Mar 02 18:36:20 
Mar 02 18:36:20 Process 1 exited with error code 10 and exception:
Mar 02 18:36:20 Traceback (most recent call last):
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 02 18:36:20     getattr(self, test_name)()
Mar 02 18:36:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 02 18:36:20     fn()
Mar 02 18:36:20   File "distributed/test_c10d.py", line 1297, in test_gather_checks
Mar 02 18:36:20     pg = c10d.ProcessGroupGloo(store, self.rank, self.world_size, self.opts())
Mar 02 18:36:20 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:56518
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/pull/61396 might be a fix, close to let it run in CI

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/pull/61396 might be a fix, close to let it run in CI
