### ISSUE TITLE
test_ddp_control_flow_same_across_ranks is failing due to race condition

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#53159]
## 🐛 Bug

Due to race condition of H2D async copy
https://github.com/pytorch/pytorch/blob/a3cd881890c6e73781c20823750aa8de5d738e05/torch/lib/c10d/reducer.cpp#L678
with host write https://github.com/pytorch/pytorch/blob/a3cd881890c6e73781c20823750aa8de5d738e05/torch/lib/c10d/reducer.cpp#L1290

the `local_used_maps_dev_` is not computed correctly when the device goes far behind the host.

this causes `test_ddp_control_flow_same_across_ranks` to fail if we run this test when GPU util is ~100%

```
======================================================================
ERROR: test_ddp_control_flow_same_across_ranks (__main__.TestDistBackendWithFork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
    self._join_processes(fn)
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 418, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 461, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
    getattr(self, test_name)()
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
    fn()
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 158, in wrapper
    return func(*args, **kwargs)
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 4663, in test_ddp_control_flow_same_across_ranks
    self.assertEqual(variable_usage_tensor, expected)
  File "/home/gaoxiang/.local/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1189, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
  File "/usr/lib/python3.9/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Tensors failed to compare as equal!Found 2 different element(s) (out of 2), with the greatest difference of 2 (0 vs. 2) occuring at index 0.
----------------------------------------------------------------------
```

## To Reproduce

Find any script to run at background to stress the GPU util to 100%, for example
```python
import torch
import torch.nn as nn
x = torch.randn(1024, 1024).cuda()
for _ in range(100000):
    y = torch.matmul(x, x)
print('workload test done')
```

Then run the test
```
python test/run_test.py --verbose -i distributed/test_distributed_spawn -- -k test_ddp_control_flow_same_across_ranks
```

## Expected behavior

test pass

## Additional context

We have identified the issue, and a PR is coming soon.

cc: @mcarilli @ptrblck 

cc @ngimel @aocsa @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by zasdfgbnm** [comment]
@malfet Should this be 1.8.1 milestone?
