### ISSUE TITLE
RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/ir.cpp":513, please report a bug to PyTorch. 3005 not in scope

### ISSUE THREAD

**Issue by JulesBelveze** [pytorch/pytorch#53189]
## 🐛 Bug
Hi there,
I am trying trying to export a PyTorch module to ONNX following the docs [here](https://pytorch.org/docs/stable/onnx.html). 
As I am calling an external function from my `torch.nn.Module` I am trying to utilize _script-based export_. However, I face the following issue:
```
Traceback (most recent call last):
  File "pytorch2onnx.py", line 57, in <module>
    pytorch2onnx()
  File "pytorch2onnx.py", line 51, in pytorch2onnx
    "score": {0: "batch_size"}
  File "/home/julesbelveze/ner/.venv/ner/lib/python3.6/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/julesbelveze/ner/.venv/ner/lib/python3.6/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/julesbelveze/ner/.venv/ner/lib/python3.6/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/julesbelveze/ner/.venv/ner/lib/python3.6/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/julesbelveze/ner/.venv/ner/lib/python3.6/site-packages/torch/onnx/utils.py", line 171, in _optimize_graph
    torch._C._jit_pass_lint(graph)
RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/ir.cpp":513, please report a bug to PyTorch. 3005 not in scope
```
## To Reproduce

I am trying to export the custom `torch.nn.Module` as follow:
```
model_input = (batch["input_ids"].to("cpu"), batch["attention_mask"].to("cpu"), batch["label_ids"].to("cpu"), 
                           batch["valid_mask"].to("cpu"))

torch.onnx.export(model, model_input, "labse.onnx", export_params=True, opset_version=12,
                  do_constant_folding=True, verbose=True,
                  input_names=["input_ids", "attention_mask", "labels", "valid_mask"],
                  output_names=["loss", "score"],
                  dynamic_axes={
                      "input_ids": {0: "batch_size"},
                      "attention_mask": {0: "batch_size"},
                      "labels": {0: "batch_size"},
                      "valid_mask": {0: "batch_size"},
                      "score": {0: "batch_size"}
                  })
```
where each element of `model_input` is a tensor of shape `(16,512)`.

The instanciated model is the following:
```
class LabseForTokenClassification(torch.nn.Module):
    def __init__(self, config):
        super(LabseForTokenClassification, self).__init__()
        self.config = config
        self.num_labels = config.num_labels

        self.labse = AutoModel.from_pretrained(config.model_name, add_pooling_layer=False)
        ....

    def forward(self, input_ids=None, attention_mask=None, labels=None, valid_mask=None):
        """"""
        outputs = self.labse(
            input_ids=input_ids,
            attention_mask=attention_mask
        )
        sequence_output = outputs[0]
        sequence_output, attention_mask = valid_sequence_output(sequence_output, valid_mask, attention_mask)
       ....
```
and the `valid_sequence_output` function is defined as a script as follow:
```
@torch.jit.script
def valid_sequence_output(sequence_output, valid_mask, attention_mask):
    batch_size, max_len, feat_dim = sequence_output.shape
    valid_output = torch.zeros(batch_size, max_len, feat_dim, dtype=torch.float32,
                               device='cuda' if torch.cuda.is_available() else 'cpu')
    valid_attention_mask = torch.zeros(batch_size, max_len, dtype=torch.long,
                                       device='cuda' if torch.cuda.is_available() else 'cpu')
    for i in range(batch_size):
        jj = -1
        for j in range(max_len):
            if valid_mask[i][j].item() == 1:
                jj += 1
                valid_output[i][jj] = sequence_output[i][j]
                valid_attention_mask[i][jj] = attention_mask[i][j]
    return valid_output, valid_attention_mask
```

I have also tried to export the model to ONNX without registering the `valid_sequence_output` as as script but then I get a bunch of warnings and the output ONNX graph is corrupted.
```
/home/julesbelveze/ner/models/labse.py:112: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i in range(batch_size):
/home/julesbelveze/ner/models/labse.py:114: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for j in range(max_len):
/home/julesbelveze/ner/models/labse.py:115: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if valid_mask[i][j].item() == 1:
```

## Expected behavior
Be able to export the pytorch model to ONNX

## Environment
- OS Ubuntu 18.04
- `torch==1.7.1+cu110`
- `onnx==1.8.1`
- `onnxruntime==1.7.0`
- `transformers==4.3.2`

Thanks for your help guys :D

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

**Comment by garymm** [comment]
Hi @JulesBelveze can you reproduce this issue with the latest PyTorch nightly?
If so, can you please provide some code that we can copy-paste to reproduce the issue?
Maybe some code that just calls `valid_sequence_output` with appropriate inputs to trigger the failure?

Also I guess you may be able to avoid `torch.jit.script` if you can express `valid_sequence_output` without for-loops.
I think you should be able to use tensor indexing rather than for loops. E.g.,
```python
valid_mask = torch.tensor([[0, 1, 0], [1, 0, 0]], dtype=torch.bool)
print("valid_mask:\n", valid_mask)
sequence_output = torch.randn((2, 3))
valid_output = torch.zeros_like(sequence_output)
valid_output[valid_mask] = sequence_output[valid_mask]
print("valid_output:\n", valid_output)
```
Produces:
```
valid_mask:
 tensor([[False,  True, False],
        [ True, False, False]])
valid_output:
 tensor([[ 0.0000, -1.9027,  0.0000],
        [ 0.3091,  0.0000,  0.0000]])
```

**Comment by JulesBelveze** [comment]
Hey @garymm, thanks for your help! 
As you mentioned I actually managed to express `valid_sequence_output` only with tensor operations and everything went smoothly 😃
