### ISSUE TITLE
test_broadcast_checks (__main__.ProcessGroupGlooTest) is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#53270]
Not disabling yet, as this is rare so far.

https://app.circleci.com/pipelines/github/pytorch/pytorch/280728/workflows/1076107b-50d4-4043-aac0-4d92602920b4/jobs/11296301/steps

```
Mar 04 01:22:35   test_broadcast_checks (__main__.ProcessGroupGlooTest) ... ERROR:root:Caught exception: 
Mar 04 01:22:35 Traceback (most recent call last):
Mar 04 01:22:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 04 01:22:35     getattr(self, test_name)()
Mar 04 01:22:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 04 01:22:35     fn()
Mar 04 01:22:35   File "distributed/test_c10d.py", line 772, in test_broadcast_checks
Mar 04 01:22:35     pg = c10d.ProcessGroupGloo(store, self.rank, self.world_size, self.opts())
Mar 04 01:22:35 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:5352
Mar 04 01:22:35 exiting process with exit code: 10
Mar 04 01:22:35 ERROR (0.151s)
```

```
Mar 04 01:23:01 ======================================================================
Mar 04 01:23:01 ERROR [0.151s]: test_broadcast_checks (__main__.ProcessGroupGlooTest)
Mar 04 01:23:01 ----------------------------------------------------------------------
Mar 04 01:23:01 Traceback (most recent call last):
Mar 04 01:23:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
Mar 04 01:23:01     self._join_processes(fn)
Mar 04 01:23:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 418, in _join_processes
Mar 04 01:23:01     self._check_return_codes(elapsed_time)
Mar 04 01:23:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 461, in _check_return_codes
Mar 04 01:23:01     raise RuntimeError(error)
Mar 04 01:23:01 RuntimeError: Process 3 exited with error code 10 and exception:
Mar 04 01:23:01 Traceback (most recent call last):
Mar 04 01:23:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 04 01:23:01     getattr(self, test_name)()
Mar 04 01:23:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 04 01:23:01     fn()
Mar 04 01:23:01   File "distributed/test_c10d.py", line 772, in test_broadcast_checks
Mar 04 01:23:01     pg = c10d.ProcessGroupGloo(store, self.rank, self.world_size, self.opts())
Mar 04 01:23:01 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:5352
Mar 04 01:23:01 
Mar 04 01:23:01 
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by zhaojuanmao** [comment]
https://github.com/pytorch/pytorch/pull/51929 may be related and it was reverted for investigation
