### ISSUE TITLE
[mypy] AssertionError: Cannot find component 'DDPUnevenTestInput@4052' for 'torch.testing._internal.distributed.distributed_test.DistributedTest._DistTestBase.DDPUnevenTestInput@4052'

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53272]
PyTorch seems to be tickling some sort of mypy invalid cache bug. I don't have a minimal reproducer so I haven't reported this upstream

Steps to reproduce:
1. Check out 7cec4b3d4a11731dcd08e5e4077149de82643eae and run mypy (no type errors)
2. Apply this patch:

```
diff --git a/torch/nn/qat/modules/linear.py b/torch/nn/qat/modules/linear.py
index 26849e42d4..3f84859c8b 100644
--- a/torch/nn/qat/modules/linear.py
+++ b/torch/nn/qat/modules/linear.py
@@ -20,7 +20,7 @@ class Linear(nn.Linear):
     _FLOAT_MODULE = nn.Linear
 
     def __init__(self, in_features, out_features, bias=True,
-                 qconfig=None):
+                 qconfig=None, **kwargs):
         super().__init__(in_features, out_features, bias)
         assert qconfig, 'qconfig must be provided for QAT module'
         self.qconfig = qconfig
```

3. Run mypy again

This triggers a mypy internal assert error:

```
mypy
Traceback (most recent call last):
  File "/home/ezyang/local/pytorch-tmp-env/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.6/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 89, in main
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 249, in _build
  File "mypy/build.py", line 2649, in dispatch
  File "mypy/build.py", line 2949, in process_graph
  File "mypy/build.py", line 3027, in process_fresh_modules
  File "mypy/build.py", line 1954, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 76, in visit_symbol_table
  File "mypy/fixup.py", line 299, in lookup_qualified_stnode
  File "mypy/lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component 'DDPUnevenTestInput@4052' for 'torch.testing._internal.distributed.distributed_test.DistributedTest._DistTestBase.DDPUnevenTestInput@4052'
```

This assert failure is sticky; even if you revert the diff, it will still fail. `rm -rf .mypy_cache` fixes the problem.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by ezyang** [comment]
Might be this upstream bug https://github.com/python/mypy/issues/7281
