### ISSUE TITLE
CUDA error when used torch.mm() with gpu in pytorch1.8.0

### ISSUE THREAD

**Issue by maqy1995** [pytorch/pytorch#53336]
## 🐛 Bug

when used torch.mm(mat1, mat2) in pytorch 1.8.0, mat1 and mat2 both in gpu, there is a Runtime Error.
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling 'cublasCreate(handle)'

## To Reproduce
```
import torch
mat1 = torch.randn(2,3).to(0)
mat2 = torch.randn(3,3).to(0)

torch.mm(mat1, mat2)
```
## Environment

 - PyTorch Version : 1.8.0
 - OS (e.g., Linux): Centos7
 - How you installed PyTorch (`conda`, `pip`, source): pip install
 - Python version: 3.7.6
 - CUDA/cuDNN version: cuda 10.2

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @aocsa @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by malfet** [comment]
Please run `python3 -m torch.utils.collect_env` and post its results here

**Comment by maqy1995** [comment]
the results after run `python3 -m torch.utils.collect_env`:
```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.8.2003 (Core) (x86_64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 2.8.12.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4
GPU 5: Tesla T4

Nvidia driver version: 440.64.00
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] pytorch-lightning==1.0.0
[pip] torch==1.8.0
[pip] torch-cluster==1.5.4
[pip] torch-geometric==1.5.0
[pip] torch-scatter==2.0.4
[pip] torch-sparse==0.6.4
[pip] torch-spline-conv==1.2.0
[pip] torchvision==0.8.2
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] pytorch-lightning         1.0.0                    pypi_0    pypi
[conda] torch                     1.8.0                    pypi_0    pypi
[conda] torch-cluster             1.5.4                    pypi_0    pypi
[conda] torch-geometric           1.5.0                    pypi_0    pypi
[conda] torch-scatter             2.0.4                    pypi_0    pypi
[conda] torch-sparse              0.6.4                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchvision               0.8.2                    pypi_0    pypi

```

**Comment by maqy1995** [comment]
In addition, when I use pytorch1.7.1 there is no such problem.

**Comment by ptrblck** [comment]
I cannot reproduce this issue on a T4 with the `1.8.0+CUDA10.2` binaries:
```python
import torch

print(torch.__version__)
print(torch.cuda.get_device_name(0))
print(torch.version.cuda)

mat1 = torch.randn(2,3).to(0)
mat2 = torch.randn(3,3).to(0)

y = torch.mm(mat1, mat2)
print(y)
```
Output:
```python
1.8.0
Tesla T4
10.2
tensor([[-1.8373, -0.3539,  0.6408],
        [ 2.5686,  0.5632, -1.2593]], device='cuda:0')
```

**Comment by maqy1995** [comment]
It may be that there is some problem with my pip source. This weekend I will try to install PyTorch1.8 on my PC to see if the problem still exists.

**Comment by maqy1995** [comment]
I met the same issue on my PC:
```
(base) maqy@ubuntu:~$ pip install torch
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting torch
  Downloading https://mirrors.aliyun.com/pypi/packages/94/99/5861239a6e1ffe66e120f114a4d67e96e5c4b17c1a785dfc6ca6769585fc/torch-1.8.0-cp37-cp37m-manylinux1_x86_64.whl (735.5MB)
     |████████████████████████████████| 735.5MB 9.2MB/s 
Requirement already satisfied: numpy in ./miniconda3/lib/python3.7/site-packages (from torch) (1.19.1)
Collecting typing-extensions
  Downloading https://mirrors.aliyun.com/pypi/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.8.0 typing-extensions-3.7.4.3
(base) maqy@ubuntu:~$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.8.0
>>> print(torch.cuda.get_device_name(0))
GeForce RTX 2060 SUPER
>>> print(torch.version.cuda)
10.2
>>> mat1 = torch.randn(2,3).to(0)
>>> mat2 = torch.randn(3,3).to(0)
>>> y = torch.mm(mat1, mat2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
>>> quit()
```
and the environment is below:
```
(base) maqy@ubuntu:~$ pip install torch
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting torch
  Downloading https://mirrors.aliyun.com/pypi/packages/94/99/5861239a6e1ffe66e120f114a4d67e96e5c4b17c1a785dfc6ca6769585fc/torch-1.8.0-cp37-cp37m-manylinux1_x86_64.whl (735.5MB)
     |████████████████████████████████| 735.5MB 9.2MB/s 
Requirement already satisfied: numpy in ./miniconda3/lib/python3.7/site-packages (from torch) (1.19.1)
Collecting typing-extensions
  Downloading https://mirrors.aliyun.com/pypi/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.8.0 typing-extensions-3.7.4.3
(base) maqy@ubuntu:~$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.8.0
>>> print(torch.cuda.get_device_name(0))
GeForce RTX 2060 SUPER
>>> print(torch.version.cuda)
10.2
>>> mat1 = torch.randn(2,3).to(0)
>>> mat2 = torch.randn(3,3).to(0)
>>> y = torch.mm(mat1, mat2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
>>> quit()
```

**Comment by wangg12** [comment]
I got the same error with 1.8 yesterday. Now I have to stick with 1.7.

**Comment by malfet** [comment]
I can reproduce the problem using torch-1.8 on RTX 2080 (sm_75)
torch-1.8 (unlike 1.7) is shipped without sm_75 cubins due to the size considerations:
```
Analyzing /home/nshulga/.local/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so
.nv_fatbin size 705.5MiB
  sm_37: 72.5MiB
  sm_50: 171.1MiB
  sm_60: 179.7MiB
  sm_70: 193.0MiB
  sm_35: 39.0MiB
  sm_61: 50.2MiB
__nv_relfatbin size 35.4MiB
  sm_35: 5.3MiB
  sm_50: 7.4MiB
  sm_60: 7.8MiB
  sm_70: 14.9MiB
  sm_37: 54.5KiB
```

**Comment by wangg12** [comment]
@malfet Any solution?

**Comment by malfet** [comment]
Apparently pruning arches kills cublasLt:
```
$ nvprune /usr/local/cuda/lib64/libcublasLt_static.a  -o libcublasLt_pruned_static.a; echo 'int main(void) { void * handle; printf("%d\n",cublasCreate_v2(&handle)); }'|gcc -x c - -L. -lcublas_static -lcublasLt_pruned_static -lcublas_static -lculibos -lcudart_static -lpthread -ldl -lrt -lstdc++; ./a.out 
3
```
And leaving only sm_70 reproduces internal error:
```
nvprune /usr/local/cuda/lib64/libcublasLt_static.a -arch sm_70 -o libcublasLt_pruned_static.a; echo 'int main(void) { void * handle; printf("%d\n",cublasCreate_v2(&handle)); }'|gcc -x c - -L. -lcublas_static -lcublasLt_pruned_static -lcublas_static -lculibos -lcudart_static -lpthread -ldl -lrt -lstdc++; ./a.out 
14
```
CC: @ptrblck

**Comment by malfet** [comment]
@wangg12 Are using CUDA-11.1 absolutely out of the question for you? If not consider downloading torch-1.8.0 with CUDA-11.1 support from  https://download.pytorch.org/whl/torch_stable.html

**Comment by ptrblck** [comment]
Checking with cublas team on it.

**Comment by wangg12** [comment]
@malfet I tried both 11.1 and 10.2, both failed.

**Comment by gevezex** [comment]
Same problem here. Here is my output:
`
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.8.0                    pypi_0    pypi
`

**Comment by seemethere** [comment]
Creating some test builds in https://github.com/pytorch/pytorch/pull/53533 to see if changes in pytorch/builder#676 actually resolve this issue

**Comment by pfeatherstone** [comment]
Using a nightly build of pytorch resolved this for me.

**Comment by maqy1995** [comment]
Torch 1.8.1 fixes this problem, so close this issue.

**Comment by Sunzz1996** [comment]
**问题描述：**在使用 pytorch 1.8.0 版本的时候出现的CUDNN_STATUS_NOT_INITIALIZED的情况，但是

`torch.cuda.is_available() = True`
**已有解决方案：**有人提出将 pytorch 1.8.0 退回到 1.7.0，可以解决问题。 但是对于必须要使用 pytorch 1.8+版本的用户来说就很不友好。

**新的解决方案：**

_原因分析：是 pytorch 1.8.0 版本与 CUDA 10.2 不兼容导致的_

_步骤：只需升级pytorch 至 1.8.1 即可_

`pip install torch==1.8.1 --upgrade`
**tips:**

- CUDA 版本一定要是 10.2
- NVIDIA driver 版本一定要是 440+， 本文使用的是470， 2080Ti GPU
- 无需额外配置对应的cuDNN
