### ISSUE TITLE
Default pytest is truncating stacktrace (somehow!!!)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53386]
Steps to reproduce:

1. Check out 5ebfabb310d6b3c8b32d28314b3e4612d21f5d85
2. Apply this patch (this doesn't really matter, just need to trigger an error in test setup code)

```
diff --git a/torch/testing/_internal/common_device_type.py b/torch/testing/_internal/common_device_type.py
index 40062d3cb1..692e227850 100644
--- a/torch/testing/_internal/common_device_type.py
+++ b/torch/testing/_internal/common_device_type.py
@@ -346,6 +346,12 @@ class CPUTestBase(DeviceTypeTestBase):
     def _should_stop_test_suite(self):
         return False
 
+class MetaTestBase(DeviceTypeTestBase):
+    device_type = 'meta'
+
+    def _should_stop_test_suite(self):
+        return False
+
 class CUDATestBase(DeviceTypeTestBase):
     device_type = 'cuda'
     _do_cuda_memory_leak_check = True
@@ -399,8 +405,10 @@ def get_device_type_test_bases():
                 test_bases.append(CUDATestBase)
         else:
             test_bases.append(CPUTestBase)
+            test_bases.append(MetaTestBase)
     else:
         test_bases.append(CPUTestBase)
+        test_bases.append(MetaTestBase)
         if torch.cuda.is_available():
             test_bases.append(CUDATestBase)

```
3. Run `pytest --tb=native test/test_torch.py`

Expected result: I expect a full backtrace as I would get when I do `python test/test_torch.py`

```
======================================================================
ERROR: test_advancedindex_mixed_cpu_devices_meta (__main__.TestDevicePrecisionMETA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 710, in multi_fn
    return fn(slf, devices, *args, **kwargs)
  File "test/test_torch.py", line 6556, in test_advancedindex_mixed_cpu_devices
    ia = torch.tensor([0, 2, 1]).to(device)
NotImplementedError: Could not run 'aten::empty_strided' with arguments from the 'Meta' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
```

Actual result: pytest truncates(!!!!) the backtrace, removing important context.

```
_______________________________________________ TestTensorDeviceOpsMETA.test___rshift___meta_float64 _______________________________________________
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/test_torch.py", line 7092, in fn
    device_tensor = cpu_tensor.to(dtype=dtype, device=device)
NotImplementedError: Could not run 'aten::empty_strided' with arguments from the 'Meta' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
```

pytest why do you slay me like this!!!

**Comment by ezyang** [comment]
I'm not even sure this is even a fair comparison pytest is failing somewhere way different than regular unittest

**Comment by guilhermeleobas** [comment]
There's an option in pytest (`--full-trace`) that shows the entire traceback rather than cutting it.
