### ISSUE TITLE
[bug][JIT] tracing with partial hooks

### ISSUE THREAD

**Issue by antoinebrl** [pytorch/pytorch#53421]
## 🐛 Bug

:wave: Hello! Well done on releasing v1.8.0 with so many new great features.

I might have found a bug which was not in previous versions (tested against 1.7.0 and 1.7.1). It's related to the use of `torch.jit.script` after registering a forward hook prepared with `functools.partial`.

## To Reproduce

This is a minimal reproducible example:

```
import torch
import torchvision
from functools import partial

def hook(module, input, output, foo):
    print(foo)

model = torchvision.models.resnet18()
hook_fn = partial(hook, foo="bar")
model.layer4.register_forward_hook(hook_fn)

torch.jit.script(model)
model(torch.rand(7, 3, 224, 224))
```

v1.8.0 output:
```
Traceback (most recent call last):
  File "test_jit.py", line 12, in <module>
    torch.jit.script(model)
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_script.py", line 943, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 391, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 448, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_script.py", line 391, in _construct
    init_fn(script_module)
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 428, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 405, in create_script_module_impl
    hook_stubs, pre_hook_stubs = get_hook_stubs(nn_module)
  File "/home/antoine/Projects/torchextractor/.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 664, in get_hook_stubs
    if hook.__name__ in hook_map:
AttributeError: 'functools.partial' object has no attribute '__name__'
```

## Expected behavior

For the example above we should expect no error and `bar` on stdout.

## Environment

```
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 960M
Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.0, 1.7.1 when it's working. 1.8.0 when it fails
[pip3] torchvision==0.8.1 or 0.8.2 when it's working. 0.9.0 when it fails
[conda] Could not collect
```

**Comment by gmagogsfm** [comment]
Hi antoinebrl,

Thanks for reporting this issue, passing partial functions as hooks isn't a supported use case in JIT yet. A workaround is to create a temporary function, note that you'd need to make a few additional changes to make this work:

- First argument of hook function must be named "self", which is a special keyword recognized by JIT to be flexibly representative of any type 
- Type annotations must be added to `input`/`output`/`foo`
- `self` argument of `hook` must be annotated with `Any` type

```
def hook(self: Any, input : Tuple[torch.Tensor], output, foo: str):
    print(foo)

def hook_fn(self, input: Tuple[torch.Tensor], output):
    return hook(self, input, output, foo="bar")
model.register_forward_hook(hook_fn)
```

We will look into all the issues discovered in this bug.

**Comment by antoinebrl** [comment]
gmagogsfm - thanks for coming back to me on this bug issue. I will try your alternative.

> passing partial functions as hooks isn't a supported use case in JIT yet.

What do you mean? I have not tested the serialization but the code snippet above works as expected when using previous versions of pytorch. That looks like a regression from a user perspective.

Given the error, I thought lambda functions as hooks would yield the same error. I learned that lambda functions are all named `<lambda>`. if several lambda hooks are registered, could that cause a collision in the  `hook_map` ?

The code I used to test lambda functions as hooks runs as expected with 1.7.1 but raises another error when 1.8.0 is used. I am not sure if it's related to the previous exception or not.
```
import torch
import torchvision

model = torchvision.models.resnet18()
model.layer4.register_forward_hook(lambda m, i, o: print("hello"))

torch.jit.script(model)
model(torch.rand(7, 3, 224, 224))
```
```
Traceback (most recent call last):
  File "test_jit.py", line 8, in <module>
    torch.jit.script(model)
  File ".../.env/lib/python3.6/site-packages/torch/jit/_script.py", line 943, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 391, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 448, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File ".../.env/lib/python3.6/site-packages/torch/jit/_script.py", line 391, in _construct
    init_fn(script_module)
  File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 428, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 405, in create_script_module_impl
    hook_stubs, pre_hook_stubs = get_hook_stubs(nn_module)
  File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 673, in get_hook_stubs
    hook_stubs.append(make_stub(hook, hook.__name__))
  File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 37, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File ".../.env/lib/python3.6/site-packages/torch/jit/frontend.py", line 241, in get_jit_def
    sourcelines = normalize_source_lines(sourcelines)
  File ".../.env/lib/python3.6/site-packages/torch/jit/frontend.py", line 211, in normalize_source_lines
    fn_def = sourcelines[idx]
UnboundLocalError: local variable 'idx' referenced before assignment
```

**Comment by gmagogsfm** [comment]
> gmagogsfm - thanks for coming back to me on this bug issue. I will try your alternative.
> 
> > passing partial functions as hooks isn't a supported use case in JIT yet.
> 
> What do you mean? I have not tested the serialization but the code snippet above works as expected when using previous versions of pytorch. That looks like a regression from a user perspective.

AFAIK, compiling hooks that are attached to module is supported starting from 1.8. Previously the hooks are just silently dropped. 
See [1.8 release notes](https://github.com/pytorch/pytorch/releases), search for "module level hooks in JIT".

> Given the error, I thought lambda functions as hooks would yield the same error. I learned that lambda functions are all named `<lambda>`. if several lambda hooks are registered, could that cause a collision in the `hook_map` ?

Sorry for not being clear, I wasn't proposing using lambdas. `hook_fn` in the workaround I proposed is a top-level global free function.

> 
> The code I used to test lambda functions as hooks runs as expected with 1.7.1 but raises another error when 1.8.0 is used. I am not sure if it's related to the previous exception or not as they both come from `get_hook_stubs`.
> 
> ```
> import torch
> import torchvision
> 
> model = torchvision.models.resnet18()
> model.layer4.register_forward_hook(lambda m, i, o: print("hello"))
> 
> torch.jit.script(model)
> model(torch.rand(7, 3, 224, 224))
> ```
> 
> ```
> Traceback (most recent call last):
>   File "test_jit.py", line 8, in <module>
>     torch.jit.script(model)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_script.py", line 943, in script
>     obj, torch.jit._recursive.infer_methods_to_compile
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 391, in create_script_module
>     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 448, in create_script_module_impl
>     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_script.py", line 391, in _construct
>     init_fn(script_module)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 428, in init_fn
>     scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 405, in create_script_module_impl
>     hook_stubs, pre_hook_stubs = get_hook_stubs(nn_module)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 673, in get_hook_stubs
>     hook_stubs.append(make_stub(hook, hook.__name__))
>   File ".../.env/lib/python3.6/site-packages/torch/jit/_recursive.py", line 37, in make_stub
>     ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
>   File ".../.env/lib/python3.6/site-packages/torch/jit/frontend.py", line 241, in get_jit_def
>     sourcelines = normalize_source_lines(sourcelines)
>   File ".../.env/lib/python3.6/site-packages/torch/jit/frontend.py", line 211, in normalize_source_lines
>     fn_def = sourcelines[idx]
> UnboundLocalError: local variable 'idx' referenced before assignment
> ```

**Comment by gmagogsfm** [comment]
> > AFAIK, compiling hooks that are attached to module is supported starting from 1.8. Previously the hooks are just silently dropped. See 1.8 release notes, search for "module level hooks in JIT".
> 
> Thanks for pointing this out! The tests in my project were working due to weird side effects. That lets me to wrongfully conclude JIT was supporting hooks in previous version.
> 
> > Sorry for not being clear, I wasn't proposing using lambdas.
> 
> I'm the one being sorry for introducing some confusion here. As the original stack-trace fails with `'functools.partial' object has no attribute '__name__'` I thought maybe lambda functions would produce the same error. It turns out lambda functions also raise an error but a different one. Do you want me to open another issue?
> 
> On your proposed solution I tried to provide a non constant argument but I didn't work. Do you know any work around?
> 
> ```
> def hook(self: Any, input : Tuple[torch.Tensor], output, foo: str):
>     print(foo)
> 
> def hook_fn(foo):
>     def wrapper(self, input: Tuple[torch.Tensor], output):
>         return hook(self, input, output, foo)
>     return wrapper
> 
> model = torchvision.models.resnet18()
> model.layer3.register_forward_hook(hook_fn("bar"))
> model.layer4.register_forward_hook(hook_fn("foo"))
> 
> model_traced = torch.jit.script(model)
> 
> 
> RuntimeError: 
> python value of type 'str' cannot be used as a value. Perhaps it is a closed over global variable? If so, please consider passing it in as an argument or use a local variable instead.:
>   File "<ipython-input-21-909c11a5ad4e>", line 6
>     def wrapper(self, input: Tuple[torch.Tensor], output):
>         return hook(self, input, output, foo)
>                                          ~~~ <--- HERE
> ```

Unfortunately I don't know of any workaround in this case, the function needs to be statically defined without closing over values outside of its scope.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
