### ISSUE TITLE
Cuda related autograd tests fail with Jacobian mismatch for output 0 with respect to input 0

### ISSUE THREAD

**Issue by realiti4** [pytorch/pytorch#53446]
Hi,

Couple of cuda releated tests failed, when I wanted check my fresh Pytorch 1.8.0 build and run run_test.py. These are what I used to build and errors that I am getting

```
set CONFIG=release

set CMAKE_GENERATOR=Ninja

set TH_BINARY_BUILD=1
set USE_DISTRIBUTED=0
set INSTALL_TEST=0
set DISTUTILS_USE_SDK=1

set CUDA_PREFIX=cuda111
set MAGMA_VERSION=2.5.4

set TMP_DIR_WIN=F:\virtualenvs\builds\library\

:check_magma
if not exist %TMP_DIR_WIN%\magma\ (
	curl -k https://s3.amazonaws.com/ossci-windows/magma_%MAGMA_VERSION%_%CUDA_PREFIX%_%CONFIG%.7z -o %TMP_DIR_WIN%\magma.7z
	7za x -aoa %TMP_DIR_WIN%\magma.7z -o%TMP_DIR_WIN%\magma
	del %TMP_DIR_WIN%\magma.7z
)

set MAGMA_HOME=%TMP_DIR_WIN%\magma
set libuv_ROOT=C:\packages\libuv-1.40.0

"D:\Files\Program\IntelSWTools\compilers_and_libraries_2020.4.311\windows\bin\compilervars.bat" intel64 vs2019

python setup.py bdist_wheel
```

```
ERROR: test_lu_square_batch_no_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 295, in instantiated_test
    raise rte
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 5176, in do_test
    check(name)
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 4947, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION,
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_utils.py", line 1911, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.1295,  0.2564],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3685, -0.8116],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.3453]],
       device='cuda:0')
analytical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.1295,  0.2564],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3685, -0.8116],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.3453]],
       device='cuda:0')


======================================================================
ERROR: test_lu_square_many_batches_no_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 295, in instantiated_test
    raise rte
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 5176, in do_test
    check(name)
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 4959, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradgradcheck(apply_method, input_variables,
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_utils.py", line 1925, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 674, in gradgradcheck
    return gradcheck(
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 3.6142e+00,  7.0091e+00,  5.3443e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 7.0091e+00,  1.1945e+01,  9.4077e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 5.3443e+00,  9.4077e+00,  7.4169e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.4775e+00,
          1.3568e+00, -9.9772e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.3568e+00,
          1.2459e+00, -9.1998e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.9772e-02,
         -9.1998e-02, -1.1102e-10]], device='cuda:0')
analytical:tensor([[ 3.6142,  7.0091,  5.3443,  ...,  0.0000,  0.0000,  0.0000],
        [ 7.0091, 11.9455,  9.4077,  ...,  0.0000,  0.0000,  0.0000],
        [ 5.3443,  9.4077,  7.4169,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  1.4775,  1.3568, -0.0998],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.3568,  1.2459, -0.0920],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.0998, -0.0920,  0.0000]],
       device='cuda:0')


======================================================================
ERROR: test_lu_square_many_batches_with_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 295, in instantiated_test
    raise rte
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 5176, in do_test
    check(name)
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "F:\virtualenvs\git-repos\pytorch\test\test_autograd.py", line 4959, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradgradcheck(apply_method, input_variables,
  File "F:\virtualenvs\env\lib\site-packages\torch\testing\_internal\common_utils.py", line 1925, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 674, in gradgradcheck
    return gradcheck(
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "F:\virtualenvs\env\lib\site-packages\torch\autograd\gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 3.6142e+00,  7.0091e+00,  5.3443e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 7.0091e+00,  1.1945e+01,  9.4077e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 5.3443e+00,  9.4077e+00,  7.4169e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.4775e+00,
          1.3568e+00, -9.9772e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.3568e+00,
          1.2459e+00, -9.1998e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.9772e-02,
         -9.1998e-02, -1.1102e-10]], device='cuda:0')
analytical:tensor([[ 3.6142,  7.0091,  5.3443,  ...,  0.0000,  0.0000,  0.0000],
        [ 7.0091, 11.9455,  9.4077,  ...,  0.0000,  0.0000,  0.0000],
        [ 5.3443,  9.4077,  7.4169,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  1.4775,  1.3568, -0.0998],
        [ 0.0000,  0.0000,  0.0000,  ...,  1.3568,  1.2459, -0.0920],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.0998, -0.0920,  0.0000]],
       device='cuda:0')
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows 2004
 - How you installed PyTorch (`conda`, `pip`, source): source build in virtualenv
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1 / 8.0.4
 - GPU models and configuration: rtx 2060
 - Any other relevant information: MSVC 19.28, cmake 3.19.6

**Comment by albanD** [comment]
Thanks for the report!
@ngimel  to do you know if there are known precision issues with CUDA libs on windows wrt to linear algebra methods (lu in particular here) ?

**Comment by gchanan** [comment]
do we test these on windows?

**Comment by albanD** [comment]
We don't test this exact set of arguments, but we do test python 3.6, cuda 11.1 with vs2019.

And these test run there and are passing on master: `test_lu_square_many_batches_with_info_cuda (__main__.TestAutogradDeviceTypeCUDA) ... ok (5.933s)` from https://app.circleci.com/pipelines/github/pytorch/pytorch/282163/workflows/7c7526c2-1323-42c5-86cb-823e17bb5d19/jobs/11367326

**Comment by ngimel** [comment]
I don't, maybe @xwang233 does.

**Comment by xwang233** [comment]
There was a similar test_autograd Jacobian failure in cuda **11.2**, but it's for `masked_scatter`, and due to `thrust::exclusive_scan` change https://github.com/pytorch/pytorch/issues/51544. So this might be irrelevant.

Currently `lu` on CUDA only uses MAGMA backend. I'm not sure what happened for this test. Perhaps MAGMA version is different in the release vs CI build?

**Comment by mruberry** [comment]
Notably we don't run these tests with an RTX 2060, however. They might be less precise on that card.

**Comment by realiti4** [comment]
> Notably we don't run these tests with an RTX 2060, however. They might be less precise on that card.

But these tests past on linux on same hardware.

**Comment by xwang233** [comment]
It seems like `lu` backward uses `triangular_solve` internally, which also uses MAGMA as its backend right now.

https://github.com/pytorch/pytorch/blob/c31ced42469cd5f0b4e758f5484be40a9515bc38/torch/_autograd_functions.py#L71-L72

For this failure on windows, I suspect it's MAGMA version issue or something else.

Fortunately, we have a cublas `triangular_solve` PR on going, https://github.com/pytorch/pytorch/pull/53147, which may be helpful on this case.

**Comment by Lezcano** [comment]
I believe these should be fixed in https://github.com/pytorch/pytorch/pull/66933 which is already available in master. @realiti4 could you confirm?

**Comment by realiti4** [comment]
> I believe these should be fixed in #66933 which is already available in master. @realiti4 could you confirm?

Hi, I'll test the fix and inform you soon.
