### ISSUE TITLE
ImportError: libtinfo.so.5

### ISSUE THREAD

**Issue by chiboreache** [pytorch/pytorch#53452]
## 🐛 Bug

```
python3.9/site-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *
ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory
```

## To Reproduce

run

```python
import torch

print("torch.__version__: ", torch.__version__)
print("cuda.is_available: ", torch.cuda.is_available())
```

## Environment

can't open `collect_env.py`

 - PyTorch Version: 1.8 (nightly tested too)
 - OS: Arch Linux
 - How you installed PyTorch: `pip`
 - Python version: 3.9.2:
 - GPU models and configuration: 5700XT + 5950X

**Comment by styler00dollar** [comment]
I tried to install it myself with a very similar environment.
```
- PyTorch Version: 1.8 (https://download.pytorch.org/whl/rocm4.0.1/torch-1.8.0%2Brocm4.0.1-cp39-cp39-linux_x86_64.whl)
- OS: Arch Linux (Manjaro)
- Installed with pip inside anaconda
- Python 3.9.1
- RX470 + I7 4770
```

```
Traceback (most recent call last):
  File "/home/x/codes/train.py", line 11, in <module>
    import torch
  File "/home/x/.local/lib/python3.9/site-packages/torch/init.py", line 196, in <module>
    from torch._C import *
ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory
```
Can confirm this, I have the same error.

**Comment by skyline75489** [comment]
I can confirm this issue on my Ubuntu. The fix is rather easy, for me I just install the `libncurses5` using:

```text
sudo apt install libncurses5
```

I wonder what introduced this particular dependency, though. Fact that `libncureses5` is somewhat an "out-of-data" version. The newer version is `libncurses6`.
