### ISSUE TITLE
Library location assumption in test/jit/test_backends.py, test/jit/test_torchbind.py, and test/test_fx.py

### ISSUE THREAD

**Issue by branfosj** [pytorch/pytorch#53455]
## 🐛 Bug

`test/jit/test_backends.py`, `test/jit/test_torchbind.py`, and `test/test_fx.py` assume that the tests will be run with the `build` directory being a sibling to the `test` directory. If the tests are run from an alternative location then they each have tests that fail on a library load - `ibtorchbind_test.so` or `libjitbackend_test.so`.

Error is:
```
======================================================================
ERROR: test_native_callable (__main__.TestFX)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_fx.py", line 379, in test_native_callable
    torch.ops.load_library(str(p))
  File "/rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/PyTorch/1.8.0-foss-2020b/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /rds/projects/2017/branfosj-rse/ProblemSolving/pyt18/pytorch/build/lib/libtorchbind_test.so: cannot open shared object file: No such file or directory
```

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting. This is because these tests are actually across C++ and Python language, C++ generates a custom op library and Python portion tests it. Right now, indeed it is fragile because both parts need to agree on location of library. However, this is usually fine since PyTorch provides its own build script and test driver which ensures the locations of generated artifacts are in the right place.

As a work-around, could you try creating a symlink connecting the actual build folder to wherever you'd like the tests to run from?

**Comment by gmagogsfm** [comment]
Closing due to inactivity

**Comment by tktrungna** [comment]
#61960 has been land and solve this issue with an additional step of install torch wheel package
