### ISSUE TITLE
[FX] Ability to wrap functions in other modules for symbolic tracing

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [pytorch/pytorch#53534]
## 🚀 Feature

It is not currently possible to trace an imported function that requires function wrapping:

`mod.py`
```python
import torch
def f(x):
    return len(x)
```

`main.py`
```python
import torch
import torch.fx

torch.fx.wrap('len')

from mod import f

x = torch.randn(3, 4)
print(f(x))

def g(x):
    return len(x)

g_fx = torch.fx.symbolic_trace(g)
print(g_fx)

f_fx = torch.fx.symbolic_trace(f)
print(f_fx)
```
gives
```
3
g()

def forward(self, x):
    len_1 = len(x);  x = None
    return len_1
    
    raise RuntimeError("'len' is not supported in symbolic tracing by default. If you want "
RuntimeError: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope
```

## Motivation

FX transforms may sometimes require a graph that does not treat functions or modules that are imported as leaf nodes — for example, an optimization transform that does operator fusion may need to access the internal graph of some library function that happens to use `math.sqrt`, for example.

## Pitch

Either extending `torch.fx.wrap` to handle this case automatically, or providing a way to ask it to wrap for a function or module:
```
torch.fx.wrap('len', for_function=f)
```

## Alternatives

This works:
```python
exec("import torch.fx; torch.fx.wrap('len')", f.__globals__)

f_fx = torch.fx.symbolic_trace(f)
print(f_fx)
```
gives
```
f()

def forward(self, x):
    len_1 = len(x);  x = None
    return len_1
```
and may provide a starting point for implementing this feature.

**Comment by alexander-soare** [comment]
@Linux-cpp-lisp just to check, is doing `torch.fx.wrap(f)` after the import in `main.py` the sort of solution you want?

**Comment by Linux-cpp-lisp** [comment]
Yes @alexander-soare — it makes sense to me that this is something the client code (which is using `fx`) is responsible for. Given that, your proposed solution is even better, moving away from global state entirely into arguments to the _actual_ client code, which is the call to the FX tracer.

**Comment by youkaichao** [comment]
Hi, I tried the solution of `exec("import torch.fx; torch.fx.wrap('len')", f.__globals__)`, but it does not work. Do I miss something?

It still raises an exception saying that "RuntimeError: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope"

And, it is very strange, why such a common operator like `len` is not supported?

**Comment by youkaichao** [comment]
@alexander-soare autowrap_functions does not work.

mod.py:
```
import torch
def f(x):
    return len(x)
```

main.py:
```
import torch
import torch.fx

torch.fx.wrap('len')

from mod import f

x = torch.randn(3, 4)
print(f(x))

def g(x):
    return len(x)

g_fx = torch.fx.Tracer(autowrap_functions=(len, )).trace(g)
print(g_fx)

f_fx = torch.fx.Tracer(autowrap_functions=(len, )).trace(f)
print(f_fx)
```

error with tracing `f`:
```
RuntimeError: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope
```

**Comment by rpl-alan-shangguan** [comment]
I got this error when I train a segformer_b2, use segformer_mit-b2_8xb1-160k_cityscapes-1024x1024.py
```
09/06 08:20:19 - mmengine - INFO - Enabling the "efficient_conv_bn_eval" feature for sub-modules: ['backbone']
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    runner.train()
  File "/home/alan/Downloads/mmengine/mmengine/runner/runner.py", line 1738, in train
    turn_on_efficient_conv_bn_eval(ori_model, modules)
  File "/home/alan/Downloads/mmengine/mmengine/model/efficient_conv_bn_eval.py", line 158, in turn_on_efficient_conv_bn_eval
    turn_on_efficient_conv_bn_eval_for_single_model(module)
  File "/home/alan/Downloads/mmengine/mmengine/model/efficient_conv_bn_eval.py", line 147, in turn_on_efficient_conv_bn_eval_for_single_model
    fx_model: fx.GraphModule = fx.symbolic_trace(model)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 1070, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/backbones/mit.py", line 444, in forward
    x = block(x, hw_shape)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 434, in call_module
    return forward(*args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/backbones/mit.py", line 294, in forward
    x = _inner_forward(x)
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/backbones/mit.py", line 287, in _inner_forward
    x = self.attn(self.norm1(x), hw_shape, identity=x)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 434, in call_module
    return forward(*args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/backbones/mit.py", line 161, in forward
    x_kv = nlc_to_nchw(x, hw_shape)
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/utils/shape_convert.py", line 13, in nlc_to_nchw
    assert len(x.shape) == 3
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/fx/proxy.py", line 305, in __len__
    raise RuntimeError("'len' is not supported in symbolic tracing by default. If you want "
RuntimeError: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope
```

**Comment by Rickustc** [comment]
I also meet this error "    raise RuntimeError("'len' is not supported in symbolic tracing by default. If you want "
RuntimeError: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope"
it was raised in Proxy's __len__ method....and i cant solve it by torch.fx.wrap('len') ：D

**Comment by Priyanshu88** [comment]
> I also meet this error " raise RuntimeError("'len' is not supported in symbolic tracing by default. If you want " RuntimeError: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope" it was raised in Proxy's **len** method....and i cant solve it by torch.fx.wrap('len') ：D

Have you resolved this issue? How?
