### ISSUE TITLE
RuntimeError: Failed to export an ONNX attribute 'onnx::Sub'

### ISSUE THREAD

**Issue by whcjb** [pytorch/pytorch#53594]
## 🐛 Bug

trying from pytorch model to onnx using onnx.export(), occur bug.
`Traceback (most recent call last):
  File "examples/inpainting/inpainting_onnx.py", line 39, in <module>
    torch.onnx.export(model, (x, mask), "./examples/inpainting/inpainting.onnx", verbose=True, input_names=input_names, output_names=output_names, opset_version=10)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py", line 83, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Sub', since it's not constant, please try to make things (e.g., kernel size) static if possible
`

## To Reproduce

1. 
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): centos
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 
 - Any other relevant information: opset10

## Additional context

when the onnx outbreak errors, dont know where the exactly the proble come from, the traceback dint have little with the original code. cant know what cause the onnx::Sub problem.

**Comment by spandantiwari** [comment]
@whcjb - Please try the latest version of PyTorch (1.8). Quite a few updates have gone in since the version you are using (1.6).

If you still see this error, please re-open this issue along with the model and export code to repro the issue.
