### ISSUE TITLE
test_metal.py must skip when not compiled with metal support

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53627]
Steps to reproduce:
1. `python test/test_metal.py` on a non-metal build of PyTorch

Result:
```
======================================================================
ERROR: test_conv (__main__.TestMetalRewritePass)
----------------------------------------------------------------------
Traceback (most recent call last):                                                                           
  File "test/test_metal.py", line 84, in test_conv   
    TestMetalRewritePass.validate_transformed_module(Conv2D(), pattern_count_map, data_shape)
  File "test/test_metal.py", line 34, in validate_transformed_module
    torch.jit.save(scripted_model, buffer)
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_serialization.py", line 83, in save
    ret = m.save_to_buffer(_extra_files=_extra_files)                                                        
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_script.py", line 515, in save_to_buffer
    return self._c.save_to_buffer(*args, **kwargs)
RuntimeError:    
Schema not found for node. File a bug report.                                                                
Node: %29 : Tensor = metal_prepack::conv2d_prepack(%3, %4, %11, %14, %17, %8, %28, %28)
```

There shouldn't be an error here. Actually, arguably, schema should always be found (but there should be no implementations)

**Comment by ezyang** [comment]
cc @xta0
