### ISSUE TITLE
Exception ignored in DataLoader _shutdown_workers when using tqdm.auto

### ISSUE THREAD

**Issue by rafi-cohen** [pytorch/pytorch#53703]
## 🐛 Bug

I'm getting a bunch of "Exception ignored" warnings when using a `DataLoader` wrapped by `tqdm.auto`.
The errors occur within the `_shutdown_workers` method of `_MultiProcessingDataLoaderIter`. However, these are `AssertionError`s that originate from python's multiprocessing module, so I'm not entirely sure if this is actually a PyTorch bug.

## To Reproduce

1. Wrap a `DataLoader` with `num_workers`>0 with a `tqdm.auto.tqdm` object
2. Iterate it until you get the following warning:
```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f7162a08af0>
Traceback (most recent call last):
  File "path/to/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "path/to/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "path/to/env/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

Below is a simple code snippet reproducing the problem:
```python
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import FakeData
from tqdm.auto import tqdm


dataset = FakeData(size=100, transform=transforms.ToTensor(), num_classes=1000)
dataloader = DataLoader(dataset, batch_size=32, shuffle=False, num_workers=2, pin_memory=True)
epochs = 90
for _ in tqdm(range(epochs)):
    for _ in tqdm(dataloader, leave=False):
        continue
```

## Expected behavior

Should work without any warnings, exceptions, or errors
~Sidenot: I would also expect errors like this to propagate (and eventually crash the program), rather than being "ignored".~ (edit: this is expected behavior in Python)

## Environment
<details>
<summary>collect_env.py output</summary>
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch
</details>

PyTorch was installed using `conda env create -f environment.yml`, with the following `environment.yml`:
```yaml
name: env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.8
  - cudatoolkit=11.1
  - torchvision
  - torchaudio
  - tqdm
  - viztracer
  - PyYAML
```
## Additional context
* Setting `num_workers=0` obviously avoids this issue, however it is not a desirable solution.
* While the traceback doesn't mention anything about `tqdm`, it seems that replacing `tqdm.auto.tqdm` with `tqdm.tqdm` solves this issue. But I thought I'd still report it just in case there actually is a bug in the `DataLoader`.
* Related post from the forum, comments also mention replacing `tqdm.auto` with `tqdm` (wish I found it sooner): https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845
* I also found this, not sure if it's related: https://bugs.python.org/issue39021

cc @SsnL @VitalyFedyunin @ejguan

**Comment by rafi-cohen** [comment]
> * All exceptions in `__del__` are ignored in Python https://docs.python.org/3/reference/datamodel.html#object.__del__

Thanks for the link, I did not know about that. I originally thought that the "Exception ignored" was a PyTorch thing. Anyway, I edited the relevant part from the issue report.

And thanks for looking into this!

**Comment by ejguan** [comment]
Closing the issue. Feel free to re-open it if needed.

**Comment by Johnqczhang** [comment]
I met a similar issue when evaluating the model during training with `num_workers = 8` in the [detectron2](https://github.com/facebookresearch/detectron2) framework (with `torch-1.10.0+cu102` and `python-3.8.12`). However, this issue doesn't happen when I switch to another machine with the same environment and training configuration. Can anyone give me some help?

> Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f3924085280>
Traceback (most recent call last):
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1295, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "tools/train_net.py", line 262, in <module>
    launch(
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/disk1/johnqczhang/exp/adet/tools/train_net.py", line 256, in main
    return trainer.train()
  File "/disk1/johnqczhang/exp/adet/tools/train_net.py", line 103, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/disk1/johnqczhang/exp/adet/tools/train_net.py", line 93, in train_loop
    self.after_step()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 552, in after_step
    self._do_eval()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 525, in _do_eval
    results = self._func()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 608, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 149, in inference_on_dataset
    for idx, inputs in enumerate(data_loader):
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
      return _MultiProcessingDataLoaderIter(self)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable

**Comment by Adeyinka-hub** [comment]
@Johnqczhang 
I resolved the bug by just replacing "from tqdm.auto import tqdm" with "from tqdm import tqdm".   
Note that: Any num_workers = 0 can only be used with "from tqdm.auto import tqdm" but any num_workers > 0 can only be used with "from tqdm import tqdm".
Hope it's cleared now, just replace  "from tqdm.auto import tqdm" with "from tqdm import tqdm".
