### ISSUE TITLE
ZeroDivisionError: float division by zero (bias_correction1 is zero)

### ISSUE THREAD

**Issue by kenorb** [pytorch/pytorch#53758]
## 🐛 Bug

> ZeroDivisionError: float division by zero

## To Reproduce

1. Error happens at rare occasions.

```
                if self.optim:
                    if zero_grad:
                        # Zero gradients.
                        self.optim.zero_grad()

                # Perform a backward pass, and update the weights.
                loss.backward()

                if self.optim:
                    self.optim.step()
```

## Environment

```
Collecting environment information...
/home/kenorb/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect
```

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Build command you used (if compiling from source): n/a
 - Python version: 3.8.5
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

## Additional context

```
Traceback (most recent call last):
  File "./main.py", line 128, in <module>
    tm.run()
  File "/home/kenorb/Train.py", line 278, in run
    self.optim.step()
  File "/home/kenorb/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/kenorb/.local/lib/python3.8/site-packages/torch/optim/adam.py", line 108, in step
    F.adam(params_with_grad,
  File "/home/kenorb/.local/lib/python3.8/site-packages/torch/optim/functional.py", line 96, in adam
    step_size = lr / bias_correction1
ZeroDivisionError: float division by zero
```

**Comment by CAFdeGitHub** [comment]
The same issue exist for pytorch 2.0.1. 
<img width="755" alt="Screenshot 2023-06-01 at 22 16 45" src="https://github.com/pytorch/pytorch/assets/7681915/fcf259de-48bc-4feb-97fa-f9fc73f621fa">
It seems work fine if i train model at cpu. 
the reason for the error come to torch.__foreach__add. It assign zero to device_state_steps.
