### ISSUE TITLE
After the source code is compiled, an error will be reported fvcore

### ISSUE THREAD

**Issue by nmanhong** [pytorch/pytorch#53862]
python:3.7.9
linux:centos
Traceback (most recent call last):
  File "demo/demo.py", line 12, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/loongson/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/loongson/detectron2/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/loongson/detectron2/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/home/loongson/detectron2/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/home/loongson/detectron2/detectron2/layers/__init__.py", line 19, in <module>
    from .blocks import CNNBlockBase, DepthwiseSeparableConv2d
  File "/home/loongson/detectron2/detectron2/layers/blocks.py", line 4, in <module>
    import fvcore.nn.weight_init as weight_init
  File "/usr/local/python3/lib/python3.7/site-packages/fvcore/nn/__init__.py", line 4, in <module>
    from .focal_loss import (
  File "/usr/local/python3/lib/python3.7/site-packages/fvcore/nn/focal_loss.py", line 51, in <module>
    sigmoid_focal_loss
  File "/usr/local/python3/lib/python3.7/site-packages/torch/jit/_script.py", line 940, in script
    qualified_name, ast, _rcb, get_default_args(obj)
TypeError: Object of type 'module' is not an instance of 'function'

**Comment by gmagogsfm** [comment]
Hi @nmanhong,

Could you provide steps to reproduce the issue? Thanks

**Comment by nmanhong** [comment]
@gmagogsfm

Just compile normally
1. "python3 setup.py build --cmake only"
2. "ccmake build"
3. "python3 setup.py install develop"
In the second step
already setup:
export BUILD_CUSTOM_PROTOBUF=OFF
export protobuf_BUILD_PROTOC_BINARIES=OFF
export protobuf_BUILD_SHARED_LIBS=ON
export CAFFE2_STATIC_LINK_PROTUBUF=OFF
I haven’t changed other operations. I don’t know why this error occurs.

**Comment by nmanhong** [comment]
Is this error caused by JIT or pytorch?

**Comment by tugsbayasgalan** [comment]
Is there a file or test we can run to reproduce this issue? It looks like just an instruction on how to compile?

**Comment by nmanhong** [comment]
@tugsbayasgalan
Yes, as long as I run the demo of detectron2, this problem occurs

**Comment by gmagogsfm** [comment]
> @tugsbayasgalan
> Yes, as long as I run the demo of detectron2, this problem occurs

Do you mean here?
https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html

What commandline arguments are you using with demo.py?

**Comment by nmanhong** [comment]
Yes this is my order
"python3 demo/demo.py --config-file ./configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --input ./itest/000000290640.jpg --output ./otest/ --opts MODEL.WEIGHTS /home/loongson/pkl_model/model_final_280758.pkl MODEL.DEVICE cpu"

**Comment by nmanhong** [comment]
@gmagogsfm

**Comment by nmanhong** [comment]
Can I directly disable JIT when compiling? What I mean is to set options when compiling. When it is in use, it directly disables JIT instead of commanding "export PYTORCH_JIT=0" when using it. To avoid errors, or do I install this JIT separately first? Then compile pytorch

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
