### ISSUE TITLE
Segmentation fault in dataloader after upgrading to pytorch v1.8.0

### ISSUE THREAD

**Issue by Haydnspass** [pytorch/pytorch#53894]
## 🐛 Bug

I get a segmentation fault in the dataloader upgrading to pytorch v1.8.0.
The worker crash immediately.
With pytorch v1.7.1 it works without any issues.

Is there anything substantial that changed and needs to be accounted for?

## Expected behavior

No segmentation fault.

## Environment
```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.15.5

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 460.32.03
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0
[conda] blas                      2.108                       mkl    conda-forge
[conda] blas-devel                3.9.0                     8_mkl    conda-forge
[conda] cudatoolkit               10.2.89              h8f6ccaa_8    conda-forge
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] liblapacke                3.9.0                     8_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-devel                 2020.4             ha770c72_305    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.19.5           py39hdbf815f_1    conda-forge
[conda] pytorch                   1.8.0           py3.9_cuda10.2_cudnn7.6.5_0    pytorch
```

## Additional context

I tried to debug with gdb:

```bash
(decode_dev_cuda) lucas@pc-ries25:~/DeepSMLM$ gdb --args python -m decode.neuralfitter.train.live_engine -p config/template.yaml -i cuda:0 -w 10 --no_log --debug
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.
(gdb) run
Starting program: /home/lucas/xconda3/envs/decode_dev_cuda/bin/python -m decode.neuralfitter.train.live_engine -p config/template.yaml -i cuda:0 -w 10 --no_log --debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff5fbd4700 (LWP 19441)]
/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/runpy.py:127: RuntimeWarning: 'decode.neuralfitter.train.live_engine' found in sys.modules after import of package 'decode.neuralfitter.train', but prior to execution of 'decode.neuralfitter.train.live_engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[New Thread 0x7fff5e1e9700 (LWP 19443)]
[New Thread 0x7fff5d9e8700 (LWP 19444)]
[New Thread 0x7fff5d1e7700 (LWP 19445)]
[New Thread 0x7fff5c9e6700 (LWP 19446)]
[New Thread 0x7fff57fff700 (LWP 19447)]
[New Thread 0x7fff577fe700 (LWP 19448)]
[New Thread 0x7fff56ffd700 (LWP 19449)]
[New Thread 0x7fff567fc700 (LWP 19450)]
[New Thread 0x7fff55ffb700 (LWP 19451)]
[New Thread 0x7fff557fa700 (LWP 19452)]
[New Thread 0x7fff54ff9700 (LWP 19453)]
[New Thread 0x7fff547f8700 (LWP 19454)]
[New Thread 0x7fff53ff7700 (LWP 19455)]
[New Thread 0x7fff537f6700 (LWP 19456)]
[New Thread 0x7fff52ff5700 (LWP 19457)]
[New Thread 0x7fff527f4700 (LWP 19458)]
[New Thread 0x7fff51ff3700 (LWP 19459)]
[New Thread 0x7fff517f2700 (LWP 19460)]
[New Thread 0x7fff50ff1700 (LWP 19461)]
[New Thread 0x7fff3ffff700 (LWP 19462)]
[New Thread 0x7fff3f7fe700 (LWP 19463)]
[New Thread 0x7fff3effd700 (LWP 19464)]
[Thread 0x7fff50ff1700 (LWP 19461) exited]
[Thread 0x7fff517f2700 (LWP 19460) exited]
[Thread 0x7fff51ff3700 (LWP 19459) exited]
[Thread 0x7fff527f4700 (LWP 19458) exited]
[Thread 0x7fff52ff5700 (LWP 19457) exited]
[Thread 0x7fff537f6700 (LWP 19456) exited]
[Thread 0x7fff53ff7700 (LWP 19455) exited]
[Thread 0x7fff547f8700 (LWP 19454) exited]
[Thread 0x7fff54ff9700 (LWP 19453) exited]
[Thread 0x7fff557fa700 (LWP 19452) exited]
[Thread 0x7fff55ffb700 (LWP 19451) exited]
[Thread 0x7fff567fc700 (LWP 19450) exited]
[Thread 0x7fff577fe700 (LWP 19448) exited]
[Thread 0x7fff57fff700 (LWP 19447) exited]
[Thread 0x7fff5c9e6700 (LWP 19446) exited]
[Thread 0x7fff5d1e7700 (LWP 19445) exited]
[Thread 0x7fff5d9e8700 (LWP 19444) exited]
[Thread 0x7fff5e1e9700 (LWP 19443) exited]
[Thread 0x7fff56ffd700 (LWP 19449) exited]
[New Thread 0x7fff50ff1700 (LWP 19465)]
[New Thread 0x7fff517f2700 (LWP 19466)]
Model instantiated.
Model initialised as specified in the constructor.
[New Thread 0x7fff51ff3700 (LWP 19467)]
[New Thread 0x7fff527f4700 (LWP 19468)]
[New Thread 0x7fff5d379700 (LWP 19469)]
[Thread 0x7fff3f7fe700 (LWP 19463) exited]
[Thread 0x7fff3effd700 (LWP 19464) exited]
[Thread 0x7fff3ffff700 (LWP 19462) exited]
[New Thread 0x7fff5cb77780 (LWP 19470)]
[New Thread 0x7fff54bd0800 (LWP 19471)]
[New Thread 0x7fff543ce880 (LWP 19472)]
Sampled dataset in 0.05s. 20828 emitters on 1025 frames.
Sampled dataset in 0.01s. 2501 emitters on 129 frames.
[New Thread 0x7fff3effd700 (LWP 19473)]
  0%|                                                                                                                         | 0/15 [00:00<?, ?it/s]ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
[New Thread 0x7fff3f7fe700 (LWP 19493)]
[Thread 0x7fff5d379700 (LWP 19469) exited]
[Thread 0x7fff527f4700 (LWP 19468) exited]
[Thread 0x7fff51ff3700 (LWP 19467) exited]
ERROR: Unexpected segmentation fault encountered in worker.
[New Thread 0x7fff5d379700 (LWP 19495)]
[New Thread 0x7fff527f4700 (LWP 19496)]
[New Thread 0x7fff51ff3700 (LWP 19497)]
[New Thread 0x7fff3ffff700 (LWP 19498)]
[New Thread 0x7fff53bcd700 (LWP 19499)]
[New Thread 0x7fff533cc700 (LWP 19500)]
[New Thread 0x7fff3e7fc700 (LWP 19501)]
[New Thread 0x7fff3dffb700 (LWP 19502)]
[New Thread 0x7fff3d7fa700 (LWP 19503)]
[New Thread 0x7fff3cff9700 (LWP 19504)]
  0%|                                                                                                                         | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 19478) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lucas/RemoteDeploy/DeepSMLM/decode/neuralfitter/train/live_engine.py", line 437, in <module>
    live_engine_setup(args.param_file, args.device, args.debug, args.no_log, args.num_worker_override, args.log_folder,
  File "/home/lucas/RemoteDeploy/DeepSMLM/decode/neuralfitter/train/live_engine.py", line 175, in live_engine_setup
    train_loss = decode.neuralfitter.train_val_impl.train(
  File "/home/lucas/RemoteDeploy/DeepSMLM/decode/neuralfitter/train_val_impl.py", line 21, in train
    for batch_num, (x, y_tar, weight) in enumerate(tqdm_enum):  # model input (x), target (yt), weights (w)
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1138, in _get_data
    success, data = self._try_get_data()
  File "/home/lucas/xconda3/envs/decode_dev_cuda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 19474, 19476, 19478, 19480) exited unexpectedly
[Thread 0x7fff3effd700 (LWP 19473) exited]
[Thread 0x7fff3dffb700 (LWP 19502) exited]
[Thread 0x7fff533cc700 (LWP 19500) exited]
[Thread 0x7fff3ffff700 (LWP 19498) exited]
[Thread 0x7fff527f4700 (LWP 19496) exited]
[Thread 0x7fff3cff9700 (LWP 19504) exited]
[Thread 0x7fff3d7fa700 (LWP 19503) exited]
[Thread 0x7fff53bcd700 (LWP 19499) exited]
[Thread 0x7fff51ff3700 (LWP 19497) exited]
[Thread 0x7fff5d379700 (LWP 19495) exited]
[Thread 0x7fff3e7fc700 (LWP 19501) exited]
[Thread 0x7fff54bd0800 (LWP 19471) exited]
[Thread 0x7fff543ce880 (LWP 19472) exited]
[Thread 0x7fff5cb77780 (LWP 19470) exited]
[Thread 0x7fff50ff1700 (LWP 19465) exited]
[Thread 0x7fff517f2700 (LWP 19466) exited]
[Thread 0x7fff5fbd4700 (LWP 19441) exited]
[Thread 0x7ffff7fd1740 (LWP 19427) exited]
[Inferior 1 (process 19427) exited with code 01]
(gdb) bt
No stack.
(gdb) 
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @SsnL @VitalyFedyunin @ejguan

**Comment by ngimel** [comment]
#53565 might be related.

**Comment by ezyang** [comment]
Unfortunately the gdb session is not that useful because the segfault happened in a worker (which was not attached in gdb). Maybe you can get it to dump a core dump and then inspect it post facto in gdb. Any chance you can share the script?

**Comment by malfet** [comment]
@Haydnspass can you please run gdb with `set follow-fork-mode child` to get a backtrace of the crash in the child thread?
Something like (after ignoring the first fork, which is a call to `uname -p`. This can be achieved by setting a breakpoint on `fork` and then continuing over the first  instance:
` b fork`, `run`, `continue`, `set follow-fork-mode child`, `continue`

**Comment by datumbox** [comment]
I'm hitting the same problem and I have a consistent way to reproduce the problem every time using FB infra. In my case the issue appears in a well tested pipeline of TorchVision and occurs only if workers > 0 and the job runs on a multi-node and multi-GPU setup. The problem does not appear on a single node multi-GPU setup.

Let me know if I can help you debug the issue.
