### ISSUE TITLE
test_remote_module (__main__.TensorPipeTensorPipeDistAutogradTestWithSpawn) is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#53901]
https://app.circleci.com/pipelines/github/pytorch/pytorch/283943/workflows/09a33011-2ef9-4e71-a4cd-8d6eac6de626/jobs/11465225/steps

```
Mar 11 11:58:14 ======================================================================
Mar 11 11:58:14 ERROR [64.403s]: test_remote_module (__main__.TensorPipeTensorPipeDistAutogradTestWithSpawn)
Mar 11 11:58:14 ----------------------------------------------------------------------
Mar 11 11:58:14 Traceback (most recent call last):
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
Mar 11 11:58:14     self._join_processes(fn)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 418, in _join_processes
Mar 11 11:58:14     self._check_return_codes(elapsed_time)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 461, in _check_return_codes
Mar 11 11:58:14     raise RuntimeError(error)
Mar 11 11:58:14 RuntimeError: Process 3 exited with error code 10 and exception:
Mar 11 11:58:14 Traceback (most recent call last):
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 11 11:58:14     getattr(self, test_name)()
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 11 11:58:14     fn()
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
Mar 11 11:58:14     return func(*args, **kwargs)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2316, in test_remote_module
Mar 11 11:58:14     result = local_compute(input)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
Mar 11 11:58:14     return forward_call(*input, **kwargs)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2285, in forward
Mar 11 11:58:14     return self.next_stage.rpc_sync().forward(input)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/rref_proxy.py", line 34, in _invoke_rpc
Mar 11 11:58:14     timeout=timeout
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 79, in wrapper
Mar 11 11:58:14     return func(*args, **kwargs)
Mar 11 11:58:14   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 790, in rpc_sync
Mar 11 11:58:14     return fut.wait()
Mar 11 11:58:14 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
```

```
Mar 11 11:58:13   test_remote_module (__main__.TensorPipeTensorPipeDistAutogradTestWithSpawn) ... ERROR:root:Caught exception: 
Mar 11 11:58:13 Traceback (most recent call last):
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 11 11:58:13     getattr(self, test_name)()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 11 11:58:13     fn()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2316, in test_remote_module
Mar 11 11:58:13     result = local_compute(input)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
Mar 11 11:58:13     return forward_call(*input, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2285, in forward
Mar 11 11:58:13     return self.next_stage.rpc_sync().forward(input)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/rref_proxy.py", line 34, in _invoke_rpc
Mar 11 11:58:13     timeout=timeout
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 79, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 790, in rpc_sync
Mar 11 11:58:13     return fut.wait()
Mar 11 11:58:13 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Mar 11 11:58:13 exiting process with exit code: 10
Mar 11 11:58:13 ERROR:root:Caught exception: 
Mar 11 11:58:13 Traceback (most recent call last):
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 11 11:58:13     getattr(self, test_name)()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 11 11:58:13     fn()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2316, in test_remote_module
Mar 11 11:58:13     result = local_compute(input)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
Mar 11 11:58:13     return forward_call(*input, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2285, in forward
Mar 11 11:58:13     return self.next_stage.rpc_sync().forward(input)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/rref_proxy.py", line 34, in _invoke_rpc
Mar 11 11:58:13     timeout=timeout
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 79, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 790, in rpc_sync
Mar 11 11:58:13     return fut.wait()
Mar 11 11:58:13 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Mar 11 11:58:13 exiting process with exit code: 10
Mar 11 11:58:13 ERROR:root:Caught exception: 
Mar 11 11:58:13 Traceback (most recent call last):
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 11 11:58:13     getattr(self, test_name)()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 11 11:58:13     fn()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2316, in test_remote_module
Mar 11 11:58:13     result = local_compute(input)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
Mar 11 11:58:13     return forward_call(*input, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2285, in forward
Mar 11 11:58:13     return self.next_stage.rpc_sync().forward(input)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/rref_proxy.py", line 34, in _invoke_rpc
Mar 11 11:58:13     timeout=timeout
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 79, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 790, in rpc_sync
Mar 11 11:58:13     return fut.wait()
Mar 11 11:58:13 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Mar 11 11:58:13 exiting process with exit code: 10
Mar 11 11:58:13 ERROR:root:Caught exception: 
Mar 11 11:58:13 Traceback (most recent call last):
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 366, in run_test
Mar 11 11:58:13     getattr(self, test_name)()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 11 11:58:13     fn()
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 99, in wrapper
Mar 11 11:58:13     return func(*args, **kwargs)
Mar 11 11:58:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2318, in test_remote_module
Mar 11 11:58:13     dist_autograd.backward(context_id, [loss])
Mar 11 11:58:13 RuntimeError: Error on Node 1: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Mar 11 11:58:13 exiting process with exit code: 10
Mar 11 11:58:14 [W tensorpipe_agent.cpp:693] RPC agent for worker0 encountered error when sending response to request #16 to worker3: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:260)
Mar 11 11:58:14 terminate called after throwing an instance of 'c10::Error'
Mar 11 11:58:14   what():  invalid device pointer: 0x7c2b960000
Mar 11 11:58:14 Exception raised from free at /var/lib/jenkins/workspace/c10/cuda/CUDACachingAllocator.cpp:890 (most recent call first):
Mar 11 11:58:14 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7fcff04ab3ab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 11 11:58:14 frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xce (0x7fcff049a6be in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 11 11:58:14 frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x4bf (0x7fcff06e187f in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
Mar 11 11:58:14 frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7fcff04882c4 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 11 11:58:14 frame #4: std::_Sp_counted_ptr_inplace<torch::distributed::rpc::TensorpipeWriteBuffers, std::allocator<torch::distributed::rpc::TensorpipeWriteBuffers>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() + 0x9a (0x7fd00afd3d9a in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #5: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0x46 (0x7fd00a6dcbf6 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #6: <unknown function> + 0xbb26e1 (0x7fd00afc66e1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #7: <unknown function> + 0xc19f5f (0x7fd00b02df5f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #8: tensorpipe::PipeImpl::callWriteCallback(tensorpipe::OpsStateMachine<tensorpipe::PipeImpl, tensorpipe::WriteOperation>::Iter) + 0x67 (0x7fd00b0229b7 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #9: tensorpipe::PipeImpl::advanceWriteOperation(tensorpipe::OpsStateMachine<tensorpipe::PipeImpl, tensorpipe::WriteOperation>::Iter, tensorpipe::WriteOperation::State) + 0x159 (0x7fd00b021ba9 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #10: <unknown function> + 0xc27de0 (0x7fd00b03bde0 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #11: <unknown function> + 0xc1fe83 (0x7fd00b033e83 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #12: tensorpipe::ContextImpl::deferToLoop(std::function<void ()>) + 0x164 (0x7fd00b004a64 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #13: <unknown function> + 0xc15f65 (0x7fd00b029f65 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #14: <unknown function> + 0xcd4095 (0x7fd00b0e8095 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #15: tensorpipe::channel::cuda_basic::ChannelImpl::callSendCallback(tensorpipe::OpsStateMachine<tensorpipe::channel::cuda_basic::ChannelImpl, tensorpipe::channel::cuda_basic::ChunkSendOperation>::Iter) + 0x1e (0x7fd00b183d5e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #16: <unknown function> + 0xd793c9 (0x7fd00b18d3c9 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #17: tensorpipe::channel::cuda_basic::ChannelImpl::advanceChunkSendOperation(tensorpipe::OpsStateMachine<tensorpipe::channel::cuda_basic::ChannelImpl, tensorpipe::channel::cuda_basic::ChunkSendOperation>::Iter, tensorpipe::channel::cuda_basic::ChunkSendOperation::State) + 0x101 (0x7fd00b184981 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #18: <unknown function> + 0xd790e5 (0x7fd00b18d0e5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #19: <unknown function> + 0xd7741c (0x7fd00b18b41c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #20: <unknown function> + 0xbeca84 (0x7fd00b000a84 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #21: tensorpipe::channel::cuda_basic::ContextImpl::deferToLoop(std::function<void ()>) + 0x5b (0x7fd00b0e19db in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #22: <unknown function> + 0xd753be (0x7fd00b1893be in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #23: <unknown function> + 0xca86e5 (0x7fd00b0bc6e5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #24: <unknown function> + 0xd510f6 (0x7fd00b1650f6 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #25: tensorpipe::channel::basic::ContextImpl::deferToLoop(std::function<void ()>) + 0x16f (0x7fd00b0b644f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #26: <unknown function> + 0xd4f3aa (0x7fd00b1633aa in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #27: <unknown function> + 0xc7f4c5 (0x7fd00b0934c5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #28: tensorpipe::transport::shm::ConnectionImpl::handleErrorImpl() + 0x30d (0x7fd00b11b36d in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #29: tensorpipe::transport::ConnectionImplBoilerplate<tensorpipe::transport::shm::ContextImpl, tensorpipe::transport::shm::ListenerImpl, tensorpipe::transport::shm::ConnectionImpl>::handleError() + 0x159 (0x7fd00b090659 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #30: tensorpipe::transport::shm::ConnectionImpl::handleEventInFromLoop() + 0x88b (0x7fd00b11961b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #31: tensorpipe::transport::shm::ConnectionImpl::handleEventsFromLoop(int) + 0x5c8 (0x7fd00b11a2d8 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #32: tensorpipe::EpollLoop::handleEpollEventsFromLoop(std::vector<epoll_event, std::allocator<epoll_event> >) + 0xe3 (0x7fd00b115773 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #33: <unknown function> + 0xd018f2 (0x7fd00b1158f2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #34: <unknown function> + 0xd1ac11 (0x7fd00b12ec11 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #35: <unknown function> + 0xcfdd90 (0x7fd00b111d90 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #36: std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (tensorpipe::EventLoopDeferredExecutor::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), tensorpipe::EventLoopDeferredExecutor*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_run() + 0x75 (0x7fd00b111ad5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 11 11:58:14 frame #37: <unknown function> + 0xc819d (0x7fd00e54819d in /opt/conda/lib/libstdc++.so.6)
Mar 11 11:58:14 frame #38: <unknown function> + 0x76ba (0x7fd0446d76ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Mar 11 11:58:14 frame #39: clone + 0x6d (0x7fd04440d4dd in /lib/x86_64-linux-gnu/libc.so.6)
Mar 11 11:58:14 
Mar 11 11:58:14 Process 3 terminated with exit code 10, terminating remaining processes.
Mar 11 11:58:14 ERROR (64.403s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by mrshenli** [comment]
cc @SciPioneer @pritamdamania87

**Comment by pritamdamania87** [comment]
Should be fixed after https://github.com/pytorch/pytorch/pull/53929
