### ISSUE TITLE
torch.fx replacement doesn't handle torch.narrow with dynamic inputs

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#53938]
## 🐛 Bug

torch.fx replacement doesn't handle torch.narrow with dynamic inputs

## To Reproduce

```
import torch
from torch.fx import symbolic_trace, replace_pattern

def pattern(inp):
    return inp

def replacement(inp):
    return torch.narrow(inp, 0, 0, inp.size(0) // 2)

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, inp):
        return inp


if __name__ == "__main__":

    traced_model = symbolic_trace(MyModule())
    print ('Before Replacement: {}'.format(traced_model.code))

    replace_pattern(traced_model, pattern, replacement)

    traced_model.recompile()

    print ('After Replacement: {}'.format(traced_model.code))

    traced_model(torch.rand(10))
```

Output:

```
Before Replacement: 
def forward(self, inp):
    return inp
    
Traceback (most recent call last):
  File "/tmp/test.py", line 23, in <module>
    replace_pattern(traced_model, pattern, replacement)
  File "/data/users/pritam/pytorch/torch/fx/subgraph_rewriter.py", line 202, in replace_pattern
    replacement_graph = symbolic_trace(replacement).graph
  File "/data/users/pritam/pytorch/torch/fx/symbolic_trace.py", line 621, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/users/pritam/pytorch/torch/fx/symbolic_trace.py", line 368, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/tmp/test.py", line 8, in replacement
    return torch.narrow(inp, 0, 0, inp.size(0) // 2)
TypeError: narrow() received an invalid combination of arguments - got (Proxy, int, int, Proxy), but expected one of:
 * (Tensor input, int dim, Tensor start, int length)
      didn't match because some of the arguments have invalid types: (Proxy, int, int, Proxy)
 * (Tensor input, int dim, int start, int length)
      didn't match because some of the arguments have invalid types: (Proxy, int, int, Proxy)
```
## Expected behavior

Creating views of tensors based on input arguments is something that should be supported.

**Comment by pritamdamania87** [comment]
Duplicate of https://github.com/pytorch/pytorch/issues/53937.
