### ISSUE TITLE
[fx]  Only tensor can be proxied in builtin operators with `__torch_function__`

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#53937]
## 🐛 Bug

Only tensor can be proxied in builtin operators, which means we couldn't accept dynamic value for non-tensor arguments, pretty fundamental limitation, we should figure out a way to fix it.

## To Reproduce

```python
import torch
from torch.fx import symbolic_trace

def test(input, world_size):
    return input_1.size(1) / world_size


class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # self.param = torch.nn.Parameter(torch.rand(3, 4))
        # self.linear = torch.nn.Linear(4, 5)

    def forward(self, input, world_size):
        return torch.narrow(input, 0, 0, input.size(1) / world_size)
        # return torch.add(input, 1)


m = MyModule()

gm = symbolic_trace(m)
print(gm.code)
```

error:

```
Traceback (most recent call last):
  File "/private/home/wanchaol/test_fx.py", line 21, in <module>
    gm = symbolic_trace(m)
  File "/raid/wanchaol/pytorch/torch/fx/symbolic_trace.py", line 621, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/raid/wanchaol/pytorch/torch/fx/symbolic_trace.py", line 368, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/private/home/wanchaol/test_fx.py", line 15, in forward
    return torch.narrow(input, 0, 0, input.size(1) / world_size)
TypeError: narrow() received an invalid combination of arguments - got (Proxy, int, int, Proxy), but expected one of:
 * (Tensor input, int dim, Tensor start, int length)
      didn't match because some of the arguments have invalid types: (Proxy, int, int, Proxy)
 * (Tensor input, int dim, int start, int length)
      didn't match because some of the arguments have invalid types: (Proxy, int, int, Proxy)
```

## Expected behavior

should not crash

cc @jamesr66a

**Comment by Chillee** [comment]
This has the same root cause as https://github.com/pytorch/pytorch/issues/53678, except that this issue was previously hidden.

@bhosmer

**Comment by jamesr66a** [comment]
cc @ezyang @hameerabbasi we've been discussing this. It makes sense that `__torch_function__` supports only Tensor-like and TensorList-like arguments as there's still overload resolution happening, and if multiple datatypes can have `__torch_function__` defined overload resolution would be ambiguous. However, we're trying to figure out what the best UX for FX should be here. Some thoughts:

* Type-aware proxies, whose underlying types can be used in overload resolution. This has the upside that we have the same validation experience as now, but the downside is the implementation complexity of inferring types for every proxied value. (I have some infrastructure in https://github.com/pytorch/pytorch/pull/53653 https://github.com/pytorch/pytorch/pull/53830 that might be used for this, but not sure if it's feasible in general)
* Defer overload resolution during FX tracing. Essentially, when symbolic tracing, we just take whatever arguments the user specified, and overload resolution/validation happens later, e.g. as a separate schema validation pass or deferring it to runtime in the final generated code. I'd prefer the former, but we'd still need some way to infer concrete types for the proxy'ed values in the program. The latter introduces less complexity at the cost of making it so that passes don't have an assurance that the code is well formed (and consequently pushing the responsibility of schema validation onto pass authors)

**Comment by ezyang** [comment]
I was curious what Numpy did here, so I did a quick test:

```
import numpy as np

class MyArray:
    def __array_function__(self, func, types, args, kwargs):
        print((self, func, types, args, kwargs))

np.unique(MyArray(), 0, 1, 2, 3, 4, 5, 6, 7)
```

this fails with

```
(/home/ezyang/local/pytorch-tmp-env) [ezyang@devvm066.ash0 ~/local/pytorch-tmp] python arf.py
Traceback (most recent call last):
  File "arf.py", line 7, in <module>
    np.unique(MyArray(), 0, 1, 2, 3, 4, 5, 6, 7)
  File "<__array_function__ internals>", line 4, in unique
TypeError: _unique_dispatcher() takes from 1 to 5 positional arguments but 9 were given
```

So Numpy does test if the number of arguments is valid.  However, this variant:

```
np.unique(MyArray(), "obviously bad")
```

is OK:

```
(<__main__.MyArray object at 0x7f6bf5423ef0>, <function unique at 0x7f6bb8913b70>, (<class '__main__.MyArray'>,), (<__main__.MyArray object at 0x7f6bf5423ef0>, 'obviously bad'), {})
```

So it doesn't do typechecking.

I was also curious if Numpy checked argument validity in order. Here is another example:

```
np.compress("nyehnyeh", MyArray())
```

This dispatches to `__array_function__`. This makes efficient C++ implementation more difficult, as it implies that we have to do type checking on ALL tensor arguments, but defer errors, until we have reached the end and concluded that there are no overloaded types. But it does seem doable.

IDK about type-aware proxies, I agree it seems pretty heavy weight.

cc @rgommers

**Comment by hameerabbasi** [comment]
The way NumPy works is they have a "dispatcher" that extracts relevant arguments. The following steps are followed:

1. A list of types is created, including `ndarray` itself if applicable. 
2. The arguments are checked for `getattr(type(obj), "__array_function__") is not ndarray.__array_function__` in subclass-before-superclass order.
3. `__array_function__` is called exactly once per type (if any match the condition).
4. The first one to return anything but `NotImplemented` wins.

This has the benefit of separating things into a clean dispatching layer and a execution layer for NumPy. The downside, as you mention, is performance.

**Comment by ezyang** [comment]
Downgrading priority because torchdynamo nopython=True will subsume the tracing mechanism here

**Comment by ezyang** [comment]
This might still be useful for other torch function users though

**Comment by ezyang** [comment]
If you need a workaround for this issue, https://github.com/pytorch/pytorch/issues/91293#issuecomment-1404985927 is a recipe
