### ISSUE TITLE
torch.fx doesn't handle `torch.empty` appropriately.

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#53935]
## 🐛 Bug

torch.fx doesn't handle `torch.empty` appropriately.

## To Reproduce

```
import torch
from torch.fx import symbolic_trace, replace_pattern

def pattern(inp):
    return inp

def replacement(inp):
    t = torch.empty(10)
    return t + inp

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, inp):
        return inp


if __name__ == "__main__":

    traced_model = symbolic_trace(MyModule())
    print ('Before Replacement: {}'.format(traced_model.code))

    replace_pattern(traced_model, pattern, replacement)

    traced_model.recompile()

    print ('After Replacement: {}'.format(traced_model.code))

    traced_model(torch.rand(10))
```

Output is:

```
Before Replacement: 
def forward(self, inp):
    return inp
    
After Replacement: 
def forward(self, inp):
    _tensor_constant0 = self._tensor_constant0
    add = _tensor_constant0.add(inp);  _tensor_constant0 = inp = None
    return add
    
Traceback (most recent call last):
  File "/tmp/test.py", line 30, in <module>
    traced_model(torch.rand(10))
  File "/data/users/pritam/pytorch/torch/fx/graph_module.py", line 506, in wrapped_call
    raise e.with_traceback(None)
```

## Expected behavior

Method like `torch.empty` should be supported in replacement patterns for torch.fx

**Comment by pritamdamania87** [comment]
cc @ansley @jamesr66a
