### ISSUE TITLE
Is pytorch 1.8.0 incompatible with cuda 11.2 or what is the reason for this error?

### ISSUE THREAD

**Issue by tueboesen** [pytorch/pytorch#53957]
I have spent all day trying to upgrade cuda to 11.2 and get it working with pytorch. At the moment I believe I should have a fully working version of Cuda 11.2, yet I still get the following error when I try to run my pytorch code, which normally works without issues.

```
Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/tue/PycharmProjects/Pfold/run_1d_supervised.py", line 112, in <module>
    losses = main()
  File "/home/tue/PycharmProjects/Pfold/supervised/main.py", line 73, in main
    net = train(net, optimizer, dl_train, loss_fnc, dl_test=dl_test, scheduler=lr_scheduler,ite=ite_start, loss_reg_fnc=loss_reg_fnc, loss_reg_min_sep_fnc=loss_reg_min_sep_fnc)
  File "/home/tue/PycharmProjects/Pfold/supervised/optimization.py", line 75, in train
    dists_pred, coords_pred = net(features,mask)
  File "/home/tue/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tue/PycharmProjects/Pfold/supervised/network_vnet.py", line 508, in forward
    dists += (tr2DistSmall(x[:,i*3:(i+1)*3,:]),)
  File "/home/tue/PycharmProjects/Pfold/supervised/network_transformer.py", line 155, in tr2DistSmall
    D = torch.sum(Z**2, dim=1).unsqueeze(1) + torch.sum(Z**2, dim=1).unsqueeze(2) - 2*Z.transpose(1,2) @ Z
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
python-BaseException
Backend TkAgg is interactive backend. Turning interactive mode on.

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

```

I have checked that cuda/cudnn seems to work, at least I was able to compile and run a hello_world script with nvcc. Additional information:

```
tue@tue-laptop:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

```
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
import torch
torch.version.cuda
'11.1'
torch.version
<module 'torch.version' from '/home/tue/.local/lib/python3.8/site-packages/torch/version.py'>
torch.version.__version__
'1.8.0+cu111'
```

Searching on the error pytorch is giving, hasn't really lead me to any understanding of what the problem could be, so I'm hoping for some insight here and perhaps a solution?

**Comment by h6197627** [comment]
As far as I understand it should be compatible but not recommended due to some performance issues: https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998
Unfortunately there is no separate issue to track the current status of CUDA 11.2 support. After 11.2 CUDA was downgraded to 11.1 in PyTorch there were 2 CUDA updates (11.2 update 1 and 11.2 update 2). So, I am also interested, maybe performance issues are already resolved with the latest CUDA release?

**Comment by ngimel** [comment]
cc @ptrblck

**Comment by ptrblck** [comment]
@tueboesen 
Based on the output of `torch.__version__` and `torch.version.cuda` it seems that you are using the `1.8.0+CUDA11.1` pip wheels.
If that's the case, your local CUDA toolkit won't be used (unless you build PyTorch from source or a custom CUDA extension).

Did you upgrade your drivers recently and are able to use any CUDA operations in PyTorch?
E.g. does this create a valid CUDA tensor:
```python
import torch
print(torch.randn(1).cuda())
```

Also, for the cublas issue: could you post an executable code snippet and fill out your env setup via:
```python
python -m torch.utils.collect_env
```

@h6197627 No, the performance issues were unfortunately not resolved in CUDA11.2U2.

**Comment by tueboesen** [comment]
> @tueboesen
> Based on the output of `torch.__version__` and `torch.version.cuda` it seems that you are using the `1.8.0+CUDA11.1` pip wheels.
> If that's the case, your local CUDA toolkit won't be used (unless you build PyTorch from source or a custom CUDA extension).
> 
> Did you upgrade your drivers recently and are able to use any CUDA operations in PyTorch?

I actually deleted all drivers and anything related to CUDA or nvidia, and reinstalled it all (Nvidia, cuda, cudnn), trying to get pytorch-geometric to work, however, upon reinstalling/upgrading cuda I found that I was getting the cublas error. 

> E.g. does this create a valid CUDA tensor:
> 
> ```python
> import torch
> print(torch.randn(1).cuda())
> ```

This runs without any problems

> 
> Also, for the cublas issue: could you post an executable code snippet and fill out your env setup via:
> 
> ```python
> python -m torch.utils.collect_env
> ```


I tried to create a small code snippet containing just the part it was crashing in, but fortunately/unfortunately once isolated it no longer crashes. The section that fails is the following small function:

```
def tr2DistSmall(Y):
    k = Y.shape[1]
    Z = Y - torch.mean(Y, dim=2, keepdim=True)
    D = torch.sum(Z**2, dim=1).unsqueeze(1) + torch.sum(Z**2, dim=1).unsqueeze(2) - 2*Z.transpose(1,2) @ Z
    D = 3*D/k
    D[...,torch.arange(D.shape[-1]),torch.arange(D.shape[-1])] = 0
    D = torch.relu(D)
    D = torch.sqrt(D)
    return D
```
which fails on the third line (D = torch.sum...)
The interesting thing about the failure is that it fails on first pass, however once it has failed, I can manually run the code without any problems as many times as I want. 
If this is something that has any interest I can give a github clone link, but it doesn't look like I can produce a small and clean example of the problem unfortunately. 
 

```
(venv) tue@tue-laptop:~/PycharmProjects/Pfold$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Linux Mint 20.1 (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0+cu111
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.6.3
[pip3] torch-scatter==2.0.6
[pip3] torch-sparse==0.6.9
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

```

**Comment by ptrblck** [comment]
> I tried to create a small code snippet containing just the part it was crashing in, but fortunately/unfortunately once isolated it no longer crashes. The section that fails is the following small function:

If I understand it correctly, the stack trace points to the mentioned line of code running your entire script, but this minimal code snippet works fine in isolation?
If so, could you rerun the entire script with `CUDA_LAUNCH_BLOCKING=1 python script.py args` and recheck the stack trace?
Also, could you check the memory usage e.g. via `torch.cuda.memory_summary()` and see, if you were running out of memory when hitting this issue? If that's the case, could you lower the batch size and check, if this code runs fine?

**Comment by tueboesen** [comment]
> > I tried to create a small code snippet containing just the part it was crashing in, but fortunately/unfortunately once isolated it no longer crashes. The section that fails is the following small function:
> 
> If I understand it correctly, the stack trace points to the mentioned line of code running your entire script, but this minimal code snippet works fine in isolation?

Yes exactly

> If so, could you rerun the entire script with `CUDA_LAUNCH_BLOCKING=1 python script.py args` and recheck the stack trace?

```
(venv) tue@tue-laptop:~/PycharmProjects/Pfold$ CUDA_LAUNCH_BLOCKING=1 python run_1d_supervised.py 
Traceback (most recent call last):
  File "run_1d_supervised.py", line 112, in <module>
    losses = main()
  File "/home/tue/PycharmProjects/Pfold/supervised/main.py", line 73, in main
    net = train(net, optimizer, dl_train, loss_fnc, dl_test=dl_test, scheduler=lr_scheduler,ite=ite_start, loss_reg_fnc=loss_reg_fnc, loss_reg_min_sep_fnc=loss_reg_min_sep_fnc)
  File "/home/tue/PycharmProjects/Pfold/supervised/optimization.py", line 75, in train
    dists_pred, coords_pred = net(features,mask)
  File "/home/tue/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tue/PycharmProjects/Pfold/supervised/network_vnet.py", line 508, in forward
    dists += (tr2DistSmall(x[:,i*3:(i+1)*3,:]),)
  File "/home/tue/PycharmProjects/Pfold/supervised/network_transformer.py", line 155, in tr2DistSmall
    D = torch.sum(Z**2, dim=1).unsqueeze(1) + torch.sum(Z**2, dim=1).unsqueeze(2) - 2*Z.transpose(1,2) @ Z
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
```
So this give exactly the same stacktrace as before from what I can see, one thing worth noting about this is that the error happens in the first forward pass of the model, so before backpropagation is ever used. 

> Also, could you check the memory usage e.g. via `torch.cuda.memory_summary()` and see, if you were running out of memory when hitting this issue? If that's the case, could you lower the batch size and check, if this code runs fine?

The memory shouldn't be a problem, since I have run quite a bit larger models before. But just to check it I stopped the code where it crashes in debugging mode, and then ran the following in the terminal: 
```
tue@tue-laptop:~$ nvidia-smi
Mon Mar 15 20:55:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce MX150       On   | 00000000:01:00.0 Off |                  N/A |
| N/A   68C    P0    N/A /  N/A |   1256MiB /  2002MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1548      G   /usr/lib/xorg/Xorg                310MiB |
|    0   N/A  N/A     14556      G   cinnamon                           85MiB |
|    0   N/A  N/A     14884      G   ...dates/1.6.6/proton-bridge       10MiB |
|    0   N/A  N/A     20565      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A   2253495      C   ...cts/Pfold/venv/bin/python      845MiB |
+-----------------------------------------------------------------------------+
```
So there is still plenty of memory available as far as I can see.

**Comment by ptrblck** [comment]
Could you nevertheless check for OOMs? The `memory_summary` call would give you the number of encountered OOMs.
In your previous post you've mentioned that you were able to continue running the script even after this error was raised, so you might also be able to check for these OOMs. Since your GPU has only 2GB it's not unlikely to run out of memory and `nvidia-smi` might report the memory alllocation without the cache after PyTorch was already failing.

**Comment by tueboesen** [comment]
> Could you nevertheless check for OOMs? The `memory_summary` call would give you the number of encountered OOMs.
> In your previous post you've mentioned that you were able to continue running the script even after this error was raised, so you might also be able to check for these OOMs. Since your GPU has only 2GB it's not unlikely to run out of memory and `nvidia-smi` might report the memory alllocation without the cache after PyTorch was already failing.

I wasn't aware of that, cool.

I ran the code with the memory_summary() printed just before it crashes, and then I manually triggered memory_summary() immediately after again.
```

|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  115060 KB |  116280 KB |  303836 KB |  188776 KB |
|       from large pool |  111550 KB |  113075 KB |  300010 KB |  188460 KB |
|       from small pool |    3510 KB |    3511 KB |    3826 KB |     316 KB |
|---------------------------------------------------------------------------|
| Active memory         |  115060 KB |  116280 KB |  303836 KB |  188776 KB |
|       from large pool |  111550 KB |  113075 KB |  300010 KB |  188460 KB |
|       from small pool |    3510 KB |    3511 KB |    3826 KB |     316 KB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |  126976 KB |  126976 KB |  126976 KB |       0 B  |
|       from large pool |  122880 KB |  122880 KB |  122880 KB |       0 B  |
|       from small pool |    4096 KB |    4096 KB |    4096 KB |       0 B  |
|---------------------------------------------------------------------------|
| Non-releasable memory |   11915 KB |   26811 KB |  302138 KB |  290223 KB |
|       from large pool |   11330 KB |   25190 KB |  297965 KB |  286635 KB |
|       from small pool |     585 KB |    2038 KB |    4173 KB |    3588 KB |
|---------------------------------------------------------------------------|
| Allocations           |      95    |      96    |     235    |     140    |
|       from large pool |      54    |      55    |     153    |      99    |
|       from small pool |      41    |      42    |      82    |      41    |
|---------------------------------------------------------------------------|
| Active allocs         |      95    |      96    |     235    |     140    |
|       from large pool |      54    |      55    |     153    |      99    |
|       from small pool |      41    |      42    |      82    |      41    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       8    |       8    |       8    |       0    |
|       from large pool |       6    |       6    |       6    |       0    |
|       from small pool |       2    |       2    |       2    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       6    |       9    |     121    |     115    |
|       from large pool |       2    |       5    |      94    |      92    |
|       from small pool |       4    |       5    |      27    |      23    |
|===========================================================================|
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/tue/PycharmProjects/Pfold/run_1d_supervised.py", line 112, in <module>
    losses = main()
  File "/home/tue/PycharmProjects/Pfold/supervised/main.py", line 73, in main
    net = train(net, optimizer, dl_train, loss_fnc, dl_test=dl_test, scheduler=lr_scheduler,ite=ite_start, loss_reg_fnc=loss_reg_fnc, loss_reg_min_sep_fnc=loss_reg_min_sep_fnc)
  File "/home/tue/PycharmProjects/Pfold/supervised/optimization.py", line 75, in train
    dists_pred, coords_pred = net(features,mask)
  File "/home/tue/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tue/PycharmProjects/Pfold/supervised/network_vnet.py", line 508, in forward
    dists += (tr2DistSmall(x[:,i*3:(i+1)*3,:]),)
  File "/home/tue/PycharmProjects/Pfold/supervised/network_transformer.py", line 156, in tr2DistSmall
    D = torch.sum(Z**2, dim=1).unsqueeze(1) + torch.sum(Z**2, dim=1).unsqueeze(2) - 2*Z.transpose(1,2) @ Z
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
python-BaseException
print(torch.cuda.memory_summary())
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  115060 KB |  152499 KB |  341686 KB |  226626 KB |
|       from large pool |  111550 KB |  148760 KB |  337220 KB |  225670 KB |
|       from small pool |    3510 KB |    3739 KB |    4466 KB |     956 KB |
|---------------------------------------------------------------------------|
| Active memory         |  115060 KB |  152499 KB |  341686 KB |  226626 KB |
|       from large pool |  111550 KB |  148760 KB |  337220 KB |  225670 KB |
|       from small pool |    3510 KB |    3739 KB |    4466 KB |     956 KB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |  167936 KB |  167936 KB |  167936 KB |       0 B  |
|       from large pool |  163840 KB |  163840 KB |  163840 KB |       0 B  |
|       from small pool |    4096 KB |    4096 KB |    4096 KB |       0 B  |
|---------------------------------------------------------------------------|
| Non-releasable memory |   11915 KB |   26811 KB |  306528 KB |  294613 KB |
|       from large pool |   11330 KB |   25190 KB |  301715 KB |  290385 KB |
|       from small pool |     585 KB |    2038 KB |    4813 KB |    4228 KB |
|---------------------------------------------------------------------------|
| Allocations           |      95    |     114    |     447    |     352    |
|       from large pool |      54    |      56    |     155    |     101    |
|       from small pool |      41    |      59    |     292    |     251    |
|---------------------------------------------------------------------------|
| Active allocs         |      95    |     114    |     447    |     352    |
|       from large pool |      54    |      56    |     155    |     101    |
|       from small pool |      41    |      59    |     292    |     251    |
|---------------------------------------------------------------------------|
| GPU reserved segments |      10    |      10    |      10    |       0    |
|       from large pool |       8    |       8    |       8    |       0    |
|       from small pool |       2    |       2    |       2    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       6    |      12    |     242    |     236    |
|       from large pool |       2    |       5    |      96    |      94    |
|       from small pool |       4    |       9    |     146    |     142    |
|===========================================================================|

```

Everything looks good as far as I can see?

**Comment by cbasavaraj** [comment]
Hi,
I upgraded to PyTorch 1.8.0 only today and am getting the same error on a call of the function `torch.bmm`. Didn't have any issues with the nightly release I was using previously. And plenty of unused GPU memory. 
I had the error with CUDA 11.1, so tried 11.2, but same error here as well.

**Comment by enhuiz** [comment]
Similar issue here.  After upgrading to 1.8.0 and cuda 11.1. The problem occurs occasionally when executing the following line of code (which calls affine_grid):

```
grid = F.affine_grid(θ, x.shape, align_corners=True)
.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/functional.py", line 3930, in affine_grid
    return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
```

My env:

```
Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: 
GPU 0: Tesla M60
GPU 1: Tesla M60
GPU 2: GeForce RTX 2070

Nvidia driver version: 455.23.05
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-ranger==0.1.1
[pip3] reformer-pytorch==1.2.4
[pip3] siren-pytorch==0.0.9
[pip3] torch==1.8.0+cu111
[pip3] torch-optimizer==0.1.0
[pip3] torch-receptive-field==0.0.1
[pip3] torch-stoi==0.1.2
[pip3] torchaudio==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect
```
