### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_roberta_128_5_1'

### ISSUE THREAD

**Issue by vijumane** [pytorch/pytorch#53970]
To Reproduce

follow installation steps as here https://simpletransformers.ai/docs/installation/

then run following python code

category_model = ClassificationModel('roberta', f"C:\Vijay\CaseClassification\Category", num_labels=5, use_cuda=False, args=f"C:\Vijay\CaseClassification\Category\model_args.json")
category_predictions, category_raw_outputs = category_model.predict(cleaned_text_list)
Expected behavior

A clear and concise description of what you expected to happen: Was not expecting this error

Screenshots
(st) C:\Users\Q15166\Anaconda3\condabin>python.exe C:\Vijay\src\PythonScript\predict_emails.py "some test text"
Traceback (most recent call last):
File "C:\Vijay\src\PythonScript\predict_emails.py", line 147, in
print(get_prediction(sys.argv[1]))
File "C:\Vijay\src\PythonScript\predict_emails.py", line 137, in get_prediction
category_predictions, category_raw_outputs = category_model.predict(cleaned_text_list)
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_model.py", line 1441, in predict
eval_dataset = self.load_and_cache_examples(
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_model.py", line 1284, in load_and_cache_examples
dataset = ClassificationDataset(
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_utils.py", line 215, in init
self.examples, self.labels = build_classification_dataset(
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_utils.py", line 208, in build_classification_dataset
torch.save(data, cached_features_file)
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 369, in save
with _open_file_like(f, 'wb') as opened_file:
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
return _open_file(name_or_buffer, mode)
File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 211, in init
super(_open_file, self).init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_roberta_128_5_1'

Desktop (please complete the following information):

OS: Windows 10
Additional context

**Comment by ngimel** [comment]
Looks like this error is specific to the package you are trying to use, simpletransformers. The error message complains about missing file. It doesn't look like pytorch problem, reopen if you think it is.

**Comment by vijumane** [comment]
issue was of relative path of "cache_dir" in model_args.json file, which was set to "cache_dir": "cache_dir/",

I changed it to absolute path on windows
