### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED in pytorch

### ISSUE THREAD

**Issue by HBolandi** [pytorch/pytorch#54047]
I am running CNN algorithm using PyTorch lightning on my new machine with 3 Nvidia GPUs and getting the error below:

`RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

```
File "code.py", line 342, in <module>
    trainer.fit(model)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 514, in fit
    self.dispatch()

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 554, in dispatch
    self.accelerator.start_training(self)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 615, in run_train
    self.run_sanity_check(self.lightning_module)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 733, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 164, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 178, in validation_step
    return self.training_type_plugin.validation_step(*args)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 290, in validation_step
    return self.model(*args, **kwargs)

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 63, in forward
    output = self.module.validation_step(*inputs, **kwargs)

  File code.py", line 314, in validation_step
    pred = self.forward(x)

  File code.py", line 259, in forward
    x = self.conv0(x)          #([12, 600, 600])

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)

  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

```
 - PyTorch Version : 1.8
 - OS: ubuntu
 - installed PyTorch : pip
 - Python version: 3.8
 - CUDA/cuDNN version: 11.2 / 7605
 - GPU models and configuration: NVIDIA RTX 8000
 - Driver version : 460.32.03
```
The code is running without any issue on another machine with driver version 450.51.06 and Cuda version 11. You can see the NVIDIA GPUs configuration of the new machine above. I checked different comments on other questions same to this issue and none of them resolved my issue.

**Comment by ptrblck** [comment]
This is most likely a duplicate of https://github.com/pytorch/pytorch/issues/53336, as you are using a Turing GPU with the `1.8.0` pip wheels. Could you try out the nightly binary and check, if it's working?

**Comment by HBolandi** [comment]
Thanks for your response. I install it with the command below:
"pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html" but still the problem exists.

**Comment by xwang233** [comment]
Thanks for the comments. If you still see the cudnn error message with the latest nightly binary. Can you run your script with `CUDA_LAUNCH_BLOCKING=1 TORCH_SHOW_CPP_STACKTRACES=1 python script.py`  and post the entire error message here?

**Comment by xsacha** [comment]
Only happening on one of my machines. Latest nightly as of today.
CUDA 11.3, Driver 470, Card: P620

```Traceback (most recent call last):
  File "detect_quantized.py", line 375, in <module>
    net = torch.jit.trace(net, inp, check_trace=False)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/d/dev/cavaface.pytorch/backbone/resnet_irse.py", line 106, in forward
    x = self.input_layer(x)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
Exception raised from createCuDNNHandle at ../aten/src/ATen/cudnn/Handle.cpp:9 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f580e70f8d2 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x26ed7ca (0x7f58626fd7ca in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #2: at::native::getCudnnHandle() + 0xe38 (0x7f58626fece8 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: <unknown function> + 0x268abe7 (0x7f586269abe7 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #4: <unknown function> + 0x268afe4 (0x7f586269afe4 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #5: <unknown function> + 0x26846fc (0x7f58626946fc in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #6: at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) + 0x95 (0x7f5862694c15 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #7: <unknown function> + 0x11d6866 (0x7f580fb2f866 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #8: <unknown function> + 0x11d68df (0x7f580fb2f8df in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #9: at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) + 0x23d (0x7f5849cd144d in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::native::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) + 0xc80 (0x7f584946d430 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x1e23a5a (0x7f5849ef4a5a in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #12: at::_ops::_convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) + 0x1f0 (0x7f58499de490 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x2c2c9d7 (0x7f584acfd9d7 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) + 0x277 (0x7f5849a08377 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: at::native::convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) + 0xfb (0x7f584946635b in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x1e237fa (0x7f5849ef47fa in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) + 0x176 (0x7f58499df106 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x294d038 (0x7f584aa1e038 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: <unknown function> + 0x294db86 (0x7f584aa1eb86 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #20: at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) + 0x176 (0x7f58499df106 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #21: <unknown function> + 0x2c0ba79 (0x7f584acdca79 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #22: at::_ops::convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) + 0x251 (0x7f5849a07001 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #23: at::native::conv2d(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) + 0x159 (0x7f584946a0f9 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #24: <unknown function> + 0x1eb3752 (0x7f5849f84752 in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #25: at::_ops::conv2d::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) + 0x13b (0x7f5849d69e3b in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #26: <unknown function> + 0x2e810de (0x7f584af520de in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #27: at::_ops::conv2d::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) + 0x20e (0x7f5849d8aaee in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #28: <unknown function> + 0x36711c (0x7f58c606711c in /home/sacha/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #32: python3() [0x50a4ce]
frame #35: python3() [0x50a5cc]
frame #40: python3() [0x50a5cc]
frame #45: python3() [0x59cc9d]
frame #49: python3() [0x50a5cc]
frame #54: python3() [0x50a5cc]
frame #59: python3() [0x59cc9d]
frame #63: python3() [0x50a5cc]
```
