### ISSUE TITLE
Dispatch table for linalg_norm is fishy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54082]
Current native_functions.yaml entry is:

```
- func: linalg_norm(Tensor self, Scalar? ord=None, int[1]? dim=None, bool keepdim=False, *, ScalarType? dtype=None) -> Tensor
  python_module: linalg
  variants: function

- func: linalg_norm.ord_str(Tensor self, str ord, int[1]? dim=None, bool keepdim=False, *, ScalarType? dtype=None) -> Tensor
  python_module: linalg
  variants: function

- func: linalg_norm.out(Tensor self, Scalar? ord=None, int[1]? dim=None, bool keepdim=False, *, ScalarType? dtype=None, Tensor(a!) out) -> Tensor(a!)
  use_c10_dispatcher: hacky_wrapper_for_legacy_signatures
  python_module: linalg
  variants: function

- func: linalg_norm.ord_str_out(Tensor self, str ord, int[1]? dim=None, bool keepdim=False, *, ScalarType? dtype=None, Tensor(a!) out) -> Tensor(a!)
  use_c10_dispatcher: hacky_wrapper_for_legacy_signatures
  python_module: linalg
  variants: function
```

As there is no dispatch table, all of the linalg_norm entries are registered as Math, implying that they work universally. But this doesn't seem to be true:

```
======================================================================
ERROR: test_norm_matrix_meta_float32 (__main__.TestLinalgMETA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_utils.py", line 955, in wrapper
    method(*args, **kwargs)
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test/test_linalg.py", line 1289, in test_norm_matrix
    run_test_case(input, ord, dim, keepdim)
  File "test/test_linalg.py", line 1259, in run_test_case
    result = torch.linalg.norm(input, ord, dim, keepdim)
RuntimeError: matrix norm only supports CPU AND CUDA device type, got: meta
```

I don't mind diagnosing this particular problem but it seems like we still have some sort of education problem about how to properly setup dispatch tables for new operators.

cc @ailzhang @kurtamohler @mruberry

**Comment by ezyang** [comment]
I see

```
    // 'ord' is int or None
    std::vector<int64_t> dim_ = opt_dim.has_value() ? opt_dim.value().vec() : make_dim_list(ndim);
    if (!opt_num_ord.has_value() || dim_.size() == 1) {
      _linalg_norm_vector_out(result, self, opt_num_ord, dim_, keepdim, opt_dtype);
    } else if (dim_.size() == 2) {
      _linalg_norm_matrix_out(result, self, opt_num_ord.value(), dim_, keepdim, opt_dtype);
    } else {
      TORCH_CHECK(false, "'dim' must specify 1 or 2 dimensions when order is numerical and input is "
        "not 1-D or 2-D");
```

Kind of getting the vibe that autograd doesn't work in this case.....

**Comment by ezyang** [comment]
@ngimel tells me that linalg_norm is gonna die in a fire, so I'm just going to skip these tests.

**Comment by mruberry** [comment]
Skipping the tests sounds good but I don't think torch.linalg.norm() will "die in a fire." It will be revised before the 1.9 release, however.

It'd be nice to either clarify the three backend keys or simplify them down to two (math and cpu/cuda). Also, maybe there's some way we can test that the dispatch type is correct? For ops with multiple dispatch types that might be too tricky, but ops with a single dispatch type could probably have that metadata exposed to the test suite in an OpInfo.

**Comment by ezyang** [comment]
> it'd be nice if we could test that that the op is using the appropriate dispatch key

Yeah, I was thinking about how to go about doing this. The way I triggered this in the meta tensors bringup is that I have a device type for which most operations are not implemented, and then run the test suite far enough so that I can call the not implemented operation on the tensor (and then test if I get NotImplementedError or not). Obviously, as meta tensors get more and more operations implemented on it, this will become less and less of a good way for testing this, but maybe we could define some sort of permanent "not implemented" device that would serve this purpose. Unfortunately, you *do* have to implement enough to actually get the test suite going in the first place (or maybe we could just define new tests specifically for this case, i.e., literally just get all the arguments in order, then call the not implemented operation)

> it might be nice to update the names of "Math" and "DefaultBackend" to "Composite" and "CompositeNoAutograd," respectively. (Or "Math" and "MathNoAutograd," whatever.)

Let's workshop this in composability

**Comment by zou3519** [comment]
Running that test now gives the following: https://gist.github.com/zou3519/50c248ac3ab81834effa674db4e443ad , which may or may not be the same problem in a different form. Although linalg_norm is registered as a "Math" (I'm not sure what we renamed that to) kernel, it ends up calling `abs_out` which is [only registered for CPU and CUDA](https://github.com/pytorch/pytorch/blob/179b3ab88c3e71e01980585530fa8d71d461394a/aten/src/ATen/native/native_functions.yaml#L219-L222)
