### ISSUE TITLE
DISABLED test_destroy_group (__main__.TestMPIWithFork) 

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#54097]
https://app.circleci.com/pipelines/github/pytorch/pytorch/285682/workflows/4c9d5f42-3c4a-40dd-bf23-3bd944700b26/jobs/11568350

```
Mar 16 01:30:00   test_destroy_group (__main__.TestMPIWithFork) ... [a34ceb6576ba:611] *** An error occurred in MPI_Comm_create
Mar 16 01:30:00 [a34ceb6576ba:611] *** reported by process [3044540417,2]
Mar 16 01:30:00 [a34ceb6576ba:611] *** on communicator MPI_COMM_WORLD
Mar 16 01:30:00 [a34ceb6576ba:611] *** MPI_ERR_IN_STATUS: error code in status
Mar 16 01:30:00 [a34ceb6576ba:611] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
Mar 16 01:30:00 [a34ceb6576ba:611] ***    and potentially your MPI job)
Mar 16 01:30:00 Traceback (most recent call last):
Mar 16 01:30:00   File "test/run_test.py", line 1075, in <module>
Mar 16 01:30:00     main()
Mar 16 01:30:00   File "test/run_test.py", line 1054, in main
Mar 16 01:30:00     raise RuntimeError(err_message)
Mar 16 01:30:00 RuntimeError: distributed/test_distributed_fork failed!
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by mrshenli** [comment]
the fix #55921 is landed, closing this issue.
