### ISSUE TITLE
[Torchscript] Error detected in torch::jit::(anonymous namespace)::DifferentiableGraphBackward on custom RNN model

### ISSUE THREAD

**Issue by zheninjas** [pytorch/pytorch#54140]
## 🐛 Bug

`Error detected in torch::jit::(anonymous namespace)::DifferentiableGraphBackward` when using `chunk` on forward but no error when using `split`

## To Reproduce

Run this code snippet:
```
import torch
from torch import jit
from torch.nn import Parameter

class CustomRNNCell(jit.ScriptModule):
    def __init__(self, input_size, hidden_size):
        super(CustomRNNCell, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.weight_ih = Parameter(torch.randn(3 * hidden_size, input_size))
        self.weight_hh = Parameter(torch.randn(3 * hidden_size, hidden_size))
        self.bias_ih = Parameter(torch.randn(3 * hidden_size))
        self.bias_hh = Parameter(torch.randn(3 * hidden_size))

    @jit.script_method
    def forward(self, input, state):
        # type: (Tensor, Tuple[Tensor, Tensor]) -> Tuple[Tensor, Tuple[Tensor, Tensor]]
        hx, cx = state
        gates = (torch.mm(input, self.weight_ih.t()) + self.bias_ih +
                 torch.mm(hx, self.weight_hh.t()) + self.bias_hh)
        
        # Cause error
        m, o, i = gates.chunk(3, 1)

        # # No Error
        # m, o, i = gates.split(self.hidden_size, 1)

        m = torch.sigmoid(m)
        o = torch.tanh(o)
        i = torch.tanh(i)        

        cy = (1 - m) * cx + (m * i)
        hy = (1 - o) * i + (o * cx)

        return hy, (hy, cy)

torch.autograd.set_detect_anomaly(mode=True)

cell = CustomRNNCell(
    input_size=1280,
    hidden_size=256
)

for i in range(20):
    x = torch.randn(8, 1280)
    state = (
        torch.zeros(8, 256),
        torch.zeros(8, 256)
    )

    out, _ = cell(x, state)
    
    print(i)
    out.mean().backward()
```

Full error message
```
0
1
/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py:147: UserWarning: Error detected in torch::jit::(anonymous namespace)::DifferentiableGraphBackward. Traceback of forward call that caused the error:
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 451, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 434, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-261e1fca8504>", line 51, in <module>
    out, _ = cell(x, state)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
 (Triggered internally at  /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-261e1fca8504> in <module>()
     52 
     53     print(i)
---> 54     out.mean().backward()

1 frames
/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    145     Variable._execution_engine.run_backward(
    146         tensors, grad_tensors_, retain_graph, create_graph, inputs,
--> 147         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    148 
    149 

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: tensor does not have a device
```

## Expected behavior

No error happen

## Environment
```
PyTorch version: 1.8.0+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0+cu101
[pip3] torchinfo==0.0.8
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.9.0
[pip3] torchvision==0.9.0+cu101
[pip3] torchviz==0.0.1
[conda] Could not collect
```

## Additional context

[Related discussion](https://discuss.pytorch.org/t/error-detected-in-torch-anonymous-namespace-differentiablegraphbackward/114962)

**Comment by t-vi** [comment]
As you note, the this is the backward of chunk, which is cat. Apparently it gets fed an undefined tensor, the ultimate cause seems to be that the `DifferentiableGraph` gets undefined `grad_out` for `(cy, hy)` (because they're not connected) and cannot deal with it. (My guess it is cy and then m having undefined gradient.)
 So either autodiff needs to materialize these or the chunk autodiff backward needs to be prepared that part of its grad_out is undefined and it needs to materialize it.

A clumsy workaround is to add `cy.sum() * 0` to the output you want.

**Comment by zheninjas** [comment]
if `split` is used, there is no error happen. is `split` different with `chunk` when it come to autodiff in jit?

**Comment by t-vi** [comment]
The crucial difference seems to be that using `split` also comes with a `prim::ListUnpack` to map the list to the three variables, which is not put in the differentiable subgraph, instead you get two (one before and one after). But this then seems to trigger the materialization of the required inputs. The `chunk` (with constant number) gets translated to `prim::ConstantChunk` instead and gets assigned directly to the tuple, so you have one large `prim::DifferentiableGraph`.
(run your script with ipython -i or so and then look at `gr = cell.forward.graph_for(x, state)`).

Another (but not crucial as far as I can tell) difference is that split has its autodiff formula defined in symbolic script:

https://github.com/pytorch/pytorch/blob/527c1e0e37b7c65148bcbc390b65e94fb4624a9d/torch/csrc/jit/runtime/symbolic_script.cpp#L534-L541

while `chunk` (with a constant number of chunks) gets translated to `prim::ConstantChunk`, which is handled here directly in autodiff.cpp:

https://github.com/pytorch/pytorch/blob/527c1e0e37b7c65148bcbc390b65e94fb4624a9d/torch/csrc/jit/runtime/autodiff.cpp#L214-L231

This specialization is needed for the fusers (at least historically).

So I guess we need to enhance the gradient of `prim::ConstantChunk` to deal with `None` in `grad_out` (and possibly we should also do this with split, but what do I know).

"normal" autograd does the same in split_backward_with_sizes (called from split_backward for regular split)

https://github.com/pytorch/pytorch/blob/527c1e0e37b7c65148bcbc390b65e94fb4624a9d/torch/csrc/autograd/FunctionsManual.cpp#L977-L987

**Comment by zheninjas** [comment]
Ok, so it's different handling for `split` and `chunk`. Is there some temporary fix for these kind of problem? or i'll just wait to "enhance the gradient of `prim::ConstantChunk` to deal with `None` in `grad_out`" and split directly weight variable on __init__ so it's not use chunk?

I'm not really understand of this implemetation of "A clumsy workaround is to add `cy.sum() * 0` to the output you want"

**Comment by t-vi** [comment]
> I'm not really understand of this implemetation of "A clumsy workaround is to add cy.sum() * 0 to the output you want"

```
out, (_, _cy) = cell(x, state)
out = out + cy.sum() * 0
```

**Comment by zheninjas** [comment]
Oh, ok thanks. should i close this issue or leave it for "Enhance the gradient of prim::ConstantChunk to deal with None in grad_out" part?

**Comment by t-vi** [comment]
Please leave it open. It's a bug and we're grateful for your report with repro. Thanks!

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
