### ISSUE TITLE
Error:code call  .pyd for torch error not found caffe2_detectron_ops_gpu.dll

### ISSUE THREAD

**Issue by botao1995** [pytorch/pytorch#54233]
## ❓ Using Python to compile pytorch. PYD file, using C # or Python to call error.

pytorch 1.5.1 is successful
pytorch >1.5.1 errors

Python.Runtime.PythonException: OSError : [WinError 126] 找不到指定的模块。 Error loading "C:\Anaconda3\envs\mtscript\Lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
['  File "C:\\Anaconda3\\envs\\mtscript\\Lib\\site-packages\\torch\\__init__.py", line 127, in <module>\n    raise err\n']   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at MT.AIBuilder.MainWindow..ctor() in C:\code\pycode\MT.AIBuilder\View\MainWindow.xaml.cs:line 78
['  File "C:\\Anaconda3\\envs\\mtscript\\Lib\\site-packages\\torch\\__init__.py", line 127, in <module>\n    raise err\n']   at Python.Runtime.Runtime.CheckExceptionOccurred()

**Comment by skyline75489** [comment]
You may want to try install vcredist, or other dependencies that are missing.

**Comment by botao1995** [comment]
> You may want to try install vcredist, or other dependencies that are missing.

VCredist is already installed.

**Comment by skyline75489** [comment]
OK, so `caffe2_detectron_ops_gpu.dll` depends on a lot of DLLs for it to work. VCRedist is one of them. It's almost impossible for us to help you with this kind of issue since we do not know the exactly DLLs that's missing from your system. One possible way to find out is using tools like [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon).

**Comment by skyline75489** [comment]
If you're using conda, try this:

```text
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
```

**Comment by malfet** [comment]
@botao1995 can you please confirm whether it happens when you try to `import torch` or caffe2 (caffe2_detectron_gpu should not be loaded only if pytorch interfaces are used)

**Comment by peterjc123** [comment]
caffe2_detectron_ops_gpu.dll depends on VCOMP140.DLL and LIBIOMP5MD.dll, so maybe you forget to install the omp dlls, since you use conda, I suppose `conda install intel-openmp` should be enough.

**Comment by botao1995** [comment]
> @botao1995 can you please confirm whether it happens when you try to `import torch` or caffe2 (caffe2_detectron_gpu should not be loaded only if pytorch interfaces are used)

I have solved the problem

**Comment by botao1995** [comment]
> caffe2_detectron_ops_gpu.dll depends on VCOMP140.DLL, LIBIOMP5MD.dll and the CUDA libs, so maybe you forget to install the omp dlls, since you use conda, I suppose `conda install intel-openmp` should be enough.

I have solved the problem
