### ISSUE TITLE
test_randperm is failing on CPU-only build

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#54282]
## 🐛 Bug

See: https://github.com/pytorch/pytorch/pull/54231, this test is marked as slow test, but:
1. it is actually not slow
2. trying to run it on cpu-only build gives the following failure:

```
Mar 18 03:25:07 ======================================================================
Mar 18 03:25:07 FAIL [0.004s]: test_randperm_meta (__main__.TestRandomTensorCreationMETA)
Mar 18 03:25:07 ----------------------------------------------------------------------
Mar 18 03:25:07 Traceback (most recent call last):
Mar 18 03:25:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 955, in wrapper
Mar 18 03:25:07     method(*args, **kwargs)
Mar 18 03:25:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
Mar 18 03:25:07     result = test_fn(self, *args)
Mar 18 03:25:07   File "test_tensor_creation_ops.py", line 3146, in test_randperm
Mar 18 03:25:07     with torch.random.fork_rng(devices=rng_device):
Mar 18 03:25:07   File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
Mar 18 03:25:07     return next(self.gen)
Mar 18 03:25:07   File "/opt/conda/lib/python3.6/site-packages/torch/random.py", line 118, in fork_rng
Mar 18 03:25:07     gpu_rng_states.append(torch.cuda.get_rng_state(device))
Mar 18 03:25:07   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/random.py", line 22, in get_rng_state
Mar 18 03:25:07     _lazy_init()
Mar 18 03:25:07   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 164, in _lazy_init
Mar 18 03:25:07     raise AssertionError("Torch not compiled with CUDA enabled")
Mar 18 03:25:07 AssertionError: Torch not compiled with CUDA enabled
Mar 18 03:25:07 
Mar 18 03:25:07 ----------------------------------------------------------------------
```

**Comment by mruberry** [comment]
We would accept a PR fixing this.

**Comment by ngimel** [comment]
cc @ezyang for Meta test failure

**Comment by ezyang** [comment]
This is because fork_rng only understands CUDA. CPU seems to manually stubbed in the prologue. Bandaid fix is easy but real fix is to fix the test and/or fork_rng.
