### ISSUE TITLE
Unit testing failures when porting PyTorch wheel

### ISSUE THREAD

**Issue by ydaiming** [pytorch/pytorch#54332]
## 🐛 Bug

I built and installed a PyTorch wheel inside a custom container, and ran the unit test with the `run_test.py` command with a few exclusions. The unit testing completed successful inside this container.

However, when I start a second container (the same container as above), clone the pytorch repo with the same version tag, and run the `run_test.py` command with the same set of exclusions. Some tests started to fail, for example, the `test_linalg` test.

Then, I investigated the unit testing logs, and found out that the `test_linalg` wasn't in the first test suite, but showed up in the second one. I suspect this is due to some environmental settings during the wheel building phase and thus caused the test suites to be different in the two containers. Could you provide some ideas on how to resolve this issue?

## To Reproduce

1.
1.
1.

## Expected behavior

The same set of unit testing should be in the two same containers, regardless of building or not building PyTorch inside it. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
I'm using a CPU image with a locally built wheel.

PyTorch version: N/A
--
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.6 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
CuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] sagemaker-pytorch-training==2.4.0
[pip3] torch==1.8.1
[pip3] torchvision==0.9.0
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] numpy                     1.19.1           py36h30dfecb_0    anaconda
[conda] numpy-base                1.19.1           py36h75fe3a5_0    anaconda
[conda] sagemaker-pytorch-training 2.4.0                    pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchvision               0.9.0                    pypi_0    pypi

**Comment by ydaiming** [comment]
I think if there's way to only run the configuration part of the `setup.py`, this issue would be solved. Is there am available method to try out this idea?

**Comment by ydaiming** [comment]
I just tried to stop `python setup.py install` right after the `-- Configuring done` section of the install on the second container. Then I ran the unit testing again. The issue persists. Is there any way to resolve the different settings of two containers? Re-building the wheel on the second one doesn't look like an options, as it defeats the purpose of using a wheel.

**Comment by ydaiming** [comment]
With a closer look, the first container tried to run:
```
Executing ['mpiexec', '-n', '3', '--noprefix', '--allow-run-as-root', '/opt/conda/bin/python3.6', 'distributed/test_distributed_fork.py']
```
while the second runs
```
Executing ['mpiexec', '-n', '3', '', '', '/opt/conda/bin/python3.6', 'distributed/test_distributed_fork.py'] 
```
Thus led to different results.

I'm trying to provide with all I can find, please let me know if there's something I can do, try, or help.

**Comment by ezyang** [comment]
Is it possible to post the entire Dockerfile that you built the PyTorch wheel with? Are you using our scripts?

**Comment by ydaiming** [comment]
I'm using a public AWS pytorch 1.8.0 CPU DLC, and uninstall pytorch, and build a wheel inside it.
Port this wheel to a new DLC, and unit tests would be different, as I tried to explain above.
The link to [the dockerfile](https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/1.8.0/py3/Dockerfile.cpu), but I think you need to follow readme at root folder to actually build it.

**Comment by ydaiming** [comment]
I'm using a public AWS pytorch 1.8.0 CPU DLC, and uninstall pytorch, and build a wheel inside it.
Port this wheel to a new DLC, and unit tests would be different, as I tried to explain above.
The link to [the dockerfile](https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/1.8.0/py3/Dockerfile.cpu), but I think you need to follow readme at root folder to actually build it.

**Comment by ydaiming** [comment]
@ezyang Is there any update or help needed from my side?

**Comment by ezyang** [comment]
What's the exact set of commands you're using to build the wheel, and then transfer it to the other docker image? (e.g., a cli session would probably be most illustrative)

**Comment by ezyang** [comment]
I see in the docker file there are a bunch of ENV declarations. What if you manually replicate these into your second shell session?

**Comment by ydaiming** [comment]
@ezyang I've been trying to dig deeper into this issue. Now I think it's not about porting wheels, it's about installing pytorch directly from code, or by a wheel. 

If I install the pytorch from code directly, the number of unit tests is greatly reduced, while installing from the wheel, the number of unit tests is huge. 

> What's the exact set of commands you're using to build the wheel, and then transfer it to the other docker image? (e.g., a cli session would probably be most illustrative)

```
pip uninstall torch -y
# This is how I build the wheel
python setup.py clean
python setup.py bdist_wheel --universal --plat-name=manylinux1_x86_64
pip install --no-cache-dir -U dist/torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl
# This is how I install the pytorch directly
python setup.py install
```

> I see in the docker file there are a bunch of ENV declarations. What if you manually replicate these into your second shell session?

I think this is unrelated now, because it's not about the second container anymore. Just to answer, I'm using the same container image for the two containers, so the environment variables are the same.

**Comment by malfet** [comment]
@ydaiming can you share output of `python3 -c "import torch;print(torch.__config__.show())"`? I suspect when you use PyTorch build from source, you skip some of the additional dependencies, that greatly reduces total number of test being available to run.

**Comment by ydaiming** [comment]
@malfet
This is the config if I build the pytorch 1.8.1 directly from source
```
root@bb1811ef501f:/pytorch/test# python3 -c "import torch;print(torch.__config__.show())" 2>&1 | tee configs.log
PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 
```

This is the config if I build a wheel first and install the wheel:
```
root@5a61cddac83f:/pytorch/test# python3 -c "import torch;print(torch.__config__.show())" 2>&1 | tee configs.log
PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 
```
Both are installed/built from a new container. Looks like the only differences are in the `CXX_FLAGS`.

**Comment by ydaiming** [comment]
Below are the commands I used to build/install pytorch 1.8.1 + torchvision 0.8.1 for cpu:
```
# set up
export PYTORCH_BUILD_VERSION=1.8.1
export PYTORCH_BUILD_NUMBER=1

pip uninstall torch torchvision -y
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses -y
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git checkout v1.8.1 -b v1.8.1
git submodule sync
git submodule update --init --recursive
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

# method 1 in container 1
python setup.py clean
python setup.py install

# method 2 in container 2
python setup.py clean
python setup.py bdist_wheel --universal --plat-name=manylinux1_x86_64
pip install -U -no-cache dist/torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl 

# unit test
cd test
python3 -c "import torch;print(torch.__config__.show())" 2>&1 | tee configs.log # results pasted above

pip install -U --no-cache https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp36-cp36m-linux_x86_64.whl
pip install hypothesis

python run_test.py
```

Though not expected, building from source (method 1) failed the `test_datapipe` while installing the wheel (method 2) fails at the `distributed/test_distributed_fork` with the info I pasted in the bug description:
```
Executing ['mpiexec', '-n', '3', '', '', '/opt/conda/bin/python', 'distributed/test_distributed_fork.py'] ... [2021-05-21 18:09:50.930552]
--------------------------------------------------------------------------
mpiexec has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpiexec as a non-root user.

You can override this protection by adding the --allow-run-as-root option
to the cmd line or by setting two environment variables in the following way:
the variable OMPI_ALLOW_RUN_AS_ROOT=1 to indicate the desire to override this
protection, and OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 to confirm the choice and
add one more layer of certainty that you want to do so.
We reiterate our advice against doing so - please proceed at your own risk.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "run_test.py", line 926, in <module>
    main()
  File "run_test.py", line 905, in main
    raise RuntimeError(err_message)
RuntimeError: distributed/test_distributed_fork failed!
```

**Comment by ydaiming** [comment]
@malfet Do you recommend opening another issue for the failing unit test out of box for PT 1.8.1, or we can stay at this one? 

Regarding the current issue, I'm not sure why the `distributed/test_distributed_fork` doesn't get the proper option or maybe the test shouldn't be run at all? If this issue is solved, we can probably have a better idea on other tests.

**Comment by ydaiming** [comment]
Could you let me know what I can do to progress this further?

**Comment by ydaiming** [comment]
A gentle ping for any possible updates. Thanks.

**Comment by ezyang** [comment]
@ydaiming Sorry about the delay. I have a suspicion that the difference has to do with what modules Python is picking up (because the test directory lives in the same directory as the torch directory, and this can make a difference in sys.path).

Some questions, because I haven't tried to repro yet:

1. Is `test_linalg` still being omitted from one run but not the other? I checked on a development copy of PyTorch and I see `test_linalg` is still being run, and it is hard for me to see how it could be not run
2. Have you tried doing this exercise on master, or on the upcoming 1.9 release?
3. Re the mpiexec problem, the way we compute the arguments is pretty simple and it's this code in run_test.py
```
                    # test mpiexec for --noprefix option
                    with open(os.devnull, 'w') as devnull:
                        allowrunasroot_opt = '--allow-run-as-root' if subprocess.call(
                            'mpiexec --allow-run-as-root -n 1 bash -c ""', shell=True,
                            stdout=devnull, stderr=subprocess.STDOUT) == 0 else ''
                        noprefix_opt = '--noprefix' if subprocess.call(
                            f'mpiexec {allowrunasroot_opt} -n 1 --noprefix bash -c ""', shell=True,
                            stdout=devnull, stderr=subprocess.STDOUT) == 0 else ''
        
                    mpiexec = ['mpiexec', '-n', '3', noprefix_opt, allowrunasroot_opt]
```
If you could manually add some debug statements here to diagnose what is going on with those subprocess calls, it may be illuminating
4. Can you try moving `test/` to another directory and then doing the same experiment?
5. Can you post the full logs somewhere?

**Comment by ydaiming** [comment]
I would like to do the experiments you suggest. Two quick questions:
1. To get us on the same page, which version of PyTorch do you suggest me to test on now? I was testing on e.g. 1.8.0, 1.8.1. 
2. What's a common way to share the full logs once I have them? 

Then, I can properly 1. debug `mpiexec`, 2. move `test/` around, 3. diagnose other things e.g. `test_linalg`.

**Comment by ezyang** [comment]
1. It's nice to know that the bug in question isn't already fixed on master. So master is best.
2. I just make a github gist and put it there
