### ISSUE TITLE
[JIT] TorchScript does not correctly handle `torch.` namespace functions called with `kwargs`

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#54348]
```
import torch

def foo(x):
    return torch.sigmoid(input=x)

x = torch.randn(3, 4)
print(foo(x))
"""
tensor([[0.3897, 0.3828, 0.1852, 0.8445],
        [0.2609, 0.6442, 0.3572, 0.7560],
        [0.1253, 0.4718, 0.6553, 0.1772]])
"""

scripted = torch.jit.script(foo)
"""
Traceback (most recent call last):
  File "ns.py", line 9, in <module>
    scripted = torch.jit.script(foo)
  File "/data/users/jamesreed/pytorch/torch/jit/_script.py", line 995, in script
    qualified_name, ast, _rcb, get_default_args(obj)
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::sigmoid(Tensor self) -> (Tensor):
  Argument self not provided.
  
  aten::sigmoid.out(Tensor self, *, Tensor(a!) out) -> (Tensor(a!)):
  Argument self not provided.

The original call is:
  File "ns.py", line 4
def foo(x):
    return torch.sigmoid(input=x)
           ~~~~~~~~~~~~~ <--- HERE

"""
```

The PyTorch ops in the `torch.` namespace take the input argument with kwarg name `input`, not `self`

**Comment by SplitInfinity** [comment]
Documentation for `torch.sigmoid`:
```
def sigmoid(input: Tensor, *, out: Optional[Tensor]=None) -> Tensor: ...
```

Schema in `native_functions.yaml`:
```
- func: sigmoid(Tensor self) -> Tensor
```

Torchscript uses the latter, so that's why it doesn't recognize a call of the form `torch.sigmoid(input=...)`.

**Comment by SplitInfinity** [comment]
There is a compatibility layer that allows you to declare certain argument names as aliases

**Comment by SplitInfinity** [comment]
@jamesr66a Is this urgent?

**Comment by eellison** [comment]
I take it back, this hasn't been solved, but this is another example: https://github.com/pytorch/pytorch/issues/33887

**Comment by jamesr66a** [comment]
@SplitInfinity  whether it's urgent depends on which direction we go with https://github.com/pytorch/pytorch/pull/54290. I have a tentative plan with @zdevito that may circumvent this issue. But I still think it would be good to smooth out the Python arg parser differences generally

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
