### ISSUE TITLE
RuntimeError: $ Torch: not enough memory: you tried to allocate 72GB. Buy new RAM!

### ISSUE THREAD

**Issue by ponomarevsy** [pytorch/pytorch#5434]
- OS: 

Red Hat Enterprise Linux Server release 7.2 (Maipo)

- PyTorch version: 

pytorch                   0.3.1           py35_cuda8.0.61_cudnn7.0.5_2    pytorch
torchvision               0.2.0            py35heaa392f_1    pytorch

- How you installed PyTorch (conda, pip, source):

$ module load anaconda3/4.3.1
$ source activate pytorchenv
$ conda install pytorch torchvision -c pytorch

- Python version:

$ python -V
Python 3.5.5

- CUDA/cuDNN version:

cuda8.0.61/cudnn7.0.5_2

- GPU models and configuration:

$ nvidia-smi
Tue Feb 27 10:06:13 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.69                 Driver Version: 384.69                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:04:00.0 Off |                    0 |
| N/A   28C    P8    26W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:05:00.0 Off |                    0 |
| N/A   22C    P8    29W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:84:00.0 Off |                    0 |
| N/A   32C    P8    26W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:85:00.0 Off |                    0 |
| N/A   24C    P8    29W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           On   | 00000000:8A:00.0 Off |                    0 |
| N/A   24C    P8    26W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           On   | 00000000:8B:00.0 Off |                    0 |
| N/A   33C    P8    29W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           On   | 00000000:8E:00.0 Off |                    0 |
| N/A   26C    P8    26W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           On   | 00000000:8F:00.0 Off |                    0 |
| N/A   35C    P8    31W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

- GCC version (if compiling from source):

N/A

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

Training a model with:
```
...
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
...
	valid_loader = DataLoader(dataset=valid_dataset, batch_size=32, shuffle=False, num_workers=12)
	# ====== start trianing =======

	cudnn.benchmark = True
	N_CLASSES = 8
	BATCH_SIZE = 32
```
I've tried batch sizes from 128 to 8, and using GPUs from just one to all 8. GPU node has plenty of RAM (124G):

$ free
              total        used        free      shared  buff/cache   available
Mem:      131930696     6299776   124697204       16968      933716   124718092
Swap:      16777212      441996    16335216

Do you have a maximum RAM allocation limit hardcoded in PyTorch (file "THGeneral.c")? Thank you in advance!

Complete error message:
```
$ python3 train.py ./out/ > train.out
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    augment_img = torch.stack(augment_img)[perm_index]
  File "/path-to-anaconda/Anaconda3/4.3.1/envs/pytorchenv/lib/python3.5/site-packages/torch/functional.py", line 64, in stack
    return torch.cat(inputs, dim)
RuntimeError: $ Torch: not enough memory: you tried to allocate 72GB. Buy new RAM! at /opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/TH/THGeneral.c:253
```

**Comment by apaszke** [comment]
72GB is a lot, it might be the OS that rejects such a request. We don't have any allocation limits, this error is raised when `malloc` fails to claim more memory.

**Comment by zou3519** [comment]
@ponomarevsy do you think your code should be allocating 72GB?

I'm currently investigating large memory usage with convolutions on the CPU: https://github.com/pytorch/pytorch/issues/5285, if you're using any convolutions in your model this could be related.

**Comment by ponomarevsy** [comment]
Thank you for your feedback, @apaszke and @zou3519. @apaszke, are you sure this is not a memory leakage issue similar to @zou3519? Also, I see no reason why wouldn't PyTorch allocate more than 72G (if needed), knowing that there is 124G available on the node. Still this sounds like too much RAM to me. I remember having similar issues using DIGITS (with Caffe). Do these training sets require that much RAM?

**Comment by colesbury** [comment]
You probably don't have 124 GB available at the point where you try to allocate 72GB. It looks like the triggering call is `torch.stack`. Unless you have repeated inputs, there's a good chance that the inputs use up 72 GB as well.

**Comment by yeladlouni** [comment]
It could be a problem of memory alignment.

**Comment by lisiyaoATbnu** [comment]
I think I've met a similar situation.

I tested my small (totally forward) network on one ~1000x1000 image but it seemed to try to allocate ~45G memory. Hence it broke.

Very interestingly, when I tried Python 2 (different env) on the same computer, it ran and I got a good result.

I'm still confused by that...

**Comment by linchart** [comment]
I also met a similar situation with a small network and data, when my code run after 5 epochs, it raised: RuntimeError: $ Torch: not enough memory: you tried to allocate 5GB , really strange

**Comment by ronalddas** [comment]
Even I am facing a simillar issue, am trying run evaluation on a  28MB model file and am getting issue, `RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 377216000 bytes. Error code 12 (Cannot allocate memory)
` , why is it trying to allocate in PetaBytes??

**Comment by zou3519** [comment]
@ronalddas 377216000 is 377 mb

**Comment by GraphGrailAi** [comment]
> Even I am facing a simillar issue, am trying run evaluation on a 28MB model file and am getting issue, `RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 377216000 bytes. Error code 12 (Cannot allocate memory) ` , why is it trying to allocate in ~PetaBytes~??(Correction, 377mb)

Similar problem: RAM is 4GB, GPU with 12 GB memory, my model i try to load is 5GB. But i see error "you tried to allocate 108216000 bytes" - that is 108mb - that is strange

**Comment by Dungarian** [comment]
When I sace the same model using torch.save and load again using torch.load and run embedding layer in the model, I encounter the same error. But if I don't save the model, it runs without errors.

**Comment by nusherjk** [comment]
> > Even I am facing a simillar issue, am trying run evaluation on a 28MB model file and am getting issue, `RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 377216000 bytes. Error code 12 (Cannot allocate memory) ` , why is it trying to allocate in ~PetaBytes~??(Correction, 377mb)
> 
> Similar problem: RAM is 4GB, GPU with 12 GB memory, my model i try to load is 5GB. But i see error "you tried to allocate 108216000 bytes" - that is 108mb - that is strange

having same issue with 196 mb of RAM. any solution?

**Comment by nusherjk** [comment]
> > > Even I am facing a simillar issue, am trying run evaluation on a 28MB model file and am getting issue, `RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 377216000 bytes. Error code 12 (Cannot allocate memory) ` , why is it trying to allocate in ~PetaBytes~??(Correction, 377mb)
> > 
> > 
> > Similar problem: RAM is 4GB, GPU with 12 GB memory, my model i try to load is 5GB. But i see error "you tried to allocate 108216000 bytes" - that is 108mb - that is strange
> 
> having same issue with 196 mb of RAM. any solution?

Fixed it with a garbage collector.
add ` import gc` 
and add `gc.collect()` after each end of epoch or wherever you please

**Comment by afogarty85** [comment]
> Fixed it with a garbage collector.
> add ` import gc`
> and add `gc.collect()` after each end of epoch or wherever you please

This fixed a similar issue for me with repeated hyperopt trials. Thank you.

**Comment by nitish1295** [comment]
Seem to be facing a similar issue, the program expects the availability of **61172617632 bytes or 61.172617632 GB of memory.**

Setup Details:

- OS : Windows 10
- Python Version : Python 3.7.6
- Torch Version : 1.9.0
- How you installed PyTorch (conda, pip, source): pip install torch torchvision torchaudio
- CUDA/cuDNN version : N/A
- GPU models and configuration: NVIDIA GeForce 940MX
- GCC version (if compiling from source):N/A
- RAM : 8.00 GB

- Script to reproduce the bug and error traces below

```
import torch
tensor1 =  torch.rand((133574, 30),dtype=float)
tensor2 = torch.rand((57246, 30),dtype=float)
similarity_measure = torch.cdist(tensor1, tensor2, p=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path\Python\Python37\lib\site-packages\torch\functional.py", line 1049, in cdist
    return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 61172617632 bytes.

```

- Context
Trying to find similarty based on 2-norm(Eucledian Distance) for each of the value in ```tensor2``` against each value in ```tensor1```,relatively new to Pytorch so not sure about the underlying working of ```cdist``` or  if this is a valid response from Pytorch

**Comment by Mehmaam99** [comment]
Same issue occur, Open Task Manager and End Task all files related to this code, (ex: Python, VS Code etc.) and restart your IDE.
These steps solve my issue.
