### ISSUE TITLE
[proposal] Integrate autograd graph visualizer for displaying crashed locations during detect_anomaly

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#54375]
@szagoruyko made a good simple visualizer: https://github.com/szagoruyko/pytorchviz. if sth like that starts to include identifiers produced by stack traces (produced by anomaly detector), it would be very useful for debugging infs/nans produced at forward or backward

**Comment by szagoruyko** [comment]
I think that’s a great idea, although might be a bit cumbersome for large networks. cc @albanD who’s been working on pytorchviz recently.

**Comment by albanD** [comment]
> Otherwise, could PyTorch enable some tracing information (like line numbers) at python level, so that exceptions from anomaly detector include it?

It already provide a full stack trace, so it does contain like numbers. Or I am missing something?

More generally, including these info might be possible but can be tricky to get from the error unless we specify a specific protocol that anomaly mode would mark some inputs and torchviz will be able to read this information.

**Comment by vadimkantorov** [comment]
An example of stack trace from my colleagues fine-tuning svoice contains no lines specific to the failed op. + our good friend cutting off long python lines
```
Traceback (most recent call last):
  File "train.py", line 118, in main
    _main(args)
  File "train.py", line 112, in _main
    run(args)
  File "train.py", line 93, in run
    solver.train()
  File "/work/svoice/svoice/solver.py", line 133, in train
    train_loss = self._run_one_epoch(epoch)
  File "/work/svoice/svoice/solver.py", line 230, in _run_one_epoch
    self.scaler.scale(loss).backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function 'AddmmBackward' returned nan values in its 0th output.
```

**Comment by albanD** [comment]
This stack trace is expected not to be super informative for me. It will always point to the `.backward()` call.
The one above (in a warning) should be the interesting one pointing at what you want?

**Comment by vadimkantorov** [comment]
I'll check for that one! Thanks for the suggestion.

Orignally I meant somehow enabling to identify a failed AddmmBackward node in the graph (e.g. by having some unique ids allowing to identify failing part of the graph)

**Comment by albanD** [comment]
> Orignally I meant somehow enabling to identify a failed AddmmBackward node in the graph (e.g. by having some unique ids allowing to identify failing part of the graph)

We do have these. But it is hard to share that information between the failing backward and the torchviz code :p 

What we could do is make the anomaly mode leave info on the failing Node's metadata field that the torchviz visualizer can use to show the issue.
