### ISSUE TITLE
JIT CUDA linalg.pinv and torch.pinverse tests are failing on pytorch_linux_xenial_cuda9_2_cudnn7_py3_gcc7_test

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54381]
See https://app.circleci.com/pipelines/github/pytorch/pytorch/287971/workflows/3566b7af-c730-40f3-bbe9-81062df4eb35/jobs/11696712 for an example. Relevant snippets:

```
test_variant_consistency_jit_linalg_pinv_cuda_float64 - TestCommonCUDA
test_ops.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 955, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 265, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 317, in test_variant_consistency_jit
    no_grad=not test_backward)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 78, in check_against_reference
    outputs_test = output_func(self.runAndSaveRNG(func, recording_inputs, kwargs))
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 130, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/jit_metaprogramming_utils.py", line 302, in script_fn
    self.assertExportImport(fn.graph, tensors)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 118, in assertExportImport
    self.assertExportImportModule(m, inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 123, in assertExportImportModule
    b = self.runAndSaveRNG(m_import, inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 130, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 134, in prof_meth_call
    return prof_callable(meth_call, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 128, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 7, in forward
  def forward(self: __torch__.PlaceholderModule,
    i0: Tensor) -> Tensor:
    _0 = torch.linalg_pinv(i0, 1.0000000000000001e-15, False)
         ~~~~~~~~~~~~~~~~~ <--- HERE
    return _0

Traceback of TorchScript, original code (most recent call last):
  File "<string>", line 3, in forward

def the_method(i0):
    return torch.linalg.pinv(i0)
           ~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: magma: The value of work_size(-9223372036854775808) is too large to fit into a magma_int_t (4 bytes)
```

```
test_variant_consistency_jit_pinverse_cuda_float64 - TestCommonCUDA
test_ops.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 955, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 265, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 317, in test_variant_consistency_jit
    no_grad=not test_backward)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 78, in check_against_reference
    outputs_test = output_func(self.runAndSaveRNG(func, recording_inputs, kwargs))
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 130, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/jit_metaprogramming_utils.py", line 302, in script_fn
    self.assertExportImport(fn.graph, tensors)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 118, in assertExportImport
    self.assertExportImportModule(m, inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 122, in assertExportImportModule
    a = self.runAndSaveRNG(m, inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 130, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 131, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 128, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 3, in forward

def the_method(i0):
    return torch.pinverse(i0)
           ~~~~~~~~~~~~~~ <--- HERE
RuntimeError: magma: The value of work_size(-9223372036854775808) is too large to fit into a magma_int_t (4 bytes)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @gmagogsfm

**Comment by mruberry** [comment]
Started happening in the HUD on https://github.com/pytorch/pytorch/commit/544a996f83be15f2a13553ceb4041ec1af9f0c36 (but several other PRs shared a signal) and has been happening consistently.

**Comment by mruberry** [comment]
These tests have been skipped, but it looks like another test is now failing intermittently. Relevant snippet:

```
test_fn_grad_linalg_pinv_hermitian_cuda_float64 - TestGradientsCUDA
test_ops.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 955, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 265, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 138, in test_fn_grad
    self._grad_test_helper(device, dtype, op, op.get_op())
  File "test_ops.py", line 123, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck')
  File "test_ops.py", line 109, in _check_helper
    check_grad_dtypes=True))
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 563, in gradcheck
    torch._C._functions.UndefinedGrad()(o) for o in _differentiable_outputs(func(*tupled_inputs))
  File "test_ops.py", line 103, in fn
    output = variant_out_fn(*inputs, **sample.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_methods_invocations.py", line 1093, in hermitian_func
    return self.op(hermitian_input, **kwargs)
RuntimeError: magma: The value of work_size(-9223372036854775808) is too large to fit into a magma_int_t (4 bytes)
```

**Comment by mruberry** [comment]
cc @IvanYashchuk would you take a look?

**Comment by IvanYashchuk** [comment]
Yes, will do.
