### ISSUE TITLE
test_clamp fails on ppc64le

### ISSUE THREAD

**Issue by cdeepali** [pytorch/pytorch#54407]
## 🐛 Bug

```
======================================================================
FAIL: test_clamp (__main__.TestTEFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit_fuser_te.py", line 430, in test_clamp
    s = self.checkScript(f, (inp1, inp2), profiling=ProfilingMode.PROFILING)
  File "/opt/conda/envs/opence-conda-env-20210322080214/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 440, in checkScript
    frames_up=2)
  File "/opt/conda/envs/opence-conda-env-20210322080214/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 470, in checkScript
    self.assertEqual(script_outputs, opt_script_outputs, atol=atol, rtol=rtol)
  File "/opt/conda/envs/opence-conda-env-20210322080214/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1165, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 16 element(s) (out of 16) whose difference(s) exceeded the margin of error (including 16 nan comparisons). The greatest difference was nan (0.0 vs. nan), which occurred at index (0, 0).

----------------------------------------------------------------------
Ran 79 tests in 191.082s

FAILED (failures=1, skipped=14)
Traceback (most recent call last):
  File "test/run_test.py", line 926, in <module>
    main()
  File "test/run_test.py", line 905, in main
    raise RuntimeError(err_message)
RuntimeError: test_jit_fuser_te failed!
```

## To Reproduce
`python test/run_test.py -i test_jit_fuser_te`

## Expected behavior

The test should pass. 

## Environment

 - PyTorch Version : 1.8.0
 - OS (e.g., Linux):  RHEL 7.8

**Comment by SplitInfinity** [comment]
@ZolotukhinM Can I add this to the NNC project instead?

**Comment by ZolotukhinM** [comment]
Yeah, that sounds right, I'll move it.

**Comment by suo** [comment]
@malfet fyi

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
