### ISSUE TITLE
Some Numba tests are failing

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54418]
test_from_cuda_array_interface, test_from_cuda_array_interface_active_device, and test_from_cuda_array_interface_lifetime are failing. Example failure snippet:

```
Traceback (most recent call last):
  File "test_numba_integration.py", line 339, in test_from_cuda_array_interface_active_device
    self.assertEqual(torch_ary.__cuda_array_interface__, numba_ary.__cuda_array_interface__)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1268, in assertEqual
    exact_device=exact_device)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1259, in assertEqual
    super().assertEqual(x, y, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: Items in the second set but not the first:
'stream' : Attempted to compare [set] types: Expected: {'version', 'typestr', 'data', 'shape', 'strides'}; Actual: {'version', 'typestr', 'data', 'stream', 'shape', 'strides'}.
```

The PR these failures first appear on seems to be unrelated.

**Comment by zou3519** [comment]
@malfet says: maybe we just need to update numba here.

**Comment by bluenote10** [comment]
> @malfet says: maybe we just need to update numba here.

FYI numba went from 0.53 (at the time the issue was reported) to 0.56, so there is a certain potential that updating numba changes something.
