### ISSUE TITLE
Caught an integer overflow or wraparound in torch.nn.MaxPool1d

### ISSUE THREAD

**Issue by PangPangpeng** [pytorch/pytorch#54499]
## 🐛 Bug

The `MaxPool1d` takes an integer as its first argument. However, when I pass a big number to this function, I got an Runtime Errror. This error is quit normal but the log is interesting.
`RuntimeError: Given input size: (16x1x50). Calculated output size: (16x1x-272823246). Output size is too small`
the calculated out put size, has a negative number. I think it meets an integer overflow. But I can't figure out what function going wrong right now.

## To Reproduce

`import torch `
`m=torch.nn.MaxPool1d(545646544,stride=2)`
`input=input=torch.randn(20,16,50)`.
`m(input)`

then I got the runtime error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 651, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 76, in forward
    self.return_indices)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/_jit_internal.py", line 209, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/functional.py", line 496, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (16x1x50). Calculated output size: (16x1x-272823246). Output size is too small
`

## Expected behavior

the unexpected number should bu filtered out.

## Environment
PyTorch version: 1.5.0+ascend.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 7.3.0
CMake version: version 3.20.0-rc3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by eqy** [comment]
This is not an overflow or wraparound but just a negative value caused by the output size computation not checking that the kernel size is not larger than the input size. We can add a check/error message for this case if it is less confusing.
