### ISSUE TITLE
Exporting the operator prim_dtype to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by II245** [pytorch/pytorch#54532]
## 🐛 Bug
When I export model from Pytorch (1.7.1) to onnx with jit decorator I get RuntimeError. Please, see output below.

```
1.7.1
{'o': tensor([[0.9552, 0.6199, 0.5749, 0.0528, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.2690, 0.3177, 0.9293, 0.6636, 0.9397, 0.9952, 0.6596, 0.2583, 0.0496,
         0.8314]], device='cuda:0')}
Traceback (most recent call last):
  File "fp32_jit_prim_dtype_repro.py", line 31, in <module>
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 978, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, symbolic_name, opset_version,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator prim_dtype to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

```

## To Reproduce

Run script below

```python
import onnxruntime
from torch import nn
import torch

print(torch.__version__)

@torch.jit.script
def compute_output_lengths(x, lengths_fraction):
	return (lengths_fraction * x.shape[-1]).ceil().long()

@torch.jit.script
def temporal_mask(x, lengths):
	return (torch.arange(x.shape[-1], device = x.device, dtype = lengths.dtype).unsqueeze(0) <
			lengths.unsqueeze(1)).view(x.shape[:1] + (1, ) * (len(x.shape) - 2) + x.shape[-1:])

class Model(nn.Module):
	def forward(self, x, xlen):
		l = compute_output_lengths(x, xlen)
		tm = temporal_mask(x, l)
		x = x * tm
		return dict(o=x)

model = Model()
model.to(device='cuda')

x = torch.rand(2, 10).to( device='cuda')
xlen = torch.rand(2).to( device='cuda')

print(model(x, xlen))

torch.onnx.export(
		model, (x, xlen),
		'fp32_jit_prim_dtype_repro.onnx',
		verbose=False,
		opset_version=12,
		export_params=None,
		do_constant_folding=True,
		input_names=['x', 'xlen']
)

runtime = onnxruntime.InferenceSession('fp32_jit_prim_dtype_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy(), xlen=xlen.cpu().numpy())))
```

## Environment

 - OS Platform and Distribution: Linux Ubuntu 18.04: Linux x86_64
 - ONNX Runtime version: onnxruntime-1.6.0
 - Python version: Python 3.8
 - Pytorch version: 1.7.1
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - CUDA/cuDNN version: CUDA Version: 10.2
 - GPU model and memory: Tesla V100 (32G)

## Additional context
 
[fp32_jit_prim_dtype_repro_onnx.zip](https://github.com/pytorch/pytorch/files/6192255/fp32_jit_prim_dtype_repro_onnx.zip)

Note: Current problem is gone with Pytorch version (1.8.0)
But then I got another fail and opened an issue at onnxruntime repo. See here https://github.com/microsoft/onnxruntime/issues/7098

Thanks for reply!

**Comment by jiafatom** [comment]
This is the exporter issue not an onnxruntime issue: `x.shape[:1] + (1, ) * (len(x.shape) - 2) + x.shape[-1:])` is tuple add which is not well support now.
In your case, (1,)*0=(), but exporter treat it as [0].
Is your code from part of the model? We will evaluate the priority for handling this.

The current workaround is to export `def temporal_mask(x, lengths)` via tracing - remove the line `@torch.jit.script` and it works.

**Comment by vadimkantorov** [comment]
@jiafatom This is a substitute for multidim multiple unsqueeze which we don't have: https://github.com/pytorch/pytorch/issues/7991 in order to enable broadcasting. If we had multidim unsqueeze, this would be `x.unsqueeze(dim = [-2] * (x.ndim - 2))`

**Comment by jiafatom** [comment]
@vadimkantorov Did my suggested work around unblock your case?

**Comment by vadimkantorov** [comment]
Yes, then it works. That's what we ended up doing, so we are not blocked. But decided to report this anyway

**Comment by garymm** [comment]
I don't see the original error message. Current error that is produced by the given code is tracked by https://github.com/pytorch/pytorch/issues/55597
