### ISSUE TITLE
if cannot be symbolically traced

### ISSUE THREAD

**Issue by turian** [pytorch/pytorch#54602]
## 🐛 Bug

`if` conditional cannot be symbolically traced. Related to #44901

## To Reproduce

```
import torch

# Simple module for demonstration
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(3, 4))
        self.linear = torch.nn.Linear(4, 5)

    def forward(self, batch_idx=None):
        if batch_idx:
            self.randomize(seed=batch_idx)
        return T(0.0)


module = MyModule()

from torch.fx import symbolic_trace

# Symbolic tracing frontend - captures the semantics of the module
symbolic_traced: torch.fx.GraphModule = symbolic_trace(module)

# High-level intermediate representation (IR) - Graph representation
print(symbolic_traced.graph)
```

```
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    symbolic_traced: torch.fx.GraphModule = symbolic_trace(module)
  File "/Users/joseph/opt/miniconda3/lib/python3.8/site-packages/torch/fx/symbolic_trace.py", line 606, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/Users/joseph/opt/miniconda3/lib/python3.8/site-packages/torch/fx/symbolic_trace.py", line 355, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "example.py", line 11, in forward
    if batch_idx:
  File "/Users/joseph/opt/miniconda3/lib/python3.8/site-packages/torch/fx/proxy.py", line 164, in __bool__
    return self.tracer.to_bool(self)
  File "/Users/joseph/opt/miniconda3/lib/python3.8/site-packages/torch/fx/proxy.py", line 94, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

## Expected behavior

FX graph is printed.

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): OSX
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information:

**Comment by jamesr66a** [comment]
Hi @turian,

This is a known limitation of symbolic tracing. In your specific example, if `batch_idx` is known statically to be either `None` or not `None`, `concrete_args` can be used to specialize the trace. See the docs for information: https://pytorch.org/docs/stable/fx.html#limitations-of-symbolic-tracing

**Comment by MHGL** [comment]
https://github.com/DeepVAC/deepvac/issues/115

**Comment by aksenventwo** [comment]
With custom Tracer, the control flow can be used by Trace，Please see https://github.com/pytorch/pytorch/issues/51803#issuecomment-1104634592
