### ISSUE TITLE
qsize not implemented error

### ISSUE THREAD

**Issue by gilgarad** [pytorch/pytorch#54655]
## To Reproduce

```
from torch.multiprocessing import Queue
queue = Queue()
print(queue.qsize())
```
Working at 1.5.0 ver (desktop, ryzen 2700)
NOT working at 1.7.1 ver (laptop, m1 chip macbook)

It shows the NOT IMPLEMENTED error.

 - PyTorch Version (e.g., 1.0): 1.7.1 
 - OS (e.g., Linux): macos
 - How you installed PyTorch (`conda`, `pip`, source): pip install
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information: macbook air m1

**Comment by skyline75489** [comment]
Hi, please try to provide as much as information as you can. There's [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) that helps you do that. Also you may want to provide the actual output of this error.

**Comment by ailzhang** [comment]
It works for me on master branch. Maybe try the latest 1.8.1 release?

**Comment by malfet** [comment]
Hmm, I can reproduce it on x86_64 Mac, although my setup is admittedly weird:
```
% python3 -c "import torch;print(torch.multiprocessing.Queue().qsize())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
 % python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.3 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.26.2)
CMake version: version 3.19.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.1
[pip] torch==1.7.1
[conda] mkl-include               2020.1                intel_216    intel
[conda] mkl-static                2020.1                intel_216    intel
```

**Comment by malfet** [comment]
Though it's not a pytorch, but rather Python runtime problem:
```
% python3 -c "import multiprocessing;print(multiprocessing.Queue().qsize())"                                     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()

```
