### ISSUE TITLE
torch.sqrt for negative values should either return complex tensors or clearly throw a domain error/warning

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#54753]
There are three possible courses of action here:
1. Throw a warning like numpy and continue returning nan
2. Throw a domain error like `math.sqrt`
3. Return a complex tensor like cmath

```
>>> np.sqrt(np.array([-1]))
<stdin>:1: RuntimeWarning: invalid value encountered in sqrt
array([nan])
>>> math.sqrt(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>> torch.sqrt(torch.tensor(-1))
tensor(nan)
>>> cmath.sqrt(-1)
1j
```

**Comment by anjali411** [comment]
I think we should return a complex tensor, and I am surprised numpy doesn't already do that. I think we should align ourselves with `cmath` now that we support both real and complex numbers. @rgommers what are your thoughts here?

**Comment by kshitij12345** [comment]
> I think we should return a complex tensor, and I am surprised numpy doesn't already do that.

I don't think it is feasible as the output dtype will change based on the input values of the tensor (complex for negative values and float for positive?) (or should it always return complex tensor as output?)

**Comment by rgommers** [comment]
> I don't think it is feasible as the output dtype will change based on the input values of the tensor (complex for negative values and float for positive?)

I agree, such value-based behavior is undesirable. 

We have such discussions a lot in NumPy when a stdlib module deviates. I think `math`/`cmath` are more for teaching and not the best reference, they have none of the constraints of a library for serious numerical work. The same goes for `statistics`, and anything numerical in the stdlib. We should follow Python for numerical operators (true division, `@`, etc.) but little else.

The NumPy default makes sense to me. If you have a large array with one negative value, you often want to just continue and propagate nans. This is use case dependent though, there's also times where you do want the domain error. With numpy that's easy to get:
```
>>> x = np.array([-1, 0, 1])
>>> np.sqrt(x)
<ipython-input-3-0b43c7e80401>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(x)
array([nan,  0.,  1.])
>>> with np.errstate(invalid='raise'):
...     np.sqrt(x)
... 
Traceback (most recent call last):
  File "<ipython-input-4-0d4fdb02b53a>", line 2, in <module>
    np.sqrt(x)
FloatingPointError: invalid value encountered in sqrt
```

I mentioned `errstate` in https://github.com/pytorch/pytorch/issues/38349#issuecomment-631656705, but we didn't discuss it in detail. I'm guessing it may not make sense to implement for PyTorch because it won't work well on GPU.

**Comment by ezyang** [comment]
We want something like errstate for CUDA; I really want someone to dust off #26776 and get it over the finish line

**Comment by mruberry** [comment]
Returning NaN for these values (when given on float inputs) sounds good.

Just to echo @kshitij12345 and @rgommers, we don't want to determine the dtype of an output based on the values inside tensor inputs. (Going further, we probably want to be able to determine the shape, device, and dtype of outputs just from tensor metadata and non-tensor args to a function.)

**Comment by amehra-github** [comment]
Hi @anjali411, I am new to this repo and would like to know if I could work on this as my first issue.
