### ISSUE TITLE
[FX] Cannot symbolically trace class method

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#54785]
```
import torch

from torch import fx

class M(fx.GraphModule):
    def __init__(self):
        super().__init__(self, fx.Graph())
        graph = fx.symbolic_trace(M.fake_forward)
        self.graph = graph
        self.recompile()
        self.register_buffer("w1", torch.ones(3))

    def fake_forward(self, x):
        return self.w1 * x

m = M()
"""
Traceback (most recent call last):
  File "/home/jamesreed/repro.py", line 16, in <module>
    m = M()
  File "/home/jamesreed/repro.py", line 8, in __init__
    graph = fx.symbolic_trace(M.fake_forward)
  File "/data/users/jamesreed/pytorch/torch/fx/symbolic_trace.py", line 622, in symbolic_trace
    return GraphModule(tracer.root, graph, name)
  File "/data/users/jamesreed/pytorch/torch/fx/graph_module.py", line 232, in __init__
    self.graph = graph
  File "/data/users/jamesreed/pytorch/torch/nn/modules/module.py", line 1142, in __setattr__
    object.__setattr__(self, name, value)
  File "/data/users/jamesreed/pytorch/torch/fx/graph_module.py", line 257, in graph
    self.recompile()
  File "/data/users/jamesreed/pytorch/torch/fx/graph_module.py", line 466, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals)
  File "/data/users/jamesreed/pytorch/torch/fx/graph_module.py", line 43, in _forward_from_src
    exec_with_source(src, globals)
  File "/data/users/jamesreed/pytorch/torch/fx/graph_module.py", line 28, in exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key_1>", line 2
SyntaxError: duplicate argument 'self' in function definition
"""
```

**Comment by jamesr66a** [comment]
@ansley
