### ISSUE TITLE
Why does my pytorch distributed training (DDP) code send a SIGKILL signal on its own on most version of pytorch 1.6.0, 1.7.0, 1.7.1?

### ISSUE THREAD

**Issue by brando90** [pytorch/pytorch#54823]
## 🐛 Bug

In an attempt to fix error (https://github.com/pytorch/pytorch/issues/54550) I decided to downgrade to multiple pytorch and cuda version (mainly 1.6.0, 1.7.0, 1.7.1 and using cuda 10.2, 11.0 & 11.1). I will only paste the info for 1 case as you will find at the end of the issue since for those version the error is exactly the same (random SIGKILL without explanation). 

```
('lr_reduce_steps', 3)
('validation', True)
('rank', -1)
('master_port', '46209')
('device', device(type='cuda'))
('jobid', '-1_pid_22342')
('slurm_jobid', -1)
('slurm_array_task_id', -1)
('condor_jobid', -1)
('current_time', 'Mar26_19-44-40')
('tb_dir', PosixPath('/home/miranda9/data/logs/logs_Mar26_19-44-40_jobid_-1_pid_22342/tb'))
('gpu_name', 'GeForce GTX TITAN X')
('PID', '22342')
torch.cuda.device_count()=2

opts.world_size=2

ABOUT TO SPAWN WORKERS
done setting sharing strategy...next mp.spawn
rank=0
mp.current_process()=<SpawnProcess name='SpawnProcess-1' parent=22342 started>
os.getpid()=22426
setting up rank=0 (with world_size=2)
MASTER_ADDR='127.0.0.1'
46209
backend='nccl'
rank=1
mp.current_process()=<SpawnProcess name='SpawnProcess-2' parent=22342 started>
os.getpid()=22427
setting up rank=1 (with world_size=2)
MASTER_ADDR='127.0.0.1'
46209
backend='nccl'
--> done setting up rank=1
setup process done for rank=1
--> done setting up rank=0
setup process done for rank=0
2021-03-26 19:44:46.630599: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Starting training...

n_epoch=0
i=0: loss=tensor(11.1175, device='cuda:0', grad_fn=<NllLossBackward>)
i=1: loss=tensor(10.8209, device='cuda:0', grad_fn=<NllLossBackward>)
i=2: loss=tensor(10.2632, device='cuda:0', grad_fn=<NllLossBackward>)
i=3: loss=tensor(10.0895, device='cuda:0', grad_fn=<NllLossBackward>)
...
i=175: loss=tensor(7.8008, device='cuda:0', grad_fn=<NllLossBackward>)
i=176: loss=tensor(7.6099, device='cuda:0', grad_fn=<NllLossBackward>)
i=177: loss=tensor(6.5869, device='cuda:0', grad_fn=<NllLossBackward>)
i=178: loss=tensor(7.2652, device='cuda:0', grad_fn=<NllLossBackward>)
i=179: loss=tensor(6.9902, device='cuda:0', grad_fn=<NllLossBackward>)
i=180: loss=tensor(7.1965, device='cuda:0', grad_fn=<NllLossBackward>)
Traceback (most recent call last):
  File "/home/miranda9/ML4Coq/ml4coq-proj/embeddings_zoo/tree_nns/main_brando.py", line 279, in <module>
    print(f'-----> device = {torch.device("cuda" if torch.cuda.is_available() else "cpu")}\n')
  File "/home/miranda9/ML4Coq/ml4coq-proj/embeddings_zoo/tree_nns/main_brando.py", line 188, in main_distributed
    print('done setting sharing strategy...next mp.spawn')
  File "/home/miranda9/miniconda3/envs/metalearningpy1.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/miranda9/miniconda3/envs/metalearningpy1.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/miranda9/miniconda3/envs/metalearningpy1.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 106, in join
    raise Exception(
Exception: process 0 terminated with signal SIGKILL
```

## To Reproduce

Train DDP with any model for a long time. Don't save info or do anything else that is fancy, just train with DDP.

## Expected behavior

Train and converge i 1 day more or less as it used to do.

## Environment

```
(metalearningpy1.6) miranda9~/ML4Coq $ python collect_env.py
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 2.8.12.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X
GPU 4: GeForce GTX TITAN X
GPU 5: GeForce GTX TITAN X
GPU 6: GeForce GTX TITAN X
GPU 7: GeForce GTX TITAN X

Nvidia driver version: 450.36.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0
[pip3] torchmeta==1.7.0
[pip3] torchtext==0.8.0a0+c851c3e
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchmeta                 1.7.0                    pypi_0    pypi
[conda] torchtext                 0.7.0                      py38    pytorch
[conda] torchvision               0.7.0                py38_cu102    pytorch
```

## Additional context

this was ran as an attempt to avoid the error that happens for me on the newer version 1.8.0 and related issues here:

- https://github.com/pytorch/pytorch/issues/54550
- https://stackoverflow.com/questions/66807131/how-to-solve-the-famous-unhandled-cuda-error-nccl-version-2-7-8-error
- https://stackoverflow.com/questions/66820865/why-does-my-pytorch-distributed-training-ddp-code-send-a-sigkill-signal-on-its

**Comment by brando90** [comment]
potentially useful:

```
(metalearningpy1.6) miranda9~/ML4Coq $ nvidia-smi
Fri Mar 26 22:08:11 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0 Off |                  N/A |
| 22%   25C    P8    14W / 250W |      0MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   25C    P8    14W / 250W |      0MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:08:00.0 Off |                  N/A |
| 22%   51C    P2    73W / 250W |   1388MiB / 12212MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:09:00.0 Off |                  N/A |
| 22%   29C    P8    15W / 250W |      0MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX TIT...  Off  | 00000000:84:00.0 Off |                  N/A |
| 22%   25C    P8    14W / 250W |      0MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX TIT...  Off  | 00000000:85:00.0 Off |                  N/A |
| 22%   45C    P2    76W / 250W |   1390MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX TIT...  Off  | 00000000:88:00.0 Off |                  N/A |
| 22%   24C    P8    15W / 250W |      0MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX TIT...  Off  | 00000000:89:00.0 Off |                  N/A |
| 22%   26C    P8    15W / 250W |      0MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    2   N/A  N/A      4343      C   python                           1385MiB |
|    5   N/A  N/A      4283      C   python                           1387MiB |
+-----------------------------------------------------------------------------+
```

**Comment by brando90** [comment]
potentially useful:
```
(metalearningpy1.6) miranda9~/ML4Coq $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
I thought 10.2 was loaded as thats what I think conda list says but I also was told by my sys admin it should be backwards compatible even if pytorch was built with cuda 10.2. Will post conda list in the next comment just to confirm and re-run by loading 10.2.

**Comment by brando90** [comment]
output of conda list as I promised:
```
(metalearningpy1.6) miranda9~/ML4Coq $ conda list
# packages in environment at /home/miranda9/miniconda3/envs/metalearningpy1.6:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.12.0           py38h06a4308_0  
aioconsole                0.3.1                    pypi_0    pypi
aiohttp                   3.7.4            py38h27cfd23_1  
anatome                   0.0.1                    pypi_0    pypi
argcomplete               1.12.2                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-timeout             3.0.1            py38h06a4308_0  
attrs                     20.3.0             pyhd3eb1b0_0  
beautifulsoup4            4.9.3              pyha847dfd_0  
blas                      1.0                         mkl  
blinker                   1.4              py38h06a4308_0  
boto                      2.49.0                   pypi_0    pypi
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.1.19            h06a4308_1  
cachetools                4.2.1              pyhd3eb1b0_0  
cairo                     1.14.12              h8948797_3  
certifi                   2020.12.5        py38h06a4308_0  
cffi                      1.14.0           py38h2e261b9_0  
chardet                   3.0.4           py38h06a4308_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                    pypi_0    pypi
conda                     4.9.2            py38h06a4308_0  
conda-build               3.21.4           py38h06a4308_0  
conda-package-handling    1.7.2            py38h03888b9_0  
coverage                  5.5              py38h27cfd23_2  
crcmod                    1.7                      pypi_0    pypi
cryptography              3.4.7            py38hd23ed53_0  
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   py38_0  
cython                    0.29.22          py38h2531618_0  
dbus                      1.13.18              hb2f20db_0  
dill                      0.3.3              pyhd3eb1b0_0  
expat                     2.3.0                h2531618_2  
fasteners                 0.16                     pypi_0    pypi
filelock                  3.0.12             pyhd3eb1b0_1  
flatbuffers               1.12                     pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gcs-oauth2-boto-plugin    2.7                      pypi_0    pypi
glib                      2.63.1               h5a9c865_0  
glob2                     0.7                pyhd3eb1b0_0  
google-apitools           0.5.31                   pypi_0    pypi
google-auth               1.28.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.3              pyhd3eb1b0_0  
google-pasta              0.2.0                    pypi_0    pypi
google-reauth             0.1.1                    pypi_0    pypi
graphite2                 1.3.14               h23475e2_0  
graphviz                  2.40.1               h21bd128_2  
grpcio                    1.32.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
gsutil                    4.60                     pypi_0    pypi
gym                       0.18.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
harfbuzz                  1.8.8                hffaf4a1_0  
higher                    0.2.1                    pypi_0    pypi
httplib2                  0.19.0                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
importlib-metadata        3.7.3            py38h06a4308_1  
intel-openmp              2020.2                      254  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py38h2531618_0  
lark-parser               0.6.5                    pypi_0    pypi
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
learn2learn               0.1.5                    pypi_0    pypi
libarchive                3.4.2                h62408e4_0  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblief                   0.10.1               he6710b0_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.14.0               h8c45485_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h1bed415_2  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lmdb                      0.94                     pypi_0    pypi
lz4-c                     1.9.3                h2531618_0  
markdown                  3.3.4            py38h06a4308_0  
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.3.4            py38h06a4308_0  
matplotlib-base           3.3.4            py38h62a2d02_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
mock                      2.0.0                    pypi_0    pypi
monotonic                 1.5                      pypi_0    pypi
multidict                 5.1.0            py38h27cfd23_2  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2           py38hff7bd54_0  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.1.0                      py_0  
olefile                   0.46                       py_0  
openssl                   1.1.1k               h27cfd23_0  
opt-einsum                3.3.0                    pypi_0    pypi
ordered-set               4.0.2                    pypi_0    pypi
pandas                    1.2.3            py38ha9443f7_0  
pango                     1.42.4               h049681c_0  
patchelf                  0.12                 h2531618_1  
pbr                       5.5.1                    pypi_0    pypi
pcre                      8.44                 he6710b0_0  
pexpect                   4.6.0                    pypi_0    pypi
pillow                    7.2.0                    pypi_0    pypi
pip                       21.0.1           py38h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
pkginfo                   1.7.0            py38h06a4308_0  
progressbar2              3.39.3                   pypi_0    pypi
protobuf                  3.14.0           py38h2531618_1  
psutil                    5.8.0            py38h27cfd23_1  
ptyprocess                0.7.0                    pypi_0    pypi
py-lief                   0.10.1           py38h403a769_0  
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                      py_0  
pycapnp                   1.0.0                    pypi_0    pypi
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pyglet                    1.5.0                    pypi_0    pypi
pyjwt                     1.7.1                    py38_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.2                hcf32534_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-libarchive-c       2.9                pyhd3eb1b0_0  
python-utils              2.5.6                    pypi_0    pypi
pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2021.1             pyhd3eb1b0_0  
pyu2f                     0.1.5                    pypi_0    pypi
pyyaml                    5.4.1            py38h27cfd23_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
retry-decorator           1.1.1                    pypi_0    pypi
ripgrep                   12.1.1                        0  
rsa                       4.7.2              pyhd3eb1b0_1  
ruamel_yaml               0.15.100         py38h27cfd23_0  
scikit-learn              0.24.1           py38ha9443f7_0  
scipy                     1.6.2            py38h91f5cce_0  
setuptools                52.0.0           py38h06a4308_0  
sexpdata                  0.0.3                    pypi_0    pypi
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
soupsieve                 2.2.1              pyhd3eb1b0_0  
sqlite                    3.35.2               hdfb4753_0  
tensorboard               2.4.0              pyhc547734_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.4.1                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hbc83047_0  
torchmeta                 1.7.0                    pypi_0    pypi
torchtext                 0.7.0                      py38    pytorch
torchvision               0.7.0                py38_cu102    pytorch
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.56.0                   pypi_0    pypi
typing-extensions         3.7.4.3              hd3eb1b0_0  
typing_extensions         3.7.4.3            pyh06a4308_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
werkzeug                  1.0.1              pyhd3eb1b0_0  
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.3            py38h27cfd23_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

**Comment by brando90** [comment]
> pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch

emphasis on 1.6.0 and 10.2 cuda

**Comment by brando90** [comment]
Note I am using the "right cuda" version now:
```
(metalearningpy1.6) miranda9~/ML4Coq $ module swap cuda-toolkit/11.1 cuda-toolkit/10.2

The following have been reloaded with a version change:
  1) cuda-toolkit/11.1 => cuda-toolkit/10.2

(metalearningpy1.6) miranda9~/ML4Coq $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```
next I will post the SIGKILL error if it happens again.

**Comment by imaginary-person** [comment]
If the linux kernel sent the SIGKILL, kernel logs would describe why SIGKILL was sent

**Comment by brando90** [comment]
> Note I am using the "right cuda" version now:
> 
> ```
> (metalearningpy1.6) miranda9~/ML4Coq $ module swap cuda-toolkit/11.1 cuda-toolkit/10.2
> 
> The following have been reloaded with a version change:
>   1) cuda-toolkit/11.1 => cuda-toolkit/10.2
> 
> (metalearningpy1.6) miranda9~/ML4Coq $ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:24:38_PDT_2019
> Cuda compilation tools, release 10.2, V10.2.89
> ```
> 
> next I will post the SIGKILL error if it happens again.
> 
> Note that it seems its running on the following nccl version:
> 
> ```
> ('nccl', 2408)
> ```

seems after cuda 10.2 it deadlocks now:
```
('device', device(type='cuda'))
('jobid', '-1_pid_16310')
('slurm_jobid', -1)
('slurm_array_task_id', -1)
('condor_jobid', -1)
('current_time', 'Mar26_22-13-49')
('tb_dir', PosixPath('/home/miranda9/data/logs/logs_Mar26_22-13-49_jobid_-1_pid_16310/tb'))
('gpu_name', 'GeForce GTX TITAN X')
('PID', '16310')
('nccl', 2408)
torch.cuda.device_count()=2

opts.world_size=2

ABOUT TO SPAWN WORKERS
done setting sharing strategy...next mp.spawn
rank=1
mp.current_process()=<SpawnProcess name='SpawnProcess-2' parent=16310 started>
os.getpid()=16322
setting up rank=1 (with world_size=2)
MASTER_ADDR='127.0.0.1'
51309
backend='nccl'
rank=0
mp.current_process()=<SpawnProcess name='SpawnProcess-1' parent=16310 started>
os.getpid()=16321
setting up rank=0 (with world_size=2)
MASTER_ADDR='127.0.0.1'
51309
backend='nccl'
--> done setting up rank=1
setup process done for rank=1
--> done setting up rank=0
setup process done for rank=0
```

**Comment by brando90** [comment]
> If the linux kernel sent the SIGKILL, kernel logs would describe why SIGKILL was sent

@imaginary-person how do I check that? I am not a sys admin.

**Comment by imaginary-person** [comment]
@brando90, do you mean you don't have root-access?
Then you can't do `grep /var/log/kern.log* -ie kill`, but you can probably do `dmesg -e | grep -i kill`.
