### ISSUE TITLE
torch.jit.trace(network, data) fails if data is an OrderedDict

### ISSUE THREAD

**Issue by bnsh** [pytorch/pytorch#5489]
My network takes a bunch of inputs, and I was keeping them in an ordereddict so that I could keep track of what they were. When I tried to run TensorboardX on my network, it fails with:

`Traceback (most recent call last):
  File "tensorboard.py", line 63, in <module>
    main()
  File "tensorboard.py", line 60, in main
    writer.add_graph(network, data)
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/writer.py", line 400, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/graph.py", line 52, in graph
    trace, _ = torch.jit.trace(model, args)
  File "/usr/local/lib/python2.7/dist-packages/torch/jit/__init__.py", line 241, in trace
    return TracedModule(f, nderivs=nderivs)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/jit/__init__.py", line 266, in forward
    in_vars, in_struct = _flatten((args, tuple(kw_items)), self.state_dict(keep_vars=True).values())
  File "/usr/local/lib/python2.7/dist-packages/torch/jit/__init__.py", line 568, in _flatten
    obj_vars = tuple(itertools.chain(function._iter_variables(obj), params))
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 277, in _iter
    for var in _iter(o):
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 277, in _iter
    for var in _iter(o):
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 281, in _iter
    "an input object of type " + torch.typename(obj))
ValueError: NestedIOFunction doesn't know how to process an input object of type collections.OrderedDict
`

Digging through, I found that the problem was in torch.jit.trace, tho, I'm less confident about trying to fix it.

I'm running Linux, 4.4.0-112-generic, pytorch 0.3.1 on python 2.7.12 and I installed it with pip. (I don't think the CUDA information is relevant, because this fails on my laptop which doesn't have a GPU.)

I'm attaching two files: One called "works.py" which works, if instead of using an OrderedDict, I use a list.
and one called "fails.py" which fails, since it uses an OrderedDict.

Thanks..
[demo.zip](https://github.com/pytorch/pytorch/files/1770599/demo.zip)

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
