### ISSUE TITLE
FX tracer doesn't support returning a new instance of object subclass from module forward

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#54913]
## To Reproduce

If the data class is inherited from `NamedTuple`, FX-tracing works:
```python
import torch
from torch.fx import symbolic_trace
from typing import NamedTuple


class SparseFeaturesNamedTuple(NamedTuple):
    lengths: torch.Tensor
    values: torch.Tensor


class ModuleReturnsSparseFeaturesNamedTuple(torch.nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, inputs: SparseFeatures):
        return SparseFeatures(inputs.lengths, inputs.values)
    

m = ModuleReturnsSparseFeaturesNamedTuple()
tm = symbolic_trace(m)
```

However, if the data class is inherited from `object`, FX-tracing doesn't work:
```python
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by yf225** [comment]
We want to avoid needing to introduce a new tracer subclass to handle custom data classes, so it would be awesome to have this support in vanilla PyTorch FX tracer. :)

**Comment by yf225** [comment]
Python `dataclass` doesn't seem to be a viable alternative:
```python
import torch
from torch.fx import symbolic_trace
from typing import NamedTuple
from dataclasses import dataclass


@dataclass
class SparseFeaturesDataClass:
    lengths: torch.Tensor
    values: torch.Tensor

    def values2(self):
        return self.values


class ModuleReturnsSparseFeaturesDataClass(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, inputs: SparseFeaturesDataClass):
        return SparseFeaturesDataClass(inputs.lengths, inputs.values)


m = ModuleReturnsSparseFeaturesDataClass()
tm = symbolic_trace(m)
fxsm = torch.jit.script(tm)

"""Gives error:
Traceback (most recent call last):
  File "test_yf225.py", line 25, in <module>
    tm = symbolic_trace(m)
  File "/data/miniconda3/lib/python3.7/site-packages/torch/fx/symbolic_trace.py", line 621, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/miniconda3/lib/python3.7/site-packages/torch/fx/symbolic_trace.py", line 368, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/data/miniconda3/lib/python3.7/site-packages/torch/fx/symbolic_trace.py", line 155, in create_arg
    return super().create_arg(a)
  File "/data/miniconda3/lib/python3.7/site-packages/torch/fx/proxy.py", line 121, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
NotImplementedError: argument of type: <class '__main__.SparseFeaturesDataClass'>
"""
```

**Comment by jamesr66a** [comment]
Adding support for this in base FX would likely involve defining some convention for exploding/reconstructing arbitrary classes into "primitive" data-types. We could add such a convention, or @Chillee is mentioning something like pytrees could help here
