### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED error on torch >= 1.8.0 and CUDA 11.1

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#54975]
## 🐛 Bug

When trying to run fairscale unittests with torch >= 1.8.0 and cuda 11.1, I am getting many CUBLAS failures This did not happen with 1.7.1. I've also tried March 30 nightly torch 1.9.0 and see the same error.

> attn_output_weights = torch.bmm(q, k.transpose(1, 2))
E RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
https://app.circleci.com/pipelines/github/facebookresearch/fairscale/2192/workflows/9d16d5d4-d104-4aee-971e-4eb329da80c8/jobs/14498

This does not occur with torch 1.7.1 and cuda 11.1

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.9.0.dev20210330+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla M60
GPU 1: Tesla M60
GPU 2: Tesla M60
GPU 3: Tesla M60

Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.9.0.dev20210330+cu111
[pip3] torchtext==0.6.0
[pip3] torchvision==0.10.0.dev20210330+cu111
[conda] Could not collect

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by H-Huang** [comment]
Could you also include a reproducible script where you hit this issue?

**Comment by AndyTheFactory** [comment]
I get a similar error when running the huggingface example run_ner.py for the **bert-base-multilingual-uncased** model

```
python run_ner.py \
  --model_name_or_path bert-base-multilingual-uncased \
  --dataset_name conll2003 \
  --output_dir /tmp/test-ner \
  --do_train \
  --do_eval
```

If i use torch 1.7.1+cu110 the training runs successfully

Error i get for 1.8.1+cu111:

```
Traceback (most recent call last):

  File "run_ner.py", line 501, in <module>
    main()
  File "run_ner.py", line 446, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1053, in train
    tr_loss += self.training_step(model, inputs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1443, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1475, in compute_loss
    outputs = model(**inputs)
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1679, in forward
    outputs = self.bert(
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 971, in forward
    encoder_outputs = self.encoder(
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 568, in forward
    layer_outputs = layer_module(
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 496, in forward
    layer_output = apply_chunking_to_forward(
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1819, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 508, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 411, in forward
    hidden_states = self.dense(hidden_states)
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/andrei/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Environment Information:
```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro M5000
Nvidia driver version: 460.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```
I hope this helps

**Comment by jeffwillette** [comment]
I was also getting this issue with pytorch 1.8.1 and cuda 11.1. The code I was working with worked fine on CPU but failed with this error on GPU. Downgrading pytorch to 1.8.1 with cuda 10.2 solved the problem for me. 

I am not sure what the error is with cuda 11.1

**Comment by ptrblck** [comment]
@msbaines @AndyTheFactory could you check, if you are running close to an out of memory issue in your workloads?
I've seen different cublas errors while I was hitting an OOM. Could you also try to disable the workspace via `CUBLAS_WORKSPACE_CONFIG=:0:0` and rerun the code?

@jeffwillette I think your issue is not related to this one here and I'm still debugging it. Will update you in the thread.

**Comment by larsbratholm** [comment]
@ptrblck I had a similar issue on pytorch 1.8.0/1.8.1 with cudatoolkit 11.0-11.2.2 using a RTX 3070. `CUBLAS_WORKSPACE_CONFIG=:0:0` fixed the issue for me, although not sure if it will affect performance.

**Comment by xmlyqing00** [comment]
I had similar problems. They appear randomly when I train a model. My Cuda version is 
`Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0`

`print(torch.backends.cudnn.version())` outputs `8005`
My torch version is 1.8.0+cu111 (I downgraded from 1.8.1 to 1.8.0 because I have the same issue on 1.8.1).  My torchvision version is 0.9.0+cu111
