### ISSUE TITLE
cudnn_convolution_add_relu failed when conv3d is used and allow_tf32 is enabled (cuda10, cudnn7)

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#54980]
## 🐛 Bug

If we enable conv3d-add-relu fusion, it triggers CUDNN runtime error on two CI tests,

https://app.circleci.com/pipelines/github/pytorch/pytorch/291461/workflows/24f210ec-4de2-4110-8ca0-aa72a3d1e85d/jobs/11880802
https://app.circleci.com/pipelines/github/pytorch/pytorch/291461/workflows/24f210ec-4de2-4110-8ca0-aa72a3d1e85d/jobs/11880803

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/jit/test_freezing.py", line 1816, in test_freeze_conv_relu_fusion
    self.assertEqual(mod_eager(inp), frozen_mod(inp))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 134, in prof_meth_call
    return prof_callable(meth_call, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 128, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):

    graph(%input, %weight, %bias, %z, %alpha, %stride:int[], %padding:int[], %dilation:int[], %groups:int):
        %res = aten::cudnn_convolution_add_relu(%input, %weight, %z, %alpha, %bias, %stride, %padding, %dilation, %groups)
               ~~~~ <--- HERE
        return (%res)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([5, 3, 10, 10, 10], dtype=torch.double, device='cuda', requires_grad=True)
net = torch.nn.Conv3d(3, 6, kernel_size=[3, 3, 3], padding=[0, 0, 0], stride=[2, 2, 2], dilation=[1, 1, 1], groups=1)
net = net.cuda().double()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_DOUBLE
    padding = [0, 0, 0]
    stride = [2, 2, 2]
    dilation = [1, 1, 1]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x5588cac6fee0
    type = CUDNN_DATA_DOUBLE
    nbDims = 5
    dimA = 5, 3, 10, 10, 10, 
    strideA = 3000, 1000, 100, 10, 1, 
output: TensorDescriptor 0x5588cac697d0
    type = CUDNN_DATA_DOUBLE
    nbDims = 5
    dimA = 5, 6, 4, 4, 4, 
    strideA = 384, 64, 16, 4, 1, 
weight: FilterDescriptor 0x5588cac74d90
    type = CUDNN_DATA_DOUBLE
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 5
    dimA = 6, 3, 3, 3, 3, 
Pointer addresses: 
    input: 0x40034c7000
    output: 0x40034ebe00
    weight: 0x40034c1800
cudnnConvolutionBiasActivationForward: 1
```

## To Reproduce

1. To reproduce, cherry-pick https://github.com/pytorch/pytorch/pull/54772 but revert the corresponding changes in aten/src/ATen/native/cudnn/ConvShared.cpp, meaning turning allow_tf32 back ON. 
2. Load the failed CI docker image
3. Build Pytorch and run `python test/test_jit.py -k test_freeze_conv_relu_fusion`

## Expected behavior

Test to pass without error

## Environment

See the CI error links

## Additional context

cc @csarofeen @ptrblck @xwang233

**Comment by ptrblck** [comment]
I'm currently unable to reproduce this issue on a V100 using current master with the changes from https://github.com/pytorch/pytorch/pull/54772 with `allow_tf32` kept as `true` on CUDA10.2 and cudnn7.6.5.32 (the test passes).
Unfortunately, I wasn't able to use a Maxwell GPU yet to debug this issue (I assume the test crashes on an M60 in CircleCI?) and will try to grab one again.

Based on the used cudnn version (7.6.5), the `dtype` which raises the error (`float64`), as well as the used GPU architecture I'm unsure how `allow_tf32` might interfere with this test at the moment and need to debug a bit more.
