### ISSUE TITLE
DDP checkpointing tests, test failures

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#55071]
`test_ddp_checkpointing_once` and `test_ddp_checkpointing_weight_sharing` under `test_c10d.py` were re-enabled (https://github.com/pytorch/pytorch/pull/54916) and are now always failing.

https://www.internalfb.com/intern/opensource/ci/job/log/1108125679694003/

test commands:
`pytest -vs test/distributed/test_c10d.py -k test_ddp_checkpointing_once`
`pytest -vs test/distributed/test_c10d.py -k test_ddp_checkpointing_weight_sharing`

<details>
<summary>Errors</summary>

```
Mar 30 23:01:44 ======================================================================
Mar 30 23:01:44 ERROR [2.422s]: test_ddp_checkpointing_once (__main__.DistributedDataParallelTest)
Mar 30 23:01:44 ----------------------------------------------------------------------
Mar 30 23:01:44 Traceback (most recent call last):
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
Mar 30 23:01:44     self._join_processes(fn)
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _join_processes
Mar 30 23:01:44     self._check_return_codes(elapsed_time)
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 485, in _check_return_codes
Mar 30 23:01:44     raise RuntimeError(error)
Mar 30 23:01:44 RuntimeError: Process 0 exited with error code 10 and exception:
Mar 30 23:01:44 Traceback (most recent call last):
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 382, in run_test
Mar 30 23:01:44     getattr(self, test_name)()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 30 23:01:44     fn()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 74, in wrapper
Mar 30 23:01:44     return func(*args, **kwargs)
Mar 30 23:01:44   File "distributed/test_c10d.py", line 4254, in test_ddp_checkpointing_once
Mar 30 23:01:44     assert numpy.allclose(norm, 78053), norm
Mar 30 23:01:44 AssertionError: 78250.61169433594
Mar 30 23:01:44 
Mar 30 23:01:44 Process 1 exited with error code 10 and exception:
Mar 30 23:01:44 Traceback (most recent call last):
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 382, in run_test
Mar 30 23:01:44     getattr(self, test_name)()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 30 23:01:44     fn()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 74, in wrapper
Mar 30 23:01:44     return func(*args, **kwargs)
Mar 30 23:01:44   File "distributed/test_c10d.py", line 4254, in test_ddp_checkpointing_once
Mar 30 23:01:44     assert numpy.allclose(norm, 78053), norm
Mar 30 23:01:44 AssertionError: 78250.61169433594
Mar 30 23:01:44 
Mar 30 23:01:44 
Mar 30 23:01:44 
Mar 30 23:01:44 ======================================================================
Mar 30 23:01:44 ERROR [2.422s]: test_ddp_checkpointing_weight_sharing (__main__.DistributedDataParallelTest)
Mar 30 23:01:44 ----------------------------------------------------------------------
Mar 30 23:01:44 Traceback (most recent call last):
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 286, in wrapper
Mar 30 23:01:44     self._join_processes(fn)
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _join_processes
Mar 30 23:01:44     self._check_return_codes(elapsed_time)
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 485, in _check_return_codes
Mar 30 23:01:44     raise RuntimeError(error)
Mar 30 23:01:44 RuntimeError: Process 0 exited with error code 10 and exception:
Mar 30 23:01:44 Traceback (most recent call last):
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 382, in run_test
Mar 30 23:01:44     getattr(self, test_name)()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 30 23:01:44     fn()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 74, in wrapper
Mar 30 23:01:44     return func(*args, **kwargs)
Mar 30 23:01:44   File "distributed/test_c10d.py", line 4313, in test_ddp_checkpointing_weight_sharing
Mar 30 23:01:44     assert numpy.allclose(norm, 57004), norm
Mar 30 23:01:44 AssertionError: 57085.12341308594
Mar 30 23:01:44 
Mar 30 23:01:44 Process 1 exited with error code 10 and exception:
Mar 30 23:01:44 Traceback (most recent call last):
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 382, in run_test
Mar 30 23:01:44     getattr(self, test_name)()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 288, in wrapper
Mar 30 23:01:44     fn()
Mar 30 23:01:44   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 74, in wrapper
Mar 30 23:01:44     return func(*args, **kwargs)
Mar 30 23:01:44   File "distributed/test_c10d.py", line 4313, in test_ddp_checkpointing_weight_sharing
Mar 30 23:01:44     assert numpy.allclose(norm, 57004), norm
Mar 30 23:01:44 AssertionError: 57085.12341308594
Mar 30 23:01:44 
Mar 30 23:01:44 
Mar 30 23:01:44 
Mar 30 23:01:44 ----------------------------------------------------------------------
Mar 30 23:01:44 Ran 177 tests in 202.419s
Mar 30 23:01:44 
Mar 30 23:01:44 FAILED (errors=2, skipped=20)
```
</details>

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
cc: @zhaojuanmao

**Comment by zhaojuanmao** [comment]
@H-Huang to unblock you to land your PR, you can help skip the two tests, I will enable it after fixing. thanks!

**Comment by zhaojuanmao** [comment]
fixes are in https://github.com/pytorch/pytorch/pull/55248

**Comment by gcramer23** [comment]
I am closing this issue because pr with fixes has merged.
