### ISSUE TITLE
Parameterless model still has extra inputs when exported to ONNX + insufficient checking of argument export_params

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#55144]
Note the wrong setting of `export_params = None` - probably should be checked by PyTorch. Somehow the exported model has three inputs: one tensor and two int64. Where are they coming from?

![](https://user-images.githubusercontent.com/9969784/113292658-a75dc200-92a9-11eb-9fa6-9cfb94d41321.png)

Original report: https://github.com/microsoft/onnxruntime/issues/7096 

```python
import onnxruntime
from torch import nn
import torch
import torch.nn.functional as F

print(torch.__version__)


class Model(nn.Module):
	def forward(self, x):
		p = F.pad(x, (1, 1), mode='constant').squeeze(1)
		return dict(o=p)


model = Model()
model.to(device='cuda')
x = torch.rand(1, 10).to(device='cuda')
print(x.shape)
print(model(x))

torch.onnx.export(
		model, (x,),
		'fp32_squeeze_repro.onnx',
		verbose=False,
		opset_version=12,
		export_params=None,
		do_constant_folding=True,
		input_names=['x'],
		output_names = ['o']
)

runtime = onnxruntime.InferenceSession('fp32_squeeze_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy())))

#1.8.0
#torch.Size([1, 10])
#{'o': tensor([[0.0000, 0.7245, 0.8421, 0.7092, 0.6501, 0.6383, 0.4523, 0.5001, 0.9790,
#         0.5590, 0.3269, 0.0000]], device='cuda:0')}
#Traceback (most recent call last):
#  File "fp32_squeeze_repro.py", line 33, in <module>
#    print(runtime.run(None, dict(x=x.cpu().numpy())))
#  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 120, in run
#    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
#ValueError: Model requires 3 inputs. Input Feed contains 1
```

**Comment by jiafatom** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1446551

**Comment by thiagocrepaldi** [comment]
`export_params=None` is now properly errored out through `beartype` runtime checks, which will raise an exception if incorrect type is used

**Comment by thiagocrepaldi** [comment]
On the onnx exporter, we should make sure the if-branch and else-branch have the same dimension!

**Comment by vadimkantorov** [comment]
@thiagocrepaldi Is the last item still pending?

Are plenty of Gather/Constant/Equal nodes from the `F.pad` export implementation? Would you say `F.pad` should switch to being exported directly as [Pad](https://github.com/onnx/onnx/blob/main/docs/Operators.md#pad) ONNX node?

**Comment by thiagocrepaldi** [comment]
I am not sure. 
IIRC the exporter relies on onnx shape inference to validate and propagate the shape for the if. the exporter itself cannot make any guarantees there

However, `torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by vadimkantorov** [comment]
Regarding the new exporter, two big questions are standing...
1) support for RNN export <- this was a regression
2) support for complex tensors and op lowering, important for torch fft/complex ops...
