### ISSUE TITLE
[FX] to_folder breaks with qualified type name

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#55198]
```
import torch
import torch.fx
from typing import Tuple

class Foo(torch.nn.Module):
    def forward(self, x : Tuple[torch.Tensor, torch.Tensor]):
        return x[0] + x[1]

traced = torch.fx.symbolic_trace(Foo())
traced.to_folder('fold', 'Mod')
from fold import Mod
"""
Traceback (most recent call last):
  File "to_folder.py", line 11, in <module>
    from fold import Mod
  File "/home/jamesreed/fold/__init__.py", line 1, in <module>
    from .module import *
  File "/home/jamesreed/fold/module.py", line 4, in <module>
    class Mod(torch.nn.Module):
  File "/home/jamesreed/fold/module.py", line 9, in Mod
    def forward(self, x : typing_Tuple[torch.Tensor,torch.Tensor]):
"""
```

**Comment by yuhc** [comment]
PS: After I fixed the `typing_*` qualified type name manually, it was observed to have different behaviors when being loaded by `importlib.util` (as in the test) and `from module import module_name`. The latter seems not to work.
