### ISSUE TITLE
[torch.jit.script] Python type cannot be used as a value:

### ISSUE THREAD

**Issue by BelongAl** [pytorch/pytorch#55208]
## 🐛 Bug
Python type cannot be used as a value

## To Reproduce
```
def f(x):
    return nn.Softmax(dim=-1)(x)

script = torch.jit.script(f)
```
provides the following trace:
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    script = torch.jit.script(f)
  File "/home/users/common/Python-3.6.5/lib/python3.6/site-packages/torch/jit/_script.py", line 940, in script
    qualified_name, ast, _rcb, get_default_args(obj)
  File "/home/users/common/Python-3.6.5/lib/python3.6/site-packages/torch/jit/_script.py", line 1056, in _recursive_compile_class
    _compile_and_register_class(obj, rcb, _qual_name)
  File "/home/users/common/Python-3.6.5/lib/python3.6/site-packages/torch/jit/_script.py", line 64, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
Python type cannot be used as a value:
  File "/home/users/common/Python-3.6.5/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 1189
    def __init__(self, dim: Optional[int] = None) -> None:
        super(Softmax, self).__init__()
              ~~~~~~~ <--- HERE
        self.dim = dim
'Softmax.__init__' is being compiled since it was called from '__torch__.torch.nn.modules.activation.Softmax'
  File "test.py", line 13
def f(x):
    return nn.Softmax(dim=-1)(x)
           ~~~~~~~~~~ <--- HERE
'__torch__.torch.nn.modules.activation.Softmax' is being compiled since it was called from 'f'
  File "test.py", line 13
def f(x):
    return nn.Softmax(dim=-1)(x)
           ~~~~~~~~~~~~~~~~~~~~ <--- HERE
```
## Environment

 - PyTorch Version (e.g., 1.7.1):
cc @gmagogsfm

**Comment by gmagogsfm** [comment]
This is because `nn.Module` initialization isn't supported in TorchScript. Instead, it's recommended to be constructed as a submodule of another module.

```
class ParentModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.softmax = torch.nn.Softmax(dim=-1)
 
    def forward(self, x: torch.Tensor):
         return self.softmax(x)

m = ParentModule()
scripted_m = torch.jit.script(m)
print(scripted_m(torch.rand([1, 2, 3])))
```

**Comment by BelongAl** [comment]
Thank you so much for your help! @gmagogsfm
