### ISSUE TITLE
Creating a cudatoolkit-dev to enable CUDA extension building

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#55267]
## 🚀 Feature

Requesting in addition to releasing `cudatoolkit` to also release `cudatoolkit-dev`.

## Motivation

It's so convenient that `pytorch` comes with the `cudatoolkit`.  Thank you to whoever had this bright idea in the first place!

Unfortunately when it comes to pytorch CUDA extensions one has to install a matching cuda system-wide, which is not always straightforward and there are all kinds of build problems around it. Very often JIT builds fail despite having the right cuda installed system-wide and there isn't always even the log why - often the build just hangs w/o any traceback.

But the most common problem is:
```
    Exception: Installed CUDA version 11.0 does not match the version torch was compiled with 10.2, 
unable to compile cuda/cpp extensions without a matching cuda version.
```

Would it be too difficult to also release `cudatoolkit-dev` which would enable building cuda extensions like `fairscale` and `deepspeed` w/o needing a matching system-wide cuda?

This is especially an issue for those of us that do a lot of testing and integration work and to be able to have various cuda toolkit builds contained to different virtual environments like conda would make such testing so much easier.

Thank you!

**Comment by stas00** [comment]
Just tried https://anaconda.org/conda-forge/cudatoolkit-dev and I think this is what's needed as it makes the whole cuda build environment available inside conda - so it should make extensions building a much simpler quest.

But it's not up-to-date (it's 11.0 e.g. can't use it for sm_86 cards) so somehow it'd be great to make sure that these 2 get synchronized:

- https://anaconda.org/conda-forge/cudatoolkit
- https://anaconda.org/conda-forge/cudatoolkit-dev

**Comment by rgommers** [comment]
> It's so convenient that `pytorch` comes with the `cudatoolkit`.

@stas00 I'm not sure what you mean by this. There are `cudatoolkit` packages in defaults, conda-forge, and nvidia channels, but not in the pytorch or pytorch-nightly ones.

> Just tried https://anaconda.org/conda-forge/cudatoolkit-dev and I think this is what's needed as it makes the whole cuda build environment available inside conda - so it should make extensions building a much simpler quest.

Yes, it does look useful.

> But it's not up-to-date (it's 11.0 e.g. can't use it for sm_86 cards) so somehow it'd be great to make sure that these 2 get synchronized:

The recipe for it is maintained at https://github.com/conda-forge/cudatoolkit-dev-feedstock. There are open PRs for 11.1 and 11.2, but it looks like they need some attention.

Note that that's a regular conda-forge feedstock, it's unrelated to PyTorch.

**Comment by stas00** [comment]
> > It's so convenient that `pytorch` comes with the `cudatoolkit`.
> 
> @stas00 I'm not sure what you mean by this. There are `cudatoolkit` packages in defaults, conda-forge, and nvidia channels, but not in the pytorch or pytorch-nightly ones.

I meant that one doesn't need to install `cuda` system-wide to use `pytorch`, regardless which channel it comes from.

> > Just tried https://anaconda.org/conda-forge/cudatoolkit-dev and I think this is what's needed as it makes the whole cuda build environment available inside conda - so it should make extensions building a much simpler quest.
> 
> Yes, it does look useful.
> 
> > But it's not up-to-date (it's 11.0 e.g. can't use it for sm_86 cards) so somehow it'd be great to make sure that these 2 get synchronized:
> 
> The recipe for it is maintained at https://github.com/conda-forge/cudatoolkit-dev-feedstock. There are open PRs for 11.1 and 11.2, but it looks like they need some attention.
> 
> Note that that's a regular conda-forge feedstock, it's unrelated to PyTorch.

Right, and what I was proposing that perhaps `pytorch` could maintain a cuda dev toolkit too for those users who need to build cuda extensions.

As projects like fairscale, megatron-lm, deepspeed try to gain wider adoption - they all have one common entry barrier - they don't work out of the box and require cuda-dev. Which often if already installed on one's system mismatches the cuda build of pytorch. And downgrading/upgrading system-wide packages is a problem due to conflicts with other packages. So often users are forced to use pytorch's build that matches their system-wide's cuda install, which doesn't always give the users what they want.

**Comment by rgommers** [comment]
Here's some context, from @pearu (thanks!):

- `cudatoolkit-dev` installation is basically equivalent to executing `bash cuda_11.3.0_465.19.01_linux.run --toolkit --toolkitpath=$CONDA_PREFIX --installpath=$CONDA_PREFIX --override --no-opengl-libs --no-man-page --no-drm --silent`, for instance. That is, you'll get all the development files (headers, static libraries, etc) as well as the `nvcc` compiler (IIRC) and more.. Hence, this enables building your CUDA-dependent software.
- `cudatoolkit` contains only shared libraries that are needed in runtime. No header files, no static libraries, no compilers (there is a separate conda-forge package for `nvcc` that requires locally installed CUDA Toolkit), ..

So, `cudatoolkit-dev` adds important development pieces compared to `cudatoolkit`.
For instance, when developing pytorch on our servers, we typically have `cudatoolkit` installed to `/usr/local/cuda-X.Y.Z` and we have to ensure that the conda-forge `cudatoolkit` version matches with X.Y.Z when running pytorch tests. An alternative to that would be to use `cudatoolkit-dev` package but I am not using it because installing `cudatoolkit-dev` to each conda environment that does CUDA builds, is very annoying:
- it is time-consuming to install `cudatookit-dev`
- it is disk wasting to have the same `cudatoolkit` installed into multiple conda environments. Recall: `du -sh /usr/local/cuda-11..` reports 4.8GB.

I think `cudatoolkit-dev` has only historical value.
The current practice is to let software users use `cudatoolkit` while software developers install CUDA Toolkit locally (to `/usr/local/cuda`) and use `nvcc` conda-forge package that actually just picks up the locally installed nvcc  compiler.

> Right, and what I was proposing is that perhaps `pytorch` could maintain a cuda dev toolkit too for those users who need to build cuda extensions.

There's no reason to do this. In case the PyTorch team sees value in `cudatoolkit-dev`, helping keep the conda-forge package up to date is the correct thing to do here, and far less work than adding a new `cudatoolkit-dev` in a pytorch channel.

It's also something that you can do yourself fairly easily - you can open a PR to add yourself as a maintainer on the conda-forge feedstock, and it immediately lets you merge PRs there. Note that this is what NVIDIA devs do as well - about half of the maintainers of `cudatoolkit`, `nvcc` and `cudatoolkit-dev` are from NVIDIA.

> Or alternatively, perhaps to build a pytorch cuda extension one doesn't need the whole cuda-devkit, is it possible that only a handful of files is needed?

It's not just a few files, but more importantly: this isn't allowed by the CUDA toolkit EULA.

**Comment by stas00** [comment]
> An alternative to that would be to use cudatoolkit-dev package but I am not using it because installing cudatoolkit-dev to each conda environment that does CUDA builds, is very annoying:

I'd add one more - you can't uninstall it (but probably it's easy to remove it if it's under a single dir as it usually is under `/usr/local/cuda-xxx`)

Thank you for your detailed reply,  @rgommers and I saved the magic incantation to install cuda under conda env manually. 

As you explained it's unlikely pytorch will be doing anything to make it easier for the users to build python packages with CUDA extensions. 

I am happy to close this ticket now.

**Comment by ngimel** [comment]
@stas00 please don't close the ticket, building cuda extensions has long been a pain point for our users, and we should try to make it more convenient.

**Comment by rgommers** [comment]
@ngimel do you have some suggestions to make that actionable? 

The things that come to mind for me:

- The tutorial at https://pytorch.org/tutorials/advanced/cpp_extension.html#writing-a-mixed-c-cuda-extension looks pretty good, but it doesn't include any info on toolchain installation. That could be added.
- The build system integration in the above tutorial is only for `setuptools`, and larger projects are perhaps going to want to use CMake (or scikit-build, or ...). Could use some pointers on how to do that.
- https://github.com/conda-forge/cudatoolkit-dev-feedstock could be updated, if desired.

**Comment by stas00** [comment]
There is a multitude of issues with building CUDA extensions, having the correct cuda dev env is only one of them, and the most important one. It'll probably take some scouring through pytorch Issues and issues of projects that use cuda extensions (fairscale, deepspeed, megatron, apex to name a few) to collect the full range. I will list a few of these out of the top of my head:

* One other issue that often comes up is either not having the right version of `g++`, or having it but a different version being found.
https://huggingface.co/transformers/master/main_classes/trainer.html#possible-problem-3

* the env vars PATH and LD_LIBRARY_PATH not being set up correctly.
https://huggingface.co/transformers/master/main_classes/trainer.html#possible-problem-2

* `ninja` most of the time reports that it fails to run `ninja -v` when the problem is totally different. So it's very confusing to the users. One has to ignore that error and instead go up the build log and look for the real problem.

* the failed build report often suggests looking in a log file for the details which is not there, since pip cleaned up after failing to build.

* the current pytorch by default saves all CUDA extensions under `~/.cache/torch/` which completely breaks under multiple env setup, since well, there is only one version of the binary incompatible builds. It needs to save those in the specific python env it was built with.

**Comment by rgommers** [comment]
Thanks @stas00, that's a great list. Adding more checks on correct versions, fixing the cache and improving the build log situation should all be relatively straightforward to do I'd expect.

**Comment by stas00** [comment]
One more request - currently it's very difficult to debug CUDA build problems. 

e.g. currently we are baffled about this error message:
```
gcc: error: : No such file or directory
```
when building one of the deepspeed cuda extensions:

https://github.com/microsoft/DeepSpeed/issues/1126#issuecomment-853289728 

but there is no Makefile, so it's impossible to debug what is it complaining about. As the command it printed has all the files in place.

It works on one setup, and fails on another - both being almost identical Ubuntu boxes - with just pytorch builds being different.

**Comment by stas00** [comment]
And specifically to the ninja problem I mentioned this is the most typical error:

```
...
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

As you can tell it gives a complete misleading diagnosis, since it's not `ninja -v' that returned with non-zero exit status. I don't remember the details now, but some months back I traced it and the report is almost always wrong.

**Comment by rgommers** [comment]
@andfoy will start working on this. Basic plan to start with is using the CUDA extension in https://github.com/pytorch/extension-cpp, and then introducing issues like use of mismatching CUDA or g++ version in the build env, and then fixing that to get clear error messages.


> As you can tell it gives a completely misleading diagnosis, since it's not `ninja -v' that returned with non-zero exit status. I don't remember the details now, but some months back I traced it and the report is almost always wrong.

@malfet mentioned this as well just now, and said that the old `FindCUDA` version PyTorch is using now is a cause of this - upgrading to a recent `FindCUDA` should fix/improve the situation.

**Comment by stas00** [comment]
one more related issue - very often minor CUDA changes make no difference to the API, yet most CUDA extensions by default require an exact match, .e.g. 11.2 vs 11.2. I don't know how to judge the API compatibility, but shouldn't it be the same for the minor versions?

It's a different story if certain CUDA extension wants a specific CUDA version because the others are knowingly buggy.

e.g. here is what I proposed for Deepspeed. https://github.com/microsoft/DeepSpeed/pull/1139
```
# list compatible minor CUDA versions - so that for example pytorch built with cuda-11.0 can be used
# to build deepspeed and system-wide installed cuda 11.2
cuda_minor_mismatch_ok = {
    10: ["10.0",
         "10.1",
         "10.2"],
    11: ["11.0",
         "11.1",
         "11.2",
         "11.3"],
}


def assert_no_cuda_mismatch():
    cuda_major, cuda_minor = installed_cuda_version()
    sys_cuda_version = f'{cuda_major}.{cuda_minor}'
    torch_cuda_version = ".".join(torch.version.cuda.split('.')[:2])
    # This is a show-stopping error, should probably not proceed past this
    if sys_cuda_version != torch_cuda_version:
        if (cuda_major in cuda_minor_mismatch_ok
                and sys_cuda_version in cuda_minor_mismatch_ok[cuda_major]
                and torch_cuda_version in cuda_minor_mismatch_ok[cuda_major]):
            print(f"Installed CUDA version {sys_cuda_version} does not match the "
                  f"version torch was compiled with {torch.version.cuda} "
                  "but since the APIs are compatible, accepting this combination")
            return
        raise Exception(
            f"Installed CUDA version {sys_cuda_version} does not match the "
            f"version torch was compiled with {torch.version.cuda}, unable to compile "
            "cuda/cpp extensions without a matching cuda version.")
```

At least in my experiments these minor differences didn't make any difference. But I haven't done a fully exhaustive testing.

**Comment by pearu** [comment]
> It's a different story if a certain CUDA extension wants a specific CUDA version because the others are knowingly buggy.

Usually, a CUDA software wanting a specific CUDA version is related to using a specific feature of the CUDA version, and not so much if other CUDA versions are buggy in general. I would claim that all CUDA versions are buggy in one or another way, the usability of a CUDA version depends on whether the CUDA software hits a particular bug or not.

My point is that excluding the support for a particular CUDA version based on its version number, may be a too drastic restriction as the CUDA software may function just fine with all CUDA versions assuming that some CUDA version-specific bug/feature is not hit/used and one is using the stable part of the CUDA API.

Stating that CUDA versions 11.1 and 11.2 are compatible, for instance, is really just a guess. Sometimes it is a good one, and sometimes not: it may give a false positive decision for cases where some bug in 11.1 is fixed in 11.2 and a CUDA software hits the particular bug.

The approach used in `assert_no_cuda_mismatch` uses system CUDA version info and the version-info of CUDA that pytorch was built with. My recommendation would be to include also the actual CUDA version requirements of a specific CUDA extension to this assert function. For instance, by default, all CUDA version combinations would be allowed. When the practice shows that some combinations of CUDA versions do not work together and there is no way to circumvent the issue, only then raise the incompatibility exception in the assert function, otherwise just warn about possible incompatibility issues.

**Comment by stas00** [comment]
> For instance, by default, all CUDA version combinations would be allowed. 

You must have meant to say within the same major version as implied by the context, correct?

Your explanations sounds reasonable to me.

So perhaps the core API should:

1. assert if major versions aren't identical
2. warn if minor versions are mismatched
3. give a project using CUDA extension API to blacklist some CUDA versions as incompatible - albeit I'm yet to see such an example other than for pytorch itself with Amphere cards.

Currently, each project replicates these APIs internally.

**Comment by stas00** [comment]
could we please revive this discussion? 

HF Transformers started getting models with custom CUDA kernels https://github.com/huggingface/transformers/pull/15091

and so the strict minor version check is a problem, since pytorch is fixed to 11.3 but cuda-11.6 is out already and in my experience I'm yet to see an incompatibility of minor versions, albeit of course my experience is limited to apex, Megatron-LM and Deepspeed, all of which have custom CUDA kernels and they all work just fine with minor version mismatch.


Thank you!

**Comment by andfoy** [comment]
@stas00, the PR https://github.com/pytorch/pytorch/pull/63230 that added the CUDA version check got stalled due to a lack of additional review, if you could ping there it would be helpful

**Comment by stas00** [comment]
done, might be a good idea to rebase the PR as it hasn't been updated in a long time.

**Comment by andfoy** [comment]
Thanks!

**Comment by stas00** [comment]
Actually, I have just run a CUDA build `torch.utils.cpp_extension.load`  with pytorch-1.10 / cuda-1.13 and system-wide cuda-11.5 and it built the cuda kernel w/o a single complaint. 

So have I missed the change and pytorch is already not checking minor version matches?

you can clearly see `/usr/local/cuda-11.5/bin/nvcc` and `py38_cu113` play well together:

```
PYTHONPATH=src python test.py 
Using /home/stas/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Creating extension directory /home/stas/.cache/torch_extensions/py38_cu113/fast_lsh_cumulation...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/stas/.cache/torch_extensions/py38_cu113/fast_lsh_cumulation/build.ninja...
Building extension module fast_lsh_cumulation...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] /usr/local/cuda-11.5/bin/nvcc  -DTORCH_EXTENSION_NAME=fast_lsh_cumulation -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/include -isystem /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/include/TH -isystem /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.5/include -isystem /home/stas/anaconda3/envs/py38-pt110/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /mnt/nvme1/code/huggingface/transformers-cuda-no-minor-match/src/transformers/models/yoso/fast_lsh_cumulation_cuda.cu -o fast_lsh_cumulation_cuda.cuda.o 
[...]
success
```

**Comment by albertotono** [comment]
I have CUDO 11.1 in my machine Linux, Ubuntu 20, but in my conda env I have 10.2. How can I install the extension for the conda version 10.2? Thanks in advance.

**Comment by stas00** [comment]
it's probably better to update your conda to cuda-11 see: https://anaconda.org/nvidia/cuda-toolkit

or alternatively remove cuda from your conda env completely and rely on the system-wide conda which is already 11.1

**Comment by albertotono** [comment]
> it's probably better to update your conda to cuda-11 see: https://anaconda.org/nvidia/cuda-toolkit
> 
> or alternatively remove cuda from your conda env completely and rely on the system-wide conda which is already 11.1

I think there are issues if you have CUDA 11.1 and then cudatoolkit 11.3 with pytorch, as far as I saw and read online.

**Comment by stas00** [comment]
not really, at least for the many extension packages that I work with - e.g. deepspeed and apex - any minor version will do. I remove any checks that require them to match exactly and it works just fine. of course, you can't mix cuda-10 and 11. but any 11.x will do.

that is not to say that there are no packages out there that need an exact match, but minor releases are mostly backward compatible.

Though if you have an Ampere card you want to use at least cuda-11.3 since earlier versions were buggy.

**Comment by albertotono** [comment]
> not really, at least for the many extension packages that I work with - e.g. deepspeed and apex - any minor version will do. I remove any checks that require them to match exactly and it works just fine. of course, you can't mix cuda-10 and 11. but any 11.x will do.
> 
> that is not to say that there are no packages out there that need an exact match, but minor releases are mostly backward compatible.
> 
> Though if you have an Ampere card you want to use at least cuda-11.3 since earlier versions were buggy.

Thanks, so do you may know why we are running into this message: 

>  File "/usr/local/lib/python3.7/dist-packages/knn_cuda/__init__.py", line 15, in load_cpp_ext
>     assert torch.cuda.is_available(), "torch.cuda.is_available() is False."
> AssertionError: torch.cuda.is_available() is False.

I thought it was because Colab has CUDA 11.1 and Pytorch uses 11.3 when installing knn_cuda

**Comment by stas00** [comment]
Looking at the https://github.com/unlimblue/KNN_CUDA - it doesn't say which cuda it was built against - and the repo hasn't been touched in a long time - the wheel must be against some really old cuda

but if you have this print `False`:

```
python -c "import torch; print(torch.cuda.is_available())"
```

then it's either your environment that is missing cuda, perhaps you installed pytorch for cpu, or perhaps it can't find any gpus. 

You need to sort out this one liner first - I don't think the issue has anything to do with KNN_CUDA.

You can see how on my machine it prints `True`, but if I tell it not to see my gpus it becomes `False`:

```
$ python -c "import torch; print(torch.cuda.is_available())"
True
$ CUDA_VISIBLE_DEVICES="" python -c "import torch; print(torch.cuda.is_available())"
False
```

**Comment by YodaEmbedding** [comment]
Let's say that a package's `setup.py` contains `torch.utils.cpp_extension.CUDAExtension`.

When installing that package via, e.g., `pip install <my_cuda_extension_package>`, the installer pip (or whatever) creates an isolated build environment, and installs packages specified in pyproject.toml's `build-system.requires`. (e.g., `requires = ["setuptools", "wheel", "torch"]`.) However, this version of torch may not match the configured torch version outside the isolated environment. The outer torch version should already be correctly chosen for the CUDA version. But since the isolated torch version may not be CUDA-compatible, this can lead to the [infamous error](https://github.com/facebookresearch/pytorch3d/issues/1518):

> The detected CUDA version (*) mismatches the version that was used to compile PyTorch (*). Please make sure to use the same CUDA versions.

Ideally, the torch version available within the isolated build environment should be the same as the outside environment. `pip` has a `--no-build-isolation` flag, though that's not always available (e.g., poetry), and seems like a bit of a hack.

`CUDAExtension`-using packages could avoid specifying pyproject.toml's `build-system.requires`... but that makes it impossible to install via `poetry add <my_cuda_extension_package>`.

Some package maintainers tell you to install very specific pre-built wheels for a given system (e.g., `pytorch3d...cu11.7` or something like that), but that just means that the user has to manually choose an install wheels that are compatible with various CUDA/PyTorch/Python versions... and what can a user do when the maintainer takes forever to release builds for a new CUDA/PyTorch/Python version, or just doesn't do them at all? Not to mention: if a downstream library uses a very specific pre-built wheel of a CUDAExtension-library, then clearly that library is not very useful as a library.

It would be great to have documentation on how to install `CUDAExtension` packages without running into the above problems.

**Comment by ezyang** [comment]
I don't know what a good solution for this problem is, but I am happy to help shepherd PRs people want to write to make it better.
