### ISSUE TITLE
Unable to build pytorch master branch with commit 041b4431b28eb24335189979e9a110dc9892dfe4

### ISSUE THREAD

**Issue by dbonner** [pytorch/pytorch#55276]
## 🐛 Bug

Unable to build pytorch master branch with commit 041b4431b28eb24335189979e9a110dc9892dfe4

## To Reproduce

1. git clone --recursive https://github.com/pytorch/pytorch -j 256
1. cd pytorch
1. MAX_JOBS=256 CMAKE_PREFIX_PATH=/home/daniel/py38 USE_CUDA=1 USE_CUDNN=1 USE_DISTRIBUTED=1 USE_SYSTEM_NCCL=1 TORCH_CUDA_ARCH_LIST="7.5;8.0" CUDA_HOME=/usr/local/cuda-11.2 CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu CUDNN_INCLUDE_DIR=/usr/include/x86_64-linux-gnu pip install -v ./

Final part of output:
```
    [5588/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_class_type.cpp.o
    [5589/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_interpreter.cpp.o
    [5590/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_class_import.cpp.o
    [5591/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_backend.cpp.o
    [5592/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_interface.cpp.o
    [5593/6050] Building CXX object test_jit/CMakeFiles/torchbind_test.dir/test_custom_class_registrations.cpp.o
    [5594/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_custom_class_registrations.cpp.o
    [5595/6050] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.o
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-v9cz0zti/setup.py", line 876, in <module>
        build_deps()
      File "/tmp/pip-req-build-v9cz0zti/setup.py", line 354, in build_deps
        build_caffe2(version=version,
      File "/tmp/pip-req-build-v9cz0zti/tools/build_pytorch_libs.py", line 58, in build_caffe2
        cmake.build(my_env)
      File "/tmp/pip-req-build-v9cz0zti/tools/setup_helpers/cmake.py", line 345, in build
        self.run(build_args, my_env)
      File "/tmp/pip-req-build-v9cz0zti/tools/setup_helpers/cmake.py", line 140, in run
        check_call(command, cwd=self.build_dir, env=env)
      File "/home/daniel/.pyenv/versions/3.8.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '36']' returned non-zero exit status 1.
    Running setup.py install for torch: finished with status 'error'
  Rolling back uninstall of torch
  Moving to /home/daniel/py38/bin/convert-caffe2-to-onnx
   from /tmp/pip-uninstall-vccczkpu/convert-caffe2-to-onnx
  Moving to /home/daniel/py38/bin/convert-onnx-to-caffe2
   from /tmp/pip-uninstall-vccczkpu/convert-onnx-to-caffe2
  Moving to /home/daniel/py38/lib/python3.8/site-packages/caffe2/
   from /home/daniel/py38/lib/python3.8/site-packages/~affe2
  Moving to /home/daniel/py38/lib/python3.8/site-packages/torch-1.9.0a0+gitec609e7.dist-info/
   from /home/daniel/py38/lib/python3.8/site-packages/~orch-1.9.0a0+gitec609e7.dist-info
  Moving to /home/daniel/py38/lib/python3.8/site-packages/torch/
   from /home/daniel/py38/lib/python3.8/site-packages/~orch
  Replacing /home/daniel/py38/bin/convert-caffe2-to-onnx from /tmp/pip-uninstall-vccczkpu/convert-caffe2-to-onnx
  Replacing /home/daniel/py38/bin/convert-onnx-to-caffe2 from /tmp/pip-uninstall-vccczkpu/convert-onnx-to-caffe2
  Replacing /home/daniel/py38/lib/python3.8/site-packages/caffe2/ from /home/daniel/py38/lib/python3.8/site-packages/~affe2
  Replacing /home/daniel/py38/lib/python3.8/site-packages/torch-1.9.0a0+gitec609e7.dist-info/ from /home/daniel/py38/lib/python3.8/site-packages/~orch-1.9.0a0+gitec609e7.dist-info
  Replacing /home/daniel/py38/lib/python3.8/site-packages/torch/ from /home/daniel/py38/lib/python3.8/site-packages/~orch
ERROR: Command errored out with exit status 1: /home/daniel/py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-v9cz0zti/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-v9cz0zti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wrsvtypt/install-record.txt --single-version-externally-managed --compile --install-headers /home/daniel/py38/include/site/python3.8/torch Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 812, in install
    success = install_legacy(
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:
'''
Traceback (most recent call last):
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 391, in run
    installed = install_given_reqs(
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 80, in install_given_reqs
    requirement.install(
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 830, in install
    six.reraise(*exc.parent)
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 289, in runner
    call_subprocess(
  File "/home/daniel/py38/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/daniel/py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-v9cz0zti/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-v9cz0zti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wrsvtypt/install-record.txt --single-version-externally-managed --compile --install-headers /home/daniel/py38/include/site/python3.8/torch Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-knz4xlo6'
Command exited with non-zero status 1
```
## Expected behavior

Successful build

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
```
torch-1.9.0a0+git041b443
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: GeForce RTX 2080 with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.3.0.dev0
[pip3] torch==1.9.0a0+gitec609e7
[pip3] torch-stft==0.1.4
[pip3] torchaudio==0.9.0a0+52decd2
[pip3] torchmetrics==0.2.0
[pip3] torchtext==0.10.0a0+93b03e4
[pip3] torchvision==0.10.0a0+37eb37a
[conda] Could not collect
```
## Additional context

It builds successfully when I checkout the previous commit and re-run the build process:
```
git checkout 322854d2f04eea16eacf1ebc9da82c5ecf359420
```

**Comment by imaginary-person** [comment]
What if you try building with `sudo`?

**Comment by dbonner** [comment]
I just tried sudo.  It still does not build.

**Comment by skyline75489** [comment]
Hi @dbonner thanks for the feedback. we’d appreciate it if you could find the log that shows what the actual cause of the error. The log you posted isn’t showing anything useful.

**Comment by dbonner** [comment]
I can build pytorch from the latest master now. I'll close the issue.  It does not seem worth pursuing it if the latest commit builds OK. Sorry I did not include a complete log before.  I'll include a complete log if I experience an isssue again.
