### ISSUE TITLE
Backprop second time on spectral_norm

### ISSUE THREAD

**Issue by SolomidHero** [pytorch/pytorch#55368]
## 🐛 Bug

module with spectral norm couldn't be propagated second time. This is very useful for GANs training (not to perform forward of generator second time, but remember output for discriminator and generator optimizing step)

## To Reproduce

```python
import torch
model = torch.nn.utils.spectral_norm(torch.nn.Linear(2, 5))
opt1 = torch.optim.SGD(model.parameters(), lr=1e-3)
opt2 = torch.optim.SGD(model.parameters(), lr=1e-3)

output = model(torch.randn(7, 2))
loss = output.abs().mean()

opt1.zero_grad(); loss.backward(retain_graph=True); opt1.step() # first propagation
opt2.zero_grad(); loss.backward(); opt2.step() # second
```

Traceback:
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [5, 2]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

Traceback (with detect anomaly set `True`):
```pytb
/usr/local/lib/python3.9/site-packages/torch/autograd/__init__.py:145: UserWarning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 875, in _call_impl
    result = hook(self, input)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/utils/spectral_norm.py", line 105, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "/usr/local/lib/python3.9/site-packages/torch/nn/utils/spectral_norm.py", line 92, in compute_weight
    weight = weight / sigma
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [5, 2]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

## Expected behavior

opt1 and opt2 separately calculate gradients and perform optimizing step

## Environment
```
Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.12)
CMake version: version 3.19.1

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-lightning==1.2.0
[pip3] pytorch-metric-learning==0.9.96
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.8.1
[pip3] torch-audiomentations==0.4.0
[pip3] torch-optimizer==0.1.0
[pip3] torch-summary==1.4.5
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.8.2
[conda] Could not collect
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @mruberry @jbschlosser

**Comment by albanD** [comment]
Looks like there are some inplace ops in there that break double backward. We should fix that.

**Comment by soulitzer** [comment]
This is actually an issue for any module that performs some calculation in its forward that results in a param becoming a saved variable. For example:
```
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.param = torch.nn.Parameter(torch.tensor(1., requires_grad=True))

    def forward(self, x):
        return self.param**2 * x
```
The first `opt.step()` is what is modifying param in-place.

**Comment by albanD** [comment]
What if the input requires_grad=True? Which would be the case if the Linear is not the first layer in your net.

**Comment by albanD** [comment]
After more discussion, this is expected that after the optimizer step, you have to re-do the forward to be able to backprop as most modules (Linear, conv, batchnorm, spectral_norm, etc) save the weights and so won't allow you to do that.

**Comment by carperbr** [comment]
I encountered this issue when using spectral_norm with RaLSGAN loss. However, this seems to only be an issue with the new spectral_normalization function; torch.nn.utils.spectral_norm.spectral_norm works without issue, torch.nn.utils.parameterizations.spectral_norm however encounters this issue and seems to preclude using spectral_norm with WGANs or RaLSGANs unless I'm misunderstanding something.

**Comment by soulitzer** [comment]
@carperbr Does this happen on master? We recently landed https://github.com/pytorch/pytorch/pull/62293
