### ISSUE TITLE
Can not backward torch.cdist when one of the tensor has ndim=4

### ISSUE THREAD

**Issue by TheAutumnOfRice** [pytorch/pytorch#55370]
## 🐛 Bug

The function `torch.cdist` can not be backwarded if one of the tensor has a ndim=4.

This problem can be solved by reshaping the tensor to ndim=3 before torch.cdist method, but I think it would be better if it becomes compatible with high dimension tensors, or at least giving clear error/warning messages.

## To Reproduce

```python
# 1.8.1+cpu, python3.7.4, Win10
import torch
from torch.nn import Parameter

T1 = Parameter(torch.rand(3,3,21,2),requires_grad=True)
T2 = Parameter(torch.rand(22,2),requires_grad=False)
dis = torch.cdist(T1,T2)
out = dis.max()
print(out)
out.backward()
```

The output:
```
tensor(1.2296, grad_fn=<MaxBackward1>)
Traceback (most recent call last):
  File "F:/AAAAAutumnii/project/IM/try3.py", line 9, in <module>
    out.backward()
  File "C:\Users\Autumnii\venv\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Autumnii\venv\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function CdistBackward returned an invalid gradient at index 0 - got [9, 21, 2] but expected shape compatible with [3, 3, 21, 2]
```

## Expected behavior

`torch.cdist` will support high dimension tensors.

## Environment

```

PyTorch version: 1.8.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-ignite==0.4.3
[pip3] pytorch-wavelets==1.2.3
[pip3] torch==1.8.1+cpu
[pip3] torchaudio==0.8.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.9.1+cpu
[conda] Could not collect
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by albanD** [comment]
cc @ngimel I guess the fast formula for cdist is not working for all inputs :/

**Comment by ngimel** [comment]
On the contrary, fast formula is working: 
```
In [16]: import torch
    ...: from torch.nn import Parameter
    ...: 
    ...: T1 = Parameter(torch.rand(3,3,21,2),requires_grad=True)
    ...: T2 = Parameter(torch.rand(22,2),requires_grad=False)
    ...: dis = torch.cdist(T1,T2, p=2., compute_mode='use_mm_for_euclid_dist')
    ...: out = dis.max()
    ...: print(out)
    ...: out.backward()
tensor(1.3699, grad_fn=<MaxBackward1>)

```
and slow custom backward doesn't.
