### ISSUE TITLE
DISABLED test_ddp_logging_data_cpu (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#55384]
https://app.circleci.com/pipelines/github/pytorch/pytorch/296531/workflows/35b8a894-e478-4036-a894-f0de8af14c88/jobs/12142999/steps

```
Apr 06 06:26:23 ======================================================================
Apr 06 06:26:23 ERROR [0.122s]: test_ddp_logging_data_cpu (__main__.TestDistBackendWithFork)
Apr 06 06:26:23 ----------------------------------------------------------------------
Apr 06 06:26:23 Traceback (most recent call last):
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 321, in wrapper
Apr 06 06:26:23     self._join_processes(fn)
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 514, in _join_processes
Apr 06 06:26:23     self._check_return_codes(elapsed_time)
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 557, in _check_return_codes
Apr 06 06:26:23     raise RuntimeError(error)
Apr 06 06:26:23 RuntimeError: Process 0 exited with error code 10 and exception:
Apr 06 06:26:23 Traceback (most recent call last):
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 440, in run_test
Apr 06 06:26:23     getattr(self, test_name)()
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 323, in wrapper
Apr 06 06:26:23     fn()
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3651, in test_ddp_logging_data_cpu
Apr 06 06:26:23     model_DDP = self._test_ddp_logging_data(is_gpu=False)
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3625, in _test_ddp_logging_data
Apr 06 06:26:23     self.assertGreaterEqual(ddp_logging_data.backward_compute_comm_overlap_time, 1)
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/unittest/case.py", line 1227, in assertGreaterEqual
Apr 06 06:26:23     self.fail(self._formatMessage(msg, standardMsg))
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Apr 06 06:26:23     raise self.failureException(msg)
Apr 06 06:26:23 AssertionError: 0 not greater than or equal to 1
Apr 06 06:26:23 
Apr 06 06:26:23 Process 1 exited with error code 10 and exception:
Apr 06 06:26:23 Traceback (most recent call last):
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 440, in run_test
Apr 06 06:26:23     getattr(self, test_name)()
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 323, in wrapper
Apr 06 06:26:23     fn()
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3651, in test_ddp_logging_data_cpu
Apr 06 06:26:23     model_DDP = self._test_ddp_logging_data(is_gpu=False)
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3612, in _test_ddp_logging_data
Apr 06 06:26:23     1,
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 2901, in _test_DDP_helper
Apr 06 06:26:23     l.backward()
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
Apr 06 06:26:23     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
Apr 06 06:26:23   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 148, in backward
Apr 06 06:26:23     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
Apr 06 06:26:23 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.17.0.2]:64134
Apr 06 06:26:23 
Apr 06 06:26:23 
```

```
Apr 06 06:23:26   test_ddp_logging_data_cpu (__main__.TestDistBackendWithFork) ... ERROR:torch.testing._internal.common_distributed:Caught exception: 
Apr 06 06:23:26 Traceback (most recent call last):
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 440, in run_test
Apr 06 06:23:26     getattr(self, test_name)()
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 323, in wrapper
Apr 06 06:23:26     fn()
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3651, in test_ddp_logging_data_cpu
Apr 06 06:23:26     model_DDP = self._test_ddp_logging_data(is_gpu=False)
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3625, in _test_ddp_logging_data
Apr 06 06:23:26     self.assertGreaterEqual(ddp_logging_data.backward_compute_comm_overlap_time, 1)
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/unittest/case.py", line 1227, in assertGreaterEqual
Apr 06 06:23:26     self.fail(self._formatMessage(msg, standardMsg))
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Apr 06 06:23:26     raise self.failureException(msg)
Apr 06 06:23:26 AssertionError: 0 not greater than or equal to 1
Apr 06 06:23:26  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Apr 06 06:23:26 ERROR:torch.testing._internal.common_distributed:Caught exception: 
Apr 06 06:23:26 Traceback (most recent call last):
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 440, in run_test
Apr 06 06:23:26     getattr(self, test_name)()
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 323, in wrapper
Apr 06 06:23:26     fn()
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3651, in test_ddp_logging_data_cpu
Apr 06 06:23:26     model_DDP = self._test_ddp_logging_data(is_gpu=False)
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3612, in _test_ddp_logging_data
Apr 06 06:23:26     1,
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 2901, in _test_DDP_helper
Apr 06 06:23:26     l.backward()
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
Apr 06 06:23:26     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
Apr 06 06:23:26   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 148, in backward
Apr 06 06:23:26     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
Apr 06 06:23:26 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.17.0.2]:64134
Apr 06 06:23:26  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Apr 06 06:23:26 Process 0 terminated with exit code 10, terminating remaining processes.
Apr 06 06:23:26 ERROR (0.122s)
Apr 06 06:23:30   test_ddp_logging_data_gpu (__main__.TestDistBackendWithFork) ... ok (4.230s)
Apr 06 06:23:42   test_ddp_model_diff_across_ranks (__main__.TestDistBackendWithFork) ... Process process 1:
Apr 06 06:23:42 Traceback (most recent call last):
Apr 06 06:23:42   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Apr 06 06:23:42     self.run()
Apr 06 06:23:42   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Apr 06 06:23:42     self._target(*self._args, **self._kwargs)
Apr 06 06:23:42   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 432, in _run
Apr 06 06:23:42     self._barrier()
Apr 06 06:23:42   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 446, in _barrier
Apr 06 06:23:42     Barrier.sync(*args, **kwargs)
Apr 06 06:23:42   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 363, in sync
Apr 06 06:23:42     raise RuntimeError("barrier timeout")
Apr 06 06:23:42 RuntimeError: barrier timeout
Apr 06 06:23:42 ok (12.444s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by mrshenli** [comment]
cc @zhaojuanmao
