### ISSUE TITLE
Error building docker image: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by robotrapta** [pytorch/pytorch#55437]
## 🐛 Bug

I'm trying to build a docker image myself follow [these instructions](https://github.com/pytorch/pytorch#building-the-image-yourself) and it's failing with `ModuleNotFoundError typing_extensions`.
 
## To Reproduce

On a clean ubuntu 20.04 machine with the current head 96655e2b81765d94c359a5dc079ec00404244184 I run:

```
git clone https://github.com/pytorch/pytorch
cd pytorch
make -f docker.Makefile
```

and it fails with

```
#24 10.94 INFO CUPTI_INCLUDE_DIR = /usr/local/cuda/include
#24 10.94 -- Configured Kineto
#24 10.94 -- GCC 7.5.0: Adding gcc and gcc_s libs to link line
#24 10.94 -- Performing Test HAS_WERROR_FORMAT
#24 11.02 -- Performing Test HAS_WERROR_FORMAT - Success
#24 11.02 -- Performing Test HAS_WERROR_CAST_FUNCTION_TYPE
#24 11.05 -- Performing Test HAS_WERROR_CAST_FUNCTION_TYPE - Failed
#24 11.05 -- Looking for backtrace
#24 11.11 -- Looking for backtrace - found
#24 11.11 -- backtrace facility detected in default set of libraries
#24 11.11 -- Found Backtrace: /usr/include  
#24 11.11 -- don't use NUMA
#24 11.13 -- Performing Test COMPILER_SUPPORTS_NO_AVX256_SPLIT
#24 11.20 -- Performing Test COMPILER_SUPPORTS_NO_AVX256_SPLIT - Success
#24 11.24 Traceback (most recent call last):
#24 11.24   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
#24 11.24     "__main__", mod_spec)
#24 11.24   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
#24 11.24     exec(code, run_globals)
#24 11.24   File "/opt/pytorch/tools/codegen/gen.py", line 3, in <module>
#24 11.24     from typing_extensions import Literal
#24 11.24 ModuleNotFoundError: No module named 'typing_extensions'
#24 11.24 -- 
#24 11.24 CMake Error at cmake/Codegen.cmake:213 (message):
#24 11.24   Failed to get generated_cpp list
#24 11.24 Call Stack (most recent call first):
#24 11.24   caffe2/CMakeLists.txt:2 (include)
#24 11.24 
#24 11.24 
#24 11.26 -- Configuring incomplete, errors occurred!
```

## Expected behavior

Successfully builds docker image.  If I roll back to 57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57 (1.7.1) this works.

## Environment

 - PyTorch Version (e.g., 1.0): n/a
 - OS (e.g., Linux): Ubuntu 20.04: `Linux ip-172-31-54-78 5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - How you installed PyTorch (`conda`, `pip`, source): have not yet
 - Build command you used (if compiling from source): `make -f docker.Makefile`
 - Python version: docker.Makefile is configured for py3.7
 - CUDA/cuDNN version: none
 - GPU models and configuration: none
 - Any other relevant information: instance is aws c5a.2xl
- Docker version 19.03.8, build afacb8b7f0

## Additional context

My goal in building from source is to get a docker image that I can use with an old GPU per https://github.com/pytorch/pytorch/issues/31285

**Comment by caseybasichis** [comment]
I am also having the same issue building on a fresh machine.

Only deviation from the instructions is I am not running Anaconda.

**Comment by SlowFlight** [comment]
try pip install typing_extensions

**Comment by jianshen92** [comment]
Facing the same

**Comment by tyoc213** [comment]
did `pip install typing_extensions` and did pass, but which step are we skiping as to not have this installed from the instructions?

**Comment by Madouura** [comment]
I also get this, but in nix.
