### ISSUE TITLE
Errors occur when operating broadcast with error log: Got completion with error 12, opcode 1, len 32547, vendor err 129

### ISSUE THREAD

**Issue by zhangwei222** [pytorch/pytorch#55448]
## 🐛 Bug
Errors occur when operating broadcast in pytorch v1.6.1 with nccl v2.7.8 as backend and set NCCL_BLOCKING_WAIT=1. There is 8 gpus in 1 docker and the rank0 broadcast tensor to other rank. Rank0 dump error logs:
```shell
tb2b07342:9298:11152 [0] transport/net_ib.cc:818 NCCL WARN NET/IB : Got completion with error 12, opcode 1, len 32602, vendor err 129
tb2b07342:9298:11152 [0] NCCL INFO include/net.h:28 -> 2
tb2b07342:9298:11152 [0] NCCL INFO transport/net.cc:357 -> 2
tb2b07342:9298:11152 [0] NCCL INFO proxy.cc:198 -> 2 [Proxy Thread]
```
and rank1 dump error logs:
```shell
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/miniconda3/envs/pytorch_esl1.6.0/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/dev/shm/accl_test/pytorch_test/src/btry.py", line 34, in BroadcastWorker
    dist.broadcast(objects, src=0, async_op = False)
  File "/miniconda3/envs/pytorch_esl1.6.0/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 919, in broadcast
    work.wait()
RuntimeError: NCCL error: unhandled system error, NCCL version 2.7.8
```

## Test code
```python
def BroadcastWorker(gpuid, master_ip, master_port):
    dist_url = "tcp://{}:{}".format(master_ip, master_port)
    torch.cuda.set_device(gpuid)
    dist.init_process_group(backend="nccl", init_method=dist_url, world_size=8, rank=gpuid)

    data = list(range(2))
    if dist.get_rank() == 0:
        objects = torch.tensor(data, dtype=torch.int32).cuda()
    else:
        objects = torch.empty(size, dtype=torch.int32).cuda()
    data = torch.tensor(data, dtype=torch.int32)

    dist.broadcast(objects, src=0, async_op = False)

if __name__ == '__main__':
    master_ip=xx.xx.xx.xx
    master_ip=xxxxx
    mp.spawn(BroadcastWorker, nprocs=8, args=(master_ip, master_port))
```

some flowing code can fix this issue like:
1. dist.barrirer() in the end of function BroadcastWorker
2. time.sleep(5) in rank0 after operating broadcast.
3. **NCCL_BLOCKING_WAIT=0**

## Expected behavior

No issue happen and tensor can be broadcast from rank0 to rank1 - rank7

## Environment
 - PyTorch Version (e.g., 1.0):1.6.0
 - OS (e.g., Linux): CentOS 7.2
 - How you installed PyTorch (`conda`, `pip`, source):source
 - Build command you used (if compiling from source):
 ```shell
 USE_DISTRIBUTED=1 USE_LMDB=1 TORCH_NVCC_FLAGS="-Xfatbin -compress-all" BUILD_TEST=0 CMAKE_BUILD_PARALLEL_LEVEL=32 USE_SYSTEM_NCCL=1 USE_FBGEMM=0 python setup.py bdist_wheel
```
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.1.243
 - NCCL version: nccl-repo-rhel7-2.7.8-ga-cuda10.1-1-1.x86_64

**Comment by zhangwei222** [comment]
I have seen the issue [214](https://github.com/NVIDIA/nccl/issues/214) here and all the acsctl settings have been closed in my docker.

**Comment by mrshenli** [comment]
cc oncall @agolynski
