### ISSUE TITLE
Source location range issue for dictionary 

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#55577]
## 🐛 Bug

During our hackathon today, I ran into this weird error highlighting. 
```
import torch
from typing import Dict

@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    return x['dne']

missing_index({'item': 20, 'other_item': 120})
```

This code outputs:
```     
     9 
     10 
---> 11 missing_index({'item': 20, 'other_item': 120})

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<ipython-input-6-f7e8ae85d5ad>", line 8, in missing_index
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    return x['dne']
           ~~~~ <--- HERE
RuntimeError: KeyError: dne
```
I feel like the highlighted range should be either shorter or long enough to highlight the entire statement. 

cc @gmagogsfm

**Comment by Lilyjjo** [comment]
A good place in the codebase to start exploring this would be in `pytorch/torch/csrc/jit/frontend/source_range.cpp`'s `void SourceRange::print_with_context` function, that controls the logic of what is printed

**Comment by darkuswraith** [comment]
Hey,
I would like to contribute to this issue, but I can't seem to figure out what statement needs to be highlighted in the above example. Any tips would be appreciated.
Thanks.

**Comment by Lilyjjo** [comment]
Hi @darkuswraith, yes that is a good question! @gmagogsfm @tugsbayasgalan do y'all have opinions on what should be highlighted when a dictionary has a missing key? I'm not sure of the implementation difficulties/differences of the various options below, but I'd be fine with any of these three highlightings:
A: just the dict variable
```
def missing_index(x: Dict[str, int]) -> int:
    return x['dne']
           ~ <--- HERE
```
B: just the missing key
```
def missing_index(x: Dict[str, int]) -> int:
    return x['dne']
             ~~~~~ <--- HERE
```
C: both the dict variable and the missing key 
```
def missing_index(x: Dict[str, int]) -> int:
    return x['dne']
           ~~~~~~~~ <--- HERE
```

**Comment by gmagogsfm** [comment]
@darkuswraith Thanks for contributing to PyTorch!

IMHO, B seems a better choice. @Lilyjjo could you help @darkuswraith with some implementation pointers and code review?

**Comment by tugsbayasgalan** [comment]
I also think B is better. @Lilyjjo @darkuswraith feel free to tag me on the review as well.

**Comment by darkuswraith** [comment]
Thank you guys for the very prompt and informative replies!
So, from what I understand , I should make it so that the missing key is output in case of an error. So, should I make a separate file that handles this error or should I try and add it to the current code?

**Comment by Lilyjjo** [comment]
I think adding to the current code is the way to go!

Looking into this task a little bit more, we might be missing the logic to highlight the key access into the dict to create the behavior in option B. @tugsbayasgalan's original code variant prints out like the following:
```
    return x['dne']
           ~~~~ <--- HERE
```
But if you change the length of the dict's name the behavior changes:
```
    return xxxxxx['dneeeeee']
           ~~~~~~ <--- HERE
    return xx['dneeeeee']
           ~~ <--- HERE
```
Originally I thought the length of the highlighted function was determined by the length of the key name, but it's actually determined by the length of the dict's name. The output looks funky because we have a logic error that messes up when the dict's name is of length 1. I'm not sure if this is an error where the SourceRange is being set, or an error in the function SourceRange::print_with_context() which prints out the SourceRange. 

Going the route of option B might is more complicated. For the sake of a first issue, I think fixing the current code to print out Option A for the dicts with name length of 1 correctly is more attainable.

I'd go about this task by determining why the SourceRange start()/end() indexes are only wrong for dicts with the name lengths of 1, and then fixing the logic to work for @tugsbayasgalan's example with option A. Check out SourceRange::print_with_context and the SourceRange definition in torch/csrc/jit/frontend/source_range.h as a starting code point.

Solving option A could be a good warmup task for solving option B :)

**Comment by darkuswraith** [comment]
Thanks! I'll work on this.

**Comment by SabbirAhmedAdor629** [comment]
> ## 🐛 Bug
> During our hackathon today, I ran into this weird error highlighting.
> 
> ```
> import torch
> from typing import Dict
> 
> @torch.jit.script
> def missing_index(x: Dict[str, int]) -> int:
>     return x['dne']
> 
> missing_index({'item': 20, 'other_item': 120})
> ```
> 
> This code outputs:
> 
> ```
>      9 
>      10 
> ---> 11 missing_index({'item': 20, 'other_item': 120})
> 
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
>   File "<ipython-input-6-f7e8ae85d5ad>", line 8, in missing_index
> @torch.jit.script
> def missing_index(x: Dict[str, int]) -> int:
>     return x['dne']
>            ~~~~ <--- HERE
> RuntimeError: KeyError: dne
> ```
> 
> I feel like the highlighted range should be either shorter or long enough to highlight the entire statement.
> 
> cc @gmagogsfm

Hi, I want to work on this. Is it still available

**Comment by Lilyjjo** [comment]
Hi @SabbirAhmedAdor629! I think @darkuswraith is currently working on this. If you keep on checking the `OSS contribution wanted' label our team is starting to add to it more regularly and there will be more issues up for grab

**Comment by tugsbayasgalan** [comment]
Hi @SabbirAhmedAdor629, if you are looking for more issues, you can start with this issue too (https://github.com/pytorch/pytorch/issues/56909).

**Comment by SabbirAhmedAdor629** [comment]
> Hi @SabbirAhmedAdor629, if you are looking for more issues, you can start with this issue too (https://github.com/pytorch/pytorch/issues/56909). 

Thanks mate

**Comment by Anupam-USP** [comment]
Is this issue still open? I can try some changes in logic but I wanted to know how to check the same, get the above error for it so that I can recheck? Any way?

**Comment by Joymfl** [comment]
> Is this issue still open? I can try some changes in logic but I wanted to know how to check the same, get the above error for it so that I can recheck? Any way?
> 

Hey, I tried working on this issue and made no headway, I don't know how to remove myself from being assigned to it but I'll do so,. If you want to pick it up. Cheers.

**Comment by Lilyjjo** [comment]
@Joymfl thanks for trying it out! If you see any other issues you want to try feel free to comment on them! It can be a little difficult at first to get into the codebase.

@Anupam-USP Feel free to try it out! To develop on PyTorch we have a guide [here](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md) with directions on how to setup an environment to develop with. After you've done those steps, you should be able to run the original code example as a python script and the error message should match

**Comment by Anupam-USP** [comment]
I am using M1 mac, I think you have sent me setup of windows?

**Comment by Lilyjjo** [comment]
@Anupam-USP, the setup guide does include Mac instructions! I recommend reading most of the content in the links, they have a lot of useful information scattered around

**Comment by aaditya-panik** [comment]
> I think adding to the current code is the way to go!
> 
> Looking into this task a little bit more, we might be missing the logic to highlight the key access into the dict to create the behavior in option B. @tugsbayasgalan's original code variant prints out like the following:
> 
> ```
>     return x['dne']
>            ~~~~ <--- HERE
> ```
> 
> But if you change the length of the dict's name the behavior changes:
> 
> ```
>     return xxxxxx['dneeeeee']
>            ~~~~~~ <--- HERE
>     return xx['dneeeeee']
>            ~~ <--- HERE
> ```
> 
> Originally I thought the length of the highlighted function was determined by the length of the key name, but it's actually determined by the length of the dict's name. The output looks funky because we have a logic error that messes up when the dict's name is of length 1. I'm not sure if this is an error where the SourceRange is being set, or an error in the function SourceRange::print_with_context() which prints out the SourceRange.
> 
> Going the route of option B might is more complicated. For the sake of a first issue, I think fixing the current code to print out Option A for the dicts with name length of 1 correctly is more attainable.
> 
> I'd go about this task by determining why the SourceRange start()/end() indexes are only wrong for dicts with the name lengths of 1, and then fixing the logic to work for @tugsbayasgalan's example with option A. Check out SourceRange::print_with_context and the SourceRange definition in torch/csrc/jit/frontend/source_range.h as a starting code point.
> 
> Solving option A could be a good warmup task for solving option B :)

I'm not sure this is the case, I tried recreating this error. But the highlighting logic is the same (seems to cover the name of the dictionary variable + 3, strangely).
The example provided in the original post:
```
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    return x["dne"]
           ~~~~ <--- HERE
RuntimeError: KeyError: dne
```
Another example with `xyz` as the name of the variable:
```
@torch.jit.script
def missing_index(xyz: Dict[str, int]) -> int:
    return xyz["dne"]
           ~~~~~~ <--- HERE
RuntimeError: KeyError: dne
```
And a different key name:
```
@torch.jit.script
def missing_index(xyz: Dict[str, int]) -> int:
    return xyz["does_not_exist"]
           ~~~~~~ <--- HERE
RuntimeError: KeyError: does_not_exist
```
What I found odd about this is the static length of the key string literal. For some reason, the SourceRange of the string literal is fixed for any length it may be. I think this part of the code is the culprit:

https://github.com/pytorch/pytorch/blob/3d70ab08ae58b1cf12c09e12729c61d3e850f739/torch/jit/frontend.py#L982-L986

Maybe it should be `r = ctx.make_range(expr.lineno, expr.col_offset, expr.col_offset + len(value) + 1)` so that the source range captures the entire string literal (key in this case), but maybe it was written like this by design. With this change however, the highlight for the above examples change to:
The example provided in the original post:
```
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    return x["dne"]
           ~~~~~~~ <--- HERE
RuntimeError: KeyError: dne
```
Another example with `xyz` as the name of the variable:
```
@torch.jit.script
def missing_index(xyz: Dict[str, int]) -> int:
    return xyz["dne"]
           ~~~~~~~~~ <--- HERE
RuntimeError: KeyError: dne
```
And a different key name:
```
@torch.jit.script
def missing_index(xyz: Dict[str, int]) -> int:
    return xyz["does_not_exist"]
           ~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: KeyError: does_not_exist
```

**Comment by Anupam-USP** [comment]
Hey @Lilyjjo, as you shared some links I have tried setting up the local environment as [this](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#c-frontend-development-tips), but always got hardware integration problems! Is there any other way to check my logic or should I open the PR and you will check it?

**Comment by kishansairam9** [comment]
Issue only occurs with string as key and doesn't with keys as integers
```
@torch.jit.script
def missing_index(xxx: Dict[int, int]) -> int:
    return xxx[123]
           ~~~~~~~~ <--- HERE
RuntimeError: KeyError: 123
```
I second @aaditya-panik's analysis. (Tested on master)
- `ctx.make_range(expr.lineno, expr.col_offset, expr.col_offset + 1)` was used not only in build for Strings, it is also used for List, Tuple, Dict, JoinedStr
- `offset+1` is correct for List, Dict, Tuple because variables enclosed in braces for each of them account for appropriate ranges. But using it in case of string would cause range issues
- In case of `List[int]`, `Tuple[int]`, `Dict[int, int]` we won't run into source location misrepresentation because int variables accumulates of number of digits in range appropriately
https://github.com/pytorch/pytorch/blob/3d70ab08ae58b1cf12c09e12729c61d3e850f739/torch/jit/frontend.py#L962

Bug in build_Str's range not accounting for length we face issues with `List[str], Tuple[str], Dict[str, int], Dict[str, str]`

A fix should target both [build_Str](https://github.com/pytorch/pytorch/blob/3d70ab08ae58b1cf12c09e12729c61d3e850f739/torch/jit/frontend.py#L983) and [build_JoinedStr](https://github.com/pytorch/pytorch/blob/3d70ab08ae58b1cf12c09e12729c61d3e850f739/torch/jit/frontend.py#L989) (which also uses [offset+1](https://github.com/pytorch/pytorch/blob/3d70ab08ae58b1cf12c09e12729c61d3e850f739/torch/jit/frontend.py#L993))

**Comment by narang99** [comment]
> Hey @Lilyjjo, as you shared some links I have tried setting up the local environment as [this](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#c-frontend-development-tips), but always got hardware integration problems! Is there any other way to check my logic or should I open the PR and you will check it?

Hey if you have any problems building cpp projects in M1 Macs, I would suggest running your terminal with Rosetta and then building. I don't know the details or if this would solve the issue, but it normally solves for me in C++ projects

**Comment by lg20987** [comment]
Hi, I'd like to contribute to this issue. Please assign it to me. Thanks

**Comment by lg20987** [comment]
I am able to reproduce the error. The same behavior applies regardless of the length of the dictionary name or that of the key. To recap the original error:
```
Traceback (most recent call last):
  File "../../test.py", line 10, in <module>
    missing_index({'item': 20, 'other_item': 120})
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "../../test.py", line 7, in missing_index
def missing_index(x: Dict[str, int]) -> int:
    # assert 1 == 2
    res = x['dne']
          ~~~~ <--- HERE
    return res
RuntimeError: KeyError: dne
```
It's caused by the `end()` attribute of `SourceRange` early terminated at letter 'd':
```python
out << source_->text().substr(start(), end() - start()) << "\n";
```
The above will print `x['d` instead of `x['dne']` -- that is, the full segment of code where the error is triggered.

The function `SourceRange::print_with_context` is implemented algorithmically correct but the python source code is not sliced correctly by `end()` on which other position variables in that function depend on. 

Per the constructor `end_` is passed as an argument:
```python
struct TORCH_API SourceRange {
  SourceRange(std::shared_ptr<Source> source_, size_t start_, size_t end_)
      : source_(std::move(source_)), start_(start_), end_(end_) {}
}
```
and the only caller script that initializes `SourceRange` is `torch/csrc/jit/runtime/interpreter.cpp` and here is the caller stack (omitting the module namespace):
```
InterpreterStateImpl constructor
runImpl
handleError
formatStackTrace
callstack
```
Where `callstack()` returns a vector of `StackEntry` (a wrapper struct of `SourceRange` but in the same spirit) objects initialized by `frame.function->instructions_source_[pc]`.

Beyond that it's hard to trace further as the codes get thicker. I think the initialization of `SourceRange` happens when the `frame` object is created -- perhaps we should examine the details there. Would appreciate further clues!

(Also noticed that this bug does not occur for other types of error such as:
```python
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    assert 1 == 2
    res = x['dne']
    return res

missing_index({'item': 20, 'other_item': 120})
```
The above will yield:
```
Traceback (most recent call last):
  File "../../test.py", line 10, in <module>
    missing_index({'item': 20, 'other_item': 120})
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "../../test.py", line 6, in missing_index
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    assert 1 == 2
    ~~~~~~~~~~~~~ <--- HERE
    res = x['dne']
    return res
RuntimeError: AssertionError: 
```
)

**Comment by malfet** [comment]
@lg20987 please check if AST representation (and source attribution) is correct in https://github.com/pytorch/pytorch/blob/bdf439a95869582861bc54e7bfb7dedc29382bda/torch/jit/frontend.py#L254

**Comment by lg20987** [comment]
@malfet `get_jit_def` invokes a recursive build of the body of the python function bottom-up from elementary units (or leaf-nodes) (e.g., number, string), compounded units (e.g., function call, subscript) up to statements (e.g., lines starting with keywords `if`, `return`, `raise`). 

An instance of `SourceRange` is created for each leaf-node with its `col_offset` and length as consistently seen across several such builders. So `build_Str` was incorrect in hardcoding the end offset as '+1':

https://github.com/pytorch/pytorch/blob/d6899fe492076885d2dfb547cd93994dcbfeb87b/torch/jit/frontend.py#L985

Changing that to (the '+2' is trivial to account for the quotes around it):

`        r = ctx.make_range(expr.lineno, expr.col_offset, expr.col_offset + len(value) + 2)
`
The highlight will reach the closing bracket now:
```
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    return x['dne']
           ~~~~~~~~ <--- HERE
RuntimeError: KeyError: dne
```
But **unclear** to me is whether/how `SourceRange` gets created for non-leaf nodes where `SourceRangeFactory` is not explicitly triggered. If we let the error come from a `raise` statement instead of `x['dne']` (in `torch/jit/frontend.py` statements and subscripts come from  different builders):
```python
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    raise Exception('dne')
```
The highlight will miss the closing bracket:
```
@torch.jit.script
def missing_index(x: Dict[str, int]) -> int:
    raise Exception('dne')
    ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

Checking on the factory `SourceRangeFactory::create` (`torch/csrc/jit/python/python_tree_views.cpp`):
```cpp
std::cout << "SourceRange Factory: "
              << source_->text().substr(
                     start_byte_offset, end_byte_offset - start_byte_offset)
              << "\n";
```
Everything seems to be correct at the leaf-nodes
```
SourceRange Factory: raise
SourceRange Factory: Exception
SourceRange Factory: 'dne'
```

**Comment by pranav1610** [comment]
Hello @tugsbayasgalan and @Lilyjjo, I would love to work on this issue. Is it available to assign?

**Comment by langong347** [comment]
Sorry that I have reopened this issue. Originally, I tested modifying the end index of `build_Str` from `+1` to `len(value) + 1` and fixed the highlight for the dictionary case `x["dne"]`. However, the highlight is still off by one character when you raise an exception. For example, step into [this test](https://github.com/pytorch/pytorch/blob/3b4cb9ddca1cc2b92277541ff781730042bee3c5/test/test_jit.py#L5773-L5782) will show you what the AST actually gets for the highlighted range:

```
(Pdb) ast.range()
  File "/Users/langong/local/pytorch/test/test_jit.py", line 5774
        def fn():
        ~~~~~~~~~
            raise Exception("hello")
            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```
The last quotation should be included as in the case with `x["dne"]`.
Please advise, thanks.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
