### ISSUE TITLE
[ONNX] Incorrect handling of tuple multiplication with zero

### ISSUE THREAD

**Issue by shubhambhokare1** [pytorch/pytorch#55597]
## 🐛 Bug

Opening this issue based on ONNXRuntime issue https://github.com/microsoft/onnxruntime/issues/7098 as issue is relevant to exporter and not ONNXRuntime

Currently, cases in which two tuples are mutliplied is handled incorrectly in ONNX export
For example in ```x.shape[:1] + (1, ) * (len(x.shape) - 2) + x.shape[-1:])``` and ```len(x.shape) = 2``` we get a scenario where
 ```(1,)*0=()```, but exporter treats it as [0], causing shape mismatch in the Mul operator

## To Reproduce

Model code to reproduce error
```
import onnxruntime
from torch import nn
import torch

print(torch.__version__)

@torch.jit.script
def compute_output_lengths(x, lengths_fraction):
    return (lengths_fraction * x.shape[-1]).ceil().long()

@torch.jit.script
def temporal_mask(x, lengths):
    tup_prod = (1,) * (len(x.shape) - 2)
    return (torch.arange(x.shape[-1], dtype=lengths.dtype).unsqueeze(0) <
            lengths.unsqueeze(1)).view(x.shape[:1] + tup_prod + x.shape[-1:])

class Model(nn.Module):
    def forward(self, x, xlen):
        l = compute_output_lengths(x, xlen)
        tm = temporal_mask(x, l)
        return x * tm

model = Model()

x = torch.rand(2, 10)
xlen = torch.rand(2)

print(model(x, xlen))

torch.onnx.export(
        model, (x, xlen),
        'fp32_jit_prim_dtype_repro.onnx',
        verbose=True,
        opset_version=14,
        input_names=['x', 'xlen']
)

runtime = onnxruntime.InferenceSession('fp32_jit_prim_dtype_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy(), xlen=xlen.cpu().numpy())))
```

## Expected behavior

Inference without ONNXRuntimeError

**Comment by vadimkantorov** [comment]
(also mentioned in https://github.com/pytorch/pytorch/issues/54532)

**Comment by spandantiwari** [comment]
We will take a look.

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1650135>

**Comment by thiagocrepaldi** [comment]
The repro
```python
import onnxruntime
from torch import nn
import torch

print(torch.__version__)

@torch.jit.script
def compute_output_lengths(x, lengths_fraction):
    return (lengths_fraction * x.shape[-1]).ceil().long()

@torch.jit.script
def temporal_mask(x, lengths):
    tup_prod = (1,) * (len(x.shape) - 2)
    return (torch.arange(x.shape[-1], dtype=lengths.dtype).unsqueeze(0) <
            lengths.unsqueeze(1)).view(x.shape[:1] + tup_prod + x.shape[-1:])

class Model(nn.Module):
    def forward(self, x, xlen):
        l = compute_output_lengths(x, xlen)
        tm = temporal_mask(x, l)
        return x * tm

model = Model()

x = torch.rand(2, 10)
xlen = torch.rand(2)

print(model(x, xlen))

torch.onnx.export(
        model, (x, xlen),
        'fp32_jit_prim_dtype_repro.onnx',
        verbose=True,
        opset_version=16,
        input_names=['x', 'xlen']
)

runtime = onnxruntime.InferenceSession('fp32_jit_prim_dtype_repro.onnx', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
print(runtime.run(None, dict(x=x.cpu().numpy(), xlen=xlen.cpu().numpy())))

````
Produces the following error on latest torch/ort

```bash
1.14.0a0+gitba4d5aa
tensor([[0.4040, 0.5623, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3882, 0.3568, 0.8019, 0.2298, 0.9562, 0.6483, 0.0000, 0.0000, 0.0000,
         0.0000]])
Exported graph: graph(%x : Float(2, 10, strides=[10, 1], requires_grad=0, device=cpu),
      %xlen : Float(2, strides=[1], requires_grad=0, device=cpu)):
  %onnx::Mul_2 : Float(requires_grad=0, device=cpu) = onnx::Constant[value={10}]() # /home/thiagofc/dev/pytorch_repros/missing_complex.py:9:12
  %onnx::Ceil_3 : Float(2, strides=[1], device=cpu) = onnx::Mul(%xlen, %onnx::Mul_2) # /home/thiagofc/dev/pytorch_repros/missing_complex.py:9:12
  %onnx::Cast_4 : Float(2, strides=[1], device=cpu) = onnx::Ceil(%onnx::Ceil_3) # /home/thiagofc/dev/pytorch_repros/missing_complex.py:9:12
  %onnx::Unsqueeze_5 : Long(2, strides=[1], device=cpu) = onnx::Cast[to=7](%onnx::Cast_4) # /home/thiagofc/dev/pytorch_repros/missing_complex.py:9:12
  %onnx::Unsqueeze_6 : Long(1, strides=[1], device=cpu) = onnx::Constant[value={1}]() # /home/thiagofc/dev/pytorch_repros/missing_complex.py:15:12
  %onnx::Less_7 : Long(2, 1, strides=[1, 1], device=cpu) = onnx::Unsqueeze(%onnx::Unsqueeze_5, %onnx::Unsqueeze_6) # /home/thiagofc/dev/pytorch_repros/missing_complex.py:15:12
  %onnx::Less_8 : Long(1, 10, strides=[10, 1], requires_grad=0, device=cpu) = onnx::Constant[value= 0  1  2  3  4  5  6  7  8  9 [ CPULongType{1,10} ]]() # /home/thiagofc/dev/pytorch_repros/missing_complex.py:14:12
  %onnx::Reshape_9 : Bool(2, 10, strides=[10, 1], device=cpu) = onnx::Less(%onnx::Less_8, %onnx::Less_7) # /home/thiagofc/dev/pytorch_repros/missing_complex.py:14:12
  %onnx::Reshape_10 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= 12  10 [ CPULongType{2} ]]() # /home/thiagofc/dev/pytorch_repros/missing_complex.py:14:12
  %onnx::Cast_11 : Bool(12, 10, strides=[10, 1], device=cpu) = onnx::Reshape[allowzero=0](%onnx::Reshape_9, %onnx::Reshape_10) # /home/thiagofc/dev/pytorch_repros/missing_complex.py:14:12
  %/Cast_output_0 : Float(12, 10, strides=[10, 1], device=cpu) = onnx::Cast[to=1, onnx_name="/Cast"](%onnx::Cast_11), scope: __main__.Model:: # /home/thiagofc/dev/pytorch_repros/missing_complex.py:21:0
  %13 : Float(12, 10, strides=[10, 1], requires_grad=0, device=cpu) = onnx::Mul[onnx_name="/Mul"](%x, %/Cast_output_0), scope: __main__.Model:: # /home/thiagofc/dev/pytorch_repros/missing_complex.py:21:0
  return (%13)

Traceback (most recent call last):
  File "/home/thiagofc/dev/pytorch_repros/missing_complex.py", line 38, in <module>
    runtime = onnxruntime.InferenceSession('fp32_jit_prim_dtype_repro.onnx', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
  File "/home/thiagofc/dev/github/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thiagofc/dev/github/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from fp32_jit_prim_dtype_repro.onnx failed:Node (/Mul) Op (Mul) [ShapeInferenceError] Incompatible dimensions
```

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
