### ISSUE TITLE
RuntimeError: "max_cuda" not implemented for 'ComplexFloat'

### ISSUE THREAD

**Issue by momo1986** [pytorch/pytorch#55661]
#To Reproduce

After do torch.fft.fft
Here is the implementation code:
` m1,_ = torch.max(absFxri,2)`

Error-log:

Traceback (most recent call last):
  File "train_cifar.py", line 1018, in <module>
    main()
  File "train_cifar.py", line 780, in main
    fast_better=args.fast_better, BNeval=args.BNeval)
  File "train_cifar.py", line 252, in attack_pgd
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "train_cifar.py", line 48, in backward
    m1,_ = torch.max(absFxri,2)
RuntimeError: "max_cuda" not implemented for 'ComplexFloat'

Expected behavior

I think PyTorch should support torch.max() on ComplexFloatTensor.

Environment

Collecting environment information...
PyTorch version: 1.8.0a0+17f8c32
Is debug build: True
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 455.38
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.8.0a0+17f8c32
[pip3] torchtext==0.8.0a0
[pip3] torchvision==0.8.0a0
[conda] magma-cuda110 2.5.2 5 local
[conda] mkl 2019.1 144
[conda] mkl-include 2019.1 144
[conda] nomkl 3.0 0
[conda] numpy 1.19.2 py36h6163131_0
[conda] numpy-base 1.19.2 py36h75fe3a5_0
[conda] pytorch-transformers 1.1.0 pypi_0 pypi
[conda] torch 1.8.0a0+17f8c32 pypi_0 pypi
[conda] torchtext 0.8.0a0 pypi_0 pypi
[conda] torchvision 0.8.0a0 pypi_0 pypi

Additional context

If this issue has been resolved, could you give the explicit version of new PyTorch?

Thanks & Regards!
Momo

**Comment by kshitij12345** [comment]
Some context https://github.com/pytorch/pytorch/issues/36444

**Comment by momo1986** [comment]
Hi, @kshitij12345 , it looks like that support for min/max on the absolute value is in the plan.

In which release, would this feature be stable?

Thanks & Regards!
Momo

**Comment by kshitij12345** [comment]
Sorry, but I don't have any idea about the same.
@anjali411 can shed more light.

**Comment by gchanan** [comment]
> t looks like that support for min/max on the absolute value is in the plan.

I don't think that is an accurate reading of that discussion, a couple of people suggest that but it's not codified as a plan.

**Comment by mruberry** [comment]
Let's let @anjali411, our area expert, comment.

If we don't intend to support max for complex values then this is a good opportunity to improve the error message.

**Comment by momo1986** [comment]
Therefore, what should be the expected behavior?
For example, user should explicitly calculate the module value of the complex number and do the comparison?
Maybe we should give a clear clarification.
Thanks & Regards!

**Comment by mruberry** [comment]
> Therefore, what should be the expected behavior?
> For example, user should explicitly calculate the module value of the complex number and do the comparison?
> Maybe we should give a clear clarification.
> Thanks & Regards!

In PyTorch we don't let our operations compare complex numbers directly because complex numbers aren't part of an totally ordered field, so how to compare them is not obvious.

One idea would be to take their absolute value and compare their magnitudes:

```
t = torch.tensor((complex(1, 2), complex(3, 4), complex(-5, 2), complex(-2, 7)))
: tensor([ 1.+2.j,  3.+4.j, -5.+2.j, -2.+7.j])

value, index = torch.max(t.abs(), dim=0)
t[index]
: tensor(-2.+7.j)
```

In this case the indices return from max are used in the original tensor to select the element with greatest absolute value.

What kind of maximum were you thinking of applying to the complex values, @momo1986?
```

**Comment by gchanan** [comment]
> If we don't intend to support max for complex values then this is a good opportunity to improve the error message.

We can improve the error message even before we decide!  E.g. just say something like "it's not obvious, we haven't decided yet.  If you want to compare magnitudes, use this.  If you want numpy-style, use this"
