### ISSUE TITLE
Cuda OOM after several steps for DataParallel model

### ISSUE THREAD

**Issue by kventinel** [pytorch/pytorch#55756]
## 🐛 Bug

Code Example:
https://pastebin.com/cWNZAP06

This script run on 2 gpus make several steps:
```
max allocated memory on step 1: 8237874176
max allocated memory on step 2: 9265800192
max allocated memory on step 3: 9265800192
```

And then fault with cuda oom:
```
Traceback (most recent call last):
  File "/home/lollypop/docker_data/data_parallel_test/./main.py", line 263, in <module>
    train()
  File "/home/lollypop/docker_data/data_parallel_test/./main.py", line 254, in train
    loss.backward()
  File "/usr/local/lib/python3.9/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/checkpoint.py", line 112, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 1; 10.76 GiB total capacity; 7.21 GiB already allocated; 267.06 MiB free; 7.86 GiB reserved in total by PyTorch)
```

## To Reproduce

1. Pytorch '1.8.1+cu111'
1. Run on machine with 2 gpus geforce 2080 ti

## Expected behavior

OOM after first step (or maybe second, but not after third), because i think, that all variables already allocated after first 2 steps

## Environment

Run in docker: https://github.com/kventinel/docker_images/blob/master/default/Dockerfile

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by kventinel** [comment]
This case can be fixed by add `gc.collect()` between `del ...` and `torch.cuda.empty_cache()`.

**Comment by ptrblck** [comment]
Thanks for raising this issue @kventinel!
Could you post the code here as a follow-up or as a Gist, as I cannot access pastebin, please?

**Comment by ngimel** [comment]
@ptrblck here's code from pastebin
<details><summary>code</summary>
<p>

```
#!/usr/bin/env python3
import torch
from torch import nn, einsum
import torch.nn.functional as F
import torch.utils.checkpoint

from einops import rearrange
from einops.layers.torch import Rearrange

# helper functions

def exists(val):
    return val is not None

def default(val, d):
    return val if exists(val) else d

def calc_same_padding(kernel_size):
    pad = kernel_size // 2
    return (pad, pad - (kernel_size + 1) % 2)

# helper classes

class Swish(nn.Module):
    def forward(self, x):
        return x * x.sigmoid()

class GLU(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, x):
        out, gate = x.chunk(2, dim=self.dim)
        return out * gate.sigmoid()

class DepthWiseConv1d(nn.Module):
    def __init__(self, chan_in, chan_out, kernel_size, padding):
        super().__init__()
        self.padding = padding
        self.conv = nn.Conv1d(chan_in, chan_out, kernel_size, groups = chan_in)

    def forward(self, x):
        x = F.pad(x, self.padding)
        return self.conv(x)

# attention, feedforward, and conv module

class Scale(nn.Module):
    def __init__(self, scale, fn):
        super().__init__()
        self.fn = fn
        self.scale = scale

    def forward(self, x, **kwargs):
        return self.fn(x, **kwargs) * self.scale

class PreNorm(nn.Module):
    def __init__(self, dim, fn):
        super().__init__()
        self.fn = fn
        self.norm = nn.LayerNorm(dim)

    def forward(self, x, **kwargs):
        x = self.norm(x)
        return self.fn(x, **kwargs)

class Attention(nn.Module):
    def __init__(
        self,
        dim,
        heads = 8,
        dim_head = 64,
        dropout = 0.,
        max_pos_emb = 512
    ):
        super().__init__()
        inner_dim = dim_head * heads
        self.heads= heads
        self.scale = dim_head ** -0.5
        self.to_q = nn.Linear(dim, inner_dim, bias = False)
        self.to_kv = nn.Linear(dim, inner_dim * 2, bias = False)
        self.to_out = nn.Linear(inner_dim, dim)

        self.max_pos_emb = max_pos_emb
        self.rel_pos_emb = nn.Embedding(2 * max_pos_emb + 1, dim_head)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x, context = None, mask = None, context_mask = None):
        n, device, h, max_pos_emb, has_context = x.shape[-2], x.device, self.heads, self.max_pos_emb, exists(context)
        context = default(context, x)

        q, k, v = (self.to_q(x), *self.to_kv(context).chunk(2, dim = -1))
        q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h = h), (q, k, v))

        dots = einsum('b h i d, b h j d -> b h i j', q, k) * self.scale

        # shaw's relative positional embedding
        seq = torch.arange(n, device = device)
        dist = rearrange(seq, 'i -> i ()') - rearrange(seq, 'j -> () j')
        dist = dist.clip(-max_pos_emb, max_pos_emb) + max_pos_emb
        rel_pos_emb = self.rel_pos_emb(dist).to(q)
        pos_attn = einsum('b h n d, n r d -> b h n r', q, rel_pos_emb) * self.scale
        dots = dots + pos_attn

        if exists(mask) or exists(context_mask):
            mask = default(mask, lambda: torch.ones(*x.shape[:2], device = device))
            context_mask = default(context_mask, mask) if not has_context else default(context_mask, lambda: torch.ones(*context.shape[:2], device = device))
            mask_value = -torch.finfo(dots.dtype).max
            mask = rearrange(mask, 'b i -> b () i ()') * rearrange(context_mask, 'b j -> b () () j')
            dots.masked_fill_(~mask, mask_value)

        attn = dots.softmax(dim = -1)

        out = einsum('b h i j, b h j d -> b h i d', attn, v)
        out = rearrange(out, 'b h n d -> b n (h d)')
        out = self.to_out(out)
        return self.dropout(out)

class FeedForward(nn.Module):
    def __init__(
        self,
        dim,
        mult = 4,
        dropout = 0.
    ):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, dim * mult),
            Swish(),
            nn.Dropout(dropout),
            nn.Linear(dim * mult, dim),
            nn.Dropout(dropout)
        )

    def forward(self, x):
        return self.net(x)

class ConformerConvModule(nn.Module):
    def __init__(
        self,
        dim,
        causal = False,
        expansion_factor = 2,
        kernel_size = 31,
        dropout = 0.):
        super().__init__()

        inner_dim = dim * expansion_factor
        padding = calc_same_padding(kernel_size) if not causal else (kernel_size - 1, 0)

        self.net = nn.Sequential(
            nn.LayerNorm(dim),
            Rearrange('b n c -> b c n'),
            nn.Conv1d(dim, inner_dim * 2, 1),
            GLU(dim=1),
            DepthWiseConv1d(inner_dim, inner_dim, kernel_size = kernel_size, padding = padding),
            nn.BatchNorm1d(inner_dim) if not causal else nn.Identity(),
            Swish(),
            nn.Conv1d(inner_dim, dim, 1),
            Rearrange('b c n -> b n c'),
            nn.Dropout(dropout)
        )

    def forward(self, x):
        return self.net(x)

# Conformer Block

class ConformerBlock(nn.Module):
    def __init__(
        self,
        *,
        dim,
        dim_head = 64,
        heads = 8,
        ff_mult = 4,
        conv_expansion_factor = 2,
        conv_kernel_size = 31,
        attn_dropout = 0.,
        ff_dropout = 0.,
        conv_dropout = 0.,
        max_pos_emb = 512
    ):
        super().__init__()
        self.ff1 = FeedForward(dim = dim, mult = ff_mult, dropout = ff_dropout)
        self.attn = Attention(dim = dim, dim_head = dim_head, heads = heads, dropout = attn_dropout, max_pos_emb = max_pos_emb)
        self.conv = ConformerConvModule(dim = dim, causal = False, expansion_factor = conv_expansion_factor, kernel_size = conv_kernel_size, dropout = conv_dropout)
        self.ff2 = FeedForward(dim = dim, mult = ff_mult, dropout = ff_dropout)

        self.attn = PreNorm(dim, self.attn)
        self.ff1 = Scale(0.5, PreNorm(dim, self.ff1))
        self.ff2 = Scale(0.5, PreNorm(dim, self.ff2))

        self.post_norm = nn.LayerNorm(dim)

    def forward(self, x, mask = None):
        x = self.ff1(x) + x
        x = self.attn(x, mask = mask) + x
        x = self.conv(x) + x
        x = self.ff2(x) + x
        x = self.post_norm(x)
        return x


class Conformer(nn.Module):
    def __init__(self):
        super().__init__()
        layers = 17
        dim = 512
        heads = 8
        self._segments = 19
        self._subsample = nn.Sequential(
            nn.Conv1d(80, dim, kernel_size=3, padding=1, stride=2),
            nn.ReLU(),
            nn.Conv1d(dim, dim, kernel_size=3, padding=1, stride=2),
            nn.ReLU()
        )
        ll = []
        ll.append(nn.Linear(dim, dim))
        ll.append(nn.Dropout(0.1))
        for layer in range(layers):
            ll.append(ConformerBlock(
                dim=dim, heads=heads, attn_dropout=0.1, ff_dropout=0.1, conv_dropout=0.1, max_pos_emb=100
            ))
        self._net = nn.Sequential(*ll)
        self._conv = nn.Sequential(
            nn.Conv1d(dim, 64, 9, padding=4),
            nn.ReLU(),
            nn.MaxPool1d(2)
        )
        self._dense = nn.Linear(64 * 37, 1)

    def forward(self, X):
        subsample = self._subsample.forward(X)
        emb = torch.utils.checkpoint.checkpoint_sequential(self._net, self._segments, subsample.permute(0, 2, 1))
        conv = self._conv.forward(emb.permute(0, 2, 1))
        return self._dense.forward(conv.reshape(X.shape[0], -1))


def train():
    device = 'cuda:0'
    batch_size = 1024
    model = Conformer()
    model = nn.DataParallel(model)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters())
    for i in range(100):
        tensor = torch.rand((batch_size, 80, 299), device=device)
        target = torch.rand((batch_size, 1), device=device)
        pred = model.forward(tensor)
        loss = F.binary_cross_entropy_with_logits(pred, target)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        del tensor, target, pred
        torch.cuda.empty_cache()
        print(f'max allocated memory on step {i + 1}: {torch.cuda.max_memory_allocated(device)}')


if __name__ == '__main__':
    train()
```
</p>
</details>

**Comment by ptrblck** [comment]
Thanks for the code @ngimel!

A quick check points to the usage of `torch.utils.checkpoint` in the `nn.DataParallel` model (and maybe in combination with the usage of `torch.cuda.empty_cache()`).
I don't know, if checkpointing a `nn.DataParallel` model (or any model) is expected to create an additional bump in the memory usage or what the general support is.

Output of the original code snippet:
```
max allocated memory on step 1: 8980636160
max allocated memory on step 2: 10242334720 # !!!
max allocated memory on step 3: 10242334720
max allocated memory on step 4: 10242334720
max allocated memory on step 5: 10273701888 # !!!
max allocated memory on step 6: 10273701888
max allocated memory on step 7: 10273701888
max allocated memory on step 8: 10273701888
max allocated memory on step 9: 10273701888
max allocated memory on step 10: 10273701888
max allocated memory on step 11: 10273701888
max allocated memory on step 12: 10273701888
max allocated memory on step 13: 10273701888
max allocated memory on step 14: 10273701888
max allocated memory on step 15: 10273701888
max allocated memory on step 16: 10273701888
```
Output without checkpointing:
```
max allocated memory on step 1: 21129135104
max allocated memory on step 2: 22573904896 # !!!
max allocated memory on step 3: 22573904896
max allocated memory on step 4: 22573904896
max allocated memory on step 5: 22573904896
max allocated memory on step 6: 22573904896
max allocated memory on step 7: 22573904896
max allocated memory on step 8: 22573904896
max allocated memory on step 9: 22573904896
max allocated memory on step 10: 22573904896
max allocated memory on step 11: 22573904896
max allocated memory on step 12: 22573904896
max allocated memory on step 13: 22573904896
max allocated memory on step 14: 22573904896
max allocated memory on step 15: 22573904896
```
The first increase could be explained by Python's function scoping and potentially more active tensors in the second iteration, while I cannot explain the second increase in the checkpointing usage.

Also note, that your devices would have an imbalanced memory usage (GPU1 was using ~50% of memory compared to GPU0 using your code), which is why we generally recommend to use `DistributedDataParallel`. However, since https://github.com/pytorch/pytorch/issues/24005 is not implemented yet, you could try to use the suggested approaches in the feature request. 

I would also not recommend to call the `forward` methods directly, as they would skip all hooks, and the usage of `torch.cuda.empty_cache()` should only slow down your code and would be needed, if you want to free memory for other applications.

@ngimel do you know, if DP + checkpointing is fully supported or do you remember any similar issues in the past?

**Comment by ngimel** [comment]
Sorry, I don't know about DP + checkpointing. 
@kventinel is it possible for you to switch to DDP? DP is not recommended for parallel training and is not actively maintained.

**Comment by kventinel** [comment]
> GPU1 was using ~50% of memory compared to GPU0 using your code

May be you know, why here so big difference in mem on gpu0 and gpu1? Because it doesn't seem to be the way it should be: input and output of model comparatively small (https://medium.com/huggingface/training-larger-batches-practical-tips-on-1-gpu-multi-gpu-distributed-setups-ec88c3e51255)
