### ISSUE TITLE
matmul on CPU doesn't work well with float16

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#55755]
## 🐛 Bug

This occurs during porting of matmul to OpInfo #55543. 
1. If float16 is included in the dtypes list, the following error occurs in test result
```
======================================================================
ERROR: test_supported_backward_matmul_cpu_float16 (__main__.TestOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 730, in only_fn
    return fn(self, device, *args, **kwargs)
  File "test/test_ops.py", line 74, in test_supported_backward
    result = op(sample.input, *sample.args, **sample.kwargs)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_methods_invocations.py", line 233, in __call__
    return self.op(*args, **kwargs)
RuntimeError: "addmv_impl_cpu" not implemented for 'Half'

======================================================================
ERROR: test_supported_dtypes_matmul_cpu_float16 (__main__.TestOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 730, in only_fn
    return fn(self, device, *args, **kwargs)
  File "test/test_ops.py", line 56, in test_supported_dtypes
    op(sample.input, *sample.args, **sample.kwargs)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_methods_invocations.py", line 233, in __call__
    return self.op(*args, **kwargs)
RuntimeError: "addmv_impl_cpu" not implemented for 'Half'
```

2. If float16 is excluded from the dtypes test list, the following error also occurs:
```
======================================================================
FAIL: test_unsupported_dtypes_matmul_cpu_float16 (__main__.TestOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 582, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/rongr/local/pytorch/torch/testing/_internal/common_device_type.py", line 730, in only_fn
    return fn(self, device, *args, **kwargs)
  File "test/test_ops.py", line 46, in test_unsupported_dtypes
    op(sample.input, *sample.args, **sample.kwargs)
AssertionError: RuntimeError not raised
```

This seems to indicate matmul on CPU for float16 both worked and did not worked at the same time?

**Comment by ngimel** [comment]
`matmul` is a composite operation that delegates to dot, mv, mm, bmm depending on the dimensionality of inputs, so listing supported dtypes if there are multiple sample inputs invoking different paths isn't possible, and it's only more complicated because backward path branches further. cc @mruberry on how  best to handle this situation.

**Comment by mruberry** [comment]
In these cases the operator doesn't actually implement the dtype. The correct thing to do is not to enumerate the dtype in question in the list of supported dtypes, then skip that dtype in the check for unsupported dtypes with a commented link to the corresponding issue (like this one).

**Comment by kshitij12345** [comment]
How about multiple OpInfo (1 per path) based on the different paths that can be taken.

This way 
* No need to skip `float16` for all path (even if only one path doesn't support it)
* Clarity at the OpInfo entry as to which path has the inconsistency or failures if any.


Eg.
https://github.com/pytorch/pytorch/blob/399b66c8137db9ef86e45707ec30a44e40495f62/torch/testing/_internal/common_methods_invocations.py#L3577-L3600

**Comment by mruberry** [comment]
> How about multiple OpInfo (1 per path) based on the different paths that can be taken.
> 
> This way
> 
> * No need to skip `float16` for all path (even if only one path doesn't support it)
> * Clarity at the OpInfo entry as to which path has the inconsistency or failures if any.
> 
> Eg.
> https://github.com/pytorch/pytorch/blob/399b66c8137db9ef86e45707ec30a44e40495f62/torch/testing/_internal/common_methods_invocations.py#L3577-L3600

This is a neat idea that would improve code coverage, but I'm going to suggest we don't pursue it for two reasons:

1) It would take a considerable amount of developer time, and OpInfos are supposed to make developer's more efficient
2) From a user's perspective the op does not support the dtype, and we should focus on testing user-facing features

The op should actually be updated to throw an error when given a float16 input on CPU.
