### ISSUE TITLE
test_rref_context_debug_info is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#55774]
## 🐛 Bug

Not disabling yet because only seen the failure once, but creating this issue to track. `test_rref_context_debug_info - TensorPipeRpcTestWithSpawn` is flaky, see https://app.circleci.com/pipelines/github/pytorch/pytorch/298891/workflows/8afd4417-8dc6-4f5b-9b00-c58c2959e1cf/jobs/12266924 for example (for PR https://github.com/pytorch/pytorch/pull/55624#issuecomment-817547343). 

Failure:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 322, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 515, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 558, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 441, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 324, in wrapper
    fn()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/dist_utils.py", line 91, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 2731, in test_rref_context_debug_info
    dist.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2481, in barrier
    work.wait()
RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.17.0.2]:28582

Process 2 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 441, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 324, in wrapper
    fn()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/dist_utils.py", line 91, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 2726, in test_rref_context_debug_info
    self.assertEqual(2, int(info["num_owner_rrefs"]))
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1341, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
  File "/opt/conda/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Scalars failed to compare as equal! Comparing 2 and 3 gives a difference of 1, but the allowed difference with rtol=0 and atol=0 is only 0!
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
dup of https://github.com/pytorch/pytorch/issues/55382
