### ISSUE TITLE
[feature request] Upsample improvements

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5580]
1. Bilinear upsampling on integer types like ByteTensor
2. Nearest upsampling with different when target size isn't divisible by input size

**Comment by SsnL** [comment]
I was working on this a bit, but will have to put it aside temporarily. I'll get back to this when I have time.

**Comment by hyperfraise** [comment]
Totally agree

**Comment by fmassa** [comment]
@hyperfraise nearest upsampling when target size isn't divisible by input size is already implemented and working on master (probably in 0.4.1 as well). ByteTensor support is not yet implemented though

**Comment by vadimkantorov** [comment]
@fmassa Cool :) One more step towards doing without Pillow dependency potentially :)

**Comment by vadimkantorov** [comment]
These benchmarks show Pillow-SIMD isn't etalon of speed either... https://github.com/albu/albumentations

**Comment by Solacex** [comment]
Hello, Any progress now ?

**Comment by karlind** [comment]
Hope this feature can be added. `scipy.ndimage.interpolation.zoom` is too slow in 3D tensor(D, H, W), hope this feature make pytorch's `interpolate` a alternative to scipy's `zoom`.

**Comment by vadimkantorov** [comment]
was just interpolating some integer maps and found that integer inputs to interpolate are still not supported... causing to allocate a float copy

**Comment by vadimkantorov** [comment]
@fmassa Interpolate on uint8 seems supported now?

**Comment by vadimkantorov** [comment]
```python
import torch
import torch.nn.functional as F

x = torch.zeros(3, 244, 395, dtype = torch.uint8)

print(F.interpolate(x.unsqueeze(0), (320, 240)).dtype)

print(F.interpolate(x.unsqueeze(0).to(torch.int32), (320, 240)).dtype)
```

torch.uint8
Traceback (most recent call last):
  File "/home/gamir/lab/vadim/mask2cad_pytorch/bug.py", line 8, in <module>
    print(F.interpolate(x.unsqueeze(0).to(torch.int32), (320, 240)).dtype)
  File "/home/gamir/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/functional.py", line 3690, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "compute_indices_weights_nearest" not implemented for 'Int'

**Comment by vadimkantorov** [comment]
Also, it could have better error message for unsupported dtypes for now. A typical one:
```
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "compute_indices_weights_nearest" not implemented for 'Bool'
```

**Comment by vadimkantorov** [comment]
Bool one should be easily supported since uint8 is already supported. But it would also require saturated cast (so that it never goes above 1 even in bicubic case).

**Comment by iTomxy** [comment]
Here's an solution: [What is the good way to interpolate int tensor](https://discuss.pytorch.org/t/what-is-the-good-way-to-interpolate-int-tensor/29490)

**Comment by vadimkantorov** [comment]
The solution you are linking seems kind of subsampling - and I agree this is a useful mode to have, but if we assume linearity of the underlying values, bilinear interpolation/averaging of integer values for uint8/int16 and other integral types (even including bool) does have useful sense
