### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by nikhilraghava** [pytorch/pytorch#5588]
I was running the following code on FlyodHub using this command: `floyd run --gpu --env pytorch-0.3 'python artist.py'`.

```python
import torch
from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms

import utils
from transformer_net import TransformerNet
from vgg import Vgg16


def stylize(input_image_path, model, output_image_path):
    content_image = utils.load_image(input_image_path)
    content_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.mul(255))
    ])
    content_image = content_transform(content_image)
    content_image = content_image.unsqueeze(0)
    content_image = content_image.cuda()
    content_image = Variable(content_image, volatile=True)

    style_model = TransformerNet()
    style_model.load_state_dict(torch.load(model))
    style_model.cuda()
    output = style_model(content_image)
    output = output.cpu()
    output_data = output.data[0]
    utils.save_image(output_image_path, output_data)


if __name__ == "__main__":
    stylize('test.jpg', 'saved_models/mosaic.pth', 'mosaic_test.png')
```
However I get the following error:

```bash
2018-03-06 01:08:49 PST  Run Output:
2018-03-06 01:11:15 PST  /usr/local/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:133: UserWarning: nn.UpsamplingNearest2d is deprecated. Use nn.Upsample instead.
2018-03-06 01:11:15 PST  warnings.warn("nn.UpsamplingNearest2d is deprecated. Use nn.Upsample instead.")
2018-03-06 01:11:15 PST  Traceback (most recent call last):
2018-03-06 01:11:15 PST  File "artist.py", line 32, in <module>
2018-03-06 01:11:15 PST  stylize('test.jpg', 'saved_models/mosaic.pth', 'mosaic_test.png')
2018-03-06 01:11:15 PST  File "artist.py", line 25, in stylize
2018-03-06 01:11:15 PST  output = style_model(content_image)
2018-03-06 01:11:15 PST  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
2018-03-06 01:11:15 PST  result = self.forward(*input, **kwargs)
2018-03-06 01:11:15 PST  File "/code/transformer_net.py", line 38, in forward
2018-03-06 01:11:15 PST  y = self.relu(self.in4(self.deconv1(y)))
2018-03-06 01:11:15 PST  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
2018-03-06 01:11:15 PST  result = self.forward(*input, **kwargs)
2018-03-06 01:11:15 PST  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/instancenorm.py", line 11, in forward
2018-03-06 01:11:15 PST  b, c = input.size(0), input.size(1)
2018-03-06 01:11:15 PST  AttributeError: 'NoneType' object has no attribute 'size'
2018-03-06 01:11:20 PST
```
How do I overcome this error?

**Comment by apaszke** [comment]
We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
