### ISSUE TITLE
ONNX export fails on constant_pad_nd (input.type().dim() is None)

### ISSUE THREAD

**Issue by anszom** [pytorch/pytorch#55900]
## 🐛 Bug

I've received a torchscript model for image classification and I'm trying to convert it to ONNX. The export fails on transforming constant_pad_nd, the direct cause being that the 'dim' of the input is None. 

Unfortunately I don't have the source for the model and I can't share the torchscript file. Please advise how I can trace the root cause of this problem.

## To Reproduce

1. This is how I'm running the converter
```
import torch
device = torch.device("cpu")
model = torch.jit.load("bla.pt", map_location=device)
model.to(device)
model.eval()
x = torch.randn(1, 3, 224, 224, requires_grad=True)
torch_out = model(x)
torch.onnx.export(model, x, 'model.onnx', export_params=True, opset_version=11, example_outputs=torch_out)
```

2. The resulting error message

```
Traceback (most recent call last):
  File "export1.py", line 8, in <module>
    torch.onnx.export(model, x, 'model.onnx', export_params=True, opset_version=11, example_outputs=torch_out)
  File "somepath/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "somepath/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "somepath/lib/python3.6/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "somepath/lib/python3.6/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "somepath/lib/python3.6/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "somepath/lib/python3.6/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "somepath/lib/python3.6/site-packages/torch/onnx/utils.py", line 657, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "somepath/lib/python3.6/site-packages/torch/onnx/symbolic_opset11.py", line 273, in constant_pad_nd
    pad = _prepare_onnx_paddings(g, input.type().dim(), padding)
  File "somepath/lib/python3.6/site-packages/torch/onnx/symbolic_opset11.py", line 251, in _prepare_onnx_paddings
    extension = g.op("Sub", g.op("Mul", g.op("Constant", value_t=torch.tensor(dim, dtype=torch.int64)),
TypeError: an integer is required (got type NoneType) (occurred when translating constant_pad_nd)

```

## Expected behavior

The conversion should complete successfully.

## Environment
PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Linux Mint 19.3 Tricia (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GT 430
Nvidia driver version: 390.141
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.5.0
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by lazykyama** [comment]
I'm not sure if my issue came from the same root cause, but I encountered a similar error.

## Minimal reproduction code

```python
import math
from typing import List

import torch
from torch import nn
import torch.nn.functional as F


# Some of the following codes come from padding.py in rwightman/pytorch-image-models repo.
# https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/padding.py
def get_same_padding(x: int, k: int, s: int, d: int):
    return max((math.ceil(x / s) - 1) * s + (k - 1) * d + 1 - x, 0)

class TestModule(nn.Module):
    def __init__(self, k, s):
        super(TestModule, self).__init__()
        self.k = [k, k]
        self.s = [s, s]
        self.d = [1, 1]
        self.value = 0.0

    def forward(self, x):
        ih, iw = x.size()[-2:]
        pad_h, pad_w = get_same_padding(ih, self.k[0], self.s[0], self.d[0]), get_same_padding(iw, self.k[1], self.s[1], self.d[1])
        if pad_h > 0 or pad_w > 0:
            x = F.pad(x, [pad_w // 2, pad_w - pad_w // 2, pad_h // 2, pad_h - pad_h // 2], value=self.value)
        return x

class Wrapper(nn.Module):
    def __init__(self, k, s):
        super(Wrapper, self).__init__()
        self.first = TestModule(k, s)
        self.second = TestModule(k, s)

    def forward(self, x):
        x = self.first(x)
        x = self.second(x)  # <- if commented out, no error.
        return x


def main():
    model = Wrapper(k=3, s=1)
    model.eval()
    model = torch.jit.script(model)

    x = torch.randn((1, 3, 150, 150))
    example_outputs = model(x)
    print(example_outputs)

    torch.onnx.export(
        model,
        x,
        './tmp/minimum.onnx',
        verbose=True,
        input_names=['x'],
        output_names=['out'],
        dynamic_axes=None,
        opset_version=11,
        example_outputs=example_outputs)


if __name__ == '__main__':
    main()
```

After simply running the above code, the following error should happen.

```
/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:295: UserWarning: Type cannot be inferred, which might cause exported graph to produce incorrect results.
  warnings.warn("Type cannot be inferred, which might cause exported graph to produce incorrect results.")
Traceback (most recent call last):
  File "minimum_repro_dynamic_padding_scripting.py", line 65, in <module>
    main()
  File "minimum_repro_dynamic_padding_scripting.py", line 52, in main
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 676, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 450, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1029, in _run_symbolic_function
    torch._C._jit_pass_onnx_block(b, new_block, operator_export_type, env)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 981, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_opset11.py", line 418, in constant_pad_nd
    pad = _prepare_onnx_paddings(g, sym_help._get_tensor_rank(input), padding)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_opset11.py", line 397, in _prepare_onnx_paddings
    extension = g.op("Sub", g.op("Mul", g.op("Constant", value_t=torch.tensor(dim, dtype=torch.int64)),
TypeError: an integer is required (got type NoneType)
(Occurred when translating constant_pad_nd).
(Occurred when translating If).
```

Note that, as far as I investigated:

* As a comment, if a line, `self.second = TestModule(k, s)`, is commented out, there's no error.
* It looks like first If operation returns output Tensor with dim=None during onnx exporting. That's the reason why this error happened.

## Environment

* Host OS: Ubuntu 18.04.5 LTS
* Docker version: `Docker version 20.10.6, build 370c289`
* GPU: NVIDIA TITAN X (Pascal)
    - Driver: 465.19.01
* Docker container: `nvcr.io/nvidia/pytorch:21.05-py3`
    - OS: Ubuntu 20.04.2 LTS
    - Python: 3.8.8
    - CUDA 11.3.58
    - cuDNN 8.2.0
    - `numpy==1.20.1`
    - `onnx==1.8.0`
    - `torch==1.9.0a0+2ecb2c7`
    - `torchtext==0.10.0a0`
    - `torchvision==0.9.0a0`

**Comment by BowenBao** [comment]
hi @lazykyama could you try with latest pytorch nightly? I tried your repro locally and it works. I think latest master resolved the issue with improved shape inferencing.

**Comment by BowenBao** [comment]
@anszom please give latest pytorch nightly a try if the issue is resolved.

**Comment by lazykyama** [comment]
Thanks for the update, @BowenBao! I tried to test today's nightly version, `1.10.0.dev20210609+cu111`, and it works for me, too. At least my error, the issue is resolved.

**Comment by anszom** [comment]
@BowenBao I've installed pytorch nightly but I'm encountering #35669 instead so I can't test it.

**Comment by lazykyama** [comment]
@BowenBao Sorry to bother you. I confirmed my issue was resolved, but it's only on the minimal repro code. On the actual code, the issue happened again. Please let me know if I should file another issue. (Or, continuing a discussion here. Either is fine for me.)

Steps for reproduction are below.

```
$ cd /path/to/workdir
$ git clone https://github.com/rwightman/efficientdet-pytorch.git
$ git clone https://github.com/rwightman/pytorch-image-models.git
$ sudo docker run --gpus=all --rm -it -v $(pwd):/ws nvcr.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
# apt update && apt install -y python3-pip
# pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
# pip3 install -e ./pytorch-image-models/
# pip3 install -r ./efficientdet-pytorch/requirements.txt
# python3 repro.py
```

After running `repro.py`, the following logs appeared. I guess several other issues could exist in the code and some of such issues should be problems on the `efficientdet-pytorch` itself, but at first, I need to resolve this error.

```
Apply torch.jit.script()
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1054: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1295.)
  return forward_call(*input, **kwargs)
/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_helper.py:243: UserWarning: ONNX export failed on interpolate (with scales) because missing input shape not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_helper.py:318: UserWarning: Type cannot be inferred, which might cause exported graph
to produce incorrect results.
  warnings.warn("Type cannot be inferred, which might cause exported graph to produce incorrect results.")
Traceback (most recent call last):
  File "repro.py", line 72, in <module>
    main()
  File "repro.py", line 58, in main
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 687, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 461, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1086, in _run_symbolic_function
    torch._C._jit_pass_onnx_block(b, new_block, operator_export_type, env,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 992, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset11.py", line 453, in constant_pad_nd
    pad = _prepare_onnx_paddings(g, sym_help._get_tensor_rank(input), padding)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset11.py", line 432, in _prepare_onnx_paddings
    extension = g.op("Sub", g.op("Mul", g.op("Constant", value_t=torch.tensor(dim, dtype=torch.int64)),
TypeError: an integer is required (got type NoneType)
(Occurred when translating constant_pad_nd).
(Occurred when translating If).
```

`repro.py` is below.

```python
"""
This code is based on validate.py in original effdet.
https://github.com/rwightman/efficientdet-pytorch/blob/master/validate.py
"""

import sys
import torch
from timm.utils import setup_default_logging
from timm.models.layers import set_layer_config

# Manually adding a path to efficientdet-pytorch
sys.path.append('./efficientdet-pytorch/')
from effdet import create_model
from effdet.config import model_config


def main():
    modelname = 'tf_efficientdet_d7x'
    exportpath = 'repro.onnx'
    torchscript = True
    no_jit = True
    exportable = True

    num_classes = None
    redundant_bias = None
    soft_nms = None
    checkpoint = ''
    use_ema = False

    # create model
    with set_layer_config(scriptable=torchscript, exportable=exportable, no_jit=no_jit):
        model = create_model(
            modelname,
            bench_task='',
            num_classes=num_classes,
            pretrained=True,
            redundant_bias=redundant_bias,
            soft_nms=soft_nms,
            checkpoint_path=checkpoint,
            checkpoint_ema=use_ema,
        )
        model.eval()
        image_size = model.config['image_size']

        dummy_input = torch.randn(1, 3, image_size[0], image_size[1])

        print('Apply torch.jit.script()')
        model = torch.jit.script(model)
        example_outputs = model(dummy_input)

        # export model.
        input_names = ['images']
        output_names = ['classes', 'boxes']
        dynamic_axes = None
        torch.onnx.export(
            model,
            dummy_input,
            exportpath,
            verbose=True,
            input_names=input_names,
            output_names=output_names,
            dynamic_axes=dynamic_axes,
            opset_version=11,
            example_outputs=example_outputs)
    print('done.')


if __name__ == '__main__':
    main()
```

Also, before running the above code, the patch below should be applied to `efficientdet-pytorch/effdet/efficientdet.py`.

```diff
diff --git a/effdet/efficientdet.py b/effdet/efficientdet.py
index cf7a1b6..60740f4 100644
--- a/effdet/efficientdet.py
+++ b/effdet/efficientdet.py
@@ -189,6 +189,34 @@ class ResampleFeatureMap(nn.Sequential):
     #     return x
 
 
+class FpnCombineAttnWeightMethod(nn.Module):
+    def __init__(self, inputs_offsets):
+        super(FpnCombineAttnWeightMethod, self).__init__()
+        self.edge_weights = nn.Parameter(torch.ones(len(inputs_offsets)), requires_grad=True)  # WSM
+
+    def forward(self, nodes: List[torch.Tensor], dtype: torch.dtype):
+        normalized_weights = torch.softmax(self.edge_weights.to(dtype=dtype), dim=0)
+        return torch.stack(nodes, dim=-1) * normalized_weights
+
+class FpnCombineFastAttnWeightMethod(nn.Module):
+    def __init__(self, inputs_offsets):
+        super(FpnCombineFastAttnWeightMethod, self).__init__()
+        self.edge_weights = nn.Parameter(torch.ones(len(inputs_offsets)), requires_grad=True)  # WSM
+
+    def forward(self, nodes: List[torch.Tensor], dtype: torch.dtype):
+        edge_weights = nn.functional.relu(self.edge_weights.to(dtype=dtype))
+        weights_sum = torch.sum(edge_weights)
+        return torch.stack(
+            [(nodes[i] * edge_weights[i]) / (weights_sum + 0.0001) for i in range(len(nodes))], dim=-1)
+
+class FpnCombineSumWeightMethod(nn.Module):
+    def __init__(self):
+        super(FpnCombineSumWeightMethod, self).__init__()
+        pass
+
+    def forward(self, nodes: List[torch.Tensor], dtype: torch.dtype):
+        return torch.stack(nodes, dim=-1)
+
 class FpnCombine(nn.Module):
     def __init__(self, feature_info, fpn_config, fpn_channels, inputs_offsets, target_reduction, pad_type='',
                  downsample=None, upsample=None, norm_layer=nn.BatchNorm2d, apply_resample_bn=False,
@@ -212,10 +240,14 @@ class FpnCombine(nn.Module):
                 downsample=downsample, upsample=upsample, norm_layer=norm_layer, apply_bn=apply_resample_bn,
                 conv_after_downsample=conv_after_downsample, redundant_bias=redundant_bias)
 
-        if weight_method == 'attn' or weight_method == 'fastattn':
-            self.edge_weights = nn.Parameter(torch.ones(len(inputs_offsets)), requires_grad=True)  # WSM
+        if weight_method == 'attn':
+            self.weight_method_fn = FpnCombineAttnWeightMethod(inputs_offsets)
+        elif weight_method == 'fastattn':
+            self.weight_method_fn = FpnCombineFastAttnWeightMethod(inputs_offsets)
+        elif weight_method == 'sum':
+            self.weight_method_fn = FpnCombineSumWeightMethod()
         else:
-            self.edge_weights = None
+            raise ValueError('unknown weight_method {}'.format(self.weight_method))
 
     def forward(self, x: List[torch.Tensor]):
         dtype = x[0].dtype
@@ -225,18 +257,7 @@ class FpnCombine(nn.Module):
             input_node = resample(input_node)
             nodes.append(input_node)
 
-        if self.weight_method == 'attn':
-            normalized_weights = torch.softmax(self.edge_weights.to(dtype=dtype), dim=0)
-            out = torch.stack(nodes, dim=-1) * normalized_weights
-        elif self.weight_method == 'fastattn':
-            edge_weights = nn.functional.relu(self.edge_weights.to(dtype=dtype))
-            weights_sum = torch.sum(edge_weights)
-            out = torch.stack(
-                [(nodes[i] * edge_weights[i]) / (weights_sum + 0.0001) for i in range(len(nodes))], dim=-1)
-        elif self.weight_method == 'sum':
-            out = torch.stack(nodes, dim=-1)
-        else:
-            raise ValueError('unknown weight_method {}'.format(self.weight_method))
+        out = self.weight_method_fn(nodes, dtype)
         out = torch.sum(out, dim=-1)
         return out
 
@@ -424,14 +445,17 @@ class HeadNet(nn.Module):
             self.bn_level_first = not self.bn_level_first
             self.bn_rep = new_bn_rep
 
-    @torch.jit.ignore()
     def _forward(self, x: List[torch.Tensor]) -> List[torch.Tensor]:
         outputs = []
         for level in range(self.num_levels):
             x_level = x[level]
             for conv, bn in zip(self.conv_rep, self.bn_rep):
                 x_level = conv(x_level)
-                x_level = bn[level](x_level)  # this is not allowed in torchscript
+                for i, b in enumerate(bn):
+                    # NOTE: this loop is not efficient but need to avoid the following restriction.
+                    # https://github.com/pytorch/pytorch/issues/47496
+                    if i == level:
+                        x_level = b(x_level)
                 x_level = self.act(x_level)
             outputs.append(self.predict(x_level))
         return outputs
```

**Comment by garymm** [comment]
Works with latest nightly PyTorch (`Version: 1.12.0.dev20220216+cpu`).
