### ISSUE TITLE
Sparse-sparse matrix multiplication only works with torch.sparse.mm()

### ISSUE THREAD

**Issue by wenleix** [pytorch/pytorch#55944]
## 🐛 Bug

Sparse-sparse matrix multiplication only works with `torch.sparse.mm()`, doesn't work with 
- `torch.mm()`
- `Tensor.mm()`

## To Reproduce

```python
>>> i = [[0, 2], [1, 0], [1, 2]]
>>> v = [3.0, 4.0, 5.0]
>>> s = torch.sparse_coo_tensor(list(zip(*i)), v, (2, 3))
>>> torch.mm(s, s.t())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: sparse tensors do not have strides
>>> s.mm(s.t())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: sparse tensors do not have strides
>>> torch.sparse.mm(s, s.t())
tensor(indices=tensor([[0, 0, 1, 1],
                       [1, 0, 0, 1]]),
       values=tensor([15.,  9., 15., 41.]),
       size=(2, 2), nnz=4, layout=torch.sparse_coo)
```

## Expected behavior

It should work with `torch.mm()` and `Tensor.mm()`? Also I don't find document about this sparse-sparse matrix multiplication feature. 

## Environment

```
PyTorch version: 1.9.0a0+git2f6a806
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: Could not collect
CMake version: version 3.19.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0a0+gitf4d5639
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.9.0a0+git197549d          pypi_0    pypi
```

**Comment by mruberry** [comment]
Thank you for filing this issue, @wenleix; I agree we could be more straightforward with our sparse UX.
