### ISSUE TITLE
Can't assign container literals to variables annotated with `Optional`

### ISSUE THREAD

**Issue by ansley** [pytorch/pytorch#56011]
## 🐛 Bug

The TorchScript type system sees `Optional[List[T]]` as different from `List[T]`, so the assignment fails. More logic needs to be added in the IR Emitter (and probably in later passes as well) to account for this type of assignment. We make a bit of an effort [here](https://github.com/pytorch/pytorch/blob/132f5c1f36698361149ea99ca3504bd2acfdc19f/torch/csrc/jit/frontend/ir_emitter.cpp#L2832), but I think we also need to expand [this section](https://github.com/pytorch/pytorch/blob/132f5c1f36698361149ea99ca3504bd2acfdc19f/torch/csrc/jit/frontend/ir_emitter.cpp#L3603).

## Example

```python
import torch
from typing import List, Optional

@torch.jit.script
def fn():
    x: Optional[List[torch.Tensor]] = [torch.tensor(3)]
    if torch.jit.isinstance(x, List[torch.Tensor]): 
        x.append(torch.tensor(3))
    return x

fn()
```
```
Traceback (most recent call last):
  File "test/tinytest.py", line 5, in <module>
    def fn():
  File "/Users/ansley/pytorch/torch/jit/_script.py", line 1047, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
Expected a List type hint but instead got Optional[List[Tensor]]:
  File "test/tinytest.py", line 6
@torch.jit.script
def fn():
    x: Optional[List[torch.Tensor]] = [torch.tensor(3)]
                                      ~~~~~~~~~~~~~ <--- HERE
    if torch.jit.isinstance(x, List[torch.Tensor]): 
        x.append(torch.tensor(3))
```

cc @gmagogsfm

**Comment by ansley** [comment]
Fixed by #58911
