### ISSUE TITLE
Test spam "This caffe2 python run failed to load cuda module" on python test/distributed/rpc/test_process_group_agent.py ProcessGroupJitRpcTestWithSpawn.test_call_fork_in_jit_with_profiling and other tests

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56109]
When running

```
python test/distributed/rpc/test_process_group_agent.py ProcessGroupJitRpcTestWithSpawn.test_call_fork_in_jit_with_profiling
```

and other tests I get a ton of Caffe2 spam like this:

```
WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
Apr 14 21:01:51 WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
Apr 14 21:01:51 WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
Apr 14 21:01:51 WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
```

It would be great if the tests didn't spam like this as it would make it easier to read the output. More importantly, should caffe2 even be imported for these tests?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gmagogsfm

**Comment by ezyang** [comment]
The caffe2 import is caused by this backtrace:

```
Traceback (most recent call last):
  File "/home/ezyang/local/install3.8.9/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ezyang/local/install3.8.9/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_distributed.py", line 427, in _run
    self.run_test(test_name, pipe)
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_distributed.py", line 435, in run_test
    import caffe2.python._import_c_extension as C  # type: ignore
  File "/data/users/ezyang/pytorch-tmp/caffe2/python/_import_c_extension.py", line 8, in <module>
    assert False
```

**Comment by zhaojuanmao** [comment]
it is trying to call 'set_print_stack_traces_on_fatal_signal', I'm wondering whether PyTorch has equivalent API to print stack trace @ezyang?

**Comment by ezyang** [comment]
No I don't think so. We should move this code to, e.g., c10. See also #40137

**Comment by pritamdamania87** [comment]
Resolved in https://github.com/pytorch/pytorch/pull/56717
