### ISSUE TITLE
Compiling from src got AssertionError: No matching output for forward derivative in native_functions.yaml _embedding_bag_dense_backward

### ISSUE THREAD

**Issue by tyoc213** [pytorch/pytorch#56104]
## ❓ Questions and Help

When I try to install as in the instructions I got an error that I nailed from the logs to this command:

```
$     cd /home/tyoc213/Documents/github/pytorch && /home/tyoc213/miniconda3/envs/xla/bin/python tools/setup_helpers/generate_code.py --declarations-path /home/tyoc213/Documents/github/pytorch/build/aten/src/ATen/Declarations.yaml --native-functions-path aten/src/ATen/native/native_functions.yaml --nn-path aten/src   --force_schema_registration
Traceback (most recent call last):
  File "tools/setup_helpers/generate_code.py", line 183, in <module>
    main()
  File "tools/setup_helpers/generate_code.py", line 168, in main
    generate_code(
  File "tools/setup_helpers/generate_code.py", line 60, in generate_code
    gen_autograd_python(
  File "/home/tyoc213/Documents/github/pytorch/tools/autograd/gen_autograd.py", line 83, in gen_autograd_python
    differentiability_infos = load_derivatives(
  File "/home/tyoc213/Documents/github/pytorch/tools/autograd/load_derivatives.py", line 42, in load_derivatives
    infos = [
  File "/home/tyoc213/Documents/github/pytorch/tools/autograd/load_derivatives.py", line 43, in <listcomp>
    create_differentiability_info(defn, functions_by_signature, functions_by_schema)
  File "/home/tyoc213/Documents/github/pytorch/tools/autograd/load_derivatives.py", line 397, in create_differentiability_info
    derivatives, forward_derivatives, args_with_derivatives, non_differentiable_arg_names = set_up_derivatives(canonical)
  File "/home/tyoc213/Documents/github/pytorch/tools/codegen/context.py", line 36, in wrapper
    return func(f)
  File "/home/tyoc213/Documents/github/pytorch/tools/autograd/load_derivatives.py", line 334, in set_up_derivatives
    forward_derivatives.append(create_forward_derivative(f, formula, names))
  File "/home/tyoc213/Documents/github/pytorch/tools/autograd/load_derivatives.py", line 117, in create_forward_derivative
    assert var_type is not None, "No matching output for forward derivative definition"
AssertionError: No matching output for forward derivative definition
  in aten/src/ATen/native/native_functions.yaml:1490:
    _embedding_bag_dense_backward(Tensor grad, Tensor indices, Tensor offset2bag, Tensor bag_size, Tensor maximum_indices, int num_weights, bool scale_grad_by_freq, int mode, Tensor? per_sample_weights, int padding_idx=-1) -> Tensor

```

If it serves something `tools/autograd/load_derivatives.py`
![image](https://user-images.githubusercontent.com/506234/114812793-5bfde600-9d76-11eb-8d9d-d1f1d5ba201a.png)

prints:

```
NativeFunction(func=FunctionSchema(name=OperatorName(name=BaseOperatorName(base='_embedding_bag_dense_backward', inplace=False, dunder_method=False), overload_name=''), arguments=Arguments(pre_self_positional=(), self_arg=None, post_self_positional=(Argument(name='grad', type=BaseType(name=<BaseTy.Tensor: 3>), default=None, annotation=None), Argument(name='indices', type=BaseType(name=<BaseTy.Tensor: 3>), default=None, annotation=None), Argument(name='offset2bag', type=BaseType(name=<BaseTy.Tensor: 3>), default=None, annotation=None), Argument(name='bag_size', type=BaseType(name=<BaseTy.Tensor: 3>), default=None, annotation=None), Argument(name='maximum_indices', type=BaseType(name=<BaseTy.Tensor: 3>), default=None, annotation=None), Argument(name='num_weights', type=BaseType(name=<BaseTy.int: 4>), default=None, annotation=None), Argument(name='scale_grad_by_freq', type=BaseType(name=<BaseTy.bool: 8>), default=None, annotation=None), Argument(name='mode', type=BaseType(name=<BaseTy.int: 4>), default=None, annotation=None), Argument(name='per_sample_weights', type=OptionalType(elem=BaseType(name=<BaseTy.Tensor: 3>)), default=None, annotation=None), Argument(name='padding_idx', type=BaseType(name=<BaseTy.int: 4>), default='-1', annotation=None)), pre_tensor_options_kwarg_only=(), tensor_options=None, post_tensor_options_kwarg_only=(), out=()), returns=(Return(name=None, type=BaseType(name=<BaseTy.Tensor: 3>), annotation=None),)), device_guard=True, python_module=None, category_override=None, variants={<Variant.function: 1>}, manual_kernel_registration=False, manual_cpp_binding=False, dispatch={<DispatchKey.CPU: 1>: '_embedding_bag_dense_backward_cpu', <DispatchKey.CUDA: 2>: '_embedding_bag_dense_backward_cuda'}, loc=Location(file='aten/src/ATen/native/native_functions.yaml', line=1490), structured=False, structured_delegate=None, structured_inherits=None, cpp_no_default_args=set())
    ------
    non_differentiable
    ------
    ('offsets',)
    +++++++++++++++++++++
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @albanD @mruberry

**Comment by mruberry** [comment]
@jbschlosser does this make sense to you?

**Comment by jbschlosser** [comment]
Problem is that `offsets` was removed from the signature of `_embedding_bag_dense_backward()` but an entry for it was left in `derivatives.yaml`. Workaround is to remove this line:
https://github.com/pytorch/pytorch/blob/50057e560bc0b863dcb0fa67b7dec891eaa4023f/tools/autograd/derivatives.yaml#L1291

 @albanD has a fix and recently landed tests to ensure this sort of thing doesn't slip through unnoticed again (https://github.com/pytorch/pytorch/pull/49098).

**Comment by albanD** [comment]
Hey,

Thanks for the report.
Sorry about the inconvenience, there was a race landing two PRs and we didn't notice this breakage. Master was broken for an hour before we identified it and reverted the offending diff.
So latest master doesn't have this problem anymore.

Even though master is not broken very often, it does happen, if you encounter this issue again, you can try to compile from the `viable/strict` branch. It is the latest version of master that passed all the CI so this one should never be broken.
