### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute 'ComplexDoubleStorageBase'

### ISSUE THREAD

**Issue by samfux84** [pytorch/pytorch#56126]
## 🐛 Bug

I have a pytorch 1.5.1+cu101 installation that was done with pip (pip3). Now I would like to install a newer version with "pip install --user" in $HOME/.local without overwriting the existing one. For all other Python packages this works without any problem. But for PyTorch it does not matter what version I install locally, I always get errors on importing the local version

This is on a HPC cluster, so building PyTorch with conda is not an option (and I assume it must also be possible to install PyTorch with pip)

## To Reproduce

1. Install a PyTorch version in a central Python installation
2. Install a second version locally with pip install --user
3. Start Python and import torch

```
[sfux@lo-login-02 ~]$ module list

Currently Loaded Modules:
  1) StdEnv   2) gcc/6.3.0   3) openblas/0.2.19   4) cuda/10.1.243   5) cudnn/7.6.4   6) jpeg/9b   7) libpng/1.6.27   8) nccl/2.4.8-1   9) python_gpu/3.7.4  10) libsndfile/1.0.31



[sfux@lo-login-02 ~]$ pip list | grep torch
gpytorch              1.0.1
torch                 1.5.1+cu101
torchtext             0.6.0
torchvision           0.6.1+cu101
[sfux@lo-login-02 ~]$ python
Python 3.7.4 (default, Oct 17 2019, 10:45:10)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.5.1+cu101'
>>> quit()
[sfux@lo-login-02 ~]$ which pip
/cluster/apps/python/3.7.4_gpu_gcc630/x86_64/bin/pip
[sfux@lo-login-02 ~]$ pip install --user torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.1+cu101
  Using cached https://download.pytorch.org/whl/cu101/torch-1.7.1%2Bcu101-cp37-cp37m-linux_x86_64.whl (735.4 MB)
Collecting torchvision==0.8.2+cu101
  Using cached https://download.pytorch.org/whl/cu101/torchvision-0.8.2%2Bcu101-cp37-cp37m-linux_x86_64.whl (12.8 MB)
Collecting torchaudio==0.7.2
  Using cached torchaudio-0.7.2-cp37-cp37m-manylinux1_x86_64.whl (7.6 MB)
Requirement already satisfied: numpy in /cluster/apps/python/3.7.4_gpu_gcc630/x86_64/lib64/python3.7/site-packages (from torch==1.7.1+cu101) (1.17.3)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: pillow>=4.1.1 in /cluster/apps/python/3.7.4_gpu_gcc630/x86_64/lib64/python3.7/site-packages (from torchvision==0.8.2+cu101) (6.2.0)
Installing collected packages: typing-extensions, torch, torchvision, torchaudio
Successfully installed torch-1.7.1+cu101 torchaudio-0.7.2 torchvision-0.8.2+cu101 typing-extensions-3.7.4.3
[sfux@lo-login-02 ~]$ pip list | grep torch
gpytorch              1.0.1
torch                 1.7.1+cu101
torchaudio            0.7.2
torchtext             0.6.0
torchvision           0.8.2+cu101
[sfux@lo-login-02 ~]$ python
Python 3.7.4 (default, Oct 17 2019, 10:45:10)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/home/sfux/.local/lib/python3.7/site-packages/torch/__init__.py", line 455, in <module>
    class ComplexDoubleStorage(_C.ComplexDoubleStorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'ComplexDoubleStorageBase'
>>>
```

## Expected behavior

import torch should import the pytorch module and not throw an AttributeError.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1+cu101 and 1.7.1+cu101
 - OS (e.g., Linux): CentOS Linux release 7.9.2009 (Core)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.7.4 (compiled from source code)
 - CUDA/cuDNN version: CUDA:10.1.243, cuDNN 7.6.4
 - GPU models and configuration: -
 - Any other relevant information: -

## Additional context

I tried to install the second PyTorch version in a venv (python -m venv --system-site-packages myenv) and there I get the same error when running "import torch".

**Comment by samfux84** [comment]
Just tested to create an empty venv and to install another pytorch version there, but I still get the same error:

```
[sfux@lo-s4-009 ~]$ module load gcc/6.3.0 python_gpu/3.7.4 eth_proxy

The following have been reloaded with a version change:
  1) gcc/4.8.5 => gcc/6.3.0

[sfux@lo-s4-009 ~]$ python -m venv pytorch171cu101
[sfux@lo-s4-009 ~]$ source $HOME/pytorch171cu101/bin/activate
(pytorch171cu101) [sfux@lo-s4-009 ~]$ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cd/6f/43037c7bcc8bd8ba7c9074256b1a11596daa15555808ec748048c1507f08/pip-21.1.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.6MB 6.8MB/s
Installing collected packages: pip
  Found existing installation: pip 19.0.3
c    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-21.1.1
(pytorch171cu101) [sfux@lo-s4-009 ~]$ OPENBLAS=$OPENBLAS_ROOT/lib/libopenblas.so pip install --no-binary :all: numpy==1.19.5
Collecting numpy==1.19.5
  Downloading numpy-1.19.5.zip (7.3 MB)
     |████████████████████████████████| 7.3 MB 4.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.19.5-cp37-cp37m-linux_x86_64.whl size=11916710 sha256=a8661f0667ca6f8de0fbeaff9dc991caddf0af16de7c5bc80948351aebeebaf7
  Stored in directory: /cluster/home/sfux/.cache/pip/wheels/62/f7/b2/69a26275770f55d1e8d7355aaa221caf38536f5f0795390b8f
Successfully built numpy
Installing collected packages: numpy
Successfully installed numpy-1.19.5
(pytorch171cu101) [sfux@lo-s4-009 ~]$ pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.1+cu101
  Using cached https://download.pytorch.org/whl/cu101/torch-1.7.1%2Bcu101-cp37-cp37m-linux_x86_64.whl (735.4 MB)
Collecting torchvision==0.8.2+cu101
  Using cached https://download.pytorch.org/whl/cu101/torchvision-0.8.2%2Bcu101-cp37-cp37m-linux_x86_64.whl (12.8 MB)
Collecting torchaudio==0.7.2
  Using cached torchaudio-0.7.2-cp37-cp37m-manylinux1_x86_64.whl (7.6 MB)
Collecting typing-extensions
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Requirement already satisfied: numpy in ./pytorch171cu101/lib/python3.7/site-packages (from torch==1.7.1+cu101) (1.19.5)
Collecting pillow>=4.1.1
  Downloading Pillow-8.2.0-cp37-cp37m-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 6.4 MB/s
Installing collected packages: typing-extensions, torch, pillow, torchvision, torchaudio
Successfully installed pillow-8.2.0 torch-1.7.1+cu101 torchaudio-0.7.2 torchvision-0.8.2+cu101 typing-extensions-3.10.0.0
(pytorch171cu101) [sfux@lo-s4-009 ~]$ python
Python 3.7.4 (default, Oct 17 2019, 10:45:10)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/home/sfux/pytorch171cu101/lib64/python3.7/site-packages/torch/__init__.py", line 455, in <module>
    class ComplexDoubleStorage(_C.ComplexDoubleStorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'ComplexDoubleStorageBase'
>>>
```

How can this be?  How can a pytorch installation in the central site-packages directory break another torch installation in a venv that ignores the central site-packages directory?

**Comment by sublee** [comment]
I met a similar issue on PyTorch 1.8.1. [A comment](https://github.com/pytorch/pytorch/issues/24834#issuecomment-534595871) in #24834 was helpful for me. This issue seems duplicate.
