### ISSUE TITLE
DISABLED test_send_recv (__main__.TestMPIWithFork)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#56146]
https://app.circleci.com/pipelines/github/pytorch/pytorch/302347/workflows/03c31f92-9dfe-41fd-bdc4-a247f10ae6fd/jobs/12444570
https://app.circleci.com/pipelines/github/pytorch/pytorch/302169/workflows/00946250-ae8a-4376-a860-2d70bb2cf60b/jobs/12436215/steps

```
Apr 15 04:16:09 ======================================================================
Apr 15 04:16:09 FAIL [0.116s]: test_send_recv (__main__.TestMPIWithFork)
Apr 15 04:16:09 ----------------------------------------------------------------------
Apr 15 04:16:09 Traceback (most recent call last):
Apr 15 04:16:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 968, in test_send_recv
Apr 15 04:16:09     self.assertEqual(event_count, expected_event_count)
Apr 15 04:16:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1371, in assertEqual
Apr 15 04:16:09     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Apr 15 04:16:09 AssertionError: False is not true : Scalars failed to compare as equal! Comparing 1 and 2 gives a difference of 1, but the allowed difference with rtol=0 and atol=0 is only 0!
Apr 15 04:16:09 
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
Thanks for flagging @mrshenli, will prioritize resolving this flakiness before the release

**Comment by rohan-varma** [comment]
Close since the test name has changed: https://github.com/pytorch/pytorch/issues/56690
