### ISSUE TITLE
optim.Adedelta: local variable 'lr' referenced before assignment

### ISSUE THREAD

**Issue by mmmmayi** [pytorch/pytorch#56237]
## 🐛 Bug
Previously I used pytorch1.7.0 and the code works well. After I upgrade my pytorch to 1.8.1, I got this bug for my optimizer with the same code.

## To Reproduce
```
optimizer = optim.Adadelta(params, lr=learning_rate)
optimizer.zero_grad()
#other code to compute loss
optimizer1.step()  
optimizer.zero_grad()
```

The error shows:
```
Traceback (most recent call last):
  File "run_debug.py", line 179, in <module>
    network, stop_flag, epoch = network_training.train_network(training_data, mean_train,std_train, mean_lps, std_lps, writer, epoch)
  File "/data07/mayi/code/asvtorch/asvtorch/src/networks/network_training_single.py", line 154, in train_network
    optimizer1.step()
  File "/data07/mayi/anaconda3/envs/asvtorch2/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/data07/mayi/anaconda3/envs/asvtorch2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data07/mayi/anaconda3/envs/asvtorch2/lib/python3.7/site-packages/torch/optim/adadelta.py", line 85, in step
    lr,
UnboundLocalError: local variable 'lr' referenced before assignment
```

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:10.2
 - GPU models and configuration: 2080
 - Any other relevant information:

**Comment by mmmmayi** [comment]
I find the condition that trigger this bug:
My code is
```
params = [{'params': no_decay, 'weight_decay': 0.},
                  {'params': decay, 'weight_decay': Settings().network.weight_decay}]
optimizer1 = optim.Adadelta(params, lr=learning_rate)
```
then the bug occurs.
But if I set
```
optimizer1 = optim.Adadelta(net.parameters(), lr=learning_rate)
```
Then it works
