### ISSUE TITLE
Test suite doesn't work without scipy installed

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56274]
```
Traceback (most recent call last):
  File "test/test_autograd.py", line 46, in <module>
    from torch.testing._internal.common_methods_invocations import (method_tests,
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_methods_invocations.py", line 3315, in <module>
    ref=scipy.special.i0e,
NameError: name 'scipy' is not defined
```

cc @kshitij12345 @mruberry

**Comment by kshitij12345** [comment]
Apologies, missed that. Thanks!

All the CI test env have `scipy` installed, so the CI doesn't signal us.
