### ISSUE TITLE
Unable to pip install PyTorch on M1 Mac - Errors

### ISSUE THREAD

**Issue by erinjerri** [pytorch/pytorch#56333]
### Please note that this issue tracker is not a help form and this issue will be closed.

I got this error after running several doing `pip install` and installing from source code on your main GH repo and from these two installation forums discussing the issue:
https://discuss.pytorch.org/t/installing-pytorch-on-m1-macbook/105961/9

https://stackoverflow.com/questions/64949501/pytorch-wont-install-in-pycharm-on-macos/65528845#65528845

This is the error I get after installing the `setup.py build` command
`uilding wheel torch-1.9.0a0+git8512662
Traceback (most recent call last):
  File "/Users/erinjerri/pytorch/setup.py", line 298, in <module>
    cmake = CMake()
  File "/Users/erinjerri/pytorch/tools/setup_helpers/cmake.py", line 97, in __init__
    self._cmake_command = CMake._get_cmake_command()
  File "/Users/erinjerri/pytorch/tools/setup_helpers/cmake.py", line 124, in _get_cmake_command
    raise RuntimeError('no cmake or cmake3 with version >= 3.5.0 found')
RuntimeError: no cmake or cmake3 with version >= 3.5.0 found`

This is the error after installing from `pip3 install torch`command
`-c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gh/jq7gcjwd2tqb6ct4mzxmwn880000gn/T/pip-install-stil29du/torch_8996362e29aa48ce8418ef81767c331f/setup.py'"'"'; __file__='"'"'/private/var/folders/gh/jq7gcjwd2tqb6ct4mzxmwn880000gn/T/pip-install-stil29du/torch_8996362e29aa48ce8418ef81767c331f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gh/jq7gcjwd2tqb6ct4mzxmwn880000gn/T/pip-record-kbve4sgs/install-record.txt --single-version-externally-managed --compile --install-headers /Users/erinjerri/miniforge3/include/python3.9/torch Check the logs for full command output.`
We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

I already tried to run a similar install for [Tensorflow](https://github.com/apple/tensorflow_macos).

**Comment by quest4next** [comment]
You cannot pip install Pytorch on Mac M1. Follow these instructions https://naturale0.github.io/machine%20learning/setting-up-m1-mac-for-both-tensorflow-and-pytorch

**Comment by malikasinger1** [comment]
I was getting same error with following pip packeges
flask
stocker
pystmark
mysql-connector-python
gunicorn
phpserialize
matplotlib
google-cloud-storage

# Solved

just go to your application folder, then goto utilities, inside the utilities folder you will see the terminal app, right-click on that and goto info, check open using rozetta, now your terminal will always open in x86 mode and all cli apps of x86 will work just fine


<img width="997" alt="Screen Shot 2021-06-08 at 4 53 41 PM" src="https://user-images.githubusercontent.com/14273842/121180397-4094f000-c87a-11eb-8e07-923c6390aaf6.png">

**Comment by malfet** [comment]
PyTorch should be available for M1 on both PyPI and conda-forge

**Comment by nashid** [comment]
@malfet can you please elaborate further, which python version do I need to use?

**Comment by malfet** [comment]
> @malfet can you please elaborate further, which python version do I need to use?

@nashid Only Python-3.8 and 3.9 are supported natively on M1, aren't they?

**Comment by hfoffani** [comment]
This is the current url for the above mentioned article: https://naturale0.github.io/2021/01/29/setting-up-m1-mac-for-both-tensorflow-and-pytorch  (I haven't tested).

_I'm assuming this is the correct thread to add info/hints/etc regarding PyTorch on Apple M1._

**Comment by pietz** [comment]
Tested it today. **pip install torch** works under python **3.9.9** but not under **3.10.1**.

**Comment by malfet** [comment]
Resolved: PyTorch ships native Apple Silicon (arm64) pip wheels, so `pip install torch` works on M1 Macs without building from source. Closing as done.
