### ISSUE TITLE
Error in generating TorchScript: torch.jit.trace: 'Conv2dBottleneck' object has no attribute 'baseline_flops'

### ISSUE THREAD

**Issue by yonatanbitton** [pytorch/pytorch#56339]
Hello
I have a torch model that I need to generate TorchScript for it.

This is what I run:
```python
example_input = torch.rand(1, 3, 256, 192) 
traced_model = torch.jit.trace(model, example_input)
```

This is the error:
```python
>>> traced_model = torch.jit.trace(model, example_input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 1028, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 727, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 1836, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 727, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 1836, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 727, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 1836, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 713, in make_module
    elif torch._jit_internal.module_has_exports(mod):
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/_jit_internal.py", line 409, in module_has_exports
    item = getattr(mod, name)
  File "/mnt/conda/envs/dist_MSRA_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'Conv2dBottleneck' object has no attribute 'baseline_flops'
```

‘Conv2dBottleneck’ is a private class inheriting from ‘nn.Module’.

How can I solve it?

Thanks

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Could you provide more details about `model` and `Conv2dBottleneck`? thanks.

**Comment by yonatanbitton** [comment]
This is a layer that inhertis from `torch._distilled_layer.DistilledLayer`, and uses `torch._general_bottleneck.General2dBottleneck`. Is it helping?

**Comment by gmagogsfm** [comment]
Could you provide exact source code needed for a repro?

**Comment by gmagogsfm** [comment]
Due to inactivity, I will close this issue.

Based on the limited information, my best guess is that `baseline_flops` is an optional attribute of a module. It happens to not exist for this particular module instance being compiled. Feel free to reopen the issue and continue discussion if you could provide more details about your program.
