### ISSUE TITLE
torch.distributed.launch no longer works in nightly

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#56364]
## 🐛 Bug

torch.distributed.launch no longer works in nightly

## To Reproduce

Put following code into `main.py`, 

```python
import torch
import argparse

def main(rank):
    print('this is rank', rank)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--local_rank', type=int)
    args = parser.parse_args()

    main(args.local_rank)
```

run with 

```
python -m torch.distributed.launch --nproc_per_node 2 main.py
```

got error message

```
/opt/pytorch/pytorch/torch/distributed/launch.py:163: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.elastic_launch
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
WARNING:torch.distributed.elastic_launch:`torch.distributed.launch` is Deprecated. Use torch.distributed.elastic_launch
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : main.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 2
  run_id           : <NONE>
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 300}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "ModuleNotFoundError: No module named 'etcd'",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 324, in wrapper\n    return f(*args, **kwargs)\n  File \"/opt/pytorch/pytorch/torch/distributed/launcher/api.py\", line 214, in launch_agent\n    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/registry.py\", line 52, in get_rendezvous_handler\n    return handler_registry.create_handler(params)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/api.py\", line 256, in create_handler\n    handler = creator(params)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/registry.py\", line 19, in _create_static_handler\n    from . import etcd_rendezvous\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/etcd_rendezvous.py\", line 17, in <module>\n    import etcd  # type: ignore[import]\nModuleNotFoundError: No module named 'etcd'\n",
      "timestamp": "1618821126"
    }
  }
}
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "ModuleNotFoundError: No module named 'etcd'",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 324, in wrapper\n    return f(*args, **kwargs)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic_launch.py\", line 587, in run\n    elastic_launch(\n  File \"/opt/pytorch/pytorch/torch/distributed/launcher/api.py\", line 116, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 324, in wrapper\n    return f(*args, **kwargs)\n  File \"/opt/pytorch/pytorch/torch/distributed/launcher/api.py\", line 214, in launch_agent\n    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/registry.py\", line 52, in get_rendezvous_handler\n    return handler_registry.create_handler(params)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/api.py\", line 256, in create_handler\n    handler = creator(params)\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/registry.py\", line 19, in _create_static_handler\n    from . import etcd_rendezvous\n  File \"/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/etcd_rendezvous.py\", line 17, in <module>\n    import etcd  # type: ignore[import]\nModuleNotFoundError: No module named 'etcd'\n",
      "timestamp": "1618821126"
    }
  }
}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/pytorch/pytorch/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/opt/pytorch/pytorch/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/opt/pytorch/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 324, in wrapper
    return f(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/distributed/elastic_launch.py", line 587, in run
    elastic_launch(
  File "/opt/pytorch/pytorch/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/pytorch/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 324, in wrapper
    return f(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/distributed/launcher/api.py", line 214, in launch_agent
    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)
  File "/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/registry.py", line 52, in get_rendezvous_handler
    return handler_registry.create_handler(params)
  File "/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/api.py", line 256, in create_handler
    handler = creator(params)
  File "/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/registry.py", line 19, in _create_static_handler
    from . import etcd_rendezvous
  File "/opt/pytorch/pytorch/torch/distributed/elastic/rendezvous/etcd_rendezvous.py", line 17, in <module>
    import etcd  # type: ignore[import]
ModuleNotFoundError: No module named 'etcd'
```

## Expected behavior

No fail

## Environment

Does not work in pyTorch version: 1.9.0a0+git 04e7891

It was working 3 days ago in 1.9.0a0+git 0a541e2, which looked nice and clean.

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
this is rank 0
this is rank 1
```

## Additional context

N/A

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @ptrblck

**Comment by rohan-varma** [comment]
cc @tierex @cbalioglu

**Comment by tierex** [comment]
Thanks for reporting. This PR should resolve the issue: https://github.com/pytorch/pytorch/pull/56386

**Comment by xwang233** [comment]
Even after installed `python-etcd`, I still got error

```
Traceback (most recent call last):
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdaffd548e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xwang/.local/lib/python3.9/site-packages/etcd/client.py", line 296, in machines
    response = self.http.request(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/xwang/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=29500): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdaffd548e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xwang/Developer/pytorch/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/home/xwang/Developer/pytorch/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 324, in wrapper
    return f(*args, **kwargs)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic_launch.py", line 587, in run
    elastic_launch(
  File "/home/xwang/Developer/pytorch/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 324, in wrapper
    return f(*args, **kwargs)
  File "/home/xwang/Developer/pytorch/torch/distributed/launcher/api.py", line 214, in launch_agent
    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/rendezvous/registry.py", line 52, in get_rendezvous_handler
    return handler_registry.create_handler(params)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/rendezvous/api.py", line 256, in create_handler
    handler = creator(params)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/rendezvous/registry.py", line 21, in _create_static_handler
    return etcd_rendezvous.create_rdzv_handler(params)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/rendezvous/etcd_rendezvous.py", line 1060, in create_rdzv_handler
    client = _create_etcd_client(params)
  File "/home/xwang/Developer/pytorch/torch/distributed/elastic/rendezvous/etcd_rendezvous.py", line 1000, in _create_etcd_client
    return etcd.Client(
  File "/home/xwang/.local/lib/python3.9/site-packages/etcd/client.py", line 203, in __init__
    set(self.machines))
  File "/home/xwang/.local/lib/python3.9/site-packages/etcd/client.py", line 320, in machines
    raise etcd.EtcdException("Could not get the list of servers, "
etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
```

**Comment by xwang233** [comment]
@tierex Thanks for the fix. Do you know if `python-etcd` is going to be a required python module for pytorch project? If so, can you add that to `requirements.txt` file?

**Comment by tierex** [comment]
Right now it should not be required, this is a simple bug: https://github.com/pytorch/pytorch/pull/56386/files#diff-a23f7a6efecd02df8f91e9ba0c9668f0dcef6bd03cc9488219a287f7a437adb1L12

**Comment by xwang233** [comment]
Thanks. This seems fixed in master now. Closed.
