### ISSUE TITLE
NoneType object is not subscriptable occurred when translating split

### ISSUE THREAD

**Issue by II245** [pytorch/pytorch#56376]
## 🐛 Bug
When I export a model from Pytorch (1.8.1) to onnx (opset 13) I get TypeError. Please, see output below.

```
1.8.1
torch.Size([2, 1024])
{'o': tensor([[[8.7999e-03, 5.0594e-02, 1.6806e-02,  ..., 9.8131e-03,
          2.2909e-01, 8.0491e-02],
         [7.1657e-04, 1.1610e-03, 4.1497e-04,  ..., 2.0145e-02,
          7.3948e-02, 6.0986e-02],
         [6.3549e-02, 4.6601e-04, 1.3716e-03,  ..., 1.1153e-03,
          5.6995e-04, 6.1731e-02],
         ...,
         [1.8082e-02, 1.3487e-02, 4.6422e-02,  ..., 5.5731e-03,
          3.6483e-03, 1.8362e-02],
         [1.4879e-01, 2.1655e-01, 1.1041e-01,  ..., 1.6832e-01,
          2.6434e-02, 1.3597e-01],
         [2.8711e-02, 2.6926e-02, 4.5051e-04,  ..., 1.3086e-02,
          1.6363e-04, 6.7658e-04]],

        [[5.8452e-02, 8.8316e-02, 7.5456e-03,  ..., 1.2578e-02,
          5.0840e-03, 3.3902e-02],
         [1.1250e-03, 1.0461e-01, 3.0154e-02,  ..., 1.1294e-02,
          4.3130e-02, 2.6737e-03],
         [1.2553e-02, 6.7388e-03, 1.5452e-02,  ..., 5.4921e-03,
          1.1490e-01, 3.8380e-02],
         ...,
         [1.6907e-02, 6.1064e-02, 8.0837e-02,  ..., 6.8258e-03,
          2.1773e-02, 1.4764e-02],
         [3.3045e-01, 2.1649e-01, 1.0370e-01,  ..., 1.7957e-01,
          3.5815e-01, 3.9849e-01],
         [3.8014e-02, 7.5352e-03, 2.7492e-04,  ..., 6.6090e-03,
          3.2415e-03, 6.0792e-03]]], grad_fn=<SplitBackward>)}
Traceback (most recent call last):
  File "repro/opset13.py", line 27, in <module>
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 694, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 997, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 148, in wrapper
    return fn(g, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_opset13.py", line 73, in split
    size = self.type().sizes()[dim]
TypeError: 'NoneType' object is not subscriptable 
(Occurred when translating split).


```

## To Reproduce

Run script below

```python
import onnxruntime
from torch import nn
import torch
import torch.nn.functional as F

print(torch.__version__)


class Model(nn.Module):
	def __init__(self):
		super().__init__()
		self.sftt = nn.Conv1d(1, 258, 256, bias=False, stride=80)

	def forward(self, x):
		pad = 5
		padded_signal = F.pad(x, (0, pad), mode='constant', value=0)
		stft_res = self.sftt(padded_signal.unsqueeze(dim=1))
		real_squared, imag_squared = (stft_res * stft_res).split(129, dim=1)
		return dict(o=real_squared)


model = Model()
x = torch.rand((2, 1024))
print(x.shape)
print(model(x))

torch.onnx.export(
		model, (x,),
		'fp32_opset_13.onnx',
		verbose=False,
		opset_version=13,
		export_params=True,
		do_constant_folding=True,
		input_names=['x']
)
```

## Expected behavior
Onnx export without TypeError

## Environment

 - OS Platform and Distribution: Linux Ubuntu 18.04: Linux x86_64
 - Python version: Python 3.8.5
 - Pytorch version: 1.8.1
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - CUDA/cuDNN version: CUDA Version: 11.1
 - GPU model and memory: Tesla V100 (32G)

Thanks for reply!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by jiafatom** [comment]
This issue can be resolved by the PR https://github.com/pytorch/pytorch/pull/56277
Please apply the patch for now, it will get merged soon.

**Comment by jiafatom** [comment]
@II245 Closing this issue as there is no feedback. Please feel free to reopen if the issue still exists.
