### ISSUE TITLE
ONNX export failed: Couldn't export Python operator SwishImplementation

### ISSUE THREAD

**Issue by ardeal** [pytorch/pytorch#56458]
Hi,

I cloned the code and pth file from:
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch

I wrote the following code to export pth to onnx. however, I encountered unknown issue.
it should be easy to reproduce the issue if you:
1) clone the code,
2) download the pth file: https://github.com/zylo117/Yet-Another-Efficient-Pytorch/releases/download/1.0/efficientdet-d0.pth
3) run my code below.

```python

import sys
import os
import torch
from backbone import EfficientDetBackbone
def pth_onnx(input_pth):

    outpath = os.path.join(os.path.dirname(input_pth), os.path.basename(input_pth)[:-3] + 'onnx')

    compound_coef = 0
    anchor_ratios = [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]
    anchor_scales = [2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]

    obj_list = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
                'fire hydrant', '', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep',
                'cow', 'elephant', 'bear', 'zebra', 'giraffe', '', 'backpack', 'umbrella', '', '', 'handbag', 'tie',
                'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove',
                'skateboard', 'surfboard', 'tennis racket', 'bottle', '', 'wine glass', 'cup', 'fork', 'knife', 'spoon',
                'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
                'cake', 'chair', 'couch', 'potted plant', 'bed', '', 'dining table', '', '', 'toilet', '', 'tv',
                'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink',
                'refrigerator', '', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier',
                'toothbrush']

    model = EfficientDetBackbone(compound_coef=compound_coef, num_classes=len(obj_list), ratios=anchor_ratios, scales=anchor_scales)
    model.load_state_dict(torch.load(input_pth, map_location='cpu'))
    model.requires_grad_(False)
    model.eval()

    # model = EfficientDetBackbone(compound_coef=compound_coef, num_classes=len(obj_list))
    # model.load_state_dict(torch.load(f'weights/efficientdet-d{compound_coef}.pth'))
    # model.requires_grad_(False)
    # model.eval()

    dummy_input = torch.ones(1, 3, 512, 512)
    # model.set_swish(memory_efficient=False)
    with torch.no_grad():
        torch.onnx.export(model, dummy_input, outpath, opset_version=11, verbose=False)

    return

if __name__ == '__main__':

    input_pth_path = r'weights/efficientdet-d0.pth'
    pth_onnx(input_pth_path)

```

Fails with
`RuntimeError: ONNX export failed: Couldn't export Python operator SwishImplementation`

**Comment by skyline75489** [comment]
What is the exact error you encountered? Please provide as much as information as you can.

**Comment by ardeal** [comment]
the error message is not displayed. if it was visible, I would have already pasted it.

**Comment by skyline75489** [comment]
What is the “unknown issue” you mentioned? Is it exception? Does it have stacktrace? Please provide as much as information as you can so people can help you.

**Comment by ardeal** [comment]
@skyline75489 ,
Thank you !


I run the code posted on the topic. the code automatically breaks at the first picture. I then click "run" to continue, the code finished at the second picture.




![image](https://user-images.githubusercontent.com/6227348/115480728-afdc6380-a27d-11eb-9207-531258b32e3c.png)



![image](https://user-images.githubusercontent.com/6227348/115480756-be2a7f80-a27d-11eb-87d8-89c62c03e38f.png)

**Comment by skyline75489** [comment]
Please post what's in the console. It should give more info about the issue.

**Comment by ardeal** [comment]
@skyline75489 ,

In above pictures, all information I could see is posted.
This is why I said "unknown reason". The error message I could see is very rare.

**Comment by skyline75489** [comment]
Can you not use PyCharm and just run it with console? The raw output from console is usually the most helpful source of troubleshooting.

**Comment by ardeal** [comment]
@skyline75489 ,

I tried to run the code on console. there are so many lines and log message couldn't be display.  I then change the buffer size of console and re-run. I found that there were useful error messages in the beginning of the log messages as follows:



```python
python C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\pth_onnx.py
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientnet\utils_extra.py:36: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  extra_h = (math.ceil(w / self.stride[1]) - 1) * self.stride[1] - w + self.kernel_size[1]
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientnet\utils_extra.py:37: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  extra_v = (math.ceil(h / self.stride[0]) - 1) * self.stride[0] - h + self.kernel_size[0]
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientnet\utils_extra.py:75: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  extra_h = (math.ceil(w / self.stride[1]) - 1) * self.stride[1] - w + self.kernel_size[1]
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientnet\utils_extra.py:76: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  extra_v = (math.ceil(h / self.stride[0]) - 1) * self.stride[0] - h + self.kernel_size[0]
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\utils.py:111: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if image_shape[1] % stride != 0:
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\utils.py:117: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x = np.arange(stride / 2, image_shape[1], stride)
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\utils.py:117: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x = np.arange(stride / 2, image_shape[1], stride)
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\utils.py:118: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  y = np.arange(stride / 2, image_shape[0], stride)
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\utils.py:118: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  y = np.arange(stride / 2, image_shape[0], stride)
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\utils.py:134: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  anchor_boxes = torch.from_numpy(anchor_boxes.astype(dtype)).to(image.device)
Traceback (most recent call last):
  File "C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\pth_onnx.py", line 50, in <module>
    pth_onnx(input_pth_path)
  File "C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\pth_onnx.py", line 38, in pth_onnx
    torch.onnx.export(model, dummy_input, outpath, opset_version=11, verbose=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 647, in _export
    proto, export_map = graph._export_onnx(
RuntimeError: ONNX export failed: Couldn't export Python operator SwishImplementation

Defined at:
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientnet\utils.py(54): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(709): _slow_forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(725): _call_impl
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\efficientdet\model.py(438): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(709): _slow_forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(725): _call_impl
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\backbone.py(70): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(709): _slow_forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(725): _call_impl
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_trace.py(116): wrapper
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_trace.py(125): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(727): _call_impl
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_trace.py(1148): _get_trace_graph
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(342): _trace_and_get_graph_from_model
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(379): _create_jit_graph
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(409): _model_to_graph
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(632): _export
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(85): export
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\__init__.py(225): export
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\pth_onnx.py(38): pth_onnx
C:\doc\code_python\efficientnet\Yet-Another-EfficientDet-Pytorch\pth_onnx.py(50): <module>
......

```

**Comment by skyline75489** [comment]
Now we have something useful to work with. Please try to avoid screenshot and use raw logs instead, and don't just say "unknown reason".

**Comment by garymm** [comment]
@ardeal custom autograd functions are not automatically supported by torch.onnx.export yet.

Looks like the author of the model you're using knows this and has a work-around specifically for exporting to onnx:
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/15403b5371a64defb2a7c74e162c6e880a7f462c/efficientdet/model.py#L40

`self.swish = MemoryEfficientSwish() if not onnx_export else Swish()`

So you need to figure out how to set `onnx_export = True` in that code (and probably other code).

Closing since this doesn't seem to be a bug in PyTorch.
