### ISSUE TITLE
Broadcasting is not correctly handled for torch.baddbmm

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#56508]
```
======================================================================
ERROR: test_variant_consistency_eager_baddbmm_cpu_complex64 (__main__.TestCommonCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 309, in test_variant_consistency_eager
    _test_consistency_helper(samples, variants)
  File "test/test_ops.py", line 298, in _test_consistency_helper
    variant_forward = variant(cloned,
RuntimeError: Expected self_sizes[0] == bs && self_sizes[1] == res_rows && self_sizes[2] == res_cols to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

======================================================================
ERROR: test_variant_consistency_eager_baddbmm_cpu_float32 (__main__.TestCommonCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 309, in test_variant_consistency_eager
    _test_consistency_helper(samples, variants)
  File "test/test_ops.py", line 298, in _test_consistency_helper
    variant_forward = variant(cloned,
RuntimeError: Expected self_sizes[0] == bs && self_sizes[1] == res_rows && self_sizes[2] == res_cols to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

======================================================================
======================================================================
ERROR: test_inplace_grad_baddbmm_cpu_complex128 (__main__.TestGradientsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 185, in test_inplace_grad
    self._grad_test_helper(device, dtype, op, self._get_safe_inplace(op.get_inplace()))
  File "test/test_ops.py", line 156, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck')
  File "test/test_ops.py", line 140, in _check_helper
    self.assertTrue(gradcheck(fn, gradcheck_args,
  File "/home/chourdiaanjali/pytorch3/torch/autograd/gradcheck.py", line 1027, in gradcheck
    func_out = func(*tupled_inputs)
  File "test/test_ops.py", line 130, in fn
    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_methods_invocations.py", line 185, in <lambda>
    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck
  File "test/test_ops.py", line 100, in _fn
    return inplace_variant(t.clone(), *args, **kwargs)
RuntimeError: Expected self_sizes[0] == bs && self_sizes[1] == res_rows && self_sizes[2] == res_cols to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
======================================================================
ERROR: test_inplace_grad_baddbmm_cpu_float64 (__main__.TestGradientsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 185, in test_inplace_grad
    self._grad_test_helper(device, dtype, op, self._get_safe_inplace(op.get_inplace()))
  File "test/test_ops.py", line 156, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck')
  File "test/test_ops.py", line 140, in _check_helper
    self.assertTrue(gradcheck(fn, gradcheck_args,
  File "/home/chourdiaanjali/pytorch3/torch/autograd/gradcheck.py", line 1027, in gradcheck
    func_out = func(*tupled_inputs)
  File "test/test_ops.py", line 130, in fn
    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_methods_invocations.py", line 185, in <lambda>
    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck
  File "test/test_ops.py", line 100, in _fn
    return inplace_variant(t.clone(), *args, **kwargs)
RuntimeError: Expected self_sizes[0] == bs && self_sizes[1] == res_rows && self_sizes[2] == res_cols to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
======================================================================
ERROR: test_inplace_gradgrad_baddbmm_cpu_complex128 (__main__.TestGradientsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 205, in test_inplace_gradgrad
    self._gradgrad_test_helper(device, dtype, op, self._get_safe_inplace(op.get_inplace()))
  File "test/test_ops.py", line 159, in _gradgrad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradgradcheck')
  File "test/test_ops.py", line 144, in _check_helper
    self.assertTrue(gradgradcheck(fn, gradcheck_args,
  File "/home/chourdiaanjali/pytorch3/torch/autograd/gradcheck.py", line 1140, in gradgradcheck
    outputs = _as_tuple(func(*tupled_inputs))
  File "test/test_ops.py", line 130, in fn
    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_methods_invocations.py", line 185, in <lambda>
    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck
  File "test/test_ops.py", line 100, in _fn
    return inplace_variant(t.clone(), *args, **kwargs)
RuntimeError: Expected self_sizes[0] == bs && self_sizes[1] == res_rows && self_sizes[2] == res_cols to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

======================================================================
ERROR: test_inplace_gradgrad_baddbmm_cpu_float64 (__main__.TestGradientsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 205, in test_inplace_gradgrad
    self._gradgrad_test_helper(device, dtype, op, self._get_safe_inplace(op.get_inplace()))
  File "test/test_ops.py", line 159, in _gradgrad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradgradcheck')
  File "test/test_ops.py", line 144, in _check_helper
    self.assertTrue(gradgradcheck(fn, gradcheck_args,
  File "/home/chourdiaanjali/pytorch3/torch/autograd/gradcheck.py", line 1140, in gradgradcheck
    outputs = _as_tuple(func(*tupled_inputs))
  File "test/test_ops.py", line 130, in fn
    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)
  File "/home/chourdiaanjali/pytorch3/torch/testing/_internal/common_methods_invocations.py", line 185, in <lambda>
    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck
  File "test/test_ops.py", line 100, in _fn
    return inplace_variant(t.clone(), *args, **kwargs)
RuntimeError: Expected self_sizes[0] == bs && self_sizes[1] == res_rows && self_sizes[2] == res_cols to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

```

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by anjali411** [comment]
This is expected and not a bug.
