### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by LysSanzMoreta** [pytorch/pytorch#56577]
## 🐛 Bug

Whenever I change a torch.cuda.DoubleTensor type tensor to .long() or integer type, because it's required, such as with embeddings, I **cannot see what is inside the tensor anymore or use it**.  Although I can see it's shape,

## To Reproduce

```
import torch
import torch.nn as nn
class Embed(nn.Module):
    def __init__(self,aa_probs):
        super(Embed, self).__init__()
        self.aa_probs = aa_probs
        self.embedding = nn.Embedding(num_embeddings=1, #----> does NOT matter the number
                                      embedding_dim=aa_probs,
                                      padding_idx=None,
                                      max_norm=None,
                                      norm_type=2.0,
                                      scale_grad_by_freq=False,
                                      sparse=False,
                                      _weight=None)
        self.cuda()
    def forward(self,input):
        output = self.embedding(input.type(torch.cuda.IntTensor))
        print(output.shape) #works
        print(output) #crashes
        return output

input = torch.tensor([[[1,2,-3],[4,-5,6],[-7,8,9]],[[10,-11,12],[13,-14,15],[-16,-17,18]]]).type(torch.cuda.DoubleTensor).cuda()

a = Embed(21)

a.forward(input)
```

#Error (shortened because it's very long)

```
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [2,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/home/lys/Dropbox/PhD/DRAUPNIR/error.py", line 28, in <module>
    a.forward(input)
  File "/home/lys/Dropbox/PhD/DRAUPNIR/error.py", line 20, in forward
    print(output)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 193, in __repr__
    return torch._tensor_str._str(self)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 383, in _str
    return _str_intern(self)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 358, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 242, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 90, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: device-side assert triggered
```

## Expected behavior

I hope to be able to use the tensor, slice it etc

## Environment

 - PyTorch Version (e.g., 1.0): pytorch                   1.8.1           py3.7_cuda11.1_cudnn8.0.5_0 
 - OS (e.g., Linux): Linux 5.8.0-50-generic x86_64 | "20.04.2 LTS (Focal Fossa)"
 - How you installed PyTorch (`conda`, `pip`, source): python -m pip install 
 - Python version: 3.7
 - CUDA/cuDNN version: 11.1
 - nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
 - GPU models and configuration:
NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2
 - NVIDIA card : GeForce GTX 1050 Ti Mobile (Type 6.1 Pascal, should be compatible with Cuda > 11)

Thanks!

cc @ngimel

**Comment by LysSanzMoreta** [comment]
I have downgraded to pytorch 1.8 that comes with cuda 10.2 and the error still persists. It helped me solve some other errors though, but there is something still wrong

**Comment by ailzhang** [comment]
Does pytorch work if you don't convert double to long?

**Comment by ngimel** [comment]
You are sending invalid input to nn.Embedding (num_embeddings=1, which means that you can only send indices equal to 0), and you are getting correct error for this. Unfortunately, this error causes invalidation of the context, which means that you can no longer inspect the contents of your cuda tensors. This is expected behavior though.

**Comment by LysSanzMoreta** [comment]
@ailzhang  Hi! The code provided is an example, it's a recreation of what I have to do with my own tensors, which require a transformation from float to integer/long , otherwise nn.Embedding layer complains, so if I just give floats to nn.Embedding it triggers:
```
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.DoubleTensor instead (while checking arguments for embedding)
```

@ngimel I get the same error no matter the number that I give to num_embeddings, so that is not the issue....

**Comment by ngimel** [comment]
Embedding does not accept negative indices. If I correct negative indices in your input an send correct number of embeddings, I get expected outputs
```
In [1]: import torch
   ...: import torch.nn as nn
   ...: class Embed(nn.Module):
   ...:     def __init__(self,aa_probs):
   ...:         super(Embed, self).__init__()
   ...:         self.aa_probs = aa_probs
   ...:         self.embedding = nn.Embedding(num_embeddings=19, #----> does NOT matter the number
   ...:                                       embedding_dim=aa_probs,
   ...:                                       padding_idx=None,
   ...:                                       max_norm=None,
   ...:                                       norm_type=2.0,
   ...:                                       scale_grad_by_freq=False,
   ...:                                       sparse=False,
   ...:                                       _weight=None)
   ...:         self.cuda()
   ...:     def forward(self,input):
   ...:         output = self.embedding(input.type(torch.cuda.IntTensor))
   ...:         print(output.shape) #works
   ...:         print(output) #crashes
   ...:         return output
   ...: 
   ...: input = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]).type(torch.cuda.DoubleTensor).cuda()
   ...: 
   ...: a = Embed(21)
   ...: 
   ...: a.forward(input)
```
