### ISSUE TITLE
Python backtrace in distributed RPC tests gets truncated

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56582]
Consider the test failure in https://app.circleci.com/pipelines/github/pytorch/pytorch/306242/workflows/7ad29f54-1dfb-4760-94b3-69093df41a3c/jobs/12644726

```
test_infer_backend_from_options - ProcessGroupProcessGroupAgentRpcTestWithSpawn
distributed/rpc/test_process_group_agent.py

Traceback (most recent call last):
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 344, in wrapper
    self._join_processes(fn)
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 537, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 599, in _check_return_codes
    msg="Expected zero exit code but got {}".format(first_process.exitcode)
  File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1371, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expected zero exit code but got -6
```

The backtrace starts in the middle of nowhere, in some utility function for joining processes. I expect to see a method "test_infer_backend_from_options" somewhere in the trace, but it is no where to be found. Somehow, the backtrace is getting truncated before the useful part.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
@ezyang This appears to be a UI issue (that I've noticed before as well), I usually go into the job and click the entire logs: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/12644726/output/105/0?file=true&allocation-id=607f5b2e06d1b70661e8b15d-0-build%2F10A6BAA1

the following trace is available: 

```
Apr 21 02:00:15   test_infer_backend_from_options (__main__.ProcessGroupProcessGroupAgentRpcTestWithSpawn) ... /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py:158: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Apr 21 02:00:15   "RPC was initialized with the PROCESS_GROUP backend which is "
Apr 21 02:00:15 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py:158: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Apr 21 02:00:15   "RPC was initialized with the PROCESS_GROUP backend which is "
Apr 21 02:00:15 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py:158: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Apr 21 02:00:15   "RPC was initialized with the PROCESS_GROUP backend which is "
Apr 21 02:00:15 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py:158: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Apr 21 02:00:15   "RPC was initialized with the PROCESS_GROUP backend which is "
Apr 21 02:00:15 Fatal Python error: PyEval_SaveThread: NULL tstate
Apr 21 02:00:15 
Apr 21 02:00:15 Fatal Python error: PyEval_SaveThread: NULL tstate
Apr 21 02:00:15 
Apr 21 02:00:15 Fatal Python error: PyEval_SaveThread: NULL tstate
Apr 21 02:00:15 
Apr 21 02:00:15 Fatal Python error: PyEval_SaveThread: NULL tstate
Apr 21 02:00:15 
Apr 21 02:00:15 FAIL (1.948s)
```

**Comment by ezyang** [comment]
While this is indeed good advice (and how I solved this particular bug in the end), the point still stands that the Python backtrace doesn't seem to ever talk about the actual Python code that was run in the test.

**Comment by pritamdamania87** [comment]
@ezyang The reason for this is that the main process doesn't run the test and instead spawns a bunch of processes that run the actual tests. Thats why the final error reported by the test failure displays that the exit code for one of the processes was non-zero and doesn't display the test method itself. As mentioned by Rohan, the entire logs do display for each process what went wrong.

**Comment by ezyang** [comment]
Alright, that explains it (although it doesn't save other people from being puzzled by this in the future)
