### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by jishan900** [pytorch/pytorch#5658]
jishan@jishan-B85M-HD3:~$ pip install http://download.pytorch.org/whl/cu80/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl 
Collecting torch==0.3.1 from http://download.pytorch.org/whl/cu80/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl
  Downloading http://download.pytorch.org/whl/cu80/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl (496.9MB)
    100% |████████████████████████████████| 496.9MB 1.4MB/s 
Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (from torch==0.3.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages/PyYAML-3.12-py2.7-linux-x86_64.egg (from torch==0.3.1)
Installing collected packages: torch
Exception:
Traceback (most recent call last):
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/jishan/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/torch-0.3.1.dist-info'

Please give me the correct solution. Thanks in advance.

**Comment by apaszke** [comment]
You can’t install python packages into the system wide install of python without root privileges. Use `virtualenv` or `conda` to create a local environment
