### ISSUE TITLE
consistency jit tests gives error for gradient operator

### ISSUE THREAD

**Issue by iramazanli** [pytorch/pytorch#56660]
In the following Pull Request -  #54617  we get the following error :

```
======================================================================
ERROR: test_variant_consistency_jit_gradient_cpu_float32 (__main__.TestCommonCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 379, in test_variant_consistency_jit
    check_against_reference(self,
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/common_jit.py", line 84, in check_against_reference
    outputs_test = self.runAndSaveRNG(func, nograd_inputs, kwargs)
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/common_jit.py", line 154, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/jit_metaprogramming_utils.py", line 307, in script_fn
    fn, tensors = gen_script_fn_and_args(method_name, func_type, *args, **kwargs)
  File "/fsx/users/iramazanli/pytorch/torch/testing/_internal/jit_metaprogramming_utils.py", line 298, in gen_script_fn_and_args
    CU = torch.jit.CompilationUnit(script)
RuntimeError: 
undefined value tensor:
  File "<string>", line 3

def the_method(i0):
    return torch.gradient(i0, dim=(0, -1), spacing=[tensor([1., 2., 3.]), tensor([4., 5., 6.])])
                                                   ~~~~~~ <--- HERE


```

**Comment by tugsbayasgalan** [comment]
Can you change it to torch.tensor and try again?

**Comment by tugsbayasgalan** [comment]
@iramazanli Is this resolved? I see you skipped the test for torch.float using SkipInfo.

**Comment by iramazanli** [comment]
thanks so much for following up :)  Actually if you see the line : 

https://github.com/pytorch/pytorch/blob/c0a3036c3b1b853e87f6648a0b68dccd65836461/torch/testing/_internal/common_methods_invocations.py#L1249

The tensor is created using torch.tensor rather than tensor. I don't know why generated code shows it with just tensor. So, unfortunately this error has not been solved

**Comment by tugsbayasgalan** [comment]
Hmm now I am getting following error from test_variant_consistency_jit_gradient_cpu_float32:
```
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::gradient.scalarint(Tensor self, *, Scalar? spacing=None, int? dim=None, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'Optional[number]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.scalararray(Tensor self, *, Scalar spacing, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'number' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.array(Tensor self, *, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[int]' for argument 'dim' but instead found type 'NoneType'.
  
  aten::gradient.scalarrayint(Tensor self, *, Scalar[] spacing, int? dim=None, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[number]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.scalarrayarray(Tensor self, *, Scalar[] spacing, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[number]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.tensorarrayint(Tensor self, *, Tensor[] spacing, int? dim=None, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[Tensor]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.tensorarray(Tensor self, *, Tensor[] spacing, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[Tensor]' for argument 'spacing' but instead found type 'List[float]'.

The original call is:
  File "<string>", line 3

def the_method(i0):
    return torch.gradient(i0, dim=None, spacing=[2.0, 2.1])
           ~~~~~~~~~~~~~~ <--- HERE
```
Did you run into same issue?

**Comment by iramazanli** [comment]
thanks for the response quick response.

To be honest, it didn't fail on integer case for me, but for float / complex i am also getting the following error

```
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::gradient.scalarint(Tensor self, *, Scalar? spacing=None, int? dim=None, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'Optional[number]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.scalararray(Tensor self, *, Scalar spacing, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'number' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.array(Tensor self, *, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[int]' for argument 'dim' but instead found type 'NoneType'.
  
  aten::gradient.scalarrayint(Tensor self, *, Scalar[] spacing, int? dim=None, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[number]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.scalarrayarray(Tensor self, *, Scalar[] spacing, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[number]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.tensorarrayint(Tensor self, *, Tensor[] spacing, int? dim=None, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[Tensor]' for argument 'spacing' but instead found type 'List[float]'.
  
  aten::gradient.tensorarray(Tensor self, *, Tensor[] spacing, int[] dim, int edge_order=1) -> (Tensor[]):
  Expected a value of type 'List[Tensor]' for argument 'spacing' but instead found type 'List[float]'.

The original call is:
  File "<string>", line 3

def the_method(i0):
    return torch.gradient(i0, dim=None, spacing=[2.0, 2.1])
           ~~~~~~~~~~~~~~ <--- HERE
```

**Comment by tugsbayasgalan** [comment]
We can do either of following:
1. add more overloads that specify List[int] or List[float]

**Comment by iramazanli** [comment]
After having a video call we have decided temporarily postponing fixing this issue

**Comment by gmagogsfm** [comment]
Any latest update here? Shall we close it?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
