### ISSUE TITLE
Segmentation default on Pytorch 1.8.1 + cuda 11.1

### ISSUE THREAD

**Issue by williampiat3** [pytorch/pytorch#56678]
## 🐛 Bug

Running a GAN structure on a personal project I came to bump into a segmentation error and I managed to reproduce the error on a quick MNIST GAN that I provide here (the GAN structure doesn't converge but that's not the point here) . The code runs with pytorch 1.8.1 + cuda 10.2 but does a segmentation error with pytorch 1.8.1 + cuda 11.1.
 I browsed before submitting so as not to make a duplicate but I couldn't find anything related to  segmentation error with this version (1.8.1+cu111). If 
## To Reproduce

Here is my code:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
import torchvision
import torch.optim as optim
import numpy as np



def load_data(root="data"):
	transform = torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])
	train_dataset = MNIST(root,train=True,transform=transform,download=True)
	test_dataset = MNIST(root,train=False,transform=transform,download=True)
	return train_dataset,test_dataset


class Generator(nn.Module):
	def __init__(self):
		super(Generator,self).__init__()
		m= [
		nn.ConvTranspose2d(10, 30, 3, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros'),
		nn.ReLU(),
		nn.ConvTranspose2d(30, 60, 5, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=2, padding_mode='zeros'),
		nn.ReLU(),
		nn.ConvTranspose2d(60, 120, 5, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros'),
		nn.ReLU(),
		nn.ConvTranspose2d(120, 160, 7, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros'),
		nn.ReLU(),
		nn.ConvTranspose2d(160, 1, 7, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros'),
		nn.Tanh()
		]
		self.seq = nn.Sequential(*m)
	def forward(self,x):
		return self.seq(x)

class Discriminator(nn.Module):
	def __init__(self):
		super(Discriminator,self).__init__()
		m=[nn.Conv2d(1,30,5),
			nn.MaxPool2d(2),
			nn.ReLU(),
			nn.Conv2d(30,60,5),
			nn.MaxPool2d(2),
			nn.ReLU(),
			nn.Conv2d(60,120,4),
			nn.ReLU()

		]
		self.seq = nn.Sequential(*m)
		self.lin=nn.Linear(120,1)
	def forward(self,x):
		return self.lin(self.seq(x).reshape(-1,120))





if __name__ =="__main__":
	device = torch.device('cuda')
	train_dataset,test_dataset = load_data()
	dataloader = DataLoader(train_dataset, batch_size=24, shuffle=True, sampler=None,
           batch_sampler=None, num_workers=4, collate_fn=None,
           pin_memory=True, drop_last=False, timeout=0,
           worker_init_fn=None, prefetch_factor=2,
           persistent_workers=False)
	gen = Generator()
	disc = Discriminator()
	gen.to(device)
	disc.to(device)
	optimizer_gen = optim.Adam(gen.parameters(),lr=0.00001)
	optimizer_disc = optim.Adam(disc.parameters(),lr=0.000001)

	log_gen=[]
	log_disc=[]

	for _ in range(100):
		for imgs,_ in iter(dataloader):
			imgs = imgs.to(device)
			#gen pass
			x = torch.randn(24,10,2,2,device=device)
			fake_img = gen(x)
			lamb_fake = torch.sigmoid(disc(fake_img))
			loss = -torch.sum(torch.log(lamb_fake))
			loss.backward()
			log_gen.append(loss.item())
			optimizer_gen.step()
			optimizer_gen.zero_grad()
			optimizer_disc.zero_grad()


			#disc pass
			x = torch.randn(24,10,2,2,device=device)
			fake_img = gen(x)
			lamb_fake = torch.sigmoid(disc(fake_img))
			lamb_real = torch.sigmoid(disc(imgs))
			loss2 = torch.sum(-torch.log(lamb_real)-torch.log(1-lamb_fake))/2
			loss2.backward()
			log_disc.append(loss2.item())
			optimizer_disc.step()
			optimizer_gen.zero_grad()
			optimizer_disc.zero_grad()

			# logs
			if len(log_gen)>100:
				print("Loss gen:",np.mean(log_gen))
				print("Loss disc:",np.mean(log_disc))
				log_gen = []
				log_disc = []
```

## Environment

PyTorch version: 1.8.1+cu111
installed with 
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect

## Additional context
Environnement where is works:

PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1
[conda] Could not collect

**Comment by ailzhang** [comment]
Marking as high pri since the report was about a crash on our latest release. But I remember we had issues with cuda11 so not sure if this is a real high pri.

**Comment by ptrblck** [comment]
@williampiat3 I wasn't able to reproduce the issue on a P100, which doesn't use the same compute capability, but is also from the Pascal family, and the code finishes successfully after ~2h.
Since it's a seg fault, could you rerun the code via:
```python
gdb --args python script.py
...
run
...
bt
```
and post the backtrace here, please?

**Comment by williampiat3** [comment]
Hope it helps, if you need anything else, do not hesitate
```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) run
Starting program: /usr/bin/python3 mnist_gan.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 538018]
[New Thread 0x7fff099af700 (LWP 538052)]
[New Thread 0x7fff011ae700 (LWP 538053)]
[New Thread 0x7fff009ad700 (LWP 538054)]
[New Thread 0x7ffef81ac700 (LWP 538055)]
[New Thread 0x7ffee79ab700 (LWP 538056)]
[New Thread 0x7ffedf1aa700 (LWP 538057)]
[New Thread 0x7ffed69a9700 (LWP 538058)]
[New Thread 0x7ffebe4cc700 (LWP 538063)]
[New Thread 0x7ffebdccb700 (LWP 538064)]
[New Thread 0x7ffebd4ca700 (LWP 538065)]
[Thread 0x7ffed69a9700 (LWP 538058) exited]
[Thread 0x7ffedf1aa700 (LWP 538057) exited]
[Thread 0x7ffee79ab700 (LWP 538056) exited]
[Thread 0x7ffef81ac700 (LWP 538055) exited]
[Thread 0x7fff009ad700 (LWP 538054) exited]
[Thread 0x7fff011ae700 (LWP 538053) exited]
[Thread 0x7fff099af700 (LWP 538052) exited]
[Detaching after fork from child process 538078]
[Detaching after fork from child process 538086]
[Detaching after fork from child process 538094]
[Detaching after fork from child process 538102]
[New Thread 0x7ffed69a9700 (LWP 538103)]
[New Thread 0x7ffedf1aa700 (LWP 538104)]
[New Thread 0x7ffee79ab700 (LWP 538105)]
[New Thread 0x7ffef81ac700 (LWP 538106)]
[New Thread 0x7fff011ae700 (LWP 538107)]
[New Thread 0x7fff009ad700 (LWP 538108)]
[New Thread 0x7ffeb5069700 (LWP 538113)]
[New Thread 0x7ffeb4868700 (LWP 538117)]
[Thread 0x7fff011ae700 (LWP 538107) exited]
[Thread 0x7ffef81ac700 (LWP 538106) exited]
[Thread 0x7fff009ad700 (LWP 538108) exited]
[Thread 0x7ffee79ab700 (LWP 538105) exited]
[Thread 0x7ffedf1aa700 (LWP 538104) exited]
[Thread 0x7ffeb4868700 (LWP 538117) exited]
[Thread 0x7ffeb5069700 (LWP 538113) exited]
[New Thread 0x7ffeb4868700 (LWP 538118)]
[New Thread 0x7ffeb5069700 (LWP 538119)]
[New Thread 0x7fff009ad700 (LWP 538120)]
[New Thread 0x7fff011ae700 (LWP 538121)]
[New Thread 0x7ffef81ac700 (LWP 538130)]
Loss gen: 15.728745196125296
Loss disc: 16.82705025625701
Loss gen: 15.709346450201355
Loss disc: 16.794593697727315
Loss gen: 15.678890568195003
Loss disc: 16.751730588403078
[New Thread 0x7ffee79ab700 (LWP 538356)]
[Thread 0x7ffed69a9700 (LWP 538103) exited]
[Thread 0x7ffee79ab700 (LWP 538356) exited]
[Thread 0x7ffeb4868700 (LWP 538118) exited]
[Thread 0x7fff009ad700 (LWP 538120) exited]
[Thread 0x7fff011ae700 (LWP 538121) exited]
[Thread 0x7ffeb5069700 (LWP 538119) exited]
Traceback (most recent call last):
  File "mnist_gan.py", line 91, in <module>
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([24, 60, 12, 12], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(60, 30, kernel_size=[5, 5], padding=[0, 0], stride=[1, 1], dilation=[2, 2], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [2, 2, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7ffe700f2640
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 24, 60, 12, 12, 
    strideA = 8640, 144, 12, 1, 
output: TensorDescriptor 0x7ffe700f2f20
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 24, 30, 4, 4, 
    strideA = 480, 16, 4, 1, 
weight: FilterDescriptor 0x7ffe700f2e70
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 30, 60, 5, 5, 
Pointer addresses: 
    input: 0x7ffe6e600000
    output: 0x7ffe9fb84800
    weight: 0x7ffe7bcf4800
Additional pointer addresses: 
    grad_output: 0x7ffe9fb84800
    grad_weight: 0x7ffe7bcf4800
Backward filter algorithm: 0

--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffec46e1de0 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
(gdb) bt
#0  0x00007ffec46e1de0 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007ffec4885c99 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007ffec46e85ef in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007ffec47c840c in cuMemFree_v2 ()
   from /lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fff0c8972fe in ?? ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libcudart-6d56b25a.so.11.0
#5  0x00007fff0c8c6588 in cudaFree ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libcudart-6d56b25a.so.11.0
#6  0x00007fff9708b7b1 in cublasFixedSizePool::tearDown() ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#7  0x00007fff970455e0 in cublasPoolWithGraphSuppport::tearDown() ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#8  0x00007fff96e6f2fa in cublasDestroy_v2 ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#9  0x00007fff94dc2d8d in std::_Sp_counted_ptr_inplace<at::cuda::(anonymous namespace)::DeviceThreadHandlePool<cublasContext*, &at::cuda::(anonymous namespace)::createCublasHandle, &at::cuda::(anonymous namespace)::destroyCublasHandle>, std::allocator<at::cuda::(anonymous namespace)::DeviceThreadHandlePool<cublasContext*, &at::cuda::(anonymous namespace)::createCublasHandle, &at::cuda::(anonymous namespace)::destroyCublasHandle> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
--Type <RET> for more, q to quit, c to continue without paging--
    ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#10 0x00007fff94dc2e91 in std::shared_ptr<at::cuda::(anonymous namespace)::DeviceThreadHandlePool<cublasContext*, &at::cuda::(anonymous namespace)::createCublasHandle, &at::cuda::(anonymous namespace)::destroyCublasHandle> >::~shared_ptr()
    ()
   from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#11 0x00007ffff7e01a27 in __run_exit_handlers (status=1, 
    listp=0x7ffff7fa3718 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:108
#12 0x00007ffff7e01be0 in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007ffff7ddf0ba in __libc_start_main (main=0x4eec80 <main>, argc=2, 
    argv=0x7fffffffe078, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe068)
    at ../csu/libc-start.c:342
#14 0x00000000005f927e in _start ()
```

**Comment by ptrblck** [comment]
Thanks for the stacktrace.
The seg fault might be a red herring and seems to be failing during the tear down of cublas.
However, the failure seems to be triggered by cudnn in:
```python
Traceback (most recent call last):
  File "mnist_gan.py", line 91, in <module>
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
I'll try to grab a similar GPU to yours and reproduce this issue.
