### ISSUE TITLE
default_pg_timeout in torch/testing/_internal/distributed/distributed_test.py is not sufficient to change system-wide timeouts

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56699]
Steps to reproduce:
1. Check out a copy of PyTorch that deadlocks, e.g., https://github.com/ezyang/pytorch/tree/example/deadlock
2. Run the deadlocking test and see that it does deadlock: `python test/distributed/rpc/test_process_group_agent.py ProcessGroupJitRpcTestWithSpawn.test_load_script_module_with_pickled_rref`
3. Edit the default testing timeout in attempt to increase the timeout time to make it easier to attach gdb
```
diff --git a/torch/testing/_internal/distributed/distributed_test.py b/torch/testing/_internal/distributed/distributed_test.py
index e99cbe5b945..0a04cb7e084 100644
--- a/torch/testing/_internal/distributed/distributed_test.py
+++ b/torch/testing/_internal/distributed/distributed_test.py
@@ -248,7 +248,7 @@ def get_timeout(test_id):
     else:
         return DEFAULT_TIMEOUT
 
-default_pg_timeout = 60
+default_pg_timeout = 600
 
 CUSTOM_PG_TIMEOUT = {
     # This test runs slowly and needs additional time to complete, otherwise can
```

Observe that the timeout is still the old one:

```
====================================================================== 
ERROR: test_load_script_module_with_pickled_rref (__main__.ProcessGroupJitRpcTestWithSpawn)                                                 
----------------------------------------------------------------------                                                                      
Traceback (most recent call last):                                    
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/common_distributed.py", line 344, in wrapper
    self._join_processes(fn)                                                                                                                
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/common_distributed.py", line 537, in _join_processes            
    self._check_return_codes(elapsed_time)
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/common_distributed.py", line 580, in _check_return_codes
    raise RuntimeError(error)                                                                                                               
RuntimeError: Process 0 exited with error code 10 and exception:                                                                            
Traceback (most recent call last):                                                                                                          
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/common_distributed.py", line 463, in run_test
    getattr(self, test_name)()                                                                                                              
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/common_distributed.py", line 346, in wrapper
    fn()                                                                                                                                    
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/dist_utils.py", line 91, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)              
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 1004, in test_load_script_module_with
_pickled_rref                                                                                                                               
    out1 = rpc.rpc_sync(                                              
  File "/data/users/ezyang/pytorch-tmp2/torch/distributed/rpc/api.py", line 79, in wrapper
    return func(*args, **kwargs)                                      
  File "/data/users/ezyang/pytorch-tmp2/torch/distributed/rpc/api.py", line 790, in rpc_sync
    return fut.wait()    
RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
@ezyang You are running into the RPC timeout which is different from the process group timeout. The default timeout for RPC is set here: https://github.com/pytorch/pytorch/blob/d83ae5d1b74df1ad6e2b80652392ce0c2b31f3f3/torch/csrc/distributed/rpc/init.cpp#L80. 

You can also modify the rpc timeout by specifying it in rpc_backen_options.rpc_timeout as part of the init_rpc call: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/dist_utils.py#L83
