### ISSUE TITLE
quantization for tuple input

### ISSUE THREAD

**Issue by LeopoldACC** [pytorch/pytorch#56848]
## 🚀 Feature

support quantization for tuple input
## Motivation

Due to the rnnt model need tuple input as shown below,and I'm doing quantization on the model at the same time.
```python
feature, feature_length = self.audio_preprocessor.forward((waveform, waveform_length))
```
**which lead to bug as shown below**
```shell
Traceback (most recent call last):
  File "run_tune.py", line 156, in <module>
    main()
  File "run_tune.py", line 135, in main
    q_model = quantizer()
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/lpot-1.2.1-py3.7.egg/lpot/experimental/quantization.py", line 151, in __call__
    self.strategy.traverse()
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/lpot-1.2.1-py3.7.egg/lpot/strategy/strategy.py", line 289, in traverse
    tune_cfg, self.model, self.calib_dataloader, self.q_func)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/lpot-1.2.1-py3.7.egg/lpot/utils/utility.py", line 201, in fi
    res = func(*args, **kwargs)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/lpot-1.2.1-py3.7.egg/lpot/adaptor/pytorch.py", line 703, in quantize
    self.model_calibration(q_model.model, dataloader, iterations)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/lpot-1.2.1-py3.7.egg/lpot/adaptor/pytorch.py", line 659, in model_calibration
    output = q_model(*input)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/zhenggo1/LowPrecisionInferenceTool0/examples/pytorch/speech_recognition/inference/rnnt/pytorch/decoders.py", line 63, in forward
    logits, logits_lens = self._model.encoder(x, out_lens)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/zhenggo1/LowPrecisionInferenceTool0/examples/pytorch/speech_recognition/inference/rnnt/pytorch/model_separable_rnnt.py", line 84, in forward
    x_padded, _ = self.pre_rnn(x_padded, None)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/zhenggo1/LowPrecisionInferenceTool0/examples/pytorch/speech_recognition/inference/rnnt/pytorch/rnn.py", line 81, in forward
    x, h = self.lstm(x, h)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 552, in __call__
    hook_result = hook(self, input, result)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/quantization/quantize.py", line 74, in _observer_forward_hook
    return self.activation_post_process(output)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/zhenggo1/anaconda3/envs/lpot/lib/python3.7/site-packages/torch/quantization/observer.py", line 804, in forward
    x = x_orig.detach()
AttributeError: 'tuple' object has no attribute 'detach'
```
## Pitch

I want to torch quantization support tuple input.
## Alternatives

If you can help me to quantize such input in another way,that is also ok.
## Additional context

Thanks!

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
yeah this is not supported currently, are you using eager mode quantization? I think you can put quant after the tuple is unpacked.

**Comment by jerryzh168** [comment]
Also please use discussion forum for questions: https://discuss.pytorch.org/c/quantization/17

**Comment by LeopoldACC** [comment]
This problem has been solved,I find that the reason is that LSTM is not support by torch quantization but the white list include the LSTM,thus I manually removed the torch.nn.LSTM from the white list and it run without problem.@jerryzh168
