### ISSUE TITLE
TorchScript lack good support for integer argument passed to function

### ISSUE THREAD

**Issue by DLtangsan** [pytorch/pytorch#56861]
## 🐛 Bug
It seems that TorchScript doens't support passing integer arguments to a function.

## To Reproduce
```
def splitA(x):
    return torch.split(x, 3)
class NetA(torch.nn.Module):
    def forward(self, x):
        return splitA(x)
print(torch.jit.script(NetA())) # pass

########

def splitB(x, split_size):
    return torch.split(x, split_size)
class NetB(torch.nn.Module):
    def forward(self, x):
        return splitB(x, 3)
print(torch.jit.script(NetB())) # fail

```
The `NetA` passes, but `NetB` fails. This is the error message I got:
```
RecursiveScriptModule(original_name=NetA)
Traceback (most recent call last):
    print(torch.jit.script(NetB()))
  File ".../lib/python3.6/site-packages/torch/jit/_script.py", line 943, in script
    obj, torch.jit._recursive.infer_methods_to_compile
    ...
  File ".../.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 335, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
splitB(Tensor x, Tensor split_size) -> (Tensor[]):
Expected a value of type 'Tensor (inferred)' for argument 'split_size' but instead found type 'int'.
Inferred 'split_size' to be of type 'Tensor' because it was not annotated with an explicit type.
:
    def forward(self, x):
        return splitB(x, 3)
               ~~~~~~ <--- HERE

```

## Expected behavior
Expect no exception.

## Environment
PyTorch Version (e.g., 1.0): 1.8
OS (e.g., Linux): Linux
How you installed PyTorch (conda, pip, source): pip
Python version: 3.6.6
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: V100

## Additional context

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
You need to explicitly annotate the input type of splitB function. We assume the type of any object to be Tensor if no annotations are provided. So, following example would work:

```
import torch


def splitB(x, split_size: int):
    return torch.split(x, split_size)

class NetB(torch.nn.Module):
    def __init__(self):
        super(NetB, self).__init__()
    def forward(self, x):
        return splitB(x, 3)
torch.jit.script(NetB())
