### ISSUE TITLE
[ONNX] prim::Uninitialized not supported in lower_tuples pass

### ISSUE THREAD

**Issue by matejsladek** [pytorch/pytorch#56911]
## 🐛 Bug

Currently, when there's a raised exception in model code, prim::Uninitialized is handled incorrectly in lower_tuples pass in onnx exporter.

## To Reproduce

Error:
```
Traceback (most recent call last):
  File "/mnt/nvdl/usr/msladek/notes/python_code/unitialized.py", line 18, in <module>
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 694, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 136, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples, unsupported kind: prim::Uninitialized
```

Code to reproduce:
```
import torch
from torch import Tensor
from typing import Tuple

class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()

    def forward(self, t: Tensor) -> Tuple[Tensor, Tensor]:
        if t < 0:
            raise Exception("Negative input")
        else:
            return torch.zeros(5), torch.zeros(5)


scripted_module = torch.jit.script(MyModule())

torch.onnx.export(
    scripted_module,
    (torch.zeros(5),),
    "./model.onnx",
    do_constant_folding=True,
    input_names=["INPUT__0"],
    output_names=["OUTPUT__0", "OUTPUT__1"],
    opset_version=13,
    example_outputs=(torch.zeros(5), torch.zeros(5))
)
```

## Expected behavior

Export onnx model without runtime error.

## Environment

 - PyTorch Version: PyTorch version: 1.8.1+cu111
 - OS: Ubuntu 20.04.1 LTS (x86_64)
 - How you installed PyTorch: pip
 - Python version: 3.8 (64-bit runtime)
 - CUDA/cuDNN version: CUDA runtime version: 11.2.67
 - GPU models and configuration: Tesla V100-SXM2-32GB

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by neginraoof** [comment]
Hi @matejsladek 
Thanks for reporting this. We know of an existing issue with lower_tuple pass, and we are planning the work here.
To help us prioritize this work, would you let us know if this is blocking any specific model for conversion to ONNX?

**Comment by matejsladek** [comment]
I'm working on the BART. This issue is blocking a family of NLP models with beam search, as beam search has control flow statements, it uses scripting.

**Comment by sssimpleboy** [comment]
hi, have you solved this problem？
