### ISSUE TITLE
nn.LSTM.cuda() leads to CuDNNError

### ISSUE THREAD

**Issue by jiacheng-xu** [pytorch/pytorch#5700]
- OS:   
uname -a
Linux everest 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- PyTorch version: 0.3.1.post2
- How you installed PyTorch (conda, pip, source): conda
- Python version: Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
- CUDA/cuDNN version:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
--and--
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

- GPU models and configuration: NVIDIA-SMI 384.111                Driver Version: 384.111
gpu is 1080ti and titan xp
- GCC version (if compiling from source): [GCC 7.2.0] on linux
--------------------------------
Code:
`torch.backends.cudnn.enabled = False //<--`
`rnn = torch.nn.LSTM(5, 10, num_layers=1, batch_first=True)`
`rnn.cuda()`
Result: pass!

--------------------------------
Code:
`torch.backends.cudnn.enabled = True//<--`
`rnn = torch.nn.LSTM(5, 10, num_layers=1, batch_first=True)`
`rnn.cuda()`
Result:
> Traceback (most recent call last):
  File "/home/user/main.py", line 16, in <module>
    rnn.cuda()
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 85, in flatten_parameters
    handle = cudnn.get_handle()
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 296, in get_handle
    handle = CuDNNHandle()
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 110, in __init__
    check_error(lib.cudnnCreate(ctypes.byref(ptr)))
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 4: b'CUDNN_STATUS_INTERNAL_ERROR'
Exception ignored in: <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle object at 0x7f5f02e5a2b0>>
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 114, in __del__
    check_error(lib.cudnnDestroy(self))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1

**Comment by ailzhang** [comment]
Hi @jiacheng-xu , your code snippet works on my pytorch0.3.1 build. Could you try deleting ~/.nv if it exists and rerun?

**Comment by jiacheng-xu** [comment]
@ailzhang It works. Thank you!

**Comment by crackcomm** [comment]
Is there any equivalent folder on Windows?
