### ISSUE TITLE
Allow `ScriptFunction`s to be symbolically traced

### ISSUE THREAD

**Issue by ansley** [pytorch/pytorch#57124]
## Motivation

Currently, we can't trace `ScriptFunction`s (the object produced by using the `@torch.jit.script` decorator on a function), since they aren't `nn.Module`s or instances of `FunctionType`. We should support this to ensure full FX-TorchScript compatibility.

## Example

```python
import torch
from torch.fx import symbolic_trace

@torch.jit.script
def fn(x, y):
    return torch.add(x, y)

traced = symbolic_trace(fn)
```

```
Traceback (most recent call last):
  File "test/tinytest.py", line 8, in <module>
    traced = symbolic_trace(fn)
  File "torch/fx/symbolic_trace.py", line 673, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "torch/fx/symbolic_trace.py", line 379, in trace
    assert isinstance(fn, FunctionType)
AssertionError

```

**Comment by ansley** [comment]
EDIT: Looks like we can't trace ScriptModules either. Same issue:

```python
class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.bn = torch.nn.BatchNorm2d(100)

    def forward(self, x: torch.Tensor):
        return torch.add(x, x)

m = torch.jit.script(M())
traced = symbolic_trace(m)
```

**Comment by jamesr66a** [comment]
An example solution for `ScriptMethod`: https://github.com/pytorch/pytorch/pull/52884

The solution to this issue will likely look similar
