### ISSUE TITLE
test_eig_with_eigvec_cuda_float64 is flaky on ROCm

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#57128]
```
12:23:46 ======================================================================
12:23:46 FAIL [0.051s]: test_eig_with_eigvec_cuda_float64 (__main__.TestTensorDeviceOpsCUDA)
12:23:46 ----------------------------------------------------------------------
12:23:46 Traceback (most recent call last):
12:23:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
12:23:46     method(*args, **kwargs)
12:23:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
12:23:46     result = test_fn(self, *args)
12:23:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 759, in only_fn
12:23:46     return fn(self, device, *args, **kwargs)
12:23:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 611, in dep_fn
12:23:46     return fn(slf, device, *args, **kwargs)
12:23:46   File "test_torch.py", line 7947, in fn
12:23:46     self.assertEqual(cpu_result, device_result, atol=precision, rtol=0, exact_dtype=False)
12:23:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1386, in assertEqual
12:23:46     exact_dtype=exact_dtype, exact_device=exact_device)
12:23:46   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1352, in assertEqual
12:23:46     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
12:23:46 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0 and atol=1e-05, found 19 element(s) (out of 100) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.1797657785383522 (-0.5898828892691765 vs. 0.5898828892691756), which occurred at index (5, 6).
12:23:46 
12:23:46 ----------------------------------------------------------------------
12:23:46 Ran 1975 tests in 251.605s
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.1-py3.6-test2/5679//console

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by jeffdaily** [comment]
Seems to have become flaky after recent magma upgrade in our CI image.  We need additional time to triage.  We already have a PR to skip this test.
https://github.com/pytorch/pytorch/pull/56951

**Comment by hongxiayang** [comment]
This issue is too old. Would like to close it. Please create a new one if this is still an issue.
