### ISSUE TITLE
Multiple versions of Dockerfiles fail to build

### ISSUE THREAD

**Issue by s1113950** [pytorch/pytorch#5712]
PyTorch GitHub Issues Guidelines
--------------------------------

- OS: Mac
- PyTorch version: master, v0.3.1, v0.3.0, v0.2.0, v0.1.12
- How you installed PyTorch (conda, pip, source):
- Python version: N/A
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): N/A

Version 0.3.1 below:
```
docker build --build-arg HTTP_PROXY=XXXX --build-arg HTTPS_PROXY=XXXX --build-arg http_proxy=XXXX --build-arg https_proxy=XXXX -t test:XXXXX https://github.com/pytorch/pytorch.git#v0.3.1
```
This produces this:
```
WARNING: The following packages cannot be authenticated!
  libnccl2 libnccl-dev
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends          build-essential          cmake          git          curl          vim          ca-certificates          libnccl2=2.0.5-2+cuda8.0          libnccl-dev=2.0.5-2+cuda8.0          libjpeg-dev          libpng-dev &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
UPDATE:
Same goes for v0.3.0

UPDATE:
Running `v0.2.0` fails with below
```
 CMakeFiles/THC.dir/build.make:217: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensorMode.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMode.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/THC.dir/all' failed
    make[1]: *** [CMakeFiles/THC.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    Running setup.py install for torch: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-nvl2npin-build
Command "/opt/conda/envs/pytorch-py35/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-nvl2npin-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k2bx1enk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-nvl2npin-build/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/opt/conda/envs/pytorch-py35/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-nvl2npin-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k2bx1enk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-nvl2npin-build/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 1
```
UPDATE:
Running 0.1.12 gives this, similar to latest versions but different package:
```
WARNING: The following packages cannot be authenticated!
  libcudnn6 libcudnn6-dev
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends          build-essential          cmake          git          curl          ca-certificates          libjpeg-dev          libpng-dev          libcudnn6=$CUDNN_VERSION-1+cuda8.0          libcudnn6-dev=$CUDNN_VERSION-1+cuda8.0 &&      rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
UPDATE:
Running `master` gives this:
```
[ 19%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorMode.cu.o
    Killed
    CMake Error at ATen_generated_THCTensorIndex.cu.o.cmake:267 (message):
      Error generating file
      /tmp/pip-fbuuiu10-build/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/__/THC/./ATen_generated_THCTensorIndex.cu.o


    src/ATen/CMakeFiles/ATen.dir/build.make:154: recipe for target 'src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorIndex.cu.o' failed
    make[2]: *** [src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorIndex.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:233: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
    make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    Running setup.py install for torch: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-fbuuiu10-build
Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fbuuiu10-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-giq0q4m5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-fbuuiu10-build/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fbuuiu10-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-giq0q4m5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-fbuuiu10-build/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 1
```

**Comment by s1113950** [comment]
Possibly this has to do with my Mac setup? I'm going to stop trying other versions now

**Comment by ashahba** [comment]
@s1113950 You want me try building it?

**Comment by s1113950** [comment]
Go for it @ashahba !

**Comment by s1113950** [comment]
@ashahba could be due to the base image being `nvidia/cuda` not working on my machine. I have a gpu but it's not nvidia

**Comment by ashahba** [comment]
It's possible, but I'll find out shortly after I'm out of meeting with my team.

**Comment by ashahba** [comment]
@s1113950 your setup should be fine the only thing is you may need to user `--no-proxy` info as well.
I was able to build both `master` and also `v0.3.1` behind corporate proxy although it took a bit long.

```
Successfully installed pillow-5.0.0 torchvision-0.2.0
Cleaning up...
 ---> 63dce00d2bad
Removing intermediate container 02743c0ec397
Step 13 : WORKDIR /workspace
 ---> Running in f1e33c97eaa3
 ---> 0ffa74b39fa5
Removing intermediate container f1e33c97eaa3
Step 14 : RUN chmod -R a+w /workspace
 ---> Running in 32c626887f44
 ---> 3e6422c72b8f
Removing intermediate container 32c626887f44
Successfully built 3e6422c72b8f
$ docker images
REPOSITORY          TAG                            IMAGE ID            CREATED              SIZE
pytorch             0.3.1                          3e6422c72b8f        About a minute ago   4.416 GB
<none>              <none>                         85cab9281f05        28 minutes ago       3.648 GB
pytorch             latest                         074671e67a8e        43 minutes ago       5.174 GB
nvidia/cuda         9.0-cudnn7-devel-ubuntu16.04   3ada27a3ae03        3 days ago           2.864 GB
nvidia/cuda         8.0-cudnn6-devel-ubuntu16.04   547cf50ecba4        3 days ago           1.97 GB
```

Also since for `v1.3.0` and possibly older versions `/opt/conda/bin` is not added to `PATH` calls to `conda` fail. So in order to build `v0.3.1` I had to make a small change:
```
$ git diff
diff --git a/Dockerfile b/Dockerfile
index cba8b33..b95f612 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -24,7 +24,7 @@ RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-la
 #     /opt/conda/bin/conda install conda-build && \
      /opt/conda/bin/conda create -y --name pytorch-py$PYTHON_VERSION python=$PYTHON_VERSION numpy pyyaml scipy ipython mkl&& \
      /opt/conda/bin/conda clean -ya 
-ENV PATH /opt/conda/envs/pytorch-py$PYTHON_VERSION/bin:$PATH
+ENV PATH /opt/conda/bin:/opt/conda/envs/pytorch-py$PYTHON_VERSION/bin:$PATH
 RUN conda install --name pytorch-py$PYTHON_VERSION -c soumith magma-cuda80
 # This must be done before pip so that requirements.txt is available
 WORKDIR /opt/pytorch
```

**Comment by ashahba** [comment]
I'm so Sorry @s1113950 .
I'm getting the same error as you @s1113950 on both `master` and `v0.3.1` on my MacBook.
The build was successful on my workstation which is behind corporate proxy but this machine has a GPU so most likely the issue is lack of GPU on failing ones.

**Comment by s1113950** [comment]
👍 I have a gpu but not an nvidia one. That's probably the issue I agree!
