### ISSUE TITLE
Intermittent segmentation fault when using rpc_async/rpc_sync with CUDA tensors

### ISSUE THREAD

**Issue by anj-s** [pytorch/pytorch#57136]
## 🐛 Bug

`rpc_sync` (and `rpc_async`) with CUDA tensors result in a segmentation fault at regular intervals. I am not able to reproduce this consistently but happens often enough. 
The error is raised when using `rpc_sync` (and `rpc_async`) for P2P communication between 2 processes on the same machine as well as on remote machines.

Stack Trace:

```
[W tensorpipe_agent.cpp:983] RPC agent for worker0 encountered error when reading incoming response from worker1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:260)
[W tensorpipe_agent.cpp:779] RPC agent for worker0 encountered error when reading incoming request from worker1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:260)
run_worker 0 with world size 2
Traceback (most recent call last):
  File "playground/herring/rpc_perf.py", line 214, in <module>
    mp.spawn(run_worker, args=(args, 2), nprocs=2, join=True)
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGSEGV

```

## To Reproduce
Run the following snippet of code with the --use_cuda_tensors flag.
https://gist.github.com/anj-s/0af840dfe2e9e192c66760a9da59e951

## Expected behavior
There should not be a segmentation fault.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.9.0.dev20210428+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210428+cu111
[pip3] torchaudio==0.9.0.dev20210428
[pip3] torchtext==0.10.0a0+34ccda8
[pip3] torchvision==0.10.0.dev20210428+cu111
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.9.0.dev20210428+cu111           <pip>
[conda] torchaudio                0.9.0.dev20210428           <pip>
[conda] torchtext                 0.10.0a0+34ccda8           <pip>
[conda] torchvision               0.10.0.dev20210428+cu111           <pip>

**Comment by anj-s** [comment]
cc @lw

**Comment by lw** [comment]
I haven't been able to repro this segfault. I ran the repro script a few dozen times on an internal build of PyTorch (from fbcode) on today's master branch. I might try running it on an OSS nightly build just in case. If @anj-s you're still able to repro it, could you add `torch._C._set_print_stack_traces_on_fatal_signal(True)` at the beginning of the `run_worker` function and see if it prints a more useful error stacktrace?

**Comment by lw** [comment]
I also tried on a different machine, with both the OSS 1.9 and nightly releases (for CUDA 10.2) and still didn't manage to repro.

**Comment by anj-s** [comment]
Thanks for taking a look @lw! It looks like I can't repro on a single machine either but it fails with the same errors on multiple machines. Here is the [stack trace](https://gist.github.com/anj-s/3e615541c34dc45a714e4a3aa8ada098).

**Comment by lw** [comment]
Awesome! This looks like the problem:
```
SIGSEGV(11), PID: 1831084, Thread 1831156:
frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x12a (0x7f11eaf85a6a in /private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::FatalSignalHandler::fatalSignalHandler(int) + 0x16a (0x7f11eaf85d7a in /private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x153c0 (0x7f12694e63c0 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #3: <unknown function> + 0x18e70e (0x7f126946d70e in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x35e5a (0x7f114c7d4e5a in /usr/lib/x86_64-linux-gnu/libibverbs/libmlx5-rdmav25.so)
frame #5: <unknown function> + 0x1b246 (0x7f114c7ba246 in /usr/lib/x86_64-linux-gnu/libibverbs/libmlx5-rdmav25.so)
frame #6: tensorpipe::channel::cuda_gdr::IbvNic::pollOnce() + 0x2e (0x7f126759173e in /private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: tensorpipe::channel::cuda_gdr::ContextImpl::pollOnce() + 0x34 (0x7f1267592454 in /private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xf30d6a (0x7f1267599d6a in /private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (tensorpipe::EventLoopDeferredExecutor::*)(std::string), tensorpipe::EventLoopDeferredExecutor*, std::string> > >::_M_run() + 0x41 (0x7f1267599981 in /private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0xd6d84 (0x7f126820cd84 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #11: <unknown function> + 0x9609 (0x7f12694da609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #12: clone + 0x43 (0x7f1269401293 in /lib/x86_64-linux-gnu/libc.so.6)
```
So the segfault happens inside a libibverbs call, namely inside the libmlx5 driver. This reminds me of an issue @beauby was investigating, caused by what we think is a bug in that driver when sending "too small" tensors. @beauby do you think this is the same bug?
