### ISSUE TITLE
torch.nn.utils.weight_norm breaks TorchScript support

### ISSUE THREAD

**Issue by mthrok** [pytorch/pytorch#57289]
## 🐛 Bug

When a Module object is passed to `torch.nn.utils.weight_norm`, it can no longer be scripted.

## To Reproduce

```python
import torch


conv1d = torch.nn.Conv1d(2, 4, 6)
torch.jit.script(conv1d)  # This works

normed = torch.nn.utils.weight_norm(conv1d, name='weight', dim=2)
torch.jit.script(normed)  # this does not work
```

```
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    torch.jit.script(normed)
  File "/fsx/users/moto/conda/lib/python3.8/site-packages/torch/jit/_script.py", line 1047, in script
    return torch.jit._recursive.create_script_module(
  File "/fsx/users/moto/conda/lib/python3.8/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/fsx/users/moto/conda/lib/python3.8/site-packages/torch/jit/_recursive.py", line 426, in create_script_module_impl
    hook_stubs, pre_hook_stubs = get_hook_stubs(nn_module)
  File "/fsx/users/moto/conda/lib/python3.8/site-packages/torch/jit/_recursive.py", line 715, in get_hook_stubs
    if pre_hook.__name__ in hook_map:
AttributeError: 'WeightNorm' object has no attribute '__name__'
```

## Expected behavior

The normalized Module should support TorchScript as well.

## Environment

```
$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.9.0.dev20210429
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210429
[pip3] torchaudio==0.9.0a0+e2bca36
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.9.0.dev20210429 py3.8_cuda10.2_cudnn7.6.5_0    pytorch-nightly
[conda] torchaudio                0.9.0a0+e2bca36           dev_0    <develop>
```

## Additional context

- I am trying to convert a pre-trained model from `fairseq`, so I have no control on how model parameter is initialized, but that does not matter to me because my goal is to script the model with trained parameters.
- See also https://github.com/pytorch/pytorch/issues/21275

**Comment by SplitInfinity** [comment]
`weight_norm` tries to use an instance of a class with `__call__` defined (`WeightNorm`) as a forward pre hook. 
```
fn = WeightNorm(name, dim)

module.register_forward_pre_hook(fn)

class WeightNorm:
    def __call__(...):
        ...
```
This throws an error because the hook scripting code in `_recursive.py` uses `hook.__name__` to make sure two hook functions do not have the same name, and `fn` above does not have a `__name__` attribute.

Taking a step back, the current implementation of scripted static hooks cannot support generic callables. We throw an error when non-function callables are used as hooks and consider adding support for other kinds of callables.

**Comment by mthrok** [comment]
I see. Thanks for the info.
Is it possible to make it TorchScript compatible when the target module is TorchScript compatible?

**Comment by c9412600** [comment]
hello,is your problem solved?

**Comment by andjelatodorovich** [comment]
I have the same problem when using Wav2Vec2 from HuggingFace. How to avoid it?

**Comment by evrrn** [comment]
If you like me use **jit scripting only on inference**, during this phase you do not change the layers weights so there is no need in their normalization. So I used to **apply [remove_weight_norm function](https://pytorch.org/docs/stable/generated/torch.nn.utils.remove_weight_norm.html) to every layer, that was previously normalized**:

```
for layer in layers_with_weight_norm:
   torch.nn.utils.remove_weight_norm(layer)
```

This works for me, hope it'll be helpful.

**Comment by evrrn** [comment]
@fijipants 

Yes, I first load the checkpoint, then apply remove_weight_norm

**Comment by WHU-gentle** [comment]
> 



> 

How to get layers_with_weight_norm?

**Comment by WHU-gentle** [comment]
I have solved this problem, using a custom function following `remove_weight_norm ` to remove the weight norm. The following is the code. I am not sure whether it is standard and proper, but it did work.
```
def remove_weight_norm(module):
    module_list = [mod for mod in module.children()]
    if len(module_list) == 0:
        for k, hook in module._forward_pre_hooks.items():
            if isinstance(hook, WeightNorm):
                hook.remove(module)
                del module._forward_pre_hooks[k]
    else:
        for mod in module_list:
            remove_weight_norm(mod)
```

**Comment by victor-shepardson** [comment]
this appears to work as a scriptable weight norm for training. (had to hard code the name and dimension, torchscript seems unable to close a function over them similarly to how it can't handle a callable. it also won't do `setattr` with a computed name):

```python
from torch.nn.parameter import Parameter, UninitializedParameter
from torch import _weight_norm, norm_except_dim, Tensor
from typing import Any, TypeVar, Tuple
from torch.nn import Module

__all__ = [
    'weight_norm',
    'remove_weight_norm'
    ]

T_module = TypeVar('T_module', bound=Module)

def weight_norm(module: T_module) -> T_module:

    def fn(module: Module, inputs: Tuple[Tensor]) -> None:
        module.weight = _weight_norm(module.weight_v, module.weight_g, 0)

    fn.is_weight_norm = True

    weight = getattr(module, 'weight')
    if isinstance(weight, UninitializedParameter):
        raise ValueError(
            'The module passed to `WeightNorm` can\'t have uninitialized parameters. '
            'Make sure to run the dummy forward before applying weight normalization')
    # remove w from parameter list
    del module._parameters['weight']

    # add g and v as new parameters and express w as g/||v|| * v
    module.register_parameter('weight_g', Parameter(norm_except_dim(weight, 2, 0).data))
    module.register_parameter('weight_v', Parameter(weight.data))
    fn(module, None)

    # recompute weight before every forward()
    module.register_forward_pre_hook(fn)

    return module

def remove_weight_norm(module: T_module) -> T_module:
    for k, hook in module._forward_pre_hooks.items():
        if hasattr(hook, 'is_weight_norm') and hook.is_weight_norm:
            weight = _weight_norm(module.weight_v, module.weight_g, 0)
            delattr(module, 'weight')
            del module._parameters['weight_g']
            del module._parameters['weight_v']
            module.weight = Parameter(weight.data)

            del module._forward_pre_hooks[k]
            return module
```

**Comment by matthijsvk** [comment]
I'm applying this to the weight of an nn.Linear inside a torch.jit.ScriptModule
I'm still getting "RuntimeError: cannot delete methods or parameters of a script module"

**Comment by mthrok** [comment]
For those looking for a solution, you can define `__prepare_scriptable__` method to remove the weight norm automatically when scripting.

https://github.com/pytorch/audio/blob/8690e6ec9b419299076ef333d9d25d1f59fe92b1/torchaudio/models/wav2vec2/components.py#L214-L223
