### ISSUE TITLE
test_cudnn_multiple_threads_same_device is flaky

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#57401]
## 🐛 Bug

Sometimes CI will fail with this:

```
======================================================================
FAIL [0.830s]: test_cudnn_multiple_threads_same_device (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 439, in wrapper
    fn(*args, **kwargs)
  File "test_cuda.py", line 2505, in test_cudnn_multiple_threads_same_device
    (2048 - test_iters) * (2048 - test_iters))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 1397, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing 1425636.0 and 1098304 gives a difference of 327332.0, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 1.4278052!

----------------------------------------------------------------------
Ran 159 tests in 41.540s

FAILED (failures=1, skipped=59)

Generating XML reports...
Generated XML report: test-reports\python-unittest\test_cuda\TEST-TestCuda-20210430175253.xml
Generated XML report: test-reports\python-unittest\test_cuda\TEST-TestCudaComm-20210430175253.xml
Traceback (most recent call last):
```

I observed this failure a long time ago, but recently it is becoming more often.

cc: @ngimel  @ptrblck @mcarilli 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mruberry** [comment]
Happened 3 times in a row today on periodic_pytorch_windows_cuda11.2_test1

**Comment by vladimir-aubrecht** [comment]
Test is not failing pipeline anymore as it was disabled year ago. Problem might or might not persist.
