### ISSUE TITLE
test_reduce_checks (__main__.ProcessGroupGlooTest) is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#57469]
test_reduce_checks is flaky, see:
```
May 03 06:42:34 ======================================================================
May 03 06:42:34 ERROR [0.128s]: test_reduce_checks (__main__.ProcessGroupGlooTest)
May 03 06:42:34 ----------------------------------------------------------------------
May 03 06:42:34 Traceback (most recent call last):
May 03 06:42:34   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 374, in wrapper
May 03 06:42:34     self._join_processes(fn)
May 03 06:42:34   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 566, in _join_processes
May 03 06:42:34     self._check_return_codes(elapsed_time)
May 03 06:42:34   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 609, in _check_return_codes
May 03 06:42:34     raise RuntimeError(error)
May 03 06:42:34 RuntimeError: Process 0 exited with error code 10 and exception:
May 03 06:42:34 Traceback (most recent call last):
May 03 06:42:34   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 492, in run_test
May 03 06:42:34     getattr(self, test_name)()
May 03 06:42:34   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 376, in wrapper
May 03 06:42:34     fn()
May 03 06:42:34   File "distributed/test_c10d_gloo.py", line 1037, in test_reduce_checks
May 03 06:42:34     pg = c10d.ProcessGroupGloo(store, self.rank, self.world_size, self.opts())
May 03 06:42:34 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:35521
```

https://app.circleci.com/pipelines/github/pytorch/pytorch/314912/workflows/2598a16d-265b-4cc3-991a-69ffb4e08d22/jobs/13094781

Not disabling yet as I've only seen it once. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
Additional failures have not been encountered even though this test was not disabled, and could not repro locally even after 1000+ runs. Will close and reinvestigate as needed.

**Comment by rohan-varma** [comment]
Another failure - https://app.circleci.com/pipelines/github/pytorch/pytorch/347608/workflows/052c4498-01c7-4b9d-bd93-cd4463d474dc/jobs/14640771

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/pull/61396 is an attempt to fix this, close to let it run in CI
