### ISSUE TITLE
`TestLinAlgCUDA.test_inverse_errors_large_cuda_float64` failing for CUDA 11.3 on Windows

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#57482]
The test fails with error: `RuntimeError: CUDA error: too many resources requested for launch` when executing `torch.inverse`. 

Logs: 
https://app.circleci.com/pipelines/github/pytorch/pytorch/314168/workflows/e7b9471e-b734-451d-927a-b16cd9fd57f5/jobs/13063189

This is only on Windows. The same test passed for Linux 11.3 on CI: https://app.circleci.com/pipelines/github/pytorch/pytorch/314166/workflows/4d4b805e-45be-4eb8-85e3-f79a61615b2a/jobs/13066285

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by zasdfgbnm** [comment]
cc: @xwang233

**Comment by xwang233** [comment]
Thanks @janeyx99 . I see that MAGMA is installed in the CI. This test https://github.com/pytorch/pytorch/blob/4a872f85396b426f7e26ee20c25e7916d45f70e2/test/test_linalg.py#L3205 is then dispatched to MAGMA backend. Tentatively assuming a MAGMA issue.

**Comment by ngimel** [comment]
@janeyx99 is it possible to get a backtrace for this error?

**Comment by janeyx99** [comment]
@ngimel Do you mean something more specific than what's already in the logs? (The below)
```
RuntimeError: CUDA error: too many resources requested for launch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 617, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 765, in only_fn
    return fn(self, device, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 617, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_linalg.py", line 3121, in test_inverse_errors_large
    torch.inverse(x)
AssertionError: "For batch 0: U\(11,11\) is zero" does not match "CUDA error: too many resources requested for launch"
```

**Comment by ngimel** [comment]
Yeah, cpp stack trace would be better (on linux that would be the one shown with `export TORCH_SHOW_CPP_STACKTRACES=0`)

**Comment by janeyx99** [comment]
I reran with SSH and turned on that variable to get this:
```
(base) C:\Users\circleci\project>python test/test_linalg.py TestLinalgCUDA.test_inverse_errors_large_cuda_float64
C:\Jenkins\Miniconda3\lib\site-packages\numba\cuda\envvars.py:16: NumbaDeprecationWarning:
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_NVVM=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\nvvm\bin\nvvm64_32_0.dll.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
C:\Jenkins\Miniconda3\lib\site-packages\numba\cuda\envvars.py:16: NumbaDeprecationWarning:
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_CUDALIB=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))

Running tests...
----------------------------------------------------------------------
Couldn't download test skip set, leaving all tests enabled...
F
======================================================================
FAIL [3.148s]: test_inverse_errors_large_cuda_float64 (__main__.TestLinalgCUDA)
----------------------------------------------------------------------
RuntimeError: CUDA error: too many resources requested for launch
Exception raised from at::native::magmaLuBatched at C:\Users\circleci\project\aten\src\ATen\native\cuda\BatchLinearAlgebra.cu:278 (most recent call first):
00007FFE1539113200007FFE153910D0 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFE15390D9E00007FFE15390D50 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFDA52D14C000007FFDA52CFBC0 torch_cuda_cu.dll!at::native::avg_pool3d_out_cuda [<unknown file> @ <unknown line number>]
00007FFDA52E322700007FFDA52E2FB0 torch_cuda_cu.dll!at::native::_inverse_helper_cuda [<unknown file> @ <unknown line number>]
00007FFDA52E2FE800007FFDA52E2FB0 torch_cuda_cu.dll!at::native::_inverse_helper_cuda [<unknown file> @ <unknown line number>]
00007FFDA6628D9500007FFDA651EB50 torch_cuda_cu.dll!at::native::set_storage_cuda_ [<unknown file> @ <unknown line number>]
00007FFDA65F739A00007FFDA651EB50 torch_cuda_cu.dll!at::native::set_storage_cuda_ [<unknown file> @ <unknown line number>]
00007FFDBD52A6E200007FFDBD52A5C0 torch_cpu.dll!at::_inverse_helper [<unknown file> @ <unknown line number>]
00007FFDBD02D68500007FFDBD02D620 torch_cpu.dll!at::native::inverse [<unknown file> @ <unknown line number>]
00007FFDBDA0D20E00007FFDBD8B5B10 torch_cpu.dll!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBD9F2A8F00007FFDBD8B5B10 torch_cpu.dll!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBD73877700007FFDBD7198F0 torch_cpu.dll!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBD7FFB4E00007FFDBD7FFAE0 torch_cpu.dll!at::redispatch::inverse [<unknown file> @ <unknown line number>]
00007FFDBEBDAD4000007FFDBE9C6930 torch_cpu.dll!torch::jit::Value::wrap [<unknown file> @ <unknown line number>]
00007FFDBEBC30A200007FFDBE9C6930 torch_cpu.dll!torch::jit::Value::wrap [<unknown file> @ <unknown line number>]
00007FFDBDBA5EE200007FFDBDBA5DC0 torch_cpu.dll!at::Tensor::inverse [<unknown file> @ <unknown line number>]
00007FFDF63ADFDB00007FFDF63A20B0 torch_python.dll!torch::FunctionSignature::operator= [<unknown file> @ <unknown line number>]
00007FFDF64F66C500007FFDF63A20B0 torch_python.dll!torch::FunctionSignature::operator= [<unknown file> @ <unknown line number>]
000000005F608426000000005F6080A0 python36.dll!PyCFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F608909000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F60933E000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F608D76000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F60933E000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F608D76000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F609F08000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F608D76000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F609F08000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F605383000000005F6051E0 python36.dll!PyFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F605166000000005F604EB8 python36.dll!PyType_GenericNew [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F605383000000005F6051E0 python36.dll!PyFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F605166000000005F604EB8 python36.dll!PyType_GenericNew [<unknown file> @ <unknown line number>]
000000005F600CFC000000005F600CA0 python36.dll!PyObject_Call [<unknown file> @ <unknown line number>]
000000005F5DAA93000000005F5DAA20 python36.dll!PyOS_FSPath [<unknown file> @ <unknown line number>]
000000005F608C59000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F60933E000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F605383000000005F6051E0 python36.dll!PyFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F605166000000005F604EB8 python36.dll!PyType_GenericNew [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 617, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 765, in only_fn
    return fn(self, device, *args, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 617, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test/test_linalg.py", line 3121, in test_inverse_errors_large
    torch.inverse(x)
AssertionError: "For batch 0: U\(11,11\) is zero" does not match "CUDA error: too many resources requested for launch
Exception raised from at::native::magmaLuBatched at C:\Users\circleci\project\aten\src\ATen\native\cuda\BatchLinearAlgebra.cu:278 (most recent call first):
00007FFE1539113200007FFE153910D0 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFE15390D9E00007FFE15390D50 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFDA52D14C000007FFDA52CFBC0 torch_cuda_cu.dll!at::native::avg_pool3d_out_cuda [<unknown file> @ <unknown line number>]
00007FFDA52E322700007FFDA52E2FB0 torch_cuda_cu.dll!at::native::_inverse_helper_cuda [<unknown file> @ <unknown line number>]
00007FFDA52E2FE800007FFDA52E2FB0 torch_cuda_cu.dll!at::native::_inverse_helper_cuda [<unknown file> @ <unknown line number>]
00007FFDA6628D9500007FFDA651EB50 torch_cuda_cu.dll!at::native::set_storage_cuda_ [<unknown file> @ <unknown line number>]
00007FFDA65F739A00007FFDA651EB50 torch_cuda_cu.dll!at::native::set_storage_cuda_ [<unknown file> @ <unknown line number>]
00007FFDBD52A6E200007FFDBD52A5C0 torch_cpu.dll!at::_inverse_helper [<unknown file> @ <unknown line number>]
00007FFDBD02D68500007FFDBD02D620 torch_cpu.dll!at::native::inverse [<unknown file> @ <unknown line number>]
00007FFDBDA0D20E00007FFDBD8B5B10 torch_cpu.dll!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBD9F2A8F00007FFDBD8B5B10 torch_cpu.dll!at::redispatch::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBD73877700007FFDBD7198F0 torch_cpu.dll!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FFDBD7FFB4E00007FFDBD7FFAE0 torch_cpu.dll!at::redispatch::inverse [<unknown file> @ <unknown line number>]
00007FFDBEBDAD4000007FFDBE9C6930 torch_cpu.dll!torch::jit::Value::wrap [<unknown file> @ <unknown line number>]
00007FFDBEBC30A200007FFDBE9C6930 torch_cpu.dll!torch::jit::Value::wrap [<unknown file> @ <unknown line number>]
00007FFDBDBA5EE200007FFDBDBA5DC0 torch_cpu.dll!at::Tensor::inverse [<unknown file> @ <unknown line number>]
00007FFDF63ADFDB00007FFDF63A20B0 torch_python.dll!torch::FunctionSignature::operator= [<unknown file> @ <unknown line number>]
00007FFDF64F66C500007FFDF63A20B0 torch_python.dll!torch::FunctionSignature::operator= [<unknown file> @ <unknown line number>]
000000005F608426000000005F6080A0 python36.dll!PyCFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F608909000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F60933E000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F5EC02D000000005F5EBBC0 python36.dll!PyBytes_FromStringAndSize [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F608D76000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F60933E000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F608D76000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F609F08000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F608D76000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F609F08000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F605383000000005F6051E0 python36.dll!PyFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F605166000000005F604EB8 python36.dll!PyType_GenericNew [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F605383000000005F6051E0 python36.dll!PyFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F605166000000005F604EB8 python36.dll!PyType_GenericNew [<unknown file> @ <unknown line number>]
000000005F600CFC000000005F600CA0 python36.dll!PyObject_Call [<unknown file> @ <unknown line number>]
000000005F5DAA93000000005F5DAA20 python36.dll!PyOS_FSPath [<unknown file> @ <unknown line number>]
000000005F608C59000000005F608570 python36.dll!PyObject_GetAttr [<unknown file> @ <unknown line number>]
000000005F60933E000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
000000005F605383000000005F6051E0 python36.dll!PyFunction_FastCallDict [<unknown file> @ <unknown line number>]
000000005F605166000000005F604EB8 python36.dll!PyType_GenericNew [<unknown file> @ <unknown line number>]
000000005F600998000000005F600268 python36.dll!PyUnicodeWriter_WriteSubstring [<unknown file> @ <unknown line number>]
000000005F60A0B7000000005F609090 python36.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
000000005F606D88000000005F6068F0 python36.dll!PyUnicode_RichCompare [<unknown file> @ <unknown line number>]
"

----------------------------------------------------------------------
Ran 1 test in 3.148s

FAILED (failures=1)

Generating XML reports...

(base) C:\Users\circleci\project>
```

**Comment by janeyx99** [comment]
CUDA 11.5 hits the same issue. Example failures on my PR: https://hud.pytorch.org/pr/pytorch/pytorch/70010

**Comment by IvanYashchuk** [comment]
What GPU is used in Windows CI, it might be specific to the certain architecture because the MAGMA codebase has a few of these branches.

**Comment by Lezcano** [comment]
This is going to be affected by https://github.com/pytorch/pytorch/pull/80074
