### ISSUE TITLE
INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 

### ISSUE THREAD

**Issue by kylematoba** [pytorch/pytorch#57684]
## 🐛 Bug

```
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 
```

## To Reproduce

```
import torch
if __name__ == "__main__":
    a = torch.zeros(1, 2, 4, 4)
    b = torch.nn.Conv2d(2, 2, 2)(a)
    b = b.view(-1, b.size(-1))
    b.unique_consecutive(dim=0)

Traceback (most recent call last):
  File "<input>", line 9, in <module>
  File "/Users/kylematoba/xyz/localenv/lib/python3.9/site-packages/torch/tensor.py", line 504, in unique_consecutive
    return torch.unique_consecutive(self, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
  File "/Users/kylematoba/xyz/localenv/lib/python3.9/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/Users/kylematoba/xyz/localenv/lib/python3.9/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/Users/kylematoba/xyz/localenv/lib/python3.9/site-packages/torch/functional.py", line 832, in _consecutive_return_output
    output, _, _ = _unique_consecutive_impl(input, return_inverse, return_counts, dim)
  File "/Users/kylematoba/xyz/localenv/lib/python3.9/site-packages/torch/functional.py", line 744, in _unique_consecutive_impl
    output, inverse_indices, counts = _VF.unique_consecutive(  # type: ignore
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 

```
## Expected behavior
Not ask me to report a bug.

## Environment

```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A
OS: macOS 11.2.3 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: Could not collect
Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect

```

## Additional context

None

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by gchanan** [comment]
I was able to reproduce this on 1.7.1, but it's fixed on trunk.
