### ISSUE TITLE
torch.sum throws `Function not yet implemented for AVX2`

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#5770]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS: Windows
- PyTorch version: master(0476a2346b9f364e98971002c96269f64568a785)
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.3
- CUDA/cuDNN version: 8.0
- GPU models and configuration: -
- GCC version (if compiling from source): MSVC 2017

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

```pytb
>>> import torch
>>> torch.sum([1,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sum(): argument 'input' (position 1) must be Tensor, not list
>>> torch.sum(torch.Tensor([1.,2.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Function not yet implemented for AVX2
```

**Comment by peterjc123** [comment]
Fixed by #5765.
