### ISSUE TITLE
TorchScript JIT Compiler Can't Recognize Repeated Branches (Scripting)

### ISSUE THREAD

**Issue by dtoniolo** [pytorch/pytorch#57717]
## 🐛 Bug

The TorchScript JIT compiler (via scripting) can't recognise some combination of branches will never be accessed, or that the same logical branch can be referred to in multiple places in the code. Scripting fails even when type hinting is provided.

## To Reproduce

Define the class
```python
import torch
from torch import nn


class SadModule(nn.Module):
    """Takes a (*, 2) input and runs it thorugh a linear layer. Can optionally
    use a skip connection. The usage of the skip connection or not is an
    architectural choice.

    """
    def __init__(self, use_skip: bool):
        nn.Module.__init__(self)
        self.use_skip = use_skip
        self.layer = nn.Linear(2, 2)

    def forward(self, x):
        if self.use_skip:
            x_input = x
        x = self.layer(x)
        if self.use_skip:
            x = x + x_input
        return x
```

and try to script it:
```python
mod1 = SadModule(False)
scripted_mod1 = torch.jit.script(mod)
```
It will result in the following error:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-a7ebc7af32c7> in <module>
----> 1 scripted_mod1 = torch.jit.script(mod)

~/Software/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    895
    896     if isinstance(obj, torch.nn.Module):
--> 897         return torch.jit._recursive.create_script_module(
    898             obj, torch.jit._recursive.infer_methods_to_compile
    899         )

~/Software/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types)
    350     check_module_initialized(nn_module)
    351     concrete_type = get_module_concrete_type(nn_module, share_types)
--> 352     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    353
    354 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

~/Software/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    408     # Compile methods if necessary
    409     if concrete_type not in concrete_type_store.methods_compiled:
--> 410         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    411         torch._C._run_emit_module_hook(cpp_module)
    412         concrete_type_store.methods_compiled.add(concrete_type)

~/Software/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    302     property_rcbs = [p.resolution_callback for p in property_stubs]
    303
--> 304     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    305
    306

RuntimeError:

x_input is not defined in the false branch:
  File "<ipython-input-7-d08ed7ff42ec>", line 12
    def forward(self, x):
        if self.use_skip:
        ~~~~~~~~~~~~~~~~~
            x_input = x
            ~~~~~~~~~~~ <--- HERE
        x = self.layer(x)
        if self.use_skip:
and was used here:
  File "<ipython-input-7-d08ed7ff42ec>", line 16
        x = self.layer(x)
        if self.use_skip:
            x = x + x_input
                    ~~~~~~~ <--- HERE
        return x
```

The error persists even if `use_skip` is type hinted as constant:
```python
from typing import Final

class SadModule(nn.Module):
    use_skip: Final[bool]
    ...
```

## Expected behavior
The above code is logically well defined and the two branches are either both `True` or both `False`. The TorchScript JIT should be able to recognise this at least when `use_skip` is type hinted as constant.

## Environment
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0
[pip3] torch-cluster==1.5.8
[pip3] torch-geometric==1.6.1
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.8
[pip3] torch-spline-conv==1.2.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.1
[conda] numpy                     1.19.5                   pypi_0    pypi

## Additional context

It is true that, to avoid the issue, I could split the class into two subclasses, as in:
```python
class SadModuleNoSkip(nn.Module):
    """Takes a (*, 2) input and runs it thorugh a linear layer. Can optionally
    use a skip connection. The usage of the skip connection or not is an
    architectural choice.

    """
    def __init__(self):
        nn.Module.__init__(self)
        self.layer = nn.Linear(2, 2)

    def forward(self, x):
        x = self.layer(x)
        return x

class SadModuleSkip(nn.Module):
    """Takes a (*, 2) input and runs it thorugh a linear layer. Can optionally
    use a skip connection. The usage of the skip connection or not is an
    architectural choice.

    """
    def __init__(self):
        nn.Module.__init__(self)
        self.layer = nn.Linear(2, 2)

    def forward(self, x):
        x_input = x
        x = self.layer(x)
        x = x + x_input
        return x
```
However, I am working on a huge code base and I would have to repeat the process for many classes, which is time consuming and could introduce bugs. Moreover, often the modules I'm working on are huge convolutional nets and the ifs just control the presence of an additional batch normalization. It seems to me undesirable to have to classes that are identical in 99% of the blocks, save for a single batch norm layer.

Finally, it seems to me that TorchScript scripting should be able to handle this situation

**Comment by nikithamalgifb** [comment]
For now as a workaround, can you try this below in forward? Basically define `x_input` before assigning in `if`

```
def forward(self, x):
        x_input = torch.empty_like(x)
        if self.use_skip:
            x_input = x
        x = self.layer(x)
        if self.use_skip:
            x = x + x_input
        return x
```

**Comment by dtoniolo** [comment]
Thanks, in this way I can make it work. For anyone that stumbles upon this issue, using `torch.empty_like` takes up extra memory, so in order to be more efficient I'd do:
```python
def forward(self, x):
        x_input = x
        if self.use_skip:
            x_input = x
        x = self.layer(x)
        if self.use_skip:
            x = x + x_input
        return x
```
In this way `x_input` is just a reference to the input `x`, with no data new data creation.

While I'm using this workaround, can you confirm that this is indeed a bug/missing feature in the JIT and that I'm not doing something wrong?

**Comment by eellison** [comment]
This also works if you mark `use_skip` as Final/Constant.
```
class SadModule(nn.Module):
    """Takes a (*, 2) input and runs it thorugh a linear layer. Can optionally
    use a skip connection. The usage of the skip connection or not is an
    architectural choice.

    """
    __constants__ = ['use_skip']

    def __init__(self, use_skip: bool):
        nn.Module.__init__(self)
        self.use_skip = use_skip
        self.layer = nn.Linear(2, 2)

    def forward(self, x):
        if self.use_skip:
            x_input = x
        x = self.layer(x)
        if self.use_skip:
            x = x + x_input
        return x

torch.jit.script(SadModule(True))
torch.jit.script(SadModule(False))
```

CC @gmagogsfm better documentation of metaprogramming and related issue: https://github.com/pytorch/pytorch/issues/53414

**Comment by dtoniolo** [comment]
Doesn't work for me, I get the same error, and according to the [docs page on JIT](https://pytorch.org/docs/stable/jit.html), using `__constants__` is equivalent to `Final`. The former is deprecated in favour of the latter.

That issue however confirms that it's actually a problem with the JIT.

**Comment by eellison** [comment]
@dtoniolo I think this works on master, not the latest release.

**Comment by dtoniolo** [comment]
@eellison You're right. I've downloaded the `pytorch-nightly` and it works. Thank you all for your support👍🏻

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
