### ISSUE TITLE
calling register_buffer in forward of jited module fails

### ISSUE THREAD

**Issue by joh4n** [pytorch/pytorch#57740]
## 🐛 Bug
Calling `.register_buffer` in the forward of an nn module fails when trying to use jit.

## To Reproduce
Minimal example:
```python
import torch

class Net(torch.nn.Module):
    def forward(self):
        self.register_buffer('test', torch.ones(1))
        return self.test

net = Net()
net() #== tensor([1.]) 
torch.jit.script(net) # RuntimeError
```
the error:
```
RuntimeError  Traceback (most recent call last)
<ipython-input-30-dcabad8ebb17> in <module>
----> 1 torch.jit.script(net)

/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    941         obj = call_prepare_scriptable_func(obj)
    942         return torch.jit._recursive.create_script_module(
--> 943             obj, torch.jit._recursive.infer_methods_to_compile
    944         )
    945

/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types)
    389     check_module_initialized(nn_module)
    390     concrete_type = get_module_concrete_type(nn_module, share_types)
--> 391     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    392
    393 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    450     # Compile methods if necessary
    451     if concrete_type not in concrete_type_store.methods_compiled:
--> 452         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    453         # Create hooks after methods to ensure no name collisions between hooks and methods.
    454         # If done before, hooks can overshadow methods that aren't exported.

/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    333     property_rcbs = [p.resolution_callback for p in property_stubs]
    334
--> 335     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    336
    337 def create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs):

/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/jit/_recursive.py in compile_unbound_method(concrete_type, fn)
    780         # We don't want to call the hooks here since the graph that is calling
    781         # this function is not yet complete
--> 782         create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
    783     return stub
    784

/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    333     property_rcbs = [p.resolution_callback for p in property_stubs]
    334
--> 335     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    336
    337 def create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs):

RuntimeError:
Unknown type name 'torch.jit.ScriptModule':
  File "/run/media/johan/1db46b5f-db24-403e-af85-594a510d545e/py-envs/borch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 296

        """
        if persistent is False and isinstance(self, torch.jit.ScriptModule):
                                                    ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            raise RuntimeError("ScriptModule does not support non-persistent buffers")

'Net.register_buffer' is being compiled since it was called from 'Net.forward'
  File "<ipython-input-27-75598b00b67c>", line 3
    def forward(self):
        self.register_buffer('test', torch.ones(1))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return self.test

```
## Expected behavior
I would like to be able to call `.register_buffer` in the forward of a module

## Environment
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce MX250
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.5
[pip3] torch==1.8.1
[pip3] torchvision==0.9.1
[conda] Could not collect

cc @gmagogsfm

**Comment by nikithamalgifb** [comment]
Unfortunately, this is not supported for now. Can you call `register_buffer` from `init` instead?

**Comment by joh4n** [comment]
The implementation I was playing with needed to update the buffer in every forward pass. But looking at the code for `.register_buffer` I could try to register it in the init and then use `self._buffers[name]` in the forward for now

**Comment by nikithamalgifb** [comment]
You can do something like this:

```
class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("test", torch.tensor([1]))

    def forward(self, b):
        self.test = torch.tensor(1, 3)
        return self.test
```

**Comment by gmagogsfm** [comment]
To add on @nikithamalgifb said, TorchScript requires a fully initialized static modules, thus it is unsupported to register new buffer in the middle of forward by design.
