### ISSUE TITLE
a error when torch.load(）

### ISSUE THREAD

**Issue by huanghanmei** [pytorch/pytorch#57805]
Traceback (most recent call last):
  File "temp.py", line 25, in <module>
    check = torch.load(path,map_location="cpu")
  File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94308821128336

**Comment by ngimel** [comment]
You have a clear error message "file not found: archive/data/94308821128336"

**Comment by Zhang-O** [comment]
> Traceback (most recent call last): File "temp.py", line 25, in check = torch.load(path,map_location="cpu") File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 594, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load result = unpickler.load() File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load load_tensor(data_type, size, key, _maybe_decode_ascii(location)) File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor storage = zip_file.get_storage_from_record(name, size, dtype).storage() RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94308821128336

Two possibile reasons:
1. your file is corupted
2.  you save your checkpoint in DDP training style with writing file of multi-processes, which induces a unsave writing.
