### ISSUE TITLE
Using NNAPI model in Android

### ISSUE THREAD

**Issue by zhao028** [pytorch/pytorch#57803]
I successfully converted the nnapi model of mobilenet according to the official blog，According to the official statement, it can be called directly on the original project through the API. The following is how I load the model，
  `model = Module.load(assetFilePath(this, "mobilenetv2-quant_none-nnapi.pt"));`
But this will give the following error：
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.opencv, PID: 23334
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.opencv/com.example.opencv.MainActivity}: com.facebook.jni.CppException: 
    Unknown type name 'NoneType':
    Serialized   File "code/__torch__/torch/backends/_nnapi/prepare.py", line 15
      __buffers__ = []
      training : bool
      _is_full_backward_hook : NoneType
                               ~~~~~~~~ <--- HERE
      ser_model : Tensor
      weights : List[Tensor]
    
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3898)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: com.facebook.jni.CppException: 
    Unknown type name 'NoneType':
    Serialized   File "code/__torch__/torch/backends/_nnapi/prepare.py", line 15
      __buffers__ = []
      training : bool
      _is_full_backward_hook : NoneType
                               ~~~~~~~~ <--- HERE
      ser_model : Tensor
      weights : List[Tensor]
    
        at org.pytorch.NativePeer.initHybrid(Native Method)
        at org.pytorch.NativePeer.<init>(NativePeer.java:25)
        at org.pytorch.Module.load(Module.java:25)
        at org.pytorch.Module.load(Module.java:35)
        at com.example.opencv.MainActivity.onCreate(MainActivity.java:198)
        at android.app.Activity.performCreate(Activity.java:8121)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3871)
        	... 11 more
```

I don’t know where there is a problem in the process, if you know the solution, please tell me, thank you！

**Comment by cometonf** [comment]
I have the same issue.

**Comment by axitkhurana** [comment]
@cometonf what's the pytorch version for conversion and libtorch version on the app that you're using?

**Comment by cometonf** [comment]
@axitkhurana For this issue, the versions were
```
# pytorch for conversion
torch                     1.9.0.dev20210427+cpu
torchvision               0.10.0.dev20210427+cpu

# libtorch on the app
    implementation 'org.pytorch:pytorch_android:1.8.0'
    implementation 'org.pytorch:pytorch_android_torchvision:1.8.0'
``` 
I resolved this by changing versions of them like [issue#50533](https://github.com/pytorch/pytorch/issues/50533)


However, there was a new issue when I checked with [PyTorchDemoApp](https://github.com/pytorch/android-demo-app/tree/master/PyTorchDemoApp).
I tested two cases,
```
# pytorch for conversion
torch                     1.9.0.dev20210503+cpu
torchvision               0.10.0.dev20210503+cpu

# libtorch on the app
    implementation 'org.pytorch:pytorch_android:1.9.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.9.0-SNAPSHOT'
``` 
```
# pytorch for conversion
torch                     1.10.0.dev20210608+cpu
torchvision               0.11.0.dev20210608+cpu

# libtorch on the app
    implementation 'org.pytorch:pytorch_android:1.10.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.10.0-SNAPSHOT'
``` 

and got this log,
```
2021-06-09 08:57:28.969 30810-30937/org.pytorch.demo E/AndroidRuntime: FATAL EXCEPTION: ModuleActivity
    Process: org.pytorch.demo, PID: 30810
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpytorch_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:22)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
        at org.pytorch.NativePeer.<clinit>(NativePeer.java:10)
        at org.pytorch.Module.load(Module.java:28)
        at org.pytorch.Module.load(Module.java:38)
        at org.pytorch.demo.vision.ImageClassificationActivity.analyzeImage(ImageClassificationActivity.java:166)
        at org.pytorch.demo.vision.ImageClassificationActivity.analyzeImage(ImageClassificationActivity.java:31)
        at org.pytorch.demo.vision.AbstractCameraXActivity.lambda$setupCameraX$2$AbstractCameraXActivity(AbstractCameraXActivity.java:90)
        at org.pytorch.demo.vision.-$$Lambda$AbstractCameraXActivity$t0OjLr-l_M0-_0_dUqVE4yqEYnE.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:57)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:135)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Do you have any idea?

**Comment by H1Gdev** [comment]
@cometonf

Looking at callstack, I think cause is this issue.
https://github.com/pytorch/pytorch/commit/0c3db1cb33cda1de61c754f14e7bfd2c53ea6d07#r51222309

**Comment by axitkhurana** [comment]
Hi @cometonf, sorry for the trouble, glad you were able to figure out the torch versions. We recently switched to the lite interpreter or nightlies, so @IvanKobzarev suggested the following change:

```
Module.load(targetFile.getAbsolutePath(), extraFiles, Device.CPU);
-->
Module module = LiteModuleLoader.load(targetFile.getAbsolutePath(), extraFiles, Device.CPU);
```

Hope this helps!
