### ISSUE TITLE
quantize_per_tensor not symbolically traceable with FX if scale+zp are proxied

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#58051]
## 🐛 Bug

Unable to symbolically trace a `torch.quantize_per_tensor` method call with FX if scale and zero_point are proxied.

## To Reproduce

```
# code
import torch                                                       
from torch.quantization.quantize_fx import prepare_fx, convert_fx  
from torch.fx.experimental import normalize                        
                                                                   
                                                                   
class M(nn.Module):                                                
    def __init__(self):                                            
        super().__init__()                                         
        self.dtype = torch.quint8                                  
                                                                   
    def forward(self, x, scale, zp):                               
        return torch.quantize_per_tensor(x, scale, zp, self.dtype) 
                                                                   
mp = torch.fx.symbolic_trace(M())                                  

# error

Traceback (most recent call last):
  File "/home/vasiliy/local/tmp/test.py", line 28, in <module>
    mp = torch.fx.symbolic_trace(M())
  File "/data/users/vasiliy/pytorch/torch/fx/symbolic_trace.py", line 771, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/users/vasiliy/pytorch/torch/fx/symbolic_trace.py", line 483, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/home/vasiliy/local/tmp/test.py", line 26, in forward
    return torch.quantize_per_tensor(x, scale, zp, self.dtype)
TypeError: quantize_per_tensor() received an invalid combination of arguments - got (Proxy, P
roxy, Proxy, torch.dtype), but expected one of:
 * (Tensor input, float scale, int zero_point, torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (Proxy, Proxy, Proxy, to
rch.dtype)
 * (tuple of Tensors tensors, Tensor scales, Tensor zero_points, torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (Proxy, Proxy, Proxy, to
rch.dtype)

```

**Comment by jamesr66a** [comment]
This works if the first argument is a tuple of tensors:
```
import torch                                                       
from torch.quantization.quantize_fx import prepare_fx, convert_fx  
from torch.fx.experimental import normalize                        
import torch.nn as nn                                                                   
                                                                   
class M(nn.Module):                                                
    def __init__(self):                                            
        super().__init__()                                         
        self.dtype = torch.quint8                                  
                                                                   
    def forward(self, x, scale, zp): 
        return torch.quantize_per_tensor((x, x), scale, zp, self.dtype) 
                                                                   
mp = torch.fx.symbolic_trace(M())  
```
