### ISSUE TITLE
Save checkpoint error

### ISSUE THREAD

**Issue by TXacs** [pytorch/pytorch#58127]
when I save the lr_scheduler.state_dict() to checkpoint, torch.save will report following error

Traceback (most recent call last):
  File "pytorch_imagenet_resnet50.py", line 526, in <module>
    save_checkpoint(epoch)
  File "pytorch_imagenet_resnet50.py", line 311, in save_checkpoint
    torch.save(state, filepath)
  File "/THL5/home/wql17/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 372, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/THL5/home/wql17/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 476, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <class 'horovod.torch.optimizer.SGD'>: attribute lookup SGD on horovod.torch.optimizer failed

I need some help to solve this problem！

**Comment by mruberry** [comment]
I wonder if this is a horovod issue? @vincentqb, have you seen anything like this?

**Comment by TXacs** [comment]
> I wonder if this is a horovod issue? @vincentqb, have you seen anything like this?

Yeah，I use the horovod, but I am not sure the error whether  comes from horovod
