### ISSUE TITLE
Mobile Android: Could not run 'aten::quantize_per_tensor' with arguments from the 'Vulkan' backend

### ISSUE THREAD

**Issue by IsCoelacanth** [pytorch/pytorch#58172]
## 🐛 Bug

When running a model with vulkan on android (converted using the mobile recipes on PyTorch Mobile page), this error happens on forward pass. Works fine when inferencing on CPU.

### Mobile Code:
```Java
try {
                    bitmap = ((BitmapDrawable)imageView.getDrawable()).getBitmap();
                    image_h = bitmap.getHeight();
                    image_w = bitmap.getWidth();

                    //resize to 416 x 416
                    bitmap = Bitmap.createScaledBitmap(bitmap, 416, 416, true);

                    module = Module.load(fetchModelFile(MainActivity.this, "mobile.pts"), Device.VULKAN);
                } catch (IOException e) {
                    finish();
                }

                //Input Tensor
                float[] mean = {0.5f, 0.5f, 0.5f};
                float[] std = {0.5f, 0.5f, 0.5f};
                final Tensor input = TensorImageUtils.bitmapToFloat32Tensor(
                        bitmap,
                        mean,
                        std
                );

//                //Calling the forward of the model to run our input
                final Tensor output = module.forward(IValue.from(input)).toTensor(); 
```

At forward this is raised:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.uwudemo, PID: 18203
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/unet_aligner_trainer/models/unet.py", line 43, in forward
        _13 = self.encoder_layer2
        _14 = self.encoder_layer1
        _15 = (self.conv1).forward((self.quant).forward(X, ), )
                                    ~~~~~~~~~~~~~~~~~~~ <--- HERE
        _16 = (_14).forward(_15, )
        _17 = (_13).forward(_16, )
      File "code/__torch__/torch/nn/quantized/modules.py", line 10, in forward
      def forward(self: __torch__.torch.nn.quantized.modules.Quantize,
        X: Tensor) -> Tensor:
        input = torch.quantize_per_tensor(X, 0.0066144033335149288, 104, 13)
                ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return input
    class DeQuantize(Module):

// stack trace of python calls //

    RuntimeError: Could not run 'aten::quantize_per_tensor' with arguments from the 'Vulkan' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::quantize_per_tensor' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].
    
    CPU: registered at aten/src/ATen/RegisterCPU.cpp:5925 [kernel]
    BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
    Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
    AutogradOther: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
    AutogradCPU: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
    AutogradCUDA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
    AutogradXLA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
    Tracer: fallthrough registered at ../torch/csrc/jit/frontend/tracer.cpp:999 [backend fallback]
    Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:250 [backend fallback]
    Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
    VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
    
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:49)
        at com.example.uwudemo.MainActivity$2.onClick(MainActivity.java:106)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Expected behavior

As per the mobile recipe, optimizing for mobile with backend set to "Vulkan" should apply all the layer optimizations needed.

## Environment
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu 18.04.3
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2 / 7.6.5
 - GPU models and configuration: 4x RTX2080Ti
 - Any other relevant information: Android Build version 30

**Comment by SS-JIA** [comment]
Unfortunately, we don't support Quantized tensors in Vulkan at the moment. We plan to support it in the future, however.

What model are you trying to run?

**Comment by IsCoelacanth** [comment]
Trying to run the unet model from torch-model-hub. In FP32 mode, are all ops supported on Vulkan? (assuming its optimized for mobile and converted to torchscript?)

```torch.hub.load('mateuszbuda/brain-segmentation-pytorch', 'unet',
    in_channels=3, out_channels=1, init_features=32, pretrained=True)```

**Comment by IsCoelacanth** [comment]
leaving the model as fp32 and running on mobles gives a new error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.uwudemo, PID: 28076
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/unet_aligner_trainer/models/unet.py", line 39, in forward
        _11 = self.encoder_layer3
        _12 = self.encoder_layer2
        _13 = (self.encoder_layer1).forward((self.conv1).forward(input, ), )
                                             ~~~~~~~~~~~~~~~~~~~ <--- HERE
        _14 = (_12).forward(_13, )
        _15 = (_11).forward(_14, )
      File "code/__torch__/torch/nn/modules/conv.py", line 9, in forward
      def forward(self: __torch__.torch.nn.modules.conv.Conv2d,
        input: Tensor) -> Tensor:
        input0 = torch._convolution(input, self.weight, None, [2, 2], [3, 3], [1, 1], False, [0, 0], 1, False, False, True, True)
                 ~~~~~~~~~~~~~~~~~~ <--- HERE
        return input0
    class ConvTranspose2d(Module):
RuntimeError: expected scalar type Float but found UNKNOWN_SCALAR
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:49)
        at com.example.uwudemo.MainActivity$2.onClick(MainActivity.java:106)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

model was converted as follows:
```
model = torch.hub.load('mateuszbuda/brain-segmentation-pytorch', 'unet', in_channels=3, out_channels=1, init_features=32, pretrained=True)
dummy = torch.rand(1, 3, 416, 416)
scripted = torch.jit.trace(model , dummy)
optimized_model= optimize_for_mobile(scripted, backend='Vulkan')
optimized_model.save('model_vulkan.pts)
```
and Uses the same code as above on android.

**Comment by SS-JIA** [comment]
Ah, unfortunately we don't have full op coverage for the Unet model yet. We're currently working on adding the final required op (`max_pool2d`). However, this error isn't related to op coverage. As a sanity test, could you try running [this model](https://www.dropbox.com/s/k0ic8vkibixnd9n/mnet_vulkan.pt?dl=0)?

If that works, I would recommend you try re-building Pytorch from source with the `USE_VULKAN=ON` flag? So

```
USE_VULKAN=ON python3 setup.py install
```

**Comment by IsCoelacanth** [comment]
The model works right away, no glitches.
I'm quite new to working with on device, by "re-building Pytorch from source with the USE_VULKAN=ON flag" you're referring to building my PyTorch install which I'm using to prepare the model for mobile right? I'm following the Vulkan recipe from (here)[https://pytorch.org/tutorials/prototype/vulkan_workflow.htm]

**Comment by SS-JIA** [comment]
Yep, rebuilding your Pytorch install.

**Comment by IsCoelacanth** [comment]
got it, Thanks!
