### ISSUE TITLE
"_amp_foreach_non_finite_check_and_unscale_cuda" not implemented for 'ComplexFloat'

### ISSUE THREAD

**Issue by 863zq** [pytorch/pytorch#58228]
## To Reproduce

1. scaler = torch.cuda.amp.GradScaler()

RuntimeError: "_amp_foreach_non_finite_check_and_unscale_cuda" not implemented for 'ComplexFloat'

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ezyang** [comment]
I feel like this particular error shouldn't be too hard to fix, although it is questionable whether or not AMP works at all on complex numbers

**Comment by 863zq** [comment]
> I feel like this particular error shouldn't be too hard to fix, although it is questionable whether or not AMP works at all on complex numbers

Yes, it's easy to fix by not using AMP. I believe AMP doesn't work on complex64 now.

**Comment by gchanan** [comment]
can you post a full reproduction?

**Comment by rouniuyizu** [comment]
> can you post a full reproduction?

I'm having the same issue on pytorch 2.0  + cuda 11.8 + python 3.8 + ubuntu 22. Following code would reproduce the error:

```bash
Traceback (most recent call last):
  File "/home/r/test/test_amp_with_complex_type.py", line 40, in <module>
    scaler.step(optimizer)  #this line of code throws error.
  File "/home/r/anaconda3/envs/test/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 366, in step
    self.unscale_(optimizer)
  File "/home/r/anaconda3/envs/test/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/home/r/anaconda3/envs/test/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 229, in _unscale_grads_
    torch._amp_foreach_non_finite_check_and_unscale_(grads,
RuntimeError: "_amp_foreach_non_finite_check_and_unscale_cuda" not implemented for 'ComplexFloat'
```

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class MiniNet(torch.nn.Module):
    def __init__(self):
        super(MiniNet, self).__init__()
        self.w = nn.Parameter(torch.rand(16, 20, 17, dtype=torch.cfloat))
        self.squeeze = nn.Linear(32, 1)
        self.o = nn.Linear(20, 3)
        self.s = nn.Softmax(dim=-1)

    def forward(self, x):
        l = x.shape[1]
        x = x.permute(0, 2, 1)
        x = torch.fft.rfft(x, dim=-1)
        x = torch.einsum("bif,iof->bof", x, self.w)
        x = torch.fft.irfft(x, n=l)
        # x = x.permute(0, 2, 1)
        x = self.squeeze(x).squeeze()
        x = self.o(x)
        logits = self.s(x)
        return logits

if __name__ == '__main__':
    model = MiniNet().cuda()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

    x = torch.rand(8, 32, 16, dtype=torch.float).cuda()
    y = torch.randint(0, 2, (8,)).long().cuda()

    scaler = torch.cuda.amp.GradScaler()

    with torch.autocast(device_type="cuda"):
        o = model(x)
        l = F.cross_entropy(o, y)

        scaler.scale(l).backward()

    scaler.step(optimizer)  #this line of code throws error.
    scaler.update()
    model.zero_grad()
```

**Comment by Snagnar** [comment]
Any updates on this? I am having the same issue, when trying to train a S5 model with mixed precision, as some of the parameters are complex floats. Would be nice if complex64 support was added to AMP.
