### ISSUE TITLE
`fmod` and `remainder`: self resized on inplace variant

### ISSUE THREAD

**Issue by krshrimali** [pytorch/pytorch#58226]
## 🐛 Bug

Failures occurs for `fmod` (on CUDA and CPU both, dtype: `float32`) and same for `remainder`. This is probably because of self being resized on inplace variant for both `fmod` and `remainder`.

## To Reproduce

1. Once https://github.com/pytorch/pytorch/pull/57941 is merged, do: `python test/test_ops.py -k fmod` after removing the skips for `test_variant_consistency_eager` in the `OpInfo` definition of `fmod` and `remainder`.

```
FAIL: test_variant_consistency_eager_fmod_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krshrimali/git/krshrimali/pytorch/torch/testing/_internal/common_utils.py", line 1033, in wrapper
    method(*args, **kwargs)
  File "/home/krshrimali/git/krshrimali/pytorch/torch/testing/_internal/common_utils.py", line 1033, in wrapper
    method(*args, **kwargs)
  File "/home/krshrimali/git/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/home/krshrimali/git/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/home/krshrimali/git/krshrimali/pytorch/test/test_ops.py", line 326, in test_variant_consistency_eager
    _test_consistency_helper(samples, variants)
  File "/home/krshrimali/git/krshrimali/pytorch/test/test_ops.py", line 310, in _test_consistency_helper
    variant_forward = variant(cloned,
AssertionError: RuntimeError not raised
```

## Additional context

Please see https://github.com/pytorch/pytorch/pull/57941.

cc: @kshitij12345 @mruberry

**Comment by krshrimali** [comment]
Sorry, a confusion caused creating this issue.
