### ISSUE TITLE
unable to cast Python instance to C++ type in .backward()

### ISSUE THREAD

**Issue by gcramer23** [pytorch/pytorch#58255]
## 🐛 Bug

I am implementing a parameter server with an average_gradient method that returns a future and is decorated with `@rpc.functions.async_execution`. The ddp_communication hook calls the parameter server and returns the future from the parameter server. In the .backward() part of the training loop an exception is thrown `RuntimeError('Unable to cast Python instance to C++ type (compile in debug mode for details)',)`.
## To Reproduce

1. Create parameter server implement a method and return a future.
2. Call the parameter server from a ddp_communication hook and return the future from the parameter server

```python

    @staticmethod
    def process_bucket(state, bucket):
        cref = state.cref
        tensor = bucket.get_tensor()
        tensors_count = len(cref.bucket_to_parameters(bucket))
        state.param_loc += tensors_count
        sparse = tensor.is_sparse
        if not cref.use_cuda_rpc:
            tensor = tensor.cpu()
        if sparse:
            tensor = cref.sparse_tensor_to_rpc_format(tensor)
        if state.batch_number > 0:
            ps = cref.ps
            ps_args = [
                cref.ps_rref,
                state.batch_number,
                state.param_loc,
                tensor
            ]
            fut = cref.send_async_request(
                state.get_key(),
                cref.ps_rref,
                ps.average_gradient,
                *ps_args
            )
        else:
            fut = cref.get_tensor_fut(bucket)
        return fut

    @staticmethod
    def hook(state, bucket):
        cref = state.cref
        tensor = bucket.get_tensor()
        tensors_count = len(cref.bucket_to_parameters(bucket))
        if tensor.is_sparse:
            return cref.process_bucket(state, bucket)
        else:
            tensor = [tensor / state.process_group_size]
            key = state.get_key()
            cref.record_hook_fut_start(key, cref.backend)
            fut = state.process_group.allreduce(tensor).get_future()
            state.param_loc += tensors_count

            def callback(fut):
                cref.record_hook_fut_end(key)
                return fut.wait()

            return fut.then(callback)
            
    @staticmethod
    @rpc.functions.async_execution
    def average_gradient(
        ps_rref,
        received_batch_number,
        param_loc,
        gradient
    ):
        self = ps_rref.local_value()
        if type(gradient) is list:
            gradient = self.sparse_rpc_format_to_tensor(gradient)
        if not self.use_cuda_rpc:
            gradient = gradient.cuda(self.rank)
        fut = torch.futures.Future()
        with self.lock:
            if self.batch_number < received_batch_number:
                self.batch_number = received_batch_number
                self.clear_batch_state()
            self.process_gradient(gradient, param_loc)
            if param_loc not in self.futures:
                self.futures[param_loc] = []
            self.futures[param_loc].append(fut)
            if len(self.futures[param_loc]) == self.trainer_count:
                self.record_straggler_end(self.param_key(param_loc))
                param_loc_avg = self.average(param_loc)
                if not self.use_cuda_rpc:
                    param_loc_avg = param_loc_avg.cpu()
                if param_loc_avg.is_sparse:
                    param_loc_avg = self.sparse_tensor_to_rpc_format(param_loc_avg)
                for cur_fut in self.futures[param_loc]:
                    cur_fut.set_result([param_loc_avg])
                self.record_batch_end(self.param_key(param_loc))
        return fut
```

```
(pytorch1) gcramer@q2-dy-p38xlarge-2:~/cluster/work/pytorch/benchmarks/distributed/rpc/parameter_server/experiment_scripts$ bash ddp_cuda_rpc.sh 
Namespace(benchmark='4', benchmark_config_path='configurations/benchmark_configurations.json', data='DummyData', data_config_path='configurations/data_configurations.json', model='DummyModelSparse', model_config_path='configurations/model_configurations.json', server='AverageCudaParameterServer', server_config_path='configurations/server_configurations.json', trainer='DdpCudaSparseDenseRpcTrainer', trainer_config_path='configurations/trainer_configurations.json')

On WorkerInfo(id=0, name=trainer0):
RuntimeError('Unable to cast Python instance to C++ type (compile in debug mode for details)',)
Traceback (most recent call last):
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/internal.py", line 193, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/launcher.py", line 76, in run_trainer
    trainer.train(model, data)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/trainers/DdpSparseRpcTrainer.py", line 155, in train
    loss.backward()
  File "/fsx/users/gcramer/work/pytorch/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/fsx/users/gcramer/work/pytorch/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

On WorkerInfo(id=1, name=trainer1):
RuntimeError('Unable to cast Python instance to C++ type (compile in debug mode for details)',)
Traceback (most recent call last):
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/internal.py", line 193, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/launcher.py", line 76, in run_trainer
    trainer.train(model, data)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/trainers/DdpSparseRpcTrainer.py", line 155, in train
    loss.backward()
  File "/fsx/users/gcramer/work/pytorch/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/fsx/users/gcramer/work/pytorch/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

[W tensorpipe_agent.cpp:843] RPC agent for trainer0 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:843] RPC agent for trainer1 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:843] RPC agent for ps2 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:843] RPC agent for ps2 encountered error when reading incoming request from trainer0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:843] RPC agent for ps2 encountered error when reading incoming request from trainer1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Traceback (most recent call last):
  File "launcher.py", line 361, in <module>
    main()
  File "launcher.py", line 356, in main
    join=True
  File "/fsx/users/gcramer/work/pytorch/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/fsx/users/gcramer/work/pytorch/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/fsx/users/gcramer/work/pytorch/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/fsx/users/gcramer/work/pytorch/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/launcher.py", line 191, in run_benchmark
    run_master(rank, model, data, config, rpc_backend_options)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/launcher.py", line 169, in run_master
    config, model, train_data, ps_rrefs
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/launcher.py", line 116, in benchmark_warmup
    fut.wait()
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/internal.py", line 207, in _handle_exception
    raise result.exception_type(result.msg.encode("utf-8").decode("unicode_escape"))
RuntimeError: On WorkerInfo(id=0, name=trainer0):
RuntimeError('Unable to cast Python instance to C++ type (compile in debug mode for details)',)
Traceback (most recent call last):
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/internal.py", line 193, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/launcher.py", line 76, in run_trainer
    trainer.train(model, data)
  File "/fsx/users/gcramer/work/pytorch/benchmarks/distributed/rpc/parameter_server/trainers/DdpSparseRpcTrainer.py", line 155, in train
    loss.backward()
  File "/fsx/users/gcramer/work/pytorch/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/fsx/users/gcramer/work/pytorch/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

## Expected behavior

the future returned in the ddp_communication hook is processed, and the gradients are updated.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0a0+gite4b00b2
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0a0+gitc927584
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.2.0           h726a3e6_389    conda-forge
[conda] mkl-include               2021.2.0           h726a3e6_389    conda-forge
[conda] numpy                     1.19.2           py36h6163131_0  
[conda] numpy-base                1.19.2           py36h75fe3a5_0  
[conda] torch                     1.9.0a0+gitc927584           dev_0    <develop>
```

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by SciPioneer** [comment]
I guess you have a bug in the hook:
```
            def callback(fut):
                cref.record_hook_fut_end(key)
                return fut.wait()
```

Can you try to change `fut.wait()` in your hook to ` fut.value()[0]`?

Additionally, it seems that this callback does not have any dependency on the input future. Is `cref.record_hook_fut_end(key)` mainly used for profiling?

**Comment by gcramer23** [comment]
@SciPioneer that hook works as intended. the problem is the return from the process_bucket method
```
    @staticmethod
    def process_bucket(state, bucket):
        cref = state.cref
        tensor = bucket.get_tensor()
        tensors_count = len(cref.bucket_to_parameters(bucket))
        state.param_loc += tensors_count
        sparse = tensor.is_sparse
        if not cref.use_cuda_rpc:
            tensor = tensor.cpu()
        if sparse:
            tensor = cref.sparse_tensor_to_rpc_format(tensor)
        if state.batch_number > 0:
            ps = cref.ps
            ps_args = [
                cref.ps_rref,
                state.batch_number,
                state.param_loc,
                tensor
            ]
            fut = cref.send_async_request(
                state.get_key(),
                cref.ps_rref,
                ps.average_gradient,
                *ps_args
            )
        else:
            fut = cref.get_tensor_fut(bucket)
        return fut
```

I tried adding a callback to return the `fut.value()[0]`
```
            fut = cref.send_async_request(
                state.get_key(),
                cref.ps_rref,
                ps.average_gradient,
                *ps_args
            )
            def callback(fut):
                return fut.value()[0]
            return fut.then(callback)
```
it still produces the same `RuntimeError: Unable to cast Python instance to C++ type `

**Comment by gcramer23** [comment]
> cref.record_hook_fut_end(key) mainly used for profiling

yes, that is used to measure communication and computation time for the bucket

**Comment by SciPioneer** [comment]
> @SciPioneer that hook works as intended. the problem is the return from the process_bucket method
> 
> ```python
>     @staticmethod
>     def process_bucket(state, bucket):
>         cref = state.cref
>         tensor = bucket.get_tensor()
>         tensors_count = len(cref.bucket_to_parameters(bucket))
>         sparse = tensor.is_sparse
>         if not cref.use_cuda_rpc:
>             tensor = tensor.cpu()
>         if sparse:
>             tensor = cref.sparse_tensor_to_rpc_format(tensor)
>         if state.batch_number > 0:
>             ps = cref.ps
>             ps_args = [
>                 cref.ps_rref,
>                 state.batch_number,
>                 state.param_loc,
>                 tensor
>             ]
>             fut = cref.send_async_request(
>                 state.get_key(),
>                 cref.ps_rref,
>                 ps.average_gradient,
>                 *ps_args
>             )
>         else:
>             fut = cref.get_tensor_fut(bucket)
>         return fut
> ```
> 
> I tried adding a callback to return the `fut.value()[0]`
> 
> ```python
>             fut = cref.send_async_request(
>                 state.get_key(),
>                 cref.ps_rref,
>                 ps.average_gradient,
>                 *ps_args
>             )
>             def callback(fut):
>                 return fut.value()[0]
>             return fut.then(callback)
> ```
> 
> it still produces the same `RuntimeError: Unable to cast Python instance to C++ type `

Which callback raises this runtime error?

Before the return statement, can you print out `type(ret)`, where `ret` could be `fut.value[0]`, or `fut.then(callback)`?

**Comment by gcramer23** [comment]
I found the bug. My fault,  to send sparse tensors using rpc, I convert the tensor to a list containing indices, values, and size. The future being returned from the parameter server for sparse layers contained a list, not a tensor. I converted the sparse format to tensor in the callback and got it working. 

example of code that works
```python
    @staticmethod
    def process_bucket(state, bucket):
        cref = state.cref
        tensor = bucket.get_tensor()
        tensors_count = len(cref.bucket_to_parameters(bucket))
        sparse = tensor.is_sparse
        if not cref.use_cuda_rpc:
            tensor = tensor.cpu()
        if sparse:
            tensor = cref.sparse_tensor_to_rpc_format(tensor)
        ps = cref.ps
        ps_args = [
            cref.ps_rref,
            state.batch_number,
            state.param_loc,
            tensor
        ]
        fut = cref.send_async_request(
            state.get_key(),
            cref.ps_rref,
            ps.average_gradient,
            *ps_args
        )
        state.param_loc += tensors_count

        def callback(fut):
            tensor = fut.wait()
            if type(tensor) is list:
                tensor = cref.sparse_rpc_format_to_tensor(tensor)
            if not cref.use_cuda_rpc:
                tensor = tensor.cuda(cref.rank)
            return [tensor]

        return fut.then(callback)
```

**Comment by gcramer23** [comment]
> Which callback raises this runtime error?

it was the callback in the process_bucket method when the future contained a list representing a sparse tensor.

> Before the return statement, can you print out type(ret), where ret could be fut.value[0], or fut.then(callback)?

tensor for dense layers. list for sparse layers.
