### ISSUE TITLE
The `word_language_model` example script seems to not work with RocM

### ISSUE THREAD

**Issue by ChristopherKing42** [pytorch/pytorch#58374]
## Issue description

The `word_language_model` example script seems to not work with RocM.

## Code example

```
cd examples/word_language_model
python3 main.py
```

The error:
```
terminate called after throwing an instance of 'c10::Error'
  what():  HIP error: hipErrorNoDevice
Exception raised from deviceCount at /pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:98 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5ce5fdc7a2 in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f5ce5fd9b2b in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x59361f (0x7f5ce69f161f in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_hip.so)
frame #3: torch::autograd::Engine::start_device_threads() + 0x43a (0x7f5d1f83c68a in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x1247f (0x7f5d30f5647f in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #5: torch::autograd::Engine::initialize_device_threads_pool() + 0xcc (0x7f5d1f8388cc in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x32 (0x7f5d1f83ff22 in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x3c (0x7f5d2edf0c7c in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x8e3 (0x7f5d1f83ede3 in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x56 (0x7f5d2edf0b16 in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: THPEngine_run_backward(_object*, _object*, _object*) + 0xd3a (0x7f5d2edf1a4a in /home/christopher/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: python3() [0x67d5a1]
frame #25: python3() [0x67d61f]
frame #30: __libc_start_main + 0xf3 (0x7f5d30f8e0b3 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

## System Info

Collecting environment information...
PyTorch version: 1.8.1+rocm4.0.1
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.0.20496-4f163c68

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: []
MIOpen runtime version: []

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.1+rocm4.0.1
[pip3] torchvision==0.9.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by jeffdaily** [comment]
Which AMD GPU are you trying to run on?  Why is your collect_env.py not reporting HIP or MIOpen versions?  Are you attempting to run the example using the gpu device `python main.py --cuda`  (this is also how you run on AMD gpus for ROCm builds).  Or are you running the example using a torch+rocm build, but intend to run on CPU only and this is what you're reporting as failing?

**Comment by ChristopherKing42** [comment]
Ah, okay I think the issue is on my or `RocM`s end. When I run with `python3 main.py --cuda` it gives the following error: ```
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    train_data = batchify(corpus.train, args.batch_size)
  File "main.py", line 89, in batchify
    return data.to(device)
  File "/home/christopher/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```
and indeed my GPU is the *AMD® Radeon(tm) vega 8 graphics*, which apparently has problems with RocM. I think this issue can be closed then since its not related to pytorch? A more helpful error message when running without the `--cuda` flag would be nice though.
