### ISSUE TITLE
test_ddp_hook_parity_powerSGD fails on Gloo and MPI backends

### ISSUE THREAD

**Issue by SciPioneer** [pytorch/pytorch#58467]
## 🐛 Bug

DDP communication hook should be supported on Gloo and MPI backends after #42048 is resolved. However, `test_ddp_hook_parity_powerSGD` still fails on Gloo backend.

## To Reproduce

1. Remove the following decorator in `test_ddp_hook_parity_powerSGD` of `distributed_test.py`:
```
        @unittest.skipIf(
            BACKEND != "nccl",
            "Only NCCL backend supports DDP communication hook",
        )
```

2. Run the following command on a devgpu:
`buck test @mode/dev-nosan caffe2/test/distributed:distributed_gloo_fork -- test_ddp_hook_parity_powerSGD`

The failure occurs at L511 of `torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py`:
`state.q_memory_dict[bucket_index] = fut.value()[0].div_(world_size)`

It triggers the following runtime error:
`RuntimeError: [enforce fail at gloo/allreduce.cc:105] opts.elements > 0. `

## Error Message

```
Traceback (most recent call last):
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 509, in run_test
    getattr(self, test_name)()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 393, in wrapper
    fn()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 93, in wrapper
    return func(*args, **kwargs)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 242, in wrapper
    return func(*args, **kwargs)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/distributed/distributed_test.py", line 3437, in test_ddp_hook_parity_powerSGD
    self._test_ddp_hook_parity(state=powersgd_state, hook=powerSGD.powerSGD_hook)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/distributed/distributed_test.py", line 3394, in _test_ddp_hook_parity
    loss_hook.backward()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Got the following error when running the callback: RuntimeError: Got the following error when running the callback: RuntimeError: Got the following error when running the callback: RuntimeError: [enforce fail at gloo/allreduce.cc:105] opts.elements > 0. 

At:
  /data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py(481): unpack_uncompressed_tensors_and_allreduce_ps


At:
  /data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py(489): compute_qs


At:
  /data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py(511): decompress


  File "/usr/local/fbcode/platform009/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/local/fbcode/platform009/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/local/fbcode/platform009/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 391, in wrapper
    self._join_processes(fn)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 583, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/distributed_gloo_fork#binary,link-tree/torch/testing/_internal/common_distributed.py", line 626, in _check_return_codes
    raise RuntimeError(error)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by agolynski** [comment]
@SciPioneer  Seems like it means that we are giving trivial work to allreduce (nothing to reduce)? If so, it also happens for other backends, it's just we never caught it (gloo does the explicit check).

**Comment by SciPioneer** [comment]
> @SciPioneer Seems like it means that we are giving trivial work to allreduce (nothing to reduce)? If so, it also happens for other backends, it's just we never caught it (gloo does the explicit check).

Comm hook does not seem to work on MPI backend either. Actually #58444 that I submitted yesterday got reverted, because all the comm hook tests on MPI backend failed on CI:
https://app.circleci.com/pipelines/github/pytorch/pytorch/323731/workflows/784f6e8d-2137-4142-b2ba-5158ae47bb3b/jobs/13540765

**Comment by agolynski** [comment]
> > @SciPioneer Seems like it means that we are giving trivial work to allreduce (nothing to reduce)? If so, it also happens for other backends, it's just we never caught it (gloo does the explicit check).
> 
> Comm hook does not seem to work on MPI backend either. Actually #58444 that I submitted yesterday got reverted, because all the comm hook tests on MPI backend failed on CI:
> https://app.circleci.com/pipelines/github/pytorch/pytorch/323731/workflows/784f6e8d-2137-4142-b2ba-5158ae47bb3b/jobs/13540765

Right now we don't have any CUDA aware tests for MPI and proper setup for such tests (e.g. see https://github.com/pytorch/pytorch/issues/57547), we can test MPI with CPU model as was done for test_accumulate_gradients_no_sync*

**Comment by agolynski** [comment]
2 action items here:
1) add testing for MPI via CPU model
2) discuss whether we should fail on empty inputs (current GLOO) or give warning or do silent noop (NCCL)

**Comment by SciPioneer** [comment]
A bit more context on PowerSGD part. This gradient compression algorithm divides a list of tensors into two groups, one group contains only high-dimensional tensors to compress, and the other contains only 1D tensors to skip compression. Each group of tensors needs to run allreduce and returns a future after batching the tensors. These two futures will need to be chained together.

The tricky part is that, the input tensor list (as a batch for gradient averaging) may only have high-dimensional tensors or 1D tensors, and hence one reduce may face an empty input.

If allreduce cannot accept an empty input and behave like a no-op (similar to `torch.empty()` `torch.zeros()` that can allow creating an empty tensor), then we have to add extra complexity to allow skipping some parts in the future chain at runtime.

**Comment by SciPioneer** [comment]
Closes this bug, since the test is already re-enabled after https://github.com/pytorch/pytorch/pull/58882.
