### ISSUE TITLE
RuntimeError: mkldnn_linear_backward: weight needs to be a dense tensor

### ISSUE THREAD

**Issue by C-Underkoffler** [pytorch/pytorch#58508]
## 🐛 Bug

Cannot call loss.backward() for simple binary classification net with sigmoid when using MKLDNN utilities.

Am I not understanding the poper way to put the model weights back into a dense memory format? I thought given the [__getstate__ of each MKLDNN function ](https://github.com/pytorch/pytorch/blob/master/torch/utils/mkldnn.py) the weights would be returned as weights.to_dense() already?

## To Reproduce

Code:
```
import torch
import torch.nn as nn
from torch.utils import mkldnn as mkldnn_utils
import time

print(f'Pytorch version : {torch.__version__}')
print(*torch.__config__.show().split("\n"), sep="\n")


class Toy1(nn.Module):
    """
    Call output.to_dense() BEFORE sigmoid
    """
    def __init__(self, batch_dim, use_mkldnn=False):
        super(Toy1, self).__init__()
        self.use_mkldnn = use_mkldnn
        self.enc = nn.Linear(batch_dim, 1)
        self.sig = nn.Sigmoid()

    def forward(self, x):
        x = self.enc(x)

        if self.use_mkldnn:
            x = x.to_dense()

        x = self.sig(x)
        return x


def run_toy(net, batch_dim, train, use_mkldnn, iter_cnt=100, batch_size=2):
    start_time = time.time()

    if train:
        net.train()
    else:
        net.eval()

    if use_mkldnn:
        net = mkldnn_utils.to_mkldnn(net)

    for i in range(iter_cnt):  # fake batch iteration
        batch = torch.rand(batch_size, batch_dim)  # fake batch
        if use_mkldnn:
            batch = batch.to_mkldnn()

        if train:
            output_batch = net(batch)

            loss_func = nn.BCEWithLogitsLoss()
            loss = loss_func(output_batch, torch.randn(batch_size, 1))
            loss.sum().backward()

        else:
            with torch.no_grad():
                output_batch = net(batch)

    print(f'Time: {time.time() - start_time}s')


batch_dim = 13
use_mkldnn = True

# Toy1 Train
print('Train Toy1')
run_toy(
    net=Toy1(batch_dim=batch_dim, use_mkldnn=use_mkldnn),
    batch_dim=batch_dim,
    train=True,
    use_mkldnn=use_mkldnn,
)
```

Output:
```
Pytorch version : 1.8.1
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

Train Toy1
Traceback (most recent call last):
  File "/home/ec2-user/ChempropLearner/simple_net.py", line 84, in <module>
    run_toy(
  File "/home/ec2-user/ChempropLearner/simple_net.py", line 70, in run_toy
    loss.sum().backward()
  File "/home/ec2-user/anaconda3/envs/chemproplearner/lib/python3.9/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ec2-user/anaconda3/envs/chemproplearner/lib/python3.9/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: mkldnn_linear_backward: weight needs to be a dense tensor
```

## Expected behavior

Loss is backpropogated through net after training.

## Environment

```
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12)
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: glibc-2.26

Python version: 3.9 (64-bit runtime)
Python platform: Linux-4.14.219-161.340.amzn2.x86_64-x86_64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1
[pip3] torchvision==0.9.1
[conda] blas                      2.109                       mkl    conda-forge
[conda] blas-devel                3.9.0                     9_mkl    conda-forge
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] libblas                   3.9.0                     9_mkl    conda-forge
[conda] libcblas                  3.9.0                     9_mkl    conda-forge
[conda] liblapack                 3.9.0                     9_mkl    conda-forge
[conda] liblapacke                3.9.0                     9_mkl    conda-forge
[conda] mkl                       2021.2.0           h726a3e6_389    conda-forge
[conda] mkl-devel                 2021.2.0           ha770c72_390    conda-forge
[conda] mkl-include               2021.2.0           h726a3e6_389    conda-forge
[conda] numpy                     1.20.2           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.8.1           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchvision               0.9.1                py39_cu111    pytorch
```

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by XiaobingSuper** [comment]
@C-Underkoffler, for training, the model should not call **mkldnn_utils.to_mkldnn** to convert the model to MKLDNN model, the one reason is that some optimizer not suuport MKLDNN tensor input,, so for training, you just need convert input to MKLDNN, which not need gradient update:
```
class MyModel(nn.Module):
    """
    Call output.to_dense() BEFORE sigmoid
    """
    def __init__(self):
        super(Toy1, self).__init__(batch_dim)
        self.linear = nn.Linear(batch_dim, 1)
        self.sig = nn.Sigmoid()

    def forward(self, x):
        x = self.linear (x)
        x = self.sig(x)
        return x

model  = MyModel(3).train()
x = torch.randn(3, 3).to_mkldnn()
y = model(x).to_dense().sum()
y.backward()
```

**Comment by C-Underkoffler** [comment]
Adapted from above:
```
class MyModel(nn.Module):
    def __init__(self, batch_dim):
        super(MyModel, self).__init__()
        self.linear = nn.Linear(batch_dim, 1)
        self.sig = nn.Sigmoid()

    def forward(self, x):
        x = self.linear(x)
        x = self.sig(x)
        return x

model  = MyModel(3).train()
x = torch.randn(3, 3).to_mkldnn()
y = model(x).to_dense()
loss_func = nn.BCEWithLogitsLoss()
loss_func(y, torch.randn(3, 1)).sum().backward()
```
Error @ backward():
```
RuntimeError: Could not run 'aten::sigmoid_backward' with arguments from the 'MkldnnCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build).
```

I've seen this before (also with a `net = mkldnn_utils.to_mkldnn(net)` example) hence why I put the x.to_dense() before the sigmoid in my original forward call.

But anyways, it seems like if the model can't use the MKLDNN modules then it doesn't make sense to change the input to the MKLDNN format (unless I am misunderstanding where the performance improvement comes from). Given this and the lack support from some optimizers, I probably just won't use the MKLDNN utils while training then.

**Comment by XiaobingSuper** [comment]
MKlDNN sigmoid backward path is not enabled now, so need add **to_dense** before sigmoid for  training.

**Comment by C-Underkoffler** [comment]
Yes, and then loss.backward() fails with the error in my first example (which calls `x = x.to_dense()` before the sigmoid)
